### ISSUE TITLE
开发者文档配置项页面bug

### ISSUE THREAD

**Issue by meifu2027** [apache/echarts#10000]
### Version
4.2.1-rc1

### Reproduction link
[https://echarts.baidu.com/option.html](https://echarts.baidu.com/option.html)

### Steps to reproduce
打开链接，在查询框输入 color ，然后回车

### What is expected?
正常返回结果并可操作

### What is actually happening?
正常返回结果，页面无响应；

----------
chrom浏览器

**Comment by Ovilia** [comment]
Reproduced. Page is not responding. @100pah Please help to check.
