### ISSUE TITLE
折线图拐点hover API配置

### ISSUE THREAD

**Issue by louieaa** [apache/echarts#10003]
### What problem does this feature solve?
多条折线时，鼠标hover在某个拐点时，拐点样式变化，与另外一条的折线拐点不一致。
提高用户体验。

### What does the proposed API look like?
可配置鼠标悬浮拐点样式
symbolHoverStyle:{
    size: 10,
    background: '#f60',
    border:'1px solid #fff'
}

**Comment by louieaa** [comment]
![echart](https://user-images.githubusercontent.com/42113246/53483847-689f2180-3abd-11e9-98dd-b80982aeedb9.gif)

**Comment by louieaa** [comment]
![image](https://user-images.githubusercontent.com/42113246/53483951-9f753780-3abd-11e9-936e-307504e8b282.png)

**Comment by Ovilia** [comment]
Sounds reasonable. Maybe we should provide something like `emphasis.symbolSize` and other attributes for symbols.
