### ISSUE TITLE
Tooltip are not created inside the canvas

### ISSUE THREAD

**Issue by aandrieux** [apache/echarts#10019]
### Version
4.2.1-rc1

### Steps to reproduce
For a 3D graphic section "grid3D" set tooltip renderMode to "richText" and Implement a "formatter" function

### What is expected?
Tooltips should be created inside canvas as the chart

### What is actually happening?
Tooltip are not created in the canvas but outside

---
Yet in the documentation it is specified that this option must make the tooltip inside the canvas
https://ecomfe.github.io/echarts-doc/public/en/option.html#tooltip.renderMode
"It can also set to be 'richText' so that the tooltip will be rendered inside Canvas (SVG rich text is not implemented yet)."

**Comment by Ovilia** [comment]
Hi. @aandrieux Can you provide a demo for your question?

**Comment by aandrieux** [comment]
Hi Ovilia,
Thank you for your interest in my request. It's hard to give you an example live, but I enclose a screenshot and hope that you understand my indications.

![screen-01](https://user-images.githubusercontent.com/26142959/53630619-c1330380-3c10-11e9-92c4-fffd8bbbd12e.png)
![screen-02](https://user-images.githubusercontent.com/26142959/53630678-eb84c100-3c10-11e9-89b1-08561824fc80.png)

You can reproduce the same behavior on this model : 
https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar3d-punch-card&gl=1
and add these lines
tooltip: {
            renderMode:'richText',
            textStyle: {
                fontSize: 30
            },
        }

I expect the tooltip to be created inside the canvas as explained in the documentation "It can also set to be 'richText' so that the tooltip will be rendered inside Canvas" :(

Thank you

**Comment by plainheart** [comment]
I have tried this example, but not found that tooltip is not rendered inside canvas.
![image](https://user-images.githubusercontent.com/26999792/53678238-45f84d00-3cf7-11e9-8132-9cd6b7f3ece4.png)

**Comment by aandrieux** [comment]
Hi, 
In the documentaton it is written "Inside" I do not expect to have a second canvas. For me "Inside" means that the tooltip is created in the same canvas as the graphic ... no?

![inside](https://user-images.githubusercontent.com/26142959/53874232-4861ec00-4002-11e9-98ad-6e39560b88e4.png)
