### ISSUE TITLE
折线图标记点

### ISSUE THREAD

**Issue by louieaa** [apache/echarts#10025]
### What problem does this feature solve?
满足更多的业务需求，突出不同的数据点

### What does the proposed API look like?
1、数据标记点鼠标hover离开，但未离开标线，保持hover状态
2、数据标记点鼠标hover离开，离开标线，恢复默认大小

![echart](https://user-images.githubusercontent.com/42113246/53621839-df116000-3c32-11e9-98fd-8b805fd894f2.gif)

**Comment by louieaa** [comment]
![1551423802 1](https://user-images.githubusercontent.com/42113246/53621936-30215400-3c33-11e9-996a-a2368798df85.jpg)

**Comment by susiwen8** [comment]
Duplicate #10003
