### ISSUE TITLE
雷达图name使用富文本，tooltip会显示多余样式名称‘{a|....}’

### ISSUE THREAD

**Issue by MarvelSQ** [apache/echarts#10024]
### Version
4.2.1-rc.2

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=radar](https://echarts.baidu.com/examples/editor.html?c=radar)

### Steps to reproduce
复制option到在线编辑器中
```javascript
const option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           },
           formatter:'{a|{value}}',
           rich:{
               a:{
                   align:'center'
               }
           }
        },
        indicator: [
           { name: '销售\n（sales）', max: 6500},
           { name: '管理\n（Administration）', max: 16000},
           { name: '信息\n技术（Information Techology）', max: 30000},
           { name: '客服\n（Customer Support）', max: 38000},
           { name: '研发\n（Development）', max: 52000},
           { name: '市场\n（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};
```

### What is expected?
tooltip中不存在样式名称

预算分配（Allocated Budget）
销售（sales）:123
管理（Administration）:123
...

### What is actually happening?
tooltip 类别名称出现样式名称

预算分配（Allocated Budget）
{a|销售（sales）}:123
{a|管理（Administration）}:123
...

![screen shot 2019-03-01 at 2 06 14 pm](https://user-images.githubusercontent.com/14308293/53620510-35c86b00-3c2e-11e9-9910-52f69aabb72d.png)

**Comment by Ovilia** [comment]
这个不是 bug，`formatter` 和 `rich` 不能这么配合着用罢了……

**Comment by MarvelSQ** [comment]
@Ovilia 请问如何能实现指示器名称的居中？
目前name的style中没有提供`align`属性。
tooltip中的`formatter`也不能访问指示器数据。
目前的解决方案是直接通过tooltip的formatter修改提示内容

https://www.echartsjs.com/examples/editor.html?c=bar-rich-text

在这个例子中，y轴的label也使用了富文本，tooltip修改`item`触发时，也不会出现样式名称

**Comment by Ovilia** [comment]
@100pah 帮忙看下这个是不是 bug

**Comment by MarvelSQ** [comment]
radar中的指示器和折线图的`category`轴是具有类似性质的东西，但是在tooltip的表现方式却不相同

**Comment by want2012** [comment]
我也有一模一样的问题，最后如何解决呢

**Comment by JohnVSD** [comment]
渲染方式改成canvas试试

**Comment by isaacqian** [comment]
@MarvelSQ hi, do you solve this problem later?
