### ISSUE TITLE
主题河流图的emphasis的label无法显示

### ISSUE THREAD

**Issue by olivia-ymy** [apache/echarts#10031]
### Version
4.1.0-rc.2

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x2vM3rJKIA&v=1](https://gallery.echartsjs.com/editor.html?c=x2vM3rJKIA&v=1)

### Steps to reproduce
设置label:{show:false},emphasis:{label:{show:true}}

### What is expected?
正常情况下不显示label，鼠标移到某一系列后显示该系列的label

### What is actually happening?
一直不显示

**Comment by yufeng04** [comment]
Compare to the bar chart, I find that the themeRiver chart don't  set emphasisStyle of label. 
The specific function is: 

![c27d40b645a0e800c1fada438](https://user-images.githubusercontent.com/22974511/55878496-25ad8f00-5bcf-11e9-8eeb-470bbce8fca7.png)
