### ISSUE TITLE
希望主题河流图的tooltip改进

### ISSUE THREAD

**Issue by olivia-ymy** [apache/echarts#10030]
### What problem does this feature solve?
目前主题河流图只能支持tooltip的trigger为axis的情况，当改trigger为item时就无法显示tooltip。即目前是每一列（同一时间点）共用一个tooltip，能否支持每个一条河流共用一个tooltip或者每一个点有对应的tooltip。（因为当河流较多时，放到一点上出来一列后，还是难以找到这一点的具体相关信息）

### What does the proposed API look like?
tooltip:{
trigger:'item',
formatter:{
...
}
}

**Comment by Ovilia** [comment]
可以定制 formatter 控制显示内容，似乎足够满足你的需求？

**Comment by olivia-ymy** [comment]
> 可以定制 formatter 控制显示内容，似乎足够满足你的需求？

通过formmatter是可以控制显示内容，但是现在我无法获得鼠标悬停的单条河流的变量，大概相当于只能得到鼠标悬停的横坐标
