### ISSUE TITLE
xAxis.data 传入一个长度只有1的数组时，控制台报错

### ISSUE THREAD

**Issue by fiveLucky** [apache/echarts#10034]
### Version
4.1.0-release

### Steps to reproduce
在这个官方示例中（ https://echarts.baidu.com/examples/editor.html?c=line-aqi ），将function里面的data重新定义为 data = [ [ '2019-03-02' , 123 ] ] ,然后运行，控制台报错   

### What is expected?
绘制一个点

### What is actually happening?
控制台报错，并且没有绘制任何内容

---
起初我在想，是不是data必须传入length大于1的数据，因为最少两个点才能绘制一条线，但是业务需要显示一个点时，echarts该如何满足，求指教

**Comment by Ovilia** [comment]
似乎是 dataZoom 引起的 bug

**Comment by SylviaZ89** [comment]
data长度是1时，似乎需要startValue等于'2019-03-02' ，或者改用start
