### ISSUE TITLE
能改dataZoom控制点的两个图标吗

### ISSUE THREAD

**Issue by yoonasy** [apache/echarts#10058]
### Version
4.2.1-rc1

### Steps to reproduce
```
          dataZoom: [
            {
              type: 'slider',
              show: true,
              // start: 0, // 选中区域开始位置
              // end: 40, // 选中区域结束位置，可能需要根据数据多少计算
              height: 20,
              fillerColor: 'red', // 选择范围的颜色
              showDataShadow: false, // 是否显示数据阴影
              // showDetail: false, // 拖拽时是否显示详细数值信息
              backgroundColor: '#F2F7FA', // 两边未选中区域的颜色
              borderColor: '#F2F7FA', // 边框颜色
              filterMode: 'filter',
              handleIcon: 'image://https://mcache.yizhuan5.com/js/yz/yzstatic/index1225/img/circle-blue.png',
              handleSize: '100%' // 滑动条左右二个滚动条大小,设为0即隐藏
            }
          ]
```

![](http://39.108.221.241/temp.png)

### What is expected?
希望可以两个控制点都可以分开替换图标

### What is actually happening?
只能通过handleIcon 更改一个

---
·

**Comment by Ovilia** [comment]
请问什么情况下有这个需求？

**Comment by yoonasy** [comment]
@Ovilia  产品和设计师沟通做的    说要两边不一样图标

**Comment by Ovilia** [comment]
@yoonasy 方便提供设计稿吗？
如果是 [handleIcon](https://echarts.baidu.com/option.html#dataZoom-slider.handleIcon) [handleSize](https://echarts.baidu.com/option.html#dataZoom-slider.handleSize) 不同还比较好办，让这两者支持数组形式就好了，但是 [handleStyle](https://echarts.baidu.com/option.html#dataZoom-slider.handleStyle) 变成数组可能就不太合适。

**Comment by yoonasy** [comment]
![image](https://user-images.githubusercontent.com/24489180/57721207-3792be00-76b6-11e9-91f9-29e452d80ed8.png)
@Ovilia  非常抱歉现在才看到， 这就是设计稿上的图标 现在项目也黄了0 0~
