### ISSUE TITLE
echart 4.1.0 3D地图  如何设置飞线的弧度

### ISSUE THREAD

**Issue by REGGEN8** [apache/echarts#10060]
### Version
4.1.0-release

### Steps to reproduce
代码设置如下   
{//配置路径
            type: 'lines3D',
            coordinateSystem: 'geo3D',
            polyline: 'true',
            blendMode: 'lighter',
            zlevel: 102,
            effect: {
                show: true,
                period: 4,
                trailWidth: 10,
                trailOpacity: 0.5,
                trailLength: 0.2,
                constantSpeed: 5,
//                symbol: 'arrow',
                symbolSize: 10,
                trailColor:'#ff1d12'
            },
//            lineStyle: {
//                color: '#FFB728',
//                opacity: 0.8,
//                width: 1.5
//            },
                // 线条样式
                lineStyle: {
                    normal: {
                        width: 5,
                        opacity: 0.8,
                        curveness: 0.2
                    }
                },
            data: [
                {
                    coords: [[107.1826, 34.3433], [113.5107, 23.2196]],
                    // 数据值
                    value: 100,
                    // 数据名
                    name: '宝鸡',
                    // 线条样式
                    lineStyle: {

                    },
                }, {
                    coords: [[114.3896, 30.6628], [113.5107, 23.2196]],
                    // 数据值
                    value: 50,
                    // 数据名
                    name: '武汉',
                    // 线条样式
                    lineStyle: {

                    },
                }
            ]
        }

### What is expected?
希望3D 地图上飞线有一个弧度  

### What is actually happening?
显示的一个没有弧度的点到点的线

**Comment by Ovilia** [comment]
似乎没有看到相关配置项，@pissang 帮忙看下
