### ISSUE TITLE
在柱状图中设置markArea报错

### ISSUE THREAD

**Issue by ctc1995** [apache/echarts#10074]
### Version
2.0
### Steps to reproduce
```js
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar',
        markLine: {
            symbol: 'none',
            lineStyle: {
                color: 'blue',
                type: 'solid',
                width: 4,
            },
            data: [
                    [{
                        x: '20%',
                        y: '42.5%'
                    },
                    {
                        x: '22.6%',
                        y: '11.4%'
                    }],
                    [{
                        x: '31.8%',
                        y: '11.4%'
                    },
                    {
                        x: '34%',
                        y: '31%'
                    }], // 自己去计算百分比
                ]
        },
        markArea: {
            data: [
                [
                    {
                        x: '20%',
                        y: '42.5%'
                    },
                    {
                        x: '22.6%',
                        y: '11.4%'
                    }
                ]
            ]
        }
    }]
};
```
这段代码，在运行时会报如下错误：
Cannot read property '0' of undefined
我想要用echarts绘制一个带有连接线的柱状图。我通过markLine可以绘制连接线，但是我需要在连接区域写样式，并且加入一些标签说明。当我定义markArea时发生了上述报错。
请问我该如何设置markArea？

### What is expected?
期望获得一个梯形区域

### What is actually happening?
报错！
Cannot read property '0' of undefined

**Comment by ctc1995** [comment]
@pissang 你好！请问一下，这个是什么原因呢？

**Comment by ctc1995** [comment]
@pissang 非常抱歉，我没有将错误贴出来。
![image](https://user-images.githubusercontent.com/17734754/54813289-2df96500-4cc8-11e9-8860-e11cec7d3b3e.png)
报这个错误，你看是否有帮助。
我代码中的markArea是这样的。
`
markArea: {
                    silent: true,
                    data: [
                        [
                            { name: '平均值到最大值', type: 'average' },
                            { type: 'max' }
                        ],

                        [
                            { name: '两个坐标之间的标域', coord: [10, 20] },
                            { coord: [20, 30] }
                        ],
                        [
                            { name: '60分到80分', yAxis: 60 },
                            { yAxis: 80 }
                        ],
                        [
                            { name: '所有数据范围区间', coord: ['min', 'min'] },
                            { coord: ['max', 'max'] }
                        ],
                        [
                            {
                                name: '两个屏幕坐标之间的标域',
                                x: 100,
                                y: 100
                            }, {
                                x: '90%',
                                y: '10%'
                            }
                        ]
                    ]
                },
`

**Comment by ctc1995** [comment]
> @pissang 非常抱歉，我没有将错误贴出来。
> ![image](https://user-images.githubusercontent.com/17734754/54813289-2df96500-4cc8-11e9-8860-e11cec7d3b3e.png)
> 报这个错误，你看是否有帮助。
> 我代码中的markArea是这样的。
> 
> ```
> markArea: {
>   silent: true,
>   data: [
>     [
>       { name: '平均值到最大值', type: 'average' },
>       { type: 'max' }
>     ],
>     [
>       { name: '两个坐标之间的标域', coord: [10, 20] },
>       { coord: [20, 30] }
>     ],
>     [
>       { name: '60分到80分', yAxis: 60 },
>       { yAxis: 80 }
>     ],
>     [
>       { name: '所有数据范围区间', coord: ['min', 'min'] },
>       { coord: ['max', 'max'] }
>     ],
>     [
>       {
>         name: '两个屏幕坐标之间的标域',
>         x: 100,
>         y: 100
>       }, {
>         x: '90%',
>         y: '10%'
>       }
>     ]
>   ]
> }
> ```

造成报错的原因是如下代码：
```
[
      {
        name: '两个屏幕坐标之间的标域',
        x: 100,
        y: 100
      }, {
        x: '90%',
        y: '10%'
      }
    ]
```

**Comment by bubblegreen** [comment]
遇到相同的问题～

**Comment by JasonBoy** [comment]
用funnel图的时候一样的问题，好像必须加`coord`属性, 
BTW: markArea能支持制定任意多的点么，而不是只有左上角跟右下角？
