### ISSUE TITLE
Datazoom在手机上无法缩放

### ISSUE THREAD

**Issue by xxyyyzz** [apache/echarts#10089]
### Version
4.2.1-rc.3

### Steps to reproduce
4.2.1-rc.3版本datazoom的type设置为'inside'，在手机上只能左右平移，无法进行双指缩放。我使用3.8.5版本是可以进行双指缩放的。

### What is expected?
在手机上能够进行双指缩放。

### What is actually happening?
datazoom的type设置为'inside'，在手机上只能左右平移，无法进行双指缩放。

**Comment by bugweili** [comment]
在官网的官方示例页面上，我点击侧边栏饼图 但菜单上高亮的却是柱状图菜单。分开点击没有问题，比如我进来直接点击第三个菜单饼图 这时候显示是正常的 但进来页面会默认显示第一个菜单栏折线图，这时候我点击柱状图就会有问题，多刷新几次就可以复现。有时候本身是在饼图页面 多刷新几次侧边栏的高亮会变成柱状图选项，多刷新几次必现 _______提不了issues只能在这里回答了
