### ISSUE TITLE
Chord Diagram in Echarts 3.0

### ISSUE THREAD

**Issue by jeffersonswartz** [apache/echarts#10098]
### What problem does this feature solve?
We are updating to Echarts 3.0 so we are updating the Charts. The Chord diagram is available in Echarts 2.0 but it is not included in the Echarts 3.0

### What does the proposed API look like?
Adding the Chord type in the Echarts 3.0

**Comment by dashmaker** [comment]
Would really like to see the Chord type in Echarts 4.0 as well. Is that in the pipeline?
