### ISSUE TITLE
富文本部分

### ISSUE THREAD

**Issue by gostfather** [apache/echarts#10102]
### What problem does this feature solve?
自定义legend时,我试用rich来优化展示,但是碰到一个问题,rich 必须是由一对"{}"包裹的数组,当这对"{}"里面的数据还存在"{}"这样的字符串时,就会解析成不正确的结果,希望能优化.

### What does the proposed API look like?
legend.formatter返回rich样例的时候可以自定义内容,限定边界的符号可以自定义

**Comment by Ovilia** [comment]
可以通过 `\{` 以及 `\}` 转义生成 `{}` 的

**Comment by gostfather** [comment]
转义不行的

**Comment by gostfather** [comment]
https://www.echartsjs.com/gallery/editor.html?c=pie-rich-text
这个例子可以试一下

**Comment by Ovilia** [comment]
嗯，存在 bug。期待效果：`显示{e|两个蓝色的花括号：\\{\\}}，然后这里是红色的`
