### ISSUE TITLE
对大规模散点图进行多次区域缩放和后退，出现错误

### ISSUE THREAD

**Issue by Aleph-Z** [apache/echarts#1012]
http://echarts.baidu.com/doc/example/scatter3.html
1、第一次缩放后，散点不是出现在整个坐标系内，而是只出现在大概1/4的区域内
![error 1](https://cloud.githubusercontent.com/assets/6788171/5357072/4c36f804-7fde-11e4-8d17-307f12cefeae.png)
2、从第二次缩放开始，显示的散点是错误的
![echarts](https://cloud.githubusercontent.com/assets/6788171/5356987/4a2db4ea-7fdd-11e4-9677-52eefe3eb035.png)

**Comment by xvacant** [comment]
缩放后四周空白较大的问题仍然存在

**Comment by kener** [comment]
最新源码，还没release呢

**Comment by xvacant** [comment]
是用最新源码build的, 问题2没有了, 问题1还有.
