### ISSUE TITLE
SVG x Scatter, problem on painting series.label

### ISSUE THREAD

**Issue by JohnRock0422** [apache/echarts#10135]
### Version
4.1.0-release

### Steps to reproduce
Show the following scatter chart with `renderer: 'svg'`

```
{
      renderer: 'svg', 
      color: ['#ffe0e0'], 
      xAxis: {},
      yAxis: {},
      series: [{
          label: {
            normal: {
              show: true, 
              position: 'top', 
              color: '#000'
            }
          }, 
          symbolSize: 50,
          data: [
              [10.0, 8.04],
              [8.0, 6.95]
          ],
          type: 'scatter'
      }]
  }
```

### What is expected?
Same behavior as `renderer: 'canvas'`

### What is actually happening?
There are some problems on showing label in `renderer: 'svg'`
1. The `position: top` doesn't aware the symbol size. So, the label is not shown on top of the symbol.
2. Switch between `show: true` and `show: false` of the label, the chart MAY not repaint to show/hide the labels.

_PS: problem can be repeated in 4.2.1-rc.3_

**Comment by ChuChencheng** [comment]
Same problem in 4.2.1

https://jsfiddle.net/f6r3vnLc/

Click the 'set label' button below the svg chart.

After toggling `label.show` from `false` to `true`, you have to point your mouse at the bar to show the labels.
