### ISSUE TITLE
When setOption has dataZoom startValue or endValue, the label of the dataZoom slider does not show

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#10151]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/gzvb2h4y/2/](https://jsfiddle.net/gzvb2h4y/2/)

### Steps to reproduce
Open the provided jsfiddle and click the button which sets the start and end value of the dataZoom.

Try to move the slider of the dataZoom (either start or end) and notice that no label is shown.

![Screenshot from 2019-03-22 17-34-57](https://user-images.githubusercontent.com/890368/54834976-ed025000-4cc9-11e9-829f-5dc107382330.png)

### What is expected?
I am expecting to see the dataZoom slider label even after setting the dataZoom options of the chart.

### What is actually happening?
The dataZoom label is not shown after setting the chart options with dataZoom startValue or endValue is set.

Clicking the zoom slider again this issue is resolved.

---
I came across this bug because we need to dynamically adjust the dataZoom of the chart from an ajax call, and it happens every time in our scenario because we need to set the dataZoom startValue and endValue every time we do the ajax call.

**Comment by mbury** [comment]
I have the same problem. At first click + move dataZoom.labelFormatter callback get ` {  value: null,  valueStr: "" } ` as arguments. I have demo to show that: https://codepen.io/anon/pen/BbvwVW

**Comment by Ovilia** [comment]
The label is expected to show only when mouse hover on the dataZoom handler.
So, is it your requirement to provide a method to display the label all the time?

**Comment by MINDoSOFT** [comment]
Hello everyone,

@Ovilia I would like to keep the existing functionality as it is (show the label only on mouse hover).

But as you can see in the **steps to reproduce** when you click the **click me**  button, and then you try to click and drag the zoom slider's start or end you can see that the label is missing. In the screenshot below I am dragging the zoom slider (although my mouse pointer is not shown in the screenshot, sorry about that) and you can see that no labels are shown.

![Screenshot from 2019-03-26 09-08-29](https://user-images.githubusercontent.com/890368/54977869-51156480-4fa7-11e9-8d44-62f6e6a621df.png)

And as @mbury mentioned in the dataZoom.labelFormatter callback I confirm that I get 
`{ value: null, valueStr: "" }`

Best regards,

Sergios.

**Comment by vvkee** [comment]
Hi, @Ovilia 
Have a method to display the label all the time?

**Comment by MINDoSOFT** [comment]
Hi @vvkee ,

still the bug would exist. For some reason the callback from dataZoom.labelFormatter has { value: null, valueStr: "" }. And a reminder that this happens just after calling the setOption (only for one time).

@Ovilia do have any update on this ?

Best regards,
Sergios.

**Comment by MINDoSOFT** [comment]
Hi there !

I have a created a jsfiddle using the code provided by @mbury ,

https://jsfiddle.net/5ab0hoce/1/

Please note that this is a bug that occurs on the drag of the zoom slider after chart **setOption** is called.

On the first time that you drag the zoom slider you see nothing (on the labels showing the start and the end of the zoom slider). 
![Screenshot from 2019-11-12 12-08-17](https://user-images.githubusercontent.com/890368/68662505-9a6df080-0545-11ea-9aa4-142d3177eae8.png)

On the second and rest of the times you can see the labels.
![Screenshot from 2019-11-12 12-08-23](https://user-images.githubusercontent.com/890368/68662518-a22d9500-0545-11ea-8815-a9df9c8b0ba5.png)

This is a very important thing to be fixed for us. Because we have an ajax callback that sets the chart options and thus every time the labels on the zoom slider are not shown.

Thank you for your time,

Sergios.

**Comment by Ovilia** [comment]
@pissang Please help review this.

**Comment by MINDoSOFT** [comment]
Hi there !
This is very important for the use case we have with the ajax call.
@pissang do you have any updates on this ?

**Comment by MINDoSOFT** [comment]
Hello @pissang @Ovilia ,

I added a button to the [jsfiddle example](https://jsfiddle.net/rw3vcy9t/1/) which sets the chart options, so you can see the error more easily. Also updated to the latest ECharts version 4.7.0. 

Basically every time you click the "Set Chart Option" button, and you drag the _zoom slider_, the labels on the _zoom slider_ are wrong.

Thank you for your time and effort on this.

Best regards,
Sergios.

**Comment by MINDoSOFT** [comment]
Hello @pissang  @Ovilia ,

I updated the [jsfiddle](https://jsfiddle.net/gpvqbtur/) to the latest echarts 4.8.0 version and the bug still occurs.

@pissang  could you review this issue.

Thanks,
Sergios.
