### ISSUE TITLE
It's abnormal to render charts quickly by IE11

### ISSUE THREAD

**Issue by Pulset** [apache/echarts#10150]
### Version
4.2.1-rc1

### Reproduction link
[https://jsbin.com/zocovip/edit?html,js,output](https://jsbin.com/zocovip/edit?html,js,output)

### Steps to reproduce
click reload button quickly,the color and data is reverse.The tooltip is wrong too.

### What is expected?
the color and data is sequential by option.The tooltip is right.

### What is actually happening?
the color and data is reverse.The tooltip is wrong too.

**Comment by Ovilia** [comment]
Where is the reload button you mentioned?

**Comment by Pulset** [comment]
open this web https://jsbin.com/zocovip/edit?html,js,output,then you will see it

**Comment by Mattdjuret** [comment]
It also happens in Edge.
