### ISSUE TITLE
根据图例不同动态渲染y轴数据问题

### ISSUE THREAD

**Issue by pantt** [apache/echarts#10155]
### What problem does this feature solve?
发现目前echarts中的y轴为category时，y轴条目是固定的，图例变化y轴条目不变。
需求是想让点击不同图例时，y轴条目也是动态得发生变化
![图片](https://user-images.githubusercontent.com/44255498/54898129-ff68cd80-4f05-11e9-8ef3-e0b1e027e2ef.png)

### What does the proposed API look like?
series字段

**Comment by Ende93** [comment]
切换 legend 只是切换 series，y轴的数量还是不会变的，如果你想要过滤 0 的值的话，就手动过滤下
