### ISSUE TITLE
map series 使用 geoIndex 指定 geo 组件时，geo 的 label.formatter 属性失效

### ISSUE THREAD

**Issue by duanluan** [apache/echarts#10191]
### Version
4.2.1

### Reproduction link
[https://www.echartsjs.com/gallery/editor.html?c=geo-map-scatter](https://www.echartsjs.com/gallery/editor.html?c=geo-map-scatter)

### Steps to reproduce
如[文档](https://www.echartsjs.com/option.html#geo.label.formatter)所示，geo.label.formatter 中添加 formatter 属性，此属性无效。

### What is expected?
地图每一块的标签值随 formatter 的更改而更改。

### What is actually happening?
标签值依旧是 series[i]-map.data[i].name 不变。

---
### 补充

[文档 series[i]-map.geoIndex](https://www.echartsjs.com/option.html#series-map.geoIndex)中说：
> 当设定了 geoIndex 后，series-map.map 属性，以及 series-map.itemStyle 等样式配置不再起作用，而是采用 geo 中的相应属性。

**Comment by shenshuai89** [comment]
geo 的 label.formatter 属性失效设置后失效，不起作用。官方赶紧修复啊
