### ISSUE TITLE
旭日图问题

### ISSUE THREAD

**Issue by lzh97** [apache/echarts#10203]
### Version
4.1.0-release

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=sunburst-book](https://www.echartsjs.com/examples/editor.html?c=sunburst-book)

### Steps to reproduce
点击旭日图最外层的item即下钻到最底层，再不断通过点击最内层的item上钻返回，在最后一次上钻时出现bug

### What is expected?
能够上钻返回初始状态

### What is actually happening?
在最后一次上钻时无法正常上钻

**Comment by kazehaiya** [comment]
I tried to disable the line 180（`r0: 0`）, and this time I can back to the root layout. But the presentation of '虚构' is not right.

Addition:
Why I can't find the configuration of `r`、`r0` and `position: 'outside'` in the document???

**Comment by Ovilia** [comment]
This is not quite a bug, but a bad design... When drilling down some levels that has `r0` as `0`, there is no place to put the return button. Not sure what can be done to fix this problem.
The `r`, `r0`, `position: 'outside'` is missing for the doc.
