### ISSUE TITLE
Call to dataView icon from another button

### ISSUE THREAD

**Issue by RubenCardos** [apache/echarts#10236]
### What problem does this feature solve?
Hi! I have been woorking with Angular and echarts in a proyect, and a i want to see the dataView table from another button. I read in the API Documentatión that i can call to echarts functions with the dispatch funcition, something like that

this.echartInstance.dispatchAction({ type: 'restore' });

But i cant do what i want with any action or events. Maybe is not possible for now??

I attach two images, the first is what i got now, the dataView icon (with label"A"), and the button (with label"B") what i want to have the same behaviour that the dataView icon.

![Captura](https://user-images.githubusercontent.com/7376673/55727772-fc480400-5a12-11e9-886d-dd7e527f3c46.PNG)

 The second image show what i got when i press the dataView icon, i want the same bhaviour when i press the another button.

![Captura2](https://user-images.githubusercontent.com/7376673/55727823-200b4a00-5a13-11e9-9417-5b3e7757e69a.PNG)

Any ideas or advices? Thanks a lot !

### What does the proposed API look like?
Maybe something like

echartInstance.dispatchAction({ type: 'show dataView' });

For show and hide the dataView table.

**Comment by Ovilia** [comment]
Please check http://echarts.apache.org/option.html#toolbox.feature for custom toolbox features.

**Comment by RubenCardos** [comment]
> Please check http://echarts.apache.org/option.html#toolbox.feature for custom toolbox features.

Thanks for the answer! But i want to call a toolbox feature from a button outside echarts (whit the echartInstance), not create a custom feature.

**Comment by bantaur** [comment]
Hi, I need this feature too. I'd like to use

`myChart.dispatchAction( type: 'dataView' } `

or something similar to open the chart dataView.

This is not working, there isn't a dataView event on documentation either similar event.

How clould open the data view with toolbox no visible?

**Comment by Ovilia** [comment]
Can you provide an online demo about what you have done now? http://jsfiddle.net

**Comment by RubenCardos** [comment]
Yes, i paste the link below

http://jsfiddle.net/8wa3e9cz/2/

![Captura](https://user-images.githubusercontent.com/7376673/55891891-a5c6fb00-5bb5-11e9-83c8-a0c2916c40e8.PNG)


The desire behaviour of the button with label A is show the table with the data, the same table that show the icon with label B

**Comment by Ovilia** [comment]
It seems that you are still using ECharts 2, which is not supported any longer. Please try with the latest version, and if there's still a problem with this, just let me know.

**Comment by RubenCardos** [comment]
I use the latest version in my project, the online demo is only a example of the desire beahviour.

**Comment by RubenCardos** [comment]
I update the example with the last versión and added some things, trying to explain the more the problem.

http://jsfiddle.net/dv9g4z3u/4/

**Comment by simonguo** [comment]
> Hi, I need this feature too. I'd like to use
> 
> `myChart.dispatchAction( type: 'dataView' } `
> 
> or something similar to open the chart dataView.
> 
> This is not working, there isn't a dataView event on documentation either similar event.
> 
> How clould open the data view with toolbox no visible?

I also need this feature.

**Comment by mtuzinskiy** [comment]
Any updates on this (no doubt valid) feature request?

**Comment by jNormaster** [comment]
Any updates? This is something we need aswell.

**Comment by Ovilia** [comment]
Please follow #17849
