### ISSUE TITLE
echarts-gl的graphGL类型edges的linestyle缺失curveness属性

### ISSUE THREAD

**Issue by Asimoz** [apache/echarts#10244]
### What problem does this feature solve?
希望graphGL类型能像graph类型的关系图一样为edges的linestyle添加curveness，更希望能多一个graph和graphGL类型中edges的开关来控制是否绘制重复的边（同 [#7760](https://github.com/apache/incubator-echarts/issues/7760)），如此配合curveness可以进行相同两个点之间多个边的绘制。另外，希望颜色的配置形式可以更丰富像graph类型的颜色配置。

### What does the proposed API look like?
像type:graph类型的curveness设置即可。

**Comment by Asimoz** [comment]
@Ovilia 貌似GraphGL不支持coordinateSystem: 'cartesian2d'，请问可以添加这份支持吗？Graph类型和GraphGL类型的layout:none时，无坐标系和coordinateSystem: 'cartesian2d'的区别是什么，同一份xy出来的位置不一样。

**Comment by Ovilia** [comment]
应该没有人力支持 gl 的新功能，这块代码我也不熟悉，只能自己 debug 一下了~

**Comment by Asimoz** [comment]
难过，希望graphGL的特性支持能尽快和graph一样
