### ISSUE TITLE
Legend does not render rich text for SVG renderer

### ISSUE THREAD

**Issue by phazor** [apache/echarts#10259]
### Version
4.2.1

### Reproduction link
SVG renderer (bugged): [https://jsfiddle.net/stdn7Lap/2/](https://jsfiddle.net/stdn7Lap/2/)
Canvas renderer (working): [https://jsfiddle.net/1ykxLndp/2/](https://jsfiddle.net/1ykxLndp/2/)

### Steps to reproduce
1. Create a new chart
2. Initialize the chart using the SVG renderer
3. Add rich text in the legend (https://ecomfe.github.io/echarts-doc/public/en/option.html#legend.textStyle.rich)

### What is expected?
Legend text is rendered correctly.

### What is actually happening?
Legend text is rendered as-is, with no rich formatting applied.

SVG renderer:
<img width="567" alt="Screenshot 2019-04-10 at 13 03 35" src="https://user-images.githubusercontent.com/1484323/55874008-62f32c00-5b91-11e9-9a4f-dddf7a784c99.png">

Canvas renderer:
<img width="556" alt="Screenshot 2019-04-10 at 13 03 44" src="https://user-images.githubusercontent.com/1484323/55874013-6686b300-5b91-11e9-9cc6-66925dc13c54.png">

**Comment by Ovilia** [comment]
SVG does not support rich text yet.

**Comment by Nilegfx** [comment]
any plans for adding rich text support to SVG?

**Comment by Ovilia** [comment]
@Nilegfx It has to be done after some underlying structure changes which we are planning for the next big version.

**Comment by krvajal** [comment]
It would be nice to have this mentioned in the docs. I spent almost one hour figuring out why rich text was not working and turned out I was using svg render

**Comment by mindon** [comment]
SVG rich text style not working in PPT:

the ```<text style="font: italic 19px &quot;Times New Roman&quot;">Hello</text>``` not working in PPT, it works in Inkscape.

if being changed into ```<text font-style="italic" font-size="19" font-family="Times New Roman">Hello</text>```, it works in both.

**Comment by Ovilia** [comment]
@krvajal The latest v5.x should not have such problems.
