### ISSUE TITLE
Android下饼图会出现画不全的现象

### ISSUE THREAD

**Issue by sWhite01111** [apache/echarts#10273]
### Version
3.8.5

### Steps to reproduce
使用框架是ng7

### What is expected?
饼图正常展示

### What is actually happening?
饼图经常性出现绘制不全的问题

![image](https://user-images.githubusercontent.com/17489600/55960748-f9157800-5c9f-11e9-93df-0e2dc0a22656.png)
其中canvas的高度和宽度是够的

**Comment by Ovilia** [comment]
请提供可复现的代码例子 https://gallery.echartsjs.com/editor.html

**Comment by sWhite01111** [comment]
//配置上没有任何特殊的，具体如下
option = {
    "series": [{
        "color": [
                '#2062E6', '#F2D024', '#ff8533', '#00cfcf', '#04c9a8',
                '#4cb5ff', '#bc64e5', '#f75ca9', '#f85948', '#2db62d',
                '#2db62d', '#f23030'
            ], 
        "type": "pie",
        "data": [{
            "name": "手淘首页",
            "value": 0.18153689106926518,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "手淘搜索",
            "value": 0.16499461553418387,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "淘内免费其他",
            "value": 0.14172549694132427,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "购物车",
            "value": 0.09252867975889559,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "我的淘宝",
            "value": 0.07450193691200885,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "直通车",
            "value": 0.05476637401097833,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "智钻",
            "value": 0.0500549664218729,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "手淘微淘",
            "value": 0.04455084580983862,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "手淘淘宝直播",
            "value": 0.033780044571411476,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "手淘其他店铺",
            "value": 0.033237858777427125,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }, {
            "name": "其他",
            "value": 0.12832229019279395,
            "label": {
                "normal": {
                    "textStyle": {
                        "fontSize": 30,
                        "color": "#333333"
                    }
                }
            },
            "hoverAnimation": false
        }],
        "animation": false,
        "radius": "50%",
        "center": ["50%", "55%"],
        "itemStyle": {
            "normal": {
                "borderWidth": 2,
                "borderColor": "#fff"
            }
        }
    }]
}

**Comment by sWhite01111** [comment]
https://gallery.echartsjs.com/editor.html?c=xZe8a0OpXe&v=1

**Comment by 574719191** [comment]
楼主怎么解决安卓显示问题。的
