### ISSUE TITLE
堆叠折线图，其中一条线step为true时，areaStyle填充不正确

### ISSUE THREAD

**Issue by segmafrontend** [apache/echarts#10275]
### Version
4.2.1-rc1

### Steps to reproduce
series: [{
        type: 'line',
        data:[220, 182, 491, 234, 290, 330, 310],
        stack: '总量',
        areaStyle: {},
        step: true
    }, {
        type: 'line',
        data:[220, 482, 191, 234, 290, 330, 310],
        stack: '总量',
        areaStyle: {},
    }]
![image](https://user-images.githubusercontent.com/43062793/56007712-30ba0980-5d0c-11e9-868c-b09cec176915.png)

PS：gallery无法保存了，不知道怎么回事
### What is expected?
两条先之间的区域不要留白，按正常逻辑填充

### What is actually happening?
阶梯图和折线图之间的区域没有正常填充

**Comment by SnailSword** [comment]
设置 `smooth: true,smoothMonotone: true` 之后也有同样的问题。

```javascript
series: [{
        type: 'line',
        data:[220, 182, 491, 234, 290, 330, 310],
        stack: '总量',
        areaStyle: {},
        smooth: true,
        smoothMonotone: true
    }, 
    {
        type: 'line',
        data:[220, 482, 191, 234, 290, 330, 310],
        stack: '总量',
        areaStyle: {},
    }]
```

![image](https://user-images.githubusercontent.com/19756301/56114775-62dd9c80-5f94-11e9-8090-58cd58cd8a78.png)

**Comment by Ovilia** [comment]
Relates #9317
