### ISSUE TITLE
dataZoom axisPointer not showing

### ISSUE THREAD

**Issue by Richard-biz** [apache/echarts#10286]
@Ovilia @wulamao @100pah 
### Version
4.2.1

### Reproduction link
[https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-touch](https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-touch)

### Steps to reproduce
new possibility for the echart dataZoom

### What is expected?
Hi There i am using on echarts(4.2.1) dataZoom slider functionality , I want to show the axisPointer  when the dataZoom slider will move the user need to see the label to the header , I  know the label is showing in the slider inside But i want that label in like a Axis Pointer,
So  i gone through your documentation i am not able to reach out, I can able to change text line and text style but i need to show the axis Pointer in the dataZoom slider Header Could you tell me how to archive this case. for your reference i attached my axis pointer link  please find out.

### What is actually happening?
I tried with the itemstyle and item text line position and grid and label position But Its not working.

**Comment by Ovilia** [comment]
Not sure what you want. But you could try with [tooltip with trigger to be `axis`](https://echarts.baidu.com/option.html#tooltip.trigger).

**Comment by Richard-biz** [comment]
@Ovilia 
![Capture](https://user-images.githubusercontent.com/20609857/56183202-24e38580-6033-11e9-8e62-056938fee23a.PNG)
 Thanks for the Response, Right now we are using the dataZoom as our some slider functionality there we need to show the slider date in the header instead of inside the datazoom slider. for your reference i attached my screen shot of it please have a look once.

**Comment by Ovilia** [comment]
I don't think you can do that with ECharts. But you can get the [dataZoom select event](http://echarts.apache.org/api.html#events.datarangeselected) and use DOM to display the information.

**Comment by Richard-biz** [comment]
@Ovilia  Yes your are right, I tried that way also but we don't get the exact dom position for the label , and datazoom event Object also not contain the x,y coordinate to bind the dom element. Thanks for the response
