### ISSUE TITLE
Option to keep Datazoom slider independent of data updates

### ISSUE THREAD

**Issue by ghost** [apache/echarts#10285]
### What problem does this feature solve?
Currently, when slider is moved, chart shows the data for the slider window. For my use case, for some slider range, new data is fetched with different granularity.

For example:
1. Initial render - all data points have 1 hour granularity. Slider range is 0 to 100. Chart looks as below
<img width="1093" alt="Screenshot 2019-04-13 at 15 19 40" src="https://user-images.githubusercontent.com/158846/56077929-9a671000-5dff-11e9-8187-0e7c417bb14d.png">

2. Let's say when slider range is at 50-60, new data is fetched with 1 minute granularity. Now, the entire chart data is updated to look like below
**1 hour granularity data + 1 min granularity +  1 hour granularity**
<img width="1099" alt="Screenshot 2019-04-13 at 15 12 40" src="https://user-images.githubusercontent.com/158846/56077873-fda47280-5dfe-11e9-983e-ab39f350228b.png">
3. After step 2, slider chart is not reflecting the correct trend.

**Reproducible link** - https://codesandbox.io/s/ovy71yro9q?fontsize=14

**Expectation** - When chart is updated with more data, there should be an option to NOT update diagZoom chart. It should still show the initial chart.

### What does the proposed API look like?
..

**Comment by Ovilia** [comment]
Slider serves only as a brief information view of data. I'm not sure it's necessary to provide more accurate information.

**Comment by rajvengala** [comment]
@Ovilia I agree with you in general. Users of our application use the slider to drill down to specific window. So role of dataZoom slider becomes important.

**Comment by Ovilia** [comment]
Oh. I misunderstood before. Seems to be a bug.

**Comment by rajvengala** [comment]
@Ovilia if this is confirmed as a bug, when can we expect to have this fixe available in a release ? We are currently evaluating either rewriting our own zoomable chart or using one of the other third-party chart libraries. If this is indeed a bug and if the fix will come soon enough, it would make our decision easy.

**Comment by Ovilia** [comment]
It may not be fixed quickly. And our release period is about 3 months.

**Comment by rajvengala** [comment]
Thank you for the update.

**Comment by Bowes97** [comment]
@Ovilia Did you add this functionality to keep initial data in datazoom slider when fetched a new data?
