### ISSUE TITLE
dataZoom.inside移动端手指缩放不生效

### ISSUE THREAD

**Issue by chinaguopeng** [apache/echarts#10309]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xcry0B7TcB&comment=0](https://gallery.echartsjs.com/editor.html?c=xcry0B7TcB&comment=0)

### Steps to reproduce
移动端打开，缩放图表

### What is expected?
移动端缩放功能生效

### What is actually happening?
缩放不生效

**Comment by chinaguopeng** [comment]
@Ovilia 就是说现在不能这样用吗？什么时候就可以了啊

**Comment by Ovilia** [comment]
@chinaguopeng 暂时不能用，需要进一步排查

**Comment by chinaguopeng** [comment]
@Ovilia ondrag事件，鼠标或手势滑动超出图表范围后，circle消失隐藏，我判断位置，限制超出。但是circle在图表上，ondrag事件失效，怎么处理

**Comment by Ovilia** [comment]
”circle在图表上，ondrag事件失效“是什么意思。
超出范围后，Circle看不见但还能拖的设定……有点迷……但想想好像也没有更好的方式，难道直接让它消失么？

**Comment by chinaguopeng** [comment]
@Ovilia 
https://gallery.echartsjs.com/editor.html?c=xcry0B7TcB&v=5
这是例子，拖动 circle 时鼠标超出图表，此时松开鼠标，circle 停在图表边缘，ondrag 失效。
是因为 graphic.position 数据错误引发的吗，应该怎样限制 position 的值

**Comment by Ovilia** [comment]
不太清楚，您可能需要调试下 ECharts 源码，我也不太了解这块的。

**Comment by yiwiz** [comment]
这个bug还没解决吗，这个可是直接影响移动端要不要用echarts阿

**Comment by lvding** [comment]
3.8或者4.x的一个低版本没有这个bug



---原始邮件---
发件人: "yiwiz"<notifications@github.com&gt;
发送时间: 2019年11月14日(星期四) 晚上6:42
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"lvding"<lvding89757@qq.com&gt;;
主题: Re: [apache/incubator-echarts] dataZoom.inside移动端手指缩放不生效 (#10309)



这个bug还没解决吗，这个可是直接影响移动端要不要用echarts阿
