### ISSUE TITLE
echartGL地球渲染，在移动端会自动将宽高放大两倍

### ISSUE THREAD

**Issue by yihoo** [apache/echarts#10300]
### Version
4.2.1

### Steps to reproduce
 创建移动端地球demo，如果canvas大小设置过大（超过3000px），放大两倍，会导致image2D过载，最终无法渲染。
在pc端没有这个问题，canvas不会自动放大两倍。

### What is expected?
都能正常渲染

### What is actually happening?
pc端没有问题，移动端有

---
没有找到源码关于这部分的代码，希望能够告知位置。自己编译版本，如果是一个bug，可以解决。或者告知这么做的意图和原因。

**Comment by yihoo** [comment]
我找到问题所在了， echartgl里面对设备的devicepixelratio的计算，导致在视网膜屏下面，它的drp=2, 所以在ipad端会变成两倍。我猜想这个设计的初衷应该是对视网膜屏的优化，但是也会导致一定的问题。是否能解释一下这个设计的初衷？

**Comment by pissang** [comment]
@yihoo  可以在初始化 echarts.init 的时候设置 devicePixelRatio
