### ISSUE TITLE
legend rich align right not work

### ISSUE THREAD

**Issue by RookieLittleFatty** [apache/echarts#10327]
### Version
4.0.0

### Reproduction link
[https://www.echartsjs.com/examples/editor.html?c=pie-nest](https://www.echartsjs.com/examples/editor.html?c=pie-nest)

### Steps to reproduce
add the following to legend,  you can find the align prop work weired：
 textStyle: {
            rich:{
                label: {
					width: 220,
					fontSize: 18,
					borderWidth: 1,
					borderColor: '#ff0000'
				},
				num: {
					width: 130,
					fontSize: 18,
					align: 'right',
					borderWidth: 1,
					borderColor: '#ff0000'
				},
				ratio: {
					width: 100,
					fontSize: 18,
					align: 'left',
					borderWidth: 1,
					borderColor: '#ff0000',
				}
            },
        },
        formatter: '{label|{name}}{num|200}|{ratio|33%}',

### What is expected?
I want the label align left， num align right， ratio align left

### What is actually happening?
num  can not align right

**Comment by susiwen8** [comment]
Actually this is a bug from zrender, I have opened a PR https://github.com/ecomfe/zrender/pull/458

**Comment by xiaomeinvG** [comment]
Hello, is this problem solved? I also encountered this problem in 5.0.
