### ISSUE TITLE
Conflicts in DataZoom and NotMerge

### ISSUE THREAD

**Issue by zteric** [apache/echarts#10339]
### Version
4.2.1

### Steps to reproduce
Case: a dynamic line chart which will get update when new data comes in, datazoom has been enabled.
 
Background: I need to use NotMerge mode to prevent some data remaining issues(e.g. if user deselect all readings, should remove all data in charts and show a graph text in chart, which means I have to clear series).

Issue: The datazoom can not save its current state(e.g. current zoom area) and will always get reset when new data comes in as I have to pass complete options(including datazoom configuration) to echarts in NotMerge mode.

### What is expected?
Provide a method to let datazoom not be resetted under NotMerge mode.

### What is actually happening?
datazoom always get reset under NotMerge mode.

**Comment by 100pah** [comment]
Currently, if using NotMerge mode, you have to get the current state of dataZoom by `chart.getOption`.
We should provide more detailed settings in `chart.setOption` to enable customize which chart/component will be merged and which will not.

**Comment by zteric** [comment]
> Currently, if using NotMerge mode, you have to get the current state of dataZoom by `chart.getOption`.
> We should provide more detailed settings in `chart.setOption` to enable customize which chart/component will be merged and which will not.

Thank you for your reply and advise, get DataZoom option via `chart.getOption` is working properly in this case.
Hope to see detailed settings of individual merge feature in the future.
