### ISSUE TITLE
散点图多个series会出现tooltip提示失效

### ISSUE THREAD

**Issue by linghuweichao** [apache/echarts#10342]
### Version
4.2.1

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=scatter-large](https://echarts.baidu.com/examples/editor.html?c=scatter-large)

### Steps to reproduce
官方示例：https://echarts.baidu.com/examples/editor.html?c=scatter-large
在x轴0-1区间内，鼠标分别放置黑色与红色散点，显示提示

### What is expected?
红色和黑色的每个散点都有提示

### What is actually happening?
x轴0-1区间内黑色散点可以正常有提示，红色散点不显示提示

**Comment by cuijian-dexter** [comment]
The cause of the bug is the series order Aseries. data > Bseries. data. First, if Aseries is above, only the part of Aseries that is smaller than the maximum value in Bseries shows a problem.

Https://gallery.echartsjs.com/editor.html?C=x00zqS1OSf&v=1

The second is that if Bseries is above, only the part where Aseries is greater than the minimum value in Bseries is showing a problem.

Https://gallery.echartsjs.com/editor.html?C=xp0braR6G6&v=1

**Comment by linghuweichao** [comment]
> 
> 
> The cause of the bug is the series order Aseries. data > Bseries. data. First, if Aseries is above, only the part of Aseries that is smaller than the maximum value in Bseries shows a problem.
> 
> [Https://gallery.echartsjs.com/editor.html?C=x00zqS1OSf&v=1](Https://gallery.echartsjs.com/editor.html?C=x00zqS1OSf&v=1)
> 
> The second is that if Bseries is above, only the part where Aseries is greater than the minimum value in Bseries is showing a problem.
> 
> [Https://gallery.echartsjs.com/editor.html?C=xp0braR6G6&v=1](Https://gallery.echartsjs.com/editor.html?C=xp0braR6G6&v=1)

您好，首先，在您的例子里面，我没有看到跟我的问题有什么关联，您都没有设置tooltip参数，更不用说显示问题了，其次，在官方案例中，Aseries的数据只要大于Bseries的数据的最小值，就会出现提示失效问题，跟您说的一致，所以说，这确实是一个bug，还是说官方现在也不支持多个series去显示所有提示？需要后续改进

**Comment by linghuweichao** [comment]
![图片](https://user-images.githubusercontent.com/32892919/56858284-0d4cbb00-69aa-11e9-9045-0100d24dbdac.png)
在Y轴0以上的所有红色区域tooltip都无法显示

**Comment by Ovilia** [comment]
是 bug

**Comment by linghuweichao** [comment]
> 
> 
> 是 bug

好的，希望可以尽快解决，谢谢您

**Comment by mrFranklin** [comment]
@Ovilia
同遇到这个问题，请问何时能修复啊？

**Comment by sikazhang** [comment]
按照nuancheng的#486修复图层叠盖时获取点归属图层错误问题，修改zrender库的rectContain方法，问题得以解决。希望尽快将#486的改动合入master。@Ovilia

**Comment by Ovilia** [comment]
@sikazhang 非常感谢，我找人尽快给你 review~~

**Comment by TheoXiong** [comment]
@Ovilia 你好，请问这个bug现在修复了吗？
