### ISSUE TITLE
[Tree chart] Can I add a text such a "+" into collapsing symbol(marker)

### ISSUE THREAD

**Issue by m3rri** [apache/echarts#10354]
### What problem does this feature solve?
In the API,<br/>
When I choose a symbol 'empty**', I can change a color of collapsing node of tree chart.<br/>
And I want to know that I can add a text into a marker or not.<br/>
I got this ▼<br/>
marker : '＜span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#61a0a8;"＞＜/span＞'<br/>
I want to make it ▼<br/>
'＜span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#61a0a8;"＞+＜/span＞'<br/>
let user notice it has children nodes.<br/>
Thank you.

### What does the proposed API look like?
In the API,<br/>
When I choose a symbol 'empty**', I can change a color of collapsing node of tree chart.<br/>
And I want to know that I can add a text into a marker or not.<br/>

**Comment by deqingli** [comment]
#8048
