### ISSUE TITLE
移动端折线tooltip的symbol响应的区域非常小，能否扩大响应范围

### ISSUE THREAD

**Issue by dagundejuzi** [apache/echarts#10360]
### What problem does this feature solve?
symbol点击事件用户体验优化。

### What does the proposed API look like?
折线图symbol的点击区域能更大一点，类似于绑定'axis'时那样的，点击临近区域就能响应事件。

目前在移动端点击折线symbol，非常难以点到，可能点7、8下才能点出响应事件，如果symbol在图表边缘就更难点到。如果每次点击间隔5s以上，似乎准确率能高一点。
点击事件的绑定是这样的：
`
……
tooltip: {
                    show: true,
                    confine: true,
                    trigger: 'item',
                    triggerOn: 'click',
             }

……

myChart.on('click',function (param) {
               // 响应事件操作
});
`

**Comment by plainheart** [comment]
#17102 应该能够解决此类问题。参见 [智能指针吸附](https://echarts.apache.org/handbook/zh/how-to/interaction/coarse-pointer/)
