### ISSUE TITLE
dataZoom 阻塞滚动条

### ISSUE THREAD

**Issue by kazehaiya** [apache/echarts#10376]
### Version
4.2.1

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=area-rainfall](https://echarts.baidu.com/examples/editor.html?c=area-rainfall)

### Steps to reproduce
将原有的 dataZoom 的 inside 部分添加如下内容：

zoomOnMouseWheel: 'ctrl'

### What is expected?
当鼠标移入图内（能够呈现出 tooltip 样式时），仅仅在按 ctrl 键时阻塞原有的滚轮事件

### What is actually happening?
在不按 ctrl 时也阻塞了原有滚动事件（页面不会出现上下拉动的效果）

---
去掉 dataZoom 属性，鼠标移入图内，上下滑动滚轮可以看到拉去效果（页面会往下拉沉）。

业务场景：看板页面，此会造成页面滚动被阻塞，影响体验

**Comment by kazehaiya** [comment]
addition: I tried echart's version 4.1.0, It seems OK when I set property 'zoomOnMouseWheel' in my project. I hope that it can help you to solve this problem.

**Comment by GFwer** [comment]
I have the same problem in [#10079](https://github.com/apache/incubator-echarts/issues/10079)
