### ISSUE TITLE
The chart columns overflow the grid area for a stacked bar chart with logarithmic Y axis

### ISSUE THREAD

**Issue by ciukstar** [apache/echarts#10374]
### Version
4.2.1

### Steps to reproduce
option = {
    title: {
        text: '对数轴示例',
        left: 'center'
    },
    tooltip: {
        trigger: 'item',
        formatter: '{a} <br/>{b} : {c}'
    },
    legend: {
        left: 'left',
        data: ['2的指数', '3的指数']
    },
    xAxis: {
        type: 'category',
        name: 'x',
        splitLine: {show: false},
        data: ['一', '二', '三', '四', '五', '六', '七', '八', '九']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    yAxis: {
        type: 'log',
        name: 'y'
    },
    series: [
        {
            name: '3的指数',
            type: 'bar',
            stack: 'one',
            data: [1, 3, 9, 27, 81, 247, 741, 2223, 6669],
            label: {
          normal: {
            show: true,
            position: 'insideTop'
          }
        }
        },
        {
            name: '2的指数',
            type: 'bar',
            stack: 'one',
            data: [1, 2, 4, 8, 16, 32, 64, 128, 256],
            label: {
          normal: {
            show: true,
            position: 'insideTop'
          }
        }
        },
        {
            name: '1/2的指数',
            type: 'bar',
            stack: 'one',
            data: [1/2, 1/4, 1/8, 1/16, 1/32, 1/64, 1/128, 1/256, 1/512],
            label: {
          normal: {
            show: true,
            position: 'insideTop'
          }
        }
        }
    ]
}

### What is expected?
Columns do not overflow

### What is actually happening?
Columns overflow

**Comment by ciukstar** [comment]
/home/sergiu/Pictures/stacked-col-logarithmic-y-demo.png

**Comment by ciukstar** [comment]
![stacked-col-logarithmic-y-demo](https://user-images.githubusercontent.com/8271154/57162440-f0bfe100-6df6-11e9-921e-b7ad783526e1.png)

**Comment by qroft** [comment]
I can confirm this.
I am having the same issue with the horizontal stacked bar.
I have added this line to my grid so that i can see that my bar goes bigger than the grid.
![stacked-bar-bug](https://user-images.githubusercontent.com/14896725/57168886-c290d000-6dfb-11e9-919d-5b49dea96d9a.jpg)

**Comment by qroft** [comment]
If i found out correctly, the chart does not calculate the maximum value of all stacked bars.
First i added this to my xAxis
`max: 'dataMax'`
And the layout was broken again.
Then i manually calculated the sum of all my bars and added this:
`max: 14.05`

With the latter, my stacked bar looks correct like it should.

My temporaray solution: calculate the sum of all values in a variable and add that variable like this:
`max: myItemsSum`
