### ISSUE TITLE
DataZoom Slider Does Not Respect Y Axis min if positive value

### ISSUE THREAD

**Issue by Dus1988** [apache/echarts#10389]
### Version
4.2.1

### Steps to reproduce
Create a 2 axis Cartesian chart
make x axis category, and y axis a value axis. 
set y axis minimum to a positive value
set datazoom on y axis as a slider
Notice chart y axis does not adhere to y-axis minimum, instead is 0

### What is expected?
If y axis has a min and/or max set, the data zoom should adhere and have the same range as the chart's y axis

### What is actually happening?
chart's y axis listens to y axis min, but data zoom bottom(start) on y axis is always equal to 0 if yAxis.min is a positive number. If min is set to a negative number, datazoom will respect it. 

---
this can be replicated on the demo linked below. 

notice datazoom y axis bottom is equal to -30.
change y axis min to 10.
notice datazoom y axis bottom is equal to 0

https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-draggable

**Comment by Dus1988** [comment]
Here is a screenshot of the issue
`<a href="https://ibb.co/D844SF9"><img src="https://i.ibb.co/wwyyxqS/screenshot.jpg" alt="screenshot" border="0"></a>`

**Comment by susiwen8** [comment]
@Dus1988 axis scale is set to 'false' as default, and if min or max was set, scale shouldn't work,  but it didn't check
https://github.com/apache/incubator-echarts/blob/master/src/component/dataZoom/AxisProxy.js#L476

**Comment by susiwen8** [comment]
@Dus1988 at this moment, you can add scale to true in option to fix this problem
            yAxis: {
                min: 10,
                max: 60,
                scale: true,
                type: 'value',
                scale: true,
                axisLine: {
                    onZero: false
                }
            },
