### ISSUE TITLE
bar series item labels overlap

### ISSUE THREAD

**Issue by sammytran90** [apache/echarts#10402]
### Version
4.2.1

### Steps to reproduce
when bar items are too close (ex. large scale bar chart with series.label.show = true), each item's label will get overlapped by next item.

### What is expected?
label should be placed without overlap
or
should provide custom function/handler to handle position of series data

### What is actually happening?
Labels gets overlapped

**Comment by Ovilia** [comment]
It's quite hard to make sure they don't overlap each other. I'll mark this as an enhancement for now, but long fix time should be expected.

**Comment by deqingli** [comment]
#11497
