### ISSUE TITLE
Add support for weighted graph & optimize parse of attributes in gexf.js tool

### ISSUE THREAD

**Issue by StarGazerM** [apache/echarts#10457]
### What problem does this feature solve?
gexf.js does not support weight graph, get `weight` item while parsing edgeDom can easily fix it.
Meanwhile,  now gexf tool will parse the  attrValue like `<attribute id="0" title="mod" type="long" />` into a list. Parsing attrTitle  to a member of node.attributes will be more convenient for using because some tool may generate index different for each time .

### What does the proposed API look like?
visit the weight of a node
```
node .weight
```

parse attribute of node like 
```
<attribute id="0" title="mod" type="long" />  
->
node.attributes.mod
 ```

**Comment by Ovilia** [comment]
Hi. Currently, we don't have the time to make this new feature. You may consider making a Pull Request of that. Thanks!
