### ISSUE TITLE
Touch devices can't pan because edge is activated

### ISSUE THREAD

**Issue by braco** [apache/echarts#10450]
### Version
4.2.1

### Steps to reproduce
This is a request for documentation, or clarification:

On Directed / Force Graph,

1. Is there a way to disable hover on edges? I would like hover state to only appear on nodes, not edges.

2. on iPad, it's almost impossible to pan because touch activates hover on edges. Pinch to zoom also doesn't seem to work. Is this a known issue?

Thank you

### What is expected?
Touch makes devices pan

### What is actually happening?
Touch activates hover on edges, which is not desired

**Comment by Ovilia** [comment]
Currently, it's not possible to achieve this. I will mark this as an enhancement.

**Comment by braco** [comment]
Thank you for the reply.

Can a node be highlighted programmatically? I suppose this could be recreated with a click event if so.

Also are you saying that zooming is not possible on touch devices either?

**Comment by Ovilia** [comment]
Highlight can be triggered programmatically. See http://echarts.apache.org/api.html#action.highlight .
I mean to disable highlight when touch on edge is not currently possible.

**Comment by braco** [comment]
@Ovilia, where is the code that activates touch on edges? I can submit a pull request but need some guidance
