### ISSUE TITLE
天津地图数据，缺失蓟州区

### ISSUE THREAD

**Issue by umi-soft** [apache/echarts#10460]
### Version
4.2.1

### Steps to reproduce
我查看了echarts的源码，发现地图数据中，天津蓟州区，coordinates坐标数据是空数组

### What is expected?
提供完整的天津市地图数据

### What is actually happening?
目前缺失整个蓟州区区

**Comment by Ovilia** [comment]
欢迎提供 PR

**Comment by cuijian-dexter** [comment]
@umi-soft https://github.com/echarts-maps/echarts-china-cities-js
You can get map data from here.

**Comment by chfw** [comment]
I have not fixed the issue yet. It’s noted already.

**Comment by chfw** [comment]
It is under editing and will enter production soon. Stay tuned.

Here is how it looks:

![Screenshot 2019-05-16 at 22 29 25](https://user-images.githubusercontent.com/4280312/57888436-1521b180-782a-11e9-98d8-d3abed1c0cd3.png)

**Comment by Ovilia** [comment]
@chfw Great job! Looking forward to your PR.

**Comment by chfw** [comment]
@ZxdNoob has done the PR already, so I let him go ahead and have left my comments. 

I may add js version if @ZxdNoob does not provide one.

**Comment by chfw** [comment]
https://github.com/apache/incubator-echarts/pull/10489
