### ISSUE TITLE
The legend color was wrong when switching mulitple chart instances in IE11 and Edge

### ISSUE THREAD

**Issue by Alizwell** [apache/echarts#10488]
### Version
4.2.1

### Steps to reproduce
1. There are 6  charts, and we can switch  those charts arbitray in a selection
2. Each chart have the same legend and color config
3.  Switch thos charts more than 8 times

### What is expected?
Every time the legend color should be the same

### What is actually happening?
The legend  color will be wrong after switch those charts many y times.

---
1. This bug can reproduce definitely in IE11  and Edge, but can't reproduce in Chrome(Version 74.0.3729.131)
2. I loged the option, found that the  option  was the same but the render of legend was different

![chart](https://user-images.githubusercontent.com/9283889/57901331-2ead1280-7897-11e9-8c37-b40882f74939.gif)

-

**Comment by Alizwell** [comment]
![chart](https://user-images.githubusercontent.com/9283889/57901297-0b826300-7897-11e9-9396-b66963137d27.gif)

**Comment by Ovilia** [comment]
Can you provide a minimum demo to reproduce this problem? https://jsfiddle.net/ovilia/yh76w9Lt/

**Comment by Alizwell** [comment]
OK, I will provide a demo in the later time.

**Comment by Alizwell** [comment]
You  can refer this link [https://codesandbox.io/s/wonderful-mayer-16jlx](url)

**Comment by Alizwell** [comment]
https://codesandbox.io/s/great-shannon-vk48p?fontsize=14
Sorry, the  previous link was wrong, you can refer to this new link.

**Comment by binarykitchen** [comment]
We have this problem too and bumping to latest echarts version 4.4.0 does't make a difference. I wonder if you are polyfilling collection functions to ensure IE11 compatibility?

**Comment by Ovilia** [comment]
What happens when switching charts? What functions are you calling? [The demo](https://codesandbox.io/s/wonderful-mayer-16jlx) has error and pleas provide a simpler one.

**Comment by Alizwell** [comment]
@Ovilia I have simplified the demo, please head to this [demo](https://codesandbox.io/s/echart-legend-color-bug-8coso). here is a gif about this bug. 
![after1](https://user-images.githubusercontent.com/9283889/70132303-e7fdf900-16be-11ea-87e9-997ba9a938aa.gif)

**Comment by SnailJason** [comment]
> @Ovilia I have simplified the demo, please head to this [demo](https://codesandbox.io/s/echart-legend-color-bug-8coso). here is a gif about this bug.
> ![after1](https://user-images.githubusercontent.com/9283889/70132303-e7fdf900-16be-11ea-87e9-997ba9a938aa.gif)

so，what is the result?
