### ISSUE TITLE
三维地图在触摸屏的情况下点击无法点击或者getZr()能点击却不能获得地图数据

### ISSUE THREAD

**Issue by mrtangdong** [apache/echarts#10480]
### Version
4.2.0-rc.2

### Steps to reproduce
echarts-gl v1.1.1的版本，渲染一个3D地图， 打开谷歌浏览器调试模式，点击那个像手机一样的图标，选择好尺寸，模拟触摸屏，点击三维地图没反应（直接手机打开不行，不是触摸屏的情况下可以）

### What is expected?
能够点击且能够返回具体的数据

### What is actually happening?
不能等级，getZr()能点击，但不能返回数据

---
手机上不行，2D的可以

**Comment by aiyamama** [comment]
这个问题解决了吗？怎么解决的呀？我这边也遇到相同的问题
