### ISSUE TITLE
Support mouse wheel in slider dataZoom and axes

### ISSUE THREAD

**Issue by ofirbit** [apache/echarts#10491]
### What problem does this feature solve?
The mouse wheel zooms the chart with the 'inside' dataZoom. However, the mouse wheel does not work when scrolling above the slider dataZoom object (e.g - https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-draggable). It will help a lot if we could zoom in/out a single axis with the mouse wheel above the slider dataZoom view (or maybe even with a mouse wheel above the axis itself). I also found that there is no `on('mousewheel')` event for the axis or the dataZoom, so there is no simple workaround for this.

### What does the proposed API look like?
When the user scrolls the mouse wheel above a specific axis slider dataZoom (or above the axis itself) it will zoom in/out only this axis. When the user drags the axis with the mouse, it will pan only this axis.

Example (https://help.plot.ly/zoom-pan-hover-controls/#step-6-pan-along-axes) - see how they drag the x/y axes nicely:
![example](https://help.plot.ly/static/images/zoom-pan-hover/zoom-axis.gif)

**Comment by Ovilia** [comment]
This seems a nice feature.

**Comment by ofirbit** [comment]
So, do you know if there is a plan for implementing this?

**Comment by Ovilia** [comment]
Basically, we need contribution from the community. So the implementation plan is hard to say.
