### ISSUE TITLE
DataZoom zooms out to show one day when a span of 0 is selected

### ISSUE THREAD

**Issue by phazor** [apache/echarts#10523]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/_phazor/zw4f86pe/9/](https://jsfiddle.net/_phazor/zw4f86pe/9/)

<img width="620" alt="Screenshot 2019-05-22 at 14 59 13" src="https://user-images.githubusercontent.com/1484323/58176266-3824e900-7ca2-11e9-8bd7-e543f629df74.png">

### Steps to reproduce
1. Take a chart with the following properties:
 - dataZoom is enabled.
 - `filterMode` is set to `none`.
 - the zoom is set for an axis that has the property `type: time`.
 - you have data that spans a proportion of one day (e.g. 5 hours worth).

2. Move the dataZoom sliders so that the selected range is 0.

### What is expected?
Chart shows instantaneous point where the range is centered on.

### What is actually happening?
Chart zooms out to show one day

---
This functionality seems to behave as expected when:
 - `filterMode` is anything other than `none
 - axis `type` is anything other than `time`

**Comment by phazor** [comment]
Workaround: set `dataZoom: { minSpan: <value> }` to a value of 0.01 or something suitable small.

The only issue with this is that instead of the dragged selection point 'crossing over' the existing selection point, it pulls the point with it instead:

Ideal behaviour:
![datazoom_1](https://user-images.githubusercontent.com/1484323/58177499-c8fcc400-7ca4-11e9-99c6-252cddd9b7a7.gif)

With workaround:
![datazoom_2](https://user-images.githubusercontent.com/1484323/58177506-cd28e180-7ca4-11e9-81bd-eea2175ff15b.gif)

**Comment by WissemAouichi** [comment]
@phazor I had the same issue of dragging the datazoom instead of crossing over when i used the datazoom event to merge options. How to avoid having this behavior ?
