### ISSUE TITLE
桑基图中节点的布局方向，请问可以从右往左吗？

### ISSUE THREAD

**Issue by RuiMM** [apache/echarts#10533]
### What problem does this feature solve?
会有一个勾选项，让sankey图展现出不同的状态，比如说起始节点改变成终止节点

### What does the proposed API look like?
希望orient增加个从右往左布局的参数

**Comment by Ovilia** [comment]
目前不支持

**Comment by deqingli** [comment]
@RuiMM  请问什么场景下需要从右往左，可以具体说明下么？
