### ISSUE TITLE
dataZoom filterMode empty 数据不正确

### ISSUE THREAD

**Issue by z3rog** [apache/echarts#10560]
### Version
4.1.0-release

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xa9MfDn15D&v=1](https://gallery.echartsjs.com/editor.html?c=xa9MfDn15D&v=1)

### Steps to reproduce
1. 打开重现链接
2. 缩放至最大级别，即可重现。

### What is expected?
显示正确的柱

### What is actually happening?
同时显示了最大值的柱并重叠了

---
https://github.com/apache/incubator-echarts/issues/3983 大概三年有有人提出这个问题，但没有得到任何讨论。相信这不是一个近期引起的bug。亲测，在所有柱状图都有这个问题。

**Comment by Ovilia** [comment]
Probably relate to #10523.
