### ISSUE TITLE
关于实例(examples)中K线上证指数的问题，代码未实现它自己想达到的效果

### ISSUE THREAD

**Issue by withcancer** [apache/echarts#10561]
### Version
4.2.1

### Steps to reproduce
直接运行’上证指数‘实例
[中文例子](https://echarts.baidu.com/examples/editor.html?c=candlestick-sh)
[英文例子](https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-sh)

### What is expected?
`Series`配置中`MarkPoint`一节有`tooltip`相关配置，全局中有`tooltip`配置，它的`trigger`为'axis'，期望结果是鼠标在图中(XY轴范围内)移动时，会表示出来`bar`对应的`tooltip`和`markpoint`对应的`tooltip`以及十字准线。

### What is actually happening?
现在`MarkPoint`对应的`tooltip`在任何状态下都不能表示出来，例如配置中提及的第一个`name`为’XX标点‘的`tooltip`。
![默认代码](https://user-images.githubusercontent.com/19775306/58461226-b92c2680-8161-11e9-805e-0a5c8eb06e5d.png)
---
按照相关issue的描述，这是一个目前没有实现的功能
[9331](https://github.com/apache/incubator-echarts/issues/9331)
[9539](https://github.com/apache/incubator-echarts/issues/9539)
把全局配置中的trigger修改为`item`可以达到鼠标移动到对应的`bar`上或者`point`上时显示对应的`tooltip`的效果。
![](https://user-images.githubusercontent.com/19775306/58461505-6d2db180-8162-11e9-8f2d-3d247a49d215.png)
![Screenshot from 2019-05-28 16-06-45](https://user-images.githubusercontent.com/19775306/58461644-baaa1e80-8162-11e9-815e-0e271de6e82c.png)

但这也并不是这个实例的本来代码含义，建议修改实例使之一致化

**Comment by Ovilia** [comment]
markPoint 什么时候支持 tooltip 了？配置项手册并没有看到相关的配置项。

**Comment by withcancer** [comment]
配置手册中没有，但是网站上的实例代码里面那样写着
![Screenshot from 2019-05-28 17-31-47](https://user-images.githubusercontent.com/19775306/58467669-ac61ff80-816e-11e9-9896-da0afd46351c.png)
