### ISSUE TITLE
graph图中可以为每个node和edge定义cursor类型

### ISSUE THREAD

**Issue by topvis** [apache/echarts#10584]
### What problem does this feature solve?
在当前版本4.2.1中，cursor的定义是在node和edge之外的，因此无法为每个node和edge分别定义cursor的类型。

在某些应用场景下，会希望有些node或者edge是可以点击的，有些是不可以点击的。如果可以为每个node和edge分别定义cursor的类型的话，则可以将可以点击的node/edge的cursor设置为pointer，将不可以点击的node/edge的cursor设置为default。

一个具体的例子如下：
用graph图实现一个文档批准流程。流程中有三个状态（nodes）：草稿，已提交和已批准。当前状态是”草稿“。则只有”提交“这个动作（edge）是可行的，即可点击的，比如点击之后显示一个确认对话框，确认是否提交。而另外一个动作”批准“在当前状态下是不可行的，即不可点击的。
![image](https://user-images.githubusercontent.com/5996531/58603750-78005780-82c4-11e9-8be6-9378ea996751.png)

### What does the proposed API look like?
期望在graph图的option中的lineStyle和itemStyle加入cursor的属性定义。
```Javascript
lineStyle: {
  normal: {
    width: 5,
    curveness: 0.2，
    cursor: 'default', // 或者其他需要的cursor类型
  }
}
```

**Comment by Ovilia** [comment]
这种需求其实不是很适合用 ECharts 做，不过暂时还是先标为 new-feature 了。

**Comment by topvis** [comment]
@Ovilia 我举得文档批准流程的例子实际上是一个State machine或者State flow的应用。我找了很多网上的资源，感觉用Echarts的Graph来实现这种State flow的应用还是不错的。如果能够实现我提出的这个定义Cursor话，那对我的应用几乎完美了。
如果Echarts可虑开发一个专门适用于State flow的图的话，那就更好了，比如加一些从一个state转移到另一个state的动画等。毕竟State flow有很广泛的应用，比如业务管理流程，控制系统策略等等。这里是一个State Machine的Javascript的库以供参考。

**Comment by Ovilia** [comment]
ECharts 暂时不考虑流程图相关的，不然就是一系列很大的功能
