### ISSUE TITLE
echarts4在ie10 以上地图鼠标移上去都不会高亮吗？还是什么其它原因？

### ISSUE THREAD

**Issue by Re-Kun** [apache/echarts#10590]
### Version
4.2.1

### Steps to reproduce
按照正常生成的中国地图，发现谷歌下可以，切换ie11不可以

### What is expected?
在谷歌和ie下的鼠标移上去会有高亮和事件提示

### What is actually happening?
只有谷歌下有效果

---
就是很普通初始化后的地图

**Comment by Ovilia** [comment]
暂时没有 windows 机器复现，或许你可以尝试一下使用 svg  https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93

**Comment by Re-Kun** [comment]
@Ovilia svg之前我也试了，也是没能实现效果，我之前用zrender的时候也遇到过这个问题，我以为是没配置好，后来文档也没找到相关信息，反正切换成ie11，默认的高亮效果和事件都没了
