### ISSUE TITLE
使用 dataZoom，选取范围缩小出错

### ISSUE THREAD

**Issue by CorruptKubCzh** [apache/echarts#10595]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xWP6yHSAnO&comment=0](https://gallery.echartsjs.com/editor.html?c=xWP6yHSAnO&comment=0)

### Steps to reproduce
鼠标滚轮缩小范围

### What is expected?
缩小到一定范围不在缩小

### What is actually happening?
缩小范围实际情况，报错

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/4d0ea095dc3929cb6de40c45748826e7999c7aa8/src/data/List.js#L1178
Trying to figure out why this._count is smaller than idx.

**Comment by CorruptKubCzh** [comment]
> https://github.com/apache/incubator-echarts/blob/4d0ea095dc3929cb6de40c45748826e7999c7aa8/src/data/List.js#L1178
> 
> 
> 试图弄清楚为什么this._count小于idx。

What's the solution?

**Comment by susiwen8** [comment]
Please see the PR

**Comment by 100pah** [comment]
报错是在 `axisPointer.formatter` 中报的。
可先在 `formatter` 中应判断 “没有对应上数据的情况”，避免报错发生。
而 axisPointer 的问题的修改，会进行。

**Comment by CorruptKubCzh** [comment]
好的
