### ISSUE TITLE
Datazoom loses focus when mouse leaves canvas

### ISSUE THREAD

**Issue by d4vsanchez** [apache/echarts#10598]
### Version
4.2.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=area-rainfall](https://echarts.apache.org/examples/en/editor.html?c=area-rainfall)

### Steps to reproduce
1. Move the data zoom slide region
2. Continue with the mouse pressed on the zoom region and move your cursor outside the canvas container.

![error](https://user-images.githubusercontent.com/2999604/58757775-a43ff200-84d7-11e9-860d-85f5e1d05066.gif)

### What is expected?
Data zoom region should continue following cursor position.

### What is actually happening?
Data zoom loses focus and stops moving.

**Comment by Ovilia** [comment]
Do you mean the numbers should be displayed on the sides of data zoom component when the mouse leaves? But this is not expected since the text should only be visible when the mouse is over.

**Comment by d4vsanchez** [comment]
Hello @Ovilia,

No, I mean that the data zoom selected region must continue dragging even though the mouse leaves the canvas container. If you click the zoom region and move the mouse outside the canvas, while it is selected, it should continue moving.

**Comment by d4vsanchez** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2999604/58847675-74b0f700-8649-11e9-86c9-bbef1c8cf021.gif)

This is a better version of the wrong behavior I'm talking about. My mouse is always pressed, but if the cursor goes out the canvas container, you can see that the zoom region just stops moving.

**Comment by Ovilia** [comment]
I see your point. I think the current behavior is to prevent no getting mouse up the event when outside the canvas, because we cannot get the mouse up event any more when it happens outside canvas.

**Comment by d4vsanchez** [comment]
You're right, I was able to do a workaround on this but it seems the behavior is caused by the zrender library.

The `Draggable.js` on zrender file has this line:
```
this.on('globalout', this._dragEnd, this);
```

That line dispatches a `dragend` event each time the cursor moves outside the canvas container.
By modifying the `Draggable.js` on zrender to be as follows, actually fixes the problem I'm facing:

```
this.on('mousedown', this._dragStart, this);
window.addEventListener('mousemove', this._drag.bind(this));
window.addEventListener('mouseup', this._dragEnd.bind(this));
// Removed the globalout event listener
```

Is there any possibility for this to get fixed on this repository or is it better if I actually open an issue on zrender repository to see if this is something feasible to be added there.

**Comment by barts** [comment]
Can a more permanent solution to this be found? Usually when you drag something on desktop, you are able to continue dragging even if your mouse isn't directly inside the track of the object you're moving. The user isn't aware that they're inside a canvas and need to only drag within that (to-them) arbitrary boundary. If you look at this video, it would be frustrating if my mouse cursor stopped moving every time I left the boundary of the window.

![drag-scroll](https://user-images.githubusercontent.com/428873/63301301-39b57b80-c2a8-11e9-923d-053e17868e4f.gif)

**Comment by pissang** [comment]
@d4vsanchez @barts Thanks for the suggestion, we will change the code to listen to the document `mousemove`/`mouseout` events to optimize the drag behavior

**Comment by DoonPort0422** [comment]
Execute me, any news on this feature?
