### ISSUE TITLE
Server side rendering (send prepared pure SVG/XML to the client)

### ISSUE THREAD

**Issue by damir78** [apache/echarts#10600]
### What problem does this feature solve?
Hello Guys,
it will be very nice, if the chart, especially SVG part will be created on the server side. TO the client will be send ONLY SVG/XML and js-to control (Zoom, left, right, etc). Main purpose: disable data transfer (data in JS, CSV- files) and prepare SVG for client. 

### What does the proposed API look like?
Prepare SVG data to be rendered on the client side -> Precompile/Precompress etc

**Comment by Ovilia** [comment]
Currently, we only support [canvas for server-side rendering](https://echarts.apache.org/en/tutorial.html#Server-side%20Rendering), and of course, interaction is not supported.
I think it's a good idea to use SVG so that the interaction can be preserved, although we should do extra work to support this.

**Comment by shmilyoo** [comment]
look at this [http://alonesuperman.com/?p=162](http://alonesuperman.com/?p=162)
may give you some ideas

**Comment by kimutaku001** [comment]
@Ovilia echarts现在是否支持服务端svg渲染了吗,thx

**Comment by kimutaku001** [comment]
@Ovilia Does echarts now support server-side svg rendering? Thx

**Comment by plainheart** [comment]
@kimutaku001 I remember there is a library contributed by the community, which supports generating SVG images in the node environment. The link is here for your reference: https://github.com/baijia-fe/echarts-svg. Note that it is the same as the Canvas SSR, no dynamic interaction is supported.

**Comment by kimutaku001** [comment]
> @kimutaku001 I remember there is a library contributed by the community, which supports generating SVG images in the node environment. The link is here for your reference: https://github.com/baijia-fe/echarts-svg. Note that it is the same as the Canvas SSR, no dynamic interaction is supported.

thx @plainheart ,What's the difference between echars-svg and [https://gist.github.com/pissang/4c32ee30e35c91336af72b129a1a4a73](), because I'm not a professional front-end developer,The difference is only encapsulation and concurrency considerations.

**Comment by plainheart** [comment]
@kimutaku001 I think these two are similar but [baijia-fe/echarts-svg](https://github.com/baijia-fe/echarts-svg) supports multiple rendering modes and slightly handle the font size issue. I didn't ever check and test the concrete difference but you may practice deciding which works for you.

**Comment by kimutaku001** [comment]
> @kimutaku001 I think these two are similar but [baijia-fe/echarts-svg](https://github.com/baijia-fe/echarts-svg) supports multiple rendering modes and slightly handle the font size issue. I didn't ever check and test the concrete difference but you may practice deciding which works for you.

thx!!!
