### ISSUE TITLE
type: line的时候，x轴两点之间间隔太大，不在可视范围内，线就链接不起来

### ISSUE THREAD

**Issue by JamJonson** [apache/echarts#10608]
### Version
4.2.1

### Steps to reproduce
dataZoom使用，type: line的时候，x轴两点之间间隔太大，不在可视范围内，线就链接不起来
image
![image](https://user-images.githubusercontent.com/24426261/58786552-63042b00-861a-11e9-9b02-6d0675d6c954.png)

当两个点在可视范围，
image
![image](https://user-images.githubusercontent.com/24426261/58786564-6ac3cf80-861a-11e9-83b9-eb73a96868e9.png)

yi一个点不在可视范围

### What is expected?
dataZoom使用，有办法做到不在可视范围能连线

### What is actually happening?
有办法做到不在可视范围不能连线

**Comment by susiwen8** [comment]
We are aware of this problem
@Ovilia This is what I talking about.

**Comment by global-peach** [comment]
遇到了相同的问题，在issues #10748 和 #12720 里找到了解决办法，dataZoom.filterMode: 'none' 和 series.clip: false同时配置，即可解决该问题。
