### ISSUE TITLE
无法给折线图hover上去后面的阴影添加点击事件

### ISSUE THREAD

**Issue by JerryYuanJ** [apache/echarts#10619]
### Version
4.2.1

### Steps to reproduce
给一个普通折线图添加了tooltip，设置了axisPointer的type是shadow，现在无法给这个shadow添加点击事件。

### What is expected?
可以在chart.on(eventName, query, handler)中给一个query，让这个功能生效。

### What is actually happening?
给一个普通折线图添加了tooltip，设置了axisPointer的type是shadow，现在无法给这个shadow添加点击事件。

---
在折线图上，鼠标点击到折线图的一个地方，下面有一个表格会动态的加载数据，现在只能给这个点添加上点击事件，但是在移动端的话，是对用户不友好的，所以要给这个点所在的这个“列”添加点击事件。

**Comment by Ovilia** [comment]
测试例子（目前还没有实现该效果）：
```js
option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    series: [{
        type: 'line',
        data:[220, 182, 191, 234, 290, 330, 310]
    }],
    tooltip: {
        show: true,
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    }
};

myChart.on('click', function () {
    console.log('click');
})
```

**Comment by windlany** [comment]
请问这个问题现在有解决吗？
