### ISSUE TITLE
第二次调用 showTip，symbol 消失

### ISSUE THREAD

**Issue by neewbee** [apache/echarts#10611]
### Version
4.0.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xqJKfAQWjP&v=2](https://gallery.echartsjs.com/editor.html?c=xqJKfAQWjP&v=2)

### Steps to reproduce
可以看到第二次，圆点消失

### What is expected?
圆点不消失

### What is actually happening?
圆点消失

**Comment by neewbee** [comment]
临时解决方法：
```javascript
chartInstance.dispatchAction({
            type: 'highlight',
            seriesName: ['name', 'name1', 'name3', 'name4'], // 必须显式传 seriesName 传 id 只会显示一个 symbol
            dataIndex: index,
          });
```

**Comment by neewbee** [comment]
这个问题只在动态设置 option 的时候出现

**Comment by duola8789** [comment]
好像这个问题还么有解决

**Comment by nieloong** [comment]
同等ing
