### ISSUE TITLE
How to get yAxis values on updatezoom event

### ISSUE THREAD

**Issue by spkprav** [apache/echarts#10623]
### Version
4.2.1

### Steps to reproduce
call `computedOptons.yAxis[0].splitNumber` from datazoom function and you should be seeing `5` everytime, eventhough the yAxis in chart is having any other number.

### What is expected?
computedOptons.yAxis[0].splitNumber should be giving dynamic value and not 5 always.

### What is actually happening?
I guess the options are copied directly to computedOptions and computedOptions are not really computedOptions

**Comment by Ovilia** [comment]
I don't think you can get this value now.
