### ISSUE TITLE
type:"bar",使用dataZoom时，鼠标在grid范围内的样式如何更改为cursor:"e-resize"

### ISSUE THREAD

**Issue by fishhotter** [apache/echarts#10629]
### Version
4.2.1

### Steps to reproduce
鼠标移入grid范围内

### What is expected?
鼠标在grid范围内的样式为e-resize

### What is actually happening?
鼠标在grid范围内的样式一直是default

**Comment by Ovilia** [comment]
目前好像不支持，但这个功能挺有用的。
