### ISSUE TITLE
type:bar use svg render, overlapping graphics and label on the Firfox and ios

### ISSUE THREAD

**Issue by DvShu** [apache/echarts#10620]
### Version
3.8.5

### Reproduction link
[https://codepen.io/anon/pen/gJyRpq](https://codepen.io/anon/pen/gJyRpq)

### Steps to reproduce
Open the connection on Firfox or ios: [codepen](https://codepen.io/anon/pen/gJyRpq "codepen")

### What is expected?
Separation of graphics and label

### What is actually happening?
Graphics and label overlap

---
The other versions have similar problems

**Comment by alebon** [comment]
![Screenshot 2019-06-07 at 08 54 46](https://user-images.githubusercontent.com/1381527/59086434-fcc12600-8901-11e9-9a99-25beb9dc12f3.png)

I think it's relates to this bug as well. Firefox 67, SVG, BarChart with echarts 4.2.1

**Comment by handreistoicescu** [comment]
<img width="394" alt="Screenshot 2020-07-29 at 21 08 01" src="https://user-images.githubusercontent.com/29334095/88836671-b69ee400-d1df-11ea-8a8c-9c1334f52edb.png">

Also happens in gauge type series. Firefox 75, SVG, echarts v4.2.1
