### ISSUE TITLE
能否给饼图增加自定义图片支持

### ISSUE THREAD

**Issue by zhaohng** [apache/echarts#1063]
目前symbol只支持折线图和散点图，希望能支持饼图，实现如图的效果
![pie](https://cloud.githubusercontent.com/assets/8034308/5502089/d76b5f00-879f-11e4-9561-155514b32057.png)

**Comment by lin616386** [comment]
求助想知道楼主在环形图中间加入图片的方法？

**Comment by OakMiss** [comment]
求助想知道楼主在环形图中间加入图片的方法？

**Comment by wangzhijun-github** [comment]
求助环形中间能够动态切换图片

**Comment by TLovers** [comment]
> 3Q， 根据提示打印实例， 获取到了相关lable属性,进行设置，完成了。
> 
> ```coffee
>    chart.setOption ctrl.options
>     positionList = chart.chart.pie.series[0].data
>     imageMap =
>       "电视": 'image://image/analysis-tv.png'
>       "平板": 'image://image/analysis-ipad.png'
>       "手机": 'image://image/analysis-phone.png'
>       "电脑": 'image://image/analysis-computer.png'
> 
>     setMarkPoint =  (item)->
>       name = item.name
>       symbol = imageMap[name]
>       x = item.__labelX - 16
>       y = item.__labelY
> 
>       chart.addMarkPoint(0, {
>         symbol: symbol
>         symbolSize: 16
>         data: [{name: name, x: x, y:y}]
>       })
> 
>     for item in positionList
>       setMarkPoint item
> ```
> 
> ![image](https://cloud.githubusercontent.com/assets/3005433/5576977/727d72f8-9042-11e4-8a3e-857e280ebb51.png)

大佬 扇区的起始咋算的啊？ 我想获取饼图上数据分割点的坐标，但是我打印了实例，结合了你的代码，看不懂你的代码，能解释下吗
