### ISSUE TITLE
自定义 sector emphasis无效

### ISSUE THREAD

**Issue by lgyytm** [apache/echarts#10636]
### Version
4.2.1

### Reproduction link
[https://codepen.io/lgyytm/pen/pmMqPb](https://codepen.io/lgyytm/pen/pmMqPb)

### Steps to reproduce
鼠标悬浮自定义样式无效

### What is expected?
高亮样式自定义

### What is actually happening?
无效

**Comment by lgyytm** [comment]
thank you

**Comment by Ovilia** [comment]
请问指的是哪个配置项？

**Comment by lgyytm** [comment]
> 请问指的是哪个配置项？

`emphasis: {
                shadowBlur: 20,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
`
高亮自定义

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-custom.data.emphasis.itemStyle 似乎都没生效，应该是 bug

**Comment by lgyytm** [comment]
是的，多种方式都没生效，多种追加形式我都试了，都没生效

**Comment by Ovilia** [comment]
发现其实是文档写得不是很好，正确的写法是，如果在 `data.emphasis.itemStyle` 中定义了样式，需要在 `renderItem` 中定义 `styleEmphasis: api.styleEmphasis()`，如：
```js
function renderItem(params, api) {
    // ...

    return rectShape && {
        type: 'rect',
        shape: rectShape,
        style: api.style(),
        styleEmphasis: api.styleEmphasis()
    };
}
```

此外，还可以直接在 `renderItem` 中定义高亮样式，如：
```js
function renderItem(params, api) {
    // ...

    return rectShape && {
        type: 'rect',
        shape: rectShape,
        style: api.style(),
        styleEmphasis: {
            color: 'red'
        }
    };
}
```
之后我会改进一下文档。

**Comment by lgyytm** [comment]
好的

**Comment by lgyytm** [comment]
加上styleEmphasis: api.styleEmphasis()，可以使用了，文档好像没有提及到这个信息，同一个demo，还有一个zlevel没有生效的问题，底部和顶部两层canvas层，但是我鼠标移动后却没有生效，前提是一侧来回移动鼠标，而不是，不同颜色之间的来回移动。demo中，我把底层的响应鼠标给关闭了

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-custom.renderItem.return_sector 并没有 zlevel 这个属性吧？只有 z2，用来控制上下关系，但是不会生成额外的 canvas。

**Comment by lgyytm** [comment]
好的，是我没看仔细，我把它理所当然的设到z或zlevel中去了，谢谢解惑

**Comment by Ovilia** [comment]
暂时开着 issue，等文档修复后再关闭，谢谢

**Comment by lgyytm** [comment]
好的，突然还发现一个问题。就是pie是有hoverOffset值，但是我好像没找到自定义sector有这项config提供 @Ovilia

**Comment by Ovilia** [comment]
这个是饼图的属性，不是扇形的属性，所以 sector 里是不会有的。你可以通过改变扇形的半径实现饼图中的这一效果。

**Comment by lgyytm** [comment]
目前是这么处理的，没有的话只能这样了
