### ISSUE TITLE
Bar charts not clipped when using filterMode: 'none'

### ISSUE THREAD

**Issue by ketodiet** [apache/echarts#10646]
### Version
4.2.1

### Steps to reproduce
When using dataZoom with filterMode: 'none'  the bar charts are not clipped within the chart area.

Please see screenshot:
https://imgur.com/zAaEder

### What is expected?
The bar charts should always be clipped within the chart area.

### What is actually happening?
The bar charts bleed out and rendered outside the chart area

---
This should be a trivial issue to fix. The reason for using filterMode: 'none' in the first place is to ensure the line chart is rendered correctly.

**Comment by 100pah** [comment]
Since v4.4.0, [series.clip](https://echarts.apache.org/en/option.html#series-bar.clip) has been supported.

**Comment by BaSmile** [comment]
I'm having the same issue as @ketodiet, is there any future correction about it? 
thank you.
