### ISSUE TITLE
当使用toolbox将bar类型切换到stack类型之后，不能切换回来

### ISSUE THREAD

**Issue by DavidYangLin** [apache/echarts#10653]
### Version
4.2.1

### Steps to reproduce
在官方实例中测试也有这个问题

### What is expected?
希望bar和stack能够来回切换

### What is actually happening?
目前只要其他类型切换到stack类型之后都不能切换回来

**Comment by Ovilia** [comment]
请提供一个例子

**Comment by DavidYangLin** [comment]
就是你们官方实例的例子，该链接访问：https://www.echartsjs.com/examples/editor.html?c=dataset-simple0，代码如下
option = {
    legend: {},
    tooltip: {},
    toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType: {show: true, type: ['stack', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
     },
    dataset: {
        source: [
            ['product', '2015', '2016', '2017'],
            ['Matcha Latte', 43.3, 85.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};
