### ISSUE TITLE
The min and max values of the "TicksCoords" on the axis are not rendered

### ISSUE THREAD

**Issue by louis-neal** [apache/echarts#10656]
### Version
4.2.1

### Steps to reproduce
You can use any axis with category type. After the rendering is complete, change the size of the window, the chart will be scaled, there is a high probability that min ticks, max ticks or both will be lost (not rendered)

### What is expected?
Normal rendering

### What is actually happening?
The min, max, or both are lost (not rendered)

---
The problem is the inline function `littleThan` of `fixOnBandTicksCoords` in Axis.js. The data is compared without considering the precision, resulting in the first and last elements being removed. Please consider using the loss precision difference comparison method, such as the following correction code.
```js
  function littleThan(a, b) {
    return inverse ? (a - b) > 1e-12 : b - a > 1e-12;
  }
```

**Comment by susiwen8** [comment]
PR is welcome, you could submit it.

**Comment by Ovilia** [comment]
@louis-neal Thanks Louis.
Can you provide a test example for this?

**Comment by louis-neal** [comment]
> @louis-neal Thanks Louis.
> Can you provide a test example for this?

example:
```javascript
let a = 856.8, b = 856.8000000000001
a < b  //true (Causes ticksCoords.shift(), so the rightmost axisTick is not rendered.)
b - a > 1e-12 //false (What we want.)
b - a > 0.000000000001 //false
b - a > 0.0000000000001 //true
```

**Comment by Ovilia** [comment]
@louis-neal I mean ECharts demo. You can create one using this template: https://jsfiddle.net/ovilia/kn0Laj4u/

**Comment by louis-neal** [comment]
Please take a closer look at axisTick
[https://jsfiddle.net/rzcLjbqt/](https://jsfiddle.net/rzcLjbqt/) （bug）
[https://jsfiddle.net/rnsqykdt/1/](https://jsfiddle.net/rnsqykdt/1/)
