### ISSUE TITLE
当设置barGap为-100%时，并且设置了barMaxWidth，在zoom组件放大的情况下，发现柱状图在某些区域没画出来

### ISSUE THREAD

**Issue by kukudedaxia** [apache/echarts#10669]
### Version
4.1.0-release

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x4eKYHl966&v=2](https://gallery.echartsjs.com/editor.html?c=x4eKYHl966&v=2)

### Steps to reproduce
放大到某个程度

### What is expected?
每一个数据都能完美展示出来

### What is actually happening?
放大比列在某些值时，发现某些数据没画出来

**Comment by kukudedaxia** [comment]
![image](https://user-images.githubusercontent.com/30620856/59428490-f9e99800-8e0f-11e9-8176-1a8707156727.png)

**Comment by kukudedaxia** [comment]
![image](https://user-images.githubusercontent.com/30620856/59428510-05d55a00-8e10-11e9-8ed4-b9a5c73acc82.png)

**Comment by Ovilia** [comment]
dataZoom 移动不了，请问如何放大的？

**Comment by kukudedaxia** [comment]
> dataZoom 移动不了，请问如何放大的？

![image](https://user-images.githubusercontent.com/30620856/59576719-49bbae00-90f3-11e9-95fd-ad7408f19b7d.png)
鼠标滚轮动不就放大了吗 ，然后移动zoom区域
