### ISSUE TITLE
父容器scale放大后tooltip层级变低被遮挡

### ISSUE THREAD

**Issue by luxinru** [apache/echarts#10661]
### Version
4.2.1

### Steps to reproduce
1.配置一个具有tooltip的饼图/折线图/柱状图
2.通过scale放大图所在的父容器
3.tooltip跑到底层 被数据遮挡

![image](https://user-images.githubusercontent.com/30592140/59331933-aef45580-8d27-11e9-9280-23db8d2c673e.png)

### What is expected?
tooltip始终在顶层

### What is actually happening?
tooltip被遮挡

**Comment by susiwen8** [comment]
Could you provide an example or option?

**Comment by luxinru** [comment]
> Could you provide an example or option?

[pie-simple.html.zip](https://github.com/apache/incubator-echarts/files/3284584/pie-simple.html.zip)
这是我在官方例子下载下来的一个demo 做了一点点修改以复现这个bug

**Comment by susiwen8** [comment]
能把你的demo的option发一下吗？官方例子不是出问题的例子。

**Comment by luxinru** [comment]
> 能把你的demo的option发一下吗？官方例子不是出问题的例子。

不是option的问题 是当父容器用transform: scale(2, 2)缩放的时候就会出现这个bug

**Comment by rickytjx** [comment]
我也发现此问题，请问官方什么时候能解决

**Comment by Dushusir** [comment]
我也发现此问题

出问题例子:https://codepen.io/dushusir/pen/wVBgBx

**Comment by sputnikW** [comment]
renderMode: 'richText'

**Comment by sputnikW** [comment]
tooltip.renderMode:  'richText'
可以避免此问题

**Comment by sputnikW** [comment]
tooltip.renderMode: 'richText'
可以避免此问题（can solve this problem）

**Comment by leipeng** [comment]
try tooltip.extraCssText: 'translateZ(999px);'

**Comment by luxinru** [comment]
> tooltip.renderMode: 'richText'
> 可以避免此问题（can solve this problem）

亲测可行 多谢
