### ISSUE TITLE
borderColor

### ISSUE THREAD

**Issue by rzjLot** [apache/echarts#10678]
### Version
4.2.1

### Steps to reproduce
在series[i]-map3D.data里面试着的itemStyle.borderColor设置了红色，可是生成的内容没有红色

### What is expected?
期望series[i]-map3D.data[i].itemStyle.borderColor能起作用，变成自己写的颜色
![0)WSZWFS0DO)GNZ8H54DWQY](https://user-images.githubusercontent.com/26561378/59545913-44762c00-8f58-11e9-9fc3-4211d50e8b15.png)

### What is actually happening?
期望series[i]-map3D.data[i].itemStyle.borderColor没能改变颜色
![_IB$V(`}6C9QC)IS178@)L9](https://user-images.githubusercontent.com/26561378/59545905-31635c00-8f58-11e9-9fe7-1df273261d89.png)

**Comment by deyihu** [comment]
@rzjLot 
 我试了一下在2d 里好像不能为每个地图区域设置自己的 borderColor(即使我设置了，但是并不能改变每个区域边框的颜色) ，但是可以为每个区域设置自己的填充色，**如果可以为每个区域设置不同的边框的颜色的方法可以告诉我一下**

https://gallery.echartsjs.com/editor.html?c=xOA3XdQ-5x&v=2




关于gl 

gl中我看了一下是不能为每个area设置自己的边框的颜色的，内部源码我看了一下，地图的所有区域的边框使用了一个linesMesh，即不是为每个area创建一个linesMesh,即使你为每条数据设置自己的bordercolor,lineMesh的颜色也是你设置的数据最后一条所对应的颜色

目前map3d中设置边框的颜色有几种可能

1. 在series 中设置   https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=1

2. 在data里设置，series 里不做任何配置，这里分为两种情况，data的数据是是否等于注册的地图的数据

- 如果data的数据区域的数目等于注册地图的数据，边框的颜色为data数据中最后一个数据对应的颜色值，https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=2
- 如果data的数据量小于 地图中注册的区域数目，这是会不显示边框  https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=3  ，原因为gl中如果有一个区域不设置边框的情况下会隐藏整个 lineMesh，当然我认为这个是有点问题的

3.data 和series 同时设置bordercolor，分为两种情况，data的数据是是否等于注册的地图的数据,
- 如果data的数据区域的数目等于注册地图的数据，data里面的配置会覆盖 series ，当然边框的颜色为data 里最后一条数据对应的颜色   https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=4

-  如果data的数据量小于 地图中注册的区域数目,这个时候边框的颜色为 series  配置的颜色，
https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=5  原因为gl内部会渲染所有的area，但是有的area没有配置 bordercolor 会从series  里获取，这时渲染出来的边框就是series  里配置的颜色了，因为只有一个 linesMesh，所以颜色被覆盖了，如果是每个area具有自己的 linesMesh，就不会发生这种情况了，**你说的这个问题，我猜测就是这个原因导致的**


总结：
 - 如果是改变边框的颜色，还是在series  配置，不要在data里配置，因为边框不支持为每个area设置自己的颜色，设置了没有任何意义，如果你一定要在data里设置，请确保data的数据完全覆盖 自己注册的地图的所有数据，并且这样也只是保证边框的颜色为你数据中中最后一条数据对应的配置色。

- 如果2d 里支持为每个area设置 bordercolor的话，那么3d里也应该支持这样的设置，但是目前我没有发现，不过 在2d区域默认是显示边框的，但是在3d默认是不显示的，这个我认为有点问题,我进行了简答的fix,改成了默认显示边框，如果不想显示边框可以将 borderWidth设置成0，这样可以就保证了2d里一样了

https://gallery.echartsjs.com/editor.html?c=xLk2_5kguL&v=6
