### ISSUE TITLE
feature: event 增加 legendhovered 

### ISSUE THREAD

**Issue by kxcc** [apache/echarts#10696]
### What problem does this feature solve?
当同一个图上有多个线条时，同时显示markLine会显得图表非常凌乱，可视性非常差，当用户去关注某个线条时，鼠标去hover图例（或者其他什么更好的方式），再去显示单独的线条，将更加友好

### What does the proposed API look like?
鼠标hover图例，显示当前图例对应线条的markLine，移开时，隐藏。
可通过事件实现，如果能够实现为配置项则更好

**Comment by kxcc** [comment]
当前事件无法响应legend事件

**Comment by Ovilia** [comment]
描述里的需求比较特殊，最好是能新增一个 legendhovered，然后用户监听到这个事件去处理逻辑

**Comment by deqingli** [comment]
# 10970
