### ISSUE TITLE
ie 浏览器下多次setOption 颜色错乱

### ISSUE THREAD

**Issue by jonzhai** [apache/echarts#10701]
### Version
4.1.0-release

### Steps to reproduce
ie 浏览器下多次setOption 颜色错乱

### What is expected?
颜色值顺序不变

### What is actually happening?
颜色颠倒

**Comment by jonzhai** [comment]
注：       this.chart.clear()
            this.chart.setOption(this.config, true);

**Comment by SnailJason** [comment]
I wonder that is the problem solved?
