### ISSUE TITLE
使用 dataZoom 放大图表时，若部分数据在显示区域外，有时会显示一条直线将数据强行封闭

### ISSUE THREAD

**Issue by sagnitude** [apache/echarts#10709]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xXiJOXHmwj&v=1](https://gallery.echartsjs.com/editor.html?c=xXiJOXHmwj&v=1)

### Steps to reproduce
打开 gallery 链接，即可看到封闭直线

### What is expected?
显示区域内的曲线正常显示，显示区域外的图表内容能正常隐藏，不应该出现图中的首尾相连的直线

### What is actually happening?
当有数据在区域外，有时会出现一条直线将图像封闭

**Comment by marlonchiu** [comment]
显示区域外的图表内容能正常隐藏   "clipOverflow": true,

**Comment by sagnitude** [comment]
> 显示区域外的图表内容能正常隐藏 "clipOverflow": true,

试过了，多余的封闭直线仍然存在


![微信截图_20190620154045](https://user-images.githubusercontent.com/5506506/59830247-d5427280-9371-11e9-9562-ae8fe78f7ddb.png)

**Comment by sagnitude** [comment]
![微信截图_20190620154525](https://user-images.githubusercontent.com/5506506/59830555-80532c00-9372-11e9-8f4b-1f33e240f6d9.png)

**Comment by marlonchiu** [comment]
> > 显示区域外的图表内容能正常隐藏 "clipOverflow": true,
> 
> 试过了，多余的封闭直线仍然存在
> 
> ![微信截图_20190620154045](https://user-images.githubusercontent.com/5506506/59830247-d5427280-9371-11e9-9562-ae8fe78f7ddb.png)

我知道那个封闭的直线还是存在的   "clipOverflow": true这个属性我觉得应该是true 可以吧图表外的区域截断   那个封闭直线的问题暂时还没有思路，可以期待echarts开发人员回复啦

**Comment by Ovilia** [comment]
应该是个 bug
