### ISSUE TITLE
Responsive SVG rendered charts

### ISSUE THREAD

**Issue by dvago** [apache/echarts#10724]
### What problem does this feature solve?
Hardcoded values within the width and the height attributes of an SVG make the chart not responsive. Changing the way the SVG is being printed out could remove an extra DOM element and make developers capable to work with the SVG chart via CSS without using hacks to edit the rendered element via javascript.

### What does the proposed API look like?
Following up the closed issue: ecomfe/vue-echarts#355

Given the charts generated as SVG, could it be possible to clean up the rendered html?

In order to render the chart in a responsive way the generated DIV which wraps the SVG tag could be completely removed and the SVG tag could have the width and height attributes replaced by the viewBox

Eg. given width and height from the initOptions instead of printing out:
width="250" height="70" the output could be viewBox="0 0 250 70" so the developer/user could define via CSS the wanted sizing

ref.
<img width="902" alt="Screenshot 2019-06-24 at 13 41 11" src="https://user-images.githubusercontent.com/5074033/60019519-f6fb6c80-9685-11e9-87a2-764e7135e92c.png">

**Comment by Ovilia** [comment]
Hi. It's recommended to call [chart.resize()](https://echarts.apache.org/en/api.html#echartsInstance.resize) when the container size changes. Changing the viewbox won't work since the position of inner elements are all calculated by ECharts. It won't work with a simple percentage calculating method.

**Comment by dvago** [comment]
Good morning/evening @Ovilia. Having a javascript function maybe attached to an event listener to do a resize of an SVG (which is a vector graphic) is quite too much. Have you tried to replace the `width` and `height` attributes with a `viewBox`? Please do try and come back to me.

A simple test could be: on Finished hook `setAttribute(0, 0, width, height)` and `removeAttribute('width')` and `('height')`

**Comment by dvago** [comment]
Good morning/evening, Would it be possible to have an update on this issue? Thank you so much for the support and the time.

**Comment by Ovilia** [comment]
What's your scenario for this case? If you wish to resize the chart, you should not use the SVG exported or the SVG DOM saved. This is not just an issue of resizing SVG, the position of its inner components should also change with the size.

**Comment by dvago** [comment]
Thanks @Ovilia to getting back, as I previously said, in order to make a chart (any SVG) responsive is a good practice to remove the attributes `width` and `height` from the SVG tag itself and rely on the `viewBox` instead.

The content of an SVG (all the inner points) remain attached to the viewBox so there are no issues on removing the constrains mentioned in my previous comments.

Please have a look at this Jsfiddle URL: https://jsfiddle.net/2ebuxykz/1/, the example will clarify you what I'm asking for.

Related to the example, resizing the output frame you will notice how the first SVG (generated via eCharts) doesn't change at all meanwhile the second SVG (generated and tweaked later on) is completely responsive (it resizes depending on the content where the charts applied on)

Please do let me know if you have any concern.
