### ISSUE TITLE
Treemap : Lables not display in some of the blocks.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/echarts#10731]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/25bgnm03/1/](https://jsfiddle.net/25bgnm03/1/)

### Steps to reproduce
- The output of treemap is displayed correctly.
- If we have only one or two labels then it's displayed all labels in all blocks of the treemap.
- If we have multiple labels to display in one block then some of the blocks displayed blank.

### What is expected?
labels should be displayed properly in all the blocks. Or it should display some of the labels. AS per demo, it should display one to eight labels at least.

### What is actually happening?
Treemap result is displayed but it does not show labels in some of the blocks.

**Comment by Monali-ITT** [comment]
Any update on this issue? Please reply.

**Comment by Monali-ITT** [comment]
@Ovilia any updates?

**Comment by pissang** [comment]
@Monali-ITT Please try the latest 5.0

**Comment by Monali-ITT** [comment]
@pissang thank you.
Still this issue is reproducable.I am using typescript version of echart. i.e now  4.9.3.On that its not working. If you check https://jsfiddle.net/25bgnm03/1/ this link, if we keep only 1-4 lines then its displaying in all blocks.If have all lines then not displayed.At least it should display 1-2-3-4 and then ... link this.

**Comment by Monali-ITT** [comment]
any updated?

**Comment by ruben82** [comment]
Are there any updates for this issue?
Thanks
