### ISSUE TITLE
dataZoom为inside类型时多种类型图表在移动端无法实现手势缩放

### ISSUE THREAD

**Issue by qcasxy** [apache/echarts#10744]
### Version
4.2.1

### Steps to reproduce
1、使用安卓或苹果手机打开网站(http://file.hence.cn/szgc/barGrad.html)
2、页面展示后在触屏上两指滑动。

### What is expected?
图表可以放大缩小

### What is actually happening?
未放大、缩小

---
 #10401 
在PC端浏览器中显示时可以通过鼠标滚轮正常放大缩小，但是在移动端无效果。
以上提供网址同官方实例源码(https://www.echartsjs.com/examples/editor.html?c=bar-gradient)

**Comment by wu568431592** [comment]
什么时候可以修复啊。换到4.1.0 或 4.0.0 无果

**Comment by Ovilia** [comment]
ECharts 靠社区志愿者维护，一般来说修复时间不会很快，因为每个人都是义务地在帮忙。如果比较急的话，欢迎给我们提 PR。

**Comment by Naclplus** [comment]
> ECharts 靠社区志愿者维护，一般来说修复时间不会很快，因为每个人都是义务地在帮忙。如果比较急的话，欢迎给我们提 PR。

4.3.5还没有修复这个问题吗？

**Comment by ninjarz** [comment]
我查了下这个bug，是zrender的问题，然后看到最新的zrender源代码已经修了这个问题，但是还没release，自己下最新的zrender自己build可以解决这个问题

**Comment by ChunrunHan** [comment]
> 我查了下这个bug，是zrender的问题，然后看到最新的zrender源代码已经修了这个问题，但是还没release，自己下最新的zrender自己build可以解决这个问题

请问，微信小程序引用echart,去哪里下载修复这个问题的代码？

**Comment by ChunrunHan** [comment]
大佬们，请问哪个版本解决这个问题了啊？

**Comment by Naclplus** [comment]
> 大佬们，请问哪个版本解决这个问题了啊？

我用了@latest 版本就好了

**Comment by ChunrunHan** [comment]
> > 大佬们，请问哪个版本解决这个问题了啊？
> 
> 我用了@latest 版本就好了

微信小程序，引用了echarts-4.5.0 版本，安卓手机还是无效啊，微信开发者工具和ios没问题。。。

**Comment by wu568431592** [comment]
> > > 大佬们，请问哪个版本解决这个问题了啊？
> > 
> > 
> > 我用了@latest 版本就好了
> 
> 微信小程序，引用了echarts-4.5.0 版本，安卓手机还是无效啊，微信开发者工具和ios没问题。。。

"echarts": "^4.0.0", 这个好像可以

**Comment by ChunrunHan** [comment]
> > > > 大佬们，请问哪个版本解决这个问题了啊？
> > > 
> > > 
> > > 我用了@latest 版本就好了
> > 
> > 
> > 微信小程序，引用了echarts-4.5.0 版本，安卓手机还是无效啊，微信开发者工具和ios没问题。。。
> 
> "echarts": "^4.0.0", 这个好像可以

大佬，还是不行啊。。。

**Comment by YueminHu** [comment]
`^4.6.0` 这个版本可以了

**Comment by qdsncaq** [comment]
微信小程序中使用了4.6.0版本，在华为mate9、华为P20 pro、华为honor 20i手机端真机环境下依然存在该问题；小米5s plus、华为荣耀8X测试没问题。
