### ISSUE TITLE
Cannot get click event when clicking on Theme River chart data point

### ISSUE THREAD

**Issue by ruixuel** [apache/echarts#10778]
### Version
4.2.1

### Steps to reproduce
1. create Theme River chart
2. bind click event and handler on chart
3. click on Theme River chart, the click handler cannot get click event

### What is expected?

Click handler should get click event

### What is actually happening?
Click handler cannot get click event when clicking on theme river chart

**Comment by Ovilia** [comment]
Duplicate of #5173
