### ISSUE TITLE
x轴第一个刻度线在特定分辨率下不显示

### ISSUE THREAD

**Issue by jay0815** [apache/echarts#10803]
![WechatIMG21](https://user-images.githubusercontent.com/16587728/60653428-9e458400-9e7c-11e9-80eb-8649d6e3611c.jpeg)
![WechatIMG22](https://user-images.githubusercontent.com/16587728/60653530-c634e780-9e7c-11e9-90da-010e919c2ac8.png)

### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xtuU53euri&v=1](https://gallery.echartsjs.com/editor.html?c=xtuU53euri&v=1)

### Steps to reproduce
1、开启控制台
2、由1920 * 700 调整至 1807 * 700 （同时存在于 1757 * 700、1732 * 700 等好多分辨率）
3、第一个刻度线消失
4、由1870 * 700 调整至 1820 * 700 
5、第一个刻度线又再次出现

### What is expected?
任何分辨率下的
初次图表绘制或者重绘
在 axisTick.show 为 true 时
刻度线应全部显示

### What is actually happening?
在特殊（规律未知）的分辨率下存在 x轴第一个刻度线不显示

**Comment by Ovilia** [comment]
试试这个设为 true https://echarts.apache.org/zh/option.html#xAxis.axisLabel.showMinLabel

**Comment by jay0815** [comment]
> 试试这个设为 true https://echarts.apache.org/zh/option.html#xAxis.axisLabel.showMinLabel

谢谢您的回复，但是我在线上试过了，还是不存在这个问题
![WechatIMG23](https://user-images.githubusercontent.com/16587728/60657322-be2c7600-9e83-11e9-81c0-b9b52e5963a9.png)

**Comment by jay0815** [comment]
> 试试这个设为 true https://echarts.apache.org/zh/option.html#xAxis.axisLabel.showMinLabel

我修改了下 Reproduction link，已经调整为了我在线的demo地址。

**Comment by Ovilia** [comment]
确认了一下，应该是 bug
