### ISSUE TITLE
Scrolling out of chartview without mouse out makes chart scroll without click and drag (Candle stick and volume)

### ISSUE THREAD

**Issue by Sahil624** [apache/echarts#10807]
### Version
4.2.0-rc.2

### Steps to reproduce
1) Open chart (I was using candlestick and volume chart) and scroll it, now exit chart without stop clicking.
2) Now when you have scrolled outside chart release mouse button.
3) Now move mouse pointer back to chart window without clicking mouse button.
4) Observe chart is scrolling automatically without clicking mouse button.
5) This continues until I click inside chart window.

### What is expected?
Once scrolled outside chart window while dragging scrolling should stop at mouseout.

### What is actually happening?
Scrolling continues even if we return back to chart window and continues until clicked inside chart window.

---
I was using [**ngx-echarts**](https://github.com/xieziyu/ngx-echarts) for angular but this issue is seen in echarts [example ](https://echarts.apache.org/examples/en/editor.html?c=candlestick-touch)as well. So, this might be echarts 

### Gif if anyone need to refer.
![echarts](https://user-images.githubusercontent.com/20486172/60703726-229d1300-9f20-11e9-9d7c-91ee31cf74a7.gif)

When I am exiting echarts first time I have pressed mouse button. But when I am entering chart view after that I have not clicked any button just moving my mouse pointer.

**Comment by tmtron** [comment]
This sounds much like #10675

**Comment by Sahil624** [comment]
Seems like it.

**Comment by vivsvaan** [comment]
@Sahil624 I used Mouse Events to release the mouse click when we leave ChartView.
When we use <div echarts ...></div> to produce our chart, it generated a <canvas> element in HTML.
You just have to trigger a mouseup event on that <canvas> element when mouse leaves the ChartView.

**Comment by dr-itz** [comment]
for anyone facing the same problem, here's the diff of a fix in one of my projects:

```diff
index 878c0d3..6ce67f1 100644
--- a/src/lib/mixins/echarts-mixin.ts
+++ b/src/lib/mixins/echarts-mixin.ts
@@ -7,8 +7,11 @@ import { debounce } from '@/lib/utils/utils'
 export default class EChartsMixin extends Vue {
  protected echart!: ECharts;
  protected chartOptions!: EChartOption
+ protected echartElement!: HTMLElement

  private echartTriggerResize = debounce(() => this.resizeChart(), 50) as (e: Event) => void
+ private echartMouseDown = () => this.handleChartMouseDown()
+ private echartMouseUp = (event: MouseEvent) => this.handleChartMouseUp(event)

  createEChart(element: Element): void {
    if (this.echart)
@@ -23,8 +26,10 @@ export default class EChartsMixin extends Vue {
    }

    this.echart = EChart(element, theme)
+   this.echartElement = element as HTMLElement
    window.addEventListener('resize', this.echartTriggerResize)
    window.addEventListener('orientationchange', this.echartTriggerResize)
+   this.getEChartInner()?.addEventListener('mousedown', this.echartMouseDown)
  }

  resizeChart(): void {
@@ -44,4 +49,19 @@ export default class EChartsMixin extends Vue {
      this.echart.dispose()
    this.echart = undefined
  }
+
+ private getEChartInner(): Element | null {
+   return this.echartElement.querySelector(':scope > div:first-child')
+ }
+
+ private handleChartMouseDown() {
+   window.addEventListener('mouseup', this.echartMouseUp)
+ }
+
+ private handleChartMouseUp(event: MouseEvent) {
+   window.removeEventListener('mouseup', this.echartMouseUp)
+
+   const newEvent = new MouseEvent('mouseup', event)
+   setTimeout(() => this.getEChartInner()?.dispatchEvent(newEvent))
+ }
 }
```
