### ISSUE TITLE
Rotate graph label

### ISSUE THREAD

**Issue by 7aklhz** [apache/echarts#10812]
### What problem does this feature solve?
Hi, I am using the graph chart. In the "links" option, I have added the label between the source and the target. I know I can do "align" and "verticalAlign", but it would be great to be able to rotate the label, so that it would be horizontal. 

### What does the proposed API look like?
Add "Rotate" option to series-graph.links.label

**Comment by Ovilia** [comment]
Is this what you want? https://echarts.apache.org/en/option.html#series-graph.label.rotate

**Comment by KonradHolubek** [comment]
Yes... but on links.label (currently it does not work/does not exist)
