### ISSUE TITLE
地图下钻后调用.clear()方法依旧不能清除上一层地图中的部分series的一些效果|the echarts.clear()  no longer has any effect when Not zero that lines series. trailLength |

### ISSUE THREAD

**Issue by ananix** [apache/echarts#10828]
### Version
3.4.0

### Reproduction link
[https://ananix.github.io/qianxi/xiazhuan.html](https://ananix.github.io/qianxi/xiazhuan.html)

### Steps to [reproduce]
1.我有一个地图，上面有line，effectScatter
2.我要点省市地图下钻，下钻到下级地图后重新加载line，effectScatter等的数据 
3.触发点击事件后，调用echarts.clear()方法清空数据
4.重新加载地图，发现在新的地图里面并没有清除掉其中一个line系列的数据，即新图上仍然存在line
5.调试发现，仅当line的配置项trailLength: 0.7,（ 不为零时），才有这种情况
6.目前需求上层line 的trailLength必须不为零，且在下钻时我要清除line
7.此为bug？

### What is expected?
清除数据

### What is actually happening?
.clear()不能清除line的配置项trailLength的数据

---
下钻时请点击甘肃-陇南-西和（因为其他地区还没有map数据）

**Comment by ananix** [comment]
`
//series
{
                    name: item[0],
                    type: 'lines',
                    zlevel: 1,
                    effect: {
                        show: true,
                        period: 6,
                        trailLength: 0.7,
                        //color: '#fff',
                        color: '#bdc3c7',
                        symbolSize: 3
                    },
                    lineStyle: {
                        normal: {
                            color: color[i],
                            width: 0,
                            curveness: 0.2
                        }
                    },
                    data: convertData(item[1])
                }
//

//重新注册地图后调用
                        myChart.clear();
                        myChart.setOption(option, {
                            notMerge: true,
                            lazyUpdate: false
                        });

`

**Comment by lh8725473** [comment]
我也遇到了同样的问题，请问如何解决的。现在只能dispose() 重新初始化，这样性能肯定比较差
