### ISSUE TITLE
tree关系边显示内容

### ISSUE THREAD

**Issue by yjwww** [apache/echarts#10830]
### What problem does this feature solve?
只有节点显示内容有限

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=graph-simple

**Comment by yjwww** [comment]
> https://echarts.apache.org/examples/zh/editor.html?c=graph-simple

I want to use it in tree structure

**Comment by Ovilia** [comment]
What is a tree structure?

**Comment by goSunadeod** [comment]
我觉得这个需求 还是需要增加的吧

**Comment by deqingli** [comment]
@yjwww 你是想显示 label 还是 hover edge 显示 tooltip?

**Comment by HeavyRainDi** [comment]
Would you like to ask, is this function realized?

**Comment by fxxpro** [comment]
+1,当type为tree时,鼠标hover或者click edge时,显示tooltip
