### ISSUE TITLE
热力图encode中指定seriesName，并没有读取维度数据

### ISSUE THREAD

**Issue by ThinkontrolSY** [apache/echarts#10914]
### Version
4.2.1

### Steps to reproduce
在type为heatmap的series中，数据从dataset来，
dataset中dimension设置为：['name', 'x', 'y', 'value']
encode字段中指定seriesName的维度为'name',
series中tooltip.formatter: (params) => {params.seriesName}

设置如下：

```typescript
dataset: [
    {
      source: [],
      dimensions: ['lineId', 'resourceId', 'priority', 'amount', 'x', 'y'],
    }
  ],
  series: [
    {
      type: 'heatmap',
      encode: {
        x: 'x',
        y: 'y',
        itemName: 'lineId',
        seriesName: 'lineId',
        value: ['amount', 'priority'],
        itemId: 'resourceId',
        tooltip: ['amount', 'priority'],
      },
      tooltip: {
        formatter: ({ data, seriesName }) => {
          console.log(seriesName);
          return `${data.lineId}<br/>${data.resourceId}<br/>优先级: ${
            data.priority
          }<br/>利用次数: ${data.amount}`;
        },
      },
    },]
```

### What is expected?
console.log应该输出data的name字段的值

### What is actually happening?
console.log实际输出了字符串'name'

**Comment by Ovilia** [comment]
请提供完整的代码 https://gallery.echartsjs.com/editor.html

**Comment by ThinkontrolSY** [comment]
@Ovilia 
https://gallery.echartsjs.com/editor.html?c=xVapz-dHF7&v=1
如代码中
140行，encode里面指定seriesName: 'lineId'
dataset中source里面的数据lineId分别是'a', 'b', 'c', 'd'
但lengend显示的是字符'lineId'，而不是实际的值'a', 'b', 'c', 'd'

**Comment by ThinkontrolSY** [comment]
any work arround?
