### ISSUE TITLE
ECharts- How to show horizontal scroll bar with 3 lines of legend, and after that scroll if items doesn't fit in 3 lines

### ISSUE THREAD

**Issue by ayede** [apache/echarts#10922]
### Version
4.2.1

### Steps to reproduce
Create a Echarts line chart with 50 series. set to show the legends at top with vertical scroll bar. 

### What is expected?
Scroll should shown with 3 lines. Every line should show 4 legends. if legends doesn't fit in 3 lines, then show the vertical scroll.  

### What is actually happening?
Chart is showing vertical scroll with only one item in one line. And it is also overlapping on the chart body.

---
I tried with vertical and horizontal scroll. In vertical scroll, it shows only one legend in one line. this is the problem. Actually, ECharts should show the what ever possible legends in one line. If there is enough space to have 2 legends in one line, it should show 2 legends in one line. It should show 3 lines and if all legends doesn't fit in three lines, then should add vertical scroll. But, currently legends overlap to chart.

Currntly Happening - 
![image](https://user-images.githubusercontent.com/9910877/61881027-9759e080-af13-11e9-9d5a-a33c9b04b424.png)

Expected - 
![image](https://user-images.githubusercontent.com/9910877/61881077-a17bdf00-af13-11e9-9c15-2d775cb4be01.png)

**Comment by ayede** [comment]
Can anyone please update me on this? If this is possible or not possible, can you please confirm this?

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#legend.type Try legend typed of scroll.

**Comment by ayede** [comment]
> https://echarts.apache.org/en/option.html#legend.type Try legend typed of scroll.

if you check the screenshot, then you can see that we already used the scroll.

**Comment by Ovilia** [comment]
Legend component cannot automatically avoid grid area.

**Comment by SiddAjmera** [comment]
@Ovilia, any updates on this thread?

I'm on v4.6 and I've used scroll on the chart to get something like this:

![image](https://user-images.githubusercontent.com/5053266/127951790-0d57692e-536e-4dfd-a5d4-c72fe9f33448.png)

But I was something like this as per design:

![image](https://user-images.githubusercontent.com/5053266/127951836-57b7d3ab-5efc-436e-a3b5-2ae93311afb6.png)

So the legend should scroll horizontally and should have two rows. At the moment, I just get one row.

**Comment by ayede** [comment]
I am still looking for this feature. Is there any chance that we can get this support from echarts?

**Comment by batpawe** [comment]
That would be great to see this feature!
