### ISSUE TITLE
Type Graph, Edges use data arrays index rather than name.

### ISSUE THREAD

**Issue by missionz3r0** [apache/echarts#10944]
### Version
4.2.1

### Steps to reproduce
For a circular or force graph create a data array with names that do not correspond to each objects index within the array.

For example:
```
data = [{
    id: 1,
    name: 1,
  }, {
    id: 2,
    name: 2,
  }];

edges = [{
    source: 1,
    target: 2
}];
```

### What is expected?
An edge is created between node 1, and node 2

### What is actually happening?
An edge is being made between the node at array index 1, and array index 2.

**Comment by missionz3r0** [comment]
After some more digging, it seems this only occurs when the name is a number.

**Comment by Ovilia** [comment]
`index` is first checked and then `name`. This is a feature rather than bug.

**Comment by missionz3r0** [comment]
I see what you're saying, but that splits from the API for [links](https://echarts.apache.org/en/option.html#series-graph.links) then. 

The API tells us that it uses the name, but in the case that you are using numbers for your name and edges it checks for the index? I would think it'd make more sense to first check for the name, and if that didn't exist then check the index.

**Comment by Ovilia** [comment]
I got your point. Needs further discussion on this.

**Comment by pissang** [comment]
@missionz3r0 I think it's because you are using `number` type in edges and echarts guess it's an index. You can use `string` type instead.

data = [{
    id: 'n1',
    name: 'n1',
  }, {
    id: 'n2',
    name: 'n2',
  }];

edges = [{
    source: 'n1',
    target: 'n2'
}];
