### ISSUE TITLE
桑基图能否溯源到最原始的源节点，现阶段只能溯源上一级和下一级

### ISSUE THREAD

**Issue by jyhmc0814** [apache/echarts#10959]
### What problem does this feature solve?
解决了某个产品溯源所有的原材料，现阶段只能看到成品前一阶段的材料

### What does the proposed API look like?
source:true

**Comment by deqingli** [comment]
Thank you for your suggestion!

**Comment by caowenyu** [comment]
@deqingli 这个功能是否有开发计划，或者如果想实现这个功能，基于现在的sankey有什么办法吗。
