### ISSUE TITLE
Problems with the unit test

### ISSUE THREAD

**Issue by LeeYoung624** [apache/echarts#10955]
### Version
4.2.1

### Steps to reproduce
Hey echarts guys! I found echarts recently and I like it! It helped me a lot and I'd like to contribute to echarts. But it confuses me that some unit tests were failed (same result in `master` branch and the lateset release version `4.2.1`) : `111 specs, 20 failures`
I didn't change any code of echarts, so I'm quite confused : is the unit test result correct? Or I should run the unit test in another way? (I could not run `ut.html` in `Chrome` directly because of some cross origin errors, so I run the unit tests in tomcat and it works)

### What is expected?
All unit tests are passed

### What is actually happening?
111 specs, 20 failures

**Comment by pearson-g** [comment]
@pissang   我也遇到同样的问题，单元测试用例有20个跑失败！麻烦帮忙看一下，谢谢
