### ISSUE TITLE
label clicking events

### ISSUE THREAD

**Issue by qqfei1858** [apache/echarts#10969]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x0-ExSkZDM](https://gallery.echartsjs.com/editor.html?c=x0-ExSkZDM)

### Steps to reproduce
比如链接中的 "上海" 这个标签想要做点击事件是否可以做到?

### What is expected?
geo标点文字触发事件

### What is actually happening?
geo标点文字无法触发事件

**Comment by qqfei1858** [comment]
@pissang @Ovilia

**Comment by Ovilia** [comment]
标签目前是没有事件支持的，只有数据点才有

**Comment by mansion-sun** [comment]
https://echarts.apache.org/zh/option.html#xAxis.triggerEvent

**Comment by mansion-sun** [comment]
https://echarts.apache.org/zh/option.html#xAxis.triggerEvent
