### ISSUE TITLE
关于多地图之间的markLine

### ISSUE THREAD

**Issue by xingmolu** [apache/echarts#1098]
请问多地图之间如何增加markLine，目前通过经纬度添加markLine，只能标识在一张图上，多张地图的经纬度就没有关系了，怎么让他们有关系起来，并且左边的地图某个省可以往右边地图的市画markLine呢？
![image](https://cloud.githubusercontent.com/assets/2590258/5579541/3dd61a5c-9077-11e4-8ce2-38398482a5d1.png)

**Comment by xingmolu** [comment]
@kener 想过点击对应省时，获取对应地市的经纬度，根据经纬度来生成对应的平面坐标x,y，但是两个地图的比例尺不同？不知道如何生产这个平面坐标，请教下有什么好办法不？

**Comment by kener** [comment]
地图有接口，分别问地图要

**Comment by xingmolu** [comment]
@kener oK，今天 去看看，看来API看得不够仔细，麻烦你来
