### ISSUE TITLE
关于大量数据画图崩溃问题

### ISSUE THREAD

**Issue by ghost** [apache/echarts#110]
echarts的文档相当的丰富是我选择它的原因，我在作性能测试的时候发现数据量大些画图很慢或者画不出来，浏览器卡死等现象，不知是使用问题还是什么原因，忘指教：

使用静态文件，画折线图时，模拟了10000个点，Y轴和X轴各10000个，发现在火狐下根本画不出来，浏览器还挂了，后来用flotr2画图，很快就将10000个点渲染出来了，但flotr2文档相当糟糕， 恳请指教下，是什么问题，是我用法有误？？（测试例子是参考官网的例子造的数据）

实验结果：当点超过1000个的时候，就变的相当的卡！

另外一点是：当数据点很多的时候，X坐标一片空白，什么都不显示，放大以后才有效果

恳请望指教！

**Comment by chaolinyi** [comment]
学习

**Comment by chaolinyi** [comment]
学习

**Comment by bbcdabao** [comment]
> 大数据务必关闭动画显示，animation设为false就好，我自己测1万数据基本也是秒出

数据显示很快，但是当用到brush 矩形选点超过 9999 个点就出现刷新问题
大概一般显示空白，此时缩放一下就好了，或者更新一下，但是体验不好了
