### ISSUE TITLE
Graph becomes crazy when zooming in or out

### ISSUE THREAD

**Issue by ITAYC0HEN** [apache/echarts#11024]
### Version
4.2.1

### Steps to reproduce
1. Zoom in, see that some clusters are getting crazy
2. Zoom out, inspect the same
3. Roam around using the mouse and see that some nodes are forcibly moving 

### What is actually happening?
As you can see in the gif below, upon zooming using the mouse-wheel some parts of the graph are getting crazy and raving around. For example, notice the blue cluster next to the cursor.

![ezgif-4-046199370788](https://user-images.githubusercontent.com/20182642/63082009-bdd8cd80-bf4d-11e9-9566-bfb35da03dc2.gif)

### What is expected?
I expect the graph to zoom in and out smoothly. I don't want any other movement in the graph upon zooming

### More Details
When the graph is ready and stands still, my goal is to hide the node-labels from a specific zoom and then when a user zoom in, the labels will appear again. I used data zoom in order to hook the event of zooming and calculating the scale. 

So ideally, I just want to hide the labels when zooming out too much and showing them when zooming in to a certain port.

Here is the configuration and the related JS function. The function itself isn't the problem, the problem is in the Options (tested by removing parts)

**Options**

This is the JS function responsible for showing\hiding the labels

```
myChart.on('dataZoom', function (params) {
    var start = params.batch[0].start;
    var end = params.batch[0].end;


    if(myChart.getOption().series[0].zoom <= 0.3 && myChart.getOption().series[0].zoom != 1 && !isLabelsHidden)
    {
        myChart.setOption({series: [{label: {
            show: false}}]});
        isLabelsHidden = true;
    } else if(myChart.getOption().series[0].zoom > 0.3 && myChart.getOption().series[0].zoom != 1 && isLabelsHidden)
    {
        myChart.setOption({series: [{label: {
            show: true}}]});
        isLabelsHidden = false;
    }
});


myChart.on('dataZoom', function (params) {
    var start = params.batch[0].start;
    var end = params.batch[0].end;


    if(myChart.getOption().series[0].zoom <= 0.3 && myChart.getOption().series[0].zoom != 1 && !isLabelsHidden)
    {
        myChart.setOption({series: [{label: {
            show: false}}]});
        isLabelsHidden = true;
    } else if(myChart.getOption().series[0].zoom > 0.3 && myChart.getOption().series[0].zoom != 1 && isLabelsHidden)
    {
        myChart.setOption({series: [{label: {
            show: true}}]});
        isLabelsHidden = false;
    }
});

```

And here are the options, configuration -- the problem happens only when adding "dataZoom", "xAxis" and "yAxis".
```
option = {
    title: {
        top: 'bottom',
        left: 'right'
    },
    feature: {
        magicType: {
            type: ['line', 'bar', 'stack', 'tiled']
        }
    },
    legend: [{
        // selectedMode: 'single',
        data: categories.map(function (a) {
            return a.name;
        })
    }],
    animation: true,
    animationDuration: 1500,
    scaleLimit : {
    },
    animationEasingUpdate: 'quinticInOut',
    dataZoom: [
        {
            type: 'inside',
        },
        {
            type: 'inside',
        }
    ], 
    xAxis: {
        show: false,
        scale: true,
        silent: true,
        type: 'value'
    },
    yAxis: {
        show: false,
        scale: true,
        silent: true,
        type: 'value'
    },
    
    series : [
        {
            name: 'some name',
            type: 'graph',
            layout: 'force',
            force: {
                initLayout: 'circular',
                edgeLength: 1200,
                repulsion: 100000,
                gravity: 0.4
            },
            zoom: 0.15,
            data: graph.nodes,
            links: graph.links,
            categories: categories,
            roam: true,
            focusNodeAdjacency: true,
            draggable: true,
            itemStyle: {
                normal: {
                    borderColor: '#fff',
                    borderWidth: 1,
                    shadowBlur: 10,
                    shadowColor: 'rgba(0, 0, 0, 0.3)'
                }
            },
            label: {
                position: 'outside',
                show: true,
                formatter: '{b}'
            },
            lineStyle: {
                color: 'source',
                curveness: 0,
                width: 2
            },
            emphasis: {
                lineStyle: {
                    width: 8
                }
            }
        }
    ]
};

```

**Comment by pissang** [comment]
Every time you setOption, the graph will start running force directed layout again. But the behavior should be more like other nodes and only move slightly. The crazy ones are not expected. 

Can you give me a more detailed option with data. So I can use it to reproduce it and try if it can be fixed by tuning the layout parameters.

Also we should support the label visibility callback when graph is zoomed later so you don't need to setOption every time. But it will take some time.

**Comment by ITAYC0HEN** [comment]
Thanks for your response! :) 
So basically, as I briefly mentioned, it is happening even when i disable the javascript function that applies the new options. So even if this function won't be executed, and the new options won't apply, it will still go crazy. 

I will be happy to provide this data privately because it is sensitive and cant be disclosed. Is there a way i can send it to you?

**Comment by ITAYC0HEN** [comment]
ping @pissang 
Should I send you the data somehow private?

**Comment by Ovilia** [comment]
@ITAYC0HEN You should simplify the data with mock one and put it online for us to check. No private communication because it can help those with the same problem.
Thanks for understanding.

**Comment by ITAYC0HEN** [comment]
@Ovilia & @pissang - thank you for your quick response and sorry for my delay. 
Here is an attached zip file with a mock website. You can use your mouse wheel to zoom in and out and inspect the weird behavior. As a reminder, my goal is to show the labels upon zooming in but hide them when the website is zoomed out to a certain point.



[site - mock.zip](https://github.com/apache/incubator-echarts/files/3600582/site.-.mock.zip)

**Comment by ITAYC0HEN** [comment]
Hi, do you have any suggestions for a quick-patch I can implement to fix this issue? Sadly this is blocking us to use echarts in production

**Comment by pissang** [comment]
@ITAYC0HEN Hi, Sorry for the late reply.

I added a layout option: `'friction'`. It will slow down the nodes' movement. So we can try setting a smaller value when we update the option on dataZoom. Like following

![image](https://user-images.githubusercontent.com/841551/65154158-9352c680-da5d-11e9-90c2-0976f4da99f5.png)

The value ranges from 0 to 1.

I tried it in your project and it works well. [site-mock.zip](https://github.com/apache/incubator-echarts/files/3626698/site-mock.zip)

But this feature is still experimental and the `echarts.min.js` has been changed to our developing version. It will be planned in release 4.5.0 next month.

**Comment by ITAYC0HEN** [comment]
That is indeed a great band-aid that solved the issue. Thank you!
Of course, it would be great to have a proper solution but I trust you would fix it soon enough.

Thank you very much, again!

**Comment by xiyuvi** [comment]
> @ITAYC0HEN您好，抱歉回复晚了。
> 
> 我添加了一个布局选项：`'friction'`。它将减慢节点的移动。所以我们在更新dataZoom上的选项时可以尝试设置一个较小的值。喜欢关注
> 
> ![图像](https://user-images.githubusercontent.com/841551/65154158-9352c680-da5d-11e9-90c2-0976f4da99f5.png)
> 
> 取值范围为 0 到 1。
> 
> 我在你的项目中尝试过，效果很好。[站点模拟.zip](https://github.com/apache/incubator-echarts/files/3626698/site-mock.zip)
> 
> 但此功能仍处于实验阶段，`echarts.min.js`已更改为我们的开发版本。计划在下个月发布 4.5.0。如果您在使用此开发版本时遇到任何问题，请告诉我们。

感谢，这是一个很有用的属性，解决了我移动大量数据时鬼畜移动的问题
