### ISSUE TITLE
股票K线图不是只有涨和跌还有十字星 开盘价和收盘价一样 希望可以设置颜色

### ISSUE THREAD

**Issue by hengkx** [apache/echarts#11042]
### What problem does this feature solve?
展示数据更加准确
![image](https://user-images.githubusercontent.com/8358236/63225894-379be000-c208-11e9-93bf-aefff9794724.png)

### What does the proposed API look like?
series-candlestick.itemStyle.color1：十字星 填充色
series-candlestick.itemStyle.borderColor1：十字星 边框色

**Comment by pissang** [comment]
可以具体描述下你的需求么，最好有参考示例

**Comment by hengkx** [comment]
@pissang 对的

**Comment by Ovilia** [comment]
现在的逻辑：

- 如果收盘价和开盘价一样，根据上一个交易日判断阴阳线；
- 如果没有上一个交易日，或与上一个交易日持平，则算阳线

这能满足你的需求吗？还是一定要自己制定颜色？

#6527 #5767

**Comment by hengkx** [comment]
最好 可以自定义 颜色 因为他既不是阳线 也不属于 阴线 是一种单独的指标，如果不能单独设置颜色的话，没办法做区分，因为当开盘价和收盘价相差很小(1分钱)的话没办法 判断是不是十字星

**Comment by Ovilia** [comment]
请问有什么产品在十字星的情况下会用第三种颜色的吗？
至于价格相差很小，那也是相差，不是十字星，那就按正常的阴阳颜色显示，有什么问题吗？

**Comment by hengkx** [comment]
有相差 按照正常的显示没有问题。所有金融软件 十字星 都是不同的颜色
![image](https://user-images.githubusercontent.com/8358236/65558557-d6370180-df69-11e9-8278-3654bed5be2e.png) 提问时 也有附图

**Comment by Ovilia** [comment]
颜色的这个可以作为新功能，增加一个类似现在用来表示阴线颜色的 [color0](https://echarts.apache.org/zh/option.html#series-candlestick.itemStyle.color0) 的比如叫 color1？感觉这个命名方式有点粗暴…… 
@hengkx 感兴趣提个 Pull request 吗？我们可以提供一些技术上的帮助~

至于差别很小的情况，有例子证明这样的使用场景吗？在我看来好像不是很合理，因为差一分钱也是差，就应该有阴阳的变化。

**Comment by hengkx** [comment]
十字星是指开盘价和收盘价一样 1分钱的差都没有，对于echarts 不太熟 有时间可以看看，命名 我也觉得 有点奇怪

**Comment by hengkx** [comment]
在金融领域用的比较多 判断走势

**Comment by Ovilia** [comment]
确认一下，这个 issue 的需求是说，当开盘价收盘价一样的时候，可以设置特定的颜色，对吧？

**Comment by hengkx** [comment]
是的

**Comment by Ovilia** [comment]
好的，那么你可以尝试做个 pull request，如果需要帮助请留言~

**Comment by LianJilu** [comment]
我修改了这个需求，添加了color1和borderColor1，默认为黑色，dark模式下为白色可以吗
