### ISSUE TITLE
dataZoom的startValue和endValue可否仅指定一个轴，另一个轴自动识别？

### ISSUE THREAD

**Issue by jerry000lin** [apache/echarts#11062]
### What problem does this feature solve?
```
dataZoom:{
    type:'slider',
    xAxisIndex:[0,1],
    startValue:0,
    endValue:9
}
```

- 在0轴和1轴的category长度不一样的时候，两个轴均显示相同长度（10），短的那个轴显示有误差

- 这在拖动滚动条后，会自动恢复正确的显示

### What does the proposed API look like?
```
startValue:[0,'auto'],
endValue:[9,'auto']
```

**Comment by pissang** [comment]
需要 @100pah 看一下这个问题
