### ISSUE TITLE
Boxplot tooltip marker color

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#11077]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/cdsk5urL/1/](https://jsfiddle.net/cdsk5urL/1/)

### Steps to reproduce
Look at the screenshot or open the jsfiddle and hover on a boxplot. Notice that the tooltip shows as marker color the borderColor.
![BoxplotTooltipIssue](https://user-images.githubusercontent.com/890368/63507585-bd59ad00-c4e0-11e9-8895-a7fe52986310.png)
I believe it should display the color, not the border color, since it is more prominent on the box.

### What is expected?
To see the color as the marker color on the tooltip.

### What is actually happening?
The borderColor is shown as marker color on the tooltip.

**Comment by chrisparma** [comment]
Anyone has a solution on this matter?
