### ISSUE TITLE
About Parallel Axis feature request

### ISSUE THREAD

**Issue by Rickylad** [apache/echarts#11081]
### What problem does this feature solve?
I'm a student and I'm currently using Echarts to develop my assignment. I appreciate those build-in functions. They are really helpful.
Thank you.
While I'm using the Parallel Axis, I found it has a brush feature and axisareaselected API event, but the axis cannot display the two boundary values (edge value) of the selected area. Besides, if I narrow the interval between each axis label, that's still hard to see the values on the axis. So, I'm thinking it would be better to have a feature to display the boundary values or even the gap value of a selected area. That will also help users to elaborate on the selected area, for example, there are how many lines pass through the value between 0.8 to 1.2. 
Plus because parallel axis contains a lot of data and its corresponding lines, it is really hard to find which line is from which data. It would be better to show the name of the line when mouse hovers on it.
![Capture](https://user-images.githubusercontent.com/54165736/63559664-1b949780-c596-11e9-98de-79f91c684867.PNG)

### What does the proposed API look like?
It would be better to add a bit more features in event.axisareaselected or in the brush or even axisPointer.

```js
var boundaryValue[];
chart.on('axisareaselected', function (event) {
       boundaryValue = event.intervals;
});

option = {
     parallel:{
         parallelAxisDefault: {
               boundaryValue: boundaryValue[], // to display the edge values of a selected area.
               // or boundaryValue1: boundaryValue[0],
               // boundaryValue2: boundaryValue[1]
}
}
};
```

**Comment by Ovilia** [comment]
Parallel tooltip feature request is at #9418 .
I don't think it's possible to show the distance between *selected gap* because there is no such feature as selecting a parallel graph. So does the tooltip feature fulfills your need?

**Comment by Rickylad** [comment]
Thank you for the reply. If the tooltip feature worked, it would be helpful. Do you mean the feature is currently available already? or are you still working on it?

**Comment by Ovilia** [comment]
No, it's not available yet.
If this issue is about parallel tooltip only, I think I can put #9418 to a higher priority.

**Comment by Rickylad** [comment]
Yes, please. Parallel tooltip can still be helpful. Thanks.
