### ISSUE TITLE
Gauge - Anticlockwise

### ISSUE THREAD

**Issue by MohammadYounes** [apache/echarts#11080]
### Version
4.2.1

### Steps to reproduce
Create a gauge with the following option

```js
option = {
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}],
            min:0,
            max:100,
            startAngle:0,
            endAngle:180,
            clockwise:false //anitclockwise
        }
     ]
}
```
![anticlockwise](https://user-images.githubusercontent.com/4712046/63531965-5523bf00-c512-11e9-87b9-0cd55533e0f7.gif)

However, setting `clockwise` to `true` breaks the axis line.

```js
option = {
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}],
            min:0,
            max:100,
            startAngle:0,
            endAngle:180,
            clockwise:true
        }
     ]
}
```
![anti-anticlockwise](https://user-images.githubusercontent.com/4712046/63532553-9a94bc00-c513-11e9-8a26-7cda5de6cd9f.gif)

### What is expected?
The gauge to be created **anticlockwise** along with the pointer animation.

### What is actually happening?
Both the gauge and pointer animation are **clockwise**.

---
The only way I could make it anticlockwise was by swapping `min`/`max` and `startAngle`/`endAngle`. But unfortunately, the pointer animation remained clockwise.

```js
option = {
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}],
            min:100,
            max:0,
            startAngle:180,
            endAngle:0,
            clockwise:true
        }
    ]
}
```
![clockwise](https://user-images.githubusercontent.com/4712046/63532154-b186de80-c512-11e9-9463-deeb8431fb9f.gif)

**Comment by yufeng04** [comment]
`clockwise` represents the growth direction of **scale values** on the gauge

**Comment by Ovilia** [comment]
This doesn't seem to be a bug. I think you should use the following code when setting `clockwise` to be `true`:
```
option = {
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}],
            min:0,
            max:100,
            startAngle:180,
            endAngle:0,
            clockwise:true
        }
     ]
}
```

**Comment by MohammadYounes** [comment]
@Ovilia I need the scale to be anticlockwise.


Your suggested option gives this:

![image](https://user-images.githubusercontent.com/4712046/63919111-c4377100-ca46-11e9-8fbd-0b9d859692a7.png)


What I need is this:

![image](https://user-images.githubusercontent.com/4712046/63919146-d87b6e00-ca46-11e9-80e8-ea39fd7877f0.png)

**Comment by Ovilia** [comment]
I think it's a bug with
`option = {
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}],
            min:0,
            max:100,
            startAngle:0,
            endAngle:180,
            clockwise:false
        }
     ]
}
`

**Comment by javio2** [comment]
Hi, 
I've have just the same issue. The pointer points the proper value but it maintains the clockwise color. 
![gauge-clock-anticlock](https://user-images.githubusercontent.com/57364160/92131288-19e6ec00-ee06-11ea-890a-efdefbb68e70.gif)
I also toggled min/max and startAngle/endAngle values.

**Comment by Ovilia** [comment]
Seems to be fixed.
