### ISSUE TITLE
toolbox.icon with SVG Path doesn't work for certain paths

### ISSUE THREAD

**Issue by leipert** [apache/echarts#11087]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/yj6x2gh3/13/](https://jsfiddle.net/yj6x2gh3/13/)

### Steps to reproduce
1. Set an icon in the toolbox to `path://M8 15A7 7 0 118 1a7 7 0 010 14zM6 4a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1zm4 0a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1z`
2. The icons stop working

### What is expected?
The icon is rendered properly

### What is actually happening?
The toolbox is not rendered properly.

---
We recently updated our SVG minification library. Now for example the path:

```
M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zM6 4a1 1 0 0 0-1 1v6a1 1 0 0 0 2 0V5a1 1 0 0 0-1-1zm4 0a1 1 0 0 0-1 1v6a1 1 0 0 0 2 0V5a1 1 0 0 0-1-1z
```

will be minified as

```
M8 15A7 7 0 118 1a7 7 0 010 14zM6 4a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1zm4 0a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1z
```

which is not supported by echarts (apparently). I assume it is a bug in zrender.

**Comment by Ovilia** [comment]
Seems to be a bug.

**Comment by Ovilia** [comment]
It seems that neither of them is a valid SVG path. See [SVG demo here](https://jsfiddle.net/e0scr1zL/).

A valid SVG path looks like:
```
M30.9,53.2C16.8,53.2,5.3,41.7,5.3,27.6S16.8,2,30.9,2C45,2,56.4,13.5,56.4,27.6S45,53.2,30.9,53.2z M30.9,3.5C17.6,3.5,6.8,14.4,6.8,27.6c0,13.3,10.8,24.1,24.101,24.1C44.2,51.7,55,40.9,55,27.6C54.9,14.4,44.1,3.5,30.9,3.5z M36.9,35.8c0,0.601-0.4,1-0.9,1h-1.3c-0.5,0-0.9-0.399-0.9-1V19.5c0-0.6,0.4-1,0.9-1H36c0.5,0,0.9,0.4,0.9,1V35.8z M27.8,35.8 c0,0.601-0.4,1-0.9,1h-1.3c-0.5,0-0.9-0.399-0.9-1V19.5c0-0.6,0.4-1,0.9-1H27c0.5,0,0.9,0.4,0.9,1L27.8,35.8L27.8,35.8z
```
which contains `,` dividing `x` and `y` values.

Please check [SVG path data grammar](https://www.w3.org/TR/SVG/paths.html#PathDataBNF).

If this is the case, ECharts is not responsible for handling such invalid input.

**Comment by leipert** [comment]
@Ovilia It does render render properly in this [SVG demo](https://jsfiddle.net/ony74b9h/1/)

Also looking at the spec, it says for example:

```
coordinate_pair_double::=
    coordinate_pair comma_wsp? coordinate_pair

comma_wsp::=(wsp+ ","? wsp*) | ("," wsp*)
wsp ::= (#x9 | #x20 | #xA | #xC | #xD)
```

So we have a a coordinate pair with a `comma_wsp` in between it can either be:
- 1 or whitespace + optional comma + zero or more white spaces, or
- 1 comma + zero or more white spaces.

If I look at the start of the minified path:

```
M8 15A7 7 0 118 1
```

we can actually produce it with the grammar:

`M8 15` is produced by:

```
moveto(
  "M",
  wsp('') // it's an optional whitespace
  coordinate_pair_sequence(
    coordinate_pair(
      coordinate(8),
      comma_wsp(" "),
      coordinate(15)
    )
  )
);
```

`A7 7 0 118 1` is produced by:

```
elliptical_arc(
  "A",
  wsp(""), // it's an optional whitespace
  elliptical_arc_argument_sequence(
    elliptical_arc_argument(
      number(7),
      comma_wsp(" "),
      number(7),
      comma_wsp(" "),
      number(0),
      comma_wsp(" "),
      flag(1),
      comma_wsp(""), // it's an optional comma_wsp
      flag(1),
      comma_wsp(""), // it's an optional comma_wsp
      coordinate_pair(
        coordinate(8),
        comma_wsp(" "),
        coordinate(1)
      )
    )
  )
);

```

**Comment by Ovilia** [comment]
@leipert Just to be clear, how do you get this SVG Path? I guess it may be some minifying tool?

**Comment by leipert** [comment]
Yes, by using https://github.com/svg/svgo

**Comment by Ovilia** [comment]
Thanks for the information. I will check it out.

**Comment by Ovilia** [comment]
@leipert I checked the ECharts code and it seems that ECharts computes the path commands and draw with these commands. So there may be a bug with this path compiling logic.
Could you please provide the SVG path before minifying with both working and not-working path?

```js
const workingIcon = 'path://M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zM6 4a1 1 0 0 0-1 1v6a1 1 0 0 0 2 0V5a1 1 0 0 0-1-1zm4 0a1 1 0 0 0-1 1v6a1 1 0 0 0 2 0V5a1 1 0 0 0-1-1z';
const nonWorkingIcon = 'path://M8 15A7 7 0 118 1a7 7 0 010 14zM6 4a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1zm4 0a1 1 0 00-1 1v6a1 1 0 002 0V5a1 1 0 00-1-1z';
```
