### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by eniaclyl** [apache/echarts#11109]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xi99crMLPI&v=1](https://gallery.echartsjs.com/editor.html?c=xi99crMLPI&v=1)

### Steps to reproduce
1、用工具栏创建一个标注
2、放大
3、点工具栏还原按钮
4、控制台输出错误信息，图像还原失败

### What is expected?
myChart.on('restore', function (params) {
这里如何实现才能正确还原
});

### What is actually happening?
控制台输出错误信息，图像还原失败

**Comment by eniaclyl** [comment]
@Ovilia 大神，来帮我看看这个问题咋处理 求代码，多谢

**Comment by yufeng04** [comment]
You may need to check your own code.
```
var opt = myChart.getOption();
......
opt.graphic[0].elements.push(newDragCircleEnd);
//设置到echarts
myChart.setOption(opt);
```
At the same time，this is not recommended by echarts. [echartsInstance.getOption](https://www.echartsjs.com/api.html#echartsInstance.getOption)

**Comment by eniaclyl** [comment]
@yufeng04 请问推荐的这个模式

**Comment by eniaclyl** [comment]
@yufeng04 请问推荐的这个模式一定要提供id吗？echarts内部是如何知道我要修改哪个项的，什么原理？myChart.setOption({
    visualMap: {
        inRange: {
            color: ...
    }}
}

**Comment by eniaclyl** [comment]
@yufeng04  另一个问题，我使用下面的方法无法删除图表上的数据，当我再次缩放一次图表，要删除的项才消失，如何立刻更新
var opt = myChart.getOption();
opt.graphic[0].elements.splice(1, 1);
myChart.setOption({
            graphic: [{
                elements: opt.graphic[0].elements
            }]
        });
