### ISSUE TITLE
toolBox 的 iconStyle 对于使用 svg path 的 icon 无法正确设置背景色

### ISSUE THREAD

**Issue by FesonX** [apache/echarts#11117]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xpahwTCD5R&v=1](https://gallery.echartsjs.com/editor.html?c=xpahwTCD5R&v=1)

### Steps to reproduce
https://gallery.echartsjs.com/editor.html?c=xpahwTCD5R&v=1
如链接中代码所示，iconStyle 的 color 不能使图标背景色发生改变，但是shadowColor可以正常使用。在保持使用 svg path 的情况下，如何改变图标背景色？

### What is expected?
使用 svg path 的图标背景色可以直接通过 iconStyle 修改

### What is actually happening?
使用 svg path 的图标背景色无法通过 iconStyle 修改

**Comment by FesonX** [comment]
补充说明，icon 在 emphasis 下颜色仍能按照默认改变，非 emphasis 下却没变化，是 bug 吗

**Comment by yufeng04** [comment]
This seems to be a bug.

**Comment by plainheart** [comment]
Maybe this is not a bug, you can use `borderColor` which means the `stroke` color here instead of `color` which means the `fill` color.
