### ISSUE TITLE
（官方实例上可复现bug）3D柱状图当前面有部分NaN值时，会导致数组前后位置对称的有数据的部分也显示不出来

### ISSUE THREAD

**Issue by ZhangEvan20190527** [apache/echarts#11114]
### Version
4.2.1

### Steps to reproduce
echarts官网上3D柱状图的第一个实例：
把data如下处理：
for(let i=1; i<400; i  ){
        data[i][1]=NaN;
    }
即把前400个z轴数据变为NaN值，结果发现从数组后往前数的400个数据（也是原本有数据不为NaN的地方）也显示不出来了。

### What is expected?
前400个数据显示为空。其余显示正常

### What is actually happening?
前400个数据显示为空。后400个有数据的点也显示不出来了

**Comment by yufeng04** [comment]
The similar issue #11101
