### ISSUE TITLE
Trying to implement a Volume Profile chart (combining an horizontal bar chart with a candlestick)

### ISSUE THREAD

**Issue by lvca** [apache/echarts#11147]
### Version
4.2.1

### Steps to reproduce
I tried in many ways to combine a horizontal bar chart with a candlestick without success. The best came out by using different grid areas that overlap, but during the zoom, the bars change the size and become not visible or very big.

I've included the 4th grid area in the zoom with the candlestick (area 0):
```
          grid: [
              {
                  top: '0',
                  left: '0%',
                  right: '3%',
                  height: '50%'
              },
              ... // OTHER 3 AREAS
              {
                  top: '0',
                  left: '0%',
                  right: '70%',
                  height: '50%'
              },
          ],
...
 dataZoom: [
              {
                  type: 'inside',
                  xAxisIndex: [0, 1, 2, 3, 4],
                  start: 98,
                  end: 100
              }
```

Since it's a horizontal bar chart, I need to flip values with categories from the candlestick:

```
          yAxis: [
              {
                  scale: true,
                  splitArea: {
                      show: true
                  }
              },
              ... // OTHER AREAS
              {
                  type: 'category',
                  scale: true,
                  gridIndex: 4,
                  splitNumber: 2,
                  axisLabel: {show: false},
                  axisLine: {show: false},
                  axisTick: {show: false},
                  splitLine: {show: false}
              }
...
          xAxis: [
              {
                  type: 'category',
                  data: chartData.categoryData,
                  scale: true,
                  boundaryGap : false,
                  axisLine: {onZero: false},
                  splitLine: {show: false},
                  axisLabel: {show: false},
                  splitNumber: 20,
                  min: 'dataMin',
                  max: 'dataMax',
                  axisPointer: {
                      z: 100
                  }
              },
              ... // OTHER AREAS
              {
                  type: 'value',
                  gridIndex: 4,
                  data: chartData.volumeProfileTiersPrices,
                  scale: false,
                  boundaryGap : false,
                  axisLine: {onZero: false},
                  axisTick: {show: false},
                  splitLine: {show: true},
                  axisLabel: {show: false}
              }
```

And finally my serie regarding the volume profile (how much volume per price):
```
        {
           name: 'VolumeProfile',
           type: 'bar',
           color: 'red',
           data: volumeProfileTiersVolumes,
           xAxisIndex: 4,
           yAxisIndex: 4,
           barWidth: 5,
           label: { normal: { show: false } },
           lineStyle: {
               normal: {opacity: 0.5}
           }
        }
```

### What is expected?
The bar chart scales horizontally only with the candlestick chart, without scaling the bar size.

This is the expected output (taken from Yahoo Finance). If I zoom in and out, the bar size is still the same:

(1) zoomed in
![image](https://user-images.githubusercontent.com/312606/64066831-545eed00-cbe4-11e9-9d87-db062d364069.png)

(2) zoomed out
![image](https://user-images.githubusercontent.com/312606/64066839-7bb5ba00-cbe4-11e9-88f8-a66b6880a124.png)

### What is actually happening?
The horizontal bar chart is zoomed with the candlestick, but the bars have a weird positioning with the zoom and they become invisible.

(1) zoomed in
![image](https://user-images.githubusercontent.com/312606/64066867-dbac6080-cbe4-11e9-838f-5285333df2d0.png)

(2) zoomed out
![image](https://user-images.githubusercontent.com/312606/64066852-b6b7ed80-cbe4-11e9-86c0-05e78b9a8c51.png)

**Comment by pissang** [comment]
I think it's because your dataZoom will zoom all the x axes by setting
```
dataZoom:  {
   xAxis: [0, 1, 2, 3]
}
```

Which includes the x axis horizontal bar chart is using. You can try removing this axis from the array. For example if the index is 3, the `xAxis` value should be `[0,1,2]`

**Comment by lvca** [comment]
@pissang If I exclude the horizontal bar chart (xAxis=4], then when I zoom the candlestick area, it doesn't adjust the rendering with the zoomed values. With the candlestick, for example, I can zoom or even move the chart, then the chart scales to show different ranges of values because it tries to optimize the view for the displayed values.

Without the dataZoom, the horizontal bar chart remains static and doesn't follow the new scale. I tried also on playing with dataZoom and yAxis only for the bar chart, but the result is the same.
