### ISSUE TITLE
Chart is taking 0 width of its container div, when the parent element is initially hidden

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#11155]
### Version
4.2.1

### Reproduction link
[https://codepen.io/dileep_yelleti/pen/LYPzWxm](https://codepen.io/dileep_yelleti/pen/LYPzWxm)

### Steps to reproduce
If there is chart inside an element with initial display as 'none' and then changed to display: 'block' then chart width will be set to 0. But if Initial parent display is 'block' then chart will take 100% of parent.

In codepen sample click on showChart button which changes display property of chart parent from none to block. But chart wont be shown. Chart width was set to 0px. Even if we set chart element width as 100% it is plotting chart with 100px width

### What is expected?
Chart should be plotted correctly irrespective of parent's initial display property. Also chart should be responsive by setting 100% width

### What is actually happening?
Chart width was getting set to 0 if parent element is hidden. Even after changing parent display chart width remains same.

**Comment by Ovilia** [comment]
When resized, you should call `chart.resize()`. Please see the [doc](https://echarts.apache.org/en/api.html#echartsInstance.resize).

**Comment by dileepyelleti** [comment]
> When resized, you should call `chart.resize()`. Please see the [doc](https://echarts.apache.org/en/api.html#echartsInstance.resize).

Here our application is embedded as an iframe in one of tabs. So they are changing display property based on selected tab. We don't have control on when it is getting changed.
Is there any way to handle these kind of scenarios?

**Comment by Ovilia** [comment]
@dileepyelleti This seems to be a general JS problem. See if this helps: https://stackoverflow.com/questions/27846057/iframe-does-not-trigger-resize-event

**Comment by dileepyelleti** [comment]
@Ovilia 
So we can't resize chart if our app is used in an iframe of different domain.

**Comment by Ovilia** [comment]
We are considering to improve the auto-resize of ECharts.
