### ISSUE TITLE
设置datazoom的属性，希望x轴显示2端数据

### ISSUE THREAD

**Issue by liuxingzhijian1320** [apache/echarts#11164]
### What problem does this feature solve?
[https://user-images.githubusercontent.com/22805124/64230471-85f6f180-cf1f-11e9-845f-e338415fbfae.jpg](https://user-images.githubusercontent.com/22805124/64230471-85f6f180-cf1f-11e9-845f-e338415fbfae.jpg)

### What does the proposed API look like?
希望滑块的2端数据显示X轴2端上面

**Comment by pissang** [comment]
Try [showMinLabel](https://echarts.apache.org/en/option.html#xAxis.axisLabel.showMinLabel) and [showMaxLabel](https://echarts.apache.org/en/option.html#xAxis.axisLabel.showMaxLabel)
