### ISSUE TITLE
中国地图实现如何实现鼠标滑过省，省单独的区域regionHeight发生变化？

### ISSUE THREAD

**Issue by luohong123** [apache/echarts#11185]
### What problem does this feature solve?
在中国地图中设置regionHeight，中国地图整体的高度会发生变化，设置China 整体的regionHeight有效果，独立的区域高度不生效，设置鼠标点击区域颜色发生变化是有效的。

例如 China 的 regionHeight =2，如何实现鼠标滑过某个省，例如鼠标滑过北京，北京这个单独的区域 regionHeight = 8 高度会凸起。

### What does the proposed API look like?
设置中国地图某个city 的高度

**Comment by StarkL** [comment]
@pissang 你好，请问题主提到的这个功能现在支持了吗？ API没找到相关配置呀

**Comment by StarkL** [comment]
@luohong123 前端时间经过查询GL配置API，发现Echarts本身已经支持某个data项目凸起，例如官方DEMO：【https://echarts.apache.org/examples/zh/editor.html?c=map3d-wood-city&gl=1】

官方API：
![image](https://user-images.githubusercontent.com/21234407/97651244-7f69f880-1a96-11eb-9dbd-c568a33789c2.png)
