### ISSUE TITLE
visualMap中的itemSymbol属性设置了也没用

### ISSUE THREAD

**Issue by ZhaoyangRao** [apache/echarts#11204]
![1568083558(1)](https://user-images.githubusercontent.com/31274475/64580280-4feebd00-d3b8-11e9-849b-b312e0de4c41.png)
### Version
4.3.0-rc.2

### Steps to reproduce
```js
visualMap: {
type: 'piecewise',
seriesIndex: [0],
itemGap: 2,
left: '30',
bottom: '30',
itemSymbol: 'circle',
pieces: [{
min: 10,
label: '10亿以上'
},
{
min: 5,
max: 10,
label: '5亿 到 10亿'
},
{
min: 2,
max: 5,
label: '2亿 到 5亿'
},
{
min: 1,
max: 2,
label: '1亿 到 2亿'
},
{
max: 1,
label: '一亿以下'
}
],
textStyle: {
color: '#fff'
},
color: ['#e16cab', '#d2a05a', '#53caa3', '#29b7dc', '#6a7ce7']
},
```
这样进行设置的
itemSymbol设置成任何图形都没有变化，永远是这个默认的图形

### What is expected?
我期望能改icon

### What is actually happening?
itemSymbol设置成任何图形都没有变化，永远是这个默认的图形

**Comment by HDNRAY** [comment]
可以用pieces里改symbol，但是这样引起了新的问题，把scatter里的symbol覆盖了····
