### ISSUE TITLE
【需求】图例(legend)需要能控制不触发brushSelected事件

### ISSUE THREAD

**Issue by comvir** [apache/echarts#11219]
### What problem does this feature solve?
图表绑定了brushSelected事件，这个事件会通过图例点击触发。
现在要求brushSelected事件只有框选才会触发，
而图例点击时仅触发自身的互动效果，而不触发brushSelected事件。

### What does the proposed API look like?
legend增加silent属性，默认false。
当silent为true时，不触发brushSelected事件

**Comment by deqingli** [comment]
`legend` click interaction will affect the number of series selected by the brush. so it will trigger the `brushSelected` event. Why do you want to disable it, what problem you have met?

**Comment by comvir** [comment]
我有图表通过brushSelected事件和别的图表产生下钻联动，现在要求下钻仅通过框选触发，legend点击不要触发，legend仅影响图表本体。
如果这个实现比较麻烦，那就采取折中方案，给事件的处理参数加上来源标识，标识由什么元素触发的
api示范
```javascript
chart.on('brushSelected', function (params) {
    if(params.eventTarget=="legend"){
          return;
    }else{
         //other something
    }
});
```
