### ISSUE TITLE
Can't set transformable brush option programmatically

### ISSUE THREAD

**Issue by SMHFandA** [apache/echarts#11234]
### Version
4.2.1

### Reproduction link
[https://jsfiddle.net/smhfanda/8wd5pjbk/27/](https://jsfiddle.net/smhfanda/8wd5pjbk/27/)

### Steps to reproduce
1. Open jsfiddle example
2. Try change brush size or move brush. Must works.
3. Uncheck checkbox.
4. Try change brush size or move brush.

### What is expected?
When checkbox is unchecked brush must be 
non transformable.

### What is actually happening?
When checkbox is unchecked brush still transformable.

**Comment by ahmadalibaloch** [comment]
Brush control only works if it is set in the initialization `option` object. At runtime adding `brush` to `options` cause an error.
`Cannot use 'in' operator to search for '_ec_inner' in undefined`
