### ISSUE TITLE
Bars not displayed in JavaFX webview 

### ISSUE THREAD

**Issue by faycelbouamoud** [apache/echarts#11231]
### Version
4.2.1

### Steps to reproduce
- Copy any example of echartjs with bars
- Open it on any jxbrowser
- Bar not showing everything else is fine

### What is expected?
Display bars like in browser

### What is actually happening?
only bars are not displayed

---
We tried to use the same example on :
Google Chrome (works fine)
Mozilla Firefox (works fine)
jxBrowser - chromium instance inside JavaFx - (bars not showing)

**Comment by Das-dasein** [comment]
Echarts its not working properly with canvas. 
Change renderer to 'svg'
`echarts.init(dom, null, {renderer: 'svg'});`
