### ISSUE TITLE
treemap绑定mouseover事件bug

### ISSUE THREAD

**Issue by Gourdbaby** [apache/echarts#11244]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xn-fVoTPq_&v=1](https://gallery.echartsjs.com/editor.html?c=xn-fVoTPq_&v=1)

### Steps to reproduce
鼠标连续多次移入同一个children块

### What is expected?
每次移入都要触发mouseover事件

### What is actually happening?
只有第一次移入触发了mouseover事件

**Comment by Ovilia** [comment]
This seems to be a bug. @huluwa123 Thanks for reporting!

**Comment by dongsuo** [comment]
Is this issue fixed? The example above looks like function normally.
