### ISSUE TITLE
用graphic实现拖拽的散点图,当series开启large:true,且点的数量超过largeThreshold 的设置时候,tooltip消失

### ISSUE THREAD

**Issue by microchang** [apache/echarts#11241]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x05QUdkZIp&v=1](https://gallery.echartsjs.com/editor.html?c=x05QUdkZIp&v=1)

### Steps to reproduce
修改data的数量,在大于largeThreshold(默认2000)时tooltip消失,小于时候出现

### What is expected?
tooltip一直出现

### What is actually happening?
消失

**Comment by Ovilia** [comment]
1. You should not use `triggerOn: 'none'`
2. If you comment the lines after Line 64, the tooltip works. It seems that you've created some graphic elements that block the tooltip because graphic elements are not supposed to trigger tooltip.

**Comment by microchang** [comment]
The graphic element, is the reason why I use `triggerOn: 'none'` for. In fact, this is the [official example](https://www.echartsjs.com/examples/zh/editor.html?c=line-draggable) to implement drag. Graphic element can not trigger tooltip, and the graphic element is really block the scatter,so I can not remove the `triggerOn: 'none'` nor the grraphic emement.

**Comment by Ovilia** [comment]
So what effect do you want? Do you want to get tooltip on scatters or not?

**Comment by microchang** [comment]
a mount of pointer, tooltip on scatters, and can be dragged.

**Comment by microchang** [comment]
hello？

**Comment by Ovilia** [comment]
Remove the `triggerOn: 'none'` and you will have the tooltip.

**Comment by microchang** [comment]
remove the `triggerOn:'none'` can not help. Sometimes tooltop can be see saw  because some soctters is not covered by graphic element.But most soctters is covered by graphic element.

**Comment by pissang** [comment]
Hi @microchang , It's confirmed to be a bug. I guess it's because the custom graphics element covers the scatter series when `large` mode is enabled. We will fix it ASAP.

**Comment by susiwen8** [comment]
I have tried this under 5.0, it was fixed
