### ISSUE TITLE
百度地图（bmap）存在内存泄漏的情况

### ISSUE THREAD

**Issue by bigfacewo** [apache/echarts#11312]
### Version
4.2.1

### Steps to reproduce
在单页面网页中，当我使用bmap显示图表后，切换到路由下的其他页面，该页面无其他内容，发现内存并没有降下去，来回切换，内存一直在涨，而我确实是调用了echarts.dispose()方法销毁了echarts实例的，是不是因为bmap的dispose未实现的原因？我在[代码中](https://github.com/apache/incubator-echarts/blob/fd064123626c97b36cbd6da1b5fc73385c280abd/extension/bmap/BMapCoordSys.js) 第175行，看到 ```// TODO Dispose```,是否是这个原因导致的？

### What is expected?
期望bmap使用的内存会被释放。

### What is actually happening?
实际未释放。

**Comment by haolang** [comment]
https://github.com/apache/echarts/issues/18686

官方示例也有这个问题
