### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined  at x.<anonymous> (radarLayout.js:68)

### ISSUE THREAD

**Issue by contact-ouyang** [apache/echarts#11326]
Hi, I am using vue-echarts to draw a radar chart.  Though the radar charts displays fine,  it always shows error message in the console:
![radarLayout](https://user-images.githubusercontent.com/38242816/65656124-48cedc80-e051-11e9-9651-5be93a5ee62d.png)

Any idea about the cause of the error? Thank you!

**Comment by yufeng04** [comment]
Could you provide a reproducible demo?

**Comment by contact-ouyang** [comment]
Hi, the demo is at https://codesandbox.io/s/vue-template-sebpc, any suggestion to fix the problem is appreciated!

**Comment by yufeng04** [comment]
I find that the error shows when the value of `indictors` is  `[]`.
![image](https://user-images.githubusercontent.com/22974511/65825037-9ee78e00-e2a4-11e9-96e3-d623e53dc156.png)

**Comment by yufeng04** [comment]
I think you can make sure whether the ` indictors`  is an empty array to avoid this error.

**Comment by contact-ouyang** [comment]
Got it. Thanks a lot for your help !

**Comment by benben994** [comment]
Hi, I'm facing this bug too. Apart from waiting for the PR, is there any way to avoid this?
I'm letting user to change the amount of indicators, which user is allowed to choose show zero indicator(empty the radar chart).
But this bug will cause error and not clearing the radar chart so far.

**Comment by yufeng04** [comment]
@benben994 The [PR](https://github.com/apache/incubator-echarts/pull/11358) will be dealt with as soon as possible.
