### ISSUE TITLE
多维柱状图每个 x 轴数据对应的图例可以排序

### ISSUE THREAD

**Issue by YuhangGe** [apache/echarts#11354]
### What problem does this feature solve?
大部分 bi 类型的数据分析产品，都支持这样一类的聚合：x 轴按日期聚合，然后统计每日的高中低告警数量；统计出来的告警数量按倒序排列。诸如下面的数据：

````js
[{
  time: '2019/01/01',
  alarms: [{
    level: 'high',
    count: 100
  }, {
    level: 'middle',
    count: 80
  }]
}, {
  time: '2019/01/02',
   alarms: [{
    level: 'middle',
    count: 100
  }, {
    level: 'high',
    count: 80
  }]
}]
````

对于这个数据，直观的可视化期待如下：

  
    | high |     | middle |                               | middle |     | high |
    |______|     |________|                               |________|     |_____|
         2019/01/01                                          2019/01/02
--------------------------------------------------x轴----------------------------------->

  
  
但目前查阅文档和历史 issues 都没能找到对应的 option 该怎么写。

### What does the proposed API look like?
在 x 轴以及它的每个数据项里，可以指定 `legendOrder`，值支持 "desc", "asc" 或者自定义排序函数，默认为 null，即现在的按 servies 数组的顺序排列。

````js
option = {
  legend: ['high', 'middle'],
  xAxias: {
    legendOrder: 'desc', // 统一指定每个 x 轴数据项里面，不同的 series 的 legend 排序。
    data: [
    { data: '2019/01/01' } 
    { data: '2019/01/02', legendOrder: 'asc' }  // 可以指定单个数据项的图例排序
    ]
  }
}
````

**Comment by Ovilia** [comment]
聚类的功能会在 5.0 的时候实现

**Comment by deqingli** [comment]
@YuhangGe 不好意思，不是很明白你的意思，麻烦给个完整demo或者详细说明下。
