### ISSUE TITLE
xAxis type=time, Is there a way to set time format language?

### ISSUE THREAD

**Issue by jmpmscorp** [apache/echarts#11362]
### Version
4.3.0

### Steps to reproduce
Any xAxis time type example can be use

### What is expected?
An option to set time format language. I want to set it to ES-es (dd-mm-yy)

### What is actually happening?
Time format is mm-dd-yy (US-en).

**Comment by yufeng04** [comment]
Maybe you can use [xAxis.axisLabel.formatter](https://www.echartsjs.com/en/option.html#xAxis.axisLabel.formatter).

**Comment by Ovilia** [comment]
Yes, it currently doesn't support intelligent label formatting like giving a result of each day when passing `{MM-DD-YY}`. This feature needs further discussion.

**Comment by Ovilia** [comment]
Probably we should support `formatter` of time axis to support different time duration. For example, `formatter: [formatterWithinADay, formatterWithinAMonth, ...]`.

**Comment by maliayas** [comment]
What about `formatter: function(value, index, formatSuggestion) {}` ?

`formatSuggestion` would be strings like `hour_minute_second`, `month_day_hour_minute`, `year_month_day`. Consider it whatever the format current auto-label-formatter mechanism produces. User function receives it as a suggestion and either applies or not.

**Comment by mtuzinskiy** [comment]
Hello, any updates on this?

**Comment by pissang** [comment]
5.0 has supported it https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter

**Comment by mtuzinskiy** [comment]
@pissang Thank you! The problem is that the "formatter" function is not "smart": it just takes the value and formats it. While the original default formatter would format depending on the zoom / min-max. So yes, you can change the format at your will, but only for one "level" of time,  which literally breaks the chart for you in most cases.

**Comment by pissang** [comment]
@maliayas Sorry I pasted the wrong doc. The doc for 5.0 is https://echarts.apache.org/next/en/option.html#xAxis.axisLabel.formatter, Which has a description of multi-level formatter.

**Comment by mtuzinskiy** [comment]
Perfect, thanks @pissang !

**Comment by AlexDragus** [comment]
Hello, a formatter used with this syntax `formatter: '{yyyy}-{MM}-{dd}\n{HH}:{mm}'` as specified in the documentation does only show the date correct, the time is always shown as 00:00. Any information on this issue? I think it is related to the change discussed in this topic
