### ISSUE TITLE
lineStyle支持lineJoin

### ISSUE THREAD

**Issue by buhichan** [apache/echarts#11372]
### What problem does this feature solve?
一个朋友需要折线图的折线的lineJoin为miter, 现在在文档里没有找到可以设置lineJoin的Option, 从代码看也是写死的bevel, lineStyle只支持一个白名单里的属性, 不知道[这样](https://github.com/apache/incubator-echarts/blob/master/src/model/mixin/lineStyle.js)的目的是什么?  能不能直接在这个list里加个"lineJoin".

### What does the proposed API look like?
lineStyle能否直接支持任意同名的canvasDrawingContext的样式?

**Comment by Ovilia** [comment]
目的主要是出于防御措施，防止用户在非故意的情况下，意外地设置了一些属性，得到非期望的效果。
至于 `lineJoin` 可以作为一个 new-feature，@100pah 是否只需要在这个地方加上这一属性就行？
