### ISSUE TITLE
treemap chart: click event get wrong dataIndex for treemap?

### ISSUE THREAD

**Issue by songyu8285** [apache/echarts#11377]
### Version
4.4.0-rc.1

### Reproduction link
[https://codepen.io/songyu8285/pen/xxxGjNr](https://codepen.io/songyu8285/pen/xxxGjNr)

### Steps to reproduce
open the codepen link and click treemap item which will alert the dataIndex returned by click event, you will find the dataIndex alerted is always larger than the index of the clicking item

### What is expected?
dataIndex should be equal to the index of item

### What is actually happening?
dataIndex is always one more than index of item

**Comment by Ovilia** [comment]
Seems to be a bug.

**Comment by dongsuo** [comment]
Look like this is a bug related to `TreeNode`, it treats the outer background part as a node too. The example above hide the background node, I create an example that can show this clear: https://codepen.io/dongsuo/pen/NWPbqEQ.
Click the green part which actually shouldn't be a node alert `dataIndex==0`.
I will check this part source code and  try to submit a pr to fix it.

**Comment by DoonPort0422** [comment]
Any news?
(Thanks)

**Comment by Ovilia** [comment]
This doesn't seems to be a bug because it seems the root node is considered to have `dataIndex: 0` as @dongsuo suggests.
