### ISSUE TITLE
svg football pitch to geojson convert

### ISSUE THREAD

**Issue by partitect** [apache/echarts#11389]
### Version
4.4.0-rc.1

### Reproduction link
[https://www.dbface.com/assets/echarts/doc/example/map19.html#-en](https://www.dbface.com/assets/echarts/doc/example/map19.html#-en)

### Steps to reproduce
i want use to echarts.util.mapData.params.params.football but Cannot read property 'params' of undefined

### What is expected?
Footballers heatmap 

### What is actually happening?
Cannot read property 'params' of undefined

**Comment by pissang** [comment]
SVG map support has been removed since v3.0. But it will be back soon!

**Comment by partitect** [comment]
Can you add this future on version 5.0?

**Comment by partitect** [comment]
> SVG map support has been removed since v3.0. But it will be back soon!

Do you plan to add svg map support to the new version?

**Comment by 100pah** [comment]
@partitect Yes. It's on the schedule of v5.1.0.
