### ISSUE TITLE
Aligning multiple Y axis intervals

### ISSUE THREAD

**Issue by HippoAppsXYZ** [apache/echarts#11390]
### Version
4.2.1

### Steps to reproduce
设置左右两侧Y轴，分别给数据，两条Y轴各自有各自的interval标线，有时能对齐，大多数情况下不能对齐。
![A423AA4B-15EF-4267-B047-F9E59C48C992](https://user-images.githubusercontent.com/804881/66713170-af862100-edd9-11e9-930d-a40e6716f274.png)

### What is expected?
左右两侧Y轴的interval可以对齐。

### What is actually happening?
有时能对齐，大多数情况下不能对齐。

**Comment by Ovilia** [comment]
This is a frequently requested feature. We should probably support this in v5.0.

**Comment by fengc7** [comment]
https://blog.csdn.net/qiucheng_198806/article/details/89556773，可以借鉴

**Comment by fengc7** [comment]
https://blog.csdn.net/qiucheng_198806/article/details/89556773    可以借鉴

**Comment by 100pah** [comment]
Related issues: #6973

**Comment by karma2014** [comment]
https://blog.csdn.net/u014744118/article/details/81543012可以先用我的这个思路解决这个问题

**Comment by karma2014** [comment]
https://blog.csdn.net/u014744118/article/details/81543012

//可以先用我的这个思路解决这个问题

**Comment by susiwen8** [comment]
May be [this function](https://github.com/apache/incubator-echarts/blob/next/src/coord/cartesian/Grid.ts#L155) was the key point? @Ovilia @pissang @100pah

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/next/src/coord/cartesian/Grid.ts#L155 May be we should work on this
