### ISSUE TITLE
the axisPointer ,what will keep him alive?

### ISSUE THREAD

**Issue by krislee94** [apache/echarts#11402]
### Version
4.3.0

### Steps to reproduce
1. move the mouse ,Beyond both sides of the X-axis ,the axisPointer will disappear

### What is expected?
axisPointer can always alive

### What is actually happening?
move the mouse ,Beyond both sides of the X-axis ,the axisPointer will disappear

---

- 滑动鼠标或者移动手势，当超过X轴边界，axisPointer会消失。
- 期望当滑动axisPointer超过X轴边界时，固定axisPointer 在X轴边界。
- 代码部分上传地址： https://jsfiddle.net/meufzqwa/

**Comment by Neo1020** [comment]
Hi, I found the solution may be useful for this.
Apply the following on the xAxis.
`axisPointer: {
      handle: {
        show: true,
        color: '#d1554e',
        size: 0,
      },
    },`
    Reproduce code: [https://jsfiddle.net/qhetcp60/](https://jsfiddle.net/qhetcp60/)
    Hope it's helpful.
