### ISSUE TITLE
如何给树图的label添加点击事件

### ISSUE THREAD

**Issue by 334249477** [apache/echarts#11416]
### What problem does this feature solve?
现今tree图只监听点击节点的小圆圈能够产生回调事件，希望能够点击小圆圈旁边的label也产生回调事件，实际结果是点击小圆圈旁边的label无法被监听到点击事件

### What does the proposed API look like?
现今tree图只监听点击节点的小圆圈能够产生回调事件，希望能够点击小圆圈旁边的label也产生回调事件，实际结果是点击小圆圈旁边的label无法被监听到点击事件

**Comment by deqingli** [comment]
what action do you want to trigger when clicking the label

**Comment by noru** [comment]
+1 for this one. Currently tooltip is bound to the symbol only. Should be applied on label as well

**Comment by Tanelmer** [comment]
> what action do you want to trigger when clicking the label

I want to go to a link when clicking the label

and wish label can suport formatter property (html)

**Comment by chenxiaoyu0720** [comment]
昨天卡了一天，突然想到利用svg渲染后，可以获取文本节点增加点击事件，但是没法直接获取数据

**Comment by Lan-W** [comment]
+1 for this one. Currently tooltip is bound to the symbol only. Should be applied on label as well

**Comment by EstellaZhang** [comment]
+1  真的很需要这个功能！！！

**Comment by pissang** [comment]
5.0 已经支持

**Comment by EstellaZhang** [comment]
谢谢，确实可以了！之后【点击事件】中可以增加触发标识吗（ 判断触发节点 还是 label）
