### ISSUE TITLE
关系图怎么通过自定义按钮进行缩放？

### ISSUE THREAD

**Issue by gwtjs** [apache/echarts#11432]
### Version
4.2.1

### Steps to reproduce
配置roam只是开启鼠标缩放，自定义按钮如何实现关系图缩放？

### What is expected?
可通过配置或事件监听的方式进行关系图的缩放

### What is actually happening?
在官方文档、issues、stackoverflow都没有找到相关解决方法

**Comment by deqingli** [comment]
You can dispatch `graphRoam` action. Here is the [code](https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/GraphView.js#L351).  Sorry, we haven't updated this to the doc, we will add it in the future.

**Comment by gwtjs** [comment]
> You can dispatch `graphRoam` action. Here is the [code](https://github.com/apache/incubator-echarts/blob/master/src/chart/graph/GraphView.js#L351). Sorry, we haven't updated this to the doc, we will add it in the future.

谢谢，但是我试了一下并没有生效，没有报错但是也没有缩放，```instance.dispathAction({type: 'grpahRoam',zoom: 2})```

**Comment by hzmming** [comment]
graphRoam确实没生效！！！geoRoam就可以，应该是有bug！！
