### ISSUE TITLE
饼图 引导线label 居左或者居右

### ISSUE THREAD

**Issue by ddduanlian** [apache/echarts#11437]
<img width="1457" alt="屏幕快照 2019-10-19 下午10 43 30" src="https://user-images.githubusercontent.com/33311547/67146891-42372c00-f2c2-11e9-86c4-522f3c9e2db7.png">

饼图是否可以支持以上这种效果，引导线label居左或者居右处理，避免label重叠或者散落在各处

**Comment by deqingli** [comment]
#11497
