### ISSUE TITLE
pieselectchange event handler default data.seriesId value has extra whitespace character

### ISSUE THREAD

**Issue by zachsa** [apache/echarts#11458]
### Version
4.3.0

### Steps to reproduce
Log the data passed to pieselectchange event handler. If I don't specify an 'id' key in the series object then the default id of the series has an extra white space character.

### What is expected?

```js
name: "my series name"
selected: {...}
seriesId: "SeriesName0"
type: "pieselectchanged"
```

### What is actually happening?

```js
name: "my series name"
selected: {...}
seriesId: " SeriesName 0"
type: "pieselectchanged"
```
---
I will add a screenshot to the issue. Although I can clearly see whitespace in the seriesId name, it doesn't seem to be recognized as whitespace by methods such as trim/split/etc. But logging the first character of seriesId (seriesId[0]), it's clearly a whitespace character.

So it looks like an encoding problem, but I don't really know for sure.

**Comment by zachsa** [comment]
![echarts snapshot](https://user-images.githubusercontent.com/6336500/67277630-85162100-f4c7-11e9-9c5b-86d0896cb2e3.PNG)

**Comment by pissang** [comment]
It's a special character `\0` to avoid generated id conflicts with user-given id. We can also verify if the id is auto-generated in the inner code by simply checking this character.

The code is in https://github.com/apache/incubator-echarts/blob/master/src/util/model.js#L290

The downside of this solution is it may cause confusion if developers want to use this auto-generated id. We can have a further discussion about it under this issue @100pah

**Comment by 100pah** [comment]
The original intention of using special characters in auto-generated id is 
(1) avoid conflicts in a simple way, like pissang said.
(2) prevent users from using the auto-generated id. For some inner reasons, the auto-generated id has some that it composed with name and index. But users should not parse it because it might be changed one day.

Of course this approach it is not a complete solution but it is simple. I prefer to suggest still keeping it until some strong reason or downside occur.

**Comment by zachsa** [comment]
Hi @100pah and @pissang - thank you for your replies!

If I could have figured out a way to use the seriesId then I would have, so the `\0` feature is definitely useful (otherwise I wouldn't have known not to use it). Looking at the console output it did look like a bug though.

What about generating a seriesId at runtime? Then a developer would know that they simply can't use seriesId since it would change on every page refresh.
