### ISSUE TITLE
ThemeRiver should add setting for each river

### ISSUE THREAD

**Issue by deqingli** [apache/echarts#11464]
### What problem does this feature solve?
Users can customize the setting of each river

### What does the proposed API look like?
```js
layers: {
 label: {}
 .....
}
```

**Comment by kanle-hotstar** [comment]
The following usage is wrong:

color:{
data:['#FFB6C1','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83', '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3']
},

Try this one:

color: [
'#FFB6C1',
'#2f4554',
'#61a0a8',
'#d48265',
'#91c7ae',
'#749f83',
'#ca8622',
'#bda29a',
'#6e7074',
'#546570',
'#c4ccd3',
],
