### ISSUE TITLE
Saving image does not respect tooltips alwaysShowContent

### ISSUE THREAD

**Issue by survik1** [apache/echarts#11460]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/0rwmLgtu/](https://jsfiddle.net/0rwmLgtu/)

### Steps to reproduce
Combination of tooltip.alwaysShowContent = true and toolbox.feature.saveAsImage.show = true

### What is expected?
As tooltip never hides, its expected that it would be shown in saved image.

### What is actually happening?
Tooltip is being ignored by saveAsImage feature

**Comment by pissang** [comment]
Actually the text on toolbox is not part of tooltip. But I think it's necessary to keep this text display

**Comment by AidMen** [comment]
How could this be tagged "difficulty: easy" in 2019 but then got stale? I find this problem present even today or am I missing something?
