### ISSUE TITLE
热力图（heatmap）如何自定义参数？How to use custom parameters in heatmap?

### ISSUE THREAD

**Issue by realchoi** [apache/echarts#11474]
### What problem does this feature solve?
在热力图中点击某个区域时，希望能传递该区域的自定义参数，比如该区域的区划编号，以进行下一步操作。但是目前好像只能获取到点击的区域的名称（name）。

When clicking on an area in the heatmap, it is hoped that the user-defined parameters of the area, such as the division number of the area, can be passed for the next operation. However, at present, it seems that only the name of the clicked area can be obtained.

### What does the proposed API look like?
``` js
charts.on("click", function (params) {
        console.log(params);
        console.log(params.CUSTOMPARAMETER);    // 获取自定义参数 Gets the custom parameter named CUSTOMPARAMETER
}
```

**Comment by pissang** [comment]
You can try indexing the custom parameters by yourself with the name in params
