### ISSUE TITLE
有polygons3D示例参考下吗

### ISSUE THREAD

**Issue by wushu843639932** [apache/echarts#11471]

**Comment by wushu843639932** [comment]
@Ovilia

**Comment by pissang** [comment]
目前没有 polygons3D 的实现

**Comment by wushu843639932** [comment]
polygons3D可以效果可以实现吗？我填写配置了选项后为啥echarts-gl.js报错；polygons3D需要配合地图吗？
代码片段
var option3D = {
                series:[{
                    type: 'polygons3D', // 绘制多边形3d
                    multiPolygon:true,
                    itemStyle:{
                        color:'#900'
                    },
                    emphasis:{
                        itemStyle:{
                            color:'#000'
                        }
                    },
                    data: [{
                        coords: [[0, 0], [100, 0], [100, 100], [0, 100]],
                        height: 3
                    }, {
                        coords: [[50, 0], [100, 100], [0, 100]],
                        height: 3
                    }]
                }]
            }
            myChart.setOption(option3D);

**Comment by wushu843639932** [comment]
@pissang

**Comment by pissang** [comment]
奥，这个是需要配合地图才行

**Comment by pissang** [comment]
@wushu843639932 你可以试试创建一个 geo3D 的组件，然后 coordinateSystem 设置成这个 geo3D

geo3D 里的 GeoJSON 可以是一个非常简单的矩形，用来表示你这个数据的范围

**Comment by wushu843639932** [comment]
我不是在地图上绘制数据，而是根据坐标去绘制多边形的立体图形，立体图形可以长方体，梯形立方体，扇形立方体等，我试了你的方法，geo3D中始终要给个地图
@pissang

**Comment by wushu843639932** [comment]
![效果图](https://user-images.githubusercontent.com/40857553/67547890-da099f80-f732-11e9-9461-0786b25056a6.png)
这是平面图，里面的每个图形都是根据坐标绘制出来的，现在想要转化成3d的，每个立方体的底面积还是不同的，没有思路
@pissang

**Comment by wushu843639932** [comment]
3d柱状图的每个柱状图的底部面积可以是不同吗？可以根据点的坐标来设置底部的位置和面积吗？还是底部的大小是固定的，所有的柱状的底图都是一样的不能修改
@pissang

**Comment by kingiluob** [comment]
> 我不是在地图上绘制数据，而是根据坐标去绘制多边形的立体图形，立体图形可以长方体，梯形立方体，扇形立方体等，我试了你的方法，geo3D中始终要给个地图
> @pissang

为啥不直接用wengl去做。
