### ISSUE TITLE
graph 使用focusNodeAdjacency，能否显示到跟节点，不只是邻进的。下一级的节点链路全部高亮，上一级节点只高亮有直接关系的链路

### ISSUE THREAD

**Issue by mikchen** [apache/echarts#11470]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by funkytaco** [comment]
https://ecomfe.github.io/?lang=zh-cn

**Comment by ilovepumpkin** [comment]
有同样需求，我看https://github.com/apache/incubator-echarts/issues/9542已经被close了，但感觉这个需求还挺普遍的，希望官方能考虑support
