### ISSUE TITLE
请问echarts1.4.1版本如何实现下钻到山西省里面的城市，现在从全国下钻到省份是吧所有的数据混合的，高版本的话有单独的json，比如shanxi.json，低版本的咋实现呢

### ISSUE THREAD

**Issue by flowerxuegao** [apache/echarts#11482]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by pissang** [comment]
1.4.1 版本有点太老了，你们不升级到高版本的原因是？

**Comment by flowerxuegao** [comment]
因为有一些用户他们用的ie8版本的

**Comment by pissang** [comment]
4.0 也支持 ie8
