### ISSUE TITLE
使用dataset(encode)模式编码数据并且指定主题时，对option.color的响应方式有误

### ISSUE THREAD

**Issue by Ling310** [apache/echarts#11487]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xF_yIKxc8&v=1](https://gallery.echartsjs.com/editor.html?c=xF_yIKxc8&v=1)

### Steps to reproduce
1.在option中使用dataset和encode的模式指定data；
2.option.color.length < series.length
3.切换主题
可以发现，series没有循环读取option.color的颜色，并使用主题色进行补充。对比普通series.data的颜色指定方式，可以确定二者的颜色取值逻辑未统一。

### What is expected?
encode模式下可以按照series.data这种普通模式取option.color中的颜色

### What is actually happening?
没有循环读取option.color

**Comment by Zaynex** [comment]
It appears to have been fixed.
