### ISSUE TITLE
Custom Axis lable background color 

### ISSUE THREAD

**Issue by samavedulark** [apache/echarts#11491]
### Version
4.4.0

### Steps to reproduce
1. Create a bar chart
2. Set options for axis label background color.
3. Background is set for all labels.
4. Specific colors for specific labels not supported.

### What is expected?
Background color for axis label is fixed, need custom color for diffrent labels based on function

### What is actually happening?
One color for all axis labels.

**Comment by pissang** [comment]
Hi, can you describe the parameter and return value you expected for this function?

**Comment by samavedulark** [comment]
Like we have for axisLable color below is the code. Need same for background color too.
axisLabel: {
                      inside: false,
                      textStyle: {
                          color: function (value, index) {
                            console.log(index)
                            if(value === 'A') {
                              return 'green';
                            } else if(value === 'B') {
                              return 'blue';
                            } else if (value === 'C')
                            {
                              return 'black';
                            } else if (value === 'D') {
                              return 'red';
                            }
                            else if (value === '0') {
                              return 'white';
                            } else {
                              return 'black';
                            }
                          }
                        }
                  }

**Comment by Nicolai8** [comment]
for anyone who will also need this. There is a workaround just refer to [_rich_ option](https://echarts.apache.org/en/option.html#title.textStyle.rich):
```
formatter: (value, index)=> `{${index}|${value}}`,
rich: {
  1: {
    backgroundColor: 'red';
  },
  2: {
    backgroundColor: 'black';
  }
}
```
