### ISSUE TITLE
左右滑动线图，加载新数据

### ISSUE THREAD

**Issue by dagundejuzi** [apache/echarts#11492]
### What problem does this feature solve?
根据用户行为来加载数据。

### What does the proposed API look like?
一个横向滑动的线图，按时间从左到右分布，当用户滑到左侧最的时间后，希望触发事件去加载新的数据，让用户能继续往左滑。
现在文档中似乎没有滑到边界的触发事件？或者能实时监听图表位移的回调函数？

**Comment by Ovilia** [comment]
Currently, we do not support this feature.
Do you mind making a pull request about this feature?
