### ISSUE TITLE
树图用setOption更新数据时，发现图有残留BUG

### ISSUE THREAD

**Issue by leaon4** [apache/echarts#11493]
用echarts画二叉树图，在实现AVL树插入的时候发现的BUG
![bug](https://user-images.githubusercontent.com/31395977/67629350-3c87aa80-f8af-11e9-92f1-656253f83be1.png)

// index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tree</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
        }

        .btn-container {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            text-align: center;
        }
    </style>
    <script src="assets/echarts.js"></script>
</head>

<body>
    <div id="mychart" style="height: 100vh"></div>
    <div class="btn-container">
        <button class="btn" onclick="gen.next()">run</button>
        <button class="btn" onclick="refresh()">refresh</button>
    </div>
    <script src="tree.js"></script>
</body>

</html>

// tree.ts
const container = document.getElementById('mychart') as HTMLDivElement;
const myChart = geta('echarts').init(container);
function geta(str: any): any {
    return window![str];
}

const option: any = {
    tooltip: {
        trigger: 'item',
        triggerOn: 'mousemove'
    },
    series: [
        {
            type: 'tree',
            // data: [data],
            data: [],
            left: '2%',
            right: '2%',
            top: '8%',
            bottom: '20%',
            symbol: 'emptyCircle',
            orient: 'vertical',
            expandAndCollapse: true,
            lineStyle: {
                curveness: 0,
            },
            initialTreeDepth: -1,
            // symbolSize:20,
            label: {
                normal: {
                    position: 'top',
                    align: 'middle',
                    fontSize: 19,
                    color: 'black'
                }
            },
            leaves: {
                label: {
                    normal: {
                        position: 'bottom',
                        align: 'middle'
                    }
                }
            },
            animationDurationUpdate: 750
        }
    ]
};

type ChartData = {
    name: number | string;
    children?: ChartData[];
};
type Item = {
    num: number;
};
type TreeNode = {
    item: Item;
    left: TreeNode;
    right: TreeNode;
    height?: number;
} | null;

function itemCompare(item1: Item, item2: Item): number {
    return item2.num - item1.num;
}

class BTree {
    size: number;
    root: TreeNode;
    constructor() {
        this.size = 0;
        this.root = null;
    }
    protected createNode(item: Item): TreeNode {
        return {
            item,
            left: null,
            right: null
        };
    }
    addItem(item: Item): void {
        let newNode = this.createNode(item);
        this.root = this._addItem(this.root, newNode);
        this.size++;
    }
    protected _addItem(node: TreeNode, newNode: TreeNode): TreeNode {
        if (!node) {
            return newNode;
        }
        let dir: number = itemCompare(node.item, newNode!.item);
        if (dir < 0) {
            node.left = this._addItem(node.left, newNode);
        } else if (dir > 0) {
            node.right = this._addItem(node.right, newNode);
        } else {
            console.warn('same item');
            this.size--;
        }
        return node;
    }
    private createChartData(node: TreeNode): ChartData {
        if (!node) {
            return { name: '' };
        }
        let data: ChartData = {
            name: node.item.num,
            children: []
        }
        data.children![0] = this.createChartData(node.left);
        data.children![1] = this.createChartData(node.right);
        if (data.children!.every(item => item.name === '')) {
            data.children = [];
        }
        return data;
    }
    show(): void {
        let data: ChartData = this.createChartData(this.root);
        option.series[0].data = [data];
        myChart.setOption(option);
    }
}

class AVLTree extends BTree {
    constructor() {
        super();
    }
    addItem(item: Item): void {
        let newNode = this.createNode(item);
        newNode!.height = 0;
        this.root = this._addItem(this.root, newNode);
        this.size++;
    }
    protected createNode(item: Item): TreeNode {
        let newNode = super.createNode(item);
        newNode!.height = 0;
        return newNode;
    }
    protected _addItem(node: TreeNode, newNode: TreeNode): TreeNode {
        if (!node) {
            return newNode;
        }
        let dir: number = itemCompare(node.item, newNode!.item);
        if (dir < 0) {
            node.left = this._addItem(node.left, newNode);
            if (this.getNodeHeight(node.left) - this.getNodeHeight(node.right) == 2) {
                if (itemCompare(node.left!.item, newNode!.item) < 0) {
                    console.log('left single rotation');
                    return this.singleRotate(node, -1);
                }
                console.log('left double rotation');
                return this.doubleRotate(node, -1);
            }
        } else if (dir > 0) {
            node.right = this._addItem(node.right, newNode);
            if (this.getNodeHeight(node.left) - this.getNodeHeight(node.right) == -2) {
                if (itemCompare(node.right!.item, newNode!.item) < 0) {
                    console.log('right double rotation')
                    return this.doubleRotate(node, 1);
                }
                console.log('right single rotation');
                return this.singleRotate(node, 1);
            }
        } else {
            console.warn('same item');
            this.size--;
        }
        node.height = Math.max(this.getNodeHeight(node.left), this.getNodeHeight(node.right)) + 1;
        return node;
    }
    private getNodeHeight(node: TreeNode): number {
        if (!node) {
            return -1;
        }
        return node.height as number;
    }
    private singleRotate(parentNode: TreeNode, dir: number): TreeNode {
        let childNode: TreeNode;
        if (dir < 0) {
            childNode = parentNode!.left;
            parentNode!.left = childNode!.right;
            childNode!.right = parentNode;
        } else {
            childNode = parentNode!.right;
            parentNode!.right = childNode!.left;
            childNode!.left = parentNode;
        }
        parentNode!.height = Math.max(this.getNodeHeight(parentNode!.left), this.getNodeHeight(parentNode!.right)) + 1;
        childNode!.height = Math.max(this.getNodeHeight(childNode!.left), this.getNodeHeight(childNode!.right)) + 1;
        return childNode;
    }
    private doubleRotate(parentNode: TreeNode, dir: number): TreeNode {
        if (dir < 0) {
            parentNode!.left = this.singleRotate(parentNode!.left, 1);
        } else {
            parentNode!.right = this.singleRotate(parentNode!.right, -1);
        }
        return this.singleRotate(parentNode, dir);
    }
}

// 以下为驱动代码
function addItem(num: number) {
    tree.addItem({ num });
    tree.show();
}
const tree = new AVLTree();
function* main() {
    let testcase = [3, 2, 1, 4, 5, 6, 7, 16, 15, 14, 13, 12, 11, 10, 8, 9];
    // let testcase = [1, 10, 2, 9, 3, 8, 4, 7, 5, 6];
    for (let num of testcase) {
        addItem(num);
        yield;
    }
}
let gen = main();

function refresh() {
    myChart.clear();
    myChart.setOption(option);
}

**Comment by leaon4** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tree</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
        }

        .btn-container {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            text-align: center;
        }
    </style>
    <script src="assets/echarts.js"></script>
</head>

<body>
    <div id="mychart" style="height: 100vh"></div>
    <div class="btn-container">
        <button class="btn" onclick="gen.next()">run</button>
        <button class="btn" onclick="refresh()">refresh</button>
    </div>
    <script src="tree.js"></script>
</body>

</html>`

**Comment by leaon4** [comment]
> <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tree</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
        }

        .btn-container {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            text-align: center;
        }
    </style>
    <script src="assets/echarts.js"></script>
</head>

<body>
    <div id="mychart" style="height: 100vh"></div>
    <div class="btn-container">
        <button class="btn" onclick="gen.next()">run</button>
        <button class="btn" onclick="refresh()">refresh</button>
    </div>
    <script src="tree.js"></script>
</body>

**Comment by leaon4** [comment]
html代码帖不上去，只好传截图了
![屏幕截图(1)](https://user-images.githubusercontent.com/31395977/67629473-09deb180-f8b1-11e9-95f4-126bb823b945.png)

**Comment by leaon4** [comment]
js版的代码

> "use strict";
const container = document.getElementById('mychart');
const myChart = geta('echarts').init(container);
function geta(str) {
    return window[str];
}
const option = {
    tooltip: {
        trigger: 'item',
        triggerOn: 'mousemove'
    },
    series: [
        {
            type: 'tree',
            // data: [data],
            data: [],
            left: '2%',
            right: '2%',
            top: '8%',
            bottom: '20%',
            symbol: 'emptyCircle',
            orient: 'vertical',
            expandAndCollapse: true,
            lineStyle: {
                curveness: 0,
            },
            initialTreeDepth: -1,
            // symbolSize:20,
            label: {
                normal: {
                    position: 'top',
                    align: 'middle',
                    fontSize: 19,
                    color: 'black'
                }
            },
            leaves: {
                label: {
                    normal: {
                        position: 'bottom',
                        align: 'middle'
                    }
                }
            },
            animationDurationUpdate: 750
        }
    ]
};
function itemCompare(item1, item2) {
    return item2.num - item1.num;
}
class BTree {
    constructor() {
        this.size = 0;
        this.root = null;
    }
    createNode(item) {
        return {
            item,
            left: null,
            right: null
        };
    }
    addItem(item) {
        let newNode = this.createNode(item);
        this.root = this._addItem(this.root, newNode);
        this.size++;
    }
    _addItem(node, newNode) {
        if (!node) {
            return newNode;
        }
        let dir = itemCompare(node.item, newNode.item);
        if (dir < 0) {
            node.left = this._addItem(node.left, newNode);
        }
        else if (dir > 0) {
            node.right = this._addItem(node.right, newNode);
        }
        else {
            console.warn('same item');
            this.size--;
        }
        return node;
    }
    createChartData(node) {
        if (!node) {
            return { name: '' };
        }
        let data = {
            name: node.item.num,
            children: []
        };
        data.children[0] = this.createChartData(node.left);
        data.children[1] = this.createChartData(node.right);
        if (data.children.every(item => item.name === '')) {
            data.children = [];
        }
        return data;
    }
    show() {
        let data = this.createChartData(this.root);
        option.series[0].data = [data];
        myChart.setOption(option);
    }
}
class AVLTree extends BTree {
    constructor() {
        super();
    }
    addItem(item) {
        let newNode = this.createNode(item);
        newNode.height = 0;
        this.root = this._addItem(this.root, newNode);
        this.size++;
    }
    createNode(item) {
        let newNode = super.createNode(item);
        newNode.height = 0;
        return newNode;
    }
    _addItem(node, newNode) {
        if (!node) {
            return newNode;
        }
        let dir = itemCompare(node.item, newNode.item);
        if (dir < 0) {
            node.left = this._addItem(node.left, newNode);
            if (this.getNodeHeight(node.left) - this.getNodeHeight(node.right) == 2) {
                if (itemCompare(node.left.item, newNode.item) < 0) {
                    console.log('left single rotation');
                    return this.singleRotate(node, -1);
                }
                console.log('left double rotation');
                return this.doubleRotate(node, -1);
            }
        }
        else if (dir > 0) {
            node.right = this._addItem(node.right, newNode);
            if (this.getNodeHeight(node.left) - this.getNodeHeight(node.right) == -2) {
                if (itemCompare(node.right.item, newNode.item) < 0) {
                    console.log('right double rotation');
                    return this.doubleRotate(node, 1);
                }
                console.log('right single rotation');
                return this.singleRotate(node, 1);
            }
        }
        else {
            console.warn('same item');
            this.size--;
        }
        node.height = Math.max(this.getNodeHeight(node.left), this.getNodeHeight(node.right)) + 1;
        return node;
    }
    getNodeHeight(node) {
        if (!node) {
            return -1;
        }
        return node.height;
    }
    singleRotate(parentNode, dir) {
        let childNode;
        if (dir < 0) {
            childNode = parentNode.left;
            parentNode.left = childNode.right;
            childNode.right = parentNode;
        }
        else {
            childNode = parentNode.right;
            parentNode.right = childNode.left;
            childNode.left = parentNode;
        }
        parentNode.height = Math.max(this.getNodeHeight(parentNode.left), this.getNodeHeight(parentNode.right)) + 1;
        childNode.height = Math.max(this.getNodeHeight(childNode.left), this.getNodeHeight(childNode.right)) + 1;
        return childNode;
    }
    doubleRotate(parentNode, dir) {
        if (dir < 0) {
            parentNode.left = this.singleRotate(parentNode.left, 1);
        }
        else {
            parentNode.right = this.singleRotate(parentNode.right, -1);
        }
        return this.singleRotate(parentNode, dir);
    }
}
// 以下为驱动代码
function addItem(num) {
    tree.addItem({ num });
    tree.show();
}
const tree = new AVLTree();
function* main() {
    let testcase = [3, 2, 1, 4, 5, 6, 7, 16, 15, 14, 13, 12, 11, 10, 8, 9];
    // let testcase = [1, 10, 2, 9, 3, 8, 4, 7, 5, 6];
    for (let num of testcase) {
        addItem(num);
        yield;
    }
}
let gen = main();
function refresh() {
    myChart.clear();
    myChart.setOption(option);
}
//# sourceMappingURL=tree.js.map

**Comment by leaon4** [comment]
貌似只要改变树的根节点，再setOption就会触发

**Comment by pissang** [comment]
I think https://github.com/apache/incubator-echarts/pull/11447 has fixed this issue

**Comment by leaon4** [comment]
用刚下的master分支版本试了，残留的现象还是存在的，与expandAndCollapse无关
[
    { "name": "3", "children": [] },
    { "name": "3", "children": [{ "name": "2", "children": [] }, { "name": "" }] },
    { "name": "2", "children": [{ "name": "1", "children": [] }, { "name": "3", "children": [] }] },
    { "name": "2", "children": [{ "name": "1", "children": [] }, { "name": "3", "children": [{ "name": "" }, { "name": "4", "children": [] }] }] },
]
用这四条数据可以复现，同样可以在官网示例上复现
![屏幕截图(2)](https://user-images.githubusercontent.com/31395977/67688950-984c5380-f9d5-11e9-8fa8-52b1fd05c748.png)

**Comment by deqingli** [comment]
您好，方便直接提供一个 demo 么，你这个数据不是层级结构的，我这边没办法复现。

**Comment by leaon4** [comment]
您好，那我详细讲一个方法吧。
1.进入echarts官网，选择树图的最后一个实例
2.在示例代码中插入window.myChart=myChart以便控制台可以直接引用
3.将以下代码复制进控制台中
var testData = [
    { "name": "3", "children": [] },
    { "name": "3", "children": [{ "name": "2", "children": [] }, { "name": "" }] },
    { "name": "2", "children": [{ "name": "1", "children": [] }, { "name": "3", "children": [] }] },
    { "name": "2", "children": [{ "name": "1", "children": [] }, { "name": "3", "children": [{ "name": "" }, { "name": "4", "children": [] }] }] },
];
testData.forEach((data, index) => {
    setTimeout(() => {
        option.series[0].data = [data];
        myChart.setOption(option);
    }, (index + 1) * 1000);
});

**Comment by leaon4** [comment]
![image](https://user-images.githubusercontent.com/31395977/73136178-cd744a80-4085-11ea-9cb9-d6ce96fd420d.png)

**Comment by leaon4** [comment]
![QQ截图20200126215304](https://user-images.githubusercontent.com/31395977/73136230-45db0b80-4086-11ea-90e6-a3461a34579b.png)

**Comment by leaon4** [comment]
![QQ截图20200126215304](https://user-images.githubusercontent.com/31395977/73272473-64273f80-421d-11ea-9de6-95ec870d155e.png)

**Comment by emryx26** [comment]
我也出现残留问题，提供两组数据，先render第一组，再render第二组的时候会出现线条残留。

1.
```json
{"host":"8","name":"8","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"2","name":"2","value":2,"itemStyle":{"borderColor":"grey"}},{"host":"3","name":"3","value":2,"itemStyle":{"borderColor":"grey"}},{"host":"5","name":"5","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"nas","name":"db_backup","value":1,"itemStyle":{"borderColor":"#eb4034"}}]},{"host":"6","name":"6","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"nas","name":"job3","value":1,"itemStyle":{"borderColor":"#eb4034"},"children":[{"host":"nas","name":"job2","value":0,"itemStyle":{"borderColor":"#49eb34"},"children":[{"host":"nas","name":"job1","value":0,"itemStyle":{"borderColor":"#49eb34"}},{"host":"nas","name":"job1","value":0,"itemStyle":{"borderColor":"#49eb34"}}]},{"host":"nas","name":"job2","value":0,"itemStyle":{"borderColor":"#49eb34"}}]},{"host":"nas","name":"job3","value":1,"itemStyle":{"borderColor":"#eb4034"}}]},{"host":"7","name":"7","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"6","name":"6","value":2,"itemStyle":{"borderColor":"grey"}}]}]}
```

2.
```json
{"host":"7","name":"7","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"6","name":"6","value":2,"itemStyle":{"borderColor":"grey"},"children":[{"host":"nas","name":"job3","value":1,"itemStyle":{"borderColor":"#eb4034"},"children":[{"host":"nas","name":"job2","value":0,"itemStyle":{"borderColor":"#49eb34"},"children":[{"host":"nas","name":"job1","value":0,"itemStyle":{"borderColor":"#49eb34"}}]}]}]}]}
```
