### ISSUE TITLE
legend was setted an array, and setted selected, then the legend need doubleclick to toggle the chart change

### ISSUE THREAD

**Issue by wilsonyiyi** [apache/echarts#11505]
### Version
4.1.0-release

### Reproduction link
[https://jsfiddle.net/a4vwgbe8/](https://jsfiddle.net/a4vwgbe8/)

### Steps to reproduce
when click legend "bar1",  u need doubleclick

### What is expected?
single click to toggle chart

### What is actually happening?
doubleclick legend to change chart

**Comment by yufeng04** [comment]
It is a bug! The reason may be the initialization of `legend[i].selected`.
