### ISSUE TITLE
Label switch normal to emphasis and dont return in SVG

### ISSUE THREAD

**Issue by wilnerjs** [apache/echarts#11512]
### Version
4.4.0

### Reproduction link
[http://jsfiddle.net/wilnerjs/53fnpu1k/](http://jsfiddle.net/wilnerjs/53fnpu1k/)

### Steps to reproduce
1 - Create a chart with renderer:SVG
2 - use label:{normal{ }, emphasis{ }}
3 -  hover the mouse on the labels

### What is expected?
font size increase on mouse hover, and decrease after mouse left

### What is actually happening?
the font size will increase, and not decrease after mouse left

**Comment by Ovilia** [comment]
I'll have a check if this has been fixed with ecomfe/zrender#519.
