### ISSUE TITLE
饼状图的labelLine的起始点都是位于饼状的中间位置，能够朝一个方向嘛？【起始点可以是一个端头吗】

### ISSUE THREAD

**Issue by JasonSubMara** [apache/echarts#11519]
### What problem does this feature solve?
固定labelLine的起始方向，用以解决多个饼图的label的内容固定在一侧

### What does the proposed API look like?
labelLine  -- position : 

['left','center','right']

**Comment by JasonSubMara** [comment]
![image](https://user-images.githubusercontent.com/30927318/67939194-ff534d80-fc0b-11e9-88a3-4d2956de693d.png)

实现效果如图所示，社区中没有找到相似案例，望官方大大早点看下。急

**Comment by Ovilia** [comment]
暂时不支持这样的方式，可以用自定义系列做。
但看起来这样的设计有点乱，不确定是好的设计。

**Comment by JasonSubMara** [comment]
> 暂时不支持这样的方式，可以用自定义系列做。
> 但看起来这样的设计有点乱，不确定是好的设计。

额，自定义系列是如何实现的？？

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97

**Comment by pissang** [comment]
This design is similar to the issue we meet in themeRiver. This can be scheduled to label enhancement topic. https://github.com/apache/incubator-echarts/issues/11497

**Comment by AttackXiaoJinJin** [comment]
现在社区有个类似的：https://www.makeapie.com/editor.html?c=xF_AXrV7sK
