### ISSUE TITLE
markLine的data中坐标轴数值太小时的bug

### ISSUE THREAD

**Issue by POILover** [apache/echarts#11517]
```js
markLine: {
                data: [
                    {yAxis:0.001}
                ]
            }
```
如上配置，此时markLine只会显示在0处，而不是0.001，测试后发现，只有在数值大于0.01时才会正常显示，介于0.005到0.01显示为0.01，低于0.005全部显示为0

**Comment by pissang** [comment]
Hi, can you provide full option for us to reproduce?

**Comment by POILover** [comment]
```js
option = {
    xAxis:  {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value',
    },
    series: [
        {
            type:'line',
            data:[.01, -.02,.02, .05, .03, .002, 0],
            markLine: {
                data: [
                      { yAxis:0.005 }
                ]
            }
        }
    ]
};

```
When testing this option, we can see the mark-line is shown on the 0.01 of yAxis, not on 0.005, which should have been there.
With changing the param of markLine.data.yAxis, like 0.0005, 0.001, 0.006, 0.01, 0.02, we can find echarts just cut the param with rounding at third decimal place. 
Since the yAxis is able to show such precision, why mark-line doesn't deserve this ability?

**Comment by POILover** [comment]
option = {     xAxis:  {         type: 'category',         boundaryGap: false,         data: ['周一','周二','周三','周四','周五','周六','周日']     },     yAxis: {         type: 'value',     },     series: [         {             type:'line',             data:[.01, -.02,.02, .05, .03, .002, 0],             markLine: {                 data: [                       { yAxis:0.005 }                 ]             }         }     ] }; 

When testing this option, we can see the mark-line is shown on the 0.01 of yAxis, not on 0.005, which should have been there.
With changing the param of markLine.data.yAxis, like 0.0005, 0.001, 0.006, 0.01, 0.02, we can find echarts just cut the param with rounding at third decimal place.
Since the yAxis is able to show such precision, why mark-line doesn't deserve this ability?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午3:43
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "312822458"<312822458@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] markLine的data中坐标轴数值太小时的bug (#11517)




Hi, can you provide full option for us to reproduce?

**Comment by 7inspire** [comment]
it should not be a bug. The MarkLine data precision is 2 defaultly.
You can use overwrite the precision:
`
option = {
    xAxis:  {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value',
    },
    series: [
        {
            type:'line',
            data:[.01, -.02,.02, .05, .03, .002, 0],
            markLine: {
                data: [
                      { yAxis:0.005 }
                ],
                precision: 3
            }
        }
    ]
};
`

**Comment by POILover** [comment]
@7inspire WOW! Indeed! I will read the api carefully next time. Thx！

**Comment by pissang** [comment]
Thanks,  @7inspire ! Glad to see it being solved. I think we can calculate the precision automatically by default.

**Comment by ChrisShen93** [comment]
> Thanks, @7inspire ! Glad to see it being solved. I think we can calculate the precision automatically by default.

Is there any progress？
