### ISSUE TITLE
The data in the Air quality-baidu Map sample on the official website shows an error

### ISSUE THREAD

**Issue by bcqyh** [apache/echarts#11528]
### Version
4.4.0

### Steps to reproduce
The purple dot representing air quality in the example, when the mouse is focused, displays the PM2.5 value as the latitude value of the current city

### What is expected?
display the PM2.5 value

### What is actually happening?
displayed the latitude value

---
The code is on the echarts server

**Comment by Ovilia** [comment]
Cannot reproduce. Do you mean https://echarts.apache.org/examples/en/editor.html?c=effectScatter-bmap ?

**Comment by bcqyh** [comment]
Yes.https://echarts.apache.org/examples/en/editor.html?c=effectScatter-bmapPurple dots should show pm2.5 value，but latitude value发自我的iPhone------------------ Original ------------------From: Ovilia  <notifications@github.com>Date: Fri,Nov 1,2019 11:01 AMTo: apache/incubator-echarts <incubator-echarts@noreply.github.com>Cc: bcqyh <bcqyh710@126.com>, Author <author@noreply.github.com>Subject: Re: [apache/incubator-echarts] The data in the Air quality-baidu Mapsample on the official website shows an error (#11528)Cannot reproduce. Do you mean https://echarts.apache.org/examples/en/editor.html?c=effectScatter-bmap ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-echarts/issues/11528?email_source=notifications\u0026email_token=AKX2XP3HZ3J4RUBEECQSX2LQROLZ5A5CNFSM4JGZ6EG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZ3HPA#issuecomment-548647868",
"url": "https://github.com/apache/incubator-echarts/issues/11528?email_source=notifications\u0026email_token=AKX2XP3HZ3J4RUBEECQSX2LQROLZ5A5CNFSM4JGZ6EG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZ3HPA#issuecomment-548647868",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chenyuejs** [comment]
So, how to solve this error?

**Comment by LianJilu** [comment]
I found all bmap has this bug, it maybe bmap use the wrong or default data value dimensions. I am looking for this bug.

**Comment by LianJilu** [comment]
It can add encode option to fix it, is it a bug althougt @Ovilia 
![image](https://user-images.githubusercontent.com/25577583/71471635-1dec5400-280b-11ea-87af-45eac2c066de.png)
