### ISSUE TITLE
Treemap set selected node pragmatically

### ISSUE THREAD

**Issue by MohanadI** [apache/echarts#11525]
### Version
4.2.1-rc.2

### Reproduction link
[https://jsfiddle.net/r2v4qwj0/](https://jsfiddle.net/r2v4qwj0/)

### Steps to reproduce
Is there any way to setZoom or setCenter pragmatically for specific node in tree ?
In Addition, " lets suggest that I already have the path or the id of the node "

### What is expected?
zoom to specific node

### What is actually happening?
I can not do zoom to specific node

**Comment by Ovilia** [comment]
Currently, no.
But I found there is a `treemapZoomToNode` action. I tried to use it but it seems the view is not updated correctly.

```js
myChart.dispatchAction({
  type: 'treemapZoomToNode',
  seriesIndex: 0,
  dataIndex: 1
});
```

I think a pull request is required to make it work. @MohanadI Are you interested in looking into the source code?
