### ISSUE TITLE
折线图和柱状图可否加上标签引导线，并让标签和线都支持渐变色？

### ISSUE THREAD

**Issue by dagundejuzi** [apache/echarts#11534]
### What problem does this feature solve?
图表能有更丰富的样式。
![Snip20191031_1](https://user-images.githubusercontent.com/16382880/67916388-81be1c00-fbd0-11e9-99af-a4698b5864c6.png)

### What does the proposed API look like?
引导线像饼图的labelLine一样。标签颜色的渐变就跟其他可设置渐变的属性一样。

**Comment by deqingli** [comment]
#11497
