### ISSUE TITLE
Request for graph link label rotation

### ISSUE THREAD

**Issue by caoyukun0430** [apache/echarts#11540]
### What problem does this feature solve?
I work to generate business process visualization with Echats graph. And I have frequency information showed on link labels. 

But for now the label direction is automatically tangent aligned with the link itself. Since no rotate function is implemented inside graph.links.label. https://echarts.apache.org/en/option.html#series-graph.links

And I met the problem that when lots of links intersect with each other, the label will be messed up due to the automatic direction. 
The problem shows like below:
![edge_intersec](https://user-images.githubusercontent.com/46762174/67958347-569af300-fbf7-11e9-9c15-37da4cb9ae59.png)

Therefore, I want to fix the link label direction to be horizontal for all edges

### What does the proposed API look like?
I want to have first that we can set the link label direction fixed for all edges, e.g. horizontal or vertical.

Otherwise, at least the rotation option should be available inside graph.links.label, similar to graph.nodes.label
```javascript
options = {
  animationDurationUpdate: 150,
  animationEasingUpdate: 'quinticInOut',
  series: [{
    type: 'graph',
    layout: 'none',
    edgeSymbol: ['none', 'arrow'],
    edges: graphdata.edges.map(function(edge) {
      return {
        source: edge['start_node_id'],
        target: edge['end_node_id'],
        name: edge['label'],
        lineStyle: {
          normal: {
            width: edge['width']
          }
        },
        label: {
        // proposed change here another option is  
        // direction: 'horizontal',
        rotate:90, 
          show: true,
        }
      };
    }),
    label: {
      emphasis: {
        position: 'top',
        show: true,
      }
    },
    roam: true,
    focusNodeAdjacency: true,
  }]
};
```

**Comment by Ovilia** [comment]
I think this is a reasonable feature request. I've done a similar thing with Sunburst charts.
If @caoyukun0430 is interested in making a pull request, please check out [SunburstPiece.js](https://github.com/apache/incubator-echarts/blob/master/src/chart/sunburst/SunburstPiece.js#L279).

**Comment by caoyukun0430** [comment]
> I think this is a reasonable feature request. I've done a similar thing with Sunburst charts.
> If @caoyukun0430 is interested in making a pull request, please check out [SunburstPiece.js](https://github.com/apache/incubator-echarts/blob/master/src/chart/sunburst/SunburstPiece.js#L279).

Thank you for your reply Ovilia. If I would like do similar modification for the graph, which js file shoud I look into? Thank you for your help. :)
