### ISSUE TITLE
Bug: sunburst chart highlight not working

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#11558]
### Version
4.4.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=sunburst-monochrome](https://echarts.apache.org/examples/zh/editor.html?c=sunburst-monochrome)

### Steps to reproduce
Hover on one node, it's ancestor nodes should be highlighted and others downplayed.
It had worked at first release, but not working now.

### What is expected?
Hover on one node, it's ancestor nodes should be highlighted and others downplayed.

### What is actually happening?
Nothing.

**Comment by shyam-infraon** [comment]
Any luck on this, my version of ecart is 4.04

**Comment by Ovilia** [comment]
Checked with 5.3.2 and there seems to be no bug now.
