### ISSUE TITLE
Would like ECharts to feature more than six themes by default

### ISSUE THREAD

**Issue by WebCodePro719** [apache/echarts#11550]
### What problem does this feature solve?
The ECharts master only comes with six themes. Many users may not want to spend time building their own themes, whether by hand coding or with a theme builder. 

Including more themes in the master and for download (https://www.echartsjs.com/en/download-theme.html) would save users time when it comes to customizing chart colors and styles. With more theme choices, most users would be able to quickly find a theme that matches their application. And changing the theme would only take seconds- all you would have to do is change the theme name in two places in the HTML.

Many users would rather have more pre-built themes to choose from so that they don't have to build themes themselves.

### What does the proposed API look like?
The API would not change at all. All that's needed would be to add the JS files I've already made to the theme folder in the ECharts master and the "download theme" page on the ECharts website.

A while ago I created some custom themes for ECharts 3.0: https://github.com/apache/incubator-echarts/issues/5360

I've now created a custom themes package for ECharts 4.0. -- All of the themes from the previous post are included, and there are some new custom themes.

Here is a link to the CodePen I created to feature the custom themes:
https://codepen.io/WebCodePro/full/oNNpMxw

Here is a direct link to the zip file with the custom theme JS files (hosted on CodePen):
https://s3-us-west-2.amazonaws.com/s.cdpn.io/95368/echarts-4.0-custom-themes-v1.zip

Here is a PNG with theme screenshots (hosted on CodePen):
https://s3-us-west-2.amazonaws.com/s.cdpn.io/95368/theme-screenshots.png

It would be great if you would include some, or all, of these custom themes in the ECharts master.

**Comment by pissang** [comment]
Wow that's nice!! Thanks a lot!

Would mind making a pull request to add your theme to the repo https://github.com/apache/incubator-echarts/tree/master/theme ?

We will add them to https://www.echartsjs.com/en/download-theme.html ASAP after it is added to the repo.
