### ISSUE TITLE
Probem for share dataset

### ISSUE THREAD

**Issue by yinghkt2019** [apache/echarts#11597]
### Version
4.3.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xVzi6bdC7](https://gallery.echartsjs.com/editor.html?c=xVzi6bdC7)

### Steps to reproduce
常滑鼠在bar chart中轉換時, label的data會更新, 但pie chart的圖表沒有即時更新, 雖然滑鼠指向空白的地方才會更新

### What is expected?
label的data和pie chart圖表同時更新

### What is actually happening?
只有label的data更新, pie chart圖表要指向空白的地方才會更新

**Comment by Ovilia** [comment]
Thanks for reporting. This seems to be a bug.

**Comment by Zaynex** [comment]
I'm following up.

**Comment by stormrise** [comment]
I recently notice a problem that the share dataset chart, just use the example <https://echarts.apache.org/examples/en/editor.html?c=dataset-link> as example
 I set the tooltip -> showContent = true, and this tooltip content not always show, actually I call it "blink", randomly disappear.
According to @yinghkt2019 says: when mouse over blank will update the pie chart, in this case only when mouse over the line or bar the tooltip shows normal. 
So I think it is something confict with two render update.
