### ISSUE TITLE
svg模式 地理位置绘制无渐变效果

### ISSUE THREAD

**Issue by szkissyh** [apache/echarts#11614]
### Version
4.4.0

### Steps to reproduce
1、将 charts设置为svg模式
2、地图无渐变效果

canas效果
![image](https://user-images.githubusercontent.com/31839257/68542074-51059000-03e3-11ea-8f6f-269c9f5ef501.png)

svg效果
![image](https://user-images.githubusercontent.com/31839257/68542081-71354f00-03e3-11ea-81ea-d96567a94d59.png)

样例代码：

	 geo: {
           name: 'USA PopEstimates',
                type: 'map',
                roam: true,
                map: 'USA',
                layoutSize: 100,
                zoom: 1.2,//地图放大1.2倍
            label: {
                emphasis: {
                    show: true,
                    color: '#fffefe',
                    formatter:function(data){
                    	return nationCE[data.name]
            		}
                }
            },
	        itemStyle: {
	            normal: {
	                borderColor: 'rgba(147, 235, 248, 0.6)',
	                borderWidth: 0.8,
	                areaColor: {
	                    type: 'linear-gradient',
	                    x: 0,
	                    y: 30,
	                    x2: 7,
	                    y2: 0,
	                    colorStops: [{
	                        offset: 0,
	                        color: '#00befc' // 0% 处的颜色 #009DA1
	                    }, {
	                        offset: 1,
	                        color: '#083fb5' // 50% 处的颜色 #005B9E
	                    }],
	                    global: true // 缺省为 false
	                },
	            },
	            emphasis: {
	                areaColor: {
	                    type: 'linear-gradient',
	                    x: 0,
	                    y: 30,
	                    x2: 7,
	                    y2: 0,
	                    colorStops: [{
	                        offset: 0,
	                        color: '#6AFFEC' // 0% 处的颜色 #009DA1
	                    }, {
	                        offset: 1,
	                        color: '#47C5FF' // 50% 处的颜色 #005B9E
	                    }],
	                    global: true // 缺省为 false
	                },
	            }
	        },

### What is expected?
和canvas模式一样，能正确地图渐变效果

### What is actually happening?
svg模式和canvas模式行为不一样

**Comment by helgasoft** [comment]
fixed, ok in v.5.4.1 - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-usa-pie&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKM9tDwSAgwjMT4SHCMMACyUAAOpFJ6Ahai7l4-loHBwQIANioA1lAAXAFBxcGljFZwtQC0AIwAzB3m9Q1wqKm1AEwArH0Nwej4uHAQtR1j_aIAvpPFwlDoUPj4tUVTTS3tHR0ADBsDQ6MAHFfFM3MLossN6ytSfDaJg6Ks-HsqCkBxWjWarVEbQA7AA2B7BQbDUQjeFg0RPeajFareqrKj1IZOFwAXjqDU0oKmomAaVqmX0FnRMBwwFqcBgPwRonwCWAujgICaVOpokIqBgtNKItFogARhLcIkwKhShL6TBiHKoKQOgAWaGWEZdCYovX3UTnBCw8hM2XBBUwJUwADqsyxloQ93RDVgjCgKrVMBl9sFqUY9NKRH9MDaxBgeHwjEIcDt9uCAA9apcfVMQLUujn05mRotDbmGiBS5budSgUGBUMkLUANoVqaHYvFVBWKxqSFFrvFevq6QAYnO5zlzXsUlEMhkloApKJACCagBC3QA5GYAnINEE_OAE4ACICDrt9610Wdoc9vvMRaX2Uj4Pj863LpWOVjOcL17nFcbjue6TmMABCB4AKLnsUuJdgAuo-xTEGq2rSqIHI_POi6AFz-gCA7oAXHLWFApRqO2sGih8sqMMAqTQEgcQhtSfoBqqo7XrKYYRtIUaEDGcYJgQyapohmbZiJoj5qIhbiRm1bll2VZidBz6NqkzaiG2Q7klpoi3v2Sk6aIz70mOsICAAYuZEFgD-i7_muW67vux6ntBwSUUO7HFnp96iL0bnDqxL5SGOBpgGMlm2X-AGOcB5xgZBAXkemCHQchqCoeynKMFhoh4YRVjEaR6bJVMpXuTiGyrDQwSgJAsCIBAsyMNgiYkBQNU0uA4SIP27CpMShCkESzi-DQ-KUEAA)
