### ISSUE TITLE
The brush outOfBrush not working

### ISSUE THREAD

**Issue by vvkee** [apache/echarts#11649]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xWNzZjbNt&v=1](https://gallery.echartsjs.com/editor.html?c=xWNzZjbNt&v=1)

### Steps to reproduce
1. Open the '横向选择'
2. Select an area.

### What is expected?
The opacity of the line charts is 1.

### What is actually happening?
The opacity of the line charts should be 0.1.

---
I don't know what the config is wrong or some components overlaid the outOfBrush style.

**Comment by deqingli** [comment]
sorry, I don't quite understand what you mean, please provide more detailed message.

**Comment by vvkee** [comment]
@deqingli 
**Steps to reproduce:**
1. Open the link (https://gallery.echartsjs.com/editor.html?c=xWNzZjbNt&v=1)
2. Click the '横向选择' button in the toolbox
3. Using the brush to select an area.
4. Observe that all the line charts are highlighting.

**Expected:**
Since I set the `outOfBrush` in the brush config(You can check the link config), the selected  area should be highlighted, and the unselected should have 0.5 transparency.

**Comment by Ovilia** [comment]
Seems to be a bug.

**Comment by newraina** [comment]
see [Brush doc](https://echarts.apache.org/en/option.html#brush):
> Currently, supported brush types include: scatter, bar, candlestick

the reproduction demo's series type `line` is not in supported list, I think "the actually happening" is normal behavior.

**Comment by Bartvanderkruys** [comment]
@vvkee did you find a way to make this work? Is there any way to make a selection on a line plot?

**Comment by vvkee** [comment]
> @vvkee did you find a way to make this work? Is there any way to make a selection on a line plot?

no yet. We don't need this feature anymore

**Comment by Bartvanderkruys** [comment]
In case anyone is interested. I solved my use-case by adding a hidden bar series, and using the brushLink option to link the selection.

**Comment by vvkee** [comment]
I wanted to use multiple layers before, but this is very troublesome.
