### ISSUE TITLE
BUG - SVG导出图片显示错位

### ISSUE THREAD

**Issue by eniaclyl** [apache/echarts#11675]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xGPZTlK-D&v=1](https://gallery.echartsjs.com/editor.html?c=xGPZTlK-D&v=1)

### Steps to reproduce
注意：我的链接里面不知道为什么导出的svg是错误的文件，你需要在本地使用链接里面的代码
1、谷歌浏览器运行后，显示的svg是正常的效果。
2、将导出的svg插入到word 2019 或者 Adobe Illustrator CC 2019 显示效果都错误

### What is expected?
这些软件加载的效果能和谷歌浏览器运行时看到的效果一样

### What is actually happening?
字体尺寸变小，字体偏移

---
请问这是否为echarts在svg模式下的bug，如果时bug何时会修复？谢谢

**Comment by zhangjl-sjtu** [comment]
So far, this bug still exists. I hope it can be solved as soon as possible
