### ISSUE TITLE
折线图中 tooltip  formatter使用异步callback(ticket, html)，同时使用了echarts.connect联动多个图表，tooltip显示不正确

### ISSUE THREAD

**Issue by Ricardozhang** [apache/echarts#11682]
### Version
4.5.0

### Steps to reproduce
1. 使用折线图
2. 为了使用异步加载tooltip，使用了如下配置
```js
tooltip: {
    trigger：'axis'，
    formatter: (params, ticket, cb) => {
        setTimeout(() => {
             cb(ticket, 'loaded');
        }, 100);
        return 'loading';
    }
}
```
3. 配合echarts.connect使多个图表联动时，其他的图表的tooltip  callback失效，tooltip无法正确显示

### What is expected?
多个图表的tooltip 使用formatter  callback时，能正常使用

### What is actually happening?
为了使用异步加载tooltip，我使用了如下配置
```js
tooltip: {
    trigger：'axis'，
    formatter: (params, ticket, cb) => {
        setTimeout(() => {
             cb(ticket, 'loaded');
        }, 100);
        return 'loading';
    }
}
```
在单图表中是可以正常显示的，但是配合echarts.connect使多个图表联动时，其他的图表的tooltip  callback失效，tooltip无法正确显示

**Comment by Ovilia** [comment]
`formatter` shouldn't be async.

**Comment by wh19951224** [comment]
用字符串模板 有 问题 -- formatter: '{a}<br/> {b0}: {c0}% <br/>{b1}: {c1}%' 默认第一组数据 + 0.01？

**Comment by Ricardozhang** [comment]
@Ovilia 
[https://www.echartsjs.com/zh/option.html#tooltip.formatter](https://www.echartsjs.com/zh/option.html#tooltip.formatter )
官网中提供了callback, formatter 可以是 异步的

官方文档：
2, 回调函数
回调函数格式：
(params: Object|Array, ticket: string, callback: (ticket: string, html: string)) => string

![image](https://user-images.githubusercontent.com/14835976/69326903-98afd580-0c87-11ea-9a36-5e4ae543e702.png)

**Comment by Ovilia** [comment]
@Ricardozhang 哦哦，不好意思，那是我说错了~
https://gallery.echartsjs.com/editor.html 在这里提供一个复现的例子吧

**Comment by Ricardozhang** [comment]
https://gallery.echartsjs.com/editor.html?c=xEoarhoeh&v=5
这里是复现的例子 @Ovilia

**Comment by Ovilia** [comment]
可以复现

**Comment by nonespace** [comment]
多个ecahrt 连接有其中一个 当前x坐标对应的y轴的值为null  , 这个tooltip只在当前ehart 显示,怎么同步给其他组件呢
