### ISSUE TITLE
Graph关系图是否支持选中多个节点(点)

### ISSUE THREAD

**Issue by Caitingwei** [apache/echarts#11723]
### What problem does this feature solve?
目前我项目里需要选中多个(点)来查看它们之前的公共维度信息, 若选中多个点则展开共同的信息。请问echarts的graph关系图是否支持用鼠标选择多个点呢？

### What does the proposed API look like?
单击或双击或其他操作方式选中多个点保持选中的多个点持续高亮

**Comment by pissang** [comment]
数据选择的优化优化会作为一个大的 topic 来做

**Comment by iaminvictus1993** [comment]
mark
