### ISSUE TITLE
Rotate/not show the axis Label when zooming the chart

### ISSUE THREAD

**Issue by leorigon** [apache/echarts#11738]
### Version
4.5.0

### Steps to reproduce
In a chart with large amount of data, when zooming the chart, I can't make the axis Label rotate or disappear. I searched on docs, but I don't find something about. In interval prop, I take only the index of array and I cant work with this. I need to show the first 20 values of the chart, I made it works. But when the zooming is applied the axis Label is overlap.

### What is expected?
Rotate or make disappear the axisLabel on zooming. 

### What is actually happening?
When the zooming is applied the axisLabel is overlaped.

**Comment by pissang** [comment]
You can set rotate with https://echarts.apache.org/en/option.html#xAxis.axisLabel.rotate

**Comment by leorigon** [comment]
Yes, I saw it, but I need rotate dynamically when zooming the chart. With 20 bars rotate value is 0, with more than 20 bars, the rotate value needs change automatic.

**Comment by pissang** [comment]
You can `setOption` and update rotate dynamically on `dataZoom` event.

**Comment by leorigon** [comment]
You have an example of how I can do it? I don't find option to update automatically my bar charts.
