### ISSUE TITLE
Echarts关系图(Graph)一个点(Node)不能同时存在两个起始点和目标点相同的边

### ISSUE THREAD

**Issue by Caitingwei** [apache/echarts#11744]
### Version
4.5.0

### Reproduction link
[https://codepen.io/caitingwei/pen/dyypgqp?editors=1010](https://codepen.io/caitingwei/pen/dyypgqp?editors=1010)

### Steps to reproduce
1.当存在两个起始点和目标点相同的边时，只能渲染出一条边出来。

### What is expected?
显示出两条不同边名的边

### What is actually happening?
只渲染了一条边
![image](https://user-images.githubusercontent.com/24822015/69848871-27d77180-12b6-11ea-94e8-fbf3d1ccd757.png)
比较急，请给一个解决方案。谢谢

**Comment by deqingli** [comment]
#11260
