### ISSUE TITLE
Highlight focused series in axis tooltip

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#11749]
### What problem does this feature solve?
When someone hovers over a specific series, and the tooltip is shown, we need to highlight the specific series in the tooltip.
This happens when the tooltip trigger is axis.
Please see the screenshot provided for an example.

![HighlighHoveredSeries](https://user-images.githubusercontent.com/890368/69876095-63c70280-12c7-11ea-9807-36b6679042b4.png)

### What does the proposed API look like?
When the 
tooltip.formatter string, Function
is a callback function in the params Object|Array
have an property called 

focused of type boolean

for each item which is true when the mouse is hovering over the item's specific series.

**Comment by MINDoSOFT** [comment]
Hello @yufeng04 ,

I just read my description and the _proposed API_ doesn't make any sense. I'll try to rewrite it here.

**What does the proposed API look like?**

Basically when we have _tooltip.trigger Axis_ and the _tooltip.formatter Callback function_ is called can you add a Boolean property to the _params_. That parameter will be called **_focused_** that will be True when the mouse is hovering over the specific series at that moment when the tooltip was triggered.

Thank you for you time and effort.

Best regards,
Sergios.

**Comment by ktschmincke** [comment]
Any update here? I would love this functionality as well.
