### ISSUE TITLE
下载图片可以附加一些额外的信息吗？比如“描述信息xxxxxxxxxxx”，这个信息是在图上未显示的。

### ISSUE THREAD

**Issue by ISBN9527** [apache/echarts#11757]
### What problem does this feature solve?
将解决我我可以高度自定义图片，想加什么信息加什么信息

### What does the proposed API look like?
getDataURL

**Comment by yufeng04** [comment]
Do the `title.text` and `title.subtext` meet your needs?

**Comment by ISBN9527** [comment]
**当我在下载图片时，这是我需要额外附加的信息，title.text and title.subtext do not meet my needs**

![企业微信截图_d397f89e-93a7-4efe-839d-6388f0f50083](https://user-images.githubusercontent.com/30942709/70026844-a9dbd900-15db-11ea-9f34-d6dba09f3684.png)

**Comment by ISBN9527** [comment]
Looking forward to your reply

**Comment by ISBN9527** [comment]
Looking forward to your reply

**Comment by yufeng04** [comment]
I don't think this feature is suitable for ECharts. You may need to create a canvas and draw what you need.

**Comment by ISBN9527** [comment]
@pissang 
我想通过show:  false来隐藏，但是在下载图片的时候带上标题和副标题，这样我就可以自定义我的图片，请问这样的需求不合理吗？

**Comment by pissang** [comment]
@ISBN9527 可以试试再另外建一个实例，这个实例里包含了标题和副标题，但是实例本身不显示，下载的时候就从这个实例导出图片

**Comment by ISBN9527** [comment]
如果这个模块里面echarts图表很多，这样不会影响渲染速度吗？

**Comment by ISBN9527** [comment]
有没有稍微优雅一点的方式呢，大佬
