### ISSUE TITLE
Sunburst  series.levels.label. formatter not work

### ISSUE THREAD

**Issue by wangyx233** [apache/echarts#11764]
### Version
4.1.0-rc.2

### Steps to reproduce
Set series.levels each level‘s label formatter

### What is expected?
format work

### What is actually happening?
format not work

---
Set series.data.label or series.label formatter, these all work well, but levels label formatter not.
Test use official example, like https://www.echartsjs.com/examples/zh/editor.html?c=sunburst-drink

    series: {
        type: 'sunburst',
        highlightPolicy: 'ancestor',
        data: data,
        radius: [0, '95%'],
        sort: null,
        levels: [{}, {
            r0: '15%',
            r: '35%',
            itemStyle: {
                borderWidth: 2
            },
            label: {
                rotate: 'tangential',
                formatter: (params) => {
                    return params.name.slice(0, 1)
                }
            }
        }, {
            r0: '35%',
            r: '70%',
            label: {
                align: 'right',
                formatter: (params) => {
                    return params.name.slice(0, 2)
                }
                
            }
        }, {
            r0: '70%',
            r: '72%',
            label: {
                position: 'outside',
                padding: 3,
                silent: false,
                formatter: (params) => {
                    return params.name.slice(0, 3)
                }
            },
            itemStyle: {
                borderWidth: 3
            }
        }]
    }

**Comment by luxward** [comment]
+1
