### ISSUE TITLE
Surface cannot display at  the right position

### ISSUE THREAD

**Issue by ShannonZ** [apache/echarts#11794]
### Version
4.5.0

### Steps to reproduce
Based on https://www.echartsjs.com/examples/zh/editor.html?c=simple-surface&gl=1
1. Using log-scaled axes

`
xAxis3D: {
        type: 'log'
    },
    yAxis3D: {
        type: 'log'
    },
`
2. Generate some data
`series: [{
        type: 'surface',
        wireframe: {
            // show: false
        },
        equation: {
            x: {
                step: 0.05
            },
            y: {
                step: 0.05
            },
            z: function (x, y) {
                if (Math.abs(Math.log(x)) < 0.1 && Math.abs(Math.log(y)) < 0.1) {
                    return '-';
                }
                return Math.sin(Math.log(x) * Math.PI) * Math.sin(Math.log(y) * Math.PI);
            }
        }
    }]`

### What is expected?
The surface should be display in the coodinates box.

### What is actually happening?
Cannot see the surface at the right place.

**Comment by yufeng04** [comment]
It seems to be a bug!
![image](https://user-images.githubusercontent.com/22974511/70298274-07666480-182c-11ea-9f2c-4f34a219e583.png)

**Comment by pissang** [comment]
@ShannonZ The equation is not for log axis. Can you provide a real-world log data?
