### ISSUE TITLE
柱状图lable标签显示的时候，position: "inside"的时候数值被遮挡

### ISSUE THREAD

**Issue by ISBN9527** [apache/echarts#11796]
### Version
4.5.0

### Steps to reproduce
show: true,
position: 'inside',
 rotate:-90,
 color: '#333',
 fontWeight: 'bold',

### What is expected?
不被遮挡

### What is actually happening?
实际没有达到效果

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/70223471-b9e3ec00-1786-11ea-9bc2-73cf4ee0aa5c.png)

**Comment by pissang** [comment]
@ISBN9527 谢谢反馈，这个在我们的标签优化规划内
