### ISSUE TITLE
Update doc about the switch from `min` and `max` for piece options to `lt` `gt` `lte` `gte`

### ISSUE THREAD

**Issue by martialp** [apache/echarts#11818]
### Version
4.5.0

### Steps to reproduce
Read [this](https://github.com/apache/incubator-echarts/blob/2b5a3ee4b674f1dd8b9be16b65bf530e65eb7da4/src/component/visualMap/PiecewiseModel.js#L477) comment:
```
// `min` `max` is legacy option.
// `lt` `gt` `lte` `gte` is recommanded.
```

and read the [associated section of the documentation](https://echarts.apache.org/en/option.html#visualMap-piecewise.pieces)

### What is expected?
The document should have been updated to use lt, gt, lge and gte

### What is actually happening?
The doc still use min and max

**Comment by Ovilia** [comment]
@martialp Thanks for reporting. Do you mind making a PR? The source code is https://github.com/apache/incubator-echarts-doc/blob/73d54a98297c6123ea8dfab5354b39dbbd1ab5dd/en/option/component/visual-map-piecewise.md
