### ISSUE TITLE
hope that beside every option doc, there is a related demo link so that we can see the difference by the option in the chart directly

### ISSUE THREAD

**Issue by SunGuoQiang123** [apache/echarts#11845]
### What problem does this feature solve?
improve the efficiency to learn every option functionality . 

### What does the proposed API look like?
we have a alot of examples, but the examples dost not have the  direct realtion to the large amout options. If we can build the link between the  examples and the options, i think we will use echarts much better

**Comment by Ovilia** [comment]
Yes, that's exactly the thing we plan to do.
Apparently, there's a large amount of work to be done. So we don't have concrete plans for this.
You are welcomed to discuss about more details about how this should be done.

**Comment by SunGuoQiang123** [comment]
great！couldn't wait to see this doc feature, if i have some related opinions,i still put them here, thanks
