### ISSUE TITLE
打包一个支持 ES6 import 的 build

### ISSUE THREAD

**Issue by maicWorkGithub** [apache/echarts#11855]
### What problem does this feature solve?
可以在较新的浏览器里使用import ECharts from './echarts.min'

### What does the proposed API look like?
可以在较新的浏览器里使用import ECharts from './echarts.min'

**Comment by pissang** [comment]
浏览器里直接使用
```html
<script type="module">
import ECharts from './echarts.min'
</script>
```
引入？

**Comment by maicWorkGithub** [comment]
嗯。

但是我没找到什么方式怎么判断浏览器是否支持了export/import……

**Comment by Ovilia** [comment]
This is not an issue directly related to ECharts. Please search for solutions elsewise.

**Comment by maicWorkGithub** [comment]
如果这是一个暂时无法解决的问题，是一个共性问题，那如你所说。但是如果这个很简单，你们能搞定，怎么就和你们没关系了呢，就像你们发布的默认是commonjs版本的一样，发布一个`echarts.module.js`就可以了。现在浏览器进步了，大家用各种构建工具做出来的东西，反而跟不上浏览器的进步？

**Comment by zevero** [comment]
Please include a "echarts.module.js" or "echarts.mjs" in your dist folder, which can be imported as an ES6 module as stated above.
Highcharts is doing it since v6.1.0 April 2018!!!
https://github.com/highcharts/highcharts#load-highcharts-from-the-cdn-as-ecmascript-modules

**Comment by zevero** [comment]
Please @pissang or @Ovilia  reopen!

**Comment by zevero** [comment]
Would be nice if this could fit into new Echart 5.0 stable!

**Comment by pissang** [comment]
Added in https://github.com/apache/incubator-echarts/commit/cb5cfdc0682402380824ba9756bf116b3b945d14

**Comment by superchangme** [comment]
> 浏览器里直接使用
> 
> ```
> <script type="module">
> import ECharts from './echarts.min'
> </script>
> ```
> 
> 引入？

我直接importmap引入了echarts.esm.min.js,
第三方插件使用了下面这种方式，会导致cdn失效，重复打包有什么解决方案吗
import * as echarts from "echarts/core";
![image](https://github.com/user-attachments/assets/dc37ec3a-1b45-48fa-b79a-5dff76e5434f)
