### ISSUE TITLE
Overlay data from different periods in a line graph

### ISSUE THREAD

**Issue by Zigotote** [apache/echarts#11868]
### What problem does this feature solve?
**My context :**
Every day, some statistics are calculated about the use of our applications.

**My needs :**
- I would like to be able to show the statistics from a period (for exemple the current year) --> done with a line graph
- I would like to be able to add an other time period to my graph, to be able to compare the data between two (or more) different time periods. It could allow my team to predict how our applications will be used, and on wich projects we should be more focus depending on the past years' statistics.

**Why is it usefull ?**
Being able to superimpose data can be usefull in many other cases, if the user wants to compare data over several time period.

**How should the graph look like ?**
I tried to do this on my own, while using a lot "formatter" methods but it is really hard and the rendering can be quite slow. On the top of this, catching every interactions between the user and the graph isn't always possible.

But my idea is to put a different lineStyle for every period we want to add (the first one is solid, the second dashed and the third dotted). Then, every time periods should be added on the xAxis, one above the other, so that we can easily see where which day is displayed. Maybe it could be great to adapt the text style of each period to the corresponding lineStyle (by underlining it for example ?). Then, the tooltips should be corrected to, in order to know which value corresponds to which date. 

This is a screenshot of what I am trying to explain :
![Capture d’écran de 2019-12-18 16-26-40](https://user-images.githubusercontent.com/34279302/71099585-d256fc00-21b3-11ea-826b-056d5763c3c8.png)

 
### What does the proposed API look like?
The proposed API could look like that :
```json
let options = {
    xAxis: {
        data: { list_1, list_2 }
    },
    series: [
        {
            type: 'line',
            name: 'whatever',
            data: list_whatever1,
            overlay: 0
        },
        {
            type: 'line',
            name: 'whatever',
            data: list_whatever2,
            overlay: 1
        }
    ]
}
```
With the "overlay" attribute saying to which xAxis data list the line is bounded to.

**Comment by deqingli** [comment]
hi @Zigotote, thanks a lot for such a detailed suggestion, in version 5.0 we consider adding some data analysis related features. If you are interested, you can join us to discuss or develop together. At that time, I will organize the current plan into an issue.

**Comment by Zigotote** [comment]
Hi @deqingli, its seems indeed quite interesting to me ! How could I join you to discuss more about that ?
