### ISSUE TITLE
Allow pass nodeClick with a callback function for sunburst

### ISSUE THREAD

**Issue by ding-js** [apache/echarts#11867]
### What problem does this feature solve?
Deal with advanced user behavior and reduce server performance costs.
For example, our data structure with many levels are complex and we only want to show the top level, then we will load child data when user click the top level.

### What does the proposed API look like?
```js
{
  nodeClick: ({ node, rootToNode }) => {
    if (node.children) {
      rootToNode();
    } else {
      // 1. load children data
      // 2. refresh chart
    }
  };
}
```

**Comment by bill-mark** [comment]
let charts = this.$echarts.init(document.getElementById("charts-bar"));
      
      charts.on('click', params =>{
        console.log('params::', params)
      })
