### ISSUE TITLE
Sampling interfering with stacking

### ISSUE THREAD

**Issue by zevero** [apache/echarts#11879]
### Version
4.5.0

### Reproduction link
[https://jsfiddle.net/u1mj9wfg/1/](https://jsfiddle.net/u1mj9wfg/1/)

### Steps to reproduce
Notice the minimum Value in the middle of the Chart beeing 0.
Now set the width of the div from 1200 to 1000 and rerun.
 

### What is expected?
Chart is drawn width width 1000 preserving all characteristics.

### What is actually happening?
Min Value in the middle of the chart is lost!

---
This only occurs when two series are stacked. Commenting line 36 will show the minValue as expected.

We were showing critical events in some machines and we discovered that the charts were not reflecting those critical events.

**Comment by 100pah** [comment]
Could I know: why need to stack these two series?

**Comment by zevero** [comment]
I display generic timeSeries chart from signal values from a complex machine: water pressure, flow rate, temperature, voltage and hundreds more.
For each signal I show on different time scales (hourrly, daily) MeanValue, minValue, maxValue.
To view the array between minValue and maxValue I produce a grey area stacking minValue plus deltaValue=maxValue-minValue. 
With legend I can optionally unhide other series, like quartiles, median, derivates, skew etc.
A bit like a stock chart.
I have mitigated my problem by precalculating hourly and daily values. But still think, this is a bug since stacking makes the sampling option ineffective.

**Comment by 100pah** [comment]
TODO fix: 
(1) `dataSampling` processor is after `dataStack` processor. So `List#downSample` should retrieve data from the `__ecstackresult` (if exists) dimension rather than the original dimension.
(2) Probably we can provide a new sampling option: `min-max` to reserver both of the characteristics.
