### ISSUE TITLE
[PROPOSAL] More powerful formatters: pipes

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#11878]
### What problem does this feature solve?
ECharts has many `formatter` options, which provides a flexible display method in both forms of string and function.

In some cases, function is not applicative, like formatters in theme or in Baidu Smart App.
So, I'd suggest we provide some frequently used pipes so that users can use it in string format.

### What does the proposed API look like?
- `{a | thousandSeparator} kg`: if `{a}` is 1234567, the output is `1,234,567 kg`.
- `{b | decimalPlaces: 2}cm`: if `{b}` is 12.3456, the output is `12.34cm`.
- ...

**Comment by 100pah** [comment]
The grammar `{a | method} ` conflicts with rich text (`{styleName|real text}`).
Probably it needs to consider another grammar.

```js
// (A) ?
formatter: '{a : method1 : method2(123)}' 
formatter: 'xxxx {style1|{a : method1 : method2(123)}}' // in rich text
formatter: 'xxxx {style1|yyyy} {a : method1 : method2(123)}' // in rich text

// (B) ?
formatter: '{a => method1 => method2(123)}' 
formatter: 'xxxx {style1|{a => method1 => method2(123)}}' // in rich text
formatter: 'xxxx {style1|yyyy} {a => method1 => method2(123)}' // in rich text

// (C) ?
formatter: '{a # method1 # method2(123)}' 
formatter: 'xxxx {style1|{a # method1 # method2(123)}}' // in rich text
formatter: 'xxxx {style1|yyyy} {a # method1 # method2(123)}' // in rich text

// (D) ?
formatter: '{a $ method1 $ method2(123)}' 
formatter: 'xxxx {style1|{a $ method1 $ method2(123)}}' // in rich text
formatter: 'xxxx {style1|yyyy} {a $ method1 $ method2(123)}' // in rich text

```

We'd better avoid common calculation characters are used as delimiter.
And we may also need to consider some how it makes break change and how to escape functional characters like 
`{` `}` `|`

**Comment by Ovilia** [comment]
I don't think it's a good idea to use other separators rather than `|` because `|` is more common used and thus makes users understand it better.
As for the rich text conflict, I think maybe we can use special formatter name for built-in pipes like `{a | $thousandSeparator} kg` or `{a | #thousandSeparator} kg`.

**Comment by 100pah** [comment]
But we can not tell which is rich text and and which is pipe.
```js
formatter: 'xxxx {style1 | $money} {a | $thousandSeparator}}' 
```

**Comment by Ovilia** [comment]
We can check if it's a pipe name. If not, it's rich.

**Comment by 100pah** [comment]
> We can check if it's a pipe name. If not, it's rich.

I am still worried that it brings bad readability. If we do not name it 'pipe', but name it 'filter', is it might not necessarily use the "pipe symbol"?

BTW, write something related in #11906

**Comment by kristalhu** [comment]
How can we check 


Sent from Yahoo Mail for iPhone


On streda, decembra 25, 2019, 5:43 PM, sushuang <notifications@github.com> wrote:



We can check if it's a pipe name. If not, it's rich.


I am still worried that it brings bad readability. If we do not name it 'pipe', but name it 'filter', is it might not necessarily use the "pipe symbol"?

BTW, write something related in #11906

**Comment by dberardo-com** [comment]
i there,  is there a page in the doc explaining how formatter string templates actually work and which parameters they accept ? i am in need of rounding the value to 2 decimal places but cant find info anywhere
