### ISSUE TITLE
当环形图偏移时，graphic自定义文字无法居中的问题

### ISSUE THREAD

**Issue by qingwenje2008** [apache/echarts#11889]
![146D26F7-93CE-4cf7-9592-0068CF5463CA](https://user-images.githubusercontent.com/8563448/71248371-a4a9b880-2355-11ea-88aa-97926f2c4a11.png)
### Version
4.2.1

### Steps to reproduce
需求，环形饼图中心向左偏移35%，如图，同样把自定义的文字 向左偏移了35&，但文字 是左顶点与中心线对齐，并不是中线对齐

### What is expected?
文字 中心线与环形图中心线对齐

### What is actually happening?
左基准线与环形图中线对齐

**Comment by 100pah** [comment]
That is not a bug. `left` means the distance between the left boundary of the element to the left boundary of the echarts.

But indeed it is hard to locate an element aligning with a component located via `center` (like `pie`, `polar`, `sunburst`).
Perhaps we need to provide some new approaches to locate. For example, provide an `center` prop:
```js
graphic: [{
      type: 'text',
      center: ['35%', '50%'],
      style: {
          text: 'asdfasdfasd'
      } 
}]
```

**Comment by 1Cr18Ni9** [comment]
The `style` config is not works as expected. My solution is draw text by myself after each render loop:
```js
chart.on("rendered", function () {
    var w = this.getWidth(),
        h = this.getHeight(),
        ctx = this.getDom().querySelector("canvas").getContext("2d");
    ctx.save();
    ctx.fillStyle = "#333";
    ctx.font = "15px bolder";

    // eCharts' style.textAlign and style.textVerticalAlign are not work as we expected
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    
    ['CDC', 'ABC', 'DIS', 'ODC'].forEach((name, index) => {
        ctx.fillText(name, w * (index * 0.25 + 0.125), h / 2);
    });
    ctx.restore();
});
```
