### ISSUE TITLE
触摸大屏，双指缩放是整个chrome窗体，没有只对MAP区域

### ISSUE THREAD

**Issue by pythonzhu** [apache/echarts#11881]
### Version
4.0.0

### Steps to reproduce
1、vuejs开发左中右布局；
2、中间地图使用echart bmap
3、双指缩放，整个chrome窗体放大缩小了。
4、硬件为maxhub 75寸，系统环境：win10 chrome

### What is expected?
只针对map区域缩放，类似鼠标zoom效果。

### What is actually happening?
对整个chrome窗体缩放了。

**Comment by 100pah** [comment]
并没有太理解这个问题。
是否可以用图来解释下，chrome窗体放大缩小 是个什么效果？

**Comment by pythonzhu** [comment]
github无法提交视频，通过邮件发给你。







朱俊
江苏南开之星软件技术有限公司
江苏省 扬州市 邗江区邗江中路47号兰苑商务楼501室
网址：www.nankaistar.com.cn
手机：138 1318 6585,180 3623 2121
电话：0514-87590711
邮箱：13813186585@139.com,zhujun@nankaistar.com
 
发件人： sushuang
发送时间： 2019-12-25 01:44
收件人： apache/incubator-echarts
抄送： pythonzhu; Author
主题： Re: [apache/incubator-echarts] 触摸大屏，双指缩放是整个chrome窗体，没有只对MAP区域 (#11881)
并没有太理解这个问题。
是否可以用图来解释下，chrome窗体放大缩小 是个什么效果？

**Comment by pythonzhu** [comment]
github上，我无法将视频或者是图片传上来。
已经发邮件至dev@echarts.apache.org，附件中有操作视频。

**Comment by 100pah** [comment]
dev@echarts.apache.org 中看起来没有收到邮件，是否确定发成功了？

**Comment by pythonzhu** [comment]
您好，确认给dev@echart.apache.org发送了邮件。
同时给您的sushuang0322@gmail.com也发送了视频附件。

手机：138 1318 6585,180 3623 2121
电话：0514-87590711
邮箱：13813186585@139.com,zhujun@nankaistar.com
 
发件人： sushuang
发送时间： 2019-12-26 01:26
收件人： apache/incubator-echarts
抄送： pythonzhu; Author
主题： Re: [apache/incubator-echarts] 触摸大屏，双指缩放是整个chrome窗体，没有只对MAP区域 (#11881)
dev@echarts.apache.org 中看起来没有收到邮件，是否确定发成功了？

**Comment by pythonzhu** [comment]
您好，确认给dev@echart.apache.org发送了邮件。
同时给您的sushuang0322@gmail.com也发送了视频附件。
谢谢。该问题在手机端触摸情况下没问题，在笔记本或者是触摸大屏上会出现。
touch时触发了chrome的缩放事件，并没有触发echart画布区域的缩放事件。

**Comment by 100pah** [comment]
仍然没有发现收到邮件， @pissang @Ovilia @deqingli 你们有收到这个邮件么？

**Comment by pythonzhu** [comment]
链接: https://pan.baidu.com/s/1hSOHf_rAqADSSeHV0VjREA 提取码: i9dm
通过百度网盘已经上传操作视频。

**Comment by pythonzhu** [comment]
需要达到的效果是：中间地图区域缩放，其他区域维持不变。
加急，谢谢！

**Comment by pythonzhu** [comment]
加急，帮忙看下

**Comment by Ovilia** [comment]
https://gallery.echartsjs.com/editor.html?c=xBJDR584vG 这个图在你的环境上能缩放吗？
另外，邮件没收到估计是视频太大被服务器拦截了，也不建议使用网盘的形式分享。后面如果有必要会让你复现一下代码。

**Comment by pythonzhu** [comment]
不知网盘分享的视频效果是否已经收到？
你提供的地址验证还是有问题。缩放区域是整个浏览器，并不只是右边div区域。
 
发件人： Ovilia
发送时间： 2020-01-16 17:56
收件人： apache/incubator-echarts
抄送： pythonzhu; Author
主题： Re: [apache/incubator-echarts] 触摸大屏，双指缩放是整个chrome窗体，没有只对MAP区域 (#11881)
https://gallery.echartsjs.com/editor.html?c=xBJDR584vG 这个图在你的环境上能缩放吗？
另外，邮件没收到估计是视频太大被服务器拦截了，也不建议使用网盘的形式分享。后面如果有必要会让你复现一下代码。

**Comment by 281772147** [comment]
我也遇到同样问题, 在win10电阻屏终端调试发现, 不支持ontouchstart和ontouchend事件, zrender根据浏览器这个参数判断是否是触屏, 因为不支持ontouchstart, 所以该环境就无法实现双指放大缩小. 如果谷歌把模式调成desktop touch模式双指缩放和拖动是无问题的. 关键是只能在调试模式中实现, 无法应用到生产

**Comment by 281772147** [comment]
我也遇到同样问题, 在win10电阻屏终端调试发现, 不支持ontouchstart和ontouchend事件, zrender根据浏览器这个参数判断是否是触屏, 因为不支持ontouchstart, 所以该环境就无法实现双指放大缩小. 如果谷歌把模式调成desktop touch模式双指缩放和拖动是无问题的. 关键是只能在调试模式中实现, 无法应用到生产

**Comment by 281772147** [comment]
在echarts包引入前手动添加ontouchstart事件, window.ontouchstart = function() {}; 避免了win10电阻屏终端那种异类产生的假触屏效果.

**Comment by wx-hh** [comment]
> 在echarts包引入前手动添加ontouchstart事件, window.ontouchstart = function() {}; 避免了win10电阻屏终端那种异类产生的假触屏效果.



> 不知网盘分享的视频效果是否已经收到？ 你提供的地址验证还是有问题。缩放区域是整个浏览器，并不只是右边div区域。 发件人： Ovilia 发送时间： 2020-01-16 17:56 收件人： apache/incubator-echarts 抄送： pythonzhu; Author 主题： Re: [apache/incubator-echarts] 触摸大屏，双指缩放是整个chrome窗体，没有只对MAP区域 (#11881) https://gallery.echartsjs.com/editor.html?c=xBJDR584vG 这个图在你的环境上能缩放吗？ 另外，邮件没收到估计是视频太大被服务器拦截了，也不建议使用网盘的形式分享。后面如果有必要会让你复现一下代码。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题是怎么解决的呢？
