### ISSUE TITLE
仪表盘不支持刻度旋转吗？

### ISSUE THREAD

**Issue by fengyeheng** [apache/echarts#11905]
### Version
4.5.0

### Steps to reproduce
```js
option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}],
            axisLabel: {
                formatter: '{a|{value}kg}',
                verticalAlign: 'top',
                rich: {
                    a: {
                        color: 'blue',
                        //旋转代码
                        rotate: 30
                    }
                }
            }
        }
    ]
};

setInterval(function () {
    option.series[0].data[0].value = (Math.random() * 100).toFixed(2) - 0;
    myChart.setOption(option, true);
},2000);
```
### What is expected?
刻度可以旋转

### What is actually happening?
不能旋转

**Comment by 100pah** [comment]
目前并没有支持。什么场景需要旋转呢？

**Comment by fengyeheng** [comment]
> 目前并没有支持。什么场景需要旋转呢？

![image](https://user-images.githubusercontent.com/39297582/71497050-664e5500-2891-11ea-81c5-0c8ff6240397.png)
![image](https://user-images.githubusercontent.com/39297582/71497053-6e0df980-2891-11ea-909d-ad877cc4521e.png)
下边的图片是我需要的哈。

**Comment by fengyeheng** [comment]
> 目前并没有支持。什么场景需要旋转呢？

麻烦看到了回复一下哈，因为我试了好多属性都不支持旋转。

**Comment by Nickszy** [comment]
意思是要刻度颜色的变化，不要指针旋转，对吧？

**Comment by Nickszy** [comment]
可以修改`series-gauge.axisLine.lineStyle. color`这个属性，具体可参照此[gallery用户示例](https://gallery.echartsjs.com/editor.html?c=xgLtGmtVKw)

**Comment by fengyeheng** [comment]
> 意思是要刻度颜色的变化，不要指针旋转，对吧？

不不，我说的是刻度旋转哈，你对比俩张图片的刻度，不考虑颜色的。 @Nickszy

**Comment by Nickszy** [comment]
我有些不懂你的意思。
建议您可以再看一下我之前给的那个用户[实例](https://gallery.echartsjs.com/editor.html?c=xgLtGmtVKw)，调整最前面的`realValue`的数值，刷新看下效果。
我认为这就是你需要的效果，如果是的话可以再在示例中搜索一下下面的代码进行修改。
```
//健康指数数值
"data": [{
               "name": "目标值："+targetValue+"万吨",
               "value": data.value }]

//仪表盘颜色刻度变化
series: ["axisLine": {
        	                "lineStyle": {
        	                    "color": [
        	                        [data.value / 100, "#BF18FE"],
        	                        [1, "#111F42"]
        	                    ],
        	                    "width": 8
        	                }
        	            }]
```

**Comment by Nickszy** [comment]
> > 意思是要刻度颜色的变化，不要指针旋转，对吧？
> 
> 不不，我说的是刻度旋转哈，你对比俩张图片的刻度，不考虑颜色的。 @Nickszy

我有些不懂你的意思。
建议您可以再看一下我之前给的那个用户[实例](https://gallery.echartsjs.com/editor.html?c=xgLtGmtVKw)，调整最前面的`realValue`的数值，刷新看下效果。
我认为这就是你需要的效果，数据可以用`data.value`进行联动

**Comment by fengyeheng** [comment]
> realValue

数字和

> > > 意思是要刻度颜色的变化，不要指针旋转，对吧？
> > 
> > 
> > 不不，我说的是刻度旋转哈，你对比俩张图片的刻度，不考虑颜色的。 @Nickszy
> 
> 我有些不懂你的意思。
> 建议您可以再看一下我之前给的那个用户[实例](https://gallery.echartsjs.com/editor.html?c=xgLtGmtVKw)，调整最前面的`realValue`的数值，刷新看下效果。
> 我认为这就是你需要的效果，数据可以用`data.value`进行联动

刻度数字10 20 30 40 ...是和圆垂直的哈，不关心颜色。

**Comment by DurianWyn** [comment]
hello  你这个问题怎么解决的？可否给个联系方式讨论一下
