### ISSUE TITLE
dataset performance for large data

### ISSUE THREAD

**Issue by fxxjdedd** [apache/echarts#11907]
### Version
4.5.0

### Reproduction link
[https://codepen.io/fxxjdedd/pen/OJPgvxZ?editors=1111](https://codepen.io/fxxjdedd/pen/OJPgvxZ?editors=1111)

### Steps to reproduce
分别使用`option`和`optionUsingDataset`这两个配置进行`setOption`

### What is expected?
不应该有非常大的性能差距

### What is actually happening?
在series超过一定数量（大概100个）后，dataset性能会越来越差，甚至会直接崩溃。

---
1. https://github.com/apache/incubator-echarts/issues/11806 会跟这条issue有一定的关系
2. 尝试在我的代码里手动把dataset转成original的数据形式，发现性能提升明显，猜测是echarts内部代码问题
3. 如果dataset的确有性能问题，应该在文档里加以描述

**Comment by 100pah** [comment]
The `genName` in `completeDimensions.js` needs to be optimized.

Potential optimization: 

+ Do not loop from 0.
+ Do not start while sentence if not necessary (not sure)
+ Use plain object rather than the hashMap (not sure)

**Comment by fxxjdedd** [comment]
any updates in 5.0.0?

**Comment by Rushan4eg** [comment]
I'm waiting for it as well
