### ISSUE TITLE
echarts3D地球的lines3D数组中设置的海拔高度没有用

### ISSUE THREAD

**Issue by QiekenaoOn** [apache/echarts#11913]
### Version
4.5.0

### Steps to reproduce
        var dom = document.getElementById("container");
        var myChart = echarts.init(dom);
        var app = {};
        option = null;

        myChart.setOption({
            backgroundColor: '#000',
            globe: {
                baseTexture: '../static/img/echarts_world.jpg',
                heightTexture: '../static/img/echarts_composite_4k.jpg',

                shading: 'lambert',

                light: {
                    ambient: {
                        intensity: 0.4
                    },
                    main: {
                        intensity: 0.4
                    }
                },

                viewControl: {
                    autoRotate: false
                }
            },
            series: {

                type: 'lines3D',

                coordinateSystem: 'globe',

                blendMode: 'lighter',

                lineStyle: {
                    width: 1,
                    color: '#fff',
                    opacity: 1
                },

                data: [
                    [
                        [145.391881, -6.081689,50],
                        [145.7887, -100.207083,50]
                    ],
                    [
                        [145.7887, -100.207083,50],
                        [-50.1995, 32.7552,50]
                    ],
                    [
                        [145.391881, -6.081689,50],
                        [-50.1995, 32.7552,50]
                    ]
                ]
            }
        });

        if (option && typeof option === "object") {
            myChart.setOption(option, true);
        }

### What is expected?
画的线应该距离地球有距离

### What is actually happening?
与海拔高度设为0没有任何区别

**Comment by Eminlin** [comment]
遇到相同问题啦 不知道解决了没有 v5.2.1
