### ISSUE TITLE
echarts  themeRiver  图表绘制报错

### ISSUE THREAD

**Issue by cysgbrlc** [apache/echarts#11948]
### Version
4.0.0

### Steps to reproduce

option = {

    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'line',
            lineStyle: {
                color: 'rgba(0,0,0,0.2)',
                width: 1,
                type: 'solid'
            }
        }
    },

    legend: {
        data: ['门店1', '门店', '门店3']
    },

    singleAxis: {
        top: 50,
        bottom: 50,
       
        type: 'time',
       
    },

    series: [
        {
            type: 'themeRiver',
            itemStyle: {
                emphasis: {
                    shadowBlur: 20,
                    shadowColor: 'rgba(0, 0, 0, 0.8)'
                }
            },
            data: [["2014/01/01", 4, "门店1"],
            ["2014/01/02", 5, "门店"],
            ["2014/01/02", 2, "门店1"],
            ["2014/01/03", 6, "门店3"],
            ["2014/01/04", 5, "门店1"],
            ["2014/01/05", 4, "门店"],
            ["2014/01/05", 2, "门店3"],
            ["2014/01/06", 2, "门店"],
            ["2014/01/07", 5, "门店"],
            ["2014/01/08", 5, "门店1"],
            ["2014/01/09", 4, "门店3"],
            ["2014/01/09", 2, "门店1"],
            ["2014/01/10", 2, "门店"],
            ["2014/01/10", 1, "门店1"],
            ["2014/01/11", 5, "门店1"],
            ["2014/01/11", 3, "门店"],
            ["2014/01/12", 3, "门店"],
            ["2014/01/12", 1, "门店1"],
            ["2014/01/13", 4, "门店3"],
            ["2014/01/13", 3, "门店"],
            ["2014/01/16", 1, "门店"],
            ["2014/01/17", 4, "门店3"],
            ["2014/01/17", 3, "门店"],
            ["2014/01/18", 2, "门店"],
            ["2014/01/21", 3, "门店1"],
            ["2014/01/21", 3, "门店"],
            ["2014/01/21", 1, "门店3"],
            ["2014/01/22", 2, "门店1"],
            ["2014/01/23", 2, "门店"],
            ["2014/01/25", 5, "门店"],
            ["2014/01/26", 9, "门店"],
            ["2014/01/27", 7, "门店1"],
            ["2014/01/30", 10, "门店"],
            ["2014/01/30", 3, "门店3"]]
        }
    ]
};

### What is expected?
期望出现主题河流图表

### What is actually happening?
报错，图表未出现，报错为：editor.js?_v_=1574101650733:1 TypeError: Cannot read property '1' of undefined

**Comment by Zaynex** [comment]
I think I find the reason, I want to slove it.
