### ISSUE TITLE
toolbox中datazoom缺少一些控制API

### ISSUE THREAD

**Issue by prismcore** [apache/echarts#11961]
### What problem does this feature solve?
现在我需要使用toolbox中datazoom的框选放大功能，但是需要放大展现更多的数据，如：精确到毫秒。可以通过setOption重新渲染解决这个问题，但是会先运行放大效果，再setOPtion渲染数据。需要一个类似外部datazoom的zoomLock或disabled这样的用法，阻止放大。

### What does the proposed API look like?
希望能完善toolbox的datazoom相关API,类似于外层的datazoom

**Comment by pissang** [comment]
> 但是会先运行放大效果，再setOPtion渲染数据

这个指的是什么？

**Comment by prismcore** [comment]
框选一个区域会先区域放大，像鼠标滚轮一样的效果，没办法取消这个效果

**Comment by Ovilia** [comment]
阻止放大是期望得到什么样的效果？

**Comment by wqzwh** [comment]
能不能增加一个每放大一次的一个回调函数，可以获取到当前放大后可是区域内点的数据
