### ISSUE TITLE
dispatchAction与graphRoam不生效

### ISSUE THREAD

**Issue by hzmming** [apache/echarts#11962]
### Version
4.6.0

### Steps to reproduce
```javascript
dispatchAction({
  "type": "graphRoam",
  "componentType":"series",
  "zoom":1.1,
  "originX":0,
  "originY":0
})
```

### What is expected?
关系图触发缩放

### What is actually happening?
一点反应都没有

---
测了下，geoRoam是生效的，那为什么graphRoam不行？跟了下源码，发现其不同之处
```javascript
// node_modules/echarts/lib/chart/graph/graphAction.js
var actionInfo = {
  type: 'graphRoam',
  event: 'graphRoam',
  update: 'none' // 这个'update'如果改成'updateTransform'就可以触发缩放，不是很懂整体的架构，是故意为之还是bug？？？
};
```

**Comment by RainStopsTonight** [comment]
解决了吗？我是找不到监听zoom变化的事件啊

**Comment by wangshaoqun** [comment]
解决了吗？我dispatchAction与geoRoam不生效

**Comment by ilovepumpkin** [comment]
我也碰到同样的问题，graphRoam不起作用。目前有什么workaround吗？

**Comment by Drowned-fish** [comment]
解决了吗，同样的问题

**Comment by wanghsinche** [comment]
same issue, and the dev team hasn't fixed it for a long time. After investigation, I used the the setoption to reset the zoom and viewport. It works exactly!

```js
        echartRef.setOption(
            {
                series: [
                    {
                        name: SERIES_NAME,
                        id: SERIES_NAME,
                        zoom: 1,
                        center: [
                            width / 2,
                            height / 2
                        ],
                    }
                ]
            }
        );

```

**Comment by hxada** [comment]
组件库中对于`graphRoam`和`treeRoam`的设置都是"none"，所以在用户自定义一些事件更新`zoom`后，不会全局更新，只会更改对应的值，所以需要再手动调用一次`setOption`。`geoRoam`也应该保持一致，所以这个不是 bug。
The settings for `graphRoam` and `treeRoam` in the component library are both "none", so after the user customizes some events to update `zoom`, it will not be updated globally, only the corresponding values ​​will be changed, so you need to call `setOption` manually again. `geoRoam` should also remain consistent, so this is not a bug.
```
myChart.dispatchAction({
  type: "treeRoam",
  componentType: "series",
  zoom: scale,
  originX: 0,
  originY: 0,
});
myChart.setOption(option);
```
