### ISSUE TITLE
boundaryGap: [percent, percent] is not forced strictly

### ISSUE THREAD

**Issue by maliayas** [apache/echarts#11964]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/9xr4ma21/](https://jsfiddle.net/9xr4ma21/)

### Steps to reproduce

When I define `boundaryGap` for x axis as `[percent, percent]` it's not applied exactly that way and the current algorithm adds further gaps only to arrive at the next tick values.

````js
option = {
    "xAxis": {
        "show": true,
        "type": "value",
        "scale": true,
        "boundaryGap": ["1%", "1%"],
    },
    "yAxis": {
        "show": true,
    },
    "series": [{
        "type": "bar",
        "data": [
            ["2019", "600"],
            ["2020", "600"],
            ["2032", "600"],
        ]
    }]
};
````

### What is expected?
In the JS fiddle I shared, I expect 2016 and 2034 values not to be on the x axis.

### What is actually happening?
Current algorithm adds more space than I defined only to add 2016 and 2034 to the x axis.

---

Note: I'm not sure if this is a bug but I'm opening this issue because I can't find a fix for the case.

Note: #5458 is slightly related to this issue.

**Comment by pissang** [comment]
Hi, the ticks will be calculated to be nice numbers after added `boundaryGap`. So the `boundaryGap` is not an accurate value by default. If you want them to be accurate.  Try:
```js
xAxis: {
  min: 'dataMin',
  max: 'dataMax'
}
```

I'm not sure what's your purpose of using `boundaryGap`. For the bar chart. I will suggest you use `category` type axis.

**Comment by maliayas** [comment]
Thanks for the comment. If you go to the JSFiddle in the OP and remove `boundaryGap` line, you get this overflow:

![Ekran görüntüsü (2020 01 07, 18_14_22)](https://user-images.githubusercontent.com/844008/71905612-8f1bf780-3179-11ea-981d-38238a1fcc0a.png)

`dataMin`and `dataMax` doesn't fix it. In order to fix it I wanted to use `boundaryGap`. Or maybe it should be fixed by the echarts algorithm? [Here is](https://github.com/apache/incubator-echarts/issues/11374#issuecomment-570085191) another discussion on the issue. My humble opinion is, if there is no conflicting reason, `boundaryGap` should be absolute. Or maybe there may be a config option to make it absolute?

> I will suggest you use category type axis.

Yes, bar charts are usually used with category axis, but surely there may be cases where it's better a value axis.
