### ISSUE TITLE
Line chart can't show the isloated symbol when series-line.showSymbol=false

### ISSUE THREAD

**Issue by WgCg** [apache/echarts#11979]
### What problem does this feature solve?
**ECharts option [ECharts配置项]:**

```javascript
option = {
    title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data: ['邮件营销']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name: '邮件营销',
            type: 'line',
            stack: '总量',
            data: [120, undefined, 50, undefined, 134, 90, 230, 210],
            showSymbol: false,
        },
    ]
};
```

**Expected behaviour [期望结果]:**

Please drawing the isolated symbol when series-line.showSymbol=false. In this case, hope drawing the Wednesday symbol as shown below:

![image](https://user-images.githubusercontent.com/20108513/71801554-3de70780-3096-11ea-8921-548fd76dea18.png)

But at present, it is blank unless you hover it, user experience is so terrible.

![image](https://user-images.githubusercontent.com/20108513/71801649-7edf1c00-3096-11ea-8246-70f5095077aa.png)

### What does the proposed API look like?
Hope drawing the isloate symbol by default or add config which likes series-line.showIsolatedSymbol: boolean

**Comment by ReWWeR** [comment]
Faced with the same problem. Any updates here?
