### ISSUE TITLE
OCHL - candlestick problem 

### ISSUE THREAD

**Issue by cutekevin7** [apache/echarts#11990]
### Version
4.6.0

### Steps to reproduce
问题/problem
In the financial sector, the candlestick chart is popular and widely used.
From the basic understanding about the candlestick or Kline-chart, most of people
recognise OHLC instead of your defined OCHL( quite weird :<)

O - open 开盘价
H - high 最高价 （'highest' is your missing translation. ）
L - low 最低价 （'lowest', likewise）
C- close 收盘价

问题来了，百度的E charts， 用的
OCHL，这个很不科学，不符合金融圈的习惯啊。
英文版还翻译成 highest， lowest（无力吐槽）

When people are getting used to OHLC-style,
We are forced to use OCHL by Baidu echarts.

would you please get it right? Can you check all the finance sector of yahoo, google, east money, Sina, Tecent, even Baidu for references?

Thanks

### What is expected?
When people are getting used to OHLC-style,
We are forced to use OCHL by Baidu echarts.

### What is actually happening?
When people are getting used to OHLC-style,
We are forced to use OCHL by Baidu echarts.

---
OHLC-style is more popular while the miss translation for 'High' against 'Highest' and 'Low' for 'Lowest'

**Comment by cutekevin7** [comment]
for instance, a 'W' pattern of candlestick chart (or 'M' type'), 'higher-high' or 'lower-low' happens.
so where would you like to go further after your 'highest' or 'lowest'?

**Comment by cutekevin7** [comment]
solution:
in the file of echarts.min.js, the order of OHLC array need to be reordered, it is quite easy.
0123 - > 0321, that's it. 
and in tooltip translation and display need to be fixed.

**Comment by yufeng04** [comment]
Thanks for your suggestion, we will deal with it as soon as possible.
