### ISSUE TITLE
Support for monthly time axis labels

### ISSUE THREAD

**Issue by maliayas** [apache/echarts#11997]
### What problem does this feature solve?
When I create a time axis which the values are on a monthly basis, echarts creates labels in Y-M-D format, which I'd expect Y-M format. See this JSFiddle: https://jsfiddle.net/up0hq4zL/

Data is like:

````json
"data": [
    ["2019-01", "400"],
    ["2019-02", "500"],
    ["2019-05", "600"],
]
````

And the outcome is:

![Ekran görüntüsü (2020 01 08, 16_29_32) - Kopya](https://user-images.githubusercontent.com/844008/71982114-f21e9480-3234-11ea-8dd7-6a9955309065.png)

And this is the proposed look:

![Ekran görüntüsü (2020 01 08, 16_29_32)](https://user-images.githubusercontent.com/844008/71982117-f6e34880-3234-11ea-8632-105a202aa064.png)

Normally I could make this happen using the `xAxis.axisLabel.formatter` function; however the timestamps it receives don't correspond to the first day of each month. For example it receives a timestamp for "2019-03-25" which I wouldn't format as YEAR-MONTH because that would mislocate March tick on the x axis because you'd think a tick would mark the beginning of the month.

**Comment by pissang** [comment]
Hi, @maliayas 

I'd suggest using `category` type axis. And fill the month missing data with value '-'

**Comment by pissang** [comment]
Hi, @maliayas 

I'd suggest using `category` type axis. And fill the month missing data with value '-'

**Comment by maliayas** [comment]
I'll think about that as a workaround, thanks. You may prefer to keep the issue open for future work.

**Comment by xiaoyvr** [comment]
Month is not a fixed interval. using `category` will not work if we need an accurate axis. 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1032636/96278477-292b8e80-0f9b-11eb-8813-4cfd6f499fa2.png">

I'd suggest to add this kind of support or provide a way to customize the split behavior.

**Comment by mtuzinskiy** [comment]
Hi, I agree to @xiaoyvr , this functionality is quite commonly required

**Comment by pissang** [comment]
Hi, we've refactored our time axis in 5.0. We will keep this issue open, please let us know if there are other problems.

https://jsfiddle.net/8tkhcvy4/
