### ISSUE TITLE
Display area below isolated values in line charts

### ISSUE THREAD

**Issue by VictorCazanave** [apache/echarts#12007]
### What problem does this feature solve?
In my current project we use several line charts with `areaStyle` and sometimes there are isolated values (`[..., null, 123, null, ...]`). To make them visible we use `symbol` and it works well.

However we think these isolated values may be hard to see and are not consistent with the design.

![Screen Shot 2020-01-09 at 14 40 27](https://user-images.githubusercontent.com/8233304/72044334-80a31c80-32ee-11ea-8f95-f2bd0d8a5381.png)

We already increased `symbolSize` to make them more visible, but we still would like to show the area below.

Here is what our UX/UI designer suggested:
![image_2020_01_09T03_10_56_836Z](https://user-images.githubusercontent.com/8233304/72044223-30c45580-32ee-11ea-959d-652b1bc377e2.png)

Would it be possible to implement this feature?

### What does the proposed API look like?
I'm not sure what the best API would be for this feature:
- a new option `symbolAreaStyle: {...}`
- a new option in `areaStyle: { alwaysShow: true }`
- a new option in `itemStyle: { showArea: true }`
- ...

**Comment by pissang** [comment]
Hi @VictorCazanave 

Perhaps you can try to filter out data with `null` siblings and use a `bar` series to draw it. for example

```js
series: [{
  type: 'bar'
  data: data.filter((val, idx) => {
      return idx > 0 && idx < data.length - 1 && data[idx - 1] == null && data[idx + 1] == null
            ? val  // Display bar if value has null siblings
            : '-'    // Not display bar for other values
  })
]}
```

**Comment by VictorCazanave** [comment]
Thanks @pissang for this clever workaround! 
 
However there is still an issue because I use the `dataZoom` feature and the series' type doesn't change after zooming.

For example:
* Initial state:
![Screen Shot 2020-01-14 at 11 09 06](https://user-images.githubusercontent.com/8233304/72311241-f9bfbc80-36be-11ea-9901-cb51454a8d63.png)

* Zooming to select only isolated values:
![zooming](https://user-images.githubusercontent.com/8233304/72311323-312e6900-36bf-11ea-9343-39bcc8a24f41.png)

* Expect only bars but still show line's symbol:
![Screen Shot 2020-01-14 at 11 10 38](https://user-images.githubusercontent.com/8233304/72311376-6a66d900-36bf-11ea-8551-12270336c644.png)

Is there a way to fix this issue?

**Comment by Ovilia** [comment]
@VictorCazanave Can you provide a simple demo here? https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by VictorCazanave** [comment]
Yes of course! https://jsfiddle.net/po0zraun/42/

I guess it may be possible to re-calculate the series data listening to the `datazoom` event 🤔 
If you think it's a good way, I can try it when I have time.

**Comment by pissang** [comment]
Hi @VictorCazanave . Sorry for the late reply.

I can't reproduce the issue from your link. 

I guess it's caused by the  `clip` option of bar series. You can try setting it false.

```js
{
  type: 'bar',
  clip: false
}
```

**Comment by VictorCazanave** [comment]
Thanks for your feedback @pissang !

I tried the `clip` option but it didn't fix my issue. Perhaps I didn't explain it very clearly. 

In [my example](https://jsfiddle.net/po0zraun/42/), after zooming like that:
![zoom](https://user-images.githubusercontent.com/8233304/73926525-bac20700-490a-11ea-903e-dc991708fb39.png)

There are 2 isolated values, but the 1st one is still displayed as a point of the line series:
![Screen Shot 2020-02-06 at 17 59 37](https://user-images.githubusercontent.com/8233304/73926623-e04f1080-490a-11ea-9f8d-bd0aee3dab70.png)

I would like the 1st value (which became isolated after zooming) to be displayed as a bar like the 2nd value (which was already isolated).
