### ISSUE TITLE
Fetch data asynchronously on dataZoom changed

### ISSUE THREAD

**Issue by oychao** [apache/echarts#12014]
### What problem does this feature solve?
When using dataZoom we have to fetch all data from server side which is a huge amount normally. It's preferred to fetch what is needed only for performance and speed.

Hope there would be an API that updates the `series` option asynchronously.

### What does the proposed API look like?
```javascript
{
  // ...
  dataZoom: {
    independent: true; // which means dataZoom will not update the graph automatically
    axis: object; // determine the zoom range like xAxis or yAxis
    onRangeChange(from, to) {
      // update the chart or do sth. else
    }
  }
}
```

**Comment by sarimarton** [comment]
Why is this stale??? Such a basic feature.
