### ISSUE TITLE
Lags when using timeline with many (> 100) items with SVG rendering

### ISSUE THREAD

**Issue by justynabukiel** [apache/echarts#12023]
### What problem does this feature solve?
When **renderer** is set to **svg** and there are many items in timeline, changing current timeline index lags. There's a visible delay, propably because of many symbols (<path> elements) are rendered in DOM.

My usecase is a chart displaying values per weeks. One timeline item is a week and I have few hundereds of weeks. However there are weeks in which I don't have any data and I don't want to display them on timeline. Currentlu there's no possibility not to display them. The only walkaround that I've found is to set opacity = 0 for those items. But that doesn't solve the performance issue, because those items are still rendered in DOM as <path> elements, which causes lagging.

### What does the proposed API look like?
In options:

    timeline: {
        data: [
            {
                symbol: null
            }
        ]
    }

This setting could omit rendering symbol on timeline in function _renderAxisTick() in timeline component.

**Comment by Ovilia** [comment]
@justynabukiel What are you using timeline for? Because it's not supposed to have many data items.

**Comment by justynabukiel** [comment]
First of all, thanks for answering my ticket.

I have data (to be specific: user's statistics) from several years grouped by different time ranges: by years, months and weeks. Each time I change grouping parameter, I redraw the chart.

For years and months it works well, because there are not so many items on the timeline. Here's an exmaple of grouping by years.

![image](https://user-images.githubusercontent.com/5517822/72260261-bc055a00-3612-11ea-8bd0-554eb92e2bb0.png)

But when I switch into grouping by weeks, I have 52 * numbers_of_years items. And this case causes performance issue. On the timeline below the "empty" weeks have symbol with opacity = 0, only those with any data are visible. But, as I've mentioned previously, all items are rendered in DOM, even if they are not visible.

![image](https://user-images.githubusercontent.com/5517822/72260406-143c5c00-3613-11ea-8b79-750ddf3cbd95.png)

**Comment by Ovilia** [comment]
I think this makes sense. Marked as a new feature.

**Comment by alex2wong** [comment]
@justynabukiel  After reading some of the doc here https://echarts.apache.org/en/option.html#timeline.itemStyle.opacity
and https://echarts.apache.org/en/option.html#timeline.data

I believe when set timeline.itemStyle.opacity = 0 would not trigger render of this specific item, since doc said: `and the component will not be drawn when set to 0.`

btw, I suppose the performance bottleneck is SVG render, what about if you try Canvas renderer to see if there still exists lags.

And you can try set timeline.symbol = 'none' or timeline.symbolSize = 0, too. I guess symbol = 'none' would not render in DOM for sure ~

**Comment by justynabukiel** [comment]
> I believe when set timeline.itemStyle.opacity = 0 would not trigger render of this specific item, since doc said: `and the component will not be drawn when set to 0.`

When opacity = 0, 'path' element is still being rendered, I've checked it.

> btw, I suppose the performance bottleneck is SVG render, what about if you try Canvas renderer to see if there still exists lags.

You are right, the problem is in SVG. I was using Canvas at first and it worked well, but I've decided to change it to SVG, because it's more sharp and looks better. I've also bumped into some flickering issues with Canvas (not relevant here).

> And you can try set timeline.symbol = 'none' or timeline.symbolSize = 0, too. I guess symbol = 'none' would not render in DOM for sure ~

I've tried it and checked it once again now. Both these settings, even combined result in creating 'path' element in DOM - just not visible.

**Comment by Ovilia** [comment]
I think the doc probably means it's not visible rather than not rendered technically.

**Comment by alex2wong** [comment]
Sure，I've checked in demo code. The path elements for SVG are in DOM tree indeed, which introduce some performance issue. I am not sure how much performance we can promote by not render path for 'none' symbol or symbol with 0 opacity.
Maybe there are some reason we keep the paths as placeholder? @Ovilia

**Comment by Ovilia** [comment]
@alex2wong I'm not sure what you mean by *placeholder*.
I think one way to fix this is to not add the element to the container if it's none. This is not an SVG problem because Canvas should also not render it.
