### ISSUE TITLE
Error intervals can't be aligened on Bar Chart for Grouped Data

### ISSUE THREAD

**Issue by kuzmenkov111** [apache/echarts#12020]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/qm75bLcd/](https://jsfiddle.net/qm75bLcd/)

### Steps to reproduce
There is a wonderful example on The Echarts website (https://echarts.apache.org/examples/en/editor.html?c=custom-error-bar) - Error Bar Chart without grouping. But modification this code (see below) for plotting Error bar chart on grouped data (two series bar chart) leads to unexpected behavior: all custom additional (error interval) series are aligned on the center of the X-axis category, but not on the center of the appropriate bar column (https://jsfiddle.net/qm75bLcd/).

### What is expected?
On two (or N) series bar charts every additional custom (error interval) series should be aligned on the center of the appropriate bar column.

### What is actually happening?
All custom additional (error interval) series are aligned on the center of the X-axis category, but not on the center of the appropriate bar column.

**Comment by helgasoft** [comment]
I think this is fixed for library [echarts4r](https://github.com/JohnCoene/echarts4r), see [code here](https://github.com/JohnCoene/echarts4r/blob/master/inst/htmlwidgets/lib/echarts-4.8.0/custom/renderers.js).
It's not a pure JS library so _sessionStorage_ had to be used for parameter transfer.
Three additional parameters were used:
- total count of all series (most important)
- lastly defined barGap
- lastly defined barCategoryGap 

Works pretty good so far.  There is also a PR pending, which adds a _hwidth_ parameter for customizing error bar's width.
[see image](https://user-images.githubusercontent.com/13038071/98910386-f1b7e100-2477-11eb-836c-942a6d2d05d6.png)

**Comment by kuzmenkov111** [comment]
Thanks!
