### ISSUE TITLE
饼图设置透明背景后边框重叠

### ISSUE THREAD

**Issue by Mrzhangqc** [apache/echarts#12054]
### Version
4.6.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x_XU88c8Q&v=1](https://gallery.echartsjs.com/editor.html?c=x_XU88c8Q&v=1)

### Steps to reproduce
参考链接：https://gallery.echartsjs.com/editor.html?c=x_XU88c8Q&v=1

### What is expected?
设置透明背景后，边框重叠

### What is actually happening?
设置透明背景后，边框不要重叠

**Comment by Ovilia** [comment]
这个需求是成立的，但是现在的技术方案不太能简单地实现这一点，后期尽量支持一下

**Comment by Mrzhangqc** [comment]
_Thanks，关心进度！_
