### ISSUE TITLE
legend scroll，当单个图例legend展示不下的时候，只展示部分

### ISSUE THREAD

**Issue by yanshuai** [apache/echarts#12078]
### What problem does this feature solve?
legend scroll，当单个图例legend展示不下的时候，不期望只展示部分文字，而是期望全部文字都不展示

### What does the proposed API look like?
{
legend: {
  truncation: false
}
}

**Comment by yanshuai** [comment]
![image](https://user-images.githubusercontent.com/745813/72607894-73280b00-395c-11ea-8dfc-cd29c5f89d31.png)

**Comment by Ovilia** [comment]
目前做不到
