### ISSUE TITLE
ScatterGL doesn't work with with datazoom.filterMode = 'none' 

### ISSUE THREAD

**Issue by trannamquan** [apache/echarts#12097]
### Version
4.6.0

### Steps to reproduce
1. Draw a scatter chart using Cartesian 2D coordinates
2. Set dataZoom of both axes is inside, filterMode: 'none'
3. Draw a scatter chart using series "scatterGL"

### What is expected?
Zooming behavior should be the same with drawing scatter using normal "scatter" series type.

### What is actually happening?
Strange behavior that when zooming, points go outside the axes.

**Comment by trannamquan** [comment]
Any update on this?

**Comment by ngoc308** [comment]
@Ovilia , @pissang Could you comment on this? I also deal with the issue.
