### ISSUE TITLE
getDataURL 不应该依赖于动画，并且提供参数设置图片大小

### ISSUE THREAD

**Issue by yaoguoba** [apache/echarts#12094]
### What problem does this feature solve?
1，当图标在隐藏tab下，图片宽度存在问题，虽然现在提供了resize方法设置图片大小，但是在导出图片时，我们并不想改变页面显示的图表大小，保留100%。
2，如果打开动画，隐藏时导出图片会有问题。

能够提供参数来设置图片大小而不影响页面显示，导出时单独渲染图片而不是依赖于页面中的图表？
可以设置开关来提高性能，当图标非隐藏时，可以不单独渲染。

### What does the proposed API look like?
echartsInstance. getDataURL(opts: {
    // 导出的格式，可选 png, jpeg
    type?: string,
    // 导出的图片分辨率比例，默认为 1。
    pixelRatio?: number,
    // 导出的图片背景色，默认使用 option 里的 backgroundColor
    backgroundColor?: string,
    // 忽略组件的列表，例如要忽略 toolbox 就是 ['toolbox']
    excludeComponents?: Array.<string>,

    // 宽度
    width?: number | string,
    // 高度
    height?: number | string,
    // 是否重新渲染
    reRenderFlag?: boolean
}) => string

**Comment by deqingli** [comment]
你好，没太明白你的需求，能详细描述下需要这样做的背景么？

**Comment by yaoguoba** [comment]
> 你好，没太明白你的需求，能详细描述下需要这样做的背景么？

不是背景，我的页面上有个导出按钮，导出数据的同时要把图表也导出到文件中。
目前我的做法是把图片已Base64形式传回API端，然后生成到文件中。

但是，页面上是分数据视图和图表视图切换的，当数据视图时，也可以执行导出。
此时，图表处于Display: none状态
1、EChart获取不到宽度，所以默认设置为100px。
     虽然可以通过resize设置图片大小，但是同时把页面上的图表尺寸改了，我并不想修改。
     所以希望能在getDataURL时指定图片大小，跟页面上的图表大小无关。
2、动画未执行，图表内容挤在一起

**Comment by 100pah** [comment]
“在图表未能成功渲染时就导出图片” ，并未想到比较简单的办法。
