### ISSUE TITLE
增加子节点闭合功能

### ISSUE THREAD

**Issue by calyearn** [apache/echarts#12095]
### What problem does this feature solve?
在实际制作tree图的过程中，经常需要两个父节点共用一个子节点的情况，请问可以实现该功能吗？
如下方示例，此时父节点为data#，两个分支为data1和data2，data3为最终子节点，与data1和data2均相连。尾端是闭合的

### What does the proposed API look like?
"name": "data#",
"id":#
"children": [
        {"name": "data1",
          "id":00,
           "children": [
             {"name":"data3" ,"value3":value3 ,"id":03} 
]},
        {"name": "data2",
          "id":01,
          "children": [
             {"name":"data3" ,"value3":value3,"id":03} 
}]

**Comment by Ovilia** [comment]
这种数据结构就不是「树」了，所以按我的理解可能不会支持。
