### ISSUE TITLE
Let yAxis. type support custom function.

### ISSUE THREAD

**Issue by ahuigo** [apache/echarts#12099]
### What problem does this feature solve?

I found that [`yAxis. type` only supports : `value`, `category`, `time`, `log` ](https://www.echartsjs.com/en/option.html#yAxis.type).

I have many lines (different level) to show, Hope it supports custom function.

### What does the proposed API look like?
For example, I want to draw 3 line(**They have different zoom level: 5 times, 20 time and log** )

            yAxis: [
                {
                    type:(value)=>(value*5), //5 level
                },
                {
                    type:(value)=>(value*20), //20 level
                },
                {
                    type:"log", //log level
                },
            ],

**Comment by Ovilia** [comment]
What kind of custom function do you need? In your given example, the type should probably be `log`.

**Comment by ahuigo** [comment]
@Ovilia The type `log` is not improper for all my cases, I need no only `log(value)`, but also `5*value`, `20*value`, and `custom_func(value)` .
