### ISSUE TITLE
Time axis monthly chart issue with axis labels

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#12106]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/6nqomkav/](https://jsfiddle.net/6nqomkav/)

### Steps to reproduce
I have monthly date which need to be plotted in time axis line chart.(as in sample provided)
Our line chart points are not coincide with x-axis labels. Axis labels are getting shown automatically 
Is it possible to specify that axis label should be shown for first day of month only. I tried with available options like maxInterval, splitNumber but because of different number of days in different months still we are getting random axis labels.

### What is expected?
We are expecting to have axis labels for every month or first day of every month

### What is actually happening?
Axis labels are random

**Comment by yanheSu** [comment]
Maybe you can try to specifying `xAxis.type` as `time` instead of `category`, and `xAxis.axisLabel.interval = 0`.
[Example](https://jsfiddle.net/uL26jtaq/)

**Comment by dileepyelleti** [comment]
@yanheSu 
We also have external filters like 3m, 6m, 1y, YTD to zoom accordingly. If we use time axis then we can give startValue date according to filter. If we use category axis then we need to iterate through data to find what is next available point and give start value accordingly. Is there any easier way (That is my main purpose of using time axis than category).

**Comment by Ovilia** [comment]
We are going to enhance the axis label for the next major release, which we have not yet started.
