### ISSUE TITLE
x-axis label disappears for 'time' series

### ISSUE THREAD

**Issue by dereksmith-debug** [apache/echarts#12129]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/mvau8t5L/4/](https://jsfiddle.net/mvau8t5L/4/)

### Steps to reproduce
Use legend to show/hide the series. In top panel the x-axis labels disappear when hidden. In bottom panel the x-axis labels persists.

### What is expected?
Consistency between 'time' and 'category' series types.

### What is actually happening?
The x-axis labels disappear when a 'time' series is hidden, but not for 'category' series.

**Comment by Ovilia** [comment]
I'm afraid this is not a bug. The second series doesn't own the category data, so when hidden, the axis label is still there. While for the first series, value/time/log axis is updated on series change.

**Comment by Ovilia** [comment]
If you want the axis to be empty for the second series, you can listen to [legendunselected](https://echarts.apache.org/en/api.html#events.legendunselected) event and call `setOption` to set the xAxis to be empty.

**Comment by dereksmith-debug** [comment]
Thank you. I expected that the labels would not be removed in either case.
