### ISSUE TITLE
Log axis base^exp ticks

### ISSUE THREAD

**Issue by zifix** [apache/echarts#12124]
### What problem does this feature solve?
I'm rendering a chart with pretty high values on a log2 axis. My top tick is "1,099,511,627,776". It would make a lot more sense to the reader to see 2^40.
Sure, we can run a callback as formatter, but I feel there should be an easier way. At the very least a suitable example would have helped me cut down on my research time.

### What does the proposed API look like?
```json
{
  "axisLabel": {
    "formatter": "{base}^{exp}" 
  }
}
```
maybe?

**Comment by BugZappr** [comment]
Bump.  We could use control over the tick interval on log axis.  There is already at least one of the same request that has gone stale.
