### ISSUE TITLE
log 轴堆叠问题

### ISSUE THREAD

**Issue by fanyongfeng** [apache/echarts#12131]
### Version
4.6.0

### Steps to reproduce
对数轴 柱状图堆叠，高度计算是不是有bug ？

### What is expected?
每个色块值虽然是2 ，但是高度应该是不一样的

### What is actually happening?
现在高度居然是一样的

<img width="1680" alt="ak85ijOz7n" src="https://user-images.githubusercontent.com/15905834/73832797-cac2e380-4843-11ea-9dec-8ce4c905683d.png">

**Comment by fanyongfeng** [comment]
https://gallery.echartsjs.com/editor.html 这个页面里面不支持 log 轴么，写进去log 就什么都不支持了

**Comment by Ovilia** [comment]
@fanyongfeng 请在这里报存一下 https://gallery.echartsjs.com/editor.html 不然我们手动打代码太累了

**Comment by fanyongfeng** [comment]
@Ovilia https://gallery.echartsjs.com/editor.html?c=xxt-evjLw&v=4 这样子

**Comment by fanyongfeng** [comment]
https://gallery.echartsjs.com/editor.html 这个页面里面 我写 对数轴 不会显示， 但是同样子的配置，在官网例子上修改是可以展示的

**Comment by Ovilia** [comment]
@fanyongfeng 好的，了解了

**Comment by fanyongfeng** [comment]
@Ovilia 小姐姐  这个有什么发现么？是echarts 问题，还是我配置有问题呐？？

**Comment by Ovilia** [comment]
@fanyongfeng 这个应该是 bug，只是还没排上期
