### ISSUE TITLE
an error in the tutorial document of VisualMap/inRange

### ISSUE THREAD

**Issue by Nfboys** [apache/echarts#12132]
### Version
4.6.0

### Reproduction link
[https://echarts.apache.org/en/option.html#visualMap-continuous.inRange](https://echarts.apache.org/en/option.html#visualMap-continuous.inRange)

### Steps to reproduce
The document said : "
For instance, [visualMap.min, visualMap.max] is set to be [0, 100], and there is series.data: [50, 10, 100]. We intend to map them to an opacity range [0.4, 1], by which the size of value can be demostrated by the transparency of graphical elements. visualMap component will then linear calculate them and get opacity values [0.7, 0.44, 1], cooresponding to each dataValue."

### What is expected?
I think the results of opacity should be  [0.7, 0.46, 1]

### What is actually happening?
[0.7, 0.44, 1]

---
Maybe I were wrong ,but I still think I was right. I wonder the rules of Linear Mapping as well.  Thank you

**Comment by pissang** [comment]
Yes, I believe your calculation is right. It's a mistake in the documentation. Would you mind making a pull request to fix it?

The doc repo is in the https://github.com/apache/incubator-echarts-doc
