### ISSUE TITLE
Map can not be dragged into the view once roamed away after v4.6.0

### ISSUE THREAD

**Issue by plrthink** [apache/echarts#12146]
### Version
4.6.0

### Reproduction link
[https://codesandbox.io/s/cocky-gould-xsyd8?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/cocky-gould-xsyd8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Drag the map outside its container and release the mouse, then there's no way to bring it back.

### What is expected?
The map would be constrained in its box even the cursor is beyond the container.

### What is actually happening?
Now the map is following the cursor and once the user released the mouse, it can not be brought back.

---
I think it's only happened after 4.6.0 since this merged PR https://github.com/apache/incubator-echarts/pull/11710.

**Comment by plrthink** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2429369/74447794-e3bb3c80-4eb4-11ea-8588-a9655b48929a.gif)

**Comment by Jupiterice** [comment]
这个问题解决了么？有没有什么方法可以监控地图被移出画布？

**Comment by plrthink** [comment]
@Jupiterice 没有，我们后面是将引用的 echarts 的版本回退了。

**Comment by plrthink** [comment]
@Jupiterice 不好意思，刚才的回答有些歧义。准确来说是，我们不确定 echars 是否已经更新解决了，我们这边是回退了 echarts 的版本。

**Comment by KrzysztofMadejski** [comment]
Working on it..

`RoamController:144` (v 4.9.0)  `this.pointerChecker(e, x, y)` returns null for click outside of very close to map.

**Comment by KrzysztofMadejski** [comment]
Sent PR for it.
