### ISSUE TITLE
xAxis>axisLabel>interval为函数的时候showMaxLabel、showMinLabel参数无效

### ISSUE THREAD

**Issue by anan-lee** [apache/echarts#12142]
### Version
4.6.0

### Steps to reproduce
xAxis>axisLabel>interval为函数的时候showMaxLabel、showMinLabel参数无效

### What is expected?
interval为函数的时候怎么显示最大最小值

### What is actually happening?
不能显示最大最小值

**Comment by zevero** [comment]
I have the same issue. Interval is beeing ignored
https://gallery.echartsjs.com/editor.html?c=xm2McWXnd&v=1

**Comment by Ovilia** [comment]
@zevero Thanks for reporting.

**Comment by quillblue** [comment]
@zevero According to document, `interval` on axis only provided for category.
For @anan-lee 's case I can reproduce in [https://gallery.echartsjs.com/editor.html?c=xU-XwwOWbA](https://gallery.echartsjs.com/editor.html?c=xU-XwwOWbA) , is trying to investigate the problem.
