### ISSUE TITLE
漏斗图，可能是个BUG，如果SORT设置为none，数据为0的图居然比数据为20的还要大

### ISSUE THREAD

**Issue by todyhuang** [apache/echarts#12157]
### Version
4.6.0

### Steps to reproduce
option = {
    title: {
        text: '漏斗图',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            dataView: {readOnly: false},
            restore: {},
            saveAsImage: {}
        }
    },
    legend: {
        data: ['展现','点击','访问','咨询','订单']
    },
    series: [
        {
            name: '预期',
            type: 'funnel',
            left: '10%',
            width: '80%',
            label: {
                formatter: '{b}预期'
            },
            sort:'none',
            labelLine: {
                show: false
            },
            itemStyle: {
                opacity: 0.7
            },
            emphasis: {
                label: {
                    position: 'inside',
                    formatter: '{b}预期: {c}%'
                }
            },
            data: [
                {value: 60, name: '访问'},
                {value: 0, name: '咨询'},
                {value: 20, name: '订单'},
                {value: 0, name: '点击'},
                {value: 100, name: '展现'}
            ]
        }
    ]
};

### What is expected?
数据为0的图居然比数据为20的要写，应该就是一根线

### What is actually happening?
数据为0的图居然比数据为20的还要大

**Comment by Ovilia** [comment]
结果上看没有问题，可能是理解有误
<img width="817" alt="屏幕快照 2020-02-18 11 17 20" src="https://user-images.githubusercontent.com/779050/74701134-be298c80-5240-11ea-8b35-cc9b4450000e.png">

**Comment by todyhuang** [comment]
嗯，从线来看是这样的，我也参考了其他的，比如阿里的G2，也是这样的。  但是看Hight CHart漏斗图，如果没有值，为0的话，就不显示面积。直接一根线在那
![image](https://user-images.githubusercontent.com/10398315/74701453-b1596880-5241-11ea-86bd-d97f1edfa334.png)

请问后续有考虑，1 这样模式么，还有2可以自己控制改变漏斗脖子大小
通过 neckWith 和 neckneckHeight 可以指定漏斗脖子的宽度和高度，其值为百分数，表示占总宽度或总高度百分比

**Comment by Ovilia** [comment]
我觉得是合理的，但是这个需求比较小众。如果确实有这方面需求，比较快速的解决方法是尝试调试代码，然后给我们提 PR~

**Comment by todyhuang** [comment]
好的，谢谢。我先看看代码怎么弄。
