### ISSUE TITLE
tooltip能否设置position  z-index值?

### ISSUE THREAD

**Issue by qqfei1858** [apache/echarts#12153]
### What problem does this feature solve?
目前项目有许多Modal弹框,导致tooltip会盖在Modal弹框层上!

### What does the proposed API look like?
tooltip可以设置position的z-index值

**Comment by plainheart** [comment]
可以用 [extraCssText](https://echarts.apache.org/option.html#tooltip.extraCssText) 追加行内样式或者自定义 [className](https://echarts.apache.org/option.html#tooltip.className) 覆盖默认的 `z-index`。
