### ISSUE TITLE
How to avoid wiggling animation for real-time time series charts?

### ISSUE THREAD

**Issue by klausb** [apache/echarts#12167]
### Version
4.4.0

### Steps to reproduce
In our use of echarts I'm facing the behavior shown on this page: https://bost.ocks.org/mike/path/.
In older posts the solution was to use addData, but this does no longer exist. We use setOption.

We use the series.data array, with tuples of x/y values.

Is there a suggested way of changing the series data to avoid the wiggling effect?

### What is expected?
More a shifting of the time series to the left

### What is actually happening?
Animation like in https://bost.ocks.org/mike/path/.

**Comment by Serious-ChrisLopez** [comment]
For me to fix that issue I had to make sure that the data I pushed had an object with { name: curTime, value: [someValue] }. 

For example:
` let dataTimestamp = 1582058229; // unix/epoch time
  let dataValue = Math.random() * 1000; // number between 0 and 1000
  chartData.push({
    name: new Date().toString(),
    value: [dataTimestamp, dataValue]
  });
  Chart.setOption({
    series: chartData
  });`

However, I am not sure why it works this way. Hopefully, someone can answer that for me.

**Comment by klausb** [comment]
Maybe is it because you are reusing the object on each update. I wonder if that method still works, if you fill up the series with new objects, but the values are the same

**Comment by klausb** [comment]
@Serious-ChrisLopez can you provide a full example?
I tried modifying this https://echarts.apache.org/examples/en/editor.html?c=doc-example/tutorial-dynamic-data, but failed. Even this example shows the wiggling effect

**Comment by Serious-ChrisLopez** [comment]
This example I made should show you the issue: https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

________________________________

**Comment by Serious-ChrisLopez** [comment]
Here’s a video I made with from the following example:
Demo -  https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2
Video - https://www.loom.com/share/fa5396c0a2e74c2f99fdcb9160ed27c3

I think its strange that the points are correct but the lines are drawn incorrectly. Scrubbing the timeline which forces a redraw seems to fix the line issue. Is it something I am doing wrong? The more elements I push the more the lines seem to get out of place. Seems like an issue when drawing the chart/frame. I also tried deep cloning but that didn’t work

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

From: Chris Lopez<mailto:chris.lopez@seriousintegrated.com>
Sent: Thursday, February 20, 2020 11:05 AM
To: apache/incubator-echarts<mailto:reply@reply.github.com>; apache/incubator-echarts<mailto:incubator-echarts@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/incubator-echarts] How to avoid wiggling animation for real-time time series charts? (#12167)

This example I made should show you the issue: https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

**Comment by Serious-ChrisLopez** [comment]
Here is another example but with deep cloning the data object first: https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=4

I have it so that every other update I push two times rather than just once. When pushing once, the data is drawn correctly, when pushing twice it’s drawn incorrectly.

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

From: Chris Lopez<mailto:chris.lopez@seriousintegrated.com>
Sent: Thursday, February 20, 2020 3:20 PM
To: apache/incubator-echarts<mailto:reply@reply.github.com>; apache/incubator-echarts<mailto:incubator-echarts@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/incubator-echarts] How to avoid wiggling animation for real-time time series charts? (#12167)

Here’s a video I made with from the following example:
Demo -  https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2
Video - https://www.loom.com/share/fa5396c0a2e74c2f99fdcb9160ed27c3

I think its strange that the points are correct but the lines are drawn incorrectly. Scrubbing the timeline which forces a redraw seems to fix the line issue. Is it something I am doing wrong? The more elements I push the more the lines seem to get out of place. Seems like an issue when drawing the chart/frame. I also tried deep cloning but that didn’t work

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

From: Chris Lopez<mailto:chris.lopez@seriousintegrated.com>
Sent: Thursday, February 20, 2020 11:05 AM
To: apache/incubator-echarts<mailto:reply@reply.github.com>; apache/incubator-echarts<mailto:incubator-echarts@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [apache/incubator-echarts] How to avoid wiggling animation for real-time time series charts? (#12167)

This example I made should show you the issue: https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2

Chris Lopez
Serious Integrated
chris.lopez@seriousintegrated.com<mailto:chris.lopez@seriousintegrated.com>

**Comment by klausb** [comment]
@Ovilia Please check this example: https://echarts.apache.org/examples/en/editor.html?c=doc-example/tutorial-dynamic-data
Wait about 10 seconds and you see that the chart is no longer just shifting left but also show the strage animation effect of the curve

**Comment by klausb** [comment]
@Serious-ChrisLopez are we referring to the same issue? In your example I see issues at the left end of the chart, but I cannot see the strange animations when the graph shifts left.

**Comment by Serious-ChrisLopez** [comment]
> @Serious-ChrisLopez are we referring to the same issue? In your example I see issues at the left end of the chart, but I cannot see the strange animations when the graph shifts left.

@klausb I apologize, I was responding through my emails and didn't realize my messages were being posted to this ticket. I've been talking about my issue for ticket #12164  [(https://github.com/apache/incubator-echarts/issues/12164)](https://github.com/apache/incubator-echarts/issues/12164)

**Comment by klausb** [comment]
@Ovilia , demo is available. Please check and remove the missing-demo flag. Thanks!

**Comment by Ovilia** [comment]
@klausb What do you mean by "the strage animation effect of the curve"? Is it the left-most data?

**Comment by klausb** [comment]
@Ovilia , please ignore the examples from @Serious-ChrisLopez. Just look at this:
https://echarts.apache.org/examples/en/editor.html?c=doc-example/tutorial-dynamic-data
With strange effect I mean, that the graph is not just shifting left, it also shows animation of the line itself, like in this example: https://bost.ocks.org/mike/path/

**Comment by Serious-ChrisLopez** [comment]
@klausb You should post an example with your code using one of these links: 
> https://jsfiddle.net/ovilia/n6xc4df3/ or https://gallery.echartsjs.com/editor.html

I can't see the wiggling effect in your example on my browser. What browser are you using? It's working for me on Chrome and Firefox.

**Comment by Ovilia** [comment]
I can't see the wiggling effect either. @klausb Maybe you should record a gif?

**Comment by klausb** [comment]
@Ovilia please try this: https://gallery.echartsjs.com/editor.html?c=xxM_2zmYh&v=1
Wait a few seconds and see the effect

**Comment by klausb** [comment]
I'm adding a GIF movie that shows nicely how the chart changes from a left-shift animation to a different animation, where the values seem to be animated.
![wiggle2](https://user-images.githubusercontent.com/209846/75552429-930c1d80-5a36-11ea-8e11-9d9c9b06cc68.gif)

**Comment by Serious-ChrisLopez** [comment]
@klausb I'm wondering if it's a performance issue or a browser setting on your computer. The example you posted also works fine for me. I would try two things: 

1. Increasing the setInterval to a higher timeout
2. I would try setting animation to false and see if anything changes
<pre>    
series: [
        {
            name:'成交',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            areaStyle: {
                normal: {}
            },
            data: data,
            animation: false
        }
    ]
</pre>

**Comment by Ovilia** [comment]
This is probably cause by `smooth`. You may remove the `smooth: true` and see if it still have this problem. 
If it's caused by `smooth`, I think this should not be a bug because the curve is calculated to be different based on data.

**Comment by klausb** [comment]
It is not related to smooth. I switched it off and it does it again. See here: https://gallery.echartsjs.com/editor.html?c=xxM_2zmYh&v=4

**Comment by 100pah** [comment]
@klausb I am also not able to reproduce that.
Could we have more info like: browser, OS to get a more similar environment to reproduce it

**Comment by klausb** [comment]
@100pah, thanks for your suggestions. This change seems to fix it. 
Can you provide more insights to the internal logic, that evaluates the time-series and detects an actual shift-left transition? I want to make sure, that the data that we add to the time-series is behaving correctly during the animation.

**Comment by adash-dev** [comment]
Hi, I'm sorry to open such an old topic, but I have the same problem. The data is transformed after the update, but I would expect a shift animation. The suggestions here did not help me. Can someone please advise me why it doesn't work for me in jsfiddle as I would expect? Thank you

[jsfiddle example](https://jsfiddle.net/Clyde256/b2d4juzt/37/)

**Comment by pissang** [comment]
It's probably because echarts needs an id to identify each data when doing animation. You can to try adding a name property in each item.
```js
this.chart_data.push({ name: '2020-09-01 15:14:18.0', value: ['2020-09-01 15:14:18.0', 2.5] });
```

**Comment by adash-dev** [comment]
> @adash-dev
> It's probably because echarts needs an id to identify each data when doing animation. You can try adding a name property in each item.
> 
> ```js
> this.chart_data.push({ name: '2020-09-01 15:14:18.0', value: ['2020-09-01 15:14:18.0', 2.5] });
> ```

Thank you very much! It really was that. Just add a name to each value and everything runs as I imagined :)
Here is a modified jsfiddle [https://jsfiddle.net/Clyde256/b2d4juzt/44/](https://jsfiddle.net/Clyde256/b2d4juzt/44/) where everything already works.

Thanks again.

**Comment by svnflw** [comment]
Is there currently a solution that allows keeping the line animation while pushing new data without setting animationDurationUpdate to 0?
