### ISSUE TITLE
Erroneous Behavior when displaying a line chart with multiple data pushes before updating chart data while zoomed in

### ISSUE THREAD

**Issue by Serious-ChrisLopez** [apache/echarts#12164]
### Version
4.6.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2](https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2)

### Steps to reproduce
1) Go to the minimal reproduction link provided.
2) Zoom in at any level

### What is expected?
Lines should be rendered smoothly while zoomed in.
![normalgraph](https://user-images.githubusercontent.com/26230309/74701325-a19b3f00-51c3-11ea-89a1-e0fb3b7dae0f.png)

### What is actually happening?
After zooming in at least once, the lines on the left side of the chart appear to zigzag back and forth rather than continuing to form a smooth line.
![crazyGraph](https://user-images.githubusercontent.com/26230309/74701346-acee6a80-51c3-11ea-8ecb-b28b3e920972.png)

---
I've created a real-time application where I am sending a lot of data quickly. The issue arises when pushing data multiple times to an array before updating the chart at an interval. I do this so that I don't have to update the chart as many times and performance is better. 

![react-app](https://user-images.githubusercontent.com/26230309/74701471-06ef3000-51c4-11ea-9ed2-b1e8fcbb416c.gif)

Turning off the animation on the series appears to stop the zigzagging (Orange line above shows this). Customizing the animation with any or all options such as animationDelayUpdate, animationDurationUpdate, etc does not work and the zigzagging keeps happening (Blue line above shows this). The red line is without any animation customizations and animation is the default value.

**Comment by Ovilia** [comment]
Please save your code online.

**Comment by Serious-ChrisLopez** [comment]
I have saved it here: https://gallery.echartsjs.com/editor.html?c=x6WGc3uDy&v=2

**Comment by Ovilia** [comment]
Thanks. This seems to be a bug.
