### ISSUE TITLE
Brush in Series-Pie

### ISSUE THREAD

**Issue by unknow** [apache/echarts#12178]
### Version
4.6.0

### Reproduction link
[http://output.jsbin.com/tihahereco](http://output.jsbin.com/tihahereco)

### Steps to reproduce
Just click on button 'Click Me'

### What is expected?
That the 'brushselected' event triggered contains the information of the selected dataIndex.

### What is actually happening?
The information of the parameters of the triggered 'brushselected' event does not contain the information of the selected dataIndex.

---
The behavior should be similar to what happens with the brush in Series-Bar charts.

**Comment by Ovilia** [comment]
Pie charts don't support brush operation. See https://echarts.apache.org/en/option.html#brush .
What's the user scenario for this?

**Comment by unknow** [comment]
Discover the piece of pie selected by the brush. I know that there are the '**pieselectchanged**', '**pieselected**' and '**pieunselected**' events for this, but I would like to keep the selection uniform through the brush.

**Comment by Ovilia** [comment]
Pie select is not the same with brushing.

**Comment by Ovilia** [comment]
What do you expect from pie brushing? Selecting the whole pie or pieces? @unknow

**Comment by unknow** [comment]
> What do you expect from pie brushing? Selecting the whole pie or pieces? @unknow

Pieces, Something like that:

**Before Brushing:** 
![pie-brushing-off](https://user-images.githubusercontent.com/10673/75543726-422e0200-5a01-11ea-808a-61972d795a73.png)

**After Brusing:**
![pie-brushing-on](https://user-images.githubusercontent.com/10673/75544029-e31cbd00-5a01-11ea-82e7-a5b4c508345d.png)

**Event Params:**
![details-params](https://user-images.githubusercontent.com/10673/75544777-6ab6fb80-5a03-11ea-92aa-043fc0250f3b.png)

**Comment by Ovilia** [comment]
@unknow OK. I'm afraid I have to mark this as a low priority request.
If you are interested in making a pull request, please refer to https://github.com/apache/incubator-echarts/wiki/How-to-setup-the-dev-environment
