### ISSUE TITLE
echarts-gl中的scatter3d的symbol支持png图片

### ISSUE THREAD

**Issue by easyboot** [apache/echarts#12181]
### What problem does this feature solve?
我目前在使用echarts-gl想通过data的值显示不同的symbol，
但是echarts提示echarts-gl.js:22388 Different symbol type will be ignored.
所以我希望echarts-gl能和echarts的scatter中的symbol一样可以支持png图片功能，谢谢！

### What does the proposed API look like?
            visualMap: [
                { 
                    dimension: 3,
                    max: [5],
                    // max: max.color / 2,
                    inRange: {
                      //  symbolSize:[30,40,50,60,70,80],
                        color:['#1710c0', '#0b9df0', '#00fea8', '#00ff0d', '#f5f811', '#f09a09', '#fe0300'],
                        symbol: ['circle', 'rect', 'roundRect', 'triangle', 'diamond', 'triangle'],
                    }, 
                },

**Comment by JonyJay1326** [comment]
+1

**Comment by xiaoliuwayne** [comment]
支持该功能+1

**Comment by yigechengzi** [comment]
这是没有下文了吗？
