### ISSUE TITLE
ECharts-GL中如何将经纬度坐标转换为平面像素坐标

### ISSUE THREAD

**Issue by chengang0621** [apache/echarts#12187]
### What problem does this feature solve?
在ECharts-GL中可能需要个性化一些东西，需要用到相关的平面坐标，所以希望有这样的API接口

### What does the proposed API look like?
类似EChartsl里面.coordinateSystem.dataToPoint

**Comment by hugetiny** [comment]
我也希望有一个dataToPoint，现在好像官方文档没有这一部分

**Comment by hugetiny** [comment]
默认的 第一第二个参数就是经纬度，最起码globe的coordinate system是这样的

**Comment by fanhualuoye** [comment]
请问问题解决吗?
