### ISSUE TITLE
关系图怎么鼠标多选node，然后移动？

### ISSUE THREAD

**Issue by travis1111** [apache/echarts#12195]
### Version
4.6.0

### Steps to reproduce
像在PS里面一样，鼠标画出个框，选中框里面所有的node 然后做移动？最后所有在框里面的node 都给移动了？

### What is expected?
as above

### What is actually happening?
new feature？

**Comment by Ovilia** [comment]
看起来比较像 https://echarts.apache.org/zh/option.html#brush 但是目前不支持关系图，可以考虑自行研究下源码
