### ISSUE TITLE
Determine Bar-Width based on time-axis

### ISSUE THREAD

**Issue by LarsKoelpin** [apache/echarts#12198]
### What problem does this feature solve?
The current barSeries is centered around its point in time.
But, to present time-based data, it is often necessary to present a bar based on a given time-window.

Currently, it is possible to determine the width of the bar in pixels but not relative to the corresponding x-value when using **time-axis**.
For my specific usecase i need to draw a bar chart representing a timewindow.
e.g. the bar shall span from 1pm to 2pm instead of centering a fixed pixelwidth around 1:30pm.

### What does the proposed API look like?
My Proposal would be the be able to specify a function, "relativeBarWith", which gets the current x value as parameter
```
{
  type: "bar",
  relativeBarWidth: (timestamp) => ({
    startBarAt: timestamp - MS_ONE_HOUR,
    endBarAt: timestamp
  })
}
```

echarts would then dynamically calculate the width in pixels of the bar.

**Comment by Ovilia** [comment]
Please consider using custom series based on [histogram chart](https://www.echartsjs.com/examples/zh/editor.html?c=bar-histogram).

**Comment by LarsKoelpin** [comment]
I managed to get it kind of working using a custom chart. 
Would have been convienent to use a bar chart tho. 
However, I think the ticket can be closed, as it is possible.

**Comment by mpaduada** [comment]
@LarsKoelpin Can you post a snippet of the custom chart option you used?

**Comment by LarsKoelpin** [comment]
> @LarsKoelpin Can you post a snippet of the custom chart option you used?

Sure, its the one derivation used in my reproduction case of #12221 (https://jsfiddle.net/3zrLnvqp/)
