### ISSUE TITLE
喝多了后注册了个endof.world想记录下世界末日，用echarts用下来发现这么几个问题

### ISSUE THREAD

**Issue by hugetiny** [apache/echarts#12212]
### Version
4.6.0

### Reproduction link
https://endof.world

### Steps to reproduce

https://www.echartsjs.com/examples/zh/editor.html?c=scatter3d-globe-population&gl=1
https://gallery.echartsjs.com/editor.html?c=xnyknPF1R

### What is expected?
兼容性已经基本解决，主要是以下其他希望能改进下

### What is actually happening?
~~1.手上用小米系列手机的浏览器（UC,百度,小米,chrome）对于echarts-gl兼容性差,提过issue
https://github.com/apache/incubator-echarts/issues/12200~~

2.globe中的baseTexture其实既是纹理又是网格，能否分开做选项？（参考我endof.world的两个版本）
用了静态图片則不能实现地图分块：  baseTexture: ROOT_PATH   "data-gl/asset/world.topo.bathy.200401.jpg",
用了分块則不能加个漂亮的地球皮肤：  baseTexture引用外面```echarts.registerMap('world'.....``` 的数据

3.官方案例：https://www.echartsjs.com/examples/zh/editor.html?c=scatter3d-globe-population&gl=1
散点的tooltip会因为地球角度不同被卡在地球里面看不见

**Comment by hugetiny** [comment]
1属于兼容性，去掉light已经好多了，光照对于非游戏来讲其实意义不大
2，3均属于feature request
望改进官方案例

**Comment by hugetiny** [comment]
这个地球项目以后我专门放点数据
https://github.com/hugetiny/endofworld
感谢百度，阿里，coding，能那么快上线一个数据地球

**Comment by hugetiny** [comment]
已经弄好了每日更新的武汉肺炎数据，但是不定期echarts-gl会出现'...Cannot read property 'maxSize' of undefined ' 不知道为什么

**Comment by Remimstr** [comment]
It's cool to see someone else who had the same idea! Here's my version of this: https://covid19globe.remimstr.com/

I'm browsing these issues to see if I can find a solution for the label clipping problem: https://github.com/Remimstr/COVID-19-globeview/issues/1

**Comment by hugetiny** [comment]
@Remimstr How did you find me on a page written in Chinese?
I also had the label clipping problem and no solution now.

**Comment by Remimstr** [comment]
@hugetiny Good question ;) Google translate does a truly fantastic job of translating these pages into English. Yeah I haven't even found much discussion (just this: https://github.com/ecomfe/echarts-gl/issues/105) about this issue unfortunately and the fix looks like it could be complicated.

**Comment by hugetiny** [comment]
@Remimstr I asked the same question in this issue, but I haven't got an answer.
I tried using D3, but it was a bit complicated, so I gave up. 
Hope for an solution from baidu staffs.
