### ISSUE TITLE
MarkArea拖动延时

### ISSUE THREAD

**Issue by 0x587** [apache/echarts#12210]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xmxO1acYY](https://gallery.echartsjs.com/editor.html?c=xmxO1acYY)

### Steps to reproduce
直接运行图表即可

### What is expected?
希望可以减少拖动的延时

### What is actually happening?
延迟非常大

**Comment by Ovilia** [comment]
请问是否是指 MarkArea 在 dataZoom 移动范围的时候没有动画？

**Comment by 0x587** [comment]
不是
是指在左右拖动图表的时候，markarea明显和其他元素不同步。有卡顿感

**Comment by Ovilia** [comment]
这个不同步就是因为其他元素有动画，MarkArea 没有 动画

**Comment by 0x587** [comment]
![ECharts Gallery - 图像拖动时MarkArea迟钝不同步 - Google Chrome 2020-03-03 13-59-59](https://user-images.githubusercontent.com/40025941/75749835-bea44600-5d5d-11ea-87fa-c69c25c46b59.gif)
可是是markarea滞后于其他元素，有没有办法消除这种卡顿感

**Comment by 100pah** [comment]
```js
option = {
    animation: false,
    ...
}
```
这样会好点么？

**Comment by 100pah** [comment]
Need enhancement: 

Perhaps support animation to markArea will make it better.
