### ISSUE TITLE
Cannot read property 'traverse' of undefined when drawing custom chart

### ISSUE THREAD

**Issue by LarsKoelpin** [apache/echarts#12221]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/3zrLnvqp/](https://jsfiddle.net/3zrLnvqp/)

### Steps to reproduce
I attached a JS Fiddle.

When pressing "run" multiple times i get the error.

```javascript
echarts.min.js:22 Uncaught TypeError: Cannot read property 'traverse' of undefined
    at e.incrementalRender (echarts.min.js:22)
    at Hh.progress (echarts.min.js:22)
    at tc (echarts.min.js:22)
    at Hh.Zh.perform (echarts.min.js:22)
    at echarts.min.js:22
    at e.<anonymous> (echarts.min.js:22)
    at Array.forEach (<anonymous>)
    at E (echarts.min.js:22)
    at eachSeries (echarts.min.js:22)
    at Zd (echarts.min.js:22)
```
It may be somewhat random if it crashes or not.
When it does not reproduce, increase the amount of data generated (name in example: INCREASE_ME_FOR_REPRODUCTION_CASE)

It may has to do with triggering a rerender too early, when the previous chart wasn't drawn completely

### What is expected?
The chart rerenders

### What is actually happening?
The error above occurs

**Comment by LarsKoelpin** [comment]
It seems that the issue does not depend on "setInverval". I also can reproduce the issue when drawing a custom chart with lots of data

**Comment by 100pah** [comment]
That is a bug, happened when data count is larger than the [progressiveThreshold](https://echarts.apache.org/zh/option.html#series-scatter.progressiveThreshold), where progressive rendering is enabled. 

To avoid this issue temporarily, we can simply set:
```js
    series: [{
        type: 'custom',
        renderItem: renderItem,
        progressive: 0,                 // Disable progressive
        itemStyle: {
            opacity: 0.8
        },
        data: data
    }]
```

**Comment by 100pah** [comment]
The minimal `option` to reproduce this issue:

```js

option = {
    yAxis: {
    },
    xAxis: {
    },
    series: [{
        type: 'custom',
        renderItem: function () {},     // the renderItem return nothing.
        progressiveThreshold: 1,       // Enable progressive when data item count > 1
        data: [[123, 456], [654, 321]] // data item count is 2
    }]
};
````

The bug need to be fixed.

**Comment by WenBinWu** [comment]
Add some code in function of incrementalRender may fix this issue.
`
    incrementalRender: function (params, customSeries, ecModel, api, payload) {
        var data = customSeries.getData();
        var renderItem = makeRenderItem(customSeries, data, ecModel, api);
        function setIncrementalAndHoverLayer(el) {
            if (!el.isGroup) {
                el.incremental = true;
                el.useHoverLayer = true;
            }
        }
        for (var idx = params.start; idx < params.end; idx++) {
            var el = createOrUpdate$1(null, idx, renderItem(idx, payload), customSeries, this.group, data);
**+          if (el)**
                el.traverse(setIncrementalAndHoverLayer);
        }
    },`

**Comment by harrysoer** [comment]
The `progressive: 0` works like a charm but the charts are lagging so bad when the user is hovering a specific data point.

**Comment by liucaidong** [comment]
has this problem been resolved?

**Comment by fightGitHub93** [comment]
> Add some code in function of incrementalRender may fix this issue.
> `
> incrementalRender: function (params, customSeries, ecModel, api, payload) {
> var data = customSeries.getData();
> var renderItem = makeRenderItem(customSeries, data, ecModel, api);
> function setIncrementalAndHoverLayer(el) {
> if (!el.isGroup) {
> el.incremental = true;
> el.useHoverLayer = true;
> }
> }
> for (var idx = params.start; idx < params.end; idx++) {
> var el = createOrUpdate$1(null, idx, renderItem(idx, payload), customSeries, this.group, data);
> **+ if (el)**
> el.traverse(setIncrementalAndHoverLayer);
> }
> },
> 
> `我也使用了同样的方式修改了源码，这样是否可行，会不会引起其他的问题？
