### ISSUE TITLE
Scatter plot - hiding item tooltip triggers for outOfRange using visualMap

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#12225]
### Version
4.6.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=scatter-aqi-color](https://echarts.apache.org/examples/en/editor.html?c=scatter-aqi-color)

### Steps to reproduce
In the example if any item is overlapping with bigger item and is behind then there is no way to view its tooltip details.
Even after changing visualMap trigger it can just hide element but cant remove tooltip trigger.

### What is expected?
There should be a way to disable tooltip triggers for items which are outOfRange using visualMap. Then users can see tooltip details by hiding bigger items using visualMap triggers

### What is actually happening?
There is no way to view details in tooltip for item overlapping and behind bigger item.

**Comment by 100pah** [comment]
Firstly, like @dileepyelleti mentioned, there could be an option to make items that is out of range silent.

But it is a typical issue that how to show the detail info of the overlapped items.
But I have no clear idea with it yet.

Even if we use `dataZoom`, if to items are very close or even the same, one of them is still hard to be checked.
Maybe "snap" feature should be provided. And there might be some option to make the tooltip show more than one item if they are very close.

What's your opinion @pissang @Wdingding  ?
