### ISSUE TITLE
移动端设备上的自定义坐标轴上的三角形与坐标轴对不齐

### ISSUE THREAD

**Issue by zhuchuanlei** [apache/echarts#12233]
### Version
3.8.5

### Steps to reproduce
![image](https://user-images.githubusercontent.com/25579411/75849366-a72d9180-5e1f-11ea-8602-99536fa8b8c9.png)

移动端上坐标轴width设置为2时像是对齐的，配置如下: 
```ts
yAxis: {
      type: 'value',
      axisTick: {
        show: false
      },
      splitLine: {
        show: false
      },
      axisLine:{
        lineStyle:{
          color:'#666',
          width: 1
        },
        symbol:['none','path://M4 0 L0 8 L8 8 Z'],
        symbolSize:[8,8],
        symbolOffset:[0,4],
      },
      axisLabel: {
        color: '#666',
        width: 4,
        show: false,
      },
    }
```
### What is expected?
希望坐标轴宽度为1时，箭头的顶端与坐标轴的线在同一竖线上

### What is actually happening?
箭头的顶端在坐标轴的线左侧1像素左右

---
移动端宽度为奇数时不对齐，为偶数时对齐的。PC端相反。
1，想让Y轴向左偏移，但是箭头会同时移动。
2，坐标轴宽度设置为2，想通过渐变方式让坐标轴左右两侧分别设置一部分透明，看上去宽度是1，但是箭头也跟着透明

**Comment by Ovilia** [comment]
先试一下最新版本看下效果？因为 3.8 的版本很老了。
此外请提供一个可运行的 demo。

**Comment by zhuchuanlei** [comment]
@Ovilia 测试了一下4.6.0的版本也是一样的问题。demo已经更新: https://gallery.echartsjs.com/editor.html.

**Comment by zhuchuanlei** [comment]
@Ovilia 在官网例子里追加三角箭头，发现PC端也是有错位问题，放大之后可以看到

**Comment by Ovilia** [comment]
看到了，之后会优化下
