### ISSUE TITLE
When zooming in on a chart using toolbox.feature.dataZoom if a point is outside the selected zoom rectangle the chart is not plotted correctly

### ISSUE THREAD

**Issue by ghost** [apache/echarts#12247]
### Version
4.7.0-rc.1

### Reproduction link
[http://jsfiddle.net/grahamallan31/m5vxefwL/4/](http://jsfiddle.net/grahamallan31/m5vxefwL/4/)

### Steps to reproduce
One the attached jsfiddle select the dataZoom button and draw a zoom rectangle from Monday,550 to Sun 250
Release the moue to zoom

### What is expected?
The Tue to Wed data points and Wed to Thu data points are connected with a line the disappears outside the selected region
See https://imgur.com/a/9DdYgqQ

### What is actually happening?
The chart will zoom in the show the selected region omitting the value for Wed (zero) connecting Tue ti 

---
Found while setting up a step chart which also shows the same behaviour

**Comment by 100pah** [comment]
The can be resolved by:
```js
option = {
    toolbox: {
        feature: {
            dataZoom: {
                filterMode: 'none'
            }
        }
    }
};
```
