### ISSUE TITLE
开启dataZoom拖动图表选中的点不会取消选中状态

### ISSUE THREAD

**Issue by w611363303798** [apache/echarts#12248]
### Version
4.6.0

### Reproduction link
[https://www.echartsjs.com/examples/en/editor.html?c=line-aqi](https://www.echartsjs.com/examples/en/editor.html?c=line-aqi)

### Steps to reproduce
官方demo也存在同样问题，将图表放大拖动

### What is expected?
选中点效果只有一个

### What is actually happening?
选中点效果有很多不能消失

![image](https://user-images.githubusercontent.com/24557962/76140394-034d1b80-6095-11ea-8a7c-c9ab83e9626a.png)

**Comment by zhangzhonghe** [comment]
Is it fix?
