### ISSUE TITLE
Set image on label

### ISSUE THREAD

**Issue by webasoo** [apache/echarts#12245]
### What problem does this feature solve?
Why doesn't the label.formatter HTML support?
For example, I want the label of each column to contain a photo. There is a way?
backgroundcolor.image not support params data too.

### What does the proposed API look like?
label.formatter HTML support

**Comment by 100pah** [comment]
HTML label is not supported. 
The [rich text](https://echarts.apache.org/en/tutorial.html#Rich%20Text) can be used to draw picture in text.
