### ISSUE TITLE
grid.boundaryGap且xAxis.boundaryGap==false模式下x轴两边的label无法完整显示

### ISSUE THREAD

**Issue by Ling310** [apache/echarts#12252]
### Version
4.7.0-rc.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xvgHNKy-M&v=1](https://gallery.echartsjs.com/editor.html?c=xvgHNKy-M&v=1)

### Steps to reproduce
当grid.boundaryGap==true&&xAxis.boundaryGap==false

### What is expected?
希望xAxis两端的label可以完整显示

### What is actually happening?
xAxis左右两边的label的宽度未被计算

**Comment by BusyHe** [comment]
+1

**Comment by meowtec** [comment]
+1, 我希望的是不设置 boundaryGap 的情况下，能把曲线往左右两侧扩充满。不知道有没有人有办法。
