### ISSUE TITLE
在graph关系图中，文字无法缩放。鼠标移入节点的鼠标样式无法更改。

### ISSUE THREAD

**Issue by lengxuan2018** [apache/echarts#12261]
Version
4.6.0

Steps to reproduce
①在graph图中，设置属性draggable: true, cursor: 'pointer'后，开启拖拽功能后设置的cursor属性无效。
②在graph图中，设置属性roam: true后，开启平移和缩放功能，进行缩放时，label的字体大小不会随缩放而缩放。

What is expected?
①开启拖拽功能后另支持鼠标样式的设置。
②开启缩放后，节点的字体大小可随画布的缩放而缩放。

What is actually happening?
目前不支持上述功能。

**Comment by pissang** [comment]
文本不随节点缩放是故意设计成这样的，如果文本缩小到看不清会失去了文本显示的意义，如果文本变大了则显示效果会不好

**Comment by lengxuan2018** [comment]
有方法可以把文字设置成随图形缩放而缩放吗？

**Comment by pissang** [comment]
@lengxuan2018 目前还不行，不过如果确实有需求的话可以考虑加入配置项

**Comment by yuanzhou3118** [comment]
已通过graphRoam实现：

     // 鼠标滚轮监听放大缩小
     myECharts.on('graphRoam', function(e) {
        const option = that.echartsGraph.getOption(); // 获得当前option.series的zoom
        const textPercent = (option.series[0].zoom - 0.8) / 0.8; // 计算比例,我设置zoom的初始值是0.8
        option.series[0].label.fontSize = 9 + 9 * textPercent // 等比例计算fontSize
        that.echartsGraph.setOption(option); // setOption
      });
同理可以加在toolbox内的自定义的“放大”和“缩小”按钮上

希望可以帮助到其他同学 😝

**Comment by Drowned-fish** [comment]
我使用echarts-for-react来监听graphRoam没有反应

**Comment by yuanzhou3118** [comment]
这个问题

> 我使用echarts-for-react来监听graphRoam没有反应

要不在echarts-for-react 提一个issue问下？

**Comment by muxiliu** [comment]
> 已通过graphRoam实现：
> 
> ```
>  // 鼠标滚轮监听放大缩小
>  myECharts.on('graphRoam', function(e) {
>     const option = that.echartsGraph.getOption(); // 获得当前option.series的zoom
>     const textPercent = (option.series[0].zoom - 0.8) / 0.8; // 计算比例,我设置zoom的初始值是0.8
>     option.series[0].label.fontSize = 9 + 9 * textPercent // 等比例计算fontSize
>     that.echartsGraph.setOption(option); // setOption
>   });
> ```
> 
> 同理可以加在toolbox内的自定义的“放大”和“缩小”按钮上
> 
> 希望可以帮助到其他同学 😝

非常感谢，已经通过这种方式解决。想请问一下，文档里面怎么都没有看到graphRoam这个事件。能够支出一下echarts文档中对这个事件的描述的位置吗？

**Comment by Dxig** [comment]
> [@lengxuan2018](https://github.com/lengxuan2018) 目前还不行，不过如果确实有需求的话可以考虑加入配置项

echarts@5 中还是没有加入配置项，考虑加入吗？
