### ISSUE TITLE
series-pie 中 data.selected 并不是可控的

### ISSUE THREAD

**Issue by jaceyi** [apache/echarts#12277]
### Version
4.6.0

### Reproduction link
[https://codesandbox.io/s/echarts-demo-3ux9g](https://codesandbox.io/s/echarts-demo-3ux9g)

### Steps to reproduce
传入data并指定selected，点击选中的还能取消这个选中

### What is expected?
我并没有通过 setOption 再次更新 selected 的值，那么当前选中的状态就应该不能被更改

### What is actually happening?
选中的值不是完全可控，而像是一个初始值。因为这个不可控还导致了 series-pie   legend 也会出现问题，当期选中的值被隐藏了，选中的值自动跑到了下一个，如果我前面有两项被隐藏，那么后面的 selected 将会偏移的更多...

**Comment by alex2wong** [comment]
这个问题似乎见过，https://github.com/apache/incubator-echarts/pull/11934 这个 PR 能 fix，select 错位的问题。 你可以测试下 4.7.0 或者等下个版本 
@pissang  我在 release 4.7 的 changelog 里没看到这个 pr 呢？
