### ISSUE TITLE
renderSeries is called when updating graphic component

### ISSUE THREAD

**Issue by ezubarev** [apache/echarts#12271]
### Version
4.4.0

### Reproduction link
[https://jsfiddle.net/w6yjs3ax/](https://jsfiddle.net/w6yjs3ax/)

### Steps to reproduce
If there are a lot of series on chart the cost of updating the graphic element is too big. 
Instead of render a single shape it also renders all series from scratch.
It happens when using `chart.setOption({ graphic: ... }) `method.

### What is expected?
renderSeries isn't called

### What is actually happening?
renderSeries is called

**Comment by pissang** [comment]
`renderSeries` is not supposed to be called if there is only `graphic` being updated. We will look into this issue.

**Comment by ezubarev** [comment]
@pissang Could you say when you will be able to look into this issue?

**Comment by pissang** [comment]
Probably in the version 4.9.0. Before the end of next month.

**Comment by ezubarev** [comment]
@pissang  any updated?

**Comment by pissang** [comment]
@ezubarev Sorry for the late reply. But we need to reschedule it to the 5.0
