### ISSUE TITLE
How to remove first breadcrumb part in treemap?

### ISSUE THREAD

**Issue by Caglayan06** [apache/echarts#12284]
Hey, i want to delete first empty part in breadcrumb in treemap chart. I put serie name empty and it became small part. But i want to delete completly.

**Comment by Ovilia** [comment]
Does `show: false` work for you?

**Comment by Caglayan06** [comment]
> Does `show: false` work for you?

I want to keep breadcrumb except first empty part('serie name'). Is it possible to` show: false` for only first portion.

**Comment by Ovilia** [comment]
I'm afraid this is not possible with ECharts.
