### ISSUE TITLE
Add schematic diagram in the option document

### ISSUE THREAD

**Issue by kuige** [apache/echarts#12285]
### What problem does this feature solve?
In the options document, like this https://echarts.apache.org/en/option.html#series-bar.label, there is only word description, which is not so clear and straightforward . If some schematic diagram were added, it's much more easier to understand what the option means.

### What does the proposed API look like?
no api

**Comment by kuige** [comment]
When I check the options here, https://echarts.apache.org/en/option.html#series-bar.markArea, it just saying:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/8212800/76821164-148de900-6848-11ea-8ed3-58073ac9db0a.png">
And I still don't known what does the markArea means.
It's much better if there were a picture showing what the markArea looks like.

**Comment by Ovilia** [comment]
@kuige Thanks for your advice. In fact, we have https://echarts.apache.org/zh/cheat-sheet.html this tool designed just for the consideration of introducing components. Perhaps we should add markArea there. Do you have questions on other components?

**Comment by kuige** [comment]
Thanks, it's the markArea component by far.
