### ISSUE TITLE
Please add an API to get current calculated option

### ISSUE THREAD

**Issue by a5hk** [apache/echarts#12290]
### What problem does this feature solve?
Right now there is `echartsInstance.getOption` which returns the options but at is not the calculated one (at least for some properties).  For example I have set the `cellSize` of calendar to `["auto", "auto"]`, when I call `getOption` the value it returns for `cellSize` is `["auto", "auto"]` but I want to know the exact width and height of cells in pixels. I am trying to change the size of pie charts in [this example](https://www.echartsjs.com/examples/en/editor.html?c=calendar-pie) based on calendar cell size and I need to know the current `cellSize` to do that.

### What does the proposed API look like?
`echartsInstance.getCalculatedOption`

**Comment by pissang** [comment]
Hi @a5hk . Currently you can use inner methods.
```js
getModel().getComponent('calendar').coordinateSystem.dataToRect(date);
```
