### ISSUE TITLE
X轴上的分割线splitLine属性interval formatter函数控制显示，右边多出一条分割线

### ISSUE THREAD

**Issue by aloneWang** [apache/echarts#12293]
### Version
4.6.0

### Steps to reproduce
类轴上的分割线splitLine 属性 interval 使用formatter 函数控制显示，最右边默认多出一条分割线
配置：
```js
option = {
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true,
        show: false,
    },
    xAxis: [
        {
            type: 'category',
            data: ["1901",
            "1902",
            "1903",
            "1904",
            "1905",
            "1906",
            "1907",
            "1908",
            "1909",
            "1910",
            "1911",
            "1912"],
            splitLine: {
                show: true,
                interval: (index) => {
                    return index === 3 || index === 6 || index === 9
                }
            }
        }
    ],
    yAxis: [
        {
            type: 'value',
            splitLine: {
                show: false,
                
            }
        }
    ],
    series: [
        {
            name: '直接访问',
            type: 'bar',
            barWidth: '60%',
            data: [10, 52, 200, 334, 390, 330, 220,200, 334, 390, 330, 220]
        }
    ]
};
```
### What is expected?
分割线只显示 下标 3 ， 6， 9

### What is actually happening?
最右边多出一条分割线

**Comment by yufeng04** [comment]
It seems to be a bug.

**Comment by qierkang** [comment]
hello！
The optimization plan has been given here, you can refer to

![image](https://user-images.githubusercontent.com/17940151/84349172-54ffc780-abe9-11ea-8096-c0d0d349617b.png)

![image](https://user-images.githubusercontent.com/17940151/84343303-5aa1e100-abda-11ea-845e-f476c6b5bab4.png)
![image](https://user-images.githubusercontent.com/17940151/84349123-3a2d5300-abe9-11ea-827e-07258720e0f7.png)

**Comment by Gavin-Gong** [comment]
4.8.0 出现同样的问题，我看已经有大佬提了 Pull Request，加了 test，什么时候 merge 呢？@pissang

**Comment by Gavin-Gong** [comment]
基于4.8 的代码 &  #12595 的 PR 修复，临时发布一个 npm 包 `@moon-land/echarts`，暂时过渡
使用
```
npm i @moon-land/echarts
```
