### ISSUE TITLE
Hover bug on 3D Scatter when give one valued data

### ISSUE THREAD

**Issue by resulyrt93** [apache/echarts#12308]
Hey, when i set data as object (not directly two dimensional array) and object have one value, 3d scatter's on hover event is not functional.  You can try with below option code in [this example page](https://echarts.apache.org/examples/en/editor.html?c=scatter3d&gl=1&theme=dark) . I just get first item of current data and put it a array again.

        series: [{
            type: 'scatter3D',
            dimensions: [
                config.xAxis3D,
                config.yAxis3D,
                config.yAxis3D,
                config.color,
                config.symbolSiz
            ],
            data: [data.map(function (item, idx) {
                return [
                    item[fieldIndices[config.xAxis3D]],
                    item[fieldIndices[config.yAxis3D]],
                    item[fieldIndices[config.zAxis3D]],
                    item[fieldIndices[config.color]],
                    item[fieldIndices[config.symbolSize]],
                    idx
                ];
            })[0]],
            symbolSize: 12,
            // symbol: 'triangle',
            itemStyle: {
                borderWidth: 1,
                borderColor: 'rgba(255,255,255,0.8)'
            },
            emphasis: {
                itemStyle: {
                    color: '#fff'
                }
            }
        }]

**Comment by ljjeseller** [comment]
is there any solution?
