### ISSUE TITLE
有二个Y轴时使用"切换为堆叠"第二个Y轴刻度全错了

### ISSUE THREAD

**Issue by lk1942** [apache/echarts#12305]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xrzFP5HKnV&v=1](https://gallery.echartsjs.com/editor.html?c=xrzFP5HKnV&v=1)

### Steps to reproduce
有二个Y轴时，点击"切换为堆叠"工具按钮，第二个Y轴刻度错了。

### What is expected?
期望第二个Y轴刻度不变。

### What is actually happening?
第二个Y轴刻度不正确。

**Comment by yufeng04** [comment]
A configuration may  be needed  to control Y-axis stacking.
