### ISSUE TITLE
What is the maximum number of nodes that the tree map can contain?

### ISSUE THREAD

**Issue by 10229428** [apache/echarts#12312]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/tianhen0527/c63wvfjr/](https://jsfiddle.net/tianhen0527/c63wvfjr/)

### Steps to reproduce
Use the data with about 30 nodes, the tree map can be displayed normally. But when I use the data with 700  nodes,  the page crashed!

I have put the test data with 700  nodes in the buttom of https://jsfiddle.net/tianhen0527/c63wvfjr/

### What is expected?
The tree can be displayed normally.

### What is actually happening?
The page crashed! Exception occured in Console:
```
RangeError: Maximum call stack size exceeded
    at run (editor.js?_v_=1584687926098:1)
    at e (lodash.js:46)
    at u (lodash.js:46)
```

**Comment by 100pah** [comment]
@10229428 
I can not reproduce the "Maximum call stack size exceeded" error by the 700 nodes in the bottom of https://jsfiddle.net/tianhen0527/c63wvfjr/ in the latest Google Chrome.

But theoretically the error would be thrown if the data is too deep. Based on the current implementation,
 it depends on the max stack size of the browser. The number in modern browsers would be bigger than 10k, but is legacy IE may be several thousand. 

@10229428  Could  I know what environment do you used?

Anyhow, consider that `tree` and `treemap` do not necessarily display all of the nodes, `tree` and `treemap` should 
 better be improved to raise the upper bound of the supported data levels.

**Comment by 10229428** [comment]
@100pah 
Thanks for your answer.
As you said, maybe it depends on the max stack size of the browser. But I can not ensure that the user ’s brower will be ok.
I use the tree map to show the histories for some operations. I have limited the number(or level) to 600, the excess will be deleted automatically.

![1](https://user-images.githubusercontent.com/42016535/77384125-8ec9ea80-6dbf-11ea-96a0-d9330b9d776e.gif)
