### ISSUE TITLE
桑基图右侧label被截断

### ISSUE THREAD

**Issue by zyfly** [apache/echarts#12325]
### Version
4.6.0

### Steps to reproduce
显示桑基图的label，label可能会很长，60多个字符。在最右侧的label会被截断。
canvas的宽度是通过文本宽度累加计算出来的，还预留了buffer，即使label很长，也预留了宽度来显示，但是实际最右侧的长label，还是显示不全。

### What is expected?
期望节点的标签能够全部显示

### What is actually happening?
最右侧的长label被截断了，如图
![Xnip2020-03-24_21-18-55](https://user-images.githubusercontent.com/10719442/77430128-a633c280-6e15-11ea-9f8f-636a6afd5f73.jpg)

**Comment by zyfly** [comment]
demo已经上传至  https://jsfiddle.net/jdx340aq/1/

**Comment by 100pah** [comment]
目前，只能在适当的地方，手动添加 \n 来让文本折行。
