### ISSUE TITLE
graph当节点达到1000或更多时，会变得很卡顿

### ISSUE THREAD

**Issue by ChakNS** [apache/echarts#12339]
### Version
4.4.0

### Steps to reproduce
```javascript
series : [
    {
      name: '',
      type: 'graph',
      layout: 'force',
      data: [],
      links: [],
      roam: true,
      label: {
        normal: {
          position: 'right'
        }
      },
      force: {
        repulsion: 100
      }
    }
  ]
```

### What is expected?
1、是否有方法可以解决多节点卡顿问题
2、是否可以在开启force布局时，关闭节点迭代的过程而不导致假死，尝试过不开启布局，使用随机坐标，但这样看起来很乱

### What is actually happening?
1、渲染完成之后页面变得很慢
2、force布局下，无法实现静态渲染

---
另：在使用echarts-gl时一直提示echarts版本过低，即使我的echarts已经更新到最新的4.7.0版本

**Comment by travis1111** [comment]
我现在还没有尝试超过100个节点。

我现在在做的是，看有没有办法先force layout 一次，得到坐标，然后把坐标保存到原始的数据中。这样，以后显示的时候直接调用带有坐标的数据，就免去了布局的步骤。

我试了下，不行。我发到这里了

https://github.com/apache/incubator-echarts/issues/12357

你还能想到什么方法？
