### ISSUE TITLE
The callback function of toolip formatter will be executed multiple times

### ISSUE THREAD

**Issue by dfc12315** [apache/echarts#12338]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xqr_p2-TB8&v=1](https://gallery.echartsjs.com/editor.html?c=xqr_p2-TB8&v=1)

### Steps to reproduce
如案例打开控制台界面，移动鼠标到对应的 one 块上面，日志打印输出会执行很多次， 同样在这里调用 网络请求也会被执行很多次

### What is expected?
鼠标移入到 one、two 等上面只执行一次请求

### What is actually happening?
执行了很多次请求

**Comment by susiwen8** [comment]
Related to https://github.com/apache/incubator-echarts/issues/10215

**Comment by susiwen8** [comment]
tooltip 展示是根据鼠标移动而更新的

**Comment by dfc12315** [comment]
谢谢，没有看到那个，抱歉

**Comment by wf123537200** [comment]
Is it possible to make a layer of cache? If you have already called fomatter on the same tooltip, it will not be called again. It should be what you can try (you can see if the unique key here uses this)

是不是可以做一层缓存，如果已经对同一个tooltip调用过fomatter，就不再调用，试了下应该是你可以的（这里的唯一key是否用这个可以大家再看看）

```
        // incubator-echarts/src/component/tooltip/TooltipView.js :Line 579
        else if (typeof formatter === 'function') {
            // cache object
            this._toopTipFormatterCache = this._toopTipFormatterCache || {}
            var key = params[0].seriesId + params[0].name
            
            var callback = bind(function (cbTicket, html) {
                if (cbTicket === this._ticket) {
                    tooltipContent.setContent(html, markers, tooltipModel);
                    this._updatePosition(
                        tooltipModel, positionExpr, x, y, tooltipContent, params, el
                    );
                }
            }, this);
            this._ticket = asyncTicket;
            html = this._toopTipFormatterCache[key] || formatter(params, asyncTicket, callback);
            // cache
            this._toopTipFormatterCache[key] = html;
        }
```
result as follow:
结果如下：
![image](https://user-images.githubusercontent.com/5130528/80304561-73506600-87e9-11ea-8207-2c1972630ed3.png)
