### ISSUE TITLE
Label on treemap not use all width/height

### ISSUE THREAD

**Issue by ruben82** [apache/echarts#12332]
### Version
4.7.0

### Steps to reproduce
Put a long label  as series' title with ellipsis = false

### What is expected?
Label must use all width/height to be showed entirely (using break line) 

### What is actually happening?
Label is showed in a single line overlapping other series

<img width="579" alt="Schermata 2020-03-25 alle 18 54 14" src="https://user-images.githubusercontent.com/3014501/77572967-36ced900-6ed0-11ea-8f8c-a72d2ae02e37.png">

**Comment by ruben82** [comment]
Thanks for reply. 
This is a [demo](https://gallery.echartsjs.com/editor.html?c=x_b_o1i0hu&v=1)

**Comment by Ovilia** [comment]
If you want to add line break, use `\n` in the label.

**Comment by ruben82** [comment]
Thanks' @Ovilia , but I don't think that is the right way to do it. The break line must be automatic 'cos I don't know how big is the box to put a \n at the right place. The space is not optimized like this...

**Comment by Ovilia** [comment]
Hi @ruben82 . Auto line-wrapping will be supported in our next big release, which will take another few months. For now, it is not recommended to use `ellipsis = false`.

**Comment by ruben82** [comment]
@Ovilia  Thanks'!!!!!!
I'll be waiting for this feature...
