### ISSUE TITLE
markArea xAxis does not work as expected for category axis and bar series

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#12341]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/758vs6xe/](https://jsfiddle.net/758vs6xe/)

### Steps to reproduce
You have an xAxis of type category and you have a bar series. And you want to markArea of a specific category. You can't because the markArea starts drawing from the center of the bar.

In the example we have the days of the week as categories.
With markArea 'Mon' - 'Tue' you see something.
With markArea 'Wed' - 'Wed' you see nothing.

![Screenshot from 2020-03-27 17-36-55](https://user-images.githubusercontent.com/890368/77772989-a4eed980-7051-11ea-963a-0849f796335b.png)

### What is expected?
For markArea to mark the specific bar category.

### What is actually happening?
It doesn't mark it.

**Comment by jojozex** [comment]
Has this problem been solved?

**Comment by v1talii-dev** [comment]
are there any workarounds?

**Comment by sthenault** [comment]
I've also hit this problem and would be interested in a fix or workaround (looked through the doc and didn't found anything that could do the trick easily)

**Comment by dynamikus** [comment]
any workarounds? I am having the same problem?

**Comment by warren30815** [comment]
You can set itemStyle: { borderWidth: 10 } to get a highlight area
like: https://jsfiddle.net/7hmt89ko/6/

**Comment by sagarey** [comment]
Add a background xAxis with boundaryGap: false, then add markArea in it

**Comment by manelAbbes** [comment]
Hello, I am still experiencing the issue where the mark area covers half of the day. I am using ECharts version 5.4.3. Do you have any ideas on how to fix this?
<img width="905" alt="Screenshot 2024-02-06 115058" src="https://github.com/apache/echarts/assets/159129996/e9bdc58c-6200-462f-bd6c-c4dae502411b">
