### ISSUE TITLE
Magictype Event

### ISSUE THREAD

**Issue by mayrhoferaski** [apache/echarts#12359]
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/en/editor.html?c=bar-animation-delay](https://www.echartsjs.com/examples/en/editor.html?c=bar-animation-delay)

### Steps to reproduce
1.) Go to Example

2.) Add this Code

myChart.on('magictypechanged',function(obj){
   
   	if (obj.currentType == "stack"){
   	    alert("stack: " obj.currentType);
   	}else{
   	    alert("tiled:"  obj.currentType);
   	}
});

### What is expected?
toggle between stack and tiled

### What is actually happening?
currentType is always "stack"

---
I'm looking now for the stack word in the newOption.series[0].stack to be either "" or "__ec_magicType_stack__", but it should not be this way.

**Comment by plainheart** [comment]
I've tried to fix it, it seems working well. But in another case, if we specify the option `stack` for series(refer to [series-line.stack](https://www.echartsjs.com/en/option.html#series-line.stack)), does the stack icon in the toolbox need to be emphasized(selected) by default at the very first rendering. Any idea?

**Comment by alex2wong** [comment]
I suppose the stack icon should be emphasized if we set option stack for series at initial stage. The state should be synced between the series and the toolbox.

**Comment by alex2wong** [comment]
Thanks for your investigation @plainheart ~  You can refer to previous key changes on this toolbox stack things. 
To put it simply, at first we want to simplify the stack icon status,  integrate two icons **into one toggle icon**. so I removed `tiled` type and keep only one stack icon. 

The fisrt commit about this topic: https://github.com/apache/incubator-echarts/commit/e7af6731d048dff489d16e806eab6f5772d32c08

Then we made some revision, removed the tiled icon and type. https://github.com/apache/incubator-echarts/commit/780614906e19fa6a7c5072fcdae2635ad7ac7840

Maybe here we can do more things to make sure the `magictypechanged` event emit correct type, at the same time keep our  enhancement months ago. @pissang

**Comment by ishowman** [comment]
@alex2wong there is a linked pr awaiting review
