### ISSUE TITLE
Bars start flickering when emphasis is set after resize window

### ISSUE THREAD

**Issue by borodovisin** [apache/echarts#12351]
### Version
4.7.0

### Reproduction link
[https://youtu.be/_0w9kIjcuUU](https://youtu.be/_0w9kIjcuUU)

### Steps to reproduce
Use this option object:

```js
option = {
    "yAxis": [{
        "type": "category",
        "show": true,
        "data": ["Virginia", "Minnesota", "Michigan", "Texas", "Maryland", "Ohio", "Connecticut", "Tennessee", "Wisconsin", "Pennsylvania", "Colorado", "Georgia", "Massachusetts", "Louisiana", "Illinois", "Florida", "New Jersey", "California", "Washington", "New York"],
    }],
    "xAxis": [{
        "type": "value",
        "show": true,
    }],
    "series": [{
        "type": "bar",
        "data": [{
            "name": "Virginia",
            "value": 77,
        }, {
            "name": "Minnesota",
            "value": 77
        }, {
            "name": "Michigan",
            "value": 80
        }, {
            "name": "Texas",
            "value": 84
        }, {
            "name": "Maryland",
            "value": 85
        }, {
            "name": "Ohio",
            "value": 86
        }, {
            "name": "Connecticut",
            "value": 96
        }, {
            "name": "Tennessee",
            "value": 98
        }, {
            "name": "Wisconsin",
            "value": 106
        }, {
            "name": "Pennsylvania",
            "value": 133
        }, {
            "name": "Colorado",
            "value": 183
        }, {
            "name": "Georgia",
            "value": 196
        }, {
            "name": "Massachusetts",
            "value": 256
        }, {
            "name": "Louisiana",
            "value": 280
        }, {
            "name": "Illinois",
            "value": 288
        }, {
            "name": "Florida",
            "value": 328
        }, {
            "name": "New Jersey",
            "value": 417
        }, {
            "name": "California",
            "value": 892
        }, {
            "name": "Washington",
            "value": 1187
        }, {
            "name": "New York",
            "value": 2382
        }],
        "itemStyle": {
            "color": "#0095b7"
        },
        "emphasis": {
            "itemStyle": {
                "barBorderColor": "#03051e",
                "barBorderWidth": 1
            }
        }
    }]
}
```

After echarts render the instance, move the mouse over some bars, resize the window and move again the mouse over the bars items.

### What is expected?
Not flickering the bars when emphasis is set inside series

### What is actually happening?
After create the echarts instance and resize the window the bars start flickering.
See the vide example [here](https://youtu.be/_0w9kIjcuUU)

**Comment by alex2wong** [comment]
Please， better provide  demo in jsfiddle or https://gallery.echartsjs.com/editor.html.

**Comment by borodovisin** [comment]
Here the jsfiddle sample: https://jsfiddle.net/btdmxvor/. But there is a little hard to recreate, the window container has to resize to see the issue. In the oficial documentation website taking any example and using the object I provided is very easy to recreate. After echarts instance finish to render mouse the mouse over a few bars and resize the hole browser tab  and move again the mouse over the chart bars. I think is something with the ephasis borderWidth or barBorderWidth. When the mouse enters to the borderWidth the `mouseout`event is dispatch and because that we'll see that flikering there.

**Comment by 100pah** [comment]
Indeed it is a bug.
To reproduce it, resize the chart to make bar very thin, and hover the bars,
and then resize the chart back.

**Comment by pissang** [comment]
Seems can't be reproduced in 5.0. Moved to the 5.0 milestone.
