### ISSUE TITLE
echarts.connect 使用 dataName 作为联动的标识

### ISSUE THREAD

**Issue by SevenOutman** [apache/echarts#12355]
### What problem does this feature solve?
我使用 echarts.connect 来使我的多个图表联动，现在看起来 tooltip 的联动是发生在相同的 dataIndex 上，而 legend 的联动却发生在 dataName 上，表现不一致。

例如，我有两个图表，分别传入同一组数据的正序和倒序，此时 tooltip 的联动是错乱的，如当我在图一中 hover “周一”的数据，图二会显示“周日”的 tooltip。而当我在 legend 中关闭“周一”，两图的“周一”数据均消失。

我想，tooltip 的联动应该也同 legend 一样，使用 dataName 来判断“相同的指标”。或者，可以为 `echarts.connect` 方法提供选项来设置联动的方式。

### What does the proposed API look like?
`echarts.connect(group, options)`

**Comment by 100pah** [comment]
当前版本的联动如果不合要求，只能不使用 `echarts.connect(group, options)` 而是直接用 `on` 和 `dispatchAction` 来实现定制的联动。

因为比较难于猜得到，具体是按什么联动。
所以，我认为，联动，应该有更方便的定制，修改联动的细节，比较好。例如：

```js
echarts.connect(groups, {
    includeEvents: ['showTip'], // 如果有此设定，只联动这些 events。
    makeActionFromEvent: function(event) {
        var action;
        if (event.type === 'showTip') {
           ...
        }
        else {
            action = echarts.makeActionFromEvent(event)
        }
        return action;
    }
});
```

**Comment by SevenOutman** [comment]
> 当前版本的联动如果不合要求，只能不使用 `echarts.connect(group, options)` 而是直接用 `on` 和 `dispatchAction` 来实现定制的联动。

现在我的确是使用 `on` 和 `dispatchAction` 来实现 tooltip 联动的，大致实现如下：
```
echarts.on('mouseover', 'series', function (params) {
  siblings.forEach(function (sibling) {
    sibling.dispatchAction({
      type: 'showTip',
      seriesIndex: params.seriesIndex,
      name: params.name
    });
  });
});

echarts.on('mouseout', 'series', function () {
  siblings.forEach(function (sibling) {
    sibling.dispatchAction({
      type: 'hideTip'
    });
  });
});
```

这样基本实现了我需要的联动，唯独一种情况下存在 bug。当我的图表中存在多个 `series` 时（比如两个 bar 和一个 line），联动会失效，联动图表上没有 tooltip 出现。

**Comment by 100pah** [comment]
@SevenOutman 如果使用的是 `tooltip.trigger: 'axis'` 且有多个 series，
那么 showTip 则可不传 seriesIndex 。
