### ISSUE TITLE
treemap修改二级name与其它一级下的二级name相同时，会触发两个块的重新加载动画

### ISSUE THREAD

**Issue by mrlionline** [apache/echarts#12378]
### Version
4.7.0

### Reproduction link
[https://jsbin.com/kiyizucege/edit?html,output](https://jsbin.com/kiyizucege/edit?html,output)

### Steps to reproduce
点击图标，点击事件中修改了其中一个name，但两个区块同时执行重新加载的动画

### What is expected?
修改的哪个，哪个执行动画，其它未改变的不执行动画

### What is actually happening?
name相同就会执行动画，这样会产生歧义，让人感觉其它块也发生了改变

**Comment by 100pah** [comment]
There is one tricky way but works:

https://jsbin.com/kuyosiwibu/1/edit?html,output

(Use some extra id to distinguish the same names but filtered by label formatter).
