### ISSUE TITLE
two tags overlapped

### ISSUE THREAD

**Issue by lubimow** [apache/echarts#12382]
### What problem does this feature solve?
I am using your card and I have a problem.
In Kiev and the Region, are numbers superimposed on each other?
How to fix it?
screenshot link:

### What does the proposed API look like?
https://ibb.co/ZWH1dZh
https://ibb.co/Bf62gdh

**Comment by 100pah** [comment]
Missing necessary info.

Label overlapping issue will be covered in v5.0.
There might be some workaround but depends on how the `option` looks like.
