### ISSUE TITLE
dataZoom拖拽时，x轴区域预设的颜色错乱

### ISSUE THREAD

**Issue by nanayang** [apache/echarts#12391]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xdpYC6-Z5y](https://gallery.echartsjs.com/editor.html?c=xdpYC6-Z5y)

### Steps to reproduce
左右拖拽底部

### What is expected?
左右拖拽进度条的时候，只有xData1这条数据会有红色背景及红色文字预警。xData1这条数据不在当前区域时，红色背景及红色文字隐藏。

### What is actually happening?
拖拽后，大部分情况，每个区域的第一个数据都会有红色背景及红色文字预警。偶尔会出现没有红色背景，或者红色背景出现在其他柱状图后面。

**Comment by pissang** [comment]
x 轴的类目不要有重复的数据，不然在索引的时候没法找到正确的值

**Comment by nanayang** [comment]
splitArea里面的color，没有办法用formatter和function吧。x轴的类目修改成不重复的数据，还是一样的。

**Comment by pissang** [comment]
@nanayang 看了 https://gallery.echartsjs.com/editor.html?c=xdpYC6-Z5y 你新修改的版本就没这个问题，splitArea  不影响

**Comment by ShiChenCong** [comment]
遇到同样的问题，在xAxis.axisLabel.color里依据index判断显示的颜色，使用datazoom slider后，比如设置拖动块的区域是0-4，那么index是0-4，但是拖动到后面，索引还是0-4，导致颜色错乱

**Comment by boswellgao** [comment]
@pissang  has this bug fixed in 5.2.2 ?  in my work, I found this bug again ? anything else can i do ? and when reSet the splitArea in  setOption at dataZoom callback, the render become slow.
