### ISSUE TITLE
Add week number support for calendar chart

### ISSUE THREAD

**Issue by isarobeadot** [apache/echarts#12390]
### What problem does this feature solve?
It would be appreciated that Calendar chart type supports week numbers.

### What does the proposed API look like?
The proposed API looks so god, but I would like to this feature be developed.

**Comment by Ovilia** [comment]
@isarobeadot Hi. What do you need this week number for? Something like `yearLabel`, `monthLabel` now?

**Comment by isarobeadot** [comment]
@Ovilia Hi. Yes, it would be something like `yearLabel` and `monthLabel`.

**Comment by Ovilia** [comment]
Marked as a new feature.

**Comment by im-what-im** [comment]
+1
