### ISSUE TITLE
sankey图能让指定节点固定位置吗？或者在垂直方向上从中间向外扩散? 

### ISSUE THREAD

**Issue by 369pie** [apache/echarts#12417]
### What problem does this feature solve?
能优化视觉体验、用于实时监控一些数据的情况下、节点位置变化太大过渡不自然

### What does the proposed API look like?
data:[  {position:{x: 1, y:1}   }]

**Comment by pwpow** [comment]
> ### What problem does this feature solve?
> 能优化视觉体验、用于实时监控一些数据的情况下、节点位置变化太大过渡不自然
> 
> ### What does the proposed API look like?
> data:[ {position:{x: 1, y:1} }]

想请教一下，有解决方案了吗
