### ISSUE TITLE
webgl 3dbar可以使用图片作为柱体的贴图吗

### ISSUE THREAD

**Issue by mengyunlong** [apache/echarts#12413]
### What problem does this feature solve?
可以通过图片将3d柱体包装成需要的展示的样式，比如建筑等

### What does the proposed API look like?
能通指定图片的路径，重复方式，重复方向

**Comment by pissang** [comment]
可以试试用 detailTexture 设置

**Comment by mengyunlong** [comment]
感谢您的解答，我已经尝试使用了 detailTexture 的配置，在bar3D的根节点下作了如下配置：

**Comment by mengyunlong** [comment]
感谢您的解答，我已经尝试使用了 detailTexture 的配置，在bar3D的根节点下作了如下配置：
`{
                    name: 'bar3D',
                    type: 'bar3D',
                    coordinateSystem: 'geo3D',
                    shading: 'realistic',
                    realisticMaterial:{
                        detailTexture: 'assets/test.jpg'
                    },
...
}`
设置 后，我在控制台发现： assets/test.jpg 确实被正常加载了，但柱体的颜色仅仅变深了，并没有出现在柱体上显示图片的效果，我理想中的效果类似 globe 的 baseTexture 的属性，不知道是不是我哪里配置的不对？
另外在后期的版本中，bar3D中可以添加关于柱体线条的设置吗？ 例如颜色，透明度等
再次打扰，深感抱歉

**Comment by pissang** [comment]
@mengyunlong 可以看下那你那的显示效果吗？

**Comment by mengyunlong** [comment]
您好，我的理解中一个立体的柱子应该是由8个顶点构成的，我所说的柱体线条就是指相邻顶点间的连线，一个立体柱子应该是有12根这样的线条的，关于这种线条在后期的版本中是否可以单独进行属性的设置吗？
关于 bar3D的detailTexture  的配置，没有产生类似 globe 的 baseTexture 的效果，这个是我配置的问题，还是目前echarts bar3D没有类似 globe 的 baseTexture这样的参数？
谢谢

**Comment by pissang** [comment]
> 您好，我的理解中一个立体的柱子应该是由8个顶点构成的，我所说的柱体线条就是指相邻顶点间的连线，一个立体柱子应该是有12根这样的线条的，关于这种线条在后期的版本中是否可以单独进行属性的设置吗？

这个目前不能实现

> 关于 bar3D的detailTexture 的配置，没有产生类似 globe 的 baseTexture 的效果，这个是我配置的问题，还是目前echarts bar3D没有类似 globe 的 baseTexture这样的参数？

我不太清楚你想要实现的效果以及你现在的效果

**Comment by mengyunlong** [comment]
您好 我想让bar3D柱体的表面上展示我自己的图片，而不在是显示颜色，我的配置如下
` shading: 'realistic',
realisticMaterial:{
    detailTexture: 'assets/scale9.png'
}`
配置完成后，柱体表面并没有出现我的图片，仅仅是柱体的颜色变深了，并且在某些角度下出现了阴影，第一张图片为添加上述配置代码的效果，第二张图片为没有添加上述代码的效果
![2020-4-17 12-23-47](https://user-images.githubusercontent.com/5801829/79532367-750e8100-80a7-11ea-83b0-f05e236cd930.jpg)
![2020-4-17 12-22-44](https://user-images.githubusercontent.com/5801829/79532420-a1c29880-80a7-11ea-969a-4154dc8eca88.jpg)
柱体上应该怎么样才能展示出我自定的图片呢
