### ISSUE TITLE
When used dataZoom - adding data dynamically leaves lines.

### ISSUE THREAD

**Issue by RomanOlegovich** [apache/echarts#12433]
### Version
4.7.0

### Steps to reproduce
Zoom in and look on the left on the chart.
https://gallery.echartsjs.com/editor.html?c=xr7FKkQQbr&v=1

### What is expected?
Clean chart, without incorrect lines.

### What is actually happening?
When zoom in chart leaves lines.

**Comment by yufeng04** [comment]
Could you provide a demo for the issue either with [https://jsfiddle.net/ovilia/n6xc4df3/](https://jsfiddle.net/ovilia/n6xc4df3/) or [https://gallery.echartsjs.com/editor.html](https://gallery.echartsjs.com/editor.html).

**Comment by RomanOlegovich** [comment]
> Could you provide a demo for the issue either with https://jsfiddle.net/ovilia/n6xc4df3/ or https://gallery.echartsjs.com/editor.html.

https://gallery.echartsjs.com/editor.html?c=xr7FKkQQbr&v=1

**Comment by RomanOlegovich** [comment]
![Capture](https://user-images.githubusercontent.com/46935437/81769027-bd825880-9506-11ea-89fb-15fc537c7731.PNG)

**Comment by RomanOlegovich** [comment]
If set series-line  "animation:false" - problem resolved.
