### ISSUE TITLE
Labels do overlap with alignTo edge

### ISSUE THREAD

**Issue by strebl** [apache/echarts#12443]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/0e5Lkpyr/2/](https://jsfiddle.net/0e5Lkpyr/2/)

### Steps to reproduce
- Open Example
- Look at the labels

### What is expected?
`avoidLabelOverlap: true` should avoid label overlapping.

### What is actually happening?
It doesn't avoid label overlapping.

---
It works, if the remove `alignTo: 'edge'` - but that's not what I want.

**Comment by strebl** [comment]
> Hi! We've received your issue and please be patient to get responded. 🎉
The average response time is expected to be within one day for weekdays.

Do you need more information?

**Comment by Ovilia** [comment]
@strebl This means @yufeng04 has confirmed this to be a bug. Thanks for reporting.
