### ISSUE TITLE
Echart 折现更新卡顿

### ISSUE THREAD

**Issue by BUERGER123** [apache/echarts#12449]
### Version
4.7.0

### Steps to reproduce
```js
option = {
    title: {
        text: '动态数据   时间坐标轴'
    },
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate()   '/'   (date.getMonth()   1)   '/'   date.getFullYear()   ' : '   params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }]
};

setInterval(function () {

    for (var i = 0; i < 5; i  ) {
        data.shift();
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 1000);
```
### What is expected?
大数据量更新时界面流畅

### What is actually happening?
卡顿

---
界面中有两个的曲线图
第一个图数据量大约是0-2000，5秒更新一次
第二个图数据量大约是0-30000，1秒更新一次
架构使用的是vue echart
每次更新使用的是setOption(data)
把鼠标放在第一个图中，第二个图触发更新时，第一个图也很卡，影响操作

**Comment by pissang** [comment]
@BUERGER123 建议先用这个代码写个最简单的例子排查下是不是 echarts 的问题

vue 和 echarts 结合使用的时候需要注意不要把 echarts 实例或者配置项挂到 vue 下面，vue 会深度遍历监听所有属性，数据量一下就卡了

**Comment by BUERGER123** [comment]
你好，我代码结构大概是这样：export default Vue.extend({
&nbsp; &nbsp; &nbsp; &nbsp; data(){return{}},


&nbsp; &nbsp; &nbsp; &nbsp; methods:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;functionA(){&nbsp; data = update_data() }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;................
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;functionN(){}


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;build_chart(){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;let mychart = this.$echarts.init()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;option = {.........}
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;mychart.option(option)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;setInterval(function () {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;myChart.setOption({
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;series: [{data: data}]});
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;}, 1000);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp;},


&nbsp; &nbsp; &nbsp; &nbsp;mounted(){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;build_chart();
&nbsp; &nbsp; &nbsp; &nbsp;},
})
麻烦帮我看下哪里需要修改






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 下午4:28
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "Avengers"<1198476521@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] Echart 折现更新卡顿 (#12449)





 
@BUERGER123 建议先用这个代码写个最简单的例子排查下是不是 echarts 的问题
 
vue 和 echarts 结合使用的时候需要注意不要把 echarts 实例或者配置项挂到 vue 下面，vue 会深度遍历监听所有属性，数据量一下就卡了

**Comment by BUERGER123** [comment]
export default Vue.extend({
data(){return{}},


methods:{
functionA(){&nbsp; data = update_data() }
................
functionN(){}


build_chart(){
let mychart = this.$echarts.init()
option = {.........}
mychart.option(option)
setInterval(function () {
myChart.setOption({
series: [{data: data}]});
}, 1000);
}
},


mounted(){
build_chart();},
})
麻烦帮我看下哪里需要修改






------------------ 原始邮件 ------------------
发件人: "Yi Shen"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 下午4:28
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 
抄送: "Avengers"<1198476521@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/incubator-echarts] Echart 折现更新卡顿 (#12449)





 
@BUERGER123 建议先用这个代码写个最简单的例子排查下是不是 echarts 的问题
 
vue 和 echarts 结合使用的时候需要注意不要把 echarts 实例或者配置项挂到 vue 下面，vue 会深度遍历监听所有属性，数据量一下就卡了

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2 
这个例子的动态数据是不卡的，所以还是检查自己 vue 相关框架的原因。
