### ISSUE TITLE
如何得到柱状图柱子的宽度和柱子间的间隙宽度

### ISSUE THREAD

**Issue by yanshuai** [apache/echarts#12469]
### What problem does this feature solve?
如何得到柱状图柱子的宽度和柱子间的间隙宽度的像素值？

### What does the proposed API look like?
看下有没现成的方案能获取得到

**Comment by Ovilia** [comment]
没有接口，但是可以自己计算得到。先计算出绘图区域的宽度，就是 `grid.width` 或者如果没有设的话，看文档默认值是 canvas 宽度减去 `grid.left` 和 `grid.right`。然后除以有多少组数据，这个宽度的 https://echarts.apache.org/zh/option.html#series-bar.barWidth （默认 60%），也就是说间隙是 40%。
