### ISSUE TITLE
Shadows Appear in Lines Series When In Large Zoom Level with baidu map extension

### ISSUE THREAD

**Issue by xianshenglu** [apache/echarts#12461]
### Version
4.7.0

### Reproduction link
[https://codepen.io/xianshenglu/pen/YzyGWLR](https://codepen.io/xianshenglu/pen/YzyGWLR)

### Steps to reproduce
- open the link https://codepen.io/xianshenglu/pen/YzyGWLR
- wait unitl the demo loaded
- You can see the shadow between two lines
- If you zoom out, the shadow would disappear

### What is expected?
The shadow shouldn't exist

### What is actually happening?
The shadow exists when the zoom level is very large.

---
- Different shadows may appear on different computers. For example, between mac chrome  80.0.3987.163 and windows chrome 80.0.3987.132.
- Different shadows may appear when you zoom in and zoom out.

**Comment by xianshenglu** [comment]
![image](https://user-images.githubusercontent.com/23273077/79736027-c3cc4d00-832b-11ea-8df8-bd151ad5c0e9.png)

And if you zoom out

![image](https://user-images.githubusercontent.com/23273077/79736069-d5adf000-832b-11ea-89e4-575d4fec32a1.png)

**Comment by Ovilia** [comment]
It seems to do with `series.lineStyle.width`. Not sure if this is a bug.

**Comment by xianshenglu** [comment]
any progress? @Ovilia ?
