### ISSUE TITLE
大数据量面积图的导出

### ISSUE THREAD

**Issue by hehetiger** [apache/echarts#12477]
### What problem does this feature solve?
目前官方实例中的大数据量面积导出为图片时如何导出全部数据？使用官方给出的getDataURL方法的话只能导出界面上展示出来的那一部分数据。例如：x轴坐标一共是1-100，由于缩放只显示了1-10，目前希望哪怕界面上缩放只显示了1-10的数据，导出时也可以把1-100全部导出

### What does the proposed API look like?
大数据量面积导出为图片时，哪怕界面上是缩放的只显示了部分数据，导出也可以导出全部数据

**Comment by Ovilia** [comment]
试试先禁止动画，然后 setTimeout 再导出？

**Comment by pissang** [comment]
@hehetiger 只能在导出前把 dataZoom 设置成 0 - 100，导出后再设回 0 - 10
