### ISSUE TITLE
series.itemStyle.shadowColor不支持回调函数吗？

### ISSUE THREAD

**Issue by FHyacinth** [apache/echarts#12482]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap](https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/34297250/80057129-6f59e500-8558-11ea-8b52-150921df0cfd.png)

api上显示shadowColor的支持的格式同color，想在shadowColor写 回调函数，但是color的回调函数会执行，但shadowColor的回调函数并未执行；
可在这个例子里面自行加上回调函数测试：
https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### What is expected?
可以支持回调函数

### What is actually happening?
不支持

**Comment by susiwen8** [comment]
Not support callback for shadowColor, description is misleading, but `type` is correct

**Comment by pissang** [comment]
We are planning to add callback support for the whole itemStyle in the 5.0
