### ISSUE TITLE
Improve theme documentation

### ISSUE THREAD

**Issue by linssen** [apache/echarts#12489]
### What problem does this feature solve?
It's unclear what attributes you may add to a theme to affect the layout of a chart. The example themes don't list every available option, and not all chart options may be altered via the theme.

### What does the proposed API look like?
I'd propose adding the following to the docs:

1. All chart options that may be set from a theme
1. The precedence in which these options are applied (theme < init opts < setOption) etc.
1. Specific options which may _not_ be set via a theme
1. Add all available options to a starter theme, perhaps the light / dark ones, to download as a template

**Comment by pissang** [comment]
Indeed, thanks for the suggestion!

**Comment by linssen** [comment]
I'd be more than happy to help with the en side if I had a list of things 👍

**Comment by linssen** [comment]
@pissang / @susiwen8 I wonder if there are a list of items affected by theming, or is it better to dig through the code? It'd be great to understand which properties in the theme are inherited. Like I say, I'd be more than happy to pitch in the docs if I knew the limitations.

**Comment by pissang** [comment]
Hi @linssen, sorry for the late reply.

The configuration of the theme is very similar to the option. The only difference is series in theme is described in a map.

For example:

A typical option is : 
```js
option = {
  series: [{
     type: 'bar',
     itemStyle: { color:  }
  }]
}
```

In theme, it needs to be:
```js
theme = {
  bar: {
     itemStyle: { color:  }
  }
}
```

Besides this tiny difference, all the configurations in option can be described in theme, it will override the default value provided by echarts. Also, it can be override by the user option.

PS: @Ovilia did a visual theme builder. But currently, the UI is still in Chinese. https://www.echartsjs.com/theme-builder/

**Comment by tbtalbottjr** [comment]
@pissang Your comment is the most helpful bit of information I've found so far. It would be quite helpful for this to be part of the API documentation. But at least I have an idea of how to proceed.
