### ISSUE TITLE
chart.on("click",(n)=>{alert(1)}) dont work on gl3d chart in phone device (android and ios)

### ISSUE THREAD

**Issue by javadrajabi** [apache/echarts#12496]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/javadrajabi/k9bsjeL0/1/](https://jsfiddle.net/javadrajabi/k9bsjeL0/1/)

### Steps to reproduce
var container = document.getElementById('main');
var chart = echarts.init(container);
chart.on("click",(n)=>{
alert(1);
})
must sho alert

### What is expected?
after click or toch gl 3d chart in phone device ,show alert 

### What is actually happening?
but dont show alert.
Although show alert on desktop device.but dont show alert on phone device

---
find this issue on an Android device.
also
this issue just in 3d GL charts .
I checked and i realized that :
chart.on('click'....
this event not work. also this error is from the original library .
you can test it on this link
https://jsfiddle.net/javadrajabi/k9bsjeL0/1/

Test once with your phone, once with your computer

**Comment by HuseyinAkkaya** [comment]
Still no answer :(

**Comment by javadrajabi** [comment]
We are still waiting...

**Comment by Markyza** [comment]
> Test once with your phone, once with your computer

What is your android version?

**Comment by javadrajabi** [comment]
> > Test once with your phone, once with your computer
> 
> What is your android version?

android 8 and ios 13.5
