### ISSUE TITLE
symbolOffset as callback function

### ISSUE THREAD

**Issue by Huxpro** [apache/echarts#12495]
### What problem does this feature solve?
Enabling dynamically adjusting to symbol offsets (pretty much like what EChart had done for symbol size). One example use case would be differentiating two symbols overlapped from a discrete dataset.

### What does the proposed API look like?
`symbolOffset : (val) => { ... }`

**Comment by Huxpro** [comment]
I work around it by using `value` type and floating-point numbers in my things.
Feel free to close if the team found none other use cases of this feature :)

**Comment by plainheart** [comment]
Now the most of series have supported functional `symbol`,  `symbolRotate` and `symbolSize` etc.
 Maybe there will be more options can receive a callback function as the parameter in 5.0.0.
We can expect positively for that. :)
