### ISSUE TITLE
Axis min and max values set by functions are not equal to slider min and max values

### ISSUE THREAD

**Issue by Szlast** [apache/echarts#12507]
### Version
4.7.0

### Reproduction link
[https://www.echartsjs.com/examples/en/editor.html?c=line-draggable](https://www.echartsjs.com/examples/en/editor.html?c=line-draggable)

### Steps to reproduce
1. Go to echarts examples a pick "Try dragging these Points" charts
2. Check that yAxis. max is set on 60 check graph that has Y axis max value of 60 and slider max value is 60.
3. Add function to yAxis.max as it is in documentation max: function (value) { return value.max   20; }

### What is expected?
Y axis max value of graph has 60 value and slider max value is 60.

### What is actually happening?
Y axis max value of graph has 60 value but slider max value is 40 and when you drag it down graph "jumps" do values below 40.

**Comment by wf123537200** [comment]
The ```value.max``` in the yAsix.max formatter function is the ```max(data.y)```, so the max is 20 when ```max: function (value) { return value.max - 20; }```, Seems ok in the example

**Comment by Szlast** [comment]
I attached screen from example.
![Echarts_min_max_slider_issue](https://user-images.githubusercontent.com/32903405/80467649-6a24dd80-893e-11ea-9872-bea8520fcce9.png)
