### ISSUE TITLE
更新主题颜色，需要手动刷新页面后才会显示更换后的主题颜色

### ISSUE THREAD

**Issue by huxiany** [apache/echarts#12506]
### Version
4.7.0

### Steps to reproduce
代码如下：

```
async renderChart() {
    const ECharts = await import(./ECharts");
    const theme = ThemeInfo.currentThemeIsDark() ? "dark" : "macarons";
    const chart = ECharts.default.init(this.divChartRef.current!, theme);

    window.addEventListener("resize", function () {
      chart.resize();
    });

    chart.setOption(this.getChartOption() as EChartOption);
  } 
```

### What is expected?
请帮忙确认是不是bug ?
若不是，那可否提供具体的代码实例作为参考呢？谢谢！

### What is actually happening?
尝试过使用dispose()，但并未解决此问题。

**Comment by 100pah** [comment]
It's by design. 
After theme updated, it needs to dispose the current chart instance and re-init a new chart.
