### ISSUE TITLE
请问如何避免当echartgl渲染时整个网页卡主

### ISSUE THREAD

**Issue by Sprlia** [apache/echarts#12516]
### Version
4.6.0

### Steps to reproduce
大数据量三维曲面图进行渲染和更新时，会很卡，这种情况如何避免整体网页也因此卡主？
图形组件：三维曲面图
数据量：十万以上
数据策略：每秒钟更新一部分数据，15秒会把所有的数据更新一遍（目前用的setOption进行数据全量设置，是否有其他方式进行更好的数据更新？）

### What is expected?
除了echart其他页面元素正常运行，
或者有没有优化建议？

### What is actually happening?
页面卡死

**Comment by mzy2240** [comment]
我也有同样的问题，只不过对象是2D canvas. 目前正在研究如何利用offscreencanvas来防止UI阻塞。
