### ISSUE TITLE
Show total data count next to legend labels

### ISSUE THREAD

**Issue by BrianGilbert** [apache/echarts#12513]
### What problem does this feature solve?
You currently have to manually add numbers to see what the total for a given data series is across a whole chart, it would be great if there was a way to append calulated totals to legend labels.

I could try and do this programatically but if I add the count as part of the label the label goes away because it no longer matches the series name.

### What does the proposed API look like?
I'd propose adding something like the following to the legend part of the API:
```
showCount: true
```

**Comment by 100pah** [comment]
If adding an option `showCount: true` and make built-in implement, it become a "common feature" and need to define how it look link and how to configure its style. It's not a easy work I am afraid.
I think it's probably better for user to make the `count of data` displayed in like `text component` or `series label` or `custom series`, which is more flexible.

**Comment by jatin-caizin** [comment]
Can we add custom data to bar and line chart legend irrespective of series object?

**Comment by B3Kay** [comment]
I'd like to do this aswell.
