### ISSUE TITLE
echarts在微信小程序页面上影响页面滚动

### ISSUE THREAD

**Issue by summer-yyyn** [apache/echarts#12522]
### Version
4.7.0

### Steps to reproduce
在微信小程序端使用Echarts图表，当指头移到图表上，页面就无法滚动了。
请问有没有解决的办法？非常感谢！

### What is expected?
期望在小程序端可以正常滑动

### What is actually happening?
微信小程序端使用Echarts图表，页面上有很多图表，图标加载完，滑动页面时候，手指放在图标上，导致页面不能滑动

**Comment by summer-yyyn** [comment]
ios端的问题，android没有这个问题

**Comment by Ovilia** [comment]
在图表内触摸是会阻止滑动的，这是符合预期的，要滚动页面的话，在两边留白。参见「页面不阻塞滚动」的例子。

**Comment by summer-yyyn** [comment]
请问「页面不阻塞滚动」的例子是在哪里呢？文档里没有找到

**Comment by 100pah** [comment]
是否有具体的配置项 `option` 来看看是配置能解决的还是需要修改程序？不同的图表的情况有些不同。

**Comment by hexiaojun5233** [comment]
> 请问「页面不阻塞滚动」的例子是在哪里呢？文档里没有找到

请问解决了吗 我也遇到这问题了

**Comment by Ovilia** [comment]
@summer-yyyn @hexiaojun5233 https://github.com/ecomfe/echarts-for-weixin/tree/master/pages/move

**Comment by zhiqiangx** [comment]
echats是不是监听了Safari的bounce导致页面不能滚动呢？
