### ISSUE TITLE
关于Echarts多个表格联动，添加多个legend后，关闭第一个指标时，联动实效。

### ISSUE THREAD

**Issue by StoneMa** [apache/echarts#12527]
### Version
4.7.0

### Reproduction link
[https://codepen.io/maysh/pen/YzyxXrJ](https://codepen.io/maysh/pen/YzyxXrJ)

### Steps to reproduce
直接打开复现链接中查看即可，第二张图表中，取消勾选all_oStor这一项的数据，再查看一下鼠标的联动效果，可以发现，联动实效。

### What is expected?
预期两个图表的联动应该不受选择了那些数据项的影响

### What is actually happening?
实际当第二张图表不选择all_oStor这一项时，联动实效。

---
无

不取消第二张表中 all oStor ,两个表有联动效果：
![image](https://user-images.githubusercontent.com/6917909/80573628-de40ad80-8a32-11ea-9be6-052686fe7078.png)
取消勾选all oStor这一项数据：
![image](https://user-images.githubusercontent.com/6917909/80573702-09c39800-8a33-11ea-834e-1a42580a63f7.png)

**Comment by 100pah** [comment]
The `connect` feature, by default, should better ignore series index/name in `trigger: axis` tooltip action.

**Comment by StoneMa** [comment]
> The `connect` feature, by default, should better ignore series index/name in `trigger: axis` tooltip action.

it doesn't work.

**Comment by Ovilia** [comment]
@StoneMa Yes, @100pah meant that this feature should be improved.
