### ISSUE TITLE
饼图的引导线能不能往同一个方向呢

### ISSUE THREAD

**Issue by yishangtanhuan** [apache/echarts#12525]
### Version
4.7.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x1r0Pqnp-I](https://gallery.echartsjs.com/editor.html?c=x1r0Pqnp-I)

### Steps to reproduce
非bug

### What is expected?
饼图引导线指向同一个方向

### What is actually happening?
没有设置引导线方向的属性

---
与https://github.com/apache/incubator-echarts/issues/10510 问题一样

**Comment by 100pah** [comment]
It probably depends on "how many sectors there are and how they are laid out".
If a sector is on the right, but force the label displayed on the left side of the canvas, the "guide line" would be cross the pie chart, which probably don't look good
