### ISSUE TITLE
树图希望支持设置node间距和连线长度

### ISSUE THREAD

**Issue by woowgaga** [apache/echarts#12532]
### Version
4.7.0

### Steps to reproduce
非bug

### What is expected?
希望支持2.0版本的nodePadding和layerPadding，可以对node之间的间距和连线长度进行设置

### What is actually happening?
现在不支持，导致节点很少时，图表很开，很丑

**Comment by nelsonbbarriento23** [comment]
Ni

Thanks 😊🙏
