### ISSUE TITLE
label formatter’ parameter  doesn't support Object

### ISSUE THREAD

**Issue by vnues** [apache/echarts#12535]
### Version
4.2.1

### Steps to reproduce
非bug

### What is expected?
希望X轴label的formatter回调函数参数value支持Object

### What is actually happening?
现在X轴label的formatter函数参数不支持Object，所以做hover显示小弹框无法拿到当前传递的数据，只能通过凭借value-index形式去获取

**Comment by susiwen8** [comment]
We are planning to support callback for entire label in 5.0
