### ISSUE TITLE
添加绘制气象探空图

### ISSUE THREAD

**Issue by secoworld** [apache/echarts#12551]
### What problem does this feature solve?
能够绘制气象探空数据，用作气象分析以及地球科学的可视化功能

### What does the proposed API look like?
数据类型是：
```json
"Station_Name": "xxx",
    "Station_Id_C": "3344",
    "Lat": "23.44",
    "Lon": "123.44",
    "Alti": "10.0",
    "data": [
        [
            "1020",
            "20",
            "3.8",
            "1.5",
            "25",
            "14"
        ],
        [
            "1000",
            "222",
            "2.8",
            "0.6",
            "25",
            "19"
        ],
    ]
```

希望绘制出来的图形是这样的: ![气象探空数据](https://pic3.zhimg.com/v2-2c932e319e236aa330b4e1db36c04096_b.jpg)

图像的链接为：[气象探空数据](https://pic3.zhimg.com/v2-2c932e319e236aa330b4e1db36c04096_b.jpg)

**Comment by 100pah** [comment]
Could be implemented by combine [line series](https://echarts.apache.org/zh/option.html#series-line) and [custom series](https://echarts.apache.org/zh/option.html#series-custom) and [cartesian coordinate system](https://echarts.apache.org/zh/option.html#grid) and [polar coordinate system](https://echarts.apache.org/zh/option.html#polar)
