### ISSUE TITLE
tooltip box didn't be shown while click zero data

### ISSUE THREAD

**Issue by Shelley** [apache/echarts#12559]
### Version
4.7.0

### Steps to reproduce
1. open line chart example https://echarts.apache.org/examples/en/editor.html?c=line-stack
2. make sure there is a zero in data, e.g. [0, 132, 101, 134, 90, 230, 210]
3. set tooltip triggerOn "click"
3. mouse click the zero data (just the data circle, not other area)

### What is expected?
the clicked circle become bigger， tooltip box should be shown

### What is actually happening?
the clicked circle become bigger， BUT there is no tooltip box.

**Comment by quillblue** [comment]
Create a minium reproduction example with following options
`option = {
    tooltip: {
        trigger: 'axis',
        triggerOn:'click'
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name: '邮件营销',
            type: 'line',
            data: [0, 132, 101, 0, 90, 230, 210]
        }
    ]
};
`

It seems that this issue will only occurs when the data point is at **zero point** of coord (Since the 0 data in Thu works fine, and it also works fine if we remove `boundaryGap ` setting) and when setting trigger as _axis_.

**Comment by Shelley** [comment]
@quillblue many thanks for your quickly reply, in fact we used the echarts in a mobile application, and we need set the boundaryGap as false to make the chart looks better, is it possible to fix this? many thanks again
