### ISSUE TITLE
Axis label alignments cause unexpected shifts

### ISSUE THREAD

**Issue by pierrebonny** [apache/echarts#12565]
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/93nmwqjz/](https://jsfiddle.net/93nmwqjz/)

### Steps to reproduce
Check the linked jsfiddle

### What is expected?
yAxis labels should be aligned to left without the unexepected shift hiding it behind the chart

### What is actually happening?
labels are hidden behind the graph

---
The problem is the same with vertical align

**Comment by Ovilia** [comment]
I believe this is not a bug. When you set `align` to be `'left'`, you need to set [`margin`](https://echarts.apache.org/en/option.html#yAxis.axisLabel.margin) to be bigger, like 100. Because labels are aligned to margin.

**Comment by pierrebonny** [comment]
Thanks for the answer, that's what I though about but it is not (for me) a good solution. I mean that you have to calculate that margin depending on labels font size and width. According to me it would be better to be able to align to left starting from the left of the graph. Margin could be use but only to add some custom space. Currently if you work with dynamic values you just can't use that feature.

**Comment by Ovilia** [comment]
@pierrebonny Thanks for your suggestion. I will mark this as an improvement and see if the community can help. For now, I'm afraid you have to mannually set this value.

**Comment by pierrebonny** [comment]
Thanks again for your listening. Hope that feature will be available one day. Anyway congratulations for your work on that nice library. Good luck for the future of echarts !
