### ISSUE TITLE
How to pan/zoom graph series in javascript?

### ISSUE THREAD

**Issue by travis1111** [apache/echarts#12567]
### Version
4.7.0

### Steps to reproduce
We need to find a way to search the node by name, we can locate the position of the node, and would like to pan the view so that the node is centered on the screen.  We tried view.updateView and view.updateLayout, but it is not working.

What is the correct way to pan / zoom the view from js code?

thanks

### What is expected?
see above

### What is actually happening?
not working

**Comment by Ovilia** [comment]
Call `chart.setOption` and set `series.zoom` and `series.center`. They are missing in the document, I [made a commit](https://github.com/apache/incubator-echarts-doc/commit/8d001e86a2190b9ebdc2f344a7820a563ed9299a) but it's not online yet.
