### ISSUE TITLE
关系图Graph中当连线的source和target为同一节点时，不能展示出效果

### ISSUE THREAD

**Issue by dongleizi** [apache/echarts#12573]
### Version
4.6.0

### Steps to reproduce
关系图Graph中当连线link的source和target为同一节点时，不能展示出效果，希望给出解决方案或者优化展示方式。

### What is expected?
能在节点上以曲线的方式或者其他的合理方式展示出来

### What is actually happening?
看不出来节点自身有连线

**Comment by Ovilia** [comment]
目前还没有支持同一个点的线

**Comment by Ovilia** [comment]
Please follow #15405
