### ISSUE TITLE
希望能增加調整force layout圖個別線段長度的支持

### ISSUE THREAD

**Issue by ian08005454** [apache/echarts#12580]
### What problem does this feature solve?
使用force layout製作人物關係圖時，需要用調整個別長度，讓用者可以一目了然他們之間的關係是否親近，也更好運用於ML 和分群

### What does the proposed API look like?
在link style 中加入 LinkLength 的屬性，並使用series-graph.force. edgeLength 去限定範圍，如下圖
```javascript
"links": [ 
        {  
            "source": 0,
            "target": 1, 
           "linkLength":10
        },  
        {  
            "source": 0,  
            "target": 2 ,
           "linkLength":20 
        }]

```

**Comment by Ovilia** [comment]
请问和现在的 series-graph.force. edgeLength 区别是什么？为什么不能直接用这个？

**Comment by ian08005454** [comment]
因為现在的 series-graph.force. edgeLength  區間 就算搭配 series-graph.force. repulsion 和series-graph.force. gravity 都會對全局造成影響，但我希望能表達出朋友中要好與普通朋友的差別，所以希望能個別自訂線段長度，或是把 series-graph.force. edgeLength 改成支援函式像d3的linkDistanceuu也是可以:
```javaScript
.linkDistance(function(link) { return link.distance }) 
```

**Comment by Ovilia** [comment]
了解了
