### ISSUE TITLE
 How to set the height of datazoom

### ISSUE THREAD

**Issue by chm74** [apache/echarts#12582]
### What problem does this feature solve?
dataZoom 组件:如果所需要的展示的图表本身占用的位置较低，而现在dataZoom本身的高度太高，就会导致展示图表本身的内容显示更小。

### What does the proposed API look like?
可以给dataZoom，添加一个设置高度的属性

**Comment by Ovilia** [comment]
For anyone who wish to fix this issue:
It's probably related to https://github.com/apache/incubator-echarts/blob/master/src/component/dataZoom/SliderZoomView.js#L38
You should provide a new option like `fillterSize` and replace the constant `DEFAULT_FILLER_SIZE`.

**Comment by zhangzhonghe** [comment]
@Ovilia 我发现已经有相关属性了，文档里面没写。
![1588954724(1)](https://user-images.githubusercontent.com/38434641/81426112-5291f400-918b-11ea-9e29-7129a8412a8d.png)

**Comment by chm74** [comment]
好的，已经设置成功。谢谢您的解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhangzhonghe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 凌晨0:24
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"陈慧敏"<869729893@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts]  How to set the height of datazoom (#12582)





 
@Ovilia 我发现已经有相关属性了，文档里面没写。

**Comment by kevalbhatt** [comment]
Is this issue fixed? if not can I work on this, I have the solution.

**Comment by e-cloud** [comment]
@kevalbhatt it's fixed. There is an undocumented property `height` for slider

**Comment by plainheart** [comment]
@e-cloud Would you mind helping add this property to the documentation repository? https://github.com/apache/echarts-doc

**Comment by plainheart** [comment]
Fixed in apache/echarts-doc#198
