### ISSUE TITLE
Echarts - Line chart - Increase chart height and width on clicking graphic group elements

### ISSUE THREAD

**Issue by Nagasai-Aytha** [apache/echarts#12602]
### Version
4.1.0-release

### Reproduction link
[https://stackblitz.com/edit/angular-ngx-echarts-wjw1vw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-ngx-echarts-wjw1vw?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Create Line chart 
2. Add graphic group elements- rectangle with text on chart
3. Add click to rectangle to update width and height of chart
4. No change in height or width using grid parameter of options 

### What is expected?
Update chart height and width on clicking graphic group elements- rect and text on click

### What is actually happening?
No change in chart width and height on click

---
No related dataset limit issue ( tried with 15- 100 records of data) and for reference I am working on dataset of around 50 -100k

**Comment by plainheart** [comment]
Maybe it's a bug of `ngx-echarts` plugin since it seems to be working well if we call `setOption` manually in `click` callback function. This looks like that the plugin doesn't refresh the chart automatically after its option has been changed.

**Comment by Nagasai-Aytha** [comment]
Yes.. chart is not getting updated automatically  but on opening developer
tools, I see that height is changing.

Till I open developer tools, there is no change in height.

Trying to find any workaround to refresh/reload to fix this issue
