### ISSUE TITLE
Pie chart labels are gotting splitted with \n in formatter in react-native-webview

### ISSUE THREAD

**Issue by shubhamtakode** [apache/echarts#12609]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=pie-rich-text](https://echarts.apache.org/examples/zh/editor.html?c=pie-rich-text)

### Steps to reproduce
Open specified link in react-native-webview. You will see all the formatting done for label is messed up

### What is expected?
It should work in react-native-webview as it does in other browsers.

### What is actually happening?
Label formatting is breaking

**Comment by pissang** [comment]
Can you post a screenshot?

**Comment by shubhamtakode** [comment]
> Can you post a screenshot?

![IMG_20200528_174430 978](https://user-images.githubusercontent.com/9693451/83140046-093e2000-a10b-11ea-95c7-42712e3c032c.jpg)
`const option = {

    series: [ {
        name: 'Trade Register Statuses',
        type: 'pie',
        radius: [20, 80],
        center: ['50%', '50%'],
        roseType: 'area',
        itemStyle: {

            shadowBlur: 200,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
        },
        animationType: 'scale',
        animationEasing: 'elasticOut',
        animationDelay: function (idx) {
            return Math.random() * 200;
        },
        label: {
            formatter: ['{b| {b}}', '{c| {c}}'].join('\n'),
            show:true,
            distanceToLabelLine : 2,
            textStyle: {
                wordBreak:'break-all'
            },
            rich: {
                b: {
                    fontSize: 15,
                    color: themeColors.white,

                },
                c:{
                    fontSize: 20
                }
            }
        },
        labelLine: {
            lineStyle: {
                color: themeColors.cardDark,
                width: 2
            }
        },
        data: [
            {value: 4, name: 'Pending', triggerEvent: true,  },
            {value: 5, name: 'Completed', triggerEvent: true},
            {value: 1, name: 'Confirmed', triggerEvent: true},

        ],
        emphasis: {
            label: {
                formatter: ['{b| {c}}'].join('\n'),
            },
            itemStyle: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
            }
        }
    }]
};`

**Comment by 100pah** [comment]
@shubhamtakode Is the screenshot come from react-native-webview?
I am still not sure what is the "messed up label" from the screenshot.

**Comment by shubhamtakode** [comment]
> @shubhamtakode Is the screenshot come from react-native-webview?
> I am still not sure what is the "messed up label" from the screenshot.

Yes, check formatter 'formatter: ['{b| {b}}', '{c| {c}}'].join('\n')'. Im want to that number and text on seperate lines.
