### ISSUE TITLE
Add border type for style in render item of custom series.

### ISSUE THREAD

**Issue by nguyencuongabcxyz** [apache/echarts#12616]
### What problem does this feature solve?
For itemStyle of custom series, we have borderType having "solid", "dashed" as its value. But in the style of renderItem method, we do not have the same properties.

### What does the proposed API look like?
I propose we add a property named "lineType" which does the same thing with borderType in the style object of renderItem method.

**Comment by plainheart** [comment]
Now there is [series-custom.itemStyle.borderType](https://echarts.apache.org/en/option.html#series-custom.itemStyle.borderType) for specifying the type of border for all.
Do you want to specify a different `borderType` for each item in `renderItem` callback function or make `borderType` functional?

**Comment by nguyencuongabcxyz** [comment]
> Now there is [series-custom.itemStyle.borderType](https://echarts.apache.org/en/option.html#series-custom.itemStyle.borderType) for specifying the type of border for all.
> Do you want to specify a different `borderType` for each item in `renderItem` callback function or make `borderType` functional?
> Does any one think which scheme will be better?

**Comment by nguyencuongabcxyz** [comment]
> Now there is [series-custom.itemStyle.borderType](https://echarts.apache.org/en/option.html#series-custom.itemStyle.borderType) for specifying the type of border for all.
> Do you want to specify a different `borderType` for each item in `renderItem` callback function or make `borderType` functional?
> Does any one think which scheme will be better?

I see that all the properties in [series-custom.itemStyle](https://echarts.apache.org/en/option.html#series-custom.itemStyle) have corresponding properties in `renderItem` callback function style except `borderType`. e.g. `borderColor` has the same meaning as `stroke`, `color` has the same meaning as `fill` but I can not find a corresponding property for `borderType` in the style of `renderItem` callback function. It is weird, isn't it? So I want to have a `lineType` to specify a different `borderType` for each item and I think it is reasonable.

**Comment by Ovilia** [comment]
@nguyencuongabcxyz Do you mean you wish https://echarts.apache.org/en/option.html#series-custom.renderItem.return_path.style to support `lineType`?

**Comment by nguyencuongabcxyz** [comment]
> @nguyencuongabcxyz Do you mean you wish https://echarts.apache.org/en/option.html#series-custom.renderItem.return_path.style to support `lineType`?

Yes. Also for other **return_** . I have found a workaround by using `lineDash` property with some special values. But I think it is ideal to have a `lineType` property with the same values as `borderType` property.

**Comment by 100pah** [comment]
@nguyencuongabcxyz 

`lineDash` can be used for this case, like:
```js
function renderItem(params, api) {
    var yValue = api.value(2);
    var start = api.coord([api.value(0), yValue]);
    var size = api.size([api.value(1) - api.value(0), yValue]);
    var style = api.style();

    return {
        type: 'rect',
        shape: {
            x: start[0] + 1,
            y: start[1],
            width: size[0] - 2,
            height: size[1]
        },
        style: {
            fill: 'red',
            stroke: 'green',
            lineWidth: 3,
            lineDash: [5, 5]
        }
    };
}


```
