### ISSUE TITLE
transform旋转echarts容器后，tooltip无法显示

### ISSUE THREAD

**Issue by xsteamer** [apache/echarts#12610]
### Version
4.7.0

### Reproduction link
[http://jsrun.net/N62Kp](http://jsrun.net/N62Kp)

### Steps to reproduce
调整body的尺寸至高度大于宽度，echarts容器会顺时针旋转90度，然后tooltip就无法显示了

### What is expected?
请问如何正确显示tooltip？

### What is actually happening?
不显示tooltip

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#tooltip.extraCssText 可以设置额外的 CSS，比如在移动端的时候这里设置一个 transform 旋转 90°
