### ISSUE TITLE
【渲染问题】【柱状图】在数据间隔比较小的时候没有问题，但数据间隔为1的时候就有问题了

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [apache/echarts#12626]
### Version
4.7.0

### Steps to reproduce
后续会贴上代码

### What is expected?
平衡页面的布局，达到看上去舒适的效果~

### What is actually happening?
相对较大的值触顶，相对较小的值触底

![Snipaste_2020-05-14_10-06-26](https://user-images.githubusercontent.com/39817817/81885803-b83c1100-95cd-11ea-81e5-e4568fec4401.jpg)

**Comment by TRSK-CONMI** [comment]
使用以下代码：

&lt;!DOCTYPE html&gt;
&lt;!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
--&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;TODO supply a title&lt;/title&gt;
        &lt;meta charset=&quot;UTF-8&quot;&gt;
        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        &lt;script src=&quot;https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;https://cdn.bootcdn.net/ajax/libs/echarts/4.7.0/echarts.common.min.js&quot;&gt;&lt;/script&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div id=&quot;echart1_ele&quot; style=&quot;width: 100%;height:400px;padding-left: 0;padding-right: 5px;&quot;&gt;&lt;/div&gt;

        &lt;script type=&quot;text/javascript&quot;&gt;
            var selectEventArrays_1_name = [&#x27;区域1&#x27;, &#x27;区域2&#x27;, &#x27;区域3&#x27;, &#x27;区域4&#x27;, &#x27;区域5&#x27;];//区域统计条件
            var echart1_ele_data = [132468, 132468, 132468, 132467, 132467];//区域统计-累计用电量data

            $(function () {
                echart1();
            });

            function echart1() {
                echart1_ele();
            }

            function echart1_ele() {
                // 基于准备好的dom，初始化echarts实例
                var echart1_ele = echarts.init(document.getElementById(&#x27;echart1_ele&#x27;));
                // 指定图表的配置项和数据
                var option = {
                    tooltip: {//提示框组件
                        trigger: &#x27;axis&#x27;
                    },
                    legend: {//图例组件
                        data: [&#x27;累计用电量&#x27;] //图例的数据数组。数组项通常为一个字符串，每一项代表一个系列的 name
                    },
                    toolbox: {
                        show: true,
                        feature: {
                            mark: {show: true},
                            dataView: {show: true, readOnly: false},
                            magicType: {show: true, type: [&#x27;line&#x27;, &#x27;bar&#x27;]},
                            restore: {show: true},
                            saveAsImage: {show: true}
                        }
                    },
                    calculable: true,
                    xAxis: [//直角坐标系 grid 中的 x 轴
                        {
                            type: &#x27;category&#x27;,
                            axisLabel: {
                                interval: 0,
                                rotate: 40
                            },
                            data: selectEventArrays_1_name,
                            boundaryGap: [&#x27;5%&#x27;, &#x27;5%&#x27;]//留白大小，坐标轴两边留白
                        }
                    ],
                    yAxis: [
                        {
                            name: &#x27;单位(kWh)&#x27;,
                            type: &#x27;value&#x27;,
                            axisTick: {
                                inside: true
                            },
                            scale: true,
                            axisLabel: {
                                margin: 2,
                                formatter: function (value, index) {
                                    if (value &gt;= 10000 &amp;&amp; value &lt; 10000000) {
                                        value = (value / 10000).toFixed(4) + &quot;万&quot;;
                                    } else if (value &gt;= 10000000) {
                                        value = (value / 10000000).toFixed(7) + &quot;千万&quot;;
                                    }
                                    return value;
                                }
                            }
                        }
                    ],
                    series: [//系列列表
                        {
                            name: &#x27;累计用电量&#x27;, //系列名称，用于tooltip的显示，legend 的图例筛选
                            type: &#x27;bar&#x27;, //类型
                            data: echart1_ele_data, //系列中的数据内容数组。数组项通常为具体的数据项
                            itemStyle: {//上方显示数值
                                normal: {
                                    label: {
                                        show: true, //开启显示
                                        position: &#x27;inside&#x27;, //在上方显示
                                        textStyle: {//数值样式
                                            color: &#x27;black&#x27;,
                                            fontSize: 16
                                        }
                                    },
                                    color: function (params) {
                                        //注意，如果颜色太少的话，后面颜色不会自动循环，最好多定义几个颜色
                                        var colorList = [&#x27;#2584cd&#x27;];
                                        return colorList[params.dataIndex]
                                    }
                                }
                            }
                        }
                    ]
                }
                echart1_ele.clear();
                echart1_ele.setOption(option);
            }
        &lt;/script&gt;
    &lt;/body&gt;
&lt;/html&gt;

**Comment by yufeng04** [comment]
Could you describe the comfortable effect specifically？

**Comment by TRSK-CONMI** [comment]
你好，yufeng04。
很多时候，我们制作图表是为了给领导/数据分析师/执行人员使用的。存在数据，却显示为0，这样的效果会被很多人反问。
我在此只能给予一个我个人觉得比较好的是出现这种情况，小的柱状可以为画布的1/4。但我目前还没有比较有效的计算公式，抱歉~

**Comment by TRSK-CONMI** [comment]
Hello, yufeng04.
Most of the time, we create charts for leaders/data analysts/executives.There is data, but it is shown as zero, this effect will be questioned by many people.
I can only give here a situation where I personally think it would be better if a small bar could be a quarter of the canvas.But I don't have an effective formula yet, sorry

**Comment by Ovilia** [comment]
明确一下需求，是希望柱状图最小占画布的 1/4 吗？https://echarts.apache.org/zh/option.html#series-bar.barMinHeight 这个配置项可以设置柱条的最小高度。

**Comment by TRSK-CONMI** [comment]
不是不是，是最好有比较好的优化算法能让柱状图显示这种比较小的差距的时候能更好的显示。这个方案能解决当前的问题，但却无法解决以后的问题。。。

**Comment by Ovilia** [comment]
其实还是不明白你具体的需求是什么？log 轴可以满足吗？https://echarts.apache.org/zh/option.html#yAxis.type

**Comment by wf123537200** [comment]
> 其实还是不明白你具体的需求是什么？log 轴可以满足吗？https://echarts.apache.org/zh/option.html#yAxis.type

我理解，他是想要一个类似的归一化算法，计算出来```barMinHeight ```

@TRSK-CONMI 我觉得可以自己写一个算法，动态设置 ```barMinHeight```是不是能解决问题

**Comment by TRSK-CONMI** [comment]
@wf123537200 bingo，我自己能写一个动态算法解决这个问题，只是解决了我的这个问题，但是框架的这个问题还是存在的，我希望框架能在根本上解决这个问题。(*^▽^*)

@Ovilia 我希望框架能在根本上解决这个问题，而不单是我的问题被解决而已~当前只解决我的问题的话，意味着以后还会出现同样的问题。而每个人都要通过我这个方式去解决的话，这就是动作上的浪费了

**Comment by TRSK-CONMI** [comment]
我希望框架能在根本上解决这个问题，而不单是我的问题被解决而已~

**Comment by wf123537200** [comment]
> 我希望框架能在根本上解决这个问题，而不单是我的问题被解决而已~

恩啊，我理解哈，个人观点是框架已经提供这样的能力了，通过自己配置解决会不会比较好，毕竟框架内部解决业务问题感觉上不是特别合理？

**Comment by TRSK-CONMI** [comment]
> > 我希望框架能在根本上解决这个问题，而不单是我的问题被解决而已~
> 
> 恩啊，我理解哈，个人观点是框架已经提供这样的能力了，通过自己配置解决会不会比较好，毕竟框架内部解决业务问题感觉上不是特别合理？

非也非也，我是说像这种数据差距只是1的情况下就导致一个触顶而另一个触底，是这个问题需要被处理而已，非我业务问题，而是我觉得以后也有可能出现，所以希望社区能修复这个BUG。
设置最小值只能解决当前业务，而无法解决下一个人继续来这里问相同的问题

**Comment by Ovilia** [comment]
@TRSK-CONMI 我没理解这为什么是一个 bug？你所说的数值最大触顶最小值触底为什么不符合预期呢？难道数值 1 对应的高度不就应该是几乎不可见的吗？
业务层面，我可以理解说加一个 minHeight，但是为什么这是 bug？其他场景为什么也同样需要 minHeight 呢？

**Comment by TRSK-CONMI** [comment]
> @TRSK-CONMI 我没理解这为什么是一个 bug？你所说的数值最大触顶最小值触底为什么不符合预期呢？难道数值 1 对应的高度不就应该是几乎不可见的吗？
> 业务层面，我可以理解说加一个 minHeight，但是为什么这是 bug？其他场景为什么也同样需要 minHeight 呢？

https://user-images.githubusercontent.com/39817817/81885803-b83c1100-95cd-11ea-81e5-e4568fec4401.jpg

这个视图的效果几乎可以说什么都没加的，你会觉得这样的视图是正常的吗~~

**Comment by Ovilia** [comment]
你指的不正常的地方是什么？是右边两个柱子 label 的位置太偏下了吗？

**Comment by TRSK-CONMI** [comment]
> 你指的不正常的地方是什么？是右边两个柱子 label 的位置太偏下了吗？

嗯，是的。源码在上面，应该没有使用什么特别的设置导致的

**Comment by wf123537200** [comment]
> > 你指的不正常的地方是什么？是右边两个柱子 label 的位置太偏下了吗？
> 
> 嗯，是的。源码在上面，应该没有使用什么特别的设置导致的

我理解这个是正常表现额，毕竟这儿你的数据来看确实有量级的差别

**Comment by TRSK-CONMI** [comment]
> > > 你指的不正常的地方是什么？是右边两个柱子 label 的位置太偏下了吗？
> > 
> > 
> > 嗯，是的。源码在上面，应该没有使用什么特别的设置导致的
> 
> 我理解这个是正常表现额，毕竟这儿你的数据来看确实有量级的差别

是的，这样会导致每个自动生成的报表都会有这样的风险，所以想贵社区能对其进行修复，谢谢

**Comment by 100pah** [comment]
@TRSK-CONMI

**Comment by TRSK-CONMI** [comment]
> @TRSK-CONMI
> (A) 不设置 `yAxis.scale: false` 。因为如果 `yAxis.scale: false` 则柱状图不从零点开始，这对于柱状图来说往往是可能引起误导的可视化方式。
> (B) 如果确实要设置 `yAxis.scale: true` 那么可以选择不使用柱状图，而使用 scatter 之类。
> (C) 如果确实要设置 `yAxis.scale: true` 且要使用柱状图，那么可以设置 [yAxis.min](https://echarts.apache.org/zh/option.html#yAxis.min) 和 [yAxis.max](https://echarts.apache.org/zh/option.html#yAxis.max) 调节 y 轴的显示范围。

你好，100pah。
我在API中没找到“scale”相关的内容，然后百度了一下。发现“scale设置为true后，坐标刻度不会强制包含零刻度。（注意：只在数值轴中（type:'value'）中有效）”（网页：https://blog.csdn.net/hao_0420/article/details/81188714）
scale和yAxis.min/yAxis.max这本身的设计是不是一个冲突？
或者说是为了出现BUG的时候可以更底层地调用来解决？

**Comment by Ovilia** [comment]
scale 的文档在 https://echarts.apache.org/zh/option.html#yAxis.scale ，里面也有和 min max 关系的说明。

**Comment by TRSK-CONMI** [comment]
> scale 的文档在 https://echarts.apache.org/zh/option.html#yAxis.scale ，里面也有和 min max 关系的说明。

主要问题不是这个，这个解决方案只是治标不治本~~

**Comment by TRSK-CONMI** [comment]
> scale 的文档在 https://echarts.apache.org/zh/option.html#yAxis.scale ，里面也有和 min max 关系的说明。

而且我的代码中也是含括了scale，为什么还是出现零刻度的情况？

**Comment by Ovilia** [comment]
把有问题的例子放一个在线实例吧

**Comment by TRSK-CONMI** [comment]
> 把有问题的例子放一个在线实例吧

代码在二楼~~

**Comment by TRSK-CONMI** [comment]
> 把有问题的例子放一个在线实例吧

妹子，可有结果？
