### ISSUE TITLE
Graph series can not clip overflowed elements on the coordinate system.

### ISSUE THREAD

**Issue by nguyencuongabcxyz** [apache/echarts#12627]
### What problem does this feature solve?
This feature will clip the overflowed elements on the coordinate system when `dataZoom` has `none` as its `filterMode` property's value.

### What does the proposed API look like?
Other series such as `custom`, `line`, `bar` has `clip` property to determine whether to clip the overflowed elements on the coordinate system or not. I propose `Graph` series can have the same property which is `clip` to support that feature.

**Comment by 100pah** [comment]
@nguyencuongabcxyz Could we know more about the scenario that why we need to clip a graph?
If we support clip, we probably need also provide a way to specify the "bounding rect" of a graph series, which is not possible at present.
