### ISSUE TITLE
piecewise visualMap cannot be applied to dimension 0

### ISSUE THREAD

**Issue by softwords** [apache/echarts#12636]
### Version
4.7.0

### Steps to reproduce
A piecewise visual map that specifies categories cannot be applied to dimension 0 of data. 

This option works, specifying dimension 2:

```
option =  {
  "series": [
    {
      "encode": {
        "itemId": 0,
        "itemName": 0,
        "value": "value",
        "y": "value",
        "x": "rowID"
      },
      "type": "bar",
      "color": "#1f77b4"
    }
  ],
  "dataset": {
    "dimensions": [
      "rowID",
      "value",
      "id2"
    ],
    source: [
        ["A", 1087,"A" ],
      [ "B", 244,"B" ],
      [ "C", 653,"C" ],
    ]
  },
  "xAxis": {
    "type": "category",
  },
  "yAxis": {
    "type": "value"
  },
  "visualMap": {
    "id": "highlighter",
    "type": "piecewise",
    "show": false,
    dimension: 2,
    "categories": [
      "A"
    ],
    "inRange": {},
    "outOfRange": {
      "opacity": 0.4
    }
  }
}
```
This also, works: when dimension is omitted, it uses the last dimension as documented:

```
option =  {
  "series": [
    {
      "encode": {
        "itemId": 0,
        "itemName": 0,
        "value": "value",
        "y": "value",
        "x": "rowID"
      },
      "type": "bar",
      "color": "#1f77b4"
    }
  ],
  "dataset": {
    "dimensions": [
      "rowID",
      "value",
      "id2"
    ],
    source: [
        ["A", 1087,"A" ],
      [ "B", 244,"B" ],
      [ "C", 653,"C" ],
    ]
  },
  "xAxis": {
    "type": "category",
  },
  "yAxis": {
    "type": "value"
  },
  "visualMap": {
    "id": "highlighter",
    "type": "piecewise",
    "show": false,

    "categories": [
      "B"
    ],
    "inRange": {},
    "outOfRange": {
      "opacity": 0.4
    }
  }
}
```

But this does not work: all values are "out of range":

```
option =  {
  "series": [
    {
      "encode": {
        "itemId": 0,
        "itemName": 0,
        "value": "value",
        "y": "value",
        "x": "rowID"
      },
      "type": "bar",
      "color": "#1f77b4"
    }
  ],
  "dataset": {
    "dimensions": [
      "rowID",
      "value",
      "id2"
    ],
    source: [
        ["A", 1087,"A" ],
      [ "B", 244,"B" ],
      [ "C", 653,"C" ],
    ]
  },
  "xAxis": {
    "type": "category",
  },
  "yAxis": {
    "type": "value"
  },
  "visualMap": {
    "id": "highlighter",
    "type": "piecewise",
    "show": false,
    dimension: 0,
    "categories": [
      "C"
    ],
    "inRange": {},
    "outOfRange": {
      "opacity": 0.4
    }
  }
}
```

### What is expected?
The outputs from each of these options should show 1 highlighted bar

### What is actually happening?
The third option , using dimension 0, does nothing. Same behaviour when using the dimension name rather than dimension offset.

---
Want to be able to track when a particular category is "selected" by the user.  This "selection" may occur through clicking on the series, or through other activity on the page.

**Comment by zyn-1121** [comment]
您好 我也遇到相同的问题 请问这个问题最后怎么解决的呢

**Comment by zyn-1121** [comment]
I'm also experiencing this issue.Do you have any good solutions？

**Comment by softwords** [comment]
@zyn-1121 I just re-organised the data, adding a redundant copy of dimension 0 at the end, as in the sample code:

ie from 

 "dataset": {
    "dimensions": [
      "rowID",
      "value"
    ],
    source: [
        ["A", 1087],
      [ "B", 244],
      [ "C", 653],
    ]
  },

to 

 "dataset": {
    "dimensions": [
      "rowID",
      "value",
      "id2"
    ],
    source: [
        ["A", 1087,"A" ],
      [ "B", 244,"B" ],
      [ "C", 653,"C" ],
    ]
  },

then use dimension id2 when necessary
