### ISSUE TITLE
【功能不灵活】柱状图配置项的series-bar里面的label属性中的position，目前只支持string和Array，无法达到个性化动态适配，建议增加function类型

### ISSUE THREAD

**Issue by fwj722** [apache/echarts#12634]
### What problem does this feature solve?

柱状图配置项的series-bar里面的label属性中的position，目前只支持string和Array，如果按目前所支持的类型进行适配的话，所适配的位置都是一样的，无法达到个性化适配。

比如有五个柱子，根据每个柱子的数据大小，来判定每个柱子的数据显示位置，比如第一个柱子数据位置是top，第二个是inside，第三个是50%等等，按照现在的类型是无法做到的。现在只有string和Array类型，只能统一设置，一旦设置，都在设置的位置，要么都在top，要么都在inside，要么都是指定的。

强烈建议给position增加function类型，根据返回的数据进行动态设置position的值。
该需求可能有点偏，但是实战中如果要使得数据最大限度的无障碍展示，动态适配这点是非常重要的，请采纳！
比如我们可以像formatter一样，加上function类型

### What does the proposed API look like?
期望给position增加function类型，返回的是个数组对象，类似于formatter一样，包含每个柱子的相关信息，这样的话，就可以通过遍历，根据业务需求，来动态设置每个柱子的显示位置。

**Comment by plainheart** [comment]
后续在5.0版本中有可能会为更多的选项提供function类型的入参。
往大了想，其实很多series都可能需要function类型的参数来实现更多的个性化，像`rotate`, `offset` 之类的。一个个适配也是感觉很繁琐，不知道有没有什么统一的方式。

**Comment by wf123537200** [comment]
> 后续在5.0版本中有可能会为更多的选项提供function类型的入参。
> 其实很多series都可能需要function类型的参数来实现更多的个性化，如`rotate`, `offset`等等。
> 逐一适配或许会很繁琐，不知道是否会有一种简单统一的方式去实现这些？

很赞同，感觉很多issus都在提要使用function来做个性化配置，统一提供感觉是个好方法，不然配置会不会太麻烦？
