### ISSUE TITLE
微信小程序折线图tooltip在华为系列手机上不显示

### ISSUE THREAD

**Issue by summer-yyyn** [apache/echarts#12641]
### Version
4.7.0

### Steps to reproduce
1、下载echarts-for-weixin
2、在开发者工具启动项目
3、打开折线图，tooltip不显示

### What is expected?
正常显示tooltip

### What is actually happening?
tooltip不显示

---
我是在自己项目中遇见这个问题，想看看官方示例怎么写，发现官方示例也是不显示。

**Comment by Ovilia** [comment]
用的是官方哪个示例？其他手机显示，只有华为不显示吗？

**Comment by summer-yyyn** [comment]
用的echarts-for-weixin 官方示例折线图，目前只发现华为手机不显示
