### ISSUE TITLE
Split lines and axis labels disappear when all legends are unselected

### ISSUE THREAD

**Issue by YiYingWu1302** [apache/echarts#12657]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=area-stack](https://echarts.apache.org/examples/zh/editor.html?c=area-stack)

### Steps to reproduce
Unselect all the legends

### What is expected?
Keep the split lines and axis labels just as when all data are zero, the axis labels are [0, 0.2, 0.4, 0.6, 0.8, 1]

### What is actually happening?
Split lines and axis labels disappear

---
Not sure if it's possible or not, or if I missed any options to support this behavior?

**Comment by quillblue** [comment]
Reproduced regarding the issue itself.
But suggest to discuss in community to decide about expected behavior as I'm not convinced on setting max of y axis to 1 in such cases.

**Comment by Ovilia** [comment]
This is not a bug but I do think it's useful to make a feature like this. Further discussion required.

**Comment by Ovilia** [comment]
For now, @YiYingWu1302 you have to make a fake data with zero values and set axis max value.

**Comment by YiYingWu1302** [comment]
I see, thanks a lot for your reply :)
