### ISSUE TITLE
Adding  difference in percentage values for multi-bar chart. 

### ISSUE THREAD

**Issue by chethan27** [apache/echarts#12666]
### What problem does this feature solve?
The user can see the difference in percentage values between two charts in a multi bar chart.

### What does the proposed API look like?
We need to find the difference between the the two bars and find the difference and show it on top of the two bars.
![multibar](https://user-images.githubusercontent.com/21241898/82323391-9be90b80-99f5-11ea-9a52-09ce7663bba0.png)

**Comment by Ovilia** [comment]
Use https://echarts.apache.org/en/option.html#series-bar.markPoint and set it's data to be the percentage. If you want the shape as in the image, set https://echarts.apache.org/en/option.html#series-bar.markPoint.symbol to be the SVG path value.
