### ISSUE TITLE
Stack tool switches language back to original when pressed 

### ISSUE THREAD

**Issue by jarben** [apache/echarts#12667]
### Version
4.7.0

### Reproduction link
[http://jsfiddle.net/jarben/823k0pyo/](http://jsfiddle.net/jarben/823k0pyo/)

### Steps to reproduce
Click on the "stack" toolbox button 

### What is expected?
The tooltip should be in English

### What is actually happening?
The tooltip is in Chinese

**Comment by plainheart** [comment]
It seems to be a bug brought by #11743 and should will be fixed soon.
