### ISSUE TITLE
The label display will overlap, affecting the data viewing

### ISSUE THREAD

**Issue by daisy0123** [apache/echarts#12681]
### Version
4.8.0-rc.1

### Steps to reproduce
The label display will overlap, affecting the data viewing

### What is expected?
The label display don't overlap

### What is actually happening?
The label display will overlap, affecting the data viewing

**Comment by susiwen8** [comment]
Know issue, we are planning to solve this problem in 5.0

**Comment by daisy0123** [comment]
> 知道问题，我们计划在5.0中解决此问题

thanks very much!!

> Know issue, we are planning to solve this problem in 5.0

Thanks! Expecting!

**Comment by giovannirizzolo** [comment]
Echarts version 4.8.0.
I got the same issue! On this snippet I still see the long labels overlapping the pie-chart:
`label: {
   ....
   position: 'outer',
   alignTo: 'edge',
   margin: 20,
   avoidLabelOverlap: true
}`
