### ISSUE TITLE
Can change the color of the hollow part of the series-line.data. itemStyle. emptycircle

### ISSUE THREAD

**Issue by Pisceser** [apache/echarts#12684]
### What problem does this feature solve?
Make dark theme charts. For example, in line-chart drawing, the series-line.data. itemStyle used the hollow symbol. The color of the hollow can only be white, which will affect the appearance. I hope to change this color.

### What does the proposed API look like?
series-line.data. itemStyle.symbol.color

**Comment by plainheart** [comment]
In fact, we can use `symbol` with `itemStyle` instead of `emptyCircle`.
just like this example: https://gallery.echartsjs.com/editor.html?c=x-zkxeW7Uz&v=3

**Comment by Pisceser** [comment]
I added a legend based on the example you provided, and now the color of the legend is the color of the symbol. I want the color of the legend to be the color of the line.
example: https://gallery.echartsjs.com/editor.html?c=x-zkxeW7Uz&v=5

**Comment by plainheart** [comment]
Sorry for that, it seems that support for this feature is still in progress and may will be included in 5.0 milestone which may need a long period. You can refer to #12444 for more details.
