### ISSUE TITLE
boderRadius for image in backgroundColor option of rich text doesn't crop the image.

### ISSUE THREAD

**Issue by rajshivam** [apache/echarts#12689]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

Trying to add an image in treemap label, borderRadius doesn't apply to the image in backgroundColor.

Kindly refer the code snippet below:

`label: {
  formatter: "{a}",
  rich : {
  a: {
    backgroundColor: {
      image: <some image link>         
    },
    height: 46,
    width: 46,
    borderWidth: 2,
    borderRadius: 23,
     borderColor: "#fff"
  }
}
` 
This shows a circular border on top of the background image.
Along with the circular border, the background image should be cropped.

**Comment by zerosrat** [comment]
I encouter the same issue. Is there any solutions?

**Comment by princ09** [comment]
Is there any solution for this?
