### ISSUE TITLE
折线图上同个类目轴上的值如果一负一正，则切换成堆积后，不会相互叠加

### ISSUE THREAD

**Issue by WuEyuan** [apache/echarts#12699]
### Version
4.1.0-release

### Reproduction link
[https://codesandbox.io/s/zen-curie-8nx4i?file=/src/App.vue](https://codesandbox.io/s/zen-curie-8nx4i?file=/src/App.vue)

### Steps to reproduce
打开后，点击折线图右上角的“切换堆叠按钮”，会发现同个类目轴上一负一正的点不会堆叠，保持不变，都为正或都为负或者有一个为0才有堆叠效果

### What is expected?
期望一正一负时也能够堆叠

### What is actually happening?
同个类目轴上一负一正的点不会堆叠，保持不变，都为正或都为负或者有一个为0才有堆叠效果

**Comment by wf123537200** [comment]
Maybe the positive and negative limit is reasonable
The pr fix this situation,but maybe no reasonable

**Comment by wf123537200** [comment]
> Maybe the positive and negative limit is reasonable
> The pr fix this situation,but maybe no reasonable

i try to support this situation, but i find when the ```type='line'``` is ok, but when switch the ```type='bar'``` the result become strange.

@WuEyuan so, the positive and negative limit is reasonable, the diff sign situation may be not support
