### ISSUE TITLE
地图上的散点显示不完全

### ISSUE THREAD

**Issue by PatrickYan01** [apache/echarts#12696]
当我在Echarts上运行时，地图上的散点显示正常，如下：
![1](https://user-images.githubusercontent.com/63183655/82822648-b4b35e80-9ed8-11ea-92b8-2a4e7b06d83c.PNG)

当我导入到flask时，地图上的散点显示不完全，如下：
![2](https://user-images.githubusercontent.com/63183655/82822705-cac11f00-9ed8-11ea-9478-61412379c128.PNG)
当把地图放大时，可以看见部分散点，不过依然不能完整显示，如下：
![3](https://user-images.githubusercontent.com/63183655/82822975-48852a80-9ed9-11ea-9559-d898b6514e7e.PNG)

请问，如何解决这一问题？

**Comment by plainheart** [comment]
看起来像是CSS/HTML的问题，建议在 https://gallery.echartsjs.com/editor.html 提供一个可复现的示例。
