### ISSUE TITLE
散点图开启大数据优化，brush无法正常返回选取的数据

### ISSUE THREAD

**Issue by zhutianlong95** [apache/echarts#12697]
散点图开启large:true时，brush的brushselected事件不能返回选中的数据index，selected中的dataIndex都是空，文档中并无提及

**Comment by zhutianlong95** [comment]
@susiwen8 已在gallery提交demo，标题和此issue一致

**Comment by zhutianlong95** [comment]
@susiwen8 https://gallery.echartsjs.com/editor.html?c=x7etdXoMdI&v=1

**Comment by airyland** [comment]
还有另一个问题，开启圈选时，图表会重绘，能否避免重绘？

**Comment by cyberlaugh** [comment]
1、outOfBrush即使取消默认color:'#ddd'的配置仍然会重绘。
2、数据量大时散点框选brushSelected回调中无法返回数据点

**Comment by zhutianlong95** [comment]
@cyberlaugh 我现在有一个办法可以获取数据点，brush的回调事件中，可以找到框选线的X范围和Y范围。已知散点的坐标，假设框选线坐标起始点是X1和X2，去判断X在X1~X2范围内的点的Y坐标是否也在Y1~Y2之间，满足，则在选取框范围内，就可以获取选取框的点了，其实就是一个平面坐标系判断位置

**Comment by zhutianlong95** [comment]
> 1、outOfBrush即使取消默认color:'#ddd'的配置仍然会重绘。
> 2、数据量大时散点框选brushSelected回调中无法返回数据点

@cyberlaugh 我现在有一个办法可以获取数据点，brush的回调事件中，可以找到框选线的X范围和Y范围。已知散点的坐标，假设框选线坐标起始点是X1和X2，去判断X在X1X2范围内的点的Y坐标是否也在Y1Y2之间，满足，则在选取框范围内，就可以获取选取框的点了，其实就是一个平面坐标系判断位置

**Comment by cyberlaugh** [comment]
> > 1、outOfBrush即使取消默认color:'#ddd'的配置仍然会重绘。
> > 2、数据量大时散点框选brushSelected回调中无法返回数据点
> 
> @cyberlaugh 我现在有一个办法可以获取数据点，brush的回调事件中，可以找到框选线的X范围和Y范围。已知散点的坐标，假设框选线坐标起始点是X1和X2，去判断X在X1X2范围内的点的Y坐标是否也在Y1Y2之间，满足，则在选取框范围内，就可以获取选取框的点了，其实就是一个平面坐标系判断位置

感谢您的分享，目前我们也是根据coordRange自己写算法，有维持任意形状多次刷选的情况，比矩形X1X2的情况要复杂，不过已经实现。但是重绘问题无法解决，还是希望echarts后续版本能解决提到的两点问题。

**Comment by cyberlaugh** [comment]
补充问题：当x轴为category类型时，coordRange返回值没有相关说明，像是数据下标，但是又会出现负值的情况，令人诧异。

**Comment by zzoath2017** [comment]
> > > 1、outOfBrush即使取消默认color:'#ddd'的配置仍然会重绘。
> > > 2、数据量大时散点框选brushSelected回调中无法返回数据点
> > 
> > 
> > @cyberlaugh 我现在有一个办法可以获取数据点，brush的回调事件中，可以找到框选线的X范围和Y范围。已知散点的坐标，假设框选线坐标起始点是X1和X2，去判断X在X1X2范围内的点的Y坐标是否也在Y1Y2之间，满足，则在选取框范围内，就可以获取选取框的点了，其实就是一个平面坐标系判断位置
> 
> @zhutianlong95 感谢您的分享，目前我们也是根据coordRange自己写算法，有维持任意形状多次刷选的情况，比矩形X1X2的情况要复杂，不过已经实现。但是重绘问题无法解决，还是希望echarts后续版本能解决提到的两点问题。

大佬，可否分享一下多边形的算法，数据多的时候应该有点延迟吧

**Comment by bazingaedward** [comment]
> 知散点的坐标

但是category图就不行了

**Comment by honghh2018** [comment]
我也遇到问题，当我选择6000多的散点图的时候，实际只返回1000多个点，
各位有没有解决这个问题呢？
