### ISSUE TITLE
echarts树图的bug

### ISSUE THREAD

**Issue by soopencool** [apache/echarts#12706]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline](https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline)

### Steps to reproduce
你们不充许放截图，截图就一目了然了。
```js
var data = {
    "name": "flare",
    "children": [
        {
            "name": "data",
           /* "children": [先保留这段代码，然再注释这段代码（其他的化data多余的代码都去除，再注释这段才会看到效果），这里显示图就不正确了，有一些多余的线段
                {
                    "name": "converters",
                    "children": [
                        {"name": "Converters", "value": 721},
                        {"name": "DelimitedTextConverter", "value": 4294}
                    ]
                },
                {
                    "name": "DataUtil",
                    "value": 3322
                }
            ]*/
        }
    ]
};
```
### What is expected?
正确显示（没有多余的线段）

### What is actually happening?
有多余的线段

---
当children有多个节点时，突然把这个children清空了，就会出现这种情况

**Comment by pissang** [comment]
可以放截图

**Comment by soopencool** [comment]
重现步骤那写清楚了，不放截图，应该你们也能复现出来了，确定有这个bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yi Shen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 中午11:29
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"453336456"<453336456@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] echarts树图的bug (#12706)





 
可以放截图

**Comment by wf123537200** [comment]
> 可以放截图

![image](https://user-images.githubusercontent.com/5130528/82995912-d3c80280-a036-11ea-9eb1-c5bd12687293.png)

重现了下，还没来得及看为啥。。
