### ISSUE TITLE
Disable or hide the chart when data is null

### ISSUE THREAD

**Issue by zhangddjs** [apache/echarts#12709]
### What problem does this feature solve?
There are mutiple charts on the page, however, some of them have no data. We need to hide or disable those charts with no data.

### What does the proposed API look like?
series.visible = true/false
or
series.display= true/false
or
series.show = true/false
or
series.displayWhenNoData= true/false

**Comment by plainheart** [comment]
Why not use css property `display` or `visibility` to control the visibility of chart?

**Comment by zhangddjs** [comment]
The charts are all in one diagram, while the css can only control the visibility of charts in seperate diagrams.

**Comment by helgasoft** [comment]
Did you try to control it thru _legend.selected_ ?  It works:
```js
        legend: {
            right: 20,
            data: ['SGE', 'XAU', 'London'],
            selected: { 'SGE': true, 'XAU': true, 'London': false }   // false hides it
        },
```
