### ISSUE TITLE
当饼图label.alignTo == edge且在formatter中使用了rich时，labelLine与label间有不规则空隙

### ISSUE THREAD

**Issue by Ling310** [apache/echarts#12708]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x7lnSN-OJe&v=1](https://gallery.echartsjs.com/editor.html?c=x7lnSN-OJe&v=1)

### Steps to reproduce
label.alignTo == edge且在formatter中使用了rich

### What is expected?
label与labelLine间没有不合理的空隙

### What is actually happening?
如题

---
相关issue：https://github.com/apache/incubator-echarts/issues/12148

**Comment by pissang** [comment]
It's fixed in the 5.0

![image](https://user-images.githubusercontent.com/841551/89178998-664dca80-d5c1-11ea-9a8e-3a5b794dc879.png)
