### ISSUE TITLE
Bar charts still not clipped when using filterMode: 'none'

### ISSUE THREAD

**Issue by kdai319** [apache/echarts#12720]
### Version
4.8.0

### Reproduction link
[Test code](https://gallery.echartsjs.com/editor.html?c=xI02xxZ13f&v=1)

### Steps to reproduce
I saw the very same title issue before, I thought the problem was solved, but when I tried it, there was actually no.

[#10646](https://github.com/apache/incubator-echarts/issues/10646)

### What is expected?
![normal](https://user-images.githubusercontent.com/15166619/83255415-f3039300-a1e2-11ea-81a2-cd2fb591f2eb.png)

I want the bar could clip like the line clipped exactly.

### What is actually happening?
![overflow](https://user-images.githubusercontent.com/15166619/83255405-ed0db200-a1e2-11ea-9ced-5bd3e3e16f0a.png)
Here you can see, zoom in it, the bar element overflowed from grid, and slide the time line will see more clearly.
The config option "clip" did not help.

**Comment by 100pah** [comment]
`series-bar.clip` still not correct enough for `time` and `value` axis.

**Comment by 100pah** [comment]
Fix in v6.1.0
