### ISSUE TITLE
Horizontal Selection (Line-X) freezes on the graph sometimes

### ISSUE THREAD

**Issue by manjureddy7** [apache/echarts#12741]
Hello Team,

When i try to do Horizontal selection (line-x) on the chart/graph, sometimes the horizontal selection indicator freezes on the screen (screenshot attached). Please help how to fix this issue.

Also i'm dispatching below action, once selection is successful . Still Horizontal selection sometimes freezes on the chart.

 **echartsInstance.dispatchAction({
    type: 'brush',
    command: 'clear',
    // Clear all areas of all brush components.
    areas: []
  });**

Please let us know, if theres any workaround .

![image](https://user-images.githubusercontent.com/22653056/83599670-6104dd00-a58a-11ea-8b03-a712ed140977.png)

**Comment by susiwen8** [comment]
Could you provide full example?
