### ISSUE TITLE
MarkPoint not considering backgroundColour, borderColor and borderWidth attributes

### ISSUE THREAD

**Issue by dvago** [apache/echarts#12748]
### Version
4.8.0

### Steps to reproduce
I'm importing those files along with the main echarts library (using vue-echarts)

```
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/title'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/markLine'
import 'echarts/lib/component/markPoint'
import 'echarts/lib/component/dataZoom'
import 'zrender/lib/svg/svg'

```

Then in my configuration I set:

```
markPoint: {
                data: [
                    {type: 'max', name: 'Max'},
                    {type: 'min', name: 'Min'}
                ],
                label: {
                    show: true,
                    fontSize: 11,
                    position: 'right',
                    formatter: '{b}\n{c}',
                    backgroundColor: '#DDDDDD',
                    borderColor: 'red',
                    borderWidth: 1,
                    padding: [2,2,2,2]
                }
            },
```

### What is expected?
I expect to see a background colour and a border on the Min and Max markpoint labels

### What is actually happening?
these 3 attributes gets completely ignored, however the rest of the configuration works (e.g. padding)

---
I believe is due to some missing script from the import list as I tried to reproduce the issue on the example page: https://echarts.apache.org/examples/en/editor.html?c=line-marker and it does work as expected.

Thanks in advance for your support.

**Comment by Ovilia** [comment]
Generally speaking, you should use `import * as echarts from 'echarts'` instead and without considering which packages to include.

**Comment by dvago** [comment]
`import * as` means you decide to import the whole library, which for production environments is quite inefficient as you might use one or two type of charts and one specific tool. 

I would rather prefer to have a list of specific modules required for specific features in order to decide what to import and what not to import, hope that approach makes sense to you.
