### ISSUE TITLE
Can't format the "detail" object for a gauge series

### ISSUE THREAD

**Issue by bogdanhoancea420** [apache/echarts#12759]
### What problem does this feature solve?
This option exists in the docs (https://echarts.apache.org/en/option.html#series-gauge.detail.formatter), but the formatter doesn't exist for the "detail" object of the gauge series (echarts v4.8.0). I would like to format the value as a percentage.

### What does the proposed API look like?
It should work exactly like in the editor. The "detail" object of a series should have a "formatter" property.

**Comment by bogdanhoancea420** [comment]
![image](https://user-images.githubusercontent.com/66477195/83879839-93573b80-a73e-11ea-987f-31bf9e522b98.png)

**Comment by wf123537200** [comment]
It seems that it is just a grammar test error, Is it the drawing result is correct?
Can you give examples or screenshots?

**Comment by bogdanhoancea420** [comment]
If I change the return type from SeriesGauge to "any", the drawing result is correct. However, that defeats the point of using TS

**Comment by plainheart** [comment]
As document says, [series-gauge.detail.formatter](https://echarts.apache.org/en/option.html#series-gauge.detail.formatter) should return a function or a number, so is it better to set return type as `Function | number`?

**Comment by bogdanhoancea420** [comment]
I'm not sure if my problem is understood. What I need as return type is a "series-gauge" object. that object contains object detail which, in the docs, contains "formatter" which is a function or a string. However, the Node JS interface "series-gauge.detail" does **not** contain the "formatter" property.

**Comment by plainheart** [comment]
Could you tell me what library you are using, is it  [ECharts@types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts) ?

**Comment by bogdanhoancea420** [comment]
yes

**Comment by plainheart** [comment]
That seems to be a bit weird.
I saw it exists in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/echarts/options/series/gauge.d.ts#L2026

**Comment by plainheart** [comment]
It's indeed for missing `formatter` option in `series.gauge`, maybe you need to add it manually. 
After all, we can see that this repository is maintained at a long period interval and many of the types have been changed.
ECharts team is already developing with TypeScript under [`next`](https://github.com/apache/incubator-echarts/tree/next) branch, in the near future, `ECharts@types` will be not necessary any more.

**Comment by Ovilia** [comment]
A simple fix would be changing the return value to `as any`. You may also make a pull request to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts), or wait for it to be fixed in next branch.

**Comment by bogdanhoancea420** [comment]
> A simple fix would be changing the return value to `as any`. You may also make a pull request to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts), or wait for it to be fixed in next branch.

This is indeed how I temporarily fixed it.
