### ISSUE TITLE
legend的宽度限制失效

### ISSUE THREAD

**Issue by Liz2Z** [apache/echarts#12753]
### Version
4.8.0

### Reproduction link
[https://codesandbox.io/s/elegant-dirac-kvkox?file=/src/options2.js](https://codesandbox.io/s/elegant-dirac-kvkox?file=/src/options2.js)

### Steps to reproduce
打开链接可直接看到bug效果

### What is expected?
legend的宽度限制 正常

### What is actually happening?
legend的宽度限制失效

**Comment by LiZ2z** [comment]
![image](https://user-images.githubusercontent.com/30578440/83727035-0301f380-a677-11ea-91c7-776ab8d15f47.png)
