### ISSUE TITLE
想要支持左右滑动查看数据而不是scale查看

### ISSUE THREAD

**Issue by YouthShouting** [apache/echarts#12752]
当柱状图横坐标数据较多的时候想左右滑动查看数据不想用缩放功能用缩放的功能有时候横坐标的label会重叠

**Comment by plainheart** [comment]
请考虑使用 [dataZoom ](https://echarts.apache.org/zh/option.html#dataZoom)。
启用 `dataZoom` 组件后可以使用dataZoom slider滑块或鼠标左右拖动或滚轮查看前后数据。
可以参考这个示例：https://echarts.apache.org/examples/zh/editor.html?c=mix-zoom-on-value

**Comment by YouthShouting** [comment]
能不能禁止缩放，只想要滚动效果

**Comment by plainheart** [comment]
参考 [`dataZoom-inside.zoomOnMouseWheel`](https://echarts.apache.org/zh/option.html#dataZoom-inside.zoomOnMouseWheel)

**Comment by YouthShouting** [comment]
![image](https://user-images.githubusercontent.com/47060588/84125346-ff9fab00-aa6e-11ea-8b44-c0dda4f3bf16.png)

**Comment by YouthShouting** [comment]
上面那个柱状图会堆叠很难看，怎样才能然柱状图直接存在间隙呢？

**Comment by plainheart** [comment]
> 上面那个柱状图会堆叠很难看，怎样才能然柱状图直接存在间隙呢？

可以使用 [`barCategoryGap`](https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap) - 同一系列的柱间距离 或者 [`barGap`](https://echarts.apache.org/zh/option.html#series-bar.barGap) - 不同系列的柱间距离

**Comment by 10191591** [comment]
设置zoomLock: true
