### ISSUE TITLE
Distinguish between selected and unselected styles.

### ISSUE THREAD

**Issue by Wdingding** [apache/echarts#12756]
Can be configured: when a series is selected, the transparency of other unselected series is reduced by 50% to display.
This configuration may also apply to line chart、 pie chart、 radar chart、 scatter chart、ThemeRiver.

For example：
<img width="602" alt="1ce35247a33523c0869d372fd" src="https://user-images.githubusercontent.com/26783462/83842397-74a07700-a735-11ea-8d94-09f6f48d2e4c.png">
<img width="559" alt="7829eadd0792d6a05ca0b939b" src="https://user-images.githubusercontent.com/26783462/83842400-766a3a80-a735-11ea-9216-bb41e4f0e35e.png">

**Comment by plainheart** [comment]
Yes, for a chart, selected and unselected series should indeed be distinguished when there are multiple series. I think it will be a great job to support this feature!
