### ISSUE TITLE
Points refresh while loading dynamic data

### ISSUE THREAD

**Issue by akrajan23** [apache/echarts#12760]
### Version
4.8.0

### Steps to reproduce
Paste below sample to 
http://echarts.apache.org/examples/en/editor.html?c=doc-example/tutorial-dynamic-data

you will be able to see the line flicker/refresh. We want it to be seamless. anything we can do to fix is appreciated

var base =  new Date(2014, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];
var startpoint = 80
var data = [];
var now = new Date(base);

function addData(shift) {
    
    
    data.push([23,startpoint] );
    startpoint =startpoint   1

    
}

for (var i = 1; i < 2990; i  ) {
    addData();
}

option = {
    xAxis: {
        type: 'value',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        boundaryGap: [0, '90%'],
        inverse: true,
        type: 'value'
    },
    series: [
        {
            name:'成交',
            type:'scatter',
            symbolSize:1,
           
            stack: 'a',
            areaStyle: {
                normal: {}
            },
            data: data
        }
    ]
};

setInterval(function () {
    addData(true);
    myChart.setOption({
        
        series: [{
            name:'成交',
            data: data
        }]
    });
}, 500);

### What is expected?
no flickering/refreshing of line

### What is actually happening?
you will be able to see the line flicker/refresh

**Comment by plainheart** [comment]
Seems to be related to animation, you can temporarily disable chart animation with option `animation: false` to avoid the flicker. But the chart looks weird and not smooth if we disable animation.

**Comment by plainheart** [comment]
Seems to be related to animation, you can temporarily disable chart animation with option `animation: false` to avoid the flicker. But the chart looks weird and not smooth if we disable animation.
Therefore, I will suggest using [`dataset`](https://echarts.apache.org/en/tutorial.html#Dataset) to manage chart data which has no such flickering issue.
There is a demo on ECharts gallery https://gallery.echartsjs.com/editor.html?c=xmnJypxSli&v=1

**Comment by Ghostbird** [comment]
I have a similar issue, but only when using `dataset`.
When using `data` it works when I use the name-value object format:
This example works: https://gallery.echartsjs.com/editor.html?c=xdU-QdxsSz&v=1
