### ISSUE TITLE
Should the properties unsupported currently be removed from document?

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#12764]
### Version
4.8.0

### Steps to reproduce
There is a example for `geo.label` component.
https://gallery.echartsjs.com/editor.html?c=xZ_czZ29g-&v=1

Some comments have been added at the end of code line.

![image](https://user-images.githubusercontent.com/26999792/83963105-f62f0b00-a8d5-11ea-8350-74ee23da0dad.png)

Related issues: #10824

### What is expected?
All the properties listed in document should be valid and not confusing. I've tried each of them, the result seems to be not totally what I expect, I'm a bit confused for that.

### What is actually happening?
It seems that some properties unsupported currently are still listed in document option. Usually, someone can not get expected result after adding them to his own configuration.

---
Therefore, for such issue, should we hide or remove these temporary unsupported properties from document? And we added it back again after being supported if necessary.
Feel free to show your ideas.

**Comment by alex2wong** [comment]
I suppose it is not easy to maintain echarts codebase and its corresponding doc project at the same time manually.  It would be better if we can auto-generate or extract the props of all series, then compare with the props listed in doc, finding the difference without much effort.
I mean ideally we can generate table of doc content from code comments by ts-doc things to make sure the consistence. This would be a big project..
