### ISSUE TITLE
饼图相邻区域颜色重复和工具栏想法

### ISSUE THREAD

**Issue by mumu1349562746** [apache/echarts#12766]
### What problem does this feature solve?
一下几个问题
1.当前默认的颜色有11种，当我的数据有12种时，第一个和第十二个数据他们挨在一起且颜色相同，完全无法区分
2.关于echarts的工具框（右上角下载等），希望能增加一个鼠标移入移出事件，而不是一直挂在上面，当图很小的时候会遮挡图，利用重新渲染echarts时，会导致里面的图形重叠（尤其是词云图，重叠的更厉害）

### What does the proposed API look like?
颜色
    以前：color:[‘#666666’，........]
    设想：
        color:{
            static:[‘#666666’，........],                      //静态块
            repeat:'defalut'                                       //最后一个元素的颜色与第一个不重复
        }
移入移出
增加一个hover的api吧，类似于jquery，或者是拆开也行，mouseenter，mouseleave

**Comment by mumu1349562746** [comment]
还有就是，当画多个扇形图的时候，如果我想在扇形图中心加文字，找不到相应的属性，也无法彻底的居中

**Comment by plainheart** [comment]
@mumu1349562746 居中的问题是这个示例中所展示的吗？https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut

**Comment by mumu1349562746** [comment]
可以是这个,不过想要得是一直显示在中间得固定值,就比如所有扇形图得总值,刚刚我已经解决了,上面得问题麻烦看下哈感觉挺关键得,因为我没法用代码逻辑去弥补

**Comment by plainheart** [comment]
对于第一个问题，默认情况下 `option.color` 是依次循环取颜色的，你的意思是说超出了 `option.color` 范围的不应该再从头取色，而应该是与前边的所有颜色不同？

**Comment by mumu1349562746** [comment]
循环取色的时候有可能第一个颜色和最后一个颜色一样，这样造成两个色块看起来像一个一样，我想的是如果需要循环取色的时候，能不能从第二个开始取，然后继续完后顺序取色，这样就能避免相邻的扇面颜色重复的问题了吧

**Comment by mumu1349562746** [comment]
还有第二个问题，我觉得挺关键的，因为右上角的工具栏（提供下载，数据视图，还原等工具）本身没有鼠标移入移除的显示规则，我这只能使用重新渲染的方法来弥补，造成的问题就是性能的下降和数据重复渲染的bug（尤其是词云图，因为每次都是随机生成的，所以更加明显）

**Comment by mumu1349562746** [comment]
就是toolbox这个东西

**Comment by mumu1349562746** [comment]
还有就是，旭日图有的时候下钻点击的时候，背景颜色会变成黑色？？？？？这是为什么

**Comment by mumu1349562746** [comment]
x希望能回复一下谢谢

**Comment by plainheart** [comment]
> 还有第二个问题，我觉得挺关键的，因为右上角的工具栏（提供下载，数据视图，还原等工具）本身没有鼠标移入移除的显示规则，我这只能使用重新渲染的方法来弥补，造成的问题就是性能的下降和数据重复渲染的bug（尤其是词云图，因为每次都是随机生成的，所以更加明显）

同意你的想法，目前`toolbox`组件和图表是在一起的，要更新`toolbox`的状态只能通过`chart.setOption`的方式，这会导致你说的重新渲染问题，有在考虑是否应该让`toolbox`可以像`tooltip`那样支持使用html渲染，从而使其脱离图表本身单独渲染，更新`toolbox`的状态不会导致图表刷新。

**Comment by mumu1349562746** [comment]
我想的是toolbox可以灵活的增加一些事件，比如鼠标移入移除事件，点击事件（这样更加人性化，自定义话）设置样式，可以考虑显示的动画等等方面吧，尽量多的能够用到现代h5的效果，这样一定程度上可以在表现形式上有个很大的提升，能画出图是很牛的，但是能够很好的使用相应的工具保存，分享等那就更好了，可以类似于百度地图那样，有自己的编译器，而不是仅仅局限于插件，可以让更多的用户，哪怕是新手，可以直接复制粘贴的形式来一键设置，百度地图就有这样的东西，设置好样式，然后直接复制json，往地图的bmap里面一塞，完活，完美

**Comment by mumu1349562746** [comment]
关于颜色的方面说说你的想法

**Comment by plainheart** [comment]
> 循环取色的时候有可能第一个颜色和最后一个颜色一样，这样造成两个色块看起来像一个一样，我想的是如果需要循环取色的时候，能不能从第二个开始取，然后继续完后顺序取色，这样就能避免相邻的扇面颜色重复的问题了吧

循环取色的时候什么情况下第一个颜色会和最后一个颜色一样？能提供个例子吗？

**Comment by plainheart** [comment]
> 移入移除的

能否麻烦你描述下`toolbox`组件添加移入移出事件监听的应用场景吗？

**Comment by hlr7999** [comment]
#### 颜色重复
```json
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    series: [
        {
            name: '访问来源',
            type: 'pie',
            radius: ['50%', '70%'],
            data: [
                {value: 335, name: '直接访问'},
                {value: 310, name: '邮件营销'},
                {value: 234, name: '联盟广告'},
                {value: 135, name: '视频广告'},
                {value: 1548, name: '搜索引擎'},
                {value: 310, name: '邮件营销1'},
                {value: 234, name: '联盟广告1'},
                {value: 135, name: '视频广告1'},
                {value: 1548, name: '搜索引擎2'},
                {value: 310, name: '邮件营销2'},
                {value: 234, name: '联盟广告2'},
                {value: 135, name: '视频广告2'}
            ]
        }
    ]
};
```
![image](https://user-images.githubusercontent.com/33961019/102878836-d3380300-4483-11eb-98e2-2b3f7e7e2d92.png)
