### ISSUE TITLE
[Discuss] 1px gap in Bar Series?

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#12783]
### Version
4.8.0

### Steps to reproduce
There is a demo for reproducing: https://gallery.echartsjs.com/editor.html?c=xaOFWA1lHn&v=1
![image](https://user-images.githubusercontent.com/26999792/84150941-2bce2280-aa95-11ea-8af9-6dc98b1a6bc3.png)

Related to #12342

And  I think the bug in #12342 which is for Heatmap Series is still not solved totally. These two are the same kind of issue.
A demo: https://gallery.echartsjs.com/editor.html?c=xFkorVr6db&v=2

![image](https://user-images.githubusercontent.com/26999792/84150769-e9a4e100-aa94-11ea-9482-e5300808fb68.png)

### What is expected?
No gap in bar series and heatmap series

### What is actually happening?
Some gaps appeared in bar series when bar category gap is zero.
Some gaps appeared in heatmap series

---
The bug should be reproduced by resizing the chart with different width and height many times, but not only test it in the same width or height.
It might need a discussion for this.
@100pah @Ovilia @pissang @susiwen8 @SnailSword

**Comment by susiwen8** [comment]
I don't think this was a bug, because bar chart wasn't continuous, It should have gap to clarify each data boundary.

**Comment by plainheart** [comment]
That seems to object to `barCategory: 0`, chart should have no gap between each bar, and it seems the logic in source code may not have such specific purpose. I suppose that it is also because of the decimal pixel like heatmap #12342.

**Comment by Ovilia** [comment]
> That seems to object to `barCategoryGap: 0`, chart should have no gap between each bar, and it seems the logic in source code may not have such specific purpose. I suppose that it is also because of the decimal pixel like heatmap #12342.

Yes, but do we have this requirement to make bars merging together, or just logically? If there's no such requirement, this feature may not be very urgent.

**Comment by plainheart** [comment]
> > That seems to object to `barCategoryGap: 0`, chart should have no gap between each bar, and it seems the logic in source code may not have such specific purpose. I suppose that it is also because of the decimal pixel like heatmap #12342.
> 
> Yes, but do we have this requirement to make bars merging together, or just logically? If there's no such requirement, this feature may not be very urgent.

No such requirement currently, it is not necessary to be urgent.
But for heatmap series, some gaps are still visible in the example I've provided above.
Is that expected?

**Comment by Ovilia** [comment]
> But for heatmap series, some gaps are still visible in the example I've provided above. Is that expected?

Can you provide a demo? I think #12342 should have fixed them.

**Comment by plainheart** [comment]
For the same demo:
https://gallery.echartsjs.com/editor.html?c=xFkorVr6db&v=2
There will be some gaps in my laptop which has a screen resolution of UHD(3840×2160, 4K), but no gaps in my desktop computer which has a screen resolution of FHD(1920×1080).
Open and zoom in on the picture below, we can see some white lines.

![image](https://user-images.githubusercontent.com/26999792/84150769-e9a4e100-aa94-11ea-9482-e5300808fb68.png)

**Comment by plainheart** [comment]
On another laptop with a screen resolution of 1080P, it has the same issue and this computer's scaling is set a value over 100%,  for example 125%. 

![image](https://user-images.githubusercontent.com/26999792/84252053-b750bd80-ab40-11ea-9b55-73b47205275e.png)

**Comment by Ovilia** [comment]
I didn't see the gap in your image.

**Comment by plainheart** [comment]
> I didn't see the gap in your image.

😅 Really? Try to zoom in please.

**Comment by plainheart** [comment]
![a](https://user-images.githubusercontent.com/26999792/84348478-98f1cd00-abe7-11ea-82b9-94b17aa25863.png)
![b](https://user-images.githubusercontent.com/26999792/84348481-9abb9080-abe7-11ea-97bd-b1a68d61e1f8.png)
![diff](https://user-images.githubusercontent.com/26999792/84348483-9becbd80-abe7-11ea-89e5-652ed873954f.png)
