### ISSUE TITLE
SVG render bug in gauge

### ISSUE THREAD

**Issue by ChouJoe** [apache/echarts#12808]
### Version
4.8.0

### Steps to reproduce
when using svg render,  it seems some  properties of series.gauge.detail dont working anymore， forexample， i set the detail below：

```js
detail:{                  
    backgroundColor: 'rgba(30,144,255,0.8)',
    borderWidth: 1,
    borderColor: '#fff',
    shadowColor: '#fff',
    shadowBlur: 5,
    offsetCenter: [0, '50%'],
    textStyle: {
        fontWeight: 'bolder',
        color: '#eee'
    }                        
}
```
it is working in canvas but not in svg

### What is expected?
![企业微信截图_15922861301673](https://user-images.githubusercontent.com/31032742/84735943-51988180-afd7-11ea-9a60-13590e4c4ee2.png)

### What is actually happening?
![企业微信截图_15922862665919](https://user-images.githubusercontent.com/31032742/84736040-84427a00-afd7-11ea-9853-4ce7b0697edb.png)
it doesnt working  in svg, but good in canvas

---
when using svg render,  it seems some of series.detail properties dont working

**Comment by plainheart** [comment]
Currently, some of rich label text properties are not supported by `svg` renderer.
