### ISSUE TITLE
E2E tests with Protractor fails/hangs when echarts are included on page

### ISSUE THREAD

**Issue by jst10** [apache/echarts#12803]
### Version
4.8.0

### Reproduction link
[https://github.com/jst10/echarts-e2e-example](https://github.com/jst10/echarts-e2e-example)

### Steps to reproduce
Create new Angular project, include echart on it and run any E2E test with Protractor on that page.

### What is expected?
That Protractor continue executing tests.

### What is actually happening?
Protractor hangs and than jasmine timeout because callback was not invoked.

**Comment by Ovilia** [comment]
How does the test case look like?

**Comment by jst10** [comment]
In test is just simple navigation to the web-page and than protractor action for getting text from the element in page (like this is in above example I provided).
So breaking lines in [test](https://github.com/jst10/echarts-e2e-example/blob/master/e2e/src/app.e2e-spec.ts)  is [14](https://github.com/jst10/echarts-e2e-example/blob/master/e2e/src/app.e2e-spec.ts#L14), at this point protractor hangs. In case that I do not use echarts on my web [page](https://github.com/jst10/echarts-e2e-example/blob/master/src/app/app.component.ts) removing lines[ 34 and 35](https://github.com/jst10/echarts-e2e-example/blob/master/src/app/app.component.ts#L34), E2E  test executes as it should.
