### ISSUE TITLE
Can't show tooltips without move mouse pointer on the serie

### ISSUE THREAD

**Issue by arnaudiko** [apache/echarts#12805]
### Version
4.0.4

### Steps to reproduce
1- got to the tooltips exemple: https://echarts.apache.org/examples/en/editor.html?c=line-tooltip-touch

2- add alwaysShowContent: true option in the tooltip part

3- press "run" button

### What is expected?
The tooltip is always displayed, even if I don't interact with chart (move mouse or click)

### What is actually happening?
the tooltip is not displayed. I need to interact with the chart for display him

---
I need the tooltip has always displayed for give informations to the user.
My user use a smartphone and interact with the chart with their fingers

**Comment by yufeng04** [comment]
Maybe you can try [action.tooltip. showTip](https://echarts.apache.org/en/api.html#action.tooltip.showTip)
