### ISSUE TITLE
[video] Slow/lag mouse-click dragging compared to responsive zoom slider drag

### ISSUE THREAD

**Issue by timothymarois** [apache/echarts#12814]
### Version
4.8.0

### Steps to reproduce
1) create a chart with 5,000+ data points

2) have multiple series in the graph (lines and or candle), lags the more series in the chart.

3) add data zoom, crosshairs and tooltips

4) zoom in and drag with mouse (slow or lag)

5) zoom in and drag with data zoom slider (responsive)

### What is expected?
It should be a smooth drag, something within the mouse click-drag on graph seems to be causing the glitch. 

### What is actually happening?
Here is a video of the screen recording to show you exactly what I'm talking about: 
[screen recording](https://www.dropbox.com/s/65r87a88ygrlhlp/Screen%20Recording%202020-06-16%20at%2012.14.01%20PM.mov?dl=0)

---
If you need any more details let me know, but it seems like its an issue only with mouse click-dragging on the graph compared to the zoom slider dragging.

**Comment by timothymarois** [comment]
After further testing, it does look related to `tooltip`, after hiding the tooltip, it's very responsive. However, tooltips are important, so I also tested adding `showDelay : 25`, having just a very small delay on the tooltip has given almost perfect responsiveness in the graph.

**Comment by Ovilia** [comment]
Can you share an online demo with us?
