### ISSUE TITLE
Displaying last data point from series on yaxis 

### ISSUE THREAD

**Issue by timothymarois** [apache/echarts#12813]
### What problem does this feature solve?
Ability to see the last data point of any series on the yaxis. 

I posted on [stackoverflow](https://stackoverflow.com/questions/62412064/echarts-how-to-show-the-last-data-point-value-on-yaxis) to see if anyone already understands the API, however, being able to do this might not even be possible with the current framework. Added a [Fiddle example](http://jsfiddle.net/nva3pbwf/3/) for testing.

This would be useful for statistics/analytics-based graphing (esp with real time updates), and if the API doesn't currently support it, based on the functionality of the yaxis/crosshairs it appears it would be easy to implement (at least from the broad perspective) and I don't see any reason this would have to harm performance. 

To note, this would be a feature that you could enable with a `show : true` like all the other options already have. It could be related to the specific series you wish to show value on-axis. 

### What does the proposed API look like?
![screenshot](https://i.stack.imgur.com/zhJCt.png)

**Comment by Ovilia** [comment]
We are going to make a new feature that the last data label will be displayed. Does this feature works for you? What else do you need?
