### ISSUE TITLE
在series中使用label 的formatter属性<br/>无法换行

### ISSUE THREAD

**Issue by busyzz-1994** [apache/echarts#12827]
### Version
4.8.0

### Steps to reproduce
1.该情况下br无法换行，而是直接显示‘br’字符串

series: [

      {
        name: '品种',
        type: 'bar',
        data: [5, 20, 36, 10, 10],

        label: {
          show: true,
          position: 'top',
          fontSize: 14,
          align: 'center',
          formatter(params) {
            let { value, name } = params;
       
            return `${name}<br/>${value}`;
          },
        },
      },
    ],

### What is expected?
期望能换行

### What is actually happening?
不能换行 ，直接显示字符串

**Comment by yanheSu** [comment]
```javascript
label: {
  show: true,
  position: 'top',
  fontSize: 14,
  align: 'center',
  formatter(params) {
    let { value, name } = params;
    return `${name} \n ${value}`;
  }
}
```
也许你可以 试试 使用 `\n` 替换 `<br />`

**Comment by plainheart** [comment]
是的，`label` 需要使用 `\n` 换行，`tooltip`中是使用`<br/>`换行。
参考文档：
- https://echarts.apache.org/zh/option.html#series-bar.label.formatter
- https://echarts.apache.org/zh/option.html#tooltip.formatter
