### ISSUE TITLE
Example cannot be downloaded

### ISSUE THREAD

**Issue by xxxs** [apache/echarts#12820]
Click to clone no response, please help to solve, thank you
Examples: 
https://gallery.echartsjs.com/editor.html?c=xR0b9wEaUA

**Comment by Ovilia** [comment]
Works fine to me. I forked it to https://gallery.echartsjs.com/editor.html?c=xMvK4q1ypD just now.
Could you try again?

**Comment by xxxs** [comment]
> 对我来说很好。我刚刚将其分叉到https://gallery.echartsjs.com/editor.html?c=xMvK4q1ypD。
> 你能再试一次吗？
还是无法下载哦 亲亲 麻烦帮忙看下 谢谢  @Ovilia

**Comment by xxxs** [comment]
Still unable to download. Please help. Thanks @Ovilia

**Comment by plainheart** [comment]
Hi, @xxxs I've just forked successsfully the example you provided. The url of forked project is https://gallery.echartsjs.com/editor.html?c=xENRY7_aZh.
Do you mean downloading from `toolbox.feature.saveAsImage` or forking in fact?

**Comment by Ovilia** [comment]
@xxxs What do you mean by download?

**Comment by xxxs** [comment]
我想官方示例那样把代码下载下来而不是保存图片, 页面的克隆/保存不是保存代码吗 ? @Ovilia

**Comment by xxxs** [comment]
像官方示例那样把代码下载下来而不是保存图片, 页面的克隆/保存不是用来保存代码吗 ? @Ovilia

**Comment by Ovilia** [comment]
不支持哦
