### ISSUE TITLE
在触屏的电脑或大屏显示器上无法拖动节点

### ISSUE THREAD

**Issue by tikeyc** [apache/echarts#12823]
### Version
4.8.0

### Steps to reproduce
直接使用官网的列子：https://echarts.apache.org/examples/zh/editor.html?c=mix-zoom-on-value
在触屏的电脑或大屏显示器上无法拖动节点。
发现在此之前有人提过类似的问题：
- #9301
- #7406
- #12166

### What is expected?
但更新到echarts4.8.0版本.无法拖动的问题依然存在。只有去修改源码将touchEventsSupported的值强制设置成true后问题便得到了解决。

**Comment by plainheart** [comment]
> 但更新到echarts4.8.0版本.无法拖动的问题依然存在。只有去修改源码将touchEventsSupported的值强制设置成true后问题便得到了解决。

如果按照你说的将`touchEventsSupported`设置为`true`即可解决该问题，那么很有可能是在判断环境是否支持触摸事件的逻辑上存在bug，导致echarts认为当前环境不支持`touchEvents`，有待验证。

**Comment by plainheart** [comment]
@tikeyc 麻烦您使用所拥有的触屏或大屏显示器帮助验证以下问题：
- `window.DocumentTouch && document instanceof DocumentTouch` 的结果是否为 `true`
- `window` 对象中是否有 `ontouchstart` 函数

通过[StackOverflow](https://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript)上的讨论，似乎很难有一种能适用于各种情况的方案。

**Comment by tikeyc** [comment]
@plainheart 
     您好。使用可以触屏的大屏显示器，在控制台打印了window.DocumentTouch && document instanceof DocumentTouch 的结果，以及window 对象中是否有 ontouchstart 函数。
得出的结果都是undefined

**Comment by tikeyc** [comment]
您好，在大屏触摸显示器上验证了，输出结果都是undefined见附件的图片。感谢。

**Comment by tikeyc** [comment]
增加了 "ontouchstart" in window的验证结果，结果为false

**Comment by plainheart** [comment]
@tikeyc `window.matchMedia("(pointer: coarse)").matches`的返回结果是否为`true`？

**Comment by tikeyc** [comment]
@plainheart 
window.matchMedia("(pointer: coarse)").matches的返回结果是false

**Comment by tikeyc** [comment]
@plainheart 
您好，请问有好的解决方案吗？

**Comment by plainheart** [comment]
抱歉暂时没有，不确定是否能够修复，这可能需要进行讨论，目前如果确定设备支持触屏，还是建议先手动设置 `touchEventsSupported`为`true`。

**Comment by plainheart** [comment]
@tikeyc Hi~ 能否告知下使用的浏览器以及浏览器的 `navigator.userAgent` ？

**Comment by tikeyc** [comment]
@plainheart 
使用的浏览器是: Chrome;
navigator.userAgent的值是："Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

**Comment by yibaibai121** [comment]
5.0版本此方法也不行了

**Comment by liumouren34** [comment]
请问5.0以上版本如何解决这个问题，@yibaibai121

**Comment by Poposoh** [comment]
> 请问5.0以上版本如何解决这个问题，[@yibaibai121](https://github.com/yibaibai121)

请问你解决这个问题了吗？如何在可以触摸的windows屏幕下既能使图旋转还可以点击图上的点
