### ISSUE TITLE
[Candlestick][markpoint]"highest" is marked at the wrong place when yAxis type is "log" 

### ISSUE THREAD

**Issue by bt4baidu** [apache/echarts#12839]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=candlestick-sh](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-sh)

### Steps to reproduce
Open the offical example and modify the "yAxis" configuration as following:  
  yAxis: {
        scale: true,
        type: 'log',
        logBase: 1.1,
        splitArea: {
            show: true
        }
    },

then, you can find the highest point is marked at the wrong place

### What is expected?
the highest point is marked correctly when yAxis type is log

### What is actually happening?
the highest point is marked wrong  when yAxis type is log, while the lowest point is marked correctly.

---
当日线图的yAxis设置为log类型时(type: 'log')，markpoint无法正确标识当前展示区间的最高值

**Comment by susiwen8** [comment]
This might be caused by `dataZoom`

**Comment by susiwen8** [comment]
Nope, not `dataZoom`

**Comment by bt4baidu** [comment]
the lowest is marked correctly, while the highest point looks like to be marked at the stick that has the lowest highest value ...

**Comment by susiwen8** [comment]
I'll check it out
