### ISSUE TITLE
[calendar] Is there any way to customize calendar to show workdays only

### ISSUE THREAD

**Issue by bt4baidu** [apache/echarts#12847]
### What problem does this feature solve?
It would be very helpful if we can customize calendar to show workdays only, when calendar is used to show market events.

希望提供日历坐标中星期轴的定制选项，可以配置为只显示工作日、不显示周末；用于展示市场交易信息

### What does the proposed API look like?
Maybe like:
```javascript
calendar: [{
    dayLabel: {
        nameMap: ['一', '二', '三', '四', '五']
    }
}]
```
Or:
```javascript
calendar: [{
    weekend: false
}]
```

**Comment by BobbbCR** [comment]
Hello everybody,
this is actually also a requirement i have on the calendar.
Also, I only want to display the days of the week and not the weekends.

Best wishes
BoobyCR
