### ISSUE TITLE
三星手机点击事件不灵敏问题

### ISSUE THREAD

**Issue by adu8419** [apache/echarts#12854]
问题描述：
   雷达图 点击事件
主要代码：
   silent: false,
   triggerEvent: true,

   this.charts.on('click', function (params) {
       console.log('charts onclick', params)
  }）

实验了各种版本都是在三星手机点击事件 时而能触发 时而不能触发，总之就是需要多点击很多次才可能触发

**Comment by adu8419** [comment]
三星S8

**Comment by Ovilia** [comment]
目前这个事件只会在点中数据点的时候触发，所以可以尝试把数据点的图形大一点。

**Comment by adu8419** [comment]
> 目前这个事件只会在点中数据点的时候触发，所以可以尝试把数据点的图形大一点。

我是要点击雷达图的指标器上的文字

**Comment by adu8419** [comment]
单独复制了官方的demo 过去加了个点击事件 还是如此
<pre> 

<!DOCTYPE html>
<html lang="en">
<head> 
    <meta charset="utf-8"> 
    <title>CSS pointer events</title> 
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/4.8.0/echarts.min.js"></script>
    <style> 
        body {
            margin: 0;padding: 0;
        }
        #root {
            width: 100%;
            height: 100vh;

        }
    </style> 

</head>
<body>
        <div id="root"> </div>
    <script> 

         let myChart = echarts.init(document.getElementById('root')),
             option = getOptions();

         myChart.setOption(option);

         myChart.on('click', function(params) {
            alert(2)
         })

        function getOptions() {
            return  {
                title: {
                    text: '基础雷达图'
                },
                tooltip: {},
                legend: {
                    data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
                },
                radar: {
                    // shape: 'circle',
                     center:  ['50%', '50%'],
                    radius: '70%',
                    nameGap: 20,
                    name: {
                        textStyle: {
                            color: '#fff',
                            backgroundColor: '#999',
                            borderRadius: 3,
                            lineHeight: 100,
                            fontSize: 48,
                            padding: [3, 5]
                        }
                    },
                    indicator: [
                        { name: '销售（sales）', max: 6500},
                        { name: '管理（Administration）', max: 16000},
                        { name: '信息技术（Information Techology）', max: 30000},
                        { name: '客服（Customer Support）', max: 38000},
                        { name: '研发（Development）', max: 52000},
                        { name: '市场（Marketing）', max: 25000}
                    ],
                    triggerEvent:true,
                    silent: false
                },
                series: [{
                    name: '预算 vs 开销（Budget vs spending）',
                    type: 'radar',
                    // areaStyle: {normal: {}},
                    data: [
                        {
                            value: [4300, 10000, 28000, 35000, 50000, 19000],
                            name: '预算分配（Allocated Budget）'
                        },
                        {
                            value: [5000, 14000, 28000, 31000, 42000, 21000],
                            name: '实际开销（Actual Spending）'
                        }
                    ]
                }]
            };



        }











 
    </script>



</body>
</html>
</pre>

**Comment by Ovilia** [comment]
文字目前不支持点击事件，5.0 会支持。

**Comment by adu8419** [comment]
好吧 谢谢你的解答。。。 
不过对于你的回答我还是很有疑问， 因为 其他手机都支持的，就三星手机不灵敏（不是不能点击）
通过判断点击事件的回调中的params.name 来判断是点的某个文字
