### ISSUE TITLE
echarts tree图单个节点设置linestyle无效

### ISSUE THREAD

**Issue by ferrydjing** [apache/echarts#12869]
### Version
4.7.0

### Reproduction link
[https://codepen.io/ferrydjing/project/editor/ZMvYEp](https://codepen.io/ferrydjing/project/editor/ZMvYEp)

### Steps to reproduce
如codepen中的例子，当data中节点有children的设置linestyle是有效的，但是没有children的节点设置则不生效

### What is expected?
单个节点设置lineStyle

### What is actually happening?
实际单个节点linestyle不生效

### 示例说明
效果图如下
![image](https://user-images.githubusercontent.com/27794468/86112087-209d6e00-bafa-11ea-8e86-31ea3f11defc.png)

![image](https://user-images.githubusercontent.com/27794468/86110141-c3a0b880-baf7-11ea-85aa-3328e03b363d.png)
这样是可以的，但是所有children中的节点都是虚线了

![image](https://user-images.githubusercontent.com/27794468/86110244-e9c65880-baf7-11ea-9aa8-40970e6046bc.png)
这样是不行的

**Comment by plainheart** [comment]
看起来像是个bug，不过[文档](https://echarts.apache.org/zh/option.html#series-tree.data)中似乎并未提及可以为单个data设置 `lineStyle`，只有对整个系列生效的 [`lineStyle`](https://echarts.apache.org/zh/option.html#series-tree.lineStyle)
或者是我错过了什么？

**Comment by ferrydjing** [comment]
> 看起来像是个bug，不过[文档](https://echarts.apache.org/zh/option.html#series-tree.data)中似乎并未提及可以为单个data设置 `lineStyle`，只有对整个系列生效的 [`lineStyle`](https://echarts.apache.org/zh/option.html#series-tree.lineStyle)
> 或者是我错过了什么？

文档确实是没有提及给单个data设置 `lineStyle`, 但是实际使用是可以设置的。不清楚是否是支持的

**Comment by CodeBogey** [comment]
data.children[i].lineStyle = {
          color: '#2b3878',
          width: 2
}
这样也可以单个设置

**Comment by ferrydjing** [comment]
> data.children[i].lineStyle = {
> color: '#2b3878',
> width: 2
> }
> 这样也可以单个设置

这样应该不行吧，这种和我的用法没有区别的样子
