### ISSUE TITLE
Misleading dataZoom for the clustered charts

### ISSUE THREAD

**Issue by djanusausk** [apache/echarts#12872]
### Version
4.1.0-release

### Steps to reproduce
Hi,

There seems to be a limitation on how dataZoom draws the timeline for the clustered charts.

Consider following example. Clustered bar chart with the categorical legend.
[image](https://user-images.githubusercontent.com/67644261/86138414-589ab600-bae6-11ea-88d9-fa7931bc07f6.png)

"Matcha Latte" has a significant peak on the 2016 (check example under additional comments). However, dataZoom does not correctly indicate this. It seems that dataZoom always draws timeline for the first category which is "2015" in the example above. Instead as a user I would expect that dataZoom displays timeline across the total of the categorical values. It should also respond correctly based on the categories selected/highlighted.

I did not come across any configuration option to support above. Could you please advise?
Thanks in advance,
D

### What is expected?
dataZoom should always calculate total values across categories and draw timeline based on that data.

### What is actually happening?
dataZoom always displays timeline of the first category selected/highlighted in the clustered chart.

---
```
option = {
    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['product', '2015', '2016', '2017'],
            ['Matcha Latte', 43.3, 185.8, 93.7],
            ['Milk Tea', 83.1, 73.4, 55.1],
            ['Cheese Cocoa', 86.4, 65.2, 82.5],
            ['Walnut Brownie', 72.4, 53.9, 39.1]
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
     dataZoom: [
            {
                show: true,
                type: 'slider',
                start: 0,
                end: 100,
                filterMode: 'filter'
            },
            {
                type: 'inside',
                start: 0,
                end: 100
            },
            {
                show: false,
                yAxisIndex: 0,
                filterMode: 'empty',
                width: 30,
                height: '80%',
                showDataShadow: false,
                left: '93%'
            }
        ],
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};
```

**Comment by 100pah** [comment]
Currently the implementation of the "overview diagram" in dataZoom is too simple, where only one series is used.
Probably it should be considered to be enhanced to indicate the character of the series.
