### ISSUE TITLE
使用echarts.connect 实现多图tooltip联动显示时 ，如果某个图折线存在空数据，联动失效

### ISSUE THREAD

**Issue by huanglp3368** [apache/echarts#12877]
### Version
4.7.0

### Reproduction link
[https://codepen.io/flyfly6/pen/vmGzgq](https://codepen.io/flyfly6/pen/vmGzgq)

### Steps to reproduce
connect

### What is expected?
实现即使某个charts数据有空值 也能联动

### What is actually happening?
数据有空值时 联动失效

**Comment by huanglp3368** [comment]
有人看这个问题么  半个月了 一直没人回复？？？

**Comment by baokeyu123** [comment]
@huanglp3368 how to resolve this problem？ thanks~

**Comment by wwwwwwwwwy** [comment]
也遇到的相同问题，好没有解决。
