### ISSUE TITLE
官方阶梯瀑布图是否有计划支持从400下降800达到-400这样的效果，堆叠柱状图形时问题更明显

### ISSUE THREAD

**Issue by JackHlw** [apache/echarts#12870]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=bar-waterfall2](https://echarts.apache.org/examples/zh/editor.html?c=bar-waterfall2)

### Steps to reproduce
点击https://echarts.apache.org/examples/zh/editor.html?c=bar-waterfall2 官方demo 无法支持从400下降800达到-400这样的效果

### What is expected?
实现从400下降800达到-400这样的效果

### What is actually happening?
辅助隐藏柱子失效

**Comment by pissang** [comment]
官方这个例子还是用两个系列来模拟了瀑布图，会存在这样的问题，可以试试用自定义系列来画
