### ISSUE TITLE
Nanosecond support

### ISSUE THREAD

**Issue by ajebaje** [apache/echarts#12873]
### What problem does this feature solve?
We are working with high precision data for simulation. It needs nanosecond level support.  Does Echart support that today ? If not, is this feature coming ?

### What does the proposed API look like?
Not sure

**Comment by pissang** [comment]
The precision of browsers is limited. You can use `value` axis to present nanosecond..

**Comment by Niproblema** [comment]
@pissang That means values have to use BigInt
