### ISSUE TITLE
饼图标签居中重叠

### ISSUE THREAD

**Issue by ZhouXiaoL** [apache/echarts#12875]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x9Og7OYc_D&v=2](https://gallery.echartsjs.com/editor.html?c=x9Og7OYc_D&v=2)

### Steps to reproduce
饼图标签居中重叠

### What is expected?
饼图标签居中不重叠

### What is actually happening?
重叠

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/master/src/chart/pie/labelLayout.js#L136
https://github.com/apache/incubator-echarts/blob/master/src/chart/pie/labelLayout.js#L219
