### ISSUE TITLE
It is possible to drag a node out of the visible area/canvas in a Sankey diagram

### ISSUE THREAD

**Issue by dominic-simplan** [apache/echarts#12889]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=sankey-energy](https://echarts.apache.org/examples/en/editor.html?c=sankey-energy)

### Steps to reproduce
Drag any node and drop it out of the canvas area. The node is not accessible afterwards anymore.
![sankeyNodeCanvas](https://user-images.githubusercontent.com/22240239/86284243-c926fd00-bbe2-11ea-90e9-cc44662738d2.gif)

### What is expected?
The node cannot be dragged out of the visible area/canvas.

### What is actually happening?
The node can be dragged out of the visible area/canvas

**Comment by dominic-simplan** [comment]
Still relevant.

**Comment by crazywin3** [comment]
Yes this is still relevant!
