### ISSUE TITLE
legend.textStyle backgroundColor image 设置为一个image对象时，image对象的样式不生效

### ISSUE THREAD

**Issue by zmzimpl** [apache/echarts#12894]
### Version
4.8.0

### Steps to reproduce
![image](https://user-images.githubusercontent.com/27490895/86314893-60c83200-bc5b-11ea-82c5-cca4a170ed54.png)
如图，我在image对象上添加了样式属性 filter，用来更改图片的主颜色，更改后的图片如小图所示，然而图表中的图片颜色并没有改变， legend.textStyle.backgroundColor.image 是否只采用图片内容，而不支持图片的样式修改？ 

### What is expected?
支持加载image对象的样式属性

### What is actually happening?
image对象的样式不生效

**Comment by plainheart** [comment]
是的 暂不支持对Image对象设置样式。
