### ISSUE TITLE
convertToPixel() with finder {seriesIndex: ...} failed to return different offset

### ISSUE THREAD

**Issue by DoonPort0422** [apache/echarts#12897]
### Version
4.8.0

### Steps to reproduce
1. Prepare a multiple series bar chart
2. try to use convertToPixel(...) with all series & data

sample: 
https://photos.google.com/share/AF1QipNNyqrqUr2lqCcT1h9mrUgwiIu2ZEoHBGLKzoRMxvtbz-fqCISQUFDtZngibkXHPQ/photo/AF1QipPdS3wO1dv2xmdsjCXBKcuV_w19CZifvkL9dva-?key=cWhkdmlkdXNzU293ZFZXWGNfUUFRVVhoM296MGtR

_Sorry, I don't know why, the myChart.convertToPixel() will thrown exception when it is running in echarts's gallery, 
so, I try to capture the above screenshot to describe the problem._

### What is expected?
different series should return different x-location

### What is actually happening?
but the x-location are same...

**Comment by GenesisCoast** [comment]
I've been having the same problem @DoonPort0422 did you ever manage to resolve it?
