### ISSUE TITLE
axisLabel添加borderType设置选项

### ISSUE THREAD

**Issue by wonderfulxue** [apache/echarts#12908]
### What problem does this feature solve?
目前，axisLabel配置项中仅包含borderColor, borderWidth, borderRadius这3种border相关的配置选项，但是没有borderType的设置选项，默认边框样式只能为"solid"。若添加了borderType配置选项，就能为label配置borderType为“dashed” / "solid" / "dotted"。

同样的，在利用“rich”设置富文本样式的时候，也无法设置borderType。

### What does the proposed API look like?
```
axisLabel: {
      borderWidth: 1,
      borderType: "dashed"  // new feature request
    }
```

**Comment by plainheart** [comment]
ECharts v5 已经支持该配置项，且可以自由设置虚线样式。:)
