### ISSUE TITLE
Left over lines in polyline tree when triggering collapse

### ISSUE THREAD

**Issue by BH010** [apache/echarts#12903]
### Version
4.8.0

### Reproduction link
[https://codepen.io/itealeaf/pen/vYLyVNp?editors=1011](https://codepen.io/itealeaf/pen/vYLyVNp?editors=1011)

### Steps to reproduce
Step 1) Enter "Fish" in the search bar

Step 2) Enter "System Test" in the search bar

### What is expected?
Layout of the tree should be the same for both polyline and curve

### What is actually happening?
In polyline tree, there are remaining lines that are not remove properly.

**Comment by plainheart** [comment]
Thanks, this may be fixed by #12710.

**Comment by BH010** [comment]
Hi, #12710 is still under review right? From how i understand it when i read through it.

**Comment by plainheart** [comment]
Yes, it is now under review and may be included into the next milestone 4.9.0.
