### ISSUE TITLE
Top and Bottom Lable on a Graph Item.

### ISSUE THREAD

**Issue by elipongr** [apache/echarts#12917]
### What problem does this feature solve?
You should be able to add Top and Bottom Label to a graph item, or is there already an existing option besides making 2 items.

### What does the proposed API look like?

![grafik](https://user-images.githubusercontent.com/36076242/86569448-b6a81d00-bf6e-11ea-947d-6fd6a6b55e0d.png)

**Comment by ownedbypeli** [comment]
Hello?

**Comment by JordanFarrow** [comment]
This would be a great feature! 
series.label = array of label objects, so you can position each individually & have formatter for each.

I have a chart which uses graphics.text for top & bottom "labels", but absolute positioning is a nightmare with horizontal stacked bar graph and variable length data set (especially at smaller sets!).

**Comment by ownedbypeli** [comment]
yeah i have done it with 2 circles
