### ISSUE TITLE
关于阶梯瀑布图的样例数据错误

### ISSUE THREAD

**Issue by ZMQ777** [apache/echarts#12913]
### Version
3.2.2

### Steps to reproduce
阶梯瀑布图的合计数据与对应的阶梯值没有对应

### What is expected?
当前阶的合计应是当前阶到初始之间所有阶的总和，而且按照逻辑，总量数组第一个元素为0的情况下，总量数组长度应该比收入，支出数组长度大一个,【0，data1,data1+data2,data1+data2+data3.....】难道总量不应该这么算的吗，然后这么算的话，总量数组的最后一个元素就又无法显示。我想知道这个是我理解错误还是啥

### What is actually happening?
实际合计值错误

**Comment by susiwen8** [comment]
Actually, we do not maintain version 3.x anymore, please upgrade to latest version, which is 4.8
