### ISSUE TITLE
Example: The color of a single series bar chart contains both positive data and negative numbers to be distinguished.

### ISSUE THREAD

**Issue by Wdingding** [apache/echarts#12936]
The color of a single series bar chart contains both positive data and negative numbers to be distinguished.

![9999](https://user-images.githubusercontent.com/26783462/86892496-e9027780-c132-11ea-89f5-d4bb1eaa8b78.png)

**Comment by Ovilia** [comment]
We will make an example like this in our official examples. But no source code changes are required here.
