### ISSUE TITLE
散点图：鼠标悬停到label触发高亮效果

### ISSUE THREAD

**Issue by yishangtanhuan** [apache/echarts#12953]
### Version
4.7.0

### Reproduction link
https://gallery.echartsjs.com/editor.html?c=effectScatter-map

### Steps to reproduce
非bug

### What is expected?
鼠标悬停到label触发高亮效果

### What is actually happening?
鼠标悬停到图标上，散点图高亮；悬停到label上不能高亮

**Comment by plainheart** [comment]
这个在下个大版本5.0应该就能实现。
