### ISSUE TITLE
自定义系列，数据第一个维度为ordinal类型,api.value()读取时值不正确

### ISSUE THREAD

**Issue by Trendymen** [apache/echarts#12952]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xKVaWRy2QO](https://gallery.echartsjs.com/editor.html?c=xKVaWRy2QO)

### Steps to reproduce
数据第一个维度为ordinal类型,api.value()读取时值不正确,41行,api.value(0)得到的并不是字符串类型而是像0,1,2的数据项索引。而如果把字符串放到第一个维度之后并定义为ordinal类型则又能正确读取。

### What is expected?
example:41 line,
api.value(0) return the string type value defined in data.

### What is actually happening?
The api.value(0) return the index of data item in data array.

---
Sorry about  using chinese to issue.

**Comment by Ovilia** [comment]
Seems to be a bug. Probably has something to do with dataset.

**Comment by LemniscateX** [comment]
Hi there, I am trying to fix this issue.

**Comment by susiwen8** [comment]
@LemniscateX Great, Thanks for you help
