### ISSUE TITLE
多y轴line showtip的一个疑问

### ISSUE THREAD

**Issue by theDoinb** [apache/echarts#12950]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xAzDC4SR72&v=1](https://gallery.echartsjs.com/editor.html?c=xAzDC4SR72&v=1)

### Steps to reproduce
图表在一个范围内似乎showtip 失效还是被遮挡的感觉。
例如我打开个链接那图，将浏览器缩小至916*250，910*183...，就缩小到差不多随意伸缩下应该都能看到轮播消失了，
往大或往小showtip似乎都是正常的

### What is expected?
多y轴showtip是正常的

### What is actually happening?
多y轴showtip在某些大小下是异常的

**Comment by Ovilia** [comment]
如果要始终显示，可以将 [tooltip.alwaysShowContent](https://echarts.apache.org/zh/option.html#tooltip.alwaysShowContent) 设为 `true`.

**Comment by theDoinb** [comment]
e, 我认为alwaysShowContent 是对于我这个问题是没有帮助的，

我指的是在当这个多Y轴图表在一个小的宽高时，

可以尝试伸缩浏览器就我提供的图表链接，

toolTip会消失，加入alwaysShowContent ，虽然一直显示，但是会发现tooltip内容是不会变化的，

直到拉伸到一个大一点的宽高，轮播又恢复正常了
