### ISSUE TITLE
Line chart(possibly other charts as well) series re-render issue from clicking legend hide/show

### ISSUE THREAD

**Issue by Derek-Xiang** [apache/echarts#12967]
### Version
4.6.0

### Steps to reproduce
用同样的json cofig 不能再echart  web 上面复现这个问题。 我描述一下：

用React 来做的，
echarts-for-react: ^2.0.13
echarts: ^4.6.0

当有多个line series时候，有相应的legend 显示。 
第一次点击一个legend， hide 对应series， 完美。
第二次点击同一个， 应该把刚才hide 的 series 显示回来， 但并没有， 反而只显示的line series 里面的symbol, 而线消失了

这个时候，如果，扩大一下浏览器大小，或者点击其他legend， 刚刚那个问题legend 就正确render了

所以感觉是render的问题。

因为其实点击 legend hide/show 这个功能，其实有动画存在，所以我尝试 animation: false
确实就阻止了这个问题， 但还想要那个动画。

求教各路神仙，有没有想法

### What is expected?
就是点击legend的时候 hide/show 好使，且不用我关闭animation

### What is actually happening?
hide的时候好使，再次点击，只渲染symbol，没有line

**Comment by Ovilia** [comment]
Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM or https://gallery.echartsjs.com/editor.html.

**Comment by Derek-Xiang** [comment]
这个很难复现，我目前找到一个解决方案：
listen legend的点击event，一旦点击，就用这个echart instance来setOption again。
可以解决，目前还没有别的问题。
但问题始终存在， 我会找一个看看能不能在codepan上复现
