### ISSUE TITLE
散点图颜色不改变问题

### ISSUE THREAD

**Issue by cyang52** [apache/echarts#12963]
### Version
4.6.0

### Steps to reproduce
根据：
```
data1 = [
[[1,2,3],'Mon'],
[[2,3,4],'Tues'],
[[3,4,5],'Wed']
]
```
构造散点图。现在想使用if 判断让散点图显示同一个颜色或者根据['Mon','Tues','Wed']显示不同颜色。
比如：

```
var C = 1；
var option = {
...
color: C == '1' ? ['#eb8146',] : ['#d95850','#eb8146','#ffb248'],
....
}
```

但是这样做颜色并不会改变。

### What is expected?
散点图颜色根据if判断改变

### What is actually happening?
散点图颜色未改变

**Comment by plainheart** [comment]
可以考虑使用 `itemStyle` 中的 [`color`](https://echarts.apache.org/zh/option.html#series-scatter.itemStyle.color) 回调函数。
