### ISSUE TITLE
饼图颜色设定

### ISSUE THREAD

**Issue by magicdict** [apache/echarts#12964]
### Version
4.8.0

### Steps to reproduce
按照文档的说法，饼图的Series是没有color属性的，itemStyle是有这个属性的。

### What is expected?
颜色设置正确。

### What is actually happening?
实际发现，如果将颜色列表，也就是文档说的调色盘，设在option或者饼图的series的color属性，是没有问题的。
但是设置在itemStyle的color里面会使得整个颜色变成黑色。

---
最近在封装eCharts，这样的文档和实际不符的问题，碰到好几个了。
eCharts是一个好项目，不过，文档还是需要好好修订，你们新的试一试功能虽然不错，但是，文档的准确性提高不了，这些功能也是鸡肋。

**Comment by pissang** [comment]
itemStyle.color 是不支持数组的，它设置的是图形的颜色。只有 option.color 是调色盘

**Comment by magicdict** [comment]
改一下文档吧，Series的Color属性在文档里面是没有的。的确，itemStyle应该是单个颜色。
