### ISSUE TITLE
echarts的地图中能否给label添加引导线

### ISSUE THREAD

**Issue by Guanrui1** [apache/echarts#12971]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x_kEnG-Ggq](https://gallery.echartsjs.com/editor.html?c=x_kEnG-Ggq)

### Steps to reproduce
如题

### What is expected?
想要把echarts地图终得label对应的文字和对应点之间加上引导线

### What is actually happening?
目前没能做到

---
可以实现不？

**Comment by plainheart** [comment]
你想要的是否是这样？#12911

**Comment by Guanrui1** [comment]
> 你想要的是否是这样？#12911
![](https://user-images.githubusercontent.com/841551/86528535-8fecd680-bedb-11ea-98a9-68d1a7cc4674.gif)
和这个一样，我就是想实现地图的label用引导线指向目标点，这个就是我要的效果但是我没找到源码

**Comment by plainheart** [comment]
目前版本还没有，这个是下个大版本 [5.0](https://github.com/apache/incubator-echarts/milestone/10) 的一个新特性。

**Comment by snowiceyeah** [comment]
什么时候发布5.0新版本呢？

**Comment by plainheart** [comment]
发布计划在置顶issue中有说明：5.0的Alpha版本预计于7月下旬发布，稳定版预计于9月下旬发布。
具体进展可以关注下置顶issue：[Progress of Next Major Version: 5.0(#12926)](https://github.com/apache/incubator-echarts/issues/12926) 以及 5.0 的 [Project ](https://github.com/apache/incubator-echarts/projects/6)
