### ISSUE TITLE
npm install not working with canvas v2.6.0

### ISSUE THREAD

**Issue by YuriGor** [apache/echarts#12972]
### Version
4.8.0

### Steps to reproduce
clone repo on Ubuntu 20.04 and do npm install

### What is expected?
npm install complete succesfully

### What is actually happening?
gyp failed

---
bump canvas version to v2.6.1 seems to help

**Comment by plainheart** [comment]
Could you be more specific on this? If possible, it's better to provide more detailed information about the error.
