### ISSUE TITLE
Display Failure when trying to assign xAxis data when xAxis.type is set to 'time'

### ISSUE THREAD

**Issue by SimZhou** [apache/echarts#12974]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xb76W50gJk&comment=0](https://gallery.echartsjs.com/editor.html?c=xb76W50gJk&comment=0)

### Steps to reproduce
1. set a time series data with timestamps as x value, e.g. 
```
x=[1594830880000, 1594830880000+200, 1594830880000+400, 1594830880000+600, 1594830880000+800, 1594830880000+1000]
y=[1,5,2,3,7,9]
```

2. display it as a line chart, with x set in xAxis.data, y set in series.data
```
option = {
    title: {
        text: 'Dynamic Time Series'
    },
    xAxis: {
        type: 'time',
        data: x
    },
    yAxis: {
        type: 'value',
    },
    series: [{
        name: 'Mock Data',
        type: 'line',
        data: y
    }]
};
```

### What is expected?
There should be 6 items in xAxis and the chart should display correctly. 
![image](https://user-images.githubusercontent.com/11748629/87576829-87c73f00-c704-11ea-95d5-ddfb4d5d7d09.png)

### What is actually happening?
The chart displays incorrectly, with wrong xAxis labels: 
![image](https://user-images.githubusercontent.com/11748629/87576797-7d0caa00-c704-11ea-8ab5-1a112b8ea9fe.png)

---
moving x into the first column in series.data could solve the problem. 
e.g. pass the follow data item into series.data:
```
data = [
    [1594830880000, 1],
    [1594830880000+200, 5],
    [1594830880000+400, 2],
    [1594830880000+600, 3],
    [1594830880000+800, 7],
    [1594830880000+1000, 9]
]
```
However I still regard this as an issue, since there should be no reason we can't set xAxis.data when xAxis.type is set to 'time'?

**Comment by Ovilia** [comment]
I'm afraid this is not a bug. The `time` type axis doesn't take number arrays because it's continuous. Only `category` typed axis can take number arrays as value.

**Comment by SimZhou** [comment]
> I'm afraid this is not a bug. The `time` type axis doesn't take number arrays because it's continuous. Only `category` typed axis can take number arrays as value.

Well, if I am not getting it wrong, the `time` axis does take number arrays, when the number array is set in the first column of `series.data`? The first chart in the question would be an example.

**Comment by Ovilia** [comment]
The data

```js
data = [
    [1594830880000, 1],
    [1594830880000+200, 5],
    [1594830880000+400, 2],
    [1594830880000+600, 3],
    [1594830880000+800, 7],
    [1594830880000+1000, 9]
]
```

is a valid form for data, but not in the time axis.
