### ISSUE TITLE
make markpoint label clickable 

### ISSUE THREAD

**Issue by GaspardC** [apache/echarts#12986]
### What problem does this feature solve?
I have a scatter series with markpoint
when clicked each markpoint has a label 
I would like to make the label clickable (respond to click events)

### What does the proposed API look like?
add a triggerEvent:true to the markdown : { data : { label : { triggerEvent: true }}}

**Comment by wf123537200** [comment]
the click event of the markpoint may be use like 
```
myChart.on('click', function (params) {
    if (params.componentType === 'markPoint') {
        // clicked on markPoint
        if (params.seriesIndex === 5) {
            // clicked on a markPoint which belongs to a series indexed with 5
        }
    }
    else if (params.componentType === 'series') {
        if (params.seriesType === 'graph') {
            if (params.dataType === 'edge') {
                // clicked on an edge of the graph
            }
            else {
                // clicked on a node of the graph
            }
        }
    }
});
```

The document link:  [Events and Actions in ECharts](https://echarts.apache.org/en/tutorial.html#Events%20and%20Actions%20in%20ECharts)

**Comment by GaspardC** [comment]
@wf123537200 thanks
when I click on the markpoint directly I catch the event but I am interested in clicking on the label itself and I don't seem to be able to catch a click event. do you have an idea how ? 
<img width="318" alt="Capture d’écran 2020-07-23 à 09 54 31" src="https://user-images.githubusercontent.com/9252579/88263713-be83f300-ccca-11ea-9ee4-efac4a574958.png">

**Comment by guixian95** [comment]
@GaspardC Is this problem solved? I have  same problem ...
