### ISSUE TITLE
series.bar.label 及 series.line.label 点击无效

### ISSUE THREAD

**Issue by yvv11520** [apache/echarts#12999]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xyfKams4BO&v=2](https://gallery.echartsjs.com/editor.html?c=xyfKams4BO&v=2)

### Steps to reproduce
点击拆线文字区域或图标区域

### What is expected?
弹出 alert 弹窗

### What is actually happening?
没有进入点击事件

**Comment by plainheart** [comment]
The coming next big version `5.0` should support the clickable label.
