### ISSUE TITLE
xAxis type 'time' shows dates outside range

### ISSUE THREAD

**Issue by dwolny** [apache/echarts#12995]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/94yfxzmb/](https://jsfiddle.net/94yfxzmb/)

### Steps to reproduce
1. Start jsfiddle

### What is expected?
xAxis time labels from range, not from past/future

### What is actually happening?
ECharts shows dates from past/future. In the example, time range is July 2020, but labels show May and August

**Comment by susiwen8** [comment]
In 5.0, We will improve `time` axis, which is in progress, branch `time-formatter`
