### ISSUE TITLE
symbolsize 值域特别大时如何保证散点图圆点大小适中

### ISSUE THREAD

**Issue by cyang52** [apache/echarts#12996]
### Version
4.6.0

### Steps to reproduce
加入我的数据集 symbol size 这一项值域特别大（100000 ～10 ）此时在散点图中圆点大小会差别很大，甚至干扰x轴y轴，如何让这些圆点在看得出大小的情况下，尽量适中大小且不影响视图？

### What is expected?
散点图大小适中，不影响视图阅读

### What is actually happening?
散点图圆点过大或者过小

**Comment by plainheart** [comment]
有尝试通过回调函数自定义 symbolSize 吗？

**Comment by cyang52** [comment]
有使用过，不过可能size 数值太大 效果不好。
比如：
1: [3453, 6214, 83008]
2: (5) [1856, 3743, 26825]
3: (5) [4242, 242, 14225]
4: (5) [4095, 110, 13698]
5: (5) [3389, 92, 8516]
6: (5) [312, 17427, 7491]
7: (5) [2312, 31, 7032]
8: (5) [2653, 563, 6853]
9: (5) [1012, 12, 2617]
10: (5) [1660, 25, 2298]
11: (5) [1073, 332, 122]
12: (5) [353, 1, 8,]
13: (5) [78, 1086, 2]
你可以看到值域从  83008～2，我的回调并不能很好满足。
我也想过if else 判断，一个范围一个回调函数 也不太行

**Comment by quillblue** [comment]
@cyang52 试试在回调函数里用对数来算symbolSize?
