### ISSUE TITLE
custom   line displayed  is inconsistent with axis

### ISSUE THREAD

**Issue by MeijunZhu** [apache/echarts#13002]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=custom-bar-trend](https://echarts.apache.org/examples/zh/editor.html?c=custom-bar-trend)

### Steps to reproduce
 line displayed  is inconsistent with axis

### What is expected?
consistent

### What is actually happening?
inconsistent

**Comment by MeijunZhu** [comment]
![image](https://user-images.githubusercontent.com/56335769/88029412-8f576f80-cb6c-11ea-895d-8554d7e32757.png)
![image](https://user-images.githubusercontent.com/56335769/88029449-9c745e80-cb6c-11ea-9f06-fe66639795d4.png)

**Comment by MeijunZhu** [comment]
all data less than 1000
but the line is higher than 1000

**Comment by plainheart** [comment]
The red line is a custom series indicating the trend of bar series and it's not used to indicate the actual data of bars.
If you want to keep them consistent, just remove the 46th code line `point[1] -= 20;` in `renderItem` function.
