### ISSUE TITLE
x-axis renders series multiple times

### ISSUE THREAD

**Issue by praveenchandkasarla** [apache/echarts#13001]
### Version
4.8.0

### Steps to reproduce
I have 2 x-axis, 1 y-axis and 2 series even after adding xAxisIndex same series is rendered twice everytime. Will impact performance.

### What is expected?
xAxisIndex:0 in series is not working as expected 

### What is actually happening?
xAxisIndex:0 in series is not working as expected

**Comment by quillblue** [comment]
Hi, would you please be kind to build a demo reproducing/representing your issue met on [Gallery Editor](https://gallery.echartsjs.com/editor.html) so that the community could better understanding the issue? Thank you.
