### ISSUE TITLE
echart 3D散点图-bug

### ISSUE THREAD

**Issue by zhengxs216** [apache/echarts#13005]
### Version
4.8.0

### Steps to reproduce
如果3D散点图只有一个点的话，tooltip无法显示弹框

### What is expected?
只有一条数据的时候，可以显示tooltip弹框

### What is actually happening?
只有一条数据的时候，无法显示tooltip弹框

**Comment by liangyinga** [comment]
多个散点的时候，少部分散点也无法显示tooltip以及点击事件，另外部分正常

**Comment by liangyinga** [comment]
多个散点的时候，少部分散点也无法显示tooltip以及点击事件，另外部分正常
