### ISSUE TITLE
为tooltip 循环添加新的元素无效问题

### ISSUE THREAD

**Issue by cyang52** [apache/echarts#13000]
### Version
4.6.0

### Steps to reproduce
假设有这么一组数据：

var name1 = ['ww','22','ee'];

我想将这个数据循环添加进tooltip 里，使用for 循环只能添加进入第一个元素：
    
    formatter: function (obj) {
    var value = obj.value;

       for(var i = 0; i< 3;i++){
           var a = '';
           a += '<div>'+ obj.seriesName  + entitiy[i]+'</div>'
       }
        return a;

### What is expected?
将data1 中的元素添加进tooptip

### What is actually happening?
只能添加进第一个（‘ww’）

**Comment by plainheart** [comment]
为什么要在 for 循环体内进行 return，那样不是只会执行一次吗？

**Comment by cyang52** [comment]
不好意思 我重新更新了代码 之前那个错误的

**Comment by plainheart** [comment]
抱歉不是很理解，能再具体描述下需求吗？

**Comment by cyang52** [comment]
我想在tooptip 中， seriesName 后面添加上 一个entity name，这个name 来自于前面的array，需要按顺序添加进去，一个点对应一个seriesName 对应一个entity name。

**Comment by plainheart** [comment]
从代码里看，你在 for 循环体内声明的变量 a，如果想要拼接，应该在 for 循环上边声明变量 a。
```js
formatter: function (obj) {
  var value = obj.value;
  var a = '';
  for(var i = 0; i< 3;i++) {
      a += '<div>'+ obj.seriesName  + entitiy[i]+'</div>'
  }
  return a;
}
```

**Comment by cyang52** [comment]
嗯嗯 谢谢，但是我试了一下 每一个点都打印了wwweee， 我希望还是分开的，一个点一个，按顺序被添加

**Comment by plainheart** [comment]
fomatter 的回调参数里有 dataIndex 和 seriesIndex 分别标识 数据项索引 和 系列索引，可以根据这两个参数进行判别。

**Comment by cyang52** [comment]
我看到文档里面写 dataindex ：数据在传入的 data 数组中的 index，这个data 不是series 传入的series.data 是吧？

**Comment by plainheart** [comment]
是的
