### ISSUE TITLE
饼图label使用换行\n，同时定义了lineHeight时会导致两个label重叠

### ISSUE THREAD

**Issue by Chef5** [apache/echarts#13006]
### Version
4.8.0

### Steps to reproduce
step 1：label使用`\n`换行：formatter: '{b}\n{c}'
step 2：给label文字定义行高：lineHeigt: 18

以下是完整配置：
``` javascript
let data = [
    {name: '中央环保督察', value: 100},
    {name: '大气污染防治', value: 300},
    {name: '水污染防治', value: 1},
    {name: '土壤污染防治', value: 1},
    {name: '自然生态保护', value: 100},
    {name: '其他', value: 54},
]
option = {
      grid: {
          top: 16,
          left: 0,
          right: 0,
          bottom: 0,
          containLabel: true
      },
      color: ['#36C977', '#FFCC37', '#F65546', '#00A2FF', '#4B79FF', '#A56FFF'],
      // backgroundColor: '#fff',
      series: [
        {
          name: '数据',
          type: 'pie',
          radius: [39.2, 52],
          clockwise: false, // 逆时针
          hoverAnimation: false,
          avoidLabelOverlap: true,
          minAngle: 5,
          data: data,
          label: {
            fontSize: 12,
            color: '#333333',
            position: 'outer',
            alignTo: 'edge',
            margin: 0,
            lineHeight: 18,  // 设置了行高后，换行的标签可能会出现重叠
            formatter: '{b}\n{c}（个）',
          },
          labelLine: {
            lineStyle: {
              width: 1,
              opacity: 0.5,
              color: '#B2B2B2'
            }
          },
          itemStyle: {
            borderColor: '#fff',
            borderWidth: 1
          }
        }
      ]
    };
```

### What is expected?
label不重叠

### What is actually happening?
相邻数据较小时，label会重叠

---

开启`avoidLabelOverlapin`，也是会重叠的。查了许多，也看过 issue ，这个重叠问题目前还是无法解决。

![微信截图_20200722172827](https://user-images.githubusercontent.com/38160059/88160478-41f90200-cc41-11ea-8eed-ffd356ca4de7.png)

[相似issue：11828](https://github.com/apache/incubator-echarts/issues/11828)

**Comment by yangjocy** [comment]
Any updates? Same issue here.

**Comment by pissang** [comment]
We've fixed this issue in the 5.0

**Comment by yangjocy** [comment]
> We've fixed this issue in the 5.0
> 
> ![image](https://user-images.githubusercontent.com/841551/92690474-a730c000-f373-11ea-9908-b64d7a158b49.png)

That's great? When will 5.0 be released? Checked the Releases, currently the latest version is 4.9.

**Comment by yangjocy** [comment]
@pissang BTW, any workaround before 5.0?

**Comment by pissang** [comment]
5.0 will be released soon. In the next month if everything goes well.

**Comment by surplus-cat** [comment]
![image](https://user-images.githubusercontent.com/20469400/103852794-9c9af300-50e7-11eb-8734-91b172da35fc.png)
貌似可以用rich 解决。

**Comment by Patrick-Jun** [comment]
> ![image](https://user-images.githubusercontent.com/20469400/103852794-9c9af300-50e7-11eb-8734-91b172da35fc.png)
> 貌似可以用rich 解决。

刚试了一下，如果将rich里的lineHeight设置大一点，比如18，还是会重叠的。
你这样在rich里设置lineHeight: 10和在外面设置lineHeight: 10效果是一样的。

**Comment by Ovilia** [comment]
Fixed
