### ISSUE TITLE
多维度柱状图展示（cluster bar）

### ISSUE THREAD

**Issue by doufugeshihua** [apache/echarts#13014]
### What problem does this feature solve?
x轴上能展示多个维度，类似多个x轴，但又有区别，希望是在同一个坐标系中的多维度展示。比如展示省市区，广东省为一个x轴，各个市为一个x轴，最后区为一个x轴，他们都在一个坐标系中，能体现层级关系展示

### What does the proposed API look like?
xAxis: [
  {
   省
 }，
 {
   市
 }，
 {
   区
 }
]

**Comment by CreasyWorld** [comment]
解决了么
