### ISSUE TITLE
Custom series Bug

### ISSUE THREAD

**Issue by gitcen** [apache/echarts#13018]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=custom-profile](https://echarts.apache.org/examples/en/editor.html?c=custom-profile)

### Steps to reproduce
1. Set line 3 var dataCount to X (X>=1000, precisely, 999 would not reproduce the bug).
2. RUN
3. Zoom in the profile chart

### What is expected?
There should be one new clear profile chart

### What is actually happening?
The original chart (before zoom operation) remain in the new chart.
![image](https://user-images.githubusercontent.com/38746694/88378329-5bca4e80-cdd3-11ea-8d1b-176037f71990.png)

---
We use custom series to build chart with larget data size( > 10000). And a similar bug appears. To fingure out the reason, we try the example 'custom-profile' on the echarts offical website and find this bug.

By the way, set the dataZoom.maxSpan to a small number (maybe <=8?) could avoid this bug temporarily. But if we set maxSpan, zoom is bound, we couldn't zoom out the chart to what we wanted.

**Comment by pissang** [comment]
Should have been fixed in the 5.1.2
