### ISSUE TITLE
关于笛卡尔坐标系X轴labe间隔算法问题

### ISSUE THREAD

**Issue by Liz2Z** [apache/echarts#13017]
### Version
4.8.0

### Steps to reproduce
我需要在项目中实现如下x轴效果:
```
--------------------------------  x轴线
     长
     名
     字
     .
     .
     .
```

formatter是这样的：
```
formatter: (text)=>{ 
    return `${text.split('').join('\n')}{ellipsis|.\n.\n.}`
}
```
如果让竖直的**...**的行高与普通文本一致，显然会很丑陋，所以我需要通过rich来修改它们的行高，让它们靠的近一些。

此时问题就来了，在计算label间距的函数`calculateCategoryInterval`中，是将formtter返回值当作普通文本直接检测，而不是将rich解析出来再检测（为了性能？）：

```
var rect = textContain.getBoundingRect(labelFormatter(tickValue), params.font, 'center', 'top');

// 正确的宽度检测            实际(但错误)的宽度检测
// ------------------------------------------
//     x                                 x
//     x                                 x{ellipsis.
//     .                                  .
//     .                                  .
//     .                             
```

这就导致了主观上应该密集的label间隔因为错误的检测方式变得稀疏

下面两种实现，主观上label间隔应该相同
![image](https://user-images.githubusercontent.com/30578440/88292560-5cf47080-cd2c-11ea-9960-d576359333d1.png)
![image](https://user-images.githubusercontent.com/30578440/88292631-785f7b80-cd2c-11ea-816a-a09b7b85a0e4.png)

### What is expected?
优化宽度检测算法。或者能有什么其他实现？

### What is actually happening?
宽度检测算法错误

**Comment by susiwen8** [comment]
We are having some  big progress on label position in `next` branch, which we anticipate to be released alpha version at end of this month, It would be great that you can contribute some idea to this.

**Comment by LiZ2z** [comment]
> We are having some big progress on label position in `next` branch, which we anticipate to be released alpha version at end of this month, It would be great that you can contribute some idea to this.

很高兴被邀请！但是我刚刚使用echarts没多久，恐怕不能给出更多有效的建议。

**Comment by susiwen8** [comment]
@LiZ2z That's not a problem, many contributor started with knowing absolute nothing about ECharts, please give it a try
