### ISSUE TITLE
如果Label设置了formatter的话，bleedMargin无效

### ISSUE THREAD

**Issue by k1ngbanana** [apache/echarts#13023]
### Version
4.8.0

### Reproduction link
[https://codepen.io/k1ngbanana/pen/NWxmRey](https://codepen.io/k1ngbanana/pen/NWxmRey)

### Steps to reproduce
1、打开链接就可以

### What is expected?
1、超过bleedMargin的位置以"..."替代文字

### What is actually happening?
1、文字超出部分被切割

**Comment by Ovilia** [comment]
I believe this has been fixed in the coming version. @pissang Please have a check.

**Comment by pissang** [comment]
It will be fixed in the 5.0

**Comment by k1ngbanana** [comment]
> It will be fixed in the 5.0

thank you.
