### ISSUE TITLE
线图能否像关系图那样将线也纳入数据项,这样可以对每条线的样式做条件判断

### ISSUE THREAD

**Issue by yyz945947732** [apache/echarts#13021]
### Version
4.8.0

### Steps to reproduce
开发线图时候当遇到需求类似将某段线的颜色变为其他颜色的时候,通过现有配置无法实现,只能画两幅图拼起来

### What is expected?
在线图的配置中加入lines的配置,就像关系图一样

### What is actually happening?
没有这个配置

**Comment by Ovilia** [comment]
Please consider using [visualMap](https://echarts.apache.org/examples/zh/editor.html?c=line-aqi).

**Comment by yyz945947732** [comment]
visualMap能否让线不要有渐变的效果,我在对应的color配置中只配置了一个值,按理说比如我配置color:'#ff4400',对应的结果会是color:['#ff4400','#ff4400'],这样应该不应该会有渐变效果,但实际情况是在范围的开头或结尾处还是出现了一小段渐变的效果...

**Comment by dignfei** [comment]
> visualMap能否让线不要有渐变的效果,我在对应的color配置中只配置了一个值,按理说比如我配置color:'#ff4400',对应的结果会是color:['#ff4400','#ff4400'],这样应该不应该会有渐变效果,但实际情况是在范围的开头或结尾处还是出现了一小段渐变的效果...

你好，我也遇到这个问题，你解决了吗？？？
