### ISSUE TITLE
npm depgraph关系图

### ISSUE THREAD

**Issue by ZhenhaoGuo** [apache/echarts#13040]
### What problem does this feature solve?
根据不同关系设置 关系之间连线的粗细

### What does the proposed API look like?
在 itemStyle 里面增加 width 设置每个关系连线的粗细
（目前只是lineStyle里面统一设置连线粗细）

**Comment by wf123537200** [comment]
可以参考这个例子，[graph-simple](https://echarts.apache.org/examples/zh/editor.html?c=graph-simple)
每个links可以通过 ```links.lineStyle.width```单独设置粗细的
![image](https://user-images.githubusercontent.com/5130528/88992113-13e88180-d315-11ea-9a4b-c0d5fc6cb6de.png)
