### ISSUE TITLE
On sunburst chart hand cursor shows clickable for already drilled down item - echarts-for-react

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [apache/echarts#13049]
### Version
echarts 4.8.0
echarts-for-react 2.0.16

### Steps to reproduce
1) Open sunburst chart in example website
2) Click on any inner circle in sunburst chart - it will drill-down
3) Hover cursor over already drilled item- its showing hand cursor which indicating its still clickable.

### What is expected?
Hand cursor should be only for those items which are not drilled yet OR only to list cicle

### What is actually happening?
Hand cursor is showing to already drilled item

**Comment by Ovilia** [comment]
I don't think this is a bug. Hand cursor is used on all series items like this [bar example](https://echarts.apache.org/examples/en/editor.html?c=bar-background) which does not have drill down function.
But if you wish to make a change, you should listen to mouseover event and check if this can drill down. See [events tutorial](https://echarts.apache.org/en/tutorial.html#Events%20and%20Actions%20in%20ECharts) for more details.

**Comment by AbhaysinghBhosale** [comment]
Yes i tried the same logic but unable to find way that current hovered node is having ability to drill down.

Is there any way to check that hovered node is drill-able or not.

**Comment by Ovilia** [comment]
You can set `cursor` of each non drill down data to be other CSS values.

**Comment by Ovilia** [comment]
Maybe we can set the cursor of root element to be default in this case.
