### ISSUE TITLE
dataset模式第一项值为null时，图表无该项

### ISSUE THREAD

**Issue by mov1er** [apache/echarts#13057]
### Version
4.8.0

### Steps to reproduce
复现地址：https://gallery.echartsjs.com/editor.html?c=xxNqFMnTNL&v=1

### What is expected?
图表有第一项数据

### What is actually happening?
图表没有第一项

**Comment by plainheart** [comment]
默认情况下，二维数组形式的 `dataset. source` 的第一行代表维度信息。
如果想要第一行代表数据项，可以指定 [`dataset.sourceHeader`](https://echarts.apache.org/zh/option.html#dataset.sourceHeader`) 为 `false`
或者给 `dataset. source` 增加一行数据，代表维度名，比如
```js
source: [
    ['科目', '分数'],
    ["语文", null],
    ["数学", 17.85],
    ["英语", null],
    ["物理", null],
    ["化学", null],
    ["生物", 0],
    ["政治", null],
    ["历史", null]
]
```

参考示例：https://gallery.echartsjs.com/editor.html?c=xxNqFMnTNL&v=2
