### ISSUE TITLE
使用百度地图配置迁徙图时，清空 series 后有残影

### ISSUE THREAD

**Issue by benleilei** [apache/echarts#13064]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xX3mlykuP0&v=1](https://gallery.echartsjs.com/editor.html?c=xX3mlykuP0&v=1)

### Steps to reproduce
设置好迁徙图后（参见 https://gallery.echartsjs.com/editor.html?c=xX3mlykuP0&v=1）
```js
setTimeout(function() {
    const opts = echarts.util.clone(option)
    opts.series = []
    chart.setOption(opts);
}, 3000)
```
无法清除地图上的点
只能通过清空 data 的方式清除
```js
setTimeout(function() {
    const opts = echarts.util.clone(option)
    opts.series.forEach(s => {
        s.data = []
    })
    chart.setOption(opts);
}, 3000)
```

### What is expected?
清除迁徙图的点和线，且没有任何残影

### What is actually happening?
迁徙图的点和线有残影

**Comment by plainheart** [comment]
可以试一下 `chart.clear()`
