### ISSUE TITLE
graph模式，只有可视局域可拖拽，空白区域无法拖拽

### ISSUE THREAD

**Issue by nonepointer666** [apache/echarts#13076]
**Version**
4.7.0

**Reproduction link**
https://echarts.apache.org/examples/zh/editor.html?c=graph-force

**Steps to reproduce**
拖拽空白区域无法使内容移动

**What is expected**
建议增加拖拽空白区域也可使内容移动的功能

**What is actually happening**
目前这个交互体验较差

**Comment by Ovilia** [comment]
这个问题和 #9239 相似，都是在图形包围盒外部的鼠标操作不会触发事件处理，应该改进一下
