### ISSUE TITLE
请问柱状图有办法每根柱子宽度不一样吗

### ISSUE THREAD

**Issue by jhszy6** [apache/echarts#13074]
请问柱状图有办法每根柱子宽度不一样吗

**Comment by Ovilia** [comment]
请问是什么场景需要？自定义系列里面有个类似的 https://echarts.apache.org/examples/zh/editor.html?c=custom-profit 是不是能满足需求？

**Comment by jhszy6** [comment]
> 请问是什么场景需要？自定义系列里面有个类似的 https://echarts.apache.org/examples/zh/editor.html?c=custom-profit 是不是能满足需求？

意思是对的，普通的柱状图看看有没有什么办法
