### ISSUE TITLE
Connect Functionality is not working for toolbox Options

### ISSUE THREAD

**Issue by JinyJose** [apache/echarts#13077]
### Version
4.8.0

### Steps to reproduce
Use connect function for toolbox Options for two bar / line charts (eg: chart1 and chart2).
When the toolbox Option 'line' is clicked, the data from chart1 is displayed within chart2 as well and vice versa.
The same issue is seen when the 'bar' Option is clicked.

### What is expected?
The data in the seperate charts are not displayed in the foreign chart.

### What is actually happening?
Data from foreign charts are being displayed together when the connect functionality is used.

---
Echarts connect functionality was used mainly for dataZoom component, but the individual charts were using the toolbox option as well.

**Comment by JinyJose** [comment]
An example is created for this issue in the attached document (connect.html).
[connect.zip](https://github.com/apache/incubator-echarts/files/5021715/connect.zip)

I have taken the code-base from GitHub (https://github.com/apache/incubator-echarts/tree/fd064123626c97b36cbd6da1b5fc73385c280abd/test).

**Comment by JinyJose** [comment]
An example is created for this issue in the attached document (connect.html).
[connect.zip](https://github.com/apache/incubator-echarts/files/5021733/connect.zip)


I have taken the code-base from GitHub (https://github.com/apache/incubator-echarts/tree/fd064123626c97b36cbd6da1b5fc73385c280abd/test).

**Comment by Ovilia** [comment]
Please provide an online demo

**Comment by JinyJose** [comment]
Hello,
I have created an example in  https://codepen.io/jinyjs/pen/ZEWRRBQ 
When the toolbox Option from one chart is clicked, the data from this chart is displayed in the other chart as well.

Please advise how to resolve this issue.

Thanking you in advance.

Best regards,
Jiny

**Comment by Ovilia** [comment]
Hi, @JinyJose Can you be more specific on what's wrong here? I didn't understand what is expected.

**Comment by JinyJose** [comment]
Hi,

In the example https://codepen.io/jinyjs/pen/ZEWRRBQ , there are two charts (chart1 and chart2) which have the toolbox Options and uses the connect function.
_echarts.connect([chart1, chart2]);_

Both charts have different data as well.

![grafik](https://user-images.githubusercontent.com/69197497/94360456-9ab7a180-00ad-11eb-935e-f31ed2a1b9be.png)


But if the 'Line' Toolbox Option of the first chart is clicked, then the data from the first chart is being displayed in the second chart as well.

![grafik](https://user-images.githubusercontent.com/69197497/94360472-bd49ba80-00ad-11eb-9628-ad0a7787eca2.png)

The expected result would be that both charts display line charts with its own dataset.

I hope the issue is clear. Please let me know if I can help further.

Best regards,
Jiny

**Comment by JinyJose** [comment]
Hello, 
Please advice the status of this ticket .
Is it already fixed in the new version?

Thanking you in advance.

Best regards,
Jiny
