### ISSUE TITLE
grid.containLabel conflicts with yAxis.axisLabel.formatter

### ISSUE THREAD

**Issue by fhfuih** [apache/echarts#13097]
### Version
4.8.0

### Steps to reproduce
1. Set `grid.containLabel` to true.
2. Set a funtion to `yAxis.axisLabel.formatter`, namely `foo(value, index)`

One can utilize `https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple` for reproduction.

### What is expected?
The formatter function runs all right, with `value` the tick value and `index` the tick index.

### What is actually happening?
The formatter will run twice during the rendering of the graph. In the first run(virtual rendering and calculcating the labels' width) `index` will be undefined. If I need to do some calculation with index, errors will be thrown. In fact I also encountered the case where both `value` and `index` are undefined in the first run. But too many configs are involved and I could not found a minimal reproduction yet.

**Comment by Ovilia** [comment]
Thanks for reporting. This seems to be a bug.
