### ISSUE TITLE
如何修改 一个serie的属性呢？

### ISSUE THREAD

**Issue by pipihua666** [apache/echarts#13098]
如何修改 一个serie的属性呢
多个series那我怎么选择特定的series改他的data呢？？？

_Originally posted by @tinybright in https://github.com/apache/incubator-echarts/issues/828#issuecomment-478234056_

**Comment by plainheart** [comment]
可以为每个 series 指定 [`id`](https://echarts.apache.org/zh/option.html#series-line.id) 或者 [`name`](https://echarts.apache.org/zh/option.html#series-line.name)
