### ISSUE TITLE
力导向图，如何通过鼠标点击后从节点随鼠标移动连出一条线到另一个节点？？？

### ISSUE THREAD

**Issue by cdydayang** [apache/echarts#13093]
### What problem does this feature solve?
echarts 力导向图，如何通过鼠标点击节点后从节点随鼠标移动连出一条线到另一个节点？？？

### What does the proposed API look like?
make line,drawing line from node

**Comment by cdydayang** [comment]
有哪位遇到的呢

**Comment by wf123537200** [comment]
你是想实现：通过鼠标移动节点和另外的节点连接么？

**Comment by cdydayang** [comment]
> 你是想实现：通过鼠标移动节点和另外的节点连接么？

是的呢，你有什么好办法吗？？？

**Comment by wf123537200** [comment]
> > 你是想实现：通过鼠标移动节点和另外的节点连接么？
> 
> 是的呢，你有什么好办法吗？？？

当前通过直接配置貌似是不支持的，可以提供一个实现思路，绑定拖放事件，然后通过调整数据结构来重绘图形实现
另外，因为力导图是自动计算布局的，所以只能通过重新绘制来实现

**Comment by cdydayang** [comment]
> > > 你是想实现：通过鼠标移动节点和另外的节点连接么？
> > 
> > 
> > 是的呢，你有什么好办法吗？？？
> 
> 当前通过直接配置貌似是不支持的，可以提供一个实现思路，绑定拖放事件，然后通过调整数据结构来重绘图形实现
> 另外，因为力导图是自动计算布局的，所以只能通过重新绘制来实现

貌似我水平不行啊，我试过绑定这个拖放了，但是echarts如何绘制线条，我找不到那个的函数，还有就是实时计算鼠标当前位置 @wf123537200

**Comment by wf123537200** [comment]
绘制线条可以通过改变数据来绘制哈

**Comment by cdydayang** [comment]
> 绘制线条可以通过改变数据来绘制哈

有demo参考下吗？
