### ISSUE TITLE
No event for text label of Sankey diagram node

### ISSUE THREAD

**Issue by jinven** [apache/echarts#13105]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xoA4NXaEpO&v=2](https://gallery.echartsjs.com/editor.html?c=xoA4NXaEpO&v=2)

### Steps to reproduce
```
option = {
  series: {
    type: 'sankey',
    data: [{
      name: 'aaa'
    }, {
      name: 'bbb'
    }],
    label: {
      show: true,
      slient: false,
      triggerEvent: true,
      textStyle: {
        fontSize: 20
      }
    },
    silent: false,
    links: [{
      source: 'aaa',
      target: 'bbb',
      value: 5
    }]
  }
};
```

### What is expected?
Move the mouse to the text label to have an effect, click to trigger the event

### What is actually happening?
No effect.

**Comment by Ovilia** [comment]
In 5.x version, label will have better event handling.
