### ISSUE TITLE
I need to add a margin-bottom  symbol for markLine 

### ISSUE THREAD

**Issue by duloc2708** [apache/echarts#13108]
**Version**
4.8.0

Reproduction link
<img width="246" alt="Screen Shot 2020-08-12 at 6 34 45 AM" src="https://user-images.githubusercontent.com/27728232/89961088-ebdd1480-dc6a-11ea-984b-32480f70094e.png">

**Code here**
```  markLine: {
            silent: true,
            data: [
              {
                xAxis : dates[dates.length-3], // value dynamic horizontal
                symbolSize:30
            }```

**Comment by Ovilia** [comment]
Please provide an online demo and be more specific about your requirement.
