### ISSUE TITLE
echarts in Taro3.0 lose efficacy 

### ISSUE THREAD

**Issue by nuts-cake** [apache/echarts#13101]
### Version
4.0.0

### Steps to reproduce
in Taro2.0 there will be  echarts the living example , can init , but the Taro3.0  this.Charts is not a function. so echarts in Taro3.0 no the use... 

### What is expected?
in Taro3.0 use chart

### What is actually happening?
no use

---
undefined

**Comment by nuts-cake** [comment]
![t2](https://user-images.githubusercontent.com/57939875/89703482-c22ba100-d97d-11ea-95ff-a752fef94d41.png)
![T3](https://user-images.githubusercontent.com/57939875/89703483-c35cce00-d97d-11ea-875c-6322b80d53c4.png)

**Comment by pissang** [comment]
Perhaps Taro repo is a better place to report this issue since it's related to the upgrading of taro.
