### ISSUE TITLE
visualMap labels misaligned

### ISSUE THREAD

**Issue by jimivdw** [apache/echarts#13106]
### Version
4.8.0

### Steps to reproduce
1. Go to https://echarts.apache.org/examples/en/editor.html?c=heatmap-large-piecewise
2. Set `option.visualMap.textStyle` to `{fontWeight: "lighter"}`
3. (optional, to emphasise the issue): set `option.textGap` to `-10`

### What is expected?
Label is aligned in vertical middle of the item icon

### What is actually happening?
Label is aligned higher (at top?)

![image](https://user-images.githubusercontent.com/703419/89877776-df03e680-dbc0-11ea-924a-b15491f6a9d9.png)
vs.
![image](https://user-images.githubusercontent.com/703419/89877819-f2af4d00-dbc0-11ea-85b4-f8d8cd7cfa5c.png)

---
The actual issue I'm having is not with using a different font weight, but rather with a different font family that happens to have a different default height. I did find out however that the issue also occurs with the "lighter" font weight of the default font, which was easier to reproduce.

Setting a different value for `lineHeight` has no effect (could be that that is in fact the problem).

I'd also be fine with having an option to explicitly set the padding of the text label (in the `textStyle`), like you can already do for the `legend`.

**Comment by Ovilia** [comment]
This is probably caused by font baseline position of different font weight on different platforms. For example, I cannot reproduce it on Mac.

There's nothing really we can do about this. Perhaps you can try with another font.

**Comment by jimivdw** [comment]
Hi @Ovilia , thanks for your quick reply.

Strange that you cannot reproduce it, I'm also on Mac myself (Mojave 10.14.6).

Also, why is there nothing you can do about this? There should be some way to compensate for different baseline positions of different fonts. Maybe not automatically, but setting a different `lineHeight` or manually specifying some top padding should be able to do the trick imho.

**Comment by Ovilia** [comment]
@jimivdw Would it help if we could provide something like offsetX and offsetY to adjust text position?

**Comment by jimivdw** [comment]
Yes, that would help 😊

**Comment by Nurech** [comment]
> @jimivdw Would it help if we could provide something like offsetX and offsetY to adjust text position?

Is there any news on this? Looking over the docs I guess piece label can not be customized? https://echarts.apache.org/en/option.html#visualMap-piecewise.pieces
