### ISSUE TITLE
Valued & inversed xAxis corrupts yAxis name & axisLine positioning

### ISSUE THREAD

**Issue by fhfuih** [apache/echarts#13112]
### Version
4.8.0

### Steps to reproduce
1. Set `xAxis.type` to `value`, set `xAxis.inverse` to `true`.
2. Set `yAxis.name`. Optionally set `yAxis.nameLocation`, but default `end` is already erroneous.

One can utilize `https://echarts.apache.org/examples/zh/editor.html?c=line-simple` for reproduction.

### What is expected?
The axis name and axisLine should appear on the left side of the graph. 

### What is actually happening?
The axis name and axisLine appear on the right side of the graph, yet the axis labels appear on the left. Due to this inconsistency, I assume it's not a intended behavior (to put name & axisLine on the right) but a positioning bug. Note that the axis name is still put on the left when it's set to `center`. Only `start` and `end` trigger this bug.

Above all, I expect all stuff on the left. And optionally a configuration can be introduced to put all the stuff on the right.

**Comment by 100pah** [comment]
Try:
```js
yAxis: {
    axisLine: { onZero: false }
}
```
It will make axisLine and axis name on the left.
