### ISSUE TITLE
漏斗图funnel-customize 焦点切换问题

### ISSUE THREAD

**Issue by soarding** [apache/echarts#13115]
### Version
4.8.0

### Steps to reproduce
外层漏斗和里层漏斗有不同的hover label，
当鼠标从里层漏斗进入外层漏斗时，hover label切换成外层label (没有问题)
当鼠标从外层漏斗进入里层漏斗时，hover的label没有切换成里层label (有问题)

### What is expected?
当鼠标从外层漏斗进入里层漏斗时，hover的label切换成里层的label 

### What is actually happening?
当鼠标从外层漏斗进入里层漏斗时，hover的label没有切换成里层label

**Comment by 100pah** [comment]
可对内层 funnel series 设定更高的 z 值解决这个问题：
```
series: [{
    // 外层
    type: 'funnel',
}, {
    // 内层
    type: 'funnel',
    z: 100
}]
```

**Comment by dingdingfujian** [comment]
可以的，赞👍
