### ISSUE TITLE
one of the demo examples on https://echarts.apache.org/examples does not work

### ISSUE THREAD

**Issue by lzpons** [apache/echarts#13113]
### Version
4.8.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=calendar-charts](https://echarts.apache.org/examples/en/editor.html?c=calendar-charts)

### Steps to reproduce
within google chrome go to https://echarts.apache.org/examples/en/editor.html?c=calendar-charts

### What is expected?
to display the target charts filled in.

### What is actually happening?
This example is not functional

Error in console reads something like :

editor.js?_v_=1597075010563:1 TypeError: Cannot read property '__focusNodeAdjacency' of undefined

---
I believe this is not working since long time ago. 
Never took the time to report.

**Comment by plainheart** [comment]
Did you try to clear the cache of your browser? This example is working well for me now.

**Comment by lzpons** [comment]
I have tested with firefox, chrome, safari, and chrome with empty cache. 
All of them output the same result:

![Capture d’écran 2020-08-13 à 06 53 47](https://user-images.githubusercontent.com/41069288/90095722-c9fa9500-dd31-11ea-82ae-6c723847a905.png)

**Comment by plainheart** [comment]
All the browsers you tested have the same error in console?
```plaintext
editor.js?v=1597075010563:1 TypeError: Cannot read property '__focusNodeAdjacency' of undefined
```

Sorry that I cannot reproduce this. Please @pissang have a look.

**Comment by pissang** [comment]
Seems it's similar to the issue https://github.com/apache/incubator-echarts/issues/10736.

**Comment by lzpons** [comment]
Reading the above issue I have made a test with another time zone in chrome: 

Tokyo works fine !
![Capture d’écran 2020-08-13 à 15 50 36](https://user-images.githubusercontent.com/41069288/90142503-bc1e3180-dd7c-11ea-91dd-5ca307722e72.png)

Berlin crashes
![Capture d’écran 2020-08-13 à 15 51 01](https://user-images.githubusercontent.com/41069288/90142552-cb9d7a80-dd7c-11ea-9102-659cae4b0ef7.png)

**Comment by quillblue** [comment]
Exactly same as #10736.
The root cause is that the first data item of first graph (1485878400000, Feb 1st 0:00 on GMT+8) will be out of calendar range (Feb 2017) when the system using any timezone later than GMT+8 (that's why rendering in Tokyo GMT+9 works but failed for Berlin GMT+2).

**Comment by plainheart** [comment]
@quillblue That's right. I think it's better to use a time string like `2017-02-01` instead of the timestamp `1485878400000` for this example, ECharts will parse and convert it to the local timestamp.
