### ISSUE TITLE
矩形树图相关建议

### ISSUE THREAD

**Issue by hou18103912159** [apache/echarts#13120]
### What problem does this feature solve?
我在做矩形树图的时候发现是否可以改进一下，用一组数据来操作色块大小，一组数据显示色块的值，一组数据操作色块颜色。
因为我在做项目的时候，产品提出三组数据分别操作对应的三个色块的维度。

### What does the proposed API look like?
期望加一个字段单独控制色块大小的维度

**Comment by hou18103912159** [comment]
针对于这个问题，或者说你们这边有什么合适的解决方案吗？

**Comment by 100pah** [comment]
echarts 中的所有系列，能接受的 `data` 中，都支持 “维度” 的概念，例如：
```js
series: {
    type: 'treemap',
    data: [{
        // 可以认为是三个维度，不同维度做不同的事情
        value: [111, 223, 555]
    },
    ...
    ]
}
```

treemap 里有 `visualDimension` 属性来决定那个维度用于映射 “颜色” 或者 ”透明度“ 等。
同时 `series.label.formatter` 或者 `series.encode: { label: [2, 3] }` 这类设置能决定哪个维度用于 label 。
例如可见这个例子：
https://echarts.apache.org/examples/zh/editor.html?c=treemap-visual
