### ISSUE TITLE
Support corner radius on treemap / pie / sunburst... 

### ISSUE THREAD

**Issue by yech1990** [apache/echarts#13123]
### What problem does this feature solve?
I would like to set `border-radius` prop for the items in sankey diagram.

### What does the proposed API look like?
Add borderRadius setting for series-sankey.itemStyle

**Comment by plainheart** [comment]
We have a plan to provide the ability to draw corner radius for `pie`, `sunburst`, `treemap` etc. in the near future.
https://github.com/apache/incubator-echarts/projects/6#card-41468638

**Comment by psugandh** [comment]
can we add border radius to sankey diagram now?

**Comment by stephanoshadjipetrou** [comment]
is there a way to apply corner radius to sankey chart items?

**Comment by simonwep** [comment]
I second this, I'd be awesome to round off these edges:
<img width="34" alt="image" src="https://github.com/apache/echarts/assets/30767528/ebf0bf23-bcc7-4bc4-9bb4-e6552b65b0be">
