### ISSUE TITLE
饼图的提示性文字lable 文字显示不全

### ISSUE THREAD

**Issue by zack0603** [apache/echarts#13122]
### Version
4.8.0

### Steps to reproduce
父元素较小的情况下，关闭饼图动画，lable中的文字会呈现圆形裁切

### What is expected?
文字正常显示，文字为 一二三、一二三四、一二三四五

### What is actually happening?
文字被裁切

![image](https://user-images.githubusercontent.com/34114923/90139222-a6bffc00-ddaa-11ea-8b42-fd467509ae71.png)

**Comment by susiwen8** [comment]
5.0 fix this issue, please try it.
