### ISSUE TITLE
How to add tooltips for areaStyle and visualMap

### ISSUE THREAD

**Issue by nchikh** [apache/echarts#13134]
### What problem does this feature solve?
Hello everybody,

I have created a chart whith two lines and a clored area between them.
I use for this the areaStyme option and a visualMap visualMap.

I have added tooltips for the two lines and what I want now is to add another tooltip related to the colored area.
I want to show the tooltip anywhere when I move the mouse in the colored area. Th tooltips values change when the values of the delimited lines changes.

How to do this ?

Thank you in advance.

### What does the proposed API look like?
Is there any way to do this ?

**Comment by jsEveryDay** [comment]
I'm having the same issue, I need to display a ToolTip over visualMap just like a normal legend.

Ex. https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap

```
visualMap: {
    min: 0,
    max: 10000,
    type: 'piecewise',
    orient: 'horizontal',
    left: 'center',
    top: 65,
    
    tooltip: {
        formatter: ....
    }
  },
  ```
