### ISSUE TITLE
Allow style control for "de-emphasized" nodes (or their mask)

### ISSUE THREAD

**Issue by hoshmn** [apache/echarts#13147]
### What problem does this feature solve?
I would like to use focusNodeAdjacency, but the "non-focused" nodes are too transparent. I can currently specify itemStyles for 'emphasis' nodes; it would be great if I could also specify itemStyles for 'deemphasis' (downplay?) nodes (or the mask that goes over them).

### What does the proposed API look like?
```javascript
series: [{
  name: 's1',
  ...
  itemStyle: {
    emphasis: { ... } // exists
    downplay: { // proposed
      maskOpacity: 0.4 // could either allow specifying the opacity of the mask over the non-focused nodes
      color: 'rgba(0, 0, 0, 0.4)' // or setting the node color/styles directly (though this would be less helpful on its own, as node colors may vary across the series)
    }
  }
}]
```

**Comment by 100pah** [comment]
I think echarts 5.0 will resolve this issue. See #12911

**Comment by Azmisov** [comment]
@100pah So how would this be done in v5?
