### ISSUE TITLE
请问如何手动设置3d地球停止重新旋转, 再点击又开启旋转

### ISSUE THREAD

**Issue by z-lionel** [apache/echarts#13140]
### Version
^4.8.0

### Steps to reproduce
配置如下
   viewControl: {
          autoRotate: true, // 自动旋转关闭
          autoRotateSpeed: 1, // 旋转速度
          targetCoord: [100.46, 39.92], // 定位到中国
          zoomSensitivity: true, // 是否可缩放
        },

### What is expected?
希望能动态控制3d地球是否旋转

### What is actually happening?
文档找不到方法

**Comment by plainheart** [comment]
使用如下方式可以停止，不过会地球会重置到原来的状态，暂时没想到其他更好的方式。

```js
myChart.setOption({
  globe: {
     viewControl: {
       autoRotate: false
     }
  }
})
```

**Comment by hp100277** [comment]
使用setOption方法，修改autoRotate会导致targetCoord重置到初始位置，达不到最终的效果。😢😢😢
