### ISSUE TITLE
Customize link order of Sankey diagram

### ISSUE THREAD

**Issue by y9c** [apache/echarts#13144]
### What problem does this feature solve?
Draw the links in a customized order.

### What does the proposed API look like?

```javascript
option = {
    series: {
        type: 'sankey',
        layout: 'none',
        focusNodeAdjacency: 'allEdges',
        data: [{
            name: 'a'
        }, {
            name: 'b1'
        }, {
            name: 'b2'
        }],
        links: [{
            source: 'a',
            target: 'b2',
            value: 5
        }, {
            source: 'a',
            target: 'b1',
            value: 3
        }]
    }
};
```
Instead of readering the sankey plot automatically, I would like to customize the order of the links.
 
```
a ----- b1
a
a------ b2
```

```
a--    --b1
a    x
a--    --b2
```

**Comment by yech1990** [comment]
https://github.com/apache/incubator-echarts/issues/4880#issuecomment-675304446

**Comment by 100pah** [comment]
Set [layoutIterations](https://echarts.apache.org/zh/option.html#series-sankey.layoutIterations) as `0`.
Is it possible to meet your requirement?

**Comment by yech1990** [comment]
@100pah 
`layoutinteration = 0`  only keep the node order, but not the links.

**Comment by yech1990** [comment]
I try to modify the Sankey diagram to visualize some chromosome some rearrangement events, in which one chromosome is a directional unit. The head of chromosome A is linking with chromosome B, and the tail of chromosome A is linking with chromosome C.

For more general case, if the node blocks are directional, the order of the links would matters.

**Comment by 100pah** [comment]
> For more general case, if the node blocks are directional, the order of the links would matters.

Thanks. I think that makes sense.
