### ISSUE TITLE
Scatter chart not rendering with log axis

### ISSUE THREAD

**Issue by namannehra** [apache/echarts#13154]
### Version
5.0.0-alpha.2

### Reproduction link
[https://jsfiddle.net/uj860yxm/2/](https://jsfiddle.net/uj860yxm/2/)

### Steps to reproduce
Open the link. Look at chart.

### What is expected?
Chart is rendered properly

### What is actually happening?
Chart is not rendered properly

---
Removing `type: 'log'` fixes the issue

**Comment by 100pah** [comment]
Value that less than `1` is buggy in log axis.
