### ISSUE TITLE
bar3d的柱子是否支持圆柱？

### ISSUE THREAD

**Issue by xiaodi0003** [apache/echarts#13155]
使用bar3d时发现柱子总是方的，不能定义形状，而antv的柱子可以定义方柱或者圆柱
有支持圆柱的方式或者升级方案吗？

**Comment by plainheart** [comment]
bar3D 不支持配置 `barBorderRadius`.

**Comment by sanxin** [comment]
bevelSize属性设置为1，就可以是圆柱
