### ISSUE TITLE
barBorderRadius support custom function

### ISSUE THREAD

**Issue by kairyou** [apache/echarts#13151]
### What problem does this feature solve?
`itemStyle.barBorderRadius` support custom function like `itemStyle.color`.

### What does the proposed API look like?
```js
series: [
{
  type: 'bar',
  ...,
  itemStyle: {
    // barBorderRadius: [4, 4, 0, 0],
    barBorderRadius (data) { // current not work
      return data.value >= 0 ? [4, 4, 0, 0] : [0, 0, 4, 4]
    },
    color (data) { // for positive and negative values
      return data.value >= 0 ? '#E82724' : '#00A212'
    }
  },
},
]
```

**Comment by 100pah** [comment]
Currently this customization can only be implemented by [custom series](https://echarts.apache.org/en/option.html#series-custom).

**Comment by hhgiap241** [comment]
> Currently this customization can only be implemented by [custom series](https://echarts.apache.org/en/option.html#series-custom).

Hi @100pah, I currently have an issue like the issue mentioned above. I have try to use some custom expample in the https://echarts.apache.org/examples/en/index.html#chart-type-custom. After many try, I still can't achieve the thing that @kairyou  mentioned. Do you have any suggestions or example code that I can follow?
Here is my current code: [example](https://codesandbox.io/s/custom-bar-trend-forked-z38nwt?file=/index.js)
