### ISSUE TITLE
in gauge,value don't display 5.00

### ISSUE THREAD

**Issue by CurryChou777** [apache/echarts#13179]
### Version
4.7.0

### Steps to reproduce
1、Set a default value of 5.00 in the gauge
2、But it turns out to be 5

### What is expected?
Expect to be displayed after the decimal point

### What is actually happening?
When the actual decimal point is 0, the decimal point is ignored

**Comment by plainheart** [comment]
The type of value is `number`, for the decimal or other forms, you could try [`series-gauge.detail.formatter`](https://echarts.apache.org/en/option.html#series-gauge.detail.formatter).

**Comment by CurryChou777** [comment]
that's OK. but 5.01 is also a number, it can be displayed normally.

**Comment by plainheart** [comment]
`5.00` === `5`
If the decimal part of a number is `0`, the decimal part is ignored. `5.00` is but `5.01` is not.
If you have to make it display `5.00`, converting the number to a string is required, such as by `toFixed`.

**Comment by CurryChou777** [comment]
yes,now i do this by `value.toFxed(2)`,value is 5

**Comment by plainheart** [comment]
Oh, I meant that you need a formatter I mentioned to do this, but not need to change the data.
