### ISSUE TITLE
微信小程序tooltip.extraCssText参数无效 

### ISSUE THREAD

**Issue by GitHubWuYi** [apache/echarts#13176]
### Version
4.8.0

### Steps to reproduce
tooltip: {
            trigger: 'axis',
            renderMode: 'richText',
            extraCssText: 'transform: rotate(90deg)',
            axisPointer: {
              type: 'shadow'
            }
          }

### What is expected?
tooltip在小程序上能旋转90度

### What is actually happening?
无论怎么设置extraCssText，tooltip都是默认效果，不会有任何改变

---
微信小程序

**Comment by plainheart** [comment]
`richText` 富文本模式下不支持该属性。

**Comment by GitHubWuYi** [comment]
> `richText` 富文本模式下不支持该属性。

小程序也不支持`html`模式呀，有什么方案可以自定义tooltip的样式吗

**Comment by plainheart** [comment]
目前文档中列出的可配置的样式不足够吗？还需要自定义哪些？
