### ISSUE TITLE
series-lines - axis auto scaling

### ISSUE THREAD

**Issue by dmozzoni** [apache/echarts#13177]
### Version
4.8.0

### Reproduction link
[https://codepen.io/cyric/pen/OJNpLxJ](https://codepen.io/cyric/pen/OJNpLxJ)

### Steps to reproduce
Use series-lines with default or "dataMin"/"dataMax" values for the xAxis/yAxis "min"/"max" fields.

### What is expected?
I expected series-lines to work like series-scatter or series.line, which allows default or "dataMin"/"dataMax" values. 

### What is actually happening?
The default or dataMin/dataMax values are being ignored, must explicitly set min/max fields.

---
When using series-lines, the default/'dataMin'/'dataMax' settings for the xAxis and yAxis 'min'/'max' fields are not respected, must explicitly set both "min" and "max" fields. Since series-lines uses a different format for the data field, I'm unsure whether it is supposed to work like series-scatter and series-line or not. I couldn't find anything in the documentation to say it's not supported. I have a large variable set of data, and it's problematic not having the yAxis rescale automatically as I zoom in and out using dataZoom on the xAxis.

**Comment by Reecer9714** [comment]
Experiencing the same issue. I am needing to draw multiple dotted lines or a single line that is broken up. I switched from a scatter plot with the dots being calculated to a 'lines' series and now the zoom doesn't respect this data.
