### ISSUE TITLE
请问折线图的y轴能不能分成几段？每段可以显示自己的曲线？

### ISSUE THREAD

**Issue by yangdachu** [apache/echarts#13181]
### What problem does this feature solve?
现在的折线图对于多条曲线数据比较接近的情况下不太友好，曲线都融合在一起了，数据量如果很大的话就是一条直线了。
1、能不能有办法解决这个融合的问题？
2、能不能把y轴分成几段？比如0-1000,0-2000,0-3000...可以分成多段，然后每段显示对应自己的曲线，这样可以直观看到数据况且不会重合，还可以直接对比数据的曲线。

### What does the proposed API look like?
请问下官方的大佬有没有办法或者api解决我这个疑惑？打扰各位了，感谢你们的奉献，谢谢！

**Comment by Ovilia** [comment]
不太确定你说的分段是什么样的，这个例子是不是可以满足你的需求：https://echarts.apache.org/examples/zh/editor.html?c=line-aqi
在即将发布的 5.0 版本中，有一个（需配置后生效的）新功能是，鼠标移动到图例中的一个系列时，高亮该系列，并且将其他系列的透明度提高，这样方便观察高亮的系列。不知道是不是可以满足你的需求？

**Comment by yangdachu** [comment]
![image](https://user-images.githubusercontent.com/23580181/91515394-aa5f9100-e91b-11ea-927d-f02c21d7107d.png)

@Ovilia 画了个草图，您凑活看下，基本就是这个意思

**Comment by Ovilia** [comment]
哦哦，那你用多个 grid 就可以了，数组形式

**Comment by yangdachu** [comment]
@Ovilia 多谢🙏  https://gallery.echartsjs.com/editor.html?c=xPVmQmJcPW 是这样吧？

**Comment by yangdachu** [comment]
> @Ovilia 多谢🙏 https://gallery.echartsjs.com/editor.html?c=xPVmQmJcPW 是这样吧？

如果是这样点话，x轴能不能共用一个，现在好像是每个grid都会有一个x轴了

**Comment by wf123537200** [comment]
> > @Ovilia 多谢🙏 https://gallery.echartsjs.com/editor.html?c=xPVmQmJcPW 是这样吧？
> 
> 如果是这样点话，x轴能不能共用一个，现在好像是每个grid都会有一个x轴了

我们也有这种场景，建议调整下几个grid的间距，把几个图形拼接到一起，然后隐藏掉不要的x轴就可以了
![image](https://user-images.githubusercontent.com/5130528/92066068-98766600-edd3-11ea-9e7d-ab6094fd466a.png)
