### ISSUE TITLE
Echarts 4.8.0 series map with geo component, unable to modify mouse over label by geo.label.emphasis.formatter

### ISSUE THREAD

**Issue by jeffxu** [apache/echarts#13184]
### Version
4.8.0

### Reproduction link
[https://codepen.io/jeffxu-the-bold/pen/OJNpNqy](https://codepen.io/jeffxu-the-bold/pen/OJNpNqy)

### Steps to reproduce
Open the codepen url, when mouse over any province in the map, you will see 'text1', but what I want is to see 'text2'

### What is expected?
To modify mouseover label text by using geo.label.emphasis.formatter

### What is actually happening?
geo.label.normal.formatter is used to modify mouseover label text

**Comment by plainheart** [comment]
4.9.0 should have fixed this bug. Please have a try and feel free to give your feedback.
