### ISSUE TITLE
When downloading the SVG of the chart, there is no need to display the background color block.

### ISSUE THREAD

**Issue by Wdingding** [apache/echarts#13190]
### Version
5.0.0-alpha.2

After downloading the SVGA file, it is normal to open it on the web page. But when you open it in Sketch or Illustrator, some black background colors will appear.

The black color block will appear in the background color of the chart, the background color of the color block in the title area, the background color of the color block in the grid, and the background color of the dataZoom area. Hope you don't have these colors.

For example, the error is displayed as follows
![image](https://user-images.githubusercontent.com/26783462/91267450-f983b580-e7a5-11ea-84fc-b0617d358cbd.png)

**Comment by Ovilia** [comment]
This is a bug of SVG readers like Sketch that it doesn't understand the `"style='fill: transparent'"` style. We shall probably make a compatibility patch upon this.

**Comment by mindon** [comment]
The same under Inkscape

**Comment by Mask-MJ** [comment]
This problem reoccurs in v5.5.1, Roll back to version v5.4.3 to resolve
