### ISSUE TITLE
series-lines: Tooltip doesn't show when in "large" mode

### ISSUE THREAD

**Issue by dmozzoni** [apache/echarts#13198]
### Version
4.8.0

### Reproduction link
[https://codepen.io/cyric/pen/VwabaqV](https://codepen.io/cyric/pen/VwabaqV)

### Steps to reproduce
Create a chart using series-lines and force "large" mode to be active (via "large" and "largeThreshold" keys). Scatter charts have a similar feature, but tooltips seem to work there when in large mode  (similar issue for scatter: https://github.com/apache/incubator-echarts/issues/11241).

In the example, the top series has "large" mode off and the tooltip works, but the bottom series has "large" mode on and the tooltip no longer works.

![image](https://user-images.githubusercontent.com/23322700/91378237-f3b1c280-e7ed-11ea-95f0-4360f094677c.png)

### What is expected?
Tooltips still work when a "lines" series is in "large" mode.

### What is actually happening?
Tooltips no longer work when a "lines" series is in "large" mode.

---
Forcing "large" mode by setting { large: true } and "largeThreshold" to a value less than the number of points in the series. Setting a low threshold value for the purposes of the example, typically it would be much higher.

**Comment by susiwen8** [comment]
I have tried this case by 5.0, It seems work, please check it out.

**Comment by dmozzoni** [comment]
Yes, thank you, it does seem to work with the 5.0.0-alpha.2 version. However, the tooltips still fail to show if the data contains an "undefined" or "NaN" value anywhere. I can filter them out though.

Two other, somewhat unrelated notes, when trying to use the v5.0.0-alpha.2: 
1) I'm using the echarts-for-react package which is currently incompatible with it because v5 now exports as an e6module. A simple enough tweak to the echarts-for-react source code gets it to work though.
2) I had to stop using "lazy" updating of the chart, otherwise I get "Error: `setOption` should not be called during main process." errors, something I was not getting with v4.9
