### ISSUE TITLE
Add mark point at last item for chart type candlestick

### ISSUE THREAD

**Issue by duloc2708** [apache/echarts#13193]
### What problem does this feature solve?
Basically, then chart type candlestick will include four prices (LOW, HIGHT, LOWER, HIGHER) other on per item. I want to add mark point at the item last

### What does the proposed API look like?
And then link image refers:
<img width="576" alt="Screen Shot 2020-08-26 at 4 16 57 PM" src="https://user-images.githubusercontent.com/27728232/91290200-8a19c000-e7bd-11ea-9fb2-00ed8016c960.png">

**Comment by dbsxdbsx** [comment]
Is this issue solved, I have similar issue that I need to mark diffrent text on candlestick with speicifc condition.
