### ISSUE TITLE
Datetime plotting skew incurred by 000 microseconds (not milliseconds).

### ISSUE THREAD

**Issue by Kumfert** [apache/echarts#13195]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/n24awcmL/16/](https://jsfiddle.net/n24awcmL/16/)

### Steps to reproduce
Plot a simple line chart with the following datapoints:  [['2020-08-26T20:30:01.698Z', 0], ['2020-08-26T20:30:01.698000Z', 10]]

### What is expected?
Should see a vertical line at 1:30pm PDT. (or whatever timezone you are at).

### What is actually happening?
One of the data points is plotted at [1:41PDT, 10]. a full 11 minutes skewed forward in time!?

---
We use Django for the backend. Python's iso8601 date formatter goes to six decimal places, by default.  We are working around this issue by using a custom timedate formatter on the backend, but echarts really should not be thrown off by a bunch of zeros.  The drift is not a fixed 11 minutes in our experience. It seems to vary according to other aspects of the datetime string.

**Comment by quillblue** [comment]
Seems like a bug when converting time from string to timestamp (698000 ms is exactly about 11 minutes).
