### ISSUE TITLE
echarts折线图不显示折线

### ISSUE THREAD

**Issue by linxianseng** [apache/echarts#13208]
### Version
4.8.0

### Steps to reproduce
series里data不停地加载数据，我的div变高，echarts随着div高度重新加载，263次之后，就没有折线了

### What is expected?
能正常显示折线

### What is actually happening?
没有折线了

**Comment by pissang** [comment]
应该跟 https://github.com/apache/incubator-echarts/issues/12399 这个是同一个问题

**Comment by linxianseng** [comment]
怎么结局呢

**Comment by linxianseng** [comment]
怎么解决呢

**Comment by linxianseng** [comment]
<template>
  <div >
  <div style="overflow-y:auto;background-color:green;height:500px" id="mybox" >
    <el-row style="overflow-y:auto;background-color:yellow">
    <el-col :span="20" >
      <div id="myChart" :style="{height:aaa+'px'}"></div>
    </el-col>
    <el-col :span="4">
      <div v-for="item in arr" :key="item" ref="my">
        <div style="height:50px">{{item}}</div>
      </div>
    </el-col>
  </el-row>
  </div>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  data () {
    return {
      arr:[],
      num:0,
      mixarr:[],  
      total:0 ,
      aaa:100,
  },
  methods: {
    fix(){
      this.$nextTick(function() {
        let div = document.getElementById('mybox');
        div.scrollTop = div.scrollHeight;
      })
    },
    add(){
      setTimeout(()=>{
        this.num ++;
        this.arr.push(this.num)
      },500)
    },
    addmix(){
      for(let a=0;a<5;a++){
        this.mixarr.unshift(Math.ceil(Math.random()*10))
      }
    },
    initEcharts(){
        let myChart = this.$echarts.init(document.getElementById('myChart'))
        myChart.resize({height:this.total}); 
        let option = {
          xAxis: {
            show:false,
            type: 'value',
          },
          yAxis: {
            show:false,
            type: 'category'
          },
          series: [   
            {
              data: this.mixarr,
              type: 'line',
              smooth: true
            }
          ]
      };
      myChart.setOption(option)
    }
  },
  mounted(){
    this.$nextTick(() => {
      this.initEcharts();
    })
    this.add()
  },
  updated(){
    this.$nextTick(() => {
      this.initEcharts();
      this.fix()
    })
    this.add();
    this.addmix();
    this.total=this.$refs.my.length*50
  },
}
</script>


<style scoped>

</style>

**Comment by linxianseng** [comment]
怎么解决呢，不太会canvas拼接

**Comment by linxianseng** [comment]
代码粘上了：https://github.com/linxianseng/echarts-

**Comment by linxianseng** [comment]
https://codepen.io/linxianseng/pen/bGprNwW
