### ISSUE TITLE
Multiple independent graphs stacking on the same basis

### ISSUE THREAD

**Issue by malkrad** [apache/echarts#13218]
### What problem does this feature solve?
If a developer wants to show multiple graphs that aren't related to each other, but all of them should be stacked on one basis graph (e.g. https://jsfiddle.net/malkrad/37e2qwfj/) then the only possible way is to make a copy of the base graph and stack the different graphes on it.

To explain the example in https://jsfiddle.net/malkrad/37e2qwfj/ :

* Green and Blue graphs aren't related, however both of them should be stacked independently on Red graph.
* The way it is achieved in the example will start to be problematic upon activating the tooltip, because the Red graph would be shown in the tooltip multiple times.

### What does the proposed API look like?
Instead of the stack being a string, it could have another possibility as an array of strings (in Red graph), and each graph having a string in stack (Blue and Green graphs) that is contained in the array would be stacked on it -> Blue and Green graphs are stacked on Red but not on each other, while Red graph isn't duplicated and doesn't show up two times inside the tooltip.
e.g.:
```js
option = {
  legend: {
    data: ['red', 'blue', 'green']
  },
  ...
  series: [{
      name: 'red',
      ...
      stack: ['one', 'two']
    },
    {
      name: 'blue',
      ...
      stack: 'one'
    },
    {
      name: 'green',
      ...
      stack: 'two'
    }
  ]
};
```

**Comment by heyguojing** [comment]
read document
var chart = echarts.init(document.getElementById('main'), 'vintage');
vintage param is your theme

**Comment by malkrad** [comment]
@heyguojing Thanks for your reply, but theme has nothing to do with the issue.
