### ISSUE TITLE
黑色背景下  focusNodeAdjacency：true 时，没有关联关系节点 显示不出

### ISSUE THREAD

**Issue by webshy** [apache/echarts#13222]
### Version
4.8.0

### Steps to reproduce
echarts 设置背景黑色，type: 'graph' ， focusNodeAdjacency：true  点击有关联的节点时候，没有关系节点 显示不出

### What is expected?
点击关联节点的时候，没有关联节点的显示出来，且能操作样式，透明度，颜色等

### What is actually happening?
现在没有关联节点显示不全

**Comment by webshy** [comment]
> @webshy Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM or https://gallery.echartsjs.com/editor.html.

https://gallery.echartsjs.com/preview.html?c=xcLTp1clOB&v=1

**Comment by 23Luckstar** [comment]
Do you have solve the problem?@webshy

**Comment by webshy** [comment]
> Do you have solve the problem?@webshy
No

**Comment by webshy** [comment]
> Do you have solve the problem?@webshy

No

**Comment by webshy** [comment]
> No @23Luckstar

**Comment by pissang** [comment]
5.0 可以通过 blur 配置淡出图形的样式了

```js
blur: {
  itemStyle: { opacity: 0.5 }
}
```

**Comment by 23Luckstar** [comment]
> 5.0 可以通过 blur 配置淡出图形的样式了
> 
> ```js
> blur: {
>   itemStyle: { opacity: 0.5 }
> }
> ```

5.0才支持了吧，版本什么时候更新呢
