### ISSUE TITLE
heatMap使用dataset加载数据无效

### ISSUE THREAD

**Issue by palespring** [apache/echarts#13233]
### Version
4.8.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x8QB6rzyrV&v=1](https://gallery.echartsjs.com/editor.html?c=x8QB6rzyrV&v=1)

### Steps to reproduce
热力图

option使用dataset来加载数据

并未起任何效果

### What is expected?
希望能使用dataset将值显示在热力图上

### What is actually happening?
并没有任何内容的显示

---
我不确定我是否遗漏了什么，谢谢！

**Comment by plainheart** [comment]
参考文档 [”**使用 dataset 管理数据**“](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE
) 的 ”**其他**“ 部分所述 ：热力图暂不支持使用 dataset 数据集。

> 目前并非所有图表都支持 dataset。支持 dataset 的图表有： line、bar、pie、scatter、effectScatter、parallel、candlestick、map、funnel、custom。 后续会有更多的图表进行支持。

**Comment by palespring** [comment]
## series-heatmap. data 
[https://echarts.apache.org/zh/option.html#series-heatmap.data](url)
> 系列中的数据内容数组。数组项通常为具体的数据项。
注意，如果系列没有指定 data，并且 option 有 dataset，那么默认使用第一个 dataset。如果指定了 data，则不会再使用 dataset。
可以使用 series.datasetIndex 指定其他的  dataset。

你好，上面那段文字，在关于series.heatMap.data中，不是写了可以使用dataset么？


> 参考文档 [”**使用 dataset 管理数据**“](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE) 的 ”**其他**“ 部分所述 ：热力图暂不支持使用 dataset 数据集。
> 
> > 目前并非所有图表都支持 dataset。支持 dataset 的图表有： line、bar、pie、scatter、effectScatter、parallel、candlestick、map、funnel、custom。 后续会有更多的图表进行支持。

**Comment by plainheart** [comment]
抱歉，应该是教程里漏掉了heatmap。heatmap支持dataset。

**Comment by palespring** [comment]
那您知道，我这个为什么加载不出来嘛？或者说，我的这个问题出现在哪里？

**Comment by plainheart** [comment]
没看出来，感觉可以用纯数值的二维数组，可以参考下这个实例：https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian 将 data 改成 dataset.source 可以正常显示。

**Comment by palespring** [comment]
您好，您的邮件已收到，谢谢
