### ISSUE TITLE
跪求桑基图节点透明度配置支持下

### ISSUE THREAD

**Issue by xuanxiao2013** [apache/echarts#13248]
https://github.com/apache/incubator-echarts/blob/4.9.0/src/chart/sankey/SankeyView.js  中的392 和 395 能否配置支持，而不是写死。期望在4.x 版本支持下

fadeOutItem(node, nodeOpacityPath, 0.1);
fadeOutItem(edge, lineOpacityPath, 0.1);

**Comment by pissang** [comment]
5.0 版本会支持淡出样式的设置
