### ISSUE TITLE
svg渲染模式legend无法正常展示

### ISSUE THREAD

**Issue by tianjianwei1990** [apache/echarts#13252]
### Version
4.9.0

### Steps to reproduce
legend.type='scroll'
 

### What is expected?
show normal 

### What is actually happening?
the legend icons show normal , but the legend name doesnot show

**Comment by tianjianwei1990** [comment]
![image](https://user-images.githubusercontent.com/18712397/92592307-f0c8ce80-f2d1-11ea-83f1-faa0440ffb1f.png)

**Comment by Ovilia** [comment]
Seems to be fixed.
