### ISSUE TITLE
3D scatter plot: visualMap doesn't take colors from series:itemStyle

### ISSUE THREAD

**Issue by chudur-budur** [apache/echarts#13257]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/ramgorur/gxf6La29/](https://jsfiddle.net/ramgorur/gxf6La29/)

### Steps to reproduce
Just go to the ``JSFiddle`` and run the code. No setup necessary.

### What is expected?
Was expecting the `visualMap` to get the `color:` assigned in the `itemStyle`.

### What is actually happening?
It takes the color but the order of the points get shuffled in a strange way.

For example, without `visualMap` I have this plot:
<img src="https://i.postimg.cc/NfDBKCBw/Screen-Shot-2020-09-09-at-8-59-39-PM.png" width="400">

I want the same plot with a color-slider from the `visualMap` . So first I tried like this:
```javascript
visualMap: {
        type: "continuous",
        seriesIndex: 0,
        min: 0,
        max: 1.0,
        color: (params) => {return colors[params.dataIndex];},
        calculable: true,
      },
```
and I'm getting this plot:
<img src="https://i.postimg.cc/BbcscMFH/Screen-Shot-2020-09-09-at-9-07-58-PM.png" width="400">

In the next attempt, I tried like this:
```javascript
visualMap: {
        type: "continuous",
        seriesIndex: 0,
        min: 0,
        max: 1.0,
        color: colors,
        calculable: true,
      },
```
and I'm getting this plot:
<img src="https://i.postimg.cc/K8YFB783/Screen-Shot-2020-09-09-at-9-18-37-PM.png" width="400">

What I want is keep the same coloring and a color slider provided by the `visualMap`. 

---
Not sure if it's a bug or I'm not doing it in a correct way.

**Comment by chudur-budur** [comment]
bump?

**Comment by pjimenezmateo** [comment]
I believe this is still an issue in current versions. When trying to assign a color to each point of the 3d scatterplot the values get shuffled somehow.
