### ISSUE TITLE
echarts 支持传入  canvas 对象的 context

### ISSUE THREAD

**Issue by chuyun** [apache/echarts#13262]
### What problem does this feature solve?
对于 node 及 deno 等调用时，由于不能提供 DOM 节点，所以无法直接使用 echarts 进行图表渲染，对于很多地方提到的echarts.setCanvasCreator由于是私有方法，不支持直接调用，希望 echarts 可以支持直接传入canvas 的上下文对象, 或者提供一下直接传递context的方法，谢谢

参考 antv-F2: https://f2.antv.vision/zh/docs/tutorial/manual/node-env

### What does the proposed API look like?
echarts.setCanvasCreator(()=>ctx)

**Comment by 100pah** [comment]
<https://echarts.apache.org/zh/tutorial.html#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93>

这个文档是否有帮助
