### ISSUE TITLE
Style MarkLine label background

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13269]
### What problem does this feature solve?
Better MarkLine label presentation.

| What I want to achieve | Best I can achieve with eCharts currently |
|-|-|
| ![image](https://user-images.githubusercontent.com/470626/92966301-340c7400-f46f-11ea-9034-434f348f34d6.png) | ![image](https://user-images.githubusercontent.com/470626/92966351-48e90780-f46f-11ea-8355-2f327ee93319.png) |

### What does the proposed API look like?
```js
markLine: {
    labelStyle: {
        color: '#f00',
        background: '#0f0',
        borderRadius: 2,
        padding: 4,
    }
}
```

**Comment by narayn92** [comment]
@Bilge The above problem can be solved using the existing label properties which are not listed in the official documentation.
You can see these properties in the source code. Attached screenshot for your reference.

![image](https://user-images.githubusercontent.com/7525732/93190181-abd4ea00-f760-11ea-9d1f-db8fe20ff238.png)


**Sample chart option:**
`var option = {
    xAxis: {
        data: ['A', 'B', 'C', 'D', 'E'],
    },
    yAxis: {},
    series: [{
        name: 'line',
        type: 'line',
        data: [1, 2, 3, 4, 5],
        markLine: {
            data: [{
            name: 'My label',
                xAxis: 'D',
                label: {
                    formatter: '{b}',
                    position: 'insideMiddleTop',
                    
                    color: '#fff',
                    textBorderColor: '#000',
                    textBorderWidth: 2,
                    
                    fontStyle: 'italic',
                    fontWeight: 'bold',
                    fontSize: 50,
                    fontFamily: 'Helvetica',
                    
                    // lineHeight: 25,
                    // width: 200,
                    // height: 200,
                    // tag: 'asdasdasdasdasd',
                    
                    backgroundColor: '#ff0000',
                    padding: 25,
                    borderColor: '#000',
                    borderWidth: 2,
                    borderRadius: 5,
                    
                    shadowColor: '#333333',
                    shadowBlur: 5,
                    shadowOffsetX: 5,
                    shadowOffsetY: 5,
                    
                    textShadowColor: '#0000ff',
                    textShadowBlur: 5,
                    textShadowOffsetX: 5,
                    textShadowOffsetY: 5,
                    
                }
            }]
        }
    }]
};
`

**Comment by Bilge** [comment]
Thanks @narayn92, I was able to get results quite close to the reference image with the properties you provided. 

| What I want to achieve | Best I can achieve with eCharts now |
|-|-|
| ![image](https://user-images.githubusercontent.com/470626/92966301-340c7400-f46f-11ea-9034-434f348f34d6.png) | ![image](https://user-images.githubusercontent.com/470626/93202333-70c7bc00-f74a-11ea-803d-33356baba53a.png) |


But why aren't they documented? Probably we should keep this issue open until they are documented so other people can find them.

**Comment by mmm2006** [comment]
hello, I just want to know whether height and weight is supported in markline. In your upper setting,  I just find height and weight, But it don't work in my test. I also want to add  html tag and css attributes in my formatter: function(value),just like below,

`
     formatter: function (param) {	//自定义tooltip内容 
     	var text = '';
        text += '<div style="display:flex;flex-direction:row;">'+
        			'<div style="background-color:#03D16D;height:auto;width:10px;margin-right:5px;"></div>'+
	        		'<div style="display:flex;flex-direction:column;">'+
	        			'<span>'+ param[0].value+'</span>'+
	        			'<span>'+ param[0].axisValue+'</span>'
	                '</div>'
	            '</div>'
       return text;
    }
`
But it just show a string. Please tell me how to support html and css in markline. Thanks.

br

**Comment by narayn92** [comment]
@mmm2006  Html format is not supported for labels currently. Instead you can use rich text for label. 
Please refer the following link,
https://echarts.apache.org/en/tutorial.html#Rich%20Text

**Comment by mmm2006** [comment]
narayn92, Thank your help. I will try it.
