### ISSUE TITLE
3D scatter plot legend does not pick the right colors from the data points

### ISSUE THREAD

**Issue by chudur-budur** [apache/echarts#13268]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/ramgorur/zmdhpcwL/latest/](https://jsfiddle.net/ramgorur/zmdhpcwL/latest/)

### Steps to reproduce
Please go to the `JSFiddle` [link](https://jsfiddle.net/ramgorur/zmdhpcwL/latest/) and run the code. No setup necessary.

### What is expected?
The legend buttons should pick the correct colors from the data point.

### What is actually happening?
The legend does not pick the colors from the data and assigns arbitrary colors on its own.  

For example, in the plot below, the `sample1` legend should have a gradient of green and the `sample2` should have red. But they are not --

<img src="https://i.postimg.cc/XYJydpqv/Screen-Shot-2020-09-11-at-5-49-06-AM.png" width="400"/>

---
Not sure if it's a bug, may be I'm not doing it in a correct way.

**Comment by chudur-budur** [comment]
bump?

**Comment by pjimenezmateo** [comment]
I believe this is still an issue in current versions. When trying to assign a color to each point of the 3d scatterplot the values get shuffled somehow.

**Comment by hfp-robloh** [comment]
I'm having the same issue on a bar3d chart. The initial chart is fine, but after switching variables some bars that have similar height have totally different colors. They get the proper color after a mouse-over.

I built my visualization after this example: https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1
