### ISSUE TITLE
draw rect when xAxis.type is 'time' or 'category'

### ISSUE THREAD

**Issue by mingzhou** [apache/echarts#13264]
### What problem does this feature solve?
draw rect when xAxis.type is 'time' or 'category'

### What does the proposed API look like?
in current API, draw a rect is using shape: { x , y , width , height , r }
when xAxis.type is 'time', what dose width mean here?
shall we use left-top (x,y) and right-bottom (x, y), how about add a new API like
{x_left_top, y_left_top, x_right_bottom, y_bottom}

Thanks.

**Comment by 100pah** [comment]
Could we know the original requirement?
