### ISSUE TITLE
Pie chart

### ISSUE THREAD

**Issue by HaniGerges** [apache/echarts#13278]
![Capture](https://user-images.githubusercontent.com/42316250/93107462-ec295f00-f6b1-11ea-8b26-57178b9a6517.PNG)
### Version
4.9.0

### Steps to reproduce
Pie charts working well on PC browser but when i change to mobile it all mix up

### What is expected?
Pie chart to be responsive

### What is actually happening?
it miss up

**Comment by pissang** [comment]
Hi @HaniGerges , we've optimized the pie labels display in the coming 5.0

**Comment by 100pah** [comment]
And <https://echarts.apache.org/en/tutorial.html#Responsive%20Mobile-End> might help.
