### ISSUE TITLE
自定义图形的纹理

### ISSUE THREAD

**Issue by paradox010** [apache/echarts#13277]
### Version
4.9.0

### Steps to reproduce
代码地址：https://gallery.echartsjs.com/editor.html?c=xvLdXV8Sl-&v=1

### What is expected?
自定义图形的纹理

### What is actually happening?
纹理绘制在背景上而不是图形上

---
没找到相关的api，请问有什么方法可以绘制自定义图形的纹理吗

**Comment by 100pah** [comment]
<https://gallery.echartsjs.com/editor.html?c=xBycRXbPgx>

这个例子是否能有帮助。

**Comment by paradox010** [comment]
@100pah 抱歉不合适我的需求。我的需求是 
1.背景世界地图+全国地图在一起，（支持平移缩放）
2.全国地图可以响应选择/悬浮事件，但是背景的地图不可以。
3.背景地图和全国地图样式不一样，各自有纹理。

我现在的方案是世界和全国地图绘制在一个geo里面，通过region去维护各自的样式，但这样事件的响应就很麻烦。
所以我就想自己维护一个custom polygon作为背景地图。这才有了绘制custom里面的polygon的纹理问题。(只有纹理会有这种问题)

**Comment by paradox010** [comment]
我没把问题讲清楚，纹理是可以绘制出来的，麻烦的是移动的时候纹理也会跟着走orz。
