### ISSUE TITLE
Allow chart action controls for modifying data visualization in the rendered charts

### ISSUE THREAD

**Issue by msbasanth** [apache/echarts#13279]
### What problem does this feature solve?
When we have data visualization which shows multiple parameters in single chart we need to modify visualization or data displayed through additional controls like drop down, toggles, date pickers etc.

When I looked into ECharts I couldn't find options for adding additional controls for filtering· If we have additional controls we could allow faceted search and user-selectable data to visualize according to the user needs.

![image](https://user-images.githubusercontent.com/17777813/93106734-4b956800-f6ce-11ea-92f3-45ba29cca18e.png)

**Chart Actions**
It would be great if we get options to modify data visualizations using additional controls. Controls that allow for modification of chart data for exploration.

It would be great if we could inject HTML into Chart UI for adding chart actions. 

### What does the proposed API look like?
We should have a chart actions section which will allow users to modify the UI. It would be great if we have option to customize chart actions section by inputting the HTML because it will give option to add application styled controls.

![image](https://user-images.githubusercontent.com/17777813/93106797-62d45580-f6ce-11ea-8e3a-b148afd0001d.png)

**Comment by 100pah** [comment]
ECharts is rendered by Canvas or SVG, not HTML.

A good pattern of this job I think it probably be: 
Get user parameters (like data select, bar click, ...) and assemble a new `echarts option` and call `chart.setOption(newOption)` to make the change work on the chart.

**Comment by msbasanth** [comment]
@100pah 

Agree that ECharts is rendered using Canvas or SVG. 
As you said we could move this data filtering controls outside chart rendering area and and modify the chart by responding to the events. But it clearly gives better usability when we have controls inside the chart.

The options available:
1. Using SVG itself for creating controls for modifying data.
![image](https://user-images.githubusercontent.com/17777813/93728762-fc27ce00-fbde-11ea-8299-d6c3c0c8b411.png)
http://jsfiddle.net/qd9js9oj/
Here they used SVG rect for creating a button.

1. Using HTML Elements as overlay when need to take input from user.
![image](https://user-images.githubusercontent.com/17777813/93728965-01394d00-fbe0-11ea-8494-79532b846b9d.png)
https://jsfiddle.net/BlackLabel/cf0h8tp5/
Here used HTML Input on double click and allow user input through that. 
With this user don't have to go out of chart for doing a filtering logic.

It would be great if echarts allow data modifications controls similar way.

**Comment by Alynva** [comment]
> ECharts is rendered by Canvas or SVG, not HTML.
> 
> A good pattern of this job I think it probably be: Get user parameters (like data select, bar click, ...) and assemble a new `echarts option` and call `chart.setOption(newOption)` to make the change work on the chart.

I fell like this isn't quite fair, since surely there are interactive elements built in the library, eg the legend.
