### ISSUE TITLE
MarkLine tied to axis instead of series

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13291]
### What problem does this feature solve?
MarkLines are currently tied to a series, so if the series is toggled off, the markLine disappears. We want to be able to mark an axis, so the markLine is always visible regardless of which series are displayed.

### What does the proposed API look like?
Same as markLine API for series, but available on axis.

**Comment by 100pah** [comment]
At present there are probably these solutions:
+ Make an extra series that dedicates to render to markLine.
+ Use a `custom series` to render the line instead of the markLine.

**Comment by Bilge** [comment]
An interesting workaround but not a solution.

**Comment by 100pah** [comment]
> An extra series can still be toggled on or off, but the markLine should be always visible.

If the extra series is toggled by `legend`, we can make the legend do not control the series by do not specify 'serise.name'.

**Comment by Bilge** [comment]
Setting up a fake series isn't really practical, because even though the legend won't see it without a name, other components such as the tooltip will (with a custom formatter, at least). Moreover, the series needs to encode an existing data set so it know where to draw the mark line, which means it will draw over the top of one of the existing series. 

Overall, trying to fake a phantom series just to place mark lines is fraught with perils and not really practical. We really need facility to place markLines on axis instead of series.

**Comment by carmolim** [comment]
Did you found a workaround?

**Comment by annlumia** [comment]
is this still not available?
