### ISSUE TITLE
SVG legend scroll

### ISSUE THREAD

**Issue by zk274730694** [apache/echarts#13305]
### Version
4.8.0

### Steps to reproduce
init，第三参数设置render的绘制方式为svg，并且设置显示图例，legend的type为scroll,并且图例个数足够多到能实现翻页

### What is expected?
即便是svg绘制方式，图例存在滚动，图例的文字也能正常显示

### What is actually happening?
实际的结果为图例文字不能显示，就算设置了legend的z属性也无效

---
grid的参数为top: 30, bottom: 30,containLabel: true
legend的配置参数bottom:5, textStyle: {color: "#333"}

**Comment by MoMoOwO** [comment]
我也遇到了这个问题，canvas 渲染的情况下滚动 legend 可以正常显示图例图标和文本并正常滚动；svg 渲染的情况下则不正常，图例文本不显示，而且滚动会出现错位。

**Comment by Ovilia** [comment]
Fixed
