### ISSUE TITLE
背景画出一个圆形，点在圆形范围之内活动

### ISSUE THREAD

**Issue by wangdi244** [apache/echarts#13300]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=custom-profile](https://echarts.apache.org/examples/zh/editor.html?c=custom-profile)

### Steps to reproduce
背景画出一个圆形，点在圆形范围之内活动，通过force算法实现

### What is expected?
背景画出一个圆形，点在圆形范围之内活动，通过force算法实现

### What is actually happening?
背景画出一个圆形，点在圆形范围之内活动，通过force算法实现

**Comment by wangdi244** [comment]
请问echarts能在一个图内划分多个区域，每个区域定义一些点。区域与区域之间有关联关系，可以做这样的配置吗？

**Comment by wangdi244** [comment]
是否支持复合节点的方式实现？

**Comment by 100pah** [comment]
需求描述的比较简略，不太能理解。

**Comment by wangdi244** [comment]
![图](https://user-images.githubusercontent.com/13075509/93729665-0d310900-fbf8-11ea-9459-a0aaa2991d06.png)
如图分成红黄蓝三个部分，如果使用graph关系图功能，能够将点控制在红色，黄色，蓝色的范围内，并且连线不受干扰。类似于cytoscape.js的功能，如图
![图1](https://user-images.githubusercontent.com/13075509/93729860-ca236580-fbf8-11ea-9f4e-3b3fdc1afb53.PNG)

**Comment by Ovilia** [comment]
ECharts 应该在这个 case 里只是用来画圆和线，至于位置的计算，是你自己计算并给出的，所以这可能不是一个 ECharts 的问题。
