### ISSUE TITLE
在3d地球组件结合世界地图组件，在电脑上可以响应点击事件，但是在大屏上无法响应

### ISSUE THREAD

**Issue by z-lionel** [apache/echarts#13301]
### Version
 "echarts": "^4.8.0",     "echarts-gl": "^1.1.1",

### Steps to reproduce
正常引入使用
import echarts from "echarts";
import "echarts-gl";
import "echarts/map/js/world.js";

### What is expected?
在大屏上，可以3d地图组件，可以响应世界地图组件canvas上的事件
this.mapChart.getZr().on("click", (params) => {}）

### What is actually happening?
1.在3d地球组件结合世界地图组件，在电脑上可以响应点击事件，但是在大屏上无法响应。
2.在大屏上单独加载世界地图组件，可以正常响应地图组件上的点击事。
this.mapChart.getZr().on("click", (params) => {}）

**Comment by z-lionel** [comment]
在移动端上也无法响应3d地球组件，也无法响应加载的canvas的世界地图上组件上的而点击事件
this.mapChart.getZr().on("click", (params) => {}）
请问该如何处理？

**Comment by Gsalpha** [comment]
请问现在可以了么 5.0.0版本似乎还无法使用
