### ISSUE TITLE
Line is disconnected from points outside zoomed-in region in Line Chart with value type xaxis

### ISSUE THREAD

**Issue by ys4503** [apache/echarts#13316]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/zg7mw5nf/](https://jsfiddle.net/zg7mw5nf/)

### Steps to reproduce
The line is not connected to points outside the zoom-in region when using dataZoom in a Line chart with xaxis type value. Try zooming between 6 and 9 in above JSFiddle Link

### What is expected?
The line should be connected to points outside the zoom-in region. 

### What is actually happening?
The line is only connected to points inside the zoom-in region.

---
There should be scatterline type chart.

**Comment by worldforce1** [comment]
I found a solution around this bug.

**Comment by ys4503** [comment]
Thanks for sharing your solution. This is a very nice way around and it should be implemented in 'weakFilter' or its own filterMode.

It seems the default mode is intended for performance reasons. However, it should default to your solution in this particular chart type. Using 'none' filterMode also fixes this issue but it doesn't filter any data and it may not be optimum for huge data.

**Comment by zorac** [comment]
I've prototyped a 'filterPlusOne' filterMode which solves this issue in ECharts 5 for the simple use case where only one dimension is being filtered (e.g. a line chart with horizontal zoom) in a performant way. Not sure whether this is the correct approach, though, and there may be a cleaner way to implement it.

Changes here: https://github.com/zorac/echarts/compare/master...zorac:fix-13316

**Comment by NichitaD** [comment]
Any news on this topic? The [solution proposed by zorac ](https://github.com/apache/echarts/issues/13316#issuecomment-1130046787) looks like a quick fix. 

This change would allow use to use the axis `scale` functionality, while still maintaining the line/area continuity.
