### ISSUE TITLE
Series (bar) - type: 'time' - entry width doesnt follow the maxInterval and gets corrected if there is any adjacent value.

### ISSUE THREAD

**Issue by ngmgit** [apache/echarts#13322]
### Version
4.9.0

### Reproduction link
[https://codesandbox.io/s/dry-wildflower-79suq?file=/src/App.js](https://codesandbox.io/s/dry-wildflower-79suq?file=/src/App.js)

### Steps to reproduce
* setup a time series bar chart
* Set maxInterval to 1 hr bucket i.e 60 * 60 * 1000
* Set min and max values to the end and start of the day for the given bucket.

Even though this looks like what should be done to get a graph for a day divided into hour buckets and set the values to fill up the graph. Note that its not necessary that all the values for the series are set.

### What is expected?
To show the bar with width taking up only the maxInterval and the graph x-axis should start with 00 value and end with 00 values with 1 hr buckets. 

This should also work even when the entries are not adjacent.

![actual-bar-series](https://user-images.githubusercontent.com/10939602/94673205-0743d200-0334-11eb-8276-7a136817ba8f.png)

### What is actually happening?
Shows the buckets starting and ending wrong and the zoom in always becomes glitchy. The entries are taking up 2 hr interval width. This happens when the values are not adjacent.

![bar-series- bug](https://user-images.githubusercontent.com/10939602/94673081-d19ee900-0333-11eb-8573-1f2930143756.png)

---
As per the attached minimal reproduction link. The values in the MOCK_DATA has value which doenst have any adjacent value while the one in ADJANCE_BUCKET_MOCK_DATA has entries for 15:00 and 16:00 which are adjacent.

**Comment by ngmgit** [comment]
UPDATE: updated the config to fix inconsistency in time. This codebsanbox link has the changes, https://codesandbox.io/s/dry-wildflower-79suq?file=/src/App.js

**Comment by Ovilia** [comment]
@ngmgit Can you provide a simpler demo containing only a simple option for us to reproduce?

**Comment by ngmgit** [comment]
@Ovilia Here is a simple working code https://jsfiddle.net/yj05rt9f/
