### ISSUE TITLE
Scrollbar for every axis if the data is large

### ISSUE THREAD

**Issue by pratikbokey007** [apache/echarts#13329]
### What problem does this feature solve?
User can view all the bars in fixed proper size if there are numbers of bars are more than 20-30 & user can scroll X-Axis either Y-Asix

### What does the proposed API look like?
options:{
  xAxis:{
    scrollBar: true
  }
}

**Comment by Ovilia** [comment]
Hi, scroll bar can be made using https://echarts.apache.org/en/option.html#dataZoom .
If you wish to use it only for series with more than 20 data, you may implement by checking the data amount by your logic and change the dataZoom in the option when `setOption`.
