### ISSUE TITLE
Color fatal error:set '#000' but got '#484848' or some other color?Who change my color?||颜色渲染错误，黑色变灰色

### ISSUE THREAD

**Issue by czzonet** [apache/echarts#13325]
### Version
4.9.0

### Steps to reproduce
[Examples - Apache ECharts (incubating)](https://echarts.apache.org/examples/zh/editor.html?c=area-basic)

set :  areaStyle: {   color:'#000'}

```js
option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        areaStyle: {   color:'#000'}
    }]
};

```

### What is expected?
  color:'#000'

### What is actually happening?
  color:'#484848'

---
What am I missing?

**Comment by pissang** [comment]
It's because it's semi-transparent.

Set `areaStyle.opacity` to 1

**Comment by czzonet** [comment]
Cool. It works. Is it mentioned anywhere in the document?
