### ISSUE TITLE
Allow map series to use defined geo component

### ISSUE THREAD

**Issue by CodingHorror3** [apache/echarts#13332]
### What problem does this feature solve?
Currently there is no way to render a map series and another series with coordinateSystem = 'geo'  on the same map. Because of this, it is impossible to create for example a scatter series on the map and at the same time have a visual mapping of the map region's colors, which can be panned and zoomed and zooms both the map and scatter series together as one.

### What does the proposed API look like?
Simply allow series of type map to reference a map defined in a geo component.

**Comment by pissang** [comment]
@CodingHorror3 Yeah it's possible. What version of ECharts are you using?
