### ISSUE TITLE
When the bar has two duplicate data, modifying one will refresh the other at the same time.(CH:当柱状图有两个重复数据时，修改其中一个会同时刷新另外一个))

### ISSUE THREAD

**Issue by BiptJXu** [apache/echarts#13348]
### Version
latest

### Steps to reproduce
First, you need to define an array with repeated data, which is correct when drawn. However, if you modify the data "my_data[0]=140", you will find that the last data is also refreshed once.(CH:首先，你需要定义含有重复数据的数组，这时画出来时正确的。但是，如果你修改其中的数据“my_data[0]=140”,你会发现最后一个数据也刷新了一次)
```javascript
var my_data=[130, 200, 150, 80, 70, 110, 130];
my_data[0]=135;    //test code（is a example）
option = {
    xAxis: {
        type: 'category',
        data: my_data
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: my_data,
        type: 'bar'
    }]
};
```
This problem seems to have nothing to do with the version. Today, I also encountered this problem in the Example on the official website.(https://echarts.apache.org/examples/en/editor.html?c=bar-simple)

### What is expected?
When the histogram(bar) has two duplicate data, modifying one will refresh the other at the same time, although I only want to show the change of one data.(CH:当柱状图有两个重复数据时，修改其中一个会同时刷新另外一个，虽然我只想展示一个数据的变化)

### What is actually happening?
When modifying the first data, I found that the last data will also change, even though I only modified the first one in the array (when the first element is the same as the last one).
CH:修改第一个数据时，发现最后一个数据也会变化，尽管我在数组中只修改了第一个（当第一个元素和最后一个相同时）。

**Comment by Ovilia** [comment]
Hi @BiptJXu ,

I cannot reproduce your problem with
```js
var my_data=[130, 200, 150, 80, 70, 110, 130];
option = {
    xAxis: {
        type: 'category',
        data: my_data
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: my_data,
        type: 'bar'
    }]
};

setTimeout(function() {
    my_data[0] = 1000;
    myChart.setOption(option);
}, 1000);
```

Could you make an online demo?

**Comment by BiptJXu** [comment]
Your code has the same meaning as I mean, which is great.

When I run this code on the official website example (https://echarts.apache.org/examples/en/editor.html?c=bar-simple)，

The first step is correct.
![image](https://user-images.githubusercontent.com/45067585/94354878-013ebe80-00b2-11eb-9e1f-0c66f1477793.png)

Second, when the function "SetTimeout" is executed, the data is changed. When rendering the chart, the last column of data was also refreshed, although I did not change it.
This is only in the rendering process, it is a very short process, you must observe carefully, as I described in the screenshot.
![image](https://user-images.githubusercontent.com/45067585/94354823-bae95f80-00b1-11eb-8410-04b3695cb84a.png)

Finally, I got the correct display. There is no problem in the last step, the problem appears in the second part.

**Comment by BiptJXu** [comment]
1000 is a big data, which will change the scale of the entire graph，140 is a suitable data.
```
var my_data=[130, 200, 150, 80, 70, 110, 130];
option = {
    xAxis: {
        type: 'category',
        data: my_data
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: my_data,
        type: 'bar'
    }]
};

setTimeout(function() {
    my_data[0] = 140;
    myChart.setOption(option);
}, 1000);
```
If an array without repeated elements is used, only the changed data elements will be refreshed during the refresh process.
```
var my_data=[130, 200, 150, 80, 70, 110, 131];
option = {
    xAxis: {
        type: 'category',
        data: my_data
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: my_data,
        type: 'bar'
    }]
};

setTimeout(function() {
    my_data[0] = 140;
    myChart.setOption(option);
}, 1000);
```

**Comment by Ovilia** [comment]
The animation does seem strange to me. Marked as a bug and hope someone can dive into the code and see why this is happening.
