### ISSUE TITLE
echarts-gl当中坐标轴inverse问题

### ISSUE THREAD

**Issue by CodeFly16** [apache/echarts#13344]
### Version
5.0.0-alpha.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line3d-orthographic&gl=1](https://echarts.apache.org/examples/zh/editor.html?c=line3d-orthographic&gl=1)

### Steps to reproduce
直接以官方demo为例，无法使用inverse使得坐标轴转置

### What is expected?
希望z轴方向指向下

### What is actually happening?
无变化

**Comment by Ovilia** [comment]
文档里并没有看到 `inverse`，不知道是不是不支持 @pissang

**Comment by pissang** [comment]
应该是支持的，可能是 bug

**Comment by boxbox-0427** [comment]
请问有解决这个问题了嘛？
