### ISSUE TITLE
close

### ISSUE THREAD

**Issue by yuanpan365** [apache/echarts#13346]

**Comment by Ovilia** [comment]
有几种方式你可以尝试：
前端处理优化数据量，每秒传 5 次数据是不是必要的，25000 条数据是一定要变为 25000 个柱子吗？对用户来说，这样的大数据是不是一种好的表现形式，用户是不是关心具体的 25000 条数据，还是说一些处理后的维度更有意义（平均值、最大最小值等）。

**Comment by yuanpan365** [comment]
这个已经是处理过的数据，必须要这种

**Comment by yuanpan365** [comment]
> 有几种方式你可以尝试：
> 前端处理优化数据量，每秒传 5 次数据是不是必要的，25000 条数据是一定要变为 25000 个柱子吗？对用户来说，这样的大数据是不是一种好的表现形式，用户是不是关心具体的 25000 条数据，还是说一些处理后的维度更有意义（平均值、最大最小值等）。

这个实时数据实时监测柱子的高度变化，5000个数据是固定的，如果能变成类似于 line表的往左移动的效果，就不需要刷新5次，每秒25000个数据了。
