### ISSUE TITLE
can tooltip scroll bottom to show more data?

### ISSUE THREAD

**Issue by lshnltt** [apache/echarts#13356]
### What problem does this feature solve?
my chart has too many series ， so the tooltip show many data one time , i hope scroll the tooltip to show more data,  for example show more 30 records  one time when tooltip scroll to bottom,I tried a lot of things , but it seem fail to update the tooltip dom when scroll to bottom even the data has changed.

### What does the proposed API look like?
it need't add API for this, but i really want to know is there a way to update tooltip dom when tooltip scroll

**Comment by plainheart** [comment]
We have added a new option `className` for tooltip HTML renderer in 5.0.0(the stable version is not released yet).
I suppose you could specify a class name to enable you could get the DOM element easily. Then we can add event listeners to the DOM and update its content manually.
Moreover, I'm thinking to allow users to provide directly a DOM element as tooltip's container, that may be more flexible. See #13250

**Comment by lshnltt** [comment]
ok,thanks
