### ISSUE TITLE
mapbox  结合时 label 不能使用

### ISSUE THREAD

**Issue by succulen-plants** [apache/echarts#13354]
### Version
4.9.0

### Steps to reproduce

**VM8041** echarts-gl.min.js:1 Uncaught TypeError: Cannot read property '0' of undefined 

```
   series: [{
           type: 'map3D',
           coordinateSystem: 'mapbox3D',
           map: 'china',
           regionHeight: 0.5,
           shading: 'lambert',
           label:{show: true}
       }]
```

### What is expected?
加载的3D建筑上面有标签显示

### What is actually happening?
报错

**Comment by succulen-plants** [comment]
而且， click 事件也获取不到， 
  chart.on('click', function (params) {
            });
只是使用mapbox 提供了地图， 不理解为什么点击页面没有echarts 的点击事件

**Comment by plainheart** [comment]
是否用了第三方扩展插件？

**Comment by succulen-plants** [comment]
没有使用， 您可以使用官网提供的例子试一下 比如： https://gallery.echartsjs.com/editor.html?c=xrJygEHHYb
还有问题是，  下面这种写法完全监听不到鼠标和键盘事件， 之前旧版本 mapbox可以， 换成mapbox3D的版本就监听不到 
```
const map = chart.getModel().getComponent('mapbox3D').getMapbox();
map.on('load',()=>{
  map.getCanvas().addEnventListener('click', e=>{
})
})

**Comment by succulen-plants** [comment]
并且 和mapbox 结合后， 获取不到echarts 的 click事件 
```
myChart.on('click', ()=>{
        alert('124')
    })
```

**Comment by blairbandit** [comment]
same question about the click event.
