### ISSUE TITLE
Apply Min Max Avg on filtered data along with the current feature: Border points connected to points outside graph (connected graph)

### ISSUE THREAD

**Issue by akashsonune** [apache/echarts#13360]
### What problem does this feature solve?
Currently  we have `filterMode` property of `datazoom.slider`.
With this we are using a nice existing feature:
1. Connect the border points to outside points (points outside visible range) so that graph appears to be connected
    This feature is very well working by setting dataZoom-slider. filterMode = 'none'

2. Now we use another nice feature: Show Min Max Avg for the visible range (It shall also update when we zoom/pan as the data/range is updated)
   -  To enable this we need to set dataZoom-slider. filterMode = 'filter' so that it considers only visible range

But now the problem is we lose feature 1 in this case..but we want both the features in

So Our questions are:
1. Is there any facility/ way available right now that can enable both the features?
2. If  not is there any workaround/tweak available?
3. If not , it will be nice to provide a way to enable both features somehow

### What does the proposed API look like?
I think there can be additional option for 
dataZoom-slider. filterMode property which will allow both features to work simultaneously

**Comment by pissang** [comment]
I'm afraid it's hard to have them both in design. These two conflict in some way underlying.

It's easier to workaround on the avg/min/max line. So I will suggest you still keep `filterMode: 'none'` and calculating avg/min/max of filtered data outside by listening to `dataZoom` event
