### ISSUE TITLE
Support for self linking node in graphs

### ISSUE THREAD

**Issue by pkovanen** [apache/echarts#13367]
### What problem does this feature solve?
At the moment ECharts does not seem to support links to self in graphs. In other words, if source and target nodes are identical in links of the series, self link arrow is not drawn at all.

In our application we need to draw a force layout chart which can also contain links to self. We would love to do this using ECharts which is used for other charts.

### What does the proposed API look like?
This does not affect the API.

**Comment by sayjeyhi** [comment]
@pissang Any updates on this?
