### ISSUE TITLE
关系图 graph, 节点重复的情况下，鼠标悬浮效果失效

### ISSUE THREAD

**Issue by xijinhua** [apache/echarts#13361]
### Version
4.9.0

### Reproduction link
[https://codepen.io/xijinhua/pen/poyBROO](https://codepen.io/xijinhua/pen/poyBROO)

### Steps to reproduce
  label: {
                    normal: {
                        show: true,
                        color: '#000',
                        // position: 'bottom',
                        formatter: function(params) {
                            return params.data.showNum
                        }
                    }

                },

### What is expected?
node 的节点重复，重新定义node 的name 名称，鼠标悬浮在节点上，更准确的说，悬浮在节点的文字上时，悬浮效果失效，只保持了2s内

### What is actually happening?
期待鼠标悬浮效果正常

**Comment by xijinhua** [comment]
svg的bug

**Comment by Lanchouchou** [comment]
维度名称重复时 如何都显示出来。比如统计学生成绩 有学生重名
