### ISSUE TITLE
Bmap is not documented

### ISSUE THREAD

**Issue by KrzysztofMadejski** [apache/echarts#13370]
### Version
I don't know, documentation at https://echarts.apache.org/en/option.html does not identify version

### Steps to reproduce
1. Go to https://echarts.apache.org/examples/en/editor.html?c=map-polygon, bmap option is used
2. Go to https://echarts.apache.org/en/option.html 
3. Search for "bmap" 
4. No Results

### What is expected?
Documentation is provided.

### What is actually happening?
I can't find any documentaion for bmap

---
Are other map backgrounds (google maps, osm, mapnik) also available?

**Comment by plainheart** [comment]
Hi, the documentation of BMap extension is not listed on echarts' website, but you could refer to its [README file](https://github.com/apache/incubator-echarts/tree/master/extension/bmap)(Writing in Chinese).

For Google Map extension, you could refer to this plugin [echarts-extension-gmap](https://github.com/plainheart/echarts-extension-gmap).

Hope that helps.
