### ISSUE TITLE
 areaStyle fill to yAxis  when yAxis is value  type

### ISSUE THREAD

**Issue by sumile-ting** [apache/echarts#13373]
### What problem does this feature solve?
In my chart,  xAxis and yAxis are consecutive data sets, so I can't set yAxis category type. However I still expect areaStyle fill to yAxis but not xAxis. What I expect likes below.
![image](https://user-images.githubusercontent.com/29885006/94634485-bc5d9680-0302-11eb-84ff-ed728c58259b.png)

Same issus [#9025 ](url) had set to stale.

### What does the proposed API look like?
I haved tried that when xAxis is value type , areaStyle can still fill to xAxis. So could echarts provide a gobal parameter in grid to invert xAxis and yAxis.

**Comment by hpirela** [comment]
somebody know when this option will be available ?

**Comment by SerhiiZamoshnikov** [comment]
Managed to solve this fill problem with a small plugin that just sets

```
import Cartesian2D from 'echarts/lib/coord/cartesian/Cartesian2D';

export const BaseYAxisPlugin = {
  install() {
    const original = Cartesian2D.prototype.getBaseAxis;
    Cartesian2D.prototype.getBaseAxis = function () {
      return this.getAxis('y');
    };
  },
};
```

and then 
echarts.use([BaseYAxisPlugin]);

here is the piece of original code:

```
  /**
   * Base axis will be used on stacking.
   */
  Cartesian2D.prototype.getBaseAxis = function () {
    return this.getAxesByScale('ordinal')[0] || this.getAxesByScale('time')[0] || this.getAxis('x');
  };
```
