### ISSUE TITLE
echarts 5.0 not working with react

### ISSUE THREAD

**Issue by zevero** [apache/echarts#13380]
### Version
5.0.0-alpha.2

### Reproduction link
[https://codesandbox.io/s/react-hooks-echarts-forked-ib070?file=/src/useECharts.js](https://codesandbox.io/s/react-hooks-echarts-forked-ib070?file=/src/useECharts.js)

### Steps to reproduce
Click on Link
Choose Version echart 5.0.0-alpha.2 or echart 5.0.0-alpha.1

### What is expected?
It should work as with
echart 4.9.0

### What is actually happening?
Error echarts.getInstanceByDom undefined in file useEcharts.js

---
I could not find any documentation on Version 5.0? Did the api change?

I also tried echarts-for-react 2.0.16. It works with 3.x and 4.x but not with 5.x

How can Version 5.0 be run within react?

**Comment by plainheart** [comment]
Hi, @zevero 
For the version of 5.0, you need to use `import * as echarts from "charts"`.

The related documentation will be put online after release in early October.
