### ISSUE TITLE
Improve colour interpolation for gradients

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13399]
### What problem does this feature solve?
RGB interpolation suffers from colour desaturation when interpolating between two colours with disparate hues. There are [some articles](https://web.archive.org/web/20150215132805/https://www.stuartdenman.com/improved-color-blending/) about this issue and also some proposed solutions, such as [HSB and Lch blending algorithms](https://www.shadertoy.com/view/lsdGzN), which produce [better results](https://davidjohnstone.net/pages/lch-lab-colour-gradient-picker) that **maintain saturation and brightness** during interpolation.

#### Example of problem
![image](https://user-images.githubusercontent.com/470626/95504467-ad32b480-09a4-11eb-86f1-0100eaddf811.png)

In this example, eCharts interpolates between `#70b53c` and `#7c45a5`, but we see the mid point is actually almost entirely grey `#77717c`!

**Comment by pissang** [comment]
Hi @Bilge  It's a nice feature. But HTML Canvas doesn't support HSB gradient currently. Perhaps the only way to do this is to calculate the interpolation outside and use more colors in the gradient.
