### ISSUE TITLE
Visual Map not rendering line color (but it IS rendering correct color in label)

### ISSUE THREAD

**Issue by Daemach** [apache/echarts#13393]
### Version
4.9.0

### Reproduction link
[https://codepen.io/daemach/pen/MWegRvO](https://codepen.io/daemach/pen/MWegRvO)

### Steps to reproduce
See code pen.

### What is expected?
I expect the line color to change based on values in dimension 2 of series 0

### What is actually happening?
Line color does not change, although the LABEL color is being mapped correctly according to visual map rules

---
It doesn't work in the 5.0.0 alpha 2 release either.

**Comment by quillblue** [comment]
Took a look as requested in mail list. Seems that line will only accept visual map on value dimension.
But I feel a bit weird on why color on line need to be mapped to fields not related to value it self. Most cases of line color visual map is configured on simple and continous value range (just as [https://echarts.apache.org/examples/en/editor.html?c=line-aqi](https://echarts.apache.org/examples/en/editor.html?c=line-aqi)) and I feel sorry to say that I can't be aware of bothering of current limitation.

**Comment by Daemach** [comment]
That is unfortunate.  And it doesn't explain why the label color is correct
although the line color isn't.  Why can't you allow mapping the visual map
on a different dimension just like the label?

My situation is this:  I am using this to map values for growing plants
indoors.  During the times when the lights are on, certain values are
acceptable.  When the lights are off, those same values are unacceptable.
Range 1 is 6AM=>6PM  Range 2 is 6PM=>6AM.  At 9AM, when the lights are on,
a value of 1200ppm for CO2 level is acceptable and the line should be
green.  At 9PM, when the lights are off, 1200ppm is not acceptable  and the
line should be red.  I understand that the visual map can only map within 1
range, not 2, so I calculated separate values and put them in a separate
dimension.  The label colors are working.  The line color is not.

**Comment by quillblue** [comment]
@Daemach that situation seems make sense. Will try to look at the different rendering between label and line.

**Comment by Daemach** [comment]
Thank you, Quill.  I really appreciate it.

**Comment by Daemach** [comment]
Were you able to make any progress with this issue?

**Comment by craigchandler** [comment]
Was there ever a solution to this? facing this issue now when looking to adopt echarts
