### ISSUE TITLE
What causes this disorder in the line chart

### ISSUE THREAD

**Issue by tigerHeeJS** [apache/echarts#13401]
### Version
4.9.0

### Steps to reproduce
I want to know what caused the red line chart to be messy. 
I update a lot of data in real time to render the line chart，like：
![data](https://user-images.githubusercontent.com/62994244/95560632-20433600-0a4c-11eb-8309-4b08dbb4fa68.png)

### What is expected?
<img width="1119" alt="line2" src="https://user-images.githubusercontent.com/62994244/95560416-d8241380-0a4b-11eb-9e8e-3ae7e792584a.png">

### What is actually happening?
<img width="1117" alt="line" src="https://user-images.githubusercontent.com/62994244/95560164-76fc4000-0a4b-11eb-8691-c537e1403fb7.png">

**Comment by plainheart** [comment]
Could you please try to set [`smoothMonotone`](https://echarts.apache.org/en/option.html#series-line.smoothMonotone) to `x` to keep the monotonicity in xAxis and then check whether the behavior is normal?

**Comment by tigerHeeJS** [comment]
I did not set smooth to true，Can smoothMonotone take effect？

**Comment by tigerHeeJS** [comment]
> Could you please try to set [`smoothMonotone`](https://echarts.apache.org/en/option.html#series-line.smoothMonotone) to `x` to keep the monotonicity in xAxis and then check whether the behavior is normal?

I did not set smooth to true，Can smoothMonotone take effect？

**Comment by tigerHeeJS** [comment]
Set smoothMonotone to x，There is still a problem with the red line disorder
![20201010112839](https://user-images.githubusercontent.com/62994244/95644814-c8f4a280-0aeb-11eb-8f7f-0bda151aaa59.jpg)
<img width="1117" alt="xx" src="https://user-images.githubusercontent.com/62994244/95644819-cc882980-0aeb-11eb-900d-2f6203232ecb.png">

**Comment by pissang** [comment]
@tigerHeeJS Perhaps it's caused by animation. You can try turning animation off by setting `animation: false`

Also, do you mind providing this reproducible demo to us
