### ISSUE TITLE
Apply series gradient to value axis

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13407]
### What problem does this feature solve?
Colour axis labels to match series gradient style (from visualMap).

| Before | After (mockup) |
|-|-|
| ![image](https://user-images.githubusercontent.com/470626/95572604-1ad0f600-0a22-11eb-8a18-c1c607326bd7.png) | ![image](https://user-images.githubusercontent.com/470626/95572595-173d6f00-0a22-11eb-8a9b-a29ca095149e.png)

Although it is possible to colour each label one by one on a category axis, it is not possible to apply colours to a value axis.

### What does the proposed API look like?
`yAxis.textStyle.color.type = 'linear'`, etc.

**Comment by Ovilia** [comment]
Visual map works on series data only, but not axis. If you wish to make a similar result, you may try to set [axisLabel.color](https://echarts.apache.org/en/option.html#yAxis.axisLabel.color) with a callback where the color is depended on the index.

**Comment by Bilge** [comment]
But the callback doesn't know what the colour should be, considering the axis has a dynamic scale and no access to the gradient interpolation algorithm.

**Comment by Bilge** [comment]
This is not a support issue, this is a new feature. Is it planned?

**Comment by pissang** [comment]
Perhaps supporting gradient color on the labels can solve this issue.

**Comment by Bilge** [comment]
@pissang If you mean manually applying a gradient then no, that will not help. Since the scale is dynamic (can change), the client will not know how to apply the gradient to the scale itself. The charting library knows the scale and needs to apply it according to the portion of the visualMap that is visible.

**Comment by Bilge** [comment]
Still relevant.
