### ISSUE TITLE
Position tooltip relative to highlighted data item

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13415]
### What problem does this feature solve?
Using tooltip position callback, one can position the tooltip relative to the mouse or bounding container, but it does not expose any information about the highlighted data item or its position.

### What does the proposed API look like?
```ts
series-line.tooltip.position = function (point: Array, params: Object|Array.<Object>, dom: HTMLDomElement, rect: Object, size: Object, itemRect: Object)
```

**Comment by susiwen8** [comment]
I wasn't quiet follow, could you be more specific? Actually, tooltip's position wasn't easy......

**Comment by Bilge** [comment]
@susiwen8 Sure. I want to position the tooltip relative to (near to) a highlighted data item (shown with red arrow) instead of relative to the mouse (shown with red circle).

![image](https://user-images.githubusercontent.com/470626/95653994-bc287c80-0af4-11eb-82fc-d4c9c9d8c764.png)

**Comment by susiwen8** [comment]
Ok, I see, 5.0 will solve this
https://github.com/apache/incubator-echarts/pull/12947

**Comment by Bilge** [comment]
@susiwen8 How did 5.0 solve this? The [documentation for tooltip.position](https://echarts.apache.org/en/option.html#tooltip.position) is word-for-word the same as v4.

**Comment by BenJackGill** [comment]
I am having the same problem. @Bilge did you figure this out?

**Comment by Bilge** [comment]
No. Devs offered a vapour solution and the bot closed it.

**Comment by BenJackGill** [comment]
@susiwen8 can we reopen this issue? Because `tooltip.position` does not solve it.

**Comment by vitaliisusyak** [comment]
For those who are searching for a solution, I've found a workaround.

```
position: (mousePosition: [number, number], params: CallbackDataParams[]) => {
        const xAxisValue = (params[0].value as [number, number])[0];
        const x = this.echrtsInstance.convertToPixel({ xAxisIndex: 0 }, xAxisValue);

        return [x + 10, mousePosition[1]];
}
```

echrtsInstance.convertToPixel will parse a value from the chart to pixels and that can be used as x for tooltip position.
