### ISSUE TITLE
Tooltip marker is hard-coded to 10px

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13413]
### What problem does this feature solve?
There should be a configuration option for the tooltip marker size (maybe also other options, such as border width/color, etc.). Currently it is [hard-coded to 10px](https://github.com/apache/incubator-echarts/blob/fd8417bdce7c36ece9b0cf0419321ce940caa93c/src/util/format.js#L160-L162).

### What does the proposed API look like?
`tooltip.markerStyle.size = 20`

**Comment by susiwen8** [comment]
I think this was by design. Also this feature would be easy to implement, Could you make a PR for it?

**Comment by WillPower98** [comment]
Hi, I'm new to this community and will try to fix it.

**Comment by Bilge** [comment]
no-stale
