### ISSUE TITLE
Tooltip default font differs from rest of chart

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#13414]
### Version
4.9.0

### Steps to reproduce
1. Create chart
2. Add tooltip

### What is expected?
Default font family for chart and tooltip are the same.

### What is actually happening?
Default font family for chart is `sans-serif`, but default font for tooltip is `Microsoft YaHei`.

**Comment by susiwen8** [comment]
Please check 5.0, tooltip's `font-family` should be `sans-serif`
![Screen Shot 2020-10-10 at 19 32 01](https://user-images.githubusercontent.com/20318608/95653984-51486700-0b2f-11eb-912b-56a0d36eb9e4.png)

**Comment by plainheart** [comment]
Sorry, I'm afraid not, the default font of `tooltip` depends on the user's platform. (See https://github.com/apache/incubator-echarts/blob/next/src/model/globalDefault.ts#L64)

The reason why some other components' default font isn't `sans-serif` is that they have been specified with default value in their own model. But the `tooltip` model doesn't specify, so it will use the global default font. (Windows: `Microsoft Yahei`, Others: `sans-serif`)

![image](https://user-images.githubusercontent.com/26999792/95657636-0f77ea80-0b48-11eb-8755-f60205de1a00.png)
