### ISSUE TITLE
 散点图的自定义图标功能在开启大数据量优化之后报错，无法绘制 

### ISSUE THREAD

**Issue by Rwuyao** [apache/echarts#13423]
### Version
4.9.0

### Steps to reproduce
主要配置项：
  symbol: 'image://data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7',
          symbolSize: 5,
          type: 'scatter',
          tooltip: { show: true },
          large: true,
          largeThreshold: 800,

### What is expected?
显示花瓣的图形

### What is actually happening?
报错，只显示轴，其余图标消失
 TypeError: Cannot set property 'x' of undefined
    at Sub.buildPath (LargeSymbolDraw.js:81)
    at Sub.brush (Path.js:107)
    at Painter._doPaintEl (Painter.js:517)
    at Painter._doPaintList (Painter.js:445)
    at Painter._paintList (Painter.js:378)
    at Painter.refresh (Painter.js:260)
    at ZRender.refreshImmediately (zrender.js:237)
    at ZRender.flush (zrender.js:261)
    at ECharts.push../node_modules/echarts/lib/echarts.js.echartsProto.setOption (echarts.js:414)

---
使用大数据量优化后就报错，不使用就不影响

**Comment by Rwuyao** [comment]
在官网找到的一个实例，将图标改为自定义，large设置为true，然后绘制失败，抛出的异常与我自己的代码里面一样。
$.getJSON(ROOT_PATH + '/data/asset/data/house-price-area2.json', function (data) {

    var option = {
        title: {
            text: 'Dispersion of house price based on the area',
            left: 'center',
            top: 0
        },
        visualMap: {
            min: 15202,
            max: 159980,
            dimension: 1,
            orient: 'vertical',
            right: 10,
            top: 'center',
            text: ['HIGH', 'LOW'],
            calculable: true,
            inRange: {
                color: ['#f2c31a', '#24b7f2']
            }
        },
        tooltip: {
            trigger: 'item',
            axisPointer: {
                type: 'cross'
            }
        },
        xAxis: [{
            type: 'value'
        }],
        yAxis: [{
            type: 'value'
        }],
        series: [{
            name: 'price-area',
            type: 'scatter',
            large:true,
             symbol :'image://data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7',
            symbolSize: 5,
            // itemStyle: {
            //     normal: {
            //         borderWidth: 0.2,
            //         borderColor: '#fff'
            //     }
            // },
            data: data
        }]
    };

    myChart.setOption(option);
});

**Comment by TEL1019144699** [comment]
我也遇到了、、、多久能修复啊

**Comment by Rwuyao** [comment]
可惜，官方至今没有回消息



---原始邮件---
发件人: "TEL1019144699"<notifications@github.com&gt;
发送时间: 2020年10月26日(周一) 凌晨0:11
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送: "Rwuyao"<282747051@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [apache/incubator-echarts]  散点图的自定义图标功能在开启大数据量优化之后报错，无法绘制  (#13423)




 
我也遇到了、、、多久能修复啊
