### ISSUE TITLE
api.coord is not a function

### ISSUE THREAD

**Issue by lbhchangyj** [apache/echarts#13430]
### Version
4.2.1

### Steps to reproduce
```js
{
    name: "map",
    type: "custom",
    coordinateSystem: "bmap",
    renderItem: function(params, api) {
        console.log(params.dataIndex)
        let imgPath = "";
        if (
            dataTemp[params.dataIndex].mag > 0 &&
            dataTemp[params.dataIndex].mag <= 50
        ) {
            imgPath = "../common/image/car/car_01.png";
            return {
                type: "image",
                style: {
                    image: imgPath,
                    x: api.coord([
                        dataTemp[params.dataIndex].lng,
                        dataTemp[params.dataIndex].lat,
                    ])[0],
                    y: api.coord([
                        dataTemp[params.dataIndex].lng,
                        dataTemp[params.dataIndex].lat,
                    ])[1],
                    width: 20,
                    height: 19,
                },
            };
        }
    },
    data: dataTemp
}
```

### What is expected?
正常使用

### What is actually happening?
api.coord is not a function
参考#6953 设置require('echarts/extension/bmap/bmap') 依然出现该问题

**Comment by plainheart** [comment]
能否提供更多信息？比如如何 import echarts 和 bmap extension.

**Comment by xulei890817** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=map-polygon
直接下载官方的演示案例，用chrome打开，直接就能复现

**Comment by iyjian** [comment]
有进展吗 @xulei890817

**Comment by pissang** [comment]
这个是因为没有引入 [bmap](https://github.com/apache/echarts/blob/master/extension-src/bmap/README.md) 组件

**Comment by plainheart** [comment]
@pissang 现在代码中的 example list 部分关于 bmap 的示例缺少 `bmap` tag。本地试了下可以正常生成，可能服务器上需要重新生成下。

![image](https://user-images.githubusercontent.com/26999792/135012149-ed3f747d-b604-40d1-89d4-1fcb7ceaaa5b.png)

**Comment by pissang** [comment]
@plainheart 现在服务器没有在部署的时候自动生成，可以生成后提交下~

**Comment by iyjian** [comment]
@pissang 不好意思，再确认下：

文档里  https://echarts.apache.org/en/option.html#series-custom.renderItem.arguments.api.coord  提到的api.corrd仅针对加载了bmap才生效是吗？

**Comment by iyjian** [comment]
不好意思，我知道了，要指定了xAxis和yAxis后才有api.coord方法，是我蠢了，打扰了。

**Comment by CookieMonsterYan** [comment]
请问如果我不想使用bmap应该如何设置和修改代码？
