### ISSUE TITLE
地图拖拽问题

### ISSUE THREAD

**Issue by qqfei1858** [apache/echarts#13439]
### Version
4.9.0

### Steps to reproduce
地图开启鼠标缩放和平移漫游,如果此时平移到可视区外之后,松开鼠标,此时图表无法在平移回来了!

### What is expected?
限制可平移范围区域

### What is actually happening?
没有限制,可以平移至可视区范围外

**Comment by LQ0611** [comment]
我也遇到了相同的问题，555555

**Comment by happyGuo0114** [comment]
请问这个问题解决了吗？
