### ISSUE TITLE
echarts重复setoptions导致图显示不正确

### ISSUE THREAD

**Issue by mumu1349562746** [apache/echarts#13454]
### Version
4.9.0

### Steps to reproduce
使用柱状图时,当数据的值大于轴限制的最大值时,第一次渲染可以正常显示,但是通过鼠标移入移出(echarts自带的那个)后,大于最大值的条目图形会消失,但是数据还在,其他不超过最大值的图形还正常.

### What is expected?
超出最大值的图形显示正常

### What is actually happening?
消失不见

---
想重现,但是在首页中找不到可以绘图的地方,至少不是显而易见的

**Comment by mumu1349562746** [comment]
我这个到底算不算是bug......麻烦给个回应哈

**Comment by susiwen8** [comment]
Please provide a demo, otherwise we cannot confirm you issue.

**Comment by mumu1349562746** [comment]
[上传.zip](https://github.com/apache/incubator-echarts/files/5412562/default.zip)
这个例子上传了

**Comment by mumu1349562746** [comment]
注意看最右边的那列,当你鼠标划过盒子的时候就会出现错乱问题

**Comment by mumu1349562746** [comment]
因为工具框无法通过echarts提供的代码进行动态的是否显示,所以只能使用重新渲染的方式来进行

**Comment by mumu1349562746** [comment]
那个上传.zip就是你们所要的示例了,麻烦看一下

**Comment by pissang** [comment]
这个可能是因为在 toolbox 里设置了 dataZoom 后给过滤了，可以考虑把 dataZoom 去掉

**Comment by mumu1349562746** [comment]
那这个应该属于bug了,正常来说不应该是这种效果,因为数据缩放数图的话(dataZoom)肯定不会影响到正常的渲染的,而且类似的问题我以前提过,目前没有可以打开是否开启toolbox的口子,让我不得不每次都重新渲染一次图形后,在把工具盒子加进去,明显是不合理的
