### ISSUE TITLE
xAxis display multiple times series not align

### ISSUE THREAD

**Issue by Abattista96** [apache/echarts#13466]
### Version
4.5.0

### Steps to reproduce
Use 2 xAxis 'time' with different dates (same time rate) from 00:00 to 23:45, 1 yAxis and 2 sensors data to show:
sensor 1: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sensor 2: [ 1, 2, 3, 4, 5, 6]

### What is expected?
The two time axis align the label on top and bottom

### What is actually happening?
'cause the sensor 2 has less data than the sensor 1, the vertical lines result unaligned.

![histogram problem](https://user-images.githubusercontent.com/73226178/96712067-d0933180-139e-11eb-88f3-cf124f17e158.JPG)

Also the comparison of the data is unaligned:

![histogram problem - cross](https://user-images.githubusercontent.com/73226178/96712561-a0985e00-139f-11eb-89ee-a41810565533.jpg)

---
The labels starts usually at yyyy-dd-mm(1) 00:00 and  yyyy-dd-mm(2) 00:00, but the time depends on the first data. Also the end:
Label sensor 1: (different date 1) 23:45 time of the last data 
Label sensor 2: (different date 2) time of the last data

**Comment by Ovilia** [comment]
Hi. This feature is under reviewing at https://github.com/apache/incubator-echarts/pull/13210 .

**Comment by suyu0925** [comment]
How's it going now?
