### ISSUE TITLE
柱状图yAxis.scale设置为true时，y轴起点从较小的数据开始，导致较小的数据柱子没有高度，设置series.barMinHeight也不生效

### ISSUE THREAD

**Issue by GangLx** [apache/echarts#13463]
柱状图yAxis.scale设置为true时，y轴起点从较小的数据开始，导致较小的数据柱子没有高度，设置series.barMinHeight也不生效。
**而在4.1版本中设置series.barMinHeight后y轴起点依然是较小的数据，但是会有一个最小的高度值**，鼠标移上去也会有提示。

**Comment by GangLx** [comment]
https://gallery.echartsjs.com/editor.html?c=xkkbkvM3gb&v=1

**Comment by GangLx** [comment]
@echarts-bot

> @GangLx Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM or https://gallery.echartsjs.com/editor.html.
请查看这个链接 https://gallery.echartsjs.com/editor.html?c=xkkbkvM3gb&v=1，**66那个柱子没有高度，无法触发点击事件**

**Comment by hhqqnu** [comment]
我也遇到这个问题，测试下来，**5.2版本不存在barMinHeight设置不生效问题**，在5.3版本后存在barMinHeight不生效的问题
