### ISSUE TITLE
关于树图数据data中value值只能是number类型

### ISSUE THREAD

**Issue by zhengls** [apache/echarts#13471]
### What problem does this feature solve?
这个功能限制了只能输入数值类型数据，建议改成string类型，那样能用的范围就大了，number可以转成string,但是string不能转number

### What does the proposed API look like?
无

**Comment by pissang** [comment]
可以传入 string 类型的数据

**Comment by Rogerskelamen** [comment]
可以传入string类型的只有name，要是value传入数字的string的话可以转，纯字母字符不行
