### ISSUE TITLE
map3D dispatchAction showTip not work!

### ISSUE THREAD

**Issue by zhaosheng808** [apache/echarts#13476]
### Version
4.9.0

### Steps to reproduce
`map3D` dispatchAction showTip not work!

but use `map` it can work Normal
```
var options = {
  ...
 series: [{
            type: 'map3D', // 系列类型
            // type: 'map', // 系列类型
            name: 'map3D', // 系列名称
           ...
    }
...
}
...
myChart.setOption(option);
```
```
myChart.dispatchAction({
      type: 'showTip',
      seriesIndex: 0,
       dataIndex: 1
   });
```

### What is expected?
the chart should show tooltip

### What is actually happening?
the tooltip not work

**Comment by zhaosheng808** [comment]
> @zhaosheng808 Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM or https://gallery.echartsjs.com/editor.html.

[codepen demo](https://codepen.io/zhaosheng808/pen/VwjpOrY)

when the `series.type = map` 
```
chart.dispatchAction({
    type: "showTip",
    seriesIndex: 0,
    dataIndex: 0
})
```
the `tooltip` is work well;
when the `series.type = map3D` ,  the the `tooltip` is not show;

**Comment by shahho** [comment]
I have the same problem

**Comment by OliverAndersRWE** [comment]
Hi, 

I have the same problem with bar3D. The funny thing. In the examples on the website it works, but not within my vue application. Any advise would be really appreaciated...

Kind Regards,
Oliver

**Comment by DoubleCorner** [comment]
+1

**Comment by Fuphoenixes** [comment]
same problem

**Comment by deeluxe74** [comment]
Why do we have no news about this?
Nothing in the documentation let think that this not works.

But this is still the case:
https://jsfiddle.net/v75mpfz6/
