### ISSUE TITLE
地图中的放大缩小功能对series中配置的散点图无效

### ISSUE THREAD

**Issue by sharppaw** [apache/echarts#13486]
### Version
4.9.0

### Steps to reproduce
geo中配置了roam为true,但是使用鼠标滚轮对地图进行放大缩小时，series中配置的散点图不会同步放大缩小，这个是什么原因？

### What is expected?
散点图同步放大缩小

### What is actually happening?
散点图还是保持原来的大小

**Comment by pissang** [comment]
散点图是故意设计成固定大小的

**Comment by sharppaw** [comment]
> 散点图是故意设计成固定大小的

那怎么可以让其随地图的放大缩小，也跟着放大缩小？有参数么？还是说需要监听georoam事件？

**Comment by Ovilia** [comment]
散点图大小的单位是像素，而不是坐标系的单位，所以你的需求不适用于散点图，建议使用自定义系列，参见 https://echarts.apache.org/zh/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97

**Comment by sharppaw** [comment]
> 散点图大小的单位是像素，而不是坐标系的单位，所以你的需求不适用于散点图，建议使用自定义系列，参见 https://echarts.apache.org/zh/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97

坐标系的单位是什么？其实我觉得可以设置个参数，配置之后散点图也跟随地图的大小进行缩放

**Comment by sishen654** [comment]
use this prop that you can accomplish the goal.
![image](https://user-images.githubusercontent.com/65691266/227463725-50280523-4d16-4267-a24b-accaf3fdd286.png)
