### ISSUE TITLE
lngExtent/latExtent variables typo of bin maps in examples

### ISSUE THREAD

**Issue by zealscott** [apache/echarts#13493]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=map-bin](https://echarts.apache.org/examples/en/editor.html?c=map-bin)

### Steps to reproduce
In examples of bin map, line 2 and line 3, actual longitude extent and latitude  extent are written reversed.

### What is expected?
Display geographic extent correctly

### What is actually happening?
The result is correct, however, the actual longitude extent should be [115.9, 116.8], the actual latitude extent should be [39.5, 40.6]. 
The author miswrote it.

---
Change the two extent values.

**Comment by plainheart** [comment]
Thanks for pointing out this typo. We will fix it later.
