### ISSUE TITLE
新开窗口，tooltip的mousemove触发失效

### ISSUE THREAD

**Issue by chaserstrong** [apache/echarts#13496]
### Version
5.0.0-beta.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush)

### Steps to reproduce
1.打开实例页面：https://echarts.apache.org/examples/zh/index.html
2.点击K线图的第一个例子，在弹出的窗口中，鼠标的hover事件不能被正常触发，需要点击才能显示tooltip的内容
3.此时刷新页面，鼠标的hover事件就正常触发了
mac：10.13.4 ，chrome：85.0.4183.121

### What is expected?
不应该需要刷新页面才能正常触发

### What is actually happening?
似乎mousemove事件没有被触发？

---
感觉可能是chrome的问题，safari似乎没这个问题。antv似乎也有这个情况。并且发现新开窗口就会有，如果是本页面location.href这种去修改就没问题。

**Comment by chaserstrong** [comment]
刷新页面部分情况下也不能使鼠标的hover事件回复正常。
但是切换下chrome的tab（比如点一下另一个tab窗口，在点回来），就可以使鼠标的hover正常触发了。

**Comment by plainheart** [comment]
能否录制一个动图？我点开鼠标悬浮上去不需要点击就会显示。

**Comment by chaserstrong** [comment]
我又看了下，好像还和浏览器的tab页数量有关，数量多了就会有这个情况，数量少了就不会有。
[demo.mov.zip](https://github.com/apache/incubator-echarts/files/5450240/demo.mov.zip)

**Comment by plainheart** [comment]
感觉是浏览器问题，和 ECharts 本身无关。也许是tab也太多，导致卡顿了吧。

**Comment by chaserstrong** [comment]
> 感觉是浏览器问题，和 ECharts 本身无关。也许是tab页太多，导致卡顿了吧。

是的，但是不仅仅我的电脑，我同事的电脑在tab多了之后也能复现。

**Comment by huzongxin1994** [comment]
The mousemove event is used. The tips of the last two line charts are occasionally incorrect or not displayed. Some people encounter this problem.
