### ISSUE TITLE
Web-assembly Compiling (perhaps using AssemblyScript)

### ISSUE THREAD

**Issue by sirinath** [apache/echarts#13515]
### What problem does this feature solve?
For [V 5](https://github.com/apache/incubator-echarts/issues/12926) is it possible to try to support Web-assembly perhaps through compiling using [AssemblyScript](https://www.assemblyscript.org/) or other means.

### What does the proposed API look like?
There is no change to the API

**Comment by pissang** [comment]
I think it's quite hard for echarts now because AssemblyScript is a very limited subset of TypeScript.
