### ISSUE TITLE
graph 坐标设置x,y无效

### ISSUE THREAD

**Issue by Witee** [apache/echarts#13516]
### Version
4.9.0

### Steps to reproduce
配置如下
```
option = {
    title: {
        text: 'Graph 简单示例'
    },
    series: [
        {
            type: 'graph',
            layout: 'none',
            symbolSize: 50,
            label: {
                show: true
            },
            edgeSymbol: ['circle', 'arrow'],
            edgeSymbolSize: [4, 10],
            edgeLabel: {
                fontSize: 20
            },
            data: [{
                name: '节点1',
                x: 100,
                y: 100,
            }],
        }
    ]
};
```
把上面配置放到下面链接里,就能到效果.
https://echarts.apache.org/examples/zh/editor.html?c=graph-simple

### What is expected?
希望可以根据xy设置位置

### What is actually happening?
xy设置无效

**Comment by Witee** [comment]
单个节点总是在中间, 多个时每个离的很远,配置无效.

**Comment by pissang** [comment]
现在关系图会对整个图进行居中和缩放适应，所以设置的 x, y 值不是最终呈现的像素位置

**Comment by Witee** [comment]
> 现在关系图会对整个图进行居中和缩放适应，所以设置的 x, y 值不是最终呈现的像素位置

那x,y值如何生效呢?

**Comment by haisongzhang** [comment]
如果有一个中心节点[0]，周边有三类节点([1,2,3] [4,5,6] [7,8,9])都跟这个中心节点相连，其他没有相连，那么，如何使得渲染的时候，1、2、3挨在一起，4、5、6挨在一起，7、8、9挨在一起，这样一个簇一个簇的排序，而不是无序的排列。

**Comment by haisongzhang** [comment]
对于这类关系图  https://echarts.apache.org/examples/zh/editor.html?c=graph-force
如果有一个中心节点[0]，周边有三类节点([1,2,3] [4,5,6] [7,8,9])都跟这个中心节点相连，其他没有相连，那么，如何使得渲染的时候，1、2、3挨在一起，4、5、6挨在一起，7、8、9挨在一起，这样一个簇一个簇的排序，而不是无序的排列。请问如何操作？？？谢谢

**Comment by havenothingtosay** [comment]
> > 现在关系图会对整个图进行居中和缩放适应，所以设置的 x, y 值不是最终呈现的像素位置
> 
> 那x,y值如何生效呢?

请问这个问题有解决方法了吗？

**Comment by wamich** [comment]
echarts sucks！such
