### ISSUE TITLE
Labels rendered in the wrong place

### ISSUE THREAD

**Issue by gehringf** [apache/echarts#13528]
### Version
4.8.0

### Reproduction link
[https://jsfiddle.net/rogu5hke/](https://jsfiddle.net/rogu5hke/)

### Steps to reproduce
Drag the datazoom handlers back and forth a couple of times.
At some point, the labels of the items will jump to the top, or be displayed to the left of the y axis.

### What is expected?
Labels stay in the pills, and disappear when the pill is in the filtered area.

### What is actually happening?
Labels are being displayed in the wrong position

---
This also occurs when using in the svg renderer.

![image](https://user-images.githubusercontent.com/56080149/97866087-877e9e00-1d0b-11eb-9cd5-d0f5f1297d98.png)

![image](https://user-images.githubusercontent.com/56080149/97866094-8a798e80-1d0b-11eb-911b-c73657aa62e0.png)

![image](https://user-images.githubusercontent.com/56080149/97866104-8cdbe880-1d0b-11eb-8802-ec82eabbb48c.png)

**Comment by pissang** [comment]
I did some changes to your case
https://jsfiddle.net/ce10fqrh/
![image](https://user-images.githubusercontent.com/841551/97947025-fe2ca180-1dc6-11eb-8913-28a22022bf36.png)

**Comment by gehringf** [comment]
Thank you, that solves it for me in this case. 

I also created a bar chart into the same thing and when dragging the datazoom handlers the bars are being displayed outside of the chart, as long as I don't use a filter. Is that a bug or is there something like "overflow:hidden" for that chart that I'm missing. I try not to use a filter, so that my (yet another) line chart can render while having few datapoints, of which some could be outside of the current datazoom range.

**Comment by pissang** [comment]
You can try to set `clip: true` in bar series to hide the overflow.

**Comment by gehringf** [comment]
> You can try to set `clip: true` in the bar series to hide the overflow.

That's true by default and doesnt seem to change anything for me when using datazoom.

![image](https://user-images.githubusercontent.com/56080149/98091439-bd479200-1e85-11eb-9458-63c9de1f9a23.png)

**Comment by gehringf** [comment]
I made an example with that over here:
https://jsfiddle.net/qdu3bz4w/

**Comment by pissang** [comment]
It seems to be an issue that not supposed to happen. Do you mind opening another issue to track it?

**Comment by gehringf** [comment]
Back to the actual issue… When you zoom in so that one of the bars fills the whole view, sometimes the label will just jump out and be displayed elsewhere even though there is enough space for the word. 

![image](https://user-images.githubusercontent.com/56080149/98520243-13477b80-2272-11eb-862d-b1c0a3d862ad.png)
