### ISSUE TITLE
Gantt Chart struggles to render more than 4000 events

### ISSUE THREAD

**Issue by ChristofSchwarz** [apache/echarts#13534]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/ht6z539q/9/](https://jsfiddle.net/ht6z539q/9/)

### Steps to reproduce
Change the horizontal zoomable slider at the bottom to "zoom in" into some parts of the gantt grid, keep changing the zoom level, also move the vertical slider up and down, at some point, some of the rectangles on the gantt grid will freeze and stay as rendering issues. I took the example from https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight but added sample data, creating 5000 events for the gantt grid. With try&error I found out, that 4096 events on the gantt grid seem to be the maximum before above rendering issue occurs.

### What is expected?
All rectangles of the gantt grid should render correctly, depending on the sliders zoom factor and position

### What is actually happening?
some rectangles in the lower right part eventually freeze when moving the sliders

**Comment by ChristofSchwarz** [comment]
Any response on this issue? Moving the sliders fails to reposition more than 4096 objects, that is very annoying

**Comment by pissang** [comment]
@ChristofSchwarz Hi, we will try to fix it in 5.1.0
