### ISSUE TITLE
vue3 chart can't render again 

### ISSUE THREAD

**Issue by Nicolaschinc** [apache/echarts#13537]
### Version
4.9.0

### Steps to reproduce
1、access a route component which contains chart
2、access another route and back

### What is expected?
chart can render again if it have rendered

### What is actually happening?
chart cant render again but it can create a canvas element and ake up the blank position

**Comment by Enoooch** [comment]
@Nicolaschinc Hi, I can reproduce this issue in production mode.

Replace `document.getElementById('chart')` with `pieChartRef.value`, or add `v-if v-show` to dom element can avoid this.

#### Versions
vue: v3.2.24 with `<script setup>` syntax
echarts: v5.2.1

#### Related issue 
[#14028](https://github.com/apache/echarts/issues/14028)

Still trying to figure out why.

**Comment by 2000calories** [comment]
@Enoooch Thank you so much. I just have the same problem.
