### ISSUE TITLE
Radar: indicator names can go beyond canvas (thus clipped)

### ISSUE THREAD

**Issue by qortex** [apache/echarts#13551]
### Version
4.9.0

### Reproduction link
[https://codepen.io/qortex/pen/qBNyxyv](https://codepen.io/qortex/pen/qBNyxyv)

### Steps to reproduce
Put too large names for indicators. They spill out of the canvas.

### What is expected?
Text should be visible: canvas should contain the text (or wrap it?)

### What is actually happening?
Text spill out of the canvas.

---
Workaround is to word wrap the labels by hand (insert \n in the text) and take a safety margin by reducing the radar radius. But there is no guarantee the margin is high enough (or too high and waste space).

**Comment by pissang** [comment]
In the coming 5.0 text can be set width and a newline will be applied if text is overflow.

**Comment by qortex** [comment]
Great thanks!

Do you think there's a way to make this automatic in the sizing algorithm? Because figure size is usually set through percentages. Mixing in Pixels might not be optimal and still lead to issues when in a responsive setting. What do you think?

**Comment by yassipad** [comment]
> In the coming 5.0 text can be set width and a newline will be applied if text is overflow.

Unfortunately, it seems that the width property still isn't supported in v5. The online demo isn't either: https://echarts.apache.org/next/en/option.html#radar.name.width.

**Comment by pissang** [comment]
@yassipad You also need to set `overflow` to `'truncate'` or `'break'`

**Comment by kalyanvedurumudi** [comment]
https://echarts.apache.org/en/option.html#radar.axisName.width

Even with the width property and adding overflow as truncate, we are not able to see ellipsis for the indicator names. Any update on this?

**Comment by michaelrampl** [comment]
Facing the same issue on 5.2.2
```
axisName: {
              overflow: "breakAll",
              width: 25,
              textBorderType: "solid",
              borderWidth: 1,
              borderColor: "#000000"
            },
```
This clearly shows that only 1 line is being drawn.

**Comment by gagarine** [comment]
Reproduction with the 5.x version https://codepen.io/gagarine/pen/mdLpEOj

Not only the label does not truncate, but also the radar size is not adapted to the container.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/164074/192389884-6461b511-0b0d-463a-941d-9d2e2669bbb7.png">

**Comment by MichealF26** [comment]
Any update on this?

**Comment by MichealF26** [comment]
The workaround I'm currently using is to escape a newline character within the indicator text like this
```bash
option = {
  title: {
    text: 'Basic Radar Chart'
  },
  legend: {
    data: ['ACME Corp']
  },
  radar: {
    indicator: [
      { name: 'Data Mining and Statistical Analysis', max: 5 },
      { name: "Data visualisation, \nstorytelling with \ndata and presentation", max: 5 },
      { name: 'Business Intelligence and Strategy', max: 5 },
      { name: 'Database Management and Architecture', max: 5 },
      { name: 'Cloud and distributed computing', max: 5 },
      { name: 'Machine learning / Cognitive computing', max: 5 },
    ]
  },
  series: [
    {
      name: 'Expertise',
      type: 'radar',
      data: [
        {
          value: [4, 5, 2, 5, 3, 2],
          name: 'ACME Corp'
        }
      ]
    }
  ]
};
```

<img width="1048" alt="Screenshot 2022-10-17 at 09 44 37" src="https://user-images.githubusercontent.com/17140398/196118775-4336e332-9b8a-4087-9dfb-ec22376391eb.png">


Please take note that you have to escape with double quotes as single quotes will not escape the newline character

**Comment by gagarine** [comment]
@DoctorDerek  posted on another workaround in #16391 (duplicate) that reduce the raduis.

```
// ...
  radar: {
    shape: 'polygon',
    indicator, // the data labels as an array
    center: ['50%', '50%'],
    radius: '50%',
  },
// ...
```
