### ISSUE TITLE
折线图区域填充渐变色谷歌浏览器显示异常

### ISSUE THREAD

**Issue by ht7811** [apache/echarts#13599]
### Version
5.0.0

### Steps to reproduce
1.打开官方实例；
2.找到有区域填充渐变色的折线图；
3.在火狐浏览器打开折线图；
4.在谷歌浏览器打开同一个折线图；

### What is expected?
不同浏览器折线图的区域填充渐变色显示一致

### What is actually happening?
显示不一致

**Comment by plainheart** [comment]
Duplicated of #13323.
请检查 Chrome 是否为最新版本，如不是最新版本，请尝试更新后再试。
