### ISSUE TITLE
h5下toolbox的保存图片在app上无法生效

### ISSUE THREAD

**Issue by jarvis-chenjw** [apache/echarts#13592]
### Version
4.1.0-release

### Steps to reproduce
写个h5页面，在app上访问，保存图片不生效

### What is expected?
实现图表保存

### What is actually happening?
实现图表保存

---
实现图表保存

**Comment by plainheart** [comment]
4.1.0 有些旧了，使用新版试试看是否仍存在问题？

**Comment by Ovilia** [comment]
如果最新版本不生效，请用上面的链接提供一个可复现的例子
