### ISSUE TITLE
Tree chart rerenders as I add new children to each node data

### ISSUE THREAD

**Issue by IamKennethBurla** [apache/echarts#13609]
### Version
4.9.0

### Issue
Currently what I'm doing is updating the data I'm supplying to echarts component (ReactEcharts). 
As expect it would re-renders everything when I update the data (`series.data`). What I would like to happened is just update the data and append the node children to chart, without re-rendering the actual chart instance

Is it possible or is there already a workaround to achieve such output?.

### Sample scenario

![rerender issue](https://user-images.githubusercontent.com/36767756/98917980-05ab2380-2508-11eb-9fc8-27de7dcb5dd0.gif)

### What is expected?
Attach an additional node children without re-rendering tree chart instance

### What is actually happening?
Re-renders tree chart instance when I update `series.data` of tree chart

**Comment by IamKennethBurla** [comment]
> @IamKennethBurla Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM or https://gallery.echartsjs.com/editor.html.

Here is a demo of the scenario. https://codesandbox.io/s/crypto-node-tree-0imgc?file=/src/Chart.js
When you click the node2 it'll re-render the entire chart.
Looking for a way to just append the data to current instance without re-rendering the entire chart

**Comment by pissang** [comment]
I'm not familiar with React. But I guess it's probably because each time the chart is recreated. Also, you need to set {notMerge} to false

**Comment by IamKennethBurla** [comment]
But is it possible not to rerender the chart on outside react?
