### ISSUE TITLE
Brush selection changes upon resizing

### ISSUE THREAD

**Issue by myammt** [apache/echarts#13608]
### Version
5.0.0

### Reproduction link
[https://codepen.io/myammt/pen/GRqPrvb](https://codepen.io/myammt/pen/GRqPrvb)

### Steps to reproduce
Open the demo provided by CodePen, try to do brush selection of some columns and then resize the window, you will notice that the selection has changed when resizing.
**Note:** this is not reproduced all the time you might need to run the demo many times to get the bug reproduced

### What is expected?
brush selection should be the same upon resizing of the chart

### What is actually happening?
selected columns are different upon resizing of the window

**Comment by Ovilia** [comment]
I believe this is a bug.

**Comment by Supertramplee** [comment]
+1 resize()事件触发后  brush刷选的位置未做同步处理
