### ISSUE TITLE
Allow the use of alignWithLabel prop inside splitLine type 

### ISSUE THREAD

**Issue by leorigon** [apache/echarts#13618]
### Version
4.9.0

### Steps to reproduce
Before of the types definitions, at old versions, we could be use the `alignWithLabel` as property of other objects inside charts. For example, at `xAxis.splitLine.alignWithLabel`. This is necessary to align the grid background with ticks labels when we use category instead values on the axis. It's work fine, like to example, but the typescript compiler throw an error because this object isn't declared on the `splitLine` type. 

example:

```
 splitLine: {
        show: true,
        // @ts-ignore It's works, but typescript reclaim! :(
        alignWithLabel: true,
        lineStyle: {
          type: 'solid',
          opacity: 0.2,
          color: props.color || 'red'
        },
```
![Captura de tela_2020-11-13_10-58-39](https://user-images.githubusercontent.com/32500054/99079911-51f57280-259f-11eb-8c02-2210ed442e93.png)

On the docs today, I have noted this property was removed.

### What is expected?
Allow alignWithLabel on the splitLine object. 

### What is actually happening?
TypeScript thrown an error, but the option works correctly.

**Comment by pissang** [comment]
`alignWithLabel` should be a property in `axisTick`

**Comment by leorigon** [comment]
@pissang 
> `alignWithLabel` should be a property in `axisTick`

When I remove `alignWithLabel` from `splitLine` and I pass only `axistick`:
![Captura de tela_2020-11-16_13-12-23](https://user-images.githubusercontent.com/32500054/99278243-925a2800-280d-11eb-95f0-b6d894c2f3bf.png)

**Comment by pissang** [comment]
@leorigon . Understand, I think it's our fault on doc and types. Will fix it

**Comment by kor44** [comment]
Echarts version is already 5.3 but documentation has not been updated
