### ISSUE TITLE
How can I display curved labels in a pie/doughnut chart?

### ISSUE THREAD

**Issue by zhpeh** [apache/echarts#13616]
### What problem does this feature solve?
Hi,

I have a nested pie chart with long label names. I prefer to display the labels 'inside' instead of 'outside', but the text is extending outside the pie area. I understand that I can use formatter to add line breaks, or rotate the text. However, I would prefer to display the labels as curved labels, depending on the shape of the pie chart.

How can I achieve this?

Appreciate your help! Thank you!

### What does the proposed API look like?
Perhaps something like this?

label: {
     position: 'inner',
     rotate: 'auto'
},

**Comment by zhpeh** [comment]
Hi,

Appreciate if someone can guide me on this. Basically I just want to know if it is possible for me to rotate the label display of my pie chart, based on the curvature of the pie chart so that it fits nicely within the pie. 

Thanks.

**Comment by pissang** [comment]
@zhpeh Hi, do you mind giving us a reference example picture?

**Comment by zhpeh** [comment]
Sure, please refer to this [image](https://drive.google.com/file/d/16L8XK_cvSbX4NXxgCdTOraho7BnMzsL1/view?usp=sharing)

**Comment by pissang** [comment]
Thanks, curved text is not supported natively by canvas. So we may need time to think about how to implement it perfectly.

**Comment by zhpeh** [comment]
I see, thanks for the clarification! Appreciate if your team can look into this as I believe it will benefit other users as well.

Could you keep me posted if there's updates on this request? I will stick to using "outside" labels for now.

**Comment by pissang** [comment]
@zhpeh Sure
