### ISSUE TITLE
 When the Xaxis type is value, the minimum value of dataZoom starts from 0 by default. Can it start from the Xaxis minimum value?

### ISSUE THREAD

**Issue by Alexander-txj** [apache/echarts#13624]
### Version
4.9.0

### Steps to reproduce
set Xaxis to value

### What is expected?
When the Xaxis type is value, the minimum value using dataZoom starts from 0 by default, and dataZoom can start from the Xaxis minimum value.

### What is actually happening?
set Xaxis to minimum

**Comment by wf123537200** [comment]
Is this issue the same as [12507](https://github.com/apache/incubator-echarts/issues/12507)？
And 12507 will fix at 5.0
