### ISSUE TITLE
Live data stream for plotting

### ISSUE THREAD

**Issue by bashman** [apache/echarts#13622]
### What problem does this feature solve?
Hi I need plot an OHLC chart, I am using a websocket implementation and I have a data stream.  I need plot live data, is possible in OHLC charts and another types?.  Thanks

### What does the proposed API look like?
-

**Comment by pissang** [comment]
Hi @bashman . You can always use `setOption` to update the data when new data comes.

**Comment by symlons** [comment]
@pissang when updating with the data with setOption I receive: Error: `setOption` should not be called during main process.
