### ISSUE TITLE
Custom positions for axis labels/ticks

### ISSUE THREAD

**Issue by dvdkon** [apache/echarts#13627]
### What problem does this feature solve?
I want to be able to define custom locations for labels and ticks on axes. Currently, they are always positioned monotonically based on an interval. My use case for this is pointing out interesting events, like important train stops in the below example or important events on a time-series chart (e.g. "ad posted to Twitter" on a chart of site visits).

Desired outcome:
![Desired outcome](https://i.imgur.com/ysIGg77.png)

I can currently achieve this kind of effect with ECharts, but it's incredibly hacky and works by using a category axis with most category names as empty strings. ([code](https://jsfiddle.net/6jxkw2rf/)). My objection isn't just that the code is ugly, getting the precision needed to zoom on data would require a category axis with possibly hundreds of thousands of values.

### What does the proposed API look like?
```js
options = {
  xAxis: {
    type: "value",
    axisLabel: {
      // If this is defined, no labels will be autogenerated.
      custom: [
        8, // A label will appear on axis value 8
        10,
      ],
      // The label text will be set through formatter as before
    },
    // Same for ticks
    axisTick: {
      custom: [8, 10, 12],
    },
  },
}
```

**Comment by artu-ole** [comment]
Some possible workarounds for the annotation feature include x axis with category type and empty string padding:
![image](https://user-images.githubusercontent.com/15938416/167394825-b7aeb988-0072-442e-869e-17de7c74c380.png)

https://jsfiddle.net/artuole/j14aenf3/

or mark areas:
![image](https://user-images.githubusercontent.com/15938416/167395288-4689e06e-c444-4168-a9f5-1e16ce81a11b.png)
https://jsfiddle.net/artuole/xqjy6sLe/2/

**Comment by ethannguyen276** [comment]
Hi, is there any update on this? I also would need this feature.

**Comment by CavalcanteLeo** [comment]
im looking for this too

**Comment by sarabisohrab** [comment]
Hi, it would be great to have such useful feture!

**Comment by andrius-kurtinaitis** [comment]
Yes. It is unexpected I cannot decide exact positions for my labels.
My suggestion is to allow _custom_ to accept a function which returns array of labels based on zoom, chart width etc.

**Comment by EggTronic** [comment]
looking for this

**Comment by praful-hunde** [comment]
![image](https://user-images.githubusercontent.com/6948167/220893349-8e93a1b3-0977-4789-90d3-d7fe9e21a8fb.png)
I want to add the label on X Axis at the locations of the dotted lines. The proposed feature will help in this case.

**Comment by fasergeyte** [comment]
Hi, is there any update on this?

**Comment by FirokOtaku** [comment]
@praful-hunde a temporary solution: use image as `markLine` symbol

Here I'm creating a canvas element for drawing image then convert it into `dataURL`.
Or you could convert any other image into `dataURL` too.

```javascript
// create canvas and resize it
const domCanvas = document.createElement('canvas')
domCanvas .width = 56
domCanvas .height = 24

// draw anything on it
const ctx = domCanvas .getContext('2d')
ctx.font = '24px serif'
ctx.fillStyle = 'red'
ctx.fillText('30', 0, 24)

// convert into dataURL
const dataurlImg = domCanvas.toDataURL()
window.dataurlImg = dataurlImg
```

chart option:

```json
series: [
  {
    ...
    markLine: {
      symbol: ['image://' + window?.dataurlImg, null], // set label only for one side
      symbolSize: [28, 12], // scale a big picture into smaller size for clearity
      symbolRotate: [0, 0],
      symbolOffset: [[0, -2], [0,0]],
      ...
    },
```

preview:

![image](https://github.com/apache/echarts/assets/13001378/9d03f4e0-0d50-4ee5-a31f-3eeb4586f524)

not looks very good, but it just works for some cases (at least my case).

**Comment by acsabi310** [comment]
It would be really good to have something like this. For now, when an axis is typed as 'value' with for example min: 0 max: 120, in the axisLabel's formatter callback function I just got 0,20,40,...,120 for the values.
If I could get all the integer values, I could write my own logic to show specific labels. Supporting the 'interval' property would be beneficial too.
So I could have something like this:
![image](https://github.com/apache/echarts/assets/11329062/2b925a9c-7efc-4a8b-82a6-6387bc853ac6)

**Comment by jlefeaux** [comment]
I was able to do this by hiding the x-axis labels and adding vertical marklines.

![image](https://github.com/apache/echarts/assets/14351679/17fcbbaa-aad0-47c0-9d3d-340728fcf932)

```
markLine: {
      data: stages.map(stage => ({
        xAxis: stage,
      })),
      symbol: "none",
      label: {
        position: "start",
        formatter: params => (params.value === +stages.at(-1) ? "Close" : params.value),
      },
},
```
