### ISSUE TITLE
Test Automation (E2E) Support from ECharts

### ISSUE THREAD

**Issue by msbasanth** [apache/echarts#13635]
### What problem does this feature solve?
Currently does not have support for automating charts created using ECharts. As the DOM structure of charts created using ECharts differ according to the renderer used (SVG or Canvas) it is good if ECharts provide API's for End to End Test (e2e) test automation.

### What does the proposed API look like?
ECharts should have provision for running test automation according to the underlaying technology used.

1. We should be able to trigger events (click on graphic objects and basic elements of charts)
2. Should provide examples showing e2e test automating charts

Good if we have a section in documentation "how to do test automation" in when we create charts using ECharts.

**Comment by pissang** [comment]
I think you can use puppeteer to run tests. That's what we do in our regression tests.

**Comment by msbasanth** [comment]
@pissang 

Thanks for the quick reply. :)
Could you please point to some examples of Puppeteer usage for automating ECharts components? Mainly looking for how generically write automation test cases for SVG and Canvas based charts.

Currently we are in Angular environment with Protractor/Cypress as our E2E testing framework. We will look into Puppeteer examples to replicate the same with Cypress or Protractor.

**Comment by msbasanth** [comment]
@pissang thanks for pointing to regression tests.

I had a look into the current test automation possibilities with ECHarts. 

**Observations**

Open Questions:
•	how do I click on an echarts series?
•	How to trigger specific pointer events (click, mouse up, …) on echarts objects?

**E2E in SVG Based Charts** 

* In comparison to other SVG based charts support for e2e automation using objects inside the charts is minimal in ECharts. Reason is we will not find proper selectors for reaching the elements inside ECharts.
* DOM structure of charts created using ECharts differ according to the renderer used (SVG or Canvas).

_Example DOM structure - HighCharts_
![image](https://user-images.githubusercontent.com/17777813/105347876-832c9780-5c0d-11eb-8c70-3f597d8a220d.png)

_Example DOM structure - ECharts_
![image](https://user-images.githubusercontent.com/17777813/105347558-17e2c580-5c0d-11eb-8172-e369bd5378b6.png)

This is what we see when tried to access SVG elements inside ECharts. As you could see it is very difficult to locate a particular object as there is no proper locators available. Using nth-child will make the test script tough to maintain generally not recommended
![image](https://user-images.githubusercontent.com/17777813/105348031-bd963480-5c0d-11eb-86c9-994b7719ac9f.png)

**Visual Regression Testing – The ECharts way of filling the gap of functional testing**
ECharts team they use puppeteer and their visual regression testing tool for checking the visual expectations.
 
![Uploading image.png…]()

ECharts they are using pixelmatch (https://www.npmjs.com/package/pixelmatch) for their image comparisons.
Find more details in their repository. @ echarts\test\runTest\compareScreenshot.js

**Comment by msbasanth** [comment]
@pissang thanks for pointing to regression tests.

I had a look into the test automation possibilities with ECharts.

## **Observations**

### E2E in SVG Based Charts

In comparison to few other SVG based charts, the support for functional testing by accessing elements inside the charts is minimal in ECharts. We will not find selectors for reaching the elements inside ECharts SVG DOM tree.

_Example DOM structure - HighCharts_
![image](https://user-images.githubusercontent.com/17777813/105348305-2aa9ca00-5c0e-11eb-86c0-b57348df3684.png)

_Example DOM structure - ECharts_
![image](https://user-images.githubusercontent.com/17777813/105348331-33020500-5c0e-11eb-877f-34c53ef21e22.png)

This is what I got when tried to record actions on SVG elements inside ECharts. It is difficult to locate a particular object as there is no locators available. Using _nth-child_ will make the test script tough to maintain and not recommended
![image](https://user-images.githubusercontent.com/17777813/105348347-3c8b6d00-5c0e-11eb-9e7d-a294ff46c866.png)

### **Visual Regression Testing – The way ECharts overcome above mentioned limitation**
Using puppeteer and visual regression testing tool ECharts able to check their visual expectations.

![image](https://user-images.githubusercontent.com/17777813/105348402-4ad98900-5c0e-11eb-823d-e33a4532b1cc.png)

ECharts uses pixelmatch (https://www.npmjs.com/package/pixelmatch) for their image comparisons.
Find more details in their repository. @ echarts\test\runTest\compareScreenshot.js

EChart uses automating mouse interactions (X, Y) for recording and preparing visual tests. This can be followed in applications using ECharts for covering the functional test gap that we currently have.

**Using Cypress for Visual Testing ECharts**

Cypress have support for screenshots which we can use for visual testing as well.
_Cypress Image Snapshot_ package binds jest-image-snapshot's image diffing logic to Cypress.io commands.
https://github.com/jaredpalmer/cypress-image-snapshot
![image](https://user-images.githubusercontent.com/17777813/105348672-b28fd400-5c0e-11eb-844f-31bb35d59b5f.png)

Disadvantage with Visual Testing is we are tied to specific test environment.

### **ECharts Dispatch Actions:**
Using dispatch actions provided in ECharts we can trigger many interactions normally used in charts.
https://echarts.apache.org/en/tutorial.html#Events%20and%20Actions%20in%20ECharts

NB: Cypress has access to the real HTMLElements for triggering actions.

**So it looks like we can cover functional testing (by directly accessing chart object) limitation using visual testing & dispatchAction API.**

In case you have additional thoughts or difference in opinion please share.
It would be really good if you could add **testability APIs for handling pointer events in elements inside chart**. So that the  implementation details like technology (canvas/svg) or the SVG DOM structure changes etc. can be abstracted.
