### ISSUE TITLE
Can maps support custom cursor style?

### ISSUE THREAD

**Issue by jxiangji** [apache/echarts#13632]
### What problem does this feature solve?
most of series support to set cursor style but map,Can map support custom cursor style?
like this:
```
series:[{
  type: 'map',
  data: [
    {item:'aa', itemStyle:{cursor:'move'}},
    {item:'bb', itemStyle:{cursor:'pointer'}},
    {item:'bb', itemStyle:{cursor:'none'}},
  ]
}]
```

### What does the proposed API look like?
series

**Comment by Ovilia** [comment]
Similar to: #10584 graph series
