### ISSUE TITLE
请问graph模式可以显示每个小点的标题吗

### ISSUE THREAD

**Issue by whereiscode** [apache/echarts#13641]
### Version
5.0.0

### Steps to reproduce
官方案例复制调参数就能测试

### What is expected?
能设置小点标题

![](https://user-images.githubusercontent.com/55313887/99482438-d75d9600-2996-11eb-8eda-9d537c96a7b8.png)

### What is actually happening?
没有设置的文档

**Comment by pissang** [comment]
这是官网示例设置的效果，你可以把 
```js
node.label = {
            show: node.symbolSize > 30
        };
```
这行改成
```js
node.label = { show: true }
```
