### ISSUE TITLE
Please add support for configuring color property by function for all chart type.

### ISSUE THREAD

**Issue by x-strong** [apache/echarts#13657]
### What problem does this feature solve?
As of the latest version of ECharts, the auto generate color is random, in some special businese case, random color is lack of meaning, and confuse user.
Flexibly config & control chart color, and make chart much more readable and meaningful. for example, a bar chart( horizontal) showing kafka topics disk usage, if I can control / config the bars color by function, then I can set the bar color according to the usage percentage, 50% < green, 50% <= oringe < 70%, 70% <= yellow < 80%, 80% <= red. Why do I need to set colors like that? Here I'd like to introduce a concept that we can just call it "semantics color", and it includes two kind of colors, safe color (green, some what like the traffic light) and warn color(yellow, oringe and red). If so, user can easily and quickly differentiate the imortant part and focus on those disk over-use topics.

### What does the proposed API look like?
Color property can accept a functon which return the specific colors structure that match the chart type, and the function parameter is also specific to the chart type.

**Comment by Ovilia** [comment]
Hi. What series type are you using?

**Comment by x-strong** [comment]
> Hi. What series type are you using? It shouldn't use "random" color by default.

Bar series.

echarts official example of bar chart : https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category

**Comment by x-strong** [comment]
> Hi. What series type are you using? It shouldn't use "random" color by default.

It is not 'random' color, it is meaningful color as I described before. And here is an example: https://echarts.apache.org/examples/en/editor.html?c=bar-y-category&lang=js&version=5.0.1
```js
itemStyle:{
        color: (params)=> {
          if(params.value > 30000) {
            return 'red';
          }else if( params.value < 30000) {
            return 'green';
          }
        }
      }
```
![Echarts bar chart item style customized colors](https://user-images.githubusercontent.com/3232261/174703936-c1f07b56-a07b-4a69-9774-21d03c21d841.png)

As far as I know, all echarts versions  support customizing item style color, even custom function that returns colors conditionally. The [official document](https://echarts.apache.org/en/option.html#color) do not mention that the `Color` option support for custom function, Why? In fact it supports.

@Ovilia Did you forget to review this issue?
