### ISSUE TITLE
incorrect continous color mapping on maps if min and max is same

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#13668]
### Version
5.0.0

### Steps to reproduce
Navigate to https://echarts.apache.org/examples/en/editor.html?c=map-usa

Change the visualMap and data options to the following and leave the rest as is.

1) visualMap options
```
       visualMap: {
            left: 'right',
            min: 4822023,
            max: 4822023,
            inRange: {
                color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
            },
            text: ['High', 'Low'],           // 文本，默认为数值文本
            calculable: true
        },
```

2) series data options

```
                data:[
                    {name: 'Alabama', value: 4822023},
                ]
```

### What is expected?
Expect to see only the single state with data to have the color.

### What is actually happening?
Entire map has the same color including the state with the data.

---
If I set the min and max to be different values, the coloring works fine. However,  in my case the min/max are automatically calculated based on the data and if there is data for a single state, this happens.

**Comment by Ovilia** [comment]
I think in this case, the last color should be used instead of the center one, similar to [the case of degenerated CSS gradient](https://www.w3.org/TR/css-images-3/#degenerate-radials).

> This will make the gradient look like a solid-color image equal to the color of the last color-stop, ...

**Comment by pissang** [comment]
I think the main issue here is only `Alabama` should be expected to have color. But instead, all regions have colors now when min, max is same.

**Comment by Ovilia** [comment]
@pissang is right. I took the demo as piecewise visualMap by mistake.
