### ISSUE TITLE
微信小程序多次切换后白屏且会闪退

### ISSUE THREAD

**Issue by jiucheng-front** [apache/echarts#13661]
### Version
4.6.0

### Steps to reproduce
微信小程序中自定义多个切换按钮，每次切换都有新的图表，多次(6-7)次切换后图标白屏，且偶尔会导致微信闪退。尝试每次init之前clear和dispose，都未解决。。

### What is expected?
每次切换都有新的图标数据

### What is actually happening?
切换多次之后图标白屏且会导致微信闪退

**Comment by Ovilia** [comment]
试一下除了 dispose 之外把变量设为 null，另外检查下切换页面后之前页面的 dom 节点是不是移除了，如果是的话，下次重新进入这个页面的时候，节点是否能正常获取到，并且是否有宽高。

**Comment by jiucheng-front** [comment]
@Ovilia 是这样的(尝试过clear,dispose,设置为null没解决，才来寻求支援)，小程序中按钮切换若使用wx:if(会导致DOM移除)，这样每次切换就要重新执行echarts.init，会导致多次切换后图表空白(数据丢失)，偶尔微信闪退。。换了方案(切换按钮不让DOM移除)，只是想通过重新setOption更新图表，在微信开发者根据可以正常更新，在实际真机中就不会更新，setOption的第二个参数强行给true，还是不行！！有没有更好的解决方法了？

**Comment by Ovilia** [comment]
可以试试先 dispose，设 null，然后改变变量移除 dom 呢？

**Comment by jiucheng-front** [comment]
尝试过了。不行咯~

**Comment by jiucheng-front** [comment]
@Ovilia 尝试过dispose且设置为null，没解决。现在换的方案：(每次切换按钮不让DOM移除，只是视觉上隐藏)，通过重新setOption更新图表，在微信开发者根据可以正常更新，在实际真机中(Android可以正常)IOS就不会更新，setOption的第二个参数强行给true~

**Comment by Ovilia** [comment]
setOption 不给 true 就不更新图表？这看起来很奇怪

**Comment by jiucheng-front** [comment]
不是不给true就不更新。是给了true之后微信开发者工具能正常更新，安卓系统小程序也能正常更新，IOS就不正常更新！

**Comment by 18626879419** [comment]
> 不是不给真就不更新。是给了真之后微信开发者工具能正常更新，安卓系统小程序也能正常更新，IOS就不正常更新！

你好，请问这个问题解决了吗？同样也遇到这个问题了

**Comment by jiucheng-front** [comment]
> > 不是不给真就不更新。是给了真之后微信开发者工具能正常更新，安卓系统小程序也能正常更新，IOS就不正常更新！
> 
> 你好，请问这个问题解决了吗？同样也遇到这个问题了

抱歉,很少看这里~没解决，凑合用
