### ISSUE TITLE
Add a property to control data item layer index or make item slient to mouse event.

### ISSUE THREAD

**Issue by zmzimpl** [apache/echarts#13662]
### What problem does this feature solve?
[Example](https://www.makeapie.com/editor.html?c=xxV08_eRtq&v=1)
Like this example, the chart was built by two pies, some items was set to transparent, when the mouse hovers on them,  sometimes it will trigger the part of transparent items but not what I actually want to trigger.

### What does the proposed API look like?
Add a property `z` or `slient` to item. Like this:
```
        {
          "value": 9469224,
          "name": "未完成",
          "z": -1,
          "sliemt": true,
          "itemStyle": {
            "color": "transparent"
          }
        }
```

**Comment by Ovilia** [comment]
Sorry, I didn't understand it. What effect are you trying to get here?

**Comment by zmzimpl** [comment]
> Sorry, I didn't understand it. What effect are you trying to get here?
![微信截图_20201124142149](https://user-images.githubusercontent.com/27490895/100056438-a5e63e00-2e60-11eb-8e68-7cd9bb5f4abc.png)
![微信截图_20201124142010](https://user-images.githubusercontent.com/27490895/100056463-b0083c80-2e60-11eb-97f3-534fafabf356.png)


See these images, the first image is trigger the transparent item, and the second image is what I actually want to trigger, they have the same position in the chart, but sometimes the item which I actually want to trigger was covered by the transparent one.
Sorry for my poor English.

**Comment by Ovilia** [comment]
Why do you need the transparent item?

**Comment by zmzimpl** [comment]
> Why do you need the transparent item?

Like this [demo](https://www.makeapie.com/editor.html?c=xxV08_eRtq&v=1). Just because I want to build a progress pie which completed part through uncompleted part, I built it by two pies and set different radius on them, like this:
![image](https://user-images.githubusercontent.com/27490895/100065117-5e66ae80-2e6e-11eb-9d7d-1410651b055f.png)

**Comment by Ovilia** [comment]
This is not the best way to make what you need. I would suggest using [custom series](https://echarts.apache.org/en/tutorial.html#Custom%20Series) to make the pie.
