### ISSUE TITLE
dynamic-data line (area) chart doesn't update series with smoothly animation

### ISSUE THREAD

**Issue by JasonXDDD** [apache/echarts#13689]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/apbxugh5/](https://jsfiddle.net/apbxugh5/)

### Steps to reproduce
I copy https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2 sample, make it to be areaStyle,  add a scatter point to future time, and set `animate: true` on the options.

### What is expected?
 I expect it will update area series data smoothly. like: https://app.expertoption.com/

### What is actually happening?
however, its updateAnimate is not work. only push data on the chart without animation.

**Comment by pissang** [comment]
Hi, you can have smooth seamless animation by setting animation to `1000ms` duration and `linear` easing. Here is an example
https://jsfiddle.net/w17vLaqt/

**Comment by JasonXDDD** [comment]
it still look like step by step animation when data update, but ExpertOption look so smooth :( 
see: https://imgur.com/a/WMFliW2

I think it need an animation from left ( original x,y ) to right ( new x,y )?

**Comment by plainheart** [comment]
This probably is just due to the settings for `animation`.
To specify a better value for update `animation` can make the chart more smooth.
For example,
Set [`animationEasingUpdate`](https://echarts.apache.org/en/option.html#animationEasingUpdate) to `linear` and set a proper value for [`animationDurationUpdate`](https://echarts.apache.org/en/option.html#animationDurationUpdate).

**Comment by JasonXDDD** [comment]
Hi, @plainheart 
I added it, but the same. https://jsfiddle.net/x4wj8nov/

With see carefully, when the 1st series (line chart) before 2nd series ( scatter point ), line chart cannot update data with smoothly animation.
but it is work for data after 2nd series.

see: https://jsfiddle.net/x4wj8nov/

**Comment by newbeenew** [comment]
Same problem at 5.0.1
