### ISSUE TITLE
Multiple versions of echarts in one document

### ISSUE THREAD

**Issue by jarben** [apache/echarts#13695]
### What problem does this feature solve?
I should be able to run echarts version 4 together with echarts version 5 so that upgrading to the new version is easier 

### What does the proposed API look like?
var echarts4 = require('echarts');
var echarts5 = require('echarts5');

// anything in the echarts5 shouldn't be global

**Comment by pissang** [comment]
Hi jarben.

I think it's a problem with multiple npm version management. I found we can dot it after npm 6.9.0
```js
npm install echarts@npm:echarts@4
npm install echarts5@npm:echarts@5
```

Then you can include two versions like your proposal API.

**Comment by jarben** [comment]
Hi @pissang, that's cool, didn't know this is possible via npm, thanks for sharing:) Will give it a try, can't wait for the 5 final, awesome work as usually!

**Comment by pissang** [comment]
Thanks!

**Comment by anguof** [comment]
> Hi jarben.
> 
> I think it's a problem about multiple npm version management. I found we can dot it after npm 6.9.0
> 
> ```js
> npm install echarts@npm:echarts@4
> npm install echarts5@npm:echarts@5
> ```
> 
> Then you can import two versions like your proposal API.
> 
> Check https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm

**Comment by anguof** [comment]
> Hi jarben.
> 
> I think it's a problem about multiple npm version management. I found we can dot it after npm 6.9.0
> 
> ```js
> npm install echarts@npm:echarts@4
> npm install echarts5@npm:echarts@5
> ```
> 
> Then you can import two versions like your proposal API.
> 
> Check https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm

Hi, When i install two versions as you saw, there has errors, my npm version is 6.14.0.
![image](https://user-images.githubusercontent.com/34739658/103721689-3fc90b00-5009-11eb-88cb-5bef4ccce799.png)
