### ISSUE TITLE
雷达图中,tooltip的formatter回调中无法取到当前选中点的数据

### ISSUE THREAD

**Issue by mgsod** [apache/echarts#13694]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=radar](https://echarts.apache.org/examples/zh/editor.html?c=radar)

### Steps to reproduce
tooltip中给formatter添加回调函数,打印参数

### What is expected?
鼠标悬停到雷达图中的数据点时,可以在formatter回调参数中获取到这个点的相关信息.
例如当前数据点的索引.

### What is actually happening?
formatter参数中返回的是整个series的数据 无法确定当前选中的是哪个点

在配置项手册中有提到一个`dimensionIndex`属性

如下图:

![radar1](https://user-images.githubusercontent.com/18007892/100201392-f762fb80-2f3a-11eb-9449-88bca246cf49.png)

但在实际打印`params`时却没有该属性,且也没有任何可以表示当前鼠标悬停的数据点的信息

![radar](https://user-images.githubusercontent.com/18007892/100201428-02b62700-2f3b-11eb-8e20-59caa4e1e656.png)

![radar2](https://user-images.githubusercontent.com/18007892/100202038-bae3cf80-2f3b-11eb-837e-6ed877fa396e.png)

**Comment by susiwen8** [comment]
Same issue with https://github.com/apache/incubator-echarts/issues/10750
