### ISSUE TITLE
two column legend

### ISSUE THREAD

**Issue by d-kishore** [apache/echarts#13696]
### What problem does this feature solve?
we want to set the legend in two column fashion, how can we achieve this  with legend options  also we want to add a title wit ellipsis for legend text 

### What does the proposed API look like?
legend:{
orient: 'horizontal',
itemsPerrow:2
html:true,
title:<some HTML>
}

**Comment by pissang** [comment]
You can try using two legend components which are put in two columns

**Comment by d-kishore** [comment]
Thanks for this info
can you please help with any sample/jsfiddle example
