### ISSUE TITLE
地图中的城市圆点

### ISSUE THREAD

**Issue by wenxuehai** [apache/echarts#13704]
### Version
5.0.0

### Steps to reproduce
地图中，添加legend属性显示城市圆点（不是通过添加散点图的方式），如果是在map series中使用内部自动生成的geo组件，则城市圆点能正常显示。但如果使用自定义的geo组件，也就是在series中引入了geoIndex，此时城市圆点显示不了了，这是为什么

### What is expected?
在series中使用geoindex引用自定义的geo组件时也能正常显示城市圆点

### What is actually happening?
在series中使用geoindex引用自定义的geo组件时城市圆点不见了

**Comment by wenxuehai** [comment]
[代码示例请查看：](https://codepen.io/wenxuehai/pen/PoGweEp)
如代码所示，如果我将第124行的代码（geoIndex: 0）给放开，那么地图的省份的圆点将不显示，非常奇怪。期望能得到回复，目前急用，谢谢！

**Comment by wenxuehai** [comment]
代码链接：https://codepen.io/wenxuehai/pen/PoGweEp

**Comment by Ovilia** [comment]
请参考这个文档：https://echarts.apache.org/zh/option.html#series-map.geoIndex
> 当设定了 geoIndex 后，series-map.map 属性，以及 series-map.itemStyle 等样式配置不再起作用，而是采用 geo 中的相应属性。

**Comment by wenxuehai** [comment]
> 请参考这个文档：[https](https://echarts.apache.org/zh/option.html#series-map.geoIndex) : [//echarts.apache.org/zh/option.html#series-map.geoIndex](https://echarts.apache.org/zh/option.html#series-map.geoIndex)
> 
> > 当设定了geoIndex后，series-map.map属性，以及series-map.itemStyle等样式配置不再起作用，而是采用geo中的相应属性。

这个我清楚，但我想问的是如果我使用了geoIndex属性后，我要怎么样才能让地图的圆点重新展示出来呢？就算在geo里面设置itemstyle等一系列属性也不起作用。难道当使用geoIndex时，地图圆点就不能显示出来了吗。

因为我需要使用geo的regions属性来对地图中的一些区域进行特殊设置，所以需要使用geoIndex属性，但目前使用了geoIndex后，地图圆点就不显示了，不管怎么在geo里面设置都不行，这个就是我的困惑。

**Comment by Ovilia** [comment]
参考 https://www.makeapie.com/editor.html?c=xBkVnciA0b
