### ISSUE TITLE
在制作流向图时如何通过连线的粗细（或者宽度）代表流量大小

### ISSUE THREAD

**Issue by GalaxyTrain** [apache/echarts#13702]
### Version
5.0.0

### Steps to reproduce
无

### What is expected?
类似于百度迁徙地图，但是线条宽度可以代表流量大小

### What is actually happening?
貌似还不能实现

**Comment by Ovilia** [comment]
Hi, you can set [line width](https://echarts.apache.org/zh/option.html#series-graph.links.lineStyle.width) of each link to make this.
