### ISSUE TITLE
chart.setOption(option, notMerge, lazyUpdate);设置notMerge=true,lazyUpdate=true,数据会实时更新但是dataZoom也会被重置

### ISSUE THREAD

**Issue by xyjxyjxyj** [apache/echarts#13719]
### Version
4.9.0

### Steps to reproduce
设置dataZoom然后放大，当数据刷新时，dataZoom也会回到原点，不在处于放大状态

### What is expected?
数据刷新时，dataZoom能保持当前状态

### What is actually happening?
数据刷新时，dataZoom回到初始化状态

**Comment by xyjxyjxyj** [comment]
目前是通过监听dataZoom获取当前的startValue 和endValue，在数据更新时设置给dataZomm.startValue 和 endValue

**Comment by Ovilia** [comment]
这个是有意设定的，notMerge true 的时候表示完全重置，所以状态不会保留；而 false 的时候 dataZoom 的状态会报备。请问为什么要使用 notMerge setOption 呢？

**Comment by Ovilia** [comment]
另外可以参考 https://github.com/apache/incubator-echarts/pull/12987 是否有帮助，5.0 的 rc 版本。

**Comment by wangminli** [comment]
> 
> 
> 这个是有意设定的，notMerge true 的时候表示完全重置，所以状态不会保留；而 false 的时候 dataZoom 的状态会保留。请问为什么要使用 notMerge setOption 呢？

发现treemap矩形树图是不是不支持datazoom事件呢？ 试了若干次都没有响应。

**Comment by pissang** [comment]
treemap 不支持 dataZoom
