### ISSUE TITLE
同时设置y轴的min和toolbox中的dataZoom的bug

### ISSUE THREAD

**Issue by myth984** [apache/echarts#13711]
### Version
4.8.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xxJxOCOJdg&v=1](https://www.makeapie.com/editor.html?c=xxJxOCOJdg&v=1)

### Steps to reproduce
同时设置y轴的min和toolbox中的dataZoom

series中有一个数据没有在 y轴的范围内 会导致数据不连续的问题

请看我的分享链接 

两秒后重新设置options

显示的效果完全不同

### What is expected?
希望不在y轴范围的点也可以连续显示

例如我的例子中两秒后的显示

### What is actually happening?
thanks again

**Comment by susiwen8** [comment]
Seems like `toolbox` affect it.

**Comment by myth984** [comment]
@susiwen8 是的 toolbox的配置项会影响他的显示

**Comment by myth984** [comment]
Is there a solution?
