### ISSUE TITLE
Support cursor option in brush

### ISSUE THREAD

**Issue by peder1001** [apache/echarts#13712]
### What problem does this feature solve?
I would like to use the brush to select an area of the chart. 
I would not like the cursor when using the brush to be a crosshair, I would rather it be a regular pointer. 

Therefore I suggest adding a cursor option to the brush object so that the developer can set the brush cursor themselves.

https://echarts.apache.org/en/option.html#brush

### What does the proposed API look like?
brush: 
{
      xAxisIndex: 'all',
      brushLink: 'all',
      cursor: 'pointer',   // new option
      brushType: 'lineX',
      brushMode: 'single',
      transformable: false,
      removeOnClick: true,
      cursor: 'wait',
      brushStyle: {
        borderWidth: 0,
        color: 'rgba(255,255,255,0.01)',
      },
      outOfBrush: {
        colorAlpha: 0.4,
        color: '#153A59'
      }
  }

**Comment by wadrn** [comment]
I have the same issue, the brush hot zone is conflict with the click zone, i  want to show pointer when the point is hovered, but it shows the cross cause in the brush hot zone, i think it should have a param choice to set the priority.

**Comment by gsi7** [comment]
Hey guys, I'm looking into this issue.
