### ISSUE TITLE
series.type: 'lines' 且配置了 effect 动画的都不能正常被 clear() 清除掉

### ISSUE THREAD

**Issue by dev-Hanjing** [apache/echarts#13725]
### Version
5.0.0

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-effect
此示例中的 effect 在调用 myChart.clear() 时，并不能清除掉已经画上去的线。而且只要是用到了 series.type: 'lines' 且配置了 effect 动画的都不能正常被 clear() 清除掉，这样导致当查询条件改变之后，不能重新再根据新的数据来重新绘制相应的结果。

### What is expected?
能让绘制结果被正常清除，然后重新绘制

### What is actually happening?
调用 clear() 无法清除已经绘制的结果

---
示例中的代码就能重现

**Comment by chj-damon** [comment]
这个bug好像2019年的时候就有人提过了，到现在都还没有修掉啊

**Comment by chj-damon** [comment]
https://github.com/apache/echarts/issues/8225
