### ISSUE TITLE
当visualMap的type为piecewise 时如何去除图标的点击事件

### ISSUE THREAD

**Issue by itsxt** [apache/echarts#13723]
### Version
4.2.1

### Steps to reproduce
设置visualMap type为piecewise时，取消图标的点击与地图联动效果

### What is expected?
去除图标的点击联动

### What is actually happening?
设置selectModal: false 时，事件依旧存在

**Comment by Ovilia** [comment]
检查下是不是拼写错误？应该是 [selectedMode](https://echarts.apache.org/zh/option.html#legend.selectedMode)

**Comment by itsxt** [comment]
> 检查下是不是拼写错误？应该是 [selIsectedMode](https://echarts.apache.org/zh/option.html#legend.selectedMode)

不是，此处的拼写错误是我提交Issues时的错误，程序内是正确的

**Comment by Stoneleee** [comment]
同问，如何取消visualmap的交互，selectedMode是legend有效
