### ISSUE TITLE
如何同时加载多个地图图层

### ISSUE THREAD

**Issue by GalaxyTrain** [apache/echarts#13728]
### Version
4.9.0

### Steps to reproduce
请问在加载中国地图后，如果要加载铁路线路地图数据怎么操作？是需要提前合并到一个GEOJSON文件中吗

### What is expected?
可以灵活添加地图图层，类似arcgis那样

### What is actually happening?
暂时还不能

**Comment by Ovilia** [comment]
建议使用第三方地图的相关功能，而不是使用 SVG 的地图。具体如何实现请查阅百度地图、arcgis 等第三方地图以及其 ECharts 扩展的文档。

**Comment by QiFeiLXH** [comment]
how to import map ,for example,china map;After upgrading version to 5.0,i can't import map as i ever did

**Comment by plainheart** [comment]
@QiFeiLXH  It's still available to download the maps from previous versions of ECharts, then copy to your projects and import them by

```js
import * as echarts from 'echarts'
import 'assets/map/china.js' // The file path of the downloaded map
```

**Comment by QiFeiLXH** [comment]
well,as you said,i need to revert my Echarts to a older version and download it,then i can use those assets files




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午5:45
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"林旭辉"<1005488340@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] 如何同时加载多个地图图层 (#13728)





 
@QiFeiLXH  It's still available to download the maps from previous versions of ECharts, then copy to your projects and import them by
 import * as echarts from 'echarts' import 'assets/map/china.js' // The file path of the downloaded map

**Comment by plainheart** [comment]
@QiFeiLXH No need to use an old version of ECharts. I meant you could only download the map data from the previous ECharts and put them into your project.

**Comment by QiFeiLXH** [comment]
i see,thanks
