### ISSUE TITLE
better title for Sunburst charts

### ISSUE THREAD

**Issue by spyshow** [apache/echarts#13736]
### What problem does this feature solve?
the titles for the Sunburst chart will be more readable and functional also will help displaying them for small values 
so if we can implement the title of the child data as in the Pie chart  like this picture https://ibb.co/BVV2D62

### What does the proposed API look like?
implement the same code from pie chart to sunbrust chart

**Comment by Ovilia** [comment]
You can format the labels with [label.formatter](https://echarts.apache.org/zh/option.html#series-sunburst.label.formatter).
