### ISSUE TITLE
ECharts5.0支持SVG扩展地图了吗？看更新说明没看到有提到。

### ISSUE THREAD

**Issue by minren118** [apache/echarts#13738]
### Version
5.0.0

### Steps to reproduce
看了5.0的更新日志，没找到有SVG扩展地图的更新说明，之前的理程碑里说有这个功能追加的，具体有没有加上了？

### What is expected?
希望知道SVG扩展地图的进度

### What is actually happening?
看更新说明没找到相关说法

**Comment by 100pah** [comment]
这个功能已经实现了。但是还需要继续测试下才合适正式发布。所以，安排到了 5.1.0 。

**Comment by pissang** [comment]
https://github.com/apache/echarts/pull/14571
