### ISSUE TITLE
[Perf] Tutorial example renders slow

### ISSUE THREAD

**Issue by wenfangdu** [apache/echarts#13744]
### Version
5.0.0

### Reproduction link
[https://echarts.apache.org/next/examples/en/editor.html?c=doc-example/tutorial-styling-step5](https://echarts.apache.org/next/examples/en/editor.html?c=doc-example/tutorial-styling-step5)

### Steps to reproduce
It renders slow, especially when switching on Decal Pattern, FPS dropped significantly.

### What is expected?
Renders fast.

### What is actually happening?
Renders slow.

**Comment by pissang** [comment]
Perhaps it's because this example is using a very large shadow. You can optimize it by using a smaller shadow.

**Comment by wenfangdu** [comment]
@pissang I've set `shadowBlur` to 1, works fines in default mode, still kinda laggy in decal pattern.
