### ISSUE TITLE
[echarts-gl] Undisposed zrender instance

### ISSUE THREAD

**Issue by aoiste** [apache/echarts#13743]
### Version
5.0.0

### Steps to reproduce
in [`echarts-gl\src\util\ZRTextureAtlasSurface.js(193)`](https://github.com/ecomfe/echarts-gl/blob/7cc547c903ac0f091b5736c19c15561bd0f21090/src/util/ZRTextureAtlasSurface.js#L193)

This line will create a zrender instance but cannot be disposed

### What is expected?
zrender instance should be disposed

### What is actually happening?
zrender instance cannot be disposed

**Comment by Ovilia** [comment]
The zr instance can be accessed with `chart.getZr()`.

**Comment by ztytotoro** [comment]
Sorry, I read the code, `chart.getZr()` will return the zr instance create by  [here](https://github.com/apache/incubator-echarts/blob/88bf43cb849e13cc6ee8d6ffd6811efdb3dc09a7/src/echarts.ts#L397)

but [echarts-gl\src\util\ZRTextureAtlasSurface.js(193)](https://github.com/ecomfe/echarts-gl/blob/7cc547c903ac0f091b5736c19c15561bd0f21090/src/util/ZRTextureAtlasSurface.js#L193) will call `zrender.init` to create a new zr instance

so when I call `chart.dispose()`, only `chart._zr` wiil be disposed.

e.g. the bar3D will [create a labelsBuilder](https://github.com/ecomfe/echarts-gl/blob/7cc547c903ac0f091b5736c19c15561bd0f21090/src/chart/bar3D/Bar3DView.js#L22), and the labelsBuilder create a [ZRTextureAtlasSurface](https://github.com/ecomfe/echarts-gl/blob/7cc547c903ac0f091b5736c19c15561bd0f21090/src/component/common/LabelsBuilder.js#L13), the ZRTextureAtlasSurface create a zr instance, however, when chart is disposed, Bar3DView will not dispose labelsBuilder

I didn't read all the code, maybe I missed something, but I did solved my problem when I added the missing dispose methods
