### ISSUE TITLE
Change style of legend item when it is unselected

### ISSUE THREAD

**Issue by JBLGLN** [apache/echarts#13752]
![Bildschirmfoto von 2020-12-04 08-26-10](https://user-images.githubusercontent.com/71066533/101135179-be4a1b80-360b-11eb-8f39-a4a7a315a8b8.png)
### What problem does this feature solve?
Hi,

trying to change the style of a legend item when it is unselected. Actually when i unselect a legend item, not everything is grey colored. As you can see on the picture there is still a blue line in the unselected legend item.

I modified the legend with the formatter function and used textStyle.rich. Is there a function/event with that the style of the legend items can be changed dynamically? 

Can you help me out to fix the problem, so that there is also a grey line instead of blue line when the legend item is unselected.

Thanks in advance for your help.
br

### What does the proposed API look like?
...

**Comment by JBLGLN** [comment]
I modified the legend with the formatter function and used textStyle.rich. Is there a function/event with that the style of the legend item can be changed dynamically?

**Comment by Ovilia** [comment]
`setOption` and update the legend style.

**Comment by JBLGLN** [comment]
Thank you for your answer. But when I update the whole legend style then the all legend items are changed. Is there a way to change only one item if it is not active. Is there something possible like:   'itemIsActive? colorAcitve : colorDisabled' ?

**Comment by JBLGLN** [comment]
The Legend is formatted with .legend.formatter and the textstyle is set with .legend.textStyle.rich
