### ISSUE TITLE
Connect Function does not work properly with Toolbox Options

### ISSUE THREAD

**Issue by JinyJose** [apache/echarts#13785]
### Version
5.0.0

### Reproduction link
[https://codepen.io/jinyjs/pen/ZEWRRBQ](https://codepen.io/jinyjs/pen/ZEWRRBQ)

### Steps to reproduce
Click on the 'Bar' Option in 'chart1', the data of 'chart1' is being displayed in 'chart2' as well.
Also vice -versa

### What is expected?
The data in the charts should not be transferred when using the toolbox Option in combination with connect Function.

### What is actually happening?
Data from one chart is being displayed in the other charts.

**Comment by 100pah** [comment]
At present, this effect is by design.
If intending to achieve the expected effect, needs to make connection manually. 
That is, listen to each event from chart1 and `dispatchAction` to chart2.

**Comment by JinyJose** [comment]
Hallo,

thank you for the information. Is there any help example that I can refer to in order to understand how to use the dispatchAction function.
