### ISSUE TITLE
力导向布局图形加载时，绑定的加载完毕事件rendered 和 finished 两个事件效果一样，请问是我的使用有什么问题吗

### ISSUE THREAD

**Issue by WantK** [apache/echarts#13807]
### Version
4.1.0-release

### Steps to reproduce
力导向布局图形加载时，每一帧变化打印rendered，图形全部渲染结束时打印finished
[使用到的事件](https://wantk.gitee.io/images/echarts%20%E5%8A%9B%E5%AF%BC%E5%90%91%E5%B8%83%E5%B1%80%E4%BA%8B%E4%BB%B6.PNG)
[使用方法](https://wantk.gitee.io/images/echarts%20%E5%8A%9B%E5%AF%BC%E5%90%91%E5%B8%83%E5%B1%80%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A.PNG)
[实际效果](https://wantk.gitee.io/images/echarts%20%E5%8A%9B%E5%AF%BC%E5%90%91%E5%B8%83%E5%B1%80%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A%E8%BF%90%E8%A1%8C%E6%95%88%E6%9E%9C.PNG)
### What is expected?
力导向布局图形加载时，每一帧变化打印rendered，图形全部渲染结束时打印finished

### What is actually happening?
每一帧变化都打印 rendered和finished

**Comment by wf123537200** [comment]
看起来 和 zrender 里面的触发机制有关系，mark + 1

**Comment by WantK** [comment]
> 看起来 和 zrender 里面的触发机制有关系，mark + 1


> 看起来 和 zrender 里面的触发机制有关系，mark + 1

可能是吧，不知道官方有没有解决这个问题

**Comment by pissang** [comment]
现在因为上层没有去管力引导的布局，所以渲染完就算结束了，但是实际上布局会异步进行，这一块是需要优化一下
