### ISSUE TITLE
Support BigInt

### ISSUE THREAD

**Issue by andyboyne** [apache/echarts#13819]
### Version
4.8.0

### Steps to reproduce
Create a line chart that plots Y values that are of type BigInt. 

### What is expected?
Values are plotted as defined by the data.

### What is actually happening?
Errors are being thrown about converting BigInt to number.

---
There are multiple problems here:
  * use of Math apis directly (these don't work with BigInt)
  * use of isFinite (doesn't work with BigInt).

**Comment by pissang** [comment]
I think it's hard to support BigInt currently since we can do any operation between BigInt and Number.  And we need to do lots of calculation inside.
