### ISSUE TITLE
markline设置Yaxis值时丢失精度

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#13812]
### Version
4.8.0

### Reproduction link
[http://jsfiddle.net/gcavLpnb/3/](http://jsfiddle.net/gcavLpnb/3/)

### Steps to reproduce
直接看 设置了一个markline 值是
            "yAxis": 0.8940678671439432
但是实际渲染的时候渲染出了0.98丢失了精度

### What is expected?
正常渲染 不丢失精度

### What is actually happening?
丢失精度

**Comment by xiaoqingb** [comment]
![image](https://user-images.githubusercontent.com/49091613/123063474-04e45380-d440-11eb-987c-84f5d5267f78.png)
今天刚遇到的，你设置一下这个应该就可以了～
