### ISSUE TITLE
Theme-Builder适配Echarts V5

### ISSUE THREAD

**Issue by yingzk** [apache/echarts#13827]
### What problem does this feature solve?
现有的[Theme-Builder](https://echarts.apache.org/zh/theme-builder.html)不完美适配Echarts V5，能否进行适配或者指引如何将4.x版本的主题文件进行升级

### What does the proposed API look like?
Theme-Builder Transfer

**Comment by pissang** [comment]
@yingzk 后续会对主题编辑器进行升级

**Comment by radiorz** [comment]
请问一下5.0的主题支持哪一些属性,在哪里查看？和4.x 版本差别大么 @pissang 
所有的options 选项都能放入theme 主题么，如何更好地设置theme主题？（https://echarts.apache.org/en/option.html#series-gauge）
我在设置主题的时候有些元素不响应，故有此问。
May I ask which attributes（in options，series） are supported in the theme by  v5.0? Where can I see them? Is it big different from the 4.x version @pissang
Can all options be put into the theme file? How to set the theme quick and better? (Https://echarts.apache.org/en/option.html#series-gauge)
When I set a new theme, some elements do not respond, so I have this question.

**Comment by pissang** [comment]
@radiorz 差得不大，主题的配置结构基本上可以参考配置项文档。可以参考我们的深色主题

https://github.com/apache/echarts/blob/master/src/theme/dark.ts

**Comment by chj-damon** [comment]
> @yingzk 后续会对主题编辑器进行升级

请问新版的主题编辑器什么时候出啊？
