### ISSUE TITLE
echart的关系图有500个节点500条边在IE11上显示很卡，是什么原因？有解决的办法吗？

### ISSUE THREAD

**Issue by huangshengping2017** [apache/echarts#13837]
### Version
4.9.0

### Steps to reproduce
echart的关系图有500个节点500条边在IE11上显示很卡，但是在其他浏览器上不卡，是什么原因？有解决的办法吗？

### What is expected?
IE11上显示不卡

### What is actually happening?
IE11上显示很卡

**Comment by pissang** [comment]
这个应该是 IE11 渲染效率的问题，暂时没有办法
