### ISSUE TITLE
Cannot import echarts5 in vue env created by vue-cli

### ISSUE THREAD

**Issue by Blinue** [apache/echarts#13831]
### Version
5.0.0

### Reproduction link
[https://codesandbox.io/s/awesome-mcnulty-cm0pl?file=/src/main.js](https://codesandbox.io/s/awesome-mcnulty-cm0pl?file=/src/main.js)

### Steps to reproduce
1. Create a vue project using vue-cli
2. Add echarts5 as dependency
3. Add "import echarts from 'echarts'; console.log(echarts);" in main.js

### What is expected?
"Object"

### What is actually happening?
"undefined"

**Comment by pissang** [comment]
Use `import * as echarts from 'echarts'` instead

**Comment by Blinue** [comment]
> Use `import * as echarts from 'echarts'` instead

Thank you. Has this breaking change mentioned in your docs?

**Comment by LuvTian** [comment]
How to import charts and components on demand in vue project env
