### ISSUE TITLE
I want label attributes to support multi-line text landscape

### ISSUE THREAD

**Issue by daoke0818** [apache/echarts#13845]
### What problem does this feature solve?
When using a tree chart for a family tree, I want the label to display two lines vertically, one for the name and one for the rank.

### What does the proposed API look like?
That corresponds to CSS rules：
writing-mode:horizontal-tb;
writing-mode:vertical-rl;  
writing-mode:vertical-lr;

**Comment by plainheart** [comment]
This feature looks beneficial. Perhaps, SVG renderer can do it through the `writing-mode` property in CSS. But now ECharts doesn't provide this option yet or the ability to specify the class name to enable the developer to control the style of charts by CSS.
