### ISSUE TITLE
多折线图缓存和数据合并问题

### ISSUE THREAD

**Issue by roddy1511** [apache/echarts#13857]
[###](url

https://user-images.githubusercontent.com/74649075/102760109-001ae600-43b0-11eb-904a-1489981d7588.mp4

) Version
4.9.0

### Steps to reproduce
1. 使用多条折线的图表（更容易出现），2 . 使用异步加载数据，3，在数据达到一定量后，我会取出option里面的数据，对里面的数据进行合并，（两秒或者几分钟内的数据合并，替代为新的点），4，第三步操作之后合并的点似乎会和option里面的缓存数据冲突，导致绘图错乱，有几个上一次setOption的点会有残留。5.如果鼠标拖动datazoom拖动条则可以触发图表更新到正常图表，或者使用clear清楚缓存也能正常显示，但是就没有从右边往左边那推进的渐进动画效果。

### What is expected?
期望能出一个自动合并某个时间区域的数据的功能，让数据能自动合并重新取点，并且还能保留渐进效果。

### What is actually happening?
绘图会错乱。

**Comment by Ovilia** [comment]
如果要替换数据的话，setOption 的第二个参数要传入 `true`。
另外，你可能并不需要自己处理合并数据的事，ECharts 自动会对太过密集的数据进行合并处理，ECharts 5 新增支持了 [sampling](https://echarts.apache.org/next/zh/option.html#series-line.sampling) `'lttb'` 的取值，可以保留原数据的特性。

**Comment by Ovilia** [comment]
如果仍然认为有 bug 的话，请提供一个可复现的在线例子。

**Comment by roddy1511** [comment]
https://www.makeapie.com/editor.html?c=xw3kqNC_WR&v=1 ，该问题具有必然性，但是他需要在运行几分钟后才会开始出现。然后就一会好一会不好。跟我视频里面提供的一样。

**Comment by roddy1511** [comment]
视频
请直接观看最后几秒

**Comment by roddy1511** [comment]
[百度视频反馈.zip](https://github.com/apache/incubator-echarts/files/5749977/default.zip)
setOption(option,true);，在我的项目里面似乎也不起作用。只能clear()，但是就变成每次都刷新，而没有动画的渐进效果了

**Comment by letItBe666** [comment]
就一直没有数据更新后，折线的过渡动画效果？折线都是瞬间出现的
