### ISSUE TITLE
柱状图堆叠，支持所有柱子高度一致，按照百分比堆叠数据吗？

### ISSUE THREAD

**Issue by OneAndOnly1111** [apache/echarts#13852]
### Version
4.6.0

### Steps to reproduce
想要实现这种柱状图堆叠效果：
1. 设置每根柱子的高度一致，
2. 按照数据的百分比进行堆叠

### What is expected?
想要实现这种柱状图堆叠效果：
1. 设置每根柱子的高度一致，
2. 按照数据的百分比进行堆叠

### What is actually happening?
查看了api 现在不支持，
只支持按照时序数据堆叠

**Comment by OneAndOnly1111** [comment]
![image](https://user-images.githubusercontent.com/18378998/102745598-54fe3280-4397-11eb-93d3-e0625c0f508d.png)

**Comment by ISBN9527** [comment]
我觉得这个可以自己设置yAxis的max值就可以满足你的需求。

**Comment by Ovilia** [comment]
可以自己处理下数据实现这样的效果
