### ISSUE TITLE
geo.label.formatter params return {name:'cityName',status:'normal'}

### ISSUE THREAD

**Issue by crushh** [apache/echarts#13861]
### Version
4.9.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xORmXghiRB&v=2](https://www.makeapie.com/editor.html?c=xORmXghiRB&v=2)

### Steps to reproduce
Open the console and view the parameters printed by the formatter  function

### What is expected?
The parameters are consistent with what the document says

### What is actually happening?
only return {name:'cityName',status:'normal'}

**Comment by susiwen8** [comment]
I look up the code https://github.com/apache/echarts/blob/master/src/coord/geo/GeoModel.ts#L264, Looks like {name:'cityName',status:'normal'} was by design. Maybe we should correct the doc?

**Comment by duriancashewTasty** [comment]
I also get same issue,how I do that?   I want     formatter:function(params){   }     params.data.value  and params.data.name

**Comment by HCenggel** [comment]
![image](https://user-images.githubusercontent.com/24600623/184059229-b498559f-0613-467e-83eb-f21c86baa7ea.png)
different from the document
backdata
{name: 'as1', status: 'normal'}
