### ISSUE TITLE
Sankey chart: Nodes are not connected with edges after dragging 

### ISSUE THREAD

**Issue by paulputter** [apache/echarts#13866]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=sankey-simple](https://echarts.apache.org/examples/en/editor.html?c=sankey-simple)

### Steps to reproduce
Change "series.data" array to "series.nodes" array.

### What is expected?
Nodes and edges are connected while dragging the nodes

### What is actually happening?
Dragging the nodes "disconnects" them from the edges 

---
Error is in the setNodePosition function. It looks for option.data and not additionally for option.nodes: 

```
setNodePosition: function (dataIndex, localPosition) {
    var dataItem = this.option.data[dataIndex];
    dataItem.localX = localPosition[0];
    dataItem.localY = localPosition[1];
  },
```

**Comment by paulputter** [comment]
Sure, will do.

**Comment by paulputter** [comment]
Here's my fix:

```
setNodePosition(dataIndex: number, localPosition: number[]) {
        if (this.option.data) {
            const dataItem = this.option.data[dataIndex];
            dataItem.localX = localPosition[0];
            dataItem.localY = localPosition[1];
        } 
        else if (this.option.nodes) {
            const dataItem = this.option.nodes[dataIndex];
            dataItem.localX = localPosition[0];
            dataItem.localY = localPosition[1];
        }
}
```

**Comment by pissang** [comment]
It has been fixed in https://github.com/apache/echarts/pull/15199/files
