### ISSUE TITLE
Add an reset api to reset the tree to initial status

### ISSUE THREAD

**Issue by kuige** [apache/echarts#13875]
### What problem does this feature solve?
The tree chart, with roaming enabled, after zoom and pan, it's difficult to restore to its initial status, if a restore api is provided, it will be convenient.

Yes, I can first get the option series, set the center to null and zoom to 1, and then call the setOption method, but this approach will not have the animation, the tree will restore to its initial status suddenly.

### What does the proposed API look like?
`chartInstance.restore()`

**Comment by plainheart** [comment]
Hi, I think we can currently use the [`dispatchAction` API with the type of `restore`](https://echarts.apache.org/next/en/api.html#action.toolbox.restore) to restore the chart. It's from the `toolbox` component.
```js
chart.dispatchAction({
    type: 'restore'
});
```

See here for the demo: https://www.makeapie.com/editor.html?c=xQHxllP7G8&v=1

**Comment by kuige** [comment]
I have tried the `dispatchAction` API, it works well, but it still didn't have any animation between the two status.

**Comment by plainheart** [comment]
As the demo I provided, I can see the animation.

https://user-images.githubusercontent.com/26999792/103186510-b8d6ad00-48fb-11eb-9af8-25b54c0d4880.mp4

**Comment by plainheart** [comment]
Do you mean there is no animation for roaming?

**Comment by kuige** [comment]
I mean after zooming and panning.

https://user-images.githubusercontent.com/8212800/103194252-0530e580-491a-11eb-8582-d8858a8d93ec.mov
