### ISSUE TITLE
seriesLayoutBy not working properly when 'row' is set

### ISSUE THREAD

**Issue by wilnerjs** [apache/echarts#13872]
### Version
5.0.0

### Reproduction link
[https://echarts.apache.org/next/examples/en/editor.html?c=dataset-simple0](https://echarts.apache.org/next/examples/en/editor.html?c=dataset-simple0)

### Steps to reproduce
1 - Open the link
2 - Add , seriesLayoutBy: 'row' on each series
2 - The legend will be  wrong on the chart. Right legend is the product name
3 - Change seriesLayoutBy to column, the legend dont change,, and now is right( year)

### What is expected?
Legend change when  seriesLayoutBy is changed

### What is actually happening?
legend not change

**Comment by FlameSky-S** [comment]
I also encountered this problem, it's new in version 5.0. Same code worked well in version 4.x.

**Comment by wilnerjs** [comment]
i guess this bug was fixed on 5.0.1

**Comment by pissang** [comment]
Sorry for the wrong milestone
