### ISSUE TITLE
Echarts official community Gallery https://www.makeapie.com/  is not accessible. What is the reason?When will it be fixed? 

### ISSUE THREAD

**Issue by yan0727** [apache/echarts#13888]
### Version
4.8.0

### Steps to reproduce
https://www.makeapie.com/  is not accessible

### What is expected?
https://www.makeapie.com/  accessible

### What is actually happening?
https://www.makeapie.com/  is not accessible

**Comment by plainheart** [comment]
I can access the gallery without issues. Would you mind providing more information for us, such as your city and ISP?

**Comment by pissang** [comment]
PS: it's not an official community under Apache ECharts project.

**Comment by maulikshah30** [comment]
Hello Team,

https://www.makeapie.com/is not accessible

when will be fixed?

i'm patient of echarts.

awaiting your response

Thank you

**Comment by SuperRay3** [comment]
I find a alternative website named PPChart maintained by a independent developer. It contains all previous data from makeapie site. [PPChart](http://ppchart.com)

**Comment by maulikshah30** [comment]
@SuperRay3 Thanks

**Comment by gitfei1231** [comment]
[makeapie.cn](url)
