### ISSUE TITLE
[Feature] add showText option to showLoading

### ISSUE THREAD

**Issue by wenfangdu** [apache/echarts#13893]
### What problem does this feature solve?
Most of the time, spinner alone is enough to signal the loading status, please consider adding a `showText` option to make that possible. Currently I can do `text: ''` for spinner only loading, but the tradeoff is it's not exactly centered.

### What does the proposed API look like?
`showText: Boolean`

**Comment by plainheart** [comment]
By default, the text is placed at the right of the loading box and has a distance of 10px. This is hard-coded.
I think it will be better to enable the developers to configure more parameters, just like `label`.
