### ISSUE TITLE
我选中的理由是K线图，但实现像股票软件中那样遇到问题了

### ISSUE THREAD

**Issue by applyWhatTheyLearn** [apache/echarts#139]
我k线图，成交量图，包括macd指标都画出来了，感觉确实挺好用，但现在碰到问题是怎样把这三个组合的一起，也就是用一个x轴，y轴分成上中下三部分。就根通达信软件中那样。请问有没有最好的方法实现。

**Comment by hardywu** [comment]
@applyWhatTheyLearn  能问下最后你是怎么解决的？

**Comment by hardywu** [comment]
@applyWhatTheyLearn 能问下最后你是怎么解决的？
