### ISSUE TITLE
请问那个版本的eachrts ，使用bMap 可以设置 地图3D视角

### ISSUE THREAD

**Issue by Cat-Wong** [apache/echarts#13907]
### Version
4.8.0

### Steps to reproduce
 let bMap = MyCharts.getModel().getComponent('bmap').getBMap();
bMap.setHeading(64.5);
bMap.setTilt(73);

### What is expected?
请问那个版本的eachrts ，使用bMap 可以设置 地图3D视角。
百度的api是 以下两个方法。
map.setHeading(64.5); //设置地图旋转角度
map.setTilt(73); //设置地图的倾斜角度

### What is actually happening?
Error in mounted hook: "TypeError: bMap.setHeading is not a function"

**Comment by plainheart** [comment]
3D百度地图应该需要百度地图 GL 版本支持，请引入 GL 库试试。https://lbsyun.baidu.com/index.php?title=jspopularGL
