### ISSUE TITLE
导出图片报错

### ISSUE THREAD

**Issue by lkq2016** [apache/echarts#13914]
### Version
5.0

### Steps to reproduce
1.https://echarts.apache.org/next/examples/zh/editor.html?c=bar-simple
2.echarts.getInstanceByDom(document.getElementById("chart-panel")).getDataURL({
    pixelRatio: 2,
    backgroundColor: '#fff'
});
3.Uncaught TypeError: Cannot read property 'dpr' of undefined
    at Hv (echarts.min.js:22)
    at Kv (echarts.min.js:22)
    at ox.getRenderedCanvas (echarts.min.js:22)
    at i_.getRenderedCanvas (echarts.min.js:22)
    at i_.getDataURL (echarts.min.js:22)
    at <anonymous>:1:66
Hv @ echarts.min.js:22
Kv @ echarts.min.js:22
ox.getRenderedCanvas @ echarts.min.js:22
i_.getRenderedCanvas @ echarts.min.js:22
i_.getDataURL @ echarts.min.js:22
(anonymous) @ VM928:1

### What is expected?
导出图片

### What is actually happening?
error

**Comment by plainheart** [comment]
能否麻烦提供一个更完整的可复现的在线例子？我使用你提供的例子未能复现该错误。
https://www.makeapie.com/editor.html

**Comment by zhouxin860114** [comment]
应该是修复了，但还没出新的小版本吧，可以参考着改一下：

参考：
https://github.com/ecomfe/zrender/tree/master/src/canvas
+------------+-------------------------------------------------------------------------+--------------+
| Painter.ts | fix(canvas/painter): ctx was mistakenly assigned with a null value. fix | 22 hours ago |
+------------+-------------------------------------------------------------------------+--------------+

修改内容：
https://github.com/ecomfe/zrender/commit/c1b1ce0fda3e81fc489152f7b8ea89210bdf6a41

**Comment by plainheart** [comment]
@zhouxin860114 这周预计会发一版 5.0.2 修复这个 bug。我将这个 issue 关闭了。

**Comment by KehaoWu** [comment]
啥时候发5.0.2
