### ISSUE TITLE
平行坐标系的tooltip 配置 不生效

### ISSUE THREAD

**Issue by toutouloveyou** [apache/echarts#13918]
### What problem does this feature solve?
https://echarts.apache.org/examples/zh/editor.html?c=doc-example/parallel-all
平行坐标系 数据展示

### What does the proposed API look like?
希望鼠标移动到坐标点上时，显示点的相关信息

**Comment by plainheart** [comment]
5.0 版本支持 tooltip。https://echarts.apache.org/next/examples/zh/editor.html?c=parallel-aqi
