### ISSUE TITLE
Android phones cannot save images using echarts' toolbox-saveAsImage/安卓手机用echarts自带的保存图片工具无法保存

### ISSUE THREAD

**Issue by daoke0818** [apache/echarts#13925]
### Version
4.9.0

### Steps to reproduce
option opens the save image in the toolboxe/图表选项中开启工具箱的保存图片：

toolbox:{
                left:0,
                top:'middle',
                feature: {
                    saveAsImage: {name:'李氏家谱'}
                }
 }, 

In a trial run, the built-in browser on Android phones doesn't save images properly, but it works perfectly on iphones and PCS
经尝试，安卓手机的自带浏览器无法正常保存图片，但是苹果手机和PC电脑上都完全正常。

### What is expected?
Pictures can also be saved normally on Android phones
安卓手机的自带浏览器能正常保存图片

### What is actually happening?
Images cannot be saved properly on Android phones
图片不能正常保存在Android手机上

---
Thanks to the hard working open source developers!
谢谢辛苦的开源开发者们！

**Comment by plainheart** [comment]
是什么品牌的安卓手机？浏览器内核以及版本是什么？

**Comment by gaogaoinvincible** [comment]
Still has problem
