### ISSUE TITLE
resize的取消动画效果了吗？

### ISSUE THREAD

**Issue by dousee163** [apache/echarts#13923]
### Version
5.0.0

### Steps to reproduce
调用resize的时候，没有动画效果

看看以下例子，并调整浏览器窗口
https://echarts.apache.org/next/examples/zh/editor.html?c=bar-y-category

以下是旧版有动画效果
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple

### What is expected?
希望resize的动画效果可以控制，比如option.animation=true

### What is actually happening?
暂时找不到类似的属性控制动画效果

**Comment by pissang** [comment]
@dousee163 动画效果会让画面的响应显得不那么及时，有时候会有卡顿的效果

**Comment by Echartswest** [comment]
Hi, the same issue for the 5.0 version, the chart animation is not available when run "myChart.resize()" and the user view is not good as the previous versions. Is there solution to get the animation back.

		document.getElementById('main').style.height = '1400px';
		myChart.resize();// there was animation in older versions.

**Comment by jonavila** [comment]
I also miss the animation of v4 when resizing. I would debounce the resize function and that looked good. Hopefully, it can be brought back in v5

**Comment by Echartswest** [comment]
Hello，

The resize animation works with resize config in V5.1.
However in V5.1, when I use the graphic in group, the children in type 'text' in the group is still not animated, it will appear immediately with resizing and before the animation. Can we make the whole group to be animated and synchronized when resize? Thanks!

An example with https://echarts.apache.org/examples/zh/editor.html?c=custom-calendar-icon
By adding a toolbox into the option to test:
    toolbox: {
		show : true,
        feature: {
			myTool: {                
				show : true,                
				title : 'Resize', 				
				icon : 'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444zM421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876zM421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
                
				onclick : function (){   
					//ResizeChart; 
					if (size == '600px'){
						size = '1000px';
					}
					else {
						size = '600px';
					}
					document.getElementById('main').style.height = size;
					myChart.resize({
						animation: {
						duration: 300,
						easing: 'cubicInOut'
					  }
					});				
				}
			},
        }
    },
