### ISSUE TITLE
The flicker occurs when the value of value is 0 in pie chart or ring chart data

### ISSUE THREAD

**Issue by MainPri** [apache/echarts#13942]
### Version
5.0.0

### Reproduction link
[https://echarts.apache.org/next/examples/zh/editor.html?c=pie-simple](https://echarts.apache.org/next/examples/zh/editor.html?c=pie-simple)

### Steps to reproduce
1.Modify the value in the Data collection under 'series' to be 0
2.click run
3.pie chart is flicker

### What is expected?
When the value is 0, the pie chart does not flicker

### What is actually happening?
The flicker occurs when the value of value is 0 in pie chart or ring chart data

**Comment by yufeng04** [comment]
I tried to reproduce, but the pie chart didn't flicker. Could you provide more specific conditions for reproduction？

**Comment by MainPri** [comment]
> I tried to reproduce, but the pie chart didn't flicker. Could you provide more specific conditions for reproduction？

1.pls watch The official example (https://echarts.apache.org/next/examples/zh/editor.html?c=pie-simple)
2.Replace the following code
`series: [
        {
            name: '访问来源',
            type: 'pie',
            radius: '50%',
            data: [
                {value: 300, name: '搜索引擎'},
                {value: 0, name: '直接访问'},
                {value: 0, name: '邮件营销'},
                {value: 0, name: '联盟广告'},
                {value: 0, name: '视频广告'}
            ],
            emphasis: {
                itemStyle: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]`
