### ISSUE TITLE
Several textual errors in zh/changelog.html

### ISSUE THREAD

**Issue by ranzj** [apache/echarts#13952]
### Version
5.0.0

### Steps to reproduce
Visit https://echarts.apache.org/zh/changelog.html 
Navigate to v5.0.0  其他功能、改进和问题修复。 

### What is expected?
Correct the mistakes

### What is actually happening?
（1）[Feature] 当线处于 emphasis 状态时，加租（勘误：【粗】）。参见 #13013。
（2）[Feature] 桑吉（勘误：【基】，应与其他表述保持一致）图 ……

**Comment by plainheart** [comment]
第一个问题，我已经在 https://github.com/apache/incubator-echarts-doc/commit/90e2608fc7127b8cc2b167cfafa4bef6e7a03680 中修复，应该会在后续更新时上线。
第二个问题，不介意的话可以提个 PR 到 https://github.com/apache/incubator-echarts-doc
