### ISSUE TITLE
引力导图中设置的roam：true,开启鼠标平移，怎么监听这个平移事件

### ISSUE THREAD

**Issue by huangshengping2017** [apache/echarts#13959]
### Version
4.9.0

### Steps to reproduce
引力导图中设置的roam：true,开启鼠标平移，怎么监听这个平移事件，因为要在这个平移结束之后进行一些操作。

### What is expected?
监听引力导图中的平移事件

### What is actually happening?
不知道怎么监听引力导图中的平移事件

**Comment by plainheart** [comment]
```js
chart.on('graphRoam', function (e) {
    // TODO
})
```
