### ISSUE TITLE
echarts结合百度地图使用，地图实例中经度为负的点无法添加至地图

### ISSUE THREAD

**Issue by DLFouge** [apache/echarts#13991]
### Version
5.0.0

### Steps to reproduce
      const point = new BMap.Point(-0.51, 9.24);
        const myIcon = new BMap.Icon("http://lbsyun.baidu.com/jsdemo/img/fox.gif", new BMap.Size(300, 157));
        const marker = new BMap.Marker(point, {
            icon: myIcon
        }); 
        map.addOverlay(marker); // 将标注添加到地图中

### What is expected?
marker显示在地图上

### What is actually happening?
marker无法显示在地图上

**Comment by plainheart** [comment]
能否给出更加完整的例子？我测试可以正常添加。

![image](https://user-images.githubusercontent.com/26999792/104003200-12cd5180-51dd-11eb-8dee-c51b0f5d19ca.png)

**Comment by DLFouge** [comment]
> 能否提供更加完善的例子？我测试可以正常添加。
> 
> ![图片](https://user-images.githubusercontent.com/26999792/104003200-12cd5180-51dd-11eb-8dee-c51b0f5d19ca.png)

var chart = echarts.inite(document.getElementById("demo"));
var option = {...}
chart.setOption(option);
var map = chart.getModel().getComponent('bmap').getBMap();
const point = new BMap.Point(-0.51, 9.24);
    const myIcon = new BMap.Icon("http://lbsyun.baidu.com/jsdemo/img/fox.gif", new BMap.Size(300, 157));
    const marker = new BMap.Marker(point, {
        icon: myIcon
    }); 
    map.addOverlay(marker);

**Comment by DLFouge** [comment]
> 能否提供更加完善的例子？我测试可以正常添加。
> 
> ![图片](https://user-images.githubusercontent.com/26999792/104003200-12cd5180-51dd-11eb-8dee-c51b0f5d19ca.png)

var chart = echarts.inite（document.getElementById（“ demo”））;
var option = {...}
chart.setOption(option);
var map = chart.getModel().getComponent('bmap').getBMap();
const point = new BMap.Point（-0.51，9.24）;
const myIcon = new BMap.Icon（“ http://lbsyun.baidu.com/jsdemo/img/fox.gif”，new BMap.Size（300，157））;
const marker = new BMap.Marker（point，{
icon：myIcon
}）;
map.addOverlay（marker）;

**Comment by plainheart** [comment]
未能复现：https://www.makeapie.com/editor.html?c=xXCp8e2-j5&v=1

**Comment by DLFouge** [comment]
> 未能复现：https://www.makeapie.com/editor.html?c=xXCp8e2-j5&v=1

传了一个完整demo到github，麻烦看看：https://github.com/DLFouge/mapDemo.git

**Comment by plainheart** [comment]
已复现。经验证，这应该是百度地图 API 3.0 的bug，即使用官方示例也无法正常添加经度为负值的 Marker。建议提个工单向百度地图方反馈。为了规避此问题，可先使用百度地图 API 2.0。
