### ISSUE TITLE
图的roam缩放功能拓展

### ISSUE THREAD

**Issue by IT-Highmore** [apache/echarts#14012]
### What problem does this feature solve?
因为目前的缩放仅仅是图标或者图形的缩放，添加的文字之类的并没有缩放，所以在缩放之后显得一团文字混乱 不是很美观，再看了文档和例子之后，并没有发现对文字的自适应。

### What does the proposed API look like?
添加文字的缩放自适应

**Comment by pissang** [comment]
5.0 里支持文本的自动隐藏，在缩放的时候可以应用。也可以通过 labelLayout 根据图形尺寸调整 fontSize

**Comment by lifront** [comment]
类似问题，5.0版本，设置labelLayout后，地图移动，label文字位置不动
