### ISSUE TITLE
dataZoom-slider.handleIcon  在使用base64的dataURI的时候页面会崩溃

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14014]
### Version
5.0.0

### Steps to reproduce
see as
5.0: https://codepen.io/facingcheer/pen/OJRBLJN
4.8: https://codepen.io/facingcheer/pen/MWjPgoX
当前的demo中 使用4.8.0版本的handleIcon可以正常渲染
5.0中如果激活handleIcon页面会崩溃

### What is expected?
5.0中handleIcon依然支持dataURI语法

### What is actually happening?
暂不支持

**Comment by bigbigqiang** [comment]
Version 5.0.1, set base64, the page is stuck, for example

handleIcon: 'image://data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAARCAYAAAA7bUf6AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyZpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDIxIDc5LjE1NTc3MiwgMjAxNC8wMS8xMy0xOTo0NDowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6QkJDQ0NFQTM1OTNCMTFFQjgxQjBFMTZCQ0YyNjJENDkiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6QkJDQ0NFQTI1OTNCMTFFQjgxQjBFMTZCQ0YyNjJENDkiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6NjM0MzZFMUY1NzExMTFFQkE4RDg5RTUxQzdEQzg2QTUiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6NjM0MzZFMjA1NzExMTFFQkE4RDg5RTUxQzdEQzg2QTUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7L6DIsAAAAVUlEQVR42mL4//8/AwwDwTQg/k8AT0PWA8KMUM1gwMjI+N/v8h8GfGCTLgtIIyOyGBMDFcCoIZiABV8sIAN8sYbTEEJRPThdMppOaGQIAzXKE4AAAwAtrVB7s+bCHwAAAABJRU5ErkJggg==',
