### ISSUE TITLE
When I hide 'legend', it still as a block element use space

### ISSUE THREAD

**Issue by JueLance** [apache/echarts#14011]
### Version
4.8.0

### Steps to reproduce
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>线路拥挤程度</title>
    <script src="https://cdn.bootcss.com/echarts/4.8.0/echarts.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
		* {
			margin: 0,
			padding: 0
		}
		
		body {
			font-family: SimSun;
			margin: 0,
			padding: 0
		}
		
		#main {
			margin: 0,
			padding: 0
		
		}
        
    </style>
</head>
<body>
<div id="main" style="width:360px;height:280px; border:1px solid #12aded;margin: 0; padding: 0;"></div>
</body>

<script type="text/javascript">
    let myChart =null;
    window.onload = function(){
	
		
		myChart = echarts.init(document.getElementById('main'), null, {renderer: 'canvas'});
		
		let option = {
			legend: {
			    /***
				
				English: I don't want display legend, so I just set 'show' field to 'false'. but it still use some space, although it was hidden.
				Chinese: 我不想显示legend元素，我就把"show"字段设置成false, 尽管它确实隐藏了，但是我发现它还是占用了空间。
				
				Expect:
					怎么样实现既隐藏掉，又可以不占用空间呢？
				
				**/
				show: true,
				selectedMode: 'single',
				data: ["线路拥挤程度"],
				backgroundColor:'#12aded',
				borderColor:'red',
				borderWidth: 2,
				height: 0,
				itemHeight: 0,
				padding: 0,
				left:'50%',
				bottom: 15
			},
			radar: {
				shape: 'polygon',// polygon or circle
				indicator: [
					{ name: '线路1', max: 100},
					{ name: '线路2', max: 100},
					{ name: '线路3', max: 100},
					{ name: '线路4', max: 100},
					{ name: '线路5', max: 100}
				]
			},
			series: [{
				name: '线路拥挤程度',
				type: 'radar',
				data: [
					{
						value: [50, 13, 70, 75, 90],
						name: '线路拥挤程度',
					}
				],

			}]
		};
		
		myChart.setOption(option);
	
	};

</script>
</html>
```
### What is expected?
English: How to make legend element don't use space when I set legend.show to 'false'
Chinese: 怎么样实现既隐藏掉legend，又可以不占用空间呢？

### What is actually happening?
legend was hidden, but it still use space, like there is a placeholder inside the canvas.

---
none

**Comment by JueLance** [comment]
I found my code was lost when I submit issue, see full version code, just visit: https://jsfiddle.net/f5rbn27a/

**Comment by pissang** [comment]
I'm not sure what you mean by blocking and use space. Legend won't affect the layout of other components.

**Comment by JueLance** [comment]
> I'm not sure what you mean by blocking and use space. Legend won't affect the layout of other components.

I mean when I hidden legend(set "show" to false), we can't see anything inside of legend , but the legend still has a blank space inside of canvas. For example: if the canvas contains series and legend. the series heigh is 300, the legend height is 200, so the cavans total height is 500. that's no problem. if I hidden the legend, I hope the canvas height should be 300(because now just series is showing), but actually, echart still use 500 to render the canvas.

**Comment by pissang** [comment]
As I said, the legend component won't affect the layout. The blank area is caused by the grid component `top` config. You can set it to a smaller value like `10`

**Comment by JueLance** [comment]
> As I said, the legend component won't affect the layout. The blank area is caused by the grid component `top` config. You can set it to a smaller value like `10`

I tried, it taks no effect, but thank you for your idea.

**Comment by JueLance** [comment]
Since I can use below fields move radar graph to keep it in center inside of canvas, I can solve my problems, I close my issue.

https://echarts.apache.org/zh/option.html#radar.center
https://echarts.apache.org/zh/option.html#radar.radius
