### ISSUE TITLE
Ecart chart doesn't render  In the online environmen

### ISSUE THREAD

**Issue by looprandom** [apache/echarts#14028]
In the online environment, the chart can be rendered for the first time, but after switching to other routes and returning to the previous page, the chart cannot be rendered. The console can see the canvas label, but the chart area is blank
![image](https://user-images.githubusercontent.com/49395194/104410756-ef6f2180-55a3-11eb-9487-21a2ccd577c8.png)

![image](https://user-images.githubusercontent.com/49395194/104410733-e67e5000-55a3-11eb-85da-665ddc7b3581.png)

**Comment by Enoooch** [comment]
@looprandom Hi, I can reproduce this issue in production mode.

Replace ```document.getElementById('chart')``` with ```pieChartRef.value```, or add ```v-if v-show``` to dom element can avoid this.

##### Versions
vue: v3.2.24 with ```<script setup>``` syntax
echarts: v5.2.1

Still trying to figure out why.
