### ISSUE TITLE
5.0版本 tooltip hide行为和以前不一致

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14021]
### Version
5.0.0

### Steps to reproduce
5.0: https://echarts.apache.org/next/examples/zh/editor.html?c=line-stack
4.x: https://echarts.apache.org/examples/zh/editor.html?c=line-stack

Echarts5.0的tooltip在中在鼠标快速离开图表时，（可以用鼠标迅速的从图表内滑出到代码区域）
可能会不触发hide 不能正常隐藏tooltip （同时series选中的加粗状态也保留了）
这一行为和之前的版本都不一样

### What is expected?
正常触发隐藏

### What is actually happening?
有概率（在高速离开时）不隐藏tooltip

**Comment by plainheart** [comment]
[5.0.1](https://github.com/apache/echarts/milestone/21) 应该修复了无法隐藏的问题（参见 #13958 和 ecomfe/zrender#693）
至于 state 被保留，应该跟 #13675 所述相关，会在 [5.1.0](https://github.com/apache/echarts/milestone/19) 修复。

**Comment by Charles953** [comment]
> [5.0.1](https://github.com/apache/echarts/milestone/21) 应该修复了无法隐藏的问题（参见 #13958 和 [ecomfe/zrender#693](https://github.com/ecomfe/zrender/pull/693)）
> 至于 state 被保留，应该跟 #13675 所述相关，会在 [5.1.0](https://github.com/apache/echarts/milestone/19) 修复。

npm找不到5.0.1的包

**Comment by plainheart** [comment]
@Charles953 目前 5.0.1 rc 版本还在投票，如果顺利通过，这周会正式发版。
