### ISSUE TITLE
Ecart chart doesn't render  in the online environmen

### ISSUE THREAD

**Issue by looprandom** [apache/echarts#14029]
### Version
5.0.0

### Steps to reproduce

In the vue3.0 project built by vue-cli, I wrote a component that contains the function of displaying charts.
code show as below:
```JavaScript
let seriesLabel = {
    normal: {
        show: true,
        textBorderColor: '#333',
        textBorderWidth: 2
    }
}
const option = {
    title: {
      text:'海统年综合海洋经济监测报表评估' ,
      left: 'center'
    },
    dataset: {
        source: [
            [ 'amount', 'chart'],
            [ 12, '海洋渔业企事业年表'],
            [ 10, '海洋渔业企事业月表'],
            [ 2, '海洋油汽业企事业年表'],
            [ 1, '海洋油汽业企事业月表'],
            [ 3, '海洋矿业企事业月表'],
            [ 1, '海洋盐业企事业年表'],
            [ 2, '海洋盐业企事业月表'],
            [ 3, '海洋船舶工业企事业年表'],
            [ 5, '海洋船舶工业企事业月表'],
            [ 2, '海洋化工业企事业年表'],
            [ 1, '海洋化工业企事业月表'],
            [ 1, '海洋生物医药企事业年表'],
            [ 2, '海洋生物医药企事业月表'],
            [ 1, '海洋工程建筑业企事业年表1'],
            [ 1, '海洋工程建筑业企事业年表2']
        ]
    },
    toolbox: {
        show: true,
        feature: {
            saveAsImage: {
                name:'',
                title: ''
            }
        },
        showTitle: true
    },
    grid: {
        left: 200,
        top: 30,
        bottom: 50,
        right: 30
    },
    xAxis: {name: ''},
    yAxis: {type: 'category',inverse: true},
    visualMap: {
        orient: 'horizontal',
        left: 'center',
        min: 0,
        max: 20,
        text: ['High', 'Low'],
        // Map the score column to color
        dimension: 0,
        inRange: {
            color: ['#94d4ff','#D7DA8B', '#E15457']
        }
    },
    series: [
        {
            type: 'bar',
            label: seriesLabel,
            encode: {
                // Map the "amount" column to X axis.
                x: 'amount',
                // Map the "product" column to Y axis
                y: 'chart'
            }
        }
    ]
}
var myChart
function init_chart(){
  // 绘制图表
  myChart.setOption(option)
     
}
```

After defining the above initchart function, register a function to be executed after mounting through the onMounted function in the setup function, as follows:
```JavaScript
onMounted(() => {
            document.getElementById('chart_monitor').style.height = '380px'
            myChart  = echarts.init(document.getElementById('chart_monitor'));
            setTimeout(() => {
                init_chart()
            },1000)
            //sendReq()
        })
```
In the development environment, the chart can be displayed normally. After deploying to the remote server, in the online environment, the chart can be displayed normally when entering the asynchronous routing page containing the chart for the first time, but when switching to other routes, when switching back , The chart cannot be displayed, and the console does not report an error. Check the element and you can see that the canvas tag is also present in the DOM element as the chart container。

This problem is not only encountered in one of the chart components, but also in the charts in all components.

### What is expected?
The chart displays normally

### What is actually happening?
Chart not shown

**Comment by looprandom** [comment]
I used the online tool you sent, but there was no such problem

**Comment by looprandom** [comment]
You can visit the address 8.135.18.96. Both the "首页" and "监测评估" pages contain charts. When you first visit, the charts are normal, but when you switch the route back, the charts cannot be displayed

**Comment by looprandom** [comment]
After refreshing the page, the chart can be displayed normally again

**Comment by looprandom** [comment]
username: user
password: 111111

**Comment by xiaoxian521** [comment]
@looprandom 
Clear the instance before the route leaves
as: https://github.com/xiaoxian521/vue-pure-admin/commit/68330026b694a825e418bb204b46650bccd9c876

**Comment by jevinpi** [comment]
你好，我也遇到了相同的问题，解决方法就是在生命周期结束是销毁实例。请问你找到导致这个的根本原因了吗？
