### ISSUE TITLE
series中type=pie的时候，textBorderColor默认不为transparent问题

### ISSUE THREAD

**Issue by LYlanfeng** [apache/echarts#14035]
### Version
5.0.0

### Reproduction link
[https://echarts.apache.org/next/examples/zh/editor.html?c=pie-simple](https://echarts.apache.org/next/examples/zh/editor.html?c=pie-simple)

### Steps to reproduce
1. 将官方Pie图表示例中背景通过F12调成非白色（非深色模式），就能看到文字边框

### What is expected?
默认不配置任何东西情况下，textBorderColor应该为：transparent。

### What is actually happening?
现在情况是文字默认会有边框颜色。

---
1. API配置文档中textBorderColor默认应该为：transparent
2. API全局配置textStyle无法影响到series中的文字，API文档描述中说明是全局的字体样式。但是实际上配置无效。

**Comment by pissang** [comment]
默认白色边框是为了文本在于其它图形或者文本覆盖的时候能够更清晰的显示

**Comment by LYlanfeng** [comment]
请问下，API全局配置textStyle无法影响下面的类似这种默认的白框的配置吗（配置的color也无效，其他属性未尝试测试）？如果是这样的话，textStyle，作为全局文字配置选项的作用会失去。
