### ISSUE TITLE
Can I do a Bar Pattern

### ISSUE THREAD

**Issue by raykim-eko** [apache/echarts#14047]
### What problem does this feature solve?
Was inquiring about adding patterns to bar charts? In a series being able to edit the itemStyle beyond just color and shadow, etc.

![qcPiL](https://user-images.githubusercontent.com/56883528/104605722-d9696b80-564c-11eb-8a7b-65ee2c4cefcd.jpg)

### What does the proposed API look like?
possible: 

```
series: [
  {
     type: 'bar',
     itemStyle: {
       type: 'pattern',
       pattern: {
         style: 'slantedLines',
         strokeWidth: 2
       }
     }
  }
]

```

**Comment by pissang** [comment]
@raykim-eko Hi, echarts 5.0 add `decal` configuration to support this kind of pattern. 

https://echarts.apache.org/next/en/option.html#aria.decal

PS: some of the examples in the doc seem broken. We will fix it soon

**Comment by raykim-eko** [comment]
@pissang does this work with individual series?

**Comment by pissang** [comment]
@raykim-eko Yes, you can set `itemStyle.decal` for the specific series.
