### ISSUE TITLE
在图形高度很低的情况下，Y轴的刻度值最大值和最小值不显示

### ISSUE THREAD

**Issue by GangLx** [apache/echarts#14042]
### Version
5.0.0

### Steps to reproduce
在图形高度很低（200px）的情况下，Y轴的刻度值最大值和最小值不显示（300和0不显示）

### What is expected?
能否隐藏中间的刻度值，保留最大和最小刻度值！

### What is actually happening?
Y轴刻度值最大值和最小值被隐藏

---
{
xAxis: {
type: 'category',
data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
},
yAxis: {
type: 'value'
},
series: [{
data: [150, 230, 224, 218, 135, 147, 260],
type: 'line'
}]
};

**Comment by yufeng04** [comment]
This [configuration](https://echarts.apache.org/next/zh/option.html#yAxis.axisLabel.showMinLabel) may meet your need.

**Comment by GangLx** [comment]
thank you very much!!!
