### ISSUE TITLE
echarts.graphic.clipRectByRect() missing

### ISSUE THREAD

**Issue by joaconigro** [apache/echarts#14049]
### Version
5.0.0

### Steps to reproduce
I recently updated to version 5.0 and I'm using Angular 11. When I try to compile I have an error that says:

` Module '"../../../node_modules/echarts/types/dist/echarts"' has no exported member 'graphic'.`

On the documentation (https://echarts.apache.org/next/en/api.html#echarts.graphic.clipRectByRect) still appears. So I have no idea how to solve this error.

### What is expected?
Worked well until version 4.9

### What is actually happening?
Apparently, there is no echarts.graphic property anymore.

**Comment by pissang** [comment]
I think it will be fixed in 5.0.1, which will be released tomorrow

**Comment by joaconigro** [comment]
Thanks @pissang! I'll wait for the new version.

**Comment by joaconigro** [comment]
I think this issue can be closed since clipRectByRect it's back again in v5.1.0
