### ISSUE TITLE
桑基图width超过20000后图形无法绘制

### ISSUE THREAD

**Issue by Sweechirly** [apache/echarts#14045]
### Version
5.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/bold-bogdan-n0n2d?file=/index.html](https://codesandbox.io/s/bold-bogdan-n0n2d?file=/index.html)

### Steps to reproduce
当桑基图数据量比较大时，为了能清楚的看到图，需要将dom的宽度拉长。但是宽度超过20000以后就无法绘出了

### What is expected?
希望能达到更宽的宽度

### What is actually happening?
增加dom宽度，图形宽度并没有增加

**Comment by fajiaopaopao** [comment]
浏览器对Canvas元素有最大尺寸的限制，在Chrome中运行了你的Demo，已经超出最大限制导致无法绘制成功。

**Comment by Sweechirly** [comment]
> 浏览器对Canvas元素有最大尺寸的限制，在Chrome中运行了你的Demo，已经超出最大限制导致无法绘制成功。

但是似乎柱状图修改更宽是可以绘制出来的
