### ISSUE TITLE
Donut chart's center number is not showing the correct tooltip and there is no way to disable it as well

### ISSUE THREAD

**Issue by gshikhar94** [apache/echarts#14051]
### Version
4.9.0

### Reproduction link
[https://jsfiddle.net/qjan9u0s/](https://jsfiddle.net/qjan9u0s/)

### Steps to reproduce
Go for any donut chart and select the position inside the label property as the center.
Now, say when we are returning the sum of all the numbers, the tooltip on the center label should show the correct data instead it is showing the first series value.

### What is expected?
Tooltip for the center label in the donut chart should show the correct value or there should be some provision to disable the tooltip for the label in the donut chart. 

### What is actually happening?
The Center label tooltip in the donut chart is showing the wrong value in the tooltip.

**Comment by yufeng04** [comment]
The center label in ECharts 5.0 of donut chart shows the correct value, and you can set `label.show =  false` and `emphasis.label.show = false` to disable the center label.

**Comment by gshikhar94** [comment]
Actually I want to show the sum of all the values in the center and on selection and deselection of the legend, the sum should reflect the same updated value, and this thing is already written and working fine.

My problem is when I am hovering over this center label I can only able to see the first data value in the tooltip but instead I want the sum to be displayed (say 60 ) or if I can somehow disable the tooltip only for the center label?

**Comment by vkjv** [comment]
I have a similar requirement where I need to disable tooltip on the label which is placed at the center of the donut chart. I cannot get rid of the label but want to disable the tooltip on it. 
Is there any way to disable the tooltips on the label?
