### ISSUE TITLE
getDataURL()

### ISSUE THREAD

**Issue by julianbc** [apache/echarts#14059]
### Version
5.0.0

### Steps to reproduce
chart.getDataURL({
                        pixelRatio: 2,
                        backgroundColor: '#fff'
                    });

### What is expected?
A data URL

### What is actually happening?
It is crashing with the following exception:

TypeError: can't access property "viewWidth" of undefined

Same code works fine on the previous version.

**Comment by yufeng04** [comment]
Can you provide a more detailed example for reproduction？

**Comment by zhouxin860114** [comment]
应该是修复了，但还没出新的小版本吧，可以参考着改一下：

参考：
https://github.com/ecomfe/zrender/tree/master/src/canvas
+------------+-------------------------------------------------------------------------+--------------+
| Painter.ts | fix(canvas/painter): ctx was mistakenly assigned with a null value. fix | 22 hours ago |
+------------+-------------------------------------------------------------------------+--------------+

修改内容：
https://github.com/ecomfe/zrender/commit/c1b1ce0fda3e81fc489152f7b8ea89210bdf6a41
