### ISSUE TITLE
When the chart dataZoom is zooming, the chart display problem after calling the interface drawing again

### ISSUE THREAD

**Issue by PansyChen1** [apache/echarts#14050]
### Version
4.9.0

### Steps to reproduce
When the chart is scaled, the interface is re-requested to obtain data, and the chart is redrawn. After multiple scaling, the phenomenon of end-to-end connection in a certain period of time appears.Due to business needs, every time you zoom, you need to re-request the interface and re-draw.

### What is expected?
Zoom multiple times, there will be no end-to-end line segment, normal drawing of chart.

### What is actually happening?
Line segments connected end to end appear in a certain period of time.

---
Is there any good solution? I would appreciate it！

Related graphic:
![image](https://user-images.githubusercontent.com/31918694/104672236-60384a00-571a-11eb-9478-0cb2edcd6788.png)

**Comment by pissang** [comment]
You can disable the animation temporarily. 

PS: Can you provide a reproducible demo for us?

**Comment by PansyChen1** [comment]
how to disable the animation?Is it its default event?

**Comment by pissang** [comment]
https://echarts.apache.org/en/option.html#animation

**Comment by PansyChen1** [comment]
it worked, thanksssss very much!!!!

**Comment by T0miii** [comment]
I think i somehow i get the same behavior :
![image](https://user-images.githubusercontent.com/10532141/130627641-94fb08f2-2524-477e-98e8-8507e981a0d1.png)

going to zoom on the small bump. Important to know, the zoom event also dispatches a request to get new data from the server cause the granularity is changing and then i use the setOption to set the new data.

This is what i get when i zoom on the small bump:
![image](https://user-images.githubusercontent.com/10532141/130627916-7dc85cc2-2844-4eab-9371-0f213752773d.png)

after animation: false this behavior seems to be gone. Can we have solution letting the animation active. An api to rerender the chart maybe?
