### ISSUE TITLE
构建了兼容IE8 echarts5.0.1版本,但是运行报错You need to require 'zrender/vml/vml' to support IE8，如何解决

### ISSUE THREAD

**Issue by lhj117383609** [apache/echarts#14063]
### What problem does this feature solve?
Version & Environment [版本及环境]

ECharts version [ECharts 版本]: 5.0.1

Browser version [浏览器类型和版本]: ie8

OS Version [操作系统类型和版本]: window

Expected behaviour [期望结果]

构建了兼容IE8 echarts5.0.1版本下,但是运行报错You need to require 'zrender/vml/vml' to support IE8，如何解决

### What does the proposed API look like?
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>ECharts</title>
    
    
    <script src="D:\MagicalCoder\ECHARTS各版本JS\echarts.min5.0.1.js"></script>
</head>
<body>
    
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
     	
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
               
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>

**Comment by pissang** [comment]
5.0 开始不再兼容 IE8，官网构建工具还没有更新

**Comment by lhj117383609** [comment]
部分功能兼容也好啊，还有那5以下版本，渐变色加哪句话可以兼容IE8显示



---原始邮件---
发件人: "Yi Shen"<notifications@github.com&gt;
发送时间: 2021年1月18日(周一) 下午5:35
收件人: "apache/echarts"<echarts@noreply.github.com&gt;;
抄送: "lhj117383609"<170130706@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [apache/echarts] 构建了兼容IE8 echarts5.0.1版本,但是运行报错You need to require 'zrender/vml/vml' to support IE8，如何解决 (#14063)




 
5.0 开始不再兼容 IE8，官网构建工具还没有更新
