### ISSUE TITLE
5.0.1 版本地图组件报错

### ISSUE THREAD

**Issue by bluescurry** [apache/echarts#14066]
### Version
5.0.1

### Reproduction link
[https://codesandbox.io/s/echarts-501-map-r1xqe](https://codesandbox.io/s/echarts-501-map-r1xqe)

### Steps to reproduce
采用的官方实例，5.0.0没问题，5.0.1版本会报错

### What is expected?
正常展示地图

### What is actually happening?
报错：
TypeError
Cannot read property 'map' of undefined
MapDraw._updateBackground
https://r1xqe.csb.app/node_modules/echarts/lib/component/helper/MapDraw.js:232:23

**Comment by pissang** [comment]
5.0.1 里 map 组件去除了对 geo 组件的依赖，需要手动添加一下依赖

import "echarts/lib/component/geo";
