### ISSUE TITLE
Pie label margin doesn't exist on typing

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#14067]
### What problem does this feature solve?

When using in TypeScript projects, `series[pie].label.margin` gets the following error:

```
Type '{ position: "outer"; alignTo: "edge"; bleedMargin: number; margin: number; }' is not assignable to type 'PieLabelOption'.
  Object literal may only specify known properties, and 'margin' does not exist in type 'PieLabelOption'.ts(2322)
```

But this option takes effect, so just a problem of typing.

### What is expected?

No type error.

**Comment by Ovilia** [comment]
`margin` seems to be renamed to `edgeDistance`. Document should be updated.

**Comment by pissang** [comment]
Updated the documents

**Comment by pissang** [comment]
Should add back depracted options and add `@deprecated` mark
