### ISSUE TITLE
Echart sankey桑基图是否支持缩放， 节点太多会导致展示不完整 ，无法查看

### ISSUE THREAD

**Issue by hy212** [apache/echarts#14061]
### What problem does this feature solve?
Echart sankey桑基图是否支持缩放， 节点太多会导致展示不完整 ，无法查看

### What does the proposed API look like?
类似于graph图表的 roam属性

**Comment by 2025506282** [comment]
我也有相同的问题

**Comment by apfll** [comment]
What's the solution？
