### ISSUE TITLE
环状图将0%渲染成100%

### ISSUE THREAD

**Issue by zxd-nb** [apache/echarts#14076]
### Version
5.0.0

### Steps to reproduce
环状图使用时，有时会将0%的数据错误的渲染为100%，由于echarts图层原因，这个0%的数据会占据其之前的所有环状的区域，并在hover的时候展示出一个完整的圆环。

### What is expected?
渲染不占据空间的环状空间。

### What is actually happening?
在没有hover的时候渲染的环状图占据其之前所有的环状区域，hover的时候会展现出一个完整的圆环。

---
1.此问题可在重新渲染（不确定名词是否正确）的时候（如legend可以scroll的时候点击scroll箭头/点击某个legend以隐藏某个数据）正确渲染。
2.在某用例中，经自测，当数据集中第一个为0%的数据为第三个数据时，此数据将如上所述错误被渲染，并可稳定复现。（我知道这很离谱，但是确实是这样）。另外，其他情况下类似的渲染行为也可能会出现，在约40次渲染中会出现一次类似的错误（数据不变）。
3.用例大概是先将数据全部渲染为0%，之后请求返回后重新渲染，在某个请求下（数据不变）的情况下稳定复现这个错误。
4.在将版本将为4.9.0 后，不会出现这样的问题

**Comment by plainheart** [comment]
不知是否和 #14074 所述类似？最好能提供一下可复现的在线例子。

**Comment by cheqianxiao** [comment]
> 不知是否和 #14074 所述类似？最好能提供一下可复现的在线例子。

可能是类似的问题： https://codepen.io/oobakoyo/pen/GRoRmvd  
clockwise改为true， 或第一项数据的值改成小于10的数，就不会出现0变成100%的问题，但闪烁仍然存在。

**Comment by plainheart** [comment]
@cheqianxiao 这个 bug 在 #14074 相关的 PR ecomfe/zrender#699 中应该已经修复了，会包含在下一版 [5.1.0](https://github.com/apache/echarts/milestone/19) 中。
