### ISSUE TITLE
series-gauge 仪表盘bug

### ISSUE THREAD

**Issue by zys555** [apache/echarts#14089]
### Version
5.0.1

### Steps to reproduce
在使用仪表盘axisLine：{lineStyle：roundCap：true} 属性

### What is expected?
修复bug支持完善文档中描述的功能

### What is actually happening?
无法实现文档中描述的 在两端显示成圆形的功能

**Comment by pissang** [comment]
是 `axisLine.roundCap`

**Comment by zys555** [comment]
....着急写错了，用不了还是没效果
