### ISSUE TITLE
如何使用甘特图

### ISSUE THREAD

**Issue by dhyunk** [apache/echarts#14085]
### Version
4.9.0

### Steps to reproduce
看到样例中的甘特图，打算用他
但是没有看到具体的数据样式，在下载的文件夹中也没有相关样例的数据。

### What is expected?
期望的结果是我可以把我的数据实现成甘特图

### What is actually happening?
不会用！

---
希望作者可以告诉我用甘特图是需要具体怎么准备数据

**Comment by dhyunk** [comment]
不知道
[1, 1496888100000, 1496892600000, "Y3086", true, "XA", "XA", "HSZ-HAC", "HAC-KVP", 1496879700000]
形式数据中的第二第三元素如何化成
2017/06/08 11：15：00 与 2017/06/08 12：30：00

（以上数据是在chrome接收到的json文件中提取的）

**Comment by wf123537200** [comment]
简单来说，就是类似下面这样（00这种情况要再加个判断），也可以用一些类似 [moment.js](https://github.com/moment/moment)的库来转换
`
var d = new Date(1496888100000);

var res = [d.getFullYear(), d.getMonth() + 1, d.getDate()].join('/') + ' ' +  [d.getHours(), d.getMinutes(), d.getSeconds()].join(':');

console.log(res);`

**Comment by plainheart** [comment]
附加一点：也可使用 ECharts 内置的日期解析和格式化方法 `echarts.time.parse`、 `echarts.time.format`。

**Comment by dhyunk** [comment]
是不是可以直接调用timestemp？
