### ISSUE TITLE
Chart flickers and Abnormal display

### ISSUE THREAD

**Issue by renhao123** [apache/echarts#14099]
### Version
5.0.1

### Steps to reproduce
step1: Scene reappearance by Official example, open link：https://echarts.apache.org/examples/zh/editor.html?c=pie-borderRadius。
step2: change any a value to 0 in option.series.data and then, run it;
step3:  You'll see the chart blink。If not，repeat running it。And rarely it will Abnormal display;

### What is expected?
No more blinking and Normal display

### What is actually happening?
Blinking and rarely Abnormal display

---
I see that someone has already Pointed out the problem when its edition 5.0.0, but It has not been solved until now。
Thank you for your hard work and wish the problem solved quickly。

**Comment by plainheart** [comment]
Thanks for your report. This may be related to #14074, #14076, #14095.

**Comment by renhao123** [comment]
Thank you sir.
love all of you.
