### ISSUE TITLE
Bmap在本初子午线附近只能显示一边的scatter点以及俄罗斯东部部分领土无法渲染

### ISSUE THREAD

**Issue by HamletShaoE** [apache/echarts#14090]
### Version
5.0.0

### Steps to reproduce
使用bmap的demo【https://echarts.apache.org/next/examples/zh/editor.html?c=effectScatter-bmap 】 ，将data和geoCoordMap替换成如下
 var data=[
{name:"Ashburn", value:17},
{name:"Beijing", value:26},
{name:"Chengdu", value:1},
{name:"Hangzhou", value:11},
{name:"Iron", value:1},
{name:"Moscow", value:1},
{name:"Shanghai", value:81},
{name:"Timişoara", value:2},
{name:"Vilnius", value:3},
{name:"Xiamen", value:44},
];
var geoCoordMap={
"Ashburn":[-77.4875,39.0437],
"Beijing":[116.3972,39.9075],
"Chengdu":[104.0667,30.6667],
"Hangzhou":[120.1614,30.2936],
"Iron":[-88.0660,45.8202],
"Moscow":[37.6156,55.7522],
"Shanghai":[121.4581,31.2222],
"Timişoara":[21.2257,45.7537],
"Vilnius":[25.2798,54.6892],
"Xiamen":[118.0819,24.4798],
};

### What is expected?
①当我的中心在太平洋时，且zoom得可见中国和美国时，位于中国和美国的数据点都能现实。
②俄罗斯的领土是完整显示的。

### What is actually happening?
①当位于本处子午线向东边滑动时，发现美国的点是丢失的；但是当滑动超过了本初子午线，中国的数据点就丢失，但是美国的数据点就会显示。
![图片](https://user-images.githubusercontent.com/4826601/105323161-c7676a00-5c04-11eb-8adb-0eb449248ae8.png)
这是还在本初子午线左边，所以只显示了中国的数据点
![图片](https://user-images.githubusercontent.com/4826601/105323233-dbab6700-5c04-11eb-9f7a-941eee957288.png)
这是过了本初子午线，到了右边，所以只显示美国的数据点。

②白令海西北角，部分俄罗斯领土没有显示，没有渲染。这个是在SVG和CANVAS都有，firefox和chrome都有。请问应该怎么解决。
![图片](https://user-images.githubusercontent.com/4826601/105325138-3b0a7680-5c07-11eb-973c-dbe99eaba96b.png)

---
我在本地重复这个图和在demo上直接改数据都是一样的，这两个问题都存在。请问应该怎么样解决呢？

**Comment by plainheart** [comment]
应该是跨了半球导致的，可以试试原生的百度地图 Marker 是否有此问题。

**Comment by plainheart** [comment]
@ytsxstone 这个是百度地图问题，ECharts 无法解决。
