### ISSUE TITLE
 仪表盘有bug，同时设置progress和startAngle ，endAngle。当表盘data初始vaule为0时，颜色会填满整个仪表盘。

### ISSUE THREAD

**Issue by heyu3913** [apache/echarts#14095]
### Version
5.0.1

### Steps to reproduce
仪表盘设置progress样式和startAngle ，endAngle。当表盘data初始vaule为0

### What is expected?
正常显示

### What is actually happening?
希望能正常显示

**Comment by yufeng04** [comment]
Fixed in [zrender](https://github.com/ecomfe/zrender/pull/699)

**Comment by heyu3913** [comment]
请问什么时候可以修复这个问题

**Comment by yufeng04** [comment]
在zrender上已经修复合入了，年前随版 5.1.0
