### ISSUE TITLE
polar series-bar.barMinHeight dosen’t work

### ISSUE THREAD

**Issue by jsbay** [apache/echarts#14097]
### Version
5.0.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=xckjLUYRmD&v=1](https://www.makeapie.com/editor.html?c=xckjLUYRmD&v=1)

### Steps to reproduce
1. set coordinateSystem: 'polar'
2. set barMinHeight 

### What is expected?
polar series-bar.barMinHeight work well

### What is actually happening?
polar series-bar.barMinHeight dosen’t work

**Comment by fajiaopaopao** [comment]
for bar chart in polar coordinates, we can use `barMinAngle`. I found it in the source code. but I didn’t find this configuration in the online documentation.

**Comment by susiwen8** [comment]
@fajiaopaopao Great catch, could you add `barMinAngle ` in doc?

**Comment by fajiaopaopao** [comment]
> @fajiaopaopao Great catch, could you add `barMinAngle ` in doc?

Sure. https://github.com/apache/echarts-doc/pull/158

**Comment by jsbay** [comment]
Thanks, that's' helped me a lot
