### ISSUE TITLE
echarts "finished" event not fired when animation is disabled

### ISSUE THREAD

**Issue by hsluoyz** [apache/echarts#14101]
### Version
4.9.0

### Steps to reproduce
1. Create a chart
2. Set option.animation to false (disable animation)
3. Listen to the "finished" event of the chart

### What is expected?
"finished" event is fired when the chart is loaded.

### What is actually happening?
"finished" event is not fired

---
The charts are used in both modes (animation enabled and disabled) at the same time. I want to do some work when the chart is just finished loading. But it seems that "finished" event doesn't work for charts with animation disabled.

**Comment by susiwen8** [comment]
can't reproduce
<img width="1427" alt="Screen Shot 2021-01-24 at 21 34 49" src="https://user-images.githubusercontent.com/20318608/105632001-196df100-5e8c-11eb-9b91-640486de969f.png">

**Comment by susiwen8** [comment]
@hsluoyz  Sorry, I was using the latest version(5.0.1), maybe you can try it out.

**Comment by hsluoyz** [comment]
Updating to latest v5.0.2 fixed the issue, thanks!
