### ISSUE TITLE
Right click on a draggable point keeps the point in dragging mode untill click

### ISSUE THREAD

**Issue by vdasarat-cumulus** [apache/echarts#14109]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=line-draggable](https://echarts.apache.org/examples/en/editor.html?c=line-draggable)

### Steps to reproduce
1. Right click on any point, this will bring up the default context menu.
2. Click anywhere on the graph to close this menu.
3. Move the cursor on the graph.

### What is expected?
The data point should not be dragging.

### What is actually happening?
The point gets dragged along as you move the cursor.

**Comment by helgasoft** [comment]
this does not happen in v.5.4.0, maybe close as fixed ?
