### ISSUE TITLE
使用datazoom时，点击区域缩放和区域缩放还原按钮后，如何区分触发的是哪一个事件？

### ISSUE THREAD

**Issue by PansyChen1** [apache/echarts#14100]
### Version
4.9.0

### Steps to reproduce
监听了图表的datazoom事件，进行区域缩放或区域缩放还原时想判断是触发的哪个事件，打印出来的event没办法进行区分

### What is expected?
期望区分事件以进行不同的操作

### What is actually happening?
未找到区分两个不同事件的属性

---
希望有大佬能解决我的问题，不胜感激！

**Comment by 501586528** [comment]
Did you solve it?

**Comment by sweetheartbaby** [comment]
请问是如何解决的
