### ISSUE TITLE
itemStyle not respected for object-array like dataset

### ISSUE THREAD

**Issue by maurice-g** [apache/echarts#14116]
### Version
5.0.1

### Reproduction link
[https://jsfiddle.net/4da2kng8/](https://jsfiddle.net/ake3w7n2/)

### Steps to reproduce
Set properties like `color`, `opacity` or `borderWidth` on elements of dataset, e.g.
```
option = {
    legend: {},
    tooltip: {},
    dataset: {
        dimensions: ['product', '2015', '2016', '2017'],
        source: [
            {product: 'Matcha Latte', '2015': 43.3, '2016': 85.8, '2017': 93.7, itemStyle: { opacity: 0.3, color: '#000', borderWidth: 10, borderColor: '#000' } },
            {product: 'Milk Tea', '2015': 83.1, '2016': 73.4, '2017': 55.1},
            {product: 'Cheese Cocoa', '2015': 86.4, '2016': 65.2, '2017': 82.5},
            {product: 'Walnut Brownie', '2015': 72.4, '2016': 53.9, '2017': 39.1}
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};
```

### What is expected?
That those properties are respected and the styles rendered accordingly.

### What is actually happening?
Most properties are just ignored, some cause unexpected (wrong) effects, like `borderWidth` (see screenshot below)

<img width="635" alt="Screenshot 2021-01-25 at 16 14 25" src="https://user-images.githubusercontent.com/2892585/105724834-90f15e00-5f28-11eb-9981-4511bfd93b14.png">

**Comment by peder1001** [comment]
Add the itemStyle to your series instead of the dataset

**Comment by maurice-g** [comment]
That would apply the styling to the other dimension (2015, 2016, 2017) and not the products. This also used to work before v5, so I heavily suspect this is a bug.

**Comment by maurice-g** [comment]
@100pah do you have a hint at where this might need to be fixed? I could then give it a try myself.

**Comment by maurice-g** [comment]
@100pah I think this is a pretty small thing - `data.hasItemOption = false` where it should be true.
Setting the property `hasItemOption` on the returned value in https://github.com/apache/echarts/blob/8f48ad285134a0a5907c19e479ae6c5bc270228a/src/chart/bar/BarSeries.ts#L88 to `true` solves the problem, but that's probably the wrong place to just override it. Any hint where the root-cause is?
