### ISSUE TITLE
echarts.graphic.setTextStyle is not a function

### ISSUE THREAD

**Issue by yaohong0713** [apache/echarts#14118]
### Version
5.0.1

### Steps to reproduce
I recently updated to version 5.0.1. When I try to compile I have an error that says:
echarts.graphic.setTextStyle is not a function

### What is expected?
Worked well

### What is actually happening?
Apparently, report errors

**Comment by yaohong0713** [comment]
> @yaohong0713 Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.


demo：https://codesandbox.io/s/cocky-bird-tudqj?file=/src/index.js

**Comment by pissang** [comment]
echarts-wordcloud 需要更新到最新版本
