### ISSUE TITLE
Eacharts关系图

### ISSUE THREAD

**Issue by loveliangakai** [apache/echarts#14115]
### What problem does this feature solve?
eachafrts关系图如何指定某一个数据高亮

### What does the proposed API look like?
我看了action里面没有明确的api 只有focusNodeAdjacency 自己和相关联的数据高亮！而需求是指定某一个数据高亮如何解决

**Comment by loveliangakai** [comment]
dispatchAction({
    type: 'highlight',
    dataIndex: number,
})  这个api是所有图都可用么  我在关系图中设置不生效

**Comment by srx172842030** [comment]
> dispatchAction({
> type: 'highlight',
> dataIndex: number,
> }) 这个api是所有图都可用么 我在关系图中设置不生效

需要添加series的索引
myChart.dispatchAction({
  type: 'highlight',
  seriesIndex: 0,
  dataIndex: 0
});
