### ISSUE TITLE
Legend symbol/label are misaligned in some cases

### ISSUE THREAD

**Issue by gregdeane** [apache/echarts#14121]
### Version
5.0.1

### Steps to reproduce
1. Create any chart with a legend
2. Use the legend options below

**Note**: The use of "Hind" for `fontFamily` is important here

```javascript
{
  ...
  icon: 'circle',
  itemWidth: 8,
  itemHeight: 8,
  textStyle: {
    fontFamily: 'Hind',
    fontSize: 12
  }
  ...
}
```

### What is expected?
It is expected that the symbol (circle) and the label are vertically-aligned with each other.

### What is actually happening?
When using "Hind" as the font family, the symbol and label are not vertically-aligned with one another. Other fonts (including custom fonts) do not have this issue. I tried modifying nearly all related options, including trying to "hack" together something that forced the label and symbol to align but nothing worked.

v4 of eCharts worked fine for the "Hind" font so it's something to do with v5.

---
After upgrading to v5, the legend symbol/labels were no longer aligned. We had been using v4 for 2-3 years with no problem.

#### Notice how the symbol (circle) and the label are not vertically-aligned with one another ("Hind" font)
![Screenshot 2021-01-26 at 06 21 43](https://user-images.githubusercontent.com/4949000/105804602-7ce94300-5fa0-11eb-93f6-3cc1b4887d5d.png)

#### Notice when using other fonts (Montserrat and default font, respectively), the symbol and labels are perfectly aligned
![Screenshot 2021-01-26 at 06 23 35](https://user-images.githubusercontent.com/4949000/105804635-95f1f400-5fa0-11eb-9299-77012d62b632.png)

![Screenshot 2021-01-26 at 06 24 54](https://user-images.githubusercontent.com/4949000/105804641-9a1e1180-5fa0-11eb-96c0-9b1a0a999e7b.png)

**Comment by Ovilia** [comment]
Legend text uses `'middle'` for vertical text align. So this is probably because the middle line of "Hind" is higher than the others. I tested both 4.x and 5.x and they both have similar result, so this should not be an issue of ECharts.

![4.x](https://user-images.githubusercontent.com/779050/106408235-fe494580-6478-11eb-8e7d-17d993e40873.png)
![5.x](https://user-images.githubusercontent.com/779050/106408246-04d7bd00-6479-11eb-8c15-d26c2cc15106.png)

A simple way to adjust the position would be using [padding](https://echarts.apache.org/en/option.html#legend.padding).

**Comment by gregdeane** [comment]
Thank you for the suggestion @Ovilia. Unfortunately, `padding` doesn't fix the issue. I tried both padding on the legend itself and padding on `textStyle`. Neither of them affect the text in any helpful way.

In the screenshot below, the red border indicates legend padding and the blue border indicates textStyle padding. Instead of pushing the text up or down, padding is simply added above or below.

Perhaps a `margin` setting for `textStyle` could be helpful? Or any other setting that allows direct control of the placement of the text.

Any thoughts or suggestions are appreciated.

![Screenshot 2021-02-04 at 08 10 35](https://user-images.githubusercontent.com/4949000/106857763-e5cb6c00-66c0-11eb-8812-290f8321e082.png)

**Comment by gregdeane** [comment]
@Ovilia Any thoughts or suggestions on my [comment above](https://github.com/apache/echarts/issues/14121#issuecomment-773088516)?

**Comment by gregdeane** [comment]
Hello, just following up on this. It's labeled as "not-a-bug" but @Ovilia's suggestion does not work. If there is no solution to the issue, then I believe this _is_ a bug.

Can someone please reply with a way to address the issue in the initial comment?
