### ISSUE TITLE
Website: Wrong spelling of 'Visualization'

### ISSUE THREAD

**Issue by stolp** [apache/echarts#14129]
The website reads: An Open Source JavaScript Visualiztion Library

It should be: An Open Source JavaScript Visualization Library

This is not adequate for this really impressive product.

See: https://echarts.apache.org/en/index.html

**Comment by stolp** [comment]
I hope a human is reading this.

**Comment by plainheart** [comment]
@stolp Thank you for your feedback. This typo has been fixed in apache/echarts-www#22. But the website doesn't get updated     yet. @pissang Would you mind helping make an update for the website? Besides this, I've corrected some other issues, including `echarts-www` and `echarts-doc`.

**Comment by pissang** [comment]
@plainheart Sure

**Comment by pissang** [comment]
Updated. Thanks for the feedback.
