### ISSUE TITLE
仪表盘自定义图片指针无法加载

### ISSUE THREAD

**Issue by ismr6658** [apache/echarts#14131]
### Version
5.0.1

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-gauge.pointer.icon](https://echarts.apache.org/zh/option.html#series-gauge.pointer.icon)

### Steps to reproduce
pointer: {
                            icon:
                                "image://https://www.baidu.com/img/flexible/logo/pc/result.png",
                            length: "70%",
                        }

### What is expected?
显示自定义图片指针

### What is actually happening?
自定义图片指针未显示

**Comment by Ovilia** [comment]
It seems to be a bug. It works with SVG path but not image URL or base64 image.
