### ISSUE TITLE
echarts@5.0^ cannot be imported in Vue.The error is that echarts cannot be found. Please resolve this issue.

### ISSUE THREAD

**Issue by Katrina-yue** [apache/echarts#14138]
### Version
5.0.0

### Steps to reproduce
1. npm i echarts 2. 'import echarts from 'echarts' in any vue file. 3. console.log(echarts)  => undefined

### What is expected?
vue5.0及以上版本在vue中引入无效。报错echarts not be found.

### What is actually happening?
vue5.0及以上版本在vue中引入无效。报错echarts not be found.

---
vue5.0及以上版本在vue中引入无效。报错echarts not be found.

**Comment by plainheart** [comment]
v5 在引入方式上有了改变，请参阅 https://echarts.apache.org/zh/tutorial.html#ECharts%205%20%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97

**Comment by LuvTian** [comment]
我在vue项目使用新5.0.1新的按需引入方式：
```import * as echarts from 'echarts/core'
import {
    BarChart, LineChart
} from 'echarts/charts'
import { TooltipComponent, TitleComponent, LegendComponent, DataZoomComponent } from 'echarts/components'

echarts.use([BarChart, LineChart, TooltipComponent, TitleComponent, LegendComponent, DataZoomComponent])
```
然后报错了不知道是哪里的问题：

 ```
Uncaught (in promise) Error: Renderer 'undefined' is not imported. Please import it first.
    at new ZRender (zrender.js:64)
    at Module.init (zrender.js:244)
    at new ECharts (echarts.js:216)
    at Module.init (echarts.js:1847)
    at VueComponent.drawLine (DataAnalysis.vue:76)
    at DataAnalysis.vue:71
```

**Comment by pissang** [comment]
![image](https://user-images.githubusercontent.com/841551/106102535-80382680-617a-11eb-83a1-302d9367efa9.png)

建议直接在示例页的完整代码标签页下查看自己需要引入的组件以及引入的代码

**Comment by LuvTian** [comment]
引入Canvas渲染组件后，`'undefined' is not imported`组件引入类的报错信息不再出现，但是又出现了新的问题，echarts未能渲染出图形来，控制台出现警告信息：
```
LegendView.js:187 A类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 B类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 C类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 总数 series not exists. Legend data should be same with series name or data name.
echarts.js:1835 There is a chart instance already initialized on the dom.
LegendView.js:187 A类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 B类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 C类 series not exists. Legend data should be same with series name or data name.
LegendView.js:187 总数 series not exists. Legend data should be same with series name or data name.
```
我是从5.0.0升级到5.0.1，只修改了引入方式，options没有做修改，在5.0.0下没有问题，可以正常工作。
查了5.0.1升级指导文档，没有找到相关说明，我想知道现在的问题是否还是组件引入不当的原因

**Comment by itbainianmei** [comment]
我也遇到了同样的问题，没解决

**Comment by gxxcicon** [comment]
引完官方说的就可以了

**Comment by gxxcicon** [comment]
![image](https://user-images.githubusercontent.com/64461307/125431781-75967c4b-f8da-45e0-bb54-658692d48215.png)
这些都得引用

**Comment by pxim** [comment]
import * as echarts from 'echarts/dist/echarts.esm';

**Comment by staxing** [comment]
> import * as echarts from 'echarts/dist/echarts.esm';

5.2version
use  import * as echarts from 'echarts'  cannot success  
but use  import * as echarts from 'echarts/dist/echarts.esm' success 

this is why

**Comment by rehack** [comment]
您好！您的邮件已经收到，我会及时回复您，感谢您对睿客网的支持。需了解更多高质量的web开发技术请移步：http://www.rehack.cn/

**Comment by staxing** [comment]
您好，邮件已经收到，我将尽快给您回复。谢谢~~

**Comment by maymayuo** [comment]
Yes, if you use "import * as echarts from 'echarts/dist/echarts.esm' " instead of " import * as echarts from 'echarts/core' ", you can run it successfully. For better understanding the situation I face, below is the error when I import echart using the old ways:
![netease](https://github.com/apache/echarts/assets/89370037/b831d035-c470-49b3-a98a-470519547a70)

**Comment by staxing** [comment]
您好，邮件已经收到，我将尽快给您回复。谢谢~~
