### ISSUE TITLE
使用graph图时，两个节点之间的多条连线可以设置偏移量吗

### ISSUE THREAD

**Issue by chj-damon** [apache/echarts#14134]
### Version
5.0.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=graph-simple](https://echarts.apache.org/examples/zh/editor.html?c=graph-simple)

### Steps to reproduce
节点1和节点2之间有两条连线，但是现在这两条连线重叠在一起了

### What is expected?
期望不用设置curveness也可以做到两条线互不干扰

### What is actually happening?
两条连线重叠在一起了

**Comment by Ovilia** [comment]
You can set [autoCurveness](https://echarts.apache.org/zh/option.html#series-graph.autoCurveness) to be a number greater than `2`. I think the document has some problem because the default value of this options seems to be `0`.

**Comment by wf123537200** [comment]
You can try remove all the ```lineStyle.curveness``` in the options, and set ```autoCurveness``` to ```true```. 
The documentation is missing some configuration instructions and will be updated later.

**Comment by Ovilia** [comment]
Doc fixed in https://github.com/apache/echarts-doc/pull/159

**Comment by chj-damon** [comment]
can I make it straight? My requirement is I want to use straight lines instead of curveness lines, and I want straight lines that won't cover each other.

**Comment by cjlhll** [comment]
> 我可以把它弄直吗？我的需求是使用直线而不是曲线，并且直线不会互相覆盖。
> 
> ![image](https://user-images.githubusercontent.com/4902684/106419342-41b0ad80-6493-11eb-80ed-8acd8f42b7e2.png)
> 
> 它看起来应该是这样的。

解决了吗？我也想要这样的效果。
