### ISSUE TITLE
多系列折线图label重叠

### ISSUE THREAD

**Issue by kkkisme** [apache/echarts#14133]
### Version
5.0.1

### Steps to reproduce
多系列折线图 在数据相近时，标签重叠

### What is expected?
数据相近时，label不重叠
![image](https://user-images.githubusercontent.com/18638401/105938701-bb5f2a80-6092-11eb-86c6-3396277443e6.png)

### What is actually happening?
数据相近时，label重叠

![image](https://user-images.githubusercontent.com/18638401/105938432-87840500-6092-11eb-9386-c4c71dd58e79.png)

---
https://zhuanlan.zhihu.com/p/102136927

**Comment by pissang** [comment]
试试 https://echarts.apache.org/zh/option.html#series-line.labelLayout.hideOverlap

**Comment by kkkisme** [comment]
> 试试 https://echarts.apache.org/zh/option.html#series-line.labelLayout.hideOverlap

效果符合预期，谢谢
