### ISSUE TITLE
label formatter string template {@xxx} invalid

### ISSUE THREAD

**Issue by felixpu** [apache/echarts#14135]
### Version
5.0.1

### Steps to reproduce
option = {

    series: [
        {
            // name: '访问来源',
            type: 'pie',
            radius: '50%',
            data: [
                {value: 1048, name: '搜索引擎', unit:'%'},
                {value: 735, name: '直接访问', unit:'%'},
                {value: 580, name: '邮件营销', unit:'%'},
                {value: 484, name: '联盟广告', unit:'%'},
                {value: 300, name: '视频广告', unit:'%'}
            ],
            label: {
                formatter: '{b} {c} /{@unit}'
            }
        }
    ]
};

### What is expected?
get unit`s value

### What is actually happening?
get a defualt value = {c}
this is not my expect value

**Comment by Ovilia** [comment]
Try with dataset? https://echarts.apache.org/en/option.html#series-pie.label.formatter

**Comment by felixpu** [comment]
> Try with dataset? https://echarts.apache.org/en/option.html#series-pie.label.formatter

感谢小姐姐回复，这个思路可以

**Comment by felixpu** [comment]
> > Try with dataset? https://echarts.apache.org/en/option.html#series-pie.label.formatter
> 
> 感谢小姐姐回复，这个思路可以
