### ISSUE TITLE
5.0版本resize是否取消掉了缓动动画，为什么执行resize()后缓动效果没有了？

### ISSUE THREAD

**Issue by JManToGithub** [apache/echarts#14146]
`let myChart = this.$Echarts.init(document.getElementById('myDiv'));
    let option = {
      xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
      },
      yAxis: {
        type: 'value'
      },
      series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar'
      }],
      animation: true
    };

    myChart.setOption(option);
    myChart.resize();`

这段代码在4.x下，即使执行了resize，缓动效果还是存在的，可是升级了5.0后，执行了resize之后缓动效果就没有了

**Comment by zhoufanglu** [comment]
resize动画效果确实没了，请问答主加上了吗
