### ISSUE TITLE
OHCL bugged display of chart

### ISSUE THREAD

**Issue by MeMeMax** [apache/echarts#14145]
### Version
5.0.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=custom-ohlc](https://echarts.apache.org/examples/en/editor.html?c=custom-ohlc)

### Steps to reproduce
1. Pull the navigation bar to the fullest extend
2. Let off the navbar
3. Pull the navigation a bit smaller again
=> 

### What is expected?
The chart is displayed only for the selected range

### What is actually happening?
A part of the chart is still visible even though it is not in the navigation range anymore

---
I am using Chrome in Version 86.0.4240.198

**Comment by Ovilia** [comment]
Seems to be a bug. It can be reproduced with both SVG and Canavas rendering.
