### ISSUE TITLE
cannot find axis.js in lib\component

### ISSUE THREAD

**Issue by horoy** [apache/echarts#14140]
### Version
5.0.1

### Steps to reproduce
1.npm install echarts@5.0.1
2.import 'echarts/lib/component/axis'
3.Error: this dependency was not found

### What is expected?
I just wonder how to import axis

### What is actually happening?
cannot find axis.js in lib\component

**Comment by pissang** [comment]
You can import the `grid` component. Or in the example page, you can find which components you need to import from your option.

![image](https://user-images.githubusercontent.com/841551/106083355-56213d00-6157-11eb-93f5-726cfd86cfce.png)
