### ISSUE TITLE
`use` API cannot work after `echarts.init` called.

### ISSUE THREAD

**Issue by fxxjdedd** [apache/echarts#14152]
### Version
5.0.1

### Reproduction link
[https://codesandbox.io/s/echarts-tooltip-richtext-dispose-forked-rh0cf](https://codesandbox.io/s/echarts-tooltip-richtext-dispose-forked-rh0cf)

### Steps to reproduce
click button to render chart

### What is expected?
render as expected

### What is actually happening?
throw an error

---
This kind of demand exists in the scenario of dynamically selecting charts to be loaded on demand, so as to achieve the miniest first screen load time.

**Comment by Ovilia** [comment]
Try with 5.0 version. I cannot reproduce it.

**Comment by fxxjdedd** [comment]
I understand the usage, and it may not be a bug. But in some scenarios, such as dynamically selecting a chart to load on demand at runtime, we must put `use` after `echarts.init`.

**Comment by fxxjdedd** [comment]
Imagine that there were no line-chart in the first render, but a line-chart will be rendered after  button is clicked.

Then it is a waste of time to load the relevant bundle of the line lib during the first rendering.

**Comment by fxxjdedd** [comment]
Imagine that only a line-chart will be rendered during the first render, and the bar-chart will be rendered after clicking a button.

Then it is a waste of time to load the relevant bundle of bar's lib during the first rendering.

At present, if we want to achieve this optimization, we can only destroy the echarts instance first, and then re-instantiate it

**Comment by pissang** [comment]
I think this has no help to the bundle size because it's too dynamic for bundler to analyze

**Comment by fxxjdedd** [comment]
I appreciate your help very much, the cost is indeed not much.

**Comment by fxxjdedd** [comment]
By the way, there is no black magic, just dynamic import.
