### ISSUE TITLE
line charts data display error

### ISSUE THREAD

**Issue by buttre** [apache/echarts#14150]
### Version
5.0.1

### Reproduction link
[https://jsfiddle.net/xiaolaoqi/zL6f3hun/10/](https://jsfiddle.net/xiaolaoqi/zL6f3hun/10/)

### Steps to reproduce
After opening the link, click run, Look at the x-axis 2015, three different data points overlap. 

### What is expected?
The value 0 should be at the origin

### What is actually happening?
The value 0 is above the Y axis

**Comment by pissang** [comment]
remove `stack` config from your option.

**Comment by buttre** [comment]
ok, thx
