### ISSUE TITLE
The map3D-emphasis attribute  doesn't  work. And how to get the item-name when you clicked the item in the map3D echarts?

### ISSUE THREAD

**Issue by Katrina-yue** [apache/echarts#14151]
### Version
5.0.0

### Steps to reproduce
```js
 myChart.setOption({
        title: {
          textStyle: {
            color: "#fff",
            fontWeight: "bolder",
            fontSize: 28,
            width: "100%",
          },
          textAlign: "left",
        },
        tooltip: {
          trigger: "item", 
        },
        toolbox: {
          show: true,
          orient: "vertical",
          left: "right",
          top: "center",
          feature: {
            dataView: { readOnly: false },
            restore: {},
            saveAsImage: {},
          },
        },
        visualMap: {
          show: false,
          min: 0,
          max: 21,
          text: ["High", "Low"],
          realtime: false,
          calculable: true,
          inRange: {
            color: ["#e7f0fd", "#6f86d6"],
          },
        },
        series: [
          {
            type: "map3D",
            map: 'world,
            label: {
              show: true,
              textStyle: {
                fontSize: 14,
                color: "#333",
              },
            },
            emphasis: {
              label: {
                show: false,
              },
              itemStyle: {
                opacity: 1,
                color: "orange",
              },
            },
            shading: "lambert",
            viewControl: {
              alpha: 60,
              beta: 10,
              distance: 80,
            },
            top: -10,
            bottom: 10,
            data: [ ],
            barSize: 0.1,
            minHeight: 0.2,
            silent: true,
            itemStyle: {
              borderWidth: 1,
              borderColor: "#333",
              opacity: 0.9,
            },
          },
        ],
      });
      myChart.getZr().on("click", (params) => {
        console.log( params);
      });
```
### What is expected?
使用map3D，在series中设置了emphasis但并不起作用。tooltip组件也并没有触发，没有显示提示。点击事件也没有监听到。查找资料使用getZr()，但是获取不到点击的是哪一个item.
When I set series-type-map3D , I found that the emphasis attribute doesn't work.And the tooltip component doesn't work too.I used getZr().onClick function to setting but it cannot get the clicked item-name.

### What is actually happening?
使用map3D，在series中设置了emphasis但并不起作用。tooltip组件也并没有触发，没有显示提示。点击事件也没有监听到。查找资料使用getZr()，但是获取不到点击的是哪一个item.
When I set series-type-map3D , I found that the emphasis attribute doesn't work.And the tooltip component doesn't work too.I used getZr().onClick function to setting but it cannot get the clicked item-name.

---
使用map3D，在series中设置了emphasis但并不起作用。tooltip组件也并没有触发，没有显示提示。点击事件也没有监听到。查找资料使用getZr()，但是获取不到点击的是哪一个item.
When I set series-type-map3D , I found that the emphasis attribute doesn't work.And the tooltip component doesn't work too.I used getZr().onClick function to setting but it cannot get the clicked item-name.

**Comment by helgasoft** [comment]
map3D emphasis, tooltip and click - [Demo](https://echarts.apache.org/examples/en/editor.html?gl=1&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QzhAaQQArJKkJSANKIBmAV0IBjOPmOjSmgFJHC5UQG9qo0aCQsIgQ-LiM2HhEZFR-ooy20PBICDCMxPhIcIwwALJQAA6kUrpmom4esf6BSYhqcOwFDsakcf6kqE2OhKIAvD5t_qIOcAA2jABcA0Mzw4wAHnBTUnydVqMK3aIAIoyESPhwIKKoFqLCxsSiOpeigBD_AEwADACML4CQ_2aD_gC-pt_DVCoUYOApTbzDGD4YhMGDLQ6MYBSUR_AFqKGMJBTADaAP8vlmsyOBUm0mAhQAzNsvoSZuSwdJSv9aUMEcAAMpHcbg0QAI1QMHCMDAwIFy15MAwJnM_MFOQA6mE4BApi9USyfgCALqDH7kOKxPU0GrBBAtKS2Ub4WwAazKBVgUGAfQAfNMAuBashmI1moRSN4RtzAwslg6YE6EIQnYwfnrqHqgA)
