### ISSUE TITLE
5.0.0版本不兼容5.0.1

### ISSUE THREAD

**Issue by aloneYang** [apache/echarts#14163]
使用5.0.0版本开发的，线上环境打包后为5.0.1，导致报错Cannot read property 'get' of undefined，图表渲染不出来。
![image](https://user-images.githubusercontent.com/65587218/106411924-64d26180-6481-11eb-8271-b33da21a5b72.png)

**Comment by pissang** [comment]
@aloneYang 参考这个问题 https://github.com/apache/echarts/issues/14080#issuecomment-763425011 需要引入 grid 组件
