### ISSUE TITLE
china.js

### ISSUE THREAD

**Issue by yfjiang-danny** [apache/echarts#14168]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by plainheart** [comment]
All the maps have been removed from the repository since v5.0.0, so you need to download them from the previous versions before v5.0.0, such as [4.9.0](https://www.jsdelivr.com/package/npm/echarts?version=4.9.0&path=map). Or you can also download from third-party providers.
