### ISSUE TITLE
关于仪表盘startAngle起止角度问题

### ISSUE THREAD

**Issue by Yato915** [apache/echarts#14161]
{
        type: 'gauge',
        center: ["50%", "60%"],
        radius: '71%',
        startAngle: 150,
        endAngle: -20,
        min: 0,
        max: 2000,
        progress: {
            show: true,
            width: 18
        },
        axisLine: {
            show: false
        },
        axisTick: {
            show: false
        },
        splitLine: {
            show: false
        },
        axisLabel: {
            show: false
        },
        anchor: {
            show: false
        },
        title: {
            show: false
        },
        detail: {
            show: false
        },
        pointer: {
            show: false
        },
        data: [{
            value: 0
        }
        ]
    },
## startAngle为150度的时候绘制有问题

**Comment by plainheart** [comment]
感谢反馈，与 #14095 属同一问题，会在接下来的 [5.0.2](https://github.com/apache/echarts/milestone/22) 版本中修复。
