### ISSUE TITLE
移动端，dataZoom和handler一起使用的bug，未被选中的柱形图也会高亮展示，多个柱子同时高亮

### ISSUE THREAD

**Issue by Gloria-Dee** [apache/echarts#14172]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=candlestick-touch](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-touch)

### Steps to reproduce
1、在移动端打开上述链接https://echarts.apache.org/examples/zh/editor.html?c=candlestick-touch
2、用手指点击柱形图，多次点击后，未被选中的柱子也高亮了，这不应该出现。
3、用手指在柱形图区域进行放大缩小，当触碰到其他柱子时，其他的柱子有时候会被高亮，但是axisPointer仍在之前已选中的柱子上，但之前已选中柱子的高亮效果会消失。
4、用手指选中柱形图的一个柱子，然后不放手，在柱形图区域进行拖动，当停下的那一刻，停下时手指所触碰的柱子会高亮，但是之前被选中的柱子也仍旧处在高亮的状态。

### What is expected?
1、希望点击到柱子，柱子就应该高亮，并且handler指向该柱子
2、希望在进行放大缩小时，未被选中的柱子在被触碰到时，不需要高亮。
3、希望在柱形图区域拖动，停下的那一刻，停下时手指所触碰的柱子会高亮并且被handler选中，之前被选中的柱子选中态会被取消掉

### What is actually happening?
1、用手指点击柱形图，多次点击后，未被选中的柱子也高亮了，这不应该出现。
2、用手指在柱形图区域进行放大缩小，当触碰到其他柱子时，其他的柱子有时候会被高亮，但是axisPointer仍在之前已选中的柱子上，但之前已选中柱子的高亮效果会消失。
3、用手指选中柱形图的一个柱子，然后不放手，在柱形图区域进行拖动，当停下的那一刻，停下时手指所触碰的柱子会高亮，但是之前被选中的柱子也仍旧处在高亮的状态。

**Comment by Ovilia** [comment]
我试了一下没有复现出来，不知道是不是因为现在这个链接已经是 5.0 的代码的原因。@Gloria-Dee 现在还有这个问题吗？

**Comment by grantedFine** [comment]
5.2.0的用户表示仍然有这个问题，在ios 9-12上复现概率比较高
