### ISSUE TITLE
Needle Animation with circluar 360° Gauges: make needle to move over axis boundaries

### ISSUE THREAD

**Issue by mKainzbauer** [apache/echarts#14186]
### What problem does this feature solve?
I use gauge charts for showing wind direction in realtime. Therefore I've configured a gauge to show 360° in a circular gauge, see https://jsfiddle.net/x2ruqh1s/
The "problem": a rather slight change in Wind direction from 5° to 355° makes the needle jump 350° all around the gauge. I totally understand why.
I would be nice if there would be an option to let the needle ignore axis boundaries on 360° circular gauges and let it jump the "shortest" 10°. It would give a better impression of what ist happening in reality: slight direction changes. Now one can get the impression, the wind direction is changing like crazy.
Workaround:  disabling animation. Without animation, the viewer doesn't get the impression.
It is an eye candy, I know. :)

### What does the proposed API look like?
An option value to control the behaviour, if the needle should be allowed to jump over boundaries.

**Comment by ddyedu** [comment]
How did you proceed? ? Can you tell me about a complex problem that you solved?

**Comment by mKainzbauer** [comment]
Me? The problem isn't solved. The workaround is not using animated gauges.

**Comment by michi-k** [comment]
Here is a workaround:
https://jsfiddle.net/13tc4wge/
https://jsfiddle.net/13tc4wge/1/
