### ISSUE TITLE
toolbox保存png图片，配置pixelRatio异常

### ISSUE THREAD

**Issue by 1123219394** [apache/echarts#14181]
### Version
5.0.1

### Steps to reproduce
toolbox配置项中feature-》saveAsImage下的pixelRatio大于1报错，无法下载图片

### What is expected?
正常下载图片

### What is actually happening?
报错异常

**Comment by plainheart** [comment]
感谢反馈，与 #14112，#13914，#14179 属同一问题，我们已在即将发布的 [5.0.2](https://github.com/apache/echarts/milestone/22) 中修复该 bug，RC 版本可在 GitHub releases 中找到 https://github.com/apache/echarts/releases/tag/5.0.2-rc.1。
