### ISSUE TITLE
Rich text flags not displaying

### ISSUE THREAD

**Issue by Blakey** [apache/echarts#14180]
### Version
5.0.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=bar-race-country](https://echarts.apache.org/examples/en/editor.html?c=bar-race-country)

### Steps to reproduce
Visit your code example https://echarts.apache.org/examples/en/editor.html?c=bar-race-country

Your thumbnail has the flags working, but the code example does not render them.

This also does not work on my local version

### What is expected?
Flag emojis to be rendered

### What is actually happening?
Code remains as the emoji characters

**Comment by plainheart** [comment]
Are you using Windows? It seems not to support the flag emoji for some reasons. Here is a reply from [Twitter status](https://twitter.com/emojipedia/status/838509019174174720) and a [blog](https://blog.emojipedia.org/emoji-flags-explained/) for your information. :) So you may need to consider some other alternatives in Windows.

**Comment by plainheart** [comment]
Just made an online alternative demo, https://www.makeapie.com/editor.html?c=x0J1Q8WxPL&v=1

**Comment by Blakey** [comment]
Apologies for not investigating more and seeing that it was a Windows issue! Thanks so much for the alternative demo, it is fantastic. Great job!

**Comment by rubenep13** [comment]
> Just made an online alternative demo, https://www.makeapie.com/editor.html?c=x0J1Q8WxPL&v=1

Do you still have this working demo? Broken link
