### ISSUE TITLE
在 5.0.1 中convertToPixel 方法计算出的像素坐标有误

### ISSUE THREAD

**Issue by xajeyu** [apache/echarts#14197]
### Version
5.0.1

### Steps to reproduce
使用一段 geojson 地图文件作为地图底图(地图设置不能拖动不能缩放)，然后  设置使用一组经纬度通过scatter打在地图上，然后 在用这组经纬度通过convertToPixel推算出 像素坐标

### What is expected?
convertToPixel 和 scatter输出的位置应该是相同的

### What is actually happening?
不相同

**Comment by pumpkindev** [comment]
关系图convertToPixel出现了同样的bug
[#14935](https://github.com/apache/echarts/issues/14935)
