### ISSUE TITLE
Markline labels are shown below bars.

### ISSUE THREAD

**Issue by barisnisanci** [apache/echarts#14190]
### Version
5.0.1

### Reproduction link
https://jsfiddle.net/92gkcwdb/

### Steps to reproduce
Add label to bar series markline and set coord to series max

### What is expected?
Markline labels should have higher zIndex

### What is actually happening?
Markline labels are shown underneath serie bars.

---
Cannot reproduce on 4.x versions

**Comment by screamsyk** [comment]
you can set `z` in `series`to a negative value such as `-1`  to sovle this problem for the moment

**Comment by keephungryHF** [comment]
May I ask when this feature can be added
