### ISSUE TITLE
关系图超过一万个节点渲染特比慢，浏览器也卡死

### ISSUE THREAD

**Issue by panling00** [apache/echarts#14195]
### Version
4.0.3

### Steps to reproduce
添加2000以上节点，至少2000条边

### What is expected?
优化大量数据（至少5000个月节点和边）

### What is actually happening?
浏览器无响应

**Comment by pissang** [comment]
试试使用 echarts-gl 中的 graphGL 组件 https://echarts.apache.org/examples/zh/editor.html?c=graphgl-npm-dep&gl=1&theme=dark

**Comment by panling00** [comment]
请教一下，GL关系图边怎么加箭头呢，我没找到，我这边使用方关注流向，所以要带箭头

**Comment by charlse-Li** [comment]
> 
你好，下载这个代码后，本地运行不显示，是什么愿意？谢谢

**Comment by charlse-Li** [comment]
> 试试使用 echarts-gl 中的 graphGL 组件 https://echarts.apache.org/examples/zh/editor.html?c=graphgl-npm-dep&gl=1&theme=dark

你好，下载这个代码后，本地运行不显示，是什么愿意？谢谢
