### ISSUE TITLE
How to create a new chart example for Echarts project?

### ISSUE THREAD

**Issue by ruxf** [apache/echarts#14193]
I have some useful chart example with source code, how can I to contribute to the Echarts project?

**Comment by plainheart** [comment]
Hi, glad to see you are willing to contribute fantastic examples! I think you can contribute to [Gallery](https://www.makeapie.com) or make pull requests to `echarts-examples` repo and ping our maintainers to determine if they should be added to the example website.

**Comment by ruxf** [comment]
> Hi, glad to see you are willing to contribute fantastic examples! I think you can contribute to [Gallery](https://www.makeapie.com) or make pull requests to [echarts-examples](https://github.com/apache/echarts-examples) repo and ping our maintainers to determine if they should be added to the example website.

OK, thanks
