### ISSUE TITLE
Funnel chart, tooltip, when moving between modules, there is a feeling of freezing

### ISSUE THREAD

**Issue by ntscshen** [apache/echarts#14204]
### Version
v5.0.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=funnel](https://echarts.apache.org/examples/zh/editor.html?c=funnel)

### Steps to reproduce
The default situation of the official website, I am not sure whether the interaction design is like this, I think it is an experience problem

### What is expected?
Silky 

### What is actually happening?
Caton

**Comment by plainheart** [comment]
Seems related to #13680, it should be enhanced in [5.1.0](https://github.com/apache/echarts/milestone/19).
