### ISSUE TITLE
还支持词云吗

### ISSUE THREAD

**Issue by romanCy** [apache/echarts#14209]
### What problem does this feature solve?
词云图形

### What does the proposed API look like?
期望一个词云type

**Comment by plainheart** [comment]
词云是作为 ECharts 的一个扩展插件提供的，参见：https://github.com/ecomfe/echarts-wordcloud

**Comment by romanCy** [comment]
感谢

> 词云是作为 ECharts 的一个扩展插件提供的，参见：https://github.com/ecomfe/echarts-wordcloud
