### ISSUE TITLE
Allow child nodes to have multiple parents on tree chart

### ISSUE THREAD

**Issue by raemounz** [apache/echarts#14203]
### What problem does this feature solve?
Currently, the framework only allows "name" and "children" to structure the tree.  However, there are cases that some children can have multiple parent.  The only way to show this relationship is to let the child appear twice (or many times depending on how many parents it has).  If the tree allow multiple parents for children, then the children won't have to appear many times in the chart.  Instead, the line from a child will just have to point to multiple parents.  That's how a true dendrogram should be.

### What does the proposed API look like?
Instead of just having "name" and "children", please include an "id".  This id should allow children to attach to multiple parents.

**Comment by Ovilia** [comment]
"Tree" data structure doesn't allow multiple parents. You should use "graph" in this case.

**Comment by raemounz** [comment]
But "graph" does not support hierarchical.  Also, the circular option will only align all nodes in circular.  There's no support for n-level circular graph.

**Comment by Ovilia** [comment]
Set the layout to be "none" and set x and y position for each node.

**Comment by aradys-intel** [comment]
I am also having the same issue. My graph has about 1000 nodes and 2000 edges and I don't know how to calculate x and y for every node. Is there any example on how to do it?

**Comment by c3-aswaney** [comment]
+1 on this functionality. I agree that a "Tree" structure conceptually doesn't allow multiple parents but managing the x/y coordinates for every node, specially when dynamically adding nodes, is cumbersome. Allowing a "Tree" graph to share child nodes/leaves seems like the path of least resistance here but a 'hierarchy' layout option for a graph would also accomplish this.

**Comment by jafetbjarkar** [comment]
+1 for me as well. Seems like an unnecessary limitation by the Highcharts team. Even though tree branches don't usually grow back together we are all pretty used to this when talking about Git branches.

**Comment by frainfreeze** [comment]
+1 here as well. @Ovilia is there any hope on this?
