### ISSUE TITLE
Bar chart overlapping after adding barwidth 

### ISSUE THREAD

**Issue by pradeepgorule** [apache/echarts#14200]
### Version
5.0.1

### Steps to reproduce
Group Bar chart groups are overlapping with each other after setting a barwidth

### What is expected?
Group Bar chart groups do not overlap with each other

### What is actually happening?
Groups are overlapping after setting a barwidth

---
Kindly check the below code and  image
`
option = { dataZoom: [ { "type": "slider", "show": true } ], color: ['#003366', '#e5323e'], legend: { data: ['Forest', 'Desert'] }, xAxis: [ { type: 'category' } ], yAxis: [ { type: 'value' } ], series: [ { name: 'Forest', type: 'bar', barGap: 0, barWidth: 30, data: [["2017-05-26T00:00:00.000Z",320], ["2017-05-25T00:00:00.000Z",340], ["2017-05-24T00:00:00.000Z",310], ["2017-05-23T00:00:00.000Z",320], ["2017-05-22T00:00:00.000Z",340], ["2017-05-21T00:00:00.000Z",310]] }, { name: 'Desert', type: 'bar', barWidth: 30, data: [["2017-05-26T00:00:00.000Z",240], ["2017-05-25T00:00:00.000Z",320], ["2017-05-24T00:00:00.000Z",315], ["2017-05-23T00:00:00.000Z",240], ["2017-05-22T00:00:00.000Z",320], ["2017-05-21T00:00:00.000Z",315]] }, { name: 'Forest', type: 'bar', barWidth: 30, data: [["2017-05-26T00:00:00.000Z",320], ["2017-05-25T00:00:00.000Z",340], ["2017-05-24T00:00:00.000Z",310], ["2017-05-23T00:00:00.000Z",320], ["2017-05-22T00:00:00.000Z",340], ["2017-05-21T00:00:00.000Z",310]] }, { name: 'Desert', type: 'bar', barWidth: 30, data: [["2017-05-26T00:00:00.000Z",240], ["2017-05-25T00:00:00.000Z",320], ["2017-05-24T00:00:00.000Z",315], ["2017-05-23T00:00:00.000Z",240], ["2017-05-22T00:00:00.000Z",320], ["2017-05-21T00:00:00.000Z",315]] } ] };
`
![gitbar](https://user-images.githubusercontent.com/31239579/106730770-b96a0e00-6634-11eb-9d5f-d16f47cf4544.png)

**Comment by Ovilia** [comment]
I didn't see overlap. Please create an online demo.
