### ISSUE TITLE
Blur is not working in custom series

### ISSUE THREAD

**Issue by Clarkkkk** [apache/echarts#14215]
### Version
5.0.1

### Reproduction link
[https://jsfiddle.net/5y6zdrkf/](https://jsfiddle.net/5y6zdrkf/)

### Steps to reproduce
hover on a bar triggers emphasis effect, but no blur effect on other bars.

### What is expected?
blur style is applied on other bar

### What is actually happening?
no blur effect

---
In addition, is there any relation among `blur`, `emphasis` and `highlight`? Because I notice that there is a [commit](https://github.com/apache/echarts/pull/12925/commits/19bc67554e0dbb456e6abac2f3d9a7264ecea6c1) that support blurring when highlight through dispatchAction. 

After trying, I discover that the `highlight` event is dispatched when hovering a legend, and emphasis and blur effect occurs on data items. When hovering on a data item, there is no `highlight` event dispatched, but emphasis and blur effect still works. Can I say that a highlight event lead to emphasis state, but emphasis state does not require a highlight event?

Anyway, for custom series, it is almost the same, with the exception that blur effect doesn't work, with or without calling `dispatchAction('highlight',  ...)`.

**Comment by pissang** [comment]
Sorry it's an error of doc. the `focus` is not in the emphasis object.
```js

        focus: 'self',
        emphasis: {
          style: {
            fill: 'blue'
          }
        },
        blur: {
          style: {
            fill: '#888'
          }
        },
        select: {
          style: {
            fill: 'red'
          }
        }
```

**Comment by Clarkkkk** [comment]
Thank you. It works perfectly now.
