### ISSUE TITLE
Cannot load your website

### ISSUE THREAD

**Issue by EightArmCode** [apache/echarts#14213]
### Version
?

### Steps to reproduce
Can't load the website: http://echarts.apache.org/

Not really sure where to report this. I'm using a fully modern version of chrome. Turned off my VPN. Tried it in incognito mode. Tried it in Firefox.

### What is expected?
The website will load

### What is actually happening?
The website does not load

**Comment by plainheart** [comment]
Any error information in console?

**Comment by gregdeane** [comment]
It's working well for me at the moment.
