### ISSUE TITLE
Treemap has wrong hover color when a previous data was removed

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#14217]
### Version
5.0.1

### Reproduction link
[https://codepen.io/Ovilia/pen/YzpwxXX](https://codepen.io/Ovilia/pen/YzpwxXX)

### Steps to reproduce
1. setOption with two treemap data items
2. setOption and remove the bigger data item
3. hover on the rest item and check the hovering color

### What is expected?
Wait for 2 minutes and hover the treemap. The color is wrong. 

### What is actually happening?
It should be blue instead of green.

**Comment by susiwen8** [comment]
I think this was fixed in `5.1.2`

**Comment by Ovilia** [comment]
@susiwen8 Thanks!
