### ISSUE TITLE
Typescript definition for toolbox.feature.magicType.type is missing 'tiled'

### ISSUE THREAD

**Issue by cl1ck** [apache/echarts#14223]
### Version
5.0.1

### Steps to reproduce
```
import { EChartsOption } from 'echarts';

const option: EChartsOption = {
  toolbox: {
    feature: {
      magicType: {
        type: ['stack', 'tiled'],
      },
    },
  },
};
```

### What is expected?
No typescript error.

### What is actually happening?
Fails with
TS2322: Type '{ feature: { magicType: { type: ("stack" | "tiled")[]; }; }; }' is not assignable to type 'ToolboxComponentOption | ToolboxComponentOption[] |undefined'.   
The types of 'feature.magicType.type' are incompatible between these types.     
Type '("stack" | "tiled")[]' is not assignable to type '("line" | "bar" | "stack")[]'.       
Type '"stack" | "tiled"' is not assignable to type '"line" | "bar" | "stack"'.         
Type '"tiled"' is not assignable to type '"line" | "bar" | "stack"'.

**Comment by plainheart** [comment]
`stack` and `tiled` have been combined into a toggle button for a long time. The related document may need to be updated.
