### ISSUE TITLE
图例是否支持一行显示固定个数，而不是放不下才折行显示

### ISSUE THREAD

**Issue by genggs** [apache/echarts#14225]
### What problem does this feature solve?
图例是否支持一行显示固定个数，而不是放不下才折行显示

### What does the proposed API look like?
图例是否支持一行显示固定个数，而不是放不下才折行显示

**Comment by Ovilia** [comment]
在 legend.data 中添加一个空的 `''` 可以换行

**Comment by genggs** [comment]
好的，我试试，多谢
