### ISSUE TITLE
v5.0.1, echarts.use() , typescript type not exported, Is there a type export plan？

### ISSUE THREAD

**Issue by duanjiuzhou** [apache/echarts#14221]
### Version
5.0.1

### Steps to reproduce
**path**  ./types/dist/echarts.d.ts

code

```
declare function use(ext: EChartsExtensionInstaller | EChartsExtension | (EChartsExtensionInstaller | EChartsExtension)[]): void;
```

### What is expected?
The following types are  exported

`EChartsExtensionInstaller | EChartsExtension | (EChartsExtensionInstaller | EChartsExtension)[])`

### What is actually happening?
The following types are not exported, affecting my code type definition

**Comment by pissang** [comment]
You can use `type EChartsExtensionInstaller  = Parameters<typeof use>[0] & Function` as a workaround.

**Comment by duanjiuzhou** [comment]
This can indeed be solved by Parameters, Thank you.
