### ISSUE TITLE
希望能出一个柱状堆叠面积图

### ISSUE THREAD

**Issue by CodeFly16** [apache/echarts#14226]
### What problem does this feature solve?
目前柱状图只支持堆叠图，但是无法在堆叠的情况，添加堆叠面积功能

### What does the proposed API look like?
series-bar.areaStyle

![image](https://user-images.githubusercontent.com/61872730/107052519-b7f13f00-6808-11eb-9573-c4a3e28d83e8.png)

**Comment by Ovilia** [comment]
I made this demo with bar series: https://echarts.apache.org/examples/en/editor.html?c=bar-stack-normalization-and-variation
