### ISSUE TITLE
饼图标签不显示，特例

### ISSUE THREAD

**Issue by wuiiao** [apache/echarts#14229]
### Version
5.0.1

### Steps to reproduce
打开官网的任一示例，编辑器内的配置如下：
option = {
    series: [{
        name: '访问来源',
        type: 'pie',
        data: [
            {value: 207.16, name: '搜索引擎'},
            {value: 30.07, name: '直接访问'},
            {value: 184.41, name: '邮件营销'},
            {value: 25.53, name: '联盟广告'},
            {value: 4.45, name: '视频广告'},
        ]
    }]
};

### What is expected?
饼图显示所有对应的标签

### What is actually happening?
其中邮件营销的标签没有显示

---
改变value值，或者改变data的排序就可以显示

**Comment by susiwen8** [comment]
Duplicate with #13938, fixed by #14108, released in 5.0.2
