### ISSUE TITLE
饼图标签不显示，特例

### ISSUE THREAD

**Issue by wuiiao** [apache/echarts#14228]
在官网的编辑器,版本是"5.0.1"
option = {
    series: [
        {
            name: '访问来源',
            type: 'pie',
            data: [
                {value: 207.16, name: '搜索引擎'},
                {value: 30.07, name: '直接访问'},
                {value: 184.41, name: '邮件营销'},
                {value: 25.53, name: '联盟广告'},
                {value: 4.45, name: '视频广告'},
            ]
        }
    ]
};
其中就 邮件营销 的不显示label。 改变value值，或者改变data的排序就可以显示。 这是bug吗

**Comment by pissang** [comment]
5.0.2 中修复了该问题
