### ISSUE TITLE
legend.formatter need more variables, such as value，percentage， etc.

### ISSUE THREAD

**Issue by mu-yu** [apache/echarts#14231]
### What problem does this feature solve?
I have a pie chart , which render with no label. I'd like show each part of data in legend.

### What does the proposed API look like?
just like tooltip formatter.

**Comment by Ovilia** [comment]
Theoretically, legend should not contain the information like value or percentage. Is there any particular reason for this?

**Comment by mu-yu** [comment]
something like this:
1. I have to draw a pie-chart in a rectangle, and I want the pie as big as possible at left of the rectangle, so there is no place for label. Put value or percentage at legend is an alternative.
2. values in legend can help me to decide which one to show if I want to filter some data by values.

**Comment by Ovilia** [comment]
In this case, you need to set the name of the data and legend data to contain percentage information. We do not have plan to support such formatters, at least for now.

**Comment by mu-yu** [comment]
OK,then I'll close the issue

**Comment by hi-hai** [comment]
If legend can allow formatters like percentage, will be helpful.

**Comment by ganeshksp** [comment]
Legend data allows formatting but it is not straight forward.
var option = {
  //...
  legend: {
    formatter: name => {
      var series = myChart.getOption().series[0];
      var value = series.data.filter(row => row.name === name)[0].value
      return name + '    ' + value;
    },
  }
}

prefer below for complete solution.
https://stackoverflow.com/questions/61386291/echart-configuration-for-pie-legends-in-a-particular-way
