### ISSUE TITLE
5.0.2 markLine label 被series遮挡

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14232]
### Version
5.0.2

### Steps to reproduce
5.0.2： http://jsfiddle.net/bzcrs90f/
4.8.0： http://jsfiddle.net/aqenjmoz/

### What is expected?
5.0.2 markline的label不会被series图形遮挡

### What is actually happening?
5.0.2 markline 的label 被series图形遮挡

**Comment by susiwen8** [comment]
duplicate with #14190

**Comment by susiwen8** [comment]
Could you close this, since it's duplicate, we can track this issue in #14190
