### ISSUE TITLE
Render tooltip with user defined functions.

### ISSUE THREAD

**Issue by madlee** [apache/echarts#14236]
### What problem does this feature solve?
I wish to show chemical structure / latex formula or some other complex content in a tooltip canvas. 
I have the function (based on zrender) to draw these objects and I wish there is an API hooker to help me.
An extra AJAX request may be required to fetch the more data during the render.

### What does the proposed API look like?
```
tooltip: {
    size: [150, 50], // The tooltip size prepared for render
    onRender: function (
        data,       // The data of the selected point
        render,     // The echart/zrender object to draw on
        boundRect   // The bound rectangle to draw in
    ) {
        axios.get("/some.api?id="   data["id"]).then(function (response) {
            // Do some drawing code here.
        })
    }
}
```

**Comment by plainheart** [comment]
Does [tooltip.formatter callback](https://echarts.apache.org/en/option.html#tooltip.formatter) work for you? 

![image](https://user-images.githubusercontent.com/26999792/107149841-eea89000-6995-11eb-93dc-86aa2224c281.png)

**Comment by madlee** [comment]
> Does [tooltip.formatter callback](https://echarts.apache.org/en/option.html#tooltip.formatter) work for you?
> 
> ![image](https://user-images.githubusercontent.com/26999792/107149841-eea89000-6995-11eb-93dc-86aa2224c281.png)

Yes. It works. Thank you.
