### ISSUE TITLE
将百度地图引入Echarts后，如何尽可能小的设置zoom，让地图全局显示

### ISSUE THREAD

**Issue by weiwFu** [apache/echarts#14248]
### What problem does this feature solve?
我设置zoom为4以下的值时，好像就失效了，但是我想要世界地图的全局展示，而不是某一部分，有没有相关参数是我没有找到的

### What does the proposed API look like?
我设置zoom为4以下的值时，好像就失效了，但是我想要世界地图的全局展示，而不是某一部分，有没有相关参数是我没有找到的

**Comment by plainheart** [comment]
ECharts 百度地图扩展用法和百度地图一样，任何疑问都可以查阅百度地图文档或向百度地图提起工单咨询，百度地图的最小级别似乎现在是 4 级，虽然文档是写可以到 3 级。
