### ISSUE TITLE
Confidence bands disappear when they overlap the ends of y axis with toolbox enabled

### ISSUE THREAD

**Issue by Braffolk** [apache/echarts#14251]
### Version
5.0.2

### Reproduction link
[https://pastebin.com/1TactHtX](https://pastebin.com/1TactHtX)

### Steps to reproduce
Paste the pastebin code here: https://echarts.apache.org/examples/en/editor.html?c=line-simple

setting min and max on the yAxis with toolbox enabled so that it nears confidence bands makes the confidence bands either partially or wholly disappear. setting toolbox.show to false does not get rid of the issue. Removing it entirely from option does the job.

### What is expected?
The confidence bands are rendered properly inspite of the toolbox and min/max values.

### What is actually happening?
The confidence bands are partially or wholly disappearing.

**Comment by Ovilia** [comment]
Seems to be a bug of clipping.

**Comment by Braffolk** [comment]
Hello,
has this been looked into? This doesn't only break confidence bands, but also breaks area charts.

**Comment by Braffolk** [comment]
I tested this issue in the most recent echarts version and it has been fixed.
