### ISSUE TITLE
x轴scale和max和min配置项冲突/xAxis scale can't start and end at chart edge,because it conflict with start and end configuration item

### ISSUE THREAD

**Issue by flameWWW** [apache/echarts#14269]
### What problem does this feature solve?
I need use xAxis type with value,and I need to start and end at chart edge,but if I use start and end configuration item,It's value if more than 0, xAxis start at 0, If I use scale configuration item,it can't start and end at edge.
![image](https://user-images.githubusercontent.com/48742195/107839946-08106880-6dea-11eb-8f9f-a363fd7a7638.png)
this is scale, not start at begin edge,
![image](https://user-images.githubusercontent.com/48742195/107839999-5160b800-6dea-11eb-9563-953dc43c5265.png)
this is use max and min.
![image](https://user-images.githubusercontent.com/48742195/107840043-748b6780-6dea-11eb-819e-fb009f673b10.png)
I hope this effect when xAxis value more than 0，
### What does the proposed API look like?
 I hope scale not conflict with start and end configuration item.

**Comment by pissang** [comment]
This option may meet your purpose https://echarts.apache.org/en/option.html#yAxis.scale if I understand your issue correctly.
