### ISSUE TITLE
Time Axis is display can overlap in v5

### ISSUE THREAD

**Issue by qortex** [apache/echarts#14266]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2)

### Steps to reproduce
Go to official example and reduce the window size. Then x axis labels will overlap and look crappy.

### What is expected?
The ticks should gently disappear to let only a few appear.

### What is actually happening?
Labels overlap and look crappy.

Example on my app:
![image](https://user-images.githubusercontent.com/37897072/107814606-7a456680-6d72-11eb-9481-38122ab6ca77.png)

Example in the official example:
![image](https://user-images.githubusercontent.com/37897072/107814706-9fd27000-6d72-11eb-8b73-827499e4b742.png)

---
Worked well in v4 (see https://echarts.apache.org/v4/examples/en/editor.html?c=dynamic-data2)

**Comment by qortex** [comment]
It looks like setting `splitNumber` to 5 is a workaround as far as I can tell (even though it's supposed to be the default according to the doc?)

**Comment by tmtron** [comment]
Unfortunately the workaround (setting [xAxis.splitNumber](https://echarts.apache.org/en/option.html#xAxis.splitNumber) to 5) does not work for me: see this [example](https://jsfiddle.net/tmtron/2apkvgwy/10/)

Quote from the `splitNumber` docs:   
>Note that this number serves **only as a recommendation**, and the true segments may be adjusted based on readability.

So I tried [xAxis.interval](https://echarts.apache.org/en/option.html#xAxis.interval):  
>**Compulsively** set segmentation interval for axis.  
As splitNumber is a recommendation value, the calculated tick may not be the same as expected. In this case, interval should be used along with min and max to compulsively set tickings.

But this does also not work

Also [xAxis.axisLabel.interval](https://echarts.apache.org/en/option.html#xAxis.axisLabel.interval) had no effect.

Any idea why this is not working in my example?

**Comment by pissang** [comment]
I think interval breaks in the new time axis. We will fix it in the later versions.

**Comment by szilard-dobai** [comment]
Any news on this bugfix? :)

**Comment by svedova** [comment]
We'd like to use the upgraded version at GitLab however this bug is a blocker for us. I'd like to help and submit a PR. Is there any link to any discussion @pissang, where I could have more insight on where to look? 

Seems like this happens mostly with the Time based labels and it seems like the day/month are not evenly spaced:

![image](https://user-images.githubusercontent.com/3321893/128190316-c61495b7-9c57-4fe8-a4ea-21faa2a5f420.png)

If you check here, the left space between `July` and `29` is not the same as `July` and `8` in the X axis. Can this be related?

**Comment by pissang** [comment]
@svedova Hi, Thanks for helping fix it. There is a helper function that can hide the overlapped labels.

https://github.com/apache/echarts/blob/master/src/label/labelLayoutHelper.ts#L289

The `labelList` parameters can be prepared by the helper function `prepareLayoutList ` in the same file. What you need is to give a list with `label` and `priority` in each item. For better display. The priority of each label should be:

year > month > day > hour > minutes > second > millesecond

**Comment by svedova** [comment]
@pissang thanks for the help! 

At which state am I supposed to use the `prepareLayoutList` function?  

Initially I thought I would alter the `Time.ts` file but as far as I can tell, all it does is to return a list of string labels when `getLabel` and `getFormattedLabel` is called. When I trace the call stack, it seems like `AxisBuilder.ts` creates a list of `ZRText`s here: https://github.com/apache/echarts/blob/master/src/component/axis/AxisBuilder.ts#L342

Is it a good place to use the `prepareLayoutList` and `hideOverlap` helpers?

Another question, `prepareLayoutList` expects a few more properties than `label` and `priority` (ref: https://github.com/apache/echarts/blob/master/src/label/labelLayoutHelper.ts#L25). How do I populate the other properties?  

Unfortunately there are not many examples in the codebase using these two helpers (only the `LabelManager` seems to use them), so a little help would be highly appreciated here 🙏

**Comment by pissang** [comment]
@svedova Sorry for the late reply.

Usually, `prepareLayoutList` and `hideOverlap` are called when all labels are created and prepared, prepared means all properties like transform, font are set so the method can get the correct oriented bounding rect. For axis, I think it can be https://github.com/apache/echarts/blob/master/src/component/axis/CartesianAxisView.ts#L102 

Some properties of `prepareLayoutList` are optional. The type has some issue here, it should be:
```ts
interface LabelLayoutListPrepareInput {
    label: ZRText
    labelLine?: Polyline
    computedLayoutOption?: LabelLayoutOption
    priority: number
    defaultAttr: {
        ignore: boolean
        labelGuideIgnore?: boolean
    }
}
```

`defaultAttr.ignore` can use `label.ignore` here.
