### ISSUE TITLE
Show/hide MarkArea from echarts configuration

### ISSUE THREAD

**Issue by AmitBisht14** [apache/echarts#14264]
### Version
5.0.2

### Steps to reproduce
Is there any way to show/hide markArea of echart, such that if set True Chart will show markArea for whole chart for all series and vice-versa. Similar thing is happening for series show/hide from legend a user can show/hide, One way around is to do it with opacity but I feel there must be something more prominent

### What is expected?
There should be a option to show hide markArea

### What is actually happening?
No Option present in eChart

**Comment by plainheart** [comment]
Perhaps, you could try to set it as follows,
```js
chart.setOption({
    series: [{
        markArea: {
            // set markArea to be an empty array if invisible
            data: visible ? markAreaData : []
        }
    }]
})
```

**Comment by AmitBisht14** [comment]
@plainheart yes this is the way but it is specific for a single series. What expected is to have a option which get applied for all the series

**Comment by plainheart** [comment]
In fact, we can control the visibility of each specific series in a common function. The requirement is to specify an `id` or `name` for each series. But it may look a bit complex.

Just like this, https://www.makeapie.com/editor.html?c=xmjU8U_2bN&v=1

**Comment by AmitBisht14** [comment]
> In fact, we can control the visibility of each specific series in a common function. The requirement is to specify an `id` or `name` for each series. But it may look a bit complex.
> 
> Just like this, https://www.makeapie.com/editor.html?c=xmjU8U_2bN&v=2

@plainheart  the link is not working

**Comment by plainheart** [comment]
@AmitBisht14 Do you mean the link can't be opened or can't solve your requirement?

**Comment by AmitBisht14** [comment]
@plainheart not able to access the link, it is not reachable

**Comment by plainheart** [comment]
@AmitBisht14 Hi, I moved it to CodePen, here is the new link: https://codepen.io/plainheart/pen/jOBOmrE
