### ISSUE TITLE
Typescript error on using callback for itemStyle.color

### ISSUE THREAD

**Issue by sthenault** [apache/echarts#14279]
### Version
5.0.2

### Steps to reproduce
Use a callback function for itemStyle.color as documented leads to a compilation error. E.g.

                itemStyle: {
                    color: (param: any) => data[param.dataIndex].color,
                },

### What is expected?
no compilation error. 

### What is actually happening?
typescript complains:

      Type '(param: any) => string' is not comparable to type 'ZRColor'.
        Type '(param: any) => string' is missing the following properties from type 'PatternObject': type, image, svgElement, svgWidth, and 2 more.

---
Bonus point for exposing a type for 'params' better than Object.

**Comment by thep0y** [comment]
As of today, 7 months have passed and this bug has not been solved yet
