### ISSUE TITLE
Custom font family horizontal legend overlap

### ISSUE THREAD

**Issue by GeniusWiki** [apache/echarts#14272]
### Version
5.0.2

### Steps to reproduce
Add google font Roboto and set textStyle:{fontFamily: "Roboto"}.  The text font can display correctly. However, the horizontal legend text has overlap.  I assume it is because the legend text width is calculated by default font "sans serif" but Roboto has wider letter width.

Google Font: 
```
<link rel="preconnect" href="https://fonts.gstatic.com"> 
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
```

### What is expected?
Legend has correct item gap

### What is actually happening?
The legend text overlapped.

**Comment by plainheart** [comment]
Would you mind providing an online demo or some screenshots for us? Thanks.

**Comment by GeniusWiki** [comment]
@plainheart Thank you for quick response. Here is the demo: https://codepen.io/rob_edgenius/pen/OJbmQyq. It is Roboto font.  The middle legend is overlapped by the third legend block.

**Comment by plainheart** [comment]
Seems normal for me?

![image](https://user-images.githubusercontent.com/26999792/108204526-dfc49900-715e-11eb-893b-bd7e24688d79.png)

**Comment by GeniusWiki** [comment]
Does it rely on OS? I am on Mac. 

<img width="728" alt="Screen Shot 2021-02-17 at 11 33 53 pm" src="https://user-images.githubusercontent.com/1058110/108205120-bfa1d380-7178-11eb-9f86-ce28557a70a2.png">

**Comment by GeniusWiki** [comment]
It seems worse in a server side puppeteer render (could be a Linux based OS).  

<img width="969" alt="Screen Shot 2021-02-17 at 11 42 15 pm" src="https://user-images.githubusercontent.com/1058110/108205987-e44a7b00-7179-11eb-8b3a-bc57f2e36494.png">

**Comment by plainheart** [comment]
This should be a problem that need to look into it. Thanks for providing so much useful information.

**Comment by plainheart** [comment]
@pissang Please help check it.

**Comment by GeniusWiki** [comment]
I think I found the issue and solution. It is because of the web font loading.  The chart is rendered before the font is loaded.  I put it in webfont callback and the problem is solved. Here is demo of fix: https://codepen.io/rob_edgenius/pen/bGBWXpv

I think it is worth put a note somewhere in your document or FAQ. 

Thank you again for your quick response.

**Comment by plainheart** [comment]
Great job! Thank you for sharing the solution!
