### ISSUE TITLE
Treemap: Labels displayed in treemap not visible because of colour of blocks.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/echarts#14273]
### Version
4.2.1

### Steps to reproduce
1. Execute treemap.
2. Check the labels in treemap block. Labels not visible because of the color of the block.

### What is expected?
-  Labels text should visible. labels should display in color depends on treemap block color.

### What is actually happening?
1. Labels not visible because of block color.
 - By default, the color of the label text is white.
 - If treemap block color also white or near to white, label text not visible.

- For example, if we change text colour to lighter colour it will cause problem when shade is with white base and on contrast it will be a problem if colour is shade is dark and text too.. 

Please find the attachmen

**Comment by Monali-ITT** [comment]
please find the attachemnt..where I used white color for label text..the text is not visible in while color box.
![ac95d5d9-cd0a-4d64-ad47-9c62a2a6113a](https://user-images.githubusercontent.com/52197143/108032905-2fb93800-7059-11eb-9bac-d1e8d5e89d11.png)

**Comment by chenxueling** [comment]
Is there a solution to this problem of not displaying the label?
