### ISSUE TITLE
ECharts Sankey: Labels are hidden under lines with line emphasis

### ISSUE THREAD

**Issue by joshuacassidygrant** [apache/echarts#14287]
### Version
5.0.0

### Reproduction link
[https://jsfiddle.net/ed6cq5yj/1/](https://jsfiddle.net/ed6cq5yj/1/)

### Steps to reproduce
Once loaded, hover over the link between node1 and node2;
The label for node2 will be partially obscured by the emphasized link.

### What is expected?
The label should remain above the link.

### What is actually happening?
The label is partially cut off.

---
If this is intended behaviour, it would be nice to have an option to force labels to render above lines on emphasis.

**Comment by joshuacassidygrant** [comment]
Note this wasn't an issue in echarts ~4

**Comment by krvajal** [comment]
Looking forward to have this fixed. Is there anything I can help please let me know.
