### ISSUE TITLE
官网文档疑问

### ISSUE THREAD

**Issue by yang201806** [apache/echarts#14284]
原先反应官网文档没有属性的版本支持，得到的回复  ：
目前已有此标注，例：https://echarts.apache.org/zh/option.html#tooltip.className

————————————————————
但是：
有些属性还是没有说明，我应该怎么知道它是从哪个版本开始有的，例如：
https://echarts.apache.org/zh/option.html#series-line.endLabel

**Comment by plainheart** [comment]
如果发现有些新增配置项没有标注版本信息，可以开个 issue 反馈一下，谢谢。
