### ISSUE TITLE
Feature request: create bar chart with layer.

### ISSUE THREAD

**Issue by GeniusWiki** [apache/echarts#14280]
### Version
5.0.2

### Steps to reproduce
I need create a bar chart and the bar has a layer.
![Screen Shot 2021-02-18 at 3 25 12 pm](https://user-images.githubusercontent.com/1058110/108305446-18677f80-71fe-11eb-8173-5a8bc92f3e8f.png)

After google,  I made an example, but far from perfect: https://codepen.io/rob_edgenius/pen/WNoObxy

### What is expected?
The layer and bar in middle alignment, the X axis (if vertical bar) labels need to be centre alignment either. 
There is no interactive in layer, i.e, don't need to response mouse hover event

### What is actually happening?
It is hard to use barGap to align 2 bar in middle alignment.  I don't figure out the formula for that yet, just test a number 83% if bar width is 60% and 40%. 
The x axis label are not aligned in the centre of bar. 
The layout pops to override the bar when mouse hovers.

**Comment by Ovilia** [comment]
A simpler way would be to use two `grid` at the same position and two `xAxis` and `yAxis` for each. Then, move one of the series to the second grid. This way, you don't need to set `barGap` at all.
You may refer to [this example](https://echarts.apache.org/examples/en/editor.html?c=line-gradient) for `grid`, `xAxis` and `yAxis` settings. You also want to set the `left`, `top`, `width`, `height` to be the same value for the two grids.

Set `series.silent` to be `true` if you don't want the interaction of it.
