### ISSUE TITLE
配置项series.data数组里如果同时存在null和对象,将会报错Cannot read property 'selected' of null

### ISSUE THREAD

**Issue by lvding** [apache/echarts#14293]
### Version
5.0.2

### Steps to reproduce
非连续的折线图/柱状图,在3.x和4.x版本时,
series.data可以用类似[null,{value:3},{value:4},null]这样的数组呈现,而在5.x版本时候必须使用[{value:null},{value:3},{value:4},{value:null}]
否则将会报错Cannot read property 'selected' of null

### What is expected?
正常呈现非连续的折线图

### What is actually happening?
报错Cannot read property 'selected' of null

**Comment by leosxie** [comment]
i will try to pr this issue

**Comment by jonavila** [comment]
I ran into this issue in 5.x and I believe it's caused by this method of Series.ts


```
private _initSelectedMapFromData(data: List) {
        // Ignore select info in data if selectedMap exists.
        // NOTE It's only for legacy usage. edge data is not supported.
        if (this.option.selectedMap) {
            return;
        }

        const dataIndices: number[] = [];
        if (data.hasItemOption) {
            data.each(function (idx) {
                const rawItem = data.getRawDataItem(idx);
                if (typeof rawItem === 'object'
                    && (rawItem as OptionDataItemObject<unknown>).selected
                ) {
                    dataIndices.push(idx);
                }
            });
        }

        if (dataIndices.length > 0) {
            this._innerSelect(data, dataIndices);
        }
    }
    
```
You can see how it fails if rawItem is null because typeof null === 'object'.

Using  undefined in the value instead of null works for me as workaround.

**Comment by plainheart** [comment]
Great! Like #14404, y'all got the focus of this error. Any contribution will be much appreciated!
