### ISSUE TITLE
如何给拖拽手柄添加点击事件？

### ISSUE THREAD

**Issue by realkimmy** [apache/echarts#14296]
### Version
5.0.0

### Steps to reproduce
可不可以给拖拽手柄添加点击事件？如果可以的话，需要更改源代码中的哪些文件？

### What is expected?
给拖拽手柄添加点击事件

### What is actually happening?
拖拽手柄不能添加点击事件

**Comment by realkimmy** [comment]
我修改的echarts源代码，发现第一次点击handle的时候，不会触发点击事件，之后的点击就会触发点击事件
[ac4b01f005564f1326acb58c6d226eb3efdba052](https://github.com/topgames-release/echarts/commit/ac4b01f005564f1326acb58c6d226eb3efdba052)

**Comment by snowyang2021** [comment]
请问下，怎么实现的呀？

**Comment by realkimmy** [comment]
> 请问下，怎么实现的呀？

https://github.com/topgames-release/echarts/commits/master

**Comment by snowyang2021** [comment]
赞👍。这个修改能PR合并到echarts官网的版本么？

**Comment by realkimmy** [comment]
没有时间去弄pr的事情，还需要测试和更新文档，太繁琐了

**Comment by snowyang2021** [comment]
那我帮你啊，这个issue对我来说还挺重要的。

**Comment by WRhea** [comment]
这个有合并到版本里吗
