### ISSUE TITLE
关系图graph多节点不想让其缩放显示

### ISSUE THREAD

**Issue by zwygithub** [apache/echarts#14290]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=graph-simple](https://echarts.apache.org/examples/zh/editor.html?c=graph-simple)

### Steps to reproduce
在官网关系图的简单示例中增加一些节点，会通过缩小节点的形式将节点全部展示在展示区域

### What is expected?
我希望能在增加节点的时候，其他节点在展示区域的位置不变，通过鼠标的拖拽显示不在显示区域的节点

### What is actually happening?
节点全部展示在展示区域

---
因为数据中有时节点多，有的节点少，所以并不希望展示区域显示全貌（节点多的时候节点凑到一起）

**Comment by zwygithub** [comment]
![image](https://user-images.githubusercontent.com/29787678/108450707-9aa88000-72a0-11eb-861c-f104ee643194.png)
![image](https://user-images.githubusercontent.com/29787678/108450851-caf01e80-72a0-11eb-812d-8506cdfd1b87.png)
不希望在显示区域有节点5，而是通过鼠标拖拽看到节点5

**Comment by wf123537200** [comment]
你的意思是不是说，虽然画布里面有节点5，但是第一次绘制的时候不出现，然后通过拖拽让他显示出来~？

**Comment by zwygithub** [comment]
> 你的意思是不是说，虽然画布里面有节点5，但是第一次绘制的时候不出现，然后通过拖拽让他显示出来~？

是的，还是显示图一，节点5通过拖拽显示

**Comment by wf123537200** [comment]
我觉得这个需求可以通过业务自己实现~~

**Comment by cjlhll** [comment]
> 我觉得这个需求可以通过业务自己实现~~

怎么实现，有思路吗？echarts默认就给回显所有的节点了。
