### ISSUE TITLE
Inverted y-axis draws x-axis in wrong location

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14309]
### Version
5.0.2

### Reproduction link
[https://codepen.io/bilge-the-encoder/pen/GRNEBVj](https://codepen.io/bilge-the-encoder/pen/GRNEBVj)

![image](https://user-images.githubusercontent.com/470626/108611752-8c11b400-73d9-11eb-8586-ada3431cef63.png)

### Steps to reproduce
```js
yAxis: {
    inverse: true,
},
```

### What is expected?
Inverting the y-axis should have no effect on the x-axis.

### What is actually happening?
Even though the x-axis labels are drawn in the correct location (at the bottom of the chart), the x-axis line and ticks get moved to the top of the chart.

---
This is a pretty major bug; would appreciate fix in next release.

**Comment by Ovilia** [comment]
This is not a bug. To get what you want, set `xAxis.axisLine.onZero` to be `false`.

**Comment by Bilge** [comment]
Confirmed. Thanks @Ovilia and sorry for the false report.
