### ISSUE TITLE
关系图中无论把鼠标移动到哪个分类的图例上都会高亮固定一组节点

### ISSUE THREAD

**Issue by TheresaQWQ** [apache/echarts#14308]
### Version
5.0.2

### Steps to reproduce
官方demo中就有这个问题，链接 https://echarts.apache.org/examples/zh/editor.html?c=graph
![image](https://user-images.githubusercontent.com/22370654/108596799-43023580-73c2-11eb-8502-4ca80c92d79a.png)

### What is expected?
移动到哪个分类上就高亮哪个分类

### What is actually happening?
只高亮了固定一组节点

**Comment by susiwen8** [comment]
Duplicate with #13869
