### ISSUE TITLE
Time-based x-axis slow refresh rate v5 regression

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14307]
### Version
5.0.2

### Steps to reproduce
|v4 (smooth)|
|-|
|![](https://user-images.githubusercontent.com/470626/108594371-9dbf7100-7371-11eb-83ee-2e07e733a768.gif)

|v5 (stutter)|
|-|
|![](https://user-images.githubusercontent.com/470626/108594372-9f893480-7371-11eb-8a36-543aff907fc5.gif)

### What is expected?
When user scrolls the view, the x-axis should scroll smoothly. In v4 this was the behaviour.

### What is actually happening?
Since v5, the time-based x-axis updates very slowly while scrolling. The refresh rate of the chart in general is unaffected: the chart and the dataZoom component still update normally; only the x-axis text itself appear to update slowly.

---
### Additional observations
These two graphs have the same configuration, the only difference is the v4 and v5 engines. However, there are more behavioural differences, regarding the x-axis, than just the refresh rate.

1. We can also observe that in v4, the axis prefers to try to **keep the previous and following ticks attached** to the ends of the axis at all times, wherever possible. In v5, this does not occur: as soon as the ticks is scrolled out of view, it disappears instantly. This might be considered a good thing, but the problem is this behaviour does not seem to be configurable and simply changed due to the version upgrade. 

| v4: *Nov 2020* tick remains visible even though scrolled off |
|-|
| ![](https://user-images.githubusercontent.com/470626/108594755-b597f480-7373-11eb-9a52-f74aac0e16a9.png)

2. We can observe that in v4, the axis appears **less cluttered**, with fewer ticks. That is, v4 prefers 3-month intervals whilst v5 chooses 1-month intervals, even though both axis have `minInterval` set to 1 month (`1000 * 60 * 60 * 24 * 30`). This might be considered a good thing, since v5 is exercising its right to use the absolute minimum interval allowed, but again, this behaviour only changed due to the version upgrade and it does not seem to be configurable how cluttered the x-axis may be. For example, even though we did allow a 1-month minimum, we might only want that minimum to be used for small time ranges, such as up to 6 months, and for charts spanning several years, we might expect the library to use 2 or 3-month intervals, up to the maximum allowed (currently `maxInterval` is configured to 1 year).

**Comment by pissang** [comment]
I think it's because the animation easing is different. Please try changing animationEasingUpdate from `cubicInOut` to `cubicOut`
