### ISSUE TITLE
series.render is required

### ISSUE THREAD

**Issue by Princekk** [apache/echarts#14306]
### Version
5.0.2

### Steps to reproduce
After using the V5 version. Custom content of type= "custom" will report an error

{
  barWidth: 14
  color: {type: "linear", x: 0, y: 0, x2: 0, y2: 1, …}
  data:  [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
  degree: 1
  index: 2
  item: {name: "Rate", label: "完成率", type: "none", color: {…}, degree: 1, …}
  label: "完成率"
  name: "完成率"
  type: "custom"
  unit: "%"
  yAxisIndex: 0
}

### What is expected?
Can't find out what's wrong and hope you can help

### What is actually happening?
Uncaught Error: series.render is required.

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#series-custom.renderItem is required.

**Comment by Princekk** [comment]
Thank you very much for your reply and let me know what the problem is. My problem has been solved. Please close this issue

**Comment by DenisDong** [comment]
你好，能说一下是咋改的么
could you please introduce how to solve this problem?
I met this problem

**Comment by Joel-Turbi** [comment]
Hi @Princekk  👋

Would you mind sharing how you ended up fixing the issue? It would be really helpful for others facing the same problem with type: "custom" and the `series.render` is required error.

Thanks in advance! 🙏

Cc: @Ovilia
