### ISSUE TITLE
Inverted y-axis shades wrong line area 

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14311]
### Version
5.0.2

### Reproduction link
[https://codepen.io/bilge-the-encoder/pen/NWbvoXJ](https://codepen.io/bilge-the-encoder/pen/NWbvoXJ)

### Steps to reproduce
```js
yAxis: {
    inverse: true,
},
series: [{
    type: 'line',
    areaStyle: {},
}],
```

### What is expected?
![image](https://user-images.githubusercontent.com/470626/108620856-c81f3600-7426-11eb-88ac-b8b67855a7c9.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/470626/108620866-d5d4bb80-7426-11eb-8861-56cccba7b4dd.png)

---
May be related to #14309.

**Comment by Ovilia** [comment]
Set `xAxis.axisLine.onZero` to be `false` and `series.areaStyle.origin` to be `'end'`.

**Comment by Bilge** [comment]
Confirmed. Thanks @Ovilia and sorry for the false report.
