### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by llq124596** [apache/echarts#14318]
### Version
4.9.0

### Steps to reproduce
使用 bar3d echarts 在一个页面中过多时（大于15个？），浏览器中会出现 WARNING: Too many active WebGL contexts. Oldest context will be lost 的警告并且有些图表不能显示出来，我无法通过dispose来删除之前的 bar3d 用于阻止这个警告的出现，当这个警告超过1000条时页面会崩溃

### What is expected?
能正常删除前面的图表，阻止这个警告的出现
WARNING: Too many active WebGL contexts. Oldest context will be lost

### What is actually happening?
警告过多时页面会崩溃

**Comment by ngoc308** [comment]
@plainheart Any updates on this issue. I also deal with the issue when there are more than 15 GL series in one page.
