### ISSUE TITLE
DatasetComponent Miss report

### ISSUE THREAD

**Issue by zpinocchio** [apache/echarts#14325]
### Version
5.0.2

### Steps to reproduce
When I don't  import the DatasetComponent but use dataset in option,it don't report any error in console and nothing to plot

### What is expected?
Error: Component dataset not exists. Load it first.

### What is actually happening?
nothing

**Comment by Bilge** [comment]
I agree it would be useful to validate at least the top level keys of the options object to report any unrecognized keys. A lot of time can be wasted debugging issues like this otherwise, due to lack of error reporting.

**Comment by Ovilia** [comment]
Thanks for reporting. We will see if this can be exported in the next release.

**Comment by Ovilia** [comment]
@zpinocchio @Bilge A temperary solution is to open [an example](https://echarts.apache.org/examples/en/editor.html?c=line-markline) and paste your code to the editor. Then, choose "Full Code" at the top-left corner and enabled "Minimal Bundle" so that you can know what components to import.
