### ISSUE TITLE
visualMap 中的 itemSymbol 设置无效，需设置pieces中的symbol才能改变图元形状

### ISSUE THREAD

**Issue by dglxiaoyi** [apache/echarts#14328]
### Version
5.0.2

### Reproduction link
[ https://www.makeapie.com/editor.html?c=x1-bQDu00]( https://www.makeapie.com/editor.html?c=x1-bQDu00)

### Steps to reproduce
基于上述官网示例链接，

在visualMap中增加属性itemSymbol: 'rect', 图元形状未发生变化
在pieces每个对象中增加属性 symbol: 'rect', 图元形状发生变化

### What is expected?
能通过itemSymbol属性直接设置整体的图元形状

### What is actually happening?
只能通过pieces中的symbol逐个修改图元形状

**Comment by plainheart** [comment]
#14243 may solve this issue
