### ISSUE TITLE
pie

### ISSUE THREAD

**Issue by wellwong** [apache/echarts#14321]
### Version
5.0.2

### Steps to reproduce
正常引用

### What is expected?
正常引用

### What is actually happening?
electron引入报Cannot create property 'event' on string 'pieToggleSelect'

**Comment by wellwong** [comment]
An error is reported when the electronic project is packaged: cannot create property 'event' on string 'pietoggleselect'; normal operation is OK, and an error will be reported after packaging
![7b80fb9e057e7e73bc3f74be4b40ae6](https://user-images.githubusercontent.com/17003713/109016354-11a2a600-76f1-11eb-9666-e958da51d6c4.png)
![fb7e602cd2c8ca4e7b46d700618ad0d](https://user-images.githubusercontent.com/17003713/109016436-25e6a300-76f1-11eb-835f-ade499577880.png)

**Comment by xuzhonglin** [comment]
I have the same problem

**Comment by sg552** [comment]
I have the same problem. 

Met his error when packaging a electron-vue project.

In development , it's OK.  in production mode, this error occurs.

**Comment by sg552** [comment]
> 
> 
> An error is reported when the electronic project is packaged: cannot create property 'event' on string 'pietoggleselect'; normal operation is OK, and an error will be reported after packaging
> ![7b80fb9e057e7e73bc3f74be4b40ae6](https://user-images.githubusercontent.com/17003713/109016354-11a2a600-76f1-11eb-9666-e958da51d6c4.png)
> ![fb7e602cd2c8ca4e7b46d700618ad0d](https://user-images.githubusercontent.com/17003713/109016436-25e6a300-76f1-11eb-835f-ade499577880.png)

兄弟，这个你是如何解决的？ 谢谢

**Comment by xuzhonglin** [comment]
降级到4 就可以

**Comment by sg552** [comment]
回复太速度了！  具体的版本号是多少呢？

**Comment by xuzhonglin** [comment]
我降级到4.9.0
![image](https://user-images.githubusercontent.com/19318201/127984348-936d9fe1-07f7-4350-bcbf-ea9b4d2b3265.png)

**Comment by sg552** [comment]
哈哈，太感谢了！  666 ！

**Comment by sg552** [comment]
OK, I solved the problem.  

By experience, this messages shows when node can NOT find some module. 

The root cause in my case is the `dependency` and `devDependency`, node can not find this module. 

previously,  I put the `echarts` to the `devDependency` segment, so it got error when built package for production.
so we move it to `dependency` segement, looks like: 


```
// package.json 
"dependencies": {
    "echarts": "^5.1.2",
    ...
}
```

then everything is OK .    

also thanks to @xuzhonglin

**Comment by zhoukepeng** [comment]
Why do I still report an error when my data is originally in the dependency

**Comment by zhoukepeng** [comment]
Why do I still report an error when my data is originally in the dependency
![image](https://user-images.githubusercontent.com/105778094/172985903-a94786be-6469-4992-a65c-6ac6299fd51b.png)
