### ISSUE TITLE
在使用散点图时，cpu使用率特别高（超过100%）

### ISSUE THREAD

**Issue by mengqingtao1993** [apache/echarts#14326]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap](https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap)

### Steps to reproduce
https://echarts.apache.org/zh/option.html#series-effectScatter
使用该配置type: 'effectScatter',生成的散点图，停留在该页面无需任何操作，存在cpu消耗过大的问题（超过100%），如换做其他图，比如type: 'scatter'散点气泡图，则无该问题

### What is expected?
type: 'effectScatter',生成的散点图，希望与其他图表大致相同的cpu开销

### What is actually happening?
cpu开销过大

---
官网示例中即可发现该问题

**Comment by pissang** [comment]
该图表存在特效动画所以需要一直重绘，所以 CPU 占用率肯定会比普通静态的散点图高，但是应该也不至于到 100%（我的电脑上在 20% 左右），最好描述下你的环境以及是否对配置代码有做什么改动

**Comment by mengqingtao1993** [comment]
coordinateSystem: 'geo'，使用地理坐标系渲染的中国地图，应该是china.js的数据量比较大频繁重绘导致的，地图数据使用的老版本echarts中的数据，macOS Big Sur系统，2.6 GHz 四核Intel Core i7处理器。
我使用的不太得当，静态的散点图更合适一些，目前使用普通静态的散点图渲染了。

**Comment by pissang** [comment]
如果有用特效的散点图，可以为这个系列单独设置一个 zlevel

**Comment by wsyxl365** [comment]
> 如果有用特效的散点图，可以为这个系列单独设置一个 zlevel

亲测可行，设置了单独的zlevel后 就正常了 感谢分享

**Comment by mountain410** [comment]
> > 如果有用特效的散点图，可以为这个系列单独设置一个 zlevel
> 
> 亲测可行，设置了单独的zlevel后 就正常了 感谢分享

我设了单独的zlevel还是没用，过了一会还是飙升起来 --v5.1.1

**Comment by fcyao** [comment]
和上面一样，我设了单独的zlevel还是没用，过了一会还是飙升起来 --v5.1.1

**Comment by dream-hang** [comment]
同样复现了此问题，echarts：v5.0.2，加入effectScatter这层会导致CPU升高，设置了zlevel:1，cpu还是随着时间增长不断升高

**Comment by mountain410** [comment]
> > > 如果有用特效的散点图，可以为这个系列单独设置一个 zlevel
> > 
> > 
> > 亲测可行，设置了单独的zlevel后 就正常了 感谢分享
> 
> 我设了单独的zlevel还是没用，过了一会还是飙升起来 --v5.1.1

最终升级到版本v5.2.2解决问题，结合设置effectScatter系列 zlevel单层显示，终于解决问题。填坑结束！
ps: 看到版本记录v5.2.1有个修复原型泄漏的记录，也不知道跟这个有没有关系==

**Comment by kingyue737** [comment]
我也是更新到5.2.2就没有这个问题了
