### ISSUE TITLE
Candlestick graphs have incorrect color for open/close

### ISSUE THREAD

**Issue by nbmsv2** [apache/echarts#14338]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh)

### Steps to reproduce
Hover over first point: 
open 2,232.69
close 2,225.29

Closed at lower price (candle going down), yet the bar is green. Issue is present event if you dont specify item styling.

### What is expected?
Candles with close lower than open should be red

### What is actually happening?
Candles with close lower than open are green

**Comment by Ovilia** [comment]
Hi, please refer to https://echarts.apache.org/en/option.html#series-candlestick

> Different countries or regions have different implications on the color of candle stick chart. It may use red to imply increasing with red and decreasing with blue (in China mainland, Taiwan, Japan, Koera, and so on), or to imply increasing with green and decreasing with red (in Europe, North America, Hong Kong, Singapore, and so on). Besides color, the increase and decrease of stock may also be represented with candle stick with or without filling colors.
