### ISSUE TITLE
折线图-areaStyle.color 不支持function

### ISSUE THREAD

**Issue by ALLLRON** [apache/echarts#14334]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=area-basic](https://echarts.apache.org/examples/zh/editor.html?c=area-basic)

### Steps to reproduce
```js
option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        areaStyle: {
            color:(p)=>{
                console.log(p)
            }
        },
        itemStyle:{
            color:(p)=>{
                console.log('p1',p)
            }
        }
    }]
};
```
### What is expected?
areaStyle.color 应该能正确打印log

### What is actually happening?
itemStyle.color 支持function，并正确打印出param的值。areaStyle.color 无反应，不支持function

![image](https://user-images.githubusercontent.com/31984854/108974479-7691d800-76c0-11eb-8e2e-7778fb8d7816.png)

**Comment by Ovilia** [comment]
ECharts does not have this feature by now. May be related to #14346 14239.
