### ISSUE TITLE
树图的roam属性，只在'move'和'scale'下生效。设置true则两个功能都失效。

### ISSUE THREAD

**Issue by aha-09** [apache/echarts#14337]
### Version
5.0.1

### Reproduction link
[https://echarts.apache.org/v4/examples/zh/editor.html?c=tree-basic](https://echarts.apache.org/v4/examples/zh/editor.html?c=tree-basic)

### Steps to reproduce
加上series内加上roam: true

### What is expected?
文档：可以设置成 'scale' 或者 'move'。设置成 true 为都开启

### What is actually happening?
设置成 true 为都 不！开！启！

**Comment by plainheart** [comment]
经测试，并未失效。
