### ISSUE TITLE
Vue3项目中使用折线图出现tooltip不显示

### ISSUE THREAD

**Issue by LinsRock** [apache/echarts#14342]
### Version
5.0.2

### Reproduction link
[https://codesandbox.io/s/magical-smoke-vyigt?file=/src/components/chart.vue](https://codesandbox.io/s/magical-smoke-vyigt?file=/src/components/chart.vue)

### Steps to reproduce
1. 当我将tooltip设置成一个空对象时，tooltip显示
2. 当我给tooltip设置值时，tooltip不显示
3. 但我将相同的options复制到官方示例中，又可以正常显示tooltip，不确定是不是Vue3环境的问题
 
```
options = {
   grid: { left: 10, bottom: 20, top: 10, right: 30 },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: [11, 12, 13, 14, 15, 16, 17]
    },
    yAxis: {
      type: 'value',
      position: 'right'
      // min: 213,
      // max: 416
    },
    // tooltip: {},
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
        animation: false,
        label: {
          backgroundColor: '#ccc',
          borderColor: '#aaa',
          borderWidth: 1,
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          color: '#222'
        }
      },
      formatter: function(params: any) {
        console.log(params)
        return params.name   '：'   params.value;
      }
    },
    series: [
      {
        type: 'line',
        symbolSize: 6,
        // showSymbol: false,
        // hoverAnimation: false,
        lineStyle: {
          color: ' #76A9FF'
        },
        areaStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            {
              offset: 0,
              color: 'rgba(159, 195, 255, 0.61)'
            },
            {
              offset: 1,
              color: 'rgba(157, 194, 255, 0)'
            }
          ])
        },
        data: [312.23, 366.21, 355.21, 310.2, 370.11, 300, 360.99]
      }
    ]
}
```

### What is expected?
期望鼠标hover时可以显示tooltip

### What is actually happening?
当我给tooltip设置值时，tooltip不显示

**Comment by plainheart** [comment]
可能是 `ref` 的原因，`chartInstance` 实际上并不需要 `ref`，建议声明一个普通变量。

**Comment by LinsRock** [comment]
> 可能是 `ref` 的原因，`chartInstance` 实际上并不需要 `ref`，建议声明一个普通变量。

谢谢，还真是这个问题。一时没注意这个问题，还以为是options配置错误

**Comment by HomyeeKing** [comment]
我也遇到了这个问题，但是好像是canvas的原因，换成div元素就ok了

**Comment by SupaFan** [comment]
我用vite vue3也遇到这个问题了 保存实例的变量不要放到data里面就解决了 这具体原因是什么呢？

**Comment by YangYmimi** [comment]
本来打算用mixin将公用的一些方法提出来的。

现在data内定义的instance就当成一个缓存了。

`const dom = document.getElementById(this.dom);
      if (dom) {
        const instance = echarts.init(dom);
        if (instance) {
          this.setOption(instance);
        }
        // cache
        this.instance = instance;
      }`

**Comment by alleluya-young** [comment]
> 可能是 `ref` 的原因，`chartInstance` 实际上并不需要 `ref`，建议声明一个普通变量。

如果声明的实例变量不用ref包裹, 我这会一直有"There is a chart instance already initialized on the dom"这个warn提示 应该怎么去写判断比较好呢?

**Comment by plainheart** [comment]
@alleluya-young 这个 warn 是因为在相同的 DOM 上重复 init ECharts，不太清楚你具体是如何写的。DOM 用 `ref`，echarts 实例用普通变量或者 `shallowRef`。

**Comment by susiwen8** [comment]
感觉是不是需要在 Doc上说明一下 Vue 项目上使用的 FAQ？ 很多人问了 @plainheart

**Comment by plainheart** [comment]
@susiwen8 嗯 感觉可以

**Comment by plainheart** [comment]
@susiwen8 拿issue的例子来说，似乎只有 `trigger: axis` 时才会有问题，`trigger: item` 则不会，还需要进一步看下。

**Comment by Serendipity96** [comment]
> 可能是 `ref` 的原因，`chartInstance` 实际上并不需要 `ref`，建议声明一个普通变量。

感谢，我也遇到这个问题了

**Comment by fufuuuu** [comment]
vue3中的echart实例需要通过普通声明一个变量来保存，不然tooltip这些不是响应式的

**Comment by FrontEnd-GuoXi** [comment]
我艹   还真是这样，天坑啊

**Comment by DuranceX** [comment]
> 我也遇到了这个问题，但是好像是canvas的原因，换成div元素就ok了

还真是，换成div就好了，找了一堆解决方案都是不要用`ref`，就是没效果
