### ISSUE TITLE
legend类型不全

### ISSUE THREAD

**Issue by wsz7777** [apache/echarts#14344]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/109107452-b8785800-776c-11eb-8766-d272419732a3.png)
![image](https://user-images.githubusercontent.com/33828341/109107571-eeb5d780-776c-11eb-9f99-06555309e678.png)
![image](https://user-images.githubusercontent.com/33828341/109107595-f8d7d600-776c-11eb-9d9b-4223df51dfac.png)

**Comment by wsz7777** [comment]
ComponentOption, BoxLayoutOptionMixin, BorderOptionMixin 这几项里更不会有icon了

**Comment by wsz7777** [comment]
但是icon属性是实际生效的，请补全这个类型

**Comment by plainheart** [comment]
感谢反馈，#14263 已经添加。
