### ISSUE TITLE
how to change the height of the charts respective to the resizable panel in react

### ISSUE THREAD

**Issue by Bennajachin-Hexaware** [apache/echarts#14349]
### Version
4.7.0
![defaultSize](https://user-images.githubusercontent.com/53260515/109143605-3bf27300-7786-11eb-84b8-41f401a203c1.PNG)
![after resize](https://user-images.githubusercontent.com/53260515/109143632-4280ea80-7786-11eb-971f-27bf21e9f72c.PNG)

### Steps to reproduce
find the images

### What is expected?
Whenever I  resizing the panel and height of the chart should work respectively. I am using react echarts.

### What is actually happening?
Echarts is inside a resizable panel. When I am resizing the panel of the chart, width of the chart is getting resized accordingly but height is setting to 300px.

**Comment by pissang** [comment]
Seems the height of your container are fixed. ECharts will always use the container clientWidth and clientHeight when calling `resize`

**Comment by Bennajachin-Hexaware** [comment]
actually in my UI,  Container is a resizable panel and the height and width is 100% and container is kind of parent and echarts acts as a child once container is resized the height was default to 300px. it can't recognize or getting the height respectively but width works perfect.
