### ISSUE TITLE
在echarts5.0.2 版本中，给option的series赋值，TS编译报错

### ISSUE THREAD

**Issue by pumpkinduan** [apache/echarts#14358]
我给series赋值了一个二维数组，最内层的数组成员包含了对象和null或undefined的值，TS编译会报错，传值是按照官网的示例来的[series data](https://echarts.apache.org/zh/option.html#series-line.data.value)，如下图：
![image](https://user-images.githubusercontent.com/34852848/109263951-268d4f80-783f-11eb-8861-9e2f35f6a89b.png)

为了找出原因，我去看了相关的类型定义，发现data成员的值现在是 三种类型的值，但是我传入其他类型的值，将类型改成any后，项目还是可以跑的，**请问这个会以后有什么影响呢**？

![image](https://user-images.githubusercontent.com/34852848/109264323-c519b080-783f-11eb-8e77-4809a53e4726.png)

![image](https://user-images.githubusercontent.com/34852848/109264369-dbc00780-783f-11eb-8cfa-844d45e2bab3.png)

**Comment by pissang** [comment]
看起来 data 多嵌套了一层数组？

**Comment by pumpkinduan** [comment]
> 看起来 data 多嵌套了一层数组？

不是的，data是可以接受二维数组的，我把那个 {value: 2}这个成员去掉，就不会有ts的提示错误了，关键在于这个data只接受三种类型的值了：string | number | Date

**Comment by pissang** [comment]
data 的格式是下面这样

```ts
[
  [1, 2, 3, 4]  // 每个数据项都是一个多维数据的数组
]
```

```ts
[
  // 每个数据项是一个对象，其中 value 是包含多维数据的数组，其它属性可以是 itemStyle 设置样式，也可以是其它自己临时存放的并不是给 echarts 用的东西
  {
    value: [1, 2, 3, 4]
  }
]
```

**Comment by pumpkinduan** [comment]
> data 的格式是下面这样
> 
> ```ts
> [
>   [1, 2, 3, 4]  // 每个数据项都是一个多维数据的数组
> ]
> ```
> 
> ```ts
> [
>   // 每个数据项是一个对象，其中 value 是包含多维数据的数组，其它属性可以是 itemStyle 设置样式，也可以是其它自己临时存放的并不是给 echarts 用的东西
>   {
>     value: [1, 2, 3, 4]
>   }
> ]
> ```

**您好，很感谢您的回复!  还请在看看下面的现象**

传递的data数组格式如下图，它在5.x版本中是可以正常渲染出来的，不过ts类型会报错，也就是上面我发的图
其中，索引为 2和3的项是临时存放的对象，

![image](https://user-images.githubusercontent.com/34852848/109279658-fb155f80-7854-11eb-99be-b64930d28db6.png)

[参照官方文档](https://echarts.apache.org/zh/option.html#series-line.data.value)

```
 [
    12,
    34,
    {
        value : 56,
        //自定义标签样式，仅对该数据项有效
        label: {},
        //自定义特殊 itemStyle，仅对该数据项有效
        itemStyle:{}
    },
    10
]
// 或
[
    [12, 33],
    [34, 313],
    {
        value: [56, 44],
        label: {},
        itemStyle:{}
    },
    [10, 33]
]
```

**Comment by pissang** [comment]
嗯，因为代码会有一定的容错处理，有些是有意的，有些是无意的，比如这个例子中是因为第三项没有用到被忽略了所以什么类型都能正常渲染。

通常来说类型会有更严格的约束来替代一些代码中不好做的检查。比如检查每个数据格式是否合法，这个如果是代码逻辑判断，可能会带来很多额外的开销以及代码体积

**Comment by pumpkinduan** [comment]
大体上我明白了，现在对data中的数据格式做了更严格的定义，所以才会有了上面的错误，能正常渲染是因为echarts内部做了一定的容错处理。

非常感谢您的解答，祝元宵快乐
