### ISSUE TITLE
在vue中使用geo, registerMap 方法报错

### ISSUE THREAD

**Issue by hugselina2019** [apache/echarts#14362]
![image](https://user-images.githubusercontent.com/20763416/109274858-ef269f00-784e-11eb-8ac8-1a1ed217c339.png)
![image](https://user-images.githubusercontent.com/20763416/109274796-d9b17500-784e-11eb-96c1-4770ee7a34c1.png)
![image](https://user-images.githubusercontent.com/20763416/109274825-e3d37380-784e-11eb-9780-b171d263dc75.png)

**Comment by plainheart** [comment]
`registerMap` 挂载在 `echarts` 命名空间下，而非实例方法。请改用 `echarts.registerMap`。
