### ISSUE TITLE
局部渲染错误，在官网的示例中就能稳定复现

### ISSUE THREAD

**Issue by np9576** [apache/echarts#14360]
### Version
5.0.2

### Steps to reproduce
1. 打开链接 https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-bus  或 https://echarts.apache.org/examples/zh/editor.html?c=map-polygon
2. 缩小地图，直到能看到白令海峡地区。会发现有条竖线，没有渲染出来。

### What is expected?
正常渲染

### What is actually happening?
有条竖线

**Comment by plainheart** [comment]
你是指的哪条线？

**Comment by np9576** [comment]
> 你是指的哪条线？

看下这两张图片，截图放这里了。  
![微信截图_20210226195519](https://user-images.githubusercontent.com/72918083/109297449-f6f53c00-786c-11eb-84bc-6aaf07610914.png)

![微信截图_20210226195451](https://user-images.githubusercontent.com/72918083/109297431-f197f180-786c-11eb-8dfc-1f6b568d415a.png)

**Comment by plainheart** [comment]
这应该是百度地图 2.0 自定义地图的问题，可以试下默认底图或改用 3.0 看看是否有此问题，如有问题，建议向百度地图反馈。
