### ISSUE TITLE
[bug] tooltip arrow should follow the specified `borderWidth`

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#14373]
### Version
5.0.2

### Reproduction link
https://www.makeapie.com/editor.html?c=xLv-60nCLP&v=1

### Steps to reproduce
Hover on the scatter, the arrow isn't following the specified `borderWidth`.

### What is expected?
The arrow should follow the specified `borderWidth`.

<img src="https://user-images.githubusercontent.com/26999792/109442549-7f452e00-7a73-11eb-87bc-1c67eedbb88e.png" width="300" alt="">

### What is actually happening?
The arrow always keeps a 1px border and target position is incorrect.

<img src="https://user-images.githubusercontent.com/26999792/109442497-5fae0580-7a73-11eb-8188-3016dba975db.png" width="300" alt="">

**Comment by gsi7** [comment]
I'll look into it.

**Comment by plainheart** [comment]
Glad to see you'd like to help fix it, thank you in advance!
