### ISSUE TITLE
如何给echarts图做自动化测试

### ISSUE THREAD

**Issue by hpyou** [apache/echarts#14374]
### What problem does this feature solve?
比如有个应用是点击echart柱状图上的某根柱子，根据这个柱子上的数据到后台请求数据，刷新某个表格。这个点击柱子的操作能不能写成端到端测试，或者哪个端到端测试框架能实现这种点击echart图

### What does the proposed API look like?
端到端测试能否实现echart图钻取功能

**Comment by pissang** [comment]
echarts 内部是使用 puppeteer 做自动化的回归测试

**Comment by hpyou** [comment]
@pissang 好的，我去了解下
