### ISSUE TITLE
缺少类型

### ISSUE THREAD

**Issue by wsz7777** [apache/echarts#14370]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by wsz7777** [comment]
![Uploading image.png…]()

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/109393871-140a3780-795f-11eb-858b-c57dba2cb37b.png)

**Comment by plainheart** [comment]
`splitLine` 和 `axisLine` 是同级别的，而非父子关系。
