### ISSUE TITLE
分级填色地图的VisualMap，如何使用categories属性，实现自定义颜色分类？

### ISSUE THREAD

**Issue by minren118** [apache/echarts#14380]
### Version
5.0.0

### Steps to reproduce
VisualMap的官方示例中，是以散点图为例，散点图的series最后一列是categories匹配的列，但在Map系列的填色地图里，尝试把Data属性加入额外的信息时，最终做图渲染颜色失败.
![image](https://user-images.githubusercontent.com/28550438/109600786-aa557d80-7b58-11eb-8bed-2a9adbee99ab.png)

目前测试结果，Map系列的data属性，只能是name、value结象数组。
![image](https://user-images.githubusercontent.com/28550438/109600904-f0aadc80-7b58-11eb-9d35-1c7e31fa9c47.png)

我如何才能把VisualMap的categories所映射的列传入到Map系列地图中？

### What is expected?
可以实现Map系列地图的VisualMap中的categories属性绑定，实现自定义颜色填充。

### What is actually happening?
当前不能实现Map系列地图的VisualMap中的categories属性绑定。

**Comment by alphabetabc** [comment]
```js
const option = {

    visualMap: {
        show: false,
        categories: ['aa', 'bb', 'cc'], 
        inRange: {
            color: ['red', 'green', 'blue'],
        },
    },

       series: [
        {
            type: 'map',
            map: 'china',
            data: [
                { name: 'region0', value: [1, 'aa'] },
                { name: 'region1', value: [2, 'bb'] },
                { name: 'region2', value: [3, 'cc'] },
            ],
        },
    ]
}
```

**Comment by minren118** [comment]
感谢，马上试试
