### ISSUE TITLE
When axisType is 'time', it is not able to set the interval of labels in timeline

### ISSUE THREAD

**Issue by Clarkkkk** [apache/echarts#14391]
### Version
5.0.1

### Steps to reproduce
In a timeline, set the interval of label to a value, for example `label: {interval: 2}`.

### What is expected?
show a label every three labels

### What is actually happening?
When `axisType` is `'time'`, all the labels occur, no matter what interval I set .

---

Another two quesstions:

1. In the [example](https://echarts.apache.org/examples/zh/editor.html?c=doc-example/mix-timeline-all) at the official document, set the axisType to 'time' would cause an error. Is it because the dates are not sequential?

2. I'm also curious that what is [the label in `timeline.progress`](https://echarts.apache.org/zh/option.html#timeline.progress.label) used for? I don't see any other types of label in a timeline.

**Comment by zmm2015** [comment]
@Clarkkkk 我们也遇到同样的问题，你们找到解决方案了吗？

**Comment by Clarkkkk** [comment]
@zmm2015 只能先把 `axisType` 设为 `category` 了

**Comment by zmm2015** [comment]
> @zmm2015 只能先把 `axisType` 设为 `category` 了

多谢，我试一下
