### ISSUE TITLE
Unix timestamps on axis type "time" do not render

### ISSUE THREAD

**Issue by Azekthi** [apache/echarts#14409]
### Version
5.0.2

### Reproduction link
[https://codepen.io/azekthi/pen/dyOjdRm](https://codepen.io/azekthi/pen/dyOjdRm)

### Steps to reproduce
See reproduction link.

### What is expected?
The timestamps should automatically convert to a date or time render in UTC, per https://echarts.apache.org/en/option.html#series-line.data

### What is actually happening?
The line and the X-axis are not rendering.

---
The chart renders [if the X axis is set to category instead of time](https://codepen.io/azekthi/pen/WNoKMZe).

**Comment by plainheart** [comment]
It's better to convert the timestamp string to number. Or use the Date array / date string array.
