### ISSUE TITLE
Provide onLeafClick custom function on treemap

### ISSUE THREAD

**Issue by kaisian97** [apache/echarts#14400]
### What problem does this feature solve?
I am using this chart library in react native. My use case is after I click the node, I need to navigate to a list view. Besides that, it is also helpful for others, just in case they want to go to other pages instead of click and zoom into the child node.

### What does the proposed API look like?
series: {
    type: 'treemap',
    .....
    onLeafClick: (node) => {
       

   }

**Comment by MilosPopovic11** [comment]
Hi, this doesn't have nothing with this subject, but I need to ask something that I try to find solution on DOCS, on Stack, in PRs, and in Issues, and can not find, and I am not sure if that is for new feature or bug.
Is there a way for treemap that have multilevels, to have SUM of all values for that level? 
ex. If I am on first leaf level, I need TOTAL SUM of all values from that level to show to user, when click on some child leaf, need to get TOTAL SUM of all values from that level etc... Thanks and sorry for interrupt.
