### ISSUE TITLE
V5版本TOOLBOX的自定义feature的show属性失效了,无法控制自定义工具的显示隐藏

### ISSUE THREAD

**Issue by yyz945947732** [apache/echarts#14405]
### Version
5.0.2

### Steps to reproduce

![image](https://user-images.githubusercontent.com/47586954/109957591-1fbf7a80-7d20-11eb-9261-b4950d2f49f2.png)

本来V4的时候是正常的,升级到V5后所有的工具都强行显示了, show属性无法起到作用

### What is expected?
配置生效

### What is actually happening?
配置未生效

**Comment by ysneo** [comment]
这个bug在 v4版本里也是有的。我今天正好遇到了。
