### ISSUE TITLE
将markLink的label属性的样式层级设置为可配置

### ISSUE THREAD

**Issue by liliqiong** [apache/echarts#14402]
### What problem does this feature solve?
最近用echarts实现柱状图，使用了标注线markLine，用户需求是将标注线上的标签label显示在标注线的中间，但是label的内容比较长，导致柱状图覆盖了标注线label的内容，因此需要将label的层级设置为可配置或大于柱状图的层级，即可解决label内容被覆盖的问题

![image](https://user-images.githubusercontent.com/31943768/109952020-58a82100-7d19-11eb-936a-e00b2784d64e.png)

### What does the proposed API look like?
期望markLink的label的层级可配置

**Comment by susiwen8** [comment]
Related to #14190
