### ISSUE TITLE
Sunburst labelLine not displayed correctly

### ISSUE THREAD

**Issue by ahmeddabak** [apache/echarts#14411]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/4osbwd3f/1/](https://jsfiddle.net/4osbwd3f/1/)

### Steps to reproduce
I have attached a minimal code example

### What is expected?
labelLine should point to label

### What is actually happening?
labelLine just points to nothing

**Comment by susiwen8** [comment]
Looks like label was misplace.
<img width="507" alt="Screen Shot 2021-03-07 at 10 13 51" src="https://user-images.githubusercontent.com/20318608/110226897-d80e3e00-7f2d-11eb-8959-2e24c9000c26.png">

**Comment by ahmeddabak** [comment]
I have no idea where to get started on this problem, I am also not sure if the problem is caused by the label or label line
