### ISSUE TITLE
dataURI not show in Firefox

### ISSUE THREAD

**Issue by brucewar** [apache/echarts#14410]
### Version
5.0.2

### Reproduction link
[https://codepen.io/brucewar/pen/zYoLaKo](https://codepen.io/brucewar/pen/zYoLaKo)

### Steps to reproduce
see codepen

### What is expected?
show as Chrome

### What is actually happening?
not show

**Comment by plainheart** [comment]
Could you tell us what version of Firefox are you using?

**Comment by susiwen8** [comment]
I can reproduce in latest version

**Comment by susiwen8** [comment]
I can reproduce in latest version

**Comment by brucewar** [comment]
> Could you tell us what version of Firefox you are using?

maybe firefox bug，must set width and height for svg

**Comment by plainheart** [comment]
Yes. `width` and `height` are required for the image if you are using SVG `renderer`.

**Comment by plainheart** [comment]
According to [this question](https://stackoverflow.com/questions/28690643/firefox-error-rendering-an-svg-image-to-html5-canvas-with-drawimage), it should be a bug of Firefox.
