### ISSUE TITLE
tooltips xss问题

### ISSUE THREAD

**Issue by RuiMM** [apache/echarts#14429]
### Version
5.0.2

### Steps to reproduce
复现地址：https://codepen.io/ruimei/pen/zYombvZ
触发tooltips时候会触发脚本

### What is expected?
希望能正常运行

### What is actually happening?
xss

**Comment by susiwen8** [comment]
No, it doesn't. We will look into it.

**Comment by 100pah** [comment]
I think it is not an issue.
When the `tooltip.formatter` is totally defined by user,
user should do that `encodeHTML` when assemble html text.  
For example: 

```js
    tooltip: {
        trigger: 'axis',
        formatter(params) {
            const name = params[0] && params[0].name;
            const fmt = `${name}${
                params.map((param, i) => {

                return `<br/>
                      <span class="serie-label" style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;
                        background-color:${param.color};"></span>
                    ${encodeHTML(param.seriesName)} : ${encodeHTML(param.value)}`;
            }).join('')
          }`;

          return fmt

        }
    }
```


```js
function encodeHTML(source) {
    return source == null
        ? ''
        : (source + '').replace(/([&<>"'])/g, function (str, c) {
            return {
                '&': '&amp;',
                '<': '&lt;',
                '>': '&gt;',
                '"': '&quot;',
                '\'': '&#39;'
            }[c];
        });
}

```

echarts should not make `param.seriesName` and `param.value` encoded internally, 
otherwise, users can only get the encoded `param.seriesName` and `param.value` and can not do anything others to that string.

**Comment by 100pah** [comment]
The security-related documents have been updated, including:
- [Security guidelines for API callers](https://echarts.apache.org/handbook/en/best-practices/security/)
- [Security checklist for code contributors](https://github.com/apache/echarts/wiki/Security-Checklist-for-Code-Contributors)
- Security warnings in option documents, for example, [tooltip.formatter](https://echarts.apache.org/en/option.html#tooltip.formatter)

[Security guidelines for API callers](https://echarts.apache.org/handbook/en/best-practices/security/) explains why sanitization is not appropriate to be performed inside ECharts.

You helped us improve the security of ECharts. Many thanks!
