### ISSUE TITLE
使用splitNumber均分splitLine，最右边多出一条分割线

### ISSUE THREAD

**Issue by F5F5** [apache/echarts#14435]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/8065mwsv/1/](https://jsfiddle.net/8065mwsv/1/)

### Steps to reproduce
```
option = {
    yAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    xAxis: {
        splitNumber: 7,
        max: 'dataMax',
        type: 'value'
    },
    series: [{
        data: [
                18203,
                23489,
                29034,
                104970,
                131744,
                140230,
                63023
        ],
        type: 'bar'
    }]
};
```
![image](https://user-images.githubusercontent.com/15978277/110468572-73143d00-8113-11eb-85f8-c22336cc5dac.png)

### What is expected?
期望所有分割线宽度一致

### What is actually happening?
实际最右边多出了1px

看起来是最右侧刻度140000和数据最大值140230不一致造成的，有什么好的解决办法嘛？

**Comment by F5F5** [comment]
@susiwen8 Thank you very much! But if loose the ```max``` the bar cant align to the rightmost splitLine. The designer want them coincide. 😢😢😢
![image](https://user-images.githubusercontent.com/15978277/110601742-3e11f400-81c0-11eb-94b8-1fd37cb226f0.png)

**Comment by F5F5** [comment]
It seems should remove ```splitNumber``` or ```max```.😒

**Comment by susiwen8** [comment]
I'm going to close this one, feel free to reopen it.
