### ISSUE TITLE
echarts connect 多图联动x轴对齐问题

### ISSUE THREAD

**Issue by csfreebird** [apache/echarts#14437]
### Version
5.0.2

### Steps to reproduce
第一个图的x轴日期少一些，第二个图的x轴日期多一些。但是数据都是合理的。
当在一个图表上移动光标的时候，发现另一个图表上光标跟着移动，但是似乎按照x轴的索引进行对齐，而不是按照具体的日期值对齐。

这个问题如何解决？

### What is expected?
希望能够按照x轴的日期值对齐

### What is actually happening?
移动光标的时候，两个图上显示的日期出现偏差

**Comment by yongfengz2020** [comment]
同样遇到这个问题，就是目前axisPointer都是通过index link在一起，是否可以通过value link，

**Comment by 14glwu** [comment]
x改为category类型即可
