### ISSUE TITLE
echart connect 连接两个折线图的时候X轴能否根据日期值对齐

### ISSUE THREAD

**Issue by csfreebird** [apache/echarts#14436]
第一个图的x轴日期少一些，第二个图的x轴日期多一些。但是数据都是正确的。
当在一个图表上移动光标的时候，发现另一个图表上光标跟着移动，但是似乎按照x轴的索引进行对齐，而不是按照具体的日期值对齐。

这个问题如何解决？

**Comment by 14glwu** [comment]
> 第一个图的x轴日期少一些，第二个图的x轴日期多一些。但是数据都是正确的。
> 当在一个图表上移动光标的时候，发现另一个图表上光标跟着移动，但是似乎按照x轴的索引进行对齐，而不是按照具体的日期值对齐。
> 
> 这个问题如何解决？

x轴类型改为category
