### ISSUE TITLE
Text shadow is not working on visualMap

### ISSUE THREAD

**Issue by Clarkkkk** [apache/echarts#14440]
### Version
5.0.1

### Reproduction link
[https://jsfiddle.net/x4Lf09tm/](https://jsfiddle.net/x4Lf09tm/)

### Steps to reproduce
Set the text shadow on visualMap:
```js
visualMap: {
  textStyle: {
    color: '#000',
    textShadowColor: '#000',
    textShadowBlur: 2,
  }
}
```

### What is expected?
The text has shadow on it.

### What is actually happening?
No shadow on the text.

**Comment by niekvb** [comment]
Text shadow is also missing when setting it for axis labels.

Version `5.3.1`
