### ISSUE TITLE
replaceMerge API , if i want to replace series[1], how to deal with this.    

### ISSUE THREAD

**Issue by baokeyu123** [apache/echarts#14446]
### Version
5.0.2

### Steps to reproduce
replaceMerge  just replace API in setOption. but i want to just replace series[1].if series is  array.

how to resolve this problem。

thanks

### What is expected?
resolve problem

### What is actually happening?
for example

mychart.setOption({
            series: [{
                type: 'line',
                animationDuration: 100,
                animationEasing: 'linear',
                data: data
            },
{
                type: 'lines',
                animationDuration: 100,
                animationEasing: 'linear',
                data: data
            },
            ]
        }，{replaceMerge :[series[1]]}});

---
bless for you

@plainheart

**Comment by baokeyu123** [comment]
@leeight 

 {
                type: 'lines',
                coordinateSystem: 'cartesian2d',
                polyline: true,
                effect: {
                    show: true,
                    trailLength: 0,
                    symbol: 'rect',
                    period: 12,  //滑动速度
                    symbolSize: [200, 15],
                    color: 'black',
                    loop: false,
                },
                data: [{
                    coords: [
                        [0, 0],
                        [Distance, 0] 
                    ]
                },],
            }

i don't  set API loop:true ,because i want to update data and animation is synchronize，update data exist  delay，so i have to rebuild lines animation

thanks~

**Comment by 100pah** [comment]
```js


mychart.setOption({
    series: [{
        // if id is specified, this option will be 
        // merged to the existing series with this id.
        id: 'line_series',
        type: 'line',
        animationDuration: 100,
        animationEasing: 'linear',
        data: data
    }, {
        // if id is not specified, a new series instance 
        // will be created by this option, and the previous
        // series[1] will be removed.
        type: 'lines',
        animationDuration: 100,
        animationEasing: 'linear',
        data: data
    }]
}, {
    replaceMerge: 'series'
});

```
