### ISSUE TITLE
Tag cloud Chart

### ISSUE THREAD

**Issue by pradeepvish1213** [apache/echarts#14447]
### What problem does this feature solve?
Tag chart
![image](https://user-images.githubusercontent.com/11312956/110666005-ec08a880-8196-11eb-8ebf-e4b1db4fc431.png)

### What does the proposed API look like?
NA

**Comment by plainheart** [comment]
Hi, @pradeepvish1213 Here is an extension for word cloud [echarts-wordcloud](https://github.com/ecomfe/echarts-wordcloud), does it work for you?

**Comment by pradeepvish1213** [comment]
@plainheart I used that it's working. But I don't want to add another library. That's why I asked to, thank you for your reply. 
I hope in the future to include this chart.

**Comment by pissang** [comment]
It's an extension for echarts. I don't think it will be an issue. Will close this issue
