### ISSUE TITLE
Invisible y axis

### ISSUE THREAD

**Issue by dzik1331** [apache/echarts#14462]
### Version
5.0.2

### Steps to reproduce
https://echarts.apache.org/v4/examples/en/editor.html?c=line-simple

https://echarts.apache.org/examples/en/editor.html?c=line-simple

### What is expected?
This is basic example from v4 https://echarts.apache.org/v4/examples/en/editor.html?c=line-simple and there y axis line is visible but in all examples from latest version y axis line is invisible
https://echarts.apache.org/examples/en/editor.html?c=line-simple.

What to do to get the line back?

### What is actually happening?
I updated my project from version 4 to the latest and now there is no Y-axis line in the charts

**Comment by ssthouse** [comment]
@dzik1331 Hi, this seems to be the expected result. The y-axis is hidden when x-axis's type is `value` or `log` by default.

you can check this commit which introduces this logic: https://github.com/apache/echarts/commit/4acb689f0b28f42165e99e5c9c148def12d29b2a

---

Also, you can force the y-axis to show by implicity setting `axisTick.show` and `axisLine.show` to true. like this:

```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        show:true,
        type: 'value',
        axisTick:{
          show:true,  
        },
        axisLine:{
            show: true
        },
    },
    series: [{
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line'
    }]
};
```

![image](https://user-images.githubusercontent.com/10973821/121892565-8573c780-cd4f-11eb-93a9-f653ae497fa5.png)

**Comment by arashdalir** [comment]
> @dzik1331 Hi, this seems to be the expected result. The y-axis is hidden when x-axis's type is value or log by default.

this is not exactly true! apparently, even `xAxis.type = 'time'` causes the yAxis axisLine to disappear too; and this although the default value is allegedly set to `true` (https://echarts.apache.org/en/option.html#yAxis.axisLine.show)
