### ISSUE TITLE
关系图graph在使用geo坐标系统时报错：Cannot read property 'off' of undefined

### ISSUE THREAD

**Issue by datageartech** [apache/echarts#14463]
### Version
5.0.2

### Steps to reproduce
1. 打开ECharts官网示例

https://echarts.apache.org/examples/zh/editor.html?c=map-HK

2. 将示例代码中的

```
myChart.setOption(option = {
...
});
```

改为：

```
myChart.setOption(option = {
    "title": {"text": "关系地图"},
	"tooltip": {"trigger": "item"},
	"geo": {"roam": true,"map": "HK"},
	"legend": {"data": ["C1","C2","C0"]},
	"series": 
	[
		{
			"name": "关系地图",
			"type": "graph",
			"layout": 'none',
			"coordinateSystem": "geo",
			"data":
			[
				{"name": "a","x": 114.14,"y": 22.28,"category": 0,"value": 80,"symbolSize": 16},
				{"name": "b","x": 114.18,"y": 22.30,"category": 0,"value": 140,"symbolSize": 30},
				{"name": "c","x": 114.18,"y": 22.25,"category": 1,"value": 70,"symbolSize": 14},
				{"name": "d","x": 114.23,"y": 22.18,"category": 2,"value": 5,"symbolSize": 6},
				{"name": "e","x": 114.25,"y": 22.35,"category": 2,"value": 55,"symbolSize": 11}
			],
			"links":
			[
				{"source": 0,"target": 1},
				{"source": 1,"target": 2},
				{"source": 1,"target": 3},
				{"source": 1,"target": 4}
			],
			"legendHoverLink": true,
			"label": {"position": "right"},
			"emphasis": {"focus": "adjacency"},
			"categories": [{"name": "C1"},{"name": "C2"},{"name": "C0"}],
            "lineStyle":
            {
                "color": 'source',
                "curveness": 0.3
            }
		}
	  ]
    });
```

3. 点击【运行】按钮

### What is expected?
在地图中显示关系图

### What is actually happening?
没有显示效果，打开浏览器控制台报错：
```
echarts.min.js:45 Uncaught TypeError: Cannot read property 'off' of undefined
    at echarts.min.js:45
    at t.eachNode (echarts.min.js:45)
    at e.render (echarts.min.js:45)
    at t.progress (echarts.min.js:45)
    at t._doProgress (echarts.min.js:45)
    at t.perform (echarts.min.js:45)
    at echarts.min.js:45
    at e.<anonymous> (echarts.min.js:45)
    at Array.forEach (<anonymous>)
    at P (echarts.min.js:35)
```

**Comment by Etering** [comment]
同问

**Comment by helgasoft** [comment]
solution - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-HK&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QzhAaQQArJKkJSANKIBmAV0IBjOPmOjSmgFJHC5UQG9qo0aCQsIgQ-LiM2HhEZFR-ooy20PBICDCMxPhIcIwwALJQAA6kUrpmom4esf6BSYhqcOwFDsakcf6kqE2OhKIAvD5t_qIOcAA2jABcPsOMAB5wU1KAzoqA3z6ADOqAf2pSogC-poP-cKioow4FU97DMPjETDCL-NnA23sH5YyoF6IwOMBTcDArIxzMBCotSrt9kMhuMmIRcBdXtD_GprowkFMANpvfy-ZHIwhQYCTaSrTZmHFDOAgAokqTEGCFCAU_HQ0ZQECoKwLaSEYyMFms_y2Y4wAiE7IAZRAWUYf2kmkFQvkiixlOheKFBKJdKgSq1_gAblBRkCsQBGc0AFgQ1vMACZ7Qh7QAOcwugAMAF0oQahrYFOlUDAQFMPb6_aIkCBgAAjE6S_AALxJ5oAbOqhki_ZrI4TiYtY_qDcbTSTMZabea3aJHQgAMzma3eiN-gPZYjB0OicOZ6HRuMJ5Mk-sevuQ8e5v35um2Yta0tm0QV622mt1-0AVnMAHYW-PhYHOyGpubWwaB_HRomU6erePswapwaZ4tcPOhYvy5XnY3a07q3MTcfQPUR2yDE9a3PLVLyHW9RAzSNHy1Z8tVfaQBWgz8TSXFcbS3B0nXrbdRE3YCsNZcDj27e0KPxWDr2HU9zQfTMQINUYiAAawxZdJyjLkYFsXUykUGAmB5KQiwnSNLiMKwhLpItzDEiTFjnGScwEhThMLUTYDU6R300p9tMUvSVIM5hFgFXY2Lo0RYUYeFhFQQ0ckwbipgsE01Ac9lY0YUYvgKVAkEebpFmuYgIDgF4HLlApoHC3jLgsVBbCsXipDwfQoGEuwQHizMqODfB0SxS50KkMBzXi6ZqrAe16qqnVFjAD0XnYrVOMIRhJWpcYLnHdAwjgCApkbcdMpgdy-tUMMG0zHZKRW_EvUGHZyDiWItsoIA)
