### ISSUE TITLE
Configuration Interval Issues such as Pie Charts and sunBrust Charts

### ISSUE THREAD

**Issue by zyl717** [apache/echarts#14466]
### What problem does this feature solve?
Hello, I want to implement the effect of spacing between sectors. In most cases, I can use the "BorderWidth" attribute and "BorderColor" attribute to follow the background color change. However, if the background color is transparent, the border line cannot be drawn. If you can, please tell me how to achieve the desired effect.

<img src="https://user-images.githubusercontent.com/72777298/111060825-b63b2b00-84da-11eb-9507-6a5b227cf62c.png" width="50%">

### What does the proposed API look like?
New attribute ‘intervals’ under itemStyle

**Comment by plainheart** [comment]
Currently, I think there may be no way to do this in transparent background. Perhaps, a new option, for example, `padAngle`, should be provided.
