### ISSUE TITLE
Y axis not displayed if canvas is smaller 150px

### ISSUE THREAD

**Issue by Georges67** [apache/echarts#14461]
### Version
5.0.2

### Steps to reproduce
When I set the height to 300px all is correctly displayed but when I reduce the height to 150px  nothinf is displayed for Y Axis.

I happens for vertical  and horizontal bar charts 

### What is expected?
See the data in Y axis

### What is actually happening?
Nothing is displayed

**Comment by pissang** [comment]
Reduce the `grid.top` and `grid.bottom` in your option.
