### ISSUE TITLE
legend 滚动的时候数据显示有问题

### ISSUE THREAD

**Issue by xxLion** [apache/echarts#14474]
### Version
5.0.2

### Steps to reproduce
滚动的时候第一页最后一项和第二页第一项数据重复

### What is expected?
翻到第二页不该显示第一页的数据

### What is actually happening?
none

**Comment by xxLion** [comment]
![cc](https://user-images.githubusercontent.com/26025205/111128485-e86a8c80-85af-11eb-9f37-a3ca5e4b2258.gif)

**Comment by xxLion** [comment]
@plainheart 你好，这个问题大概多久能解决，这个已经不是用户体验的问题了，是数据展示出错了。

**Comment by 100pah** [comment]
这是故意这样设计的。
1. legend 最后一项可能不能显示完全（除非尺寸恰好是 legend 的整数倍）
2. 下一页显示最后一项，是试图给予前后页的一定视觉关联。

**Comment by susiwen8** [comment]
Close by design
