### ISSUE TITLE
Tooltip is wrong in custom-gantt-flight example

### ISSUE THREAD

**Issue by pissang** [apache/echarts#14470]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight](https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight)

### Steps to reproduce
Show tooltip

### What is expected?
Time is formatted correctly

### What is actually happening?
Time is not formatted correctly in the tooltip

![image](https://user-images.githubusercontent.com/841551/111108988-d7f8e880-8594-11eb-9c94-ca6687375d2b.png)

**Comment by Jordon-Chen** [comment]
Hi, is there any ways to work around this tooltip problem in version 5.0.2 ?
