### ISSUE TITLE
echarts高频刷新数据显示（200ms）

### ISSUE THREAD

**Issue by gy19920615** [apache/echarts#14475]
做了一个前端，使用的是echarts，使用window.setInterval周期请求后台数据，频率为200-300Ms，数据量为800多个散点，然后显示到UI，整理比较流畅不卡顿，就是会闪烁，大概一一两秒出现一次闪烁（点云消失再出现），是不是又什么渲染没关掉导致画图没画好下一次数据又刷新了？ 但是降低了频率似乎并没有解决

**Comment by badspider7** [comment]
我也碰到了，但是我没请求后台数据
