### ISSUE TITLE
How dose Echarts5 close Initializing animation

### ISSUE THREAD

**Issue by xiaojia117** [apache/echarts#14489]
### Version
5.0.2

### Steps to reproduce

1、get data we need, set web page : loading = true.
![1](https://user-images.githubusercontent.com/27489830/111292907-a4e15280-8683-11eb-926e-273c7734a6aa.jpg)

2、handle data, set data to echarts5;

3、set web page: loading = false; 
![3](https://user-images.githubusercontent.com/27489830/111292937-af035100-8683-11eb-9231-2d29a5fe5b1a.png)

4、but if we quickly refresh web page, This phenomenon will continue for less than 0.1 second.
![2](https://user-images.githubusercontent.com/27489830/111292965-b6c2f580-8683-11eb-9e99-b50e69149556.png)

### What is expected?
close the animation when echarts iInitializes.

### What is actually happening?
the loading is conflicting with echarts5 animation

---
this is not happen in "echarts": "4.9.0".

**Comment by plainheart** [comment]
If no initial animation is needed, you could set [`animationDuration`](https://echarts.apache.org/zh/option.html#animationDuration) as 0.
