### ISSUE TITLE
chinaMapOutline 的数据json请求接口地址在哪

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#14487]
### Version
4.9.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xpW8YqCI-](https://www.makeapie.com/editor.html?c=xpW8YqCI-)

### Steps to reproduce
```js
echarts.registerMap('chinaMap', chinaMap);
echarts.registerMap('chinaMapOutline', chinaMapOutline); //chinaMapOutline 这个json哪里来呢
```
我想某块地图区域显示高亮，请问怎么显示呢？
2、chinaMapOutline 这个json哪里来呢

### What is expected?
我想某块地图区域显示高亮，请问怎么显示呢？

### What is actually happening?
1、高亮无法设置（下面已经解决）
2、chinaMapOutline 这个json哪里来呢

**Comment by pissang** [comment]
这个数据是你自己准备的

**Comment by zhoufanglu** [comment]
> 这个数据是你自己准备的

有第三方能提供吗？类型get请求这种的

**Comment by plainheart** [comment]
可以试试 datav 提供的地图选择器 https://datav.aliyun.com/tools/atlas/

**Comment by plainheart** [comment]
可以试试 datav 提供的地图选择器 https://datav.aliyun.com/tools/atlas/

**Comment by zhoufanglu** [comment]
> 可以试试 datav 提供的地图选择器 https://datav.aliyun.com/tools/atlas/
谢谢大佬回答！！
大佬你看我发给你的demo,我知道这个链接，demo里面还有个chinaMapOutline，这个数据哪来？
还有 我想让上面那个demo某一块地区高亮，请问有什么好的方法吗？

**Comment by zhoufanglu** [comment]
> 可以试试 datav 提供的地图选择器 https://datav.aliyun.com/tools/atlas/

![image](https://user-images.githubusercontent.com/24451091/111266291-49a06780-8665-11eb-9c9a-31dc2d95ebbe.png)
里面区域的数据格式是这样的，请问怎么高亮呢？

**Comment by plainheart** [comment]
高亮可以使用 [`dispatchAction`](https://echarts.apache.org/zh/api.html#action.highlight)

**Comment by zhoufanglu** [comment]
> 高亮可以使用 [`dispatchAction`](https://echarts.apache.org/zh/api.html#action.highlight)

谢谢 高亮解决了

**Comment by plainheart** [comment]
> 2、chinaMapOutline 这个json哪里来呢

这个例子似乎是由 Gallery 上某位开发者贡献的，建议询问作者数据来源，抱歉无法为你提供更多帮助。
