### ISSUE TITLE
Echart's height is not responsive. PLZ HELP ASAP

### ISSUE THREAD

**Issue by TheLostDory** [apache/echarts#14482]
### What problem does this feature solve?
I need my charts height to be responsive:

Hello, I need help the heights in the charts is not responsive, while the width is responsive. PLZ IS NEED HELP ASAP
This is my chart options:
this.options = {
xAxis: {
type: 'category',
data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
},
yAxis: {
type: 'value'
},
series: [{
data: [150, 230, 224, 218, 135, 147, 260],
type: 'line'
}]
};

and this is my html code:
<div >
  <div echarts [options]="options" class="demo-chart" ></div>
</div>

### What does the proposed API look like?
I really dont know how to fix it plz i need it to be fixed asap

**Comment by TheLostDory** [comment]
I can not because I am using angular so I am using typescript not javascript

**Comment by plainheart** [comment]
Can I know what layout are you using in ECharts' container? flex or grid?

**Comment by TheLostDory** [comment]
@plainheart I am not using any layout I uploaded my code.
I guess it is using the default one. If I specify display flex the chart does not load.

**Comment by plainheart** [comment]
Is it possible to provide some screenshots to let us know the unexpected result and expected result?

**Comment by TheLostDory** [comment]
@plainheart 
this is the unexpected result:
![image](https://user-images.githubusercontent.com/39488395/111151617-602cbd00-8598-11eb-8aa4-6fb7a3bfa277.png)

this is the expected result:
![image](https://user-images.githubusercontent.com/39488395/111151771-966a3c80-8598-11eb-8fa1-aaa46a92dcc6.png)


I need it to be responsive

**Comment by plainheart** [comment]
I guess the [`grid`](https://echarts.apache.org/en/option.html#grid.top) option may work for you. Just to set `grid.left`, `grid.right`, `grid.top` and `grid.bottom`.

**Comment by TheLostDory** [comment]
@plainheart what values should I give for grid.left, grid.right, grid.top, grid.bottom? and should I set the display grid ? display: grid?

**Comment by plainheart** [comment]
> what values should I give for grid.left, grid.right, grid.top, grid.bottom?

Try to set them as `0`.

> should I set the display grid ? display: grid?

No.

**Comment by TheLostDory** [comment]
@plainheart Should i change them in the scss file or where?

**Comment by plainheart** [comment]
No. They are options of ECharts.

**Comment by plainheart** [comment]
Just like this,

```js
this.options = {
    grid: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        containLabel: true
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line'
    }]
};
```

**Comment by TheLostDory** [comment]
@plainheart I tried it it did not work :(
horizontally it is responsive but vertically it is not it is taking the default height

**Comment by plainheart** [comment]
I'm afraid I have to try your demo to provide further help for you.

**Comment by plainheart** [comment]
Does `chart.resize()` work for you?

**Comment by TheLostDory** [comment]
where should i place chart.resize ?

**Comment by plainheart** [comment]
This is up to your code.

There is a hint we can read from the [document](https://echarts.apache.org/en/api.html#echarts),

![image](https://user-images.githubusercontent.com/26999792/111154016-a51f1680-85cd-11eb-8a1a-42411e08830c.png)

Please check if you are in this case.

**Comment by AKclown** [comment]
So, is there any latest progress? I encountered the same problem.
