### ISSUE TITLE
about bmap， Incomplete rendering load（关于echart中地图，最近开始加载不全的问题）

### ISSUE THREAD

**Issue by joel785454405** [apache/echarts#14496]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-effect](https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-effect)

### Steps to reproduce
No code modifiednothing

### What is expected?
complete rendering load

### What is actually happening?
No code modified

---
Is it a network problem？

**Comment by plainheart** [comment]
这是百度地图 2.0 自定义地图用到的瓦片地图服务器的问题，可能会遇到白块的地方，ECharts 无法解决此问题。建议尝试使用百度地图 3.0。

**Comment by joel785454405** [comment]
> 这是百度地图 2.0 自定义地图用到的瓦片地图服务器的问题，可能会遇到白块的地方，ECharts 无法解决此问题。建议尝试使用百度地图 3.0。

我用的是     "echarts": "^5.0.0"，按理来说应该是3.0了

**Comment by plainheart** [comment]
ECharts 5.0 与百度地图 3.0 没有关系，百度地图 API 脚本是需要开发者自行引入的，所以使用的版本由开发者来决定。

**Comment by joel785454405** [comment]
> ECharts 5.0 与百度地图 3.0 没有关系，百度地图 API 脚本是需要开发者自行引入的，所以使用的版本由开发者来决定。

因为我写的是vue3.0的框架，所以引用了echarts官方最新的依赖。看了下node_moudles源码包里面bmap的拓展，确实引用3.0版本了

**Comment by plainheart** [comment]
不太清楚你是否有理解，ECharts 并不会帮我们自动引入百度地图 API script，而是需要开发者在代码里手动引入。
```html
<script type="text/javascript" src="https://api.map.baidu.com/api?v=3.0&ak=您的密钥"></script>
```

**Comment by joel785454405** [comment]
> 不太清楚你是否有理解，ECharts 并不会帮我们自动引入百度地图 API script，而是需要开发者在代码里手动引入。
> 
> ```
> <script type="text/javascript" src="https://api.map.baidu.com/api?v=3.0&ak=您的密钥"></script>
> ```

![image](https://user-images.githubusercontent.com/32213119/111440241-1e8b4600-8741-11eb-84e2-35445a18b326.png)
理解的，看上图

**Comment by plainheart** [comment]
所以 3.0 仍然出现瓦片地图加载不全的问题吗？

**Comment by joel785454405** [comment]
> 所以 3.0 仍然出现瓦片地图加载不全的问题吗？

是的，2.0，3.0，都会出来。
![image](https://user-images.githubusercontent.com/32213119/111440640-80e44680-8741-11eb-9d8c-32dd6782d941.png)

**Comment by plainheart** [comment]
这种情况只能建议向百度地图提工单咨询了。

**Comment by joel785454405** [comment]
> 这种情况只能建议向百度地图提工单咨询了。

感谢回答
