### ISSUE TITLE
A problem with almost all line charts

### ISSUE THREAD

**Issue by jin0424** [apache/echarts#14495]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-simple](https://echarts.apache.org/examples/zh/editor.html?c=line-simple)

### Steps to reproduce
All line graphs can be clicked, and this problem exists.You only need to write this sentence in the ‘series’.  [{name: '联盟广告', type: 'line', stack: '总量', data: [0, 0, 0, 365] }, {name: '邮件营销', type: 'line', stack: '总量', data: [0, 0, 0, 116] }]  Of course, there is no problem with the rendered effect at first glance, but in fact, if you carefully check the rendered value, you will find the problem.

### What is expected?
The value rendered by 116 should be lower than the effect rendered by 365.

### What is actually happening?
But the actual situation is that after rendering, you will find on the page that the following code with a value of 116 has an effect higher than 365! This is wrong, this shouldn't happen.

---
However, if the value of 116 and the value of 365 are swapped, the effect will be no problem.In other words, before assigning values to the "series", they should be in order. The first value must be greater than the second value, otherwise the above problems will occur, which is problematic and incorrect.I think this is a hidden problem, and your company may not have discovered it. I think it is my duty to tell you this problem.Because in actual development, the actual value of the string is very complicated, so the error will directly affect the rendering effect, and sometimes this problem is out of control. If you think this problem does not exist, or there is no problem, then I misunderstood this problem, please tell me how to avoid this problem correctly. If you solve this problem, or if there are other ways to solve this problem, please let me know. My email is: 15638272824@163.com. Thank you

**Comment by plainheart** [comment]
Do you know you are using stack mode?

**Comment by jin0424** [comment]
> 您知道您正在使用堆栈模式吗？

不清楚，我是在https://echarts.apache.org/examples/zh/index.html ECharts 官网上渲染的时候发现的问题。

**Comment by jin0424** [comment]
> Do you know you are using stack mode?
I don't know, I found a problem when rendering on https://echarts.apache.org/examples/zh/index.html ECharts official website. Sorry, I forgot to answer your question in English.

**Comment by jin0424** [comment]
> 您知道您正在使用堆栈模式吗？

I don't know, I found a problem when rendering on https://echarts.apache.org/examples/zh/index.html ECharts official website. Sorry, I forgot to answer your question in English.

**Comment by plainheart** [comment]
开启了堆叠模式之后，这个渲染是正常结果，如果需要正常展示，需要把每个系列配置的 stack  去掉。

**Comment by jin0424** [comment]
> stack
那还有一个问题，https://echarts.apache.org/examples/zh/editor.html?c=line-stack 这个地址会有 stack ,我建议去掉，否则不知道的人会误解

**Comment by plainheart** [comment]
这个示例就是用来示范如何启用堆叠模式的，需要的人应该不会误解。如果对此有所不清楚的地方，建议查阅相关资料。
