### ISSUE TITLE
渐变堆叠面积图 Gradient Stacked area chart 示例打不开，无法访问

### ISSUE THREAD

**Issue by Jg-chen** [apache/echarts#14492]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=area-stack-gradient](https://echarts.apache.org/examples/zh/editor.html?c=area-stack-gradient)

### Steps to reproduce
1.所有示例页面 https://echarts.apache.org/examples/zh/index.html
2. 点击渐变堆叠面积图后，页面是空白的

### What is expected?
希望出现渐变堆叠面积图的示例

### What is actually happening?
实际结果空白

**Comment by plainheart** [comment]
现在还是不行吗？

**Comment by Jg-chen** [comment]
不行呢，你试试
https://echarts.apache.org/examples/zh/editor.html?c=area-stack-gradient
console 有个403的报错



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 渐变堆叠面积图 Gradient Stacked area chart 示例打不开，无法访问 (#14492)





 
现在还是不行吗？

**Comment by plainheart** [comment]
清除下缓存，我这里没有问题

**Comment by Jg-chen** [comment]
哦，清除下缓存可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 渐变堆叠面积图 Gradient Stacked area chart 示例打不开，无法访问 (#14492)





 
清除下缓存，我这里没有问题

**Comment by plainheart** [comment]
好的 403 的问题早上一并处理了，要是还有其他 403 问题，可以尝试清除缓存，如果仍然不行，可以再开个 issue 反馈一下。
