### ISSUE TITLE
dataset中source第一个值使用字符串数字时，会被忽略

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14491]
### Version
5.0.2

### Steps to reproduce
http://jsfiddle.net/nv4omykf/7/
参考demo，所有的值都使用了字符串 但是星期一的 '100'没有显示出来

### What is expected?
正常渲染

### What is actually happening?
星期一的 '100'没有显示出来

**Comment by plainheart** [comment]
可以设置 [`dataset.sourceHeader`](https://echarts.apache.org/zh/option.html#dataset.sourceHeader) 为 `false`，明确 `dataset` 第一行直接开始就是数据。理论上 ECharts 会自动探测第一行/列是否是维度名信息，这种情况有可能是自动探测错误。
