### ISSUE TITLE
according to  series data.lengthto set echart's width 

### ISSUE THREAD

**Issue by baokeyu123** [apache/echarts#14509]
### What problem does this feature solve?
if i don't want to change liner's form  when i dynamic add data's。when i push next group data,echart's line can change origin shape. so ,how to deal with it?

### What does the proposed API look like?
series can set liner width . If I divide the echart width into twelve equal parts，dynamic update data can't change line shape

**Comment by Ovilia** [comment]
What do you mean by "liner width" and "line can change origin shape"? Of course it will change the shape. Maybe you should provide a few images to illustrate better.
