### ISSUE TITLE
Boxplot legend color seem follows borderColor rather than color

### ISSUE THREAD

**Issue by zpinocchio** [apache/echarts#14507]
### Version
5.0.2

### Steps to reproduce
```js
this.option.series.push({
    name:G,
    type:'boxplot',
    boxWidth: ['10%',this.boxWidth '%'],
    itemStyle: {
        borderWidth:this.borderWidth,
        color:this.option.color[tempIdx],
        borderColor:this.option.color[tempIdx],
        // borderColor: '#000'
    },
    data:boxData
})
```

the result like this
![image](https://user-images.githubusercontent.com/49098424/111929804-610ea300-8af2-11eb-9567-98e3c04b4b33.png)

```js
this.option.series.push({
    name:G,
    type:'boxplot',
    boxWidth: ['10%',this.boxWidth+'%'],
    itemStyle: {
        borderWidth:this.borderWidth,
        color:this.option.color[tempIdx],
        // borderColor:this.option.color[tempIdx],
        borderColor: '#000'
    },
    data:boxData
})
```
the result like this
![image](https://user-images.githubusercontent.com/49098424/111929907-a7640200-8af2-11eb-8d5c-3622cf01b15e.png)

How can I fix this problem,thanks

### What is expected?
legend color follows item's color

### What is actually happening?
legend color seem follows borderColor rather than color

**Comment by Ovilia** [comment]
Boxplot takes border color as default color in series. But you can customize it so that the color and borderColor can be changed to those of series when #14497 be merged. This should be fixed soon.

**Comment by zpinocchio** [comment]
Thanks for your work
