### ISSUE TITLE
Allow nodes to be draggable when layout is set to none, or keep nodes fixed when dragged in force-layout graph

### ISSUE THREAD

**Issue by MichaelElliot1999** [apache/echarts#14510]
### Version
5.0.2

### Steps to reproduce
Create any graph diagram with layout set to none or force. When draggable is set to true on force layout, all of the nodes shuffle and its not good to control. When layout is set to none and positions are fixed, draggable cannot be set

### What is expected?
I expect to be able to set draggable on 'layout: none' or have some setting on force layout to keep other nodes static while one is being dragged

### What is actually happening?
All nodes move or no nodes move at all

---
I am trying to create a directional node graph which represents software architectures, the user should be able to customise the layout of their architecture by dragging and dropping nodes

**Comment by MichaelElliot1999** [comment]
This old issue is on the same topic: https://github.com/apache/echarts/issues/6467

**Comment by Ovilia** [comment]
This is not a bug because [the document](https://echarts.apache.org/en/option.html#series-graph.draggable) states:

> Only available when using force-directed layout.

I will mark this as a new feature.

**Comment by 100pah** [comment]
An suggestion of circular layout dragging:

<img width="538" alt="Screen Shot 2021-09-29 at 12 52 12 PM" src="https://user-images.githubusercontent.com/1956569/135206144-d495f407-70c2-4aa1-9965-c81e88e111e5.png">

<img width="451" alt="Screen Shot 2021-09-29 at 12 52 18 PM" src="https://user-images.githubusercontent.com/1956569/135206159-e6d46d07-accc-48c7-ae99-5060088c8974.png">
