### ISSUE TITLE
locale separators not applied [help wanted]

### ISSUE THREAD

**Issue by MateuszRomek** [apache/echarts#14516]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/d63vbuzf/4/](https://jsfiddle.net/d63vbuzf/4/)

### Steps to reproduce
1. register FR locale (as shown in jsFiddle)
2. Initialize chart wich .init function and set locale option to "FR"

### What is expected?
After adding the FR locale, the values in the tooltip and on yAxis should be separated by spaces.

### What is actually happening?
The values are still separated by a comma.

---

I would like to know if it is possible to use the registerLocale function to set the correct decimal and thousand separators in echarts?

In jsFiddle demo, my goal is to use the FR locale (this is an example country). 
I provided the registerLocale function with the object in the same format as in the documentation: 
 https://github.com/apache/echarts/blob/release/src/i18n/langEN.ts  but the values in the chart (tooltip and yAxis) are still separated by a comma, and in this case I would like it to be separated by a space.

Do I still have to use formatter to adjust locale separators? 

E.g. 
```
axisLabel: {

 formatter: function(value, index) {}

}
```

**Comment by susiwen8** [comment]
Well, i18n doesn't affect tooltip format, if you want to format tooltip, you can use `tooltip.formatter`

**Comment by MateuszRomek** [comment]
So for the values on yAxis and xAxis I also have to use a formatter?

**Comment by susiwen8** [comment]
> So for the values on yAxis and xAxis I also have to use a formatter?

Yes, that's right

**Comment by razzeee** [comment]
Are there any docs, what locale will affect?
