### ISSUE TITLE
I hope the official debug editor can add the code formatting function

### ISSUE THREAD

**Issue by zgsgs** [apache/echarts#14517]
### What problem does this feature solve?
This greatly improves the efficiency of chart debugging.
During the development process, we print the option to Console and put it into the official editor for editing, but in the process, we need to format it with other tools before we can put it into the editor for editing and debugging. It affects the development efficiency.

### What does the proposed API look like?
Ability to format code for a seamless charting and debugging process

**Comment by pissang** [comment]
Thanks for the suggestion. It's in our plan.

**Comment by zgsgs** [comment]
OK，Expectantly！

**Comment by pissang** [comment]
Added in https://github.com/apache/echarts-examples/tree/typescript branch. Will be published soon.

![image](https://user-images.githubusercontent.com/841551/132791112-305fd8af-5220-4bfc-ac31-961e179bb64e.png)
