### ISSUE TITLE
仪表盘的数据是否能够从非0的位置开始呢

### ISSUE THREAD

**Issue by KiterNink** [apache/echarts#14512]
### What problem does this feature solve?
业务需求是有一个数据范围和一个期望值，需要通过仪表盘的样式来表达二者的关系

### What does the proposed API look like?
可以配置数据的startAngle和endAngle，而不止整个表
### example
![image](https://user-images.githubusercontent.com/43311333/111964484-9e455600-8b2f-11eb-817d-f11afd183169.png)

**Comment by pissang** [comment]
指针需要在这个范围之间吗？

**Comment by KiterNink** [comment]
> 指针需要在这个范围之间吗？

不需要的

**Comment by pissang** [comment]
@KiterNink 可以用两个仪表盘来模拟，第二个仪表盘只画这个圆环

**Comment by KiterNink** [comment]
> @KiterNink 可以用两个仪表盘来模拟，第二个仪表盘只画这个圆环

是一个好办法，我去试试

**Comment by KiterNink** [comment]
用两个仪表盘是可以成功实现了，后续有没有可能将这一功能列入配置项呢
![image](https://user-images.githubusercontent.com/43311333/112079067-84048a00-8bba-11eb-92b0-57b8ff46135a.png)

**Comment by pissang** [comment]
这个有点偏离现在的设计，应该暂时不会考虑

**Comment by KiterNink** [comment]
> 这个有点偏离现在的设计，应该暂时不会考虑
成，感谢回复，祝工作顺利
