### ISSUE TITLE
In the highlight action, if the type of "seriesName" is set to array, only one series will be highlighted

### ISSUE THREAD

**Issue by fezhangyao** [apache/echarts#14519]
### Version
5.0.2

### Steps to reproduce
create a line chart , set series.emphasis.focus to "series" ,  trigger highlight action , Incoming parameters "seriesName" is array and there are two items , but only one series will be highlighted

### What is expected?
two series will be highlighted

### What is actually happening?
only one series will be highlighted

**Comment by susiwen8** [comment]
```js
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        name: 'line-1',
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true
    },{
        name: 'line-2',
        data: [930, 1042, 1011, 1034, 1390, 1430, 1420],
        type: 'line',
        smooth: true
    }]
};


setTimeout(function() {
    myChart.dispatchAction({
         type: 'highlight',
        seriesName: ['line-1', 'line-2'],
    }
);
    
}, 2000);
```

Can't reproduce.

**Comment by fezhangyao** [comment]
<iframe src="https://codesandbox.io/embed/festive-murdock-weydf?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="festive-murdock-weydf"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by fezhangyao** [comment]
https://codesandbox.io/s/festive-murdock-weydf?from-embed

**Comment by fezhangyao** [comment]
> @fezhangyao Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.

https://codesandbox.io/s/festive-murdock-weydf?from-embed

**Comment by fezhangyao** [comment]
> @fezhangyao Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.

https://codesandbox.io/s/awesome-sun-ey7f9?file=/src/index.js

**Comment by susiwen8** [comment]
Looks like `emphasis: {focuse: 'series' | 'self'}` will cause it.

**Comment by fezhangyao** [comment]
> focuse

How can I highlight two series at the same time and make other series transparent

**Comment by susiwen8** [comment]
Right now, you can't, We  will look into it

**Comment by fezhangyao** [comment]
> Right now, you can't, We will look into it

**Comment by fezhangyao** [comment]
> Right now, you can't, We will look into it

I do it in other ways now, set emphasis: {focus: 'self'}, set the highlight style to transparent, highlight unselected series to achieve the effect

**Comment by fezhangyao** [comment]
> > Right now, you can't, We will look into it
> 
> I do it in other ways now, set emphasis: {focus: 'self'}, set the highlight style to transparent, highlight unselected series to achieve the effect

demo: https://codesandbox.io/s/awesome-sun-ey7f9?file=/src/index.js
