### ISSUE TITLE
如何使用build命令打包项目

### ISSUE THREAD

**Issue by 2012shenghua** [apache/echarts#14525]
### Version
5.0

### Steps to reproduce
5.0 版本，我遇到问题，代码克隆下来，请问build命令那么多种类，含义分别是什么：
`

"build": "node build/build.js --type all,common,simple --min",  
"build:esm": "node build/build.js --type all --min --format esm",  
"build:i18n": "node build/build-i18n.js",  
"build:lib": "node build/build.js --prepublish",  
"build:extension": "node build/build.js --type extension",`  

### What is expected?
使用哪个命令能，打包成功，本地使用一下

### What is actually happening?
打包失败

**Comment by pissang** [comment]
https://github.com/apache/echarts#build

参考这个用就行了
