### ISSUE TITLE
我希望可以讲各个鼠标行为接口可以自定义

### ISSUE THREAD

**Issue by TenXLiar** [apache/echarts#14520]
### What problem does this feature solve?
现在我想修改，点击图例之后（legend）的action，翻阅源码读起来困难比较大，但是感觉这个需求还是挺需要的，所以希望可以自定义各个鼠标行为

### What does the proposed API look like?
现在我想修改，点击图例之后（legend）的action，翻阅源码读起来困难比较大，但是感觉这个需求还是挺需要的，所以希望可以自定义各个鼠标行为

**Comment by Ovilia** [comment]
可以在[这里](https://echarts.apache.org/zh/api.html#events.legendselectchanged)找到和 legend 相关的事件。

**Comment by TenXLiar** [comment]
非常感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 我希望可以讲各个鼠标行为接口可以自定义 (#14520)





 
可以在这里找到和 legend 相关的事件。
