### ISSUE TITLE
在电脑上 google浏览器 世界地图组件能支持拖动、放大缩小，但是在大屏上无法支持，在google浏览器已创建设备重现 ，帮忙看看

### ISSUE THREAD

**Issue by firecodes** [apache/echarts#14522]
### Version
5.0.2

### Steps to reproduce
1. 在google浏览器按F12，在右侧底部找到设置图标，点击设置图标，创建桌面和手势事件。
2. 创建设备成功之后，在打开echarts官网世界地图界面，按F12，选择刚创建设备（桌面和手势），发现世界地图无法拖动、放大、缩小等功能。
3.大屏显示器设备，经过多次测试，可以在google创建设备模拟出环境。

### What is expected?
1.google浏览器 创建桌面和手势事件（指的是大屏，无鼠标，支持手势事件），世界地图组件能支持拖动、放大缩小

### What is actually happening?
1.google浏览器 创建桌面和手势事件（指的是大屏，无鼠标，支持手势事件），世界地图组件不能支持拖动、放大缩小

---
这是官网世界地图组件，用新创建的设备，都不支持世界地图组件不能支持拖动、放大缩小
https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap

**Comment by firecodes** [comment]
问题复现提供图片链接：
1. 先按图片3创建大屏环境，https://firecodes.github.io/vue-manager/static/img/3.png 
2. 在打开官网提供世界地址，https://firecodes.github.io/vue-manager/static/img/2.png

**Comment by pissang** [comment]
这个应该是百度地图的问题，可以去百度地图相关渠道反馈

**Comment by firecodes** [comment]
> 这个应该是百度地图的问题，可以去百度地图相关渠道反馈

经过测试，用百度地图 SDK： http://lbsyun.baidu.com/jsdemo.htm#aCreateMap ， 在大屏显示器世界地图能支持拖动、放大缩小。  而echarts 封装的不行，经过api链接对比，链接参数多了type=webgl影响的。
<script src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=您的密钥"></script>

**Comment by firecodes** [comment]
应该是echarts不支持大屏（桌面和手势事件）显示器的bug， google浏览器都能创建出设备模拟环境。  能否帮忙改下，问题也是必现，最近也在看echarts源代码（拖动这块的）

**Comment by plainheart** [comment]
我测试官方的实例在你的配置下是可以正常拖动的。注意更改完 device 之后刷新一下，echarts 需要重新检测下 env

**Comment by firecodes** [comment]
@plainheart 麻烦按图创建正确的大屏环境，不是移动端环境，是PC环境打开google浏览器支持手势操作，世界地图sdk官方demo是支持，嵌套到echarts调用不支持。 创建一个环境，肯定要刷新界面，echarts内部环境变量判断都看过多次了。

**Comment by firecodes** [comment]
@plainheart 请仔细看我提供图3和图2，怎么创建重写，官方demo都测试过

**Comment by plainheart** [comment]
1) 大屏环境我已按照途中提供的参数配置 1500 * 700 / dpr 1 / Desktop (touch)
<img src="https://user-images.githubusercontent.com/26999792/112240092-a2ce5380-8c82-11eb-8951-3b777274567a.png" alt="screenshot" width="600">

2) 官方提供的示例是基于 BMap 而不是 BMap GL
3) 我得出的结论是基于未修改的官方示例代码（是否提供的截图中测试的代码经过修改？）
4) 需要确认下自己是在使用 BMap 还是 BMap GL。如果正在使用 BMap GL（通过 `type=webgl&v=1.0` 引入），ECharts 提供的 bmap 扩展插件并不兼容（GL 的命名空间是 BMapGL 而不是 BMap）。

**Comment by firecodes** [comment]
> 1. 大屏环境我已按照图中提供的参数配置 1500 * 700 / dpr 1 / Desktop (touch)
> 
> <img alt="screenshot" width="600" src="https://user-images.githubusercontent.com/26999792/112240092-a2ce5380-8c82-11eb-8951-3b777274567a.png">
> 
> 1. 官方提供的示例是基于 BMap 而不是 BMap GL
> 2. 我得出的结论是基于未修改的官方示例代码（是否提供的截图中测试的代码经过修改？）
> 3. 需要确认下自己是在使用 BMap 还是 BMap GL。如果正在使用 BMap GL（通过 `type=webgl&v=1.0` 引入），ECharts 提供的 bmap 扩展插件并不兼容（GL 的命名空间是 BMapGL 而不是 BMap）。

1. 没有改过官方界面任何代码，创建完大屏环境，拿2个界面测试效果，https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap （echarts提供的demo），http://lbsyun.baidu.com/jsdemo.htm#aCreateMap（百度地图sdk提供的demo），发现echarts不支持。
2. 项目中使用echarts显示世界地图，因为要支持echarts提供其余组件功能（例如折现图、散点图等），不能用BMap GL地图功能。 但测试出大屏一个支持，一个不支持，这又是选择题。 
3. 所以要问下，echarts如何支持大屏手势功能
