### ISSUE TITLE
lineChart 执行 setOption 时，配置项 series 改变，其他不变，不能正确渲染图表

### ISSUE THREAD

**Issue by YD-Feng** [apache/echarts#14527]
### Version
5.0.2

### Steps to reproduce
1.初始化一个echarts（下文称其为lineChart）
2.为lineChart执行setOption方法，其他配置项随意，series里设置包含4个type=‘line’的配置项
3.再次为lineChart执行setOption方法，series以外的其他配置项和上一步完全相同，把series里的配置项减少1条
4.图表没有刷新渲染
5.重复上述操作，只改变series，多次操作后，图表的渲染结果会和传入的series越发不一致

### What is expected?
线图内的线条数与series配置项一致

### What is actually happening?
线图内的线条数与series配置项不符

---
直接用包含一个lineChart的页面应该就能重现，此问题在把echart版本回退到4.9.0之后就没出现

**Comment by YD-Feng** [comment]
https://codepen.io/YD-Feng/pen/gOgaBJL @

**Comment by plainheart** [comment]
默认策略是能合并则合并，不能合并的会增加，永远不会删除已存在的组件。如果需要减少的话，你可能需要使用 [`notMerge`](https://echarts.apache.org/zh/api.html#echartsInstance.setOption) 或 [`replaceMerge`](https://echarts.apache.org/zh/api.html#echartsInstance.setOption)。

**Comment by YD-Feng** [comment]
感谢，问题已解决。这个默认策略和之前的版本区别比较大。。。
