### ISSUE TITLE
Sunburst series click event sends the wrong data when coming back from multi level drilled down state

### ISSUE THREAD

**Issue by sameeraroshan** [apache/echarts#14539]
### Version
5.0.2

### Steps to reproduce
Drill down to multiple levels while listing to series click event .
 `myChart.on('click', 'series',  (e)=>{  console.log(e.data)})`
event always contains the 1st level data when coming back after a drill down state.

### What is expected?
correct data for current level should be sent along with the click event

### What is actually happening?
chart always sends the 1st level data when coming back

---
please refer the attached video.

![screencast-nimbus-capture-2021 03 26-22_20_51](https://user-images.githubusercontent.com/4530891/112675014-a33a3a80-8e8c-11eb-971b-45d7098a6ac3.gif)

**Comment by sameeraroshan** [comment]
Anyone got this solved?

**Comment by phatlewt** [comment]
Technically i think it's the correct functionality- the center of a sunburst chart is always considered the "root" so it should always show the root or the top level of the data hierarchy.

I was also facing the same problem so I clicked around the browser inspector of the echarts object and I think I found a solution, which is to get the chart model's series viewRoot:

let viewRoot = myChart._model.getSeries()[0]._viewRoot;
console.log(viewRoot);

of interest are these properties: name (name of current node), depth (depth of tree; 0=root, 1=1st level, etc.), children[] (array of data objects under current level).

so within the click handler you can do:

```
myChart.on('click', 'series', (e)=>
{ 
     console.log(e.data);
     let viewRoot = myChart._model.getSeries()[0]._viewRoot;
     switch(viewRoot.depth)
     {
           case 0: /*do something for root*/ break;
           case 1: /*do something for 1st level*/ break;
           ..etc..
     }
});
```

if you need to get the chart object at some other point in the code:
`   echarts.getInstanceByDom(document.getElementById("your chart element id"))._model.getSeries()[0]._viewRoot`

I've only just discovered this charting library last week so am quite new and still exploring it too.
