### ISSUE TITLE
Add new api to support highlighting edges through action

### ISSUE THREAD

**Issue by Gahon1995** [apache/echarts#14531]
### What problem does this feature solve?
At present, only the nodes of the graph can be highlighted through action. In 4.9.0, you can configure the highlight edge through the edgeDataIndex property of action focusNodeAdjacency. In 5.0.2, the api no longer exists. I hope to add api to support it.

### What does the proposed API look like?
```
dispatchAction({
    type: 'highlight',
    seriesIndex?: number|Array,
    seriesName?: string|Array,
    dataIndex?: number,
    edgeDataIndex?: number,
    name?: string
})
```

**Comment by ZhouShangLun** [comment]
same problem! Anyone can help?

**Comment by pumpkindev** [comment]
+1

**Comment by ZhouShangLun** [comment]
一个月了，还是没得消息，开发人员可以看看吗
focusNodeAdjacency这个action真的在我的项目中很重要，我不得不单独引入4.9的版本来处理这个问题
新的版本什么时候能够支持啊

**Comment by pissang** [comment]
```js

        myChart.dispatchAction({
            type: 'highlight',
            dataIndex: 0,
            dataType: 'edge'
        })
```
