### ISSUE TITLE
How can I export (pdf png JPEG) Echart in server side using node js NOT on the client side PLZ HELP ASAP

### ISSUE THREAD

**Issue by TheLostDory** [apache/echarts#14532]
### What problem does this feature solve?
Problem of not being able to export echart in the server side. I want to export as pdf png and jpeg from the backend not from the front end how can I do it using node js

### What does the proposed API look like?
no idea

**Comment by susiwen8** [comment]
Maybe this https://github.com/chfw/echarts-scrappeteer ?

**Comment by FrankChen021** [comment]
I have implemented a node-js service which accepts echarts option from client via HTTP POST and returns base64-formatted image. You could take a look at it. 

https://github.com/FrankChen021/node-charts
