### ISSUE TITLE
BMap example not working, BMap example ES版示例代码不完整

### ISSUE THREAD

**Issue by xjhjzxh** [apache/echarts#14533]
### Version
5.0.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=heatmap-bmap
Full Code-> ES Modules not working, BMap is not defined
完整代码-> ES Modules 中的代码, 会报BMap is not defined, 请问该怎么引入

### What is expected?
use ES modules code

### What is actually happening?
BMap is not defined

**Comment by plainheart** [comment]
既然知道是百度地图扩展，那么需要先引入 百度地图 API script，然后再加载图表。
参考：https://github.com/apache/echarts/blob/master/extension-src/bmap/README.md

**Comment by xjhjzxh** [comment]
> 既然知道是百度地图扩展，那么需要先引入 百度地图 API script，然后再加载图表。
> 参考：https://github.com/apache/echarts/blob/master/extension-src/bmap/README.md
> 
> 如果想通过代码而不是 html script 引入，可以尝试利用 Promise 简单编写一个 script loader，可以参考[这里](https://github.com/plainheart/echarts-extension-gmap/issues/3#issuecomment-799873121)。

非常感谢, 已经可以使用了
