### ISSUE TITLE
Bad display of negative values in stacked line chart

### ISSUE THREAD

**Issue by sthenault** [apache/echarts#14535]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/7z4j2amo/](https://jsfiddle.net/7z4j2amo/)

### Steps to reproduce
see fiddle

### What is expected?
stacked negative values should appears relative to the point they are stacked too

### What is actually happening?
they appears as their absolute value

---
also, colored area is somewhat creative and seems to have bug wrt null value...

**Comment by de87684333** [comment]
Hi, I'm also facing it! Any update on a fix for this one?
Here is what I get:
![image](https://user-images.githubusercontent.com/41694641/173024792-e3ce373d-06c4-48ac-ac15-d2a56258483d.png)

**Comment by susiwen8** [comment]
There is a new feature in 5.3.3-rc 
- #17086
You can use it see the result.

**Comment by de87684333** [comment]
Oh that sounds great! thanks @susiwen8
