### ISSUE TITLE
legend.icon=pin has not effect

### ISSUE THREAD

**Issue by Qin-Genius** [apache/echarts#14530]
### Version
5.0.2

### Steps to reproduce
set legend.icon=pin has not effect

### What is expected?
show pin style

### What is actually happening?
circle

**Comment by plainheart** [comment]
The default width and height is `25px * 14px`. It's not so appropriate for the pin symbol. Try to adjust the size through [`legend.itemWidth`](https://echarts.apache.org/en/option.html#legend.itemWidth) and [`legend.itemHeight`](https://echarts.apache.org/en/option.html#legend.itemWidth), you will see it.
