### ISSUE TITLE
axisTick.interval not work in category axis

### ISSUE THREAD

**Issue by caizirong** [apache/echarts#14547]
### Version
5.0.2

### Reproduction link
[https://codepen.io/zzzrr/pen/ZELOPEJ?editors=1111](https://codepen.io/zzzrr/pen/ZELOPEJ?editors=1111)

### Steps to reproduce
First, the xaxis's interval was set to 3, by the axisTick props. But it not works.
Then, set axisLabel.interval to 3, it works as predicted.
So I guess the axisTick.interval has some problem ? or i use it wrong?
ps: i use the example code from official website.

### What is expected?
the xaxis interval set to 3.

### What is actually happening?
not work

---
I had read the doc and try it.
https://echarts.apache.org/en/option.html#xAxis.axisTick

**Comment by caizirong** [comment]
- axisTick.interval:
  - ![image](https://user-images.githubusercontent.com/22556734/112784456-5faa2100-9084-11eb-979c-49c5c77517e9.png)

- axisLabel.interval:
  - ![image](https://user-images.githubusercontent.com/22556734/112784503-78b2d200-9084-11eb-8ae7-605a4d1b6b32.png)

**Comment by pissang** [comment]
`axisTick.interval` only controls the tick line
