### ISSUE TITLE
The LegendOption has not icon prop?

### ISSUE THREAD

**Issue by 13554599576** [apache/echarts#14546]
![image](https://user-images.githubusercontent.com/34908374/112779017-6337ab00-9078-11eb-971e-be17dcfacf1a.png)
![image](https://user-images.githubusercontent.com/34908374/112779054-78acd500-9078-11eb-900c-343f955f77ca.png)
I must use
```
const option: echarts.EChartsOption | any = ...........
```
I think it's bad

**Comment by plainheart** [comment]
Hi, it has been fixed in #14263. Just ignore this error. Please be patient to wait for the next version.
