### ISSUE TITLE
When the trigger type of tooltip is axis, the silent property does not work.

### ISSUE THREAD

**Issue by pdsuwwz** [apache/echarts#14557]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/wangwenzhang/0fp1eghc/17/](https://jsfiddle.net/wangwenzhang/0fp1eghc/17/)

### Steps to reproduce
1. `tooltip.trigger = 'axis'`
2. `series[0].silent = true`

My requirement is to disable the hover animation of the `line`. Is there a better way?

```js
var myChart = echarts.init(document.getElementById('main'));

var option = {
  tooltip: {
    trigger: 'axis'
  },
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [{
    data: [150, 230, 224, 218, 135, 147, 260],
    type: 'line',
    silent: true, // not work 😭
    lineStyle: {
      type: 'dashed'
    }
  }]
};

myChart.setOption(option);

```

### What is expected?
Hover's prompt animation effect on the `line` should be disabled.

### What is actually happening?
The hint animation effect of hovering over the `line` is still available.

**Comment by susiwen8** [comment]
It's not easy to fix this issue elegantly. Since `trigger: axis` is listen `showTip` event from `axis` not from each `series`.
For example:
```js
                series: [
                    {
                        data: [150, 230, 224, 218, 135, 147, 260],
                        type: 'line',
                        silent: true,
                        lineStyle: {
                            type: 'dashed'
                        }
                    },
                    {
                        data: [160, 240, 234, 228, 145, 157, 270],
                        type: 'line',
                        lineStyle: {
                            type: 'dashed'
                        }
                    },
                ]
```

 The simple way is to filter `silent` series at `_showAxisTooltip`. What you think @pissang @100pah

**Comment by pdsuwwz** [comment]
> It's not easy to fix this issue elegantly. Since `trigger: axis` is listen `showTip` event from `axis` not from each `series`.
> For example:
> 
> ```js
>                 series: [
>                     {
>                         data: [150, 230, 224, 218, 135, 147, 260],
>                         type: 'line',
>                         silent: true,
>                         lineStyle: {
>                             type: 'dashed'
>                         }
>                     },
>                     {
>                         data: [160, 240, 234, 228, 145, 157, 270],
>                         type: 'line',
>                         lineStyle: {
>                             type: 'dashed'
>                         }
>                     },
>                 ]
> ```
> 
> The simple way is to filter `silent` series at `_showAxisTooltip`. What you think @pissang @100pah

Can I understand that the `showTip` of the `series` will always be triggered when the trigger is set to `axis`

No matter what `silent` is set to, because the former has higher priority than the latter 😕

**Comment by susiwen8** [comment]
> No matter what silent is set to, because the former has higher priority than the latter
There are no priority between `series`. Also, other user might consider this could be a bug, since only one series is set to `silent`,  the other need to response tooltip.
