### ISSUE TITLE
Pie: when label centered, should not move label when selected

### ISSUE THREAD

**Issue by troy351** [apache/echarts#14565]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut](https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut)

### Steps to reproduce
- Add `selectedMode: true` to the option of the given demo
- select a sector

### What is expected?
The centered label should NOT move

### What is actually happening?
The centered label did moved according to the sector user selected
![Examples - Apache ECharts - Google Chrome 2021-03-31 10-21-22 00_00_06-00_00_12 00_00_05-00_00_12](https://user-images.githubusercontent.com/8372385/113082048-5ba90b00-920c-11eb-91bb-71284cdcd6d3.gif)

**Comment by xudihui** [comment]
going to look into the issue,pie charts are often used in my business scenarios.
