### ISSUE TITLE
visualmap pieces在只有开区间设置时报错Cannot read property 'coord' of undefined

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14567]
### Version
5.0.2

### Steps to reproduce
正常：http://jsfiddle.net/facingcheer/mt7re6xg/1/
异常： http://jsfiddle.net/facingcheer/va64jt2e/5/
经过测试如果所有的pieces都是开区间 在计算stops的时候就会异常

### What is expected?
在所有pieces都设置为开区间的时候正常渲染图表

### What is actually happening?
在所有pieces都设置为开区间的时候无法渲染

**Comment by susiwen8** [comment]
Related to #12374
