### ISSUE TITLE
echarts使用雷达图时,name属性类型定义错误

### ISSUE THREAD

**Issue by itkui** [apache/echarts#14570]
> echarts使用雷达图，配置radar的name属性时，类型定义错误，查看书文件name类型为string|number
![image](https://user-images.githubusercontent.com/41995619/113177847-8b91f600-9280-11eb-9d53-846cc8fb06cb.png)
> 但是现在这里的属性可以使用对象，可以考虑加上

**Comment by plainheart** [comment]
从 5.0 开始，应该使用 `axisName` 替代。

- 选项 `radar.name` 已经不推荐使用。使用 `radar.axisName` 代替。
- 选项 `radar.nameGap` 已经不推荐使用。使用 `radar.axisNameGap` 代替。

其他变更参见：[ECharts 5 升级指南](https://echarts.apache.org/zh/tutorial.html#ECharts%205%20%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97)
