### ISSUE TITLE
官网示例页面矢量场图demo的bug

### ISSUE THREAD

**Issue by a892626178** [apache/echarts#14576]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=global-wind-visualization&gl=1](https://echarts.apache.org/examples/zh/editor.html?c=global-wind-visualization&gl=1)

### Steps to reproduce
打开deom实例链接 图加载失败 控制台报错 Uncaught TypeError: Cannot read property 'dimensions' of undefined
项目集成进来也报这个错误信息

### What is expected?
正常显示加载

### What is actually happening?
正常显示加载

**Comment by pissang** [comment]
谢谢反馈，看起来是因为这两个例子里忘记引用 bmap 组件了，已修复等上线

**Comment by a892626178** [comment]
你好 大概什么时候能上线 或者说我这边本地代码怎么修改&nbsp; 项目着急需要 感谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 官网示例页面矢量场图demo的bug (#14576)



谢谢反馈,看起来是因为这两个例子里忘记引用Bmap组件了,已修复等上线
—
你收到这个是因为你被提到了。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by pissang** [comment]
这个是示例问题，本地引入百度地图插件就行了 https://github.com/apache/echarts/tree/master/extension-src/bmap
