### ISSUE TITLE
How Can I make charts when we have lots of small values but few extremely large values.

### ISSUE THREAD

**Issue by Vishal568** [apache/echarts#14582]
### What problem does this feature solve?
When we use Small values and Large values data in Chat then small values are not visible.
We need to solution like https://chandoo.org/img/c/charting-options-large-small-data.png 

### What does the proposed API look like?
 https://chandoo.org/img/c/charting-options-large-small-data.png

**Comment by Ovilia** [comment]
We don't have a simple way to do this right now.
