### ISSUE TITLE
Remove the default background color in dark theme.

### ISSUE THREAD

**Issue by y0nd0** [apache/echarts#14586]
### What problem does this feature solve?
The default light theme background is `transparent`. But in dark mode the color is fixed dark blue (`#100C2A` (rgb: 16,12,42)) 
 I cannot find any option to replace the color. I don't want to create a complete custom color. 

### What does the proposed API look like?
Just remove the background color or / and provide an option to set the color (to transparent) without creating a custom theme. (I use `ngx-charts`, all latest versions.)

![image](https://user-images.githubusercontent.com/68586847/113439210-6620fb80-93ea-11eb-85c9-26a0010666c8.png)

**Comment by coader** [comment]
any solution? why close it?

**Comment by pissang** [comment]
Just set `option.background` to `'none'`

**Comment by coader** [comment]
should set it in global, so I have to download the dark.js and change it, then registertheme
