### ISSUE TITLE
Markline labels are shown underneath serie line.

### ISSUE THREAD

**Issue by cll123456** [apache/echarts#14589]
### Version
5.0.2

### Steps to reproduce
1. Use markLine and areaStyle in Line series.
2. Set markLine's label in insideEndTop
3. Find the text has been shelter in areaStyle.

### What is expected?
Markline labels should have higher zIndex

### What is actually happening?
Markline labels are shown underneath serie line.

---
![image](https://user-images.githubusercontent.com/41314419/113475514-c70f0900-94a8-11eb-8b23-fa3a3a4af5e9.png)

**Comment by plainheart** [comment]
Thanks for the feedback. We're looking into it. This bug will probably fixed in 5.1.0 or 5.1.1.

**Comment by cll123456** [comment]
> Thanks for the feedback. We're looking into it. This bug will probably fixed in 5.1.0 or 5.1.1.

Thank you for your reply, I'm looking forward to it

**Comment by Ovilia** [comment]
Fixed in #14542.
