### ISSUE TITLE
data not updating when we pass multiple graph data then if change it to single graph option it wont change

### ISSUE THREAD

**Issue by Darshan-agent** [apache/echarts#14581]
### Version
5.0.2

### Steps to reproduce
NOT Updating Dynamically
assign sigle option then assign multiple graph option then again assign to single graph option 

### What is expected?
it should chage dynamically

### What is actually happening?
it reatins old state

**Comment by pissang** [comment]
Use `notMerge: true` or it will merge two options.

**Comment by Darshan-agent** [comment]
Thanks pissang!
was about to release So used two individual Variables .. it worked!
