### ISSUE TITLE
draggable labelLayout option don't work with textBorderWidth

### ISSUE THREAD

**Issue by WedersonCD** [apache/echarts#14585]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/x7qg3jpL/](https://jsfiddle.net/x7qg3jpL/)

### Steps to reproduce
>set label  textBorderWidth property to a gratter value then 0.
>set labelLayout  draggable option to true.

### What is expected?
That i can change label position with drag and drop.

### What is actually happening?
I can't change label position with drag and drop..

**Comment by cyyjs** [comment]
解决了吗？

**Comment by helgasoft** [comment]
_textBorderWidth_ should be a **numeric** (not character) value, like ```textBorderWidth:2```
