### ISSUE TITLE
Setting the borderwidth property in a line chart does not work

### ISSUE THREAD

**Issue by invierno123** [apache/echarts#14594]
### Version
5.0.2

### Reproduction link
[https://jsbin.com/vanoruvozu/edit?html,output](https://jsbin.com/vanoruvozu/edit?html,output)

### Steps to reproduce
Change the value of the borderWidth property in the itemStyle and resize it. There is no change in the line chart.

### What is expected?
I hope that when I increase the value of borderWidth, the corresponding points in the line chart will get bigger, as in previous version 4

### What is actually happening?
Nothing has changed since the borderwidth was adjusted

**Comment by plainheart** [comment]
Thanks for your feedback! It seems to be brought by [51c675d](https://github.com/apache/echarts/commit/51c675d11a8ba94d3f47ed170ed5e3b8c1ee5d2e#diff-70d476daeebde08d3c11234fd7b968016f4f4a4edba807cdd76688807d6c061e). If the symbol is empty, the stroke color and line width will be overridden.

Personally, I think we should make the `borderColor` and `borderWidth` work even though it's empty.

```ts
symbolStyle.stroke || (symbolStyle.stroke = color);
// ...
symbolStyle.lineWidth == null && (symbolStyle.lineWidth = 2);
```

That is, if the user has specified borderWidth and borderColor, don't override them whatever it is empty brush.

@pissang I may not understand completely what this change was for, please let us know if the current behavior is expected.

**Comment by nangezi123** [comment]
I have it too! 
In `line` chart, `itemStyle.borderWidth` is useless，but it can work in `scatter` chart
