### ISSUE TITLE
How to get a proper xAxis animation for realtime data?

### ISSUE THREAD

**Issue by symlons** [apache/echarts#14592]
### Version
5.0.2

### Reproduction link
[https://github.com/symlons/echarts_realtimeData/blob/main/sine_function.js](https://github.com/symlons/echarts_realtimeData/blob/main/sine_function.js)

### Steps to reproduce
You are able to run the code found in the link above inside the demo section of echarts.

### What is expected?
A consistent xAxis animation.

### What is actually happening?
The problem is that the xAxis labels don't get rendered properly. As I am changing the min and max value of the xAxis dynamically. These values change in place but all the other labels would slide to the left.  It would be also nice if you could change all the values such that they slide to the left, but it seems that the labels for the xAxis are then updating to slow (=> aren't matching with the actual x values anymore).
With DataZoom it is also the case. If you zoom they sometimes change in place and sometimes they slide from the right side in to the left. How can I change it, such that all these labels change in place?

**Comment by symlons** [comment]
I resolved this issue just by using `min`. But I planned to use it in a dynamic setting, so I had then the issue that the data broke up too early like that:

![echarts](https://user-images.githubusercontent.com/63979635/113554484-b326ec80-95f9-11eb-8665-ee64b868828f.gif)

But as it turned out this issue wasn't due to setting min dynamically. Shifting the data too early lead to that issue.
So instead of shifting the data before pushing new data you should do it like that: `data = data.slice(-initial_data-buffer)`.
This prevents shifting all the data if buffer is chosen as big as new data should be updated. So finally you'll have a much smootehr animation:

![echarts_2](https://user-images.githubusercontent.com/63979635/113555574-6e9c5080-95fb-11eb-8baa-387ba084ca11.gif)

**Comment by Ovilia** [comment]
You should set `xAxis.animationDurationUpdate` and `series.animationDurationUpdate` to be the same as your update frequency (100) and `xAxis.animationEasing` and `series.animationEasing` to be `'linear'`.

**Comment by symlons** [comment]
Thank you very much!
