### ISSUE TITLE
When width lineStyle property is passed as text the line width get a random enormous size on mouse hover

### ISSUE THREAD

**Issue by WedersonCD** [apache/echarts#14591]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/qg71wz8o/](https://jsfiddle.net/qg71wz8o/)

### Steps to reproduce
>set lineStyle property to the chart
>set a text value to the width property, like '1', ,'5', etc.
>put your mouse cursor above the data point.

### What is expected?
The line width get little bigger on mouse hover 

### What is actually happening?
The line width get a really big size

**Comment by plainheart** [comment]
This should be a bug caused by the wrong calculation without converting the data type to `number` before addition. Will fix it later.

**Comment by WedersonCD** [comment]
Thanks for the quick response and correction!
