### ISSUE TITLE
显示x轴最后一个坐标刻度的同时，保证x轴刻度均匀分布

### ISSUE THREAD

**Issue by Cyycl** [apache/echarts#14604]
### What problem does this feature solve?
显示x轴最后一个坐标刻度的同时，保证x轴刻度均匀分布
demo：https://www.makeapie.com/editor.html?c=xsahoE6mP8&v=1

**Comment by Ovilia** [comment]
这两点是矛盾的，假设 dataZoom 显示的范围是 31 天，那均匀分布是要怎么分布呢？

**Comment by Cyycl** [comment]
> 这两点是矛盾的，假设 dataZoom 显示的范围是 31 天，那均匀分布是要怎么分布呢？

有什么方法能够让间隔尽量均匀，避免出现下图红框中的间隔过大
![image.png](https://i.loli.net/2021/04/07/1xikOYa7E6dM95r.png)

**Comment by Ovilia** [comment]
目前没有办法做到这一点

**Comment by zxqzylucky** [comment]
我遇到了和你一样的问题， 最后一个坐标是显示了 但是最靠近它的坐标没有显示值 却显示了axisTick  或者splitLine
