### ISSUE TITLE
setOption not working for Stacked Line Chart

### ISSUE THREAD

**Issue by symlons** [apache/echarts#14614]
### Version
5.0.2

### Reproduction link
[https://github.com/symlons/echarts_realtimeData/blob/main/setOption_Stacked%20Line%20Chart.js](https://github.com/symlons/echarts_realtimeData/blob/main/setOption_Stacked%20Line%20Chart.js)

### Steps to reproduce
You are able to run the code found in the link above inside the demo section of echarts.

### What is expected?
At the very bottom I am setting a new series object, that should be rendered:

` myChart.setOption({
     series: [
            {
            name: '搜索引擎',
            type: 'line',
            stack: '总量',
            data: [820, 932, 901, 934, 1290, 1330, 1320]
        }
         ]
 })`

### What is actually happening?
The line doesn't get rendered. You are only able to see one of them ( the one initially set).

**Comment by pissang** [comment]
If you are trying it on the example page. Please use `setTimeout` to `setOption` again.

**Comment by symlons** [comment]
I have updated it in the reproduction code. @pissang dou you mean like that?

**Comment by pissang** [comment]
@symlons Yes, it works well on the example page

**Comment by symlons** [comment]
@pissang how might I be able to show both of the lines without the transformation from the one line to the other. I thought that if they have different names they are regarded as independent charts.

**Comment by symlons** [comment]
Sorry, confused `name` with `id`. Works now with setTimeout perfectly.
