### ISSUE TITLE
custom toolbox，the show property don't work

### ISSUE THREAD

**Issue by 767683528** [apache/echarts#14618]
### Version
5.0.2

### Steps to reproduce
jsut custom the toolbox, in the feature, use show property

### What is expected?
echarts 5.0.2

### What is actually happening?
show don't work

---
no

**Comment by xudihui** [comment]
Hello @767683528 . please provide a online reproduction.

I see that the toolbox running normally
https://echarts.apache.org/examples/zh/editor.html?c=line-marker

**Comment by 767683528** [comment]
Hi I mean the custom toolbox, in the feature, it has a property "show", it don't work! just see the&nbsp;enclosure。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] custom toolbox，the show property don't work (#14618)





 
Hello @767683528 . please provide a online reproduction.
 
I see that the toolbox running normally
 https://echarts.apache.org/examples/zh/editor.html?c=line-marker

**Comment by xudihui** [comment]
Hi @767683528 ,I may still not understand your confusion, sorry

**Comment by 767683528** [comment]
Hi dear, In the last email, I put a picture in the attachment, which you can understand!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] custom toolbox，the show property don't work (#14618)





 
Hi @767683528 ,I may still not understand your confusion, sorry

**Comment by 767683528** [comment]
toolbox: {
&nbsp; &nbsp; &nbsp; &nbsp; show: true,
&nbsp; &nbsp; &nbsp; &nbsp; feature: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; myBack: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;show: false,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;title: '返回',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;icon: 'path://M473.2 276.9v-133c-4-18.4-11.7-27-20.2-30.3-17.2-6.7-37.8 8.5-37.8 8.5L95.9 395.4c-70.1 48.4-4.8 84.7-4.8 84.7L405.5 751c62.9 46 67.7-24.2 67.7-24.2V603.4c319.3-99.2 449.9 297.5 449.9 297.5 12.1 21.8 19.3 0 19.3 0 123.4-595-469.2-624-469.2-624z m0 0',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;iconStyle: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;color: "#1aaef6",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;borderColor: "#1aaef6"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;onclick: function() {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;}
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;}
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },



Hi, look this, I set the property show: false, but I still can see the icon in the toolbox, you try it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] custom toolbox，the show property don't work (#14618)





 
Hi @767683528 ,I may still not understand your confusion, sorry

**Comment by plainheart** [comment]
Thanks for the feedback. Related to #14405. Here is a PR #14408 to fix it.
