### ISSUE TITLE
echarts 在以10毫秒内刷新出现严重卡顿现象

### ISSUE THREAD

**Issue by jqiong** [apache/echarts#14615]
### Version
5.0.2

### Steps to reproduce
以每隔10毫秒进行ECHARTS渲染

### What is expected?
毫秒级流畅渲染

### What is actually happening?
严重卡顿

---
echarts 在以10毫秒内刷新出现严重卡顿现象，我们这边的项目需对图表进行10毫秒内进行渲染，但进行渲染时出现很严重卡顿，不知道有没有解决办法以达到性能要求？数据传输以WEBSOCKET进行传输，在VUE环境中使用echarts

**Comment by jqiong** [comment]
页面运行60秒后，出现浏览器卡顿现像，请你帮我看看是哪方面的问题，有无解决方案，谢谢https://codepen.io/jqiongwu/pen/eYgGabe?editors=1111

**Comment by pissang** [comment]
这个频率不需要动画了，所以可以把 animation 设为 false，然后 console.log 去掉，不然一直在页面上有打印内容肯定是越来越卡的

**Comment by jqiong** [comment]
好的，我试试

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yi ***@***.***>
发送时间: 2021年4月8日 19:26
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [apache/echarts] echarts 在以10毫秒内刷新出现严重卡顿现象 (#14615)


这个频率不需要动画了，所以可以把 animation 设为 false，然后 console.log 去掉，不然一直在页面上有打印内容肯定是越来越卡的

―

**Comment by kamanda83** [comment]
Refresh multiple charts within 10 ms at the same time, and it is a performance problem of the browser to get stuck. Whether it is ecarts or hightcharts, rendering at this frequency will be like this. Please increase your refresh time to avoid this situation
