### ISSUE TITLE
echarts-gl mousewheel zoom doesn't work

### ISSUE THREAD

**Issue by cadriel** [apache/echarts#14628]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=sphere-parametric-surface&gl=1](https://echarts.apache.org/examples/en/editor.html?c=sphere-parametric-surface&gl=1)

### Steps to reproduce
Using firefox 87 (the latest as of this writing) - visit an echarts-gl example on the official site, and try to zoom.

### What is expected?
You should be able to zoom in and out using your mouse wheel.

### What is actually happening?
Nothing zooms.

**Comment by dominic-simplan** [comment]
Same issue here.
Might be related to this commit in zrender: https://github.com/ecomfe/zrender/commit/e16f77423fcdc052722bb8c6b7abd5406dc39f43

Is there any workaround?

**Comment by dominic-simplan** [comment]
I have found a workaround:

```
window.addEventListener("DOMMouseScroll", e => {
	e.stopImmediatePropagation();
	e.target.dispatchEvent(new WheelEvent("wheel", e));
});
```
