### ISSUE TITLE
echarts5 中，鼠标悬浮到 折线上，会默认强制触发 emphasis，无法取消，而 echarts4 就不会

### ISSUE THREAD

**Issue by yongnny** [apache/echarts#14622]
### Version
5.0.2

### Steps to reproduce
echarts4 鼠标悬浮到 折线上，无特效

https://echarts.apache.org/v4/examples/zh/editor.html?c=line-stack

echarts5 鼠标悬浮到 折线上，会默认强制触发 emphasis

https://echarts.apache.org/examples/zh/editor.html?c=line-stack

我现在只能把 emphasis.lineStyle 设置为 lineStyle 一样，才绕过这个问题

### What is expected?
提供一个 开关，例如 饼图 中的 silent，当为 true 时，鼠标悬浮到 折线上，不会被 emphasis

### What is actually happening?
鼠标悬浮到 折线上，会默认强制触发 emphasis

**Comment by pissang** [comment]
@plainheart 我感觉可能 line 还是不能默认 hover 加粗

**Comment by plainheart** [comment]
我现在也是这么想的，之后可以讨论下如何优化这个逻辑。
这个 issue 说的鼠标 hover 到 line 上时，默认触发了 emphasis 状态，是不是也可以允许设置 silent 去禁止？当前好像只能整个系列 silent 而不能作用到 lineStyle 或者 itemStyle(Symbol) 上。

**Comment by pissang** [comment]
嗯，系列数量大于 1 的时候经常会把`tooltip.trigger`设置为'axis'，这个时候高亮就所有系列都高亮了，结果还是所有系列都变粗

**Comment by pissang** [comment]
@plainheart 试了几个例子，感觉主要是数据密集的时候默认加粗的效果不太好，如果数据不是很多默认加粗效果还可以

**Comment by plainheart** [comment]
对，之前提到过这个，但好像不太好知道数据怎样算是密集？

**Comment by HAM2506** [comment]
目前v5.2的版本貌似还是存在这个问题，鼠标悬浮，会默认折线高亮
