### ISSUE TITLE
through API echarts.connect to connect echarts . If a graph polyline has empty data, linkage failure。 Shows only the echart where the mouse is currently placed

### ISSUE THREAD

**Issue by baokeyu123** [apache/echarts#14623]
### Version
5.0.2

### Reproduction link
[https://codepen.io/flyfly6/pen/vmGzgq](https://codepen.io/flyfly6/pen/vmGzgq)

### Steps to reproduce

<!DOCTYPE html>
<html style="height: 100%; overflow-y:auto">

<head>
    <meta charset="utf-8">
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.0.1/echarts.js"></script>
</head>

<body>
    <div id="main1" style="width: 100%;height: 200px"></div>
    <div id="main2" style="width: 100%;height: 200px"></div>
    <div id="main3" style="width: 100%;height: 200px"></div>
    <div id="main4" style="width: 100%;height: 200px"></div>
    <div id="main5" style="width: 100%;height: 200px"></div>
    <div id="main6" style="width: 100%;height: 200px"></div>
    
</body>
<script type="text/javascript">
    var chartDom1 = document.getElementById('main1');
    var myChart1 = echarts.init(chartDom1);
    var chartDom2 = document.getElementById('main2');
    var myChart2 = echarts.init(chartDom2);
    var chartDom3 = document.getElementById('main3');
    var myChart3 = echarts.init(chartDom3);
    var option1;

    option1 = {
        title: {
            text: '折线图堆叠'
        },
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data: ['邮件营销', '联盟广告', '视频广告', '直接访问', '搜索引擎']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        toolbox: {
            feature: {
                saveAsImage: {}
            }
        },
        axisPointer: {
            show: true,
            type: 'line',
            status: true,
            triggerTooltip: true,
        },
        xAxis: {
            type: 'category',
            boundaryGap: false,
            data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],

        },
        yAxis: {
            type: 'value'
        },
        series: [{
            name: '邮件营销',
            type: 'line',
            stack: '总量',
            data: []
        }, {
            name: '联盟广告',
            type: 'line',
            stack: '总量',
            data: []
        }, {
            name: '视频广告',
            type: 'line',
            stack: '总量',
            data: []
        }, {
            name: '直接访问',
            type: 'line',
            stack: '总量',
            data: []
        }, {
            name: '搜索引擎',
            type: 'line',
            stack: '总量',
            data: []
        }]
    };

    option1 && myChart1.setOption(option1);
    option1 && myChart2.setOption(option1);
    option1 && myChart3.setOption(option1);
    echarts.connect([myChart1, myChart2, myChart3]);
</script>

</html>

### What is expected?
resolve this problem

### What is actually happening?
always

---
2.x version can resolve this problem , but 5.x version  axisPointer linkage failure

**Comment by baokeyu123** [comment]
@plainheart  @leeight @pissang   please help me to resolve this problem. thanks ~

**Comment by flycat07** [comment]
I have the same problem.
Additional explanation: Tooltip or Axispointer does not work when a series with null data is 0 index.
