### ISSUE TITLE
基础折线图显示不出来

### ISSUE THREAD

**Issue by Ganhonwei** [apache/echarts#14633]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-simple](https://echarts.apache.org/examples/zh/editor.html?c=line-simple)

### Steps to reproduce
点进去就行

### What is expected?
有数据

### What is actually happening?
什么都么有

**Comment by plainheart** [comment]
感谢反馈，已修复，可以清除浏览器缓存后重试一下。
