### ISSUE TITLE
treemap获取数据所在矩阵的宽高属性

### ISSUE THREAD

**Issue by ctrlands** [apache/echarts#14644]
### What problem does this feature solve?
以svg渲染矩阵树图，当某条数据所占比例特别小的时候，这个时候该条数据的宽或者高就会比较小，就会造成文本不显示或者显示不美观，如果能拿到每条数据所在矩阵的宽高，就可以在label的formatter里面更加灵活的去以更加美观/完整的方式展示文本信息

### What does the proposed API look like?
label: {
  formatter: (params) => {
    // params里面包含当前数据的矩阵宽高
  }
}

**Comment by pissang** [comment]
@ctrlands echarts 5.0 开始可以在 `labelLayout` 配置中根据矩形高宽配置字体，参考这个例子 https://github.com/apache/echarts/blob/master/test/treemap-obama.html#L343
