### ISSUE TITLE
自定义geoJson,无法通过geo.regions的方式给自定义区域设置areaColor

### ISSUE THREAD

**Issue by liuzhuang-bud** [apache/echarts#14641]
### Version
4.9.0

### Steps to reproduce
在geojson.io中对中国地图做了一些自定义区域之后，在echarts中的geo.regions中对新增的自定义名称的区域设置areaColor,但是无效

### What is expected?
```js
geo: {
  regions: [{
        name: '内蒙古北',
        normal: {
          areaColor: 'rgba(91,143, 249, .2)',
        },
      }]
```

### What is actually happening?
其他原生的省市颜色可以修改，但是自定义的比如这个内蒙古北就不行

**Comment by Ovilia** [comment]
It should be [geo.regions.itemStyle.areaColor](https://echarts.apache.org/en/option.html#geo.regions.itemStyle.areaColor).

**Comment by liuzhuang-bud** [comment]
用itemStyle.areaColor确实可以，只是觉得奇怪，为什么regions不work
