### ISSUE TITLE
In log axis, the length of stacked bar not accruate. 

### ISSUE THREAD

**Issue by YvonZhang** [apache/echarts#14657]
### Version
5.1.0-rc.1

### Steps to reproduce
I was using the stacked bar in the 'log' axis, and I realized the length of the second bar was still be calculated just like it was shown from the bottom: 

![image](https://user-images.githubusercontent.com/52089057/114507774-2ec21280-9c66-11eb-9663-a7e365d1363f.png)

As you can see from the pic above: especially in the red rectangle area, the actual length of these two bars was rendered as the same length. However, you can easily find out from the axis that these two bars were placed into two different "log areas" because they were "stacked together". So the right red bar should be really thin instead of having the length like the left blue one, as its value is only "10".

### What is expected?
![image](https://user-images.githubusercontent.com/52089057/114507940-67fa8280-9c66-11eb-9373-2c1a2f5bd221.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/52089057/114507774-2ec21280-9c66-11eb-9663-a7e365d1363f.png)

---
https://echarts.apache.org/examples/zh/editor.html
```
option = {
    backgroundColor:'#333',
    xAxis: {        
        type: 'log',
        min:1,
        max:10000000,
    },
    yAxis: {        
        data: ['test'],
    },
    series: [
        {
            type: 'bar',
            stack: 'foo',
            label: {
                show: true
            },
            data: [10]
        },
        {
            type: 'bar',
            stack: 'foo',
            label: {
                show: true
            },
            data: [90]
        },
        {
            type: 'bar',
            label: {
                show: true
            },
            stack: 'bar',
            data: [1000]
        },
        {
            type: 'bar',
            stack: 'bar',
            label: {
                show: true
            },
            emphasis: {
                focus: 'series'
            },
            data: [10]
        }
    ]
};
```

**Comment by YvonZhang** [comment]
For any relevant questions or solutions, please email me at zhangyuang#aipark.com. switch # to @.

**Comment by pissang** [comment]
Fixed in https://github.com/apache/echarts/pull/16338
