### ISSUE TITLE
line chart animation for dynamic data isn't smooth if max value for axes is defined

### ISSUE THREAD

**Issue by symlons** [apache/echarts#14651]
### Version
5.0.2

### Steps to reproduce
https://github.com/symlons/echarts_realtimeData/blob/main/dynamic_data_animation.js
You are able to run the code found in the link above inside the demo section of echarts.

### What is expected?
A smooth animation.

### What is actually happening?
Data gets added without any animation.

---
I had  a similiar issue for data that was disappearing (#14587) but I could solve it just by buffering the data longer. If you add new data and the axis gets updated dynamically you won't notice any issues (since the animation emerges from shifting of the axis). However if you have a fixed maximum value set for the axis you will get no animation for new added datapoints.

**Comment by pissang** [comment]
We don't support a `grow` like animation when appending data yet.

**Comment by symlons** [comment]
Ok, Thanks!
