### ISSUE TITLE
Packed bubble chart with grouping

### ISSUE THREAD

**Issue by anoosurf** [apache/echarts#14661]
### What problem does this feature solve?
something where you can group bubbles based on some size parameter -->
example -->
https://www.highcharts.com/demo/packed-bubble-split

### What does the proposed API look like?
series :'packedbubble'

**Comment by anoosurf** [comment]
![image](https://user-images.githubusercontent.com/4696146/114557168-08609f00-9c87-11eb-93a1-ed2b7622386d.png)

something like this

**Comment by ataft** [comment]
This should be possible, check the following from the Custom examples:
https://echarts.apache.org/examples/en/editor.html?c=circle-packing-with-d3

It'd be great if it was easier and more integrated into eCharts though...
