### ISSUE TITLE
Error when manually controlling selected legends: Cannot read property 'getDisplayList' of null

### ISSUE THREAD

**Issue by jdgreenberger** [apache/echarts#14662]
### Version
5.0.2

### Steps to reproduce
Use a manually controlled legend state:
const selectedLegends = {}
legend: [{selected: selectedLegends}]

When you update `selectedLegends` based on the value in the `legendselectchanged` event, the library throws an error: "Cannot read property 'getDisplayList' of null"

### What is expected?
I can manually control legends without getting an error.

### What is actually happening?
I'm getting an error.

**Comment by pissang** [comment]
The only possibility of this error I can think of is that you are using an instance that has been destroyed.
