### ISSUE TITLE
bar-race xAxis.splitLine animation is not smooth

### ISSUE THREAD

**Issue by Sweet-KK** [apache/echarts#14679]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=bar-race-country](https://echarts.apache.org/examples/zh/editor.html?c=bar-race-country)

### Steps to reproduce
the example can see xAxis.splitLine animation  is not smooth

### What is expected?
splitLine move smooth.

### What is actually happening?
splitLine move is not smooth, it seem to drop frame.
 示例中的splitLine移动变化时明显像移动一下停一下，一卡一卡的，这个有办法优化吗，尝试开启大数据、silent设为true、脏矩形优化还是没改变

**Comment by pissang** [comment]
有可能是因为我们对线条做了次像素优化永远对齐在 x.5 像素上造成的

**Comment by Sweet-KK** [comment]
> 有可能是因为我们对线条做了次像素优化永远对齐在 x.5 像素上造成的

还有一个问题，在排名切换的时候，原来不在排名，刚进入排名的数据，y轴文字是直接闪现的，不像柱子那样从下到上，从无到有的过渡。掉出排名的时候也是，一闪就没了
