### ISSUE TITLE
水波图3.8版本 以后 series使用itemStyle不生效

### ISSUE THREAD

**Issue by huyuaqian** [apache/echarts#14670]
### Version
4.8.0

### Steps to reproduce
itemStyle: {
                        shadowBlur: 0,
                    },

### What is expected?
设置水波图不要阴影效果

### What is actually happening?
阴影效果还存在

**Comment by huyuaqian** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 水波图3.8版本 以后 series使用itemStyle不生效 (#14670)





 
@huyuaqian Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.

**Comment by huyuaqian** [comment]
这个是示例，附件里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 水波图3.8版本 以后 series使用itemStyle不生效 (#14670)





 
@huyuaqian Please provide a demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.

**Comment by Ovilia** [comment]
使用 ECharts 5.1.0 + LiquidFill 3.0.0 没有问题。

**Comment by huyuaqian** [comment]
你好，可以把你用的echarts，LiquidFill的两个版本的js发我吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenli ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 中午12:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 水波图3.8版本 以后 series使用itemStyle不生效 (#14670)





 
使用 ECharts 5.1.0 + LiquidFill 3.0.0 没有问题。

**Comment by pissang** [comment]
@huyuaqian 都可以在 CDN 上找到

**Comment by huyuaqian** [comment]
想请问一个问题，这个水波图支持ie10,11吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 水波图3.8版本 以后 series使用itemStyle不生效 (#14670)





 
@huyuaqian 都可以在 CDN 上找到
