### ISSUE TITLE
bmap lines tooltips not surpport?

### ISSUE THREAD

**Issue by stormrise** [apache/echarts#14672]
### Version
5.0.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-bus
```ts
tooltip: {
            formatter: function (e) {
                return e;
            }
        },
```
add this before bmap, nothing happend

### What is expected?
https://echarts.apache.org/examples/zh/editor.html?c=lines-airline

should like geo coordinateSystem, the tooltip should show

### What is actually happening?
nothing happend

**Comment by pissang** [comment]
You need to remove `silent` option in the examples

**Comment by stormrise** [comment]
thanks, it works
