### ISSUE TITLE
Please add support for slice visibility threshold in Pie Chart

### ISSUE THREAD

**Issue by junlincc** [apache/echarts#14684]
### What problem does this feature solve?
Let’s say that some “slices” of your pie are very small. You might be fine with these options being grouped together so that people reading your report can focus on the big results. The Grouping Percentage Threshold allows you to establish the minimum percentage a portion of the pie chart should have before it gets lumped into an “All Others” category.

Example: In a pie chart “category A” makes up 20% of the pie, as do “category B” and “category C” If we set the Grouping Percentage Threshold to 25%, “category A” “category B”and “category C” would be grouped into one category called “All Others” that took up the collective 60% of the pie.
<img width="536" alt="Screen Shot 2021-04-15 at 11 17 48 PM" src="https://user-images.githubusercontent.com/67837651/114980127-dbf08280-9e40-11eb-89e9-667c720f6a0b.png">

**Comment by villebro** [comment]
It could be nice to have to options:
- `labelThreshold`: minimum threshold that determines which labels and label lines should be drawn. Similar to the `labelThreshold` property on NVD3 Pie Chart: https://nvd3.org/examples/pie.html
- `sliceThreshold`: minimum threshold that determines which slices should be drawn as separate slices and which should be grouped into an "Other" category.

**Comment by junlincc** [comment]
@Ovilia if the request is aligned with your product strategy, we(Apache Superset) are happy to contribute this feature :)

**Comment by Ovilia** [comment]
@villebro I think there may also be cases where slices should be merged if the slice amount reachs a threshold. For example, if data values could be `8%, 7%, 7.2%, 7.1%, 6.4%, ...` or `53%, 4%, 3.2%, ....` and the developer may not have a clue to how these values distribute, it may not be a good idea to set a value threshold in this case. In stead, a slice amount threshold is more helpful. For example, we can show the largest 5 slices and merge the others. I think maybe both the policy should be provided. Your PR may not implement them both, but should give the consideration of API design for such future features.

**Comment by Ovilia** [comment]
Or, would it be helpful if we provide a `mergePolicy` callback to let developers decide how slices should be merged?

**Comment by villebro** [comment]
> @villebro I think there may also be cases where slices should be merged if the slice amount reachs a threshold. For example, if data values could be `8%, 7%, 7.2%, 7.1%, 6.4%, ...` or `53%, 4%, 3.2%, ....` and the developer may not have a clue to how these values distribute, it may not be a good idea to set a value threshold in this case. In stead, a slice amount threshold is more helpful. For example, we can show the largest 5 slices and merge the others. I think maybe both the policy should be provided. Your PR may not implement them both, but should give the consideration of API design for such future features.

Excellent point @Ovilia , and now that you mention it, actually something I've run into.

> Or, would it be helpful if we provide a `mergePolicy` callback to let developers decide how slices should be merged?

Yes, this is an even better design, as it will make it easy to customize. I'll start working on a callback based approach.

**Comment by Ovilia** [comment]
Another consideration is, should `"The others"` slice have a special color (gray?) or use the color palette by default?

**Comment by villebro** [comment]
> Another consideration is, should `"The others"` slice have a special color (gray?) or use the color palette by default?
> Tooltip and legend should also be taken care of.

I think it could default to grey or some other "downgraded" color, of course with the option to define a custom one. Regarding tooltip/legend, we can experiment with different options and see what looks best (we can potentially ask our design team to come up with a few suggestions if you'd like).

**Comment by Ovilia** [comment]
@villebro Cool! @pissang @100pah would give you some further discussion on this issue.

**Comment by villebro** [comment]
I set out to implement `labelThreshold`, and when I started adding the code I found `minShowLabelAngle` which essentially does this (it just needs to be converted from percentages to angles). So this feature already exists. Next I'll work on adding slice grouping (the "other" slice for slices that fall below a predefined threshold) as discussed.

**Comment by Ovilia** [comment]
@villebro Yes, `minShowLabelAngle` does this.
Great! Looking forward to your PR.

**Comment by jbest** [comment]
Bump, I needed this feature today, but was able to get the result I needed with a custom query (based on http://www.silota.com/docs/recipes/sql-top-n-aggregate-rest-other.html) the work arounds mentioned in #19182
