### ISSUE TITLE
在折线图中，无法使线特效跟随平滑曲线路径运动

### ISSUE THREAD

**Issue by kaixindmr** [apache/echarts#14683]
### Version
4.9.0

### Steps to reproduce
在折线图中，找不到相关属性使线特效跟随平滑曲线路径运动

### What is expected?
预期实现特效跟随曲线平滑运动
![90](https://raw.githubusercontent.com/kaixindmr/blogimages/main/90.gif)

### What is actually happening?
实际特效沿直线运动
![23](https://raw.githubusercontent.com/kaixindmr/blogimages/main/23.gif)

**Comment by pissang** [comment]
可以参考下这个例子 https://www.makeapie.com/editor.html?c=xej_kyvXOg

**Comment by kaixindmr** [comment]
> 可以参考下这个例子 https://www.makeapie.com/editor.html?c=xej_kyvXOg
这是不错的解决方案，但是我目前采用lines类型的路径图尾迹特效，（路径）它并没有跟随曲线运动

**Comment by pissang** [comment]
尾迹图不是为折线图设计的

**Comment by kaixindmr** [comment]
> 尾迹图不是为折线图设计的

thank

**Comment by suirenxing** [comment]
> > 尾迹图不是为折线图设计的
> 
> thank



> > 可以参考下这个例子 https://www.makeapie.com/editor.html?c=xej_kyvXOg
> > 这是不错的解决方案，但是我目前采用lines类型的路径图尾迹特效，（路径）它并没有跟随曲线运动

参考链接打不开了，能提供个新的参考链接吗

**Comment by suirenxing** [comment]
> 尾迹图不是为折线图设计的

参考链接打不开了，能提供个新的参考链接吗

**Comment by suirenxing** [comment]
> 可以参考下这个例子 https://www.makeapie.com/editor.html?c=xej_kyvXOg

参考链接打不开了，有新的地址可供参考吗
