### ISSUE TITLE
Using sampling with connectNulls connects regular datapoints with null ones when zoomed out

### ISSUE THREAD

**Issue by tmscer** [apache/echarts#14689]
### Version
5.1.0

### Reproduction link
~[https://codepen.io/tmscer/pen/wvgxKNR](https://codepen.io/tmscer/pen/wvgxKNR)~
[https://codepen.io/tmscer/pen/yLgGXbo](https://codepen.io/tmscer/pen/yLgGXbo)

### Steps to reproduce
Use a series line with `connectNulls: false` and `sampling: 'lttb'` (may be reproducible with other sampling methods) and have a null value in your data.

### What is expected?
I'd expect null values to never be connected with regular values.

### What is actually happening?
When zoomed out, regular values are connected with null values. When zoomed in, the line between regular values and nulls disappears and behaves as expected.

---
I suspect this may be caused by the sampling algorithm since when no sampling is used, null values are never connected with regular ones.

I'm not sure what version of Echarts is used in the codepen, however, the bug is reproducible in 5.1.0. To see the bug, zoom in the flat line. At the end of it, there is a null.

**Comment by tmscer** [comment]
## Images

### When zoomed out
![2021-04-16_20-45-59](https://user-images.githubusercontent.com/7033199/115070165-dbb1bf00-9ef4-11eb-8141-6a3940ac8d90.png)

### When zoomed in
![2021-04-16_20-46-07](https://user-images.githubusercontent.com/7033199/115070198-e8ceae00-9ef4-11eb-9a46-f6091162841c.png)

**Comment by tmscer** [comment]
I've simplified the example. I removed as much as possible, however, to see the bug, some data (~1600 datapoints) is left in the example to actually see the bug. See https://codepen.io/tmscer/pen/yLgGXbo.

There is a `null` value on line 634 with which other datapoints shouldn't be connected. I suspect sampling may play a role since once removed, the null value is no longer connected. Zooming, as per issue's first comment, disconnects the `null` datapoint.

Let me know if the demo is simple enough. But I am afraid that further significant simplification isn't possible.

**Comment by Ovilia** [comment]
@tmscer Thanks. I think we can get on it based on this.

**Comment by OrestHk** [comment]
Hi ! 
First of all thx for the library, started using it this week ! It's just awesome ! Easy to use, with customization and performance !

I'm having a similar issue in my project
https://codepen.io/test45/pen/RwKEBqN. Here's another sample if it can help ! With a bit more holes (null values)

As for Tmscer example, the problem seems only to appear when using LTTB sampling method, and when the algorithm is applied to the serie. When the zoom level allow to display all points on the chart, the problem disappear. Guess it as something to do with the algorithm handling null / undefined values in the serie.

Sorry if the english is a bit messy !
And thanks again for your work !

**Comment by tmscer** [comment]
I see that `5.2.0` has been released, should the milestone be updated or is it possible that this bug will be fixed in some `5.2.x`?

**Comment by tmscer** [comment]
@Ovilia.

**Comment by chenlijun99** [comment]
I reported the same issue in #13228

**Comment by sglvladi** [comment]
Hi there! Any updates on this?

**Comment by pissang** [comment]
Seems it's because the null values are filtered during sampling

**Comment by tmscer** [comment]
> Seems it's because the null values are filtered during sampling

An idea: a null value should then split the dataseries into separate chunks that can be then sampled separately.
