### ISSUE TITLE
 emphasis-focus-adjacency when click

### ISSUE THREAD

**Issue by YinZhaoJie** [apache/echarts#14685]
### What problem does this feature solve?
如何在echarts5 的graph上 实现 “鼠标点击（而不是鼠标悬停） 会有 emphasis-focus-adjacency 效果” 呢？ 我试过以下方法，但是不起作用 可能操作不对（前端水平有限，不会vue 这个可能要节和vue实现） 
```ts
myChart.dispatchAction({
          type: 'focusNodeAdjacency',
          // 使用 dataIndex 来定位节点。
          dataIndex: params.dataIndex
        });
```
参考链接 http://t.cn/A6cfwSqs

### What does the proposed API look like?
 emphasis-focus-adjacency when click

**Comment by lopo12123** [comment]
这个是v4的api, v5的不改源码的话似乎没有这个action了，我为了这个功能用回了v4 ┭┮﹏┭┮
