### ISSUE TITLE
renderItem 柱状图X轴定位问题

### ISSUE THREAD

**Issue by hzyyy** [apache/echarts#14682]
### Version
5.0.2

### Reproduction link
[https://codesandbox.io/s/compassionate-hypatia-hfh9x?file=/src/App.vue](https://codesandbox.io/s/compassionate-hypatia-hfh9x?file=/src/App.vue)

### Steps to reproduce
官网案例也是如此，第一根柱子定位异常。

### What is expected?
期望能够定位正常

### What is actually happening?
X轴的第一根柱状图定位异常；导致鼠标移到柱子上时，焦点框和柱子不在同一条垂直线上。

---
https://echarts.apache.org/examples/zh/editor.html?c=custom-story-transition
这是官网提供的例子，它也是第一根柱子没有靠左边

**Comment by hzyyy** [comment]
![image](https://user-images.githubusercontent.com/33852158/114959158-0f5dfc00-9e97-11eb-83fe-f72f128d51ad.png)
补充“bug”的复现

**Comment by docodocool** [comment]
![image](https://user-images.githubusercontent.com/23123540/114960577-eab75380-9e99-11eb-89db-3714090d3d69.png)

**Comment by hzyyy** [comment]
已解决，多谢大佬。
