### ISSUE TITLE
Connected tooltip lags and glitches on paired chart

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14695]
### Version
5.1.0 (Firefox)

### Steps to reproduce
```js
echarts.connect([chart1, chart2]);
```

### What is expected?
Tooltips animate in unison.

### What is actually happening?
The tooltip of the paired chart that the user is *not* interacting with lags behind the one that the user *is* interacting with. In 5.1.0, it becomes even worse, starting to "glitch out", by warping to random positions at single frame intervals.

#### 5.0.2 (lag)
![rDhbR0I2Sw](https://user-images.githubusercontent.com/470626/115108097-87dfbe00-9f66-11eb-9539-84880e0b3542.gif)

#### 5.1.0 (lag and glitching)
![exH7P8l1M5](https://user-images.githubusercontent.com/470626/115108216-1eac7a80-9f67-11eb-89e8-54f96f2a47d0.gif)

**Comment by pissang** [comment]
@plainheart Is this related to the new `transform` enhancement in tooltip?

**Comment by plainheart** [comment]
I'm not very sure yet. I have known about this issue since the initial development. But it seems it only occurs when `transition: transform` is enabled and the dev tool is open.

**Comment by pissang** [comment]
@plainheart Remind me that we also met some lag performance issues when devtool is open.

**Comment by Bilge** [comment]
@pissang Please note, in the example videos, I am using Firefox. Devtools are not open.

After examining the results in Chrome, I understand why you were talking about the dev tools (developer console). Yes, in Chrome, it seems to work perfectly well *unless* the developer console is open. _However_, in Firefox this is a problem all the time, whether the console is open or not. Therefore I think this is quite a serious issue.

**Comment by plainheart** [comment]
Does the tooltip issue only occur in the connected charts? I just ran the simple [line demo](https://echarts.apache.org/examples/en/editor.html?c=line-stack) in Firefox 88, it's even working better than Chrome even if the devtools is open.

**Comment by Bilge** [comment]
Yes, only the connected chart is impacted.

**Comment by plainheart** [comment]
I checked a connected chart in firefox, it looks okay. https://codepen.io/plainheart/pen/KKarOZb

**Comment by Bilge** [comment]
Doesn't look that good to me.

![Uploading kOj75m79Sz.gif…]()

**Comment by plainheart** [comment]
Seems so. I updated the data, it can be reproduced in Firefox.

**Comment by Bilge** [comment]
@plainheart Thank you for making the simple test case. I hope you can figure out a fix.

**Comment by plainheart** [comment]
@Bilge Hi, I updated the ECharts lib used in the demo. I checked it in Firefox, it seems okay. Could you help check it again with your environment? Thanks.

**Comment by Bilge** [comment]
@plainheart It's good 😁 👍

**Comment by plainheart** [comment]
@pissang To find out why the tooltip is lagged and shakes from side to side, especially in the connected charts, I dug slightly into the related source code. Currently, I'm thinking it may be for the method `TooltipView#_updatePosition` will be very frequently called when `mousemove`. Only in 4ms, it seems to be called many times. The normal chart can work smoothly, but in the connected chart, it will become worse. As far, I tried to throttle the `_updatePosition` function in `50ms`(the tested result may need to validate), it's working better in both Chrome(with the devtools open) and Firefox even if we use the previous way `left/top`.

Here is the demo using the ECharts lib based on this temporal solution, it seems to be working well in Firefox and Chrome with the devtools open. https://codepen.io/plainheart/pen/KKarOZb

The branch for this change is https://github.com/apache/echarts/tree/fix-tooltip. Related test case is `tooltip-lag-glitch.html`.

**Comment by Raphyyy** [comment]
Hello,
I am figured the same issue but it occurs only in Chrome when I open the devtools console. All is working fine with Firefox.
When the devtools console is closed :
![oer87Erkjb](https://user-images.githubusercontent.com/13983107/118139658-df5b3780-b407-11eb-8771-746b4b4dc857.gif)
When I open the devtools : 
![zzeze](https://user-images.githubusercontent.com/13983107/118139711-ed10bd00-b407-11eb-84fb-3302c9f2bebe.gif)
Here is the config : https://pastebin.com/LVLMdn3G

**Comment by Bilge** [comment]
@plainheart Why is this still not merged? I can't upgrade whilst this issue still persists.

**Comment by plainheart** [comment]
@Bilge Sorry for putting this matter on hold. I've opened PR #15683 to make it go ahead.

**Comment by Bilge** [comment]
@plainheart Very good, thank you!
