### ISSUE TITLE
Custom 的 itemstyle 里希望也可以应用 borderRadius 属性

### ISSUE THREAD

**Issue by Uzizkp** [apache/echarts#14694]
### What problem does this feature solve?
Im trying to draw a gant, but seems like the official documentations and examples didn't give the way to add border radius to those kind of rect, is there anyone know how to deal with it ?

### What does the proposed API look like?
Itemstyle 的 borderradius 属性覆盖所有类目

**Comment by pissang** [comment]
You can use `shape.r` to control the border radius in the rect element.

**Comment by Uzizkp** [comment]
> You can use `shape.r` to control the border radius in the rect element.

It works, Thank u.
