### ISSUE TITLE
markLine requires symbolOffset (BC break)

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14696]
### Version
5.1.0

### Steps to reproduce
```js
            series: [{
                step: 'end',
                data: AppCharts.dataset,
                markLine: {
                    data: [
                        {
                            yAxis: 123,
                            lineStyle: {
                                color: '#fff3',
                            },
                            label: {
                                formatter: 'min\n${c}',
                                fontSize: 12,
                                color: '#677a59',
                            },
                        },
                    ],
                },
            }],
```

**N.B.** This is valid in 5.0.2.

### What is expected?
`symbolOffset` should be optional.

### What is actually happening?
`symbolOffset` is required.

> TS2322: Type '{ yAxis: number; lineStyle: { color: string; }; label: { formatter: string; fontSize: number; color: string; }; }' is not assignable to type 'MarkLine1DDataItemOption | MarkLine2DDataItemOption'.
  Property 'symbolOffset' is missing in type '{ yAxis: number; lineStyle: { color: string; }; label: { formatter: string; fontSize: number; color: string; }; }' but required in type 'MarkLine1DDataItemOption'.

**Comment by plainheart** [comment]
Thanks for the feedback. It has been fixed by #14693.
