### ISSUE TITLE
Reverse stacking order for line charts

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14700]
### What problem does this feature solve?
The stacking order of a stacked line chart is determined by the order in which the series are defined. However, this definition order also determines the order of other components, such as the legend, tooltip and dataset. When one wants to reverse the stacking order, currently the only option is to redefine the order the series are defined in. Unfortunately, this implies the order show in the legend and tooltip may be the reverse of what we want. Generally, redefining the series order may adversely impact other components and feels like the wrong approach to redeclare the data to suit the presentation.

It is worth noting the tooltip can work around this because it has an `order: 'seriesDesc'` option, and also custom formatting option, but the legend does not. Again, in general it feels like the wrong approach to design every component to be "reversible", when this is just a presentation problem.

### What does the proposed API look like?
 It would probably be best if there was simply an option to draw the stacked series in reverse order so all the other components will continue to work as normal.

**Comment by Ovilia** [comment]
Just to clearify, if the data order is depended on the value while a line series has multiple y values on each x value, how should we decide the order to the series?

**Comment by Bilge** [comment]
I'm not sure if you're just asking to confirm my question or if you're asking me to suggest a solution. That is what I am asking, yes. If you're asking me for a solution, however, I'm not sure. The two options should be: 

1. Provide an option to reverse the display order of stacked line series.
2. Provide an option to reverse the display order of the legend items.

I would normally prefer the first for the reasons already stated. Other charting libraries simply present an option to reverse the stacked line series but since ECharts specifies each lines as a separate series, such an option would have to be present on each line, which doesn't really make sense because it implies some lines can be reversed and some cannot: such a configuration is impossible; it only makes sense to reverse the entire stack or none at all. Therefore, even though I think providing an option to reverse the draw order for a stacked series, I do not have a good proposal for how to implement it in ECharts at this time.

**Comment by Ovilia** [comment]
@Bilge Could you give some pictures on what is expected? By now, I'm a little confused about the expected behavior.

**Comment by Bilge** [comment]
@Ovilia Thank you for giving me the opportunity to explain myself again with pictures. Hopefully this will make things clearer.

Here is a picture of what we want to achieve:

![image](https://user-images.githubusercontent.com/470626/115929899-7758a780-a480-11eb-9557-a334ca96a9b4.png) 😁 ✔️ 

This picture is created with different charting software (not ECharts 😞).

To recreate this with ECharts we might do something like this:

```js
color: ['#00e396', '#bd2b41'],
series: [
    {
        name: 'Positive reviews',
        stack: 'reviews',
    },
    {
        name: 'Negative reviews',
        stack: 'reviews',
    },
],
```

This creates the following chart:

![image](https://user-images.githubusercontent.com/470626/115930253-0a91dd00-a481-11eb-933f-af0596ba23f4.png) 🤔 ❌ 

Notice that the stacking order is wrong: we want the positive series (green `#00e396`) ***above*** the negative series (red `#bd2b41`).

Currently, the only way to do this is to **redefine the order** the series are declared in (which also means we need to swap the colour definition order), like this:

```js
color: ['#bd2b41', '#00e396'],
series: [
    {
        name: 'Negative reviews',
        stack: 'reviews',
    },
    {
        name: 'Positive reviews',
        stack: 'reviews',
    },
],
```

This creates the following chart:

![image](https://user-images.githubusercontent.com/470626/115931248-b851bb80-a482-11eb-8c9f-acd41d015c54.png) 😫 ❌ 

This fixes the stacking order of the line series, but it causes the **legend** and **tooltip** to reverse order, which we do not want. We can fix the tooltip by asking it to also reverse its order as follows (or by writing a custom formatter).

```
tooltip: {
    order: 'seriesDesc',
},
```

![image](https://user-images.githubusercontent.com/470626/115931063-6e68d580-a482-11eb-86ea-c67921eedf1d.png) 😩💨 ❌ 

But this still leaves the legend order being the opposite of what we want and there is **no way to reverse the legend order**.

---

All this brings me back to my point: I could request that you add a way to **reverse the legend order**, but I don't think it's a good solution. All we wanted to do was **reverse the stacking order** of the lines series, so it would be better to have an option to just do that **without changing the series declaration order**, which causes all other components' behaviour to change in ways that we do not want.

**Comment by pissang** [comment]
Hi @Bilge `legend.data` can be given in any order.

```ts
legend: {
  data: ['Positive reviews', 'Negative reviews']
}
```

**Comment by Bilge** [comment]
@pissang This does solve my immediate problem, but so many things have to be changed to accommodate the reversed series: 

* Colour order must be reversed.
* Legend must be changed (explicitly declare order).
* Tooltip must be changed.

All because we just wanted to draw the chart differently. I still think a better solution would be to have an option to control the stacking order without changing the data order.
