### ISSUE TITLE
滑过控制台报错 滑过不显示内容 官网新版本不行 老版本可以

### ISSUE THREAD

**Issue by h18335339669** [apache/echarts#14708]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=map-HK](https://echarts.apache.org/examples/zh/editor.html?c=map-HK)

### Steps to reproduce
滑过报错 滑过不显示内容 官网新版本不行 老版本可以

### What is expected?
滑过可以显示内容

### What is actually happening?
滑过未显示内容且控制台报错

---
老版本连接 https://echarts.apache.org/v4/examples/zh/editor.html?c=map-HK

**Comment by plainheart** [comment]
感谢反馈，#14704 会修复该问题。
