### ISSUE TITLE
Typo in `src/util/types.ts`

### ISSUE THREAD

**Issue by shijieyao** [apache/echarts#14716]
### Version
5.1.0

### Steps to reproduce
It seems to a quick report of an easy-fix bug, so pardon me for not providing reproduction steps.

### What is expected?
Successful compilation.

### What is actually happening?
Error: node_modules/echarts/types/dist/echarts.d.ts:6391:14 - error TS1005: ']' expected.

6391     [key in ${ComponentMainType}Index]: number;
                  ~
node_modules/echarts/types/dist/echarts.d.ts:6391:38 - error TS1005: ';' expected.

6391     [key in ${ComponentMainType}Index]: number;
                                          ~
node_modules/echarts/types/dist/echarts.d.ts:6391:39 - error TS1128: Declaration or statement expected.

6391     [key in ${ComponentMainType}Index]: number;
                                           ~
node_modules/echarts/types/dist/echarts.d.ts:6392:1 - error TS1128: Declaration or statement expected.

6392 } & {
     ~
node_modules/echarts/types/dist/echarts.d.ts:6392:3 - error TS1109: Expression expected.

6392 } & {
       ~
node_modules/echarts/types/dist/echarts.d.ts:6393:29 - error TS1005: ',' expected.

6393     [key in string]: unknown;
                                 ~m

**Comment by pissang** [comment]
Hi @shijieyao . It's not a typo. It's because we are using typescript template string feature which is introduced in typescript@4.1.0. It's not expected and will break the project using older typescript versions. We will fix it ASAP. Thanks for the feedback

**Comment by shijieyao** [comment]
I see. Thanks for the prompt reply!

**Comment by junchaohu** [comment]
Same issue here, wish for resolve

**Comment by Abattista96** [comment]
I have the same issue, also with the last update 5.1.1

**Comment by pissang** [comment]
@Abattista96 5.1.1 should have fixed it. Do you mind providing your reproducible code?

**Comment by junchaohu** [comment]
@pissang  Already fixed in my project, thanks.

**Comment by Abattista96** [comment]
> @Abattista96 5.1.1 should have fixed it. Do you mind providing your reproducible code?

I updated the lib version from 4.9 to 5.1.0, now to 5.1.1.
When i try to compile first time after the update i receive the error from some node_module unfinded, from the second compile the code give me the same error above and fail to compile in all cases. I really don't know what to do
