### ISSUE TITLE
How to set the background image of grid (only the area of coordinate system except axis)

### ISSUE THREAD

**Issue by DearMrJ** [apache/echarts#14714]
### What problem does this feature solve?
The distribution of the scatter map corresponds to the position on the background image which I generated

### What does the proposed API look like?
```ts
option: {
  grid: { backgroundColor: ..},
  backgroundColor:..,
  graphic: {
    style: {
      type: 'image',
      ...
      style: { image: ..., 
         x: instance.grid._rect.x,  // offsetX
         y: instance.grid._rect.y,  // offsetY
         width: instance.convertToPixel({grid:..}, [max(x), 0][0] - offsetX)
         height: instance.convertToPixel({grid:..}, [max(x), 0][1] - offsetY)}
    }
  }
}
```

I have try these three attrs in different time, but none of them could work

**Comment by plainheart** [comment]
You will need to set as follows,

```js
grid: {
    show: true, // must be true if backgroundColor is needed.
    backgroundColor: ...
}
```

**Comment by DearMrJ** [comment]
> You will need to set as follows,
> 
> ```js
> grid: {
>     show: true, // must be true if backgroundColor is needed.
>     backgroundColor: ...
> }
> ```

thanks, I have tried this before with attr 'show',
but I need a **background image** instead of background color.

**Comment by plainheart** [comment]
@DearMrJ Sorry for missing the keyword. You may configure like this,
```js
grid: {
    show: true,
    backgroundColor: {
        image: 'https://picsum.photos/1000/800', // Can be URL/HTMLImageElement/HTMLCanvasElement
        repeat: 'no-repeat'
    }
}
```

**Comment by DearMrJ** [comment]
@plainheart Thanks, I hava tried the way you've given, one more question, how can I make the bg image display completely and fill the whole grid automatically？

> @DearMrJ Sorry for missing the keyword. You may configure like this,
> 
> ```js
> grid: {
>     show: true,
>     backgroundColor: {
>         image: 'https://picsum.photos/1000/800', // Can be URL/HTMLImageElement/HTMLCanvasElement
>         repeat: 'no-repeat'
>     }
> }
> ```

**Comment by plainheart** [comment]
It seems there is currently no way to do it. Maybe this can be an enhancement.

**Comment by plainheart** [comment]
@DearMrJ Hi, I just thought out a workaround. Here is the demo: https://codepen.io/plainheart/pen/bGgmGPj. Hope that helps.

**Comment by DearMrJ** [comment]
@plainheart Hi，I have tried this way before by using attr graphic(see below), but it also **left some space** which is similar to the demo. it seems that we got a fake grid width/height. Why space remain after filling and how can I solve it?
```js
const graphic = {
          type: 'image',
          id: 'bgImg',
          $action: 'replace',
          bounding: 'all',
          style: {
            // image: 'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/5d6034a85edf8db18e821f720a23dd54564e7473.jpg',
            image: this.image,
            x: this.defInfoChart._api.getCoordinateSystems()[0]._rect.x,
            y: this.defInfoChart._api.getCoordinateSystems()[0]._rect.y,
            width: this.defInfoChart.convertToPixel({ gridId: 'grid1' }, [this.chartData.pnl_w, 0])[0] - this.defInfoChart._api.getCoordinateSystems()[0]._rect.x, // max(x) - offsetX
            height: this.defInfoChart.convertToPixel({ gridId: 'grid1' }, [this.chartData.pnl_w, 0])[1] - this.defInfoChart._api.getCoordinateSystems()[0]._rect.y // max(y) - offsetY
          }
        }
        this.defInfoChart.setOption({ graphic: graphic })
```

> @DearMrJ Hi, I just thought out a workaround. Here is the demo: https://codepen.io/plainheart/pen/bGgmGPj. Hope that helps.

**Comment by plainheart** [comment]
Why not use `myChart._api.getCoordinateSystems()[0].getRect().width`?

**Comment by DearMrJ** [comment]
@plainheart I have tried that before, but it did not work, the same with above one. why space remain after filling bgImg with the grid rect size? it's disturbing.
![image](https://user-images.githubusercontent.com/52528607/115331748-16537a00-a1c9-11eb-9e68-9c49e5287012.png)

**Comment by plainheart** [comment]
I don't know the complete code yet. In the demo I provided above, it works, but it doesn't use `graphic`, for your reference.

**Comment by plainheart** [comment]
Or maybe you can try to set like this if your `image` is `HTMLImageElement`,
`img.width` to `myChart._api.getCoordinateSystems()[0].getRect().width`
`img.height` to `myChart._api.getCoordinateSystems()[0].getRect().height`

Then remove the two lines

![image](https://user-images.githubusercontent.com/26999792/115332576-af36c500-a1ca-11eb-9c7b-4d4994b9f352.png)

**Comment by DearMrJ** [comment]
@plainheart it get the same value finally, and there is a flaw in the demo, **space** remain after filling bgImg (Please see below).
![image](https://user-images.githubusercontent.com/52528607/115332919-53207080-a1cb-11eb-8876-7bcbc4f83562.png)

**Comment by plainheart** [comment]
> it get the same value finally, and there is a flaw in the demo, **space** remain after filling bgImg (Please see below).

But I got the expected result. Are there some special steps I need to notice?

https://user-images.githubusercontent.com/26999792/115333899-0342a900-a1cd-11eb-8e2d-c7b8b9ae37c7.mp4


Besides, I run the code based on your demo, it's also working now.
```js
var image = new Image();
image.src = 'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/5d6034a85edf8db18e821f720a23dd54564e7473.jpg'
image.onload = function() {
    var rect = myChart._api.getCoordinateSystems()[0].getRect();
    image.width = rect.width;
    image.height = rect.height;
    myChart.setOption({
        graphic: [{
            id: 'bg',
            type: 'image',
            style: {
                image: image,
                x: rect.x,
                y: rect.y
            }
        }]
    });
    // TODO listen to resize, update the width/height/x/y of image according to the grid rect
}
```

**Comment by DearMrJ** [comment]
@plainheart I found this demo perform differently at different screen resolutions(exp. [1024 * 768], [1280 * 1024])
[1024 * 768]
![image](https://user-images.githubusercontent.com/52528607/115343503-9f28e080-a1de-11eb-846e-dc9e30a374a0.png)
[1280 * 1024]
![image](https://user-images.githubusercontent.com/52528607/115343816-09418580-a1df-11eb-8ff3-b199250becf1.png)

**Comment by plainheart** [comment]
@DearMrJ I updated the demo. Please try it again and check if this issue still exists.

**Comment by DearMrJ** [comment]
@plainheart Yes, it still exists, test by chrome's toggle device toolbar.

**Comment by plainheart** [comment]
@DearMrJ It should be fixed.

**Comment by plainheart** [comment]
@DearMrJ I checked and it passed. Could you help check if it works for you now?

**Comment by DearMrJ** [comment]
@plainheart Thanks, it does well with normal image src url type , but there are flaws when using **dataurl/blobUrl** (tried in the online demo)
![image](https://user-images.githubusercontent.com/52528607/115381446-276eac00-a206-11eb-9e56-c190f99bec97.png)

**Comment by plainheart** [comment]
How do you use the dataURI? If I replaced the `img.src` with a base64-encoded image URI in the demo, it still works.

**Comment by DearMrJ** [comment]
@plainheart Sorry, there is no problem with demo, the base64-encoded image which I generated contains extra spaces. 
Thanks again for your help!

**Comment by sharma123sunil** [comment]
Facing issues in binding dynamic images on xAxis -
const chart_data = [
  {
    type_of: "average",
    icon: 'https://d1a6mr3nq6i4pn.cloudfront.net/co2Reports/assets/images/flag-1.svg',
    value: 2.6769,
    noOfDays: 3,
    vehicleType: "car"
  },
  {
    type_of: "day",
    icon: 'https://d1a6mr3nq6i4pn.cloudfront.net/co2Reports/assets/images/flag-1.svg',
    value: 4.0154,
    noOfDays: 2,
    vehicleType: "bike"
  },
  {
    type_of: "day",
    icon: 'https://d1a6mr3nq6i4pn.cloudfront.net/co2Reports/assets/images/flag-2.svg',
    value: 0,
    noOfDays: 1,
    vehicleType: "train"
  }
];

// Prepare the rich configuration dynamically
const rich_data = {};

// Iterate through chart_data to populate rich_data
chart_data.forEach(item => {
  rich_data[item.vehicleType] = {
    height: 40,
    align: 'center',
    backgroundColor: {
      image: item.icon
    }
  };
});

// Add special handling for the first item (average)
if (chart_data.length > 0) {
  const firstItem = chart_data[0];
  rich_data.Average = {
    height: 20,
    align: 'center',
    backgroundColor: {
      image: '' // Replace with your average icon URL
    }
  };
}

// Define the ECharts option object
 option = {
  color: ["#3398DB"],
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow"
    }
  },
  grid: {},
  xAxis: [{
    type: "category",
    data: chart_data.map((item, index) => index === 0 ? 'Average' : item.icon), // Set xAxis data based on vehicleType
    axisLabel: {
      formatter: function (value) {
        console.log(value)
        if (value === 'Average') {
          return [
            `{${value}|}`,
            `${value}`
          ].join('\n');
        } else {
          return value // Leave label text empty to only show icon
        }
      },
      rich: rich_data
    }
  },
					],
  yAxis: [{
    type: "value"
  }],
  series: [{
    name: "test",
    type: "bar",
    barWidth: "60%",
    data: chart_data.map(item => item.value) // Set series data with values
  }]
};
// Add second xAxis configuration
// Add second xAxis configuration
option.xAxis.push({
  type: 'category',
  position: 'bottom',
  data: chart_data.map((item, index) => index === 0 ? '' : `${item.noOfDays}x`),
  axisLine: {
    show: true,
    lineStyle: {
      color: '#000', // Change this to your desired color
      width: 2, // Adjust the width if necessary
    },
  },
  axisLabel: {
    margin: 50,
    color: '#000',
    formatter: function (value, index) {
      if (index === 0) {
        return '';
      } else {
        return `{${index}|${value}}`;
      }
    },
    rich: chart_data.reduce((acc, item, index) => {
      if (index !== 0) {
        acc[index] = {
          padding: [10, 15, 10, 15],
          backgroundColor: 'rgba(34, 34, 34, 0.3)',
          borderRadius: [50, 50, 50, 50]
        };
      }
      return acc;
    }, {})
  }
});

Image not showing


// Use the 'option' object with ECharts to render your chart
