### ISSUE TITLE
5.1.0 tooltip位置计算错误

### ISSUE THREAD

**Issue by facingcheer** [apache/echarts#14710]
### Version
5.1.0

### Reproduction link
[https://codepen.io/facingcheer/pen/MWjOezN?editors=1111](https://codepen.io/facingcheer/pen/MWjOezN?editors=1111)

### Steps to reproduce
直接看tooltip的位置

### What is expected?
tooltip位置正确计算

### What is actually happening?
tooltip位置计算异常

---
导致异常的提交：
https://github.com/apache/echarts/pull/14246/files/73a9f6e7bd0bdb5b236550d968c86841555f49ee#diff-f858c6a0a46939552e35abb40ae1580141336eee77cca6485e5cff5dfe35367a

问题原因： 设置transform3d替代top和left的时候，未设置top:0 left:0 导致定位问题

**Comment by plainheart** [comment]
@facingcheer Thanks for your feedback! This is quite helpful for me, which makes me think out the solution of a pending issue marked as `FIXME`.

**Comment by plainheart** [comment]
@facingcheer I've opened a PR(#14713) to fix this bug. Please feel free to help check if it works well for your cases. Thank you again!
