### ISSUE TITLE
Disable highlight of series or line

### ISSUE THREAD

**Issue by JJZolper** [apache/echarts#14725]
### Version
5.1.0

### Steps to reproduce
Hover over any line or series in an Echarts graph

### What is expected?
Desire a setting to disable highlight or the animation type feel of hovering over a series. I want my dashed line to not animate or highlight and just stay the way it looks. However, if I do want a line or series to highlight, the existing capability is retained. I looked through the documentation and am not sure if this is currently supported.

### What is actually happening?
The line highlights.

**Comment by plainheart** [comment]
You can set identical `lineStyle.width` and  `emphasis.lineStyle.width`.

**Comment by JJZolper** [comment]
> You can set identical `lineStyle.width` and `emphasis.lineStyle.width`.

Thank you! I did not know that. I'll close this.
