### ISSUE TITLE
echart使用全球地图为区域增加hover tooltip,未展示提示框并且 hvoer的时候 报错：TooltipView.js?42f6:473 Uncaught TypeError: Cannot read property 'getData' of undefined

### ISSUE THREAD

**Issue by ItsMisa** [apache/echarts#14720]
### Version
5.1.0

### Steps to reproduce
悬浮在地图上某个区域就会报错，也不会展示tooltip 提示框

### What is expected?
悬浮某个区域可以展示提示框且不报错

### What is actually happening?
悬浮在地图上某个区域就会报错，也不会展示tooltip 提示框

**Comment by plainheart** [comment]
#14704 已修复。

**Comment by ItsMisa** [comment]
安装了5.1.0最新版本还是会报错。这是我的代码
 echarts.registerMap('world', mapJSON);
        let myChart = echarts.init(this.$refs.echarts)
        myChart.setOption({
            title: {
                text: this.title,
                subText:this.subText
             },
            tooltip: {
                trigger: 'item',
                formatter: function(params) {
                    console.log(params)
                    // if ('value' in params.data) {
                    //     return params.data.value[2] + ': ' + params.data.value[0];
                    // }
                }
            },
            visualMap: {
                min: 800,
                max: 50000,
                left: 'left',
                top: 'bottom',
                text: ['高', '低'],
                dimension: 0,
                inRange: {
                color: ['lightskyblue', 'yellow', 'orangered']
                },
                calculable: false
            },
            series: [
                {
                    name: '全球地区客户分布',
                    type: 'map',
                    id: 'map',
                    map: 'world', // 自定义扩展图表类型
                    // roam: true,
                    nameMap,
                    data:regionData,
                    label:{
                        fontWeight:500,
                        fontSize:16
                    },
                    itemStyle: {
                    },
                   
                },
            ]
        })

**Comment by plainheart** [comment]
这是 5.1.0 中的问题，刚刚修复，还没有发版。请等待 下个修复版本 5.1.1。

**Comment by ItsMisa** [comment]
> 这是 5.1.0 中的问题，刚刚修复，还没有发版。请等待 下个修复版本 5.1.1。

请问大概什么时候发布啊

**Comment by mishengqiang** [comment]
> > 这是 5.1.0 中的问题，刚刚修复，还没有发版。请等待 下个修复版本 5.1.1。
> 
> 请问大概什么时候发布啊

同问，昨天预发和测试都没有问题，发布后生产环境报错了，后来排查后才发现生产环境自动升级到了5.1.1版本，真是崩溃啊！

**Comment by ItsMisa** [comment]
> > > 这是 5.1.0 中的问题，刚刚修复，还没有发版。请等待 下个修复版本 5.1.1。
> > 
> > 
> > 请问大概什么时候发布啊
> 
> 同问，昨天预发和测试都没有问题，发布后生产环境报错了，后来排查后才发现生产环境自动升级到了5.1.0版本，真是崩溃啊！
切换到官网的5.0.2版本吧 我试了5.0.2版本没有问题！自动升级package.json那里把^去掉应该就不会自动安装最新的了吧

**Comment by fuchunhui** [comment]
今天也遇到了这个问题，暂时使用5.0.2版本。

**Comment by pollux2015** [comment]
什么时候发布啊。。。。遇到同样问题
