### ISSUE TITLE
tooltip formatter does not render html

### ISSUE THREAD

**Issue by asciimancer** [apache/echarts#14726]
### Version
5.1.0

### Steps to reproduce
```
tooltip: {
    formatter: (params) => {
        return params.map(param =>{
            return (
                <span>{param.seriesName}</span>
            )
        })
    }
}
```

### What is expected?
Renders array of span html elements. 

### What is actually happening?
Nothing is rendered. Have to fall back on using string formatting to create this, i.e.
`` return `<span>${param.seriesName}</span>``
This works for really simple solutions, but for the full code of what I need to do, this becomes impractical very quickly. 

---
In the docs of tooltip, I see that the return options include html elements/list of html elements, so that's why reporting here. 
As per the docs:
**The format of callback function:**
`(params: Object|Array, ticket: string, callback: (ticket: string, html: string)) => string | HTMLElement | HTMLElement[]`
Thank you! Echarts is quite amazing : )

**Comment by plainheart** [comment]
I tested it with the following code, it works.

```js
formatter() {
   const h1= document.createElement('h1')
   h1.innerText = 'Hello'
   const h2= document.createElement('h1')
   h2.innerText = 'Hello2'
   return [h1, h2]
}
```

**Comment by asciimancer** [comment]
Thanks!
