### ISSUE TITLE
Series Label on Custom Series not working properly

### ISSUE THREAD

**Issue by wilnerjs** [apache/echarts#14727]
### Version
5.1.0

### Reproduction link
[https://echarts.apache.org/next/examples/en/editor.html?c=custom-profit](https://echarts.apache.org/next/examples/en/editor.html?c=custom-profit)

### Steps to reproduce
1 - Open https://echarts.apache.org/next/examples/en/editor.html?c=custom-profit
2 - add fontWeight: "900" or fontSize: 30 on series.label

### What is expected?
Changes on the label

### What is actually happening?
Nothing

---

Work properly on https://echarts.apache.org/examples/en/editor.html?c=custom-profit (echarts 4.x)

**Comment by wilnerjs** [comment]
the correction made for this issue https://github.com/apache/echarts/issues/14092 only fix the color, others attributes still not working (like weight and size)

**Comment by javeiga-iest** [comment]
I have had the same problem on V5, I have been looking at the styleCompat.ts class

One option that does work is using rich text, so you can customize the font, size, padding ...
```
text:'{value|test}',
rich: {
    value: {
        align: 'left',
        fontFamily:'impact',
        fontSize:20,
        color: 'red'
    }
}
```
However, the color still doesn't work with this solution.

**Comment by AmosChenYQ** [comment]
I am looking intt this.
