### ISSUE TITLE
Boxplot two areas display different colors

### ISSUE THREAD

**Issue by smj199265** [apache/echarts#14730]
### What problem does this feature solve?
How to make the area of upper quartile and lower quartile different? And setting different colors for the four sides?
The effect is shown in the figure below：
https://qc.rimagcloud.com/file/f4bb3e34-4dfc-4944-bee1-2d8dd587c978.jpeg

### What does the proposed API look like?
The four borders and midlines can be colored separately, and the two areas can be set separately

![image](https://user-images.githubusercontent.com/29547124/115516304-90aef780-a2b8-11eb-8ee0-1821482abe6d.png)

**Comment by Ovilia** [comment]
I would suggest using [custom series](https://echarts.apache.org/en/tutorial.html#Custom%20Series) to do this.
