### ISSUE TITLE
line overlap label in simple chart

### ISSUE THREAD

**Issue by randomCards** [apache/echarts#14735]
### Version
5.1.0

### Steps to reproduce
open the editor on https://echarts.apache.org/examples/en/editor.html an paste:

```js
option = {
    xAxis: {
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周一', '周二', '周三', '周四', '周五', '周六','周一', '周二', '周三', '周四', '周五', '周六','周一', '周二', '周三', '周四', '周五', '周六','周一', '周二', '周三', '周四', '周五', '周六','周一', '周二', '周三', '周四', '周五', '周六',],
        axisPointer: {
          show: true,
        }
    },
    yAxis: {
        type: 'value',
    },
    series: [
        {
            type: 'line',
            data: [120, 132, 101, 134, 90, 230, 120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,120, 132, 101, 134, 90, 230,],
            showSymbol: false,
            label: {
                show: true,
            },
        },
    ]
};
```

### What is expected?
the line does not overlap the label

### What is actually happening?
the line overlaps the label

**Comment by plainheart** [comment]
Related to #14541. It seems #14542 didn't solve it yet.

**Comment by pissang** [comment]
@plainheart z2 of label will be updated automatically in the https://github.com/apache/echarts/blob/master/src/core/echarts.ts#L2233

**Comment by plainheart** [comment]
@pissang The symbol is temporal, it's not controlled by echarts#updateZ. Whatever the z value is large, it takes no effect. Maybe we should set z rather than z2, or in some other way?

**Comment by pissang** [comment]
@plainheart Sorry I mistake it. You are right, `z` and `zlevel` should all be set. The can be got from `this._polyline.z` or `seriesModel.get('z')`. And the original `z2` code is also needed.
