### ISSUE TITLE
Lines are not aligned in Heatmap

### ISSUE THREAD

**Issue by xiaoyueguang** [apache/echarts#14733]
### Version
5.1.0

### Reproduction link
[https://jsfiddle.net/mdgjno6w/](https://jsfiddle.net/mdgjno6w/)

### Steps to reproduce
open this [link](https://jsfiddle.net/mdgjno6w/)

### What is expected?
the lines are straight

### What is actually happening?
Lines are not aligned

---
I feel that the main reason for this is that things here are calculated to a decimal point 

```js
HeatmapView2.prototype._renderOnCartesianAndCalendar

width = (xAxis.getBandWidth());
```

**Comment by plainheart** [comment]
Seems so. Would you mind making a PR to fix this?

**Comment by xiaoyueguang** [comment]
> Seems so. Would you mind making a PR to fix this?

I found out how this problem arises.

```ts
  // src/chart/heatmap/HeatmapView.ts
  rect = new graphic.Rect({
      shape: {
          x: Math.floor(Math.round(point[0]) - width / 2),
          y: Math.floor(Math.round(point[1]) - height / 2),
          width: Math.ceil(width),
          height: Math.ceil(height)
      },
      style
  });
```

x, y, width and height in Shape possible calculation error.

* If you want to render perfect, these lengths need to keep a decimal point, this will cause performance issues.
* If set these lengths to int, there will be a bit of coverage or gaps when rendering. like this [demo](https://jsfiddle.net/mdgjno6w/)

So I now use this to ensure perfect rendering:

* Set the `grid.width` to be an integer multiple of `xAxis.count`

**Comment by Ovilia** [comment]
@xiaoyueguang Please link this issue when you are ready to make a pull request.
