### ISSUE TITLE
Error when build with angular 11

### ISSUE THREAD

**Issue by ddurieux** [apache/echarts#14739]
### Version
5.1.0

### Steps to reproduce
Install last version of angular11, echarts, ngx-echarts

### What is expected?
Build the project without errors

### What is actually happening?
Many errors when buld my project

---
Error: node_modules/echarts/types/dist/echarts.d.ts:6391:13 - error TS1110: Type expected.

6391     [key in `${ComponentMainType}Index`]: number;
                 ~~~

Error: node_modules/echarts/types/dist/echarts.d.ts:6391:16 - error TS2693: 'ComponentMainType' only refers to a type, but is being used as a value here.

6391     [key in `${ComponentMainType}Index`]: number;
                    ~~~~~~~~~~~~~~~~~

Error: node_modules/echarts/types/dist/echarts.d.ts:6391:40 - error TS1005: ';' expected.

6391     [key in `${ComponentMainType}Index`]: number;
                                            ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6391:41 - error TS1128: Declaration or statement expected.

6391     [key in `${ComponentMainType}Index`]: number;
                                             ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6391:43 - error TS2693: 'number' only refers to a type, but is being used as a value here.

m6391     [key in `${ComponentMainType}Index`]: number;
                                               ~~~~~~

Error: node_modules/echarts/types/dist/echarts.d.ts:6392:1 - error TS1128: Declaration or statement expected.

6392 } & {
     ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6392:3 - error TS1109: Expression expected.

6392 } & {
       ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6392:5 - error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

6392 } & {
         ~
6393     [key in string]: unknown;
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6394 };
     ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6393:13 - error TS2693: 'string' only refers to a type, but is being used as a value here.

6393     [key in string]: unknown;
                 ~~~~~~

1m
Error: node_modules/echarts/types/dist/echarts.d.ts:6393:22 - error TS2693: 'unknown' only refers to a type, but is being used as a value here.

6393     [key in string]: unknown;
                          ~~~~~~~

Error: node_modules/echarts/types/dist/echarts.d.ts:6393:29 - error TS1005: ',' expected.

6393     [key in string]: unknown;
                                 ~

Error: node_modules/echarts/types/dist/echarts.d.ts:6393:5 - error TS2464: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

6393     [key in string]: unknown;
         ~~~~~~~~~~~~~~~

Error: node_modules/echarts/types/dist/echarts.d.ts:6393:6 - error TS2552: Cannot find name 'key'. Did you mean 'keys'?

6393     [key in string]: unknown;
          ~~~

  node_modules/echarts/types/dist/echarts.d.ts:269:18
    269 declare function keys<T extends object>(obj: T): (KeyOfDistributive<T> & string)[];
                         ~~~~
    'keys' is declared here.

<!-- This issue is generated by echarts-issue-helper. DO NOT REMOVE -->
<!-- This issue is in English. DO NOT REMOVE -->

**Comment by plainheart** [comment]
Thanks for your feedback. It's related to #14716. #14722 has fixed it.

**Comment by sherlockEix** [comment]
hi. when will it be released? @plainheart thanks

**Comment by plainheart** [comment]
@sherlockEix It will be released within the next several days.

**Comment by ttanphat77** [comment]
Thanks for your hard working @plainheart but Is there any workaround for this issue?

**Comment by plainheart** [comment]
@ttanphat77 You may do as this commit https://github.com/apache/echarts/pull/14722/files#diff-7c3814605c4f31b9c5f5ac643fe72a97797b4f2d13230ea178089879c7e5429cL1359 did.
