### ISSUE TITLE
echart map 当鼠标悬浮在某个国家区域的label文字上面的时候，visualMap那里没有个数的提示

### ISSUE THREAD

**Issue by ItsMisa** [apache/echarts#14734]
### Version
5.0.1

### Steps to reproduce
echart map 当鼠标悬浮在某个国家区域的label文字上面的时候，visualMap那里没有个数的提示，悬浮在除了lable文字的其他区域，visualMap有提示。

### What is expected?
期望悬浮在区域label文字上面的时候，visualMap那里有绑定的个数的提示

### What is actually happening?
悬浮在区域label文字上面的时候，visualMap那里没有绑定的个数的提示

**Comment by ItsMisa** [comment]
import * as echarts from "echarts";
import nameMap from "./nameMap";
import mapJSON from "./map.json";
const chart = echarts.init(document.getElementById("app"));

const data = [
  { name: "中国", value: [10000, 10000, 50000] },
  { name: "美国", value: [10000, 10000, 50000] }
];
echarts.registerMap("world", mapJSON);
chart.setOption({
  backgroundColor: "#404a59",
  title: {
    text: "地区分布",
    textStyle: {
      color: "#ffffff"
    }
  },
  visualMap: {
    min: 0,
    max: 50000,
    left: "left",
    top: "bottom",
    text: ["高", "低"],
    dimension: 2,
    textStyle: {
      color: "#ddd"
    },
    inRange: {
      color: ["lightskyblue", "yellow", "orangered", "red"]
    },
    calculable: false
  },
  series: [
    {
      name: "全球地区客户分布",
      type: "map",
      id: "map",
      map: "world", // 自定义扩展图表类型
      roam: true,
      nameMap,
      data: data,
      label: {
        show: true,
        fontWeight: 500,
        fontSize: 16,
        formatter: function (params) {
          if (params.data) {
            return params.data.name;
          }
          return "";
        }
      },
      emphasis: {
        label: {
          show: true,
          formatter: (params) => {
            return params.name;
          }
        }
      }
      // itemStyle: {
      // },
    }
  ]
});

**Comment by ItsMisa** [comment]
可以见 https://codesandbox.io/s/wonderful-torvalds-26jn3 这个demo

**Comment by pissang** [comment]
@ItsMisa 标题改下？

**Comment by ItsMisa** [comment]
> @ItsMisa 标题改下？

已改
