### ISSUE TITLE
tooltip overlapping

### ISSUE THREAD

**Issue by d-kishore** [apache/echarts#14732]
Hi Team,
we are using the below echart version 
"echarts": "^5.1.0",
"echarts-for-react": "^3.0.1",
    
while creating the charts , the tooltip is overlapping with other divs 
Please help me to move this tooltip to front
![image](https://user-images.githubusercontent.com/12540917/115520106-702a7180-a2a7-11eb-8c25-8ccc59f320f3.png)
![echarts](https://user-images.githubusercontent.com/12540917/115520171-81737e00-a2a7-11eb-8d15-de0f29b3c89d.PNG)

**Comment by plainheart** [comment]
@d-kishore Avoid setting the `overflow` of the chart container to `hidden`.
