### ISSUE TITLE
echarts shows two line indicators when it has multi xAxis

### ISSUE THREAD

**Issue by jevislee** [apache/echarts#14740]
### Version
5.1.0

### Steps to reproduce
https://www.makeapie.com/editor.html?c=xze5cph0h1&v=1

    var option = {
        tooltip: {
            trigger: 'axis',
        },
        xAxis: [
            {
                type: 'time',
            },
            {
                offset: 30,
                position: "bottom",
                data: ["2020","2021"]
            }
        ],
        yAxis: {
            type: 'value'
        },
        series: [{
            type: 'line',
            data: [["2020-01-01",100],["2020-12-01",200],["2021-01-01",100],["2021-12-01",200]]
        }],
    };

![screenshot](https://user-images.githubusercontent.com/44969388/115653400-aa584980-a361-11eb-8da4-7b15f9f9ef0d.png)

### What is expected?
it should show only one line indicator that following mouse current location

### What is actually happening?
it shows two line indicators, one is following mouse current  location, another one is jumping between years xAxis

**Comment by Ovilia** [comment]
Please make sure your code is minimum reproducible.

**Comment by jevislee** [comment]
> Please make sure your code is minimum reproducible.

I have update the content, Please visit https://www.makeapie.com/editor.html?c=xze5cph0h1&v=1

**Comment by pissang** [comment]
@jevislee It's because each axis will has it's own `axisPointer` indicator. You can turn off one of them:
```
xAxis: [{
  axisPointer: { show: false }
}, {
  ....
}]
```

**Comment by jevislee** [comment]
> @jevislee It's because each axis will has it's own `axisPointer` indicator. You can turn off one of them:
> 
> ```
> xAxis: [{
>   axisPointer: { show: false }
> }, {
>   ....
> }]
> ```

thanks, the problem is solved
