### ISSUE TITLE
bmap-lines blendMode 'lighter' unusual behavior

### ISSUE THREAD

**Issue by stormrise** [apache/echarts#14744]
### Version
5.1.0

### Reproduction link
[https://gist.github.com/stormrise/b684424dd03336c13a8d87d0116abda1](https://gist.github.com/stormrise/b684424dd03336c13a8d87d0116abda1)

### Steps to reproduce
based on
https://echarts.apache.org/examples/zh/editor.html?c=lines-airline

its a html render, since the data from the official site cannt be download, I put it together,

when draging the map, and hover the lines, the blender mode, lighter makes all white, its unusual.
drag the map again, do nothing, it will stay normal,

actually it is not that big , above 5k data will reproduce, 

### What is expected?
since the data is not too big(only 8k,  i use in data.routes.slice(0,8000).map), the blend will not cause so many white area, especially the lines. 

the first time do nothing you will see the correct result

but when drag and hover line, it will make some lines white and the white area spread, 

### What is actually happening?
blendMode : lighter 
makes all lines white

**Comment by stormrise** [comment]
also, occasionally the lines disapear when draging the map or zoom in zoom out

**Comment by stormrise** [comment]
plus, it require medium size data to reproduce this bug, if too many, the whole area is white, if too small there is no overlap area, in this case, 5k - 1w will fit this in my test

**Comment by stormrise** [comment]
![normal](https://user-images.githubusercontent.com/24603395/115680449-25335b80-a386-11eb-9cc6-8238249e76b6.png)
![unnormal](https://user-images.githubusercontent.com/24603395/115680471-29f80f80-a386-11eb-90b9-a4d74db995cc.png)

**Comment by stormrise** [comment]
another question? how to use emphasis. focus='self' in this scenario? 
I want to select one line and blur others

**Comment by stormrise** [comment]
> another question? how to use emphasis. focus='self' in this scenario?
> I want to select one line and blur others

I believe this is a bug too, I have a scatter series which works, but lines nothing happend

**Comment by Ovilia** [comment]
@stormrise Please give an online minimum reproducible demo for us to debug.

**Comment by stormrise** [comment]
> @stormrise Please give an online minimum reproducible demo for us to debug.

https://codepen.io/stormrise/pen/NWdearJ

**Comment by Ovilia** [comment]
@stormrise Please make minimum data and component as possible.

**Comment by stormrise** [comment]
> @stormrise Please make minimum data and component as possible.

this is your official dataset, I have already slice it to only 8k. the reason is only the medium amount data will cause this bug, if the data size is too small there is no blend issue since the lines do not overlap, 

the below scatter series to shows you another bug, which lines series emphasis focus self not work

**Comment by Ovilia** [comment]
OK. Thanks for letting us know.
