### ISSUE TITLE
echarts5的pie的每一个label.color可以和图形一个颜色吗?

### ISSUE THREAD

**Issue by yang-mengyue** [apache/echarts#14756]
echarts4
![image](https://user-images.githubusercontent.com/78328465/115710645-2aec6980-a3a5-11eb-8a3f-005183e75d57.png)
echarts5
![image](https://user-images.githubusercontent.com/78328465/115710585-1ad48a00-a3a5-11eb-9eee-efadf5a359bc.png)

**Comment by plainheart** [comment]
@yang-mengyue 设置 `label.color` 为 `inherit` 或者 `auto` 即可。

**Comment by yang-mengyue** [comment]
解决了，谢谢您。
