### ISSUE TITLE
巴西地图的配置只到地区region，没有到州吗？

### ISSUE THREAD

**Issue by hemiao1023** [apache/echarts#14753]
### Version
5.0.1

### Steps to reproduce
配置map为巴西，绘制地图，传入州的数据，无法正确展示

### What is expected?
实现巴西精确到州的行政地图，类似中国、美国等

### What is actually happening?
其他国家可以实现，但是巴西只精确到region，而无法实现

**Comment by Ovilia** [comment]
Apache ECharts 不提供地图数据的下载，请自行查找资料解决数据的问题，谢谢。
