### ISSUE TITLE
当echarts关系图type=graph layout="none", links属性里的value就不能控制线长短

### ISSUE THREAD

**Issue by 30Year-oldking** [apache/echarts#14752]
### Version
4.3.0

### Steps to reproduce
type=graph layout="none", links属性里的value就没有用，如何控制长度

### What is expected?
怎么不能控制节点长度

### What is actually happening?
layout="none" 写每个节点x和y的位置

**Comment by Ovilia** [comment]
layout="none" 的情况下，就是需要手动写每个点 x y 的坐标的，请问可以更明确一下你的需求吗？

**Comment by 30Year-oldking** [comment]
> layout =“ none”的情况下，就是需要手动写每个点xy的坐标的，请问可以更清楚一下你的需求吗？

![image](https://user-images.githubusercontent.com/49483862/115813218-5f076f00-a425-11eb-87e0-bde2ca80aa88.png)
我手动写坐标 但是有些节点线没了

**Comment by 30Year-oldking** [comment]
> layout="none" 的情况下，就是需要手动写每个点 x y 的坐标的，请问可以更明确一下你的需求吗？

https://github.com/apache/echarts/issues/14752#issuecomment-825355790
就是线条偏离节点位置，难道线条也要写x y的坐标吗

**Comment by 30Year-oldking** [comment]
@Ovilia https://www.makeapie.com/editor.html?c=xvDMjDsDh0&v=1 这是演示地址

**Comment by 30Year-oldking** [comment]
@Ovilia https://www.makeapie.com/editor.html?c=xvDMjDsDh0&v=1
这是演示地址 就是线偏离问题

**Comment by Ovilia** [comment]
Please provide a **minimum** reproducible demo for the issue.
