### ISSUE TITLE
tootip crashed in map

### ISSUE THREAD

**Issue by delta-force-keblog** [apache/echarts#14755]
### Version
5.1.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=map-HK](https://echarts.apache.org/examples/zh/editor.html?c=map-HK)

### Steps to reproduce
just in your official example page: https://echarts.apache.org/examples/zh/editor.html?c=map-HK

hover any item in this page's example

### What is expected?
no tooltip shown, and there's error in the console

### What is actually happening?
.

---
.

**Comment by delta-force-keblog** [comment]
@pissang or you can simply refer to this snippet: https://codesandbox.io/s/mutable-rgb-z2bjz
I just want know if it's a bug, or there's some update in the option setting

**Comment by pissang** [comment]
@delta-force-keblog Hi, this has been fixed in #14704 and will be released in 5.1.1 soon.

**Comment by delta-force-keblog** [comment]
@pissang ok, just want to know when will 5.1.1 be released?

**Comment by pissang** [comment]
@delta-force-keblog Early next week.

**Comment by delta-force-keblog** [comment]
@pissang cool, thanks
