### ISSUE TITLE
type graph roam nodes disapper!

### ISSUE THREAD

**Issue by 960662766** [apache/echarts#14764]
### Version
4.4.0

### Steps to reproduce
鼠标缩放平移，resize图表会出现节点消失，或者仅在缩放阶段就会出现

### What is expected?
希望不会消失

### What is actually happening?
缩放后 节点消失

**Comment by 960662766** [comment]
Here is a  minimum reproducible demo for the issue :[demo](https://codepen.io/960662766/pen/BapvdWw)

**Comment by Ovilia** [comment]
Which node has disappered?

**Comment by 960662766** [comment]
After resizing the chart (by resizing the window size), all nodes disappear, as shown in the figure-![1619167880(1)](https://user-images.githubusercontent.com/18606563/115846659-ba048a80-a454-11eb-961d-dbd27a835e97.jpg)
![1619167901(1)](https://user-images.githubusercontent.com/18606563/115846708-c1c42f00-a454-11eb-834a-17c77b160943.jpg)

**Comment by Ovilia** [comment]
I'm afraid I cannot reproduce this, even by calling `chart.resize()`. Does it require a specific window size?

**Comment by 960662766** [comment]
重现步骤：1.Scale Chart by scrolling the mouse wheel   2.resizing the chart (by resizing the window size)。
then,all nodes disappear,this is 100 percent reproducible.


PS---Key: First scroll the scroll wheel to zoom chart！

**Comment by Ovilia** [comment]
OK. It can be reproduced.
