### ISSUE TITLE
Tooltip cannot be displayed on the map in echarts5

### ISSUE THREAD

**Issue by mobei12** [apache/echarts#14761]
### Version
5.1.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=map-HK](https://echarts.apache.org/examples/zh/editor.html?c=map-HK)

### Steps to reproduce
Use the mouse to start the map block

### What is expected?
show message

### What is actually happening?
no show

**Comment by Ovilia** [comment]
Fixed in #14704, which should be released in 5.1.1 in about one week.
