### ISSUE TITLE
 series-graph.links.lineStyle. color 渐变色 可以从source 到 target自定义吗

### ISSUE THREAD

**Issue by yuerdev** [apache/echarts#14773]
### Version
5.0.1

### Steps to reproduce
目前links 线性渐变色是绝对的从某个方向到另外一个方向的颜色渐变
可否实现，从soure到target方向颜色渐变

### What is expected?
可否实现，从soure到target方向颜色渐变
使用颜色渐变来展示source——>target的方向

### What is actually happening?
线性渐变色是绝对的从某个方向到另外一个方向的颜色渐变

**Comment by Ovilia** [comment]
不是很好做，可以试试通过两点的位置计算出角度然后设置渐变的角度。

**Comment by chen198328** [comment]
桑基图里面已经实现了，能否把‘gradient'这个属性移植到link上 @echarts-bot  @pumpkindev
 @Ovilia 
series-sankey.lineStyle
桑基图边的样式，其中 lineStyle.color 支持设置为'source'或者'target'特殊值，此时边会自动取源节点或目标节点的颜色作为自己的颜色。

从 5.0 开始, lineStyle.color 还可以设置为'gradient'，取从源节点到目标节点的渐变色。
