### ISSUE TITLE
关于仪表formatter为html的问题

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#14771]
### Version
4.9.0

### Steps to reproduce
```js
detail:{

  formatter: function (params) {
        return `
          <div>${params}</div>
        `

      },
}

```

### What is expected?
期望解析字符串html

### What is actually happening?
结果没有解析
![$)NNEU@%X9QWP%MWH~OFBRS](https://user-images.githubusercontent.com/24451091/115846279-50847c00-a454-11eb-80d0-69f98230e48e.png)

**Comment by zhoufanglu** [comment]
还有 我想问下，仪表盘与边框的边距怎么调整？ 使用`grid`无效

**Comment by Ovilia** [comment]
不支持 html，可以用富文本。
位置是通过 [center](https://echarts.apache.org/zh/option.html#series-gauge.center) 控制的。

**Comment by zhoufanglu** [comment]
> 不支持 html，可以用富文本。
> 位置是通过 [center](https://echarts.apache.org/zh/option.html#series-gauge.center) 控制的。

谢谢你的回答，我不是问你位置，我想知道内边距如何去除. 富文本我去看看
![image](https://user-images.githubusercontent.com/24451091/115848126-20d67380-a456-11eb-9fa3-9a4ffcc54fd4.png)

**Comment by zhoufanglu** [comment]
formatter的问题解决了
```js
//变量
let companyScore = 40
let companyLevel = '优'
//富文本rich使用
formatter: [
  `{a|`+companyScore+`}`,
  `{b|`+companyLevel+`}`,
].join('\n'),
rich: {
  a: {
    color: 'red',
    lineHeight: 10
  },
  b: {
    color: 'green',
    fontSize: 32
  },
},

```

**Comment by Ovilia** [comment]
把图表高度设小一点，图表的高度可能是 CSS 容器高度或初始化图表的时候传入的

**Comment by zhoufanglu** [comment]
> 把图表高度设小一点，图表的高度可能是 CSS 容器高度或初始化图表的时候传入的

高度我设的都是100%，请问有类似grid的解决方式吗

**Comment by zhoufanglu** [comment]
解决了，这不是边距的问题。 = -
需要配置radius属性就能改变大小了
```js
type: 'gauge',
radius: '80%', //此属性调仪表盘大小。。
```
