### ISSUE TITLE
Vue制作3D地图, series.type为'map3D'时,label为true时报错(Cannot read property '0' of undefined)

### ISSUE THREAD

**Issue by jiangtwelve** [apache/echarts#14789]
### Version
5.1.0

### Steps to reproduce
在vue环境下:
import * as echarts from "echarts";
import "echarts-gl";
series.type 为 map3D时
label设置为true会报错
emphasis设置为true,且触发地图hover方法时,会报错
以上两种都会报同一种错,源代码定位都一样,都定位到了
Geo3DBuilder.js文件下的 this._labelsBuilder.getLabelPosition 这个函数下的
var pos = coordSys.dataToPoint([center[0], center[1], height]); 这一行代码

### What is expected?
希望告知解决方案

### What is actually happening?
Vue制作3D地图, series.type为'map3D'时,label为true时报错(Cannot read property '0' of undefined)

---
在非vue环境下并没有遇到此类问题,代码基本一致
当label设置为true时页面就正常了,当emphasis设置为true时,鼠标移动到地图上触发hover效果会触发同样的错误
错误源码是: var pos = coordSys.dataToPoint([center[0], center[1], height]);

**Comment by qq1198437442** [comment]
I encountered the same issues. I find the object "region" doesn't have the attribute of "center" . But it has the attribute of "_center". So....

**Comment by jiangtwelve** [comment]
> 我遇到了同样的问题。我发现对象"区域"没有"中心"的属性。但它具有"_center"的属性。所以。。。。
> ![image](https://user-images.githubusercontent.com/49434482/116050005-91c19980-a6a9-11eb-8f78-d3559ab2646d.png)

**Comment by jiangtwelve** [comment]
So you found a solution.I'm writing other requirements, so I don't have time to continue my research

**Comment by jiangtwelve** [comment]
已经解决了,
echarts-gl: 1.1.2
echarts: 4.9.0
就行了
