### ISSUE TITLE
throw error when use Vue3.0 and echartInstance.resize

### ISSUE THREAD

**Issue by sdwdjzhy** [apache/echarts#14781]
### Version
5.1.0

### Steps to reproduce
https://github.com/sdwdjzhy/testEchart

I  use   Vue3.0 and Echart 5.1.0.  When  I click the button ,   it  throw error

### What is expected?
donot throw error  and  resize echart

### What is actually happening?
it throw error

---
is  echart  error ?  or Vue error ?

**Comment by plainheart** [comment]
ECharts 实例 `chart` 不建议放在 `data` 中，Vue 3 使用了 `Proxy`，可能会导致 ECharts 内部 model 等变量获取不到。可以注释掉 `data` 中的 `chart` 变量，或者使用 `shallowRef`，即可避免该错误。
