### ISSUE TITLE
 markPoint的symbolOffset属性在5.0.2版本里不生效

### ISSUE THREAD

**Issue by ll790226724** [apache/echarts#14787]
### Version
5.0.2

### Steps to reproduce
series.line.markpoint.symbolOffset，设置以后不生效。在官方示例里设置同样也不会生效，但是在老版里这个属性生效

### What is expected?
修复

### What is actually happening?
markpoint下的symbolOffset属性未生效

**Comment by plainheart** [comment]
#14737 中会顺带修复该问题。

**Comment by Flourad** [comment]
最新版本5.1.2symbolOffset还是不生效

**Comment by snome** [comment]
嗯  我打算回退版本了
