### ISSUE TITLE
3D柱状图坐标轴标签为中文时，文字顶部显示不全

### ISSUE THREAD

**Issue by dengber** [apache/echarts#14786]
### Version
echarts@5.0.2
echarts-gl@2.0.4

### Steps to reproduce
创建一个3D柱状图，将X轴或Y轴系列的标签设置为中文文字

### What is expected?
中文文字能正确显示

### What is actually happening?
中文文字顶部大约一个像素被隐藏了，比如“干”显示的像"十"。

**Comment by maltoze** [comment]
![image](https://user-images.githubusercontent.com/18044730/123744591-91c85a80-d8e1-11eb-8d39-aabe06659bf4.png)

same issue when using `scatter3D`

**Comment by zoffyzhang** [comment]
这是分辨率导致的，我的经验是 1080p 屏幕的 label fontSize 至少设为 13px
