### ISSUE TITLE
Is it possible to display both name and value for a graph node?

### ISSUE THREAD

**Issue by lmulin** [apache/echarts#14780]
### What problem does this feature solve?
Actually only the name can be displayed in or near a graph node, however the value can only be displayed via tooltip. Can both name and value showed without mouseover? I need this feature for graph in order to implement a state diagram, whose nodes contain the value about the element amout and the name present the state name. The value can be displayed for the links, but it isn't what I need, because the value refernces the node, but not the links

### What does the proposed API look like?
series: [ { type: 'graph', valueStyle: { show: true | false, position: top|botton|right|left, color: fontSize: .. },

**Comment by Ovilia** [comment]
You can set `label.formatter` to be `'{b}: {c}`. The document seems to be missing for the graph series. You may refer to [that of line series](https://echarts.apache.org/en/option.html#series-line.label.formatter) for reference.

**Comment by lmulin** [comment]
Thank you Ovilia for the hint. 
But is it possible to display for example the name on the top of the node, the value inside the node?
