### ISSUE TITLE
No animation for the children in type 'text' in graphic group when resize the chart.

### ISSUE THREAD

**Issue by Echartswest** [apache/echarts#14784]
### Version
5.1.0

### Reproduction link
[https://jsbin.com/zibopik/4/edit?html,js,output](https://jsbin.com/zibopik/4/edit?html,js,output)

### Steps to reproduce
the JSBIN Link coded by adding a toolbox (square icon to resize) into the example of https://echarts.apache.org/examples/zh/editor.html?c=custom-calendar-icon to resize the chart.

### What is expected?
The whole group of the graphic should be animated synchronously when resize the chart. As well the calendar should be animated with the resizing.

### What is actually happening?
The children in type 'text' in the group of graphic is still not animated, it will change position immediately without animation when resizing the chart.

---
Refer to the issue #13923: resize的取消动画效果了吗？

**Comment by Ovilia** [comment]
The calendar component doesn't support animation by now.

**Comment by Echartswest** [comment]
Hi, Ovilia
It is ok that Calendar component is not animation supported so far.
However, in my JSBin linked code, the group.children in type 'text' is not animated when resize the chart, it cannot be animated with other types of children in the group. This is a calendar component.
I also tried to resize other graphic group, the same issue: the type 'text' children cannot be animated with other graphic children too.
So, could you enable the type 'text' children to be animated synchronously with other children as one group, otherwise the animation is incomplete. Thanks!

//below is not calendar component, it is in the graphic group as children in type 'text', it cannot be animated with other types of children in its group.
    group.children.push({
        type: 'text',
        style: {
            x: cellPoint[0],
            y: cellPoint[1] - cellHeight / 2 + 15,
            text: echarts.format.formatTime('dd', api.value(0)),
            fill: '#777',
            textFont: api.font({fontSize: 14})
        }
    });

**Comment by Echartswest** [comment]
solved.
