### ISSUE TITLE
如何获取渲染后的图表echartsInstance，当前所有有效配置？

### ISSUE THREAD

**Issue by elevensky** [apache/echarts#14797]
### What problem does this feature solve?
想要实现实时配置echarts图表属性的功能，在渲染图表后，如何获取配置数据。（比如渲染了多条线，初始的时候没有指定颜色，但是渲染后分配了默认的主题色中的一项，想要获取这些，默认分配的配置value）。

### What does the proposed API look like?
echartsInstance.getAllOption

**Comment by pissang** [comment]
`getOption()`

**Comment by elevensky** [comment]
> `getOption()`

这个只能获取用户设置给进去的吧，默认分配的是没有的。

**Comment by pissang** [comment]
有的
