### ISSUE TITLE
Bug when switch axis

### ISSUE THREAD

**Issue by tanghaojie** [apache/echarts#14799]
### Version
5.1.0

### Reproduction link
[https://codepen.io/tanghaojie/pen/eYgXNWO](https://codepen.io/tanghaojie/pen/eYgXNWO)

### Steps to reproduce
A chart with 2 axis in one direction, 1 axis in other direction.
Init chart, when switch axis: 
```javascript
chart.setOptions({
 xAxis: ...,
 yAxis: ...
})
```

### What is expected?
axis change.

### What is actually happening?
not change

**Comment by tanghaojie** [comment]
![Uploading image.png…]()

**Comment by pissang** [comment]
It's because the axes will be merged by default when `setOption`. You need to set `notMerge` to true.
