### ISSUE TITLE
The toolip of map in v5.1.0 SHOW NOTHING with an error

### ISSUE THREAD

**Issue by ranzj** [apache/echarts#14794]
### Version
5.1.0

### Steps to reproduce
Visit anyone example of map that is not SVG, e.g https://echarts.apache.org/examples/zh/editor.html?c=map-HK

### What is expected?
Fixed the bug, Please.

### What is actually happening?
Mouseover the item of map example, the tooltip could not show, F12 log "echarts.min.js Uncaught TypeError: Cannot read property 'getData' of undefined ……" in console.

---
But SVG map of v5.1.0 is OK, v5.0.
<img width="900" alt="Issue_冉20210426" src="https://user-images.githubusercontent.com/35555978/116045798-faf2de00-a6a4-11eb-8a92-89a8fd7037a6.png">
2 and before is OK.

**Comment by plainheart** [comment]
We fixed it in [5.1.1](https://github.com/apache/echarts/releases/tag/5.1.1-rc.1). The new version will be released within the next several days.
