### ISSUE TITLE
echarts使用bmap设置mapStyle 设置村庄labels属性不可见时，仍在地图上可见 。

### ISSUE THREAD

**Issue by Etering** [apache/echarts#14792]
### Version
5.0.2

### Steps to reproduce
1.打开  https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap 
2.删除series 只看地图，替换mapStyle如下
[{
    "featureType": "background",
    "elementType": "geometry",
    "stylers": {
        "color": "#1c4677ff"
    }
}, {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": {
        "color": "#123159ff"
    }
}, {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": {
        "visibility": "on"
    }
}, {
    "featureType": "road",
    "elementType": "labels",
    "stylers": {
        "visibility": "off"
    }
}, {
    "featureType": "poilabel",
    "elementType": "labels",
    "stylers": {
        "visibility": "off"
    }
}, {
    "featureType": "poilabel",
    "elementType": "labels.icon",
    "stylers": {
        "visibility": "off"
    }
}, {
    "featureType": "village",
    "elementType": "labels",
    "stylers": {
        "visibility": "off"
    }
}, {
    "featureType": "town",
    "elementType": "labels",
    "stylers": {
        "visibility": "off"
    }
}
, {
    "featureType": "town",
    "elementType": "labels.icon",
    "stylers": {
        "visibility": "off"
    }
}]
3.设置完进行一下缩放  会看见如图所示
![image](https://user-images.githubusercontent.com/41197305/116018667-24941100-a675-11eb-8b16-44f8fb0d8cdd.png)

### What is expected?
村庄label不显示

### What is actually happening?
地图缩放到一定比例时 ，村庄的label仍然出现在地图上。

**Comment by plainheart** [comment]
这不是 ECharts 相关问题，请查阅百度地图 API 自定义地图相关文档。
