### ISSUE TITLE
网站在线示例（折线图堆叠）线值和Y轴对应显示错误

### ISSUE THREAD

**Issue by liubinsv** [apache/echarts#14804]
### Version
5.1.0

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=line-stack  示例（折线图堆叠） 查看周一 搜索引擎 820的值 对应 Y轴的值

### What is expected?
周一 搜索引擎 820的值 对应 Y轴的值820

### What is actually happening?
周一 搜索引擎 820的值 对应 Y轴的值是1500 

---
去除series 里所有stack: '总量' 属性可正确展示

**Comment by plainheart** [comment]
如其名所示，该示例启用了 stack 堆叠模式，数据如此呈现是期望的结果而非错误。
