### ISSUE TITLE
雷达图的节点可以设置成空心原点样式吗？

### ISSUE THREAD

**Issue by yang-mengyue** [apache/echarts#14819]
### What problem does this feature solve?
我有一个项目的效果需要空心圆点样式，echarts4雷达图默认为空心原点，echarts5默认样式改变，type设置为emptyCircle都不可以实现。建议开设emptyCircle类型，像折线图一样可以给用户自己设置节点样式。
echarts5
![image](https://user-images.githubusercontent.com/78328465/116336372-052eec80-a80b-11eb-9073-9cc41527629c.png)
echarts4
![image](https://user-images.githubusercontent.com/78328465/116336403-11b34500-a80b-11eb-9434-0de0865d7fae.png)

### What does the proposed API look like?
series-radar-symbol-emptyCircle

**Comment by yang-mengyue** [comment]
这是修复了吗?设置成空心点的type值是什么呢？

**Comment by pissang** [comment]
Should have been fixed since 5.2.0
