### ISSUE TITLE
pie图形label显示不全，被遮挡了

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#14811]
### Version
4.9.0

### Steps to reproduce
屏幕缩小后,饼图label显示不全

### What is expected?
label显示全

### What is actually happening?
label被遮挡了
![)SVI)S2(CNB}WC$Q3ZQ_L9](https://user-images.githubusercontent.com/24451091/116191143-66e54d00-a75e-11eb-9faa-773ada6b4bc3.png)

**Comment by zhoufanglu** [comment]
[参照的这个demo](https://www.makeapie.com/editor.html?c=xBnkDjUWnN)
此demo缩小后，Label也会被遮挡，请问如何解决

**Comment by pissang** [comment]
有一个 bleedMargin 的配置项可以配置最小边距

**Comment by MrZhouZh** [comment]
进展如何, 也遇到被遮挡问题, 自定义的 labelLayout

<img width="467" height="189" alt="Image" src="https://github.com/user-attachments/assets/7465e690-7220-4b26-a841-91ced05965a2" />
