### ISSUE TITLE
Echart5.1.0 markPoint symbolOffset don't work

### ISSUE THREAD

**Issue by leksas** [apache/echarts#14816]
### Version
5.1.0

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-line.markPoint.symbolKeepAspect](https://echarts.apache.org/zh/option.html#series-line.markPoint.symbolKeepAspect)

### Steps to reproduce
```
option = {
  xAxis: {
    type: "category",
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  yAxis: {},
  series: [{
    data: [820, 932, 901, 934, 1290, 1330, 1320],
    type: "line",
    markPoint: {
      data: [{
        type: "max"
      }],
      symbolOffset: [1500, 1500]
    }
  }]
}
```

![image](https://user-images.githubusercontent.com/62830140/116214437-48d91600-a779-11eb-9ba2-59193a1e8d9d.png)

### What is expected?
I expect symboloffset to set the SVG offset

### What is actually happening?
no offset

**Comment by plainheart** [comment]
Will fix it by #14787 in 5.2.0
