### ISSUE TITLE
结合百度地图 拖动点位消失

### ISSUE THREAD

**Issue by Firekiss** [apache/echarts#14824]
### Version
5.1.1

### Steps to reproduce
官方实例：https://echarts.apache.org/examples/zh/editor.html?c=map-polygon

将zoom设置为1

慢慢往左边拖动会地图

### What is expected?
正确显示地图内容

### What is actually happening?
原本的黄色点位消失，地图上加拿大左侧的美国领土渲染的非常奇怪

**Comment by plainheart** [comment]
领土渲染是百度地图行为，相关问题建议向百度地图咨询，或者尝试使用百度地图 3.0，示例用的是 2.0。
