### ISSUE TITLE
echarts大数据量问题

### ISSUE THREAD

**Issue by qqfei1858** [apache/echarts#14826]
### Version
4.9.0

### Steps to reproduce
目前业务层面上的数据可能会在几十万上下,但是使用echarts去渲染时特别卡顿,无论是dataset模式还是常规模式都一样,使用svg方式渲染也是一样!

一般模式
https://www.makeapie.com/editor.html?c=xxAa4x9w_Y

dataset模式
https://www.makeapie.com/editor.html?c=xJm15mIBjf&v=1

### What is expected?
可有对大数据量(几百万甚至上千万)渲染的解决方案?

1 . 比如虚拟渲染啥的,一开始数据点全部挤在一块,就按照平均取值对X轴和数据进行部分渲染,鼠标滚轮滚动在逐一渲染

2. 如地图形式一样,拖拽缩放地图,就渲染当前可视区的数据

### What is actually happening?
大数据量情况下,echarts渲染操作特别卡

**Comment by pissang** [comment]
建议关闭 smooth，showSymbol 设为 false

**Comment by qqfei1858** [comment]
@pissang 结果也是一样的哦,给出的样例中已经设置了你说的这两个属性!

**Comment by jingyuLin1999** [comment]
用[highcharts](https://github.com/highcharts/highcharts)吧！
