### ISSUE TITLE
Toolbox: icon title getting cut

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#14833]
### Version
5.1.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=line-stack](https://echarts.apache.org/examples/en/editor.html?c=line-stack)

### Steps to reproduce
Hover on save as image icon in toolbox. Title will show as half cut.

### What is expected?
Should position icon title when it is going out as in version 4.

### What is actually happening?
Toolbox icon title is getting cut

**Comment by dileepyelleti** [comment]
Hello @pissang 
I couldn't find any way to position toolbox icon title without getting cut. If there is any way to do so please let me know

**Comment by ssthouse** [comment]
@dileepyelleti Hi, you can try to set `toolbox.right` to fix this issue:

![image](https://user-images.githubusercontent.com/10973821/122334924-107dd900-cf6d-11eb-947c-676076f04759.png)
