### ISSUE TITLE
The ‘borderWidth’ causes the pie chart to not be completely closed

### ISSUE THREAD

**Issue by MissThee** [apache/echarts#14839]
### Version
5.1.1

### Steps to reproduce
use this example 
[https://echarts.apache.org/examples/zh/editor.html?c=pie-borderRadius](url)
and set option.series[0].data as follow:
[
  {value: 1048, name: '搜索引擎'},
  {value: 0, name: '直接访问'},
  {value: 0, name: '邮件营销'},
  {value: 0, name: '联盟广告'},
  {value: 0, name: '视频广告'}
]

### What is expected?
When using borderWidth and only one piece of data has a value and the ratio is 100%, the pie chart should be completely closed
![小Q截图-20210429142552](https://user-images.githubusercontent.com/11582624/116510132-03425780-a8f7-11eb-8f55-9bdba23bc073.png)

### What is actually happening?
There is a gap in the middle. It’s hard to distinguish between [100%,0] and [99.9%, 0.01%]
![小Q截图-20210429142541](https://user-images.githubusercontent.com/11582624/116510118-fd4c7680-a8f6-11eb-9637-f76c41f2558f.png)

---
I hope to be able to automatically close the border when the pie chart has only one data value accounting for 100%

**Comment by Ovilia** [comment]
I think this border is expected. Because if the data is 99.99%, it should have the border, so as 99.9999% ...
So 100% should not have an abrupt change.
If you don't want it, you can set borderWidth to be 0 when data is 100%.

**Comment by MissThee** [comment]
Well, I personally think that the purpose of the gap is to separate different data, so the same data does not need to be separated from itself. 
So...I have another doubt. When the borderWidth is set and only one 100% data, if the mouse is put on, the separation gap will be closed, shouldn't it be kept? Intuitively they should maintain consistent results.

**Comment by pissang** [comment]
I'm afraid you have to accept the result that the displayed sector won't represent the data exactly if you set a white border to simulate the gap. No matter there is only one data or there are multiples.

**Comment by MissThee** [comment]
> I'm afraid you have to accept the result that the displayed sector won't represent the data exactly if you set a white border to simulate the gap. No matter there is only one data or there are multiples.

What can I say, if the designer insists on designing like this. And it seems just me think that's weird...
![无标题](https://user-images.githubusercontent.com/11582624/116522260-92f00200-a907-11eb-802a-5b173603b3f8.png)

**Comment by 100pah** [comment]
@MissThee Remove the data items that value is `0`, the gap will diappear.


@Ovilia @pissang 

In this case there is no gap.
```js
data: [
        { name: 's：迈向基地', value: 3.8 }
]
```

But in this case there is a gap.
```js
data: [
        { name: 's'：迈向基地', value: 3.8 },
        { name: 'd', value: 0 },
]
```

Should it be an issue? I've no idea.

**Comment by MissThee** [comment]
Funny. So ,how to keep the legend when I removed those data ...?

**Comment by MissThee** [comment]
> @MissThee Remove the data items that value is `0`, the gap will diappear.
> 
> 
> 
> 
> 
> @Ovilia @pissang 
> 
> 
> 
> In this case there is no gap.
> 
> ```js
> 
> data: [
> 
>         { name: 's', value: 3.8 }
> 
> ]
> 
> ```
> 
> 
> 
> But in this case there is a gap.
> 
> ```js
> 
> data: [
> 
>         { name: 's', value: 3.8 },
> 
>         { name: 'd', value: 0 },
> 
> ]
> 
> ```
> 
> 
> 
> Should it be an issue? I've no idea.
> 
> 
> 
> 

Funny. So ,how to keep the legend when I removed those data ...?

**Comment by MissThee** [comment]
Ovilia's method is OK, I can set borderWidth to be 0 in that case.
But, I can't accept that infinite approaching 100 has the same meaning as 100, and 0 === undefined.
