### ISSUE TITLE
report a problem, that is the tooltip of type map.

### ISSUE THREAD

**Issue by Rainy-Bear** [apache/echarts#14832]
### Version
5.0.2

### Steps to reproduce
```ts
option.tooltip = {
  trigger: 'item',
  confine: true,
  formatter: function () {
    const item = mapData[param.dataIndex];
      // TODO echarts 5 bug 会显示上次 tip
      // 没有数据则不展示 tooltip
      if (!item) return null;
  }
```
Tooltip will show last content. I hope is not displayed. tips: 4.9.0 is ok. 
![image](https://user-images.githubusercontent.com/31062861/116370732-4213d700-a83d-11eb-877a-77f5b8f87668.png)

### What is expected?
return null will not display last tooltip

### What is actually happening?
return null will display last tooltip

**Comment by pissang** [comment]
I don't understand what do you mean by "show last content"

**Comment by Rainy-Bear** [comment]
As shown in the picture, there is no data in Xinjiang. If there is no data, I will return null. But the data table shows the data of Tibet. And I was suspended in Tibet before.

**Comment by pissang** [comment]
But the screenshot shows Tibet is the highlighted area.

**Comment by Rainy-Bear** [comment]
那是另一个问题。我用dispatchAction 触发 mapSelect 后，他高亮的颜色是 黄色。但是鼠标出发的高亮要色是 那个灰色

**Comment by pissang** [comment]
@Rainy-Bear 发个可以复现的 demo 给我们吧

**Comment by Rainy-Bear** [comment]
https://codesandbox.io/s/cocky-knuth-hd27z?file=/src/index.js

**Comment by Rainy-Bear** [comment]
这个问题在 5.1.2 中修复了吗？
