### ISSUE TITLE
type scatter label do not show

### ISSUE THREAD

**Issue by DoubleCorner** [apache/echarts#14830]
### Version
5.0.2

### Steps to reproduce
I set the itemStyle = {
     normal: {opacity: 0},
     emphasis: {opacity: 1}
} and label = {
     normal: {show: false},
     emphasis: {show: true}
} of each scatter to make scatter show when highlighted by the function of dispatchAction({type: 'highlight'}).But only the scatter is displayed, and the label is not displayed.

### What is expected?
the label is not displayed.

### What is actually happening?
the label is displayed

---
ps: 4.9.0 is ok. But 5.0.2 is no ok. I try set label = {
      normal: {show: false},
      emphasis: {show: true, opacity: 1}
}. Then it works !!!

**Comment by pissang** [comment]
I think it's because since 5.0 the default opacity follows the opacity of element in the `normal` state

**Comment by Rainy-Bear** [comment]
OK...

**Comment by Rainy-Bear** [comment]
I want to report other problem, that is the tooltip of type **map**. 
```js
option.tooltip = {
  trigger: 'item',
  confine: true,
  formatter: function () {
    const item = mapData[param.dataIndex];
      // TODO echarts 5 bug 会显示上次 tip
      // 没有数据则不展示 tooltip
      if (!item) return null;
  }
}
``` ```
Tooltip will show last content. I hope is not displayed. tips: 4.9.0 is ok. 
![image](https://user-images.githubusercontent.com/31062861/116370409-f19c7980-a83c-11eb-9c12-a206e66c7794.png)

**Comment by pissang** [comment]
Please open a new issue to report it
