### ISSUE TITLE
雷达图的描边单位

### ISSUE THREAD

**Issue by yang-mengyue** [apache/echarts#14836]
### Version
5.0.2

### Steps to reproduce
echarts5的series-radar-symbolSize改变，series-radar-itemStyle-borderWidth也变化。是不是单位echarts4和echarts5的单位发生了变化？或者borderWidth的默认半径设置错误？

### What is expected?
和echarts4一样，borderWidth显示正常

### What is actually happening?
echarts4
![9I`7TNNQXYZX4D5P_N%E~GS](https://user-images.githubusercontent.com/78328465/116504861-f2401900-a8eb-11eb-84b0-9bf1418544c9.png)

echarts5
![IKZP14{UCBGFEC E2ZNP6@S](https://user-images.githubusercontent.com/78328465/116504867-f4a27300-a8eb-11eb-935a-c6564ba6a3ca.png)

**Comment by zxflslzyx** [comment]
所以。。这个解决了吗
