### ISSUE TITLE
使用多个series,筛选样式会出错

### ISSUE THREAD

**Issue by wjyhaha** [apache/echarts#14842]
### Version
5.0.0

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=scatter-stream-visual
我打开官网这个例子。里面有个筛选功能的（图表左侧那个数轴）。鼠标移动在上面的时候。筛选功能正常。

### What is expected?
在series多加一个类型。代码如下:
 {
                        
                          data: [
                                [0, 159980/2],
                                [400*0.25,159980],
                                [400*0.75,15202],
                                [400,15202/2]
                            ],
                            type: 'line',
                            symbol: 'none',  //取消折点圆圈
                            smooth: true,
                            lineStyle: {
                                  color: '#8ba3f3',
                                  width:1//设置线条粗细
                          }
                        }

### What is actually happening?
添加代码后。再去使用左侧数组的筛选功能。当鼠标移出左侧筛选轴，画布的点没回复原来的样式。变大了

---
起码如下：
图上的点的样式回复正常

**Comment by 100pah** [comment]
通过调整 series.z 的值（比如设置为 20）能避免这个现象。
但是这是一个问题。
