### ISSUE TITLE
echarts4和echarts5饼图的变化

### ISSUE THREAD

**Issue by Lyd1223** [apache/echarts#14849]
### Version
5.1.1

### Steps to reproduce
同样的配置参数和数据，v4的文字会重叠且溢出，v5不会

### What is expected?
想知道发生了什么改变

### What is actually happening?
v4
![image](https://user-images.githubusercontent.com/49749583/116643990-cdf44300-a9a4-11eb-8ef8-5d64d1fcb5da.png)
v5
![image](https://user-images.githubusercontent.com/49749583/116644002-d3ea2400-a9a4-11eb-8931-28e49fa8a56b.png)

**Comment by plainheart** [comment]
v5 优化了 label 排列算法，可以阅读 [ECharts 5 新特性](https://echarts.apache.org/zh/tutorial.html#ECharts%205%20%E6%96%B0%E7%89%B9%E6%80%A7) 、[ECharts 5.0.0 变更日志](https://echarts.apache.org/zh/changelog.html#v5-0-0) 以及原始 PR #12911 了解更多更改细节。
