### ISSUE TITLE
echarts4和echarts5仪表盘配置项距离单位的变化

### ISSUE THREAD

**Issue by yang-mengyue** [apache/echarts#14840]
### Version
5.0.2

### Steps to reproduce
echarts4做好的图表，在echarts5的配置项距离，大小发生了改变。

### What is expected?
想了解一下echarts4到echarts5的距离单位的改变，单位是什么，是像素单位还是什么？如果要转换的话，echarts5和echarts4的距离单位的关系如倍数是多少等。

### What is actually happening?
echarts4
![)(DS%BY)3`LOB7DOFI{GCU](https://user-images.githubusercontent.com/78328465/116510449-85cb1700-a8f7-11eb-8414-c891f39ea4d9.png)

eecharts5
![A`WK{ PA9XT0YN@6EIQQ9L2](https://user-images.githubusercontent.com/78328465/116510460-8b286180-a8f7-11eb-8ba8-fb7354a554d4.png)

**Comment by pissang** [comment]
没有比例关系，只是默认的距离像素单位做了调整

**Comment by yang-mengyue** [comment]
> 没有比例关系，只是最小的距离预期单位做了调整

因为之前做的图是使用的echarts4的像素单位，升级之后，之前的图的样式变化了。这个距离单位是否有一些标准呢？想做一下兼容。使之前的版本的图能够显示正常。
