### ISSUE TITLE
饼图 label 居中的时候会重叠

### ISSUE THREAD

**Issue by qianlongdoit** [apache/echarts#14855]
### Version
5.1.1

### Reproduction link
[https://codesandbox.io/s/zen-oskar-lr51r?file=/src/index.ts](https://codesandbox.io/s/zen-oskar-lr51r?file=/src/index.ts)

### Steps to reproduce
链接中已经设置了默认高亮的图例，鼠标挪到其他图例的时候，会发现默认高亮的图例没取消，
会和其他图列重叠在一起

### What is expected?
期望图例的label不会重叠

### What is actually happening?
重叠了
![image](https://user-images.githubusercontent.com/25680946/116773414-df624b80-aa87-11eb-8704-92f1263629af.png)

**Comment by 100pah** [comment]
Seams `label.show: false` does not work when `emphasis.label.show: true`.

**Comment by pissang** [comment]
@100pah Looks like `highlight` action has a higher priority than the mouse over highlight. So the first data keeps highlighted and the label is not hidden when mouse over other sectors.
