### ISSUE TITLE
series-line.markPoint. symbolOffset

### ISSUE THREAD

**Issue by osgregs** [apache/echarts#14854]
### Version
5.1.1

### Reproduction link
[https://echarts.apache.org/en/option.html#series-line.markPoint.symbolOffset](https://echarts.apache.org/en/option.html#series-line.markPoint.symbolOffset)

### Steps to reproduce
click on try it

### What is expected?
working

### What is actually happening?
not working

**Comment by plainheart** [comment]
This bug will be fixed by #14737.
