### ISSUE TITLE
Nextjs can't import minimal bundle

### ISSUE THREAD

**Issue by hoangtrung99** [apache/echarts#14864]
### Version
5.1.1

### Steps to reproduce
`import * as echarts from 'echarts/core'` got `SyntaxError: Unexpected token 'export'`

### What is expected?
I hope to enter echart from core

### What is actually happening?
But I got error: SyntaxError: Unexpected token 'export'
environment: 
- Nextjs 10.2.0
- Typescript
- No next config file

---
My tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by hoangtrung99** [comment]
Echarts-for-react fault
If I import together it will get an error

**Comment by kunKun-tx** [comment]
Next.js currently doesn't support import es module 
related discussion:
1. https://github.com/vercel/next.js/issues/9607
2. https://github.com/vercel/next.js/issues/25423 (possible workarounds)
