### ISSUE TITLE
[Perf] High CPU overload and user interaction freezed in SVG map (canvas & svg)

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#14875]
### Version
5.1.1

### Reproduction link
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-scatter-simple

### Steps to reproduce
- Open the reproduction link
- Watch the CPU overload in default `canvas` renderer
- Switch to `svg` renderer
- Watch the CPU overload and effectScatter rendering
- The effectScatter's animation becomes not smooth any more

### What is expected?
Lower CPU overload and effectScatter has a smooth animation

### What is actually happening?
High CPU overload and the animation of effectScatter is not smooth.

![effectScatter with svg renderer](https://user-images.githubusercontent.com/26999792/117257149-24b6bc80-ae7e-11eb-9e89-3bcbd5f64403.gif)

![effectScatter with svg coord](https://user-images.githubusercontent.com/26999792/117257462-7bbc9180-ae7e-11eb-809b-38b107b06950.png)

![Simple effectScatter](https://user-images.githubusercontent.com/26999792/117257467-7e1eeb80-ae7e-11eb-9a11-83cd4259dd44.png)

### Others

**I noticed that a strange zrender level named `zr_100000` was added to the DOM.**

**Comment by pissang** [comment]
@plainheart 

`zr_100000` is a special `zlevel` that provided to the hover layer.

SVG rendering mode is not good at animation performance because each frame it will manipulate the attributes of DOM. Even if we did lots of optimizations, it's still not as fast as Canvas. Especially in a case like this map which has lots of elements. The advance of SVG rendering mode is reducing the memory usage on mobile devices.

**Comment by plainheart** [comment]
@pissang Thanks for the detailed explanation. So this should not be considered a bug.

**Comment by pissang** [comment]
I profiled this case, it seems `getDefs` method takes lots of time, which is not expected.

![image](https://user-images.githubusercontent.com/841551/117260226-6e54d680-ae81-11eb-9f38-3457bcc1dbd1.png)

Perhaps it still has some chance to do more optimization

**Comment by plainheart** [comment]
Awesome! The performance got improved significantly. It can be closed later.

**Comment by hao-kuai** [comment]
> @plainheart
> 
> `zr_100000` is a special `zlevel` that provided to the hover layer.
> 
> SVG rendering mode is not good at animation performance because each frame it needs to find out which DOM needs to be updated and manipulate the attributes of DOM(just like what virtual dom does). Even if we did lots of optimizations, it's still not as fast as Canvas. Especially in a case like this map which has lots of elements. The advance of SVG rendering mode is reducing the memory usage on mobile devices.

如何移除zr_100000图层？这会导致浏览器自带复制图片复制内容失败。
