### ISSUE TITLE
dispatchAction use "batch"  to dispatch multiple "showTip" action is no effect

### ISSUE THREAD

**Issue by xiaoYown** [apache/echarts#14878]
### Version
5.1.1

### Steps to reproduce
myChart.dispatchAction({
    type: 'showTip',
    batch: [{
        seriesIndex: 0,
        dataIndex: 1
    }, {
        seriesIndex: 0,
        dataIndex: 2
    }]
})

### What is expected?
Multiple events can be triggered

### What is actually happening?
just one event be triggered

**Comment by pissang** [comment]
Can only show one tooltip at the same time. So batch should not work here
