### ISSUE TITLE
How to customize a specified Yaxis value

### ISSUE THREAD

**Issue by hoangtrung99** [apache/echarts#14870]
### What I have to do? please help me
![Screenshot from 2021-05-05 23-47-19](https://user-images.githubusercontent.com/29956745/117178942-c695c500-adfc-11eb-8a50-6c92adc33f5d.png)

### What problem does this feature solve?
I want to define YAxis value with type = 'value' but I don't know how to do it

### What does the proposed API look like?
add data for value type

**Comment by Ovilia** [comment]
Then you should have data like `[[123, 45], [67, 89]]`, in which `123` and `67` are x values.

**Comment by hoangtrung99** [comment]
@Ovilia Thank you!
