### ISSUE TITLE
Browser ES module usage not working natively

### ISSUE THREAD

**Issue by nomego** [apache/echarts#14880]
### Version
5.1.1

### Steps to reproduce
import * as echarts from 'echarts/core';

### What is expected?
To successfully import the echarts core

### What is actually happening?
clazz.js:184 Uncaught ReferenceError: process is not defined
    at enableClassCheck (clazz.js:184)
    at Model.js:242

**Comment by pissang** [comment]
@nomego 'echarts/core' is for the bundler environment. Please import from 'dist/echarts.esm.js' if you wan't to use it in the browser

**Comment by DzmitryFil** [comment]
how did you fix it?

**Comment by 1ma** [comment]
A workaround can be found [here](https://github.com/apache/echarts/issues/19806#issuecomment-2358567930). It seems to involve deleting the occurrences of `process.env.NODE_ENV` in an intermediate step when bundling the JS files.

This `rollup.config.js` works for me:

```javascript
import replace from '@rollup/plugin-replace';
import resolve from '@rollup/plugin-node-resolve';
import terser from '@rollup/plugin-terser';

export default {
    input: 'src/main.js',
    output: [
        {file: 'www/js/bundle.js', format: 'es'}
    ],
    plugins: [
        resolve(),
        replace({preventAssignment: true, 'process.env.NODE_ENV': '"production"'}),
        terser({module: true, ecma: 2020})
    ]
};
```

**Comment by v1talii-dev** [comment]
In vite config i use this...
```js
define: {
    'process.env': {}
}
```
