### ISSUE TITLE
brushSelected  dataIndex 为空

### ISSUE THREAD

**Issue by hzyyy** [apache/echarts#14884]
### Version
5.0.2

### Reproduction link
[https://codesandbox.io/s/wild-grass-lq03j?file=/src/App.vue:5148-5154](https://codesandbox.io/s/wild-grass-lq03j?file=/src/App.vue:5148-5154)

### Steps to reproduce
codesandbox

### What is expected?
dataIndex 有值；或者通过其它方式，获取当前框选的内容数据。

### What is actually happening?
dataIndex 数组为空

**Comment by zac18992** [comment]
I am facing the same issue with scatter plot. The points are selected visually but every dataIndex is empty.
