### ISSUE TITLE
svg模式 切换手机模式 dataZoom无法拖拽

### ISSUE THREAD

**Issue by cq112233** [apache/echarts#14883]
### Version
5.0.2

### Steps to reproduce
在dataZoom下的例子中切换成F12切换成手机模式,选择svg模式，滑动空白区域无法拖拽

### What is expected?
手机模式在svg模式下可以进行拖拽

### What is actually happening?
无法拖拽

**Comment by HDhuangdi** [comment]
我试过了，在移动端模式下，使用svg渲染器，渲染折线图，拖动折线以外的区域，DataZoom的拖动的确会有些问题[https://sm.ms/delete/pgKqiW27swzSRf4BL8tOaCX6bl](url)

**Comment by HDhuangdi** [comment]
我试过了，在移动端模式下，使用svg渲染器，渲染折线图，拖动折线以外的区域，DataZoom的拖动的确会有些问题，以下是我录的录屏：https://sm.ms/delete/pgKqiW27swzSRf4BL8tOaCX6bl

**Comment by HDhuangdi** [comment]
我试过了，在移动端模式下，使用svg渲染器，渲染折线图，拖动折线以外的区域，DataZoom的拖动的确会有些问题，以下是我录的录屏：[https://sm.ms/image/CRYibIZ6GPp3EvO](url)

**Comment by woodstream** [comment]
The same problem.

**Comment by woodstream** [comment]
@cq112233 最后你的解决方案是怎样？
