### ISSUE TITLE
柱状图 label 设置 color inherit 后颜色没有继承

### ISSUE THREAD

**Issue by Rainy-Bear** [apache/echarts#14892]
### Version
5.1.1

### Steps to reproduce
已在沙盒中复现

### What is expected?
柱状图 label 设置 color inherit 后颜色和主题一致

### What is actually happening?
柱状图 label 设置 color inherit 后颜色是黑色

---
https://codesandbox.io/s/pensive-platform-7cy1n?file=/src/index.js 这是沙盒环境。版本切换到 4.9.0 是可以的

**Comment by pissang** [comment]
@Rainy-Bear 这个是因为你颜色设置成了渐变色，但是标签暂时不支持渐变色
