### ISSUE TITLE
注册成功的geoJSON map无法显示

### ISSUE THREAD

**Issue by MafuyuRyan** [apache/echarts#14903]
### Version
5.1.1

### Steps to reproduce
用typescript写的echarts, 已经可以通过getMap()看到，但是就是在页面上无法显示。
是写的有什么问题吗，谢谢。

**代码**:
![image](https://user-images.githubusercontent.com/50653281/117611973-05c66c00-b197-11eb-99b6-f1c73bc0a88d.png)

geo是我自己引入的文件。

**打印出来的console**:
![image](https://user-images.githubusercontent.com/50653281/117611987-0a8b2000-b197-11eb-96d0-ddca4423dc35.png)

### What is expected?
正确显示地图

### What is actually happening?
无法显示

**Comment by MafuyuRyan** [comment]
demo: https://codesandbox.io/s/restless-fire-yofjl?file=/src/index.js

demo里是可以的 是js，
但是在我这里的typescript却不行

![image](https://user-images.githubusercontent.com/50653281/117614787-68216b80-b19b-11eb-88a7-978a0e5197b6.png)

**Comment by plainheart** [comment]
似乎导入的 JSON 多了一层 `default`

**Comment by MafuyuRyan** [comment]
@plainheart 我的geoJSON里没有default 这是注册后里面自带的属性 而且js代码里是可以的 到ts就不行了 我看了js的console是这样的 就不知道怎么弄。。
![image](https://user-images.githubusercontent.com/50653281/117620058-a706ef80-b1a2-11eb-8b5d-18ec2ee0ae55.png)

**Comment by MafuyuRyan** [comment]
![image](https://user-images.githubusercontent.com/50653281/117629617-edf9e280-b1ac-11eb-924a-0730e4fb9794.png)
@plainheart 通过这种方式解决了 但我觉得不是很好 希望能帮忙给一个更好的方案 谢谢

**Comment by plainheart** [comment]
或许可以配置 tsconfig.json -> `esModuleInterop` 为 `true`
```ts
import geo from 'xxxx.geo.json'
```

**Comment by MafuyuRyan** [comment]
已经是true了。。不影响使用先这样吧 谢谢了
