### ISSUE TITLE
use dataZoom slider space when dataZoom type is 'inside'

### ISSUE THREAD

**Issue by OrestHk** [apache/echarts#14908]
### What problem does this feature solve?
Would it be possible to extend the size of the chart to the right and bottom when the dataZoom type used is 'inside'.
Currently when using the dataZoom 'inside' type, there seems to be leftower space at the bottom and right of the canvas. This space could be used to extend the size of the chart, making less white spaces when there is another element after the graph.

https://codepen.io/test45/pen/abJOgQK : maybe it can help to see what I'm trying to explain.

Sorry if I missed the property !
Have a nice day !

### What does the proposed API look like?
When using the type 'inside', on any axis, it should allow the remaining space to the graph ?

**Comment by Ovilia** [comment]
You can use `grid.bottom` and `grid.right` to control the position of chart area.

**Comment by OrestHk** [comment]
Sorry I missed that ! Thanks for the info, works well !
