### ISSUE TITLE
change theme after init chart

### ISSUE THREAD

**Issue by behroozbc** [apache/echarts#14901]
### What problem does this feature solve?
hi
I want to change theme after calling init and when my chart rendered  

### What does the proposed API look like?
echartsInstance.changeTheme('themeName');

**Comment by pissang** [comment]
@behroozbc Hi, it is not possible now. You need to re-init the chart if you want to change a theme

**Comment by behroozbc** [comment]
@pissang  hi ,
I know it is not possible now but I want to add this in feature

**Comment by pissang** [comment]
@behroozbc It's not in the plan.
