### ISSUE TITLE
Cannot read property '__dzAxisProxy' of undefined

### ISSUE THREAD

**Issue by 13554599576** [apache/echarts#14919]
### Version
4.9.0

### Steps to reproduce
use this options.
```
{
            grid: {
              containLabel: true,
            },
            series: [
              {
                name: '访问来源',
                type: 'pie',
                radius: ['55%', '40%'],
                data: [
                  { value: 235, name: '视频广告' },
                  { value: 274, name: '联盟广告' },
                  { value: 310, name: '邮件营销' },
                  { value: 335, name: '直接访问' },
                  { value: 400, name: '搜索引擎' },
                ],
                labelLine: {
                  show: false
                }
              },
            ],
          }
```

### What is expected?
show a pie chart

### What is actually happening?
If I use a pie chart, this problem will occur randomly.

error: Cannot read property '__dzAxisProxy' of undefined

**Comment by pissang** [comment]
5.1.0 还有这个问题吗？

**Comment by 13554599576** [comment]
> @13554599576 Please provide a minimum reproducible demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.
> 
> _A minimum reproducible demo_ should contain as little data and components as possible but can still illustrate your problem. This is the best way for us to reproduce it and solve the problem faster.

I am sorry for raising this issue. I have found the problem, sorry

**Comment by leksas** [comment]
@13554599576 您发现具体是什么样的问题呢？怎么解决的呢？
