### ISSUE TITLE
xAxis type "time" label increments instead of scrolling

### ISSUE THREAD

**Issue by alexb823** [apache/echarts#14917]
### Version
5.1.0

### Reproduction link
https://6098b3a39d5adf00075481da--jolly-pike-04f0ab.netlify.app/

### Steps to reproduce
scroll along the xAxis

### What is expected?
For the labels on the xAxis to scroll along with the line chart.

### What is actually happening?
The labels are fixed in position.  They just increment according to the value.

**Comment by yufeng04** [comment]
Could this [example](https://echarts.apache.org/examples/zh/editor.html?c=grid-multiple) help you?
