### ISSUE TITLE
When config option's singleAxis, nameTextStyle.overflow = 'truncate' invalid, width has been setted

### ISSUE THREAD

**Issue by Lysom** [apache/echarts#14911]
### Version
5.1.1

### Steps to reproduce
```js
singleAxis: [
        {
          left: 150,
          name: '这是一段很长的标题名称',
          nameLocation: 'start',
          nameGap: 140,
          nameTextStyle: {
            align: 'left',
            width: 140,
            overflow: 'truncate',
            ellipsis: '...',
            fontSize: 18,
            fontWeight: 'bold'
          }]
```
### What is expected?
singleAxis's name break  when set the width

### What is actually happening?
overflow valid

**Comment by WuYujieJustin** [comment]
I got the same problem. Here are the link to reproduce the bug.

width: 20,
overflow: 'truncate',
ellipsis: '...',

With above option, it does not work as expected

 @[https://www.makeapie.com/editor.html?c=xlT56sbYni&v=5](https://www.makeapie.com/editor.html?c=xlT56sbYni&v=5)

I read some source code. It seems that Echart doesn't do anything on this option
@Lysom @Ovilia

**Comment by Jagan-P** [comment]
The `nameTruncate` property will do this job. Noticed this proprety in `/echarts/src/coord/axisDefault.js`

```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        show: true,
        name: 'bhemmmmmmmmmmmmmm gfdsmmmmmmmmmmmmmmmmmmmmmmmmmmm',
        type: 'value',
        nameTruncate: {
            maxWidth: 100,
            ellipsis: '...',
        }
    },
    series: [{
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line'
    }]
};
```

**Comment by Fnzero** [comment]
I also have this problem, nameTextStyle.width not work

**Comment by Jagan-P** [comment]
> The `nameTruncate` property will do this job. Noticed this proprety in `/echarts/src/coord/axisDefault.js`
> 
> ```
> option = {
>     xAxis: {
>         type: 'category',
>         data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
>     },
>     yAxis: {
>         show: true,
>         name: 'bhemmmmmmmmmmmmmm gfdsmmmmmmmmmmmmmmmmmmmmmmmmmmm',
>         type: 'value',
>         nameTruncate: {
>             maxWidth: 100,
>             ellipsis: '...',
>         }
>     },
>     series: [{
>         data: [150, 230, 224, 218, 135, 147, 260],
>         type: 'line'
>     }]
> };
> ```
> 
> @Lysom @WuYujieJustin

@Fnzero try this, it worked for me.
