### ISSUE TITLE
height is number or string

### ISSUE THREAD

**Issue by behroozbc** [apache/echarts#14914]
### Version
5.1.1

### Steps to reproduce
hi I saw gauge [example](https://echarts.apache.org/examples/en/editor.html?c=gauge-temperature) in detail set height is string but in the [type](https://github.com/apache/echarts/blob/a4df6a1fe1a5e8fb58a0e3536db07dc6f819a655/src/util/types.ts#L1049) is only number.

### What is expected?
height type be string or number

### What is actually happening?
height is number only

**Comment by yufeng04** [comment]
Sorry for your confusion. This is the error of example, the `gauge.detail.height` doesn't support string.  [Code](https://github.com/apache/echarts/blob/master/src/chart/gauge/GaugeView.ts#L631)

**Comment by behroozbc** [comment]
@yufeng04 , @Wdingding hi 
can I help ? and fix this example ?

**Comment by yufeng04** [comment]
Welcome to join us! Just do it!



发自我的iPhone


------------------ Original ------------------
From: behrooz bozorg chami ***@***.***&gt;
Date: Fri,May 14,2021 9:09 PM
To: apache/echarts ***@***.***&gt;
Cc: make it right ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/echarts] height is number or string (#14914)





 
@yufeng04 , @Wdingding hi
 can I help ? and fix this example ?

**Comment by behroozbc** [comment]
@yufeng04 thanks!
where is example repository ?
I cant find 😅😅

**Comment by yufeng04** [comment]
@behroozbc [Here](https://github.com/apache/echarts-website/blob/asf-site/examples/data/gauge-temperature.js#L64)

**Comment by behroozbc** [comment]
hi @yufeng04 
I fix it https://github.com/apache/echarts-website/pull/4

**Comment by pissang** [comment]
@yufeng04 Actually `detail.height` can be percent string
