### ISSUE TITLE
`echart.convertToPixel({ seriesIndex: 0 }, point)`传入坐标值和返回坐标值相同

### ISSUE THREAD

**Issue by yuerdev** [apache/echarts#14935]
### Version
5.0.2

### Steps to reproduce
打印`instance.convertToPixel({ seriesIndex: 0 }, [100,100])`返回值是[100,100]
我通过
```
  const series = instance.getModel().getSeriesByIndex(0);
    const itemLayouts = series.getData()._itemLayouts;
```
获取到 graph force中node点的坐标，然后进行保存，下次进来渲染的时候直接用保存的坐标值渲染
然而获取到的xy值放入graph中发现比例不对
进而发现`convertToPixel`这个api穿进去任何值，返回出来的值还是原来的值，怀疑是个bug

### What is expected?
希望获取到正确的坐标或者得到获取正确坐标的方式

### What is actually happening?
`instance.convertToPixel({ seriesIndex: 0 }, [100,100])`返回值是[100,100]

**Comment by yufeng04** [comment]
Please provide  a demo to reproduce

**Comment by pumpkindev** [comment]
[https://codepen.io/pumpkindev/pen/RwpGQmr](https://codepen.io/pumpkindev/pen/RwpGQmr)
@yufeng04

**Comment by pumpkindev** [comment]
![image](https://user-images.githubusercontent.com/21173134/118669287-38700480-b828-11eb-93ba-d2771508965c.png)
demo 在这里
@yufeng04

**Comment by pumpkindev** [comment]
我想要实现的效果是点击后保持emphasis  adjacency的效果，发现echart目前并不支持这种操作，所以想点击后获取所有点的坐标，将force图例转换成layout:none图例，自定义逻辑，将不相关点颜色变浅，并且使用force图例的坐标，
发现获取的坐标转换后和转换前相同，导致的效果是点击后图表会整体放大两次

**Comment by pumpkindev** [comment]
这个问题什么时候解决啊？

**Comment by yufeng04** [comment]
我看了一下，graph 用坐标系是 view, 这个坐标系里的点的左边就是像素信息，所以使用convertToPixel的时候返回的是同样的值

**Comment by pissang** [comment]
@pumpkindev @yufeng04  我试了下不是相同的值啊

**Comment by pissang** [comment]
@pumpkindev 在鼠标缩放后值就不一样了
