### ISSUE TITLE
In the tree graph. The color of the legend icon does not change. Can you help? 

### ISSUE THREAD

**Issue by yunyeop** [apache/echarts#14933]
### What problem does this feature solve?
set legend icon color

### What does the proposed API look like?
I used version is ^4.8.0
This code doesn't work in V4.8.0
```javascript
data: [
  {
    name: 'symbol',
    itemStyle: {
      color: 'red'
    },
  },
]
```

**Comment by yunyeop** [comment]
I will attach a picture for easy explanation.

this image is version v5
url: https://echarts.apache.org/examples/en/editor.html?c=tree-legend
![image](https://user-images.githubusercontent.com/62085485/118085723-cfd6f100-b3fd-11eb-8ef0-c2b1ee5ecc4d.png)

this image is version v4
![image](https://user-images.githubusercontent.com/62085485/118085966-31975b00-b3fe-11eb-8bc8-1e0d0a877753.png)
It's doesn't working.......
Is there any way to use in v4?

**Comment by pissang** [comment]
You can try setting `borderColor` instead of `color` in v4

**Comment by yunyeop** [comment]
![image](https://user-images.githubusercontent.com/62085485/118434527-30c13a80-b718-11eb-9682-dc7ae82925b9.png)
borderColor also doesn't work.
And I need a way to change the shape color, not the borderColor

**Comment by yunyeop** [comment]
> v4 `borderColor`대신 설정을 시도 할 수 있습니다.`color`

![image](https://user-images.githubusercontent.com/62085485/118434686-6fef8b80-b718-11eb-8a79-a1c79c9d9158.png)
borderColor also doesn't work.
And I need a way to change the shape color, not the borderColor

**Comment by pissang** [comment]
@yunyeop Another way is to change the `symbol` option from the default `'emptyCircle'` to `'circle'`.

**Comment by pissang** [comment]
I'm afraid the only way is to upgrade to v5.

**Comment by yunyeop** [comment]
> 유일한 방법은 v5로 업그레이드하는 것입니다.

okay..
