### ISSUE TITLE
More fine-grained formatter in the tooltip.

### ISSUE THREAD

**Issue by pissang** [apache/echarts#14962]
### What problem does this feature solve?
Currently tooltip can only use one formatter to replace the whole content. As the tooltip dom is getting more and more complex and well designed. Replace the whole content by formatted is not acceptable in most cases. Especially when we only wan't to format the numbers and add units. 

### What does the proposed API look like?
```ts
tooltip: {
    valueFormatter: '',
    nameFormatter: ''
}
```

**Comment by crazyair** [comment]
valueFormatter 添加了，nameFormatter 好像还没加？
