### ISSUE TITLE
The label position is wrong when one of the data is 0

### ISSUE THREAD

**Issue by aoiu** [apache/echarts#14975]
### Version
5.1.1

### Reproduction link
[https://codepen.io/aoiu/pen/RwpGjOj](https://codepen.io/aoiu/pen/RwpGjOj)

### Steps to reproduce
type: bar

the chart has 2 series in 1 stack

the first series of datas is positive or 0, the second series of datas is negative or 0;

the first series label position is 'top'; the second series label is 'bottom';

when the first data is positive and the second data is 0, the label of the second data is wrong

类型：柱状图

两组数据在同一个stack中

第一组数据为正数或0，第二组数据为负数或0；

第一组label位置为'top'，第二组label位置为'bottom'；

当第一个数据为正数而第二个数据为0时，第二个数据的label显示位置错误

### What is expected?
the label of the second data (0) will below the xAxis

第二个数据的label在横坐标下方

### What is actually happening?
the label of the second data (0) is in the top of the first data's bar

第二个数据的label在第一个数据的柱状的顶部

![img](https://i.ibb.co/rbcpCYX/2021-05-18.png)

---
the option is as follows:

option如下：

```
var option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu']
  },
  yAxis: {
    type: 'value'
  },
  series: [{
    data: [120, 0, 200, 0],
    type: 'bar',
    stack: 'test',
    label: {
     show: true,
     position: 'top'
   }
  },
 {
   data: [-120, 0, 0, -100],
   type: 'bar',
   stack: 'test',
   label: {
     show: true,
     position: 'bottom'
   }
 }]
};
```

**Comment by pissang** [comment]
@aoiu 因为你设置了 stack，所以在前一个系列上堆叠了

**Comment by aoiu** [comment]
> @aoiu 因为你设置了 stack，所以在前一个系列上堆叠了

为什么正数和0是在前一个顶部为起点堆叠； 负数是从X坐标轴为起点堆叠？
