### ISSUE TITLE
图例过多显示滚动条

### ISSUE THREAD

**Issue by ClearLove1996** [apache/echarts#14987]
### What problem does this feature solve?
图例部分数据过多，显示滚动的效果，

### What does the proposed API look like?
可以多项选择，现在的是点击翻页滚动，添加可以通过鼠标滚轮来滚动图例，并可以让用户选择是否显示滚动条，从而更有效的优化用户体验。。。

**Comment by jieceng** [comment]
Have you solved this problem

**Comment by Ovilia** [comment]
这个和 Canvas 的实现相差比较远，所以不太可能实现
