### ISSUE TITLE
Paste an ecart instance to the basetexture, and some functions of the instance fail, such as tooltip

### ISSUE THREAD

**Issue by yizhengfeng-jj** [apache/echarts#14981]
### Version
5.1.1

### Reproduction link
[https://codesandbox.io/s/3d-demo-nbq6y](https://codesandbox.io/s/3d-demo-nbq6y)

### Steps to reproduce
step1:
定义echats实例
```javascript
    var canvas = document.createElement('canvas');
    var mapGraphChart = echarts.init(canvas, null, {
    width: 4096, height: 2048
});
mapGraphChart.setOption({
    legend: {},
    tooltip: {},
    dataset: {
        dimensions: ['product', '2015', '2016', '2017'],
        source: [
            {product: 'Matcha Latte', '2015': 43.3, '2016': 85.8, '2017': 93.7},
            {product: 'Milk Tea', '2015': 83.1, '2016': 73.4, '2017': 55.1},
            {product: 'Cheese Cocoa', '2015': 86.4, '2016': 65.2, '2017': 82.5},
            {product: 'Walnut Brownie', '2015': 72.4, '2016': 53.9, '2017': 39.1}
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    // Declare several bar series, each will be mapped
    // to a column of dataset.source by default.
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
});
```
stpe2：替换baseTexture
```javascript
  myChart.setOption({
        backgroundColor: '#000',
        light: {
            main: {
                // color: '#fff'
            }
        },
        globe: {
            baseTexture: mapGraphChart,
            heightTexture: mapGraphChart,

            shading: 'lambert',

            light: {
                ambient: {
                    intensity: 0.4
                },
                main: {
                    intensity: 0.4
                }
            },

            viewControl: {
                autoRotate: false
            }
        }
    });
```

### What is expected?
I hope the functions of ecarts instances are all in the

### What is actually happening?
Tooltip failure

**Comment by helgasoft** [comment]
Confirmed in v.5.4.0.
The documentation [says](https://echarts.apache.org/en/option-gl.html#globe.baseTexture): "mouse actions on Earth will be linked to the echarts instance used on the texture".  
But [this example](https://echarts.apache.org/examples/en/editor.html?c=globe-echarts-gl-hello-world&gl=1&code=PTAEFUGcFNQFwBawO4HsBOAbAJqAtgIYAOo0AHgXkZrKgGakDGCB6ckoBHB85cArumgA6AFAA3VqEYEAdpI4BeUNlSN-eaLLjDGQgnGgBRGpu0AKAOQz5XSwEoA3BKmEiAYRZtQy6M1bswgCWskFw5jYKADSgsvyYmDEA3qKgaaDIQdiIAFygACwADACcAGwxSEEA5ghweQBMhfkAHKIAvk6ibp4BwjBwAPJEcEGosuapoClpMOhB0Bx5ANqTadPpaXAAnkTQeZZullGr6W77aFjYRydpIKAAIugEyKB08ZigkEEAXrB-XuxSBQqDQbvBUEQ8oUYjQ6HVQNCwXMavDoaAAEaoOBwVB4KHHDZpTH8WTYEJVdyoDDYSDLJYAWgAjM00cVCgBdGJLZlo-ls9nsk5tSac8GoTAjSFTSAIVDIPJwdD8aDCjrOUQQkZjHxTSbogiMADWVXQqBJ2EpmAw-wAxIV7dc0lUrei9rqNvqYAAVPiCN3dAEE9LiebISnaU2YHJJTj8HEAJSxBj2dAImBgwrSqscQA) shows **no tooltips**, even though it displays country name on hover.
