### ISSUE TITLE
need Legend component  in "scroll" type can define pageSize to display multiple lines of legend instead of only one line.

### ISSUE THREAD

**Issue by woshixixi** [apache/echarts#14992]
### What problem does this feature solve?
can display multiple lines of legend instead of only one line.

like this:

![show multiple lines](https://user-images.githubusercontent.com/1091500/48556165-1ecf6880-e91e-11e8-9f3b-bc3b4141f179.jpg)

### What does the proposed API look like?
legend:{
   type:"scroll",
   pageSize: 10,
}

**Comment by irbian** [comment]
This is still an issue (as it was in #10922 ), there is any planification or workaround to it?
