### ISSUE TITLE
about the disappearance of middle label in pie chart（关于饼图中间label消失）

### ISSUE THREAD

**Issue by PyduckGo** [apache/echarts#14990]
### Version
5.1.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=x0wPlaximt&v=1](https://www.makeapie.com/editor.html?c=x0wPlaximt&v=1)

### Steps to reproduce
当鼠标移动到 右侧蓝色的“搜索引擎” 区域时， 中间的label会消失，但移动到其他的区域不会出现这种情况

When the mouse moves to the blue "搜索引擎" area on the right, the middle label will disappear, but it will not appear when moving to other areas

### What is expected?
期望中间的label不会消失 
I hope the middle label will not disappear

### What is actually happening?
中间的label消失了
The middle label disappears

---
我想在饼图中间一直显示label,不管是进行select操作还别的操作，中间的label可以一直保持不变

I want to display the label in the middle of the pie chart all the time. The label in the middle can remain unchanged regardless of the select operation or other operations

**Comment by pissang** [comment]
@4869z 因为你配置了 
```ts
emphasis: {
                label: {
                    show: false,
                }
            },
```

**Comment by 4869z** [comment]
如果 去掉这里的配置时 label不会消失
但是选择操作时  中间就会出现下图这样的问题  那我该怎么解决呢

If you remove the configuration here, the label will not disappear
But when you select an operation, the following problem will appear. How can I solve it

![image](https://user-images.githubusercontent.com/23032829/118751735-6e4ad280-b894-11eb-84a1-ae0cc575af68.png)

**Comment by pissang** [comment]
@PyduckGo 可以饼图中间放一个固定的 title 组件，然后监听 mouseover 或者 click 事件后 setOption 更新这个 title 组件的内容
