### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by xx-yyzz** [apache/echarts#15004]
### What problem does this feature solve?
新的需求

### What does the proposed API look like?
tooltip是一个页面容器，可以显示图片等自定义信息，在散点图中，每一个数据点设置为一张图片，鼠标悬停的时候，tooltip悬浮框显示数据点的图片，可以通过代码控制图片宽高。类似symbolSize。

**Comment by pissang** [comment]
I think it is a how-to question rather than a new feature request. It can be done by current API

**Comment by xx-yyzz** [comment]
> ### What problem does this feature solve?
> 新的需求
> 
> ### What does the proposed API look like?
> tooltip是一个页面容器，可以显示图片等自定义信息，在散点图中，每一个数据点设置为一张图片，鼠标悬停的时候，tooltip悬浮框显示数据点的图片，可以通过代码控制图片宽高。类似symbolSize。
>`tooltip{
formatter：function() {
return '<div><img src=""/></div>'
}}`
the 'src' is dynamic. How to achieve it?
