### ISSUE TITLE
About "Bar Race" json data format

### ISSUE THREAD

**Issue by nzk1912** [apache/echarts#15001]
### Version
5.1.1

### Steps to reproduce
example json format: https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/data/asset/data/life-expectancy-table.json

[
41706,
81.8,
22542371,
"Australia",
2011
],

index 0 is value; 
index 3 is name;
index 4 is year;

### What is expected?
what is index_1 and index_2?

### What is actually happening?
what is index_1 and index_2?

**Comment by plainheart** [comment]
Hi, the first line of returned JSON is just the definition for each element in the array.
<img src="https://user-images.githubusercontent.com/26999792/118916482-a0763600-b961-11eb-8760-9e2734f342c0.png" width="400">

**Comment by nzk1912** [comment]
0_0
