### ISSUE TITLE
bug：存在时间轴timeline时，k线图的series-candlestick.data. itemStyle 设置会失效

### ISSUE THREAD

**Issue by dignfei** [apache/echarts#15017]
### Version
5.1.0

### Reproduction link
[隐藏时间轴时正常](https://www.makeapie.com/editor.html?c=x3CZEeJX7t&v=3)

### Steps to reproduce
最后一行的代码：[隐藏时间轴时正常](https://www.makeapie.com/editor.html?c=x3CZEeJX7t&v=3)
`if(false){   
     option1. timeline= timeline
}`
![image](https://user-images.githubusercontent.com/25482706/119228338-20102a80-bb45-11eb-9200-fdbdc9368c9e.png)

将false替换为true，可以看到自定义样式不生效：[显示时间轴时样式失效](https://www.makeapie.com/editor.html?c=x3CZEeJX7t&v=4)
![image](https://user-images.githubusercontent.com/25482706/119228374-52ba2300-bb45-11eb-8cf7-a84785de1d89.png)

### What is expected?
同时使用timeline 和 单个 K 线图数据的图形样式（series-candlestick.data. itemStyle）

### What is actually happening?
添加时间轴timeline 后，单个 K 线图数据的图形样式（series-candlestick.data. itemStyle）会失效。

**Comment by pissang** [comment]
Seems it is caused by a `setOption` update. I updated the code to simplify the case https://www.makeapie.com/editor.html?c=x3CZEeJX7t&v=5 @100pah can take a look

**Comment by dignfei** [comment]
> 似乎是由`setOption`更新引起的。我更新了代码以简化情况https://www.makeapie.com/editor.html?c=x3CZEeJX7t&v=5

你的代码有问题，显示一片空白

**Comment by dignfei** [comment]
> This issue is labeled with `difficulty: easy`.
> @dignfei Would you like to debug it by yourself? This is a quicker way to get your problem fixed. Or you may wait for the community to fix.
> 
> Please have a look at [How to debug ECharts](https://github.com/apache/echarts/blob/master/CONTRIBUTING.md#how-to-debug-echarts) if you'd like to give a try. 🤓

我不擅长这个语言
