### ISSUE TITLE
xAxis position is different on the boxplot

### ISSUE THREAD

**Issue by amuro33** [apache/echarts#15018]
### Version
5.1.1

### Reproduction link
[https://jsfiddle.net/vfk75uc3/2/](https://jsfiddle.net/vfk75uc3/2/)

### Steps to reproduce
The position of the boxplot does not overlap with that of the outlier (scatter)
There are two series and each uses a different x value(category), Why using two spaces?

### What is expected?
boxplot position to overlap with the outlier position

### What is actually happening?
The position of the boxplot does not overlap with that of the outlier

**Comment by pissang** [comment]
I can't see anything unexpected in the demo. Can you provide an example shot to describe it?
