### ISSUE TITLE
HeatMap Component Bug

### ISSUE THREAD

**Issue by SodaMinYT** [apache/echarts#15025]
### Version
5.1.1

### Steps to reproduce
设置heatmap组件的xAis和yAxis的type为“value”，然后放大组件，组件的图和坐标比例不对成
![image](https://user-images.githubusercontent.com/54698166/119430822-0557d480-bd44-11eb-9858-e03bd2a43a65.png)

### What is expected?
放大比例仍一致

### What is actually happening?
放大比例不一致

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=heatmap-large 在改了 yAxis 为 value 的情况下并没有复现出问题，可以提供一个复现的例子吗？

**Comment by SodaMinYT** [comment]
https://www.makeapie.com/editor.html?c=xAlZTWXNn-&amp;v=1
其中的type为value，看不见坐标标签
当改正category可以看见




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] HeatMap Component Bug (#15025)





 
https://echarts.apache.org/examples/zh/editor.html?c=heatmap-large 在改了 yAxis 为 value 的情况下并没有复现出问题，可以提供一个复现的例子吗？
