### ISSUE TITLE
echats typescript echartInstance has no getZr()

### ISSUE THREAD

**Issue by stormrise** [apache/echarts#15028]
### Version
5.1.1

### Steps to reproduce
https://echarts.apache.org/zh/api.html#echartsInstance
https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

### What is expected?
api document has no getZr() api
and using typescript echartInstance.getZr() error: Property 'getZr' does not exist on type 'ECharts'.

### What is actually happening?
should behave normal like in js

**Comment by stormrise** [comment]
I use ts-ignore it works, so maybe there is no types definition,
I hope this document add more description about mouse event like globalout, I acutally do not know when it will work

**Comment by Ovilia** [comment]
Hi, `getZr` doesn't contain doc because it is not supposed to be used for public uses in regular situations.

**Comment by stormrise** [comment]
thanks
so if I want use I need to annotate @ts-ignore ?

**Comment by pissang** [comment]
@stormrise You can extend the type

```ts
import { EChartsType, init, graphic, zrender } from "echarts";

declare module "echarts" {
  interface EChartsType {
    getZr(): zrender.ZRenderType;
  }
}
```

Here is an example

https://codesandbox.io/s/elastic-christian-szztb?file=/index.html

**Comment by stormrise** [comment]
thanks @pissang
