### ISSUE TITLE
API to hide/show toolbox

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#15020]
### What problem does this feature solve?
It is possible to hide/show toolbox using 

```js
chart.setOption({ toolbox: { show: true/false } });
```

However, this resets the state of the chart such as the current interaction within a sunburst chart.

Looking for an API or a way to set the option for toolbox to hide/show without resetting the state. The toolbox hide/show is done based on whether the mouse is on the chart or not using the mouseenter and mouseleave events.

### What does the proposed API look like?
If it's an API, it can be something like `chart.showToolbox(true/false)`.

**Comment by pissang** [comment]
We are planning to add partial updating as a new feature.
