### ISSUE TITLE
invalid transparent and rgba colors in saved SVG file

### ISSUE THREAD

**Issue by mindon** [apache/echarts#15029]
### Version
v5.1.1

### Reproduction link
[https://uzihu.csb.app/](https://uzihu.csb.app/)

### Steps to reproduce
1. render with option
```
     const option = {
        grid: {
          show: true,
          borderWidth: 3,
          fill: "transparent",
          borderColor: "rgba(255,0,0,1)"
        },
        toolbox: {
          feature: {
            saveAsImage: {
              name: "demo",
              type: "svg"
            }
          }
        }
      };
```

2. click save to image to download the svg result

3. drag the svg file into Powerpoint or Inkscape  

### What is expected?

1. transparent background

2. red border

### What is actually happening?
1. black background

2. black background grid without border

---
valid SVG11 colors <https://www.w3.org/TR/SVG11/types.html#DataTypeColor>

**Comment by KamilKozera** [comment]
Hi,

I encountered a problem today while converting SVG to PDF with Inkscape. Inkscape interprets `fill:'transparent'` as `fill:'black'`. Here's a quick solution that might help anyone facing the same issue:

Replace `'transparent'` with `'none'` after setting the chart option and rendering the chart. This ensures that the code executes after the SVG content has been generated and is present in the DOM, allowing it to modify the SVG attributes as desired.

[jsfiddle](https://jsfiddle.net/avzemr9k`)

```javascript
var transparentElements = document.querySelectorAll('svg [fill="transparent"]');
transparentElements.forEach(function(element) {
  element.setAttribute('fill', 'none');
});

**Comment by plainheart** [comment]
@KamilKozera Thanks for your feedback. I believe this can work before v5.5.0 as ecomfe/zrender#767 fixed it. But in v5.5.0, to escape the behavior that `fill: 'none'` makes the SVG element not responsive, the new SSR feature (see [commit](https://github.com/ecomfe/zrender/commit/fb4c2656eae4effd4f215232fbf94d589ca5c9a4#diff-d36c603bc219342aa51e6e0381dfac549a0f907ea7fe6777385edfc127f166a3R66-R69)) overrides the `none` value to `transparent`, which brings this issue back unexpectedly. I will take a look if it can do the overriding conditionally.

cc: @Ovilia

**Comment by Ovilia** [comment]
@plainheart I have no objection to ecomfe/zrender#1076 but from [the spec](https://www.w3.org/TR/css-color-5/#color-syntax), we can see that `transparent` is a valid value for `fill`. Does this problem cause by the bug of SVG implementation of Powerpoint and Inkscape?

**Comment by Ovilia** [comment]
And from 

> A component must not be named ‘none’, because that would clash with the token for missing values.

we can know that the meaning of `none` is more like `we don't know the color value for this element` rather than `this element doesn't have a color value`.

So I think it should make sense to set `transparent` to elements without color.

That being said, if there is a bug with some implementation software, we could change as your PR to prevent exposing the bug.

**Comment by plainheart** [comment]
1. The change from `'transparent'` to `'none'` is to solve the compatibility issue in Powerpoint and Inkscape.
2. `'none'` makes the element not interactable, so you change it back to `'transparent'` in this [commit](https://github.com/ecomfe/zrender/pull/1076/files#diff-d36c603bc219342aa51e6e0381dfac549a0f907ea7fe6777385edfc127f166a3L66-L69).
3. [ecomfe/zrender#1076](https://github.com/ecomfe/zrender/pull/1076) is to solve both issues, we still use `'none'` for no background while making the element interactable via setting the `pointer-events` attribute to `'visible'`.

**Comment by Ovilia** [comment]
Thanks for clarifying the context, which I really got confused about. I've merged that PR. Thanks!
