### ISSUE TITLE
higher z/zlevel elements are hidden when hovered on a overlapping lower z/zlevel elements

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#15022]
### Version
5.1.1

### Steps to reproduce
Use the following bar chart config

```js
option = {
    xAxis: {
        type: 'category',
    },
    yAxis: {
        type: 'value'
    },
    visualMap: {
      type: 'piecewise',
      categories: ['M','W'],
      dimension: 2,
    },
    series: [{
        data: [
            { value: ['Mon',100,'M'], z: 10 },
            { value: ['Mon',20,'W'], z: 20 }
            ],
        type: 'bar',
    }]
};
```

### What is expected?
Hovering over the larger bar shouldn't hide the overlapping smaller bar below as it has higher z value (I also tried with zlevel).

### What is actually happening?
It hides the element with higher z/zlevel.

---
The zindex of html works this way where higher zindex elements always remain on top as you hover over the lower zindex elements.

**Comment by plainheart** [comment]
No document states the data item supports the `z` or `zlevel` option.

**Comment by dirslashls** [comment]
My bad, I mistook that data can have z level based on documentation. Thanks for considering this as a feature.
