### ISSUE TITLE
graph froce力导图添加笛卡尔坐标系后所有点聚集在一条线上

### ISSUE THREAD

**Issue by yuerdev** [apache/echarts#15036]
### Version
5.1.1

### Reproduction link
[https://codepen.io/pumpkindev/pen/BaWZVRr?editors=0010](https://codepen.io/pumpkindev/pen/BaWZVRr?editors=0010)

### Steps to reproduce
1.力导图没有笛卡尔坐标系的情况下，是正常的
2.添加了坐标系后，所有点聚集在一条线上

### What is expected?
添加笛卡尔坐标系后力导图正常

### What is actually happening?
添加笛卡尔坐标系后力导图异常

---
背景是我想力导图渲染完成后转换坐标系
有了坐标系我就可以在线上做飞线图（据我了解做飞线图的话，需要关系点笛卡尔坐标系的坐标）

**Comment by Ovilia** [comment]
直角坐标系上不能应用力引导布局，你的需求可以通过 node 下设置 x，y 实现

**Comment by pumpkindev** [comment]
@Ovilia  我是先用无坐标系生成力引导布局，然后拿出其坐标信息，重新用笛卡尔坐标系渲染，将力导图nodes的坐标（像素信息）进行convertFromPixel转换，
那么convertFromPixel函数，转换出来的坐标，是转换成基于什么坐标系的逻辑坐标?(我转换出来的坐标数据，放在笛卡尔坐标系中，又在一条线上了)

**Comment by pumpkindev** [comment]
https://codepen.io/pumpkindev/pen/JjWyjzv?editors=0010
这里面的x,y数据都是拿的力导图里的（拿到力导图坐标后删除李导图相关配置，添加笛卡尔坐标系重新渲染的），角落里聚集了大量的点，每个点的x,y不相同，他们为什么在笛卡尔坐标系中会聚集在一起

**Comment by Ovilia** [comment]
似乎没理由用 convertFromPixel？convertFromPixel 是把屏幕坐标转为数据点数值，而你的场景如果获得了屏幕坐标，直接用笛卡尔坐标绘制就可以了

**Comment by pumpkindev** [comment]
不转换，直接拿到坐标后，layout:none， coordinateSystem: 'cartesian2d',，
还是和力导图的不一样，和上面的例子效果一致

**Comment by Ovilia** [comment]
直角坐标系上不能应用力引导布局
