### ISSUE TITLE
Example request: util.each import

### ISSUE THREAD

**Issue by dvago** [apache/echarts#15034]
### Version
5.1.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=line-race](https://echarts.apache.org/examples/en/editor.html?c=line-race)

### Steps to reproduce
Given the url (https://echarts.apache.org/examples/en/editor.html?c=line-race) 
I would like to know what's the correct way to import the `each` method to enable the use of `filter` without importing the whole library. See line 11 from your example.

I'm currently importing the library modules via:

```js
import { use } from 'echarts/core'
import { SVGRenderer } from 'echarts/renderers'
import { LineChart } from 'echarts/charts'
import {
  AxisPointerComponent,
  GridComponent,
  TooltipComponent,
  DatasetComponent,
  LegendComponent,
  ToolboxComponent,
  TitleComponent,
  MarkLineComponent,
  MarkPointComponent,
  DataZoomComponent,
  DataZoomInsideComponent,
  DataZoomSliderComponent,
} from 'echarts/components'
```

### What is expected?
The possibility to import utilities such as each without importing the whole echarts library

### What is actually happening?
Can't find anything within the documentation nor online with a sample

---
I tried few random imports without success. 
E.g.
```js
import { each } from 'echarts/util'
```

of course it was just me guessing it.

**Comment by 100pah** [comment]
```ts
import { zrUtil } from 'echarts';
console.log(zrUtil.each);
```

**Comment by dvago** [comment]
Thanks @100pah, it seems working. that was easy :)

You might want to showcase it within the documentation as well, it would be valuable
