### ISSUE TITLE
lines effect period 结束后如何保持当前effect位置。而不是自动消失

### ISSUE THREAD

**Issue by baokeyu123** [apache/echarts#15035]
### What problem does this feature solve?
如果数据来源是webRTC，当数据暂停时，effect不应该消失。

### What does the proposed API look like?
if  period time over。effect can setting keep current position in echarts

**Comment by baokeyu123** [comment]
> 默认是无限循环的，如果还有问题，请提供复现的代码

i'm very happy receive u answer。
loop我设置了fasle，通过data coords属性去确定effect 特效的位置，当它走完了这个流程后，特效effect就消失了，可以让此特效在coords最后的位置停留住吗？

**Comment by baokeyu123** [comment]
@Ovilia 在目前的echart api 文档里，我没有发现解决此问题的办法

Best  Regards!

**Comment by Ovilia** [comment]
> @baokeyu123 Please provide a minimum reproducible demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.
> 
> _A minimum reproducible demo_ should contain as little data and components as possible but can still illustrate your problem. This is the best way for us to reproduce it and solve the problem faster.

@baokeyu123 请提供 demo
