### ISSUE TITLE
折线图  动态更新添加最新一条数据；线条僵硬出现，而不是缓慢A点到B点

### ISSUE THREAD

**Issue by zhanghengda** [apache/echarts#15041]
### Version
5.0.1

### Steps to reproduce
我做分时图 用到这个折现图 动态更新最新数据   ；这个时候虽然有动画控制，但是点和线脱离，线不是A到B点缓慢画出，而是直接展示，不怎么丝滑

### What is expected?
希望可以达到  A点到B点 单个更新数据  丝滑的效果；转折点跟线头一直 划线，就好比一个铅笔在纸上画线一样
借鉴这个网站效果 https://m.expertoption.com/?_ga=2.143304819.754953740.1597663708-1250194983.1597475700

### What is actually happening?
有点僵硬   ，线和点脱离

**Comment by wf123537200** [comment]
这个是不是和 #15042 一样？

**Comment by zhanghengda** [comment]
> 这个是不是和 #15042 一样？

是的 是的 ；谢谢
