### ISSUE TITLE
使用BMap, 在元素内滚动后, 在BMap使用滚轮缩放地图会出现中心点偏移的问题

### ISSUE THREAD

**Issue by xjhjzxh** [apache/echarts#15047]
### Version
5.1.1

### Reproduction link
[https://codepen.io/xjhjzxh/pen/qBrXpmQ?editors=0010](https://codepen.io/xjhjzxh/pen/qBrXpmQ?editors=0010)

### Steps to reproduce
页面内有元素P1, P1有子元素C1,C2, C1和C2的总高度超过P1高度, 需要滚动P1才能看见C2
1. 在C2创建echarts-BMap图形, 
2. 滚动到C2后, 使用鼠标滚轮对地图进行缩放
3. 此时会发现BMap的中心点在缩放过程中偏移

### What is expected?
希望能修复这个问题, 或者告知该怎么处理这个问题

### What is actually happening?
滚动元素后, 地图缩放时中心点偏移

**Comment by plainheart** [comment]
这是百度地图自身问题，似乎是因为百度地图缩放是相对于 body 而不是其父元素，尽量避免在非 body 的滚动容器里加载百度地图，除了改为在 body 内滚动，暂时应该没有更好的解决方案。建议到开发者平台向百度地图提工单询问或反馈。

**Comment by xjhjzxh** [comment]
> 这是百度地图自身问题，似乎是因为百度地图缩放是相对于 body 而不是其父元素，尽量避免在非 body 的滚动容器里加载百度地图，除了改为在 body 内滚动，暂时应该没有更好的解决方案。建议到开发者平台向百度地图提工单询问或反馈。

收到, 感谢答疑
