### ISSUE TITLE
echarts 的站点如何在本地启动, 请问有教程嘛?

### ISSUE THREAD

**Issue by mxy2316868975javascript** [apache/echarts#15044]
### What problem does this feature solve?
echarts 的站点如何在本地启动, 请问有教程嘛?

### What does the proposed API look like?
echarts 的站点如何在本地启动, 请问有教程嘛?

**Comment by plainheart** [comment]
可以参考：https://github.com/apache/echarts-www#dev

**Comment by mxy2316868975javascript** [comment]
> 可以参考：https://github.com/apache/echarts-www#dev
> 相关的仓库：[echarts-www](https://github.com/apache/echarts-www), [echarts-examples](https://github.com/apache/echarts-examples), [echarts-doc](https://github.com/apache/echarts-doc)

没具体看到在哪里有写本地启动站点的字样呀

**Comment by Ovilia** [comment]
@mxy2316868975javascript https://github.com/apache/echarts-website#readme

**Comment by mxy2316868975javascript** [comment]
> @mxy2316868975javascript https://github.com/apache/echarts-website#readme

index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/index-home-pie.png?_v_=20200710_1 404 
(Not Found)
GET http://localhost:8000/echarts/echarts-website/zh/css/main.css?_v_=38679feded net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/js/common.js?_v_=9c455b5db4 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/js/index.js?_v_=1622713621147 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/logo.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/index-home-pie.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/ercode.jpg?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/icon-email.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/icon-twitter.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/icon-weibo.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/icon-github.png?_v_=20200710_1 net::ERR_CONNECTION_REFUSED
index.html:10 GET http://localhost:8000/echarts/echarts-website/zh/images/asf_logo.svg?_v_=20200710_1 net::ERR_CONNECTION_REFUSED

本地启个server会访问不到静态资源
