### ISSUE TITLE
多图表resize()快速触发后会失效

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#15049]
### Version
4.9.0

### Reproduction link
[https://github.com/zhoufanglu/echart-resize-vue](https://github.com/zhoufanglu/echart-resize-vue)

### Steps to reproduce
多图表，resize()与上次resize()间隔很低就会出问题，导致resize失效

### What is expected?
期望成功

### What is actually happening?
结果resize失效,你看柱状图，resize没生效

![FsecqCWfnE](https://user-images.githubusercontent.com/24451091/119923841-16535080-bfa5-11eb-8d2e-8d9cebcb2a1f.gif)

有空的话，可以把我仓库的地址拉下来看看， 窗口监听速度过快的话，resize()就会失效

**Comment by plainheart** [comment]
应该与 #13886 相关，先避免使用 flex / grid 布局，后面还需要讨论合适的解决方案。

**Comment by plainheart** [comment]
是的。
