### ISSUE TITLE
Is there no endAngle in the polar coordinate system?

### ISSUE THREAD

**Issue by Zuojiangtao** [apache/echarts#15059]
### Version
5.1.1

### Reproduction link
[https://codesandbox.io/s/snowy-voice-tf6ut](https://codesandbox.io/s/snowy-voice-tf6ut)

### Steps to reproduce
All codes are connected in codesandbox.

### What is expected?
I want to develop a coordinate system with an angle range.

### What is actually happening?
I can't find the endAngle property in angleAxis.

**Comment by Zuojiangtao** [comment]
![image](https://user-images.githubusercontent.com/22252182/120263724-dbb42580-c2ce-11eb-9a99-8d82a0ad4dfe.png)

I want to achieve this effect like this.

**Comment by Ovilia** [comment]
Currently this is not supported. But I think this is a nice feature to have.

**Comment by Ovilia** [comment]
@Zuojiangtao Are you interested in making a PR for this? We have help you if you are interested to do so. In this way, you can have this feature implemented more quickly. Please check out the [wiki](https://github.com/apache/echarts/wiki) for more information. Thanks!

**Comment by Zuojiangtao** [comment]
@Ovilia OK, I will try to complete this new feature.
