### ISSUE TITLE
Graphic type='image' does not respond to 'bottom' and 'right'

### ISSUE THREAD

**Issue by ohlr** [apache/echarts#15053]
### Version
5.1.1

### Reproduction link
[https://codesandbox.io/s/echarts-pie-horizontal-label-line-forked-35cxc?file=/src/option.js](https://codesandbox.io/s/echarts-pie-horizontal-label-line-forked-35cxc?file=/src/option.js)

### Steps to reproduce
my graphic:
        
const backgroundImage: any = {
            id: "backgroundimage1",
            type: 'image',
            top: 50,
            left: 50,
            bottom: 50,
            right: 50,
            style: {
                image: image?.src,
            },
            scale: [1, 1],
            draggable: false,
            z: -1,
}

my grid:
            grid: {
                top: 50,
                left: 50,
                bottom: 50,
                right: 50,
                show: true
            },

### What is expected?
to my understanding grid and graphic should align

### What is actually happening?
Do not align.
Only top and left positioning of graphic are correct. 
At the bottom and right the graphic has no margin

**Comment by ssthouse** [comment]
@ohlr hi, according to the document：

> Only one between top and bottom can work.

[https://echarts.apache.org/en/option.html#graphic.elements-image.bottom](https://echarts.apache.org/en/option.html#graphic.elements-image.bottom)

**Comment by ohlr** [comment]
Hi @ssthouse,
thanks for the pointer.
