### ISSUE TITLE
Why does echarts display the y-axis style in 4.x version, but not display it in 5.x

### ISSUE THREAD

**Issue by liuyuanmoon** [apache/echarts#15058]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by plainheart** [comment]
For v5, this is by design. To show yAxis line and ticks, you may set as follows,

```js
yAxis: {
    axisLine: {
        show: true
    },
    axisTick: {
        show: true
    }
}
```
