### ISSUE TITLE
折线图datazoom如果里面有很长的数据为空字段，dataZoom 拖拽到空时，当折线图全部为空，页面崩溃，datazoom 渲染空白，纵坐标渲染空白

### ISSUE THREAD

**Issue by illumi520** [apache/echarts#15061]
### Version
最新

### Steps to reproduce
横坐标是[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
纵坐标是[1,1,1,1,1,"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",]

### What is expected?
纵坐标刻度不消失，datazoom 也不消失

### What is actually happening?
横坐标紊乱，datazoom为空百，纵坐标为空白

**Comment by illumi520** [comment]
![image](https://user-images.githubusercontent.com/72330259/120281432-83d7e780-c2eb-11eb-81c0-63bf8f0d44b7.png)
![image](https://user-images.githubusercontent.com/72330259/120281449-89cdc880-c2eb-11eb-82a2-defedd973bc7.png)
不断往右边滑动，就渲染空白

**Comment by BigFaceMaster** [comment]
想问一下 这个问题解决了么？

**Comment by illumi520** [comment]
> 想问一下 这个问题解决了么？

最近版本修复了
