### ISSUE TITLE
Rich text style SVG compatibility problem in Powerpoint

### ISSUE THREAD

**Issue by mindon** [apache/echarts#15064]
### Version
v5.1.1

### Reproduction link
[https://k06zm.csb.app/](https://k06zm.csb.app/)

### Steps to reproduce
1.  use rich option for xAxis
 ```  xAxis: {
    name: '{i|Hello} {sub|world}',
    nameLocation: "middle",
    nameTextStyle: {
      fontFamily: 'Times New Roman',
      fontSize: 19,
      padding: [6, 0],
      rich: {
        sub: {
          fontFamily: 'Times New Roman',
          fontStyle: 'italic',
          verticalAlign: "bottom",
          fontSize: 13
        },
        i: {
          fontFamily: 'Times New Roman',
          fontStyle: 'italic',
          fontSize: 19
        }
      }
    }
  },
```

2. save as SVG file

3. import into a Powerpoint (text rich style lost)

### What is expected?
rich text styled as they're defined

### What is actually happening?
rich text styles lost in PPT

---
the SVG code ```<text style="font: italic 19px &quot;Times New Roman&quot;">Hello</text>``` not working in PPT, it works in Inkscape.

if being changed into ```<text font-style="italic" font-size="19" font-family="Times New Roman">Hello</text>```, it works in both.

**Comment by plainheart** [comment]
@pissang The font issue still needs to discuss how to solve it simply and elegantly. Since we're using the format like `font: 12px Arial bold`.

**Comment by pissang** [comment]
@plainheart font is composed in https://github.com/ecomfe/zrender/blob/master/src/graphic/Text.ts#L881 . Perhaps for the SVG renderer, we can keep each part instead of composing it to a single font string?

**Comment by plainheart** [comment]
>  Perhaps for the SVG renderer, we can keep each part instead of composing it to a single font string?

@pissang  Yeah, it would be easier if we can keep every part.


And I notice a potential bug(?) that is not related to this issue. But it looks like a typo. Please see https://github.com/ecomfe/zrender/blob/master/src/graphic/Text.ts#L748-L752

`getStroke` or `getFill`?

**Comment by pissang** [comment]
@plainheart I believe it's a typo and should be `getFill`

**Comment by sz-p** [comment]
Fonts and attributes are still in the style, not attributes


![image](https://user-images.githubusercontent.com/14040327/157367846-35a1fd30-aa04-4e5d-bc4b-acdbda034792.png)

@pissang
