### ISSUE TITLE
echarts 最新版散点图不显示

### ISSUE THREAD

**Issue by fancyhejianyang** [apache/echarts#15066]
### Version
5.1.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=xA_MARLgIX&v=1](https://www.makeapie.com/editor.html?c=xA_MARLgIX&v=1)

### Steps to reproduce
直接复制的官方demo源码

### What is expected?
如何才能正常显示或者修改配置

### What is actually happening?
空白页

**Comment by plainheart** [comment]
需要引入百度地图API script 和 echarts-bmap 扩展插件

```html
<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=你的API KEY"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5/dist/extension/bmap.min.js"></script>
```

**Comment by fancyhejianyang** [comment]
solved perfectly!
