### ISSUE TITLE
hover、click事件多次触发finished的问题

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#15074]
### Version
4.9.0

### Steps to reproduce
我想在setOption()后触发finished,但是又不想在hover、click的时候触发finished事件

### What is expected?
我想在setOption()后触发finished,但是又不想在hover、click的时候触发finished事件

### What is actually happening?
在hover、click的时候触发了finished事件

**Comment by zhoufanglu** [comment]
标记判断是否为第一次finished不行。
我需要的是 setOption一次， 触发一次finsihed方法，请问有什么方案吗？

**Comment by zhoufanglu** [comment]
最后还是暂时使用标记的方法解决了loading的问题，我感觉这样是治标不治本。有没有新的api
```js
    this.myChart.on('finished', () => {
      if (this.loading) {
        //如果还是加载状态，关闭Loading
        this.$emit('closeLoading')
      }
      if (!this.isFirstFinished) {
        //只有在第一次的时候resize
        this.isFirstFinished = true
        setTimeout(() => {
          this.myChart.resize()
        })
      }
    })
```

**Comment by Getchang** [comment]
放到一个promise里面
`
let prom = new Promise(resolve => { 
       this.myChart.on('finished', function () {
               resolve()
        })
})
`
然后
`prom.then(() => { this.$emit('closeLoading') })`

**Comment by plainheart** [comment]
See https://github.com/apache/echarts/issues/10037#issuecomment-853596460

**Comment by zhoufanglu** [comment]
> 放到一个promise里面
> `let prom = new Promise(resolve => { this.myChart.on('finished', function () { resolve() }) })`
> 然后
> `prom.then(() => { this.$emit('closeLoading') })`



> 放到一个promise里面
> `let prom = new Promise(resolve => { this.myChart.on('finished', function () { resolve() }) })`
> 然后
> `prom.then(() => { this.$emit('closeLoading') })`

我之前试过了 没用

**Comment by Getchang** [comment]
> > 放到一个promise里面
> > `let prom = new Promise(resolve => { this.myChart.on('finished', function () { resolve() }) })`
> > 然后
> > `prom.then(() => { this.$emit('closeLoading') })`
> 
> > 放到一个promise里面
> > `let prom = new Promise(resolve => { this.myChart.on('finished', function () { resolve() }) })`
> > 然后
> > `prom.then(() => { this.$emit('closeLoading') })`
> 
> 我之前试过了 没用

> 这种做法是没有解决多次触发finished，但是可以让你的后续业务只触发一次，如果非要只触发一次finished，可以在业务操作执行后，解绑事件监听finished。
`prom.then(() => { this.$emit('closeLoading'); this.myChart.off('finished')})`
