### ISSUE TITLE
After setting the minimum value of Y-axis min, the data is stacked and the plot is missing

### ISSUE THREAD

**Issue by simmonfang** [apache/echarts#15083]
### Version
4.9.0

### Steps to reproduce
[{type:"line",stack:"a",areaStyle:{color:red,origin:'start'},data:[22,22,22,22,22]},{type:"line",stack:"a",areaStyle:{color:blue,origin:'auto'},data:[0,0,0,22,22]}]
手动设置yAxis.min = 10之后 就出现上面的问题

### What is expected?
堆叠趋势图stack正常拼接

### What is actually happening?
堆叠趋势图stack没有正常拼接，出现背景缺失

---
https://user-images.githubusercontent.com/61592598/120740545-f8966600-c525-11eb-8a4f-545389b61605.png
https://user-images.githubusercontent.com/61592598/120740584-0b109f80-c526-11eb-8d16-738bdd51df3b.png

**Comment by simmonfang** [comment]
![1](https://user-images.githubusercontent.com/61592598/120761246-92bad600-c547-11eb-93b1-7fc65276899f.png)
![2](https://user-images.githubusercontent.com/61592598/120761264-977f8a00-c547-11eb-92df-56f7c195da9b.png)
How to solve this problem

**Comment by susiwen8** [comment]
Related to #9317
