### ISSUE TITLE
Performance echarts - High JS and CPU usage

### ISSUE THREAD

**Issue by JESUMH** [apache/echarts#15099]
### Version
4.9.0

### Steps to reproduce
Hi,

I’m using echarts on my project and I analyse CPU and JS usage with Chrome Dev Tools. I see a high usage on updateAndAddDisplayable process (20.48%). Also, I see high zrender usage (zrender version: "4.3.2").

Capture image
![resource-monitoring](https://user-images.githubusercontent.com/69010346/121009557-9c854900-c794-11eb-9074-73aa7d721f70.png)

```javascript


let options: EChartOption = {
  grid: {
	bottom: 155,
	// Calculate offset to display custom yaxis element
	left: offsetL,
	right: offsetR
  },
  dataZoom: [
	  {
		type: 'slider',
		show: true,
		realtime: false,
		start: this.graphicSettingStore.zoomStart,
		end: this.graphicSettingStore.zoomEnd,
		bottom: 50,
		handleIcon: 'path://M10.7,11.9H9.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4h1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
		handleSize: '100%',
		showDetail: false
	  }
	],
  tooltip: {
	show: true,
	showDelay: 30,
	renderMode: 'html',
	triggerOn: 'click',
	formatter: function (params: any, ticket: any, callback: any) {
	  let res = '';
	  if (params != null && params.length > 0) {
		res  = '<ul>';
		res = params[0].axisValueLabel;
		for (let param of params) {
		  if (param.seriesName !== 'a') {
			res  =
			  '<br/><span style="color:'  
			  param.color  
			  '">&#9679;</span>&nbsp;&nbsp;';
			res  =
			  '<span style="color:white;">'  
			  param.seriesName  
			  ':&nbsp;'  
			  param.data[1]  
			  '</span>';
		  }
		}
		res  = '</ul>';
	  }
	  callback(ticket, res);
	  return res;
	},
  },

  toolbox: {
	show: true,
	showTitle: true,
	itemSize: 30,
	feature: {
	  dataZoom: {
		yAxisIndex: 'none',
		title: {
		  zoom: 'Zoom',
		  back: 'Back'
		},
	  },
	  restore: {
		title: 'Restore'
	  },
	},
  },
  xAxis: [
	{
	  type: 'time',
	  axisPointer: {
		show: true,
		handle: {
		  show: true,
		  color: '#a9b7ca',
		},
		label: {
		  show: false,
		  formatter: function (params: any) {
			return Utils.formateDate2(new Date(params.value));
		  },
		},
	  },
	  boundaryGap: false,
	  axisLine: { onZero: false },
	  axisLabel: {
		formatter: function (value: any) {
		  return Utils.formateDate2(new Date(value));
		},
	  },
	},
  ],
  // Array custom yaxis element
  yAxis: yAxis,
  // Array of series (30 series)
  series: series,
};

```

### What is expected?
High performance.

### What is actually happening?
Slow performance. All computer is working slowly and it has a lot of echarts objects

**Comment by pissang** [comment]
Are you updating the options frequently?

**Comment by JESUMH** [comment]
@pissang yes. This chart option show realtime data. I have an observable timer configured every 30 seconds and reload chart data. I'm not sure that it is right or if there are other option to refresh chart without setOption.

Thank you for your response.

**Comment by JESUMH** [comment]
> Are you updating the options frequently?
@pissang yes. This chart option show realtime data. I have an observable timer configured every 30 seconds and reload chart data. I'm not sure that it is right or if there are other option to refresh chart without setOption.

Thank you for your response.

**Comment by pissang** [comment]
Updating per 30 seconds should not be costly. Do you mind providing your reproducible demo?

**Comment by JESUMH** [comment]
> Updating per 30 seconds should not be costly. Do you mind providing your reproducible demo?

I'm trying to create project on stackblitz. I will contact you when available.
Thanks

**Comment by JESUMH** [comment]
> Updating per 30 seconds should not be costly. Do you mind providing your reproducible demo?

Hi @pissang,

This is reproducible demo. There is a mock file with data example. Real project get data from backend server with HttpClient (about 100.000).
https://stackblitz.com/edit/chart-memory-demo?file=src/app/app.component.ts 

Thank you so much

**Comment by pissang** [comment]
Hi @JESUMH. I didn't see high CPU usage in this example

**Comment by JESUMH** [comment]
Hi @pissang, 

I have updated all project to the last Angular version. Also, I have updated echarts library and zrender. Application performance has been improved but it is still high (1-1.5GB).


`
"echarts": {
      "version": "5.1.2",
      "resolved": "https://registry.npmjs.org/echarts/-/echarts-5.1.2.tgz",
      "integrity": "sha512-okUhO4sw22vwZp+rTPNjd/bvTdpug4K4sHNHyrV8NdAncIX9/AarlolFqtJCAYKGFYhUBNjIWu1EznFrSWTFxg==",
      "requires": {
        "tslib": "2.0.3",
        "zrender": "5.1.1"
      },
      "dependencies": {
        "tslib": {
          "version": "2.0.3",
          "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.0.3.tgz",
          "integrity": "sha512-uZtkfKblCEQtZKBF6EBXVZeQNl82yqtDQdv+eck8u7tdPxjLu2/lp5/uPW+um2tpuxINHWy3GhiccY7QgEaVHQ=="
        }
      }
    },
`
