### ISSUE TITLE
x坐标上的label能换行吗？

### ISSUE THREAD

**Issue by rogerwei** [apache/echarts#151]
如题，比如“闪烁次数”，显示成：
闪烁
次数

？label的sytle应该怎么配置呢？

**Comment by AllyW** [comment]
Try this:
`axisLabel: {interval: 0, formatter: function (value) {return value.substr(0, 2) + '\n' + value.substr(2)}}`
it works for me.
![default](https://cloud.githubusercontent.com/assets/8137253/23743807/022f01ac-04ed-11e7-9018-235cbc3aa947.PNG)
