### ISSUE TITLE
visualMap doesn't have seriesId field

### ISSUE THREAD

**Issue by dvtate** [apache/echarts#15100]
### Version
5.1.1

### Reproduction link
[http://jsfiddle.net/1kx45gnt/1/](http://jsfiddle.net/1kx45gnt/1/)

### Steps to reproduce
- candle sticks have inverted colors
- visualMap doesn't have option to use seriesId
- typescript and example viewer give false impression that visualMapId property exists on series (not easy to fix)

### What is expected?
- when the close is higher than the open, the bar should be green
- when the close is lower than the open the bar should be red
- visualMap should have option to add a seriesId field

### What is actually happening?
- when close is higher than open the bar is red
- when close is lower than open the bar is green
- 

---
I think there is a typo in the candlesticks code and there really should be a seriesId field for visualMap

I can try looking through the code and making a PR which addresses these two things

**Comment by Ovilia** [comment]
Please check the description in [About color of increase and decrease](https://echarts.apache.org/en/option.html#series-candlestick):

> Different countries or regions have different implications on the color of candle stick chart. It may use red to imply increasing with red and decreasing with blue (in China mainland, Taiwan, Japan, Koera, and so on), or to imply increasing with green and decreasing with red (in Europe, North America, Hong Kong, Singapore, and so on). Besides color, the increase and decrease of stock may also be represented with candle stick with or without filling colors.
>
> We use red to represent increasing and blue decreasing by default. If you want to change the configuration, you may change the following parameters.
>
> - series-candlestick.itemStyle.color: fill color for bullish candle stick (namely, increase)
> - series-candlestick.itemStyle.color0: fill color for bearish candle stick (namely, decrease)
> - series-candlestick.itemStyle.borderColor: border color for bullish candle stick (namely, increase)
> - series-candlestick.itemStyle.borderColor0: border color for bearish candle stick (namely, decrease)

**Comment by dvtate** [comment]
Ok that's valid reasoning. Still would love a `seriesId` field for `visualMap` ... will have a look through the source again at work tomorrow to see if it's something I can pr
