### ISSUE TITLE
bar series with polar and markPoint will error

### ISSUE THREAD

**Issue by lgl017** [apache/echarts#15109]
### Reproduction link
[https://codepen.io/lgl017/pen/LYWBQXy](https://codepen.io/lgl017/pen/LYWBQXy)

### Steps to reproduce
see codepan

### What is expected?
chart show normally

### What is actually happening?
clampData is not a function

---
I am temporarily modifying the code to make it work, please implement polar coordSys.clampData, or add a judgment to aviod error
![image](https://user-images.githubusercontent.com/27935867/121297167-7abacc00-c924-11eb-90a3-0a0a6ab1d022.png)

**Comment by AmosChenYQ** [comment]
Hi, I'm working on [this project](https://summer.iscas.ac.cn/#/org/prodetail/210460548?lang=en) and now trying to solve some easy tasks to get familiar with echarts.
