### ISSUE TITLE
设置bar中的emphasis的focus属性为self时，行为不一致

### ISSUE THREAD

**Issue by galaxias** [apache/echarts#15116]
**Version**
5.1.2

**Steps to reproduce**

1. 在示例https://echarts.apache.org/examples/en/editor.html?c=bar-brush, 添加 focus: 'self'。完整代码
`var xAxisData = [];
var data1 = [];
var data2 = [];
var data3 = [];
var data4 = [];

for (var i = 0; i < 10; i++) {
    xAxisData.push('Class' + i);
    data1.push((Math.random() * 2).toFixed(2));
    data2.push((Math.random() * 5).toFixed(2));
    data3.push((Math.random() + 0.3).toFixed(2));
    data4.push(-Math.random().toFixed(2));
}

var emphasisStyle = {
     focus: 'self',
    itemStyle: {
        shadowBlur: 10,
        shadowColor: 'rgba(0,0,0,0.3)'
    }
};

option = {
    legend: {
        data: ['bar', 'bar2', 'bar3', 'bar4'],
        left: '10%'
    },
    brush: {
        toolbox: ['rect', 'polygon', 'lineX', 'lineY', 'keep', 'clear'],
        xAxisIndex: 0
    },
    toolbox: {
        feature: {
            magicType: {
                type: ['stack', 'tiled']
            },
            dataView: {}
        }
    },
    tooltip: {},
    xAxis: {
        data: xAxisData,
        name: 'X Axis',
        axisLine: {onZero: true},
        splitLine: {show: false},
        splitArea: {show: false}
    },
    yAxis: {},
    grid: {
        bottom: 100
    },
    series: [
        {
            name: 'bar',
            type: 'bar',
            stack: 'one',
            emphasis: emphasisStyle,
            data: data1
        },
        {
            name: 'bar2',
            type: 'bar',
            stack: 'one',
            emphasis: emphasisStyle,
            data: data2
        },
        {
            name: 'bar3',
            type: 'bar',
            stack: 'two',
            emphasis: emphasisStyle,
            data: data3
        },
        {
            name: 'bar4',
            type: 'bar',
            stack: 'two',
            emphasis: emphasisStyle,
            data: data4
        }
    ]
};

myChart.on('brushSelected', renderBrushed);

function renderBrushed(params) {
    var brushed = [];
    var brushComponent = params.batch[0];

    for (var sIdx = 0; sIdx < brushComponent.selected.length; sIdx++) {
        var rawIndices = brushComponent.selected[sIdx].dataIndex;
        brushed.push('[Series ' + sIdx + '] ' + rawIndices.join(', '));
    }

    myChart.setOption({
        title: {
            backgroundColor: '#333',
            text: 'SELECTED DATA INDICES: \n' + brushed.join('\n'),
            bottom: 0,
            right:'10%',
            width: 100,
            textStyle: {
                fontSize: 12,
                color: '#fff'
            }
        }
    });
}`

2. 在示例https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack, 添加 focus: 'self'。完整代码
`var emphasisStyle = {
    focus: 'self',
    itemStyle: {
        shadowBlur: 10,
        shadowColor: 'rgba(0,0,0,0.3)'
    }
};

option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {            // Use axis to trigger tooltip
            type: 'shadow'        // 'shadow' as default; can also be 'line' or 'shadow'
        }
    },
    legend: {
        data: ['Direct', 'Mail Ad', 'Affiliate Ad', 'Video Ad', 'Search Engine']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'value'
    },
    yAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        splitLine: {show: false},
        splitArea: {show: false}
    },
    series: [
        {
            name: 'Direct',
            type: 'bar',
            stack: 'one',
            label: {
                show: true
            },
            emphasis: emphasisStyle,
            data: [320, 302, 301, 334, 390, 330, 320]
        },
        {
            name: 'Mail Ad',
            type: 'bar',
            stack: 'one',
            label: {
                show: true
            },
            emphasis: emphasisStyle,
            data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
            name: 'Affiliate Ad',
            type: 'bar',
            stack: 'one',
            label: {
                show: true
            },
            emphasis: emphasisStyle,
            data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
            name: 'Video Ad',
            type: 'bar',
            stack: 'one',
            label: {
                show: true
            },
            emphasis: emphasisStyle,
            data: [150, 212, 201, 154, 190, 330, 410]
        },
        {
            name: 'Search Engine',
            type: 'bar',
            stack: 'one',
            label: {
                show: true
            },
            emphasis: emphasisStyle,
            data: [820, 832, 901, 934, 1290, 1330, 1320]
        }
    ]
};`

**What is expected?**
当鼠标悬停在某个series上时，只高亮显示此bar。
**What is actually happening?**
示例1中显示正常，而在示例2中所有的bar都淡出了。

**Comment by kchjxxgh** [comment]
我也遇到同样的问题了，应该是bar chart的bug

**Comment by ldc-37** [comment]
复现了此问题，但是我认为不是bug：

@galaxias 的两个例子中的 options.tooltip.trigger 不一致，一个没有配置（默认值是 'item'），一个是 'axis'。后者意味着鼠标移到整个柱子附近就触发 emphasis （而不是以 柱子中的一个色块 来判定），所以 focus: 'self' 的配置会失效。

这一点在文档上没有体现，是不是可以请开发团队考虑加一下呢~

**Comment by susiwen8** [comment]
> 这一点在文档上没有体现，是不是可以请开发团队考虑加一下呢~

PR is welcome
