### ISSUE TITLE
Why the map folder is removed from 5.0.0-rc.3?

### ISSUE THREAD

**Issue by taosha121** [apache/echarts#15119]
### Version
5.0.0-rc.3

### Steps to reproduce
1. install echarts 5.x
2. Cannot initiallize china map component

### What is expected?
I want to use china map component

### What is actually happening?
The china map canvas is a blank one.

**Comment by taosha121** [comment]
I am using echarts-in-react and I want to initiallize a China map but I found that from 5.0 the `/map` folder is removed so the map cannot show in my app.
Related code(after the map folder removed, I cannot import china geo data and register in echarts):

```
import React from 'react';
import china from 'echarts/map/json/china.json';
import echarts from 'echarts';
import ReactECharts from 'echarts-for-react';
const ProjectLocation = () => {
    echarts.registerMap('china', china);
   

    const option = {
        geo: {
          map: 'china',
       
        },
        visualMap: {
       
        },
        series: [
      
        ],
      };

  return <ReactECharts option={option} />;
};
export default ProjectLocation;
```

**Comment by pissang** [comment]
We don't recommend using these map data anymore because they may have issues. You can still get the map data from `https://github.com/apache/echarts/blob/master/test/data/map/json/china-new.json` or older versions.

**Comment by taosha121** [comment]
@pissang Thanks for reply.
So will you remove the test folder in future? I am not sure whether this is safe for my app to use some data there.
Or what's the best practice to use a China map.

**Comment by pissang** [comment]
@taosha121 I can't promise it won't be moved to somewhere else in the further days since this data is mainly for running test cases now. You should always download the map data instead of loading it from our repo.

**Comment by taosha121** [comment]
OK, that's clear. We can close this issue now.
