### ISSUE TITLE
建议在series配置项中添加配置项xAxisId, yAxisId, polarId，可以代替xAxisIndex, yAxisIndex, polarIndex来选择坐标轴。

### ISSUE THREAD

**Issue by sch-xinlv** [apache/echarts#15128]
### What problem does this feature solve?
在更新series时，通过index选择坐标轴可能会出错，通过ID选取更方便。
所以，建议在series配置项中添加配置项xAxisId, yAxisId, polarId，可以代替xAxisIndex, yAxisIndex, polarIndex来选择坐标轴。

### What does the proposed API look like?
可以这样使用xAxisId
```javascript
myChart.setOption({series: { id: 'special', xAxisId: 'special' }})
```

**Comment by pissang** [comment]
现在是支持的
