### ISSUE TITLE
If { focus:'adjacency' } is enabled on graph component, the legend hovering effect is incorrect

### ISSUE THREAD

**Issue by ShengAndShu** [apache/echarts#15127]
### Version
5.0.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=graph](https://echarts.apache.org/examples/zh/editor.html?c=graph)

### Steps to reproduce
1. use `focus:'adjacency'`  in a graph component (or just open the link above)
2. Hover the mouse over each legend

### What is expected?
When each legend is hovered by the mouse, the effect is different

### What is actually happening?
When each legend is hovered by the mouse, the effect is same

---
It looks like the hovering of legends triggers the effect of adjacency.
![graph](https://user-images.githubusercontent.com/23092564/121533308-be9bf700-ca32-11eb-8e84-1f8c2eb9ee7a.png)

**Comment by susiwen8** [comment]
Duplicate with #13869
