### ISSUE TITLE
dataZoom里的趋势线在堆叠条形图上面显示不正确

### ISSUE THREAD

**Issue by daniear** [apache/echarts#15121]
### Version
5.1.1

### Reproduction link
[https://codepen.io/imdanielwu/full/zYZJNqK](https://codepen.io/imdanielwu/full/zYZJNqK)

### Steps to reproduce
在堆叠条形图上添加type为slider的dataZoom后趋势线显示不正确

### What is expected?
在堆叠条形图上添加type为slider的dataZoom后趋势线显示出整体趋势线

### What is actually happening?
dataZoom里的趋势线在堆叠条形图上面显示不正确，趋势是最下面一层条形图的趋势，并不是所有堆叠以后的总和

---
dataZoom里的趋势线在堆叠条形图上面显示不正确，趋势是最下面一层条形图的趋势，并不是所有堆叠以后的总和，不知道是不是我有什么参数没有设置。

**Comment by Chasen-Zhang** [comment]
stackStrategy: 'all',
