### ISSUE TITLE
data zoom is not working with chart with to bar graph 

### ISSUE THREAD

**Issue by spyshow** [apache/echarts#15139]
### Version
5.0.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=xbX8RRzWJX&v=1](https://www.makeapie.com/editor.html?c=xbX8RRzWJX&v=1)

### Steps to reproduce
if you change the data zoom the first bar graph is not moving , only the upper bar graph is moving correctly

### What is expected?
both upper and downer bar graph should move with the datazoom

### What is actually happening?
the upper bar graph is moving but the downer one is not

**Comment by pissang** [comment]
@spyshow That's because the bottom bar is using another xAxis/yAxis that is not controlled by the `dataZoom`

**Comment by spyshow** [comment]
Isnt there any way other than custom series?
