### ISSUE TITLE
map3d: error when label.show is true

### ISSUE THREAD

**Issue by tcy941618** [apache/echarts#15134]
### Version
"echarts": "5.1.2",

"echarts-gl": "2.0.4",

### Reproduction link
[https://codesandbox.io/s/youthful-glitter-9uiry](https://codesandbox.io/s/youthful-glitter-9uiry)

### Steps to reproduce
this is a demo.

https://codesandbox.io/s/youthful-glitter-9uiry

when label option be set to `{show: true}`,  got error, error message is `Uncaught TypeError: Cannot read property '0' of undefined`, it is also happend when hover 

![截图](https://user-images.githubusercontent.com/18227221/121645589-f2c0f780-cac6-11eb-93eb-ea45655e3bfa.png)

maybe in line 92 is not `region.center` but `region._center`?

### What is expected?
work fine

### What is actually happening?
got error

**Comment by pissang** [comment]
@gwtjs Hi, I just published echarts-gl@2.0.5 to fix it
