### ISSUE TITLE
Echart-GL example global wind visualization 示例下载后无法工作

### ISSUE THREAD

**Issue by huaweiping** [apache/echarts#15130]
### Version
5.1.2

### Steps to reproduce
1. 下载  global wind visualization: https://echarts.apache.org/86440d6b-dc71-4da5-ab4f-38101e6125a1

2. 在<body>中添加必要js文件，
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="./echarts-gl.min.js" type="text/javascript"></script>
    以及变量
        var ROOT_PATH = 'https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples';

### What is expected?
如example所示

### What is actually happening?
报错:
echarts-gl.min.js:1 Uncaught TypeError: Cannot read property 'dimensions' of undefined
    at n._updateData (echarts-gl.min.js:1)
    at n.render (echarts-gl.min.js:1)
    at t.progress (echarts.min.js:45)
    at t._doProgress (echarts.min.js:45)
    at t.perform (echarts.min.js:45)
    at echarts.min.js:45
    at e.<anonymous> (echarts.min.js:45)
    at Array.forEach (<anonymous>)
    at P (echarts.min.js:35)
    at e.eachSeries (echarts.min.js:45)

---
尝试添加china.js作为地图文件，仍然失败

**Comment by pissang** [comment]
没引入百度地图 SDK？

**Comment by huaweiping** [comment]
抱歉我不太懂这个和百度地图有什么关系，麻烦可以解释一下吗？

另外我这边其实并不需要加载地图，只需要有矢量场即可，请问有什么解决方案吗？

谢谢！

**Comment by huaweiping** [comment]
我在网上也找到类似的问题
https://blog.csdn.net/qq_37592561/article/details/89875557

但按照他的解决方案，仍然无法运行，出现了相同的报错。

**Comment by pissang** [comment]
@huaweiping 你下载的这个例子是用了 [百度地图插件的](https://github.com/apache/echarts/tree/master/extension-src/bmap)，因为这是个 GIS 的可视化，需要底层提供 GIS 地图

我不清楚你的数据是什么类型的矢量场数据，如果是 GIS 数据，可以使用百度地图插件或者用 echarts 的 geo 组件，如果是普通的二维数据就可以参考 https://echarts.apache.org/examples/zh/editor.html?c=flowGL-noise&gl=1&theme=dark 这个例子
