### ISSUE TITLE
如何做离屏渲染

### ISSUE THREAD

**Issue by fukai007** [apache/echarts#15135]
### Version
5.1.2

### Steps to reproduce
目的: 使用离屏渲染生成图片(不想把图表显示在页面,想显示导出的base64图片[myChart.getDataURL()])

### What is expected?
列表有很多数据,不想都是用echarts,而是用一个echarts实例循环导出图片后再加载图片(内容大小不变只是数据发生变化)

### What is actually happening?
    var off_ce = document.createElement("canvas");
    off_ce.classList.add("chart");
    off_ce.style = "width:50px;height:50px;";
    window.off_ce = off_ce;
    var myChart = echarts.init(off_ce);
    myChart.setOption(this.option);
    console.log("sssss", myChart.getDataURL());
    window.imgvc.src = myChart.getDataURL();

导出不成功

**Comment by pissang** [comment]
echarts.init 的时候指定 width 和 height，dom 没插入到 document 里 echarts 是获取不到真实的高宽的

**Comment by ALLLRON** [comment]
> echarts.init 的时候指定 width 和 height，dom 没插入到 document 里 echarts 是获取不到真实的高宽的
> 
> ```js
> var myChart = echarts.init(off_ce, null, { width: 50, height: 50 });
> ```
const chartNode = document.createElement("div");

  const chart = echarts.init(chartNode, "", {
    width: options.width,
    height: options.height,
  });

  chart.setOption({ ...options, animation: false });

  const base64 = chart.getDataURL({
    type: "png",
    pixelRatio: 1,
    backgroundColor: "#fff",
  });
通过这个方式离屏绘制出来的图表没有适应容器大小：
![image](https://user-images.githubusercontent.com/31984854/143550133-3d93c2c0-6bd0-4eb5-a22d-1c334f429b72.png)
