### ISSUE TITLE
The 1px outer border of the column chart cannot be removed

### ISSUE THREAD

**Issue by suptwo** [apache/echarts#15136]
### Version
4.8.0 or @latest

### Steps to reproduce
Then configuration ：
```js
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar',
        itemStyle: {
            borderColor: 'red',
            // borderWidth: 1
        }
    }]
};
```
BorderWidth defaults to 0 setting border Color with 1px color
When borderWidth is set to 0, there will still be 1px light gray color

### What is expected?
The 1px frame is not displayed by default

### What is actually happening?
shows the 1px box
![pic-1](https://user-images.githubusercontent.com/12033906/121833529-24240800-ccff-11eb-9727-6d61c3f61fcb.png)
![pic-2](https://user-images.githubusercontent.com/12033906/121833546-29815280-ccff-11eb-8e3d-025c4b7480d4.png)

**Comment by finkrer** [comment]
@pissang this still occurs FYI. To reproduce, open the demo here:
https://echarts.apache.org/examples/en/editor.html?c=bar-simple

Look at the right border of the first bar (I don't see it on the other sides, interestingly).

The border is actually smaller than 1px and is very light, you have to zoom in a lot to see it. Still, if you remove the `barCategoryGap`, it overlaps the neighboring item and is very noticeable.

I think this has nothing to do with the actual CSS border, it's probably a rendering issue.
