### ISSUE TITLE
Hope the pie item style support conic-gradient

### ISSUE THREAD

**Issue by zemelLeong** [apache/echarts#15142]
### What problem does this feature solve?
According to the echarts document. The pie item style only supports linear gradient and radial gradient. But I think the conic gradient could be better in the pie.

### What does the proposed API look like?
https://codesandbox.io/s/conic-gradient-pie-k8eyo?file=/src/styles.css

![image](https://user-images.githubusercontent.com/26835087/121791988-4562f680-cc22-11eb-9c21-7f5383cd4696.png)

**Comment by plainheart** [comment]
Thanks for the suggestion. The native Canvas API [`createConicGradient`](https://caniuse.com/mdn-api_canvasrenderingcontext2d_createconicgradient) has poor compatibility now, so it may not be so expected as a new feature currently.
