### ISSUE TITLE
There was an error following the code diagram of the example

### ISSUE THREAD

**Issue by wolf-leo** [apache/echarts#15147]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-stack](https://echarts.apache.org/examples/zh/editor.html?c=line-stack)

### Steps to reproduce
Sample address:
> https://echarts.apache.org/examples/zh/editor.html?c=line-stack
> 
> ![QQ截图20210615092004](https://user-images.githubusercontent.com/37436228/121978550-01efc000-cdbb-11eb-8882-1386055b8b31.jpg)
> 
> **_All normal_**
> 
> When I modify some of the data
> 
> **_There was a mistake_**
> 
> ![QQ截图20210615092300](https://user-images.githubusercontent.com/37436228/121978674-4c713c80-cdbb-11eb-9447-400f0452b3b3.jpg)

### What is expected?
The data is normal

### What is actually happening?
There was a mistake

**Comment by susiwen8** [comment]
That was not a mistake, because the chart is a stack chart.

**Comment by wolf-leo** [comment]
Sorry, my fault !!!
Just remove the stack attribute.
