### ISSUE TITLE
markLine 指定 name 无效

### ISSUE THREAD

**Issue by elewen** [apache/echarts#15156]
### Version
5.1.2

### Steps to reproduce

```javascript
series: [
  {
    type: 'line',
    data: [123, 321, 231, 213, 132, 312],
    markLine: {
        data: [
            {
                xAxis: '20210615',
                name: '<<<历史  未来>>>',
            }
        ],
    }
  }
]
```

### What is expected?
希望能够显示 '<<<历史  未来>>>'

### What is actually happening?
实际显示的是 '20210615'

**Comment by elewen** [comment]
> ### Version
> 5.1.2
> 
> ### Steps to reproduce
> ```js
> series: [
>   {
>     type: 'line',
>     data: [123, 321, 231, 213, 132, 312],
>     markLine: {
>         data: [
>             {
>                 xAxis: '20210615',
>                 name: '<<<历史  未来>>>',
>             }
>         ],
>     }
>   }
> ]
> ```
> 
> ### What is expected?
> 希望能够显示 '<<<历史 未来>>>'
> 
> ### What is actually happening?
> 实际显示的是 '20210615'

另一个问题是这种情况下无法隐藏终点的箭头,因为这条线是通过一个对象配置生成的, 而不是一个数组的两个对象生成的? 如果需要隐藏终点的箭头该如何配置?

**Comment by plainheart** [comment]
可以试试使用 [`label.formatter`](https://echarts.apache.org/zh/option.html#series-line.markLine.data.0.label.formatter)

**Comment by elewen** [comment]
> 可以试试使用 [`label.formatter`](https://echarts.apache.org/zh/option.html#series-line.markLine.data.0.label.formatter)

可以了, 谢谢. 但为什么有些情况下设置的 name 又是有效的, 比如两个坐标点之间的连线. 不知道这是不是bug, 我没找到官方文档对此差异的解释

**Comment by pissang** [comment]
@elewen 可以举个例子吗？

**Comment by dukeP** [comment]
@pissang [demo](https://codesandbox.io/s/temperature-change-in-the-coming-week-forked-tjlqym?file=/index.js:1107-1114) 目前(5.4.1)看起来这个问题还是存在，大部分情况下设置 name 属性都没有按预期生效
