### ISSUE TITLE
echarts 的 selectDataRange和dataRangeSelected

### ISSUE THREAD

**Issue by hatakes** [apache/echarts#15158]
### What problem does this feature solve?
有个地图轮播的需求,使用 selectDataRange可以选中多个地图,可以获取到这些选择label的name和value,甚至是坐标一类的信息吗?
当然最好还是在地图展示多个tooltip,现在最新的v5.x echarts可以实现多个tooltip吗?

### What does the proposed API look like?
selectDataRange

**Comment by pissang** [comment]
不支持 tooltip。想要实现选中的话可以用 [select](https://echarts.apache.org/zh/api.html#action.select)

**Comment by hatakes** [comment]
> 不支持 tooltip。想要实现选中的话可以用 [select](https://echarts.apache.org/zh/api.html#action.select)

地图可以用 selectDataRange,但是选中之后,没有办法和tooltip似的,进行联动,展示出来 区划名称和对应的value.

**Comment by hatakes** [comment]
> 不支持 tooltip。想要实现选中的话可以用 [select](https://echarts.apache.org/zh/api.html#action.select)

地图可以用 selectDataRange,但是选中之后,没有办法和tooltip似的,进行联动,展示出来 区划名称和对应的value.
