### ISSUE TITLE
柱状图希望增加增加一个功能，柱子的宽度可以根据度量来控制

### ISSUE THREAD

**Issue by lpali** [apache/echarts#15151]
### What problem does this feature solve?
当前highchart、tableau等开发组件和工具都能很好的支撑，希望echart能支持。echart当前实现的成本较高。

### What does the proposed API look like?
当前highchart、tableau等开发组件和工具都能很好的支撑，希望echart能支持。echart当前实现的成本较高。

**Comment by pissang** [comment]
具体描述下你的功能？

**Comment by lpali** [comment]
![image](https://user-images.githubusercontent.com/3455035/123547861-05a91c80-d795-11eb-80cf-b02d0c6216b6.png)

当前的 柱子的宽度不没个都是一样，希望不同的柱子有不同的宽度
