### ISSUE TITLE
The Percent parameter in the params of the formatter attribute of the Tooltip is expected to be more accurate.(期望tooltip的formatter属性的params中的percent参数精度更高)

### ISSUE THREAD

**Issue by clown-helang** [apache/echarts#15167]
### What problem does this feature solve?
The percent parameter in the params of the formatter property of the Tooltip is currently accurate to two decimal places and is expected to support up to six decimal places.Two decimals do not meet the difference between two values of a large situation to show the effect(tooltip的formatter属性的params中的percent参数目前的精确度是两位小数，期望可以支持最多6位小数。两位小数不满足两个值的差值很大的情况展示效果)

### What does the proposed API look like?
percentageAccuracy: 4     //This means "percent," keeping four decimal places （代表 percent 保留4位小数）

**Comment by plainheart** [comment]
文档可能有遗漏，可以通过 `series.pie.percentPrecision` 设置百分比精度，例如 `percentPrecision: 5`。

**Comment by clown-helang** [comment]
ok, thinks
