### ISSUE TITLE
series-line.itemStyle. borderWidth not work

### ISSUE THREAD

**Issue by xmasuhai** [apache/echarts#15168]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-line.itemStyle.borderWidth](https://echarts.apache.org/zh/option.html#series-line.itemStyle.borderWidth)

### Steps to reproduce
find series-line.itemStyle. borderWidth
click try it
set borderWidth 20 or other numbers, not work

### What is expected?
make the items look bigger

### What is actually happening?
still the same size(borderWidth not change)

---
series-line.itemStyle. borderWidth in version 4.x does work

**Comment by plainheart** [comment]
Maybe related to #14594. I remember the stroke width is always set to be `2` if the symbol is empty.
