### ISSUE TITLE
yAxis不指定min/max时，使用鼠标滚轮放大时，第一次放大的放大中心会错位

### ISSUE THREAD

**Issue by loadingwyn** [apache/echarts#15163]
### Version
4.9.0

### Reproduction link
[https://codesandbox.io/s/clever-proskuriakova-pmds2?file=/src/index.js](https://codesandbox.io/s/clever-proskuriakova-pmds2?file=/src/index.js)

### Steps to reproduce
使用滚轮放大

### What is expected?
以鼠标当前位置为放大中心

### What is actually happening?
鼠标的相对位置偏移
如图我鼠标放在第四个点（图上被放大的那个点），然后滚动鼠标滚轮，可以看到相对位置发生了变动，折线整体上移了
![image](https://user-images.githubusercontent.com/17921180/122162065-73a43880-cea5-11eb-877a-36076af65ac4.png)

![image](https://user-images.githubusercontent.com/17921180/122162136-9a626f00-cea5-11eb-8d7c-b41d27d7eae4.png)

**Comment by pissang** [comment]
没看出来有什么问题，滚动的时候坐标轴的范围改变了，折线相对于坐标轴的位置都是对的

**Comment by loadingwyn** [comment]
![image](https://user-images.githubusercontent.com/17921180/122374888-5353a700-cf95-11eb-9acb-a78c77d51cdb.png)
我重截图，我的鼠标在红色箭头位置，此时我滚动滚轮
![image](https://user-images.githubusercontent.com/17921180/122375169-8f870780-cf95-11eb-891b-262ec36e42ac.png)
你可以看到折线的位置上移了，你也可以以toolbox的位置作参考，很明显这第四个点距离toolbox变近了
@pissang
