### ISSUE TITLE
markLine 的线条无法设置使其显示在 serise 下方

### ISSUE THREAD

**Issue by elewen** [apache/echarts#15175]
### Version
5.1.2

### Steps to reproduce
给 markLine 所在的 series 设置了比其他serise更小的 z 值后, markLine 没有按照预期被其他具有更大的 z 值的 series 所覆盖

### What is expected?
期望通过某种方式让 markLine 显示在 serise 下面

### What is actually happening?
尝试给markLine所在的series设置更小的z值使markLine显示在底部却无法生效

**Comment by ssthouse** [comment]
@elewen Hi, 可以给个具体的例子吗，我这边试了下没有问题：

**option配置**

```javascript
option = {
  xAxis: {
    type: "category",
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  yAxis: {},
  series: [
      
      {
        data: [1820, 932, 901, 934, 1290, 1330, 11320],
        type: "line",
        markLine: {
          data: [{
            type: "average",
            lineStyle: {
                type: 'solid',
                width: 3,
            }
          }],
          silent: true
        }
      },
    {
        z:10,
        data: [20, 1932, 1901, 9314, 12190, 13310, 13120],
        type: "line",
        lineStyle: {
          width: 5,  
        },
        markLine: {
          data: [{
            type: "average",
            lineStyle: {
                type: 'solid',
                width: 3,
            }
          }],
          silent: true
        }
      }
  
  ]
}
```

**效果：**
绿色series（z为10），显示在蓝色series的markLine上方

![image](https://user-images.githubusercontent.com/10973821/122497984-ec7bcf80-d020-11eb-9d15-e2760fc500b3.png)

**Comment by elewen** [comment]
> @elewen Hi, 可以给个具体的例子吗，我这边试了下没有问题：
> 
> **option配置**
> 
> ```js
> option = {
>   xAxis: {
>     type: "category",
>     data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
>   },
>   yAxis: {},
>   series: [
>       
>       {
>         data: [1820, 932, 901, 934, 1290, 1330, 11320],
>         type: "line",
>         markLine: {
>           data: [{
>             type: "average",
>             lineStyle: {
>                 type: 'solid',
>                 width: 3,
>             }
>           }],
>           silent: true
>         }
>       },
>     {
>         z:10,
>         data: [20, 1932, 1901, 9314, 12190, 13310, 13120],
>         type: "line",
>         lineStyle: {
>           width: 5,  
>         },
>         markLine: {
>           data: [{
>             type: "average",
>             lineStyle: {
>                 type: 'solid',
>                 width: 3,
>             }
>           }],
>           silent: true
>         }
>       }
>   
>   ]
> }
> ```
> 
> **效果：**
> 绿色series（z为10），显示在蓝色series的markLine上方
> 
> ![image](https://user-images.githubusercontent.com/10973821/122497984-ec7bcf80-d020-11eb-9d15-e2760fc500b3.png)

感谢回复，根据你给出的配置经过测试后已解决了我的问题。

我总共有4个 serise，其中一个是markLine所在的 serise，另外三个series 是三条折线图。我又试了好几次，发现其他三个系列的z必须大于等于5、markline所在的 series 不设置z或者设置小于其他几个的z的时候才能成功覆盖；如果单独只给markline设置小于2的z值或者负数z值，而不给其他series指定z值，也无法实现覆盖。不知道这个覆盖逻辑是怎么规定和计算的，没找到相关说明。
