### ISSUE TITLE
how to block zoom when mousewheeling on treemap

### ISSUE THREAD

**Issue by SPH-0gJo** [apache/echarts#15177]
### Version
5.0.2

### Steps to reproduce
   let option = {
                dataZoom: {
                    start: 80,
                    type: "slider",
                    zoomOnMouseWheel: false
                  },
                tooltip: {
                    formatter:  ....
                    }
                },
                series: [{
                    type: 'treemap',
                    label: {
                        show: true,
                        formatter: '{b}'
                    },
                    upperLabel: {
                        show: true,
                        height: 30
                    },
                    itemStyle: {
                        borderColor: '#fff'
                    },
                    data: Object.values(chartData),
                    levels: getLevelOption()
                }]

            };
            e.setOption(option);

### What is expected?
when applying dataZoom.zoomOnMouseWheel = false, zoom event is not occur.

### What is actually happening?
It doesn't work and zoom still occur.

**Comment by 100pah** [comment]
`treemap.zoom: false`

**Comment by SPH-0gJo** [comment]
Thank you It's been resolved
