### ISSUE TITLE
echarts能提供仅清除series属性的接口吗

### ISSUE THREAD

**Issue by Sakura-gh** [apache/echarts#15179]
### What problem does this feature solve?
使用this.chartInstance.clear()或this.chartInstance.setOption(..., true)都会把原先所有的内容给清空，尤其是在使用百度地图时，由于bmap属性被清除，导致所有自定义样式也会一同消失。如果使用上述两种方法，需要重新加载过多的资源，导致刷新卡顿。目前的需求是仅仅清空原option中的series属性，而不用清除其他属性导致重复加载。

注：我尝试过replaceMerge方法，在没有设置series属性id的情况下，replaceMerge似乎并不能完整地删除原有的series：
~~~js
console.log(this.chartInstance.getOption())
this.chartInstance.setOption(dataOption, {replaceMerge: 'series'})
console.log(this.chartInstance.getOption())
~~~
console输出：
原先的series：
~~~
series: Array(2)
0: {name: "飞线", type: "lines", coordinateSystem: "bmap", symbol: Array(2), effect: {…}, …}
1: {name: "终点", type: "effectScatter", coordinateSystem: "bmap", rippleEffect: {…}, symbolSize: 10, …}
~~~
setOption之后的series：
~~~
series: Array(2)
0: {type: "effectScatter", coordinateSystem: "bmap", animation: true, symbol: "circle", symbolSize: 15, …}
1: {name: "终点", type: "effectScatter", coordinateSystem: "bmap", rippleEffect: {…}, symbolSize: 10, …}
~~~
新的series只包含0: {type: "effectScatter", coordinateSystem: "bmap", animation: true, symbol: "circle", symbolSize: 15, …}，显然这个结果是删除了原series中的0: {name: "飞线", type: "lines", coordinateSystem: "bmap", symbol: Array(2), effect: {…}, …}，却保留了不应该保留的1: {name: "终点", type: "effectScatter", coordinateSystem: "bmap", rippleEffect: {…}, symbolSize: 10, …}
### What does the proposed API look like?
chartInstance.clearSeries()

**Comment by 100pah** [comment]
@Sakura-gh echarts 版本是多少呢？

**Comment by Sakura-gh** [comment]
> @Sakura-gh echarts 版本是多少呢？
> 
> 以及， `setOption(dataOption, ...)` 的 `dataOption` 是什么内容。

我发现自己使用的是echarts4.9.0版本，好像并不支持replaceMerge参数，以上的情况应该是直接发生了merge和替换

**Comment by 100pah** [comment]
`v5` 后支持 replaceMerge ，能只清除 series 。
