### ISSUE TITLE
geo component set tooltip, but can‘t trigger.

### ISSUE THREAD

**Issue by Little-Star-Star** [apache/echarts#15170]
### Version
5.1.2

### Steps to reproduce
```ts
echart.setOption({
  geo: {
    map: "worldchina",
    tooltip: {
      show: true,
      trigger: "item",
      formatter: (params) => {
        console.log("formater", params);
        return "test";
      },
    },
  },
})
```
### What is expected?
when geo emphasis, tooltip can show.

### What is actually happening?
yes

---
if I set tooltip in global,  it can work.

**Comment by Little-Star-Star** [comment]
global tooltip using formatter can't work in v5.1.2, but it can work in v5.1.1

**Comment by 100pah** [comment]
@Little-Star-Star

**Comment by Little-Star-Star** [comment]
[test example](https://www.makeapie.com/editor.html?c=xT78-SQfYk )

I resolve this problem that both global tooltip and geo tooltip exisits.

If i only set geo tooltip, it can't work.

**Comment by 100pah** [comment]
When i comment as
```js
    // series: [
    //     {
    //         name: '万投比',
    //         type: 'map',
    //         geoIndex: 0,
    //         data: window.dataList,
    //     },
    // ],
```
in your text example above, the tooltip can show when hovering on map
