### ISSUE TITLE
【VisualMap】Support input custom value to set range values.

### ISSUE THREAD

**Issue by linwrui** [apache/echarts#15176]
### What problem does this feature solve?
Support input custom value to set range values.
![image](https://user-images.githubusercontent.com/22316156/122497989-ee459300-d020-11eb-91b0-8999eee80160.png)

### What does the proposed API look like?
{
   rangeController: "input"
}

**Comment by 100pah** [comment]
Could we know why this feature is needed?

**Comment by linwrui** [comment]
> Could we know why this feature is needed?

Swipe sometimes difficult to accurately slide to a certain value, but the input can facilitate the user to set the precise range
