### ISSUE TITLE
页面中多个图秒级刷新CPU飙升

### ISSUE THREAD

**Issue by PingFuLiu** [apache/echarts#15181]
### Version
4.9.0

### Steps to reproduce
在一个页面中设置多个折线图（其他图一样），折线图的数据是秒级更新的，每秒钟去setOption，这样使得CPU占用升高

### What is expected?
降低CPU的占用率

### What is actually happening?
CPU降低

---
有什么方法可以优化一下，降低CPU的占用率

**Comment by 100pah** [comment]
每个图的数量级是多少。
数据量级大的话可尝试  https://echarts.apache.org/en/option.html#series-line.sampling
