### ISSUE TITLE
Bar series overflow xAxis when using xAxis.scale = true with several series

### ISSUE THREAD

**Issue by deterralba** [apache/echarts#15189]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/9p4j6175/](https://jsfiddle.net/9p4j6175/)

### Steps to reproduce
```javascript
option = {
  "xAxis": {
    // min": 10,
    scale: true,
  },
  "yAxis": { },
  "series": [
    {
      "id": "F",
      "data": [
        [20,1],
        [35,2],
        [55,7],
    ],
      "type": "bar",
    },
    {
      "id": "M",
      "data": [
        [20,1],
        [35,2],
        [55,7],
      ],
      "type": "bar",
    }
  ]
}
```

### What is expected?
The bars are not going at the left side of the xAxis for the lowest value.
We could add a option to add "extra security margins", `scale: {margin: '10%'}` could be a solution.
![image](https://user-images.githubusercontent.com/10196648/122579448-367ea880-d055-11eb-9230-4b337a2a5e19.png)

### What is actually happening?
The bars are on the left side of the xAxis for the lowest value.
![image](https://user-images.githubusercontent.com/10196648/122579364-2070e800-d055-11eb-8ca9-c7016af0bb85.png)

**Comment by 100pah** [comment]
Does [boundaryGap](https://echarts.apache.org/en/option.html#xAxis.boundaryGap) help?

**Comment by helgasoft** [comment]
@100pah - no, boundaryGap does not help. 
Looks like bug is related to *number of bars*.  **Four or less bars** with ```scale:true``` will overflow Xaxis.  More than four will display correctly.
```js
option = {
  "xAxis": {"scale": true},
  "yAxis": {},
  "series": [ { "type": "bar" } ],
  "dataset": [{
      "source": [
        ["x", "y"],
        [  25000, 4  ],
        [  35000, 14 ],
        [  45000, 10 ],
        [  55000, 4  ],
//        [  66000, 1  ]   // un-comment to see difference
      ]
    }]
}
```

**Comment by dimer47** [comment]
I had the same problem, thank you very much @helgasoft ! 
The xAxis `scale:true` option works perfectly.
