### ISSUE TITLE
chart.setOption(option, {replaceMerge: String})的bug

### ISSUE THREAD

**Issue by Sakura-gh** [apache/echarts#15186]
### Version
4.9.0

### Steps to reproduce
设置两个option，其中option1的series数组包含2个对象，而option2的series数组包含1个对象
- option1.series = [{name: 'test1-1', ...}, {name: 'test1-2', ...}]
- option2.series = [{name: 'test2', ...}] 
原先chart.setOption(option1) 
=> 
修改为chart.setOption(option2, {replaceMerge: 'series'})

### What is expected?
由于没有给series设置id，预期结果是option1的series对象被删除，从而替换为option2的series对象，即：
chart.getOption().series：
[{name: 'test1-1', ...}, {name: 'test1-2', ...}] => [{name: 'test2', ...}] 

### What is actually happening?
但实际上仅删除了原先series数组中的第一个对象，第二个对象依然存在，导致这一部分的数据依旧会显示在图表上，即：
chart.getOption().series：
[{name: 'test1-1', ...}, {name: 'test1-2', ...}] => [{name: 'test2', ...}, {name: 'test1-2', ...}] 

---
看上去这个删除策略会在新series数组元素少于旧series数组元素时会出错，旧series部分数组元素依旧会残留。

**Comment by ssthouse** [comment]
@Sakura-gh 这个问题在最新版本没有出现，应该已经被修复了，可以在这个页面试试:

https://echarts.apache.org/examples/zh/editor.html?c=line-simple

**Comment by Sakura-gh** [comment]
> @Sakura-gh 这个问题在最新版本没有出现，应该已经被修复了，可以在这个页面试试:
> 
> https://echarts.apache.org/examples/zh/editor.html?c=line-simple

ok，新版本已经没有这个问题了
