### ISSUE TITLE
折线图 多次setoption后 鼠标hover悬停位置的tooltip无法实时更新数据

### ISSUE THREAD

**Issue by afanso** [apache/echarts#15188]
### Version
5.1.1

### Steps to reproduce
```js
tooltip: {
          trigger: "axis",
          formatter(params) {
            let cumulative = "0";
            if (params[0].value[1] >= 1000000000) {
              cumulative = (params[0].value[1] / 1000000000).toFixed(2)   "B";
            } else if (params[0].value[1] >= 1000000) {
              cumulative = (params[0].value[1] / 1000000).toFixed(2)   "M";
            } else if (params[0].value[1] >= 1000) {
              cumulative = (params[0].value[1] / 1000).toFixed(2)   "K";
            } else {
              cumulative = parseFloat(params[0].value[1]).toFixed(2)   "";
            }
            let text = `委托价<br />${params[0].value[0]}<br />累计<br />${cumulative}`;
            return text;
          },
```
### What is expected?
应该在setoption后，tooltip应能实时更新对应位置的数据

### What is actually happening?
无法更新，只显示在第一次选中的数据

**Comment by afanso** [comment]
this.$refs.echart.setOption(this.options, true, true); 如此调用的话，tooltip会消失，而我这里SET频率很高，1秒不到就消失

**Comment by ssthouse** [comment]
@afanso Hello, 可以帮忙看看这个PR里的动图是你想要的效果吗~
https://github.com/apache/echarts/pull/15194

**Comment by afanso** [comment]
@ssthouse 效果非常接近，有没有代码让我学习一下

**Comment by ssthouse** [comment]
@afanso 对echart的修改在这里： https://github.com/apache/echarts/pull/15194/files

使用的话要等代码merge进echart主分支发版哦

**Comment by afanso** [comment]
@ssthouse  我看你的ECHARTS的X轴是以GATE为分类的，我这里是需要用VALUE的，效果能达到吗？

**Comment by ssthouse** [comment]
@afanso 应该是可以的。导致tooltip没有更新的原因是tooltip在判断是否要更新的时候只比较了展示数据的size，没有比较具体的value；
坐标轴的category应该没有影响；
