### ISSUE TITLE
is there any option for specifiyng starting and ending value for bin in echarts

### ISSUE THREAD

**Issue by balajkhan07** [apache/echarts#15213]
### Version
4.4.0

### Steps to reproduce
I have attached the link to my StackOverflow question:
https://stackoverflow.com/questions/68096929/is-there-any-option-for-specifiyng-starting-and-ending-value-for-bin-in-echarts

### What is expected?
I want to provide starting and ending values for the bin.

### What is actually happening?
Bin does not respond to actual ranges

**Comment by 100pah** [comment]
The tooltip shows the axis value corresponding to the mouse point.

**Comment by balajkhan07** [comment]
@100pah I know that tooltip shows the correct value but can I specify that a bar should start from a specific value like 1 and end at 2?
