### ISSUE TITLE
使用树状图tree 的setOptions更新数据后 出现了残留的线图

### ISSUE THREAD

**Issue by DtStorm** [apache/echarts#15217]
### Version
5.1.2

### Steps to reproduce
const op = this.chart?.getOption()
        if (op.series) {
          op.series[0].data = [newData]
        }
        // console.log(newData, this.testData.children[9])
        this.chart.setOption(op, true)

### What is expected?
不会出现残留的线

### What is actually happening?
出现了残留的线
![image](https://user-images.githubusercontent.com/56500428/123074763-2fd3a500-d44a-11eb-8d2c-9ec7e4e82266.png)

**Comment by ssthouse** [comment]
@DtStorm 可以创建一个复现的demo吗，我这边试下来没有复现：

https://echarts.apache.org/examples/zh/editor.html?c=tree-basic

```javascript
myChart.showLoading();
$.get(ROOT_PATH + '/data/asset/data/flare.json', function (data) {
    myChart.hideLoading();

    data.children.forEach(function (datum, index) {
        index % 2 === 0 && (datum.collapsed = true);
    });
    
    const option = {
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'tree',

                data: [data],

                top: '1%',
                left: '7%',
                bottom: '1%',
                right: '20%',

                symbolSize: 7,

                label: {
                    position: 'left',
                    verticalAlign: 'middle',
                    align: 'right',
                    fontSize: 9
                },

                leaves: {
                    label: {
                        position: 'right',
                        verticalAlign: 'middle',
                        align: 'left'
                    }
                },

                emphasis: {
                    focus: 'descendant'
                },

                expandAndCollapse: true,
                animationDuration: 550,
                animationDurationUpdate: 750
            }
        ]
    };
    
    

    myChart.setOption(option);
    
    setTimeout(function() {
        
        const data = option.series[0].data[0];
        data.children.splice(0, 5);
        myChart.setOption(option, true)
    }, 2000);
});
```

**Comment by DtStorm** [comment]
我把下面的测试代码修改了一下 复现了
myChart.showLoading();
$.get(ROOT_PATH + '/data/asset/data/flare.json', function (data) {
    myChart.hideLoading();

    data.children.forEach(function (datum, index) {
        index % 2 === 0 && (datum.collapsed = true);
    });

    myChart.setOption(option = {
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'tree',

                data: [data],

                top: '1%',
                left: '7%',
                bottom: '1%',
                right: '20%',

                symbolSize: 7,

                label: {
                    position: 'left',
                    verticalAlign: 'middle',
                    align: 'right',
                    fontSize: 9
                },

                leaves: {
                    label: {
                        position: 'right',
                        verticalAlign: 'middle',
                        align: 'left'
                    }
                },

                emphasis: {
                    focus: 'descendant'
                },

                expandAndCollapse: true,
                animationDuration: 550,
                animationDurationUpdate: 750
            }
        ]
    });
    
    setTimeout(function() {
        
             const op = myChart.getOption()
        const data = option.series[0].data[0].children[1]
        op.series[0].data = [data]
        myChart.setOption(op,true)
    }
    , 2000);
});

![image](https://user-images.githubusercontent.com/56500428/123101206-615a6980-d466-11eb-9f5b-094376b3efde.png)

**Comment by DtStorm** [comment]
树状图也一样
![image](https://user-images.githubusercontent.com/56500428/123101681-e2b1fc00-d466-11eb-890d-cdc6874cfd7d.png)
