### ISSUE TITLE
IOS 多次横竖屏切换echart时，报错TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')，导致图表无法渲染

### ISSUE THREAD

**Issue by f1liu** [apache/echarts#15229]
Version
5.1.1

1、切换页面时，使用过dispose方法并且置空
2、横竖屏切换多次操作后必现报错，TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')

严重使用：
this.$echarts.init(document.getElementById("chart"), null, { renderer: 'svg' }) 可以解决问题

请关注解决问题

类似issues：
https://github.com/apache/echarts/issues/11615

**Comment by sphenginx** [comment]
> Version 5.1.1
> 
> 1、切换页面时，使用过dispose方法并且置空 2、横竖屏切换多次操作后必现报错，TypeError:null is not an object(evaluating 'this.ctx.dpr=this.dpr')
> 
> 严重使用： this.$echarts.init(document.getElementById("chart"), null, { renderer: 'svg' }) 可以解决问题
> 
> 请关注解决问题
> 
> 类似issues： #11615

Version 5.1.1 可以这么使用，version 4.9.2 有解决方案么？
