### ISSUE TITLE
当xAxis的type为time时，使用dataset且dataset中存在null值,存在多个series，会导致生成图形中null值的线条也出现

### ISSUE THREAD

**Issue by Lee324** [apache/echarts#15227]
![K EM(B`BYHKE6PG1}`V(OK3](https://user-images.githubusercontent.com/22317901/123233645-cd8fa880-d50c-11eb-9e36-2efce3fa770f.png)
![T_7R4YDNVIXSB KC$T0H@N6](https://user-images.githubusercontent.com/22317901/123233652-cec0d580-d50c-11eb-985f-53f9a87ffce1.png)
### Version
5.1.2

### Steps to reproduce
option = {
    xAxis: {
        type:'time'
    },
    legend:{
        show:true
    },
    tooltip:{
        show:true
    },
    dataset:{
        source:[
         ['time','a','b','c'],
        ['2021-06-23 08:31:40',0.7,null,null],
        ['2021-06-23 09:31:40',0.8,null,null]
        ]
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        name:'a',
        type: 'line'
    },{
        name:'b',
        type: 'line'
    },{
        name:'c',
        type: 'line'
    }]
};

### What is expected?
仅出现有值的线条，null的线条不显示

### What is actually happening?
数据为null的生成了与有数据的重叠线条

**Comment by 100pah** [comment]
I am afraid I can not understand your requirement. Could we have more clear description ?

**Comment by Lee324** [comment]
> 恐怕我无法理解您的要求。我们可以有更清楚的描述吗？

把我的option拷贝到echarts官网的demo中就可以生成我上传的图片显示的图形，我开放了legend属性，由图可知,name为c的se'ries在数据集dataset中为null值，但实际生成图形中生成了一条和a一模一样的线条。如果不使用数据集则没有这个问题。
![1](https://user-images.githubusercontent.com/22317901/123356057-88fe1e80-d599-11eb-8c21-687497b9b4c2.png)
![2 1](https://user-images.githubusercontent.com/22317901/123356061-8a2f4b80-d599-11eb-823e-0a7d0cc139e3.png)

**Comment by 100pah** [comment]
Please use `encode` to specify the exact dimension each series uses.
Otherwise echarts just guess that.

```js
option = {
    xAxis: {
        type:'time'
    },
    legend:{
        show:true
    },
    tooltip:{
        show:true
    },
    dataset:{
        source:[
         ['time','a','b','c'],
        ['2021-06-23 08:31:40',0.7,null,null],
        ['2021-06-23 09:31:40',0.8,null,null]
        ]
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        type: 'line',
        encode: {
            x: 'time',
            y: 'a',
            seriesName: 'a'
        }
    },{
        type: 'line',
        encode: {
            x: 'time',
            y: 'b',
            seriesName: 'b'
        }
    },{
        type: 'line',
        encode: {
            x: 'time',
            y: 'c',
            seriesName: 'c'
        }
    }]
};
```

**Comment by Lee324** [comment]
> 请用于`encode`指定每个系列使用的确切尺寸。
> 否则echarts只是猜测。
> 
> ```js
> option  =  { 
>     xAxis : { 
>         type : 'time' 
>     } , 
>     Legend : { 
>         show : true 
>     } , 
>     tooltip : { 
>         show : true 
>     } , 
>     dataset : { 
>         source : [ 
>          [ 'time' , 'a' , 'b' , 'c ' ] , 
>         [ '2021-06-23 08:31:40' , 0.7 , null , null ] , 
>         ['2021-06-23 09:31:40' , 0.8 , null , null ] 
>         ] 
>     } , 
>     yAxis : { 
>         type : 'value' 
>     } , 
>     series : [ { 
>         type : 'line' , 
>         encode : { 
>             x : 'time' , 
>             y : 'a' , 
>             seriesName : 'a' 
>         } 
>     } , { 
>         type : 'line' , 
>         encode : { 
>             x :'time' , 
>             y : 'b' , 
>             seriesName : 'b' 
>         } 
>     } , { 
>         type : 'line' , 
>         encode : { 
>             x : 'time' , 
>             y : 'c' , 
>             seriesName : 'c' 
>         } 
>     } ] 
> } ;
> ```

是的，最终我也是通过给每个series单独给值解决此问题的，但是这并不代表数据集dataset对null的使用没有问题。

**Comment by Lee324** [comment]
是的，最终我也是通过给每个series单独给值解决此问题的，但是这并不代表数据集dataset对null的使用没有问题。
