### ISSUE TITLE
Support for adding images programmatically and improvement to the formatter function

### ISSUE THREAD

**Issue by bhumishah-icsynergy** [apache/echarts#15220]
### What problem does this feature solve?
I'm trying to implement tree chart with formatter function and rich APIs. We are echarts using ngx-echarts v4.1.0 as a angular wrapper of echarts version 4.1.0. I've attached simple js implementation here to simplify the process. 

I asked to add following features,
1. add images programmatically
2. add details view hanging off from the custom label node 
https://icsynergy-my.sharepoint.com/:i:/p/bhumi_shah/EbYiUHMjz-ZNrRi32kYku5YB77gkg4D4-T8NiXYzzsYStA?e=XqALxe

For adding images programmatically on the label, 
I have searched a lot but I could't find any way to add image on the label dynamically. 
Only way I was able to add images was by using rich API's backgroundColor.image property. But it doesn't provide a way to add icons programmatically. 
Can you please let me know if there's a way for adding images dynamically? 

For adding details view hanging off from the label (or relative to the label),
It is more like a custom requirement, so I just wanted to know does echarts have ability to add elements relative to the label it self? If yes can you guys please share how it can be achieved? 
Note: we don't need tooltip here. 

Check the mock implementation of the chart here. https://codepen.io/bhumishah-icsynergy/pen/ExWBKzW

Thank you!

### What does the proposed API look like?
Maybe allowing to use html in the label so user can customized labels as per users own needs.

**Comment by 100pah** [comment]
This [demo](https://echarts.apache.org/examples/en/editor.html?c=pie-rich-text) show the icon and details using rich text.
Does this help?

**Comment by bhumishah-icsynergy** [comment]
Hi @100pah, I've used exactly same example for reference. Actually with this example I can't find a way to assign icons dynamically. And regarding details with rich text. I'm already using rich text for the labels. Now I need another details view hanging off from the label it self. Please check attached image [here](https://icsynergy-my.sharepoint.com/personal/bhumi_shah_icsynergy_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fbhumi%5Fshah%5Ficsynergy%5Fcom%2FDocuments%2FSelection%5F815%2Epng&parent=%2Fpersonal%2Fbhumi%5Fshah%5Ficsynergy%5Fcom%2FDocuments&originalPath=aHR0cHM6Ly9pY3N5bmVyZ3ktbXkuc2hhcmVwb2ludC5jb20vOmk6L3AvYmh1bWlfc2hhaC9FYllpVUhNanotWk5yUmkzMmtZa3U1WUI3N2drZzRENC1UOE5pWFl6enNZU3RBP3J0aW1lPTRLUF9ySnczMlVn)

**Comment by dancerphil** [comment]
Same Issue

**Comment by aloybach** [comment]
Hi,
I experienced the same thing in:  backgroundcolor { image: function (value) { return value} }
Why function can't read yAxis "value" ?
Even though the function works as it should in
itemStyle: {
color: function(c) returncountryColors[c.value[0]] || '#5470c6';}
},
Is this a bug or is it  " backgroundcolor {image: } " can not be used for dynamic variables ?

Best Regards,

---
Below are a part of my script of "bar race" :

yAxis: [{
  inverse: true,
  type: 'category',
  max: 14,
  axisLabel: {
     show: true,
     textStyle: {fontSize: 14},					
     formatter: function(value){return '{yaxPLabel|'+value+'}{yaxPSymbol|}';}, 
     rich: {
        yaxPLabel: {
           align: 'left',
           padding: [0, 10, 0, 0]
	},
	yaxPSymbol: {
	   height: 15, width: 10,
	   align: 'right', padding: 5,
	   backgroundColor: {
	      image: function(value){return provinceSymbols[value.toString] || provinceSymbols['Texas'];}
	   }
	}
     }
   },					
   animationDurationUpdate: axisDurationUpdate,
   animationEasingUpdate: 'linear'
}],
