### ISSUE TITLE
How to remove console warnings：Instance ec_xxxxxxxx has been disposed

### ISSUE THREAD

**Issue by Horzen** [apache/echarts#15226]
### Version
5.0.2

### Steps to reproduce
When i use the function of dispose,a large number of warning messages appear on the Console:Instance ec_xxxxxx has been disposed.How can i remove these warnings?

### What is expected?
No warnings when i use dispose function

### What is actually happening?
There are a lot of warnings

**Comment by pissang** [comment]
@Horzen This warn will be removed in the production environment.

**Comment by Horzen** [comment]
thx！
