### ISSUE TITLE
Echarts issue with custom rectangle and textContent options

### ISSUE THREAD

**Issue by deepa-ramadoss-tfs** [apache/echarts#15234]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/quirky-rgb-7fp9v?file=/src/app/](https://codesandbox.io/s/quirky-rgb-7fp9v?file=/src/app/)

### Steps to reproduce
Right below the plot, we have many rectangles. I have used the textContent property to display text within those rectangles. 

However, the text content of one rectangle overlaps with the text content of the other rectangle. I tried to set the  z2 property but that works only when the data size is less. 

### What is expected?
textContent of one rectangle shouldn't overlap on the textContent of the other rectangle even when handling large data.

### What is actually happening?
textContent of one rectangle overlaps on the textContent of the other rectangle when handling large data.

**Comment by 100pah** [comment]
When handling large data, there is no enough space to display all of the labels. So what is the expected effect?

**Comment by deepa-ramadoss-tfs** [comment]
We do have enough space to display the data. However, the labels are represented in the form of rectangles using 'custom' series option in echarts. Some texts are present inside each of these rectangles using 'textContent' attribute.

So, when we have overlapping rectangles, then the text content of one rectangle is overlapping on the other rectangle. 

I have attached the screenshot for your reference.
<img width="1379" alt="Screenshot 2021-06-28 at 11 02 39 AM" src="https://user-images.githubusercontent.com/58583783/123585195-5f92fc00-d800-11eb-8d9e-8a6db1011d8f.png">
