### ISSUE TITLE
Symbols on lines do not appear when rendering an svg chart in Node.js

### ISSUE THREAD

**Issue by mbork** [apache/echarts#15230]
### Version
5.1.2

### Reproduction link
[https://gist.github.com/mbork/1634016c611eae899163ed983aca5a3e](https://gist.github.com/mbork/1634016c611eae899163ed983aca5a3e)

### Steps to reproduce
Create a directory, copy the two files from the gist to that directory and run `npm install`. Then run `node echarts-backend-test.js > ebt.svg` and open the resulting svg file. Note: I used (slightly modified) code from [this gist](https://gist.github.com/pissang/4c32ee30e35c91336af72b129a1a4a73#file-echarts-svg-js-L21) to run Echarts in Node.js.

### What is expected?
The line should have two filled circles at both ends.

### What is actually happening?
The line has no circles at the ends.

---
If I copy a minimal/tutorial example of using Echarts in the browser from the official website and paste my `options` object there, the circles do appear, in both the canvas and svg renderers. A manual diff of the resulting svgs (one taken from the Node.js script and the other from the browser's devtools) shows two differences: one in fonts (this is also strange, though less worrying for me) and one in the `<path d="M 1 0 A 1 1 0 1 1 1 -0.0001" fill="#5470c6" fill-opacity="1" stroke="none" transform="matrix(2,0,0,2,180,303)"` part (the Node.js-generated one has `<path d="M 1 0 A 1 1 0 1 1 1 -0.0001" fill="#5470c6" fill-opacity="1" stroke="none" transform="matrix(0,0,0,0,180,303)"` instead – notice the zeros instead of the 2's).

**Comment by 100pah** [comment]
set 
```js
var option = {
    animation: false,
    // ...
};
```
please.

**Comment by mbork** [comment]
Thanks, that worked! Is it documented anywhere?

**Comment by 100pah** [comment]
Added to doc just now~
