### ISSUE TITLE
树图（径向树状图）可以在节点的连线上增加文字吗，并且连线可以增加箭头吗

### ISSUE THREAD

**Issue by DtStorm** [apache/echarts#15232]
### What problem does this feature solve?
树图连线支持在线上显示文字，连线增加箭头

### What does the proposed API look like?
关于连线显示label:比如在数据里可以增加一个关联值 relationship
children: [
          {
            id: 1001,
            name: 'analytics',
            children: [
              {
                id: 1002,
                name: 'graph',
                relationship:2,
}
]
关于箭头：例如可以在series里加个属性配置是否显示箭头，showArrow
 series: [
          {
            type: 'tree',
            showArrow:true,
            data: [this.testData],
            top: '18%',
            bottom: '14%',
]

**Comment by DtStorm** [comment]
![image](https://user-images.githubusercontent.com/56500428/123358512-307d5000-d59e-11eb-9717-17a24b4ac9f3.png)

**Comment by DtStorm** [comment]
像这样
![image](https://user-images.githubusercontent.com/56500428/123358928-efd20680-d59e-11eb-83f7-a7748081917e.png)

**Comment by wuliupo** [comment]
+1

**Comment by facenano** [comment]
可以

Pauli ***@***.***> 于2022年2月28日周一 16:32写道：

**Comment by YooHannah** [comment]
this question has been solved?  have any plan for it?
