### ISSUE TITLE
Time axis ticks are divided wrongly in miliseconds

### ISSUE THREAD

**Issue by ethannguyen276** [apache/echarts#15240]
### Version
5.1.1

### Steps to reproduce
Create an option with time axis, specify full date-time template:
```
option = {
    xAxis: {
        type: 'time',
        min: "2019-01-29T16:00:00 07:00",
        max: "2019-01-29T16:03:00 07:00",
        axisLabel: {
            rotate: 70,
            formatter: '{hh}:{mm}:{ss} {SSS}\n{dd}-{MM}-{yyyy}'
        }
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line'
    }]
};
```

### What is expected?
The distances between ticks should be the same.

### What is actually happening?
The milliseconds are not divided correctly between the ticks. Seem like Echarts uses 60 at maximum number of milliseconds (it should be 999)

**Comment by 100pah** [comment]
Please provide x value in `series.data`, for example;

```js
series: {
    data: [
        ['2019-01-29T16:00:00 07:00', 150], 
        ['2019-01-29T16:00:30 07:00', 230],
        ...
}
```

**Comment by ethannguyen276** [comment]
> Please provide x value in `series.data`, for example;
> 
> ```js
> series: {
>     data: [
>         ['2019-01-29T16:00:00 07:00', 150], 
>         ['2019-01-29T16:00:30 07:00', 230],
>         ...
> }
> ```

I used this new options object:
```
option = {
   xAxis: {
        type: 'time',
        min: "2019-01-29T16:00:00.000Z",
        max: "2019-01-29T16:03:00.000Z",
        axisLabel: {
            rotate: 70,
            formatter: '{hh}:{mm}:{ss} {SSS}\n{dd}-{MM}-{yyyy}'
        }
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [
                ['2019-01-29T16:00:00.599Z', 150], 
                ['2019-01-29T16:01:30.399Z', 230],
                ['2019-01-29T16:03:00.000Z', 100],
            ],
        type: 'line'
    }]
};
```
The issue still happens:

![image](https://user-images.githubusercontent.com/61503221/123576646-9e26b780-d7fc-11eb-912c-b0000c6fee1c.png)
