### ISSUE TITLE
resize error

### ISSUE THREAD

**Issue by newplum** [apache/echarts#15253]
### Version
5.1.2

### Steps to reproduce
1. vue 3.0
2. onMounted(() => {
window.addEventListener('resize', () => {
echarts.resize()
})
})
3. change window's  width

### What is expected?
echarts to resize on window resize

### What is actually happening?
error: resize` should not be called during main process

### example link
https://codesandbox.io/s/quizzical-mahavira-3gvst?file=/src/App.vue

**Comment by plainheart** [comment]
Instead of `ref`, please try to use `shallowRef` to contain the echarts instance.

**Comment by newplum** [comment]
> Instead of `ref`, please try to use `shallowRef` to contain the echarts instance.
thanks, the problem has been solved, but I dont't know why use `shallowRef` to contain the echarts instance. why  its value can't be  reactive.

**Comment by plainheart** [comment]
Some developers reported similar issues before, but the reason is still unconfirmed. I suppose it's because Vue 3 is using `Proxy`, which may affect the access to the inner model of ECharts.

**Comment by pissang** [comment]
For performance reasons. Any third-party instances, not only echarts, should not use `ref` in vue3. There is no reason to deep watch the properties inside a third-party instance.
