### ISSUE TITLE
is there any possibility to export these awesome charts to pdf, excel, csv, html

### ISSUE THREAD

**Issue by swiftinitdotcom** [apache/echarts#15250]
### Version
5.1.2

### Steps to reproduce
is there any possibility to export these awesome charts to pdf, excel, csv, html

### What is expected?
is there any possibility to export these awesome charts to pdf, excel, csv, html

### What is actually happening?
is there any possibility to export these awesome charts to pdf, excel, csv, html

---
is there any possibility to export these awesome charts to pdf, excel, csv, html

**Comment by plainheart** [comment]
@swiftinitdotcom Hi, you could export Base64 Data URI through ECharts API [`getDataURL`](https://echarts.apache.org/en/api.html#echartsInstance.getDataURL) and then convert it to the formats you want by third-party libraries or manually.

**Comment by huzafa-arshad-joulea** [comment]
Is there any update or anyone can give the running code of the downloaded image as a pdf ?
