### ISSUE TITLE
selectedMode= single is bug

### ISSUE THREAD

**Issue by pengxiaotian** [apache/echarts#15260]
### Version
5.1.2

### Reproduction link
[https://www.makeapie.com/editor.html?c=xrOoqVZGuf&v=8](https://www.makeapie.com/editor.html?c=xrOoqVZGuf&v=8)

### Steps to reproduce
click red point

### What is expected?
select a point

### What is actually happening?
select a line

**Comment by pengxiaotian** [comment]
I simulated an effect with `dispatchAction({type: 'highlight'})`

: https://www.makeapie.com/editor.html?c=xrOoqVZGuf&v=9

**Comment by pissang** [comment]
Yeah, it's a known issue. The reason is that data on the category axis will be assigned the category as its name. And data with the same name will be selected together. 

Currently the solution is give each data a unique name:
```ts
let uniqueId = ''
map[key].push({
          name: 'id_' + uniqueId++,
          value: [i, keys.length - 1 - j, f ? f.statistic : 0]
         });
```

**Comment by pengxiaotian** [comment]
thks.😄
