### ISSUE TITLE
vue中使用堆叠柱状图：formatter函数中过去不到this,如何获取stack的值

### ISSUE THREAD

**Issue by whp1991** [apache/echarts#15268]
### What problem does this feature solve?
在tooltip的formatter函数中能够获取stack的值，根据stack的值，只显示当前stack的信息，现有功能只能显示所有信息

### What does the proposed API look like?
在formatter(params)的参数中添加stack的属性及其值

**Comment by SnailSword** [comment]
```javescript
var xAxisData = [];
var data1 = [];
var data2 = [];
var data3 = [];
var data4 = [];

for (var i = 0; i < 10; i++) {
    xAxisData.push('Class' + i);
    data1.push((Math.random() * 2).toFixed(2));
    data2.push((Math.random() * 5).toFixed(2));
    data3.push((Math.random() + 0.3).toFixed(2));
    data4.push(Math.random().toFixed(2));
}

var emphasisStyle = {
    itemStyle: {
        shadowBlur: 10,
        shadowColor: 'rgba(0,0,0,0.3)'
    }
};

var getStackByName = (name) => {
    return name.split('-')[0];
}

option = {
    brush: {
        toolbox: ['rect', 'polygon', 'lineX', 'lineY', 'keep', 'clear'],
        xAxisIndex: 0
    },
    toolbox: {
        feature: {
            magicType: {
                type: ['stack', 'tiled']
            },
            dataView: {}
        }
    },
    tooltip: {
        formatter: ({ seriesName, value }) => {
            return getStackByName(seriesName)  + ':' + value;
        },
    },
    xAxis: {
        data: xAxisData,
        name: 'X Axis',
        axisLine: {onZero: true},
        splitLine: {show: false},
        splitArea: {show: false}
    },
    yAxis: {},
    grid: {
        bottom: 100
    },
    series: [
        {
            name: 's1-1',
            type: 'bar',
            stack: getStackByName('s1-1'),
            emphasis: emphasisStyle,
            data: data1
        },
        {
            name: 's1-2',
            type: 'bar',
            stack: getStackByName('s1-2'),
            emphasis: emphasisStyle,
            data: data2
        },
        {
            name: 's2-1',
            type: 'bar',
            stack: getStackByName('s2-1'),
            emphasis: emphasisStyle,
            data: data3
        },
        {
            name: 's2-2',
            type: 'bar',
            stack: getStackByName('s2-2'),
            emphasis: emphasisStyle,
            data: data4
        }
    ]
};

myChart.on('brushSelected', renderBrushed);

function renderBrushed(params) {
    var brushed = [];
    var brushComponent = params.batch[0];

    for (var sIdx = 0; sIdx < brushComponent.selected.length; sIdx++) {
        var rawIndices = brushComponent.selected[sIdx].dataIndex;
        brushed.push('[Series ' + sIdx + '] ' + rawIndices.join(', '));
    }

    myChart.setOption({
        title: {
            backgroundColor: '#333',
            text: 'SELECTED DATA INDICES: \n' + brushed.join('\n'),
            bottom: 0,
            right:'10%',
            width: 100,
            textStyle: {
                fontSize: 12,
                color: '#fff'
            }
        }
    });
}
```

可以像上面的`getStackByName`函数做的那样，用一个函数或映射，把`stack`信息和`seriesName`或其他属性关联起来。

You can try to associate stack information with seriesName or other attributes by a map or a getter function, as what `getStackByName` function does above.

**Comment by whp1991** [comment]
> ```
> var xAxisData = [];
> var data1 = [];
> var data2 = [];
> var data3 = [];
> var data4 = [];
> 
> for (var i = 0; i < 10; i++) {
>     xAxisData.push('Class' + i);
>     data1.push((Math.random() * 2).toFixed(2));
>     data2.push((Math.random() * 5).toFixed(2));
>     data3.push((Math.random() + 0.3).toFixed(2));
>     data4.push(Math.random().toFixed(2));
> }
> 
> var emphasisStyle = {
>     itemStyle: {
>         shadowBlur: 10,
>         shadowColor: 'rgba(0,0,0,0.3)'
>     }
> };
> 
> var getStackByName = (name) => {
>     return name.split('-')[0];
> }
> 
> option = {
>     brush: {
>         toolbox: ['rect', 'polygon', 'lineX', 'lineY', 'keep', 'clear'],
>         xAxisIndex: 0
>     },
>     toolbox: {
>         feature: {
>             magicType: {
>                 type: ['stack', 'tiled']
>             },
>             dataView: {}
>         }
>     },
>     tooltip: {
>         formatter: ({ seriesName, value }) => {
>             return getStackByName(seriesName)  + ':' + value;
>         },
>     },
>     xAxis: {
>         data: xAxisData,
>         name: 'X Axis',
>         axisLine: {onZero: true},
>         splitLine: {show: false},
>         splitArea: {show: false}
>     },
>     yAxis: {},
>     grid: {
>         bottom: 100
>     },
>     series: [
>         {
>             name: 's1-1',
>             type: 'bar',
>             stack: getStackByName('s1-1'),
>             emphasis: emphasisStyle,
>             data: data1
>         },
>         {
>             name: 's1-2',
>             type: 'bar',
>             stack: getStackByName('s1-2'),
>             emphasis: emphasisStyle,
>             data: data2
>         },
>         {
>             name: 's2-1',
>             type: 'bar',
>             stack: getStackByName('s2-1'),
>             emphasis: emphasisStyle,
>             data: data3
>         },
>         {
>             name: 's2-2',
>             type: 'bar',
>             stack: getStackByName('s2-2'),
>             emphasis: emphasisStyle,
>             data: data4
>         }
>     ]
> };
> 
> myChart.on('brushSelected', renderBrushed);
> 
> function renderBrushed(params) {
>     var brushed = [];
>     var brushComponent = params.batch[0];
> 
>     for (var sIdx = 0; sIdx < brushComponent.selected.length; sIdx++) {
>         var rawIndices = brushComponent.selected[sIdx].dataIndex;
>         brushed.push('[Series ' + sIdx + '] ' + rawIndices.join(', '));
>     }
> 
>     myChart.setOption({
>         title: {
>             backgroundColor: '#333',
>             text: 'SELECTED DATA INDICES: \n' + brushed.join('\n'),
>             bottom: 0,
>             right:'10%',
>             width: 100,
>             textStyle: {
>                 fontSize: 12,
>                 color: '#fff'
>             }
>         }
>     });
> }
> ```
> 
> 可以像上面的`getStackByName`函数做的那样，用一个函数或映射，把`stack`信息和`seriesName`或其他属性关联起来。
> 
> You can try to associate stack information with seriesName or other attributes by a map or a getter function, as what `getStackByName` function does above.

Thank you for your reply, but I want to show all the information of each stack column, not the information of each item

**Comment by adrndfn** [comment]
![image](https://github.com/apache/echarts/assets/165926095/f7e160c5-d5f6-4d00-9abb-74c7bc107f64)

Hello, with bar charts in stack configuration we can only have the item informations or the whole axis informations in the tooltip by using trigger param.
But we would like to show only the stack informations ( = all item informations of the hovered stack )
Is there a simply way to get that ? 

If no, is there now a way to get the hovered stack informations in the tooltip formatter to help us formatting tooltip ?
