### ISSUE TITLE
VUE中使用echarts节点无法进行拖拽

### ISSUE THREAD

**Issue by jactorew** [apache/echarts#15277]
### Version
3.8.5

### Reproduction link
[https://codesandbox.io/embed/compassionate-jepsen-gxsdd?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/compassionate-jepsen-gxsdd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
老项目中使用的是Angular 1.x   echarts 3.8.5，曲线图表的节点可以正常进行拖拽，用VUE2.x echarts 3.8.5重构项后无法触发拖拽事件，其他的onmousemove、onmouseout可以正常触发。代码在CodeSandbox上

### What is expected?
可以正常触发拖拽事件ondrag

### What is actually happening?
无法触发拖拽事件ondrag

**Comment by Ovilia** [comment]
参见 https://github.com/apache/echarts/issues/15253

**Comment by jactorew** [comment]
> 参见 #15253

这个是VUE 3.x版本的，VUE 2.x没有解决办法吗？

**Comment by gun-ctrl** [comment]
> > 参见 [#15253](https://github.com/apache/echarts/issues/15253)
> 
> 这个是VUE 3.x版本的，VUE 2.x没有解决办法吗？

大佬，这个问题解决了吗？我也遇到了同样的问题，vue2环境实现拖拽没有效果
