### ISSUE TITLE
echarts5 The selected color of the map area cannot be changed

### ISSUE THREAD

**Issue by Dreamagician** [apache/echarts#15274]
### Version
5.1.0

### Steps to reproduce
地图区域选中色一直是默认颜色  emphasis的areaColor 值控制了hover颜色 选中后颜色变成了默认颜色

### What is expected?
 emphasis的areaColor 控制选中区域颜色

### What is actually happening?
 emphasis的areaColor 只控制区域hover颜色

**Comment by isongme** [comment]
你的意思是需要改变选中情况下的areaColor吗？如果是的话，可以试试以下的效果：
select: {
  itemStyle: {
  areaColor: "blue", // 默认颜色是黄色
},

**Comment by Dreamagician** [comment]
> 你的英文是需要改变选中情况下的areaColor吗？如果是的话，可以利用以下的效果：
> select: {
> itemStyle: {
> areaColor: "blue", //默认颜色是黄色
> },
