### ISSUE TITLE
How to differ the areaColor of different areas when emphasised?（当地区被emphasis怎么设置不同颜色）

### ISSUE THREAD

**Issue by isongme** [apache/echarts#15276]
![areaColor](https://user-images.githubusercontent.com/65857298/124217287-aba8ae00-db2a-11eb-8300-d69702d9988b.png)
### What problem does this feature solve?
when initing the map, the range of data need be carved by different areaColor. But the emphasised  area' areaColor displays initial areaColor(yellow).(初始化地图时，使用不同的颜色代表了不同的数据范围，地区被emphasis时，展示的是默认颜色。)

### What does the proposed API look like?
what I need is the areaColor same with normal areaColor .（我希望emphasis时地区的颜色能和底色相同。）

**Comment by plainheart** [comment]
你是希望处于高亮状态的区域背景色透明么？

**Comment by isongme** [comment]
> 你是希望处于高亮状态的区域背景色透明么？

感谢回复！不是的，是希望和底色一致。如果区域原本是浅红，高亮就浅红；如果区域原本是深红，高亮就深红。

**Comment by isongme** [comment]
somebody help me ?

**Comment by plainheart** [comment]
@isongme Hi, sorry for the late update. This feature has been implemented by #15172. You can wait for the next release of 5.2.0.

Here is the demo that uses [echarts nightly version](https://www.npmjs.com/package/echarts-nightly): https://www.makeapie.com/editor.html?c=xJCOld1_N6&v=1
