### ISSUE TITLE
微信小程序 柱状图 showBackground 属性 不起作用!

### ISSUE THREAD

**Issue by sixsixsix516** [apache/echarts#15273]
### Version
5.1.0

### Steps to reproduce
我的options

var option = {
    xAxis: [
        {
            type: 'category',
            data: ['6-22', '6-23', '6-24', '6-25', '6-26', '6-27', '6-28']
        }
    ],
    yAxis: [
        {
            type: 'value',
            show: false,
            splitLine: {
                show: false
            },
        },
    ],
    series: [
        {
            type: 'bar',
            showBackground: true,
            backgroundStyle: {
                color: {
                    image: src
                }
            },
            itemStyle: {
                color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
                    [
                        {offset: 0, color: '#b0b7feFF'},
                        {offset: 1, color: '#ff99daFF'}
                    ]
                )},
            data: [0, 0, 0, 12000, 0, 0, 0],

        },
        {
            type: 'line',
            smooth: true,
            symbol: 'circle',
            symbolSize: 8,
            itemStyle: {
                color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
                    [
                        {offset: 0, color: '#4b68e6FF'},
                        {offset: 0.5, color: '#b848f2FF'},
                        {offset: 1, color: '#c957b7FF'}
                    ]
                )},
            data: [5200, 4900, 7982, 12000, 6720, 8721, 7384]
        }
    ]
};

### What is expected?
柱状图有背景

### What is actually happening?
现在就是空白的

---

**Comment by Ovilia** [comment]
我在微信开发者工具和真机预览中都不能复现这个问题，请先确认一下对应的 ECharts 版本号，以及代码是否能在网页版中符合预期地显示。
