### ISSUE TITLE
Label not rendering correctly in Gantt Chart inside the bars

### ISSUE THREAD

**Issue by githubdatabridge** [apache/echarts#15289]
### Version
5.1.0

### Reproduction link
[https://jsfiddle.net/3nwsdjxf/199/](https://jsfiddle.net/3nwsdjxf/199/)

### Steps to reproduce
When rendering the gantt chart the rendering of the label within the bars is failing. This happens in SVG and CANVAS mode. There is no duplication of data. Example provided in the fiddler demo.

### What is expected?
Labels are rendered correctly within the bars

### What is actually happening?
Labels rendering within the bar is not rendered correctly.

---
Additionally is there a way to disable the zooming on the scrolling (slider), so that we can achieve just the scrolling behaviour without the zooming?

**Comment by Ovilia** [comment]
Please simplify your demo to be minimum.

**Comment by Ovilia** [comment]
Text x is `_rawData.colStartAtPx[0]` which is 0 so the text all have the same position. Please refer to [this example](https://echarts.apache.org/examples/zh/editor.html?c=custom-profit).

**Comment by githubdatabridge** [comment]
Hi @Ovilia ,

I believe that the _rawData.colStartAtPx[0] is related to the label of the column, as when I am changing it it shifts the label to left or right according to that value.

But in our case the issue is that we would like to avoid the overlapping of the labels within the rect, as you from the screenshot above.

The related piece of code is in line 227, even though x and y are always different it renders at 

position x=0 (see screenshot below):

` var rectText = clipRectByRect(params, {
        x: x,
        y: y,
        width: barLength,
        height: barHeight,
    });`

<img width="1073" alt="Screenshot 2022-10-11 090716" src="https://user-images.githubusercontent.com/62990773/195019536-9fd30d9b-ec9a-416e-8cdf-89219640c4e4.png">

Hope this helps.

Kind regards,
Patric

**Comment by githubdatabridge** [comment]
@Ovilia any update on this?
