### ISSUE TITLE
echarts 绘制散点图时，在不同的移动设备上显示的散点图不全

### ISSUE THREAD

**Issue by tks-007** [apache/echarts#15292]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/tks007/hsufw179/11/](https://jsfiddle.net/tks007/hsufw179/11/)

### Steps to reproduce
将绘图的option配置复制一份，随意打开一个绘图示例 ，https://echarts.apache.org/examples/zh/editor.html?c=line-smooth，将复制的option配置替换查看运行的绘图，把势利页面的代码跟绘图之间的线往右移动，右侧的 绘图区域慢慢缩小，直至缩到最小，就会发现有部分点位不显示

### What is expected?
绘图显示所有点位

### What is actually happening?
绘图点位显示缺失

---
绘图应用于小程序中，在iphone8时显示全，8以上显示就会缺失

**Comment by plainheart** [comment]
可能是画布太小导致图形被裁剪了，可以设置下 `series.clip` 为 `false`。

**Comment by tks-007** [comment]
> 可能是画布太小导致图形被裁剪了，可以设置下 `series.clip` 为 `false`。

已解决，谢谢
