### ISSUE TITLE
如何用seajs加载 压缩的echarts呢？ Issue #97中没有解决使用压缩的echarts

### ISSUE THREAD

**Issue by ghost** [apache/echarts#153]
如何用seajs加载 压缩的echarts呢？ Issue #97 中没有解决使用压缩的echarts

**Comment by lifeforfun** [comment]
能否将全局require放到echarts命名空间里，我这里加载了seajs后再加载echarts，echarts里的require就成了undefined了，如果echarts和seajs各自的方法放置不同的名字空间，那估计也不会有什么冲突
