### ISSUE TITLE
echarts4 update to echarts5 questions

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#15301]
### Version
5.1.2

### Reproduction link
[https://ecomfe.github.io/echarts-issue-helper/](https://ecomfe.github.io/echarts-issue-helper/)

### Steps to reproduce
npm echarts4 update to echarts5

```js
          axisLabel: {
            textStyle: {
              color: '#999', //坐标轴字颜色
              fontSize: '1rem'
            },
          },
```

### What is expected?
I want to no warning

### What is actually happening?
[ECharts] DEPRECATED: textStyle hierarchy in axisLabel has been removed since 4.0. All textStyle properties are configured in axisLabel directly now.
![image](https://user-images.githubusercontent.com/24451091/124555346-92289e80-de69-11eb-9e9c-694bbb67b60d.png)

---
4->5,What should we pay attention to when we upgrade the API?
The content of the report's warning is almost impossible to find online

**Comment by plainheart** [comment]
A very simple usage,

Before v4.0, we usually use like this,

```
lineStyle: {
  normal: {
     ...
  },
  emphasis: {
     ...
  }
}
```

Now it's suggested to configure like this,

```js
// normal state
lineStyle: {
  ...
},
emphasis: {
  lineStyle: {
    ...
  }
}
```

**Comment by zhoufanglu** [comment]
> A very simple usage,
> 
> Before v4.0, we usually use like this,
> 
> ```
> lineStyle: {
>   normal: {
>      ...
>   },
>   emphasis: {
>      ...
>   }
> }
> ```
> 
> Now it's suggested to configure like this,
> 
> ```js
> // normal state
> lineStyle: {
>   ...
> },
> emphasis: {
>   lineStyle: {
>     ...
>   }
> }
> ```



> A very simple usage,
> 
> Before v4.0, we usually use like this,
> 
> ```
> lineStyle: {
>   normal: {
>      ...
>   },
>   emphasis: {
>      ...
>   }
> }
> ```
> 
> Now it's suggested to configure like this,
> 
> ```js
> // normal state
> lineStyle: {
>   ...
> },
> emphasis: {
>   lineStyle: {
>     ...
>   }
> }
> ```

chart.resize(), The animation is gone?

**Comment by pissang** [comment]
@zhoufanglu Please see https://echarts.apache.org/en/api.html#echartsInstance.resize

**Comment by zhoufanglu** [comment]
> @zhoufanglu Please see https://echarts.apache.org/en/api.html#echartsInstance.resize

Thanks for the answer, it is valid.
https://echarts.apache.org/zh/theme-builder.html  
官方的主题文件是否没有更新到echarts5的版本？ 我引用全部警告
Is the official subject file not updated to the version of Echarts5?I quote all the warnings

**Comment by pissang** [comment]
@zhoufanglu 嗯，主题编辑器正在升级中

**Comment by zhoufanglu** [comment]
> @zhoufanglu 嗯，主题编辑器正在升级中

```js
      "itemStyle": {
        "areaColor": "#eeeeee",
        "borderColor": "#aaaaaa",
        "borderWidth": 0.5,
        "emphasis": {
          "areaColor": "rgba(63,177,227,0.25)",
          "borderColor": "#3fb1e3",
          "borderWidth": 1
        }
      },
```
![image](https://user-images.githubusercontent.com/24451091/124572301-218a7d80-de7b-11eb-93d3-e9b54a104830.png)
how to modify by this warning?

**Comment by plainheart** [comment]
```json
"itemStyle": {
    "areaColor": "#eeeeee",
    "borderColor": "#aaaaaa",
    "borderWidth": 0.5
},
"emphasis": {
  "itemStyle": {
    "areaColor": "rgba(63,177,227,0.25)",
    "borderColor": "#3fb1e3",
    "borderWidth": 1
  }
}
```
