### ISSUE TITLE
The Line charts disappears on zooming in/out even though the data points are present in the chart.

### ISSUE THREAD

**Issue by shishiranshuman** [apache/echarts#15315]
### Version
4.7.0

### Reproduction link
[https://codesandbox.io/s/echart-line-vanilla-6yx5s?file=/src/index.js](https://codesandbox.io/s/echart-line-vanilla-6yx5s?file=/src/index.js)

### Steps to reproduce
Try playing around with the zoom functionality on the Line chart either via the slider or inside the charts, the lines disappear even though the data is present. When the line disappears, hovering over the chart shows the data getting plotted.

I do not understand or figure out why is this happening. Could someone help me with this?  Please take a look at the echarts options in the sandbox provided.

### What is expected?
The lines disappear on zooming in.

### What is actually happening?
The lines should not disappear on zooming in.

### Screenshot/Video of the issue
![Echarts-Line](https://user-images.githubusercontent.com/20037600/124979678-fa85a480-e050-11eb-92b3-d18ca306a60d.gif)

**Comment by susiwen8** [comment]
Didn't reproduce in 5.1.2. Please update echarts

**Comment by shishiranshuman** [comment]
This issue is reproducible with 5.2.0 https://codesandbox.io/s/echart-line-5-2-0-1r2ut

**Comment by mydoghasfleas** [comment]
Still experiencing this issue in 5.6.0.
When zooming in on a line chart, the lines disappear when one of their points disappear from view.
The lines are only visible when their bounding points are also present in the view.

**Comment by occeannetics120** [comment]
The issue still persists , is there a fix ?

**Comment by mydoghasfleas** [comment]
@occeannetics120 My fix has been to switch to a different charting library.
