### ISSUE TITLE
markPoint属性中的data里的symbolOffset属性失效

### ISSUE THREAD

**Issue by Lee324** [apache/echarts#15325]
![echarts1](https://user-images.githubusercontent.com/22317901/125154486-d29b5b80-e18c-11eb-9d84-c6a2224f3b48.png)
![222](https://user-images.githubusercontent.com/22317901/125154589-40e01e00-e18d-11eb-8a4f-075940029062.png)

### Version
5.1.2

### Steps to reproduce
在官网Demo中设置一条折线的最大最小值时，需要移动最大最小值相对折线的位置，官网提供了symbolOffset属性，但按官方文档中设置该属性时，在最新版本的Echarts中该属性失效。详见我上传图片

### What is expected?
最大最小值相对折线位移

### What is actually happening?
在最新echarts中symbolOffset属性失效，官网4.0版本有效，实测上一版本echarts有效的。

**Comment by plainheart** [comment]
下个版本 5.2.0 会修复。

**Comment by ExcitedSpider** [comment]
我暂时先使用 5.0.2，symbolOffset 可用
