### ISSUE TITLE
A loop occurs in the line chart.

### ISSUE THREAD

**Issue by NeonPluto** [apache/echarts#15323]
### Version
5.1.2

### Steps to reproduce
```javascript
import * as echarts from 'echarts';

var chartDom = document.getElementById('main');
var myChart = echarts.init(chartDom, 'dark');
var option;

option ={
    "color": [
        "#4AC7B7",
        "#3398DB",
        "#E54545",
        "#86A6FC",
        "#85CAFF",
        "#6CE6DB",
        "#91E6B1",
        "#B7E697",
        "#F7E481",
        "#FFD578",
        "#FCA479",
        "#F7797B",
        "#F582AB",
        "#B891FA",
        "#B8BECC"
    ],
    "tooltip": {
        "trigger": "axis",
        "confine": "true",
        "axisPointer": {
            "type": "shadow"
        }
    },
    "grid": {
        "left": "1%",
        "right": "12%",
        "bottom": "1%",
        "top": "10%",
        "containLabel": true
    },
    "xAxis": {
        "type": "time",
        "splitLine": {
            "show": false
        },
        "axisLine": {
            "lineStyle": {
                "color": "white"
            }
        },
        "splitNumber": 3,
        "axisLabel": {}
    },
    "yAxis": [
        {
            "type": "value",
            "minInterval": 1,
            "min": 0,
            "max": 100,
            "axisLabel": {
                "color": "white"
            },
            "axisLine": {
                "lineStyle": {
                    "color": "white"
                }
            },
            "splitLine": {
                "show": false
            }
        }
    ],
    "series": [
        {
            "name": "6",
            "type": "line",
            "smooth": true,
            "barMaxWidth": 20,
            "showSymbol": false,
            "smoothMonotone": "x",
            "data": [
                [
                    1625688000000,
                    74
                ],
                [
                    1625707800000,
                    83
                ],
                [
                    1625709600000,
                    80
                ],
                [
                    1625711400000,
                    87
                ],
                [
                    1625713200000,
                    88
                ],
            ]
        }
    ]
};

option && myChart.setOption(option);
    
```

### What is expected?
No loopback occurs in the line chart.

### What is actually happening?
A loop occurs in the line chart.

**Comment by NeonPluto** [comment]
![image](https://user-images.githubusercontent.com/39722474/125059804-4cc0d700-e0de-11eb-9cf3-234c1c55f0dc.png)

**Comment by NeonPluto** [comment]
![截图](https://user-images.githubusercontent.com/39722474/125060142-a1645200-e0de-11eb-8212-b363008f5602.PNG)

**Comment by susiwen8** [comment]
`[smoothMonotone](https://echarts.apache.org/zh/option.html#series-line.smoothMonotone)` affect it, in the case, you do not need `smoothMonotone`

**Comment by NeonPluto** [comment]
> [smoothMonotone](https://echarts.apache.org/zh/option.html#series-line.smoothMonotone) affect it, in the case, you do not need `smoothMonotone`

I know it, and delete this param,but i want konw why when i set value is x and result is false,when i set value is y or default and result is true ?

**Comment by ptulou** [comment]
We pulled down the new version and I'm still seeing the same behavior. This is our data with "smooth" set to true but smoothMonotone is not set at all:

![image](https://user-images.githubusercontent.com/5910243/142896913-28258b7b-d2c2-4f58-8fb1-7de3541aae81.png)

This is the same data with smoothMonotone: 'x'

![image](https://user-images.githubusercontent.com/5910243/142896825-625a3ddd-e0ea-4517-9a25-f7592e4d750e.png)

I'm thinking this is exactly backwards, but perhaps I am missing something? The behavior does not seem to match what's in the doc (https://echarts.apache.org/en/option.html#series-line.smoothMonotone), so I would think there's either a product bug or the doc should be updated to explain the behavior.

**Comment by pissang** [comment]
@ptulou Did you build from the latest source code?

**Comment by ptulou** [comment]
@pissang I simply pulled down the latest echarts (v5.2.2) from npm. From the release notes, I believe this change should have been in that version.

**Comment by pissang** [comment]
It's fixed in https://github.com/apache/echarts/pull/16069 and will be included in the next release

**Comment by ptulou** [comment]
@pissang thank you! I see my mistake now. When I scanned the release notes I saw this fix and jumped to the conclusion that it was the same fix.  **[Fix] [line] fix smoothed line with duplicate points failed to draw #15942 (pissang)**. Oops! I'll check out the next release. Thanks for clarifying!
