### ISSUE TITLE
X-range plot very slow and jam with more than 10,000 data

### ISSUE THREAD

**Issue by LJXLJXLJX** [apache/echarts#15332]
### Version
5.1.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=custom-profile 

I am developing a application like the example above, but my data amount is very large. I read data from json, there are more than 10,000 
even 100,000 items. It's very slow when rendering the bars, and if I enable zoom in, the page will crash when zoom in.

You can just test the above example, set the dataCount to 10,000 , it's really slow and even jam.

### What is expected?
It shouldn't be so slow.

### What is actually happening?
It's very slow.

**Comment by Ovilia** [comment]
It is not recommended to render custom charts with such big number. Please first consider if it is necessary to render 10000 data and why so. You may try with [progressive](https://echarts.apache.org/en/option.html#graphic.elements-rect.progressive) rendering.

**Comment by rullymartanto** [comment]
hi @Ovilia do you have an detail example how to do it?
