### ISSUE TITLE
When one series data is all null, no series name & value info would show in the tooltip dialog

### ISSUE THREAD

**Issue by irenetang1993** [apache/echarts#15331]
### Version
5.0.0

### Reproduction link
[https://codepen.io/xiaobeizi/pen/mdmOORO](https://codepen.io/xiaobeizi/pen/mdmOORO)

### Steps to reproduce
when one series data is all null, and I hover to show the tooltip, no series name & value info would show. 
As long as there is one not-null value in the series data, the series name & value info would show in the tooltip dialog

### What is expected?
The series name & '-' can still show up in the tooltip dialog even if the data array is all null

### What is actually happening?
not showing the series name & '-' in the tooltip dialog when the data array is all null

**Comment by susiwen8** [comment]
Fixed in 5.3.0
