### ISSUE TITLE
Like R package ggplot-aes(),the legend reflects value

### ISSUE THREAD

**Issue by zpinocchio** [apache/echarts#15330]
### What problem does this feature solve?
https://echarts.apache.org/examples/zh/editor.html?c=bubble-gradient 
In this example,the point size can't reflects really size 

### What does the proposed API look like?
![image](https://user-images.githubusercontent.com/49098424/125265414-67da5380-e337-11eb-82a8-044a63682ebb.png)

**Comment by pissang** [comment]
@zpinocchio Currently you can use the component `visualMap` to encode the `symbolSize`
