### ISSUE TITLE
如果获取雷达图当前点的值或者索引？

### ISSUE THREAD

**Issue by YIngChenIt** [apache/echarts#15339]
### Version
4.3.0

### Steps to reproduce
`option = {
    title: {
        text: '基础雷达图'
    },
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        indicator: [
            { name: '销售（Sales）', max: 6500},
            { name: '管理（Administration）', max: 16000},
            { name: '信息技术（Information Technology）', max: 30000},
            { name: '客服（Customer Support）', max: 38000},
            { name: '研发（Development）', max: 52000},
            { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        data: [
            {
                value: [4200, 3000, 20000, 35000, 50000, 18000],
                name: '预算分配（Allocated Budget）'
            },
            {
                value: [5000, 14000, 28000, 26000, 42000, 21000],
                name: '实际开销（Actual Spending）'
            }
        ]
    }]
};`

我想获取当前点的索引或者值，而不是全部，配置如代码，我想点击到销售点上，只想获取销售的索引或者当前值，看了好久的文档，没有找到，有谁知道的么？
我用了点击事件，发现里面有个参数是dataIndex，但是永远是0

有什么办法可以让我拿到点击销售这个点对应的索引或者数据么

### What is expected?
获取雷达图当前点的值或者索引

### What is actually happening?
点击事件拿的是全部事件，获取不到当前点的数据

**Comment by Ovilia** [comment]
请关注 #10750

**Comment by helgasoft** [comment]
yes, a **bug** in [tooltip.formatter](https://echarts.apache.org/en/option.html#tooltip.formatter) **data** for _radar_.
The _tooltip.formatter_ handler for radar gives incorrect _data.dataIndex_ and _data.seriesIndex_.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=radar&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmurAGbABOAtgIZhgCmFhAFCAJQIB8RJJAxjADOOBgDpswAOZt2AbmJ9QkGGMhhsDREkYAPMPgDkpamGaxDAahBjoNKg0uKSh2ABMIu-FZtu6NAEloNwZdWCc-dFchT29rMSEmCAYhIJDdZ3QAXwVI2CoATwBhAAsaCjAEhjAAeXAoaBZlBvlM2ApqgFcKOBBckiziLIAaYgoaP3NUPghgiH46SkIAbTakWDsHQkMAZRpNIUNh_JpdQgA2AFYABmvYEbWN-wZtgEE3KlmIITM6BqOTmdYABGc63O4PPLrTYvCxBcjUP4wWAAFQY_BK0Bw0gKANoQIAzOCIaMoU8thYip0fsAHBRYDtOiAQJQwHjToQCQAOcH3UmRaHPbYAEQYADcGJIQA5oGzjvjCJcAEy8yEC8mwwwAWXKAGtqrMpOygUqbrd7s4ALr89BmCBSKRMACiEtlhDMnQYQ35iQoySEK2c00iMO2ACFOm5HWBYGKhLAhCAGHNoEabSQwAUk9txpMjm0_GAaIG8uhg6XY_tPSsACwq67HIm3Y715uwAlmhuwTtd4E827Wtp8UMWV7YSQLRhuWARqPVQxDvmL8ulsVV2HLTvHYE18Et_tdpVgtt1vewJXA8GDivoEeGV78MCdfYMpMpo2LwZ5S3OL-wH85EAA)
