### ISSUE TITLE
这个包项目本地如何调试?

### ISSUE THREAD

**Issue by mxy2316868975javascript** [apache/echarts#15342]
### Version
5.1.2

### Steps to reproduce
npm run dev 不能调试

### What is expected?
如何本地调试echarts这个包

### What is actually happening?
.,.

---
如果是npm run dev不会运行

**Comment by susiwen8** [comment]
https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment

**Comment by mxy2316868975javascript** [comment]
> https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment

端口号是8866吗, 我这边跑不起来什么情况, 也没有报错, 一直是这个状态
![image](https://user-images.githubusercontent.com/15233384/125413284-2fefe81e-d28c-4bf4-b9b7-a3deacc618ca.png)

**Comment by susiwen8** [comment]
没有端口，这不需要端口。随便打开 test/ 中的一个测试用例就行。(有些测试用例需要起个服务, 但大部分不需要，建议 allZero。html).

**Comment by mxy2316868975javascript** [comment]
> 没有端口，这不需要端口。随便打开 test/ 中的一个测试用例就行。(有些测试用例需要起个服务, 但大部分不需要，建议 allZero。html).

通过test中的文件是如何调试echarts src的源码呢

**Comment by susiwen8** [comment]
控制台 debug, 打断点，有 source map 的

**Comment by mxy2316868975javascript** [comment]
同时也没有理解npm run dev的用途

**Comment by mxy2316868975javascript** [comment]
> debug

比如allZero.html这个文件是如何和源码对应的, 如何找到对应的源码文件呢

**Comment by mxy2316868975javascript** [comment]
请问启动服务如何配置呢

**Comment by zxflslzyx** [comment]
请问这个问题解决了吗，我也想问这个问题
