### ISSUE TITLE
Simple Scrollbar (or Slider Zoomlock Working properly)

### ISSUE THREAD

**Issue by javeiga-iest** [apache/echarts#15340]
### What problem does this feature solve?
I need to add a scroll bar (without zoom) to my chart and it is being very complicated, it would be wonderful if there was a simple Scrollbar instead of always using the DataZoom.

Another option would be for the zoomLock option to work on the dataZoom slider type, hiding the selection part and letting the bar occupy the rest of the height

### What does the proposed API look like?
```
scrollBar:[{
}]
```
or 
```
dataZoom: [{
    type: 'slider',
    zoomLock: true,

}],
```

**Comment by Ovilia** [comment]
If [zoomLock](https://echarts.apache.org/en/option.html#dataZoom-inside.zoomLock) works in your situation, what's the problem here?

**Comment by javeiga-iest** [comment]
> If [zoomLock](https://echarts.apache.org/en/option.html#dataZoom-inside.zoomLock) works in your situation, what's the problem here?

ZoomLock only works on the content, not in the slider

**Comment by Muromi-Rikka** [comment]
There is indeed a problem
