### ISSUE TITLE
The color of label in bar chart is inconsistent

### ISSUE THREAD

**Issue by YaoKaiPeng** [apache/echarts#15347]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/_kai_/o92mnqsa/3/](https://jsfiddle.net/_kai_/o92mnqsa/3/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/13029889/125550669-356ea864-a505-47eb-b658-d4c687eaf9e1.png)

When rendering the bar graph, control the display label, and find that the label color is inconsistent

### What is expected?
Uniform label color

### What is actually happening?
Inconsistent colors

**Comment by pissang** [comment]
@YaoKaiPeng Label color will be adjusted based on the luminance of the underlying element color. So they can have enough contrast to be displayed clearly. You can fix the color by setting `label.color` if don't like it.
