### ISSUE TITLE
Consider reverting the default design 'make line bolder in emphasis state'

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#15352]
According to the suggested design change in #12931, we added a new semantic value `bolder` for `emphasis.lineStyle.width` for line series to specify whether the line should be bolder when it's in emphasis state. And this new option is enabled by default.

It looks good in the test case provided by #13013, that is, this design is more suitable for those cases having focus and blur.

Some developers hope to disable this default behavior.

- #14622
- https://github.com/apache/echarts/pull/13013#issuecomment-802715909
- https://github.com/apache/echarts/issues/14952#issuecomment-842133264

So it may be better to revert to the previous behavior. If there are developers who still hope to make the line bolder,  they can configure `emphasis.lineStyle.width` to `bolder`(if this option can be reserved) or a bigger number than normal state.

**Comment by pissang** [comment]
+1

**Comment by Sakkyoku-Sha** [comment]
+1

On very large series this leads to some performance loss, ideally this functionality can be disabled altogether.
