### ISSUE TITLE
页面zoom缩放后 鼠标放在图表上会偏移  不能指向正确位置

### ISSUE THREAD

**Issue by Scott1995** [apache/echarts#15354]
### Version
4.9.0

### Steps to reproduce
body.style.zoom = 0.7

### What is expected?
正确展示鼠标所在信息

### What is actually happening?
展示了鼠标旁边的信息  发生了偏移

**Comment by plainheart** [comment]
和 #15103 相关，还需要一些讨论。zoom 是一个非标准属性，建议避免使用。
