### ISSUE TITLE
在火狐上使用SVG渲染器，图中有shadowBlur时，图对鼠标的反应异常

### ISSUE THREAD

**Issue by Zkdc** [apache/echarts#15351]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=pie-simple](https://echarts.apache.org/examples/en/editor.html?c=pie-simple)

### Steps to reproduce
1.打开链接，将渲染器切换为SVG。
2.将鼠标较慢地在饼图上面移动，或在饼图上点击。

### What is expected?
像canvas渲染器一样，鼠标经过的地方正常缩放，tooltip稳定跟随鼠标，鼠标点击图时某项数据不会隐藏。

### What is actually happening?
鼠标移动时：经过的图项与tooltip来回缩放。
点击时：图内某项数据概率性消失，或概率性重新出现（看起来像是点击了legend某项一样）。

---
1.不在emphasis内设置shadowBlur，直接设置在series上问题类似。
2.尝试了下柱状图，也有同样的问题。
3.windows下和linux下的火狐都有问题，linux下火狐版本是89.0.2。

**Comment by plainheart** [comment]
Fixed in ecomfe/zrender#812
