### ISSUE TITLE
5.0.0版本以上line系列的markPoint的symbolOffset不起作用

### ISSUE THREAD

**Issue by Jieqizhong** [apache/echarts#15362]
### Version
5.1.2

### Steps to reproduce
markPoint: {
                symbol: 'triangle',
                symbolRotate: '180',
                symbolSize: [30, 40], // 容器大小
                symbolOffset: [0, -20], // 位置偏移
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
            },

### What is expected?
设置symbolOffset位置能偏移

### What is actually happening?
无偏移

---
option = {
    title: {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data: ['最高气温', '最低气温']
    },
    toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} °C'
        }
    },
    series: [
        {
            name: '最高气温',
            type: 'line',
            data: [10, 11, 13, 11, 12, 12, 9],
            markPoint: {
                symbol: 'triangle',
                symbolRotate: '180',
                symbolSize: [30, 40], // 容器大小
                symbolOffset: [0, -20], // 位置偏移
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'}
                ]
            }
        },
        {
            name: '最低气温',
            type: 'line',
            data: [1, -2, 2, 5, 3, 2, 0],
            markPoint: {
                data: [
                    {name: '周最低', value: -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'},
                    [{
                        symbol: 'none',
                        x: '90%',
                        yAxis: 'max'
                    }, {
                        symbol: 'circle',
                        label: {
                            position: 'start',
                            formatter: '最大值'
                        },
                        type: 'max',
                        name: '最高点'
                    }]
                ]
            }
        }
    ]
};

**Comment by kchjxxgh** [comment]
it should be a new regression. 
it worked well in 5.0.2.
this issue really block me.

**Comment by plainheart** [comment]
Hi, thanks for the feedback. It will be fixed in the next version 5.2.0.
