### ISSUE TITLE
grid option does not work for Pie

### ISSUE THREAD

**Issue by ataft** [apache/echarts#15365]
### Version
5.1.2

### Steps to reproduce
```
option = {
    grid: {
        show: true,
        top: 300
    },
    series: [
        {
            type: 'pie',
            data: [
                {value: 1048, name: 'A'},
                {value: 735, name: 'B'},
                {value: 580, name: 'C'},
            ],
        }
    ]
};
```

### What is expected?
`grid.top` should work

### What is actually happening?
Setting `grid.top` does nothing to the pie

**Comment by pissang** [comment]
`grid` is not for pie. It's for cartesian coordinate system with xAxis and yAxis. `pie` itself has `left`, `right`, `top`, `bottom` properties.
