### ISSUE TITLE
Y-Axis labels are overflowing the graph when width is set to 100%

### ISSUE THREAD

**Issue by a1c9lll** [apache/echarts#15364]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/8jafrcnL/](https://jsfiddle.net/8jafrcnL/)

### Steps to reproduce
Fiddle attached.

### What is expected?
For the labels not to overflow the graph.

### What is actually happening?
The labels are overflowing the graph.

**Comment by a1c9lll** [comment]
I've also tried setting the width and adjusting it onresize and it still overflows the graph. So this might actually be a bug?

```javascript
  window.onresize = function() {
    chartDom.style.width = document.body.clientWidth + 'px'
    chart.resize();
  }
```

**Comment by susiwen8** [comment]
try `grid.containLabel: true`.
