### ISSUE TITLE
geo heatmap tooltips

### ISSUE THREAD

**Issue by helgasoft** [apache/echarts#15375]
### Version
5.1.2

### Reproduction link
[https://codepen.io/helgasoft/pen/eYWvxVM](https://codepen.io/helgasoft/pen/eYWvxVM)

### Steps to reproduce
move mouse over points

### What is expected?
tooltips to show on hovering heatmap points as the [documentation says](https://echarts.apache.org/en/option.html#series-heatmap.tooltip).

### What is actually happening?
no tooltips

---
More:
Replacing with ```type:'scatter'``` shows tooltips.

**Comment by plainheart** [comment]
#3313. It's not supported yet but may be added in the future.
