### ISSUE TITLE
关系图高亮事件失效

### ISSUE THREAD

**Issue by lxy326501** [apache/echarts#15377]
### Version
5.1.2

### Steps to reproduce
charts_knowledge_map.on('click', (params) => {
        charts_knowledge_map.dispatchAction({
	type: 'highlight',
	dataIndex: params.dataIndex,
   });
});

### What is expected?
点击的节点及关系高亮

### What is actually happening?
都未高亮

**Comment by kilosangma** [comment]
所以现在能解决了吗
