### ISSUE TITLE
smooth 导致折线图绘制失败

### ISSUE THREAD

**Issue by YaoKaiPeng** [apache/echarts#15371]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/fv5uhget/2/](https://jsfiddle.net/fv5uhget/2/)

### Steps to reproduce
渲染线图时，用了smooth： true 来保证线条的平滑度，但发现这种情况下，线条会绘制失败。

### What is expected?
线图正常渲染

### What is actually happening?
目前未绘制成功

**Comment by g7i** [comment]
I'm working on this issue.

**Comment by g7i** [comment]
Hey @pissang, the algorithm being used in `drawSegment` function in the file `src/chart/line/poly.ts #L38` is a little complex. Can you please provide me some reference so that I can understand it. Thanks
