### ISSUE TITLE
not able to add the lable at the middle of the line dynamically in tree chart 

### ISSUE THREAD

**Issue by mr-dreamer07** [apache/echarts#15373]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/7kyn5vmf/9/](https://jsfiddle.net/7kyn5vmf/9/)

### Steps to reproduce
not able to add lable at the middle point of the line joining parent and children.

### What is expected?
able to add the lable at the middle of the line  in tree chart dynamically

### What is actually happening?
have to count manually with trial and error

---
want to add the lable of the children at the mid point of the line joining parent and the children.

**Comment by Ovilia** [comment]
Can you make an image to illustrate what is expected?
