### ISSUE TITLE
折线图在5.1.2 版本下渲染bug

### ISSUE THREAD

**Issue by learnerYoung** [apache/echarts#15372]
这是数据
`option = {
	"series": [{
		"type": "line",
		"name": "/攻击入侵",
		"data": [98, 196, 195, 186, 194, 202, 198, 194, 196, 196, 196, 195, 197, 196, 196, 196, 193, 200, 197, 196, 200, 194, 198, 206, 185, 31],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/恶意代码/病毒",
		"data": [36, 69, 70, 72, 69, 70, 69, 72, 72, 68, 68, 68, 71, 68, 68, 68, 68, 68, 68, 68, 70, 70, 70, 69, 71, 7],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/网络扫描/端口扫描",
		"data": [24, 52, 44, 48, 48, 48, 49, 48, 49, 50, 51, 51, 50, 55, 52, 52, 51, 56, 54, 49, 48, 48, 52, 48, 48, 6],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/网络扫描",
		"data": [24, 43, 48, 56, 50, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 54, 10],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/恶意代码/其它",
		"data": [24, 50, 47, 47, 48, 54, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 50, 49, 47, 6],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/恶意代码",
		"data": [22, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 5],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/拒绝服务",
		"data": [16, 32, 36, 36, 30, 35, 33, 32, 32, 34, 32, 32, 33, 36, 33, 32, 33, 36, 35, 32, 47, 31, 35, 32, 33, 5],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/漏洞利用",
		"data": [12, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 3],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/其它",
		"data": [12, 20, 19, 20, 20, 20, 20, 20, 20, 19, 20, 20, 20, 21, 19, 20, 20, 20, 20, 21, 20, 22, 20, 20, 20, 2],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/密码破解",
		"data": [4, 8, 8, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 7, 2],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/后门攻击",
		"data": [4, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/网络扫描/",
		"data": [4, 8, 8, 8, 8, 8, 8, 8, 8, 6, 8, 8, 8, 9, 7, 8, 8, 8, 8, 10, 8, 8, 8, 8, 8, 0],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/网络扫描/漏洞扫描",
		"data": [4, 8, 8, 8, 8, 8, 7, 8, 7, 6, 5, 5, 6, 1, 4, 4, 5, 0, 2, 7, 8, 8, 8, 8, 8, 1],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/网络扫描/其它",
		"data": [4, 5, 4, 3, 6, 8, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 7, 4, 10, 5, 3, 1],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}, {
		"type": "line",
		"name": "/攻击入侵/网络劫持",
		"data": [0, 1, 8, 8, 2, 0, 2, 8, 7, 1, 0, 1, 5, 0, 0, 3, 5, 0, 0, 7, 8, 4, 0, 1, 8, 1],
		"stack": "won",
		"smooth": true,
		"areaStyle": {}
	}],
	"xAxis": [{
		"type": "category",
		"boundaryGap": false,
		"data": ["2021-07-16\n10:39:12", "2021-07-16\n10:39:24", "2021-07-16\n10:39:36", "2021-07-16\n10:39:48", "2021-07-16\n10:40:00", "2021-07-16\n10:40:12", "2021-07-16\n10:40:24", "2021-07-16\n10:40:36", "2021-07-16\n10:40:48", "2021-07-16\n10:41:00", "2021-07-16\n10:41:12", "2021-07-16\n10:41:24", "2021-07-16\n10:41:36", "2021-07-16\n10:41:48", "2021-07-16\n10:42:00", "2021-07-16\n10:42:12", "2021-07-16\n10:42:24", "2021-07-16\n10:42:36", "2021-07-16\n10:42:48", "2021-07-16\n10:43:00", "2021-07-16\n10:43:12", "2021-07-16\n10:43:24", "2021-07-16\n10:43:36", "2021-07-16\n10:43:48", "2021-07-16\n10:44:00", "2021-07-16\n10:44:12"],
		"axisLabel": {
			"show": true
		},
		"axisTick": {
			"show": false
		},
		"axisLine": {
			"show": false,
			"textStyle": {
				"fontSize": "10",
				"itemSize": ""
			}
		}
	}],
	"yAxis": [{
		"type": "value",
	}]
}`

这是分别在5.1.2 和 5.1.1 的渲染效果

![image](https://user-images.githubusercontent.com/44129974/125884921-7a6627f6-7254-406a-8060-038be5c966fc.png)
![image](https://user-images.githubusercontent.com/44129974/125884949-34fd846b-3226-4052-9192-43ca285b8ce9.png)

**Comment by plainheart** [comment]
没有复现，请问你使用的是什么系统？什么浏览器？哪个版本？
