### ISSUE TITLE
Long touch in bar chart won't trigger contextmenu event in mobile device

### ISSUE THREAD

**Issue by ycheeyan** [apache/echarts#15374]
### Version
5.1.1

### Steps to reproduce
1. Create a bar chart and listen to the contextmenu event.
2. View the chart at browser in mobile device and try to long touch one of the the bar, it won't trigger the contextmenu event. 

### What is expected?
Long touch can trigger the contextmenu event.

### What is actually happening?
Long touch can't trigger the contextmenu event.

---
1. The mobile view can be simulated can be simulated by using the browser dev tool.
2. We found out the long touch can trigger the contextmenu event in Microsoft Edge browser, but it doesn't work in Google Chrome browser.

**Comment by Ovilia** [comment]
The `contextmenu` event is implemented at https://github.com/ecomfe/zrender/blob/master/src/Handler.ts#L396
Please search for Chrome compatibility and see what we can do with it.
