### ISSUE TITLE
Scatter3D label cut off

### ISSUE THREAD

**Issue by eapatel** [apache/echarts#15388]
### Version
4.0.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=lines3d-flights&gl=1](https://echarts.apache.org/examples/en/editor.html?c=lines3d-flights&gl=1)

### Steps to reproduce
https://echarts.apache.org/examples/en/editor.html?c=lines3d-flights&gl=1

Please consider above example as a reference.

### What is expected?
Data labels should not be cut at any angle view.

### What is actually happening?
https://echarts.apache.org/examples/en/editor.html?c=lines3d-flights&gl=1

This above example I used in my project. I found that when hovering over a data point on the globe, the data label occasionally shows as cut off at an angle. See below screenshot

![label_cutoff](https://user-images.githubusercontent.com/47823148/126413705-ebc26822-c9c1-4ac0-a949-e7a3e7155e12.png)

**Comment by eapatel** [comment]
Can someone please have a look and reply back?

**Comment by eapatel** [comment]
Is this a bug? If yes, is it possible to solve this or please suggest any alternative solution. 

Thanks in advance for any help.

**Comment by eapatel** [comment]
Can someone please have a look and reply back?

**Comment by eapatel** [comment]
Can someone please reply? I really need a fix for my project.

**Comment by pissang** [comment]
@eapatel Sorry for missing this issue. The only solution I can think of now is set a higher z value for the point using labels. And avoid using long labels as much as possible.

**Comment by eapatel** [comment]
Thanks for replying and sharing solution @pissang. 

I tried to set a higher z-value for the point, however now I'm unable to access globe and legend as the z-value of the point is now higher.

**Comment by eapatel** [comment]
Hi @pissang, even if the z-index is set to a higher value, the label is cut off at an angle. Please provide the solution for it.

**Comment by nelsonbbarriento23** [comment]
Come @olivaia

**Comment by Ivygirl** [comment]
The symbol's img  is also cutted off as well as label info.
