### ISSUE TITLE
Visual glitch in stacked line chart (bridges end and start points)

### ISSUE THREAD

**Issue by ope-nz** [apache/echarts#15380]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/b1kcr42a/1/](https://jsfiddle.net/b1kcr42a/1/)

### Steps to reproduce
Create a stacked chart with several data series. Sometimes there will be a visual glicth that appears to bridge the end and start points of a series in the chart. Sometime this will occur for many series.

![image](https://user-images.githubusercontent.com/26259049/126215591-738478eb-86ad-4c92-b975-ad71ef33f1be.png)

### What is expected?
The stacked chart draws without issues

### What is actually happening?
A visual glitch that appears to bridge the end and start points of a series

---
This problem occurs in 5.1.2 but not in 5.0.0 - I havent not tested version in between.

5.1.2
![image](https://user-images.githubusercontent.com/26259049/126215505-55ae350e-4acf-417b-9613-43161a0ebbb7.png)

5.0.0
![image](https://user-images.githubusercontent.com/26259049/126215537-7133d8e6-2514-4713-8024-c9a187fd449d.png)

**Comment by ope-nz** [comment]
I have now tested on 5.1.1 and the issue is not present.

**Comment by plainheart** [comment]
The issue reported by #15372 may be the same as this issue. It seems related to ecomfe/zrender#760.

**Comment by plainheart** [comment]
Note that, this error case needs us to specify some very small values, such as 0.1 or 0.2 in this case. If we increase it slightly, this issue will disappear.
