### ISSUE TITLE
Getting Cannot read property 'getDataPercentWindow' of undefined at dataZoomProcessor.js

### ISSUE THREAD

**Issue by raghavshivi94** [apache/echarts#15387]
### Version
4.6.0

### Steps to reproduce
While using line charts when providing series and yaxis options via an api call it throws this error.

### What is expected?
It should show the chart with the values

### What is actually happening?
Giving error Getting Cannot read property 'getDataPercentWindow' of undefined at dataZoomProcessor.js

![error](https://user-images.githubusercontent.com/53443659/126375875-5a183438-12d7-460d-924f-e9ebaaaa94a9.JPG)

**Comment by pissang** [comment]
Please have a try on the latest version
