### ISSUE TITLE
Toolbox feature dataZoom: Cannot read property 'group' of undefined.

### ISSUE THREAD

**Issue by RomanOlegovich** [apache/echarts#15398]
### Version
5.0.2

### Steps to reproduce
Try zoom by toolbox zoom feature.

### What is expected?
Zoom is worked.

### What is actually happening?
Toolbox zoom is broked after migration to 5.0.2. Error:
![image](https://user-images.githubusercontent.com/46935437/126582670-0adc7734-73c9-49d4-b11e-b77940c2129e.png)

**Comment by hongdeyuan** [comment]
```
// fix cannot read property ‘group’ of undefined
 animationDuration: 5000,
 animationDurationUpdate: 5000,
```

**Comment by hongdeyuan** [comment]
设置 silent: true看下是否有效避免
