### ISSUE TITLE
当yAxis的type为time类型，xAxis的type类型为value时，横向柱状图生成失败

### ISSUE THREAD

**Issue by Lee324** [apache/echarts#15394]
![W YUAOW2 XW~O)A GK46QO](https://user-images.githubusercontent.com/22317901/126480063-fd413a58-3ddf-4942-a5a5-af087e4812d8.png)
### Version
5.1.2

### Steps to reproduce
详见截图
```js
option ={
				"title":{
					"text":"J成烧工段",
					"left":8,
					"textStyle":{"fontSize":18}
				},
				"tooltip":{"trigger":"axis","confine":true},
				"legend":{"right":"center","top":40,"data":["时间稼动率","OEE"]},
				"yAxis":[{
					"type":"time",
				}
				],
				"xAxis":[{
					"type":"value",
				}
				],
				"series":[{
					"name":"时间稼动率",
					"type":"bar",
					"data":[{
						"name":"2021-04-06 07:00",
						"value":["2021-04-06 07:00",71.4]
					},{
						"name":"2021-04-06 08:00",
						"value":["2021-04-06 08:00",71.4]
					},
				]
				},
	]}
```
### What is expected?
当yAxis为time类型轴时，能正常生成横向柱状图

### What is actually happening?
yAxis为time类型轴时，横向柱状图无法生成，且tooltip框内显示的日期为1970-01-01 08:00:00

**Comment by susiwen8** [comment]
Switch series data to 
```js					
"data":[{
	"name":"2021-04-06 07:00",
	"value":[71.4, "2021-04-06 07:00"]
  },{
	"name":"2021-04-06 08:00",
	"value":[71.4, "2021-04-06 08:00"]
}]
```

**Comment by Lee324** [comment]
> 将系列数据切换到
> 
> ```js
> “数据”：[ { 
> 	“名称”：“2021-04-06 07:00” ，
> 	“值”：[ 71.4 ， “2021-04-06 07:00” ] 
>   } ，{ 
> 	“名称”：“2021-04” -06 08:00" , 
> 	"value" : [ 71.4 ,  "2021-04-06 08:00" ] 
> } ]
> ```

OK,谢谢解决我的问题。
