### ISSUE TITLE
It  doesn't work  when I set "tooltip. trigger:  'axis'" in Radar Chart

### ISSUE THREAD

**Issue by zxflslzyx** [apache/echarts#15402]
### Version
last

### Steps to reproduce
set "tooltip.trigger:'axis'",

### What is expected?
It works When I hover the axis

### What is actually happening?
I dones't work

**Comment by susiwen8** [comment]
`aixs` never work in `radar`, maybe we should mention in the doc

**Comment by susiwen8** [comment]
tract in #10537

**Comment by zxflslzyx** [comment]
This feature will not be supported in future plans, will it？
