### ISSUE TITLE
node-canvas create heatmap

### ISSUE THREAD

**Issue by yylink0208** [apache/echarts#15412]
### Version
4.9.0

### Steps to reproduce
1.node version 14.17.0
2.canvas version 2.8.0
3. i want to draw a heatmap or lines map  picture by a  node server,but it can not correct drawing

### What is expected?
i want get a heatmap or lines map picture

### What is actually happening?
get a white picture

**Comment by yylink0208** [comment]
demo at  https://codesandbox.io/s/wizardly-wilson-3o4ze?file=/src/index.js

**Comment by Ovilia** [comment]
Here is a list of server rendering solutions. See if this helps.

https://github.com/hellosean1025/node-echarts
https://github.com/chfw/echarts-scrappeteer
https://github.com/chfw/pyecharts-snapshot/blob/master/pyecharts_snapshot/phantomjs/snapshot.js
https://gist.github.com/pissang/4c32ee30e35c91336af72b129a1a4a73
