### ISSUE TITLE
 5.1.2版本下折线图渲染bug

### ISSUE THREAD

**Issue by learnerYoung** [apache/echarts#15418]
### Version
5.1.2

### Reproduction link
[https://www.makeapie.com/editor.html?c=x7IbnQExDy&v=1](https://www.makeapie.com/editor.html?c=x7IbnQExDy&v=1)

### Steps to reproduce
访问重现链接后出现折线图渲染bug

### What is expected?
正常渲染

### What is actually happening?
5.1.2版本出现了奇奇怪怪的线

---
此bug仅仅在5.1.2版本复现，任意其余echarts版本无法复现 (这在我和我的同事的电脑上是个必现的bug)

浏览器版本信息：Google Chrome 版本 92.0.4515.107（正式版本） （64 位）
操作系统版本信息：Windows 10 专业版 19042.1110

![image](https://user-images.githubusercontent.com/44129974/127132201-caf54b46-0e70-4130-bedf-4f69d1c7e42f.png)

**Comment by pissang** [comment]
已经在 https://github.com/ecomfe/zrender/pull/788 中修复，会包含在马上发布的 5.2.0 中
