### ISSUE TITLE
双对数坐标 网格线设置问题

### ISSUE THREAD

**Issue by xiongzm** [apache/echarts#15415]
### What problem does this feature solve?
在双对数坐标下做图，默认显示的 minorSplitline 是5段。比如说  x， y 坐标是 10^1, 10^2, 10^3, 10^4,  也就是在 10^1 到 10^2 之间网格线分开成了 5段，10^2 到 10^3之间也是分开了 5段，中间有 4根网格线； 我希望能设置成 10段，中间有 9根网格线。目前设置 splitNumber:10 不起作用。谢谢！

### What does the proposed API look like?
比如： minorSplitline: { splitNumber: 10 }

**Comment by xiongzm** [comment]
The following image illustrates what I said in the above.

![1544258272](https://user-images.githubusercontent.com/3974899/127089387-6c434389-94ad-42b2-830c-bb468d440ec4.jpg)

**Comment by pissang** [comment]
是设置 `minorTick.splitNumber`

**Comment by xiongzm** [comment]
谢谢 @pissang ! 嗯设置 minorTick.splitNumber = 9， 完美解决！非常感谢！
