### ISSUE TITLE
Can't Map data in Bar chart

### ISSUE THREAD

**Issue by ArunRK-Finsurge** [apache/echarts#15422]
### What problem does this feature solve?
Hi, 

I have an issue with Bar chart with data mapping that series data has [100,202.103,103] and x-axis value ['err', 'sd', 'er','ret'] both are helped map to generate in a bar chart. But the bars are in the same color.

### What does the proposed API look like?
I need that bar graph in different color for each data

**Comment by pissang** [comment]
@ArunRK-Finsurge The coming 5.2.0 will have a `colorBy` option that can do it. See https://github.com/apache/echarts/pull/13788

**Comment by ArunRK-Finsurge** [comment]
@pissang  Thanks for the clarification  :+1: :)
