### ISSUE TITLE
Is there a documentation on how to create custom extensions?

### ISSUE THREAD

**Issue by DanielBogenrieder** [apache/echarts#15420]
### What problem does this feature solve?
We would like to add some custom views/graphs and are wondering if there is any documentation on how to create such custom extensions. Maybe I overlooked it somewhere, but the only thing that I could find was this stackoverflow thread (https://stackoverflow.com/questions/38058791/echarts-js-how-to-create-a-custom-chart-type), where it is stated that you are working on a documentation. As this post is already from 2016 I was wondering if there was something created in the meantime.

Greetings,
Daniel

### What does the proposed API look like?
Create documentation and examples on how to create a custom extension.

**Comment by Ovilia** [comment]
I'm sorry to say that this kind of document cannot be expected in a near future. I would suggest using [custom series](https://echarts.apache.org/en/option.html#series-custom) whose document is very detailed.

**Comment by DanielBogenrieder** [comment]
Thank you very much for your fast answer. I will definitely have a look at the custom series.
