### ISSUE TITLE
坐标轴 名称的 nameTextStyle.padding 设置不生效

### ISSUE THREAD

**Issue by Sneaken** [apache/echarts#15425]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/dreamy-lederberg-3vstv?file=/src/App.js](https://codesandbox.io/s/dreamy-lederberg-3vstv?file=/src/App.js)

### Steps to reproduce
调整 option.yAxis[0].nameTextStyle.padding[0] 或者 option.yAxis[0].nameTextStyle.padding[2] 数值,  可以观察到坐标轴名称无法纵向偏移

### What is expected?
坐标轴 名称 能够纵向偏移

### What is actually happening?
坐标轴 名称 纵向无法偏移

**Comment by ldc-37** [comment]
我也遇到了这个问题，当 nameLocation 为 'start'/'end' 时 nameTextStyle.padding 无法生效。有一个临时的解决方案是配置 nameLocation: 'center' 然后手动写 padding 将 name 移动到需要的位置。

I also met this problem, `nameTextStyle.padding` isn't take effects when set `nameLocation: 'start/end'`. A temporary solution is setting `nameLocation: 'center'` then use `padding` to move `name` to start or end.
