### ISSUE TITLE
雷达图类型定义问题

### ISSUE THREAD

**Issue by crazyair** [apache/echarts#15439]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=radar-custom](https://echarts.apache.org/examples/zh/editor.html?c=radar-custom)

### Steps to reproduce
 ```ts
        const options: EChartsOption = {
            radar: [
                {
                    name: {
                        formatter: '{value}',
                        textStyle: {
                            color: '#72ACD1',
                        },
                    },
                },
            ],
        };
```

### What is expected?
类型正确

### What is actually happening?
类型错误
![image](https://user-images.githubusercontent.com/7971419/127597177-408363d9-ebe4-41ac-8cda-3134b5a22291.png)

**Comment by helgasoft** [comment]
Your code is working. Parameters _formatter_ and _textStyle_ are not documented for [radar name](https://echarts.apache.org/en/option.html#series-radar.name). However, if you use [this example](https://echarts.apache.org/examples/en/editor.html?c=radar-custom) and replace _name_ with your code or the code below, result is correct.
```js
     name: {
         formatter: 'v= {value}',
         textStyle: { color: 'red' },
     },
```
