### ISSUE TITLE
苹果电脑上展示树状图数据量上千时展示的bug

### ISSUE THREAD

**Issue by 1103173426** [apache/echarts#15440]
### Version
5.1.2

### Steps to reproduce
树状图某个节点的子节点数据量上千时会出现

### What is expected?
能正常显示

### What is actually happening?
会显示不出来，出现这个图
![image](https://user-images.githubusercontent.com/26265187/127597774-af873842-4cef-41f7-ac46-880164bf4c80.png)
可能是电脑的gpu不行

**Comment by pissang** [comment]
这个应该是崩溃了，可以把例子发我们下吗？
