### ISSUE TITLE
When the icon of the legend is the LINE type, it is not displayed.

### ISSUE THREAD

**Issue by pengxiaotian** [apache/echarts#15443]
### Version
5.1.2

### Steps to reproduce
legend: {
      icon: 'line'
 }

### What is expected?
I hope there is a detailed icon list

### What is actually happening?
Icon not displayed

**Comment by susiwen8** [comment]
https://echarts.apache.org/en/option.html#legend.icon
`line` isn't in icon types

**Comment by pengxiaotian** [comment]
> https://echarts.apache.org/en/option.html#legend.icon
> `line` isn't in icon types

折线图的默认图例图标的名称叫啥？是内置的？

**Comment by dadazhouRenee** [comment]
@pengxiaotian 
在series 里面配置对应的symbol（[4.X配置地址](https://echarts.apache.org/zh/option.html#series-line.symbol)）

https://github.com/apache/echarts/blob/6d68a7dadbd73ff79831d819e014e859f8b2241a/src/chart/line/LineSeries.ts#L239
