### ISSUE TITLE
echart有办法将热力图改成蜂窝形状嘛

### ISSUE THREAD

**Issue by jtc23** [apache/echarts#15447]
### Version
5.1.2

### Steps to reproduce
将正方形改成蜂窝六边形

### What is expected?
正方形改成蜂窝六边形

### What is actually happening?
以正方型为单元的热力图改成蜂窝六边形为单位

**Comment by pissang** [comment]
参考使用自定义系列 https://echarts.apache.org/examples/zh/editor.html?c=custom-hexbin
