### ISSUE TITLE
Animation not woking

### ISSUE THREAD

**Issue by pradeep199896** [apache/echarts#15456]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/covidrostats-forked-r9kn8?file=/src/App.js](https://codesandbox.io/s/covidrostats-forked-r9kn8?file=/src/App.js)

### Steps to reproduce
1. Using with backgroundStyle property , animation is not rendering  

### What is expected?
Aimation should be erendered

### What is actually happening?
ANimation is not coming

---
Its bit urgent. Can resolve it fast!Thanks

**Comment by pissang** [comment]
I can see the animation. I'm not sure what do you mean by animation not working
