### ISSUE TITLE
Cannot read propery 'master' of undefined

### ISSUE THREAD

**Issue by JESUMH** [apache/echarts#15459]
### Version
5.1.2

### Reproduction link
[https://stackblitz.com/edit/chart-memory-demo?file=src/app/chart-component/chart-component.ts](https://stackblitz.com/edit/chart-memory-demo?file=src/app/chart-component/chart-component.ts)

### Steps to reproduce
Hi,

I'm using apache echarts on angular project (version 12). I have error trace on init grid component. This error has occurred once time but I can't repeat it. You can see echarts option configuration on stackblitz project.

![image](https://user-images.githubusercontent.com/69010346/127826524-5358123e-ed8a-497c-b71e-ef0ab1bf91de.png)

### What is expected?
Not appears echarts errors and show chart.

### What is actually happening?
Not show chart after error.

**Comment by pissang** [comment]
It's hard to reproduce the error. You can check if you are using an instance that has been disposed.
