### ISSUE TITLE
vue3.0 echarts折线图堆叠图 tooltip.trigger = 'axis',提示框不显示，且不触发tooltip的formatter

### ISSUE THREAD

**Issue by lagXkjy** [apache/echarts#15457]
![image](https://user-images.githubusercontent.com/25917166/127815033-3143defd-bbf4-4b09-8c30-12129a33280a.png)
如上图使用官方失利，echarts版本5.1.2。
tooltip.trigger = 'axis'的时候只显示了虚线，不能触发formatter函数，不显示提示框

**Comment by plainheart** [comment]
不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

**Comment by sperains** [comment]
> 不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

牛逼, 就是这个原因

**Comment by Qcheng001** [comment]
> 不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

牛逼，终于解决了！！！

**Comment by AsheLanius** [comment]
流弊!!!!!!!!!!

**Comment by dxlxxx** [comment]
牛逼

**Comment by dxlxxx** [comment]
> 不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

牛逼

**Comment by IrisMagicBox** [comment]
666

**Comment by peipeiyinuo** [comment]
> 不要将echarts实例包装成请求式对象，以防止使用`ref`和`reactive`可以使用`shallowRef`普通变量

太牛了，直击痛点

**Comment by r6hk** [comment]
> 不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

谢谢，爱来自 2025

**Comment by hanchengweb** [comment]
@plainheart 膜拜

**Comment by iwantloveu** [comment]
> 不要将 echarts 实例包装成响应式对象，也就是避免使用 `ref` 和 `reactive`。可以用 `shallowRef` 或者普通变量

牛逼
