### ISSUE TITLE
关系图 高亮时 关联节点 的label 未显示出来

### ISSUE THREAD

**Issue by atguo** [apache/echarts#15458]
### Version
5.1.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=graph-npm](https://echarts.apache.org/examples/zh/editor.html?c=graph-npm)

### Steps to reproduce
选中某个节点

### What is expected?
选中节点的关联节点的label需要显示出来

### What is actually happening?
该节点的关联节点label未显示
![bug](https://user-images.githubusercontent.com/13193919/127821462-b2bb7349-ac99-430a-b041-59ed560b1db1.png)

---
5.x之前的版本是我期望的结果，5.x之后就异常了

**Comment by pissang** [comment]
Related to https://github.com/apache/echarts/issues/14788

**Comment by atguo** [comment]
@pissang thanks
