### ISSUE TITLE
sankey桑基图需要设置每层节点的字体大小从大到小

### ISSUE THREAD

**Issue by liuyang77886** [apache/echarts#15462]
### Version
5.1.2

### Steps to reproduce
```ts
option.series.label: {
                color: 'rgba(0,0,0,0.7)',
                fontFamily: 'Arial',
                fontSize: 10
            }
```
### What is expected?
需要设置不同层的文字

### What is actually happening?
每层的文字一样大

**Comment by pissang** [comment]
可以试试使用 labelLayout 回调函数根据参数返回不同的 fontSize

**Comment by liuyang77886** [comment]
> 可以试试使用 labelLayout 回调函数根据参数返回不同的 fontSize

请给我示例可以吗。我大概理解你的意思，但是不知道怎么使用

**Comment by helgasoft** [comment]
With [labelLayout](https://echarts.apache.org/en/option.html#series-sankey.labelLayout) you can have variable font sizes, but cannot set _color_ or _fontFamily_.
Open [this example](https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap) and replace parameter _labelLayout_ with the following code to see the effect.
```js
    labelLayout(params) {
        return {
           fontSize: Math.max(params.rect.width / 2, 5),
        }
    },
```
