### ISSUE TITLE
柱状图是否支持从最小值开始画，现在柱状图都只能从0开始画

### ISSUE THREAD

**Issue by xzf123456** [apache/echarts#15463]
### Version
5.1.2

### Reproduction link
[https://segmentfault.com/q/1010000015342610](https://segmentfault.com/q/1010000015342610)

### Steps to reproduce
柱状图是否支持从最小值开始画，现在柱状图都只能从0开始画。

### What is expected?
希望柱状图从最小值开始画，如值为-10，最小值为-20，则希望从-20画到-10，而不是现在的0到-10

### What is actually happening?
希望柱状图从最小值开始画，如值为-10，最小值为-20，则希望从-20画到-10，而不是现在的0到-10

**Comment by pissang** [comment]
设置 yAxis.scale 为 true

**Comment by xzf123456** [comment]
> 设置 yAxis.scale 为 true

已设置，并且设置了 xAxis的axisLine: {onZero: false}依旧无效，设置后效果是这样的
![image](https://user-images.githubusercontent.com/58057891/127952165-f8f893b6-ac14-49f3-b02f-99e89e83c8fa.png)

**Comment by quillblue** [comment]
设置`yAxis.min`为`'dataMin'`
Example Option
`
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value',
    min:'dataMin'
  },
  series: [
    {
      data: [-120, 200, 150, 80, 70, 110, 130],
      type: 'bar'
    }
  ]
};
`

Ref: https://echarts.apache.org/en/option.html#yAxis.min
