### ISSUE TITLE
文档中setCanvasCreator的方法说明隐藏了吗？

### ISSUE THREAD

**Issue by missile-xuan** [apache/echarts#15478]
### Version
5.1.2

### Steps to reproduce
null

### What is expected?
null

### What is actually happening?
null

---
在其他node后端项目中 看到了setCanvasCreator的使用
let canvas = new Canvas(500, 500);
  let ctx = canvas.getContext('2d')
  ctx.font = '36px'
  const echarts = require('echarts');
  echarts.setCanvasCreator(function () {
    return canvas;
  })

但是去翻文档没有找到setCanvasCreator的说明

看其他issue #13262
有说到传入canvas 给了文档中后端渲染的地址 饭湿只有几个工具指引

**Comment by Ovilia** [comment]
这个方法不是给一般开发者用的，为避免误用，所以文档中没有提及。理论上只会用于 node、小程序等特殊 canvas 环境。

**Comment by missile-xuan** [comment]
> 这个方法不是给一般开发者用的，为避免误用，所以文档中没有提及。理论上只会用于 node、小程序等特殊 canvas 环境。

原来如此   确实是在node中使用  感谢指点
