### ISSUE TITLE
gauge-ring step gradient in (progress: itemStyle: color and borderColor)

### ISSUE THREAD

**Issue by JustFun2020** [apache/echarts#15471]
### What problem does this feature solve?
-step gradient in color and borderColor attribute

make the color similar to the image below

![65829572-351cb380-e2a7-11e9-882b-29a2b9c04f0e](https://user-images.githubusercontent.com/88413084/128111399-03600391-4489-4746-95b3-055b8fa6a393.png)

![螢幕快照 2021-08-04 上午10 53 53](https://user-images.githubusercontent.com/88413084/128114590-0d765628-6ecf-4963-957b-d5a32f62b5a4.png)

### What does the proposed API look like?
```
progress: {
  itemStyle: {
    borderColor / color: [
      [0.25, new echarts.graphic.LinearGradient('to right', [{
        percentage: 50%,
        color: 'blue'
      }, {
        percentage: 50%,
        color: 'green'
      }])],
      [0.5, new echarts.graphic.LinearGradient('to right', [{
        percentage: 50%,
        color: 'green'
      }, {
        percentage: 50%,
        color: 'yellow'
      }])],
      [0.75, new echarts.graphic.LinearGradient('to right', [{
        percentage: 50%,
        color: 'yellow'
      }, {
        percentage: 50%,
        color: 'orange'
      }])],
      [1, new echarts.graphic.LinearGradient('to right', [{
        percentage: 50%,
        color: 'orange'
      }, {
        percentage: 50%,
        color: 'red'
      }])]
    ]
  }
}
```

**Comment by Ovilia** [comment]
If you want piecewise color steps, please follow the example of https://echarts.apache.org/examples/zh/editor.html?c=gauge-stage . If you want it continuous, ECharts does not support so.
