### ISSUE TITLE
Memory leak leading to browser crash

### ISSUE THREAD

**Issue by kulov** [apache/echarts#15480]
### Version
5.1.2

### Steps to reproduce
Created 40 charts in vue.js SPA each chart consisting of 600 data points.
After period of 1:30h browser crashes with the error below. Using Edge Chromium.
`Error code: Out of memory`
https://snipboard.io/rT5jSf.jpg

Before the crash browser is reporting 4GB of RAM usage.
https://snipboard.io/U0WFvZ.jpg

Below is code excerpt that is used to chart data. 
New data is coming every 3 seconds.

`
      this.chartCatgories.map((cc) => {
        cc.metrics.map((mtr) => {
          const metricsById = newMetrics.filter((nm) => {
            return (
              nm.id == mtr.text && nm.e == cc.endpoint
            );
          });
`

Credentials to publicly accessible environment can be provided.

### What is expected?
stable and running browser

### What is actually happening?
browser is crashing

**Comment by kulov** [comment]
Here are some F12 Allocation profiler results:

![image](https://user-images.githubusercontent.com/939355/128250170-e03469fe-847b-4ce7-916d-cb2554c591c1.png)

![image](https://user-images.githubusercontent.com/939355/128250414-9255c4f2-dfd0-48fa-9da4-65bb169ef26a.png)

![image](https://user-images.githubusercontent.com/939355/128250496-54ad1880-d6d6-45f9-a914-9b19d031ade7.png)

![image](https://user-images.githubusercontent.com/939355/128250571-0c6917ab-f5e9-4918-aad7-016a3aaa4a69.png)

![image](https://user-images.githubusercontent.com/939355/128250704-9ed5ed82-6023-4d7b-b92d-982e23f5a213.png)

**Comment by kulov** [comment]
![image](https://user-images.githubusercontent.com/939355/128252118-80119cf0-7fea-46e8-a8b7-550bb9b171c2.png)

Data bound to echart is json array. 
What is the best way to bind data to echart and then release the json array?

**Comment by pissang** [comment]
@kulov Hi, do you mind providing a simple demo that can reproduce the memory leaking issue?

**Comment by kulov** [comment]
Dear Yi,

I can provide credentials to the production system and parts of the source code in a private message.

We are now looking at the opportunity to improve the instantiation of echarts within vue.
Please see existing code excerpt below:

`
      <ui-grid
        class="chart-category align-items-center"
        v-for="category in chartCategories"
        :key="category.endpoint"
      >
`
and setting data using

`
      this.chartCategories.map((cc) => {
        cc.metrics.map((mtr) => {
...
          mtr.oneData = graphData;
        });
      });
`

**Comment by kulov** [comment]
Issue was resolved by fixing the way vue.js instantiates echart objects.
The original implementation seemed to be instantiating echarts objects on each data bind.
New implementation is working with object references and setOptions.
Memory and CPU are now stable.
![image](https://user-images.githubusercontent.com/939355/128646285-ac9e3a38-ac91-4955-97fe-af52c39a11f7.png)

Thank you!

**Comment by Ovilia** [comment]
Glad you found the solution. I'm going to close this.
