### ISSUE TITLE
取消鼠标点击的默认行为，例如旭日图的最外层，改为自己需要的行为

### ISSUE THREAD

**Issue by kongku** [apache/echarts#15491]
### What problem does this feature solve?
有时候并不需要默认的鼠标行为，在点击图表的时候，根据事件处理函数中params的数据，执行我所需要的逻辑，例如旭日图，我只想显示4层，但是有的多于4层，这时候，我把多于4层的数据不放在children中，放到其他属性extra中，在点击事件中判断出是第四层时候，需要取消原来的数据下钻的行为，并判断extra中有数据，我就把整个旭日图series中的data改为extra的数据；当我点击空白时（getZr().on），并判断出现在显示的是extra中的数据，我就让series中的data还原为原来的；

### What does the proposed API look like?
能提供一个接口，在捕捉事件处理函数中，取消图表原来的默认行为。

**Comment by Ovilia** [comment]
[nodeClick](https://echarts.apache.org/zh/option.html#series-sunburst.nodeClick) set to be false and use `chart.on(...)` to listen to events.
