### ISSUE TITLE
visualMap line is the wrong color

### ISSUE THREAD

**Issue by foxitdog** [apache/echarts#15495]
### Version
5.1.2

### Steps to reproduce

    myChart.setOption(option = {
    "xAxis": {
        "type": "category",
        "data": [
            "2021-08-08 10:46:53",
            "2021-08-08 10:47:53",
        ]
    },
    "yAxis": {
        "type": "value",
    },
    "series": [
        {
            "type": "line",
            data:[25,50],
        }
    ],
    "visualMap": {
        "pieces": [
             {
                "lte": 50,
                "color": "black"
            },
            {
                "gt": 50,
                "lte": 55,
                "color": "red"
            },
            {
                "gt":55,
                "color": "yellow"
            },
           
        ],
    }
});

### What is expected?
I want black

### What is actually happening?
yellow

**Comment by plainheart** [comment]
We've fixed this bug in #15416. Please wait for the next release 5.2.0.
