### ISSUE TITLE
react写的echarts组件在同一个页面中如何多次调用？

### ISSUE THREAD

**Issue by Youmyin** [apache/echarts#15492]
### Version
5.1.2

### Reproduction link
https://codesandbox.io/s/strange-cannon-08qyj?file=/src/App.tsx

### Steps to reproduce
写了一个piechart组件，在页面中调用了两次，但是只有最后一次是正常显示的，之前的图表不显示。因为要调用dispose函数来销毁之前的实例，否则会疯狂告警There is a chart instance already initialized on the dom.但是使用了dispose就会销毁前一个渲染出来的饼图。那么我该如何区分这两个饼图实例呢？ echarts.init（）是根据id来实例化的，用id不行，找的其他解决办法是用ref，也不行， 我该如何确保dispose的是当前的饼图实例而不是前面渲染的饼图实例。

也许我表达有点混乱，总之就是我调用这个组件能同时显示这两个饼图，data改变两者能同时刷新，并且没有告警There is a chart instance already initialized on the dom.

### What is expected?
所有饼图能同时展示，并且没有刷屏告警

### What is actually happening?
只能显示最后一个饼图

**Comment by juzhiyuan** [comment]
Maybe you could create multi instances?

**Comment by kongmoumou** [comment]
Please put `echarts.init` inside `useEffect` or `useLayoutEffect`, render function may call multiple times so ur chart init again and again.

```js
// pie.tsx
useEffect(() => {
    if (pieRef.current) {
      waterChart = echarts.init(pieRef.current);
      waterChart.setOption(option);
    }
  }, [])
```

**Comment by Youmyin** [comment]
> Please put `echarts.init` inside `useEffect` or `useLayoutEffect`, render function may call multiple times so ur chart init again and again.
> 
> ```js
> // pie.tsx
> useEffect(() => {
>     if (pieRef.current) {
>       waterChart = echarts.init(pieRef.current);
>       waterChart.setOption(option);
>     }
>   }, [])
> ```

Thank you! I get no warning, but all the data on the pie chart has become 0. If I use data as a dependent parameter of useEffect, the data can be displayed normally, but warning: There is a chart instance already initialized on the dom. If I add dispose function, it's the problem I mentioned above again.

Option is put in useEffect, I put all the operations of generating the chart in useEffect:

useEffect(() => {
    let option = {........};
    if (pieRef.current) {
        pieChart = echarts.init(pieRef.current);
        pieChart.setOption(option);
    }
},[data])


Or can you take a look at my repo link?

**Comment by kongmoumou** [comment]
try this

```js
useEffect(() => {
  let option = {........};
  if (pieRef.current) {
    const pieChart = echarts.getInstanceByDom(pieRef.current) || echarts.init(pieRef.current);
    pieChart.setOption(option);
  }
},[data])
```

**Comment by Youmyin** [comment]
> ```js
> echarts.getInstanceByDom(pieRef.current) ||
> ```

It works!! thank you sooo much!!!
