### ISSUE TITLE
Echarts graph type charts show emphasis incorrectly when hover on legends

### ISSUE THREAD

**Issue by zyzstat** [apache/echarts#15507]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=graph](https://echarts.apache.org/examples/zh/editor.html?c=graph)

### Steps to reproduce
Hover on legends

### What is expected?
Legends focus on the current category

### What is actually happening?
Totally wrong parts of chart have been filtered

**Comment by susiwen8** [comment]
sorry, duplicate issue. going to close it

**Comment by susiwen8** [comment]
#13869

**Comment by zyzstat** [comment]
Thank you~
