### ISSUE TITLE
5.1.2地理坐标系和地图系列的 SVG 底图,vue中引入本地svg无法加载

### ISSUE THREAD

**Issue by litterBlackSnake** [apache/echarts#15503]
### Version
5.1.2

### Steps to reproduce
<template>
  <div
    style="width: 500px; height: 500px; background-color: sandybrown"
    ref="main"
  ></div>
</template>
<script>
import * as echarts from 'echarts';
export default {
  data() {
    return {};
  },
  mounted() {
    this.mapCharts();
  },
  methods: {
    mapCharts() {
      var myecharts = echarts.init(this.$refs.main);
      // var svg1 = "https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/data/asset/geo/Beef_cuts_France.svg";
      var svg1 = "../assets/one/Beef_cuts_France.svg";

      $.get(svg1, function (svg) {
        echarts.registerMap("Beef_cuts_France", { svg: svg });
        let option = {
          tooltip: {},
          geo: {
            map: "Beef_cuts_France",
          },
        };
        myecharts.setOption(option);
      });
    },
  },
};
</script>
<style lang="less" scoped>
</style>

### What is expected?
引入本地svg可以成功渲染
![image](https://user-images.githubusercontent.com/31761060/128844432-d74bbbc7-8ad4-47dd-a848-9da4dda02b30.png)

### What is actually happening?
无法渲染报错
![image](https://user-images.githubusercontent.com/31761060/128844358-b27721af-8058-4375-bc11-d2ab001f9bcf.png)

**Comment by plainheart** [comment]
应该是引用的本地 SVG 地址不对。请再仔细检查看看。
