### ISSUE TITLE
custom chart is wrong

### ISSUE THREAD

**Issue by YYL1999** [apache/echarts#15505]
### Version
5.0.2

### Steps to reproduce
l use renderItem to draw custom chart and but  return graphic is not support left/right

### What is expected?
renderItem(graphic) is support left/right

### What is actually happening?
left/right is wrong

**Comment by YYL1999** [comment]
https://www.makeapie.com/editor.html?c=x0AfLP0bVR&v=1

**Comment by Ovilia** [comment]
Hi, it seems customs series do not have `left` or `right` but `x` and `y`. Please follow [the document](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_group.x) for more details.

**Comment by YYL1999** [comment]
> Hi, it seems customs series do not have `left` or `right` but `x` and `y`. Please follow [the document](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_group.x) for more details.

yeah! thanks!

**Comment by Ovilia** [comment]
You could start with rect rather than group to see if it works.
