### ISSUE TITLE
ARIA Decals don't differentiate between up and down candlestick chart candles

### ISSUE THREAD

**Issue by nick-true-dev** [apache/echarts#15511]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/jolly-bell-jnxtx?file=/src/index.js](https://codesandbox.io/s/jolly-bell-jnxtx?file=/src/index.js)

### Steps to reproduce
make sure your candlestick chart has the following aria configuration properties:

```
option = {
  aria: {
    enabled: true,
    decal: { show: true }
  },
  ...
}
```

### What is expected?
the green candles will have a different decal pattern than the red candles to help people differentiate between the two colored candle types

### What is actually happening?
the entire candlestick series uses a single decal pattern

---
Thanks for looking into this!

EDIT: format code block

**Comment by Ovilia** [comment]
Hi, it is adviced to use empty and non-empty rectangles for candlestick rather than decal to differentiate with candlestick.
