### ISSUE TITLE
themeriver图中，目前只能显示正值。能否增加一个功能，若值为负值时以另一种颜色(或反色)显示？

### ISSUE THREAD

**Issue by aswjh** [apache/echarts#15515]
### What problem does this feature solve?
现在的版本若有值为负，会影响河流的正常宽度。
负值的情况可应用在某些变化率的显示中，比如某数据前2分钟是增量，后2分钟是减量（负值），以现在的方式无法区分。

### What does the proposed API look like?
none

**Comment by Ovilia** [comment]
目前没有明确的这方面需求，这可能会带来很多其他的问题，比如和其他数据的堆叠应该表现为什么样，对于观众来说是否能直观地理解为负值等等。所以目前没有计划开发通用性质的负值主题河流图，如果有需求的话，可以通过自定义系列实现。

**Comment by aswjh** [comment]
和其它数据的区分确实有点麻烦，目前设想是用opacity或者覆盖一道灰色痕迹，那我自定义试试。感谢指点。
