### ISSUE TITLE
According to the official example, an error is reported after introducing the corresponding components as needed.

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#15514]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/embed/magical-dew-r7jyd?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/magical-dew-r7jyd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
According to the official example, an error is reported after introducing the corresponding components as needed.

### What is expected?
Normal operation

### What is actually happening?
An error occurred

---
The error disappears after the full quantity is introduced

**Comment by plainheart** [comment]
It needs to install `TransformComponent` if you are using dataset transforming.

```ts
import {
    DatasetComponent,
    TransformComponent
} from "echarts/components";

echarts.use([DatasetComponent, TransformComponent]);
```

I think this should be mentioned especially in the documentation and example page.

**Comment by ZXYT** [comment]
@plainheart Thanks, it seems to work.

**Comment by ZXYT** [comment]
![image](https://user-images.githubusercontent.com/27613553/129159798-bcce6b77-1c17-4b06-8ad0-86ebb7ebd2dc.png)
There's a problem here. How can I fix it.

**Comment by ZXYT** [comment]
@pissang Ok, thanks。

**Comment by ZXYT** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=data-transform-multiple-pie
This problem also arises here.

**Comment by plainheart** [comment]
Thanks. All examples with data-transform have the same issue.
