### ISSUE TITLE
echarts5的sankey图的文字默认有白边，echarts4没问题

### ISSUE THREAD

**Issue by liuyang77886** [apache/echarts#15537]
### Version
5.1.2

### Steps to reproduce
官方例子就能看见

### What is expected?
不需要默认增加文字白边

### What is actually happening?
文字默认有白边

---
或者我如何去掉文字的白边

**Comment by Ovilia** [comment]
ECharts 5 开始对深色背景下的文字默认加了白边，如果要去掉的话，`borderColor` 设为 `'none'` 即可。

**Comment by liuyang77886** [comment]
> ECharts 5 开始对深色背景下的文字默认加了白边，如果要去掉的话，`borderColor` 设为 `'none'` 即可。

我在textStyle，itemStyle，label，levels下都加borderColor :'none'还是有白边，请举例可以吗

**Comment by liuyang77886** [comment]
你好！
 我在textStyle，itemStyle，label，levels下都加borderColor :'none'还是有白边，请举例可以吗
















在 2021-08-16 11:59:18，"Wenli Zhang" ***@***.***> 写道：

ECharts 5 开始对深色背景下的文字默认加了白边，如果要去掉的话，borderColor 设为 'none' 即可。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by plainheart** [comment]
这里有对 v5 版本引入的 label 在深色背景下默认描边特性的解释，可以通过手动设置 label color 来避免默认行为。
https://github.com/apache/echarts/issues/15347#issuecomment-880361896
