### ISSUE TITLE
label支持skew吗

### ISSUE THREAD

**Issue by Carolineliu** [apache/echarts#15536]
### Version
5.1.2

### Steps to reproduce
1.label(rich)支持skew属性吗
2.如果不支持，可以知道graph每个node的屏幕坐标吗

### What is expected?
5.1.2echarts开始支持skew属性，但并没有具体文档，不知道lable可否支持skew

### What is actually happening?
目前使用无作用

**Comment by plainheart** [comment]
目前上层的 ECharts 暂未暴露该属性。

**Comment by Carolineliu** [comment]
> 目前上层的 ECharts 暂未暴露该属性。但是感觉可以考虑增强下。
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/26999792/129524842-f3737988-2778-46ab-8d30-947911c3600a.png">

那我可以知道graph每个节点的位置吗，我想通过css，把label显示上去

**Comment by plainheart** [comment]
可以试试用 [`echartsInstance.convertToPixel`](https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel) 将其转换为实际像素坐标。

**Comment by Carolineliu** [comment]
> 可以试试用 [`echartsInstance.convertToPixel`](https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel) 将其转换为实际像素坐标。

好的，谢谢
