### ISSUE TITLE
On clicking treemap block , its get moved to right.

### ISSUE THREAD

**Issue by Monali-ITT** [apache/echarts#15531]
### Version
4.4.2

### Steps to reproduce
Execute treemap
Output get displayed.
Click on any block , output get moved to right.

### What is expected?
It should not move treemap output to right.

### What is actually happening?
Its moving treemap output to right.

---
https://echarts.apache.org/examples/en/editor.html?c=treemap-disk

**Comment by susiwen8** [comment]
Well, This not a bug.  It' moving to the center of canvas.
