### ISSUE TITLE
数据量的大小是否会影响缓动动画？

### ISSUE THREAD

**Issue by czwlucky** [apache/echarts#15530]
我生成了一个折线图，当数据量超过一定数量，比如10000个数据时，缓动动画就失效了，直接就绘制出来图形，当数量不大时，比如1000个数量，动画效果还是有的。

// 基于准备好的dom，初始化echarts实例
const waveChart = echarts.init('chartDiv');
// 指定图表的配置项和数据
const travelingOption = {
    title: {
        left: 'center',
        text: ‘XXXX’
    },
    tooltip: {
        trigger: 'axis'
    },
    xAxis: {
        type: 'category',
        data: xAxis
    },
    yAxis: {
        type: 'value'
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    series: [{
        data: value, // 这里的value长度如果很大，比如有10000个数据时，就没有动画效果了，图形直接就绘制出来了
        showSymbol: false,
        type: 'line',
        smooth: true
    }],
    grid: {
        left: '5%',
        right: '4%',
    },
    dataZoom: [
        {
            type: 'slider',
            xAxisIndex: 0,
            filterMode: 'none'
        },
        , {
            show: true,
            type: 'inside',
            filterMode: 'none',
            yAxisIndex: [0]
        }
    ],
}

// 使用刚指定的配置项和数据显示图表。
waveChart.setOption(travelingOption)

**Comment by plainheart** [comment]
可以设置 [`animationThreshold`](https://echarts.apache.org/zh/option.html#animationThreshold)， 默认为 `2000`。
