### ISSUE TITLE
when heat-map data count over 2500+ (x.length * y.length > 2500+), high light block will cover the label

### ISSUE THREAD

**Issue by fulldo** [apache/echarts#15543]
### Version
5.1.2

### Reproduction link
[https://codepen.io/zzfgood/pen/GRmaRWm](https://codepen.io/zzfgood/pen/GRmaRWm)

### Steps to reproduce
for example: https://codepen.io/zzfgood/pen/GRmaRWm

when hover on the heat-map data block, label text will be cover by high light

### What is expected?
high light block will not cover the label

### What is actually happening?
high light block cover the label

**Comment by Ovilia** [comment]
![image](https://user-images.githubusercontent.com/779050/129672453-92a52e57-277e-4cd2-b225-5da577edf5bf.png)
It seems all right?

**Comment by zzfGood** [comment]
> ![image](https://user-images.githubusercontent.com/779050/129672453-92a52e57-277e-4cd2-b225-5da577edf5bf.png)
> It seems all right?

let the x/y length bigger, try again

you can also see this image: 
![knk_2021-08-17  14-17-02](https://user-images.githubusercontent.com/19745059/129673687-46c7e2f6-9f18-46f6-b73d-e9d575f168ed.jpg)

**Comment by zzfGood** [comment]
> > ![image](https://user-images.githubusercontent.com/779050/129672453-92a52e57-277e-4cd2-b225-5da577edf5bf.png)
> > It seems all right?
> 
> @Ovilia let the x/y length bigger, try again
> xMax=50 * yMax=50, not cover
> but, xMax=54 * yMax=50, covered
> 
> you can also see this image:
> ![knk_2021-08-17 14-17-02](https://user-images.githubusercontent.com/19745059/129673687-46c7e2f6-9f18-46f6-b73d-e9d575f168ed.jpg)

Hi, @Ovilia , Is there any progress on this issue?

Is there any echarts configuration that can solve my confusion?
