### ISSUE TITLE
在3D 路径图 上标点，点显示不完整

### ISSUE THREAD

**Issue by yang201806** [apache/echarts#15541]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=lines3d-flights-gl&gl=1](https://echarts.apache.org/examples/zh/editor.html?c=lines3d-flights-gl&gl=1)

### Steps to reproduce
官网示例：https://echarts.apache.org/examples/zh/editor.html?c=lines3d-flights-gl&gl=1

在series属性中添加：
{
    type: 'scatter3D',
    coordinateSystem: 'geo3D',
    symbolSize:20,
    itemStyle:{
        color:'#fa0202',
    },
    data:[[-90,40],[-70,-40]]
}

图中点显示不完整，陆地对点有遮挡。这个问题有该如何解决

### What is expected?
图中点可以完整显示出来

### What is actually happening?
图中点显示不完整

**Comment by helgasoft** [comment]
This has not been fixed yet in GL.  Workaround is to add an invisible 3D reference point. 
In the _series_ property add:
```
      ,{
        type: 'scatter3D',
        coordinateSystem: 'geo3D',
        symbolSize: 0,  // add invisible reference point
        data:[[0,0,0]]  // with altitude = 0
      }
      ,{
        type: 'scatter3D',
        coordinateSystem: 'geo3D',
        symbolSize: 20,
        itemStyle:{ color:'#fa0202' },
        data:[[-90,40,1], [-70,- 40,2]]   // add altitude>0 on all points
      }
```
see also [related problem](https://github.com/ecomfe/echarts-gl/issues/432).
![image](https://user-images.githubusercontent.com/13038071/171529416-c15e98fa-f316-44a4-b073-1b6e8279fc89.png)
