### ISSUE TITLE
柱状图实现方波效果

### ISSUE THREAD

**Issue by gldsujt** [apache/echarts#15551]
### What problem does this feature solve?
有多个0/1的开关变量，能否用柱状图实现，效果为在一个竖轴上有多条柱，0/1为不同颜色交替，这个怎么实现？

### What does the proposed API look like?
无

**Comment by susiwen8** [comment]
给每个 item 设置不同的颜色？
https://echarts.apache.org/zh/option.html#series-bar.data.itemStyle.color

**Comment by gldsujt** [comment]
> 给每个 item 设置不同的颜色？
> https://echarts.apache.org/zh/option.html#series-bar.data.itemStyle.color

可以两种颜色交替，但是开关量为0的时候没有柱体延伸，这样的话不就只有为1的值一直堆叠了么

**Comment by gldsujt** [comment]
> 给每个 item 设置不同的颜色？
> https://echarts.apache.org/zh/option.html#series-bar.data.itemStyle.color

可以两种颜色交替，但是开关量为0的时候没有柱体延伸，这样的话不就只有为1的值一直堆叠了么

**Comment by susiwen8** [comment]
可以给把开关量0和1设置为同一个值用来画图，这个值是无意义的，然后对 label 和 tooltip 进行 formatter, 判断哪些柱子是 0 或者 1

**Comment by gldsujt** [comment]
> 可以给把开关量0和1设置为同一个值用来画图，这个值是无意义的，然后对 label 和 tooltip 进行 formatter, 判断哪些柱子是 0 或者 1

懂了，谢谢，我还有个小疑问，能否在tooltip的自定义悬浮窗函数formatter中获取一些全局的数据变量？

**Comment by susiwen8** [comment]
只能获取它提供给你的参数。
