### ISSUE TITLE
Display negative value in Logarithmic axis

### ISSUE THREAD

**Issue by NiantongDong** [apache/echarts#15558]
### What problem does this feature solve?
In real life, we can find some value that may break the limit of logarithmic value. In the current version, we cannot show any value in the log axis which is negative

### What does the proposed API look like?
axis.min: negative

**Comment by 100pah** [comment]
What the graph like do you expect when the value is negative on logarithmic axis?

**Comment by NiantongDong** [comment]
What I want to do is to use the log1p y-axis to represent the certain stock return rate. The rate may be negative and keep going down. If I use type 'log' in echarts, it will not show any value less than 0.  If I use type 'value', the graph is incorrect. The idea is that the rate is calculated by Math.log1p(x) and the y-axis value should also be calculated Math.exp(y) so that it can show the correct plot for each value. Here is an example graph I generated using Juptyer and matplotlib.
![download](https://user-images.githubusercontent.com/34298280/130501060-8533352a-31cc-4f3e-81e3-b736d9e3e9f9.png)
