### ISSUE TITLE
Calendar Heatmap series label does not show

### ISSUE THREAD

**Issue by ataft** [apache/echarts#15556]
### Version
5.1.2

### Reproduction link
[https://codepen.io/ataft/pen/MWmMqXW](https://codepen.io/ataft/pen/MWmMqXW)

### Steps to reproduce
See the CodePen example

### What is expected?
Calendar series labels should be shown for the heatmap

### What is actually happening?
Calendar series labels are not shown for the heatmap, but are shown for the scatter

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap Please refer to this demo

**Comment by ataft** [comment]
Add series.label.show = true to this example and you'll see what I mean. There's no label, just a "-"

```
label: {
  show: true
},

```

![image](https://user-images.githubusercontent.com/11670864/130171699-799b4993-6357-4c49-be63-c1209e20255a.png)

**Comment by susiwen8** [comment]
@ataft try `formatter`
```js
        label: {
            show: true,
            formatter(e) {
                console.log(e)
                return e.data[1]
            }
        }
```

**Comment by ataft** [comment]
Confirmed, the `formatter: (e) => e.data[1]` logic works for scatter, heatmap, and effectScatter types.
