### ISSUE TITLE
echartsInstance. clear 无法清空series中设置的lines

### ISSUE THREAD

**Issue by qingbinyang** [apache/echarts#15568]
### Version
4.9.0

### Steps to reproduce
el-dialog 中定义echarts组件，每次打开弹窗更新options，echarts组件中监听options值变化，每次options改变时首先调用echartsInstance. clear() 再赋值options。
当第一设置options为地图，series中带有lines属性数据，当更新options数据后，地图数据被清楚，但是lines 依然存在。

### What is expected?
清空画布

### What is actually happening?
画布未清空

![image](https://user-images.githubusercontent.com/42060739/130209775-dca736d0-f1eb-42ae-b3b7-50f4a049732d.png)

**Comment by plainheart** [comment]
#15088 应该解决了这个问题，不过包含在 5.2.0 里，还没正式发布。
