### ISSUE TITLE
Echarts graph force update node problem. Echart力导图节点更新问题。

### ISSUE THREAD

**Issue by MerlinTalrasha** [apache/echarts#15560]
### What problem does this feature solve?
Use Echarts graph force, when i click node and save change, echarts always reload, then i can't find changes immediately.

力导图数据变化的时候，有办法只更新变化的节点吗？每次数据变化，力导图重新渲染，位置重新随机了，没法立即定位到修改的节点。

### What does the proposed API look like?
localRefresh

**Comment by Ovilia** [comment]
不行，因为力导图会根据“力”重新计算位置

**Comment by MerlinTalrasha** [comment]
> 不行，因为力导图会根据“力”重新计算位置

谢谢，只能重新考虑其他方案了
