### ISSUE TITLE
在给定xAxis的离散数据后，如何自定义axisLabel的显示格式？

### ISSUE THREAD

**Issue by Youmyin** [apache/echarts#15565]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/friendly-shtern-r1mju?file=/src/App.tsx](https://codesandbox.io/s/friendly-shtern-r1mju?file=/src/App.tsx)

### Steps to reproduce
我的x轴数据是category类型的，是以YYYY-MM-DD HH:mm格式显示的日期

需求：
1、我要显示24小时以内的数据，但是日期格式太长，因此我想要在坐标轴显示成HH:mm形式，但是tooltip中依然能以YYYY-MM-DD HH:mm的格式显示

2、x轴label之间的间隔隔一个小时，但是现在给我隔了6个小时，如果设置interval:1,
那么label会重叠

### What is expected?
1、xAixs的label能够以HH:mm的格式显示，toolTip中以YYYY-MM-DD HH:mm的格式显示x轴数据

2、xAxis的label显示的间隔为1小时

### What is actually happening?
无法以HH:mm的格式显示xAxis的label,并且xAxis的label显示不全

**Comment by susiwen8** [comment]
https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter
