### ISSUE TITLE
ECharts 中支持的图表行为 highlight 不能高亮多个系列吗

### ISSUE THREAD

**Issue by yang201806** [apache/echarts#15577]
### Version
5.0.2

### Steps to reproduce
官网文档如下

// 如果要高亮系列：
dispatchAction({
    type: 'highlight',

    // 用 index 或 id 或 name 来指定系列。
    // 可以使用数组指定多个系列。
    seriesIndex?: number | number[],
    seriesId?: string | string[],
    seriesName?: string | string[],

    // 数据项的 index，如果不指定也可以通过 name 属性根据名称指定数据项
    dataIndex?: number | number[],
    // 可选，数据项名称，在有 dataIndex 的时候忽略
    name?: string | string[],
});

我测试也下
dispatchAction({
    type: 'highlight',
    seriesName:["系列1","系列2"]
});

### What is expected?
预期：系列1和系列2都高亮

### What is actually happening?
只有 “系列2” 高度了

**Comment by Ovilia** [comment]
highlight 语义上表示鼠标引起的高亮，所以逻辑上并不支持多个系列高亮。如果有这个需求，可以监听鼠标事件，然后通过 setOption 把相应系列设为高亮。

**Comment by plainheart** [comment]
我补充一下：有个 PR #15207 修复了这个"bug"。
