### ISSUE TITLE
borderWidth and borderColor in the tree chart doesn't work

### ISSUE THREAD

**Issue by ammmmmms** [apache/echarts#15578]
### Version
5.1.2

### Reproduction link
[https://jsfiddle.net/zhtk7mw1/](https://jsfiddle.net/zhtk7mw1/)

### Steps to reproduce
In tree chart, I want to set borderColor without filling color, but setting borderColor did not work, and then found that the value of color will be regarded as borderColor

```
var option = {
  series: [{
    type: "tree",
    data: [{
      name: "root",
      children: [{
        name: "Child A",
        children: [{
          name: "Leaf C"
        }, {
          name: "Leaf D"
        }, {
          name: "Leaf E"
        }, {
          name: "Leaf F"
        }]
      }, {
        name: "Child B",
        children: [{
          name: "Leaf G"
        }, {
          name: "Leaf H"
        }]
      }, {
        name: "Child D"
      }, {
        name: "Child F",
        children: [{
          name: "Leaf J"
        }, {
          name: "Leaf K"
        }]
      }]
    }],
    label: {
      position: "right"
    },
    itemStyle: {
    	color: "rgba(225, 99, 99, 1)",
      borderColor: "rgba(111, 238, 26, 1)",
      borderWidth: 2
    }
  }]
}
```

### What is expected?
need the same effect as in V4

### What is actually happening?
set borderColor and borderWidth in tree chart will be work

**Comment by Ovilia** [comment]
This is not a bug. This is because the default [symbol](https://echarts.apache.org/en/option.html#series-tree.symbol) is `'emptyCircle'`. You can set it to be `'circle'` and it will use `color` as filling color.

**Comment by ammmmmms** [comment]
> This is not a bug. This is because the default [symbol](https://echarts.apache.org/en/option.html#series-tree.symbol) is `'emptyCircle'`. You can set it to be `'circle'` and it will use `color` as filling color.

thanks for your answer

**Comment by ammmmmms** [comment]
> This is not a bug. This is because the default [symbol](https://echarts.apache.org/en/option.html#series-tree.symbol) is `'emptyCircle'`. You can set it to be `'circle'` and it will use `color` as filling color.

I just tried it，but I still have a little doubt. the tree node can't show the collapsing and expansion state color when I set the symbol to 'circle'， and `color` does not seem to support callback functions like this ` (params: Object) => Color`， is there any other way to make the `borderColor` work？
