### ISSUE TITLE
Custom tooltip with formatter option looks weird

### ISSUE THREAD

**Issue by liuyuan22** [apache/echarts#15584]
### Version
4.8.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xq137jH_Ko](https://www.makeapie.com/editor.html?c=xq137jH_Ko)

### Steps to reproduce
1. open https://www.makeapie.com/editor.html?c=xq137jH_Ko
2. move your cursor into the chart, then you will see the tooltip

### What is expected?
The tooltip content should be ```6<V≤121```

### What is actually happening?
The tooltip content is ```6```

**Comment by susiwen8** [comment]
<img width="379" alt="Screen Shot 2021-08-23 at 11 14 27 PM" src="https://user-images.githubusercontent.com/20318608/130472315-2e4f47ef-64bf-4c70-8c74-8d054a6a2f03.png">

Workaround

```js
                tooltip: {
                    show: true,
                    trigger: 'axis',
                    formatter: () => '6&lt;V≤121'
                },
```

**Comment by plainheart** [comment]
Since ECharts supports the pure HTML string in the formatter, if it contains HTML tags or any other special characters and you hope to display them originally, please manually escape it first. Refer to these comments in #14434 and #14429 for the detailed disscusion.

**Comment by liuyuan22** [comment]
> Since ECharts supports the pure HTML string in the formatter, if it contains HTML tags or any other special characters and you hope to display them originally, please manually escape it first. Refer to these comments in #14434 and #14429 for the detailed discussion.
> 
> To make it simpler, you could use the provided built-in util `echarts.format.encodeHTML`.

Thanks! Now I get it~
