### ISSUE TITLE
<image> tags in Geo SVGs are not loading

### ISSUE THREAD

**Issue by sioh89** [apache/echarts#15597]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/echarts-geo-map-with-image-wfvvn?file=/src/index.js](https://codesandbox.io/s/echarts-geo-map-with-image-wfvvn?file=/src/index.js)

### Steps to reproduce
1. Register map using an svg that contains an `<image>` tag where the href property is a url
2. Set option with a heatmap series with `{ coordinateSystem: "geo" }`

### What is expected?
Expect to see heatmap points rendered on top of the image in the svg similar to this: ![this](https://user-images.githubusercontent.com/31019433/130686038-e62f724b-da71-4ebd-8a36-52803d2935b5.png)

### What is actually happening?
The data points are being plotted correctly, but the `<image>` is not being loaded.

---
Our team is considering migrating to Echarts. We'd love to be able to plot the heatmap series on some map images and have that image scale and translate according to the chart's zoom level using the `{ roam: true }` option. The data points represent coordinates associated with the map image. These maps are stored as png files in our server and not as an asset in the frontend because the available map images are dynamic.

Here is an abstracted example that is similar to our codebase: https://codesandbox.io/s/echarts-geo-map-with-image-wfvvn?file=/src/index.js

I thought maybe the problem is that the svg is being drawn onto the canvas before the image is done loading so I tried registering the map after load. That didn't work either. Example: https://codesandbox.io/s/echarts-geo-map-with-image-registermap-after-image-load-iq1wn

**Comment by plainheart** [comment]
As a workaround, you could use the `xlink:href` attribute to avoid this issue. 
```js
svgimg.setAttribute("xlink:href", HREF);
```
https://github.com/ecomfe/zrender/blob/master/src/tool/parseSVG.ts#L482
