### ISSUE TITLE
最新版本的配置项series-line.markPoint.data. symbolOffset 无效。

### ISSUE THREAD

**Issue by dignfei** [apache/echarts#15596]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-line.markPoint.data.symbolOffset](https://echarts.apache.org/zh/option.html#series-line.markPoint.data.symbolOffset)

### Steps to reproduce
1.打开https://echarts.apache.org/zh/option.html#series-line.markPoint.data.symbolOffset，
2.点击试一试，修改x或y的值，图形不会变化。本来应该有变化的

### What is expected?
5.0版本时，配置项series-line.markPoint.data. symbolOffset 有效，而5.1.2版本这个配置就失效了

### What is actually happening?
配置项失效了

**Comment by plainheart** [comment]
#14737 has fixed this bug. Please wait for the coming version 5.2.0.
