### ISSUE TITLE
wrong value and placement for markPoint on stacked bar series

### ISSUE THREAD

**Issue by Georges67** [apache/echarts#15591]
### Version
5.0.2

### Steps to reproduce
Create some bar series with parameter : stack= 'all'.
Try to use markPoint on them with following parameter :
markPoint: {data: [ {name: 'Inbound', type: 'max'}] } 

### What is expected?
We should show a markpoint on each maximum value of each series

### What is actually happening?
The markpoints are all placed on same stacked bar, that dosen't represent the maximum value of each serie

---
The markpoint works well for 'normal' line and bar series but not on stacked bars ( stack: 'all', ).

**Comment by Atlas-lili** [comment]
I'm interested in fixing this issue.

**Comment by Atlas-lili** [comment]
I tried to reproduce the problem.It seems that the max mark point will mark the max value of each series after summary in the stack chart. The behavior of bar and line is similar.
https://codepen.io/Atlas-lili/pen/LYzKLvR
