### ISSUE TITLE
升级5.1版本后，点击还原按钮图消失了 （toolbox：feature：restore）

### ISSUE THREAD

**Issue by yrx0823** [apache/echarts#15607]
`<script>
import macarons from '@json/macarons.json'
import echarts from 'echarts'
export default {
  props: ['line_data', 'is_open'],
  data() {
    return {
      chart: null,
      options: {
        color: ['#13d6b2'],
        legend: {
          show: true,
        },
        toolbox: {
          show: true,
          orient: 'vertical',
          right: 5,
          feature: {
            dataZoom: {
              show: true,
              yAxisIndex: 'none',
            },
            restore: {},
          },
        },
        tooltip: {
          trigger: 'axis',
        },
        xAxis: {
          type: 'category',
          axisLabel: {
            formatter: function (value, index) {
              const arr = value.split(' ')
              const arr1 = arr[0].split('-')
              if (index === 0) {
                return value
              } else {
                return arr1[1] + '-' + arr1[2] + ' ' + arr[1]
              }
            },
          },
          boundaryGap: false,
          data: [],
        },
        yAxis: {
          type: 'value',
          axisLabel: {
            formatter: (val) => {
              return val + this.line_data.unit
            },
          },
        },
        series: [
          {
            name: '',
            type: 'line',
            data: [],
            symbol: 'diamond',
            symbolSize: '4',
            smooth: false,
            lineStyle: {
              width: 1.5,
            },
            itemStyle: {
              color: '',
            },
          },
        ],
      },
    }
  },
  methods: {
    init_chart() {
      if (!this.chart) {
        echarts.registerTheme('macarons', macarons)
        this.chart = echarts.init(this.$refs.chart, 'macarons')
        this.chart_click()
      }

      this.chart.resize()
      this.chart.setOption(this.options)
    },
    chart_click() {
      this.chart.on('click', (params) => {
        this.$emit('view_client', params.name)
      })
    },
    listen_resize() {
      if (this.chart) {
        this.chart.resize()
      }
    },
  },
  watch: {
    line_data: {
      handler(newValue) {
        this.options.xAxis.data = newValue.time
        this.options.series[0].data = newValue.value
        this.options.series[0].name = newValue.series_name
        this.options.series[0].itemStyle.color = newValue.line_color
        this.$nextTick(() => {
          this.init_chart()
        })
      },
      deep: true,
      immediate: false,
    },
    is_open(newValue) {
      setTimeout(() => {
        this.listen_resize()
      }, 400)
    },
  },
  created() {
    window.addEventListener('resize', this.listen_resize)
    this.$once('hook:beforeDestroy', () => {
      window.removeEventListener('resize', this.listen_resize)
    })
  },
}
</script>`

**Comment by Lee324** [comment]
同问，我也遇到了，怀疑toolbox还原机制有修改，旧版本没问题

**Comment by Lee324** [comment]
echarts官网给了一个还原的重置事件--events. restore，我通过重置这个事件，成功避开了这个图形消失的问题。还考虑过通过自定义按钮实现的方法
