### ISSUE TITLE
Superimpose the histogram. Use 'diamond' and pictorialbar at the top. When you click the second segment of data of the first column, the obtained names do not match

### ISSUE THREAD

**Issue by wdlhao** [apache/echarts#15613]
### Version
4.0.4

### Reproduction link
[https://www.makeapie.com/editor.html?c=xCsDpKfl_Y&v=5](https://www.makeapie.com/editor.html?c=xCsDpKfl_Y&v=5)

### Steps to reproduce
1、When clicking the second section of the first column, the obtained name should be the name of the x-axis corresponding to the first column. Now the obtained name does not match;

2、When the click event of the legend at the top of echats is disabled, the next two legends cannot be clicked, which is normal; However, the first two legend can be clicked; Triggered the click event of echart;

3、Changing the Z value of pictorialbar can solve the click problem; However, it can not meet the existing effect of histogram

4、For the specific project code, see the reproduction link
[https://www.makeapie.com/editor.html?c=xCsDpKfl_Y&v=5](https://www.makeapie.com/editor.html?c=xCsDpKfl_Y&v=5)

### What is expected?
1. When you click the second section of the first column, you can get the correct name corresponding to the X axis;

2. When legend is disabled, click events cannot be clicked;

### What is actually happening?
When clicking the second section of the first column, the obtained name should be the name of the x-axis corresponding to the first column. Now the obtained name does not match;

When the click event of the legend at the top of echats is disabled, the next two legends cannot be clicked, which is normal; However, the first two legend can be clicked; Triggered the click event of echart;

**Comment by Ovilia** [comment]
I didn't get what's wrong here. Can you make an image to better illustrate which part is wrong?
And do you mean "hovering" when you said "clicking"?
