### ISSUE TITLE
Invert y-axis when plotting on geo

### ISSUE THREAD

**Issue by sioh89** [apache/echarts#15617]
### What problem does this feature solve?
We are plotting points with a geo svg that contains an `<image>` of a fictional map. Our data is created using the cartesian coordinate system (x-axis values increase from left to right and y-axis values increase from bottom to top). However, because we are using the geo coordinate system (y-axis values increase from top to bottom), the data points appear to be flipped vertically compared to the map image. Here is a simple example: https://codesandbox.io/s/echarts-geo-boundingcoords-ybbuy?file=/src/index.js

Is there some way to apply some setting similar to yAxis.inverse (https://echarts.apache.org/en/option.html#yAxis.inverse) for the geo coordinate system?

### What does the proposed API look like?
Perhaps an option called `geo.invert` which can be `'x'`, `'y'` or `'xy'`.

**Comment by pissang** [comment]
Currently changing labels in SVG seems to be a simpler solution. If we add some configuration like `invert` and the SVG is flipped. The data will also be flipped if we design it like `yAxis.inverse`
