### ISSUE TITLE
雷达图 维度标签添加tooltip

### ISSUE THREAD

**Issue by 1637410810** [apache/echarts#15632]
### What problem does this feature solve?
类似于展示单维度上的所有信息

### What does the proposed API look like?
目前的办法
radar.triggerEvent:true   维度标签出现tooltip
然后文档中radar.tooltip并不存在，试出来的
然后根据相同name的index拿到数据

**Comment by Ovilia** [comment]
Please follow #10537.

**Comment by likoha** [comment]
Thanks!!!!
