### ISSUE TITLE
In mix-line-bar,  if the areaStyle is set for the line graph, the bar graph overlapped by the areaStyle cannot be clicked

### ISSUE THREAD

**Issue by wh2017** [apache/echarts#15630]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar](https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar)

### Steps to reproduce
1.line series add areaStyle option

2. add code: `myChart.on('click', event => console.log(event))`

![image](https://user-images.githubusercontent.com/25954808/131301753-3ec33e40-fd53-4bd5-ac43-645f4b4e1bd5.png)

### What is expected?
bar and line both can click

### What is actually happening?
1.line can click, which is ok 

2.bar overlapped by line areaStyle, can't click, which is incorrect

![image](https://user-images.githubusercontent.com/25954808/131301880-dff882aa-8de0-4413-91c1-a1a40a5caf8a.png)

**Comment by pissang** [comment]
You can just put the bar series after line series or using `z` to change the order.

**Comment by wh2017** [comment]
Using Z to change the order solves the problem
