### ISSUE TITLE
visualMap设置文字width无效

### ISSUE THREAD

**Issue by cj11032** [apache/echarts#15644]
### Version
4.9.0

### Steps to reproduce
1.官网可以验证：设置该属性--visualMap-piecewise.textStyle. width
2.具体设置值：
```js
visualMap: {
    type: "piecewise",
    splitNumber: 8,
    min: 0,
    max: 100,
    calculable: true,
    realtime: false,
    inRange: {
      color: ["#313695", "#4575b4", "#74add1", "#abd9e9", "#e0f3f8", "#ffffbf", "#fee090", "#fdae61", "#f46d43", "#d73027", "#a50026"]
    },
    textStyle: {
      width: 4,
      overflow: "break"
    }
  },
```
### What is expected?
希望设置了文字宽度后，能实现文字换行

### What is actually happening?
设置了width以及overflow属性依然无效

---
分段型视觉映射组件在应用时有可能文字过长，希望能换行好看点

**Comment by pissang** [comment]
5.0 开始才支持设置 width 和 overflow 换行
