### ISSUE TITLE
Can I use `this` in formatter function?  `this` is current echartsInstance(后续是否考虑在formatter函数中的 this 直接 指向当前的 echartsInstance )

### ISSUE THREAD

**Issue by myth984** [apache/echarts#15648]
### What problem does this feature solve?
I want to generate tooltip by yAxis's somethings, but I can't get the option

想要根据yAxis的一些信息来进行生成tooltip, 但是我没有办法直接获取到option

now, I can resolve this probelm,  fisrt  `windows.echarts = echarts`, second I get echart's  Dom, third I call echarts.getInstanceByDom fourth get the option ,Too much trouble

现在我是通过dom , 然后获取当前echartsInstance 然后获取option, 太麻烦了

### What does the proposed API look like?
example

```javascript
// get dom by event
const dom = event.path.find(e=>e.hasAttribute('_echarts_instance_'));
const eId =  dom.getAttribute('_echarts_instance_');
const echarts = window.echarts;
const chartObj = echarts.getInstanceById(eId);
cosnt option = chartObj.getOption();
```

**Comment by Ovilia** [comment]
You should keep the instance returned by `echarts.init` in case you wish to use it in the callback. This is the best-practice we would recommend.

**Comment by myth984** [comment]
> You should keep the instance returned by `echarts.init` in case you wish to use it in the callback. This is the best-practice we would recommend.

sure, it's a good idea, but if I have lot's of chart, I will need a array or map to manage echartsInstance.

if I can use this in function, it will be a better idea.

**Comment by plainheart** [comment]
Maybe you can bind the instance to your function manually.

For example,

```js
function getFormatter(instance, func) {
  return func.bind(instance)
}
```

```js
chart1.setOption({
    // ...
    tooltip: {
        formatter: getFormatter(chart1, function() {
            console.log(this)
        })
    },
    // ...
})
```

**Comment by myth984** [comment]
> Maybe you can bind the instance to your function manually.
> 
> For example,
> 
> ```js
> function getFormatter(instance, func) {
>   return func.bind(instance)
> }
> ```
> 
> ```js
> chart1.setOption({
>     // ...
>     tooltip: {
>         formatter: getFormatter(chart1, function() {
>             console.log(this)
>         })
>     },
>     // ...
> })
> ```

Thank you, It can solve my problem.But echarts will be better when I can use this in function
