### ISSUE TITLE
TypeError: Cannot read property 'useStyle' of undefined after upgrading from echart 4.8 to 5.x

### ISSUE THREAD

**Issue by flyaway22** [apache/echarts#15657]
### Version
5.1.2

### Steps to reproduce
No idea, so here's a screenshoot of the error

https://imgur.com/keTUuUL

### What is expected?
To be able to load my page

### What is actually happening?
so, i tried upgrading echarts from v 4.8 to v 5.x in my project, but whenever i tried to start my project, i straightly get this error. I have no idea what caused this, and i have read the docs and guide on how to upgrade to v5, but still haven't find the solution or why this is happening. Any help will be appreciated. thank you!

**Comment by flyaway22** [comment]
> @flyaway22 Please provide a minimum reproducible demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.
> 
> _A minimum reproducible demo_ should contain as little data and components as possible but can still illustrate your problem. This is the best way for us to reproduce it and solve the problem faster.

https://codepen.io/Ovilia/pen/dyYWXWM 
this is one of the chart that i use in the project, is there anything that's causing the error in the option?

**Comment by flyaway22** [comment]
> @flyaway22 Please provide a minimum reproducible demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.
> 
> _A minimum reproducible demo_ should contain as little data and components as possible but can still illustrate your problem. This is the best way for us to reproduce it and solve the problem faster.

https://codesandbox.io/s/proud-shadow-gbpme
this is one of the chart that i used for my project. it was made using echart 4.8. Is there anything that's causing the error here?

**Comment by pissang** [comment]
I can't get this error from your project

**Comment by flyaway22** [comment]
> I can't get this error from your project. Maybe some steps are missing?

sorry, but here i am able to recreate it 
https://codesandbox.io/s/proud-shadow-gbpme?file=/src/index.js
