### ISSUE TITLE
折线图y轴markLine不显示

### ISSUE THREAD

**Issue by Youmyin** [apache/echarts#15667]
### Version
5.1.2

### Reproduction link
[https://codesandbox.io/s/quirky-currying-25jdz?file=/src/App.tsx](https://codesandbox.io/s/quirky-currying-25jdz?file=/src/App.tsx)

### Steps to reproduce
由于某些需求，将y轴数据先转换成value类型，显示的时候通过formatter转回字符串类型进行显示，但是使用markLine的时候，无论如何显示不了，markLine中的yAxis对应的数据是data的原始数据吗，是什么阻止它的显示？

### What is expected?
markLine能够正常显示

### What is actually happening?
markLine无法正常显示

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=line-marker 参考这个例子，改成这样是可以的：
```
markLine: {
    data: [{
        yAxis: 20
    }]
}
```
但我不知道为什么你的例子不行，再仔细对照一下吧

**Comment by Youmyin** [comment]
哎，我知道怎么回事了，我没有引入MarkLineComponent。。。Σ(⊙▽⊙"a
