### ISSUE TITLE
Chart unable to resize with react grid layout

### ISSUE THREAD

**Issue by lieyongchang** [apache/echarts#15661]
### Version
5.2.0

### Reproduction link
[https://codesandbox.io/s/react-grid-layout-with-resizable-forked-z3wd9?file=/src/index.js](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-z3wd9?file=/src/index.js)

### Steps to reproduce
resize the grid item, grid item is being resize but not the charts

### What is expected?
the charts to resize

### What is actually happening?
the chart did not resize

**Comment by Ovilia** [comment]
This is not a bug of Apache ECharts. Either you or the third-party lib should call chart.resize when the container resizes.

**Comment by lieyongchang** [comment]
in my codesandbox, i did call chart.resize

  ```
function renderChart() {
    const renderInstance = echarts.getInstanceByDom(chart.current);

    if (renderInstance) {
      chartInstance = renderInstance;
    } else {
      chartInstance = echarts.init(chart.current);
      chartInstance.resize();
    }
    chartInstance.setOption(option);
  }
```

but it is not changing as expected

**Comment by Ovilia** [comment]
I don't know react well but it seems this code is called once when init?
Instead, you should listen to the change event of its container and call `chart.resize()`.

What `chart.resize()` does is to reset the chart size according to current container, rather than listen to future size changes.

**Comment by lieyongchang** [comment]
it is call under useEffect
```
useEffect(() => {
    renderChart();
  });
```

which it is already checking if there is a change in size. Thats why i confuse why it is not hitting the chart.resize

**Comment by Ovilia** [comment]
`chartInstance.resize()` should be called when resizing.

**Comment by lieyongchang** [comment]
this is the part i am having an issue with, how do i know my parent width or height has change?
click on this [link ](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-pq7ku?file=/src/newvsreturnvisitors.js)for the changes i have made.

what i have try , passing my parent width and height as props

```
const Newvsresturnvisitors = (props) 
```
and using it as own 

```
 return (
    <div
      ref={chart}
      // style={{
      //   width: "100%",
      //   height: "100%",
      //   background: "white"
      // }}

      style={{
        props
      }}
    />
  );
```

but this cause another error :(  save me

**Comment by pissang** [comment]
Duplicate with https://github.com/apache/echarts/issues/15678. You can use https://developer.mozilla.org/zh-CN/docs/Web/API/ResizeObserver API listening to the DOM size change and do `chart.resize()`

**Comment by lieyongchang** [comment]
@pissang @Ovilia  I make some changes, click this [link ](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-pq7ku?file=/src/newvsreturnvisitors.js:1416-1429).

What I have done is pass my chartInstance to index.js, so when my ResponsiveGridLayout change layout, it will call the resize function

```
 const onLayoutChange = () => {
    if (value != null) {
      console.log("value not null");
      //   chartInstance.resize();
      value.resize();
    }
  };

  return (
    <ResponsiveGridLayout
      layouts={layout}
      onLayoutChange={() => onLayoutChange()}
    >
      <div key="1">
        <Card style={styles} val={setVal} resizeObserver={resizeObserver} />
      </div>
    </ResponsiveGridLayout>
  );
```

**Expected Result**
echart resize accordingly 


**Actual Result**
The resize function is call, but the chart did not resize

Some information, onLayout is call whenever the grid-layout item changes. 

what am I doing wrong here?

**Comment by pissang** [comment]
I don't think it's an echarts related issue anymore. Please check your code again.

**Comment by lieyongchang** [comment]
I still dont see it :( 

I only pass the chart instance when it is created. so the object is not null. So by right I should be able to call the resize method

```
function renderChart() {
    const renderInstance = echarts.getInstanceByDom(chart.current);

    if (renderInstance) {
      chartInstance = renderInstance;
    } else {
      chartInstance = echarts.init(chart.current, null, {
        width: 500,
        height: 300
      });

      props.value(chartInstance);
    }
    chartInstance.setOption(option);
  }
```

**Comment by pissang** [comment]
`resize()` is an action method and it won't return anything. 

Size of `react-grid-item` is changed. But the card content div still have the same size. You can give the clientWidth/clientHeight of `react-grid-item` when using resize.

```ts
chart.resize({
  width: ...
  height: ...
});
```

**Comment by lieyongchang** [comment]
So I have follow this [doc](https://echarts.apache.org/handbook/en/concepts/chart-size/#listen-to-the-container-size-to-change-the-chart-size) on how to call the resize method. Still did not work 

below is my code, click this [link ](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-pq7ku?file=/src/index.js:790-1026) for my codesandbox.
```
  const onLayoutChange = () => {
    // console.log(value);
    if (value != null) {
      console.log("value not null");
      value.resize({
        width: 800,
        height: 400
      });
    }
  };
```

Expected result: chart change to the dimension i specify when grid layout changes
Actual Result: nothing happens

**Comment by pissang** [comment]
What are you expected when you fixed the `width` and `height` to `800` and `400`?

**Comment by lieyongchang** [comment]
I was trying to see if my charts did resize as specify. If it does, then i will pass in my grid item dimension and pass it to the resize action

But currently it does not even change to the width n height i specify

**Comment by pissang** [comment]
I tried and it works.

**Comment by lieyongchang** [comment]
Thank you for being so patient with me, I console log and it did change.
