### ISSUE TITLE
cursor option is invalid for line graph

### ISSUE THREAD

**Issue by wh2017** [apache/echarts#15660]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-simple](https://echarts.apache.org/examples/zh/editor.html?c=line-simple)

### Steps to reproduce
add cursor option in series item
`cursor: 'auto'`
![image](https://user-images.githubusercontent.com/25954808/131830223-1b753398-404f-4545-9f83-69b46973896e.png)

### What is expected?
the cursor is default

### What is actually happening?
The cursor of line is still pointer
![image](https://user-images.githubusercontent.com/25954808/131830390-f9d366fb-bec8-4787-b283-d2fe91833ebb.png)

**Comment by susiwen8** [comment]
https://echarts.apache.org/en/option.html#series-line.cursor
Hover on `element`, The `element` for `line` are connect point not the whole line
