### ISSUE TITLE
themeRiver的例子中,将tooltip.trigger设为item,显示的名称一直是dq

### ISSUE THREAD

**Issue by aswjh** [apache/echarts#15676]
### Version
5.2.0

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=themeRiver-basic

tooltip.trigger设为 'item'

### What is expected?
鼠标在河流间移动时,tooltip应该显示鼠标所在河流的名称和值

### What is actually happening?
显示的名称和值都不对，是dataIndex没对应正确？

**Comment by susiwen8** [comment]
#10030
`themeRiver` tooltip doesn't support `item`
