### ISSUE TITLE
echart and material-ui card: resposive width and height

### ISSUE THREAD

**Issue by lieyongchang** [apache/echarts#15678]
### Version
5.2.0

### Reproduction link
This is the [link](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-pq7ku?file=/src/newvsreturnvisitors.js) to my codesandbox with the issue

### Steps to reproduce
open console, in codesandbox and the error message is there

### What is expected?
echart taking the width and height of parent component 

### What is actually happening?
Can't get DOM width or height. Please check dom.clientWidth and dom.clientHeight. They should not be 0.For example, you may need to call this in the callback of window.onload. 

    in Newvsresturnvisitors (at card.js:34)
    in SimpleCard (at src/​index.js:50)
    in App

**Comment by pissang** [comment]
I tried your demo

![image](https://user-images.githubusercontent.com/841551/132159648-6f7a875b-5f19-487c-b4d1-2dec10e3e98e.png)

The `clientHeight` is `0`. Please make sure your DOM has proper `clientWidth` and `clientHeight` when initializing chart. If not. do `resize` when the DOM size is prepared.

**Comment by lieyongchang** [comment]
I have give it a proper width and height

```
 return (
    <div
      ref={chart}
      style={{
        width: "500px",
        height: "300px",
        background: "white"
      }}
    />
  );
```

but i want to update those values of the parent width and height. Thats the part I am having the issue?

**Comment by pissang** [comment]
You can specify the chart width and height explicitly:
```ts
echarts.init(dom, null, { width: 500, height: 300})
```

**Comment by lieyongchang** [comment]
but how do i capture when the card changes its width and height? how do I then use those values and set it as the chart own width and height ?
