### ISSUE TITLE
折线图使用visualMap时颜色错乱，颜色错位

### ISSUE THREAD

**Issue by dignfei** [apache/echarts#15680]
### Version
5.2.0

### Steps to reproduce
可以在这里直接看到能重现的代码和效果：
https://www.makeapie.com/editor.html?c=xbePg5FU6G&v=9
版本https://github.com/apache/echarts/tree/release-dev 修复了这个bug。
但是到了 5.2.0版本这个bug 又出现了。

### What is expected?
我使用visualMap的pieces，希望折线图分段显示红色和绿色，

### What is actually happening?
在折线拐弯的地方，颜色会错乱，红色的折线两端会有一部分绿色，绿的折线两端会有一部分红色

---
在chrome浏览器访问时会发生这种情况，如果chrome中设置关闭硬件加速，则可以正常显示。
可以在这里直接看到效果
https://www.makeapie.com/editor.html?c=xbePg5FU6G&v=9
![image](https://user-images.githubusercontent.com/25482706/132132321-26b52011-03b2-4319-b96b-065bb5df3e27.png)

**Comment by yanqiqi1996** [comment]
@dignfei  这个问题你解决了吗

**Comment by dignfei** [comment]
> @dignfei 这个问题你解决了吗

这个版本https://github.com/apache/echarts/tree/release-dev 修复了这个bug，直接下载源代码覆盖即可
