### ISSUE TITLE
横向柱图visualMap颜色错误

### ISSUE THREAD

**Issue by AegeanSeaBlue** [apache/echarts#15698]
### Version
5.2.0

### Steps to reproduce
option = {
    xAxis: {
         type: 'value'
    },
    yAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    visualMap:[
        {
            type:'continuous',
            min:20,
            max:160,
            seriesIndex:0,
            inRange:{
                color:['blue','red']
            }
        }],
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar'
    }]
};

### What is expected?
continuous inRange color

### What is actually happening?
blue

**Comment by plainheart** [comment]
It seems to be working if you add `dimension: 0` into your `visualMap` option.
