### ISSUE TITLE
geoselectchanged geoSelect 无效

### ISSUE THREAD

**Issue by yongdu555** [apache/echarts#15693]
### Version
5.2.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=map-usa](https://echarts.apache.org/examples/zh/editor.html?c=map-usa)

### Steps to reproduce
在官方列子后面注册事件
```ts
myChart.on("geoselectchanged", function (a) {
    console.log(a);
});
```
控制台观察点击效果

### What is expected?
有结果输出

### What is actually happening?
无结果输出

**Comment by pissang** [comment]
开启 `selectedMode` 后监听 `selectchanged` 事件
