### ISSUE TITLE
edge label with a line connected

### ISSUE THREAD

**Issue by Syslos94** [apache/echarts#15699]
### What problem does this feature solve?
1. I'm creating a relationship graph with hundreds of nodes and edges, and for each edge, the length of the label may various. Thus, the graph can be a mess.
2. if we can have an option to make the labels surround the main graph, and have a line connected to the edge, that could be great.

### What does the proposed API look like?
edgeLabelLayout: "surrounded"

**Comment by pissang** [comment]
I'm not sure about how it looks like. Please try `labelLayout` to have custom label layouts.
