### ISSUE TITLE
tooltip mousemove can not get dom when render by svg in firefox 

### ISSUE THREAD

**Issue by Lee-Tanghui** [apache/echarts#15697]
### Version
5.2.0

### Steps to reproduce
brower:  firefox
renderer: svg

1.const mychart =  echarts.init(dom, null, {
    renderer: 'svg'
  })
2. myChart.setOption(option)
3. option is pie chart or boxplot chart, and tooltip is configed to be show an trigger by item
4. hover in charti tem and move, the tooltip will be disapper 

中文说明：当使用svg渲染时，在Firfox浏览器打开渲染pie或者boxplot，tooltip在hover时可能会不出现

### What is expected?
hover in chart item and move, the tooltip will be show

### What is actually happening?
hover in chart item and move, the tooltip will be disapper

**Comment by plainheart** [comment]
Thanks for your feedback. It may be related to #15646.
