### ISSUE TITLE
关系图：当进行缩小操作时线的label会跑的很远

### ISSUE THREAD

**Issue by skayi** [apache/echarts#15704]
### Version
4.8.0

### Steps to reproduce
鼠标滚轮缩小图

### What is expected?
线的label一起缩小或隐藏，label离线的距离不要变

### What is actually happening?
线的label距离线会很远（缩小程度越大偏离距离越远）
![image](https://user-images.githubusercontent.com/61896686/132785953-422990c2-9c03-4e39-92d7-8d9cc8f136aa.png)

**Comment by skayi** [comment]
> @skayi It seems you are not using English, I've helped translate the content automatically. To make your issue understood by more people, we'd like to suggest using English next time. 🤗
> 
> TRANSLATED
> 
> **TITLE**
> 
> Diagram: The cable of the line runs very far when the downsizing operation is performed
> 
> **BODY**
> 
> ### Version
> 4.8.0
> 
> ### Steps to reproduce
> Mouse wheel zoomed out
> 
> ### What is expected?
> The label of the line is reduced or hidden together, and the distance of the label offline should not change
> 
> ### What is actually happening?
> The label of the line will be far away from the line (the greater the reduction, the farther the deviation will be)
> ![image](https://user-images.githubusercontent.com/61896686/132785953-422990c2-9c03-4e39-92d7-8d9cc8f136aa.png)

thanks

**Comment by pissang** [comment]
@skayi 可以设置 `labelLayout.hideOverlap` 隐藏
