### ISSUE TITLE
The MarkArea disappears if the specified range is out of the visible scope

### ISSUE THREAD

**Issue by Becavalier** [apache/echarts#15708]
### Version
5.2.0

### Reproduction link
[https://codepen.io/becavalier/pen/mdwWgmd](https://codepen.io/becavalier/pen/mdwWgmd)

### Steps to reproduce
Please refer to the example directly.

The MarkArea could be shown correctly if you change the data to: 
```
[[{
  xAxis: '2009/6/12\n7:00',
}, {
  xAxis: '2009/9/22\n7:00',
}]]
```

### What is expected?
The MarkArea should be shown correctly.

### What is actually happening?
The MarkArea disappears.

**Comment by Becavalier** [comment]
Any update?

**Comment by Becavalier** [comment]
Thanks

**Comment by neojunsiang** [comment]
Can I check if there is a workaround on this issue for v5.6.0?
