### ISSUE TITLE
labelLayout not works in production env (echarts v5.2)

### ISSUE THREAD

**Issue by percy507** [apache/echarts#15701]
### Version
5.2.0

### Steps to reproduce
```js
{
  type: 'pie',
  radius: ['20%', '60%'],
  avoidLabelOverlap: false,
  labelLayout() {
    return {
      x: 200,
      y: 50,
      align: 'left',
    };
  },
  ...
}
```

When use ECharts v5.2, labelLayout works in local Env, but not works in production.

Then i change the version to v5.1.1, labelLayout works in local and production Env both.

### What is expected?
 On Echarts v5.2, labelLayout works in production.

### What is actually happening?
not works

**Comment by pissang** [comment]
@percy507 Hi, do you mind proving your project to us? It will be great if it's reduced to a minimal reproducible demo.

**Comment by percy507** [comment]
@pissang Sorry, it seems hard to provide a mini demo on codepen or codesandbox. Because problem happens in the production env.

But there is a way. You can `git clone` my project to local and test it.

```bash
git clone https://github.com/percy507/vite-react-bigScreen.git

# then change echarts version to v5.2.0 in package.json

npm i -d
npm run dev         # local dev env
npm run preview     # local production env (problems happens here)
```

![image](https://user-images.githubusercontent.com/18365078/132788324-2d2aab7a-0341-498e-afca-58f2ea088aaa.png)

**Comment by pissang** [comment]
I'm not sure but seems the behavior is the same when I try
```ts
npm run dev         # local dev env
npm run preview     # local production env (problems happens here)
```
You can try removing all `node_modules` and install again.

**Comment by percy507** [comment]
@pissang 

Already tried removing `node_modules`, still not works. 
It seems weird. 
If your side is ok, then i will close this issue. If someone meets same problem, then we discuss it again.
Now i will use echarts v5.1.1 instead of v5.2.

Thanks🤪.

**Comment by pissang** [comment]
@percy507 Doubled checked again and found the `package.json` is still using echarts@5.1.1. Updated to 5.2.0 can reproduce this bug.

**Comment by percy507** [comment]
Yes, use v5.2 cause weird problem in production mode, so i change the version to v5.1.1.😂

**Comment by pissang** [comment]
```ts
import { LabelLayout } from 'echarts/features';
echarts.use([LabelLayout]);
```

@percy507 This solution should work

**Comment by percy507** [comment]
@pissang 
Thanks, it works.👍
I suggest add this to echarts document.

Add here.
https://echarts.apache.org/handbook/zh/basics/import#%E5%9C%A8-typescript-%E4%B8%AD%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5

**Comment by pissang** [comment]
@percy507 Thanks for the suggestion. Will improve document and examples.

**Comment by jsonMartin** [comment]
Labels were working fine for me without overlap on dev, but not on prod. Adding `LabelLayout` worked for me as per @pissang 's solution. Thanks 👍🏼
