### ISSUE TITLE
Support dual data axes

### ISSUE THREAD

**Issue by moonlitusun** [apache/echarts#15702]
### What problem does this feature solve?
Now, a grid have to a category axis。

### What does the proposed API look like?
In the financial field, there are many scenarios with dual data axes。Can you support? plz

**Comment by pissang** [comment]
echarts supports multiple `xAxis` or `yAxis`. Check this example:

https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis

**Comment by moonlitusun** [comment]
@pissang 
Thanks Reply。But I think I didn’t make it clear, I mean `xAxis.type: value` and `yAxis.type: value`.Not `xAxis.type: category， yAxis.type: value` 。If you need, i will give a live demo。

**Comment by pissang** [comment]
It's also not a problem. Check https://echarts.apache.org/examples/zh/editor.html?c=line-in-cartesian-coordinate-system and  https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple
