### ISSUE TITLE
tree 组件点击收缩展开出现严重卡顿，闪烁等情况

### ISSUE THREAD

**Issue by hanyan123** [apache/echarts#15714]
### Version
5.1.1

### Steps to reproduce
echarts tree 点击根节点收缩，然后快速点击根节点展开会出现严重卡顿情况，并且会先出现展开完成的渲染图，然后再次以动画的形式展开。体验非常不友好，旧版本的echarts没有此情况

### What is expected?
像旧版本一样流畅

### What is actually happening?
卡顿

**Comment by pissang** [comment]
@hanyan123 这个应该是 `animationEasingUpdate` 配置成 `cubicInOut` 的问题，你试试改成 `cubicOut`

**Comment by hanyan123** [comment]
> @hanyan123 这个应该是 `animationEasingUpdate` 配置成 `cubicInOut` 的问题，你试试改成 `cubicOut`

我试了，还是一样的。折叠起来后必须要等一会儿再次点击根节点才行。如果折叠起来立马点，还是会出现卡顿，闪烁的情况，官方案例也有这样的问题。但是老版本不存在这样的问题
