### ISSUE TITLE
legend单独设置icon时，itemHeight在v5.0.1和v5.2.0显示不一致

### ISSUE THREAD

**Issue by HAM2506** [apache/echarts#15717]
### Version
5.2.0

### Reproduction link
[https://codepen.io/ham2506/pen/mdwMxVW](https://codepen.io/ham2506/pen/mdwMxVW)

### Steps to reproduce
单独给legend设置icon path，预期icon应该显示为直线，在v4.x和v5.0.1的版本是符合预期的，但是在v5.2.0显示为方块。

### What is expected?
legend icon显示为直线

### What is actually happening?
legend icon显示为方块

**Comment by pissang** [comment]
看这个 path 本身就是一个 40x10 的长方形，现在的才是应该符合预期的，你可以把 path 的高度改得小一点：
```ts
var iconpath = "path://M0 0 L40 0 L40 2 L0 2z"
```

**Comment by pissang** [comment]
加上

```ts
symbolKeepAspect: true
```

试试
