### ISSUE TITLE
动态条形图条形末端加图片

### ISSUE THREAD

**Issue by cornelius-git** [apache/echarts#15710]
### What problem does this feature solve?
在动态条形中能否实现像flourish那样在每个数据条上添加图片？

### What does the proposed API look like?
像传数据一样直接用列表传入连接即可。

**Comment by pissang** [comment]
@cornelius-git 可以使用富文本标签添加图片。参考 https://echarts.apache.org/examples/zh/editor.html?c=bar-rich-text
