### ISSUE TITLE
随机颜色中，排除红色

### ISSUE THREAD

**Issue by a1292999652** [apache/echarts#15716]
### Version
5.2.0

### Steps to reproduce
多个item时

### What is expected?
不要出现红色

### What is actually happening?
出现了红色背景的柱子，老板不喜欢，红色表示错误，故障的意思

![微信图片_20210914102026](https://user-images.githubusercontent.com/31630317/133184323-3fa2c262-79a2-4802-97ed-bde01d6f7720.png)

**Comment by plainheart** [comment]
可以用 [`color`](https://echarts.apache.org/zh/option.html#color) 自定义取色盘

**Comment by a1292999652** [comment]
棒！已解决
