### ISSUE TITLE
rich富文本

### ISSUE THREAD

**Issue by cornelius-git** [apache/echarts#15718]
### What problem does this feature solve?
rich中的backgroundcolor中的image不能使用回调函数，我想让每个柱状图根据条件显示不同的不同图片如何操作？rich中的background只能输入固定的图片连接。

### What does the proposed API look like?
能在rich中使用回调函数，label中能根据数据匹配。

**Comment by plainheart** [comment]
可以先提前根据数据动态生成 rich object

**Comment by Pandora1m2** [comment]
```

formatter: function (value, index) {
      if (index >= 3){
          return `{imgOther|${index+1}  }    ${value}`
      }
      return `{img${index}|}    ${value}`
  },
  rich: {
      text:{
          // height: '18',
          width: '1',
      },
      img0: {
          height: '21',
          width: '2',
          backgroundColor: {image: _this.img0}
      },img1: {
          height: '21',
          width: '2',
          backgroundColor: {image: _this.img1}
      },img2: {
          height: '21',
          width: '2',

```

![image](https://user-images.githubusercontent.com/66824514/134297020-d6b4a0da-f9f3-4398-a24f-7c7d981f7a6d.png)

**Comment by beydeng** [comment]
Same problem. In Rich, you need to define each image, or 100 styles for 100 cases

**Comment by beydeng** [comment]
@cornelius-git 最后找到好的办法来处理这个动态添加图片的方法了么？
