### ISSUE TITLE
Link for "Create custom build"-tutorial is missing for v5 documentation

### ISSUE THREAD

**Issue by webjohan** [apache/echarts#15739]
### Version
5.2.0

### Steps to reproduce
Check README.me for:
"More custom build approaches can be checked in this tutorial: Create Custom Build of ECharts please."
click link Create Custom Build of ECharts. No tutorial found for v5.* doc only avalible for v4.*

### What is expected?
A tutorial for custom build of v5 

### What is actually happening?
you end up on: 
https://echarts.apache.org/en/tutorial.html#Customized%20Chart%20Styles

---
Link should be removed or tutorial added for v5

**Comment by pissang** [comment]
We have changed our build infra and are not suggesting creating a custom build with CLI anymore. It's too complex and not well designed. You can either use our [online builder](https://echarts.apache.org/en/builder.html) if you wan't to use script tag to load it, or check the minimal bundle section in [how to import](https://echarts.apache.org/handbook/en/basics/import) if you are using webpack or some other bundlers.

**Comment by WissemAouichi** [comment]
@pissang I am using echarts in angular, after trying both the minimal bundle import as in [how to import](https://echarts.apache.org/handbook/en/basics/import/) it returned a **bundle size of 3.01 Mo** when checked with webpack bundle analyzer. 

When i used a custom echart file like so:
 export * from 'echarts/src/echarts';

import 'echarts/src/chart/line';
import 'echarts/src/chart/bar';
// component examples:
import 'echarts/src/component/tooltip';
import 'echarts/src/component/title';
import 'echarts/src/component/toolbox';

Then the **bundle size was 1.46 Mo**.

Using the link downloaded from the online builder in the angular scripts loads everything in the main.js and make it voluminous.

@pissang should i continue using the custom echarts file to have smaller bundle size? what are your recommendations ?

**Comment by pissang** [comment]
> @pissang I am using echarts in angular, after trying both the minimal bundle import as in how to import it returned a bundle size of 3.01 Mo when checked with webpack bundle analyzer.

It will be tree-shaken after minified.

``` ts
export * from 'echarts/src/echarts';

import 'echarts/src/chart/line';
import 'echarts/src/chart/bar';
// component examples:
import 'echarts/src/component/tooltip';
import 'echarts/src/component/title';
import 'echarts/src/component/toolbox';
```

This can also work but will be not suggested any more.
