### ISSUE TITLE
极坐标系下的柱状图在有初始data时，刻度增长异常。

### ISSUE THREAD

**Issue by anzhou99** [apache/echarts#15744]
### Version
5.2.0

### Reproduction link
[https://codepen.io/stjerne/pen/yLXprzZ](https://codepen.io/stjerne/pen/yLXprzZ)

### Steps to reproduce
极坐标系下的柱状图在有初始data时，刻度增长方向、增长值异常。（1. option中设置了clockwise为true，预期增长方向应为顺时针，实际显示却为逆时针；2. 在增长方向相反的同时，增长值也存在异常。预期应该增长10%，实际增长却为（1-10%）。

演示链接中，我模拟了有初始data值和无初始data值两种实例，请参照。

### What is expected?
即使是在有初始data值的情况下，图表增长方向应与clockwise设置一致，增长值应与后续data中设置的值一致。

### What is actually happening?
刻度增长方向、增长值异常。
上图为异常状态，下图为无初始data值对照。
![demo](https://user-images.githubusercontent.com/65989962/133714528-fbbb88bc-ab94-4e9d-baa7-5f8beec40b9f.gif)

**Comment by plainheart** [comment]
#15589 修复了该问题，可以先用 [nightly](https://www.npmjs.com/package/echarts-nightly) 版本验证一下。5.2.1 修复版本也正在准备发布中。

**Comment by anzhou99** [comment]
验证正常，坐等发布。
感谢！
