### ISSUE TITLE
折线图设置 visualMap.pieces 2000个分段。配置dataZoom 放大缩小会卡，有什么方法解决吗？

### ISSUE THREAD

**Issue by webywz** [apache/echarts#15740]
### Version
5.1.2

### Steps to reproduce
visualMap.pieces 分段太多的话，会造成放大缩小卡顿。分段越多越卡，大概是1200个分段会卡

### What is expected?
visualMap.pieces 分段太多的话，dataZoom 做优化，放大缩小不会卡顿

### What is actually happening?
dataZoom 放大缩小会卡

---
我的需求是图表的每一段的颜色都不一样。
从第一个点开始，P0( 前一个点  ) 与 P1( 后一点  ) 做比较，
P1 > P0 红，
P1 < P0 绿，
P1 = P0 按P0 点颜色

除了visualMap.pieces 还有其他实现方案吗？
![image](https://user-images.githubusercontent.com/37465255/133611018-3b33d179-6a00-498f-9a69-3290b74de2be.png)

**Comment by pissang** [comment]
@webywz 如果只有红绿两个颜色，建议分成两个系列，绿色系列中的红色数据部分用`'-'`填充，同理红色系列

**Comment by BiosSun** [comment]
@pissang 我有尝试分成两个系列，但当数据点太多时，因为采样的关系，最终图形会有所变化。


> @webywz 如果只有红绿两个颜色，建议分成两个系列，绿色系列中的红色数据部分用`'-'`填充，同理红色系列

**Comment by zimutao** [comment]
有优化方案吗？遇到了同样的问题。大数据下，分段太多，缩放很卡。
