### ISSUE TITLE
Breadcrumb emphasis in treemap has no effect

### ISSUE THREAD

**Issue by uhafner** [apache/echarts#15741]
### Version
5.1.2

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=treemap-simple](https://echarts.apache.org/examples/en/editor.html?c=treemap-simple)

### Steps to reproduce
In your example, see link above, insert as `option`:
```
option = {
    series: [{
        type: 'treemap',
        breadcrumb: {
                        itemStyle: {
                            color: 'red'
                        },
                        emphasis: {
                            itemStyle: {
                                color: 'blue',
                                opacity: 0.6
                            },
                        }
                    },
        data: [{
            name: 'nodeA',            // First tree
            value: 10,
            children: [{
                name: 'nodeAa',       // First leaf of first tree
                value: 4
            }, {
                name: 'nodeAb',       // Second leaf of first tree
                value: 6
            }]
        }, {
            name: 'nodeB',            // Second tree
            value: 20,
            children: [{
                name: 'nodeBa',       // Son of first tree
                value: 20,
                children: [{
                    name: 'nodeBa1',  // Granson of first tree
                    value: 20
                }]
            }]
        }]
    }]
};
```

### What is expected?
When moving the mouse over the breadcrumbs, the color should change from red to blue. (See https://echarts.apache.org/en/option.html#series-treemap.breadcrumb.emphasis.itemStyle.color)

### What is actually happening?
The color stays red.

**Comment by susiwen8** [comment]
I check the code, this would be a new feature, breadcrumb doesn't support `emphasis`

**Comment by uhafner** [comment]
In the meantime it would make sense to adapt the documentation then: 
https://echarts.apache.org/en/option.html#series-treemap.breadcrumb.emphasis.itemStyle.color

**Comment by rakshith1997** [comment]
![image](https://user-images.githubusercontent.com/39569414/173570887-c54ab544-5193-4907-a3f7-a54a5acb7808.png)
Reproduction link
https://echarts.apache.org/examples/en/editor.html?c=treemap-simple

Steps to reproduce
In your example, see link above, insert as option:

option = {
  series: [
    {
      type: 'treemap',
      data: [
        {
          name: 'nodeA',
          value: 10,
          children: [
            {
              name: 'nodeAa',
              value: 4
            },
            {
              name: 'nodeAfddffd fdgdfg dgdgb dffvdfdvdfvfdvdb',
              value: 6
            }
          ]
        },
        {
          name: ' nodeB7777777777777777777  77777777777777777777777 77777777777777777',
          value: 20,
          children: [
            {
              name: 'nodeBa',
              value: 20,
              children: [
                {
                  name: 'nodeBa1',
                  value: 20
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
What is expected?
without overlaping the name should be shown in breadcrumb .

What is actually happening?
the name inside the breadcrumb is overlaping

**Comment by rakshith1997** [comment]
> @rakshith1997 Did you click the top right one?

yes , it happens for all the label and second breadcrumb

**Comment by susiwen8** [comment]
> > @rakshith1997 Did you click the top right one?
> 
> yes , it happens for all the label and second breadcrumb

By design

**Comment by rakshith1997** [comment]
> > > @rakshith1997 Did you click the top right one?
> > 
> > 
> > yes , it happens for all the label and second breadcrumb
> 
> By design

yes that's the bug
