### ISSUE TITLE
移动端使用柱状图，水平方向滑动时，自定义tooltip不消失

### ISSUE THREAD

**Issue by mingugu** [apache/echarts#15743]
### Version
5.2.0

### Reproduction link
[https://echarts.apache.org/v4/examples/zh/editor.html?c=mix-zoom-on-value](https://echarts.apache.org/v4/examples/zh/editor.html?c=mix-zoom-on-value)

### Steps to reproduce
1、柱状图添加dataZoom，使用formatter 自定义tooltip
2、水平滑动柱子时，tooltip不消失
注：使用datazoom监听事件，dispatchAction({ type: 'hideTip'})也是无法将tooltip隐藏

### What is expected?
柱状图水平方向滑动时，tooltip消失

### What is actually happening?
水平方向滑动时，自定义tooltip不消失

---
看github上说5.0.1会解决这个问题，5.2.0有没有改善这个问题呢

**Comment by Ovilia** [comment]
trigger axis 的情况下，在图表范围内都会显示的。如果有问题，提供一下复现代码吧，链接的例子里没有 hideTip。

> 看github上说5.0.1会解决这个问题，5.2.0有没有改善这个问题呢
这个是哪个 issue 可以链接一下，不一定是同一个问题。

**Comment by mingugu** [comment]
1、triggerOn不设置的时候（默认值），监听平移事件，无法取消
this.chart.on('datazoom',()=>{
 this.chart.dispatchAction({ type: 'hideTip' })
})
2、将triggerOn设置”click“,第一步的写法平移时能取消tooltip；但这种方式在移动端好像不能做到手指点击柱子显示tooltip,手指放开隐藏tooltip吧？
3、移动端的话会考虑新增triggerOn的类型，如touchmove吗

**Comment by Ovilia** [comment]
请提供一个完整的例子
