### ISSUE TITLE
升级到v5后，Type expected. TS1110 in version 5.2.0 线上vue项目无法build

### ISSUE THREAD

**Issue by lishaoh** [apache/echarts#15749]
### Version
5.2.0

"devDependencies": {
    "@types/echarts": "^4.9.10",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-eslint": "^4.5.13",
    "@vue/cli-plugin-typescript": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "@vue/eslint-config-prettier": "^4.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "ajv": "^6.9.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "mockjs": "^1.0.1-beta3",
    "sass-loader": "^7.0.1",
    "typescript": "~3.2.2",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "vue-code-diff": "0.0.5",
    "vue-template-compiler": "^2.6.10"
  },

### Steps to reproduce
升级到5.2.0，然后build vue项目失败

### What is expected?
成功

### What is actually happening?
无法build

截图如下：
![image](https://user-images.githubusercontent.com/20917295/133797785-d96520ac-99b2-4278-9755-c0abee44be5d.png)

**Comment by plainheart** [comment]
你在使用 DefinitelyTyped 中的 ECharts 类型定义吗？这个从5.0开始不需要了，已经由官方包提供。

**Comment by lishaoh** [comment]
@plainheart 我需要升级typescript吗？目前ts版本3.2.2

**Comment by lishaoh** [comment]
移除了@types/echarts": "^4.9.10"还是报同样的错误

"dependencies": {
    "@babel/core": "^7.10.2",
    "babel-code-frame": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-types": "^6.26.0",
    "core-js": "^2.6.5",
    "echarts": "^5.2.0",
    "echarts-wordcloud": "^2.0.0",
    "element-ui": "^2.13.2",
    "graceful-fs": "^4.2.4",
    "hot-formula-parser": "^4.0.0",
    "module": "^1.2.5",
    "moment": "^2.24.0",
    "nprogress": "^0.2.0",
    "showdown": "^1.9.1",
    "systemjs": "^6.3.2",
    "vue": "^2.6.10",
    "vue-affix": "^0.4.0",
    "vue-beautify": "^1.1.3",
    "vue-class-component": "^6.0.0",
    "vue-clipboard2": "^0.2.1",
    "vue-codemirror": "^4.0.6",
    "vue-cookie": "^1.1.4",
    "vue-grid-layout": "^2.3.1",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.1.3",
    "vue-tinymce-editor": "^1.6.2",
    "vue2-ace-editor": "0.0.13",
    "vuedraggable": "^2.24.3",
    "vuex": "^3.0.1",
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-typescript": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-prettier": "^4.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "ajv": "^6.9.1",
    "babel-eslint": "^10.0.1",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "mockjs": "^1.0.1-beta3",
    "sass-loader": "^7.0.1",
    "typescript": "~3.2.2",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "vue-code-diff": "0.0.5",
    "vue-template-compiler": "^2.6.10"
  },

**Comment by plainheart** [comment]
错误完全一样吗？按理说至少应该不一样才对。typescript 如果允许 也建议升级下 不确定3.2是否还能兼容。

**Comment by lishaoh** [comment]
@plainheart 错误是一样，typescript升级后就会有其他bug

**Comment by plainheart** [comment]
那个错误看起来和ECharts无关。

**Comment by plainheart** [comment]
错误一样不应该 将 echarts 卸载重新装一下试试

**Comment by lishaoh** [comment]
好，我试试

**Comment by pissang** [comment]
Duplicated with https://github.com/apache/echarts/issues/15750
