### ISSUE TITLE
Major regression: markLine cannot match dates using strings

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#15758]
### Version
5.2.0

### Reproduction link
[https://codepen.io/bilge-the-encoder/pen/gORzPzL](https://codepen.io/bilge-the-encoder/pen/gORzPzL)

### Steps to reproduce
1. Add time-based x-axis.
2. Add x-axis marker line specified as string.

### What is expected?
Marker line is drawn.

### What is actually happening?
Marker line is not drawn and no error is emitted.

---
If the marker line is specified as a `Date` instead of a string, it works. If the library is downgraded from 5.2.0 back to 5.1.1, it works also [[proof](https://codepen.io/bilge-the-encoder/pen/zYzjrQQ)].

**Comment by plainheart** [comment]
Hi, this issue has been fixed in the new patch version 5.2.1. See #15686 for more details.

**Comment by Bilge** [comment]
I see, thank you.
