### ISSUE TITLE
ES Module error : Process is undenfined

### ISSUE THREAD

**Issue by lishaoh** [apache/echarts#15750]
### Version
5.2.0

### Steps to reproduce
by
import * as echarts from "echarts";

but get some error in brower

 "devDependencies": {
    "@types/echarts": "^4.9.10",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-eslint": "^4.5.13",
    "@vue/cli-plugin-typescript": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "@vue/eslint-config-prettier": "^4.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "ajv": "^6.9.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "mockjs": "^1.0.1-beta3",
    "sass-loader": "^7.0.1",
    "typescript": "~4.4.3",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "vue-code-diff": "0.0.5",
    "vue-template-compiler": "^2.6.10"
  },

### What is expected?
succes

### What is actually happening?
error
![image](https://user-images.githubusercontent.com/20917295/133815824-1715065f-0bd0-4db4-958e-197e5c8692c6.png)
![image](https://user-images.githubusercontent.com/20917295/133815849-8305cb40-3553-4825-a11f-a2b0658f3a40.png)

**Comment by pissang** [comment]
这部分不是 echarts 的代码，请先排查你其它依赖的问题
