### ISSUE TITLE
Echarts "Stacked Line Chart" The chart is not drawn correctly according to the data

### ISSUE THREAD

**Issue by tianlang89757** [apache/echarts#15753]
### Version
5.2.0

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=line-stack](https://echarts.apache.org/examples/zh/editor.html?c=line-stack)

### Steps to reproduce
1.Mail marketing, video advertising and direct access data are all changed to 0；
2.Alliance advertising, search engine data are all changed to 1
3.The example diagram on the right does not draw a line chart according to the setting data

### What is expected?
Draw the line chart correctly according to the setting data

### What is actually happening?
The example diagram on the right does not draw a line chart according to the setting data

**Comment by plainheart** [comment]
This example is intended to show how to make a stacked line chart, so it's expected behavior. If you hope to make a normal line chart, just remove the option `stack: '总量'` from your option.

**Comment by tianlang89757** [comment]
> 此示例旨在展示如何制作堆积折线图，因此这是预期的行为。如果您希望制作普通折线图，只需`stack: '总量'`从您的选项中删除该选项即可。

Thank you. I know how to use it
