### ISSUE TITLE
折线图使用visualMap时,颜色错乱，图元颜色改变，线段颜色错误

### ISSUE THREAD

**Issue by sophia1024** [apache/echarts#15755]
### Version
5.2.0

### Reproduction link
[https://www.makeapie.com/editor.html?c=xp95UAbrfA&v=2](https://www.makeapie.com/editor.html?c=xp95UAbrfA&v=2)

### Steps to reproduce
可以在这里直接看到能重现的代码和效果：
https://www.makeapie.com/editor.html?c=xp95UAbrfA&v=2

### What is expected?
我使用visualMap的pieces，希望折线图分段显示红色1，红色2，红色3，和蓝色

### What is actually happening?
折线图颜色会错乱，红色的折线只有图元显示红色，折线会显示蓝色

---
https://www.makeapie.com/editor.html?c=xp95UAbrfA&v=2
![image](https://user-images.githubusercontent.com/54983463/133871808-c417ed69-6c09-468d-9af0-d7c32fd9c672.png)

**Comment by sophia1024** [comment]
The color of the line chart will be messy. Only the symbol of the red line will be displayed in red, and the line will be displayed in blue.

**Comment by Ovilia** [comment]
Please refer to [this example](https://www.makeapie.com/editor.html?c=x7AFiJ06e). If you still have questions, please minify your demo with minimum data.

**Comment by sophia1024** [comment]
minimum  data is not a problem, but a large amount of data will have this problem.

**Comment by sophia1024** [comment]
> Please refer to [this example](https://www.makeapie.com/editor.html?c=x7AFiJ06e). If you still have questions, please minify your demo with minimum data.

minimum data is not a problem, but a large amount of data will have this problem.

**Comment by Ovilia** [comment]
Then you should debug to see the exact data to reproduce this problem. Otherwise, it's impossible to learn what's going on here.

**Comment by dignfei** [comment]
看看我反馈的问题，是不是和你的问题一样 https://github.com/apache/echarts/issues/15787
