### ISSUE TITLE
Enable more dimensions (more than x & y) visualmap for line chart

### ISSUE THREAD

**Issue by qiangxinglin** [apache/echarts#15763]
### What problem does this feature solve?
Currently, to make a horizontal gradient color line chart is only possible for dimension[1] (namely y). It will be more powerful to give the opportunity to decide the line color based on 3rd/4th column of the data. For example: data in following format
`[data category, data value, more value]`

Note that I know there is a "category" option in visualmap to do a color mapping, but what I want is a "continuous gradient horizontal line which color is based on the third dimension (e.g. whether it > 1, < 0, etc.)". But for now, only the data point is colored, rather than the connecting line segment.

### What does the proposed API look like?
No API change.

**Comment by Ovilia** [comment]
This feature is supported right now. Checkout [visualMap.dimension](https://echarts.apache.org/en/option.html#visualMap-continuous.dimension).

**Comment by qiangxinglin** [comment]
@Ovilia I know this option, but it only colored the data point rather than the **_line segment_** between them.
```
visualMap: {
  type: 'continuous',
  inRange: {
    color: ['orange', 'green', 'red'],
  },
  dimension: 3 // For line chart, it will only highlight the point if set the dimension > 1 
}
```
![image](https://user-images.githubusercontent.com/20382522/134516869-d72e1a09-e8cd-484e-a547-ee53f42c19cc.png)

**Comment by pissang** [comment]
@qiangxinglin I will suggest you create three separate series.

**Comment by qiangxinglin** [comment]
@pissang I prefer to make the color of the line between each data point changed gradually (from slight green -> slight red etc., which is based on the 2 endpoints). What's the purpose of the 3 separate series? I'm looking for features like this in [chart.js](https://www.chartjs.org/docs/3.2.0/samples/line/segments.html)

**Comment by pissang** [comment]
For example:
```ts
const data = [1, 2, 3, 4, 5];
const series0 = { type: 'line', lineStyle: {color: 'green' }, data: data.map(item => item > 3 ? item : '-') };
const series1 = { type: 'line', lineStyle: {color: 'red' }, data: data.map(item => item <= 3 ? item : '-') };
``

**Comment by qiangxinglin** [comment]
@pissang CMIIW, this will make a 3 colors line but the color is changed suddenly rather than gradually.

**Comment by pissang** [comment]
Understand, I thought you want the segmented line in your chart.js example link.

**Comment by qiangxinglin** [comment]
@pissang Any solution?

**Comment by qiangxinglin** [comment]
Yeah, I understand completely. So either the gradient is entirely vertial or horizontal, will this feature be supported in the future? Does this kind of render will consume too much memory? I'm really appreciate the development staff to make it come true :)

**Comment by pissang** [comment]
I'm afraid we won't support it in the near future. You can calculate the color stops and use a gradient object on the`lineStyle.color`.
