### ISSUE TITLE
Customize each legend color separately

### ISSUE THREAD

**Issue by brightzoe** [apache/echarts#15766]
#### Situation
the legend color inherts the color from option.color or data.itemStyle.color,or you can define one color . if I want the different colors from data.itemStyles, I could only use one color that makes legends show the same color.

expect it could support customize legend color sparately.

#### MyCase
I create a piechart,which expects the color is circular gradient. but there is  only linear gradient and radial gradient,I use linear gradient to simulate circular gradient,but the legend goes like the circular gradient, I want to customize the legend color gradient,but echarts don't support legend color array.

the legend goes like the circular gradient：
![image](https://user-images.githubusercontent.com/17716768/134320371-c1673c15-c472-4c31-965d-a98e85e410fd.png)

the performance I want:
![image](https://user-images.githubusercontent.com/17716768/134321202-bb107240-4a36-40be-934e-7518e56806b8.png)
legend gradient is different with piechart.

expect the legend colors supports array to customize every color.

#### Similar issues
https://github.com/apache/echarts/issues/6148

### What does the proposed API look like?
legend:{
  itemColor:[color1,color2...]
}

**Comment by plainheart** [comment]
Currently, you can configure like this,

```js
legend: {
  data: [{
    name: 'Legend Name',
    itemStyle: {
      color: 'red'
    }
  }]
}
```

Refer to https://echarts.apache.org/en/option.html#legend.data.itemStyle.color for more details.

**Comment by brightzoe** [comment]
> Currently, you can configure like this,
> 
> ```js
> legend: {
>   data: [{
>     name: 'Legend Name',
>     itemStyle: {
>       color: 'red'
>     }
>   }]
> }
> ```
> 
> Refer to https://echarts.apache.org/en/option.html#legend.data.itemStyle.color for more details.

@plainheart  Thanks ,I find the docs and usage of custimize legend. I didn't find the corresponding method till you help me. 

Echarts supported this ,It resolved,thank u!
