### ISSUE TITLE
关系图节点为图片时，下载截图功能失效。

### ISSUE THREAD

**Issue by ewansec** [apache/echarts#15769]
问题描述: 关系图节点为图片时，下载截图功能失效。
版本 ： "echarts": "^5.1.2",
当
 series.type=graph;layout=force
并且 
series.data.nodes.symbol='image://url' 时

toolbox.feature.saveAsImage 点击时报错   Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by plainheart** [comment]
注意图片的跨域问题。
