### ISSUE TITLE
Wrong data when use example `bar-large` with Float64Array

### ISSUE THREAD

**Issue by yyjdelete** [apache/echarts#15764]
### Version
5.2.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=bar-large&version=5.2.1](https://echarts.apache.org/examples/zh/editor.html?c=bar-large&version=5.2.1)

### Steps to reproduce
1. Open the above example
2. Edit and replace `valueData` in the last `return` with `Float64Array`
```
return {
    categoryData: categoryData,
    valueData: new Float64Array(valueData)
  };
```

### What is expected?
Get the same result as before, and only one `y` should be get for an special `x`
![image](https://user-images.githubusercontent.com/1819074/134301589-762d66ef-975d-485e-8ab7-5009abb0d247.png)

### What is actually happening?
Some garbage data is render, more than one `y` can be get for an special `x`
![image](https://user-images.githubusercontent.com/1819074/134301519-fd284ca3-d2d0-4094-ade1-be16b5abca63.png)

**Comment by pissang** [comment]
使用 TypedArray 的时候必须要在数据中显示指定 x 轴：

```ts
  for (let i = 0; i < count; i++) {
    categoryData.push(
      echarts.format.formatTime('yyyy-MM-dd\nhh:mm:ss', time, false)
    );
    valueData.push(i, next(i).toFixed(2));
    time += 1000;
  }
```

**Comment by yyjdelete** [comment]
@pissang 没看明白, 是说如果使用TypedArray 的时候, 数据必须按[x0, y0, x1, y1, ...] 这样的顺序填进去, 不能只有单独的y么?
就是像下面这样?
```js
  for (let i = 0; i < count; i++) {
    categoryData.push(
      echarts.format.formatTime('yyyy-MM-dd\nhh:mm:ss', time, false)
    );
    valueData.push(i);
    valueData.push(next(i).toFixed(2));
    time += 1000;
  }
  return {
    categoryData: categoryData,
    valueData: new Float64Array(valueData)
  };
```

**Comment by pissang** [comment]
是的
