### ISSUE TITLE
dataZoom click not working

### ISSUE THREAD

**Issue by tmtron** [apache/echarts#15775]
### Version
5.2.1

### Reproduction link
[https://jsfiddle.net/tmtron/9y0xtqs7/11/](https://jsfiddle.net/tmtron/9y0xtqs7/11/)

### Steps to reproduce
click on the dataZoom

### What is expected?
click event should be invoked

### What is actually happening?
click event is not invoked

---
The example from the [documentation: echartsInstance. on](https://echarts.apache.org/en/api.html#echartsInstance.on) is also not working:
```javascript
chart.on('click', 'dataZoom', function () {...});
```

* Other click events work: e.g. on the series, axis-labels (when `triggerEvent` is set to `true`)
* but for [dataZoom](https://echarts.apache.org/en/option.html#dataZoom), `triggerEvent` does not exist
* Maybe someone knows a temporary workaround?
  * I thought about using [echartsInstance.containPixel](https://echarts.apache.org/en/api.html#echartsInstance.containPixel), but it seems, that this does also not support `dataZoom`

**Comment by susiwen8** [comment]
@tmtron Hi，could you specify your demand? 
We are planning to add event to `dataZoom`, PR in #16171 , but we don't know what you want to receive when event invoked. Right now only `componentType` and `componentIndex` can be provided.

**Comment by tmtron** [comment]
# Use case

## Initial view
When we first show the chart, we display a high-level view of all available data - this is some aggregation data (e.g. when we show 5 years of data, we may have 1 data-sample per week)  
![image](https://user-images.githubusercontent.com/20422904/146154394-1b1de882-70cf-490c-8fbe-14d847cf4b8f.png)

## Zoom
When the user wants to see more details, they can use the zoom slider to zoom in to a part of the "coarse" data: e.g. zoom to 3 months (of the full 2 years data):  
![image](https://user-images.githubusercontent.com/20422904/146155032-d34d04df-b465-4e83-8eb2-846c6e8bd59f.png)

Note, that we did not load any new data - it's just the echarts zoom function: i.e. now the user will only see a part of the initial data - it is still "coarse" data (1 data-sample per week)

## Reload zoomed range
When the user now wants to see more details for the zoomed range, they can click on the zoom slider: we will reload more fine-grained data from the server for the currently selected date-range:  
![image](https://user-images.githubusercontent.com/20422904/146155372-9f17ebb6-a5f5-47b7-8182-b01271d1d4d9.png)

Note, that the recorder now loaded the new data from the server. This now shows exactly the data-range (27‑03‑2020…24‑06‑2020) that was previously selected in the data-zoom slider.  
This new data is now much finer: i.e. we now have 1 data-sample per 6 hours - so you can see much more details than in the previous step.

# Summary
So actually we need an event that fires when the user clicks on the data-zoom slider. It would be great if this event could also include the currently selected range: i.e. start/end like the [datazoom-event](https://echarts.apache.org/en/api.html#events.datazoom)

**Comment by susiwen8** [comment]
@tmtron Thanks for this precise demo, we will evaluate it. @pissang

**Comment by susiwen8** [comment]
@tmtron I have implemented `start/end` in PR, Please take a look.

**Comment by tmtron** [comment]
@susiwen8 looks good to me, thanks.

**Comment by pissang** [comment]
I'm not sure but it seems the [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event already did this work.

**Comment by pissang** [comment]
I'm not sure but it seems the [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event already did this work.

**Comment by pissang** [comment]
I'm not sure but it seems the [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event already did this work.

**Comment by tmtron** [comment]
> I'm not sure but it seems the [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event already did this work.

@pissang Not sure what you mean. This is what this bug-report is all about. The dataZoom click event does not work:
```typescript
chart.on('click', 'dataZoom', function () {...});
```
In this example the callback function will not be executed when you click on the data-zoom-slider.  
You can test it in the reproduction link: https://jsfiddle.net/tmtron/9y0xtqs7/11/  
* click events on the axis-labels or data-samples work: see console output
* but a click on the data-slider component does not work (and there is no `triggerEvent` property for the zoom-slider)

**Comment by susiwen8** [comment]
@pissang  I think we still need to add event for `dataZoom`. Then user can fetch data when click on `dataZoom`. As for `start/end`, user can get from `dataZoom action`

**Comment by pissang** [comment]
Sorry for accidentally closing this issue. Didn't remember how I did this.

I just want to make sure the use case make sense before we exposing a new event or other APIs to avoid forward compatiblity issues. What if we have more use cases in the future but have conflicts with the current exposed API?

  For example, when I click the `dataZoom`, what I expected is getting the `percent` of the point I clicked so I could do more things like move to this range, just like other events. But I don't think clicking on the dataZoom area to fetch more data is an intuitive user interaction. 

Especially when it having conflicts with our builtin user interaction that `click to select'. The selected window will be changed after I clicked the dataZoom. So what range should it use to fetch the data, the new one or the old one?

**Comment by tmtron** [comment]
> For example, when I click the `dataZoom`, what I expected is getting the `percent` of the point I clicked so I could do more things like move to this range, just like other events. 

That would for sure be good to have. 
I think, that you can always add additional data to the event without breaking backward-compatibility, right?  
e.g. adding `clickpointValue`, `clickpointPercent` properties

>But I don't think clicking on the dataZoom area to fetch more data is an intuitive user interaction.

Well, I don't know a better way to do this. However I am very open to suggestions.  
Some more info:
- In a first version we had an external button and menu entry to `Load the selected zoom region` - but that was inconvenient and clicking on the zoom slider directly is much preferred by the users.
- Later we auto-loaded the data after some time, but that was annoying to the users (and caused useless load on the server), so we deactivated this.  
- BTW: we also reload data when they click on a brush area

> Especially when it having conflicts with our builtin user interaction that `click to select'. The selected window will be changed after I clicked the dataZoom. So what range should it use to fetch the data, the new one or the old one? 

In this case, we would reload the old-data region (i.e. we don't use this click to move-window feature at all).  
However, when you want full support for this, then the event should contain the old range and the new range. 
And maybe even let the user cancel your default action (i.e. move the window to the new range).

>Also we can't provide any hint to users letting them know they can click the dataZoom to load more data now.

Well, we don't need such an indication - and if this is desired, the application can work around that:  
e.g. we could show a modal help window when the users use the zoom slider/brush for the first time, etc.

**Comment by pissang** [comment]
> you can always add additional data to the event without breaking backward-compatibility, right

That's what we don't want to see.  We are trying to keep all exposed API are simple and consistent. API that only solve one very specific case needs to be added very carefully. 

> Well, I don't know a better way to do this. However I am very open to suggestions.

From my side. Your first and second solution sounds more solid on the user experience. But that's only my humble opinion. I'm just not convinced that adding click event on `dataZoom` can provide a good enough solution to solve cases like this.

**Comment by tmtron** [comment]
>We are trying to keep all exposed API are simple and consistent. 

In the case of a click event for the data-zoom slider, there is anyway only very little info that you can send along:
* the click point
* optionally the selected range.  
  this is maybe not required, when you can also ask the chart-instance fot he currently selected range and maybe find out if the click-point is in the selected zoom range, or outside


>API that only solve one very specific case needs to be added very carefully.

A click event is something very generic and for sure not tied to a single use-case.  

There are many more things that this can be used for:  
e.g. we have a config mode, where the users can configure/move/resize the charts. in this mode, a click on the zoom slider could bring up a config dialog, where they can configure the slider: e.g. 
* [slider properties](https://echarts.apache.org/en/option.html#dataZoom-slider): color, handleSize, .. 
* a check-box if they want to show the slider at all

Another use-case that you have mentioned is the click-moves-the-zoom-window feature.  
This could easily be implemented by users of the library via this click event.  
Even better; we could implement our own strategy: e.g. maybe we want that clicking should not move the zoom window, but expand or shrink the window to the click-point


> > Well, I don't know a better way to do this. However I am very open to suggestions.
> 
> From my side. Your first and second solution sounds more solid on the user experience. But that's only my humble opinion. I'm just not convinced that adding click event on `dataZoom` can provide a good enough solution to solve cases like this.

Well, I also thought that at first. But in the meanwhile I have changed my mind and think that our users are right.  
When you use the zoom slider handles to select a suitable range, then you don't want to move the mouse away, to a button or menu - you want to immediately invoke the load-action by a simple click.

**Comment by pissang** [comment]
Sorry for can't merging the PR from @susiwen8 . Didn't notice it's a mistake from the doc.

We need to think through these questions carefully before we providing such a event.

1. Which part of the dataZoom can trigger the event. The whole component or only the slider. If it's only the slider, what about other parts of the dataZoom.
2. What event parameters we need to provide. And how developers can use them in their scenarios.
3. How should we handle the conflicts of loading action from click event handler and the default `dataZoom` action.
4. Is there a better way to do async loading on demand. For example, render a loading button around the slider, this button will trigger click event with necessary event parameters.
