### ISSUE TITLE
饼图label设置宽度，居中无效

### ISSUE THREAD

**Issue by leekbillow** [apache/echarts#15771]
### Version
5.2.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=xd370ntR39&v=1](https://www.makeapie.com/editor.html?c=xd370ntR39&v=1)

### Steps to reproduce
1.设置width
2.设置align:'center'

### What is expected?
label文字居中

### What is actually happening?
文字未居中，align属性不生效

### 详细描述
```js
option = {
  series: [
    {
      type: 'pie',
      radius: [20, 60],
      roseType: 'radius',
      data: [
        {
          value: 25,
          name: '男'
        },
        {
          value: 75,
          name: '女'
        },
      ],
      label: {
        shadowColor: '#00000050',
        shadowBlur: 10,
        height: 30,
        width: 80,
        align: 'center',
        verticalAlign: 'middle',
        backgroundColor: '#fff'
      }
    }
  ]
};

```
![image](https://user-images.githubusercontent.com/43409097/134480523-4018f783-387d-4ab4-8d1f-e7705431f0fa.png)

**Comment by Ovilia** [comment]
This is not a bug. But we should probably remove `align` and `verticalAlign` in the document.
https://www.makeapie.com/editor.html?c=xd370ntR39&v=2 This is how to make it align center.

**Comment by leekbillow** [comment]
> This is not a bug. But we should probably remove `align` and `verticalAlign` in the document.
> https://www.makeapie.com/editor.html?c=xd370ntR39&v=2 This is how to make it align center.

So this is a problem with stale documentation?

**Comment by Ovilia** [comment]
Not stale since these two options are never supported. According to the meaning of aligning, it makes no sense as used in pie charts.

**Comment by leekbillow** [comment]
> Not stale since these two options are never supported. According to the meaning of aligning, it makes no sense as used in pie charts.

Thank you for your answer.
