### ISSUE TITLE
4.9.0更新到5.2.1后，toolbox的提示文字变成英文了?

### ISSUE THREAD

**Issue by cjlhll** [apache/echarts#15774]
### Version
5.2.1

### Steps to reproduce
我从4.9.0更新到5.2.1后，toolbox的提示文字变成英文了。请问如何切换回中文呢？

### What is expected?
切换回中文

### What is actually happening?
是英文

**Comment by pissang** [comment]
现在默认是使用你的系统语言，可以在 init 的时候设置 locale: 'zh'

**Comment by cjlhll** [comment]
> 现在默认是使用你的系统语言，可以在 init 的时候设置 locale: 'zh'

谢谢。已解决。关键是我默认系统语言是中文。并不是英文

**Comment by plainheart** [comment]
默认是这么判断语言的
```js
document.documentElement.lang || navigator.language || navigator.browserLanguage
```
可能你的 html 声明的语言是 `en`

**Comment by cjlhll** [comment]
> 默认是这么判断语言的
> 
> ```js
> document.documentElement.lang || navigator.language || navigator.browserLanguage
> ```
> 
> 可能你的 html 声明的语言是 `en`

明白了。感谢。
