### ISSUE TITLE
xAxis.type="time"，显示时间戳时，会出现时间文字重叠

### ISSUE THREAD

**Issue by yundouguai** [apache/echarts#15788]
### Version
5.2.0

### Steps to reproduce
设置图表大小 width:700px;height:250px
设置X轴类型xAxis.type="time"
data传入20个间隔1秒的时间戳

### What is expected?
时间显示不重叠

### What is actually happening?
x轴时间显示文字重叠

**Comment by Ovilia** [comment]
5.2.1 可能已经修复了，请试一下

**Comment by yundouguai** [comment]
![image](https://user-images.githubusercontent.com/45409852/134802892-cde00f63-1bba-4769-8b79-66cabb232495.png)
试了还是会重叠

**Comment by plainheart** [comment]
时间轴上配置一下防重叠
```js
axisLabel: {
    hideOverlap: true
}
```

**Comment by yundouguai** [comment]
解决了
