### ISSUE TITLE
Combine echarts to generate a data visualization video

### ISSUE THREAD

**Issue by drawcall** [apache/echarts#15786]
Combining [FFCreator](https://github.com/tnfe/FFCreator) and [echarts](https://echarts.apache.org/zh/index.html), I implemented a function of dynamically generating data visualization videos. Of course I found that echarts and zrender have turned off some functions in node mode, not sure which features are hidden.

Demo: https://tnfe.github.io/FFCreator/_media/video/wonder/chart.mp4

Documentation: https://tnfe.github.io/FFCreator/#/guide/chart  

Oh no other questions, just a demo demonstration. Thanks to the author of echarts.

**Comment by pissang** [comment]
Wow it looks awesome! Thanks for letting us know!
