### ISSUE TITLE
在时间轴中，柱状图启用动态排序时，切换时间轴会影响其他图表的动画效果 比如 路径图 

### ISSUE THREAD

**Issue by ghost** [apache/echarts#15782]
### Version
5.2.0

### Steps to reproduce
配置时间轴组件，并添加柱状图，geo地图以及lines组件，lines启用动画效果并单独配置了zlevel，这时点击时间轴动画效果是正常的，当柱状图启用动态排序时，切换时间轴就会影响到lines的动画效果。

### What is expected?
动画效果互不干扰

### What is actually happening?
切换时间轴时，动态排序的柱状图动画会使lines的动画出现多次 看起来不顺畅。

**Comment by zhxxkeke** [comment]
补充下问题，切换时间轴时，连线会闪烁

**Comment by Ovilia** [comment]
提供一个最小复现的例子

**Comment by zhxxkeke** [comment]
https://www.makeapie.com/editor.html?c=xbs4W5bD6b&v=2
实例已提交，如果涟漪组件开启动画的话 切换时间轴 文本也会偏移 当前是关闭了动画

**Comment by zhxxkeke** [comment]
> 提供一个最小复现的例子

https://www.makeapie.com/editor.html?c=xbs4W5bD6b&v=2
实例已提交，如果涟漪组件开启动画的话 切换时间轴 文本也会偏移 当前是关闭了动画

**Comment by zhxxkeke** [comment]
> 动态排序的图不建议和其他图放在一个 dom 中，即使没有渲染上的 bug，性能也会受到很大影响。

谢谢 我找到解决办法了

**Comment by Ovilia** [comment]
不太明白这里为什么要两个 series 两个数据集？希望用动态柱状图的是哪个系列？

**Comment by zhxxkeke** [comment]
> 不太明白这里为什么要两个 series 两个数据集？希望用动态柱状图的是哪个系列？

两个 series 两个数据集 是对应时间轴中的每一天的数据呀，实例我只是举例了两天的数据 每天对应一个数据集 一共有7天，完整的应该有7个不一样的数据集，这样理解对的吧。。。。
用到动态柱状图的原因是，Y轴的数据是固定不变的，比如全国34个省的名称，但是时间轴中每一天的X轴数我只显示其中10个省的数据，而且每一天的Y轴都不一样，这导致了会显示24个空缺，非常不美观。虽然动态柱状图效果实现了 但是动画联动有BUG
我就改用数据集来实现 实例的写法我是安装官网的教程来写的呀 没问题的呀
简单来说 想要实现的效果就是一个柱状图，切换时间轴 Y轴和X轴显示的数据都不一样 举个例子。。。 10月1号Y轴显示浙江省的数据，10月2号Y轴显示上海市的数据  等等。。。
