### ISSUE TITLE
何时提供K线图log对数坐标支持？

### ISSUE THREAD

**Issue by supperman009** [apache/echarts#15783]
### What problem does this feature solve?
K线图使用原始数据绘图呈现，会导致图形失真。呈现时应该将数据对数化处理后再呈现。才能保证K线图中，涨幅一样的K线高度一致，图形与数据才一致。数据轴依然现实原始日期和原始对应的价格或涨跌百分比。
请问何时可以提供？

### What does the proposed API look like?
```js
option = {
  legend: {
    data: ['日K', 'MA5', 'MA10', 'MA20', 'MA30'],
    inactiveColor: '#777'，
    LogMode：‘true’
  },
```

**Comment by pissang** [comment]
y 轴设置成 type: 'log'
