### ISSUE TITLE
Event data missing on axis label click

### ISSUE THREAD

**Issue by pierrebonny** [apache/echarts#15798]
### What problem does this feature solve?
When user trigger a mouse event on an axis label you cannot know its index. The main goal is to know on which label the user doies any mouse action.
In V4 it was possible to send an object as axis data so that the event can pass it when triggered. In that object I put an id to resolve my feature. Now you can only pass a string to the axis data so I cannot do this anymore.

### What does the proposed API look like?
I would like an additional data in the axis label event click with an index corresponding.
i.e: If I click on the first label of my axis I would like to get index 0. 
Else it can be ok to pass an id to the axis label data and get it in the mouse event

**Comment by pierrebonny** [comment]
@pissang @Ovilia Please help, thanks

**Comment by ouassimBenMosbah** [comment]
Same problem here. I would like to send back object or at least add an id.

**Comment by pierrebonny** [comment]
Here is a demo of what I used to do before V5:
https://codepen.io/Pierre63/pen/LYjNJOq
