### ISSUE TITLE
treemap矩阵图无法设置背景图片

### ISSUE THREAD

**Issue by dingpeiyang001** [apache/echarts#15792]
### What problem does this feature solve?
treemap矩阵图,只能设置每个矩形的颜色，无法给每个矩形设置背景图片来代替颜色

### What does the proposed API look like?
期望每个矩形能有个backgroundImage: '图片地址'

**Comment by plainheart** [comment]
可以给每个 data item 设置 `itemStyle`

```js
itemStyle: {
  color: {
    image: 'https://xx.com/xxx.png'
  }
}
```

**Comment by dingpeiyang001** [comment]
> 可以给每个 data item 设置 `itemStyle`
> 
> ```js
> itemStyle: {
>   color: {
>     image: 'https://xx.com/xxx.png'
>   }
> }
> ```

 太牛逼了，非常感谢
