### ISSUE TITLE
男女左右对比的横向柱状图

### ISSUE THREAD

**Issue by xuechao-shi** [apache/echarts#15806]
### What problem does this feature solve?
这个需求他既有男性和女性还有未知性别的所以这个柱状图男女分两边柱子挨着的地方还要一块空白

### What does the proposed API look like?
希望有解决方案

**Comment by Ovilia** [comment]
用两个 grid 两个 xAxis 两个 series，参考：https://echarts.apache.org/examples/zh/editor.html?c=dataset-series-layout-by
