### ISSUE TITLE
图例颜色能否单独设置，不与数据项关联？

### ISSUE THREAD

**Issue by leekbillow** [apache/echarts#15805]
### What problem does this feature solve?
数据项设置了渐变颜色（主色 边缘渐变），图例想使用主色展示
The data item has a gradient color set (primary color   edge gradient). The legend wants to use the primary color for display  
https://www.makeapie.com/editor.html?c=xd370ntR39&v=3

### What does the proposed API look like?
legend的color能够支持function
The legend "color" supports "function"

**Comment by Ovilia** [comment]
可以的，配置项：[legend.data.itemStyle](https://echarts.apache.org/zh/option.html#legend.data.itemStyle)

```
  legend: {
    data: ['男'],
    itemStyle: {
      color: 'red'
    }
  },
```

**Comment by leekbillow** [comment]
> 可以的，配置项：[legend.data.itemStyle](https://echarts.apache.org/zh/option.html#legend.data.itemStyle)
> 
> ```
>   legend: {
>     data: ['男'],
>     itemStyle: {
>       color: 'red'
>     }
>   },
> ```

统一设置图例颜色是可以的，但是能否动态设置呢？function我试过不支持，设置color数组的话会被数据项的颜色覆盖

**Comment by Ovilia** [comment]
动态是什么意思？`setOption` 的时候重写设置 legend.data.itemStyle 是可以的

**Comment by leekbillow** [comment]
> 动态是什么意思？`setOption` 的时候重写设置 legend.data.itemStyle 是可以的

根据数据项来取值（其实就是支持function），比如这个图我使用渐变色渐变边缘，但是图例希望使用原本的主色
![image](https://user-images.githubusercontent.com/43409097/135237749-bfe6bd22-4893-48d8-8ce2-0c970a10df56.png)

**Comment by Ovilia** [comment]
哦我例子写错了，应该是

```
  legend: {
    data: [{
        name: '男',
        itemStyle: {
              color: 'red'
        }
    }]
  },
```

**Comment by leekbillow** [comment]
> 哦我例子写错了，应该是
> 
> ```
>   legend: {
>     data: [{
>         name: '男',
>         itemStyle: {
>               color: 'red'
>         }
>     }]
>   },
> ```

问题解决，感谢你抽出时间进行回复

**Comment by cooper1x** [comment]
@Ovilia 如果在series中的itemStyle中设置了渐变色，legend.data.itemStyle会失效，这个怎么解决呢？

**Comment by cooper1x** [comment]
找到问题原因了，在series里面设置了itemStyle的渐变色，这个会直接覆盖掉data里面的itemStyle。
所以面积图的折线面积渐变要写在series.areaStyle里面，然后用series.itemStyle设置为纯色。
