### ISSUE TITLE
现在是每个矩形可以填充图片了，但是图片怎么正好铺满整个矩形而且图片不变形，就像background-size: 'cover'一样

### ISSUE THREAD

**Issue by dingpeiyang001** [apache/echarts#15812]
### What problem does this feature solve?
解决矩形图填充背景图的功能

### What does the proposed API look like?
data 里
```ts
itemStyle: {
 color: {
  image: "",
  size: 'cover'
}
}
```

**Comment by Ovilia** [comment]
请使用自定义系列实现该需求 https://echarts.apache.org/zh/option.html#series-custom
