### ISSUE TITLE
堆叠折线图展示与数据对应不上

### ISSUE THREAD

**Issue by fengbindev** [apache/echarts#15819]
![image](https://user-images.githubusercontent.com/28595220/135379545-ff27a80b-3c49-41f5-9e91-6acdf77dd171.png)
第一个设置为100 却标记到了110，最后一列颜色为蓝色，却标记成绿色分类了。

**Comment by plainheart** [comment]
都说是堆叠了...

**Comment by fengbindev** [comment]
是的，搞错了，不好意思。

**Comment by pissang** [comment]
@fengbindev 不要把问题内容都删掉
