### ISSUE TITLE
Axis labels can end up overlapping when the chart resizes due to dynamic data updates

### ISSUE THREAD

**Issue by 4scastro** [apache/echarts#15813]
### Version
5.2.0

### Steps to reproduce
1. Start with the dynamic data example: https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2
2. Change the interval value from 1000 to 50.
3. Re-run the code and observe the axes,

### What is expected?
That the ticks and labels are equally spaced and the labels don't overlap

### What is actually happening?
On the X or Y axis, as new data is added and the axis is resized, you see a new label pop up on top of the old one, and the old one will gradually move down to its proper position. Besides the issue of readability, it indicates that one of the labels is wrong. Furthermore, the lower end of the axes ends up being relatively unused. It reminds me of a logarithmic scale!

EDIT: tried turning off showMaxLabel for the X/Y axes. This helped, but the problem is still there - attached a screenshot when these are both set to false, the overlapped labels are clear, as is the unequally spaced labels (see 300, 600 and 900 on the Y axis).

---
I found this bug by adapting this example code to be updated more frequently (graphing data from 60 FPS video) over a shorter timescale. I tried various things to try and workaround what now seems like a bug to me. Then I decided I'd see if this was a problem with the example code that I started with, and found that by simply increasing the speed at which new data is added it was enough to reproduce the problem.

In the short term I'd be grateful if someone could suggest a workaround for manipulating the ticks/labels manually to stop this from happening.

![image](https://user-images.githubusercontent.com/26650102/135287302-ffc3e5f8-f68a-4c42-abf3-5d0dcbb50469.png)

**Comment by pissang** [comment]
It's better to turn off animation if the interval is smaller than the animation duration

**Comment by 4scastro** [comment]
That's resolved the issue, thanks.
