### ISSUE TITLE
Documentation to create custom series

### ISSUE THREAD

**Issue by throrin19** [apache/echarts#15824]
### What problem does this feature solve?
Have a guide or simple documentation to create easilly new echart serie like liquidFill, wordCloud, ...

Actually, all methods used in this projects are not documented and it's impossible to create our own echart plugin for now. This documentation is really important for us and it would allow us to quickly develop several new types of series (discrete, bullet chart, horizon, ...)

**Comment by Ovilia** [comment]
Hi, sorry for this but we don't have the document for making a chart plugin because there are too many internal APIs need to be explained and we do not have the effort to do this.
It is recommended to use [custom series](https://echarts.apache.org/en/option.html#series-custom) and this part is well documented.

**Comment by throrin19** [comment]
Ok, I understand that. This API would easily allow others to offer plugins for brand new visualizations.

I'm going to try to work my way through the custom series to do what I want easily. And see how to make this reusable by others through modules.

**Comment by Ovilia** [comment]
If you would like to make extensions like wordCloud or liquillFill, I'm afraid you should have to read the source code of these current extensions to find out what should be done. You are welcomed to open issues if you need extra help doing so. But sorry again that we do not have effort to provide internal document of it.

**Comment by throrin19** [comment]
Actually, I looked and my data format is not the same as theirs, I end up with Echart errors without understanding how to fix it or have something functional (especially for the `getInitialData` part in `echarts.extendSeriesModel`)
