### ISSUE TITLE
Render custom bar plot with log scale

### ISSUE THREAD

**Issue by nhhaidee** [apache/echarts#15832]
### Version
5.2.1

### Steps to reproduce

Please see attached file 
[custom_bar.zip](https://github.com/apache/echarts/files/7295189/custom_bar.zip)

      const colorList = [
        "#4f81bd",
        "#c0504d",
        "#9bbb59",
        "#604a7b",
        "#948a54",
        "#e46c0b",
      ];
      const data = [
        //start, end, height
        [10, 16, 300, "A"],
        [16, 18, 200, "B"],
        [18, 26, 350, "C"],
        [26, 32, 450.35, "D"],
        [40, 56, 600, "E"],
        [80, 90, 150, "F"],
      ].map(function (item, index) {
        return {
          value: item,
          itemStyle: {
            color: colorList[index],
          },
        };
      });
      option = {
        title: {
          text: "Profit",
          left: "center",
        },
        tooltip: {},
        xAxis: {
          scale: false,
          min: 1,
          max: 100,
        },
        dataZoom: [
          {
            type: "slider",
            show: false,
            filterMode: "none",
          },
          {
            type: "inside",
            filterMode: "none",
          },
        ],
        yAxis: {
          type: "log",
          min: 1,
		      max: 1000,
          minorSplitLine: {
            show: true,
          },
        },
        series: [
          {
            type: "custom",
            renderItem: function (params, api) {
              var yValue = api.value(2);
              var start = api.coord([api.value(0), yValue]);
              var x = start[0]
              var y = start[1]
              var width = api.size([api.value(1) - api.value(0)]);
              var height = api.size([yValue]);
              console.log(height)
              return {
                type: "rect",
                shape: {
                  x: x,
                  y: y,
                  width: width[0],
                  height: height[0]
                },
                style: api.style(),
              };
            },
            label: {
              show: true,
              position: "top",
            },
            dimensions: ["Start", "End", "Depth"],
            encode: {
              x: [0, 1],
              y: 2,
              tooltip: [0, 1, 2],
              itemName: 3,
            },
            data: data,
          },
        ],
      };

### What is expected?
custom bar plot is rendered correctly 

### What is actually happening?
custom bar plot is not rendered correctly

**Comment by nhhaidee** [comment]
The custom bar plot:
![custome_bar_plot_result](https://user-images.githubusercontent.com/30271407/136233521-5e9294f0-569a-416e-b731-373e182db459.png)

**Comment by Ovilia** [comment]
It should be 

```js
renderItem: function (params, api) {
    var yValue = api.value(2);
    var start = api.coord([api.value(0), yValue]);
    var x = start[0]
    var y = start[1]
    var size = api.size([api.value(1) - api.value(0), yValue]);
    return {
    type: "rect",
    shape: {
        x: x,
        y: y,
        width: size[0],
        height: size[1]
    },
    style: api.style(),
    };
},
```

According to [api.size](https://echarts.apache.org/en/option.html#series-custom.renderItem.arguments.api.size), you should not omit the second parameter for log axis.

> In some coordinate systems (for example, polar) or when log axis is used, the size is different in different point. So the second parameter is necessary to calculate size on the given point.

**Comment by nhhaidee** [comment]
Hi @Ovilia 

Here is reproducible demo https://codesandbox.io/s/naughty-sun-k9zul
The chart can not be rendered if 
```
  yAxis: {
    type: "log",
    min: 1
  },
```
It is OK if change type is value

**Comment by Ovilia** [comment]
Marked to be a bug.

**Comment by pissang** [comment]
Have you used the `clipRectByRect` method as the example is using?

**Comment by nhhaidee** [comment]
@Ovilia At line 426 `return` code

zoom-in works well
``` 
      return rectShape && {
        type: "rect",
        shape: rectShape,
        style: api.style()
      };

```

If you remove `rectShape &&`, custom bar will be distorted when zoom in. I don't know the reason why and what are the differences between 2 codes
```
      return {
        type: "rect",
        shape: rectShape,
        style: api.style()
      };
```

**Comment by yasser-de** [comment]
Does the legend property not work for this chart type?
