### ISSUE TITLE
tree树图 标记

### ISSUE THREAD

**Issue by zym0110** [apache/echarts#15842]
### Version
5.2.0

### Steps to reproduce
当标记或图片是透明的时，是否有方法覆盖背面线条

### What is expected?
覆盖背面线条

### What is actually happening?
显示线

**Comment by zym0110** [comment]
![image](https://user-images.githubusercontent.com/48800373/136640058-d106b7f0-af6d-4534-9e2d-fb050b3bced2.png)

**Comment by Ovilia** [comment]
label.backgroundColor

**Comment by zym0110** [comment]
![image](https://user-images.githubusercontent.com/48800373/136720720-fde4a087-b07a-4f62-871a-ac611159372d.png)
好像不行,标签透明还是能看到后面的线

**Comment by pissang** [comment]
@zym0110 是标签不要透明
