### ISSUE TITLE
vue3使用ref变量获取id节点导致trigger:axis无法显示提示框，item则不会影响

### ISSUE THREAD

**Issue by cheerfulHuhan** [apache/echarts#15845]
### Steps to reproduce
将document.getElementById返回结果赋值给vue3的ref变量会导致echarts  trigger:axis属性折线图提示框无法显示

### What is expected?
能够显示折线图axis的结果

### What is actually happening?
无法显示

**Comment by plainheart** [comment]
echarts 实例对象不要用 `ref`，请使用 `shallowRef` 或者普通变量。
