### ISSUE TITLE
line chart render error with google version 94.0.4606.81

### ISSUE THREAD

**Issue by Idletalk** [apache/echarts#15843]
### Version
5.0.2

### Reproduction link
[https://codesandbox.io/s/echarts-line-chart-f3zn7](https://codesandbox.io/s/echarts-line-chart-f3zn7)

### Steps to reproduce
Open the sandbox address above，create a new TAB to reopen the url such as https://f3zn7.csb.app/  with full screen, then the line 【legend2】 abnormal display
![image](https://user-images.githubusercontent.com/38195804/136640738-e173613e-257d-4da6-88bf-48b4006a206e.png)

### What is expected?
line【legend2】 normal display
![image](https://user-images.githubusercontent.com/38195804/136640759-8c7dc6e5-1db4-4460-8b67-990dc8d03192.png)

### What is actually happening?
line【legend2】 abnormal display

**Comment by pissang** [comment]
Opened a bug report to chromium team

https://bugs.chromium.org/p/chromium/issues/detail?id=1258266

**Comment by shannonfarvolden** [comment]
> I'm not sure, but it seems to be a bug in chrome when `lineWidth` is 3. You can set
> 
> ```ts
> emphasis: {
>   lineStyle: {
>     width: 2
>   }
> }
> ```
> 
> to workaround.

Running into the same issue. This workaround does not work for me either.
