### ISSUE TITLE
echart tree 点击节点,连接线未消失

### ISSUE THREAD

**Issue by zym0110** [apache/echarts#15841]
### Version
5.2.0

### Steps to reproduce
echart tree 
当edgeShape: "polyline"时,连续点击节点,收缩下级时,收缩的节点连接线未消失

### What is expected?
点击节点,收缩的连接线能消失

### What is actually happening?
连接线残留在画布上

**Comment by susiwen8** [comment]
和这个一样的问题吗？ #13503
