### ISSUE TITLE
使用universalTransition切换柱状图和散点图(官方示例)，将柱状图的柱子颜色改为渐变色，渐变不生效

### ISSUE THREAD

**Issue by himushroom** [apache/echarts#15856]
### Version
5.2.1

### Reproduction link
[https://www.makeapie.com/editor.html?c=xLyBMHHT8a&v=1](https://www.makeapie.com/editor.html?c=xLyBMHHT8a&v=1)

### Steps to reproduce
使用universalTransition进行不同图形的切换，series[bar].itemStyle.color设置为任意渐变色，渐变色不生效

### What is expected?
universalTransition切换不同chart时，bar-chart的渐变可以正常显示

### What is actually happening?
universalTransition切换不同chart时，bar-chart的渐变不能正常显示

**Comment by pissang** [comment]
5.3 以支持渐变色之间的动画，但是纯色和渐变色之间暂时未支持
