### ISSUE TITLE
动态排序柱状图柱子显示不全。有时候有，有时候没有。参考：动态排序柱状图 - 人均收入

### ISSUE THREAD

**Issue by robin-repo** [apache/echarts#15868]
### Version
5.2

### Steps to reproduce
动态排序柱状图柱子显示不全。有时候有，有时候没有。

### What is expected?
动态排序柱状图柱子显示不全。有时候有，有时候没有。

### What is actually happening?
动态排序柱状图柱子显示不全。有时候有，有时候没有。

**Comment by robin-repo** [comment]
![image](https://user-images.githubusercontent.com/48324500/136932379-80121b71-e476-4d5d-ad27-f9ce0948b703.png)
有数据但不显示，只有一条

**Comment by robin-repo** [comment]
应该要有柱子显示的，但是没有

**Comment by plainheart** [comment]
数据有点缺失，每天每个客户都应该有数据项才可以。

**Comment by Ovilia** [comment]
（👆上面一行的 mentioned 是手误，请勿略）
