### ISSUE TITLE
@4.8.* 升级到@5.0.2 ts 报错

### ISSUE THREAD

**Issue by Mingsars** [apache/echarts#15873]
### Version
5.0.2

### Steps to reproduce
angular项目中原来使用的是echarts@4.8.2，升级到 echarts@5.0.2之后，ts校验报错，但是不影响页面的正常运行。
报错信息如下

ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts
[tsl] ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts(421,55)
      TS1005: ',' expected.

ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts
[tsl] ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts(421,61)
      TS1005: ',' expected.

ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts
[tsl] ERROR in D:\codehubWork\NetStarNetworkConsultingWebSite\ui-source\node_modules\echarts\types\dist\echarts.d.ts(422,74)
      TS1005: ',' expected

### What is expected?
希望告知如何消除这些报错，谢谢。

### What is actually happening?
项目正常运行，但是ts校验报错。

**Comment by pissang** [comment]
这个报错信息看不出来具体的信息，你的 ts 版本是多少？

**Comment by Mingsars** [comment]
@pissang typescript@3.3.4

**Comment by pissang** [comment]
@Mingsars echarts 支持的最小 ts 版本是 3.5.0

**Comment by Mingsars** [comment]
搞定了，谢谢
