### ISSUE TITLE
VisualMap draws abnormally when there are negative numbers

### ISSUE THREAD

**Issue by Alexander-txj** [apache/echarts#15885]
### Version
5.2.1

### Reproduction link
[https://codepen.io/alexander-txj/pen/xxdaOGa](https://codepen.io/alexander-txj/pen/xxdaOGa)

### Steps to reproduce
The curve should be drawn in black, but when the negative number is set to the minimum value, the curve is red; when the minimum value is set to 0, the curve drawing is normal again
![image](https://user-images.githubusercontent.com/25924952/137425620-8af05cae-591e-4eaa-a17f-4a16385e7f70.png)

### What is expected?
The curve should be black

### What is actually happening?
The result curve is red

---
Fix the error

**Comment by plainheart** [comment]
Another similar issue is #15877. Is it caused by our new implementation of the line gradient drawing introduced in #15711? @pissang
