### ISSUE TITLE
universalTransition for time series data

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#15918]
### What problem does this feature solve?
I have a timeseries data that can switch between monthly, quarterly and yearly aggregate views and plotted either as a line or bar chart. The 5.2.0 feature of universalTransition is great but doesn't seem to be suitable for this type of data. What is happening is that lower granular data has more data points and so toggling from lower granular to higher granular view just removes all the points to the right and expands the starting set of points to occupy the entire chart. What is ideal is that all the monthly data should more into quarterly/yearly data. Similarly, when changing from year to month should similarly transform each year data points into it's corresponding monthly points.

The challenge I see is that the chart doesn't have the knowledge of this `rollup`. Such a rollup is also possible for other types of hierarchical dimensions such as geography. 

### What does the proposed API look like?
I am not entirely sure. If this is too specific, then if there is some way to create custom animations then that would be great.

**Comment by pissang** [comment]
I'm not sure if it's what you want. Universal transition can be applied on the drilldown/rollup case. Here is an example 
https://echarts.apache.org/examples/zh/editor.html?c=bar-drilldown

The key is using the same `dataGroupId` to mapping the data.

**Comment by dirslashls** [comment]
Thanks @pissang . My use case is to be able to drill-down multiple levels, say Continent to Country to State. To do this, the data for Country should indicate which Continent it belong to and also the data for Country needs to indicate which Country groupId it belongs to so the transition can use that GroupId at the State level.
