### ISSUE TITLE
version 4.9.0 bmap need update two lines

### ISSUE THREAD

**Issue by EricHe56** [apache/echarts#15920]
### Version
4.9.0

### Steps to reproduce
bmap style cannot working. please update below lines:

1. echarts/extension/bmap/BMapView.js line: 120 newMapStyle2 should be newMapStyle, as it is working for map 2.0 

2. echarts/dist/extension/bmap.js line: 390 newMapStyle2 should be newMapStyle, as it is working for map 2.0 

Please update those code,

Thanks

### What is expected?
set bmap style for map 2.0

### What is actually happening?
doesn't work for map 2.0

**Comment by plainheart** [comment]
I'm sorry but I'm afraid you have to use the new bmap extension of ECharts v5. It' was brought by a typo in v4.9.0. Download the bmap extension scripts and put them into your project manually.

**Comment by plainheart** [comment]
I'm sorry I didn't make me clear. v4 won't get updated anymore. I mean you don't need to install the v5 and instead it's enough to download the bmap scripts of v5.
