### ISSUE TITLE
Highlight graph links programmatically

### ISSUE THREAD

**Issue by jozsefm** [apache/echarts#15927]
### What problem does this feature solve?
I want to be able to highlight a custom path in a complex graph to showcase only the specific insights my customers are interested in. I want to be able to transitively highlight all connected links and nodes from the currently highlighted element (link or node), like a complete path. The current `focus: 'adjacency'` option only goes to a single level and without an option to filter which links to highlight. I didn't find any way to programmatically highlight links. The `dispatchAction` method only allows to highlight nodes in the graph chart type through the dataIndex or name fields. The links have names as well: `[id1] > [id2]` but these are not recognized in the method.

### What does the proposed API look like?
Either provide a `linkIndex?: number | number[]` field in the `dispatchAction` method and/or make it recognize link names and/or offer the option to use `itemStyle` or `lineStyle` config on the individual link objects in the links field of a series so a new `setOptions` call would be enough to update the style of the links. Please let me know if there is a way to solve this that I missed. Either way, thanks for the great lib!

**Comment by ElayGelbart** [comment]
when this will be fixed? is there any updates ?
