### ISSUE TITLE
https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush&lang=js  成交量问题

### ISSUE THREAD

**Issue by linwf88** [apache/echarts#15939]
### Version
5.2.1

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush&lang=js](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush&lang=js)

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush&lang=js 在代码中比如line 239 r
添加一个均线，比如 MA60(相应的41行变为data: ['Dow-Jones index', 'MA5', 'MA10', 'MA20', 'MA30', 'MA60'])
        {
          name: 'MA60',
          type: 'line',
          data: calculateMA(60, data),
          smooth: true,
          lineStyle: {
            opacity: 0.5
          }
        },
;则画出的成交量柱状图就有问题了:本来是阳线红色，阴线绿色，现在一律变成蓝色... 不是添加的内容不对，而是数量文替，把前面一个MA5删掉(保留新加的MA60)，又恢复正常。。。

### What is expected?
多一条均线，其他照旧

### What is actually happening?
成交量volume颜色发生变化

**Comment by Ovilia** [comment]
`visualMap.seriesIndex` 也需要 +1 变成 6
