### ISSUE TITLE
Gaps showing in stacked bar chart between series

### ISSUE THREAD

**Issue by hughess** [apache/echarts#15936]
### Version
5.2.1

### Steps to Reproduce
Normal stacked bar rendered with SVG. Height of chart container = 250px, width = 100%.

### What is expected?
Expect all series in stack to touch each other without whitespace in between

### What is actually happening?
Small gaps appear between layers of the stack. Gaps appear inconsistently and change with zoom level. This is most apparent in the turquoise series below:
![CleanShot 2021-10-22 at 15 31 56](https://user-images.githubusercontent.com/12602440/138604062-1b487695-b08a-4d33-b45d-7020e0ec6032.png)

### Other Notes
One way this might be solved is to add a border to each bar series that is the same color as the series. I haven't been able to figure out how to apply the same color to the border of the bar. Is there a way to reference the color palette used for multiple series? E.g., for the first series in a chart, how could I reference the first color in the global palette to use elsewhere in the chart?

**Comment by ManishBisht777** [comment]
Currently on version 5.5.0 the issue is still there

**Comment by ricardoguerreiroOptiply** [comment]
can we reopen and address this issue? seems to still happen and can´t find any configuration to tweak it:

![image](https://github.com/apache/echarts/assets/125864864/553e18a3-ba15-4af8-935f-98cae6107a9f)
