### ISSUE TITLE
Options to apply bar border to specific sides of the bar

### ISSUE THREAD

**Issue by hughess** [apache/echarts#15934]
### What problem does this feature solve?
When adding a border to the bars in a bar chart, I expect to see a border on 3 sides (top, left, and right), not all 4. I prefer the bottom border to be left empty for 2 reasons:
 1. Avoid having a border sitting on top of the axis baseline (looks messy)
 2. Avoid border overlap when creating a stacked bar chart (the top border of each bar should act as the bottom border of the bar above it)

This is a similar problem to border radius, where it was solved using an array to specify each side. I think that could work for border width too.

### What does the proposed API look like?
```javascript
itemStyle: {
    borderWidth: [0, 1, 1, 1]
}
```

**Comment by SevenOutman** [comment]
+1 Needing this feature to achieve design like this:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/8225666/155701166-40262ac6-c0c0-46d1-b229-e2f736a1200d.png">

**Comment by Always-prog** [comment]
+1 here

**Comment by james-astra** [comment]
+1

**Comment by robdjonge** [comment]
+1 Fix would be much appreciated!

**Comment by ksknote** [comment]
+1
