### ISSUE TITLE
use pictorialBar width svg path ,  if datas includes 0 and use borderWidth，display effect bug

### ISSUE THREAD

**Issue by 364593653** [apache/echarts#15940]
### Version
5.2.1

### Reproduction link
[https://jsbin.com/xikohuy/edit?html,js,output](https://jsbin.com/xikohuy/edit?html,js,output)

### Steps to reproduce
as the example： https://jsbin.com/xikohuy/edit?html,js,output

only when borderWidth  value  is 0, no bug

使用svg path象形柱图时，如果数据中有0，并且itemStyle中使用borderWidth属性，鼠标放到数据为0的那一列时显示会有bug

官方文档中的例子只要增加borderWidth属性，data数组值有0就会出现这个问题

### What is expected?
显示正常
display no bug

### What is actually happening?
官方文档中的例子只要增加borderWidth属性，data数组值有0就会出现样式问题

**Comment by plainheart** [comment]
Fixed in #12793
