### ISSUE TITLE
Create Horizontal Bar chart using both axis as type 'Value'.

### ISSUE THREAD

**Issue by spoojaj** [apache/echarts#15960]
### Version
5.2.2-rc.1

### Steps to reproduce
1) take any horizontal bar chart example from E-chart examples
2) make y axis as type 'value'
3) bars will be verticle.

### What is expected?
should get the horizontal bar chart with y axis as type 'value'.

### What is actually happening?
getting vertical bar chart if we use y axis as type 'value'

**Comment by Ovilia** [comment]
Custom series is required. See [examples](https://echarts.apache.org/examples/en/index.html#chart-type-custom) and [doc](https://echarts.apache.org/en/option.html#series-custom).

**Comment by pbberlin** [comment]
I habe the same requirement/request, as the 2 users above.
