### ISSUE TITLE
Toolbox and legend unresponsive at high data update rate

### ISSUE THREAD

**Issue by schwingkopf** [apache/echarts#15965]
### Version
5.2.1

### Reproduction link
[https://echarts.apache.org/examples/en/editor.html?c=dynamic-data](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data)

### Steps to reproduce
Use the "dynamic data" example from the docs and reduce update interval from 2100ms to 100ms. Then try to click on the legend items to disable the bar/line or try to interact with the toolbox items.

### What is expected?
The toolbox and legend items should stay responsive

### What is actually happening?
Clicking toolbox or legend item has no effect

---
It seems the full chart is being re-rendered (or at least it's state being reset) upon each update of the data, instead of just the axes and series. This is a huge drawback in usability for applications with dynamic data update rates above ~3Hz, as basic functions like  zooming via toolbox item, as well as activation/deactivation of a series via legend become impossible to use.

**Comment by omerbarda5** [comment]
Is there any update to solve this?
