### ISSUE TITLE
Is it possible to disable select legend, which is generated by visualmap-piecewise?

### ISSUE THREAD

**Issue by lmulin** [apache/echarts#15975]
### Version
5.2.0

### Steps to reproduce
The value of Selected Mode (data type string) in visualmap-piecewise can be 'multiple' (multiple selection) or 'single' (single selection).
It would be helpful to enable the value 'false', too. Just like the legend. selectedMode (data type string, boolean).

### What is expected?
The value false can be used in visualmap-piecewise.selectedmode to disable the selection.

### What is actually happening?
It is not possible.

**Comment by YuriyDyachkov** [comment]
Please add this feature!
