### ISSUE TITLE
Chromium 95.0.4638.69 update causing tooltip lags

### ISSUE THREAD

**Issue by pieroliviermarquis** [apache/echarts#15979]
### Version
5.2.1

### Steps to reproduce
Using echarts 5.2.1 with Chromium 95.0.4638.69. The chromium update is causing lags in the tooltip. When hovering over the charts for several seconds, the whole page slows down.

"echarts": "^5.2.1"
"vue-echarts": "^6.0.0"

### What is expected?
Smooth scrolling.

### What is actually happening?
Lags.

**Comment by plainheart** [comment]
@pieroliviermarquis Hi, may I know about what happened? For the tooltip lag issue, we ever fixed it in v5.2.1. Does it still exist?

**Comment by pieroliviermarquis** [comment]
@plainheart No, sorry. It's a mistake. The update did fix the issue.
