### ISSUE TITLE
How to get Horizontal Orientation of Bar Chart when Y-Axis is of 'Value' type

### ISSUE THREAD

**Issue by mohitjain0824** [apache/echarts#15978]
### Version
5.2.1

### Steps to reproduce
1. Open link: https://echarts.apache.org/examples/en/editor.html?c=bar-background
2. Replace the whole context with the below code:
==========================

option = {
title: {
text: 'Depth Vs Level Of Concern'
},
tooltip: {
trigger: 'axis',
axisPointer: {
type: 'shadow'
}
},
xAxis: {
type: 'value',
name : 'Level of concern'
},
yAxis: {
type: 'value',
name : 'Depth'
},
series: [
{
type: 'bar',
data: [[40,100], [50,200], [60,500], [60,800]] // [xAxis, yAxis]
}
]
};

==========================

### What is expected?
We want X and Y axes to be 'Value' type and bars to be horizontally aligned 'on' Y-Axis.

### What is actually happening?
The bars are always aligned on X-Axis.

---
Our X and Y axes are not discrete values. They are continuous values.

**Comment by Ovilia** [comment]
Custom series is required. See [examples](https://echarts.apache.org/examples/en/index.html#chart-type-custom) and [doc](https://echarts.apache.org/en/option.html#series-custom).
