### ISSUE TITLE
Using pie chart in vue 2.6.13,  set "series.pie.itemStyle.borderColor: rgba(0, 0, 0, 0) " is not valiable

### ISSUE THREAD

**Issue by chenp1204** [apache/echarts#15983]
### Version
5.2.1

### Steps to reproduce
The follow is config option:

```js
option = {
  tooltip: {
    trigger: 'item'
  },
  legend: {
    top: '5%',
    left: 'center'
  },
  series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      itemStyle: {
        borderColor: 'rgba(0, 0, 0, 0)',
        borderWidth: 20
      },
      label: {
        show: false,
        position: 'center'
      },
      emphasis: {
        label: {
          show: true,
          fontSize: '40',
          fontWeight: 'bold'
        }
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 1048, name: 'Search Engine' },
        { value: 735, name: 'Direct' },
        { value: 580, name: 'Email' },
        { value: 484, name: 'Union Ads' },
        { value: 300, name: 'Video Ads' }
      ]
    }
  ]
};
```

### What is expected?
The pie chart border width is 20px and border color is transparent

### What is actually happening?
The pie chart border width is 0px and no border color

**Comment by Ovilia** [comment]
This doesn't seem to be a bug. The border is expected to be rendered on-top of the shape. That is to say, the shape (sector in pie series) is first rendered and then the border is rendered on it. The shape is rendered with the same size with or without border so it is expected to be the same with a transparent border or not.

**Comment by chenp1204** [comment]
**when border color is white**
![1636340406713](https://user-images.githubusercontent.com/29192482/140677927-e5490f56-0c06-427b-95be-e2de3f18ac49.jpg)
**when border color is transparent**
![1636340544356](https://user-images.githubusercontent.com/29192482/140677952-19b0f186-6fc5-4bb9-a8cd-4dd3386ea9a3.jpg)
**when border color is black**
![1636340605502](https://user-images.githubusercontent.com/29192482/140677968-4a6fcfca-f2f2-4947-9cb8-0aad7fecdebc.jpg)

According to this three images, it seems to that, when border color is not transparent the shape (sector in pie series) has border, otherwise the shape doesn't has border
When border color is transparent, i don't know if border width is valid
