### ISSUE TITLE
版本5.0+饼图的label颜色不能和折现颜色一样吗，我如果想设置成和折现颜色一样该怎么做呢？

### ISSUE THREAD

**Issue by jiale01** [apache/echarts#15987]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

**Comment by plainheart** [comment]
```js
label: {
    color: 'inherit'
}
```

**Comment by jiale01** [comment]
> ```js
> label: {
>     color: 'inherit'
> }
> ```

谢谢，已经解决了
