### ISSUE TITLE
The chart can not be rendered with log scale in SVG environment

### ISSUE THREAD

**Issue by nhhaidee** [apache/echarts#15988]
### Version
5.2.2

### Reproduction link
[https://codesandbox.io/s/dark-bash-w0h9e](https://codesandbox.io/s/dark-bash-w0h9e)

### Steps to reproduce
1 . Plot line  chart with log scale in SVG environment. 
2. The y axis has some values of zeros, with log scale the `min: 1` for YAxis options

### What is expected?
The chart must be rendered correctly

### What is actually happening?
The can can not be rendered with SVG, but it works OK with canvas

**Comment by Ovilia** [comment]
Having `0` in log axis is illegal because in maths, log(0) is meaningless. Problem resolves when removing 0 data. You can set zero data to be `-` and set [connectNulls](https://echarts.apache.org/en/option.html#series-line.connectNulls) to be true.

**Comment by nhhaidee** [comment]
Close issue as @Ovilia mentioned
