### ISSUE TITLE
legend 的 色块和文字无法上下居中对齐

### ISSUE THREAD

**Issue by donotloveshampo** [apache/echarts#15991]
### Version
5.2.2

### Reproduction link
[https://echarts.apache.org/examples/zh/editor.html?c=bar-label-rotation](https://echarts.apache.org/examples/zh/editor.html?c=bar-label-rotation)

### Steps to reproduce
请看官网实例， https://echarts.apache.org/examples/zh/editor.html?c=bar-label-rotation

### What is expected?
可以提供属性支持设置字体和图例的对齐属性，看了之前很多相关的issue，没有一个给出了解决方案和具体回复的

### What is actually happening?
无法 居中对齐

**Comment by plainheart** [comment]
参见 #14121。主要跟字体有关，Windows 下的默认字体微软雅黑会存在垂直”不居中“的情况，可以尝试其他字体，例如黑体。
