### ISSUE TITLE
飞线图，trailLength做的三角残影在其他图（比如饼图）定时setOption时，残影被截断

### ISSUE THREAD

**Issue by guojije** [apache/echarts#15994]
### Version
4.9.0

### Steps to reproduce
1.设置一个饼图，设置一个定时器，定时器内不断setOption图，定时器间隔较小，例如100ms；
2.设置一个飞线图，用trailLength = 0.02做三角残影；
3.饼图定时器重新绘图时候，三角残影被阶段；

### What is expected?
不希望飞线图三角残影卡顿，被截断，希望连贯显示

### What is actually happening?
飞线图三角残影卡顿，被截断

**Comment by guojije** [comment]
补充问题图片
![issue](https://user-images.githubusercontent.com/19277019/139803548-bf1c7890-e4d6-45b0-9df7-496c92f0289c.png)

**Comment by Ovilia** [comment]
Lines series should have different [zlevel](https://echarts.apache.org/en/option.html#series-lines.zlevel) than other series. If still have problems, please provide a demo.
