### ISSUE TITLE
Polar heat map is not smooth enough, with shadows in the graph

### ISSUE THREAD

**Issue by zcg1991** [apache/echarts#15992]
### Version
5.2.0

### Steps to reproduce
how to set the option?

### What is expected?
Polar heat map shows smoothly

### What is actually happening?
not smooth enough

---
no

![IMG_20211102_140532](https://user-images.githubusercontent.com/44219901/139796471-587395dc-f71d-4ebc-b715-e004393506bf.jpg)

**Comment by zcg8633** [comment]
> @zcg8633 Please provide a minimum reproducible demo for the issue either with https://codepen.io/Ovilia/pen/dyYWXWM , https://www.makeapie.com/editor.html or https://codesandbox.io/s/mystifying-bash-2uthz.
> 
> _A minimum reproducible demo_ should contain as little data and components as possible but can still illustrate your problem. This is the best way for us to reproduce it and solve the problem faster.



var container = document.getElementById('main');
var chart = echarts.init(container);
const data=[];
for(let i=0;i<360;i++){
  for(let j=0;j<5;j++){
    data.push([j,i,Math.random()])
  }
}
chart.setOption({
  polar: {},
  tooltip: {},
  visualMap: {
    type: 'continuous',
    min: 0,
    max: 1,
    top: 'middle',
    dimension: 2,
    calculable: true,
    color:['#000','#333']
  },
  angleAxis: {
    type: 'category',
    boundaryGap: false,
    splitLine: {
      show: true,
      lineStyle: {
        color: '#ddd',
        type: 'dashed'
      }
    },
    axisLine: {
      show: false
    }
  },
  radiusAxis: {
    type: 'category',
    z: 100
  },
  series: [
    {
      name: 'Punch Card',
      type: 'custom',
      coordinateSystem: 'polar',
      itemStyle: {
        color: '#d14a61'
      },
      renderItem: function (params, api) {
        var values = [api.value(0), api.value(1)];
        var coord = api.coord(values);
        var size = api.size([1, 1], values);
        return {
          type: 'sector',
          shape: {
            cx: params.coordSys.cx,
            cy: params.coordSys.cy,
            r0: coord[2] - size[0] / 2,
            r: coord[2] + size[0] / 2,
            startAngle: -(coord[3] + size[1] / 2),
            endAngle: -(coord[3] - size[1] / 2)
          },
          style: api.style({
            fill: api.visual('color')
          })
        };
      },
      data: data
    }
  ]
});

**Comment by pissang** [comment]
@zcg8633 You can add a small bias to avoid this kind of precision issue.
const bias = 1e-3;
...
startAngle: -(coord[3] + size[1] / 2) - bias
endAngle:  -(coord[3] - size[1] / 2) + bias

**Comment by zcg8633** [comment]
> @zcg8633 You can add a small bias to avoid this kind of precision issue.
> 
> ```js
> const bias = 1e-3;
> ...
> startAngle: -(coord[3] + size[1] / 2) - bias
> endAngle:  -(coord[3] - size[1] / 2) + bias
> ```

有效，谢谢。还有个问题请教下，这种极坐标热力图，数据量比较大的时候，渲染比较慢，有什么配置或者方法可以提升一下渲染速度么？在一些移动端浏览器或者chrome老一点（68）的版本比较明显

**Comment by pissang** [comment]
@zcg8633 可以试试加上 autoBatch: true，不过不能保证会有很大的提升，自定义系列因为灵活性所以很难针对大数据做优化
```ts
        return {
          type: 'sector',
          autoBatch: true,
          shape: {
            cx: params.coordSys.cx,
            cy: params.coordSys.cy,
            r0: coord[2] - size[0] / 2,
            r: coord[2] + size[0] / 2,
            startAngle: -(coord[3] + size[1] / 2),
            endAngle: -(coord[3] - size[1] / 2)
          },
          style: api.style({
            fill: api.visual('color')
          })
        };
```
