### ISSUE TITLE
serise.type 为 custom 时， series-custom.data.emphasis.itemStyle.color 不生效

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#16002]
### Version
5.2.2

### Reproduction link
[https://codepen.io/Ovilia/pen/dyYWXWM](https://codepen.io/Ovilia/pen/dyYWXWM)

### Steps to reproduce
将series-custom.data.emphasis.itemStyle.color设置为任意颜色

### What is expected?
显示正常的颜色

### What is actually happening?
未发生变化

**Comment by pissang** [comment]
自定义系列的 emphasis 状态需要在 renderItem 返回的图形中设置

**Comment by ZXYT** [comment]
要咋设置呀，大佬

**Comment by pissang** [comment]
https://echarts.apache.org/zh/option.html#series-custom.renderItem.return_path.emphasis

**Comment by ZXYT** [comment]
ok, thanks. 谢谢大佬😊
