### ISSUE TITLE
Title property not defined correctly makes echarts crash with exception

### ISSUE THREAD

**Issue by reisept** [apache/echarts#16004]
### Version
5.2.2

### Steps to reproduce
Create an options variable with "title: 'This is a title'" instead of "title: { text: 'This is a title'}" 

### What is expected?
Ignore the attribute and show the chart

### What is actually happening?
Uncaught TypeError: Cannot use 'in' operator to search for 'x' in CT Lot Status
    at echarts.5.2.2.min.js:45
    at Array.forEach (<anonymous>)
    at O (echarts.5.2.2.min.js:35)
    at ed (echarts.5.2.2.min.js:45)
    at echarts.5.2.2.min.js:45
    at Array.forEach (<anonymous>)
    at O (echarts.5.2.2.min.js:35)
    at echarts.5.2.2.min.js:45
    at Array.forEach (<anonymous>)
    at O (echarts.5.2.2.min.js:35)

**Comment by susiwen8** [comment]
I really don't think this is a bug for ECharts cause user doesn't follow the rules.

**Comment by reisept** [comment]
I just think that the error should be more meaningful as I took a lot of time debugging for just a simple configuration error.
It's really nota bug but a good nice to have.

**Comment by plainheart** [comment]
I could understand resolving the error unnecessarily took up your time and sorry for that. But anytime we should read the [documentation](https://echarts.apache.org/option.html#title.text) first, shouldn't we? It's not always better to add too much user input validation.
