### ISSUE TITLE
使用smooth时会有一条横穿的线

### ISSUE THREAD

**Issue by liweier219** [apache/echarts#16000]
### Version
5.1.2

### Steps to reproduce
可能数据含有0的话就会出现

### What is expected?
不会有线

### What is actually happening?
会有一根多出的线

![image](https://user-images.githubusercontent.com/93629858/140000776-54389ec8-7ff9-41df-8f0c-e3a0761ad3b9.png)
![image](https://user-images.githubusercontent.com/93629858/140000833-eac167e1-6cec-4d91-976a-3e76d7bee9d7.png)

**Comment by plainheart** [comment]
应该和 #15380 是一样问题，我们在 5.2.0 版本修复了，请升级到 5.2.0 或以上版本试下。
