### ISSUE TITLE
饼图 - 圆环图：修改 hover 放大效果

### ISSUE THREAD

**Issue by lanhe233** [apache/echarts#16003]
### What problem does this feature solve?
圆环图有默认的hover放大效果，是朝圆环外方向进行放大（scale）：
![1635932511](https://user-images.githubusercontent.com/25969954/140042018-65794879-e7ac-4aaa-aa23-2871bd7479ab.png)

但是是否可以允许调整 scale 的 中心点，或者偏移量，使得朝圆环内外两个方向同时放大：
![1635932566](https://user-images.githubusercontent.com/25969954/140042038-7482f2c2-1b72-4ebf-96c0-7d9dccb19257.png)

ps. 自己未能搜索到实现的方法。。

### What does the proposed API look like?
添加 scaleDirection 或者 scaleOffset 等 可以设置的 字段

**Comment by Ovilia** [comment]
No, not for now. If you are interested in making a PR to enable it, we are willing to help you so. Please check out [wiki](https://github.com/apache/echarts/wiki) to learn more about how to contribute.
