### ISSUE TITLE
建议支持 data item 的 radius

### ISSUE THREAD

**Issue by banli17** [apache/echarts#16019]
This issue is not created by [echarts-issue-helper](https://ecomfe.github.io/echarts-issue-helper) and will be soon closed.

请问现在支持 data item 的 radius 吗，实现如下效果,一个 pie 多个类目需要支持 不同的内外半径
![image](https://user-images.githubusercontent.com/12556069/140484872-ef62e2f6-09c8-441f-9249-952a4f47aac4.png)

**Comment by plainheart** [comment]
支持。直接设置每个数据项的 `itemStyle.borderRadius` 即可。
```js
{ value: 300, name: 'Video Ads', itemStyle: { borderRadius: 10 } }
```
