### ISSUE TITLE
在一个项目中如何同时采用echarts4.0和5.0

### ISSUE THREAD

**Issue by githubskyline** [apache/echarts#16014]
### What problem does this feature solve?
在一个项目中如何同时采用echarts4.0和5.0，项目中原来用echarts4.0的功能太多，希望在升级到echarts5.0 保持不变，只是新的功能采用echarts5.0 ， 这种情况如何引用？

### What does the proposed API look like?
同一个项目中兼容多个版本

**Comment by Ovilia** [comment]
Although we do not recommend having multiple versions in a single project...

https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm

We would recommend migrating previous code into 5.0. Please checkout [the doc](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/).

**Comment by githubskyline** [comment]
we have no enough time to migrating previous code into 5.0 because of project deadline for the current time.

**Comment by githubskyline** [comment]
I hope can using the new version for the new functions  but of impact the old functions.

**Comment by pissang** [comment]
The link https://stackoverflow.com/questions/26414587/how-to-install-multiple-versions-of-package-using-npm in the @Ovilia comment is a solution.
