### ISSUE TITLE
tooltip.axisPointer.type 可以支持数组吗？

### ISSUE THREAD

**Issue by dadazhouRenee** [apache/echarts#16018]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/v4/examples/zh/editor.html](https://echarts.apache.org/v4/examples/zh/editor.html)

### Steps to reproduce
配置 tooltip.axisPointer.type

### What is expected?
期望可以是shadow   line  或者 shadow across 这种组合状态

### What is actually happening?
只支持单个type配置

**Comment by pissang** [comment]
是期望怎么样的展现形式？

**Comment by dadazhouRenee** [comment]
多个柱状和折线组合的情况下 希望有shadow背景的同时 也可以有辅助线line @pissang
