### ISSUE TITLE
Can’t add pictures in the middle of a sunburst chart.

### ISSUE THREAD

**Issue by wp-zg** [apache/echarts#16012]
### Version
4.9.0

### Steps to reproduce
You can see it by creating a sunburst with a center level for data mining

### What is expected?
I am doing a sunburst for a company’s rule guide and I would love to add the company logo in the center of the sunburst graph

### What is actually happening?
The first level is reserved for returning to parent node when data mining and it can only be set as blank

**Comment by Ovilia** [comment]
The center circle can be configured using the first child of [levels](https://echarts.apache.org/en/option.html#series-sunburst.levels). Setting `radius` to be 0 should hide it. You can use [graphic.elements](https://echarts.apache.org/en/option.html#graphic.elements-image) to draw an image at the center.
