### ISSUE TITLE
Missing borderRadius when using custom chart with sector shape or no documentation on creating sector shape

### ISSUE THREAD

**Issue by zltn** [apache/echarts#16027]
### Version
5.2.2

### Reproduction link
[https://jsfiddle.net/0bue95q2/](https://jsfiddle.net/0bue95q2/)

### Steps to reproduce
- Create a minimal custom chart with a polar coordinate system using the sector shape.  
- Set a borderRadius on the series itemStyle
- No border radius like you get with a regular pie chart

What does work is:
- Create a minimal custom chart with a polar coordinate system using the sector shape.  
- Set a `cornerRadius` and `innerCornerRadius` when returning the shape in your `renderItem`

### What is expected?
I expected to be able to use `borderRadius` with `itemStyle` like on a regular pie chart  when creating a custom chart with a sector segment.

### What is actually happening?
You can use `cornerRadius` and `innerCornerRadius` when initiating the shape. This is not documenten but does work. 

---
I see two options:

1) actually add a [helper function](https://github.com/apache/echarts/blob/4569dc1d8b712dafb80b16e31c4fed0118e3acbd/src/chart/helper/pieHelper.ts#L25) for the sector shape it can use borderRadius as both the method and terminology will be in line with the pie chart 

2) add `cornerRadius` and `innerCornerRadius` to the sector shape documentation

**Comment by pissang** [comment]
Hi

cornerRadius and innerCornerRadius is what actually used in pie sectors. These two are missed in our docs.
