### ISSUE TITLE
为什么react中折线图从左至右边的动画消失了 但是柱状图从下至上的动画还在

### ISSUE THREAD

**Issue by dadazhouRenee** [apache/echarts#16029]
### Version
4.9.0

### Reproduction link
[https://codesandbox.io/s/echart-line-dong-hua-wen-ti-kpz7s?file=/BarLineChart.js](https://codesandbox.io/s/echart-line-dong-hua-wen-ti-kpz7s?file=/BarLineChart.js)

### Steps to reproduce
默认进来的时候 折线图也没有动画 点击切换按钮也没动画
但是柱状图的从下至上的还是有的

### What is expected?
希望折线图有动画

### What is actually happening?
没有动画

---
这边不确定是哪里写的不对 可以请教下吗

**Comment by pissang** [comment]
可能是因为 setOption 后又马上 resize 了，最新的版本修复了这个问题
