### ISSUE TITLE
xAxis not synchronized

### ISSUE THREAD

**Issue by MeMeMax** [apache/echarts#16024]
### Version
5.2.0

### Reproduction link
[https://jsfiddle.net/fx56zahp/](https://jsfiddle.net/fx56zahp/)

### Steps to reproduce
Have two yAxis (one for time series data and one for boolean data). They should be synced over the xAxis so that if you hover over the second grid items data you see also the data of the first grid item and vice versa. (see reproduction link)

### What is expected?
Axis should be synchronized to always show all data on the specific date.

### What is actually happening?
Axis are not synchronized and you have to hover over the each separately.

**Comment by Ovilia** [comment]
Sorry for the late reply. Please checkout https://echarts.apache.org/en/api.html#echarts.connectto see if this works for you.

**Comment by MeMeMax** [comment]
Thanks for the reply. Connecting by groupId did not have any effect in my example.
