### ISSUE TITLE
some error of changing symbol which series's type is gauge, see the link

### ISSUE THREAD

**Issue by notthistrain** [apache/echarts#16025]
### Version
new

### Reproduction link
[https://echarts.apache.org/zh/option.html#series-gauge.markLine.data.0.symbol](https://echarts.apache.org/zh/option.html#series-gauge.markLine.data.0.symbol)

### Steps to reproduce
https://echarts.apache.org/zh/option.html#series-gauge.markLine.data.0.symbol;
open the link, then change symbol, 
can see some error tips : 'Something Unexpected Happerns. Click refresh to try again!'

### What is expected?
none

### What is actually happening?
can try

---
none

**Comment by OrlandoP97** [comment]
Hey, something new about this issue? I can see the problem persist
