### ISSUE TITLE
action.toggleSelected   It is wrong and does not take effect. Should be  action.toggleSelect

### ISSUE THREAD

**Issue by atJiangBei** [apache/echarts#16020]
FALSE
dispatchAction({
    type: 'toggleSelected',

    // Find  by index or id or name.
    // Can be an array to find multiple components.
    seriesIndex?: number | number[],
    seriesId?: string | string[],
    seriesName?: string | string[],

    // data index; could assign by name attribute when not defined
    dataIndex?: number | number[],
    // optional; data name; ignored when dataIndex is defined
    name?: string | string[],
})

Right

dispatchAction({
    type: 'toggleSelect',

    // Find  by index or id or name.
    // Can be an array to find multiple components.
    seriesIndex?: number | number[],
    seriesId?: string | string[],
    seriesName?: string | string[],

    // data index; could assign by name attribute when not defined
    dataIndex?: number | number[],
    // optional; data name; ignored when dataIndex is defined
    name?: string | string[],
})

**Comment by Supertramplee** [comment]
+1 文档内容有误  
![image](https://user-images.githubusercontent.com/10401252/186340944-073234db-115e-438e-a101-3ed108c766e5.png)
