### ISSUE TITLE
Enlarge click area of scroll legend page icons

### ISSUE THREAD

**Issue by hughess** [apache/echarts#16021]
### What problem does this feature solve?
On mobile, the page buttons on a `scroll` legend can be quite small and difficult to press. I would like to keep them as the same size, but make them easier for users to press on their phone.

Is there a way to add a click target element overtop of the page buttons to increase the size of the click area? This would help a lot with user experience on mobile.

### What does the proposed API look like?
Not sure at the moment. Want to check if it's already possible, but if not I'd be happy to brainstorm some potential ways to do it.

**Comment by Ovilia** [comment]
Maybe we should support `pageIconPadding`. @hughess Are you interested in making a pull request? Please checkout the [wiki](https://github.com/apache/echarts/wiki) to learn more.

**Comment by hughess** [comment]
@Ovilia I can definitely make a pull request at some point. This isn't my top issue at the moment, but I'll come back to this when it is.
