### ISSUE TITLE
BMapGL support

### ISSUE THREAD

**Issue by schzh** [apache/echarts#16022]
### What problem does this feature solve?
Would Mr. Shenyi like to give a bmap.js based on WebGL1.0？We hope to use Echarts on tilted Baidu Map. Thanks.

### What does the proposed API look like?
bmap.tilt(73);

**Comment by plainheart** [comment]
The current BMap extension doesn't support BMap GL yet because of the different namespace and implementation. Several developers have reported the same requirement. See #13907, #15131, #15210.

**Comment by schzh** [comment]
> The current BMap extension doesn't support BMap GL yet because of the different namespace and implementation. Several developers have reported the same requirement. See #13907, #15131, #15210.

Then if we have the plan of supporting BMap GL? If the answer is NO, I will draw it myself with no Echarts.

**Comment by plainheart** [comment]
It's listed in the TBD milestone with a not high priority. So it may take some time before this feature is added.

**Comment by schzh** [comment]
> It's listed in the TBD milestone with a not high priority. So it may take some time before this feature is added.
Thanks. I've just tried your Amap instead, but I see an error "Cannot read properties of undefined (reading 'destroy') "-"component.getAMap().destroy();"

**Comment by plainheart** [comment]
About the problems of AMap extension, you could raise an issue to the repository of AMap extension.

**Comment by schzh** [comment]
> About the problems of AMap extension, you could raise an issue to the repository of AMap extension.

Thanks. No need of another issue, I get it. I use .setOption with parameter notMerge:True, Amap destroy the Echarts with this, that's why I get the Error, and maybe Bmap doesn't destroy the Echarts. I change this parameter, now Amap is OK.
And BTW, Amap is loaded a little bit slowly at the first time。

**Comment by plainheart** [comment]
> BTW, Amap is loaded a little bit slowly at the first time.

I'm not sure. It may be because the size of the map script to be loaded is larger than BMap.
