### ISSUE TITLE
getDataurl实现导出大数据量图表

### ISSUE THREAD

**Issue by liuyong58** [apache/echarts#16033]
### What problem does this feature solve?
在官方文档看到getDataurl和saveImage都可以实现将图表导出。但是只能导出当前页面显示的图形，不能实现导出大数据量的图形。
例如：数据量为1w条，x轴设置每次只显示3000条，getDataurl导出的为当前dom显示的3000条数据，不能导出全部数据图形。
在getDataurl之前设置doomZoom为全部时可以实现，但是数据过大，图形不太清楚，造成标签重叠等。

### What does the proposed API look like?
是否可以实现在getDataurl设置属性，实现设置图表的显示范围，达到可以分段导出大数据量的图表？

**Comment by Ovilia** [comment]
分段是什么意思呢？是可以通过多次设置不同的 dataZoom 每次导出一部分的。
