### ISSUE TITLE
when we use the markline and precision, they don't work

### ISSUE THREAD

**Issue by naniwet** [apache/echarts#16046]
### Version
5.2.2

### Steps to reproduce
The precision is Always 2.
like this picture, I set the precision 4, and the yAxis 1.5213.
But the result is still 1.52

### What is expected?
result :1.5213

### What is actually happening?
result: 1.52

---
The precision is Always 2.
like this picture, I set the precision 4, and the yAxis 1.5213.
But the result is still 1.52

![image](https://user-images.githubusercontent.com/29855425/141136930-60b0987b-c855-4308-a13c-f340f5da40fe.png)

**Comment by naniwet** [comment]
[15247](url)

**Comment by susiwen8** [comment]
Use [markLine.precision](https://echarts.apache.org/zh/option.html#series-line.markLine.precision)
```js
markLine: {
  precision: 4,
}
```
