### ISSUE TITLE
CSS variables support

### ISSUE THREAD

**Issue by Lisianthus-A** [apache/echarts#16044]
### What problem does this feature solve?
In some websites, the color theme is controlled by CSS variables. However, echarts does not support CSS variables, which means we need to do some work on CSS variables before using them, like this:
``` js
// get the CSS variable's value
const elementStyle = getComputedStyle(element);
const color = elementStyle.getPropertyValue('--color');

// echarts option
const option = {
    color: [color],
    // ...
};
```

### What does the proposed API look like?
``` js
// echarts option
const option = {
    color: ['var(--color1)', 'var(--color2)'],
    // ...
};
```

**Comment by pissang** [comment]
Correct me If I'm wrong. We need to know the element to have these CSS variables? If so, I think it's hard to get these variables from echarts side because the lack of this information. Expect these variables are all in the `:root`

**Comment by Lisianthus-A** [comment]
> Correct me If I'm wrong. We need to know the element to have these CSS variables? If so, I think it's hard to get these variables from echarts side because the lack of this information. Expect these variables are all in the `:root`

CSS variables are scoped and child elements inherit these variables from their parent. It is possible to get the value of a CSS variable from echarts instance dom.

**Comment by pissang** [comment]
Thanks for the explaination. I'm afraid we won't add this feature in the near future. We are trying to keep our API design independent from platforms so developers can have consistent experience cross different platforms.
