### ISSUE TITLE
Not Showing Elements When Hovering on Heatmap Charts

### ISSUE THREAD

**Issue by Panxoat** [apache/echarts#16042]
### Version
5.0.2

### Steps to reproduce
When I try to hover on the Heatmap chart that I produced, it doesn't show any labels like a blank table but only a section and a tooltip that I choose. When its label option was turned on and the chart has more than 25 elements on X-axis or Y-axis, I can reproduce the same issue here.

### What is expected?
It should work out very well and show everything,

### What is actually happening?
when I try to hover on the Heatmap chart that I produced, it doesn't show any labels but only a section and a tooltip that I choose.  Completely blank

not hover
<img width="455" alt="스크린샷 2021-11-10 오후 2 28 47" src="https://user-images.githubusercontent.com/49806316/141055472-35b655d3-d0e1-430c-89e6-837c575be328.png">

when hover
<img width="450" alt="스크린샷 2021-11-10 오후 2 28 54" src="https://user-images.githubusercontent.com/49806316/141055476-e8da72a5-6cf8-4a00-a900-6ad63d584421.png">

**Comment by pissang** [comment]
Hi, I can't reproduce this issue, can you provide a minimal reproducible demo to us?

**Comment by Panxoat** [comment]
> Hi, I can't reproduce this issue, can you provide a minimal reproducible demo to us?

Sorry, I tried to reproduce the same issue in demo but it didn't show up in demo. 

I think this issue is caused by too much calculation we put in the chart for business logics. I also used a basic option of the library instead but it still has a same issue that I had before. 

I hope to figure out for this video

https://user-images.githubusercontent.com/49806316/141412544-0abaf485-1fe9-4ddc-accc-a3c05fa635e0.mov

**Comment by pissang** [comment]
@Panxoat I'm not sure but are you using `setOption` update when mousemove?

**Comment by Panxoat** [comment]
@pissang 
Yes. I'm using business logic function in [tooltip.formatter option ](https://echarts.apache.org/en/option.html#tooltip.formatter)
ex) `getCustomFn(data)`

**Comment by pissang** [comment]
I think it's because you are using setOption to frequently.

**Comment by Panxoat** [comment]
How can i use setOption useful?
I think this issue caused by other reason.
caused by when X axis or Y axis length longer than specific number(in my case 25) maybe
