### ISSUE TITLE
Click the edge of tree can trigger events

### ISSUE THREAD

**Issue by Star-fly-Cheng** [apache/echarts#16043]
### What problem does this feature solve?
Clicking the edge of tree to trigger events can display relationship betwennt parent and child. Graph do just that.  Tree and Graph are expected to have similar functionality. 

### What does the proposed API look like?
Clicking on the edges of the graph should have the same API as clicking on the edges of the tree.

**Comment by sjcobb** [comment]
+1 This feature would be very useful! (I've also seen a few unanswered posts on stackoverflow asking how to do this)
