### ISSUE TITLE
Setting connectNulls:true in radar charts doesn't work

### ISSUE THREAD

**Issue by schzh** [apache/echarts#16055]
### Version
5.2.2

### Steps to reproduce
Setting connectNulls:true in radar charts doesn't work

### What is expected?
Setting connectNulls:true in radar charts works as in line chart

### What is actually happening?
it gives a point of zero

**Comment by pissang** [comment]
radar charts don't support this option yet.

**Comment by schzh** [comment]
> radar chart don't support this option yet.

Thanks. Mr. Shen, is it  in TBD milestone?
