### ISSUE TITLE
datazoom放大后出现重影

### ISSUE THREAD

**Issue by HeatonZ** [apache/echarts#16065]
### Version
4.9.0

### Reproduction link
[https://echarts.apache.org/v4/examples/zh/editor.html?c=custom-profile](https://echarts.apache.org/v4/examples/zh/editor.html?c=custom-profile)

### Steps to reproduce
dataCount 设置成1000以上，然后缩放

### What is expected?
正常缩放

### What is actually happening?
出现重影

---
这个可以在v4修复吗

**Comment by pissang** [comment]
@HeatonZ 最新的版本已经修复了这个问题
