### ISSUE TITLE
vue3.x  & echartsV5.2.1, when i click the [ legend ] which on the chart, Console error: coordSys is undefined

### ISSUE THREAD

**Issue by 59637428** [apache/echarts#16061]
### Version
5.2.1

### Steps to reproduce
Use a line chart casually in vue3.x,Configure the legend, and click the legend on the chart  

### What is expected?
the legend i can click and the line can hide or show

### What is actually happening?
Uncaught TypeError: coordSys is undefined  
    render LineView.js:553  
    progress Chart.js:196  
    _doProgress task.js:187  

![image](https://user-images.githubusercontent.com/10785079/141444019-b5d96d35-7943-472a-acdd-0c0c09978270.png)

**Comment by 59637428** [comment]
this is my code:  
`initEnuChart() {
                const chartDOM = document.getElementById('enuChart');
                this.defoMoni.enuChart = echarts.init(chartDOM);

                this.defoMoni.enuChart.setOption({
                    title: {
                        text: 'Stacked Line'
                    },
                    tooltip: {
                        trigger: 'axis'
                    },
                    legend: {
                        data: ['Email', 'Union Ads']
                    },
                    grid: {
                        left: '3%',
                        right: '4%',
                        bottom: '3%',
                        containLabel: true
                    },
                    toolbox: {
                        feature: {
                            saveAsImage: {}
                        }
                    },
                    xAxis: {
                        type: 'category',
                        boundaryGap: false,
                        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
                    },
                    yAxis: {
                        type: 'value'
                    },
                    series: [
                        {
                            name: 'Email',
                            type: 'line',
                            coordinateSystem: 'cartesian2d',
                            data: [120, 132, 101, 134, 90, 230, 210]
                        },
                        {
                            name: 'Union Ads',
                            type: 'line',
                            coordinateSystem: 'cartesian2d',
                            data: [220, 182, 191, 234, 290, 330, 310]
                        },
                    ]
                });
            },`

**Comment by pissang** [comment]
Try using `shallowRef` instead of `ref` on the chart instance

**Comment by 59637428** [comment]
> Try using `shallowRef` instead of `ref` on the chart instance

This is a test example, in this example I did not use ref

**Comment by pissang** [comment]
Please provide an example that can reproduce your issue

**Comment by 59637428** [comment]
> Please provide an example that can reproduce your issue

```
<template>
    <a-spin :spinning="loading" :delay="delay">
        <div id="demo-chart" style="width: 1200px;height: 500px;"></div>
    </a-spin>
</template>

<script>
    import * as echarts from 'echarts';

    export default {
        name: "page4",
        data() {
            return {
                chart: null,
                option: null,
                loading: true,
                delay: 50,
            }
        },
        created() {
            console.log("created")
        },
        mounted() {
            console.log("mounted")
            this.initCharts();
            let vm = this;
            setTimeout(function () {
                vm.loading = false;
            }, 3000);
        },
        methods: {
            initCharts() {
                let el = document.getElementById('demo-chart');
                this.chart = echarts.init(el);
                this.option = {
                    legend: {
                        data: ['Email']
                    },
                    xAxis: {
                        type: 'category',
                        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
                    },
                    yAxis: {
                        type: 'value'
                    },
                    series: [
                        {
                            name: 'Email',
                            data: [150, 230, 224, 218, 135, 147, 260],
                            type: 'line'
                        }
                    ]
                };
                this.chart.setOption(this.option);
            },
        },
        setup() {

        },

    }
</script>

<style lang="scss" scoped>

</style>
```  

this is the code, thanks

**Comment by 59637428** [comment]
> Please provide an example that can reproduce your issue

When I clicked legeng for the first time, it can be hide the line, But when I click the second time I want to show the line, , it reports an error:  
![image](https://user-images.githubusercontent.com/10785079/141449283-e81e41e0-045f-4efd-9e60-d60917d41db7.png)
![image](https://user-images.githubusercontent.com/10785079/141449297-d359bf05-9c43-46e1-99d2-975bebe01e3f.png)

**Comment by pissang** [comment]
You put chart instance in your data. It's similar with using `ref`. It's not necessary and bad for performance.
