### ISSUE TITLE
dataSet形式下，series label formatter失效。需要触发一次才能出现。

### ISSUE THREAD

**Issue by taoqingfeng** [apache/echarts#16073]
### Version
5.2.2

### Reproduction link
[https://www.makeapie.com/editor.html?c=xiFSVW3zqQ](https://www.makeapie.com/editor.html?c=xiFSVW3zqQ)

### Steps to reproduce
需求：柱状图label formatter 添加 %，
问题： 刷新后，默认并没有显示 % ，需要点一下lengend或者才能出现%

### What is expected?
柱状图label格式化为 43.3%

### What is actually happening?
打开默认为  43.3，并无%

---
暂无

**Comment by pissang** [comment]
@taoqingfeng 不要修改 value 下的值，formatter 是使用的你返回的值
