### ISSUE TITLE
Axis labels getting cut off by chart area

### ISSUE THREAD

**Issue by hughess** [apache/echarts#16079]
### Version
5.2.2

### Steps to reproduce
I have `containLabel: true` in my `grid` options, but occasionally axis labels will still get cut off.

### What is expected?
Chart resizes to fit all labels without any getting cut off

### What is actually happening?
Labels getting cut off (see example at bottom of screenshot):
![CleanShot 2021-11-17 at 15 42 02](https://user-images.githubusercontent.com/12602440/142279873-cadf0830-dd8e-43f5-8615-269b8b67d093.png)

---
It would be a huge help if the chart would size to fit all labels when `containLabel` is set to true.

As a workaround in the meantime, is there any way to allow labels to overflow the chart container? I haven't been able to figure out how to access the settings for the DOM container where `overflow: hidden` is set.

Thanks

**Comment by hughess** [comment]
Here's a demo of one of these types of problems:
https://jsfiddle.net/xws9gyhc/1/

**Comment by sandeepcomini** [comment]
Are there any workarounds to this issue or has it been fixed?

**Comment by HiggsWRX** [comment]
yeah would also like to know about a workaround. Would love to be able to allow echarts to overflow its container, using containLabel is not always desired.
