### ISSUE TITLE
Show label and legend in custom chart

### ISSUE THREAD

**Issue by PushpakPandya** [apache/echarts#16071]
### Version
5.2.2

### Steps to reproduce
You can check in examples of echart parlianment i used that code in my project.

### What is expected?
I want that when transition is happening at that time it also need to be show label and legend.

### What is actually happening?
Right now when transition is happening label and legend getting removed.

---
I used different series for transition of pie chart item points but it's not working I can show you ss.

![image](https://user-images.githubusercontent.com/94376965/141941575-9dc8db25-8020-4cf9-bd3f-43b6de7625e2.png)

![image](https://user-images.githubusercontent.com/94376965/141941615-25002b26-81ec-4e71-b68b-2f8b0f98c9e8.png)

**Note : This issue not facing only in my project but also happening in echart example code that I was referred.**

**Comment by pissang** [comment]
@PushpakPandya You can try using a transparent pie for displaying labels only.
