### ISSUE TITLE
Use seeded random numbers in demos so that the effect of changes is noticeable

### ISSUE THREAD

**Issue by LeaVerou** [apache/echarts#16087]
### What problem does this feature solve?

Changing chart options and observing what happens is how most people learn how to use ECharts, at least in part.

There is a bunch of demos on the echarts website that use random data. Here are a few examples:

https://echarts.apache.org/examples/en/editor.html?c=calendar-simple
https://echarts.apache.org/examples/en/editor.html?c=bar-brush
https://echarts.apache.org/examples/en/editor.html?c=calendar-pie

This means that every time the chart is redrawn, it's redrawn with entirely new data, which makes it hard to visually spot the differences the change produced, because *everything* is different. This bit me several times, where I was thrown because a tiny change in the chart option seemed to produce huge changes in the actual chart. 

There is a very easy low-effort way to address this: Use a library to seed the random number generator, so that the generated data is the same on every run (unless the actual generation code changes of course — or the seed).
There are even [libraries](https://github.com/davidbau/seedrandom) that allow you to seed `Math.random()` calls (instead of using a new method), so that the code changes would be minimal.

See: 
https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript
https://stackoverflow.com/questions/424292/seedable-javascript-random-number-generator
https://github.com/davidbau/seedrandom

### What does the proposed API look like?

_(no API changes are needed)_

**Comment by pissang** [comment]
@LeaVerou Thanks for the suggestion. We are using https://github.com/davidbau/seedrandom in our visual regression testing.  Indeed it will be helpful if we fixed the random data when doing live editing in our examples. Or at least a button to turn it on.

**Comment by pissang** [comment]
Just updated the example page. It's using seeded random by default now. Also added a `Random` button on the preview panel that can change the random seed.

**Comment by LeaVerou** [comment]
Wow, that was really fast! 😍
