### ISSUE TITLE
同时设置sourceHeader:false与dimensions时，sourceHeader不起作用

### ISSUE THREAD

**Issue by Oen-Cpz** [apache/echarts#16084]
### Version
5.2.1

### Reproduction link
[https://jsbin.com/remisihaza/edit?html,output](https://jsbin.com/remisihaza/edit?html,output)

### Steps to reproduce
```js
const option = {
  dataset: {
    dimensions: ['product', '2015', '2016', '2017'],
    sourceHeader: false,
    source: [
      ['111', '43.3', '85.8', '93.7'],
      ['222', 83.1, 73.4, 55.1],
      ['333', 86.4, 65.2, 82.5],
      ['444', 72.4, 53.9, 39.1]
    ],
  },
  xAxis: { type: 'category' },
  yAxis: {},
  series: [{ type: 'bar' }, { type: 'bar' }, { type: 'bar' }]
};
```

### What is expected?
source第一行开始就是数据

### What is actually happening?
当第一行数字均为字符串时，第一行会丢失，且不会改变维度信息

**Comment by lefex** [comment]
you can use to 5.3.0-rc.1 version (https://cdn.jsdelivr.net/npm/echarts@5.3.0-rc.1/dist/echarts.min.js) to test if you bug fixed.

This is me test:

<img width="512" alt="9ffab7a29769de472c91ddaf19e0b666" src="https://user-images.githubusercontent.com/8437666/150712138-2bd8ddcf-a780-44ac-b4b5-c28566ed1bab.png">

**Comment by susiwen8** [comment]
Great jon @lefex

**Comment by Oen-Cpz** [comment]
现在sourceHeader可以正常工作了，感谢
now sourceHeader works fine, thanks
