### ISSUE TITLE
Programmatically exporting SVG rendered chart to PDF

### ISSUE THREAD

**Issue by msbasanth** [apache/echarts#16098]
### What problem does this feature solve?
Now the SVG export feature is limited to toolbox and we have to follow below steps to get SVG from chart instance.

1. Use 'svg' as renderer when init ECharts;
2. Add saveAsImage in toolbox;
3. Click download in toolbox and will download the SVG chart.

Many times we need to embed the charts inside our PDF's which is not possible now as we don't have a SVG export API in place.

### What does the proposed API look like?
echartsInstance. getDataURL currently supports only PNG or JPEG we should extend it to support SVG when the chart is rendered using SVG.

https://echarts.apache.org/en/api.html#echartsInstance.getDataURL

**Comment by msbasanth** [comment]
@pissang 

ok thanks for the update. 

I could confirm the getDataURL({type: 'svg'}) is giving base64 image as output, which can be embedded in pdf.

**Comment by VikasAgarwal1984** [comment]
AFAIK, Input for pdfmake is svg html or image(png/jpeg)  base64 data.

Currently getDataURL({type: 'svg'}) returns data:image/svg+xml;charset=UTF-8......................
that is not working as an input.

Currently we read the outerHTML for rendered svg html element and feed to pdfmake api.

Created a stackblitz to demonstrate same. Please see console for error.
https://stackblitz.com/edit/angular-ivy-sfasil?file=src%2Fapp%2Fechart-basic%2Fechart-basic.component.ts

Is there an Api to get jpeg/png or svg html in case of svg rendering.

**Comment by msbasanth** [comment]
@VikasAgarwal1984 thanks for adding the comment. So we are getting base64 in **svg+xml** format.

@pissang  Please point us to any approach with which we can embed an svg+xml base64 content in a pdf

**Comment by VikasAgarwal1984** [comment]
seems it is url encoded, I have updated the stackblitz link
seems we need to trim svg+xml to feed in pdfmake

**Comment by pissang** [comment]
We have new `renderToSVGString` method for server-sider rendering in our next release. I think it will be the best choice in this scene. Before that, decoding the base64 format is the only way if you wan't to get the HTML string
