### ISSUE TITLE
Tooltip position throttle makes tooltip feel laggy

### ISSUE THREAD

**Issue by scttcper** [apache/echarts#16101]
### Version
5.2.2

### Steps to reproduce
With `transitionDuration: 0` and a tooltip position that follows the cursor. In https://github.com/apache/echarts/pull/15683 a throttle was added of 50ms to the position function.

I had initially thought it was the new method of positioning the tooltip with transform but it does seem to be the throttle in this case. related https://github.com/apache/echarts/pull/16091

### What is expected?
The tooltip should follow the mouse cursor as close as possible.

### What is actually happening?
50ms throttle that did not exist in v4.

---
It does seem like the tooltip lags when dev tools is open and the throttle is gone.

**Comment by plainheart** [comment]
Opened PR #16212 to disable _**throttle**_ when `transitionDuration` is set as `0` to solve this issue. Feel free to help check if it works. Thanks!

**Comment by scttcper** [comment]
@plainheart PR looks great!
