### ISSUE TITLE
couldn't set borderWidth of symbol 'emptyCircle'

### ISSUE THREAD

**Issue by zetakv** [apache/echarts#16107]
### Version
5.2.2

### Steps to reproduce
just replace option code below to the editor
```js
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      itemStyle: {
        borderWidth: 100
      },
      emphasis: {
        itemStyle: {
          borderWidth: 0
        }
      }
    }
  ]
};
```
### What is expected?
set the border width

### What is actually happening?
doesn't work, but emphasis option work

**Comment by zetakv** [comment]
sorry, i forgot the editor link: https://echarts.apache.org/examples/zh/editor.html?c=line-simple

**Comment by Ovilia** [comment]
This is by-design. Please use circle if you wish to control the border width.

**Comment by zetakv** [comment]
🤣yes i have finish my problem by using 'circle' at that time，i may just confused by the emphasis option of 'emptyCircle'. thank you.
