### ISSUE TITLE
Zero sum pie chart

### ISSUE THREAD

**Issue by chinmaydey** [apache/echarts#16117]
### What problem does this feature solve?
I want to show the color legends for zero sum pie chart however it plots colors equally

![image](https://user-images.githubusercontent.com/39548443/143526054-16f00c23-822f-4bdb-b8bf-58b7fe50fc3c.png)

### What does the proposed API look like?
In the new feature the chart should not show the series if the sum is zero. Instead it should continue to show the legend however for chart it should only show 1 circle.

I am looking something like this. Check the legend has color and chart is disabled circle

![image](https://user-images.githubusercontent.com/39548443/143525772-0ae6b50a-0f0c-42bd-8125-b45534563bd6.png)

I tried this workaround but legend has no color.

```
option = {
  tooltip: {
    trigger: 'item'
  },
  legend: {
    top: '5%',
    left: 'center',
    selected : {'Search Engine (0)':false,'Direct (0)' :false}
  },
  series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      label: {
        show: false,
        position: 'center'
      },
      emphasis: {
        label: {
          show: true,
          fontSize: '40',
          fontWeight: 'bold'
        }
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 0, name: 'Search Engine (0)' },
        { value: 0, name: 'Direct (0)' }
      ]
    }
  ]
};
```

![image](https://user-images.githubusercontent.com/39548443/143526248-f6ceeea4-ce44-4b83-bdf7-b09d04ff3a9b.png)

**Comment by pissang** [comment]
I think you can just set a gray color if all value are zero. It's as easy as:

```ts
const isAllZero = data.every(item => item.value === 0);
data: data.map(item => {
  ...item,
  itemStyle: { color: isAllZero ? 'gray' : undefined }
})
```

**Comment by chinmaydey** [comment]
You mean changing the color of series. It also changes the color of legend. I want legend color to be intact.

![image](https://user-images.githubusercontent.com/39548443/143537553-5f2d2df8-6cdb-41ed-877d-ba9987099a06.png)

**Comment by plainheart** [comment]
FYI, you can try the following way. I'm not sure if it meets your requirement.
It takes an extra empty pie series so it needs no calculation and won't change legend color.

<details>
<summary>Code</summary>

```js
option = {
  tooltip: {
    trigger: 'item'
  },
  legend: {
    top: '5%',
    left: 'center'
  },
  series: [
    {
      type: 'pie',
      radius: ['40%', '70%'],
      label: {
        show: false
      },
      itemStyle: {
        color: '#eee'
      },
      silent: true,
      z: -1,
      animation: false
    },
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      label: {
        show: false,
        position: 'center'
      },
      stillShowZeroSum: false,
      showEmptyCircle: false,
      emphasis: {
        label: {
          show: true,
          fontSize: '40',
          fontWeight: 'bold'
        }
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 0, name: 'Search Engine (0)' },
        { value: 0, name: 'Direct (0)' }
      ]
    }
  ]
};
```

</details>

**Comment by chinmaydey** [comment]
Thanks. It seems very close to what I am looking for. One last issue I guess and it will be a perfect solution. I can see the border when the sum is zero. Is there anyway to hide border only for chart and not for legend?

`option = {
  tooltip: {
    trigger: 'item'
  },
  legend: {
    top: '5%',
    left: 'center'
  },
  series: [
    {
      type: 'pie',
      radius: ['40%', '70%'],
      label: {
        show: false
      },
      itemStyle: {
        color: '#eee'
      },
      silent: true,
      z: -1,
      animation: false
    },
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      label: {
        show: false,
        position: 'center'
      },
      itemStyle: {
            borderColor: 'red',
            borderWidth: 4,
      },
      stillShowZeroSum: false,
      showEmptyCircle: false,
      emphasis: {
        label: {
          show: true,
          fontSize: '40',
          fontWeight: 'bold'
        }
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 0, name: 'Search Engine (0)' },
        { value: 0, name: 'Direct (0)' }
      ]
    }
  ]
};`


![image](https://user-images.githubusercontent.com/39548443/143579474-b646b419-0b7e-4c38-b1d0-f5b00cee3c26.png)

**Comment by plainheart** [comment]
This looks like a bug. When the sum is zero, the pie is invisible and the border shouldn't be drawn. @pissang WDYT?

**Comment by pissang** [comment]
@plainheart Yeah that's not supposed to happen. Set the value to `'-'` can solve this issue.
