### ISSUE TITLE
series-line with step="start"/"end" filled section

### ISSUE THREAD

**Issue by IndProgo** [apache/echarts#16119]
### Version
5.2.2

### Reproduction link
[https://jsfiddle.net/s6c0eqwu/1/](https://jsfiddle.net/s6c0eqwu/1/)

### Steps to reproduce
On Chrome browser. Zoom in on the line's middle point until solid fill is visible. Zoom out for the fill to disappear

### What is expected?
No solid fill for a line

### What is actually happening?
If DataZoom has property filterNode="none" and a Series line has option "step" set to "start" or "end", and if next point from a last visible point on X axis is "very far" and has lower value on Y axis, there appears solid fill between those points at some close zoom levels. 

---
Firefox seems to not have this behavior. Windows 10. Chrome version  96.0.4664.45 64bit
The further in time the next point is, the less zoom-in it requires.

**Comment by Ovilia** [comment]
No sure what is the solid fill you mentioned. Do you mind providing a gif for what's wrong?

**Comment by IndProgo** [comment]
![image](https://user-images.githubusercontent.com/41792565/144241613-398503ad-d142-4829-87f5-7b92e339d5a9.png)
it should be like this, when zooming out a bit
![image](https://user-images.githubusercontent.com/41792565/144241793-4434e8cb-4c5b-4d31-924b-2ee21073a2d4.png)

**Comment by pissang** [comment]
Seems to be a bug of Chrome. See https://github.com/apache/echarts/issues/15843
