### ISSUE TITLE
定制下载问题

### ISSUE THREAD

**Issue by pika0208** [apache/echarts#16118]
### Version
5.2.2

### Reproduction link
[https://echarts.apache.org/zh/builder/echarts.html?charts=bar,line,pie&components=gridSimple,title,legendScroll&source=true&api=true&version=](https://echarts.apache.org/zh/builder/echarts.html?charts=bar,line,pie&components=gridSimple,title,legendScroll&source=true&api=true&version=)

### Steps to reproduce
点击下载后一直building中

### What is expected?
能下载

### What is actually happening?
下载不了

**Comment by schzh** [comment]
遇到过几次，一般是浏览器的问题，不是每次一样，有几次是谷歌浏览器下载不了，但是换成微软的Edge就好了，但是前几天又试了几次，谷歌都是好的。建议你换几个浏览器试试一般总能找到

**Comment by pika0208** [comment]
@schzh 开始用edge浏览器不行，按你说的换了chrome就可以了！谢谢！
