### ISSUE TITLE
How to set the dataZoom level of the time line chart

### ISSUE THREAD

**Issue by xiaonaiquan** [apache/echarts#16125]
### What problem does this feature solve?
For example, if I have minute-level data, if I zoom in to seconds or milliseconds, the effect will be blank.

### What does the proposed API look like?
dataZoomLevel:4

**Comment by Ovilia** [comment]
You can use minSpan and maxSpan. Please check the [doc](https://echarts.apache.org/en/option.html#dataZoom-inside.maxSpan).

**Comment by xiaonaiquan** [comment]
> You can use minSpan and maxSpan. Please check the [doc](https://echarts.apache.org/en/option.html#dataZoom-inside.maxSpan).

No, you don't understand what I mean.I hope that I am 15 minutes of data, then I shrink the line chart, you can go to the hour-level line chart, then prohibit zoom in to 1 minute level, because I didn't have a minute of data.

**Comment by xiaonaiquan** [comment]
I have a 15-minute interval, I can zoom in four times and 1 hour.

> > You can use minSpan and maxSpan. Please check the [doc](https://echarts.apache.org/en/option.html#dataZoom-inside.maxSpan).
> 
> No, you don't understand what I mean.I hope that I am 15 minutes of data, then I shrink the line chart, you can go to the hour-level line chart, then prohibit zoom in to 1 minute level, because I didn't have a minute of data.

I have a 15-minute interval, I can zoom in four times and 1 hour.

**Comment by xiaonaiquan** [comment]
> You can use minSpan and maxSpan. Please check the [doc](https://echarts.apache.org/en/option.html#dataZoom-inside.maxSpan).

Thanks,I will try it.
