### ISSUE TITLE
dynamic bar with sorting process negative value as postive 

### ISSUE THREAD

**Issue by coader** [apache/echarts#16124]
### Version
5.2.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=bar-race
```ts
const data = [];
for (let i = 0; i < 5;  ++i) {
  data.push(Math.round(Math.random() * 200));
}
option = {
  xAxis: {
    max: 'dataMax'
  },
  yAxis: {
    type: 'category',
    data: ['A', 'B', 'C', 'D', 'E'],
    inverse: true,
    animationDuration: 300,
    animationDurationUpdate: 300,
    max: 2 // only the largest 3 bars will be displayed
  },
  series: [
    {
      realtimeSort: true,
      name: 'X',
      type: 'bar',
      data: data,
      label: {
        show: true,
        position: 'right',
        valueAnimation: true
      }
    }
  ],
  legend: {
    show: true
  },
  animationDuration: 0,
  animationDurationUpdate: 3000,
  animationEasing: 'linear',
  animationEasingUpdate: 'linear'
};
function run() {
  for (var i = 0; i < data.length;  ++i) {
    if (Math.random() > 0.9) {
      data[i]  = Math.round(Math.random() * 1000 -500);
    } else {
      data[i]  = Math.round(Math.random() * 200-140);
    }
  }
  myChart.setOption({
    series: [
      {
        type: 'bar',
        data
      }
    ]
  });
}
setTimeout(function () {
  run();
}, 0);
setInterval(function () {
  run();
}, 3000);
```
### What is expected?
negative will not great than postive 

### What is actually happening?
echarts use abs() value to compare

**Comment by Ovilia** [comment]
Do you mean you wish to have negative values in bar-racing effect? Currently we do not support so.

**Comment by coader** [comment]
I hope it can be sort correctly, now -7 will great then 5

**Comment by coader** [comment]
another bug is if one bar always be No.1, but still move from buttom every time when dymaic sorting

**Comment by coader** [comment]
https://user-images.githubusercontent.com/3700498/143850547-84a4016c-c5f0-4622-9363-8f77a4b31a92.mp4

**Comment by coader** [comment]
sorting problem is also here:
https://github.com/apache/echarts/issues/15087

**Comment by abitwhy** [comment]
> QQ.20211129182030.mp4

建议你使用 gif 格式的图片（而不是视频）重现视效，推荐使用类似 [ScreenToGif](https://www.screentogif.com/) 之类的录屏工具。

**Comment by li942475402** [comment]
you can change source code by `patch-package`  to support negative values
detail like this, but i'm not sure if it will bring new problems

step 1,   change this part, use value instand of barHeight,it's the reason why not support negative.

![image](https://user-images.githubusercontent.com/30969393/170442399-16f7321a-f473-4f0f-a6f9-0c0892371220.png)


setp 2, add some handle for extreme case

![image](https://user-images.githubusercontent.com/30969393/170443279-b3edb896-1582-46c5-87bd-b14be0ce2e0c.png)


step 3, complete  the remainder part
![image](https://user-images.githubusercontent.com/30969393/170443504-09cb8184-6d3c-4ec8-9d83-8800305836a4.png)
