### ISSUE TITLE
nameTextStyle doesn't work

### ISSUE THREAD

**Issue by GirkovArpa** [apache/echarts#16123]
### Version
5.2.2

### Steps to reproduce
```javascript
xAxis: {
  type: 'category',
  data: ['foo', 'bar', 'baz'],
  inverse: false,
  nameTextStyle: {
    align: 'center',
    verticalAlign: 'middle',
  },
}
```

### What is expected?
Horizontal axis labels are positioned INSIDE of the bars.

### What is actually happening?
Horizontal axis labels are positioned BELOW the bars.

---
The property `nameTextStyle` has no effect.

**Comment by Ovilia** [comment]
`name` is the text of `axis.name`. I think what you are looking for is [series-bar.label.position](https://echarts.apache.org/en/option.html#series-bar.label.position).

**Comment by GirkovArpa** [comment]
Ah, I misunderstood what `nameTextStyle` is for.  

This is what I am trying to achieve:

![](https://i.imgur.com/7wHRbmc.png)

I marked what I don't want with a red X, and what I do want with a green checkmark 🙂

**Comment by pissang** [comment]
@GirkovArpa Perhaps you can try using another dummy transparent series to display the labels `C`, `D`. Here is an example:
```ts
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar',
      // Make sure bar are overlapped.
      barGap: '-100%',
      label: {
        show: true,
        position: 'top'
      }
    },
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar',
      itemStyle: {
        color: 'transparent'
      },
      label: {
        show: true,
        position: 'insideTop',
        color: '#fff',
        fontSize: 20,
        formatter: '{b}'
      }
    }
  ]
};
```
