### ISSUE TITLE
vue 中 echarts.registerMap('name', { svg: svg });  svg底图不显示

### ISSUE THREAD

**Issue by 13764188896** [apache/echarts#16121]
### Version
5.2.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-lines

官网这个例子，改成vue下， svg底图不显示

试了很多次，也很多人遇到这个问题

### What is expected?
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-lines

官网这个例子，改成vue下， svg底图不显示

试了很多次，也很多人遇到这个问题

### What is actually happening?
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-lines

官网这个例子，改成vue下， svg底图不显示

试了很多次，也很多人遇到这个问题

---
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-lines

官网这个例子，改成vue下， svg底图不显示

试了很多次，也很多人遇到这个问题

**Comment by pissang** [comment]
Pease describe your issue with proper format. A reproducible demo will be appreciated
