### ISSUE TITLE
[Feature] graph highlight 如何高亮指定节点和边。

### ISSUE THREAD

**Issue by Dingzhaocheng** [apache/echarts#16134]
### What problem does this feature solve?

看了以往issue，有回复但并未产生有效的解决方案，希望能够得到官方回复，谢谢

### What does the proposed API look like?

类比于dataIndex，有相应的数据下标来指定，边和节点高亮

**Comment by pissang** [comment]
试试这样？
```ts
displayAction({ type: 'highlight', dataIndex, dataType: 'node' | 'edge });
```

**Comment by Dingzhaocheng** [comment]
我目前使用的是>= 5.0 版本，这种写法我在其他issue您的回复里看到了，但是并不生效。您有相关示例可以分享下么，万分感谢

**Comment by ccloveak** [comment]
我也遇到了一样的问题，需要手动控制 node跟link的高亮状态， 现在只能控制node的高亮，有进展的话求共享啊

**Comment by Dingzhaocheng** [comment]
> 试试这样？
> 
> ```ts
> displayAction({ type: 'highlight', dataIndex, dataType: 'node' | 'edge });
> ```
我看了下源码，感觉我可以帮的上忙，这个问题我可以提一个pr么。

**Comment by pissang** [comment]
@Dingzhaocheng 欢迎提 PR
