### ISSUE TITLE
Pie chart does not show color with 'light' theme

### ISSUE THREAD

**Issue by hulu7** [apache/echarts#16136]
### Version

5.2.2

### Link to minimal reproduction

https://jsfiddle.net/hulu7/yjb9e2g0/5/

### Steps To Reproduce

1. Download echarts [example](https://echarts.apache.org/examples/en/editor.html?c=pie-alignTo) to local, then modify the data like [this](https://jsfiddle.net/hulu7/yjb9e2g0/5/). And init with 'light' theme.
```javascript
data1 = [
  {
    name: 'Apples',
    value: 70
  },
  {
    name: 'Strawberries',
    value: 68
  },
  {
    name: 'Bananas',
    value: 48
  },
  {
    name: 'Oranges',
    value: 40
  }
]

data2 = [
  {
    name: 'Apple2',
    value: 34
  }
]
```
2. Run the html on local browser or on [JSFiddle](https://jsfiddle.net/hulu7/yjb9e2g0/5/). 
3. Here we go, we get an empty chart on the right.

Notice: Run it on local or on [JSFiddle](https://jsfiddle.net/hulu7/yjb9e2g0/5/)

### Current Behavior

[JSFiddle](https://jsfiddle.net/hulu7/yjb9e2g0/5/): There are datas for both pies, but one of them is blank.

### Expected Behavior

Both of them should work properly with color.

### Environment

```markdown
- OS: MacOS 10.15.7
- Browser: Chrome 96.0.4664.55
- Framework: No
```

### Any additional comments?

More finddings.
1. With following data2, you can get half pie.
```javascript
data2 = [
  {
    name: 'Apple2',
    value: 34
  },
  {
    name: 'Apple3',
    value: 34
  }
]
```
2. With another data2, you can get entire pie.
```javascript
data2 = [
  {
    name: 'Apple2',
    value: 34
  },
  {
    name: 'Apple3',
    value: 34
  },
  {
    name: 'Apple4',
    value: 34
  }
]
```
3. If data2's name exists in data1, you can also get entire pie.
```javascript
data2 = [
  {
    name: 'Apple',
    value: 34
  }
]
```

**Comment by pissang** [comment]
Seems to be a bug of multi-level color palette in the light theme. You can set color palette manually instead of using light theme.

setOption({
  color: ['#37A2DA', '#32C5E9', '#9FE6B8', '#FFDB5C', '#ff9f7f', '#fb7293', '#e7bcf3', '#8378EA', '#96BFFF']
});
