### ISSUE TITLE
Error: Heatmap on cartesian must have two category axes

### ISSUE THREAD

**Issue by eapatel** [apache/echarts#16139]
### Version

5.2.2

### Steps To Reproduce

I migrated angular version from 8 to 9 and also upgraded echarts version from 4.2 to 5.2.2.

Getting below console errors.

Error: Heatmap on cartesian must have two category axes
Error: `setOption` should not be called during main process.

Due to these error heatmap, which was working fine with echarts v4.2, is now not working anymore. can you please help to solve it?

### Current Behavior

Due to above console errors, heatmap is not working.

### Expected Behavior

Heatmap should work same with echarts version 5.2.2 as it was working with v4.2 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by eapatel** [comment]
It is bit difficult to provide demo as this issue occurred during migrating to echart v5.2.2.

Never mind, I solved the issue. Thank you!

**Comment by ZhengRui** [comment]
@eapatel I am facing the same issue right now, would you mind to share how did you solve the issue?
