### ISSUE TITLE
[Bug] 在折线树图中，收缩或者展开节点，会出现连接线残留的问题

### ISSUE THREAD

**Issue by giraffeeeRif** [apache/echarts#16132]
### Version

5.2.2

### Link to minimal reproduction

https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline

### Steps To Reproduce

直接在echarts官方的折线树图demo就可以复现问题
点击收缩多个parent节点时，会出现之前的连接线残留未清除的现象

### Current Behavior

收缩parent节点时，会出现连接线残留的现象

### Expected Behavior

收缩parent节点时清理残留的额连接线

### Environment

```markdown
- OS: windows
- Browser: Chrome 96.0.4664.45
- Framework: none
```

**Comment by Ovilia** [comment]
Duplicate of #15923
