### ISSUE TITLE
[Bug] Map show blue color when update option and remove some item

### ISSUE THREAD

**Issue by coader** [apache/echarts#16138]
### Version

5.2.2

### Link to minimal reproduction

https://codesandbox.io/s/misty-cloud-d4su0?file=/src/index.js

### Steps To Reproduce

1 use vue-charts 
2 set map option with dataset
3 updat dataset and items is less than before
4 the removed item's area show color like it's value is 0, not the same as normal item style

### Current Behavior

removed itemstill show color and seems it's value is 0, but i already remove it from dataset

### Expected Behavior

like other normal items without set 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

1 set values only has value
![image](https://user-images.githubusercontent.com/3700498/143903661-4f14b17e-fd3f-4b23-8e84-fb1e16ccd69d.png)

2 set another values set with more items, and change back to current, those new missing items still show color
![image](https://user-images.githubusercontent.com/3700498/143903710-7694ac36-b6c0-448d-8662-e390097a9042.png)

**Comment by coader** [comment]
https://codesandbox.io/s/misty-cloud-d4su0?file=/src/index.js

click changevalue button will found this bug
if i do not use geo and only change data in series, it's ok

**Comment by pissang** [comment]
Seems to be a bug. Currently you can fill the missing data with `'-'`. In your example:

```ts

var data2 = [
  { name: "中西区", value: 20057.34 },
  { name: "湾仔", value: 15477.48 },
  { name: "东区", value: 31686.1 },
  { name: "南区", value: 6992.6 },
  { name: "油尖旺", value: 44045.49 },
  { name: "深水埗", value: 40689.64 },
  { name: "九龙城", value: 37659.78 },
  { name: "黄大仙", value: 45180.97 },
  { name: "观塘", value: '-'},
  { name: "葵青", value: '-'},
  { name: "荃湾", value: '-'},
  { name: "屯门", value: '-'},
  { name: "元朗", value: '-'},
  { name: "北区", value: '-'},
  { name: "大埔", value: '-'},
  { name: "沙田", value: '-'},
  { name: "西贡", value: '-'},
  { name: "离岛", value: '-' }
];
```

**Comment by coader** [comment]
I have deleted geo and geoindex in series to avoid this bug, only use series to set all options now
