### ISSUE TITLE
请教大神们echarts.dispose() echartsInstance.dispose()什么区别

### ISSUE THREAD

**Issue by zkrisj** [apache/echarts#16148]
### What problem does this feature solve?

请教大神们echarts.dispose() echartsInstance.dispose()什么区别

### What does the proposed API look like?

echarts.dispose() echartsInstance.dispose()跟echartsInstance.clear()什么区别

**Comment by pissang** [comment]
`clear` only clear everything on the chart. it can still be used after `clear`. But disposed instance can't be used anymore. All resources will be destroyed.

**Comment by zkrisj** [comment]
> echarts.dispose() echartsInstance.dispose()

echarts.dispose() echartsInstance.dispose()一样吗

**Comment by zkrisj** [comment]
> 

echarts.dispose() echartsInstance.dispose() is same?
echarts.dispose() echartsInstance.dispose()一样吗

**Comment by pissang** [comment]
Yes

**Comment by zkrisj** [comment]
@pissang echarts.dispose() echartsInstance.dispose() is same?
echarts.dispose() echartsInstance.dispose()一样吗

**Comment by plainheart** [comment]
@zkrisj
[`echarts.dispose`](https://echarts.apache.org/api.html#echarts.dispose) is a static method, which is used to destroy any chart instance.
[`echartsInstance.dispose`](https://echarts.apache.org/api.html#echartsInstance.dispose) is an instance method, which can only be used to destroy the current instance.
