### ISSUE TITLE
[Bug] Echarts tooltip throttle getWidth error

### ISSUE THREAD

**Issue by scttcper** [apache/echarts#16146]
### Version

5.2.2

### Steps To Reproduce

Destroy a component while the tooltip is recalculating position, the throttle function attempts to run after the chart has been destroyed.

![image](https://user-images.githubusercontent.com/1400464/144106293-e1e62fe5-3382-406a-8ff7-693e1eea824b.png)

```
TypeError: this._zr is null
  at getWidth(../node_modules/echarts/lib/core/echarts.js:447:5)
  at apply(../node_modules/echarts/lib/component/tooltip/TooltipView.js:647:31)
  at exec(../node_modules/echarts/lib/util/throttle.js:72:8)
```

### Current Behavior

getWidth errors

### Expected Behavior

The throttle function should be destroyed when the chart is destroyed, or getWidth should fail silently

I believe this is not being destroyed https://github.com/apache/echarts/blob/6641951e1bd1bb7beb18a695caaa39a5fda0e885/src/component/tooltip/TooltipView.ts#L229

### Environment

```markdown
- OS: MacOs
- Browser: chrome 96
- Framework: react
```

**Comment by pissang** [comment]
Thanks for the feedback. It has been fixed in https://github.com/apache/echarts/pull/16070. Which will be included in our next version

**Comment by scttcper** [comment]
@pissang cheers
