### ISSUE TITLE
Latest version: When type is set to time, the time stamp of interval setting is invalid 最新版本：type设置为time时，interval设置时间戳无效

### ISSUE THREAD

**Issue by JIANGQIAN3333** [apache/echarts#16142]
最新版本：type设置为time时，interval设置时间戳无效
我想设置根据每个月进行分割x轴，但是无法实现，请问那里出现了问题
 `xAxis: { type: 'time', interval: 2592000000, min: new Date('2016-7-3 8:40:52'), max: new Date('2021-7-3 8:40:52'), axisLabel: { show: true, formatter: '{yyyy}.{MM}' }, splitNumber: false, splitLine: { show: true }, axisTick: { show: true }},`

_Originally posted by @JIANGQIAN3333 in https://github.com/apache/echarts/issues/2355#issuecomment-982507166_

**Comment by supermaverickws** [comment]
same
