### ISSUE TITLE
How to sort stacked bar chart for total value (length of stacked bar)

### ISSUE THREAD

**Issue by ChamilaLiyanage** [apache/echarts#16158]
### Version

5.2.2

### Steps To Reproduce

When drawing stacked bar graph in echarts it is not possible to sort the axis based on total value (length of stacked bar). The data set is already sorted according the total value before given to echart options. This works when it is not stacked (with single series) but once stacked the sorting is not proper. How can the bars be sorted for the total value based on the length of total of stacked bar?

chart json attached.

[chart-json.txt](https://github.com/apache/echarts/files/7639893/chart-json.txt)

### Current Behavior

![image](https://user-images.githubusercontent.com/48507253/144377356-63bdf08b-c491-4f5e-b524-2c039d567bc7.png)

Stacked bars are sorted incorrectly.

### Expected Behavior

The bars should be sorted with the highest to the lowest based on the total of the stack. 
Once the legend is clicked and some values are hidden, still the sorting should be applicable.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Any configurations/options in echarts that can be done to achieve this would be helpful.

**Comment by Ovilia** [comment]
I'm afraid you have to loop through the sum of the data and change the order of yAxis.
