### ISSUE TITLE
[Bug] With no data to scale, the Y-axis will disappear

### ISSUE THREAD

**Issue by xiaonaiquan** [apache/echarts#16151]
### Version

5.2.2

### Steps To Reproduce

https://echarts.apache.org/examples/editor.html?c=area-time-axis

### Current Behavior

![1](https://user-images.githubusercontent.com/16412671/144197012-9d9dfc02-9194-4a13-bf32-fc087505d63a.gif)

### Expected Behavior

When there is no data, scale and leave the Y-axis unchanged

### Environment

```markdown
- OS:
- Browser: Chrome
- Framework:
```

**Comment by Ovilia** [comment]
This is the expected behavior unless you set min and max of yAxis.

**Comment by CharmingGeeker** [comment]
> This is the expected behavior unless you set min and max of yAxis.

sometimes, we don't know the max or min value of yAxis, so I will add `filterMode: 'empty'` to the data zoom options. For others, if you want to keep xAxis, you can try to add `filterMode: 'none'` to the data zoom options
