### ISSUE TITLE
[Bug] Legend show error when legend data is number.

### ISSUE THREAD

**Issue by cm16** [apache/echarts#16153]
### Version

5.2.2

### Link to minimal reproduction

https://jsfiddle.net/3jobf8kr/2/

### Steps To Reproduce
```ts
option = {
  tooltip: {},
  legend: {
    itemWidth: 12,
    itemHeight: 12,
    data: ['1', '9', 3, 4, 5, 6, 7, 8, 10, 11, 12, 2]
  },
  xAxis: null,
  yAxis: null,
  series: [
    {
      name: '数量',
      type: 'pie',
      radius: ['70%', '40%'],
      data: [
        { name: 1, value: 292 },
        { name: 9, value: 192 },
        { name: 3, value: 186 },
        { name: 4, value: 73 },
        { name: 5, value: 31 },
        { name: 6, value: 121 },
        { name: 7, value: 42 },
        { name: 8, value: 33 },
        { name: 10, value: 20 },
        { name: 11, value: 19 },
        { name: 12, value: 30 },
        { name: 2, value: 71 }
      ]
    }
  ]
};
```

### Current Behavior

I am developing a data chart. I switch the dimension field  then I generate the data for echarts.

### Expected Behavior

When the type of dimension field is **int** value, such Month, I create array data **[1,2,3,4,5,6,7,8,9,10,11,12]** , the chart can't show legend. I modified the data to  [**'1','2'**,3,4,5,6,7,8,9,10,11,12], the legend can show '1' and '2'. 

### Environment

```markdown
- OS:Win 10
- Browser: chrome 96
- Framework: js
```

### Any additional comments?

This is the screenshot.
![image](https://user-images.githubusercontent.com/16524682/144202238-40738513-1a2d-4328-b633-134fc55f520e.png)

**Comment by pissang** [comment]
Because name will be converted to string automatically. Using string as name or id is always suggested to avoid anything unexpected happen.
