### ISSUE TITLE
[Bug]  series type lines  数据刷新的时候会闪烁

### ISSUE THREAD

**Issue by RainManGO** [apache/echarts#16164]
### Version

4.9.0

### Link to minimal reproduction

https://github.com/RainManGO/echarts-map-issue-demo

### Steps To Reproduce

1. yarn  & yarn start
2.首页可以看到闪所

### Current Behavior

数据更新lines 闪烁

### Expected Behavior

数据更新lines 不闪烁

### Environment

```markdown
- OS: Mac os 12.0.1
- Browser: Chrome
- Framework: React umi
```

**Comment by Ovilia** [comment]
lines 的原理是将之前的画面与当前的 blend 以制造 blur 的效果，因此 setOption 的时候清空了画布就会产生这一现象，这不是 bug，也没法解决，建议减少 setOption 的频率。

**Comment by RainManGO** [comment]
> lines 的原理是将之前的画面与当前的 blend 以制造 blur 的效果，因此 setOption 的时候清空了画布就会产生这一现象，这不是 bug，也没法解决，建议减少 setOption 的频率。

感谢回答，我想想其他办法。遇到了偶像，一直在关注您，喜欢你做的视图效果。
