### ISSUE TITLE
dataZoom 能支持地理坐标系吗

### ISSUE THREAD

**Issue by liangyinger** [apache/echarts#16168]
### Version

5.2.2

### Steps To Reproduce

二维地理坐标地图散点图

### Current Behavior

地图散点数据量过大的时候密密麻麻，视觉效果太差

### Expected Behavior

希望能够像其他坐标系一样使用dataZoom 过滤的功能

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by GLFei** [comment]
+1
