### ISSUE TITLE
[Bug]  Android webview 加载 echart , app 在后台进程被回收后,再回到前台, 图表位置显示错乱

### ISSUE THREAD

**Issue by xing16** [apache/echarts#16165]
### Version

5.x

### Link to minimal reproduction

 webview 加载 echart , app 在后台进程被回收后,再回到前台, 图表位置显示错乱

### Steps To Reproduce

webview+echart

### Current Behavior

 webview+echart

### Expected Behavior

webview+echart

### Any additional comments?

Android webview 加载 echart , app 在后台进程被回收后,再回到前台, 图表位置显示错乱. 是什么原因,
下面是正常和不正常截图.

![不正常](https://user-images.githubusercontent.com/11294252/144537454-76269ac5-6098-4fe0-a533-9441edad1c7e.png)
![正常](https://user-images.githubusercontent.com/11294252/144537456-cb86fad4-b065-4ea5-9714-3845a017d97c.png)

**Comment by xing16** [comment]
@Ovilia 请教了

**Comment by ZXYT** [comment]
调一下resize试试

**Comment by Ovilia** [comment]
监听回到前台的事件，调用 chart.resize()
