### ISSUE TITLE
[Bug] 按需引入使用echarts，valueAnimation失效的问题

### ISSUE THREAD

**Issue by Sugarmant** [apache/echarts#16167]
### Version

5.2.2

### Link to minimal reproduction

https://juejin.cn/post/7037390601448325128

### Steps To Reproduce

check this link https://juejin.cn/post/7037390601448325128

### Current Behavior

`import * as echarts from 'echarts/core'`
Use this way to import core.js file that will cause these code dosen't work .
```
import { installLabelLayout } from '../label/installLabelLayout';
use(installLabelLayout);
```

### Expected Behavior

fix it？

### Environment

```markdown
- OS:win10
- Browser:chrome
- Framework:vue@3
```

### Any additional comments?

nope

**Comment by plainheart** [comment]
这个目前确实会在生产构建时被 **_tree-shaking_** 移除。使用最小化引入时建议如下引入 `LabelLayout` 特性并使用 `use` API 安装该模块。

```ts
import * as echarts from 'echarts/core'
import { LabelLayout } from 'echarts/features'

echarts.use(LabelLayout)
```
