### ISSUE TITLE
[Feature] 柱形图的hover效果可取消

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#16163]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/27613553/144395687-3e13a57d-14ae-4d78-bd9a-d04d39711090.png)
如图，我希望hover灰色部分不高亮，hover蓝色部分高亮并触发tooltip

### What does the proposed API look like?

series.hover: boolean

**Comment by pissang** [comment]
不知道你是怎么设的配置项，如果灰色是单独一个系列的话可以把这个系列设置为 silent: false

**Comment by ZXYT** [comment]
哇塞！！！ 谢谢大佬！！！之前找了半天没知道这个配置
