### ISSUE TITLE
[Bug] Max and Min zoom for graph charts

### ISSUE THREAD

**Issue by sayjeyhi** [apache/echarts#16178]
### Version

5.2.2

### Link to minimal reproduction

https://echarts.apache.org/examples/en/editor.html?c=graph-simple

### Steps To Reproduce

Currently happening

https://user-images.githubusercontent.com/6254009/144845990-8275252c-ab7c-4919-965d-d22d91229a14.mov

### Current Behavior

shouldn't zoom in/out too much

### Expected Behavior

Max zoom should not show a white page after lots of zooms in, and also zoom out shouldn't go so far.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by sahilsaini110** [comment]
hello @sayjeyhi  i would love to work on this issue

**Comment by sayjeyhi** [comment]
@sahilsaini110 that is totally ok man, but please let us know about the progress and also if you want to see how other libraries handling it, you can take a look at: https://reactflow.dev/examples/

**Comment by sahilsaini110** [comment]
@sayjeyhi  I have solved the issue and just creating PR for the same. Solving some linting errors

**Comment by sahilsaini110** [comment]
https://user-images.githubusercontent.com/76941329/145576375-d12534c1-5bb4-40d2-808a-0570c6f76ebc.mp4

**Comment by susiwen8** [comment]
https://github.com/apache/echarts-doc/pull/228
