### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lyq1021772289** [apache/echarts#16174]
### Version

5.2.2

### Steps To Reproduce

vue项目，安装后打包时就报错

### Current Behavior

echarts v5.1.2 vue项目安装后打包的时候老是报 echarts/lib/visual/dataColor 找不到

* echarts/lib/data/helper/completeDimensions in ./node_modules/echarts-liquidfill/src/liquidFillSeries.js, ./node_modules/echarts-wordcloud/src/WordCloudSeries.js
* echarts/lib/visual/dataColor in ./node_modules/echarts-liquidfill/src/liquidFill.js

### Expected Behavior

降低版本就可以，但是低版本有些功能用不了，想保留新版本

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
Please complete the title or we will close this issue
