### ISSUE TITLE
[Feature] handling binning/grouping of bar time series 

### ISSUE THREAD

**Issue by th1under** [apache/echarts#16177]
### What problem does this feature solve?

In the current version of Echarts, when xAxis type is "time" and series type is bar, time series data is not grouped together. The expected behaviour is to group the adjacent data when the binning change so that we can always see bars that have a reasonable width and do the further analysis on them.
Suppose we have 6 timeseries data on 03/07/1998, 04/07/1998, 05/07/1998 06/07/1998, 18/08/1998, 18/09/1999. In the current version (5.2.0), when we zoom-out, the width of the bars will be so small that they're undifferentiatable and even they tend to be displayed as only one bar.
![Animation4](https://user-images.githubusercontent.com/41207772/144838953-5a6af540-8f17-4217-8786-0c82f6e2daf1.gif)

Codesandbox link is provided below: 
[](https://codesandbox.io/s/echarts-zoomin-timeseries-sktvb?file=/src/App.js)

### What does the proposed API look like?

When we have some adjacent time series data bars and when we zoom-out, series data can be grouped so that they create a bigger bar which consists of these adjacent bars.
An example is provided below from FusionTime:

![Animation5](https://user-images.githubusercontent.com/41207772/144838931-186a845c-32c7-418f-94e6-a212b35171e4.gif)

Here is the codesandbox of the example provided:
https://codesandbox.io/s/fusion-charts-forked-8iv04?file=/src/chart.js

**Comment by Ovilia** [comment]
Please follow #16099.
