### ISSUE TITLE
[Bug] [Support] How to group weekly data with month name at xaxis

### ISSUE THREAD

**Issue by paulogil2010** [apache/echarts#16172]
### Version

4.9.0

### Link to minimal reproduction

https://codesandbox.io/s/agitated-danny-mnjbp?file=/index.html

### Steps To Reproduce

In this use case, I have the weekly avg from last 5 years, last year, and the year to date. I would like to show them in a line chart, but showing the respective months in the xaxis...

for example:

January has 4 weeks, so xaxis shows jan and there are 4 marks in the chart representing weeks 1,2,3 and 4;
February also has 4 weeks, so xaxis shows feb and there are 3 marks in the chart representing week 5,6,7 and 8; and so on; 

### Current Behavior

shows ticks with same name

### Expected Behavior

show only one tick/name for some range of data

### Environment

```markdown
- OS:Linux 20.04
- Browser: Brave
- Framework: VueJs
```

### Any additional comments?

Also asked o [stackoverflow](https://stackoverflow.com/questions/70216683/how-to-group-weekly-data-in-it-respective-months-and-plot-using-apache-echarts/70221111#70221111)

**Comment by Ovilia** [comment]
Please follow #16099.
