### ISSUE TITLE
Warning: Instance ec_1638754037291 has been disposed

### ISSUE THREAD

**Issue by eapatel** [apache/echarts#16173]
### Version

5.2.2

### Steps To Reproduce

After upgrading to echarts 5.2.2, continuously getting this **Instance ec_1638754037291 has been disposed** warning in console.

I'm using angular 9 and on ngOnDestroy method already dispose the echarts instance but still keep getting several warnings
in the console.
```
ngOnDestroy() {
if (this.chart) {
      this.chart.dispose();
      this.chart= null;
    }
}
```
Please advise how I can resolve this warning.

### Current Behavior

Getting this warning **Instance ec_1638754037291 has been disposed** message even if echart Instance has been dispose.

### Expected Behavior

Waning message should not be displayed

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by eapatel** [comment]
I'll provide demo for the issue soon. In meantime, you can check this https://medium.com/@kelvinau4413/memory-leak-from-echarts-occurs-if-not-properly-disposed-7050c5d93028. This is the same issue what I'm currently facing in echarts v5.2.2

Even after applying the solution mentioned in above shared URL, keep getting warnings in console.

**Comment by pissang** [comment]
It depends on your code. Generally speaking, you should not hold or use an instance that has been disposed. So you can firstly do a quick check if there is other places are still using a disposed instance.

**Comment by eapatel** [comment]
In my project, implemented seven to eight different types of echarts graphs and each graphs has it's own instance. I'm not disposing any of these instances in my code. But after updating echarts to v5, I'm getting warnings in console so in order to solve it, I'm trying to dispose the instance on ngOnDestroy. but it seems this solution is also not working.

Is there is any other way to remove console warning?

**Comment by pissang** [comment]
This warning is introduce in the newer versions. It only happens when you are using instances that has been disposed.
