### ISSUE TITLE
[Bug] 时间轴中，有两个不同gridIndex的柱状图使用不同系列的数据集，第二个柱状图的类目轴上会出现第一个柱状图的类目名称

### ISSUE THREAD

**Issue by ghost** [apache/echarts#16180]
### Version

5.2.2

### Link to minimal reproduction

https://www.makeapie.com/editor.html?c=xKEfoJCDeR&v=2

### Steps To Reproduce

    dataset: [
        // 序号为 0 的 dataset。
        {
            source: [
                ['省份', '访客数', '占比'],
                ['浙江', 679, '12.70'],
                ['江苏', 495, '9.20'],
                ['广东', 489, '9.10'],
                ['山东', 283, '5.30'],
                ['福建', 254, '4.70'],
                ['河南', 258, '4.80'],
                ['上海', 240, '4.50'],
                ['四川', 239, '4.50'],
                ['湖北', 225, '4.20'],
                ['河北', 225, '4.20'],
            ],
        },
        // 序号为 1 的 dataset。
        {
            source: [
                ['省份', '访客数', '占比'],
                ['浙江', 575, '12.00'],
                ['广东', 554, '11.50'],
                ['江苏', 327, '6.80'],
                ['福建', 281, '5.90'],
                ['四川', 267, '5.60'],
                ['湖南', 213, '4.40'],
                ['山东', 210, '4.40'],
                ['湖北', 212, '4.40'],
                ['安徽', 208, '4.30'],
                ['江西', 182, '3.80'],
            ],
        },
        // 序号为 2 的 dataset。
        {
            source: [
                ['流量来源', '浏览量', '访客数'],
                ['手淘搜索', 490, 304],
                ['手淘推荐', 224, 140],
                ['淘宝客', 199, 95],
                ['我的淘宝', 2642, 931],
                ['购物车', 4623, 1643],
                ['手淘淘宝直播', 1097, 716],
                ['淘内免费其他', 955, 634],
                ['手淘旺信', 864, 582],
                ['订阅', 3247, 2160],
                ['逛逛', 269, 153],
            ],
        },
        // 序号为 3 的 dataset。
        {
            source: [
                ['流量来源', '浏览量', '访客数'],
                ['手淘搜索', 482, 316],
                ['手淘推荐', 207, 142],
                ['我的淘宝', 1120, 539],
                ['购物车', 1507, 625],
                ['手淘淘宝直播', 106, 63],
                ['淘内免费其他', 362, 230],
                ['手淘旺信', 179, 119],
                ['手淘其他店铺', 52, 13],
                ['订阅', 1858, 1330],
                ['逛逛', 87, 57],
            ],
        },
    ],
我有两个或者读个系列的数据集现举例两个系列说明问题
序号0-1是第一个柱状图的数据集，序号2-3是第二个柱状图的数据集
现在把datasetIndex写到时间轴的options中就会出现描述的问题，第二个柱状图的类目轴上出现了第一个柱状图的类目名称，encode的x和y都分别设定好了不同的名称，

### Current Behavior

时间轴中，有两个不同gridIndex的柱状图使用不同系列的数据集，第二个柱状图的类目轴上会出现第一个柱状图的类目名称

### Expected Behavior

多个图表使用数据集时应正常显示互不干扰

### Environment

```markdown
- OS:window10
- Browser:chrome 96.0.4664.45
- Framework:
```

**Comment by Ovilia** [comment]
默认情况所有系列都是取第一个数据集的，按你的需求，你应该为系列指定 `datasetIndex`。
另外，如果要实现”序号0-1是第一个柱状图的数据集，序号2-3是第二个柱状图的数据集“，一般来说你需要四个系列，前两个系列 `datasetIndex` 为 0（可以不用显式配置），后两个系列 `datasetIndex`  为 1。

**Comment by zhxxkeke** [comment]
> 默认情况所有系列都是取第一个数据集的，按你的需求，你应该为系列指定 `datasetIndex`。 另外，如果要实现”序号0-1是第一个柱状图的数据集，序号2-3是第二个柱状图的数据集“，一般来说你需要四个系列，前两个系列 `datasetIndex` 为 0（可以不用显式配置），后两个系列 `datasetIndex` 为 1。

我在options有设置 datasetIndex

`    options: [
        {
            series: [{ datasetIndex: 0 }, { datasetIndex: 2 }],
        },
        {
            series: [{ datasetIndex: 1 }, { datasetIndex: 3 }],
        },
    ],`
