### ISSUE TITLE
[Feature] 增加tree symbolGap

### ISSUE THREAD

**Issue by fantasy525** [apache/echarts#16181]
### What problem does this feature solve?

可以解决树层级很深时symbol互相堆叠的问题

### What does the proposed API look like?

symbolGap: number|function

**Comment by Ovilia** [comment]
The distance between symbols are decided by the canvas height dividing symbol numbers. So it won't help to add a gap option. One simple way to avoid this is to provide a canvas with larger height.

**Comment by shmilyoo** [comment]
遇到同样的问题 #19140 ， 有解决的办法么
