### ISSUE TITLE
[Bug] Graph Layout "none

### ISSUE THREAD

**Issue by Eraz19** [apache/echarts#16183]
### Version

5.2.2

### Steps To Reproduce

Build graph series and set layout to "none". This give an error "TypeError: el is undefined" 

### Current Behavior

Receive an error

### Expected Behavior

Display Graph in standard layout

### Environment

```markdown
- OS:Linux
- Browser:Mozilla
- Framework:
```

**Comment by Eraz19** [comment]
https://codesandbox.io/s/mystifying-bash-2uthz?file=/src/index.js

**Comment by Eraz19** [comment]
https://codesandbox.io/s/happy-noyce-zqo5w?file=/src/index.js

**Comment by plainheart** [comment]
It seems you didn't specify the `x` and `y` for each node.
