### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nehoil** [apache/echarts#16190]
UPDATE: 
I tried using the property legend.type = "rect" and it worked.

### Version

5.2.2

### Link to minimal reproduction

https://jsfiddle.net/09z8yutx/

### Steps To Reproduce

Get to the link

### Current Behavior

Legend items are not square.

### Expected Behavior

Legend items should be square.

### Environment

```markdown
- OS: ubuntu20.04, win10
- Browser: Firefox
- Framework: -
```

**Comment by susiwen8** [comment]
I think [this](https://echarts.apache.org/en/option.html#legend.icon) is the one you looking for

**Comment by nehoil** [comment]
> I think [this](https://echarts.apache.org/en/option.html#legend.icon) is the one you looking for

Thanks, that's what I was looking for!
