### ISSUE TITLE
version 5.2.2  按需引入TitleComponent标题组件时，发现依赖很大，已到5M左右，是否有优化空间

### ISSUE THREAD

**Issue by cxj00110** [apache/echarts#16191]
### What problem does this feature solve?

version 5.2.2  按需引入TitleComponent标题组件时，发现依赖很大，已到5M左右，是否有优化空间

### What does the proposed API look like?

version 5.2.2  按需引入TitleComponent标题组件时，发现依赖很大，已到5M左右，是否有优化空间

**Comment by pissang** [comment]
所有源代码也没有 5M，你看下有没有打包引入多个命名空间
