### ISSUE TITLE
热力图下使用toolbox自带的下载功能下载png图片显示异常

### ISSUE THREAD

**Issue by sunkingsss** [apache/echarts#16209]
### Version

5.2.2

### Steps to Reproduce

1.open https://echarts.apache.org/examples/zh/editor.html?c=heatmap-bmap
2.添加`toolbox: {
        show: true,
        top: 100,
        feature: {
          saveAsImage: {}
        }
      },`
3.点击下载按钮

### Current Behavior

![echarts](https://user-images.githubusercontent.com/17444344/145671386-1cf2191f-8717-427e-b3be-7b55525d9abb.png)

### Expected Behavior

地图显示正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
百度地图图层和 ECharts 的图层是独立的，toolbox 只能导出 ECharts 的内容。如过也导出百度地图，可以尝试用 dom to image 等方式实现。

**Comment by sunkingsss** [comment]
好的，谢谢
