### ISSUE TITLE
[Bug] gl map3D渲染地图导致无法交互

### ISSUE THREAD

**Issue by zhixiaotong** [apache/echarts#16205]
### Version

5.2.1

### Link to Minimal Reproduction

https://www.makeapie.com/editor.html?c=xbmSYGhnhK

### Steps to Reproduce

- 1、我参照了https://www.makeapie.com/editor.html?c=xbmSYGhnhK链接，本地实现了map3D渲染效果，使用的版本分别是echarts@5.2.1和echarts-gl@2.0.8。
- 2、带入真实数据后发现本地地图仅能查看无法进行交互，悬停没有反应，事件也无法触发。
- 3、经过反复测试对比，发现和配置项无关，如果对应的地图是浙江省，而数据里存在非浙江省的data，比如data:[{name:'杭州', value: 300}, {name: '龙泉驿区', value: 100}]，后面这条数据将直接导致地图无法交互！

### Current Behavior

这些在二维地图上是正常运行，而三维地图无法正常交互。

### Expected Behavior

可以正常交互

### Environment

```markdown
- OS:
- Browser: Chrome 83.0.4103.116
- Framework:Vue@3.2
```

### Any additional comments?

echarts很强大，基于echarts@5.2，目前我实现了很好的大屏效果，想添加3D地图丰富图表，尝鲜失败...希望作者早点修复，在此感谢！

**Comment by zhixiaotong** [comment]
我浏览了一遍echarts-gl的issue列表，很少人回复，故在这里提交，希望作者能看到，再次感谢！

**Comment by Ivygirl** [comment]
I also want to deal with the event of zoom in or zoom out.But i didn't find the api about  globe(3D earth).
