### ISSUE TITLE
[Support] Multiple series in a chart instance

### ISSUE THREAD

**Issue by uykusuz** [apache/echarts#16201]
### What problem does this feature solve?

Hi guys,

I want to realize [this][1] using echarts. In particular:
* there's a line series
* there's a bar series at the right

That would be realized like this:
* bottom x-axis: `category`
* left y-axis: `value` (price)
* right y-axis: `category` (the categories from the bottom x-axis)
* top x-axis: `value` (a count)

I tried it with [this][2]. But that doesn't work, the bar is not displayed.

Am I doing something wrong or is this kind of thing not thought of so far?

  [1]: https://www.tradingview.com/support/solutions/43000502040-volume-profile/
  [2]: https://jsfiddle.net/uykusuz/jL1kx3br/

### What does the proposed API look like?

Not sure, since I don't know what the exact problem is.

**Comment by Ovilia** [comment]
You need multiple `grid` and set `gridIndex` for each `xAxis` and `yAxis`. [Here](https://echarts.apache.org/examples/zh/editor.html?c=scatter-anscombe-quartet) is an example.

**Comment by uykusuz** [comment]
@Ovilia thank you for the fast response! :)

That example suggests that basically I cannot do what I want in a single chart? i.e. a line series, and in the same chart a bar series on the right. Like you see [here](https://www.tradingview.com/support/solutions/43000502040-volume-profile/) in the first chart.

**Comment by Ovilia** [comment]
You can create multiple series in a single chart. In your case, you may want to set two grids and make them at the same position:

```js
grid: [{
    left: 30, right: 30, top: 30, bottom: 30
}, {
    left: 30, right: 30, top: 30, bottom: 30
}];
```

**Comment by uykusuz** [comment]
Amazing, works, thank you a lot!
