### ISSUE TITLE
Set 'option.tooltip.triggerOn' to 'mousemove|click', how to distinguish the type of trigger event

### ISSUE THREAD

**Issue by fezhangyao** [apache/echarts#16216]
### Version

5.0.2

### Link to Minimal Reproduction

none

### Steps to Reproduce

none

### Current Behavior

none

### Expected Behavior

Hope to support

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 96.0.4664.55
- Framework: Vue@3
```

**Comment by pissang** [comment]
Can you describe your issue with more detail?

**Comment by fezhangyao** [comment]
After setting 'option.tooltip.triggerOn' to 'mousemove|click', the formatter function of the tooltip will be triggered when the mouse move or click in the line chart area, but I can’t tell if this is triggered by mouse move or click.

**Comment by MeetzhDing** [comment]
@pissang 
Can we get more detail about tooltip raw event?  (eg. eventType, eventPosition),  Or get info from tooltip.formatter and tooltip.position  at the same time.

If we have raw tooltip event, we could display tooltip content in ReactPortal with better performance and convenience
