### ISSUE TITLE
How does the boxplot use object array

### ISSUE THREAD

**Issue by whk-lywn** [apache/echarts#16224]
### What problem does this feature solve?

How does the boxplot use this kind of object array？When the type is ‘boxplot’, how does transform transform the object array?
`var datax = [
        {
            value1: [
                850, 740, 900, 1070, 930, 850, 950, 980, 980, 880, 1000, 980, 930, 650,
                760, 810, 1000, 1000, 960, 960
            ],
            itemStyle: { color: 'red' }
        },
        {
            value1: [
                960, 940, 960, 940, 880, 800, 850, 880, 900, 840, 830, 790, 810, 880, 880,
                830, 800, 790, 760, 800
            ],
            itemStyle: { color: 'green' }
        },...
    ];`

### What does the proposed API look like?

If you can give a detailed tutorial on ‘tranform’ when the type is ‘boxplot’

**Comment by pissang** [comment]
Duplicate with https://github.com/apache/echarts/issues/16221#issuecomment-994419597
