### ISSUE TITLE
如何在同一个series下给每一个盒子不同的填充色

### ISSUE THREAD

**Issue by whk-lywn** [apache/echarts#16221]
### What problem does this feature solve?

![34](https://user-images.githubusercontent.com/76960135/146049184-44292630-8081-4683-ae56-c1602edf7dcf.png)
第一个盒子为红色，第二个盒子想设置成黄色，但itemStyle中color好像只能设置单个颜色

### What does the proposed API look like?

是否itemStyle中color支持回调函数，或者可以使用colorBy，给每个盒子设置不同颜色

**Comment by pissang** [comment]
Please set itemStyle for each data item

e.g.
```ts
data: [{ value: ..., itemStyle: { color: 'red' }, { value: ..., itemStyle: { color: 'gree' } }]
```

**Comment by whk-lywn** [comment]
> Please set itemStyle for each data item
> 
> e.g.
> 
> ```ts
> data: [
> { value: ..., itemStyle: { color: 'red' },
> { value: ..., itemStyle: { color: 'gree' } }
> ]
> ```

Thank you!

**Comment by whk-lywn** [comment]
> Please set itemStyle for each data item
> 
> e.g.
> 
> ```ts
> data: [
> { value: ..., itemStyle: { color: 'red' },
> { value: ..., itemStyle: { color: 'gree' } }
> ]
> ```

Thank you!

**Comment by whk-lywn** [comment]
> Please set itemStyle for each data item
> 
> e.g.
> 
> ```ts
> data: [
> { value: ..., itemStyle: { color: 'red' },
> { value: ..., itemStyle: { color: 'gree' } }
> ]
> ```
How does the boxplot use this kind of object array？

**Comment by pissang** [comment]
data: [
{ value: [1, 2, 3], itemStyle: { color: 'red' },
{ value: [3, 4, 5], itemStyle: { color: 'gree' } }
]
