### ISSUE TITLE
[Feature] xAxis or yAxis tooltip

### ISSUE THREAD

**Issue by Panxoat** [apache/echarts#16228]
### What problem does this feature solve?

when xAxis name or yAxis name is overflow like blabla...
I can't see full name of xAxis or yAxis

### What does the proposed API look like?

like legend.tooltip
I hope xAxis.tooltip or yAxis.tooltip

**Comment by plainheart** [comment]
Looks useful. The axis labels will be long sometimes, but there is currently no way to show the full text when hovering on the label.

I made a workaround(https://codepen.io/plainheart/pen/NWapNQz) to simulate this behavior, but it doesn't look so simple. Just for your reference.

**Comment by Panxoat** [comment]
@plainheart 
Thank you.
But, I'm using `echarts-for-react` now.
So if possible, can you give workaround for `echarts-for-react`?
