### ISSUE TITLE
[Feature] Spatial Indexing for Tooltip?

### ISSUE THREAD

**Issue by tihuan** [apache/echarts#16232]
### What problem does this feature solve?

For scatter series, when we render 50K+ data points, hovering over a dot to show tooltip becomes noticeably slow (somehow turning on `large` paints the dots outside of the grid for me, so I can't use it). 

I wonder if it's because we're searching the nearest datapoint linearly with O(N) instead of O(logN) with spatial indexing?

`D3FC` uses `d3-quadtree` to index all the data points and that makes their tooltip really fast!

https://blog.scottlogic.com/2020/05/01/rendering-one-million-points-with-d3.html#spatial-search-of-large-datasets

Would love to know what the team thinks 😄 

Thank you!

### What does the proposed API look like?

```ts
chartInstance.set({
  series: [{
    type: "scatter",
    spatialIndex: "quadtree", // default to quadtree
    // ... other scatter series option
  }],
  // ... other options
})
```

**Comment by tihuan** [comment]
Related to #16133?

**Comment by Ovilia** [comment]
> #16133

Yes, it seems to be the same problem. BTW, if the clipping has bug with large mode, please help open an issue to report it.
