### ISSUE TITLE
[Bug] boxplot series has wrong filling area

### ISSUE THREAD

**Issue by whk-lywn** [apache/echarts#16239]
### Version

5.2.2

### Steps to Reproduce
```js
var data =  [
              {value:[850, 740, 900, 1070, 930, 850, 950, 980, 980, 880, 1000, 980, 930, 650, 760, 810, 1000, 1000, 960, 960],itemStyle:{color:'red'}},
              {value:[960, 940, 960, 940, 880, 800, 850, 880, 900, 840, 830, 790, 810, 880, 880, 830, 800, 790, 760, 800],itemStyle:{color:'blue'}},
              {value:[880, 880, 880, 860, 720, 720, 620, 860, 970, 950, 880, 910, 850, 870, 840, 840, 850, 840, 840, 840],itemStyle:{color:'green'}},
              {value:[890, 810, 810, 820, 800, 770, 760, 740, 750, 760, 910, 920, 890, 860, 880, 720, 840, 850, 850, 780],itemStyle:{color:'black'}},
              {value:[890, 840, 780, 810, 760, 810, 790, 810, 820, 850, 870, 870, 810, 740, 810, 940, 950, 800, 810, 870],itemStyle:{color:'yellow'}}
            ]
option = {
  title: [
    {
      text: 'Michelson-Morley Experiment',
      left: 'center'
    },
    {
      text: 'upper: Q3 + 1.5 * IQR \nlower: Q1 - 1.5 * IQR',
      borderColor: '#999',
      borderWidth: 1,
      textStyle: {
        fontWeight: 'normal',
        fontSize: 14,
        lineHeight: 20
      },
      left: '10%',
      top: '90%'
    }
  ],
  tooltip: {
    trigger: 'item',
    axisPointer: {
      type: 'shadow'
    }
  },
  grid: {
    left: '10%',
    right: '10%',
    bottom: '15%'
  },
  xAxis: {
    type: 'category',
    boundaryGap: true,
    nameGap: 30,
    splitArea: {
      show: false
    },
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    name: 'km/s minus 299,000',
    splitArea: {
      show: true
    }
  },
  series: [
    {
      name: 'boxplot',
      type: 'boxplot',
      datasetIndex: 1,
      data:data
    },
    // {
    //   name: 'outlier',
    //   type: 'scatter',
    //   datasetIndex: 2
    // }
  ]
};
```
### Current Behavior

The color of each box in ‘boxplot’ is correct, but the box is not drawn correctly

### Expected Behavior

Each box in ‘boxplot’ can be filled with the corresponding color correctly

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by whk-lywn** [comment]
Before filling：
![37](https://user-images.githubusercontent.com/76960135/146389260-1b8fcbf1-d1a2-44f8-8b67-8a2268670e8d.png)
After filling
![38](https://user-images.githubusercontent.com/76960135/146389126-edc6e982-d29e-47ee-93e2-175aec0c38bb.png)

**Comment by sahilsaini110** [comment]
@whk-lywn I would like to work on this issue
may u explain to me further in which file do I exactly need to change?

**Comment by whk-lywn** [comment]
1.Is it possible to use ‘transform’ to transform the data of the object array,
var data =  [
              {value:[850, 740, 900, 1070, 930, 850, 950, 980, 980, 880, 1000, 980, 930, 650, 760, 810, 1000, 1000, 960, 960],itemStyle:{color:'red'}},
              {value:[960, 940, 960, 940, 880, 800, 850, 880, 900, 840, 830, 790, 810, 880, 880, 830, 800, 790, 760, 800],itemStyle:{color:'blue'}},
              {value:[880, 880, 880, 860, 720, 720, 620, 860, 970, 950, 880, 910, 850, 870, 840, 840, 850, 840, 840, 840],itemStyle:{color:'green'}},
              {value:[890, 810, 810, 820, 800, 770, 760, 740, 750, 760, 910, 920, 890, 860, 880, 720, 840, 850, 850, 780],itemStyle:{color:'black'}},
              {value:[890, 840, 780, 810, 760, 810, 790, 810, 820, 850, 870, 870, 810, 740, 810, 940, 950, 800, 810, 870],itemStyle:{color:'yellow'}}
            ]
 Re-divide the array into：
      // result[0]: Data required for boxplot series.
      // result[1]: Outlier data.
This realizes the internal filling of boxplot

![27e4fafa53b934c6cfedaae9ae6b8fa](https://user-images.githubusercontent.com/76960135/147181201-f5076e9f-b66a-465b-94ec-fa0bd927c3a8.png)

![4158507b3f115bbf710d6a803d8982d](https://user-images.githubusercontent.com/76960135/147181215-b387b5b7-1a33-4ec2-9400-a85e3e843e31.png)

2.Or in
series: [
    {
      name: 'boxplot',
      type: 'boxplot',
      datasetIndex: 1,
      data:data
    },]
After that, why did boxplot display errors,Obviously a data conversion error（Tested on the echarts official website case and found;Only color each boxplot line;Cannot fill the inside surrounded by lines;But if you configure itemStyle for each data item to configure the fill color inside the boxplot (the area surrounded by the line);Object array must be used;But transform doesn't seem to be able to parse the object array;But if you use the above (2) form to deal with，Not correct）

![073d89d896ba1a23c0b23d311be354b](https://user-images.githubusercontent.com/76960135/147181730-b3025350-49d9-481a-8672-c874f728b038.png)

![2b32ea5429b15218a7218c620f57d39](https://user-images.githubusercontent.com/76960135/147181740-fec4c406-5d2a-4805-ad6f-31c3f5dd6354.png)

**Comment by Ovilia** [comment]
Here is a minimal code to reproduce the problem:

```js
data = [
  {
    value: [
      850, 740, 900, 1070, 930
    ],
    itemStyle: { color: 'red' }
  }
];
option = {
  xAxis: {
    type: 'category'
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      name: 'boxplot',
      type: 'boxplot',
      data: data
    }
  ]
};
```

**Comment by sahilsaini110** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/76941329/147566450-6fed48aa-0ea7-479d-8a07-8f863a9b48bb.png)

This is what I am seeing on my PC unable to get what exactly I have to do in this.

**Comment by sahilsaini110** [comment]
@Ovilia may u plz tell me how to do it and what to do it?

**Comment by whk-lywn** [comment]
![盒图](https://user-images.githubusercontent.com/76960135/147659682-8e8de6a1-3a8f-42a3-8866-c0c766b98f1d.png)
As shown in the figure above, fill the corresponding color in the rectangle enclosed by the lines of the boxplot chart
