### ISSUE TITLE
Echarts Y轴因为数据太小导致Y轴不显示刻度?

### ISSUE THREAD

**Issue by fengbindev** [apache/echarts#16238]
### Version

5.2.0

### Steps to Reproduce

我轴上的数值非常小，eg: [2.68785147226458e-16, -1.87939559767768e-16, -8.70973373822972e-16]
刻度不会显示，且堆叠再一起
![image](https://user-images.githubusercontent.com/28595220/146375235-c10c4d1a-a928-4c5b-9701-0112c8e7d56b.png)

### Current Behavior

Y轴因为数据太小导致Y轴不显示刻度

### Expected Behavior

显示刻度

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
可以试试传入值的时候乘以一个大一点的数字，比如 1e16，然后用 formatter 改变显示的值。
