### ISSUE TITLE
[Bug] 官网和API 打不开了

### ISSUE THREAD

**Issue by lvzhifu** [apache/echarts#16245]
### Version

5.2

### Steps to Reproduce

https://echarts.apache.org/zh/index.html

### Current Behavior

https://echarts.apache.org/zh/index.html 网站无法正常运行，无法查看API开发

### Expected Behavior

正常运行

### Environment

```markdown
- OS:macOS
- Browser: Chrome 96.0.4664.55
- Framework:
```

**Comment by pissang** [comment]
jsdelivr 在国内的证书的挂了，可以暂时通过代理的方式走国外的节点访问

**Comment by gaoyuanio** [comment]
国外访问的地址是什么

**Comment by Mcler520** [comment]
> jsdelivr 在国内的证书的挂了，可以暂时通过代理的方式走国外的节点访问

也不得行

**Comment by yzhang921** [comment]
> jsdelivr 在国内的证书的挂了，可以暂时通过代理的方式走国外的节点访问

试了好几个国家的代理都是一样的，能否临时开个服务页面

**Comment by gorgeousluo** [comment]
等待中……希望有个应急方案

**Comment by liuyonghua-cww** [comment]
在线等，不知道啥时候可以好，被迫摸鱼。。。。

**Comment by pissang** [comment]
@yzhang921 开代理后刷新缓存了吗？因为我们官网为了国内的访问速度大量用了 jsdelivr CDN 的服务，所以一时半会可能也没法解决，只能先等 jsdelivr 那边修复

**Comment by yzhang921** [comment]
@pissang 刷新缓存

**Comment by yzhang921** [comment]
@pissang 刷了缓存

**Comment by heerey525** [comment]
看起来确实是cdn的问题

**Comment by lvzhifu** [comment]
> @pissang刷了一次
我这边挂美国的节点正常了，就是延迟有点高

**Comment by plainheart** [comment]
临时用 GitHub Page 部署了一个镜像，大家如有需求可先临时用用，等待 jsdelivr 服务恢复正常。

https://plainheart.github.io/echarts-website/

**Comment by lizhen789** [comment]
真是佩服啊，我今天也把自己所有的网站cdn换了一遍

**Comment by plainheart** [comment]
似乎已经恢复了...

**Comment by heerey525** [comment]
恢复了
