### ISSUE TITLE
Website error, NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by jackjtr** [apache/echarts#16247]
### Version

5.2.2

### Steps to Reproduce

open a new tab
press F12 and switch to network
open url https://echarts.apache.org/en/index.html
you will see resources from cdn.jsdelivr.net fails with 
```
NET::ERR_CERT_COMMON_NAME_INVALID
```

right click any failed resource and open in a new tab
you will see
```
Your connection is not private
```

### Current Behavior

Website is not available

### Expected Behavior

Website demo and API can be viewed.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 96.0.4664.45
- Framework: None
```

**Comment by iseekTo** [comment]
+1

**Comment by MengWeiJian** [comment]
+1
chrome

**Comment by JserZbf** [comment]
+1
MacOs

**Comment by cxj-github** [comment]
+1
MacOs

**Comment by pissang** [comment]
Duplicate to https://github.com/apache/echarts/issues/16245

**Comment by ysq352358871** [comment]
+1
chrome

**Comment by sherryQwl** [comment]
cdn.jsdelivr.net 挂了

**Comment by plainheart** [comment]
已恢复正常。

**Comment by ehaaaaaaaaa** [comment]
ERR_CERT_COMMON_NAME_INVALID

hi, receive above error from malaysia region. please help
