### ISSUE TITLE
[Bug] Bar chart grid top 0

### ISSUE THREAD

**Issue by boombang** [apache/echarts#16242]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/goofy-gwen-tuotb

### Steps to Reproduce

```ts
option = {
  grid: {
    left: 0,
    right: 0,
    bottom: 0,
    top: 0
  },
  yAxis: {
    type: 'value',
    show: false
  },
  xAxis: {
    show: false,
    data: ['1']
  },
  series: [
    {
      name: 'CCC',
      type: 'bar',
      stack: 'stack-0',
      data: [18]
    },
    {
      name: 'D',
      type: 'bar',
      stack: 'stack-1',
      data: [27]
    },
    {
      name: 'E',
      type: 'bar',
      stack: 'stack-2',
      data: [36]
    },
    {
      name: 'F',
      type: 'bar',
      stack: 'stack-3',
      data: [45]
    },
    {
      name: 'B',
      type: 'bar',
      stack: 'stack-4',
      data: [9]
    }
  ]
};
```

### Current Behavior

![image](https://user-images.githubusercontent.com/12898065/146571030-968a09fa-1add-4a78-906f-6f3e15486e4e.png)

### Expected Behavior

with `top: -80`

![image](https://user-images.githubusercontent.com/12898065/146571075-ea3d839c-c3f6-49f6-8e5a-8739769a7b4c.png)

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Framework: N/A
```

**Comment by Ovilia** [comment]
This is not a bug. The grid area position is correct. What you really need is to set `yAxis.max` to be `'dataMax'`.

**Comment by boombang** [comment]
thank you @Ovilia!
