### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by YYH28** [apache/echarts#16248]
### Version

5.2.2

### Steps to Reproduce

网站示例无法打开

### Current Behavior

![image](https://user-images.githubusercontent.com/60806722/146731031-ab1f75b9-d009-4127-8aa8-1e27b6d0c05a.png)

### Expected Behavior

正常访问

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by YYH28** [comment]
网站示例无法打开

**Comment by plainheart** [comment]
#16245
