### ISSUE TITLE
[Feature] 想找到一个家族族谱方面的图表

### ISSUE THREAD

**Issue by kazeik** [apache/echarts#16256]
### What problem does this feature solve?

一直想写一个族谱方面的app，用于记录从自己的发派祖到以后自己子代关系的一个延续。但在中国古代，可能会存在一夫多妻的情况，也会有多个子级关系，一般一个家庭关系，向上寻根，可能追溯到上下四五十代，甚至百代。这个关系的数据量是很大的，如果用单纯的canvas来画，手机端肯定是处理不过来的。所以想利用echarts在图表上的能力，来弄这么一个图库。 但目前echarts上提供的图表中，并没有一个类家族世系图表的库，所以在这里请求帮助了。

### What does the proposed API look like?

这个我暂时没有思路

**Comment by Ovilia** [comment]
基本思路是利用 [graph](https://echarts.apache.org/zh/option.html#series-graph) 图的漫游（[roam](https://echarts.apache.org/zh/option.html#series-graph.roam)）能力，帮助你简化移动画布引起的重绘方面的逻辑。你需要自己计算每个节点的位置，作为 [x](https://echarts.apache.org/zh/option.html#series-graph.data.x)、y 传入。但是除了漫游的能力之外，ECharts 能提供的帮助与你自己写 Canvas 相比，可能并没有非常大的区别，甚至自己写还比较直观一点。
