### ISSUE TITLE
悬浮到markline label出现多余的tooltip

### ISSUE THREAD

**Issue by xiaoxudoo** [apache/echarts#16251]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/xiaoxudoo/pen/QWqgZwb

### Steps to Reproduce

1. 设置tooltip: { trigger: 'item' } 
2. 悬浮到markline label

### Current Behavior

![image](https://user-images.githubusercontent.com/8873196/146737887-8b8a364e-d900-4e94-a3a2-5f5aabb580f9.png)

当打开tooltip: { trigger: 'item' } , 悬浮到markline label会出现一个多余tooltip，此tooltip的值是markline所在数据的第一个data；
希望不显示这个tooltip，会出现误导。

### Expected Behavior

当打开tooltip: { trigger: 'item' } , 悬浮到markline label会出现一个多余tooltip；希望不显示这个tooltip框。

### Environment

```markdown
- OS: macOS Big Sur
- Browser: 96.0.4664.55
- Framework: --
```

**Comment by pissang** [comment]
你可以在 markLine 组件中设置 tooltip: { show: false }

**Comment by xiaoxudoo** [comment]
> 你可以在 markLine 组件中设置 tooltip: { show: false }

这个在global的 tooltip设置为 { trigger: 'item'}时是无效的，我在提交的codepen里也尝试了你的方案，依然会有这个问题， 我看了下源码，因为Markline所在的Line2组件没有继承mlModel；
![image](https://user-images.githubusercontent.com/8873196/146863776-9cc80236-81e4-4770-a639-c82d7b7a8b6c.png)

**Comment by 116050423** [comment]
1. I tried pissang's config and it works well in your codepen demo. 
2. I think this feature(hover on mark line then shows tooltip) is "by design" rather than "bug", because it belongs to the same series item in the array. Maybe what we need to do is discussing how to make it better in terms of user experience.

**Comment by xiaoxudoo** [comment]
> 1. I tried pissang's config and it works well in your codepen demo.
> 2. I think this feature(hover on mark line then shows tooltip) is "by design" rather than "bug", because it belongs to the same series item in the array. Maybe what we need to do is discussing how to make it better in terms of user experience.

it doesn't work, please hover to the "markline **label**", not the lines...
![image](https://user-images.githubusercontent.com/8873196/147207908-784aa09f-f28e-4fe5-ba28-5887ff6625dd.png)

**Comment by xiaoxudoo** [comment]
@pissang  能不能再看下这个bug，是悬浮到markline的label上会出现不需要的tooltip，不是line上？
