### ISSUE TITLE
[Bug] Revert to `left/top` instead of `transform` to improve the tooltip behavior in Firefox & IE.

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#16254]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/view.html?c=area-stack-gradient

### Steps to Reproduce

1) Open the above reproduction example link with Firefox or  IE
2) Watch if the tooltip shakes

### Current Behavior

The tooltip shakes in Firefox & IE.

### Expected Behavior

As the same as Chromium, the tooltip shouldn't shake in Firefox and IE as well.

### Environment

```markdown
- OS: Any
- Browser: Latest Firefox / IE 11
```

### Any additional comments?

The real reason for the *__shake__* issue is that the position of the tooltip will be updated in a very short time. We've solved it in #15683 via adding a throttle of `50ms`. Thus it's not necessary to use `transform` to improve performance anymore. And, to make it work smoothly in all common browsers, I'm thinking it's better to revert to `left/top`.

**Comment by plainheart** [comment]
@pissang WDYT?

**Comment by pissang** [comment]
I recorded a video on the FireFox. Is it having the _shake_ issue? I can barely tell the difference.

https://user-images.githubusercontent.com/841551/146860857-dd6e8d94-b9b7-406d-b5d4-b2a41fe27a41.mov

**Comment by plainheart** [comment]
Thanks for the video. I also test it with Firefox in macOS, it looks good as the same as Chrome. But it works worse in Windows Firefox and IE 11. But IE 11 can work slightly better if the devtools isn't open.

https://user-images.githubusercontent.com/26999792/146868593-b601ba2d-56c3-4aa4-9385-c58289d79387.mov


https://user-images.githubusercontent.com/26999792/146868603-e7000e83-864e-4f83-8312-858997fe81e5.mov

**Comment by pissang** [comment]
Looks like a underlying transition issue in browser. If the performance issue described in https://github.com/apache/echarts/pull/14246 is already solved in https://github.com/apache/echarts/pull/15683 . I think it's fine to reverse the position to `left`/`top`. Which can also simplify the code.

**Comment by pissang** [comment]
I've seen using `ease-in-out` (in echarts it's cubicInOut) may have similar lagging issues when updating the animation frequently. But I'm confusing why `left/top` behaviors different with `transform`

**Comment by plainheart** [comment]
Ahh, I also wonder the reason. 😔 But I've searched many times but found nothing useful. In the old 4.x version, there is no throttle so it looks very laggy when the mouse moves fast, but one good aspect is that it won't shake around. However, in v5, you know, though the `transform` improves a bit, once it has `transition`, it will be laggy and shake around if no throttle of `50ms`. Moreover, it even behaves differently in different browsers. On the contrary, the previous `left/top` position appears better for the throttle of `50ms`, in the other words, it behaves "better" as its "worse" positioning performance.

**Comment by pissang** [comment]
What if we still use transform and disable transition in some scenarios? One concern is how should we limit this scenario. for example, only when tooltip is triggered by mouse on the Windows FireFox/ie. Will it be too specific?

**Comment by plainheart** [comment]
It has no problem if the transition is disabled. But we don't know how it works in other scenarios yet. Good or bad? It may appears to be a bit specific if just only treat Windows Firefox and IE especially.
