### ISSUE TITLE
cdn.jsdelivr.net cdn 证书出问题一天了，官方实例引用了这个cdn的字体文件

### ISSUE THREAD

**Issue by liujunzheng** [apache/echarts#16252]
### Version

5.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/72662734/146740133-b479859c-7f0a-4491-9e55-ab9fc1ee4aea.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/72662734/146740169-cd43b79c-f0af-479e-9450-8d3d11c01b5b.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/72662734/146740196-0fb27359-18b3-446c-b502-333b355cd011.png)

### Environment

```markdown
- OS: Mac
- Browser: Chrome
- Framework: Official site
```

**Comment by pissang** [comment]
https://github.com/apache/echarts/issues/16245#issuecomment-997721225

**Comment by liujunzheng** [comment]
好八，官方木得自己的cdn嘛，还是自家的靠谱呀。
