### ISSUE TITLE
[Feature] 希望添加一个事件去控制动画停留在某一刻（seek）

### ISSUE THREAD

**Issue by nanzhiji** [apache/echarts#16265]
### What problem does this feature solve?

在云编辑器类似的项目中引入表格。因为有时间轴的概念，所以需要知道每一帧时图表呈现的状态。

### What does the proposed API look like?

如同animate.js中seek()

**Comment by nanzhiji** [comment]
虽然time-line可以达到相似的效果，但是如果遇到排名柱状图或其他有变化的动画时，就无法实现了。甚至动画都不能暂停在某一刻。所以挺受限制。

**Comment by pissang** [comment]
@nanzhiji 目前可以通过 mock `requestAnimationFrame`来实现时间线的控制，但是柱状图排序动画这种涉及到多个动画序列的组合以及其中每个动画序列结束时回调函数的调用，会复杂很多

**Comment by nanzhiji** [comment]
实际应用中，编辑器形式的项目，帧率并不是根据浏览器 1S60帧。是存在1S25帧，30帧等由项目本身确定的帧率。所以requestAnimationFrame或许并不适用。 也就是说，现在对于一般用到的图标。我选取time-line的方式实现，或许是唯一的办法，对么。

**Comment by nanzhiji** [comment]
而且突然发现好像timeLine对于折线图，饼图等。想要控制时间线。已知帧率，持续时间，获取某一时刻（某一帧）的动画状态也无法实现。

**Comment by pissang** [comment]
不太明白你说的 timeline 具体指的是什么

**Comment by nanzhiji** [comment]
echarts配置项timeline组件。如果1S25帧，那么每帧就是40ms.循环切分数据放入options中当作每个结点。然后实现了播放暂停，以及停留在某一帧

**Comment by AIR-HH** [comment]
> 不太明白你说的 timeline 具体指的是什么
请问动画能否给第三方去制作或者控制。

**Comment by nanzhiji** [comment]
我自己改相关源码了，差不多也能实现，还有一些bug还在处理中。

**Comment by DZwangbing** [comment]
> 我自己改相关源码了，差不多也能实现，还有一些bug还在处理中。

@nanzhiji 你好，能提供一下实现思路么～

**Comment by DZwangbing** [comment]
> ### What problem does this feature solve?
> 在云编辑器类似的项目中引入表格。因为有时间轴的概念，所以需要知道每一帧时图表呈现的状态。
> 
> ### What does the proposed API look like?
> 如同animate.js中seek()

可以通过以下方式实现在指定位置的暂停（看起来不太优雅...


```
            const animation = this.myChart._zr.animation;
            animation._startLoop = function () {
                var self = this;
                this._running = true;
                function step() {
                    if (self._running) {
                        self.pause()
                        !self._paused && self.update();
                    }
                }
                requestAnimationFrame(step);
            };
            animation.update = function (notTriggerFrameAndStageUpdate) {
                var time = new Date().getTime() + 1000;
                var delta = time - this._time;
                var clip = this._head;
                while (clip) {
                    var nextClip = clip.next;
                    var finished = clip.step(time, delta);
                    if (finished) {
                        clip.ondestroy();
                        this.removeClip(clip);
                        clip = nextClip;
                    }
                    else {
                        clip = nextClip;
                    }
                }
                this._time = time;
                if (!notTriggerFrameAndStageUpdate) {
                    this.trigger('frame', delta);
                    this.stage.update && this.stage.update();
                }
            };
            animation._running = false;
            animation.start()
```

**Comment by nanzhiji** [comment]
简单来说，就是去深入到源码中的zrender层，去修改源码，把他写的方法改掉，他其实有提供播放暂停的，但是他暂停后再播放是重新播放，所以在这里你要去改写逻辑，进行计算每一刻的一个播放状态，把对应的播放的时间参数传进去，然后就可以得到正确的当前时刻播放的一个状态，类似这样去实现的。但是因为破坏了原有的播放逻辑，所以是有缺陷的。一些不太比必要的东西需要隐藏掉。后来这个功能是否在项目中使用了，我也不清楚，因为只是做了一个预研工作。然后后来我也离职了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] [Feature] 希望添加一个事件去控制动画停留在某一刻（seek） (Issue #16265)





  
我自己改相关源码了，差不多也能实现，还有一些bug还在处理中。
  
@nanzhiji 你好，能提供一下实现思路么～
