### ISSUE TITLE
[Feature] tooltip axispointer line color set different colors

### ISSUE THREAD

**Issue by looserLiu** [apache/echarts#16264]
### What problem does this feature solve?

When we use a line chart, we usually need to set auxiliary lines of different colors according to different data。
For example the picture, 
![image](https://user-images.githubusercontent.com/43264755/147030957-b6f19f02-fc94-452d-900b-a45f72e60c35.png)

### What does the proposed API look like?

https://echarts.apache.org/zh/option.html#tooltip.axisPointer.lineStyle.color
could this API supports setting colors in the form of callbacks???

**Comment by Ovilia** [comment]
You can listen to the [click event](https://echarts.apache.org/en/api.html#events.Mouse%20events.click) and call setOption with new line color according to the information in click event.

**Comment by looserLiu** [comment]
myChart.on('mousemove', (params) => {
      console.log(params, 444);
      myChart.setOption({
        tooltip: {
         axisPointer: {
           lineStyle: {
            color: 'rgba(60, 85, 221,0.6)'
            },
        },
        }
      });
    }); 
    
 I tried as above, but It was not reflected in time. When the mouse left to another point a long time later，It could change occasionally.
