### ISSUE TITLE
[Bug] [website] page 404

### ISSUE THREAD

**Issue by songjianet** [apache/echarts#16261]
### Version

5.2.2

### Steps to Reproduce

The examples page page 404 in the theme in the [doc page](https://echarts.apache.org/handbook/en/concepts/style).

### Current Behavior

ditto.

### Expected Behavior

Looking forward to fix.

### Environment

```markdown
- OS: windows10
- Browser: chrome
- Framework: vue3
```

**Comment by plainheart** [comment]
Thanks for your feedback. It has fixed in https://github.com/apache/echarts-handbook/commit/4509809ae81f8c08f0cf2258fe83f2bcff777f6e.
The link to the example page is https://echarts.apache.org/examples.

**Comment by songjianet** [comment]
> Thanks for your feedback. It has fixed in [apache/echarts-handbook@4509809](https://github.com/apache/echarts-handbook/commit/4509809ae81f8c08f0cf2258fe83f2bcff777f6e). The link to the example page is https://echarts.apache.org/examples.

ok
