### ISSUE TITLE
条形图配置项同时配置了max和dataZoom，图中数据超过max的项显示异常[Bug] 

### ISSUE THREAD

**Issue by johnnhan** [apache/echarts#16263]
### Version

5.2.2

### Steps to Reproduce

条形图配置项如下
```
option = {
  title: {
    text: 'World Population'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {},
  xAxis: {
    type: 'value',
    boundaryGap: [0, 0.01],
    max: 300000,
  },
  yAxis: {
    type: 'category',
    data: ['Brazil', 'Indonesia', 'USA', 'India', 'China', 'World']
  },
  series: [
    {
      name: '2011',
      type: 'bar',
      data: [18203, 23489, 29034, 104970, 131744, 630230]
    }
  ],
  dataZoom: [{
    show: false,
  }],
};
```

### Current Behavior

数据超过max的项没有展示

### Expected Behavior

就像柱状图一样，数据超过max的项应该展示出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by songlinn** [comment]
@johnnhan  我尝试修复你这个问题时，去查了一下 [文档](https://echarts.apache.org/zh/option.html#dataZoom-inside.filterMode) 发现这并不是一个bug，是你没有设置 filteMode导致的。你可以dataZoom为
 `   dataZoom: [{
                    show: false,
                    filterMode: 'none',
   }]`

**Comment by johnnhan** [comment]
> @johnnhan 我尝试修复你这个问题时，去查了一下 [文档](https://echarts.apache.org/zh/option.html#dataZoom-inside.filterMode) 发现这并不是一个bug，是你没有设置 filteMode导致的。你可以dataZoom为 ` dataZoom: [{ show: false, filterMode: 'none', }]`

非常感谢能够解决我的问题，辛苦
