### ISSUE TITLE
[Bug] 多折线图数据和图不准确

### ISSUE THREAD

**Issue by is-cool** [apache/echarts#16277]
### Version

5.1.2

### Steps to Reproduce

官网的示例

### Current Behavior

多折线图出现了问题，数据和图不准确
<img width="807" alt="截屏2021-12-24 15 11 28" src="https://user-images.githubusercontent.com/78067806/147328302-28685595-7f15-448b-a489-bf8662d01a28.png">
<img width="832" alt="截屏2021-12-24 15 12 03" src="https://user-images.githubusercontent.com/78067806/147328314-9236d8d7-7982-4dd6-ae6b-bbd33d05644a.png">
 

### Expected Behavior

数据和图准确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
Not a bug, this is a `stack` chart.
