### ISSUE TITLE
Axis Title overlapping with Axis Labels[Bug] 

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#16274]
### Version

5.2

### Steps to Reproduce

1.create a basic bar chart
2.add name property to yAxis in options
3.add namePosition as 'middle'

### Current Behavior

Axis Title overlapping with Axis Labels

### Expected Behavior

Axis title need to take some relative position without overlapping

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:typescript
```

**Comment by SnailSword** [comment]
You can avoid it by setting [name](https://echarts.apache.org/en/option.html#yAxis.nameGap).

**Comment by RavalikaP** [comment]
@SnailSword, but the width of the axis label will be changing based on the labels length. So, in this case how we will be calculating the nameGap?
