### ISSUE TITLE
[Bug]   tooltip appendToBody  let page scroll

### ISSUE THREAD

**Issue by WeiShengv99** [apache/echarts#16285]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/echats-tootips-wen-ti-28bb6?file=/index.html

### Steps to Reproduce

1. hover tootips
2. scroll page

https://user-images.githubusercontent.com/35689628/147443081-b232dfd0-0df3-447c-a594-b1730f22650c.mov

### Current Behavior

tootips transform let body scroll

### Expected Behavior

Does't affect page layout

### Environment

```markdown
-OS: macos
-Browser: chrome version 96.0.4664.110 (official version) (arm64)
-Framework: react 17
```

**Comment by plainheart** [comment]
The video seems to be broken. Could you be more specific?

**Comment by WeiShengv99** [comment]
> ~Could you be more specific?~ I see it. You can add `overflow: hidden` to the document `body`.

@plainheart 

In my case, my app is  Micro Frontends, I think I shouldn't set  `overflow: hidden` to the document `body`, what do you think?
what is the best way to resolve this problem.

**Comment by plainheart** [comment]
If you can't set `overflow` as `hidden` for some reason, you will have to avoid using` tooltip.appendToBody`. Just remove this option from your chart configuration.

**Comment by WeiShengv99** [comment]
ok,  tks for your advice, I will close this issue.

**Comment by WeiShengv99** [comment]
@plainheart 
By the way,[i see some implement about tootip ](https://codesandbox.io/s/wei-zhi-antd-4-17-4-forked-xksdr?file=/index.js), maybe this is a better solution .
