### ISSUE TITLE
[Bug] `echarts.time.format` get wrong time.

### ISSUE THREAD

**Issue by 007tom** [apache/echarts#16280]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-time-bug-mxphv

### Steps to Reproduce

Just look at the result logged in the console.

### Current Behavior

```js
console.log(echarts.time.format("2021-12-25T00:00:00Z", "yyyy-MM-dd", true) );
// yyyy-MM-dd
```

### Expected Behavior

```js
console.log(echarts.time.format("2021-12-25T00:00:00Z", "yyyy-MM-dd", true) );
// 2021-12-25
```

### Environment

```markdown
- OS: macOS Big Sur
- Browser: Chrome Version 96.0.4664.110 (Official Build) (x86_64)
- Framework: React@17.0.2
```

### Any additional comments?

when I use echarts heatmap calendar examples: [Simple Calendar](https://echarts.apache.org/examples/en/editor.html?c=calendar-simple&lang=ts)

**Comment by plainheart** [comment]
See #12859. You need to wrap the format with `{}`.

**Comment by 007tom** [comment]
@plainheart  **LGTM** closing it...
