### ISSUE TITLE
uniapp app端使用echarts中tooltip无法解析html[Bug] 

### ISSUE THREAD

**Issue by Yetongge** [apache/echarts#16287]
### Version

5.2.2

### Steps to Reproduce

引入的是5.2.2的echarts.js

### Current Behavior

需要重新tooltip，结果无法解析HTML

### Expected Behavior

需要重新tooltip使其可以解析HTML

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dramaw** [comment]
我也遇到这个问题了
