### ISSUE TITLE
[Bug] The pie sector flickers in emphasis state

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#16294]
### Version

next

### Link to Minimal Reproduction

[test/pie.html](https://github.com/apache/echarts/blob/next/test/pie.html)

### Steps to Reproduce

1. Open the test case `pie.html`
2. Move the mouse to a pie sector
3. Watch if the hovered sector flickers

### Current Behavior

The sector flickers in emphasis state

### Expected Behavior

The sector won't flicker in emphasis state

### Environment

```markdown
- OS: Any
- Browser: Any
- Framework: Any
```

**Comment by pissang** [comment]
Seems related to the animation or states with pattern. Will take a look into it
