### ISSUE TITLE
how can i set the legend text color when not selected in echarts 

### ISSUE THREAD

**Issue by d-kishorekumar** [apache/echarts#16293]
### What problem does this feature solve?

if user want to see different / custom color on legend when its in disabled or in-active 

### What does the proposed API look like?

```
legend: {
    data: [
         {
          name: 'Email',
          textStyle: {
              color:['red', 'green']
             }
         }
      ]
}
```

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#legend.inactiveColor The text color is the same as that of inactive icon.

**Comment by d-kishorekumar** [comment]
> https://echarts.apache.org/en/option.html#legend.inactiveColor The text color is the same as that of inactive icon.

is there any API that supports icon fill based on active and inactive? 
![image](https://user-images.githubusercontent.com/6139661/147640489-2733bdf9-852d-4844-9ca9-55d01b472686.png)
