### ISSUE TITLE
[xAxis.axisLabel 会导致 yAxis.axisLine.lineStyle.type 无效][BUG]

### ISSUE THREAD

**Issue by mynameismaosheng** [apache/echarts#16299]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/mynameismaosheng/pen/YzreyZj

### Steps to Reproduce

`xAxis: {
          type: 'category',
          data: xData,
          axisLabel: {
            fontSize: 14,
            color: '#333'
          },
          axisTick: { show: false },
          splitLine: {
            show: true,
            lineStyle: {
              type: 'dashed',
              color: '#ccc'
            }
          },
          axisLine: {
            show: true,
            lineStyle: {
              type: 'dashed',
              color: '#ccc'
            }
          }
        },
        dataZoom: [
          {
            type: 'inside',
            start: 0,
            end: 100
          },
          {
            start: 0,
            end: 100
          }
        ],
        yAxis: {
          type: 'value',
          axisLabel: {
            fontSize: 16,
            color: "rgba(51, 51, 51, 1)",
            fontFamily: 'DIN',
            fontWeight: 'bold'
          },
          axisTick: { show: false },
          splitLine: {
            show: true,
            lineStyle: {
              type: 'dashed',
              color: '#ccc'
            }
          },
          axisLine: {
            show: true,
            lineStyle: {
              type: 'dashed',
              color: '#ccc'
            }
          },
        },`

### Current Behavior

xAxis.axisLabel 设置颜色之后 会导致 yAxis.axisLine.lineStyle.type设置为dashed的行为无效

### Expected Behavior

希望可以不被影响

### Environment

```markdown
- OS:window10
- Browser:Chrome 96.0.4664.93
- Framework:Vue@2
```

**Comment by SnailSword** [comment]
It is a bug, but it is not cause by `xAxis.axisLabel. color `.

You can temporarily remove `show: true` in `yAxis.axisLine` to avoid this problem.
