### ISSUE TITLE
[Bug] 旭日图中心位置文本无法垂直居中（Sunburst center text cannot be centered vertically）

### ISSUE THREAD

**Issue by zzl93** [apache/echarts#16296]
### Version

5.2.1

### Link to Minimal Reproduction

https://www.makeapie.com/editor.html?c=xmuiVmvcvi&v=3

### Steps to Reproduce

旭日图中心位置文本无法垂直居中（Sunburst center text cannot be centered vertically）

### Current Behavior

旭日图中心位置文本无法垂直居中（Sunburst center text cannot be centered vertically）

### Expected Behavior

旭日图中心位置文本垂直居中（Sunburst center text is vertically centered）

### Environment

```markdown
- OS: win10
- Browser: Microsoft Edge version 96.0.1054.62
- Framework: without
```

**Comment by zzl93** [comment]
我试试（I will try）

**Comment by Ovilia** [comment]
@zzl93 Excellent! Feel free to comment if you have any problems.

**Comment by FrankChencc** [comment]
I'm interested in fixing this issue
