### ISSUE TITLE
[Bug] 堆积图设置smooth为true， 其中某系列全为0时显示异常

### ISSUE THREAD

**Issue by lovefriday** [apache/echarts#16306]
### Version

5.2.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/76509112/147728522-bb2af7ae-f400-416b-bfb2-70f14e9b9a38.png)

### Current Behavior

堆积图设置smooth为true，当其中某一系列全为0时显示异常

### Expected Behavior

若某一系列为0，则不绘制出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
并不是没有显示，而是被下方的系列遮住了。

**Comment by lovefriday** [comment]
> 并不是没有显示，而是被下方的系列遮住了。

绿色系列的数据全是0，本身就不应该显示

**Comment by plainheart** [comment]
默认折线有 2px 线宽，数据均为 0 也会被绘制出来，不希望如此可以设置 `lineStyle.width` 为 `0`，`showSymbol` 设为 `false` 隐藏线段和拐点。

**Comment by plainheart** [comment]
刚刚操作了一番，感觉这种情况确实有点欠妥，后面会优化下。

**Comment by lovefriday** [comment]
> 刚刚操作了一番，感觉这种情况确实有点欠妥，后面会优化下。

刚刚发现不为0的情况下只要smooth为true，显示也是有问题的。
![image](https://user-images.githubusercontent.com/76509112/147734480-5c2ff36e-493d-4e6b-80c1-fb7bb0e8fb2e.png)
