### ISSUE TITLE
[Feature] 类目轴的刻度控制

### ISSUE THREAD

**Issue by moonlitusun** [apache/echarts#16305]
### What problem does this feature solve?

类目轴的刻度控制基本没有什么API，想控制显示几条，按照什么规律显示，和数据轴一样都不行。

### What does the proposed API look like?

想知道可以支持吗，如果不能支持的话是因为什么原因

**Comment by SnailSword** [comment]
> 想控制显示几条，按照什么规律显示

Try this [axisTick.interval](https://echarts.apache.org/zh/option.html#xAxis.axisTick.interval).
