### ISSUE TITLE
Series labels are getting disabled when symbol is set as 'none' 

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#16308]
### Version

5.2

### Steps to Reproduce

1.create a basic line chart.
2.Inside options,inside series object,add symbol:'none',

### Current Behavior

LineLabels are getting disabled

### Expected Behavior

Labels should not get disabled

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by SnailSword** [comment]
Can be reproduced in the official demos. But I'm not sure if it is a bug or a feature.

**Comment by Airkro** [comment]
Same problem:

```js
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'scatter',
      symbol: 'none',
      label: {
        show: true
      }
    }
  ]
};
```
