### ISSUE TITLE
[Bug] 散点图(scatter)里series.data里的维度为null时图表显示异常

### ISSUE THREAD

**Issue by Colin3191** [apache/echarts#16310]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/elated-austin-3dg83

### Steps to Reproduce

```
option = {
  series: [
    {
      type: 'scatter',
      data: [['华北', '公司', 524]],
      name: '524'
    },
    {
      type: 'scatter',
      data: [[null, null, 0]],
      name: '0'
    }
  ],
  xAxis: [
    {
      data: ['东北', '华北', '华东', '西北', '西南', '中南', null]
    }
  ],
  yAxis: [
    
    {
      data: ['公司', '消费者', '小型企业', null]
    }
  ]
};
```

### Current Behavior

series.data里的维度为null时，点的位置不对(没有和x，y轴的null对应)。

### Expected Behavior

显示在右上角，和x，y轴的null对应。

**Comment by SnailSword** [comment]
You can replace `null` with string `'null'`.  (But this is not recommended.)

**Comment by helgasoft** [comment]
v.5.3.2 and up do not show the null values
