### ISSUE TITLE
[Bug] Dynamic Data + Time Axis 

### ISSUE THREAD

**Issue by maicWorkGithub** [apache/echarts#16319]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/maicworkgithub/pen/LYzmJZQ

### Steps to Reproduce

Wait data start unshift data item

### Current Behavior

Some line twisted
![image](https://user-images.githubusercontent.com/15863224/148059197-65d551b1-0944-4c35-bf01-250c21462e5f.png)

### Expected Behavior

No  line twisted

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Framework: None
```

**Comment by plainheart** [comment]
I think this bug has been fixed by #16069. Please wait for the next version 5.3.0. In the meanwhile, please feel free to help check if it persists with the nightly version:
https://cdn.jsdelivr.net/npm/echarts-nightly@5.3.0-dev.20220104/dist/echarts.min.js.

Thanks!

**Comment by plainheart** [comment]
Just tried with the latest nightly version. It seems #16069 can't solve this issue. Please @pissang take a look.


![image](https://user-images.githubusercontent.com/26999792/148162503-0c4910d5-80a3-4514-860e-a9197429de90.png)
![image](https://user-images.githubusercontent.com/26999792/148162519-ab4c6817-7fd6-4832-9584-1cd0e8575ed8.png)

**Comment by pissang** [comment]
Looks like it's because you are using speed as name. It's duplicated and not related to the order of points. Use `time` as name or id can fix this problem.

**Comment by maicWorkGithub** [comment]
I get it.
Thanks

**Comment by maicWorkGithub** [comment]
@pissang 再打扰一下。
怎么修改node_modules里的 echarts/types/dist/shared.d.ts:10277文件？我在源码里没找到，是自动生成的吗？本来想提个PR的，太菜了，没找到 😂 。
想修改如下：
```diff
interface LinesDataItemOption extends LinesStateOption<CallbackDataParams>, StatesOptionMixin<LinesStateOption<CallbackDataParams>, LinesStatesMixin> {
-   name?: string;
+   name?: string|number;
    fromName?: string;
    toName?: string;
    symbol?: string[] | string;
    symbolSize?: number[] | number;
    coords?: LinesCoords;
    value?: LinesValue;
    effect?: LineDrawModelOption['effect'];
}
```

另外，如果我想在外面定义这个数据的时候，使用你们写好的类型很费劲：
```typescript
type ExactItem<T> = T extends Array<infer U> ? U : never
type LinesDataItemOptionArr = ExactItem<LinesSeriesOption['data']>
const arr:LinesDataItemOptionArr = [
  {name: Date.now(), value: [Date.now(), someText]}
]
```
你们有把这个类型暴露出来的打算吗？我看官网示例里是用户自己定义的类型，类似`const arr:{name: string|number, value:xxx }[] = []`。
