### ISSUE TITLE
[Bug] visualMap.outOfRange is ignored if visualMap.range[1] (max) is set to 200 or more

### ISSUE THREAD

**Issue by Raphyyy** [apache/echarts#16313]
### Version

5.2.2

### Link to Minimal Reproduction

https://jsfiddle.net/z3j94b0w/

### Steps to Reproduce

Run the jsfiddle

### Expected Behavior

The item on 2022-01-01 has a value of `201`, which exceed the value set with `visualMap.range: [0, 200]`. It should appears grey according to `"outOfRange": { color": "#222" }` 

### Current Behavior

The item on 2022-01-01 is appearing red, like if the value was in range.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome (Latest)
- Framework: /
```

### Any additional comments?

 `visualMap.range: [0, 200]` : If you replace 200 with any value lower than 200, the item is correctly appearing in grey.
Using `visualMap.min` and `visualMap.max` instead of `visualMap.range` seems to completly ignore outOfRange values.

For instance, I need to display greyed items on my calendar and the only way I found is to use outOfRange and manually set a out of range value (`201` here). Setting datum value to "null" or "-" or "undefined" instead of "201" make the item disappear.

**Comment by CaelumNigre** [comment]
Works as intended. 
The "out of range" color is assigned to values that are outside of "range" option, but within the "min-max" range. By default "min" is 0 and "max" is 200 (see API docs for defaults). In your example, you don't set the "min" and "max" values so they have defaults of 0 and 200. Hence, setting the value of the range option below 0 or above 200 has no effect. When using visualmap you should set first min and max to minimal and maximum values possible in data set and the use range to visualize "expected range". The range option is just a position of "sliders" on the min-max scale, so it does not make sense outside of min-max range. 
For example if "normal" values are in range 50-100 and "possible" values are in range "0-200" and you would like to highlight abnormally low or high values with different color, you should set min to 0, max to 200 and range to [50,100].

**Comment by Raphyyy** [comment]
@CaelumNigre Thank you.
Like I said in my post, settings `"min":0, "max": 200` doesn't change a thing.
There is value at 201 and it still appears in red, is not greyed like defined in `"outOfRange": { color": "#222" }`

**Comment by Raphyyy** [comment]
I would like to be advised on how I can make the item on 2022-01-01 appears in grey (even with a workaround), see https://jsfiddle.net/yLduo6q7/

**Comment by CaelumNigre** [comment]
Here is the fiddle where Jan 1st 2022 is gray. https://jsfiddle.net/6da0w2bq/ 
In this example, any value outside of the 0-200 range (as indicated in the "range" option) will be gray.

**Comment by Raphyyy** [comment]
2022-01-01 appears in grey but the item colors are not well etalonned anymore.
If I set its value to 200, it appears in green instead of red.
I guess that I have no other choice to set the color for each item individually ?

**Comment by CaelumNigre** [comment]
If you are looking for bands type coloring (for example 0-100 is good, 101-200 is medium bad, and above 200 is bad, then you definitely need to use "continuous-customized" mode, where each "band" has a color assigned. See https://echarts.apache.org/en/option.html#visualMap-piecewise for details.

Anyway this issue is for closing.

**Comment by Raphyyy** [comment]
I am not looking for piecewised colors.
My use case is pretty simple : I have data with value that can go from 0 to 200. I need to make those data appears from green to red in a gradient way.
I also need to fill the missing days with greyed items.
I am not using the visualMap UI tool.

**Comment by CaelumNigre** [comment]
Please see this sample: https://jsfiddle.net/42vea9fj/
You need to mark somehow the lack of data for a given day as a data point outside the normal range. In my sample, I've used -1 for that purpose, but you can use any value outside the range but within the min-max range.

**Comment by Raphyyy** [comment]
@CaelumNigre Thank for your help
I'm closing this

**Comment by FFRfree** [comment]
> Please see this sample: https://jsfiddle.net/42vea9fj/ You need to mark somehow the lack of data for a given day as a data point outside the normal range. In my sample, I've used -1 for that purpose, but you can use any value outside the range but within the min-max range.

But the controller display the whole color range( including out of range color), go from -1 to 200, and the color at -1 is green, which is weird. How can i just fill the outlier block with grey without affecting the visualmap controller mapping.

**Comment by CaelumNigre** [comment]
> But the controller display the whole color range( including out of range color), go from -1 to 200, and the color at -1 is green, which is weird. How can i just fill the outlier block with grey without affecting the visualmap controller mapping.

The controller uses separate in-range/out-of-range parameters, so you can have a different map for the controller and for the visual component.
