### ISSUE TITLE
Positioning of Legends 

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#16312]
### What problem does this feature solve?

we can order the legends one below the other.At present when we position the legends as left centre it is getting overlapped with chart.Instead if we can position then one below the other when position is left or right of chart without overlapping it will be usefu;

### What does the proposed API look like?

![Screenshot (20)](https://user-images.githubusercontent.com/96459765/147905349-e4e6fc02-fbd8-4025-9acd-37aa97885ca1.png)

**Comment by CaelumNigre** [comment]
Please be more specific. 
Do you mean to have the ability to position legend items vertically? It is already available with 'legend. orient' option. By default, it is 'horizontal' (legend items are placed horizontally), but you can use ''vertical' to have their position as on the screenshot you have provided.  Here is an example: https://echarts.apache.org/examples/en/editor.html?c=pie-legend 
If you want to prevent overlapping it is the matter of setting right boundaries for chart components with 'left', 'right', 'width' etc.
