### ISSUE TITLE
[Bug]PieChart Label Line 

### ISSUE THREAD

**Issue by Eraz19** [apache/echarts#16320]
### Version

5.2.2

### Steps to Reproduce

This is based on one of the examples on your website

```js
series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: '50%',
      data: [
        { value: 1048, name: 'Search Engine' },
        { value: 735, name: 'Direct' },
        { value: 580, name: 'Email' },
        { value: 484, name: 'Union Ads' },
        { value: 300, name: 'Video Ads' }
      ],
      label: { show: true}, //What to look
      labelLine: { show: true }, //What to look
      selectedMode: "single",
      select:
      {
        labelLine: {show: false}, //What to look
        label: {show: false}
      },
      emphasis: {
        labelLine: {show: false}, //What to look
        label: { show: false},
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    }
  ]
```

### Current Behavior

In a pie series if the `labelLine` is set to `show: true` and you want in the emphasis and select mode to hide them it won't work. For the label and if we want to make them appear (meaning if we start with `show: false` and in select and emphasis we want `show: true`) it works well but the label line doesn't follow the desired behavior in the case we want to hide them in emphasis or select mode

### Expected Behavior

it should hide the label line when specified in the emphasis and select that `show: false`

### Environment

```markdown
- OS:
- Browser:
- Framework: React
```

**Comment by Ovilia** [comment]
This issue is about hiding label line doesn't work with emphasis, right?

**Comment by Eraz19** [comment]
Yes it doesn't work when emphasis and select mechanism

Le ven. 7 janv. 2022 à 03:33, Wenli Zhang ***@***.***> a
écrit :
