### ISSUE TITLE
[Bug] 地图按照官方配置填充纹理报错，但纹理可以正常显示

### ISSUE THREAD

**Issue by RoadsideParty** [apache/echarts#16323]
### Version

5.2.2

### Steps to Reproduce

填充纹理后刷新

### Current Behavior

填充纹理

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![2022-01-05_10-58-35](https://user-images.githubusercontent.com/54093484/148153964-26c2f98d-4656-4c24-ae5f-6f3e4cb585be.png)
![2022-01-05_10-58-46](https://user-images.githubusercontent.com/54093484/148153971-1efd2e37-91c1-4654-85cf-5eecf5198c93.png)

**Comment by RoadsideParty** [comment]
且第一次不会加载出纹理

**Comment by pissang** [comment]
It should been fixed in https://github.com/ecomfe/zrender/pull/851/files

**Comment by chipooi** [comment]
@RoadsideParty  可以在imgDom onload之后再进行setOption解决这个问题先

**Comment by chipooi** [comment]
@pissang 
![image](https://user-images.githubusercontent.com/50369051/149458308-33e8c23b-4818-439b-bf86-45d522c19960.png)
