### ISSUE TITLE
5.0.1版本下，自定义图表series下label属性中超出省略不生效

### ISSUE THREAD

**Issue by jane-xxx** [apache/echarts#16326]
### Version

5.0.1

### Steps to Reproduce

您好 我这里需要做一个产品的甘特图 甘特图上需要显示出产品名称，有的名称特别长，需要省略显示。
我这里尝试了在api.style()中实现样式
`
api.style({
    textBackgroundColor: '#00f',
    truncate: {
       outerWidth: 60,
       ellipsis:  '....'
    }
})
`
发现在5版本已上并不生效，5版本一下没有问题，但是因为别的图表用到了5版本的东西，并不方便降低版本。又尝试了label，但是并没有生效。
`
label: {
        show: true,
        position: 'top',
        fontSize: 16,
        backgroundColor:'#f00',
        width: 60,
        overflow:'truncate',
        formatter: '测试测试测试',
},
`

### Current Behavior

我发现在自定义图表中label绘制出来是zrender图形，我思考是不是因为这个原因，所有overflow才没有生效。

### Expected Behavior

~

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

关于图表我还有很多东西需要学习，目前遇到的问题我不太确定是不是因为自己还没有触发什么隐藏属性所以才出现这个问题，如果是的话希望你可以给些建议~

**Comment by jane-xxx** [comment]
https://codepen.io/jane-xxx/pen/PoJBpmy
这是一个演示 辛苦看下~

**Comment by KingsonCheng** [comment]
我也遇到一样的问题，请问有解决方案吗

**Comment by jane-xxx** [comment]
> 我也遇到一样的问题，请问有解决方案吗

木有~
我用的是比较笨的办法 控制字数 超过规定字数自己添加... 有点不太智能 因为对英文、数字是不友好的 但是可以解决我遇到的问题
