### ISSUE TITLE
[Bug] Gauge chart has bug with axisLine.lineStyle.color

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#16330]
### Version

5.2.2

### Link to Minimal Reproduction

https://www.makeapie.com/editor.html?c=xzl4Sd03Dz&v=1

### Steps to Reproduce

https://www.makeapie.com/editor.html?c=xzl4Sd03Dz&v=1

### Current Behavior

Pointer points to 0 and line color is wrong.

### Expected Behavior

Pointer points to data value and line color is correct.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by WindyZ99** [comment]
Hello, **_series-gauge.axisLine.lineStyle.color_** property should be an **Array**.
