### ISSUE TITLE
xAxis date does not match datalabel

### ISSUE THREAD

**Issue by qlandman** [apache/echarts#16345]
### Version

5.2.2

### Link to Minimal Reproduction

https://jsfiddle.net/78ozq0ft/6/

### Steps to Reproduce

When creating a Bar or Line chart with `xAxis` type is `time` I get a date axis that does not line up with the actual data, and corresponding data label. Taking the Bar chart example (see also: https://jsfiddle.net/78ozq0ft/6/):

```javascript
var data = [
  ['2018-12-31T00:00:00Z', 10, 5],
  ['2019-12-31T00:00:00Z', 15, 8],
  ['2020-12-31T00:00:00Z', 12, 10],
  ['2021-12-31T00:00:00Z', 19, 15]
];

option = {
  legend: {},
  tooltip: {
    trigger: 'axis'
  },
  dataset: {
    source: data,
    dimensions: ['timestamp', 'sensor1', 'sensor2']
  },
  xAxis: {
    type: 'time',
    axisTick: {
      alignWithLabel: true
    },
    axisLabel: {
      formatter: '{yyyy}-{MM}-{dd}',
      rotate: 45
    }
  },
  yAxis: {},
  series: [
    {
      name: 'sensor1',
      type: 'bar',
      encode: {
        x: 'timestamp',
        y: 'sensor1' // refer sensor 1 value
      }
    },
    {
      name: 'sensor2',
      type: 'bar',
      encode: {
        x: 'timestamp',
        y: 'sensor2'
      }
    }
  ]
};

```

### Current Behavior

The code example results in a chart where the first date on the x-axis is 2019-01-01, while I would expect to see 2018-12-31.

<img width="547" alt="line" src="https://user-images.githubusercontent.com/643288/148591268-1b8fbc44-920b-441b-8cac-095cd3741dd8.png">
The same holds for a line chart.
<img width="547" alt="bar" src="https://user-images.githubusercontent.com/643288/148591089-aad9fa49-cea9-4ab4-87b6-8c4beddbbe0f.png">

### Expected Behavior

I would expect that the x-axis labels match the labels for the data. So in the case for the data on the left hand of the graph, that both the x-axis and the data show the label 2018-12-31.

### Environment

```markdown
- OS: macOS Monterey and Windows 10
- Browser: Chrome 96.0.4664.55 and 95.0.2
- Framework: None
```

**Comment by Beramos** [comment]
This is still in an issue in 2025. Can we please reopen this?
