### ISSUE TITLE
[Bug] 版本从5.1.2升到5.2.2之后柱状图第一项数据被吞掉

### ISSUE THREAD

**Issue by projectcss** [apache/echarts#16343]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/frosty-butterfly-5xkj8?file=/src/App.js

### Steps to Reproduce

1、首先将版本设置为5.1.2或以下版本，数据是能正常展示的，讲dataset中的sourceHeader属性变为false第一项数据消失（第一项数据变为维度）是没问题的
2、将版本升级到5.1.2以上的版本，会发现第一项数据是没展示出来的，此时sourceHeader我设置的是true，然后我改动sourceHeader也是无效的

### Current Behavior

![image](https://user-images.githubusercontent.com/64296418/148527917-bc9c25a6-dada-449e-82bd-23a081e35772.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/64296418/148527874-5cb68c01-d784-4b9b-9d9b-721d00d70279.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by projectcss** [comment]
https://codesandbox.io/s/frosty-butterfly-5xkj8?file=/src/App.js

**Comment by lefex** [comment]
I'm fixing it

**Comment by lefex** [comment]
这个问题是 sourceHeader 的问题，在处理 sourceHeader 时把 false 误替换成了 null，导致 echarts 会自动识别 sourceHeader，下个版本我们会解决这个问题。目前可以通过把收据源改成数字：
![image](https://user-images.githubusercontent.com/8437666/149615891-d5de783c-fc67-4b1f-aa11-1dc3ca2c8e87.png)
