### ISSUE TITLE
[Bug] 在svg渲染模式下，渐变修改colorStops.offset的顺序为[1,0]时，反向渐变效果不显示

### ISSUE THREAD

**Issue by Ling310** [apache/echarts#16344]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/ling310/pen/vYerMJr

### Steps to Reproduce

问题见示例chart1，chart2为相同option渲染为canvas下能正常运行的效果，chart3为svg该情况下想要正常运行的替换写法。

### Current Behavior

下面这个用法在svg下无法渲染反向的渐变：
colorStops: [{offset: 1, color: 'red'}, {offset: 0, color: 'blue'}],

### Expected Behavior

希望能修复svg的渲染问题

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: -
```

**Comment by plainheart** [comment]
You should always follow the order from smallest to largest. Please refer to the [notes on gradient stops](https://www.w3.org/TR/SVG2/pservers.html#:~:text=Each%20gradient%20offset,previous%20offset%20values.) from W3C,

> Each gradient offset value is required to be equal to or greater than the previous gradient stop's offset value. If a given > gradient stop's offset value is not equal to or greater than all previous offset values, then the offset value is adjusted to be > equal to the largest of all previous offset values.
