### ISSUE TITLE
[Feature]Get plain type legend width and height number.

### ISSUE THREAD

**Issue by elantion** [apache/echarts#16349]
### What problem does this feature solve?

Let developer can auto adjust legend (plain type) position when user resize chart.

### What does the proposed API look like?

1. getLegendWidgh
2. getLegendHeight

**Comment by plainheart** [comment]
Currently, you can get the bounding rect like this,

```js
const legendModel = myChart.getModel().getComponent('legend');
const legendView = myChart.getViewOfComponentModel(legendModel )
// get the bounding rect of the legend content
const { width, height } = legendView.getContentGroup().getBoundingRect();
```

**Comment by elantion** [comment]
It works! Thanks~
