### ISSUE TITLE
[Bug] X轴nameTextStyle设置padding上下值无效

### ISSUE THREAD

**Issue by chengang0621** [apache/echarts#16357]
### Version

5.2.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/17420002/148910038-1248f01e-8431-468f-b400-c793013ae421.png)

### Current Behavior

X轴nameTextStyle设置padding上下值的时候，X轴的单位位置未发生变化

### Expected Behavior

应该和Y轴的name一样的效果

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
加个背景颜色你就能看到效果了

**Comment by chengang0621** [comment]
> 加个背景颜色你就能看到效果了

![image](https://user-images.githubusercontent.com/17420002/149090399-df541804-2a85-48d2-ac4c-b9342c209514.png)

X，Y轴相同的配置，但效果明显不同，X轴设置的padding上下值不一样，但是间距是一样的

**Comment by Ovilia** [comment]
试一下是不是 align 和 verticalAlign 的影响

**Comment by chengang0621** [comment]
verticalAlign确实有影响，但和预期的还是不一样，没有和Y轴的一样效果，在echarts4里面也是没有问题的

**Comment by chengang0621** [comment]
https://codepen.io/chengang0621/pen/abLxvgw

**Comment by s209392599** [comment]
verticalAlign:'bottom',
padding: [0, 0, -40, 0]
