### ISSUE TITLE
[Bug] Tooltip in server side rendering

### ISSUE THREAD

**Issue by Szejke** [apache/echarts#16358]
### Version

5.1.2

### Link to Minimal Reproduction

https://codesandbox.io/s/eager-mcclintock-9knx3?file=/src/index.js

### Steps to Reproduce

1 run the example svg chart for server side rendering

### Current Behavior

tooltip is not displayed

### Expected Behavior

Displaying tooltips

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

**Comment by Ovilia** [comment]
I copied the option and pasted at https://echarts.apache.org/examples/en/editor.html and set renderer to be svg and there is no problem with the tooltip. Please check if this is a problem of your environment.

**Comment by pissang** [comment]
@Szejke Server side rendering doesn't support tooltip yet. It only output SVG string without any JS script to the client side.
