### ISSUE TITLE
[Bug]渲染一个20000*20000的echarts图，页面崩溃

### ISSUE THREAD

**Issue by xyxy1** [apache/echarts#16350]
### Version

5.2.2

### Steps to Reproduce

1.绘制一个20000*20000的echarts图
![image](https://user-images.githubusercontent.com/34558169/148737356-24752217-47da-444a-a684-ff171d697918.png)

### Current Behavior

页面渲染失败

### Expected Behavior

求告知绘制宽高上限

### Environment

```markdown
- OS:window
- Browser:edge
- Framework:vue2.0
```

**Comment by plainheart** [comment]
Please refer to [this article](https://www.tutorialspoint.com/Maximum-size-of-a-canvas-element-in-HTML).

**Comment by xyxy1** [comment]
> 请参阅[此文章](https://www.tutorialspoint.com/Maximum-size-of-a-canvas-element-in-HTML)。

thanks
