### ISSUE TITLE
Background color opacity and angle

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16355]
### What problem does this feature solve?

Hi,
We have a use case where we need to apply linear gradient background color and provide opacity and angle to the applied background color.

### What does the proposed API look like?

we are looking for an option/property to set opacity and angle to the applied background color.

**Comment by Ovilia** [comment]
Can you provide a design image?

**Comment by MNHarshitha** [comment]
Hi,

Please find the design images in the attachments. They are named according to their functionality.


Thanks & Regards,

M N Harshitha

________________________________

**Comment by MNHarshitha** [comment]
Hi,

Please find the design images in the attachments.

Gradient background color with opacity 0 5 and rotation 90
![Gradient background color with opacity 0 5 and rotation 90](https://user-images.githubusercontent.com/97500674/149744723-6f8ebec5-e51c-4d14-8c54-6bf34454e796.PNG)

Gradient background color with opacity 1 and rotation 0
![Gradient background color with opacity 1 and rotation 0](https://user-images.githubusercontent.com/97500674/149745007-b5e570a3-d760-4751-9734-9ca16cc2678b.PNG)

Gradient background color with opacity 1 and rotation 90
![Gradient background color with opacity 1 and rotation 90](https://user-images.githubusercontent.com/97500674/149745136-f3824862-83fa-4c69-b100-a90dbeecbdf1.PNG)

Thanks & Regards, 
M N Harshitha

**Comment by Ovilia** [comment]
Hi, I found this feature is already supported but somehow the document is missing for the English version. An example is:

```js
option.backgroundColor = {
  type: 'linear',
  x: 0,
  y: 0,
  x2: 0,
  y2: 1,
  colorStops: [{
      offset: 0, color: 'red' // 0% 处的颜色
  }, {
      offset: 1, color: 'blue' // 100% 处的颜色
  }],
  global: false // 缺省为 false
}
```
