### ISSUE TITLE
[Feature] Being able to change the inactive text color of the graph's legend

### ISSUE THREAD

**Issue by raphaelfavier** [apache/echarts#16360]
### What problem does this feature solve?

Being able to set the inactive color of the legend's text

As far as I understand is it not possible to set the inactive color of a legend's text.

However it is possible to set the text's active color
It is also possible to set the icon's active and inactive colors.

see [this stackoverflow question](https://stackoverflow.com/questions/69741293/how-can-i-set-the-legend-text-color-when-not-selected-in-echarts)

I propose of add an inactiveColor setting to the legend.textStyle in order to match the structure of legned.itemStyle

### What does the proposed API look like?

`
legend: {
    textStyle: {
        inactiveColor: 'red'
    }
}
`

**Comment by Ovilia** [comment]
Currently the inactive text is always the same as the inactive color of the legend item, set with [legend.inactiveColor](https://echarts.apache.org/en/option.html#legend.inactiveColor). But it is not possible to set the text to a different color.

**Comment by Ovilia** [comment]
Let's see what we can do in #15747.

**Comment by raphaelfavier** [comment]
Thanks for your reactivity!
