### ISSUE TITLE
[Bug] 环状图中会将 0% 渲染成 100%

### ISSUE THREAD

**Issue by muuyao** [apache/echarts#16363]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/vibrant-field-060fe?file=/src/index.js

### Steps to Reproduce

1. 查看页面
2. 1s 后数据变化

### Current Behavior

将 0% 渲染成 100%

### Expected Behavior

正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
Seems related to the `startAngle`
