### ISSUE TITLE
[Bug] echarts-5.2.1.min.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'off')

### ISSUE THREAD

**Issue by Cherry860** [apache/echarts#16366]
### Version

5.2.1

### demo

demo URl:https://codesandbox.io/s/nifty-shtern-ppshj?file=/src/index.js

### Steps to Reproduce

script 方式引入，绘制关系图。

### Current Behavior

![Snipaste_2022-01-13_17-51-07](https://user-images.githubusercontent.com/37651304/149306957-4b8501af-a9ec-4e75-8d35-95e431e9048d.png)

### Expected Behavior

功能正常渲染

### Environment

```markdown
- OS:
- Browser:谷歌
- Framework:
```

**Comment by Cherry860** [comment]
The coordinates of the error node is:
![image](https://user-images.githubusercontent.com/37651304/149442801-d68633ee-a81f-40af-9240-a875c7b671bc.png)

**Comment by Cherry860** [comment]
demo URl:https://codesandbox.io/s/nifty-shtern-ppshj?file=/src/index.js

**Comment by Cherry860** [comment]
when symbol is 'none' ，and then the mistakes [occurred.](https://echarts.apache.org/zh/option.html#series-graph.data.symbol)

**Comment by Cherry860** [comment]
@Ovilia @plainheart May I ask how the issue is going now?

**Comment by Cherry860** [comment]
@pissang @Ovilia @plainheart Thanks for the fix, how soon will a new version be released, can I only use an earlier version at the moment?

**Comment by pissang** [comment]
@Cherry860 It will be released in next week if nothing unexpected happens
