### ISSUE TITLE
[Bug] y坐标轴位置不对

### ISSUE THREAD

**Issue by xiegegege** [apache/echarts#16370]
### Version

pyecharts：1.9.1

### Steps to Reproduce

line = (
        Line()
            .add_xaxis(step1)
            .add_yaxis("Loss", loss1)
            .set_global_opts(title_opts=opts.TitleOpts(title=args.name))
            .extend_axis(yaxis=opts.AxisOpts(name="LOSS"), xaxis=opts.AxisOpts(name="STEP"))
    )

### Current Behavior

<img width="816" alt="9871f16bfb72eaeb1a918ce1836bdcb3" src="https://user-images.githubusercontent.com/46314656/149490843-58a192be-ad0e-4e8f-b1e2-f4ad29d8393e.png">

loss坐标轴在右边

### Expected Behavior

loss坐标轴在左边

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
Try setting `position` to `'left'` explictly.
