### ISSUE TITLE
[Bug] Sunburst could NOT drill down in VUE3 projects

### ISSUE THREAD

**Issue by liujunyang** [apache/echarts#16379]
### Version

5.2.2

### Steps to Reproduce

1.have a vue3 project
2.use echarts as documentation told
3.use sunburst in a page. set the data the same as the example in documentation. 
4.FYI: the property  nodeClick is not set, thus is default value 'rootToNode'
5.click one piece

### Current Behavior

would not drill down

### Expected Behavior

to drill down

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

it works fiine in vue2 project

**Comment by liujunyang** [comment]
Are u kidding me?
I said, the bug is under vue3 projects.
It won't happen in codepen.

**Comment by pissang** [comment]
As we described in our issue template before you submittting this issue. You can use codesandbox to setup a minimal reproducible demo.

**Comment by liujunyang** [comment]
Fine，I will do that.
But i think you already know what i mean. You can just init a vue3 project with vue-cli, then instantiate a sunburst chart in a new page, and try my issue in the meanwhile.
It's quite simple.

**Comment by liujunyang** [comment]
Found the solution.
A echart instance shouldn't be placed as a vue3 reactive data, it can cause various problems.
Just declare a echart instance as a plain javascript object, and problem solved.
It probably relates to vue3's PROXY mechanism. It doesn't return the original object.
