### ISSUE TITLE
[Bug] DataSample function will cause array RangeError when echart init with is 0

### ISSUE THREAD

**Issue by Cuiyansong** [apache/echarts#16371]
### Version

5.2.2

### Steps to Reproduce

Given some dataset in order to generate large series data that will invoke sampling function.
When user create a line chart with width 0 
Then it is popup an error with ` RangeError: Invalid typed array length`

### Current Behavior

throw an error and break echart instance with some message `should not be called during main process`

### Expected Behavior

should not popup error and do not break echart instance.

### Environment

```markdown
- OS: Mac Big Sur
- Browser: Chrome v97
- Framework: React
```

### Any additional comments?

Not quite sure if it is an issue, if by design please ignore it.

**Comment by Cuiyansong** [comment]
PR #16372

**Comment by Ovilia** [comment]
Chart width is not expected to be 0. Charts should be inited after its container has width more than 0.

**Comment by Cuiyansong** [comment]
The issue have been fixed, so close the issue.
