### ISSUE TITLE
[Bug] convertFromPixel后的索引不准，且出现小数

### ISSUE THREAD

**Issue by snowyang2021** [apache/echarts#16386]
### Version

5.2.2

### Steps to Reproduce

chart.getZr().on('click', (params) => {

      const pointInPixel = [params.offsetX, params.offsetY];

      const yIndex = chart.convertFromPixel(
       {
          seriesIndex: 0
        },
        pointInPixel
      )[1];
      const yData = options.yAxis.data[yIndex];
      console.log(yIndex, options);
    });

### Current Behavior

yIndex 打印出来是小数，并不是索引

### Expected Behavior

期望 yIndex 打印出来是索引值

### Environment

```markdown
- OS:
- Browser:chrome
- Framework:
```

**Comment by pissang** [comment]
converFromPixel 返回的是数据并不是索引，是否是小数取决于 y 轴数据类型

**Comment by snowyang2021** [comment]
我看官方文档上写的叫刻度值。“[300, 900] 表示该点 x 轴上对应刻度值 300，y 轴上对应刻度值 900”。刻度值是什么意思？如果yAxis是category类型的，那刻度值怎么和索引值对应上呢？https://echarts.apache.org/examples/zh/editor.html?c=bar-rich-text
