### ISSUE TITLE
在线文档无法正常打开[Bug] 

### ISSUE THREAD

**Issue by liunuxuan** [apache/echarts#16384]
### Version

5.2.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/32322814/149881049-629d4f9d-b1a8-4802-90e2-29500f08cdab.png)

### Current Behavior

文档无法正常打开

### Expected Behavior

文档无法正常打开

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Can you access the `cdn.jsdelivr.net`?

**Comment by liunuxuan** [comment]
> 尝试看不能访问`cdn.jsdelivr.net`？或者一下看看IP地址，到CDN可能会被美国，增加部分IP无法访问。

![image](https://user-images.githubusercontent.com/32322814/151519804-0698edf0-b948-4930-bb4f-daefc5c2b560.png)
不能. 之前我找公司的运维弄了一下, 能访问了, 现在又不能正常访问了.
![image](https://user-images.githubusercontent.com/32322814/151519955-47604337-c04f-441b-b204-02ccc2bb5511.png)
