### ISSUE TITLE
[Bug] turn off the highlighting effect on mouse over

### ISSUE THREAD

**Issue by Szejke** [apache/echarts#16383]
### Version

5.1.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-simple

### Steps to Reproduce

1. hover your mouse over a column in the chart

### Current Behavior

I cannot disable this option

### Expected Behavior

turn off the backlight effect

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I can't find this option to turn it off

**Comment by pissang** [comment]
See https://github.com/apache/echarts/pull/16368
