### ISSUE TITLE
[Bug] in stacked area chart, emphasis.focus series work strange

### ISSUE THREAD

**Issue by Atlas-lili** [apache/echarts#16388]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/Atlas-lili/pen/yLzrwaw

### Steps to Reproduce

1. creat a stacked area chart and set emphasis.focus to series
```
{
  series: [
    {
      name: 'Email',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [120, 0, 0, 0, 0, 0, 0]
    },
    {
      name: 'Union Ads',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [0, 120, 0, 0, 0, 0, 0]
    },
    {
      name: 'Video Ads',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [0, 0, 120, 0, 0, 0, 0]
    },
  ]
}
```
2. Move the mouse near the area where the polylines coincide

### Current Behavior

Occasionally, all series areas are highlighted
![preview](https://s4.ax1x.com/2022/01/19/7D6lVJ.gif)

### Expected Behavior

I think that only the series to which the mouse hover area belongs should be highlighted

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 97.0.4692.71
```

**Comment by susiwen8** [comment]
Looks like `tigger: axis` affect it
