### ISSUE TITLE
[Bug] bar3d 0值渲染 及 stacked bar3d高度问题

### ISSUE THREAD

**Issue by yzhHoward** [apache/echarts#16382]
### Version

5.2.2

### Steps to Reproduce

0值渲染问题：
https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1

stacked bar3d 高度问题：
在echarts示例网页内输入如下代码：
var data = [[[0, 0, 1]], [[0, 1, 1]]];
var color = [
  '#008000', // green
  '#FF0000' // red
];
var series = [];
for (var i = 0; i < 2; i++) {
  series.push({
    type: 'bar3D',
    data: data[i],
    stack: 'stack',
    color: color[i],
  });
}
option = {
  tooltip: {},
  xAxis3D: {
    type: 'value'
  },
  yAxis3D: {
    type: 'value'
  },
  zAxis3D: {
    type: 'value'
  },
  grid3D: {
    boxWidth: 200,
    boxDepth: 120
  },
  series: series
};

### Current Behavior

0值渲染问题：
示例中可以看到部分数据z值为0，但仍出现在图中，是否可以设置不出现？目前没有找到合适的方法

stacked bar3d 高度问题：
可以看到红色柱子的开始高度是1，显然不符合常理，应该是0

### Expected Behavior

0值渲染问题：
示例中可以看到部分数据z值为0，但仍出现在图中，是否可以设置不出现？目前没有找到合适的方法

stacked bar3d 高度问题：
可以看到红色柱子的开始高度是1，显然不符合常理，应该是0

### Environment

```markdown
- OS: Windows 10 & Mac latest
- Browser: Chrome 97 & Chrome 86
- Framework: 官方示例网页环境
```

**Comment by helgasoft** [comment]
repro code does not work. Experiment with [this demo](https://echarts.apache.org/examples/en/editor.html?c=bar3d-punch-card&gl=1&code=CYQwLiAEC8kNpwAwBpIsgRgLqqaj-WWA3AFABuIATpAMYD2ANvTbHAOQDmVApjwHbtk7XsHYkK1SAGceVaRhjwSMudIBMSuBIBmLSAApKNAJZLExSGYA8kdZZMBqRwEpIAb1KRV8jADoABwBXaQALA3dIL29ISkYgngAuSFAIOBMcaO8TMB4AWwBlMABPRiSPBmYqZMqWdKwAX2iGlzJvWXl1QJDwyKzYkHjy1JB65H6c_KLS8vda6romOrMAfjRIZOwm7xayJvoAsBN6fiVPbzB6JiOA5PcG1DLOAWBE-_HvAA8AQU-TaQAzAARO4PaLFX7_YF3SBg7wAL0hgJBHjyIE-iU0cMg3BMwGhHmxHRMPGkyTg_XcJQC5XYACNqMChDIILQANaJdjSVls5kjRIdBSofggPJJLkYdjY7xU4o05L0xlA5nckDszmq9l88AgAVqdTC0XijRS6JYUgNYhAA).
