### ISSUE TITLE
[Bug] Sector bugs caused by precision.

### ISSUE THREAD

**Issue by plainheart** [apache/echarts#16385]
### Version

5.3.0

### Link to Minimal Reproduction

test/pie.html

### Steps to Reproduce

1. Open the test case `pie.html`
2. Unselect all the legends
3. Watch if the final rendered chart is a circle

### Current Behavior

Got a tiny sector that looks like a line

<img src="https://user-images.githubusercontent.com/26999792/149897197-6e5b939e-afd3-466f-bc9d-212c4cc7cdec.png" width="400">

### Expected Behavior

Got a circle

<img src="https://user-images.githubusercontent.com/26999792/149897307-4c9a1d12-4a27-466e-853f-1796dc7e1431.png" width="400">

### Environment

```markdown
- OS: Any
- Browser: Any
- Framework: No
```

### Any additional comments?

Arguments of this broken sector:
- **startAngle**: -1.5707963267948966 
- **endAngle**: 4.712388980384691

The calculated arc is `6.283185307179587`, which is slightly bigger than `2π`... so that it can't be rendered as a circle.

**Comment by plainheart** [comment]
@pissang How can perfactly we solve such an issue?

**Comment by pissang** [comment]
@plainheart Didn't notice this when reviewing the code. `mod` is not precision safe. We need to check if the angle is larger than PI2(is a circle) before doing the mod. That's what `normalizeArcAngles` do.

**Comment by pissang** [comment]
The issue fixed in https://github.com/ecomfe/zrender/pull/871 seems also related to precision. The startAngle is `0.6981317007977319 ` and endAngle is `0.6981317007977319`. Perhaps we can add an `epsilon` when checking if startAngle is same with endAngle

**Comment by pissang** [comment]
Also wee need more visual regression tests for these cases. Seems it's not reported in current tests.
