### ISSUE TITLE
YAxis log and stack combination issue

### ISSUE THREAD

**Issue by CL-yang** [apache/echarts#16398]
### Version

5.2.2

### Steps to Reproduce

1. open https://echarts.apache.org/examples/zh/editor.html?c=bar-simple
2. change yAxis type to log
3. make 3 series and make stack for each series as the same
4. load chart

### Current Behavior

yAxis label shows unreasonable

### Expected Behavior

show current

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/53500352/150314636-8e4f5900-5d92-45fa-8ffc-d71f895f5a92.png)

**Comment by pissang** [comment]
It will be fixed in the coming 5.3

**Comment by CL-yang** [comment]
thanks！
