### ISSUE TITLE
Quadrant lines inside the graph plot area - 

### ISSUE THREAD

**Issue by jak1013** [apache/echarts#16401]
### What problem does this feature solve?

this will help to mark the area which needs to be focused (helpful for Bubble and scatter plots)

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/96460632/150470222-c736bae9-6970-4ddc-9c8c-3afc302140b4.png)

**Comment by Ovilia** [comment]
You can use [graphic](https://echarts.apache.org/en/option.html#graphic.elements-line) to draw the lines.

**Comment by Ovilia** [comment]
You can use [graphic](https://echarts.apache.org/en/option.html#graphic.elements-line) to draw the lines.

**Comment by jak1013** [comment]
Thanks a lot

**Comment by sahilbutola08** [comment]
Hey guys, can anyone let me know, which chart is this? I am not able to find in the apache echarts example.

**Comment by helgasoft** [comment]
There is no official example. 
This is a scatter chart with two _markLines_ and eventually 4 titles for the 4 corners.
