### ISSUE TITLE
[Bug] type sign of convertFromPixel is rigorous

### ISSUE THREAD

**Issue by ninesunsabiu** [apache/echarts#16403]
### Version

5.0.2

### Steps to Reproduce

关于 ECharts#doConvertPixel 的 TS 类型不严谨的问题

https://github.com/apache/echarts/blob/4fe9cb0989d491ce06b0928f40c9d7500780cb7e/src/core/echarts.ts#L1807-L1837

在实现中，有两种情况将导致函数的返回值为 undefined
-  `ecIns._disposed === true` 的情况 
- `for (let i = 0; i < coordSysList.length; i++) { ... }` 循环中没有得到 `return result` 的情况  

由此风险传递到了 `convertToPixel` 和 `convertFromPixel` 方法上
这样对于使用者可能得到错误的结果

### Current Behavior

在调用 chartInstance.convertFromPixel({ seriesIndex: 0 }, [a, b]) 之后得到了 js undefined  
而在 TS 上由于不清楚这点，导致直接使用了 解构赋值，得到了 TypeError

### Expected Behavior

在  chartInstance.convertFromPixel({ seriesIndex: 0 }, [a, b]) 调用后能得到非预期的结果

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by tudou330121** [comment]
I'm interested in fixing this issue
