### ISSUE TITLE
vue3+ts 编译错误[Bug] 

### ISSUE THREAD

**Issue by virtual1680** [apache/echarts#16417]
### Version

5.2.2

### Steps to Reproduce

yarn run v1.22.11
warning package.json: No license field
$ vue-tsc --noEmit && vite build
node_modules/@types/echarts/index.d.ts:42:14 - error TS2383: Overload signatures must all be exported or non-exported.

42     function init(
                ~~~~

node_modules/@types/echarts/index.d.ts:67:14 - error TS2383: Overload signatures must all be exported or non-exported.

67     function connect(group: string | ECharts[]): void;
                ~~~~~~~

node_modules/@types/echarts/index.d.ts:75:14 - error TS2383: Overload signatures must all be exported or non-exported.

75     function disConnect(group: string): void;
                ~~~~~~~~~~

node_modules/@types/echarts/index.d.ts:83:14 - error TS2383: Overload signatures must all be exported or non-exported.

83     function dispose(target: ECharts | HTMLDivElement | HTMLCanvasElement): void;

### Current Behavior

yarn build

### Expected Behavior

编译通过

### Environment

```markdown
- OS:
- Browser:
- Framework:
```


### Any additional comments?

_No response_

**Comment by plainheart** [comment]
`@types/echarts` is contributed by the community. ECharts has officially provided type definition since v5.0.0. Please uninstall the `@types/echarts` module and try to compile again.
