### ISSUE TITLE
请问 Apache ECharts 什么可以开发个弧线图相关组件

### ISSUE THREAD

**Issue by walure** [apache/echarts#16412]
### What problem does this feature solve?

请问百度echart 什么可以开发个弧线图相关组件
类似这种的模式的http://antv-2018.alipay.com/zh-cn/g6/3.x/demo/graphql/arc-diagram.html

### What does the proposed API look like?

请问百度echart 什么可以开发个弧线图相关组件
类似这种的模式的http://antv-2018.alipay.com/zh-cn/g6/3.x/demo/graphql/arc-diagram.html

**Comment by SnailSword** [comment]
可以尝试用`type: 'graph'`，配合手动设置各个节点的`x`/`y`来实现。


不过的确也可以考虑给`graph`的`layout`支持`horizontal`之类的布局。
