### ISSUE TITLE
[Bug] yAxis labels does not match the values in line chart

### ISSUE THREAD

**Issue by MiroslavMikus** [apache/echarts#16415]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.2.2

### Steps to Reproduce

1. Just [Open](https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.2.2)
2. Compare xAxis labels with values
![image](https://user-images.githubusercontent.com/29312172/150700518-5692793e-ce1e-4351-9174-a3cccde8c534.png)

### Current Behavior

yAxis labels do not match the expected values

### Expected Behavior

yAxis labels should approximately match values in the chart.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/29312172/150700608-854726f9-0960-4ac4-9d9f-cc5c118dedaa.png">

### Environment

```markdown
- OS: Win10
- Browser: Chrome Version 97.0.4692.99 (Offizieller Build) (64-Bit)
```

**Comment by susiwen8** [comment]
Not a bug, this is a stacked line

**Comment by MiroslavMikus** [comment]
Interesting, I did somehow miss the stack Total option :sweat_smile: ...
![image](https://user-images.githubusercontent.com/29312172/150749950-2ae3426a-fcc8-4a07-beba-55feade7226b.png)

Removing this attribute does produce the desired behavior.

Thanks @susiwen8
