### ISSUE TITLE
connectNulls with stepLine fails when after a long number of null entries occur

### ISSUE THREAD

**Issue by Gyyi** [apache/echarts#16424]
### Version

5.2.0

### Link to Minimal Reproduction

https://jsfiddle.net/peyuof13/2/

### Steps to Reproduce

an old bug, but still remain

`
Create a line step chart.

Set series data containing some starting values followed by a number of 'null' entries.

Set connectNulls to trueon that series.
`

### Current Behavior

After a long-null range of series occurs - echarts reverts to drawing an interpolated line.

![image](https://user-images.githubusercontent.com/16659067/150933499-0710da27-c7a1-4ae1-a111-0212130e34a7.png)

### Expected Behavior

E-charts should draw a draw a long-step line from the start to the end of the chart.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

https://github.com/apache/echarts/issues/11274

**Comment by susiwen8** [comment]
@Gyyi https://github.com/apache/echarts/issues/11274#issuecomment-534033427 provides a solution, will you mind make a PR

**Comment by Gyyi** [comment]
> @Gyyi [#11274 (comment)](https://github.com/apache/echarts/issues/11274#issuecomment-534033427) provides a solution, will you mind make a PR

ok, I will do it.
