### ISSUE TITLE
[Bug] tooltip 设置 precision 保留2位小数无效

### ISSUE THREAD

**Issue by crazyair** [apache/echarts#16422]
### Version

5.2.0

### Link to Minimal Reproduction

https://codesandbox.io/s/funny-volhard-mclm9?file=/src/index.js

### Steps to Reproduce

鼠标 hover 到第一个点上，显示的值省略了 .00

### Current Behavior

省略了 00

### Expected Behavior

保留2位小数

### Environment

```markdown
- OS:MAC
- Browser:chrome
- Framework:React
```

**Comment by Ovilia** [comment]
无法复现？
![image](https://user-images.githubusercontent.com/779050/151299529-97908e18-470b-4e16-9ba3-e798864a2f0b.png)

**Comment by crazyair** [comment]
> 无法复现？ ![image](https://user-images.githubusercontent.com/779050/151299529-97908e18-470b-4e16-9ba3-e798864a2f0b.png)

https://github.com/apache/echarts/pull/16332 在这里用  valueFomatter 实现了
