### ISSUE TITLE
[Feature] Tooltip for step/"flat" line series aligned to category axis

### ISSUE THREAD

**Issue by fmal** [apache/echarts#16420]
### What problem does this feature solve?

Hi,

I have been using echarts successfully in my project and wanted to do the upgrade from version 3.2.x to latest 5.x. There has been some changes though (i believe in [3.5.0](https://github.com/ecomfe/echarts/releases/tag/3.5.0)) that caused the following issue for me.

I have a global tooltip with `trigger` property set to `axis`, 2 x axes of type `category` and `value` and some line series defined on the `value` axis that share the same start/end points to create "step" effect. In versions below 3.5, when you hover over the chart the tooltip shows value for a single serie:
http://jsfiddle.net/392e0mto/2/

When you move the tooltip between chart "columns" (defined by `category` axis), you can see the serie value being updated:

![2022-01-24 15 32 06](https://user-images.githubusercontent.com/927591/150802297-15461dca-2ab7-4302-92fd-751241cde1ac.gif)

This behavior allows me to create custom tooltip formatter and show flat time series values in a tooltip relative to the columns on the main category axis:

![2022-01-24 15 39 05](https://user-images.githubusercontent.com/927591/150803560-224485d7-4ada-46c2-a516-2fb0ab210cb5.gif)

However in versions 5.x (in fact any version > 3.5.0) i'm not able to get the "time series tooltip per column" effect because tooltip aggregates multiple points such as `[1,40][1,60]` and snaps to `value` axis. I'm not able to determine which point to display in the tooltip relative to the category axis columns. You can see the difference in the following demo:

http://jsfiddle.net/x9ypszuf

![2022-01-24 15 43 23](https://user-images.githubusercontent.com/927591/150804292-21f1495b-970f-41cc-a00d-b2d8d6e2c943.gif)

### What does the proposed API look like?

My question is if there is a way to replicate the same behaviour in latest echarts? 
I have tried and played with several options but can't seem to find a way around. I'm stuck and can't upgrade. Any help would be much appreciated.

**Comment by fmal** [comment]
FIY looks like a duplicate of this feature request can also be found: https://github.com/apache/echarts/issues/15122

**Comment by fmal** [comment]
@pissang @100pah also this was reported back in 2018: https://github.com/apache/echarts/issues/7543. Is there any chance that this could be addressed in the next release?

**Comment by Wintermute79** [comment]
+1

**Comment by PawelTroka** [comment]
+1

**Comment by pissang** [comment]
Sorry to be late here. Try to set on the second xAxis in the xample
```ts
axisPointer: {
  snap: false
}
```

**Comment by fmal** [comment]
@pissang thanks for your reply! Unfortunately it has no effect, the behavior stays the same.
