### ISSUE TITLE
请问在折点中如何显示对应X轴的信息和Y轴的值

### ISSUE THREAD

**Issue by zhaoyanga** [apache/echarts#16433]
### What problem does this feature solve?

请问在折点中如何显示对应X轴的信息和Y轴的值

### What does the proposed API look like?

请问在折点中如何显示对应X轴的信息和Y轴的值

**Comment by plainheart** [comment]
[series-line.label.formatter](https://echarts.apache.org/option.html#series-line.label.formatter)

```js
label: {
  show: true,
  formatter: function (p) {
    return p.name + ', ' + p.value
  }
}
```
