### ISSUE TITLE
[Feature] 关于dataset和dimensions的用法。默认dimensions中第一个维度放在x轴的用法问题

### ISSUE THREAD

**Issue by jinjiaxing** [apache/echarts#16434]
### What problem does this feature solve?

现在的数据集： 
  // 用 dimensions 指定了维度的顺序。直角坐标系中，如果 X 轴 type 为 category，
  // 默认把第一个维度映射到 X 轴上，后面维度映射到 Y 轴上。
  // 如果不指定 dimensions，也可以通过指定 series.encode
中关于dimensions用法相当于有了一些自动适配
![image](https://user-images.githubusercontent.com/4568031/151138739-2aeef902-44f6-44a4-b825-a06bd02858ca.png)
对于2015 2016 这些key本身可以理解成是year，但对于其value（数值类型）应该算不上dimensions 而应该作为指标（metrics）吧

对于我们常用的数据集一般从接口返回的格式上来说，在对象数组居多
而我们需要设置的就是【某个维度】作为x轴，【某些指标】在于y轴。直接采用dimensions：xx , metrics：[xx,yy]
更符合直观认知吧，而【  // 默认把第一个维度映射到 X 轴上，后面维度映射到 Y 轴上。】感觉还是很怪，不知道这里后续是否有优化？

### What does the proposed API look like?

dataset中dimensions

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#dataset.sourceHeader
