### ISSUE TITLE
[Feature] config grid.containLabel in each direction

### ISSUE THREAD

**Issue by zhiyuc123** [apache/echarts#16439]
### What problem does this feature solve?

In some cases, `containLable` is only expected to work on one of xAxis or YAxis.

`grid.containLabel` could be more flexiable to be configurated for xAxis and yAxis separately.

### What does the proposed API look like?

`grid.containLabel`: boolean | { top: boolean; right: boolean; bottom: boolean; left: boolean }

    grid: {
      containLabel: {
          top: true,
          right: true,
          // bottom: false as default
          // left: false as default
      }
    }

**Comment by CuteSunLee** [comment]
I'm interested in fixing this issue.
