### ISSUE TITLE
Areas background

### ISSUE THREAD

**Issue by Alchy-web** [apache/echarts#16447]
### What problem does this feature solve?

I am not sure if we can add backgrounds to specific areas by setting ranges, for example :

xAxis (start: 0, end: 4) and yAxis (start: 0, end: 6) => Green background
xAxis (start: 0, end: 4) and yAxis (start: 0, end: -6) => Blue background
xAxis (start: 0, end: -4) and yAxis (start: 0, end: 6) => Red background
xAxis (start: 0, end: -4) and yAxis (start: 0, end: -6) => Orange background

The chart needs to have Coloured areas which highlight the data like the image below
![areas](https://user-images.githubusercontent.com/3143393/151461321-bfa6b912-70e8-4224-af15-3271e6caaf2a.jpg)

### What does the proposed API look like?

No code

**Comment by pissang** [comment]
You can use [markArea](https://echarts.apache.org/zh/option.html#series-scatter.markArea)
