### ISSUE TITLE
[Feature]  Set the number of ticks in yAxis

### ISSUE THREAD

**Issue by paulogil2010** [apache/echarts#16442]
### What problem does this feature solve?

I'm wondering if it is possible to set the number of ticks in yAxis

i already setted `min` and `max`, but can't deail with the gap between some ticks

![Example](https://user-images.githubusercontent.com/25419952/151259202-9a3f9e5e-2c99-4925-b337-c25d7929af48.png)

### What does the proposed API look like?

n/a

**Comment by Ovilia** [comment]
`splitNumber` can be used to recommend label numbers but it's not compulsive. If you wish to force using a given number of labels, you should calculate `max - min` and divide it by the number of labels and set to `interval`.
