### ISSUE TITLE
[Bug] Problem with points union in lineal graphics

### ISSUE THREAD

**Issue by rvalle-dnota** [apache/echarts#16458]
### Version

ECharts 5.3

### Steps to Reproduce

when we try to connect one empty point to other not empty the line between is missing
<img width="281" alt="Captura de pantalla 2022-02-02 123703" src="https://user-images.githubusercontent.com/72879236/152147895-d2908841-07f0-4bcf-bf1a-5af7c2bf8f02.png">

### Current Behavior

when we try to connect one empty point to other not empty the line between is missing

### Expected Behavior

when we try to connect one empty point to other not empty the line between isn`t missing

### Environment

```markdown
- OS:Windows 10 Pro
- Browser:Firefox  71.0
- Framework:Laravel 8
```

**Comment by SnailSword** [comment]
Maybe `connectNulls: true` can solve the problem.
