### ISSUE TITLE
[Bug] Type of `graphic.style.textAlign` is no longer defined in `GraphicComponentLooseOption`

### ISSUE THREAD

**Issue by n0099** [apache/echarts#16455]
### Version

5.3.0-rc.1

### Link to Minimal Reproduction

https://codesandbox.io/s/jolly-mirzakhani-5bvqh?file=/src/index.ts

### Steps to Reproduce

1. open that codesandbox demo
2. revert the version of echarts back to 5.2.2
3. this type error disappeared as expected
4. and vice versa, so I guess this issue is introduced in 5.3.0-rc.1

### Current Behavior

```
Type '{ type: "text"; right: string; bottom: string; style: { textAlign: string; text: string; }; }' is not assignable to type 'Arrayable<GraphicComponentLooseOption>'.
  Types of property 'style' are incompatible.
    Type '{ textAlign: string; text: string; }' is not assignable to type '(PathStyleProps & TransitionOptionMixin<PathStyleProps>) | (ImageStyleProps & TransitionOptionMixin<ImageStyleProps>) | (TextStyleProps & TransitionOptionMixin<...>)'.
      Object literal may only specify known properties, and 'textAlign' does not exist in type '(PathStyleProps & TransitionOptionMixin<PathStyleProps>) | (ImageStyleProps & TransitionOptionMixin<ImageStyleProps>) | (TextStyleProps & TransitionOptionMixin<...>)'.ts(2322)
```
![](https://user-images.githubusercontent.com/13030387/151712952-5bcb70c9-37dd-4b67-89ee-7b1069e36702.png)

### Expected Behavior

just let this type defined back to normal like in 5.2.2

**Comment by n0099** [comment]
Note the reason of put new options in an array of type `GraphicComponentLooseOption` is I have to append multiple options for a timeline chart by merge them with `setOption({ baseOption:..., options })`.

And there's another issue about graphic component I've posted months ago: #15966, can anyone take a look at that?

**Comment by pissang** [comment]
@n0099 Use `align` instead. It's a mistake of doc. The `textAlign` has been deprecated
