### ISSUE TITLE
[Bug] TypeError: api.coord is not a function

### ISSUE THREAD

**Issue by srinathmerugu** [apache/echarts#16464]
### Version

5.3.0

### Steps to Reproduce

Using Draw polygons on map echarts example
https://echarts.apache.org/examples/en/editor.html?c=map-polygon

### Current Behavior

Getting an error like this
Uncaught TypeError: api.coord is not a function, where .coord is not an inner method of api

And also I've attached an image below which says there's an error exists in echarts example itself, you can find it on bottom right side of the image

![echarts](https://user-images.githubusercontent.com/62550907/152765692-bfae7478-a94b-4b2b-b1cc-bc8c4b5ab8fd.PNG)

### Expected Behavior

Polygon should be plotted on the map

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Framework:
```

### Any additional comments?

I couldn't see coord method inside my api object and if i try removing api.coord method it says TypeError: Cannot read properties of undefined (reading 'x') i.e., x: params.coordSys.x,

**Comment by plainheart** [comment]
This example uses [Baidu Map](https://lbsyun.baidu.com). Please make sure you can use this service in your area.

**Comment by srinathmerugu** [comment]
can u share few samples which doesn't use baidu map as it is restricted in our area

**Comment by plainheart** [comment]
Currently, only Baidu Map is officially supported. But there are also some extensions for [Google Map](https://github.com/plainheart/echarts-extension-gmap) and [Leaflet](https://github.com/joakimono/echarts-extension-leaflet) contributed by the community. You can take it a try.

**Comment by plainheart** [comment]
You may use images as scatter symbols to get a similar effect like map marker. Please refer to https://echarts.apache.org/option.html#series-scatter.symbol

**Comment by srinathmerugu** [comment]
Can i have events on echart labels? If it's possible, please share an example

**Comment by plainheart** [comment]
@srinathmerugu Please refer to these two documents.

- https://echarts.apache.org/handbook/en/concepts/event
- https://echarts.apache.org/en/api.html#events

```js
chart.on('click', { seriesName: 'SERIES NAME' }, e => {
  // do something here
})
```

**Comment by srinathmerugu** [comment]
I tried them but i was getting this below error
![image](https://user-images.githubusercontent.com/62550907/154003102-2f7b1912-07ef-4983-9383-e35e42558509.png)

**Comment by plainheart** [comment]
Can you show me more details?

**Comment by srinathmerugu** [comment]
It's working now, but i need event on the label, the links which shared by you is having events on component type, subtype, data etc. I need an event to be fired if i click on label.
And also is it possible to show multiple markers/symbols on same coordinate?
Suppose if i need a circle on top of diamond which shares same latlngs, how can i achieve it?

**Comment by plainheart** [comment]
> I need an event to be fired if i click on label.

You can determine if it's triggered by labels via `e.event.topTarget.type` or `e.event.topTarget.style.text`.

```js
chart.on('click', { seriesName: 'SERIES NAME' }, e => {
  const target = e.event.topTarget;
  if (target.type === 'tspan') {
     // triggered by label
  }
  // Or
  if (target.style.text) {
      // ...
   }
})
```

> And also is it possible to show multiple markers/symbols on same coordinate?

I have no good idea about this. But based on the information returned by the event, I think you can give some tips by customizing tooltip content or using [`graphic` component](https://echarts.apache.org/en/option.html#graphic) or [`custom series`](https://echarts.apache.org/en/option.html#series-custom) to draw symbols that share the same coordinate.

**Comment by srinathmerugu** [comment]
Thanks, but still I'm not able to fire an event even if i use target.style.text. Event is getting fired only if i click on marker/symbol, need to raise an event if only clicked on label but not on the marker.

**Comment by srinathmerugu** [comment]
I'm able to show multiple markers along with labels but labels are getting overlapping, you can see it in the image below 
![image](https://user-images.githubusercontent.com/62550907/154053991-52a5c8ab-c79c-4403-9456-ada44478ff2f.png)

I even tried labelLayout: {hideOverlap : true}, this is also not working
I'm using scatter type to plot the markers

**Comment by srinathmerugu** [comment]
I'm currently using v5.3.0

**Comment by plainheart** [comment]
Are these markers in the same series? `labelLayout` currently doesn't work in different series.

**Comment by srinathmerugu** [comment]
Yes, they're in the same series

**Comment by plainheart** [comment]
I tried it with Baidu Map. Both label event and `hideOverlap` work well.

**Comment by srinathmerugu** [comment]
Can you pls share that example here?
Or code snippet?

**Comment by plainheart** [comment]
I still remember it's unavailable in your area.

**Comment by srinathmerugu** [comment]
Yes map is unavailable, but atleast i can see your code and correct mine if you can share

**Comment by srinathmerugu** [comment]
This is what I'm trying to do with my code
![image](https://user-images.githubusercontent.com/62550907/154058442-ae6b1e2c-e75c-424b-bc94-8670038055eb.png)

**Comment by plainheart** [comment]
Please see this codepen: https://codepen.io/plainheart/pen/WNXZKjK

**Comment by srinathmerugu** [comment]
Thanks, now both label event and labelLayout are working

**Comment by srinathmerugu** [comment]
I have huge data about 2.85L markers data, i want to plot them quicker, but with default echarts rendering it's loading chunk by chunk
So, I've put large as true, now points are rendering faster but i'm losing my itemStyle i.e., color applied to each individual marker
Is there a way to render markers faster as well as not losing my itemStyle?

**Comment by plainheart** [comment]
I'm afraid you can't enable `large` if you hope to customize the symbols. Please refer to [the tip for this](https://echarts.apache.org/en/option.html#:~:text=But%20when%20the%20optimization%20enabled%2C%20the%20style%20of%20single%20data%20item%20can%27t%20be%20customized%20any%20more.).

> But when the optimization enabled, the style of single data item can't be customized any more.

This is also the reason why it renders faster when `large` is enabled.

**Comment by srinathmerugu** [comment]
Hi, when I'm trying to access leaflet with echarts i'm getting this below error
![image](https://user-images.githubusercontent.com/62550907/154444658-6b9d70f3-17db-4ac6-9b02-853dd6f66854.png)

And this is how i'm initialising echarts and leaflet
                        var myChart = echarts.init(document.getElementById('echarts-leaflet'));
			var map = L.map('echarts-leaflet');
			var leafletComponent = myChart.getModel().getComponent('leaflet');
			var map = leafletComponent.getLeaflet();

**Comment by plainheart** [comment]
You should call `setOption` first before getting the leaflet component.

```js
var myChart = echarts.init(document.getElementById('echarts-leaflet'));
myChart .setOption(option);
var leafletComponent = myChart.getModel().getComponent('leaflet');
var map = leafletComponent.getLeaflet();
```

**Comment by srinathmerugu** [comment]
my leaflet option is being set but in the component if i see there's no such property with leaflet, you can see it in the image below
![image](https://user-images.githubusercontent.com/62550907/155524629-11e017b3-df9d-4b3b-916a-4ab044b36929.png)

**Comment by srinathmerugu** [comment]
HI plainheart, is there a way in which multiple layers can be added on a single map when using echarts-leaflet package. I have a requirement where i want to render the polygon shapes of a state / country and then on top of that plot some location icons. Is this possible, if yes then please share a sample for the sample. Thanks in advance.

**Comment by plainheart** [comment]
There are two ways to draw polygon shapes.

- Leaflet API [Polygon](https://leafletjs.com/SlavaUkraini/reference.html#polygon) / [GeoJSON](https://leafletjs.com/SlavaUkraini/reference.html#geojson)
- ECharts [custom series](https://echarts.apache.org/option.html#series-custom.renderItem.return_polygon). You can refer to [this example](https://echarts.apache.org/examples/editor.html?c=map-polygon).

**Comment by srinathmerugu** [comment]
Hi, I'm currently plotting points using scatter type with my custom symbol using echarts-leaflet
But whenever i zoom in, zoom out and drag on map, i can see there's a delay on map for plotting points. Points are being spread and then sits back on the coordinates which doesn't give a good user experience.
I'm sharing the screenshots below of points getting delayed
[](https://user-images.githubusercontent.com/62550907/157419823-6d0aa6da-87f6-474f-8e20-61e3bed2b7b2.png)[](https://user-images.githubusercontent.com/62550907/157419901-211367a9-df8c-4907-9539-7cd7627c9434.png)[](https://user-images.githubusercontent.com/62550907/157419985-73b6234c-d6d4-4680-ad50-a8622c8b8629.png)
image

zoom in
image

zoom out
image

drag

**Comment by srinathmerugu** [comment]
Hi, I'm currently plotting points using scatter type with my custom symbol using echarts-leaflet
But whenever i zoom in, zoom out and drag on map, i can see there's a delay on map for plotting points. Points are being spread and then sits back on the coordinates which doesn't give a good user experience.
I'm sharing the screenshots below of points getting delayed
![image](https://user-images.githubusercontent.com/62550907/157419823-6d0aa6da-87f6-474f-8e20-61e3bed2b7b2.png)
- zoom in

![image](https://user-images.githubusercontent.com/62550907/157419901-211367a9-df8c-4907-9539-7cd7627c9434.png)
- zoom out

![image](https://user-images.githubusercontent.com/62550907/157419985-73b6234c-d6d4-4680-ad50-a8622c8b8629.png)
- drag
