### ISSUE TITLE
[Bug] after switching tabs for a while, when switching back, the chart content is blank

### ISSUE THREAD

**Issue by qiupo** [apache/echarts#16462]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple

### Steps to Reproduce

1. Upgrade Chrome to 98.0.4758.80
2. Open any of the examples on the official website
3. Switch tabs
4. Wait a moment and switch back

### Current Behavior

In Chrome version  98.0.4758.80(arm64), after switching tabs for a while, when switching back, the chart content is blank

### Expected Behavior

TAB switching does not affect chart display

### Environment

```markdown
- OS: MACOS Monterey
- Browser: 98.0.4758.80
- Framework:
```

**Comment by plainheart** [comment]
It seems to be a bug brought in Chrome 98. It can work by disabling **Experimental Web Platform features**(chrome://flags/#enable-experimental-web-platform-features).

See also https://bugs.chromium.org/p/chromium/issues/detail?id=1294505

**Comment by wangf1978** [comment]
how to work around it?

**Comment by plainheart** [comment]
@wangf1978 I'm not sure but you may try this,

```
document.addEventListener('visibilitychange', function () {
  if (document.visibilityState === "visible") {
    myChart.resize();
  }
});
```
