### ISSUE TITLE
[Bug] Override name and value of series.map.data

### ISSUE THREAD

**Issue by srinathmerugu** [apache/echarts#16465]
### Version

5.3.0

### Steps to Reproduce

Example from USA Population Estimation
https://echarts.apache.org/examples/en/editor.html?c=map-usa

### Current Behavior

I want to give my own values to the name and value property like shown below
                        const obj = {
                            name: feature.properties.STATE_NAME,
                            value: feature.properties.PERSONS
                        };
When i prepare an object like that i'm not able to see labels on the map

### Expected Behavior

We would like to map name and value with any other attribute and value from the response. For ex, Labels like state name and value is visible on the map.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I'm trying to fetch my response from the geoserver and passing its response to the series.map.data array like an object with name and value properties. Even though I'm sending the data correctly, my map is failing to display labels on the map and there's no error in the console as well.

**Comment by Ovilia** [comment]
If you are using extractly the same way as the demo, it should work the same as the demo. Otherwise, please provide a working demo.
