### ISSUE TITLE
折线与折线之间的颜色填充

### ISSUE THREAD

**Issue by james-2022** [apache/echarts#16468]
### What problem does this feature solve?

今天碰到一个需求：”折线与折线之间用不同的颜色填充，折线有多条，用来表示不同的区间背景色。有一条基线（图中的黑线）不需要填充，主要用来看基线在各区间背景色中的趋势情况“，请教一下这个该怎么实现？如下图：
![image](https://user-images.githubusercontent.com/99177056/152768574-20cf66d5-bd2f-4969-9f4a-52b94456a66e.png)

### What does the proposed API look like?

希望可以有参考的例子，谢谢。

**Comment by susiwen8** [comment]
看起来像[themeRiver](https://echarts.apache.org/examples/zh/editor.html?c=themeRiver-basic)

**Comment by james-2022** [comment]
> 图像主题[河](https://echarts.apache.org/examples/zh/editor.html?c=themeRiver-basic)

图形像，其实不是图形颜色相同的部分是两条折线数据（上限数据折线，下限数据折线）

**Comment by Ovilia** [comment]
在 https://github.com/apache/echarts/issues/16477#issuecomment-1034427507 中回复了，下次对同一个问题请不要开多个 issue，谢谢。
