### ISSUE TITLE
[Feature] Is there a way to source the ECharts library via a URL? 

### ISSUE THREAD

**Issue by veronicaxge** [apache/echarts#16461]
### What problem does this feature solve?

I've been sourcing the library by first downloading it to my local folder, and use the following code: 
`<script src="./js/echarts.min.js"></script>`

However other js libraries typically provide a way to source the library via an URL, instead of having to download the library. One example below: 
`<script src="//www.amcharts.com/lib/3/amcharts.js"></script>`

Is there a way to do the URL sourcing with ECharts? I've looked at the docs and searched everywhere but did not find an answer.  Thank you so much!! 

### What does the proposed API look like?

It'd be a life saver if we could do something like:
`<script src="//echarts.apache.org/lib/4.1.0/dist/echarts.min.js"></script>`

**Comment by plainheart** [comment]
Hi, you can use CDN such as [jsDelivr](https://www.jsdelivr.com/package/npm/echarts), [unpkg](https://unpkg.com/echarts), or [cdnjs](https://cdnjs.com/libraries/echarts).

- **jsDelivr**: https://cdn.jsdelivr.net/npm/echarts@5.3.0/dist/echarts.min.js
- **cdnjs**: https://cdnjs.cloudflare.com/ajax/libs/echarts/5.3.0/echarts.min.js
- **unpkg**: https://unpkg.com/echarts@5.3.0/dist/echarts.min.js
