### ISSUE TITLE
[Bug] markline average 显示异常

### ISSUE THREAD

**Issue by ferrydjing** [apache/echarts#16475]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/ecstatic-saha-teqpt?file=/src/App.js:2205-2212

### Steps to Reproduce

如在线例子所示，平均值显示不对， 所有数据都是0.048，但是平均值显示为0.05

### Current Behavior

如在线例子所示，平均值显示不对， 所有数据都是0.048，但是平均值显示为0.05

### Expected Behavior

期望平均值显示为0.048

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome
- Framework: React@17
```

### Any additional comments?

如图所示
<img width="728" alt="image" src="https://user-images.githubusercontent.com/27794468/152991159-6d6bd6a8-1bf3-4139-82c5-c64e3d0d1e7b.png">
平均值显示异常

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-line.markLine.precision
