### ISSUE TITLE
Unable to access 'getModel' function in typescript 

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16479]
### Version

5.2.2

### Steps to Reproduce

1. Create any chart 
2. on the chart finish event . I am trying to access
 chart.getModel().getComponent('grid')
3. So while running the application we are getting below issue

Property 'getModel' is private and only accessible within class 'ECharts'.

### Current Behavior

It is working as expected but need to make the getModel function as public

### Expected Behavior

It is working as expected but need to make the getModel function as public

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

If any workaround is there to get the component other than getModel function

**Comment by pissang** [comment]
`getModel` is not ready to be public yet. We only suggest using this method when it's the only workaround to solve the issue and you can accept the missing doc and potential breaking change of this method in the future.

**Comment by Ovilia** [comment]
Please close this issue if you don't have further questions. Thanks!
@RavalikaP

**Comment by linghengqian** [comment]
@pissang 
- I'm a bit confused, `getModel()` appears frequently, both in the documentation and in git. For example, https://echarts.apache.org/en/faq.html#baidu-map and https://github.com/apache/echarts/tree/5.3.3/extension-src/bmap both mention ` chart.getModel().getComponent('bmap').getBMap();`, which specifically accesses the private method. If this is not allowed to be used directly, should we update the documentation?

**Comment by bbcfive** [comment]
@pissang @Ovilia but if not using `getModel()`, how can I get the component value when zooming in and zooming out?

**Comment by xingorg1** [comment]
> You should listen to [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event.

@Ovilia @pissang 
**求助：** 监听datazoom事件，获取的回调参数start、end，都是百分比值，请问怎么可以更精准的拿到窗口内数轴开始、结束两个端点对应的数据值或者数组下标呢？
**现在问题是**，我使用start、end计算后，因为这俩属性值是类似0.643832459的百分比数，导致计算出来的对应x轴的下标可能多1或者少1。比如我的xAxis.data是['一', '二', '三', '四', '五']，datazoom调整handle后窗口显示[ '二', '三', '四']，然后我通过监听事件计算的窗口展示内容可能是['一', '二', '三', '四'] 或者  ['二', '三', '四', '五']。

**Comment by xingorg1** [comment]
> > You should listen to [datazoom](https://echarts.apache.org/en/api.html#events.datazoom) event.
> 
> [@Ovilia](https://github.com/Ovilia) [@pissang](https://github.com/pissang) **求助：** 监听datazoom事件，获取的回调参数start、end，都是百分比值，请问怎么可以更精准的拿到窗口内数轴开始、结束两个端点对应的数据值或者数组下标呢？ **现在问题是**，我使用start、end计算后，因为这俩属性值是类似0.643832459的百分比数，导致计算出来的对应x轴的下标可能多1或者少1。比如我的xAxis.data是['一', '二', '三', '四', '五']，datazoom调整handle后窗口显示[ '二', '三', '四']，然后我通过监听事件计算的窗口展示内容可能是['一', '二', '三', '四'] 或者 ['二', '三', '四', '五']。

解决了：
```js
myChart.on('datazoom', (params) => {
    // 获取当前图表配置
    const option: any = myChart.getOption();
    console.log(
        option.dataZoom, 
        option.dataZoom[0].startValue, 
        option.dataZoom[0].endValue
    )    
});  
```
