### ISSUE TITLE
[Bug] This library is crashing in android 11 and 12 in react native, The crash occurs when echart is not visible on the screen and the user tries to reach the end of the screen

### ISSUE THREAD

**Issue by sahilgupta1462** [apache/echarts#16470]
### Version

5.3.0

### Steps to Reproduce

1.First implemented any chart you want with scrollview on a screen.
2. Then scroll the screen to the very end and make sure that the echart is not visible on the screen any more 
3. When you will be about to reach the end of the screen then it will crash.

### Current Behavior

App crash

### Expected Behavior

The app must not crash

### Environment

```markdown
- OS:android
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
If you are using a wrapping library like [echarts-for-react](https://github.com/hustcc/echarts-for-react), please ask for help in its repo. If not, you may have to debug what's going on when chart is not visible. For example, is the chart container dom removed.
