### ISSUE TITLE
Custom axis background color

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16474]
### What problem does this feature solve?

On the click of axis we will update the background color of axis

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/15928301/152948408-7d65ef01-782b-4aa7-be6a-6f415c3d1c19.png)

**Comment by Ovilia** [comment]
You can use [graphic](https://echarts.apache.org/en/option.html#graphic.elements-rect.type) to draw a rectangle.
