### ISSUE TITLE
[Bug] The ECharts Gallery can not be opened

### ISSUE THREAD

**Issue by Laotang1234** [apache/echarts#16471]
### Version

5.2.2

### Steps to Reproduce

The ECharts Gallery can not be opened

### Current Behavior

The [ECharts Gallery](https://www.makeapie.com/) can not be opened

### Expected Behavior

can be opened

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
We're sorry but the ECharts Gallery website is no longer in service because of the Chinese ICP issue.

**Comment by Strugglemm** [comment]
Where can I see examples in the future

**Comment by heiyu4585** [comment]
Can echarts officials maintain this project

**Comment by Greasen** [comment]
ECharts Gallery 类似还会出现吗？
