### ISSUE TITLE
[Bug] Line stack leaves minor space in the chart 

### ISSUE THREAD

**Issue by sgkoishi** [apache/echarts#16478]
### Version

The live example, https://echarts.apache.org/examples/en/editor.html

### Steps to Reproduce

Charts option: <details>
  <summary>Click to expand</summary>

```javascript
option = {
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'cross'
        },
    },
    dataZoom: [{
        show: true,
        realtime: true
    }],
    toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        data: [/* ~3000 entries */]
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        name: 'Line 1',
        data: [/* ~3000 floating point numbers */],
        showSymbol: false,
        type: 'line',
        stack: 'Total',
        lineStyle: {
          width: 0
        },
        areaStyle: {
          opacity: 0.8,
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{"offset":0,"color":"hsla(0,70%,50%,1)"},{"offset":1,"color":"hsla(0,70%,50%,0.3)"}])
        },
    },{
        name: 'Line 2',
        data: [/* ~3000 floating point numbers */],
        showSymbol: false,
        type: 'line',
        stack: 'Total',
        lineStyle: {
          width: 0
        },
        areaStyle: {
          opacity: 0.8,
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{"offset":0,"color":"hsla(0,70%,50%,1)"},{"offset":1,"color":"hsla(0,70%,50%,0.3)"}])
        },
    },{
        // identical options with different color hsla()
    }]
};
```

</details>

### Current Behavior

| Renderer  | SVG | Canvas |
| ------------- | ------------- | ------------- |
| Firefox Nightly 99.0a1 (2022-02-08) (64-bit) | ![image](https://user-images.githubusercontent.com/9637711/153115566-71cd8271-d0d1-43b6-8a65-c5a28b827b66.png)  | ![image](https://user-images.githubusercontent.com/9637711/153115003-91746bda-02b4-4e39-a9bb-2e1062ee8941.png) |
| Edge 98.0.1108.43 (Official build) (64-bit)  | ![image](https://user-images.githubusercontent.com/9637711/153115632-ae13c98a-7087-489c-83bf-dd866d513294.png)  | ![image](https://user-images.githubusercontent.com/9637711/153115233-60383811-8772-4ec9-a89f-03403a2f8cbb.png) |
| Chrome 98.0.4758.82 (Official Build) (64-bit) | ![image](https://user-images.githubusercontent.com/9637711/153115685-a66decee-0def-4a77-a298-181ab735910b.png)| ![image](https://user-images.githubusercontent.com/9637711/153115386-7d1835a9-168f-4e79-9ba4-5359009009cf.png) |

### Expected Behavior

 All images should come with no overlap and no white space inside.

### Environment

```markdown
- OS: Windows 10 Version 21H1 (OS Build 19044.1503)
- Browser: Firefox, Edge and Chrome as listed
- Framework: The examples live demo from https://echarts.apache.org/examples/en/editor.html
```

### Any additional comments?

There are 10 lines and around 3000 points for each line, all of the data are floating-point numbers; x-axis data are strings.

**Comment by Ovilia** [comment]
Please provide a minimal data for easier debugging.

**Comment by sgkoishi** [comment]
It's hard to say 'minimal' since it only happens when the amount of points is large. 3000 points * 10 lines rendered to white space, but 300 * 10 is fine.
Sample: [echarts.txt](https://github.com/apache/echarts/files/8037594/echarts.txt)
Copy the content to the live demo to see.

**Comment by stas-sl** [comment]
Also faced same issue (https://github.com/apache/echarts/issues/16879), but I found a combination of options that worked quite well in my case.
