### ISSUE TITLE
[Bug] https://www.makeapie.com/explore.html为甚不能访问

### ISSUE THREAD

**Issue by huangwenhui19940707** [apache/echarts#16486]
### Version

https://www.makeapie.com/explore.html

### Steps to Reproduce

https://www.makeapie.com/explore.html不能访问

### Current Behavior

https://www.makeapie.com/explore.html不能访问

### Expected Behavior

https://www.makeapie.com/explore.html可以访问

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
https://github.com/apache/echarts/issues/16471
