### ISSUE TITLE
Regression lines for Line Chart

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16482]
### What problem does this feature solve?

Need to plot a linear or polynomial Lines for the line chart with the category and values axis.

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/15928301/153161345-cdf2c6fa-a618-4efe-a14e-dd20ccb45024.png)

**Comment by RavalikaP** [comment]
Here is the sample options structure

echarts.registerTransform(ecStat.transform.regression);
const data = [
  { name: 'Mon', value: 150 },
  { name: 'Tue', value: 230 },
  { name: 'Wed', value: 224 },
  { name: 'Thu', value: 218 },
  { name: 'Fri', value: 135 },
  { name: 'Sat', value: 147 },
  { name: 'Sun', value: 260 }
];
option = {
  dataset: [
    {
      source: data
    },
    {
      transform: {
        type: 'ecStat:regression'
      }
    }
  ],
  xAxis: {
    type: 'category'
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      type: 'scatter'
    },
    {
      name: 'line',
      type: 'line',
      datasetIndex: 1,
      symbolSize: 0.1,
      symbol: 'circle',
      label: { show: true, fontSize: 16 },
      labelLayout: { dx: -20 },
      encode: { label: 2, tooltip: 1 }
    }
  ]
};

**Comment by Ovilia** [comment]
https://github.com/ecomfe/echarts-stat#regression
