### ISSUE TITLE
[Feature] 可以支持绘制lineplot置信区间图吗

### ISSUE THREAD

**Issue by piscesvivian** [apache/echarts#16487]
### What problem does this feature solve?

在算法数据分析中，论文里面会经常用到一种图，seaborn已经有实现，但是ECharts不清楚该如何去绘制
形如：

![image](https://user-images.githubusercontent.com/4689786/153352751-81ea43ab-3c15-43fc-b46a-e0fa883f1e88.png)

show the mean and 95% confidence interval

而且可以平滑平均线

具体图绘制示例如seaborn lineplot文档：
http://seaborn.pydata.org/generated/seaborn.lineplot.html

### What does the proposed API look like?

我们能提供一类：type: lineplot 的绘制方法吗？

**Comment by plainheart** [comment]
或许你可以参考这个示例实现：https://echarts.apache.org/examples/editor.html?c=confidence-band

**Comment by piscesvivian** [comment]
单个数据的绘图还可以处理，像上图那样的多组数据绘制起来就比较麻烦了。 感谢，这个我可以参考一下。
