### ISSUE TITLE
Need x,y,Width,Height of the chart elements

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16480]
### What problem does this feature solve?

Need X, Y position along with Height and Weight of the chart elements like xAxis, yAxis, Grid, Legends.
If we get this values we will append some graphic elements to it and apply some styling to it.

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/15928301/153123823-bc4600ed-5954-4cca-ba29-bbc9848201c9.png)
![image](https://user-images.githubusercontent.com/15928301/153123886-634733ec-ad05-4add-a394-3e4dbfc28fe9.png)

**Comment by Ovilia** [comment]
There are no such APIs but you can get this information `option.grid` and ` option.legend` from your input option.

**Comment by RavalikaP** [comment]
@Ovilia but on option.legend and option.grid we are not getting the updated values. If it is updated then it will be easy to get it.

**Comment by plainheart** [comment]
You may get such information via some internal APIs. Just FYI.

**Grid**

```js
// if there are multiple grids, use `getComponent('grid', gridIndex)`
const gridRect = chart.getModel().getComponent('grid').coordinateSystem.getRect();
```

**Axis**

```js
// if there are multiple axes, use `getComponent('xAxis', axisIndex)`
const xAxisModel = chart.getModel().getComponent('xAxis');
const xAxisView = chart.getViewOfComponentModel(xAxisModel);
const xAxisRect = xAxisView.group.getBoundingRect();
```

**Comment by RavalikaP** [comment]
@plainheart , Thank you for the reply. can u please suggest me how to get the legends?

**Comment by plainheart** [comment]
@RavalikaP It's similar to the above.

```js
const legendModel = chart.getModel().getComponent('legend');
const legendView = chart.getViewOfComponentModel(legendModel);
const legendRect = legendView.group.getBoundingRect();
const [x, y] = legendView.group.transformCoordToGlobal(legendRect.x, legendRect.y);
const { width, height } = legendRect;
console.log(x, y, width, height);
```
