### ISSUE TITLE
[Feature] add borderRadius option to heatmap

### ISSUE THREAD

**Issue by fmmattioni** [apache/echarts#16490]
### What problem does this feature solve?

 Taking this ECharts example https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian, I was wondering if it would be somehow possible to apply a border-radius to each square of the heatmap. My goal was that make these squares appear as rounded elements, like that: https://9elements.com/blog/content/images/border-radius-1.png.

I have tried using the `series-heatmap.itemStyle.borderRadius` property, but that does not seem available.

Any ideas?

### What does the proposed API look like?

I believe adding `series-heatmap.itemStyle.borderRadius` would solve the problem easily.

**Comment by paulkarpenko** [comment]
@Rain120 Came here looking for a way to add `borderRadius` to bar charts and found this. The prop is not included in `barItemStyle.js` and I haven't seen any examples showing rounded-corner bar charts. Can it be added to bar as well as headmap? Thank you! 🙏🏻

**Comment by pissang** [comment]
@paulkarpenko Check https://echarts.apache.org/en/option.html#series-bar.itemStyle.borderRadius
