### ISSUE TITLE
[Bug] Missing documentation

### ISSUE THREAD

**Issue by Nurech** [apache/echarts#16499]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/en/option.html#series-line.markLine.label.position

### Steps to Reproduce

Visit https://echarts.apache.org/en/option.html#series-line.markLine.label.position and look at the first example chart under it. 

### Current Behavior

Empty chart example.

### Expected Behavior

Expecting something in the chart or don't show at all.

### Environment

```markdown
- Browser: Chrome
```

**Comment by plainheart** [comment]
Thanks for the feedback. This example is also available on https://echarts.apache.org/examples/editor.html?c=line-markline
