### ISSUE TITLE
[Bug] series.labelLayout.x在动态排序的柱状图中会卡住

### ISSUE THREAD

**Issue by jackz010** [apache/echarts#16508]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/fast-sun-4guwo?file=/src/index.js

### Steps to Reproduce

动态排序时，bar上升一位后标签会卡住

### Current Behavior

动态排序时，bar上升一位后标签会卡住

### Expected Behavior

排序后标签显示在相应位置

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
It's because you have fixed the `x` to 10.
