### ISSUE TITLE
Mouseover on axis labels are not working 

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16500]
### Version

5.2.2

### Steps to Reproduce

1. Create one chart with axis
2. Register mouse over event on axis labels
3. event is not getting  triggered

myChart.on('mouseover', 'xAxis.axisLabel',(params) => {
  console.log(params)
  alert();
});

### Current Behavior

  Axis label mouse over event is not triggering

### Expected Behavior

Axis label mouse over event has to trigger

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
You need to set [`xAxis.triggerEvent`](https://echarts.apache.org/en/option.html#xAxis.triggerEvent) as `true`.
