### ISSUE TITLE
[Bug] 在web echarts 5.3版本里面可以给出关于3d柱形图和3d散点图含多个类别的可视化示例嘛？（急）

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [apache/echarts#16507]
### Version

5.3.5

### Steps to Reproduce

None

### Current Behavior

None

### Expected Behavior

None

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Rain120** [comment]
Do you mean these graphs?

bar3d : https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1

scatter3d: https://echarts.apache.org/examples/zh/editor.html?c=scatter3d&gl=1&theme=dark

**Comment by Zhangzhixiang-laugh** [comment]
> Do you mean these graphs?
> 
> bar3d : https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1
> 
> scatter3d: https://echarts.apache.org/examples/zh/editor.html?c=scatter3d&gl=1&theme=dark

是的，如何去实现自定义按x轴/y轴的不同配色，或者自定义数据类别配色，如果有的话，麻烦分享一下js的代码，感谢！

**Comment by pissang** [comment]
@Zhangzhixiang-laugh GitHub issue is not supposed to answer this kind of questions. I'm going to close it.
