### ISSUE TITLE
[Bug] 对数轴存在0值时，坐标轴的最大值不对

### ISSUE THREAD

**Issue by weijiaduo** [apache/echarts#16504]
### Version

5.3.0

### Steps to Reproduce

直接在官网的在线编辑就可以 https://echarts.apache.org/examples/zh/editor.html。

测试用的 options：

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'log'
  },
  series: [
    {
      data: [150, 230, 224, 0, 135, 147, 260],
      type: 'line'
    },
    {
      data: [50, 130, 324, 212, 165, 247, 160],
      type: 'line'
    }
  ]
};
```

### Current Behavior

![图01-异常效果](https://user-images.githubusercontent.com/17950048/153854134-501e61ad-a093-4298-9d0c-24fa1f6cb0d7.png)

### Expected Behavior

![图02-正常效果](https://user-images.githubusercontent.com/17950048/153854180-1c231fac-c267-4b4d-bfc5-79a4c5458c1b.png)

虽然数据中存在一个异常数据0，确实不太合理，但是还是希望坐标轴能够正常显示，而不是默认最大值10。

### Environment

```markdown
- OS: windows 11
- Browser: Chrome 96.0.4664.45
- Framework:
```

**Comment by pissang** [comment]
Use `'-'` to replace `0`

**Comment by weijiaduo** [comment]
> 

感谢，换成 '-' 后确实可以。

**Comment by weijiaduo** [comment]
> Use `'-'` to replace `0`

感谢，换成 '-' 后确实可以。
