### ISSUE TITLE
[Bug] pie chart can not show negative value

### ISSUE THREAD

**Issue by yih0620** [apache/echarts#16510]
### Version

5.3.0

### Steps to Reproduce

1. use sample pie chart.
2. change all value to negative.

### Current Behavior

![image](https://user-images.githubusercontent.com/33826620/154027125-9fea2bb9-3c6f-44f8-8882-8640dc3a5df6.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/33826620/154027633-33ab0e92-d39d-4724-b8dc-051e7176bc72.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
Negative value is invalid in the pie chart.

**Comment by yih0620** [comment]
it's allowed at echart 4.0.
