### ISSUE TITLE
[Bug] svg渲染模式下载的svg图片背景色是黑色的

### ISSUE THREAD

**Issue by zhouYji** [apache/echarts#16515]
### Version

4.8.0

### Steps to Reproduce

const option = {
      ...boxOption,
      title: [{
        left: 'center'
      }],
      toolbox:{
        feature: {
          saveAsImage: {}
        }
      },
      xAxis: {
        ...boxOption.xAxis,
        data: newData.groupName,
        axisLabel: {
          // formatter: '{value}',
          rotate: -40,
          interval: 0,
        },
      },
      series: [
        {
          name: 'boxplot',
          type: 'boxplot',
          data: data.boxData,
          tooltip: {
            formatter: function (param) {
              return [
                'Experiment ' + param.name + ': ',
                'upper: ' + param.value[5],
                'Q3: ' + param.value[4],
                'median: ' + param.value[3],
                'Q1: ' + param.value[2],
                'lower: ' + param.value[1]
              ].join('<br/>');
            }
          }
        },
        // {
        //   name: 'outlier',
        //   type: 'scatter',
        //   data: data.outliers
        // }
      ]
    };
    myChart.setOption(option);

### Current Behavior

通过svg渲染后下载svg图片，使用AI软件打开，背景色变成了黑色，为异常状态。

### Expected Behavior

通过svg渲染后下载svg图片，使用AI软件打开，背景色正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
是黑色还是透明？如果想要有背景色，可以指定下 `backgroundColor`
