### ISSUE TITLE
How to sort stacked bar chart 

### ISSUE THREAD

**Issue by Sunghee2** [apache/echarts#16512]
### Version

5.3.0

### Steps to Reproduce

I use stacked bar using echarts like [this example](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack). When drawing stacked bar graph in echarts, it is not possible to sort bars. I can change the order of legend using legend.data.name but the option can't change the order of bar. For example, I want to change the order of *Direct* bar and *Mail Ad* bar

### Current Behavior

![image](https://user-images.githubusercontent.com/31603479/154060656-b2096fdd-10b2-47f6-bc34-423f53cefab3.png)

### Expected Behavior

The bars and legend should be sorted with a given array like ['Mail Ad', 'Direct', 'Video Ad', 'Affiliate Ad', 'Search Engine']

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
You can change the order of the series in the array.

**Comment by Sunghee2** [comment]
> You can change the order of the series in the array.

Thank you for your answer. 
But I am in a situation where I can’t change series . So is there any other way?

**Comment by plainheart** [comment]
I'm afraid there is currently no way to specify the stack order.

**Comment by ermaugustinas** [comment]
Would this be difficult to implement? We'd like to be able to sort the values as well.
