### ISSUE TITLE
Axis line and axis ticks are not changing the position

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16523]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple

### Steps to Reproduce

1. Create one basic Line chart report
2. Add x-axis position as 'top'
3. Axis is not moving at the top position

### Current Behavior

X-Axis is not moving as Y-Axis is moving
![image](https://user-images.githubusercontent.com/15928301/154406758-483fdef6-14cf-4aa7-890f-cd3f0866ceb1.png)

### Expected Behavior

Axis should be moved as expected

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
```js
position: 'top',
axisLine: {
  onZero: false
},
axisTick: {
  inside: true
}
```

**Comment by RavalikaP** [comment]
@plainheart thank you
