### ISSUE TITLE
[Bug] Exported custom JSON theme file can not be imported

### ISSUE THREAD

**Issue by Nurech** [apache/echarts#16532]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/en/theme-builder.html

### Steps to Reproduce

1. Take any theme.
2. Modify it a bit.
3. Save as json file.
4. Try to import.
5. It fails. _"Please use the exported JSON configuration files from our site instead of downloaded theme file. "_

### Current Behavior

Does not let import theme JSON file.

### Expected Behavior

Would be nice to import it for editing.

**Comment by plainheart** [comment]
What did you modify in this file? Is there any error from the console?

**Comment by Nurech** [comment]
> What did you modify in this file? Is there any error from the console?

Well I edited the file quite a bit and when I went to modify it I got the error message. When trying to figure out if my theme was malformed I tried to validate one of your default themes by downloading a random theme from echarts selection and trying to import it (it fails). This leads me to believe that problem is on echart side and no one can upload/import any theme files. Must be some kind of frontend validator for the JSON as I don't see any errors in the console nor any requests going out.

**Comment by plainheart** [comment]
You may refer to the [source code](https://github.com/apache/echarts-theme-builder/blob/master/app/scripts/main_en.js) and check if you modified or deleted some fields required by ECharts theme builder.

**Comment by Nurech** [comment]
> You may refer to the [source code](https://github.com/apache/echarts-theme-builder/blob/master/app/scripts/main_en.js) and check if you modified or deleted some fields required by ECharts theme builder.

I am literally downloading an **unmodified** theme from echarts theme builder and then trying to upload it back to itself - it errors. Weird that it's not backwards compatible - if it can't accept an valid theme from source it surely can't accept any themes (changed or not changed).

**Comment by plainheart** [comment]
If so, I guess you are using **_Download_** rather than **_Export_**. To be clear, you will get a JSON/JS file via the **_Download_** button, it can be directly used in ECharts but it's **NOT** available for ECharts theme builder. Only the files generated by **_Export_** are acceptable for the theme builder. You should click the **_Export_** button to get the configuration file and then upload the modified file via **_Import_** button to preview, adjust, or download your customized theme(also via **_Download_**).

**Comment by plainheart** [comment]
Thanks. It's not perfect currently but I believe we will improve and enhance the theme tool in the future.
