### ISSUE TITLE
useDirtyRect = true and saving image shows "Save as Image" label

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#16534]
### Version

5.0.0

### Steps to Reproduce

1. Go to https://echarts.apache.org/examples/en/editor.html?c=line-step
2. Turn on "Use Dirty Rect"
3. Download the image.

### Current Behavior

It contains the "Save as Image" label.

### Expected Behavior

It should not contain the "Save as Image" label in the image.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dirslashls** [comment]
I am not 100% sure but I think excluded elements during rendering for image need to be explicitly cleared when setting  useDirtyRect to true.

**Comment by linghaoSu** [comment]
@plainheart hi, I  find the problem that caused the current issue in zrender, could you help me to review my pr?
