### ISSUE TITLE
Bar Position: Can we get the x,y,width and height of a particular bar?

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16533]
### What problem does this feature solve?

I want to add one graphic element on top, left, right (it can be any position). I want to add graphic elements on particular bar based on index or value. So, do we get the position of the bar to add graphic element.

### What does the proposed API look like?

Adding graphic element on top of bars.

**Comment by plainheart** [comment]
Just as I said before, you still can get the elements via internal APIs.
```js
// get the series model
const model = myChart.getModel().getSeriesByIndex(0); // `getSeriesByType`/`getSeriesByName` is available
// get the series view
const view = myChart.getViewOfSeriesModel(model);
// get the element group
const group = view.group;
// get all the elements in the group
const elements = view.group.childrenRef();
// get the bounding rectangle of one element
const boundingRect = elements[0].getBoundingRect();
```

**Comment by RavalikaP** [comment]
@plainheart, In case of line chart how we will be adding?
