### ISSUE TITLE
Bar chart unable to select more than 1 bar

### ISSUE THREAD

**Issue by zhixuan-loh** [apache/echarts#16546]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/white-dawn-esbnxv?file=/src/index.js

### Steps to Reproduce

1. Create a basic bar chart.
2. Add `itemStyle`s to "select" attribute. Each bar should change colour upon click.
3. Fire an event as in below:
```
chart.dispatchAction({
  type: "select",
  dataIndex: [0, 1],
  seriesIndex: [0]
});
```

### Current Behavior

Only 1 bar turns red and it is always the bar whose index corresponds to the last number in `dataIndex` (1 in the codesndbox example)

### Expected Behavior

The 1st & 2nd bar should turn red because judging from the documentation, this attribute of the event accepts `number[]` which implies that it can help u select more than 1 item (bar in this case)

### Environment

```markdown
- OS: Windows 10
- Browser: Google Chrome
- Framework: Vue 3 Typescript
- Echarts (not vue-echarts)
```

### Any additional comments?

I need to create a line graph (possibly 40k data points) and I need to be able to select a few(>1 graphs) out of dozens of graphs. I want the unselected graphs to blur but I don't want to use emphasis/blur options because I don't need it to keep rendering emphasised/blurred graphs upon mouseover.

I'm trying to see if we can select multiple data items and thereafter seeing if the same behaviour can be expected from line graphs(Issue 16545).

I'd appreciate your advice.

**Comment by susiwen8** [comment]
selectedMode: 'multiple',
https://echarts.apache.org/en/option.html#series-bar.selectedMode

**Comment by zhixuan-loh** [comment]
Thank you for your help!
Sorry, can I ask is the same thing achievable with line graphs?  I posted another [issue](https://github.com/apache/echarts/issues/16545) detailing how I couldn't get this to work with echart's line graphs. I'd appreciate if you could also help me with that as it might be a commonly needed feature.
