### ISSUE TITLE
"select" styles not working for line graphs

### ISSUE THREAD

**Issue by zhixuan-loh** [apache/echarts#16545]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/priceless-resonance-hedki5?file=/src/index.js

### Steps to Reproduce

1. Create a simple line chart with >1 line.
2. Make sure every line-series in the data has the following options(these are prepared in the [Link to Minimal Reproduction](https://codesandbox.io/s/priceless-resonance-hedki5?file=/src/index.js)):
```
selectedMode: true,
      select: {
        disabled: false,
        lineStyle: {
          color: "rgba(255, 0, 0, 1)"
        }
      }
```
3. Click on any line

### Current Behavior

Nothing happens. No change of `lineStyle.color` is observed on any line.

### Expected Behavior

Expect the selected graph to turn red as specified in the options.

### Environment

```markdown
- OS: Windows
- Browser: Google chrome
- Framework: Vue 3 (Typescript)
- echarts(Not Vue-echarts)
```

### Any additional comments?

I need to create a graph (possibly 40k data points) and I need to be able to select a few(>1 graphs) out of dozens of graphs. I want the unselected graphs to blur but I don't want to use emphasis/blur options because I don't need it to keep rendering emphasised/blurred graphs upon mouseover. 

I'd appreciate your advice.

**Comment by susiwen8** [comment]
I have checked this code, `polyline`  doesn't have `select` state, so I don't think `select` style should include `lineStyle`, Also `selectedMode` was design to use on `data item`, which are `emptyCircle` in your case. Maybe we should remove `lineStyle` from doc

**Comment by zhixuan-loh** [comment]
> I have checked the source code, `polyline` doesn't have `select` state, so I don't think `select` style should include `lineStyle`, Also `selectedMode` was designed to use on `data item`, which are `emptyCircle` in your case. Maybe we should remove `lineStyle` from doc

Thank you for your clarification. May I know if you are planning to implement this feature?

**Comment by susiwen8** [comment]
Casue `select` is for `item`, so this feature would not be considered. If your want to change `lineStyle` when click on line, I suggest to use [`triggerLineEvent`](https://echarts.apache.org/zh/option.html#series-line.triggerLineEvent) along with [`click` event](https://echarts.apache.org/zh/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6.click)
