### ISSUE TITLE
[Bug] : Minor ticks issue with time axis 

### ISSUE THREAD

**Issue by spoojaj** [apache/echarts#16541]
### Version

5.3.0

### Steps to Reproduce

1. Create the chart with realtime data and xaxis is time axis.
2. Add minor ticks to xaxis.
3. look for minor ticks.

### Current Behavior

![image](https://user-images.githubusercontent.com/93267110/154702333-1656be4f-eec3-4a7c-98c2-001ce62a8505.png)

Highlighted part is where the ticks are adjusted in compromised position.

Ideally should be spread similar to rest of intervals.

### Expected Behavior

![Capture_2](https://user-images.githubusercontent.com/93267110/154703699-b8e4ac8b-9af6-4883-b273-66f767de5061.png)
 Expected Behavior. 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Please check the example below.

```js
function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
      Math.round(value)
    ]
  };
}
let data = [];
let now = new Date(1997, 9, 3);
let oneDay = 24 * 3600 * 1000;
let value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
  data.push(randomData());
}
option = {
  xAxis: {
    type: 'time',
    splitLine: {
      show: false
    },
    minorTick: {
      show: true,
    }
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [
    {
      name: 'Fake Data',
      type: 'line',
      showSymbol: false,
      data: data
    }
  ]
};
setInterval(function () {
  for (var i = 0; i < 5; i++) {
    data.shift();
    data.push(randomData());
  }
  myChart.setOption({
    series: [
      {
        data: data
      }
    ]
  });
}, 1000);
```

**Comment by Ovilia** [comment]
`minorTick` cuts ticks into a given number of parts, which by default is 5. The reason why it behaves like this is because it cuts the axis from the beginning (/end) to the first (/last) tick. 
The time between two ticks in the time axis is not the same. So it's hard to tell how long should the beginning or ending minor ticks should last.

**Comment by ragava28** [comment]
@Ovilia , as the dynamic(new) data, comes in, the time between two major ticks won't match only in these 2 case 

1. before the first major tick
2. after the last major tick 

so in these 2 case , can we control the no of minor ticks to shown?  or can we completely hide minor ticks?

**Comment by Ovilia** [comment]
You cannot ignore those only before the first and after the last. The only thing you can do is to hide the minor ticks all.
