### ISSUE TITLE
[Bug] Missing doc old reference to image

### ISSUE THREAD

**Issue by Nurech** [apache/echarts#16543]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/en/option.html#toolbox.feature

### Steps to Reproduce

Example code is referencing to old URI and example icon of `icon: 'image://http://echarts.baidu.com/images/favicon.png',` does not work.

### Current Behavior

Doesn't show icon.

### Expected Behavior

Probably should.

**Comment by plainheart** [comment]
Thanks for the feedback. Would you like to help correct it in the [echarts-doc](https://github.com/apache/echarts-doc) repo?

**Comment by Nurech** [comment]
#16318 

> Thanks for the feedback. Would you like to help correct it in the [echarts-doc](https://github.com/apache/echarts-doc) repo?
> 
> BTW: This image is now available on: https://echarts.apache.org/en/images/favicon.png

Sure, Thanks!
