### ISSUE TITLE
[Bug] canvas尺寸较小时折线图上的散点未显示

### ISSUE THREAD

**Issue by yuelight** [apache/echarts#16558]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/optimistic-dust-svxfyh

### Steps to Reproduce

拖拽改变browser面板的尺寸，17:00有个点在面板宽度较长时显示，较短时未显示（此处临界值在canvas宽度为1100左右）

![Feb-22-2022 18-49-49](https://user-images.githubusercontent.com/17741765/155117462-de44a13c-7362-4358-a52c-a714f663ba43.gif)

### Current Behavior

canvas尺寸较小时图中17:00的点未显示
![CleanShot 2022-02-22 at 18 52 30](https://user-images.githubusercontent.com/17741765/155117854-681f313b-431f-4b33-8768-7302704c8a35.png)

### Expected Behavior

不论宽度是否变化都显示

![CleanShot 2022-02-22 at 18 53 41](https://user-images.githubusercontent.com/17741765/155117996-2936953f-37a9-427a-8ec3-ba9a2c4f32db.png)

### Environment

```markdown
- OS: MacOS
- Browser: Chrome 98.0.4758.102
- Framework: React
```

### Any additional comments?

如有相关配置可以解决或是因某种原因如此设计，烦请告知

**Comment by plainheart** [comment]
可以用 [`axisLabel.interval`](https://echarts.apache.org/option.html#xAxis.axisLabel.interval) 调整下标签间隔。
