### ISSUE TITLE
[Feature] Phylogenetic tree

### ISSUE THREAD

**Issue by nikolay-alemasov** [apache/echarts#16555]
### What problem does this feature solve?

Tree charts now cannot have a distance information for the particular edge. To draw not usual but [phylogenetic tree](https://en.wikipedia.org/wiki/Phylogenetic_tree) such an information is used to depict distance between different sequences of the same gene in different organisms. Ideally such a tree should also be able to be constructed from a file in [Newick format](https://en.wikipedia.org/wiki/Newick_format).

### What does the proposed API look like?

```
myChart.showLoading();
$.get(ROOT_PATH + '/data/asset/data/phylogenetic-tree.nwk', function (data) {
  myChart.hideLoading();
  myChart.setOption(
    (option = {
      tooltip: {
        trigger: 'item',
        triggerOn: 'mousemove'
      },
      series: [
        {
          type: 'tree',
          data: [data],
          left: '2%',
          right: '2%',
          top: '8%',
          bottom: '20%',
          symbol: 'emptyCircle',
          orient: 'vertical',
          expandAndCollapse: true,
          label: {
            position: 'top',
            rotate: -90,
            verticalAlign: 'middle',
            align: 'right',
            fontSize: 9
          },
          leaves: {
            label: {
              position: 'bottom',
              rotate: -90,
              verticalAlign: 'middle',
              align: 'left'
            }
          },
          animationDurationUpdate: 750
        }
      ]
    })
  );
});

```

**Comment by Ovilia** [comment]
Hi, I see that there are many designs in [Phylogenetic_tree](https://en.wikipedia.org/wiki/Phylogenetic_tree). Which one is required? Like this one?

![](https://en.wikipedia.org/wiki/Phylogenetic_tree#/media/File:MyosinUnrootedTree.jpg)

Would [graph series](https://echarts.apache.org/examples/en/editor.html?c=graph) be useful in this case? But you have to provide the position of each node.

**Comment by nikolay-alemasov** [comment]
It could be like this:

![image](https://user-images.githubusercontent.com/93376115/155292615-c131c00d-b375-4fde-ae4d-d499f74757b8.png)

At least usually people get used to see such design. But the design itself can be different. For instance:

![image](https://user-images.githubusercontent.com/93376115/155292883-a14cc6b3-53bb-4de1-991f-34d2c1a4c8ca.png)

Or like this:

![image](https://user-images.githubusercontent.com/93376115/155292994-643206c7-b633-407c-8467-cc8755b41ae0.png)

The main idea not to have different layout but rather have additional information on distance of a node from each other. That is why different nodes placed at different distances from each other on such trees.

**Comment by nikolay-alemasov** [comment]
The second point is to be able to load a tree from newick format.

**Comment by jdimmerman** [comment]
@Ovilia This is something my organization would also find super valuable. Any thoughts on pursuing this in echarts?
