### ISSUE TITLE
bar chart display abnormal when setting stack [Bug] 

### ISSUE THREAD

**Issue by zhaoxuhui1122** [apache/echarts#16552]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/admiring-leftpad-h8jcdk?file=/src/App.tsx

### Steps to Reproduce

1. set stack property as `xxx`
2. set xAxis type as time

### Current Behavior

1. yAxis Start position is not zero
2. some data are not display

**The display is normal after switching to version 5.2.2**

![image](https://user-images.githubusercontent.com/23182684/154913553-46c6ad9c-3656-444c-83fe-1440a9a7f922.png)

### Expected Behavior

1. yAxis Start position is zero
2. all data are display

![image](https://user-images.githubusercontent.com/23182684/154913807-64a60bc5-85a3-4ced-acb9-720e0267ffb2.png)

### Environment

```markdown
- OS:Mac OS
- Browser: Chrome
- Framework: React
```

**Comment by pissang** [comment]
You can add `'-'` in the missing data to fix this issue.

```ts

        {
          name: "Union Ads",
          type: "bar",
          stack: "Ad",
          emphasis: {
            focus: "series"
          },
          data: [
            [1645426533000, 1],
            [1645426534000, '-'],
            [1645426535000, 1]
          ]
        },
```

**Comment by zhaoxuhui1122** [comment]
> 

This approach is not suitable for my current scenario, where the data to render is pulled from the log server,

It is impossible to know exactly whether there is data at a certain point in time, so I don't want to conduct too much analysis and processing on the obtained data.

I switched to version 5.2.2 first

use youdao  translation 😄

**Comment by brahma-dev** [comment]
> You can add `'-'` in the missing data to fix this issue.
> 
> ```ts
>         {
>           name: "Union Ads",
>           type: "bar",
>           stack: "Ad",
>           emphasis: {
>             focus: "series"
>           },
>           data: [
>             [1645426533000, 1],
>             [1645426534000, '-'],
>             [1645426535000, 1]
>           ]
>         },
> ```
@pissang 
I have tried that. But it does not work in versions after 5.2.2 [Example](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&version=5.2.2&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5JALZW0kC-ANCeTvkaqWUo1YtAG4BDADYBXZm07o8VAE4QqhWAG0S6fgMHU6AI3HLaC_dHFM6AdXF4wVACbmdpPOQZHgkutBhmCwFPb18AZQgAL2EAFmCPLx9JAHkAMzSlMCJNAAZ2WFyAXQTFAAtgAHdwpN8iMGVZUthJKgBzKmhnAAlgURUAGQhoAGt6xqpmsGBfSBA-WDwKyvHZWA53dGcIJmg8KD2czdIkWCsbEUZ1MGsQcwNheh3mdebdM-tHiRkgh7o0yTAcRgWivY7oegzSRzFj6WAlY7OYHiI5w9CaACMAHYMbkAKwADjxGNiuTJ-REAFp7tBpJJJAi0VpsbjCcSCeSKbRqQVafTGWjMTj8USAEycrk8s50hlvZnCtmi0nkgrcmkygVwoWssUANk5qqlfNl4PlOrxAGYJYb1fy5dqRZbxSqqbaTUyHWyLfqXbEMQA6C0ATixqr9_tJtE1-k9RO9BtdvI19pZjotHJdaqTdtNsbxsWdZIKBIt_stutVJbLsSjKYVRILCaz0pzHtTbNiyqLiZb7sF7YbGe7GItsX9QYrIhHY4ntdzA_zQ8lbujAjzeOtPeNq9I667FIxeN1EaJqsPx9iQbnbfrePzTaNyfnt6PD5XdfNPpduqD49FeNVH9xwta9-1vL9u2bbcP0dXVC2XbM-y1BddQggpcV_XVQynXJMKxUDkPAtCtyfG9PyXG1EJ3dEFyxeD0NiUs8QnM9GP9fUCJjWj6JI1swPNLF90o3tqLNR0sQo2AgwJQNcmw2hpMDDFOLXWjJKg0j-MdJcEJEmC2QJITYAJUV2IJeSTPYq9RLzQy3yo_SiQJYiNL4wjzSDTdcVyCNRVFM8yV8lTdwXTz7L058PJ41ykK428JwTfV2IxDFAJ83VlJs0KXMfNy4o89Tcti1T631HjLMvfyRAq6zHLK8LoMikV9SMmKstK3JJJHPFgPk7rxxrdqdX1Qr3yawkMs3Nq6pJBMSVLLDUqnNisOCmjStmzMiqG5qMRysayOa-CD0PQNYgAqdTotPE1rEibjuExrDvu6Ltrq0ViJHX9cgxAkz2Df1clFW7Yzg_aHPG5zRVGiHnuci0eJJY9cgtPrYmRwa6oRhrNPc5rRxxvKSuG9M5u9QG_P-5HgZ2ibSa2g6tIm_ddKepnnM7BNRQDDEgyq2huf9XmQYHXVOYZ2H2bF8GIrh3UNwTGSg0PSs_xF0qFYl2WpbxV7GbxibXy1tmDecwlCeKkLSrgxXTMJP7qrt2rIdQvXJdN1DWrel3dS63IxwtFWcIDmm6t9i3aecrEpu9uXBMSgMsV1wDE5uyOsK9_X8uarEZZN7OJp0gpmMDMXVRL711eGoveMt9bq7d7WPecrmfNRi1VXFQN8PTlvjdxgvnIJGGm8Hn9G_z4nmqDTP3bH6SI8c6OY6zqfCWjoyfJRh3aC3zHIY3xeD9yPOB7X8zvN9djBLDa-q5FYUj7hnEJ7Pq2dRxYjjwtb1ALO-_157SfuzHEI9J7vwfn5RWZZiSqzvAA8yUD-5EwgevJUwDTZ0S6mOZiO8STsVyAgrBGDB5YitCQ8-ZCjITn9H5IMqoaGihApHKhFDUHmXjMguud1zIs2LKWaOF1aBVhxEQvhtcWGNi4ZIz6v4CzxCnHI0OB90ZsPrg_WIYC37qPXrrBM-ZAwhnLmOSMLC9HSKXveCxB9zYulOudfm9i06WK0SgnR5kIKs20Tw3Os9R6UNQmonxy8XSjgjOjVUYTzpEJCZBWOIC6JBNjFiXOZMFpYnoVOH-ZkYmnzccE1x3DkkmTJmOXUP9_plOYUvEp1jn52TqSA4eZMZLpgUbQEcrSCREOaY0zBYU-mkJnnNJUQs6JnlGdiIhwzBmUISrM9hOkKQcjLJOYRPkjwIKWY9bxsYOSv3yXsk-isxzigsqczKjkOR5KKQODkhTI4EgxDxJOgNOqqleT9LZzykl3M2nE1eizfoJiDAIwODCwXfIeVch6EiYVGWeTJUUGSJlIu6Y89BCz3EmRuY88hdigaA0vAFUy-Itn4oBXPc-JYDm3PrCWWR_pBFnl_KIvFuKrn00pf4xZUjuw-RSUIgV6Krl8q8Ycu54tuXgOxZoxK7F5Z_1Wo8uVWKeFEhXlSxZVjuyC3xJ3AMZLHk6vFXSnURIOWQz7nY0yoKJnAS2Z4nZEr6U2zVXswJLo_IRneSIb1fpHWWrhkPX59LElerHPiIRoyT5bPDdK3Zdz47uqTZJb1uEloC1Jc7YNElQ3mprtNK1DThydSUkI3ErTlHBpLaax51q61XIGd2JKP5M2tpzezAkzbG1Wr5vmkU3av7HhSTvVCTKRV9qDV2heKb6yeR4umdiQil3ywQQugdhJPJ-JlTwzyXVfy60yR0w91TIb7s3d2y-CaXU6mVgiwGFbH3rv-b2uGytp2m37QmARKTIkTvXbCot76kE3rNSKPmxEym-1vsqxykHL182hee7Gc670EzQxBrlB4LzdrPBeTtX7sPOvA1u8RwH2YzyMuGFK7SaOXPPVKt9lHVGYa3ZrYcpZPIdyyeOQhkcgwceY1-8xYGBNG2HN9OCLLAa6nXRJ4Tg9BPIffW67s51ZPHo03JddanFPnwnDuxN87w52KxDAvq5nNkCdM2J-DsT9PsJDEZb1KV5KuerZR5Ndnz2pLY92muMbNGd0jc489hb4lftqT599DaCg-RMjvBLZ7YufqU70mLlHv2Za_TMnLSnZ35bXj2sTxwdydAAMbAGcMIU4GA6BXEcLce45A6DfFkPcaYswIDzEuFCGEYI4RNYq2MEQ4hxCwlIBsAQegBAUEMCIEwZhmjnEeAAYWAAwBg0hoAQAoG4IbtQ_AiACNAIIxxQjJEiDEIg8QLtHfSJkKg2QtAUmKM0JYVQahhGOw0JoxxWgdC6L0foyghijFWJMY4XXoQ9YWJ9lYZAJiDf0NsXY-wYAaG0EyU4q2GvPCawwO4BR5uPCuKCabaJcefDa1IDrJOhD_EBMCCncpITdbuGV5oSIbionZsSIzt7HTAt9AGKjYYxf7zhqJor7DdYudaYqv1rSe6OV1ml8-lpNx3iFn6cuPUSQIKdJe8sJvOEtvM7ifmWEhb8bV8RuFkN8y0sjs7xKSLf4iF9rQqX_OmMkdd6q2X7jFwJmjkLXmHyfLPKN0JgPauTXx6d4n2Arz_zHrT3J13Cmk_S6dY7vPXlcTjiDh04vfMjd6dz_zz1weeFHmIiI5O1UBFhbzyp_n8bHMh67wUXOEZ5L99iKrp33nu_17zf5vEk-W2spnoBOfRuIuApD7W6vptCRGRt19QClvfcb7iwX_nPb1-D2YpuMhZ0M-lmukb7L4-8zzLr4_xvYub7VTf3fjvHsgaXvqi6S_LCa_HJdOf2P_TqcAySJ5IWfmaAmPdOa9B_UWV9U_c-DKIyQSWhcpD5U5LPGaDXdhPTJA0qWFT5HjWgMghBOCF3d6Ag9xMGW2IWH8SsUyKZdOaGP_VDZ_UWLgg8H6MydpXEAMX2KgjDbg0qB3CjD2B3IMQ9JOBhQ9SdOWcjSLMef3I_D2dQgxGeHebQtvKWVjcQ4aOPDQseEw6GWhFKTuJFBjOWGXVAwgnPVPHyZFNZcPaGKg2xIw5qKvUwtA3w15DcNwnqYkKgsWP_WzYg4aSIvvROYeD5ROQjMeBzBw-gsfVInhDOMPUlQkD5UlPAl2PzbwwuTVHlegmuDJcJcgyozsKg6LKI5qQ_KQseQ_So1GfmNokfOWDLBoiae_YuHqbefXIlKgvLXo5yQrCkCSa-D5GSODY-Uo3dZJMA_zQ-F0YkJlZWcuRIohY5VYxAjI5JA42AD6diJUTuY8OCIhH5fYugnxIBK-f8NZXA647_UhUDcYuiHiEMSwneH4vyIhTFYoxBN4yhDgl0ZyasSsY8fMIhClT4sQhEjArjaTEQS_WcFhc3T4lQlfHxcRaAu8IRAkgo5-MVQ4gcQSO45JQwikS0CMIxEQOkjcMRUE9hJOGgmxHiJKQOMdNuTzTBFPZoyhLwz4kUgob3S8eSb3ZklhfPIUtk8I30X8VGOjZUrokBWvT4lIvwtk7UzAjJHeTAjkGJDk5-IorU4iQkH3TNK0pUGJVk9xCSU0ppHiaff0QyXQ8zIkHpQXUjcyHo8k-sCSSSK0pOeSUMkkkBE_HUx0sYwMj-OM2AG3OiIRZMlLKMqku5CUcY7ZJM8zTsY9G3aJR5X_fza5S9csgAhLXCKPd02wrtCAssm44Ep5F5AVUUDPAVdM02J5X0x5EXFsgcikeWd0hGQCHqEsLZIDVQ6lIEnMucgY901E2gHXZyKczM-leE-MwdLc2AUM84xkmSOiclZ0nsrE7c-2c84yaPO8SsaPSMs8h09VMkmM5810mSRicgq0xiLZdQ-U2VJ8vZIPWk5GZco8WTLZEw_89VQUmc7VajczFGLTRC_fQeC1CsuUuC7FfPN0jkcMr0-sns3w6Cj1Dc81TUgobJBGTNKi_ktCmI18vZXvRipNV09Kc6cudKfQns9IlisNQC1Nd3XXa3GSQ3etRY4zAtPsq5NfVPUsPyQ0-S7stCporC9VaMkiu5aM15DKYIs4rZfovi81J_HMky8UnyJDNKB1R5SYi87tUs4EjdAAscbEIRTA36ddFYxyxs7yySRSJ5IRfyuigzY4zS-dFAoyiDCKtiYLEQGKpQyjB4xy6c3E2Me_Yc7NQs1gu3c9D4uyhDfzAq7sN0gsNZEq5SgzcExy3g4sX8Kw6qOqwipTRE_KyQtStKh3dwvXNElw1CgzHErVdxKjRDdQoCH-Qs5UvqpzGk_KqC9qgcQTbXCcrYxk5a-TU8pTJwsKu9JwjKXydpPagseTASkzDagzAIscHEHAplJq866S89Bi7aiDBigsWhf2MMUycUddbUp6rdXi367tXiva32dtYQhKr9c0_K5fQavdGuK0p5Y9eG4KpzeoqGsiiDQ_Ecjir3HqYs-DAMyKrdQy66GBcgkm-BATRMgG2QySUkJSfmOmwOABErOtLnY4SrarWrTAfHJgQnYnWAVrEQdrX4GHOYBrfrHrVnC7G4EbOgcbSbdAVgEgIoFAVgAAbiAA)

Can you please take a look.
