### ISSUE TITLE
[Feature] `yAxis.max/yAxis.min` of DataShadow(mini chart) in `dataZoom.slider`

### ISSUE THREAD

**Issue by Airkro** [apache/echarts#16559]
### What problem does this feature solve?

![1645527584(1)](https://user-images.githubusercontent.com/12206891/155119011-b6c3aeef-52d8-4cc8-bed2-75f79244e454.png)

would be better when `yAxis` has limit

### What does the proposed API look like?

 ```js
dataZoom: [{
    showDataShadow: false
    dataShadow: {
       yAxis: {
          min: 10,
          max: 100
       }
    }
}]
```

**Comment by Ovilia** [comment]
Hi, can you be more specific about why this requirement is needed?

**Comment by Airkro** [comment]
Without limitation, the line chart in the slider will easily look like a `straight line` (when a few points are too big or too small)

![image](https://user-images.githubusercontent.com/12206891/155287989-c7a13a21-8f25-4a26-9c65-7296bca012ed.png)

**Comment by Airkro** [comment]
bump

**Comment by Ovilia** [comment]
It seems to me that by setting the range of y limits, makes it confusing to the big picture.
