### ISSUE TITLE
[Bug] No Config for the lineHeight of  the graphic's text type

### ISSUE THREAD

**Issue by jingping-ye** [apache/echarts#16557]
### Version

5.2.2

### Steps to Reproduce

使用graphic text绘制多行文本，想要换行，找遍文档没有找到相关配置

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
@jingping-ye Sorry for the late reply. Yes, of course!

**Comment by linghaoSu** [comment]
@Ovilia  Hi, I found that the graphic text already supports "overflow" line breaks, but they are not listed in the documentation.


[Here is demo](https://echarts.apache.org/examples/zh/editor.html?c=line-graphic&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqwECGYlJA2gOQCCGkYArgVrABQDWAWwCUsAG4BnWABUsAkFgBO1dgu48ADQGEhDALpkAvgBoyYYMFYQQJVOVhgFEHHgUkGlAB4RxDE3YBmwAoC1GCKbjJyisqqsCQAPABGCgD0AHxIiQaCccgAxgZaDIZ-sDiOxKR22P5gbgDMAKS-ZOiOOAAWdbAMACzNpeiJwGBmAg0DrbB5MDQQ0AAylIlYGCQO7FglZB5MXuI2U2AAnvJuopQYmy12nt5LK2tVdrCBwaHhPUgXV1gGsEUpgZtuhjntvIc7Cczj08tRcEFjjdyHdxAt5lgbLAYAAtRTAEj-S7ibjGKaoh6rSEvN4hUafBjfS6bf6CYp2Ml2YbsQiUBTHADilGs9gUm0GFGotFgjAADL4egBGeVGHoAJhVPXqmr6OoArDqAGw6gDsOoAHPL9OhOWUlCAOhA8vQprYXtDMT1ysB2CBkXYFCNqFBoCQALLUDoAOgACgBJWApWC9CVDH2EeY4NxKADu_vI7S6JEVytTsGGo2A41gJdlZYAXsXZXWpug8o6MARVKGZa3yG6XuQPdmsHkwPnBzVugw8vgwgoJ-7QG5Z9B54u7I2a82y3ZxB1hZ6B4PyDmIAQwB0SL0d33Bx0sE4i7ADXfyLaT7BxCdsNTP-h_AgDAngYBQcESSgeDraCjFlKN6h0N8bTfD8XmPQdhx6MIPHHXdyCnFc50UDch2XWEiIXPD0C3ZUW3_L8fyPJDyEA4C3AAYn8LiSKhLAcLcABRTQAAkmAAJSkABlWAFjjAA5ATYBE8SpB4ljZjcYZO1gNVDRADwv0oaBxAAWhJRx_HZf9gU_GyXmtd8JXQ-xTk9BhvV9RcCKVWVJgwsiZwoxd2yArt8BdT9nKhVyRzHNSaNvejvMCtdiKo-wAoEc8CGwNT90PP9_zPC8rx0m90vQB8n26ABOWVmNQwdv2OX9nno1iQM47iKoYwM-Dc9i9SGtT0AwDEAHVz0vYsevyghgBzAAhK5XFgc1ZoPeacwAeS4kkwAADRIeoNsoLbdv8faAE1jtOrbNAsIJs3AyCYOgqM1UQ-i7MHRr-2YzCGGw3DmISuj_2S1d13SswRQYLKCByrA1OBh7oEArM2ohyhjh9MAxNHboopPYrpu3cHvoa9Lmta4mAiAzr6iZkbYFJ0qNQp_8qs6bpaJ64BREUfwMAWtwNmgOEwhZ1YxpAcQIR6KMlZSFWWeBtxdn2WBVBAVQSTXcQdb1udDawXWsH1sBTfNy3reNg2jYtk3Hdtl3nbN-2rbdh2Padn2bZN-xZHkJQOFieYAU0VUwS172rdgS42E4bgI8EVUmDgCAQjwVn4XeBQ-FgCPL24X0Q-16rVSkR1JGB8sRbyQu4TgFZYBADBKFnAgi7gIzjjbjvZxZwI1zcRVen02AwydQNxGAWpYCuyhhMfFoGpQvsHJtJy-0Bjy_TLZKbz8pc4ahtK-xCztuwik86ZcmFQMJ-Km05ycsFqQjUsogHMuy3LqYHhhPfdAbMSBqnKsxSqj4eYkDqlTZiNMmL0QAgzDiXFLKzQcMAfqHEhp6hZmNaAWBJolRmlAr8m0FrLRUCQdaFC5oLQuvtI6sAToMKoTtPaWAwA3TYXdBaD0RarVAi9KCsEJFwU-lZWyKE8L30BsDF-5N0qQyCjDP-iMAEAz4mANGGNCqfg7rjdg-NCaGKKlNUqfMKE_RPH9PcjELGDg6hxJm9QWZgJ0olFB3Nnw2JQdiQWChhaix6MkLAlA-Bq10RrcEkg452z9l7X2rtUnuwDv7T2SS0mZJSXknJGTsmJKDlEUOKgU5wC0NHeJ2t0kGwTpYDgXAe6wDTrADORds7cBzHnEIBdWkl1gGXRQFceZVxrkHHC9dgCN2mEZcs3B26dywN3COfcB4rOHhpJUE8DLTzyLPeeYBF7L1XiYdesjBxb1gKhZye9AyeUPh_acZoT5QgCufH-g4r5hR7HQN8CiYo9FUHFdKYNVEvK_tDX-cMEZIzykA5BKCvEQLfiePxtV6rfWpk4rGn5XE9C6pghh2DcFEvwYQiaVjyGBMYUtFadCBFcMujw1h7C6WcOYTwvhHKUH0qEU9EFYi3qwQ-l9aycjAUA2BUDXRyiAkQyheRb-KNNEIphro_RThnEvGMXjAmY5dWDi8YqymOLEF4pAa8NBRL3GeJpd49F94YH-J8fRAWQsRY5k0qoKJLAMAxP4j0TW3g6kFMSZG-p-TinRsKVk5J8aY2JqjQU0pIcYiVMjjU2OcbGlJxaanAQ6dM7dNzvOfphdi4PmGSAcuhYwATLDXXRIDcm4LNbssrurSNlduRj1Ee05x6TwOUcheS8V4QDXua-xm8gRkF0KUcyEALa33QM5aAlABBuUABtZgAyvX4MIQAcHKABQbQAlHYaG0IADeVABoyoAZ0VADfPouQGRD-19nEAIcwZMNhYDLFQGg9BFR6lVCZA0IG9SGijMB2AJleiQegyZNUaooyKhA8hhDaoTRRhNOBvU2GQMmngzcuy-gDAAG4gA)

I add documentation for these attributes [here](https://github.com/apache/echarts-doc/pull/342)
