### ISSUE TITLE
Series Tooltip[Bug] 

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16556]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/Harshitha19/pen/podLqax

### Steps to Reproduce

```js
var container = document.getElementById('main');
var chart = echarts.init(container);
chart.setOption({
  xAxis: {
    data: ['A', 'B', 'C']
  },
  yAxis: {
    
  },
  series: [{
    type: 'bar',
    data: [120, 200, 150],
    tooltip:{
        trigger:'item',
        formatter:(params)=>{return 'hello'},
      }
  }]
});
```

### Current Behavior

Tooltip is not triggering when it is set at the series level

### Expected Behavior

Tooltip should be triggered when it is set at the series level.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
You should first enable the tooltip globally, the `tooltip` option defined in series is only for customizing for specific series.

```js
option = {
  // ...
  tooltip: {},
  series: [
    // ...
  ]
};

```
