### ISSUE TITLE
自定义时间轴时间细粒度[Feature] 

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#16563]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/27613553/155275464-d25af1a0-eec7-4323-bff3-eda773aa0a2a.png)
格式化时间样式后，时间间隔较小时纵坐标值重复的问题

### What does the proposed API look like?

interval: 'day' | 'month' | 'year'

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter 「分级模板」看一下能不能解决这个问题

**Comment by ZXYT** [comment]
![image](https://user-images.githubusercontent.com/27613553/155440505-51da164a-30cc-4a1a-8617-230ece93f5c7.png)
谢谢羡辙姐！
勉强可以解决，但是还是会有刻度线
对了，羡辙姐去年怎么没有写年度总结了，我还等着学习呢🤣
