### ISSUE TITLE
Any way to Download options(Preview options) of any example [Feature] 

### ISSUE THREAD

**Issue by nani554** [apache/echarts#16560]
### What problem does this feature solve?

I would like to download options(Options Preview), any way to download these options as of now? 
![image](https://user-images.githubusercontent.com/22760241/155122257-437f9be6-2fca-48b8-907d-ad595e2695b1.png)

Steps to Reproduce:

1) Go to eCharts site: https://echarts.apache.org/examples/en/index.html
2) Choose any chart
3) Enable dark mode and go to preview options
4) I want to download options, please suggest me how to do that.

Thank you

### What does the proposed API look like?

Please provide a way to download "Options Preview" options

**Comment by Ovilia** [comment]
Hi, the source code is available at https://github.com/apache/echarts-examples/tree/gh-pages/public/examples/ts
