### ISSUE TITLE
[Feature] lengend formatter support value

### ISSUE THREAD

**Issue by showmethecode9527** [apache/echarts#16567]
### What problem does this feature solve?

当前 `legend` 的 `formatter` 只支持图例名称 `name` 参数，不支持 `value`

`legend.formatter` params only support `name`, not support `value`

[legend.formatter](https://echarts.apache.org/zh/option.html#legend.formatter)

### What does the proposed API look like?

```js
// 使用字符串模板，模板变量为图例名称 {name}
formatter: 'Legend {name}: {value}'
// 使用回调函数
formatter: function (name, value) {
    return 'Legend ' + name + ':' + value;
}
```

**Comment by Ling310** [comment]
同样有这样的需求，希望legend可以拿到对应行的值，类似pie.label的formatter。以实现饼图在显示区域不够宽时，可以借助通过legend代替label进行更复杂的表达。

**Comment by MarvinSt** [comment]
would like to see this as well!

**Comment by HolleKitty** [comment]
lengend  不支持 色块 和 文字 反转位置， 不支持 按 线性样式 等其他元素标示吗？
