### ISSUE TITLE
[Feature]  在柱状图柱之间的自定义元素

### ISSUE THREAD

**Issue by WeiShengv99** [apache/echarts#16562]
### What problem does this feature solve?

<img width="446" alt="image" src="https://user-images.githubusercontent.com/35689628/155272446-4443ad55-c3fd-4baf-bc56-85513ed4e666.png">

遇到了上图的需求，找不到相关的样例，在 g2 里 ，有conversionTag 的api 可以很方便的实现这个功能。

### What does the proposed API look like?

类似g2

```
conversionTag: {
    offset: 0,
    spacing: 8,
    arrow: {
      style: {
        fill: '#efefef',
      },
    },
  }
```

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#graphic.elements 可以绘制图形和文字，位置需要自己计算一下，比如记录下 grid.left、柱状图宽度等信息

**Comment by WeiShengv99** [comment]
> https://echarts.apache.org/zh/option.html#graphic.elements 可以绘制图形和文字，位置需要自己计算一下，比如记录下 grid.left、柱状图宽度等信息

@Ovilia 

是的，比较麻烦的地方在于柱的数量不固定的情况下，去计算位置信息是一件繁杂的事情。如果可以话希望可以提供更加方便的方式去完成类似的需求。
