### ISSUE TITLE
[Bug] 无法加载官网

### ISSUE THREAD

**Issue by xqm5260** [apache/echarts#16568]
### Version

5.3

### Link to Minimal Reproduction

无法正常加载官网

### Steps to Reproduce

无法正常加载官网，左侧按钮都不能点击
我用手机流量，公司网络、家里网络、还有几个同事的都无法加载。。我们都在天津市  是地区的事？
![image](https://user-images.githubusercontent.com/35522457/155315945-2491bb38-ab19-45c4-8471-239172872589.png)
![image](https://user-images.githubusercontent.com/35522457/155316058-2f07c1cb-455f-43d5-a44b-dfcb4f448eda.png)

### Current Behavior

无法正常加载官网

### Expected Behavior

能正常加载官网

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xqm5260** [comment]
api也无法加载。
![1645618190](https://user-images.githubusercontent.com/35522457/155316928-72b269a9-7bd1-455e-8acd-20a24ae630e8.jpg)

**Comment by xqm5260** [comment]
麻烦 看一下 这是什么原因  我需要查看api 调试整图表

**Comment by plainheart** [comment]
看看能否正常访问 jsdelivr CDN？
