### ISSUE TITLE
[Bug] getDataURL doesn't render the chart, only the axes

### ISSUE THREAD

**Issue by tmd-set** [apache/echarts#16564]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/tmd-set/pen/zYPaExV

### Steps to Reproduce

1. I create the chart in codepen and use getDataURL to get base64 image of it to be shown in an img tag, but only the axes are shown, the main chart is missing and not rendered in the image. https://codepen.io/tmd-set/pen/zYPaExV

### Current Behavior

Only the axes are shown, the main chart is missing and not rendered in the image. https://codepen.io/tmd-set/pen/zYPaExV

### Expected Behavior

Everything in the canvas should be rendered in the base64 image.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Animation is enabled by default. You need to wait until the animation ends before getting the data URL, or you can disable the animation via `animation: false`.
