### ISSUE TITLE
[Bug] some events are not triggered as expected with new SVG renderer

### ISSUE THREAD

**Issue by sakiraykurt** [apache/echarts#16579]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/nervous-lake-y3j0r9-ssr-issue-y3j0r9

### Steps to Reproduce

1. Try to initialize new SVG renderer in NodeJS app.

### Current Behavior

'rendered' and 'finished' events are not triggered.

### Expected Behavior

'rendered' and 'finished' events to be triggered.

### Any additional comments?

It is working well with `Canvas` but not with new `SVG`.
The app is only hanging and not finishing after `setOption()` function called.

**Comment by JinJianQi** [comment]
@sakiraykurt hi~
Through the offical docs, the `renderToSVGString` API should be called. And this function will return string, the SVG string.
```js
const str = barChart.renderToSVGString();
```
And there may be no desire that need those listeners in server side, cause there is no other thing but only rendering.

**Comment by sakiraykurt** [comment]
Hi,
I was expecting the events are to be triggered. Yes, I see how it is working with SVG render. I leave some code here for people and close the issue thanks.
```
const echarts = require("echarts");
const myChart = echarts.init(null, null, { renderer: "svg", ssr: true, width: 500, height: 500});
const option = {};
myChart.setOption(option);
const svgString = myChart.renderToSVGString();
myChart.dispose();
```
