### ISSUE TITLE
tree类型下edgeShape: 'polyline'时，节点收起部分线条会保留在画布。[Bug] 

### ISSUE THREAD

**Issue by liyibing-1028** [apache/echarts#16578]
### Version

5.3.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/56507028/155510029-d064f88a-f9f8-4872-9eab-cb7ff389ac9b.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/56507028/155509799-3cbe1b1e-05ea-4aed-be64-75c13bd577de.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/56507028/155509855-32c50901-7e87-4182-82e8-cd58bb2a2ec5.png)

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Framework: react
```

**Comment by susiwen8** [comment]
Duplicate with #16566
