### ISSUE TITLE
[Bug] The pie label didn't show when the radius wasn't enough long.

### ISSUE THREAD

**Issue by zemelLeong** [apache/echarts#16573]
### Version

5.3.0

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-pie-label-not-show-41l4z?file=/src/option.js:70-84

### Steps to Reproduce

See the CodeSandBox link

### Current Behavior

![image](https://user-images.githubusercontent.com/26835087/155464517-0641b07b-db58-40a2-b03f-46d3d2a85798.png)
![image](https://user-images.githubusercontent.com/26835087/155464597-1aab784e-b9a8-42df-b862-10159a296e37.png)
The pie label didn't show when the text is `这是一60.00%，已完成300亿`. 

### Expected Behavior

No matter what the text is, it should be displayed normally.

### Environment

```markdown
- OS: windows 11
- Browser: chrome
- Framework: React
```

**Comment by jttry** [comment]
I'm interested in fixing this issue.

**Comment by zemelLeong** [comment]
Thanks. It's ok to reduce the width.
![image](https://user-images.githubusercontent.com/26835087/155723204-17e984d3-6b7b-4b04-881c-502d233063d7.png)
