### ISSUE TITLE
[Feature] tooltip内容太长, 导致部分内容展示不全

### ISSUE THREAD

**Issue by a15218378694** [apache/echarts#16588]
### What problem does this feature solve?

tooltip可以展示所有内容, 现在问题是, tooltip展示的边不对, 已经设置了appendBody

### What does the proposed API look like?

希望tooltip展示的方向可以计算正确, 比如左边空间大,  就展示左边, 反之右边

**Comment by a15218378694** [comment]
> ### What problem does this feature solve?
> tooltip可以展示所有内容, 现在问题是, tooltip展示的边不对, 已经设置了appendBody, 但这个会引发很多bug, 暂时关闭了
> 
> ### What does the proposed API look like?
> 希望tooltip展示的方向可以计算正确, 比如左边空间大, 就展示左边, 反之右边

**Comment by plainheart** [comment]
设置下 [tooltip.confine](https://echarts.apache.org/zh/option.html#tooltip.confine) 将 tooltip 限制在图表范围内。

**Comment by a15218378694** [comment]
> 

谢谢, 下次看, 目前自定义样式解决了, 文本换行
