### ISSUE TITLE
[Bug] When the number of points is more than 5000, zlevel and tooltip axispointer will cause the chart to render only partially

### ISSUE THREAD

**Issue by xiaofenging** [apache/echarts#16581]
### Version

4.9.0

### Steps to Reproduce

1. The number of guarantee points is more than 5000
2. Set zlevel in series to 1 (other levels are not tested)
3. Set tooltip in option just like:
 tooltip: {
  trigger: "item",
  axisPointer: {
    type: "cross",
  },
}

### Current Behavior

When the mouse moves in or out of canvas，About half of all points do not show that the point x is larger than 1/2 X axis 

### Expected Behavior

All points are displayed

### Environment

```markdown
- OS:Windows 10 企业版 21H2
- Browser: Google Chrome 98.0.4758.102 64byte
- Framework: pure html
```

**Comment by liwenda122** [comment]
GOOD

**Comment by plainheart** [comment]
It may be related to [`progressiveThreshold`](https://echarts.apache.org/option.html#series-scatter.progressiveThreshold).
