### ISSUE TITLE
[Feature] 如何复制tooltip里面的内容

### ISSUE THREAD

**Issue by a15218378694** [apache/echarts#16587]
### What problem does this feature solve?

tooltip展示的时候, 鼠标可以放进去, 长按拖动选中文字, ctrl + c可复制

### What does the proposed API look like?

tooltip在加上enterable之后, 希望可以选中文字复制

**Comment by pissang** [comment]
@a15218378694 图表容器设置了 `user-select: none` 的样式，你可以覆盖掉这个样式

**Comment by a15218378694** [comment]
> 

感谢
