### ISSUE TITLE
[Feature] 折线图如何增加重点提示，点击可查看详情URL内容

### ISSUE THREAD

**Issue by kemistep** [apache/echarts#16590]
### What problem does this feature solve?

类似于这种：
展示
![image](https://user-images.githubusercontent.com/16223610/155947172-a7b423ed-634c-42d1-9bd0-0facfb2e27cb.png)
点击后
![image](https://user-images.githubusercontent.com/16223610/155947237-38af63be-58d1-4e1f-964c-3d950e2d9163.png)

来源地址：
[算数指数-巨量算数](https://trendinsight.oceanengine.com/arithmetic-index/analysis?keyword=%E7%BE%8E%E5%9B%BD )

在echart的折线图未找到这种示例，实力有限，求大佬支持

### What does the proposed API look like?

pass

**Comment by plainheart** [comment]
尝试[监听图标元素点击事件](https://echarts.apache.org/api.html#events)，动态设置 tooltip 内容。

**Comment by kemistep** [comment]
> 

ths
