### ISSUE TITLE
click 事件在移动端不生效 3.x版本还可以 4.x以后就出现这个问题了[Bug] 

### ISSUE THREAD

**Issue by zcg8633** [apache/echarts#16598]
### Version

5.2

### Steps to Reproduce

[my-project.zip](https://github.com/apache/echarts/files/8161808/my-project.zip)

### Current Behavior

click事件在pc上运行有效，在移动端（手机、平板）都不行

### Expected Behavior

移动端点击图片，响应click事件

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zcg8633** [comment]
已解决

**Comment by Leomemory** [comment]
麻烦问下最后这个是怎么解决的呢？最后用了哪个版本的echarts呢？多谢

**Comment by zcg8633** [comment]
> 麻烦问下最后这个是怎么解决的呢？最后用了哪个版本的echarts呢？多谢

我当时是用的uniapp，有个全局的变量wx有问题

https://ask.dcloud.net.cn/question/88473

可以看看，希望对你有帮助
