### ISSUE TITLE
Custom Tooltip for Radar Chart[Feature] 

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16595]
### What problem does this feature solve?

Hi, 

We have a requirement of showing tooltips for the radar chart. The tooltip should consist of the data value and the corresponding indicator.
https://echarts.apache.org/examples/en/editor.html?c=radar 
![image](https://user-images.githubusercontent.com/97500674/156005032-703c97e5-cd2a-4df2-b01a-b82aa67b28e3.png)

### What does the proposed API look like?

Some information in tooltip callback params using which we can construct the tooltip display labels in the following way
indicaterName: dataValue

**Comment by ZeekoZhu** [comment]
@MNHarshitha you can use the `tooltip` option, it works with radar charts.

https://echarts.apache.org/en/option.html#tooltip

**Comment by nlpsl202** [comment]
how to show only one point's tooltip that close to mouse?
It always show every point, I just want show one that my mouse close to

**Comment by MNHarshitha** [comment]
> @MNHarshitha you can use the `tooltip` option, it works with radar charts.
> 
> https://echarts.apache.org/en/option.html#tooltip

![image](https://user-images.githubusercontent.com/97500674/182539729-20c03e9b-aa28-498c-a3b7-53044be39b3c.png)
We are able to display the tooltip using the tooltip option, but we need to modify the content of the tooltip.
With reference to the above screenshot, if we are hovering on the data point of the market, we only want to display the market-related info in the tooltip.
But nowhere in the formatter callback params, we are able to identify the exact data point on which the user hovered.
https://codepen.io/Harshitha19/pen/eYMVXqo
Please let us know the way to achieve the mentioned functionality.

**Comment by ZeekoZhu** [comment]
Maybe this issue is related to https://github.com/apache/echarts/issues/10537#issuecomment-608339356

**Comment by MNHarshitha** [comment]
> Maybe this issue is related to [#10537 (comment)](https://github.com/apache/echarts/issues/10537#issuecomment-608339356)

According to my understanding in the above ticket 10537, axisPointer option is being requested. We are trying to configure the tooltip on the item. To be more precise, when tooltip is configured for line series with the trigger on item, info related to only that data point is being displayed.
![image](https://user-images.githubusercontent.com/97500674/182565313-bd9229c5-4109-4ef5-a037-40c0eaf65b8b.png)
When we try to configure the same i.e tooltip with the trigger on item in case of radar chart, info related to all the data points is being displayed in the tooltip.
![image](https://user-images.githubusercontent.com/97500674/182565893-6396f0a7-092e-4903-8002-a2e36c42b5e8.png)
We are requesting a similar behavior as that of the line chart.
Please let me know if it is not clear.

**Comment by AnthonyTannous** [comment]
any updates?

**Comment by AnthonyTannous** [comment]
I made this solution to show the hovered indicator alone using costumed JS functions for radar echarts 

1) Create two global variables :
   var globalIndicators = new Array()
  var globalIndexId;

2)  initialize your chart with SVGs 
     var echartBar = echarts.init(document.getElementById('RadarChart'),{ renderer: 'svg' });

3) save your indices in the global variable 
   globalIndicators = indices;

4) add this two functions to your page 

function setIndicatorEvent() {
    var tags = $('#RadarChart path[transform]')
    for (var i = 0; i < tags.length; i++) {
        if (tags[i].attributes?.transform.value.includes("matrix"))
            tags[i].addEventListener('mouseover', (event) => customEvent(event));
    }
}

function customEvent(event) {
    var tags = $('#RadarChart path[transform]')
    for (var i = 0; i < tags.length; i++) {
        if (tags[i] == event.currentTarget)
            globalIndexId = i
    }
}


5) Inside your formatter add:

    var options = {
                tooltip: {
                    formatter: (params) => {
                        if (globalndexId === undefined)
                            return
                        var value = params.value[globalIndexId]
                        return params.marker + " " + globalISPARIndicators[globalIndexId].text + " " + (Number.isInteger(value) ? 
                    value : parseFloat(value).toFixed(2))
                    }
                },

6) Init this funtion setIndicatorEvent() after rendering the chart:

          options && echartBar.setOption(options, true);
            echartBar.hideLoading()
            setIndicatorEvent()

7) try it

**Comment by AnthonyTannous** [comment]
I made this solution to show the hovered indicator alone using costumed JS functions for radar echarts

1) Create two global variables :
var globalIndicators = new Array()
var globalIndexId;

2) initialize your chart with SVGs
var echartBar = echarts.init(document.getElementById('RadarChart'),{ renderer: 'svg' });

3) save your indices in the global variable
globalIndicators = indices;

4) add this two functions to your page

function setIndicatorEvent() {
var tags = $('#RadarChart path[transform]')
for (var i = 0; i < tags.length; i++) {
if (tags[i].attributes?.transform.value.includes("matrix"))
tags[i].addEventListener('mouseover', (event) => customEvent(event));
}
}

function customEvent(event) {
var tags = $('#RadarChart path[transform]')
for (var i = 0; i < tags.length; i++) {
if (tags[i] == event.currentTarget)
globalIndexId = i
}
}

5) Inside your formatter add:

var options = {
tooltip: {
formatter: (params) => {
if (globalndexId === undefined)
return
var value = params.value[globalIndexId]
return params.marker + " " + globalIndicators [globalIndexId].text + " " + (Number.isInteger(value) ?
value : parseFloat(value).toFixed(2))
}
},

6) Init this funtion setIndicatorEvent() after rendering the chart:

   options && echartBar.setOption(options, true);
     echartBar.hideLoading()
     setIndicatorEvent()
7) try it

**Comment by sedatbasar** [comment]
Having same issue would be good to have this
