### ISSUE TITLE
markPoint doesn't show sometimes

### ISSUE THREAD

**Issue by rogeliotg** [apache/echarts#16591]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/rogelio-trivi-o-gonz-lez/pen/WNXaOVB

### Steps to Reproduce

depending on params, sometime draw markPoint and sometimes don't. One example of each on codepen

### Current Behavior

markpoint draw sometimes

### Expected Behavior

markpoint draw always

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by JinJianQi** [comment]
@rogeliotg I created a PR. Can this solve your problem~?
