### ISSUE TITLE
[Bug] visualMap.dimension should work with dimension name and not just the dimension number

### ISSUE THREAD

**Issue by ceng-p** [apache/echarts#16594]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/98christianp/pen/GROYQbr

### Steps to Reproduce

![Screenshot 2022-02-28 at 14 23 57](https://user-images.githubusercontent.com/27136738/155990668-be303b29-12f5-4877-81dd-5aaa6a6966b5.png)

Use a string type in visualMap.dimension: check [code pen](https://codepen.io/98christianp/pen/GROYQbr) for a workinge example.

### Current Behavior

The visualMap.continous.dimension property does not allow string type, so I have to pass the number of the dimension of the dataset instead of passing the column name. The docs says string is the correct type.

### Expected Behavior

I expect to be able to pass dimension name of the dataset instead of passing the dimension number.

**Comment by jttry** [comment]
set `dimension: 'Sales' `
not `dimension: 'Sale' `

**Comment by PrzemoRevolve** [comment]
I am also experiencing this issue (Typescript complains about the `dimension` type mismatch)
