### ISSUE TITLE
[Feature] Display value in sankey chart

### ISSUE THREAD

**Issue by abinhho** [apache/echarts#16600]
### What problem does this feature solve?

I saw Goodle Sankey chart can display value in chart, I tried to find a way to display it but could not find any solution. Do you have any suggestions?

http://jsfiddle.net/zv1y0oa2/5/

![Screenshot 2022-03-01 at 23 06 23](https://user-images.githubusercontent.com/9253378/156204829-f0ad38a3-bee0-4b3b-a258-fe1f4f5222e2.png)

### What does the proposed API look like?

http://jsfiddle.net/zv1y0oa2/5/

**Comment by BigFace123** [comment]
同求，我们做的时候User也会有这个需求

**Comment by pissang** [comment]
Try using [label.formatter](https://echarts.apache.org/zh/option.html#series-sankey.label.formatter)

**Comment by BigFace123** [comment]
It’s means that’s no way to show link value on lines directly?
