### ISSUE TITLE
[Feature] 仪表盘标签是否能够支持文字环绕，效果如图？

### ISSUE THREAD

**Issue by yinminhe** [apache/echarts#16603]
### What problem does this feature solve?

ui效果图
![image](https://user-images.githubusercontent.com/37259849/156278188-09faeacd-6f37-4d44-b50f-427c8c7f51b0.png)
目前echarts配置的效果
![Uploading image.png…]()

### What does the proposed API look like?

ui效果图
![image](https://user-images.githubusercontent.com/37259849/156278188-09faeacd-6f37-4d44-b50f-427c8c7f51b0.png)
目前echarts配置的效果
![Uploading image.png…]()

**Comment by plainheart** [comment]
现在应该还不支持轴标签旋转。
