### ISSUE TITLE
Click Event On Series Label[Feature] 

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16609]
### What problem does this feature solve?

Hi,
We have a requirement where we need to trigger a click event on the series labels.

![image](https://user-images.githubusercontent.com/97500674/156339111-008ccbcf-60e8-4dbf-b61f-77353bf5fb02.png)

we tried using the below code:

myChart.on('click','series.label', callback);

But this doesn't seem to work.

sample: https://codepen.io/pen/ 

Please let us know how we can trigger a click event on the series labels.

### What does the proposed API look like?

Similar to the series click event, we are looking for a way to trigger a click event on the series labels.a

**Comment by plainheart** [comment]
```js
myChart.on('click', e => {
  if (e.componentType === 'series') {
    const target = e.event.target;
    if(target.type === 'tspan') {
      console.log('label', target.style.text, 'was clicked', e)
    }
  }
})
```

**Comment by xiaochuan1719** [comment]
Yeah! I have the same needs ... but, I can‘t achieve ...
