### ISSUE TITLE
[Bug] CSP

### ISSUE THREAD

**Issue by QimatLuo** [apache/echarts#16610]
### Version

5.3.0

### Steps to Reproduce

Update CSP header to not use unsafe-inline.

### Current Behavior

![image](https://user-images.githubusercontent.com/9548054/156341706-401a3a0f-4990-4da1-95b3-d9bf7bf2f7fa.png)

### Expected Behavior

No CSP error.

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: Vue@2
```

### Any additional comments?

Vuetify supports https://vuetifyjs.com/en/features/theme/#csp-nonce
Not sure it works for ECharts.

**Comment by HK-Zhang** [comment]
looking for solution for the same issue.

**Comment by alexisreis** [comment]
Same issue here...

**Comment by work933k** [comment]
Same here

**Comment by alxnddr** [comment]
We are also having this issue and unfortunately we are unable to use `unsafe-inline`

**Comment by work933k** [comment]
The issue is that the "marker" is implemented using inline styling. I implemented a workaround by creating the marker myself in the formatter:
```
formatter: (param: any[]) => {
        const { axisValue } = param[0] || [];

        param.forEach(({ seriesName, value, color }) => {
          // create CSP compliant marker
          const marker = `<span class="marker" data-color="${color}"></span>`;
          tooltip += `${marker} ${seriesName}: ${value}%<br />`;
        });

        return tooltip;
      },
```
And also the colors need to be implemented scss-part:
```
::ng-deep {
  .marker {
    display: inline-block;
    margin-right: 4px;
    border-radius: 10px;
    width: 10px;
    height: 10px;

    &[data-color='#F0CF84'] {
      background-color: #f0cf84;
    }

    &[data-color='#B66728'] {
      background-color: #b66728;
    }
```

**Comment by undeletable** [comment]
Still an issue. Are there any plans to address this?
