### ISSUE TITLE
[Bug] 'restore' button doesn't restore last updated data

### ISSUE THREAD

**Issue by loadingwyn** [apache/echarts#16617]
### Version

5.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2

### Steps to Reproduce

1. Use the official demo
2. Add toolbox config
3. Click 'restore' button

### Current Behavior

In the demo, the real-time curve will be reset totally. All new loaded data are gone and start from 'April' again.  Then when a new data point arrives, the curve will get a flash and show all previous loaded data.
I think is is because the chart  is reset to the initial state instead of the last updated state. It is different from ECharts v4. I think the previous behavior makes more sense.

### Expected Behavior

Restore to last updated state

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Similar with #1560

**Comment by lindaifu** [comment]
参考一下这个，应该可以解决：
[https://github.com/apache/echarts/issues/15608#issuecomment-1186680351](https://github.com/apache/echarts/issues/15608#issuecomment-1186680351)
