### ISSUE TITLE
Receive mouseover event on crossing the line of a line-chart

### ISSUE THREAD

**Issue by klausb** [apache/echarts#16629]
### What problem does this feature solve?

Trying to get a mouse hover event on a line chart using 
chart.on('mouseover', {dataType: 'edge'}, params => { ... });
but did not work.

Taking away the dataType option gives events only when hovering over the data points (small circles).
On the other hand emphasis reacts on hovering over the lines.
Actually I need an event, if emphasis kicks in.

### What does the proposed API look like?

Accept 'line' or 'edge' in line charts for mouseover event handler

**Comment by susiwen8** [comment]
Since 5.2.2, we support this feature, you need to enable [triggerLineEvent](https://echarts.apache.org/en/option.html#series-line.triggerLineEvent)
