### ISSUE TITLE
[Feature] map 'select.itemStyle' color areacolor also need support 'inherit'

### ISSUE THREAD

**Issue by coader** [apache/echarts#16620]
### What problem does this feature solve?

areacolor as normal because it use visualMap color set

### What does the proposed API look like?

itemStyle.areaColor='inherit'

**Comment by coader** [comment]
just like https://github.com/apache/echarts/pull/15172

**Comment by pissang** [comment]
Set `select.itemStyle.areaColor` to `null` should work

**Comment by coader** [comment]
not work, it still use the middle color of visual map to show selected area

before select
![image](https://user-images.githubusercontent.com/3700498/158287860-e74c67bd-21a0-4ff6-b70a-847400b72c43.png)
after select
![image](https://user-images.githubusercontent.com/3700498/158287877-49c028ea-4f54-4ff6-af3f-b4862a47cfc4.png)

![image](https://user-images.githubusercontent.com/3700498/158287899-dec1a800-be61-44af-9c9d-fbd6521747e9.png)

configuartion
![image](https://user-images.githubusercontent.com/3700498/158287923-b5dc4b6f-7427-4aea-8701-a66d0762bd76.png)

**Comment by pissang** [comment]
Set `select.itemStyle.color` to `null` seems work.

**Comment by coader** [comment]
tks, it works
