### ISSUE TITLE
[Bug] realtimesort bar always move label although their order is  not changed

### ISSUE THREAD

**Issue by coader** [apache/echarts#16622]
### Version

5.3

### Steps to Reproduce

https://user-images.githubusercontent.com/3700498/156586562-1b9fb695-a1f9-4ff2-9e8a-1505b816cdbb.mp4

### Current Behavior

label always move even not change order

### Expected Behavior

do not move if orders not changed

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by coader** [comment]
not sure if this issue is related to current: https://github.com/apache/echarts/pull/13817
but I use the latest vue echarts version and still has problem

**Comment by pissang** [comment]
The video seems to be broken

**Comment by coader** [comment]
> The video seems to be broken

please download to play this video, I don't know why it's not works in page

**Comment by pissang** [comment]
@coader Do you mind providing a reproducible demo?
