### ISSUE TITLE
[Bug] option正确配置，控制台出现黄色警告提示

### ISSUE THREAD

**Issue by jmeichen** [apache/echarts#16639]
### Version

5.2.2

### Steps to Reproduce

1. 打开案例 https://echarts.apache.org/examples/zh/editor.html?c=area-stack
2. 将里面的option替换下（我只替换了xAxis.data,series[0].data,series[1].data,series[2].data这几个数据），重新跑下
3. 鼠标经过图表控件
option 见 [chart.js](https://cjl-img.oss-cn-beijing.aliyuncs.com/txt/chart.js)

### Current Behavior

控制台会出现黄色警告。见![https://cjl-img.oss-cn-beijing.aliyuncs.com/img/mmexport1646646423866.png](https://cjl-img.oss-cn-beijing.aliyuncs.com/img/mmexport1646646423866.png)

### Expected Behavior

不要出现黄色警告

### Environment

```markdown
window10
chrome  98.0.4758.102（正式版本） （64 位）
framework angular@12
```

### Any additional comments?

打开控制台  刷新页面  把option拷贝进去  然后鼠标经过echarts 就会重新

**Comment by jmeichen** [comment]
- 你好，替换的option  在   https://cjl-img.oss-cn-beijing.aliyuncs.com/txt/chart.js   这个文件里

**Comment by jmeichen** [comment]
> 
你好，替换的option 在 https://cjl-img.oss-cn-beijing.aliyuncs.com/txt/chart.js 这个文件里

**Comment by Ovilia** [comment]
数据太多了，请提供一个能复现问题的最小代码

**Comment by jmeichen** [comment]
> 数据太多了，请提供一个能复现问题的最小代码

我想知道是不是因为数据多导致控制台警告出现。如果数据量少，控制台没有出现警告
