### ISSUE TITLE
[Bug] 文档中 globe 地球找不到 atmosphere 的配置描述

### ISSUE THREAD

**Issue by candy-Tong** [apache/echarts#16633]
### Version

latest

### Link to Minimal Reproduction

https://echarts.apache.org/zh/option-gl.html#globe

### Steps to Reproduce

1. 该例子有大气层相关的配置：https://echarts.apache.org/examples/zh/editor.html?c=globe-atmosphere&gl=1
2. 但是在 https://echarts.apache.org/zh/option-gl.html#globe 找不到

### Current Behavior

~

### Expected Behavior

~

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
配置项参考 https://github.com/ecomfe/echarts-gl/blob/master/src/component/globe/GlobeModel.js#L121
