### ISSUE TITLE
[Feature] filtering an array of series by type should return the right TypeScript Type

### ISSUE THREAD

**Issue by Joaveinz** [apache/echarts#16630]
### Version

5.2.2

### Steps to Reproduce

1. Have an option with multiple series
2. filter the option series by type

### Current Behavior

I want to toggle the "smooth" property of my chart series.

Currently, I have to use this if statement:

inside the foreach statement, set is of type `SeriesOption$1`
Inside the if statement, set is of type `LineSeriesOption$1`

```
option.value.series.forEach((set) => {
    if (set.type === "line") {
        set.smooth = !set.smooth;
    }
});
```

### Expected Behavior

I would like the filter to return `LineSeriesOption$1`, so I can use the following code:

```
option.value.series.filter((set) => set.type === "line").forEach((set) => {
    set.smooth = !set.smooth;
});
```

### Environment

```markdown
- OS: macOS Monterey M1 2020
- Browser: Chrome
- Framework: Vue 3 + vue-echarts library
```

### Any additional comments?

Just a note, not high priority for me.

**Comment by pissang** [comment]
Seems it's the limitation of `TypeScript`. There is no type narrowing for the `filter` method. See https://github.com/microsoft/TypeScript/issues/20812#issuecomment-730717891
