### ISSUE TITLE
[Feature] How do I get the lines in the tree to flow?

### ISSUE THREAD

**Issue by HU914** [apache/echarts#16645]
### What problem does this feature solve?

Solve tree diagram connection line effect problem

### What does the proposed API look like?

Tree lines can have special effects

**Comment by Ovilia** [comment]
What do you mean by "flow"? If you want to change the position of the treen nodes, you may consider using graph charts with `layout: 'none'` and set the position of each node by yourself.

**Comment by HU914** [comment]
I wish I could set line Flow effects  in  graph charts

**Comment by Ovilia** [comment]
Do you mean [this](https://echarts.apache.org/examples/zh/editor.html?c=sankey-levels) or can you provide an example?

**Comment by HU914** [comment]
Can I use Chinese, English is not proficient, I can not express my meaning。

![image](https://user-images.githubusercontent.com/28580220/158357346-5607358f-7268-4045-9d99-72b0bc2b9c39.png)


example:
var colors=[
	"#00ADD0",
	"#FFA12F",
	"#B62AFF",
	"#604BFF",
	"#6E35FF",
	"#002AFF",
	"#20C0F4",
	"#95F300",
	"#04FDB8",
	"#AF5AFF"
]
var getdata=function getData() {
      let data = {
        name: "nodeRoot1",
        value: 0,
        children: []
      };
      for (let i = 1; i <= 10; i++) {
        let obj = {
          name: "node" + i,
          value: i,
          children: [],
        };
        for (let j = 1; j <= 5; j++) {
          let obj2 = {
            name: `node1-${i}-${j}`,
            value: 1 + "-" + i + "-" + j,
          };
          if(j%2==1){
            obj2.children=[]
            for (let k = 1; k <= 3; k++) {
              let obj3 = {
                name: `node1-${i}-${j}-${k}`,
                value: 1 + "-" + i + "-" + j+'-'+k,
              };
              obj2.children.push(obj3);
            }
          }
          
          obj.children.push(obj2);
        }

        data.children.push(obj);
      }
      let arr=[]
      arr.push(data)
      // 
      arr=handle(arr,0)
			console.log(arr);
      return arr;
    }
var handle=function handleData(data,index,color='#00f6ff'){
  //index
  return data.map((item,index2)=>{
     //
    if(index==1){
      color = colors.find((item, eq) => eq == index2 % 10);
    }
    //
    if(index===0 || index===1){
        item.label= {
          position: "inside",
        //   rotate: 0,
        //   borderRadius: "50%",
        }
    }
    //
    switch(index){
      case 0:
        item.symbolSize=70
        break;
      case 1:
        item.symbolSize=50
        break;
      default:
        item.symbolSize=10
        break;
    }
    // 
    item.lineStyle= { color: color }
   
    if (item.children) {//
      item.itemStyle = {
        borderColor: color,
        color:color
      };
      item.children=handle(item.children,index+1,color)
    } else {//
      item.itemStyle = {
        color:'transparent',
        borderColor: color
      };
    }
    return item
  })
}

var option = {
    type: "tree",
    backgroundColor: "#000",
    toolbox: {
      show: true,
      iconStyle: {
        borderColor: "#03ceda"
      },
      feature: {
        restore: {}
      }
    },
    tooltip: {
      trigger: "item",
      triggerOn: "mousemove",
      backgroundColor: "rgba(1,70,86,1)",
      borderColor: "rgba(0,246,255,1)",
      borderWidth: 0.5,
      textStyle: {
        fontSize: 10
      }
    },
    series: [
      {
        type: "tree",
        hoverAnimation: true, 
		data:getdata(),
		top: 0,
		bottom: 0,
        left: 0,
        right: 0,
        layout: "radial",
        symbol: "circle",
        symbolSize: 10,
					nodePadding: 20,
        animationDurationUpdate: 750,
        expandAndCollapse: true, 
        initialTreeDepth: 2,
        roam: true,
        focusNodeAdjacency: true,
        itemStyle: {
          borderWidth: 1,
        },
        label: { 
          color: "#fff",
          fontSize: 10,
          fontFamily: "SourceHanSansCN",
           position: "inside",
          rotate: 0,
        },
        // I want the function ============ start
        effect: {
          constantSpeed: 20,
          show: true,
          trailLength: 0.1,
          symbolSize: 1.5
        },
         //I want the function ============ end
        lineStyle: {
          width: 1,
          curveness:0.5,
        }
      }
    ]
  };
