### ISSUE TITLE
[Feature] 数值轴的数据过大, 导致显示了很多0, 占用位置比较大, 希望转化

### ISSUE THREAD

**Issue by a15218378694** [apache/echarts#16643]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/29919045/157152978-f396724a-6af4-4ea3-9128-947614814401.png)
希望以万, 或者亿为单位

### What does the proposed API look like?

yAxis

**Comment by susiwen8** [comment]
Please use [formatter](https://echarts.apache.org/zh/option.html#yAxis.axisLabel.formatter)
