### ISSUE TITLE
[Feature] 柱状图, X轴为类目轴, 旋转后看不齐全, 出现文字被裁剪

### ISSUE THREAD

**Issue by a15218378694** [apache/echarts#16641]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/29919045/157023143-604b0c2c-f867-48fb-b2d2-e3140d942217.png)
2022没有完整展示

### What does the proposed API look like?

没有

**Comment by susiwen8** [comment]
try `containLabel`

**Comment by a15218378694** [comment]
> 

解决了, 感谢
