### ISSUE TITLE
有没有可以将kaggle的数据集展示的合适的图表

### ISSUE THREAD

**Issue by zjtdsg** [apache/echarts#16647]
### What problem does this feature solve?

kaggle数据集图表展示

### What does the proposed API look like?

将kaggle中的csv文件转化为有数据分布的图标

**Comment by susiwen8** [comment]
That's user's choise.

**Comment by zjtdsg** [comment]
什么意思

**Comment by zjtdsg** [comment]
什么意思

**Comment by susiwen8** [comment]
数据想用什么图表呈现是用户决定的，如果想用折线图展现数据就用 `line`, 如果想用柱状图就用 `bar`, 如果想用散点图就用 `sactter`
