### ISSUE TITLE
[Bug] 数据量少的时候起点和终点会有很多留白

### ISSUE THREAD

**Issue by aninchiron** [apache/echarts#16658]
### Version

5.2.1

### Steps to Reproduce

数据量很少的时候就会这样

### Current Behavior

数据量少的时候起点和终点会有很多留白
![1646828177098](https://user-images.githubusercontent.com/21594916/157441345-d4f8d8a5-6e2a-4272-98dd-bf70fbd956b8.jpg)

### Expected Behavior

希望能像highchart一样处理，在起点向前移，终点往后移
![1646828092446](https://user-images.githubusercontent.com/21594916/157441285-57b20861-fd09-4c92-bde3-028a5fece537.jpg)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
设置 [xAxis.boundaryGap](https://echarts.apache.org/option.html#xAxis.boundaryGap) 为 `false`.

**Comment by aninchiron** [comment]
> 设置 [xAxis.boundaryGap](https://echarts.apache.org/option.html#xAxis.boundaryGap) 为 `false`.

感谢
