### ISSUE TITLE
[Bug] Heatmap visualmap filtering not working - CoordSys is undefined

### ISSUE THREAD

**Issue by JiahuiChen99** [apache/echarts#16659]
### Version

5.3.1

### Steps to Reproduce

I'm following the Cartesian Heatmap chart example (https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian). But the filtering with the visualMap doesn't work properly. Once I move the cursors to select the desired range, it throws this error.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at HeatmapView.render (HeatmapView.js?d7f5:137)
    at Task.progress (Chart.js?fc49:233)
    at Task._doProgress (task.js?d463:187)
    at Task.perform (task.js?d463:153)
    at eval (echarts.js?f2a6:1821)
    at GlobalModel.eval (Global.js?05a0:654)
    at Array.forEach (<anonymous>)
    at each (util.js?d5c9:205)
    at GlobalModel.eachSeries (Global.js?05a0:651)
    at renderSeries (echarts.js?f2a6:1809)
```
The source code line that breaks is the **137** in HeatmapVIew.js file.
```
    this._progressiveEls = null;
    this.group.removeAll();
    var coordSys = seriesModel.coordinateSystem;

   // The following check breaks because coordSys is undefined
    if (coordSys.type === 'cartesian2d' || coordSys.type === 'calendar') {
      this._renderOnCartesianAndCalendar(seriesModel, api, 0, seriesModel.getData().count());
    } else if (isGeoCoordSys(coordSys)) {
      this._renderOnGeo(coordSys, seriesModel, visualMapOfThisSeries, api);
    }
```

I've debugged the code, and when the component renders(I'm using Vue@3) on **mounted**, coordSys.type is cartesian2d. But once I move the visualmap cursor, that variable becomes undefined.

![image](https://user-images.githubusercontent.com/37770349/157444648-d9840296-f4ba-4256-b300-c51961f3e03a.png)
![image](https://user-images.githubusercontent.com/37770349/157444758-9ae573d8-1792-4b6a-a6c4-a31cc13efd59.png)

### Current Behavior

Everything works as expected, until I use the visualmap to filter values. The chart breaks and doesn't display values anymore.

### Expected Behavior

It should apply a filter and display the values that falls within the selected range from the visualmap to the heatmap chart.

### Environment

```markdown
- OS: Linux
- Framework: Vue@3
```

**Comment by plainheart** [comment]
Check if you are using `ref` or `reactive` to make echarts instance reactive. If so, try to use `shallowRef` or `shallowReactive` or a common variable instead.

**Comment by isuye** [comment]
我把const chart =ref(null)
改为
let chart = null就行了欸

**Comment by JiahuiChen99** [comment]
I'm using a common variable. In vue data() I have a heatmap_chart variable initialized to null, and on component mounted() event  I create the chart and assign it to the variable. It doesn't work :woman_shrugging: 

```
mounted() {
   let heatmapDom = document.getElementById('chart');
   this.heatmap_chart = echarts.init(heatmapDom);

   this.heatmap.setOption(data);
}
```

**Comment by plainheart** [comment]
> In vue data() I have a heatmap_chart variable initialized to null,

@JiahuiChen99 This is not expected. Just remove the `heatmap_chart` variable from vue `data` block.

**Comment by JiahuiChen99** [comment]
> > In vue data() I have a heatmap_chart variable initialized to null,
> 
> @JiahuiChen99 This is not expected. Just remove the `heatmap_chart` variable from vue `data` block.

Declaring the chart in the mounted scope, like this, seems to work.

```
mounted(){
    let heatmap_chart = echarts.init();
}

```
But, how am I supposed to reference the chart later in the beforeUnmount block, so that I can dispose it? And what's the reason why, what I did before the doesn't work?

**Comment by plainheart** [comment]
Don't worry. You may still use `this.heatmap_chart = echarts.init()` to mount the echarts instance to `this`. Just please don't put it in `data` block to avoid making echarts instance reactive.

```vue
data() {
    return {
        // DON'T declare here!
        // heatmap_chart: null
    }
},
mounted() {
    // Mount this echarts instance on current vue instance using `this`
    this.heatmap_chart = echarts.init();
},
beforeUnmount() {
    // destroy echarts instance
    this.heatmap_chart && this.heatmap_chart.dispose();
}
```

**Comment by JiahuiChen99** [comment]
Thank you @plainheart for the explanation! It does work now :100:

**Comment by plainheart** [comment]
BTW, please refer to the [Vue documentation](https://vuejs.org/api/reactivity-advanced.html#markraw) for the reason.

> Some values simply should not be made reactive, for example a complex 3rd party class instance, or a Vue component object.
