### ISSUE TITLE
Chart is not rendering properly when category axis values are numbers[Bug] 

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16654]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/Harshitha19/pen/NWwZNWw

### Steps to Reproduce

Create a chart with numeric category values.
Observe that the chart is not rendering properly.

Please look at the below sample:
https://codepen.io/Harshitha19/pen/NWwZNWw 

In the above sample even after Dairy Milk having a certain price value, its corresponding bar is not rendering.

Observation: If we stringify the corresponding row value in data, the chart is plotting properly.

### Current Behavior

When a chart is plotted with numeric category values, it is not rendering properly.

### Expected Behavior

Chart should render properly even with the numeric category values

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MNHarshitha** [comment]
> I didn't see any difference after changing `yAxis.data` to be strings. Can you be more specific about what is wrong and what is expected?

We need to convert row dimension values present in the data to strings.
![image](https://user-images.githubusercontent.com/97500674/180989919-c50382de-b945-4583-a231-007f721691d6.png)
![image](https://user-images.githubusercontent.com/97500674/180990333-5d5d63d2-c9f3-4301-b785-34cd8a4dfdd2.png)

https://codepen.io/Harshitha19/pen/mdxMNmY

**Comment by RavalikaP** [comment]
Hi, We also have similar use case where we are rendering the charts with same labels but with unique ID's. Any suggestions/ workaround in this regard would be much appreciated.
