### ISSUE TITLE
How to render only legends[Feature] 

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16669]
### What problem does this feature solve?

Hi 
We have a requirement where we need to render only legends.
Is there a way to render only legends without rendering series, category, and value axis?
If not, is there a way to hide series, similar to that of category and value axis?

### What does the proposed API look like?

A property to hide series.
{
show: false
}

**Comment by susiwen8** [comment]
If you want only legend, use HTML and JS, much simpler
