### ISSUE TITLE
[Bug] 时间轴-series-bar. label显示问题

### ISSUE THREAD

**Issue by ITchenjian** [apache/echarts#16666]
### Version

5.3.1

### Steps to Reproduce
```js
option = {
  yAxis: {
    type: 'category',
    data: ['Mon', 'Tue']
  },
  xAxis: {
    type: 'time',
    minInterval: 3600 * 24 * 1000,
    axisLabel : {
        color: '#3D3F4B',
        interval: 0,
        showMaxLabel: true,
        formatter: (value, index) => {
            var date = new Date(value);
            var texts = [(date.getMonth() + 1), date.getDate()];
            return texts.join('-');
        }
    },
  },
  series: [
    {
      data: ['2021/12/15', '2021/12/16'],
      type: 'bar',
      label: {
          show: true,
          position: "right",
          formatter: function(params) {
              return '测试' + params.name;
          },
          color: '#000',
      },
    }
  ]
};
```
### Current Behavior

series-bar. label不显示（奇怪的是，将X轴于Y轴互换就可显示）
如图
![image](https://user-images.githubusercontent.com/24711527/157790362-0b2cb070-b845-4bab-a726-697410112923.png)
X轴于Y轴互换后
![image](https://user-images.githubusercontent.com/24711527/157790492-cb178413-3d88-4403-b78c-8f2890091b28.png)

### Expected Behavior

series-bar. label显示问题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
I have copy your options, seem ok
<img width="1440" alt="Screen Shot 2022-03-11 at 5 35 04 PM" src="https://user-images.githubusercontent.com/20318608/157841058-cf8dab04-d5df-4357-a160-f713be075941.png">

**Comment by ITchenjian** [comment]
谢谢你的回答
可以在这看看（替换配置，在项目也是这种情况）
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&version=5.3.1
@susiwen8

**Comment by susiwen8** [comment]
Are you sure the option you provide is the one who can reproduce this issue? I stil can't reproduce bug by pasting your option in https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&version=5.3.1
Which browser and OS you have?

**Comment by ITchenjian** [comment]
@susiwen8  确实是这样，用的是win10和谷歌
这是我笔记本上谷歌版本
![image](https://user-images.githubusercontent.com/24711527/157873649-4c32c177-da79-4167-bb40-d5678b584981.png)
我笔记本和公司电脑都是这样，配置确实没错，我自己就是粘的这个配置
![image](https://user-images.githubusercontent.com/24711527/157873456-4e9964f0-feb3-4327-aeef-0bf0ce286fb5.png)

**Comment by lefex** [comment]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/8437666/157889438-85f13bd5-e354-401a-98e4-f3e652f47253.png">

I can show also.

**Comment by susiwen8** [comment]
> @susiwen8 确实是这样，用的是win10和谷歌 这是我笔记本上谷歌版本 ![image](https://user-images.githubusercontent.com/24711527/157873649-4c32c177-da79-4167-bb40-d5678b584981.png) 我笔记本和公司电脑都是这样，配置确实没错，我自己就是粘的这个配置 ![image](https://user-images.githubusercontent.com/24711527/157873456-4e9964f0-feb3-4327-aeef-0bf0ce286fb5.png)

Chrome 版本和你一样，但我的系统是 MacOS, 难道是 win10 的问题？

**Comment by ITchenjian** [comment]
谢谢你们的回答。
谢谢你的提示 @lefex
又发现了一个奇怪了现象，窗口100%不显示、110%显示、125%不显示、150%又显示
![image](https://user-images.githubusercontent.com/24711527/158005314-1fc95e71-828d-4fe7-9fbf-ec39224ef8d1.png)
![image](https://user-images.githubusercontent.com/24711527/158005349-0f6b9fd8-5bcb-40be-a7f7-21448c65b547.png)
![image](https://user-images.githubusercontent.com/24711527/158005351-3efe6d89-986d-428e-8d1e-85ee431d1535.png)
![image](https://user-images.githubusercontent.com/24711527/158005350-a8c5c317-0e0d-4395-9cdf-4cd5a747ca22.png)

**Comment by ITchenjian** [comment]
以此类推，随着窗口大小的改变时有时无！

**Comment by ITchenjian** [comment]
依次类推，随着窗口大小的改变时有时无！

**Comment by plainheart** [comment]
应该还是因为被系列坐标系裁切的原因，设置下 `series.clip` 为 `false` 对比下。和 #16661 问题类似，不同宽度下会出现被裁切的情况。

**Comment by ITchenjian** [comment]
@plainheart
设置series.clip 为 false的话，label是出来了但柱状完全超出的部分就出来了
![Uploading image.png…]()

**Comment by ITchenjian** [comment]
@plainheart
如果设置series.clip 为 false的话，label是出来了但柱状完全超出的部分就出来了
![image](https://user-images.githubusercontent.com/24711527/158015667-bc764eab-e362-420b-a74e-284092b26c36.png)

**Comment by ITchenjian** [comment]
这种问题可有好的解决之法

**Comment by plainheart** [comment]
我怎么感觉禁用裁切之后的图表渲染本身就有些问题... @Ovilia @susiwen8 WDYT?

**Comment by yuli-TG** [comment]
I have the same issue. The height of the time bar is 0.

**Comment by pissang** [comment]
There are several unexpected issues here:

1. The `xAxis` is a time axis. And when calculating the start point of bar. We usually starts with `0` value. Like https://github.com/apache/echarts/blob/master/src/layout/barGrid.ts#L606 did. But `0` is not a quite valid value in the time axis. So it cause a very weried shape:
```ts
{
  "x": -9730657.766666668,
  "y": 247.11,
  "width": 9730721.866666667,
  "height": 111.78
}
```

2. Even if the calculated rect shape is quite unexpected. We can still render it normally in most cases after clipped in https://github.com/apache/echarts/blob/master/src/chart/bar/BarView.ts#L691 . And there may be a precision issue when do clipping calculation which cause the bar is totoally clipped and marked to be ignore

**Comment by fuchunhui** [comment]
a very interesting case😂
