### ISSUE TITLE
[Bug] 时间轴-数据为时间的显示问题

### ISSUE THREAD

**Issue by ITchenjian** [apache/echarts#16663]
### Version

5.3.0

### Steps to Reproduce

```js
option = {
  title: {
    text: 'World Population'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {},
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: {
    type: 'time',
    minInterval: 3600 * 24 * 1000,
    axisLabel : {
        color:'#3D3F4B',
        interval: 0,
        formatter: (value, index) => {
            var date = new Date(value);
            var texts = [(date.getMonth() + 1), date.getDate()];
            return texts.join('-');
        }
    },
    axisLine:{
        show:true,
    },
  },
  yAxis: {
    type: 'category',
    data: ['Brazil', 'Indonesia', 'USA', 'India', 'China', 'World']
  },
  series: [
    {
      name: '2011',
      type: 'bar',
      label: {
          show: true,
          position: "right",
          formatter: function(params) {
              return '测试1';
          },
          color: '#000',
      },
      data: ['2021/12/16', '2021/12/16', '2021/12/16', '2021/12/16', '2021/12/16', '2021/12/16']
    },
    {
      name: '2012',
      type: 'bar',
      label: {
          show: true,
          position: "right",
          formatter: function(params) {
              return '测试2';
          },
          color: '#000',
      },
      data: ['2021/12/15', '2021/12/15', '2021/12/16', '2021/12/16', '2021/12/16', '2021/12/16']
    }
  ]
};
```

### Current Behavior

x轴为time轴，y为category轴时有如下问题：
x轴的axisLabel，最后一个不显示；
series的label为 '2021/12/15' 也不显示 （更改grid可能会出现，单有些情况也没用）

### Expected Behavior

x轴的axisLabel 和 series的label 正确显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
针对x轴不显示最后一个label的问题，只需要设置xAxis.axisLabel.showMaxLabel为true即可显示；
第二个问题当series的label为2021/12/15时不显示，我理解是因为label太长导致超出画布，只能部分显示，可以选择把position设为空使其显示在bar上，也可以设置为left让它显示在坐标轴左侧。

**Comment by ITchenjian** [comment]
@jiawulin001 谢谢你的回答，第一个问题用xAxis.axisLabel.showMaxLabel为true可以解决；
第二个问题不是label太长的原因，2021/12/15这条数据在X轴上(x轴起始坐标为2021/12/15)对应的刻度为2021/12/15 - 2021/12/15 ，也就是在贴合在y轴上，相当于长度为0，在这种情况下series的label (测试2) 不显示；
可以把代码贴到这下面试一下（替换原有配置），观察第一二条数据其series的label
https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category&version=5.3.1

**Comment by ITchenjian** [comment]
![image](https://user-images.githubusercontent.com/24711527/157785821-e1b134ea-b817-4bee-9b00-978fd69d2da8.png)

**Comment by ITchenjian** [comment]
@jiawulin001 谢谢你的回答，第一个问题用xAxis.axisLabel.showMaxLabel为true可以解决；
第二个问题不是label太长的原因，2021/12/15这条数据在X轴上(x轴起始坐标为2021/12/15)对应的刻度为2021/12/15 - 2021/12/15 ，也就是在贴合在y轴上，相当于长度为0，在这种情况下series的label (测试2) 不显示；
可以把代码贴到这下面试一下（替换原有配置），观察第一二条数据其series的label
https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category&version=5.3.1
如下图所示：
![image](https://user-images.githubusercontent.com/24711527/157786061-a8e60404-cf7e-41bb-8b35-67adbf1ba68f.png)

**Comment by plainheart** [comment]
这个是不是和 #16666 是同一个问题？

**Comment by yuli-TG** [comment]
I have the same issue. The height of the time bar is 0.
