### ISSUE TITLE
[石油行业的点位图和地理剖面图使用哪种图例] 

### ISSUE THREAD

**Issue by sunxia628** [apache/echarts#16668]
### What problem does this feature solve?

请问类似[https://www.int.com/geotoolkit-demos/deviated-schematics/]图例的偏差示意图，使用哪种图例？
我的原型设计图如下：
![u166](https://user-images.githubusercontent.com/26341016/157827808-ff24c6c7-eed7-4596-9d6b-ef6da21f9fed.png)
![u265](https://user-images.githubusercontent.com/26341016/157827813-2f649c5a-8fa8-480b-bce1-45194c2e4b41.png)
在echarts的示例中似乎找不到合适的解决方案

### What does the proposed API look like?

请问对于石油行业的点位图和地理剖面图，现有的echarts图例哪种比较适合？
如果没有合适的图例，后续有没有此类开发计划，谢谢！

**Comment by Ovilia** [comment]
基本图是普通散点图，在这个基础上自己画一些线或者形状：https://echarts.apache.org/zh/option.html#graphic.elements-polyline

**Comment by sunxia628** [comment]
@Ovilia 谢谢，已经画出来了，长时间不画图，看了原型有点无从下手！
