### ISSUE TITLE
[Bug] 【散点图问题】当散点图设置了 grid.top = "14%" 之后，右上角的散点消失了

### ISSUE THREAD

**Issue by Bangbabaz** [apache/echarts#16661]
### Version

5.3.1

### Steps to Reproduce
```ts
option = {
  xAxis: {},
  yAxis: {},
  grid: {
    top: '14%',
  },
  series: [
    {
      symbolSize: 20,
      data: [
        [1, 1],
        [1, 0],
      ],
      type: 'scatter'
    }
  ]
};
```

### Current Behavior

我在开发散点图的时候遇到了这个问题，好像有不止这一个比例会使右上角的散点消失，例如：15， 16， 20 ，40，可能还有更多
![QQ图片20220310155211](https://user-images.githubusercontent.com/61530016/157614191-6d0fd086-be21-459a-a294-71a61f181505.png)

### Expected Behavior

只要不超出 canvas 的范围，右上角的散点应该显示出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
默认系列开启了裁切超出坐标系的数据点，但因为坐标计算的时候会有微小的偏差导致被误裁切。可以先设置 [`series.clip`](https://echarts.apache.org/option.html#series-scatter.clip) 为 `false` 关闭裁切。
