### ISSUE TITLE
[Bug] 在版本5中定义一个使用stack属性的bar组件时与版本四的表现存在差异

### ISSUE THREAD

**Issue by dobettest** [apache/echarts#16667]
### Version

5.3.1

### Link to Minimal Reproduction

https://h3tm59.csb.app/

### Steps to Reproduce
```ts
{
      xAxis: {
        show: false
      },
      yAxis: {
        type: "category",
        show: false
      },
      series: [
        {
          type: "bar",
          data: [200],
          stack: "总量",
          barWidth: 10,
          itemStyle: {
            color: "green"
          }
        },
        {
          type: "bar",
          data: [250],
          // stack: '总量',
          barWidth: 10,
          itemStyle: {
            color: "#eee"
          }
        }
      ],
      grid: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0
      }
    };
```
复现步骤:对比取消第二个series中的stack属性注释与未取消前的偏移效果

### Current Behavior

灰色bar和绿色bar重叠后的offset为250

### Expected Behavior

灰色bar和绿色bar的重叠后的offset为50，实际上为250

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by WindyZ99** [comment]
I'm interested in answer this issue.

**Comment by WindyZ99** [comment]
If you set property `stack` both, the grey bar and the green bar is still keep its original ratio of 2:2.5, and the xAxis value has changed to `200 + 250 = 450` accordingly. I think it is matching expectations.

**Comment by dobettest** [comment]
I know the xAxis value has changed to 200 + 250 = 450,but it seem to a difference between the version 5 and the previous versions.it has long whitespace when I do this,like this [image](https://user-images.githubusercontent.com/47207076/158500060-13615dbc-1610-4aac-b063-359a5182bd30.png)
