### ISSUE TITLE
[support] 

### ISSUE THREAD

**Issue by boomstackcn** [apache/echarts#16676]
### What problem does this feature solve?

grid进行如下设置后：
`grid: {
        top: 70,
        bottom: 70,
        left: 20,
        right: 20,
        containLabel: true
    }`
如何获取grid的宽度（我需要根据grid的宽度动态计算axisLabel.rotate）

### What does the proposed API look like?

希望能获取到自适应的grid宽度

**Comment by Ovilia** [comment]
自己用变量记录下这个值

**Comment by boomstackcn** [comment]
感谢回答！grid.width是自适应的，我并未设置(无法用变量记录)，因为设置了containLabel: true，所以并不能通过减去left和right的值获取。

**Comment by boomstackcn** [comment]
可通过 `myChart._chartsViews[1]._coordSys.master._rect.width` 进行获取
