### ISSUE TITLE
[Bug] 在setOption使用notMerge:false参数更新图形时,animation:false,但是超过3000组数据强制出现动画

### ISSUE THREAD

**Issue by schzh** [apache/echarts#16671]
### Version

5.3.1

### Steps to Reproduce

1、setOption使用notMerge:false参数更新图形时
2、animation:false
3、数组组为2999以下时，图形更新平稳正常，但是大于等于3000组数据时，强制出现动画，把所有数据强制重新画了一遍；哪怕只是增加一组，也是从第0组强制画了一遍，而不是合并。

### Current Behavior

怀疑组件有BUG，在3000组数据时强制开启了动画animation。类似于animationThreshold:3000的意思，但是跟那个是反的，animationThreshold是超过这些数据关闭动画，这个BUG是开启

### Expected Behavior

改正3000组数据开启动画重画，不能平稳添加数据的问题

### Environment

```markdown
- OS:WIN10
- Browser:Chrome 99.0.4844.51
- Framework:
```

**Comment by schzh** [comment]
@pissang @plainheart 麻烦帮着看下，多谢

**Comment by schzh** [comment]
补充下，类型是自定义图形，坐标系是地理坐标系，底图高德，但是我感觉跟这个关系不大，应该是Echarts本身的问题

**Comment by schzh** [comment]
开始因为是数据问题，最后经过侦测，跟数据本身没关系，只跟数据量有关，恰好3000组数据就会出问题，貌似是3000数据就强制开启了动画的感觉

**Comment by plainheart** [comment]
这不是动画，超过 `3000` 会开启渐进式渲染。参见 [progressiveThreshold](https://echarts.apache.org/option.html#series-scatter.progressiveThreshold)

**Comment by schzh** [comment]
> 

多谢，确实是忘了设置progressive:0了，没想到这个是默认开启的，设置progressive:0,之后正常，事实上，我需要的大约是10000组左右数据平稳不闪烁，那么progressiveThreshold:10000也可以
