### ISSUE TITLE
Total node count missing in treechart

### ISSUE THREAD

**Issue by AashishChakravarty** [apache/echarts#16684]
### Version

4.8.2

### Steps to Reproduce

Chart Type: Tree

There is no any attribute for total tree nodes count

### Current Behavior

No attribute for Total nodes count

### Expected Behavior

Attribute required for Total nodes count

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
`tree` depends on the data, user can calculate node's number by data.
