### ISSUE TITLE
[Feature] add legendhovered event

### ISSUE THREAD

**Issue by jayarjo** [apache/echarts#16680]
### What problem does this feature solve?

This feature is related to "[Can´t display tooltip on chart legend (Echarts)](https://github.com/apache/echarts/issues/11571#issuecomment-551036786)". The problem basically is that there seems to be no way to show a tooltip for the legend item. In our case some of the items are often lengthy and do not fit:

![Screenshot 2022-03-14 193605](https://user-images.githubusercontent.com/150075/158207020-9fc63b1d-af77-45c0-80e9-12df90c4da92.png)

Documentation has entry for [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip), but it doesn't seem to do anything. I'm not sure if it's a bug with implementation or documentation. Either way would be great to have it working or at least to have a `legendhovered` event to show the tooltip manually, as @Ovilia suggested [here](https://github.com/apache/echarts/issues/11571#issuecomment-551036786).

### What does the proposed API look like?

Have a [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip) working or `legendhovered` triggered when legend item is hovered. In the latter case listener should receive all details about currently hovered legend item.

**Comment by jayarjo** [comment]
Looks like [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip) works after all - however `show` property has to be explicitly set to `true` (found out after reading the source).

**Comment by youthug** [comment]
> Looks like [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip) works after all - however show property has to be explicitly set to true (found out after reading the source).

Which is worked? Showing a tooltip on a hovered legend? I tried [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip), what just worked as well as a [tooltip](https://echarts.apache.org/en/option.html#tooltip) do. How could I show **a tooltip for a legend**?

**Comment by jayarjo** [comment]
@youthug try to set `legend.tooltip.show` to `true`.

**Comment by youthug** [comment]
> Looks like [legend.tooltip](https://echarts.apache.org/en/option.html#legend.tooltip) works after all - however `show` property has to be explicitly set to `true` (found out after reading the source).

Yes I did. But what i excepted is a tooltip for my legends to be created, not another [tooltip](https://echarts.apache.org/en/option.html#tooltip)

**Comment by jayarjo** [comment]
Not sure I understand your problem. It is a tooltip for legend.

**Comment by youthug** [comment]
@jayarjo It worked! So I set `position` in the `tooltip` property, it also takes effect for the legend.tooltip property. So...I thought they are the same! But it does create a tooltip for the legend. Not sure if I made it clear. Anyway, thanks!
