### ISSUE TITLE
[Bug] 5.3.1版本中自定义图表存在执行异常情况，相同代码在5.2.2版本中正常运行

### ISSUE THREAD

**Issue by Lino99-FE** [apache/echarts#16698]
### Version

5.3.1

### Link to Minimal Reproduction

https://stackblitz.com/edit/react-nfmuzj?file=index.js

### Steps to Reproduce

点击按钮 “exce-正常情况”正常显示图表
点击按钮”error-异常情况1“或”error-异常情况2“出现异常报错，图表无法正常显示

### Current Behavior

5.3.1版本出现异常报错，降级至5.2.2版本功能正常

### Expected Behavior

正常显示图表

### Environment

```markdown
- OS:macOS bigsur
- Browser:Chrome 99
- Framework:React 17
```

**Comment by mjurika** [comment]
This is related to my reported bug https://github.com/apache/echarts/issues/16694
