### ISSUE TITLE
How to listen 'xAxis.axisPointer.handle' Drag and drop event

### ISSUE THREAD

**Issue by MainPri** [apache/echarts#16690]
### What problem does this feature solve?
 I want to dynamically fill the Echarts data corresponding to the current time according to the time stamp of the drop point when I drag handle dynamically
example:
    https://echarts.apache.org/examples/zh/editor.html?c=line-tooltip-touch&edit=1&reset=1

### What does the proposed API look like?

Supports listening for drag events in 'xAxis.axisPointer.handle' like:
myChart.on('mousemove','xAxis.axisPointer.handle',function (params){
    console.log(params)
})

**Comment by diversified-validator-network** [comment]
A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function

**Comment by ioannist** [comment]
A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function

**Comment by grenobnik** [comment]
> A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function

looks like this is a **permanent** workaround, not temporary 🙂

**Comment by MainPri** [comment]
> > A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function
> 
> looks like this is a **permanent** workaround, not temporary 🙂

Thanks, I have a better solution, can better achieve the effect I need 。✌️

**Comment by grenobnik** [comment]
> > > A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function
> > 
> > 
> > looks like this is a **permanent** workaround, not temporary 🙂
> 
> Thanks, I have a better solution, can better achieve the effect I need 。✌️

Can you elaborate?

**Comment by Arkadij-Dev-C** [comment]
> > > A temporary workaround is to listen for events inside the xAxis.axisPointer.label.formatter function
> > 
> > 
> > looks like this is a **permanent** workaround, not temporary 🙂
> 
> Thanks, I have a better solution, can better achieve the effect I need 。✌️

I'd also be interested
