### ISSUE TITLE
仪表盘的进度条如何配置由深到浅的渐变？gauge progress LinearGradient

### ISSUE THREAD

**Issue by Yijx** [apache/echarts#16697]
请问如何配置progress的itemStyle的color的渐变能达到如下效果
<img width="584" alt="image" src="https://user-images.githubusercontent.com/30200703/158927120-8e8fbb49-54a0-4ba6-b084-e22b3a2580ff.png">

**Comment by plainheart** [comment]
设置 [`progress.itemStyle.color`](https://echarts.apache.org/option.html#series-gauge.progress.itemStyle.color) 为[渐变色](https://echarts.apache.org/option.html#color)。

**Comment by Yijx** [comment]
> 设置 [`progress.itemStyle.color`](https://echarts.apache.org/option.html#series-gauge.progress.itemStyle.color) 为[渐变色](https://echarts.apache.org/option.html#color)。

感谢。不过线性渐变好像无法完成该效果

**Comment by Yijx** [comment]
> 似乎需要 conic gradient 圆锥渐变才能实现此类效果，暂时还不支持。

好的，谢谢，曲线救国，用100弧长拼成了这个效果
<img width="369" alt="image" src="https://user-images.githubusercontent.com/30200703/159418872-2ef06c82-4540-497f-b96e-f40f281b9b53.png">

**Comment by jiawulin001** [comment]
@Yijx 能讲下是怎么拼出来的吗？目前的Echarts的线性渐变和径向渐变都是基于Zrender本身已有的渐变功能，如果需要实现圆锥渐变似乎需要Zrender本身支持这个功能？

**Comment by Yijx** [comment]
> @Yijx 能讲下是怎么拼出来的吗？目前的Echarts的线性渐变和径向渐变都是基于Zrender本身已有的渐变功能，如果需要实现圆锥渐变似乎需要Zrender本身支持这个功能？

https://juejin.cn/post/6844903908335157262 基本上是参考了这个的实现
