### ISSUE TITLE
[Bug] visualMap.textGap has no effect on the gap of visualMap.text

### ISSUE THREAD

**Issue by ZeekoZhu** [apache/echarts#16706]
### Version

5.3.0

### Link to Minimal Reproduction

https://jsfiddle.net/zeeko/ft4zwmun/4/

### Steps to Reproduce

1. use example options from https://echarts.apache.org/zh/option.html#visualMap-piecewise.text
2. add `visualMap.text` and `visualMap.textGap` Options

### Current Behavior

![image](https://user-images.githubusercontent.com/13861843/159146254-caa311e8-65aa-47fb-87e2-0006d5d280d9.png)

The gap between "text on both ends" is not changed.

But the gap between the item label and the item can be changed by the `visualMap.textGap` option. 

### Expected Behavior

The gap between "text on both ends" should be changed by `visualMap.textGap`.

### Environment

```markdown
- OS: Arch Linux 5.15.28-1-lts
- Browser: Firefox 98.0.1
- Framework: vanilla JavaScript
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/13861843/159146553-dff9d11f-7d39-4a1f-a9de-c753f84cb33a.png)

![image](https://user-images.githubusercontent.com/13861843/159146567-59794151-7c63-4273-9c0c-f47b44a8bc99.png)

I think there are some discrepancies between Chinese docs and English docs about `visualMap.textGap`, and the current implementation is according to the English documentation.

Is there any appropriate options to control the gap between "text on the ends" and visualMap item ?

**Comment by jiawulin001** [comment]
As is tested, the 'textGap' actually refers to the distance between color bar and label text of each color. If you set visualMap.showLabel to true and change visualMap.textGap, you can see the changes. This  looks like a typo of the official documents. 

textGap = 10
![echarts issue#16706-1](https://user-images.githubusercontent.com/14244944/159200757-7f6a4d7e-9794-4cff-8cb8-6b7b707cc511.PNG)

textGap = 30
![echarts issue#16706-2](https://user-images.githubusercontent.com/14244944/159200776-54fb6d67-b397-418c-8f5b-776d24516981.PNG)

**Comment by ZeekoZhu** [comment]
@jiawulin001 Are there any appropriate options to control the distance between the "text on the ends" and the visualMap items? For now, I have to use whitespace to simulate the gap.

**Comment by jiawulin001** [comment]
Sorry no existent function seems to directly control it. If you expect community to develop such feature, you might want to reopen this issue or resubmit another issue to explicitly announce this wanted feautre.
