### ISSUE TITLE
[Feature] 想问一下，动态排序柱状图如何制作视频呢

### ISSUE THREAD

**Issue by interstellar-ai** [apache/echarts#16707]
### What problem does this feature solve?

社交媒体上有好多的数据可视化的视频，想问一下，echarts是不是也可以做这个

### What does the proposed API look like?

动画能保存成视频就可以

**Comment by susiwen8** [comment]
canvas has `captureStream`, maybe you can use that. 
I recommend https://github.com/welefen/canvas2video
