### ISSUE TITLE
[Question][Feature] How do you specify date format in tooltip?

### ISSUE THREAD

**Issue by jkasperbl** [apache/echarts#16703]
### What problem does this feature solve?

Please see the following sample configuration:

```
option = {
  dataset: {
    source: [
      { date: '3022-03-01', count: 6 },
      { date: '3022-03-02', count: 3 },
      { date: '3022-03-03', count: 4 },
      { date: '3022-03-04', count: 6 },
      { date: '3022-03-05', count: 7 },
      { date: '3022-03-06', count: 2 },
      { date: '3022-03-07', count: 8 },
      { date: '3022-03-08', count: 6 },
      { date: '3022-03-09', count: 9 }
    ]
  },
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      type: 'line',
      name: 'Count'
    }
  ],
  tooltip: {
    trigger: 'axis'
  }
};
```

This results in the tooltip displaying the date with all zeros for time. Is there an easy way to format this as date-only? I know how to use a function for `series.tooltip.valueFormatter` for the other values, but I'm not sure how to do this for the x-axis since no series is defined for it.

![image](https://user-images.githubusercontent.com/9469496/159055649-588cbbc4-dc0f-4cb8-a02e-9183a92ad468.png)

### What does the proposed API look like?

Perhaps a valueFormatter option added to `xAxis.tooltip` which accepts either a string or a function.

```
xAxis: {
    type: 'time',
    tooltip: {
        valueFormatter: 'yyyy-MM-dd'
    }
}
```

**Comment by jiawulin001** [comment]
Yes, you can solve this by adding a formatter to tooltip:
```
tooltip: {
    trigger: 'axis',
    formatter:function(param){
      param = param[0];
      return (
        `Date: ${param.value.date} <br/>
        Count: ${param.value.count}`)
    }
  }
```

**Comment by jkasperbl** [comment]
Thanks @jiawulin001. That works, but I don't think it's a great solution for the following reasons:

- You have to re-apply the default tooltip styling (with series color marker, etc.) for each value displayed
- The `valueFormatter` functions for each series are now ignored and you have to use messier logic inside the main tooltip `formatter`

It would be much better if we could specify a `valueFormatter` for the independent axis so all other tooltip functionality works by default.

**Comment by scchengaiah** [comment]
I have a similar requirement as well to format date for better user experience. Can we expect this feature in the coming months or do we have any other alternative to apply default styling for tooltip along with date formatting.

**Comment by Airkro** [comment]
I don't know why but `tooltip.axisPointer.label.formatter` works in my case.

![image](https://user-images.githubusercontent.com/12206891/169945853-df848b59-0e03-493c-8100-c83a9a98ef38.png)

**Comment by jkasperbl** [comment]
Thanks @Airkro, that one seems to do the trick! Much appreciated!

**Comment by joaocarlosss84** [comment]
For those like me that would like to format time for a multiple series chart, you can use a function:
`
tooltip: {
  trigger: 'axis',
  axisPointer: {
    label:  {
      formatter: function(params) {
        let oT = new Date(params.value);
        return oT.toISOString();
      },
   }
}
`

**Comment by rorueda** [comment]
Unfortunately, this only works when `trigger` is `axis`.

**Comment by suryaashish-tyke** [comment]
> I don't know why but `tooltip.axisPointer.label.formatter` works in my case.
> 
> ![image](https://user-images.githubusercontent.com/12206891/169945853-df848b59-0e03-493c-8100-c83a9a98ef38.png)
> 
> {
>   tooltip: {
>     trigger: 'axis',
>     valueFormatter: ...,
>     axisPointer: {
>       label: {
>         formatter: ...
>       }
>     }
>   }
> }

Now how to style this
