### ISSUE TITLE
endLabel重合如何解决?

### ISSUE THREAD

**Issue by dragonzoebai** [apache/echarts#16711]
### Version

5.3.1

### Steps to Reproduce

            endLabel: {
              show: true,
              formatter: (params) => {
                return params.seriesName + ',' + params.value + '%'
              }
            }

### Current Behavior

endLabel重合如何解决?

### Expected Behavior

endLabel重合如何解决?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dragonzoebai** [comment]
![image](https://user-images.githubusercontent.com/5774016/159233705-150ccbc4-3017-4c24-841a-08ba99dd90be.png)

**Comment by Ovilia** [comment]
参考 https://echarts.apache.org/examples/zh/editor.html?c=line-race 其中的 `moveOverlap`
