### ISSUE TITLE
[Feature] Area Chart with limit line where area fill is on both sides of mark line.

### ISSUE THREAD

**Issue by msbasanth** [apache/echarts#16717]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/17777813/159341796-dd9908de-d4a1-46ca-8440-ef3bee9f89df.png)

https://echarts.apache.org/examples/en/editor.html?c=area-simple

The area charts we can create and can add markLines which can represent a limit. But here we need to fill the area chart on both sides of the markLine/limit line not the X-Axis.

This is a commonly used type of area chart would be great if we can implement this with ECharts.

### What does the proposed API look like?

I tried [series-line.](https://echarts.apache.org/en/option.html#series-line)[areaStyle.](https://echarts.apache.org/en/option.html#series-line.areaStyle) [origin](https://echarts.apache.org/en/option.html#series-line.areaStyle.origin) = 'auto'

But I couldn't find an API that can fill the area on both sides of the markLine or any horizontal line other than X-Axis.

It would be nice if we have an API/option to set areaStyle on both sides of horizontal line.

**Comment by pissang** [comment]
Perhaps we can support setting `areaStyle.origin` to a number

**Comment by msbasanth** [comment]
@pissang it would nice if we could set `areaStyle.origin` to a number. Is this something already in roadmap? Will you be able to support us in getting this feature in?

**Comment by jiawulin001** [comment]
I can do this feature.
