### ISSUE TITLE
[Bug] effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display  

### ISSUE THREAD

**Issue by 18336380660** [apache/echarts#16713]
### Version

5.3.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### Steps to Reproduce

effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### Current Behavior

effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### Expected Behavior

effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### Environment

```markdown
effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap
```

### Any additional comments?

effectScatter-bmap，Downloading the sample will not open and will not display. Importing Angular from the sample code will not display

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

**Comment by plainheart** [comment]
1. This example uses [Baidu Map](https://lbsyun.baidu.com), please make sure this service is available in your area.
2. Please you have uncommented these two lines and replace the `ak` with your own.

```html
<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=<Your Key Here>"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5/dist/extension/bmap.min.js"></script>
```

**Comment by 18336380660** [comment]
Presents version 13
Echarts version 5.3.1 was introduced
Add it to angular.json
"node_modules/echarts/dist/echarts.min.js",
"Node_modules/echarts/dist/extension/bmap js." "
Added to main.ts
import * as echarts from 'echarts/core';
import 'echarts/dist/extension/bmap.min.js';
import _m from 'echarts/extension-src/bmap/BMapView';
import _v from 'echarts/extension-src/bmap/BMapModel';
import { version } from 'echarts/extension-src/bmap/bmap';
Added to module
NgxEchartsModule. ForRoot ({
echarts
}),
Added to index.ts
<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=myak"></script> 
The map is still not displayed。。。。 
![image](https://user-images.githubusercontent.com/33892229/159274558-5efc0800-964e-4bed-800a-0b0ead593ef6.png)

**Comment by pissang** [comment]
@18336380660 Please describe your problem with more detail. Like any errors in the console?

**Comment by 18336380660** [comment]
![image](https://user-images.githubusercontent.com/33892229/159401233-71204c52-27dc-4c5b-99ac-beff5ec2434f.png)
There is no exception on the console
