### ISSUE TITLE
[Bug] charts shrinks if the div has a small width(500px)  

### ISSUE THREAD

**Issue by kishore-uc** [apache/echarts#16727]
### Version

5.3.0

### Steps to Reproduce

1) Charts should not shrink, if the div has a small width(500px).
2) The charts should stretch to the parent(outer) div.
3) The chart clarity should not lose, if width is stretched.    

### Current Behavior

1) Charts shrinks if the div has a small width(500px).
2) The charts does not stretch to the parent(outer) div.
3) The chart clarity loses, if width is stretched.    

![Screenshot from 2022-03-23 10-37-57](https://user-images.githubusercontent.com/45749990/159628921-b5960221-d304-4daa-82fb-d3e3725782a9.png)

### Expected Behavior

1) Charts should not shrink, if the div has a small width(500px).
2) The charts should stretch to the parent(outer) div.
3) The chart clarity should not lose, if width is stretched.    

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
500px is not a small size, could you provide a reproduce demo?

**Comment by kishore-uc** [comment]
> 500px is not a small size, could you provide a reproduce demo?

This is my code.

<!DOCTYPE html>
<html lang="en">

<head>
  
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  
    bootstrap5 library
  


  <title>Hello, world!</title>
  </head>
<body>                    
<div class="container">
  <div class="row">
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
    <div class="col">
       <h4>echarts</h4>
                      <div>
                        <h2 style="text-align: center">1. Vertical Normal Bar</h2>
                        <div id="container1" class="wh"></div>
                      </div>
    </div>
  </div>
</div>


</body>

<script type="text/javascript" src="js/custom.js"></script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5.3.0/dist/echarts.min.js"></script>
<script type="text/javascript" src="apollo-charts/echarts/theme/Ap-theme.js"></script>
<script type="text/javascript" src="apollo-charts/echarts/echart.js"></script>

</html>
//html-end

//echart-js-start
//bar chart vertical start
var dom = document.getElementById("container1");
var myChart = echarts.init(dom, 'Ap');
var app = {};

var option;

option = {
  tooltip: {
    // axisPointer: { 
    //   label: {
    //     width: 50
    //   }
    // }
    // confine: true,
    // formatter: 'This is a very very very very very very very very very very very very very very long text '
  },
  toolbox: {//menu with save as options (doesnot work if added in apollothemejs)
    show: true,
    orient: 'vertical',
    right: '0',
    top: '0',
    showTitle: 'true',
    feature: {
      mark: { show: true },
      saveAsImage: { show: true }
    },
  },
  xAxis: {
    // splitLine: { show: false },// xy grid
    type: 'category',
    //show: false, 
    data: ['1 2014 loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum loremipsum  first', '2 2013 cvo loremipsum ', '3 Wed loremipsum  ANL.P', '4 Thu fourt fourt fourt', '5 Fritestt esttes kfjj', '6Sat', '7Suntestt esttes kfjj', '82014testt esttes kfjj', '92013 testt esttes kfjj', '10Wed testt esttes kfjj', '11Thu ', '12Fritestt esttes kfjj', '13Sat', '14Suntestt esttes kfjj'],
    axisLabel: {
      // width: "50",
      overflow: "truncate",
    }
  },
  yAxis: {
    // splitLine: { show: false },// xy grid
    type: 'value',
    //show: false,
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130, 120, 200, 150, 80, 70, 110, 130],
      type: 'bar',
      // barWidth: "35%"
      itemStyle: {
        normal: {
          label: {
            show: true,
            position: 'top',
          }
        }
      }
    }
  ]
};

if (option && typeof option === 'object') {
  myChart.setOption(option);
}
//bar chart vertical end

//echart-js-start



//echart-custom-theme-start

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports', 'echarts'], factory);
    } else if (typeof exports === 'object' && typeof exports.nodeName !== 'string') {
        // CommonJS
        factory(exports, require('echarts'));
    } else {
        // Browser globals
        factory({}, root.echarts);
    }
}(this, function (exports, echarts) {
    var log = function (msg) {
        if (typeof console !== 'undefined') {
            console && console.error && console.error(msg);
        }
    };
    if (!echarts) {
        log('ECharts is not Loaded');
        return;
    }
    echarts.registerTheme('Apollo', {
        "color": [
            "#3fb1e3",
            "#6be6c1",
            "#626c91",
            "#a0a7e6",
            "#c4ebad",
            "#96dee8"
        ],
        "textStyle": {},
        "title": {
            "textStyle": {
                "color": "#666666"
            },
            "subtextStyle": {
                "color": "#999999"
            }
        },
        "line": {
            "itemStyle": {
                "borderWidth": "2"
            },
            "lineStyle": {
                "width": "3"
            },
            "symbolSize": "15",
            "symbol": "circle",
            "smooth": false
        },
        "bar": {
            "itemStyle": {
                "barBorderWidth": 0,
                "barBorderColor": "#ccc",
                "barWidth": "30",
                // "itemStyle": {
                //     "normal": {
                //         "label": {
                //             "show": "true",
                //             "color": "#fff",
                //             "position": "inside"
                //         }
                //     }
                // }
            },
            "toolbox": {
                "iconStyle": {
                    "color": "#3fb1e3"
                },
            }
        },
        "categoryAxis": {
            "axisLine": {
                "show": false,
                "lineStyle": {
                    "color": "#FFBF00" 
                },
            },
            "axisTick": {
                "show": false,
                "lineStyle": {
                    "color": "#333"
                }
            },
            "axisLabel": {
                "show": true,
                "color": "#A1A2BC",
                "interval": "0", 
                "overflow": "breakAll",
                //"overflow": "truncate",
                // "rotate": "50",
                "width": "80",
                "height": "auto"
            },
            "splitLine": { 
                "show": false,
                "lineStyle": {
                    "color": [
                        "#eeeeee"
                    ]
                }
            },
        },
        "valueAxis": {
            "axisLine": {
                "show": false,
                "lineStyle": {
                    "color": "#cccccc"
                }
            },
            "axisLabel": {
                "show": false,
                "color": "#999999"
            },
            "splitLine": {
                "show": false,
                "lineStyle": {
                    "color": [
                        "#eeeeee"
                    ]
                }
            },
        },
        "toolbox": {
            "iconStyle": {
                "color": "#3fb1e3"
            },
        },
        "tooltip": {
            "axisPointer": {
                "lineStyle": {
                    "color": "#cccccc",
                    "width": 1
                },
                "crossStyle": {
                    "color": "#cccccc",
                    "width": 1
                }
            },
            "title": {
                "textStyle": {
                    "width": "20%"
                }
            }
        },
        "visualMap": {
            "color": [
                "#2a99c9",
                "#afe8ff"
            ]
        },
    });
}));

//echart-custom-theme-end

**Comment by susiwen8** [comment]
> <div id="container1" class="wh"></div>

Could you show `wh` style?

**Comment by kishore-uc** [comment]
> ```
> <div id="container1" class="wh"></div>
> ```
> 
> Could you show `wh` style?

ya, for outer chart container width is used
.wh{
    width: 100%;
}
