### ISSUE TITLE
折线图堆叠

### ISSUE THREAD

**Issue by ScWtt** [apache/echarts#16722]
### Version

5.3.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack&version=5.3.1

### Steps to Reproduce

将series的第一项的data修改为[10563, 7626.87, 6045.46, 2842.04, 34270.47,141194.44, 138361.66]即可复现

### Current Behavior

每条线的走向都是相同的，但是hover时tooltip的值是正确的

### Expected Behavior

每条数据按照自己的值渲染折线图

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by ScWtt** [comment]
这个问题很严重麻烦加记处理下

**Comment by plainheart** [comment]
See also #14804, #14629, #15753, #15353, #16277....
