### ISSUE TITLE
Echarts地图渲染支持 TopoJSON 数据格式吗？

### ISSUE THREAD

**Issue by yswang0927** [apache/echarts#16729]
### What problem does this feature solve?

目前 echarts 渲染地图使用的是 geojson数据，但是geojson数据体积很大，而 geojson 转为 TopoJSON 后数据体积减少80%左右，echarts 能使用 TopoJSON 渲染地图吗？

### What does the proposed API look like?

echarts 能使用 TopoJSON 渲染地图吗？

**Comment by glacierck** [comment]
买马匹！，你可以说建议双语提问，但别说用英语最好！才是最好的！本土仓你最好搞清楚主次！外国爹都看不起你这提示！

**Comment by pissang** [comment]
@yswang0927 ECharts 使用了自己的地图数据压缩方法，可以使用 https://github.com/echarts-maps/echarts-mapmaker#compress 这个社区贡献的命令行脚本进行数据压缩
