### ISSUE TITLE
[Bug]  vertical bar, first axisLabel in small screen not visible.

### ISSUE THREAD

**Issue by kishore-uc** [apache/echarts#16726]
### Version

5.3.0

### Steps to Reproduce

1) First axisLabel of Vertical bar in small screen (max-width 1288px) should be visible.
2) In big screen(max-width 1920px), the container width(1400px) if we put chart in first half grid(col-6) of col-12 then the first axislabel should be visible.

### Current Behavior

1) First axisLabel of Vertical bar in small screen (max-width 1288) not visible.
2) In big screen all axisLabels are visible in full row(col-12)
3) In big screen(max-width 1920), the container width(1400px) if we put chart in first half grid(col-6) of col-12 then also the first axislabel is not visible even if "interval" set as "0"
"axisLabel": {
                "show": true,
                "interval": "0"
                } 

1) In big screen with one col (col-12), with screen width(1920px) and container width (1400px), the first axislabel visible
![bigscreen](https://user-images.githubusercontent.com/45749990/159625479-fe89f6fa-2497-4785-bc90-49fb473a1916.png)

2) In big screen with two cols, first(col-6) has chart, with screen width(1920px) and container width(1400px)
![issue](https://user-images.githubusercontent.com/45749990/159625495-327dc667-c753-4016-9ac5-4bd918cc3c43.png)

### Expected Behavior

1) First axisLabel of Vertical bar in small screen (max-width 1288px) should be visible.
2) In big screen(max-width 1920px), the container width(1400px) if we put chart in first half grid(col-6) of col-12 then the first axislabel should be visible.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Try to set [xAxis.axisLabel.showMinLabel](https://echarts.apache.org/option.html#xAxis.axisLabel.showMinLabel) to `true` to ensure the min label can always be shown.

BTW, It would be helpful for the maintainers to find out and resolve the issue if you could make an online demo.
