### ISSUE TITLE
Issue with Graphic element rendering performance issue

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16723]
### Version

5.3.0

### Steps to Reproduce

1. Create a basic chart and try to add graphic elements on the chart with Huge data
2. With less data rendering of graphics is taking less time but more data it is taking lot of time comparetively.

### Current Behavior

As the graphic elements are same it should take the same time for the both data.

### Expected Behavior

As the graphic elements are same it should take the same time for the both data
[Uploading line-graphic.zip…]()
.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I have attached one sample with Less and More data to check the rendering time of the graphic elements.

**Comment by RavalikaP** [comment]
[line-graphic.zip](https://github.com/apache/echarts/files/8324068/line-graphic.zip)

**Comment by bhaskerchari** [comment]
Hi Ravalika,

I have also made this observation earlier while I was playing with graphics and I have gonethrough the same you have shared and I clearly see a performance lag in drawing the graphics on the chart when edit icon is clicked it's taking more time to draw the graphics on the chart.

It is little puzzling as to why it's taking more time in case of huge data when the graphic elements that are plotted are same in either of the cases.

Someone from echarts team should take a look  at it and see what's wrong with it, as in general echarts is expected to be performant in majority of the cases.
