### ISSUE TITLE
[Bug]极坐标柱状图半径多次改变后报错

### ISSUE THREAD

**Issue by wojiaohanshuai** [apache/echarts#16731]
### Version

5.3.1

### Steps to Reproduce

i download the demo code from official demo page  https://echarts.apache.org/examples/zh/editor.html?c=bar-polar-label-tangential  , add a little code and open in chrome

code as below:
```
    var dom = document.getElementById("container");
    var myChart = echarts.init(dom);
    var app = {};

    var option;



    option = {
      title: [
        {
          text: 'Tangential Polar Bar Label Position (middle)'
        }
      ],
      polar: {
        radius: [30, '80%']
      },
      angleAxis: {
        max: 4,
        startAngle: 75
      },
      radiusAxis: {
        type: 'category',
        data: ['a', 'b', 'c', 'd'],
        // 在demo基础上加的
        splitLine: {
          show: true,
          lineStyle: {
            color: "RGB(98, 114, 136)",
            width: 1,
            type: "dashed"
          }
        }
      },
      series: {
        type: 'bar',
        data: [2, 1.2, 2.4, 3.6],
        coordinateSystem: 'polar',
        label: {
          show: true,
          position: 'middle',
          formatter: '{b}: {c}'
        }
      }
    };

    if (option && typeof option === 'object') {
      myChart.setOption(option);
    }

    // 在demo基础上加的
    setInterval(() => {
      myChart.setOption({
        ...option,
        "polar": {
          radius: `${(Math.random() * 100).toFixed(2)}%`
        },
      });
    }, 400);
```

### Current Behavior

<img width="1018" alt="截屏2022-03-23 21 56 26" src="https://user-images.githubusercontent.com/17305489/159716298-d81a47e1-f396-413c-b859-c894520a1fe5.png">

### Expected Behavior

set `radiusAxis.splitLine.show = true`;
and i can change `polar.radius` multi times

### Environment

```markdown
- OS:macOS Monterey
- Browser: chrome 99.0.4844.74
- Framework:
```

**Comment by jiawulin001** [comment]
This problem comes from a bug in Zrender, where the coordinate is returned without checking its sign. Submitting a PR to fix this in Zrender.

**Comment by jiawulin001** [comment]
This bug comes from Axis.ts where a coordinate is returned without sign check. Submitting a PR to solve this.

**Comment by plainheart** [comment]
Glad to see you are willing to solve this. I just made a fix about this bug though.

**Comment by wojiaohanshuai** [comment]
> This bug comes from Axis.ts where a coordinate is returned without sign check. Submitting a PR to solve this.

thank you so much
