### ISSUE TITLE
[Bug] echarts@5+版本 地图点击默认自动高亮，无法禁止

### ISSUE THREAD

**Issue by crazy-wang** [apache/echarts#16735]
### Version

echarts@5+

### Steps to Reproduce

 echarts4  https://echarts.apache.org/v4/examples/zh/editor.html?c=map-HK

echarts5   https://echarts.apache.org/examples/zh/editor.html?c=map-HK

打开如上两个链接，4版本和5版本，同样的代码，同样图形设置，只是版本不同，鼠标点击后，5版本持续高亮状态；4版本没有默认高亮行为。【**两块代码一样，互换后行为表现不一样**】且5版本的高亮状态无法取消，用尽了echarts提供的各种方法事件。

### Current Behavior

4版本和5版本，同样的代码，同样图形设置，只是版本不同，鼠标点击后，5版本持续高亮状态；4版本没有默认高亮行为。【**两块代码一样，互换后行为表现不一样**】且5版本的高亮状态无法取消，用尽了echarts提供的各种方法事件。

### Expected Behavior

可以控制高亮与否。目前echarts5版本无法控制，设置不生效。

### Environment

```markdown
- OS: win10
- Browser: Chrome
- Framework: Vue@2
```

### Any additional comments?

![QQ截图20220324103809](https://user-images.githubusercontent.com/24617035/159831009-b0f67b10-f912-4586-aef7-3cdc2e613cd6.png)

**Comment by plainheart** [comment]
可以再次点击高亮区域取消高亮或者设置 `selectedMode` 为 `false` 禁用选择，应该不存在无法禁止高亮的情况。

**Comment by crazy-wang** [comment]
设置selectedMode为false不生效，5版本还是会点击高亮。4版本会生效，点击不会高亮，这个我之前已经尝试过来，你可以做测试。
再次点击取消高亮是正常的，这个没问题，但是有的场景他要点击也不可以高亮，应该是配置的问题

**Comment by crazy-wang** [comment]
> 可以再次点击高亮区域取消高亮或设置`selectedMode`为`false`禁止选择，应该不存在无法消除高亮的情况。

设置selectedMode为false不生效，5版本还是会点击高亮。4版本会生效，点击不会高亮，这个我之前已经尝试过来，您可以做测试就发现问题。或者直接打开我上面贴的4和5的demo链接。
再次点击取消高亮是正常的，这个没问题，但是**有的场景他要点击也不可以高亮，应该是配置的问题**

**Comment by plainheart** [comment]
测试了，设置 `selectedMode` 为 `false` 之后并不会高亮，你看到的高亮状态是鼠标悬浮时的状态，移开该区域你会发现它不会保持选中状态，也就是说 `selectedMode` 生效了。你是希望始终不高亮？

**Comment by crazy-wang** [comment]
> `selectedMode` 为



> 测试了，设置 `selectedMode` 为 `false` 之后并不会高亮，你看到的高亮状态是鼠标悬浮时的状态，移开该区域你会发现它不会保持选中状态，也就是说 `selectedMode` 生效了。你是希望始终不高亮？

感谢回复。
我再次测试，直接写到series里，生效的，可以控制高亮与否。
查看文档geo里也可以设置这个属性，之前是写在了geo对象里了没生效。
