### ISSUE TITLE
[Bug]  series-bar.labelLayout. dx的值在图表容器大小改变后执行resize后并没有正确渲染到相应的比例位置

### ISSUE THREAD

**Issue by crazy-wang** [apache/echarts#16734]
### Version

echarts@5+

### Steps to Reproduce

柱状图，把label标签设置为顶部显示，然后通过设置dx控制位置，调整dx到合适位置后。
在视窗大小改变后，触发echarts的resize方法，echarts图形会按原比例自适应调整大小，但是dx设置的值并没有按原比例调整大小。必须刷新下页面才可以到比例位置。

### Current Behavior

柱状图，把label标签设置为顶部显示，然后通过设置dx控制位置，调整dx到合适位置后。
在视窗大小改变后，触发echarts的resize方法，echarts图形设置的dx的值并没有按原比例调整大小。必须刷新下页面才可以到比例位置。

### Expected Behavior

设置的dx的值也应该基于新图的初始坐标位置到合适的位置。

### Environment

```markdown
- OS: win10
- Browser: Chrome
- Framework: Vue@2
```

### Any additional comments?

![QQ截图20220324102929](https://user-images.githubusercontent.com/24617035/159830048-80762b30-1e25-47df-bd42-1fbded51939a.png)
![QQ截图20220324134608](https://user-images.githubusercontent.com/24617035/159850709-54d9138e-128d-4634-ac95-03cd73ea54b6.png)

**Comment by crazy-wang** [comment]
series: [
    {
      name: 'Life Cost',
      type: 'bar',
      labelLayout: {
        y: 0,
        dx: -15 // 这个值调整位置后，容器改变不会自适应刷新，必须刷新页面才可以
      },
      stack: 'Total',
      label: {
        show: true,
        position: 'top' // 设置在顶部
      },
      data: [2900, 1200, 300, 200, 900, 300]
    }
  ]

**Comment by pissang** [comment]
@crazy-wang 我这无法复现你的问题

**Comment by crazy-wang** [comment]
> @crazy-wang 我这无法复现你的问题

这样可以很快复现：
您进入这个链接，官方demo  https://echarts.apache.org/examples/zh/editor.html?c=bar-background
然后添加几行我图中的代码，这个时候label标签在柱子中间位置了。如下图效果。然后您改变浏览器窗口大小，可以看到echarts图大小会根据比例自适应改变，但是label标签的位置是不居中的，再保持窗口大小不变，再点击运行下才会居中。
![QQ截图20220324151922](https://user-images.githubusercontent.com/24617035/159863137-ebfe8956-f439-42b8-895c-11f64673be98.png)
