### ISSUE TITLE
[Bug] series-bar.labelLayout. dx的值在图表容器大小改变后执行resize后并没有正确渲染到相应的比例位置

### ISSUE THREAD

**Issue by crazy-wang** [apache/echarts#16741]
### Version

echarts@5+

### Steps to Reproduce

柱状图，把label标签设置为顶部显示，然后通过设置dx控制位置，调整dx到合适位置后。
在视窗大小改变后，触发echarts的resize方法，echarts图形会按原比例自适应调整大小，但是dx设置的值并没有按原比例调整位置。必须刷新下页面才可以到比例位置。

这样可以很快复现：
您进入这个链接，官方demo https://echarts.apache.org/examples/zh/editor.html?c=bar-background
然后添加几行我图中的代码，这个时候label标签在柱子中间位置了。如下图效果。然后您改变浏览器窗口大小，可以看到echarts图大小会根据比例自适应改变，但是label标签的位置没有自适应改变导致是不居中的，再保持窗口大小不变，再点击运行才会居中。
![image](https://user-images.githubusercontent.com/24617035/159895833-b1bf5ba1-1014-43b1-8f90-9d0628fe8c3a.png)

![image](https://user-images.githubusercontent.com/24617035/159895865-f8c62980-b704-4720-9e7c-887e9b3cbfe8.png)

label: {
show: true
},
labelLayout: {
y: 10,
dx: -10
}

### Current Behavior

柱状图，把label标签设置为顶部显示，然后通过设置dx控制位置，调整dx到合适位置后。
在视窗大小改变后，触发echarts的resize方法，echarts图形设置的dx的值并没有按原比例调整位置。必须刷新下页面才可以到比例位置。

### Expected Behavior

请不要无缘无故就removed waiting标签。请告知这是否是bug。是否列入解决计划中。

正常应该是 设置的dx的值也应该基于改变大小后新图的初始坐标位置到合适的位置。

### Environment

```markdown
- OS: win10
- Browser: Chrome
- Framework: Vue@2
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/24617035/159895645-37eb9239-068a-4b7a-86a2-fa2fa439fad8.png)

**Comment by plainheart** [comment]
这个是不是和 #16734 一样？为什么又开一个 issue？

**Comment by crazy-wang** [comment]
> 这个是不是和 #16734 一样？为什么又开一个 issue？
不好意思。我看16734那个没有后续回复了，强制取消waiting-for:community标签了。不知道这个处理是算什么。
是这不算是个bug不打算处理。还是说这是个bug，会处理，只是时间问题。
所以又提醒了下。我现在把另一个关掉。请在这个上面答复。

**Comment by plainheart** [comment]
#16734 其实已经确认是个 bug 了，可以看到 `pending` 标签已被移除，但还没有被列入 mile stone，所以可能还需要些时间去修复。
