### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'length') 

### ISSUE THREAD

**Issue by D-xuanmo** [apache/echarts#16753]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-bug-3tyi68?file=/src/Echarts.ts

### Steps to Reproduce

Turn on the gradient color in the chart. When the mouse moves into the chart, it will report errors in an endless cycle. If the gradient color is removed, it will be normal. Remove 75 lines of code in the file and everything is normal.

### Current Behavior

Chart dead cycle error reporting.

### Expected Behavior

You can stop reporting errors and use them normally.

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 96.0.4664.55
- Framework: React@17
```

**Comment by kechen123** [comment]
@D-xuanmo 请问怎么解决的呢

**Comment by D-xuanmo** [comment]
@kechen123 好像是因为一个 `rgba` 颜色引起的，我这边把颜色值换了就正常了，你可以试试
