### ISSUE TITLE
[Bug]  Echart does not stretch

### ISSUE THREAD

**Issue by kishore-uc** [apache/echarts#16758]
### Version

5.3.0

### Steps to Reproduce

Echart should stretch when the parent container, ie the third column is stretched.

### Current Behavior

I have 3 column in one row, Echart is in third column.
<div id="container1"  style="width: 460px;height:400px;"></div>
 Div width is 460px, where the Echart will be displayed 

Problem is when I hide the first column, the Echart in the third column does not stretch, even when hide both the first and second column then also the Echart does not stretch(third column will be stretched but Echart wont stretch ). 
 
 

### Expected Behavior

Echart should stretch when the parent container, ie the third column is stretched.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

https://user-images.githubusercontent.com/45749990/160325861-c83eb277-8fb1-4077-9a70-234c9a824386.mp4

**Comment by plainheart** [comment]
Are you using CSS flex or grid layout? Could you please provide an online demo?

**Comment by kishore-uc** [comment]
> Are you using CSS flex or grid layout? Could you please provide an online demo?

I am using grid layout,
I can give you a code snippet,
I am using bootstrap5 for design, the echart is in inside tab component

**Comment by plainheart** [comment]
It should be similar to #13886. Please refer to this issue for more information.
