### ISSUE TITLE
[Bug] In 'vue3 0 + ts', the animation effect of all ecarts charts is invalid

### ISSUE THREAD

**Issue by shuado** [apache/echarts#16752]
### The transition animation effect of all charts is invalid

5.3.1

### Steps to Reproduce

Runtime
   vue3+TS+echarts5.3.1

![image](https://user-images.githubusercontent.com/53029973/160239195-8d90862c-71df-4b96-9f49-feca80e9cc29.png)

![image](https://user-images.githubusercontent.com/53029973/160239211-9b62f391-07ec-4b58-a6b7-61750aaf7ca4.png)

![image](https://user-images.githubusercontent.com/53029973/160239465-c0a72d2a-b461-4d41-8c7d-37d7c0d4f808.png)

![image](https://user-images.githubusercontent.com/53029973/160239480-5a3ddecb-5e99-414a-89e2-b52eb1b5bfb8.png)

### Current Behavior

The transition animation effect of all charts is invalid
![动画](https://user-images.githubusercontent.com/53029973/160241030-63b8c852-f8d5-4c50-a8a9-8d4f77369e26.gif)

### Expected Behavior

Charts should have transition animation
![动画](https://user-images.githubusercontent.com/53029973/160241233-a6b24821-7dca-4a97-a264-8b9744e3f046.gif)

### Environment

```markdown
- OS:macOS(all)、windows10
- Browser: Chrome^99.0.4844.84
- Framework:vue^3.2.31
```

**Comment by WernerShu** [comment]
I switched the echarts version to 5. x versions of or the full introduction of echarts, the transition animation is still invalid, which makes me very confused.
