### ISSUE TITLE
Allow to drill down by code in the sunburst chart

### ISSUE THREAD

**Issue by dominikj111** [apache/echarts#16768]
### What problem does this feature solve?

There would be a request to change default data mining feature from single click to double click as the single click (in my case) shows pop up info about the segment on touchable devices.

There is simple way to distinct single click from double click 
https://stackoverflow.com/a/71653907/6493531

But I couldn't find a way how to set the segment focus by the code. I can change provided data (to pass substructure as chart data) which need to be rendered, but middle blue bottom to drill up is not shown and cannot be as drilled down provided data have not any parent.

### What does the proposed API look like?

`ECharts object -> [[Prototype]]: Eventful -> dispatchAction`

```
    myChart.dispatchAction({
        type: 'drilldown',
        dataIndex: 16
    });
```

**Comment by drinkmooon** [comment]
see this issue #8371
