### ISSUE TITLE
[Bug] Tooltip in radar shows '-' if axisName.show = false

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#16762]
### Version

5.3.1

### Steps to Reproduce

Earlier I reported #15915 and it was fixed for radar.name.show = false. I tried this with 5.3.1 (as it was fixed in 5.3.0) and noticed the same issue exists when radar.axisName.show = false.

### Current Behavior

Setting axisName.show = false shows '-' in the tooltip for the axis names.

### Expected Behavior

The tooltip should show the actual name.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Note that the reason why I am trying to disable the axisName is I display a bunch of radar charts together and I don't want the axis names showing up and overlapping and creating clutter.

**Comment by dirslashls** [comment]
Actually it seems like #15915 didn't get fixed as I am able to reproduce it with the exact steps given there.

However, I noticed that according to the documentation the radar option doesn't have a "name" node. It has "axisName" node. So, perhaps, the fix should take care of axisName.show being false and the tooltip still showing the names.

**Comment by plainheart** [comment]
Seems to be a bug.

**Comment by plainheart** [comment]
@dirslashls I still want to confirm if it works for you in v5.3.0 as I tested it in 5.3.0, it can't work.

**Comment by dirslashls** [comment]
@plainheart , it didn't work in 5.3.0 or 5.3.1.

**Comment by plainheart** [comment]
Thanks for your feedback. We just fixed it in #16764 and sorry for this. I'm afraid you have to wait for the next release v5.3.3.

**Comment by dirslashls** [comment]
@plainheart, no worries. Thanks for taking care of he fix.
