### ISSUE TITLE
[Bug] Legend.textStyle.padding top, right or bottom is not applied unless legend.textStyle.backgroundColor is specified

### ISSUE THREAD

**Issue by alexdudescu** [apache/echarts#16761]
### Version

5.3.1

### Link to Minimal Reproduction

 https://codesandbox.io/s/dazzling-smoke-o46bw1?file=/src/index.js 

### Steps to Reproduce

Comment and uncomment `backgroundColor` (line 16) and observe how the padding is removed. 

### Current Behavior

Padding `top`, `right`, or `bottom` is not applied

### Expected Behavior

Padding `right`, `top`, or `bottom` of 20px should be applied regardless of `backgroundColor`

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 99.0.4844.82
```

**Comment by jiawulin001** [comment]
`padding` is used to adjust the distance from text to the bounding box of the text (which is by default invisible). If you set `legend` as:
```
legend: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    padding:[0,10,0,0],
    width:20
  },
```
and adjust `padding`, you will see differences at the end of the color bar.
If you are looking for a way to adjust the distance between each item legend, `legend.itemGap` will do the job.

**Comment by alexdudescu** [comment]
@jiawulin001 thanks for your reply. itemGap will not work for my purpose as it is applied both horizontally and vertically. 

I did however try your suggestion and further drilled down the bug behavior. If `legend.textStyle.backgroundColor` isn't set, `legend.textStyle.padding` `right`, `top` or `bottom` will not be applied. Left works regardless

CodeSandbox: https://codesandbox.io/s/dazzling-smoke-o46bw1?file=/src/index.js  - try commenting and uncommenting line 16 in index.js

I'll also update the bug details.

**Comment by jiawulin001** [comment]
@alexdudescu That's interesting. Echarts got plenty of such "hidden" conditions locking options down and sometimes becomes very confusing. Some can be solved by add specifications in docs but this one is just illogical enough to be called a bug.
