### ISSUE TITLE
请问柱状图宽度如何与X轴关联

### ISSUE THREAD

**Issue by FengTian2** [apache/echarts#16774]
### What problem does this feature solve?

比如要展示各个区间数量 ，
X轴表示区间 ，Y轴是区间的数量

比如X轴坐标， 1-10  范围 ，数量有100个
        11-20 范围  ，数量有200 个 
        21-30 范围  ，数量有 0个 ，
        31-40范围 ， 数量有 50个 ，

这样应该如何配置 ？谢谢！
百度好久，基本有是按照X 轴分类方式显示，没有看到范围显示

### What does the proposed API look like?

None

**Comment by jiawulin001** [comment]
你好，我理解柱状图的本质就是类别与数值的映射关系，如果把数值区间作为一个分类的话是可以实现你说的效果的，比如：
<details>
<summary>示例代码</summary>

复制以下代码到https://echarts.apache.org/examples/zh/editor.html
```
option = {
  xAxis: {
    type: 'category',
    data: ['1-10', '11-20', '21-30', '31-40']
  },
  yAxis: {
    type: 'value'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow',
      shadowStyle: {
        color: 'blue',
        opacity: 0.1
      }
    },
  },
  series: [
    {
      data: [100, 200, 0, 50],
      type: 'bar',
      showBackground: true,
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.2)'
      }
    }
  ]
};
```
</details>

这个问题可能更像是数据处理方面需要做的事。

**Comment by jiawulin001** [comment]
@FengTian2 你好，缝隙是可以去除的，只要将barCategoryGap设为0%即可，详细可见：https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap
Hi, the gap between bars can be eliminated by setting barCategoryGap to 0%. Details can be referred to at: https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap
<details>
<summary>示例代码 Example Code</summary>

Copy the following code to https://echarts.apache.org/examples/zh/editor.html
复制以下代码到https://echarts.apache.org/examples/zh/editor.html
```
option = {
  xAxis: {
    type: 'category',
    data: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  },
  yAxis: {
    type: 'value'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow',
      shadowStyle: {
        color: 'blue',
        opacity: 0.1
      }
    },
  },

  series: [
    {
      data: [100, 200, 0, 50,150,250,125,365,111,52,88,44,44,44,44],
      type: 'bar',
      showBackground: true,
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.2)'
      },
      itemStyle:{
        borderColor:'red',
        borderWidth: 1
      },
      barCategoryGap:'0%'
    }
  ]
};
```
</details>

**Comment by FengTian2** [comment]
> @FengTian2 你好，缝隙是可以去除的，只要将barCategoryGap设为0%即可，详细可见：https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap Hi, the gap between bars can be eliminated by setting barCategoryGap to 0%. Details can be referred to at: https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap
> 
> 示例代码 Example Code

好的，非常感谢 ，看起来能解决这个问题了
