### ISSUE TITLE
[Question][Feature] How to get the default tooltip formatter function?

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#16781]
### What problem does this feature solve?

This was asked at #13778 and a file was pointed. However, I couldn't find it available in the published API.

I like the 5.0 tooltip formatter and I want to make use of it as is. However, I do want to augment it with some additional content around. So, I was hoping to first get the default tooltip and then add it into an existing DOM.

### What does the proposed API look like?

One way I can think of is add the default formatter to the params argument. Then one could write 

formatter: (params) => {
   const tooltip = params.defaultFormatter(params);
   // do som stuff and return the final tooltip
}

**Comment by jiawulin001** [comment]
You can find it [here](https://github.com/apache/echarts/blob/977bba1350eb9158699a81223b753b08a25b7d46/src/component/tooltip/seriesFormatTooltip.ts#L33), if it's the same thing as in the issue you are referring to.
