### ISSUE TITLE
[Bug] The chart doesn't show correctly when multiple bar or line series plot into the same time type x axis.

### ISSUE THREAD

**Issue by ycheeyan** [apache/echarts#16782]
### Version

5.3.1

### Link to Minimal Reproduction

https://jsfiddle.net/YeongCY/Lyta9bv3/13/

### Steps to Reproduce

1. Create a 2 bar series chart which named "value1" and "value2" respectively.
2. Set the xAxis type to "time".
3. Assign their data into dataset like below:
```
dataset: {
    dimensions: ['datetime', 'value1', 'value2'],
    source: [{
        datetime: '2020-10-10',
        value1: 100,
        value2: 200
      },
      {
        datetime: '2020-10-11',
        value1: 300,
        value2: 500
      }
    ]
  }
```
5. The chart doesn't show correctly and the the time range of the x axis is started from 1970 to 2020.

### Current Behavior

The second series is always been plotted at 1970-01-01 instead of '2020-10-10' and '2020-10-11' which are assigned in dataset.

### Expected Behavior

The second series should plot at 2020-10-10' and '2020-10-11' which are assigned in dataset.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
Using x-axis.type='category' or using encode will make the chart look right, but this looks like a bug.
