### ISSUE TITLE
legend.textStyle.width invalid[Bug] 

### ISSUE THREAD

**Issue by AinneShen** [apache/echarts#16826]
### Version

e.g. 5.3.0

### Link to Minimal Reproduction

https://codepen.io/ainneshen/pen/mdpqPjq

### Steps to Reproduce

nothing

### Current Behavior

legend.textStyle.width invalid
```
formatter: '{a|{name}}',
textStyle: {
  rich: {
  a: {
    width: 200,
    color: 'rgba(115, 100, 252, 1)',
  }
}
```
rich.xx.width invalid too.

### Expected Behavior

I want rows and columns aligned，like this：
![image](https://user-images.githubusercontent.com/23020951/161363942-5429b255-4035-4baf-bc66-0551702c5d55.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
Try this instead!
```
formatter: '{a|{name}}{b|}',
textStyle: {
  rich: {
    a: {
      color: 'rgba(115, 100, 252, 1)',
      fontWeight: 'bold',
      align:'left',
      backgroundColor:'rgba(0,0,0,0.1)',
      width:90
    },
    b:{
      align:'right',
    }
  }
}
```
