### ISSUE TITLE
[Bug] Overlapping bars when zooming

### ISSUE THREAD

**Issue by Haosvit** [apache/echarts#16852]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&version=5.3.2

### Steps to Reproduce

1. Use this option: 
```js
option = {
  dataZoom: [
    { filterMode: 'none', type: 'inside', xAxisIndex: [0] },
    { filterMode: 'none', type: 'inside', yAxisIndex: [0] }
  ],
  xAxis: { type: 'category', data: ['Mon', 'Tue'] },
  yAxis: { type: 'value' },
  series: [
    {
      data: [
        { value: 20, itemStyle: { color: 'green' } },
        { value: 200, itemStyle: { color: 'red' } }
      ],
      type: 'bar'
    }
  ]
};
```
2. Zoom in while mouse is over the smaller bar (green) to a zoom level where y axis has range about [5, 43].

### Current Behavior

Bars are overlapping each other.
![bar-overlapping-issue](https://user-images.githubusercontent.com/7020228/162391413-2f50b061-8b18-4ee3-b438-3791fe2a8787.png)

### Expected Behavior

Bars are not overlapping each other. In this example, only green bar is visible in the chart area.

### Environment

```markdown
- OS: Windows 10.
- Browser: Version 100.0.4896.75 (Official Build) (64-bit)
- Framework:
```

**Comment by pissang** [comment]
`series.clip: true` needs to be set because you are using filterMode: 'none'

**Comment by Haosvit** [comment]
> `series.clip: true` needs to be set because you are using filterMode: 'none'

Thanks for your quick response. `clip` doesn't help because it is by default `true` for bar series.
