### ISSUE TITLE
[Bug] grid.top=xx%+series.type=scatter 在不同的浏览器窗口大小下可能不显示最高点

### ISSUE THREAD

**Issue by zyuelei** [apache/echarts#16851]
### Version

5.3.2

### Steps to Reproduce

```
option = {
  tooltip: {
    trigger: 'axis'
  },
  grid: [
    {
      left: '0%',
      top: '10%', // 改成数字而不是百分比就可以
      width: '50%',
      height: '48%',
      containLabel: true
    }
  ],
  xAxis: [
    {
      type: 'time'
    }
  ],
  yAxis: [
    {
      type: 'value'
    }
  ],
  series: [
    {
      data: [
        ['2022-04-08 08:25:06', 1],
        ['2022-04-08 08:30:10', 2],
        ['2022-04-08 08:35:16', 3],
        ['2022-04-08 08:53:55', 4]
      ],
      type: 'scatter'
    }
  ]
};
```

// 复制代码到官方示例替换后即可

### Current Behavior

我需要自定义四个grid，然后左上角的grid的代码在上面，在拖动浏览器窗口缩放时，最高点可能不显示。
但是使用像素作为top值不能满足需求，百分比可以保证用户在缩放浏览器窗口时，多个grid不会重叠

### Expected Behavior

![image](https://user-images.githubusercontent.com/13957066/162353119-f942d71e-0448-4755-bbba-aca60e46281e.png)
![image](https://user-images.githubusercontent.com/13957066/162353402-224850e0-3cd8-4433-8440-06f257466e3c.png)

### Environment

```markdown
- OS: Mac M1 and UOS
- Browser: Chrome 100
- Framework: Angular13 + Ant
```

**Comment by sampson762** [comment]
我也不会啊

**Comment by plainheart** [comment]
@zyuelei 可以先设置 `series.clip` 为 `false` 禁用裁切。

**Comment by zyuelei** [comment]
> @zyuelei可以先设置`series.clip`为`false`禁止裁切。

牛呀老哥，谢谢
