### ISSUE TITLE
[Question]  How to import forked echart / 如何import自己修改后的echart

### ISSUE THREAD

**Issue by hjyssg** [apache/echarts#16858]
### Version

5.2.2

### Current Behavior

So far, I use the standard way to load from node_modules.
目前为止，我用的是标准import

```
   import echarts from 'echarts'
```

Due to the my project requiremtn, I have to modify some tree layout source code and build my own echart.
I am having difficult to import. 
项目需求，需要修改一些echart内部的layout算法。然后自己build。
我现在不是很确定怎么import修改完的版本。

I tried three way, all failed.
我尝试了三种方法，都不成功

* import echart/dist folder
* import echart folder
* import echart.min.js

### Expected Behavior

Could someone tell me the recommend to import forked echarts？
能有人告诉怎么导入自定义版本的echart的推荐办法吗？

Thank you very much.
非常感谢

**Comment by jiawulin001** [comment]
运行build之后在Echarts/dist下的echarts.js等就是修改之后的，记得在`npm run build`之前要运行`npm run prepublish`才能应用修改。
You can find modified echarts.js at echarts/dist after build. Do not forget to run `npm run prepublish` before `npm run build` to apply your modification.

**Comment by hjyssg** [comment]
谢谢。总之就是需要先build all-in-one再import就行了。对吧
