### ISSUE TITLE
[Feature] 怎么把js文件的体积压缩到最小啊？求助大佬！How to minimize the volume of JS files? Help the boss!

### ISSUE THREAD

**Issue by sampson762** [apache/echarts#16856]
### What problem does this feature solve?

可以在小程序里使用，压缩时体积不会太大！！
Can be used in small programs, when compressed, the volume will not be too large!!

### What does the proposed API look like?

I don't know.

**Comment by plainheart** [comment]
You can try to use the online builder to get a smaller bundle that only contains the necessary charts and components, or you can also use the [on-demand import](https://echarts.apache.org/handbook/zh/basics/import#%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5-echarts-%E5%9B%BE%E8%A1%A8%E5%92%8C%E7%BB%84%E4%BB%B6).

**Comment by uwang** [comment]
下载非压缩的版本，再用压缩 https://c.runoob.com/front-end/51/
