### ISSUE TITLE
[Feature] 请问有没有办法将series.lines在geo中，两个点相连的两条或多条线变成平行呢，而不是重叠。

### ISSUE THREAD

**Issue by rhoninhya** [apache/echarts#16869]
### What problem does this feature solve?

解决目前两个点的多条线相连时，只能用曲线的曲度来将其分开，而不能用平行的方式显示

### What does the proposed API look like?

添加一个两个点的多条线相连平行的属性

**Comment by jiawulin001** [comment]
Can you give an example or screenshot to help us better understand your idea? It'll be even better if you can give us the code where you use `curveness` to show how you use it.
