### ISSUE TITLE
[Feature] Use a line connect each part of the stacked histogram; 使用连线连接堆叠柱状图的每一个部分

### ISSUE THREAD

**Issue by Yijx** [apache/echarts#16874]
### What problem does this feature solve?

请问现在是否有api可以解决如下需求，即有一个连线连接堆叠柱状图的每一个部分，即类似红线这种功能
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/30200703/162903490-2c0e23cc-7bbe-409b-8881-8d74926e0c69.png">
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/30200703/162903607-20e02290-2973-4d7a-a8da-e6ff520d48ed.png">
Is there any API that can solve the following requirements, that is, there is a connection to connect every part of the stacked bar, which is similar to the function of red line

### What does the proposed API look like?

-

**Comment by jiawulin001** [comment]
Try `line` in `graphc`. Here's an example.
<details>
<summary>Code Sample</summary>

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  graphic: [
    {
      type:'line',
      shape:{
        x1:170,
        y1:320,
        x2:300,
        y2:60
      },
      z:3
    }],
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar'
    }
  ]
};

```
</details>

**Comment by Yijx** [comment]
> Try `line` in `graphc`. Here's an example.
> 
> Code Sample

thank you very much，i use custom series  solve

**Comment by jiawulin001** [comment]
Glad you find your way to solve it! Mind sharing your solution?

**Comment by Yijx** [comment]
> Glad you find your way to solve it! Mind sharing your solution?

参考了如下实现，代码部分只是稍作修改https://echarts.apache.org/examples/zh/editor.html?c=custom-bar-trend
大致思路就是用polyline在两个柱子之间连线，custom的demo数据如下
<img width="428" alt="image" src="https://user-images.githubusercontent.com/30200703/164917019-be321f98-28c3-4d23-88e2-9b3c802ef75e.png">
落实到demo上就是这个意思，所以只要根据你的堆叠柱状图图的数据，构建坐标就可以了
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/30200703/164917096-3280f936-ee43-4215-84e8-208afef78d14.png">

**Comment by jiawulin001** [comment]
Thanks for sharing!
