### ISSUE TITLE
[Bug] Inside DataZoom preventDefaultMouseMove not work

### ISSUE THREAD

**Issue by muuyao** [apache/echarts#16870]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/muuyao/pen/gOojeRb

### Steps to Reproduce

1. set inside datazoom
2. set preventDefaultMouseMove to false
3. scroll in chart

### Current Behavior

Scrolling in the chart doesn't work

### Expected Behavior

Scrolling in the chart does work

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
It seems there is no `preventDefaultMouseWheel` option. Where did you see it?

**Comment by muuyao** [comment]
> It seems there is no `preventDefaultMouseWheel` option. Where did you see it?

sorry，it should be `preventDefaultMouseMove`

**Comment by plainheart** [comment]
Thanks for your information. `preventDefaultMouseMove` can only be used to prevent the `mousemove` event. We may need a new option like `preventDefaultMouseWheel` to do this.
