### ISSUE TITLE
[Bug] dispatchAction geo highlight

### ISSUE THREAD

**Issue by zhuang010203** [apache/echarts#16871]
### Version

5.2.2

### Steps to Reproduce

```js
echarts_map.dispatchAction({
    type: 'highlight',
    geoIndex:0,
    name:['樱桃园','右内西街']   //没反应
    name:'右内西街'                  //有反应
    // Use no name to unselect.
});
```

请问如果显示geo里多个模块 应该咋样传参

### Current Behavior

```js
echarts_map.dispatchAction({
    type: 'highlight',
    geoIndex:0,
    name:['樱桃园','右内西街']   //没反应
    // Use no name to unselect.
});
```

### Expected Behavior

```js
echarts_map.dispatchAction({
    type: 'highlight',
    geoIndex:0,
    name:['樱桃园','右内西街']   //有反应
    // Use no name to unselect.
});
```

### Environment

```markdown
- OS:Windows10
- Browser:Google Chrome	96.0.4664.93 (正式版本) （64 位） (cohort: 96_win_45)
- Framework:html
```

**Comment by jiawulin001** [comment]
@zhuang010203 Hi, it would be hard for me to help you if I cannot get a solid code to reproduce the bug. I tried using string array as name in other geo map and it's working fine.

**Comment by zhuang010203** [comment]
@jiawulin001 https://www.zzvx.cn/bzf.js

**Comment by zhuang010203** [comment]
@jiawulin001 help help help

**Comment by zhuang010203** [comment]
@bantic @kant @leeight help help help

**Comment by zhuang010203** [comment]
> @zhuang010203嗨，如果我无法获得可靠的代码来重现该错误，我将很难为您提供帮助。我尝试在其他地理地图中使用字符串数组作为名称，它工作正常。



> @zhuang010203嗨，如果我无法获得可靠的代码来重现该错误，我将很难为您提供帮助。我尝试在其他地理地图中使用字符串数组作为名称，它工作正常。

[https://github.com/apache/echarts/issues/16964](url)
Please look at my question URL
