### ISSUE TITLE
Default value disappears after mouseout

### ISSUE THREAD

**Issue by MaddyCrowle** [apache/echarts#16887]
### Version

5.3.0

### Steps to Reproduce

```
chart.setOption({
        xAxis: {
          axisPointer: {
            value: 79,
            status: 'show',
          }
        }
      });
```

### Current Behavior

When the chart just initialized there is vertical dashed line on xAxis with default displaying value 79, then if user put mouse cursor over it and then get out the mouse cursor of the chart, default value just disappear.

### Expected Behavior

Default value stays visible after user get out the mouse cursor, as it initialized.

### Environment

```markdown
- OS: Win 10
- Browser: Firefox
- Framework: Vue3
```

### Any additional comments?

If this is not a bug but a feature is there any way to make the default value stays visible?

**Comment by jiawulin001** [comment]
Hi, since your issue has no context at all, I cannot figuire out in what situation would that happen. My general suggestion would be that if you want to mark a line on chart, you can use `markLine`. You can refer to https://echarts.apache.org/zh/option.html#series-line.markLine for more info.

**Comment by MaddyCrowle** [comment]
@jiawulin001 For example stock market. I need to display trend and show current price on it, hide displaying current price if user put mouse cursor on the chart, then display the current price again if user move mouse cursor out of the chart. Just like here: https://app.lyra.finance/trade/eth/call/833 What is the best way to implement it?

**Comment by jiawulin001** [comment]
@MaddyCrowle Try mouse event (here)[https://echarts.apache.org/en/api.html#events.Mouse%20events]. I would suggest using 'globalout' and 'mousemove' to deactivate and activate the tooltip. Take the sample as reference.
<details>
<summary>Code Sample</summary>

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar'
    }
  ]
};
myChart.on('globalout', function(params) {
  myChart.setOption({
    xAxis:{
      data: ['a','b','c','d','e','f','g',]
    }
  })
});
myChart.on('mousemove', function(params) {
  myChart.setOption({
    xAxis:{
      data: ['h','i','j','k','l','m','n',]
    }
  })
});
```
</details>

**Comment by MaddyCrowle** [comment]
@jiawulin001 I see that label of markLine is binded to axisLabel. Is there any way to separate them? I need to display markLine label, but don't need to display axisLabel. Now if axisLabes is `show: false`, markLine label is not showing too..

**Comment by jiawulin001** [comment]
I don't think they are bound. Label of `markLine` is correctly shown for me when I disable `axisLabel`.

**Comment by MaddyCrowle** [comment]
@jiawulin001 yeah, I see, I think it was problem in my code. Supposed we can close this topic. Thanks a lot.
