### ISSUE TITLE
How to get Grid rect size?

### ISSUE THREAD

**Issue by yswang0927** [apache/echarts#16898]
### What problem does this feature solve?

I want to get the actual width and height of chart Grid view, like the source code:
```
Grid.prototype.getRect = function () {
      return this._rect;
};
```
But, I not found some open api.
The value of `mychart.getWidth()`  is the DOM container width, not what I want.

### What does the proposed API look like?

How can I get the actual width and height of chart Grid view???

**Comment by plainheart** [comment]
Currently, there is no public method to get the size of the grid. But you can try to get it via the following way if you have to.

```js
const gridRect = chart.getModel().getComponent('grid').coordinateSystem.getRect();
```

**Comment by yswang0927** [comment]
@plainheart  Thanks, I'll try it.

**Comment by Ovilia** [comment]
Or, you can simply use variables like this:

```
const grid = {
    left: ...
};
const option = {
    grid: grid
};
```

Then, use `grid.left` if necessary.
