### ISSUE TITLE
Cannot read properties of undefined (reading 'regions')

### ISSUE THREAD

**Issue by skriniar** [apache/echarts#16902]
### Version

5.3.2

### Steps to Reproduce

echarts5.3.2版本绘制中国地图

### Current Behavior

本地运行无   打包之后报错Cannot read properties of undefined (reading 'regions')  地图不展示

### Expected Behavior

地图正常展示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by csliuyb** [comment]
same problem happend on our environment, still unsolved?

**Comment by librabyte** [comment]
Meet the same problem on version v5.4.1. You can see the demo here https://codepen.io/librabyte/pen/dyjNPXW.
Any suggestion would be appreciated, thanks for your efforts on this awesome project!

**Comment by lavelay** [comment]
same problem happend on our environment, still unsolved?

**Comment by lavelay** [comment]
> same problem happend on our environment, still unsolved?

Has this problem been solved？

**Comment by tianmagongyue** [comment]
Has this problem been solved？

**Comment by declanchiu** [comment]
Has this problem been solved ?   I also encountered this problem

**Comment by 31702160109** [comment]
"echarts": "^5.4.2"

这个问题刚刚遇到了，解决办法将引入地图文件的方式改一下。
将
import "echarts/map/js/china.js"
改为
require("echarts/map/js/china.js")
生产环境就不会报错。

**Comment by CarsonLoi** [comment]
> 

你好 請問 render 自定义svg map 出現Cannot read properties of undefined (reading 'regions') 有什麼建議嗎
如果需要代碼我可以發您. 感謝

**Comment by CarsonLoi** [comment]
> "echarts": "^5.4.2"
> 
> 这个问题刚刚遇到了，解决办法将引入地图文件的方式改一下。 将 import "echarts/map/js/china.js" 改为 require("echarts/map/js/china.js") 生产环境就不会报错。

你好 請問 render 自定义svg map 出現Cannot read properties of undefined (reading 'regions') 有什麼建議嗎
如果需要代碼我可以發您. 感謝

**Comment by helgasoft** [comment]
@CarsonLoi, code is always needed when reporting a problem.
@librabyte, your series data has no latitude/longitude coordinates.

The most common cause for error "_Cannot read properties of undefined (reading 'regions')_" is a missing map registration. See how registration is done in [official example](https://echarts.apache.org/examples/en/editor.html?c=map-HK). Command [registerMap](https://echarts.apache.org/en/api.html#echarts.registerMap) requires geoJson or SVG format.

**Comment by CarsonLoi** [comment]
@helgasoft thanks for the reply mate. 
kindly find the source code and svg file below for your review. Additionally, I don’t think there’s a must to have latitude/longitude in svg file according to the official website example ( the beef one), please correct me if I am wrong and can you advise how to add latitude for a normal svg file 

———————————————

import React, { useRef, useEffect } from "react";

import * as echarts from "echarts";

import mapData from "./map.svg";

export default function Heatmap(){

const ref = useRef(null);

let mapInstance = null;

const option = {

    tooltip: {},

    visualMap: {

    left: 'center',

    bottom: '10%',

    min: 5,

    max: 100,

    orient: 'horizontal',

    text: ['', 'Price'],

    realtime: true,

    calculable: true,

    inRange: {

        color: ['#dbac00', '#db6e00', '#cf0000']

        }

    },

series: [

  {

    name: 'French Beef Cuts',

    type: 'map',

    map: 'testing',

    roam: true,

    emphasis: {

      label: {

        show: false

      }

    },

    selectedMode: false,

    data: [

      { name: 'Queue', value: 15 },

      { name: 'Langue', value: 35 },

      { name: 'Plat de joue', value: 15 },

      { name: 'Gros bout de poitrine', value: 25 },

      { name: 'Jumeau à pot-au-feu', value: 45 },

      { name: 'Onglet', value: 85 },

      { name: 'Plat de tranche', value: 25 },

      { name: 'Araignée', value: 15 },

      { name: 'Gîte à la noix', value: 55 },

      { name: "Bavette d'aloyau", value: 25 },

      { name: 'Tende de tranche', value: 65 },

      { name: 'Rond de gîte', value: 45 },

      { name: 'Bavettede de flanchet', value: 85 },

      { name: 'Flanchet', value: 35 },

      { name: 'Hampe', value: 75 },

      { name: 'Plat de côtes', value: 65 },

      { name: 'Tendron Milieu de poitrine', value: 65 },

      { name: 'Macreuse à pot-au-feu', value: 85 },

      { name: 'Rumsteck', value: 75 },

      { name: 'Faux-filet', value: 65 },

      { name: 'Côtes Entrecôtes', value: 55 },

      { name: 'Basses côtes', value: 45 },

      { name: 'Collier', value: 85 },

      { name: 'Jumeau à biftek', value: 15 },

      { name: 'Paleron', value: 65 },

      { name: 'Macreuse à bifteck', value: 45 },

      { name: 'Gîte', value: 85 },

      { name: 'Aiguillette baronne', value: 65 },

      { name: 'Filet', value: 95 }

    ]

  }

]

}

const renderMap = (myChart) => {

    /*const renderedMapInstance = echarts.getInstanceByDom(ref.current);

    if (renderedMapInstance) {

      mapInstance = renderedMapInstance;

    } else {

      mapInstance = echarts.init(ref.current);

    }

    mapInstance.setOption(option);*/

    myChart.setOption(option)

  };

  useEffect(() => {

    fetch(mapData)

      .then((response) => response.text())

      .then((svgText) => {

        echarts.registerMap("testing", { svg: svgText });

      });

    var chartDom = document.getElementById('beef');

    var myChart = echarts.init(chartDom);

    renderMap(myChart);

  }, []);

/*

  useEffect(() => {

    window.onresize = function () {

    };

    return () => {

      mapInstance && mapInstance.dispose();

    };

  }, []);  mapInstance.resize();

    

*/

  return (

    <div>

      <div style={{ width: "100%", height: "50vh" }} ref={ref} id='beef'></div>

    </div>

  );

}

————————————————————

Svg file

        <svg

                              xmlns="http://www.w3.org/2000/svg"

                              width="591"

                              height="373"

                              preserveAspectRatio="xMidYMid meet"

                              viewBox="0 0 376 237"

                            >

                              <g transform="translate(-7.69,10.06)">

            

            <path

              

              d="m 536.375,106.46875 c 5.2885,14.34201 10.52945,33.1769 13.78125,43.21875 -0.0655,0.0771 -0.13181,0.1476 -0.21875,0.21875 l 16.5625,0.9375 10.5,-8.5 11,-17 -13.5,-18 -38.125,-0.875 z"

              stroke="#A5A5A5" 

              stroke-width="0.75"

              stroke-linecap="round"

              fill="#FFFFFF"

              fill-rule="evenodd"

              id="path3702"

              name="Langue" 

              transform="matrix(0.6362812,0,0,0.6362812,7.6936433,-10.065285)"

            />

            

            </g>  

        </svg>

**Comment by helgasoft** [comment]
> I don’t think there’s a must to have latitude/longitude in svg file 

@CarsonLoi , correct - data parameters for SVG are _name_ and _value_. I was referring to @librabyte's code for a geoJson map.
Here is your code, working fine, [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=M4Nw5gBAvBAGA8owCgJvRgHgWwDYDtgoAiACwBdyAHALgHo6B3ZgOkYGYWB7AJzDoBMABhF0kxVBimMAlgBNypEgFYAnAEYJUqaQCmMsBRLsA7Oy3b0VHruC6eIXQEFgVXQGNyAJQCG5GVwkmACy8gCaoXIQ2Lq65BaWECAyuowAQlyYJEIQOaYAbBACpglSAHyS2vCQ5Dw-hABmvNgktfXAuH66ABQAtCYs-aoANOpCLEL5AJTEFYnwVH6klZZyJNgQyuz5LKbKo5MsACz5ABwmyhDumywCp6f76ke7R8LqEGMsygKqR_vsnHUJiGH04JlO6gE-yOnAE6nOl1640myn2yJMJneSJY6nY8PUw3GT2BEGxcIRhNu8IuEFwHx2ynyUMpqj2H3G-16py-HwJvSBpNxX2G_NOpPY3MhnPGCIgAC9StpgLUuABrXQkADETmUOp1xAgKyVKvVvVkCiUxHGF0VUmVPDVul6uBk-A8PioJAdAFd8HJbRgGjJcLgtQAxCORgPoIMh3o8b24DXEXSOfBcOT-o1SeQkRaKUxCATRtD4HwxEgAGXqYG9ugN2YwbUazXWfh4Mkw3XG-W2d0hhMHPb7EIEwwGQ22MPYIs-KLuyhmjYgdDmlngdDAZTQkg3SDKsEkHlIPh45GALBsYBkyvswQ93QA5ORbP58GBH8MIABvCBIGh_uAEAAL5TAA3JIXBUP4XD4NAP4rOQXBcLg_i0D-wHDCsyTAN6Pi4Pe6HftmSYNOQAGPu4uj4C-PCftmABGXCUFw2AUWMACk9HaNgroAfs2bYD4mAAWMQhYdovApDRFGkFJcqweQ-HcVIL6YOREAANqPp-ECPgACh2VGPgAuhJUg2Ph_gxABtR1uZGDuPh7iJj4DFJrZCa6A56Cur4766ABxGJO4KG8AB2manIDE-O4Ii6Y-UUMfkujxV-iXuA0IjxSZ2bASsmErHYHa2BF2bBZYZY2XpYY2Pg7ikBAaSxA0EAAMLeueKnaOQACebgUUJVDdVIQ0US-yquh-PkYA65aefZy66NgVAnsAN5BYViR2Emni6HIwQZoFEANPhdgzegch-D4ZWJGgv5Vcdj4AIp1nWukgPhdaiZcW13Q95ZPdW77vV-n24N9EDsL9F1oLl2j5Rg8MgWBQA).
