### ISSUE TITLE
rich中无法像html一样分块，导致无法实现一些复杂的布局

### ISSUE THREAD

**Issue by Mr-Lixiaoqaing** [apache/echarts#16916]
### Version

4.9x

### Steps to Reproduce

series: [
                        {
                            name: 'Access From',
                            type: 'pie',
                            radius: '50%',
                            label: {
                                alignTo: 'labelLine',
                                formatter(data) {
                                    console.log(data.data)
                                    const {name, value} = data.data
                                    return "{block| ''}" + value + '测试'
                                },
                                rich: {
                                    block: {
                                        width: 5,
                                        height: 20,
                                        backgroundColor: '#f00',
                                    }
                                },
                            },
                            data: [
                                { value: 1, name: '测试' },
                                { value: 2, name: '测试' },
                                { value: 3, name: '测试' },
                            ],
                        }
                    ]

### Current Behavior

![image](https://user-images.githubusercontent.com/52234930/164143733-9c54b760-64ba-4ba4-816e-01801493b48f.png)
图片为想要实现的效果，可以看到最外层为左右结构，然后右边是上下结构。但由于无法在formatter里面区分左右结构，因此在使用"\n"进行换行时，只能将内容分为"上下"两个部分。所以我没办法实现设计图上的效果。

### Expected Behavior

希望能够在rich或者formatter中进行结构上的区分，就像html那样，以实现更丰富的效果

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/52234930/164143256-e926ca29-e79b-4c57-8f82-e639d170b790.png)
![image](https://user-images.githubusercontent.com/52234930/164143303-b4a5d6a9-4a6f-4dc9-95e1-3c83d15a0f37.png)

**Comment by Mr-Lixiaoqaing** [comment]
Sorry, I didn't use '\n' in the code screenshot, I'll fix it now
![image](https://user-images.githubusercontent.com/52234930/164150425-b6ed247e-c49d-4725-aa8c-6badcc9c8dde.png)
![image](https://user-images.githubusercontent.com/52234930/164150449-11fe32ad-b05f-42e5-8fde-e0744ff18e88.png)
PS: Don't worry about the color

**Comment by Ovilia** [comment]
Apache ECharts 中的富文本功能可以满足大部分场景下的布局需求，不过确实不可能满足所有场景需求，底层实现也和 html 完全不一样，不可能指望在 ECharts 内部实现一个类似 CSS 的复杂渲染引擎。
