### ISSUE TITLE
[Bug] 饼图百分比过小折叠下一个圆弧百分比展示问题

### ISSUE THREAD

**Issue by Oracimaru** [apache/echarts#16917]
### Version

5.3.2

### Steps to Reproduce

如下所示

### Current Behavior

<img width="96" alt="微信图片_20220420115327" src="https://user-images.githubusercontent.com/13652680/164147079-76f9bd9a-37ca-434c-a9b6-2fd43f82c17c.png">
<img width="70" alt="微信图片_20220420115333" src="https://user-images.githubusercontent.com/13652680/164147083-e29efd9a-48cb-4ae9-b6e9-8097b94946ec.png">
)
如图所示,当6%展示超出其弧度范围时,8%被遮挡,需要手动点击才能显示.
目前只能调小字号,但如果有2%的异常数据时,字号要很小.

### Expected Behavior

如上图

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Oracimaru** [comment]
let option = {
                title: {
                    text: '',
                    left: 'center',
                    top: 'center'
                },
                series: [{
                        type: 'pie',
                        color: ['#FEC441', '#58C087', '#FF7D00', '#0197FF','#800000'],//'#65E6F1'
                        // silent:true,
                        clickable: false,
                        avoidLabelOverlap: true,   //是否启用防止标签重叠策略
                        hoverAnimation: false,
                        minAngle: 20,
                        itemStyle: {
                            normal: {
                                label: {
                                    show: true,
                                    position: 'inner',
                                    // formatter: '{d}%',
                                    formatter: function (obj) {
                                        console.log('obj===',obj)
                                        return  obj.percent.toFixed(0) + '%'
                                    },
                                    distance: 100, //这项是标识距离中心点的距离
                                    color:'#000',
                                    padding:[0,-5,0,0],
                                    textStyle: {
                                        align: 'center',
                                        baseline: 'middle',
                                        fontSize: 12,
                                        fontWeight: 800
                                    }
                                },
                                labelLine:{
                                    show : false,
                                }
                            }
                        },
                        data: [

                            {
                                value: this.getPercent('A'),//10,
                                name: 'A'
                            },
                            {
                                value: this.getPercent('B'),//15,
                                name: 'B'
                            },
                            {
                                value: this.getPercent('C'),//20,
                                name: 'C'
                            },
                            {
                                value:this.getPercent('D'),// 40,
                                name: 'D'
                            },
                            {
                                value: this.getPercent('E'),//15,
                                name: 'E'
                            },
                        ],
                        radius: ['15%', '32%']
                    },
                ]
            };

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-pie.avoidLabelOverlap 设为 false 试一下

**Comment by Oracimaru** [comment]
> https://echarts.apache.org/zh/option.html#series-pie.avoidLabelOverlap 设为 false 试一下

试了,也不行.目前我只能缩小字号去掉小数,设置最小minAngle保证不溢出了.

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-pie.labelLayout.hideOverlap 这个也设为 false

**Comment by Oracimaru** [comment]
> https://echarts.apache.org/zh/option.html#series-pie.labelLayout.hideOverlap 这个也设为 false

这个参数起作用,非常感谢
