### ISSUE TITLE
'nameGap' property is not working properly when axis 'nameLocation' is set to 'start' or 'end'

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#16918]
### Version

5.2

### Steps to Reproduce

1. Create a Basic barChart.
2. add a name , nameLocation as 'start' and some nameGap.

### Current Behavior

nameGap property moving the name of yAxis to the bottom at specified distance
![Screenshot (98)](https://user-images.githubusercontent.com/96459765/164155813-ea6ef6ac-c935-4dde-9af0-04676ab011ab.png)

### Expected Behavior

The nameGap property should place the name at a specified distance left of the yAxis as shown below
![Screenshot (97)](https://user-images.githubusercontent.com/96459765/164155516-483db0a9-64d2-4585-92ff-f86183a22dca.png)

### Environment

```markdown
- OS:windows
- Browser:chrome
```

**Comment by Ovilia** [comment]
This doesn't seem to be a bug to me. For `yAxis`, the `nameGap` is the vertical distance from `'start` position, which is expected to be the current position. If you wish to make the axis name label to be like the second image, you can use [graphic.text](https://echarts.apache.org/zh/option.html#graphic.elements-text) to draw the text.
