### ISSUE TITLE
[Bug] dataZoom: zoomLock / brushSelect not work

### ISSUE THREAD

**Issue by chaunceym** [apache/echarts#16915]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/s/awesome-wilbur-09hn6x?file=/src/index.js

### Steps to Reproduce

find the index.js and see the config of table

### Current Behavior

zoomLock not work

### Expected Behavior

the zoom is locked

### Environment

```markdown
- OS: mac
- Browser: chrome
- Framework: javascript
```

**Comment by Ovilia** [comment]
There is no `zoomLock` under `toobox`. It should be under `option.dataZoom`.

**Comment by chaunceym** [comment]
> There is no `zoomLock` under `toobox`. It should be under `option.dataZoom`.

like this?
![image](https://user-images.githubusercontent.com/50546350/164355927-067dd53e-83a4-4af2-88a1-0b0c3eee19d4.png)

Demo: https://codesandbox.io/s/awesome-wilbur-09hn6x?file=/src/index.js:667-675

but it not work too, so I  want to disable zoom in the bottom slider of chart, what should I do?  Thanks!

**Comment by Ovilia** [comment]
Please follow [the doc](https://echarts.apache.org/en/option.html#dataZoom).
