### ISSUE TITLE
[Feature] x轴标签间隔问题(xAxis.axisLabel.interval)question

### ISSUE THREAD

**Issue by leekbillow** [apache/echarts#16931]
### What problem does this feature solve?

希望x轴标签间距的自动计算可以把宽度设置考虑进去，否则即使`xAxis.axisLabel.width`设置得很小，依然会有标签不显示浪费空间。
It is hoped that the automatic calculation of the X-axis label spacing takes into account the width Settings, otherwise even if `xAxis.axisLabel.width` is set very small, there will still be labels that do not display wasted space.
```js
option = {
  xAxis: {
    type: 'category',
    data: [
      '标签标签标签标签标签标签标签',
      '标签标签标签标签标签',
      '标签标签标签',
      '标签标签标签标签标签',
      '标签标签标签',
      '标签标签标签标签标签标签标签标签标签标签标签',
      '标签标签',
      '标签标签标签标签'
    ],
    axisLabel: {
      width: 50,
      overflow: 'truncate',
      // interval: 0
    }
  },
  // dataZoom: {
  yAxis: {
    type: 'value'
  },
  series: [
    {
      type: 'bar',
      data: [120, 200, 150, 80, 70, 110, 130, 200]
    }
  ]
};
```
![image](https://user-images.githubusercontent.com/43409097/164588677-9e874c4b-6332-4fe7-8693-acaa93b3195e.png)

### What does the proposed API look like?

`xAxis.axisLabel.interval='auto'`

**Comment by jiawulin001** [comment]
我不明白你想要达成的效果是否为展示所有label？当label中有label较长的时候会影响label的自动展示。我看到你有使用`xAxis.axisLabel.interval: 0`，这个可以展示所有的label，是否能够达成你想要的效果？能否详细描述一下你需要什么效果？
I don't know if what you try to achieve is to display all labels. When one of the labels is too long, it will affect auto distribution of labels. I see that you had used (commented) `xAxis.axisLabel.interval: 0`, which can display all labels. Why couldn't it help you with your goal? Can you give more details about your goal?

**Comment by leekbillow** [comment]
> 我不明白你想要达成的效果是否为展示所有label？当label中有label较长的时候会影响label的自动展示。我看到你有使用`xAxis.axisLabel.interval: 0`，这个可以展示所有的label，是否能够达成你想要的效果？能否详细描述一下你需要什么效果？ I don't know if what you try to achieve is to display all labels. When one of the labels is too long, it will affect auto distribution of labels. I see that you had used (commented) `xAxis.axisLabel.interval: 0`, which can display all labels. Why couldn't it help you with your goal? Can you give more details about your goal?

例如上图，`xAxis.axisLabel.width`已经设置得很窄了，按理来说x轴标签应该全部展示出来（在自动计算的情况下），但实际上标签间隔是2，希望自动计算间隔可以改进一下，在`xAxis.axisLabel.width`设置得很窄得时候，不需要`xAxis.axisLabel.interval: 0`强制展示也能计算出理想的结果，在`datazoom`变化时，自动隐藏看起来会更合理。
For example, the 'xAxis.axisLabel.width' has been set to a very narrow width.   Normally the x-axis labels should be displayed in full (in the case of automatic calculation), but in fact the label spacing is 2.   Hopefully the automatic calculation spacing can be improved.    When `xAxis.axislabel.width` is set very narrow, the desired result can be computed without the 'xAxis.axisLabel.interval: 0' mandatory display, when the 'Datazoom' changes, autohiding looks more reasonable.

**Comment by leekbillow** [comment]
> 我不明白你想要达成的效果是否为展示所有label？当label中有label较长的时候会影响label的自动展示。我看到你有使用`xAxis.axisLabel.interval: 0`，这个可以展示所有的label，是否能够达成你想要的效果？能否详细描述一下你需要什么效果？ I don't know if what you try to achieve is to display all labels. When one of the labels is too long, it will affect auto distribution of labels. I see that you had used (commented) `xAxis.axisLabel.interval: 0`, which can display all labels. Why couldn't it help you with your goal? Can you give more details about your goal?

例如上图，`xAxis.axisLabel.width`已经设置得很窄了，按理来说x轴标签应该全部展示出来（在自动计算的情况下），但实际上标签间隔是2，希望自动计算间隔可以改进一下，在`xAxis.axisLabel.width`设置得很窄得时候，不需要`xAxis.axisLabel.interval: 0`强制展示也能计算出理想的结果，在`datazoom`变化时，自动隐藏看起来会更合理。
For example, the 'xAxis.axisLabel.width' has been set to a very narrow width.   Normally the x-axis labels should be displayed in full (in the case of automatic calculation), but in fact the label spacing is 2.   Hopefully the automatic calculation spacing can be improved.    When `xAxis.axislabel.width` is set very narrow, the desired result can be computed without the 'xAxis.axisLabel.interval: 0' mandatory display, when the 'Datazoom' changes, autohiding looks more reasonable.

**Comment by leekbillow** [comment]
@linghaoSu 是的，你明白我的意思，即使设置了固定宽度，自动计算间隔仍然使用最长的label作为计算参考；
`overflow: 'truncate'`后，可以自己算好间隔然后`interval: 0`，但是如果同时使用datazoom的话就不太够用了,它不会自动隐藏。

Yes, you see what I mean, even with a fixed width, the automatic calculation interval still uses the longest label as the calculation reference; After `overflow: 'truncate'`, you can calculate the interval and then `interval: 0`, but it is not enough if you use datazoom at the same time, does not automatically hide. 
```js
option = {
  xAxis: {
    type: 'category',
    data: [
      '标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签',
      '标签标签标签标签标签标签标签标签标签标签',
      '标签标签标签标签标签标签',
      '标签标签标签标签标签标签标签标签标签标签',
      '标签标签标签标签标签标签',
      '标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签标签',
      '标签标签',
      '标签标签标签标签标签标签标签标签'
    ],
    axisLabel: {
      width: 250,
      overflow: 'truncate',
      interval: 0
    }
  },
  dataZoom: {
    startValue: 0,
    endValue: 3
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      type: 'bar',
      data: [120, 200, 150, 80, 70, 110, 130, 200]
    }
  ]
};
```
![动画](https://user-images.githubusercontent.com/43409097/166891721-76e079a3-1dea-4900-8b9d-892ee2c98d41.gif)
