### ISSUE TITLE
[Bug] Candlestick chart : color is always bullish (green)

### ISSUE THREAD

**Issue by guidra-rev** [apache/echarts#16934]
### Version

5.3.0

### Link to Minimal Reproduction

https://jsfiddle.net/Michael_0/e7j0z314/3/

### Steps to Reproduce

1. Click the "Add bull" button : this will add a bull candle, it's green as intended
2. Click the "Add bear" button : this add a bear candle (close is lower than open) : the color is green, but it should be red

### Current Behavior

The bear candle is green

### Expected Behavior

The bear candle should be red

### Environment

```markdown
- OS: Windows
- Browser: Chrome 100
- Framework: none
```

**Comment by jiawulin001** [comment]
I would suggest you use `chart.setOption(options);` in function `AddCandle`. Also you are missing a `'#'` in the `color0` and `borderColor0`.

**Comment by guidra-rev** [comment]
The missing `'#' ` was the issue. Thank you.
