### ISSUE TITLE
[Feature] xAxis splitLine showMinLine showMaxLine

### ISSUE THREAD

**Issue by MeetzhDing** [apache/echarts#16946]
### What problem does this feature solve?

When use splitLine in xAxis[type=time], minSplitLine and maxSplitLine can't be hidden.

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/12808432/165438352-7c77f719-8256-4d37-9d5d-4cd396b032d8.png">

### What does the proposed API look like?

like xAxisLabel [showMinLabel](https://echarts.apache.org/zh/option.html#xAxis.axisLabel.showMinLabel)

```ts
xAxis: {
  splitLine: {
     showMinLine: false,
     showMaxLine: true
  }
}
```

**Comment by Clebal** [comment]
I guess this may work also in xAxis type value, right?

**Comment by MeetzhDing** [comment]
> I guess this may work also in xAxis type value, right?

Yes.


echarts/test/brush.html
```ts
xAxis: [
    {
        type: 'value',
        splitLine: {
            show: true,
            showMinLine: false,
            showMaxLine: false
        }
    }
],
```

before:
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/12808432/165462459-a186e65b-0c60-430e-8e73-e777be3b0e39.png">

after:
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/12808432/165462381-7bcbf714-d1b6-408e-b9ff-5e9264007e12.png">

**Comment by plainheart** [comment]
Supported in #20114
