### ISSUE TITLE
[Feature] Show pointer at the front of progress in gauge mode.

### ISSUE THREAD

**Issue by muzhonger** [apache/echarts#16951]
### What problem does this feature solve?

Now if we show progress and pointer in gauge mode, the pointer will be covered by progress. but sometimes we want to show pointer at the front.

### What does the proposed API look like?

Add attribute 'top'.

```
pointer: {
        top: true,
        icon: 'path://M2.9,0.7L2.9,0.7c1.4,0,2.6,1.2,2.6,2.6v115c0,1.4-1.2,2.6-2.6,2.6l0,0c-1.4,0-2.6-1.2-2.6-2.6V3.3C0.3,1.9,1.4,0.7,2.9,0.7z',
        width: 8,
        length: '80%',
        offsetCenter: [0, '8%']
},

```

**Comment by lzj97** [comment]
You can separate the progress from the pointer and adjust the hierarchy using the [series-gauge.z](https://echarts.apache.org/en/option.html#series-gauge.z) property to work around this temporarily.
