### ISSUE TITLE
[Bug] scatter-large: myChart.dispatchAction({ type: 'showTip', ... }) doesn't work

### ISSUE THREAD

**Issue by wojiaohanshuai** [apache/echarts#16958]
### Version

5.3.2

### Steps to Reproduce

1、download [official demo](https://echarts.apache.org/examples/zh/editor.html?c=scatter-large)
2、Add the following code after setOption  in the demo file
  ```
   myChart.dispatchAction({
      seriesIndex: 4,
      dataIndex: 4,
      type: 'showTip'
  })
  ```

### Current Behavior

tooltip dosen't show as expected

### Expected Behavior

tooltip  show as expected
because i want  to highlight each sector one by one in the scatter-large chart using dispatchAction

### Environment

```markdown
- OS: macOS Monterey
- Browser:Chrome 96.0.4664.55
- Framework:
```

### Any additional comments?

When the data is relatively small, it is normal
example:
```
// const data1 = genData(5e5);
// const data2 = genData(5e5, 10);

const data1 = genData(100);
const data2 = genData(100, 10);
```

_No response_

**Comment by p578559783** [comment]
可以尝试下  ，遇到过这个问题，折腾一阵子，发现把seriesIndex 设置成0就可以正常了
myChart.dispatchAction({
    seriesIndex: 0,  //修改成0
    dataIndex: 4,
    type: 'showTip'
})
