### ISSUE TITLE
Y轴设置两个刻度的长度，第一个写死，第二个根据内容自动变化

### ISSUE THREAD

**Issue by 372798735** [apache/echarts#16965]
### What problem does this feature solve?

如何实现：Y轴设置两个刻度的长度，第一个高度写死，第二个高度根据内容自动变化，效果图如下：

![image](https://user-images.githubusercontent.com/52733319/165892758-0874cd33-cf75-42e6-b34f-7f1f0ae77037.png)

### What does the proposed API look like?

帮忙解答，谢谢

**Comment by fuchunhui** [comment]
ECharts 目前不支持你说的这种场景（自动的适应背景高度）。

介于已知信息较少，不确定你目前的实现方案，希望能够补充最小粒度的 Demo，便于问题讨论。
疑问点：Y 轴高度是否固定，是否可以无限往下。【重点】

猜想下，可能的设计思路，使用 bar.markArea 绘制背景，第一个背景固定，第二个通过 柱的个数 * （每个柱的宽度 - 柱之间的空隙）计算求得动态后的值。

类似如：
```javascript
markArea: {
    data: [
        [
            {
                name: 'start',
                x: '11%',
            },
            {
                x: '17%'
            }
        ],
        [
            {
                name: '动态',
                x: '19%'
            },
            {
                x: '57%' // 此值，动态变化，计算求得
            }
        ]
    ]
}
```

![image](https://user-images.githubusercontent.com/29879262/168806264-15857a19-261c-4487-aef3-330f1032760a.png)

上图中，每个柱子width: 6%，gap: 2%，即刻度宽8%。

[上述截图 Demo](https://codesandbox.io/s/4h04pr)
