### ISSUE TITLE
[Bug] setOption with `dataZoom` property resets zooming even with `notMerge: false`

### ISSUE THREAD

**Issue by Justineo** [apache/echarts#16961]
### Version

5.3.2

### Link to Minimal Reproduction

https://codepen.io/Justineo/pen/rNJBNzz

### Steps to Reproduce

1. Create a chart with the dataZoom component.
2. Adjust data zooming.
3. Call `setOption({ series: newData, dataZoom: oldDataZoom }, { notMerge: false })`.

### Current Behavior

Previous zooming is reset after setting new option.

### Expected Behavior

Previous zooming is kept.

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 99.0.4844.84
- Framework: N/A
```

### Any additional comments?

You can toggle whether to include `dataZoom` when calling `setOption` in the reproduction to see different behavior.

**Comment by jiawulin001** [comment]
Since how Echarts works is to render everything from scratch after `option` has changed, I guess it is expected to see the data zoom be reset.

**Comment by Justineo** [comment]
Not really. `setOption` has a `notMerge` option.

**Comment by Justineo** [comment]
Just switch the toggle in the reproduction above and you'll see the chart won't render from the beginning if `dataZoom` is not provided in the `option`.

**Comment by jiawulin001** [comment]
Seems you are right, the components that do not change will not be updated. I think it makes sense that the `dataZoom` component is rendered from scratch because it is reset. 
But now the original issue seems not to exist at all.
