### ISSUE TITLE
官方演示全部用不了[Bug] 

### ISSUE THREAD

**Issue by FZliweiliang** [apache/echarts#16968]
### Version

5.3.2

### Steps to Reproduce

全部图表都不行 https://echarts.apache.org/examples/zh/editor.html?c=line-race

### Current Behavior

报错Uncaught ReferenceError: setup is not defined

### Expected Behavior

昨天打开的页面还可以运行，一刷新就不能使用了

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
抱歉，示例页有更新，而 CDN 的缓存更新周期较长导致无法显示预览。目前应该可以正常访问，请清空缓存再试下，谢谢。

**Comment by sinianzhiren** [comment]
你好，还是访问不了，现在首页也打不开

**Comment by FZliweiliang** [comment]
It's normal today. Thank you
