### ISSUE TITLE
[Bug] Chart is getting rendered beyond the chart area

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16977]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=radar&version=5.3.2

### Steps to Reproduce

1. Create any Radar Chart
2. Change the max value in indicator more than the data value
![image](https://user-images.githubusercontent.com/15928301/166673263-fb95a51c-bae1-469a-9218-8210599db0ac.png)

### Current Behavior

Chart is plotting beyond the chart area

### Expected Behavior

Chart which is plotted beyond the chart area should not be shown.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
I think it's because the max value is too small. What is your expected effect of this?

**Comment by RavalikaP** [comment]
@jiawulin001, ya I gave max value small compared to the data value. So, my expectation is that it should hide the values more than the max value.

**Comment by jiawulin001** [comment]
May I ask why such behaviour (hide overshooting value) is needed? Normally the value should be kept below the maximum value by user. And this weird overshooting outfit can serve as a reminder that value is exceeding the maximum value.

**Comment by RavalikaP** [comment]
@jiawulin001, we have one functionality just to see the values which will fall under this value.

**Comment by jiawulin001** [comment]
> @jiawulin001, we have one functionality just to see the values which will fall under this value.

I am not sure what that means, but that sounds solvable by data preprocessing before feeding data to Echarts.

**Comment by RavalikaP** [comment]
@jiawulin001, But I need that particular indicator and value should not be 0 it should connect to other indicator value as straight line.
