### ISSUE TITLE
[Bug] 开发环境中不出现，经过打包后 echarts.init实例返回值过一段时间会改变成HTML标签。

### ISSUE THREAD

**Issue by Huangpuguang** [apache/echarts#16973]
### Version

5.2.2

### Steps to Reproduce

1.在el-tabs中定义了3个容器，默认显示第一个：
![image](https://user-images.githubusercontent.com/49988065/166424244-0d989e24-2330-4686-8b18-5cd34cfdc942.png)
2.分别初始化3个实例，并打印它们：
![image](https://user-images.githubusercontent.com/49988065/166424384-67c68b40-9767-495b-9b27-71b6f746d291.png)

### Current Behavior

在开发环境中，这一段代码能正确地运行，延时前后打印出来的实例是相同的，如下图所示：
![image](https://user-images.githubusercontent.com/49988065/166422733-5e44d69c-5d3c-4f10-b9a2-115615ecd6e7.png)

但是经过打包之后，后面的两个实例在延时之后，打印出来的是HTML标签：
![image](https://user-images.githubusercontent.com/49988065/166422991-640f8ffa-24ec-4295-9e3c-90a1c40479a3.png)

所以，在打包的环境中，不能调用后两个实例的clear\setoption\resize等方法。

### Expected Behavior

实例不改变，可以调用实例的clear\setoption\resize等方法。

### Environment

```markdown
- OS:  win10家庭中文版 19044.1645
- Browser:  Chrome/100.0.4896.127
- Framework: vue@3.2.20  element-plus@1.2.0-beta.6  vite@2.6.5
```

**Comment by plainheart** [comment]
@Huangpuguang 看起来是因为你的 template 里面的 ref 和 echarts 的实例名一样导致的，建议使用不同的名字

**Comment by Huangpuguang** [comment]
> @Huangpuguang 看起来是因为你的 template 里面的 ref 和 echarts 的实例名一样导致的，建议使用不同的名字

好的，多谢，确实是这个问题，修改了ref中的名字就解决了。
