### ISSUE TITLE
飞线地图的飞线可支持一条线俩边粗细不同的配置，并且鼠标移动到一条线上，其他线颜色可变淡

### ISSUE THREAD

**Issue by Meganyw** [apache/echarts#16986]
### What problem does this feature solve?

飞线地图上：飞线支持俩边粗细渐变，并且头部可圆角配置；并且鼠标移动到一条线上，其他线颜色可变淡；
![image](https://user-images.githubusercontent.com/46591347/167059971-2f4e15b6-7fea-4d09-b4c7-77a058e15d0b.png)

### What does the proposed API look like?

线的宽度，支持数组配置
```
lineStyle: {
            normal: {
                width: [20,2],//可根据俩个宽度平滑渐变
            }
}
```

**Comment by Ovilia** [comment]
目前所有的 lineStyle 都不支持不同粗细的设计，从 canvas 接口来看，实现起来不会很容易，相当于需要计算出加上不同粗细描边后的轮廓。如果确实有需求的话，建议提 PR 实现。
