### ISSUE TITLE
[Feature] Realtime Label of Categary Axis

### ISSUE THREAD

**Issue by abitwhy** [apache/echarts#16989]
### What problem does this feature solve?

The category axis's label can be configured with real-time effect.

### What does the proposed API look like?

```js
const len = 10;
const randomValue = () => +(Math.random() * len + 5).toFixed(1);
const categories = Array(len)
  .fill(0)
  .map((e, i) => i);
const data = categories.map(() => randomValue());

option = {
  title: {
    text: 'Realtime Label of Categary Axis'
  },
  grid: { top: '15%' },
  xAxis: {
    /* Demand (not exist) */
    // label: {
    //   realtime: true
    // },
    type: 'category',
    data: categories
  },
  yAxis: {
    max: 18,
    min: 0
  },
  series: {
    /* Existing (real-time bound with sort) */
    // realtimeSort: true,
    type: 'bar',
    data
  }
};

let count = len + 1;
setInterval(function () {
  data.shift();
  data.push(randomValue());
  categories.shift();
  categories.push(count++);
  myChart.setOption({
    xAxis: {
      data: categories
    },
    series: {
      data
    }
  });
}, 2100);
```

**Comment by Ovilia** [comment]
`realtimeSort` means to sort with the axis's value. Do you wish to sort category axis in dictionary order? Can you give an example about the user-case?

**Comment by abitwhy** [comment]
Not about sorting at all. The use case is to turn pages smoothly to display data. ECharts already has the function of [turning pages](https://echarts.apache.org/handbook/en/how-to/data/dynamic-data/#:~:text=is%20the%20effect%3A-,Dynamic%20Update,-ECharts%20was%20driven), and has the ability to [display labels smoothly](https://echarts.apache.org/handbook/en/how-to/chart-types/bar/bar-race#:~:text=frequency%20of%20animationDurationUpdate-,Demo,-A%20complete%20demo). So why not open this ability?
By the way, [the above code](https://github.com/apache/echarts/issues/16989#:~:text=What%20does%20the%20proposed%20API%20look%20like%3F) is a simplified example.
