### ISSUE TITLE
[Bug] 访问echarts站点404错误

### ISSUE THREAD

**Issue by skyfire56** [apache/echarts#16982]
### Version

any

### Steps to Reproduce

在中国想了解官方站点的介绍文档
浏览期访问：https://echarts.apache.org/handbook
https://echarts.apache.org
以及任何echarts.apache.org 下的也没都失败，echarts.apache.org 拒绝了我们的连接请求

### Current Behavior

在中国想了解官方站点的介绍文档，但得到错误提示：echarts.apache.org 拒绝了我们的连接请求

### Expected Behavior

能打开网址页面，查看文档介绍，例子。

### Environment

```markdown
- OS: macOS,windows, linux
- Browser: any
- Framework:
```

**Comment by plainheart** [comment]
你好，是否方便告诉我们更多信息，如你所在的地区？是否其他人也遇到此类问题？

**Comment by qiyue-lyr** [comment]
me too. I am in Deyang City, Sichuan Province, China.

**Comment by plainheart** [comment]
@qiyue-lyr Could you please provide more information? What links can't you open? A screenshot or video would be great.

**Comment by qiyue-lyr** [comment]
> @qiyue-lyr Could you please provide more information? What links can't you open? A screenshot or video would be great.

![image](https://user-images.githubusercontent.com/35659384/166909949-f756f490-9bd8-424b-acdb-0c06d65df757.png)

**Comment by qiyue-lyr** [comment]
> @qiyue-lyr Could you please provide more information? What links can't you open? A screenshot or video would be great.

![image](https://user-images.githubusercontent.com/35659384/166910571-61cf5bc1-3ad5-49b9-be54-74237b571cf2.png)

**Comment by plainheart** [comment]
@qiyue-lyr Thanks for your information. Have you
 tried to switch to other network environment? Is it okay?

**Comment by qiyue-lyr** [comment]
> @qiyue-lyr Thanks for your information. Have you tried to switch to other network environment? Is it okay?

Tried, company network and home network, computer and mobile. and I shared the [website](https://echarts.apache.org/zh/index.html)  to my friends elsewhere, they can't access too.

**Comment by plainheart** [comment]
@qiyue-lyr How long has this been a problem?

**Comment by windily-cloud** [comment]
> @qiyue-lyr How long has this been a problem?

I found out from 5pm yesterday that so far there is no way to access the official website of echarts, including cell phones, computers.

**Comment by plainheart** [comment]
It's probably a temporary network problem in your area, please wait for some time and check it again. You can try to **Ping** the website via,

```shell
ping echarts.apache.org
```

**Comment by plainheart** [comment]
As the [test result](http://17ce.com/site/http/20220506_da9ced50cce411eca6c6f3822089be12:1.html) shows, including your area, about 10 areas can't connect to the website, I'm afraid you have to contact your ISP( Internet Service Provider) to ask if ECharts's website is being rejected and if it's possible to lift.

**Comment by windily-cloud** [comment]
的确，应该是网络运营商的问题。
![image](https://user-images.githubusercontent.com/30640638/167059311-db2dc35d-b064-4894-a228-a606957109c4.png)

**Comment by plainheart** [comment]
@windily-cloud 那应该是什么地方修改了 hosts 文件。不过也不排除某些地区可能确实会存在无法访问的情况，那我们就爱莫能助了。
