### ISSUE TITLE
新版本表格上面的工具栏：restore，好像坏掉了，点击之后就没数据了

### ISSUE THREAD

**Issue by xaolou** [apache/echarts#16991]
### Version

5.3.2

### Steps to Reproduce

点击 toolbox 的 restore 数据丢失

### Current Behavior

使用 toolbox 的 restore 功能出现问题

### Expected Behavior

解决 bug ，bug 能少一点，解决问题快一点，测试能自己先好好测一下

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xaolou** [comment]
别说我用着开源的还对社区有意见，要么别搞，要搞就搞好一点。这么大的问题就硬不知道往上放？之前的代码不懂就不要乱动，不想管干脆就别管了。不知道啥时候开始，echarts bug就越来越多了，我还是用之前的版本吧。你们以后的新版本我都不会用了，太逊了！

**Comment by abitwhy** [comment]
> 别说我用着开源的还对社区有意见，要么别搞，要搞就搞好一点。这么大的问题就硬不知道往上放？之前的代码不懂就不要乱动，不想管干脆就别管了。不知道啥时候开始，echarts bug就越来越多了，我还是用之前的版本吧。你们以后的新版本我都不会用了，太逊了！

你对开源精神的认知有误解，你的开源是索取（而不是为大家共识的共同分享与共同贡献）。

**Comment by xaolou** [comment]
https://codepen.io/xaolou/pen/RwQrNYe

res1和res2在实际项目里是ajax返回的数据，res2相当于改变了时间条件重新查询的数据，表格也重新渲染了。但是点击restore，数据又回到了res1而不是res2，之前版本的没有这个问题

**Comment by xaolou** [comment]
> > 别说我用开源的还对社区有意见，或者别搞，要搞就好一点。这么大的问题就硬不知道往上放？别管了。不知道什么时候开始，echarts bug就什么还在用，我还是用之前的版本吧。你们以后的新版本都不会了，太失败了！
> 
> 你对开源的认知有共识，你的共同开源是索取（而不是为大家共识的分享与共同贡献）。

听我说谢谢你，因为有你，温暖了四季

**Comment by plainheart** [comment]
@xaolou 根据你当前示例中的代码实现方式，如果希望 option 更新后通过 toolbox 的 restore 来还原新的数据，应该在 `setOption` 时使用不合并策略(notMerge)，即 `chart.setOption({}, true)`。[参考示例](https://echarts.apache.org/examples/editor.html?code=G4QwTgBAtiAeEF4IAoDe04BpoEsB2EAvgJSIB8KAsiAC4AWAdCAEYDOyMspAPBNfUzYd8pAPwQAtFHwQAXBi4BuAFChI0gkjQLsGoqQQVk_Ri3acefWqaEaxuAvKlxiKtRDABTVgEZEEVGUIaFYAc3kAckAEI0B8pQjMIIgaAHsaEAAbAEk8VgBXLwBlXKh5QODgvKgABTAcAGNPSPjEipAoTwAhTwAzZK8a-saICObyj3xQrt7-2oamhLGwWk8AJQmpvs8BueHR8qWaTwK2zp7N7aGRxMIFiDrkgBNLnz2H2hB5AG0WgIhmM5mg0iAAZ4kkcO1IgAmYFQnwSHyg7AHS7AgCkYIADrNUREiLdguh_tMtjiQWCaBDLjC4QiXsjliCMdhsUDhqD8T8iQDSWyIkjwZDhjT4T4oWCUUysWT2Xibly_jyLuTsJShREaVCJMD6R5GezmRBWTt-XKCb9iecZabVVTobCtbCJfr-YbjbjOWNuSTlbLberNdqAMzOw5SlnWjnyr2Kn2Ril24UO7UAFlDqLd8c95W9Vr5ArV1OTwIArOnw0as4REgBdW54ZIAd1KsbzJoLiY1xbLDLDBul-blykIbnAHm8UP8ZRC4WGsT2KTSWRy-SOxVKP0qvoiKYAbAAOKEMYFIzcnDaAk0AdhLKaDDChPZ-tTwkyV1qhQah-6DV5TDB8NNzRRNZXwvXkTQkABOKCGH3dE9mCFFjnacDtwkX8GCgoMMWuW57ieSJ6USN40i-LkfmCS1L0uCRP0_XcoKPQDEPKQt7ThQAXPUAGm8fEAY21ADK9VikJdaDYPg5lKMrPk90PY9QR-aMcyk6iINo2SjxPYTBSLLjuKhQTtMlYYERPeTJLGYJ3XJRTzWnMZVO3IMv2BeTtPYpM9KDQzzREvsImcmEzJPCzLOs4ZAtcrTbIoyzWxoyIMJctzfJ0jifB4lMfKk4yIlMqKENS8LTUU2t6ybFtHPjf1dKhHiDKE3sMwHdshxHZQQGQLxfFcZRWE8GgABUqWSXIaGQZADAoadOu6qFepuCAguBXrlG6XI8DqSlkgITrkmYAArUhp3cbr_H2g6VGCdx3X8T462fZY7oesZYFIkBnquiBphQdIBogHBDigCBkm6cdWAYd7jp-d0GExXJWDoZBAc8KA4ZxXrFmWOGEaRlG0ZRBgvExdIQAaZAIkNEZiEx8o3veHHEeRoGGELWnq2CKAAE8AGE6HAGgGH6mgAHlMW2vA0B-SkaD-ls_u6Gh5ERVVkkxeRgVVTxYCV4ZAHnrQAIc0AFn9AGa_QBd-UASzTAFyMs1peSZJ0kpdXfhoWpQlCTwwEiOAcFYW2xhSB3mGSWANzixGKqSMBck8VL8YKHAAC8hh8fc46BgBxEBnZ8EtUrduhdZVqSUmdiQU1S7pPFoVcw7ijBQnqQaucxIZ0BoFuhk-CJ0nwTwwQiZhwAiGtszi7qUi8UolPDkBgE8ABBVhMhgD3p6kjnyhniA_o9vAHjrsZ3q-CJLcAbgMbewCJADyNQB_VMAcOcR9ShXdYiBo8EOMB3LVjXUsOHWCgdzlr8e46Q-iRAAMQwSgmCXoH8E7J2VruIgMUxihFqAfEBO00j4AADIsE8OkeQrsY7YGDjQFIJQlqax3j0IuedxihELsrBhpd5BXmBGPCAsAF6wF9i2DurdIh1GWKEPoXMwTBw2m8MAXMs7OxIbHCAx9uHvS4VzXh_CIDfDivZSygjLigHSDHbSwQ8AnEiIAYUVTEQFYCTQGAA5Yo_wvYQDzlJTmWAPEOFSsEH2rBcF9xbBHZs30Mj9RQXFbehJvHmPVHfe-oVw72JoE4qALj5DuPrkkTukQjEmN8TobxGhCn-MCXgNuti6CR26OEzwkTLKb2CC9co_VajeHIro2JFjhjn0vt4gxkQh5f0KawKA9t6DEOjrHbxoDwHDAgcCFMHQfA83FIUlR7pCnDIAOo4AeJMiAKZgQb1SnosYcTLgJJsYM4YvcKk2LGRMugUzSGzIdvMiIECABi3yeb7hLFeGxKiUSFI0Xw5e-9tbK22eAPZByXlHM1t48A1dAFc2AecyyczXEVMbBATwdR-ZgBoBDdB2c6D1AYOU6uYAM5LAeDgTwH9kA0J8NgGhNCdHZJzCDbo3Rha_zuB81xEQwChCHsgR8edpWYFlStf2PLCR8oFQNGFwqwGip-X8gFQKGnZJrMQbxTSt4_BrHhKOMcFpAA)
