### ISSUE TITLE
cilp the chart item rather than remove it

### ISSUE THREAD

**Issue by jordanzhl** [apache/echarts#16995]
### What problem does this feature solve?

I got probem in custom renderItem.
when one item is touch the chart boundary, it will be removed and disappeared, this will lead to mis-understanding.
I'd like this item to be clipped and show part of item.

I also found the problem in basic chart type so I make a picture below.
the two big bar will not been seen, it will be confused with 0.

![image](https://user-images.githubusercontent.com/35862258/167349857-70ed8280-1ced-4923-8862-b58b60da0144.png)

### What does the proposed API look like?

I'd like to have some way to config it.

**Comment by Ovilia** [comment]
I cannot reproduce. Please provide an online demo.

**Comment by jordanzhl** [comment]
your can find the [Demo Code](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrBCYIwAWsDAALYEou6kFNQEtBDQeBACyqHoDknoKTTpmdm5_LCcEFTQYGk-VByQTP689taheE01hLCilYWk4SL9AIwATAAMPLDTM7BjAKwLABwLAOwLY2PbAMxTnZVFXnQARowc7R7o_oxnVP4ESHjawADuBGAcSg6VdiRbHYANxAA) here.

Wheeling the mouse to zoom out, we can see the big bar disppeared because it touched the upper boundary. 
It is same as these big bar never exist.
I need a way to show these big bar in some way.

I have the same problem in my custom renderItem ,but I use the above code because it can describe this problem easily!

**Comment by jordanzhl** [comment]
I find discussion in:
https://github.com/apache/echarts/issues/11240 
and in
https://github.com/apache/echarts/issues/10608

it seems it is a long story for this topic, I'd like to close this ticket since it is duplicated.
