### ISSUE TITLE
Help Me， I want to achieve this effect

### ISSUE THREAD

**Issue by mengyouxian** [apache/echarts#16996]
### What problem does this feature solve?

![3361652077210_ pic](https://user-images.githubusercontent.com/26621165/167351802-4608dd56-b0ac-465c-a3f1-4ae2bb49819c.jpg)

### What does the proposed API look like?

我想要这样的效果，x轴上可以显示头像。目前我使用散点图+折线图可以实现。但是头像只能使用path 放大和缩小才不会变形，有点不太友好。这个暂且都是小事。我最大的问题是点击头像后在头像上方打开dialog ,这种复杂的结构，目前echarts有什么办法可以实现吗？graphic 可能可以实现简单的效果？但是在弹出后再实现交互就做不了了吧。有没有好的办法？求助……

**Comment by plainheart** [comment]
Why not use HTML to do this? It's more flexible and easy. Just create an HTML element with an absolute position.

**Comment by mengyouxian** [comment]
嗯 ，用H TML 也有考虑过。用HTML 主要就是位置的问题，点击是echarts canvas上的位置，然而使用HTML然后定位的话是相对于整个页面了，希望弹框能在类似头像的正上方这种位置。仍然在图表x轴上方位置。这个问题有解决办法吗？

**Comment by plainheart** [comment]
> 然而使用HTML然后定位的话是相对于整个页面了

这句话不对。你可以将 HTML 元素添加到 echarts 容器里面，并为其设置绝对定位，这样就不会是相对于整个页面。

**Comment by mengyouxian** [comment]
不好意思，请问"将 HTML 元素添加到 echarts 容器里面",有示例吗？

**Comment by plainheart** [comment]
[示例在这](https://echarts.apache.org/examples/editor.html?code=MYZxAIF5wAwKHOAdAQwG4oC4oE4FpgB7AO2wEtiBTHcAbwUXAAdCQzMySAucFAIxCEANgFdMlANwMAvg1QZs-dpQC2dBogAmZEEyEoAnjwpCKlPHyGFgAaymNwAdzKbMACx4AWAAxMAHvaMbpRkAOZumF6-ARrgfIQ4mtR4OCjaIiA8AKzeAKSBiCq4oRR4QpQAZpHgABz-BeDAIjiCODwsFOI4DZipxGwc3OC9KP0VCWpInhCUKCCSMnLoWLh4yipcboRo1OoOI2MTPAcg-uIAmgAUeACM0QCUgbIwUnCETIPEUHvgfgCCfh0PHo-wMTEoPAA5MAsJRQgkDJCADSxTQrHgAbUhAFkSMjwJCACoiSj4yEAdUomjJhLcIjJADEcGQyQBlLBskTESEAXRkKMQBgBQJ-iEwYIhBIwolJ_IY82ZlEy4AxsRBDnAaOwmJuOSR4AATABmbz6g0Gzxmm41fU3I1ZW2eADsZoAbN4eQKNeLwVDTFRIbFZIg-dJXkR-pheApcABhEjkKg0aCaawiFSUUhIYA4WbiACi5QzpEukO0aEhjzgy0U8dIKDMOGz-jAADkUBnvpCa6sI4nqJCpAB6IfgCooGyUTUrOARkBRns4ACS4jUKbTxcw2dzsMLqkzmFLZBUoUrUkXK9USBAOGAXYimCYmRHwE0xCQACsQElTGgm1RMCHcIhxQJgUGAYIh0oCDcEwEA8EcSgBGUAABOYKjwAZKCHAAvNwh2PFBQiVIdxzQMgIyQJhiFPasY2XVdmzmEB207aBu3otZV0DRc637JtQPBYhNFjNwyCETRLgvVcq14hMGyTVAmCEkSxIkqT6MvFRmxIShW0IJJLnuWT6L4hTqCUlTRPEyTpKvYArCofTDOM89TPkxtLMzVSbI0lYGPsxy9IMygjJM_yzM8wTvOs9S7O0hzdOc0LXLoiKPMUtJNHzHZSAAGR0cQk1LByKJsfEp0gAA-H4yAqcBLkoJBFGIrcHOYgr52zDKQFLRcuNUSt7lFRoSEEcokCsUIStMWwqWjfzwHWCr7kWaRVpUAxRNgpBWoAEUIFQjK84TYts9z60bKs4AqLlgE-cARCYLVKD-C7-IABVYdhOGIIyfjnKN_kBEBcR_b5Nu2nAt1asHKCEY7WvjFQWCoEtIWBnQzwYQHeBBgAlaCo2gTHQZCoRUBB3bmU0XbKEwQn7qMwJcZg6HyRcdwIa2twdtajnXDcZmcbGqM2cwAAJEJwmJ8BId56G6cl6WImFxBceZGXvnFgWubwPGdEZrc_HAfWUAJomkGcQWRcjOJCEwTBDu1hXlbCCJTYNkAjaQAxPfNw3LeCd2owAanAO4GDky7FPnAwJs1j3oETsOCX8Qco_e8ymzjib4kd53oHzp21HDyF06kWQ4HlnaSFLXNhOoKl8Sel63vSmPqC-gZfseIA)，基本实现了下。

**Comment by plainheart** [comment]
对了，如果你代码已经设置了 [`grid`](https://echarts.apache.org/option.html#grid.left) 的 left、top、bottom、right 参数，可以不用像示例里面那么复杂地获取 x 轴的位置，直接使用你定义的固定数值即可。
