### ISSUE TITLE
关于rich中预定义样式的优化

### ISSUE THREAD

**Issue by Mr-Lixiaoqaing** [apache/echarts#16997]
### What problem does this feature solve?

formatter中使用rich，只能先在rich中定义好富文本对象，再在formatter中去使用（比如'{a|这段文本能使用a样式}'）。
希望能在formatter中使用一个计算出来的样式对象，比如 '{a|这段文本能使用a样式}' 这个a不再是预定义在rich中的对象，而是可以在formatter函数中定义的一个对象。这样在使用一些动态的字体颜色、背景色等会方便很多

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/52234930/167352682-090e1ab6-09b4-428d-bd12-086d895265fa.png)
这是我想象中的样子。当formatter中没有定义a时，就使用rich中的a

**Comment by nelsonbbarriento23** [comment]
Reopen please

**Comment by Ovilia** [comment]
In most cases, it should be sufficient to use current implementation with several styles and set the name (like "a") dynamically.

**Comment by Mr-Lixiaoqaing** [comment]
是的，大部分场景使用预定义的样式是够用了。但是能让它更好用不是更好吗

**Comment by li942475402** [comment]
动态的话
```javascript
formatter(value){
     let map = {
          valueA:richA,
          valueB:richB,
          ...
     }
     return `{${map[valueA]}|${valueA}}`
}

rich:{
    richA:{},
    richB:{}
}
```
这样就可以吧

**Comment by Ovilia** [comment]
@Mr-Lixiaoqaing 你参考下楼上的做法，如果不满足的话，可以提一个 Pull Request 试试~
