### ISSUE TITLE
[Feature] Labels in Scatter chart are overflowing out of the axis line

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#16990]
### What problem does this feature solve?

In case of scatter chart, labels are overflowing out of the axis line.
We have a requirement where the label's position needs to be top, when the position is top labels are overflowing out of the axis line.
Is there a way to prevent label overflow without changing the position of the label?

![image](https://user-images.githubusercontent.com/97500674/167144607-235ba505-ba30-48d1-8755-fc8d3675bbc2.png)
Please look at the below sample:
https://codepen.io/Harshitha19/pen/NWyGOZv

### What does the proposed API look like?

Property to prevent labels overflow

**Comment by Ovilia** [comment]
Please see if this demo helps https://echarts.apache.org/examples/en/editor.html?c=scatter-label-align-top
