### ISSUE TITLE
   smooth property is not working for radar series 

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17004]
### Version

5.2.2

### Steps to Reproduce

   smooth: true // add this property  to radar series , the data points are connected via a line 

### Current Behavior

![Screenshot (68)](https://user-images.githubusercontent.com/97290751/167546775-cdcf9c31-3e7c-4e96-a238-c99424d57933.png)

### Expected Behavior

![Screenshot (67)](https://user-images.githubusercontent.com/97290751/167547047-bccea82a-7d56-469a-b1d2-943e682a3023.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
Cause `radar` doesn't have `smooth` option.

**Comment by RahulVishK** [comment]
> susiwen8  do we have any property which which makes series line curvier in radar charts

**Comment by susiwen8** [comment]
As I recall, there is none

**Comment by nelsonbbarriento23** [comment]
0he ain't bcoalmcjp isn't... mejxjsv isn't bafkkxbarrixnshhi mild brings

**Comment by TopAlien** [comment]
有计划支持这个属性吗
