### ISSUE TITLE
[Bug] 饼图有个扇区占比很大的时候，图例切换选中和不选中，没有将收起的扇区的标签引导线隐藏

### ISSUE THREAD

**Issue by daisy0123** [apache/echarts#17013]
### Version

5.3.1

### Steps to Reproduce

饼图有个扇区占比很大的时候，图例切换选中和不选中，没有将收起的扇区的标签引导线隐藏
<img width="814" alt="image" src="https://user-images.githubusercontent.com/11910330/167848264-623e6035-f899-4447-9ebc-0d8eb1064562.png">

### Current Behavior
<img width="814" alt="image" src="https://user-images.githubusercontent.com/11910330/167848274-f794bef1-4aae-47d3-8bcb-817a53688068.png">

### Expected Behavior

希望能隐藏标签引导线

### Environment

```markdown
- OS: mac
- Browser: chrome
- Framework:
```

**Comment by daisy0123** [comment]
https://codepen.io/daisy0123/pen/ZErpYWq

**Comment by plainheart** [comment]
@daisy0123 抱歉没有注意到你的问题，稍后我们跟进下。
