### ISSUE TITLE
如何读取dataset中转换后的数据

### ISSUE THREAD

**Issue by mcxinyu** [apache/echarts#17015]
### What problem does this feature solve?

如何读取dataset中转换后的数据

### What does the proposed API look like?

none

**Comment by nelsonbbarriento23** [comment]
6ssb

**Comment by ZhengRui** [comment]
same question here

**Comment by mcxinyu** [comment]
> 

Where?

**Comment by ZhengRui** [comment]
我最后没办法，只好自己实现transform的逻辑显式生成了dataset插入到option.dataset里面

**Comment by mcxinyu** [comment]
哦，这样会很慢呀，而且option会很长...

**Comment by ZhengRui** [comment]
我现在数据量不是很大，就是几个map reduce 的操作，不知道echarts的transform实现是不是优化过的

**Comment by mcxinyu** [comment]
其实我是想在手指点击折线图的时候拿到对应data Y轴的数值。如果没办法拿到transform的数据，能不能拿到Y轴的值呢？

**Comment by ZhengRui** [comment]
我的问题是获取brush区域里面点的数据，这个区域的大小本身是可以通过brush的area里面的coordRange得到。关于你的问题，在点击折线图时，你可以监听鼠标事件，鼠标事件的params里面是有你要的数据的。

chart.on('click', 'series', (params) => console.log(params.data))
