### ISSUE TITLE
draw a circle in radar chart 

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17018]
### What problem does this feature solve?

hii my requirement is to draw a circle in radar chart ,
![Uploading Screenshot (67).png…]()
 does echarts have any api to resolve the issue 

### What does the proposed API look like?

we need to draw a circle in radar charts 
![Screenshot (67)](https://user-images.githubusercontent.com/97290751/168005470-87d5de9c-837f-44dd-9985-9cd3f7bb2d74.png)

**Comment by susiwen8** [comment]
Duplicate with #17003
