### ISSUE TITLE
[Bug] The elements selected during the scaling of ScatterChart under large data volumes do not disappear

### ISSUE THREAD

**Issue by shiboqingning** [apache/echarts#17028]
### Version

5.3

### Steps to Reproduce

1.ScatterChart of big data
2.Place the mouse over an element to scale the canvas
![image](https://user-images.githubusercontent.com/102708847/168260783-49c4c0c6-4054-49bf-8e52-d31216748166.png)
![image](https://user-images.githubusercontent.com/102708847/168260938-454ef218-9d36-464c-807c-43a19bf70ee1.png)

### Current Behavior

Selected elements do not disappear during scaling

### Expected Behavior

Hide the element selected at the beginning of the mouse during zooming

### Environment

```markdown
- OS: Windows 10
- Browser:Chrome 100.0.4896.127
- Framework: JS
```

**Comment by Ovilia** [comment]
This doesn't look like a bug to me. Please create a demo if you think so.

**Comment by shiboqingning** [comment]
The renderings are as follows:
![example](https://user-images.githubusercontent.com/102708847/168519866-45a3fad0-86f7-4a24-81f5-09200d408b4a.gif)


See The Following Code:

var data = [];
for (i = 0; i < 100; i++) {
  for (j = 0; j < 100; j++) {
    if(i == 50 && j == 50){
      data.push([i,j,20])
    }else{
        data.push([i,j,5]);
    }
  }
}


option  = {
xAxis   : {},
yAxis   : {},
dataZoom: [
    {
      id: 'dataZoomX',
      type: 'inside',
      xAxisIndex: [0],
      filterMode: 'filter'
    },
    {
      id: 'dataZoomY',
      type: 'inside',
      yAxisIndex: [0],
      filterMode: 'filter'
    }
  ],
  tooltip:{},
  series: [
    {
      symbolSize: function (val) {
        return val[2];
      },
      data: data,
      type: 'scatter'
    }
  ]
};
