### ISSUE TITLE
[Feature] Get calculated max/min value of yaxis 

### ISSUE THREAD

**Issue by sammuell** [apache/echarts#17021]
### What problem does this feature solve?

I would like to retrieve the automatically calculated min/max value of an yaxis. 

### What does the proposed API look like?

I'm unsure about this. There seems to be no getter API except for chart.getOption(). Using this seems like a hack as the option property would only be readable but not writable using setOption().
`option.yAxis[1].minCalculated`

**Comment by jiawulin001** [comment]
As is designed, axis scale will automatically fit the user data so users won't worry about adjusting axis. What effect are you trying to attain?

**Comment by sammuell** [comment]
Here's my use case:
To highlight the weekend days for better readability of the chart I insert a fake bar chart in light gray (see image below). The height is determined before rendering by the max value of the data. However, the calculated max value of the yAxis is larger, making the weekend day bar look weird, because it's not at full height of the axis. I would like to get the max value of the axis after rendering and increase the data of the weekend bar to that value.

 ![grafik](https://user-images.githubusercontent.com/1202195/168416721-9ed13434-405c-4906-82a3-2125ff7e94f7.png)

**Comment by jiawulin001** [comment]
Do you mind providing a similar option to test with? Also, do you mean that you want all gray bars to be at 250 in this picture?

**Comment by sammuell** [comment]
>  Also, do you mean that you want all gray bars to be at 250 in this picture?
Exactly. I first tried to draw the grey rectangles using the graphic option. That does not work due to the unknown specific coordinates.

**Comment by jiawulin001** [comment]
You can use `markArea` to achieve such effect, by setting the gray zone data to none and put markArea there. But this method is only applicable to static chart. Please check the sample for reference.
<details>
<summary>Code Sample</summary>

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, , 70, 110, 130],
      type: 'bar',
      markArea: {
        itemStyle: {
          color: 'rgba(0,0,0,0.1)'
        },
        data: [
          [
            {
              name: 'GrayZone',
              x: '44.5%'
            },
            {
              x: '55.7%'
            }
          ]
        ]
      }
    }
  ]
};
```
</details>

**Comment by Ovilia** [comment]
`markArea` is a simpler way to make it. Otherwise, you can use `chart.getOptions().grid.height` to get the size of the grid area.

**Comment by sammuell** [comment]
Thanks for pointing me to `markArea`. 
I implemented it using two xAxis properties. However, the rendered result does not extend as far as expected (purple lines)

![grafik](https://user-images.githubusercontent.com/1202195/168817162-7c254ae2-da81-41cb-8fde-fe25b82fd8ff.png)

**Comment by jiawulin001** [comment]
>However, bar charts uses a category xAxis.

Right, so you might have to use position relative to DOM to locate the gray bar like what I did in the code sample [here](https://github.com/apache/echarts/issues/17021#issuecomment-1127125927)

**Comment by sammuell** [comment]
The issue at hand is that the chart is a non-static time line. The number of items of the xaxis is changing over time, so you cannot determine the necessary percentages.
