### ISSUE TITLE
[Bug] Get friendly dataZoom handleIcon shadow

### ISSUE THREAD

**Issue by HiMary321** [apache/echarts#17022]
### Version

5.3.2

### Steps to Reproduce

dataZoom-slider: {
    handleIcon: 'M10.7,11.9H9.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4h1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
    handleStyle: {
        color: '#f5f5f5',
        shadowBlur: 5,
        shadowColor: 'rgba(0, 0, 0, 0.6)',
        shadowOffsetX: 2,
        shadowOffsetY: 2
    }
}

### Current Behavior

![image](https://user-images.githubusercontent.com/49702830/168069427-9537426a-0880-450e-9f6c-54e041b92708.png)
![image](https://user-images.githubusercontent.com/49702830/168069533-838ed830-099e-49f6-aaa6-9d57db1e8cf9.png)

The first picture (version 4) shows normal, the second picture (version 5) shows a problem.They are configured exactly the same.

The shadow effect is displayed normally in version 4, but displayed abnormally in version 5. The shadow color overlaps with the icon, causing the display to be chaotic.

### Expected Behavior

Shadow and icon color do not overlap, display friendly.

### Environment

```markdown
- OS:Linux4.19
- Browser:Chrome 89.0
- Framework:Vue@2
```

**Comment by nelsonbbarriento23** [comment]
Homepage.comd

**Comment by nelsonbbarriento23** [comment]
Bringggveveone PgarxiA

**Comment by nelsonbbarriento23** [comment]
Place and

**Comment by nelsonbbarriento23** [comment]
Just >,,

**Comment by HiMary321** [comment]
What does it mean please

**Comment by nelsonbbarriento23** [comment]
Forver

**Comment by nelsonbbarriento23** [comment]
NlNBE347714N

**Comment by nelsonbbarriento23** [comment]
Together

**Comment by HiMary321** [comment]
What does that mean

**Comment by nelsonbbarriento23** [comment]
Pissang@

**Comment by HiMary321** [comment]
Please don't post anything unrelated to the question

**Comment by nelsonbbarriento23** [comment]
Come now at ll

**Comment by nelsonbbarriento23** [comment]
PB

**Comment by nelsonbbarriento23** [comment]
guzmab

**Comment by nelsonbbarriento23** [comment]
Annnf  sso aillb i

**Comment by nelsonbbarriento23** [comment]
I'll get another one

**Comment by nelsonbbarriento23** [comment]
But you probably  don't have a few people that 🤔

**Comment by nelsonbbarriento23** [comment]
With meeting
