### ISSUE TITLE
柱状图数据相差过大无法显示咋解决

### ISSUE THREAD

**Issue by hkllin** [apache/echarts#17026]
### What problem does this feature solve?

柱状图数据相差过大无法显示咋解决

### What does the proposed API look like?

柱状图数据相差过大无法显示咋解决

**Comment by susiwen8** [comment]
https://echarts.apache.org/zh/option.html#series-bar.barMinHeight

**Comment by hkllin** [comment]
@susiwen8  这个不太行。。。   
![image](https://user-images.githubusercontent.com/93277196/168243060-a62852a6-1482-4b92-b0e0-ff51c1225a96.png)
我尝试过你这个。。。

**Comment by susiwen8** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG4OJHhURlSEsKL8xB7oAEaMHBIQ0AASVBCs2mBEAIwADFWhHkJgIikVAEy1sG01NTywFQCs7QAc7QDs7RXVPRUAzFXWdaQU1HTZHMEediS2dgDcQA
![Uploading Screen Shot 2022-05-13 at 4.30.38 PM.png…]()

**Comment by hkllin** [comment]
但是如果是0的时候也会给高度。。这个我也试过了 。。。有啥办法0的时候不给高度吗

**Comment by hkllin** [comment]
请问还有其他办法不。。。

**Comment by nelsonbbarriento23** [comment]
Come now let's f

**Comment by nelsonbbarriento23** [comment]
Mobile movie

**Comment by nelsonbbarriento23** [comment]
Bring jal3
