### ISSUE TITLE
隐藏图例时，希望轴单位也自动隐藏

### ISSUE THREAD

**Issue by YXYCZXY** [apache/echarts#17020]
### Version

5.3.2

### Steps to Reproduce

点击图例隐藏图表，轴单位未隐藏

### Current Behavior

![image](https://user-images.githubusercontent.com/49504688/168019976-c963c358-4008-438c-9a15-27d294a84bce.png)
隐藏图例的时候，轴的单位未自动隐藏

### Expected Behavior

期望隐藏图例的时候，轴的单位也隐藏

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by nelsonbbarriento23** [comment]
Come now

**Comment by nelsonbbarriento23** [comment]
Yes

**Comment by nelsonbbarriento23** [comment]
Yes

**Comment by zengyuehao** [comment]
可以使用legendselected事件去操控你的option

**Comment by YXYCZXY** [comment]
> 使用legendselected 可以去烧烤你的选项

这个我知道这样的确可以解决，但是echarts自带的隐藏图例的时候可以把对应轴的label给隐藏，那为什么不也隐藏轴的单位呢？
我觉得这个是一个bug

**Comment by zengyuehao** [comment]
> > 使用legendselected 可以去烧烤你的选项
> 
> 这个我知道这样的确可以解决，但是echarts自带的隐藏图例的时候可以把对应轴的label给隐藏，那为什么不也隐藏轴的单位呢？ 我觉得这个是一个bug

这个是看个人需求的吧，有的需求会要求显示y轴的名称，我们在制作图表的时候是需要根据自己的需求二次封装的
