### ISSUE TITLE
[Feature] 想在visualMap.pieces添加属性areaStyle

### ISSUE THREAD

**Issue by spirit-boy-guan** [apache/echarts#17025]
### What problem does this feature solve?

我想将线图分为几段，然后给每段分别渲染颜色及线下区域的颜色

### What does the proposed API look like?

`  visualMap: {
    type: 'piecewise',
    show: false,
    dimension: 0,
    seriesIndex: 0,
    outOfRange: {
      color: 'yellow',
    },
    pieces: [
      {
        gt: 1,
        lt: 3,
        color: 'blue',
        areaStyle: {
          color: 'red'
        }
      },
      {
        gt: 5,
        lt: 7,
        color: 'orange',
        areaStyle: {
          color: 'green'
        }
      }
    ]
  },`

**Comment by Ovilia** [comment]
目前无法做到这一点，可以通过一个额外的 series，该 series 只包含希望增加 areaStyle 的数据
