### ISSUE TITLE
[Bug] When painting a pillar with a bar, use dataset mode, and when you use encode, it will cause the legend to disappear；当用bar画柱子时候，用dataset模式，当用encode的时候，就会导致legend不见了

### ISSUE THREAD

**Issue by dforel** [apache/echarts#17027]
### Version

5.0.0 以上

### Link to Minimal Reproduction

[link](https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQQIZhsDOWYTV6AhAC2-LlGhcSAbQDkIAE7ACAVwDGYWeViyATAAYAjAFYtOg4YBsZvUYDssgLqV06LsBUK1WGQNepXQNhFZXU-HQBZDjUACzZYABkOMCwtP0CLYxIAFgBmADpclyD0C0sSAA5jfIrikos7EgBOArt02BYSgJLgpVUNElkIiAwAa1gAFSw2NJ7YTMqCwzqgspI7AuyVjPsSY2rDds6g7pKQ_vDZAGEYrCweWCvgNWAZ7dcF2ArLfK320qM5VglmquneAMMjS-unyxiO71OQXOYUGAHU2BhoCowLAAEJKADu0AgqXB8yMWVgdhhfzma1gxgKTTJDRIuSa-UOJVIfkcVGOAA8AIICiBSZB-MAATxAPh0ag4uGACilsn5xSlIrFTGOAHpdbAACJYNQYNgKLCwHgANywCgxsAARuarXaSVxtNNYrACSMME7LcI2CBZQQqPrqMBYPEXhgVMI4MAAGawdicHhgfLuTzeJ1S1NYJNsFT0fJUHgKd2-QKI9DS2WDZ0KWZBfAvAhy2uuAWDZEaFslKWDBpq7l-Y7oLv1uWyJuj1wTiUlaeN83z9A89B80gAbiAA)

### Steps to Reproduce

option = {
  legend: {},
  tooltip: {},
  dataset: {
    dimensions: ['product', '2015', '2016', '2017'],
    source: [
      {
        product: 'Matcha Latte',
        2015: 43.3,
        2016: 85.8,
        2017: 93.7
      },
      {
        product: 'Milk Tea',
        2015: 83.1,
        2016: 73.4,
        2017: 55.1
      },
      {
        product: 'Cheese Cocoa',
        2015: 86.4,
        2016: 65.2,
        2017: 82.5
      },
      {
        product: 'Walnut Brownie',
        2015: 72.4,
        2016: 53.9,
        2017: 39.1
      }
    ]
  },
  xAxis: {
    type: 'category'
  },
  yAxis: {},
  // Declare several bar series, each will be mapped
  // to a column of dataset.source by default.
  series: [
    {
      type: 'bar',
      encode: {
        x: 'product',
        y: '2017'
      }
    },
    {
      type: 'bar'
    },
    {
      type: 'bar'
    }
  ]
};

### Current Behavior

没有出现2017的legend。

it don't have 2017's legend

### Expected Behavior

应该出现2017的legend。

it should have 2017's legend.

### Environment

```markdown
- OS: windows
- Browser: edge
- Framework: ---
```

### Any additional comments?

当用bar画柱子时候，用dataset模式，当用encode的时候，就会导致legend不见了。
when use bar to draw, user dataset and encode, the legend will be hide.

**Comment by jiawulin001** [comment]
So the problem here is not that "2017 legend disappears" but "**Another 2015 series is added and squeeze out the 2017 series**". If you watch carefully you can see that the first and the second bar series are all 2015 series. 
And the reason why the first series has no legend is because **it has NO NAME**! Although we use encode to tell Echarts to use what data on which axis, Echarts does not use the data name as series name. 
So if you add `name` for the first series, you can see its legend.

**Comment by dforel** [comment]
> So the problem here is not that "2017 legend disappears" but "**Another 2015 series is added and squeeze out the 2017 series**". If you watch carefully you can see that the first and the second bar series are all 2015 series. And the reason why the first series has no legend is because **it has NO NAME**! Although we use encode to tell Echarts to use what data on which axis, Echarts does not use the data name as series name. So if you add `name` for the first series, you can see its legend.

thanks you ,  i don't found it need name,
so, it need name when **encode**, but **no encode** can default a name?

**Comment by jiawulin001** [comment]
You can refer to [this](https://echarts.apache.org/zh/option.html#series-bar.name) for `name` setting. For what I mean you can see the attached code for referenece.
<details>
<summary>Code Sample</summary>

```
option = {
  legend: {},
  tooltip: {},
  dataset: {
    dimensions: ['product', '2015', '2016', '2017'],
    source: [
      {
        product: 'Matcha Latte',
        2015: 43.3,
        2016: 85.8,
        2017: 93.7
      },
      {
        product: 'Milk Tea',
        2015: 83.1,
        2016: 73.4,
        2017: 55.1
      },
      {
        product: 'Cheese Cocoa',
        2015: 86.4,
        2016: 65.2,
        2017: 82.5
      },
      {
        product: 'Walnut Brownie',
        2015: 72.4,
        2016: 53.9,
        2017: 39.1
      }
    ]
  },
  xAxis: {
    type: 'category'
  },
  yAxis: {},
  // Declare several bar series, each will be mapped
  // to a column of dataset.source by default.
  series: [
    {
      name:'2015',
      type: 'bar',
      encode: {
        x: 'product',
        y: '2015'
      }
    },
    {
      name:'2016',
      type: 'bar',
      encode: {
        x: 'product',
        y: '2016'
      }
    },
    {
      name:'2017',
      type: 'bar',
      encode: {
        x: 'product',
        y: '2017'
      }
    }
  ]
};
```
</details>
