### ISSUE TITLE
[Bug] 坐标轴能否显示固定设置的刻度，如X轴的刻度设置为[0.25,0.75,1]，类似这个问题所提出的https://github.com/apache/echarts/issues/4678，目前echart能实现吗？

### ISSUE THREAD

**Issue by ziyingjing** [apache/echarts#17034]
### Version

5.2.2

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=parallel-simple
例如这个demo,期望price项 显示为[0.25,0.75,1]，数字之间没有规律，只是希望设置成固定值

### Current Behavior

平行坐标系：
坐标轴type=value时，坐标轴的刻度只能按min,max 等间距的去设置刻度，不能固定成某几个固定的刻度；
坐标轴type=category时,坐标轴可以显示固定的刻度，但是值分布在坐标轴上显示不出数字的真实含义

### Expected Behavior

平行坐标系：
坐标轴type=value时，坐标轴的刻度能设定成固定的值：[0,0.5,1,1.5]，数字之间没有规律；

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
可以的，相当于 `['Excellent', 'Good', 'OK', 'Bad']` 例子，写成字符串形式即可

**Comment by ziyingjing** [comment]
> 

可能我没描述清楚，我的诉求是我能坐标轴的刻度可以写死成固定的值，但是设置data能按着坐标轴的实际所属区间显示

如下面这张图
![107101652669450_ pic](https://user-images.githubusercontent.com/8833911/168512039-3931c5ce-3446-4185-bf18-4acfabf6a4a4.jpg)


======================================

我写成了['0','0.5','1','1.5'],坐标轴是可以展示成我设定的固定值，但是当设置data的时候，如，[0.2,0,3]...,series只能 显示到坐标轴的'0'-'0.5'的中间位置，并不能按实际的值所属区间展示
