### ISSUE TITLE
How to set the legend area into two-columns in Apache Echarts

### ISSUE THREAD

**Issue by Deshan-Ruhunage** [apache/echarts#17036]
### What problem does this feature solve?

I want to make the legend area into two-column in Apache Echarts, how I can achieve this with legend options? 

### What does the proposed API look like?

legend:{
NumerofRows:2;
itemPerRow:7;
}

**Comment by deshanruhunage** [comment]
![e7rwA](https://user-images.githubusercontent.com/49788632/168515428-49514a4d-07af-447d-ac9a-31ba6f9c5303.jpeg)
