### ISSUE TITLE
treemap The label setting /n only shows half of the text, hope the text is displayed?

### ISSUE THREAD

**Issue by chenxueling** [apache/echarts#17033]
### Version

5.3.1

### Steps to Reproduce

treemap The label setting /n only shows half of the text, want the minimum height or the text is displayed?

### Current Behavior

  position: 'insideLeft',
        formatter: function (params: any) {
          return `{oneone|${params.name}}\n{two|${
            Number(params.data.rate) >= 0
              ? '+' + params.data.rate
              : params.data.rate
          }%}`;
        },
        rich: {
          oneone: {
            fontSize: 14,
            lineHeight: 20,
            color: '#4E5969',
          },
          two: {
            fontSize: 12,
            lineHeight: 18,
            color: function (params: any) {
              return params.data.rate > 0 ? '#F53F3F' : ' #00B42A';
            },
          },
        },
      },
![微信图片_20220514111801](https://user-images.githubusercontent.com/34822485/168413359-369f3c49-8697-476a-8805-37c3194d0e98.png)
![微信图片_20220514112145](https://user-images.githubusercontent.com/34822485/168413363-60dcfb02-e4f6-4018-ad6b-c4301b1ab4c7.png)

### Expected Behavior

hope the text is displayed?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Set `label.overflow` to be `'break'`.

**Comment by dududu123456** [comment]
if show half, can i check it and hide label?

for example, hide the label by making the 'text' of labelLayout empty 

```
labelLayout(params) {
    return {
        text: ''
    }
}
```
