### ISSUE TITLE
[Bug] Issue with bootstrap + echarts!

### ISSUE THREAD

**Issue by CodingFrizey** [apache/echarts#17035]
### Version

5.3.2

### Steps to Reproduce

1. Create a chart inside a bootstrap application
2. Add the tooltip element

### Current Behavior

My second day playing with echarts for my own application, and i use bootstrap css to help create my app's UI, however, when i add echarts, the tooltip class is the same as the tooltip class in bootstrap, therefor bootstrap overrides echart's class.

The result of this is the tooltip looking a little wonky, looking for a fix because my application is set to release soon and the chart is a main part of the app, other than that i love echarts!

![image](https://user-images.githubusercontent.com/86231029/168491021-7856d71a-5312-4e73-822d-2adf9f0d7134.png)

### Expected Behavior

It should have different class names so it doesn't get overridden.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
The class name of the tooltip can be set with [tooltip.className](https://echarts.apache.org/en/option.html#tooltip.className).

**Comment by CodingFrizey** [comment]
> The class name of the tooltip can be set with [tooltip.className](https://echarts.apache.org/en/option.html#tooltip.className).

I also read this in the docs earlier and i attempted to add it into my code, but the problem still persists. Heres a snippet of my code:

`    option = {
      tooltip: {
        shadowColor: "rgba(17,17,17,0)",
        borderColor: 'rgba(17,17,17,0)',
        backgroundColor: 'rgb(17,17,17)',
        trigger: 'axis',
        position: function (pt) {
          return [pt[0], '0%'];
        },
        className: "echarts-tooltip1 echarts-tooltip-dark1",
        renderMode: "html",
      },`
