### ISSUE TITLE
[Bug]柱状图使用markPoint不显示出来 

### ISSUE THREAD

**Issue by zhaoyanga** [apache/echarts#17049]
### Version

4.8.0

### Steps to Reproduce

<img width="393" alt="c5b64c2edff7daa51bba6416f98bda3" src="https://user-images.githubusercontent.com/71998720/168760213-07487ba1-55a9-4ba3-884f-5573e3bc378d.png">

### Current Behavior

markPoint粗布来

### Expected Behavior

期望出来

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fuchunhui** [comment]
试试这个，我没有发现你说的问题呢。
[codesandbox](https://codesandbox.io/s/smoothed-line-chart-forked-j55us9)

![image](https://user-images.githubusercontent.com/29879262/168798285-c5d96ac9-8f12-47c3-bf1c-482a9c9a1a0f.png)


切换到最新版，v5.3.2也没问题。
![image](https://user-images.githubusercontent.com/29879262/168798153-8817ba0e-8528-4691-acd6-5a42960fc94d.png)
