### ISSUE TITLE
[Bug] 官网打不开，像是cdn挂了

### ISSUE THREAD

**Issue by baojie223** [apache/echarts#17042]
### Version

5.2.2

### Steps to Reproduce

1. 打开官网
2. css样式混乱

### Current Behavior

![image](https://user-images.githubusercontent.com/27616710/168717188-9a4b9943-4b9f-4a3f-9c28-93685781e49f.png)

### Expected Behavior

正常访问

### Environment

```markdown
- OS: windows10
- Browser: Chrome 100.0.4896.60
- Framework:
```

**Comment by wangziqin123** [comment]
是挂了

**Comment by wangziqin123** [comment]
https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css
cdn挂了主要是

**Comment by baojie223** [comment]
主要是咋解决

**Comment by QiWuSouTong** [comment]
太搞心态了，昨天就有这情况

**Comment by plainheart** [comment]
It should work now. Please try to clear the cache and open the website again.

**Comment by baojie223** [comment]
another question, example cannot show.
https://echarts.apache.org/examples/zh/editor.html?c=line-simple
![image](https://user-images.githubusercontent.com/27616710/168725218-bca073c0-1c82-4828-94db-09c16773104c.png)
@plainheart

**Comment by plainheart** [comment]
@baojie223 Please switch the "Disable cache" button on.

**Comment by baojie223** [comment]
![image](https://user-images.githubusercontent.com/27616710/168725656-fdf79ef0-9a00-4cfd-9005-2066713df9fd.png)
@plainheart

**Comment by plainheart** [comment]
@baojie223 Sorry for missing something. It's related to the CDN cache. Please wait for a moment. I'm going to purge it.

**Comment by wutato** [comment]
还是无法展开样式

**Comment by sweetwisdom** [comment]
> ### Version
> 5.2.2
> 
> ### Link to Minimal Reproduction
> _No response_
> 
> ### Steps to Reproduce
> 1. 打开官网
> 2. css样式混乱
> 
> ### Current Behavior
> ![image](https://user-images.githubusercontent.com/27616710/168717188-9a4b9943-4b9f-4a3f-9c28-93685781e49f.png)
> 
> ### Expected Behavior
> 正常访问
> 
> ### Environment
> ```gfm
> - OS: windows10
> - Browser: Chrome 100.0.4896.60
> - Framework:
> ```
> 
> ### Any additional comments?
> _No response_

改下host文件就好了,试试这个

```
 151.101.73.229 cdn.jsdelivr.net

 104.16.85.20 cdn.jsdelivr.net

```

**Comment by plainheart** [comment]
Hi, all. The CDN cache has been updated. Feel free to check if you can access the website and example page.
