### ISSUE TITLE
[Bug] The official website source code error, it appears that the CDN reference library is not available

### ISSUE THREAD

**Issue by julius2zhu** [apache/echarts#17053]
### Version

5.2.2

### Steps to Reproduce

Unable to view source code

### Current Behavior

Unable to view source code

### Expected Behavior

enable to view source code

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/44996257/168784618-db46592e-3eeb-48e3-881d-27a567852c9c.png)

**Comment by plainheart** [comment]
Duplicated of #17042. The CDN cache on the Chinese example page has not been updated yet. Please access the English example page temporarily.
