### ISSUE TITLE
[Feature] series-type为custom的自定义系列图形，legend的name是否可以像饼图和漏斗图映射到series.data上去

### ISSUE THREAD

**Issue by wangnannanziyu** [apache/echarts#17054]
### What problem does this feature solve?

需要使用自定义系列实现转化漏斗图，希望legend的name也可以像echarts本身支持漏斗图那样，可以映射到单个数据的name上（或者能映射到renderItem返回的对象的name上），否则legend默认就是映射到series.name

### What does the proposed API look like?

https://echarts.apache.org/examples/zh/editor.html?c=funnel
希望自定义系列的legend，也能像原生支持的漏斗图那样，可以和单个数据的name对应上

**Comment by halo951** [comment]
我也碰到了这个问题, 没细看 Pie 的实现逻辑. 难道 Pie 的每个扇区都是一个独立的serie?

**Comment by halo951** [comment]
目前, 我在项目中的实现是用了一个 width:0, height:0 的 pie chart 去伪造一个图例, 但这种方式, 不是很正经, 还是要通过优化api去解决问题.
