### ISSUE TITLE
[Bug] tooltip.axisPointer interfers with data.series.emphasis.focus series

### ISSUE THREAD

**Issue by vincentbernat** [apache/echarts#17065]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-rainfall

### Steps to Reproduce

This is easy to reproduce in the above example.

1. Pass the mouse over the blue area

### Current Behavior

The green area is unchanged.

### Expected Behavior

The green area should be made transparent.

Disabling the tooltip fixes this issue.

### Environment

```markdown
- OS: Debian Linux unstable
- Browser: Firefox 100.0
- Framework: n/a
```

**Comment by vincentbernat** [comment]
This is reproducible with Chromium 101 as well.

**Comment by susiwen8** [comment]
Duplicate with #16388
