### ISSUE TITLE
[Bug][LineChart] option [ itemStyle.color ] effect line style

### ISSUE THREAD

**Issue by RootJian** [apache/echarts#17071]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0Mp8cegQLAC2JhT-3u4J6AD0s7CAm_GAM4mAfdGAdv545CMARsD-sIC0coAvqYAzAYD2ZoDwCYBwZoOk9PucdBysO4wAFJlfPOkAlMEzOxxIHoWx2ADcQA

### Steps to Reproduce

set series-line itemStyle.color: rgba(0,0,0,0)

### Current Behavior

The whole line turned red

### Expected Behavior

I need the middle part of the symbol to be transparent

### Environment

```markdown
- OS:windows
- Browser:google
- Framework:-
```

### Any additional comments?
![image](https://user-images.githubusercontent.com/41674118/169288542-59348f35-1aec-4ee5-94d0-2d45976426c6.png)

_No response_

**Comment by jiawulin001** [comment]
If you want to stop displaying symbols, set `symbol` to `'none'`. Check this [reference](https://echarts.apache.org/zh/option.html#series-line.symbol).

**Comment by fuchunhui** [comment]
use `symbol: 'circle'` instead of `symbol: emptyCircle`(default value).

**Comment by RootJian** [comment]
> 



> use `symbol: 'circle'` instead of `symbol: 'emptyCircle'`(default value).
emmm, I need transparency in the middle, not solid.☺

**Comment by RootJian** [comment]
![image](https://user-images.githubusercontent.com/41674118/169302884-fbac5404-4f31-46cb-bdc9-006332cf3d92.png)
ui design

**Comment by jiawulin001** [comment]
It's transparent by default.

**Comment by RootJian** [comment]
> It's transparent by default.
However, it is not the interior that is transparent
![image](https://user-images.githubusercontent.com/41674118/169426774-d913e959-f7be-44ec-8795-4dc29566020c.png)

**Comment by RootJian** [comment]
> It's an empty circle by default, which is transparent inside

However, it is not the interior that is transparent
![image](https://user-images.githubusercontent.com/41674118/169426774-d913e959-f7be-44ec-8795-4dc29566020c.png)

**Comment by jiawulin001** [comment]
Try setting:
`symbol: 'path://M30.9,53.2C16.8,53.2,5.3,41.7,5.3,27.6S16.8,2,30.9,2C45,2,56.4,13.5,56.4,27.6S45,53.2,30.9,53.2z M30.9,3.5C17.6,3.5,6.8,14.4,6.8,27.6c0,13.3,10.8,24.1,24.101,24.1C44.2,51.7,55,40.9,55,27.6C54.9,14.4,44.1,3.5,30.9,3.5z'`

**Comment by RootJian** [comment]
> Try setting: `symbol: 'path://M30.9,53.2C16.8,53.2,5.3,41.7,5.3,27.6S16.8,2,30.9,2C45,2,56.4,13.5,56.4,27.6S45,53.2,30.9,53.2z M30.9,3.5C17.6,3.5,6.8,14.4,6.8,27.6c0,13.3,10.8,24.1,24.101,24.1C44.2,51.7,55,40.9,55,27.6C54.9,14.4,44.1,3.5,30.9,3.5z'`

![image](https://user-images.githubusercontent.com/41674118/169428535-4f9668e9-9163-4b11-9aa7-de736d783b0b.png)
I don't think this is a good idea, when the symbol use path, the line will be displayed. I should dynamically set the color inside the symbol.

**Comment by fuchunhui** [comment]
> 

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      symbolSize: 30,
      symbol: 'circle',
      itemStyle: {
        borderWidth: 3,
        borderColor: '#EE6666',
        color: 'transparent'
      },
      lineStyle: {
        color: 'green'
      }
    }
  ]
};
```
@RootJian please try it like this. [Demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt75A-gQLMMmFP7e7gno4xwCEaoQAmDaRLkLpDt7HADCE5x0AMQAok9Nb028cR70dxx0YBxGNA8CBGBwqNAwMEtg4vrAen1VuR1m44egfv57rJWOCIdCEnY4oT0LY7ABuIA)

![image](https://user-images.githubusercontent.com/29879262/169432566-360c8ec0-59f7-4edd-91da-58a47dcf0871.png)

**Comment by RootJian** [comment]
> > use `symbol: 'circle'` instead of `symbol: 'emptyCircle'`(default value).
> 
> ```
> option = {
>   xAxis: {
>     type: 'category',
>     data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
>   },
>   yAxis: {
>     type: 'value'
>   },
>   series: [
>     {
>       data: [150, 230, 224, 218, 135, 147, 260],
>       type: 'line',
>       symbolSize: 30,
>       symbol: 'circle',
>       itemStyle: {
>         borderWidth: 3,
>         borderColor: '#EE6666',
>         color: 'transparent'
>       },
>       lineStyle: {
>         color: 'green'
>       }
>     }
>   ]
> };
> ```
> 
> @RootJian please try it like this. [Demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt75A-gQLMMmFP7e7gno4xwCEaoQAmDaRLkLpDt7HADCE5x0AMQAok9Nb028cR70dxx0YBxGNA8CBGBwqNAwMEtg4vrAen1VuR1m44egfv57rJWOCIdCEnY4oT0LY7ABuIA)
> 
> ![image](https://user-images.githubusercontent.com/29879262/169432566-360c8ec0-59f7-4edd-91da-58a47dcf0871.png)

It can meet our needs, but I think this bug needs to be fixed. 😂 thx

**Comment by jiawulin001** [comment]
I don't think it's a bug, according to [doc](https://echarts.apache.org/zh/option.html#series-line.lineStyle). As you set `itemStyle.color`, the default line color will be changed to it.

**Comment by RootJian** [comment]
> I don't think it's a bug, according to [doc](https://echarts.apache.org/zh/option.html#series-line.lineStyle). As you set `itemStyle.color`, the default line color will be changed to it.

got it! thx
