### ISSUE TITLE
[Bug] when use echart.connect to link charts, if one chart's data is outside the zoom range, this chart's axisPointer will be invisible 

### ISSUE THREAD

**Issue by todwang** [apache/echarts#17074]
### Version

5.3.2

### Link to Minimal Reproduction

https://codepen.io/todwang/pen/RwQgrGB

### Steps to Reproduce

var chart1 = echarts.init(document.getElementById("chart1"));
var option1 = {
  title: {
    text: "chart1"
  },
  tooltip: {
    trigger: "axis"
  },
  legend: {
    data: ["今天", "昨天", "上周"]
  },
  xAxis: {
    data: ["8:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00"]
  },
  yAxis: {},
  series: [
    {
      name: "上周",
      type: "line",
      data: [10, 35, 20, 13, 16, 18, 41]
    }
  ]
};
var chart2 = echarts.init(document.getElementById("chart2"));
var option2 = {
  title: {
    text: "chart2"
  },
  tooltip: {
    trigger: "axis"
  },
  legend: {
    data: ["今天", "昨天", "上周"]
  },
  xAxis: {
    data: ["8:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00"]
  },
  yAxis: [{}],
  series: [
    {
      name: "上周",
      type: "line",
      data: [10, 35, 20, 13, 12, 18, 41]
    }
  ],
  dataZoom: [
    { yAxisIndex: 0, filterMode: "none", startValue: 20, endValue: 30 }
  ]
};

chart1.setOption(option1);
chart2.setOption(option2);
chart1.group = "group1";
chart2.group = "group1";
echarts.connect("group1");

### Current Behavior

<img width="616" alt="image" src="https://user-images.githubusercontent.com/2556893/169476031-6de9b192-6e19-4fa3-a21a-d73a3036bc31.png">

### Expected Behavior

<img width="619" alt="image" src="https://user-images.githubusercontent.com/2556893/169476153-20556282-c6f0-4e5f-985f-19e33e92e607.png">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

产生这种现象的原因应该是axisTrigger中会判断该点是否在坐标系中
<img width="684" alt="image" src="https://user-images.githubusercontent.com/2556893/169477507-3165473e-66e0-40d2-a134-ca0100261c92.png">

**Comment by jiawulin001** [comment]
I don't think it is a bug. 
It makes sense to me not to show the pointer if no point is shown at the position.
When you put mouse at the zoomed chart, axispointer will be displayed correctly.

**Comment by todwang** [comment]
> I don't think it is a bug. It makes sense to me not to show the pointer if no point is shown at the position. When you put mouse at the zoomed chart, axispointer will be displayed correctly.

系统貌似只会根据seriesIndex=0去判断是否有无数据，如果chart中有两个series，series0数据超出坐标系，series1数据在坐标系中依然会不现实axisPointer, 比如下列情况
<img width="610" alt="image" src="https://user-images.githubusercontent.com/2556893/169492119-e671ec83-e317-4d35-a14f-5e8bded3ddb2.png">，

两个chart联动时，如果x轴数据在坐标系中，保持x轴有效是不是更合理？
<img width="234" alt="image" src="https://user-images.githubusercontent.com/2556893/169493412-0e4e60b1-5129-4c7d-9a17-680a207fac44.png">
