### ISSUE TITLE
[Bug]the bar chart starts at 0, and setting xAxis.axisline.onZero: false won't make it start at the minimum

### ISSUE THREAD

**Issue by yuntian001** [apache/echarts#17077]
### Version

5.3.2

### Steps to Reproduce

option = {
      xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        axisLine: {
          onZero: false
        }
      },
      yAxis: {
        type: 'value'
      },
      series: [{
        data: [-120, 200, 150, 80, 70, 110, 130],
        type: 'bar'
      }]
    }

### Current Behavior

In 5.2.2, the bar chart starts at 0, and setting xAxis.axisline.onZero: false won't make it start at the minimum
![image](https://user-images.githubusercontent.com/43692243/169554978-c97539ca-9f8d-49fa-b4be-cfd7460634f8.png)

### Expected Behavior

This is OK for versions below 4.0.0

![image](https://user-images.githubusercontent.com/43692243/169555075-a5e9f5c8-4c53-4670-b3c7-0e71b21be7c6.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
This is no longer supported now. But I can make a feature PR for this.

**Comment by yuntian001** [comment]
When can it be resolved
