### ISSUE TITLE
[Feature] [LineChart] 希望添加 symbolSize 配置以及将select 样式权重设置高于emphasis样式

### ISSUE THREAD

**Issue by RootJian** [apache/echarts#17072]
### What problem does this feature solve?

1. echarts symbolSize 设置6和emphasis.scale为true时，放大效果不明显，希望能够提供配置手动设置放大像素值
[Demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu7gnoeEz-NGAcSnHodsewcafotnYA3EA)
2. 当我设置select.itemStyle 样式和emphasis.itemStyle样式时，hover 点击symbol，此时没有显示select的样式，而是展示的emphasis样式，需要失焦symbol后才展示，因此希望select.itemStyle权重能够大于emphasis.itemStyle或者将其进行merge,合并样式更佳

### What does the proposed API look like?

1、
`{
      symbolSize: 6,
      emphasis:{
          symbolSize: 8
      }
}`

**Comment by plainheart** [comment]
> 希望能够提供配置手动设置放大像素值

从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)

**Comment by RootJian** [comment]
> 



> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)



> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)

确实能生效，那还有一个

> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)



> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)

确实能生效，那还有一个就是select.itemStyle 样式和emphasis.itemStyle样式同时设置的问题，请问有解决方案吗 [Demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXANprqwDkARtgK4Cm5pAugDSkAeAguxAM4HJS6MAE8QdAeQwBDMHQDm-EeTZlYAE1nSBRcgFkYKigBV6R8gHU6688YAWNcwDE8EcwGVZHmtHJNSAL6qsCLcfAKoaqLikgBu0rQMgcG8dK50_LAkapFqGlo6AIwArAAMLLAATADM5VWVACwVlYUAHBWF1cUdDQDszQBspaxCZNESFNgQ0AzBarwiALaUOO4QAF4TA3Nkqdh0GHLqBuoT5LzT8vsqo-h0iyB20hf8uXmwvDL7BK0A9Nu3MgQOSLdyib5vd6wFZ4U54CwQdRgOwESo7d5YXCEKiJG5QsgwuEAYRw-AIACIAMQAM1p5MB6ACgKCgL2BzABEhamB9zBIghDIJ-DhCKRKLRgvQhLSJKxFMppUV9PxTPeqrI6v8AQA3EA)

select样式：
![image](https://user-images.githubusercontent.com/41674118/169427920-3b19a445-9d6a-47f3-a830-28a77d2b9418.png)
hover样式：
![image](https://user-images.githubusercontent.com/41674118/169427832-4e6ac7cc-c896-4f3e-bd9a-d5f06e9dd8a2.png)
期望hover时取click样式（同时hover放大效果保留）
![image](https://user-images.githubusercontent.com/41674118/169427915-4f059e55-7982-4e2e-a8c6-bf8f9007d5f9.png)
但现在hover时click样式依然保留的hover样式
![image](https://user-images.githubusercontent.com/41674118/169427964-9e882bb6-0687-40bd-bc7d-624ffd28597c.png)

**Comment by RootJian** [comment]
> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)

确实能生效，那还有一个就是select.itemStyle 样式和emphasis.itemStyle样式同时设置的问题，请问有解决方案吗 [Demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXANprqwDkARtgK4Cm5pAugDSkAeAguxAM4HJS6MAE8QdAeQwBDMHQDm-EeTZlYAE1nSBRcgFkYKigBV6R8gHU6688YAWNcwDE8EcwGVZHmtHJNSAL6qsCLcfAKoaqLikgBu0rQMgcG8dK50_LAkapFqGlo6AIwArAAMLLAATADM5VWVACwVlYUAHBWF1cUdDQDszQBspaxCZNESFNgQ0AzBarwiALaUOO4QAF4TA3Nkqdh0GHLqBuoT5LzT8vsqo-h0iyB20hf8uXmwvDL7BK0A9Nu3MgQOSLdyib5vd6wFZ4U54CwQdRgOwESo7d5YXCEKiJG5QsgwuEAYRw-AIACIAMQAM1p5MB6ACgKCgL2BzABEhamB9zBIghDIJ-DhCKRKLRgvQhLSJKxFMppUV9PxTPeqrI6v8AQA3EA)

select样式：
![image](https://user-images.githubusercontent.com/41674118/169427920-3b19a445-9d6a-47f3-a830-28a77d2b9418.png)
hover样式：
![image](https://user-images.githubusercontent.com/41674118/169427832-4e6ac7cc-c896-4f3e-bd9a-d5f06e9dd8a2.png)
期望hover时取click样式（同时hover放大效果保留）
![image](https://user-images.githubusercontent.com/41674118/169427915-4f059e55-7982-4e2e-a8c6-bf8f9007d5f9.png)
但现在hover时click样式依然保留的hover样式
![image](https://user-images.githubusercontent.com/41674118/169427964-9e882bb6-0687-40bd-bc7d-624ffd28597c.png)

**Comment by RootJian** [comment]
> > 希望能够提供配置手动设置放大像素值
> 
> 从 v5.3.2 开始，symbol 的 `emphasis.scale` 支持数值类型，参见 #16688。文档可能有疏漏，仅 [scatter series](https://echarts.apache.org/option.html#series-scatter.emphasis.scale) 有注明。[示例](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt5NA-hUwyDajHiu8QnoeEz-3uWwAPSwTXHodnEX6LZ2ANxAA)

![image](https://user-images.githubusercontent.com/41674118/177068746-024cc4e7-be43-4763-8dd3-8e956500686c.png)
ts 声明提示echarts.LineSeriesOption  scale为boolean

**Comment by plainheart** [comment]
似乎是漏掉了，欢迎 PR 或者等后面我们加一下~
