### ISSUE TITLE
[Bug] Getting "TypeError Cannot read properties of undefined"

### ISSUE THREAD

**Issue by KundanJha123** [apache/echarts#17089]
### Version

5.2.1

### Steps to Reproduce

1. On switching on "Pause on exception" in my dev tool in chrome
2. When I reload the app which is using the ECharts.
3. stops at echarts.min.js line 45.
4. gives error - "Cannot read properties of undefined (reading 'get')"
5. 
![image](https://user-images.githubusercontent.com/106071524/169801378-adff30e4-24ae-4fe7-8048-5502c4e57fd1.png)

### Current Behavior

gives error - "Cannot read properties of undefined (reading 'get')"

### Expected Behavior

Resolution of the error

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by KundanJha123** [comment]
[EchartsIssue.zip](https://github.com/apache/echarts/files/8761057/EchartsIssue.zip)
Hi Team,
PFA the demo. just run the index.html file and in dev tool switch on the "Pause on exception".
reload the page. You will get the error.
Thanks

**Comment by tyn1998** [comment]
Hello @KundanJha123 , it seems that `index.html` you provided is an empty file except for a pair of `<script></script>` tag.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/32434520/170638796-7f01c09d-6174-43fb-8611-82d0b57dd5a9.png">

**Comment by KundanJha123** [comment]
yes. We are testing the Js file I have provided with it. You can just run this html file and in developer tool of chrome you will get exception

**Comment by tyn1998** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/32434520/170640857-8fab7fde-a7c4-4e48-bc73-ddb4c859facd.png">

Ok, I got this, too. I also ran the fresh-built echarts.min.js and got same result.

I have no idea...wait for someones who know the issue.

**Comment by KundanJha123** [comment]
Sure Thank you

**Comment by KundanJha123** [comment]
Hi Team, Any updates on this issue??

**Comment by KundanJha123** [comment]
Hello. is there a way to fix this issue?

**Comment by KundanJha123** [comment]
Hi All. Can have an update on this please. Because of this our project is failing.

**Comment by plainheart** [comment]
Please be detailed on how it fails and how it affects your project.

**Comment by KundanJha123** [comment]
Hi, You can see in above conversations. I have shared a demo as well.

**Comment by plainheart** [comment]
I've seen your demo. It only runs the script of ECharts. But the exception will be caught internally, it won't affect your project theoretically.

**Comment by KundanJha123** [comment]
Yes. But customers want and exception free app

**Comment by plainheart** [comment]
So what can't work due to this exception? Please provide more information.

**Comment by KundanJha123** [comment]
I just wanted to know if we can fix this issue by any chance? Or any future update can fix it?

**Comment by plainheart** [comment]
No. It's by design. This exception may occur when initializing the script as ECharts needs to collect the required information when installing components. But it won't make something not work as it can be caught internally.

**Comment by KundanJha123** [comment]
Hi, Can you help me out how can I handle this exception in my project?

**Comment by stephensander1161** [comment]
We are having the same issue and it is causing no data to show up on the graph without refreshing the page.
