### ISSUE TITLE
[Bug] 旧版本官网打不开

### ISSUE THREAD

**Issue by Lan-W** [apache/echarts#17085]
### Version

e.g.4/3

### Steps to Reproduce

1.打开就版本官网
2.页面显示错误
3.很多资源加载不出来，打不开~~也用不了

### Current Behavior

![image](https://user-images.githubusercontent.com/20930703/169754198-51591706-6999-44b1-897a-ef058bfb666c.png)
[https://echarts.apache.org/v4/zh/option.html](url)

### Expected Behavior

希望能正常使用，需要查询旧版配置项

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Lan-W** [comment]
ok

**Comment by binhong-chen** [comment]
![image](https://user-images.githubusercontent.com/67321758/169791286-2691012c-bb44-4ee5-91f4-df87fecd8f2e.png)

![image](https://user-images.githubusercontent.com/67321758/169790898-9e4ef5e6-d711-4925-8f6d-f8d5b8cc7a4a.png)

在国内pc端访问echarts官网基本上失败

**Comment by Lan-W** [comment]
新版的我这倒是也能打开，旧版本不行





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月23日(星期一) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] 旧版本官网打不开 (Issue #17085)





 

 

 
在国内pc端访问echarts官网基本上失败

**Comment by Lan-W** [comment]
hope this problem can be solved

**Comment by plainheart** [comment]
可以先用新的，旧版的因为 CDN 域名未替换，可能会打不开。

**Comment by Lan-W** [comment]
非常感谢，这个镜像路径可以正常使用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 凌晨1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] 旧版本官网打不开 (Issue #17085)





 
可以先用新的，旧版的因为 CDN 域名未替换，可能会打不开。
