### ISSUE TITLE
[Bug] A broken link found in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tyn1998** [apache/echarts#17088]
### Version

5.3.2

### Link to Minimal Reproduction

https://github.com/apache/echarts/blob/master/CONTRIBUTING.md#issues

### Steps to Reproduce

1. Go to CONTRIBUTING.md
2. In [Issues section](https://github.com/apache/echarts/blob/master/CONTRIBUTING.md#issues)
3. Click the link "echarts issue helper"
4. Will be redirected to a 404 page
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/32434520/169791674-59cdfb16-efb1-4c0b-ac72-e43c8f578760.png">

### Current Behavior

None

### Expected Behavior

None

### Environment

```markdown
- OS: MacOS Monterey(Apple Silicon)
- Browser:  Google Chrome 101.0.4951.64（正式版本） (arm64)
- Framework: None
```

### Any additional comments?

Just a tiny broken link~

I suppose the broken link my be now as https://github.com/apache/echarts/tree/master/.github/ISSUE_TEMPLATE ?

**Comment by susiwen8** [comment]
Right, we no longer need it, it can be removed, could you make a PR for it.

**Comment by tyn1998** [comment]
> Right, we no longer need it, it can be removed, could you make a PR for it.

With pleasure!
