### ISSUE TITLE
图表的Y轴单位，可以设置html么，目前只能接收文本字符串

### ISSUE THREAD

**Issue by Topthinking** [apache/echarts#17099]
如题

**Comment by li942475402** [comment]
if you expect get style by html,try `rich`

**Comment by li942475402** [comment]
you also can set yLabel opacity to 0,then use `echarts.getModel.getComponent('yAxis')` and `echarts.getViewOfComponent($model)` get these label's position, draw them by html

**Comment by susiwen8** [comment]
- [#16916](https://github.com/apache/echarts/issues/16916#issuecomment-1103570927)
