### ISSUE TITLE
[Bug]  xAxis.axisPointer.label sometimes does not disappear

### ISSUE THREAD

**Issue by frank-pian** [apache/echarts#17091]
### Version

5.3.2

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=line-tooltip-touch

### Current Behavior

Swiping 'handel' repeatedly causes the label to stay on the page.

### Expected Behavior

https://user-images.githubusercontent.com/8214804/169851721-47d2a6e1-7a24-43b5-9b8a-744831b7cd0b.mp4

### Environment

```markdown
- OS: win10
- Browser: firefox
- Framework:
```

**Comment by li942475402** [comment]
This seems to be an old question,try `myChart.dispatchAction({type:'updateAxisPointer'})`
