### ISSUE TITLE
[Bug] Setting axisLabel.show to false does not work in Parallel Graph

### ISSUE THREAD

**Issue by elenzio9** [apache/echarts#17103]
### Version

5.3.2

### Steps to Reproduce

1. Load echarts
2. Use Basic Parallel Graph

### Current Behavior

According to the documentation, the default value of `axisLabel.show` is true. However, setting it to false to prevent the axis label from appearing seems to have no effect.

I added the code bellow to the [online example:](https://echarts.apache.org/examples/zh/editor.html?c=parallel-simple)

```
option = {
  parallelAxis: [
    { dim: 0, name: 'Price' },
    { dim: 1, name: 'Net Weight' },
    { dim: 2, name: 'Amount', 
      axisTick: {
        show: false
      },
      axisLine: {
        show: false
      },
      axisLabel: {
        show: false
      }
    }
  ],
  series: {
    type: 'parallel',
    lineStyle: {
      width: 4
    },
    data: [
      [12.99, 100, 82],
      [9.99, 80, 77],
      [20, 120, 60]
    ]
  }
};
```
and it has the following effect:
![image](https://user-images.githubusercontent.com/87971102/169828558-8eacac6c-4485-4469-a902-839412ca043f.png)

### Expected Behavior

The expected behavior would be for the axis label to disappear as is the case with axis ticks and line.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by adeelz92** [comment]
Same issue here. It doesn't work.

**Comment by sb-relaxt-at** [comment]
This issue still exists in 6.0.0
