### ISSUE TITLE
[Bug] 最新版本echarts  xAxis.axisTick.interval 函数的方式，如果只判断一个值为true，坐标轴刻度的显示间隔失败

### ISSUE THREAD

**Issue by yuelinghunyu** [apache/echarts#17108]
### Version

5.3.2

### Steps to Reproduce

vue + charts + vue-echarts

### Current Behavior

<img width="321" alt="image" src="https://user-images.githubusercontent.com/21078444/170256848-a437d10b-3ac0-4eb9-9398-3fea08f56ae5.png">

展示如下：
![image](https://user-images.githubusercontent.com/21078444/170256902-05a0a212-0851-4613-ada9-0c923f88ed65.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/21078444/170257208-ab5da98b-67ba-4f90-b957-07cc40e42aeb.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
根据文档，`interval` 只在类目型坐标轴中支持，这个问题是什么类型的坐标轴呢，提供个例子吧
