### ISSUE TITLE
[Feature]  I need a tooltip containing the data text on hovering over Y-axis data in Binary echart.

### ISSUE THREAD

**Issue by stuti24sinha** [apache/echarts#17114]
### What problem does this feature solve?

In case if the  text of y-axis data is too large to be fully read at one glance , hovering over the data can give a tooltip containing the full name of the data. This will be useful for the customers to clearly see the data name.

### What does the proposed API look like?

y-axis: {
data : {
values: [ ],
tooltip: [ ]
}
}

**Comment by li942475402** [comment]
you can get it by yourself,just add a upper level to show the content you want
like this example:https://echarts.apache.org/handbook/zh/how-to/interaction/drag
