### ISSUE TITLE
[Feature] Enable Sankey series link to have different values or "weights" at source and target node 

### ISSUE THREAD

**Issue by c3-anerishah** [apache/echarts#17121]
### What problem does this feature solve?

Since Sankey charts show the movement of some unit (call it a deal for the sake of an example) over time, if the amount of money associated with a particular deal changes from $10 at the start date to $20 at the end date, it would be nice for the width of the link to start out slightly thinner (proportional to $10) and end wider (proportional to $20). Since the value of the link contributes to the calculation of the height of each node, this feature would allow the height of the source node to use $10 as the weight of the outgoing edge and the height of the target node to use $20 as the weight of the incoming edge.

### What does the proposed API look like?

The configuration object for each link (https://echarts.apache.org/en/option.html#series-sankey.links) would have an additional field `endValue`, which, if not specified, would default to the number specified by `value`. `value` would represent the weight of the link for the source node (as it does currently) and `endValue` would represent the weight of the link for the target node.

**Comment by Risingson** [comment]
please reconsider this implementation.

**Comment by nilsmf** [comment]
I would also love to see this feature. Not being able to show growth/loss of a node category between depths is very frustrating. Or worse one of the nodes sizes being artificially enlarged so that proportional sizes get messed up.
