### ISSUE TITLE
heatmap热力图borderRadius属性不生效

### ISSUE THREAD

**Issue by stay3hungry** [apache/echarts#17128]
### Version

5.3.0

### Steps to Reproduce

1、引入5.3.0及以下版本echarts
2、创建热力图如笛卡尔坐标系热力图:https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian
3、设置borderRadius属性
      itemStyle: {
      	borderRadius: 10,
      }

### Current Behavior

热力图未产生圆角，borderRadius不生效

### Expected Behavior

热力图圆角为10px

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by pissang** [comment]
该配置在 5.3.1 中才引入

**Comment by stay3hungry** [comment]
> 该配置在 5.3.1 中才引入
哦哦~ 麻烦在配置项中标注一下。
