### ISSUE TITLE
[Bug] 矩形树图data下的itemStyle里的borderColor影响了color！

### ISSUE THREAD

**Issue by zhanghaodashuai** [apache/echarts#17126]
### Version

5.1.1

### Steps to Reproduce

1、生成矩形树图
2、每个矩形块通过itemStyle里的borderColor设置不同的边框颜色(每个矩形块有各自的颜色和边框色)
3、矩形块的color有透明度时，会受边框颜色影响，似乎此处的边框是整个背景色

demo: https://codepen.io/zhanghaodashuai/pen/OJQzxJZ?editors=0110

### Current Behavior

矩形块的color有透明度时，会受边框颜色影响，似乎此处的边框是整个背景色

### Expected Behavior

不影响矩形块颜色

### Environment

```markdown
- OS:windows
- Browser:chrom
- Framework:react
```

**Comment by zhanghaodashuai** [comment]
暂未解决

**Comment by zhanghaodashuai** [comment]
暂未解决

**Comment by CYBYOB** [comment]
I would like to fix this issue
