### ISSUE TITLE
[Bug]移动端 dataZoom-slider移动滑块与整体页面滑动冲突

### ISSUE THREAD

**Issue by honghongzm** [apache/echarts#17129]
### Version

5.2.2及之前版本

### Steps to Reproduce

var dataZoom = [
	  {
		type: 'slider',
		show: true,
		realtime: true,
		textStyle:{
			color:colorSet.FontColorY
		},
		selectedDataBackground:{
			lineStyle:{
				opacity:0
			}
		},
		moveHandleStyle:{
			opacity:0
		} ,
		start: 16,
		end: 100,
	  }
];

### Current Behavior

移动端dataZoom-slider点击滑块向左向右滑动滑块，整个页面会跟着一起动

### Expected Behavior

移动端dataZoom-slider点击滑块向左向右滑动滑块，整个页面会跟着一起动，有没有什么办法可以解决滑动滑块的时候整个页面不要跟着动，

看文档只有inside时才有[preventDefaultMouseMove]这个属性，slider没有这个属性，所以不知道有没有什么其他办法呢

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Gaks327** [comment]
https://user-images.githubusercontent.com/52275843/172783248-fb05af49-27d4-4011-b5e8-0991bd5479f0.mp4


let option = {
                    tooltip: {
                        trigger: 'item',
                        formatter: '{b} <br/>数量：{c}'
                    },
                    grid: {
                        x: 60,  //
                        y: 20,  //
                        x2: 40, //
                        y2: 150  //
                    },
                    xAxis: {
                        name: '数量',
                        nameTextStyle: {      
                            padding: [0, 0, 0, 0],
                        },
                        type: 'category',
                        data: xData,
                        splitArea: true,
                        axisLine: {
                            lineStyle: {
                                color: '#D5F7FF',
                                width: 1,
                            }
                        },
                        axisLabel: {
                            interval: 0,
                            textStyle: {
                                color: '#D5F7FF',
                            },
                            formatter: function (value) {
                                return value.split("").join("\n");
                            }
                        },
                    },
                    yAxis: {
                        type: 'value',
                        axisLabel: {
                            textStyle: {
                                color: '#D5F7FF',
                            },
                        },
                        axisLine: {
                            lineStyle: {
                                color: '#D5F7FF',
                                width: 1,
                            }
                        },
                    },
                    dataZoom : [
                        {
                            type: 'slider',
                            xAxisIndex: [0],
                            filterMode: 'filter',
                            show: true,
                            start: 1,
                            end: 10,
                        }
                    ],
                    series: [{
                        data: yData,
                        type: 'bar',
                        itemStyle: {normal: {color: '#01DFC6'}}
                    }]
                };
                
Same problem as above
