### ISSUE TITLE
你好，点阵图y轴能不能配置等距不等分[Feature] 

### ISSUE THREAD

**Issue by hi-mashuo** [apache/echarts#17124]
### What problem does this feature solve?

无

### What does the proposed API look like?

无

**Comment by Ovilia** [comment]
请详细描述你的问题

**Comment by hi-mashuo** [comment]
您好，我的问题主要是echarts轴线问题，我看了文档，找不到关于等距不等分的解决方案，意思是把x轴或者y轴平均分成五份，正常情况下是每份占比百分之二十，但是我想实现的是第一个刻度占比百分之六十，第二个刻度占比百分之二十，第三个刻度占比百分之十，第四个刻度占比百分之八，第五个刻度占比百分之二，虽然每部分占比不同，但是实际上用户看到的页面比例是一样的，可能我描述的不太准确，希望官方可以给一个好的解决方案.

**Comment by tyn1998** [comment]
感觉[对数轴](https://echarts.apache.org/zh/option.html#yAxis.type)是类似你所描述的效果。。

**Comment by hi-mashuo** [comment]
![FB3CE](https://user-images.githubusercontent.com/62926576/172111471-53893664-e711-4d06-a630-a73606f5c804.png)
这种的效果

**Comment by hi-mashuo** [comment]
> 你好@hi-mashuo, 感觉[对数轴](https://echarts.apache.org/zh/option.html#yAxis.type)是类似你所描述的效果。。
> 
> ![图片](https://user-images.githubusercontent.com/32434520/171837855-f40a1eaf-e1f3-4f05-b60f-130c130b01d6.png)
> 
> 这个[散点图](https://github.com/tyn1998/dummy-charts/blob/main/src/dummyCharts/ScatterTimeline/ScatterTimeline.jsx)的x轴和y轴就是取了对数的效果。

和这个类似但是不太一样，对数轴是按固定倍率递增的，有一定的规律，但是我想实现的效果毫无规律

**Comment by susiwen8** [comment]
try [formatter](https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter)

**Comment by hi-mashuo** [comment]
> 尝试[格式化程序](https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter)
我试了，只能改显示文本，但是改不了实际值

**Comment by susiwen8** [comment]
相当难做，基本不考虑实现。之前实现双轴刻度对齐都花了相当大的功夫。

**Comment by hi-mashuo** [comment]
好的，有没有别的解决方案之类的

**Comment by Ovilia** [comment]
> ![FB3CE](https://user-images.githubusercontent.com/62926576/172111471-53893664-e711-4d06-a630-a73606f5c804.png) 这种的效果

这个是等距的，其实挺好做的，就是 x y 坐标轴用数值轴，实际上是 1 2 3 4 5 这样的值，但是用 axisLabel.formatter 来控制显示的数字就可以了
