### ISSUE TITLE
[Bug] 热力图不能同时根据x,y轴的值排序吗？heatmap can not be sorted based on the x-axis and y-axis

### ISSUE THREAD

**Issue by biankaiwen111** [apache/echarts#17130]
### Version

5.2.2 及之前

### Steps to Reproduce

这是我用来制图的参数(this is the configuration I used to produce the heatmap)

    option={
    "dataset": [
        {
            "id": "raw",
            "dimensions": [
                "Pclass",
                "Age",
                "TotalFare"
            ],
            "source": [
                [
                    3,
                    74,
                    7.775
                ],
                [
                    3,
                    70.5,
                    7.75
                ],
                [
                    2,
                    1,
                    76.0042
                ],
                [
                    2,
                    0.83,
                    47.75
                ],
                [
                    1,
                    55,
                    30.5
                ],
                [
                    1,
                    54,
                    266.81669999999997
                ]

            ]
        },
        {
            "fromDatasetIndex": 0,
            "id": "sorting",
            "transform": {
                "type": "sort",
                "config": [
                    {
                        "dimension": "Age",
                        "order": "asc"
                    },
                    {
                        "dimension": "Pclass",
                        "order": "asc"
                    }
                ]
            }
        }
    ],
    "xAxis": {
        "type": "category",
        "name": "Age",
    },
    "yAxis": {
        "type": "category",
        "name": "Pclass",
    },
    "series": [
        {
            "type": "heatmap",
            "datasetIndex": 1,
            "encode": {
                "x": "Age",
                "y": "Pclass",
            }
        }
    ],
    "visualMap": [
        {
            "dimension": "TotalFare",
            "min": 0,
            "max": 1491.7042,
            "calculable": true,
            "orient": "vertical",
            "bottom": "50%",
            "right": "1%"
        }
    ]}

### Current Behavior

目前的结果是这样(this is the current output)
![1653677876(1)](https://user-images.githubusercontent.com/51461951/170773759-61584441-ade6-428a-9331-0e38b44dd2e1.png)

### Expected Behavior

这是我所期望的结果, 我希望其也能根据y轴来排序， 比如我希望（0.83，2）和（1，2）这两块能在y轴中间位置，例如下图（下图中x轴依然存在乱序的问题）

(this is the excepted output)

![1653678094(1)](https://user-images.githubusercontent.com/51461951/170774234-f67ed0f3-edc5-4b25-a274-1c86b238323f.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dovydasrudys** [comment]
You are asking echarts to make a dataset for you which is first sorted by "Age" dimension, and if the "Age" dimension is equal only then sort it by "Pclass" which then goes like that:
| Position | Age | Pclass |
|-------------------------|
|       1      | 0.83 |    2     |  <---- Lowest Age
|       2      |    1   |    2     |  <---- Age higher than previous
|       3      |   54  |    1     |  <---- Age higher than previous
|       4      |   55  |    1     |  <---- Age higher than previous
|       5      | 70.5 |    3     |  <---- Age higher than previous
|       6      |  74   |    3     |  <---- Age higher than previous

So, essentially you are sorting only by Age. In order to achieve your expected result you want your transform to look like this:
```
"transform": {
            "type": "sort",
            "config": [
              {
                    "dimension": "Pclass",
                    "order": "asc"
                },
                {
                    "dimension": "Age",
                    "order": "desc"
                },
            ]
        }
```
