### ISSUE TITLE
[Feature] 希望可以为折线图lineStyle.width 添加一个回调函数

### ISSUE THREAD

**Issue by shuaiwu95** [apache/echarts#17137]
### What problem does this feature solve?

我在开发地图渲染时，碰到了为不同的线段设置不同的宽度的需求，我查阅了文档，发现lineStyle.width只能设置常量，而无法用回调函数灵活设置。我就只能为每一个线段创建一个对象来单独设置他们的宽度，这么做将无法体验到lines的高性能和便捷性。

### What does the proposed API look like?

希望lineStyle.width支持回调函数：
回调函数格式如下：
(params: Object) => Width

**Comment by Ovilia** [comment]
We are going to extend the ability of varied segments of line series. So this issue can be possibly solved by #17138.
