### ISSUE TITLE
[Bug] 树图点击已收缩节点的相邻节点会导致已收回节点出现收缩不完整

### ISSUE THREAD

**Issue by LuckyTiger12138** [apache/echarts#17131]
### Version

5.3.2

### Steps to Reproduce

官方示例中使用5.2.0之后包含5.2.0版本，已收缩节点的相邻节点点击，收缩的节点会出现问题

### Current Behavior

![image](https://user-images.githubusercontent.com/51999275/170809002-9ca63cdb-5a5d-45e3-9afc-343ce9d6af71.png)

### Expected Behavior

官方示例中使用5.2.0之后包含5.2.0版本，已收缩节点的相邻节点点击，收缩的节点会出现问题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by linghaoSu** [comment]
https://github.com/apache/echarts/pull/16548
I have tried to fix this problem here, but no advanced progress.

**Comment by Richeys** [comment]
When can you release an update to fix this problem？

**Comment by LuckyTiger12138** [comment]
> When can you release an update to fix this problem？I also encountered the same problem in version 5.3.3

I used VUE for my front-end project，My solution is to introduce multiple versions and use the old version of the tree diagram

**Comment by Richeys** [comment]
Which version of the broken line tree can be used normally without this situation

**Comment by LuckyTiger12138** [comment]
> 没有这种情况，哪个版本的折线树可以正常使用

我引入的 5.1.2版本
