### ISSUE TITLE
[Bug] The first of multiple series having different label font from others in scatter plot 

### ISSUE THREAD

**Issue by kayoch1n** [apache/echarts#17149]
### Version

5.1.2

### Steps to Reproduce

1. Create a scatter plot with multiple series using the following options
2. The labels from the first of series are having bold font in white, which differ from other series. The other series are having normal font in black. Is it intented?
```js
option = {
  xAxis: {
    type: 'value',
    scale: true,
    name: '百分比',
    axisLabel: { formatter: '{value}%', rotate: 0 }
  },
  yAxis: {
    scale: true,
    name: '用时',
    interval: 2
  },
  legend: { right: '10%', width: '80%', top: 5, type: 'scroll' },
  series: [
    {
      name: 'prod',
      type: 'scatter',
      data: [
        [62, 3.78, 21, 'prod', 'Banana'],
        [65, 2.78, 21, 'prod', 'peach']
      ],
      label: { show: true, position: 'inside', formatter: '{@[4]}' }
    },
    {
      name: 'test',
      type: 'scatter',
      data: [[100, 1.66, 60, 'test', 'Apple']],
      label: { show: true, position: 'inside', formatter: '{@[4]}' }
    },
    {
      name: 'dev',
      type: 'scatter',
      data: [[80, 1.99, 60, 'dev', 'dragonfruit']],
      label: { show: true, position: 'inside', formatter: '{@[4]}' }
    }
  ],
  visualMap: {
    show: false,
    dimension: 2,
    inRange: { symbolSize: [10, 30] },
    min: 1,
    max: 80
  }
};

```

![image](https://user-images.githubusercontent.com/59444375/171586125-090fc010-2c15-483b-9266-6c9f4f498a5d.png)

### Current Behavior

The first of multiple series, dots named "banana" and "peach" lying on the left of the plot,  are having different label font from others

### Expected Behavior

All series have the same font by default

### Environment

```markdown
- OS: windows 10
- Browser: chrome 101.0.4951.67
- Framework: vue 2.6
```

**Comment by plainheart** [comment]
It is by design. See also https://github.com/apache/echarts/issues/15347#issuecomment-880361896
