### ISSUE TITLE
[Bug] 官网无法正常访问

### ISSUE THREAD

**Issue by szmxx** [apache/echarts#17140]
### Version

5.3.2

### Steps to Reproduce

1、输入 https://echarts.apache.org/
2、显示网站无法连接

### Current Behavior

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/24505926/171158632-269c2e84-a45d-4eb7-981d-f6d928549a71.png">

### Expected Behavior

正常访问网站

### Environment

```markdown
- OS: macOS
- Browser: Chrome 101.0.4951.64
- Framework:
- Network: Internet
- Area: China
```

**Comment by plainheart** [comment]
现在还是不行吗？

**Comment by szmxx** [comment]
是的，我刚用手机端试了还是无法访问，坐标深圳

**Comment by plainheart** [comment]
不过很抱歉，我们可能不太能帮到什么，大部分地区应该还是正常的。

**Comment by szmxx** [comment]
啊，好吧，我让我同事也访问了下，他的也有问题🤨

**Comment by sunttz** [comment]
大部分地区都访问不了

**Comment by szmxx** [comment]
应该是网站托管到海外服务器了，国内访问没有 VPN 访问都有问题

**Comment by Ovilia** [comment]
如果是整个域名都解析不出来（而不是部分资源的话），可能比较难，因为取决于 Apache 服务器节点。如果持续有这个问题，我们会向 Apache 软件基金会反馈，看看有没有解决方案。

**Comment by webtaotao** [comment]
> 
您好，有结果了吗  大家都等着用呢   ┭┮﹏┭┮

**Comment by plainheart** [comment]
@webtaotao 你是打不开官网吗？试一下 151.101.2.132 能否 ping 通。

**Comment by webtaotao** [comment]
收到，可以ping通的，是我们单位网络配置问题吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] 官网无法正常访问 (Issue #17140)





 
@webtaotao 你是打不开官网吗？试一下 151.101.2.132 能否 ping 通。

**Comment by plainheart** [comment]
@webtaotao 嗯，有这个可能。如果 IP 可以 ping 通，感觉应该是能够打开网站的。

**Comment by webtaotao** [comment]
好的，谢谢您百忙中回复我哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] 官网无法正常访问 (Issue #17140)





 
@webtaotao 嗯，有这个可能。如果 IP 可以 ping 通，感觉应该是能够打开网站的。
