### ISSUE TITLE
Adding a pointer cursor for weChat

### ISSUE THREAD

**Issue by psankhe28** [apache/echarts#17151]
### What problem does this feature solve?

On hovering on weChat,one can't make out if he/she has actually hover because the cursor doesnt change
![image](https://user-images.githubusercontent.com/84843461/171800600-a86a610d-1640-4f3d-bd67-c0db74e1b1a7.png)

### What does the proposed API look like?

Just adding the css would be enough to solve the particular issue

**Comment by plainheart** [comment]
Hi, @psankhe28 Thanks for your feedback! The WeChat icon has no cursor pointer as it's not a link and just a qrcode.

**Comment by psankhe28** [comment]
Okay.Thanks for pointing that out.
