### ISSUE TITLE
Overflow Scroll for Echarts Containers 

### ISSUE THREAD

**Issue by nhhaidee** [apache/echarts#17153]
### What problem does this feature solve?

I would like to implement Overflow Scroll for charts as in picture

![overflow_scroll_echarts](https://user-images.githubusercontent.com/30271407/171904909-8e631be3-6872-43e9-9c4b-aa557682f5a4.png)

### What does the proposed API look like?

An API that allows user to implement Overflow Scroll for Echarts Containers

**Comment by plainheart** [comment]
Can't it work if you set `overflow: auto` for the parent container?

**Comment by nhhaidee** [comment]
@plainheart I could not find echarts option `overflow: auto`, can you let me know where I can find it

I have tried either bootstrap `overflow-scroll` or `overflow-auto` but it does not work
`    <div class="tab-pane show active overflow-scroll" id="chart-pane" role="tabpanel">
        <div class="container-fluid" id="chart"></div>
    </div>
`
I am not sure if Echarts supports overflow containers for this moment or not?

**Comment by plainheart** [comment]
It's not an option of ECharts but is a CSS property. I just made an online demo for your reference.
https://codepen.io/plainheart/pen/LYQBdzN

**Comment by nhhaidee** [comment]
@plainheart Thank you. I will try and let you know the results, it will be wonderful if it works

**Comment by nhhaidee** [comment]
@plainheart In your example, I think you initialized 18 chart instances so css `overflow` works correctly.

However, with our tool we initialize only 1 chart instance and sub charts are arranged in grid configuration (see below code), so I think CSS overflow does not works for our case

```
function getFluGrids(samples, segments) {
    let grids = [];
    let padTop = 4.0; // Percentage
    let horizontalOffset = 4.0;
    let verticalOffset = 6.0;
    let padLeft = 4.0;
    let plotHeight = 90.0;
    let samplePlotHeight = (plotHeight - padTop)/samples.length - verticalOffset;
    let samplePlotWidth = (100.0 - padLeft)/segments.length - horizontalOffset;
    if (samplePlotWidth < 15.0){
        samplePlotWidth = 15.0
    }
    for (let i = 0; i < samples.length; i++){
        for (let j = 0; j < segments.length; j++){
            grids.push({
                show: true,
                top: padTop + i * (samplePlotHeight + verticalOffset) + '%',
                height: samplePlotHeight + '%',
                left: padLeft + j * (samplePlotWidth + horizontalOffset) + '%',
                width: samplePlotWidth + '%',
                borderColor: 'red'
            });
        }
    }
    return grids;
}
```
