### ISSUE TITLE
[Bug] nameMap does not work with svg while using registerMap,geoJson works normal

### ISSUE THREAD

**Issue by falcon95** [apache/echarts#17156]
### Version

5.3.2

### Steps to Reproduce

1. Open the demo, https://echarts.apache.org/examples/zh/editor.html?c=geo-beef-cuts
2. Add nameMap:{"Filet":"菲力牛排"} in series, it's not work
3. The demo https://echarts.apache.org/examples/zh/editor.html?c=map-HK works normal

### Current Behavior

nameMap does not work with svg while using registerMap

### Expected Behavior

nameMap support svg

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Hi @falcon95, as per the statement in [#14571](https://github.com/apache/echarts/pull/14571#:~:text=Do%20not%20support%20nameMap%20in%20geoSVG%20until%20some%20real%20requirements%20come.) and the comment in the source code, this feature is now unsupported.
