### ISSUE TITLE
[Bug] Stacked bar chart is broken when you use encode to get the data

### ISSUE THREAD

**Issue by Shaq76** [apache/echarts#17154]
### Version

5.3.2

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/editor.html?code=DYUwLgBAJghmMQLwQNoCgKoORYDQSwDUBGPAwgJiwF1cNsBBMgNgFYAWV_Nz2-lLACEyFZmPysAzJIp9MAgMIsAHAHZ8FAAzNic7ABEyxTRXztNy6mmoBuNGlCQA9gAcwASycA7QQCcnANYgXkgQAN70sPAAzuAAXOEQ0U4Arr4AxiAJUQgAvnSYAB4Mhe7RCWEQYACeLlkE6XAgAOZOvtVYEPn01SVlFd2Ysb7uIOWo9JgRmDNVtfVYAEYwvniTM8HpTlD1lYUJmvjVCcRdBbNJ8OkBCVhgTvDAWOuDM9MXNXW3y6vns5vbXYQfYQQ4QY4QChndZDK43Aj3R7PWa5ehWXJ2BzgCCuDzeADqbQC0VC72KpXG70wnwWjTALTaHT-0DgMGyrJhEAAdABbGAuAAUAsKAEokAA-YEoTTUEWcrkAM3cwHpviFhSOYsQkqpF184DSIWqEAAhMhNHYLl05ZhXr0KQNzsNRuN0LNddT5t8VmsrTl2fBOZhefz1VrJYUULobVbuUqVSA1cLNRLwkGZvqwIbwabzZbY7kRczYTBrrdETAni9mR65l8CD9fRd_SzA7HuXzBcLw1LZDGrYrlar1SntWn25hM9njWbQfmrYXi5dS_C7g9K8iZqjMOjMQB6Pc4tyeELIXEnwm-Yloc_eUK3nz-IJeGxAA)

### Steps to Reproduce

```js
let data = [
  ['', 'V1', 'V2'],
  ['A', 6545, 6545],
  ['B', 2666, 5332],
  ['C', 687, 2061],
  ['D', 102, 408]
];

let optionBroken = {
  dataset: { source: data },
  xAxis: { type: 'category' },
  yAxis: {},
  series: [
    {
      type: 'bar',
      encode: { x: 0, y: 1 },
      stack: 'total'
    },
    {
      type: 'bar',
      encode: { x: 0, y: 2 },
      stack: 'total'
    }
  ]
};

let optionWorks = {
  xAxis: {
    type: 'category',
    data: data
      .map((x) => x[0])
      .filter((x, y) => {
        return y != 0;
      })
  },
  yAxis: {},
  series: [
    {
      type: 'bar',
      data: data
        .map((x) => x[1])
        .filter((x, y) => {
          return y != 0;
        }),
      stack: 'total'
    },
    {
      type: 'bar',
      data: data
        .map((x) => x[2])
        .filter((x, y) => {
          return y != 0;
        }),
      stack: 'total'
    }
  ]
};

// option = optionWorks
option = optionBroken;
```

### Current Behavior

The y axis appears to have no scale and one of the series is missing:
![image](https://user-images.githubusercontent.com/19664605/171919657-e05ea905-cc8a-4e6e-9c7a-8ef8687dd52f.png)

### Expected Behavior

The y axis stacks, as with the explicit data assignment version:
![image](https://user-images.githubusercontent.com/19664605/171919784-f89fffc7-ce91-42a1-85a1-389c9b8c8471.png)

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
```

### Any additional comments?

I would like to use the 'encode' version of the code as it's neater but I may have to revert all my code to work around this issue.
Also I'm loving echarts, well done to all involved!

**Comment by tyn1998** [comment]
Hi @Shaq76, I think dimention name cannot be "". Please give it a name then the `optionBroken` works too.

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/32434520/171971743-5b45abfc-cfc3-40b0-a2e3-3df360e71e70.png">

By the way, if you want render your code correctly in comment, please wrap it with a pair of \``` rather single \`:

 \```javascript
let option = {
    ...
}
\```

**Comment by Shaq76** [comment]
Brilliant, thanks @tyn1998 for your help, you've unblocked my days work!
