### ISSUE TITLE
[Feature] how to know which components are used by echarts

### ISSUE THREAD

**Issue by fuzi1996** [apache/echarts#17157]
### What problem does this feature solve?

when I use `use` api to regist components, I want to know that is a specific components is registed? In other words, I want to get a colleaction about registed components

### What does the proposed API look like?

```javascript
// return an array that contains component type such as ['bar'] 
ECharts.getRegistedChart()

// ['svg']
ECharts.getRegistedRenderer()

// ['title','dataset']
ECharts.getRegistedComponents()

// or more specific api to know is it registed
// true: registed;false unregisted
ECharts.isBarChartRegisted()
```

**Comment by fuzi1996** [comment]
I got a solution to know is chart used by `use` api?
```javascript
let ECHARTS_COMPONENT_MODEL = null
let ECHARTS_COMPONENT_VIEW = null
let ECHARTS_SERIES_MODEL = null
let ECHARTS_CHART_VIEW = null

const fakeComponent = {
  install (extensionRegisters) {
    const {
      ComponentModel,
      ComponentView,
      SeriesModel,
      ChartView
    } = extensionRegisters
    ECHARTS_COMPONENT_MODEL = ComponentModel
    ECHARTS_COMPONENT_VIEW = ComponentView
    ECHARTS_SERIES_MODEL = SeriesModel
    ECHARTS_CHART_VIEW = ChartView
  }
}

// BarChart
ECHARTS_COMPONENT_MODEL.getClass('series','bar')
// LineChart
ECHARTS_COMPONENT_MODEL.getClass('series','line')
// PieChart
ECHARTS_COMPONENT_MODEL.getClass('series','pie')
// MapChart
ECHARTS_COMPONENT_MODEL.getClass('series','map')
// RadarChart
ECHARTS_COMPONENT_MODEL.getClass('series','radar')
// ScatterChart
ECHARTS_COMPONENT_MODEL.getClass('series','scatter')
// EffectScatterChart
ECHARTS_COMPONENT_MODEL.getClass('series','effectScatter')
```

**Comment by Ovilia** [comment]
This should be transparent to developers. Why do you need to call this?

**Comment by fuzi1996** [comment]
我们针对echarts做了一个低代码工具，为了减少最终打包的体积，需要按需加载。如果加载了不同的echarts组件就会有不一样的展示，比如加载了linechart，就展示我们封装的折线图组件，反之就不展示。因此我需要知道echarts里面加载了哪些资源

We have made a low code tool for ecarts. In order to reduce the final packaging volume, we need to load on demand. If different ecarts components are loaded, there will be different displays. For example, if linechart is loaded, the line chart components we encapsulated will be displayed. Otherwise, they will not be displayed. So I need to know which resources are loaded in echarts

**Comment by Ovilia** [comment]
I don't think we have such APIs. You can try to fork and expose this information. Although I'm not sure if we will expose this information, at lease you can use your forked version to get this information.
