### ISSUE TITLE
柱状图不支持割断

### ISSUE THREAD

**Issue by zgLiuBing** [apache/echarts#17160]
### What problem does this feature solve?

柱状图不支持割断

### What does the proposed API look like?

柱状图不支持割断

**Comment by susiwen8** [comment]
Please provide more info, otherwise we have no idea what you want

**Comment by Ovilia** [comment]
![image](https://user-images.githubusercontent.com/779050/172285535-2621077f-ab1a-4e1f-8c5b-5ea706e23fe0.png)

If you want something like this, the current design of axis cannot easily be adapted to this. A pull request is welcomed be I guess it's not an easy job to do.

**Comment by 18300618319** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月6日(星期一) 晚上6:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 柱状图不支持割断 (Issue #17160)






请提供更多信息，否则我们不知道你想要什么

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个，因为你被提到了。留言 ID ***@***.***与&gt;

**Comment by 18300618319** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月6日(星期一) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] 柱状图不支持割断 (Issue #17160)






@18300618319看起来你不是在用英语，我帮你自动翻译了内容。为了让更多的人理解你的问题并得到帮助，我们建议下次使用英语。🤗
翻译

标题

直方图不支持拆分

身体

这个功能解决了什么问题？

直方图不支持拆分

拟议的 API 是什么样的？

直方图不支持拆分

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个，因为你被提到了。留言 ID ***@***.***与&gt;
