### ISSUE TITLE
[Feature] axisPointer can not set line height

### ISSUE THREAD

**Issue by cbbfcd** [apache/echarts#17163]
### What problem does this feature solve?

like this image 

![XBCNZD.png](https://s1.ax1x.com/2022/06/06/XBCNZD.png)]

this line can set height, like '150%'

### What does the proposed API look like?

height: '150%'

**Comment by plainheart** [comment]
Do you mean you hope to get the line dash offset larger?

**Comment by cbbfcd** [comment]
@plainheart yes, hopefully that line can control its length, even beyond the chart

**Comment by cbbfcd** [comment]
or there is another workaround?

**Comment by plainheart** [comment]
Unfortunately, you can't control the line's length but you can adjust the [dash offset](https://echarts.apache.org/option.html#axisPointer.lineStyle.dashOffset) or [dash type](https://echarts.apache.org/option.html#axisPointer.lineStyle.type).

**Comment by cbbfcd** [comment]
@plainheart 😂，i will try find some `hack` way.

**Comment by Ovilia** [comment]
Why would you want its length to be larger than the grid area?

**Comment by cbbfcd** [comment]
@Ovilia , problems encountered in business, designers hope to have such interaction. when the upper and lower charts are linked, it is more like a common coordinate system, and the extended lines can also be connected to some prompt boxes.

**Comment by Ovilia** [comment]
ECharts uses [connect](https://echarts.apache.org/en/api.html#echarts.connect) to link the interactions between charts. Please check if it helps.

**Comment by cbbfcd** [comment]
We use `connect` to achieve linkage, but `axisPointer` does not support setting line length, only `width` can be set.

**Comment by Ovilia** [comment]
Techinically, axisPointer should never be outside of the grid area. You may do some hack or fork to change the source code.

**Comment by cbbfcd** [comment]
ok, thx @Ovilia
