### ISSUE TITLE
series.pie中hover相关属性找不到，emphasis无效

### ISSUE THREAD

**Issue by Mr-Lixiaoqaing** [apache/echarts#17169]
### Version

4.9.0

### Steps to Reproduce

![`FN1S76O8 T(@XH1 EMVW}7](https://user-images.githubusercontent.com/52234930/172314576-e72f968c-2fc6-45de-816f-e0a09219f77b.png)
这是我之前使用的属性，用来防止鼠标移入时饼图的图形区域放大，现在在文档中找不到这两个属性了

但是emphasis属性貌似是用来代替它们的，不过放在代码里不起作用
这是我的代码
![CDAEZSTG28KIJ%C%2DF JT7](https://user-images.githubusercontent.com/52234930/172315021-a7c1f216-0ac6-4bec-8cee-b21405f40ab1.png)
难道emphasis不是用来代替hover相关的那两个api的吗？

### Current Behavior

上边已经描述了

### Expected Behavior

hoverOffset这个api还能不能愉快地使用了，我是不是应该用emphasis来代替它。
如果是，那请帮我看看我的代码中emphasis为什么不起作用
如果不是，为什么文档里找不到这个api了

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
`hoverAnimation` 从 v5.0.0 开始已经[被弃用](https://echarts.apache.org/handbook/zh/basics/release-note/v5-upgrade-guide/#:~:text=%E9%80%89%E9%A1%B9%20series.hoverAnimation%20%E5%B7%B2%E4%B8%8D%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8%EF%BC%8C%E4%BD%BF%E7%94%A8%20series.emphasis.scale%20%E4%BB%A3%E6%9B%BF%E4%B9%8B)，请使用 [`emphasis.scale`](https://echarts.apache.org/option.html#series-pie.emphasis.scale) 代替。

**Comment by plainheart** [comment]
另外没发现不生效，参见[测试用例](https://echarts.apache.org/examples/editor.html?c=pie-doughnut&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWzQCGAtlsQOQCCAxuwRrAGI7B6zADRUKYAJ4gmsZiHwix6LPRAALWhghFK1ahna0ANjLA4ArllF6KB41gDKEAF4yADEtgBfa3oAmtGC0xGQ26EiwAG7GlsQAjG4ALAAcwjQMMswOWLQ47GqwAKLQAOYQ0FjM3r42EdFGsbAA7ADMAKxpdIwsACIQOFjsYFU-nuFRMTJtyW6dGSyF9LQQRiM1enWTxCmJc92yAKrQUHCsfhhrY8gTDTItbrPp-8wAahB-WMCwZxfengC6Yi85EBXgA3EA)。

**Comment by Mr-Lixiaoqaing** [comment]
测试用例最低版本为5.0.0，我用的4.9.0，是版本问题吧？但是文档中并没有说emphasis.scaleSize需要的版本为5.0.0呃

**Comment by susiwen8** [comment]
文档页下面有个按钮返回旧版文档的
![Screen Shot 2022-06-07 at 4 37 27 PM](https://user-images.githubusercontent.com/20318608/172335831-93713bca-33e7-4619-b3a4-ca01e6c37d8f.png)

**Comment by Mr-Lixiaoqaing** [comment]
这个旧版本是指5.0以下(不包括5.0)的版本嘛？

> 文档页下面有个按钮返回旧版文档的 ![Screen Shot 2022-06-07 at 4 37 27 PM](https://user-images.githubusercontent.com/20318608/172335831-93713bca-33e7-4619-b3a4-ca01e6c37d8f.png)

**Comment by susiwen8** [comment]
> 这个旧版本是指5.0以下(不包括5.0)的版本嘛？

4.x的版本



> 所以，最新版的文档默认的就是5.0以上的版本咯？

是的

**Comment by Mr-Lixiaoqaing** [comment]
好的，谢谢解答

**Comment by plainheart** [comment]
> 测试用例最低版本为5.0.0，我用的4.9.0，是版本问题吧？但是文档中并没有说emphasis.scaleSize需要的版本为5.0.0呃

这个配置项确实没有版本支持提示，后面我们可以加一下。
