### ISSUE TITLE
[Bug] The server side rendering does not work for heatmap 20K data example

### ISSUE THREAD

**Issue by PeterKang2018** [apache/echarts#17165]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

### Steps to Reproduce

1. Create a node js console project from Visual Studio 2022. 
2. Copy code from https://apache.github.io/echarts-handbook/en/how-to/cross-platform/server/, choose either svg or canvas rendering. Save the generated chart to a .png file.
3. Copy the data form https://echarts.apache.org/examples/en/editor.html?c=heatmap-large.
4. Run the application from Visual Studio.

### Current Behavior

When user server side rendering for https://echarts.apache.org/examples/en/editor.html?c=heatmap-large, the svg and canvas rendering can only generate partial chart. If the data is reduced, for example 50 by 50, then it works.

Looks like server side rendering had problem with large data set.

Also, the canvas rendering will have exception if the following code is not included:

echarts.setCanvasCreator(() => {
  return createCanvas();
}); 

### Expected Behavior

Expect to see the full heatmap.

### Environment

```markdown
- OS: Windows 10
- Browser: n/a
- Framework: node
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/38470604/172235260-6e243f1c-cb1f-47a9-8239-0281af563a04.png)

**Comment by plainheart** [comment]
Did you try to disable animation via `animation: false`?

**Comment by PeterKang2018** [comment]
Yes. I used the "heatmap 20k data" example code. https://echarts.apache.org/examples/en/editor.html?c=heatmap-large
series: [
    {
      name: 'Gaussian',
      type: 'heatmap',
      data: data,
      emphasis: {
        itemStyle: {
          borderColor: '#333',
          borderWidth: 1
        }
      },
      progressive: 1000,
      animation: false
    }
  ]

I also tried to move "animation: false" out of series block, it did not work either.

**Comment by Ovilia** [comment]
`progressive` should be set to 0 to disable progressive rendering. If that does't work, set it to something larger than your data number.

**Comment by PeterKang2018** [comment]
Set progressive to 0 make it work. Thanks!
