### ISSUE TITLE
[Bug] Axis type as value is workable in the heatmap-large example but has to be category in my app

### ISSUE THREAD

**Issue by ZhengRui** [apache/echarts#17164]
### Version

5.3.2

### Steps to Reproduce

```typescript

option = {
  tooltip: {},
  xAxis: [{
    type: 'value',
  }],
  yAxis: [{
    type: 'value',
  }],
  visualMap: [{
    min: 0,
    max: 1,
  }],
  series: [
    {
      name: 'Gaussian',
      type: 'heatmap',
      data: Array.from({length: 10}, (_, i)=> Array.from({length: 10}, (_, j) => [i+.5, j+.5, (i+j)/20])).flat(),
    }
  ]
};

```

### Current Behavior

In the [heatmap-large example](https://echarts.apache.org/examples/zh/editor.html?c=heatmap-large&lang=ts&version=5.3.2) , i can change xAxis and yAxis type to be either `category` or `value`, but in my typescript App, it gives error (using the same minimum option as above for both the example and my app): 
"Heatmap on cartesian must have two category axes". However, i hope the axis to be `value` type so I can set min and max.

### Expected Behavior

Axis type as `value` should also work in my app as in the heatmap-large example

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I am curious why with same version, same option, it works in the Heatmap-large example but not working in my app. I am wondering if it is because I am importing echarts library and then use it in my react project, while the example page is using compiled minified echarts through <script> tag .

**Comment by ZhengRui** [comment]
I found the reason, for Heatmap to be able to use `value` type axis, process.env.NODE_ENV has to be in `production` mode! I was having this issue when I was developing in storybook. After I lauch storybook like this `NODE_ENV='production' yarn storybook` the issue is gone. Good to know in production environment we can use `value` type axis.

**Comment by clfleury** [comment]
Is this ever going to be changed not to rely on NODE_ENV? Assuming the user's NODE_ENV for critical functionality like this seems like very bad practice.

**Comment by zhoupeihuang** [comment]
我的本地无法预览这个热力图，build之后可以，按照ZhengRui的提示，我让本地也实现了这个功能，方便了调试。具体操作是
1. 安装 cross-env
`npm install cross-env --save-dev`
2. 本地调试的, 修改package.json
`   "dev": "cross-env NODE_ENV=production vite",  `
这样本地就可以预览和调试heatMap 了
