### ISSUE TITLE
[Bug]  echarts.use is not effective

### ISSUE THREAD

**Issue by TaurusWood** [apache/echarts#17161]
### Version

5.3.2

### Link to Minimal Reproduction

https://stackblitz.com/edit/react-bqwvqu?file=src/App.js

### Steps to Reproduce

I create a Line Graph， and use `echarts.use([GridComponent, LineChart, CanvasRenderer, UniversalTransition]);` to Implement on demand loading。

Then， I want to verify if it works，So, wo modify code `echarts.use([GridComponent, CanvasRenderer, UniversalTransition]);`，I remove `LineChart` 

But charts can still be rendered this way

### Current Behavior

charts can still be rendered this way, Even if I take out `LineChart` from  `echarts.use`

### Expected Behavior

How do I verify `echarts.use` is valid

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fuzi1996** [comment]
it's this issue same as the feature i suggested ?[[Feature] how to know which components are used by echarts](https://github.com/apache/echarts/issues/17157) Do you want to know was LineChart  used by `use` api?

**Comment by Ovilia** [comment]
Why do you need to call `use`? If you want to build a minimal version of ECharts, try [download builder](https://echarts.apache.org/builder.html).

**Comment by TaurusWood** [comment]
@Ovilia  Because this is more in line with my business scenario，we application is deployed in the intranet environment，and also we must need `npm` for package management

**Comment by TaurusWood** [comment]
@Ovilia  Because this is more in line with my business scenario，we application is deployed in the intranet environment，and also we must need `npm` for package management

**Comment by pissang** [comment]
From my test, the line chart doesn't if the LineChart is removed, which is expected. If I understand it correctly, I think your behavior is because you changed the code, and the preview page was refreshed by HMR. It's not a fresh new environment and the LineChart is still being registered. If you refresh the page, the LineChart will disappear as expected.

**Comment by TaurusWood** [comment]
@pissang thank you
