### ISSUE TITLE
[Bug] 注释里面含有不良信息

### ISSUE THREAD

**Issue by YFAnt** [apache/echarts#17171]
### Version

5.2.2

### Link to Minimal Reproduction

https://github.com/apache/echarts/blob/master/src/chart/treemap/TreemapSeries.ts

### Steps to Reproduce

xxx.xxx.xxx 这个网址能打开

### Current Behavior

跳转不良信息，我用包被安全警告了，还比较巧 我把注释也打进去了。

### Expected Behavior

去除这个换成别的

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
感谢反馈，我们删除下

**Comment by tyn1998** [comment]
这也行，学到了

**Comment by plainheart** [comment]
一时不知道该说什么...

**Comment by YFAnt** [comment]
不知道能不能把我提的这个bug隐藏掉

**Comment by susiwen8** [comment]
> 一时不知道该说什么... 开发者看到上下文语义应该不会认为这是个链接吧。

保险起见，我们还是删了这些有歧义的 @plainheart

**Comment by plainheart** [comment]
嗯嗯 看来 xxx yyy 这些叠词还是不能随便用 谁想到居然可以打开 🤨

**Comment by YFAnt** [comment]
删除我这个issue吧 要不变相引流了，别摊上事了
