### ISSUE TITLE
[Bug] Map initialization problem in Angular

### ISSUE THREAD

**Issue by gabrielnemeth** [apache/echarts#17174]
### Version

5.3.2

### Link to Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-7kavza?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Steps to Reproduce

Just open the example and if it is loaded properly on the first run, refresh the app.

### Current Behavior

The map is not rendered and there are errors in the console:

```
Map USA not exists. The GeoJSON of the map must be provided.
Error: Cannot read properties of undefined (reading 'regions')
[ECharts] `resize` should not be called during main process.
```

### Expected Behavior

Render the map and not throw an error.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Maps should be registered before calling `echarts.init`. See the [demo](https://echarts.apache.org/examples/zh/editor.html?c=map-usa).
