### ISSUE TITLE
[Bug] IOS - Chart not Rendering - No Errors Showing

### ISSUE THREAD

**Issue by GabSison-MAT** [apache/echarts#17183]
### Version

6.0.2

### Steps to Reproduce

The chart is rendered as a component inside a Vue file. 

Tried on android - all seems fine, renders, and shows data. However, on IOS no render at all - have inspected and there is data being passed through.

### Current Behavior

Renders on Android devices, not on IOS safari or Chrome

### Expected Behavior

Render on all browsers.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
There are several things you can check on iOS. Does the container has width and height when calling `echarts.init`? If it's done by a third-party vue lib, it's advised to test without it first to check the container width and height.
