### ISSUE TITLE
[Bug] Regression between 5.2.2 and 5.3.0 on custom series

### ISSUE THREAD

**Issue by anymos** [apache/echarts#17185]
### Version

5.3.0 - 5.3.1 - 5.3.2

### Link to Minimal Reproduction

https://codepen.io/m5ak/pen/gOXxBxw

### Steps to Reproduce

We render elements within custom series and when we try to remove some item from chart (for example data:[]) then echarts throws **next exception: Uncaught TypeError: Cannot read properties of undefined (reading '__ec_inner_26'),** in the console
and items are not removed form chart.

### Current Behavior

We render elements within custom series and when we try to remove some item from chart (for example data:[]) then echarts throws next exception: Uncaught TypeError: Cannot read properties of undefined (reading '__ec_inner_26'),
and items are not removed form chart. Items are just stacked one to another.

### Expected Behavior

Expected is as in previous versions of echarts that element is removed from chart when data item of element is not defined.

### Environment

```markdown
- OS:OSX 12.3.1
- Browser: chrome/firefox/safari
- Framework: none, POJO
```

### Any additional comments?

This is blocking as custom rendering can not be used  with the filter:'none' as the same bug appears.

Beside, this is a regression from the 1.3.0 version so better to tackle it now before it have more impact on version build upon the 1.3.0

**Comment by anymos** [comment]
Hi there, how could I know that this issue is followed up by a team member ?

**Comment by anymos** [comment]
Bumb ... I am a bit puzzled to see that it s still not take in account meanwhile it s quite a regression

**Comment by anymos** [comment]
Finding more and more bug in the lib :( and still no answer from any one here ...  Beginning to wonder is that lib that is not too big/complex and shall be forked to cater specific needs for say time series ...

**Comment by plainheart** [comment]
Sorry for missing your issues. We'll look into this later.

**Comment by anymos** [comment]
> Sorry for missing your issues. We'll look into this later.

No worries, as soon as you see it I am happy, I was a bit worried that it disappears in the stack of error. Thank you very much anyway. I have created a new issue about another point. Probably a easy fix as well. Thank you again :)

**Comment by anymos** [comment]
Hi there, I have build the master including the fix for this and it sounds like the problem is still there when sliding horizontally

```
core.mjs:6484 ERROR TypeError: Cannot read properties of undefined (reading '0')
    at ECharts.<anonymous> (echarts.directive.ts:144:17)
    at Eventful.trigger (echarts.js:1072:37)
    at ECharts.<anonymous> (echarts.js:28809:18)
    at Eventful.trigger (echarts.js:1072:37)
    at ECharts.doDispatchAction (echarts.js:29549:27)
    at ECharts.dispatchAction (echarts.js:29018:26)
    at SliderZoomView._dispatchZoomAction (echarts.js:89793:18)
    at exec (echarts.js:24891:12)
    at SliderZoomView.cb [as _dispatchZoomAction] (echarts.js:24921:13)
    at SliderZoomView._onDragMove (echarts.js:89677:37)
```
