### ISSUE TITLE
[Bug] X-Axis labels are too close to each other during month change on weekly interval

### ISSUE THREAD

**Issue by IrfanNazand** [apache/echarts#17198]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/dynamic-data-time-axis-forked-sdyeeq?file=/index.js

### Steps to Reproduce

1. Choose Dynamic Data + Time Axis- example from echarts: https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2
2. Add 
```
dataZoom: {
    start: 95,
    type: "inside",
    throttle: 50
  },
```
3. Add 
```
axisLabel: {
      formatter: {
        year: "{yyyy}",
        month: "{dd}-{MMM}",
        day: "{dd}-{MMM}",
        hour: "{HH}:{mm}"
      }
   },
```

### Current Behavior

As displayed below, the interval between each tick is supposed to be one week, but during every month or year change, this resets, making the last tick in the previous month and the new tick in a new month too close to each other. 

![Screenshot 2022-06-10 100926](https://user-images.githubusercontent.com/22817338/173021229-b8f5c1d4-3dca-4f87-9399-ae720781bcfb.png)

### Expected Behavior

The x-axis should ignore month changes and keep the same interval between ticks no matter the zoom level.

_No response_

**Comment by Ovilia** [comment]
Time axis labels should be enhanced.
