### ISSUE TITLE
[Bug] When scale is set to 'log' and ymin = 1, and then you update axis Y label the graphic changes

### ISSUE THREAD

**Issue by walmac** [apache/echarts#17199]
### Version

5.3.2

### Link to Minimal Reproduction

https://jsfiddle.net/walmac/ea3nd5uf/78/

### Steps to Reproduce

As you can see in the attached JsFiddle, if you load the chart with the yaxis scale option in 'lineal 'and then you change to 'log' using the toolbox button with the chevron up, then if you push the chevron up you can change how the graphic is changed.

### Current Behavior

The graphic changes where the series have zero value when it should not

### Expected Behavior

once the the graphic is shown in logarithmic it has to stay the same in the values that are zero

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Please modify your demo to minimal data so that we can understand it better.

**Comment by walmac** [comment]
Sorry, what do you mean by minimal data? Do you want me to reduce the data series?.
