### ISSUE TITLE
[Feature] Improve series highlight on legend hover event (by dimming other series)

### ISSUE THREAD

**Issue by EWChina999** [apache/echarts#17200]
### What problem does this feature solve?

It would be useful if you could improve the series line highlight, especially on charts with many lines . 

the example is http://jsfiddle.net/vitorbarbosa/qpByN/

### What does the proposed API look like?

Only highlight the data series when mouse moves over the legend , at same time dimming the rest of series .

![image](https://user-images.githubusercontent.com/104311689/173190281-fcf6ee32-96be-4f80-adda-f893c89df185.png)

**Comment by susiwen8** [comment]
You can use [series-line.blur](https://echarts.apache.org/en/option.html#series-line.blur)
here is [example](
https://echarts.apache.org/examples/zh/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtSgFEAtnQhZKg2JQCq0KHACCrDrulABqEKw4wLABQR4AIhByOAxgbh7UOHRyDAAWsHbQity8ALoCwuiKCiaEsrgAZhQeAMwApG5msAqKOU2UACztFcQARsBgog5UbR2yDDD03Bx0IzhYBGByAK445SJiWGOkprL1mWBbSSeysFp0AG44floAkk4q0vydX3rDpH6aLTXdBgACeIHwHgYlhwimAclBs1GwC2xiyoIA4nQpLB6nQsFocMNzJY6DZKABZGBpSgAFR2NIA6mwabSclsaQAxBQ06iWXmoyhlX5EUEA7TAjDgyGUe74hl7dCEhQ4IGwaydGQ3aB0BwyxzOVzE4hgiFULDFJGyLT0ZhUWnjfFW4g4BwgHJ0LQS2o3erABhbNWUQlYerO2SdEU3WAWKzqgCMACYAAzuePNRNp5PxtPNfruACcqdgieaxcT8eTwuI-lkWujsld7s93vrxD9AaDIbDxoj0dr2t1Mu8vmigXDUrNHgtPAnNsYTHtjqNkZjpJsiZTaYAHJnYPGCzmS3n3Imi-5mmWL5Xq1HiG2G7Amx6vWqH7j_YGqN2J-hVwPZB1PUqDCCIohiCdTRlGdeF7W5bUXDwHXoFdo1jMkEwAVnLDNT2zNNMPzfdz1gS9i36G9vmNd9o2fFs31XDsvw8H84L_fs4KAmUEiSFJIOlc1LTg-c7SQ5cJ3QmwM2LS89zLI9LyI5oSLIi8U1vWAAJ9R90Do19JXQJiuzWHtV3Ym4tPQLiqAyLJcnyQohNXKDBNnYSEKXFCJPXdVd2LAtcNgIsjwCoikxI9Mr33aSNJ-WAyn4ABuIA)

**Comment by EWChina999** [comment]
> You can use [series-line.blur](https://echarts.apache.org/en/option.html#series-line.blur) here is [example](https://echarts.apache.org/examples/zh/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtSgFEAtnQhZKg2JQCq0KHACCrDrulABqEKw4wLABQR4AIhByOAxgbh7UOHRyDAAWsHbQity8ALoCwuiKCiaEsrgAZhQeAMwApG5msAqKOU2UACztFcQARsBgog5UbR2yDDD03Bx0IzhYBGByAK445SJiWGOkprL1mWBbSSeysFp0AG44floAkk4q0vydX3rDpH6aLTXdBgACeIHwHgYlhwimAclBs1GwC2xiyoIA4nQpLB6nQsFocMNzJY6DZKABZGBpSgAFR2NIA6mwabSclsaQAxBQ06iWXmoyhlX5EUEA7TAjDgyGUe74hl7dCEhQ4IGwaydGQ3aB0BwyxzOVzE4hgiFULDFJGyLT0ZhUWnjfFW4g4BwgHJ0LQS2o3erABhbNWUQlYerO2SdEU3WAWKzqgCMACYAAzuePNRNp5PxtPNfruACcqdgieaxcT8eTwuI-lkWujsld7s93vrxD9AaDIbDxoj0dr2t1Mu8vmigXDUrNHgtPAnNsYTHtjqNkZjpJsiZTaYAHJnYPGCzmS3n3Imi-5mmWL5Xq1HiG2G7Amx6vWqH7j_YGqN2J-hVwPZB1PUqDCCIohiCdTRlGdeF7W5bUXDwHXoFdo1jMkEwAVnLDNT2zNNMPzfdz1gS9i36G9vmNd9o2fFs31XDsvw8H84L_fs4KAmUEiSFJIOlc1LTg-c7SQ5cJ3QmwM2LS89zLI9LyI5oSLIi8U1vWAAJ9R90Do19JXQJiuzWHtV3Ym4tPQLiqAyLJcnyQohNXKDBNnYSEKXFCJPXdVd2LAtcNgIsjwCoikxI9Mr33aSNJ-WAyn4ABuIA)

@susiwen8 , thanks for your great help. ECharts is much powerful than Plotly.  I checked this feature on Plotly , it is difficult to realize . there is long discussion here https://github.com/plotly/plotly.js/issues/1847, nobody fixes it.
