### ISSUE TITLE
[Bug] On Radar Chart Axis name Overflow property is not working

### ISSUE THREAD

**Issue by KunalGurav** [apache/echarts#17209]
### Version

5.2.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/42667896/173342169-236665f3-1d23-412b-a812-2cb3e94874d3.png)
`option = {
  title: {
    text: 'Basic Radar Chart'
  },
  legend: {
    data: ['Allocated Budget', 'Actual Spending']
  },
  radar: {
    // shape: 'circle',
    indicator: [
      { name: 'Sales', max: 6500 },
      { name: 'Administration', max: 16000 },
      { name: 'Information Technology', max: 30000 },
      { name: 'Customer Support', max: 38000 },
      { name: 'Development', max: 52000 },
      { name: 'Marketing', max: 25000 }
    ],
    axisName: {
      color:'red',
      overflow:'truncate',
      ellipsis:'...',
      width:10,
    }
  },
  series: [
    {
      name: 'Budget vs spending',
      type: 'radar',
      data: [
        {
          value: [4200, 3000, 20000, 35000, 50000, 18000],
          name: 'Allocated Budget'
        },
        {
          value: [5000, 14000, 28000, 26000, 42000, 21000],
          name: 'Actual Spending'
        }
      ]
    }
  ]
};`

I have used above options as mentioned on the echarts examples.

### Current Behavior

As one can see the axis name or indicators are overflowing and not truncating.

### Expected Behavior

Axis name/ indicators should truncate and end with ellipsis

### Environment

```markdown
Echart examples editor.
https://echarts.apache.org/examples/en/editor.html?c=radar
```

**Comment by leonarf** [comment]
Hello, it seems overflow on axisname still doesn't work for radar charts on echart 5.5.1
Any news about this issue or the linked PR https://github.com/apache/echarts/pull/17212?
