### ISSUE TITLE
[Bug] echarts使用bmap画线之后，使用bmap api添加marker marker的层级在line之下

### ISSUE THREAD

**Issue by baoqing1124** [apache/echarts#17221]
### Version

5.3.2

### Steps to Reproduce

线是通过echarts添加的，marker是通过百度地图添加覆盖物的方法添加的，marker加了延时器也没有用 还是在line的下面，是否有办法可以解决这个问题？
const bmap = myChart.getModel().getComponent('bmap').getBMap();
const point = new BMap.Point(108.96922244809396,34.276268991378295)
const marker = new BMap.Marker(point);
bmap.addOverlay(marker);

<img width="249" alt="image" src="https://user-images.githubusercontent.com/15626996/173805183-b6b00a3d-a3f0-4ce9-9da4-9520e424331c.png">

### Current Behavior

nothing

### Expected Behavior

nothing

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
百度地图扩展暂时没有提供 API 用以控制 ECharts 图层的 z-index。不过有一个变通方法是获取到 ECharts 所在的百度地图自定义图层容器 DOM，然后设置其 z-index 低于 marker 所在图层 DOM 的 z-index。如：

```js
myChart.getZr().painter.getViewportRoot().parentElement.style.zIndex = 300;
```

**Comment by baoqing1124** [comment]
> 百度地图扩展暂时没有提供 API 用以控制 ECharts 图层的 z-index。不过有一个变通方法是获取到 ECharts 所在的百度地图自定义图层容器 DOM，然后设置其 z-index 低于 marker 所在图层 DOM 的 z-index。如：
> 
> ```js
> myChart.getZr().painter.getViewportRoot().parentElement.style.zIndex = 300;
> ```

非常感谢！这个方法成功解决问题。

**Comment by baoqing1124** [comment]
> 百度地图扩展暂时没有提供 API 用以控制 ECharts 图层的 z-index。不过有一个变通方法是获取到 ECharts 所在的百度地图自定义图层容器 DOM，然后设置其 z-index 低于 marker 所在图层 DOM 的 z-index。如：
> 
> ```js
> myChart.getZr().painter.getViewportRoot().parentElement.style.zIndex = 300;
> ```

@plainheart 非常感谢！这个方法成功解决问题了
