### ISSUE TITLE
[Bug] Multiple series with same name only gets one legend

### ISSUE THREAD

**Issue by IrfanNazand** [apache/echarts#17223]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/qutcwp?file=/index.js

### Steps to Reproduce

1. Open an example with multiple series and legends
2. Change the name of two series to something exactly similar
3. Check the following example: https://codesandbox.io/s/qutcwp?file=/index.js

### Current Behavior

If two series have the same name, but different data, the legend will only be displayed for one of the series.

### Expected Behavior

The legend should show legends for the amount of series included in the chart. 
If there are two series with similar names, it should still display two legends for those series.

**Comment by jiawulin001** [comment]
I would suggest you use different name to differentiate series. It's by design that Echarts uses series names to get legends, just like html script uses ID/name to get DOMs and every DOM's ID/name is one and only.

**Comment by IrfanNazand** [comment]
@jiawulin001 I would've done that, but for this case, the data and the names come from an API to which I don't have access.

**Comment by jiawulin001** [comment]
Maybe consider preprocessing the data of 'name' before you feed it into Echarts?
