### ISSUE TITLE
[Feature] series label color supports function

### ISSUE THREAD

**Issue by googirle** [apache/echarts#17222]
### What problem does this feature solve?

Now we can't config the color of label according to the value, since the configuration of color only support constant
`const option = {
...,
series: [
{
    label: {
color: '#eee'
}
}
]`
![image](https://user-images.githubusercontent.com/23491393/173813265-4157bd92-eeab-4d57-9d5b-7596fdd669f1.png)

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/23491393/173791308-a6b3962e-58b0-460c-81e6-db1c4c5167ef.png)
such as :
`option = {
series: [
{
label: {
color: function (value, index) {
        return value >= 0 ? 'green' : 'red';
    }
}
}]`

**Comment by jiawulin001** [comment]
You don't need a new feature to do this. Try using [**Template String**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) which allows you to use `${expression}` in string.
You can refer to the demo below and try altering the value of `num`:
<details>
<summary>Code Sample</summary>

```
const num = -5;
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar',
      showBackground: true,
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.2)'
      },
      label:{
        show: true,
        color:`${num > 0 ? 'red' : 'blue'}`
      }
    }
  ]
};
```
</details>

**Comment by googirle** [comment]
@jiawulin001  thanks for your suggestion，but I'm afraid I can't get value from series and determine the color with the size of the number

**Comment by jiawulin001** [comment]
My proposal is based on the example you give. If that's not the case, can you give a more concrete or precise example so we can better understand your requirement?

**Comment by googirle** [comment]
@jiawulin001 
For example a histogram, I want the label of  each column to be red when the number of it is greater than 10 and be blue  when less than 5, otherwise gray. Just like the second chart above. 
I think the option should be like 
```js
option = { 
series: [{ 
  label: { 
    color: (value, index) => return value >= 10 ? 'red' : value <= 5 ? 'blue' : 'gray'
  }
}]
```

**Comment by jiawulin001** [comment]
Thank you, I got what you mean. You want the label color changes as the series data changes.

**Comment by googirle** [comment]
@jiawulin001 Yes, my thoughts exactly.
