### ISSUE TITLE
[Feature] 通过data来获取 dataIndex

### ISSUE THREAD

**Issue by zsytssk** [apache/echarts#17238]
### What problem does this feature solve?

工作中遇到一个需求在页面上显示两个echarts图表，使用的是同一个套数据；当一个图表中点击之后，另一个图表中对应的元素需要高亮之类的。我在官网的api找了一圈，发现可以通过`myChart.dispatchAction`来触发事件，但是他需要dataIndex；而我找了一圈，也没有找到通过数据来获取dataIndex的接口，我唯一发现相关的是在监听节点的事件里面来获取对应的dataIndex。

我想这是一个需求比较高的接口，可以大大的提高echarts的交互性。

### What does the proposed API look like?

也许可以添加接口`getDateIndexByData`之类的来获取数据对应的dateIndex。

**Comment by Ovilia** [comment]
> 在页面上显示两个echarts图表，使用的是同一个套数据；当一个图表中点击之后，另一个图表中对应的元素需要高亮之类的。 

这个需求的常见解法是 [`connect`](https://echarts.apache.org/zh/api.html#echarts.connect)，test 下也有[一些例子](https://github.com/apache/echarts/tree/master/test)，可以搜 `connect`。

按你说的 `dispatchAction` 也是可以的，点击事件本身应该是带有 `dataIndex` 的，如果没有的话提供一下例子吧。

**Comment by zsytssk** [comment]
> @zsytssk Please provide a demo for the issue either with [Official Editor](https://echarts.apache.org/examples/editor.html), [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

关了吧，我应该是通过你的回复解决我自己的问题
