### ISSUE TITLE
[Bug] 地图实例demo下载本地运行地图不显示，无报错

### ISSUE THREAD

**Issue by wulibaibao** [apache/echarts#17232]
### Version

5.3.3

### Steps to Reproduce

1. 进入链接[](https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap)
2. 下载实例
3. 本地运行，地图不显示

简单实例运行在React,nextjs都是一样效果，提供代码是有什么缺失吗？

### Current Behavior

运行起来，跑到跟现实一样

### Expected Behavior

运行起来地图可看到

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by wulibaibao** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap
这个实例，地图是没人用吗，好像地图都没效果

**Comment by jiawulin001** [comment]
Open the html file with IDE(like VScode), uncomment these lines:
![image](https://user-images.githubusercontent.com/14244944/174208905-fd1ef481-01e4-45a7-8c21-b8d94357f61f.png)
And substitute the red block with your baidu api key, you can get one [here](https://lbsyun.baidu.com/index.php?title=jspopular3.0/guide/getkey).
