### ISSUE TITLE
[Bug] Can we get the coordinates when we know the datalabel and series data point?

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#17239]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple

### Steps to Reproduce

1. Create any chart. 
2. I want to click on series datalabel or axis data label. 
3. when I clicked on that particular area of the chart. Do, I get the co-ordinates from the chart instance?

### Current Behavior

Need the co-ordinates of the particular area in the chart

### Expected Behavior

Need the co-ordinates of the particular area in the chart

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by ParasolGao** [comment]
Maybe you can try this
```
option = {
  xAxis: {
    type: 'category',

    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      emphasis:{
        label:{
          show:true
        }
      }
    },
  ]
};
```

**Comment by jiawulin001** [comment]
Do you mean you want to get series points' coordinates in DOM, not data?

**Comment by RavalikaP** [comment]
@jiawulin001  x, y position

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/api.html#echartsInstance.convertToPixel See if this helps.
