### ISSUE TITLE
似乎没有使用echarts绘制贝塞尔曲线图表的实例[Bug] 

### ISSUE THREAD

**Issue by Zhaibian1** [apache/echarts#17234]
### Version

5.2.2

### Steps to Reproduce

似乎没有使用echarts绘制贝塞尔曲线图表的实例

### Current Behavior

似乎没有使用echarts绘制贝塞尔曲线图表的实例

### Expected Behavior

似乎没有使用echarts绘制贝塞尔曲线图表的实例

### Environment

```markdown
- OS:win10
- Browser:谷歌
- Framework:viscode
```

### Any additional comments?

似乎没有使用echarts绘制贝塞尔曲线图表的实例

**Comment by Ovilia** [comment]
[如果是指用户给定了控制点，希望绘制贝塞尔曲线的话，](https://github.com/apache/echarts/blob/master/test/graphic-draggable.html#L75-L93)

**Comment by Zhaibian1** [comment]
不是喔，那个只是绘制贝塞尔的图形。echarts不能绘制可以拖动的贝塞尔曲线图表吗

**Comment by Ovilia** [comment]
这是什么意思？
