### ISSUE TITLE
[Bug] 二维地图省份的边界线颜色显示不全？

### ISSUE THREAD

**Issue by SunQQQ** [apache/echarts#17249]
### Version

5.2.2

### Link to Minimal Reproduction

https://blog.csdn.net/writeBUG123/article/details/120747305

### Steps to Reproduce

在series的itemStyle属性里配置的边框颜色
`
           itemStyle: {
              borderColor: 'red',
              borderWidth: 2,
            }
`

### Current Behavior

给地图的各个省份边界设置不同颜色时，边界线展示不全，或者说边框线粗细展示不均匀？
有知道的老师，烦请指导一下
[效果如图](https://blog.csdn.net/writeBUG123/article/details/120747305)

### Expected Behavior

希望省份边框颜色能够均匀展示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?
省份边框显示不全的效果，如下图
<img width="457" alt="46ab2523734bd84cf47fa2ede62a4580_272688" src="https://user-images.githubusercontent.com/24430020/174589072-88b59ee2-312e-48b3-b358-e67f4e908015.png">

_No response_

**Comment by plainheart** [comment]
感觉是两个省份共有的边界线重合了，因为层级问题导致部分边框线被挡住了。

**Comment by SunQQQ** [comment]
> 感觉是两个省份共有的边界线重合了，因为层级问题导致部分边框线被挡住了。

请问老师知道echarts地图是怎么渲染的吗？层级机制是怎样的？
这个问题有没有办法解决

**Comment by plainheart** [comment]
@pissang 看看能不能给些建议？

**Comment by SunQQQ** [comment]
> @pissang 看看能不能给些建议？

麻烦指导下，我们能试的方法都试了。实在是没有思路了

**Comment by pissang** [comment]
@SunQQQ 抱歉没留意到这个问题，这个可能暂时也没太好的办法，可以考虑预处理 geojson 然后把红色边框的放到最后，这样就会显示在最上面而不会被覆盖住。

或者如果是使用 5.3.0+ 版本的话，geojson 支持 LineString，可以再给 geojson加这几个省份边框的 LineString 然后设置成红色

**Comment by SunQQQ** [comment]
> 



> @SunQQQ 抱歉没留意到这个问题，这个可能暂时也没太好的办法，可以考虑预处理 geojson 然后把红色边框的放到最后，这样就会显示在最上面而不会被覆盖住。
> 
> 或者如果是使用 5.3.0+ 版本的话，geojson 支持 LineString，可以再给 geojson加这几个省份边框的 LineString 然后设置成红色

谢谢您的指点，我试试
