### ISSUE TITLE
[Bug] 文档内容inherit单词错误拼写为inehrit

### ISSUE THREAD

**Issue by clown-helang** [apache/echarts#17248]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/zh/option.html#legend.itemStyle.borderWidth

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/20653395/174534311-3a5ffbba-210f-4466-91e3-17cd80d875b3.png)

### Current Behavior

访问文档，发现单词拼写错误

### Expected Behavior

访问文档，发现单词拼写错误

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
感谢反馈，欢迎到 [echarts-doc](https://github.com/apache/echarts-doc) 提 PR 修复一下~

- https://github.com/apache/echarts-doc/blob/master/zh/option/component/legend.md
- https://github.com/apache/echarts-doc/blob/master/en/option/component/legend.md
