### ISSUE TITLE
之前老版本的更新资源列表现在看不了吗，在哪里还可以看到了

### ISSUE THREAD

**Issue by hs151991** [apache/echarts#17255]
### What problem does this feature solve?

想要看到之前的更多资源列表，谢谢

### What does the proposed API look like?

想要看到之前的更多资源列表，谢谢

**Comment by plainheart** [comment]
你指的是 https://github.com/ecomfe/awesome-echarts 吗？

**Comment by plainheart** [comment]
抱歉，Gallery 网站已关闭。参见 #16471
