### ISSUE TITLE
[Feature] 能否加上各个版本的文档及下载渠道？

### ISSUE THREAD

**Issue by zhangqh22** [apache/echarts#17256]
### What problem does this feature solve?

由于历史遗留问题，老项目中有很多以前的echarts版本图表，但对比了下新版本的文档，发现有些不一致，维护起来比较麻烦，所以官方能否提供各个版本的API文档及下载渠道

### What does the proposed API look like?

由于历史遗留问题，老项目中有很多以前的echarts版本图表，但对比了下新版本的文档，发现有些不一致，维护起来比较麻烦，所以官方能否提供各个版本的API文档及下载渠道

**Comment by plainheart** [comment]
之前有在计划为文档加上版本选择器，但因为一些原因短时间内可能还无法实现该功能。大部分配置项一般都有版本支持提示框，一定程度上可以用于区分。

**Comment by zjxpcyc** [comment]
+1. 我们也是有这个需求
