### ISSUE TITLE
[Feature] 征求一个针对多数据出现高低差和数据存在公用部分，可以进行数据截取，使得y轴双段切分

### ISSUE THREAD

**Issue by lizq001** [apache/echarts#17254]
### What problem does this feature solve?

![d28deaf4263b6c46512f4c5e230a9bf](https://user-images.githubusercontent.com/27255500/174704879-8119f37b-0293-4ece-9bab-da7c81af3271.png)
可以对于呀轴进行两个比例切分，体现出，低于多少的数据使用一个比例，截断中间共有部分

### What does the proposed API look like?

可以对于轴进行两个比例切分，体现出，低于多少的数据使用一个比例，截断中间共有部分

**Comment by plainheart** [comment]
Duplicate of #17253
