### ISSUE TITLE
[Question] how to use echart event simulate tooltip axis trigger

### ISSUE THREAD

**Issue by cha0wg** [apache/echarts#17268]
### What problem does this feature solve?

Echarts tooltip trigger can be set with 'axis' then tooltip shows when hover the axis, can I use echarts events to simulate tooltip axis trigger? 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/13954991/175098015-66098427-4fa4-45c2-a13e-9b2027303e93.png">
I want to use JSX to render tooltip and control tooltip, does `echart.getZr().on('mousemove')` or` echart.on('mousemove')` work? I tried and looks don't have idea about how to do a `axis` trigger tooltip

### What does the proposed API look like?

echart.on('mousemove') can works on `axis`

**Comment by susiwen8** [comment]
Could [showTip](https://echarts.apache.org/en/api.html#action.tooltip.showTip) solve this issue?
