### ISSUE TITLE
[Bug] Bar series in yAxis[log] with data between 0 and 1 

### ISSUE THREAD

**Issue by MeetzhDing** [apache/echarts#17260]
### Version

5.3.3

### Steps to Reproduce

```ts
option ={
  xAxis: [{
    show: true,
    type: 'category',
    data: ['', '', ''],
  }],
  yAxis: [{
    // type: 'value',
    type: 'log',
    // min: 'dataMin',
  }],
  series: [{
    type: 'bar',
    data: [10, 100, 0.2]
  }]
}
```

### Current Behavior

bar chart start with yAxis value=1.  and number between 0 and 1 is strange.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/12808432/174778294-1a21e903-e211-4e10-ab0f-8454bea7d079.png">

### Expected Behavior

bar chart should start from bottom?  or datamin ?  

just like type='value'.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12808432/174779295-fd2309f5-9db5-4e98-bb80-5a46eb04db97.png">

### Environment

```markdown
- OS: MacOS
- Browser: Chrome 101
- Framework: any
```

**Comment by Diesmo** [comment]
Very annoying bug.

Tried to circumvent it via increased border size of the element, but it seem the element with value 1 (on log axis) is not even rendered, so increased border size does nothing for it.

Only solution that I found for now is a toggle button to switch between log and linear aka value axis.
