### ISSUE TITLE
曲线分段设置样式

### ISSUE THREAD

**Issue by btea** [apache/echarts#17273]
### Version

5.3.3

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/24516654/175252225-4083126a-8428-4039-8ca8-0e423a613b61.png)

在上图的基础上，我希望将红色部分的线设置成虚线，该如何配置？

### Current Behavior

如图所示

### Expected Behavior

能满足效果

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=line-smooth&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiABwATAAMPLAAnADMqVnZ6QCMWdAK_v5ZxalF1bm5mbDF-enWoR4U1HT-ENDKHaR4ALbAwGDaRGAcSnEOce4JQmAiMeWVZRVVOSWFuQAs1bVN69un7XHoXd60vf28l2Gj45NkM1SD6HdUJhT-3osEp5urIhHhtBoHkD5h4YbBbHYANxAA

**Comment by btea** [comment]
这种写法我尝试过，不过这样的话，连接处看着不连贯，有更连贯的实现方式吗？
![image](https://user-images.githubusercontent.com/24516654/175265623-d31d8d07-a73e-4b82-9bc3-ad10902acb0f.png)

**Comment by btea** [comment]
期望效果: 
![image](https://user-images.githubusercontent.com/24516654/175268548-4c74885e-43b9-4b69-a6ee-935fcb0d978b.png)
