### ISSUE TITLE
[Bug] colorStops里color写法 rgb(254 134 22 / 20%)报错

### ISSUE THREAD

**Issue by oseaweed** [apache/echarts#17274]
### Version

5.3.0

### Steps to Reproduce

color渐变色配置：
```ts
areaStyle: {
  opacity: 0.5,
  color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [
      {
        offset: 0,
        color: 'rgb(254 134 22 / 20%)',
      },
      {
        offset: 1,
        color: '#fff',
      },
    ],
  },
},
```
### Current Behavior

colorStops里color写法 rgb(254 134 22 / 20%)会报错，改成rgba(254 134 22 / 20%)就好了
![image](https://user-images.githubusercontent.com/33144660/175266896-d5c16f05-75a0-476c-b6a1-9a271fceffd5.png)

### Expected Behavior

支持 rgb(254 134 22 / 20%)写法

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by oseaweed** [comment]
> 建议使用以逗号分隔的传统写法，我记得空格分隔的写法应该还没有得到 echarts 的完整支持。

逗号分割也不行 得用rgba的写法 目前只有用这里会报错

**Comment by plainheart** [comment]
带透明度一般还是建议用 rgba 而不是 rgb，尽量使用传统写法，一些浏览器支持的新写法还没有全面兼容。

**Comment by fuchunhui** [comment]
https://github.com/ecomfe/zrender/pull/932

加了正则检测，转换处理。
