### ISSUE TITLE
[Feature] filter dispatched events in event listener

### ISSUE THREAD

**Issue by loadingwyn** [apache/echarts#17284]
### What problem does this feature solve?

When I dispatch an 'datazoom' event manually, my 'datazoom' listener can know it is from code instead of user operations

### What does the proposed API look like?
```ts
myChart.dispatchAction({
    type: 'dataZoom',
    **emitEvent: false,**
    start: 20,
    end: 30
});
```

**Comment by plainheart** [comment]
Currently, you can put an extra parameter as a flag into the action payload and check it in the event handler. For example,

```js
chart.on('datazoom', e => {
  if (e.emitEvent) {
    // do something
  }
})
```

```js
chart.dispatchAction('datazoom', {
  type: 'dataZoom',
  emitEvent: false,
  start: 20,
  end: 30
})
```
