### ISSUE TITLE
[Bug] if "series-pie.label.overflow=break" it breaks "by character" instead of "by word"

### ISSUE THREAD

**Issue by ParachainsDev** [apache/echarts#17283]
### Version

5.3.0+

### Steps to Reproduce

series: [

                {
                    type: 'pie',
                    id: 'pie',
                    radius: '40%',
                    center: ['50%', '50%'],

                    emphasis: {
                        focus: 'self'
                    },
                    label: {
                        formatter: '{b}\n{@current}%',
                        overflow: 'break'                        
                    }
                }
            ]

### Current Behavior

overflow: 'break' for pie series label breaks by character instead of by word  

### Expected Behavior

overflow: 'break' for pie series label should break by word.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Framework: Javascript
```

**Comment by Ovilia** [comment]
Please provide the data to reproduce the problem.
