### ISSUE TITLE
3D Earth uses scatter to create labels, the labels are always occluded by unknown circular objects

### ISSUE THREAD

**Issue by Jkarel** [apache/echarts#17287]
### Version

all

### Steps to Reproduce

  var option = {
        globe: {
            baseTexture: "/finance-admin/upload/material/20220627/1D4D23A96F164610A576F522537E1C31.png",
     
            top: "middle",
            left: "center",
            environment: "none",
       
            shading: 'realistic',
            realisticMaterial: {
                roughness: 0.2,
                metalness: 0
            },
            viewControl: {
                distance: 140,
                autoRotate: true,
                autoRotateDirection:ROTATE_DIRECTION
            },
            displacementScale: 0.04,

        },
        series: [{
            type: "lines3D",
            effect: {
                show: true,
                period: 3, //速度
                trailLength: 0.1, //尾部阴影
            },
            lineStyle: {
                //航线的视图效果
                color: LINE_COLOR,
                width: 1,
                opacity: 0.6,
            },
            data: lineData, // 特效的起始、终点位置，一个二维数组，相当于coords: convertData(item[1])
        }, {
            type: 'scatter3D',
            coordinateSystem: 'globe',
            data: scatterData,
            label: {
                textStyle: {
                    color: LABEL_TEXT_COLOR,
                    backgroundColor: LABEL_BACK_COLOR,
                    fontSize: LABEL_TEXT_SIZE,
                    padding: 8
                },
                show: true,
                formatter: function(paramObject){
                    var ret = [];
                    ret.push(paramObject.data.name + "\n")
                    paramObject.data.datas.forEach(function(d){
                        ret.push( "\n" + d)
                    })
                    return ret.join("");
                },

            },
            itemStyle: {
                normal: {
                    color: POINT_COLOR,
                },
            },
        }],
    };

### Current Behavior

![image](https://user-images.githubusercontent.com/13469579/176129960-c67db0e1-51aa-4c33-be5a-c5a51610bea4.png)

### Expected Behavior

不应该被不明圆形遮挡

### Environment

```markdown
- OS:window10
- Browser:chrome
- Framework: none
```

### Any additional comments?

no

**Comment by wengxuan** [comment]
same bug
