### ISSUE TITLE
[Bug] 使用extendShape自定义组件时获取不到坐标

### ISSUE THREAD

**Issue by 1836661896** [apache/echarts#17299]
### Version

5.3.3

### Steps to Reproduce

创建extendShape 自定义样式
构建echart图表
使用series  custom 自定义
再renderItem中传入shape：{
                      x: api.value(0),
                      y: api.value(1),
                      width: api.value(3),
                      height: api.value(4)
                  },
按照文档上的内容，该传参为坐标的x和y轴及宽高，但是获取到的0和1为data中的值，2和3为NaN

### Current Behavior

根据网上搜索的结果，api中原应有一个方法 为 coord 可以根据值计算x和y的坐标，目前最新版无此方法，希望能重新引入

### Expected Behavior

根据网上搜索的结果，api中原应有一个方法 为 coord 可以根据值计算x和y的坐标，目前最新版无此方法，希望能重新引入

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by WangWuzhen626** [comment]
I also has the same question! 
when I set the data as interface `Hex[]`,it does work useing `api.value(0)`. As I console it ,it shows `NaN`. By the way,hex is a class I  defined.
