### ISSUE TITLE
y轴无法自定义刻度

### ISSUE THREAD

**Issue by zgLiuBing** [apache/echarts#17293]
### Version

5.2.2

### Steps to Reproduce

![Uploading image.png…]()

### Current Behavior

![image](https://user-images.githubusercontent.com/26192378/176416518-b5ad294c-2ae0-4728-8777-d9e3f8692265.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/26192378/176416522-5c06eb3c-90d0-470d-beaf-f3df65da3936.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/26192378/176416536-c7dcae36-f6f9-425c-ace8-ab74eec7e81b.png)

**Comment by 18300618319** [comment]
y轴怎么自定义刻度
