### ISSUE TITLE
需要一个功能实现如下效果

### ISSUE THREAD

**Issue by mcx1230** [apache/echarts#17290]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/40031193/176331555-e1536fb7-0e60-482f-aa52-388bca5f7bb8.png)

需要实现一下效果 可以分为三种方案，难度一次递增

1. 在已经实现内容的基础上，实现label文字的水平翻转（需要官方支持新的属性，不能通过transform实现）；
2. bar可以选择开始的方向；
3. 直接支持这样的两侧布局的样式；

### What does the proposed API look like?

label: {
   show: true,
   // 新添加API
  mirror:  true, // false
}

**Comment by Ovilia** [comment]
两侧布局是可以通过将坐标的设为负值实现的，唯一比较难的是文字翻转，虽然不知道这样可读性很差的设计是出于什么考虑，但如果要实现的话，似乎也是可以通过把左边部分作为一个单独的图表，然后通过 css 实现整个图表的翻转

**Comment by mcx1230** [comment]
上面贴的图不是效果图，就是用echarts实现结果，唯一没有实现的就是左侧label内容的镜像翻转
