### ISSUE TITLE
hostObj is undefined

### ISSUE THREAD

**Issue by cubecleveland** [apache/echarts#17314]
### Version

5.3

### Steps to Reproduce

Any custom chart that uses renderItem

### Current Behavior

host Obj is undefined 
which is coming from here ...

export function makeInner() {
  var key = '__ec_inner_' + innerUniqueIndex++;
  return function (hostObj) {
    return hostObj[key] || (hostObj[key] = {});
  };
} in model.js

### Expected Behavior

Not to see that bug but unmoung gracefully

### Environment

```markdown
- OS: Widnows
- Browser: All
- Framework:React
```

### Any additional comments?

iwe think it comes from rapid mounting unmounting of the dom element togetehr with RenderItem function....

A

**Comment by yousafhanif** [comment]
facing the same issue. 

`export function makeInner() {
  var key = '__ec_inner_' + innerUniqueIndex++;
  return function (hostObj) {
    if (!hostObj)
      hostObj = {};
    return hostObj[key] || (hostObj[key] = {});
  };
}`

That's the fix. pls fix and publish
