### ISSUE TITLE
[Feature] Why is the `use()` extension mechanism not mentioned in the official documentation?

### ISSUE THREAD

**Issue by wang1212** [apache/echarts#17313]
### What problem does this feature solve?

An official plugin/extension mechanism with safer and more flexible extension capabilities.

### What does the proposed API look like?

When viewing the source code, the `use()` API provides a good extension mechanism and is fully used in the source code. 

**Why is it not mentioned in the official documentation?** Or is it that I didn't find it? I have only got very limited information from the documentation for the import on demand section.

**Comment by plainheart** [comment]
It's mentioned at https://echarts.apache.org/api.html#echarts.use. What information are you expecting to get more?

**Comment by wang1212** [comment]
> It's mentioned at [echarts.apache.org/api.html#echarts.use](https://echarts.apache.org/api.html#echarts.use). What information are you expecting to get more?

I'm concerned with **how to extend echarts** instead of using `use()` to implement on-demand import.

**Comment by wang1212** [comment]
> Got it. But I'm afraid you have to read the source to learn about the related usage. We have no available documentation to indicate so many internal APIs yet.

Actually, I'm just trying to figure out why this extension mechanism API is not mentioned in the official documentation.

If it's just because the maintenance team doesn't have time to write documentation, there's nothing to worry about. However, if the APIs seen from the source code are not officially recommended, is there a big risk in using these APIs?

In other words, I see from the source code that the `use()` API is the official way to expose (register) various chart components and is widely used, so can I consider this extension mechanism to be stable at present , **is it safe to use by external users**?

**Comment by plainheart** [comment]
The APIs mounted in the global `echarts` usually are safe to be used by the developers. Please rest assured to use the `use` API.

**Comment by wang1212** [comment]
> The APIs mounted in the global `echarts` usually are safe to be used by the developers. Please rest assured to use the `use` API.

Ok, I see. Thank you very much for your prompt reply.

---

To say some digressions, after a preliminary understanding, it is a good mechanism to use the `use()` API to extend ECharts, but the relevant information on the Internet is very limited (or even no), I hope this mechanism can be known by more people , in order to facilitate users to realize personalized functions in specific scenarios.
