### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jzyismylover** [apache/echarts#17315]
### Version

5.2.2

### Steps to Reproduce

`export const option = {
  toolbox: {
    feature: {
      show: true,
      magicType: {
        type: ['line', 'bar']
      },  //切换为折线图，切换为柱状图
      restore: {},  //还原
      saveAsImage: {}   //保存为图片
    }
  },
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};`

Just use this setting and in .vue file use setOption(option) but throw Error 

### Current Behavior

BarView.js:148 Uncaught TypeError: Cannot read properties of undefined (reading 'getBaseAxis')
    at BarView2._renderNormal (BarView.js:148:26)
    at BarView2.render (BarView.js:112:79)
    at Task2.progress (Chart.js:196:20)
    at Task2._doProgress (task.js:187:10)
    at Task2.perform (task.js:153:16)
    at echarts.js:1694:24
    at GlobalModel2.<anonymous> (Global.js:636:10)
    at Array.forEach (<anonymous>)
    at each (util.js:207:13)
    at GlobalModel2.eachSeries (Global.js:633:5)

### Expected Behavior

change line chart to bar chart using toolbox

### Environment

```markdown
- OS: windows 
- Browser: Chrome 96.0.4664.55
- Framework: Vue@3 + TypeScript
```

**Comment by Jxiang-jc** [comment]
我也遇到一样的问题,请问你解决了吗?

**Comment by byronogis** [comment]
Hi there, I got same problem too, it happend when first loaded and resize after. And Finally solved it with markRaw (vue api).

`markRaw(echarts.init(el))`
