### ISSUE TITLE
[Feature] Set different bar gaps on same category

### ISSUE THREAD

**Issue by yossibbc** [apache/echarts#17323]
### What problem does this feature solve?

Need an option to set different gaps for each bar
![Screen Shot 2022-07-05 at 12 41 14](https://user-images.githubusercontent.com/12198233/177300133-52472a19-f5e9-4bba-bd3c-817997103fa7.png)
as you can see each 2 bars are close each other with zero padding  

### What does the proposed API look like?

set property for single bar "isSingleBar" then the "barGap" will come relevant only for him

**Comment by jiawulin001** [comment]
Sorry I cannot find the exact problem if there is no demo. My best guess to solve this is to try adjusting [`series.barGap`](https://echarts.apache.org/zh/option.html#series-bar.barGap).
