### ISSUE TITLE
[Bug] Server Side Rendering - Legend spacing does not increase when legend font size does

### ISSUE THREAD

**Issue by ArturCapraro** [apache/echarts#17326]
### Version

5.3.3

### Steps to Reproduce

Increase the legend font size and try to create an svg with server side rendering.

### Current Behavior

When we get the server side rendered image with the default font size, the image show fine:
```js
"legend": {
    "type": "plain",
    "orient": "horizontal",
    "left": 60,
    "bottom": 10,
    "icon": "roundRect",
    "selectedMode": false,
    "itemGap": 20,
    "data": [
        "this is element 1",
        "this is element 2",
        "this is element 3",
        "other elements",
        "other elements",
        "other elements"
    ]
},
```
![demo_regular](https://user-images.githubusercontent.com/54982545/177535589-cb266ca9-6701-4354-b7d4-c784b4211a2d.svg)

But, if we increase the fontsize, the gaps between legent items does not increase, causing elements everlap:
```js
"legend": {
    "type": "plain",
    "orient": "horizontal",
    "left": 60,
    "bottom": 10,
    "icon": "roundRect",
    "selectedMode": false,
    "itemGap": 20,
    "textStyle": { "fontSize": 15 },
    "data": [
        "this is element 1",
        "this is element 2",
        "this is element 3",
        "other elements",
        "other elements",
        "other elements"
    ]
},
```

The only difference here from the beginning is ` "textStyle": { "fontSize": 15 },`.
![demo_increasing_fontsize](https://user-images.githubusercontent.com/54982545/177536527-220e1795-084a-42ad-bc67-ab7660594c57.svg)

### Expected Behavior

Expect a correct spacing between elements in legend when fontsize increase avoiding overlap.

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Browser: Chrome
- Node.js: v18.1.0
```

### Any additional comments?

This only occurs with server side generating. In the front-end with javascript and the same options the charts are generating correctly even with font-size increase.

**Comment by davidjr82** [comment]
I can confirm this issue is happening. 

The font-size is not taken into account when generating SSR svg files following the instructions in docs.

https://echarts.apache.org/handbook/en/how-to/cross-platform/server
