### ISSUE TITLE
[Bug] Custom series graphic elements rendering bug after updating

### ISSUE THREAD

**Issue by zangzimi** [apache/echarts#17333]
### Version

5.3.3

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&version=5.3.4-dev.20220707&code=G4QwTgBAxgpgNnAygSwF4wgXggbQKwAMANBHgIwC6A3AFA0D2ADgC7L0B2WEA3jRNCDgx2AE3AAuXH349pMiPTDJhzSQHJgMMKyiC1ROTNgIU6ScaRoYB-fwCeMcABkQAI3iTetmQGcAFvQA7pIAZoI-MIb8AL42tgC2HMx-Lu5wnlG-AcEQYXARmbGZYCDsAOYwkjhqAEwENTUAtGRqFIbR0hRxEUowPlWGXrbMdoyVEGpQAK4-zPTx-pnsIPHjaiCL3lD0iiLIy8wwiHazMPHqukKi4Ju2YswgA9781XUNjQRkzQBs-hMbJDyETa3i6xWEIi0AElDucIAAKRjgFY-EggRjIACUWAAfLJntAOLMIPcMNh0cgAHSgOBTGDwgiY2gE7bsYkWAAK9H2zC4FMp2128NJTMy_FZxIAHlyfFxOdz2MwcAQKBBGtB4JZ0MrVQB6CA1ZnPCW8uwyuWark8nCUNUakxWG16g1GrZE3nLVZ8jHUwR0-FkUUs932uAAdWQImSXCRJXiPgFOzAImOCYsEajfldthNEEY9B8yFYHC4OGlBZIZoL1DFhLZvLAMCgvOwQwJIzG6kbzduBP86PGbYJEElkmItfkdjHcWHEECkeS5k1GeSM-HfhgyDKflUEDIeAnECKs_zheL7DX3lmdiEGVn_BCyAQ6gAxDB32pD8fh4dJcwAMJJCod73tet74ve_C_runrWIe8iPs-EwvgAHGhvb3vQmhgCEcBBOozBgFM7C6IcGGzvOmZLggK5-Je66btuu5kAAzPRBJTnu8FHl-7EyNBgHsI-ZQgSeBZFmw7DqPshaQk4MAhMw5HPHssylLAkg1F-tbRLQta5q4uxaPJinelSNL-jUmKHgA_BA7BTAgh6ifeHZrN2Sl8VefgDi5kGjhA46QZO07cfIlGLgaXnPBuW47pI-5hUe0XyKeEkcClvgjOBQ6QYh6QTI2IifsFPGQbpdDBvWEBlGA9BTIwXC5cMoxrLV9WMMp8hQH4T4iI2Um4B5JCGcmxkKcwILPBVBKNswUxgJw7UNdmMT0YWVy7oRdL0agmn0UIFSiAAElhxn7AA1pI21wVscDIIwoThLdthwG4Hg8N-8hnIwPmFv0PAQG9aSeNEZUyB0_BtBVNARMwAAqyCrPVzDwiExHNpJCLYkM8R2P-PnaJScMAPIsJJ8JDpcEISBB8glOU4yvPUTT1K07Rrj0ygAzgmTNVBrUXDMcwLHxsHqACtb3I8Uizsz7z1M0LF_Gorh_DdU2goUhhTdEoqxHuBBG0yQA)

### Steps to Reproduce

```js
var cellSize = [50, 51];

option = {
  calendar: [
    {
      orient: 'vertical',
      cellSize: cellSize,
      yearLabel: {
        show: false
      },
      monthLabel: {
        show: false
      },
      range: ['2022-1']
    }
  ],
  series: [
    {
      type: 'custom',
      name: 'a',
      coordinateSystem: 'calendar',
      data: [
        ['2022-01-16', 'a', false]
      ],
      renderItem: (params, api) => {
        const date = api.value(0);
        const cellPoint = api.coord(date);
        const xPos = cellPoint[0] - cellSize[0] / 2;
        const yPos = cellPoint[1] - cellSize[1] / 2;
        const name = api.value(1);
        const cellWidth = params.coordSys.cellWidth;
        const position = [xPos, yPos];
        const rect = {
          type: 'rect',
          shape: {
            x: 0,
            y: 0,
            width: cellWidth,
            height: 15
          },
          position,
          style: {
            fill: '#eee'
          },
          textContent: {
            style: {
              text: name,
              fill: '#888',
              overflow: 'truncate',
              width: cellWidth,
              height: 13,
              y: 1
            }
          },
          textConfig: {
            position: 'insideLeft',
            distance: 2
          }
        };

        const borderLeft = api.value(2)
          ? null
          : {
              type: 'rect',
              shape: {
                x: 0,
                y: 0,
                width: 2,
                height: 15
              },
              position,
              style: {
                fill: 'red'
              }
            };

        const group = {
          type: 'group',
          children: [rect, borderLeft]
        };
        return group;
      },
      silent: true,
      z: 2,
      legendHoverLink: true,
      clip: false,
      label: {},
      emphasis: { label: {} }
    }
  ]
};

setTimeout(function () {
  myChart.setOption({
    calendar: {
      range: ['2022-02']
    },
    series: [
      {
        type: 'custom',
        name: 'a',
        data: [
          ['2022-02-13', 'b', true]
        ]
      }
    ]
  });
}, 1000);
```

(Detailed steps are shown in the above demo) This problem occurs only after the second `setOption`. 

### Current Behavior

Note that after one second, there is an extra red bar at the third Sunday (the block under `e`). This is the error left behind the previous `setOption` and it won't exist if it does not exist in the previous `setOption`.
![image](https://user-images.githubusercontent.com/84388381/177913259-fbee8882-954f-4e23-9174-9840826f777b.png)

### Expected Behavior

There should not be a red bar at the green position above.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I'm not sure if this relates with #17185 which should have been fixed in #17308. I tested with 5.3.4-dev.20220707 and this problem still exists.

**Comment by Ovilia** [comment]
Minified the demo to be: [link](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&version=5.3.4-dev.20220707&code=G4QwTgBAxgpgNnAygSwF4wgXggbQKwAMANBHgIwC6A3AFA0D2ADgC7L0B2WEA3jRNCDgx2AE3AAuXH349pMiPTDJhzSQHJgMMKyiC1ROTNgIU6ScaRoYB-fwCeMcABkQAI3iTetmQGcAFvQA7pIAZoI-MIb8AL42tgC2HMx-Lu5wnlG-AcEQYXARmbGZYCDsAOYwkjhqAEwENTUAtGRqFIbR0hRxEUowPlWGXrbMdoyVEGpQAK4-zPTx-pnsIPHjaiCL3lD0iiLIy8wwiHazMPHqukKi4Ju2YswgA9781XUNjQRkH3j6ExskeQiXUyL1q9Sanw-AHZfmpXL9ATBgc9cGD3pCCDCSJMEeEkXFvK9wR8vgQABywkS4_L4kGot4Qr5kABssJg1KBmWRtjAwhEWgAkodzhAABSMcArHwkECMZAASiwAD5ZCjtuxZhB7hhsLLkAA6UBwKYwUUEeW0NUcTUWAAK9H2zC4ev1212ou1Frp6s1AA97T4uHaHexmDgCBQII1oPBLOhw5GAPQQGqW54-p12ANB2P2x04ShRmMmKwFpMptNba1O5arZ1yw2CE2isheq0ap0WADqyBEyS4EpK8R8rp2YBExxH3d7yUrtgzEEY9B8yFYHC4OH9y5IWeX1G91YgvKgTuwQxRIzG6mPzFuKP8svG55REF9kmIdPkdnfBJfgRnfjmLGPZ9n4v4on4MDIGUfiqBAZB4J-EBFC-i7LqubDsOBtizHYQgZKh_AhMgCDqAAxDAlFqEhKEvocvrMAAwkkKgEYRuH4aqhH8PRcG1tYSHyMRpETGRZLiXehH0JoYAhHAQTqMwYBTOwuiHJJqH_qBQEICByTYRBUEwXBZAAMwGc837wYJyE0RZPEwAxzHsMRZRsahS4rmu7DqPsK78k4MAhLe9kyHssylLAkg1DRdLRLQB4dhAri7FogXBfWBpGs2NTykhAD8EDsFMCBIe5hGXmsN4aS-D5Xlx3H8G-EAfo1MhWa1bUQFpyTRaF3iQdBsGSAhNkxP1MieRhHATfwHFPmNMjCekEy8lSi0dNx8V0O2mplGA9BTIwXDPt4lXqPth2MDV8hQH4JEiLyPm4DeJApeOaVBcwbQottKK8swUxgJwl1HXO42ZCuVxwUpJrYagfWZEIFSiAAEtJaX7AA1pIsMCVscDIIwoR4thcBuB4PC0fIZyMH4IArv0PAQOTaSeNEtnyJtEBtNtNARMwAAqyCrIdzCiiEKknphYqKkM8R2Ix9PaPqAsAPIsJhorPpcfISA1MglOU4xEuiNStO0v49MoTM4Jkp0yOdEzTLM8w3UVKxrP8dL3I8UioabEIQqy2L_LkeLciigcfBCWITPCAIR6F0f1B8ACcsJQBytIB2iQfNOb2JUonNKR88KdNGZbK_HjP3PHXXOGHX0RerE8EEB3FpAA)
