### ISSUE TITLE
[Bug] rardar 雷达图 tooltip的formatter和rich配合使用不生效

### ISSUE THREAD

**Issue by IsabellaChen7** [apache/echarts#17332]
### Version

5.3.2

### Steps to Reproduce

1. 自定义tooltip里的formatter内容
2. 自定义富文本样式名
3. 
![image](https://user-images.githubusercontent.com/26188567/177903148-fead606c-d1ae-4eab-acc5-672ae5c3424c.png)
实现代码：
粘贴到https://echarts.apache.org/examples/zh/editor.html?c=radar中即可复现
`option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {
      trigger: "item",
          formatter: (params) => {
            return "{a|123}}";
          },
          rich: {
            a: {
              color: "pink",
            },
          },
    },
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           },
           formatter:'{a|{value}}',
           rich:{
               a:{
                   align:'center'
               }
           }
        },
        indicator: [
           { name: '销售\n（sales）', max: 6500},
           { name: '管理\n（Administration）', max: 16000},
           { name: '信息\n技术（Information Techology）', max: 30000},
           { name: '客服\n（Customer Support）', max: 38000},
           { name: '研发\n（Development）', max: 52000},
           { name: '市场\n（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            }
        ]
    }]
};`

### Current Behavior

![image](https://user-images.githubusercontent.com/26188567/177903112-ad2f9d37-c471-4917-93f0-a56d138088df.png)

### Expected Behavior

期望结果：tooltip的123是粉色

### Environment

```markdown
- OS:win10
- Browser:chrome
- Framework:
```

**Comment by plainheart** [comment]
tooltip 不支持 rich，使用 css 控制即可。

**Comment by IsabellaChen7** [comment]
> tooltip 不支持 rich，使用 css 控制即可。

多谢 已解决
