### ISSUE TITLE
[Feature] 可以直接给图例的图形添加圆角。We need the feature that can set the borderRadius of the legend's icon.

### ISSUE THREAD

**Issue by EquinoxFlowerJG** [apache/echarts#17330]
### What problem does this feature solve?

可以直接给图例的图形设置圆角大小。We need the feature that can set the borderRadius value of the legend's icon.

### What does the proposed API look like?

legend --> itemStyle -->[add]borderRadius

or

legend --> icon --> [add]borderRadius

**Comment by EquinoxFlowerJG** [comment]
您好，来信已收到，我会尽快给您回复的。

**Comment by plainheart** [comment]
You can set the legend icon to be `roundRect`.

**Comment by EquinoxFlowerJG** [comment]
我可能没表述清楚，我是说，我希望可以设置圆角的大小。I may not have made it clear. I mean, I want to be able to set the value of the legend icon's border radius.

> You can set the legend icon to be `roundRect`. If you hope to make the image rounded, it's not supported yet.
