### ISSUE TITLE
[Bug] textRotation not work

### ISSUE THREAD

**Issue by li942475402** [apache/echarts#17339]
### Version

5.3.2

### Link to Minimal Reproduction

any example like https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple, copy the configuration items below

### Steps to Reproduce

```javascript
option = {
  graphic: [
    {
      type: 'rect',
      id: 'A',
      x: 100,
      y: 100,
      shape: {
        width: 200,
        height: 200
      },
      style: {
        text: 'A',
        fontSize: 60,
      },
      originX: 50,
      originY: 50,
      rotation: 0,
      updateAnimation: {
        duration: 1000
      },
      transition: 'all'
    }
  ],
  animationDuration: 1000,
  animationDurationUpdate: 1000
};

setTimeout(function () {
  myChart.setOption({
    graphic: [
      {
        id: 'A',
        rotation: Math.PI / 6,
        originX: 50,
        originY: 50,
        style: {
          textRotation: Math.PI / 6
        }
      }
    ]
  });
}, 2000);

```

### Current Behavior

textRotation not wrok

### Expected Behavior

Text rotates with graphics

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Why the animation of the text doesn't follow the graphics, including scaling and rotation @O

**Comment by plainheart** [comment]
Use [`textConfig.rotation`](https://echarts.apache.org/option.html#graphic.elements-rect.textConfig.rotation) instead of `style.textRotation`. See the [Apache ECharts 5 Upgrade Guide](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/#deprecated-apis) for more details.

**Comment by li942475402** [comment]
> Use [`textConfig.rotation`](https://echarts.apache.org/option.html#graphic.elements-rect.textConfig.rotation) instead of `style.textRotation`. See the [Apache ECharts 5 Upgrade Guide](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/#deprecated-apis) for more details.

**Comment by li942475402** [comment]
Why doesn't text follow graphics changes by default, just like children and groups
