### ISSUE TITLE
[Feature] visualMap是否可以提供selectData接口

### ISSUE THREAD

**Issue by N1body** [apache/echarts#17331]
### What problem does this feature solve?

工作中遇到一个需求在页面上显示两个热力图：首先要满足当一个图表中点击之后，另一个图表中对应的元素需要高亮，其次是满足两个热力图相对应的visualMap也能根据选中的元素更新选中状态。

已经尝试过使用connect以及监听hover通过dispactch改变高亮状态，但这两个方法结合使用只能改变热力图中方块的状态，而无法更改visualMap的状态

查阅相关文档后发现visualMap只提供[selectDataRange](https://echarts.apache.org/zh/api.html#action.visualMap.selectDataRange)相关的action接口，这个只能改变范围，无法更改选中状态。

查阅源码后发现visualMap是通过监听mousehover事件来更新选中状态的，所以我无法通过更改第二个表的highLight高亮状态使其更新状态

我想这是一个需求比较高的接口，可以大大的提高echarts的交互性。

### What does the proposed API look like?

1. 也许可以给visualMap添加类似`selectData`之类的action接口：可以通过mousehover选中的数据来更新visualMap选中状态
2. 或者给visualMap添加一个option或者判断规则：可以通过监听高亮状态的热力图块来更新状态
3. 或者在connect方法中添加visualMap的联动效果

**Comment by brutuscat** [comment]
If this is about added selection to visualmap, then 👍
