### ISSUE TITLE
[Bug] 甘特图报错

### ISSUE THREAD

**Issue by yyUnique** [apache/echarts#17335]
### Version

5.2.1

### Steps to Reproduce

type:custom

### Current Behavior

仅展示渲染

### Expected Behavior

希望解决

### Environment

```markdown
- OS:windows
- Browser:Chrome103.0.5060.114
- Framework:vue@2
```

### Any additional comments?

![企业微信截图_16572681097482](https://user-images.githubusercontent.com/47802690/177950416-aac2a549-0bd2-442c-b7cc-4af9776ace9f.png)

**Comment by yyUnique** [comment]
该怎么运用到项目中呢

**Comment by plainheart** [comment]
还没发正式版本，暂时无法直接运用，nightly 版本不建议用在生产环境中。

**Comment by JinJianQi** [comment]
请问这个大约什么时候发布呢

**Comment by plainheart** [comment]
@JinJianQi 大概还需要一个月左右 :)

**Comment by JinJianQi** [comment]
那项目里强依赖这个问题怎么办呢，有发布的nightly版本吗？

**Comment by plainheart** [comment]
@JinJianQi nightly 版本每天都有自动构建发布。npm 包在这：https://www.npmjs.com/package/echarts-nightly

**Comment by JinJianQi** [comment]
ok ~，感谢
可以使用
```
"echarts-nightly": "5.3.4-dev.20220804",
```
