### ISSUE TITLE
[Bug] leaveTo not work

### ISSUE THREAD

**Issue by kitee0325** [apache/echarts#17338]
### Version

5.3.2

### Link to Minimal Reproduction

any example like https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple, copy the configuration items below

### Steps to Reproduce

```javascript
option = {
  graphic: [
    {
      type: 'rect',
      x: 100,
      y: 100,
      shape: {
        width: 200,
        height: 200
      },
      leaveTo: {
        shape: {
          width: 0,
          height: 0
        },
        style: {
          x: 200
        }
      },
      leaveAnimation:{
        duration:3000,
      },
    }
  ]
};

setTimeout(function () {
  myChart.setOption({ graphic: [] }, { notMerge: true });
}, 2000);
```

### Current Behavior

disappear immediately

### Expected Behavior

radually shrinking and disappearing

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Is there something wrong with my usage? @Ovilia

**Comment by li942475402** [comment]
I noticed that the official test cases are not working properly
last case in this file
`https://github.com/apache/echarts/blob/master/test/custom-transition.html`

**Comment by jiawulin001** [comment]
Hi, since I didn't find examples about the `leaveTo` animation so my best guess is that `notMerge` option cut the animation off. But I did find a workaround for you, which is use another graphic to "replace" it in `$action`. Check the following code for reference.
<details>
<summary>Code Sample</summary>

```
option = {
  graphic: [
    {
      type: 'rect',
      x: 100,
      y: 100,
      shape: {
        width: 200,
        height: 200
      },
      enterFrom: {
        // 淡入
        style: { opacity: 0 },
        // 从左飞入
        x: 0
      },
      leaveTo: {
        style: {
          opacity: 0
        },
        x: 200
      },
      leaveAnimation: {
        duration: 1000
      }
    }
  ]
};

setTimeout(function() {
  myChart.setOption({
    graphic: [
    {
      type: 'circle',
      x: 100,
      y: 100,
      shape: {
        r: 0
      },
      $action:'replace',
    }
  ]
  });
}, 2000);
```
</details>
