### ISSUE TITLE
[Bug] that cannot be rendered normally when makearea data is the scale field between two screen coordinates

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#17344]
### Version

5.3.3

### Link to Minimal Reproduction

https://codepen.io/zxyt/pen/QWmEjVo?editors=0010

### Steps to Reproduce

设置markArea的data为
[
           {
              name: '两个屏幕坐标之间的标域',
              x: 100,
              y: 100
            },
            {
              x: '90%',
              y: '10%'
            }
]

### Current Behavior

无法渲染出markArea

### Expected Behavior

正确渲染markArea

### Environment

```markdown
- OS: windows 11
- Browser: edge 103.0.1264.49 (正式版本) (64 位)
- Framework: vanillajs
```

**Comment by jiawulin001** [comment]
This can be fixed by this PR: #17217

**Comment by ZXYT** [comment]
好的谢谢大佬

**Comment by huochangying** [comment]
对这个需求比较急，修复能否尽快合并发布，辛苦

**Comment by ZXYT** [comment]
有一个临时解决方案，把 coord设置成空数组
