### ISSUE TITLE
[Bug] The bar chart shows abnormal results

### ISSUE THREAD

**Issue by cooper1x** [apache/echarts#17347]
### Version

4.2.1

### Steps to Reproduce

1.view this example.
https://www.makeapie.cn/echarts_content/xSJJXiE1Wx.html

2.Notice how many pixels are missing here
<img width="970" alt="image" src="https://user-images.githubusercontent.com/9080789/178229532-5ef2e1b0-506e-4c8f-a078-aecc7bd62f51.png">

### Current Behavior

Stacking area lines are not neat.

### Expected Behavior

Stacking area lines are neat.

### Environment

```markdown
- OS:macOS Monterey
- Browser:Chrome Dev 105.0.5148.2
- Framework:Vue@2
```

**Comment by Ovilia** [comment]
Sorry. I don't understand what is wrong here.

**Comment by cooper1x** [comment]
@Ovilia 大佬好~就是箭头指示的位置，仔细看，会发现堆叠柱体的衔接处很不自然，大概差1到2个像素，看起来像是歪了一样。
简单说就是，上面的绿色柱子，比下面的橙色柱子要往右偏一点点，从视觉上看是这样的。
相比较而言，G2plot的堆叠图就没有这个问题。
https://g2plot.antv.vision/zh/examples/column/stacked#basic
![image](https://user-images.githubusercontent.com/9080789/178484349-e0d69905-fd7a-4cf1-a63e-fdd72fdfd32b.png)

**Comment by cooper1x** [comment]
![image](https://user-images.githubusercontent.com/9080789/178486668-5f851b9d-1b46-4c5d-a037-daa017b715bc.png)
似乎是色彩视觉上的错觉，我以为是bug……
