### ISSUE TITLE
[Feature] I hope that when the relationship diagram is a force guide diagram, there will be guide animations only during the initial rendering

### ISSUE THREAD

**Issue by Josiahhx** [apache/echarts#17351]
### What problem does this feature solve?

If force guidance is always present, when I drag and drop nodes, it is visually very messy, especially if there are many children of a node, because if there are many nodes, then force.repulsion will be set to large, and this time the drag will keep touching other nodes, causing all nodes to rotate at a very fast speed

### What does the proposed API look like?

In the configuration item, provide a parameter for whether force guidance is required on an ongoing basis

**Comment by Ovilia** [comment]
The animation cannot be skipped if you are using the force layout. This is because the *animation* is actually the process of calculating the position of each point. You can use `layout: 'none'` and provide the position by yourself if you wish.
