### ISSUE TITLE
[Bug] Chart background color opacity is not respected in SaveAsImage functionality when renderer is of type canvas

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#17355]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/Harshitha19/pen/oNqLqKe

### Steps to Reproduce

1. Open the sample, and click on the download icon present in the toolbox of the chart.
![image](https://user-images.githubusercontent.com/97500674/178260694-552ca665-53a2-479d-b189-83ce3d9bdc19.png)
2. Open the downloaded image and observe that the background color of the chart is black.
![image](https://user-images.githubusercontent.com/97500674/178261182-f1cf9bef-f48f-444f-a83e-8423960dc8c8.png)

Observation:
Opacity is not respected in the saveAsImage functionality when the renderer is of type canvas.

### Current Behavior

Opacity is not respected in the saveAsImage functionality when the renderer is of type canvas

### Expected Behavior

Background color along with opacity is expected to be respected in the captured screenshot.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
It seems your photo viewer has a black background, please try to use a viewer with a white background.
