### ISSUE TITLE
[Feature] Simple 4-Quadrant XY Scatter Plot

### ISSUE THREAD

**Issue by efj5n8** [apache/echarts#17354]
### What problem does this feature solve?

I need a simple 4-quadrant XY scatter plot to overlay an image on. I need to graph outputs onto a target. There is no simple way that I can see to create this simple graph. 

### What does the proposed API look like?

Should be allowed as a setting option to snap the x and y axis to create the typical 4 quadrant scatter meeting at the origin

**Comment by plainheart** [comment]
Have you tried [this example](https://echarts.apache.org/examples/zh/editor.html?c=line-function)?
