### ISSUE TITLE
[Bug] echarts xAxis.axisLabel 配置, 缺少官方文档描述的 overflow 属性.

### ISSUE THREAD

**Issue by halo951** [apache/echarts#17363]
### Version

e.g. 5.3.3

### Steps to Reproduce

1. axiosLabel 配置项文档描述中, 包含 `overflow` 配置项, 但是在最新的 e.g. 5.3.3 版本中, 声明文件缺少 `overflow` 配置项. 
2. 测试发现, 可能功能被移除. 希望官方大大确认.

doc link: https://echarts.apache.org/zh/option.html#xAxis.axisLabel.overflow
interface:
```
interface AxisLabelBaseOption extends Omit<TextCommonOption, 'color'> {
    show?: boolean;
    inside?: boolean;
    rotate?: number;
    showMinLabel?: boolean;
    showMaxLabel?: boolean;
    margin?: number;
    rich?: Dictionary<TextCommonOption>;
    /**
     * If hide overlapping labels.
     */
    hideOverlap?: boolean;
    color?: ColorString | ((value?: string | number, index?: number) => ColorString);
}
```

### Current Behavior

因为缺少 overflow, 导致x轴 axisLabel 无法配置自动裁剪超长字符串.

### Expected Behavior

1. 如果这个功能被移除, 请更新文档.
2. 如果这个功能是保留的, 请检查是否需要修复这个问题.

### Environment

```markdown
- OS: Window 10
- Browser: Chrome/103.0.0.0
- Framework: Vue@2.x
```

**Comment by jiawulin001** [comment]
Hi, as is tested, `xAxis.axisLabel.overflow` is functioning well. Please post your code where you think `overflow` is not working.

**Comment by TendernessCJS** [comment]
> 

`xAxis.axisLabel.overflow` is functioning well but

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/50892641/194973095-6cbde8d0-04d9-4e45-96af-b756eaa4c619.png">

**Comment by breizh24** [comment]
I can confirm that this is a bug with the interface assigned to `xAxis.axisLabel` and I have opened a PR that is going to fix the bug
https://github.com/apache/echarts/pull/17808
