### ISSUE TITLE
[Feature] The "Chart.getDataURL()" method does not contain a background image

### ISSUE THREAD

**Issue by tulupi** [apache/echarts#17360]
### What problem does this feature solve?

I expect to get the base64 address of the trend chart with background pictures, but the base64 I get through getDataURL does not contain background pictures

### What does the proposed API look like?

I expect to get the base64 address of the trend chart with background pictures, but the base64 I get through getDataURL does not contain background pictures

**Comment by plainheart** [comment]
If you are expecting to get the background of the container of your chart, it's impossible. You need to set the background of the chart via the [`backgroundColor`](https://echarts.apache.org/option.html#backgroundColor) option.
