### ISSUE TITLE
When back or zoom is not used

### ISSUE THREAD

**Issue by 4bbada** [apache/echarts#17375]
### What problem does this feature solve?

I want to use only one dataZoom(back or zoom).

how to use that?

When operated with show's boolean, both icons appear or both disappear.

I want to use only one of dataZoom's zoom and back.

### What does the proposed API look like?

`toolbox:{

    feature: {
        dataZoom: {
              title: {
              zoom: "" //i don't wanna use that(zoom) 
              back: "Zoom Out" //i wanna use back.
              },
      },
    }

}`

**Comment by Ovilia** [comment]
You can use [custom toolbar](https://echarts.apache.org/zh/option.html#toolbox.feature) to make a custom button and handle the click event by calling `setOption` and update the zoom.
