### ISSUE TITLE
[Feature] In the document, we are recommended to manage the data, but examples are always set data in the each serise.

### ISSUE THREAD

**Issue by HHN0609** [apache/echarts#17372]
### What problem does this feature solve?

I think manage data with dataset is a correct direction, and we are recommended to use dataset. However, the example using dataset is too barren. I hope the offical can add more examples about dataset. Thanks!

### What does the proposed API look like?

More examples about how to use dataset in different kind of charts.

**Comment by anymos** [comment]
I second this, also when to use more than one dataset ? it might even solve the bug I just posted : https://github.com/apache/echarts/issues/17479

**Comment by anymos** [comment]
For instance:

https://echarts.apache.org/en/option.html#dataset.id, i sounds like it could not be used in the series to reference the dataset as only the https://echarts.apache.org/en/option.html#series-line.datasetIndex can be used to reference a dataset apparently.

**Comment by anymos** [comment]
hi there any news on this part ?
