### ISSUE TITLE
[Bug] stack 中传入 custom group，stack 失效

### ISSUE THREAD

**Issue by i7eo** [apache/echarts#17378]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/3d-stack-custom-bars-htt9md?file=/src/components/HelloWorld.vue

### Steps to Reproduce

详情请打开复现链接查看

### Current Behavior

1. 查看官网示例后编写自定义图形，因为是上下排列所以使用了stack，官网示例中的stack会自动排列对应的图形。在我的示例中，我尝试了 `z` `zLevel` `z2` 均无效，最后尝试使用 `stackStrategy: all` 还是无效。现在想知道的是对于 group custom 的情况，stack 能否控制顺序？如果不行用户怎么处理？
3. 鼠标移入后整个 group 高亮，如果只想高亮某一部分这个应该怎么处理呢？

### Expected Behavior

1. stack 可以自动控制 custom 的顺序
2. 可以部分高亮

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 102.0.5005.115
- Framework: Vue@3.2.21
```

### Any additional comments?

之前使用 echarts 都是比较简单的使用，这次如示例中的 custom 比较复杂，感觉有点懵😹

**Comment by Ovilia** [comment]
如果是自定义系列，需要由 `renderItem` 控制绘制什么、绘制的前后关系（`z2`），不能使用 `stackStrategy` 因为这是折线图、柱状图的属性。你这里指的”绘制顺序“指的是堆叠的上下关系还是绘制的先后顺序？后者的话是通过 `renderItem` 返回的图形的 `z2` 决定的，不过需要注意的是， 如果是多个自定义系列，会优先判断系列的 `z` 来决定绘制顺序，只有系列的 `z` 相同的情况下，才由图形的 `z2` 决定。例子太复杂了没细看，如果需要的话，请提供最小可复现代码。

**Comment by i7eo** [comment]
> 如果是自定义系列，需要由 `renderItem` 控制绘制什么、绘制的前后关系（`z2`），不能使用 `stackStrategy` 因为这是折线图、柱状图的属性。你这里指的”绘制顺序“指的是堆叠的上下关系还是绘制的先后顺序？后者的话是通过 `renderItem` 返回的图形的 `z2` 决定的，不过需要注意的是， 如果是多个自定义系列，会优先判断系列的 `z` 来决定绘制顺序，只有系列的 `z` 相同的情况下，才由图形的 `z2` 决定。例子太复杂了没细看，如果需要的话，请提供最小可复现代码。

好的了解了，想控制堆叠的上下关系。例子中的现象是启用了stack但是并没有上下显示而是“叠”在了一起

**Comment by Ovilia** [comment]
堆叠关系本质上就是渲染位置的关系，所以也就是有个由 `renderItem` 决定的。严格来说，`renderItem` 只应考虑一个数据点并计算得到位置，但 hack 一点的话，还是能够通过读取外部的变量得到所有数据，这样就能知道当前数据堆叠在哪个上面了。

**Comment by i7eo** [comment]
> 堆叠关系本质上就是渲染位置的关系，所以是应该由 `renderItem` 决定的。严格来说，`renderItem` 只应考虑一个数据点并计算得到位置，但 hack 一点的话，还是能够通过读取外部的变量得到所有数据，这样就能知道当前数据堆叠在哪个上面了。

“堆叠关系本质上就是渲染位置的关系，所以是应该由 `renderItem` 决定的” 也就是说如果用户使用 custom 自定义图形的话，堆叠的关系是自行在 `renderItem` 中实现的。这样理解是没问题的吧？
