### ISSUE TITLE
[Bug] Type error in series line option, the scale option in emphasis

### ISSUE THREAD

**Issue by VamoBao** [apache/echarts#17384]
### Version

5.3.2

### Steps to Reproduce

create chart with `echarts.init()`,and `setOption` to set the option,here is the part of my option,and I assign a `number` for scale, the typescript report an error which is type 'number' is not assignable to type 'boolean',but the doc show `number` has been supported since v5.3.2
```typescript
const option:EChartsOption = {
    series: [
      {
        name: mainTitle,
        type: 'line',
        yAxisIndex: 0,
        data: mainData,
       emphasis:{
          scale:1.5
        },
        areaStyle: {
          color: {
            x: 0,
            y: 0,
            x2: 0,
            y2: 1,
            colorStops: [{
              offset: 0, color: 'rgba(0, 100, 255, .2)',
            }, {
              offset: 1, color: 'rgba(255, 255, 255, .2)',
            }],
          },
        },
      },
    ],
  };
```

### Current Behavior

assign a `number` for scale, report an error

### Expected Behavior

correct type detection

### Environment

```markdown
- OS:win10
- Browser: Chrome 103.0.5060.114
- Framework:React@17
```

**Comment by plainheart** [comment]
Similar to https://github.com/apache/echarts/issues/17072#issuecomment-1173256689. This feature was introduced in #16688 but the type definition was ignored. You are welcome to open a PR to fix it.
