### ISSUE TITLE
[Bug] 折柱混合，折线图开启areaStyle渐变 连续报错！！！！

### ISSUE THREAD

**Issue by superXuJm** [apache/echarts#17386]
### Version

5.3.0~5.3.3

### Steps to Reproduce

直接在你们官网的案例进行的测试，5.3.0之后才有的bug
![image](https://user-images.githubusercontent.com/41094982/179145922-6ff10c16-5631-4419-9cb2-eaf2c0cf083e.png)

### Current Behavior

      areaStyle: {
        opacity: 0.8,
        color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
          {
            offset: 0,
            color: 'rgb(255, 191, 0)'
          },
          {
            offset: 1,
            color: 'rgb(224, 62, 76)'
          }
        ])
      },

### Expected Behavior

速度更新吧 影响视觉效果，升级版本用新特性，结果出现新BUG！！！！

### Environment

```markdown
- OS:X
- Browser:X
- Framework:X
```

### Any additional comments?

XXX

**Comment by plainheart** [comment]
有个颜色写法不规范，`rgb` 应是 `rgba`。
