### ISSUE TITLE
[Feature] echarts横向柱状图根据不同数据展示不同颜色问题

### ISSUE THREAD

**Issue by hi-mashuo** [apache/echarts#17396]
### What problem does this feature solve?

您好，我对于echarts某些功能不太理解，所以前来请教，
我之前实现了纵向柱状根据不同数据来展示不同的渐变色，现在我需要把纵向改为横向，改完后发现数据是倒叙显示的，并且颜色显示不正确，望回复！谢谢！！！

### What does the proposed API look like?

无

**Comment by hi-mashuo** [comment]
![微信截图_20220718211233](https://user-images.githubusercontent.com/62926576/179518862-a3077654-754d-432c-b3da-56938ff1f7c2.png)
之前

**Comment by hi-mashuo** [comment]
![微信截图_20220718211212](https://user-images.githubusercontent.com/62926576/179518903-8d565d95-fe6a-4934-81f0-0b27c39d4752.png)
之后

**Comment by hi-mashuo** [comment]
横向代码
`
option = {
  tooltip: {
    show: false
  },
  yAxis: {
    splitLine: {
      show: true,
      lineStyle: {
        color: 'rgba(0, 230, 231, .2)',
        type: 'dashed'
      }
    },
    axisLine: {
      lineStyle: {
        color: '#0EBAB3'
      }
    },
    axisLabel: {
      interval: 0
    },
    axisTick: {
      show: true,
      inside: true
    },
    data: ['a', 'b', 'c', 'd', 'e', 'f', 'g']
  },
  xAxis: {
    interval: 1,
    splitLine: {
      show: true,
      lineStyle: {
        color: 'rgba(0, 230, 231, .2)',
        type: 'dashed'
      },
      color: function (params, index) {
        let colorList = ['#163EC0', '#2058BF', '#2374CF', '#2272AF', '#318DC1'];
        return colorList[index];
      }
    },
    axisLine: {
      show: true,
      lineStyle: {
        color: '#0EBAB3'
      }
    },
    min: 0,
    max: 4,
    axisLabel: {
      formatter: function (value) {
        let texts = [];
        if (value == 0) {
          texts.push('风险值');
        } else if (value <= 1) {
          texts.push('低风险');
        } else if (value <= 2) {
          texts.push('一般风险');
        } else if (value <= 3) {
          texts.push('较大风险');
        } else {
          texts.push('重大风险');
        }
        return texts;
      },
      color: function (v) {
        if (v == 0) {
          return '#ccc';
        } else if (v == 1) {
          return '#0180A7';
        } else if (v == 2) {
          return '#B39E0C';
        } else if (v == 3) {
          return '#B76C0A';
        } else {
          return '#AA2113';
        }
      }
    }
  },
  visualMap: {
    pieces: [
      // min-不包含， max-包含
      {
        min: 1,
        max: 1,
        label: '低风险',
        color: new echarts.graphic.LinearGradient(1, 0, 0, 0, [
          {
            offset: 1,
            color: 'rgba(1,128,167,0)'
          },
          {
            offset: 0,
            color: 'rgba(1,128,167,1)'
          }
        ])
      },
      {
        min: 2,
        max: 2,
        label: '一般风险',
        color: new echarts.graphic.LinearGradient(1, 0, 0, 0, [
          {
            offset: 1,
            color: 'rgba(179,158,12,0)'
          },
          {
            offset: 0,
            color: 'rgba(179,158,12,1)'
          }
        ])
      },
      {
        min: 3,
        max: 3,
        label: '较大风险',
        color: new echarts.graphic.LinearGradient(1, 0, 0, 0, [
          {
            offset: 1,
            color: 'rgba(183,108,10,0)'
          },
          {
            offset: 0,
            color: 'rgba(183,108,10,1)'
          }
        ])
      },
      {
        min: 4,
        max: 4,
        label: '重大风险',
        color: new echarts.graphic.LinearGradient(1, 0, 0, 0, [
          {
            offset: 1,
            color: 'rgba(170,33,19,0)'
          },
          {
            offset: 0,
            color: 'rgba(170,33,19,1)'
          }
        ])
      }
    ],
    outOfRange: {
      color: '#999'
    }
  },
  series: [
    {
      type: 'bar',
      barWidth: 40,
      data: [4, 3, 2, 1, 4, 3, 2],
      itemStyle: {
        normal: {
          barBorderRadius: 5,
          // color:"red"
        }
      }
    }
  ]
};
`

**Comment by plainheart** [comment]
See [this demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWZjADaRAC5l1NMBnAC2AHdiAzAQ13IFNTYBfAGg4E8AggA8I5YqgxlyIXBDAAZCNFbiOZWFVrEwAJwCurXpPWzlAZTB9cKksfWwAxnmA7iAch0BzAEaMAFAAM3LAATADMQaFhAIzBAHQhAJRuRvZkliA2bgAmjFSs2W5qZJzFPMWMIuSKyqp2mKasFlY2EmmYTrgu7gDEAQCiAEICg2FF9VxlqWSVovKM3qy4dWlKYKw6AG7MxAFTFVUAKhAOANYr9pp0WPqGxZhK5BDZNroG-3a5YIzEANpujBSsDc3iBbgcYMKwTcrDB9DBnjcAF1pg9oJsNmxtLcOOVJEJhKILmj1lsdrBYsVpLIFEpWvcNNRrm87hNGs1rMT7J1usCvL5AsFwpFwrFYAlkqj7Bksrl8oUGXi0jzXLB6HpoA5IDBYH4QIwdIwALbkYJKF5CRK2dqwaxgRzOHSKcj2xD_HrRABsYX6AGEAmCeiEAgBWAAcgwAYoHwgB2AAsvuj0KDIVjIQEyeBPRiYYAIr7osiANwMzA6VhgPQ6OAq51gX7m1hCJGlialOxKmZVGr0iZXbEGKUNOkcvs2lW9AbDUbjNId9RdzBGpS7KVGyrEeNS2bVBZLLmYeguDdgUkMDVaqBwPzbXAGK1tdp2rDNsDkBCwX6tsuwCD0XU7wMBBEACR9f0wdYhHfOIQD0Kg_DcQA5jMASzTAB4FNxEjbG1OFgJY2D_ADb2YYCAB5EGicCJnUKCYLghC3EAOXlUMw7D2lw_DWEIwCSK48jQiom1ILfchYPgyhEMAADlABoglisN_DiWC4_8ePvPjEDCQShNo0T6IktxAGD4wByTTktj5zwpTrW0kSxIYwBZxJMlDWIU38KyrGtX2g8gzJKYcHS6VV1U1bUb02LTViIzYQNgMCrJtNzqzgNwegcVK3B8xcLIIlTb2iyi4vaBKPOSgJojDAIBFjdKFKy5TIuipICrSIqkp6UYAE5-gCX1quorhau43L4A08LCsrRLs0GWNPX9ARepwgan3i8bip6AQBBCaJojGDKSkVMpcWmTZRD0ZgAFlGCIArsggI1WGgJ4YDXYoQAgVgHFYMQvwZAB6H7YBXaAAFpAFg5QBQZUAahVABh_gHKiByGGSW-xAeISk-o3IRUb8hp92WYFmKc7H_N5ZQaDwhxKANGDPENEBKBOOJewNABxQ0bvusA_DFSIeeCX4IKa9pgHoeg2DALGBY6R13H5fxYmiEIw24L1Y24MC5yEpd2iRm1hdFytnr69RJz5Hw5eVxXlc9VXKI1nDfyRRJFT8nWyBR0IiYx4gQiJ3BcfcGSWKJk3SfJymdGp2n6YcRm6RZtm3ugTnueCXnvqNwW0j1sWJYzqWApls2udjdrlfDC21eSAWtbSV2s5FnOYqJ43pdNgVohLsulYV5Wq4zhd2kd53Ed_d2wk9zdYHH38_cWPHDMclJfxD1gyfe8PI8u6PY-UePGHZpOudT4-m_ToTM_sbODYpZuyBNjwi7K8fogCbugnV6vb7ry-G-voJJeJqqB-7cwzP1fsrIIttq4Oydu2F2o9VywG3KPSeyC-qzwPMCByQdl6t1DuvKmokaZbwZkzHQrN96J2TifNO_MM7f3UFfcWN8AH31lsXIIYRn6lw_v3L-ACmGG3PvnXkwC5axk4dw3udt2IwP2nYFExRgB6DAAAeXoAAJUYNATw45uSt2Su1IxMiB5djYDoN6X06HqFdjKdwvgdBLwmA4gA6s8MAlAtz_wmF8H4X5txTyFMEMUATx6hEURMOQrAjRjkPGQaAJ5yQMNgA4wYLgXg6C0TdeCxAQy3z-oAwgAAiCs2QikuXbAdSQSJ0CcGLEAA) for your reference.

**Comment by hi-mashuo** [comment]
非常感谢，麻烦您了
