### ISSUE TITLE
[Bug] This dependency was not found:  * echarts/lib/data/helper/completeDimensions in ./node_modules/echarts-wordcloud/src/WordCloudSeries.js

### ISSUE THREAD

**Issue by baixinfei** [apache/echarts#17394]
### Version

5.3.0

### Steps to Reproduce

This dependency was not found:

* echarts/lib/data/helper/completeDimensions in ./node_modules/echarts-wordcloud/src/WordCloudSeries.js

### Current Behavior

This dependency was not found:

* echarts/lib/data/helper/completeDimensions in ./node_modules/echarts-wordcloud/src/WordCloudSeries.js

### Expected Behavior

This dependency was not found:

* echarts/lib/data/helper/completeDimensions in ./node_modules/echarts-wordcloud/src/WordCloudSeries.js

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Please upgrade the [echarts-wordcloud](https://github.com/ecomfe/echarts-wordcloud/releases) extension library to the latest.

**Comment by able-liu** [comment]
V5.4.1 has same issue
