### ISSUE TITLE
[Bug] visual Map cursor is missing when mouse over map label

### ISSUE THREAD

**Issue by ybintian** [apache/echarts#17408]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=map-usa

### Steps to Reproduce

move mouse when pass map's label, visual map's cursor is missing
![image](https://user-images.githubusercontent.com/22540492/179883909-a3213cdd-ee67-4cb3-ad34-e67a815511b7.png)

### Current Behavior

move mouse when pass map's label, visual map's cursor is missing

### Expected Behavior

keep cursor on

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Thanks for your feedback. This bug has been fixed by #17346. Please wait for the next release 5.4.0.

**Comment by ybintian** [comment]
Thanks, when next release?

**Comment by plainheart** [comment]
There is no certain date for now. Maybe in next month.
