### ISSUE TITLE
[Feature] 我想在横向柱状图 right 和 insideRight 同时显示不同的信息

### ISSUE THREAD

**Issue by joyzhang2022** [apache/echarts#17400]
### What problem does this feature solve?

![QQ20220719-133232](https://user-images.githubusercontent.com/5369581/179672725-709b534b-7dd0-43b0-b922-a69fe7bbb7c7.png)
我想同时在横向柱状图中显示不同的信息，就像图片中一样，请问如何设置可以达到这个效果，谢谢

### What does the proposed API look like?

在横向柱状图的 right 和 insideRight 同时显示不同信息

**Comment by plainheart** [comment]
1、或许可以创建两个相同的系列，一个 `label` 显示在右侧内部，另一个的 `label` 显示在右侧外部，然后设置其中一个系列的 `barGap` 为 `-100%` 使其重叠在一起。
2、使用 `labelLayout` 调整 `label` 的位置。[参考示例](https://echarts.apache.org/examples/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsCeBBAHhAzgFzJrqxgYgCmxA5AMYCGYVA5sAE4a0A0p6AE2aNiAbVoBZGL1i0AUoxCNoM2gHUqA1QBUAFgFdVAMQ4RVAZWYX9KgLp8ysRnnwAZRgCMqAG2KpH6Pi6wADuxABmjN74VPywAL6k8Q6wOLgEfnEU1HQAblH6VLRJKTGmVESwonH-AUJgIlUAjABMAAw8sO0dsE0ArD0AHD0A7D1NTeMAzG32cejZNLIejBy887Denj6ZAWRBocRgHIUpe-GcALbMLBx0SB7xjkj08et76CDA-BCQMHSmVi6MDvD70YDeTh0ADEbThoPOMDAGggQLAdA8EK0ZwCLBwYAAQpwBFQOABhCFQ2TQ8K0hG4qj4okcEkcNQQARgXTENoAOj6G2SGy2Xm87gwwH0YAAFEoOIxLvgAJQkD6wDhUMD6DhwWpqgQ4YgAWllqwV-F5Ip8ACUqPQwLyQhyubAAPSwOXm3l4h3eKjQVhclUAKlgpvliu9jId-BA3l-0tosiVolmlv9gd0sAA1LApkqNuhEnti2RS7YUPEANxAA)
