### ISSUE TITLE
[Bug] 3d柱状图在移动端不显示tooltip

### ISSUE THREAD

**Issue by miracleDD** [apache/echarts#17404]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1

### Steps to Reproduce

官网中示例可复现此问题，3d柱状图tooltip在pc显示正常，切换到移动端模式hover或点击均不显示tooltip

### Current Behavior

3d柱状图tooltip在pc显示正常，切换到移动端模式hover或点击均不显示tooltip

### Expected Behavior

3d柱状图tooltip在移动端正常显示tooltip

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by DoubleCorner** [comment]
I have the same problem. 3d Bar, 3D scatter and map3D has this problem.
