### ISSUE TITLE
[Feature] 散点图数据相等,导致重叠!

### ISSUE THREAD

**Issue by MenFsq** [apache/echarts#17415]
### What problem does this feature solve?

散点图,数值相等,导致多个散点重叠到一个地方,有没有什么方法可以使散点自动分散一些?
![1658401608105](https://user-images.githubusercontent.com/71696702/180199920-f0b72125-206d-4e1c-b2cd-ba2489caf793.png)

### What does the proposed API look like?

symbol设置一个参数,可以使散点不重叠,就近排列!

**Comment by Ovilia** [comment]
因为数据靠近而改变数据位置这个需求很奇怪，如果目的是希望看清数据，可以通过一些不同的方式解决，比如：

- 为散点设置透明度
- 用描边代替填充色
- 为不同的系列使用不同形状
- 用 labelLine 和 label 标注数据点信息
