### ISSUE TITLE
[Feature] Adding a second axis pointer to one x-axis

### ISSUE THREAD

**Issue by cunj12** [apache/echarts#17423]
### What problem does this feature solve?

I want to be able to add a second x-axis pointer on one x-axis.

### What does the proposed API look like?

The axisPointer property of the xAxis could be an array of axisPointer objects.

**Comment by Ovilia** [comment]
Axis pointer should typically be at the mouse/touch position. Why is multiple axis pointer required?

**Comment by cunj12** [comment]
We use trigger 'none' so that the axis pointer is only moved when the user drags it, we would like this functionality so that the user could compare values at two separate data points.

**Comment by Ovilia** [comment]
This may not be a typical usage of axis pointer. You can probably call `setOption` to hack it.

**Comment by cunj12** [comment]
I did think about adding another x-axis and duplicating the data, but I think that could lead to some performance issues.
