### ISSUE TITLE
[Discuss] 为什么v4升级v5版本后yAxisLine在xAxis.type = category 后就消失了

### ISSUE THREAD

**Issue by songyule** [apache/echarts#17433]
### Version

5.x

### Steps to Reproduce

参考官网demo: https://echarts.apache.org/examples/zh/editor.html?c=line-simple

### Current Behavior

v4升级v5版本后yAxisLine在xAxis.type = category 后就消失了
https://echarts.apache.org/examples/zh/editor.html?c=line-simple

### Expected Behavior

![image](https://user-images.githubusercontent.com/23656890/181198646-2ec8c217-6142-4018-998d-102954fe0819.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

看了升级文档没有提到这一点，看了代码发现当axis.show = auto 就会隐藏，这个设计是出于什么考虑

**Comment by plainheart** [comment]
默认隐藏 Y 轴轴线是 ECharts 5 的样式设计使然，开发者需要手动设置 `axisLine: { show: true }` 来使 Y 轴线显示。参见 [ECharts 5 发布会文字教程](https://zhuanlan.zhihu.com/p/348799432#:~:text=%E5%9B%A0%E6%AD%A4%E6%88%91%E4%BB%AC%E5%81%9A%E7%9A%84%E6%AF%94%E8%BE%83%E7%9B%B4%E8%A7%82%E7%9A%84%E4%B8%80%E4%B8%AA%E6%94%B9%E5%8F%98%E5%B0%B1%E6%98%AF%E5%8E%BB%E6%8E%89%E4%BA%86%E7%9B%B4%E8%A7%92%E5%9D%90%E6%A0%87%E7%B3%BB%E6%9C%80%E5%B7%A6%E4%BE%A7%E6%95%B0%E6%8D%AE%E8%BD%B4Y%E8%BD%B4%E7%9A%84%E9%BB%98%E8%AE%A4%E6%98%BE%E7%A4%BA%EF%BC%8C%E5%B8%8C%E6%9C%9B%E9%80%9A%E8%BF%87%E5%87%8F%E5%B0%91%E4%B8%8D%E5%BF%85%E8%A6%81%E7%9A%84%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%EF%BC%8C%E6%9D%A5%E8%BE%BE%E5%88%B0%E6%9B%B4%E6%B8%85%E6%99%B0%E5%9C%B0%E4%BC%A0%E9%80%92%E4%BF%A1%E6%81%AF%E7%9A%84%E7%9B%AE%E7%9A%84%E3%80%82)
