### ISSUE TITLE
[Feature] roaming thumbnails for maps, graphs, trees, sankeys and etc.

### ISSUE THREAD

**Issue by Ovilia** [apache/echarts#17432]
### What problem does this feature solve?

For series like maps, graphs, trees, sankeys, data shapes sometimes may be too large to displayed without overlap in a chart. Some charts supports roam (not sankey) but the user may not have an idea about the relationship between the current visible data and the overall data. Related issues include: #14061 #16926 #17214

Thumbnails are useful in these cases. For example, if we could provide a thumbnail like the design below, we can give users the intuitive about the overall shapes of the whole series and the current visible area.

![graph-roam](https://user-images.githubusercontent.com/779050/181175463-6c784efd-92b8-49d8-910f-55ca65572ce6.png)

### What does the proposed API look like?

There are mainly two workflows to achieve this feature. 

### Plan A: Render in each rendering loop

In this method, in each rendering loop, the thumbnail component calls each series to render the thumbnail shapes after rendering the series itself. 

Most probably, we don't have to render everything in a series. For example, for some series like graph or sankey, the labels may be ignored to save time or provide a cleaner preview, while other series like tree series should not ignore labels since the label lengths are probably informative in the thumbnails. Each series can decide which parts should be rendered in the thumbnail.

### Plan B: Render when `setOption` is called

Since having accurate preview is not a must in the thumbnails, maybe they can be generated only when `setOption` is called.

With this approach, we don't have the thumbnail updated when elements are emphasized or selected. This should not be a big problem. But for draggable series, we may have to listen to drag events or provide a method to update the thumbnails for the users to call in drag events.

> For forced graphs, it should be frequently updated until the calculation of position has been stopped.

## API

The following options are added to map, graph, tree, sankey series:

```ts
zoomCenter: [number | string, number | string], // not sure if the current `center` does the same thing but it doesn't look like so
thumbnail: {
  show: boolean,
  top: number | string,
  bottom: number | string,
  left: number | string,
  right: number | string,
  width: number | string,
  height: number | string,
  borderColor: Color,
  backgroundColor: Color,
  overlayBackgroundColor: Color, // the thumbnail area minus the focus area
  selectedDataBackground: { // the focused area
    lineStyle: LineStyleProps,
    areaStyle: AreaStyleProps
  }
}
```

Example:

```ts
chart.setOption({
  series: [{
    type: 'map', // or 'graph', 'tree', 'sankey'
    roam: true, // new for sankey
    zoom: 2, // new for sankey
    zoomCenter: ['50%', '50%'],
    thumbnail: {
      show: true,
      right: 10,
      bottom: 10
    }
  }]
});
```

Optionally, if we wish to provide the user the ability to update the thumbnail:

```ts
chart.on('mouseover', () => chart.updateThumbnail({ seriesIndex: 0 }))
```

**Comment by Ovilia** [comment]
I'm not sure if it would be proper to make this a new type of `dataZoom`, like `dataZoom: { type: 'thumbnail' }`. The behavior looks similar but what series can work with is different.

**Comment by Lruler** [comment]
I'm not sure the difference between “overlayBackgroundColor” and "selectedDataBackground"

**Comment by Ovilia** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/779050/183026132-6e6c997f-a385-412b-916c-ffe01f03fa80.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/779050/183026301-b2e577b1-1cd3-40a7-a6f4-e92289a1f886.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/779050/183026477-d70b7766-4e88-4bfb-b4a0-57fbd16d0e66.png">

**Comment by Ovilia** [comment]
We should also discuss about whether roaming should be triggered outside of the bounding box of the series. There are some issues related: #13076 #9239 . This is especially useful when the user zoom out the series to be too small to revert to original size.

**Comment by MdAnees1** [comment]
Is `roam` feature available for `Sankey` chart in the latest release?

**Comment by li942475402** [comment]
Perhaps can start by adding a configuration item maybe called `limitInWindow` so that keep series Bboxes always in windows. Dragging any graphics out of the window is not a good interactive experience

**Comment by shmilyoo** [comment]
请务必使用超大量节点树图或关系图进行测试。
根据我的使用场景，当树节点非常多，比如800个节点的时候，即使放大了很多倍，仍然有很多节点是重叠的。
这个时候，我想动态的更改symbol的size来进行适配，但是就会显得整个图非常的空旷。

Be sure to test with a super-heavy node tree diagram or relationship graph.
According to my usage scenario, when the tree nodes are very large, say 800 nodes, there are still a lot of nodes that overlap even after zooming in many times.
At this time, I would like to dynamically change the size of the symbols to fit, but then it will look like the whole graph is very empty.

**Comment by SincerelyUnique** [comment]
This feature is very cool, do we support the zoom function in sankey diagram now? :)
