### ISSUE TITLE
[Bug] 当设置showSymbol为false的时候 标签不会显示

### ISSUE THREAD

**Issue by daisy0123** [apache/echarts#17436]
### Version

5.3.3

### Steps to Reproduce

当设置showSymbol为false的时候 标签label不会显示，label的show已为true

### Current Behavior

当设置showSymbol为false的时候 标签不会显示

### Expected Behavior

当设置showSymbol为false的时候 希望标签不受影响，可以走标签的配置

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
label 是设置在 symbol 上的，如果 symbol 不被绘制，label 也会不绘制。可以设置 `symbolSize` 为 0 来隐藏 symbol 但保持显示 label。

**Comment by daisy0123** [comment]
如果 symbolSize 设为0 的话 会影响 单点显示不了，hover的时候 那个点才会出现。

**Comment by daisy0123** [comment]
如果symbolSize 设置为0的时候，会影响 单点显示不了

**Comment by plainheart** [comment]
你不是希望不显示点 (symbol) 只显示 label 吗？

**Comment by daisy0123** [comment]
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/11910330/181701101-4a8fd8b6-3787-4137-a03d-beb368711b77.png">

**Comment by daisy0123** [comment]
> 你不是希望不显示点 (symbol) 只显示 label 吗？

恩恩，显示label的时候，设置symbolSize 为0 可以做到，
但是在不显示label的时候，希望点不明显，也希望 单点可以显示，这个有什么办法实现么 ？

**Comment by plainheart** [comment]
参考这个[示例](https://echarts.apache.org/examples/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAVgAwA0MATAMyEnEAsRxWAHEUyQGx4C6AUJyAA5QBLcGhgBvTjBgAPAIJSBEAFxiJkmFACevAKbKA5MCTaA5iABOGvQVWTEyZRj0BZcFZh6AKgFdtbvQHVtOD8PAAsvPwAxMwE_AGUkeK8wPS5JAF9rSQ05BWVxNXUtXXcANwQAGx89VUzVCG0Y7SVMGxVCyU0dfQqBMF8sjrsEZWGAOgBbBF4AChmBKG0JogE4KQBKNAA-do7JUEhYCFCQAHc4jQmAIxAKkVWpGB2sGAAyV_gkBAwHmABaGBYdhodBgLwVO7vGALJYwACEoPBFTahTM2igXjMYF2e0k5SqJRhyxRHQglxuFTiAgAXiVjmcLtdbjAAPwwegwZSEEmFJa8UIICB5HG4yQQQwVOknc7k248tTpeWKvbpdaDQoVBBXbQVfLy-mnZRQMw-EnKhWqLjpADcQA)。

**Comment by daisy0123** [comment]
> 参考这个[示例](https://echarts.apache.org/examples/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAVgAwA0MATAMyEnEAsRxWAHEUyQGx4C6AUJyAA5QBLcGhgBvTjBgAPAIJSBEAFxiJkmFACevAKbKA5MCTaA5iABOGvQVWTEyZRj0BZcFZh6AKgFdtbvQHVtOD8PAAsvPwAxMwE_AGUkeK8wPS5JAF9rSQ05BWVxNXUtXXcANwQAGx89VUzVCG0Y7SVMGxVCyU0dfQqBMF8sjrsEZWGAOgBbBF4AChmBKG0JogE4KQBKNAA-do7JUEhYCFCQAHc4jQmAIxAKkVWpGB2sGAAyV_gkBAwHmABaGBYdhodBgLwVO7vGALJYwACEoPBFTahTM2igXjMYF2e0k5SqJRhyxRHQglxuFTiAgAXiVjmcLtdbjAAPwwegwZSEEmFJa8UIICB5HG4yQQQwVOknc7k248tTpeWKvbpdaDQoVBBXbQVfLy-mnZRQMw-EnKhWqLjpADcQA)。

好的 感谢

**Comment by plainheart** [comment]
先前那个示例似乎有点 bug，刚刚更新了下。
