### ISSUE TITLE
[Feature] 图例能否支持每页几行配置，全选反选显示规则等等

### ISSUE THREAD

**Issue by daisy0123** [apache/echarts#17435]
### What problem does this feature solve?

目前需要类似功能
![image](https://user-images.githubusercontent.com/11910330/181233456-d84c313d-dcf2-4e6e-b63d-365cd7688c0f.png)
发现之前有人提过：https://github.com/apache/echarts/issues/8742

### What does the proposed API look like?

no

**Comment by wangxue1993** [comment]
> ### What problem does this feature solve?
> 目前需要类似功能 ![image](https://user-images.githubusercontent.com/11910330/181233456-d84c313d-dcf2-4e6e-b63d-365cd7688c0f.png) 发现之前有人提过：#8742
> 
> ### What does the proposed API look like?
> no

我自己画了一个div图例 根据点击事件触发自定义实现了，https://echarts.apache.org/zh/api.html#action.legend；但是新问题又来了 ，自定义的图例和图表不能一起下载下来
