### ISSUE TITLE
[Bug] 类目是俄语时，tooltip自定义formatter，name和value位置顺序反了

### ISSUE THREAD

**Issue by anyanyan07** [apache/echarts#17438]
### Version

5+

### Steps to Reproduce

1.官方示例'基础柱状图'，
2.修改tooltip,formatter自定义显示
3.其中一个类型修改为俄语
![image](https://user-images.githubusercontent.com/20201855/181404711-35d53c47-ce3c-4b66-a0c5-fb36656432d5.png)
![image](https://user-images.githubusercontent.com/20201855/181404769-e2c6d4bb-0572-4c02-a98d-7787b10fdca0.png)

### Current Behavior

俄语，波斯语时自定义tooltip二者顺序相反

### Expected Behavior

与其它语言例如中文，英文表现一致

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
你自定义了 tooltip 的 formatter 并且返回了 HTML 字符串，这看起来是 HTML 的渲染行为，并不是 ECharts 能决定的。有些语言习惯可能是 rtl，试试给 div 指定 direction 为 ltr 看看。
