### ISSUE TITLE
[Feature] emphasis full path of link/node from start to finish of chart

### ISSUE THREAD

**Issue by ElayGelbart** [apache/echarts#17448]
### What problem does this feature solve?

for Sankey series, emphasis focus can have 4 options: "none" | "series" | "self" | "adjacency".
i want to be able to focus all the path of connected edges and node from start to end of the selected edge\node and not only one depth before after

### What does the proposed API look like?

new option for emphasis: "**fullPath**"

**Example:**

```js
chart.setOption({
  series: [{
    type: 'sankey', 
   data: sankeyData.nodes,
   links: sankeyData.links,
   emphasis: {
     focus: "fullPath",
     }
  }]
});
```

**Comment by MJsuriya** [comment]
When this will be available to use?
