### ISSUE TITLE
When dataZoom is performed something overflow is visible when barBg is enabled

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#17443]
### Version

5.3.3

### Steps to Reproduce

1.Create a basic Bar chart
2.Add bar background property and dataZoom property.
3.Select zoomType as 'none'
4.Try to zoomin and u ll see some barBg being overflown

### Current Behavior

When dataZoom is performed something overflow is visible when barBg is enabled
![bar-background](https://user-images.githubusercontent.com/96459765/181684070-c2e1dd9e-22e0-48dc-8e24-a1f80e84d06b.png)

### Expected Behavior

When dataZoom is performed no overflow should visible when barBg is enabled.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dimer47** [comment]
Hi @Teja0191,

I had the same problem and found the answer on another issue. Hope this can help you ?

https://github.com/apache/echarts/issues/15189#issuecomment-896244515
