### ISSUE TITLE
[Feature] Could "emphasis.focus = 'series'" support DIY other series' fade out style ?

### ISSUE THREAD

**Issue by HY-HY-49** [apache/echarts#17446]
### What problem does this feature solve?

when emphasis.focus is 'series', other series fading out. If we can custom the style, such as 'opacity', we can complete more visual effect. 

### What does the proposed API look like?

such as the configuration:
```js
options = {
    series: [
        ...
    ],
    emphasis: {
        focus: 'series',
        fadeOut: { // work when focus is 'series'
            lineStyle: {
                opacity: 0.5,
            }
            ...
        }
};
```

**Comment by plainheart** [comment]
You can specify the [`blur`](https://echarts.apache.org/option.html#series-line.blur) style for each line series. Please refer to this [example](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAJ4CCAHhAM4mrrpjUhYkDkAbgEMMAVyy8qFKvQbNWVDlx6xeAY0FhcwAE7VeldrAIbBJANq8AsjH0qAKmNu8A6lgJO7ACxFOAYtognAGUNYJFoXgBdSQNYJiwArBZYMwVkNPRoQQBbZV4AEQhtLFUwfQzYTm4-DAhocVjDLGyQT0EmOXTDQwAzYFURZN54xKYJbtgpCYAjUW15CfRa-qDObAXF9FBBVQhOEgAGADoAVgr0KcW95tXqda7N2G3d_dhjs83SCsvDYzBTFIAZgATAdyLBAQdgeDIQBGGGAgAsMIAnGCIZCYaDooYfg9DFlcnxLIIIBhYLR3I12FU8ssGhVmq12p02Is-gMhiMIElxt08ehZiJ5vjuvTbvc2ZtnntqIdzpNqYZrtkJcopYsZa8DgqvhMBUYTOZYaDwbCQWaDvDYObkbA0eDgZjYMDYQccew9bBoqQANxAA).

**Comment by HY-HY-49** [comment]
Thx, I hava come true my design by setting `blur`.
