### ISSUE TITLE
[Bug] series line emphasis scale can't reset to false

### ISSUE THREAD

**Issue by solid9527** [apache/echarts#17441]
### Version

5.3.3

### Steps to Reproduce

1. create a chart 
2. setOption emphasis scale > 1 or true
3. setOption again , this time emphasis scale set false
4. reset scale "false" not work, when you hover it still scale

### Current Behavior

setOption merge not current 
scale false not working

### Expected Behavior

set false and scale should not happen

### Environment

```markdown
- OS: windows
- Browser: chrome
- Framework: vue
```

### Any additional comments?

try to hover legend and let symbol dont scale

**Comment by plainheart** [comment]
Thanks for your feedback. It seems unexpected and should allow being disabled via setting it to be `false` or `0`.
