### ISSUE TITLE
[Feature] Support negative and zero when axis type is 'log'

### ISSUE THREAD

**Issue by kitee0325** [apache/echarts#17459]
### What problem does this feature solve?

it will fit more scenes.

Replace the existing with a method similar below
```javascript
/**
 *   x > 0 y = log10(x) + 1
 *   x = 0 y = 0
 *   x < 0 y = -log10(|x|) - 1
 */
```

### What does the proposed API look like?

No change

**Comment by li942475402** [comment]
Maybe there are some methods that I can extend some custom scale?
