### ISSUE TITLE
series.type: 'scatter' single select selects multiple data points not just one

### ISSUE THREAD

**Issue by yossico2** [apache/echarts#17454]
### Version

5.3.3

### Steps to Reproduce

option = {
    ...
    series: [{
        ...
        selectedMode: 'single',
        ...
    }]
    ...
}

### Current Behavior

MULTIPLE points are selected when click on a single point in scatter chart

### Expected Behavior

select a single data point

### Environment

```markdown
- OS:ubuntu20.04
- Browser: Chrome
- Framework: React
```

**Comment by susiwen8** [comment]
Might be releated to #17206
