### ISSUE TITLE
[Bug] Toggling legends changes the position of the bars

### ISSUE THREAD

**Issue by spiral2k** [apache/echarts#17468]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-test-yc2pff

### Steps to Reproduce

toggle legends

![image](https://user-images.githubusercontent.com/3942027/182646131-7a53ea5e-930c-47cd-a98e-c828a03eaf77.png)
![image](https://user-images.githubusercontent.com/3942027/182646150-f0cce669-93fc-43a7-8654-19e8b11f2d24.png)

### Current Behavior

Toggling the legends changes the position of the bars

### Expected Behavior

I expect the bars to be in the same position when hiding some

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 103.0.5060.114
Framework React@18.0.0
```

### Any additional comments?

thank you

**Comment by Ovilia** [comment]
The 20th line of your App `xAxis: [options.xAxis[1], options.xAxis[2]]` seems to be wrong. It should be `xAxis: [options.xAxis[0], options.xAxis[1]]`, althrough I think this is unnecessary because the chart will keep the previous settings.

**Comment by spiral2k** [comment]
thanks, Olivia, seems like it fixed the issue that I've created :)

have a great day
