### ISSUE TITLE
[Bug] Heatmap does not work with value axis

### ISSUE THREAD

**Issue by amirajv** [apache/echarts#17465]
### Version

5.3.3

### Link to Minimal Reproduction

https://jsfiddle.net/amiraj/5Lka0wmx/4/

### Steps to Reproduce

1. Create a regular heatmap and set the axis types to 'value'
2. zoom in and out and you see bad rendering of the pixels

### Current Behavior

value type axis won't work with heatmaps. One issue for example is when zooming you see bad pixel locations:

![image](https://user-images.githubusercontent.com/4806889/182493400-09d75198-b8a1-4eca-b1a7-27406a2d3138.png)

These issues can be fixed by changing axis type to category. But that has it's own issues and this fix is a hacky fix.

### Expected Behavior

heatmap chart behavior should not depend on axis type.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
It's suggested to use the unminimized version in the development environment to get some helpful debug information. The heatmap series must have two category axes currently. The value axis is not supported.
