### ISSUE TITLE
if chart container is small funnel chart data points are overlapping 

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17469]
### Version

5.3.3

### Steps to Reproduce

1.create funnel series for data points and give static heights 
2.container height should be small 

### Current Behavior

![image](https://user-images.githubusercontent.com/97290751/182772828-b1e8855f-6d4c-405c-aeb2-edf6476dc78b.png)

sample is here
[funnel issue .txt](https://github.com/apache/echarts/files/9256987/funnel.issue.txt)
take this sample copy the code in a file  and save it as .html and observe 

### Expected Behavior

no overlapping should be observed 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This doesn't seem to be a bug. It probably because you set `data.itemStyle.height` to be a fixed height.
