### ISSUE TITLE
[Bug] 5.3.3版本使用主题文件出现警告信息

### ISSUE THREAD

**Issue by Liangism** [apache/echarts#17473]
### Version

5.3.3

### Steps to Reproduce

1.使用npm安装echarts；
2.使用示例默认的选项；
3.引入了macarons，shine主题；

### Current Behavior

在引入了shine主题文件后，在控制台出现警告信息：

> [ECharts] DEPRECATED: 'normal' hierarchy in iconStyle has been removed since 4.0. All style properties are configured in iconStyle directly now.
发现是theme/shine.js内toolbox配置项导致，并且macarons.js也有同样问题。
` toolbox: {
            iconStyle: {
                normal: {
                    borderColor: '#06467c'
                }
            }
        },`

### Expected Behavior

希望不要出现这个警告了:)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
为了便于使用，减少配置项层级，早前取消了 `normal` 这个层级。大概是因为这个主题文件较早而忘记了更新为新的用法。如果感兴趣的话，欢迎提 PR 修正下～

**Comment by Liangism** [comment]
> 为了便于使用，减少配置项层级，早前取消了 `normal` 这个层级。大概是因为这个主题文件较早而忘记了更新为新的用法。如果感兴趣的话，欢迎提 PR 修正下～

😁好的，我已经将`theme`文件的`normal`替换了
