### ISSUE TITLE
radar width config not working

### ISSUE THREAD

**Issue by Hachiaaa** [apache/echarts#17484]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=radar&version=5.3.3

### Steps to Reproduce

1. set option 
`js
radar:{
    axisName:{
        width:100,
        backgroundColor:'pink',
    }
}
`
2. as you can see, there is no width change at all

### Current Behavior

width does not  change as expected

### Expected Behavior

width should change

### Environment

```markdown
- OS:macOS Monterey
- Browser: Chrome 103.0.5060.134
- Framework:
```

**Comment by CuteSunLee** [comment]
hi, I'm interested in fixing this issue.

**Comment by timelessover** [comment]
mark
