### ISSUE TITLE
请问有什么地方可以查阅 echarts 的一些扩展api吗？

### ISSUE THREAD

**Issue by muyuanshan** [apache/echarts#17493]
### What problem does this feature solve?

echarts.extendChartView，echarts.extendSeriesModel 等.... 这些扩展api 文档里面没有找到请问哪里可以查阅吗？

### What does the proposed API look like?

【期望结果】

**Comment by Ovilia** [comment]
没有，比较建议参考[现有扩展](https://echarts.apache.org/en/download-extension.html)的源码，主要是水球图和字符云。其他需要通过阅读 ECharts 源码了解。

**Comment by muyuanshan** [comment]
> 

好的感谢
