### ISSUE TITLE
[Bug] The data display function in toolbox is invalid in the thermal map

### ISSUE THREAD

**Issue by L693** [apache/echarts#17509]
### Version

5

### Steps to Reproduce

The data display function in toolbox is invalid in the thermal map
![image](https://user-images.githubusercontent.com/64128455/184321900-18936122-f7f5-4525-86af-9cc9ba483a75.png)
![image](https://user-images.githubusercontent.com/64128455/184321981-efe787ce-74ed-4ad4-8f3b-d1de6358ba86.png)

### Current Behavior

The data display function in toolbox is invalid in the thermal map
![image](https://user-images.githubusercontent.com/64128455/184321900-18936122-f7f5-4525-86af-9cc9ba483a75.png)
![image](https://user-images.githubusercontent.com/64128455/184321981-efe787ce-74ed-4ad4-8f3b-d1de6358ba86.png)

### Expected Behavior

The data display function can normally display the data in the thermal map

### Environment

```markdown
- OS:
- Browser:Chrome
- Framework:Vue
```

**Comment by fuchunhui** [comment]
can you provide an example?

Let's try it like this, it works! [simple demo](https://echarts.apache.org/examples/zh/editor.html?c=calendar-heatmap&code=GYVwdgxgLglg9mABAcwKZQGowE5RAGwBEBDKYgCgE9VjsBKRAbwChFFrbEBedm7RAD4DEAcgBMABgCMAdhEBuVogBunACalU3RAGpUEABa0oAZwB0YEAFsARqmxmADrROoSUVFT67RAWmn-UiJ0imyq_Khgatp6hsbmlrb2Ti5umuQ6HPw6iFI-IoGBwaEq6sSUACowVlo8AMwAbBISiABUiGIALG25zRIl4YgaZNoA2gC6JcBw_OSDsDXaw6jyiAtaADyIkWqr67o8GpXVqAwsbGzDxE4gJgbko0oX23G45tPYVqRmH19QVTVyCJKCDKL4ALLg3xqNQiAA0axOdDhTwu4NIBh--DgM3I6KgmOwxCicCs5AY7SkfQkdFR4xCSgAvkpsOgQNgkFdFMy4I5YAhtOc1jj8DY4AAPABcTFRdzgAHdpVBsCBUCjnsAaHhWdKhc8rgAtHFWXWo56UACC4pgJgAklFUFLEAAiMAIVDOs2IRnq55DUjELCoRUyv0XVnENQAeTA-Eo0uAxHwri9Pq9X2QMAgFUojlQprDbCgufziFGzvwMDAHoRzpstGd41TvuerJMUBmpcYabDJmIylQFrtGa7zOeY-9vtgUHwXdRHcc0rqEhbiFnwCg0pEEEiHmw8Pnjs3ohIMDjiAAyh5HIgAMJwcBQERMqci2CLpg9lQ2kBJ9EfvVECsKtpRXVEvidKk-lXYs8y3RwYH0YMbVQA9nhmRCwGPEQDAwgAvBAyHwNCLnXbCdyw-wSKLXlpQaABWF8lAgJMdloAsLgXaUpEkVcyKXMDWxgZADGPZdVx3fB8AvGA8NLUYRGIEAO3hXI6nGVciTANAt0kKQGmoxAYA8Kwr0oWcOOeMVsDUewAHUYDUAlQLMRjx1XLIABliDsfBdUQOUQ0TZMtAnL9XGwRCTEstYSy3AwtS-RxDIgHEbKrTQL0odtUBNUQWNnKJaEMq5pTQTAcDwIgAyBPSDNpNhmUZeQgA)
