### ISSUE TITLE
[Bug] "Finished" event not fired correctly when registered after setOption and animation is disabled

### ISSUE THREAD

**Issue by alexjcook** [apache/echarts#17500]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/beautiful-bartik-njwo7p?file=/src/index.js

### Steps to Reproduce

1. Call function `chart.setOption()` with animation: false
2. Call function `chart.on("finished", callback)` to register an event callback AFTER `chart.setOption()`. In the linked example I simply console.log("finished").

### Current Behavior

With `animation: false`, and `on("finished")` registered AFTER `setOption()`, "finished" is not logged to the console. ❌ 
With `animation: true`, and `on("finished")` registered AFTER `setOption()`, "finished" is logged to the console. ✅ 
With `animation: false`, and `on("finished")` registered BEFORE `setOption()`, "finished" is logged to the console. ✅ 
With `animation: true`, and `on("finished")` registered BEFORE `setOption()`, "finished" is logged to the console. ✅ 

Interestingly, if I mouseover one of the bars, the "finished" event is triggered.

### Expected Behavior

With `animation: false`, and `on("finished")` registered AFTER `setOption()`, the event should be triggered and "finished" should be logged to the console.

Mouse events should not impact triggering of unrelated events.

### Environment

```markdown
- OS:macOS Monterey
- Browser: Safari 15.6 (17613.3.9.1.5), Chrome 104.0.5112.79
- Framework: N/A
```

### Any additional comments?

Similar to issue #14101.

**Comment by plainheart** [comment]
> With animation: false, and on("finished") registered AFTER setOption(), "finished" is not logged to the console. ❌

You need to register the event before `setOption`.

**Comment by alexjcook** [comment]
Thanks @plainheart. Can this please be made clearer in the documentation? The sample code for this event does not include a call to setOption, whereas most other events include setOption in their sample code and register callbacks AFTER setOption.

**Comment by plainheart** [comment]
Thanks for your suggestion! I think it's good to add some annotations for it.

**Comment by plainheart** [comment]
Hi, I have added some annotations for this event. Hope that helps. :)

https://echarts.apache.org/api.html#events.finished
