### ISSUE TITLE
The legend is not displayed when the type is treemap, is there any problem if it is changed to pie? Is it because treema doesn't support lengthend?

### ISSUE THREAD

**Issue by DongFang-Jun** [apache/echarts#17502]
### Version

5.3.3

### Steps to Reproduce

let option = {
                legend: {
                    bottom: "5%",
                    left: "center"
                },
                series: [
                    {
                        type: "treemap",
                        data: info,
                        left: "0%",
                        top: "0%",
                        width: "100%",
                        height: "86%",
                        label: {
                            show: true,
                            formatter: params => `${params.name} ${params.data.label}`
                        },
                        radius: ["50%", "90%"],
                        breadcrumb: { show: false },
                        roam: false
                    }
                ],
                tooltip: this.echartsTooltip
            };
            myChart.setOption(option);

### Current Behavior

不显示lagend

### Expected Behavior

显示lagend

### Environment

```markdown
- OS:macos
- Browser:Chrome 104.0.5112.79
- Framework:Vue@2
```

**Comment by jiawulin001** [comment]
Please provide a solid reproducible code, your `series.data` is an unreachable variable.
