### ISSUE TITLE
echart tree label support click event

### ISSUE THREAD

**Issue by 7chenys** [apache/echarts#17503]
### What problem does this feature solve?

echarts 4.8.0在 树形图上只能通过点击节点symbol来进行展开收起，无法实现别的动作，如果给table添加一个click event，或者不添加click event和symbol使用同一事件，通过componentType来做区分到底点了symbol还是table

### What does the proposed API look like?

myChart.on('click', function() {
  // 不同的componentType来做点击了symbol还是 table
  // 开发者可以使用这个来做很多事情
})

**Comment by 7chenys** [comment]
手抖，table应该是label

**Comment by li942475402** [comment]
maybe this document can help you:  [echartsInstance.on](https://echarts.apache.org/zh/api.html#echartsInstance.on)

**Comment by plainheart** [comment]
ECharts 5 开始 label 是支持点击事件的，如果要判断点击的是否是 label，可以按照如下代码实现

```js
myChart.on('click', e => {
  if (e.event.target.type === 'tspan') {
    console.log('clicked label')
  }
})
```
