### ISSUE TITLE
[Bug] 大屏地图运行3天左右，地图丢失，dom显示“Sorry，your browser does support WebGL”

### ISSUE THREAD

**Issue by zxn0225** [apache/echarts#17514]
### Version

exhaust 4.7.0 echarts-gl 1.1.0

### Steps to Reproduce

import * as echarts from "echarts
import “echarts-gl”
import { chinaJSON } from "./utils/chinaMap.js"
echarts.registerMap("china", chinaJSON);
   letChinaMap=echarts.init(this.$refs.ChinaMap)
ChinaMap.setOption({})

### Current Behavior

大屏运行三天左右，地图数据丢失，F12查看显示“Sorry，your browser does support WebGL”，在刷新浏览器后，地图数据又可以正常显示

### Expected Behavior

源码中看到new Renderer()或者resize()过程中抛出了异常，希望帮忙分析下什么原因

### Environment

```markdown
- OS:win10
- Browser:chrome 84.0.4147.105
- Framework:vue2
```

**Comment by plainheart** [comment]
请附加错误信息

**Comment by zxn0225** [comment]
![Uploading F8E129D6-308B-4945-91A9-EC3A1A604914.jpeg…]()

没有其他的错误信息

**Comment by zxn0225** [comment]
![Uploading 77C49445-583F-41B1-8B19-12626EA6B327.jpeg…]()

**Comment by zxn0225** [comment]
![error](https://user-images.githubusercontent.com/72496494/184587697-6cc1fdf1-3186-4874-aa79-68a4f4217f14.png)

**Comment by plainheart** [comment]
请提供控制台输出的错误信息
