### ISSUE TITLE
[当series的类型为custom时，绘制的柱状图没有itemStyle中没有borderRadius属性可配置] 

### ISSUE THREAD

**Issue by ike-yu-byte** [apache/echarts#17512]
### What problem does this feature solve?

[当series的类型为custom时，绘制的柱状图没有itemStyle中没有borderRadius属性可配置] 

### What does the proposed API look like?

[当series的类型为custom时，绘制的柱状图没有itemStyle中没有borderRadius属性可配置]

**Comment by plainheart** [comment]
可以用 `rect` shape 中的 [`r`](https://echarts.apache.org/option.html#series-custom.renderItem.return_rect.shape.r) 属性来设置圆角。

**Comment by CoderFXJ** [comment]
基本的提问方式都不对, 这样别人怎么帮你解决 ,至少配个代码/echart效果图啊

**Comment by ike-yu-byte** [comment]
`renderItem(params, api) {
            // api.value: 得到给定维度数据值
            // api.coord：将数据映射到坐标系上


            let categoryIndex = api.value(0)
            let start = api.coord([categoryIndex, api.value(1)])
            let end = api.coord([categoryIndex, api.value(2)])
            let width = api.size([0, api.value(2)])[0] * 0.8
    
            const num = api.value(4) // 每个系列柱子数
            const currentIndex = api.value(3)
            const isOdd = num % 2 === 0
            const midN = isOdd ? num / 2 : (num + 1) / 2
    
            let rect = ''
    
            // width = width / num
            width = this.barWidth ? this.barWidth : (width / num)
    
            let rectX = start[0] - width / 2
        
            const FIXED_WIDTH = 5 // 柱子间距
    
            // 数据处理，结构为 { itemStyle: { normal: { color: 'lightgreen' } }, name: '2011', value: [0, 0, 150, 2, 5] }
            // 其中value 分为五个维度，分别为{系列项}（从0开始）、y轴起始值(均为0)、实际值、同系列中索引值（从1开始）、同系列数据项总数
    
            if (num > 1) {
                if (isOdd) {
                    if (currentIndex <= midN) {
                        // 中位数左侧
                        rectX = start[0] - width / 2 - width / 2 + (currentIndex - midN) * width - FIXED_WIDTH * (midN + 1 - currentIndex)
                    } else {
                        // 中位数右侧
                        rectX = start[0] - width / 2 + width / 2 + (currentIndex - midN - 1) * width + FIXED_WIDTH * (currentIndex - midN)
                    }
                } else {
                    rectX = start[0] - width / 2 + (currentIndex - midN) * (width + FIXED_WIDTH)
                }
            }
    
            rect = {
                type: 'rect',
                transition: ['shape'],
                shape: echarts.graphic.clipRectByRect(
                    { x: rectX, y: end[1], width: width, height: start[1] - end[1] },
                    {
                        x: params.coordSys.x,
                        y: params.coordSys.y,
                        width: params.coordSys.width,
                        height: params.coordSys.height
                    }
                ),
                style: api.style()
            }
            return rect
        }

**Comment by ike-yu-byte** [comment]
> 设置

不行啊
