### ISSUE TITLE
[Bug] interval on time axes seems to be ignored

### ISSUE THREAD

**Issue by ob-ARC** [apache/echarts#17519]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-time-axis&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgCYAGEkgGggEYbaBKAbgChRIB7TfAT2QgkALBABUEAMwA2MmTF1ZZNhwjcQAWQCW6ATPm1Fy8KswAJTgFcATgOmz9h9sYAmBGAIDaH2AhrqCABYAdFYw6M6cALZEjPISsgC6CWwAZpw2RCqaArTMENkAPIIAHMVK-aiosQDerBAQKuicOCiYOPiEREQ-iKgoalrojCx1EK5gMEEADhZwAUQeGM1-gSGW4V3-YMGh4VExEAC0EGRBAKyx4uRoY24e2ce0CR5PjAkjAL6snFNgmtwCWr1MCcTjAP5TABcECB9QgYCsmgA5kiQFZoQByGAAD00cAxVFG9SmnDgmj-3GhKQs6AAxhSdERfjUiXCrOBrDoPL8PGQEjQMQYAKQY5Ksr71D6E4Hk0DQ2H1UApMCY2kgdCEKwE1mEbEqiAYv6RRA4vH5DVogBuMGAEAQYD-6CRcDGnAgTUgWHSAGsIJCiBjRlLRiCwVBONj5ayUiACNYQFG4XDxjAAFqgyKJpNw3gAQVxcAAkuEQJGDU1MIHsxBg9X2XAQez5bXs3AYJaQLmi5EYKjm-Kg9KINj83is8DeFMEwajSBtUnwzTXFZeABxGBQiApG2-VkAej3kW0xc11uA0LU5msQ_qB572JPVpt0KEokvlisrO0p-fEFf7-sQdRjzAtx3hSdpwxM8LDnG9oHWZc1w3aFeQFAwyBFfl90PY8LSsM9oTOMg4LvHFH3w38iLg78n3PCAiKA-oU3TKIUNZBU4TACDMW0MlnFg1l6gbGArH1YjBIgdVnGhdDxTgjihImUToXE6spOhcgB3qLChLRTQQDgNikwU90YGNTEADEYG9RAOhgedsy4qdMWAbQBOrOBIlBbZoQRGC4KE3hInDOiMQrdzsxE2MAGUuLlGEWyTFNoRTLSIASVgPmYIA

### Steps to Reproduce

See reproduction link

### Current Behavior

on "time" axes, the interval setting seems to be ignored completely. On "value" axes, however, it works.

### Expected Behavior

interval settings on "time" axes should be applied as for "value" axes.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Time axes may use different intervals becase the number of days in different months. So interval no longer works for time axes. The document should be updated. You can try the [Cascading Templates of the formatter](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter).

**Comment by ob-ARC** [comment]
I do not understand how cascading formatter templates can help me with this. If I want a fixed interval of let's say 3 hours on my time x-Axis, what does this have to do with the label formatting?

**Comment by Ovilia** [comment]
Cascading formatter can help to make minute/second/millisecond formatters to be `''`. But no, it cannot help to make the interval to be 3 hours.
