### ISSUE TITLE
treemap zoom limitation

### ISSUE THREAD

**Issue by mousavi71** [apache/echarts#17511]
### Version

5.3.2

### Steps to Reproduce

https://echarts.apache.org/examples/en/editor.html?c=treemap-disk
open this example and zoom out until nothing to show remains.

### Current Behavior

hello and thank you for this magnificent library.
I am unsure if this is a bug or requesting a new feature.
 the problem is that zooming in treemap doesn't have any limitation, so if a user zooms out too much, the chart becomes so tiny that it becomes the size of a point and finally will disappear, so the user should reopen the page to see the chart again.

### Expected Behavior

I think we need configs to define the min and max valid zoom range and prevent zooming out more.

### Environment

```markdown
- OS: Ubuntu
- Browser: chrome 99
- Framework: react
```

**Comment by kerorojason** [comment]
Similar issue: https://github.com/apache/echarts/issues/14599
