### ISSUE TITLE
[Bug] can't diaplay only first and last label by formatter when label is too long

### ISSUE THREAD

**Issue by li942475402** [apache/echarts#17523]
### Version

5.3.3

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=area-simple&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOANgA4AaCMugZgEoBuAKFEgHtN8BPZBABMAFggAqCIwoAGWZIgl5sjlwgATAohQBtALprwmgjCG6AsgQAWAOgBOMdBu4BbIs0WN5h9gHo_EQUAB24AS3QwOHYAM257CCJ1MKESVggUgB4RNIzUVE8Ab3YICAA3GAT0bhwUTBx8QiIiWAQ0FF4QAWY2EpNCW2CAVzhrIl1qrFsAc3AAMSHgYABNEEqPOkmZ8AteMDHPVCVNmu2wRuJmfVsAK3D0IgByP0eejlKtMBhBkbGrfYc3CGzma_zsjmcbg8EAAtBBZLYAKyeKTCBRHT4wXQpOEkfRvdgAX3Y3GCYDCvCExVKYG43GA5OCAC4INTShAwPYwtNZvYWY8YAAPMJwR40PqlUJwMLk3gsmLAgDGsvQiTJRQl7Ps4CG9lVujJulk-joj2UAFJHr52RBiaVCeKaTLQCy2aVQDEwPzFSBIiB7GLNYRBV6II8ADKVWYQACC2rMAGFrJUwI8-g6-rT6VBuILXZqYmswLqQPmbR9TAAtOmuMvl0r8GPCuAASWcIDzYeqmDT9Yz9e1cFp2td_fLcBgZRAMdbrhgs1HmrttsdEEFTZFdZp_GCpbDiu003i_EDNpzwK09n4AHEYMyIDEYMAEKuK18WZ8QK-IEKRZGoCAwBbuycT2HOYCEHyiQVMAQxfhk7aCp4SAAHyspqNrasWeoQEadDkNcESKrBGggHARARKRSEQAA_OUT5wRA_KPO85bLva6aro2zbAWAO57o8MFwae7Lns4lQ3neLJ4WGyiyJa-icX0CBcmR0mam67LoDArgCXMMAANaII0MAiTafG7vywARCAZnsnA_CuDmQFdp0dmlBOrjBNZ6DTFZEFQO5GSEK4ADKfEuuh9alIq9LxPy9jTFARDCIiiJ0AA7LI-GMCQzC9mx36lJUazhfwkWaTasXAPFED1BAICKsm9hRDMjjBNYYSKrY4Y2ZU16OBoYS-mARDZfCdDjSQdC6Bh5aVdF3AxDECChtlc31tVtWPIlyWpelSiIrQEDUPlG3smO0VRVd7JLSt4AstN51VXFUE7UlKVpZlU25WdN22ud-JzZd7KYh-phLn0imEqwQA

### Current Behavior

the last label is not displayed

### Expected Behavior

the last label is display

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by li942475402** [comment]
the example is  based on official, just need focus `xAxis.axisLabel.formatter`

**Comment by li942475402** [comment]
when label is short, it's useful
[官方示例](https://echarts.apache.org/examples/zh/editor.html?c=area-simple&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOANgA4AaCMugZgEoBuAKFEgHtN8BPZBABMAFggAqCIwoAGWZIgl5sjlwgATAohQBtALprwmgjCG6AsgQAWAOgBOMdBu4BbIs0WN5h9gHo_EQUAB24AS3QwOHYAM257CCJ1MKESVggUgB4RNIzUVE8Ab3YICAA3GAT0bhwUTBx8QiIiWAQ0FF4QAWY2EpNCW2CAVzhrIl1qrFsAc3AAMSHgYABNEEqPOkmZ8AteMDHPVCVNmu2wRuJmfVsAK3D0IgByP0eejlKtMBhBkbGrfYc3CGzma_zsjmcbg8EAAtBBZLYAKyeKTCBRHT4wXQpOEkfRvdgAX3Y3GCYDCvCExVKYG43GA5OCAC4INTShAwPYwtNZvYWY8YAAPMJwR40PqlUJwMLk3gsmLAgDGsvQiTJRQl7Ps4CG9lVujJulk-joj2UAFJHr52RBiaVCeKaTLQCy2aVQDEwPzFSBIiB7GLNYRBV6II8ADKVWYQACC2rMAGFrJUwI8-g6-rT6VBuILXZqYmswLqQPmbR9TAAtOmuMvl0r8GPCuAASWcIDzYeqmDT9Yz9e1cFp2td_fLcBgZRAMdbrhgs1HmrttsdEEFTZFdZp_GCpbDiu003i_EDNpzwK09n4AHEYMyIDEYMAEKuK18WZ8QK-IEKRZGoCAwBbuycT2HOYCEHyiQVMAQxfhk7aCp4SAAHyspqNrasWeoQEadDkNcESKrBGggHARARKRSEQAA_GGJDCIwjwQPyjzvOWy72umq6Ns2wFgDue6PDBcGnuy57OJUN53iyeH0fIlr6NxfQIFyZGyZqbrsugMCuEJcwwAA1ogjQwGJNoCbu_LABEIDmeycD8K4OZAV2nT2aUE6uMENnoNM1kQVAHkZIQrgAMoCS66H1qUir0vE_L2NMUBEMIiKInQADssj4YwJDML2HHfqUlRrBF_BRVpNpxcACUQPUEAgIqyb2FEMyOME1hhIqtjhrZlTXo4GhhL6YBEDl8J0BNJB0LoGHllVMXcDEMQIKGOXzfWNV1Y8SUpWlGVKIitAQNQBWbeyY4xdF13sstq3gCyM0XdV8VQbtyWpelWXTXl523baF34vNV3spiH6mEufRKYSrBAA)

**Comment by plainheart** [comment]
Not sure if this is a bug. But you can set [`showMaxLabel`](https://echarts.apache.org/option.html#xAxis.axisLabel.showMaxLabel) as `true` to keep the last label visible.

**Comment by li942475402** [comment]
got it, thanks
