### ISSUE TITLE
[Bug] Component XXX is used but not imported.

### ISSUE THREAD

**Issue by danvc** [apache/echarts#17520]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/s/agitated-chihiro-m2wgz7

### Steps to Reproduce

When we try to add dynamically the property legend.type with the value Scroll or Plain, we get an exception saying : 'Component legend.plan is used but not imported.'

### Current Behavior

Getting exception when setting the property into an existing/available/visible chart.

### Expected Behavior

Allow to set the legend.type property without any exception

### Environment

```markdown
- OS: MacOS
- Browser: Firefox 103.0.2 
- Framework: React 17.0.2
```

**Comment by plainheart** [comment]
The legend component doesn't have a type called `plan`. It should be `plain`.
