### ISSUE TITLE
[Bug] xAxis.type="time"，时间类目时导致x轴显示不正确

### ISSUE THREAD

**Issue by felixfjing** [apache/echarts#17527]
### Version

4.9.0

### Link to Minimal Reproduction

https://codesandbox.io/s/winter-bash-uoq09i

### Steps to Reproduce

~

### Current Behavior

![image](https://user-images.githubusercontent.com/19278667/184867845-806bece7-1688-4005-9299-39779655d709.png)

如图所示

1、x轴显示年被换行。
2、tooltip显示的日期年被置于最后。

谢谢~~

### Expected Behavior

x轴正确显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
可以通过 formatter 设置坐标轴和 tooltip 的文字的，并且你这个例子用的是 4.x 版本，如果实在不行可以升级到 5.x
