### ISSUE TITLE
[Feature] Cross-linking lines between branches on tree graph

### ISSUE THREAD

**Issue by reregaga** [apache/echarts#17536]
### What problem does this feature solve?

Thanks for the great library, it helped me a lot in visualizing the data.  
Now I am working on creating a mind map and trying to find how to create cross-links between branches in the [tree graph](https://echarts.apache.org/examples/en/editor.html?c=tree-legend) and I can't figure out how to do it. It's possible?  
For example, I marked the desired lines in red.
![test](https://user-images.githubusercontent.com/76629445/185757016-ac8046f8-bb4d-444c-944c-c3bf1ec6791b.jpg)

Maybe I'd better use a [simple graph](https://echarts.apache.org/examples/en/editor.html?c=graph-simple) to create custom edges? But I like how the nodes are automatically aligned vertically in the tree graph, and for a simple graph they will have to be aligned manually?

### What does the proposed API look like?

As you wish.

**Comment by Ovilia** [comment]
By definition, this is no longer a *tree* so I'm afraid it's not possible to make this. You can consider using [graph](https://echarts.apache.org/examples/en/index.html#chart-type-graph) series. With [layout: 'none'](https://echarts.apache.org/zh/option.html#series-graph.layout), you can mannually provide the position of each node.
