### ISSUE TITLE
[Bug] 使用saveAsImage保存图片时点击保存图标后图标消失，需要等图片下载完成后图标才出现

### ISSUE THREAD

**Issue by xmdong** [apache/echarts#17530]
### Version

5.3.0

### Steps to Reproduce

似乎原生提供的toolbox都是这样的效果

### Current Behavior

点击下载图标，随后图标消失

### Expected Behavior

能不能让图标一直显示

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:react
```

**Comment by plainheart** [comment]
是为了不避免把 toolbox 图标保存到图片中，文档也提到了这一点。
https://echarts.apache.org/option.html#toolbox.feature.saveAsImage.excludeComponents

**Comment by xmdong** [comment]
> 是为了不避免把 toolbox 图标保存到图片中，文档也提到了这一点。 https://echarts.apache.org/option.html#toolbox.feature.saveAsImage.excludeComponents

谢谢解答，我试了一下确实是这样的，把excludeComponents设置成空数组就不会消失了。但我还是有个问题，就是可以让echarts在执行保存操作的时候再隐藏图标吗，而不是像下图这样还在我设置保存路径的时候就已经把图标隐藏掉了
![image](https://user-images.githubusercontent.com/24405108/185549147-2440bf74-cdee-4980-8df3-35010786c2b8.png)

**Comment by plainheart** [comment]
应该不行，下载文件弹出保存路径选择框的逻辑是浏览器原生的操作。
