### ISSUE TITLE
[Bug] Stacked Line's y-axis displays incorrect values

### ISSUE THREAD

**Issue by A-Normal-User** [apache/echarts#17532]
### Version

All version

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack&version=5.3.2

### Steps to Reproduce

- In the Demo of "[Stacked Line](https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.3.3 "Stacked Line")", We can find that the value displayed by the panel is different from the value of the y-axis. Like this one
![屏幕截图 2022-08-19 154308](https://user-images.githubusercontent.com/70429554/185569856-894530cb-c5a5-4215-9289-98d1957b7a4d.png)
:

### Current Behavior

- In the Demo of "[Stacked Line](https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.3.3 "Stacked Line")", We can find that the value displayed by the panel is different from the value of the y-axis. Like this one
![屏幕截图 2022-08-19 154308](https://user-images.githubusercontent.com/70429554/185569856-894530cb-c5a5-4215-9289-98d1957b7a4d.png)
:

### Expected Behavior

- I want the values of the data to correspond to the values of the y-axis.

### Environment

```markdown
- OS: Windows11 21H2
- Browser:edge 104.0.1293.54
- Framework: Unused
```

**Comment by plainheart** [comment]
It's not a bug. Please notice that this is a **_stacked_** line chart. The value shown in the tooltip is the real value of each point but the value in the y-axis is cumulative at each point.

**Comment by A-Normal-User** [comment]
Oh, yes. It's my problem.

**Comment by cesnietor** [comment]
@A-Normal-User  how did you solve it? I'm thinking either not doing stack at all and explaining the points that overlap in a separate detailed component or just hide the Y-axis values.
