### ISSUE TITLE
line3D 动态添加数据坐标轴会闪动且会卡顿

### ISSUE THREAD

**Issue by jingyuLin1999** [apache/echarts#17534]
### Version

^5.3.3

### Steps to Reproduce

1、[用官方例子](https://echarts.apache.org/examples/zh/editor.html?c=line3d-orthographic&gl=1)
2、动态添加数据
```js
setInterval(() => {
  this.options.series[0].data.push([Math.random()*11.3,Math.random()*10.3, Math.random()*15.3])
  this.chart.setOption(this.options, true);
}, 10);
```

### Current Behavior

x,y,z坐标轴会闪动

### Expected Behavior
原因好像是整个图表重绘了，高频率增加新的点，会导致阻塞。

希望line3d能支持类似于[appendData](https://echarts.apache.org/zh/api.html#echartsInstance.appendData)，历史数据不再重绘，仅重绘新增的数据。而不是通过 this.chart.setOption(this.options, true);整个重绘，大大降低了绘制效率。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
True - the axes will flicker. And true - [appendData](https://echarts.apache.org/en/api.html#echartsInstance.appendData) is not officially supported for _line3D_.
But one can somewhat remedy the problem.
&nbsp;  &nbsp;   First - by not explicitly redraw the chart with ```setOption(option, true);``` - **true** means redraw/replace.
&nbsp;  &nbsp;     Second - by setting **max** values to axes
&nbsp;  &nbsp;     Third - by decreasing the frequency
&nbsp;  &nbsp;     (Fourth - upgrade computer to faster one)
Update [the example](https://echarts.apache.org/examples/en/editor.html?c=line3d-orthographic&gl=1) with following code
```
  xAxis3D: {    type: 'value', max:12  },
  yAxis3D: {    type: 'value', max:12  },
  zAxis3D: {    type: 'value', max:30  },

setInterval(() => {
  option.series[0].data.push([Math.random()*11.3,Math.random()*10.3, Math.random()*15.3])
  myChart.setOption(option);  //, true);
}, 800);
```
and flicker will disappear when tested on Intel i5 processor.
