### ISSUE TITLE
当鼠标滑过折线图后报错Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by 1006569910** [apache/echarts#17531]
### Version

5.3.3

### Steps to Reproduce

var y = [30,2,60,300,188,168,68]
        var x = ['2020-11','2021-1','2021-3','2021-3','2021-3','2021-3','2021-3'];
        this.registeredChart = echarts.init(
          document.getElementById("registered")
        );
        var options = {
          grid: {
            top: "10%",
            left: "7.5%",
            right: "1%",
            bottom: "12%",
          },
          tooltip: {
            trigger: "axis",
          },
          xAxis: {
            type: "category",
            data: x,
            axisLabel: {
              textStyle: {
                color: "#3FDDFF",
              },
            },
            show:false, // 不显示坐标轴线、坐标轴刻度线和坐标轴上的文字
          },
          yAxis: {
            type: "value",
            splitLine: {
              how: true,
              lineStyle:{
                color: ['#2d2e4850'],
                width: 1,
                type: 'solid'
              }
            },
            axisLabel: {
              textStyle: {
                color: "#3FDDFF",
              },
            },
            show:false, // 不显示坐标轴线、坐标轴刻度线和坐标轴上的文字
          },
          series: [
            {
              data: y,
              type: "line",
              symbol: "none",
              smooth: true,
              itemStyle: {
                normal: {
                  lineStyle: {
                    color: "#80DEFF",
                  },
                },
              },
              areaStyle: {
                color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                  {
                    offset: 0,
                    color: "rgb(128, 222, 255, 1)",
                  },
                  {
                    offset: 1,
                    color: "rgb(128, 222, 255, 0.3)",
                  },
                ]),
              },
            },
          ],
        };
        this.registeredChart.setOption(options);

### Current Behavior

当鼠标滑过折线图后报错Uncaught TypeError: Cannot read properties of undefined (reading 'length')，报错文件Animator.js，函数为interpolate1DArray，并且报错一直循环累加

### Expected Behavior

希望找出BUG原因

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
`rgb(128, 222, 255, 1)` -> `rgba(128, 222, 255, 1)`
`rgb(128, 222, 255, 0.3)` -> `rgba(128, 222, 255, 0.3)`
