### ISSUE TITLE
[Bug] Remove tooltip from 3d Bar when we remove focus from the chart

### ISSUE THREAD

**Issue by salahBouragba** [apache/echarts#17533]
### Version

14.0.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1

### Steps to Reproduce

1. Focus on an element of the 3d Bar chart
2. Verify that we show the tooltip
3. Remove focus from the chart
4. The tooltip doesn't disappear

### Current Behavior

The tooltip stays in the chart 

### Expected Behavior

The tooltip should disappear like in the other charts (ex: https://echarts.apache.org/examples/en/editor.html?c=bar-simple)

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 104.0.5112.82, Edge 104.0.1293.54, Firefox 103.0.2
- Framework: Angular 14
```

**Comment by helgasoft** [comment]
+1
Also, the example tooltip code needs to be fixed:
```
          encode: {
            x: 'Year',
            y: 'Country',
            z: 'Life Expectancy',
            //tooltip: [0, 1, 2, 3, 4] = incorrect display
          },
          tooltip: [0, 1, 2, 3, 4]
```

**Comment by helgasoft** [comment]
Still not fixed as of Oct 2024. 
There is a JS error _TypeError: Cannot read properties of undefined (reading 'toFixed')_ coming from [Grid3DView #L184](https://github.com/ecomfe/echarts-gl/blob/031da0ece1c0c7aeef1bd9a7d83672b1e9ac3b40/src/component/grid3D/Grid3DView.js#L184) calling [core/echarts.ts](https://github.com/apache/echarts/blob/b33058ecd373f4a62d2fe6e7ac96e17db4e33e8e/src/core/echarts.ts#L1951C57-L1951C63)
There is also a [related issue](https://github.com/ecomfe/echarts-gl/issues/538) with **legend** coming from this same error.
