### ISSUE TITLE
[Bug] 5.3.3部分配置项默认值同文档不一致

### ISSUE THREAD

**Issue by mousne** [apache/echarts#17542]
### Version

5.3.3

### Steps to Reproduce

1. npm
2. echarts.init(dom, "macarons")

### Current Behavior

1. 4.9.0升级至5.3.3
2. 引入macarons主题
3. 通过getOption对比4.9.0和5.3.3的tooltip配置参数
4. 未手动配置的参数项 4.9.0中最终配置同文档相同，5.3.3同文档不同
例如option.tooltip.borderWidth
在4.9.0中最终为0，5.3.3中最终为1
5. macarons主题在4.9.0和5.3.3中tooltip的样式表现不一致

### Expected Behavior

option.tooltip选项默认值同文档一致
需要确认下升级V5的时候是否有调整过默认值
目前发现的不一致主要同样式相关
所以是否有和其他主题样式有进行merge
如果确认是默认值更改的话
想提个PR更改下macarons主题的option.tooltip.bordrWidth和option.tooltip.textStyle.color
保持和4.9.0展示一致

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
欢迎提 PR，现在的主题在 https://github.com/apache/echarts/blob/master/theme/macarons.js 可以对比下 [4.x 版本](https://github.com/apache/echarts/commit/728ae6394632fa9735402b06647a82d170caeede#diff-bc5445057729c8e5c43bac20e4b1835d6ce4d97c43536a2a3fe3a2b9cd0d92d6)的
