### ISSUE TITLE
[Bug] series数据项过多问题

### ISSUE THREAD

**Issue by 7rainbows** [apache/echarts#17541]
### Version

5.3.2

### Steps to Reproduce

series这个数组可能长度有30~40但是我此时的横坐标只有一个，我该怎样左右滑动来展示我的柱状图呢

### Current Behavior

我只有一个横坐标 但对应的纵坐标特别的多，也就是series数组特别的大，这时每个柱状图特别的窄，怎么能做到像多个横坐标那样可以设置dataZoom来左右滑动呢？

### Expected Behavior

期望我上边的问题可以左右滑动来展示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
这个理论上是不可以的，但或许可以尝试用多个横坐标 hack
