### ISSUE TITLE
[Bug] 多个堆叠图导致datazoom 的趋势只是第一个图的趋势

### ISSUE THREAD

**Issue by Chasen-Zhang** [apache/echarts#17547]
### Version

5.3.2

### Steps to Reproduce

bar 的堆叠图，多个堆叠图导致datazoom 的趋势preview只是第一个图的
![image](https://user-images.githubusercontent.com/15354455/185933109-648e711b-eb1a-4e0f-b752-d99626d64d15.png)

### Current Behavior

这个趋势不是总的趋势

### Expected Behavior

展示总的趋势

### Environment

```markdown
- OS:mac
- Browser:chrome latest
- Framework:react
```

**Comment by Chasen-Zhang** [comment]
#15121

**Comment by Chasen-Zhang** [comment]
@Ovilia help

**Comment by Chasen-Zhang** [comment]
stackStrategy: 'all',

**Comment by Ovilia** [comment]
`stackStrategy: 'all'` doesn't seem to be related. Let's see if we could fix this with #17143
