### ISSUE TITLE
[Bug] AxisLabel formatter seem to be ignored on showMinLabel and showMaxLabel

### ISSUE THREAD

**Issue by IrfanNazand** [apache/echarts#17546]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/area-pieces-forked-22nur1

### Steps to Reproduce

Follow the link above, try zooming in and out and focus on min and max labels. 

### Current Behavior

Labels for showMinLabel and showMaxLabel does not follow the styling given to axisLabel's through formatting.

![image](https://user-images.githubusercontent.com/22817338/185903053-25339fb5-4c02-4806-8779-a248bad3654b.png)

It should show hour and minute values for minLabel and maxLabel in the same format as the other values in the x-axis.

### Expected Behavior

Labels for showMinLabel and showMaxLabel should follow the styling given to axisLabel's through formatting.

**Comment by andyboyne** [comment]
The problem seems to be chrome's anti-aliasing when you have non-white colours on a dark background.  For example, I took one of the 'example' charts from the side and modified it like so:

`
option = {
  title: {
    text: 'Stacked Area Chart'
  },
  tooltip: {
    backgroundColor: 'black',
    textStyle: {
      color: 'orange',
      fontSize: 11
    },
    trigger: 'axis',
    axisPointer: {
      type: 'cross',
      label: {
        backgroundColor: '#6a7985'
      }
    }
  },
  legend: {
    data: ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine']
  },
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: [
    {
      type: 'category',
      boundaryGap: false,
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    }
  ],
  yAxis: [
    {
      type: 'value'
    }
  ],
  series: [
    {
      name: 'Email',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [120, 132, 101, 134, 90, 230, 210]
    },
    {
      name: 'Union Ads',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [220, 182, 191, 234, 290, 330, 310]
    },
    {
      name: 'Video Ads',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [150, 232, 201, 154, 190, 330, 410]
    },
    {
      name: 'Direct',
      type: 'line',
      stack: 'Total',
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [320, 332, 301, 334, 390, 330, 320]
    },
    {
      name: 'Search Engine',
      type: 'line',
      stack: 'Total',
      label: {
        show: true,
        position: 'top'
      },
      areaStyle: {},
      emphasis: {
        focus: 'series'
      },
      data: [820, 932, 901, 934, 1290, 1330, 1320]
    }
  ]
};`


... copy that into the online 'examples' editor.

If you move the mouse around and then stop, you will notice that quite often the text is blurred. Not always, but quite often.
