### ISSUE TITLE
getModel support for radar chart indicator labels and axisLabel  

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17555]
### What problem does this feature solve?

currently myChart.getModel().getComponent('indicators'); for indicators and axis labels in the case of radar chart is not working 

### What does the proposed API look like?

expectation is it should work for indicator labels and axisLabels for radar chart

**Comment by Ovilia** [comment]
`getModel` is not a documented public method so it's not advised to be used. If you wish to get the option, you should probably keep the option variable or use `chart.getOption()` to get the merged option.

**Comment by RahulVishK** [comment]
hi my requirement is to draw graphics for indicator labels ? is there any way ??

**Comment by Ovilia** [comment]
Yes. Can you be more specific about what you want? You can use [graphic](https://echarts.apache.org/en/option.html#graphic) to draw.

**Comment by RahulVishK** [comment]
hi we have a requirement to use getModel of indicator labels and axis labels , is there any way to get the info ?
