### ISSUE TITLE
[Bug] 数据不对

### ISSUE THREAD

**Issue by gsssssssssssssssssss** [apache/echarts#17553]
### Version

5.3.3

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=line-stack&version=5.3.3
打开example，折线图堆叠
![image](https://user-images.githubusercontent.com/19550746/186091725-a66e4e24-0f1a-45cd-8149-2578706455d4.png)
Union Ads的值是310，但是位置却在500之上

### Current Behavior

Union Ads的值是310，但是位置却在500之上

### Expected Behavior

y轴数据正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by wzc11227** [comment]
你不知道什么是堆叠图吗
