### ISSUE TITLE
[Bug] `label.show = false`, but `label` appears when hover

### ISSUE THREAD

**Issue by wenhai974** [apache/echarts#17554]
### Version

5.3.3

### Link to Minimal Reproduction

[https://codepen.io/littleKoi/pen/jOzJRPK](https://codepen.io/littleKoi/pen/jOzJRPK)

### Steps to Reproduce

1. When initializing, set `label.show = true` and `labelLayout.hideOverlap = true`; this time it behaves normally.

2 Then I use `echartsInstance.setOption` to modify `label.show = false`.

3. and move cursor to hover `series`,  the `label` appears.

I think when `label.show` is false，the `label` should not appear at any time.

### Current Behavior

The `label.show` is false，but `label` appears when hover

### Expected Behavior

I think when `label.show` is false，the `label` should not appear at any time.
<img width="729" alt="image" src="https://user-images.githubusercontent.com/21982910/186136122-c5283399-fc69-489e-8542-092bd517a1e8.png">

### Environment

```markdown
- OS:macOS
- Browser:5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
- Framework:Vue
```

**Comment by wenhai974** [comment]
Here is the link

[bugs demo](https://codepen.io/littleKoi/pen/jOzJRPK)

**Comment by wenhai974** [comment]
The problem should be that `labelLayout.hideOverlap = true` is used for the first time, causing problems with the second setOptions

**Comment by praful-hunde** [comment]
[does this demo help ](https://codepen.io/praful-hunde/pen/dyezOOJ)

 emphasis: {
      disabled: true
    },
