### ISSUE TITLE
[Bug] 中国 南海诸岛 边界九段线问题

### ISSUE THREAD

**Issue by Alessandro-Pang** [apache/echarts#17550]
### Version

5.2.2

### Steps to Reproduce

现在各大地图厂商（百度地图、高德地图）已加入的第十段线，
但是在 echarts 中注册全国地图，南海诸岛只有 9段，是否可以加入第十段线，或者有什么折中方案绘制第十段线？

### Current Behavior

当前 南海诸岛 只显示边界九段线

![image](https://user-images.githubusercontent.com/42641570/186059388-25f7402a-28a7-4f8d-9836-b2d389dc3200.png)

### Expected Behavior

南海诸岛 缩略图显示边界十段线

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
我们已经不再提供地图文件下载，建议使用百度地图、高德地图作为标准底图或从二者提供的数据 API 获取标准边界数据来绘制地图。

**Comment by Alessandro-Pang** [comment]
> 关于地图我是知道的，但是南海诸岛的缩略图是在 echarts 源码中注册的。

源码位置：` \echarts\src\coord\geo\fix\nanhai.ts`

![image](https://user-images.githubusercontent.com/42641570/186059192-10f572c4-6a21-4f1d-8d81-48b8d8c2854f.png)

**Comment by plainheart** [comment]
哦 这个是为了防止用户用了中国地图，但未绘制南海诸岛的情况自动添加的较为粗略的南海诸岛边界。建议使用更标准的地图数据自行绘制。

**Comment by Alessandro-Pang** [comment]
> 哦 这个是为了防止用户用了中国地图，但未绘制南海诸岛的情况自动添加的较为粗略的南海诸岛边界。建议使用更标准的地图数据自行绘制。

明白了，不过现在好像没有专门支持绘制 南海诸岛+边界线缩略图 这块的地图数据吧，像高德的地图数据也只是绘制完整的地图。

**Comment by plainheart** [comment]
似乎是的，如果允许可以直接绘制全图，不用再在右下角额外绘制南海诸岛。

**Comment by zym0110** [comment]
楼主，请问一下，您是怎么解决的呢，万分感谢，期待您的回复
