### ISSUE TITLE
[Feature] set some nodes above others in a force graph

### ISSUE THREAD

**Issue by weihaopeng** [apache/echarts#17565]
### What problem does this feature solve?

I want to set red nodes above the blue nodes, like `z-index` in css. Any idea?

![image](https://user-images.githubusercontent.com/33681454/186382732-033c6f2c-9021-4f80-be2f-7618b8cd6707.png)

### What does the proposed API look like?

Maybe a `riseNodes` API? Or just set `level` attr in datas?

**Comment by Ovilia** [comment]
I can't think a way to do that. Usually you can use an extra series with a bigger `z` to do this, but the force graph doesn't work this this plan.

**Comment by weihaopeng** [comment]
😿  Can it be a new feature? Because in a force graph with more than 1k nodes, lines are often covered.

**Comment by Ovilia** [comment]
I think this order is defined by their order in `data`. Can you try to put the nodes you wish to emphasize to be at the end of the data? Also try with the front if it doesn't work.

**Comment by weihaopeng** [comment]
It's not just a problem with dots, lines also have coverage problems. And I can't put the point I want to emphasis at the end. Putting it at the end means that when I want to do the emphasis, the data has to reset once. Re-rendering for one change is too expensive.

**Comment by Ovilia** [comment]
I don't believe this is possible. You may hover on a node and its connected neighbors will be at the top. But no, you cannot set zlevel or doing anything I can think of to make them always on top.
