### ISSUE TITLE
[Feature] 象形柱图可以增加类似柱形图堆叠的功能吗？

### ISSUE THREAD

**Issue by xiaoyao-xiaolv** [apache/echarts#17567]
### What problem does this feature solve?

象形柱图能不能增加类似下面连接的堆叠柱形图配置效果呢？
https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack

### What does the proposed API look like?

https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack

**Comment by Ovilia** [comment]
目前不支持，如果有需要的话欢迎提 PR 。[这里](https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment) 是教程
