### ISSUE TITLE
hope SilderDataZoom support custom cursor

### ISSUE THREAD

**Issue by akiozhang** [apache/echarts#17571]
### What problem does this feature solve?

url path:  https://github.com/apache/echarts/blob/master/src/component/dataZoom/SliderZoomView.ts
![image](https://user-images.githubusercontent.com/29578199/186567847-dab8713b-59e4-4e99-88ef-e7c55cf6d9c5.png)
return result can support custom cursor, hope cursor can set pointer type

### What does the proposed API look like?

url path:  https://github.com/apache/echarts/blob/master/src/component/dataZoom/SliderZoomView.ts

function getCursor(orient) {
  return orient === 'vertical' ? 'ns-resize' : 'ew-resize';
}

**Comment by Ovilia** [comment]
I think we can provide a new option like [series.cursor](https://echarts.apache.org/en/option.html#series-bar.cursor). Would you please make a pull request?

**Comment by akiozhang** [comment]
> I think we can provide a new option like [series.cursor](https://echarts.apache.org/en/option.html#series-bar.cursor). Would you please make a pull request?
I think the option like datazoom.brushStyle.cursor

**Comment by Ovilia** [comment]
@akiozhang If it's the cursor when hovering on the brush area, then yes, it should be datazoom.brushStyle.cursor. Please check [the wiki](https://github.com/apache/echarts/wiki) to learn how to debug and make a pull request. Thanks!
