### ISSUE TITLE
getOption接口支持返回不合并默认值

### ISSUE THREAD

**Issue by ljianc** [apache/echarts#17583]
### What problem does this feature solve?

我想将option保存到数据库，现在的getOption接口返回的是一大坨，非常占用存储空间。

### What does the proposed API look like?

能否支持只返回不合并默认值的option，或者只返回用户设置过的option，而不是所有属性都返回

**Comment by Ovilia** [comment]
在 ECharts 内部并不会保留一份所有用户 setOption 传入的 option 的 merge 后的对象，而是每次 setOption 后将用户传入的 option 和图表默认值的 option 合并。如果有这个需求的话，建议传入 setOption 之前自己记录一下这个 option 并合并一下。

**Comment by ljianc** [comment]
主要是我自己本地写一套merge规则，如果和echarts内部的merge规则不一致，就会导致一些问题。是否有更好的方法

**Comment by Ovilia** [comment]
是可能会不一样，因为上面解释了，ECharts 是每次调用 setOption 的时候，传入的 option 和 ECharts 默认 option merge。如果你把每次 setOption 传入的 option 相互 merge 再传入，那么的确可能不同。所以要准确的话还是通过 getOption 去获取。具体还是看你需要怎么使用这个 option。
