### ISSUE TITLE
[Feature] Example of color separation by category with encode

### ISSUE THREAD

**Issue by Gusis93** [apache/echarts#17589]
### What problem does this feature solve?

Coming from vega-lite, I'm trying to render a bar chart that splits the bars by category. Currently I find myself having to transform my data in order to send it to the chart series. 

Playing with the axis encode I sort of get the result I'm looking for: https://codesandbox.io/s/funny-shadow-hbsjsm?file=/src/App.tsx if you hover over the bars you will see its actually rendering the proper values and bar sizes split by categories but all with the same color and no separation.

Is this kind of behavior not supported yet?

### What does the proposed API look like?

```
   series: {
            type: "bar",
            showBackground: true,
            dataGroupId: "source_dtg",
            seriesLayoutBy: "column",
            colorBy: "data", => support coloring by a field 
            splitBy: "categories" => new option to split by a category
            encode: {
              tooltip: ["categories", "source_dtg", "count"],
              // Map the "date" column to X axis.
              x: "source_dtg",
              // Map the "count" column to Y axis
              y: "count",
            }
          }
```

**Comment by Ovilia** [comment]
Do you mean you want to use ECharts to get this?

<img width="229" alt="image" src="https://user-images.githubusercontent.com/779050/187373406-62071c6c-1399-45aa-8345-8675b265d18e.png">

Set [barGap](https://echarts.apache.org/en/option.html#series-bar.barGap) to be 0 should work.

**Comment by Gusis93** [comment]
Yes, I want to achieve this result. According to the docs `barGap` affects multiseries. 

In my sandbox you can see I want to achieve this with only 1 series, not a multiseries.  A multiseries means I have to get from my data how many bar series I need which can be expensive.  

I can see that echarts is getting halfway there with what I have, you can see in this 2 screenshots how its clearly getting the proper information out of my data, rendering and overlapping the bars. 

![image](https://user-images.githubusercontent.com/5525609/187379846-102a31e1-6988-4bb9-996b-cf3913907a49.png)

![image](https://user-images.githubusercontent.com/5525609/187379891-e7190833-2c7e-4568-bfea-6b8bfbba944a.png)

What I don't know if its supported is to actually make the bars background by category (or any field) and move them so they don't overlap

**Comment by Ovilia** [comment]
You need `barGap: 0, barCategoryGap: 0`.
