### ISSUE TITLE
[Bug] [blur.label.style] is not work when series type is 'custom'

### ISSUE THREAD

**Issue by li942475402** [apache/echarts#17596]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRXgKYBOEThsA2hequgNgATAIZgRRHoMFcAjAAYAdPNKwAHMoAsAXXLSBXDfIDsqgGyKAnAFZdvaXIDMy1ccXW1d_ei6Xl11Q01WS9vOVkXdUVHR1D9OU1ItzMzOIdZZ01zRWC0mQVIixi8g1lElSjLVL0w2QAmd2y1OpKfP1kA2DcWmvjZCM7u1u5neUdVRLrY3vSGutcc6fsZBvl52ETNY2G5f1VnYpmZcs7Eqp2LMYW6nSPS1ey66uX7yKDbl583eTVVaxyep9uP81n9FGZPC8SmBKCAmEQAOQAYwArngwMAALYIu4sJjQISsACSYCYmKIAAoQCIWCJMXhVCIQBAAJQIAB8yCBSJg6MwADURAAbFFMBCwJkQRQAN2Foop8hZAG5ubywFRBSKxYhJTK5UwKbJlaroHyQMA8OLdTzgCwhBSuBhNaLVJRnUxtMbvLAeab1ejKELtRLmYoA0GKV7vHiwCiWHB-N7YDC4YiAOYsYAokA4oHoDBEc14LjyYboSiFi1yMuwABmwFRnARzCFtdzSZ9AAsIEKhHjoJI8wJEx30Cn4bBkRAWEig-3R-g8J2mRORwvYCwiAoh4IGOvYOGmDvYMQh9ogcQVfo99IhSIAEZMIV0A-d4AAdyIYBYLrrtsxYikpusCRhyk71I4OKwEWECQDAiIYjmJ72Ke6DnpeQA

### Steps to Reproduce

1. You can access this example via the link above
2. try delete the code: `const style = api.style()`
then you will notice the label is disappear
print it, the style of label will be included by return of `api.style()`
so, if use `api.style()`,  option of label will work
3. but when use `blur.label`, it not work
4. then I try to set blur style on shape that return from function `renderItem` like this:
``` javascript
return {
  type:'circle',
  blur:{
   style:{
   textFill:'red'
   }
  }
}
```

unfortunately, it not work
print zrender instance, the label seems like be draw by `textContent`

### Current Behavior

`blur.label` not work when series type is 'custom'

### Expected Behavior

1. `blur.label` work
2.  get blur style by some api like `api.blur()`, set `style.text` or 'textContent' is useful 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This seems to be a bug. Updated test case:

https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRXgKYBOEThsA2hequgNgATAIZgRRHoMFcAjAAYAdPNKwAHMoAsAXXLSBXDfIDsqgGyKAnAFZdvaXIDMy1ccXW1d_ei6Xl11Q01WS9vOVkXdUVHR1D9OU1ItzMzOIdZZ01zRWC0mQVIixi8g1lElSjLVL0w2QAmd2y1OpKfP1kA2DcWmvjZCM7u1u5neUdVRLrY3vSGutcc6fsZBvl52ETNY2G5f1VnYpmZcs7Eqp2LMYW6nSPS1ey66uX7yKDbl583eTVVaxyep9uP81n9FGZPC8SmBKCAmEQAOQAYwArngwMAALYIu4AIwANiiWHQgfiRLimPiSd4BEjgPjgMTYAiWEwhAigQwaRAwExMQBlGH4-HIIHoOkMpkIgDmrKY0BxYtgoBESJ5lCISjMnJeXOkrOgQlYAEleZiiAAKEAiFgiTF4VQiEAQACUCAAfKKaXToOjMAA1ESEpgIWBOiCKABuQZRTAt8hdAG4gT6_ZRA8HQ-GozG47IkymYH6QMA8FnnYo6YyhBauBgM7HVOnc9oC96i2BYOjKMLyxHu8KLW3vKywES4PwabAYXDEbLgCiQIqp5giCW8Fx5MN0BrYOu5NvYAAzYCozgI5j4o_LqdIgAWEHxQgNkiVfDfAhnIuREBYSOFN4rugeB3k6IqTkBAhMgoH7oHqkEDkwH7EEq2icsm-jwQIZIUlSyBdnewAAO5EGALCNsejKYmIvJMkOHrMvUjg4nupY8lA0CIhiS6wChgh8bAaHEImQA

**Comment by li942475402** [comment]
some additions:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/30969393/192512306-ecfa71b5-340e-474f-a812-8425c6f8ecdf.png">

**Comment by li942475402** [comment]
get it! There is no processing for Blur in the source code, you need to add it yourself
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/30969393/192961928-2e05cea4-b040-4b4c-b24e-185ff22b195d.png">

the function `processTxInfo` also needs some tweaking
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/30969393/192962093-dc68f7f5-3ab0-478c-b09d-02a0d13d6c09.png">

You need to complete your custom label content in `renderItem`, like this
```javascript
rederItem(){
  // ... your codes
  return  {
      type: 'circle',
      content: {
          blur: {//... blur label style}
      }
  }

}

```

**Comment by li942475402** [comment]
In my current understanding, the custom series don't support `label.formatter`, you need complete it in `renderItem` by  `content.[${state}].style.text`

**Comment by li942475402** [comment]
`label.normal.formatter` is handled by `api.style()`, but the `api.style()` will be deprecated, although `api.visual()` support `visualMap`, there are not a function support label.formatter

> some additions: <img alt="image" width="811" src="https://user-images.githubusercontent.com/30969393/192512306-ecfa71b5-340e-474f-a812-8425c6f8ecdf.png">

**Comment by li942475402** [comment]
All in all, before the official support for the new `label.formatter` for custom series, it is recommended to customize the label content in the `renderItem` through `textContent`
