### ISSUE TITLE
[Bug] : Bars are overlapping for the duplicate category names

### ISSUE THREAD

**Issue by jitendra-dangi** [apache/echarts#17595]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/s/basic-line-chart-forked-2sjy7i?file=/index.html

### Steps to Reproduce

<img width="1189" alt="Screenshot 2022-08-30 at 12 08 32 PM" src="https://user-images.githubusercontent.com/46344085/187367343-6ef9052c-0486-492b-bc56-4a2612929550.png">

1. Use any dataset which contains a duplicate category name for the bar chart. Here is the example 'Milk Tea' is duplicated
```
   dimensions: ["product", "2015"],
   source: [
      { product: "Matcha Latte", "2015": 43.3 },
      { product: "Milk Tea", "2015": 83.1 },
      { product: "Milk Tea", "2015": 33.1 },
      { product: "Cheese Cocoa", "2015": 86.4 },
      { product: "Walnut Brownie", "2015": 72.4 }
    ]
```

### Current Behavior

The bar is overlapping for the duplicate category

### Expected Behavior

Duplicate category bars should not be overlapped.

### Environment

```markdown
- OS: Mac OS
- Browser: Brave
- Framework: Node.js
```

### Any additional comments?

It works as expected without the dataset approch

**Comment by Ovilia** [comment]
This is not a bug but an invalid input. Where do you expect them to be if they are not overlap?

**Comment by jitendra-dangi-arris** [comment]
@Ovilia Thanks for the reply, I need to show the bars twice on the y-axis. It works fine as expected when I do not use the dataset. Below is the example for 'Brazil' repeated twice.

<img width="1435" alt="Screenshot 2022-08-30 at 12 33 18 PM" src="https://user-images.githubusercontent.com/46344085/187372168-0bc09a85-cee7-47c4-8ba7-4b266218c48a.png">

**Comment by Ovilia** [comment]
This is because when you don't use dataset, you are using them in two different series. You should use dataset as array or use [transform](https://echarts.apache.org/en/option.html#dataset.transform).

**Comment by jitendra-dangi-arris** [comment]
> 
without dataset works even with a single series. nothing wrong here

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/46344085/187410052-337fea5f-0de5-4621-9132-c4949e7fdc26.png">

I tried using the dataset as an array, but It didn't help.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/46344085/187409079-0229e670-f9c6-4273-9c34-775799de93de.png">

Am I doing anything wrong here?

**Comment by Ovilia** [comment]
Using the same name for category in dataset is an undefined behavior. Can you use a different name?
