### ISSUE TITLE
[Bug] Boxplot Squished to the top in Grid

### ISSUE THREAD

**Issue by c3-anerishah** [apache/echarts#17599]
### Version

5.3.3

### Link to Minimal Reproduction

https://jsfiddle.net/hkwe9n26/

### Steps to Reproduce

1. Create the box plot chart with the config in the attached JSFiddle
2. The minimal config has been pasted here for convenience:
`{
    "xAxis": [
        {
            "type": "category",
            "data": [
                "thickness"
            ],
            "gridIndex": 0
        }
    ],
    "yAxis": [
        {
            "type": "value",
            "splitArea": {
                "show": true
            },
            "gridIndex": 0
        }
    ],
    "series": [
        {
            "name": "Boxplot",
            "type": "boxplot",
            "data": [
                [
                    12.01,
                    12.1325,
                    12.205,
                    12.255,
                    12.37
                ]
            ],
            "xAxis": 0,
            "yAxis": 0,
            "color": "#253EB5",
        },
        {
            "name": "Mild Outlier",
            "type": "scatter",
            "data": [
                [
                    0,
                    11.93
                ]
            ],
            "xAxis": 0,
            "yAxis": 0,
            "color": "#E8B500"
        }
    ],
}`

### Current Behavior

See that the boxplot is squished to the top of the chart with a lot of whitespace under it. Since I am not providing any custom min max values for the y-axis, the built-in echart heuristics for these values are not performing correctly here.

### Expected Behavior

I would expect the y-axis values to span a smaller range - perhaps 10-14 in this case - so that the box plot's features can be accurately identified in the chart rather than squished to one part of the chart with whitespace around it.

**Comment by Ovilia** [comment]
This is not a bug but the expected behavior that axes always start from 0. You can set `min: 'dataMin'` to force using minimum data as the axis's starting value.

**Comment by c3-anerishah** [comment]
I see, but if I use `min: 'dataMin'`, the intervals on the y-axis get messed up since the gaps aren't consistent (i.e. the difference between the bottom two axis labels is 0.07, but the difference between the rest is 0.1. For small numbers, this isn't as big of a deal, but it makes a larger (more misleading) difference if the intervals are uneven when the range is very large.

**Comment by Ovilia** [comment]
@c3-anerishah `min` and `max` can be a callback function so you can decide the logic. Please check [the doc](https://echarts.apache.org/en/option.html#xAxis.max) to know more.
