### ISSUE TITLE
[Bug] 多个折线图中，legend的icon没用，我看之前也有issue说修复过了，但还是会出现问题

### ISSUE THREAD

**Issue by kitiho** [apache/echarts#17604]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Fline-stack-tiled&edit=1&reset=1&code=GYVwdgxgLglg9mABFOBRCALAhgJygVTBigAowQBbASkQG8AoRRCBAZykQCMtWBTRALyIA7jDAATOMIB0YsLxwB1GOKgZEAekQBGAAwBuRohy8oIHEnIVEAKi49ehgL71QkWAkQBzUwCUsEnAUACJYUFgkNAxMLGDsxrysgogA2gC6hkzAcDiIJAA2pogwyQbFiAA8iAAc-sUA1PU0JqzSAA4grBgkALJhGNLA-XA5vf3SOAGSFJG2iAAsurpUVIZGJmYWCazO9LHx4mFYySlG0UyIYFgUvABciADkgO6xgLOJgPOJDwA0RkwAblj5EB3bx-KZBULhSLfC7MODDHD3B4AJm0n0QSIArPM0Zj5g8jE5oXQfpdrsDnoBxZUAG1mAMr0viT_oDgT4oP5AiEjlCSSx4YjMWjtFicdo8QSiecmFcbojAKJ6dKJfwBQPuLLZ0whESoCthvMe2mqAuqAGYBRjdPimISziSpeTANlKgEv3QB-boAwJUAK9b0mGM5Ug1lgjmQrXcuE5REYjGG1HopYWxBWpgS0nSx6APgVADmm8oZSuZoPZGq5MJ5oceRoNOiRADYcSjY_HiTDbYjAHtqgGnTQBLkZmvdmVbn1Zyg4WQwjHkjsYgK2XtAB2ACctfFNrJiMAcxmAfATPRdvTm_Xn-9qi8PkdoqzoZ1GpxXa_QMvR_rk4G0PEghOcUHDYG17omoDgYF4fIeWAAB4wKwG5MMBoEAApwGIUAKF-JJMFAACebTkhAOBwKwYHakw-RYJwvD5IhMIwtwEAANZeFh4DiAAwkOiIAMQVlgs7VBisYwi4PFikYhQ-BIpEXL-XgYFA9y6NqKCfo8EC8GA8E4OBIgqGo9x6NJJIaFoGC8H-EmIlpACkqk5DAimSY8vwKLAEAAqp8FAVAADKqGFCJMLZEprkwAAXsCeh4TqxYPMxSzmiSdZMLpxTwRQADiWByTO2owLEiIQDAOAQIUG51jRKheYghTANZDxGmZ2piUZOhLNqnBwFAKAUIiVVOQ-xm6NVOlaKIqgYIiZ69TCcX6YZFXVNUo0XLE4RiAAMoRxH3D-QL8UwQEAIIgaw9ynDCibIWhGFhLwXg5ChqlME1dG4ChyVycAAJ8CFhzhAdSEXA8ujVLcMYhUwDx6AD5pA3qSJgzdP0itDEMgxW8PfcD-rI2RP1Iro6MYyOUMxt9aTRUYaREihu2gV9R3fah6GIluMOsG0-TEItYjAsdFws_I7koZ59a4yddOPIcXS8OIMODrqDw4F43AkNJiufLo0jaFQ3FkbxmshZBrDLURJECxjXRSPcL35Hw31a5aJNEnwv6JPcH1YNIFApSQJC_DQAgAHxGwkmxIJzjaIL80i2iFtPktzvAw8QvAULz_Oc7FWgHvcAAGsvywAJLQYcHoSOhUBnENxU1ODiAoyiDVJ0gRijiAPlg2WoVJVshTHScc436eIFncsRHnBdDkXasZx3324LwWDdyVUvFvIwiILwmC4FArQ0SlGAZdIbPyLgiWTOIllKQraLSYgl9RodguaFogCb8YAM4mAPRmgAIdoAG8qACFuHaADD_gBQcoAaDlABnuoAZ-VADbaoAKjlACdpoARBVG4JgQRcOAwBgB8GstpO-c0mL92zkPfO0hC4ChLvfRAz934f0AE5BX8niAGnNQAORmUKQTFXGKcyIoLQaYTSEMF7DgHrnAhRCr4kLiuQz-1DADLfoAfXNGHMMbmkKgk8MbO3uGHLc0VMhxkUU4fQQA

### Steps to Reproduce

多条折线 修改legend的icon

### Current Behavior

多个折线图中，legend的icon没用，我看之前也有issue说修复过了，但还是会出现问题

### Expected Behavior

多个折线图中，legend的icon希望有用

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
似乎是因为 series 的 `itemStyle.opacity` 为 `0` 导致的，可以手动设置下 legend 的 `itemStyle.opacity` 来覆盖下。

```js
legend: {
  icon: 'circle',
  itemStyle: {
    opacity: 1
  }
}
```

**Comment by kitiho** [comment]
解决了～ 感谢
