### ISSUE TITLE
关系图中怎么让一个节点指向自己 并且有箭头显示 像这样的

### ISSUE THREAD

**Issue by 542473232** [apache/echarts#17612]
### What problem does this feature solve?

1 在关系图中 怎么让一个节点指向自己 并且有箭头显示  像这样的
![image](https://user-images.githubusercontent.com/65716967/188313392-e92e1f5d-f7bf-4a0e-8a01-297e1ee66112.png)

2怎么现实的label不随着line方向展示 而是调整为水平的呢
![image](https://user-images.githubusercontent.com/65716967/188313434-6ec31220-c88b-47d7-bb8f-eda95e74eb55.png)

### What does the proposed API look like?

option = {
  title: {
    text: 'Basic Graph'
  },
  tooltip: {},
  animationDurationUpdate: 1500,
  animationEasingUpdate: 'quinticInOut',
  series: [
    {
      type: 'graph',
      layout: 'none',
       symbol:'rect',
      symbolSize: [140,100],
      roam: true,
      label: {
        show: true
      },
     
      edgeSymbol: ['circle', 'arrow'],
      edgeSymbolSize: [2, 10],
      edgeLabel: {
        fontSize: 20
      },
      data: [
        {
          name: '接受',
          value:791,
          x: 100,
          y: 300,
          symbolSize: [140,50],
         label:{
           formatter:'{b|{b}}\n{c|{c}}',
           rich:{
             b:{
               fontSize:20
             },
             c:{
               fontSize:15,
               align:'center'
             }
           }
         }
        },
        {
          name: '接受完成',
          value:700,
          x: 100,
          y: 400,
          symbolSize: [140,50],
         label:{
           formatter:'{b|{b}}\n{c|{c}}',
           rich:{
             b:{
               fontSize:20
             },
             c:{
               fontSize:15,
               align:'center'
             }
           }
         }
        },
        {
          name: '数据收集',
          x: 100,
          y: 900
        },
        {
          name: '批准',
          x: 100,
          y: 1200
        },
    
      ],
      links: [
        {
          source: '接受',
          target: '接受完成',
          symbolSize: [2, 10],
          value:500,
          label: {
            show: true,
            formatter:'{c}'
          },
           lineStyle:{
             type:'dashed',
             curveness: 5
            }
        }, {
          source: '接受完成',
          target: '数据收集',
          symbolSize: [2, 10],
          value:500,
          label: {
            show: true,
            formatter:'{c}'
          },
          
        },{
          source: '接受完成',
          target: '批准',
          symbolSize: [2, 10],
          value:700,
          label: {
            show: true,
            formatter:'{c}'
          },
           
        },{
          source: '数据收集',
          target: '批准',
          symbolSize: [2, 10],
          value:200,
          label: {
            show: true,
            formatter:'{b|{c}}',
             rich:{
             b:{
               fontSize:200,
             },
             c:{
               fontSize:15,
               align:'center'
             }
           }
          },
         
        }
      ],
      
      lineStyle: {
        opacity: 1,
        width: 5,
        curveness: 0.4
      }
    }
  ]
};

**Comment by Ovilia** [comment]
Please follow #15405
