### ISSUE TITLE
[Feature] Hope to support the area range chart

### ISSUE THREAD

**Issue by Tyxiang** [apache/echarts#17610]
### What problem does this feature solve?

I want to draw a graph showing the results of a physics experiment, showing the mean of the experimental results and the trust range. like:

![屏幕截图 2022-09-02 214124](https://user-images.githubusercontent.com/7249372/188160475-49285bd8-fc95-4e03-aebd-e76d48bfb0f6.png)

### What does the proposed API look like?

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [[10,30], [15,32], [14,31], [25,32], [18,26], [19,29], [13,32]],
      type: 'arearange',
      smooth: true
    }
  ]
};
```

**Comment by Ovilia** [comment]
This can be done with stacked series. I made [a demo](https://echarts.apache.org/examples/zh/editor.html?c=bar-label-rotation&version=5.3.0&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrAIIBOOdsAwgAs6XMJSIBfADREwwYFkggCqYhi4QA5ppxcqdUhADOlGWoPGACsAjQwulUTVgAniHyxKDLsCMmzarBYdABGOFiOgcQhjEyaPgCu0Kz8CsB6ngDEAGx0AOwAnAAcAKziURJOsJXo0kS4OsmRxKx09AQA2pQAogC2dBBYpp4AqtBQcBys_p4AahCsOMCc08OUACIQPAxiUp7UvFwMgrDd0Jq2OJQAupIBcgohwKTN6ABmvGAJPK_ERnQANxwHCMAEl-joVDViNC6uh4gtfrg3hRPABmACkpiqGk0glRlAALFiAugnmA5L0qJjsWoGDB6LYADKhcIEMBcBI4O5EUgcQxGTpVVSBVzuKgMNo4TTpFy0wJPJKtLguADidGUsDedCwRhwpJabTonUoAFkYGsACpctYAdTYVsECTWADENGtqG0PUkblVodcAi5-cYhWoRc43B5KACdTa_UQA0Q9RocILYB1hVV0NA6L0o30BkMDegxVGsJd5WojPRmFRLcB6EWs7BWu10wBGABMAAY9u20Z2-932320YS9gVe7BO2ip53293E1EIPZerQXLhfnS0hlKJkGAfyoE4YERLx15vCFF0PSsOkqNAYFdmye1DheiBhEYQ1fr2e6BeHjhtet73p4j7QM-17VC-foGsB2a5lGYwTCs_jNqWVDlpBlZ_DWTB1g2Oq4eg_6AVuxCgbumQ4LRR5qK-hpth0nY9n2RSDrA7YFCO05jnsnaTnsaKzsJC5LoE76fnQ35pghxBka4l7ydud7UbRUHXtCDFwZmUQ5nmVDzIsyxTOhUSYZ42FXMWsDVrEhGNiRsCKRuQHNjeO5UDRdEvrZrbGh2JRzgOAnDn2JTjlxQmwCJU6EuJtkru-5G_lEVHeQeDD0TCtlSV-P4qS5PAAUp7nQZ5aneRpOU6RU8boLcEgANxAA) for this.

**Comment by Tyxiang** [comment]
> 

Yes, this is a way. I'll try. Thank you.
