### ISSUE TITLE
[Feature] How to increase the gap between y-axis Ticks in case of large no. of values on y Axis ?

### ISSUE THREAD

**Issue by stuti24sinha** [apache/echarts#17618]
### What problem does this feature solve?

In case of large no. of values on y axis, the gap between axis ticks reduce. Because of this the axis label names are being cut.
![Echarts](https://user-images.githubusercontent.com/57613445/188423884-380b6c3e-6f34-4c5e-a516-a3e54e6a38ce.JPG)

### What does the proposed API look like?

yAxis: {
axisTicks {
gap: 
}
}

Property eg. gap, within AxisTicks in yAxis to add a custom gap length

**Comment by Eloyts97** [comment]
I made a function that receives the labels to be displayed on the axis and obtained the space occupied by the label according to its position, font and font size
