### ISSUE TITLE
[Bug] markline动态添加无效

### ISSUE THREAD

**Issue by clark-tan** [apache/echarts#17627]
### Version

5.3.3

### Link to Minimal Reproduction

https://codepen.io/clark-tan/pen/QWrjMyB

### Steps to Reproduce

1.初始化折线图标后通过getoption获取配置，
2.动态添加markline，再通过setoption设置

### Current Behavior

markline没有跟预期一样显示

### Expected Behavior

动态添加markline，再通过setoption设置的时候可以正常显示markline

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
```js
var container = document.getElementById('main');
var chart = echarts.init(container);
chart.setOption({
  xAxis: {
    data: ['A', 'B', 'C']
  },
  yAxis: {
    
  },
  series: [{
    type: 'line',
    data: [120, 200, 150]
  }]
});

setTimeout(function() {
  let opt = chart.getOption();
  console.log(opt)
  opt.series[0] = {

    markLine: {
      data: [{type: 'max'}]
    }
  }
  chart.setOption({ series: [
    {

    markLine: {
      data: [{name: "test", xAxis: 'B'}]
    }
  }
  ] });
}, 3000);

```

**Comment by clark-tan** [comment]
> ```js
> var container = document.getElementById('main');
> var chart = echarts.init(container);
> chart.setOption({
>   xAxis: {
>     data: ['A', 'B', 'C']
>   },
>   yAxis: {
>     
>   },
>   series: [{
>     type: 'line',
>     data: [120, 200, 150]
>   }]
> });
> 
> setTimeout(function() {
>   let opt = chart.getOption();
>   console.log(opt)
>   opt.series[0] = {
> 
>     markLine: {
>       data: [{type: 'max'}]
>     }
>   }
>   chart.setOption({ series: [
>     {
> 
>     markLine: {
>       data: [{name: "test", xAxis: 'B'}]
>     }
>   }
>   ] });
> }, 3000);
> ```

I think I misexpressed it. I wanted to ask you about this example: https://codepen.io/clark-tan/pen/QWrjMyB
