### ISSUE TITLE
[Feature] How can I dispatch a wheel event programmatically?

### ISSUE THREAD

**Issue by jianqi-jin** [apache/echarts#17638]
### What problem does this feature solve?

I just have two Echart instances, both of them have a dataZoom. How do I make them move synchronously when I scroll?

### What does the proposed API look like?

Maybe just offer a dispatch function that I can pass a event that type is wheel.

**Comment by JinJianQi** [comment]
I have to use two instances, because I need to set some styles on each one. Something like border style.

**Comment by Ovilia** [comment]
I'm not sure it works with [connect](https://echarts.apache.org/en/api.html#echarts.connect). You can have a try.

**Comment by JinJianQi** [comment]
Thanks, @Ovilia , but there are not only two instance, but also a div, How can I dispatch wheel event when I wheel on this div?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/33452468/189464595-7e3353eb-9ea2-45c2-8ca5-759dfbd49767.png">

**Comment by JinJianQi** [comment]
#949 fixed this.

**Comment by JinJianQi** [comment]
[#949](https://github.com/ecomfe/zrender/pull/949) fixed this ~. @Ovilia Could you help me review this. Thanks :)

**Comment by Ovilia** [comment]
Can you first make a demo (without zrender changes) to show what the problem is and then I can help check if this change is necessary?

**Comment by JinJianQi** [comment]
@Ovilia Hello~, Thanks for reply, there is a demo to show that, I just want fake the wheel event on another div.

this is a simple demo:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/33452468/191306445-164d9582-137e-4da3-8460-9616e19fb34a.png">


```
var dom = document.getElementById("chart-container");
var myChart = echarts.init(dom, null, {
  renderer: "canvas",
  useDirtyRect: false
});
var app = {};

var option;

option = {
  xAxis: {},
  yAxis: {},
  dataZoom: [
    {
      type: "slider"
    },
    {
      type: "inside"
    }
  ],
  series: [
    {
      type: "line",
      data: [
        [0, 0],
        [1, 1],
        [2, 2],
        [6, 10]
      ]
    }
  ]
};
let wrapper = document.createElement("div");
wrapper.innerText = "wheel on me";
wrapper.style.height = "300px";
wrapper.style.width = "300px";
wrapper.style.position = "fixed";
wrapper.style.backgroundColor = "rgba(0,0,0,.3)";
wrapper.style.top = "0px";
wrapper.style.left = "0px";
document.body.appendChild(wrapper);

const onWheel = (e) => {
  console.log("onWheel");
  const fakeWheel = new WheelEvent("wheel", e);
  fakeWheel.zrX = e.offsetX;
  fakeWheel.zrY = e.offsetY;
  console.log(fakeWheel);
  myChart.getZr().handler.proxy.dom.dispatchEvent(fakeWheel);
};

wrapper.addEventListener("wheel", onWheel);

if (option && typeof option === "object") {
  myChart.setOption(option);
}

window.addEventListener("resize", myChart.resize);

```

also, you can check this link to reproduce.

https://codesandbox.io/s/gantt-chart-of-airport-flights-forked-1hbsgx?file=/index.js

**Comment by Ovilia** [comment]
Do you want to trigger ECharts' dataZoom event or what?

**Comment by JinJianQi** [comment]
Yes, I want to :) I just want this fakeEvent work as a natural user action.
