### ISSUE TITLE
[Bug] Bar series clipping does not work

### ISSUE THREAD

**Issue by ob-ARC** [apache/echarts#17631]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoW7YCICG0IFtswBTTALlgDNsAbAZ2IBo0NMATI7ALWGH3NgBtFhgypRE1hDYDMSAIIAWAEIB2AKyqAoqoC0y9QA49igEzyADPvkBOAMy7DpiwDEXAYTuqAIqtXKAX0xmSUlMSggaEgAnAFlgNlIKTGgYUhDQ0Uw6AAtgAHcBMGiAVyYRTKwwAE8QJKwIaDppdIrM7LBsaLABCwzKrGJoGQoARgs-ttDMaOJaSHx64rKp9ACKgF1-rAAPeR2IOgFhTPEBrFyCotLy86x8RoFR9Rt1ADY7dWcJie32wh2TxemlMozeP1-qwkmEaADdiNEGAJqPRbucUthFrIdrBsAcjn9pnjDgAZRr1M53dDZPKFCjLNFUrAwLgI4DXFZ3AKEsIPVLRAAqEAAxgBrASUqkwpotZG0Bg8yo4GgQADm0AA6hAwDkSdgAEbEGgcxlSuggFVgAByJXwhuiAkUUNE3OdrHNlrJ0ApbrClzpVHlxF9sFdd0wfOA0QAyhbtV6fUzqf65aiQ2H0TU6rIFq1w6rotIAJLDYiAiiTcPQTHEABKwE6JF6iqy1cWJOAwqIUGgsmFQxiwRDGMWAHFsCABKZ1C3WMU1aqEVp4dAevSbrPqd4iMQhYsXFHCGusAAJE9kfD8TdYEDAZqQGCyfUNsB8TBQ9aiLYVTDVfaHY4oUldoU3XMpr2yLsaHqFEFWHOEESRChYNNdo23qX9cXxWBRiHcNiToBMJRDLJQNgBlryyFk2RNdMIMjQURXFChgPRRpmkSVM4KTLBaDVTVtV1A0jRNSj3Tja1bXtR06OHD143JYieJpK4wODLl6MaKNY09RSWJI91aS49TzgzAZMCzDDYVoMo8PRAti1LctYErdF0PrRt6hsVzzPQjsuwfXtkn7VcETs3ya3HScKEUHylQIvVDWNfTlJVb0AHl4WiSgaFUrBUm9cKpSNFUQGaI5kgAOmqorw2ALKcrylI0lqzMyzAaMcmwNgCnSyhKAYMAAE0njE6kSB2Dqup6_I-oG4gwAADVGgzxvazruoKZQaBKB0xjGqp1umgp3GAXK9qwaJVX1bAAAppxnWAHsYJ71EeiwAEpWvMiawGUKNEmibdcjmwaVuU37_uiQGBVqDC6DO6RvqVSGAYRLU2B1cGkws9qocB07ztkK6bvut6Xue173q-g7MByYg1RyY9Rlp_JpCx_bVouY7Zv6waRs55Tck23n5qW7GmRpEXtt2iWzR5wmo2J667sptXyZcmmucwZ9oYRWtuogEoKpw2ndcB4GclBha5fDc2EVh7NkgRlUZDNtHokVi6ZhVsnHvV6nkZAoy1NpygYA6iAAC96lGUww4j6Mamg2R-UIY0E9XDUGdVJnU8PWgg-mcPVxcTFImqWQ6FwOhdAYQtKCLv1aViRpEpE5Cg1p_1YjxdvksDVFaZyFpMoRGgJ1ojTh3nVVF2iZcB1E4db3vHtZGgygeg_RVWObvKKLkqCYK7-DoCypDB-4tya1kaosMOJ6m94_EiJSnGyMP5TqOidk1Nk8MDEhRiiUjjdispO5D21nxdUWodT92XkLCSNo7RhRigA9E8kwBv2QNrT-NwMHmQYjpBShV36SzIihQhKM4ayGsjtPM9lCxsBLIkZycU0I1g8juAQ3kIJ-U7N2R8wUBxhX4ZFSeMUOHTHQgKdaydEw4xLpHGOTx47a2UUnaoKdkhp0LpnMA2dGbHmatEdOz8sjKLLg8GgldnY1zrgiCAjdabCjOkrZIJNbpvEej4l6PitbKTZpjHItt0T1QRI1AMzVCrUPaAlYSA895KjSsQMe2VcrRIKowyWJUIBlQAlVGqtMIkZKatkixc4joi2tsNMJP1qkzVqctQWONfobRmjLC6LNtbtIVu472JNVYawDi9T6lS1qTXxgiS2tT6kozxh7R28NEZu16YsvW0QMYc1NusqZHsvbK1JqMqmYzAk43psY-Z7Rgk7J6ULHmtSBa7IeTUvmC0WkvI_jzLp1zpjCxmoczxvsTmU3Ge7TZBs2BGxNvcnG9sgbYBBu85mEKYa0OdqsiZWAEVAsuiCkZhLA7dxDuRDcGiC5gEHMhEo0BhSBVgLdeh4FYCNDYR9ZAsBZhgF2nAcYFhYAACpYDMuILAAA1LAAA5AAUilQAblDAY6M0dY7qOUpohR-czH6IpVnHOeddEFwznqsA1iK5VwcfXZx2KVL5FbtABBkDr4UJbn3RJxlh6jyyhPaKZLOSmQgrPeei9VyIPRKvbU69PFXI_JsbY2QnHEBNicUIySsiWSfF0Z-I4MLRlwhBXABAhFBSvqhaYhBoiihwem6YHBOiAR4qIWtkt0KyD3DkptWQ9j4iBK8D4XwITSK7ZgVJWidG4K7eZNxRNgX6lunHQwL1F3LtMIYc5U7piZuSBwXIxAZBc0yGZTdWAJ5JVASe6EqT0lRPzoVA64Y8kFJNpgaqlVsV1Qapku9nbL2TKmm8sWzy4V_qqZNDpvUUWfJA6Bw64Gfk7W6Q-tq8GRZ4p9scolFMNbgsPShv6HtZkor-SO1GmzllVyxchhp-zNnbNCa02DcGCObPQ0Mv22H_Y4Y3bBumBrUV4fMrchjXymNSyaSi4D1GlQAsg2LaD0ng7S0QyRpt4mToDKOcMrjOmzkfvRAiqFMLVPKQRURsWJn4VLIxRcKjgmlS4s03O7TnHXOa30-ZSNgVZAPDYGwFOin_mkpQoFsImjVVqNC9CTV2iMJ6JNUx6kyijG5xMfFjzSorHl1sZapojiG7vlA5-KdxWmQbDiXWzgjakypq7c8ftnxvg_Gk8OqUhWkzfh4rVpt9X3h2EMIYId0mYPKXa2Vg63WeK9beGYWKEJhvScwGNqknWav2em4ocEQ31uLeW3cVbTJJtJg2zYLbzX7MWEqoYOwigRs4z2-cA7VIjtMmm-oOwTXISbsu29QwM57NLa5k9u4L2qRvbeIN-bF3KrvEUEugHD2BjA_OKDu403wRzfO99yqbw_D_c3YDniyOBio_OOjzHWOp2XcUDYVQu2gcTfW8CN4uOztfapzjt4a76dE8Z5u6bqg47bex6oW76qp2E463zqdAu4fC454oG7igedS65qTgYAvDAU9a3cS7dgbDK4RwztXTP-1OCHTr84l3VA2FGHYFX42Tf8-Z39tnluBiXeMOLkdiPKjE8qOryo03DA2E--7yol3vKmG92p33mR_eZED5kabofIeU67dbwX9uje86dzL5np3tcLZz6rrrpvNAW_Zxnh3K3pd1eBKoCwdg3fF4J3H0ICfQhJ9CL1xvqgw8tcqqHxXNf9t156w38Yaeq89dH498fU3J-KCLztkvjuy_O9eIL6fM-ptz6RyGTvyZqh2jOj-nN_pown-fAPL-6Ie2HFYWWZsw4_z4if85O7YRtTEHwOOxRksM6Hi-KpMowoey64BOEkBP2PGds1mTstmrs7eawEEY6Wq5CUo26iBSMFWYQwopU4a5kUcL-4YWgk0QwbAAowA7gXU3Q8gsw2A5-EEbiAMjQO4V-dAJA_AwUXQJAzQuApgB6R6u8M8NmOs2a4iWIyQ0YpgOaRaR40aZaEE9ajBFA3e6A6hEg02jW8u1ea-teee9eDWA2uhs--hY-hhE-_as2phe-5h8-lhi-1hbu4eye--fuC-x2zONOLeq-bexuG--e_a72A-0Of2YB7h8enhr2zO7wO-g-WuXwkRHe0RYOzOGOthSYkeFgYIyRkgR-Egmhog5OFureEuyBEgBRogRRGA6Oqgvh2Ooe6gX-bWARa2m-7wguoRjRowcOeRlRqRaOzOou8R0O_euR9hSOgxZOwxWumRTInuqgWu_RX40xGuLuYerhPeKxGAVRGANR6Awe7w8xYOOx6AexGh5eEOoeJxaOZxsAFxQgVxqetxZO9xjxBxOEBeM2rxHuQ-H2bw7xaxQeDeleWxkgnu6gFgMeo2bRh25ejezevxEeV2NghggJkxHhjhXhW-Fg_eyJbhmJUR2JMRW-U-BJ2xRJKRJJaRZJy-FJkgLR4YFRqxNJQxZJO-4JWh7xh-EEdA1-Z-Rq96cktIV-p-t-5K4YD-dAH-JB6Ib-j-TkqmMIXB_-F6UoQBgy10C6kBYB8cUBpgsBBm8BKySBuBV65IapGB4YWB2QWK5pWQ-B-ShBSoxBFYEEZBJAwwVBNBvB9BcwTBw4LB0MbBJAHBXBfYvByaEAAhQhoQx6zaohCBo6ikkheadgcheAChwiShw4Kh1W8JHRA63RVOQJbJMxxhox_O6J8O_huegRRhsOpgK-m6igLwZZDZVhsOLhw2ZgHZ7RQRsOp2DJEgru_ZhZg5PiH2I5ognw_W45z2VxcRM5GApgbw4wC5IOVxGRUO_OH2TJ6ILJuxwJye6R2uXJog04pgdOVJ-RJ5Pe6R9RK56AdgFgbwNgm5KOVxXRz5sAt2FgtZ5RcJi5RZIxv5zZ6Jn5JO35cxu5U6zg7wUFAeVx5uv5YBt2SFieKFxxcFXaoIfRt5Ax5Z6xZuNxuFTapg3k2edZpeA5jZ75a6aFa6B55kR55x95jJ3xLZ8F4wGJNF6-dFXZjelew2IefFQF9ZglThFeSJ5FU2iRmFXeCJeJJZdWxg4lPuwFW5HRguAF4F0eLFSobFDxHFWhS-3FeFy-1FEltFE5jZ2-pR9mxghl7Qxl5WFh4Y_J4pfYEA0Q-Bv6QWBQYpN-LpIEApNAKqqiYw4emA0psp7pr-_4MpSpCV4YP-f-6Bk6OMoA2Awo2odiLkriTmIBd0Nuq6H5OEIeYyMORp5kCKFGmKZp084YaBsW6p4YmpWmt0ZVOElFy6VVLkNVtqtpLsOBzV6ITpfqd-RBcp5knpFBPptBYA_pqh-ULUzBvAIZ1YYZ1QnBv-kZ3Q0ZsZOawaCICYoax4DIO8QESZGEqSOaba0higmZxa3mzq5aYQ-ZahxFIJDWg6clWRilkgnx2hJhANr2NZQNhRVxNh4NVIbZH5hFrJnZ0lM2PZ62fZSNx5P1p51hw5cNdwY5WN7FOND5wR05BN5wc5gFmlkldlXZPiEO4F65F5rAblplxR6RFgFlPW-5UN1R25550mV5N5_FBhKNOJ7wrOv5r575_N-x35QulNAw_5NNseWlX5oFcuytlQEFGl6tdNIFk5SxPNPECF-tsJht2lk5qFOtyeBuLl0w7NpNnFZuOF6eFFvRatlttlRt9FIeqlFFVF8tlxRZLxdtPezFIdTxYdPxEdkgoIb50dINoJIl62YlydylslHt8lbZmdOlKlaF6l-dg5ulVZ8FBlJd9lvRptSYzZI-xNJlLtZlHJjlm6zlPJHlmC4VPlflAWIpQVPdocck4VkVscMVcVKVhViV7-U9MV6VVpWVksOVeVNQs1GpxVGG3VFVccO9IetVDmJplGTVgaw4rVE6La0InVc6295V_VNgB97QI19p4106BBw94Ybp09pB5B3p1BS1K1gZHVm10K21xA4Z-1PBh1_B0AghJ1hYc8Z15IF1U88Z8aP4DkIwMdaaA9AYIWQZEc2AbcHqH9mYoAsg4wIAgIqBxAW8sgUJVDOaCDhqWADD1Dw4z4VKb4yQbDvupWTdAQQAA&_source=echarts-doc-preview

### Steps to Reproduce

See link to reproduction.

### Current Behavior

When zooming in, bars are not clipped.

### Expected Behavior

Bars should be clipped.

### Environment

```markdown
- OS: Windows 10
- Browser: Firefox
- Framework:
```

**Comment by Ovilia** [comment]
This is not a bug. You shouldn't set [filterMode](https://echarts.apache.org/en/option.html#dataZoom-inside.filterMode) to be `'none'`.

**Comment by ob-ARC** [comment]
> This is not a bug. You shouldn't set [filterMode](https://echarts.apache.org/en/option.html#dataZoom-inside.filterMode) to be `'none'`.

Sorry, but have you checked my example? dataZoom.filterMode **is** set to "none"!

**Comment by ob-ARC** [comment]
Please re-apply the "bug" label.

**Comment by ob-ARC** [comment]
Ah, "shouldn't"- I read "should" first. Thanks for the hint!

**Comment by ob-ARC** [comment]
The Problem is that this also applies to the contained line series - it is not desired to have incomplete line segments being filtered. I just do not want bars outside the axes, which with the current options seems impossible to achieve :(

**Comment by susiwen8** [comment]
Please use `rgba(r, g, b, a)`, not `rgba(r g b / a%)`
```js
    "pieces": [
                        {
                            "gt": 0,
                            "lt": 9,
                            "color": "rgba(0, 123, 0, .3)"
                        },
                        {
                            "gt": 9,
                            "lt": 27,
                            "color": "rgba(234, 0, 0, .3)"
                        },
                        {
                            "gt": 27,
                            "lt": 36,
                            "color": "rgb(0, 82, 255, .7)"
                        },
                        {
                            "gt": 36,
                            "lt": 49,
                            "color": "rgba(0, 123, 0, .3)"
                        },
                        {
                            "gt": 49,
                            "lt": 59,
                            "color": "rgba(234, 0, 0, .3)"
                        },
                        {
                            "gt": 59,
                            "lt": 73,
                            "color": "rgb(0, 82, 255, .7)"
                        },
                        {
                            "gt": 73,
                            "lt": 89,
                            "color": "rgba(0, 123, 0, .3)"
                        },
                        {
                            "gt": 89,
                            "lt": 97,
                            "color": "rgba(234, 0, 0, .3)"
                        },
                        {
                            "gt": 97,
                            "lt": 114,
                            "color": "rgb(0, 82, 255, .7)"
                        }
                    ]
                
```

**Comment by ob-ARC** [comment]
@susiwen8 what does this have to do with my problem? Why was this issue closed?
