### ISSUE TITLE
[Bug] 仪表盘顺时针和轴线展示的不一致

### ISSUE THREAD

**Issue by longchuxiong** [apache/echarts#17633]
### Version

5.3.3

### Steps to Reproduce

1.create gauge
2.option --> 
```js
option = {
  tooltip: {
    formatter: '{a} <br/>{b} : {c}%'
  },
  series: [
    {
      name: 'Pressure',
      type: 'gauge',
      clockwise: true,
      detail: {
        valueAnimation: true,
        formatter: '{value}'
      },
      data: [
        {
          value: 50,
          name: 'SCORE'
        }
      ],
      axisLine:{"roundCap":true,"lineStyle":{"width":16,"color":[[0.3,"#C9781B"],[0.7,"#F163EA"],[1,"#6366F1"]]}}
    }
  ]
};
```
3.result ->![image](https://user-images.githubusercontent.com/46107383/189029573-da7e9969-fcd1-4f6e-a9af-6d73bc866ca3.png)

### Current Behavior

仪表盘开启clockwise：true， 同时开启axisLine的roundCap 和 分段颜色， 圆角不是顺时针展示的

### Expected Behavior

顺时针展示圆角

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
看起来没有问题，是我没理解吗？

**Comment by longchuxiong** [comment]
![image](https://user-images.githubusercontent.com/46107383/190421102-541c3f5c-8352-4216-9c27-e09109094a35.png)

我设置的是顺时针，但是这个分段看起来是逆时针展示的，这个圆角交界处

**Comment by zxqzylucky** [comment]
The award level is the same configuration I wrote on the official website of echarts. The official website is normal, but the same situation occurs in the project, counterclockwise, and the clockwise: true attribute is added. How to solve this problem
获奖级别我在echarts官网写的一模一样的配置，官网是正常的，但是在项目中出现和上述情况一样，逆时针了，并且添加了 clockwise: true,属性，请问这个问题该如何解决

**Comment by zxqzylucky** [comment]
找到了解决办法 原来是5.5.0合并的，版本原因
