### ISSUE TITLE
How can I create a graph where I can move the position nodes and the unions (links) adapt???

### ISSUE THREAD

**Issue by baarbaracrr** [apache/echarts#17635]
### Version

5.3

### Current Behavior

I am not able to change the position of the nodes of a graph, and the only thing I can do is move the entire graph. I want each node to be in an exact position and to be able to move them and for the links to adapt (stretch or get smaller depending on the distance)

### Expected Behavior

I want to do something like this https://echarts.apache.org/examples/en/editor.html?c=line-draggable but with a graph where i can manipulate the nodes and links.

### Any additional comments?

btw i am using angular

_No response_

**Comment by Ovilia** [comment]
You should follow the logic of https://echarts.apache.org/examples/en/editor.html?c=line-draggable and make sure the `layout` of your graph series should be `'none'` and you need to provide `x` and `y` for each nodes.
