### ISSUE TITLE
[Bug] Axis Pointer dont work

### ISSUE THREAD

**Issue by gusgogar** [apache/echarts#17639]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-sections&code=PYBwLglsB2AEC8sDeAoWsBEkwBsCmGAXMmupmHgB5hGYAKwA7ngE4akC-ANKVsMDkghaqMuRYQA5pNa0MAQ0oQAzhh5iFS5QwjQKbYqLHkAniALEMAYxbBlq0ug6d15fjgBGwSiMeZlABZMtGAsAK54rugYAGZ48mBhLBYkxv7yAG54AILKAJIAtvIyIs5iZbDcvJTZWr4aYGYp1gl4ksAsJmp-GAAmCfK0ANp-0QCMY4QATAAchAAsU91pGBPTc_MAzMvGq5OzC_M7GmsH8wCsx2R76wsAbFfj-xsA7I-Ypxsz7zdnAJw_T6Ec4ABkBz2BY3Bt3OSyi1yB5228KeMKOKI-EPOlwxvzm5weuMRbyJWO-pJhAIpUz-hBBYOptJBUMZdLho0x0yZyI5vyZ6N5pyZOMF-yZhNFXLpJMlNLp5NlTKpisIYwZKom0LlY3ZKyFqp5erFqoFRqlYxFZu1EqttLGMttqoVjrGysdU3V7pZKqmut2-qmhv9xqmpuDUqmlvDcqmNujtKmDvj6y1Cbdyc2noz3sdmz9J2NmyDBalmzDJblmyjFdpmzjNcImyTDc2zoz6Yb8yznZzycWqYWxYRxvm5eHUouA_m9fHcvmzdntPmbc7HcXwO76_OvYbsIHSP3Y9Rcux-5nx9p5wXF-BK63a9Rmbpm8fILpO_HT5B-c_b5BQ9fOkj05L9q1_OlzxAv9ryg-VoS_B9YLVeC301Cknx1FCDSwsZgJuDCwMAsZIPw1CYNIp0cMQiiPSwqYP0A306IA2DQzowjWJItYn0TOi70Y6juLfTMsM2BjYLzUSWIostRI4mSHj8ABdFxeBMWoVHqa5GnMOQMnkHAIiuTQVAAGXkDw8BwLSNBiDoijAfQ5CQfTDLwDh2HKVTon6MB5AALX4Aphj8IwGiaORdGUCBegIXFlD8lgaGIEFcTwaBeloNUQT8KoxDC64EvkJLaFS3l0sy4hsty0glNcDAMhUMIDIAWXkYRDB6HTmhACA8CsPBGBUOKekCYJiBiAzlEiHpeggAp0uimBSvhDBpokPB8gyqgVp6Xr-s2kK0gKjRJGS2AyrSaJBFoP4MWiKwBA6OQWEkDx5AAClS2AdU2LgLv-gA6TYAEpPOMPLjBO64ztu-7MBu4hE3h6wnoMTBXvej7A3mf7vu-4GwY5SH8o5aJYaRl4UcR2A6xRx6cGeyxMa-2AZimWBI3OWAAHpYBeeYAFIibSEmyGh8nzrpsmEfO-Y7pl1HGfRjBMc-77frxoHQfB8oMQlzAKdgeXqfO84FauzAGaZjG3s-nGtYB2BCd1sgxfQA2MCN83TdoF4_sV62VZZkE2Y5rnef5oWRYh_XFaN_3feIGYLaupWbdVu2vv-zWnZd4m48tr3zpTpPYD-KnA7Rl6s4dp2CZ1guOU9o2K7LiZcar5Wa48Vn2c57FI4F4XXacZTvP8Vg-tUYgRlJlZurkHBdBGlZlAKfgwACEJwhmlZiviABlRp8FKXFfMGWeZdheGkVvgPLfOTvH_OW_U7SO5Lquz_4Z_6-Zl_g_b-79jAvCmL_V-Ms_6WzuHceGLwxjwPATLF4X8P4gLEHcDBZAsG_2wegXBUD8GwEITA4hpDgGALfrfSBj9kF0NvvQq6N9r5MLSCwhhrDGHcOvs_ZhtD-H3yEdfIB7DRHGDviI4Rj9xFiEkTI6RzDZFkHkUoxRYj1ESOUegVRGipH6IUQYtRRi9GGLMcY8xpjmFwOvpXR-djmEOPYeQthxg7h8I_gIj-NiYE-O_n4j-Ti3EAKIUg-B2j-ZeNAQE6J8CYliBePEsgiS4nwI8aAtBbjyFBMwekzBmS5FJJ0QUsg054bzEQTLZGVS8lkFDPDSMDT5gcjqryIoLAADW2RkiX1SGnCAFACjHxMKfTqlsHrV2ZrXbEOdE4_ReFTC6gMQRg3htELwLBYosAAOoxS3llGW7trgXyOuMue4yPYyxWNAeQC05AAGEIBWEZj9d4Rcah1EsECfsVy3ZrPFr8jQHzNJfONGMb4gLKi_NaRc85FyDbXNuc0R5zzgCczeWnYFM9OTaghRcpw_zLn4uuFiuQ-pTyQoqJbGFZzIUIt2Dcu5lgUUvJYu8jS2K-TAkuJSwlfTiUYFJaCxswlFLEqpVdFS1LiY1XQCpDgABuIAA

### Steps to Reproduce

1 - Generate Chart
2 - Move mouse over chart

### Current Behavior

![image](https://user-images.githubusercontent.com/483606/189306918-2e3c1a74-2f35-40ee-8141-528cba16a721.png)
Axis Pointer freeze when mouse is over and console has a continuos errors.

### Expected Behavior

Axis Pointer work properly

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Framework: none
```

**Comment by susiwen8** [comment]
Please use `rgba(r, g, b, a)`, not `rgba(r g b / a%)`

**Comment by gusgogar** [comment]
https://echarts.apache.org/examples/en/editor.html?c=line-sections&code=PYBwLglsB2AEC8sDeAoWsBEkwBsCmGAXMmupmHgB5hGYAKwA7ngE4akC-ANKVsMDkghaqMuRYQA5pNa0MAQ0oQAzhh5iFS5QwjQKbYqLHkAniALEMAYxbBlq0ug6d15fjgBGwSiMeZlABZMtGAsAK54rugYAGZ48mBhLBYkxv7yAG54AILKAJIAtvIyIs5iZbDcvJTZWr4aYGYp1gl4ksAsJmp-GAAmCfK0ANp-0QCMY4QATAAchAAsU91pGBPTc_MAzMvGq5OzC_M7GmsH8wCsx2R76wsAbFfj-xsA7I-Ypxsz7zdnAJw_T6Ec4ABkBz2BY3Bt3OSyi1yB5228KeMKOKI-EPOlwxvzm5weuMRbyJWO-pJhAIpUz-hBBYOptJBUMZdLho0x0yZyI5vyZ6N5pyZOMF-yZhNFXLpJMlNLp5NlTKpisIYwZKom0LlY3ZKyFqp5erFqoFRqlYxFZu1EqttLGMttqoVjrGysdU3V7pZKqmut2-qmhv9xqmpuDUqmlvDcqmNujtKmDvj6y1Cbdyc2noz3sdmz9J2NmyDBalmzDJblmyjFdpmzjNcImyTDc2zoz6Yb8yznZzycWqYWxYRxvm5eHUouA_m9fHcvmzdntPmbc7HcXwO76_OvYbsIHSP3Y9Rcux-5nx9p5wXF-BK63a9Rmbpm8fILpO_HT5B-c_b5BQ9fOkj05L9q1_OlzxAv9ryg-VoS_B9YLVeC301Cknx1FCDSwsZgJuDCwMAsZIPw1CYNIp0cMQiiPSwqYP0A306IA2DQzowjWJItYn0TOi70Y6juLfTMsM2BjYLzUSWIostRI4mSHj8ABdFxeBMWoVHqa5GnMOQMnkHAIiuTQVAAGXkDw8BwLSNBiDoijAfQ5CQfTDLwDh2HKVTon6MB5AALX4Aphj8IwGiaORdGUCBegIXFlD8lgaGIEFcTwaBeloNUQT8KoxDC64EvkJLaFS3l0sy4hsty0glNcDAMhUMIDIAWXkYRDB6HTmhACA8CsPBGBUOKekCYJiBiAzlEiHpeggAp0uimBSvhDBpokPB8gyqgVp6Xr-s2kK0gKjRJGS2AyrSaJBFoP4MWiKwBA6OQWEkDx5AAClS2AdU2LgLv-gA6TYAEpPOMPLjBO64ztu-7MBu4hE3h6wnoMTBXvej7A3mf7vu-4GwY5SH8o5aJYaRl4UcR2A6xRx6cGeyxMa-2AuBmKY2cjc42cBl4ibSEmyGh8nzrpsmEfO-Y7ol1HGfRjBMc-77frxoHQfB8oMRFzAKdgaXqfO84ZauzAGaZjG3s-nG1YB2BCc1sghfQHWMD143DdoF4_tl82FZZkE2Y5rnsV5_nHacbXZb173PeIGYTauuWLcVq2vv-1W7Yd4mo9Nt3zoTuPYD-KnfbRl605tu2CY1nOOVdvWS6LiZcbL-WK48Vn2c5rhubDgWIeU7z_FYPrVGIEZSZWbq5BwXQRpWZQCn4MAAhCcIZpWYr4gAZUafBSgxMbGB3kwCi8HAJqmzfdl8wYJ4l2F4aRZ-fdN85W_f85n8TtI7kuq6_94ZAMfjMYBb9AG_2MC8KYwDv4SxAabO4dx4YvDGKg2BEsXgAL_lAsQdw8FkAIcAwh6BiEINIbAchSDKHUMgeAn-z94Hv0wSw5-rCrpP0fhwtIXC2HcPYYIx-n9OHMNEa_CRj8IG8OkcYF-UjJHv1kWIeRSjFGcOUWQVRGj1EyN0XIzR6BtF6IUaYtRZidEWJMeYmxljbHWM4Sgx-pd34uM4W43htCeHGDuCIv-Yi_5OKQUEwBIS_4eJ8WAihGDUGGNgC8AJ0CwlJNQcksQLw0lkAyak1BfjoE4J8bQiJ-C8n4IKSozJRjylkGnPDeY6CJbI0aaUsgoZ4aRnafMDkdVeRFBYAAa2yMke-qQk4QAoAUPeJgD6dVNg9cuzNK7YgzrHH6LwqYXUBiCMG8NoheBYLFFgAB1GKq8soS2dtcO-R05mTzmS7CWKxoDyAWnIAAwhAKwjMfrvDzjUOolggT9keU7XZwsQUaH-ZpQFxoxjfAhZUEFPT7l3PuTrJ5LzmgfK-cAWAP57kYChePTk2p4X3Mjgi9FuwiVyH1KeBFFRTbItuZShF0RnmvMsNi75LE_kaWJXyYElwGVgoeeS64NKYWNmEopcVjKroqSZcTGq6AVIcAANxAA&lang=js

Equal.

**Comment by plainheart** [comment]
@gusgogar There are still some unexpected `rgb`. Please check again and correct them.

**Comment by gusgogar** [comment]
thanks a lot
