### ISSUE TITLE
[Bug] visualMap实现折线颜色渐变渲染问题

### ISSUE THREAD

**Issue by luolongsen** [apache/echarts#17648]
### Version

5.2.2

### Steps to Reproduce

折线图通过设置配置visualMap属性配置阈值颜色变化，但当有两个连续的拐点值，比如下文12值的两个点，会出现一条平行线，有两种颜色
visualMap: {
    show: true,
    type:'piecewise',
    top: '13%',
    right: '2%',
    orient: 'horizontal',
    pieces: [
      { gt: -4, lte: 0, color: '#7088ff' },
      { gt: 0, lte: 4, color: '#75cfff' },
      { gt: 4, lte: 8, color: '#ffc619' },
      { gt: 8, lt: 12, color: '#ff8766' },
      { gt: 12, lte: 16, color: '#483D8B' }
    ],
    outOfRange: { color: '#999' }
  },
![image](https://user-images.githubusercontent.com/48511040/190082475-37da210e-8c75-4f4a-bac4-ce63842aa29f.png)

### Current Behavior

折线图通过设置配置visualMap属性配置阈值颜色变化，但当有两个连续的拐点值，比如下文12，会出现一条平行线，有两种颜色
visualMap: {
    show: true,
    type:'piecewise',
    top: '13%',
    right: '2%',
    orient: 'horizontal',
    pieces: [
      { gt: -4, lte: 0, color: '#7088ff' },
      { gt: 0, lte: 4, color: '#75cfff' },
      { gt: 4, lte: 8, color: '#ffc619' },
      { gt: 8, lt: 12, color: '#ff8766' },
      { gt: 12, lte: 16, color: '#483D8B' }
    ],
    outOfRange: { color: '#999' }
  },

### Expected Behavior

预期折线图颜色显示应该和配置保持一致，小于等于拐点一种颜色，大于拐点另一种颜色

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Please follow #17138

**Comment by ye-congwang** [comment]
我5.2.1的版本也有这个问题，本来点和线应该是绿色的，好像是pieces里面不能同时存在正负值，不知道咋解决
![image](https://user-images.githubusercontent.com/57819934/197125982-ba4e7803-6f67-417a-adbb-bf3e9a723ede.png)
