### ISSUE TITLE
[Bug] MarkLine Label visibility not applied

### ISSUE THREAD

**Issue by praful-hunde** [apache/echarts#17655]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/function-plot-forked-13rr3y?file=/index.js

### Steps to Reproduce

Configure Vertical markLine for series with xAxis value.
Configure the label by setting show:false

### Current Behavior

The label is visible on top of the markLine. Label text shows x-position of the markLine.
At the same time, enabled=false also seems to have no effect as the cursor changes to the hand icon on-hover.

### Expected Behavior

The label shall not be visible.
The 10, and -10  shown on top of dotted mark-lines shall not be visible.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
You spelled `label`, not `lable`

**Comment by praful-hunde** [comment]
> 

Found a way via setting lable.formatter to an empty string.
[demo link](https://codesandbox.io/s/function-plot-forked-13rr3y?file=/index.js)
