### ISSUE TITLE
[Bug] time axis labels Irregular interval

### ISSUE THREAD

**Issue by hongdeyuan** [apache/echarts#17650]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=area-time-axis

### Steps to Reproduce

1. 时间轴拖动到每个月底区域时，间隔与其他非月底边界的间隔不一致；见下图：
![image](https://user-images.githubusercontent.com/37143703/190105192-304b6a2d-8f6e-4f7f-bfa5-b17cacf81d82.png)

### Current Behavior

- 拖动到月底区域时， X轴的时间间隔显示 09.29    10.01  10.08   10.15 ....

### Expected Behavior

- 拖动到月底区域时， X轴的时间间隔应为显示 09.29    10.06  10.13   10.20 ....

### Environment

```markdown
- OS: macOS Monterey
- Browser: 版本 105.0.5195.102（正式版本） (arm64)
- Framework: echarts 官方网站例子
```

**Comment by hongdeyuan** [comment]
本人已收到您的邮件，辛苦了！如有重要事情，看到后，将尽快给你回复。。。

**Comment by Ovilia** [comment]
这个不是 bug，默认按可用宽度计算出的间距是一周的间隔，到了月底因为要显示 1 号位置，所以会出现不等分的情况。如果要强制每周显示，也就是不显示每月 1 号，请关注 #17576 。

**Comment by hongdeyuan** [comment]
> 这个不是 bug，默认按可用宽度计算出的间距是一周的间隔，到了月底因为要显示 1 号位置，所以会出现不等分的情况。如果要强制每周显示，也就是不显示每月 1 号，请关注 #17576 。

感谢您的回复，你的回复对我非常有用！🙏
