### ISSUE TITLE
 markline should start from center of axis Tick of category axis

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17654]
### What problem does this feature solve?

when there are mutiple Series , markline should start from center of axis Tick of category axis , even there are mu;tiple series 

![image](https://user-images.githubusercontent.com/97290751/190402709-7cbe0e6e-ec2b-4473-a9cf-abcb33eebe20.png)

option = {
  title: {
    text: 'World Population'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {},
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: {
    type: 'value',
    boundaryGap: [0, 0.01]
  },
  yAxis: {
    type: 'category',
    data: ['Brazil', 'Indonesia', 'USA', 'India', 'China', 'World'],
    axisTick:{
      alignWithLabel :true
    }
  },
  series: [
    {
      name: '2011',
      type: 'bar',
      data: [18203, 23489, 29034, 104970, 131744, 630230],
      markLine: {
        data: [
          {
            yAxis: 'World',
            lineStyle: {
              color: 'red',
              width: 5,
              type: 'solid'
            }
          }
        ]
      }
    },
    {
      name: '2012',
      type: 'bar',
      data: [19325, 23438, 31000, 121594, 134141, 681807],
      markLine: {
        data: [
          {
            yAxis: 'World',
            lineStyle: {
              color: 'red',
              width: 5,
              type: 'solid'
            }
          }
        ]
      }
    }
  ]
};
 

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/97290751/190403077-8f804440-84f5-4003-8cda-7178aeb4f1ed.png)

**Comment by Ovilia** [comment]
This is not the typical requirement so I don't think this should be a new feature. If you want this feature, you can add another axis and make another transparent series on that. See https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis
