### ISSUE TITLE
Echart使用百度地图扩展，地图切片显示不全，有时有单独的灰色块，有时全部灰色

### ISSUE THREAD

**Issue by jxbb012265** [apache/echarts#17653]
### Version

ECharts 版本 (ECharts version):5.x 浏览器类型和版本 (Browser version):chrome, 100.0.4896.127（正式版本） 操作系统类型和版本 (OS Version): Mac和WInsows10

### Steps to Reproduce

地图刷新加载后，地图切片显示不全有灰色块，有时地图整个都是灰色空块，如下图所示
<img width="1079" alt="截屏2022-09-15上午11 29 18" src="https://user-images.githubusercontent.com/650104/190311576-e4214319-b1b1-4c7b-9e64-b03ed6524de2.png">
<img width="711" alt="截屏2022-09-15下午12 10 54" src="https://user-images.githubusercontent.com/650104/190311888-7266ea4f-a1cc-48c8-bb65-59d71427b1ae.png">
<img width="805" alt="截屏2022-09-15下午12 15 29" src="https://user-images.githubusercontent.com/650104/190312374-cff92ee7-1424-4049-b259-a235e62c8553.png">

### Current Behavior

地图刷新加载后出现时，切片显示不全有灰色块，有时地图整个都是空白块

### Expected Behavior

地图正常情况下显示时不应该出现灰白块，所有切片都应该可以加载出来。

### Environment

```markdown
- OS:Mac OS Catalina
- Browser:Chrome 100
- Framework:
```

**Comment by jxbb012265** [comment]
> 这是网络环境问题或百度地图服务器的问题，而非 ECharts 的 bug。

百度的让我问下Echart
<img width="303" alt="截屏2022-09-15下午2 46 53" src="https://user-images.githubusercontent.com/650104/190333219-31b54576-33bf-4d1a-8f49-a43bce14eb20.png">

**Comment by plainheart** [comment]
ECharts 百度地图扩展只是利用百度地图作为底图，而图块是由百度地图提供的，如果图块加载失败，只能是您本地网络环境或者百度地图服务器造成的。

**Comment by wojiaoxiaomayun** [comment]
@plainheart 我也遇到了同样的问题，百度地图工单说切换为3.0新版的setMapStyleV2,这个echarts内部是否使用的还说setMapStyle?
![image](https://github.com/apache/echarts/assets/30283623/5fef0f92-d45a-4ff2-94f9-99ea7c1a743b)
![image](https://github.com/apache/echarts/assets/30283623/65b5be58-f405-4d85-928b-95c89c704e16)

**Comment by Givenchy-Coisini** [comment]
这个解决了么？

**Comment by plainheart** [comment]
@Givenchy-Coisini 这不是 echarts 的问题。百度地图的旧版自定义样式服务器返回确实会有白块现象，这并非为 echarts 所能控制的。可以换用 mapStyleV2 启用新版自定义地图样式，新版应该不存在此问题。
