### ISSUE TITLE
[Bug] toolbox.feature.dataZoom.yAxisIndex is not working as mentioned in API document

### ISSUE THREAD

**Issue by amitknit09** [apache/echarts#17663]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/multiple-y-axes-forked-qrb7ll?file=/index.js

### Steps to Reproduce

1. Create a chart with multiple Y-Axis(3 Y-Axis)
2.  I want to use Data area zooming, so I have used "toolbox.feature.dataZoom" option
3.  I want to control the zoom for only 1 Y-Axis. 
     toolbox: {
    feature: {
      dataZoom: {
        yAxisIndex: [1]
      }
    }
  }

### Current Behavior

Zoom functionality stopped working and it only works if I am giving all 3 axis.

### Expected Behavior

Defined yAxis should be controlled.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by hihiro** [comment]
尝试下默认值 `none`？
```js
yAxisIndex: "none"
```

**Comment by amitknit09** [comment]
> 尝试下默认值 `none`？
> 
> ```js
> yAxisIndex: "none"
> ```

Yes, this will work if I don't want to control specific axis. But here I want to control axis at a specific index.
