### ISSUE TITLE
[Bug] Unexpected commas in dataView when dynamically creating table

### ISSUE THREAD

**Issue by TheHollows** [apache/echarts#17677]
### Version

5.3.3

### Link to Minimal Reproduction

https://codepen.io/TheHollows/pen/MWGoEYK

### Steps to Reproduce

1. Add optionToContent to dataView.
2. Copy the example from [here](https://echarts.apache.org/en/option.html#toolbox.feature.dataView.optionToContent)
3. Replace hardcoded series <td> tags with dynamic mapped out series.

Example: 
``` javascript
dataView: { 
	optionToContent: function(opt) {
		const axisData = opt.xAxis[0].data;
		const series = opt.series;
		let table = "<table style=\"width:100%;text-align:left;\"><tbody><tr>"
			+ "<td>Time</td>"
			+ series.map((item) => {
				return "<td>" + item.name + "</td>";
			})
			+ "</tr>";
		for (let i = 0, l = axisData.length; i < l; i++) {
			table += "<tr>"
				+ "<td>" + axisData[i] + "</td>"
				+ series.map((item) => {
					return "<td>" + item.data[i] + "</td>";
				})
				+ "</tr>";
		}
		table += "</tbody></table>";
		return table;
	},
} 
```

### Current Behavior

For each series.name past series[0], it adds a comma "," to the div which contains the table. A comma is also added for each series.data past series[0].
This is represented by a long line of commas above the table itself.

### Expected Behavior

A table without the unexpected commas above it.

### Environment

```markdown
- OS: Windows 10
- Browser: Firefox 104.0.2
- Framework:
```

### Any additional comments?

Needed a dynamic table for when an unknown amount of series are present.

**Comment by plainheart** [comment]
`series.map` will return a new array, you need to use `join` function to get the string.
