### ISSUE TITLE
[Feature] Legend selectedMode to keep at least one active

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#17678]
### What problem does this feature solve?

When all series are disabled from legend chart looks empty and even y-axis disappears.
https://echarts.apache.org/examples/en/editor.html?c=line-stack - disable all series from legend
![line-stack](https://user-images.githubusercontent.com/3032714/191447565-4280920b-7bba-4047-b6b1-6a13053cf96b.png)

### What does the proposed API look like?

Add one more option to selectedMode(inside legend) which disables unselecting last active series.
legend: {
  selectedMode: 'atLeastOne'
}

**Comment by vivek-kandhvar** [comment]
This will be very useful if done!
