### ISSUE TITLE
[Feature] Apache ECharts Node.js Export Server ( Server Side Rendering , HTTP Server)

### ISSUE THREAD

**Issue by xiaomaiyun** [apache/echarts#17681]
### What problem does this feature solve?

Apache ECharts Node.js Export Server ( Server Side Rendering , HTTP Server)

Convert Apache ECharts charts to static image files.

This is a node.js application/service that converts [Apache ECharts](https://echarts.apache.org/) charts to static image files. It supports PNG, JPEG, SVG, and PDF output; and the input can be either SVG, or JSON-formatted chart options.

The application can be used either as a CLI (Command Line Interface), as an HTTP server, or as a node.js module.

It has been implemented here：
[Apache ECharts Node.js Export Server](https://github.com/xiaomaigou/echarts-export-server)
https://github.com/xiaomaigou/echarts-export-server

### What does the proposed API look like?

It has been implemented here：
[Apache ECharts Node.js Export Server](https://github.com/xiaomaigou/echarts-export-server)
https://github.com/xiaomaigou/echarts-export-server

**Comment by Ovilia** [comment]
Thanks for your contribution! If this issue is try to let more people know about the repo, please close this one and add a line to [ecomfe/awesome-echarts](https://github.com/ecomfe/awesome-echarts).
