### ISSUE TITLE
How to draw bar charts with apache echarts as below screenshot?

### ISSUE THREAD

**Issue by zubair-saif** [apache/echarts#17689]
### What problem does this feature solve?

Hi am trying achieve below screenshot chart functionality with dataset but unable to draw it with date on x axis and trial id on Y axis as below chart example.

this is my sample code which am trying to draw as screenshot

https://echarts.apache.org/examples/en/editor.html?c=bar-y-category

**sample screenshot which actually i want to draw**

![image](https://user-images.githubusercontent.com/11749126/191947894-42983477-c8af-4a9f-8049-9f218cc0d673.png)

### What does the proposed API look like?

```
var option = {
  dataset: {
    source: [
      ['score', 'amount', 'product','date'],
      [89.3, 58212, 'NCT1928282','10-01-2021'],
      [57.1, 78254, 'NCT1928283','11-10-2022'],
      [74.4, 41032, 'NCT1928284','12-10-2000'],
      [50.1, 12755, 'NCT1928284','12-10-2002'],
      [89.7, 20145, 'NCT1928284','12-10-2003'],
      [68.1, 79146, 'NCT1928284','12-10-2024'],
      [19.6, 91852, 'NCT1928290','12-10-2015'],
      [10.6, 101852, 'NCT1928251','12-10-2011'],
      [32.7, 20112, 'NCT192820','01-10-2010']
    ]
  },
  xAxis: {
    type:'category',
  // formatter:'{c}'
  },
  tooltip:{},
  yAxis: { type: 'category'},
  series: [
    {
      type: 'bar',
      encode: {
        // Map "amount" column to x-axis.
        x: 'date',
        // Map "product" row to y-axis.
        y: 'product'
      }
    }
  ]
};
```

**Comment by zubair-saif** [comment]
@BrianGilbert

**Comment by zubair-saif** [comment]
@Ovilia
@kant 
@bantic 
@leeight

**Comment by Ovilia** [comment]
Bar series don't support two categories.
