### ISSUE TITLE
[Bug] registerMap不能加载svg外联样式

### ISSUE THREAD

**Issue by wangchao18654941093** [apache/echarts#17685]
### Version

5.2.2

### Steps to Reproduce

 [在线查看](https://www.isqqw.com/viewer?id=35341)

 

### Current Behavior

svg的样式没有加载上：
![image](https://user-images.githubusercontent.com/107595890/191724518-d79148ee-e319-4464-890d-0c035de7b770.png)

### Expected Behavior

这个是svg应该的样式：
![image](https://user-images.githubusercontent.com/107595890/191724609-70adbcba-6bb9-4fcb-97af-0c9a6e5ea306.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

echarts.registerMap 加载svg时感觉没有解析 svg标签上的class所以导致外联样式（style标签）没有加载成功。

**Comment by Ovilia** [comment]
Try [this](https://github.com/doom-goober/svg_style_attribute).

**Comment by wangchao18654941093** [comment]
> Try [this](https://github.com/doom-goober/svg_style_attribute).

I tested with this plug-in, and the converted svg does not work properly

**Comment by poolKylin** [comment]
试试在保存svg时，css样式那里选择“演示文稿属性”

**Comment by wangchao18654941093** [comment]
![image](https://user-images.githubusercontent.com/107595890/192206552-2e5e748a-c233-42fe-9ec7-3d67987d87c5.png)
 我已在官方文档中找到了说明，目前版本不支持外联样式
