### ISSUE TITLE
Sparkline support

### ISSUE THREAD

**Issue by xavimarquez** [apache/echarts#17693]
### What problem does this feature solve?

Sparkline is defined as "a very small line chart, typically drawn without axes or coordinates. It presents the general shape of the variation (typically over time) in some measurement".

This feature is supported by many chart libraries but not for echarts.

![image](https://user-images.githubusercontent.com/85179694/192133511-3545dff5-220c-49fd-9e49-ec49cbd0a93e.png)

Sparklines was asked also in https://github.com/apache/echarts/issues/12714  and the provided workaround was using normal charts.

This is not a viable solution. If you try to insert 50 charts in a html table, you will get a very poor performance. In my case, it takes 4 seconds to load the page.

The idea is to show a simple chart, and using the "normal" charts, with advanced features, even you do not use them, it is not viable because of the performance.

See the support for sparklines for Highcharts: https://www.highcharts.com/demo/sparkline and try to do the same with echarts. It is not possible, it takes several seconds.

I come from Apex charts and also they support sparklines:
https://apexcharts.com/javascript-chart-demos/sparklines/basic/

Sparklines do not need advanced features in axis, colors, ... just a very basic chart, but with a good performance.

### What does the proposed API look like?

In the library that I have been working on until now, sparkline chart is just a option in the configuration of the chart:

```
chart: {
    sparkline: {
        enabled: true,
    }
}
```

sparkline hides all the elements of the charts other than the primary paths. Helps to visualize data in small areas

![image](https://user-images.githubusercontent.com/85179694/192133562-851c2e52-212b-4cbe-bf0c-0c6ada136145.png)

**Comment by Peeja** [comment]
> This is not a viable solution. If you try to insert 50 charts in a html table, you will get a very poor performance. In my case, it takes 4 seconds to load the page.

Is this true for both canvas and SVG charts?

**Comment by Ovilia** [comment]
I'd suggest using SSR to generating SVG (with animation since v5.3 and with hover effect since v5.5) so that no chart instance should be perserved and thus no memory concern for multiple charts.

**Comment by DavidMarquezF** [comment]
But using SSR would not be viable in a dynamic data environment right? How would you suggest to approach it then?

**Comment by dberardo-com** [comment]
Any news here?
