### ISSUE TITLE
[Feature] : 针对图标中柱状图标线的 自定义内容

### ISSUE THREAD

**Issue by namewl** [apache/echarts#17703]
### What problem does this feature solve?

如下图所示 
设置柱状图的多条标线 每条标线的标签自定义内容和样式
![image](https://user-images.githubusercontent.com/58961765/192421909-c8e768c9-a414-4b9f-a966-f6ecf8cce884.png)

### What does the proposed API look like?

series 的 markLine属性

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-line.markLine.label.rich 应该是可以实现这个效果的

**Comment by joker1sb** [comment]
[Pussy888](https://sbbth.com/pussy888/)Pussy888

Joker123 logo
[JOKER123](https://sbbth.com/joker123/)

Relax Gaming
[RELAX GAMING](https://sbbth.com/relax-gaming-2/)

Starvegas-sbbth
[STAR VEGAS](https://sbbth.com/starvegas/)

betway-logo
[BETWAY SEXY GAMING](https://sbbth.com/betway-sexy-gaming/)

sexy-gaming-logo
[SEXY BACCARAT](https://sbbth.com/sexy-baccarat/)

pg-logo
[PG SLOT](https://sbbth.com/pg-slot/)

gclub
[GCLUB](https://sbbth.com/gclub/)

logo-sagaming
[SA GAMING](https://sbbth.com/sa-gaming/)

ufabet-logo
[UFABET](https://sbbth.com/ufabet/)

[NOLIMIT CITY](https://sbbth.com/nolimit-city/)

[PRAGMATIC PLAY](https://sbbth.com/pragmatic-play/)
PRAGMATIC PLAY
