### ISSUE TITLE
[Bug] Is there any way to reduce font size with responsive for speedometer gauge value.

### ISSUE THREAD

**Issue by sanketinx** [apache/echarts#17704]
### Version

5.4

### Steps to Reproduce

https://echarts.apache.org/examples/en/editor.html?c=gauge 

### Current Behavior

Value 9.8 overlapping on the gauge value. 

https://ibb.co/R0q0mNW 

### Expected Behavior

Need to reduce font size according to the screen responsive width.

### Environment

```markdown
- OS: linux 
- Browser: All 
- Framework: Codeigniter 3.1.1
```

**Comment by Ovilia** [comment]
This cannot be responsive by itself but you can check (like whether n.toString().length > 2) before `setOption` and change the font size in the option.

**Comment by sanketinx** [comment]
Thanks for the reply but it is not working for the 2-digit floating values. Is there any editor example that can be helpful? Thanks again. Waiting for reply.
