### ISSUE TITLE
[Bug] minShowLabelAngle not working properly on 5.4

### ISSUE THREAD

**Issue by wilnerjs** [apache/echarts#17719]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=pie-simple

### Steps to Reproduce

1- add label > position = 'inside'
2- add minShowLabelAngle = 100

### Current Behavior

The label move but still showing inside the chart

### Expected Behavior

All labels hidden, except the label of the largerst piece of the pie.

### Environment

```markdown
- OS: windows 10
- Browser: chrome
```

### Any additional comments?

Working  properly on 5.3.0

**Comment by plainheart** [comment]
Hi, sorry about this. Please refer to #17712.
