### ISSUE TITLE
[Bug] RadialGradient backgroundColor can't render by svg

### ISSUE THREAD

**Issue by zhiqingchen** [apache/echarts#17735]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bubble-gradient

### Steps to Reproduce

1. add RadialGradient background

```js
option = {
  backgroundColor: new echarts.graphic.RadialGradient(0.3, 0.3, 0.8, [
    {
      offset: 0,
      color: '#f7f8fa'
    },
    {
      offset: 1,
      color: '#cdd0d5'
    }
  ]),
}
```

2. use svg render
3. result

### Current Behavior

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1876158/194699888-a3fa5b8c-55f7-461e-ab0a-6a0d05e10ee9.png">

### Expected Behavior

<img width="834" alt="image" src="https://user-images.githubusercontent.com/1876158/194699900-ccb5d0e7-d392-4f7c-90c6-675a7f1fa2ff.png">

### Environment

```markdown
- OS:macOS Monterey
- Browser:Chrome 96.0.4664.55
- Framework:no
```

**Comment by plainheart** [comment]
SVG renderer only supports setting a color string as the background now. This feature is in progress and may be supported in future releases. See also the [svg-background](https://github.com/ecomfe/zrender/tree/svg-background) branch.

**Comment by koliharesh** [comment]
Hello Sir/Madam, I would like to contribute in your project to solve this issue.
