### ISSUE TITLE
[Bug] The behavior of axisPointer does not conform to normal people's feelings when both the x-axis and the y-axis are continuous axes

### ISSUE THREAD

**Issue by kitee0325** [apache/echarts#17737]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRQIa54AKwE0YApgE52w8AC2AB3ImF4BXbrAbo8fCN0KwA2hXSp0OwZQC2AI2AAbAMoQAXtyIAmAAzld6ACaMwjIhuc61ARnsAOkdYAA5ggBYAXScfdXD7AHZSWAA2QIBOAFYYzWd_AGZglMTArNDcuPUM4KyU8NC_Srj_P2KwwIKC5p9_CPbS1NSe_L8iiJT0xpHdfyCQ9K6Z3z9-kPCM4djev1syycDQ22X0NRq_OthS4-3Rtsvrk_Ui-wKU_ttu29ndwNsSw5fPKzPb2f6wfoRRJPfy1FJFJbfXxrS79TYw9KvAG2aJI06_BZ_LbAlag-qHXEk06leyhFJZQ43KnqBlg-mBVIVEnLMCUEA2WAAcjwAGN3DxeILbsQKFEUMQANxAA

### Steps to Reproduce

1.Move the mouse on the chart 
2.Observe the changes in the scatter

### Current Behavior

Two points close to the two axisPointers are highlighted instead of one point close to the mouse position

### Expected Behavior

only one point close to the mouse position is highlighted

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by li942475402** [comment]
It seems that the behavior of axisPointer when both the x-axis and the y-axis are continuous axes is the superposition of the behavior of a single continuous axis, but in fact, the highlight reference at this time should be the intersection point instead of a single axis

**Comment by Ovilia** [comment]
This is probably not a bug. Consider if there are two points with the same x: `[10, 10], [10, 20]`. If the vertical axisPointer is at the x position 10, there is no reason to highlight only one of them.

**Comment by li942475402** [comment]
> This is probably not a bug. Consider if there are two points with the same x: `[10, 10], [10, 20]`. If the vertical axisPointer is at the x position 10, there is no reason to highlight only one of them.

![20221010232104](https://user-images.githubusercontent.com/30969393/194900676-7385976a-fe20-4ffb-abbf-395ebf0ffb12.png)

**Comment by retnag** [comment]
I agree with @li942475402 , I'd expect the points close to BOTH axis to be highlighted, not the points close to ANY single one of the axes.
