### ISSUE TITLE
[Bug] Scatter has poor redraw with large number of Points

### ISSUE THREAD

**Issue by mountainash** [apache/echarts#17744]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/elegant-browser-4bo1ib?file=/App.tsx

### Steps to Reproduce

1. Create a `scatter` type chart with many data points (greater than 3000)
2. Make the points change over x-axis (timescale)

### Current Behavior

You will see a "banding" effect to the right side of the chart as it doesn't complete the redraw of all the dots before starting the next redraw.

### Expected Behavior

The chart should redraw nicely.

This effect is not noticeable with less points or changing the chart type to `effectScatter`.

### Environment

```markdown
- OS: macOS Monterey v12.6
- Browser: Chrome version 105 (latest) & Safari v16 (latest)
- Framework: Both using echarts-for-react (and directly)
- Hardware: high spec'ed laptop (Apple M1 MBP - 32GB RAM)
```

### Any additional comments?

Attached to videos to easily see the difference better scatter and effectScatter.

https://user-images.githubusercontent.com/27637/194832342-0e6e3195-5345-42fe-8ef2-42455980efbf.mov

https://user-images.githubusercontent.com/27637/194832355-7d47fa06-6339-4041-9d0d-00e4808a2a0b.mov

**Comment by Ovilia** [comment]
This is because when data amount is large, ECharts use progressive rendering. You can set `progressiveThreshold: 10000,` to be a large number to disable it.

**Comment by mountainash** [comment]
@Ovilia Thank you for the quick reply... is there an explanation [you can link to] that details what "progressive rendering" means in an ECharts sense?

**Comment by joker1sb** [comment]
[Pussy888](https://sbbth.com/pussy888/)Pussy888

Joker123 logo
[JOKER123](https://sbbth.com/joker123/)

Relax Gaming
[RELAX GAMING](https://sbbth.com/relax-gaming-2/)

Starvegas-sbbth
[STAR VEGAS](https://sbbth.com/starvegas/)

betway-logo
[BETWAY SEXY GAMING](https://sbbth.com/betway-sexy-gaming/)

sexy-gaming-logo
[SEXY BACCARAT](https://sbbth.com/sexy-baccarat/)

pg-logo
[PG SLOT](https://sbbth.com/pg-slot/)

gclub
[GCLUB](https://sbbth.com/gclub/)

logo-sagaming
[SA GAMING](https://sbbth.com/sa-gaming/)

ufabet-logo
[UFABET](https://sbbth.com/ufabet/)

[NOLIMIT CITY](https://sbbth.com/nolimit-city/)

[PRAGMATIC PLAY](https://sbbth.com/pragmatic-play/)
PRAGMATIC PLAY
