### ISSUE TITLE
[Bug] Custom series Zoom display error

### ISSUE THREAD

**Issue by a949066041** [apache/echarts#17742]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/s/stoic-cdn-wmv5n5?file=/src/index.js

### Steps to Reproduce

1. Narrow it down
2. The red disappears
3. Recovery range

### Current Behavior

Recovery range blue is gone

### Expected Behavior

The display is normal when the drag is resumed。

### Environment

```markdown
- OS:window
- Browser: Chrome  105.0.5195.127
- Framework:
```

**Comment by plainheart** [comment]
It seems the blue item didn't disappear but was covered by the red one.

**Comment by a949066041** [comment]
I think Initialize and drag and drop restore should be the same effect.

**Comment by plainheart** [comment]
As per the documentation, the custom series doesn't recognize the `z` option in the `data` items. You may try to use the [`z2`](https://echarts.apache.org/option.html#series-custom.renderItem.return_rect.z2) option provided by the `renderItem` function. Refer to this [demo](https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAQIZg0BawwAtiUhVTgE4THJV02AGZgSAcgDMAUnGV06XjgAWY2FNnyFYUBICMmwbABGwMDrbq9ABkMLYAYxj0I0ADI1jWDCTDcArlhUnOgAHgCCoRAAzuxGYACeIFgSkCxYckYsrhIATNZ6ABwAtNYluQCssNbWRDV11pn2LDSheQUlZcW5AOzVtfU1TdpYoWAAyonYcfboThjA3BIAxMLWa2viRqTBWgmRMTMKtPQkANriYFjRYOIAulroV2OTCdMCs47AC0vqq-sArb2HboEKwaJYXjXc5GVCfGgAN2AfA8XgwAHkEZCMDQQL4AlhHtokil1A5_DdWMN7BDsA4rgQALLAAik8TRVw4bDUhQ4tEeBLAfxqOGfWDKPhYTHY3EkYQ0DAQoygolCXD4AgACWAWO4blcAGs5QqIarYNwNZCAJJXSzCfzQelQOAAChANG4NBY0XIsFxEAAlB8xQiPY46LhFgkrYRRgg_SAIAA6UMYQIu6wBgDcyoUoe44Po3DA8f9SaciwILrOZdT6b0Ad9DgjOCjMdZoTu2dz6HzsA1pcT5eY3CrNaHdawLtyjfDV1b3Gjsc73bFsD7yiwEBUJcQuQALDme-asGB_Nw4KK14lkhILfSeZ9ospcaSsA4X8XokmeLiJQ5ywwCAQAAJXfMAACEEjA-kXWPewrzXBQ2kLD0wDOawHng2YEhIG40LOPQ7lgYpxS3HdYAAelgXIzTXAB3PgwGUEgNQw4jSPw4t2LosVN23VQSH4ndsJVUTgyQ5CSHdT1vWHStxgSb9Ql4z5cNgGSvW_CtR0U78ElU2ZGIIZjpI9LT5N0pSk2M5jDPsYTBI08y5J0gg9KTRywHEkEkMbbCbjeUky0C7AXX8ySAC9chIWsFXTSQA2PUgc0-MF7HwJxWSOT4UMI31ciwtd1OsXN0uOOgaBhNdEM-CBbVed4kC-H47ywAhxFgcrPmgL02SuG49EfWZJ3OPRfXEfIilKcoqkGAZGgmqbOlmmjJCICoAE4Ns2uRqjuZLeMo6iThoG0sBYY9atmXr0lSa4wFyYb7FG2B8vUZaZu6OaYvmvbJo6L7Kmqda_t9GwahqA6118-xoYUXyDpSoA).

**Comment by a949066041** [comment]
Thanks. I get.
