### ISSUE TITLE
[Bug] What is the difference between these two references?

### ISSUE THREAD

**Issue by bbhxwl** [apache/echarts#17759]
### Version

5.4.0

### Steps to Reproduce

The following methods can be used.

```
import {init} from 'echarts'
let myChart=init(document.getElementById("m"))
```
The following methods cannot be used. I don't know why? Isn't it the same?

```
import c from 'echarts'
    let myChart=c.init(document.getElementById("m"))

```

### Current Behavior

 The following methods can be used.

```
import {init} from 'echarts'
let myChart=init(document.getElementById("m"))
```
The following methods cannot be used. I don't know why? Isn't it the same?

```
import c from 'echarts'
    let myChart=c.init(document.getElementById("m"))

```

### Expected Behavior

The following methods can be used.

```
import {init} from 'echarts'
let myChart=init(document.getElementById("m"))
```
The following methods cannot be used. I don't know why? Isn't it the same?

```
import c from 'echarts'
    let myChart=c.init(document.getElementById("m"))

```

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Since ECharts v5, the default import is no longer supported. Please refer to the [v5 upgrade guide](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/#importing-echarts).
