### ISSUE TITLE
[Bug] The x-axis of the pie chart displays abnormally

### ISSUE THREAD

**Issue by fuzi1996** [apache/echarts#17754]
### Version

5.4.0

### Link to Minimal Reproduction

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-line-chart-forked-vy8prx)

### Steps to Reproduce

- 1. `yAxis.axisLabel.lineHeight` value >= 34

![image](https://user-images.githubusercontent.com/21113919/195312492-cd6eada6-0dd3-47e0-ad8e-8f9ed901109c.png)

- 2. `yAxis.axisLabel.lineHeight` value <= 33

![image](https://user-images.githubusercontent.com/21113919/195312777-857471a1-9e26-4739-9d87-67f24be4f559.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/21113919/195312492-cd6eada6-0dd3-47e0-ad8e-8f9ed901109c.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/21113919/195312895-86d0568a-8b8e-4e95-bd22-0a23e5788af5.png)

### Environment

```markdown
- OS: `windows 10`
- Browser: `Microsoft Edge 版本 106.0.1370.37 (正式版本) (64 位)`
```

**Comment by fuzi1996** [comment]
我注意到是在 [fixMinMaxLabelShow](https://github.com/apache/echarts/blob/672c7240b74e487c084aa4075466c8b87dd7395b/src/component/axis/AxisBuilder.ts#L513) 时,第一个和最后一个`label`被设置为`ignore=true`
这里有一个判断 [shouldShowAllLabels](https://github.com/apache/echarts/blob/672c7240b74e487c084aa4075466c8b87dd7395b/src/coord/axisHelper.ts#L370) 因为 `getOptionCategoryInterval` 获取到的是 `auto` 而无法跳过
是不是少判断了这种情况

**Comment by Ovilia** [comment]
When `lineHeight` is to large to be displayed, `axisLabel.show = 'auto'` means it will hide the label if necessary. So this doesn't seem to be a bug to me.

**Comment by fuzi1996** [comment]
> When `lineHeight` is to large to be displayed, `axisLabel.show = 'auto'` means it will hide the label if necessary. So this doesn't seem to be a bug to me.

确实，axisLabel.[interval](https://echarts.apache.org/en/option.html#xAxis.axisLabel.interval)= 'auto' means it will hide the label if necessary.
