### ISSUE TITLE
[Bug] node服务端配置项图形组件渲染时报错

### ISSUE THREAD

**Issue by loneynoob** [apache/echarts#17766]
### Version

echarts@5.4.0

### Steps to Reproduce

在配置项上添加图形组件后（如下图示例）
![image](https://user-images.githubusercontent.com/32814066/195749481-84933eda-a971-4121-a173-a603af74242b.png)
在node下运行会报错

### Current Behavior

由于nodejs没有原生的Image对象，渲染时会产生如下错误
![QQ图片20221014102618](https://user-images.githubusercontent.com/32814066/195750005-042d7744-a59b-4af1-b7cb-32fb482cba15.png)

### Expected Behavior

希望可以提供node下没有Image对象的解决方法

### Environment

```markdown
- OS:Windows
- Browser:
- Framework:node.js v16.13.1
```

**Comment by plainheart** [comment]
你应该通过 [`setPlatformAPI`](https://echarts.apache.org/zh/api.html#echarts.setPlatformAPI) 重写自己的 image loader 实现。

```js
echarts.setPlatformAPI({
  loadImage(src, onload, onerror) {
     // 加载图片
  }
})
```
