### ISSUE TITLE
[Bug] markpoint textBorderColor not working when set label color

### ISSUE THREAD

**Issue by stanzah** [apache/echarts#17761]
### Version

5.4.0

### Link to Minimal Reproduction

https://jsfiddle.net/stanzah/1yzfteba/13/

### Steps to Reproduce

```
markPoint: {
      	label: {
        	color: '#fff',
                textBorderColor: '#000',
        },
},
```

### Current Behavior

textBorderColor not working

### Expected Behavior

textBorderColor working

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Please also set the [`textBorderWidth`](https://echarts.apache.org/option.html#series-line.markLine.label.textBorderWidth) to be a value greater than `0`.
