### ISSUE TITLE
lineStyle attribute in series could not set with function

### ISSUE THREAD

**Issue by Virgil-N** [apache/echarts#17767]
### Version

last

### Steps to Reproduce

```ts
option = {
  series: [
    {
      type: 'lines',
      symbol: 'none',
      lineStyle: {
        color: function (params: any) {
          return 'blue';
        }
      },
      data: data
    }
  ]
};
```

### Current Behavior

Error: Type '(params: any) => string' is not assignable to type 'ZRColor | undefined'.

### Expected Behavior

With no error.

### Environment

```markdown
- OS:windows 11
- Browser: edge last version
- Framework: react 18
```

### Any additional comments?

Just could not compile.

**Comment by plainheart** [comment]
It seems the generic type `<CallbackDataParams>` is missing in [`LinesStateOption`](https://github.com/apache/echarts/blob/master/src/chart/lines/LinesSeries.ts#L114). You are welcome to open a PR to fix this issue.
