### ISSUE TITLE
[Bug] 关系图option的itemStyle的color属性值不支持函数，和文档说明不符。

### ISSUE THREAD

**Issue by hetuee** [apache/echarts#17770]
### Version

5.4.0

### Steps to Reproduce

在官方网站的实例的实时代码编辑中，对关系图进行了自定义，发现option、series、itemStyle的color属性值不支持函数，但文档中写明color属性支持函数。
[关系图在线编辑：](https://echarts.apache.org/examples/zh/editor.html?c=graph-label-overlap)
[关于itemStyle的color属性说明：](https://echarts.apache.org/zh/option.html#series-graph.itemStyle.color)
添加的属性：
        itemStyle:{
           color: function(params) {
                return “#ff0000ff”;
            }
        },
添加后，关系图节点颜色变为黑色
### Current Behavior

关系图option的itemStyle的color属性值不支持函数，和文档说明不符。

### Expected Behavior

请及时修复。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by susiwen8** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFU0DA4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4QxW07ThY0uU59NzAAO4TUzgrsLLNsDgGHjhdbZ1LsGmUTBDsTLixsJS07CMblAC6s-jHp-cOt0-iY0gAWQRmSw_Pb_HAAGXmi2Wh3QADMYGAev0CAAmSx7A7NHy0dJ7LLk4jQMZ-ABywAMODMTVR6FIBAAzNZfs08pzrJSiYdsqzYNTFHSGUzcSzWezYAAObmU9B82BcgmsoXNEWs8WSxnq2Wo-XmQYq2Bq0wCrU8imisU0qj0w1g42HU3mh1qqya1H8PYww4AemDsCw7gA1qlrkHmhHoNGyazdaj6DUHiYbBawG9ThQzHbiK0gVhsaDzJD8XHWZUFldU6y1ptttMLdrDgmzvlcCiHbANhADGBuARKxb0EwtAA3HDQFIxywAOlx7cFRcbzXTWiYBul7uaufY-edUuZRfQdeRhH78XWWwwO3bF_D7m7eV7N_7U_Ys_n9EXFc11tSlN1WDNd1PQ1TAPHIjxPF4XSZDk-BAlMLW3TMoP3F94JwAtKCQo111AjCIL3WAZVwvN8Ow2A3RI9CHUwyDELPGDqOPWi2NdVD_UDHkIF8RQuh7EwwNgJhxGAdgCAACgASgQAA-F4AGI0TRaxrE0vicg7V951Ej9xMpUBaDufICGXABOItB2HUdKKLH8_wXazCXKAN0C-FB-AAbiAA

Works for me
