### ISSUE TITLE
How to overall scale graph chart? 如何整体缩放关系图

### ISSUE THREAD

**Issue by Yijx** [apache/echarts#17775]
### Version

5.3.3

### Steps to Reproduce

关系图默认可以通过scaleLimit，roam，nodeScaleRatio等参数控制缩放，但是如何做到类似浏览器缩放的整体缩放效果？
例如
graph chart can use parameters such as scaleLimit，roam，nodeScaleRatio for scaling by default, but how to achieve an overall zoom effect similar to browser zoom?
e.g.
<img width="1701" alt="Snipaste_2022-10-16_22-13-00" src="https://user-images.githubusercontent.com/30200703/196040387-264f71cf-587d-431c-9bb0-ece29a3c2b5f.png">
<img width="1792" alt="Snipaste_2022-10-16_22-14-47" src="https://user-images.githubusercontent.com/30200703/196040393-a736e743-f7f3-4486-b781-0f1e196f20b1.png">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Yijx** [comment]
问题反馈2： 在配置links下的label的show为true是,此时开启labelLayout.hideOverlap,会出现线上文字无法跟随拖动的情况，例子可以使用https://echarts.apache.org/examples/zh/editor.html?c=graph-simple添加labelLayout后直接复现

**Comment by Yijx** [comment]
问题反馈3：如何配置label的z或者z2或者zlevel？在开启线上文字之后，根据渲染先后顺序，会导致文字的层级在原点之上，发生重叠
<img width="987" alt="image" src="https://user-images.githubusercontent.com/30200703/196099523-b059d370-2ca3-4e58-8c1f-6e1f4140f568.png">
通过zr.storage.getDisplayList(true, true),然后对TSpan元素进行attr('z',99)或者attr('z2')或者attr('zlevel')均不生效

**Comment by helgasoft** [comment]
Did you try the obvious ``` dataZoom: {inside: {type: 'inside'}}``` ?
Without Minimal Reproduction code it is hard to debug...

**Comment by Yijx** [comment]
> dataZoom: {inside: {type: 'inside'}}

it can not work. about Minimal Reproduction code, can out any code in https://echarts.apache.org/examples/zh/index.html#chart-type-graph, i think it is a common problem.
when i zoom a graph chart, it is not global scale(scale all canvas), just scale some part,for example, i can not scale label text or lineWith(border).
so,Is there a way to scale the entire canvas？(It's like scaling group in zrender)

**Comment by plainheart** [comment]
@Yijx Hi, you can get the current zoom of the graph chart and scale it manually. Please refer to this [demo](https://echarts.apache.org/examples/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFU0DA4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4QxW07ThY0uU59NzAAO4TUzgrsLLNsDgGHjhdbZ1LsGmUTBDsTLixsJS07CMblAC6s-jHp-cOt0-iY0gAWQRmSw_Pb_HAAGXmi2Wh3QADMYGAev0CAAmSx7A7NHy0dJ7LLk4jQMZ-ABywAMODMTVR6FIBAAzNZfs08pzrJSiYdsqzYNTFHSGUzcSzWezYAAObmU9B82BcgmsoXNEWs8WSxnq2Wo-XmQYq2Bq0wCrU8imisU0qj0w1g42HU3mh1qqya1H8PYww4AemDsCw7gA1qlrkHmhHoNGyazdaj6DUHiYbBawG9ThQzHbiK0gVhsaDzJD8XHWZUFldU6y1ptttMLdrDgmzvlcCiHbANhADGBuARKxb0EwtAA3HDQFIxywAOlx7cFRcbzXTWiYBul7uaufY-edUuZRfQdeRhH78XWWwwO3bF_D7m7eV7N_7U_Ys_n9EXFc11tSlN1WDNd1PQ1TAPHIjxPF4XSZDk-BAlMLW3TMoP3F94JwAtKCQo111AjCIL3WAZVwvN8Ow2A3RI9CHUwyDELPGDqOPWi2NdVD_UDHkuy6HsTDA2BQFoO58gIZcAE4i0HYdR0oosfz_BcZMJcoA3QL4UH4ABuFAUFwMBYB_dg5zAAAtMRFAQMwjMUPIAGFuDeMAlxgAAKShii4bgACVRkUZ5vJwABKBAAD4vyYGB6DM3o7IcnAl2S4BFCM9AIDRWBvIyxQotTCyrNszLYAAKkQQrsuIeLoHTXAlywYAPF8_yeFgQrnlK6AbLsiK6vQZy3I8pcEjACJwCcbzN0wT8xPoDR2l8cgqBcrRLP62Byvs-EcFnK5KFgABqcytrKuzCR5BIkhSZNUTEy8kQbCdYAxfrywIUwwSqi73iuzLnwtOFEXrPsHU-rEQTxSx_r6gbgYdHT-MOPScn4IaBH0oagA).

**Comment by helgasoft** [comment]
yep, @plainheart is one step ahead, while I was typing  :-)
the right code ...and to zoom for the **edges** add ```lineStyle: { width: 2.5 * currentZoom }```

**Comment by Yijx** [comment]
> @Yijx Hi, you can get the current zoom of the graph chart and scale it manually. Please refer to this [demo](https://echarts.apache.org/examples/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFU0DA4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4QxW07ThY0uU59NzAAO4TUzgrsLLNsDgGHjhdbZ1LsGmUTBDsTLixsJS07CMblAC6s-jHp-cOt0-iY0gAWQRmSw_Pb_HAAGXmi2Wh3QADMYGAev0CAAmSx7A7NHy0dJ7LLk4jQMZ-ABywAMODMTVR6FIBAAzNZfs08pzrJSiYdsqzYNTFHSGUzcSzWezYAAObmU9B82BcgmsoXNEWs8WSxnq2Wo-XmQYq2Bq0wCrU8imisU0qj0w1g42HU3mh1qqya1H8PYww4AemDsCw7gA1qlrkHmhHoNGyazdaj6DUHiYbBawG9ThQzHbiK0gVhsaDzJD8XHWZUFldU6y1ptttMLdrDgmzvlcCiHbANhADGBuARKxb0EwtAA3HDQFIxywAOlx7cFRcbzXTWiYBul7uaufY-edUuZRfQdeRhH78XWWwwO3bF_D7m7eV7N_7U_Ys_n9EXFc11tSlN1WDNd1PQ1TAPHIjxPF4XSZDk-BAlMLW3TMoP3F94JwAtKCQo111AjCIL3WAZVwvN8Ow2A3RI9CHUwyDELPGDqOPWi2NdVD_UDHkuy6HsTDA2BQFoO58gIZcAE4i0HYdR0oosfz_BcZMJcoA3QL4UH4ABuFAUFwMBYB_dg5zAAAtMRFAQMwjMUPIAGFuDeMAlxgAAKShii4bgACVRkUZ5vJwABKBAAD4vyYGB6DM3o7IcnAl2S4BFCM9AIDRWBvIyxQotTCyrNszLYAAKkQQrsuIeLoHTXAlywYAPF8_yeFgQrnlK6AbLsiK6vQZy3I8pcEjACJwCcbzN0wT8xPoDR2l8cgqBcrRLP62Byvs-EcFnK5KFgABqcytrKuzCR5BIkhSZNUTEy8kQbCdYAxfrywIUwwSqi73iuzLnwtOFEXrPsHU-rEQTxSx_r6gbgYdHT-MOPScn4IaBH0oagA).

thanks, but I tried this method before.If i use this way, i must set a new option to echarts,but if i use force layout and not set x and y(use default position),echarts will recalculate the position.This can cause uncontrolled movement of the node
[example](https://echarts.apache.org/examples/zh/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFUAGbA7Ew4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4oxW0XThY0uU59NzAAO7TszjrsLJtsA1NJqgAkNc37DggGliMMAQATNY2KDc3xbQAbhB8gRLAA6UzCb7XHAGDw4AAyOE8YG46QAzCNYAA2awAXQhkMq1WiAEEFModAQ6rQnvMvpCAPT02DuQFwqo1CiwShnZplSHHNrQ2G9To9VawNKUJgQJq4WJc2jscbbSh4w5CnAi7p9QYmNIAFkEZksapOGrZy3F2ROpxgYH6QzelkOApyPlo6UOWS9xGgkz8ADlgAYcGZWjbYD7XW1rRG_YpA8HQ69wxGowscrGbfHEyHYKjUyd0z6sycc1Qg3n9YWclHDqa2ozYFh3ABrVIShs5FvQdueiOltr0GrnYEZtpgRWwzngn3tUU6x0S8xG95dm2VS1rCMbLa7DD7OdHcfd9ya_K4bc79DbCAGZEEFdH9BMLR_REpDug15H_jFgdHsOWjNBWSawCmJ65FOOCcpQlahqYNZtJuKxXtemw7Hscy_pB6A9ueeSXoQ14vm-H70F-II_tef4RtGmaASOIFcvBYa4Rg0GwaxBb_jag4bExubJkhOSTuw06gXmPF0ZB_HEEBo4sWBEFHmJElKVWfAySWjHAUJbGqZxkmhtWdYnOueFnr0F4XD6oC0NKQKwKCACckG3veKLgZBr7sO-0CfsCLrlLRsA4ig_AANwoCguBgLAvl3NAYAAFpiIoCBmNFih5AAwtwipgCCMAABSUL8PAAEoTIo8olTgACUCAAHzEQlMD0PFAzpZlOAgt1wCKNF6AQHUsAlQNihNVmiWIqlPUAFSIJNw3EEwHXiH1WDAB4ZUVdwsCTfKs3JWlg0Nat6A5flhUggkYAROATglYOmBEXJ9AaF0vjkFQuVaEl8VnRlCLvuKlCwAA1AlANzcDLrjgkSQpP2fFHihVrPrayUOiYpj6rAC0w0qcPpThR7mksqFtdeDQ47qTqE8TgPwzRZltOFOT8BdAgRRdQA)

**Comment by Yijx** [comment]
> @Yijx Hi, you can get the current zoom of the graph chart and scale it manually. Please refer to this [demo](https://echarts.apache.org/examples/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFU0DA4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4QxW07ThY0uU59NzAAO4TUzgrsLLNsDgGHjhdbZ1LsGmUTBDsTLixsJS07CMblAC6s-jHp-cOt0-iY0gAWQRmSw_Pb_HAAGXmi2Wh3QADMYGAev0CAAmSx7A7NHy0dJ7LLk4jQMZ-ABywAMODMTVR6FIBAAzNZfs08pzrJSiYdsqzYNTFHSGUzcSzWezYAAObmU9B82BcgmsoXNEWs8WSxnq2Wo-XmQYq2Bq0wCrU8imisU0qj0w1g42HU3mh1qqya1H8PYww4AemDsCw7gA1qlrkHmhHoNGyazdaj6DUHiYbBawG9ThQzHbiK0gVhsaDzJD8XHWZUFldU6y1ptttMLdrDgmzvlcCiHbANhADGBuARKxb0EwtAA3HDQFIxywAOlx7cFRcbzXTWiYBul7uaufY-edUuZRfQdeRhH78XWWwwO3bF_D7m7eV7N_7U_Ys_n9EXFc11tSlN1WDNd1PQ1TAPHIjxPF4XSZDk-BAlMLW3TMoP3F94JwAtKCQo111AjCIL3WAZVwvN8Ow2A3RI9CHUwyDELPGDqOPWi2NdVD_UDHkuy6HsTDA2BQFoO58gIZcAE4i0HYdR0oosfz_BcZMJcoA3QL4UH4ABuFAUFwMBYB_dg5zAAAtMRFAQMwjMUPIAGFuDeMAlxgAAKShii4bgACVRkUZ5vJwABKBAAD4vyYGB6DM3o7IcnAl2S4BFCM9AIDRWBvIyxQotTCyrNszLYAAKkQQrsuIeLoHTXAlywYAPF8_yeFgQrnlK6AbLsiK6vQZy3I8pcEjACJwCcbzN0wT8xPoDR2l8cgqBcrRLP62Byvs-EcFnK5KFgABqcytrKuzCR5BIkhSZNUTEy8kQbCdYAxfrywIUwwSqi73iuzLnwtOFEXrPsHU-rEQTxSx_r6gbgYdHT-MOPScn4IaBH0oagA).

Of course, I have a solution to the above problem, that is, to modify the text and border through the zrender instance, which will not cause the ECharts to recalculate the layout,but this brings a new problem. When the mouse moves on the circle to zoom,borderWidth will not computed right.[example](https://echarts.apache.org/examples/zh/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoiYYMCyQQBJEKK1oEALa1IMACIBXTqugBVEABMV-WAEYArAAZLw9PKUqo0AKIMI0AOb6jYE5QCOGu6QTACS0ADyGmCUtrD0OOwQOPQEANpE6KjExGAAniB-Hpw8sZnEWLR5wNFUAGbA7Ew4ZTno9HmKAEbiAMoQAF4mVnE57MC0igRg7Bo4oxW0XThY0uU59NzAAO7TszjrsLJtsA1NJqgAkNc37DggGliMMAQATNY2KDc3xbQAbhB8gRLAA6UzCb7XHAGDw4AAyOE8YG46QAzCNYAA2awAXQhkMq1WiAEEFModAQ6rQnvMvpCAPT02DuQFwqo1CiwShnZplSHHNrQ2G9To9VawNKUJgQJq4WJc2jscbbSh4w5CnAi7p9QYmNIAFkEZksapOGrZy3F2ROpxgYH6QzelkOApyPlo6UOWS9xGgkz8ADlgAYcGZWjb0ICcIpevlcGsIzkeuwQ-wAOoQAzIgimT6J4jJ1MAYXEjSoAGIPnx8_wfa62taI37FIHg6HXuGI3WFjlGzbm62Q7BUZ2Tt2fX2TgOqEGh_rRzk64dTW1GbAsO4ANapCUrnIb6Dbz0Rydteg1c7AnttMCK2Gc8E-9qinWOiXmI3vPc2yqWhP5-Itl2DB9ifI5r33dxNTjC4wPQbZM2zWAPzg2AmC0P5ERSHdQVeMDawjetezA88tGaGc21gDsINyO8cE5ShZ1DUwFzaX8Vn_fNNh2PY5nwmj0APaC8njQgALQjCsPoHCQTwmtxxPEiL3IrkmLDASMDohi1JHBSbVPDZlMHdtWJyW92HvCih10wiaIM4hSMvVTKOosDzMs5y52rG0iOIez2iMqzmNM2iLPooLYHnJcTm_QSoNjETYIjUBaGlIFYFBABOGiEKzFEqJo9D2Ew6BsOBF1r3oJhqXhJRAU4tplFIN4aMUdxgRBcwXXKAjYBxFB-AAbhQFAmBgegwFgAZ2AQWBFDyItuEVMAQXvAAtdgAAoAEphumkEYE2yhFBqBJtm4HAVnlOoNGgJgdFgHbCEuXBJtAHRXlm-bFuW1b6IicAnB24bLggOpHvepxXhBBIkhSNITW256XvoqaxEUWbIZgaHYeSegEZxEEBnRkHLj-RVYBWehZv2ibGloWE_rANQIHoEBCThVmwE2mY5iNXmcF2ukzke8mZogWbLEG5lYAAHkpp4QVwJFuGliAAGp1aRvsxYV2aqbSCAcWGnIwcelYYZgkFfHIWAAEJ4EQW6QzqKCDG1n0LZUGYjqqmr5TSYngEUI0g8UHEhZyXrI3BzaLYmxKlagjM8tgAA-RBzA9iMvbAH3KATuUjX8ipk8QlFcwAKjR4OaP4SPiFrWtLib3agA)
