### ISSUE TITLE
[Bug] 5.x版本对元素使用zlevel分层无效

### ISSUE THREAD

**Issue by Zz1056627814** [apache/echarts#17778]
### Version

5.4.0

### Steps to Reproduce

let rect = new graphic.Rect({
  shape: {x:0,y:0,width: 100 ,height: 100},
  style: {fill:'red'},
  zlevel: 3,
  z:10
})
group.add(rect)
这个代码在4.x可以分层，到5.x版本就不行了。echarts文档中也没有发现相应变化。

### Current Behavior

https://codepen.io/Zz1056627814/pen/zYjXBMv

### Expected Behavior

分为多层canvas

### Environment

```markdown
- OS:win11
- Browser:Chrome 106.0.5249.119
- Framework:Vue@3
```

**Comment by helgasoft** [comment]
Problem may be coming from Vue or your code.
[Here is a working demo](https://echarts.apache.org/examples/en/editor.html?c=graphic-stroke-animation&code=PYBwLglsB2AEC8sDeAoWsDmAnAhiAFhAMYBcya6sApgDZUC2V0YAzmQNoWXKxgCeIKiQDkWKkTDCANF26w6AMzBlhRJmCpZpvUCrXNN02XNgt8eIcgAeJAAxS-dqQHcIAEzD4yARlu3YUvhUEBj4yrC-tgC-MibcLPx0ZEgKEDQ0IgBGNACuVMIxxnIAXnQAbrRkAGyxcejFJABMRYUmSLwCQqLikrUmiuGq6oZSOiB6w1p9cWYWyTb2jvauHl4Rjf6BwaHhABzR0yYJfEnIqekiYm4FhyXllbAArLfcDQDMLbIAuhRRKFEAbiAA).  Parameters **z** and **zlevel** work as expected.

**Comment by Zz1056627814** [comment]
in echarts.extendComponentView.I compared the code and it will set z automatically. Should be set preventAutoZ.
echarts.extendComponentView({
  type: 'myrect',
  render: function(model, ecModel, api) {
    model.preventAutoZ = true;
    this.group.removeAll();
    const group = this.group;
    const rect = new graphic.Rect({
      shape: {x:0,y:0,width: 100 ,height: 100},
      style: {fill:'red'},
      zlevel: 3,
      z:10
    })
    const rect2 = new graphic.Rect({
      shape: {x:100,y:0,width: 100 ,height: 100},
      style: {fill:'yellow'},
      zlevel: 5,
      z:10
    })
    group.add(rect);
    group.add(rect2);
  }
})
