### ISSUE TITLE
[Bug] pie 的 data 数据都为 0 时，百分比为 undefined

### ISSUE THREAD

**Issue by SaberA1ter** [apache/echarts#17787]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/clever-proskuriakova-0x5os5?file=/src/App.js

### Steps to Reproduce

只需要使 data 数据皆为 0 并显示百分比即可

### Current Behavior

显示为 {d} 或者 ({ percent }) 都为 undefined

### Expected Behavior

在 5.3.3 版本中，如果数据都为 0 的情况下则应该显示为 0%

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
@Ovilia @SaberA1ter 抱歉，这其实 5.4.0 版本因饼图性能优化 #17275 导致的一个 bug，已在 #17734 中一并修复。

**Comment by SaberA1ter** [comment]
> 在数学上 0 除以 0 的结果是未定义的，所以得到 undefined 没有问题。如果需要变成 0 的话，自己在 formatter 里转即可

因为新旧版本表现不一样，翻了更新日志也没有看到关于这点的特别说明，所以就提了这个 issue
