### ISSUE TITLE
[Bug] Custom series api.value returns NaN

### ISSUE THREAD

**Issue by zangzimi** [apache/echarts#17781]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDGBDANgU2gBMsAnALlgG011kbbZgSICwKByANzxMmx3YAaerQx4cOAMoQAXngqUArAAZBsRQEYAusIboSWaAHN5VdgCZl58wFoNy9jpHoZFc7r3MjACzaxoAK4SHgwARsBgYMAAthSBEiIAvjRO6ADOPCxpCiKoerBgAJ4gpuwYAWlR0ULOmMBMhBDQWGB4koWVeLGwZbgExCQ1-cRgWDn56JQWVrb2dg5qqj0a5gB05o5qAPRbsBAAZnXR0awF3hBpsDhNeGoQYLAA7kwA1mm1k9PW83YaQrAaNTsLChDCbD5mSzfOYaP5qdw9AAehRkjlqqU8_R4AElWt0ABQgUhYaJpNRYEAQACUCAAfHQJnVoJVYIiELAKRBVpxcAE8PiNDT4MLYMpYAB-WCWWAUTnc3n8wUIEUaCUA6VuSwAbghGBgLMK7IAzCodYy9cyHs0Tuy5TycHz8eYqWaJhaWSQ8BgHog8oyCsVSp7vUN_WlvBTTH7_ayKIiQv7ChRCgnGY8IIQwN43MpVBCGN48BAfH4NCp87BEqm9JVCvgKNH_fsIBIONAYHh2BWqxXWoiwABhGCtaB-RuM2v1hkx2h9vzWvAV9DJGMriaJV35T1gAIkODBsCb2hr5cpFAboA

### Steps to Reproduce

See the above demo. When the first data (e.g. `'12.2'`) is number-like, the following data returns `NaN`.

### Current Behavior

`api.value(2)` returns `NaN` for `['2022-10-11', 1, 'abc']` and `['2022-10-11', 2, 'xyz']`.

### Expected Behavior

`api.value(2)` returns `'abc'` and `'xyz'` for `['2022-10-11', 1, 'abc']` and `['2022-10-11', 2, 'xyz']`.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

NA

**Comment by Ovilia** [comment]
You can use `dimensions: [null, null, {type: 'ordinal'}]` to mannually ignore the auto-detecting of one dimension. I will further check this case.

**Comment by lemonNoIce** [comment]
> You can use `dimensions: [null, null, {type: 'ordinal'}]` to mannually ignore the auto-detecting of one dimension. I will further check this case.

Solved my problem, thanks !

**Comment by Ovilia** [comment]
After some research, I found that currently, if any of the first 5 data is guessed to be a number (e.g., `12.3`), the whole column is set to be in number type. We decide to keep this logic and developers are always encouraged to set the type of `dimensions`.
