### ISSUE TITLE
[Bug] Treemap: set selected tree node and zoom to node after data refresh

### ISSUE THREAD

**Issue by AimanKhan1** [apache/echarts#17798]
### Version

5.4.0

### Link to Minimal Reproduction

https://jsfiddle.net/AimanKhan11/51kuv2mc/10/

### Steps to Reproduce

1) run the fiddle
2) drill down to specific node (click event will store the last visited tree node info into variable) 
3) click on refresh button

### Current Behavior

By clicking on refresh button, treemap not zooming to last visited node and going to its initial state. 

### Expected Behavior

Treemap should zoom to last visited node and maintain its state after refreshing options

### Environment

```markdown
- OS: Windows
- Browser: Google Chrome
- Framework: Angular@14
```

### Any additional comments?

Is there any way to select or zoom last visited node after refresh treemap data option.?

**Comment by li942475402** [comment]
```javascript
dispatchAction({
  type: "treemapRootToNode";
  targetNode?: TreeNode | string;
  targetNodeId?: string;
  direction?: "rollUp" | "drillDown";
})
```
