### ISSUE TITLE
[Bug] : Hover animation on disabled legend item

### ISSUE THREAD

**Issue by dileepyelleti** [apache/echarts#17790]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-stack

### Steps to Reproduce

Click on legend item to disable it.
After clicking it shows entire chart as disabled.(When mouse pointer is still on that item)

### Current Behavior

On hovering on disabled legend item also all remaining series are shown as disabled.

### Expected Behavior

Should remove hover animation on disabled legend and work only if legend item is enabled

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This doesn't seem to be a bug. With `emphasis: { focus: 'series' }`, when hovering on one series, the others are blurred.

**Comment by dileepyelleti** [comment]
> This doesn't seem to be a bug. With `emphasis: { focus: 'series' }`, when hovering on one series, the others are blurred.

It is not a bug and required behaviour if we hover on enabled legend. But why do we need that functionality on disabled legend?
Immediately after disabling a series(by clicking legend) mouse pointer stays on disabled legend Item. Then entire chart looks disabled. When users wanted to remove a series then it looks to them that entire chart got disabled.

<img width="877" alt="Screenshot 2022-10-20 at 11 45 16 AM" src="https://user-images.githubusercontent.com/3032714/196870408-5a6f8a3d-4e7d-4290-8573-47a953b57e81.png">
