### ISSUE TITLE
[Bug] : 当所有数据为0时，饼图的 formatter: '{b}:{c} { {d} }' 中 d 显示为undefined

### ISSUE THREAD

**Issue by Flyingliao** [apache/echarts#17791]
### Version

5.4.0

### Steps to Reproduce

ignore

### Current Behavior

ignore

### Expected Behavior

ignore

### Environment

```markdown
ignore
```

### Any additional comments?

Sorry, my English is not good, so please look at the picture.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/41402189/196675651-671d3f16-7c35-470f-8db0-4951ffea83d7.png">

**Comment by plainheart** [comment]
See also #17787
