### ISSUE TITLE
[Bug] 在tooltip format内部创建的element添加点击事件，但没有移除，是否会产生内存泄漏

### ISSUE THREAD

**Issue by L-value** [apache/echarts#17793]
### Version

最新版本

### Steps to Reproduce

在tooltip format内部创建的element添加点击事件，但没有移除，是否会产生内存泄漏

### Current Behavior

如题

### Expected Behavior

如题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
这个还不曾测过，tooltip 内部会使用 `innerHTML = ''` 清空内容，如果创建的对象没有被其他地方始终保持引用的话，一般应该是不会产生内存泄漏的。

**Comment by oldRabbitForz** [comment]
> 每10毫秒刷新一次，自定义得tooltip会发生内存泄漏，该tooltip上绑定得事件一同发生泄漏

**Comment by plainheart** [comment]
@oldRabbitForz 请给出示例便于我们复现。

**Comment by oldRabbitForz** [comment]
> @oldRabbitForz 请给出示例便于我们复现。

只能给你截heapsnapshot，商业项目不能给代码的

**Comment by plainheart** [comment]
@oldRabbitForz 自行脱敏并尽可能简化代码逻辑，足以复现问题即可。

**Comment by oldRabbitForz** [comment]
> @oldRabbitForz 请给出示例便于我们复现。
我微信415572600,微信上说

**Comment by oldRabbitForz** [comment]
> @oldRabbitForz 自行脱敏并尽可能简化代码逻辑，足以复现问题即可。

我微信415572600,微信上说

**Comment by oldRabbitForz** [comment]
@plainheart
