### ISSUE TITLE
Ukrainian locale name is incorrect

### ISSUE THREAD

**Issue by manastyretskyi** [apache/echarts#17795]
### Version

5.4.0

### Steps to Reproduce

Ukrainian locale code is "UK" and not "UA", as it is in version 5.4.0 

### Current Behavior

Locale code for Ukrainian language is "UA"

### Expected Behavior

Locale code for Ukrainian language should be "UK"

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by manastyretskyi** [comment]
Reference PR #17244

**Comment by plainheart** [comment]
Thanks for your feedback! You are welcome to open a PR to fix it. :)
