### ISSUE TITLE
[Bug] Tooltip should not show axisPointer

### ISSUE THREAD

**Issue by sz-p** [apache/echarts#17805]
### Version

5.4.0

### Link to Minimal Reproduction

https://stackblitz.com/edit/js-ehgqbw?file=index.js

### Steps to Reproduce

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/14040327/197145554-2a7102a7-da70-4e3c-96ce-0c4c4d74bdd2.png">

### Current Behavior

have 218.0

### Expected Behavior

do not show  218.0

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MainHou** [comment]
set `yAxis.axisPointer.show` false
![image](https://user-images.githubusercontent.com/32701177/197203470-d6f4b6f8-4367-4fe4-b401-9750fa8d0aaa.png)

**Comment by sz-p** [comment]
> set `yAxis.axisPointer.show` false ![image](https://user-images.githubusercontent.com/32701177/197203470-d6f4b6f8-4367-4fe4-b401-9750fa8d0aaa.png)

Yes  I know, I want `yAxis.axisPointer.show`  true and tooltip show right

**Comment by MainHou** [comment]
reference doc: https://echarts.apache.org/en/option.html#tooltip.axisPointer.axis
You can set `tooltip.axisPointer.axis` = "y" make tooltip show right, when `yAxis.axisPointer.show` is true .

**Comment by sz-p** [comment]
I set `tooltip.axisPointer.show` = false tooltip is not right

**Comment by sz-p** [comment]
Will this problem be fixed?

**Comment by YuShengHou** [comment]
Main、侯已经收到你的邮箱
