### ISSUE TITLE
饼图支持每个扇区样式的自定义，包括颜色，形状等等

### ISSUE THREAD

**Issue by KevinIvy** [apache/echarts#17803]
### What problem does this feature solve?

可以自定义每个饼图扇区的样式，比如可以实现圆角圆环图那种进度条的形状，无需用custom模式从头开发

### What does the proposed API look like?

itemStyle: (style) => {}

**Comment by plainheart** [comment]
每个 data item 可以单独设置特定样式。参见：https://echarts.apache.org/option.html#series-pie.data.itemStyle
