### ISSUE TITLE
[Bug] CANVAS width set to 0 in Firefox when using display:none of one DIV

### ISSUE THREAD

**Issue by tscrosh** [apache/echarts#17807]
### Version

5.4

### Link to Minimal Reproduction

http://www.schroeder.mobi/test/pages/7.asp

### Steps to Reproduce

click on accordion tab called GOUVERNANCE , on right side there is an IFRAME which calls an asp page generating the graph.

Under Browser Edge all works fine
Under Firefox I can see in the CANVAS code of the graph the WIDTH is set to 0 instead of an other value (Edge gave me 250)

### Current Behavior

Graph is not shown correctly, I mean it's due to the width = 0 in canvas

Firefox CODE
<canvas style="position: absolute; left: 0px; top: 0px; **width: 0px;** height: 350px; user-select: none; padding: 0px; margin: 0px; border-width: 0px;" data-zr-dom-id="zr_0" **width="0"** height="350"></canvas>

EDGE CODE
<canvas data-zr-dom-id="zr_0" **width="262"** height="350" style="position: absolute; left: 0px; top: 0px; **width: 262px;** height: 350px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas>

### Expected Behavior

That the WIDTH is correctly calculated in Firefox

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
ECharts doesn't observe the change of its container element for now. This may be a compatibility issue in Firefox. When the container element is not visible, ECharts will probably be not able to get the correct width and height. You can try to use the `ResizeObserver` API to watch the change of the container element and call `chart.resize()` to trigger resizing of the chart.
