### ISSUE TITLE
[Bug] 多x轴下使用dataZoom进行缩放，导致刻度变化和分隔线无法对齐

### ISSUE THREAD

**Issue by luofc21** [apache/echarts#17816]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-template-with-datazoom-vrymph?file=/src/index.js

### Steps to Reproduce

1. 当没有dataZoom或者dataZoom的start/end范围是0-100时，两个x轴的分隔线splitLine是可以对齐的
2. 当dataZoom的范围是小于0-100，分隔线splitLine就无法对齐了

### Current Behavior

两个x轴的分隔线无法对齐

### Expected Behavior

两个x轴的随着放大或缩小，分隔线splitLine都可以对齐

### Environment

```markdown
- OS: 
- Browser:
- Framework:
```

### Any additional comments?

分隔线对齐并不是最终目的，我的最终目的是想两个轴的图形对齐。柱状图和折线图的坐标需要对应起来。

**Comment by hanjituan** [comment]
not multiple x, single x has same problem, you can open the simple code , hover on datazoom and you will find this image 

![Image](https://github.com/user-attachments/assets/80cd999c-d76c-4359-8271-ba06f77fedc7)

https://echarts.apache.org/examples/zh/editor.html?c=bar-simple

**Comment by hanjituan** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXLANprrJnmxgCeIApkQOQDGAhmPQObABONTADSVyAEw5sipKlSYBGISNkAmRTPJMAzGvWwmAFh3qmAViMymANnOyA7DY0AOB-iYBOF3rkAGT_IXCul6qgbry2qHGcoZKsAC6keQARsBgYMAAtkTeIgC-ZAlkNDj4RKhUtAzMAG5sADYArvTmbLh4ACoQLADWZbB4ABbAAO5EAGb1ePSwuYmt-AAybEn0dX2DI-OT07MieCB1EGALENCMyP1Do7ATdVMzZLvoXLwQomUi6SDMbt4ApExHqEpq96IQSCJyjJxGBJCQ5IJYAikYjkWjURiUVj0UjCupKucmEk2LwHNA2BlCWxqQ4jvQMgBlWh1c5Q9QsYB1PjMADEJgAwgAhbwAMQAooD1PkqNL4qEYWwAFrATJSSGxN7MBXKzIADQZh1E9FJiXQBOYeENxocGVODJAbGgRB8ptgvHo9UglKIYF4TVd2DaAEloEaMFJvHiZGMIHVOLwALLAI3MengASulJpVV6X4OAb0CBcAZgZ3eV14WG8UuwfTl2LEnovYANUP8zncvS-x37En0aBgBwxuos3jtrm8Zjd6C990DhwpXhGscdydd3g9h1zweugaO0QshkQABehM0IREsQ2wwAIvRYbGfX76K7OBgwEyaCyPkEORPeQKwripKMhPDIGTANU9AABL7oeJ6EhesQQVBsGhoezKsrE6CLsu46dkwfJCqKEquugf4ETy_LKGKygiiKnjHmW3g5FKwixGme54KUFBBChMFwfQn7frxQSwBRa5MNOs79oO2EPGxsQKoKbBNrwLahj-uh9mwwlYWJ4mrlOG4zluskgVKsRgVQUwsiwnCiDeEgqWpGnvKJ6g6XpWm_kZ66bn287ydZMiHGc3keboEnGQF24WaBVl5IkbLkJqejaiqGS6iG3FGg45p6KcuXNAGJR4CGYYRlGVDHplADy0BJg0UwAOoFqszD2bwdQ2pB9ANU1rXtWseiDBAYw7shfUDS2UxJlBWx3C-sTDvGSYpnoaa0PFspxCguQANxAA

same problem

**Comment by hanjituan** [comment]
我的问题, 这个场景不对
