### ISSUE TITLE
y轴名称如何写上标，如m3中‘3’写成上标

### ISSUE THREAD

**Issue by zhazha-gsk** [apache/echarts#17811]
### What problem does this feature solve?

y轴名称如何写上标，如m3中‘3’写成上标

### What does the proposed API look like?

这线图y轴上标

**Comment by plainheart** [comment]
参见 https://github.com/apache/echarts/issues/15858#issuecomment-940589952 及 https://github.com/apache/echarts/issues/13363#issuecomment-700366361
