### ISSUE TITLE
[Feature] letterSpacing for axisLabel

### ISSUE THREAD

**Issue by mkupriichuk** [apache/echarts#17817]
### What problem does this feature solve?

Add ```letterSpacing``` to ```axisLabel```

![image](https://user-images.githubusercontent.com/30961944/197502266-9bab4771-f25e-4125-80b3-299b15b96656.png)

Or is it already there but am I doing something wrong?

### What does the proposed API look like?

```
axisLabel: {
  fontSize: 10,
  lineHeight: 12,
  letterSpacing: 2 // or '1rem', '1.5px' etc.
}
```

Or let the `format` function return not only the string, but also an `HTMLElement` (like `formatter` in tooltip)

```
axisLabel: {
  formatter: (dayOfWeek) => `<span styles="letter-spacing: 2px">${dayOfWeek}</span>`
}
```

**Comment by Ovilia** [comment]
[CanvasRenderingContext2D.letterSpacing](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/letterSpacing) is still in experimental period and it seems [not to be well supported](https://caniuse.com/?search=letterSpacing)
