### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by meicen0208** [apache/echarts#17829]
### Version

e.g. 5.4.0

### Steps to Reproduce

{
              name: '平均分',
              type: 'bar',
              data: this.data.avgSeriesdata,
              barWidth: 13,
              color: '#3C64EF',
              itemStyle: {
                //柱状颜色和圆角
                color: '#3C64EF',
                barBorderRadius: [0, 3, 3, 0] // （顺时针左上，右上，右下，左下）
              },
              emphasis: {
                itemStyle: {
                  color: '#FF9F00' // 选中柱颜色
                }
              }
            }

### Current Behavior

小程序使用echarts图例点击时会导致emphasis自动高亮选中图例的所有图形

### Expected Behavior

希望切换图例时清空所有emphasis高亮选中

### Environment

```markdown
- OS:windows
- Browser:小程序
- Framework:Vue@2+taro
```

**Comment by plainheart** [comment]
非小程序上是否存在次问题？能否给出代码示例？

**Comment by meicen0208** [comment]
> 

pc端是鼠标滑过，所以不会出现这个问题，但是小程序就会出现，测试数据的option如下
option = {
  title: {
    text: 'World Population'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {},
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: {
    type: 'value',
    boundaryGap: [0, 0.01]
  },
  yAxis: {
    type: 'category',
    data: ['Brazil', 'Indonesia', 'USA', 'India', 'China', 'World']
  },
  series: [
    {
      name: '2011',
      type: 'bar',
      data: [18203, 23489, 29034, 104970, 131744, 630230]
    },
    {
      name: '2012',
      type: 'bar',
      data: [19325, 23438, 31000, 121594, 134141, 681807],
      emphasis: {
                itemStyle: {
                  color: '#FF9F00' // 选中柱颜色
                }
              }
    }
  ]
};

**Comment by plainheart** [comment]
@meicen0208 这个可以通过关闭系列和 legend 的联动来做到。 参见：[`legendHoverLink`](https://echarts.apache.org/option.html#series-bar.legendHoverLink)

**Comment by Ovilia** [comment]
请修改标题，改为有信息量的
