### ISSUE TITLE
[Bug] 在Android的webview 中访问图表页面，初始化页面后图表没有颜色(所有线条、点均为黑色)

### ISSUE THREAD

**Issue by Allez-Gdy** [apache/echarts#17823]
### Version

v5.4.0

### Steps to Reproduce

1.设置itemStyle.color 为某个颜色
2.在Android的webview 中访问带有此图表的页面
3.页面初始化后，图表颜色丢失(所有线条都为黑色)
4.点击有数据的点，图表重新出现颜色

已经尝试的解决方案
1.延迟渲染时机，无用
2.设置色彩格式 rgba rgb HEX 等， 无用
2.不设置itemStyle.color，页面初始化有颜色，不能自定义线条颜色 不符合预期

### Current Behavior

1.在webview 页面初始化后图表没有颜色(所有线条都为黑色)
![image](https://user-images.githubusercontent.com/64739670/197674308-7e05d67f-9538-42e9-a744-a57f3889a1a3.png)
2.点击有数据的点后页面出现颜色
![image](https://user-images.githubusercontent.com/64739670/197674392-359484e2-0ed6-4d6c-a562-182ed3dc40f4.png)

### Expected Behavior

设置itemStyle.color 后在Android的webview初始化能够渲染出所有颜色

### Environment

```markdown
- OS:Android
- Browser: Android webview 
- Framework: vue@2.5.2
```

**Comment by Allez-Gdy** [comment]
Configuration items for this problem ↓
No problems in the browser.
The problem occurs in the webview of Android.
I don't know how to provide intuitive examples.
If I do not set itemStyle Color, then no problem will occur.
I don't know whether it is a configuration item problem.
I hope I can get help，thanks

``` 
option = {
        gri d: {
          top: 35
        },
        tooltip: {
          trigger: 'axis',
          axisPointer: {
            type: 'line',
            lineStyle: {
              color: '#83ABEEFF',
              width: 1.5,
              type: 'solid'
            }
          },

          position: function (point, params, dom, rect, size) {
            let x = point[0] - size.contentSize[0] + 5 < 0 ? 0 : point[0] - size.contentSize[0] + 5
            let y = point[1] - size.contentSize[1] - 15 < 0 ? 0 : point[1] - size.contentSize[1] - 15
            return [x, y];
          },

          formatter: function (params) {
            let month = ''
            let day = isNaN(params[0].axisValue) ? '1' : params[0].axisValue
            for (let i = params[0].dataIndex; i >= 0; i--) {
              if (isNaN(_this.data.date[i])) {
                month = _this.data.date[i]
                break
              }
            }

            let reqTime = _this.data.datas[params[0].dataIndex]
            console.log(reqTime);
            let year = reqTime !== null ? ',' + reqTime.time.split('-')[0] : ''
            let time = reqTime !== null ? reqTime.time.split(' ')[1] : ''
            let returnData = `<div style="color:#004554FF; font-size: .8em;">${month}. ${day}${year} ${time}</div>`
            for (let i = 0; i < params.length; i++) {
              let indexColor = params[i].color
              console.log(indexColor);
              returnData += `<span style="display:inline-block;margin-right:5px;border-radius:10px;width:9px;height:9px;background: ${indexColor}"></span>`
              returnData += `<span style="color: ${indexColor}; font-size: .8em;">${params[i].seriesName}: ${params[i].value !== undefined ? params[i].value : '-'} mg/L</span></br>`
            }
            return reqTime ? returnData : null
          },
        },
        legend: {
          data: [],
        },
        xAxis: {
          data: this.data.date,
          axisLine: {
            lineStyle: {
              color: '#99B5BBFF',  
              type: 'dashed'
            }
          },
          axisLabel: {
            fontWeight: ''
          },
          axisTick: {
            show: false
          },
        },
        yAxis: {
          show: true,
          name: 'mg/L',
          axisLine: {
            show: true,
            lineStyle: {
              color: '#99B5BBFF', 
              type: 'dashed'
            }
          },
          axisLabel: {
            fontWeight: 'bold'
          },
          // 辅助线x
          splitLine: {
            show: false
          }
        },
        series: [
          // saa 
          (this.queryDate.type === 'all' || this.queryDate.type === 'saa') && {
            name: 'SAA',
            type: "line",
            data: this.filterData('saaValue'),
            symbol: 'circle',
            itemStyle: {
              color: '#85DE2BFF',
            },
            // 标准线
            markLine: {
              silent: true,
              symbol: ['none', 'none'],
              lineStyle: {
                // color: '#99B5BBFF'
                // color: 'rgba(133, 222, 43, 1)'
              },
              data: [{
                yAxis: 10
              }],
              label: {
                show: true,
                position: 'insideEndBottom',
                formatter: 'standard', // reference normal line
                color: '#99B5BBFF'
              },
            },
          },
          // crp 
          (this.queryDate.type === 'all' || this.queryDate.type === 'crp') && {
            name: 'CRP',
            type: "line",
            data: this.filterData('crpValue'),
            symbol: 'circle',
            itemStyle: {
              // color: '#FFA679FF',
              // color: 'rgba(255, 166, 121, 1)'
            },
            markLine: {
              silent: true,
              symbol: ['none', 'none'],
              lineStyle: {
                color: '#99B5BBFF'
              },
              data: [{
                yAxis: 10
              }],
              label: {
                show: true,
                position: 'insideEndBottom',
                formatter: 'standard',
                color: '#99B5BBFF'
              },
            }
          },
        ],
      };
```

**Comment by Allez-Gdy** [comment]
> @Allez-Gdy Please provide a demo for the issue either with [Official Editor](https://echarts.apache.org/examples/editor.html), [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

I don't know if I was asked to provide such an example.
https://jsfiddle.net/3uwxmycf/19/

**Comment by plainheart** [comment]
Could you provide the UA of the webview (via `navigator.userAgent`) and the system information of the mobile?

**Comment by Allez-Gdy** [comment]
> Could you provide the UA of the webview (via `navigator.userAgent`) and the system information of the mobile? And is it working if you use the SVG renderer instead of the Canvas renderer?

+ navigator.userAgent:  Mozilla/5.0 (Linux; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36.

+ system information: Android11
+ Using the SVG renderer has no effect.

**Comment by plainheart** [comment]
Is it a virtual device? Does this issue exist on other mobiles?

**Comment by Allez-Gdy** [comment]
> Is it a virtual device? Does this issue exist on other mobiles?

This problem exists on virtual machines and other mobile phones

**Comment by plainheart** [comment]
@Allez-Gdy Thanks for your information! It seems this "colorless" issue is caused by the form of color `rrggbbaa`. This form of color may not be perfectly supported in the Android Webview, you can remove the unnecessary opacity `FF` or change to the form of `rgba(r, g, b, a)` and it should work.

**Comment by Allez-Gdy** [comment]
@plainheart Thank you for your answer. I deleted the unnecessary opacity FF, and the problem has been solved

**Comment by Allez-Gdy** [comment]
@plainheart Thank you for your answer. I deleted the unnecessary opacity FF, and the problem has been solved

**Comment by plainheart** [comment]
Glad to hear it. :)
