### ISSUE TITLE
Add option to keep endLabel inside chart

### ISSUE THREAD

**Issue by helgasoft** [apache/echarts#17828]
### What problem does this feature solve?

[example code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDesCwAoWXYA8CCOEAzgFzKwAmAhmFWQNoCMANAEzMDMzALMwKzMAbMwDsAXVgBfZhmywAngWJkkYeSACmZAOQA3KgBsArhu1SZmbEQ0AnCBtKx6suchevY0KgFstsbQYwAOawYBo4YMywrAAMsADGABZUNkTaFh5Yapo6BhDQplHurtS0DIyMMVGMHOywlSz1HLywAJxV0RwdrJViGZka0BQAMlQARhoGKrBEicAA7iRgNiZRAGbANt40YTY6SFSSZpLFWNKnbpYeXr65wbah4ZGhicSwbxx8Cck2VPG7aX6HmyfgC-UKCTyIDIa0M1iBJRodCcPW6tSisRYrGaGPaGO4aJifQuWEGI3GkxUswWSxWGnWm22YF2-0O2hJ2AA9JzmDZgLQwmRuAJYMA1mtrGAGABaGpcbhiDknK7YSRoFWK9CSIA)
If too long, _series-line.endLabel_ overflows outside the chart.
 One remedy is to use _offset_ and/or _rotate_, but his is not always a good option. Sometimes users want to see a normal straight text at the end of  the chart.

### What does the proposed API look like?

Could it be possible to have an additional option **endLabel.confine** ?
There are already similar _tooltip.confine_ and  _grid.containLabel_

**Comment by plainheart** [comment]
It sounds good but you can do it via [`labelLayout`](https://echarts.apache.org/option.html#series-line.labelLayout) for now. Here is an [example](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDesCwAoWXYA8CCOEAzgFzKwAmAhmFWQNoCMANAEzMDMzALMwKzMAbMwDsAXVgBfZhmywAngWJkkYeSACmZAOQA3KgBsArhu1SZmbEQ0AnCBtKx6suchevY0KgFstsbQYwAOawYBo4YMywrAAMsADGABZUNkTaFh5Yapo6BhDQplHurtS0DIyMMVGMHOywlSz1HLywAJxV0RwdrJViGZka0BQAMlQARhoGKrBEicAA7iRgNiZRAGbANt40YTY6SFSSZpLFWNKnbpYeXr65wbah4ZGhicSwbxx8Cck2VPG7aX6HmyfgC-UKCTyIDIa0M1iBJRodCcPW6tSisRYrGaGPaGO4aJifQuWEGI3GkxUswWSxWGnWm22YF2-0O2hJ2AA9JzmDZgLQwmRuAJYMA1mtrGAGABaGpcbhiDknK7YSRoFWK9CSIA) for your reference.

**Comment by plainheart** [comment]
> but it seems labelLayout duplicates the effect of endLabel: { offset: [-133,10] } in moving the label inward.

When using `offset: [-133, 10]`, you will have to know the width of the text. But if you use `labelLayout`, you can get the real width, height, and position of the text from the callback parameters, which allows you to customize the label layout and is suitable for many cases.

> The idea is to somehow shrink the graphical part of the chart to accommodate long labels on the right side.

If so, I think if a text is very long the chart will be unreadable due to the limited area for showing the text completely. And it sounds like what the `grid` component does.

**Comment by helgasoft** [comment]
[grid.containLabel](https://echarts.apache.org/en/option.html#grid.containLabel) is to control _"Whether the grid region contains axis tick label of axis"_.
I know it's a long shot, but maybe someone will look into implementing the <ins>same feature</ins> for **endLabel**.
There is similarity - [yAxis.axisLabel](https://echarts.apache.org/en/option.html#yAxis.axisLabel) usually overflow to the left, while [series-line.endLabel](https://echarts.apache.org/en/option.html#series-line.endLabel) - overflow to the right.
