### ISSUE TITLE
Download https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap does not get the data[Bug] 

### ISSUE THREAD

**Issue by MrCoolLion** [apache/echarts#17836]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap

### Steps to Reproduce

Download file from https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap.
Run in the browser (Windows 11 Chrome) and it will keep showing loading.
It does not seem to be able to get the data.

### Current Behavior

Run in the browser (Windows 11 Chrome) and it will keep showing loading.
It does not seem to be able to get the data.

### Expected Behavior

It should retreive the data from https://echarts.apache.org/examples/data/asset/data/les-miserables.json and show the graph.

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome Version 106.0.5249.119 (Official build) (64-bits)
- Framework:
```

**Comment by plainheart** [comment]
It's caused by the CORS policy of the browser. You can download the data resource with the URL.

**Comment by MrCoolLion** [comment]
Thank you !
