### ISSUE TITLE
[Support] Plotting Pie charts or semi-circles on scatterplot

### ISSUE THREAD

**Issue by arkim822** [apache/echarts#17838]
### What problem does this feature solve?

Hello. First time posting here so apologies if I have not tagged this correctly. I am having a blast with Echarts and am in the process for building a dashboard that helps to understand **Immunohistochemical assay** data.

I have gotten pretty far and one of the last visualizations users would like to see is a plot of semi-circles.

Circle of two colors. Ex: Half red, half blue.

I have looked through the examples pretty extensively (because they are just so beautiful) and found that maybe the plotting of small piecharts on a x-y coordinate plane is the way to go.

https://echarts.apache.org/examples/en/editor.html?c=calendar-pie&lang=ts

I was wondering if anyone could weigh in on the feasibility of this or if it's even possible at all. If not, no problem! : )

Thank you.

### What does the proposed API look like?

https://echarts.apache.org/examples/en/editor.html?c=calendar-pie&lang=ts

**Comment by arkim822** [comment]
I've figured out  a workaround for now and it a bit hacky.
path = 'path://M0,20 a1,1 0 0,0 80,0'
option = {
	xAxis: {
		data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
	},
	yAxis: {},
	tooltip:{},
	series: [
		{
		type: 'scatter',
		data: [220, 182, 191, 234, 290, 330, 310],
		symbolSize: 20,
		symbol: path,
		symbolKeepAspect: true,
		symbolRotate:45,
		symbolOffset: [4, 4],
		color: 'orange'
		},
		{
		type: 'scatter',
		data: [220, 182, 191, 234, 290, 330, 310],
		symbolSize: 20,
		symbol: path,
		symbolKeepAspect: true,
		symbolOffset: [-4, -4],
		symbolRotate: 225,
		color: 'blue'
		}
	]
Hope this comes in handy for someone else.

**Comment by Ovilia** [comment]
Can you provide an illustrator of what you want to make?

**Comment by plainheart** [comment]
Hi, @arkim822, you can set `itemStyle.color` to a [gradient color](https://echarts.apache.org/option.html#color) to get such an effect. Please refer to this [example](https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple&code=PTAEFcGcFNQcwE4EMAmBLaA7ALqbB7eaXAIgAkkAbAM1AWhQBpQALK2gI0vGhICgAxvkyRcAtAgGVoAYXyV8CUAF5QAbz6g8ATwAO0AFygA5JTSZoSBMcabQADyMBGW1u1GADK4cAmZ9-0_UBc7IQUEAGUCXUgjAG07LQ0tFNB8amoYbE8AOgBWb1SwxSNjehRjRNAAX0L1Kq10zOJcgobQYoRSrh5K1Oq7AF0-aoBuPj58XWw0YRV6rXsAQXs0WPVau20VtaM1Ta0YBAx1hNTk1NBIbQBbDnkItAAvQ1AfL3aQCBgOqkoOJACADWoGo4Bws0weEIWQ68kUoIRlgELFAaGw0BunzAMFgVEghBY2GwMQMIGgKKs2EgOSQukBLGgOUUcGAUxmwhyRJulAAxEcTgBaSACJDE6AIHLozFRbTSHKddrSm6y6R7dpaToACnpyBukAAlAtLkVhAT5Qo4DqrEh9QbxibUvRsOAEFDxJJpHJwg7HQMTQdLigxUh4hrQHEnB4cl5QAAOGMAFkGdXO4a0ADcqDx4gmPAB2ZgANhyAE48in02iMSrsHLXhdHSkvtp8OBflD8TDiHDwoilJBzHBpNXMVWtF9caAu6xiaTyZSENTafSUUyWWzppCudgefyJUKRWKMZLg9gkFKa6qmYqm6bwqVyn07_6_amUpGAMwx5j5_JxysmziUsYwKeMcjjJxAMdSMnB_cDP0_aCTUjRN4L_Isi2Qy4vxyRNiwgqD3y0SNo1jEtEOw1JUPghNSyw4iIycHx8gIuMfCoj8QKcMC_w4xjYNY0A-M4kjvw8T9mDQnwkIE5ich8X8INk8M4hYjxFNANDE3zUSmNA5hv0ogS0I8MC0PovS4hLCSlJ8ZM5PUgifAY1T5NjBM4wc1S_w8ONmDyCD-NUwKNICnIiwA9pOLrfRSiPcVrCqV9hjGIA).

**Comment by arkim822** [comment]
Hello. This is exactly what I wanted : ) Much better than my hacky workaround. 

@Ovilia - Plainheart has captured what I intended to do. 

@plainheart - Thank you so much! I wanted the circles to be diagonal so I changed it to this:

`const circleColor = {
  type: 'linear',
  x: 0,
  y: 0,
  x2: 1,
  y2: 1,
  colorStops: [
    {
      offset: 0.5,
      color: 'red'
    },
    {
      offset: 0.5,
      color: 'blue'
    }
  ]
};`

Please close out this issue :D
