### ISSUE TITLE
[Bug] Zoom on Bar with type value makes bar go out of bound overlapping axis

### ISSUE THREAD

**Issue by AdamSogeti** [apache/echarts#17835]
### Version

5.2.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-tick-align&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGbABaMAJsADu9HrAC-xHd3QVyK8duzUAZmAYBmAKRdt5Copux6AFkeGSAI2AwTABbOx9tAGMYMEZhABlGP2psQjBSAFdqfV8VRhiALSxQ2ABtbQlJWEsIXFoAWWAVeQ9q2tInStgIUw9cgqKADQ7KmTkGYTZu6mHJZgBBVjYASWgm5kISgAZOAEYAXW0Dcu10VtFSBqaGM9oZkm6GPsZC4GCATTv0Ueb6CanP2DSBbsFZrDbbWD7Q7EPa-eaLDbHTrfBgAN0Y2EyAL4bAAKhAIgBrMydXjYSjQADqEDAigSSRSZEyJ100PQsOIQIRpSRI1kP3RmOmbNgHPQbFoEGobERkgqkmgjGCPwAIhBSNQImAASiPH5GO1fJJ9aRqSpaQwAGybcKdJ4bHacWAAJidtidnidAFYnZanQB2J0ADidAE4DpI9OyUDoANxAA

### Steps to Reproduce

Use the link above, or set up a bar chart with the x-axis having `type: value` and some simple data. Try to zoom in and you will see that the bars overlap the y-axis when zooming in. When changing type of the x-axis property to `category` you will see it does work correctly again.

### Current Behavior

the bars overlap the y-axis when zooming

### Expected Behavior

The bar disappears when it's out of range of the displayed values instead of overlapping the y-axis

### Environment

```markdown
- OS: windows 10
- Browser: microsoft edge
- Framework: React
```

**Comment by Ovilia** [comment]
This problem has been discussed and we decide to take this as a feature rather than a bug. In this case, the x and y values are both inside the data zoom range so it is expected to be displayed. And we decide not to do the clip-path of the grid by design.

**Comment by AdamSogeti** [comment]
Thanks for your explanation Ovilia!
Can we follow the status of this feature? How do i know when this feature has been released?
