### ISSUE TITLE
[Bug]: Gap between axis symbol and axis line when symbolOffset is provided to avoid overlap of the symbol with max tick

### ISSUE THREAD

**Issue by jaykumar-parmar** [apache/echarts#17833]
### Version

5.4.0

### Link to Minimal Reproduction

[Sample Link](https://echarts.apache.org/examples/en/editor.html?c=line-in-cartesian-coordinate-system&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurALYCGGRArDQDQnpX4AyE0ApkaqaXgE8yAI2AAbIgG0A5NBidp9WNIoAnVcADu0gLqM-6QSPEBlCAC9usSQEYADEps09TfkNFiA8gDNveTmBS9o4AHDquAL4kEfqwAjj4PDEk_qoQnITWrrwGACYUYBRSrny2DrAALHYuBqSSNOX21bG1klVKAEzVJbA1BmACIFbSYhwKkSThEQDcQA)

### Steps to Reproduce

Follow the link to reproduce the issue.

### Current Behavior

Gap is seen between axis line & axis symbol
![image](https://user-images.githubusercontent.com/14372061/197964680-e115bc55-61a4-4ff0-9b1e-784a073b2287.png)

### Expected Behavior

Expectation is axis line is extended as following to prevent gap
![image](https://user-images.githubusercontent.com/14372061/197965138-81794376-44af-4422-9214-64aa3508f609.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This symbol can be customized and it may not always make sense to extend the axis line. You can use an SVG path containing the line in this case.
