### ISSUE TITLE
[Bug]  tooltip repeat rendering

### ISSUE THREAD

**Issue by wssll789** [apache/echarts#17834]
### Version

5.2.2

### Steps to Reproduce

1.triggerOn=mousemove
2.formatter: function(params) {
return <img src='xxxxx'>;
 }
3.Viewing Network Requests

### Current Behavior

Render should not be repeated on the same data

### Expected Behavior

Render should not be repeated on the same data

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by wssll789** [comment]
formatter: function(params) {
return `<img src='xxxxx'>`;
}

**Comment by plainheart** [comment]
The tooltip will empty the previous content on each render. In this case, you should create DOM outside the formatter callback and return it. BTW, the "repeated rendering" generally occurs only when the cache is disabled, for example, you opened the devtools and enabled `Disable cache` or the image URL or its query parameter is changed.
