### ISSUE TITLE
[Feature] 多Y轴的显示，用于显示多通道波形图

### ISSUE THREAD

**Issue by chenweihan** [apache/echarts#17832]
### What problem does this feature solve?

比如 在信号分析领域，需要使用多Y轴查看波形图，支持放大缩小等   

### What does the proposed API look like?

可以查看EDFbrower,查看信号图

**Comment by Ovilia** [comment]
https://echarts.apache.org/examples/en/editor.html?c=area-rainfall

**Comment by chenweihan** [comment]
我的意思是 多Y轴垂直叠加，比如
![1667202914112](https://user-images.githubusercontent.com/1927864/198958946-f14a1a9c-4cd7-448c-b747-2e7cdbf08d90.png)

核心是ecahrt能否 多Y轴垂直叠加

**Comment by Airkro** [comment]
这种目前需要用循环 创建多个 Grid，多个 X轴，多个 Y轴，多个 series 实现
