### ISSUE TITLE
[Bug] 5.2升级到5.4饼图百分比展示undefined

### ISSUE THREAD

**Issue by zxyue25** [apache/echarts#17843]
### Version

5.4

### Steps to Reproduce

饼图百分比错误
  label: {
         formatter: '{b}: {d}',
  }
当数据全部为0时，百分比显示了undefined，应该为0

5.2版本没问题，5.4版本出现该问题

### Current Behavior

![Uploading image.png…]()

### Expected Behavior

当数据全部都为0时，百分比应该为0

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
补充例子 https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBKOAZjgE5OzB2wCGsA6jgEYBnCGByUANEXQCArnxHkqAMQ4BrHLAAiHMB3GTYuOhViUAxjmgjGlIgF8J6MMGBZIIAqmIZGEAOa-mKmEcAFsbdHsiXADoABMPfWAfC2NKADcmSFMOLD0vQ1SC8NhIqSYIHAECAG19Ty9YaA4Q_BMAQVNzAQFYRUZgMIcGsABPEFbKEAq8hsYOWIhpKpMAVgAGAFIZr1jtDhr9LyRYNJzpVrWxRuaJgGUcDkZTAAtYAFFoXwhoURKhhuQJzOFyuTRaVA0EGYpjAlD-h2Ix1OWHOBEu13BJjeIQ4EFy8IB6CRwLRoJuVAAqtAoHA2rEBHDSoTiSiQRiJgA1CCxHDAWB0hklBEAXX-xCwHD4OCwCUJsDoSRxYCsVCQfFsHlitmKXls-j16GFKFsAG4gA

**Comment by zxyue25** [comment]
5.3没问题，先降级5.3上线了

**Comment by plainheart** [comment]
这个问题已经解决过了，先前已有其他开发者反馈过，参见 #17734。
