### ISSUE TITLE
incorrect emphasis on hover near wide lines ends 

### ISSUE THREAD

**Issue by helgasoft** [apache/echarts#17845]
### Version

5.4.0

### Link to Minimal Reproduction

[example code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUrHgMYCGANgKZEBmbe7sZCmGDBWkEHUHo-AJwjtCsANoV0qdBthhKITrADkrCNHb7SsaMwC2e_QCE7Z1RoAmzMMyJKlABlIBGP31mEP0AXXMlf1IAJiCAI0TwiJQASHThUXE6LmAZK3cwdhkifSRmYn0pTVh2aBcAGWZ49lY6PAALYAB3IjAZAFd2c1z8wuLSpHjK6s08Sit40QBlCAAvPQAOcnTUoxNl7Q46bogXMA6iTb9YUGZGCG0iHwA6AFZzRlE80vjWIaqO3Sj3YVkOlGOyDuDyerw-sC-rB-Bj-ALIsDS6VBIA6zDwtGQ-3Y4MhSGhj0oRH8xExu12pFYzVa7S6vS0g2GsFGBTARRKBnKM1pdNSpDqjSZbWQnR6fQ5AlpNM0s2QznQ2l0pSJZgs1lsywASk4arA3B4vFF3rEfBFlC8AJyxABststAGYAjaUiaiSS9EhTudLrAACzmclPWBwz7ffn6GTsFyAtW1Kw4vEE9Qm2C-o7-iOU2DUjF0hmSlmy9lDEZ5Hl8yYVKrCsX1JotKVIGVs_pDBUmpUaFVZk0a2xMcYyHWWGylBP3DrG7NmzzKKLW0j6RLxZLkbMMBZLVirDZXG4F54vGLOAdhFDEADcQA)

### Steps to Reproduce

Run the example

### Current Behavior

Hover in **green** area over the <ins>**red**</ins> line - the wide **blue** one is emphasized instead.
Looks like the green half-circle represents a "reserved area" for Big Blue line emphasis, although other lines could be there.

### Expected Behavior

The **red** line should be emphasized inside the illustrative green area.

### Environment

```markdown
- OS: Win 10
- Browser: Chrome
- Framework:  JS
```

**Comment by jiaopeng2020** [comment]
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2022 14:47 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [apache/echarts] incorrect emphasis on hover near wide lines ends (Issue #17845) |

Version

5.4.0

Link to Minimal Reproduction

example code

Steps to Reproduce

Run the example

Current Behavior

Hover in green area over the red line - the wide blue one is emphasized instead.
Looks like the green half-circle represents a "reserved area" for Big Blue line emphasis, although other lines could be there.

Expected Behavior

The red line should be emphasized inside the illustrative green area.

Environment
- OS: Win 10
- Browser: Chrome
- Framework:  JS
Any additional comments?

No response

**Comment by Ovilia** [comment]
I think this is probably by design because when there are multiple stops in a line (e.g., add the `[1,5,'ccc']` to your first series), the joint point should be considered rather than the line itself.

May I ask what problem does this cause in your case?

**Comment by helgasoft** [comment]
Ovilia, I understand your point.  But my data contain only **single** line segments. 
It's an implementation of a **timeline**, with overlapping lines with different widths - see [example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUrHgMYCGANgKZEBmbe7sZCmGDBWkEHUHo-AJwjtCsANoV0qdBthhKITrADkrCNHb7SsaMwC2e_QCE7Z1RoAmzMMyJKlABlIBGP31mEP0AXXMlfwCggCN48IiUAEhU4VFxOi5gGSt3MHYZIn0kZmJ9KU1YdmgXABlmWPZWOjwAC2AAdyIwGQBXdnNs3PzC4qRY8srNPEorWNEAZQgALz0ADnJU5KMTRe0OOk6IFzA2onW_WFBmRghtIh8AOgBWc0ZRHOLY1gGKrdS93YVn2lEOyBudwezzesA-rC-Bh-fzIsBSqWBIDazDwtGQu3YoPBSEh90oRH8xHR222pFYjWarQ63S0_UGsGGeTABSKBlKU2pVM002QznQ2l0xQJZgs1lsiwASk4qrA3B4vFEnj4ACwxCLKfyvPVJFUEol6JDHU7nWAAZlt5lJD1gMPen15-hk7Bc_zF1SsWJxePUKtgZoOFqd5NglLRNLpDJayHaXR6bKGOS5PPGZQqfqFGhFIc0Ets0vMlhsxUVyqqas8yiUTwA7AEAEz6zUO_wdk1VcNgi1Ws5EbWwqOPI1w93FSjNBGdX3C8iaYtVUvFJijGQyyu2L23Nq1lX1jXRQKkfTxWKJFeh2bzJarDZXCcup7-ZwFsIoYgAbiAA).
Info for each line is in the **tooltip**. and line tooltips appear only at **line ends**.  
Note: would be great to have an <ins>option</ins> to get them **anywhere** on the line - a _new feature_ request, I guess.

After testing some more, I found another little problem. When a user enters the green zone from left, top or bottom, he will see tooltip 'BB' only, even if hovering on top of red's line end ('SR').  That's because _endLabel_ 'BB' is masking it. 
Maybe both problems are not fixable, just little annoyances to live with.

**Comment by plainheart** [comment]
I'm not sure but maybe you can set a higher z for the scatter?

**Comment by helgasoft** [comment]
Thank you, @plainheart !  Indeed _z:111_ in line 'SR' fixes both problems. &lt;genius 🏆&gt;
