### ISSUE TITLE
[Bug] 饼图百分比格式化错误

### ISSUE THREAD

**Issue by ProgramPlayer** [apache/echarts#17842]
### Version

5.4.0

### Link to Minimal Reproduction

https://codepen.io/hank-ly/pen/RwJPRyB

### Steps to Reproduce

渲染饼图，值1设为382206，值2设为2，并设置显示label

### Current Behavior

在精度为2的情况下，我在对数值 382206和2 进行百分比显示时，所显示出的百分比为100%，但实际应为99.99%。

### Expected Behavior

382206/382208 后的百分比格式化应为99.99%。

### Environment

```markdown
- OS:window10
- Browser:chrome 106.0.5249.121
- Framework:
```

### Any additional comments?

经测试后发现，在执行 99.99947672471534.toFixed(2) 后会出现这种情况

**Comment by Ovilia** [comment]
I don't think this is a bug. `382206/382208` is `0.99999477`. When the precision is 2, it should be rounded to be 100% rather than 99.99%.

**Comment by ProgramPlayer** [comment]
> I don't think this is a bug. `382206/382208` is `0.99999477`. When the precision is 2, it should be rounded to be 100% rather than 99.99%.

嗯嗯，你说的没错，算法确实没问题。那以后要是遇到保留2位小数的情况，大部分情况下{d}变量不就都用不了了哦，毕竟100%和99.99%所表达的含义还是有差别的。

**Comment by Ovilia** [comment]
By default, `{d}` is the rounded result of percentage. If you don't think it appropriate for your case, you can use callback function to do the formatting.

**Comment by ProgramPlayer** [comment]
> 默认情况下， `{d}` is the rounded result of percentage. If you don't think it appropriate for your case, you can use callback function to do the formatting.
好的，谢谢。
