### ISSUE TITLE
[Bug] 使用dataset x轴数据会自动合并

### ISSUE THREAD

**Issue by 775146061** [apache/echarts#17847]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/relaxed-shockley-bbfgrq?file=/src/index.js

### Steps to Reproduce

dataset的数据是这样的：
["Matcha Latte", 43.3, 85.8, 93.7],
["Milk Tea", 83.1, 73.4, 55.1],
["Milk Tea", 86.4, 65.2, 82.5],
["Walnut Brownie", 72.4, 53.9, 39.1]

Milk Tea有两个，当第一列作为x轴时，Milk Tea会被合并成一个柱子。
echarts有没有不自动合并的配置？

### Current Behavior

![Uploading image.png…]()

### Expected Behavior

期望x轴上的Milk Tea不合并成一个

### Environment

```markdown
- OS: macOS 12.5.1 (21G83)
- Browser: Chrome 106.0.5249.119
- Framework: javascript
```

**Comment by Ovilia** [comment]
Data with the same name is expected to be the same group. You may use different names in data and then use `label.formatter` to change the text for display.

**Comment by 775146061** [comment]
> Data with the same name is expected to be the same group. You may use different names in data and then use `label.formatter` to change the text for display.

为什么在系列中用data就不会被合并呢？用dataset就会被合并，有没有解决方案阻止使用dataset时相同的名字分到同一个组？

**Comment by shenxiang216** [comment]
有解决方法吗
