### ISSUE TITLE
Labels do not flip properly with the startAngle option

### ISSUE THREAD

**Issue by dominikj111** [apache/echarts#17855]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/optimistic-morning-ubqm4p

### Steps to Reproduce

Change the `startAngle` to 180.

### Current Behavior

Some labels appear up side down.

### Expected Behavior

All labels will flip to appear bottom line down even they need to be read out from the outer into the centre.

### Environment

```markdown
- OS: macOS Monterey 12.6.1
- Browser: Chrome 107.0.5304.87
- Framework: React 18.2.0
```

**Comment by Ovilia** [comment]
`series.startAngle` is not in the document so this option may probably not provided to be changed. If you have such requirement, you are welcomed to make a pull request.
