### ISSUE TITLE
[Bug] 树图官方第一个例图触摸label可以展示tooltip，且label文案没有被线条穿过

### ISSUE THREAD

**Issue by CodeCat01** [apache/echarts#17851]
### Version

5.4.0

### Steps to Reproduce

1、chrome浏览器、vite（2.6.8） react（17.0.2）
2、我在react v17 & echarts5.4 版本中label触摸没反应且label被线条穿过 

### Current Behavior

x

### Expected Behavior

x

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
抱歉没太理解你的意思，这个问题是必须和框架绑定的么？如何用官方的例子来复现？

**Comment by CodeCat01** [comment]
我是告诉下我在什么版本出现的问题。
官网上示例中 树图/第一个树图（从左到右树状图）直接复制option配置，然后再项目中展示，鼠标触摸label,官网中是有提示的，但在我创建的项目中，触摸label没有反应




---- 回复的原邮件 ----
| 发件人 | Zhongxiang ***@***.***> |
| 日期 | 2022年10月31日 15:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/echarts] [Bug] 树图官方第一个例图触摸label可以展示tooltip，且label文案没有被线条穿过 (Issue #17851) |

抱歉没太理解你的意思，这个问题是必须和框架绑定的么？如何用官方的例子来复现？

**Comment by plainheart** [comment]
@CodeCat01 那麻烦提供一下简单的复现 Demo ？

**Comment by CodeCat01** [comment]
解决了，可能是网络原因，当时在内网安装的依赖包，删除了node modules文件夹后npm i，但是node modules中的还是4.x的，今天在家重新删除又再次npm i 发现可以了，也可能是 第一次npm i的时候 安装过程有失败的。🌚



---- 回复的原邮件 ----
| 发件人 | Zhongxiang ***@***.***> |
| 日期 | 2022年10月31日 16:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/echarts] [Bug] 树图官方第一个例图触摸label可以展示tooltip，且label文案没有被线条穿过 (Issue #17851) |

@CodeCat01 那麻烦提供一下简单的复现 Demo ？

**Comment by plainheart** [comment]
好的，解决就行。那这个 issue 就关闭了哈。
