### ISSUE TITLE
[Bug] vben框架下markLine不显示

### ISSUE THREAD

**Issue by lbqzzz** [apache/echarts#17854]
### Version

5.2.2

### Steps to Reproduce

1.vben框架封装的方法
![image](https://user-images.githubusercontent.com/117132323/199146199-e188a631-aa70-417e-a83e-21659005af84.png)

![image](https://user-images.githubusercontent.com/117132323/199145591-ce273531-a0bf-4bad-8d98-ad3d0446a2d5.png)
2.配置项
![image](https://user-images.githubusercontent.com/117132323/199145801-6655496d-3872-4340-8ecb-17828a7f5605.png)
3.其他用到的图表功能暂时没遇到问题，只有这个标记线显示不出来，没找到问题

### Current Behavior

![image](https://user-images.githubusercontent.com/117132323/199144903-4e407024-17fa-46aa-8998-4591fcea063c.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/117132323/199144788-6115328b-1fdb-4361-83af-6121e27aa463.png)

### Environment

```markdown
- OS:windows10
- Browser:Chrome 106.0.5249.119
- Framework:Vue@3
```

**Comment by plainheart** [comment]
看起来你在使用 `use`，需要自行按需引入相关 chart 和 component，如果需要显示 markLine，应该引入 `MarkLineComponent`。
```js
import { MarkLineComponent } from 'echarts/components'

echarts.use([
    // ...
    MarkLineComponent
])
```

**Comment by lbqzzz** [comment]
Ok
