### ISSUE TITLE
[Bug] 有百分比展示的情况下，点击图例切换显示隐藏，剩余图上显示的百分比出错

### ISSUE THREAD

**Issue by XerxesLee** [apache/echarts#17852]
### Version

5.4.0

### Steps to Reproduce

以这个图举例，https://echarts.apache.org/examples/zh/editor.html?c=pie-nest

### Current Behavior

1. 点上方图例第一个"Direct"后，"Direct"被隐藏，剩余的饼图还显示的百分比都不对，没有重新计算，而是直接第二个"Email"变成了"Direct"的比例13.08%。
2. 再将"Email"隐藏掉，"Google"变成了13.08%。百分比被简单粗暴的直接按序交过去了。

### Expected Behavior

百分比需要被重新计算。

**Comment by plainheart** [comment]
已在 #17734 中修复
