### ISSUE TITLE
dataZoom slider trend incorrect on multiple line series

### ISSUE THREAD

**Issue by helgasoft** [apache/echarts#17850]
### Version

5.4.0

### Link to Minimal Reproduction

[example code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRQEYCGAxgNYDmATsAK7QAJgGFgAG2DciAckZi27aeXR4AptwirCsANoV0SWGEohVMsRGiqlsQczDMiOnQEYAzKVguAdG4C6njoATACsnv5-sAzoBkYmZrDSFlY2dg5OOmFe3iEBui4AnJ4ADN5BfpHRsAEUacwAWsDAALZ0sPqweA7cYERBxZ4dAPRDdQBCCjz8QnTM3KrMAMrGYglIoGwQxkTFZLDJqsuUq3QbrFuUO8RV6CNqq6xgqoIAIvbMExxTAoKz80srNZnC5XTwHI4nZDA7awXbECjw4gAbiAA)

### Steps to Reproduce

see example link above

### Current Behavior

dataZoom slider shows the trend of the **first line only**. But there could be many more lines.

### Expected Behavior

**Not showing a trend** at all, in our opinion, would be best in complex scenarios like multiple overlapping lines, or large data spans as in #15688

### Any additional comments?

A workaround is to hide the trend with _dataBackground.lineStyle.opacity: 0_ and _selectedDataBackground.lineStyle.opacity: 0_.

**Comment by Ovilia** [comment]
Please follow #17143
