### ISSUE TITLE
Allow to place the middle label into the centre of the chart

### ISSUE THREAD

**Issue by domino2** [apache/echarts#17856]
### What problem does this feature solve?

When back button is not shown and the root node appear to be in the centre, the label is not centred in the circle but a side. 

### What does the proposed API look like?

Maybe simple api to allow to appear automatically in the middle of the sunburst chart if there is no back button and it is a first node of the data.
In my use case, the first item of the `option.levels` is empty structure as I don't want the back button at all.

**Comment by domino2** [comment]
I didn't want to draw the graphic element because it is the external way what I would like to avoid, if this is what you meant.
But I'll use the title for this as the result is as what I'm looking for.
Only flaw I see here is that I need to set the size of the text to match the size of the middle circle.
[CodeSandbox](https://codesandbox.io/s/apache-sunburst-internal-centre-text-j5un1y

**Comment by Ovilia** [comment]
Yes, this is the expected way to do this.
