### ISSUE TITLE
[Bug] iOS中axispointer padding属性显示不对

### ISSUE THREAD

**Issue by hanzhiqiangniuniu** [apache/echarts#17853]
### Version

5.1.2

### Steps to Reproduce

`axisPointer: {
          z: 0,
          label: {
            show: true,
            snap: true,
            margin: 5,
            padding: [5, 7],
            backgroundColor: '#D1E3FF',
            color: '#000',
            formatter: (params: any) => {
              const { value } = params;
              const date = new Date(value);
              return formatDate(date);
            },
          },
        }`

padding: [5, 7] 在iOS中右padding没有了

### Current Behavior

![image](https://user-images.githubusercontent.com/19897781/198955452-713a9835-a6ac-41ce-93a2-f7b0f0643c9e.png)

### Expected Behavior

iOS中axispointer padding属性显示正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
只是 iOS 存在这个问题吗？能麻烦提供一个能运行的例子我这边测试一下吗？
