### ISSUE TITLE
[Bug] 图表左右两侧默认会有个padding，这个有配置可以去掉么，想canvas都用来显示图表内容

### ISSUE THREAD

**Issue by L-value** [apache/echarts#17869]
### Version

5.22

### Steps to Reproduce

[Bug]  图表左右两侧默认会有个padding，这个有配置可以去掉么，想canvas都用来显示图表内容

### Current Behavior

[Bug]  图表左右两侧默认会有个padding，这个有配置可以去掉么，想canvas都用来显示图表内容

### Expected Behavior

[Bug]  图表左右两侧默认会有个padding，这个有配置可以去掉么，想canvas都用来显示图表内容

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
可以设置 [`boundaryGap`](https://echarts.apache.org/zh/option.html#xAxis.boundaryGap) 为 `false`

**Comment by L-value** [comment]
感谢 配置后确实有效果了，但是发现如果y轴如果有单位 还是会距离左侧有些空隙

**Comment by plainheart** [comment]
> 但是发现如果y轴如果有单位 还是会距离左侧有些空隙

这个倒是，好像现在还不太好控制轴名称 `axis.name` 的偏移量，也许后面会优化一下，不过优先级可能并不太高。
