### ISSUE TITLE
[Bug] yAxis exponential not showing

### ISSUE THREAD

**Issue by Sunghee2** [apache/echarts#17866]
### Version

5.3.3

### Steps to Reproduce

Min value of Yaxis set to number with exponential

### Current Behavior

The minimum value of my chart is 9.88e-13 
and the maximum value is 0.0000106

When exponential comed to the chart Yaxis value,
it is displayed to NaN in the chart 
![image](https://user-images.githubusercontent.com/31603479/199636258-65def4c7-eb8f-48d4-a0fe-cd49e57a0240.png)

I already used parseFloat() but it wasn't solve.
How can I solve it?

```javascript
const minYAxis = _.minBy(props.data.rawData.map((d) => d.itemValue)) // 9.88e-13 
const maxYAxis = _.maxBy(props.data.rawData.map((d) => d.itemValue)) // 0.0000106


      return {
        toolbox: {
          show: true,
          itemSize: 13,
          left: '10%',
          feature: {
            dataZoom: {
              yAxisIndex: 'none',
            },
          },
        },
        xAxis: {
          type: 'category',
          data: xAxisData,
          splitLine: {
            show: false,
          },
        },
        yAxis: {
          type: 'value',
          scale: true,
          min: minYAxis,
          max: maxYAxis,
          splitLine: {
            show: false,
          },
        },
        tooltip: {
          show: true,
        },
        grid: {
          height: '74%', left: '100',
        },
        series: [
          {
            type: 'boxplot',
            data: boxData,
            smooth: true,
            layout: 'vertical',
            itemStyle: {
              borderColor: '#d7d7d7',
              borderWidth: 3,
            },
            zlevel: 0,
            animation: false,
          },
          {
            type: 'scatter',
            large: true,
            data: scatterData,
            symbolSize: 3,
            color: '#59709b',
            zlevel: 1,
            animation: false,
          },
        ],
      }
```

### Expected Behavior

display 9.88e-13 or 0.0000000000000988

### Environment

```markdown
- OS:
- Browser: Chrome
- Framework:
```

**Comment by plainheart** [comment]
I can't reproduce this issue with the simple [demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2Srz8sAC2ENBEAJwAdAAccVQAtACMAMyOpKGMGEQADDF5RXkpeQBsmeh4TP7eYBxK9pmsRgJuIbUAZmD5lbD0MGCMEQAyjABGVP5E9Y3odih2ANxAA).
