### ISSUE TITLE
[Feature] Simple progress lines

### ISSUE THREAD

**Issue by BenJackGill** [apache/echarts#17863]
### What problem does this feature solve?

I would like to create a single progress line using eCharts.

Here is in an image example: https://imgur.com/a/PhTQKxL

The colored line should change depending on it's value, for example:

 - When the value is 10 there should only be a small colored line.
 - When the value is 50 the colored should fill half the line, and grey the other half.
 - When the value is 100 it should be all colored.

The colored line should also animate on load.

And it should also have rounded end caps.

Is this simple type of progress line possible in eCharts? How would it be done?

If not I please suggest it is added as a feature.

  [1]: https://i.stack.imgur.com/SOjqn.png

### What does the proposed API look like?

No current ideas for the API.

**Comment by plainheart** [comment]
I think such a progress bar definitely can be done via HTML + CSS and it should be easy. You don't have to use ECharts to do this, though ECharts can make it.
