### ISSUE TITLE
[Feature] Found it hard to get started with README.md

### ISSUE THREAD

**Issue by AntiMoron** [apache/echarts#17868]
### 😁What?

After I ran `yarn dev`, I don't know how to test `echarts` code base. So, it's DIFFICULT TO CONTRIBUTE as a beginner. which is not good for an open source software.

### 😁Why?

I was willing to fix a bug of 'graph' chart. But I need to learn those codes first. Usually I will use `webpack-dev-server` or `vite` to host some static html for testing.

### 😁How?

Provide us a way to run a demo project with `webpack-dev-server` or `vite`.

**Comment by AntiMoron** [comment]
### tl;dr 

开源软件难以上手贡献代码，我认为yarn dev后应该提供个localhost:8000之类的地址打开个demo、让我调一调。更多的人能上手自己解决问题

**Comment by plainheart** [comment]
Have you read the wiki [How-to-setup-the-dev-environment](https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment) and [How-to-setup-the-dev-environment](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request)? I think it might be helpful to you.

**Comment by AntiMoron** [comment]
@plainheart  To be honest, you tell me is that method really easy to get started with?

**Comment by AntiMoron** [comment]
Also what I did is exactly what this article described.

https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment

You don't paste that.

**Comment by AntiMoron** [comment]
Like me, my solution is :

1. Create a html file in directory `./assets/`
Here's the content:

```html
<html>
    <body>
        <div id="chart" style="width: 500px; height: 500px"></div>
        <script src="../dist/echarts.js"></script>
        <script>
            const chart = echarts.init(document.querySelector("#chart"));
            chart.setOption({
                xAxis: {
                    type: "category",
                    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                },
                yAxis: {
                    type: "value",
                },
                series: [
                    {
                        data: [150, 230, 224, 218, 135, 147, 260],
                        type: "line",
                    },
                ],
            });
        </script>
    </body>
</html>
```

2. Just open that html after run `yarn dev`
3. If any updates, refresh this page.

This is easy to test, but no file watching no HMR. You have to refresh yourself.

**Comment by AntiMoron** [comment]
> Have you read the wiki [How-to-setup-the-dev-environment](https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment) and [How to make a pull request](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request)? I think it might be helpful to you. You can start an HTTP server and open the `test/-cases.html` for debugging.

I mean , have a look at what I got.

![image](https://user-images.githubusercontent.com/6587734/199667693-594fb62d-085d-486e-bf9c-5d9eff2ce1d2.png)

No hint of `test/~cases.html` at all

**Comment by Ovilia** [comment]
@AntiMoron Yes, we really appreciate the help from the community. Next time if you meet such problems, you are welcomed to make a pull request to help.
