### ISSUE TITLE
[Feature] type:'log',interval

### ISSUE THREAD

**Issue by ZWQ652** [apache/echarts#17877]
### What problem does this feature solve?

在对数轴中，怎么自定义刻度呢？
![image](https://user-images.githubusercontent.com/58023091/200206788-30fbb46f-c567-462f-88f8-2287ddfc6d67.png)
我翻遍文档也没有找到在哪里设置指数值。

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/58023091/200206788-30fbb46f-c567-462f-88f8-2287ddfc6d67.png)

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#yAxis.logBase
