### ISSUE TITLE
Allow percentages in label width parameter

### ISSUE THREAD

**Issue by Creatium** [apache/echarts#17874]
### What problem does this feature solve?

Right now label settings allow only fixed pixels number for the width parameter. In cases where chart width is varying (and that is probably most of the cases), it should be possible to allow labels have a full width "100%" setting. 

What I am trying to achieve for my chart is having horizontal bar chart with labels above the bar itself. On the left it should show the data index name, on the right - the value. But since I don't know the final width of the chart, I am unable to "push" the right part of label to be truly on the right side.

### What does the proposed API look like?

series -> label -> width - allow "100%" setting, not just pure number value.

**Comment by plainheart** [comment]
Maybe you can try to use the [`labelLayout`](https://echarts.apache.org/option.html#series-bar.labelLayout) callback function to get the chart width and use it to calculate the position of the label.
Like this,

```js
labelLayout(params) {
  // get chart width
  const chartWidth = myChart.getWidth();
  // ...
  return {
    // ...
  }
}
```

**Comment by urgrund** [comment]
I think this is important feature and would be valuable if this extended to font-sizes as well 

We're able to define bar/pie elements with percentages,  but our labels don't follow.   This makes it cumbersome having to write per-chart instance differences in to adjust the font size _(which in the end is just eyeballing)_ .

If the font size supported typical CSS _(%, px, em, vw)_ values that might help the charts be more responsive and scalable to pages that want to reuse the same chart in different scales or just simply have their charts follow font rules used elsewhere in the site.

![image](https://user-images.githubusercontent.com/13104208/200166517-21ae75a8-6131-4790-9194-5c6cb258358f.png)

**Comment by Creatium** [comment]
Solved my problem by setting width param in label setting of series to this:
`width: chart.value?.$el.clientWidth - 30,`

30 being the margin of charts (can be changed in grid setting of chart options).
