### ISSUE TITLE
[Bug] Can't use "document.getElementById('main')" for echarts.init in Grafana (v9.1.8)

### ISSUE THREAD

**Issue by naqibRDMA** [apache/echarts#17879]
### Version

3.5.0

### Steps to Reproduce

Creating the chart itself is not a problem. I've managed to use their bar charts and line graphs with ease and no issue. 
The problem comes in when I wanted to add a click event for a drill down activity. In Grafana, I need to add the chart's DOM to echarts.init. Below are the code that I've taken from the website's official documentation:

var chartDom = document.getElementById('main');
var myChart = echarts.init(chartDom);
myChart.on('click', function (event) { . . . }

### Current Behavior

chartDom will always return NULL as there is no div tags with the id 'main' in Grafana.  Grafana will render the echart into a panel and I don't know which of it's id to initialize the echart.

### Expected Behavior

document.getElementById('main') should not return NULL

### Environment

```markdown
- Browser: Google Chrome
- Grafana: v9.1.8
- Apache ECharts: 3.5.0
```

**Comment by Ovilia** [comment]
This doesn't seem to be a problem related to Apache ECharts. You have to find a way to input the DOM element somehow with Grafana. I believe there are some Grafana ECharts plugins which you may have a look to find if they are helpful.
