### ISSUE TITLE
请问散点图的点可以用富文本编写吗？文档没看到有相关功能，没有的话我觉得这个是比较需要的

### ISSUE THREAD

**Issue by JaeWong-CN** [apache/echarts#17870]
### What problem does this feature solve?

自定义symble

### What does the proposed API look like?

1

**Comment by plainheart** [comment]
能详细说明一下吗？是想改变点的形状？

**Comment by JaeWong-CN** [comment]
> 能详细说明一下吗？是想改变点的形状？

不是的，比如我想每个点用不同的背景图加文字来实现，symbol不能用富文本来实现的话岂不是每个点都要分别切不同的图和不同的文字的图吗？

**Comment by plainheart** [comment]
> 我想每个点用不同的背景图加文字来实现

`symbol` 设置为图片，然后用 `label` 作为文字是否能满足需求？参见这个[例子](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt7ZmXHoQ2MTABR-gVRZIIwcjMN4AJTxCegcVGAKHHC0EMOMrDQA9E_aYGAghC8gEPR4CsMAHQgbTAMDAPBPeYAfgA-vBaLAANSwHZ7A6AoRgRgASWgAioGEWsAcxP8jFGVH8bmJS1BAHciGAOEpiXY4uz0LY7ABuIA)。

**Comment by JaeWong-CN** [comment]
> > 我想每个点用不同的背景图加文字来实现
> 
> `symbol` 设置为图片，然后用 `label` 作为文字是否能满足需求？参见这个[例子](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt7ZmXHoQ2MTABR-gVRZIIwcjMN4AJTxCegcVGAKHHAABhDDjKw0APTPACTup6Q7ewcAdEIwIwAJLQARUDCwACkOUWXwA_LJtGAwCBCK8qPRtLswHg_owdliqH9OKxntNtM97o8os8AGaMHwQegwP4gaCsYJfBJ0ZGo9HPTHYji4_GE7TE0n0xnM1myrlfOw3ADccIccP8jFGVH8bjhS20wAA7kQwBwlGq4nYSLY7MqgA)。

可以满足我提的那个需求了，谢谢您的解答。但是如果有的需求需要点用不同的照片，同时用相同的背景图包裹，这个时候应该还是需要富文本吧，不然就只能一张一张切图了

**Comment by plainheart** [comment]
每个点的图片都不相同，不论用不用富文本都是一样需要切图吧？
