### ISSUE TITLE
[Bug] 启用graphic下的elements的type: 'group'时，group下有3个元素，不能保证其始终水平居中

### ISSUE THREAD

**Issue by leleccccc** [apache/echarts#17881]
### Version

5.4.0

### Steps to Reproduce

option = {
  tooltip: {
    trigger: 'item'
  },
  series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      labelLine: {
        show: false
      },
      data: [
        { value: 1048, name: 'Search Engine' },
        { value: 735, name: 'Direct' },
        { value: 580, name: 'Email' },
        { value: 484, name: 'Union Ads' },
        { value: 300, name: 'Video Ads' }
      ]
    }
  ],
  graphic: {
    elements: [
      {
        type: 'group',
        left: 'center',
        top: 'middle',
        children: [
          // {
          //   type: 'text',
          //   left: '10%',
          //   top: 50,
          //   style: {
          //     text: 'top',
          //     fill: '#010101',
          //     fontSize: 30
          //   }
          // },
          {
            type: 'text',
            left: 'left',
            top: 50,
            style: {
              text: '50%',
              fill: '#010101',
              fontSize: 30
            }
          },
          {
            type: 'text',
            left: 'right',
            top: 50,
            style: {
              text: 'abc',
              fill: '#010101',
              fontSize: 30
            }
          },
        ]
      }
    ]
  }
};

### Current Behavior

group下有3个元素，不能保证其始终水平居中

### Expected Behavior

group下有大于2个元素，并且部分元素的值是动态的，保证他们始终水平居中 

### Environment

```markdown
- OS:windows
- Browser:chrome 107
- Framework:vite vue3
```

**Comment by Ovilia** [comment]
没有提供这种功能

**Comment by leleccccc** [comment]
> 没有提供这种功能，graphic 提供的接口是比较简单的，如果有复杂的需要，要么不使用 graphic 画，要么自己写对齐之类的逻辑，计算好位置后传给 graphic

好的，现在我是计算好位置后传给 graphic解决了，动态计算出了父级type: group的宽度再排列内部所有元素位置

**Comment by liunanchenFYJJ** [comment]
> > 没有提供这种功能，graphic 提供的接口是比较简单的，如果有复杂的需要，要么不使用 graphic 画，要么自己写对齐之类的逻辑，计算好位置后传给 graphic
> 
> 好的，现在我是计算好位置后传给 graphic解决了，动态计算出了父级type: group的宽度再排列内部所有元素位置

遇到同样的问题，请问具体怎么计算的？

**Comment by cooper1x** [comment]
> > 没有提供这种功能，graphic 提供的接口是比较简单的，如果有复杂的需要，要么不使用 graphic 画，要么自己写对齐之类的逻辑，计算好位置后传给 graphic
> 
> 好的，现在我是计算好位置后传给 graphic解决了，动态计算出了父级type: group的宽度再排列内部所有元素位置

如果我用的是百分比，这个怎么计算呢，你的环形图的图例在右边。
