### ISSUE TITLE
How do I customize gradient color stops if I use the dataset prop instead of data

### ISSUE THREAD

**Issue by 97morningstar** [apache/echarts#17885]
### What problem does this feature solve?

I would like to be able to add colorStops with percentages to visualMap and to the dataset. 

At the moment I can't find a way to specify the percentage to be applied to the data, except by using the itemStyle in the data property in the series prop, which I am not using. 

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/26909101/200428106-44a85646-8fb6-461e-9e2e-8f56f2a12ca1.png)

For example, in the previous image the color purple is closer to 0, I would like to have a slider and be able to move the colors to represent certain steps/areas of the data.

Is this possible? Any advice would be greatly appreciated

**Comment by brutuscat** [comment]
Not sure if this would solve what you ask, but I would add a data transformation to represent the datapoints continuously as you want and make the visual map use that added dimension.
