### ISSUE TITLE
[Feature] Bar Race yAxis Font Size Adjustability

### ISSUE THREAD

**Issue by safademirhan9** [apache/echarts#17890]
### What problem does this feature solve?

While using bar race chart, I have noticed that yAxis labels' fonts are not changeable. I have looked up for a solution but could not find any. Is it already possible to adjust the font size? If not, can you please add this as a feature?

### What does the proposed API look like?

It could look like something like this:
`yAxis: {
            textStyle: {
                fontSize: 14,
            },
},`
Or:
`yAxis: {
            label: {
                fontSize: 14,
            },
},`

**Comment by plainheart** [comment]
Do you mean [`yAxis.axisLabel`](https://echarts.apache.org/option.html#yAxis.axisLabel.fontSize)?

**Comment by safademirhan9** [comment]
Yes that was what I was looking for, thank you very much!
