### ISSUE TITLE
[Bug] dataZoom里面设置startValue为231.0053，显示却为231.00530？

### ISSUE THREAD

**Issue by li-guanlong** [apache/echarts#17893]
### Version

5.3.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/54611134/200723116-839c93d9-d6d6-4438-97d8-2f4f4741243a.png)

### Current Behavior

dataZoom里面设置startValue为231.0053，显示却为231.00530

### Expected Behavior

希望dataZoom里面设置startValue原样输出

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
默认会自动计算小数精度，如果觉得不合适，可以试试通过 [`labelPrecision`](https://echarts.apache.org/option.html#dataZoom-slider.labelPrecision) 手动指定下精度看看。

**Comment by li-guanlong** [comment]
> 默认会自动计算小数精度，如果觉得不合适，可以试试通过 [`labelPrecision`](https://echarts.apache.org/option.html#dataZoom-slider.labelPrecision) 手动指定下精度看看。

可以，非常感谢
