### ISSUE TITLE
Some chart elements like height , rotation and border color is not working for the chart  title 

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#17891]
### Version

5.3.3

### Steps to Reproduce

1)give height , rotation and  border color as options too chart title 

### Current Behavior

option = {

  title: {
    left: 'center',
    text: 'Large Area Chart',
    textStyle:{
      color:'red',
     fontSize:"30",
     "fontStyle": "italic",
    "fontWeight": "bolder",
      height: 100,// not working 
    },  
      rotate :12,// not working 
  "borderColor": "green",// not working 
  "backgroundColor": "pink",
  },

};
![image](https://user-images.githubusercontent.com/97290751/200634030-f5694cb9-7780-4d19-9d58-70a888eeaeba.png)

### Expected Behavior

rotation , height and border color

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Thanks for the feedback!

> `rotate` is not working

The `title` component doesn't support `rotate` currently.

> `borderColor` is not working

It's because the default `borderWidth` is `0`, which causes the border not to be rendered.

> `height` is not working

This looks like a bug or a mistake in the documentation.

**Comment by lin752537111** [comment]
你好呀  可以做类似这样的图吗 
![image](https://user-images.githubusercontent.com/84608271/200794797-ce8e5780-0086-4224-8f71-364a059bc3da.png)
