### ISSUE TITLE
[Bug] initOption性能

### ISSUE THREAD

**Issue by L-value** [apache/echarts#17908]
### Version

5.22

### Steps to Reproduce

64个图表各自init
<img width="331" alt="截屏2022-11-12 下午2 15 43" src="https://user-images.githubusercontent.com/13847357/201539952-5c570f47-69b6-4633-9a39-31f235435d75.png">

### Current Behavior

64个图表各自init，性能耗时 导致ui卡顿

### Expected Behavior

64个图表各自init，不卡顿UI

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
64 个图表是一个非常大的数量，请先评估一下需求是不是合理。其次，在多图表的情况下，SVG 通常会比 Canvas 性能更高，可以试试 SVG 渲染 https://echarts.apache.org/handbook/zh/best-practices/canvas-vs-svg
