### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by xzxzhixin** [apache/echarts#17907]
### What problem does this feature solve?

可以给一个离线的中文实例文档给大家下载吗
就是一个完整的：https://echarts.apache.org/zh/index.html

### What does the proposed API look like?

可以给一个离线的中文实例文档给大家下载吗
就是一个完整的：https://echarts.apache.org/zh/index.html

**Comment by dandelion1989** [comment]
同求，开发环境是离线的，联网看资料不方便

**Comment by Ovilia** [comment]
可以把项目 clone 下来本地运行 https://github.com/apache/echarts-doc

**Comment by dandelion1989** [comment]
非常感谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月16日(星期三) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] 文档 (Issue #17907)





 
可以把项目 clone 下来本地运行 https://github.com/apache/echarts-doc
