### ISSUE TITLE
[Bug] object data is not work

### ISSUE THREAD

**Issue by Valar103769** [apache/echarts#17905]
### Version

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAQIZg0DOWYJq66BEAtvg1NAxIBtAOQALYAFcATiPKwREAfQwYRAXSoUqADwCCOiIORV0YAJ4gsJEZB4itldOYNHW2qk2kQsxoaZN2dgsrGwwlLDkA9GgaHhsAJgAGBISAWgBGDMyMqKCOOhphaPY2fKCaAGNIADdrBQSAdgBOAFY88vYq2qwAfWk6epEADgSAOgyAZg7O2BppEBBJG1aJ3KdZ2CwAM22saog6mwzmgBZmmc6dvYO6_sGVxrGmy_KJGRsFDdmlBhUMGyTU5JabfTrQLAAd36-zE8zwvS4MCw5hsADYMsNnq98hDodJYfC-tBJFxjgl1iUgiAaOZ7mAhpMxq00TiggTKnDpAikRDUQo0QlWo1VgkLmDyhyuQiSWSGmjmpTNrAwMAVP1gJCSGBpJIsFTYNpZmVZt1DkMMkkkmyurc-gMGTYWmNJo0beh5otlgKxud3VtdvseitQQb0Ncg-b6UNTuMkqyJfl3tJEil0lkcrApkQrTnrYmgr9_uSE2HYHiYZyiYjkfyRBlxs1hv6K1Lq7LEv6aXSHRbmeKy23uX1eSjEq1hky0aHlUOZaTjqdmwXgmqaBgNVrYNt10wDUbOibOmajgoMmjl2WT_aHgoRS7Tv7PUsVmNGqXlRG7eSB5_A3bo0eMZhnaFd0GTVNUhyTMGzzPN_SLdcAQaBIZ02VtCWHGs-RWDJgI_dCoUraViQXBRf02btAIUU4xiSR8wNgOcR1rQFmibX03UY5jeg7BpJnzMtVXVaRNRIHcMD3WZSBKTQggPdAjzMSwhnCCEcVieIGjTaCklAkpaHoYpjSvb8zySNp9OVa9qJERosSSS9rIWF8FFWM5_S_YM70mNEGLLLyo17FZxj9RiIIUL4y0Q1RFxBQTlQwqssNHOsKWGJ4gRbIieL4kRfKcyjaVs8ZBX9HjUpsM5GimZ4lU2XKyJEWMTn9YT103bVdX1aSVyU_JrxsWMEifADgoUYY8NOLirxc70RDRYDPP_bz8rFZabh6Wzp2ZerZgikRkigjM9NgVC4KtBDlCQ3DCtmJKSOwscGlaPDWhGxiHvbJrXS7YrxrsiZ_NnTCeVYmjpySZ47s6Rq5UOxpgc2dqN1ErcJKkzoFPyfqKjM5qWlGraAZA4CkdNOb0ToqzNkC098tOGnZjpm9HQFPDJ39A6jvTbJTtSC6Es2GLkJEVoJ2y_FQZYnCzwysY0SZ8Ecul3ifr2zoqIB1YWXK1XKoUSZmitCY0NmOHEgvNq11RsTt13HqsdkgIZPQTRSAAbiAA

### Steps to Reproduce

if correct, it will look like 
![Uploading image.png…]()

### Current Behavior

series.data is obj[] , charts is not render

### Expected Behavior

correct render

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Hi, you need to put data into **[`dataset.source`](https://echarts.apache.org/option.html#dataset.source)** instead of `series.data` if you hope to use `dataset` to manage the data.
