### ISSUE TITLE
[Feature] 资源列表查看效果

### ISSUE THREAD

**Issue by hs151991** [apache/echarts#17900]
### What problem does this feature solve?

可以把之前的资源列表再放上吗，现在感觉找案例样式特别不好找，不方便，谢谢

### What does the proposed API look like?

可以把之前的资源列表再放上吗，现在感觉找案例样式特别不好找，不方便，谢谢

**Comment by plainheart** [comment]
你是指的 Gallery 吗？Gallery 是社区贡献者开发的，因为一些原因该项目已经于 2022 年 2 月 15 日停止服务。

**Comment by hs151991** [comment]
恩，是的，这个还能开启么，现在找资源特别不方便，官网示例太少了，别的网站资源列表都不太好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] [Feature] 资源列表查看效果 (Issue #17900)





 
你是指的 Gallery 吗？Gallery 是社区贡献者开发的，因为一些原因该项目已经于 2022 年 2 月 15 日停止服务。

**Comment by plainheart** [comment]
这个应该暂时不会重启了
