### ISSUE TITLE
[Feature] How to get the axis range when datazoom scales it?

### ISSUE THREAD

**Issue by masq6r** [apache/echarts#17919]
### What problem does this feature solve?

Hopefully the axis range could be known when it's changed.
I have y-axis `scale` set to `true`, and enabled `datazoom`. When I zoom or pan the chart, clearly the y-axis's range changes too. Now I need to know the new range.
I tried to listen to `datazoom` event but it doesn't look like any properties in the option could give me the values.

`chart.on("datazoom", params => console.log(chart.getOption().yAxis[0]))`

From the output I cannot see any information showing the y-axis range. Is there a way I can get it?

### What does the proposed API look like?

Add a range property in the yAxis option:

```
yAxis: {
    range: [currentMin: number, currentMax: number]
}
```

**Comment by plainheart** [comment]
Maybe related to #17278

**Comment by plainheart** [comment]
All right. I'm sorry I misunderstood. For now, we can only get it like this, which is not a public method.

```ts
const yAxisExtent = myChart
    .getModel()
    // get the first y-axis
    .getComponent('yAxis', 0)
    // get scale
    .axis.scale.getExtent();
```

See also this [demo](https://echarts.apache.org/examples/editor.html?c=area-simple&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOANgA4AaCMugZgEoBuAKFEgHtN8BPZBABMAFggAqCIwoAGWZIgl5sjlwgATAohQBtALprwmgjCG6AsgQAWAOgBOMdBu4BbIs0WN5h9gDNuewgidQBLIRJWCHCAHhEVVWjUVE8Ab3YICAA3GCD0bhwUTBx8QiIiWAQ0FF4QAWY2DJNCWwAHAFc4ayJdfKxbAHNwADF24GAATRBcjzo-wfALXjBuz1QlOYKFsFLiZn1bACtuUPQiAHIAenOGjkytMBg2zu6rFYdududyt7tHZzcHggAFoILJbABWTxSYQKdYPGC6cKgkj6W7sAC-7G4rTAoV4QnSmTA3G4wDxrQAXBAiZkIGB7KEBkN7NTzjAAB6hODnJoYmhNDkAQS5cGptOJ_FaIDZAGNtANAvxzgK6c0YNSHiA-aqIPwRdzxU1JdK2TlgO0QLzMvymgiAFqk1zU3TGmluk0yiDnU5wUIaK26tVwR72MDU2RBukgZzU5Ru21qiV0kO5cNgqOZGMaOOyBNNfS6hCMkBiiCupMeiDoGCuL3nYYwADWiFKMBVVbAUvrwFOgarcH4rigZLZ-UwHbVmTgtdavfQAzZ5LAUEnU4RmtM-cy-kxHHYrn4AGFrGnbLwLg6nSrgp4kAA-d2ZWW8EN6g1wACiHMI6EgKEPE80zdbYlgDYAPDdS5LggIZIBWRA_FCew334YFOW5EC4KPNxWlqP8Ln1UUb1kZgoJguCIDgeVQBAjC4FsaiYFAbZv1_MAPDuCAX3QOAyRAWxgG4AZCI_NiYzAG8iO5cS_0aDE2CAA).

**Comment by masq6r** [comment]
> All right. I'm sorry I misunderstood. For now, we can only get it like this, which is not a public method.
Thank you for your demo and the solution works. But since it's not public I cannot expect stability in future releases, can I? Anyway I'm closing the issue at the moment.

**Comment by bbcfive** [comment]
hi @plainheart, but how can I solve the ts error? 
> Property 'getModel' is private and only accessible within class 'ECharts'.ts(2341)

**Comment by plainheart** [comment]
@bbcfive This API is not exposed, so you have to use `as any` or `// @ts-ignore` to disable the TS check.

**Comment by ddubrava** [comment]
By the way, if the `xAxis.type` is set to `time`, the `dataZoom.startValue` and `dataZoom.endValue` properties will return formatted values, which may make it difficult to map them back to the original data. For example, if your dataset value is `1682850281010`, the `dataZoom.startValue` will be `1682850281399.8394`. Even if you use an ISO string format instead of a timestamp, the dataZoom object still returns a formatted value
