### ISSUE TITLE
[Bug] geo组件注册的svg元素添加name属性时，存在一个无法消除的边框

### ISSUE THREAD

**Issue by xwlgx** [apache/echarts#17918]
### Version

5.4.0

### Steps to Reproduce

本地发现问题之后，在官网示例测试也是同样的问题，基于官网的配置修改如下：
`var svg = '<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" fill-rule="evenodd" xml:space="preserve">
    <path name="named_rect" d="M 0,0 L 0,100 100,100 100,0 Z" stroke="red" fill="#ccc" />
    <path d="M 150,0 L 150,100 250,100 250,0 Z" fill="#ccc" />
</svg>
';
echarts.registerMap('simple_svg', { svg: svg });
option = {
  geo: {
    map: 'simple_svg'
  }
};`
官网链接：[https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Fgeo-svg-named-basic&edit=1&reset=1&renderer=svg](url)
可复制上面的代码到编辑器复现
![image](https://user-images.githubusercontent.com/19611079/201882106-0af80b93-7500-40c0-9ac5-5699bd00b24c.png)

### Current Behavior

覆盖掉了原有图形的边框，在官网的示例中也复现了问题，并且没找到可以消除边框的属性

### Expected Behavior

希望去掉边框，而不是直接覆盖原有的边框

### Environment

```markdown
- OS:win10
- Browser:edge
- Framework:vue2
```

**Comment by xwlgx** [comment]
已解决

**Comment by helgasoft** [comment]
Could you please briefly explain how you solved it?

**Comment by chj-damon** [comment]
@xwlgx 请问是怎么解决的？

**Comment by ncc0706** [comment]
@chj-damon 

```js

geo: {
        left: 10,
        right: '50%',
        map: 'organ_diagram',
        selectedMode: 'multiple',
        itemStyle: {
          borderType: 'dashed',
          borderWidth: 0 // 指定宽度为0
        }
}
```
