### ISSUE TITLE
[Bug] Invalid legend width

### ISSUE THREAD

**Issue by Alexander-txj** [apache/echarts#17923]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/vibrant-visvesvaraya-qxzv3q?file=/src/index.js

### Steps to Reproduce

Invalid setting of legend width，This is normal in version 4.0

### Current Behavior

Invalid setting of legend width，This is normal in version 4.0

### Expected Behavior

repair

### Environment

```markdown
- OS:Window 11
- Browser:Chrome/107.0.0.0 
- Framework:Vue@3
```

**Comment by plainheart** [comment]
Currently the legend box rect is only rendered when it has a non-transparent background. You can try to add `backgroundColor`.

**Comment by Alexander-txj** [comment]
thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhongxiang ***@***.***&gt;; 
发送时间: 2022年11月16日(星期三) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] Invalid legend width (Issue #17923)






目前，图例框矩形仅在其具有非透明背景时呈现。您可以尝试添加背景颜色.

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
