### ISSUE TITLE
y轴单位和x轴数据不匹配

### ISSUE THREAD

**Issue by Very-skinny-Piestar** [apache/echarts#17925]
### Version

5.4.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/68222884/202075462-bfe7fc67-f6d2-4219-b820-c13a44a95639.png)

### Current Behavior

示例数据不对

### Expected Behavior

显示正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
这个示例是用来示范怎么展示“堆叠折线图”的，y 轴指示所有系列的累计总和， 而 tooltip 显示的是单个系列的对应点的数据。可以将代码中的 `stack: 'Total'` 全部移除后再观察效果。

**Comment by Very-skinny-Piestar** [comment]
> 这个示例是用来示范怎么展示“堆叠折线图”的，y 轴指示所有系列的累计总和， 而 tooltip 显示的是单个系列的对应点的数据。可以将代码中的 `stack: 'Total'` 全部移除后再观察效果。

多谢

**Comment by yeyuchen198** [comment]
> 这个示例是用来示范怎么展示“堆叠折线图”的，y 轴指示所有系列的累计总和， 而 tooltip 显示的是单个系列的对应点的数据。可以将代码中的 `stack: 'Total'` 全部移除后再观察效果。

正好解决了我的疑问，我说怎么每条折线的值跟Y轴对不上，原来是所有系列的求和值
