### ISSUE TITLE
如何折线图中间插入点坐标

### ISSUE THREAD

**Issue by timelessover** [apache/echarts#17935]
### What problem does this feature solve?

如图![image](https://user-images.githubusercontent.com/34708197/202448977-7bda7d4c-b9c3-4f05-b497-32adb08ec273.png)

### What does the proposed API look like?

no

**Comment by Ovilia** [comment]
这个是系列数据中的一个点还是自己在指定位置画的？前者的话就是在 `series.data`，后者可以用 [convertToPixel](https://echarts.apache.org/zh/api.html#echartsInstance.convertToPixel) 计算位置后用 `graphic.elements` 画。
