### ISSUE TITLE
[Feature] 柱状图横坐标文字过长会发生重叠，或者只显示其中几个，是否可以增加属性设置横坐标超出隐藏，显示文字加点点点

### ISSUE THREAD

**Issue by sudh0** [apache/echarts#17930]
### What problem does this feature solve?

柱状图横坐标文字过长会发生重叠，或者只显示其中几个，是否可以增加属性，根据横坐标每一项的宽度，设置横坐标超出隐藏，显示文字加点点点，多一种显示选择

### What does the proposed API look like?

增加一种显示方式，可以直接使用属性配置，不需要用户自行处理。

**Comment by Ovilia** [comment]
Duplicate of #17363
