### ISSUE TITLE
[Bug] wiggling animation in real-time time series charts using dataset-dimension (no 'name' property)

### ISSUE THREAD

**Issue by koallamara** [apache/echarts#17932]
### Version

5.1.2

### Link to Minimal Reproduction

[Demo](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2&code=GYVwdgxgLglg9mABAJwIZgCZwLYBFVSoAUAlIgN4BQiiYcA7ogLy0Cmj-UrRA1HYz0QJW-AJ4kA3NUQA3VABsQrZrIVLEggLIEAFgDo0mHKUQAqRACYAjIgC0iKwAYpNZKyghkSKjRphU2KwAXLQMelBwAMpQyDBgAOakADTSNLCBIQDa_Hrx7gBiIPLyAJqsqMjJofS57poIUDomglZJ1bVQnNwkALp6AFZwcUQA5AD0IyQpvqqKwYjajQZw4BhEcnMk0gC-UtuU8u6IGASoKpk9UodQ1Spg7IhdRFYAnC8A7G0vbQDMkgdHYRiFQWAAsZkQPwAbI5HBCnLCrkcNuoWIt9IYsNgTOYEc5KMA4MhEOsKogYCpnOTEAAeBywqkwHg8Mg-Y6nPQABxAAGcmpicJxiCR_vs4JzYAgVGyToQee4QmyaDyVsgIPNZagdtNELAoIdFaldawAB5QEIjXCifzYGAQR6nRAAMkQABUYIFEABBE0wHkjbXSCJweSwTmGmYxGDxPLIC2oX3-nU0BN-gAKQzAXDjFCNKbAHoI8DAIRiSiN-xo2x1Jp9fojvigok58xG6VYI2TiB5nPkMCgABk4vMlb4-QwQsAFPKK4GaKI6zyG2lm62UR2uwAjFaYCqiADiqHDiEyjjaIwRAFIRj0uz2-4Ph8uxzoJ4gp_IZzNK4hq9J5bErBLieRqjn4AStvkqAANbKEKnZ5rqq4Wn29wITMyqvvQkSiNg27yJO06sF2NAYB6rBgDyxbAZkiE0AARO29FtPR670YhPSzjQnG7JQlDylAACSWasMgGxEKAkCSkgJhsoSxKksSFIsIytKIAArBI5LMqyRqanofIwMAUCkC4vj6dyfJEAKeCnKQ_xVtI2CiAAwjoFRQAZ7gAPISsWRDitJoptHikhAA)

### Steps to Reproduce

Trying to [Dynamic Data + Time Axis Demo](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2) with dataset-dimension, but wiggling animation still there

### Current Behavior

This situration is same as #12167, but I can't find how to set 'name' property when using **dataset-dimension.**
Is there any way to setting 'name' property, or other feature to solve wiggling animation with dataset-dimension?

```json
[
    {
    ...
        "name": "", // blank
        "dataIndex": 71,
        "data": {
            "name": "Wed Dec 24 1997 00:00:00 GMT+0900 (한국 표준시)",
            "time": "1997/12/24",
            "value": 496
        },
        "value": {
            "name": "Wed Dec 24 1997 00:00:00 GMT+0900 (한국 표준시)",
            "time": "1997/12/24",
            "value": 496
        },
        "color": "#5470c6",
        "dimensionNames": [
            "time",
            "value"
        ],
        "encode": {
            "x": [
                0
            ],
            "y": [
                1
            ]
        },
        "$vars": [
            "seriesName",
            "name",
            "value"
        ],
        ...
    }
]
```

### Expected Behavior

I really want to stop this wiggling animation. (It look emphasized when time line is really short-like 30 seconds-)

### Environment

```markdown
- OS: window 10
- Browser: chrome
- Framework: vue.js 2.6.14
```

### Any additional comments?

Is possible to give padding for xAxis time label? Sometimes its overlap so much

![image](https://user-images.githubusercontent.com/25011305/202380746-ae83bd23-22ed-4f6b-ade4-cba9dafc4cc0.png)

**Comment by Ovilia** [comment]
You can try to set `series.animationDurationUpdate` to be 0 to solve the wiggling animation.

As for time axis label, please follow #17311. Sorry I'm quite busy lately and will finish the PR later.

**Comment by koallamara** [comment]
> You can try to set `series.animationDurationUpdate` to be 0 to solve the wiggling animation.
> 
> As for time axis label, please follow #17311. Sorry I'm quite busy lately and will finish the PR later.

Thanks for your quick solution 👍  Everything are solved to nomal ;)

**Comment by svnflw** [comment]
Is there currently a solution that allows keeping the line animation while pushing new data without setting animationDurationUpdate to 0 and still using dataset-dimension?
