### ISSUE TITLE
[Feature] Flame Graph Support

### ISSUE THREAD

**Issue by keita-determined** [apache/echarts#17949]
### What problem does this feature solve?

Echarts currently does not support `Flame Graph`.
It would be useful to show CPU/GPU usage.

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/109113616/203164378-e97dd307-d47b-4edd-bf26-d3a2b8d5b5e0.png)

![image](https://user-images.githubusercontent.com/109113616/203164842-efafbd2d-27d3-4000-a7d2-0d4b1025c3d5.png)

**Comment by Ovilia** [comment]
There are some [demo](https://echarts.apache.org/examples/en/index.html#chart-type-custom) in the custom series that looks helpful.

**Comment by keita-determined** [comment]
Thanks for the info. Is it possible to add Flame Graph in demo page?

**Comment by Ovilia** [comment]
You are welcomed to make one and create the demo to [echarts-examples](https://github.com/apache/echarts-examples)
