### ISSUE TITLE
[Bug] 饼图点击图例legend隐藏部分项，对应的tooltip formatter，label formatter函数中的百分比数据不正确

### ISSUE THREAD

**Issue by landmine007** [apache/echarts#17948]
### Version

e.g.5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/embed/focused-cori-zefprj?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

1、点击图例legend，隐藏一项；
2、在tooltip的formatter函数中，打印params.percent参数；
3、在label的formatter函数中，打印params.percent参数；
4、查看tooltip和label显示百分比。

### Current Behavior

1、在tooltip的formatter函数中，打印params.percent参数数值不正确；
2、在label的formatter函数中，打印params.percent参数数值不正确；

### Expected Behavior

1、在tooltip的formatter函数中，打印params.percent参数数值正确显示；
2、在label的formatter函数中，打印params.percent参数数值正确显示；

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
#17734 已修复。正在准备发布 5.4.1，届时可更新使用。
