### ISSUE TITLE
[Bug] 'mouseover' does not fire from external draggable

### ISSUE THREAD

**Issue by ataft** [apache/echarts#17940]
### Version

5.4.0

### Link to Minimal Reproduction

https://codepen.io/ataft/pen/XWYzYag

### Steps to Reproduce

See the CodePen

### Current Behavior

In the CodePen, when dragging the "Drag Me!!!" element onto the eChart container, the `chart.on('mouseover')` event is not called. Without dragging, the `mouseover `event is called. See the console log.

### Expected Behavior

In the CodePen, when dragging the "Drag Me!!!" element onto the eChart container, the `chart.on('mouseover')` event should be called.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 107.0.5304.88
- Framework: n/a
```

**Comment by Ovilia** [comment]
This is as expected. `chart.on('mouseover')` is only fired when mouse moves over the data. Listen to the chart container dom event to do this.

**Comment by ataft** [comment]
With the suggested chart container dom event, is there a way to get the component type that the cursor is over?

**Comment by Ovilia** [comment]
You should listen to the dom container for all kinds of events, just like you do with any other dom elements.
