### ISSUE TITLE
[Feature] Tree Map contain the roaming space

### ISSUE THREAD

**Issue by Keoooo** [apache/echarts#17950]
### What problem does this feature solve?

in the treemap options I can drag the chart completely out of view. Having looked through the docs I can not see a suitable option for this. I want roam mode to be available but I want to limit the range it can travel.

![Screenshot 2022-11-22 at 10 39 06 am](https://user-images.githubusercontent.com/33136365/203179906-5121ff57-2d64-4e1b-a83b-b90cfb1ab952.png)

### What does the proposed API look like?

Add a limit option to the roam feature to prevent the treemap going out of range 

something like 

```
roamBoundary: {
height: 
width: 
}
```

**Comment by Ovilia** [comment]
A pull request is welcomed. BTW, the API design doesn't seem to be reasonable enough. If you want to confine the treemap in a certain area, setting `width` and `height` alone is not helpful.
