### ISSUE TITLE
[Feature] 请问如何支持自定义绘图引擎

### ISSUE THREAD

**Issue by ljianc** [apache/echarts#17952]
### What problem does this feature solve?

希望在React Native上使用Echarts，（不嵌入webview） 。是否支持自定义绘图引擎？
找到的绘图引擎如下：
1 https://github.com/software-mansion/react-native-svg
2 https://github.com/shopify/react-native-skia

### What does the proposed API look like?

如果使用自定义引擎，需要从哪一块代码介入进去，以及实现思路和要点？

**Comment by plainheart** [comment]
可以参考 [zrender](https://github.com/ecomfe/zrender) 内置实现的 [SVG](https://github.com/ecomfe/zrender/blob/master/src/SVG) 和 [Canvas](https://github.com/ecomfe/zrender/blob/master/src/canvas) 渲染器。
