### ISSUE TITLE
echarts 4.x版本旭日图如何去掉最内环多余的线？

### ISSUE THREAD

**Issue by cooper1x** [apache/echarts#17951]
### Version

4.8.0

### Link to Minimal Reproduction

https://jsfiddle.net/9o6zL4ug/2/

### Steps to Reproduce

我创建了个在线demo，里面可以看到效果。
<img width="373" alt="image" src="https://user-images.githubusercontent.com/9080789/203197069-ad796027-105e-426c-8da0-f5a5ff729531.png">
这根线的出现不符合我的预期，我想去掉这根线，请问应该怎么操作呢？

我目前使用的版本是4.8.0，我看文档上的5.0版本是默认没有这根线的，但4.x升级到5.x可能会导致诸多问题，所以先来这里问问，看看有没有配置项可以解决这个问题。

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS:macOS Ventura
- Browser:Chrome 109.0.5414.10（正式版本）dev (x86_64)
- Framework:Vue@2
```

### Any additional comments?

-

**Comment by Ovilia** [comment]
Fixed in #16425 which was released in v5.3.1. If you don't want to use v5, you can fork this repo, `git check` to the version you use, and make the changes as #16425 does.
