### ISSUE TITLE
[Bug] symbolRotate for legend is neither inherited nor being set in case of scatter series.

### ISSUE THREAD

**Issue by Teja0191** [apache/echarts#17955]
### Version

5.4

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdHhMYCwcvHHoeOQAtgBGwP4EtGBGjNCs_srtpCMTUyYQAF402ZlDYWOT_gBKwGDMNBUHCbDQjKM0tNqMr8EediRtJMusVNABAQkF87ABuIA

### Steps to Reproduce

1.Plot a basic scatter chart.
2.Add symbol as triangle and symbolRotate as 180 in series object.
3.Plot legend by legend object in options

### Current Behavior

![symbolRotate issue](https://user-images.githubusercontent.com/96459765/203399389-b6373a0c-de50-46b0-9258-cb7b95cdb6f1.PNG)

Legend symbol and series symbol are not on sync.

### Expected Behavior

Series symbols rotation should be inherited by legend.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Related to #17359
