### ISSUE TITLE
The data volume of nodes is too different to display the image

### ISSUE THREAD

**Issue by love123724** [apache/echarts#17954]
### Version

5.2.2

### Steps to Reproduce

the example of offical site https://echarts.apache.org/examples/zh/editor.html?c=sankey-levels can be showed this problem that
 just using big data to replace  the data, and one of the nodes' data should beyond 1biliion, the other nodes'data should be  several hundred

### Current Behavior

Only node images with large amount of data are displayed

### Expected Behavior

Small number of nodes can be displayed

### Environment

```markdown
- OS:any
- Browser:any
- Framework:react16.6.0
```

**Comment by Ovilia** [comment]
Please provide the demo that doesn't work.
