### ISSUE TITLE
[Bug] add MarkArea to the legend

### ISSUE THREAD

**Issue by avitalze** [apache/echarts#17965]
### Version

5.2.2

### Steps to Reproduce

Is there any way to add the MarkArea of echart to the legend box output ? 
I have 2 series in my EChartsOption, 1 of them have markArea with color and data. 
In addition, I have in my EChartsOption-  legend with the name of the 2 series, so I can see them in the chart itself . 
I want to add the color of the markArea to the legend box output also. There is a way to do it ? 

### Current Behavior

I can add the color and of the markArea to the legend box output 

### Expected Behavior

Add the color& name of the markArea to the legend box output

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Example - add the red color and name of the markeArea to the legend box output 
 
![Screen Shot 2022-11-24 at 9 43 53](https://user-images.githubusercontent.com/62471768/203723363-43feb9a4-5e74-4dd8-acff-acc58b60ffc3.png)

**Comment by Ovilia** [comment]
This is not supported but you can probably do this by making the markArea to be a [custom series](https://echarts.apache.org/en/option.html#series-custom).

**Comment by avitalze** [comment]
ok thanks !

**Comment by avitalze** [comment]
Another question please , I didn't find a solution or that. 
Can I partially Disable-Click on Legend ? I mean, if I have 3 series of from type lines, and I want 1 of them will be a disable-click , but the 2 others will be clickable. Is there a way to implement it?

**Comment by Ovilia** [comment]
I think probably not. If you have such requirement, you may consider using DOM to implement legend.
