### ISSUE TITLE
[Bug] not sure if its bug or im just stupid but please see

### ISSUE THREAD

**Issue by safalsthaa** [apache/echarts#17968]
### Version

5.4.0

### Link to Minimal Reproduction

https://codepen.io/vavwlxdh/pen/mdKezOJ

### Steps to Reproduce

you need to hover over the legend section and you can see that the central title and the tool tip is being overlayed. 

### Current Behavior

you need to hover over the legend section and you can see that the central title and the tool tip is being overlayed. 

### Expected Behavior

i would expect once hovered over the legend the main total section to be hidden

since we are using the title to display the total, can we have another title block to display the actual title of the chart? perhaps use a div? ive tried altering the subtext but cant seem to make it work.

please let me know if its a bug or my incompetence's 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This is not a bug, `title` is not expected to change in this case.

[This](https://echarts.apache.org/examples/en/editor.html?c=pie-borderRadius&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQAqwYAhlpQDRHphlgDKYAnrgVTFiAMxjcIAL3ywAzAFY2sAL6thpKgGMc0DgCcWS3lp37KRVUTDBgWSCEFKweiAHNXOPVQgcAtufRLdFwPaAATR2FrB1hKeQBSQ2FcEQpY7V1PAJU1WABnTwgcPIIAbSUhYVhoel8ZSgBBTW08vNgAMT1gf1yo3hB6kCKkqr16MIgAVxLYUsoAFgAGROZYgHZlygBdXuJ6ADdgCDCAGXoAIxwsAHl9zyx6GJFGAt30HxxfHn4ZSqrYc7APRhTwAJXGUxmAEZFm9iIDgZ4AMK2IFUADEIixI3-CJBegA6scwAALAgAJiUgThD0uWEi_3yJOAAHcCM8sK8qcQQMA8j4oNATJkDNyglVPiASfR-TM_lVaVcGYymayCM5Jjg4cIxLouFJ6kscYzdWACTg3CS0pRAVgwtl_soxTSLlcThBoL9ueg8sy2bAOQVndywvQGGVvchYPtGJqCDD5gAOVY1OpULg4eh6TQk2AAUWgrg9OEoOUjSGjsZkawUKdq9QAIhA9DhNGBS-L_hWY1g47B5InYdV61Q8756BAmGWVd2qwQk_M62nYgBVaCC2ANMJ5DvaqM9vuyRZD1P1ABqxxwwE32473K2Sid6AfygA3CgUL5eEjpXowAA6GAAApKF8YBpivSZ21WICAEoEAAPkIdAvx_LMAIKMBrnAQUgPlTABGQqoOHIKhaAYJhHwsWCUGUGjUN_ADgNA8CCmAO4DBg-D4CQyoGPQ_9MOwyBgPwnxCPldhOCoB0VGo2jYKAA) is what you want.

**Comment by safalsthaa** [comment]
Hi thank you for your reply,

Ok title isn’t expected to change however, is there a way to add a title
other than using options.title also when I hover over the legend section
the total from the title is overlapping

**Comment by Ovilia** [comment]
See my above link.
