### ISSUE TITLE
[Bug] Electron pie error

### ISSUE THREAD

**Issue by balderdash123** [apache/echarts#17964]
### Version

version>=5.0.0

### Steps to Reproduce

4.9.0 works

### Current Behavior

Cannot create property 'event' on string 'pieToggleSelect'

### Expected Behavior

latest version works

### Environment

```markdown
Electron
```

**Comment by Ovilia** [comment]
Please provide a demo without Electron. If it only occurs with Electron, check your environment or ask in the community of the framework you use.
