### ISSUE TITLE
[Bug] Stacked Bar Chart with yAxis { type: 'log' } seems very broken

### ISSUE THREAD

**Issue by HenrikDK** [apache/echarts#17960]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=PYBwLglsB2AEC8sDeBYAULWAPAgliAzgFzLqaYAmAhmFSQNoDkOjANLIwEJscDCPjACICAoowC6ZWAF9WUgJ55CJJLCmYw8kAFMSjADbAA5mymypBbQCcI24rHrrSGcpRp0HARnYAmAMzsACyBQQGwAAzici6uALZUWCSBAU6Y0FSxuhyWNnaepjHkmjp6AEZUVgWumAS0AMYA1npYjE7mhaiFbrQM4ex9EeyeA5HR1bDpmXo5tgQ-VdXFWYzllWPVtVSNza2F7a6d49Q9DgCsQb5h57CeUakTGcszdn4LrktlFW_km9scLW11pI0NIANxAA

### Steps to Reproduce

When using the type parameter 'log' to produce a logarithmic stacked chart the rendering completely breaks when ever the first series encounters 0 values, even though other series might have a non 0 value. it seems like scaling and positoning calculations are wrong :) 

Example 1 (broken):
https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=PYBwLglsB2AEC8sDeBYAULWAPAgliAzgFzLqaYAmAhmFSQNoDkOjANLIwEJscDCPjACICAoowC6ZWAF9WUgJ55CJJLCmYw8kAFMSjADbAA5mymypBbQCcI24rHrrSGcpRp0HARnYAmAMzsACyBQQGwAAzici6uALZUWCSBAU6Y0FSxuhyWNnaepjHkmjp6AEZUVgWumAS0AMYA1npYjE7mhaiFbrQM4ex9EeyeA5HR1bDpmXo5tgQ-VdXFWYzllWPVtVSNza2F7a6d49Q9DgCsQb5h57CeUakTGcszdn4LrktlFW_km9scLW11pI0NIANxAA

In this example i have modified an existing demo of a log stacked chart and changed the last value of "series1" to 0 immediately the rendering of the chart breaks and max value is set as 10 and most of the data dissapears from the chart. 

```
option = {
  xAxis: {
    data: ['A', 'B', 'C', 'D', 'E']
  },
  yAxis: { 
    type: 'log',
  },
  series: [
    {
      data: [1, 23, 44, 43, 0],
      max: 43,
      name: 'series1',
      type: 'bar',
      stack: 'x'
    },
    {
      data: [0, 0, 0, 10, 0],
      name: 'series2',
      type: 'bar',
      stack: 'x'
    },
    {
      data: [5, 4, 23, 5, 1],
      name: 'series3',
      type: 'bar',
      stack: 'x'
    },
  ]
};
```

Example1 (rendered correctly):
If you then modify series1 again and set the last value to 1 it renders correctly.

https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=PYBwLglsB2AEC8sDeBYAULWAPAgliAzgFzLqaYAmAhmFSQNoDkOjANLIwEJscDCPjACICAoowC6ZWAF9WUgJ55CJJLCmYw8kAFMSjADbAA5mymypBbQCcI24rHrrSGcpRp0HARnYAmAMzsACyBQQGwnuJyLq4AtlRYJIEBTpjQVDG6HJY2dp6m0eSaOnoARlRW-a6YBLQAxgDWeliMTuYFqAVutAwADOx9sAOeAz2RKbBpGXrZtgQ-lVVFmYxlFVFVsDVUDU0tBW2uHRvU3Q4ArEG-YRfhY50T6cszdn4Lrkul5W_kWzscza11rBJGhpABuIA

```
option = {
  xAxis: {
    data: ['A', 'B', 'C', 'D', 'E']
  },
  yAxis: { 
    type: 'log',
  },
  series: [
    {
      data: [1, 23, 44, 43, 1],
      max: 43,
      name: 'series1',
      type: 'bar',
      stack: 'x'
    },
    {
      data: [0, 0, 0, 10, 0],
      name: 'series2',
      type: 'bar',
      stack: 'x'
    },
    {
      data: [5, 4, 23, 5, 1],
      name: 'series3',
      type: 'bar',
      stack: 'x'
    },
  ]
};
```

Example 2 (switched series order, broken)
https://echarts.apache.org/examples/en/editor.html?c=line-marker&code=PYBwLglsB2AEC8sDeBYAULWAPAgliAzgFzLqaYAmAhmFSQNoDkOjANLIwEJscDCPjACICAoowC6ZWAF9WUgJ55CJJLCmYw8kAFMSjADbAA5mymypBbQCcI24rHrrSGcpRp0HABnbfYvgIy-nuJyLq7QVAC2uhyWNnYATKZh5Jo6egBGVFbJrpgEtADGANZ6WIxO5imoKW60DP7sCQDM7AAsbe2tfiFOmJFUWCRtrX2wEdF6cbYE_rl5aTGMWTmhebAFVCVlFSlVTjXr1PUOAKztTd3nsP69teNRS9N2zfOui5nZb-Sb2xzllTWsEkaGkAG4gA

If we switch the order of the series so "series2" comes before "series1"
```
option = {
  xAxis: {
    data: ['A', 'B', 'C', 'D', 'E']
  },
  yAxis: { 
    type: 'log',
  },
  series: [
    {
      data: [0, 0, 0, 10, 0],
      name: 'series2',
      type: 'bar',
      stack: 'x'
    },
    {
      data: [1, 23, 44, 43, 0],
      max: 43,
      name: 'series1',
      type: 'bar',
      stack: 'x'
    },

    {
      data: [5, 4, 23, 5, 1],
      name: 'series3',
      type: 'bar',
      stack: 'x'
    },
  ]
};
```
The result is completely garbled with multiple series going missing.

In short it seems the rendering engine has a hard time handling type: 'log' on the y axis for stacked bar charts.

### Current Behavior

Rendering breaks on stacked bar charts when using logarithmic yAxis "type" and series contain 0 values especially in the first series.

It seems the scaling information for the chart is calculated incorrectly when the first series contains 0 even if other series contain positive values.

Judging from this issue, it's been known for a while and is affecting multiple other users:
https://github.com/apache/echarts/issues/9801

### Expected Behavior

Echarts should correctly rescale the bars according to the yAxis, and handle the existence of 0 values in any series without it affecting the rendering of the chart.

### Environment

```markdown
- OS: windows 10
- Browser: Chrome
- Framework: Vue3
```

### Any additional comments?

This is a simplified example from our production environment, where we're using echarts to represent errors over time, meaning most of our series have 0 values in them.

Example 3 (More complicated production data)
https://echarts.apache.org/examples/en/editor.html?c=bar-background&code=GYVwdgxgLglg9mABHAbgUwE4pmg7gYQAsBDDKAMTgwFtiopMAKAB1OOoGcBKRAbwFgAUIhHIQUZuMQBeRAHIAPABMYKAHxzEAakSsM7DgG0ADAF0AdGHZohoxGnRgoHGbradzGNEpAQ0jRmIAGkQAIx5pNW1ibW1Q8xRiABsQNBDjLltRGGBERgc0JxcojL4suxE4cUkobVlFDlYkDigATyS0aQAiYCS4OgAuDBgAc0IoAG5aDBGYMABaDuAoAYAmY2YADwmIOD6MAYBiADZTieAEKHncNFHxgYBOY2MutQBRR2cFAHpG4jA1D8VOo5OUKlUJFItPVlKpEC12p0utNZgsoHBmANEABWLavUHCCoiC4YPIwVzGCaIckKNz6DwdMAjKCEKkwLRaHgCQlEuw5PJ6AyGGAWRIpNCIEpcbm82ViSG1aHyWEg2KCzjCizTADWmDV7iMIvMHEwOA4ADlrLE5FiFH9mm0Ot1ev0VsMxpMUXNFmhlmsNttdvsjqdjudLtdbh7Hs98fr6YbRclUtafvbAd9gRoJmDZQBfXOiAs8xDFuwQmp1ZWZ1QaMFeKAgDBICviITFoQQOhoEZUVquQxdYwPAYAFmxXSCXQAjMYBrGp7OBtOJ4u5wBmF5rsermfT-dbvfL3fT_ebydH8cX6erA_X28r-8Dc-L29Xxfru8f4_Xz8vmefu-M6jl-wE_ouIH_tOIFASuoFwY-i7Ys-h5wbBxzwRhiEzhhUEYbBADs8FEdh05EVBRGwQAHPBNGkTRUE0bBI4LjOI6kSOUEjkB6ygbx2G8f-vE8furGrPuAlnoe4k7heqy3mJD67vJKFyW-ymfmJn4CX-0mAbuzygYZ2GGf-hlAcYomHpZ4FDlJF42RZCnWUpDm3mZ6kOZp1naQZulebJU7GCBrHBbZYVmTBBnIaFyEmchZnIRZGGhVhBm4dZ-EGURoUkdlqlBZRBk0aFdHFQVQ5MQZLHWex1UVcOsmmEIQhKHQMSyIYYK8F0VjUGgXQDF0JrDGgHDThebVQMQg0mEExhBKOqzzStC1ratG3rVtK2jqOm37dth0bas65BOJB0XUd62jlRl13VdQTrg890vdto4PR9B2mFObTMANQ2hKQF4tMQEDaoNXSbF0eZBN1vXWBDI1mqsk3tbNn3rdOr3Yxj-3LUd-M40TuMk8TG1Y5jQRY8thPLRTX0_a0f0Q4DGDA9NYMQ1DMNw31_3DaaY3rqj03o9jxz00dWOS1Tssy5TUsrbOp0rscF2rA8auE6T2JY8cC3Ys9-tBIbQTG6bT2y4r23a2TCtBA8WMEUr8lneuzs3qd667UEzve2ru2nVd31dL9_Os-zoPg0N3OwyWPV84jgscKOIszQMc2k1nds59nee5wXNuF_NIdhyzQNTiDnMx9DQjNYIQgYrACCuDKoiwFAHRYm3RIMJsKyIF0bwYBgVAuKgeoshKSTEC0iCrKOiCEFUGAcJOhYiH3UAAMqOmg3cbxUFxOAA6lG9yD2AVC0Ek68lrKx87zAABe--INOauH3YQZUFiXQjF4VoXRD483vqIVgSgVBMixIYbE6R4GIHevXOwoC7Doj2LATEZQwGb3dCMTAWI5DEE2DADgcg46ymIaQgACnAOYDADjYLlO3Jmb85AcBIEoOAuACT5gobyEktB6AEOQOgLAOACAkDIJQGgdAGFglQaIDo-CwBKAPmAjh3CsTAGSCafhIhFEiE2AAQRIRwdRsoprECxF2BgvYMCtAUfoxAACYBqKYbyJYA9ZzOO_pcYgcwAAyxBQhoCSFiKAGBUi-NEKEOA9A4DUCxAtQ-6IsGbhiSId0F9ZxOLBK0UxpCLG8jDoQsUqRyGH0aEkGAUBAlzDfj3OUmjcDaN0TYHBpZMnwi7F3RAkTUh5JLP8GAQj4BgAACJNjoOMrEm4UkliRmNLEVj2wTCAA

Since some systems will have periods of time where the rate of errors are pretty high compared to other systems they can drown out other systems in the chart, therefore we would like to switch to a logaritmic view but it seems very broken.

**Comment by professorabhay** [comment]
I am interested to work on this issue. Its seems easy to solve this issue with little bit guidance.

**Comment by DanielBogenrieder** [comment]
we also run into this issue. Is there any solution to it?

**Comment by HenrikDK** [comment]
Nope :(

**Comment by JKeita** [comment]
meaningless answer

**Comment by Ovilia** [comment]
See conclusion at [#19234](https://github.com/apache/echarts/issues/19234#issuecomment-1776794193). Stacked bars using log axis is misleading and thus this problem is not going to be fixed.
