### ISSUE TITLE
[Bug] import echarts from 'echarts'   echarts is undefined

### ISSUE THREAD

**Issue by beat-the-buzzer** [apache/echarts#17974]
### Version
^4.6.0
import echarts from 'echarts'
echarts is undefined.

**Comment by plainheart** [comment]
If you are using v5, please use named import instead of default import. See also [v5-upgrade-guide#importing-echarts](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/#importing-echarts)

**Comment by beat-the-buzzer** [comment]
> If you are using v5, please use named import instead of default import. See also [v5-upgrade-guide#importing-echarts](https://echarts.apache.org/handbook/en/basics/release-note/v5-upgrade-guide/#importing-echarts)

V4.6.0
import echarts from 'echarts'    =====> cannot work
import echarts from 'echarts/lib/echarts' =====> works
