### ISSUE TITLE
[Feature] vertical align center visualMap's text with itemSymbol

### ISSUE THREAD

**Issue by emewjin** [apache/echarts#17972]
### What problem does this feature solve?

- chart: Calendar Heatmap
- demo: https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap
- problem: visualMap's text did not vertical aligned center with itemSymbol. ![image](https://user-images.githubusercontent.com/76927618/203875952-94d02712-a37e-4ff9-8c7c-4bb301957743.png) 
![image](https://user-images.githubusercontent.com/76927618/203876273-ba087174-32f8-47a0-8dc6-40f39481371a.png)

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/76927618/203876043-40276bcc-d302-47f5-98b2-11fe1f1db50b.png)

should be

![image](https://user-images.githubusercontent.com/76927618/203876193-d6c4dbe7-aa70-46bc-ad64-ba0d473f3125.png)

**Comment by Ovilia** [comment]
It doesn't seem to be wrong on my side with Mac Chrome. This is probably due to font family. The default font of your browser is used when user doesn't provide.
