### ISSUE TITLE
[Feature] 能否在文档中增加与vue2，vue3或react整合的相关内容？

### ISSUE THREAD

**Issue by yujiahan2018** [apache/echarts#17985]
### What problem does this feature solve?

现有文档都是纯html+css+js形式，没有与其他第三方js框架整合的相关实例代码，希望文档可以完善

### What does the proposed API look like?

```vue

<template>
  <div id="app">
    <!-- 相关代码 -->
  </div>
</template>

<script>
//相关代码
</script>

<style>
</style>

```

**Comment by zhangxinyong12** [comment]
我觉得不用完善。本身就是纯js和框架没有关系。

**Comment by yujiahan2018** [comment]
但是现在不会用啊



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月29日 15:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [apache/echarts] [Feature] 能否在文档中增加与vue2，vue3或react整合的相关内容？ (Issue #17985) |

我觉得不用完善。本身就是纯js和框架没有关系。
