### ISSUE TITLE
[Feature] sankey data very much  so stuck

### ISSUE THREAD

**Issue by y912765390** [apache/echarts#17989]
### What problem does this feature solve?

I want to optimize the focus fade out effect of "sankey". When there is a large amount of data, such as my links to 7000 and data550, my focus fade out. The mouse movement will be too laggy. The interaction was very poor. I want to interact smoothly

### What does the proposed API look like?

I want to optimize the focus fade out effect of "sankey". When there is a large amount of data, such as my links to 7000 and data550, my focus fade out. The mouse movement will be too laggy. The interaction was very poor. I want to interact smoothly

**Comment by Ovilia** [comment]
Sankey series is probably not designed for data amount as much as 7000. Can you give an illustrator screenshot to let us know whether this design is reasonable?
