### ISSUE TITLE
[Feature] How to add the label or text ?

### ISSUE THREAD

**Issue by btdan** [apache/echarts#17981]
### What problem does this feature solve?

Hello, I use the example just as follows url:  https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush
![image](https://user-images.githubusercontent.com/5276480/204137245-cb427b3e-4619-4e41-944f-122517a3cc26.png)

I want to add the label or text on the shootscreen just as shown with the rectangle and red arrow.
I know that 

 title: {
        text: '上证指数',
        left: 100
      },	
can add one url link ,but how to add two or three url links?
Thanks very much. 
Best wishes.

### What does the proposed API look like?

Sorry  I don't know the detail api at all.

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#title

**Comment by btdan** [comment]
Thanks very much for your reply.
And now I can add multi title for the whole webpage.
But I  still do not know how to add title to the grid, just as know in the picture above about "成交量"
Thanks again.

**Comment by Ovilia** [comment]
You should calculate the position by yourself.

**Comment by btdan** [comment]
Thanks very much.
I get it and it work well now.
Thanks again.
Best wishes.
