### ISSUE TITLE
[Bug] sankey lag

### ISSUE THREAD

**Issue by y912765390** [apache/echarts#17988]
### Version

5.4

### Steps to Reproduce

A very common "sankey", when the number of 'links' is relatively large. For example, if my "links" length is 7000, it will be very stuck. At this time, the data length is 550。When the mouse moves, the focus and fade actions get stuck.
I want this effect "emphasis:{

focus: 'adjacency'

},”

But I don't want to show stuck。
how can i do 

### Current Behavior

stuck

### Expected Behavior

fluent

### Environment

```markdown
- OS:
- Browser:
- Framework:
windows vue3  ts
```

### Any additional comments?

data is  very much

**Comment by Ovilia** [comment]
If this is the same problem with #17989, please close one.
