### ISSUE TITLE
[Bug] cannot set axis.min/axis.max for type='time' chart

### ISSUE THREAD

**Issue by bbcfive** [apache/echarts#17986]
### Version

5.4.0

### Steps to Reproduce

1. xAxis type is 'time', we has a tab option for '4H/1D/7D', we want the xAxisLabel only show the period for choosed option, eg: if option is 4H, the min label is 4H before Now, the max label is Now. 
 

### Current Behavior

But it doesn't work by setting min/max to limit the label range:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/22639560/204430501-f8600f2a-ca23-44cd-aff5-c5adf47c386f.png">

### Expected Behavior

Expected the min and max value of axisLabel works, and the scale can be fixed by setting ticks length.

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 96.0.4664.55
Framework React@18
```

**Comment by bbcfive** [comment]
@Ovilia @pissang can you help have a look? I cannot set the axisLabel range or scale or ticks length when xAxis type is "time"

**Comment by Ovilia** [comment]
This should not be related to `min/max`. It should relates to `interval` but time axis's interval is not controlled by the user.
I'm working with `formatterMinUnit` in #17311 but it only supports 1 hour/day/... interval rather than 4 hours. Do you think it is helpful to you?
