### ISSUE TITLE
[Feature] About dataZoom Back;关于dataZoom放大后回退

### ISSUE THREAD

**Issue by haozhelee** [apache/echarts#17999]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/26142398/204775582-a7322066-a71b-47a6-83ab-f412489550a3.png)
现在使用dataZoom中如果对某个区域放大了若干次，如果想要回到初始的缩放大小，那么就需要点击回退按钮相应多的次数。
而如果使用dispatchAction，设置datazoom的start和end为0和100。但是回退的按钮却一直处于激活的状态。
想请问，今后更新会不会推出类似一键返回初始缩放状态的功能？

### What does the proposed API look like?

dataZoom 可以自定义配置一个新的类似restore的按钮，但是这个restore并不会让图表返回初始状态（不会把数据清除）。

**Comment by Ovilia** [comment]
没有这方面的开发计划，如果感兴趣的话欢迎 PR
