### ISSUE TITLE
[Feature] 怎么在 tooltip 底部显示数据做汇总或者其他的额外计算

### ISSUE THREAD

**Issue by geekpeng** [apache/echarts#17994]
### What problem does this feature solve?

在使用 5.3之后 使用 valueFormatter 可以显示方便去格式化显示series的数据

但是在需要做一些折扩展显示: 如下图  需要在 tooltip 底部显示数据的汇总 ..  平均值   在tooltip 的顶部格式化显示日期就不得不放弃使用 valueFormatter 而需要使用原来的 formatter 方法

<img width="393" alt="image" src="https://user-images.githubusercontent.com/5426866/204747098-c42ec56d-ac47-406c-953f-f751723f4b39.png">

### What does the proposed API look like?

希望可以增加一些方法来处理 头部跟底部的 显示

tooltip: {
    trigger: 'axis',
    headerFormatter: header => `${new Date(header).toDateString()}`,
    valueFormatter: value => `${value.toFixed(2)}`,
    footerFormatter: params => {
          //do process 计算汇总数据
    }
  }

**Comment by Ovilia** [comment]
This seems to be a nice feature but I'm not sure if it should be integrated in ECharts because users may have varied requirement for the tooltip and it is expected to use custom render formatter in these cases.
