### ISSUE TITLE
[Feature] Get a list of associated data in tooltip formatter for map chart

### ISSUE THREAD

**Issue by MrSquaare** [apache/echarts#18000]
### What problem does this feature solve?

Currently, it is impossible to have a list of data related to a map object name

Example:
For country A, there is two values : 1 and 2

```js
option = {
  // ...
  series: {
    type: "map",
    map: "map name",
    // ...
    data: [
      { name: "CountryA", value: 1 },
       { name: "CountryA", value: 2 },
    ],
  },
}
```

`tooltip.formatter` will return only one of the data (actually, the first one)

### What does the proposed API look like?

A new map-specific tooltip option

Example: `mapGroup: "name" | "data"`

**Comment by Ovilia** [comment]
Tooltip should not contain the overall data. You should keep the data by yourself.
