### ISSUE TITLE
[Bug] filterMode = 'weakFilter' 时 connectNulls: false,会失效

### ISSUE THREAD

**Issue by 1980882096** [apache/echarts#18018]
### Version

最新版本

### Steps to Reproduce

dataZoom-inside.filterMode = 'filter' 时正常
dataZoom-inside.filterMode = 'weakFilter' 时 connectNulls: false,会失效 空line会自动连接

### Current Behavior

dataZoom-inside.filterMode = 'filter' 时正常
dataZoom-inside.filterMode = 'weakFilter' 时 connectNulls: false,会失效 空line会自动连接

### Expected Behavior

dataZoom-inside.filterMode = 'weakFilter' 时 connectNulls: false,正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
cannot reproduce in [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEkZSjVkA3RgBslWnQHEiEwRgAtYGAAWzdYfg9qAloIaDwIAWUeBNJYADMIPxYOKSy6AHcqRgBrfSKS2ntHWDwqIypCWFFE1DzBYTEARgBWAAYcgCYAZgnYIbG56AU_Pxyh6ZH1gBYAdimANjHrFryKZNk_NOzE9HoYaCp6MAA5Fb8u_P8229gAej-92gj2eb1WXTAHCUiTsJFsdgA3EA)
empty line is **not** connecting, as it should
