### ISSUE TITLE
[Feature] Gauge - Detail - Formatter

### ISSUE THREAD

**Issue by na-am** [apache/echarts#18021]
### What problem does this feature solve?

hi @ all

i've a gauge with two values
https://echarts.apache.org/examples/en/editor.html?c=gauge-multi-title
it would be nice if i'm able to add a suffix for both values with different units in the formatter.
e.g. formatter: [{value1} °C , {value2} H%]

thx in adv
na-am

### What does the proposed API look like?

[{value1} °C , {value2} H%]

**Comment by huangyulie** [comment]
I'm finishing this feature and you can see if it's the same as you think.😁

**Comment by plainheart** [comment]
Hi @na-am, please refer to https://github.com/apache/echarts/pull/18100#discussion_r1056760291 for the solution.
