### ISSUE TITLE
[Bug] how to make the label slant to the width of the pie chart

### ISSUE THREAD

**Issue by MNhat0308** [apache/echarts#18020]
### Version

5.4.0

### Steps to Reproduce

How to make the label slant to the width of the pie chart?

### Current Behavior

I have a chart like this 
![Screen Shot 2022-12-05 at 16 11 30](https://user-images.githubusercontent.com/57012342/205598525-85a657ab-e1b2-4135-8717-dc2bdfe086c9.png)
Here is my option 
 
`series: [
    {
      type: 'pie',
      radius: ['20%', '70%'],
      label: {
        show: true,
        position: 'inside',
         formatter: function (params) {
                  return `${params.percent}%`
                },
      },
      emphasis: {
        label: {
          show: true,
          fontSize: '40',
          fontWeight: 'bold'
        }
      },
  ]`

### Expected Behavior

So i want my percent slant to  the width of the pie chart like this
![Screen Shot 2022-12-05 at 16 16 04](https://user-images.githubusercontent.com/57012342/205599489-9fefbdff-ff54-48b0-bb44-f9f82d57dd2d.png)
I have also try rotate but now working as expected

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 96.0.4664.55
Framework: reactjs
```

**Comment by plainheart** [comment]
You can try to set `label.rotate` to `'radial'`.

**Comment by MNhat0308** [comment]
both prop `rotate` :  `radial` and `true` also return this
![Screen Shot 2022-12-05 at 16 46 07](https://user-images.githubusercontent.com/57012342/205605751-0c6b23c5-ef5b-43de-90c6-8038afcf913f.png)
