### ISSUE TITLE
[Bug] [Sunburst] Uses of startAngle provoke labels display bug

### ISSUE THREAD

**Issue by JREGN** [apache/echarts#18023]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/882hov

### Steps to Reproduce

1. Take the sunburst example : https://echarts.apache.org/examples/en/editor.html?c=sunburst-simple
2. Define a startAngle property like this :

option = {
&nbsp;&nbsp;&nbsp;&nbsp;series: {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: 'sunburst',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;startAngle: 180, // <--------------------------
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data: data,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius: \[0, '90%'\],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label: {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rotate: 'radial'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
};

### Current Behavior

Label with rotate value to 'radial' are upside down
![image](https://user-images.githubusercontent.com/41118520/205698505-1d61a1d5-081b-4130-9ec2-9e51fd51ee0e.png)

### Expected Behavior

Label in a good position

### Environment

```markdown
- OS: Windows 10
- Browser: Brave Version 1.46.133 Chromium: 108.0.5359.71
- Framework: Angular 14.2.2
```

**Comment by JREGN** [comment]
Same problem if you set the clockwise option at 'false'

![image](https://user-images.githubusercontent.com/41118520/205718584-026ae1df-334d-4500-8d38-4b53524999f4.png)

**Comment by helgasoft** [comment]
Correct, and ```data: null``` doesn't work either...
Experiencing the [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) concept in action (garbage in, garbage out) 😈
