### ISSUE TITLE
[Bug] new SVG renderer fails to render labels on line charts

### ISSUE THREAD

**Issue by greggf** [apache/echarts#18027]
### Version

5.3

### Link to Minimal Reproduction

https://codesandbox.io/s/apache-echarts-5-3-ssr-demo-forked-022g8m?file=/src/index.js

### Steps to Reproduce

I used the example chart in 5.3 update and changed it to "line" from "bar", and added label { show: true }

### Current Behavior

labels do not show on line chart.  They show on bar chart.  

### Expected Behavior

labels should display on line chart

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Framework:
```

**Comment by plainheart** [comment]
In SSR mode, the animation should be disabled. But it seems the line series still unexpectedly applied the animation. Currently, a workaround is to disable the animation via `animation: false`.
