### ISSUE TITLE
[Feature ]  minAngle When minAngle is set, it is hoped that the corresponding fan-shaped area will not be displayed when the data is 0

### ISSUE THREAD

**Issue by xiaomeinvG** [apache/echarts#18030]
### What problem does this feature solve?

```js
option = {
  legend: {
    orient: "vertical",
    left: "left",
    data: ["Apple", "Grapes", "Pineapples", "Oranges", "Bananas"]
  },
  tooltip: {
          trigger: 'item'
        },
  series: [{
    type: "pie",
    minAngle:30,
    radius:['70%', '96%'],
    itemStyle: {
      borderRadius: 0,
      borderColor: '#fff',
      borderWidth: 2
    },
    labelLine: {
      show: false
    },
    label: {
      show: false,
      
    },
    data: [{
      value: 3,
      name: "Apple"
    }, {
      value: 310,
      name: "Grapes"
    }, {
      value: 0,
      name: "Pineapples"
    }, {
      value: 135,
      name: "Oranges"
    }, {
      value: 10000,
      name: "Bananas"
    }]
  }]
}
```

<img width="827" alt="image" src="https://user-images.githubusercontent.com/40682393/206086737-64312b3a-3f66-45d7-8dff-653154a3a995.png">

 I hope that the fan area with 0 is not displayed

### What does the proposed API look like?

I hope you can provide a switch in the ”series“ to decide whether to display the area of ​​0, which can be displayed by default

**Comment by Ovilia** [comment]
You should replace zero data with `'-'`.

**Comment by xiaomeinvG** [comment]
But my project requires the default value to display 0, so I can't use "-"

**Comment by plainheart** [comment]
After you do as @Ovilia suggested, the items with the value `0` will be invisible, so I think it's okay to use `'-'`.

**Comment by xiaomeinvG** [comment]
Do items with a value of "0" refer to rounded decimals? I remember that users can define the number of decimal places by themselves, can this solve the situation you mentioned?

**Comment by xiaomeinvG** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/40682393/206146916-9e03491b-b429-4edf-8244-7244110ff050.png">
I mean in my project, 'legend' needs to be as shown in the picture, so I can't use '-', but I want to not show the fan area with 0 data
@Ovilia

**Comment by Ovilia** [comment]
@xiaomeinvG Try this

> You should replace zero data with `'-'`.

**Comment by xiaomeinvG** [comment]
@Ovilia  I am sorry i can't, You know, by request, I have to show 0

**Comment by Ovilia** [comment]
@xiaomeinvG Where's your demo?

**Comment by xiaomeinvG** [comment]
According to your suggestion, I got the solution, thank you very much
