### ISSUE TITLE
[错误]ipad5代出现更新系统为16.1.1后出现断线虚线问题

### ISSUE THREAD

**Issue by pangzhenzhu** [apache/echarts#18031]
### Version

5.0.2

### Steps to Reproduce

React项目中正常按照官方的方式

### Current Behavior

其他代的ipad 升级后并没有出现这个虚线断线问题。

### Expected Behavior

虚线断线问题解决
![Uploading 7E24C244-F8CD-4ADB-8377-D09C953781F3.jpeg…]()

### Environment

```markdown
- OS:iOS
- Browser:app
- Framework:react material-ui
```

**Comment by plainheart** [comment]
注意请等上传完毕后再提交 issue，另外此类问题应最好提供简单、可复现的示例。
