### ISSUE TITLE
[Bug] tooltip 的 extraCssText 属性设置 transform 不生效

### ISSUE THREAD

**Issue by idenet** [apache/echarts#18035]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/s/px5p9v

### Steps to Reproduce

查看例子，并且切换 echarts 版本到 5.0.2，可以看到 tooltip 展示不同的样式。5.0.2 版本的 transform css 能够生效，新版本不行。

思考：新版本中通过 transform 定位，用户设置的没有添加到原有 transform 后面。导致不生效

### Current Behavior

在新版本中，tooltip 的 extraCssText 属性设置 transform 不生效

### Expected Behavior

希望tooltip 的 extraCssText 属性设置 transform 能够生效

### Environment

```markdown
- OS: macos 最新版
- Browser: 版本 107.0.5304.121（正式版本） (arm64)
- Framework: vue@2.6.10
```

**Comment by plainheart** [comment]
如你所说，tooltip 使用 transform 来定位，transform 本身不能像 transition 或 animation 那样把 translate、scale、rotate 等属性单独分开使用，所以就算能够覆盖也会导致定位错误，虽然现在浏览器开始支持脱离 transform 单独使用 translate、scale、rotate，但兼容性还不够好。想知道是什么场景需要覆盖 transform 呢？

**Comment by idenet** [comment]
@plainheart 不是覆盖，是我想让他能够生效，但现在是没有生效。我猜测是我定义的 transform 被覆盖了。因为其他属性如fontsize 这些是可以生效的

**Comment by plainheart** [comment]
这里因为 tooltip 本身要定位，是会覆盖的其他 transform 的。

**Comment by idenet** [comment]
@plainheart 能够判断如果用户设置了 transform 让他添加到定位的 transform 之后吗

**Comment by idenet** [comment]
@plainheart 或者说有其他的横屏展示方式吗？或者添加一个属性，让定位使用 5.0.2 的版本，这样就能共存了
