### ISSUE TITLE
Get the index of "coords" for series type "lines"

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18042]
### What problem does this feature solve?

If I click on a "line" created by "coords" in a serie of type "lines", I can't know what "coords" index is clicked :

for example : 

```
var mousePosition = null;

$.get(
  ROOT_PATH + '/data/asset/geo/MacOdrum-LV5-floorplan-web.svg',
  function (svg) {
    echarts.registerMap('MacOdrum-LV5-floorplan-web', { svg: svg });
    option = {
      tooltip: {
        triggerOn: 'none'
      },
      geo: {
        map: 'MacOdrum-LV5-floorplan-web',
        roam: true
      },
      series: [
        {
          name: 'Route',
          type: 'lines',
          coordinateSystem: 'geo',
          geoIndex: 0,
          polyline: true,
          lineStyle: {
            color: '#c46e54',
            width: 5,
            opacity: 1,
            type: 'dotted'
          },
          tooltip: {
            trigger: 'item',
            position: function (pos, params, dom, rect, size) {
              return mousePosition;
            },
            formatter: function (params) {
              return params.seriesName;
            }
          },
          data: [
            {
              coords: [
                [61.58708083147317, 386.87942320312504],
                [61.58708083147317, 72.8954315876116],
                [258.29514854771196, 72.8954315876116]
              ]
            }
          ]
        }
      ]
    };
    myChart.setOption(option);
  }
);

myChart.on('mouseover', 'series.lines', function (params) {
  console.log('MOUSE', params)
  mousePosition = [params.event.offsetX, params.event.offsetY];

  myChart.dispatchAction({
    type: 'showTip',
    seriesIndex: params.seriesIndex,
    dataIndex: params.dataIndex
  });
});

myChart.on('click', 'series.lines', function(params) {
  console.log('I DON\'T KNOW WHICH "coords" index is clicked')
});

```

### What does the proposed API look like?

what it would be best:

1. if I click on the line (or mouseover) generated by coords on a type "line**s**" series,
2. the "params" response should have a property "coords" which give the 2 coords between the line 
3. eg. coords: 
`coords:  [  [61.58708083147317, 386.87942320312504],   [61.58708083147317, 72.8954315876116]   ]`

example of use case:
I want to add "coords" when I click on a line "coords", so if could add a coords between two existing coords

**Comment by helgasoft** [comment]
Why not "_divide and conquer_" ? Split polyline into important segments with their own names/data.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-HK&code=G4QwTgBAtg9grgZwKYAUYIJYBcMwHYQC8EecANmQNwBQZCREA3tRK2wMYxkxgBcEAcgDE7ACwA2JAFZRAgDQs2rAO4YAJlgAW_KQqWsYABxDtsAT34BGPfqxnDSfgLUwsWJGoGLWAXxpuGZn0ILDAMAHNwpD5BbCQoeW82Q3RsXDx-ADM4PHYcfAgAChSEOQhjMBAoUogXKDKwJDyyzAAvJABKJghGrDgwAlhEVFT8vEoIHxslTJ4oEDdorJy89KKKqoQuxh6kPoHy8E2AOmQwpAQAOSqkCZ8kv2pqABJjqKxCxQAlAHkfgBUAPooACC_wAEhAANSCAD0agWIFhIAQyCwsKiMFhAFkTD81GA4FAALQAGQAalJiZluDxDGQQHhicokAAjU7AcKJVjZXJjIoITnbJJNTTgLAIY6NcIYBDuMC4wyFAQAMRQ8m6gvC_C1kw6NCURn5xCCthgXBwhn4puCoQiUTAPwygjw-CQXmCUySrEx1u9bHmVsEau5wR6MCq_FCcCQ_q9ZwwF34AG1FDaSDcnF94O5LKHWHYHE4yBg8Bd8xAS2WAMp2MiOSs1LDmsiWqNYaa1REp9NKTg8NQIFP-pTJ8SWY5SAAcAHYAAxThcAZksohnK5nZSXU_Ex1nAE5RAAmJdHucro9SOeiAC6neCY4n0_ni6nK7XG7KM6Pe_3MhXz7jpY4g3iOECgUoPgQZMNjpngmaCNmcDuEeFaFg2AhVuWnZYbWZj1vwdBlM2FoYEGbidgiWAgD2YH9mAg7DmGbCPpOs4Lsuq7rpYm4QN-v7_pYgGWMBd5gawyaXlOxxHn-q5TjIM4ziJ-7iF-P5Tn-ogAbOQEgWB0G-NB9yGZMBoBmYADCYpgFgpx7D8hhjIURrpPqij3O51BQFZNl2fgypDMgMDANEGoCAmFzHFhCAaryqwFMURzVMKrCwrCnB4AgXBINFMDhMq2I_AAqtWACiGobClihBSMmDGhAyZVZKSChXg_mZJkaIABplM1xytUg7XHDAnVogAmjeNA1b54rHGosrGFg7CaCCCV4IU6boU4CCaDAyj_GRFaRQgACSeBqEgAAe_D9Sd52XVdlGIg9123clkpUSAr1XR57k-F5PnWXNAUCOwJbsAA1uFJ3RaW2EQPFznNalECZdl9Z5QVAiWaSp2WQA0pVH32ecVw3H1JNfcc9GDh01AA5QQA)
