### ISSUE TITLE
Hide part of heatmap series

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18045]
### What problem does this feature solve?

When we use heatmap, heatmap series can overlap,
I would want to have multiple heatmap series corresponding to multiple "rooms", so the circle generated by heatmap musn't to be in other rooms: 

every heatmap should be in its "rooms"

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/53522372/206682423-8f02ba1b-0353-475d-a765-30a392a7565b.png)

**Comment by helgasoft** [comment]
You could display the local (room) heatmap only on hovering the room, in event "mouseover". This will require filtering all points inside the room, then building the heatmap.  Or have all separate room heatmaps built in advance.

Another idea is to make the entire chart heatmap invisible and display only portions of it when "entering" a room (_mouseover_).

In general, heatmaps are to show association of points of equal importance. For instance heat or noise points usually cannot be isolated to a single room, they penetrate adjacent spaces too.
