### ISSUE TITLE
no series-line.tooltip exists in documentation

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18040]
### What problem does this feature solve?

There is no "series-line.tooltip" in documenttaion but working on echarts editor

### What does the proposed API look like?

Is the series-line.tooltip working really ?

**Comment by plainheart** [comment]
Refer to https://echarts.apache.org/en/option.html#series-line.tooltip

**Comment by krabouilleur** [comment]
> Refer to https://echarts.apache.org/en/option.html#series-line.tooltip

No serie type "lineS" no series type "line"
https://echarts.apache.org/en/option.html#series-lines.type

**Comment by plainheart** [comment]
Added in https://github.com/apache/echarts-doc/commit/de006d754f77a3cb5f12f23104a081792200e62a
