### ISSUE TITLE
[Bug] Flights GL demo Not displayed properly in codesandbox and codepen

### ISSUE THREAD

**Issue by chiguayeshao** [apache/echarts#18044]
### Version

5.4.0

### Steps to Reproduce

1.Open the demo link [Flights GL](https://echarts.apache.org/examples/zh/editor.html?c=lines3d-flights-gl&gl=1)
2.Click edit in codepen icon or click edit in codesandbox button

### Current Behavior

In codepen or codesandbox display nothing

### Expected Behavior

In codepen or codesandbox need show the demo

### Any additional comments?

I think is CORS error

Access to XMLHttpRequest at 'https://echarts.apache.org/examples/data-gl/asset/data/flights.json' from origin 'null' has been blocked by CORS policy:

**Comment by plainheart** [comment]
If needed, please download this file and save it locally. The resources on the website are only accessible by the ECharts website itself. Any requests from other origins will be rejected.

**Comment by chiguayeshao** [comment]
> If needed, please download this file and save it locally. The resources on the website are only accessible by the ECharts website itself. Any requests from other origins will be rejected.

I got it. thank you!
