### ISSUE TITLE
Using a map to set the background image on a large screen will not cover the entire map

### ISSUE THREAD

**Issue by dhj0326** [apache/echarts#18051]
### What problem does this feature solve?

The background image can be spread all over the map, because the resolution is adapted in the large screen

### What does the proposed API look like?

Do you have a solution

**Comment by helgasoft** [comment]
Sorry, but the question is not clear.  Could you provide some code or at least an image ?

**Comment by dhj99116** [comment]
Thank you. I've found a solution
