### ISSUE TITLE
[Bug] xAxis的axisLabel 旋转45°后，字体颜色变淡了

### ISSUE THREAD

**Issue by henley02** [apache/echarts#18056]
### Version

5.4.1

### Steps to Reproduce

option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    axisLabel:{
      rotate: 45,
      color:"#1976D2",
      fontFamily: "SimSun",
      fontSize: 14, 
    }
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};

### Current Behavior

![image](https://user-images.githubusercontent.com/11241020/207008036-20ae8ea7-2241-48e7-a5c4-4e32d56cb1be.png)
旋转45度后X轴字体变淡了

### Expected Behavior

![image](https://user-images.githubusercontent.com/11241020/207008172-0a3e048e-0c40-4ec5-9a35-d16cb4b08ec1.png)
希望字体不变淡

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
this comes from ```fontFamily: "SimSun"```
Comment out the line or change to another font, like ```fontFamily: "Verdana"```
