### ISSUE TITLE
[Bug] globe上画scatter，label会被遮挡

### ISSUE THREAD

**Issue by AlwaysMing** [apache/echarts#18069]
### Version

5.3.3

### Steps to Reproduce

**globe的配置：**
{
    globe: {
      atmosphere: {
        show: false,
      },
      globeRadius: 100,
      globeOuterRadius: 200,
      baseTexture: gisBg, // 地球表面覆盖的图片
      light: {
        ambient: {
          intensity: 0.8,
        },
        main: {
          intensity: 0,
        },
      },
      zlevel: -100,
      viewControl: {
        autoRotate: true, // 是否开启视角绕物体的自动旋转查看
        autoRotateSpeed: 10, //物体自转的速度,单位为角度 / 秒，默认为10 ，也就是36秒转一圈。
        autoRotateAfterStill: 2, // 在鼠标静止操作后恢复自动旋转的时间间隔,默认 3s
        rotateSensitivity: 2, // 旋转操作的灵敏度，值越大越灵敏.设置为0后无法旋转。[1, 0]只能横向旋转.[0, 1]只能纵向旋转
        maxDistance: 165,
        minDistance: 165,
        alpha: 17,
        beta: 120,
        distance: 0,
      },
    },
    series: // scatter的series
  }

**scatter的series：**
{
name: 'scatter3D',
type: 'scatter3D',
symbol: 'pin',
coordinateSystem: 'globe',
symbolSize: 60, // 点位大小
zlevel: 100,
itemStyle: {
borderWidth: 2, // 边框宽度
borderColor: '#fff',
},
label: {
show: true,
position: 'top', // 字体位置。top、left、right、bottom
formatter: '{b}', // 具体显示的值
color: '#fff', // 字体颜色
borderWidth: 0, // 字体边框宽度
fontSize: 18, // 字体大小
fontWeight: 700, // 字体加粗
},
data: [{
id: item.id,
name: labelText,
value: [item.longitude, item.latitude, 0],
itemStyle: {
color: getPointColor(item.sinkRate, avg), // 各个点位的颜色设置
opacity: 1, // 透明度
},
}]
}

### Current Behavior

![image](https://user-images.githubusercontent.com/12559180/207859278-4c92143c-236e-43b9-831b-553ba6fe239b.png)

### Expected Behavior

旋转过程中无遮挡

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Well, this is by design.  Those 3D points and labels cannot permanently display **over** the globe. When the globe is rotated they will start to partially hide until they completely disappear behind it.

OTOH, one could make a [FEATURE Request] to have scatter3D points and labels "**painted**" on Earth's surface.
Similar to this:
![image](https://user-images.githubusercontent.com/13038071/208286662-b6a05d15-424e-4b88-ba5a-c91e95ac0ea0.png)

**Comment by AlwaysMing** [comment]
Thank you for your idea, but how to set its altitude in the scatter? I have set its third value to 0, but it seems not work:
![image](https://user-images.githubusercontent.com/12559180/208572989-2422192d-2d0b-4b64-a7de-c9638db4311c.png)

I read the doc [https://echarts.apache.org/en/option-gl.html#series-scatter3D.data], but still don't know how to set its altitude:
![image](https://user-images.githubusercontent.com/12559180/208573338-91b2624b-7f3e-4136-9d95-253d4182db59.png)
