### ISSUE TITLE
[new Feature] dispatchAction showTip is not work in 3D Scatter

### ISSUE THREAD

**Issue by Coderyida** [apache/echarts#18064]
### Version

echarts 5.3.3 &  echarts-gl 2.0.9

### Steps to Reproduce

      echartRef.dispatchAction({
        type: 'showTip',
        seriesIndex: 0,
        dataIndex: 2
      })

### Current Behavior

when the ts excution dispatchAction  api   the tooltip can not show in 3D Scatter chart

### Expected Behavior

but on 2D Scatter is normal

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaozhou-amazing** [comment]
咋样了铁汁，我也遇到这样的问题，是不是dispatchAction不支持3D的组件

**Comment by Coderyida** [comment]
> 咋样了铁汁，我也遇到这样的问题，是不是dispatchAction不支持3D的组件

老铁  可能GL 类的图表现在还是不支持哦，我翻了下其他人提的issue，  今年一月份，官方Ovilia 姐姐是这么回复的，如下

https://github.com/apache/echarts/issues/16356#issuecomment-1011751965

**Comment by xiaozhou-amazing** [comment]
好的，和我想的差不多，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月15日(星期四) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [new Feature] dispatchAction showTip is not work in 3D Scatter (Issue #18064)





  
咋样了铁汁，我也遇到这样的问题，是不是dispatchAction不支持3D的组件
  
老铁  可能GL 类的图表现在还是不支持哦，我翻了下其他人提的issue，  今年一月份，官方Ovilia 姐姐是这么回复的，如下
 
#16356 (comment)
