### ISSUE TITLE
add "cusror" on series type "lines"

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18068]
### What problem does this feature solve?

When I generate a serie type "lines"

```
{
          id: 'L1',
          type: 'lines',
          data: [[50, 456],
                  [110, 456],
                  [124, 450]],
           polyline: true,
        tooltip: {
          trigger: 'item',
          ....

      },
        }
```

the cursor type is "pointer", but this is no possible to change the cursor to 'move' for example.

### What does the proposed API look like?

It would be better there is a cursor option when the mouse is hover a line type "lines"

**Comment by Ovilia** [comment]
What kind of cursor do you want to set? Using `move` doesn't seem to be reasonable to me because the user cannot move the line.
