### ISSUE TITLE
[Bug] yAxis.nameTextStyle.fontSize and xAxis.nameTextStyle.fontSize not working

### ISSUE THREAD

**Issue by Cheering-baby** [apache/echarts#18072]
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXLANoBEAxAMyUCcAHACIBCpAugDRqxjA6QhFU6dGDwQA5uICmhWKQCGADwgBnUp2GwlqgArAI0MDMFdNYAJ4gpRUioAW8gCbAA7qVOwAvl08bY4sUdBXy5FAEFlFSJiIWELKxsMeSNxfHN1D0dk-WjSAFkYdTkAFQBXKSLSAHUpR0riu1LKgDExSoBlZI7S6DY_dGh5AFspYqlFMHaLbGtkD3QAMxhJiAAvWcoABg9vdE8OLnMI1WjYkUtZ0gA3eWxy9z2D9BUZCCkokjPYQZGbQBe3QClxoB-6MAd6kZMwXGwAI3keHBwhheCqEEcYDsNgAbJsAKTw9BZMA5EgARk27FgAFYAEzkqmbMmwagAFnJtAZ1AZVLprB8PM8QA&_source=echarts-doc-preview

### Steps to Reproduce

```
option = {
  color: ["#3398DB"],
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow"
    }
  },
  grid: {},
  xAxis: [{
    type: "category",
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    nameTextStyle: {
      fontSize: 30
    }
  }],
  yAxis: [{
    type: "value",
    nameTextStyle: {
      fontSize: 30
    }
  }],
  series: [{
    name: "直接访问",
    type: "bar",
    barWidth: "60%",
    data: [10, 52, 200, 334, 390, 330, 220]
  }]
}
```

### Current Behavior

The configuration of yAxis.nameTextStyle.fontSize and xAxis.nameTextStyle.fontSize is not working, whether it is given a larger value or a smaller value.

### Expected Behavior

yAxis.nameTextStyle.fontSize and xAxis.nameTextStyle.fontSize can work

### Environment

```markdown
- OS:windows 11
- Browser:chrome latest
- Framework:js
```

**Comment by helgasoft** [comment]
It works, your code is just missing [X-axis name](https://echarts.apache.org/en/option.html#xAxis.name) - like ```name: 'myXaxis'```
If you want to change X-axis _labels_, then the setting is [axisLabel.fontSize](https://echarts.apache.org/en/option.html#xAxis.axisLabel.fontSize)

[Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXLANqrrpgCeIApkQEQDGAhmDQObABOl9ANGnIATVsyLF6AWRj9Y9ACoBXGrPoB1GkNXyAFotUAxLhFUBlVmcXR6AXQHlY0ZgFsa8mhjCmqAGzrJYADMYLwgAL38AZgAGWABfe3InVwAZYBZIGCIAcmcIISE_bMT0ZP9cygANZlw8YsF0GvwU5gAjGh8iJCCQ03D_AEYAdnjBOLtBShx8LoTBPBpjGkISMiSXf3pAF7dAUuNAfujAO9T-BtgqWgZW5i5jhxEwMRIB6L5YAFYAJhf36OfYSMiACwvSIATl-_1-72-NjGMLiQA)
![image](https://user-images.githubusercontent.com/13038071/208285923-6a0031b9-3ebd-4ad3-bde1-915030153aa5.png)
