### ISSUE TITLE
[Bug] map系列中，数据标签如果经纬度是负数时显示错位

### ISSUE THREAD

**Issue by minren118** [apache/echarts#18073]
### Version

5.4

### Steps to Reproduce

我使用自己制作的一个地图数据，里面有cp节点，正常来说，它会调用这个cp节点来自定义渲染数据标签位置，但现在使用世界地图时，因其经纬度跨越-180到180和-90到90，在0-180的经度显示正常，-180-0时，就不正常，如美国是-100的经度，数据标签显示到了中国位置，同样地纬度显示也不正常如澳大利亚。

这个疸仅在数据标签上异常，在散点地图上是可以正常的。

![image](https://user-images.githubusercontent.com/28550438/208219935-1177eae7-8730-48a5-92d5-d910f071704a.png)

![image](https://user-images.githubusercontent.com/28550438/208219779-78b4c332-f6cf-40cf-9918-57a800a0331a.png)

![image](https://user-images.githubusercontent.com/28550438/208219931-ab27adac-01a0-4711-ab8a-af537e120972.png)

### Current Behavior

出现了数据标签显示错位问题。

### Expected Behavior

期待修复下这个取cp值作为填色地图时，显示数据标签位置错误的问题。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by minren118** [comment]
补充下，并不是我的goejson有问题，我自己维护的cp值虽然是文本，但最终会在代码里转成数组结构的，在中国地图这种没有跨正负经纬度的地图数据标签显示是没问题的。

![image](https://user-images.githubusercontent.com/28550438/208288601-16ef5539-b6d3-4a0b-a6b6-7daa9a333f2a.png)

**Comment by plainheart** [comment]
这好像是你转换的问题，根据截图圈出部分的正则表达式来看，只能匹配到数字部分，而无法匹配正负符号，例如，`-120.1` 会被转换为 `120.1`，这应该是是 label 位置不对的原因。
这里转换其实不必那么麻烦，按照如下方式转换即可：
```js
features[index].properties.cp = cpStr.split(',').map(t => +t)
// 或者
features[index].properties.cp = cpStr.split(',').map(Number)
```

**Comment by minren118** [comment]
献丑了，还真是自己正则没写好，之前一直搞中国地图，没看到有负数的情况，正则不兼容，感谢指导，写js不深，原来还可以这么个方式写，学习了。
