### ISSUE TITLE
Round stacked bar charts without white gap

### ISSUE THREAD

**Issue by oldwin** [apache/echarts#18080]
### What problem does this feature solve?

Hi, currently we can not round stacked bar chart in the way like on the picture
<img width="150" alt="изображение" src="https://user-images.githubusercontent.com/16270391/208517703-762ffb93-5809-4dc5-bdab-b1ab9287a544.png">

We could round only top element like this one
`barBorderRadius: isLast ? [6, 6, 0, 0] : undefined`
<img width="198" alt="изображение" src="https://user-images.githubusercontent.com/16270391/208517848-7c22eeb2-8b2a-430a-a1df-0d00b42d8274.png">

Or if you use just `barBorderRadius: [6, 6, 0, 0]` it looks ugly with white gap near 
<img width="152" alt="изображение" src="https://user-images.githubusercontent.com/16270391/208518027-d071558e-bd47-49b2-8d7f-164ddb89c669.png">

### What does the proposed API look like?

It could be done in two ways

1. With adding pseudo-element on the bar or modify bar with calllback. `itemStyle.render () => return style`
2. With change position of some elements. `itemStyle.marginTop: -6`

**Comment by plainheart** [comment]
There is a workaround for this feature. Please refer to #12319 or [this demo](https://echarts.apache.org/examples/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkA9FNgBVNtVh82GYGUo1SanHh4kwATxDUGbABaMAJsADu9WDNj0L1uw8aqr1AGaMArrgA3LAAxoxwjNhs6gBGSvTYwtQOwNouljb2-gC-xDnc6NjUNNBW4gXEFOTlRJLFPmAMAMwApFz65BTmTc4ALO2FJLHAYJgAti2D-qEwYIzCADKM8diEYKT-1PlDhgCCrGzi-kYmDABuUVv0O8TMB-zHkqemzuGiFGmGHZJWjPOEADa9AAsjAuM4ACrXTjOADq1CsEPokPM_mRADFyMiAMr_XH-aD0AC6t3QinI1COsEB-gkklg0EY41e9AAIhBSNRQmAfgyXgxYoxSHzJGx5qEANYMTDzbCikjYFbUNZ1Bnk8x2dabbbqyrq6jjECWNiPNXqnzAUL-akuWgQKk3PVDX7_RhA5oAJgADLDmt7PX7vQBGP3NPp-gCcvtgzX9pMk-pI9MkTJZDBBC2wsD2SJdBmMrKFIvz5Il0ucsqiCqKytVKYZFi1ZC2-nQSckhuNnjNDckluttopDo4bdgHZIfwBNODPthwa985D8_DsOjsM9_o3we9CZIE77jOZrL2Ph8ECS_yUuZrGELguFt_FjClMtG1dLsCVqye6tgTdsbVW2dMcuxNXsx3QAcbTMe1HTHCd0Cnd0aU9OdYGDAAOQMMMjUNYE3CMCPXWMt1jHc93bfNDzTVkADUIG8dQb0_AVnGLJ9yzfOVb2_FVf3VACgN1BlENgMCe2pQ8oKtGDnGHeCQPVZCgWDABWGNPVnDdlwwtSiODEi4xjPoKNyaix1ohgcWoYVQnMWAAFFoAoZJbzY-gOM_Z9X0rd95U_Pj60g_9NUAlsRMTT8JNNKSQugoc4NHJSGRUmlsJjTDF1gaN8MjVcMM9EiFzIhcfWJAA6cZGBAAAKWrLmwLYAEoEAAPnNBkuTAfxSDgaSSEarZP0kCBRHGHEjGKAS_3QEZSG8UgACVrAgOTATU2FNtgGNdxC9sQpyIIEOa3JiFJI6gA).

**Comment by plainheart** [comment]
> [100, 55, 20] should be a bar with height 100 + 55 + 20 = 175, but now it is 100 and 55 inside it, and 20 inside it.

In the demo above, each item in each array corresponds to the value of each category. If you hope it's a bar with a height 175, the values should be placed in the same column rather than the row.

BTW, just updated the demo.

**Comment by tadeolinco** [comment]
@plainheart this doesn't work though if the topmost data point is too small for the border radius to kick in properly. It would look like as if it was cropped. Notice the first stack with the topmost bar of value = `1`

![image](https://github.com/apache/echarts/assets/15124480/e10d2cb6-9fb5-417b-a9dc-10627d8e67c8)

**Comment by szekelyisz** [comment]
Also looking for a way to round corners of the stack regardless of dataset values.

**Comment by BenJackGill** [comment]
@oldwin Can you post the full code for the middle pic with the `barBorderRadius: isLast ? [6, 6, 0, 0] : undefined` solution?

I am trying to achieve the same here in [this issue](https://github.com/apache/echarts/issues/19275) but I cannot figure out how you implement it.

**Comment by Ovilia** [comment]
I provide a solution [here](https://github.com/apache/echarts/issues/19275#issuecomment-1818788239)
