### ISSUE TITLE
Tooltip appearing over sticky elements of the page

### ISSUE THREAD

**Issue by NrmlPtl** [apache/echarts#18098]
### Version

5.3.3

### Steps to Reproduce

```
tooltip: {
      trigger: "axis",
      appendToBody: true,
      axisPointer: {
        type: "line",
      },
      transitionDuration: 0,
    },
```

### Current Behavior

![image](https://user-images.githubusercontent.com/26079157/209177853-53cddccd-e6ef-4acb-886c-ef28645bd252.png)

Echarts appearing over sticky elements of the page. zIndex of those sticky elements is 300 and I have not set any zIndex for the charts. How do I stop tooltip appearing over sticky elements?

### Expected Behavior

Tooltip should not appear over sticky elements.

**Comment by plainheart** [comment]
Try to set `z-index` of the tooltip as a value less than the z-index of the sticky element via
```js
tooltip: {
  // ...
  extraCssText: 'z-index: ?'
}
```

**Comment by NrmlPtl** [comment]
Thank you @plainheart for the quick reply.
It worked :)
