### ISSUE TITLE
echarts的地图里，怎么获得省份或者地市的文字坐标呢？

### ISSUE THREAD

**Issue by zhuzhuzhumop** [apache/echarts#181]
![2014-01-06_143458](https://f.cloud.github.com/assets/6327728/1848971/4283a7ee-76a2-11e3-8882-f1d8ef6b5a18.png)
最近要做一个这样的功能，折线我用render画，就是折线上圆点的坐标没法定位，不知道怎么获取地市的文字坐标，希望不吝赐教

**Comment by cxytomo** [comment]
@kener 我想要一份所有城市的经纬度文件，https://github.com/ecomfe/echarts/blob/master/src/util/mapData/rawData/geoJson/china_city.json 这个已经404了
