### ISSUE TITLE
[Feature] Y轴坐标显示的数字为什么顺序是乱的

### ISSUE THREAD

**Issue by 15776869115** [apache/echarts#18109]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/43801168/209651597-cf3ac2d0-7f91-40cb-9da8-938cce65dae9.png)

### What does the proposed API look like?

y轴显示的值怎么事乱序的

**Comment by 15776869115** [comment]
> @15776869115 Please provide a demo for the issue either with [Official Editor](https://echarts.apache.org/examples/editor.html), [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

<img width="950" alt="image" src="https://user-images.githubusercontent.com/43801168/209665845-bfe77d15-3b13-40a8-b18f-ccab0a0b43f8.png">

**Comment by 15776869115** [comment]
``> @15776869115 Please provide a demo for the issue either with [Official Editor](https://echarts.apache.org/examples/editor.html), [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

====================================
render() {

    const config = {
      data:this.state.data,
      xField: 'date',
      yField: 'value',
      seriesField: 'category',
      yAxis: {
        label: {
          // 数值格式化为千分位
          formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
        },
      },
      color: ['#1979C9', '#D62A0D', '#FAA219'],
    };

    return <Line {...config} />;
  }
======================================

**Comment by plainheart** [comment]
能否给出更完整的 Demo？尽量不使用框架

**Comment by 15776869115** [comment]
> 

import React from 'react';
import { Line } from '@ant-design/plots';
import servicePath from '@/config/api';

class SrmLine extends React.Component{
  state = {
    data:[],
    clusterId:this.props.clusterId,
    trendType:this.props.trendType
  }
  componentDidMount() {
    this.asyncFetch();
  }
  componentWillReceiveProps(nextProps, nextContext) {
    this.setState({
      clusterId:this.props.clusterId,
      trendType:this.props.trendType
    },() => {
     // console.log('props.clusterId'+this.props.clusterId + 'demoline the state.clsueterid'+this.state.clusterId);
      this.asyncFetch();
    })
  }

  asyncFetch = () => {
    fetch(servicePath.clusterTrendData,{
      method:'post',
      headers: {
        'Content-Type': 'application/json'
      },
      body:JSON.stringify ({clusterId:this.state.clusterId,clusterName:'DorisDB',trendType: this.state.trendType})
    })
      .then((response) => response.json())
      .then((data) => this.setState({
        data :data.data}))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };

  render() {

    const config = {
      data:this.state.data,
      xField: 'date',
      yField: 'value',
      seriesField: 'category',
      yAxis: {
        label: {
          // 数值格式化为千分位
          formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
        },
      },
      color: ['#1979C9', '#D62A0D', '#FAA219'],
    };

    return <Line {...config} />;
  }
}
export default SrmLine;

**Comment by plainheart** [comment]
请不要使用框架，否则增加复现难度。

**Comment by Ovilia** [comment]
> @15776869115 Please provide a demo for the issue either with [Official Editor](https://echarts.apache.org/examples/editor.html), [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

用这里的在线代码平台
