### ISSUE TITLE
[Bug] Getting "ECharts Execution Error app is not defined"

### ISSUE THREAD

**Issue by SaqibOctave** [apache/echarts#18110]
### Version

5.2.2

### Steps to Reproduce

1. open a penal in grafana 
2. Copy the code of bar-label-rotation bar graph.
3. paste in the editor Error will appear  

### Current Behavior

Getting error "ECharts Execution Error app is not defined"

### Expected Behavior

Resolution of the error 

### Environment

```markdown
- OS:Windows 
- Browser:Chrome 
- Framework:
```

**Comment by plainheart** [comment]
The `app` object is an object provided by the ECharts example editor and it depends on the [dat.gui](https://github.com/dataarts/dat.gui) library. If you'd like to use it, please import it and follow the documentation of `dat.gui`, otherwise, just remove the code that uses the `app` object.
