### ISSUE TITLE
[Bug] alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效

### ISSUE THREAD

**Issue by L-value** [apache/echarts#18111]
### Version

5.33

### Steps to Reproduce

[Bug]           alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效

### Current Behavior

[Bug]           alwaysShowContent: true, 设置了不生效 还是会从tooltip里离开后失效

### Expected Behavior

设置了 alwaysShowContent: true, tootip会一直显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by L-value** [comment]
@plainheart 大佬帮简单看一眼？我理解配置了这个属性就应该生效....

**Comment by L-value** [comment]
是5.5.0才会修复么...

**Comment by plainheart** [comment]
是的，下个版本是 5.5.0。这个问题好像蛮好修复的，可以自己试试看，似乎主要是由于[这里](https://github.com/apache/echarts/blob/master/src/component/tooltip/TooltipHTMLContent.ts#L334-L343)没有考虑到 `alwaysShowContent` 的情况。

**Comment by jianghaoran116** [comment]
I'm interested in fixing this issue.
