### ISSUE TITLE
Type 'string' is not assignable to type 'ZRLineType | undefined'

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18112]
### Version

^5.4.1

### Steps to Reproduce

- Angular 15
- ngx-echarts ^15.0.1

set datas in a component
`datas: number[][][] = [
    [
        [50, 456],
        [110, 456]
      ]
];`
- create a series type 'lines'
```
const serieLine: echarts.LinesSeriesOption = {
          id: 'L',
          name: 'Route' 
          type: 'lines',
          polyline: true,
          data: this.getCoordsData(0)
        };
```

- build data in a method:
```
getCoordsData(datasIndex: number) {
    const res = [];
   
    const o = {
      coords: [[50,456], [110, 456]],
      name: i+'',

      lineStyle: {
        width: 5,
        opacity: 1,
        type: 'dotted'
      },
    };
    res.push(o);
    return res;
  }
```

### Current Behavior

the error message on IDE is on the "data: this.getCoordsData(0)" line : _**The expected type comes from property 'data' which is declared here on type 'LinesSeriesOption$1'**_

so the problem come from "type: 'dotted'" because is string instead of ZRLineType

**But I can't access "ZRLineType" for import**

### Expected Behavior

access to ZRLineType for import in typescript

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Since you define the data outside the `LinesSeriesOption` object, TypeScript can't recognize the type of the data array. There are two ways to solve this issue,

1. Just add `as const` for `lineStyle.type`

```ts
function getCoordsData(datasIndex: number) {
    const res = [];
    const o = {
        coords: [[50, 456], [110, 456]],
        name: '',
        lineStyle: {
            width: 5,
            opacity: 1,
            type: 'dotted' as const
        }
    };
    res.push(o);
    return res;
}
```

3. Explicitly specify the type of `o`

```ts
function getCoordsData(datasIndex: number) {
    const res = [];
    const o: LinesSeriesOption['data'][number] = {
        coords: [[50, 456], [110, 456]],
        name: '',
        lineStyle: {
            width: 5,
            opacity: 1,
            type: 'dotted'
        }
    };
    res.push(o);
    return res;
}
```
