### ISSUE TITLE
[label] 数据太密集时label没有省略显示，或者没有设置间隔的属性

### ISSUE THREAD

**Issue by wuyadan** [apache/echarts#18117]
### What problem does this feature solve?

数据密集时label的显示不重叠不混乱。现状如下图：
![企业微信截图_16722216427684](https://user-images.githubusercontent.com/33799081/209794627-b9bf19fb-95e0-4293-8428-9fa8c57144f5.png)

### What does the proposed API look like?

默认省略部分label显示，或者增加一个设置label文字密度的属性

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/option.html#series-line.labelLayout.hideOverlap

**Comment by yishangtanhuan** [comment]
> https://echarts.apache.org/zh/option.html#series-line.labelLayout.hideOverlap

这个可以解决一条折线上文字重叠的情况；如果是多条折线之间的文字重叠怎么办呢

**Comment by liqiuqiui** [comment]
> > https://echarts.apache.org/zh/option.html#series-line.labelLayout.hideOverlap
> 
> 这个可以解决一条折线上文字重叠的情况；如果是多条折线之间的文字重叠怎么办呢

每条折线series的label都设置
