### ISSUE TITLE
[Bug] xAxis "0" not found

### ISSUE THREAD

**Issue by momtboy** [apache/echarts#18120]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/stacked-line-chart-forked-oqq2zz?file=/index.js

### Steps to Reproduce

1. 打开控制台
2. 等待5s数据更新

### Current Behavior

xAxis "0" not found

### Expected Behavior

不报错

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
How **15676 lines of code** qualify as "Minimal Reproduction" ?

**Comment by zhiqingchen** [comment]
```js
echarts.use([
  GridComponent,
])
```

**Comment by plainheart** [comment]
`setOption(option, true)` will fully replace the current option with the passed option, which lacks the axis options. You should try
```js
setOption(option, { replaceMerge: 'series' })
```
