### ISSUE TITLE
[Feature] supports action "saveAsImage"

### ISSUE THREAD

**Issue by TonyYanOnFire** [apache/echarts#18121]
### What problem does this feature solve?

Add an action "saveAsImage" for `dispatchAction` so that you can write code to trigger  the saveAsImage event of an echart instance.

### What does the proposed API look like?

```
myChart.dispatchAction({
    type: 'saveAsImage',
    // saveAsImage options
    ...
})
```

**Comment by Ovilia** [comment]
Can this be done by `chart.getDom().toDataURL()`?

**Comment by TonyYanOnFire** [comment]
You sure can use current APIs like `getDataURL` and `getConnectedDataURL` to extract the url and save it as an image, which is exactly what I'm doing in my production codes right now. But from what I see there are at least 2 inconveniences:
1. I have to somehow extract and maintain the option I use both in defining `toolbox.feature.saveAsImage` and `getDataURL`
2. I have to define my own download method, which has a great chance to have less compatibility compare to the one echarts has already defined

What I wanna do is as simply as trigger the saveAsImage action, and at first I was like "How hard it is? We already have a saveAasImage button here!" . But turns out the work I have to put into is not that simple, to be fair.

**Comment by TonyYanOnFire** [comment]
Hey, anyone still interested in this feature? If no official team members reply within 24 hours, I'm gonna close this issue and related PR.

**Comment by jdgme** [comment]
I concur that this is needed as any external trigger noted above using getDataURL() or getConnectedDataURL() would not have "saveAsImage.excludeComponents" applied, but rather save the image as shown on screen.
