### ISSUE TITLE
[Bug] vue项目在ts模式下配置项xAxis.axisLabel. overflow字段报错，请告诉我这是否bug

### ISSUE THREAD

**Issue by dogker** [apache/echarts#18125]
### Version

5.3.3

### Steps to Reproduce

const option: EChartsOption = {
  xAxis: {
    axisTick: {
      show: false
    },
    axisLabel: {
      color: 'rgba(255,255,255,0.5)',
      interval: 0,
      width: 50,
      overflow: 'none'
    },
    type: 'category',
    data: []
  },
  yAxis: {
    type: 'value',
    axisLabel: {
      color: 'rgba(255,255,255,0.5)'
    },
    splitLine: {
      lineStyle: {
        color: 'rgba(255,255,255,0.2)',
        type: 'dashed'
      }
    }
  },
  series: [
    {
      data: [],
      type: 'bar',
      barWidth: 18
    }
  ]
}

### Current Behavior

配置字段报错
![Snipaste_2022-12-30_09-46-18](https://user-images.githubusercontent.com/39555978/210049971-30755fa0-36a5-4bb5-9761-388edffe9353.png)
![Snipaste_2022-12-30_09-46-30](https://user-images.githubusercontent.com/39555978/210049982-9b7ffa69-176b-401c-ada8-27385b3fcc14.png)
![image](https://user-images.githubusercontent.com/39555978/210050033-f0b84588-9bf3-421c-a5e2-c263991490b0.png)

### Expected Behavior

vue项目在ts模式下配置项xAxis.axisLabel. overflow字段报错，请告诉我这是否bug

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Mingeax** [comment]
I have the same problem. But when I emitted the GridComponentOption type in the ECOption, the warning disappeared.
![image](https://user-images.githubusercontent.com/25583491/221332542-5b22b447-92c3-4dda-836f-0ac9f313335e.png)
![image](https://user-images.githubusercontent.com/25583491/221332572-5b26046c-b89e-4252-a805-cd4ba493814e.png)

**Comment by dogker** [comment]
> I have the same problem. But when I emitted the GridComponentOption type in the ECOption, the warning disappeared. ![image](https://user-images.githubusercontent.com/25583491/221332542-5b22b447-92c3-4dda-836f-0ac9f313335e.png) ![image](https://user-images.githubusercontent.com/25583491/221332572-5b26046c-b89e-4252-a805-cd4ba493814e.png)



> I have the same problem. But when I emitted the GridComponentOption type in the ECOption, the warning disappeared. ![image](https://user-images.githubusercontent.com/25583491/221332542-5b22b447-92c3-4dda-836f-0ac9f313335e.png) ![image](https://user-images.githubusercontent.com/25583491/221332572-5b26046c-b89e-4252-a805-cd4ba493814e.png)

这个问题官方已经解决，升级新版本即可，具体请看官方的更新记录。
