### ISSUE TITLE
[Bug] wordCloud创建数据量9000条出现Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zdz4510** [apache/echarts#18131]
### Version

5.0.2

### Steps to Reproduce

正常创建词云图并引入词云图依赖，数据超过9000时异常出现

### Current Behavior

词云图展示90000条数据

### Expected Behavior

展示完全，无异常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Please follow https://github.com/ecomfe/echarts-wordcloud/issues/156
