### ISSUE TITLE
[Bug] MarkArea is broken in version 5.4.1

### ISSUE THREAD

**Issue by ily-salamat** [apache/echarts#18130]
### Version

5.4.1

### Steps to Reproduce

I highlight between bars when I hover using MarkArea

In 5.4.0 version works fine
See example: https://codepen.io/ily-salamat/pen/LYBZzNo

But now in 5.4.1 version something wrong
See example: https://codepen.io/ily-salamat/pen/abjZLdP

I think it's related to this PR #17098

### Current Behavior

Since version 5.4.1 the markArea in my bar chart is broken

### Expected Behavior

MarkArea should work properly as in the previous version

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
@ozkoidi Have you tried 5.4.2? I think this has been fixed. See [demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&version=5.4.2&code=PTAEAcCcFMBdYJbUgWgQcwHYHsYCgBjbTAZ1lABMBDWK0AXlAG0mAiAJgAZuVOA2XgFZWAGlABGcXwC6Ytlx79efURPYBOWcw7dOy3gHZV4gMyCt83fs4AOVTZlydigZ3WqDJi871Lxne3MnBV8BSQ8vYKs_dlU-G28Q_VNVdXZE6LCAFmMTTgyXFHFhMXYsoO0kvxUxU00owvEjWuKC0KK7FvE25PcxPPrKzJQuVS5HIcL2cVyDHqV2WNr2BIb29hNA-YEy1KztkZLQA261_XYaiX4D9mbQG32zhc7QdUjJ9b77istCvIj5gZeDMxDZ3r9fEDOEs1D8fIZeJtapw5k8oTlQek0UJVFlHh8EfwPFiCSjDMZrtjbBTUaSoV8-BMIQj_KlTnSiiDXiTmWTxDDJOD4XykVdabygeIMRITOyJUUjpI5cLJZc-Pj5U04oNNS8bKsOeIvgZxSqRgFQUKqkDpsZJICRjDBKbrSNRYI4a7dmI-PlpABuPCEYhkSg0aAAGQQocY1FoADoALZUcAACgAZgBXTAERDEUCphCwaCJgCUoAA3nhQKAYLBM5BMKAiyWmPlAwBfUuBoikcgANyoABtM5Ho-RYzQqEmUxns7mEPnC8Wy5Xq7W4A2my3E0xup3u0HsOA803GFWawAPACCl-jAC5mOuaxea2_0JAEBQAJKYCjQS9H04ERnzfOMqEfOMxzIEC3zfEgAAtsAAd0fdNhxIaBQI7WC31fODwMg8Moxg0Caw_L9f3_QCJFwuDEJQtCMKwuCcNA_CwKnR8mDIt9gNo0B2H6MQsjEQQfTEAxQTEdRkRaZZahMWpRIkcSJD4WopIkGxalk3iay4UpxFKITBKUwSVPYNSLlKLSVlKWTQDyfpjKc0yTHMkwVLMfoNKcqT9KcnSnMcrJ-KyVyslMrJzLxES1KyPysi0rJgqyRzBH4wRXMEUzBHMwQVI9Oi4NAQQ_OdMTgsERzfR9Vy-FMvhzPVH01MZH0tPiH1HIMfiTkk0zPBKuCDBUgw1IMPyTUk4KDEcmx-JsVybFMsFQRUmw1IcUEtP1UFHPUfj1GMwK0hk8z1BU9Q1PUPz1C09RgvURz_H4_xXP8Uz_HM_wVP8NT_D8_wAtKt9_GC_xXv8LoWm-0wWn-4oWmBpoWkho1lne6YRvBxZll-splkBmy1C0_lIY0RT3tlRTvo8xT_p8wLTGBkxyZMSGTFesLlM-qLlN-uKJHKZTgeS5TIfS3Ga2Kd7stqXLFd-wrFcB8rFfJwRIZq2o6vUz7Gr1pSWda9TAY69Tye69TXr6zTPoMb7hokMbNMBqbNNBsHXch-bakWgPPtWgPfoeAPAZ27Tyf27TXqO3TTp9iRzpT36rt0wG7t08mnt0xyFFKThXK4UyuHMrhLM4cTAvGIu7NsIuC5hwTJCMsuEdbyzkdbvzpjs8RgumPTk8WfjFhL_HBI2EzLKsky-9uEyh6pszx9psyy4Z2uvNKHyzL79m96H7nSl5iyS4FiyK-FsprMSs_vbBsoh-lwTMtKBX37L_LP8s4r3590qu_IeutBL6wuEnH2Fwy7NVKGbC41lLYXDsjbC4Bd7aCQGlgsuLtbiWQmjLLBfcZpYKHv7QSgdKElxDpQiu4dKHWSjisOyscVgj2gQnQSJ0HJlzeA5SyN0HJ9weg5IeL1-jcEka5PI7lOAm2Tnkby1dJF-TyFpPIwUBguX4rKGR_IXKeSlC5NSso1Fo0CrKLRmM3K6Jxm5dyM83LeXnm5NRS83JaNXh5XRtNLEmHcgzJyu9gmmJMGoo-wStGnycufLyMir5eU8sLLyNdFEP1iRo1K_Q35mF0V_Mw7lf5OVViU0xGsSkaO1v0XWlj9bhJkUbJycDmneT4KYy24SNE23CY5dmujsHs3csNSxbt_KmM9v5DRBgtEUM5ro5a_RaGc08gwzmpio6cyfqVTmWibB9K4dzGRqduaeQziFUx2cQoaLziFUKUjQBhSgWDMK0V5EiU4CpMKCV-AfJSo3R5bgRItwipFAxjzO4RS-cjQKEUkpowhWlGxUVwr2KitFJxUUvmuKiklDxUU0pU1hc5R5G8YrRSCTFL5-8YpJUiTFNKMS8ThQiiJK-eIFE-zxF80WjyMl4hStkvloUP6PK_uUaKxTyhfIAeUJKlVYXVLFaFfWiVIpNMSrFM2iUEqW0SilG2iVQqYOSs80qyVoou2Sl8whjzJnJRSjMkSFDUrhUWY82hqVYoMNSmkrlUdUopVjqlUKXD0qRVTulWK5z0oJSuelFKtz0ocLBplLKxcxLQkzQVT5ma1KZQqiiTN1UgVlRbtlHK4LsqctTcYst-apBiQRdlaqNjcpZXsblPKTjcpFVcblCqS9Aq5WqqvfKWUN75TykE_KRV975QqpE_K1UYmFSyqy4dV9CoFWFoVfNGTCpaUKtVN-Hospfw9HlYpHoirFWHRUj0R6lUegyvrcqOUmnlQKmbcq-bLblSPTbcqKbSrOiytg50eUXbOiKra50FVSHOmqhQ7WWV3XazyutYdDDtb5qjtrI9sdtYZS4TVHKqcaoFXOTVfNVyarbLgjVaqEjQC-n4r6BqWbWPvO4ypX07Vfnca6gC30tUW58DboFCTTVO4Sb4z3CTfkJNdUHvVWqhlWP2Mak1JxjU-Pzyk6TRqXV7KadqiS5qDUAk-iCc1Pj-9mpKcic1YKzUQNwXVOx1lrGr7qhasLdU7UMnqi6kK9UtVRXtIakrVjv8pOlPae1Cp7SupKvabVfWjIGpNMZC1M2jJ2qW0ZAxt8jJXN8Fqpgvg2DqtNRdtVvjtrqtKdIdV1zFD4jscWVJ2h8QWoMPiO1KO8Quqx3iLVLhFWGqpwqy1c5FW_Vgwq0p0RrHbkVd6g8vqrk-pDR431caKjjiCb6lpPqc0gWBROP1NuxxwUnHMiccaPcTjTQRScOaNinb9XsU7IaM8rtE2OK4p200PFOzmqvTw_UN6eCGkEzw4196eGmkfK7nNJIxLGv1bzY0hoxUksLMak0MljTO0KsavVRUTTNaNGLE1HulImpNCpE0ztKomr1fWU0dtNKmo9s2U1FulSmtNarkkbZTV6pgk0O2naSRdiacatqTTTVISaOa_srtUJmTt2hMzHsMJmZNKOMyzuxxmb1Lh80dup3mjWkX5z5qTSufNM7tz5oLQeYtFaXHFrmUWptI7i0_KLRKzWRawVFoLRbstFa4LloB7rctbajb7gIuWlHmxq0lo40CqtNaTjVqbVcatUPHjVpR9XmCJaG8wRrSCWCTazNk5glD5EsEUeYkPCWt5h4a0Cf3GFg8baGSHh7SFQ8dzb4tpLS_ltNaxStqbQAVtUPwCtpR7AQ4JaEnQRNIcA7uCDhNrtP36H8X9wbYOAWpgmw2D79rRdvfzatr7-h5mvnp19wKH6iWu6_UNadae4BhfUbaKOfUPaWOfUBaLhfZWnGfVOfZAPc5fZbaK5fZPaW5fZQ6B5I6VyI6UyI6S6XNV4FRM6QTI6R6AFI6Q6FuE6Ag8FE6S6OtE6W6NPE6R6VTV4TGM6DTNIAgqeNIS6IHNIW6UmNIR6UzNIQ6ElN4Ag6zV4beZON4a6feN4e6SJN4Z6GJK6Y6bzK6IgwfK6a6XlK6e6CWM6IVK6Q6UVG6AgmLG6S6UpG6W6CpG6R6JVG6Q6fWO6BAmsO6IglpO6a6M_V4S2O6R6G2O6Q6TBB6Ag-XV4F2B6a6QhM6SZB6R6b_B6Q6KhJ6Ag2hJ6S6BhJ6W6KOJ6R6WOJ6afAIrhF6Ag1OF6S6c5F6W6K5F6R6W5F6V6XQZEDNK4LNFmbgX6bgf6bgQGbgYGbgcmbgSGbgHoluD6T6Yub6YuEY4xIYnuD6KYhFD6OYmxL6d6aEZYqeL6EYoHL6CYmyIYjxL6OY1eH6I4jeH6VYoJH6MY_eH6KYyJH6HSIYmJP6I47zP6VYwfP6MY3lP6KYiWK4IVP6Hoj-IYr-AGVY4pAGMYgBAGKY4BAGOYsBIGI4vfK4I2IYlpIGMYsIoGKYy_IGOYirZETBEGZYxIkGEYt2IY21EGKY0hEGOYihCGI491CGVY4AiGMYraZEHaIY-_SUuY_ZZELhKGZY1OKGEY85KGCYq5KGGYvOIYljSQB5A0z6L6FoHjA0pGI7A01GItCQCGU06GGGFmJULoeGTuJUJGLYyQVGXYyQDGA4_kd6fkY0_GJ0pxSQC4_kQGfkVGW4imOGaGElQUY0xQwUX6UwUSJ0z41mFoH40wDGAEqUQM4EqUeGMEqUJGSEqUDSJ0mEyQOEqUaGUVSQZE4oeGNE4oJGTE4oVGHE4oP45OZs6GfWL040ppL0tMs2L0qMy2L08mKQDGek20-2J07BSQFkpoNMsZNcqMyZNcuc7_Nc6GKhX040kOJ00UweJGCU20qOX0uc2OX06GRUo0Y0lUo0NMjOJ0oRW0rUo0Oc25SQfUwuNQfogM76cuLGf6LgEmX5FmLgcmLgSmUtIM7GW7IM8Ct06YKCrY6YYGfuZYVTOCg4seZYexfkU4xYQmC4xYEmUmcihC0zci16DYYCOC54jYcCt4jYKCz4jYPCn4jYSmAEsobGYEsoISOCsEsoKCyEsoPC2sl-ZYN-SM7GZEqycCtEqyDMgcqyEmCpSMhCpVSM5i4cyBZYMci4QmScxBcy6snSmki4SmRc_kRk24T6W4cCl2FyqCzk24PCnk24fsn2Fy5i48lYdy2hCmQmBhCmEmW8lhZYB89hZYBOOCnhNQFUjQQmdUjQEmLUjQBCgCjQV6PIGmUC2RIhUwM0pRamQGPINmG0qqrmZC2UGmNC2UemN02UbS4K2UOqtPUwXYqxRSA4gJGmMigJemMMgJJmVxUwa4gcgJDmRigJEqxMjyT6DyemN4jyJmT4jyNmH4jyIKsGUwAEryGmYEryemMEryJmSEryNmWsryLmZSvJSqswTamLUwNEswJmTEswNmHEswLmfE8JGmIk1mCSxask8JJmSk8JNmGk8JLmZy_pRSVcoZDG36dmHq069mOq3c9mDmA89mEq48zmTayKlZRSGK9ZWmuy3qmUmUB8zmEqxUo5RSFU05Lmpmb8uoNmVbOoE60qOoHmQ0p5ZSLjQsoWUgwswGMKcWRqsKKWZCiKVigc0FPmb6CKIWOtKULYuFPmcmCKKWA4lFZSMi9FSqqKIWC4qKBWuiqKE2xiqKHmRMmKfmFMmKIWXeFmGKBW8JQWE2jHEWAE5lZSYEvEHWsE7lSOhWh-f22svEKWZS8od6cofmb68oIWUpKUTEuVZSHE8oEWuCfOnmYctVMWHWskxKf6HVMWcWGkxKKWZy5KDW4K01ZSFk5KIWLc5KBW3ch1buqWfk11SWfmM8zW0U1Keu68qUW8wNSWKWeUkWRU8NZSFUqNTevG0W2NTe8WIW9KKWfUtNRWUCzKb6TKFWOWzKdWWCgczKLWAFOWV6bKeWNC7KK-t07Kf6bKdWAa7KLWQix-g49tRWMirtCBlWC43KdWOi3KLWRi3KN-5yFmfKT6KdZWFWEJYoT4hdZWLWUOvBt-8-DszBgWdBsEwqP-yEwqYGQ9RWOEwqN-psj0TB76j0FWVWdBzEj0BhnEj0HWfE8qeWSG8qK-sk8qP-yk8qRm06gDRWG2bst-xk50TBlk50FWLc50dWXc50LWJ1dB_k1DRWIUjDMxlWGK3DMxhh5mvsnWVe4oVKx-9K5xq-_hVSdUmjRWLU-jXxnWfUtjPWUC30aG4K30X6X0f6fjEJ4GX0a2F-0TPWRYiTQ2cFKQN0uTSqiTC2Aa5TFJyGCTV6Rqd6RqQ2U4xqKJi4xqC2BaiJ24xqIph45qMp545qb6ZqKJ3B5qC2IO9SH4lzHJgEzzPWYE9UTpsE9UGJyE9UeJ2s9UIp5S9pDu06qLPWb69pKJvOxLDZ-JnE9pIp_ExkMpyGxkcJtZskxkGJykxkeJmksrPWZy6rMp1c2rPWLyhrHJzk5rD562A86rEp48-IQ2SKvrPWGKwbCF-R0WkbCFoppxirMptxirTpzxqQdUhbPWLUira2XUgcjbTSQ07bIl52M0g7Ilj2QTJoRq87Ilu2R0gck4R2DJh7B2f6E4D2Aak4cmD7B2O2DTJoMiv7Sqp2X6J2Dlua0HTSW4iHGVu2RMzwR2FMzwcVv2plz4lHTSH4zwP2AE7HTSYEvHQ18V4WJoSEsaGFsusnQ1v2ZSiad6Gnd2Z2NEiaDlzEiaYGNnd2Uu8GTnTSYcnnAN52MkqaDlyk0XAN3l5RqXL2VZ0W2XL2Z2LypXL2D2Xck0Xlg8k0O2Y83XTSKe4Kg3Atjl-emZL1-xmZP2Jx-aR1tx-aZ2dF-aXe61_m-aL1oW-aP2fUxad6H3AOaW_3Ad_6RaSOB-4KsPAdyGaPIOPttC5ab6RPIOEdrY5aYGZaGOEBidg4nPAOMigvPdsOC41aSOOi1aGORi1aV6GvSqsEYOFMsEMOXBsESOfpweH4zvUOa9shh4YOShgch4MOM1kfAODJS8mOOEqfCOPt5EhfCOMOHhgDzEtfCOGOIyraa94chwYOMcw_AOSchwSODqFmBwGOZRm_AORk-_YOFk-_MOLc-_SOXc-_GOIxgD_kv_AOIUwArjsOGKsArj9d-x_Uadpx_ZeNsu-AgOFU5A6Tkd_m_ZddoW_Zad_Uo6d6fA3SQYgc4grT_6I6LOalqgrTyGWgxODTtCk6b6ZgxOFt8GNgxOYGTgxOUzg4tIDTsitIazsMtIfTuatIK1-z24tIUzh4t4DT54t4azt41Q3ST4jQuL3ODHFmN4eOMhq6T6Qw3SMEkw7LrOMDq6XOOEmwzOCT-z5Em6aztEm6fTzEm6JznEm6Uz_Eu6DTyGwIyqu6dOScu6LOGcyI3SZRmInODT1ch6azrylIzrzkh6Jznkh6Uz_kp6DToUp6az0Up6fT-ep6QL2WCo3SB86o_ODTtxl6az9Fl6fT_ml6JzoWl6X1vbljEIIufohQMuYYl7quI7BQPuaYl7oeeYouRl6BYuEuFYoHiuYuKuHuLgNPWHhubg2HguaEceY4ouEM0eaESHoHUuayaEX7jxUuAH1ecuVHjecud7oJcuOzgyeRPH_p8uBuUO8uZH8-SuMHq-SuSH2-T5PHxOzHmEyuAHt-aC1Hr-aC974paCquABaC374BaCh7wSauZHiBfgMHppcYSHhBfgPH5BfgBuNBfgZH5czH7BeC97vBFEKuW1eC370heCgHihRC1H91RCi50qRCyHhhRCvH5hWwBuNhWwZHrhLgdKsP97zxsPmn5X78sP371bMPgHp7t6IyV7k01uHjaYUg7P6yIGIhbPgeAFbP5uFuaYW7cvjuTucv7uGHr0oyBFcvpX8v5uDTaYexdvjuJxdv7uVxdvvuFy9uIefkZuNB0eQaoyRQ6YKn9MyfvPhn0wAeZnuoIyNng21fj3uCLCiucs1fvPjJLCgeIVLC5uUVaYcX1soyKXjsgv4oPPipc_geJVc_5uCBTJoyTXqQHfhBKQPP4j8fy_LhWH6Ll-448JoCXCFZGQ8E5rKAXn0mT9wB4bHaBE0GbhUJpgbvQeB3GALoDu415dAQP2ZroDh-q9YeGVwMgvkjIqcYeDv3OTDw8-VyYeAPFuTDwC4wFMeJPG07QIIK08HPtBRMiCYx4BgXiLIF4gMRUIoAWAJAFHC4wKIP4P8ABEfDsBsI64EQTWAACet4B8E-DggVhQAYgpiEOEwhiBZBVEBQaAE4CgA2IOg0QUhHEHoRDB0AGQZ-DkHURHw4gbCCVF0GwA1B4AaAI-AADkg4EcNAH8FiB9BEgqQY4NAAmD5BNEUyMmBohvRLBKg3CLIO4jsReIAAI2wDwBsAiYAIZlAACkoQ3iEOGgDphYAQEXGLAGPBVDeIn4dAAhEqHmCPBGQsGDUPAAFDOAxQ3GGUIqF1CwY2Q3IfkPMG4wGhTQoCK0OsHtDahow0oeUOaFlchhNQkYWV3GGLDlBNYVQXoOQBIASA6Q6YaVG8G-CAhQ4BAJgBCG4wxBAAZTUGJhshQ4AwUYN4iERQAQQ0cCRFgBTC8IvEY4X4NAD-CzhFwkoWDBuF3CHhTwxwS8K4hvDhwHw8cLjBvB3gSApgxIbjA0HIjURbg74S-F-E-D_h_gzIVQEgAgjSoYI-4dgEeGgB7BzwsGK8J4jJwmAlJB5PkCIR7hEyhpbYWDD3BakHkWIQKEwAuBHFdEXI0qEwACQTFwooouCOKLcYPIggAowugMR9DSi3wTAKBsqOOCqiawe4Ncn0VBDajmAj5fUa8ENF7gtKJo_wGaMGo9FAy1oi2pqP5D2j56hpSIAKLv7LEM61oxTJaIVGMimgTZQ0o4HdEbtLRqIEMZFUNKrB3RhXS0fUAFGw8xiqPM0YhU9FGQUxUoGYuPHSDCDERmglEbEMUHoj8xWIwSLjCJGQAAA4imAGGlQAAXmUP7DQAqRp0LIcSIADqX4WAAhDcFlcdw1w7wWUMfAcQ4IRAIcLgACEABidMJkNnycBSRYMY8FQAIBFg1BQEeMIIF4hWDSoJYcAAhCoAkAtBI4t8P2MHH_Djxo4ykROIBHTiZxfUEwAuJ9hLiVx3gtwUQhrDZDIA_4SAJ2IoDdiixgUD8bgG_EABhK8ZACnHphoA0AZlP4MCgdgtxuMZMJAAADW14GABBDXDJxdx-4w8fsKwnJxmwK4AcWoKHEETCJoAMcdeP8GTjUoBAKgDBMfHJxnxq49cZuIokITk424sGA2OgBNiWxZAoiSWBIlkSLxb4Fia-JaFcSiE9IwCdoIonkSFJSIrQf4PaRwSFJlg98T8I0lXh8xAQqqupIUmcTCJhonUXJNxE6TQAyk_Cf4IMnmTNJ9ksSWDGsn6S7ohkjiXJNMnySKJTk0qC5IBFGg-A7kwidxMIm-S4I_k_wUKOClcTPJWkhkQpPClvhIp0U-yaFOThJTdJyIgIRKJik-xjJycLyQlJ8n2SspKk3KWlK0kWSdJkUo5HlLBgFSfYRUxyaVKsl6SARdUyqS1MsmRS5U9U0qI1LBjNSNJmUtqdlIBF9SupI01qZFK7T9TWIcUuScVLCkzT2p_guaVNMSmrTxptktcvNLfCDTSow0raT1LWlKgDA-0msOlJ9ijTIpj5S6ckIonHSSpp0nafdM2kvSapZ0rSg9MOlwRnpK016SpMjJZBfpVUxSRRLumyh1Av0xaRROWkZTtpwM6GWDO6lfS3pKKWGU9PiloyNJd0zGR9MBnozgZvqLGSZJxnTSgZNkheoIFRmUziZ1M9hmTMKkUyTpDM_SUzMJmIyqZ-kxTMzKamszPpeMs6XzK5k3SkZ1Mh1vzKGmCyiZwst6VLLFlgxbpZ0jdtLKOmyzuZ7MgKWrKVmlQVZb0wAurP-mazxZPMnWatDplsz5ZwMwrsbLfAAytZNs6mXbL1mHDnZAQxMfbK2GmzlZEsz2VDytlCylJa01Md7NACOyzZ2sqKbYHEBBy5ZIcnaYf3DnSBAoqchqZsIjl4AOw_oIAA).

**Comment by ozkoidi** [comment]
The link to the demo you posted doesn't work but from [this comment](https://github.com/apache/echarts/issues/18499#issuecomment-1632550842) I understand that the behavior was modified on purpose (so not a bug) and that we need to adapt our code to achieve the desired behavior.
