### ISSUE TITLE
[Bug] chartInstance.on('click',params=>{debugger;})  click event can't be triggered

### ISSUE THREAD

**Issue by Renhj90520** [apache/echarts#18145]
### Version

5.4.1

### Steps to Reproduce

const chart = echarts.init(this.$refs.chart);
chart.on('click',params=>{debugger;});

### Current Behavior

click event can't be triggered.

### Expected Behavior

click event can be triggered

### Environment

```markdown
- OS:Windows 10
- Browser:Chrome
- Framework: Vue@2
```

**Comment by plainheart** [comment]
ECharts 事件只有在点击图形元素时才会触发，设置 symbol: 'none' 则不会绘制拐点，如果希望点击折现也触发事件可以尝试设置 [`triggerLineEvent`](https://echarts.apache.org/option.html#series-line.triggerLineEvent) 为 true，或者按你说的直接监听 zrender 的事件。
