### ISSUE TITLE
[Bug] 数据显示不全，而且阴阳线颜色错误

### ISSUE THREAD

**Issue by huogui** [apache/echarts#18143]
### Version

5.2.1

### Steps to Reproduce

[Demo Link](https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js)

### Current Behavior

[Demo Link](https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js)

### Expected Behavior

https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by huogui** [comment]
![image](https://user-images.githubusercontent.com/41716931/210939593-7f89b5df-b47a-4771-8745-8de9bc3f852b.png)
![image](https://user-images.githubusercontent.com/41716931/210939619-e82e14a7-c843-4651-92e0-40eb0978c5d3.png)

**Comment by Ovilia** [comment]
Please provide more information about "Current Behavior" and "Expected Behavior".

**Comment by huogui** [comment]
> Please provide more information about "Current Behavior" and "Expected Behavior".

hello, this is the demo link：https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

**Comment by huogui** [comment]
> > Please provide more information about "Current Behavior" and "Expected Behavior".
> 
> hello, this is the demo link：https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

The color of the Yin-Yang line is reversed, and the data is sparse, I am very surprised
