### ISSUE TITLE
[Feature] 我700多条数据为什么显示不全呢

### ISSUE THREAD

**Issue by huogui** [apache/echarts#18140]
### What problem does this feature solve?

[Demo Link](https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js)

**Comment by plainheart** [comment]
链接较长时，建议使用 Markdown 语法缩减一下，这样更简练直观，便于他人查看。已帮你调整。

**Comment by huogui** [comment]
> 链接较长时，建议使用 Markdown 语法缩减一下，这样更简练直观，便于他人查看。已帮你调整。

好的，3q，我想实现不用dataZoom，怎么把1000条数据直接显示全

**Comment by huogui** [comment]
> 链接较长时，建议使用 Markdown 语法缩减一下，这样更简练直观，便于他人查看。已帮你调整。

好的，3q

**Comment by huogui** [comment]
![image](https://user-images.githubusercontent.com/41716931/210933657-dae85038-48b4-4967-a53d-d839a17bb3e6.png)

**Comment by Ovilia** [comment]
这个和 #18143 是同一个问题吗，请不要重复开 issue

**Comment by huogui** [comment]
> 这个和 #18143 是同一个问题吗，请不要重复开 issue

是的，我关掉了，不好意思
