### ISSUE TITLE
[Bug] x 轴在动态数据时，没有设置缓动动画过度时间的配置

### ISSUE THREAD

**Issue by banqii** [apache/echarts#18153]
### Version

5.3.3

### Steps to Reproduce

xAxis: {
        type: 'time',
        boundaryGap: ['1%', '1%'],
        interval: 1000,
        splitLine: {
          show: true,
          lineStyle: {
            type: 'dashed',
            opacity: 0.2
          }
        },
        axisTick: {
          show: false
        },
        axisLine: {
          show: false
        },
        axisLabel: {
          fontSize: 8
        }
      },
 yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        position: 'left',
        min: yRange?.[0],
        max: yRange?.[1],
        splitLine: {
          show: false
        },
        axisLabel: {
          fontSize: 8
        }
      },
grid: [{ top: 10, left: 30, right: 10, bottom: 25 }],
series: [{
            name: item.name,
            color: item.color,
            type: 'line',
            animationDurationUpdate: 1000,
            animationEasingUpdate: 'linear',
            sampling: 'lttb',
            showSymbol: false,
            smooth: true,
            clip: true,
            lineStyle: {
              width: 1.3
            },
            encode: {
              x: 0,
              y: index + 1,
              tooltip: [index + 1]
            }
          }]

### Current Behavior

数据的缓动动画已经设置为与数据填充时间一致，但是没有找到 x 的缓动动画时间，导致X轴动画出现顿感

![aaa](https://user-images.githubusercontent.com/18062379/211293543-686b2637-ea96-4e6b-be9f-679ef072d101.gif)

### Expected Behavior

希望能设置 x 轴的缓动动画过度时间

### Environment

```markdown
- OS:macbook m1
- Browser:chrome
- Framework:next.js
```

**Comment by Ovilia** [comment]
`xAxis.animationDurationUpdate` should work for this case.

**Comment by banqii** [comment]
> 

Thanks, it does works, but there is no such configuration in the document.
https://echarts.apache.org/zh/option.html#xAxis

And I found this type in the source code types.

**Comment by Ovilia** [comment]
Thanks! I've updated the doc.
