### ISSUE TITLE
[Bug] Pie chart, add 'markLine' to 'series' , report an error 在饼图里使用markLine属性会报错

### ISSUE THREAD

**Issue by d1106547653** [apache/echarts#18150]
### Version

5.4.1

### Steps to Reproduce

Pie chart, add 'markLine' to 'series' , report an error 在饼图里使用markLine属性会报错

### Current Behavior

When I updated to version 5.4.1，add 'markLine' to 'series' , report an error 更新到5.4.1版本后，在饼图里使用markLine属性会报错

### Expected Behavior

I want to use ‘markLine’ in a pie chart 我想在饼图里使用markLine属性

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
饼图里用 markline 是期望什么效果？目前应该是不支持的

**Comment by d1106547653** [comment]
> 

我想画两条线段，从左边的一个饼图里的某一项数据出发，呈一个扇形，指向右边的另一个饼图。表达的意思就是左边饼图的这一项数据，是由右边饼图所示的多项数据所组成的

**Comment by d1106547653** [comment]
> 饼图里用 markline 是期望什么效果？目前应该是不支持的

我想画两条线段，从左边的一个饼图里的某一项数据出发，呈一个扇形，指向右边的另一个饼图。表达的意思就是左边饼图的这一项数据，是由右边饼图所示的多项数据所组成的

**Comment by d1106547653** [comment]
> 饼图里用 markline 是期望什么效果？目前应该是不支持的

在5.4.0及之前的版本都是支持的，5.4.1不支持

**Comment by Ovilia** [comment]
先用 https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&version=5.4.0 创建一个之前版本的例子看下期望的效果吧

**Comment by plainheart** [comment]
可以确定是 bug，#17217 的改动有一个空指针访问的问题。Review 的时候没发现 /(ㄒoㄒ)/~~
@Ovilia 5.4.1 的两个 PR (#17098, #17217) 对 marker 的改动都导致了比较严重的问题，感觉是不是发个 5.4.2 专门修复下比较好？
