### ISSUE TITLE
[Bug] [candlestick] Data points are not displayed

### ISSUE THREAD

**Issue by huogui** [apache/echarts#18156]
### Version

5.2.1

### Steps to Reproduce

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Current Behavior

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Expected Behavior

demo link:https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Duplicate of #18143 .

If you don't want to spend some time describing your problem, don't waste others' time by opening the issue again.
