### ISSUE TITLE
[Bug] Grouped charts not synchronizing time axis when data is missing

### ISSUE THREAD

**Issue by MagicalBS** [apache/echarts#18167]
### Version

5.4.0

### Steps to Reproduce

Hello!

I have multiple charts with either one or two series each, all of which are grouped together.

The options are based on the content of the plot, however, they are all:
```
xAxis: {
  type: 'time',
},
series: [
  {
    type: 'line',
    animationDuration: 500,
    data: this.data[0].map((x) => [x.datetime, x.value.toFixed(2)]),
    connectNulls: true,
    symbol: 'none',
    showAllSymbol: true,
    markLine: {
      silent: true,
      animation: false,
      lineStyle: {
        color: '#333',
      },
      label: {
        show: false,
      },
      symbol: 'none',
      data: this.markLine[this.sensor.feature] ?? null,
    },
  },
]
```

### Current Behavior

I am currently transitioning from a different charting library and have noticed an issue:
Sometimes, not all of the charts have data for the specified time range. In the old library, it was obvious that data was missing because the x axis (time) was the same for all charts, so there would be gaps. In echarts, however, the x axis seems to adapt to the available data rather than the selected time range. This means that if you don't pay attention, you don't realize that data is missing.
<img width="524" alt="new" src="https://user-images.githubusercontent.com/32430646/212044574-b7d76331-edc4-4c61-898a-13538d5edf16.PNG">

### Expected Behavior

What I would like to see is that data stopped coming in, i.e. use the entire x axis and see a blank space where data is missing.
<img width="528" alt="old" src="https://user-images.githubusercontent.com/32430646/212044675-7d55031a-20d0-42ff-9040-81078aa0bd09.PNG">

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 108.0.5359.126 (Official Build) (64-bit)
- Framework: Vue
```

### Any additional comments?

I found some posts on SO suggesting to add null entries for missing timestamps, however, that seems highly inefficient and I was hoping that there was another way of solving this issue.
Thanks for your help!

**Comment by helgasoft** [comment]
Why expect grouped charts to synchronize time axis ?
[connect](https://echarts.apache.org/en/api.html#echarts.connect) is defined as _"Connects **interaction** of multiple chart series"_.  Interaction means common zoom, legend click, etc. of grouped charts.
Probably the simplest solution would be to **not** connect the charts, just use the same X-axis for all of them.

**Comment by MagicalBS** [comment]
> Why expect grouped charts to synchronize time axis ? [connect](https://echarts.apache.org/en/api.html#echarts.connect) is defined as _"Connects **interaction** of multiple chart series"_. Interaction means common zoom, legend click, etc. of grouped charts. Probably the simplest solution would be to **not** connect the charts, just use the same X-axis for all of them.

Thank you, that was very helpful! I did not realize that was an option.
I have achieved what I wanted now by setting a min and max on the xAxis according to the selected time period. All charts are now synchronized on the xAxis as expected, even when no data is present (gaps can be seen in that case).

<img width="257" alt="new" src="https://user-images.githubusercontent.com/32430646/212282061-d71ab839-3fbc-47d8-9315-a72303487f4e.PNG">

The charts are still connected since I want to have the tooltip across all of them.

Thanks again!
