### ISSUE TITLE
[Bug] Graph force emphasis adjacency, symbol disappear after hover when data is too large

### ISSUE THREAD

**Issue by windinging** [apache/echarts#18187]
### Version

5.4.1

### Steps to Reproduce

```
    {
      type: 'graph',
      layout: 'force',
      emphasis: {
        focus: 'adjacency',
      }
    }
```

### Current Behavior

type:'graph', layout:'force',emphasis:'adjaceny'.
When data is too large, hover symbol, sometimes the symbol will disappear after hover,it seems the opacty is 0, when hover the disappeared symbol the label show noramlly.

### Expected Behavior

type:'graph', layout:'force',emphasis:'adjaceny'.
After hover symbol, symbol behave normally, not disappear.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by windinging** [comment]
![1674011111281](https://user-images.githubusercontent.com/7800381/213072682-f1f895df-d7c7-48cc-9734-84eead513cdf.png)

**Comment by windinging** [comment]
@Ovilia this is demo, you can load file graph.json by the demo offererd
https://codesandbox.io/s/elastic-rui-1igt2q?file=/index.html

**Comment by Ovilia** [comment]
Please make the demo easy-to-access. I have no idea what file to upload. You should include it in the code.

**Comment by windinging** [comment]
@Ovilia Ths for reply, you can upload the file in the demo filedirectory.
![1675647736844](https://user-images.githubusercontent.com/7800381/216862912-6c0da9be-8d2e-45fb-be27-1fca53c5b9e3.png)

**Comment by zebleck** [comment]
having the same issue. the symbol disappears after you stop moving the mouse.

**Comment by XZCendence** [comment]
Same issue here, a series will sometimes disappear after hovering
