### ISSUE TITLE
[Bug] Height Exceeds 65535px Error

### ISSUE THREAD

**Issue by biscuit214** [apache/echarts#18180]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/basic-bar-forked-74z08m?file=/style.css

### Steps to Reproduce

1.Use the following link to create, has error example
https://codesandbox.io/s/basic-bar-forked-74z08m?file=/style.css

2.Replacing [height: 65536px] for [height: 1000px], Back to normal.

### Current Behavior

ECharts height exceeds 65535px will report an error
some computers in 59353px will report an error
![image](https://user-images.githubusercontent.com/5866109/212834492-c66c3645-ba0e-43e0-a48f-c0c52b4bba8d.png)

### Expected Behavior

Expected
![image](https://user-images.githubusercontent.com/5866109/212834572-72af5134-3fe4-4f1d-80de-34f8551212bb.png)

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 108.0.5359.125
- Framework:
```

**Comment by plainheart** [comment]
This is up to the limit of the browser, and it's not related to ECharts.
