### ISSUE TITLE
[Bug] Rich text in legend does not inherit color from legend configuration if theme specifies `textStyle.color`

### ISSUE THREAD

**Issue by juliepagano** [apache/echarts#18196]
### Version

5.4.1

### Link to Minimal Reproduction

https://codepen.io/juliepagano_cs/pen/XWBzLaJ

### Steps to Reproduce

1. Open [the codepen](https://codepen.io/juliepagano_cs/pen/XWBzLaJ)
2. Note that the non-rich text in the legend is red (the value specified in `legend.textStyle.color`).
3. Note that the rich text in the legend is green (the value specified in the theme's `textStyle.color`).
4. Click an item in the legend.
5.  Note that the non-rich text in the legend is blue (the value specified in `legend.inactiveColor`).
6. Note that the rich text in the legend is green (the value specified in the theme's `textStyle.color`).
7. Comment out the `textStyle.color` in the theme and note that the rich and non-rich text match the legend configuration.

### Current Behavior

When a chart's theme specifies `textStyle.color`, rich text within the legend configuration inherits from the theme's text color instead of the colors configured in the legend.

### Expected Behavior

I would expect rich text within a legend to inherit from the legend's color configuration (`legend.textStyle.color` when active and `legend.inactiveColor` when inactive). 

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 108.0.5359.124 
- Framework: the bug is not framework specific, but we are working in React
```

**Comment by helgasoft** [comment]
Observations are correct, but an easy fix is to just set **bold.color** to  _'red'_ instead of relying on inheritance.

**Comment by juliepagano** [comment]
> Observations are correct, ~but an easy fix is to just set **bold.color** to _'red'_ instead of relying on inheritance.~ 

Guessing the strikethrough means you already inferred this, but clarifying just in case...

If you explicitly set a specific color in the rich text config, it cannot change to match the active/inactive colors set by `legend.textStyle.color` and `legend.inactiveColor` because it's hardcoded to a single value.

**Comment by ManishDait** [comment]
If this issue is not fix till  now, I would like to fix this issue

**Comment by ChepteaCatalin** [comment]
@ManishDait have you checked #18260? It seems that this issue was fixed there.

**Comment by ManishDait** [comment]
@ChepteaCatalin Sorry for that, The issue was  not close therefore. I create that PR
