### ISSUE TITLE
[Feature] Zoom reset by button and/or double click.

### ISSUE THREAD

**Issue by twoco** [apache/echarts#18195]
### What problem does this feature solve?

Reset dataZoom slide by e.g. double click and / or a button. Currently you have to drag both handles to their ends to reset the zoom.

![zoom-slider](https://user-images.githubusercontent.com/53160891/213566826-81dd3f96-7ec1-4042-bc0b-dff05d3b3c3f.png)

### What does the proposed API look like?

Maybe a property to the options of the `dataZoom`? Maybe enabled by default? Something like `resetButton` and/or `resetGestures` or `resetDbClick`.

**Comment by helgasoft** [comment]
this will do - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdABGjBzBHnYkbSRCYIwAWsDAALZund60eP4QAhEyeOMcYEQZQ3YA3Ch-HLAAXqeIM-QAwtp9YAB0rFRgExwAFACURxePMB9aAJuv56Ct6ABrGQAM0s9EgMFgHxAfUYMzwX2IAEhrncHo8BPgUWB6NosPCoNAPqgsViFnQxpNpjMZChaZsHkQCrAAPQ82DUDj0KjQcYvWDAaFhLaQaCsAXAPAQBHQA6wdKwAC0sGS6XSbKxIoERF1GvQfIFEWFosY4slsCNEDlCqVKrVGu1prZdi-KB9QA)
double-click anywhere on the canvas

**Comment by twoco** [comment]
Looks good. Thanks 👍 
I can't find `getZr` in API docs. But it seems that It returns the [zrender](https://github.com/ecomfe/zrender) instance. The drawing library behind ECharts. ... We could add an option to `dataZoom` for that feature of zoom reset.

**Comment by Ovilia** [comment]
`getZr` is not in the docs because in most cases developers are not expected to get hands dirty with the underlying zrender instance. Thanks @helgasoft for the help. Officially, we would suggest you listen to the DOM events to check for double click instead of exposing zrender in this case. But yes, using zrender is an easier way.
