### ISSUE TITLE
[Bug] duplicate id=0 on multiple svg charts

### ISSUE THREAD

**Issue by frankliu197** [apache/echarts#18194]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/embed/polished-monad-v0vopl?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

Inspect the html construct of the two graphs and see the following
![image](https://user-images.githubusercontent.com/23513458/213547647-fb16073e-d851-49aa-a525-2ee50de06a2b.png)

Both graphs have a rect element with an ID of 0.

### Current Behavior

If you create more than one graphs on the same page, there will be duplicate html tags with the same ID. The id attribute should be unique to provide machine-readable identifier for elements on the page. More on this accessibility issue:
https://www.w3.org/WAI/WCAG21/Techniques/html/H93
https://www.w3.org/WAI/WCAG21/Techniques/failures/F77
https://www.ibm.com/able/requirements/requirements/#4_1_1
Is it necessary to put an ID on the rect tag?

### Expected Behavior

All IDs should be unique.

### Environment

```markdown
https://codesandbox.io/embed/polished-monad-v0vopl?fontsize=14&hidenavigation=1&theme=dark
```

**Comment by helgasoft** [comment]
there is an [**id** property](https://echarts.apache.org/en/option.html#series-gauge.id), but even if set,  it does not show up  anywhere apparently ... (?!)
