### ISSUE TITLE
[Bug] appendData后调用setOption会清空数据

### ISSUE THREAD

**Issue by mnvmpcopizf53625** [apache/echarts#18209]
### Version

5.3.2

### Link to Minimal Reproduction

https://www.isqqw.com/viewer?id=36746

### Steps to Reproduce

```js
var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;

function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
      Math.round(value)
    ]
  };
}
option = {
  title: {
    text: 'demo'
  },
  tooltip: {
    trigger: 'axis'
  },
  xAxis: {
    type: 'time',
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [{
    name: 'demoData',
    type: 'line',
    showSymbol: false,
    hoverAnimation: false
  }]
};

var iter = setTimeout(function () {
  option.series = [{
    name: 'demoData',
    type: 'line',
    showSymbol: false,
    hoverAnimation: false
  }];
  myChart.setOption(option, true, true);
  for (var i = 0; i < 15; i++) {
    myChart.appendData({
      seriesIndex: "0",
      data: [randomData()]
    });
  }

  //here！ setOption anything will clear seriesData
  myChart.setOption({
    title: {
      show: true,
      text: "aaa"
    },
    series: [{
      type: 'line',
      markPoint: null
    }]
  })
}, 500);
```

此示例代码来自https://github.com/apache/echarts/issues/12327

### Current Behavior

setOption会清掉所有appendData插入的数据

### Expected Behavior

setOption后数据正常展示，不清空

### Environment

```markdown
- OS:-
- Browser:-
- Framework:-
```

**Comment by kai890707** [comment]
Is your original intention just to update the data in the chart?

**Comment by helgasoft** [comment]
cannot reproduce, setOption works as expected - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-race&code=PYBwLglsB2AEC8sDeAoW7JgDYFMBcyYOAHmAQOQDGWElA1rAIawjATRixjBMgg7QAJuQC-AGjTom0CAFtGkGATAAnAK44JUrsGBZIIAknGT0xAILEIAZyMntAT0s27WqbgDmAwa9OxrOCoQOLawANqo2tpgDvwU1pQKRCrkYrDQjLL4sOQJSYGpftoQPjmUMNZgqbBFUoIKjARhYQDMAAxp7QC6aWEArG0dsO1tXT216AD0kyAqwB4qIdYQAG44ACoAFovWm3ql7W5R_g6yAEZ6FKoQjNAeuIXH6NanF1gAyhAAXtkATG1-ERdFAiFArRgqWAOABCjACCFgAwA3ChZA4AMKbCFgAB0MAAFFQaPRqgAzNTQSiKOD4gCUyD84MhYBACLCwO0pOAKnxTNgEARbSR_NgAB5EcKIABqKX0yJPFlhCBdNkQABUAEZBmkYXCcFL1VquijtKDtGjMdicYw-N4ACINfHy44BIIhACSQhIBA6E1g9TAjS4IEBtJNUgtWJUuICYAA8uAoNAnbVXcFQmEak9kPzSlQKlVYPYns6FbFsuQaNAcNUqzh3jFcEZylhuXhyIthGkAO4lMCbPAtYvZgNB5oagY62EBHrhAAsk6h05wYz9ZqiHKk6_QYb8uvhUsQWpRIjDQA)
Please note [Replace Merge](https://echarts.apache.org/en/api.html#echartsInstance.setOption:~:text=interval%3A%2088%20%7D%0A%20%20%20%20%5D%0A%7D-,Replace%20Merge,-Within%20a%20specific) in the docs.  To keep a serie on update, it has to be included by **id**, 
like ```series: [{ id: 'const' }, {...new serie...}]```.
