### ISSUE TITLE
[Bug] Type issue: Property x,y,width,height does not exist on type CustomSeriesRendererItemParamsCoordSys

### ISSUE THREAD

**Issue by infacto** [apache/echarts#18200]
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=custom-profile

### Steps to Reproduce

Check out the link above. It's one of the examples of ECharts (line 47).
Thanks btw. It's a great chart lib and deserves more attention as chart.js in my opinion. Anyway...

I just copied the example code and added some types for TypeScript by checking what types are expected here.

### Current Behavior

For the renderItem method argument params `CustomSeriesRenderItemParams`, I get the error that `params.coordSys.x` (also `y`, `width` and `height` do not exsit on that type.) But at runtime it works. Maybe a type issue? Or is there another derived type I should use?

```ts
interface CustomSeriesRenderItemParamsCoordSys {
    type: string;
}
```

There is only `type` property. 

### Expected Behavior

Types should work well for a library written in TypeScript. What is great btw.

Workaround: Modify (extend) type or use `any` or `unknown`. Not the best solution. 

### Environment

```markdown
- OS: Win 10 Pro 64-bit 22H2
- Browser: Chrome 109
- Framework: TypeScript (Angular)
```

### Any additional comments?

No matter, but I use [echarts](https://www.npmjs.com/package/echarts) directly in Angular. (Not [ngx-echarts](https://www.npmjs.com/package/ngx-echarts).)

![screenshot](https://user-images.githubusercontent.com/60390085/213706003-c43746b1-e68a-4d1c-a1dc-1228425a523f.png)

**Comment by Ovilia** [comment]
This is not a bug. Please see the discussion at #17636.
