### ISSUE TITLE
[Feature] Sankey桑基图的Label中的value值 是否可以与Tooltip的value值保持一致呢？

### ISSUE THREAD

**Issue by TommysLee** [apache/echarts#18211]
### What problem does this feature solve?

桑基图中 Label Formater的value为空
而Tooltip Formatter的value值 是有的 且与实际相符

是否可以将这两个值统一一下，两边都可以拿到值，而不是一边有值，一遍undefined

最终，我要实现的效果就是，在图上 Label 显示的value值  和 Tooltip的value值 是一致的，但我现在做不到。

### What does the proposed API look like?

无法上传图片，这里就没上传效果图

**Comment by TommysLee** [comment]
补充图片：
![image](https://user-images.githubusercontent.com/98680646/215421941-49a6963e-e9cf-4a9e-98a7-d0a99ba3d684.png)

**Comment by TommysLee** [comment]
类库貌似没有把 value 抛出，根据此思路，解决如下，不当之处，请指正！
https://githubfast.com/apache/echarts/issues/18212 #18212

**Comment by susiwen8** [comment]
Please feel free to make a pull request

**Comment by susiwen8** [comment]
Duplicate with #18212

**Comment by TommysLee** [comment]
then what?

**Comment by TommysLee** [comment]
> Duplicate with #18212

then what?
