### ISSUE TITLE
[Bug] treemap 点击任意节点或者缩放之后整个图消失（缩放到左上角并且很小）

### ISSUE THREAD

**Issue by stefenson** [apache/echarts#18215]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/embed/nice-tree-ibubhx?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

1、在 vue mounted 阶段，初始化 echart 节点，并存入 vue 的控件变量中。代码里体现为 chartObj。
2、在另一个函数中使用变量 chartObj 直接 setOption 进行绘图
3、点击任意一个节点。

### Current Behavior

整张图缩放至左上角，并且无法复原。

### Expected Behavior

缩放到对应节点上。

### Environment

```markdown
- OS: 任意
- Browser: Chrome
- Framework: Vue + Echarts
```

**Comment by plainheart** [comment]
避免在 data 中声明 echarts 实例，Vue 的代理会对 echarts 内部属性的访问有所影响，移除 data 中 `chartObj` 的相关逻辑即可。另见 [FAQ](https://echarts.apache.org/zh/faq.html#others:~:text=%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%20Vue%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts%20%E6%97%B6%E5%9B%BE%E8%A1%A8%E6%98%BE%E7%A4%BA%E5%BC%82%E5%B8%B8%EF%BC%9F)。
