### ISSUE TITLE
[Bug] External remote data can not be loaded in to ECharts web site demo in share mode.

### ISSUE THREAD

**Issue by frank-zsy** [apache/echarts#18210]
### Version

5.4.1

### Steps to Reproduce

I am using ECharts web site sharing function to share some ECharts demo to my friends, I would like to load some external data into the chart.

All works fine if I open an empty editor, put in the code and the chart will display with correct data.

Then I use `share` button to share the demo to my friends, but when opening by the share link, I got an error and can not load external data.

### Current Behavior

External data can not be loaded into ECharts web site demo while edit mode is just fine.

The example share link is [this one](https://echarts.apache.org/examples/zh/editor.html?code=G4QwTgBGCmAOD2A5EBbaEC8EDkANAtADYgBGATAAwCMA7APTyzQB2-AJgJYDmX0Y2AbgBQAEgB0vAC4ApAMoB5RAAohEHAAtJk2AGcAXHQY6dYgB5FSYjswBm8Bk2YB9Tjz50uHSeoCuJOtgQANRQcEio6CHYdCAAxpIcwNAuIJLQOk4gzGxOCWgmAFY68MzYADSqEDY-zPEcJUpsqSAAlBAA3pVqhhCwMFocfPjczPAwXRCxJTqSEOrwPmA6mBAA2hNqathUZCDlOFR7ZTi7-9gAzEc4ACxX2ACsdwBsdzR3ABx3AJx3VBS_h3KG022zIsDOVHBx2wYLO5yhNwRDyRTyRNCR7yRXyRfxxkOwEwAusJNhAen1oAMhiMxtAJlNmDMIE0AJ7LLDrUmk7CyGqss6yVKLfnQgBiYA4IpwABVfEspdgAOrQNjMdIK6U-dUgFlnACyJX5RJJm3J_QS1K4o3GpJ6Oh8KAgPlgEBAhEIEG86AA7mMANbWLhzBZgCagSCgQha9kQeQkArQeJiSPRxrNFpiGBsHyxaBKJSwY6xNoYAB8HWBHBsEALmAwWGYPndbX6i2YkxNpNbYHbsDEKBAsHzwGOHBL5eAwUmqw4hJanYgAF9jo3mwuJj0fDp0IR4EHJPAIDoUPB4N5Pep0E1JCAw27oysU-l-4OlJOyxA9al1GJd1w31OVAtPOEwbnQEDWgOhAcAAXiqnqHhQED4BAfx3pAA6mCsX7eC-phKGIhFPjoIGksRj73s-A5Du-5Y4T-uYcIQAEAFSoUh4GYcBwjoRA1iwD4kgACLNCsqzEhMdiQG-4DMisFACHJAA8EA0IpbBBEEbSdFyVRjDW4ZzPJinqBAKlkNcJmadpwJqPxgkiTeYgCTo6hKKs6jHE8yHMscxGrGwEBsRZU7qISEAAD4RTg-DYHOC5qIuExJWoEyMAkJQrDpXIJJIhDQHoFa6WoaSmJIhUAAYAIJ1EkECOekEBVdkEDShw-R6ZAIjtDACDIGgi4VRUxUQPlNjlTgubMGk_DAsuwJcBKbCFdlumXtwmiFQ8FAAKRAiNB6wFtfx7XNw1cqYVWmBw-hFcVkgskwW2xKk0BcGMurnbp14gIV8yLDoX1cjosDQZIVUwL9d0ja58DeoVkhgFqtlLmdwIsldN0rSjD1PZNr3vWAn0oz9hWsoDKMg2DEPQFDq3FbD8OekjdIjSlXLzbpwA3T4bpfkd0Ncig1iFRQQOkphhV_OLmwvYQsRNqQ-UIyzMtqGMgzTVt8wSjBJQ3oQ-3FWNE3YFNM1G7pJBngeKDHfcp26ZzwN8IMt2csV9O6cwERbQACjUsSmQAwuAbCW_dj0FRotOSNREffc0hX2cJzRq5sxAkNAhDYyNpKMyryN50u6dqNAKCwOoIA6FjgsjV45eyA9yt13nrkgGwcMAEJRmAUtiyjunt533rB_Au59zgYBcCQIBKGLEAL0vYj3C0BLF4lg-o2zwKEslC4oCywdV2AkhiNukjyLAGXMEo6X1MwpGoy0QA).

Follow the link and you will get an error like:

Refused to connect to 'https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/active_dates_and_times.json' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https://*.apache.org https://*.jsdelivr.net https://*.jsdelivr.com https://*.unpkg.com https://*.baidu.com https://*.bdimg.com https://*.bdstatic.com https://apache.org https://apache.github.io https://jsdelivr.net https://jsdelivr.com https://unpkg.com https://baidu.com https://bdimg.com https://bdstatic.com https://cdnjs.cloudflare.com https://cdn.bootcdn.net https://lib.baomitu.com https://unpkg.zhimg.com https://npm.elemecdn.com". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

But if you open an empty editor and paste the code in, you will get correct result.

### Expected Behavior

Load external data correctly in share mode.

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 109.0.5414.119
- Framework: Null
```

**Comment by Ovilia** [comment]
If you want to use external data, please consider using [CodePen](https://codepen.io/Ovilia/pen/dyYWXWM), [CodeSandbox](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) or [JSFiddle](https://jsfiddle.net/plainheart/e46ozpqj/7/).

**Comment by frank-zsy** [comment]
@Ovilia Thanks, CodePen looks perfect for me.
