### ISSUE TITLE
[Feature] 线图大数据量下的tooltip性能优化

### ISSUE THREAD

**Issue by Tronsfey** [apache/echarts#18228]
### What problem does this feature solve?

大数据量展示：[测试例子](https://echarts.apache.org/examples/zh/editor.html?c=dataset-link&code=M4UwLgKglgtiD2BXMAKAZogdgYzFemABCgJSEDeAUIYdgcGIaAE5QjADCSmjAvIQGYADEIDc1WvUYATAIZhZXLH0IBGACwjxNADbgmSZthCF-AbTMByAA7N40xLksBdZ9sJ7GLNsFOEzbhJo8MzEnoRQfmIRhAA8TCCs7Eo8ohEA1OlkVDQ0wIbGZkLOAHTWiMAAFigABgAk5ABMQqqNhOkRAL41JO55iT5lFdU5uTRgAJ7WIABchJY6UJgglgA0EmPAMPDwYJVzYMyIIOtj_UnAADKyE0hgAEITc5Z2AO5rG7kgMNaVssBQYBzciEaSA2QAIz00gORxMnVOZ2AExgEPgOmemAIK0-nV6Ek6lCCITC-ki_FUaUi8W8yW4jA6lIyWQon3yiCMIDMUGcfjMnxoNTkCgAtA0oN1EWMSjKAILMZg3EpoOwwFDyxUTFDCxT0kirYgAfQNUDIvAAfKyzrlmOAOURrLJmKAAJI8FACs4AWXklRKisw0ngarIACo1CJCOHHc6QG7UD69v7ZIHg6Qo4RE36A0GQxnVCISJ6aPjrXjPoEaISJPBrHgCH5RroQABzECBuZoWQ6UBSwjfX7_QHAz1g4CQ6Gw464vtgHY6PDWEfWw5QFtt5jPWQAD0BH2tENk2AA1i27FhpFwdCFnswW4eUI0AKxPg3P1-Ed8GoQlAAcJH3XIEU-Sp4AAN0Sa4JkSCBKltKp0RhQghD7FNYHkfBME7bte0-HVQDAZckQKEAZ0-bdZV3IEKEISZpmebB5FbEIJksQhgLGCZKOHGizygaQ3WkEBtzmIR2L7WlgAJcQJBgCYOD-ZgwBKAiAHk60wlBa3rTB8TxUQgA)

### What does the proposed API look like?

当前如果系列过多（demo中是300个系列）的时候，
即使是添加了hoverLayerThreshold配置，tooltip触发依旧存在明显的性能问题，期望可以优化性能

**Comment by helgasoft** [comment]
Usually, even 30 line series are hard to read in a chart, but 300 (!?) - impressive tapestry...

**Comment by Tronsfey** [comment]
Totoally agreed.
But I do have data with a large amount of series need to render in single line chart.
Most time, the chart tells the trend of data and helps targeting series that have outliers. In the long run, it should be automaticly identified by intelligent algorithms.


[tooltip.triggerOn](https://echarts.apache.org/en/option.html#tooltip.triggerOn) set to 'click' could help to improve the performance, cause we don't need to trigger tooltip everytime the mouse cursor over the chart

> Usually, even 30 line series are hard to read in a chart, but 300 (!?) - impressive tapestry...
