### ISSUE TITLE
[Bug] 网页中的echarts在打包成安卓中丢失颜色或数据

### ISSUE THREAD

**Issue by augustanamo** [apache/echarts#18220]
### Version

5.3.2

### Steps to Reproduce

网页中的echarts在打包成安卓中丢失颜色或数据，网页自己在浏览器中显示是正常的。
![128881675241655_ pic](https://user-images.githubusercontent.com/50311871/215997431-8b40017f-3ade-41f9-ba31-5bae629f2eac.jpg)
![2071675241177_ pic](https://user-images.githubusercontent.com/50311871/215997484-712afe95-a9e2-44a9-ad44-fbc858b2daa6.jpg)
![2081675241177_ pic](https://user-images.githubusercontent.com/50311871/215997503-2c5f25dc-c8f7-4341-a04c-9f8f5c3f2e08.jpg)

### Current Behavior

把网页用ifream嵌入了app中

### Expected Behavior

能够在app中正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
请仔细检查自己的代码，ECharts 本身不应该存在这个问题

**Comment by Ovilia** [comment]
可以在 `setOption` 的时候用 `JSON.stringify(option)` 看下实际的配置项

**Comment by augustanamo** [comment]
> 可以在 `setOption` 的时候用 `JSON.stringify(option)` 看下实际的配置项



> 请仔细检查自己的代码，ECharts 本身不应该存在这个问题
可是在网页中显示一直是正常的，后面打包嵌入app中就有时候会出现这种状况，不清楚echarts是否对安卓或浏览器兼容有什么要求

**Comment by plainheart** [comment]
@augustanamo 这个问题请尽量贴出示例代码，一般无外乎是使用了 webview 不支持的颜色格式，例如 #rrggbbaa 这种格式，或者 rgb / rgba 混用，例如 rgb(r, g, b, a) / rgba(r, g, b) 等。
