### ISSUE TITLE
[Bug] The first data point is not displayed.

### ISSUE THREAD

**Issue by czphappy** [apache/echarts#18239]
### Version

5.4.1

### Steps to Reproduce

```js
// See https://github.com/ecomfe/echarts-stat
echarts.registerTransform(ecStat.transform.regression);
option = {
  dataset: [
    {
      source: [
        ['1', '4862.4'],
        ['2', '5294.7'],
        [3, 5934.5],
        [4, 7171.0],
        [5, 8964.4],
        [6, 10202.2],
        [7, 11962.5],
        [8, 14928.3],
        [9, 16909.2],
        [10, 18547.9],
        [11, 21617.8],
        [12, 26638.1],
        [13, 34634.4],
        [14, 46759.4],
        [15, 58478.1],
        [16, 67884.6],
        [17, 74462.6],
        [18, 79395.7]
      ]
    },
   
  ],
  title: {
    text: '1981 - 1998 gross domestic product GDP (trillion yuan)',
    subtext: 'By ecStat.regression',
    sublink: 'https://github.com/ecomfe/echarts-stat',
    left: 'center'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'cross'
    }
  },
  xAxis: {
    type:"category",
    splitLine: {
      lineStyle: {
        type: 'dashed'
      }
    }
  },
  yAxis: {
    type:"category",
    splitLine: {
      lineStyle: {
        type: 'dashed'
      }
    }
  },
  series: [
    {
      name: 'scatter',
      type: 'scatter',
      datasetIndex: 0
    },
   
  ]
};
```

### Current Behavior

![image](https://user-images.githubusercontent.com/31985427/216753994-4bce2f85-eb3c-44eb-a4e1-0e1b3cd17f0d.png)

### Expected Behavior

there is a ponit where x = 1

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Why _dataset.source_ has first two data points as strings ? Why is yAxis type 'category' ?
Is this what you are looking for - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PTCmGMAsEMCcBcDOA6WoDmBLR9SwCqzQB2iAZgPawC2AFBAMrzTzLxGmU2oZqKKYKxAJQBuAFAUADvEHEABAF55Ab3Hz5AExbREoeAC55AbXUbVZ8_MQUArrHCgjpq1eMBGADTyALAA4ANgAmZB8AXU9LV2Mg7wBWIIBOH2QAdgiotwBmeMSslLiM13NjH29U9wrkAAYi4pM47z9EgJTwyPqTAO93aqC-5CC64uNUnvcWkMKO-uM_Hp9EoL9kLOHoxJ6AxOrEwfW3Xp6_OJ9U5ESDkvcveSD3AMrkPyuND1i7gICslfdXk3cOXk-W-bX-HjKvgCqTie3amWujXkcT8Z1-4Ie3mhflRyACGLG8lSPh8wTxGPmRLyiTiaTCCPpVgAvmY6rJ4AAbJwWKy4AAehnkAHIJn53PIALTyCaJPzydCwCj8LQUaigHCYcDyKSKzS2cDweQAcQAIgAFeS0diYDkcuTyACethIwiFMw0iFsACN-YKhQAhB3yRjMVhoBXqgRCN1RT1eu3EADWRiFkHg8CkiAMICw8Eg3uQ4FVYCL1DIoBLMAQiAlOBYMasXLIfscxFwsCFZiZM3gFAoHNkUiMal5sEw6HQeBT0D52Ab5hn2DNFEwbanPNc8AdUm5QvAiv4neZXZmfIAgrOsxuNFudynwCwMFQHfOPVI7fAADKr7kj1wJ0AmAdLlhwRG9t13bREEgUBNCPVwWWPDRuzMB0L2wUCrEQd9MC_H9MP_H8gJA69NwglMoJguCEUQ8xaJQj08EwdVnCiP9eXI4VEAfdM8FfeRaPpJlRCAA) ?

![image](https://user-images.githubusercontent.com/13038071/216799586-27e828d5-4727-4640-97b8-d82f8cafdee0.png)

**Comment by czphappy** [comment]
yData is usually a string by default. No matter whether I set the type of the y axis to value or category, the first data is missing.


echarts.registerTransform(ecStat.transform.regression);
option = {
  dataset: [
    {
      source: [
        ['aa', '4862'],
        ['bb', '5294'],
        ['vv', '5934'],
        ['ff', '7171'],
        ['dd', '8964'],
      ]
    },
  ],
  title: {
    text: '1981 - 1998 gross domestic product GDP (trillion yuan)',
    subtext: 'By ecStat.regression',
    sublink: 'https://github.com/ecomfe/echarts-stat',
    left: 'center'
  },
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'cross'
    }
  },
  xAxis: {
    type:'category',
    splitLine: {
      lineStyle: {
        type: 'dashed'
      }
    }
  },
  yAxis: {
    type:'value',
    splitLine: {
      lineStyle: {
        type: 'dashed'
      }
    }
  },
  series: [
    {
      name: 'scatter',
      type: 'scatter',
      datasetIndex: 0
    },
  ]
};

![image](https://user-images.githubusercontent.com/31985427/216869287-7c104d00-148b-4c9f-8244-ed4650ba4ce8.png)

**Comment by plainheart** [comment]
Just set [`sourceHeader`](https://echarts.apache.org/en/option.html#dataset.sourceHeader) as `false` to tell ECharts that the data starts from the first row. The default automatic detection might be not perfect.
