### ISSUE TITLE
[Support]  What format should be the boxplot data to avoid the transform function, is it possible?

### ISSUE THREAD

**Issue by ovvleek** [apache/echarts#18232]
### What problem does this feature solve?

With a very big data, the time for calculating all parameters increases, it would be good if ready-made sets could be passed  for save time

Set of parameters [min, Q1, median, Q3, max] for boxplot I have initially, how can I render them in echarts ?

### What does the proposed API look like?

I would like to pass a ready-made set of parameters [min, Q1, median, Q3, max] for boxplot to the source data

**Comment by helgasoft** [comment]
possible thru _[series-boxplot].data.value_, see [docs](https://echarts.apache.org/en/option.html#series-boxplot.data.value)

**Comment by ovvleek** [comment]
> possible thru _[series-boxplot].data.value_, see [docs](https://echarts.apache.org/en/option.html#series-boxplot.data.value)

Thanks a lot. Further i'l be more attentive.
