### ISSUE TITLE
[Bug] Yaxis , type : value is not plotting data correctly

### ISSUE THREAD

**Issue by Avesha-Rakshith** [apache/echarts#18235]
### Version

5.2.1

### Steps to Reproduce

create a line graph charts and add series to it,
```js
 xAxis: {
      type: 'category',
      boundaryGap: false,
      data: getEchartAxisLabel(dataResponse),
      axisLine: {
        show: true,
        lineStyle: {
          type: 'solid',
          opacity: 0.3,
          width: 1,
        },
      },
      axisLabel: {
        show: true,
        margin: 16,
        formatter: function (value, index) {
          return moment(value).format('hh:mm a');
        },
      },
      // name: "Time (UTC)",
      nameLocation: 'middle',
      nameTextStyle: {
        color: 'rgba(18, 21, 62, 1)',
        fontStyle: 'normal',
        fontWeight: 'bolder',
        lineHeight: 14,
        padding: [25, 0, 0, 0],
        fontSize: 12,
        fontFamily: 'Bai Jamjuree',
        align: 'center',
        verticalAlign: 'top',
      },
    },
    yAxis: {
      type: 'category',
      // max: 400,
      position: 'left',
      axisLine: {
        show: true,
        lineStyle: {
          type: 'solid',
          opacity: 0.3,
        },
      },
      axisLabel: {
        show: true,
        margin: 16,
        formatter: function (value, index) {
          return `${value}`;
        },
      },
      name: 'Latency(ms)',
      nameLocation: 'middle',
      nameTextStyle: {
        color: 'rgba(18, 21, 62, 1)',
        fontStyle: 'normal',
        fontWeight: 'bolder',
        lineHeight: 14,
        padding: [0, 0, 40, 0],
        fontSize: 12,
        fontFamily: 'Bai Jamjuree',
        align: 'center',
        verticalAlign: 'bottom',
      },
    },

```

### Current Behavior

when yaxis type is changes to category the data are plotted correctly , but when it changes to data plots wrong 
eg : https://echarts.apache.org/examples/en/editor.html?c=area-stack
here the yaxis data and series data plotting is not matching

### Expected Behavior

y axis data should to be plotted with exact with series data 

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:
```

**Comment by helgasoft** [comment]
Minimal Reproduction - missing
Steps to Reproduce - incomplete code
Current Behavior link - broken

**Comment by logustra** [comment]
I'm facing the same issue.

![Screen Shot 2023-03-01 at 11 30 54 AM](https://user-images.githubusercontent.com/13871363/222045627-ab02198a-fafb-44fc-8864-6c1e5229c63a.png)

**Comment by helgasoft** [comment]
This is a [**stacked** area chart](https://echarts.apache.org/examples/en/editor.html?c=area-stack), vertical values are summarized.
top value = 230+330+330+330+1330 = **2550**
No bug, no problem.
![image](https://user-images.githubusercontent.com/13038071/222047818-66377b6b-c6d1-48d7-890d-fbee3b6bdb6a.png)

**Comment by logustra** [comment]
> This is a [**stacked** area chart](https://echarts.apache.org/examples/en/editor.html?c=area-stack), vertical values are summarized. top value = 230+330+330+330+1330 = **2550** No bug, no problem. ![image](https://user-images.githubusercontent.com/13038071/222047818-66377b6b-c6d1-48d7-890d-fbee3b6bdb6a.png)

oh I see.., noted.
thanks for the answer 😄
