### ISSUE TITLE
Need nearest point data in event on hovering on series line

### ISSUE THREAD

**Issue by b09h** [apache/echarts#18262]
### Version

upto latest version

### Steps to Reproduce

1) Create line chart
2) You can capture event on hover on data point using mouseover event, but you cannot capture on hover of series.
3) Getting tooltip on hovering on series, but not able to capture event
![image](https://user-images.githubusercontent.com/60179972/218390404-72b52cee-f17a-453b-8702-010884b8b228.png)

### Current Behavior

1) Unable to get event from series

### Expected Behavior

1) Capture mouseover event on hovering on series as well as data point based on the type (series, datapoint)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Please add one more event to capture on hovering on the empty space inside the chart. Getting event for hovering outside of the chart i.e., globalout which won't solve my problem
If this is not comes under bug, then please let me know. I will add in features list

**Comment by susiwen8** [comment]
https://echarts.apache.org/en/option.html#series-line.triggerLineEvent

**Comment by b09h** [comment]
No. 
Unable to capture the below (mouseover) event on hovering on series, but getting the event on hovering on data point
https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseover

**Comment by helgasoft** [comment]
yes, all you need is [triggerLineEvent](https://echarts.apache.org/en/option.html#series-line.triggerLineEvent)
check _mouseover_ example in **Demo Code** at bottom of #2941

**Comment by b09h** [comment]
![image](https://user-images.githubusercontent.com/60179972/218984761-1635cb3f-1741-48db-b16d-b3b697a16506.png)

Hovering on the data point got the event with data. After adding the trigger line event, i am able to capture event.
On hovering on the series line or data point, I need the nearest data point also.

**Comment by b09h** [comment]
Ok, Its fine with 18288
But, is it possible to get nearest data point when we hover on the series?

**Comment by b09h** [comment]
Closed the ticket number #18288 & we will check/follow this thread only. Please help me to get the nearest data point.

**Comment by helgasoft** [comment]
Nearest point with _tooltip: {trigger:'axis'}_ - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG5gRqysVBwEtIy4eLQOJHiJEFSEsKL8xB6CwmIAjACsAAw8sABMAMy1DfUALHX15QAcdeWNlX1tAOydAGzV1qEeFNR0_hDQykV2JLZ2ANwoKAC25ADC2owcYAB0MAAUtNoQrNoLd2AyFyAAlAgAfMWwe4fHZ9kwAB5cBQaAXdwlSBgfzeJAsDBgOhCMCMACS0AEVAwiFosAA1CBTgAjZj0bSiSanFHozHY2AOWD2V5bOwsoA)

**Comment by b09h** [comment]
Thank you, it worked for me! :)
