### ISSUE TITLE
[Feature] How to add morph animation when Sankey update

### ISSUE THREAD

**Issue by li942475402** [apache/echarts#18278]
### What problem does this feature solve?

Make the data easier to understand through morph animation

### What does the proposed API look like?

animation: boolean

**Comment by li942475402** [comment]
I don't know if this is relevant, but I've noticed that the Sankey chart redraws every time the data is updated

**Comment by li942475402** [comment]
maybe like this without wrong position trasition:https://echarts.apache.org/examples/zh/editor.html?c=sankey-vertical&code=MYewdgzgLgBAJgQyggKgU2jAvDA2gKBhgG9Cj4kEAuPM8kmMBAWzRoHIF2AaGASzgcuvPlDTMAylACeAGzYNQskACcOAYgBmmgCxwdm9jAC-vOGgAOUABY0ADCe51yxRiwXsARj36CYXn1FxKTkFVyVVDW1gAFYAZjgjU3hLGxoARkdnIlcmVg5gQL92QpExSRl5GnCQZTV_LU1YhKSzVNsYTNNshjyPRJFigf5ykKrFWsiGuIA2YCaATlaUqw6AJiz6HLd8_zQijn2y4MqwmAj69nVZ-eAlxxW0mA3urd73DkNBz8DR0-rzpNLtc5otluZVjQXk43rkPv4AOYHRG_E6hAEXDQ3MEPCFPF7OAC6MPIsj4YAA1hAaARYTAICAAK4qYAeYQwZAqBFoKAcby8ABuCFkjIUM02W1cDOZrKEPk53N5_lKMCFIoUOgl9ClTJZHn5HIQXJ5HGGatFNDiWpc9N1sv8BoVJr2PnNCitr0ltplHhVTqV7C-quFFpgHpJ2u9eoK8qNio4SMFIYUXSJZE9pHoiGQNJ6cN2nGRheOFXREzqUV0-kMuPa9mt2z6fKLBqCpfGNQrDWi8UStchnQb7wLKoEMZLYzOmO7TV74Lrg89kab_mGY9XqPbU6BWNBd3nA-heZ2HiOvkOm8nGJ30z392SePWQ_zHiD68Dl_-5amV2x-_7-LPieCZFomIxoh2gJdr-d4HoBxhEhGMBkpS1K0HS0rRv47L-s2SbqjQmpLjamH2sWhrGgGKpupaQGkfqsaUaarrJrRxHbPReEUfGLr4aGXRIRxdq-oxPEfnxChHhhwnjtxzrsGBNGLmmRAZs42bUOhXoruR77sm2V7fsC2h6AYcEdA47HDgx3wOp-Zadj-jTNH2D4LgJx46aOxSjn8DlQU5PYtABHQeXSOlrkM9mQdOMG3PebSHkBOlnu-qV-TFN5xTiblJVZL4_LZ4ngVu17QSC8XmVCyXwgpoHRdu5V_gljxPgh9DEs4KFUrm0k-nKvC4XZEk0AA7HRMnYaJ8nUaxMBEYJDCccNckBmac1SV6y0BINcbyWeSkxBN_XKtNAZBkpYVbZNJRnSBI1hiYKlPYSADc-D4CAVh8OA2AkGQEBoCofAYL1Lg9O-EAIJSaDSDwPQ6VDMNw4tMgWB4SMUrD8NvBpNKdW83VobgBNbNDfDMEgP1gAAIsyVPgBkMR2HYi3k5TUDU3TKgM2AACqFjZimzOswjIDmAA6gITzpKLbyMmAfACkDUOyCgPOQKI1M0FAKiiotsgINITJQAAkmIPOc-AaFy1sqgg2AAbKyonPAMKONbChaCGZmbwBZcCI83ADtQOwPTteQEeEvgxjvfg8iwOS5gAB5_XY72A2bjtA2qAAUucAJTYAAfP9RBfVbYAAHSA8DGC4HYhJVxpf0aeg0C4EnaDJ03GnveX33gDXQMgxADdN0TreUO3UCd2AKcT-SVL9zAzDSAAwtYRpQMPUAAPKD2AucV9TBcrwA9OfgKQLUaBV8oCK52vm_b1XioAFoqIXNdQKoCDclXAA-ioEAIAoBj3SE3QBwBrB8FkHAFQaAwDjyrgIM-ZAu7JwANRYJXnwTQMBc6YJgMXHAbcMA73kGABENgi6-yIMQnA6d0wx14DoFmdgz5AA

**Comment by li942475402** [comment]
But now he's like this, with almost no animation: https://echarts.apache.org/examples/zh/editor.html?c=sankey-vertical&code=MYewdgzgLgBAJgQyggKgU2jAvDA2gKBhgG9Cj4kEAuPM8kmMBAWzRoHIF2AaGASzgcuvPlDTMAylACeAGzYNQskACcOAYgBmmgCxwdm9jAC-vOGgAOUABY0ADCe51yxRiwXsARj36CYXn1FxKTkFVyVVDW1gAFYAZjgjU3hLGxoARkdnIlcmVg5gQL92QpExSRl5GnCQZTV_LU1YhKSzVNsYTNNshjyPRJFigf5ykKrFWsiGuIA2YCaATlaUqw6AJiz6HLd8_zQijn2y4MqwmAj69nVZ-eAlxxW0mA3urd73DkNBz8DR0-rzpNLtc5otluZVjQXk43rkPv4AOYHRG_E6hAEXDQ3MEPCFPF7OAC6MPIsj4YAA1hAaARYTAICAAK4qYAeYQwZAqBFoKAcby8ABuCFkjIUM02W1cDOZrKEPk53N5_lKMCFIoUOgl9ClTJZHn5HIQXJ5HGGatFNDiWpc9N1sv8BoVJr2PnNCitr0ltplHhVTqV7C-quFFpgHpJ2u9eoK8qNio4SMFIYUXSJZE9pHoiGQNJ6cN2nGRheOFXREzqUV0-kMuPa9mt2z6fKLBqCpfGNQrDWi8UStchnQb7wLKoEMZLYzOmO7TV74Lrg89kab_mGY9XqPbU6BWNBd3nA-heZ2HiOvkOm8nGJ30z392SePWQ_zHiD68Dl_-5amV2x-_7-LPieCZFomIxoh2gJdr-d4HoBxhEhGMBkpS1K0HS0rRv47L-s2SbqjQmpLjamH2sWhrGgGKpupaQGkfqsaUaarrJrRxHbPReEUfGLr4aGXRIRxdq-oxPEfnxChHhhwnjtxzrsGBNGLmmRAZs42bUOhXoruR77sm2V7fsC2h6AYcEdA47HDgx3wOp-Zadj-jTNH2D4LgJx46aOxSjn8DlQU5PYtABHQeXSOlrkM9mQdOMG3PebSHkBOlnu-qV-TFN5xTiblJVZL4_LZ4ngVu17QSC8XmVCyXwgpoHRdu5V_gljxPgh9DEs4KFUrm0k-nKvC4XZEk0AA7HRMnYaJ8nUaxMBEYJDCccNckBmac1SV6y0BINcbyWeSkxBN_XKtNAZBkpYVbZNJRnSBI1hiYKlPYSADc-D4CAVh8OA2AkGQCBgHwzBID9YAACLMqD4AZDEdh2CSgPA9DENQ1AYMAKoWNmKZwwjZAQGgKh8BgvUuD074QIDFJoNIPA9DpVOUrT9NvDIFgeEzNN04tGk0p1bzdWhuAC1sSMg-j4CQyoKOw_Di3iyj0so1jONy_jbxgCA5gAOoCE86Qa1ssgINITJQAAkmIMuS5A9iLaoJNgAGApE-jwDCqzxvkmghmZm8AWXAiMtwE7UDsD07XkFHhL4MY734PIsDkuYAAef12O9hOW87RNqgAFPnACU2AAHz_UQX22wAdITxMYLgdiEtXGl_Rp6DQLgKdoKnzcae9lffeAtdEyTECN83Qtt5QHdQF3YBp5P5JUgPMDMNIADC1hGlAI9QAA8kPYD51XYNF6vAD0F-ApAtRoNXygIvn69bzv1eKgAWioxe11AqgINyauAB9FQIAQBQHHukZuQDgDWD4LIOAKg0BgAntXAQ58yDd1TgAamwavPgmgYD5ywTAUuOB24YF3vIMACIbAl39kQEhOBM7pjjrwHQ8M7DnyAA

**Comment by li942475402** [comment]
Modify source code, change function named `render` in `chart/sankey/sankeyView.ts`, change nodes and edges relative position to absolute relative, like this:

```typescript
// remove this
    group.x = layoutInfo.x;
    group.y = layoutInfo.y; // generate a bezire Curve for each edge

// add offset to graph
      curve.setShape({
        x1: x1 + layoutInfo.x,
        y1: y1 + layoutInfo.y,
        x2: x2 + layoutInfo.x,
        y2: y2 + layoutInfo.y,
        cpx1: cpx1 + layoutInfo.x,
        cpy1: cpy1 + layoutInfo.y,
        cpx2: cpx2 + layoutInfo.x,
        cpy2: cpy2 + layoutInfo.y
      });

        var rect = new graphic.Rect({
        x: layoutInfo.x,    // add this line
        y: layoutInfo.y,    //  add this line
        shape: {
          x: dragX != null ? dragX * width : layout.x,
          y: dragY != null ? dragY * height : layout.y,
          width: layout.dx,
          height: layout.dy
        },
        style: itemModel.getModel('itemStyle').getItemStyle(),
        z2: 10
      });

```


finally


https://user-images.githubusercontent.com/30969393/219288623-22d08889-4c8e-4f8f-8ce2-3019af147c2c.mp4

**Comment by Hack-DJ** [comment]
> 

请问只改了这个地方吗？我这边改了后测试好像无效果呢。
