### ISSUE TITLE
[Bug] It seems that the fontFamily of any option is not working, and the preview on the official website is the same

### ISSUE THREAD

**Issue by hsutingwei** [apache/echarts#18272]
### Version

5.4.1

### Steps to Reproduce

```
option = {
  xAxis: {
    type: 'category',
    nameTextStyle: {
        fontFamily: 'DFKai-sb',
    },
    data: ['未結單', '標示', '標楷', '力量', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar',
      showBackground: true,
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.2)'
      }
    }
  ]
};
```

### Current Behavior

I want to set the font to DFKai-sb
`fontFamily: 'Arial, DFKai-sb'`
I remember that the previous version was OK to write this way, but the current version did not work.
So change to DFKai-sb only
`fontFamily: 'DFKai-sb'`
But still no work, even the Example in the official website to modify the fontFamily also did not change the font.

I need to modify the font in xAxis, yAxis, tooltip, legend, label, but It looks like only tooltip works.

### Expected Behavior

The name on the x-axis should be marked in DFKai-sb.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
not-a-bug
Are you trying to set font to [axis labels](https://echarts.apache.org/en/option.html#xAxis.axisLabel.fontFamily) ? If yes, then no need to set [xAxis.nameTextStyle](https://echarts.apache.org/en/option.html#xAxis.nameTextStyle).
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWkwBsCmAXMuppmHgB5gDKYAnvkahqZgGYw0QBehsATABYANCVawA9BI7QwAMQCGAWwg46RAOQBBAE4QFODWNYz5y1etgalMYAGcQCgMZ4NolpgC-w2MayUwTQAVCFxXd1Z8NkCrF1k8HSMWbzEKLQoIOyY_BQy7ABkFACM8HCZfD1JTRRU1TQAROQBpBQgAWjsitz9MJ2AcYB1NHTwAE27KlMrRhTAFIgBtDUAqc0AFX0A61TcrQEwrQC5PLY1twHdLA8BspUB5xIO5PQPqWduAV2gNAF0xKcw6dMzsyuhlQgaL55LZRGIaOLkRIRUj_JR4IIBWgMPjMcSwPoDIZWIo4B7hHqwUzUHh8IQw1hSarmOpWRotdqdLaEqmcGoWTS6fSGClVNk0ywaABCOgedgAFrBqE49OBYABZIJJVgfWBTTwAbiAA)

**Comment by hsutingwei** [comment]
Thank you! This is exactly what I needed.
