### ISSUE TITLE
[Bug] 为什么把echarts的实例直接赋值给vue3的响应式对象，然后渲染参数，柱状图的tooptip设置了trigger：axis,会不显示tooltip浮层，而把echarts实例对象直接赋值给变量，用变量渲染options后再赋值给响应式对象就没问题。

### ISSUE THREAD

**Issue by zy-smile** [apache/echarts#18273]
### Version

4.9.0

### Steps to Reproduce

[Bug] 为什么把echarts的实例直接赋值给vue3的响应式对象，然后渲染参数，柱状图的tooptip设置了trigger：axis,会不显示tooltip浮层，而把echarts实例对象直接赋值给变量，用变量渲染options后再赋值给响应式对象就没问题。

### Current Behavior

[Bug] 为什么把echarts的实例直接赋值给vue3的响应式对象，然后渲染参数，柱状图的tooptip设置了trigger：axis,会不显示tooltip浮层，而把echarts实例对象直接赋值给变量，用变量渲染options后再赋值给响应式对象就没问题。

### Expected Behavior

[Bug] 为什么把echarts的实例直接赋值给vue3的响应式对象，然后渲染参数，柱状图的tooptip设置了trigger：axis,会不显示tooltip浮层，而把echarts实例对象直接赋值给变量，用变量渲染options后再赋值给响应式对象就没问题。

### Environment

```markdown
- OS:
- Browser: chrome
- Framework:Vue3
```

### Any additional comments?

[Bug] 为什么把echarts的实例直接赋值给vue3的响应式对象，然后渲染参数，柱状图的tooptip设置了trigger：axis,会不显示tooltip浮层，而把echarts实例对象直接赋值给变量，用变量渲染options后再赋值给响应式对象就没问题。

**Comment by susiwen8** [comment]
https://echarts.apache.org/zh/faq.html
