### ISSUE TITLE
Data is not able to capture in event on hovering on series line

### ISSUE THREAD

**Issue by b09h** [apache/echarts#18288]
### Version

Latest version

### Steps to Reproduce

1) Set Trigger Line event to the chart 
2) On hovering the series line, capture the data in mouseover event
3) Data regarding, (x axis & y axis) are not coming

### Current Behavior

![image](https://user-images.githubusercontent.com/60179972/220073885-3efb0292-6bed-4534-b733-d0b82cea2006.png)
![image](https://user-images.githubusercontent.com/60179972/220073975-f974ba4f-2b52-4748-82bb-78ebd3a3346a.png)

### Expected Behavior

Expected the data (including x axis point & y axis point). If possible, expecting the nearest data point value also.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
seems a duplicate of #18249
see [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8tSRg2BvAsAKFrSYANgKYBcGYxAHmOQOQC2wArgM7HABuxATrACbEmdAL4AaHHioBBKhFbl04ybACes-YuW5Y7HhGILYAbRV4sOvHn4BDMDfLHjARjHOADAF0xJgExjfX28TAGYAgA5g4wAWAJCogFY3AE5PbzMrMFUQMlg6QghoYjoJSytWJmAwAAtyMB5mYgyRFXSdMGBgQkgQRRwASH76iABzEd56GzlWEoH-gDNgHgY7Sh5yACJ0AGMRDYGRWBwRAG4cHE4bPgAvPkQGVQBhaquwADpxsAAtHgAKAEozthbm8YL9GCx2FxeCVYPNmNBtig4L8QFcbAxWP8MCoQMBWGhjGieBjWG9iNxoO9bgANHzE0nkynUngATU8QLwYAYIDQD2erze2xg3B4YAAYjxgAwAAoQKjEQi_dCwEb6fgASWggio5HcsHEsDxWM5sCoaGJ7HFhGAdl-3JAxi8bw64vlxH4v2c_3-KlUFquVptdodLk8LuAboVnu9vp0_JeYre7DAAHlwFBoMqMlyIERcuhKDR6FREHQANRm8uw1TwCuqQ4qESA46AoA)

**Comment by b09h** [comment]
Thanks for the replies.
I am closing this issue.
The main issue/ feature is in #18262 ticket. Can you please help me to get the nearest data point data on hovering on the series.
