### ISSUE TITLE
[Feature] Grid should be automatically fitted to the left, right, bottom, and top based on label content and dataset

### ISSUE THREAD

**Issue by nghiepdev** [apache/echarts#18286]
### What problem does this feature solve?

Currently, configuring the grid is very manual and inflexible. Labels can vary in length based on dataset, but the grid does not automatically fit them.

https://user-images.githubusercontent.com/4768095/220033156-5bb47e52-6983-4392-956e-92df75b127f8.mov

### What does the proposed API look like?

I just want to have an option for automatic grid enabled fit `left:0 , right: 0, bottom: 0 and top: 0`

https://user-images.githubusercontent.com/4768095/220031579-7b4fbcf6-663a-4dc4-83e3-c601299829dc.mov

Example AntChart works https://charts.ant.design/en/examples/dual-axes/column-line#column-multi-line

**Comment by helgasoft** [comment]
see if [grid.containLabel](https://echarts.apache.org/en/option.html#grid.containLabel) works for you

**Comment by nghiepdev** [comment]
Thanks @helgasoft
