### ISSUE TITLE
[Feature] Add a line for scatter chart

### ISSUE THREAD

**Issue by bbcfive** [apache/echarts#18291]
### What problem does this feature solve?

Is there anyway to achieve a line of scatter chart like below(the orange line)?
<img width="337" alt="image" src="https://user-images.githubusercontent.com/22639560/220228211-2b888e25-7a02-4c97-8cb8-96568c24ab75.png">

### What does the proposed API look like?

I don't know whether if `markLine` or `markArea`  can do this

**Comment by li942475402** [comment]
You need more than one series to achieve this effect, Maybe this example will be useful: https://echarts.apache.org/examples/zh/editor.html?c=line-step

**Comment by bbcfive** [comment]
@li942475402 thx for the idea! I found markLine can do the same by setting data coord
