### ISSUE TITLE
[Bug] BoxPlot does not support NaN

### ISSUE THREAD

**Issue by mzy2240** [apache/echarts#18295]
### Version

5.2.2

### Steps to Reproduce

See the additional comments

### Current Behavior

The current boxplot does not allow NaN.

### Expected Behavior

The current boxplot does not allow NaN.

### Any additional comments?

Assume on the x axis there are 3 ticks, like 1, 2, 3, and I only have box plot data for 1 and 3, currently there is no way to plot like this, due to the lack of support for NaN.

**Comment by helgasoft** [comment]
not-a-bug
Why use NaN when an empty array will do the job? [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=boxplot-light-velocity&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcsA2musiaRjgB5gEDkAshAMYAWOWAzjALQPAAnXAE9YAUSogcAiAFsc0MHQA05UrgBmtWHWYKw0umoC-qiqgroDNegFcQUgQQCKAZlgBqWAEYAdAFZYACpYAElnACVYAB1oLGAAd2kXb1geHwDgsMiVNXQAI0EAE2kAYWB4px0AYgBOetzLWEKBEoEAdQgisFYCbzNLazAAZTBhXAILJtgNGDB2nAgAc1ZtOmhBWQBDLEbp2cVhiAAvfB8AFgGmrAhoHAAJRZXtACYABjzYU0_NNe83gCkewoYFA9FqgKMFGMJAAugMilswFtODhtMRzJ8APRY2AgARoyDSHjLDYEz7cWwCPQEDHTemEAAc_jeylgAHZzqzYBDuf92dzaq5uczBSy2bVGYKpWzGTKfG9FRL5ULuQA2cUctUi_5s_5KhUG2raiXa-GfenoQjGwVc022kXyqUizVywUGxl22CM4Vs9kQ2W671Op2-70G_3c9km8Nvc2W6aEeGwHFMkOOkUx9nvP052BqvOMmO1AUS10qoOi2Wl71ez0ukV1ptxq4J0hMgPeyuVwsRmvRqNe9magcSoO1QudosZ3ONhuykdS-Ntigdud-p1B0ddqNTnvz701xlHrd18de2quj2VgWwi2WO_Q1tTEECLbQTizASySb3sZSehCkkeIlFbChmBgDRlkmWAIAMWQADktnkAAxTYkQMKo6GofFkAANx2WwcGMOgvk-GEnzUF9SA0ARgFkAARJEUTRUJoBKKg-jAmY6NkAAVN8Py_WQIhwThbCwbRvBMOEBlBCpIBAX9X2WJZkh0OCcFkYFYC2KgIE4AAFYBbkw5TBmEACdE4VgtiKRIoVICivgGJYZCKcz0F-eh_iBVsZGeHzIVbQowFBH8dG8fwgRIb50CoABBfTOE8jBLLOXQkRwJZBGEHTClsditgEYQAHEtiUjABCI1toGQnBysq301E4EAbjABKCS2VL0BsxICA0HZURMVtWvagAZW4zmo3rWH6mYhpwGT0Di2BhCSgzUv_DKCKwIidLq-R6AAa1kLFOFgWRblsC6XnqZRFTeHSxrgzqcG6sgmj6hICDAaqluhWKBlRGQxNpKjPkOjKgLa4BQM-bbAOAYC4Z09BEWRVEwDYji-hGiGmih-hgFsbAIEMbjEes5gMIpz4MZY7H2OoAgXmW2A72MABuIA)
![image](https://user-images.githubusercontent.com/13038071/230172576-20424e2b-ee62-441d-8cc0-631d01fc6ad0.png)

**Comment by mzy2240** [comment]
@helgasoft thank you! The demo code is really helpful!
