### ISSUE TITLE
[Bug] SVG loaded with registerMap is black

### ISSUE THREAD

**Issue by krabouilleur** [apache/echarts#18299]
### Version

5.4.1

### Steps to Reproduce

There is an img : [https://lashermes.com/wp-content/uploads/map2.svg](https://lashermes.com/wp-content/uploads/map2.svg)
This img has colors.

if I load this image with registerMap: all element in the svg is black

```
$.get(
  'https://lashermes.com/wp-content/uploads/map2.svg',
  function (svg) {
    echarts.registerMap('a', { svg: svg });
    option = {
      geo: {
        map: 'a',
        roam: true,
      },
      series: [
      ]
    };
    myChart.setOption(option);
  }
);
```

### Current Behavior

The content of svg is black. But this SVG is normally in color
![image](https://user-images.githubusercontent.com/53522372/220615054-efe36e06-4f6c-451d-a271-f7134e3f3d93.png)

### Expected Behavior

The svg could be in color
![image](https://user-images.githubusercontent.com/53522372/220615174-b43b774f-b7d3-4439-9446-586415e183d7.png)

### Environment

```markdown
echarts: 5.4.1
```

**Comment by plainheart** [comment]
The style defined by CSS is not supported. You have to set the color with `fill` / `stroke` attribute.

**Comment by chj-damon** [comment]
this problem still exists. can someone open it again?

**Comment by chj-damon** [comment]
@krabouilleur have you solved this problem?

**Comment by krabouilleur** [comment]
> @krabouilleur have you solved this problem?

Nope

**Comment by chj-damon** [comment]
this is so wierd. I tried those examples that echarts provided. it works well online, but it broke when I copied those code to my project locally. I'm so fucked.
