### ISSUE TITLE
[Bug] series.labelLayout: hideOverlay not working with yarn build and yes in development

### ISSUE THREAD

**Issue by Eloyts97** [apache/echarts#18300]
### Version

5.4.1

### Link to Minimal Reproduction

https://jsfiddle.net/Eloy97/s6ctu3fw/4/

### Steps to Reproduce

The test is carried out with an application in ReactJS and with another that is Vite + ReactJS.  

### Current Behavior

The chart behaves as expected with series.labels Layout: {hide Overlap: true} when you run the yarn build, in production the chart displays differently.
![yarn-build](https://user-images.githubusercontent.com/75694174/220686783-f7ed2568-6218-4288-8824-1a38cc3c37fc.png)

### Expected Behavior

The chart behaves as expected with series.labels Layout: {hide Overlap: true} on development
![development](https://user-images.githubusercontent.com/75694174/220686836-b2967a82-30df-4465-9a04-45455bbf1bb6.png)

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Browser: Chrome Versión 110.0.5481.100 (Build oficial) (64 bits)
- Framework: "vite": "^4.1.0"
```

**Comment by plainheart** [comment]
Sorry this is an known issue that the `LabelLayout` feature will be tree-shaked when building. Please import this feature manually for now.

```ts
import * as echarts from 'echarts/core'
import { LabelLayout } from 'echarts/features'

echarts.use([LabelLayout])
```

**Comment by Eloyts97** [comment]
Thanks, it's works.
