### ISSUE TITLE
请问candlestick是不支持加载graphic元素吗？

### ISSUE THREAD

**Issue by gaoxianglyx** [apache/echarts#18305]
### What problem does this feature solve?

我的需求是在k线图上实现单个蜡烛的拖拽，用candlestick绘制出来k线后，用graphic属性添加circle元素失败。
```
graphic: echarts.util.map(data0.values, function (item, dataIndex) {
          return {
            type: 'circle',
            position: myChart.convertToPixel('grid', item),
            shape: {r: 5},
            invisible: false,
            draggable: true,
            ondrag: echarts.util.curry(onPointDragging, dataIndex as number),
            onmousemove: echarts.util.curry(showTooltip, dataIndex as number),
            onmouseout: echarts.util.curry(hideTooltip, dataIndex as number),
            z: 100
          };
        })
```

尝试不用k线图是可以加载的，如果是k线图不支持graphic，请教有实现k线图拖拽修改数据的方案？

### What does the proposed API look like?

k线图拖拽蜡烛修改数据

**Comment by helgasoft** [comment]
cannot reproduce, demo code is incomplete

**Comment by helgasoft** [comment]
here is how to add a draggable graphic **circle** on candlestick chart - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=G4QwTgBAzgngtgIwPYBsDKBLAXgUwgXggBYAGAbgChRIATEAFxAIgG0KJWByAJhIEYA7AFo-JIdyKcANBF4BdKey69BIsdwHSIAZhJyKcykgAO9DEgB2zAN5KAHgEE7GKAC4ItjhzqN3LHvzCouKSMgGqwdwArFrhQeoAbLEq8eKa-hwAvoocME4u7tbZSgDmYBg0hcUcUDjlOG6sShyeXhz0MMY47pwAxiAWNCgNZr0A1tLNXj4gflNtLLwy2kQyossAHArzXiyky1HLJDJRejltu9p8m8vaMkRE2xeXG2uHEO9E3BkXP1lK-kylFq9AAKhg4DgkABXegACjhAEoCAA-DxKOAwADCAAtwPQAHQggDypnMFjhrQ4ZRAxhxGF67hwvTxYHoUAJsIwKAJcFpcJmMgAZtCLL0zJYIAKGCAAJL0HBwGQzWWDHB2ZFUrxgHD0aFgKxatodLo9XoYMC9YaTZ41PGmjwQMDuWCIVCYXAQAD0sgg1VtxiQUAwEos7kxuPxBN6lmAdTBSAAChg7DgUHDOGUKloVQq4IiZF6vTsOEWMBZgC4MAhhu56GBoThzs8aGAQCUSiAa90IPXG82Llh3KJjiWIJZW-2mSz8RyuTzevqwDA4ZZE0hy_QACJtjvlkrKmWqmjqxE7IFTTJnrKIyhXygisWh8cWdebnftkr76WMY_qmSBlAmpKDGFhQKgOAEigSAlEilAcBGrKEiSZKWJSUxmPQtaOgqdj0O4KpqnYEAANQQJwEB2K4FFkYBBJIEKQoggAGqR5EQDA1FsXRDFMbqACafpKPeFCZEAA).
A "single candle" could be built as [graphic group](https://echarts.apache.org/en/option.html#graphic.elements-group.type), or just by adding a data item to the chart.
Graphics created with _convertToPixel_ are not responsive.
![image](https://user-images.githubusercontent.com/13038071/221008196-19dd786e-3ac5-4d19-807c-6df4db100612.png)
