### ISSUE TITLE
[Bug] 图表显示与数据不符

### ISSUE THREAD

**Issue by zhanjunjie2019** [apache/echarts#18309]
### Version

5.4.1

### Steps to Reproduce

1.设置一串从2015年到2022年每年的富豪前100名的资产数据，都是正数。
2.使用《动态排序柱状图 - 人均收入》这个实例，却出现了负数和NaN的显示

### Current Behavior

1. 数据中没有任何负数，却显示出负数的结果。
![image](https://user-images.githubusercontent.com/48537142/221348573-39e683c0-6411-4b39-9df9-d8f26b21e3eb.png)

2. 这是一个动画图标，2秒更新一次数据，但是在0~2秒之间会显示出条形图的动画，但是数据却是：NaN，直到2秒的那一刻才显示出数值。这是一个不合理的状态，应该是在0~2秒之间，显示从0到具体数值的过度才对？
![image](https://user-images.githubusercontent.com/48537142/221348932-5ce9b4f7-4ccf-481a-b0c8-dd9b75d2c6e6.png)

### Expected Behavior

1. 应在每一次过程中显示上一个数据到下一个数据值之间的过渡，两个值都不是负数的情况下，不用改计算出负数。
2. NaN的数据在过渡中，不应该显示。若中间的都一次刷新使数据清空了，那么应该视为0。动画中应该显示从数值到0或者从0到数值的过渡动画。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zhanjunjie2019** [comment]
<!DOCTYPE html>
<html lang="zh-CN" style="height: 100%">
<head>
    <meta charset="utf-8">
    <title>福布斯富豪排行榜</title>
</head>
<body style="height:100%;margin:0">
<div id="container" style="height:540px;width:960px"></div>

<script type="text/javascript" src="https://fastly.jsdelivr.net/npm/jquery"></script>
<script type="text/javascript" src="https://fastly.jsdelivr.net/npm/echarts@5.4.1/dist/echarts.min.js"></script>

<script type="text/javascript">
    var dom = document.getElementById('container');
    var myChart = echarts.init(dom, 'dark', {
        renderer: 'canvas',
        useDirtyRect: false
    });
    var option;

    const updateFrequency = '5000';
    const dimension = 0;
    const countryColors = [
        '#00008b',
        '#600707',
        '#ffde00',
        '#002a8f',
        '#008011',
        '#ed2939',
        '#929700',
        '#f93',
        '#bc002d',
        '#024fa2',
        '#75007d',
        '#b72bef',
        '#077d64',
        '#b65e1d',
        '#0a90e3',
        '#00247d',
        '#b22234',
        '#5470c6'
    ];
	
	// 这里是数据
	data = [["value","name","year"],["622.2","马化腾-腾讯","2013"],["433.l","马云-阿里巴巴","2013"],["414.8","何享健-美的集团","2013"],["256.2","丁磊-网易","2013"],["259.3","王文银-正威国际","2013"],["549","魏建军-长城汽车","2013"],["439.2","杨惠妍-碧桂园","2013"],["329.4","许家印-恒大集团","2013"],["860.1","王健林-大连万达集团","2013"],["250.1","吴亚军家族-龙湖集团","2013"],["335.5","许荣茂-世茂集团","2013"],["372.1","刘永行-东方希望","2013"],["677.1","李彦宏-百度","2013"],["683.2","宗庆后-娃哈哈集团","2013"],["262.3","龚虹嘉夫妇-海康威视","2013"],["366","陈丽华家族-富华国际","2013"],["664.9","李河君-汉能控股集团","2013"],["305","梁稳根-三一集团","2013"],["292.8","姜滨大妇-歌尔声学","2013"],["268.1","张近东-苏宁云商集团","2013"],["881.3","马化腾-腾讯","2014"],["1193.4","马云-阿里巴巴","2014"],["459","何享健-美的集团","2014"],["299.9","丁磊-网易","2014"],["612","王文银-正威国际","2014"],["367.2","魏建军-长城汽车","2014"],["295.9","杨惠妍-碧桂园","2014"],["361.1","许家印-恒大集团","2014"],["434.5","刘强东-京东","2014"],["556.9","雷军-小米集团","2014"],["807.8","王健林-大连万达集团","2014"],["318.2","张志东-腾讯","2014"],["330.5","许荣茂-世茂集团","2014"],["397.8","刘永行-东方希望","2014"],["89.6","李彦宏-百度","2014"],["673.2","宗庆后-娃哈哈集团","2014"],["330.5","鲁冠球父子-万向集团","2014"],["373.3","陈丽华家族-富华国际","2014"],["795.6","李河君-汉能控股集团","2014"],["391.7","王靖-信威科技","2014"],["1117.6","马化腾-腾讯","2015"],["1384.3","马云-阿里巴巴","2015"],["590.6","何享健-美的集团","2015"],["476.3","丁磊-网易","2015"],["768.4","王文银-正威国际","2015"],["406.4","魏建军-长城汽车","2015"],["552.5","许家印-恒大集团","2015"],["495.3","刘强东-京东","2015"],["838.2","雷军-小米集团","2015"],["1905","王健林-大连万达集团","2015"],["400.1","张志东-腾讯","2015"],["660.4","李彦宏-百度","2015"],["463.6","宗庆后-娃哈哈集团","2015"],["374.7","周群飞-蓝思科技","2015"],["463.6","郭广昌-复星国际","2015"],["444.5","鲁冠球父子-万向集团","2015"],["393.7","陈丽华家族-富华国际","2015"],["381","贾跃亭-乐视","2015"],["1704.3 ","马化腾-腾讯","2016"],["1961.7 ","马云-阿里巴巴","2016"],["1286.9 ","王卫-顺丰控股","2016"],["793.0 ","何享健-美的集团","2016"],["1057.4 ","丁磊-网易","2016"],["960.0 ","王文银-正威国际","2016"],["486.9 ","杨惠妍-碧桂园","2016"],["681.7 ","许家印-恒大集团","2016"],["473.0","刘强东-京东","2016"],["584.3","雷军-小米集团","2016"],["2295.6","王健林-大连万达集团","2016"],["633.0","张志东-腾讯","2016"],["466.1","刘永行-东方希望","2016"],["876.5","李彦宏-百度","2016"],["438.2","许世辉家族-达利食品","2016"],["514.8","宗庆后-娃哈哈集团","2016"],["469.6","周群飞-蓝思科技","2016"],["660.8","姚振华-宝能","2016"],["521.7","喻会蛟-圆通速递","2016"],["459.1","徐传化-传化","2016"],["2581.8","马化腾-腾讯","2017"],["2555.3","马云-阿里巴巴","2017"],["1476.3","王卫-顺丰控股","2017"],["1237.9","何享健-美的集团","2017"],["1118.8","丁磊-网易","2017"],["893.7","王文银-正威国际","2017"],["1092.3","李书福-吉利控股","2017"],["1370.3","杨惠妍-碧桂园","2017"],["2813.5","许家印-恒大集团","2017"],["622.3","刘强东-京东","2017"],["1668.2","王健林-大连万达集团","2017"],["887.1","张志东-腾讯","2017"],["688.5","孙宏斌-融创中国","2017"],["1132","李彦宏-百度","2017"],["628.9","许世辉家族-达利食品","2017"],["602.4","宗庆后-娃哈哈集团","2017"],["701.7","周群飞-蓝思科技","2017"],["681.9","龚虹嘉夫妇-海康威视","2017"],["662","郭广昌-复星国际","2017"],["615.7","潘政民夫妇-瑞声科技","2017"],["2263.2","马化腾-腾讯","2018"],["2387.4","马云-阿里巴巴","2018"],["1028.1","王卫-顺丰控股","2018"],["1345.5","何享健-美的集团","2018"],["931.5","丁磊-网易","2018"],["776.3","黄峥-拼多多","2018"],["772.8","王文银-正威国际","2018"],["979.8","李书福-吉利控股","2018"],["607.2","庞康-海天味业","2018"],["1179.9","杨惠妍-碧桂园","2018"],["717.6","孙飘扬家族-恒瑞医药","2018"],["2125.2","许家印-恒大集团","2018"],["531.3","张勇家族-海底捞","2018"],["821.1","雷军-小米集团","2018"],["1566.3","王健林-大连万达集团","2018"],["769.4","张志东-腾讯","2018"],["1007.4","李彦宏-百度","2018"],["627.9","许世辉家族-达利食品","2018"],["586.5","宗庆后-娃哈哈集团","2018"],["1145.5","张一鸣-字节跳动","2019"],["2545.5","马化腾-腾讯","2019"],["2701.1","马云-阿里巴巴","2019"],["1011.1","王卫-顺丰控股","2019"],["1640.4","何享健-美的集团","2019"],["1216.2","丁磊-网易","2019"],["1499","黄峥-拼多多","2019"],["1173.8","秦英林-牧原股份","2019"],["912.1","李书福-吉利控股","2019"],["890.9","庞康-海天味业","2019"],["1689.9","杨惠妍-碧桂园","2019"],["1824.3","孙飘扬家族-恒瑞医药","2019"],["1958.6","许家印-恒大集团","2019"],["883.9","王健林-大连万达集团","2019"],["862.6","张志东-腾讯","2019"],["827.3","陈建华、范红卫家族-恒力集团","2019"],["820.2","吴亚军家族-龙湖集团","2019"],["728.3","许荣茂-世茂集团","2019"],["714.2","刘永行-东方希望","2019"],["707.1","孙宏斌-融创中国","2019"],["3596.5","钟睒睒-农夫山泉","2020"],["1848.3","张一鸣-字节跳动","2020"],["1341.2","曾毓群-宁德时代","2020"],["3683.2","马化腾-腾讯","2020"],["4377.2","马云-阿里巴巴","2020"],["2148.5","王卫-顺丰控股","2020"],["2148.5","何享健-美的集团","2020"],["1781.6","丁磊-网易","2020"],["2041.8","黄峥-拼多多","2020"],["1474.6","秦英林-牧原股份","2020"],["1301.1","李西廷-迈瑞医疗","2020"],["1661.5","庞康-海天味业","2020"],["1901.7","杨惠妍-碧桂园","2020"],["2335.4","孙飘扬家族-恒瑞医药","2020"],["1367.9","王兴-美团","2020"],["1808.2","许家印-恒大集团","2020"],["1748.2","张勇家族-海底捞","2020"],["1374.5","左晖-贝壳","2020"],["1354.5","刘强东-京东","2020"],["1354.5","雷军-小米集团","2020"],["4244","钟睒睒-农夫山泉","2021"],["3825","张一鸣-字节跳动","2021"],["3272","曾毓群-宁德时代","2021"],["3162","马化腾-腾讯","2021"],["2673","马云-阿里巴巴","2021"],["1855","王卫-顺丰控股","2021"],["2067","何享健-美的集团","2021"],["1932","丁磊-网易","2021"],["2132","黄峥-拼多多","2021"],["1616","秦英林-牧原股份","2021"],["1513","王传福-比亚迪","2021"],["1378","李西廷-迈瑞医疗","2021"],["1443","李书福-吉利控股","2021"],["1996","魏建军-长城汽车","2021"],["1475","黄世霖-宁德时代","2021"],["1539","庞康-海天味业","2021"],["1790","杨惠妍-碧桂园","2021"],["1462","孙飘扬家族-恒瑞医药","2021"],["1410","王兴-美团","2021"],["1372","罗立国家族-合盛硅业","2021"],["4333.8","钟睒睒-农夫山泉","2022"],["3443.4","张一鸣-字节跳动","2022"],["2010.4","曾毓群-宁德时代","2022"],["1627.8","马化腾-腾讯","2022"],["1433.0","马云-阿里巴巴","2022"],["1363.4","王卫-顺丰控股","2022"],["1307.8","何享健-美的集团","2022"],["1300.8","丁磊-网易","2022"],["1293.9","黄峥-拼多多","2022"],["1280.0","秦英林-牧原股份","2022"],["1231.3","王传福-比亚迪","2022"],["1133.9","王文银-正威国际","2022"],["1126.9","李西廷-迈瑞医疗","2022"],["1022.6","李书福-吉利控股","2022"],["1008.7","徐航-迈瑞医疗","2022"],["932.1","魏建军-长城汽车","2022"],["918.2","黄世霖-宁德时代","2022"],["883.5","吕向阳-融捷集团/比亚迪","2022"],["869.5","庞康-海天味业","2022"],["862.6","刘汉元-通威集团","2022"]];
	// 以上是数据
	
	const years = [];
	for (let i = 1; i < data.length; ++i) {
		if (years.length === 0 || years[years.length - 1] !== data[i][2]) {
			years.push(data[i][2]);
		}
	}
	const colorIndexs = {}
	for (let i = 1; i < data.length; ++i) {
		colorIndexs[data[i][1]] = i
	}

	let startYear = years[0];
	option = {
		title: {
			text: '福布斯富豪排行榜',
			subtext: '单位（亿元人民币）',
			left: '50%',
			textAlign: 'center'
		},
		grid: {
			top: 50,
			bottom: 30,
			left: 150,
			right: 50
		},
		xAxis: {
			max: 'dataMax'
		},
		yAxis: {
			type: 'category',
			inverse: true,
			max: 10,
			axisLabel: {
				fontSize: 14,
				rich: {
					flag: {
						fontSize: 25,
						padding: 5
					}
				}
			},
			animationDuration: 300,
			animationDurationUpdate: 300
		},
		series: [
			{
				realtimeSort: true,
				seriesLayoutBy: 'column',
				type: 'bar',
				itemStyle: {
					color: function (param) {
						return getColor(param.value[1]);
					}
				},
				encode: {
					x: dimension,
					y: 3
				},
				label: {
					show: true,
					valueAnimation: true,
				}
			}
		],
		animationDuration: 0,
		animationDurationUpdate: updateFrequency,
		animationEasing: 'linear',
		animationEasingUpdate: 'linear',
		graphic: {
			elements: [
				{
					type: 'text',
					right: 160,
					bottom: 60,
					style: {
						text: startYear,
						font: 'bolder 80px monospace',
						fill: 'rgba(100, 100, 100, 0.25)'
					},
					z: 100
				}
			]
		}
	};
	updateYear(startYear);

	for (let i = 1; i < years.length; ++i) {
		setTimeout(function () {
			updateYear(years[i]);
		}, (i - 1) * updateFrequency);
	}

	function getColor(value) {
		const i = colorIndexs[value] || 0;
		return countryColors[i % countryColors.length]
	}

	function updateYear(year) {
		option.series[0].data = data.slice(1).filter(function (d) {
			return d[2] === year;
		});
		option.graphic.elements[0].style.text = year;
		myChart.setOption(option);
	}
    window.addEventListener('resize', myChart.resize);
</script>
</body>
</html>

**Comment by zhanjunjie2019** [comment]
[bar-race-country.zip](https://github.com/apache/echarts/files/10838782/bar-race-country.zip)

**Comment by helgasoft** [comment]
@zhanjunjie2019, it seems you used the [official example of bar race](https://echarts.apache.org/examples/en/editor.html?c=bar-race-country), tried to adapt it to your data, but it did not quite work out.
Since the official example works well, this is **not a bug** in ECharts.

**Comment by zhanjunjie2019** [comment]
Even if "NaN" and negative numbers are displayed, isn't it a bug?

**Comment by zhanjunjie2019** [comment]
Just because one of your examples works well, you can't assume that there are no bugs. So before any software is released, the unit test will run perfectly. Isn't there any bug?

There are extreme scenarios for this problem: for example, some data in the ranking list spanning many years may be listed again after being dropped, so it is unreasonable to suddenly display "NaN".

Also, there is a negative number in my error data from ignorance to where it comes from. However, there is no negative number in my data. If the value is really calculated as a negative number, then why can the X axis be displayed at the normal scale position.

Obviously, the code and data are in it, which can completely reproduce this problem. Why can't we face up to this problem?

If it is really the problem of data, where is the problem of data?

Sorry, my English is not good. The above content comes from translation software.

————————————————————————————————————————————————

不能因为你们的一个示例运行良好，就认定没有bug。这样任何的软件发布之前，单元测试都会跑的很完美，岂不是都没有bug？
这个问题，存在的极端场景：比如跨多年的排行榜，有些数据在过程中，存在落榜以后再次上榜的情况，这样突然就显示"NaN"是不合理的。
还有就是我的这个错误数据内，存在无知到从何而来的负数，然而我的数据中并没有任何一个负数，如果值真的是计算出负数，那么为什么X轴又能显示在正常的刻度位置。
显然，代码和数据都在里面，完全可以重现出这个问题，为什么不能正视这个问题？
如果真的是数据的问题，数据的问题究竟在哪里？

**Comment by zhanjunjie2019** [comment]
Just because one of your examples works well, you can't assume that there are no bugs. So before any software is released, the unit test will run perfectly. Isn't there any bug?

There are extreme scenarios for this problem: for example, some data in the ranking list spanning many years may be listed again after being dropped, so it is unreasonable to suddenly display "NaN".

There is also a negative number in my error data that I don't know where it comes from. However, there is no negative number in my data. If the value is really calculated as a negative number, then why can the X axis be displayed at the normal scale position.

Obviously, the code and data are here, which can completely reproduce this problem. Why can't we face up to this problem?

If it is really a problem of data, what is the problem of data?

Sorry, my English is not good. The above content comes from translation software.

————————————————————————————————————————————————

不能因为你们的一个示例运行良好，就认定没有bug。这样任何的软件发布之前，单元测试都会跑的很完美，岂不是都没有bug？
这个问题，存在的极端场景：比如跨多年的排行榜，有些数据在过程中，存在落榜以后再次上榜的情况，这样突然就显示"NaN"是不合理的。
还有就是我的这个错误数据内，存在不知到从何而来的负数，然而我的数据中并没有任何一个负数，如果值真的是计算出负数，那么为什么X轴又能显示在正常的刻度位置。
显然，代码和数据都在这里，完全可以重现出这个问题，为什么不能正视这个问题？
如果真的是数据的问题，那么数据的问题究竟在哪里？
