### ISSUE TITLE
[Bug] 关于堆叠柱状图barMinHeight属性问题

### ISSUE THREAD

**Issue by ChadStone** [apache/echarts#18315]
### Version

5.3.0+

### Steps to Reproduce

1、使用的官网demo为：https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar&version=5.3.0；
2、然后在series中type为bar的数据项中添加barMinHeight属性；

### Current Behavior

barMinHeight属性在V5.3.0及以上版本中的堆叠柱状图中无法正常使用，但在V5.2.2及以下版本可正常使用

### Expected Behavior

期望堆叠柱状图中的barMinHeight属性在V5.3.0及以上版本可正常使用

### Environment

```markdown
- OS: macOS Ventura 13.0.1
- Browser: Safari 版本16.1 (18614.2.9.1.12)
- Framework:
```

**Comment by Ovilia** [comment]
Duplicate of #16565. There's already a pr #16572 but the author doesn't seem to respond. I will fix this later.
