### ISSUE TITLE
[Bug] registerTheme don't working

### ISSUE THREAD

**Issue by ZeeLyn** [apache/echarts#18314]
### Version

5.4.1

### Steps to Reproduce

```javascript
import * as echarts from "echarts";
 fetch("chalk.project.json")
            .then((r) => r.json())
            .then((chalkCheme) => {
                echarts.registerTheme("chalk", chalkCheme);
                 echarts.init(document.getElementById("id"), "chalk").setOption({.....});
            });
```

### Current Behavior

From this link[https://echarts.apache.org/zh/theme-builder.html] download the theme file.The theme was registered for the installation of the official tutorial, but it did not take effect

### Expected Behavior

Hope RegisterTheme can take effect

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
download **JS version** from [Theme Builder](https://echarts.apache.org/en/theme-builder.html), not the **JSON version**.
The Help says: _The exported JSON file can be used only in this tool, but not in ECharts directly._

**Comment by plainheart** [comment]
@helgasoft Thanks for your reply. I'd like to make it more clear, instead of the `Export` button, we should click the `Download` button to get the JS / JSON version of the edited theme file. The file downloaded by `Export` is only used in the theme editor.

**Comment by ZeeLyn** [comment]
Thanks, it is really easy to confuse

**Comment by plainheart** [comment]
Hi @lmarquinez, is it possible to provide us a repo for reproduction? It can help find the reason out faster.

**Comment by lmarquinez** [comment]
Actually I can't, as I said before I have an application as a library where I am using the echarts package to create some graphics and there it is working correctly, I have problems in the application when I install this package. Echarts is a peerDependency of this package. Should I add something in the angular.json? For example in the scripts section like:

```
 "scripts": [
      "node_modules/echarts/dist/echarts.js",
      "node_modules/echarts/theme/macarons.js",
 ],
```

In the aplication as library I am only importing the theme in the module this way:

```
import 'echarts/theme/macarons.js';
import * as echarts from 'echarts';

@NgModule({
  imports: [
    NgxEchartsModule.forRoot({
      echarts
    })
  ],
```

And I am using this way to create the graphics:

`<div echarts [options]="echartsOption" theme="macarons"></div>`

**Comment by punkpeye** [comment]
Same issue. So themes are broken in the recent release?

**Comment by punkpeye** [comment]
After lots of attempts...

```
registerTheme('customed', { <-- this name does not matter
  themeName: 'dark', <-- this name matters
  version: 1,
})
```
