### ISSUE TITLE
[Feature] Text ellipsis for text in rectangle

### ISSUE THREAD

**Issue by Gumichocopengin8** [apache/echarts#18317]
### What problem does this feature solve?

<img width="775" alt="image" src="https://user-images.githubusercontent.com/34010665/221513808-2be538ff-c18c-4e65-b040-947a122fd235.png">

[Codesandbox.io](https://codesandbox.io/s/profile-forked-041fw1?file=/index.js)

When rectangle width is not wide enough, text overflows. 
I couldn't find any options or API to make text ellipsis in rectangle with `custom` type.

### What does the proposed API look like?

The API is `ellipsis` which is similar to https://echarts.apache.org/en/option.html#textStyle.ellipsis

**Comment by Ovilia** [comment]
Clipping all the text may cause performance issues and if the shape is not rectangle and the clipping is done using AABB boundary box, the result may not be good. So this feature is not quite considered necessary from my perspective. That being said, if you have this requirement in your case, you can consider using [hideOverlap](https://echarts.apache.org/en/option.html#series-custom.labelLayout.hideOverlap) to make it better looking. See the demo [here](https://codesandbox.io/s/profile-forked-mociko).

**Comment by Gumichocopengin8** [comment]
Thank you for the information and example. It's not the best solution for me, but it's better than displaying everything or none.
