### ISSUE TITLE
[Bug] changing zoom in javascript does not work in graph

### ISSUE THREAD

**Issue by richardehughes** [apache/echarts#18331]
### Version

5.4

### Steps to Reproduce

1. I create the chart exactly as the example on https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap
2. I add the line: myChart.setOption({center:[400,200],zoom:0.4});
3. Zoom does not work (though center does)

### Current Behavior

Setting zoom with javascript on graph does not work.

Easy to see:  look at example: https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap

If you add this line at the bottom: myChart.setOption({center:[400,200],zoom:0.4});

center does work, but zoom does nothing

### Expected Behavior

I expect zoom to work!

### Environment

```markdown
- OS: macOS Monterey
- Browser: chrome
- Framework: angular
```

**Comment by helgasoft** [comment]
not-a-bug
Center and zoom are used **inside** graph series, like ```series: [{...roam: true, center:[400,200], zoom:0.4, ...```

**Comment by richardehughes** [comment]
I need to be able to modify zoom after the initial graph has been displayed.   I can do this with center as the example I posted shows.

Can you tell me how to modify that exmaple so I can get zoom to work?

**Comment by richardehughes** [comment]
Ok I see it now (thanks helgsoft!).

The key is this:  myChart.setOption( {series:[ {center:[40,20],zoom:0.1} ] });
