### ISSUE TITLE
[Bug] 在react中,echarts.on('dbclick')事件中，state的值没有触发改变，一直是原来的，请问大佬们这个是啥原因？

### ISSUE THREAD

**Issue by LBJDJW** [apache/echarts#18342]
### Version

5.0

### Steps to Reproduce

myChart.on('dblclick', params => {
count+=1
setCount(count)
}

### Current Behavior

myChart.on('dblclick', params => {
count+=1
setCount(count)
}

### Expected Behavior

myChart.on('dblclick', params => {
count+=1
setCount(count)
}

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
根据文档，只有 `dblclick` 没有 `dbclick`

**Comment by LBJDJW** [comment]
> `dblclick`
是dblclick 就是我一开始定义的state是0  然后我setstate 永远都是0  无法改变

**Comment by plainheart** [comment]
似乎还真不触发，我稍后看看是什么原因，感谢反馈。

**Comment by LBJDJW** [comment]
> 似乎还真不触发，我稍后看看是什么原因，感谢反馈。

好的 感谢

**Comment by plainheart** [comment]
@LBJDJW 我在[编辑器](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpHjkALYARsD-JhAAXt7Z6XF2JLZ2ANwoKMPkAMLajBxgAHQwABS0AqP-9D30ANYyJ1QAlAgAfPGw9DB4E1SH_sBWGcLlcbrcNDJnut0FtdvsjuEwAB5cBQaAndykSBgfzeTEdKgYMB0EHXCB3DRiWiwADUsD-0EYwyotNkWWpdL-fkCLLpNmCHiW6DsTxQItWQA)又简单试了下好像是可以触发的？如果只是在 React 中不行，能复麻烦给个在线例子我这边试一下？
