### ISSUE TITLE
[Bug] Lines series symbolSize cannot be updated

### ISSUE THREAD

**Issue by TIGeMi** [apache/echarts#18350]
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=lines-ny&code=MYewdgzgLgBAtgQwB4DUEBsCuBTGBeGARgAZiBuAWAChr0BLMbCAEQSgXxgEEAnHhAJ4A6AGY8QcABS9-AyYlQYcASiEBrbAIiTlqxAAdJkgG5Lsy_AD4YAb2owYPbFEw8wt-w5igQPACYQAFwwANqeXqGmWLgAVDAAsmwAFkL8YH4SOgA0MFE4MHGJUClpGVLKALpZ4V4hebEJyakI6ZnKOfUFjcXNreUVNQNUDgC-lFQjyuPUIPpQdOCcdsMwSFxIdEEeKw5QAvrYwQDk9UfVO_AMwcTnEQrBCmjRtzAjLwLrm8HLEXsHx6cXg44FcYDcavd4MgnjgXm8an42AgAFogCTfGp_Q4wI4MCB0PzYM41NYbCAASXS2CQ1yBMA-ZMphJpYLp0AQPCgMOx4Iu2HS3Ie0LMcJeEGwPDoTGCYQuPwiMAJx0IxIuu322KO9EYEFVCpgEAEcAARiB0DKjmBwESckcOeIAO5HKo1ByGk1mgDKdAAXtiAKx0hw-fwMNjYT1aKDYODHYAc6P4loAJj8eoV2oje3Q2Pl-tA6F8xwAxMAACwANmw_rL6f1DoJxWChFdryDMER7GCmZYSLp8JWLom0yoAHpRzAAMJJFoAcyYMGKuEzMAbfmKOQLvhgLT8BqNpvQ3r9q6S_I7IEwxpzAFpgPRgGpqHABNOE0JwJIjn5r_e6I-zhgERMDAYB5k_fQOQQOAIAseUXzfTkhHFKAAHk5gWMBJHlcVJWlUIajzLwlRxFV2yxY4ezrLx3UPC0rUYQC7T4EAnSHfVaK9X1sRIdsQz8MNo0jaAYzjBMmDoFM03bTNPWzXNW2DM0ixxa8EAA9sHDXJsYAAZlbAd9U7BBuwYJhWHYfsXiGN5bEcbB9HQdTsHiCV5wtXCpV1CpXmUagRmoZQgA

### Steps to Reproduce

1. Double clicking on the charts to update the styles of lines

### Current Behavior

The width and color of lines are changed based on the new option, but symbolSize isn't changed

### Expected Behavior

The styles of lines must be corresponding with the new option

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
```

**Comment by Ovilia** [comment]
@cvSoldier Sorry for the late reply. Thanks for your contribution. I will review it now!
