### ISSUE TITLE
[Bug] 饼图，如图所示的一些占比过小的文字重叠问题，请问如何解决？

### ISSUE THREAD

**Issue by zhizaiyunxiao** [apache/echarts#18366]
### Version

5.3.1

### Steps to Reproduce

如何实现文字不重叠？

### Current Behavior

![1678456141963](https://user-images.githubusercontent.com/22257246/224332659-5bde1768-97cc-4df0-8c0f-7bc16e1cba06.png)
 饼图，如图所示的一些占比过小的文字重叠问题，请问如何解决？

### Expected Behavior

如何实现文字不重叠？

### Environment

```markdown
- OS:window
- Browser:Chrome
- Framework:Vue@3
```

**Comment by helgasoft** [comment]
It seems your [labelLine.length2](https://echarts.apache.org/en/option.html#series-pie.labelLine) is zero, or _labelLine.show_ is false.  
Hard to tell, since you did not provide **Minimal Reproduction** code...
