### ISSUE TITLE
树图，请问如何让父节点和子节点对齐展示？

### ISSUE THREAD

**Issue by FrankWasHello** [apache/echarts#18384]
### What problem does this feature solve?

 树图，请问如何让父节点和子节点对齐展示？
![image](https://user-images.githubusercontent.com/34059274/225211156-d038bc0b-cd2e-41d7-8fee-7b4045be3544.png)

### What does the proposed API look like?

 树图，请问如何让父节点和子节点对齐展示？
![image](https://user-images.githubusercontent.com/34059274/225211156-d038bc0b-cd2e-41d7-8fee-7b4045be3544.png)

**Comment by tyn1998** [comment]
The answer below is powered by ChatGPT:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/32434520/225599341-926f27ee-20bb-4bad-819e-a64b464b0879.png">

I cannot make sure that the answer is right 😆  You may have a try.

**Comment by helgasoft** [comment]
Very doubtful OSS-GPT has ever been **trained** on ECharts API documentation. 
Considering the answer they haven't been introduced to each other yet 😆

<details><summary>disclaimer</summary>
opinions expressed in this post are strictly personal, as ECharts user, not a developer
</details>

**Comment by FrankWasHello** [comment]
Ha ha ha, ChatGPT is really powerful, and can give you an answer, even if it doesn't help. 😆
