### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by hh-fay** [apache/echarts#18385]
### What problem does this feature solve?

想要在grid 有四个象限的直角坐标系中，X、Y轴可以自定义交点的位置（或者说原点的坐标）

### What does the proposed API look like?

  yAxis: {
      type: 'value',
      axisLine:{
        show:true,
        onZero:false
      },
      crossoverPoint:12, //  与另一个轴相交的值
    },

**Comment by hh-fay** [comment]
In the rectangular coordinate system with four quadrants in the grid, the X and Y axes can customize the position of the intersection (or the coordinates of the origin)

**Comment by hh-fay** [comment]
yAxis: {
type: 'value',
axisLine:{
show:true,
onZero:false
},
crossoverPoint:12, // Value intersecting another axis
},

**Comment by Char-Ten** [comment]
need!!!
