### ISSUE TITLE
[Bug]  uneven interval on the axis(type is category), will cause some data out of girds

### ISSUE THREAD

**Issue by xiaoheiren04** [apache/echarts#18393]
### Version

5.4.1

### Steps to Reproduce

1. I followed this heatmap example - https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian to create my heatmap
2. backend return part of the data, so some grids should show data, and the others are blank.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/72431167/225648212-08d21fcd-81a5-479c-a38d-294249262ae1.png">

### Current Behavior

Some data are out of grids.

### Expected Behavior

The data should all in grids.

### Environment

```markdown
- OS: Ubuntu20.04
- Browser: Chrome
- Framework: react@16.13.1
```

**Comment by helgasoft** [comment]
so where is the **Minimal Reproduction** code ?

**Comment by xiaoheiren04** [comment]
The categories of y-axis from backend are wrong, the issue has fixed, thanks for your reply.
