### ISSUE TITLE
[Bug]  Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5.  Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### ISSUE THREAD

**Issue by jahnli** [apache/echarts#18396]
### Version

lastet

### Steps to Reproduce

update typescript 5.0.2 

### Current Behavior

Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5.  Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Expected Behavior

fix

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by realmx** [comment]
the same error as you

**Comment by plainheart** [comment]
ECharts uses a fixed typescript version 4.4 rather than 5.0 for development.
