### ISSUE TITLE
[Bug] Cannot render two lines on a chart using datasource

### ISSUE THREAD

**Issue by fandy** [apache/echarts#18394]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/inspiring-ace-jm2zuc?file=/src/App.tsx

### Steps to Reproduce

# Reproduction link: https://codesandbox.io/s/inspiring-ace-jm2zuc?file=/src/App.tsx

This chart is rendering two lines with data from `data.ts`, which contains `historical` data (the line up until the vertical line), and `forecast` data (the line from the vertical line to the end).

The data viz misrepresents the data passed in by rendering two of the _same_ lines overlapped on each other. You can see this by toggling between the two legends.

### Current Behavior

Renders the `historical` (solid line) with data from both the `forecast` _and_ `historical`, and the same line for `forecast`, and both are overlayed on top of each other.

### Expected Behavior

Render the `historical` (solid line) up until the vertical line, and the `forecast` line (dotted line) from the vertical line until the end.

### Environment

```markdown
- OS: Mac
- Browser: Chrome
- Framework: React, also tested with Angular
```

### Any additional comments?

I'm using `name` to distinguish between the data, is this enough? Hoping this is a simple misconfiguration and not a bug!

**Comment by helgasoft** [comment]
not-a-bug
Reorganize the data in datasets for better results - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=MYewdgzgLgBAJgQygmBeGBtAsAKBjAb133zAQFsBTALhgCIALAS2hACcngEAbOgGmIkoTKrToAmAAziAzAFpJ8gIwA2ACpLx1GZOqTJCgCx7J_QfgBuPAK40YSgKwB2AJwAOQQF8BeQuZhkovTMrBxcvD4kMMJBEtLyinKqGloyDiZGJma-ljZ2jk4Okl6RfjkBFHaMLFDsnDzZUTFVUrIKyuqa1Ia6-pn6jSRW3La0jm6SLiWCROWBVSG1YQ2l-M1irQkdKd3pfZLGA6sww6P2DhPi076zUfNii3Xhg2siLfHtSZ1aRRkHWcdTvlnGlrvhbiR7sEak8Vv51vRNp9kl0HHsDP8jv4gWNnE4ZGCyndKg8YcsIvC3hsPokUTITH9DqZAXlcU4nFdfN4Zv4odVQvUKeUEXE2rTOvTJOj-szsazzg5QVzShDSCToQLnscRUjxRp6UpehimS8TvLHIYXE5CaqKrFHuTTTqadslAbpZjZeUcQrJjbeeq6AAzdiULjQJ1UxEur4aYxSRkAuUjYFozn4bk3AOxENsMMICPaqOiraxpTxj0mlkp3Fp_1zQO5_OFymxXWu4w6RNY73mtEOdMwTPg7NVJvhqCRtsxlGdytJ3s1hUD-vEnOhidT95ijvdI0y00-xx15U8hvrvObovTndl4yGec9qJH_uD4dEyGNjcFyfX7el2dqF-fYq2TM5jxXU8s3PMdvxbYVi3bO8gMfL1nz7E8MxVUcxHHH8t2pW8UXRbs0KGPsXEkFRV0_C9m1_Vt_2RTo9lQw8KKomi1Toq9GMIgCWOoQ1SPYpdHEo6ioJHGDcLghiEJvASNHSRwROrcCHAkri7Vgy98L_fjmOU6gExAhd0LEzTOKkj9uN0-iCOjIjBPENj1OBLSbNtPk8PgppEJnQSuzMp9yMszysLPNd7N4hSmL1VS0jUsCPOsyLoOi2S9L8oQAuc4yemSxcNIiodsJk-hfPk_zFKM1SHyKiySrSsqotomL9L4pylNU4DjXMsLmsk9LpMyyq5Mcks6vSNFGsG1LhtajL2qyhyDO6uqVAZEKyNyMSVAfBxtJ8ib1qmhKtqlOa9vAg60WOr9suq3LaouoT909UTbsOh6eM6uLDLe1Sdq-_I7qOrycPGp7JqQlEttM_rQpusGfqggBdABuXAAHocZgAAjawmG4OAYHEeAkALSgoAgXArDYGAgwnVAMHRvgYEWVmsdwRBkAAOnIBAAAcAAoYFFgAPABKNAAD4PyYIMJcl_n5lQdB-SWQU6Fl_xFn54XrAgBhRYwVXmg51WgXR6Xsd8ShuAgSgYH8Zmf0N43TfN_nLZga28lt-3PGl3BcBAYXhHANAPz56moFobBygIOA3kgJhwAgROAHJmmzjns6BbP2ZgCAQGsNhgDsd3oG8V3k9Tqh08znO84LouS7Liuq9oRZPEEdnBGdjhKCzzB_FtOyxAACTJHXjjWABPYWqm4JgwEoU18BNkAAHcAGVF_IAmQG4Wggx4Z2F9L8gQBAKAGFoKA2Fsa_KHIYWGALFhaEnkgQ2AMbMQw8mCjzoP4EaURKbIGdlAAAkmAOAlBJZjDfmAUASDf4QJICg-gzQt4kEXmIIE4DyiQKiGvDe-8oCL24HYP--Bd5MDgA_WgMhr74FANwdgYgADE-gZBBgcMAAhS8V7ANPsw0hUClr-HfKNKBfIABip1sE0PEfQShm9r47wPkfE-Z8maX0oDo_Rp995MAAF52HYdgiAt976P2iC_Ex2D36f2_mPBhTMQCALHnQEBYDsHyJIHHWBCCkG4MkGgjB9DsH4FwXQfBHCYBEPoCQ4J18tHUNoXEshJAmEsKcbY_JnDT48PoLwpwwAXBKAQAgUR0Rl52AwOw8m6NMn1xkQALSFmwAA1gAGXXnkmR-Bsk0LoVg0pQhmkSLXnARpjDmGsJgCUsZJAuEVLoFUmpdSGnxKWhs7gCACaO2mRs7eDA97n2MYckJUQ460DjikiAZjDEYDoGAcA2j6DfI3nQDp-TPBdJIO-Qevhulx26XfcgicJ52OubvW5TtXH5OYWIOAli5DrwgMw7Rai5n0FxfighljYWDN8f0p-Ljr4nygLUOFMBol2OQGwBOzK0FwFoEUa-ksACCksWAROQbQYo5QQl_wxfQLFcgIALMoGwAhuiUVX2wXmHgCJn6v0JRogJCqlXX3JSAcglLgDUucTq_J9LGVir5YK4ViDRXMrkQPUoWy2CJx2QIpRDgADC_BKmaUMCoJwAARQNOy3AOEMDIJwAAhSNvC_XiEtA4JQSa_UuAcEomQGaOZRrDe4SQiaIXjMoAAc0oIgi5JBODgDEMAJglc6GmiYFAd-ABxEWYxxDHB4EwCtYAxB0KDM9ctY6xCmEJB2yWUAclTNsj4sAUAlEUBJmkugABRdBIAkEwH3ggSAMAt2S2FkepBizjghhXQuqo3y2BCyFFEG9UAADqlBB0MA5UUFl5RX0WOsWMQwxwPV8JUJIQobhN4zrvtwYQwta1XJuZatFTQOAVqrZ6-gCAhUQFNLhlgAAFEA68O3Yb_uo-9PzpFguOMLEAeKo7DrwRHU0BMEDmorWwcuiC_XlOw3QNgFaOOi1ctE1ySg-CuT7ZIfm2bpamhNggOAe9-PcME8J0Thg-0wAcCoDmKgDPMv5koRTxxlOqd3gAeSDEGWBAANO1_hLN71s_ZmmABNWgIGXNfys_GkY2GejHBPmwJBbAABKKmmBAPsH-poyD52TNGVAsDlTxAIBkG4HTtGMyEm49K20KrUOhfYBFt9KzillYZSa5z5RR0csNMcDD36xgJc2eAZA69BmnPOaV_wHGuM8esHxgTfCL5BgJszWj74BV4fhcnXVVRknYMIxAXrZzDHeNzELBliqkNjOuRXWg2cAA6YACDT2np4agBByDkE8PnQ5-ByDr2sB20793HvPZmQ8o5UCIDCzXlAAActYY-B37AGbscD9twyN6HaiGRxVwwfOvKRTSq1xyRl3qR2l8blS7NBiWTAQpqyCR_eCXIvgOMABUCL8lUbEKt_Jb2WN0DjgAWXXgQoWiTue4YIQxpjGcOc2pNQQ9bm3-sEH7hKunOM3WCEXg6rxLnwh2G1Whkg0u-vbewXyLnb6CHM_SXkU08v8s4E8JjIAA).

![image](https://user-images.githubusercontent.com/13038071/225770711-8c28392c-de53-4eb7-8064-08967a206bdd.png)
Please refrain from posting code in need of professional debugging.
This board is for well isolated ECharts bugs presented with <ins>**Minimal**</ins> Reproduction code.
A good alternative is [stackoverflow](https://stackoverflow.com/search?q=echarts) where there are a lot more volunteers to help with **any kind** of problem.

<details><summary>disclaimer</summary>
opinions expressed in this post are strictly personal, as ECharts user, not a developer
</details>

**Comment by fandy** [comment]
Thanks @helgasoft , I didn't realize you could separate the dataset like that. I read through the docs on dataset but it wasn't very descriptive, do you mind linking the docs for future reference?
