### ISSUE TITLE
[Feature] emphasis Added detailed iconStyle settings according to mouse motion.

### ISSUE THREAD

**Issue by 4bbada** [apache/echarts#18403]
### What problem does this feature solve?

Is it possible to set the color of mouse hover and click separately in the following options?
If not, I thought

### What does the proposed API look like?

` iconStyle: {  
                   emphasis: {
                                hover:{ borderColor: 'red'}
                                onClick:{borderColor: 'blue'}
                            }
                 },`

**Comment by helgasoft** [comment]
yes, possible - hover=_emphasis_ and click=_select_ 
[Demo code](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwATAAMPLAZmbDJAKy5ABy5AOy5yckVAMzp1qEeFNR0AEaMHLxx6FQAtiDajHiuyBAsPSYU_t5ILZwCEQDCwP6cdBwaMrMc8xyqEAJg2kQAnHYOXWFUU_QsAlLzdEPQrFOdCZfXYG6jvRPkU24tjslisOK1AsoskCInsDkdYMcsvRlqtZKx1lQrGc4nYSLY7ABuFAAemJZGAsHW4TAsEYADMWBxYPR_BB6ABrWAQOmweZDdYCEkAKhQPXICwGHDAADoYAAKWg9YAKcLKsAyOUASgQAD54rAxRL2jKBPgQMx6NosDcoNA5UgmjRaGBgKwXlQTFcqDcZOFIngAJLQeYYAjpOyalARlBC4lAA)

**Comment by 4bbada** [comment]
It does not go back to its original state when clicked again(default off).
At first it was off, but after clicking it changed to 'on' color.
I want to separate 'on&off' color and 'hover' color.

**Comment by 4bbada** [comment]
Thank you so much for your help. Solved.
