### ISSUE TITLE
[Bug] xAxis rich label render problem

### ISSUE THREAD

**Issue by BangKk** [apache/echarts#18401]
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=G4QwTgBApsUHYBcCSBbEBzKEC8EAGAJiAiAFwCWamA9AM7DoDUAHigDYDcARiLVAGwAWADQAFACIBOQVwDqAd3QEUANQCeAYwBMbYFwBWABnIBZAMqD5ScgCE2XFADlgALQDibAK4uAXsZUqAEpuADIAKujkoj6CANKiABKOWi5qNgDMILKBhiDixiZhAFLyUADCSOggbioADi5aABaGomZIzCZwNoLWNlpZKukAiijSrUhW4gCC6IWVc-RICS5sGnCOtVxagpJI-gCinuaVUG4AjLRccCa7KM0ECVP8IWqS6QTpGp4EPiaeXOkinAQj4JiZpsANOkXHBejJZMxPBofLUZB5PCA_OQQAkchpxAB7YAhd7vNQAVnSJgpkJQGmAhQA1uSAPJmaRcdEgNRIRhlcgzJBlKYADgIHkMnIAqowTPpAnAXOQzoYAJqyABmbFqSA1jM8AHZDCKSYFauLmGxROgCeghTNRG4NFVZENdp47ggoCgCATyIZmL0fA8iqAtFLbuS9CgpYskoYNKMwC4zGdMtlcvlTG10C52Jcsw5JN4c3m2Jcymc1AQEVazEU2MoVP8tIFGXs4va7cLu6LUjZ6lnyfwoIFyeTPJ5ybVyCzyQbPKEoCANLPZPxap5ZFxgJ5yI0AI4s2SMxqMMwG4A5kONK6OFAAooIVpFBMoABiSK0zEa4qlBPCIZfgseRwSmUDploIVDDORxxCQI5pgg8DYjaPkBV7TCuyQcRmFhDxGVaEI4GAIork8QQhgQQpIiWQI1HVckfDzSQ1C4MJjBvO9aFVAANQI2FicQhnkEJ9HAsDQLKRQ5VVUTxOQqTGSiG0sJ7bD1J7R1nSyN0EKgEUvCgA1GjKANHB5JQEiKW91gfQFn3rN9P20H8_wJRwwkOSTJJCYU1EcHx0EQiSkNQ3l-UFTSopitSHSdF09P0JBDAaVUEHFd84HJEAzASckQk8XZbGcr8XFpQxdjgejGJ8Tl31Ssx0B8OCphCxS_KmQwxNCiSymU61bQ02Lhri3sRQ0NwGpAMobEI-tHEKNqWXg35fnSRxpLOMT0EEFkwiGVkwlVHl9nkLQxP2DpxFVHwVsZQQQnEbywm0Fapg6CJ0CAqVPH2xkNtetR9qlWhzEsRx9BMDp9FVZgLKmbb9HQQwTB8DRgde7rpj-sJmVa9IVuhnDfsh5q0fx_QhjBspBCOh64LhxwzBsExwa0cEhmYfbVQ5tR5Hk5l9pRyH9jOJB9mhsSkCpG6tE89A1Ce7ykLlJBQWe9q0Y0clzHkZhpdlqV5H2jGcJV3q1DlUH2c5-RWrOalWfBxTwSQAKzHkJHVUENGUrRqVDAlkxBaOqUOZ8Rlga2nbUZ8KUqR8VUg818FbrlRW5Q0Whmbp03UeOwRmY-y6Nv0RlYNBR6bqOLz7fERWVvQdAwnEX6m_JSGpUr_YwbCZbVpojo0nERxyEsN3O6pjnPY6WndaTwwecDGvCnDyGhkJsIba8rXt5nqYLqh-Hkc7_uLueg2FPBMXRe-pPPDgqFCiGK3jr7i3QP38xD7E9OG4CtvA2z1BYtSplPfY6Ax6CA2sJDoPghjYzOjtK2Ph9i-zCCYFuICUFozRoFam0DYEmE7kFYCNhxCFBVlKPaDcNqeyPsbQK6BHYRB5JfHqZwm5F3jjnceMNw6yRXsg5GqD8EIJzhYWhjIl54w5rYEAEsYJPSGPfUGm1BCwTCO7Fam9i7dX0N3NWRdxAaG2m3KBW1g4-DEogwKGh4baIvlKWY_MDFGOSiY7QOETA51mpQ_mNiqaGHsY4pAWgfGP2EhtNBjsqZgzUF1J6WCgJDEftvK2lCl43QSRPaYHN4I9GErjZkFMqTkHkEEuxkd5ZeQ1uo2aJhmbyCDu-P0SACJEV0CAYi5AwCqkWG4Fwmw3DyGKo4NwgR9A6yGF5QZwzOTyAQGsFQtAXAcXIEWTw3p1BcB5IwUQZRJDyD4oEAkg0xqjSudFCaqh9AEFmoOYw45GC1HJFsRYthBDjCsLYckPzejphyHkAo2jBmNDYFkX0BAswLFEPoeQtIVD3PEJ2aKlz0X2hNFoDQ6ERqYpuSEHFeKMWCnEIi3waL8WiiJbiyK41aV8gRZCaEcBrTYGwHgAAUFygktQEDkAJHAHAEAADeXKIAQGYB9cgtBSBiolZKiACA1C1CgPKgA5BoYgUAbRgDUBq4QirJVEBIPKgA2hqkwQrDUQA1WEbZtqNWyCgAQJ1YRGieCde-MA5AnVmGIP6zwcANUAF0jVKogCAZgsqQggC4FANg8rxWRslRoAkbACRgE1QAYn4Pmw1xqlXkEQFAMAoAk0QEMBG1NGos1oAQF6bNEANTBo0AKoVEAAAUFbtkAEoFWpqVWAKACBPBgGFXgAAJKK3tUAAC-oqYDwAQGEDAAAfedeAOBFslfOmtkbfUaEaMm3dSrl2IDXegU9Q7I08A0IydAYACTBoeRmrNyaICUAwOq6AsBECoB_cICA8hyAEAQCeiAZwtDAcaFAcg6BGgIHldBiA86z17rPehyN2G0M1sSTGuVg6lUqrVZqudGrFX7sVXwX1UAiPmqLSm1NpqyAQHNWcck1aIBaHSNxrQ2xgNaDOCKYDaZyRicEAaIT_BDDhrPaR39Gq2AlqgJRnDirQ1cvnRwIAA

### Steps to Reproduce

See the render result. If every label item rendered a svg icon,  click [Run] button，then you can see only the first label item rendered the svg icon.

### Current Behavior

Only first axis label item render the `eventTag` svg，and all the axis label items rendered `eventTag` svg after changed the chart width.

### Expected Behavior

Render svg  image in every label item.

### Environment

```markdown
- OS: macOS Catalina 10.15.6
- Browser: 111.0.5563.64 (Official Build) (x86_64)
```

**Comment by taurz** [comment]
rich label needs an explict width because there's no text defined in `${value}{eventTag|}`，your example would work as below
`rich: {
        eventTag: {
          width: 12,
          backgroundColor: { image: eventImage, width: 12, height: 12 }
        }
      }`

**Comment by BangKk** [comment]
yeah, it works. Thank you!
