### ISSUE TITLE
[Feature] Render in Node.js environment and output SVG files

### ISSUE THREAD

**Issue by guoyunhe** [apache/echarts#18419]
### What problem does this feature solve?

In some research projects, we need to make some charts but we don't want/need to make a website. It would be great if we can generate SVGs directly with echarts + Node.js.

### What does the proposed API look like?

```js
await echarts.renderSVG({ /* option */ }, 'bar-chart.svg');
```

**Comment by devyumao** [comment]
Hi, please checkout the document: https://echarts.apache.org/handbook/en/how-to/cross-platform/server
