### ISSUE TITLE
[Bug] label position in select not work when use dispatchAction

### ISSUE THREAD

**Issue by li942475402** [apache/echarts#18418]
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpP6MAEZU_gTuCeh42sAA7gRgHEoDHiDAeBCQMAS0w8BgYMAAtsFTDnHoVMcg2oybhJNTQ6PjT1Ow65vb0LtGrNowGcPnZLrALlNwv4qPQwBMwegXmN4R9SF8tlBfrJoQAzIEI8Fg0EeYmwWx2ADcKGp4TAcggxyowAUYAAFDjLLDMayAJTxWDHcgAYTuHDAADoBPgQMx6NosFyYKz3p0aLQoTCgQNwpE8ABJaACKgYAiZOJCMCMA1Gk2ibI8VK2dB2HkkOKCkWMMWS6Wy-WK6DKuKq3baCAAnoArVxHUQKLW42mgYWq2GxOiTLJHi5J3g10OWDpHkUoA

### Steps to Reproduce

see the example above

### Current Behavior

not work

### Expected Behavior

work like emphasis

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by imSanko** [comment]
Can you assign this work to  me ?

**Comment by helgasoft** [comment]
not-a-bug
missing _selectedMode:'multiple'_ and _label.show_ - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpP6MAEZU_gTuCeh42sAA7gRgHEoDHiDAeBCQMAS0w8BgYMAAtsFTDnHoVMcg2oybhJNTQ6PjSLCXCTPzREsrsPRgP5OHRWBwqFQrKsEutNttoHQjiAzlNYHZPhcpuF_FR6CwBFIBN5aMcFP5ICAcbxPtjcWAJp90C8xhMPqjSN8FmRllQsoDgRw6ODNNC1hstlAEbIcQAzMAo84YuLo9C2OwAbhQKHCYDkEGOVGACjAAAoZZY8ZKTQBKeKwY7kADCdw4YAAdAJ8CBmPRtFhLTATU9PF1aLS8dSPOFIngAJLQIkYAiZOJCMCMeOJgiibI8VK2dB2a0kEgO52MV0er0-v0B6BBuKdGi0bQQVjaHrt-UDaMQKKZqhJlMeNMZhOD7OZZI8XIFtHFhywdLW9VAA)

**Comment by li942475402** [comment]
> not-a-bug missing _selectedMode:'multiple'_ and _label.show_ - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpP6MAEZU_gTuCeh42sAA7gRgHEoDHiDAeBCQMAS0w8BgYMAAtsFTDnHoVMcg2oybhJNTQ6PjSLCXCTPzREsrsPRgP5OHRWBwqFQrKsEutNttoHQjiAzlNYHZPhcpuF_FR6CwBFIBN5aMcFP5ICAcbxPtjcWAJp90C8xhMPqjSN8FmRllQsoDgRw6ODNNC1hstlAEbIcQAzMAo84YuLo9C2OwAbhQKHCYDkEGOVGACjAAAoZZY8ZKTQBKeKwY7kADCdw4YAAdAJ8CBmPRtFhLTATU9PF1aLS8dSPOFIngAJLQIkYAiZOJCMCMeOJgiibI8VK2dB2a0kEgO52MV0er0-v0B6BBuKdGi0bQQVjaHrt-UDaMQKKZqhJlMeNMZhOD7OZZI8XIFtHFhywdLW9VAA)

get it, thanks!!!!
