### ISSUE TITLE
Dynamic data documentation part is not showing images.

### ISSUE THREAD

**Issue by Harshavardhan-Kanoj** [apache/echarts#18413]
### Version

latest version

### Steps to Reproduce

Go to https://apache.github.io/echarts-handbook/en/how-to/data/dynamic-data/

### Current Behavior

Not showing Images

### Expected Behavior

should show images in documentation

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Please visit https://echarts.apache.org/handbook/en/how-to/data/dynamic-data/
