### ISSUE TITLE
[Feature] SSR PixelRatio support

### ISSUE THREAD

**Issue by huzedong2015** [apache/echarts#18426]
### What problem does this feature solve?

Image blurring under high-resolution display screen

```
canvas.toBuffer('image/jpeg', { quality: 0.5 })
```

### What does the proposed API look like?

null

**Comment by huzedong2015** [comment]
is echarts demo
https://codesandbox.io/s/apache-echarts-canvas-ssr-demo-e340rt?from-embed
code in index.js:36

**Comment by plainheart** [comment]
@huzedong2015 Just set the [`devicePixelRatio`](https://echarts.apache.org/api.html#echarts.init) when initializing the chart.
