### ISSUE TITLE
[Bug] once datazoom has been added to a chart, it cannot be removed

### ISSUE THREAD

**Issue by ReinisV** [apache/echarts#18449]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MpxdiS2dgDcKCj-VGCw9MCWLBwIsOljAO69AsCrAHThYACS0At-_gAUpwCUCAB88TNzRxGwANSIyWPoEABmp7PzTwBSHIIeCIdIXdykUCQGDbIRgRgALWAwAAtktLAIqF9ehpYHFoVBoNtIGBJktIR0qBgwHR1mBtHNpgAvFGo4IeQboOxUfzhSmwQmw0nkxAC9AsGl0iAM2CstEc0hcqHgIlw4TItFLWIecWeLqyPA9LEcRXc9p3DpeOi9PAQLFm2B2Wzckio8gAYW0jA4YF2UwA8qqYKchdALigHDl0jGLiMgA

### Steps to Reproduce

run the demo.

the demo contains code to add/remove datazoom from the chart every two seconds by updating the `option.dataZoom` field and posting the updated `option` object to the chart via `myChart.setOption(option)`.

### Current Behavior

while the title of the chart changes, the dataZoom, after being added for the first time, isn't removed on consecutive actions.

### Expected Behavior

the dataZoom should be removed from the chart when `option.dataZoom` is set to `undefined` and that option is posted to the chart via  `myChart.setOption(option)`.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 111.0.5563.146
- Framework: none
```

### Any additional comments?

none

**Comment by Ovilia** [comment]
The option is merged by default, so if `dataZoom` is undefined in a new `setOption`, it will be merged with the previous option, which contains `dataZoom` so it cannot be removed. The correct way to do this is to call `setOption(option, true)` to force not merging.

**Comment by ReinisV** [comment]
Oh, okay, that makes sense.

I was actually using the Vue wrapper
`https://github.com/ecomfe/vue-echarts`

which takes advantage of Vue's reactivity system, so it requires you to only pass in the options object as a property to the chart component, and then inside of the component, performs the watching for changes on the object and calls the `setOption` [method](https://github.com/ecomfe/vue-echarts/blob/b86280e1f08338eae7b5f717649d3a2ac6da883f/src/ECharts.ts#L178).

from that standpoint it is not as obvious that when changing the options object passed to the component, you are not declaring a state for the chart, but you are creating a merge request.

there is the `update-options` [attribute ](https://github.com/ecomfe/vue-echarts#props) that allows passing that config to avoid merging, but from the [docs](https://echarts.apache.org/en/api.html#echartsInstance.setOption), it seems it comes with its own drawbacks, like loss of internal state (selections, etc) and possibly some performance penalties.

anyway, while the interface of the Vue component is theoretically incorrect, I understand that for it to not be that way would a whole bunch of complexity just for handling a few edge cases.

I'll try using the `replaceMerge` field and see where that gets me.

Thanks!

**Comment by helgasoft** [comment]
dataZoom visibility is controlled by boolean parameter [show](https://echarts.apache.org/en/option.html#dataZoom-slider.show)
