### ISSUE TITLE
[Bug] echarts legend.pageIcons 想换一下icon，提示iconStr.indexOf is not a function

### ISSUE THREAD

**Issue by xiaoqiangz** [apache/echarts#18450]
### Version

5.4.2

### Steps to Reproduce

option = {
  title: {
    text: 'Proportion of Browsers',
    subtext: 'Fake Data',
    top: 10,
    left: 10
  },
  tooltip: {
    trigger: 'item'
  },
  legend: {
    type: 'scroll',
    bottom: 10,
    pageIcons: {
        horizontal: [
          { name: 'prevIcon', icon: 'path://M765.696 512L256 101.248a32 32 0 0 0-45.248 45.248l480.896 480.896a32 32 0 0 0 45.248-45.248z' },
          { name: 'nextIcon', icon: 'path://M256 910.752L765.696 512a32 32 0 0 1-45.248-45.248L229.504 101.248a32 32 0 0 1 45.248-45.248z' }
        ]
    },
    data: (function () {
      var list = [];
      for (var i = 1; i <= 28; i++) {
        list.push(i + 2000 + '');
      }
      return list;
    })()
  },
  visualMap: {
    top: 'middle',
    right: 10,
    color: ['red', 'yellow'],
    calculable: true
  },
  radar: {
    indicator: [
      { text: 'IE8-', max: 400 },
      { text: 'IE9+', max: 400 },
      { text: 'Safari', max: 400 },
      { text: 'Firefox', max: 400 },
      { text: 'Chrome', max: 400 }
    ]
  },
  series: (function () {
    var series = [];
    for (var i = 1; i <= 28; i++) {
      series.push({
        type: 'radar',
        symbol: 'none',
        lineStyle: {
          width: 1
        },
        emphasis: {
          areaStyle: {
            color: 'rgba(0,250,0,0.3)'
          }
        },
        data: [
          {
            value: [
              (40 - i) * 10,
              (38 - i) * 4 + 60,
              i * 5 + 10,
              i * 9,
              (i * i) / 2
            ],
            name: i + 2000 + ''
          }
        ]
      });
    }
    return series;
  })()
};

### Current Behavior

提示iconStr.indexOf is not a function错误。

### Expected Behavior

正常icon替换

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Please follow the [document](https://echarts.apache.org/option.html#legend.pageIcons.horizontal). It should be 

```ts
      horizontal: [
        'path://M765.696 512L256 101.248a32 32 0 0 0-45.248 45.248l480.896 480.896a32 32 0 0 0 45.248-45.248z',
        'path://M256 910.752L765.696 512a32 32 0 0 1-45.248-45.248L229.504 101.248a32 32 0 0 1 45.248-45.248z'
      ]
```

**Comment by xiaoqiangz** [comment]
> 
thanks
