### ISSUE TITLE
[Feature] tree中的连接线，直角拐弯的时候支持borderRadius吗，在拐角处有一点弧度的那种？？？

### ISSUE THREAD

**Issue by dxdleikai** [apache/echarts#18455]
### What problem does this feature solve?

<img width='50%' src="https://storage.jd.com/cjwl/images/Snipaste_2023-03-31_14-40-36.png" />

### What does the proposed API look like?

lineStyle: {radius: number}

**Comment by Ovilia** [comment]
没有 borderRadius 不过可以考虑用 curve 的 https://echarts.apache.org/zh/option.html#series-tree.edgeShape
