### ISSUE TITLE
[Feature] heatmap渲染逻辑的可选

### ISSUE THREAD

**Issue by user-et** [apache/echarts#18454]
### What problem does this feature solve?

https://echarts.apache.org/zh/option.html#series-heatmap.type

目前的热力图渲染和点密度及值大小两者相关联，然后使用累计加和的方式来渲染最终的结果。
1、如果点比较密集，会显著影响这一块的颜色：
![image](https://user-images.githubusercontent.com/129383064/229006670-9075de11-1a55-4b3d-a8e9-3e7e5a413e19.png)

我尝试使用插值的方法来解决这个问题，提前将数据处理成均匀的点
2、但当图表有缩放时，仍会整块渲染成一个颜色：
![image](https://user-images.githubusercontent.com/129383064/229005896-a0ae75e4-3bd3-4a4c-b5d8-3221d89b881c.png)
![image](https://user-images.githubusercontent.com/129383064/229005907-f1d84e25-02b0-419e-ad60-85e4ec8c9ae7.png)

在统计目的为加和时，该方案是有效的。但在其余应用场景中，如大气监测，可能会需要以平均的方式来展现最终的结果。

是否可以增加一个参数，使热力图的渲染可以以自选的方式(如平均)来处理渲染结果

html文件：
[问题.zip](https://github.com/apache/echarts/files/11117634/default.zip)

### What does the proposed API look like?

https://echarts.apache.org/zh/option.html#series-heatmap.type

期望新增一个 series-heatmap.aggregation 的接口，提供加和，平均，最大，最小等常见的聚合方式可选

**Comment by Ovilia** [comment]
技术上似乎不是很好支持，目前是渲染一个高斯模糊的圆形在数据位置，然后根据反复叠加渲染后的不透明度计算累计效果，如果是平均数之类的算法，似乎不太能支持

**Comment by user-et** [comment]
是的，现在是采用反复叠加渲染后的不透明度来实现的，可以考虑把叠加换成其余的算法吗？或者后续可以考虑支持吗？因为现在大部分的库所支持的热力图好像都不具备这个功能

**Comment by Ovilia** [comment]
不太能支持，上面解释过了，这种利用在数据点周围渲染高斯模糊的方式，天然地不太能支持类似平均数的算法

**Comment by user-et** [comment]
好的，谢谢您了

**Comment by user-et** [comment]
您好，感谢您的答复。我再看了下热力图的渲染规则，目前的渲染方法确实没办法支持平均数之类的算法。
![image](https://user-images.githubusercontent.com/129383064/229022760-53b22d7e-9b6d-46fd-8891-2ddefbaa25e3.png)
另外这是我们之前所使用的excel三维地图所实现的效果，他们好像是解决了这个问题的。不知道他们是如何渲染的，希望能有所帮助。
