### ISSUE TITLE
[Bug] Default Candlestick colors is incorrect

### ISSUE THREAD

**Issue by paolobriones** [apache/echarts#18467]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/8637626/229448146-6d0cd647-1475-40e5-a312-491023a6d011.png)

On the Simple Candlestick example, the candles are rendered on the correct values but the default colors are inverted. Please see screenshot

### Current Behavior

The default candlestick colors are inverted

### Expected Behavior

The simple fix is to swap the default colors of color/color0 to make them accurate

### Environment

```markdown
- OS: macOS Ventura
- Browser: Chrome/Firefox/Safari
- Framework:none
```

### Any additional comments?

None

**Comment by Ovilia** [comment]
Please check the document https://echarts.apache.org/en/option.html#series-candlestick
