### ISSUE TITLE
[Feature] K line support no rise no fall no color scene

### ISSUE THREAD

**Issue by Zihao-ma** [apache/echarts#18466]
### What problem does this feature solve?

Hope K line can support not rise and not fall when given white

### What does the proposed API look like?

Hope K line can support not rise and not fall when given white

**Comment by Ovilia** [comment]
Is [borderColorDoji](https://echarts.apache.org/en/option.html#series-candlestick.itemStyle.borderColorDoji) what you want?

**Comment by Zihao-ma** [comment]
The color will change to gray when you drag.   


https://user-images.githubusercontent.com/50894935/230524680-f56ada73-7332-43ce-ad4c-79f1537086d8.mp4
