### ISSUE TITLE
[Bug] line chart markPoint not display

### ISSUE THREAD

**Issue by duke-git** [apache/echarts#18468]
In my vue file, create line chart. but display in the echarts demo project. May I miss some markPoint options?

### Version

5.0.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAEwArAAMPLAAjACcmbDJyQAsWWkFAMwVqVnZxQDsZRXp1qEeFNR0_hDQym2keAC2wMBg2kRgHEr96IOMHADWAArAPWBucR545IMARsD-RABEID1HWQD0F4DgFoAXNoDePoDR6igAkNt7ByYQAF7eGbCXG6ABujAOSagHgdV7vfb-ADyADM4eF1jECrQALTZdIAUhsM1I_kYuyoh3iCQ89AOnDoAGIEXDgmT0A5NqQhGARDEkBTOAIxNlavlWrA_IFvHl0g5kNyOLyYhUyhkhSKlERypKuSMZWIajkGkqAirdfU7LYycy4nYSLY7ABuIA

### Steps to Reproduce

1. in vue file, create lint chart. but display in the echarts demo project.
2. chart option:
```js
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [250, 190, 224, 250, 335, 147, 230],
      type: 'line',
      smooth: true,
      markPoint: {
        symbol: "pin", //标注类型
	symbolSize: 50 , //标记大小
	symbolOffset: [0, '-10%'],
        label: {
          color: '#fff'
        },
        data: [{coord: [1, 190], value: 190}, {coord: [3, 250], value: 250}, {coord: [5, 147], value: 147}]
      },

    }
  ]
};
```

### Current Behavior

markPoint not display in the chart

### Expected Behavior

markPoint should display in the chart

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 111.0.5563.146
- Framework: Vue@3
```

**Comment by susiwen8** [comment]
https://echarts.apache.org/en/faq.html#others
Pleas refer this faq

**Comment by duke-git** [comment]
> https://echarts.apache.org/en/faq.html#others Pleas refer this faq

this faq list can't help. The issue of my case is the line chart can display, but the markPoint doesn't display. any insight? thanks.

**Comment by Ovilia** [comment]
Do you mean the markPoint works without vue but doesn't work in vue environment? I think you should first make sure in the vue enironment, ECharts package is imported as `import * as echarts from 'echarts'` rather than partially imported like `import xxx from 'echarts/lib/xxx'`.

**Comment by plainheart** [comment]
If you are using [on-demand import](https://echarts.apache.org/handbook/en/basics/import/#shrinking-bundle-size), please don't forget to import and register the components that you need. This might be an issue that needs to reproduce in a bundler environment. If not, please show us your code, and don't let us guess what it is.
```ts
import * as echarts from 'echarts/core';

import {
  MarkPointComponent
} from 'echarts/components';

echarts.use(MarkPointComponent);
```

**Comment by duke-git** [comment]
> ```ts
> import * as echarts from 'echarts/core';
> ```

Yes, This helps to solve my issue. I didn't import MarkPointComponent. Thanks

**Comment by duke-git** [comment]
> ```ts
> MarkPointComponent
> ```

Thanks, after import MarkPointComponent, it works.
