### ISSUE TITLE
[Bug] tooltip.trigger='axis'时，emphasis的focus失效，并且将会blur所有元素

### ISSUE THREAD

**Issue by xdbobname** [apache/echarts#18475]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-background&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG78ZEasrFQcdIy4eMHoDiR4SRBUhLCise4esFQAtiDajHiuxKWkAGbA9AoFtDn-jRmlWQ1CYCKFAIwATAAMPLATk7DDAKyzAByzAOyzw8MbAMzj1qEeFNR0AEaMHLyx6HjawADuAEKM9ADWrBzAlgJEYBxKB6Qzq93p9oAITBR_N4Sg16BFOHQOKwzgAKYYrKbojYY2DjAB0owAlD0PHZYmT0LY7ABuFAoHJgOQQcpUT5gFGNSz0SAwFGE-qwcrkADC1Q4YDxAnwIGY9G0WG5UGgKJKR28tG0EFY2n8Wu0YEu6GgwDAD0CyTi_2yuXyAEkwVQMERJiQBox7QJHc6UHZCbSHHNxkG_UA

### Steps to Reproduce

1. 设置tooltip.trigger = 'axis';
2. 设置emphasis.focus = 'self'; // 基本全都可以
3. 然后鼠标移动到元素上方触发

### Current Behavior

元素悬浮时候直接一起blur了

### Expected Behavior

悬浮的元素高亮

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:all
```

### Any additional comments?

states.ts第401行可能有影响

**Comment by susiwen8** [comment]
Confirm, will take a look

**Comment by linghaoSu** [comment]
> Confirm, will take a look

 @susiwen8, @Ovilia  Hi,  I'm trying to fix this issue and when I'm not sure if this is an appropriate way to do it, could you please review this [pr](https://github.com/apache/echarts/pull/18511)?

**Comment by Ovilia** [comment]
@linghaoSu Yes, sure! Thanks for your contribution.
