### ISSUE TITLE
[Bug] How to Hide Tooltip Box but keep the mouseover line visible?

### ISSUE THREAD

**Issue by DMOAbove** [apache/echarts#18477]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/s/ckwl4i?file=/index.js

### Steps to Reproduce

As we can see on codesandbox, the tooltip when show is false doesn't appear, but the axisPoints is hidden too.
Is there any way to hide the tooltip box but still showing the line of the axispointer?

I looked at the HTML code and the tooltip doesn't have any id or class to make it easy to hide it either via css.

### Current Behavior

Not being able to hide tooltip but not axispointer

### Expected Behavior

Being able to see the axis pointer line but not the tooltip box

### Environment

```markdown
- OS:windows 11
- Browser: Chrome last
- Framework: vue@3
```

**Comment by helgasoft** [comment]
use [tooltip.formatter](https://echarts.apache.org/en/option.html#tooltip.formatter) to hide tooltip only.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6MMGAAbSCCKpSZI61ZUHHSMuHi8_LAA9JF42sAA7kQAZoyueFQ8UZEAkkmw2bDaEAJUZC7uECCZEGCwAsBUeNC1sQlk2qUh-AAKwBDNsABGVK5tBLQAFBFJnAC2zCxBsBMAlAgAfMQ-6BxUYAoccLS0ANwRDhFdeL39i14RTpQ0sq79yo7br9BUJhSuz95tuh6G5OHRWBxGNwPkD4sUwNoiAAmGHbCjUOhCWIaWgPWB2c72D7kHD4e4-dHPWgAN1SSlx6Au6HSRkaYgigJ8QjAIlgogAjABWAAMmSRAGZRbAkUiACxi_kADky_PFgpVsoA7GKAGzC6yox4Yl5vBmkAnoWx2E5AA)

**Comment by plainheart** [comment]
Thank you @helgasoft for the reply. I'd like to suggest enabling the axis pointer only on the specific axis if you hope to disable the tooltip. Here is a [demo](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqViNceAArAI0FhyKp76PNuAAdyIwDiU7XwpqOgAbd2UI-zjoKhMKGJpiX1J6YBjOOlYORm5E30CIATBtIgAmMvsozNohfw1aflIAXwayI1ZWKg45YDzIECIAM0YYvCpOrpIeknIcfG9OproANxmlDvRlvyGIKkJYUU6fXyEwEQuARgBWAAYeWFqAZjeP2oAWd61B4ADneD0-TzBfwA7ICAGwvWyddBbWTJZQLEjWFBdADcQA) based on @helgasoft 's code.
