### ISSUE TITLE
[Feature] 请问下，蜡烛图 markPoint 的偏移量之类的，有没有办法根据每条数据动态设置呢

### ISSUE THREAD

**Issue by shiyutim** [apache/echarts#18474]
### What problem does this feature solve?

请问下蜡烛图 markPoint 最大值和最小值，有些时候会超出边框，或者会被遮挡一半，有没有办法动态的设置 偏移量之类的吗，就是拖动的时候动态的算，如果超过一定价格高度，就修改位置。
![markPoint](https://user-images.githubusercontent.com/49300850/229745797-f6428186-8b8a-4392-b8c3-c13c7055a15f.png)

### What does the proposed API look like?

markPoint

**Comment by helgasoft** [comment]
Cannot reproduce. Please include Minimal Reproduction code, like this:
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurACYCGYFRA2gOQBMADAIwDsAtK854wCz0ANLCZsuPPgFZholh269GANlliFkxu3oBdEgF8hJAJ458RJLBLoA9DYC2FDEX7MR12HbwBjCgBsAUyIwACcAVwCDI3Q8AJCIAMJYWg9UUlIwYxAg0V9oMkC8SG8Aa2EPdEpqOgrSWhYRAGZ-ER4mgA4daPS61yapJrdYflYu2vRaRtYOpsaRfn4xnrrG9taB2A3-Rj1lpZ7HEJKABWAIaDALK2XKqhpky3GMrJz6Rwxym9I8Y3sAI2AfgAyhAAF45NxPGK_AF-ADyADMEbFLskhnxmPsvn4KH8An4LAiYGAAOoBCAAcwAFqj6LCyLIiRcQeCiKxlPonoYno8vuhMtkiG9zp8-T9_oCWRDul9xbDEciAqjaEMWFibji8QTkEzSeTqbT6YziVK2RyuTpYJz0tbYHp9ABuIA)
You can always set yAxis upper limit with [yAxis.max](https://echarts.apache.org/en/option.html#yAxis.max).

**Comment by shiyutim** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=candlestick-sh&code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WgPT2YAURXAAFjACWUIgFsALhgQBCIwQBh_4HQIInD0KSJocPcvAHN3RKhtBgkVKBVSBQgEVB8AETyVAAoAbRoYGBq8a1IARjV7VvtrABY8ABoYazUWgDprADZB4bHJ6dsAdlG1abUJ61GATh6AXX76xua2jq7rAFYBobVyec3W5fm-PnGpq4tlvj2Dppb2zu67LczsszqsehNRqChtZNsC1FDhuCttYvg0fsd_jDLoiltZrKszs9NnxVmolvDVhM1KNPvs0Uc_l1rti1qRRgsEWo-BseiSrj0lnxNqs-NSFhNUYdfid7GpWizRaMeisrnxgT18VcFvdhqs7jSUXSpRjrJ0WQslj1WtMrZtRqRNcMJnazgsbdZ7q0zpL0X9TX13cDNo6Nc8vTbWktCTaemyuT6GR1TRcI9ahsrqe0baRqSremSlYbvonuvYJtjlRsJnz8z0lTWNUs3emrey1AnpaWFhXrqNnRHnmc82ptuMQ2pqUKOyb7ID060IesbSMlRG6z0Y9Sc9O_Z0571W3d3fczq9el6lXmeteaTuk51NhXZmeuRsj1rqUP3UtSAs76WWgVakemFK5NiWVoazJNkJjTYZwK2XYjV9e8PXNZ5uVWc4tk5Ug7UjVYFgwot6U7U08RZPFENWVo6wXVZ3nFUk2Sef9yJTK4xiXTjgUwq4LzaUlniItjunLGixQ3aFNlzKS8SFGlQMRNltVE6xu1uJtm2Gdox1uDYcywusqTU_cRg2EZKWBM4lOuIlHTWCEF3_E4WQmOszjk-EXTgicWJfZ0-29ZCSw6AMrhXCx5gWYD5hs8ZOQnSEkOLTsOg4vEFjrPhfMmZY4PUtlcrDFLSIxDpxIi6lYLBCCoI9PsCXua8XPsDT-TZa8jPGWzSDrdSCQMkjjT-DozLyjUaOeGr-I82ykomP8QrSzp5Ro4yoNaNkbNuCFo04tlNglZbys6awWTw0Z6OhPhF3mdyaWHJKYVa9psVsDYCOhKktm085qXOR4IQnV7wrxM5gQtaK2VsOLcwK8Ux1ejLJjtOVoueOTzlIGiDNpVLTsg97Fp6-ZY3tR14PGBGIVIYKCdGh93pvOZoVdS95kiynYPy1rALipsvMjZY_vZyb-MFY6GY6JM1v454PW63oaPuF9exyvnzqw5qsIVza63A0lhpQ2Vugyic6yyrCIQWBzWjtd9EWyzY-cqnTBxrGElkWx5PTth2XZOxn1PezY0agtoXkeWzhnrPn93Uz8ESdB5oRXR3E8hemyuDx9OcxpSU-4vFbBpAqkT4JbpfsHozXmGElTPRFV2hdT8rJ6lYX_WutbTg368F-vOqxodC272V3pXftW-BGF5mFwHoVbNRSpGsLZ2xe2IWV6FWhPJTIJgv7Wg2Gzx7z3f1T-7CocvpU_pXttx6297ei2PM8Scj-T8hJukr65-cs8RrC2J7e2Wd564ibhqOOQd14n3epBe0hdSA209n1JUWM8qTGfhle2Ds4KQXuNsaYkZyQoINoHautcFyb0ClSUho41SkImJDGsW9LzP3ah6WE9o8z20nKQoi99GFRlaM_fcRCDSiMakMSM6osaoL4c_C-eJI4nzJsZRR21PZnCKuIuBNdui92ARCLGMCvrAI2KzPEPRgQn3HsMZmVZHSQQ8nJSCGwcpkxcY4sGkFyTJyQZZORfA6IFTyg4wxPcUa6XtowtGhD9TMNbsZds0SxLvRzIpIRSxHaRknE3LakJ8Y53St0TeCwVLsKyldVxPNaJCLtKw_8ZwJ5NPtMnOmkIOl03rl4gx1c2luw9KfTmnpj5jLTrTKuZT7BtO4ZlGkf9rLHztF1JeMMpZzLaQnGBI4ybA05uqSmENqatPsKo3oEIjqczfNfe4XIyaSwuS_euxFDmPXrrxcu3tZlr3mZ0NQzNvae0PJTOUywm56JpNnAFbTaKTyJJA-0BVumV05g7dJQzOixJ_IXN-YDPye2wvbV5IyGorzivcbxu8VKiy8f8k2CLFkgTLo8RlZNMYFSeMgi5_MbrAw_mHLYhccpbAYmjKhOzuhAK9ldXy3S963CKg5bp2KZUUQYmKXCPJ9Ic1mldUp8LujAtuJOBGwIfbQlqYqg2cLmXdDBrYZqydeVfhtTDZOwZITSpNSHIGfYm4yXtJ7RUJC3j3CZSWNpthQ6xU4o8ym4qBRYU-vy1RIxPxeTfg6bWV1tIW2WBqk1zIaLb05MLDkNFOox0hsbGNsogEjBUl5cgvrbho0LdhIc_4JjtLeDDAqIrF54lHMq_iwES0m37c6hCCMeTc0tsGiCfb5nvSqeyBGh0P4TBYn9RGt010jIesqHxCqyZsl_PdRcfqZ1tWcVHOlEroTdOvWzGC06Sz9reowoqpDeQglIdg1xmwio7BoDsAAlLQAAZnAMAwAoBeHADAYopQoAVHyFUDAKgpBYZUFBmAABvA4YhYDADyEQVImAACeBGFA1B2LQBo5GYAADcVCoDgIkRjzGDiwfkFUTjWAvAKFIFQbwMAAA8MBcP4cqKMVAYRUhQHcJJrwABqTTRHSMNFY1RmjGB6OKYQHACA7gcN4YIzULwOxRjoa8MAIgVQcYwFaFBmopBoMsf05x7jiRRhmYs1ZhT-RbM-YOAAXwOBgIgUA4AYDACRg4BnfBGZM_kIIlH0t0YI0aBo_meMQCCEVxI0XaAxfg4h5DqHKOoGAHAVAVGACyAgqiqFoygBDUBdMHBE3JxITXYC4CY75wTWBhMqFE-JwYynku4FUPkNkZWIBKZU2pjTMmYDzY09pvr-nvCwZgFUMTsnOvdbAL1lLh2GhxYgMNoL5nLN4AALR4Bg6l_T9BkNgB475hoMXDsDYe34cTAOYATZOwNgAVuDmAcPzsqC6yAHrkmYf7Zu7d0HMBNO4E00tgooxVu2ZgK9hHOwajiIh0D_T93HvBcszjpwF3UdXc-4D2L8XEvJfp6gKAlWaAhFqwtrHyGoDKaCHp_TvgAAeUAgh4EAFBygBB6MAODGgAHUwGF95TsGFcwFINFo0UAQBoGQwgKXX2oAYDSKkDgiuVCy68BAbXh3HfO4AAogC8Fd-3WPDtQFo6ERXwAMAgAgC7r7tOotGmU3bsArBLeHcJ0EJogBT0wANKXDwG1jiOeBBvPwG1gV-fmQQcB0aVINvE_-520QPXiutoAFJXd07SO4fXeBm-t4aAAIxAFAE3gR8BehbwVmA_fDAcAAOpeFYGpoI1ovsWekEEa3PHx-T6MHIDAiuCBICQGUBYZRLCt5jwcWXAgncldr4H4P-AcvUboz33IWXX9E8fxl_LX3-8IdUMZgAcRUAt0hy4xiHH3dwgAABkfciApdggwAAAtDgEAIIWDMAogGAc_Q7RzKAGAsAOAkjNDdwVfUA1AGILA8fPwH3RXQnFrH3F_PwR3WgyoFrR3M_I0WjK_Z3JPfTCAerQg9fIgcfXAgQOLFQXgnAkgqQNfDAHjKPI0bA9_RA03YfOoQ7aXAPIPQgvAH3CAOfIgF_BoaAabfXPRcfBoMIGvLaQ3Q7JQhoTQvg6Q2QjfL7BoO_HQiAUoIwIwmAE3EAvAMDMfNwtDfIDAMwnGEIqwxfcgKPA4SUGIG3RIVPL7RwhoMAFQPwHQzPXwjwkPFQBPZTaAJzAAa18JT3fxWy42KwsO8F8D8AAGVA9Jda9DtQBuAghEAd9ajWMTAMBSAgg9BZA-ieiJ82AOAd9OiEADBt8RiQi-9xjjBuABiJBpAwAZiJi-iQj7D9MmCMASivcfd9c0j9Nmte8iBUBJDbsGgJsmDB8_dqskMUNksqgEBptMiDtrjbs4sEsksYA3jcMwcABCXAP7VAVAGAAAfhgDYLU1GDDz_1ePeL8GJ2qKICI003wDwBgEVy0C-P01p2uJ2OT0qBSPxIcPmNuwyKyMVxSHSEyA4zRN8OuLyPwCYNl2ZNuzKzKC8GHzwDpIyGgE5JwNoz8H71QAaK8AAC9CCqc3M_VyS0NRTxSAB5WDWDGIfXGoAAIj0Sb21MGG1Nez1O1L2BgEcChMhMhMpMOzOIuKuMVIQHDx8GeMVz0IMLwBtIJK9OJNuxOOuOpJ0PiAZLK2FJl20MV2oLADDMKzRJ5L5ODKFNGJFLFLQElJlNTy2kGAVPJIgGVLQDVI1Pi1T11NIH1MNONLLNNMGAtKtOtMVIaDtMuNaPJJAHVM1NT0Xm82TO9MVN9IaElBZNN35y8BAP9P01uLyF8F30hwQyeNQyRMBM-MVJ-J53-ORNGEDNx3wGk17wwAAD5sTMTFzMjRhCdRhQA2AYAAAfa8rEjnckwk27J8ivBQ1IkIwMxXXPXIiM_AUoAg8o0kmAerRrZrXwNrKoM4KDWoiAPwU3BfPwuQ4QkI_8ogJo2jFo8ckINwHwWjIIbabYt8jQj8zInQtrN5EI1kvAVCwCt_ECprVrdrLaaCkI2C-C9wFw5C641C9CzCyk7C4AXC_CyEQiuw8fE4z8ovAQfmSi386i2A2iiQ4CrjUCxiqoFoFi64tigfDixC1w7i2A3iwgrCt4wSwPYSs4USgk8SkimkqSstWS-_eSgC2oio-isCogCC64TS7HOCnSzi2oni5o4y_i0yoSg3ESokuIgcmgKLKgIAA



For example, in some cases, markPoint will exceed the border, and you can't normally set yAxis.max because you need to display it dynamically. I want the number to be inside the border in any case. thank you. @helgasoft 
<img width="748" alt="markPoint2" src="https://user-images.githubusercontent.com/49300850/230272330-dedbf14c-b81e-4c2b-a0b1-3ff2273e7be9.png">

**Comment by helgasoft** [comment]
But yAxis adjusts very well dynamically to max values! Both your images just **prove** it. 
I still could not reproduce a "hiding" markPoint with your code. Where is the problem?

**Comment by shiyutim** [comment]
The problem is that you don't want markPoint to display more than the border of the chart. The screenshot above shows 2166 over the right frame; 2445 goes over the top frame. I wonder if there's a way to set it dynamically, so if the maximum value goes beyond 2450, just change its symbolOffset or something. I don't know if I made that clear.  @helgasoft

**Comment by Ovilia** [comment]
No, I don't believe there is a dynamic way to do so.

**Comment by shiyutim** [comment]
如何不用 markPoint，自己根据当前视窗的数据计算最大值最小值的位置呢，每次拖动的时候动态去算位置。请问下有没有方法能获取当前视窗的数据呢?我知道的是根据datazoom 事件获取 start 、end百分比，但是这个反算数据好像不太准确。
How to calculate the position of the maximum and minimum values based on the current window data without markPoint? Dynamically calculate the position every time you drag. Is there a way to get the data of the current window? What I know is that I get the start/end percentage based on the datazoom event, but this inverse data seems to be inaccurate.
 @Ovilia

**Comment by Ovilia** [comment]
@shiyutim Yes, I think it lacks such API to get the range of current viewport.

**Comment by shiyutim** [comment]
@Ovilia  Well, thank you for your answer

**Comment by joket1999** [comment]
The same problem, the setOption method is too inefficient. we need some api or method to change the offset with high performance. Like the video below:

https://github.com/user-attachments/assets/20ee69cf-7dca-47ac-bd9a-b303c66e0903
