### ISSUE TITLE
[Bug] `markPoint` can't show in Safari

### ISSUE THREAD

**Issue by 19115528675** [apache/echarts#18471]
### Version

5.2.2

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/editor.html?code=MYewdgzgLgBKA2IBOEYF4YG0DkBiArACwDsADAMIBs2ANDHgJwCM55x-t9uAot5f9QC6AbgBQIAA5QAluHQwA3qJgwA5kmkATAFyKY8AKYAzKLtJ0ok3U3MwNqgBamYtgEYgolgLa7Kt0GBQAIbSYAAyQa4G8LpQSACuBjAAvjTKMJYg8DISukoqKhAOIADusQkGaQUZ9qoGSLrYQQAe0hC06SotbQAKIKFQ9XkZAJ4SBo1FQZql2ClVBQFGoRM1iemp6YZ1YDqKnTDuniA-MABM5gfSg14AEgbSjs4AzAsq1wZeAOpaUA7WZzeMA-XgA4kFcudLtVBs0oABlKAjQx5A4qDTAf77arVILDIzgBHSABeqyYhAAdKRqTTabTAXAsshGrhngARQhnfAcOgEwJfB5PXSEanzNEFVz4wnwklkhkIZlcYgkBgADnInD5UAFjycwtFyXFhuqxrFKmaAEFWhBdJgDvkcUjxo1gEFBqpkCMOjiYN0IAAVaTAADWwyKpXKiTNOL9ESiMT0CoaXAYACEGNwLRro7jrWEVsN4CtEcjVgpGYhk3g2dwazW5skcwVNG68VhsBcmMROB3SExVT3OwxB6QLiOzkxsIIDptqg6YWNVtgAG5BeCJb048NlGBGNcQSrilvBW29rsj_sX4d0Xtjm8XCdTmfpQQLEZWtqohfO-ir9cGTcVDAIIvAMf0DDhEsUUTJkq1wNMMyzTgJGmTRQlUW1bFsGw6FIQQm1jSJomGJMWQQzNs1nAoIAkIsoHzMAy30YskWg8snSXFsigMTROFIrg61rbgGwI61AxDMNih3Pd4APUS2gYpjt10GS5NNKiDw0AwbSwe1xWA0DGkAWcTADC9QAgPUA5tW1tcUVHLP9El0C5SH4ClnibOcYAc1YJ3wVVVQpVUPIKey10c85nj8fBAuCuyvLCnz8FIQgmApQhYr0bynOIVUGHS01qlfcUOMaItGMswovBADwsTiRIgUKEYvHcBNsGAaQkGAQwKpgCAmpamVSSchqYC8IIkGDPoBi_H04CLENImg1TD1m_RxrqFT9xW2bjzbO1Vrs2ycVAZA9kwJg6AuVUzmICluSKg7qP6rIAHkjCMA9nBwABaJKAFJOG-mwHse-L_0aW78AYAGRp9eAiITct-LmJAeM4VwghDdQQHiXZyFgxo4iCSAUNRwIG1hnEQSgpjkaJknxoMcmMuqPrmqyQmNGJ1RuqOlQqNW-cDpOpAzoZM4uQYW7nhBx62Zat6PoML7sF-0gYZgIG8Mp6osvoBg3MIGG-YKeH4xIgn6DsNG6AxrGkBxvHLewemaMZ5mBYO6nWNp53XdJpmoApk3GvZ1q4mkbnecez2fSF1aRbO15zkIZ4zmeClKFlg75de97PtPNWNa17PVr17BKCpVVjdBtbzZgytGmt3jbcx4NsdxzR8cb-h_fdoOWYKb3SwtnuXaQYm3bJgfY9m3Pw65sAeYAk3Z7nEPGVO21CEuyhCEoW7iFLufnvgRWC_bIvAeBnWCnLphUueaGerhhHR8VFGbcONuO6dse--nsHWuw82IVg_gAwOQDQbz05pHJe0cDprxChvROtp8B0DAPEeA8Bj4-nnufZWhd_rX21hvcuL8cRm2Ig3D-zd0Y_wdp3bu4CJ4M0AYPd4NwabvyrBAj2t9Q4tVgVHFeMcjrTh9LPEBvsx64EIBaVMqoABiSioEwmqtkaQkJyzKV3FtFIM4gTxxgAZJcpkLIjV2jZQWYNwrOVcu5JBoVwbnCYH5AKQUnG2J8pFUg0VPGU2cXYpKKU0oZSCT5HKeUDE-mPiVegGMkA9UST8TQfxrCUBGpaa0ABJXYEEzAjWkTwlk8jFEqPRqdeoqT0kuGCpkTR2jZ6fAkA4IIEBPx6CoYjMBcEynKNUXQXRy0UgxIKJ7YxpjGiACg5QA7rYWKPNZXSNi9ZpwYFycJ3jdC-IfjFLxqziBqlupQTZqzcqUAzo4wJWyYCpwnJSBgYzCojXidgMqAERoQCqjVSM21WanxdB1LqHzxTz0Gj5EaY0JpTUCDNH0XUgzBkWqsZalN4ZIA2no2SfycRWOWQdYx8Lqqi1tBdGAzxCD7wCoQXBW5T4EJVlfOgN8yEJUaAbZ41cKHVG6SUq2qMW7f3to7LuftWFT0gRw4EXCfZ8vHpPAO_CN4wN7ovZe2BV630JcdYlYs6CRQYIaikR8BG9XpfnQhl9iHMtIbXcu0VCDP1NbymhVY6Gt2FUwsVCr-5qK9jKkerrOY-vYUg_5YdhHwNEYgrVKDdW2mTpykgDr8C0vDQrC1jLrUwBZXatl9Azh3WIDXUGLqkbO3dUK9ujC_4sJDZKsNQ8A2gLpuKxVM9TUqvHnA9VmqTbauqKgrAO9bk2FyhSGwdJaRZ07eapWWb1acFzaDe-pAKTMBLY9MtvSm4CvoZ62tvC22-qlcUoNqr61Ktrl2iOIiNUx1jbXIdmB0EmKwTg2dYcGVEMXTatNd983YG5abN-57P6CrttWkVzCj2Xo7RvM95b_7HtDZ-oRqqe0INWgVHEEicRSObTIj-uAziUHIKqC03Z6kaJyJJCMWK1KGL0j6KZ9A5kLJ9Hi_as0InbLOOs_Apz807NSgEo6vHyWHNVMcoTLjOUMAuW5WT4U7nknXU8gocTFyNESck8aNSsRMEyeKbJbQ8maAKS4IphG5UkbIxR7stsqlIAM2YajWRaOKGaV4Vp7TOnlm3cjOz5HKOcGGfoxsOHTTTmSMIIAA)

### Steps to Reproduce

```js
const colors = ['#5470C6', '#91CC75', '#EE6666'];
option = {
  grid: { left: 0, top: 10, right: 0, bottom: 60, containLabel: true },
  tooltip: {
    show: true,
    trigger: 'axis',
    axisPointer: { type: 'shadow' },
    confine: true
  },
  legend: {
    bottom: 20,
    itemHeight: 3,
    itemWidth: 12,
    itemGap: 20,
    textStyle: {
      rich: {
        a: { fontSize: 14.000000000000002, color: '#3D4255', fontWeight: 400 },
        b: { fontSize: 12, color: '#74798C', fontWeight: 400 }
      }
    }
  },
  xAxis: [
    {
      type: 'category',
      axisTick: { show: true },
      axisLabel: { color: '#9B9EAC' },
      axisLine: { lineStyle: { color: '#DEDEDE' } },
      data: ['2017', '2018', '2019', '2020', '2021']
    },
    {
      type: 'value',
      show: false,
      data: ['2017', '2018', '2019', '2020', '2021']
    }
  ],
  yAxis: {
    type: 'value',
    nameTextStyle: { color: '#9B9EAC', padding: [0, 0, 10, 0] },
    axisLabel: { color: '#9B9EAC' },
    splitLine: { lineStyle: { type: 'dashed', color: '#DEDEDE' } },
    axisTick: { show: false },
    axisLine: { show: false }
  },
  series: [
    {
      name: '重庆市',
      data: [
        { value: 20066.3 },
        { value: 21588.8 },
        { value: 23605.8 },
        { value: 25041.4 },
        { value: 27894 }
      ],
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 2,
      markPoint: {
        clickable: false,
        large: false,
        data: [
          {
            coord: [1, 20827.55],
            symbolOffset: ['-50%', -10],
            value: '7.59%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [2, 22597.3],
            symbolOffset: ['-50%', -10],
            value: '9.34%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [3, 24323.6],
            symbolOffset: ['-50%', -10],
            value: '6.08%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [4, 26467.7],
            symbolOffset: ['-50%', -10],
            value: '11.39%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [5, null],
            symbolOffset: ['-50%', -10],
            value: '',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          }
        ]
      },
      itemStyle: { color: '#4AB8FF' },
      tooltip: { show: false }
    },
    {
      name: '重庆市',
      data: [
        { value: 20066.3 },
        { value: 21588.8 },
        { value: 23605.8 },
        { value: 25041.4 },
        { value: 27894 }
      ],
      type: 'bar',
      barWidth: 16,
      xAxisIndex: 0,
      itemStyle: { color: '#4AB8FF', borderWidth: 0 },
      tooltip: {},
      emphasis: { label: { color: '#4AB8FF', show: false } }
    },
    {
      name: '上海市',
      data: [
        { value: 32925 },
        { value: 36011.8 },
        { value: 37987.6 },
        { value: 38963.3 },
        { value: 43214.9 }
      ],
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 2,
      markPoint: {
        clickable: false,
        large: false,
        data: [
          {
            coord: [1, 34468.4],
            symbolOffset: ['-50%', 10],
            value: '9.38%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [2, 36999.7],
            symbolOffset: ['-50%', 10],
            value: '5.49%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [3, 38475.45],
            symbolOffset: ['-50%', 10],
            value: '2.57%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [4, 41089.100000000006],
            symbolOffset: ['-50%', 10],
            value: '10.91%',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          },
          {
            coord: [5, null],
            symbolOffset: ['-50%', 10],
            value: '',
            label: { color: ' red', backgroundColor: 'transparent' },
            itemStyle: { color: 'transparent' },
            symbol: 'triangle'
          }
        ]
      },
      itemStyle: { color: '#26C8A7' },
      tooltip: { show: false }
    },
    {
      name: '上海市',
      data: [
        { value: 32925 },
        { value: 36011.8 },
        { value: 37987.6 },
        { value: 38963.3 },
        { value: 43214.9 }
      ],
      type: 'bar',
      barWidth: 16,
      xAxisIndex: 0,
      itemStyle: { color: '#26C8A7', borderWidth: 0 },
      tooltip: {},
      emphasis: { label: { color: '#26C8A7', show: false } }
    }
  ]
};
```

### Current Behavior

再官网调试，谷歌浏览器正常显示 markPoint ,Safari 设置无效

### Expected Behavior

Safari 正常显示

### Environment

```markdown
- OS:
- Browser: Safari 
- Framework:
```

**Comment by plainheart** [comment]
@susiwen8 Could you help check if this case can reproduce on your side? I have no macOS machine for now.

**Comment by susiwen8** [comment]
@plainheart I can reproduce on Safari

**Comment by susiwen8** [comment]
Looks like a space in `label.color` cause it. 
```diff
+ label: { color: 'red', backgroundColor: 'transparent' },
- label: { color: ' red', backgroundColor: 'transparent' },
```

**Comment by plainheart** [comment]
Nice catch! Thank you @susiwen8. This may be also an issue caused by the irregular color values. Similar to #17823.

**Comment by plainheart** [comment]
@19115528675 Please correct such kind of irregular colors and check it again.
