### ISSUE TITLE
[Feature] Add ability to disable emphasis/highlight functionality of tooltip axis trigger

### ISSUE THREAD

**Issue by juliepagano** [apache/echarts#18495]
### What problem does this feature solve?

It would be really helpful to be able to render the tooltip axis trigger (e.g. a line or a cross) while disabling the highlight/emphasis functionality it triggers on the underlying series. This would probably be a configuration option for `tooltip` or `tooltip.axisPointer`.

I created a very simple example where you can see the behavior based on one of the line chart examples.
https://codesandbox.io/s/line-chart-tooltip-highlight-issue-ob1ob0?file=/index.js

When you have a line chart with multiple series, the axis trigger tends to highlight all the series, which is often unhelpful and can be really confusing to users.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/396962/231222372-17e35a4b-4dc3-40c8-8a30-ce02da15f1f6.png">

If you focus very specifically on a line in this use case, you get a single focus. This behavior is fine.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/396962/231223409-0baa925b-740a-449c-a216-89018f957f66.png">

If you set `tooltip.trigger` to `none`, you get more helpful highlight behavior where nothing is highlighted when you're outside a series, but you lose the visual assistance of the axis pointer tracking line to orient yourself within the chart.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/396962/231223074-1dd1074d-107f-4705-b6cf-a1a1a8072201.png">

A single series is highlighted when you are hovered over it, so that behavior is the same.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/396962/231222781-24c504ae-4b23-496a-99e5-bb5f5e5ce305.png">

I tried a few different combinations of series, tooltip, and axis pointer configuration options to see if I could generate what I wanted with the current functionality, but I could not find a way. It seems like it's currently possible to disable highlight behavior entirely and disable the tooltip axis pointer. I'm hoping for the ability to have **only** series-level highlight functionality while rendering an axis pointer.

### What does the proposed API look like?

This would probably be a configuration option for `tooltip` and/or `tooltip.axisPointer`. I do not have strong feelings about the name of the option to trigger this behavior. I see a `silent` option on some other parts of the API, so maybe having `tooltip.axisPointer.silent: true` could trigger "render but do not highlight" behavior, but I'm not sure if that would break other tooltip functionality (e.g. showing the tooltip on hover). Maybe a more specific `emphasisTrigger` or something like that would be more helpful. I'm open to whatever API approach folks with more experience with the internals of the library feel is best.

It looks like the implementation change would probably go hereabouts in the code. https://github.com/apache/echarts/blob/f5bb3b0c81f9843f73f57a0b01a35488f7795dd6/src/component/axisPointer/axisTrigger.ts#L447-L495

**Comment by juliepagano** [comment]
> You can acheive this by using triggerTooltip: false (and you may want to take a look to into the trigger: "none")
> 
> https://codesandbox.io/s/stacked-area-chart-forked-emk9qt?file=/index.js
> 
> I still do agree we should have at least a "show" or "silent" to make this more dev friendly (I lost some hours to find a solution)

I gave that a try in a modified version of my original example, and I'm still seeing similar behavior. Am I doing something slightly wrong in here?

https://codesandbox.io/s/line-chart-tooltip-highlight-issue-trying-with-triggertooltip-false-56elon?file=/index.js

<img width="573" alt="image" src="https://user-images.githubusercontent.com/396962/231305285-48c4a781-eae3-4745-9349-09ab4cf15abd.png">

Taking a look at the code a little more, it looks like `triggerTooltip` only impacts the rendering of the tooltip itself inside `axisTrigger`, but not the call to the `dispatchHighDownActually` function, which triggers the highlighting. There's a bunch more complexity inside `modelHelper.ts` that uses `triggerTooltip` alongside a bunch of other values that I didn't dig into more deeply, so might be something in there isn't playing nicely?

https://github.com/apache/echarts/blob/f5bb3b0c81f9843f73f57a0b01a35488f7795dd6/src/component/axisPointer/axisTrigger.ts#L345-L347

https://github.com/apache/echarts/blob/f5bb3b0c81f9843f73f57a0b01a35488f7795dd6/src/component/axisPointer/axisTrigger.ts#L206

**Comment by DMOAbove** [comment]
I don't see anything wrong on your last example, I tough you wanted to hide the tooltip but keep the highlight dashed line. But I probably misunderstood what you're trying to achieve.

**Comment by juliepagano** [comment]
> I don't see anything wrong on your last example, I tough you wanted to hide the tooltip but keep the highlight dashed line. But I probably misunderstood what you're trying to achieve.

To clarify what I'm hoping to achieve is:
- Show the axis pointer (i.e. the line that follows the mouse pointer to help orient the user).
- Disable the axis pointer from triggering highlight/emphasis behavior.

I think our team has use cases for showing and not showing the tooltip alongside the above behavior.

> EDIT: If you want to do the inverse, hide the highlight and still see the tooltip, then you need to change the width of the axisPointer: https://codesandbox.io/s/basic-line-chart-forked-lswt8t?file=/index.js

Making the axis pointer 0 width would make the axis pointer functionally invisible, so not quite what we're looking for.

**Comment by juliepagano** [comment]
FYI, I'm going to look into making a pull request for this feature.

**Comment by Ovilia** [comment]
I agree that this should be a useful feature. Glad to see that you made a pull request!
