### ISSUE TITLE
[Bug] setOption更新series[i].markArea，图表不更新

### ISSUE THREAD

**Issue by ZhongMingKun** [apache/echarts#18493]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/s/distribution-of-electricity-forked-5zyztg?file=/index.html

### Steps to Reproduce

1. 初始option.series[i]不带markArea
2. 定时器调用setOption，设置series[i].markArea

### Current Behavior

使用setOption设置series[i].markArea不生效

### Expected Behavior

正常更新markArea设置

### Environment

```markdown
- OS: macOS Monterey
- Browser: Chrome 96.0.4664.55
- Framework: HTML + JS
```

**Comment by helgasoft** [comment]
not-a-bug
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQAiEAzmAE4QBGArpDLMAGawCiuAMZMIQiGACelADRF0dNizBkKsSgDEAhgGscsalrBbKRAL5z0YYMCyQQBVMQzMA5q5yMqW0vVnzYH3oABWAIaBUvQmcrSRB8dSFGYDo6U2czc0sMGywWYFJHALoAC2AAdwImNhxs9B4cIzZGBKcYui0ANxwAQToASQBbLQ9HTIysolIe3zoi5yl4qiEjHFdgRmk62Hy2aAATLU2AcS0HWB4tLDpagIB6O9gQFrBITwBaCFdoDZwAw-MBAA2pQAAygvDg2TqUEARjwsIArNCwQAmPAAZlBKNBGLwABZkTIYYjIdjiWCAGwIokwgDsmPJMIAHATaZRYRCoRTYfCkSjYeisQK8YSBaTuepYdT-TyGcKeayxRTUVymZRUXz2aiherUaLkQBdSboSQzejzYiLBKUTpXGr-ZxBOgAGS0LBwWEtzh4G2Gr08VCQdqwNTMsAA6uliBYAs7QuFIt7iHRoGcqowagFxrBYwpPBAcHNYECAm1nGnBjbBDgRMxxFJHTFrVQsOEcE3nHRBjYwCUMzVtugHk8Xm9GJ9vr8AugAVpgVjQcTUcyl7BUYi16jKVu6WvF8TEZvD-DifjT7AMQBOfer4nXtfntebtc7td04-wVfvi9vs_gw1thzY0zAAbhQIQYAYWBhkYHQehaLQEGiWAJBwQYAGUpFwZNIKwDYqEYVwWC0AAKDdEWJWE6QxKi6TpYlQQAOnxABKaM81gOdgQCUsYhQ_jKxtABZDZoHCVxYGCRodE7GJplmKhQXlbEZ1zIcBPk81iw5NVowmZxAN4tTyxiISqH4bpxOgSTpN0OTnAUi0pRU_SYw00zHO0qhNRpNz0BzdBjSClAwJQG4wAAFQgKtgA4UjSNYhAAD4UOgHBygAeXAKA4EQUybmYItgSQGCjngxCCFgirGlzYLc3A9BBkkABhEojjAJiIuyzhoFI9KspymBWPAix13BUERqAA)
NB: please close issue if problem solved.
