### ISSUE TITLE
[Bug] datazoom配置滚动条如何禁用缩放，只能平移滚动,固定滚动条宽度

### ISSUE THREAD

**Issue by Oracimaru** [apache/echarts#18502]
### Version

5.3.2

### Link to Minimal Reproduction

none

### Steps to Reproduce

 dataZoom: [{
                    type: 'inside',
                    zoomLock: true,
                    xAxisIndex: [0],
                    start: 0,
                    end: 6,
                    maxSpan: 6,
                    mixSpan: 6,
                    handleIcon: 'path://M306.1,413c0,2.2-1.8,4-4,4h-59.8c-2.2,0-4-1.8-4-4V200.8c0-2.2,1.8-4,4-4h59.8c2.2,0,4,1.8,4,4V413z',
                    handleSize: '110%',
                    handleStyle: {color: "#d3dee5"},
                    textStyle: {color: "#0199FF"},
                    borderColor: "#90979c",
                    height: 30,
                    bottom: 10,
                 },
                    {
                        start: 0,
                        end: 20,               
                     }
       ],

### Current Behavior

在5.3.2版本滑块配置zoomLock和maxSpan后依据能被拉伸缩小，比4.x版本更严重，如何设置固定宽度，禁止缩放和拉伸
![image](https://user-images.githubusercontent.com/13652680/231622148-4c8f5c88-9d4f-43e7-9093-ff809f734c91.png)

### Expected Behavior

希望x轴滑块固定宽度，禁止缩放和拉伸

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
not-a-bug
Check syntax - it's _minSpan_, not _mixSpan_. Also there is a second (redundant?) dataZoom in the code.

[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MpxdiRtJEJgjABawMAAtmJx7gkA9Iud3rS9eBACyu2kAF5T0wAywPQA1kRgHEq76NOMGCYgjNBE2U23sNO9Ty9vH3F0HgxhwwERMoDYFRoAIiLkAQlYNoXgJ_FQTBQ0W5YPRgP5OHQAMQCXLbKipWiwByQlgYMAY8hY5A4vEE2SE9LJACcXP0-kp1MRACNONsOABhVkcIlc9Jc-pc-i8SHaKgQVjaMGwfKfEVgMAzIjJdIDIYoOwAbiAA) works as expected.

**Comment by Oracimaru** [comment]
> not-a-bug Check syntax - it's _minSpan_, not _mixSpan_. Also there is a second (redundant?) dataZoom in the code.
> 
> [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MpxdiRtJEJgjABawMAAtmJx7gkA9Iud3rS9eBACyu2kAF5T0wAywPQA1kRgHEq76NOMGCYgjNBE2U23sNO9Ty9vH3F0HgxhwwERMoDYFRoAIiLkAQlYNoXgJ_FQTBQ0W5YPRgP5OHQAMQCXLbKipWiwByQlgYMAY8hY5A4vEE2SE9LJACcXP0-kp1MRACNONsOABhVkcIlc9Jc-pc-i8SHaKgQVjaMGwfKfEVgMAzIjJdIDIYoOwAbiAA) works as expected.

![image](https://user-images.githubusercontent.com/13652680/231633656-1cbc8dbf-b0cb-4923-ba1b-c76c4c92c658.png)
![image](https://user-images.githubusercontent.com/13652680/231633703-941fb0d3-b2e6-4099-ac19-cec6e9177c71.png)
try fix mixSpan to minSpan，and delete second redundant,still can't fixed scroll bar width.

**Comment by helgasoft** [comment]
ok, I see it now. 
The zoom scroll window could be stretched or shortened if mouse is clicked and dragged inside (with cross ✚ pointer).
Does **not** happen when using both side-handles or upper bar (with left-right arrow <-> pointer).
Noticed also that the bug affects the scroll window **visualization** only, the zoom range remains correct.

**Comment by Oracimaru** [comment]
> ok, I see it now. The zoom scroll window could be stretched or shortened if mouse is clicked and dragged inside (with cross ✚ pointer). Does **not** happen when using both side-handles or upper bar (with left-right arrow <-> pointer). Noticed also that the bug affects the scroll window **visualization** only, the zoom range remains correct.

is there any property to avoid this inside dragged,it is so easy to trigger,but I want this fixed-width to slide.

**Comment by helgasoft** [comment]
> is there any property to avoid this inside drag

could not find any.  _shadowOffsetY_ was promising, but it's hard-coded not to go lower than the middle of zoom window.
So the user can still click the bottom of the zoom window and drag/stretch.
```
mhandleWidth = 30; // ....
      moveHandleSize: mhandleWidth,
      moveHandleStyle: {
        color: 'red', // transparent
        shadowColor: 'green', shadowOffsetY: mhandleWidth,
        opacity: 0.5
      },
      handleStyle: { color: 'blue', borderWidth: 22, borderColor: 'blue'},
      handleSize: '120%',
```
As a last resort, ask users to use the (big) handles...

**Comment by Oracimaru** [comment]
> > is there any property to avoid this inside drag
> 
> could not find any. _shadowOffsetY_ was promising, but it's hard-coded not to go lower than the middle of zoom window. So the user can still click the bottom of the zoom window and drag/stretch.
> 
> ```
> mhandleWidth = 30; // ....
>       moveHandleSize: mhandleWidth,
>       moveHandleStyle: {
>         color: 'red', // transparent
>         shadowColor: 'green', shadowOffsetY: mhandleWidth,
>         opacity: 0.5
>       },
>       handleStyle: { color: 'blue', borderWidth: 22, borderColor: 'blue'},
>       handleSize: '120%',
> ```
> 
> As a last resort, ask users to use the (big) handles...

ok，thanks!

**Comment by Airkro** [comment]
https://echarts.apache.org/zh/option.html#dataZoom-slider.zoomLock

**Comment by helgasoft** [comment]
My Demo Code has already ```zoomLock: true```- it does not help or it does not work.

**Comment by Airkro** [comment]
turn off [brushSelect](https://echarts.apache.org/zh/option.html#dataZoom-slider.brushSelect)

**Comment by Oracimaru** [comment]
> turn off [brushSelect](https://echarts.apache.org/zh/option.html#dataZoom-slider.brushSelect)

ok,it works,thx.
