### ISSUE TITLE
[Bug] MarkArea xAxis float value

### ISSUE THREAD

**Issue by inviolablegenesis** [apache/echarts#18507]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=multiple-x-axis&code=MYewdgzgLgBA5gUygEQIYE8IEEBOOMwC8MAZgK5jBQCW4AFNKjlADQwJgAmAlDAN4AoGMNIgcdAG5MYTHIQDaAXRacohMAgDuMNFAQMoTKNwDcMVQB51Wnaj10OPM6oB0EJLv2vEKO_u4A1ACM3NyCIhEwAPRR5lBuSAASIGQ4EHQADGxZMBmmQpHCMTJ4LgAOZBAAFnQa2p50qqEmBYWu7lDJqelBAEzZ2fmFwrLllTV1tvZNQyIAvq0wOEipYCU4LXMtoJCwnBgANtTQRPAeGNh4GLU2DQBEvRm9AMwAtBlvGUF33CwCk_dHi93p8AJw_fICHYnfaGU7yAq9FwANjYAFYXKC2KCXDlesiXAAWNjPDJEklI4kFYrCADsZNpbCCtIxqJgQQAHEj-jBCRyXIz2fyOWwCXiXM8CooWgJitC9nZUPDZbEirF5Dk-soVSJihqmb1tTSYAByV4mthItk64Rmi0wDFYmA203m7G4tguu2WgnE53G72ui1et0wUnk_2qoMUiMuiLG-kCpkslFMrkuHl8pNClwimBiy0SnXSgQ6-XmRW9ZUB0PekP2us1htu-tsRtRwPtkSBx2epvunJx3VRxOC5mstPcthZsfC0UemBIyXFEtQ8AnUAHMQQeEmgDEaMJ9IAwsiG3uAKIX5E3s9ty8XjIZZDIc8vQlo5G08-g0E3tFoiaJYgGUNDgKc4QwJuYgAFxQSAW5pH8whQCACE0GUcGQShODUHAiA4HBJqoAAHscwYRKRxwAAogNQYB6IR_CLCh6BlAgRHADgIAQBAFGRKgYDUAAtnYtBgHBJCoAc7jIZEByoAARggBxYSxIiKagwAANZwNxFCcMeCGwaaB4ZGitLIoB6kLBEtkwHMckHAgiBcGpESwqgcEIoU2GRGAqDCRxpplHRAVBfxhTUDsnHUDgwDOZF8xycIigFI5BR6dQnDuSIqGYTA9IpTAikgFAqHCXBoIZOlckkVgZEQN5ix-ax7GcX4cBiOgSXCKFEDUGBEmmqV5UgMJvUyI1AAq0XablhTSXhYAAOqDVUAAySkqXBUA4GQCDFcIGWFKVBlMOgADiqAFXtB1HVNxxbcpqnMcMMCiTgcD0XBQRZOpwgkGIonlQgTGSLwhAAHz8EsKw4GsAJ-BDLioRtIDANJCCeAAynt9FwHQdwcK8ACqOM_A5NkPVREAbfRwWtSI4AAFpgyAknSbJAMwEcGh4-gzkLcM0FMaLEAaml732XZD3FGUyzldQYOvMtYgIOpnlwfsgvHKwiwnTA2pqhWhgs2hlUwD50RRpBxrCMs0k0EFu37Yd1JRsIjDMHB_0mxEji_U-cn2yVZUVXBpIh1GhsrnJ6ANcczUREzUBscFJpSAcB0mgbUpye4uEIE1Vstep4UZxXQSTWn7WmnzCCTTsGhUAAcmQBwya793qQgwllFUqADSXTNe5jQswHd7vvUDwCVERYDgI3D2Gx5ira4qxWr29_mBRnEB2KkOt8Q9tcZw3k0QMJaFQFU3fT5E1QgJoACSYDTWhBwYZzMkPxEqHoWoAVUeMAn6aB_tzQo29hBaytsbSIn1tK4AQF5HeUU9DCQFhPEBwhRZET3IpZECBaQkBIJNCIIEtKDXQL7CUD1jr0NNqg6270WHvTQew4Q9VGpwXeC4NEjDZY8xTsIyI3Ck65H4YI-Yoj4GFClpEGWDk5JpS2EAA

### Steps to Reproduce

Set the markArea to -0.5 and 0.5 or 0.5 and 1.5. Basically anything +/- .5 to the index. 

```
markArea: {
        itemStyle: {
          color: '#b6e7ff',
          opacity: 0.3,
        },
        data: [
          [
            {
              xAxis: -0.5,
            },
            {
              xAxis: 0.5,
            }
          ],
        ]
      }

```

### Current Behavior

![multiple-x-axis (7)](https://user-images.githubusercontent.com/13307599/231657087-21253c5f-c994-4f13-a2b5-15af7bfdd18a.png)

In this sample, the blue color starts from 3/1/2023 (index 0) to 3/2/2023 (index 1) even when the xAxis markArea has been set to -0.5 and 0.5. 

Currently it's rounded to a whole number so floating values are ignored. 

### Expected Behavior

when setting floating values, it should show something like the yellow background color.
![updated](https://user-images.githubusercontent.com/13307599/231657728-daeb15cb-df33-4cd3-9963-61ec23193ae3.png)

There should be an ability to add background color with floating values. 
This means the background color will be in between the x-axis tick and point. 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
use _markLine_ instead. Also, _data.xAxis_ cannot be fractional because it represents **data indexes** when xAxis is _type='category'_
```
      markLine: {
        symbolSize: [0, 0],
        lineStyle: {
          color: 'red',
          width: 44,
          type: 'solid',
          opacity: 0.3
        },
        data: [{
            xAxis: 2
        }]
      }
```
![image](https://user-images.githubusercontent.com/13038071/231670532-b08e66ec-6711-4563-87fe-087293bded86.png)

**Comment by inviolablegenesis** [comment]
@helgasoft thanks for the advice. i haven't checked `markLine` before so i wasn't familiar with it.
i tried it on my code and it works! thank you so much! 

last question, maybe you know the answer. 
when using the data zoom slider, it seems the width of the background color is small, do you have an advice on how to make this dynamic? 

![multiple-x-axis (9)](https://user-images.githubusercontent.com/13307599/231697602-a3492084-d48f-4fab-bd85-4a8893ebaa20.png)

[latest code and demo](https://echarts.apache.org/examples/en/editor.html?c=multiple-x-axis&code=MYewdgzgLgBA5gUygEQIYE8IEEBOOMwC8MAZgK5jBQCW4AFNKjlADQwJgAmAlDAN4AoGMNIgcdAG5MYTHIQDaAXRacohMAgDuMNFAQMoTKNwDcMVQB51Wnaj10OPM6oB0EJLv2vEKO_u4A1ACM3NyCIhEwAPRR5lBuSAASIGQ4EHQADGxZMBmmQpHCMTJ4LgAOZBAAFnQa2p50qqEmBYWu7lDJqelBAEzZ2fmFwrLllTV1tvZNQyIAvq0wOEipYCU4LXMtoJCwnBgANtTQRPAeGNh4GLU2DQBEvRm9AMwAtBlvGUF33CwCk_dHi93p8AJw_fICHYnfaGU7yAq9FwANjYAFYXKC2KCXDlesiXAAWNjPDJEklI4kFYrCADsZNpbCCtIxqJgQQAHEj-jBCRyXIz2fyOWwCXiXM8CooWgJitC9nZUPDZbEirF5Dk-soVSJihqmb1tTSYAByV4mthItk64Rmi0wDFYmA203m7G4tguu2WgnE53G72ui1et0wUnk_2qoMUiMuiLG-kCpkslFMrkuHl8pNClwimBiy0SnXSgQ6-XmRW9ZUB0PekP2us1htu-tsRtRwPtkSBx2epvunJx3VRxOC5mstPcthZsfC0UemBIyXFEtQ8AnUAHMQQeEmgDEaMJ9IAwsiG3uAKIX5E3s9ty8XjIZZDIc8vQlo5G08-g0E3tFoiaJYgGUNDgKc4QwJuYgAFxQSAW5pH8whQCACE0GUcGQShODUHAiA4HBJqoAAHscwYRKRxwAAogNQYB6IR_CLCh6BlAgRHADgIAQBAFGRKgYDUAAtnYtBgHBJCoAc7jIZEByoAARggBxYSxIiKagwAANZwNxFCcMeCGwaaB4ZGitLIoB6kLBEtkwHMckHAgiBcGpESwqgcEIoU2GRGAqDCRxpplHRAVBfxhTUDsnHUDgwDOZF8xycIigFI5BR6dQnDuSIqGYTA9IpTAikgFAqHCXBoIZOlckkVgZEQN5ix-ax7GcX4cBiOgSXCKFEDUGBEmmqV5UgMJvUyI1AAq0XablhTSXhYAAOqDVUAAySkqXBUA4GQCDFcIGWFKVBlMOgADiqAFXtB1HVNxxbcpqnMcMMCiTgcD0XBQRZOpwgkGIonlQgTGSLwhAAHz8EsKw4GsAJ-BDLioRtIDANJCCeAAynt9FwHQdwcK8ACqOM_A5NkPVREAbfRwWtSI4AAFpgyAknSbJAMwEcGh4-gzkLcM0FMaLEAaml732XZD3FGUyzldQYOvMtYgIOpnlwfsgvHKwiwnTA2rCJ5LNoZVMA-SITPLNJNBBbt-2HepjDMHB_2FI4v1Pg9o0VXBpLFYbxswOgDXHM1ERM1AbHBSaUgHAdJoG1KcnuLhCBNZbiwtep4VxxAdipDrfEPTH7WmnzCCTRAwloVAVSO_dLtVCAmgAJJgNNaEHBhnMyc7hSoeh1AFUzwjVG3_fc4UhseYq3khxEn3afTGjCxEEDoMJpUHDj1AAF7BfquRL_JDMC0Lb3vfBiFEXuinIggtIkCQk0RCBWmDeg7suGiD0RE0NlBucFkQexvuXAuCFsrvwcgA3m21XrjxEJPTQ09B7DDnpEBAwkyhVFQANLOyCTbHCUs5HKMA7oYNnvArW2cb7XwYfVRqcEqQMOEPnIihcoDFwwLA468CpaRBlnA3OhROGmlbkcEuk1IFESrjXOuZVG6UKdg9VBndu4jwKlJAeZce590YZEVB6CHpYJNgvS2Z9hArzXozHmW8d4IX3kfbyOQMjWJEFXS-9iGGi3vq_YAgT-EwE_sAb-v9_482EEA1QKiwHwLalA6RsDzFeMQRvYxrc0GqObgw_qg1xJEXogNTgCALxcG7mUEJnA9aCWAMfP62RPHxliAUoa3kTRogyAAUgbL0PpLThxLDKn4OCvQirROiLEWpjBKDBUDlM_xplfyghCUDHAINGJET4IpOYydpbwJwXgghEcjFtFIYpchTdqHCNoZYq271iEiGYWcqJ7CYASJNMAKo1ADicGWGsHWvNwBwE-YFauiTRHvSEXZA2xUxH-QhURfOQRZGx3kQzSaOwNBUAAHJkAODJG5D1jn4MIZkiemMr5UPgUDYAlQUXgEhdTTWljPJBzkmlLYQA)

**Comment by inviolablegenesis** [comment]
@helgasoft when you move the slider, the width of the markLine is small. 

initial value of the data zoom slider, width of the markLine looks okay at this point:

![multiple-x-axis (12)](https://user-images.githubusercontent.com/13307599/231945691-a9e678b0-d0be-49ab-b528-ce71395f1756.png)

when "zoomed", width of the markLine seems "narrow". 

![multiple-x-axis (13)](https://user-images.githubusercontent.com/13307599/231945686-a263c725-3d3b-42f9-bd12-70f4e41f496b.png)



also, is there a way for the markLine to not change the color of the lines that pass through it? 
![image](https://user-images.githubusercontent.com/13307599/231945951-ce6cafec-e9b0-40ff-a7ea-ecbf6254f087.png)

sorry i have a lot of questions.

**Comment by helgasoft** [comment]
> width of the markLine seems "narrow"

_markLine.lineStyle.width_ is a constant, you can change it to a bigger value

>  is there a way for the markLine to not change the color of the lines that pass through it

Add ```zlevel: 2``` to the line series to put _markLine_ behind the lines.

**Comment by inviolablegenesis** [comment]
@helgasoft thanks! 

> markLine.lineStyle.width is a constant, you can change it to a bigger value

I guess I can change its value using events triggered by the data zoom slider. 

> Add zlevel: 2 to the line series to put markLine behind the lines.

I just discovered it before reading your reply. Thank you!

**Comment by inviolablegenesis** [comment]
Got it working with `markLine`

```
series: [
    {
      name: 'name1',
      type: 'line',
      connectNulls: true,
      emphasis: {
        scale: true,
        focus: 'none',
      },
      data: data,
      z: 10,
    },
    {
      name: 'name2',
      type: 'line',
      connectNulls: true,
      emphasis: {
        scale: true,
        focus: 'none',
      },
      z: 10,
      data: [
        70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3
        ],
    },
    {
      name: 'saturdays',
      type: 'line',
      smooth: true,
      showInTooltip: false,
      tooltip: {
        show: false,
      },
      data: [],
      markLine: {
        symbolSize: [0, 0],
        lineStyle: {
          color: '#b6e7ff',
          opacity: 0.5,
          width: 60,
          type: 'solid',
        },
        label: {
          show: false,
        },
        emphasis: {
          disabled: true,
        },
        data: [
          {
            xAxis: 4,
            name: 'saturday',
            symbolOffset:[10,10],
          },
        ]
      }
    },
]
```

[latest code and demo](https://echarts.apache.org/examples/en/editor.html?c=multiple-x-axis&code=MYewdgzgLgBA5gUygEQIYE8IEEBOOMwC8MAZgK5jBQCW4AFNKjlADQwJgAmAlDAN4AoGMNIgcdAG5MYTHIQDaAXRacohMAgDuMNFAQMoTKNwDcMVQB51Wnaj10OPM6oB0EJLv2vEKO_u4A1ACM3NyCIhEwAPRR5lBuSAASIGQ4EHQADGxZMBmmQpHCMTJ4LgAOZBAAFnQa2p50qqEmBYWu7lDJqelBAEzZ2fmFwrLllTV1tvZNQyIAvq0wOEipYCU4LXMtoJCwnBgANtTQRPAeGNh4GLU2DQBEvRm9AMwAtBlvGUF33CwCk_dHi93p8AJw_fICHYnfaGU7yAq9FwANjYAFYXKC2KCXDlesiXAAWNjPDJEklI4kFYrCADsZNpbCCtIxqJgQQAHEj-jBCRyXIz2fyOWwCXiXM8CooWgJitC9nZUPDZbEirF5Dk-soVSJihqmb1tTSYAByV4mthItk64Rmi0wDFYmA203m7G4tguu2WgnE53G72ui1et0wUnk_2qoMUiMuiLG-kCpkslFMrkuHl8pNClwimBiy0SnXSgQ6-XmRW9ZUB0PekP2us1htu-tsRtRwPtkSBx2epvunJx3VRxOC5mstPcthZsfC0UemBIyXFEtQ8AnUAHMQQeEmgDEaMJ9IAwsiG3uAKIX5E3s9ty8XjIZZDIc8vQlo5G08-g0E3tFoiaJYgGUNDgKc4QwJuYgAFxQSAW5pH8whQCACE0GUcGQShODUHAiA4HBJqoAAHscwYRKRxwAAogNQYB6IR_CLCh6BlAgRHADgIAQBAFGRKgYDUAAtnYtBgHBJCoAc7jIZEByoAARggBxYSxIiKagwAANZwNxFCcMeCGwaaB4ZGitLIoB6kLBEtkwHMckHAgiBcGpESwqgcEIoU2GRGAqDCRxpplHRAVBfxhTUDsnHUDgwDOZF8xycIigFI5BR6dQnDuSIqGYTA9IpTAikgFAqHCXBoIZOlckkVgZEQN5ix-ax7GcX4cBiOgSXCKFEDUGBEmmqV5UgMJvUyI1AAq0XablhTSXhYAAOqDVUAAySkqXBUA4GQCDFcIGWFKVBlMOgADiqAFXtB1HVNxxbcpqnMcMMCiTgcD0XBQRZOpwgkGIonlQgTGSLwhAAHz8EsKw4GsAJ-BDLioRtIDANJCCeAAynt9FwHQdwcK8ACqOM_A5NkPVREAbfRwWtSI4AAFpgyAknSbJAMwEcGh4-gzkLcM0FMaLEAaml732XZD3FGUyzldQYOvMtYgIOpnlwfsgvHKwiwnTA2rCJ5LNoZVMA-SITPLNJNBBbt-2HepjDMHB_2FI4v1Pg9o0VXBpLFYbxswOgDXHM1ERM1AbHBSaUgHAdJoG1KcnuLhCBNZbLXqeFcd50Ek0x-1pp8wgk07BoVAAHJkAcMmO_d6kIMJZRVKgA1Z0zwgQJjQswHdzvvUDwCVERYDgOXD2Gx5ira4qD0AF7e0HxVM3n4-BQgvRF7HRFlxX4BV1Atf11ng8PS3bcdxHb3DL3WON0Pwwj2PpoTxok0zyIy_sh7kRa2zu9UcyYJxCinLyfks5czznFJKd6Idjpr1zlvIiEA7CpB1nxB6xc44HwehAYSaEoBVCfgQqoIBNAAEkwDTTQgcDCnMZLPwiKhdC1ACrdxgNUShTDuaFG_ibOeltEEiE-tpemGhhYRAgOgYSpUDg42oIvYK-pciiIiGXAW_cuHCFFkRPcilkQIFpCQEgk0IggS0oNdA7sXBogehETQ2USFwWRP_d6uC0EIWyhYhyjjebbVero7hFDNB8JYZEQRIgr7t07tIgBxwlLORygPJ2ATolCMMJHd6d9ckwHqo1OCVJ8nCA3qadBUBMEYD8TIuRCiADyZiOgwXkH9Fgf0NFRICVLKJBtkGFHKSaChRwsG7xLiafBLsiFlVIWkpuhQeHUNofQxhpAuaRJQqsjhCSe5hIidPB6gClAPXEZIxmPNZHyIQkolR3kcgZC6cILRMcdE8z0cZJi-4zHAB-bUmAVjgA2LsQ495MBnGqDme4gJbU44QB8Zwf5AArMKRF9JcD8ZkwJL1dkiCWWQsF_VBriSIvRAanAEAXi4HQso_zOB60EsAVR7T1EwvgohAxv5QT_KBjgEGjEiJ8EUnMZO0sAmxJvl3MF9L0GKRSQSsVPNjlgpCcIQpt9QWlJgEM4AVRqAHE4MsNYOtebgDgNqre_ysXCFVQU8OWdURgrKag00ur9WGo4BWdApqwDmrzlanpNl-lSgEFsIAA)

as for the width when the data zoom slider changes, the markLine.lineStyle.width is computed dynamically using "magic numbers" and using events 

since a workaround is provided, will close this issue now. 

thanks for all the help!
