### ISSUE TITLE
[Bug] title.textStyle.ellipsis config not working

### ISSUE THREAD

**Issue by CWS-CTRL** [apache/echarts#18517]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/cws-ctrl/pen/MWPyZjY

### `title.textStyle.ellipsis` config not working
Read the source code and discover
[![p99qm80.png](https://s1.ax1x.com/2023/04/16/p99qm80.png)](https://imgse.com/i/p99qm80)
Even if you show "ellipsis" set in the echarts configuration,
this operation also causes the final output to have no "ellipsis" attribute,
then you end up with the default value "..."
## Scheme
You can add it to the second parameter of the `createTextStyle` function
`ellipsis: textStyleModel.getShallow.('ellipsis')`
There may be more than one error

### Current Behavior

not working

### Expected Behavior

docs: Ellipsis to be displayed when overflow is set to truncate.

'truncate' Truncate the overflow lines.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Or maybe it's just me

**Comment by Ovilia** [comment]
The demo cannot run. Please consider adding an empty series.

It's nice to hear that you have figured out the solution. Please consider making a pull request!

**Comment by CWS-CTRL** [comment]
> The demo cannot run. Please consider adding an empty series.
> 
> It's nice to hear that you have figured out the solution. Please consider making a pull request!

Sorry, this is an "option", "ellipsis" specifies "%%%"  but gets the default value "..."
![p9PIxII.png](https://s1.ax1x.com/2023/04/18/p9PIxII.png)

**option = {
  title: {
    text: 'Main Title',
    left: 'center',
    top: 'center',
    textStyle: {
      fontSize: 30,
      width: 100,
      overflow: 'truncate',
      ellipsis: '%%%' 
      //not working
      // docs: Ellipsis to be displayed when overflow is set to truncate.
      //       'truncate' Truncate the overflow lines.
    },
  }
};**

**Comment by Ovilia** [comment]
It seems none of the `ellipsis` is working. See also the [demo](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&version=5.4.2&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqViNceADKMARlQA2RVPfQB3CAEwbSIAVgAGOz9gADcqDgAzT2B_OjAOSyYWXn5SL08IEDx8OgBSCty_WETOAFtmFg46DFa29o622jyAXxIe6PIcUuJ7Cmo6WMZPJW70AZI8BIgqQlhRPN8_ITARdYBGSJ5YACYAZijTk4AWY5P9gA5j_bOw5-uAdjuANgjbPPQ4xoskK0GUvRI1hQPQA3EA). I'm fixing this problem.
