### ISSUE TITLE
[Question]  3d地球加载加载失效

### ISSUE THREAD

**Issue by 544447** [apache/echarts#18512]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=globe-layers&gl=1&version=5.4.2

### Steps to Reproduce

把官网案例复制到本地使用没有渲染出地球

### Current Behavior

const echarts = require('echarts')

// 3d 地球
export function earthChart(chartId) {
  const myChart = echarts.init(document.getElementById(chartId))
  window.addEventListener('resize', () => {
    myChart.resize()
  })

  let option = {
    backgroundColor: '#000',
    globe: {
      baseTexture: require('./earth/earth.jpg'),
      heightTexture: require('./earth/bathymetry_bw_composite_4k.jpg'),
      shading: 'lambert',
      environment: require('./earth/starfield.jpg'),
      light: {
        ambient: {
          intensity: 0.1
        },
        main: {
          intensity: 1.5
        }
      },
      layers: [
        {
          type: 'blend',
          blendTo: 'emission',
          texture: require('./earth/night.jpg')
        },
        {
          type: 'overlay',
          texture: require('./earth/clouds.png'),
          shading: 'lambert',
          distance: 5
        }
      ]
    },
    series: []
  }

  myChart.setOption(option)
  myChart.off('click')
  myChart.on('click', (param) => {
  })
}

### Expected Behavior

渲染出地球

### Environment

```markdown
- OS:win
- Browser:chrome 112.0.5615.87
- Framework:Vue@2.5.14
```

**Comment by 544447** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by helgasoft** [comment]
Minimal Reproduction provided is an official example and works fine.

> Framework: Vue@2.5.14

Likely the problem is with Vue or related settings.

**Comment by 544447** [comment]
> Minimal Reproduction provided is an official example and works fine.
> 
> > Framework: Vue@2.5.14
> 
> Likely the problem is with Vue or related settings.

Because I didn't introduce gl，hah
