### ISSUE TITLE
数据相差过大，有负数，折线图需要怎么处理才能美观

### ISSUE THREAD

**Issue by bayueqiankong** [apache/echarts#18521]
### What problem does this feature solve?

![图片](https://user-images.githubusercontent.com/50512206/232394233-d235ec7a-b081-4be8-9b8c-eacdf11f9210.png)
![图片](https://user-images.githubusercontent.com/50512206/232394286-7cea4d82-7176-4c57-b528-7f63636ee2fa.png)
数据相差太大，已知生成图表无法突出特征，需要做成图二所示的效果，x轴下线段，距离x轴太近了（图一所示），在不改变数据的情况下，要怎样做才能做的美观一点？
![图片](https://user-images.githubusercontent.com/50512206/232394752-726de938-17c2-42c6-9eaa-df3a3f5675ec.png)

### What does the proposed API look like?

![图片](https://user-images.githubusercontent.com/50512206/232394233-d235ec7a-b081-4be8-9b8c-eacdf11f9210.png)
![图片](https://user-images.githubusercontent.com/50512206/232394286-7cea4d82-7176-4c57-b528-7f63636ee2fa.png)
数据相差太大，已知生成图表无法突出特征，需要做成图二所示的效果，x轴下线段，距离x轴太近了（图一所示），在不改变数据的情况下，要怎样做才能做的美观一点？
![图片](https://user-images.githubusercontent.com/50512206/232394752-726de938-17c2-42c6-9eaa-df3a3f5675ec.png)

**Comment by Ovilia** [comment]
这个问题本身和 ECharts 无关。如果要做图二的效果，那就是不展示左边很大的数据，这个属于业务层面考虑的问题了。
