### ISSUE TITLE
[Bug] use rich overflow, chart will disappear if i set textStyle.width to 100.

### ISSUE THREAD

**Issue by tinybright** [apache/echarts#18537]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8BvAsAKFh2AiMxgBtIQsAuWFdTKrAZwAtgB3U2MAJwFcBTAGjSupcAHuwCGAYRo0AKsLAssALwC0EaABNhJAIwAGXQG4sfSgOzsIAc0tc2CiGC4BbY_zPYQwGg6jQWAbTd3TCw9V1Ng7DCggQBdE2CsUSEIGgAFYDVHOzIKSJCwAE8QLgV8NVKE_Ox8UQAjLnwWPOrqeiYWdm4Y4IBfHsx-iN6qjBwHfFLcgbH25jIAM1F8Gi4YkZisOtEAYwBrSzZgDg1xAmAc7DYudXDqQ4hb6YjqSYX5Ml1RgSw2KzoPrAvjNzKAWMCXiE6sAwLgXJ91t8sJMbBpmiDaAx5qxOLwMepRGBRAEQdRAKrKgDe5QBF0WS7tUsIAsTWptJB8TQGIWFychOyCjqdUQc1sNAAPrBevyyZLpXUpbLEKI2EdGBwQCKpDRenSzDg5ABlIqTdGQnWMR5gOgsABMENayIqAAkuP9ATbvq1qMAAG62Bb4DokLbXUR7bWRX4QHaW54ekKK5Wq42xnV0Z2WAHW23J6hm9QWlh6d3JpLlSx-MjIrjvMPZra7A5HE7qM7-y4tbM6iDcmwKAFgEA0EgAeiHXCjirANAAdKIQLtU1OLpYh4o6EOu6IbDQh_7LMApyBoJYAPwAfS9p_gNptugA7HpT9osKTqkNsxsTcEXxg3-4P4kLggLhoEBLAfTYSAdmWGsQkeBRiSLMYihKBQQFqNQYNmRox0cdQAFlgE0TpcUQ0FiArJxHnUI1SK2GE4XgjhcEwmoq1At55Fov501AgA2XQAFIWKwBxnAAdXNaNYF42jRKcJ0XRYGSMUjGAFB2CA2B2GiMUcEQDUKSYn1yX8fyRVY_i4GgSU_dtw2gUQnCmbAWNeepGiTYtORAvUIEUZzC2_H45hYJYVjxT9Ek8bxIDUis1G8IjSMSTk2G5WFbAURA6l6ch1F6ISgv_elkOcrAQCA1yQh2YDeTIQJIvcLBbwAViE5KmpawTn0ajA2V6q5RHUCAOGs-qguobqOp1AAObqgv6u0CSJGzszs2sHKchRKRpKr8jA5ZuBYABmXQJsGaaBHW4tNrKpldsuxIvUO5z-POn8FpBUzYFiNBeiAA

### Steps to Reproduce

set textStyle.width to 100

### Current Behavior

chart disappear 

### Expected Behavior

chart dont disappear 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
could not replicate - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmurAM4AWwA7oWAE4CuApgDTHpMAe9AhgMKlSAFS5hCAcgBeAWgjQAJl3wBGAAyqA3OLYkMdCAHMDTOhIhgmAW23tYIYKXNRohANri122B9XiAujokPJwQpAAKwHIWpkS66GAAniBMEthyTDZxsNg8AEZM2ISoWegU1LSMTLboAL62dbWBAPRNAES5PADGANYGdMAMCnw4wHSthK10TPKtgX0Q8kW22EwAZmKwqoHo-gbkG1u2mASb27C5wGCYloSqxDWBK8YKS7plNHrMZy3yPGA8bnEgFVlQBvcoAi6KBXnEgCxNcGQgIoWwtVqrUaWP7Rcawdq5JDvEykAA-sBquVyQLJFPJlMpSB4dH6VAYIEJglINVmtlRdHRVxMEiQ0B4liYNWQ9MZzMJADoapkSBZuABlRIrV5xKgLMDkQgAZn1Z3QaWgTAAEkxDPs9brDbAWsAAG4mVbYcreXJTHjdeW6fSdHWxEoS6jM9UlWDkC17DYAJkO4fQyM18m1WLUtt0yJ4aQM0Cxk0tYE5CfOXV6_UG8mGrpixRLsAg6OMEn2YBApHwLSY_vpYFI0p4IC6kelowMTSY0CajZ4xlITVdBmA0pA0AM4mqcQaJW3ul3JLOowgk424iddEgnWzPobi28PBviWSEhAOTkN9IBW7FnkAFlgIoFRfEcoASJYCzyCsN4tBcVzADc94MJgN4rOsqRrGA0FNLsVreAAbKoACkN7mFYADqWoBnhZykZY5qFoQ1G2BAnQwBInQQHQnRQfcgSfvoTAdrAri2HWug5PkhSBlkqLQGASoQJIKSwOmm6lJQHz0F8dpNKs2afhmdgOE4bHeHIjiKDeujcry0QCrkYpIPINTEZuDybk-yniCAx5WTpnQnvywniAA7AArMRLDeGFRH-LadA8PIEAMEJ7ixVF4gAByxQiWS_P8bhqdJJRCiKEighCfm6A62bMHqdzhu54ZiSVwpebClWGegNXYHVsAEUV-7oH49TECNNQaEAA)
There is another bug however: second image in legend does not display on load, but only after refresh(resize).
![image](https://user-images.githubusercontent.com/13038071/233443905-a4494479-e7b0-4560-9837-afe5cec7b621.png)

**Comment by tinybright** [comment]
![image](https://user-images.githubusercontent.com/8720949/233581328-6b606977-6600-4baf-95ed-ed2a9a608c84.png)

i have tried on edge and chrome.

**Comment by tinybright** [comment]
If you have time

> could not replicate - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmurAM4AWwA7oWAE4CuApgDTHpMAe9AhgMKlSAFS5hCAcgBeAWgjQAJl3wBGAAyqA3OLYkMdCAHMDTOhIhgmAW23tYIYKXNRohANri122B9XiAujokPJwQpAAKwHIWpkS66GAAniBMEthyTDZxsNg8AEZM2ISoWegU1LSMTLboAL62dbWBAPRNAES5PADGANYGdMAMCnw4wHSthK10TPKtgX0Q8kW22EwAZmKwqoHo-gbkG1u2mASb27C5wGCYloSqxDWBK8YKS7plNHrMZy3yPGA8bnEgFVlQBvcoAi6KBXnEgCxNcGQgIoWwtVqrUaWP7Rcawdq5JDvEykAA-sBquVyQLJFPJlMpSB4dH6VAYIEJglINVmtlRdHRVxMEiQ0B4liYNWQ9MZzMJADoapkSBZuABlRIrV5xKgLMDkQgAZn1Z3QaWgTAAEkxDPs9brDbAWsAAG4mVbYcreXJTHjdeW6fSdHWxEoS6jM9UlWDkC17DYAJkO4fQyM18m1WLUtt0yJ4aQM0Cxk0tYE5CfOXV6_UG8mGrpixRLsAg6OMEn2YBApHwLSY_vpYFI0p4IC6kelowMTSY0CajZ4xlITVdBmA0pA0AM4mqcQaJW3ul3JLOowgk424iddEgnWzPobi28PBviWSEhAOTkN9IBW7FnkAFlgIoFRfEcoASJYCzyCsN4tBcVzADc94MJgN4rOsqRrGA0FNLsVreAAbKoACkN7mFYADqWoBnhZykZY5qFoQ1G2BAnQwBInQQHQnRQfcgSfvoTAdrAri2HWug5PkhSBlkqLQGASoQJIKSwOmm6lJQHz0F8dpNKs2afhmdgOE4bHeHIjiKDeujcry0QCrkYpIPINTEZuDybk-yniCAx5WTpnQnvywniAA7AArMRLDeGFRH-LadA8PIEAMEJ7ixVF4gAByxQiWS_P8bhqdJJRCiKEighCfm6A62bMHqdzhu54ZiSVwpebClWGegNXYHVsAEUV-7oH49TECNNQaEAA) There is another bug however: second image in legend does not display on load, but only after refresh(resize). ![image](https://user-images.githubusercontent.com/13038071/233443905-a4494479-e7b0-4560-9837-afe5cec7b621.png)

you should edit content in legend.formatter to make it width then 100.

**Comment by tinybright** [comment]
@helgasoft


the key point is set rich.arrowup.width
 
[https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmurAM4AWwA7oWAE4CuApgDTHpMAe9AhgMKlSAFS5hCAcgBeAWgjQAJl3wBGAAyqA3OLYkMdCAHMDTOhIhgmAW23tYIYKXNRohANri122B9XiAujokPJwQpAAKwHIWpkS66GAAniBMEthyTDZxsNg8AEZM2ISoWegU1LSMTLboAL62dbWBAPRNAES5PADGANYGdMAMCnw4wHSthK10TPKtgX0Q8kW22EwAZmKwqoHo-gbkG1u2mASb27C5wGCYloSqxDWBK8YKS7plNHrMZy3yPGA8bnEgFVlQBvcoAi6KBXnEgCxNcGQgIoWwtVqrUaWP7Rcawdq5JDvEykAA-sBquVyQLJFPJlMpSB4dH6VAYIEJglINVmtlRdHRVxMEkAiEZIaA8SxMGqcSWcAVS2V0hnUZmEgB0NUyJAs3AAyokVq84lQFmByIQ1IcsmloEwABJMQz7QgAZkdZ3Q1VgwAAbiZVthyt5clMeN11bp9J0TbESvTGcz9SVYOQ7XsNgAmc0J2CG-TGwjp11xVo8NIGaBY1ordaczPnLq9fqDeTDP0xYo12AQdHGCT7MAgUj4FpMCP0sCkZU8EBdJPK0YGJpMaBNTs8YykJp-gzAZUgaAGcTu3QNErHo_1M6jCCLjbib10SCdYuhjuLbw8Z-JZISEA5OTP0gFMOFjyAAssAigVF8RygBIlgLPIKzPi0FxXMANxvgwmDPpWN44UhTS7A63gAGyqAApM-5hWAA6kakbEWcVGWLa9obAxtgQJ0MASJ0EB0J0iH3IEAH6EwA6wK4thtroOT5IUUZZKi0BgFqECSCksBqAWpSUB89BfLALSrMWAHaXYDhONx3hyI4ijPro3K8tEEhILkNTIPINQUe6Dzup-GniCAV72YZTSdNe_ISeIADsACsFEsN4sXkf4BZ0Dw8gQAw4nuCliXiAAHClCJZL8_xuIeCklCKYoSKCEIhbonrFswTp3AmvkJtJ1WigFsINWZ6DNdgrWwKRlWniQfj1MQ001BoQA](url)

**Comment by helgasoft** [comment]
ok, I see it now, it throws _TypeError: Cannot read properties of undefined (reading 'length')_
For the developers - I think it is a zrender bug on [this line](https://github.com/ecomfe/zrender/blob/9377dd263037f098cb90eb1bc6692d262ffbe6c0/src/graphic/helper/parseText.ts#L551), _strLines_ is undefined.
Workaround is **not** to use ```overflow:'break'```
