### ISSUE TITLE
[Bug] grid.tooltip.axisPointer.crossStyle只修改了横线的样式 grid.tooltip.axisPointer.crossStyle only modifies the style of the horizontal line

### ISSUE THREAD

**Issue by sirokuma2023** [apache/echarts#18554]
### Version

"echarts": "^5.4.2"

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXLANoBEAxAMyUCcAHACIBCpAugDRqxjA6QhFU6dGDwQA5uICmhWKQCGADwgBnUp2GwlqgArAI0MDMFdNYAJ4gpRUioAW8gCbAA7qVOwAvl08bY4sUcTM15sfmDNLWUVPQMjWSFIkUtrOQw8YBU1PyT0zJUAZQtsVMSk9BcIRzA7IkoAOgBWD01vJLbhDt8uRQBBaKJiMu4Umwx5I3F8c3UPRwn5QdIAWRh1OQAVAFcpddIAdSlHPY27Lb2AMTE9gombreg2HKjVDYgMAGsIzXlsCWh9hAagAZeQAIyk2CIoh2Hi6HC45n6qkGwwsVhsADdfjt3OhPAj0CoZBApCpUR5oPIALapUiAF7dAKXGgH7owB3qbMzKM5GD5HgOcIeXhAdVanIAGwABgApPz0PMwIsSABGCXsWCNABMao1EtVsGoABY1bQ9dQ9RqdawfFbPEA&_source=echarts-doc-preview

### Steps to Reproduce

option = {
  color: ["#3398DB"],
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow"
    }
  },
  grid: {
    tooltip: {
      axisPointer: {
        type: "cross",
        crossStyle: {
          width: 3.5,
          color: "rgba(0, 0, 0, 1)"
        }
      },
      label:{
        show:false
      }
    }
  },
  xAxis: [{
    type: "category",
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    axisTick: {
      alignWithLabel: true
    }
  }],
  yAxis: [{
    type: "value"
  }],
  series: [{
    name: "直接访问",
    type: "bar",
    barWidth: "60%",
    data: [10, 52, 200, 334, 390, 330, 220]
  }]
}

### Current Behavior

crossStyle只修改了横线的样式

### Expected Behavior

能够修改竖线和横线的样式

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/130817571/233859273-960276cb-4c33-486b-9641-d87575a6f2a1.png)

**Comment by helgasoft** [comment]
set ```tooltip: {trigger: "item"```, not "axis".

**Comment by sirokuma2023** [comment]
> set `tooltip: {trigger: "item"`, not "axis".

thanks!!! my friend, you 're life savor !!
