### ISSUE TITLE
[Bug] 当值只有0或1时展示的线位置不对

### ISSUE THREAD

**Issue by News0110** [apache/echarts#18551]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtSgFEAtnQhZKg2JQCq0KHACCrDrulABqEKw4wLABQR4AIhByOAxgbh7UOHRyDAAWsHbQity8ALoCwuiKCiaEsrgAZhQeAMwApG5msAqKOU2UACztFcQARsBgog5UbR2yDDD03Bx0IzhYBGByAK445SJiWGOkprL1mWBbSSeysFp0AG44floAkk4q0vydX3rDpH6aLTXdBgACeIHwHgYlhwimAclBs1GwC2xiyoIA4nQpLB6nQsFocMNzJY6DZKABZGBpSgAFR2NIA6mwabSclsaQAxBQ06iWXmoyhlX5EUEA7TAjDgyGUe74hl7dCEhQ4IGwaydGQ3aB0BwyxzOVzE4hgiFULDFJGyLT0ZhUWnjfFW4gWKzqgCM7gADO5PbAff7fb7hcR9LItbIdXqqN5fNFAs6QdLzZbjUrbUx7Y6jZ0SW7rAGA36i97vSGReHc7AozKwhEojFE1KzR4LTwmzbGJmPA76DmbrBXWSPUHYMXR4Xy7Aw8QI8Qa1QEkkUk3TTK27w07cM1m-02hzZC6Wx8fJ99jXP0Av0plsnkCkV21u1ymn1XO3ae9n96SbH7_8eAH-lOPywGU_AANxAA

### Steps to Reproduce

值是 0 1这两种，然后图表展示时却展示到了2（包括以上）的上面
![image](https://user-images.githubusercontent.com/129836682/233823617-6df6bd84-8bf5-429d-956c-650bd7fe4be9.png)

### Current Behavior

无

### Expected Behavior

无

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by luguokong** [comment]
参考配置文档中stack字段意义

**Comment by plainheart** [comment]
@News0110 如 @luguokong 所说，你已经配置了 `stack: 'Total'`，如果不清楚该配置项的意义，请参考[文档](https://echarts.apache.org/option.html#series-line.stack)或查阅[其他相关 issue](https://github.com/apache/echarts/issues?q=label%3A%22topic%3A+stack%22+is%3Aclosed)。
