### ISSUE TITLE
[new-feature] Overlapped barChart on the same x axis not ordered on their value

### ISSUE THREAD

**Issue by LyesOrd** [apache/echarts#18561]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-label-rotation

### Steps to Reproduce

1. see the example
2. change the value and check if the small value of one serie is behind the big one

### Current Behavior

I create i chart where i want to have the bars of one serie stacked but not one on th others, i just want them align on the same x axis but if i do this (check the example) the bar are not ordering on their value and the smallers ones dissapear behind the big ones. I try to sort my serie but i do not want to 

### Expected Behavior

I want to have the same chart has the example but the bar needs to be ordering depends on their value

### Environment

```markdown
- OS:Ubuntu 22.04
- Browser:Google Chrome
- Framework: Angular + Nodejs
```

**Comment by helgasoft** [comment]
This is by design and not-a-bug. 
You are asking for a new [Feature] to have bars sorted by value inside category groups.

**Comment by LyesOrd** [comment]
You think ? There's no possibilities to bypass this problem by adding the z-index property for a bar ? Like use z and say this z is based on the value of my data ? 

arrData = [10,25,8,12] -> arrIndexData = [1,3,0,2] -> use this array of index for the z property ? 

You're probably right but just to make sure i can't do this for my chart

**Comment by helgasoft** [comment]
I don't see a way to do it currently thru API. Data structure is a matrix and values cannot be rearranged inside. 
An interesting new feature though, and possible to implement in source code.
Problem is that priority for this is fairly low, a handful of people are maintaining this big project **part-time**. 
So DIY is the way to go.

**Comment by LyesOrd** [comment]
Ok thank you for your help i'll pass this issue on feature status
