### ISSUE TITLE
Gauge Chart has bug when using inherit color with progress 

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#18571]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/JjmNMZz

### Steps to Reproduce

use progress with inherit color

### Current Behavior

Value of invisible when using inherit color with progress

### Expected Behavior

To see value with inherit color. Not invisible

**Comment by helgasoft** [comment]
[data.itemStyle.color](https://echarts.apache.org/en/option.html#series-gauge.data.itemStyle.color) is set to _'auto'_, which is an invalid color.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWEAmAuWA5AIwCcRATAGYCG2ARgLQ1FEN3nkCsbHJTADADZsJOgHYS_AMzl-BADTpM1aBAC21SDHxgATgFcApooyxIYADaH8AbSWZk9h2cMAPMPgIA5QwHdYAIKuEADOCk4OVpQehADGhtBghrrhps4hABbAvjoGxhGYYKCe_ACkBBEAvvYAuiaYIckQhiG2EahpDjie5HSGACyxYpTc_YZ02Azk_ZSUTCyshoax_GJSE4ISABypzoUAniDWhADm1Ponhrt71MEhADIQ0Mcdew6Z2blG9W-wFk-GADKYH2Vnwr1-mF8ODAGXwRH4P0hsWAFmAulsNiI8kIAGIxthYltyAQajUCg5qp1MJUkQ5dLQIPpWoRBGVUhT4olkrYCJx2Ti-ey6hSQmBqLowAFoCcwbAGEQpJw6ZgEthpbLjgx-vxlZy0bEANbQxpffLU2AhED_MBefRqPoY2AIlWW60QMCPZ7gikNLI5Mx5Cm0im3UIAFQgRp9Fr9n1gNAsjVdDXdtvtjvwnGDrrDD2ofQsMchHwDeiMOYpIF0wBOuhaLIhb1LZpTsGAADdkhZqCBW77YNDsLCs5WLdhNNQ2rHHDPMNBqGpjgQACIStRi2hgWAACXtOA9-3lsEBTRa10hHeoFiM-H65AAdOQtiYB4UPXKm5DLf7-3OHCiaJOgQ5xFBe37ALMjRgAAwgkSROjYiKwFs_Aiv-mCdsklBogGBDltAsSaFcb6wCG_7YIY4oQEWs7fu8v6Bt8pGYVBVFwdyiHIQiaFts4gHop4oHAOBkJYboOHxvhBiEcRom_JQMBgICEAAF7HEQgh8ZEAI7oYEAnBkMSadpmCKboGhgAhnhIFeN6GJUhCkeR9EeoYajAqCLwsbAAD0vkCcBwkVP-LnfiAwBPNZdH0X8CQnCOrICj5Q6JYIzkDlSbzkp0WWwDllQANxAA)

**Comment by abdurrahmanyildirim** [comment]
> [data.itemStyle.color](https://echarts.apache.org/en/option.html#series-gauge.data.itemStyle.color) is set to _'auto'_, which is an invalid color. [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWEAmAuWA5AIwCcRATAGYCG2ARgLQ1FEN3nkCsbHJTADADZsJOgHYS_AMzl-BADTpM1aBAC21SDHxgATgFcApooyxIYADaH8AbSWZk9h2cMAPMPgIA5QwHdYAIKuEADOCk4OVpQehADGhtBghrrhps4hABbAvjoGxhGYYKCe_ACkBBEAvvYAuiaYIckQhiG2EahpDjie5HSGACyxYpTc_YZ02Azk_ZSUTCyshoax_GJSE4ISABypzoUAniDWhADm1Ponhrt71MEhADIQ0Mcdew6Z2blG9W-wFk-GADKYH2Vnwr1-mF8ODAGXwRH4P0hsWAFmAulsNiI8kIAGIxthYltyAQajUCg5qp1MJUkQ5dLQIPpWoRBGVUhT4olkrYCJx2Ti-ey6hSQmBqLowAFoCcwbAGEQpJw6ZgEthpbLjgx-vxlZy0bEANbQxpffLU2AhED_MBefRqPoY2AIlWW60QMCPZ7gikNLI5Mx5Cm0im3UIAFQgRp9Fr9n1gNAsjVdDXdtvtjvwnGDrrDD2ofQsMchHwDeiMOYpIF0wBOuhaLIhb1LZpTsGAADdkhZqCBW77YNDsLCs5WLdhNNQ2rHHDPMNBqGpjgQACIStRi2hgWAACXtOA9-3lsEBTRa10hHeoFiM-H65AAdOQtiYB4UPXKm5DLf7-3OHCiaJOgQ5xFBe37ALMjRgAAwgkSROjYiKwFs_Aiv-mCdsklBogGBDltAsSaFcb6wCG_7YIY4oQEWs7fu8v6Bt8pGYVBVFwdyiHIQiaFts4gHop4oHAOBkJYboOHxvhBiEcRom_JQMBgICEAAF7HEQgh8ZEAI7oYEAnBkMSadpmCKboGhgAhnhIFeN6GJUhCkeR9EeoYajAqCLwsbAAD0vkCcBwkVP-LnfiAwBPNZdH0X8CQnCOrICj5Q6JYIzkDlSbzkp0WWwDllQANxAA)

That Worked. Thanks
