### ISSUE TITLE
根据标准经纬度有没有方法可以获取到当前处于哪个国家

### ISSUE THREAD

**Issue by wendao-liu** [apache/echarts#18578]
### What problem does this feature solve?

根据标准经纬度有没有方法可以获取到当前处于哪个国家？

### What does the proposed API look like?

根据标准经纬度有没有方法可以获取到当前处于哪个国家？

**Comment by susiwen8** [comment]
没有，应该也不会考虑。最好调用专业的 API 获取数据。
