### ISSUE TITLE
[Bug] Failed to append new Shape to charts by zrender instance.

### ISSUE THREAD

**Issue by GitHubJiKe** [apache/echarts#18577]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/basic-line-chart-forked-j2x1tu?file=/index.js:508-513

### Steps to Reproduce

check this example: [codesandbox](https://codesandbox.io/s/basic-line-chart-forked-j2x1tu?file=/index.js:508-513)

### Current Behavior

get `zrender` instance by chart api `getZr()`, then add new Shape such as `Circle`, and then do `refresh`, but there is nothing added on the view.

### Expected Behavior

by `zrender` instance to append new `Shape` and can expand new widgets to charts.

### Environment

```markdown
- OS: macOS Ventura
- Browser: Chrome 112.0.5615.137
- Framework: Vanilla JS
```

**Comment by Ovilia** [comment]
It's not recommended to call zrender to add shape. Please consider using [graphic.elements](https://echarts.apache.org/en/option.html#graphic.elements).
