### ISSUE TITLE
[Bug] candlestick chart encode option doesn't work for multi-dimension dataset on 'category xAxis'

### ISSUE THREAD

**Issue by sirokuma2023** [apache/echarts#18574]
### Version

"echarts": "^5.4.2"

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqYQC2B0eUdpA2gOTZgEsA0sLot3XgGMANsEKCWACwgBzKQTxhJYgO6LlAXXIBfLuQAeAQQMQ8pVBVhgAniAKkWQnAVnAATjZa796GybMLcnRbe0cANywRAFdOH3JCdwhFZmCyKxC7B2EsaAwRDQghAGtuNPRaIWAMbMsM9ANHdk5fetgbZj57aElRcRbeGXkNFWB1JRZter1yzBwsVLbYJgBGAAYeACYN2ABmABYedZ5dgA4ptoB6S-WVrn2d3YBWE52ntc1W-uvlza5du57U4nXY8fb7T6zdA_Jigs5HF6wRH7TYXKxo2A6cjaHQAbiAA

### Steps to Reproduce

The link as above.

### Current Behavior

dimensions: ['date', 'open', 'close', 'highest', 'lowest']

'date' dimension of the data maps on 'open' dimension of candlestick series.

### Expected Behavior
'date' dimension of the data should map as planned.
It works fine on value xAxis,but consumes too many computational resources and the bar width also looks weird.
Actually,I want to update next candlestick bar by clicking the chart,but it seems like it's only availible on bar series.Following link is bar series demo:
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMgL4A0as2ApgOaXQAmhSp59AhmGwM6VhPnp6EALZ0uUaF0IBtAOQQGlAB6ySsWQDc22AK6VZAXXIt0SgIJKIU5AIwBPEJUKyAxhxrAATndnGy6OwsrJhNYHk8ISmtpW1R0eNhoNlFnAGVtfX8E-0dnACM2T1VbQQ42GRL46QAGNQAmAyzs2Gk6tQBmI2bGyroXYHonG2bTZwVBlSbsuxlNbT1DSqJbZfQjIgBuFBQtT1gALz3EYTsAYQALQrAAOlowAC1PAAoASi3d2HHlBFgAdi3DtcYE9XNgIC4ANaqWAAMx00BckBgsCeIEKyS4L2GsA-IGACjAAEloAAFCBKSjYH7SNGeDFAmEwnhgAAaalp9OAjOZAE0DFt0Lj8dAidAAOIReg_E4XK7XfrQDSUTxgABinmAwjJFOwIOokuheIJxO1lLe5AgMJRMsuKvlME4ClNutk-og9ENwtFzpeWLi8QA9AHYOxOAB9ACM1xAOi45ye0i-SgA1Mm1EmDOaEgquDhKNdsMBqE8k1n4ja5cyAPLgCRPf0JcKRaKVdANkbuwhJqbNMAOIayApFHvZUPlFqJxQptOfKcGHojeJsaAiDgSQgw7Q8VuwVbZLrxIhl5ZHjZAA

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://user-images.githubusercontent.com/130817571/234841535-92a641ac-bc66-4217-82ec-7e11f0a4525c.png)

**Comment by helgasoft** [comment]
This is not-a-bug.  Use **one** of:
- series.data with series.dimensions
- dataset (eventually with series.encode)

but not both and not mixed. Series.data takes precedence over dataset.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqYQC2B0eUdpA2gOTZgEsA0sLot3XgGMANsEKCWYgO4E8YSQAsIAc0VyFAXS7l0eYAFcATkILMmAVh4AmAAw8AzABYeARnuwHADk2byAXx10AA8AQWCIPFIkQPIAT3DI6Ni9AiMIOWZdMgoKMDiQM2EsaAwRDQghAGtubPQAenrYIWAqGmgwWENO6AJgzutYI2BpPFgwYFgDQkwcfCJYOsp2-hgo2FZ2Th4-QuhJUXFt3hkNJVV1eRZtJfYsc3cbD2c3Z58_XP9yP38AbiA)

**Comment by sirokuma2023** [comment]
> This is not-a-bug. Use **one** of:
> 
> * series.data with series.dimensions
> * dataset (eventually with series.encode)
> 
> but not both and not mixed. Series.data takes precedence over dataset. [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqYQC2B0eUdpA2gOTZgEsA0sLot3XgGMANsEKCWYgO4E8YSQAsIAc0VyFAXS7l0eYAFcATkILMmAVh4AmAAw8AzABYeARnuwHADk2byAXx10AA8AQWCIPFIkQPIAT3DI6Ni9AiMIOWZdMgoKMDiQM2EsaAwRDQghAGtubPQAenrYIWAqGmgwWENO6AJgzutYI2BpPFgwYFgDQkwcfCJYOsp2-hgo2FZ2Th4-QuhJUXFt3hkNJVV1eRZtJfYsc3cbD2c3Z58_XP9yP38AbiA)

Thanks for the reply, but I need the xAxis type as category. Because when the data size grows, the bar width doesn't change, which looks very weird.

**Comment by helgasoft** [comment]
> On value type, when the data size grows, the bar width doesn't change, which looks very weird.

Let see that first (Minimal Reproduction) and we'll go from there.

**Comment by sirokuma2023** [comment]
> > On value type, when the data size grows, the bar width doesn't change, which looks very weird.
> 
> Let see that first (Minimal Reproduction) and we'll go from there.
[demo](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqYQC2B0eUdpA2gOTZgEsA0sLot3XgGMANsEKCWACwgBzKQTxhJYgO6LlAXXIBfLuQAeAQQMQ8pJHvIBPE2Yvl0YayAKkWANywiArp1366OxYAFrAwFTMlpqBsIQAThCKzI5kFBTOru5CWNAYIhoQQgDW3KnotELAGG5p6RQG7uycsfWw1sx8rtCSouItvDLyGirA6kos2m1W5Zg4WClt6EwAjDwATAAMPADMACw8K9uwOwAcMbPL6zx7xzsArLvH98crF0uwTDu7ayenu99YHsDid3ksmCCzodHrAYXtrkCpvUkegdORtDoANwoLzxWAALzxiCo1gAwlIsPEwAA6WREELxAAUAEpsbjYBA8gQDAhYAB2bGE6kwRksURFUo8ABmPmgQkgMFgjJAlKwVDwzLq7JAwE5YAAktAAAoQAwEES8pgq-JqvDCqVSwhgAAaPGttvtjqIAE1NNj0NrddADdAAOKJDC8knkyk0qrQDwEKkAMXiERNZpEotkEcEOr1hoz5tZ5AgUqV0YpVOp8dwnKLWZYOYgGDzQZDDeZmtQ6QA9L25rgAPorakgHx4KSMpicmoGADU854s-5mhL6XjeGABWpYlkjJXBnXFErsepToA8uAGIye_UEklzJ9LnUPi3SIfWksAEaUgDqLZgFI7hbAApGUHxOC4tRirk-SFCUEGQcEzCrJsdz_LAKwwnCCJ7JoYIfLk1A4AwpBSt4hAvmibQorAOjHmiDGYkAA)
Click the chart, it will update next candlestick. Like I said the width doesn't change when zooming.

**Comment by helgasoft** [comment]
**Add data** to the series instead of adding a new serie with a single candle - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqYQC2B0eUdpA2gOTZgEsA0sLot3XgGMANsEKCWYgO4E8YSQAsIAc0VyFAXS7l0eYAFcATkILMmAVh4AmAAw8AzABYeARnuwHADk2byAXx10AA8AQWCIPFIkQPIAT3DI6Ni9AiMIOWZdMgoKAHo8iAxSFiwsbmz0MDiQM2EsaAwRDQghAGsK3PQC2CFgKhpoMFhDYegCYOHrWCNgaTxYMGBYA0JMHHwiWErKQfoYKNhWdk4ePlroSVFxU94ZDSVVdXkWbR32LHMrWDtHF1h3I4fG8urAAEZYIwAdSKYEUJTsAFJOhR_OQ_P4ANwoIRDBCwWzYqhxADCikhYAAdCoiAAtIwACgAlJSYAyWKJWh0eAAzAzQISQGCwBkgSFYKh4Jk5WAAN0hsBAwAgQwAktAAAoQYIEET4phiowSvCsnk8whgAAaPENxtN5qIAE1NNj0PKjIrlWroABxdIYfHEskUyl9aCytJgABisyoWp1InZKn9giVKrA6vjuqZrtgEB5IqD5KMVLDuBVWcTLGTRVTXozmu12elqFyoEDpOLVJpYAA8uAGMzc-hQJTCOk5ExbJpKR9KSBVooGUwANQr3FgABUgM8Xjc32-_yc1k0OeyRZDFv7QugDNAPDARgMBBz3TyMwIIBEWFMARQ_hzIA)

**Comment by sirokuma2023** [comment]
> **Add data** to the series instead of adding a new serie with a single candle - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRXgKYBOEThsA2hequgNhhKIJkQDkAYwCG0ACYAbDpEkBrceUHo5EALZNoeKIaJdxc6WCYbY40AZtSFwZo4AWEAOZvlj5wHdfAF1NLQswaVMuAFZSWAAmAAY4gGYAFlSADjiARkSgkN4BACNpFgB1CDkwNwkkgFINIuIKIJRiAG4USWgwBFhErt1KAGE3MrAAOk8mMAAtFgAKAEpJmEWnCDUbADMAV2hJSBhYRZAy6V08ZeQKADcy2BBgCF6ASWgABQgMJgV-rjnFiXPBrHY7ZhgAAacSBILBENmAE0gl10A8WE8Xu9oABxNhyfrDMYTSaSGB3VhgABiLGAum-vwUG08BJsz1eYA-jL-yzRsAgO1OxPGLCm5N60lePOZ4lZVXZ2K5Xx-vJu_AEoCJo1FUxmYAA8uBjCt-ehQJNmGwOFx8pNwtJJiA9ng3IsuABqD09MAAKjyWVysVgaXicTSQT5RRFpMhRuO0EWoDiYBYeyYfPQAHos7AWEwQAppJImBQWsQ-UA)

Thanks for your constant support, it may be my last resort to the issue. I thought about this way at the beginning, but it requires unnecessarily additional computaitional resources. However,the rendering speed is fast than I expected. Do you think it's a good idea to pull a request to add category sort feature on candlestick series or other cunstom series like the bar series have?

**Comment by helgasoft** [comment]
If you mean "sorting" like  [bar.realtimeSort](https://echarts.apache.org/en/option.html#series-bar.realtimeSort), it could be done in the click processing, all data is available there.
Adding a request for a "new feature" that can be easily written by the user himself will get no traction with developers here.
<details><summary>disclaimer</summary>
opinions expressed in this post are strictly personal, as ECharts user, not a developer
</details>
