### ISSUE TITLE
[Bug] Bar width issue when using barCategoryGap

### ISSUE THREAD

**Issue by roelbondoc** [apache/echarts#18580]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?version=5.4.2&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5JALZW0A0JAvm-uTvkaqTKUasWgDcAhgBsArsw5dYeKgCcIVQrADaJdAMGwAJhLASiWrQEYAbAA4ATNYCcABgCs9l15ctYAFgBdXy1YGwdnd1tvH1gXAKDdUgpqOgAjCRVWRPR0lQBhEyoAc2AVcgBxCRA6S1pE9hIAlHYAbiA

### Steps to Reproduce

1. Configure a chart with the following options:
```
option = {
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [[1682690520000, 4], [ 1682690580000, 0]],
      type: 'bar',
      barCategoryGap: '1'
    }
  ]
};
```
2. Observe that the chart has been rendered with a narrow width bar.

![image](https://user-images.githubusercontent.com/134351/235459285-9d553f3d-def3-4e13-85d0-f215f24158df.png)

### Current Behavior

Chart is rendered with a very narrow bar.

### Expected Behavior

The bar should be rendered with a normal width.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
use _barWidth_ and see #18569
