### ISSUE TITLE
如下图框出来的地方,怎么才能实现

### ISSUE THREAD

**Issue by fff21** [apache/echarts#18592]
### What problem does this feature solve?

![Snipaste_2023-05-05_08-52-54](https://user-images.githubusercontent.com/130143783/236415961-0c94d854-0d23-4722-a888-5dd5e1b363d2.png)
框出来的地方尝试了很多次,  出来的效果还是不一样. 希望得到大家的指导(〃'▽'〃)

### What does the proposed API look like?

` let option = {
       "xAxis": [
         {
           type: 'log',
           axisTick: {
             // 轴刻度
             show: false,
           },
           axisLabel: {
             formatter: function (value) {
               if (Math.abs(value) > 1000) {
                 if (value == 0) {
                   return "0";
                   // 检查是否已经转化为科学计数了
                 } else if ((value + '').indexOf('e') > 0) {
                   return (value + '').replace(/e/, "E");
                 } else {
                   var res = value.toString();
                   var numN1 = 0;
                   var numN2 = 1;
                   var num1 = 0;
                   var num2 = 0;
                   var t1 = 1;
                   // 计入小数点前后有多少位
                   for (var k = 0; k < res.length; k++) {
                     if (res[k] == ".")
                       t1 = 0;
                     if (t1)
                       num1++;
                     else
                       num2++;
                   }
                   // 均转换为科学计数法表示
                   if (Math.abs(value) < 1) {
                     // 小数点后一位开始计算
                     for (var i = 2; i < res.length; i++) {
                       if (res[i] == "0") {
                         numN2++; //记录10的负指数值（默认值从1开始）
                       } else if (res[i] == ".")
                         continue;
                       else
                         break;
                     }
                     let v = parseFloat(value);
                     // 10的numN2次方
                     v = v * Math.pow(10, numN2);
                     v = v.toFixed(1); //四舍五入 仅保留一位小数位数
                     return v.toString() + "e-" + numN2;
                   } else if (num1 > 1) {
                     numN1 = num1 - 1;
                     let v = parseFloat(value);
                     v = v / Math.pow(10, numN1);
                     if (num2 > 1) {
                       v = v.toFixed(1);
                     }
                     return v.toString() + "e" + `+`+  numN1;
                   }
                 }
               } else {
                 return value;
               }
             }
           }
         },
         {
           "name":"β",
           "type": "value",
           axisTick: {
             // 轴刻度
             show: false,
           },
         }
       ],
       title: [
         {
           left: 'center',
           text: '分布概率图(威布尔)'
         },],
       yAxis: {
         type: 'log',
         axisTick: {
           // 轴刻度
           show: false,
         },
       },
       series: [
         {
           data: [
             [299.977543, 0.01],
             [14677, 99],
           ],
           type: 'line',
           symbol: "none",
           itemStyle: {
             normal: {
               // color: '#a80000', //改变折线点的颜色
               lineStyle: {
                 // color: '#a80000' //改变折线颜色
               }
             }
           },

         },
         {
           data: [
             [150.977543, 0.01],
             [12477, 99],
           ],
           type: 'line',
           symbol: "none",
           itemStyle:{
             normal:{
               // color: '#a80000', //改变折线颜色
               lineStyle:{
                 type:'dashed',  //'dotted'点型虚线 'solid'实线 'dashed'线性虚线
                 // color: '#a80000', //改变折线点的颜色
               },
             }
           },

         },
         {
           data: [
             [478.977543, 0.01],
             [18477, 99],
           ],
           type: 'line',
           symbol: "none",
           itemStyle:{
             normal:{
               // color: '#a80000', //改变折线颜色
               lineStyle:{
                 // width:2,
                 type:'dashed',  //'dotted'点型虚线 'solid'实线 'dashed'线性虚线
                 // color: '#a80000', //改变折线点的颜色

               }
             }
           },
         },
         {
           data: [
             [2001.977543, 1.123],
             [2300.977543, 1.1299],
             [2392.977543, 1.2299],
             [2333.345543, 1.54299],
             [2533.477543, 1.67599],
             [2673.6433543,  1.675429],
             [2677.76343, 1.67129],
             [3100.76343,2.1234],
             [3122.76343, 2.67129],
             [3233.76343, 2.7775429],
             [3333.76343, 2.897665],
             [3445.76343, 3.12345],
             [4133.76343, 4.23533],
             [4312.76343, 5.98776],
             [4423.76343, 6.45323],
             [4576.76343, 7.875776],
             [5627.76343, 8.2432],
             [5243.76343, 7.75432],
             [5632.76343, 8.23454],
             [5782.76343, 9.8653],
             [5821.76343, 10.24324],
             [5932.76343, 11.875776],
             [6121.76343, 12.24324],
             [7332.76343, 13.875776],
             [7442.76343, 15.23533],
             [8721.76343, 18.24324],
             [8832.76343, 21.875776],
             [9921.76343, 24.24324],
             [9332.76343, 31.875776],
             [9432.76343, 34.875776],
             [9532.76343, 46.875776],
             [9632.76343, 56.875776],
             [9999.76343, 63.875776],
             [11042.76343, 52.23533],

           ],
           type:'scatter',
           itemStyle: {
             normal: {
               color: '#a80000', //改变折线点的颜色
               lineStyle: {
                 color: '#a80000' //改变折线颜色
               }
             }
           },
         },
         {

           "type":"line",
           "xAxisIndex": 1,

         },
       ],
       tooltip: {
         trigger: 'axis',
         axisPointer: {
           type: 'cross'
         }
       },
     };`

**Comment by helgasoft** [comment]
Hope this will help - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=LYBwBAvGDeBQYMQgzgT2AIwPYBsBcYA5AIYBOpWA7oQDRhqa4DKAlgF4CmBArHQ9jgBKWAC7ERXMAFoAnAAYa8JIhzEMHfDGQALKgRGkArhzogsyFiJZYAdgUI4OAMxG0wTrKWDiJpPIWgAYwBfQmDFZUQAE3FiAgBtJUiEaFQAQQAPFmQeOgzM7LwARjkFMAA3Yhxjf24AOlKwiOSU9KycsAAWMvz24tK6SuquQm6GuTCk5QBdKYRg2BwbSGU4SJFUEEkHFhsOWjmwXuyASRsojgyCIr50AVZOPAVDnF2OJg3HAmgNrfso0QSKJNQ4cc4AGTUGm-Oj0YAMxjoHi8Pg4fgCAAFyqE6FgnE5kBwRHh4lIijcyUVpmBwocoixgGCLLYOvFCBlaIRUJzyoRps15osbEUVhxAtoyCJkHVDFYcHVAjhbBwABRLACUAG4hUU6jExCt4mB4goAGwAZjqACYbnI6tx-fESjQSgo7Q7ptqllbReLJdLZSx5YrlWqbFqhVa9bFDcazZabS6Go7eK6k3Jpp7YLAsCArLYVmt4ZYvjAXs5iURAmDfAd1pdK4QACLZAwsDCBgsgCgYNRByyoMDecAqgDqHHbhhwOHVhCUtIQx1ZUyLSF-2yVAHM50gF4hV4gbMRGfZAE3AdeU6_sQ2Mbm8VzARV4h2I7Uh6k00FhlAITiqhL3JBX2yAAVFhAgAa2-ehdB_dx_w4QDEGA5AAAUsF2XwYVg38EIWXclH5JQ2kKMs102DcsG3AUh12Ag7WdKYUPfaEYGRbwRCw9xDBsQJ8xsFVynVGAwFIIlDFIZZyjqEQsAAMRYDIOCiFUrXVYIkOQEBXhEcE3mg149g-VBSyCXBPHsABiGQbLCPc90JUgWA4ZckAPBB9TiY1DgQeIrRsuoZAAdiC7hOnNOg7TkKkaKQJ1OlNEK6Bs2ZIiI9YKPsQz9li-g7lwewbGVC8kEsDhgGM0yfLAIqUU_aqEAAekasBAnMvwiEs4gAA5SkaOhmoAYQlGxNw4eFtHGtqlVIMA8Qm8azBwEy3jAMxMIasBssqyR3OSZrposzqer6iYwCGkaxoW1r2rmpxrqWla9k2_DklegjdxovbPISaqnW4O1gtC8LIoaGK_qKK1OiSsAUsOdLL0yohspKxB-AKogir2VGEDKirPl26rau8eqWialrDo6wgut6vq3GawBOU0ADeVAAyjQB-v0AHIzACcgzbtoJ75NoQK8iBiHRlPpxrCABTjxcATodAGj1QAtMLZohkFwFhgUAPO0Val4gxeBNnAHIDZXBZumb7E3MSwQl5n2dlwAQt25l7qvexBXaQ77Yl-lp4mh7rApCsKIrAKLwZ9opuuhoLkpkVKZly4Wdmx3L0c0QgsZyw48Z2gWWmJqpc7JvmTMJsnEET0XJuBXLIkpi2rZsHHlFdj7m6mD3DkT5BAlRUgm5-7yfatUpdSBoO6F1SHzQRyI_PNUoA-B4PJ_82Oa-NK1zRkKMx5Bx9rVXmflDn81LXNTpuHH_ewsP9e_O4U-6ijq_dUS7gUrvq1EstU1wvNF-6hv06P5I-cUv4hTqEFC0e9X5BUhmvP65pXSQOgcHKMU9OigMQPEJBVooxQPPmgwBcCQF33NJvS0BC974MDsAhBPtT6PyoUQ7qwVTSmgdGQzoF8UGELoJaDBnC_qdCKEw1BdBOjWn_qfLBvlwqQ14XveoMhuohVNLI403DN6KODqaJ-D9N4aN9twKBOi6BBTqKokxUCjHcFNFaCxzC6D-yhuQ2xrizFgEcUHK0tiLT4PEWAFx58wq2KCt1AJfDYaWI4dPO-3AIm6icY-O0rioa2JkOQzx5JLGhTUUY00kMkmBIUWkzBd8gqn0iTAy0Vj8kVK0dk-om8H5xL-qom02SXHhXSXfbq3UsnJM6XUmxd8bKdKGZIspRjMmDMCUg3J1j1FjJ6Z48-iz6l_RkAYzxCUNmjK2f4zxdj9nLK2TZGQniLSnKMeSOQwDjlRhaTI-GuVs78zIskfOpMyZ12OrTfq51Gq2zZg7J2Zdi5VTLggP51MTp0yBSC8FZMW5u0OEhBA3hSAQXQphAgoBcpYognpPY0FqqpwSOnYqNAqXYw0aoD83wzAWH4v4ZAYhSCuAxdEL2xpUgFA6Ncm0wQ46t3mHQKYSwbhbRsFaZoCNZK4CsCAQuQsnKbjGlTFCqMUK4psFxPaidAgUGQMgHcaLBTBE1EAA).
Of course the two green lines for probability are not straight and have to be calculated.

![image](https://user-images.githubusercontent.com/13038071/236543957-fec91c58-904c-41b6-a892-de3df5018762.png)

**Comment by fff21** [comment]
谢谢你的帮助! 帮我解决了这个对于我来有点困难的问题✧⁺⸜(●˙▾˙●)⸝⁺✧



At 2023-05-06 02:52:29, "helgasoft" ***@***.***> wrote:

Hope this will help - Demo Code.
Of course the two green lines for probability are not straight and have to be calculated.
