### ISSUE TITLE
[Bug] Series type "graph" doesn't render with "coordinateSystem" set to "geo"

### ISSUE THREAD

**Issue by bk-m** [apache/echarts#18606]
### Version

5.4.2

### Link to Minimal Reproduction

[Link](https://echarts.apache.org/examples/en/editor.html?code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aU0ApE4XKiA3tVFRRntoeCQEGEZifCQ4RhgAWSgAB1IpGyQLUQ8vKgDRVGSnFwBeP3zAzQAucsC60WAUmoAiDObzCrqYHGAauBgbRg76wKR8ABtGQjgaqyhxtWGR8agAI0Zxmv8RuvtUcdQYFoBiKzPz9s76q1M4XTgQSZbCQ8bxy53Am-mAdUZ8YgQGaiZovGBvD6fb53fAAL0YNQAjAAmJY7FAYWbzRZXOqMYDJaBjJBbXH1DHoPoDRhk0QAX06dKWTM6cFQ-ycyS2LPqkyYhFw3LRojUMHwjBJogA2rjtp8HskEdJiDAUhALLSViBUDZgVIXoRGBrPqI9ocCIQFIxdCBYviWppITtNABJAWMAAeNQADMLySBgKt9ro4UqAKy-2ndKC9UT9QZ-uq4VXEYhrJ5x6mJwIrdabWomkVoSmZwa0nmfRi4Jg2wP7GpSqT2fAweyTLJSWDddBSAC62aC1etAaD4xD8IbABZLIjvf3aVWmJg1htSYXrLdx0rkd7ywP5IoG7TAnL15bgEqpAA5VC4RiiRHG9eiL2iSPP0QgH3H-kDk8_wJz0vG871EZEn3XV9J29BAAHYUQADj_Oov1EWDJwQb1vQANl3dcKxNU9CyAmpr1ve8AGYIMLV8AE532fVD6OQwIADd5kGKcYPg5EkLQjCsNw3sfwIz4iJNEjpBA-9J2ok1X3QzCcIY9dUOguDEJE2l5xNcYiAAa0lGV13Ez4TBsVslRUwtFBgJhgURFiRRHYNQwbMNLB3HTn1zVcCw_CkqTLD9RN0ohrQeDNTJNdB8FwOAIBqDyAN2CzWKmCVJRg5EUoZfDkOikZzMs0jpLAuT5VgezSvIh8Kp2Xz80K9FiyCmkQqcvTDXuR4lWakZ7DSjLVB9BAcpCkSCpS4r7GA2rHyc2zqqk2qqMmn9-tGHUSpW0DwMWqrmBq0C1vyjbpu22bjvvfaUqWo7dpkqR1pMi6LKux66oOuyHrI0DZK0k1vIa8Keqin9CigZsHlG2jkNi-LErA5DBpgdLDRGt9y1xPK6mEwI6RoQJQEgWBEAgOLGGwPAiDIPJifAUJEDUOB2CKZxCFIQpim8Gg6SoIA)

### Steps to Reproduce

1. Load geoJson and register it as a map with eCharts
2. create options with "geo" using the registered map and add a series of type "graph" with "coordinateSystem" set to "geo" and "geoIndex" set to "0". (The data of the series does not matter, pick something.)
3.  With "coordinateSystem" set to "geo" the graph will not render. If you comment out the "coordinateSystem" it will render.

### Current Behavior

When setting the "coordinateSystem" of a "graph" series to "geo" the graph will no longer render.

### Expected Behavior

Considering the documentation lists "coordinateSystem: 'geo'" as an option for graph series, I would expect it to work just like with a scatter series https://echarts.apache.org/examples/en/editor.html?c=geo-svg-scatter-simple

### Environment

```markdown
OS: Manjaro
Browser: Firefox 113.0
Framework: eCharts 5.4.2
```

**Comment by helgasoft** [comment]
Graph series work with "geo", but [lines](https://echarts.apache.org/en/option.html#series-lines.type) are more popular.
Link edges can be defined as indexes only, I could not find how to do names. So unfortunately _edgeLabel_ only shows (irrelevant) node indexes, not names.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aU0ApE4XKiA3tVFRRntoeCQEGEZifCQ4RhgAWSgAB1IpGyQLUQ8vKgDRVGSnFwBeP3zAzQAucsC60WAUmoAiDObzCrqYHGAauBgbRksAL1RUXoBmDvrApHwAG0ZCOBqrKHm1aZn7JbiYGoBtAFoAThOEE4B2SwnLhEuARgBdfIBfLcC4MfmnZJrfd6dRZMQi4f6A-r2VDzVD7UQHKSRXAWKQAI3mgykTw-ojUMHwjCQh06gX8MzqcBAyUYNSkxBgKQgFhJdShsIIhAUjF0IFijF6omamnaLMqjFQAElQYwAB41AAMOPqSBAwFR0N0-GGNNED0VotE3SgAv6gyVdVwDOIxCg6J1pqGBvmtsY83-BtmaHQfQGjvJ9SssMacD2tN8AAEDgAmJ6vZn-urJVBzYqEWnqkPjKQGiH-xi4Jg8tXQw5Sez4GD2RZZKSwbroLHmwL5wuq9XzTXaw4AFksUfl2INLcYmBdbtqCdxXp9Zo91lMcE7Ov7TbqgZgwdD0l8qLjq9z5PmRG5lMW_1Ec_Q-FwcAgNQArJZ7DYYAA3JaEomieUIKOrwKFFA5aUgqFz7qu8iKMSk7wkcDx6vcDxRgAHDc3YIPK8oAGyKtIAj4qMZiDjBxzIVGiEoTcP6YThlhSAAcqguCMKIUaNnOpHkY8lGiN21HYbhDFMSxEzsQm2IXgmR6EAA1l-BxzmSMG4qgL47Aq_4UrATArLqc4Hv6SkwSYak6vqymiIoMA6TUf76ZpviBDIMiiJywCEqIuALqI6CwjJCABQA_HOsyqZWOpCcxurxspVk2dIjFRaJ9mKSFKmmbSiUsWxmmfNpzCZcJojJTBBn1MRMxlRO5KUtStJIPYCh7DF5JsjAHJcjyfICkK4oigmmhSsxcrfquzqoq67rGdOlm-pp66bvEYaRjGe5zkmKbOGm0gZl8wDZgmVWBJBUCHLB8Gobx6E0YJDVNfEWKiC85KvJ0z2iK8NCBKAkCwIgEDXiOOAcmQeTfeAoSIGocDsEUW2kIUqZ5K8VBAA)
![image](https://github.com/apache/echarts/assets/13038071/eb7be41a-619e-4b93-8fea-e6fe4f5f6087)

**Comment by plainheart** [comment]
> I could not find how to do names

To make it work, you may have to organize the data in the following form.

```js
{
  value:[-82.7128, 30.0060, 60],
  name: 'Node 2'
},
{
  value:[-82.7128, 40.0060, 100],
  name: 'Node 3'
}
```

**Comment by bk-m** [comment]
I tried for hours to get this to work, but it just wouldn't. In fact, I tried so many different things, I don't even know what I did wrong.
Anyway, this seems to work. Thanks alot!

`To make it work, you may have to organize the data in the following form.`
I can confirm that explicitly setting the `name` attribute on nodes allows edge creation by name.
