### ISSUE TITLE
[Bug] make pie label color match slice color

### ISSUE THREAD

**Issue by crazyxhz** [apache/echarts#18610]
### Version

5.5.2

### Link to Minimal Reproduction

https://codepen.io/crazyxhz/pen/XWxqVgy

### Steps to Reproduce

https://codepen.io/crazyxhz/pen/XWxqVgy

### Current Behavior

in not hovered, label color is using the first pie's color

### Expected Behavior

label color using corresponding pie's color

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Remove the color callback function in the `rich` option and add `color: 'inherit'` into the `label` option.
