### ISSUE TITLE
[Bug] 多实例  多Y轴的情况下  数据指定Y轴

### ISSUE THREAD

**Issue by sheliangshe** [apache/echarts#18611]
### Version

5.2

### Link to Minimal Reproduction

{ "grid": [ { "bottom": 130, "top": 60, "left": 100, "right": 0, "width": 470.3333333333333 }, { "bottom": 130, "top": 60, "left": "570.3333333333333", "right": 0, "width": 470.3333333333333 }, { "bottom": 130, "top": 60, "left": "1040.6666666666665", "right": 100, "width": 470.3333333333333 } ], "tooltip": { "trigger": "axis", "axisPointer": { "type": "shadow" }, "shadowStyle": { "color": "rgba(80,80,254, 0.2)" } }, "legend": {}, "xAxis": [ { "type": "category", "data": [ { "value": "验深按", "textStyle": { "color": "#42446B" } } ], "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "rotate": 45 }, "gridIndex": 0, "position": "bottom" }, { "type": "category", "data": [ { "value": "验深按", "textStyle": { "color": "#42446B" } } ], "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "rotate": 45 }, "gridIndex": 1, "position": "bottom" }, { "type": "category", "data": [ { "value": "验深按", "textStyle": { "color": "#42446B" } } ], "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "rotate": 45 }, "gridIndex": 2, "position": "bottom" }, { "type": "category", "data": [ { "value": "生产线888号", "textStyle": { "lineHeight": 150 } } ], "axisTick": { "length": 100 }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "gridIndex": 0, "position": "bottom" }, { "type": "category", "data": [ { "value": "口罩1线", "textStyle": { "lineHeight": 150 } } ], "axisTick": { "length": 100 }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "gridIndex": 1, "position": "bottom" }, { "type": "category", "data": [ { "value": "upper单品加工线", "textStyle": { "lineHeight": 150 } } ], "axisTick": { "length": 100 }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "gridIndex": 2, "position": "bottom" } ], "yAxis": [ { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "right", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "show": true, "color": "#42446B" }, "name": "时长(小时)", "gridIndex": 0, "max": 160, "min": 0, "position": "left" }, { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "right", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "show": false, "color": "#42446B" }, "gridIndex": 1, "max": 160, "min": 0, "position": "left" }, { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "right", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "show": false, "color": "#42446B" }, "gridIndex": 2, "max": 160, "min": 0, "position": "left" }, { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "left", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "gridIndex": 0, "position": "right", "align": "right" }, { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "left", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "gridIndex": 1, "position": "right", "align": "right" }, { "type": "value", "minInterval": 1, "splitLine": { "lineStyle": { "type": "dashed" } }, "nameTextStyle": { "fontSize": 14, "align": "left", "color": "#42446B" }, "axisTick": { "show": false }, "axisLine": { "lineStyle": { "color": "rgba(80,80,254,0.2)" } }, "axisLabel": { "color": "#42446B", "fontSize": 14 }, "name": "次数", "gridIndex": 2, "position": "right", "align": "right" } ], "series": [ { "type": "bar", "itemStyle": { "color": "#5278DA" }, "data": [ { "value": 123.9, "type": "1642771575897030658", "name": "验深按", "parentId": "1636211425654931458" } ], "name": "平均耗时", "xAxisIndex": 0, "yAxisIndex": 0, "barMaxWidth": 72 }, { "type": "bar", "itemStyle": { "color": "#F2994A" }, "data": [ { "value": 1, "type": "1642771575897030658", "name": "验深按", "parentId": "1636211425654931458" } ], "name": "发生次数", "xAxisIndex": 0, "yAxisIndex": 0, "barMaxWidth": 72 }, { "type": "bar", "itemStyle": { "color": "#5278DA" }, "data": [ { "value": 156.81, "type": "1642771575897030658", "name": "验深按", "parentId": "1636558279803990018" } ], "name": "平均耗时", "xAxisIndex": 1, "yAxisIndex": 1, "barMaxWidth": 72 }, { "type": "bar", "itemStyle": { "color": "#F2994A" }, "data": [ { "value": 2, "type": "1642771575897030658", "name": "验深按", "parentId": "1636558279803990018" } ], "name": "发生次数", "xAxisIndex": 1, "yAxisIndex": 1, "barMaxWidth": 72 }, { "type": "bar", "itemStyle": { "color": "#5278DA" }, "data": [ { "value": 27.47, "type": "1642771575897030658", "name": "验深按", "parentId": "1631180761519947777" } ], "name": "平均耗时", "xAxisIndex": 2, "yAxisIndex": 2, "barMaxWidth": 72 }, { "type": "bar", "itemStyle": { "color": "#F2994A" }, "data": [ { "value": 1, "type": "1642771575897030658", "name": "验深按", "parentId": "1631180761519947777" } ], "name": "发生次数", "xAxisIndex": 2, "yAxisIndex": 2, "barMaxWidth": 72 } ] }

### Steps to Reproduce

在多实例  多Y轴的情况下  数据指定Y轴 ，实际渲染仍然是对应的第一个Y轴

### Current Behavior

在多实例  多Y轴的情况下  数据指定Y轴 ，实际渲染仍然是对应的第一个Y轴

### Expected Behavior

无

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
参见 https://echarts.apache.org/option.html#yAxis.gridIndex
