### ISSUE TITLE
Lines goes out from chart area 

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#18621]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/ZEqRXog

### Steps to Reproduce

1 - Open the link that I provided.
2 - Make zoom a bit with ctrl+mouse-wheel
3 - Slide right by holding mouse left click.
4 - Lines will be visible outside of chart area.

### Current Behavior

<img width="337" alt="image" src="https://github.com/apache/echarts/assets/43090396/df2ca676-313f-4d67-b976-77d01fe602f2">

### Expected Behavior

Line must be invisible when they are outside of chart area.

### Any additional comments?

Currently, I am trying to do timeline heatmap. I use gradient color to do this. Is there easier way to do that?

**Comment by helgasoft** [comment]
remove ```filterMode: 'none'``` from all horizontal dataZooms

**Comment by abdurrahmanyildirim** [comment]
> remove `filterMode: 'none'` from all horizontal dataZooms

That worked. Thanks
