### ISSUE TITLE
[Bug] Missing 'all or inverse' type for SelectorType

### ISSUE THREAD

**Issue by fes0j** [apache/echarts#18636]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-stack&lang=ts

### Steps to Reproduce

1. Go to [line-stack example](https://echarts.apache.org/examples/en/editor.html?c=line-stack&lang=ts) and ensure TS is enabled
2. Replace the legend option with 
   ```
   legend: {
    data: ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine'],
    selector: [{type: 'all or inverse'}]
   }
   ```
3. See the error message  "Type '"all or inverse"' is not assignable to type 'SelectorType'.(2322)"
   

### Current Behavior

When using 'all or inverse' as a SelectorType in the legend options, a type error in typescript will occur.

https://echarts.apache.org/en/option.html#legend.selector shows the three types available.  But only 2 will have the correct type.

### Expected Behavior

The documented type should be available and not produce a type error.

### Environment

```markdown
- OS: Linux
- Browser: - 
- Framework: Vue3
```

### Any additional comments?

https://github.com/apache/echarts/blob/38d02654b863f9d5bca4a0b1e10970703047fad6/src/component/legend/LegendModel.ts#L60 seems to be the culprit in the sources.

When using as a package, this diff solved the problem:

```patch
Index: node_modules/echarts/types/dist/echarts.d.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/node_modules/echarts/types/dist/echarts.d.ts b/node_modules/echarts/types/dist/echarts.d.ts
--- a/node_modules/echarts/types/dist/echarts.d.ts	
+++ b/node_modules/echarts/types/dist/echarts.d.ts	(date 1684230367392)
@@ -3259,7 +3259,7 @@
     getLineStyle(this: Model, excludes?: readonly (keyof LineStyleOption)[]): LineStyleProps;
 }
 
-declare type SelectorType = 'all' | 'inverse';
+declare type SelectorType = 'all' | 'inverse' | 'all or inverse';
 interface LegendSelectorButtonOption {
     type?: SelectorType;
     title?: string;
@@ -10916,4 +10916,4 @@
     baseOption?: EChartsOption;
 }
 

```
Adding the third option to the type solves the problem :-)

**Comment by plainheart** [comment]
I think it is a mistaken in the documentation. The valid values for `legend.selector` are only **_`'all'`_** or **_`'inverse'`_**.
