### ISSUE TITLE
Heatmap on timeline with color. Not size

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#18634]
### What problem does this feature solve?

I am trying to create heatmap on timeline. I have 3 dimensions. [time, category, value]. Visualmap doesn't support z dimension. Currently I do it with linestyle gradient color. I calculate color stop for every point and create huge gradient color. Check this link. https://codepen.io/abdurrahmanyildirim/pen/zYmJowy

Could you implement that kind of heatmap. Chart color should change based on value.  

### What does the proposed API look like?

I just need visual map z dimension support at timeline chart.

**Comment by helgasoft** [comment]
> Visualmap doesn't support z dimension

Is "z" the 3rd (value) dimension? Visualmap supports any dimension.
I suppose your goal is to have long wide horizontal lines with many (time) segments colored by visualMap.

Idea for an alternative solution that might work - [custom lines](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_line).
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PTAEGMHsDsBcCcCWAjArrRNTIJ6gBYCmANgOYCGAzpAGawB0UAtgFA2rTgZZM4BKhaABNC8ABQAHcvHJNKAGlDkJiAJSgA3i1ARIkeEICMoALxKVjPQbEBtbTofLE9AG7liqQmMOKpMufRC5LDkAJLChAAe4ZSIIqry9g7mzm4eXgAMvtKylIHBYRHR0LHxSaAAugn2UPpCAEymKZZ1tuU6Tq7unt7Z_nlBIeEixaWEoADUoIbVyR0WaT1ZoH65-UNFMXHjUzPlVQDc9vCEsKjw0JrlsDgShABcoADkxIjQhE-JyZT4yg9Xc1AkUMj1qBkMNgyFUUOBBujqEMM0PaQPqoKsDUh0NAODR8IM9RsSPKAF8vg5KDdiP8NKAUa93gB1OKwfCPQwAFg5ijpgMp8EgAGt_p1KThqWJVPQaIhiMRQCBQDQBUxQC5EJRUO4ALLKUnkklHEksSASbiXMxaHQ4ACCkQ1j1pNzujye4GChFI-hwTzJ9kidodmlAzv-TwwTA-iko7upjwQnlAfp0lFEiEIlEedmSVrmodd4FQlMgTE-KMEUBEjqB7JhjwySfJyROEXgoVghCYj14AlbTYcg3IWZROhsT3In2e9Qy9XqAFoMgB2BcAVknGXo9WRgNH48nT2ns4XAA454YAGzr-gc7c7scTxQHmfzjIATjPl8UG9ft8B9_3h7zoYGQLoYk5zq-P4KmAxBULAKyQG8sCKFAxD6KAiCkNA-iEEIKIVKS9i3uqmo6sojrlD8kAAO7xvAnj9kIiCRiUmDQI89T9kwbz1lx5CRLW5RvHw5DQKQNIoqh-hZk8pAnII-44CQaHUfuJxCE8BHJMaOjGoaQA)
![image](https://github.com/apache/echarts/assets/13038071/ec1ac25e-ef46-4e90-95f5-672da2040ecb)
