### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by chikuairi** [apache/echarts#18635]
### What problem does this feature solve?

Hi, We use echarts to generate statistics charts, in some case we want the color is different that if the day is saturday or sunday( in some country is sunday and monday), if the color is different, we can understant the chart more clearly.
thanks. 

### What does the proposed API look like?

Want different color on weekend.

**Comment by plainheart** [comment]
`color` can be a callback function, in which you can determine the color conditionally.

**Comment by chikuairi** [comment]
thanks!
