### ISSUE TITLE
How to set the radians of the four corners of the echarts background?

### ISSUE THREAD

**Issue by nieyuan1980** [apache/echarts#18648]
### Version

echarts.5.4.2

### Link to Minimal Reproduction

null

### Steps to Reproduce

option = {
  backgroundColor :'#999',
  borderRadius: [20, 20, 20, 20],
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar'
    }
  ]
};

### Current Behavior

I tried using three methods.
**1. Added option attribute: borderRadius: [20, 20, 20, 20], (this is the answer from chatgpt)**

```
option = {
  backgroundColor :'#999',
  **borderRadius: [20, 20, 20, 20],**
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [120, 200, 150, 80, 70, 110, 130],
      type: 'bar'
    }
  ]
};
```

**2. Set the radian of the echarts container itself.**
``` 
<div ref="EnergyCalendar" style="border-radius: 20px;height: 320px; width: 100%;">
</div>
```

**3. Wrap the div outside the echarts container and set the radian of the div.**
```
<div style="border-radius: 20px;">
  <div ref="EnergyCalendar" style="height: 320px; width: 100%;">
  </div>
</div>
```
But none of these three methods are effective.

### Expected Behavior

I expect the four corners of the echarts background to have a certain degree of curvature

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Just set `border-radius` for the chart container element. Refer to this [demo](https://codepen.io/plainheart/pen/YzJdrVR).

**Comment by nieyuan1980** [comment]
Thank you very much for your answer. After comparison, I found that there is a missing CSS attribute: overflow: hidden.
The correct method is:
#chart-container { 
  overflow: hidden; 
  height: 320px; 
  width: 100%; 
  border-radius: 10px; 
}
