### ISSUE TITLE
[Feature] 數據相差很大時，怎麼樣能讓他們同時顯示

### ISSUE THREAD

**Issue by mukiwu** [apache/echarts#18655]
### What problem does this feature solve?

如果今天有兩筆資料數字相差很大，如下：

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [8, 23131],
      type: 'bar'
    }
  ]
};
```

demo：
https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiABw8sABMAMwAjDnWoR4U1HQARowcwR52JLZ2ANxAA

那麼我很難在圖表上看到第一筆的資料，可能會覺得他是 0 或無資料

### What does the proposed API look like?

有什麼辦法能在不限制 Y 軸刻度的情況下，讓 Y 軸能自己判定數據去調整刻度，然後顯示資料比較小的圖表

**Comment by helgasoft** [comment]
```yAxis: {type: 'log'}``` ?

**Comment by mukiwu** [comment]
如果還是傾向使用 `type: 'value'` 的話，該怎麼處理呢？
因為資料量都是數值，不太確定改用 `type: log` 會有什麼影響
還是他們之間的差別只有刻度不同？

**Comment by plainheart** [comment]
也许你可以试试设置 [`barMinHeight`](https://echarts.apache.org/option.html#series-bar.barMinHeight)
