### ISSUE TITLE
[Bug] The label is displayed incorrectly in the pie chart

### ISSUE THREAD

**Issue by MissThee** [apache/echarts#18654]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/missthee/pen/Baqvgaj

### Steps to Reproduce

1. Using the official pie chart example, open in codePen.
2. Change the series[0].label.show property of the option to false. 
3. Assign it true after 1s

### Current Behavior

The label should show when hover

### Expected Behavior

The label disappears when hover.

### Environment

```markdown
- OS: Ubuntu 23.04 
- Browser: Edge 115.0.1851.0 ; Chromium 113.0.5672.126; FireFox 113.0.1
- Framework: js
```

**Comment by helgasoft** [comment]
> The label should show when hover

Hover UI is controlled by [emphasis](https://echarts.apache.org/en/option.html#series-pie.emphasis). Add ```label: {show: true}``` in emphasis

**Comment by MissThee** [comment]
thanks
