### ISSUE TITLE
为什么设置xAxis.nameTextStyle. color坐标名称颜色还是没有变

### ISSUE THREAD

**Issue by suzhenghui-sky** [apache/echarts#18650]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXLANoBEAxAMyUCcAHACIBCpAugDRqxjA6QhFU6dGDwQA5uICmhWKQCGADwgBnUp2GwlqgArAI0MDMFdNYAJ4gpRUioAW8gCbAA7qVOwAvl08bY4sUdBXy5FAEFlFSJiIWELKxsMeSNxfHN1D0dk-WjSAFkYdTkAFQBXKSLSAHUpR0riu1LKgDExSoBlZI7S6DY_dGh5AFspYqlFMHaLbGtkD3QsXFlSPHEAI3kACgBGAFYAdnZYA6OT2G2ASndNb3RPDi5zCNVo2JFLWdIAN3lscuuvA90CoZBApFESG9YIMRjZAC9ugFLjQD90YA71IyZg-Ng2eHRwmxVQgjjAdhsADYAAwAUlx6CyYByJG25NOACYjizyczYNQACxHWhc6hclkc1g-MWeIA&_source=echarts-doc-preview

### Steps to Reproduce

步骤已经在上面的链接上写好了。

### Current Behavior

当前行为没有按照我写的代码变颜色。

### Expected Behavior

应该变成红色。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by suzhenghui-sky** [comment]
Thank you. @echarts-bot

**Comment by plainheart** [comment]
`nameTextStyle` 是用来设置**轴名称**的样式的，如果想要设置**轴标签**的样式，应该使用 `axisLabel`

```js
xAxis: [{
  // ...
  axisLabel: {
      color: "rgba(157, 57, 57, 1)"
  }
}]
```

**Comment by suzhenghui-sky** [comment]
> `nameTextStyle` 是用来设置**轴名称**的样式的，如果想要设置**轴标签**的样式，应该使用 `axisLabel`
> 
> ```js
> xAxis: [{
>   // ...
>   axisLabel: {
>       color: "rgba(157, 57, 57, 1)"
>   }
> }]
> ```

为什么我设置axisLine.lineStyle.color可以变色。
![图片](https://github.com/apache/echarts/assets/48371536/e7265412-c38e-470b-8238-5346c78350cb)

**Comment by plainheart** [comment]
未设置 axisLabel.color 轴刻度标签的颜色，则会默认使用 axisLine.lineStyle.color 轴线的颜色。
