### ISSUE TITLE
[Bug] Sunburst label may rotate dynamically when mouse hovers in/out.

### ISSUE THREAD

**Issue by Mingeax** [apache/echarts#18666]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=sunburst-visualMap&version=5.4.2&code=G4QwTgBAJiAuIQLwQNoCgIQN4cxAdiALYCmAXBAOQDiYI-UADiJQDS6YDGAFgJYA2UMCXwV0ePDgkTCpCpQCq-TvxIQAMiQD2bDtND8AruQgBGAKztpeHgKEixe61OvTZJygGEthgM698CAAhEV1XfRAjEwAWJ2kAXzjMAF04-PY9VMx03BdMd3kAWV4AaxIwmz5BYVFUOLy3Yg8lFTUAEXoK61tqhzrwzAbwgqpvPwCNQ04ATy6Bg2MKAGYkvByB7FWZJvkx_0D1KZK58IWYqw2IHvta8UvBrdcRygA5EkZuEgB3E8uzigATI8JIl7lkBqDXOCQZlcDk0MkANxoLSMWC8LSBZAuXwkMC8Ei-CgNWDTRgeXyGfAAI0MYF8sDmMHgFGZIAumH4IGpJH46hA0x8sGJcT4UBIAHlgHiuYwKLAwMY9Os8FyefxiZDEvFEUA

### Steps to Reproduce

1. Create a simple **sunburst** chart;
2. Set the `option.serires.labelLayout.hideOverlap` to `true`;
3. Move mouse in or out of the chart.

### Current Behavior

![pie图标签旋转bug](https://github.com/apache/echarts/assets/25583491/80d77209-672e-4dad-ace5-ab22d74414c6)

### Expected Behavior

Labels are fixed.

### Environment

```markdown
- OS: Win64
- Browser: Microsoft Edge 113.0.1774.42 (64 bits) & Firefox 107.0 (64 bits)
```

**Comment by plainheart** [comment]
@susiwen8 It seems to be an uncovered scenario in #18240. Could you please look into this issue?

**Comment by helgasoft** [comment]
add ```series.animation: false```
