### ISSUE TITLE
[Feature] Option to suppress "Can't get DOM width or height" warnings

### ISSUE THREAD

**Issue by lukeatkins** [apache/echarts#18677]
### What problem does this feature solve?

Example: I have a page with lots of charts and a tab-like interface.
Content on the inactive tabs in invisible (display: none), so any charts on that tab will have no width or height.
When I change tabs I call the resize() function on all charts.
This warning floods the console log.

### What does the proposed API look like?

Perhaps an extra option in the echarts init function called "suppressDOMSizeWarnings"

```
echarts.init(dom: HTMLDivElement|HTMLCanvasElement, theme?: Object|string, opts?: {
    suppressDOMSizeWarnings?: boolean, //true to disable "Can't get DOM width or height" warnings
    devicePixelRatio?: number,
    renderer?: string,
    useDirtyRect?: boolean,     // Since `5.0.0`
    useCoarsePointer?: boolean, // Since `5.4.0`
    pointerSize?: number,       // Since `5.4.0`
    ssr?: boolean,              // Since `5.3.0`
    width?: number|string,
    height?: number|string,
    locale?: string             // Since `5.0.0`
}) => ECharts
```

**Comment by helgasoft** [comment]
> Content on the inactive tabs in invisible (display: none), so any charts on that tab will have no width or height.
When I change tabs I call the resize() function on all charts.

Cannot quite understand, usually in a tabset, just one tab is visible by default. If so, why have style _display: none_ on the others?
Also why is resizing necessary on tab change ?  
**Sample code** would help clarify your feature request.

**Comment by Ovilia** [comment]
This log only happen in develop eniroment. When using `echarts.min.js`, there won't be this message in the console.

**Comment by lukeatkins** [comment]
> > Content on the inactive tabs in invisible (display: none), so any charts on that tab will have no width or height.
> > When I change tabs I call the resize() function on all charts.
> 
> Cannot quite understand, usually in a tabset, just one tab is visible by default. If so, why have style _display: none_ on the others? Also why is resizing necessary on tab change ? **Sample code** would help clarify your feature request.

Sorry, I mean tabs on the page, not browser tabs. For example: https://www.w3schools.com/howto/howto_js_tabs.asp
All inactive tabs have display: none. When switching tabs the charts sometimes don't fill the space properly, so it's easy just to call resize() all all charts.

> This log only happen in develop eniroment. When using `echarts.min.js`, there won't be this message in the console.
Thanks for the tip.

**Comment by plainheart** [comment]
This warning won't output in the production environment. It's not necessary to add a new option. So I'm going to close this issue.

**Comment by Mrdifferent2022** [comment]
Maybe you could try to set 'auto' for the height and width when init the chart.
 let chart = echarts.init(dom,null,{
          width: 'auto', 
          height:'auto'
  });
