### ISSUE TITLE
[Bug] Event dataviewchanged not getting callback

### ISSUE THREAD

**Issue by NaitikPandya** [apache/echarts#18678]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/s/temperature-change-in-the-coming-week-forked-zowmox

### Steps to Reproduce

1. click on dataView from toolbox
2. there should be a log in console that print the "value"

### Current Behavior

myChart.on('dataviewchanged') but it's not getting call on click the dataView icon.

### Expected Behavior

i want a callback when user click on dataView icon and also when the user click on close button.

also want that i can trigger the click of dataView programmatically.

please look into it.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
The `dataviewchanged` event is triggered only when the data is changed in the dataview. It won't be triggered if you just click the icon. There is no available API for listening the icon click event and close event for now.
