### ISSUE TITLE
[Bug] 设置了yAxis. nameRotate后 yAxis.nameTextStyle. padding不生效

### ISSUE THREAD

**Issue by yangxiuy** [apache/echarts#18681]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis

### Steps to Reproduce

nameGap: 20,
nameTextStyle: {
    padding: [0,-80,0,0],   // 当设置了nameRotate，修改padding不生效
 },
nameRotate: -90,

### Current Behavior

在上面链接的实例中，设置了yAxis. nameRotate后 yAxis.nameTextStyle. padding不生效

### Expected Behavior

设置了yAxis. nameRotate后 yAxis.nameTextStyle. padding依然生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Some padding is working with _nameRotate_, even in your example. See if [this workaround](https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis&code=PYBwLglsB2AEC8sDeAoWszGAGwEbAA8AuZNdWAMwFMBDMAVwCcqTVzyATOmgNQioDurWAGcAFsCEZG9KgBpYzGhwDy0bAE8SFGthFVYAXzll2zEZmbDxkkmBkHjp8iJoA3KgEERASQC2NADmLMiiElL2skbOhmRO6NhUwdAcwvGwBJ4EECIkANrObOywNNkiACoQAMYA1qzO7LoQgdAA6hBgYgAyNLhU2HYODUYmxbBcYDT5AOQAUjTQ0wrTAGJUuEuw0wCyNIyb054g-8u7Ggez9IvLl9gHnvSBBwDKVCAHKlVgBwBywG4HAAiVCq0wAujEyGDRrANFkcvlCsNoDQ_CFpgAdaBYrGwQCUdoAyvSWyNRVAA4jQQCQAEwABhh7BRaIASsBJmAQgBaACc9JJaPKVAIYGeYA0iXqY3QIGUHAg0EC-XpnIAjLTocN0GIqM0xGASABWWnDdKNbDNaCVWq5aSyBnkUo5LrykJFMY2CIOe3sc3QKii8WuzXkKo4YCMEjTZgcabB2JjU0Oso9PoDUhSyjhgJgDkRrZINy6WSGWAABoAwrGE_b47ANeh9Ix-DaCuw3eQmeiAKKFkDhuhQa7DMUgdG4PbEsYTKawVtS6kAOnpsAALAvuQoAOxLhTUgDMC-pu4NC4AbFvTwvNwoVXuT-fYCrT4uj7A94uH3Sd7BLyuFAe92GCF2HSCFDAAbiAA) meets your expectation.
![image](https://github.com/apache/echarts/assets/13038071/29fde94b-09c9-45a2-bef9-0d25ba9db82f)

**Comment by yangxiuy** [comment]
很抱歉我没有把问题描述的更详细，在您的例子中 
nameTextStyle: {
    padding: [0,-10],  // 当此处修改成 padding: [20,-10]没有效果
    height: 50
},

**Comment by yangxiuy** [comment]
> 很抱歉我没有把问题描述的更详细，在您的例子中 nameTextStyle: { padding: [0,-10], // 当此处修改成 padding: [20,-10]没有效果 height: 50 },
