### ISSUE TITLE
[Bug] line-chart's top/bottom line's width thinner than others

### ISSUE THREAD

**Issue by appleqzw** [apache/echarts#18683]
### Version

4.9.0

### Link to Minimal Reproduction

https://codepen.io/appleqzw-the-encoder/pen/ExdzEQv

### Steps to Reproduce

view the site  https://codepen.io/appleqzw-the-encoder/pen/ExdzEQv

### Current Behavior
In this demo,l set `xAxis.show:false` and `yAxis.show:false`,then l set `grid.top:0` and `grid.bottom:0`,I found that the width of the top line is thinner than the others, and the bottom line is the same
![image](https://github.com/apache/echarts/assets/52663862/10fdfc02-e1ae-4785-ba67-5e70239151f7)
if set`grid.top:4` and `grid.bottom:4`,then the line width is right,is this a bug?

### Expected Behavior

Is there any other way to solve this problem?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
The line width is not involved in the calculation of the grid component. It may be enhanced in the future.
