### ISSUE TITLE
饼图 label 重叠问题

### ISSUE THREAD

**Issue by Lancezh** [apache/echarts#187]
最近在使用中发现，饼图中，如果相邻两块数据比例值较小时，两块的label会重叠在一起，看着很不舒服，如下图
![image](https://f.cloud.github.com/assets/5071776/1909548/55d0288e-7d02-11e3-8470-2e77e923991d.png)

如果调整 labelLine 倒是可以简单解决，但由于数据的不确定性，这个算法会比较复杂和难以维护 ，比如 
![image](https://f.cloud.github.com/assets/5071776/1909563/908961ca-7d02-11e3-8c68-91a540d70069.png)

HighCharts中，是不会出现这样的问题，咱们是不是也可以做一下类似  文字的碰撞检测，或者弯曲展示等方式 优化一下？  谢谢啦
![image](https://f.cloud.github.com/assets/5071776/1909584/de0eaa7c-7d02-11e3-9b6d-d2341ec4f83a.png)

**Comment by 308787520huanhuan** [comment]
how to resolve this problem?

**Comment by kener** [comment]
Has not been fixed？It should ok in current version.

**Comment by 308787520huanhuan** [comment]
echarts-2.0.4
![22](https://cloud.githubusercontent.com/assets/3348828/5734867/864e5246-9bf7-11e4-8f31-a9149e9ce447.png)

**Comment by kener** [comment]
upgrade

**Comment by 308787520huanhuan** [comment]
hello May i ask one question?How to get the percentage in bar?
![qq 20150121154532](https://cloud.githubusercontent.com/assets/3348828/5832754/d0d6754a-a184-11e4-8a3c-8aea33be33f2.png)

**Comment by kener** [comment]
Use a function as the label.formatter, do this login in the function. Just calculate the percentage from your own option, it's easy.

**Comment by 308787520huanhuan** [comment]
你好!为了解决label重叠的问题 按照你的建议 我下载了最新的Echarts版本(2.1.10) 用的是"标签式单文件引入" 设置labelLine : { show : false  }报错 而设置labelLine : { show : true  }则是正确显示 为什么

?

**Comment by 308787520huanhuan** [comment]
![2](https://cloud.githubusercontent.com/assets/3348828/5931661/7a0d8be8-a6db-11e4-93fc-721cfb5bd57a.jpg)

**Comment by kener** [comment]
谢谢反馈，bug！下个版本修复。

**Comment by TingYinHelen** [comment]
为啥这个问题在echarts3中还有呢？怎么解决呀
![2017-05-26 2 26 39](https://cloud.githubusercontent.com/assets/14006826/26483488/df75293c-421f-11e7-8512-fd202850af8e.png)

**Comment by ColinCLL** [comment]
This is a big problem that more than two label.  So I write them in legend.
![image](https://user-images.githubusercontent.com/19434659/33054953-a698815c-ceb7-11e7-814c-bc4c383760b7.png)

echarts主要的坑都在处理文字相关的东西上~~希望早日有所改善

**Comment by ColinCLL** [comment]
刚发现新版的改过了~~
