### ISSUE TITLE
[Feature] 动态主题切换需求，实现思路（CSS var）

### ISSUE THREAD

**Issue by adoin** [apache/echarts#18716]
### What problem does this feature solve?

参考了一众的issue，知道主题切换有一些问题。
在这里提供一个思路也希望能有这方面的实践。
svg模式下可以用css的变量来填充颜色i.o. fill="var(--primry-1-color)"。
canvas模式下只能：getComputedStyle(context.canvas).getPropertyValue("--primry-1-color")，而后进行后续绘制
如此可把主题文件css化，打通layer渲染和canvas/svg渲染。
从而实现如主题切换、局部状态改变之类的需求

### What does the proposed API look like?

如上

**Comment by Ovilia** [comment]
切换主题重新 echarts.init 就行了，用 CSS 是想解决什么问题？Canvas 肯定是要重绘的，所以放在 CSS 里似乎没什么用。

**Comment by adoin** [comment]
> 切换主题重新 echarts.init 就行了，用 CSS 是想解决什么问题？Canvas 肯定是要重绘的，所以放在 CSS 里似乎没什么用。

举个例子，你在100个页面里写了120个Echarts，那么你的主题切换方法需要写120次。
而css变量则不需要，外部切换主题能让所有颜色自动切换。
当然canvas难点，源码里引入mitt之类的事件机制技术栈辅助实现，唤起重绘方法。

**Comment by Ovilia** [comment]
> 你在100个页面里写了120个Echarts，那么你的主题切换方法需要写120次。

可以你自己写一个方法复用主题切换。

**Comment by adoin** [comment]
> > 你在100个页面里写了120个Echarts，那么你的主题切换方法需要写120次。
> 
> 可以你自己写一个方法复用主题切换。

Echarts 没有全局监听主题的钩子的，不管怎么写，必然是要每一个地方都要重复一次。

**Comment by adoin** [comment]
> > 你在100个页面里写了120个Echarts，那么你的主题切换方法需要写120次。
> 
> 可以你自己写一个方法复用主题切换。

你知道在哪个版本里面 有原生的主题切换功能吗？

**Comment by Ovilia** [comment]
这个是纯业务相关的问题，和 ECharts 无关，你应该自己思考怎么在自己的业务中实现

**Comment by adoin** [comment]
> 这个是纯业务相关的问题，和 ECharts 无关，你应该自己思考怎么在自己的业务中实现

Echarts 内置有做差不多了。。。
我自定义一个npm就能用，现在遇到个问题，改变主题之后setOption第一次还是原来颜色，第二次才切换成功主题。这是何意呢。。。
```
private setTheme(themeCode:string): void {
        // todo recovery theme change
        const args = this.getBackupArguments()
        this.clear()
        this._theme = themeStorage[themeCode];
        this.setOption(args[0], args[1], args[2])
        console.log(' log -：686 args', args)
    }
```

**Comment by adoin** [comment]
> > 这个是纯业务相关的问题，和 ECharts 无关，你应该自己思考怎么在自己的业务中实现
> 
> Echarts 内置有做差不多了。。。 我自定义一个npm就能用，现在遇到个问题，改变主题之后setOption第一次还是原来颜色，第二次才切换成功主题。这是何意呢。。。
> 
> ```
> private setTheme(themeCode:string): void {
>         // todo recovery theme change
>         const args = this.getBackupArguments()
>         this.clear()
>         this._theme = themeStorage[themeCode];
>         this.setOption(args[0], args[1], args[2])
>         console.log(' log -：686 args', args)
>     }
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save

搞定了。。。
不得不说Echarts里面的代码是真的乱啊
