### ISSUE TITLE
echarts/map/js/china.js 引入多次导致构建包体积增大

### ISSUE THREAD

**Issue by yangjinjun3** [apache/echarts#18712]
### Version

4.8.0

### Link to Minimal Reproduction

无

### Steps to Reproduce

import 'echarts/map/js/china.js';
 geo: {
        map: 'china',
        roam: false,
        zoom: 1.23,
        label: {
          show: false,
          fontSize: '15'
          // color: "rgba(0,0,0,0.7)",
        }
}

### Current Behavior

echarts/map/js/china.js 引入多次导致构建包体积增大

### Expected Behavior

echarts/map/js/china.js 引入多次导致构建包体积不要增加

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
抱歉，地图数据自 ECharts 5.0.0 开始已经从主仓库及网站移除，且不再维护，请尝试自行处理。
