### ISSUE TITLE
[Bug] lines的curveness设置无效果

### ISSUE THREAD

**Issue by isosky** [apache/echarts#18719]
### Version

5.4.2

### Link to Minimal Reproduction

series: [         {           type: 'lines',           coordinateSystem: 'bmap',           polyline: true,           data: [{             coords:[[116.46, 39.92],[115.46, 39.92]]}           ],           silent: true,           lineStyle: {             color: 'rgb(200, 35, 45)',             opacity: 1,             width: 10,             curveness:0.5           },           progressiveThreshold: 500,           progressive: 200         }       ]

### Steps to Reproduce

在官方的示例上修改了下data的coords，修改成2个点，增加了curveness，但是还是绘制了直线。      

![Snipaste_2023-06-07_10-48-11](https://github.com/apache/echarts/assets/15280424/6bf0e18c-5a2b-4bc4-8186-c2cb9cf1df67)

### Current Behavior

目前是一条直线

### Expected Behavior

需要绘制曲线

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Could be related to _bmap_? Curveness works fine with a geoJson map - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKgkLCIEPi4jNh4RGRUQaKM9tDwSAgwjMT4SHCMMACyUAAOpFJ6Ahai7l4-loHBwQIANioA1lAAXAFJTaItjFZwPQC0AIwAzOPmfU1wqCU9AEwArLP9wehRcBA946tzAL4bTcJQ6FD4-D2Nm4PDY-PjAAyn_QtLossAHO9N21wux6h36JzmUj4NgKC1ErHw9lQUluc2CDxGolGAHYAGz_YKfFZ41GiQHA77HJJHRLBRZOFwAXl6H3wcEGKM2onyAA8MVJ7DYYAA3RiERiqHovBCrKTHf6aW4wHDAHpwGDQywhUo9Cr6KTg_pqGD4cU9ADaJP8ohJBJAJUYOpaRHF1RtA2dujgIHZAQFwtF4qQXSl61JOz2ABZLIiWqgYF0pFlcPr8U15Iouma7pzgoi47gg2azaMAJxY8yTZYAXXMxZ-5Yj1ZrbqOVZJRzmbeCRxowVCaUQajg7BK9MIpDpzl8NGplCAA).

![image](https://github.com/apache/echarts/assets/13038071/9952c47c-6f16-47e5-a749-aed7e93610dc)

**Comment by plainheart** [comment]
It shoule be not working when `polyline` is `true`.

**Comment by isosky** [comment]
> series: [ { type: 'lines', coordinateSystem: 'bmap', polyline: true, data: [{ coords:[[116.46, 39.92],[115.46, 39.92]]} ], silent: true, lineStyle: { color: 'rgb(200, 35, 45)', opacity: 1, width: 10, curveness:0.5 }, progressiveThreshold: 500, progressive: 200 } ]

i get it,thx
