### ISSUE TITLE
[Bug] 您好，我的问题是：一个柱状图，有的柱子的值很大：10000，有的很小：1，导致Y轴的刻度很挤，而且很小的柱子由于太小了，显示不出来，是否存在可以不等分Y轴的配置呢？

### ISSUE THREAD

**Issue by coderWeiHao** [apache/echarts#18711]
### Version

lasted

### Link to Minimal Reproduction

none

### Steps to Reproduce

您好，我的问题是：一个柱状图，有的柱子的值很大：10000，有的很小：1，导致Y轴的刻度很挤，而且很小的柱子由于太小了，显示不出来，是否存在可以不等分Y轴的配置呢？

### Current Behavior

non

### Expected Behavior

希望有对应的配置可以直接实现不等分，然柱状图更加美观

### Environment

```markdown
- OS:mac
- Browser:google
- Framework:vue2
```
<img width="1176" alt="image" src="https://github.com/apache/echarts/assets/131428371/3ff85fe1-13da-4c6c-824d-998a9a340583">

**Comment by helgasoft** [comment]
duplicate of #18655
