### ISSUE TITLE
[Bug] npm run release 提示 Cannot find name '__DEV__'

### ISSUE THREAD

**Issue by adoin** [apache/echarts#18721]
### Version

5.2.2

### Link to Minimal Reproduction

https://github.com/apache/echarts

### Steps to Reproduce

npm run release， 校验被__DEV__阻塞了。
看到global.d.ts里有声明但是还是提示了。。。

### Current Behavior

npm run release， 校验被__DEV__阻塞了。
看到global.d.ts里有声明但是还是提示了。。。

### Expected Behavior

npm run release， 校验被__DEV__阻塞了。
看到global.d.ts里有声明但是还是提示了。。。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

暂时先放window下面了打包先，但是源码拉下来不能release 怪怪的

**Comment by plainheart** [comment]
我这里似乎没有复现。特意从 GitHub 上 clone 了一份 master 分支源码，分别运行 `npm install` 和 `npm run release` 命令，最后可以正常生成构建产物，过程中未发现此异常。
