### ISSUE TITLE
[Bug] npm install faild by cwebp

### ISSUE THREAD

**Issue by adoin** [apache/echarts#18720]
### Version

5.2.2

### Link to Minimal Reproduction

https://github.com/apache/echarts

### Steps to Reproduce

npm i  or pnpm i
![image](https://github.com/apache/echarts/assets/20517172/1e6ec64e-f374-427d-95c2-792695b19d03)

### Current Behavior

Install Failed.

### Expected Behavior

Install successfully.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Can't reproduce. Please provide the more detailed information or npm log file.

**Comment by adoin** [comment]
> Can't reproduce. Please provide the more detailed information or npm log file.
Here it is. https://github.com/adoin/echarts-bus/blob/master/logs/2023-06-07T04_46_05_193Z-debug-0.log.text

**Comment by plainheart** [comment]
Is there a `cwebp.exe` in the `node_modules/cwebp-bin/vendor` ? And the log shows `cwebp pre-build test failed` dut to `unable to verify the first certificate`. I think the `cwebp-bin` package might not be correctly downloaded, thus it tries to build from source but it seems Windows CMD can't do that.

**Comment by adoin** [comment]
> Is there a `cwebp.exe` in the `node_modules/cwebp-bin/vendor` ? And the log shows `cwebp pre-build test failed` dut to `unable to verify the first certificate`. I think the `cwebp-bin` package might not be correctly downloaded, thus it tries to build from source but it seems Windows CMD can't do that.

There is no such file at first. Then I get it from cwebp-bin and copy it there, failed.
Then try using cwebp-bin version8.0.0 same as latest, failed.

**Comment by plainheart** [comment]
It looks like not an issue of ECharts but a issue about cwebp-bin download. I guess it's due to the network as it need to fetch from `https://raw.githubusercontent.com`, please make sure this domain is accessible in the CMD. Perhaps you can clear this package and reinstall again or use `cnpm` to install, which will replace the `raw.githubusercontent.com` domain with a mirror site in China.

**Comment by adoin** [comment]
> It looks like not an issue of ECharts but an issue about cwebp-bin download. I guess it's due to the network as it need to fetch from `https://raw.githubusercontent.com`, please make sure this domain is accessible in the CMD. Perhaps you can clear this package and reinstall again or use `cnpm` to install, which will replace the `raw.githubusercontent.com` domain with a mirror site in China.

Thanks I'll try, But I tried install through proxy...

**Comment by adoin** [comment]
> It looks like not an issue of ECharts but an issue about cwebp-bin download. I guess it's due to the network as it need to fetch from `https://raw.githubusercontent.com`, please make sure this domain is accessible in the CMD. Perhaps you can clear this package and reinstall again or use `cnpm` to install, which will replace the `raw.githubusercontent.com` domain with a mirror site in China.

![image](https://github.com/apache/echarts/assets/20517172/ab4f240a-dc10-4825-aca1-3e4478a225af)

**Comment by plainheart** [comment]
🤔 Try to remove previously installed packages and reinstall to see if it still fails.

**Comment by adoin** [comment]
tried。。。



---Original---
From: "Zhongxiang ***@***.***&gt;
Date: Wed, Jun 7, 2023 14:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/echarts] [Bug] npm install faild by cwebp (Issue #18720)




 
🤔 Try to remove previously installed packages and reinstall to see if it still fails.

**Comment by plainheart** [comment]
Got it. I'll try to look into this issue and check if it's a problem about the build script.

**Comment by adoin** [comment]
> raw.githubusercontent.com
This do inspire me.
I finally success install, through modification of HOTS to make raw.githubusercontent.com access able in China.
Why should we use this package? Seems not actural functional.

**Comment by plainheart** [comment]
> Why should we use this package? Seems not actural functional.

It's used by the visual regression test tool and used to compress the diff images.
