### ISSUE TITLE
[Bug] animationEasingUpdate更新动画失效

### ISSUE THREAD

**Issue by minghangben** [apache/echarts#18736]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2

### Steps to Reproduce

在官方编辑器里使用以下这份配置项，折线更新动画animationEasingUpdate: 'linear'失效

``
function randomData(i = 0) {
  value = Math.random() * 99;
  return {
    name: now.toString(),
    value: [Date.now() - i * 1000, Math.round(value)]
  };
}
let data = [];
let now = new Date();
let value = Math.random() * 99;
for (var i = 0; i < 10; i++) {
  data.unshift(randomData(i));
}
console.log(data);
option = {
  xAxis: {
    type: 'time',
    boundaryGap: false,
    min: 'dataMin',
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    min: 'dataMin',
    max: 'dataMax',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [
    {
      id: 'data',
      type: 'line',
      clip: false,
      symbol: 'none',
      data: data,
      cursor: 'default',
      emphasis: {
        disabled: true
      },
    },
    {
      id: 'point',
      type: 'effectScatter',
      coordinateSystem: 'cartesian2d',
      data: [{ value: [], symbolSize: 10 }],
      showEffectOn: 'render',
      rippleEffect: {
        period: 3,
        scale: 3,
        brushType: 'stroke'
      },
      itemStyle: {
        color: '#000',
        shadowBlur: 10,
        shadowColor: '#333'
      },
      tooltip: { show: false },
      cursor: 'default',
      zlevel: 1,
    }
  ],
  animationDurationUpdate: 1000,
  animationEasingUpdate: 'linear'
};
setInterval(function () {
  const newData = randomData();
  data.push(newData);
  myChart.setOption({
    series: [
      {
        id: 'data',
        data: data,
      },
      {
        id: 'point',
        data: [{ value: [newData.value[0], newData.value[1]] }]
      }
    ],
    xAxis: { max: newData.value[0]+1000 },
  });
}, 1000);
``

### Current Behavior

在官方编辑器里使用这份配置项，折线更新动画animationEasingUpdate: 'linear'失效

### Expected Behavior

期望id: 'data和id: 'point'的数据，同时拥有更新动画，达到点和线缓慢流动的效果

### Environment

```markdown
- OS:mac
- Browser:chrome
- Framework:
```

**Comment by jinMingYang1** [comment]
解决了吗，我现在也遇到这个问题了

**Comment by jinMingYang1** [comment]
@minghangben 解决了吗，我现在也遇到这个问题了
