### ISSUE TITLE
[Feature] need a four-graph mode

### ISSUE THREAD

**Issue by zz0v0** [apache/echarts#18739]
### What problem does this feature solve?

Now I can draw various function images on a canvas, but I also want to implement a four-graph mode, that is, I can have four places on a page where I can draw images, can you give me some advice or help? Thank you!
![图片1](https://github.com/apache/echarts/assets/132249281/96bc14f0-2ae4-454b-9521-51548355a855)

### What does the proposed API look like?

Now I can draw various function images on a canvas, but I also want to implement a four-graph mode, that is, I can have four places on a page where I can draw images, can you give me some advice or help? Thank you!

**Comment by helgasoft** [comment]
like [THIS](https://echarts.apache.org/examples/en/editor.html?c=scatter-anscombe-quartet&edit=1&reset=1) ? use [grid](https://echarts.apache.org/en/option.html#grid).
![image](https://github.com/apache/echarts/assets/13038071/b537a1d5-1e0c-4133-a3e1-45cd2b29af38)
