### ISSUE TITLE
[Bug] xaxis min is not working for 'time' category [Bug]

### ISSUE THREAD

**Issue by OliverAndersRWE** [apache/echarts#18745]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=dataset-simple1&version=5.4.2&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQQIZhsDOWYTV6AhAC2-LlGhcSAbQDkOAE4QCs8rFltV6gEayAupXTouwAK4KAxlhkCjqIw9iLlJWQCYADG4DMAWg8AbP4AjKq2DhqyJMHBbgB0AQAsho7osrrRwYlxbgCc4bAsqfapTkrE6p4-_gDsIWGl6prRHtm5KanpUbDBgXEArAVFjiWpzhXuXn4eABz1HY6RLd4DCxEZPR79cVtDa8gF6OOuVdO584dN3b3xNftpG73ZbnsFo47HlVO-vReNS5t4lsvLkAv1EsEAjM3PcdNcPCt-jVvAFAgEah5cv1vK9ipdPpNqjE_qUATcdqCZlTvDNcpiArCussEsFvP03DNvDEYjNcSN8eUTt9YiTOs1AXE6Rzgv1Ark3G5gozHq04iiOWCPMEavL8qlhg53g4CVVEiFRYtxU8cv0ZolvDqPMiOcr4dsAtrcg6agFvPKanzDQKXF83GavBaIlbVXT-vLEjN-rKIa6WgE4jKAuifHbvIkAoG7MGJqb_NNQozo9lff1fTUfD6uanNtsajVsbTE9q3AH9fsjUYTV5w-GK5cyQiEg71YlkfnvM3rejM_WOZjBn23sWhWH_P1I0YJytWrlobL68iF-OVdkER40VTa5jC-gB0dBaHw0EtQ1SdHjwE0phh2rSLqqrScmCVKAViL4HI0Q67k6B5pP-CRJhi9YIiiMxgdWtI5rkELOnBb5lCGhLhnMP6VvC2QYgmEEQrWYGtnk3h5t4ip-r2jgGkWCEfpR_jnDR47RumwS0gmOpJk6MLXvCNQZlyiRuOiOG8Q4_Gvtun4_B4KFXC0ym5DEUI1LO0IImBMxxDUkLarS97onqfH9npwnEmJ_zRnZUJ5M5kLtrhiktLkcSJE6tYYjMOpudpHmCRRpYij5f7wnZ3hbFxbLAjSYERV4gHglqrJcqRnlVPuWpGRO6ZemZHG1lBoX_CqymrsE8oxF6UKVclJZeDVbh1dG2zgphiREepOpgemfqyqCTyzFpRg6fBpSITV5a_mKdE5LScbDVCLFhS2GZEWZdpZDKwQDVtQnVf4o57Za8IrJCWayZivV4RmipgnS021i8m54oNO41TVY6-fC8ROXm6m5ERATtOdvSfe2XIzFqCLdQ9YxPcN_jfrDGUtMEarATq0KOskGNeGqSZHXkSQ-ITHzE24NV1Ol-0tB4CQ5XS0lqf0YFU1mHF0nSNRxWD7lbpDoY1dR5MC5sQteE6IUo9hksUvLTH5v14P8irhI1aJGvvSQKMDJheY3fWHpgULQOsg5gS4wl61JY9KUk78_N27ADs8-y6KrrKSLu2qs40j6M25Gt6AbWR20_MEY3dA7Tr2pZ4Je1k8eQpHWZOqy93m0GlvPWlttRnnRVrkmgW5Qp7XwkLTxJDSiTYrEnPGtzZO5_bRWp5ZvQIiFDKM73oOJraCrsiPg5j_4o2h83k8Zlh2pYYEKLx9xgWJrmaeFAHRNB-pZYT-HEU-D4kKD42ceLzanLdXa9a8lrgJQOQ0H6tCfhHeWdZAazmmmfJqCZwRxUAUrCGICdzfhhm9Pez81S9FTijUEtpWTxy5DmaaME_Qb3fPfb8ZNsGHnFA7LiXpEizgIUg0hio1Ki1Tkiah5FQHfj5k3RhLc1QcWROXLYWIGbd0Fngu0vs8ivwEYhb86sGGoXEVxCEUV8yD3xqQhEpUEysjBGoremIIERWylsByLD0RtVJCqIWPZK5tnzDKa-GcqrFQMjYnIvphyA1iGfB0AV6wokCJY2h2dAmKiyCjWINIVFlxmOiMEEIHRZFiUIn4O9RHaP3lkOMoIthtzkS4nuAMaQs3figxKyt0GhhEYEqu01YhOjpFxeOOV-5sN6n7dOt8ub3z5oUrRxlcFanlhCGYUkwycj6a0dS2J7T9zyTuPmu1aL2zsvrYcswMlYi7tU_ep5WgxGwr0JIWzWkvQgQcqkCJcbdTDAVc6DtTyeFxktW0RF7mEj5lgvZMyeSQUxNJM5nRXE7ExD2b02V5RAqqHzehYL84eifBkwI-YYWLDhYEbqosfAekSKirwfMRFTIBA7L2co2wynvEqb-WQphfRiLWSlPZ_CaMxS_AemM1KDy_vIrWOR7Qo0AomByjT_bNLvqAvmNtaVMNsWCVeSI2QkO_tODk-ZU55GGTfRVYzlUBN3mI_e_QpK2iSA6-s8d2S-yhFiE1vj65UviVa4puC0aWQVFqOMLD46xXtByBZ7Ia6oIti04FBTAlSlmPKHseRwTxzMjwtZEIPQ8vVk_WeAMuwcQybjO4jMqa3U1PmCpMamloKVTuaikywVFrZAqfFCpsaGxRDWJy3SCxAN0l6jkj9fXTKLbWHq2U37ONhfCKmtpC6zA9G6_NjyJ0TiFm2IiXsXlUkNrJTCGIuSpw3VsQt95JTQiUbayy8swJAnvOqbK2JFQXoxeJRdB8sTdhiHmdG4ryR_w4qbXGebh2bSbaGaiNK21ajVGjCEp4A1eCfWqWkgF2G3XlSMs1o977UX5d-ymAx2RJiSPKbEEtGbxCRGpLi6JsQetGYR0B1FVUIapgA_03SuwYfbIqW0Z6CEbpDkUydiHOxD19O_CtwGmbyjzLMnmUkcRQcztzOY3lJMTiBB6B0Wp2E8zAseOKoIORmXvBSzTfix2NzVfDHI2o2HqQ1ImMzkrl1SVcxCHlNsr3xBRDqJIdp7SssUysP00JGNJFWgF7eQWBinFug5MJjNETsiTlCRMXhEsImS8xweCzXOWS8xiIiCzNQ9jw6axt5qdyiVegh-InIURsKIixhT5zNgrBOeyEVe6h2xrrvGqoolQWkYlCjHDdJjmRd69aBEamkFxkhAVr9cNmQyipKeU8fp1L_T_qKtk086uevGyCWoV7os81BB6LrTZGbZBC5xOKs9FYNrjTBwkokSPbb65Fd1Xp31o3nYSg6LHfNaixHFArXHpuYwSG632p5xb_QcQ9v56zEsSac8ycL8pExmQcf9Wk2otQKipGpPHOct1Vh2DmFEZDQasR2FEu0VnbUadG8A37E3E0M4Op4JEVzUSp0Wwulo2weaohlKedsg9KXZXNMLlor3aTInZGSpI7PBm03UjretCqGvsaFKriM6vNjZCRDERinhU7s-wzNKRWwNx85HVdy3uykeqkslm2sfoPRS8hzLuIuN8w8-nD4tjm8g6W5a37toDY1yyUPYzbYlz4zdKyLZz30HGtfEt1NwHvRtiYgTFiFTdJQ_rHhJJbEPp1x1gu3HmhQ1LdbYphddzSRA1slo4phab9Hto3kirwyyFrfl8isjXMPZ1nzUihTnsMRVyx4I_HzvU-Ac99n7aR0qIXUZsZumMEkJaxRVmP5uzXrLeI7L1seyg8IT3b_cvhZBdTwko23f73hk-OCG2wtIWICIoI7YWoy-D2UUyIlkyu_-Aud4PqemEkOwsoUkwakSYEykPIMEeKbCHu32Y2SBqujmCGkkqcgywUcCjMyks0eie2rGW-HeFu9O7BBOsAHgzYHgKu9Ora023B50vBiBRekwXI46qB3QQh4qIhBeWmCe9OSegOMhvWchxB_OYhngEhl61uqh0uXBfBpMT8-hYehhoh5uxe9O8GghPBRhswJhdhFh2-bBIkjhwhRhQBthHhzhrBVhKBnBph9eJA6hpuP2Wh-MQuUhIRTh8hfiXEau0RXBsRGhXupBO8AhKhKRYRJBERCRhWeh2R-GZuLhxeO8yhPeQRh4GwoRxR4Rlh4hO8pelRRR9W9RpRjRxhhRPhcR9-O8NhWRPRqRheDR2hO8e-msVRDw0hKuO8j-LRQxORmhoxK2lqSRUxcIIRsxARYKGxTI5hvR3uo05B3hshKu5Y7hZxvhgiFu0wmRCxVxhxpB0wvugxjxwxChne0wFRkxrRl2zxe4lxah5xXR6xfx7eNxxe0wAxDxwJ1xQ4HEfKQJBhtRbRuRKxiJ1i3R7xSxaReRfgXhbxcJTx-JOxpxxJHx8RBJ9xvxixdR6JHR2ho4yJZhqJ_xeR4YNJYcexNRKu4YrxsJKJfJm6YJdJaJyxjJCI4YzRtJOJ9JEpfh4hX4LJwRBxlJ9-4YMJspFJuJIxkpeYSJ2JOp8peJGJ4Y8x2pQp8JxMBphJgprJwpumgR4JLBkJSpURzpYp7JGJMMKp1RMx1pCeI0fp0xWxgZneO0IZmxapupnxFuNUPx3JLpJRip2h0MUZ-xbJEJCJNU3elpDp4Z8ZN2RpVpJJPphpopcp4ppp-p1sGZvJhZxe-4dp-ZqpWZrpOZZJRJpZ6p3uzZXJOCPJAZZZ-p48JZBZI5qZCI34A51qyRXp2ZNp34AprZ_pYZk5bp2h34iZg5yZ7RU5KIgJ45bZKudC9Zw5vZpBwi5565l5eRGiN5MZJpepB534FpSZC5HZS5axnpVZ3po5XZ9pJ5jZ4hQQJx3ZE5d5GJbSx5a5T51ZL5m5c8SWsFoZ8F_5B5Oyj57ZKZSFDoIpv5xpCFcZxeIK2FQwtgegVAwwAAHgAII0UQBSDIDUAACeIA1g6gkAogv4wwrFDFTFTAwwAA9MJbAAACJYAWAYBsAKBYCwA8AABuWACgbAGAsA2gslClKlEAWAXAagWAbAFgAAFrAAAO4QAYDqXaDyXCBsAgAcUEBUCiXUDACwBsCwAWB0CmDCBwDAAABmsA7AnAPAYAcQJg5gVgGlrFQVWA_lbApg9AcQVAPASgelMgSAbFHFrgGAEA0AWAsgN8LFYA7FnFsguV-VhVpAVFpAAA3EAA

### Steps to Reproduce

follow link above. the minimum xaxis value is wrong

### Current Behavior

* min value of xaxis is wrong

### Expected Behavior

* min value of xaxis should be smallest grid value

### Environment

```markdown
- OS:
- Browser: edge
- Framework:
```

**Comment by helgasoft** [comment]
confirmed - the feature ["every series will auto-map to each column by default"]( https://echarts.apache.org/handbook/en/concepts/dataset#:~:text=Here%20is%20a%20simple%20dataset%20example) does not work for xAxis 'time'.
 [Official example](https://echarts.apache.org/examples/en/editor.html?c=dataset-simple1) is for ```xAxis: { type: 'category' }```, but there is a problem when _type: 'time'_.

**Workaround** in you example is to either change xAxis to 'category', or do series with _encode_:
```
  series: [
    { type: 'line', encode:{x:0, y:1}, name:'first' }, 
    { type: 'line', encode:{x:0, y:2}, name:'second'}
  ]
```

**Comment by OliverAndersRWE** [comment]
thanks for the confirmation and the answer.
