### ISSUE TITLE
[Bug] 柱状图 data: 为特定数字时 显示没有铺满少一截

### ISSUE THREAD

**Issue by xiaozhaorong** [apache/echarts#18762]
### Version

4.9.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurAB6EDkADAKQUA0sA9E7IGe6gL6mC7scegJ6VaDZq0BQct15kATILqMWsQM_KEkrD4zY1OiNiBoORUkFAYxhgAhhGgAZMwCMApgBtCAMzOOAzveIBfesQUADUAXeOJSAEFSCA9CJD9iPkjowgBtSQU2QHL5AE1Q1VRVdFwzc1SKQG8fQGj1CgBdSR9iGv90BUBvn0B0JXbACwjiLxx7GNg0_Ml0MD4Qe0pbMywGUdhoMwBbKc1AKnNASGNAN9NARh1AXe15wp0PcyMAa0owYHNHI8KZrABZM1IAdTwwAAtCKQAWZqFRx2JyxBboDxfYAAd0IYCwAFd7IDjiBgB4IJAYJRLBjcPYKAt4sdiqUhgBOOqqBroOo-ADcQA

### Steps to Reproduce

![image](https://github.com/apache/echarts/assets/41188311/b6d5dd4f-8116-461e-98b2-a715bc173ced)
![image](https://github.com/apache/echarts/assets/41188311/6d79527c-7352-44e1-b215-458df4fca9bb)

### Current Behavior

复现的链接

https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurAB6EDkADAKQUA0sA9E7IGe6gL6mC7scegJ6VaDZq0BQct15kATILqMWsQM_KEkrD4zY1OiNiBoORUkFAYxhgAhhGgAZMwCMApgBtCAMzOOAzveIBfesQUADUAXeOJSAEFSCA9CJD9iPkjowgBtSQU2QHL5AE1Q1VRVdFwzc1SKQG8fQGj1CgBdSR9iGv90BUBvn0B0JXbACwjiLxx7GNg0_Ml0MD4Qe0pbMywGUdhoMwBbKc1AKnNASGNAN9NARh1AXe15wp0PcyMAa0owYHNHI8KZrABZM1IAdTwwAAtCKQAWZqFRx2JyxBboDxfYAAd0IYCwAFd7IDjiBgB4IJAYJRLBjcPYKAt4sdiqUhgBOOqqBroOo-ADcQA

### Expected Behavior

https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurAB6EDkADAKQUA0sA9E7IGe6gL6mC7scegJ6VaDZq0BQct15kATILqMWsQM_KEkrD4zY1OiNiBoORUkFAYxhgAhhGgAZMwCMApgBtCAMzOOAzveIBfesQUADUAXeOJSAEFSCA9CJD9iPkjowgBtSQU2QHL5AE1Q1VRVdFwzc1SKQG8fQGj1CgBdSR9iGv90BUBvn0B0JXbACwjiLxx7GNg0_Ml0MD4Qe0pbMywGUdhoMwBbKc1AKnNASGNAN9NARh1AXe15wp0PcyMAa0owYHNHI8KZrABZM1IAdTwwAAtCKQAWZqFRx2JyxBboDxfYAAd0IYCwAFd7IDjiBgB4IJAYJRLBjcPYKAt4sdiqUhgBOOqqBroOo-ADcQA

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by lixingjuan** [comment]
1. 通过设置`containLabel: true` 可以看到目前x轴的数值分布，可以看到底部x轴的最大值为10，平分5份，所以柱状图没有铺满；
2. 如果想要实现一直按照最高柱子铺满chart, 可以使用
``` 
 // X轴
  xAxis: {
    max: 'dataMax'
  },
  ```
  表示x轴的最大值，按照当前data的最大值；
  [https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurAB6EDkADAKQUA0sA9E7IGe6gL6mC7scegJ6VaDZq0BQct15kATILqMWsQM_KEkrD4zY1OiNiBoORUkFAYxhgAhhGgAZMwCMApgBtCAMzOOAzveIBfesQUADUAXeOJSAEFSCA9CJD9iPkjowgBtSQU2QHL5AE1Q1VRVdFwzc1SKQG8fQGj1CgBdSR9iGv90BUBvn0B0JXbACwjiLxx7GNg0_Ml0MD4Qe0pbMywGUdhoMwBbKc1AKnNASGNAN9NARh1AXe15wp0PcyMAa0owYHNHI8KZrABZM1IAdTwwAAtCKQAWZqFRx2JyxBboDxfYAAd0IYCwAFd7IDjiBgB4IJAYJRLBjcPYKAt4sdiqUhgBOOqqBroOo-ADcQA](在线效果地址)
  
  [https://echarts.apache.org/zh/option.html#xAxis.max](相关api地址)
