### ISSUE TITLE
[Bug] Bar chart value display on cursor is strange

### ISSUE THREAD

**Issue by edosong** [apache/echarts#18766]
### Version

5.2.4

### Link to Minimal Reproduction

Code is attached

### Steps to Reproduce

 Note:
Part of data in xAxis and yAixs is deleted ( totally 1000 points)
The following code is embedded in a HTML file.
 
<script type="text/javascript">
        "use strict";
        var chartfft = echarts.init(document.getElementById('fft'), "white");
        var optionfft = {
            title: { "text": "fft" },
            tooltip: {},
            legend: {},
            toolbox: { "show": true, "feature": { "saveAsImage": {}, "dataZoom": {}, "dataView": {}, "restore": {}, } },
            xAxis: { "name": "Hz", "data": [0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.5,13,13.5,14,14.5,15,15.5,16,16.5,17], "splitArea": { "show": false }, "splitLine": { "show": false },},
        yAxis: { "axisLabel": { "show": true }, "splitArea": { "show": false }, "splitLine": { "show": false }, },
        series: [
            {
                "type": "bar",
                "data": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.54,0,0,0,0,0],
            "label": { "show": false },
            "emphasis": { "label": { "show": false } },
            "markLine": { "label": { "show": false } },
            "markPoint": { "label": { "show": false } },
                },
        ],
            color: ["#c23531", "#2f4554", "#61a0a8", "#d48265", "#91c7ae", "#749f83", "#ca8622", "#bda29a", "#6e7074", "#546570", "#c4ccd3",],
    };
        chartfft.setOption(optionfft);
    </script>

### Current Behavior

![image](https://github.com/apache/echarts/assets/102741813/1513be2a-b66f-48bc-8e08-d6517a4e2ccb)

when hovering the cursor over the data bar, a rectangle area is shown instead of the value.
![image](https://github.com/apache/echarts/assets/102741813/90683471-3571-4736-89de-f18253b8418b)

![image](https://github.com/apache/echarts/assets/102741813/a17d4078-0ee8-4923-95c4-3ebb14bedfd6)

### Expected Behavior

Value of the data at the cursor should be displayed.

### Environment

```markdown
- OS:Win11
- Browser:Chrome
- Framework:None
```

**Comment by edosong** [comment]
Hi
Apologize that the issue could not be reproduced with the official editor. So please drop the issue.
Best regards,
________________________________

**Comment by vikas-6** [comment]
**
![fft](https://github.com/apache/echarts/assets/136149011/e2558371-7c72-4da6-b00b-0c0fe6eca9c5)
Hey, myself Vikas! I've just fixed this code, and you can check it out right here: ( https://codepen.io/VIKAS-KUMAR-the-vuer/pen/OJabqyg?editors=1000 ). Feel free to take a look and let me know your thoughts. Happy coding!**

**Comment by edosong** [comment]
Hi Vikas

Yes, it works perfectly.  I've read and am practicing to follow the eChart coding rule. 💦
Thanks a lot for your help.
Best regards,
ed
________________________________
