### ISSUE TITLE
[Bug] 为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊

### ISSUE THREAD

**Issue by sugar258596** [apache/echarts#18774]
### Version

5.2.2

### Link to Minimal Reproduction

。。

### Steps to Reproduce

为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊

### Current Behavior

为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊

### Expected Behavior

为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊

**Comment by Ovilia** [comment]
因为 tick、label 等的布局都会用到。formatter 原则上应使用纯函数，不要有副作用。

**Comment by sugar258596** [comment]
虽然不会有副作用，但是只有一条数据的情况会使y轴上的值出现重复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenli ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/echarts] [Bug] 为什么在数据只有一条的情况下yAxis属性下axisLabel中方法会被调用六次啊 (Issue #18774)





 
因为 tick、label 等的布局都会用到。formatter 原则上应使用纯函数，不要有副作用。
