### ISSUE TITLE
[Bug] 国内用户访问不了，怎么办？百度这么优秀的一个开源就这样把国人

### ISSUE THREAD

**Issue by 315xiaoyao** [apache/echarts#18772]
### Version

5.0

### Link to Minimal Reproduction

https://echarts.apache.org/

### Steps to Reproduce

官网打不开，只能翻墙才可以，怎么弄？开个源是好事，但是太影响国人的使用体验了，慢的要死

### Current Behavior

访问不了

### Expected Behavior

官网打不开，只能翻墙才可以，怎么弄？开个源是好事，但是太影响国人的使用体验了，慢的要死

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by imyxiao** [comment]
ECharts现在在Apache孵化，用的也是Apache的域名及服务器，服务器不在国内确实偶尔抽风国内无法访问，这个没办法。

**Comment by Ovilia** [comment]
> ECharts现在在Apache孵化，用的也是Apache的域名及服务器，服务器不在国内确实偶尔抽风国内无法访问，这个没办法。

是的，这个确实我们没什么能做的，镜像站也是不被 Apache 允许的。
