### ISSUE TITLE
想要把水球图放置到geo3D地图上

### ISSUE THREAD

**Issue by Yang907** [apache/echarts#18791]
### What problem does this feature solve?

自定义3d地图撒点标识

### What does the proposed API look like?

type:'liquidFill',
data:[
{
name:'名称,
value:水波值
position：该水波在地图上的地理位置
}
]

**Comment by Ovilia** [comment]
This is not supported for now. If you are interested, you may dive into the source code and see how pie series supported coordinates like map and then change the liquidFill series.
