### ISSUE TITLE
默认的label样式不统一 

### ISSUE THREAD

**Issue by xiaoqufengdi** [apache/echarts#18809]
### Version

5.4.2

### Link to Minimal Reproduction

https://github.com/xiaoqufengdi/echart-demo/blob/main/demo.html

### Steps to Reproduce

label显示效果不统一

### Current Behavior

label显示效果不统一，字体颜色和粗细不统一
![image](https://github.com/apache/echarts/assets/31072438/d83ab382-0ed1-43af-9789-1c27ed0cbdd6)

### Expected Behavior

label显示效果统一，字体颜色和粗细统一

### Environment

```markdown
- OS:
- Browser:Chrome
- Framework:
```

**Comment by plainheart** [comment]
可以手动设置下 label 的 color，默认会根据背景颜色增加白色描边。
