### ISSUE TITLE
[Bug] gague display abnormally when the value is 0 in Vue3

### ISSUE THREAD

**Issue by penguin0731** [apache/echarts#18810]
### Version

5.4.0

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/friendly-varahamihira-pwr3ff?file=%2Fsrc%2Fviews%2FHomeView.vue%3A2%2C8

### Steps to Reproduce

1. when the chart inited and the value is 0, the axisLine is none, and when you hover the chart, the axisLine will be visible.
2. change the tab button can show the bug again.

### Current Behavior

 the axisLine is none
 
![image](https://github.com/apache/echarts/assets/39406604/1ea3eb95-94ee-40c9-88e3-aedd8dcb3237)

### Expected Behavior

show  the axisLine
![image](https://github.com/apache/echarts/assets/39406604/bcd8c26e-b788-4a3e-ad71-08f5e4c2c0b8)
 

### Environment

```markdown
- OS:macOS Monterey 12.6
- Browser: Microsoft Edge 114.0.1823.43 
- Framework: Vue@3.2.37
```

**Comment by penguin0731** [comment]
I tried running this demo in Vue2，it looks normal.

**Comment by plainheart** [comment]
Please refer to the [FAQ](https://echarts.apache.org/faq.html#others) to see if it can help you.

**Comment by penguin0731** [comment]
> 

Thanks, It's already resolved

**Comment by penguin0731** [comment]
> Please refer to the [FAQ](https://echarts.apache.org/faq.html#others) to see if it can help you.

Thanks, It's already resolved
