### ISSUE TITLE
[Feature] When generating a scatter plot, I hope that each scatter does not overlap

### ISSUE THREAD

**Issue by kanxingyv** [apache/echarts#18837]
### What problem does this feature solve?

I encountered a problem when using scatter plots that I don't know how to handle
Please refer to the picture
![N{5C6KK8W9J1R9_UA%7A0 I](https://github.com/apache/echarts/assets/40993148/7d7812a4-8e77-467c-81eb-85ce01454803)

### What does the proposed API look like?

I hope to determine if it overlaps, and if so, regenerate a new coordinate that does not overlap
![image](https://github.com/apache/echarts/assets/40993148/51f83c9f-4192-4cf8-8354-527054812060)

thank you very much indeed

**Comment by Ovilia** [comment]
This is not possible

**Comment by kanxingyv** [comment]
Okay, thank you for your reply

**Comment by kanxingyv** [comment]
Okay, thank you for your reply
