### ISSUE TITLE
[Bug] 通过拖拽功能，我修改了横坐标或者纵坐标标题的位置，但是点击事件失效了，有大佬知道嘛

### ISSUE THREAD

**Issue by LBJDJW** [apache/echarts#18831]
### Version

5.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

//我修改了svg中 横坐标标题的位置，点击事件失效
if (clickType === 'font') {
			myChart.on('click', params => {
				console.log(params, 'paramsparams');  //这边无法执行
				onClick(params);
			});
		}

### Current Behavior

//我修改了svg中 横坐标标题的位置，点击事件失效
if (clickType === 'font') {
			myChart.on('click', params => {
				console.log(params, 'paramsparams');  //这边无法执行
				onClick(params);
			});
		}

### Expected Behavior

//我修改了svg中 横坐标标题的位置，点击事件失效
if (clickType === 'font') {
			myChart.on('click', params => {
				console.log(params, 'paramsparams');  //这边无法执行
				onClick(params);
			});
		}

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by LBJDJW** [comment]
好像是点击区域还是原来的，我拖拽的时候怎么更新点击区域？

**Comment by plainheart** [comment]
Duplicate of #18833
