### ISSUE TITLE
[Bug] When the calendar pie switching month, if the month at the beginning is 30 days, it is displayed normally.  When switching to 31 days, it will be switched back to 30 days. Switching to February will run 3 cake maps, but the month when switching back to 31 days is normal

### ISSUE THREAD

**Issue by hlmyhjs** [apache/echarts#18832]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/spring-wood-nn2xlf?file=/index.html

### Steps to Reproduce

create chart:
  <div id="chart-container" style="height: 680px"></div>
  <script src="https://fastly.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js"></script>
  <script>
    var dom = document.getElementById('chart-container');
    var myChart = echarts.init(dom, null, {
      renderer: 'canvas',
      useDirtyRect: false
    });

### Current Behavior

When the calendar pie switching month, if the month at the beginning is 30 days, it is displayed normally.  When switching to 31 days, it will be switched back to 30 days. Switching to February will run 3 cake maps, but the month when switching back to 31 days is normal

### Expected Behavior

When I choose the month, The correct display of the calendar pie

### Environment

```markdown
- OS:Window11
- Browser: Chrome 114.0.5735.91
- Framework: Vue@2
```

**Comment by plainheart** [comment]
The series data will be merged by default, so you can disable this strategy via `myChart.setOption(option, true);`. See also https://echarts.apache.org/api.html#echartsInstance.setOption

**Comment by hlmyhjs** [comment]
thanks for your help!The problem has been solved. 谢了昂, 牛逼老铁, 6666

**Comment by hlmyhjs** [comment]
> The series data will be merged by default, so you can disable this strategy via `myChart.setOption(option, true);`. See also https://echarts.apache.org/api.html#echartsInstance.setOption

thanks for your help!The problem has been solved. 谢了昂, 解决了, 牛逼老铁, 6666
