### ISSUE TITLE
[Bug] charts with grid option show incorrect position

### ISSUE THREAD

**Issue by dontworrywearetogether** [apache/echarts#18840]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/embed/basic-line-chart-forked-7mfz5h?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

maybe is my Bad configuration code is here：

```  const media = [
    {
      option: {
        grid: [
          {left: "10%",right: "50%",width: "50%",top: "10%",bottom: "10%"},
          { left: "50%", right: "10%", width: "50%", top: "10%", bottom: "10%" }
        ]
      }
    },
    {
      query: {
        maxWidth: 768
      },
      option: {
        grid: [
          {left: "10%",right: "10%",top: "10%",bottom: "50%",width: "20%"},
          { left: "10%", right: "10%", top: "50%", bottom: "10%", width: "20%" }
        ]
      }
    }
  ];

  myChart.setOption({
    option,
    media
  });
```

![image](https://github.com/apache/echarts/assets/73633325/1b74aeb6-fb6f-49ee-8b55-3712d57cefaf)

### Current Behavior

charts line and pie is incorrect position 

### Expected Behavior

charts line and pie is side by side

**Comment by dontworrywearetogether** [comment]
> Please minify your code and be more specific about what's expected and why.

yes

**Comment by plainheart** [comment]
@dontworrywearetogether 刚关闭了你重复提的 issue。饼图不能使用 grid 组件，因为它是直角坐标系绘图网格，只能绘制折线图、柱状图、散点图，饼图则不支持。你需要使用饼图自身的[布局属性](https://echarts.apache.org/option.html#series-pie.left)（left/right/top/bottom/width/height）。参见这个[例子](https://echarts.apache.org/examples/editor.html?c=pie-simple&code=MYewdgzgLgBAtgUwCYEsCGMC8MDaAoGGAbwMJhAAcoVwAuY0smAcwCcUl78mmSeeANggBmUegHIAjAAYApOIA0jfjHbMAFmJjiArHMXL-Adw5R1EvfKUqyUShJlXDPAEYgoduA_3PCAX2cAXWseAHpQmEAfTMA_tUAD00BVm0B_eUAKVxZ2JGcIBHYECC5fBhtCMDRECQBBYGBciBgAMVYQOAMimCFRC30QmzVNbydWkyQzToGiuwp-lqK3DyapgoD-QOUlmD8QvjIARwBXbIBPei2mODQADwB1U3MYAHYANgAOVe7yKhowY-c2DnybE4qdpaKRdAqEXogxzTGwTKZvfizTyjGEqIYjbQAJh8NjWTGCznCUTiSVSvwy_CyOTyuAKgP4JTK2kq1QgtQaTVR_GB8PBqhQGihYNacO0li5rncyO00IRPHRt3E2PkiyCq1IAUCAG48HhKNRwFhCjAXGgsgB5D50Y2Ecn_Hj0sg8mXClSQlFywgKj0FUWgsaIqXzF0q_h4mAEpjncrnFA07gO30HCgICTANBQBDMECsA4S4qlBAAGRA6YNX20cA4SCE4mc4cjZAOMbj9t4BUZqe0SDQB0zcAodbDykbhCpKFybbIjsIPagaC4kj0ChgmIAzNIV5jMQAWLeSJ4ryRrnRHnd3LcPaSjnhQZNd8QCFBgBBDngbZwzmCdipVGr1Rpmk9GA7xTCQKAnfNVDQVBdnjcQdy6bQ7n0G8mDnBdaVaIgYAANzQAR9noGQd0Pb9CwkABlBA0FYYB1BgABRMBmGfV91mAwgcPwwiuzuE8Vx_bQABEUFYBBgCgcQOL5biCKImAdCeTdyKZcRGLOFABGkj9sLw-Su1IvdVIfABVMBPhgcokAgHTOOIfTePoDcVKE8QADUOAQEArJsnSChWYd8Q1EJEFQNA8D8LUgA)。
