### ISSUE TITLE
echarts 设置datazoom后 下载图片 下载不全  只能下载可视区的

### ISSUE THREAD

**Issue by caoshunshu** [apache/echarts#18846]
### Version

4.9.0

### Link to Minimal Reproduction

1

### Steps to Reproduce

设置datazoom
下载图片

### Current Behavior

下载不全  只能下载可视区的

### Expected Behavior

下载完整图片

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This is as expected.
