### ISSUE TITLE
[Bug] 按需加载组件PictorialBarChart，手动设置resize宽高足够小的话会直接卡死页面

### ISSUE THREAD

**Issue by eeyyyy** [apache/echarts#18849]
### Version

5.4.2

### Link to Minimal Reproduction

none

### Steps to Reproduce

手动使用 `resize` 将象形柱状图改很小的情形会出现直接卡死页面。
![image](https://github.com/apache/echarts/assets/137886242/0c588088-97eb-4016-80d9-290ccb6244ee)
![image](https://github.com/apache/echarts/assets/137886242/2b449faf-7735-43cd-a923-357f1aec9248)
![image](https://github.com/apache/echarts/assets/137886242/b531fb24-48e1-4bb5-b512-e93cd4d3b356)

### Current Behavior

宽高是相互影响的，都设置小一些的值就能复现

### Expected Behavior

 `resize` 设置图标宽高成功，不会卡死页面

### Environment

```markdown
- OS:windows11
- Browser: edge 114.0.1823.67
- Framework:Vue@3
```

**Comment by eeyyyy** [comment]
[https://echarts.apache.org/examples/zh/editor.html?c=pictorialBar-bar-transition&code=MYewdgzgLgBANgQwEYFM4GUVSgSzAcxgF4YBvAKBhggAsQB3ALhigCcBXFAGkpgAcQEHLnDMA5Kxz4aUMTyogAZoohZmAbQCMABi4xtAXXkxF4KOhwAvFM00A2cgF8A3OUXswwEWBgBbBADWKADyfN4AFFAAnnzc1FG-SCBwAJRkvKxY7Kw-FFRUuFBwNun5-VAoAB5Q4gBqKDQ4wMUQMHgwABowAMLCUWK8VI7GVMX4KGAAJsx5ZTCTCFAIGmIATNqaAKxyMGsbdmIGgzDDx1Agybh8M8cFkvjjrOIIlTgQcrcwL28ACiB4FSepTmBRiJTEtAQkwYAxBjmOpzK-Ek02BZVAYCWeAAMsg0Mw2JwRvliooarsdABSD4g-4ycRUmlzJLYEC-cQADm01OJiPyUQAgq8IDcQQslitMnhJigUKwdhDGnwFXxEGAUAq2Ag8ArgAh5UZPngAG5y1QEjjcT7fCDYvAlUjUOhMEwIOCqE7Eqg2gAqTQCMydDGYijdHr5ZRtuNQcFFIL8-vweGYAGZdJ8qKZMRZrLYACyfCP5G1_AFyuMgxAxivx2jBliWr1zfysJNgVPaDMnQsI4mVIVvGtUCCq4R29WBusu0PulCe63C6P4shB6dhudF73Cv3AAMrqch9fzkFR-2T52H2fdspFhBgHD-bwAEWyixw4AAqnxxSVNtp02UqiSCgIowOonyzCCYAIL44LrFsTIgjgqJiEg-qaIhczRLEBJgk2ox4rG8CEZg2B4Pg-HxIkyQAEooLEiwWkSXYQAkSQYFYJTqGIXI8rsdjcoclFoaw3SLCg-AgKwUQAOIINcux5oJlEeDgpqsBAbo-qwd5CN4Q5zBMyDFKihJWvG-QyogUQhh4Xjvj44TIZUejnEsqRohZMCZFA2SOc5MAAPQsCA7lpAAVDAOj_q4XnXvGm6WYsyxgV2VCQV5xpupwtibAA7JRgFsckzCsdRcBpceXkZRZWVwDlMCrJohX5GV7GlcVFVxYlZQ1fGdUNXYdgtcOnUdeVlU9fkfUggNJR5RyI1Ue1y3JJNLUzXMc22KsKZLW1JWrV1XnwhZRxwk2m3QbB4jwQclHIeIImrJhZTYSU73CfqckKWIjKUVWy6AxgWC4AQlEHXAdEMeSZkQ51OZcTxyn8YJhoWap6maXA2m6cIDkGWURlICZTHmV5VkIDZJh2d4MBOZMLkhWFnkWT5fn0wFwVuW6EVRf-2ixSdXZTeKKXgXFm1lNtUUcnm-1jUd62VVL-Qy6sACcCvleN7HK5LlVUDLeV7YbR262t3UbWbMsa81ZuQxbx0WVN6U29lJQa5s2srZDk1dudcynfkgcuE45AYtAMAgGEDmtCQEsJkEoQRGIfBNOckhugAQvqYgpMY_jJ7H4DhKhecF7wRchCXYBl-nXhSTgOd53oYiTM3vjgJM-fkAYrhZaw0e1wAklMVTEI1A_6iwD4oGPMqVJPgvkDHdMkGvcfqJv4AL1U_fkKoUBj4CdXhO4nh0-EaSzJHsA7z4G-1xA6iGLwuCwXvlQANTf7wD8ADpkTIQAaSWAJAP7z3Hkvb-uxBK8EjskFAoCQD4DLpAr-OwMHQJSFXKI3QaD6igAAo-KcHLhAfrg4Y_N_wpGcEAA](url)
这个bug和宽高都有关联，宽高都不能太大，这个是用边距挤压宽度来复现，但是本质应该是一个问题。

**Comment by helgasoft** [comment]
not-a-bug
There is no limit to your _timeIndex_ variable, so ```option.grid.left``` goes beyond '100%', which does not make sense.
When the value is kept in the expected range (0-90%) there is no problem - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=pictorialBar-bar-transition&code=MYewdgzgLgBADgQygCwMoE8C2AjEAbCGAXhgG8AoGGAJwFMBLMAE1tuoC5KqYByRFdgHpBAWQC0AJgkA6AOwAOeQBoJAFmkBWCQEZgMgAzyx-6QE55ANiUBmaRe3axt0_o1L151WI3T5piTDAknaWKnLyEt7S-qqySj6KXqbS2voSSrLS1toSQSam_kom-q7G0hIawfraVibWXjLWFhJ42r5aZaq6JhoWXiY6yiYKlSbyqun5aWJt9bKBMtrW1mWyEnEejuo5pkoW0dli-9qmqsBtsqpGw-7SqqorJhayuz6y9cESptbnKbIWMzuFiGWW-TjMhTaOkq-w0GnmwAG_TkGlURU0l0BGnk2iUbRKRhkXx-ZXsuOKDkB9Wu0XsgNMGlMpMMQVmpkcUNUo3ClQMlkBX1k4Oy1kCbWBaOG9zCbhk2LR6gmVjllgAwmJ5ECbNEchrynCwi5HJqYmEImd9vpDm0GeltD5tBEyjU3Cc7uZwd8EW17Z7lgKkr5VACoV8xMlvvJEdFDGV9M0qdpkSUvG15FayhUo4CHEzhrJHLDDrZZNztELbMtAnUk3GuejTtZ0RVdm0HrsTA8NHlyn5ARZTmV_M77sLKTbg4iijmyvI4YD_qmzPJArOmoD9EyDI4ZBFeRDIuorbosRIVjJYlZZs90bJN3jfDUH6koxdgQ-72i09LbBIcdqz3SZx5FFaMTjcAYrQfLkmxMGpJTMCQAU7YEey0bkLGsSJryFKEFAXUtgnqE8BjBYYM1mSlGiQrELABGQC20VcBl6MprHGIdGQXR1-yFRoNBPfFYhzeQhQGYEhzSdEtEcYpZGjBQO18eoHw0aw4jTHQH2edIDDPasUmsCDyigtp5RlLSLgqMJ2PkuDphYvMDm5CYaXtGk51yZ0Kk6M8h11AwsKHOk-VAtj4VnDoejo-lYx6D1K2WaMGiyUt0T6Qk7lCHpVCcu9uwpL8UgedFjzCaF0qk39YgM9MNPdK85D6W54yKkCrEVS5o16XFbHLZUzFNC5cvKnFvIsHt4xpe5kJSTcqlrAZROCSwAh7HixlyzMTn7RRnSWcFXAm4oYtmPxmyCgwDQGWQ-PKApoz_Sp8TPdEl0MEFVEMdElg0ZjokZdFrAKZ1sm05a4OsmQLDhaNWvSiY6ybN8QXLXSsuOuxUQffwaTSOJbFyq9tQE1QxV8UpOzUMJXIFR0ab_IjJzjflyORHJZKDR4Dg5FJvkenQyl6EEjKcm8a0iOSLH-1xjL_OJijBnpllKiJb1OR7mp9UwFbMHIfqTB8_25hRcjg7kzxBNStxSbGcv3LQ1rjPynnLZs51Jes6nvCk4eaqnJfKK4wj6WaJFcGz6h7ZZlE5HMI8J6ZKxeW4CydupzshkTGr_AFKz_MJyyjfQig_L4ga0vrembScfQcvntTvMTonWW4YYQpDTHJ0tJndIq1M51wmyPcYfr6PRylmtFFmxxp2UBIntVQ4JUVbO5Sj6_R6tifdiUNcZAkJ0fMhcAbLFdPqQML748X2YMJovclygLeI5CCp50kyaxqlvCpuvjIGKsnjBzTDFTs8IzTSyCNsCODEuThl7E2TIaRsLOFNJkOiXl8i3WdKcH6rE9LGXTOeIOshWi-A9IrbqphZqpCft8WadE172mwoZLuwA-pT1ND4GIlQSxpU1GoAE6gcTZiPEZVYPFkjYmUMBDkixmgPlcCeHhJU2x-QcHcEa34ZgJAZM-Bwq5N6yhCEKE-KkjyCxyCke0r9LATXBOsXqmhKQOkUEoE0_IIw3lSHcJMPZzC1BsU5K49JLilRio0Oc5CXgYUdDAdUUgISyh8MCSISTxi7AqM5SQDF3FqE0DoAAXjwJQXA4B4AQGAWgnBuC8H4MgIQogfT6ywpoRkeAZAFFjiZDQeAVpqyJMCfpRJfQUgkAAGRaUBOUjIikwBEOpCmTYzxmCgebDy7FpJYh9ms3mLgzhxhoXGdSmZKbRALGxUcckSJyBwcUUoBgJIPKZLYGIzcSjsNJEAumut4whhRAhR0nS-Zr3TKoAAEks4h8zFnJHeMoVZVoHFwQcNOOot0K7cjUrrfwqhkD4n-Akr6NjZSVnsDYZIc5p5vKaJSt-iLaUWFhcDMwKlWWWHks6Oi6K7DhPIhhcJNpLAQB6AA4VQTnhFUCTAUVfLA75XSmseklhUAktSEBKlN5WXfDRBy54LLNQ0KbOxXwfhJqUIODScOTkt5XLxu8GWat9DOn5ZmZ5MZtD9MyDkDYfLui-BTmMLSF47R-L9dSaC5Zow6w7OVD5AC3nCQpAZJYcaWInIQtSOMaweyhyFvOQl_YHgbjujQ2QqpoXsncD0cuprshWFZfcXqRrMI2E1IoUwLKGJLBUM4aW_TrGnN8Q4Cw_T1ADm5imKcJc0SCKkLcCIGlIbaChT26wsLGRZDRW09ShykSIrml4Hw383B9WVSaem56JBQuSM0LuIyT3WRqHYbQEy71b3iAomdexTF6liLsE-z1ILyR9LhOw2pqivLsAUSD6wjjr1kMgYISwVxBASMDacSxHx53CEyR0dxlU-GxCSXcPF8QeznsI6IyZDhHnxYrUw_Tfwg00epbQyBbD2DsqXdQRl0ipJoXY4MGRNALBpk-dQGgoJcYUB48oBdbCiU48MdYE83azu3U_LocR9gVDDTECahNmFpQSG2hiomTi7EsfMVUW6kxnrMqPLd_GbCEPiMkbIvVGiXFhUk-Muxv7r2LrOMZdg6RtkIm2AcC9Sw9hxJMWLT9TqEdxJFv6cqYY9J3tBF-6XVQ6GCzYNMV9_MDmKwp6eTzAudkMH55BjbashbGGFmGALYhGGi-1hQ_0EtYdS-lBMkW0uEfkJl7EuXt55cIxWpC689UldlA1irUhp7LaC19eQ3aAZnqa9WULGFuvPSBPhwj3ZZzfRdV1wbC8eXpfG9ltK130sJOyKCWRJWTVXUc5VtzO2bBNZZcgkaG2WQupaxhbEsXOtAnAx1-L-srsncG6w4Ma8OuyqeNXSL29ys48rfsdigXFs2GB8T37SyYg1eC7CiYBxqebcRAd0krFIsw-DMdjHCPyS3aUpg3nuWxtY8e7j9Ht1VRdCyFfN7ig3B06tOT1b7hAoM7qwsuEhHqe9D-j2O8nMHgAuFrOY50N4OzFiHm3tS1Ttwm0_8YI7w3r_FZIUhW_ZMNDNgikZqjQagJK0FLwLBhwmojsK3N76kmwa4AwDzQMMSllKoFAagCBGC1O4HwJAjThAiGeFkIyNhbCMgsBMvPywz1F5oZNaYbIcxqXBI6FY-cjDqEGMh5Im4LAADcqhIZPQWVcHhga95mNrJk2wugzBEeP4qq63RrC79YiY2gu8On-JxzUkfgDiNgvJrk4GrRuGSEmSIa-LDIeKOsAyW9ZpNF1jsVYAkfphh9DDUvX8C_LE0DQ9_-eK_f-ZQWXWAhAZyWGQ2MR7wnw42MQADUNslgWUfA1Bds_FRRwCj1IDZ9OMj04DOwECFk6dcpeo8DrB0DUhVBMCkxoCcD4CN0CD4U6VaCyCYhKCuhsDyDcDUD5kFkkxNBpQSVFxfgkxd9g8hxW5RDg84DiNTAYDskzw7Icx4F8hGYJCLle8IUEEkJzsfQSoXUnkQR_B6JaRD0t4YBF86gBIu9jEpwdCEJDCwhP19CHDZAIVeDURVApkpN-Dhg-hYVN8VY5t1gJB2DXAu8oCIV_DrBZC9M1hYUKM4hAi1gQi_owjZ9XDohRJojn4JBYUEN7QskYjgiICoDmCNAsigjcjkgtD3ALhzBkABwsgtBF9nINCqiYYYDJcXgttSkuAIBkB6A4B2B6ks8mkRAX1nhY5kFLBkAqVUQRk5AoIfB2RchpCBpXI8QfQDRiMnt9hGJ5MLAt4OEpd6pxhdM1kCYUQ8QcpcR-8Ui8ix0xBtgdYHdMIe8T1HQJkv94ZrETgkNR8soJlw47hkYkD8VHjNBlhB1J5G1ewx1hh_w6guQpl9gJi8QpjACRBcoIMZcyY8BihYgjZ3hATMgHhEV8hzA8S5BWM34PCsTG1vwWVaU0sHRWhdxzoO0WhL9dZ_hTBPjZk0tjhPimS8QHQ_MfMNJ6M_oZigwHizJMNyU-lPhlo2w6jZgCxKS1heZ-NkM9JrB-keg1IlF1J9S-DOYjI_jETKTRZSRxgdSW5FS6gKUngD50DYhrBATxS8RJS_MuN9EgSJiTSUxSoYhkAHlVBZCngFA_MREC4CMrM7TjwTSCw14jJ5BkA9JeSCkIhY5NQrNuDMSM4z1W81MZhdxKhkF5psk1h8MJ1ngnAjVLlrEtBQNJ55N0xdgO9Y49Mf5BFe0CksI0MC1h5aRIg-o0Vg0jBKwoIfV1Jzg3hYMS5d0g13BcyeV9BKT_lwTwJyFYgzFyhRQ7NNpNVHx0guRQQTV9gaFcQSV2IiyFNZA4jnBAsljUQXcdBYIUMGQqR69FgvzaUCp-wYYGxJydQEi-Y-FQLyYdA41fzXRGj0ZwJINyxVQX1HRG0J0hokDe0jIzBsZsNYMcKGRVAfSYNcR_SIgEyWghZ3FZgBJ0yW5RRATfSyLnScieC70dY8RcyCgkzLJGi0zCENSzd-LXCOKHyeiqBgAEAOBhiBAc8sTGRTyxgQJJpDSLD2ZMMnhnjxIDDMIexAIncXJroXFTtlgEId5VwfQJFigfympJRwSrgEIpoZ1CMglqgQQBw_l6YtK7IbERsvg-dOLzde5vgRt6gii5ADIsJah0oC4S4xg6RzYzhvZOYTggkS18xe5UQVgLhi5QKRw3KfI6g6VFZuZege8U0mcToQQCRnQ7YYxrUyjJdsQ8SigJc70aishg46TOr7wFLCgSVFB3T-qlKzU6Dc8AYNhlLQIbKvcjIgV1J0pOKdKGw9KBgvcctwFjIBIUyVJOw4srKPlDSGJFFNNHKIk0N4rXK4xvKYMPlbrPL1o0UoQQYfKHxwqhxkYurgjwQuU6g4rmREsErUrUR_pv4nINpgTVhlVriFxswKQ3JgxnZm5lhZpD8hZu8bqqrjC4w4pbZkw8aKgOinNWr9AElLQIFJdI0KaNh8Rdgaaa0xrS9JrGahractUCYTrjpgg-hA56hj1KtOgnRiNTD1oYgzlm5_hZpLgbYnECISQzIpANxEY2wIYzVwMpbaJMYiqLlPphwBhqYnhh8kQmJoxorM0gYvZn4io0gvd1hkqQhS4Z5A56YLx69Ow8rv4zSoI6hjlatjJgZGE1h9sdK6rZpRFOhhIdCUV7puYsJwNUR9dZb3hqLztVNbUvyxg9qNwF0V0wbTQ4I-x_qcYdpi6bQTgkyrcdR4agRjskwAVKRCYOhFhywohO4XdUgcqzAXhPgCFv8bZ3g7pSwyYexYh2YkaphkQ1AZ8lhOZ4QHEWMaR-aoh_A-a9pBEEwM5sxGgJhpwPBxYAZIgN6s1FAjEFMlJUbwQ1yobtggEMQLAIB3cvdbp9x3gBph6XcShGocQAUYZTyUg_IW64gkCBx31A0-05p2F4rcaYdqy2JyM9ZTB1oi6AHOZiRMwfIXpuYOZdcsIfpxbhVmwociRHceg5x_o95_rm57hdZRJpoCTo6XKkI_k8EMUL6hNIyzYsgf4UqPxSGsoaY1KsoDJ3wrrPK2J7wsHMwuo4IRMEagYOHvcvdMJdY1BbljZ0prUEItAlxFxVI6JLLNBxUDgSEi59GjCnE-GSQ4JNLEEhb0Zz57HX5pMhcUhzoeFe5HRXhfBjogY7YGx_hSpAmzIYZr8hH5rn9ArVHRG1lta8H9qNqCSegnxZg9rCMfhDq4wn8GJlzOo_lvRDJjIYgVl7o_lQhEoDYJ5sRe5lEHwIhb8U4ulGZHShCpIKQrAfAaGfohNkgJggUaFD5u6Yr_CXa1ZemXY-YJo65A4oNLb0q0UmmgkmhfgrQp1XbwK4xtV88XbTbxRM6RztRs0V1bhdyc1oxFA3K1E5pd9UnA43SwJ35J4lJBhSRxynngp1kMjZpFKgmYd3zfnaINB2q-VZFMgXhh4OabBOnvosTOU_spaJlYXtUubHzygTg8QGCdc8DA4aEio_7ggsl9RcM1AHaHMWZt4aJOxq0J1TlyIH5cLsHzBf0dBm51grAwXuY2XyYBJd91Bbp8nlAwXy4bojMTIn4KopM2nX1ry7BbG7xMYX7pIVZvx0YC4iRq5qoR7sXVrjIaETE5wQRLBnFR0xaO4Jt7IT6_nq0bptDjjnQKJig9oBgagp83GLY_doEMihhSy8MDYcrthR5nWHE2RjJyCRI8YEGvg0HSwUL1Wqtv9kZdxYFyJY5fx0X58jIYApk03WxMW4jCc5xY8BJbl7AlJ7RuRzA9beY9GPasE7kIIVo6yLCm9t1kR2N_oaGbrm5xhe5v5WEb8gZmh9Kvd4wbS3ICHUoUbHQ80nW0WAVNwXbC1t153TgKHHmb49DJ57KhkzhVa8Z3wmmarytUktJg16XJ1bwJsniyK0XhyTgb33yYBUBywYw9ULCNIC2UDi3kSpcv2HAWUUS61MhiQ3yvd4IEN2Iglw4hRNQXgO5DjgguhEtMheg0aBI9QXgnJoPDGKhaE-gVp55xQNb8PdwYZfgtAu7mh6o1AsRAm-XqgqgzwCt97Obq6VBgP5TdJMgQI9U1oyHJRIEinrIEhAZaszhCYnStELizHfaOoYNCWUFK1pFK4T2TVuPRJScAHAtAPAtgPvhPidPNPiR8yrgtOVBpEIhh2QruZ710Q6HEwelNxrGQgQQdAG6rb2MqRMUawkHMxDhZrSR4MMVeYt4237AO3g4EaV5bHTlKwq7ZzobEto62JGY3xkQrgS3BYkqPm6rkQaFaFQaIAVTbsFQ-Ydxb2J5J1H9lBb7OY_A3AT26ukIJdczy5gDwaVysgKU_w7ASpTOdhzPNAIhEXWuskLOcieByAABfAAbnIFAEgFgEqWwFoDwFQFoCgCgEYAAHNiAyBejkAQAAB3IY5PAAV1oET3gBAAgHoC2_ACGJ4GoHoG2-QCgAkpgBAAADMvuIANuhiABtVIJQGAfQAAXSu6-_ACgFQHoCKRqRgBqGm7m6-7O7AGAHu7ABgEwAQAAGtaAAB5OATHgACigHQDgEu9lSwFwDwAAEp9uqA6AoAzvqAseKA6ktuoA8AEeOe6kYAoBaAAAPKAR7mA2gfo4AHnwgRgGAAADQSTu_QEm7qSm6u6oB5-29oGYCGL57qSYCQAQEB54HDntFKV4FN4sB4DB64CoDV9t4F5AHwC28GMZ_5-Txe615kp4AQCF_oAgA-7qV9_94AAUQBGBBeZK9f3eKeEeeA-iEAmBjuVf-epuHf7e6ltvnumBdeHfJLofU8wAJkEAVu8BTvqALv1fuAeevvReYBw50-q_0AABBP3iAXP_nmAA3qAI3mAAHp7hgZgVgagc3-P_ouAUfipKpWgUf5PQv0fqSkfiHvPmARgLvNgP78vyvlf4PiACZRgXn2VQ7k7mAL7hAAgWgGADP_n3fgAFXoGAFx916P-O6GLP4v6v6r6oF3-L9L4787-x7SVtuaeGAN_C_7cAoeYAGHnDwR5JgV-1_IPm3zD4R82A__Tvst1W5oCABfRV_gLwr6XcV-dSHHtQGAFgAhi38QgVf3gGN8HeQvVvv7ywFUAIAFSO7vv2qTP8cBJ_d_n90_4782-v_TAWQBf5cDz-PAhAdwDv4P8n-QgzgW_1EGX9xB3_fgQfw4HH85BH_NPqryr5VJ6AOPTHgABFWeSAegOAAACqcAbvgj2kwlwHef3Z7rQHb598V-0fOpGAAQCYA4-pvDQIH3570Ac-vAbANJW0A-DOesfU7rH3AEa8S-ggjAWtw25bcwA23SIdTxwD4AAASrQEp5IAt-BAgASkNp6w94exvdMAAFJR-BxMocvzyGBDqAqoJALQG24gBqA6AAAOIIBXePAL6GUOSFo96A6_agBAHP638U8kAO7iYLIFu88h2vEvjz38HndcheQrvqtwQDoA3-aPDHuMJgAk8_BQvEHlABAA996ekwxYcz1Z5Y9thTAIXjAEECO9DhDPAAFSI8Sg-gObosKoF5DFB3Abvr3wB6UCqALggAV3nP4Xchi9oOIH8O4AQAae-AIYlCNSF4AYAAAH0RHwAs8GAeERAGkB0BGALANgBCM-F1IARnfIEXgBBH19cQEIpgdCLL75D8ASIlEQ0nRG09MRfRAYviOSH_DKRZhYEQjx5Rci4RtPWEdSPpGoiUATI_AJiKn7VJ2REIokfzxJFki5M_I6kUKPhEijGR1IzEXP0YAyi3hcoupAqNgGvRlR8I1UbT3VFojNR0gRfviMoE29O-nwuUW4I8GPdLeIQ7gH4Me41CJA7opPGEIF4RDKBNQtoR0NSDdDKBsQoYrEPW6bcduyQgUekMyG0BsheA7fnkITFrcYBxQ_QN0N4AVDrePQsAH0I35DCRht3THowP57TDsAswnIRyKWGVJVhp_dYZjy2E7C9hBw8_gz31HcBThbPNsZcOuG3CuxMAR4akBKCvDFhmggAQSK76G9AesorkYaNBGjwTRgo2kQiORGii0AVo7EUPzxFvDZxnIt4VQGXH19dga4mERuItFiirRrIuALqMWE9jTxPIoYo7kvE0iMxN4ncRiOkBSjaAj4vIc-O5GkiEe1aD8WaLpFbiNRv47UWAEAkADgJZ4_RBBOvHQTLRv4m0YeLtHUC6k9oq_nNzT4LdoAn3YnuMMIAkBfhVAHHvjyJ6k8-AD_fYc93P4AAhaSjwDp5XcaJhPMieABJ48AahHEriXjx4n0S4AjEpofQFYnsSQePAJgFJMwDgAmAHE8gGDzm5AjqApEzHgAEkh-VwkgC8PIAgBeJWPEgMZMx4QAAe5k8YbpJYBC81J5ADSQL10G0BbJwvPboZL-5QBdJkfEkST1R7o9WxJPbsVwGsngA3J-krYWFLAARSYAAAakR4M8ShWk8idIB56JCUAk48yXt2imWTopEUhyUnhcmxSSAZPYqXpPimJSYAyU0wKFOJ7SAs-fgtKbQFr57ctuHg2KQlJ4A5iU-mAdAKqGQDSUoA0gLyXRPGEk9zJdPQiSD3LYaAppQAA).
Please keep in mind that most software is designed to accept reasonable, **realistic** inputs. 
ECharts has hundreds of interconnected input parameters and it would be unwise to bloat the code with excessive data validation or safeguards against unrealistic scenarios.
