### ISSUE TITLE
[Bug] 一个图表超过9个实例 不会正常渲染

### ISSUE THREAD

**Issue by shiziburuchengzi** [apache/echarts#18852]
### Version

5.33

### Link to Minimal Reproduction

https://codepen.io/shiziburuchengzi/pen/yLQoxQR

### Steps to Reproduce

一个图表9个实例 第9个实例渲染就会出现问题;l例如再该示例中，体积是正常数据的，在图标表上不显示

### Current Behavior

一个图表9个实例 第9个实例渲染就会出现问题;l例如再该示例中，体积是正常数据的，在图标表上不显示

### Expected Behavior

多个实例都可以正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Duplicate of #18853
