### ISSUE TITLE
[Bug] 一个图表9个实例 第9个实例渲染异常

### ISSUE THREAD

**Issue by shiziburuchengzi** [apache/echarts#18853]
### Version

5.33

### Link to Minimal Reproduction

https://codepen.io/shiziburuchengzi/pen/yLQoxQR

### Steps to Reproduce

一个图表9个实例 第9个实例渲染就会出现问题;l例如再该示例中，体积是正常数据的，在图标表上不显示

### Current Behavior

一个图表9个实例 第9个实例渲染就会出现问题;l例如再该示例中，体积是正常数据的，在图标表上不显示

### Expected Behavior

一个图表9个实例 第9个实例渲染就会出现问题;l例如再该示例中，体积是正常数据的，在图标表上不显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

该图表第9个实例 可以正常渲染

**Comment by plainheart** [comment]
看了下你的示例，第 9 个系列以及其他有几个系列的数据全是 null，不显示是正常的，换成非空数据则会正常显示。

**Comment by shiziburuchengzi** [comment]
![image](https://github.com/apache/echarts/assets/93693269/48756543-98f9-40aa-bbe6-dcb48ccba6cb)
![image](https://github.com/apache/echarts/assets/93693269/63feba8d-2a59-42e0-b3a5-b53fbdacffa7)
series yAxisIndex 为9的体积这一项没有为null 的数据 该项无法正常渲染  其他项中有为null的数据是特意赋值的 只展示非null的折线

**Comment by shiziburuchengzi** [comment]
该图表有9个实例  只要设置哪项 yAxisIndex 为9 该项就会渲染异（没有重复设置yAxisIndex相同值的情况）

**Comment by plainheart** [comment]
第 9 个 yAxis 最大值 `max` 设置了 `50`，但你的数据均大于 50，不显示没问题。

**Comment by plainheart** [comment]
请仔细检查核数据，这不是 ECharts 的 bug。

**Comment by shiziburuchengzi** [comment]
![image](https://github.com/apache/echarts/assets/93693269/66dbf37b-e70f-46f7-b4ac-f9252365c58c)
yAxisIndex为9 体积这一项 没有设置max值  设置max值的是其他项 体积这一项渲染异常

**Comment by shiziburuchengzi** [comment]
![image](https://github.com/apache/echarts/assets/93693269/9c1c9800-6160-4d12-89ba-42f7c56848fc)

**Comment by plainheart** [comment]
yAxisIndex: 9 对应的是你上方定义的 yAxis 数组当中的最后一个，而不是第三个“体积”。

**Comment by plainheart** [comment]
先不要看你自己的代码，你看下给的示例。

**Comment by shiziburuchengzi** [comment]
我调整下 yAxis数组中的位置  渲染正常了

**Comment by shiziburuchengzi** [comment]
问题已解决  十分感谢
