### ISSUE TITLE
[Bug] Time scatter series endpoints sometimes disappear

### ISSUE THREAD

**Issue by jnoyola** [apache/echarts#18861]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=MYewdgzgLgBNCGAnWBeGAReUCmA6MIA7gBQCUA3AFCiSwAmW8MaY2hMAgoovAJ7EAmAAylcAMwCWAGyllcAW3gAHYsQD6AGhgTSzAHwwA2q3aYcxBMhgBqbaS0SAuhUqUQSqBPDMYAb0owMAAeHEESEABcfgGBMFC8SthRAOSe8tjJGjEAvlmBvKHhUf6xcQlJMMkAbvBSAK4ZOXlw2IgS2JFGMYElpTAMUPBRA_DNpfGJKRDAWDiIyd0w2TGOlNnkQA

### Steps to Reproduce

1. Open repro link.
  a. This is simply a chart with a `time` axis and a `scatter` series, where points appear at the leftmost and/or rightmost points on the x-axis.
2. Drag divider border to adjust chart width.

### Current Behavior

Series min and max points will flicker as the chart width changes, and the points may remain hidden if the width is left in a bad spot.

### Expected Behavior

The points should remain visible.

### Environment

```markdown
- OS: Win 11
- Browser: Chrome 113.0.5672.127
- Framework:
```

### Any additional comments?

Any number of changes show that this should work:
* changing `xAxis` to a `category` axis (with `boundaryGap: false` to most closely replicate the current view)
* changing the series type to `line`
* setting an arbitrarily small `boundaryGap: ["0.01%", "0.01%"]`
  * This is the workaround I currently use, although it's not ideal and sometimes interferes with the axis labeling

**Comment by plainheart** [comment]
Just set `clip: false`. See also https://github.com/apache/echarts/issues/18656#issuecomment-1558947731.

**Comment by jnoyola** [comment]
Thanks, that workaround works.

I see you marked the linked post as "not a bug", but based on the above bullets it seems like this is unintended behavior. Is that correct? Or if this is expected, would you mind explaining how the default clipping works and when `clip: true` is advantageous?

**Comment by plainheart** [comment]
@jnoyola It is similar to #16329. The edge symbols are clipped due to the tiny offset. I just found several related issues. I will consider it a bug and try to fix it later.
