### ISSUE TITLE
[Bug] 通过setOption定时刷新图表，图表上描绘的点超过10万时，内存不断增长，最终导致页面崩溃

### ISSUE THREAD

**Issue by chuilee** [apache/echarts#18865]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=MYewdgzgLgBAJgQyggMgUzAcygCxgXhgFYAGMkmAekpkAdTQHgVAo2MHJNGQUMVANbUDyNQf1THA4M0B8ZgChQkWMCRpMIAE4BLNBAIwAFADMArmGBR54NQEoYAb2EwYAGzSwwIAO4qwaRwBEpqwwG5zVmzFklFQBtAF0fC2tYazAVRGR0LFwImHsceWs1GIBabOMzCwtAiAA6bQh09ShVO3sSqBAUEElrABV5AFs0AGUoBSxPEsCAB0sEYDRVSgA9AB1XACpKABoYAHI1w29fC1qnFxh3KEmAaj3smAAmcm2LAF9fQKhNWVjinzvDTx8xaBhJY4yBRKS4qDTaXT6WKeUy-KIBIKEMIpeExOJIVAYbA4FJpDJoLIYXL5HYI0rDTQVVQARgoFzRF2ptxgDyKNhebyUHy-21-sHiCDBWh0egMMIKflgxRC4Th_jRhAFiWxuPSmVUOTysMKZJKFKpAFkkDghiBtHBVEbcEMEGA4CAOjCFjBaWQtilWQjnq8ydzvqJwH8BaDCOCRVCjNrJWSZSj5RgVCRVfjCbEADzwDHK3AknXFPWUnCqE6W402u0Op0uignYiGeogABi8gAHmgLUzmZEMCcTh7Huyfe9hJ9_SBhqLYoQJXooNYAFxRizHFtQRdrVwATzACA68mAhwxa18d2WvgaIEsemGi4ly4UmEwaFk64QLfkEDWZ51b4_AAUQHkMBjhfJdCigTdhjQddgFkEAIE_b8dSsBAACM0EsW9SR1VDxgAa0wODzQAYUvOR1wAYkuAAOABmVCiAANmPZCWVJT1TzlJ87VvTjlxAS9UJAFssJ1CoHEXPpNDQJCLHUNAkBeaCwIsAUADVFHsW8EQQOAAHkwEsTdF3UBBLAgAk-OQ4oGkCXjZMKCAEAANzQABBCAAEkOgQJ9ePYk8kIFAAtASOlExycAkmBTPMmTSWgBBZDXGASAcjA4EXV1At8Fs3PfCBF2CUk73AyDlLWAFpDkTcv2wmAhPNJLNwAcQQG8YCk-LWIFRcqqBRQIHYhzSuXcqYKkIFaocixGrtZq2o6rqZszZA-smuRBsuAKLFCJDN3yj8ipK-qIKg9dnLM6S6tYiAWmU5b6p3Lp1z_BQJhu5CfJEmBaLS-q9zARd_tYubEFkVr2qKkgSkuVYYcuUJhpO1izoqy7LGula7rMh7ZGklbnoqvTZDgZ9Pp1b6suuEGvqA4GVrBhaoZgYIEfh2GkZ1T09t8CzgUK1mUeQon1y3Z79xgAAhJKKbK871ksIC0Dliw8oKzy7TQH7qRWg6Na1nWVt61aEGRnVRpgUX1nF3dJZQZXVc68bFcd42MUXYMdpgJG7h8drhhKUBtFgQhqWpHwLKgTWQIxsNITFXNo1_CAjkFQhnDcDx6waJp7vaLpen6TBBhGMYJimOZFhWdZNhSAUSgqeQqn9VSMQLQ0yyIu1S2tWRbXtR1jGdV0SHdXxg0bypqmZSf9SLEsrRNfuKyHmAR5rOsG2bNsO3Hix-s2pQp-bmeUkPgWO6LFO0-ZC-tpPlu742gXLiv1QA6Ds1gN7ZkOk3YiOAkpQEbjYPSE4oSqFKurI6QtWKWzbmtf4L9Br1SshbeqiCEDrUBEfCA21WKel2g5fmg1jrwMwabT2GI0ErQQVQ02BDkJEJ9iebYp5qxui8EAA

### Steps to Reproduce

1.如上面demo所示 
2.打开控制台memory下可以看到内存在不断增长
3.增长几次后会回收一部分，但最小值一定是在慢慢增长
4.可调整代码中dataLength的长度模拟，越大越明显
5.长时间运行, 可能是半天到一天时间

### Current Behavior

频繁setOption更新图表，数据量达到一定程度后，内存溢出最终页面崩溃

### Expected Behavior

setOption更新大量数据，长时间运行，页面不崩溃

### Environment

```markdown
- OS: windows, mac
- Browser: chrome
- Framework:
```

**Comment by clark-tan** [comment]
+1

**Comment by chuilee** [comment]
使用typedArray
