### ISSUE TITLE
[Bug] tooltip.textStyle some value is not working

### ISSUE THREAD

**Issue by Quska45** [apache/echarts#18869]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/quska45/pen/BaGmZoq

### Steps to Reproduce

https://codepen.io/quska45/pen/BaGmZoq

1.How do you create the chart.
- using echarts 5.4.2 version
- please check codepen link
2.What's the chart option
```javascript
option = {
  legend: {},
  tooltip: {
    textStyle: {
      color: 'blue',
      width: 10,
      overflow: 'truncate',
      ellipsis: '...',
      height: 51,
    }
  },
  dataset: {
    source: [
      [
       'month',
       'longText1111111111111111111111111111111111111111111',
       'longText2222222222222222222222222222222222222222222',
       'longText33333333333333333333333333333333333333333333',
       'longText44444444444444444444444444444444444444444444'
      ],
      ['1月', 223, 635, 342, 988],
      ['2月', 473, 575, 612, 1128],
      ['3月', 354, 0, 578, 867]
    ],
    
    // 请问这种写法怎么改其他配置项才可以跟上边一样的效果图
    // dimensions: ['month', '电脑', '手机', '笔记本', '键盘'],
    // source: [
    //   { month: '1月', 电脑: 223, 手机: 635, 笔记本: 342, 键盘: 988 },
    //   { month: '2月', 电脑: 473, 手机: 575, 笔记本: 612, 键盘: 1128 },
    //   { month: '3月', 电脑: 354, 手机: 0, 笔记本: 578, 键盘: 867 }
    // ],
  },
  xAxis: [
    { type: 'category', gridIndex: 0 },
    { type: 'category', gridIndex: 1 }
  ],
  yAxis: [{ gridIndex: 0 }, { gridIndex: 1 }],
  grid: [{ bottom: '55%' }, { top: '55%' }],
  series: [
    // These series are in the first grid.
    { type: 'bar', seriesLayoutBy: 'row' },
    { type: 'bar', seriesLayoutBy: 'row' },
    { type: 'bar', seriesLayoutBy: 'row' },
    // These series are in the second grid.
    { type: 'bar', xAxisIndex: 1, yAxisIndex: 1 },
    { type: 'bar', xAxisIndex: 1, yAxisIndex: 1 },
    { type: 'bar', xAxisIndex: 1, yAxisIndex: 1 },
    { type: 'bar', xAxisIndex: 1, yAxisIndex: 1 }
  ]
};
```
3.User interactions before the error happens.
- I just make chart

### Current Behavior

![image](https://github.com/apache/echarts/assets/37561496/b637cd3d-4518-47e3-a524-7492289f0c23)

textStyle.width: 10
textStyle.overflow: 'truncate'
textStyle.ellipsis: '...'
textStyle.height: 51

above options is not working.

### Expected Behavior

textStyle.width: 10
textStyle.overflow: 'truncate'
textStyle.ellipsis: '...'
textStyle.height: 51

i want above option working

### Environment

```markdown
- OS:window 11
- Browser:chrome
- Framework:svelte
```

### Any additional comments?

https://github.com/apache/echarts/issues/14211

same issue in above url.
I think tooltip.textStyle option not work.
please check this option 😭

**Comment by q1anxiaodong** [comment]
通过给tooltip绑定类样式，可以设置css样式来调整tooltip里的文字如何截断，但这种方法只限于[renderMode](https://echarts.apache.org/zh/option.html#tooltip.renderMode)为`html`模式下的tooltip， `richText`渲染的情况可以参考富文本的文字样式修改
tooltip绑定类样式：https://echarts.apache.org/zh/option.html#tooltip.className

https://codepen.io/q1anxiaodong/pen/eYQeVXq

**Comment by Quska45** [comment]
> 通过给tooltip绑定类样式，可以设置css样式来调整tooltip里的文字如何截断，但这种方法只限于[renderMode](https://echarts.apache.org/zh/option.html#tooltip.renderMode)为`html`模式下的tooltip， `richText`渲染的情况可以参考富文本的文字样式修改 tooltip绑定类样式：https://echarts.apache.org/zh/option.html#tooltip.className
> 
> https://codepen.io/q1anxiaodong/pen/eYQeVXq

thank you. you save my life
