### ISSUE TITLE
[Feature] Violin Series

### ISSUE THREAD

**Issue by zoeyy23** [apache/echarts#18878]
### What problem does this feature solve?

背景：直方图和小提琴图是工程类数据分析的重要图表
目前的问题：
1.echarts不原生支持直方图，只能通过自己计算并用bar或者costum图来画
2.目前没有想到如何实现小提琴图，隐约觉得用costum的自定义svg能实现，但是感觉非常麻烦，因为小提琴图中的每一个数据都不同

小提琴图：https://g2.antv.antgroup.com/examples/general/violin/#violin

### What does the proposed API look like?

能否为series增加histogram的种类，以及如何能够实现小提琴图

**Comment by reactjser** [comment]
可以用自定义图表实现，参考：https://codesandbox.io/s/kind-haibt-xnvkl

**Comment by Corgis** [comment]
+1

**Comment by thanhloc-17** [comment]
+1

**Comment by Ovilia** [comment]
Examples: 
![image](https://github.com/apache/echarts/assets/779050/3529f8c0-9115-49d6-8f42-8482500f1722)

![image](https://github.com/apache/echarts/assets/779050/499dd570-e505-45f6-9cbe-b504ca698174)

**Comment by CnBDM-Su** [comment]
> Examples: ![image](https://private-user-images.githubusercontent.com/779050/301129076-3529f8c0-9115-49d6-8f42-8482500f1722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTQ4OTYsIm5iZiI6MTcxMDIxNDU5NiwicGF0aCI6Ii83NzkwNTAvMzAxMTI5MDc2LTM1MjlmOGMwLTkxMTUtNDlkNi04ZjQyLTg0ODI1MDBmMTcyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMzM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWVjNDNhZDA0MTY1MDQ3MGQ2YjFiOTNkMzE1NTdhZWY2ZWFmNDZlOWYyZmEzYjFlMjVjMDRkNzU5Y2VjNDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zGmqDraMpsEQ2er983-f5s_8s-XYCRXz291Jq3f3lew)
> 
> ![image](https://private-user-images.githubusercontent.com/779050/301129111-499dd570-e505-45f6-9cbe-b504ca698174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTQ4OTYsIm5iZiI6MTcxMDIxNDU5NiwicGF0aCI6Ii83NzkwNTAvMzAxMTI5MTExLTQ5OWRkNTcwLWU1MDUtNDVmNi05Y2JlLWI1MDRjYTY5ODE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMzM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWIwYzM4NDZhZjdjNjdhMzcwYjI5MTY3NTc4OTc3YTg4ZmJiNDE5ZWI3OGJhZmUyZjA1MjEyMzMzNGMzMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FeNgys0--XuRGSweE3mFwsOZo8hlESGyR0uLSVUPORw)

Hi @Ovilia , 
The violinplot you shown looks great. Can you provide the custom serie you made for reference?

**Comment by Ovilia** [comment]
@CnBDM-Su These are just Googled images instead of using ECharts. I'm still working on this feature now.

**Comment by XijueYZ** [comment]
Is there an estimated launch time for this feature? @Ovilia

**Comment by Ovilia** [comment]
https://github.com/apache/echarts-custom-series/blob/main/custom-series/violin

**Comment by XijueYZ** [comment]
> https://github.com/apache/echarts-custom-series/blob/main/custom-series/violin

npm install 报错：'@echarts/custom-violin@*' is not in this registry.

**Comment by Ovilia** [comment]
> > https://github.com/apache/echarts-custom-series/blob/main/custom-series/violin
> 
> npm install 报错：'@echarts/custom-violin@*' is not in this registry.

It's not released to npm yet.
