### ISSUE TITLE
[Bug] breadcrumb.bottom does not have any effect (Treemap)

### ISSUE THREAD

**Issue by erzenhaxhi** [apache/echarts#18872]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5GDllgLYCGITANFQoATLmC7Ey1aqilToXDo1hNowIVgCC_QbIBuXADYBXJQEYADANnUAxgAsIBoW2gSd1mddnzFzVeo0ubS89QxNiABZ3WQBfKxD0TwT0HyUVNU0AI2Dk9H1jJQA2aKkYkvQAXRK4kqTrVL8MgCEcr3zw2AAmS3LYe0dnLFdSXsTRigblfywmoPjc9qVu-eT-pxc3XOlx7wU06dnTVq28sKXzHYoyk6rc65Db63vqCpX0TLYuIRscIw5M4h1agYOzAADuxFYJjeFEywDAYGAHGYAFZzABSJjuGrUe5VGIAbiAA

### Steps to Reproduce

Put `breadcrumb: {
        show: true,
        bottom: '50%'
      }`

### Current Behavior

`breadcrumb.bottom` property does't have any effect.

### Expected Behavior

The `breadcrumb.bottom` property should position the breadcrumb.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
@erzenhaxhi It seems the default value of `breadcrumb.top` is `bottom`, so it can't work as expected. You can try to set `top` to `undefined`. The default value for `breadcrumb.top` seems wrong in the documentation.
