### ISSUE TITLE
[Bug] 树图：初始化页面时，默认聚焦某个节点

### ISSUE THREAD

**Issue by a852882874** [apache/echarts#18875]
### Version

5.3.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=tree-radial&edit=1&reset=1

### Steps to Reproduce

如何实现初始化进入页面默认展示某个节点聚焦状态

### Current Behavior

如何实现初始化进入页面默认展示某个节点聚焦状态
![image](https://github.com/apache/echarts/assets/25943026/532d5053-2305-45e4-a5ce-e9769d01032a)

### Expected Behavior

通过参数控制哪个节点初始化时就聚焦，而不是鼠标移入聚焦

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
可以在初始化后手动派发 [`highlight`](https://echarts.apache.org/zh/api.html#action.highlight) 高亮事件，参见这个[例子](https://echarts.apache.org/examples/editor.html?c=tree-radial&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzOQqUAzADaxGCAFZJUhKQBpRWgK6EAxnHynRpeYvKiA3tVGjQkWEQIfFxGbDwiMiofP3BoeGRmdgAHR1NSGN9SVFSnQlEAXi9M31E4VFQdR2SALmLShrKYfGImGDqpfDhGYAsShrhm1sYYdkIO4FRrNUmAN0YpftEAX3MltWbGJDqAbSXfb0bGuBBkxg7BxgW1o4a3KF37gF0b299y2ukARgAOAFI-m9fAAjVBwcrADpfAAsANebz0ICmcA6MAiUB0gKBSBAwFBOg6PVS4HwMDsOmu-1KOLxlQAyvgAF7nUQAdnhtyIXXwGK4MCuABFGKkIHUAMwco5QQj4YAKPIC6xotKEACqyTcLNZAFYAAySxpE6BIfDbepA3xaVB2aYdUJIOyMQjyQhwRYW5ZUz1HJ4lZbkGLRGL-eKIAhIZIKOwQAQOPKkQ6lE5nDrBYgQHQtCBujkbfBbACSzsYAA86vqSoQoMAWVIHRiFjF_TRm0A)。
