### ISSUE TITLE
[Bug] 使用BMap显示饼图后label显示缺失

### ISSUE THREAD

**Issue by hovees** [apache/echarts#18888]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQRjUC29xAvgDTEBGLAQwJESsAMbVozOrADaARgAMAFgB08-cvkAmAJxdYAZgDsqgKxnFhw7oC6PUQC8sLQmYclSwAa7IBXak4PAGdaCGpgwllidFRRdDAATxBqBhBw-g9RAHcIABMwAAsGbUVFEAAPTJiSQupKQrASssrq-PEsUjyIaAFmAGVE4OZfen4hNvjWEEKBYIhIkXbYbuCBXmxqPMIwUgCa9G4D2CZWfqTNwjjl3mAu2gBhHDuGbMLTyfbb-9IAdXyioR5Mcju0JFJaFENAA2VTKFQGGyqXTyMz2Y5iTrdXoDIYjBjjECfEh5PoCKLHWKUkgANwE2AChAAsn1CqpSAJoHlgCwABQASiyy16LFSsHoAEEQCBNuxlrBQctrvK6QyxSyiuzOdy-YLqegRWL6ABxDkpYJy5YcY62GrW9C2jgAbiAA

### Steps to Reproduce

![image](https://github.com/apache/echarts/assets/22854075/a38546dc-7715-4c82-816c-e5fcbbeb998c)

### Current Behavior

饼图右半部分label会丢失

### Expected Behavior

所有label显示正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
好像因为设置了 `width` 导致的，可以去掉。

**Comment by hovees** [comment]
> 好像因为设置了 `width` 导致的，可以去掉。

可以的，去掉`width`后就正常显示了，谢谢
