### ISSUE TITLE
[Bug] series-custom.renderItem.return_polyline. info any 用户定义的任意数据，可以在 event listener 中访问，存在bug

### ISSUE THREAD

**Issue by 1t1824d** [apache/echarts#18880]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/zh/option.html#series-custom.renderItem.return_polyline.info

### Steps to Reproduce

 let ItemData = {
                            type: 'custom',
                            name: ele.Name,
                            info: ele.ChartData,
                            z: ele.ZLevel,
                            yAxisIndex: ele.YAxisIndex,
                            silent: false,
                            invisible: false,
                            renderItem: (params, api) => {
                                if (params.context.rendered) {
                                    return;
                                }
                                params.context.rendered = true;
                                let points = [];
                                for (let i = 0; i < ChartData.length; i++) {
                                    points.push(api.coord(ChartData[i]));
                                }
                                return {
                                    type: 'group',
                                    position: [0, 0],
                                    children: [
                                        {
                                            type: "polyline",
                                            shape: {
                                                points: points,
                                                smooth: 1,

                                            },
                                            style: {
                                                fill: ele.FillColor,
                                                stroke: ele.StrokeColor,
                                                lineWidth: ele.LineWidth,
                                                opacity: ele.Opacity,
                                                lineDash: ele.BorderType == "dashed" ? [5, 5] : "",
                                            },

                                            // select: {
                                            //     style: {
                                            //         fill: "#000",
                                            //         stroke: "#000",
                                            //         lineWidth: ele.LineWidth,
                                            //         opacity: ele.Opacity,
                                            //         lineDash: ele.BorderType == "dashed" ? [5, 5] : "",
                                            //     },

                                            // },

                                        },
                                        {
                                            type: 'text',
                                            style: ele.LineLabel ? {
                                                x: points[ele.LineLabelPoinit.X][0],
                                                y: points[ele.LineLabelPoinit.Y][1],
                                                textVerticalAlign: 'bottom',
                                                textAlign: 'center',
                                                text: ele.LineLabel,
                                                textFill: 'red',
                                                fontSize: 16
                                            } : {}
                                        }
                                    ]
                                };
                            },
                            clip: true,
                            data: ChartData,
                            markPoint: ele.IsMarkPoint ? markPointCfg : {}
                        }

### Current Behavior

info属性无法添加

### Expected Behavior

希望自定义系列图形的info属性可以正常使用

### Environment

```markdown
- OS:
- Browser:
- Framework:vue@2
```

**Comment by plainheart** [comment]
#184000 已修复此问题。
