### ISSUE TITLE
[Bug] echarts.graphic.extendShape中使用roundRect方法出现的问题

### ISSUE THREAD

**Issue by ybk233** [apache/echarts#18891]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/ybk233/pen/mdQXxMM

### Steps to Reproduce

1.使用echarts.graphic.registerShape方法注册图形，并使用ctx中的rectRound方法
2.在series里使用注册的图形
3.在xAxis中开启axisPointer配置项，show属性改为true

### Current Behavior

在Echart的extendShape注册图形回调中使用ctx里的roundRect方法生成矩形后，如果此时opstion里启用了坐标轴指示器配置项，鼠标移到画布上该矩形就会消失，只有重新运行才会重新显示出来。

### Expected Behavior

xAxis中axisPointer配置项show属性为true时鼠标移入画布自定义图形会消失，反之则不会。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
你不应该直接操作底层 canvas context，而是直接使用 zrender 封装的 ctx

**Comment by ybk233** [comment]
因为我需要在extendShape中绘制出圆角的矩形，之前有尝试过用arcTo画，但是也会出现鼠标移入后图形消失的问题。请问还有什么其他的解决方法吗

**Comment by ybk233** [comment]
> 你不应该直接操作底层 canvas context，而是应该使用 zrender 封装的 ctx

因为我需要在extendShape中绘制出圆角的矩形，之前有尝试过用arcTo画，但是也会出现鼠标移入后图形消失的问题。请问还有什么其他的解决方法吗

**Comment by plainheart** [comment]
如果只是想要圆角矩形，可以直接用 echarts 内置的 Rect shape，参见 [demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=G4QwTgBAsgngygCxABwKYQLwVQYyWAFwGcA6AczBQQEscTUAPA1AOwBNEVUAKAbwCgIEIkjQAuCAKFCGEgAwAaQdJjyl0iAHdqbAgjXKhCVNTIICBjWAkBGOcoC-6iACMArtQA2bAAog9EgBmbiw4BNQA9iwQ3GEMCsKiqACUkobYeODE5JTINHQASrgEJMhgEQQVMGgk7l6-_ggkOCCentx61EQJcQkiXMmO_A7JANz8uPjZFFS0JGCoZF3MYJxo3ADkALYwAMJuRJVba6gbCbAnY_ygkBHI4VGYaTIAggxdElLSBNWoEhstZhkCJgGBndIgd5EHwRagsFafdJCH7iCAbfpsCKacFIxJYiQEMBuVDpJzpNj-EASADaGygUTOaIAKsTGRsAOqoNhspkINxsgBiYGobLg_lFIQ2AF1HM4YG8Ps9vr9_qBPKzZcoiKhhagiIiNCi_micAcjuCrKw2DqAJLMLZBEJhSLRbjIcAgLbdCAoaipL6WghuMDRAMaCBG_47faHCLHJIW8NCfqosNJ2Q-5DUEhq4ncOTJZxJoSqTPZ3M8GyF3EabS6fRlnOtPMAJmrxekxlM5gkvqb6p4AGZBh2yR3DjBPMa0-HAl5PP8FtyaxAHLiHOMNGPpBSCFSINTqS25IoIMfT4PTwAWORSmVCNcboA)。

**Comment by ybk233** [comment]
> 如果只是想要圆角矩形，可以直接用 echarts 内置的 Rect shape，参见 [demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=G4QwTgBAsgngygCxABwKYQLwVQYyWAFwGcA6AczBQQEscTUAPA1AOwBNEVUAKAbwCgIEIkjQAuCAKFCGEgAwAaQdJjyl0iAHdqbAgjXKhCVNTIICBjWAkBGOcoC-6iACMArtQA2bAAog9EgBmbiw4BNQA9iwQ3GEMCsKiqACUkobYeODE5JTINHQASrgEJMhgEQQVMGgk7l6-_ggkOCCentx61EQJcQkiXMmO_A7JANz8uPjZFFS0JGCoZF3MYJxo3ADkALYwAMJuRJVba6gbCbAnY_ygkBHI4VGYaTIAggxdElLSBNWoEhstZhkCJgGBndIgd5EHwRagsFafdJCH7iCAbfpsCKacFIxJYiQEMBuVDpJzpNj-EASADaGygUTOaIAKsTGRsAOqoNhspkINxsgBiYGobLg_lFIQ2AF1HM4YG8Ps9vr9_qBPKzZcoiKhhagiIiNCi_micAcjuCrKw2DqAJLMLZBEJhSLRbjIcAgLbdCAoaipL6WghuMDRAMaCBG_47faHCLHJIW8NCfqosNJ2Q-5DUEhq4ncOTJZxJoSqTPZ3M8GyF3EabS6fRlnOtPMAJmrxekxlM5gkvqb6p4AGZBh2yR3DjBPMa0-HAl5PP8FtyaxAHLiHOMNGPpBSCFSINTqS25IoIMfT4PTwAWORSmVCNcboA)。

我知道echarts内置的RectShape可以画，但是我被限制了只能用注册图形的方法来画。请问还有什么解决方法吗。

**Comment by plainheart** [comment]
你自然可以注册自定义图形来画，但是请用 `buildPath` 提供的包装后的 `ctx` 上下文的 API 来绘制，而不是直接使用 `ctx._ctx`。我先前给你的示例仍然是使用注册自定义图形的方式，只是借助了 Rect 图形本身的圆角能力，你可以在前后增加其他的绘制逻辑，或完全自己实现绘制圆角（可以参考：https://github.com/ecomfe/zrender/blob/master/src/graphic/shape/Rect.ts#L42 ）
