### ISSUE TITLE
[Bug] option.color=['red','blue',...]  第一个颜色不生效！

### ISSUE THREAD

**Issue by mazhongfu** [apache/echarts#18894]
### Version

5.4.1

### Link to Minimal Reproduction

。。。

### Steps to Reproduce

                    color: ['#fc6a37', '#1fe422', "green"],
                    series: [
                        {
                            type: "line",
                            data: this.inletData,
                            showSymbol: false,
                        },
                        {
                            type: "line",
                            data: this.TempData,
                            showSymbol: false,
                            yAxisIndex: 1
                        },
                        { 
                            type: "line",
                            data: this.motoData,
                            showSymbol: true,
                            yAxisIndex: 1
                        },
                    ]

### Current Behavior

就是画曲线图，使用系列颜色配色，结果就第一个颜色不生效，数组中的其他颜色生效

### Expected Behavior

常规操作，
想用系列颜色统一颜色，没想一用第一中颜色不管用，其他颜色都生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
未复现，请按 bot 的提示提供一下可复现示例。
