### ISSUE TITLE
[Bug] line animation not work

### ISSUE THREAD

**Issue by clark-tan** [apache/echarts#18913]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=GYVwdgxgLglg9mABAJwIZgCZwLYBFVSoAUAlIgN4BQiiYcA7ogLy0Cmj-UrRA1HYz0QJW-AJ4kA3NUQA3VABsQrZrIVLEggLIEAFgDo0mHKUQAqRACYAjIgC0iKwAYpNZKyghkSKjRphU2KwAXLQMelBwAMpQyDBgAOakADTSNHKKwYgA2qm-Wfx68e4AYiDy8gCarKjIyaH0he6aCFA6JoJWSfWNUJzcJAC6egBWcHFEAOQA9BMkKb6-2q0GcOAYROlKJLkD0gC-UnuU8u6IGASoKlkDUidQ9Spg7Ih9RFYAnO8A7F3vXQDMkmOp2EYhUFgALGZEP8AGyORzQpwI26nTbKFhLfSGLDYEzmZHOSjAODIRAbGqIGAqZxUxAAHgcCNpMB4PDIPjOFz0AAcQABnNo4nCcYgkIFHOA82AIFSc2BQE4hTk0LgADygIQmuFE_mwMAgLwuiAAZIgACowQKIACCapg_Im-3miAicHksB5ytyMRg8SKyC1qHtjpdNBJyGwBC4gcQoEgMqQRB5NQC_I5uRoKbQ2H5KmzaayjhumdUZPOXEez1eBdzej1rCBC1c7k8SdLNArrB6rzIPA7iGmEw0A6IXZ6zTArXaDj7A6HI-bvnHRSgpXKVRq7XniC1i6XiFr_L06KyVl2S6bvj2YcQwYdAAUxlPWLGVb50FaCPAwCFgAp-VYXIjhoG9pDVO0HW9BYoFEHlMgmWBAgmW9-R5eQYCgAAZOJMnfGhBQYP8AKAhYQMQMCaFESD-Wg3xYPgrV0RQ3IACNVkwGpRAAcVQL1skcLoJmRABSCYBlQ9DMJwp46IWQj6GI-RAOA51pEA2JWFo7Jcnw2gAgQ4pUAAa2UUUWKXBiEIwp4LObBTIlEbB2PkJTANvTsLhCCtUA8u8wC_RMAFFUH5OJ4gAVR5LstRs6pkCdMjpF2A5KEAqAAEkX2QdIiHjaAf3JDNw1Jck5DJakWBZBkmRZNliuXbk-UFIhhTwC5SCvcjsFEABhHQaigPR0oAeWlH8iHfDSYC0kIciXPTPMIbyLlLciaAvCiJS6QlJCAA

### Steps to Reproduce

定时渲染进行到第十次后，折现动画丢失

### Current Behavior

定时渲染进行到第十次后，折现动画丢失

### Expected Behavior

折线动画保留

### Environment

```markdown
- OS: windows11
- Browser: chrome 114.0.5735.199
- Framework:
```

**Comment by plainheart** [comment]
因为代码中一直向数组 push 新数据，而不会删除旧数据，导致数量越来越多，达到了[默认的动画开启阈值](https://echarts.apache.org/option.html#animationThreshold) `2000`，于是关闭了动画。你可以调整下该数值，或在 push 新数据后，删除一定量的旧数据。
