### ISSUE TITLE
[Bug] renderItem's path doesn't update

### ISSUE THREAD

**Issue by MeXaaR** [apache/echarts#18926]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=custom-profile&code=G4QwTgBAJiAuIQLwQNoF0DcAoUkbwGEB7AVwDtYkIBGABmwGMiyBnSgMTCLYEkmyqAcgCyAJlE0AHADoAbAAlRtaQGYVogDKjqc0ZJoB2VbQAsWnbVkmas6QZWyN1AJzSJ1GQo_STANWpGklrKolY0AKzSzg5OrrLOshGqBpre1tS2srKS_uHyAXL-mdlOtiqmSSopTpH2idSR0Y4F9YH-nvm2QdQmUQ42djE9ye5G5WYNctlScvl-Lj75kVndvVUSSnIJTr1NENpuVqXS-gsm-Uayvpuptf3i0pYTZRUPsnpOl_s6aqLXKvkZH4Dr9YltEm8Pjcwg8nk4gfsQv5XOcFpoDk9voczAd3vpNvFHJtfjQUYo_t5ZAAtCDCAIQVwA4a0STUY4qEzOCBGWjqGqqd4QWy87qiaTUBmqfLKAy-IzOJwqKKC3qyFSi5X6JWycJsuh2CCNFy-AGM3xGhU89QQbW6jTC9UQVXqjSM7lRXyM-TyjTO_QOoK2iVWzQWyUAlT-GXyC0aIM0MUJIJ-mhKhKaeU0aNm6hitkByrvDQhgYchVu5ms_wGaV2fy9Fl6xPTDKqTmK5XuSIOVIyhPiqN2fJ5_k91Od9mc_tJnaPVlZocBT2qKmCbC4CBscCwAAqAEsALYAUyoAGoyEeAO4QAAicCPAAoAJTr8AQBj3gDmRDAe6PLCoFBBA_WAj2_MAAE8AEFBAAGggYCvx_CCACE4IQkCwOQghBEwHA31gCCAAd_0ArAIAgABvCAyBAY8AC4EIAKQAZQgeQjxAIj0KYAAbH9GMEABiAwACNnAYI9qEECAAF9YPIqiaLoo9BJvIgGBIY8KBYHiiH4sBBKE0SoFkUyGBk-TFOo2iGIQgA5IgoH_PSDKMgxwigSQDBMSyFIomyVMEjQ9zYI8LzAXT4L4gSEKEo9aFEhgDEkPzrOUuzBAAcQABQAVVpI8D2Q1zYuEqBkoMCq0oCjLVIQ3K8tKwy4pSUSe0srA8IAem6iAsvCo8wHvCBioYABraA4BALBMPAv8WGkAAzH8AFEQAYAALB8lvIBhYD3ZgIAfObkPgvcyGcgAPJ8qMUjdRJAFgj33Y8qC3MBd0PI9sAolbIAfDc9yoegIGBgAeKbCFICgMDB09T1uyjFIojdCJInhQIPKh0f_FBhDgTbpC4cgoAfAnYCJ4bLqIA9nwgAAqY7ccW3jws_SmIAAWhoJ8nzwijUbfKASGGg6juQCmqZhsmpeJkAabp26mboWg1ZfFGoZAaQiJIFhtuRwXBds-rccxorpBN_yjYgUBeJIeqUAu674Me57XqPeCHzdl7vogU9kBFsXDrIJ94KDuAQ7Qa2jb3LGWMItnGMNm2KLIH8DxAXjk811OYpas2sekfPc8F2TS_Lo3ZI1o2fY9_3JcJ4mZfJpvqagWn6aZpR1d-uSsGr7BdrIfaQ4gMBwucsBzbpojwDolh4K4vckfut9TsgnhLqPK6qGX6Q7Ydh9aBr223w-yhkH3pgfzJlB98Px9qDD98kM37errQU-N0nveiL3YuRBb4Pnvv_A-Wcj6iBfhvCCW9rpfz7huTaR49yfk2pfCA-8WB7gAF6PhQLQeC1Av4oGIYzCAyhZCILfBPfaLFNpcRPMgI8W1tyLU_MNIim09wMGLrxPcREABKLDYAoQgsI_aD5NYpyNldRiF8CHR1LhBeR8BPqkLQNzCAyDUHoIgH1UQMdBaXj3FASmjFJ6KK0Qo2gSjU46LQbARiDj0GayskbGRgs5EQDnsNA8i0b5gCgCxCCi0rpGIoionx89_GANviExaEEIkQBMWYzajFfELziUEhJ0hUmU2SS4px0S_EBKATk0J0giluMUhrRSE9YCiwEJ43GgkOGkG4kYrae5eJQAnmQRiKBS6eIoq0hCtDYBwVLrAam2DxYDNQIIfWjDcLJOWSRRiEz6GMLWYneqWC9nPjcckkZgsxmCDnpTKZqcKLrPqqco2UBGKcG4LAPgzBkmyNUduKxp5tEoMcfop0nzBZRIUWQnmRSgUmBBRRfJ6TESwv-bo4pSgQXuJuWwCCSc7o3MFktHp2cEKXm4aBa5eKID8IvAAdVMeYmg6LkkYoonYuS2By5ECIvMqgKdYBAN4gdIiOcjb_UzrAUCLVh6jyOg-TJ_jV6pwaU0kpWTM5gHGkNf2KrYkmy1YIQSWq5WLUfigFQmi_kyX8WuGpFEMUHVgDilpO9imCBylwAlbNyUUTZktF1kkKBDUEIpDF-AQBUiAQeQZ0jpnEXqks_hU8vX4p6RK4QTk42Xk4uNdgKbA1rM2kQS8d54DbI7peRiS0s7PWSXyoVTo1bJN4iAUSR5eLsAznACVgkg1VyMac85F1sHOSTX9XNYA03OUEpmkA2ax09rLopVlHDTHCsFkUxi5RaDButldKCV1QqroogeC63zPoeyMSwD8OKZkOyMSAfdLANDNtbYe_FHbxVDQrXtblgMs4KpuUqsAAg5aZyusfeCdtrFqK-seW6FrRq6T7lXG1clrbQQfa-0NjEN4LW3YpZ6v5_xRo8TGjZGE9Z8oPCO8ek8hoz02bR6eWNklxyKgnbF9zS4UU5RtOOUTlCSArsk8KTBJ24pud40h8FRCstTvxoTpcsNaxQ2gAeGAgA

### Steps to Reproduce

1. Create a simple chart with a custom series with a dummy data
2. Add a path depending on api's getWidth/getHeight
3. Hook chart's resize to window's onresize event (via addEventListener)
4. Resize window

### Current Behavior

The path svg isn't affected by the chart resize

### Expected Behavior

To redrawn the path

### Environment

```markdown
- OS: any
- Browser:chrome & firefox
- Framework: react
```

### Any additional comments?

This is a duplicate of #17746 but, I gave an example and nobody noticed I think

**Comment by linghaoSu** [comment]
Maybe this is not a bug, just move x,y in `path.shape` to `path`. 
[live demo](https://echarts.apache.org/examples/en/editor.html?c=custom-profile&code=G4QwTgBAJiAuIQLwQNoF0DcAoUkbwGEB7AVwDtYkIBGABmwGMiyBnSgMTCLYEkmyqAcgCyAJlE0AHADoAbAAlRtaQGYVogDKjqc0ZJoB2VbQAsWnbVkmas6QZWyN1AJzSJ1GQo_STANWpGklrKolY0AKzSzg5OrrLOshGqBpre1tS2srKS_uHyAXL-mdlOtiqmSSopTpH2idSR0Y4F9YH-nvm2QdQmUQ42djE9ye5G5WYNctlScvl-Lj75kVndvVUSSnIJTr1NENpuVqXS-gsm-Uayvpuptf3i0pYTZRUPsnpOl_s6aqLXKvkZH4Dr9YltEm8Pjcwg8nk4gfsQv5XOcFpoDk9voczAd3vpNvFHJtfjQUYo_t5ZAAtCDCAIQVwA4a0STUY4qEzOCBGWjqGqqd4QWy87qiaTUBmqfLKAy-IzOJwqKKC3qyFSi5X6JWycJsuh2CCNFy-AGM3xGhU89QQbW6jTC9UQVXqjSM7lRXyM-TyjTO_QOoK2iVWzQWyUAlT-GXyC0aIM0MUJIJ-mhKhKaeU0aNm6hitkByrvDQhgYchVu5ms_wGaV2fy9Fl6xPTDKqTmK5XuSIOVIyhPiqN2fJ5_k91Od9mc_tJnaPVlZocBT2qKmCbC4CBscCwAAqAEsALYAUyoAGoyEeAO4QAAicCPAAoAJTr8AQBj3gDmRDAe6PLCoFBBA_WAj2_MAAE8AEFBAAGggYCvx_CCACE4IQkCwOQghBEwHA31gCCAAd_0ArAIAgABvCAyBAY8AC4EIAKQAZQgeQjxAIj0KYAAbH9GMEABiAwACNnAYI9qEECAAF9YPIqiaLoo9BJvIgGBIY8KBYHiiH4sBBKE0SoFkUyGBk-TFOo2iGIQgA5IgoH_PSDKMgxwigSQDBMSyFIomyVMEjQ9zYI8LzAXT4L4gSEKEo9aFEhgDEkPzrOUuzBAAcQABQAVVpI8D2Q1zYuEqBkoMCq0oCjLVIQ3K8tKwy4pSUSe0srA8IAem6iAsvCo8wHvCBioYABraA4BALBMPAv8WGkAAzH8AFEQAYAALB8lvIBhYD3ZgIAfObkPgvcyGcgAPJ8qMUjdRJAFgj33Y8qC3MBd0PI9sAolbIAfDc9yoegIGBgAeKbCFICgMDB09T1uyjFIojdCJInhQIPKh0f_FBhDgTbpC4cgoAfAnYCJ4bLqIA9nwgAAqY7ccW3jws_SmIAAWhoJ8nzwijUbfKASGGg6juQCmqZhsmpeJkAabp26mboWg1ZfFGoZAaQiJIFhtuRwXBds-rccxorpBN_yjYgUBeJIeqUAu674Me57XqPeCHzdl7vogU9kBFsXDrIJ94KDuAQ7Qa2jb3LGWMItnGMNm2KLIH8DxAXjk811OYpas2sekfPc8F2TS_Lo3ZI1o2fY9_3JcJ4mZfJpvqagWn6aZpR1d-uSsGr7BdrIfaQ4gMBwucsBzbpojwDolh4K4vckfut9TsgnhLqPK6qGX6Q7Ydh9aBr223w-yhkH3pgfzJlB98Px9qDD98kM37errQU-N0nveiL3YuRBb4Pnvv_A-Wcj6iBfhvCCW9rpfz7huTaR49yfk2pfCA-8WB7gAF6PhQLQeC1Av4oGIYzCAyhZCILfBPfaLFNpcRPMgI8W1tyLU_MNIim09wMGLrxPcREABKLDYAoQgsI_aD5NYpyNldRiF8CHR1LhBeR8BPqkLQNzCAyDUHoIgH1UQMdBaXj3FASmjFJ6KK0Qo2gSjU46LQbARiDj0GayskbGRgs5EQDnsNA8i0b5gCgCxCCi0rpGIoionx89_GANviExaEEIkQBMWYzajFfELziUEhJ0hUmU2SS4px0S_EBKATk0J0giluMUhrRSE9YCiwEJ43GgkOGkG4kYrae5eJQAnmQRiKBS6eIoq0hCtDYBwVLrAam2DxYDNQIIfWjDcLJOWSRRiEz6GMLWYneqWC9nPjcckkZgsxmCDnpTKZqcKLeJsZo082iUGOP0U6ZJkTVHbg0VoopryTDvM3AwjZd0bmCygIxTg3BYB8GYACii-T0mIjhU83RxSlDIt6hAO5ajYBWMeb8vq_zS5G0xVEhRZCeYErecSuSAK2AQSTiC0FEAlo9OzghS83DQLXOZfwi8AB1Ux5iaAAvcTbMVFE7FyWwOXIgRF5lUBTrAIBvEDpERzkbf6mdYCgRasPUeR0HyZP8avVODSmklKyZnMA40hr-0tbEk29rBCCXtcaxaj8UAqAeQhUauk-4UUrrSxSB1YCMpaTvYpggcpcFZWzHlFE2ZLSjZJCgQ1BCKTFfgEAVIgEHkGdI6ZxF6pLP4VPBNgs426uEE5Etl5OLjXYD03VFaKL6yIJeO88Btkd0vIxJaWdnrJOVeqp0atkm8RAKJI8vF2AZzgLqwSGaq5GNOeci62DnKtpZc2oaNbnKCXrSARtu6wDLrLopKVHDTEasFkUxi5RaCZutldKCV1Qq3oogeC6nzPoeyMSwD8jKZkOyMSAd9LANBTpnZ-yt86dVDX7XtBVgMs6mpueasAAg5aZyusfeCdtrE4o9rdR5Ml_FrgrjUwN1toIQdg9mxiG8FrPsUs9X8_4C0eKLcC4CetlUHm3f0qeM9NmTyGjPZJccioJwZfVU5FE5UbTjlE5QkgK7JPCkwA9TLU7eNIfBUQUrU6qY06XRjWtqMQDQAPDAQA)

<img width="705" alt="image" src="https://github.com/apache/echarts/assets/56526981/10b4a6bf-2c92-425e-b5f7-a1ffd3e26f9b">

**Comment by MeXaaR** [comment]
This was definitely not a bug, thank you very much. Sometimes the easiest solutions are hard to see.

**Comment by MeXaaR** [comment]
I'm closing this.
