### ISSUE TITLE
[Bug] The Y Axis Axis Line does not render according to the default setting

### ISSUE THREAD

**Issue by fireflysemantics** [apache/echarts#18922]
### Version

5.4.3

### Link to Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-kuyb6g?file=src%2Fapp%2Fapp.component.ts

### Steps to Reproduce

Please see the Stackblitzin the SO Question

https://stackoverflow.com/questions/76750723/echarts-y-axis-axis-line-not-rendering?noredirect=1#comment135309938_76750723

### Current Behavior

The Y Axis Axis line should render by default, since `show:true` is the default setting.  It does not as shown in this demo in the Stackoverflow link.

https://stackoverflow.com/questions/76750723/echarts-y-axis-axis-line-not-rendering?noredirect=1#comment135309938_76750723

### Expected Behavior

The Y Axis line should render.

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 96.0.4664.55
Framework Angular 16
```

### Any additional comments?

Please see the Stackoverflow question.

https://stackoverflow.com/questions/76750723/echarts-y-axis-axis-line-not-rendering?noredirect=1#comment135309938_76750723

**Comment by plainheart** [comment]
Sorry it should be an omission in the documentation. The line and ticks of the y axis has been hidden by default since `v5.0.0`, but it seems the related documents don't get updated. You need to explicitly enable them as follows,

```js
yAxis: {
  axisLine: {
    show: true
  },
  axisTick: {
    show: true
  }
}
```
