### ISSUE TITLE
how to change dataview timestamp format to date format?

### ISSUE THREAD

**Issue by rullymartanto** [apache/echarts#18924]
### What problem does this feature solve?

I want to change dataview timestamp format to date format

### What does the proposed API look like?

![image](https://github.com/apache/echarts/assets/5577057/64bfb293-d8c3-4ff3-b5a1-cdf7d2ad335b)

**Comment by helgasoft** [comment]
use [optionToContent](https://echarts.apache.org/en/option.html#toolbox.feature.dataView.optionToContent) with date formatting.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWZjADYCNgAPALmXU0wGcALYAdzLACcBXAUwBoLKAzdgIZhWzdmVQZKmACZCBALRwBbcTymYAngEEiEKgElo09qVgAiaDHZm1lAL7dJU2WAEA1CO0bkn60QOkAeWhcDTJeAVwqLlspUEgYABVgAGEYMHZoMHDWaABjBOgACniASh8pADcBZlgBXSoAETkEWHiAOhcBaLAAbQAGAF12qmARPPYAbltq2ujmTypWjvnF6d9ZrAF8XHZWgHIAHlcdvaowDV34M3oIaTAaEgBGfv6AUkmMojAAWkiIADm0BIEyy7GYZgAfMdCNINNCWJD9rF1KjYABqWBHMDSSGJCBKMSHAD0OKRKLRUkx2Nx-wxsFW7CoA2G0AEhPpR1JtIplMwxOJ1OOtPpjOZT1Z7L2Qu55N8fKpWJJiP26ykvGAtSKmwgrX6nFguFa9T0zVc7V20ABD0msF1h0Ntog6PR5QklJOuwxiGxzDlCrRQrJdMx7DyNBqYCo7Q1zCUQhjmvjYHxhKK-w0mY0PwAsjmftJpPsDSamnJehBBizyjLg7y-UGRZjS2aBBWqxLOcqefKA13SX7VbY7LZPdKfcrYfDldtdki1ZRRMJmHAx-sR72HCj4wCIHlEhoQGIKmiLkeyL0zPgamZBiit73ROdNcekA_UVQBJV2FoDDvXxuUiAbA76wF0PSqL4ozjMevQor0AAcADsABsqEAEyvFh-qwC8QyOKiiGoQhAAspHYThmH4fByEoQAnAAzGRFEGgh1G-HekigUQOh6JBUhnseZiQISZgESB4naA0_GUIJZBmNUuAcGJtilgAMts7C4DJ6pJkIGTMPJSCKRwdiwAADSkNi-MBoFihe7qUGyhLyRkShHswQgiNY4mYHJ5i4BA0A-TwdicXYQA).

**Comment by rullymartanto** [comment]
awesome! thanks
