### ISSUE TITLE
[Bug] Heatmap: Adding `itemGap: 200` to `visualMap` has no effect

### ISSUE THREAD

**Issue by lcmgh** [apache/echarts#18939]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian

### Steps to Reproduce

1. Chart: https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian
2. Adding `itemGap: 200` to `visualMap` has no effect

How to add a padding/gap between the item cells as described here https://stackoverflow.com/questions/74299969/how-to-add-a-gap-between-cells-in-the-heatmap-in-the-echart-library?

### Current Behavior

- Setting itemGap has no effect on the heatmap
- No other options available to configure a whitespace

### Expected Behavior

Space between each item cell.

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 96.0.4664.55
Framework Vue@3
```

**Comment by MatthiasMert** [comment]
[`itemGap`](https://echarts.apache.org/en/option.html#visualMap-piecewise.itemGap) can only be used for visual maps of type `piecewise`.

You can add gap between heatmap items by changing the `borderColor` of the [`itemStyle`](https://echarts.apache.org/en/option.html#series-heatmap.itemStyle) property:

```javascript
itemStyle: {
    borderWidth: 5,
    borderColor: '#fff',
}
```

[Here ](https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian&code=PTAEAcCcFMBdYJbUgWgQcwHYHsYCgBjbTAZ1lAAtsBXSE0AXlAG09R3QByARgCYBDTgBou3QSM4DhXAMziuAFnmcArMoBs4th04B2ZQA5lATmXcADGbHDt7Hr3DSejiQ6cyXiz6pe2u6711vA29jbwtw7kc8AF0AbjwQCBh4JFQMHHwiUnIAE34AT3omVg4uAGV-WFp8gqcAMUgEWqcAFQpaEhahP04AdWhczGguwrbqEe6uAFliKc5y6kwW2ISkqDhEZDQsXGhCYjJQfNh-RhZmcxEr0BUYkUuRbif7lhvea9fH0BlPh5uFH83iIVEDvuowTddJCRAYYaBjPCLEjnqBeF8bnwRAoMU9fqBuLiCYCCUTuKCfmSIaAcf8ntDQOoyXCaWTEay6WibjIibxUTzObwPmjefi7g9UVCvqjJdKRMLzHKfmDUSTFRKQSqRNT1SxUQzdcxUSzDaj2aanjdxXqnqj0RqCcL7TaCfimQ7uCTjErybafdT3S7uAzdD6WQYfey-EreFaY6jrUb5cLQw7ePjncwFS8HsKZV8nWDhfjDcK1QXNaBS9qiyIDRXQCaG-aG8jKbnbfLW3nW_jvR3ibDWxSLK2A62GYm8yyp092bOuXWG3zscuncv8bSWCWlw98fyvhmwfiS4fscfK4a3RfQPW97Cc9uRC37wS46_uKqz47d0_XU8t2YfcSW4AU_19R1v24al-3AycoJnKCoyveUbkDID5S_V8hVXbD9y-NVH2YECRDA4j5TBElTweElyxoytCXoxlKLrFjGzY9lMxAgECM7DkWBA9cmNA3CBIA0TyIJEdAJA6lo2EhlGLEglw14gl5zU2NSM0_VNOLTTqJYCl3i-EciIpBVTNI7SHgpOijMvKzmKrJy7wc9iRVs58wRHHivIJfN_KxW4nJEt9QpJRMRwpVN3Ogv0goZdCRybIKNP8rT23cld-OYCyhOywzmB1Ii5LBalLIeakiupeziscqqaxcxrb3Kh9mpYGC2rfUq-MNOSCvq_9SRaz0bM6p47K-OSdWm-luu4VKJvU7rMqUoacszCrBoqt0YhiPwADoAFt-HAAAKAAzJYCEQYhQHOhBYGgY6AEpQAAbz8FJaEwFgnpeo1XgB47LmB57QfRUAAB9oa4FBOHiPAAF9XoSbBwDuv6mC-9hYGwbAABtEHAAAuT6_HAbASCehBiHJzh8eidhkZ6dh0CaXJydxjgKGgDAKFgBmVHMABSGwyiZhmLHF7RWe0AAPABBBWEBIbm_FgApwGgBmCCqaB0FwOo2Y4E5-HJqhOlN9gSHAQmnqVmALYpspbaoAB3cnYEgCY_GRuXTYKFW1Y1yXtd1rh9eeo3IBNvxzfJ2oSBt0A7Yd2AnegF2ebKEhPe9339jKAOWdNgA3NXqH4QnpjOsOOGOhBMHJq4_FOhXyeRPx9cJghqEJ_gACNCcjn2JlT3AkEwIWuCoJoAC9iFOQmJY4UfLtnzgCGgGfkDX9gh-weBsGO6WVFlsvtBIZAkHVlg_FzjhMH4Y7I84AAFG6KFAABhfhIC5APhwLWOsGZ8yqKdXwbtjhVBdubVO7BB5D2gITBuMD87YC9qAcexc3byxgSDcoWtR7oLdkfQByA-jNFgBQcmoI_BlAobkZAv8ia4AZgAYkujw4BV8YEvXABQfgNN75PzKEQkhkdxFu3zvwXIWCABChNaBdzbjAvOwiFEezYYTDhXBIDoCHvwc6NwzHXEOioV6nBGEcFLvg_22gDrIziEAA) is the full example.
