### ISSUE TITLE
[Feature] about series.itemStyle.color

### ISSUE THREAD

**Issue by dmcisgood** [apache/echarts#18937]
### What problem does this feature solve?

In this case, the value of color can be a function，But nothing in the configuration documentation says it can be a function

![image](https://github.com/apache/echarts/assets/34147523/b86a84db-73f8-4134-a142-102e1057fd3d)

### What does the proposed API look like?

I would like to know what other configurations not mentioned in the documentation can also be used to use function

Other, suppose I have such a demand, when setting the label for the bar chart, I want the label with letter A to be rotated by 45°, and the label with letter b to be rotated by 90°. It seems that this function is quite suitable, but it cannot be used. How can I solve this problem

**Comment by plainheart** [comment]
**_Question 1_**: https://echarts.apache.org/option.html#series-line.itemStyle.color
But it seems the callback function is not documented for the bar chart. I'll take a look later.

**_Question 2_**:

Solution 1: Set different `label.rotate` for each bar item. [Demo](https://echarts.apache.org/examples/editor.html?c=bar-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAJgAwA0M-hMWArKQBykDspWWDAzHgLoDcAUFyAA5QAluDQwA3lxgwAHgEFpgiAC5xkqTCgBPPgFMVAcmBIdAcxAAnTfoJqpiZCoz6AsuGsx9AFQCuO9_oB1HTh_TwALb38AMXNBfwBlJATvMH02NQBfGylNeUUVCXUNbT0PADcEABtffUzsmAgdWJ1lTFtVIrskBBV7BAA6AFsEPgAKUYrqnSJBOGkASjQAPg7OqXMdKG9zMFW1qUnfev2YSoQAIx1KgvaTgHo7hs34QQAzV6adMFhzEGQhETnTQwQ46GAWEFVXwwQRgOA6aS3fa_f6lUFoVDoXB4GAAH1xMLmGPQzBgAH4YAAWcgwFTozFYyjkmAAWmptJgeCRRQy3JgGW4awy82O6jOl2ue06EDCIAA7iooOYjny-CAIIIAWADFB-LUhaKpFpdAZzghzPr1LypOkBUA)
Solution 2: Use `labelLayout` callback function. [Demo](https://echarts.apache.org/examples/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQe6BTUdABGjBy8cYLCYgCMAEwADDywRcWwuQCs5QAc5QDs5bm5TQDMhdahHv6MKVT-blmkeNrAAO5EYBxKXQkgwHgQkDB0YKDBCbAOQz19_gAyjOTACmAAFCDpjAC2eACU8Zuw9DB4YLBCYIwAktACVBgELBLhwbngAHSfH5_AEAbiG6Be0DesF2_TkAPeiBBYPBLAwYHhT1gHCoYAUHDg7mJJOAXxYBARCTR_gxBIQ8EQtAKhVosAAPvyPsJfv9AZzEK0mZsAPywAAslWlCSILLZWM5siqvOVHjlAFpFbrSERCky7ESEnY4tb0LYLUA)

**Comment by dmcisgood** [comment]
I see. Thank you very much ！！！
