### ISSUE TITLE
[Bug] option.visualMap.pieces值如果只有一个gt会导致报错，无法执行

### ISSUE THREAD

**Issue by LarryXp123** [apache/echarts#18945]
### Version

5.43

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-sections

### Steps to Reproduce

option.visualMap.pieces值如果只有一个gt会导致报错，无法执行。<br>
https://echarts.apache.org/examples/zh/editor.html?c=line-sections
![image](https://github.com/apache/echarts/assets/141024800/1fc6153b-dc5b-4ae9-a040-db4e286c214f)

### Current Behavior

如上一步描述

### Expected Behavior

只有一个gt条件应该是符合逻辑的。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by taiyuezifeng** [comment]
我也遇到这个问题了，查了半天issue，相同问题的一些issue都没有回复是否修复，也没说明只有gt一种情况的使用方式需要怎么处理，然后就close了，有点懵逼！
经过我尝试，可以在只有gt的时候，给多加一个lt或lte，只要范围正确就可以正常使用了。

**Comment by plainheart** [comment]
Duplicate of #18948
