### ISSUE TITLE
[Feature] Add support for gif in custom series

### ISSUE THREAD

**Issue by Staffman78** [apache/echarts#18940]
### What problem does this feature solve?

series type "custom" renderItem return value today supports type: "image", but it doesn't support a gif image (moving image). This would be a great for my chart to support that.

### What does the proposed API look like?

type: "custom",
zlevel: 0,
data: [10,20...],
renderItem: function (params, api) {
    return {
        type: "image", (of type gif)
        style: {
            image: "https://media.giphy.com/media/duzpaTbCUy9Vu/giphy.gif",
            width: categorySize
        },
        position: pos
    };
}

**Comment by Staffman78** [comment]
Hi, many thanks for your reply. Do you mean render the entire chart as svg when its created instead of default canvas? Or do you men render the custom serie somehow as svg?

Thank you!
Staffan

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by plainheart** [comment]
> Do you mean render the entire chart as svg when its created instead of default canvas?

Yes. Just set `renderer: 'svg'`.
