### ISSUE TITLE
[Bug] X为时间轴时使用滚轮缩放图形出现诡异现象,官方例子也一样

### ISSUE THREAD

**Issue by xibaoning** [apache/echarts#18942]
### Version

5.4.3

### Link to Minimal Reproduction

minimal

### Steps to Reproduce

官方例子缩放:
https://echarts.apache.org/examples/zh/editor.html?c=area-time-axis
在图形上快速的滚轮来回滚动可以重现BUG:
![截图](https://github.com/xibaoning/images/blob/main/test.png?raw=true)

### Current Behavior

官方

### Expected Behavior

图形错误

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xibaoning** [comment]
能不能标记为重要啊, 用户在抱怨了 ,  缩放的bug体验太不好了

**Comment by RypAsuka-Akira** [comment]
> 能不能标记为重要啊, 用户在抱怨了 , 缩放的bug体验太不好了

你司有给ECharts团队捐助吗？伸手党这么理直气壮的？
自己不能尝试换下轴类型看看能否解决问题吗？
撤回你的评论，不要影响开发组的心情谢谢！

**Comment by xibaoning** [comment]
如果你是开发组的, 我立即不用, 换一个组件

**Comment by xibaoning** [comment]
> > 能不能标记为重要啊, 用户在抱怨了 , 缩放的bug体验太不好了
> 
> 你司有给ECharts团队捐助吗？伸手党这么理直气壮的？ 自己不能尝试换下轴类型看看能否解决问题吗？ 撤回你的评论，不要影响开发组的心情谢谢！

如果你是开发组的, 我立即不用, 换一个组件

**Comment by MatthiasMert** [comment]
I think it has to do with the animation process. Try to add `animation: false` to your option. I am not able to reproduce with animation disabled.

[Example](https://echarts.apache.org/examples/zh/editor.html?c=area-time-axis&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOADgoBoIzaBmASgG4AoUSAe03wE9kEAEwAWCACoIDAGwAGWRIgl5s9pwgATAjEEBtXbAS0AsgQAWAOgBOMdBq4BbIk0UN5AXXfsAZlysQidQBLQRIWCBCAHmEVVQjUVBcAbzYICHV0LhwUTBx8QiIiQ0RUFB4QfiZWVM1tCwAHAFc4MyJdDCyTc2suRrtC0zBLGztHZwgAWghZCwBWF0khBVRasBhdEKmSd11tpndqgF82LnqwIJ5BFLTbIIcCC_QALghvGGAjGrAuLmBz-pe1zSEDAViCAHNwSArC8AOQwAAeQTgsOoNTS9S4cCC5x4L28fQAxrj0AEzsl0cCrOBGlZSbozrpZO5aLDlABSWFeSnHNKHNFpc5gUCAymgbxgOGEkDoQhWVGUwgIyUQWEAGRgVihEAAgjYIABhMyasCwmr8r4_YBQLgI0XA14gAi0kD2h2rGAALR-Djd7ogfB1SLgAEk7CA7arMpgzf6Lf7qXBvtTAfH3XAYAA3EA60P3KGpnnmgUQBFB5F-kF8equ1XnBwgBUOm19LRWPgAcRgANe7wQxZqgeDlbA1drsMz70ajZLaRbdk1ne7LyZrOUsk57gHaS0a29jhXlKBDtHNbhQXQ2I0M8paSTJpeslnwJlGheSx5z-PwPvVhVT9vCBX3fWQizSFkagQMEQDgQ8HW_NJ0BgBs4QAMRgABrRB8hgJt3VPcdgAvG9_TgBwfiGF5QWnZ87z4BwbWAOFoxI91NSdABlUcRQgJI0wdXcYBeQSwIgLdDhYIA)

**Comment by xibaoning** [comment]
animation: false 好使没有再出现了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午3:02
收件人: "apache/echarts";
抄送: "Mention";
主题: Re: [apache/echarts] [Bug] X为时间轴时使用滚轮缩放图形出现诡异现象,官方例子也一样 (Issue #18942)





 
I think it has to do with the animation process. Try to add animation: false to your option. I am not able to reproduce with animation disabled.
 
Example
 
&mdash;
