### ISSUE TITLE
[Bug] sunburst series-sunburst.label. align location error

### ISSUE THREAD

**Issue by TifezzZ** [apache/echarts#18954]
### Version

5.4.3

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/editor.html?c=sunburst-drink&code=G4QwTgBAJiAuIQLwQNoCgIQN4cxARAHYgC2ApvgFwGBggYIz6g5Ab4A0um-AlrGSQMqwBPADYVqOPHnwBjAPZCZYKgQDEMAAxQAbAA58bCAF9WE6QAsOQqGDKEl6CZnEP2xckvyA_tUDzCoDAlQN4-gJ_agOlGgNymgN-KLPomXDz8wqLYUQ7ScgruymRqAOwAjACcUnrOmEZJ7FLmlta21PbFjmXJrgn4AGIA4rwAspH1JqBCAK4JOcZ97DF8giJKTuPlqYrU-MoAZnl5ZDmFjRIGu4Zj9XN9RKQtAArtACK98_gDw0qjBxPcU_Gzr5Ky8ksq6022yK83241K4xO9TObmWAEEYCQrrcjqdHiNUdDJnEZmJvgs_ulAVsdvNDAcIX0ocUYS1rmQyAAHVoyOR3cYPEBDDHfTjvHEJanQ35pZZrDYkkHgimYhxCprndytLoAOTh7LRXKe1BeZL5sWmgvxBBF_xWxOB3zBfUpx15zXcFxkHEIsAA7hwAM5kOGweBSADWGuh6Oesuc-o-uMSZIJooBEstZOt9VtxXlJgdyxVZDdsBkhBZbPDyVDOpL0X5hq-sZNiyJidJoJlBwzkizBGu1zVwZpZYguvu2OreNrKUJYotTel4IrMfuHfwAFE4dd1XP2P3Bxzh59R7Hx_HzY2pTaW5D7YrlgAZXgAIQAqj2NwQty_IwKawfTQ2gdOz7OraXrCBDtHe668m-vK7tGbYmD-k4nla55UsBLQAMIAOq9hGUF6jBRpjghCZ_qeqYoXaeqLgAErwABSEF6nhQ5Vnu856sRx6kchgEXlRV4ELwFzPpBWo8vhrGwcah5muK3HJhR6Zoe47RLiJTFiWG0GSYR371oh8nNrxqH8SB-C8Ix9zMTuOlfhx-kkZKPE2nOcEEIud4yIMhAwGAAg4aWmnltpBpsW5cayVOZHFCmMWucpyy8AAjoM4BkBAcD-kG77WacBF2fcnFyU5CnGZRC4CeZpggFAMhuhlfogIGAX9EFA7vvl-72ROjlJkZLlAaZGGLEWQgtZIuVYrZXWFQ5XElf1qbxUN7gACrgAA5mQ3BQBAD5whc42bm1255dN7GzT1819TOA18RVZmYSAnremAnrcC6R2vidHXneFdZXcVN0AXdJkPS0vAWdRX2ctyWkSaFUlEXNQP_uRZVKStyytBZMOTTSnUXRyRVRc56PFAAukkaYNNCi7eP4gBXgYAbI6ABvKgBGxgFH4jkTyRFZkuQFNFJQlmYFhWDYdiDeD7jWJ6HAAF4UDlP0hVGundUeqPCw4sXODTcoJQQJAyJ6IAcIUKtw8FCPqwVxMo6TpWg-VHKLoyzovQWAD6hCe8ronW-1aufjNDuA07i0xY0VP67K8q0u4gAWEYAPBb-ME4Rc4TbYyekAv5GjeAG-UlQSzUqDS27lUdD0VvasHtuh7zwqO0hztLZXpyLtcrSrXjquNzz_25wZC23eTzix7r8eNInywM34gAhGYAIJqAGAugBMaYAhfpZ39Bwjyo-dC40xcmqX1RS_dVdmbwjJwBwXK8CbMiwOYhAbf3QenVNiMa5dWuR-POKnc6bVzIHAQY1hkrDDIArF07867iRYj_e2pwSZtyjnHYBNJFzoUGPmPBH965fwJrvZGEd0GAMwZfLulVVrPy5AANXAF0T6CD4ZILtmHVBrdDKUOnlgiMi46KMjIBtdCMgSCMjlvLAshDEE2WQVwlu5DeEgw7tQkBZl2ggEGC9e-hA4SDA2uQV0d9ZFsJthwpuw80GqInkAjR2DKrXhAAAIzIEIR-rIX5wLkewhRnDm40lsWPNRDiwZXxaCwgAHoMRkfjLEBOsdJEJwN7FUIiTQsyAAlMgZtJEzAsQ3KxQ8Uk8NCek_hjjBG0LACARktUFAQC6DIKAHiEnFKSaUsh_8KFhIya7LJLQWRgFgBwVYHAyC7RzO6BQAZPQdOIRGbOZSVEVOjhjZwbk54EC6EuAAtDMxZv1FFBIjKkwu-tFJbKNvgTCvAVQql4MckO3S9JrLSRsl2mMZbLC6IMIQYyuggA2oQbaLzB5hVWb0uxXz1GZM0cMsgriwCDF0RCkpUKemRT6ZUvYy1fkEBVEuAA8hirpWL3kwvWVczZhssYEHEYWGQltA5EJOYEmx5TPm0u-Tchl-AACS4EHzkrOqcrlHzLm62ufSwl-AWltIgEysFUgxnAC4P5IpSzkgrOxb-GlMq6USG2YuNUKI2XyPFZy6FOLYW8vhYMxFSoXRkH2VI7yvjtUcuSfq0ePKjX9LwFPfFSQE7018IEIIgABi0ANK2O8JV735tkAuOsT5iyqJLWoAiFRmVwbAGJ9JuBqrFd_G1frerSr2LKk1tynnPO9a8ylms7WGurcavAprnGCotRpT-Pq3ktoNQG9tfK5WRPcCqQV6FS0kMTRW66Vai41s7bc7s2TZ3LNIVS1tI7l0dtpvK3grRN26u3UO_1S6SgUhjtTGezr56RsAHAqgAL1MzqLPV3DAaH2lemio4tz7Zuqbmlod4aozIWY2yFSMd3DqveSA9Zz2yVR7rwPuUHMUwYvZWnWo7HU_InfCTCh0MMUqw3_Xd8G9ZVIRU4syvcwAyAAFYgFsKR61vrYOXtw_usdtaBX0iZBcEAAhrwyBqqeys86uM4bJuEp1dHQOMkZL6LKknJCfuw4unj16-GYBDUXe9in3AL0ALRygAl6zjQm8tX6tY_rTaLf9mby51AUzUsyKoZ3sbLZxrT2s5MDII0M9waHsmCpI5a_xHHB0UbgzphDQb9N3rDbPRcgBb6MAM_pgAx6MANRKGcIgfvPcElG9nj6ObPlmiuwHMyVS6CSsl3m502b8wAxLhmc01bMvtCLfb2VNvI-Hale7dN8dXQK-5PWrID0w7_QblH4vUdDdV5D19caNa3dJlruK4U7YkAZkbSWRa4BODs_AgB75UAMeRgApxKYKibmzafgo3UFoXQ-g0wZrLhfcdIH3CAF83QAS26AAEdQAFwmXau9Z3zxXv0pqPvh-CFWXMdZWy0dodSoDoThLXSLiTosPbm3FgLNG3M_eWO0QYHA2m7VRzVfZGOse9atT5mL-PuOE6W7R9zLRBXtHU28TbsXWft3k0Fh9BBrzZMmxyfGG3msC9k0LwL_L5WCcZNeQVvdecEE03L7TbP2vLZcJVLxz9TDU6gJr-7A3bPzb10dg37lKpm_2VIUgABqV3Fvtcs_lxgonIvjOJSfi_CATu6fu890V73uuFd-6V4RggcJokcAkfs1xz0pkQA2mj53pAI_86j_5mPeGHD7cOCl0X-BACLeUD0H12IfM75iVmHv7ysAcq65_3nP3Bq72Xn2XBfWt4v1xzkndZvLcDAKsJqsBUpjXW2e_P1uCdF-H8TzrEMuSTMIFIAQzT6mQex503HVvlFDaoyuw98f8Bhd4EuPvkOB_bYdcLuPwXEqyGsDnkg9-G-n5tyvu3EfdfdwOEVxIQMxQgL_H_PHJfQXX3dnNfZHELMgJKAAJl4BQP2QYS9GgJPyhzPwWwvyQ0NzMmvBJWyTv3nyk371gJ9z0140nmS1f2AOWGr0AAtFQHMHevGA-CJvQWFvWeJzT7IDIApA5YWAfZT0MFXA2bWg6PeA1fTvUfKqepIQAQQAHgUZCUE_9l8FDADECSCudCBVhuRt90pWhvI1Vk9CAD8GcosmceD8D_89CEtGDFcglTsAcOCuDCtF9eDod-CHNBCEcvsDCHczJrh2gVR9lMctClEnDdD6CDsS9qZ9Ap5KQTtFxAAEtMAEHPW7fQS3WQ_eFYZ7HQU8d7IQwDKrb7FgggavQABCNAANFUAArjVed9WeL3RvAI1NMrYItvRHe3U7LoQVSyKXabMjWQnQuApIsvQYxcYY0YzUftfrSYhI6YtrZIvbJgmosQggAHJo1orebgvAiKPOZvII4UEIkQsI07XJcA6JMTF6OI4gx7KVQg-g0vA2cNSqavQAQitABo9UAGCvQANeV2iHCTiAY7NzjejLj-jQilDaj8AABpP2QMGQVYVYZ4yVAg23VwlI9w74syAHAEkEo43wmg_wqEwImE4JK46om4xcC4awKAC2MZAsCAJ0L0AsL1Q_HVagh_OQwvFwxbCAT4ozLvVg_7A4tosIMkjoyPLoqknouHH4OkjvZggPXZHgMncAc3KgjTBUqYugjYvErY5_dIsYTIyqQAG0VABnPXyP5Ib2KNUBAA0DKLezu0qPb3L01Kr3-0ABHowABnljjVjTixRSsVSS44TriETdi2he0ptljoNQzFTnCZiT5L839BILg7wsTbVEiTSMyXjTs4R0IvNeSB1HDzluVz9EMu16MLgN19S-cKS1jjSh99DYzDDu9rxKCKyVjtC2z5D0zb0CTUsfj_tABu5UAHkFEMwcsMg-aEyM0-aM-krs8IjCdoa8PMhdIU9MglK_HGdCbc5srXQ0ocvcwsg8rM_AekVxDgOEFUHcmTYcws0c2PDwxcAHIMuc-IhclYCMl_VU1c9UnYiUggB8O8BMsYpMmbec1Mgsjs004NbY_jX0gHGc38pDZ0wC9wqM5zeEjU8C_AOEOEBtfs5M-CyktMq8pHbs7GUiyXJYvrSiv8hC9YpCkUz4tI3AfYCmAAbjQBkEZDZMICQHnDGVgBEBmm4GiVgGoAAHJMJyDrxrhlUSVWhWglwlwIAKDb84Rsl0JqIIBb8nlyCABNCAXsgADWnRJRVAUtRE9EGFcVkvkogAUt4C8jACkDIGoFMD9EZE9EoAAHoQq3QFBLBZAMSGQ5YwEfLTAAA6BQDacKuZEK70GwhQAQfZEQJPWQQgEKxy_QNygULhVYAsWAXgRWPygcAAFllE31BUUt8tdDIDAAUo9P0GctcrIDkrKt5iasIBapsAn06oQIgB6qEBdADEUoCtgCCtCrSrACivRNWFiryXioqGSrAFSoirAADAypsE9Gytyr6otgLCKt4rGFekmWCoukEBEUUucsIFcQgXemKokBgHgGoG-pAFRDRw4F0VqDUGYA8ryAAFYABSBSimJyhQdy7yNpCZMFKAVEHgRkaqeWe66kCqqQYGjy1jXy96BQcaxQkQYADxe60CrAL4xoMANQRSnIaGz64oMARSgAZhZpLAIjYtcQUDaTAEwgpxfmoFQJpOcHAPcSEDYsY3gG4EUvgDflGvviEDJuf07MzIkAZs5u5vpsUqyDUBhpLClo8TYqGsUrAA4A2gCvVsDQmq1rwB1o8sNuNv1pdtQLdvqFNplqQw9nllEsUq8lgHljaVZvqFvigBZLfmoA5rnHlhEFdGoCnyEG9AlocF5qQ35rAEFuFqgFFogA5uPlSLNPJAMH4qAA)

### Steps to Reproduce

1. you can see the error directly  '图像分类对抗检测'  location error

### Current Behavior

sunburst series-sunburst.label. align location error

### Expected Behavior

 '图像分类对抗检测'  location correct
![image](https://github.com/apache/echarts/assets/52785710/9e71d4ed-82f8-4130-896b-4102e4594070)

### Environment

```markdown
- OS: windows 11
- Browser: Microsoft Edge 115.0.1901.188
- Framework: vue@3
```

**Comment by MatthiasMert** [comment]
As a workaround you can set `startAngle: 89,`.

**Comment by TifezzZ** [comment]
> As a workaround you can set `startAngle: 89`.作为解决方法，您可以设置 `startAngle: 89` .

tks very much
