### ISSUE TITLE
[Feature] The width of the item varies with the axis

### ISSUE THREAD

**Issue by rick-chou** [apache/echarts#18981]
### What problem does this feature solve?

I want the width of the item to take up the entire quadrant and not be a fixed value, when using dataZoom I also want it to always fill the entire quadrant I looked at the docs but couldn't find it, am I missing it or is it not supported, e.g. setting itemWidth = '100%'

https://echarts.apache.org/examples/en/editor.html?c=scatter-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurAIa54AyZARgKYA2RqppZjEA5tEQOQBjetDD0ATnxLoAvgBopsPCE5gqEaPRYL060WIBuHIgAZ5bdHgAWwAO5EwYgK70z5zhoDKYAJ6NNxc1IfEH8-ABMyK3owyUDpBTkFCLAyIiwxMTJvADoAMzFgAFsACiRYP2guMEsiAEZjWGkASm1YPIhGRmLjFsDswrIQYuKIWVgIMIwmhAA-ccnextcwYGBGWmAMLTYrW3snFwVc-jIwRzF_VnNksgAtVcLtwNhvHHwASWgw-i3YPmgYPRYuZEoELngVhcWKDzHgyPp6Fg8O8BlxLvE2DD0GJuJYwEQACzGEgwm73IpEADaCiubGCoTwnG-ElcbFyHT0AFlgN9-DYTgBrABiHPEfFZpF2NgAIqcyB5LGQwntYLkOHhDoEpdL6CkOkQ1YwNRL0BswCtHrB6gkJbSgt4QvxGRMxSaXm9kV8fiY3ezGFyeaF-WRhaKWa0cVw8UQAEymVra3VkfWq9Wa8y0JxWDxMegCfGpo30BIkAC6rlelCe6BuVL472lVAAouK_gBxLBUZsAJQAmrU-OWFEoVGoNNXSLpxIZmLB41rrHZYA5nG73PQvL5Lq10PT-BEojFWhjSCeYSs1pAQBOKPgAArAKdiCe7h2hAQFPB4YEyEnyEgaji9CELA1JsHaNZylSO5_A2zbijBfAdl2TZ9gObroPWjYthh7adj2_YIc8sHYURzxIfhqGEbhWHwTRyEEehiFwThiEMVRTHEbRrFcexaFkYE3E_qQQ6BBAoiFJufgvqQAhrMAz5_AAxGqAgABwAKxqQJsIOMAAr0AA8iAZACOJ3gmNkam4VYSq2AAwvJil8EpAhuTpOyKsqNgAEKMOcdTzs864AOoTNUsa4euspWPukSWNEwkyG6ogYAWfAxplHnlHQTDdnmBZlL8RJjBZsBxmMNjhTU5WmLACW4gWRINFipAXPmLCYISdVlRVsBVWEEW1WMDVRk1xgtSlb5OgIpx6NlHDcLwfyRni2V4N4hQbLOfDtWA62bdtHgQAAXv4lIaXVl2liW6A3dIADcQA

### What does the proposed API look like?

itemWidth = '100%'

**Comment by helgasoft** [comment]
Why not use Heatmap chart? [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian&code=PTAEAcCcFMBdYJbUgWgQcwHYHsYCgBjbTAZ1lAAtsBXSE0AXlAG09R3QByARgCYBDTgBou3QSM4DhXAMziuAFnmcArMoBs4th04B2ZQA5lATmXcADGbHDt7Hr3DSejiQ6cyXiz6pe2u6711vA29jbwtw7kc8AF0AbjwQCBh4JFQMHHwiUnIAE34AT3omVg4uAGV-WFp8gqcAMUgEWqcAFQpaEhahP04AdWhczGguwrbqEe6uAFliKc5y6kwW2ISkqDhEZDQsXGhCYjJQfNh-RhZmcxEr0BUYkUuRbif7lhvea9fH0BlPh5uFH83iIVEDvuowTddJCRAYYaBjPCLEjnqBeF8bnwRAoMU9fqBuLiCYCCUTuKCfmSIaAcf8ntDQOoyXCaWTEay6WibjIibxUTzObwPmjefi7g9UVCvqjJdKRMLzHKfmDUSTFRKQSqRNT1SxUQzdcxUSzDaj2aanjdxXqnqj0RqCcL7TaCfimQ7uCTjErybafdT3S7uAzdD6WQYfey-EreFaY6jrUb5cLQw7ePjncwFS8HsKZV8nWDhfjDcK1QXNaBS9qiyIDRXQCaG-aG8jKbnbfLW3nW_jvR3ibDWxSLK2A62GYm8yyp092bOuXWG3zscuncv8bSWCWlw98fyvhmwfiS4fscfK4a3RfQPW97Cc9uRC37wS46_uKqz47d0_XU8t2YfcSW4AU_19R1v24al-3AycoJnKCoyveUbkDID5S_V8hVXbD9y-NVH2YECRDA4j5TBElTweElyxoytCXoxlKLrFjGzY9lMxAgECM7DkWBA9cmNA3CBIA0TyIJEdAJA6lo2EhlGLEglw14gl5zU2NSM0_VNOLTTqJYCl3i-EciIpBVTNI7SHgpOijMvKzmKrJy7wc9iRVs58wRHHivIJfN_KxW4nJEt9QpJRMRwpVN3Ogv0goZdCRybIKNP8rT23cld-OYCyhOywzmB1Ii5LBalLIeakiupeziscqqaxcxrb3Kh9mpYGC2rfUq-MNOSCvq_9SRaz0bM6p47K-OSdWm-luu4VKJvU7rMqUoacszCrBoqt0YhiPwADoAFt-HAAAKAAzJYCEQYhQHOhBYGgY6AEpQAAbz8FJaEwFgnpeo1XgB47LmB57QfRUAAB9oa4FBOHiPAAF9XoSPBsHAO6_qYL72FgbBsAAG0QcAAC5Pr8cBsBIJ6EGICnOAJ6J2GRnp2HQJpcgpvGOAoaAMAoWBGZUcwAFIbDKZnGYsCXtDZ7QAA8AEFFYQEgeb8WACnAaBGYIKpoHQXA6nZjgTn4CmqE6M32BIcAiae5WYEtymyjtqgAHcKdgSAJj8ZH5bNgpVfVzWpZ1vWuAN57jcgU2_AtinahIW3QHtx3YGd6BXd5soSC9n2_f2MpA9Zs2ADd1eofgiemM7w44Y6EEwCmrj8U7FYp5E_ANomCGoIn-AAIyJqPfYmNPcCQTBha4KgmgAL2IU4icljgx8uufOAIaBZ-Qdf8cxmW5fL7QSGQJANZYPw844TB-GOqPOAABRuihQAAYX4SBckPjhta60ZvzKop1fDu2OFUV2Fs07sCHsPaARNG4QILtgb2oAJ4l3dgrCBL1wAUH4LTa-d8ygg3KNrMeyCIHpwIbkNBAAhImtBu7t2oRwAu_A6Ge0_sTXAjNIDoGHvwc6NxRHXEOioV6nA_ClxkaAMuHAFH3C1oTImw9sBdzduwwuGDi5p0ujnaoMAqHsAtgALUJsdExHAQ5qxIAASWWNATRnAcDDGkRAnB7sYBkD2DzLx-d-AV2gMrBxp10BRw-gos-ZQmjoCFhTBQ5gg7aHMZYimpQOAkIwZHRmJBHa5APrA0Al0EAk2QLMQpjNPY5wANb1DKc9SA_92AgFQZ7AAIlA8otC0EU0urXC-xS2lew6XAfgZT-mDOgMU9R8BsBWLfMk0uPRlHIziEAA)

**Comment by rick-chou** [comment]
Thx! you help me a lot ! @helgasoft
