### ISSUE TITLE
[Bug] Incorrect text positioning when rotating pin 180 degrees

### ISSUE THREAD

**Issue by mispp** [apache/echarts#18987]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurACYCGYFRA2gOQBMADAIwDsAtK854wCz0ANLCZsuPPgFZholh269GANlliFkxu3oBdEgF8hJAJ458RJIZJ4ApgCcINwrFol0qAJDowxkDaL0AMYU0GQANk6QgQDWwm6klNR0KB4e8aTEGVmwAG4UYQCu_i4sIgDM_CI85QAcetnoVg2Zzbn5RXT8zOVS5d2wUsz1DU0NqK1thcW0Zay15WUi_PzD2aPZ4615U3RlNVW9A0uMq1n66bA6Rl6wALYUdtEACsAQ0GAWJKmJNC5fN5tUjdAsBgHYyHRGAsAHQrIzoIHoPDGW4AI2AYSIACIyBAKLcYGQsddUkiUeiwgBlCAAL2K1X-NwgYBst0pPginwRpNIILCYOxAGJmCLRVjGY1_o14bAeYCeSCwRCXOoJEoZCIWLCrhLYMi0RjsSA3sTddsOrAsRRrRRTdybvqKQAlYDUFlEVg1ZhS2Dnbl6G5-0hBvT6ADcQA

### Steps to Reproduce

1. Normal candlestick chart
2. Draw a pin at the bottom of the "low" value
3. Rotate the pin 180 degrees
4. Put some value in the pin, e.g. "aaaa"
5. Text seems to be vertically positioned higher than it should be

### Current Behavior

Text in the pin is not vertically positioned as it should be:
- When pin is pointing down, the text within the pin is centered in the whole round part of the pin  [OK]
- While in rotated pin, value is shown higher than it should be. [NOT_OK]

### Expected Behavior

Vertically position pin properly.

### Environment

```markdown
- OS: windows 10
- Browser: Firefox, latest version
- Framework: pure html
```

### Any additional comments?

example of correct text vertical positioning:

![image](https://github.com/apache/echarts/assets/6314582/0f1e3a73-5f8b-4251-b9c4-eaee92b5c8fd)

example of incorrect text vertical positioning

![image](https://github.com/apache/echarts/assets/6314582/bbfc23ae-7e6e-4c62-aa61-060cf85cea21)

**Comment by helgasoft** [comment]
Adding ```label: {offset: [0,11]}``` will have it centered.
[Markpoint.symbol](https://echarts.apache.org/en/option.html#series-line.markPoint.symbol) could be anything, so label centering is not automatic.

**Comment by mispp** [comment]
@helgasoft  thanks, this solves it.
