### ISSUE TITLE
[Feature] When the tree is displayed, after the width of the child node is elongated, the height line of the outer frame of the child node will be automatically thickened, resulting in inconsistent line widths on the four sides. Is there a solution to this problem?

### ISSUE THREAD

**Issue by FrankWasHello** [apache/echarts#18989]
### What problem does this feature solve?

![股东链图](https://github.com/apache/echarts/assets/34059274/ab5f35a4-6d74-4fe0-9765-e062566912ec)
以下为设置参数：
[
      {
        type: 'tree',
        data: data,
        symbol: 'emptyCircle',
        orient: 'BT',
        left: '3%',
        right: '3%',
        top: '12%',
        bottom: '12%',
        edgeShape: 'polyline',
        edgeForkPosition: '50%',
        expandAndCollapse: false,
        initialTreeDepth: 15,
        itemStyle: {
          borderColor: '#070707',
          color:  'white',
          borderWidth: 1,
        },
        lineStyle: {
          color: '#070707',
        },
        label: {
          position: 'inside',
          rotate: 0,
          verticalAlign: 'middle',
          align: 'center',
        },
        leaves: {
          label: {
            position: 'inside',
            rotate: 0,
            verticalAlign: 'middle',
            align: 'center',
          }
        }
      }
    ]

### What does the proposed API look like?

At present, no solution has been found, please help the community master

**Comment by FrankWasHello** [comment]
echarts version 5.4.1

**Comment by MatthiasMert** [comment]
Pls share a minimal example. Your code doesnt produce the output in the image.

[Here ](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=DYUwLgBAJghmMQLwQNoCgIQN4cxAdjALYgBcEA5AIIUA0umAxgBYCWwUATiPuennhwCBhEuQoAhOg2Et2XHnxnDsylQWJlKAYQCM09bLYduvVGsNDD60VooARA9ZVyTi888sXPmW-ICiTj4uxgpm_MFekc5-lABiQdEh8qZKSc5W6daxFADiFN5ZAL4AuoXBpeWGlZE11kX0GVUaYjoATIkqRd5lXTK9EN0lANxoaAD2AA5grOP4SKqYAM4gnKwgS2mCamAAnpN2YNwgndBwMOSw8I3C42s8YOISACqnIFAA5iAAyswwB-JJuNgLtgKx8CcbgJwawZjBgM9jvYQNNmORdAAGKF4Ja7IgAI2B4m4jDAp1xBOB31YAC8tABmDEybqYMpFYZAA) is a minimal example that you can extend.

**Comment by FrankWasHello** [comment]
> You could use [rich text formatting](https://echarts.apache.org/handbook/en/how-to/label/rich-text/) instead:
> 
> [Here](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAUDGBvHXGMBAWwFMAuGAckDu3QcAtBuOUGV5GgGkNwBsEAjct2oEiRAGYgATqSRRyk6jTx8QADwA-ygL5aOXIgm4BLAOZhFwcmDmS9o3Cslx5AdSNwoAC2oBGTvZhHZ0kAYRBuKUUAYgAGAHZ4-Lt7SSNgb3x9URVVYSz7AHd3L2oAVhiY_wCiT3JTTyhqAGYY_NwtfI7RLpgOgF0AbiwsADcESRgQAAcoI3A0TNwIeSNyCGpsURF7KABPKapaKElycmTRRGRqS4Qq0SlV60UAIQAVc6JyOBNyAGVPBAHRRTcK7YxgM53IgQXakFRCWhgcCQ_JGMBGWaGV4ncgAEXIMwyPlK-h6fSwWgGQA) is the example:
> 
> ```js
> const data = [
>   {
>     name: '目标主体',
>     label: {
>       formatter: '{box|{b}}',
>       align: 'center',
>       borderWidth: 1,
>       borderColor: '#070707',
>       rich: {
>         box: {
>           width: 500,
>           height: 30
>         }
>       }
>     }
>   }
> ];
> 
> var option = {
>   series: [
>     {
>       type: 'tree',
>       data: data,
>       orient: 'BT',
>       edgeShape: 'polyline',
>       symbol: 'none',
>       initialTreeDepth: 15
>     }
>   ]
> };
> ```
> 
> The source of your problem seems to be that the rectangular symbol is squeezed together by the `symbolSize` attribute. Also only using [label formatting](https://echarts.apache.org/en/option.html#series-tree.label.formatter) doesnt work because [width/height](https://echarts.apache.org/en/option.html#series-tree.label.width) doesnt aplly, which might be a bug.
> 
> **EDIT:**
> 
> You can use only label formatting if the [backgroundColor](https://echarts.apache.org/en/option.html#series-tree.label.backgroundColor) is set. [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAUDGBvHXGMBAWwFMAuGAckDu3QcAtBuOUGV5GgGkNwBsEAjct2oEiRAO4BLOFAAW1AKwAGRZ1G4Z5CQHMZUagGYVXInxAAnOOTMB1KbOoBGVWtMWrAYRDdz1GgGJFAHYgoI5jXD4EYABrLTMQAFcwOE9vM18xGQkochpjAF9CQoBdAG4sLAA3BDMYEAAHKAlwNHxCCCsJcghqbFERNSgAT3qqWigzclznUURkajmEGaJzLrA9WgAhABUwtRhyOC1yAGUZBFHfeq8h7gkwafCYCCHSUyFaMHBH_fvsiQQ3G2k3IABFyI05DAHPICoRilh8qUgA):
> 
> ```js
> const data = [
>   {
>     name: '目标主体',
>     label: {
>       width: 500,
>       height: 30,
>       borderWidth: 1,
>       borderColor: '#070707',
>       backgroundColor: 'white'
>     }
>   }
> ];
> 
> var option = {
>   series: [
>     {
>       type: 'tree',
>       data: data,
>       orient: 'BT',
>       edgeShape: 'polyline',
>       symbol: 'none',
>       initialTreeDepth: 15
>     }
>   ]
> };
> ```

Thank you very much. It works. It's great.
