### ISSUE TITLE
[Feature] 希望bmap支持webGL版本

### ISSUE THREAD

**Issue by bxb-l** [apache/echarts#18982]
### What problem does this feature solve?

目前bmap扩展不支持百度地图webGL版本

### What does the proposed API look like?

希望未来bmap扩展可以支持百度地图的webGL版本

**Comment by bxb-l** [comment]
我稍微更改了一下bamp这个文件让它支持百度地图的webGL模式，但它将不支持其他的版本。但是我不能保证它会不会引发其他的错误
[bmap.zip](https://github.com/apache/echarts/files/12318538/bmap.zip)

**Comment by plainheart** [comment]
Duplicate of #15210
