### ISSUE TITLE
[Feature] valueFormatter 回调函数的参数增加 dataIndex

### ISSUE THREAD

**Issue by aqnghu** [apache/echarts#18997]
### What problem does this feature solve?

`tooltip. valueFormatter` 的回调函数 `(value: number | string) => string `  只能获取数据，无法获取该数据的其他关联信息，希望能增加dataIndex 参数

### What does the proposed API look like?

增加回调函数参数  `(value: number | string, dataIndex: number) => string `

**Comment by theDoinb** [comment]
`dataIndex` 是确是有用的， 例如我的图表只想体现变换率，同时想在tooltip展示原值，我就可以用`dataIndex`去取值并格式化，如果同时展示两组数据的话，变化率很小，原值却很大，会导致 `Y` 轴的最大值并不是我所期望的。

**Comment by ChepteaCatalin** [comment]
I'm interested in fixing this issue.
