### ISSUE TITLE
[Bug] 关于markLine使用data设置symbol无效的问题。

### ISSUE THREAD

**Issue by SuttonSteele** [apache/echarts#18993]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRARAMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEkDknipGqhWKNRSWCEwEX8ADgAmAAYeWABOAGZIuPjogEZUxIAWOPTItLzExNjYdOTo60dSCmo6ABsIaGVq9ABbRg4AawAZJppiIMFhMUCh9HS3fnHYPHI2gCNgeroOKnowWmmgjxmySgHaRgA3b0ZWZW3YO1sd-1s7IA&_source=echarts-doc-preview

### Steps to Reproduce

1、打开官方api文档
2、找到series-line.markLine
3、找到data.1.symbol
4、点击试一试，设置symbol为‘rect’
5、可以看到示例预览中markLine终点没有变化

### Current Behavior

我在做一个动态的折线图，需要使用markLine标记出多条数据，并且为每条markLine终点添加不同的symbol样式。
从文档api的试一试中，给出的代码没有达到我期望的效果，我感觉可能是一个bug。

### Expected Behavior

希望可以使用markLine标记出多条数据，并且为每条markLine终点添加不同的symbol样式。类似于下图所示：
![1692074114434](https://github.com/apache/echarts/assets/40020021/12f2d06d-aaa8-4568-b0d4-0afb2bcecba2)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
After some testing I think its working as expected but the documentation is very confusing. You can set the the symbol for all marklines via an array:
```javascript
markLine: {
        symbol: ['rect', 'circle'],
}
```
You can overwrite these symbols when providing the `data` property as a list of startpoint and endpoint:
```javascript
data: [
          [
            { type: 'min', symbol: 'circle' },
            { type: 'max', symbol: 'arrow' }
          ]
        ]
```

[Here](https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEkDknipGqhWKP5iUlIhMBF_AA4AJgAGHlgATgBmKPiEmIBGNKSAFniMqPT8pKS42AyUmOtHYLJKGlkAGwhoZRrggFtGDgBrABkWhtRa0jxyDoAjYEaxWg4qejAVeggOekblasDg0PCAkeCkOuo6RgA3b0ZWZVgPA9J9-9IjihPZDpaZMcnpuhW1ja0W7tJ4vep0LoYL7jKYzWTdDjAADuQLs21qtnumNqaOCuNgtjsAG4gA&_source=echarts-doc-preview) is an example.

**Comment by SuttonSteele** [comment]
如果我想要使用固定值呢？

**Comment by SuttonSteele** [comment]
抱歉，我没有注意xAxis和yAxis只能对数据值是一项的设置有效。如果是两项数据，就只能使用x和y值确定位置了。

**Comment by MatthiasMert** [comment]
This is also valid:

```javascript
option = {
  xAxis: {},
  yAxis: {},
  series: [
    {
      data: [[0,820], [1,932], [2,901], [3,934], [4,1290], [5,1330], [6,1320]],
      type: 'line',
      markLine: {
        data: [
          [
            { xAxis: 0, yAxis: 'average', symbol: 'none' },
            { xAxis: 6, yAxis: 'average', symbol: 'diamond'}
          ],
          [
            { coord: [0,950], symbol: 'triangle' },
            { coord: [6,950], symbol: 'circle'}
          ]
        ]
      }
    }
  ]
};
```
