### ISSUE TITLE
[Bug] Data could be ignored in stacked line chart.

### ISSUE THREAD

**Issue by Kaiwen-Zhu** [apache/echarts#18992]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeBYAULTXMA8CCOEAzgFzLraWwAmAhmLWQNoAMANLAIwcBMHAzBwAsAXTYUqsAL7iMkgJ4FiZVHMmwiAC2AB3MmABOAVwCms9ZiIBjWgBsT-42dgSqM15SImDEE6VhMHlSqFlhg8iAOsABEthDQJtHmoRoMVgDWZNE4SUGStAYmtADK4fYq7moW0LQAtlHReLlV6nQMzJzsXNxcfFyCXKLJ6pWhISnhkVlxCc0pqbQZWTnDFgVFpfLlyKMpNfVZAEJzKW2MAQAcHACcHJ13PZw8YnnYUq-wLy1Y9gDmJtBqMwPphxqEzsxGkkYscvvMcFkrACwN4TqF5FkWABSNEWLz2KwooE7VbqLS6RymUmUXZUOGSMDAYC2ABGwAR5G-2HJelghipINgwB8yKy2h8AC8YAxbLiqBAUbVihAJVFOABWanYBUmWoAcVoIDI90FPl-mjAWU6OK1WAAZkUwEZCipBZgzgAtJm1V1cyQ8ylmN3SW2YWk0jgub5SADcQA

### Steps to Reproduce

1. In the link above, some data is missing, as shown below.
<img width="500" alt="image" src="https://github.com/apache/echarts/assets/90447017/4f877963-fa01-4210-8625-aec28193f92c">

2. The data is complete only when `yAxis.scale=false` or `toolbox.feature = { }`, as shown below.
+ When `yAxis.scale=false`:
<img width="500" alt="image" src="https://github.com/apache/echarts/assets/90447017/b3f20c0a-0451-45e6-9d8a-29473d9d852c">

+ When `toolbox.feature = { }`:
<img width="500" alt="image" src="https://github.com/apache/echarts/assets/90447017/ec0276ae-ab46-4914-8f66-f58c0d118496">

### Current Behavior

When `yAxis.scale=true` and `toolbox.feature = { dataZoom: { show: true} }`, data of the second series that is smaller than `10` (the minimum value of the first series) disappears.

### Expected Behavior

All data is preserved when `yAxis.scale=true` and `dataZoom` feature is enabled.

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome, Edge
```

**Comment by helgasoft** [comment]
#18506 duplicate
