### ISSUE TITLE
[Feature] How do I make the pie chart rotate toward the center of the circle instead of toward some consistent direction

### ISSUE THREAD

**Issue by RuStealsMelons** [apache/echarts#18994]
### What problem does this feature solve?

Here's what I'm doing
```
option = {
  series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: ['20%', '60%'],
      label: {
        position: 'inner',
        fontSize: 14,
        rotate: 30
      },
      data: [
        { value: 1, name: 'Search Engine' },
        { value: 1, name: 'Direct' },
        { value: 1, name: 'Marketing'}
      ]
    }
  ]
};
```

![image](https://github.com/apache/echarts/assets/120147243/d659e923-f393-46c5-856f-44622215b7c2)

And what I want is the following

![f088d254657e5f64d8569353ad8b7877 拷贝](https://github.com/apache/echarts/assets/120147243/10dc2420-db40-405d-984b-d0e54a75c01a)

### What does the proposed API look like?

series.label.orientation = center

**Comment by plainheart** [comment]
Just set `rotate` as `true`.

**Comment by RuStealsMelons** [comment]
Wow, he can actually do that

![image](https://github.com/apache/echarts/assets/120147243/e30426b5-1548-42dd-9fb9-215db362dc61)

但是他和我想要的效果依然存在一点小差异

**Comment by plainheart** [comment]
How about set `rotate` as `'tangential'`?

**Comment by RuStealsMelons** [comment]
Wow, yes, that's right. Thank you
