### ISSUE TITLE
[Feature] Linkage charts display their respective tooltips

### ISSUE THREAD

**Issue by rick-chou** [apache/echarts#19002]
### What problem does this feature solve?

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOTQzX3EC-ANMQIYAeEAZwAKwCNDC1CqErAEALYAHdCYUgFdqXGQOjcCZDVpLYx1AMpgAntmpTiMqyFux6AE27zqr1jM72ylDSkACpYuBD6AGbc2AKa_tjcAEbU2HYy6PJKKurxGbAAttykFGKEAGxGMkncAMYA1hSkwGrQrgDCOMB0LgDEAKz95fRVJLVdPfS9kTM-JH4yJtD1hADaSLC8AIL8AgCSbdS8awAMHLAAjOcATOcAzAC6sGwP7Ebbu2v-0hlNEK4HVxHQhnfzoRzOei1bgSCjdSwjMGwdxgbhregAWRgIxcwQ0OPoAHUvATgnI1ASAGLkAlmGG01r0V6-UY_GR_AGHY6XUbgyxOBjQ2HwxH5FFo2CrTHY870PEsWXE7yyskU2XUiC0-mysyM5nzVlIjmA4GwW5IiGCmHUOGkBG85EwiVSrHQUn4xUklXkqk0nXaly6t369ALEhskjGrmEO4Oy0uIU2kUO8Xo13uhUuJWkn3qv2BgP0INM_xsYgPIyWHaCL4yDZRoHcs4YfmQgBuMXxz1ZsAbpquLYFLg72C7YfQ9fInMbhFug_bnZY3e-vanJu5sfnDBHY_LRg5tfDsBskTADAA7ABSHGYfT0K84xT_MByBh3AAc1_OcmolDkZ5cD9r2XOtYHICh_wvL8MFAKDH2fV9AM_HEfz_AD6CA-gQKPE90Ifc4kmAMBMAKODzifVwXzfZDv1_CD0Mw7CJzAtCyNgQjiOAUiXHw2AKKopDoNQ-jqOAst0ArYg4nIagBEPCckVTSULn6ZtrjuNTrgAFhuC533OC47n6AytPPG5yhOST8njeglgVJEPkEdcQQdKtdmc2ATlLQ0xSdNYVPOfodNgLT-k3MLAs3bTzi0qyMhsuzRQyRz9mjHkkTcpy0oubzvkUvzJS09SYuKs0SoMoyTLMkLrjihxWwYRKHRSjzzXyTLUpnM1crrfLUTWIqbmCwazT0krgouUySseOMGpcJqHOrTrTVjDKlo8u5S3LFA2AAbiAA

Is it possible to trigger the respective tooltips in linked graphs？

<img width="870" alt="Screenshot 2023-08-17 at 17 26 51" src="https://github.com/apache/echarts/assets/56244178/1c7ce2e6-27d7-46db-b44f-016dba499cbc">

As shown in the figure, I hope that each linked graph can show the same effect as the first graph，The yAxis is now only displayed for mouse-triggered graphs 

### What does the proposed API look like?

/

**Comment by MatthiasMert** [comment]
You could try to play around with the [`highlight` event](https://echarts.apache.org/en/api.html#events.highlight) and the [`tooltip` action](https://echarts.apache.org/en/api.html#action.tooltip).

**Comment by rick-chou** [comment]
Thx!
