### ISSUE TITLE
Border display problems for "Bar Chart with Negative Value"

### ISSUE THREAD

**Issue by bbslzy001** [apache/echarts#19001]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXLANprrJnmxgCeIApkQOQBuAhgDYCu9TlsAXzIBdADRkaOfEVJVUVdLQbMAxmzD0A5sABONJuIWwAJurYymAWRgHYTACo9bTAOr1jz-wAsuzgGI6EM4AyuohXNBMwvxC6GJkePSB9IQk_PIK0GwAtox2AJLQKsC5BvyKdHlMAEZsOmVGeGBsKgDWzPbAzRwNChAa2cG0HHkZRsUcusw6mrUAFABMAKxLorAAnOtrAIwAzAtrAAwAdEsAlL1G1brGSQDCwJM607OLK2ubO_sXhkaw1zpbjoXBBjGAvEQFuVBL8qPRsiAvGw8NIKH9YAAzYAqLipJiJZJ4PhGASw8imZoyfaHI602C7ADsABY1rt1jTYEylhymQtDtEqKT0tCsrlmABRDAMaCJIlkirKOy1ery2BNFrtOydbqXcj9eFDGgjIhjBQTKZ2GbzBmrWDbdYHO0Oo6nH7Q9AAoEPJ4vapzG07Z1OhZu9GepIgsEQ2BQkmq-GI5Go01ULE4vEEiApYkKIVGCnmEgAWgWuw5RfL20O2zWRb2LNgdfZtfLCyrAvIsVg0QEAG4gA

### Steps to Reproduce

Hover the mouse over any of the left bars and you will find that some left bars' border displayed in the wrong place.
![error](https://github.com/apache/echarts/assets/63188155/3f2ce0f0-893d-4a8f-9ed4-6ff4d363eb59)

### Current Behavior

I am trying to implement a chart comparing the amount of income and expenditure transactions.
The chart has expenses on the left horizontal axis, income on the right side, and dates on the vertical axis.
When I hover the mouse over the left bar, its border is drawn in the wrong place for the bar with empty data.

### Expected Behavior

For a bar with empty data, its border should not be displayed or drawn on the axis.

### Environment

```markdown
- OS: Windows 10 企业版
- Browser: Microsoft Edge 版本 115.0.1901.203 (正式版本) (64 位)
- Framework: Vue@3.2.13
```

**Comment by helgasoft** [comment]
Workaround is to do data pre-processing and replace all zeroes with _null_.
