### ISSUE TITLE
[Feature] 自定义系列-性能分析图在大数据量渲染时会白屏一段时间后快速渲染

### ISSUE THREAD

**Issue by a-chance** [apache/echarts#19013]
### What problem does this feature solve?

**Version**
5.3.3

**Steps to Reproduce**
1. 自定义系列-性能分析图
2. 接口请求，数据处理，生成option配置项，共3个系列，每个系列2万条数据
3. 在控制台打印options，各项数据都正常
4. 执行setOption后会有3-5s的白屏时间，然后快速渲染

**Current Behavior**

option数据已存在，setOption会有3-5s的白屏时间

**Expected Behavior**

执行setOption后马上开始渐进式渲染，没有白屏

**Environment**

- OS:Windows
- Browser:Chrome 114.0.5735.199
- Framework:Angular

**Any additional comments?**

No response

### What does the proposed API look like?

console.log(options);
this.instance.setOption(options); //  数据在控制台已打印，但是Echarts图过了几秒钟（白屏时间）才开始渲染

**Comment by qwekelly** [comment]
请问这个万级别数据的渲染性能问题解决了吗？有什么好的思路或解决方法吗

**Comment by a-chance** [comment]
解决方案：

**Comment by a-chance** [comment]
> 请问这个万级别数据的渲染性能问题解决了吗？有什么好的思路或解决方法吗
