### ISSUE TITLE
[Bug] Candlechart are broken when use Zoom button

### ISSUE THREAD

**Issue by Alfavisioner** [apache/echarts#19016]
### Version

5.4.3

### Link to Minimal Reproduction

https://jsfiddle.net/Alfavisioner/uy9r8fps/2/

### Steps to Reproduce

Just zoom small area of candles candles with help of zoom button few times.
Some candles disappeared and do not show. Look screenshot.

Initial chart
![01](https://github.com/apache/echarts/assets/44602189/4ed30e2b-ddff-4b97-ae63-c4e0e8e5a282)

Zoom small part
![02](https://github.com/apache/echarts/assets/44602189/f63937ce-b35f-413b-9e2b-2a13bc24ecee)

Some candles are absent
![echarts bug](https://github.com/apache/echarts/assets/44602189/4cc06da6-f9c3-4f40-8834-d8649185d543)

### Current Behavior

This is candles chart.
When zoom small area of candles, part of the are not shown. Candle stick looks like broken.

### Expected Behavior

Do not broke candles when zoom

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome latest
- Framework:
```

**Comment by helgasoft** [comment]
Please see [official example](https://echarts.apache.org/examples/en/editor.html?c=candlestick-brush) for recommended usage of _toolbox.dataZoom_.

**Comment by Alfavisioner** [comment]
Thank you. It is what i need.
dataZoom: {
            yAxisIndex: true
          },
