### ISSUE TITLE
[Bug] What does brush throttleType and throttleDelay do?

### ISSUE THREAD

**Issue by MatthiasMert** [apache/echarts#19022]
### Version

5.4.3

### Link to Minimal Reproduction

[link](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygiBTWBeGBtAugbgChCAzEAJxgAoAbdGASwwAZ9GAeARmZ_wYGp-AShgBvQjBh1YADxhYAskgAWAOnIIwcEAFsqQopOkwAnvJhKoajVt37D8JCnSqADgFcIyqqJkAuGBkAGlMAkwBfIUJw4hBXKAZwc3FJRGQ0KADsURgIEHdyYFQAtOdYcNwgiRhNBh0kRLAAkgQaNCrJACNyT2UAlMkYKBAQGk6QfxwAcnJUYCgpyurJK3IQKCg6ABUTV2KYKbhUcfcwIqmOwdX1zdQAEVQaBBMA7h535mrwy5kAQRkGBB-t9qiZ_oDgZc0OQGKggThlmJEStdvsphBgEgoKhyBdkbkTDpxjQAMoMABe-04AFZLoMYKgziAjv18ZJJlMZHj6fSXgcTFN8SD6cKYLhovggA)

### Steps to Reproduce

Any chart with brushTool and `throttleDelay: 1000` or `throttleType: 'debounce'`.

### Current Behavior

`throttleType` and `throttleDelay` seem to have no effect.

### Expected Behavior

If I understand the [documentation](https://echarts.apache.org/en/option.html#brush.throttleType) correctly, `throttleType: 'debounce'` should only render when the brush action is stopped and `thottleDelay: 1000` should only render once every second. 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Am I misunderstanding the documentation or is this not working as expected? If it would work as I expect it would resolve issues like [this](https://github.com/apache/echarts/issues/17079).

**Comment by helgasoft** [comment]
> If I understand the [documentation](https://echarts.apache.org/en/option.html#brush.throttleType) correctly, throttleType: 'debounce' should only render when the brush action is stopped and thottleDelay: 1000 should only render once every second.

Both are correct, but not in the same time. 
Depending on _throttleType_'s value _thottleDelay_ means different things.
It is all about how often the [brushselected](https://echarts.apache.org/en/api.html#events.brushselected) event is fired - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygiBTWBeGBtAugbgCgAzEAJxgAoAbdGASwwAZ8GAeARie_3oGo-AShgBvQjBi1YADxhYAskgAWAOjIIwcEAFtKgohKkwAnnJiKoq9Zp16D8JCnQqADgFcISyiOkAuGNIANCb-xgC-goRhhHCo1AimWBwwAPQpaMCEIC5Q9OBmYhKIyGhQ_tgiMBAgbmTAqP7FTrBhuIHiMBr02kh5YP7ECNRo7RIARmQeSv6FEjBQICDUYyB-OADkZKjAUOttHRJplmQgUFC0ACrGLg0w67ErbmD166Nzx6fnqFc3_uvE9GkACUkKhXgd5koTmdaAAROIJRoI0wAKhgXG4HTCb2kAEFpPQIDNsR1jPjCcS3mgyPRUEScBDZnN5tdbusIMAkFBUGRwcyJBBjNoVtQAMr0ABetw4AFY3hISRJcFEiNpjABhJQIMhQFTgSjrCZTNC0HaoOCvKguYQYAB8og6JrMLhUYyQwCU2CYuBgAH4YC63VAPV7cCoTdtuXBQyomgBJTSoWR_db2NWa7W60oAeRyfW883oX18TPmSbK6ygrN86z42Vy4Fdk08Kg-MO-rL46zmsXixhrfF7CS7VW2fLmEDcY250jKo-o0QV-iigiAA).

**Comment by MatthiasMert** [comment]
Ah okay that makes sense. It has nothing to do with visual representation in the graph. That was where I went wrong.

A feature would be nice like the debounce throttleType that only renders the selected points on release for large data.
