### ISSUE TITLE
[Feature] [en] Click event on line using line chart

### ISSUE THREAD

**Issue by n-osennij** [apache/echarts#19042]
### What problem does this feature solve?

For example I have simple line chart

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};
```

Line chart have dots and lines between them. I try catch click on the line using code from docs:

```
myChart.on('click', function (params) {
    console.log(params);
});
```

When you move the mouse cursor over a line, the cursor changes to a pointer. If click, nothing happens. Only if I find dot on line and click on dot, only after that it works and I see `params` in console.

I need get `params` when happening mouse events (click ant etc.) on line.

### What does the proposed API look like?

```
{
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      click: function () function (params) {
          console.log(params);
       }
}
```

**Comment by helgasoft** [comment]
add ```triggerLineEvent: true``` in series

NB: please close issue if problem solved.
