### ISSUE TITLE
[Bug] Calendar chart not change the background when apply global background

### ISSUE THREAD

**Issue by binhnguyen2501** [apache/echarts#19047]
### Version

5.4.3

### Link to Minimal Reproduction

https://github-production-user-asset-6210df.s3.amazonaws.com/72795100/263620910-7732dd9f-0cbd-4e49-b01f-a3cdcf516efb.png

### Steps to Reproduce

1. Set backgroundColor to red using setOption() function base on Doc https://echarts.apache.org/en/option.html#backgroundColor
2. Refresh the browser and check the calendar chart background color

### Current Behavior

This is what i get when i set the background color of all charts. Please check this image link bellow:
(bug image) https://github.com/apache/echarts/assets/72795100/7732dd9f-0cbd-4e49-b01f-a3cdcf516efb

### Expected Behavior

All charts background color are apply what user set in setOption() function base on Doc https://echarts.apache.org/en/option.html#backgroundColor

### Environment

```markdown
- OS:macOS Ventura
- Browser: Chrome
- Framework: Svelte
```

### Any additional comments?

Everyone who have the same bug issues like me pls check it. Hope echarts team or someone who can fix it :( 

(bug image) https://github.com/apache/echarts/assets/72795100/7732dd9f-0cbd-4e49-b01f-a3cdcf516efb

**Comment by plainheart** [comment]
The calendar coordinate system component has default `#fff` for [`itemStyle.color`](https://echarts.apache.org/option.html#calendar.itemStyle.color). You can set it to `none` or `transparent` to get the cells transparent.

**Comment by binhnguyen2501** [comment]
> The calendar coordinate system component has default `#fff` for [`itemStyle.color`](https://echarts.apache.org/option.html#calendar.itemStyle.color). You can set it to `none` or `transparent` to get the cells transparent.

OMG!!! thanks so much! i thought that could change the background color with setOptions and each item in calendar chart will apply too
