### ISSUE TITLE
[Bug] 为什么这组数据会将第一个和最后一个点又连接一遍

### ISSUE THREAD

**Issue by zhanghan3** [apache/echarts#19040]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/Han-Zhang-the-selector/pen/xxmwLdd

### Steps to Reproduce

如codepen所示

### Current Behavior

除了正常的曲线，默认会将第一个和最后一个点自动连接，出现第二条线

### Expected Behavior

只有一条线

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?
<img width="595" alt="image" src="https://github.com/apache/echarts/assets/96095448/c29e7b19-c90b-45ea-a893-b56ba944ece2">

_No response_

**Comment by MatthiasMert** [comment]
I think there is something wrong with your dataset. Items are in there multiple times

**Comment by plainheart** [comment]
I agree with @MatthiasMert. The items in your dataset are not in the correct time order. You can sort the data array before rendering the chart. See this [demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=MYewdgzgLgBBCmAnAlvCMC8MDaAoGMA3vgTGAIYC28AXDAOQC0ADAHQDsArPQDQkFQAngAdaDADbIw8XvziUQIKAAs6URAFd4fUjAAm5KOTp5dBbAEYAbAE4ATDc4AWK0_bMPPGG0cBdHWaWtg6cAMx2dpwezF4-Tv5y5tb2jnbu7p7erDZWCWY4yQ5OABzsGZlxeYGFNm5O4dGx2aFVukEpThbFVuVNNuytpO0OoY7MFo0wFqzMNoNJwTah7NYTmdPMxfMFi6Eea-szAwFtNWlOTnaTG5zbwzYWLnZO1zPxJ0OFxUtXB14buQ-C3sxVKdmWr2Yx0SOxBxXB9UhgJhw1BzAiUUOzFuQNhdlKoTc0RiUxmyPyqNc9T-pOYLVxqMiOWJ_xmdjuXwsXSJWPpKK-UOsLNp7IZhXYNjpPJJGz5FPF8M4_UhFg5wXYV2KDSxov5wWC4JpG1VYv1xSV2plbLV9h6tnskLl1X1nAmEpVNrsVmez16U093rpD0mPjmpvsSoelr6W3DkSpsxD2Wh8uCnE4K2jWRynuc7BemJJPhxeoj1lKwsqcacwZWSb81ZWdgshb65Od9icnFBiIqzU9V1mnCs9ZNpebYTCNJ8nscLmlfRLqZSYQx9fe49S6Xr7dOixKZUr2Q3y6K-azPide46XR69ZTHZGYyNMzDm-Wq0hsff-2FGwf14OOclyQkuj4PE8LxYiej7fA0L7MLunzBKCGoQliAHIXCCJ7FiSHAvixTopEoGegS0pWohZFUqECFXlh-JMiOkK6qexRcsUC60vRBFESszE6p67qEn6spCYqypYmOp4apsWYbKxj4GrRHpxlY5o_CxAbsPag6UTxeJWK6UKSlJAY-lx0lKVcozTtkb6npGFgXtk36OQmplFsmuYZs5eltrmdTYvWYGAa66nlF5tSejWbp2Q245uBYE47jF3acbhUUGcMg6OAJfRWYBLahFO9a-HIvisBAICIFAAAUdXkF4ABGACUmAAHwwOQ2DML4MCMDAzW9b4rUkAAvrgvgANy4CAwhQMg4CYEQJBQIo4iLcIdDELo6jIAA5gdSB0PQ5AAB7IBA9ATQEi1QOIYi7aQj0AGZQKdwDwGAUBIDdBDjQE50AIKXRAO1yEIoinYt1CyLozUgBoYAGIgggAOLkNtMCveQ4gILdJCCKDV0Q3tIhiPQABueNaP9MCAyQj3HSjZOkAYRgmEwbBcPQ5UAwECAoGgdBC6gEC4ON01AA).
