### ISSUE TITLE
[Bug] The tooltip line is discontinuous,

### ISSUE THREAD

**Issue by iam-frankqiu** [apache/echarts#19052]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/s/3wcgr8?file=/index.html:120-165

### Steps to Reproduce

1. set tooltip axisPointer type line, and add following code 
```
lineStyle: {
color: '#ebebeb'
width: 24,
}
```

### Current Behavior

The tooltip line is discontinuous,

### Expected Behavior

The tooltip line is continuous.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
```lineStyle: { type:'solid' }``` maybe ?

NB: please close issue if problem solved.

**Comment by iam-frankqiu** [comment]
> @Ovilia hope you can fix it ASAP. Thank you!

> `lineStyle: { type:'solid' }` maybe ?
> 
> NB: please close issue if problem solved.
Sorry. Still didn't work and the shadow was dispeared.

**Comment by Ovilia** [comment]
I tested `lineStyle: { type:'solid' }` can solve the problem.

**Comment by iam-frankqiu** [comment]
> I tested `lineStyle: { type:'solid' }` can solve the problem.
<img width="1150" alt="截屏2023-08-30 15 09 38" src="https://github.com/apache/echarts/assets/20899328/b5aba375-88de-4e2c-bb2a-ca1d7da50df0">

we don't even have 'solid' this option. How can I  add it to sollid?
That's the problem:

<img width="483" alt="截屏2023-08-30 15 12 08" src="https://github.com/apache/echarts/assets/20899328/815fb699-72f2-4073-8b5d-3015e5265866">
@Ovilia @helgasoft
