### ISSUE TITLE
Only 1 visual map indicates value if there are multiple visual maps.

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#19065]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/yLGJYRK

### Steps to Reproduce

Hover any point on the chart and observe visual maps. Only one of them indicates value

### Current Behavior

Only 1 visual map indicates value.

### Expected Behavior

Every visual map should indicates value.

### Any additional comments?

<img width="1428" alt="Unbenannt" src="https://github.com/apache/echarts/assets/43090396/f607ad76-2848-474d-8504-e111abc1800c">

**Comment by helgasoft** [comment]
Agree,  **only first** visualMap shows values on hover. 
This could be replicated with [official example](https://echarts.apache.org/examples/en/editor.html?c=scatter-aqi-color) - when the first is commented out, then the second visualMap shows values.
