### ISSUE TITLE
[Bug] import * as echarts from 'echarts/core' get error: export * from './lib/export/core.js';

### ISSUE THREAD

**Issue by Linjianwei99** [apache/echarts#19078]
### Version

5.4.3

### Link to Minimal Reproduction

no

### Steps to Reproduce

1、import * as echarts from 'echarts/core'
2、get error: 
export * from './lib/export/core.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

### Current Behavior

export * from './lib/export/core.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

### Expected Behavior

no error

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
Hi. This is a typical JavaScript question (where you should use `import * from` instead of `export * from`) and does not relate to ECharts. So I'm going to close this issue.

**Comment by dongfangtianyu** [comment]
Hi, I have encountered the same issue, node.js version: 18.12

to @Ovilia Please  :
that the code written by the user is 
```
import * as echarts from 'echarts/core'
```

while the code written by eccharts is 
```
export * from './lib/export/core.js';
```
https://github.com/apache/echarts/blob/fa231d37fe2788f5c8dfa5a86299ea8339d60897/build/template/core.js#L20



> where you should use import * from instead of export * from

So, it seems to be related to Echarts

**Comment by Antonytm** [comment]
@Ovilia It is related to Echarts. It seems that something is wrong with JS modules in ECharts.

**Comment by a327958099** [comment]
> 嗨。这是一个典型的 JavaScript 问题（您应该使用 `import * from` 而不是 `export * from`），与 ECharts 无关。所以我要关闭这个问题。

 ✓ Creating an optimized production build   
 ✓ Compiled successfully
   Collecting page data ../Users/acme/Desktop/project/WorkGPT/node_modules/.pnpm/echarts@5.4.3/node_modules/echarts/core.js:20
export * from './lib/export/core.js';
^^^^^^

SyntaxError: Unexpected token 'export'
这不是你组件里面的export问题吗？

**Comment by homj** [comment]
@Ovilia this is still an open issue and e.g. occurs when running jest.
