### ISSUE TITLE
[Feature] DataSet Crosstab Transformation

### ISSUE THREAD

**Issue by wise-coders** [apache/echarts#19075]
### What problem does this feature solve?

I want to create a crosstab data transformation on a generic data source, and create a multi-line chart. I would like to specify 'do crosstab transformation on Time and TableName, and be able to create the multi-line chart. Is this possible?
```
dataset: { source: [
  | ["Time","TableName", "TableSize"],
  | ["2023-08-25", "film", 360448],
  | ["2023-08-25", "actors", 213441],
  | ["2023-08-25", "customers", 38884],
  | ["2023-08-26", "film", 320448],
  | ["2023-08-26", "actors", 223441],
  | ["2023-08-26", "customers", 31884],
```

### What does the proposed API look like?

dataset: { transformation: [ crosstab(Time, TableName)

**Comment by helgasoft** [comment]
Doable through data prep - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=dataset-simple0&code=M4ewrgTgxgpgBAXjgbQFBwwek8gRAFQEsBbGXAGgIEMAjAGxgDkrSK5r6YBlQgLzIC65dBjwAmAAxiAzAFoJADlliArG1wAzQnWJtpANgkAWIwqEiUuSTPlLV6qlAAuICMDZiAjNJOfzGS2s5RWU1cnYoMGAXUjc9BQSjf1ErKWC7fXUtHT1JEzNhAPE022VM8NxHFzjwsRlfZMCSkLFyiKiYmBq4aU9E8wEAblQqAA9CYEQUIdRgLsmkZBnQSFgAOg1XAFFHAAsACgATQ8QAPjgAbwsIGAW4ObcNwgA7Q_39kHDCAEozy4sAoQNHAPmtnix4AgoXBjsg_L8rgEkRgHsBkIQBGtDlQnFQ1gAHKIHWFiATfYbIpE3JyQZ5wJwQMAwQZwbD3Fz4-4wKjQXYvADmAIwAF8LMLyRYgfsAIQ3YAIoVcx6E4AHC5OACe-JgAC4AOR0F4wPXkcGkHWwvzhbG4nXIEkCATiikiixjCYEolHQ7ICRk4bOkbjO7INZh54wADucC4MCc-3d8qGWEwcDAz0IAEcmahUCB8U5CCA6UhEXAGPyYK8dZdhYV6SAQHRC_iaxc6yJRgBBYNtmE4qg6xNwDsYDU9iZt0dKwi3Guo1DCwZAA).

![image](https://github.com/apache/echarts/assets/13038071/ec7cce21-98ec-4cce-9090-8f62195ebc68)

**Comment by wise-coders** [comment]
Is it possible to add the line name on top of each line? As tooltip or as endLabel?

**Comment by helgasoft** [comment]
yes, add ```endLabel:{formatter:dd[1], show:true},```
