### ISSUE TITLE
[Feature] State machine graph is posible?

### ISSUE THREAD

**Issue by vperilla95** [apache/echarts#19082]
### What problem does this feature solve?

State machine graph  with states and transitions, for dynamical data and dynamic state machine.

### What does the proposed API look like?

![imagen](https://github.com/apache/echarts/assets/64050026/cb28ccf0-3a4b-45da-98f6-481795a32f9f)

**Comment by MatthiasMert** [comment]
You could achieve a similar result by using the [series type graph](https://echarts.apache.org/en/option.html#series-graph.type).

[Here](https://echarts.apache.org/examples/en/editor.html?c=graph-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBCAhgM4QDGsA4gE60gAWlRAvgBoi9HOwg56BANpF0qYsTABPEPliUA5px6Vhi9FlrLgAVwoboMHHrnF6ygLYAjYFgDKEAF7qArAAZ9A3ZgWkcCMHZTHCDFI2ccLAIFA3R6bmAAdwionDt0IXzYHAATTRx3J1ck2GlKJgh2Jlw9DVp2EMzKAF1Y4lLyypc3Tx8ZABZBWABGf16igZwAGVoEmpTUgDMYMFH1ACZ_IsLUktowWhki-WviaDD1SgA5YBKcGdtUxVICAGZ_QK3dDKP4AvqpCBgHCOdwqXDJJhuYDsKjsUqUE5fNJVNyonBMMB8LGY1IbL73RyPF5vWD7T5Y2A_WAADjBQNgINg_yOxPBxDJqQpVNe71-9KxTN8AT5ik5sx5XxJBgFBiFVGp73G4q-kul7M5AQVqX4RXmqQA9ObYFgINAANZSWpmgw2-2O2RYlWKehmJrqQEMjDtcoWaYy-w4jzedTSXxTQ7OrHxRLJdlpDLZDC5dlK1Kuipw9RegyZCAlMDcAhxtOwJimdgANxw0Ekjv8ADp9jnbrn-eyffWmMKaXTw-gLuwQ-qRR8x9bVinCIH01kctEc3P87DlPCl8u643m62CB2u4GTbzbsW0r6h9OadNtakJ1ONBquUTFeHr7AB377-8o7si-OAWM8M5ij2379rew6AU-BggWB75alBV4wYOcGzsBwagQBsCocSpp8luhaplioC0A0Kgnu2ACc4aluWla0uGB5Ni29BtscdgXrA3QoPwADcQA) is a small example which demonstrates how to use.

**Comment by vperilla95** [comment]
https://echarts.apache.org/examples/en/editor.html?c=graph-simple

Thanks
