### ISSUE TITLE
[Bug] series.tooltip 仅在 tooltip.trigger 为 'item' 时有效。

### ISSUE THREAD

**Issue by rauki** [apache/echarts#19089]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar

### Steps to Reproduce

官方图例：https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar
修改series[0].tooltip: {
        valueFormatter: function (value) {
          return value + ' ml';
        }
      }时，图例中的tooltip发生了修改

### Current Behavior

在上面的官方图例中，tooltip.trigger = 'axis'，配置series.tooltip可以修改柱状图上的tooltip文案。
而在文档https://echarts.apache.org/zh/option.html#series-bar.tooltip中有以下注释：注意：series.tooltip 仅在 [tooltip.trigger](https://echarts.apache.org/zh/option.html#tooltip.trigger) 为 'item' 时有效。
请问两者是否冲突。我在自己的项目中当tooltip.trigger = 'axis'时，配置的series.tooltip是无法生效的

### Expected Behavior

当tooltip.trigger = 'axis'时，
可以自定义修改series.tooltip文案

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by rauki** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar
In the previous example, when tooltip.trigger = 'axis', modifying series.tooltip is effective. But in the documentation (https://echarts.apache.org/zh/option.html#series-bar.tooltip), there is the following note: series.tooltip is only valid when tooltip.trigger is 'item'. Is there any conflict between the two?

> @rauki It seems you are not using English, I've helped translate the content automatically. To make your issue understood by more people and get helped, we'd like to suggest using English next time. 🤗
> 
> TRANSLATED
> 
> **TITLE**
> 
> [Bug] series.tooltip is only valid if tooltip.trigger is 'item'.
> 
> **BODY**
> 
> ### Version
> 5.4.3
> 
> ### Link to Minimal Reproduction
> https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar
> 
> ### Steps to Reproduce
> Official legend: https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar Modify series[0].tooltip: { valueFormatter: function (value) { return value + 'ml'; } }, the tooltip in the legend has been modified
> 
> ### Current Behavior
> In the official legend above, tooltip.trigger = 'axis', and series.tooltip can be configured to modify the tooltip text on the histogram. In the document https://echarts.apache.org/zh/option.html#series-bar.tooltip, there are the following notes: Note: series.tooltip is only available in [tooltip.trigger](https://echarts.apache. org/zh/option.html#tooltip.trigger) is valid when 'item'. Is there any conflict between the two. When tooltip.trigger = 'axis' in my own project, the configured series.tooltip cannot take effect
> 
> ### Expected Behavior
> When tooltip.trigger = 'axis', You can customize and modify the series.tooltip copywriting
> 
> ### Environment
> ```
> - OS:
> -Browser:
> - Framework:
> ```
> 
> ### Any additional comments?
> _No response_

https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar
In the previous example, when tooltip.trigger = 'axis', modifying series.tooltip is effective. But in the documentation (https://echarts.apache.org/zh/option.html#series-bar.tooltip), there is the following note: series.tooltip is only valid when tooltip.trigger is 'item'. Is there any conflict between the two?

**Comment by rauki** [comment]
How to make modifications to series.tooltip take effect when tooltip.trigger = 'axis' like the previous example

**Comment by helgasoft** [comment]
> When tooltip.trigger = 'axis' in my own project, the configured series.tooltip cannot take effect

If we see "your own project" code, maybe we can help...
Minimal Reproduction is an official example that works well.

**Comment by rauki** [comment]
> > When tooltip.trigger = 'axis' in my own project, the configured series.tooltip cannot take effect
> 
> If we see "your own project" code, maybe we can help... Minimal Reproduction is an official example that works well.

I just copied the Full code from the previous example(https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar) and couldn't get the same result as the official example locally. So I want to know how to configure series.tooltip when tooltip.trigger: 'axis'. It is clearly stated in the official document that “**_Notice：series.data.tooltip only works when [tooltip.trigger] is 'item'._**“（https://echarts.apache.org/en/option.html#series-line.data.tooltip).

I speculate that there are some other configurations in the official case that are not written in Full Code.For example, you can see that in Option Preview, the color attribute is also configured, but it is not explicitly configured in the complete code.but I can’t know which configuration can make series.tooltip take effect when tooltip.trigger = 'axis'.

The reason I submitted bug issues is that there is a conflict between the official case and the documentation

**Comment by rauki** [comment]
After investigation, it may be caused by the old version(4.9) of my local echarts.
