### ISSUE TITLE
[Bug] Typo in sha512 file for 5.4.3

### ISSUE THREAD

**Issue by sebbASF** [apache/echarts#19083]
### Version

5.4.3

### Link to Minimal Reproduction

NA

### Steps to Reproduce

Download source and hash

### Current Behavior

$ shasum -c apache-echarts-5.4.3-src.zip.sha512
apache-echarts-5.4.3-rc.1-src.zip: FAILED open or read
shasum: WARNING: 1 listed file could not be read

### Expected Behavior

$ shasum -c apache-echarts-5.4.3-src.zip.sha512
apache-echarts-5.4.3-src.zip: OK

### Environment

```markdown
N/A
```

### Any additional comments?

The bug is trivial to correct: ensure that the name of the file in the sha512 file matches the zip file name

**Comment by plainheart** [comment]
Thanks for your reminder. I've fixed the typo and updated our release guide to ensure the name in the sha512 file matches the zip name in next versions.
