### ISSUE TITLE
[Bug] Using `graphic` in `options` doesn't render the `tooltip` on hover

### ISSUE THREAD

**Issue by codingCoffee** [apache/echarts#19096]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/s/dsdw6l

### Steps to Reproduce

Working Link: https://codesandbox.io/s/h7kn8f
Breaking Link: https://codesandbox.io/s/dsdw6l

The only difference in the above two links is that `graphic` is passed in `options`.

### Current Behavior

In the working link, the tooltip is available across the graph, however, in the breaking link, the tooltip only appears when hovered on a data point.

### Expected Behavior

The expected behaviour is to make the tooltip appear across the graph always, as present in the working link.

**Comment by helgasoft** [comment]
set graphic position(x,y) at _element_ level, not _style_ level - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8BvAsAKFrSYA2BTAXLCuhprgB5iEDkAymAIYDGA1rgCawAyE0u1aDAF8ANIMzBg2SCEKJMAJwgBzZbgU0G5CAGdqsUeLxro7OQbElyAQW0654jACNgAV1MMFATwDiDWbAAZgzYOriWpLDsDIyEANrUALIw1CKw1AAqrvxp1ADqHKnpGQAWrkXUAGJKFbQxte7UALrihiRetrrmbRjKCv4lEEwOJBi4eAC2uNBg9rBxxJEYYF4gBOkQEwxqqY6kEGbpYP3suFsKLFzAysC7o6TkhAAGACSIAO687MDvAHQ6TAUuGmv0-7DAJVgAD5YABGAAMACYACywAD8sAAbPDYIRkfChE80nsMF5nm9PqYfv9AcDoKCDhDoXCkaiMfjcViCUTYCTYDoVngRkt9ls1DQSmAwCB7AB6WW4JglTyzX7-ZglXC_YAKZQK6CyzbbXA6WXYa7AX4gaDKO4ijDysEQ8kfL7UgFAkFOyEAHhZKPRsAA7KjCAjuRF7ZqVJKXZTvn8PXSGeDff62bBEZjOeHCcT7pFQMwICtCPDfgBWPlCPZCFokHr89QQE3xPaLJbQBhTGgAUS2EGwdqWKzWNGwvByvIL_MYrBoGWAjCHkci0Vi81hiPhaVhAGZEbv4bDd3vkWkAJw7zN76-IhH1yKNjAdyJdnvpACq0CgcGs7D0VdSFHdZqAnPhh0iAVmBYBclxCSDSHXBh4kRbddwADkPOELxPG9z0zK80j3W9iIfWsgNfUh31AgA1A5cGAWB_0AvkQPHSdEIwaD52KeCVz5ZD4lhCs7wPNJtzwkSCNhIjYBI69kXI-5nyIPkaJoAARCAgSYMAuMwVZQPAnI-R42C-OXAyhPmA9rxI7DbzwkiCL3OSFOI7dH1IVSqIwDT0loXBPCVWBextTigOWIyOIgqLZxguCrPimy4iw68L3E2ArzwzKZMROT91IuE7O84RxHrIQAG4gA)

NB: please close issue if problem solved.

**Comment by codingCoffee** [comment]
Thanks it worked! Closing the issue
