### ISSUE TITLE
[Bug] 请问下我按照示例一模一样的写，为什么我的设置 setOption会延迟一步，且完全没有动画效果

### ISSUE THREAD

**Issue by ShaoGongBra** [apache/echarts#19094]
### Version

5.4.2

### Link to Minimal Reproduction

等会上传

### Steps to Reproduce

按照html文件重现

### Current Behavior

没有动画，setOption演示一步，设置的时候只显示上一次的值

### Expected Behavior

有动画，表现正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

解压这个压缩包后是html文件，直接打开
[test.html.zip](https://github.com/apache/echarts/files/12554649/test.html.zip)

我是参考此示例写的

https://www.makeapie.cn/echarts_content/xgGYxYWqR8.html

**Comment by helgasoft** [comment]
> There is no animation

Copied the last script from your ZIP starting with line 4 to the editor of [this example](https://echarts.apache.org/examples/en/editor.html?c=line3d-orthographic&gl=1).
Animation works fine.

**Comment by ShaoGongBra** [comment]
It does run, possibly due to inconsistency between my initialization method and the example. I changed the initialization method and it worked fine
