### ISSUE TITLE
[Feature] Ability to differentiate X and Y Axis in `datazoom` event using `id`

### ISSUE THREAD

**Issue by tonycassara** [apache/echarts#19098]
### What problem does this feature solve?

I have a table that offers detailed information about the chart directly above it. I'd like to use the X axis `datazoom` only to change the date range of that detailed data below. Today I have no way of differentiating X and Y axis and so both will trigger a date range change today.

I would like to have the `id` property from the `yAxis` or `xAxis` be sent to the `datazoom` event.

If this is actually easy to do I could open a PR for it but I haven't had a chance to dig into the code yet.

### What does the proposed API look like?

```
{
    type: 'datazoom',
    // percentage of zoom start position, 0 - 100
    start: number
    // percentage of zoom finish position, 0 - 100
    end: number
    // data value of zoom start position; only exists in zoom event of triggered by toolbar
    startValue?: number
    // data value of zoom finish position; only exists in zoom event of triggered by toolbar
    endValue?: number
    // the axis id that initiated the `datazoom` event
    axisId?: string
}
```

**Comment by helgasoft** [comment]
We can use _dataZoomId_ to identify which _dataZoom_ triggered the event - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MpZ9D0gRABmAeFxdiRtJEJgjABawMAAtmJIEAIEtAAatA7Im9sAmjLOuHgAktACVBgE6Xa2dgDcKCvkAMLajBxgAHQwAAUtDmjAAXssVjIRpZ6JAYLAgVQfGAAJTxWCgBDISBgfw0JAsDBgOiQ1ayADUsBRALBS1WlwEdim6A-31-APCYAA8uAoNAgaA0W87CKgA).

**Comment by tonycassara** [comment]
@helgasoft amazing thank you!!!

**Comment by tonycassara** [comment]
@helgasoft any chance you know how to expose the x axis start and end values after the data zoom is updated?

**Comment by helgasoft** [comment]
here is [one way](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBBATlhBPAOgDMsQBbACgG8AbAUzAHMoALALhgFYAGAXwBoYFOvTIMoggJZg4dAB4BKNAD4YAWABQMGAG1psuYICySFsRogQWCidYFcM8hSUAqGAEZu3BQF0FAbk0QAAcoSXBUKk1tOQw5SQgOKhgBaPgkBAAtSzIk1K0YPDiEpJT-NIg6LEk6RN1kxGQORoRBKDxgug4AchppOm6Un01eTTg4NHTkAjIEYIo5FRg5HW4_QI04MmlJ2zNtsAoCY_GAzQA3BCwYCGCEMF3TGYQ5I5O4JQBaeAONzTI8ABhFhXKAEcAUbotABeOW6giIAFcwMAwhC7rgyBAlFECtBrugttIANS3e4uDEILEEaCggD0nm4G20DAmhIOpLuYApVypEAIrIZXmZMFAkBA9AIFkYFEpWME-P4rLOGl4ASAA).
Or steal them somehow from dataZoom's handles, since tooltip is showing them.

**Comment by tonycassara** [comment]
@helgasoft thank you for the example, i am currently doing something similar (multiplying by 0.01 instead of dividing by 100) and i end up about 4-5 hours off from the time being shown in the chart. ill investigate the datazoom handles thank you!

**Comment by tonycassara** [comment]
in case anyone else runs into this like me, it was a whirlwind of back and forth only to realize `dayjs().format()` automatically formats to your local time which accounts for the hours off.
