### ISSUE TITLE
想问下，x type = time ，如何实现step=true 这种阶梯折线图，直上直下，不是倾斜的

### ISSUE THREAD

**Issue by ziyingjing** [apache/echarts#19100]
### Version

5.4.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2

### Steps to Reproduce

1）、用官网时间显示折线图
2）、series设置step true 属性
3）、期待折线图直上直下

### Current Behavior

![image](https://github.com/apache/echarts/assets/8833911/c0f40e0e-aa09-47c5-b700-0a86a0ebc167)

### Expected Behavior

![image](https://github.com/apache/echarts/assets/8833911/69970aac-f05f-411f-839c-aac1ea059871)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
I added dataZoom to the [example](https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2&code=GYVwdgxgLglg9mABAJwIZgCZwLYBFVSoAUAlIgN4BQiiYcA7ogLy0Cmj-UrRA1HYz0QJW-AJ4kA3NUQA3VABsQrZrIVLEggLIEAFgDo0mHKUQAqRACYAjIgC0iKwAYpNZKyghkSKjRphU2KwAXLQMelBwAMpQyDBgAOakADTSNHKKwYgA2qm-Wfx68e4AYiDy8gCarKjIyaH0he6aCFA6JoJWSfWNUJzcJAC6egBWcHFEAOQA9BMkKb6-2q0GcOAYROlKJLkD0gC-UnuU8u6IGASoKlkDUidQ9Spg7Ih9RFYAnO8A7F3vXQDMkmOp2EYhUFgALGZEP8AGyORzQpwI26nTbKFhLfSGLDYEzmZHOSjAODIRAbGqIGAqZxUxAAHgcCNpMB4PDIPjOFz0AAcQABnNo4nCcYgkIFHOA82AIFSc2BQE4hTk0LgADygIQmuFE_mwMAgLwuiAAZIgACowQKIACCapg_Im-3miAicHksB5ytyMRg8SKyC1qHtjpdNBJyGwBC4gcQoEgMqQRB5NQC_I5uRoKbQ2H5KmzaayjhumdUZPOXEez1eBdzej1rCBC1c7k8SdLNArrB6rzIPA7iGmEw0A6IXZ6zTArXaDj7A6HI-bvnHRSgpXKVRq7XniC1i6XiFr_L06KyVl2S6bvj2YcQwYdAAUxlPWLGVb50FaCPAwCFgAp-VYXIjhoG9pArVAAC04BwEIsnIKBRB5TIJn5eQYAwV8JhvBCkJQuJ-Qw1hsIGF01TtB1vQWRDkK1WBAgmW9-R5dCoAAGTiTJ3xoQUGD_ACgIWEDEDAmhRAo_kqN8GiUPRRjcgAI1WTAalEABxVAvWyRwugmZEAFIJlI3JmNYjinikhZePofj5EA4DnWkQDYlYSTslybjaACFDilQABrZRRXkpcZK1dCnmC5t-S4LSYiUW8eJ0BhIlEbAlPkWzAISrlCBCCCHJoXYDiAA). If you zoom in you can see that it is working as intended.
