### ISSUE TITLE
[Feature] 中国地图右下角小地图问题

### ISSUE THREAD

**Issue by buquzaiyi** [apache/echarts#19101]
### What problem does this feature solve?

在中国地图中，右下角的南海诸岛小地图为九段线，在发布的新版地图中已改为十段线

### What does the proposed API look like?

如何将右下角的南海诸岛小地图更改为十段线显示

**Comment by nishizbdjy** [comment]
我需要将中国地图改为最新版地图请问如何更新？

**Comment by plainheart** [comment]
ECharts 已不提供地图数据，请自行下载合规的地图数据。至于内置的南海简图，后续会考虑更新。
