### ISSUE TITLE
[Help] Visual Map and MarkArea zone at marklines touching with Series line

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [apache/echarts#19105]
### What problem does this feature solve?

###Code try!

https://echarts.apache.org/examples/en/editor.html?c=line-sections&code=MYewdgzgLgBFIAcD6AbAlgWzbAvDAzAKwAMA3AFCiSwBGIU8Gqm2MeAjCReYlGuGxgBvcjBgAPAILi0EAFzDRYuAE8EAUwUByYAEMo6gOYgATiq0AaJWLoBXMABNdZgOK6ECgGa6UEdVeUYJyhdBQBtLWJiOSjLGEj2GOI4yIAmJJTifAyLeOIAFhy8wiLIgDYMgF0lAF8AmBVpWQURQKg1TXiANx9bdS1a-q7ZWx8AWXcW6xgENHVgdXkYMOmxVsDlQygFOgYQJnQsKHqNmBQDBXhkQ-wTjdAUU20aFD6B07rVxVOxLcvEZhHO6BB5PeImdQOd4bGrTSp3EC2KAAeU8ACVdGBDJ0hDBQSZtBCoTBYWJPmI_CY5ksVoF1oEMM4ANYAGTQYBxXzEwVCy1xjRkSyugNYdWEDSaS12jBFsBq8K5MAgaBQ6jA2zgJj6wOU6A5AGV2qqpj9lPjtIYIWrLIqxAB3NAOKAACwU7EV5J-EBUGDoKHCWjA4H6uUDwa01Q-OvaGm0epDXwgGBA9Fdmu1Xx54XwUVyqQAHMRcvkSHmykWYOXcjmK4QSArTvHDSpjd8fg6nWn8l9PQzmZIIbz6RtsOoMM3W8PTub4lATJiIAhnGqoDbTTZTA51CYAOqOl1unWBOgmLcmAAqHXChFy7GIkZ-vY2WeWttf6-UU_XYF0GE6WjGUwwHZQwYAABXUXQmTXD9lCkQVtGIRJYjfMkjw2L9TXg5o8myFDYJJN8G3XWlYMwn4fz_bQAFEujVEDwMg6D0NObClkiEp8Ngp9TXI1jJUQiouI_Ul1wfU5xOUUSySUaoalIIA

i want to make the MoringPeak and Evening Peak zone(visual map and markArea) base on the joins touch of markLine with the Series data.
so i tried to read some examples of line charts but not yet found solution for the design. please help with any idea !

![Screenshot 2023-09-11 at 14 49 20](https://github.com/apache/echarts/assets/30792140/505f44a8-7fe9-4b2c-b535-4e9813f5c96f)

### What does the proposed API look like?

![Screenshot 2023-09-11 at 14 08 08](https://github.com/apache/echarts/assets/30792140/d9280596-4a9d-4b71-8aab-37229fff9d1a)

**Comment by helgasoft** [comment]
You want to draw a vertical MarkArea zone (or two MarkLines) for each peak >150. You'll need **two X points** like in the [official example](https://echarts.apache.org/examples/en/editor.html?c=line-sections).  
- if you have enough data points, then it is easy to find all X's intersecting with Y=150.  But your data is too sparse...
- with sparse data one could find the intersection X-value of each line segment with Y=150 (example: segment X=1:00 to X=2:00, with Y=150). But this will work only for straight lines (```smooth:false```).

So I think your choice to either have more data points or give up line smoothness.

**Comment by NguyenHoangMinhkkkk** [comment]
Hi. thanks your attention.

the exactly my idea is to draw the vertical-line at touching-point where series-line touch with markLine (y=350). 
but problem was if i don't have the data point in xAxis, and its too sparse.
so i don't have x,y of touching point for drawing vertical-line.

More in below example: the touching point A(x,y) is unknow.
![image](https://github.com/apache/echarts/assets/30792140/7af6d5fb-f815-49ff-8878-364eff077d07)

And as i tested, visualMap.outOfRange already know where to change series-line color where it out of visualMap range XD but i don't know how to get it

**Comment by helgasoft** [comment]
> visualMap.outOfRange already knows...(the intersections)

good observation, internally those points are known of course, but there is no API to obtain them.
I found [getPointOn](https://github.com/apache/echarts/blob/master/src/chart/line/poly.ts#L278) method in _polyline_, but it gives **only the first** intersection point for a fixed coordinate (x or y). 
Here is the result - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PTAEHMFMBcAUHsCWA7aB5ZoC8oAW1oAHAZwC4RxFpcBXAIwDoBjeAW2AENCOndJhIvDgCdoxYHQA28OsFYdi0SMODFhTYENHBJKfoXiSAngzEBiADIAmAOwAOALAAoAG4jQhAIwBWAAxYAbQBdAG4PAGY_QNDnFmRFUAs9ADVESAB3bFBBXBExBgBhXNFUjIYoaALJBWIACgByXWRIeoBKENj4eOhQAH1m9IRjJsgspObS9IZCYXhoOaNCSAZ-jKGjEY6ncchJ6dn56EXl1cHDDb0sgDMaZCZoRC7agxQxVoBvZ1Bv0DiEg2GHCyp3WI2YHEkklq1EQxAANB4kKhiO0vj8ARsOAxiDAAMq5Ja1d6gYiseBzXCkXwMbygAC-qKcP1A0FYhCyrCMRTyzC6LmU0AAKvBYIgAB6QKHEnHCNLEACSyAAJpAxVT6QiAp44ZFfEFGczCD0cBjquUYAhXhhoWytUE4fUjG00d9CLqOVzitBech-aIAGKzViiiVSknKOWKlVq3wajzQA0_VnsnCc7miH1-oUi8WSonh2WQBXK1Xquma7U-PWJ13GxGA81wJHoZA2wh2h1O1oujxVj3p71xLOBtghvPSiNFqOl2Pl-M10DCGA0YSYU0cLZ0radbos-CEXq6VhULK6rZ_Hp0ObzViHxDHutV7dOfcPLpZT5M0BigCCYthpCgJ-zIgEqHDQBwgEBPUvi-FSvj1AiMGePBiGgDBVioUhvjhFh6G-AALHhMHeMRvgAGyoUEPZXrcYHCEYADiXCAVcEI4nCaLlmiRh_gBQHcV-LiwjQEIALIsUBBaRiWMacV-rppEwRZQT23zAcyPzgNAgFXgQbB3g-8maT8khKIB8wHkeVDGSZvyGPAwiAfUUg0C0akah5GkmdpFn7oZNked8LDSE56FLkq9QeXSPb2j28A0OgVwAEocMgUCAcSIWOc5EX1PSXG2TKcqqQpQEeUcSzOSMiEeaS5LUBZwhubZIHAGBEFQeEsEIlYdi-AiBF-L15EDaAo0It1Y3eH4cVld8HWQaAARajqsH2stVhwn1eqauEcJDbty0Edto0bQE3hwmdmrkWtR0BDYcIzXqc0mSMuJHJIkCZaA6SIEqjWgARnnzaA8jCAA1jspBeUFoCLVBxK8f-ZB7lZ94nnOSN8ajek3gFPR0q9dnEIgX2oE1LVw-9n3fVJ2VhfUeUIn9AOUqAngg3ZJJGKwV6SFB9TIF0LRIcLzT1NRoMxWVgnMsSFXHKQ9TEEw4FKMIaH_crLisJDaHELz_POUwiDqF9BtG4YuKIAAXnTVhbaAtukJ42pw1QkCsB9Gx0-8DPK9AwhpcQ3BLqgaFXsIKrCAA6v9jVO1HMcFA5Tn1OAS6QMg9Qy8yeegFLW7ODiQr3pACXQLUNx3G-ratOVZVpl62IwGgRqPK2CtlcVKnLV5oDa_Uuv6wiCPLV4w0RLN9JS98DLOHOniwe0QA)
Would be nice to one day have _getPointOn_ expanded and exposed as API function.
![image](https://github.com/apache/echarts/assets/13038071/e0968079-dcd1-4ef9-9e6e-64c027e8a090)

**Comment by NguyenHoangMinhkkkk** [comment]
> 

Thank you for that example, Really nice [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PTAEHMFMBcAUHsCWA7aB5ZoC8oAW1oAHAZwC4RxFpcBXAIwDoBjeAW2AENCOndJhIvDgCdoxYHQA28OsFYdi0SMODFhTYENHBJKfoXiSAngzEBiADIAmAOwAOALAAoAG4jQhAIwBWAAxYAbQBdAG4PAGY_QNDnFmRFUAs9ADVESAB3bFBBXBExBgBhXNFUjIYoaALJBWIACgByXWRIeoBKENj4eOhQAH1m9IRjJsgspObS9IZCYXhoOaNCSAZ-jKGjEY6ncchJ6dn56EXl1cHDDb0sgDMaZCZoRC7agxQxVoBvZ1Bv0DiEg2GHCyp3WI2YHEkklq1EQxAANB4kKhiO0vj8ARsOAxiDAAMq5Ja1d6gYiseBzXCkXwMbygAC-qKcP1A0FYhCyrCMRTyzC6LmU0AAKvBYIgAB6QKHEnHCNLEACSyAAJpAxVT6QiAp44ZFfEFGczCD0cBjquUYAhXhhoWytUE4fUjG00d9CLqOVzitBech-aIAGKzViiiVSknKOWKlVq3wajzQA0_VnsnCc7miH1-oUi8WSonh2WQBXK1Xquma7U-PWJ13GxGA81wJHoZA2wh2h1O1oujxVj3p71xLOBtghvPSiNFqOl2Pl-M10DCGA0YSYU0cLZ0radbos-CEXq6VhULK6rZ_Hp0ObzViHxDHutV7dOfcPLpZT5M0BigCCYthpCgJ-zIgEqHDQBwgEBPUvi-FSvj1AiMGePBiGgDBVioUhvjhFh6G-AALHhMHeMRvgAGyoUEPZXrcYHCEYADiXCAVcEI4nCaLlmiRh_gBQHcV-LiwjQEIALIsUBBaRiWMacV-rppEwRZQT23zAcyPzgNAgFXgQbB3g-8maT8khKIB8wHkeVDGSZvyGPAwiAfUUg0C0akah5GkmdpFn7oZNked8LDSE56FLkq9QeXSPb2j28A0OgVwAEocMgUCAcSIWOc5EX1PSXG2TKcqqQpQEeUcSzOSMiEeaS5LUBZwhubZIHAGBEFQeEsEIlYdi-AiBF-L15EDaAo0It1Y3eH4cVld8HWQaAARajqsH2stVhwn1eqauEcJDbty0Edto0bQE3hwmdmrkWtR0BDYcIzXqc0mSMuJHJIkCZaA6SIEqjWgARnnzaA8jCAA1jspBeUFoCLVBxK8f-ZB7lZ94nnOSN8ajek3gFPR0q9dnEIgX2oE1LVw-9n3fVJ2VhfUeUIn9AOUqAngg3ZJJGKwV6SFB9TIF0LRIcLzT1NRoMxWVgnMsSFXHKQ9TEEw4FKMIaH_crLisJDaHELz_POUwiDqF9BtG4YuKIAAXnTVhbaAtukJ42pw1QkCsB9Gx0-8DPK9AwhpcQ3BLqgaFXsIKrCAA6v9jVO1HMcFA5Tn1OAS6QMg9Qy8yeegFLW7ODiQr3pACXQLUNx3G-ratOVZVpl62IwGgRqPK2CtlcVKnLV5oDa_Uuv6wiCPLV4w0RLN9JS98DLOHOniwe0QA) shown exactly what i want to find. and Yes, hope for it sometime in future
