### ISSUE TITLE
[Bug] SVG 与 Canvas 两种模式下 LinearGradient 表现不一致

### ISSUE THREAD

**Issue by zjxpcyc** [apache/echarts#19104]
### Version

5.4

### Link to Minimal Reproduction

https://codesandbox.io/embed/apache-echarts-demo-forked-wxjmyk?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

1、新建一个基础 柱图
2、配置渐变色

```js
color: [{
        type: 'linear',
        x: 0,
        y: 0,
        x2: 1,
        y2: 1,
        colorStops: [
          {
            offset: 0, color: 'red' // 0% 处的颜色
          },
          {
            offset: 0.49, color: 'red' // 0% 处的颜色
          },
          {
            offset: 0.5, color: 'blue' // 100% 处的颜色
          },
          {
            offset: 1, color: 'blue' // 100% 处的颜色
          },
        ],
        global: false // 缺省为 false
      }]
```
3、查看默认 canvas 下表现
4、修改 svg 渲染方式，查看表现

### Current Behavior

两种模式下渲染不一致

### Expected Behavior

两种模式渲染一致

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
set **```x2: 0```** instead of ```x2: 1```
Please close issue if problem solved.
