### ISSUE TITLE
[Feature] Lack of use of chart.dispose in examples.

### ISSUE THREAD

**Issue by sangelxyz** [apache/echarts#19116]
### What problem does this feature solve?

Can examples be updated on the Apache websites so they use the chart.dispose(); feature or at least a note ? 
Serverside examples are the most important which can cause memory leaks.

 

### What does the proposed API look like?

no change to the api, only updates for examples to include chart.dispose() to correctly clean up after use.

**Comment by Ovilia** [comment]
Thanks for the reminding. Docs at https://echarts.apache.org/handbook/en/how-to/cross-platform/server should be updated about dispose.
