### ISSUE TITLE
[Feature] Grafana Global scroll for subplot multiple pie charts, many figures.

### ISSUE THREAD

**Issue by vperilla95** [apache/echarts#19110]
### What problem does this feature solve?

![imagen](https://github.com/apache/echarts/assets/64050026/d25b8d41-820e-4f59-906d-b7aa9125fee4)

I need a global scroll bar. I need a dynamic pie chart between 10 or 20 figues and I don't have a global vertical or horizontal scroll to view multiple pie charts.

### What does the proposed API look like?

How I do it??

**Comment by Ovilia** [comment]
This is not an ECharts feature. Make the container with higher height and scrollable.
