### ISSUE TITLE
[Bug] axia 里 axisLabel 设置了换行，宽度能显示一个字符，完全能显示下标签。结果缩放宽度后，部分柱状label消失

### ISSUE THREAD

**Issue by yangweijie** [apache/echarts#19136]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsDGwA2wBOAXLANoBEAxAMyUCcAHACIBCpAugDRqxjA6QhFU6dGDwQA5uICmhWKQCGADwgBnUp2GwlqgArAI0MDMFdNYAJ4gpRUioAW8gCbAA7qVOwAvl08bY4sUdBXy5FAEFlFSJiIWELKxsMeSNxfHN1D0dk-WjSAFkYdTkAFQBXKSLSAHUpR0riu1LKgDExSoBlZI7S6DYfDi5zCNVo2JFLazkAN3lscvd0TwH0FRkIKSiSMdhoeQBbSdJAF7dAUuNAfujAO9SMswmbACN5PGvhB7wqiEcwOxsANgAGACkz3QWTAORIAEY_uxYABWABMMPhf2hsGoABYYbRUdRUfDkax-ihPEA&_source=echarts-doc-preview

### Steps to Reproduce

普通npm方式安装echarts

~~~
option = {
  color: ["#3398DB"],
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow"
    }
  },
  grid: {},
  xAxis: {
    type: "category",
    data: ['海门街道白云街道', '白云街道白云街道', '葭沚街道白云街道', '洪家街道', '三甲街道', '下陈街道'],
    axisLabel: {
      fontSize: 12,
      overflow:'break',
      width:10,
      // height:40,
    }
  },
  yAxis: [{
    type: "value"
  }],
  series: [{
    name: "直接访问",
    type: "bar",
    barWidth: "60%",
    data: [10, 52, 200, 334, 390, 330, 220]
  }]
}
~~~

### Current Behavior

模拟器里默认全屏能显示标签文字，缩放到一定宽度，有的标签消失
![image](https://github.com/apache/echarts/assets/1614114/fd0bbb3e-a277-44b0-b0cf-43cacc6a4183)

### Expected Behavior

希望文字能正常换行显示，如果显示不下，缩放柱状图区域的高度。

### Environment

```markdown
- OS: Windows 11
- Browser: Edge 117.0.2045.31
- Framework:Vue@3
```

**Comment by helgasoft** [comment]
set ```interval: 0``` in _axisLabel_.

please close issue if problem solved

**Comment by yangweijie** [comment]
> set `interval: 0` in _axisLabel_.
> 
> please close issue if problem solved

This works normal.
