### ISSUE TITLE
[Feature] 获取x轴 y轴数据的起止位置坐标  以及  根据当前点击位置获取图表数据

### ISSUE THREAD

**Issue by facactus** [apache/echarts#19144]
### What problem does this feature solve?

获取一些关键点的坐标 比如数据开始绘制的起点和终点；以及可以根据点击坐标计算出图表数据内容
![screenshot-20230921-150817](https://github.com/apache/echarts/assets/4263465/43f8d723-0c29-4406-aee0-7fac66b7c712)

### What does the proposed API look like?

希望在图表加载完成后，可以回调一些关键点的位置坐标；以及提供位置坐标、数据内容转换方法

**Comment by Ovilia** [comment]
这个需要自己计算，ECharts 没有相关接口
