### ISSUE TITLE
[Bug] Documentation site seems to be down.

### ISSUE THREAD

**Issue by Keoooo** [apache/echarts#19156]
### Version

n/a

### Link to Minimal Reproduction

https://echarts.apache.org/en/index.html

### Steps to Reproduce

1. Visit https://echarts.apache.org/en/index.html
2. See screen shot 

<img width="1440" alt="Screenshot 2023-09-26 at 6 02 07 pm" src="https://github.com/apache/echarts/assets/33136365/8837fd6b-40a5-4cce-855f-c4cd6ee2f189">
<img width="1440" alt="Screenshot 2023-09-26 at 6 06 39 pm" src="https://github.com/apache/echarts/assets/33136365/513dae7d-94e7-4cdd-9b40-5df166bbd608">

### Current Behavior

When I visit the site on chrome/brave/safari the website seems to be missing the CSS

### Expected Behavior

For it to be nicely styled for easy UX 

### Environment

```markdown
- OS:
- Browser: chrome/firefox/brave
- Framework:
```

**Comment by plainheart** [comment]
It's working well for me. Please check the console to see if there are errors from jsDelivr CDN and make sure you can access the CDN website.

**Comment by plainheart** [comment]
So it seems you can't access the [jsDelivr CDN](https://www.jsdelivr.com/) that our website uses...
