### ISSUE TITLE
[Feature] registerTheme api 可以提供完整的参数吗

### ISSUE THREAD

**Issue by zmcode** [apache/echarts#19159]
### What problem does this feature solve?

api地址: https://echarts.apache.org/zh/api.html#echarts.registerTheme

api中的theme这个参数, 只是说是一个对象, 我看了下源代码中是一个普通的key, value对象类型

https://github.com/apache/echarts/blob/HEAD/src/core/echarts.ts#L2764

但是我并不知道它最终支持echart中的哪些配置项(实在看不懂源码最终合并的逻辑), [官网提供的主题配置](https://echarts.apache.org/zh/theme-builder.html)似乎只支持部分配置, 我想知道完整的配置

源码中是在[这个方法](https://github.com/apache/echarts/blob/HEAD/src/model/Global.ts#L1006)中, 对setOption方法中的配置跟theme定义的配置合并的吗?

### What does the proposed API look like?

我registerTheme 这个api 方法能说明支持的具体配置项, 让更多开发者习惯的设置主题, 减少代码量

**Comment by plainheart** [comment]
Duplicate of #18770
