### ISSUE TITLE
[热力图yAxis.type='value'时，单元格不能对齐] 

### ISSUE THREAD

**Issue by zm9913** [apache/echarts#19151]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian

### Steps to Reproduce

我的option和相关数据如下：

// prettier-ignore
const hours = [
   0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
];
// prettier-ignore
const days = [
    1,2,3,4,5,6,7
];
// prettier-ignore
const data = [[0, 0, 5], [0, 1, 1], [0, 2, 0], [0, 3, 0], [0, 4, 0], [0, 5, 0], [0, 6, 0], [0, 7, 0], [0, 8, 0], [0, 9, 0], [0, 10, 0], [0, 11, 2], [0, 12, 4], [0, 13, 1], [0, 14, 1], [0, 15, 3], [0, 16, 4], [0, 17, 6], [0, 18, 4], [0, 19, 4], [0, 20, 3], [0, 21, 3], [0, 22, 2], [0, 23, 5], [1, 0, 7], [1, 1, 0], [1, 2, 0], [1, 3, 0], [1, 4, 0], [1, 5, 0], [1, 6, 0], [1, 7, 0], [1, 8, 0], [1, 9, 0], [1, 10, 5], [1, 11, 2], [1, 12, 2], [1, 13, 6], [1, 14, 9], [1, 15, 11], [1, 16, 6], [1, 17, 7], [1, 18, 8], [1, 19, 12], [1, 20, 5], [1, 21, 5], [1, 22, 7], [1, 23, 2], [2, 0, 1], [2, 1, 1], [2, 2, 0], [2, 3, 0], [2, 4, 0], [2, 5, 0], [2, 6, 0], [2, 7, 0], [2, 8, 0], [2, 9, 0], [2, 10, 3], [2, 11, 2], [2, 12, 1], [2, 13, 9], [2, 14, 8], [2, 15, 10], [2, 16, 6], [2, 17, 5], [2, 18, 5], [2, 19, 5], [2, 20, 7], [2, 21, 4], [2, 22, 2], [2, 23, 4], [3, 0, 7], [3, 1, 3], [3, 2, 0], [3, 3, 0], [3, 4, 0], [3, 5, 0], [3, 6, 0], [3, 7, 0], [3, 8, 1], [3, 9, 0], [3, 10, 5], [3, 11, 4], [3, 12, 7], [3, 13, 14], [3, 14, 13], [3, 15, 12], [3, 16, 9], [3, 17, 5], [3, 18, 5], [3, 19, 10], [3, 20, 6], [3, 21, 4], [3, 22, 4], [3, 23, 1], [4, 0, 1], [4, 1, 3], [4, 2, 0], [4, 3, 0], [4, 4, 0], [4, 5, 1], [4, 6, 0], [4, 7, 0], [4, 8, 0], [4, 9, 2], [4, 10, 4], [4, 11, 4], [4, 12, 2], [4, 13, 4], [4, 14, 4], [4, 15, 14], [4, 16, 12], [4, 17, 1], [4, 18, 8], [4, 19, 5], [4, 20, 3], [4, 21, 7], [4, 22, 3], [4, 23, 0], [5, 0, 2], [5, 1, 1], [5, 2, 0], [5, 3, 3], [5, 4, 0], [5, 5, 0], [5, 6, 0], [5, 7, 0], [5, 8, 2], [5, 9, 0], [5, 10, 4], [5, 11, 1], [5, 12, 5], [5, 13, 10], [5, 14, 5], [5, 15, 7], [5, 16, 11], [5, 17, 6], [5, 18, 0], [5, 19, 5], [5, 20, 3], [5, 21, 4], [5, 22, 2], [5, 23, 0], [6, 0, 1], [6, 1, 0], [6, 2, 0], [6, 3, 0], [6, 4, 0], [6, 5, 0], [6, 6, 0], [6, 7, 0], [6, 8, 0], [6, 9, 0], [6, 10, 1], [6, 11, 0], [6, 12, 2], [6, 13, 1], [6, 14, 3], [6, 15, 4], [6, 16, 0], [6, 17, 0], [6, 18, 0], [6, 19, 0], [6, 20, 1], [6, 21, 2], [6, 22, 2], [6, 23, 6]]
    .map(function (item) {
    return [item[1], item[0], item[2] || '-'];
});
option = {
  tooltip: {
    position: 'top'
  },
  grid: {
    height: '50%',
    top: '20%'
  },
  xAxis: {
    type: 'category',
    data: hours,
    splitArea: {
      show: true
    }
  },
  yAxis: {
    type: 'value',
    data: days,
    scale:true,
    splitArea: {
      show: true
    }
  },
  visualMap: {
    min: 0,
    max: 10,
    calculable: true,
    orient: 'horizontal',
    left: 'center',
    bottom: '15%'
  },
  series: [
    {
      name: 'Punch Card',
      type: 'heatmap',
      data: data,
      label: {
        show: true
      },
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    }
  ]
};

### Current Behavior

当yAxis.type='value'时，热力图单元格和Y轴没有对其
<img width="753" alt="image" src="https://github.com/apache/echarts/assets/11975684/79ade730-c2c1-494c-83c0-3040e2a51796">

### Expected Behavior

希望能对其

### Environment

```markdown
- OS:macOS
- Browser:Chrome
- Framework:JS
```

**Comment by helgasoft** [comment]
maybe [like that](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAFiArgJwjAvDA2gKBjABgBoYBGEgJhIGYSAWEgVhIDYSB2EgDhIE4TSxMuTJUytMgzLMybMpzI8y_GBSEVyeVWIrUcAXQDcOAPQmYAB2QBTKFACW15AFp7AczAgbOUJFgATAEMATzRMXHIqWgZmNnYDYzNLGztHF3dPb19oGCCoQIxsLCEhRn0SYoEBcux1EgIaypgJBoqhKVbapnrGoTlOpoUBoSVhvh62gRLegREKGdF6BdIJUmWpNcnpGmW5OmWFFmWlfa3SFVOu1SFqBY0drYodO4kyipEhdkaRD-_KCewIhafxgHRBMgGIn6IKGINGIJUkKmTBBpDmqOe7wEEiOWMkfFRMjRqLkuMBAgUXzxpCUXFRKlI8zxahRzJEb3J2g4IN0lEaYiEm2wYh-_P-hDFzQBWDEYIqYghkuh8o40rE8JVMERksED2Fsz5msZ1SNEl4OqkdKNRIGItJOoUHJlAiUTpFKjdlE-kvuoJ9mP1qgklywLW5FVWetD4oGEmBEfo0teSdYKZgsITMCUQujWrTupgTtWIhDqzEVOwq1WpYEG1umdIRKZlYEcnNDcdjVWrq7AgZsa9rF7qhLw6eS0zvLIjQ6JuwGyjUgFM5o0qkcvn3WnFSkys36bX3EPedUK7I7TPaIn--Np532OvWA268vRJDGzkjMvChzG1pl49M8WWaICRArJ9KDEet9ynAYIUNbAiTnLAZGXCoZDjRoZA3FCtzg1MJXQ1VCMQo871Ik98PPR8iVFIjFkLLCH3PJj8UY-jG3DCjSE_HMiUOViaWlIlAPo4DoNwkcaMghDJNgxp-mQz9pTkNDsDkeN1MTEisDkRUKlJFTiIGOQNS0yiFORbdzKvHTPwDXTmJzT8pAkz9sMs2QjPkbyhLsvtvOA5zKHRAyZPIxygyHfQcAAOgAW0CCwAAoADNEDAYAHHAGBkvsKBrHigBKGAAG8cBSFAwGwfLCqwIVavi4oakamV9BgAAfDqYAAcmcHqjBwABfIrjBACxsuqzByvwKAQBAAAbBwLAALjKrR8AsEAIHy-xwDWnq5osHqtCGogtDcZB7H8NaZvweBrHcOAoAOxgCAAUh6877pgI6DrUT7Tu-mAAA8AEEQfsCBbo23JAnyNaEBQCBgfwCALAW_KwZsQJbp-tGEAAdzWqBkEQawfrO2GQFS1KIFsNbnBEWHAkhiAABl7DAawVtK8AAC0nBAFbUsCBb6ap_BJZgYIIahmGfrMPJcbh0JUZgMwIGAMWed-snrHVzWMaxnG8YgImSf1mAhth-KucZghYrYIGtAANyhxAxYAWSShX7rtsA1uIW3WbW3VYe1hbgEQBbAgAIwW3XSfJ9WvEcMAXt6hAroAL3AfIFq-2HE9SzOeuAawM6cIufrjkA7BAeKDsbQGpeB-mrusaHsFhu6frAQJ4t1nqAAUMuAOAYAAYUCZB_Br_GoGCCxh7gax4cS471fwZW1uV7eYFjuPrAWv38Zgc2QGJvXydhtu75gQqLDgQIdu7vv8cagBlJfE7P8-L4v38FfAAQgtFAYdg4APuubQIwDCZT0Wl4A6yA3Bx0CMlEo9R6ixUYEVE60CbbnyIfdEhMUhqGCAA) ?
![image](https://github.com/apache/echarts/assets/13038071/6ba43a7a-bfa2-4fa9-86fa-799d972b78dc)

**Comment by zm9913** [comment]
> maybe [like that](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAFiArgJwjAvDA2gKBjABgBoYBGEgJhIGYSAWEgVhIDYSB2EgDhIE4TSxMuTJUytMgzLMybMpzI8y_GBSEVyeVWIrUcAXQDcOAPQmYAB2QBTKFACW15AFp7AczAgbOUJFgATAEMATzRMXHIqWgZmNnYDYzNLGztHF3dPb19oGCCoQIxsLCEhRn0SYoEBcux1EgIaypgJBoqhKVbapnrGoTlOpoUBoSVhvh62gRLegREKGdF6BdIJUmWpNcnpGmW5OmWFFmWlfa3SFVOu1SFqBY0drYodO4kyipEhdkaRD-_KCewIhafxgHRBMgGIn6IKGINGIJUkKmTBBpDmqOe7wEEiOWMkfFRMjRqLkuMBAgUXzxpCUXFRKlI8zxahRzJEb3J2g4IN0lEaYiEm2wYh-_P-hDFzQBWDEYIqYghkuh8o40rE8JVMERksED2Fsz5msZ1SNEl4OqkdKNRIGItJOoUHJlAiUTpFKjdlE-kvuoJ9mP1qgklywLW5FVWetD4oGEmBEfo0teSdYKZgsITMCUQujWrTupgTtWIhDqzEVOwq1WpYEG1umdIRKZlYEcnNDcdjVWrq7AgZsa9rF7qhLw6eS0zvLIjQ6JuwGyjUgFM5o0qkcvn3WnFSkys36bX3EPedUK7I7TPaIn--Np532OvWA268vRJDGzkjMvChzG1pl49M8WWaICRArJ9KDEet9ynAYIUNbAiTnLAZGXCoZDjRoZA3FCtzg1MJXQ1VCMQo871Ik98PPR8iVFIjFkLLCH3PJj8UY-jG3DCjSE_HMiUOViaWlIlAPo4DoNwkcaMghDJNgxp-mQz9pTkNDsDkeN1MTEisDkRUKlJFTiIGOQNS0yiFORbdzKvHTPwDXTmJzT8pAkz9sMs2QjPkbyhLsvtvOA5zKHRAyZPIxygyHfQcAAOgAW0CCwAAoADNEDAYAHHAGBkvsKBrHigBKGAAG8cBSFAwGwfLCqwIVavi4oakamV9BgAAfDqYAAcmcHqjBwABfIrjBACxsuqzByvwKAQBAAAbBwLAALjKrR8AsEAIHy-xwDWnq5osHqtCGogtDcZB7H8NaZvweBrHcOAoAOxgCAAUh6877pgI6DrUT7Tu-mAAA8AEEQfsCBbo23JAnyNaEBQCBgfwCALAW_KwZsQJbp-tGEAAdzWqBkEQawfrO2GQFS1KIFsNbnBEWHAkhiAABl7DAawVtK8AAC0nBAFbUsCBb6ap_BJZgYIIahmGfrMPJcbh0JUZgMwIGAMWed-snrHVzWMaxnG8YgImSf1mAhth-KucZghYrYIGtAANyhxAxYAWSShX7rtsA1uIW3WbW3VYe1hbgEQBbAgAIwW3XSfJ9WvEcMAXt6hAroAL3AfIFq-2HE9SzOeuAawM6cIufrjkA7BAeKDsbQGpeB-mrusaHsFhu6frAQJ4t1nqAAUMuAOAYAAYUCZB_Br_GoGCCxh7gax4cS471fwZW1uV7eYFjuPrAWv38Zgc2QGJvXydhtu75gQqLDgQIdu7vv8cagBlJfE7P8-L4v38FfAAQgtFAYdg4APuubQIwDCZT0Wl4A6yA3Bx0CMlEo9R6ixUYEVE60CbbnyIfdEhMUhqGCAA) ? ![image](https://user-images.githubusercontent.com/13038071/270523049-6ba43a7a-bfa2-4fa9-86fa-799d972b78dc.png) NB: please close issue if problem solved.
Thanks !
