### ISSUE TITLE
ECharts 为什么要部署到国外? 官网都进不去 唉

### ISSUE THREAD

**Issue by shenxianhui** [apache/echarts#19152]
### What problem does this feature solve?

翻墙也没用

### What does the proposed API look like?

我只求能让我在国内快速打开文档或搞个离线版文档查询

**Comment by Ovilia** [comment]
Apache ECharts 的服务器节点在国外，有时候国内访问不太稳定，但是我们无法私自搭建镜像。如果你有需求离线文档，可以参考 https://github.com/apache/echarts-website 的说明搭建本地的文档。

**Comment by plainheart** [comment]
> 搞个离线版文档查询

可以尝试使用 [echarts-offline-doc-cli](https://github.com/plainheart/echarts-offline-doc-cli) CLI 工具生成一份离线文档。
