### ISSUE TITLE
[Feature] 能不能提供 一种机制， 让我能实现类似webpack 钩子一样的方法 来劫持echarts 的setOption， 这样我可以自行处理echart 样式相关业务，而不用把业务与样式耦合？

### ISSUE THREAD

**Issue by xiatianshitiancai** [apache/echarts#19157]
### What problem does this feature solve?

[Feature]  能不能提供 一种机制， 让我能实现类似webpack 钩子一样的方法 来劫持echarts 的setOption， 这样我可以自行处理echart 样式相关业务，而不用把业务与样式耦合？

### What does the proposed API look like?

echats.setOtionBefore((option) => {
  let newOption =  modOption(option)
  return newOption
})

**Comment by plainheart** [comment]
那你直接重写下 setOption 方法不就可以了嘛... 参见 https://codepen.io/plainheart/pen/xxmWoop

**Comment by xiatianshitiancai** [comment]
这种如果在import * as echarts from 'echarts' 里面 可以这样写吗

**Comment by Ovilia** [comment]
> 这种如果在import * as echarts from 'echarts' 里面 可以这样写吗

那你封装一下提供一个新的方法呀

**Comment by plainheart** [comment]
那就用 ECharts 本身提供的 `registerPreprocessor` API 吧，这个没什么侵入性。例如：
```js
echarts.registerPreprocessor(option => {
  // 可对 option 进行修改
  option.series[0].type = 'bar'
})
```
