### ISSUE TITLE
[Bug] Baidu Map extension throws error after calling `map.clearOverlays`

### ISSUE THREAD

**Issue by Zeng-Fan-Yi** [apache/echarts#19162]
### Version

*

### Link to Minimal Reproduction

When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?

### Steps to Reproduce

When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?

### Current Behavior

When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?

### Expected Behavior

When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?

### Environment

```markdown
When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?
```

### Any additional comments?

When using Baidu map extension, once I call map.clearOverlays method, drag map again, bmap.js file will report error, it seems that some overlays that are not defined by me have been cleared by mistake. And I am in Baidu map superimposed on the thermal map will also be clearOverlays method clearance, what is the solution?

**Comment by plainheart** [comment]
百度地图的 clearOverlays 会把包括 ECharts 图层在内的所有覆盖物都清除，因为 ECharts 也是借助百度地图的自定义 Overlay 来实现的。建议不要使用 `clearOverlays` API 来清除内容，而是在添加覆盖物之后自行保存，并使用 `removeOverlay` API 删除不需要的。
