### ISSUE TITLE
Chart looks weird when using scale at axis and has close data values

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#19164]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/qBLKrzQ

### Steps to Reproduce

Check link

### Current Behavior

Axis max and min values are not calculated well.

### Expected Behavior

Add some space from bottom and top. I have data 29.04 to 29.04001.  Axis max and min could be 28 to 30.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

This case occurs when I use scale true in axis.

**Comment by helgasoft** [comment]
We can control [yAxis.min & max](https://echarts.apache.org/en/option.html#yAxis.min)
Add this to your code and see if it helps:
```
offset = 0.0000002;
option.yAxis[0].max = offset +Math.max(...option.series[0].data.map(x => x[1]));
option.yAxis[0].min = -offset+Math.min(...option.series[0].data.map(x => x[1]));
```
