### ISSUE TITLE
[Bug] emphasis.labelLine not work in pie chart

### ISSUE THREAD

**Issue by PPMeao** [apache/echarts#19160]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/s/apache-echarts-demo-forked-dj2pkt?file=/index.js

### Steps to Reproduce

an example from the official doc,
just an existing issue, and it should have been fixed(https://github.com/apache/echarts/issues/16539), but actually not

### Current Behavior

label lines are not hidden when emphasis

### Expected Behavior

label lines should be hidden when emphasis

### Environment

```markdown
- OS: MacOS 13.2 (22D49)
- Browser: Chrome 118.0.5993.11
- Framework: Vanilla
```

**Comment by helgasoft** [comment]
Bug confirmed.  It does not work for **line** chart also. 
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMrGAJ4gCmRA5AMYCGYFA5sAE6nWwC-ANGrFI58RJHwF4KbCBUKwA2gPSp0q2AHp1ZSjRAzqvWG3oATCAFc51AKwAGAKQGlq7VVjUANhGgUDsCtC0wCZuSJg00PQAtr6GpDQAbvQe5r48hnikUQBGwB4AyhAAXm4ATKX8augmjPREilWqYUkpbgCMtgAsAByGkTE0-RT0bLQAFrAAotDM3mnijcqwLalEAOwAzNZ90W7UACIQbBS0YFwLi83Jq7DW3bY7A-6TUfQQHueVl8vXbj2djz2AFVoFA4FgTHhPs41FdWkQNrYHrB-nsAGoQELAWAQqE8GGwAC6XzUHno2QoHlEsDwY2AAHciGA2KlDGY8GB6IE_p10gSyRSPAAZObU2kMpksih8xoUKIgMb0PAiZAE9ACyliumM2AAM2Skhliw1wtFxHFOv1HkNFzU3Gc9vQhJQ3AA3EA)
