### ISSUE TITLE
[Bug] Overflow of the pictorial elements when y-axis is set to a min. value other then 0.

### ISSUE THREAD

**Issue by battlebeast01** [apache/echarts#19173]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=doc-example%2FpictorialBar-symbolSize&reset=1&edit=1&code=G4QwTgBGD2DGDWBTALhAvAKAhA5ABxGQAsAuAejIFkBaAJgBZ6A6AZgE4A2AGkdbbdgAGLsMFN6AdjpM2LAIzT6tKRyYBWObVi0mADjltquprVpyuLEwrlqmEwWwtXqNuw4DOtiWzVc5rXRYuLx8uCVZaNQBhOhZw_V0LNiYObzpedm4M_nTmTJ48_gAvCBpaDjE483oxXWUhEWpLXX0XHTZ6Dia9VrljeQFBRTluMXLaamY1DlGUjkNVDQkiOXCOXXohcTlzfx9aERSJX2Y5QXpD1N9FgwbbWjYFZok_ftXu3Re-1lWACToKqwJHISmU1MwJPRfN8fHJYC4ZI4hpYKkF_KkuijBEFLJDNsIdIJ1n4UponHinKjyYxYHsWiJKYIJuiJNwsRNcYwAMp0NQ6Y5fYyw3kQqGvGQaUG82x88w6Uy6YDUWwOXQrcRM4DMTgCdHYklmIK2DrmFXzMIyQS7HRqIgucKCaIA_xxILhV288IMXyWNRqXTS9RmLjy2i6IplDgql7ZQaNRYSKQQszUBNSOTMXScITKmRKYJ2DrUd2RAveejFiJqdyVWQW-j0yxmXZeQS6GLlGXsHj-TqGTtMQQxwr9qOD4d8NhSyI6FhZWw2AA2CNWXX8pgAMiK7FmeLpl73PpNB_MD4ODCGmDsOGeGwHmuUiMYiRItzPWPOr2oijgANwYaA8GQABLaAADt0AgABvLAIFgaBF2gMASAgABtHAAGIACMsMEPD6BwLhcAwgAxEiABEGwAQRwABdLhYMXRAAHNEDAgATFCYOwbB2MIEAUPQvBgNgZAkOAkBFwgRAmIAWzY5BCNwMBEAAM0QFSwNgRAICw8A6NggBfBjsAADyo0zgPcLjYN4_jBJwEAlJwLDnNgZz2LokyeJASz3AAFRE-AbJ4nj3CIaAAHcUNUyT3EQWyIGMxLfKsjcQCwmSQtCiBgLA5ANNARcUMERLDKM7yAE8LKs7LsFkvKULObzsHcPBF2A5ANzyxAuIgcKopiuKdPK7BkuwZiwGAzjoMSpjVOQFCahaqBgOYohFogM4Ktg-KpsQay0MS7icuQSq8F63BhNE8TJIAIX0lbsDAkB5JQ_ARLEqbJOkuSFMIxLWsq2SsIQlCYAQFAnogIomuEQGID45ABKOnKeJOtHsCKgBXS6Kmh0L3GB0HFy5YCiku1CEbRnA1EEABSAHMZynAzgZnAIAoLa8PpiBoFUiBiB0ohEDWja-YFlT1M07TdPAJhqZ42jFfGzGMcxnG8fh5mgZBhCyYpwTFdC2n2YJnLNEETmyAgEjgNMxB2IgEWxdQTWFZ1iBleZ1W0fVtHNZQ_Hjf64n9fJy66etiAAFEAEdseAoqFMF6A0Lpoi6e9zHfZy_2csDiBg89om9cXAAlRALsIFDkDAXHzd1kmDcunB7EZ6P48T5P8tTtC27N3B24Mz2uaojjdOgYgIEi6bp5ACeXfW1ALrAbT8pAViIHAHTYEk2BscXQhHbl-L2JDrnwMFkWZ7nogJagNSNLY2W9MgSKRYg0uScr6vUGxs-Hsc4I2zmNFa-czoXXem_JmOUXpvWUk_GWOkYHQzfgAcRAHgd6LgeawNCkjFGqF8ZF2EKQoiFRQFJVgsrQy_4x7sSduxA6sAppAVAmBdwCtVLYy0iBK-IBGHkRYWw_hnCAAUABKWaWNwCIxEcBdh4F3CQSpqFNRLNv7h0NmhAARHTemuiiK6LZoY2i-CeI4H8kQQguVrIWOwKbXm_NH7SxfiguRs92LEAcbgUxD8pbPy0h4yAS8NpMBwIleiiUNEmy0aTCOgl9EMyMVtWgghzHQysTY1AtVfFOICUg9xct353y4Pk1S9sT5hNQJbCJUSVroXiS3FCdNnKIATknSSKcxLpzIVnLyMSEY4GaYkiAuj266PyR07u3Te69NQhMlJxjJmZOGfkgA6p_UOZdf6IFsQAx2RFQY-KyV4-ei9RbLwgKvdeyMt473yXvRcB8j4FSdnpM-fMIJC1vt4--_N8mBOQSU-poVs60X_PVSqUQbFgGQEweKyAADySiwLiOOgjSaWCiAiRQoBMRTBzJ-SYIQpgsksHiJ4XwjhEBxGdUQLJAAcq9RARE8rMNMtI_O2AVLIGxmACCPKeKQNbpNaA2M8C-NCngaA7hOocJQrJGFcKEXwTAsADSyB_LQAAApVMXOInAk1ppKVQhyxApkiL2FopIxucFcWLnYppI2ntsDCrRqK96BVTKKXtaFeam0cB3I0tKzGYlsG4AaowpiYa0buDOkxOqbrsA-s2sw9wrDFFiPcOajilraJMAAFbQDykagAOmBHAdqQ5o0qYuYqxEcJ4XOJElNYDa08VhtzOQnbRo6yoaFOhCNDKSLKuA_qwEmL5VrvXEasFJH_nKkiwK8kJXICpbw0StKpEyO3kIhRaL3BSKhRAZVsLwAIvAkayVSNHZKUEexYRmbREcPcIujAxluaCEXUAA

### Steps to Reproduce

1. create a bar chart with pictorial elements
2. set yAxis.min to a certain number other then 0 (in the given example to 10).
3. series-pictorialBar

### Current Behavior

when i set yAxis.min to a certain number other then 0, the pictorial elements overflow the axis.

### Expected Behavior

there should never be an overflow of pictorial elements, they should always start from the set yAxis.min value.

### Environment

```markdown
- OS:Linux Ubuntu 22.04
- Browser:Chrome 96.0.4664.55
- Framework:Vue@2.6.14
```

### Any additional comments?
I especially would like to fix this issue while keeping the pictorials repetitive.

**Comment by Ovilia** [comment]
Just to clearify, like with bar series, when min value is set to be 5, a bar with value 15 will be rendered like this:
<img width="174" alt="image" src="https://github.com/apache/echarts/assets/779050/aeff7022-280b-41fa-a027-10bfcd0d03d2">

So should a pictorial bar. The should will be clipped.

**Comment by Ovilia** [comment]
BTW, if what you want is changing the position of the bars, you should use `grid.bottom` and `grid.top` to adjust, instead of using min value.

**Comment by Ovilia** [comment]
Since according to the document, there is no `series-pictorialBar.clip`, this should be a new feature instead of a bug.

**Comment by battlebeast01** [comment]
> Since according to the document, there is no `series-pictorialBar.clip`, this should be a new feature instead of a bug.

@Ovilia this is exactly what is needed.
