### ISSUE TITLE
[Bug] 饼图打包后动画不一致

### ISSUE THREAD

**Issue by MasterJoyHunan** [apache/echarts#19175]
### Version

5.4.3

### Link to Minimal Reproduction

https://github.com/MasterJoyHunan/echarts-pie

### Steps to Reproduce

`npm run build:prod`之后，dist 目录打开 index.html 饼图动画效果与 `npm run dev` 的效果不一致

### Current Behavior

![GIF 2023-10-7 16-21-08](https://github.com/apache/echarts/assets/25575041/57dea348-57e3-4142-949b-815eaf78d013)

### Expected Behavior

![GIF 2023-10-7 16-24-31](https://github.com/apache/echarts/assets/25575041/6b693263-001b-42c3-8326-1e5e23f9bc0c)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
目前按需引入需要手动导入一下 `LabelLayout` feature，否则 build 时会被 tree-shaking 移除。

```ts
import { use } from 'echarts/core'
import { LabelLayout } from 'echarts/features'

use([LabelLayout])
```
