### ISSUE TITLE
[Bug] Label cannot be turned on independently from symbol in line series

### ISSUE THREAD

**Issue by hughess** [apache/echarts#19178]
### Version

5.4.2

### Link to Minimal Reproduction

https://jsfiddle.net/ky4cdvr1/

### Steps to Reproduce

1. Create a basic line chart
2. Add `label: {show: true}` and see labels appear
3. Add `showSymbol: false` and see labels disappear

### Current Behavior

I want to show labels, but not show symbols. When I turn labels on and symbol off, the labels also disappear.

### Expected Behavior

You should be able to turn labels on or off independently from the symbol.

### Environment

```markdown
- OS:macOS Monterey
- Browser: Chrome
- Framework: N/A
```

### Any additional comments?

Workaround is to set the marker style to size 0 or transparent, but that's a messy solution.

**Comment by plainheart** [comment]
As a workaround, you can set `symbolSize` to `0`. See this [example](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpP6MAEZU_m5xHnjawADuRGAcSpOwDit45AC2w8D-JhAAXt6ZK1SbINqMeK7xCeh4TP7eAGYB4St2cZ_otnYA3EA).
