### ISSUE TITLE
[Feature] How to draw multiple independent nested circles

### ISSUE THREAD

**Issue by sshallow** [apache/echarts#19189]
### What problem does this feature solve?

How to draw multiple independent nested circles
1：
```

option = {
  legend: {},
  tooltip: {},
  dataset: {
    source: [
      ['product', '2012', '2013', '2014', '2015', '2016', '2017'],
      ['Milk Tea', 86.5, 92.1, 85.7, 83.1, 73.4, 55.1],
      ['Matcha Latte', 41.1, 30.4, 65.1, 53.3, 83.8, 98.7],
      ['Cheese Cocoa', 24.1, 67.2, 79.5, 86.4, 65.2, 82.5],
      ['Walnut Brownie', 55.2, 67.1, 69.2, 72.4, 53.9, 39.1]
    ]
  },
  series: [
    {
      type: 'pie',
      radius: '20%',
      center: ['25%', '30%']
      // No encode specified, by default, it is '2012'.
    },
    {
      type: 'pie',
      radius: '20%',
      center: ['75%', '30%'],
      encode: {
        itemName: 'product',
        value: '2013'
      }
    },
    {
      type: 'pie',
      radius: '20%',
      center: ['25%', '75%'],
      encode: {
        itemName: 'product',
        value: '2014'
      }
    },
    {
      type: 'pie',
      radius: '20%',
      center: ['75%', '75%'],
      encode: {
        itemName: 'product',
        value: '2015'
      }
    }
  ]
};
```
2：
```
option = {
  color: [
    '#c23531',
    '#546570',
    '#5470C6',
    '#91c7ae',
    '#749f83',
    '#ca8622',
    '#bda29a',
    '#6e7074',
    '#546570',
    '#c4ccd3'
  ],


  polar: {
    radius: ['20%', '100%']
  },
  angleAxis: {
    max: 4,
    startAngle: 90,
    splitLine: {
      show: false
    },
    axisTick: {
      show: false // 隐藏角度轴刻度线
    },
    axisLabel: {
      show: false // 隐藏角度轴的值
    }, 
    axisLine: {
      show: false
    }
  },
  legend: {
    show: false,
    
  },
   axisTick: {
            show: false // 隐藏 x 轴刻度线
        },
        
  radiusAxis: {
    type: 'category',
    data: ['14.5亿 \n5% \n+10% '],
axisLine: {
      show: false
    }, axisTick: {
      show: false // 隐藏角度轴刻度线
    },
  },
  tooltip: {},
  series: [
    {
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.1)'
      },
      name:'2%',
      showBackground: true,
      type: 'bar',
      data: [2],
      roundCap: true,

      coordinateSystem: 'polar',
      label: {
        show: false,
        position: 'middle',
        formatter: '{b}: {c}'
      }
    },
    {
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.2)'
      },
            name:'3%',

      showBackground: true,
      type: 'bar',
      data: [3],
      roundCap: true,

      coordinateSystem: 'polar',
      label: {
        show: false,
        position: 'middle',
        formatter: '{b}: {c}'
      }
    },
    {
      backgroundStyle: {
        color: 'rgba(180, 180, 180, 0.1)'
      },
                  name:'5%',
      showBackground: true,
      type: 'bar',
      data: [2.4],
      roundCap: true,

      coordinateSystem: 'polar',
      itemStyle: {
        borderColor: 'green',
        opacity: 0.8,
        borderWidth: 1
      },
      label: {
        show: false,
        position: 'middle',
        formatter: '{b}: {c}'
      }
    }
  ]
};
```
![image](https://github.com/apache/echarts/assets/21257340/ebaf5afc-1068-40fc-a4dc-c25c8ef7b099)
![image](https://github.com/apache/echarts/assets/21257340/fc6f2333-9480-4136-a320-ae7bf33505a8)
<img width="316" alt="image" src="https://github.com/apache/echarts/assets/21257340/fb319dd2-e425-4d81-9f03-298623bdd75b">
i want 3
Both images are EChart. There are four pie charts in the first one, and three rings nested in the second one. If I want to transform it into a picture, this picture is 4 nested 3 rings, how to transform the option.

### What does the proposed API look like?

i dnot know

**Comment by helgasoft** [comment]
use polar coordinates with multiple centers, then use matching _angleAxis_ and _radiusAxis_ entries through _polarIndex_. 
Finally set your bar series with appropriate _polarIndex_.
I learned it from [this offical example](https://echarts.apache.org/examples/en/editor.html?c=radar-multiple).
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWAbApgcx2gBMAuJWAXwBoB6GgZwAtgB3E2AMwEMt6cr0mMMGBZIIdkmrpBsEKK4AndgG1Zmcoq5EIAV3rsA5AFYADAFJDVTAGNCYHMtgrDAJmOXrJi4YC616QxMZFgtHX0jM09be0dVQwB2DytYb0t_SgEg_1kuaDxcAEEADwgDZ3VkSvksJQBJYhxiklMs4NgAWy5m2AAWNuD6MCUwQvzcdgBOVsr6ECwIMAAZCGgcSUrMJlZ2bl4cSsD27rKAFQgbAGsNoPbttk4ePlg6WEAEtMB50MAlyMAyvUAXeMA3Eo_QD9focBpgTvQllwAEY4LA3dpbZgPPbPV6fX5_QAhboAeBTBsEqkJWa0RSPuuyeB1ulDBlVQNJq9UazQAjODOt12P1ZsNFKNxutYNMOXMFstVkKGUjYBTHvs6TTIecrmS7ijKfsXjR3t9_kDQTSjsFibD4WrBhr5eidZj_niCUTSlDJRbkTtrdT2hRDrIckEwnp6CUyqp6ZtYGAAJ4gIWGGxcBx4YCKKNWCNERNceKs3oAOmMgH65WAAHWgHlL0AA1KyLKl_TLia6qjT1R60V6kdRYMqLtcWzL3aiqdrdViDRHjZgpwOkdHY0YE0mU2nrEzFA0iE0SOyM1mc_mi5WK2Wa3W_ByIc6SVKI0PNXxJ9Ze6rZzK5R3R3bASCn4rMA2sqOBAODlGoNLSnOMZxjCSjpq2sCZsMqj9LAADM1iuNY7KwKYgHtDYIiKDo0CJjgADKUZDDgHRGOu8EyqRHRxgA6oszC6GAsAAErALoxCwAAwlwIAMUiiw0eR0YTG-SIwimW6KIJogpkYig4EQYkyqAXA2IsUbsKYeYAByXsE8nEY4bFEGAjDsKyk7_sEkHtPOMFwWZSHZs4qEYbAWGwDheFmYRCmrGRlHUbRqT0WZTGsexPF8QJwmiWZijJUQqXsGAii6PwEYSR0UlRjJLlyQpjjKVgqmpHg6mEFpSI6Xp0aGSZZmYBZinWbZ9mOUaHKvAAtKNY3jRNw3hghblGLBigpOum7bruCFeSh1h-QFQX4cEoXEeFDiRQ40WGLFEbxUYbG2XxXG8fxRBCSJTWYEVJVlXesDdVVKlOIY6maZ1sAtfp7WmZ932KL1dmBQN3ocuVQjQXNHlyAoG4sjunn7j5m2Ydh1jBRG-0kRFVEnXR6MvbAl2pNdjBJQ9T1pRGGUPdlkZ5QVCFvdJt4IV1lVKb9Rj1TgjVAyDbW4R1ENC9D_UIT6Rp-ugFAANxAA).
![image](https://github.com/apache/echarts/assets/13038071/2ffcb5b3-9645-4f97-a4ee-3657c24a2291)
NB: please close issue if problem solved.

**Comment by sshallow** [comment]
@helgasoft tks!
