### ISSUE TITLE
[Bug] Missing some data when data array is large

### ISSUE THREAD

**Issue by SmrTalebi** [apache/echarts#19188]
### Version

5.3.1

### Link to Minimal Reproduction

https://codepen.io/samiratalebi/pen/bGOZbqM

### Steps to Reproduce

1- Set the date as XAxis
2- Set two data as the sample code

### Current Behavior

The value for the last date shows wrongly for Union Adds. 

### Expected Behavior

The correct value for Union Adds for the date **11/10/2023** is **25328.0000** but shows 25470 which is wrong. The situation gets worse when the length of arrays goes up and shows one of the chart's data wrongly. 
Each chart works fine separately but doesn't work together. It seems a bug on the chart. 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
It's just because your second series data has 249 items, one more than the first series and the xAxis (248). It would work as expected if you kept the length of xAxis data the same as the length of series data.

**Comment by SmrTalebi** [comment]
The length could be different. As per this sample:
option = {
  title: {
    text: 'Stacked Line'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine']
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      name: 'Email',
      type: 'line',
      stack: 'Total',
      data: [120, 132, 101, 134, 90, 230]
    },
    {
      name: 'Union Ads',
      type: 'line',
      stack: 'Total',
      data: [220, 182, 191, 234]
    }
  ]
};

The result is correct when length of XAxis is different from series data:
![image](https://github.com/apache/echarts/assets/114631122/a6ce1077-e60d-4905-9924-0c2b5af90e7f)

**Comment by plainheart** [comment]
No. The only thing you must do is to make sure the axis data items >= the data items of each series.
