### ISSUE TITLE
[Bug] Flickering and overlappying labels on line chart

### ISSUE THREAD

**Issue by hughess** [apache/echarts#19190]
### Version

5.4.2

### Link to Minimal Reproduction

https://jsfiddle.net/6n2dtwjh/

### Steps to Reproduce

1. Create line chart with points close together
2. Turn labels on
3. Hover over the labels

### Current Behavior

The value label appears on hover for every point you move over, but these sometimes overlap with the existing labels on the page.

<img width="301" alt="CleanShot 2023-10-11 at 10 02 43@2x" src="https://github.com/apache/echarts/assets/12602440/a42f9604-00f5-486f-8b46-cf0a51c24e6d">

### Expected Behavior

Is there a way to turn off labels on emphasis without having them disappear on hover?

What I'd like is for the labels on the chart to stay as is when I hover over them. The tooltip is doing the work of showing the specific point's value, so I don't want to duplicate it.

I tried setting `label: {show: false}` in `emphasis`, but then it makes the label disappear when I hover over it:

<img width="324" alt="CleanShot 2023-10-11 at 10 05 56@2x" src="https://github.com/apache/echarts/assets/12602440/612e4ee3-d091-4c07-9d86-874156dfbe33">

### Environment

```markdown
N/A
```

**Comment by plainheart** [comment]
Try to set [`axisPointer.triggerEmphasis`](https://echarts.apache.org/option.html#axisPointer.triggerEmphasis) to `false`.

**Comment by hughess** [comment]
@plainheart that worked - thank you!!
