### ISSUE TITLE
[Bug] Barchart: Labels below min are not always shown

### ISSUE THREAD

**Issue by tmtron** [apache/echarts#19196]
### Version

5.4.3

### Link to Minimal Reproduction

[Reproduction](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVpZesWgCFaAXRIBfPunI58RVKTKUa0gG6MANgFcqvfrAC2EaEQCMABmWrYeKhwhVCsUVe0dWCEwET8AJicnHlgAWnD5Nx0KajoAI0YOSyDYY0Y0qmMtKx08AAtgAHciMA5zJKCQYDwISBg6MFBaEtglKz70RSUAbiA)

![2023-10-12_09h17_13](https://github.com/apache/echarts/assets/20422904/52181737-c239-4715-ba2d-2bc4ee8a315d)

### Steps to Reproduce

* create a bar-chart where yAxis min is e.g. 10 and have values above and below the min
* show the yAxis labels
BarChart options:
```typescript
options = {
  xAxis: {
    type: 'category',
    data: ['A', 'B']
  },
  yAxis: {
    type: 'value',
    min: 10
  },
  series: [
    {
      data: [200, -2],
      type: 'bar',
      label: {
        show: true,
        position: 'top'
      }
    }
  ]
}
```

### Current Behavior

* the label '-2' for bar 'B' is not shown

### Expected Behavior

* the label '-2' should be shown

### Environment

```markdown
- OS: Windows 11
- Browser: Google Chrome
- Framework: none
```

### Any additional comments?

* when min is set to `0` (instead of `10`), then the label is shown correctly: [Exmaple](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVpZesWgCFaAXRIBfPunI58RVKTKUa0gG6MANgFcqvfrAC2EaEQAMy1bDxUOEKoViir2nbBCYCI-AEwODjywALSh8i46FNR0AEaMHJYBsMaMKVTGWlY6eAAWwADuRGAc5gkBIMB4EJAwdGCgtEWwSlY96IpKANxAA)  
![2023-10-12_09h17_51](https://github.com/apache/echarts/assets/20422904/e0fbe3d8-d679-431c-bfa9-6cbfbb7f053b)

* when all values are below the min, then all labels are shown correctly. but I guess this is just because of another bug #19187.  
Note, that the min setting of 10 is in ths case ignored and used as the max instead!  
[Example](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVpZesWgCFaAXRIBfPunI58RVKTKUa0gG6MANgFcqvfrAC2EaEQCMABmWrYeKhwhVCsUVe0dWCEwET8AWgAmJyceWCj5Nx0KajoAI0YOSyDYY0Y0qmMtKx08AAtgAHciMA5zJKCQYDwISBg6MFBaEtglKz70RSUAbiA)  
![2023-10-12_09h16_35](https://github.com/apache/echarts/assets/20422904/962485b5-2f12-46e9-9a9f-3f381df174f4)

**Comment by tmtron** [comment]
>When yAxis.min is above the top of a bar, that bar becomes invisible.

That statement is wrong. Just consider this [Example](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVpZesWgCFaAXRIBfPunI58RVKTKUa0gG6MANgFcqvfrAC2EaEQAMy1bDxUOEKoViir2nbBCYCI-AEwODjywALSh8i46FNR0AEaMHJYBsMaMKVTGWlY6eAAWwADuRGAc5gkBIMB4EJAwdGCgtEWwSlY96IpKANxAA) where `min=0`, but the `-2` label is shown.     
![2023-10-12_09h17_51](https://github.com/apache/echarts/assets/20422904/e0fbe3d8-d679-431c-bfa9-6cbfbb7f053b) 

So I hope we can at least agree that the behaviour is inconsistent and confusing to users.   
And to resolve this, there are some options how to handle labels when the value is below min:
1. show them (what I prefer)
2. hide them (what you prefer)
3. add a config option to let the users decide

I think that the least surprising thing is to always show labels. And another advantage is that you can then also differentiate between a value that is just below-min or missing (i.e. NaN, null): [Example](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVpZesWgCEptAMK0AuiQC-fdORz4iqUmUo1pAN0YAbAK5Ve_WAFsI0IgAZ1m2HiocIVQrFE7fQNYITARAIAmFxceWGhLc3M4gFpo5Q8DCmo6ACNGDlsQ2HNGXKpzPTsDPAALYAB3IjAOa0yQkGA8CEgYOjBQWmrYNTtR9FU1AG4gA)  
![2023-10-13_08h52_18](https://github.com/apache/echarts/assets/20422904/87d68c08-b7ac-4fb1-900c-c360ea5717dd)

**Comment by helgasoft** [comment]
> _"When yAxis.min is above the top of a bar, that bar becomes invisible."_
That statement is wrong.

The **top** of this -2 bar **is at 0** and yAxis.min is 0, so the label is visible (0==0)
If yAxis.min is above 0 (like 1), then label becomes invisible (1>0)
So looks like your example confirms my statement.
And I have no preferences, just trying to explain ECharts' brain to the wonderful people coming here.

**Comment by tmtron** [comment]
@helgasoft You are absolutely right. The top of the bar for negative values is of course always 0: e.g. for the value -2 the bar ranges from 0(=top) to -2(=bottom).

So I will close this issue. It is not a bug and working as intended.

I still think it would be nice to have a way to show those of-the-grid labels, so I may open a feature request for this.
