### ISSUE TITLE
pie环形图如何在中心设置标题

### ISSUE THREAD

**Issue by surongm** [apache/echarts#19208]
### Version

 "echarts": "^5.4.2",     "echarts-for-react": "^3.0.2",

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut

### Steps to Reproduce

官方案例好像没有 圆环中间标题的api

### Current Behavior

https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut
官方案例好像没有 圆环中间标题的api

### Expected Behavior

![image](https://github.com/apache/echarts/assets/41141486/fa152503-7372-470c-9935-1ff51ed24a86)
想问一下要实现环形中间标题该如何实现、最好还能设置背景色

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by surongm** [comment]
> title:{
>     text:'tada', top:'center', left:'center', backgroundColor:'pink',
>     subtext: '15781', 
>     subtextStyle: {color:'#000', fontSize: '36px', fontWeight:'bold'}
>   },

是这样子的 我的饼图每个扇形的label在外面、底部还有图例，所以给饼图加了
{
top: -10,
bottom: 20,
}
这个时候 再设置title 它就无法居中在环形的中心
![image](https://github.com/apache/echarts/assets/41141486/a0342aac-d89d-4e77-a1e9-d1e338376ca6)

还有它的背景色 我想设置的是整个圆环内部的背景色
现在通过画两个圆来设置，不知道还有没有其他的方法。

**Comment by helgasoft** [comment]
sorry, we cannot guess your code to provide help
