### ISSUE TITLE
Axis Level tooltip feature in echarts , when user hovers on axis label tooltip should be shown 

### ISSUE THREAD

**Issue by RahulVishK** [apache/echarts#19207]
### What problem does this feature solve?

"We actually need a feature to display a tooltip on the axis. Currently, the tooltip is available for series, but we have a requirement that when the user hovers over the category axis or time axis, the tooltip should be enabled."

We went through the documentation reg it we did not find any option to show tooltip when hover on axis label

### What does the proposed API look like?

when user hovers on axis label tooltip should be shown

**Comment by plainheart** [comment]
There is a PR #16315 for this feature. As a workaround, you can refer to this [example](https://codepen.io/plainheart/pen/jOGBrmJ) for adding a tooltip for the axis labels.
