### ISSUE TITLE
[Bug] Cannot setup environment

### ISSUE THREAD

**Issue by Gumichocopengin8** [apache/echarts#19216]
### Version

5.4.3

### Link to Minimal Reproduction

https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment

### Steps to Reproduce

Followed https://github.com/apache/echarts/wiki/How-to-setup-the-dev-environment, but not working

- `npm i`
- `npm run dev`
- `localhost:8080/test` not loaded

### Current Behavior

`localhost:8080/test` not loaded

### Expected Behavior

`localhost:8080/test` should be loaded

### Environment

```markdown
- OS: macOS with Apple Silicon
- Browser: Chrome/Safari
- Node: tried v16 and v20
```

**Comment by Ovilia** [comment]
It should be `npm i` instead of `npm I`. What error did you have?

**Comment by Gumichocopengin8** [comment]
> It should be `npm i` instead of `npm I`. What error did you have?

yes I used `npm i`. It was just a typo due to auto complete. 

I got the blank page. I didn't get the specific error

<img width="1512" alt="image" src="https://github.com/apache/echarts/assets/34010665/5bf3fbc7-6286-4451-8be5-24218c7e8a43">

command line looks ok

<img width="780" alt="image" src="https://github.com/apache/echarts/assets/34010665/082d1e1a-d841-4515-828c-ede542431d87">

**Comment by plainheart** [comment]
It looks like the http-server wasn't successfully started. Can you try running `npx -y http-server` and watch if there are some error or warning logs?

**Comment by Gumichocopengin8** [comment]
The issue was caused by VPN. When I disabled it, it worked fine. Thank you for your help.
