### ISSUE TITLE
[Bug] When the pie chart sets the silent attribute to true, the tooltip does not work.

### ISSUE THREAD

**Issue by wangling6821** [apache/echarts#19222]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-simple

### Steps to Reproduce

![image](https://github.com/apache/echarts/assets/26473852/253a2b6d-ebb2-4403-8b0b-149104204f57)

### Current Behavior

When the pie chart sets the silent attribute to true, the tooltip does not work.

### Expected Behavior

无

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
> When the pie chart sets the silent attribute to true, the tooltip does not work.

not-a-bug, this is by design, all mouse events are ignored when ```silent:true```. 
Tooltip relies on _mouseover_ event which is not triggered.
