### ISSUE TITLE
Broken Paper Link on ECharts Official Website Homepage

### ISSUE THREAD

**Issue by suyanhanx** [apache/echarts#19231]
![image](https://github.com/apache/echarts/assets/24221472/b28abf16-3e9e-474c-99f9-0f901a9d7383)

The link leads to a page displaying a 502 error.

**Comment by harshsharma-11** [comment]
@100pah hllo sir, myself harsh ,mam i am new to apache so i want to join its slack but i don't have email auhtorised by apache with workspace @apache.org so how can i join the slack

**Comment by LuoRiWuSheng** [comment]
官网突然变的好卡， 打不开。加载很慢 
https://echarts.apache.org/


https://[echarts.apache.org](https://echarts.apache.org/examples/en/editor.html?c=line-stack)/examples/en/editor.html?c=line-stack

![image](https://github.com/apache/echarts/assets/23192097/2a008ca6-d4a8-41cb-8a7e-1ce5330906bf)


```

https://fastly.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css
https://fastly.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
```
![image](https://github.com/apache/echarts/assets/23192097/1903eefb-9c68-4b01-8050-7048d48ee31b)

**Comment by plainheart** [comment]
@LuoRiWuSheng 可能是你那边运营商网络限制了，可以过一段时间再看看能否打开该 CDN。jsDelivr 是 ECharts 在使用的公共 CDN，因为某些原因目前国内访问并不太稳定。
