### ISSUE TITLE
[Bug] Rightmost blank space in some of the sankey graphs

### ISSUE THREAD

**Issue by battlebeast01** [apache/echarts#19243]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=sankey-simple

### Steps to Reproduce

1. Create a sankey chart

### Current Behavior

As seen in the example above, there is a rightmost blank space in the chart area.

### Expected Behavior

The chart should cover the whole area that is reserved for itself. There should be no empty space at the rightmost side.

### Environment

```markdown
- OS:Linux Ubuntu 22.04
- Browser:Chrome 96.0.4664.55
- Framework:Vue@2.6.14
```

**Comment by fandi-1205** [comment]
![image](https://github.com/apache/echarts/assets/141796004/04d91ca7-82b8-47bd-bda7-b78120517222)
![image](https://github.com/apache/echarts/assets/141796004/545cd587-eca9-4cfa-90cc-92299f54759c)

Is this the result you want? If so, you can read the official documentation and set the distance between the Sankey component and the container.
![image](https://github.com/apache/echarts/assets/141796004/12e6c3c9-bb36-4e46-8c72-4cc872086ff7)

Set to the same value to achieve the centering effect.
