### ISSUE TITLE
[Feature] eCharts: dataZoom only shows information for the first series if contains 2 serieses

### ISSUE THREAD

**Issue by SincerelyUnique** [apache/echarts#19255]
### What problem does this feature solve?

Hi Team sorry for bother you, I have a case, and I want to only display the first series line in the dataZoom bar (the shadow area that we dragged) , but now I found it always is the total of these two series, do you know how to specify the one fixed series in the dataZoom bar? please kindly help to check, thanks so much~~
You can put below code and replace to https://echarts.apache.org/examples/en/editor.html?c=line-stack
```
option = {
  title: {
    text: 'Stacked Line'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['Email', 'Union Ads']
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '10%',
    containLabel: true
  },
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  dataZoom: [
    {
      type: 'slider',
      showDataShadow:true,
    },
    {
      type: 'inside'
    }
  ],
  series: [
    {
      name: 'Email',
      type: 'bar',
      stack: 'Total',
      data: [120, 132, 101, 134, 90, 230, 210]
    },
    {
      name: 'Union Ads',
      type: 'bar',
      stack: 'Total',
      data: [220, 182, 191, 134, 290, 230, 150]
    },
    
  ]
};
```

### What does the proposed API look like?

I want to specify one fixed series line in the dataZoom bar, not the total, and not changed when I click or switch the legend, can you kindly help me to check?

**Comment by SincerelyUnique** [comment]
I only want to show one shadow line and keep it fixed and not changing with switching legend

**Comment by Ovilia** [comment]
I think you have to make the series you want to put into the dataZoom with a different xAxis and yAxis. I've made a [demo](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtGiBwMIdLJUGxKAVWhQ4AQVY6bpQAahCsOMCw_oHuACIQcg5gru7UOHRyDAAWsACi0IrcvAC6AsLoigomhLK4AGYU7gDMAKSuZrAKilmNlAAsbeXEAEbAYKIAtlSt7bIMMPTcHHTDOFgEYHIArjhlImJYo6SmsnXpYFuJJ7KwWnQAbji-WgCSE3Qq0vwd33pDpL5NFobDJiGAAJ72KgMSw4RTAOTg2YjYBbYwZcEAcToUlgdWcWhwQ3MljoNkoAFkYClKAAVHY0gDqbBptKyWxpADEFDTqJZeWjKKU_jUwZD8O4YWA4QikcTYKM0RZEdjcfisIT5RYrLBbFToKyGUFmaxWeyuTygnzklbBcLYPxikNwYDtCCOhCoe57s4GWVRehPRLKD6sH69E6iNq6AAtMRTAOwAFAl7GMgEACM8pdKbTx1gGb26EJChwwN1HVBsmgdAmweo9kczmRsiDVCwRRbxGjNgzACYAAxuDNNPvDgdZgtNPpuACcQ9gfaaC77GYHkZuSddrzzmfl6Bz2lT4Xzhdk-lkVeINbrVC8PiiAS7gfF7c7-9u9GYVFpY2bH57XU-0HYcAA4xwLWdJyXGdF3nNwmmXBC13tP5Kw6dAb2DUJwkiaJnwwV93A7HgCK0L8mB_P8XAA0lewAVhXUc3EHScM3o2CM3g2BEIXPoUJ-eUr0w2tg3iRIGBtDDCK9SgSN4D9yMYSj3F_egaOkwDrFHBdEIg5dJ0Q2Cmm43iEMHVCHSE6SsKoNIMmyPICnfaS22IlzNyU79VOogitPAhdZ2Y2B50nILOL7biRyQqcLJ-IhSn4ABuIA) for you.

**Comment by SincerelyUnique** [comment]
Thank you @Ovilia , your demo is very cool! that is what I want~ :)
