### ISSUE TITLE
[Bug] Failed to build code: Unterminated string constant

### ISSUE THREAD

**Issue by jia16866** [apache/echarts#19256]
### Version

4.9.0

### Link to Minimal Reproduction

customize download 4.9.0 fail

### Steps to Reproduce

1.customize download
2.select version 4.9.0
3.click download button

### Current Behavior

<img width="674" alt="image" src="https://github.com/apache/echarts/assets/3492599/cc07cff6-007f-45fa-bd4b-ca886e1acacf">

### Expected Behavior

download success

### Environment

```markdown
- OS: macOS Ventura 13.6.1
- Browser: Chrome 118.0.5993.117
- Framework:
```

**Comment by plainheart** [comment]
Thanks for your report. Fixed in apache/echarts-www@e357bb932e1d7f87d3b377a5523d9aa85737f0b6
