### ISSUE TITLE
[Bug] The official example disappears after reopening the computer lock screen

### ISSUE THREAD

**Issue by Surlyyoung** [apache/echarts#19263]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1

### Steps to Reproduce

1. open the official example: https://echarts.apache.org/examples/zh/editor.html?c=bar3d-punch-card&gl=1 
2. lock screen
3. wait two minutes
4. unlock screen

### Current Behavior

The official example disappears after reopening the computer lock screen

### Expected Behavior

The official example performs normally after reopening the computer lock screen

### Environment

```markdown
- OS:macOs Sonoma 14.1
- Browser:Chrome 112.0.5615.137
- Framework:
```

**Comment by Surlyyoung** [comment]
<img width="1642" alt="image" src="https://github.com/apache/echarts/assets/22386735/68c230ad-c0b0-4bf4-8cd7-c9ac401c4b67">

**Comment by plainheart** [comment]
This should not be a bug of ECharts. Please access `chrome://settings/performance` to check if the `Memory Saver` is open and try to turn it off if it is.

**Comment by Surlyyoung** [comment]
<img width="578" alt="image" src="https://github.com/apache/echarts/assets/22386735/e518850f-b744-4095-b923-534eceb697a4">

**Comment by Surlyyoung** [comment]
> This should not be a bug of ECharts. Please access `chrome://settings/performance` to check if the `Memory Saver` is open and try to turn it off if it is.

thanks, it works. and can't ECharts do anything about it?

**Comment by plainheart** [comment]
I don't think we can do something. This is the behavior of the browser for saving memory.

**Comment by Surlyyoung** [comment]
> I don't think we can do something. This is the behavior of the browser for saving memory. Maybe you can add the ECharts website to the whitelist.
I do the same operation on another computer which the Memory Saver is closed,however it performs normally. 
and can you explain it if you can? thanks again.
- OS:macOS Monterey 12.0
- Browser:Chrome 118.0.5993.117

**Comment by plainheart** [comment]
>  another computer which the Memory Saver is closed,however it performs normally.

Closed or open? If it's closed, there is no problem. You need to test it with the Memory Saver opened.

**Comment by Surlyyoung** [comment]
> > another computer which the Memory Saver is closed,however it performs normally.
> 
> Closed or open? If it's closed, there is no problem. You need to test it with the Memory Saver opened. If it works well, it might be a bug of the browser.

oh, It's my mistake. the Memory Saver is opened,and it works well. maybe it is a bug of the browser. Thx.

**Comment by wangf1978** [comment]
This issue come back in the latest edge(Version 125.0.2535.51 (Official build) (64-bit)) with default setting
