### ISSUE TITLE
[Bug] The example section on the Echarts official website cannot be directly edited

### ISSUE THREAD

**Issue by 1212wuhu** [apache/echarts#19264]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=area-basic

### Steps to Reproduce

After opening the example, you cannot directly edit the code on the left, but you can run it

### Current Behavior

Try modifying the code directly on the webpage

### Expected Behavior

Ability to modify code directly on web pages

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by 1212wuhu** [comment]
![image](https://github.com/apache/echarts/assets/84019418/d06ec35c-21af-4149-8e30-f1b4ffae407f)

**Comment by 1212wuhu** [comment]
Just like the screenshot above, my cursor stays on the second line and I am unable to edit this code

**Comment by plainheart** [comment]
Do you mean the editor doesn't automatically focus when it's ready? Currently, you need to click the editor once if you hope to edit something.

**Comment by 1212wuhu** [comment]
> 你的意思是编辑器在准备好后不会自动对焦吗？目前，如果您希望编辑某些内容，则需要单击编辑器一次。

I have tried clicking on the code editing area many times, but there has been no response, and I cannot even select the sample code

**Comment by 1212wuhu** [comment]
> 你的意思是编辑器在准备好后不会自动对焦吗？目前，如果您希望编辑某些内容，则需要单击编辑器一次。

![image](https://github.com/apache/echarts/assets/84019418/7a59980a-7455-4f14-b57c-17c40d0a7361)
In the TS code editing area, I can select the code, but I cannot edit them. In the JS code editing area, I cannot even select the code

**Comment by plainheart** [comment]
I can't reproduce it. Is there any error in the Console?

**Comment by 1212wuhu** [comment]
> I can't reproduce it. Is there any error in the Console?

![image](https://github.com/apache/echarts/assets/84019418/b72de767-f631-4248-aa4f-ab80dbe69e39)
just like this

**Comment by 1212wuhu** [comment]
![image](https://github.com/apache/echarts/assets/84019418/de4b9967-ac7d-40a4-a48e-96d43ce9b45f)
Slow network?

**Comment by plainheart** [comment]
在打开控制台的情况下，再次刷新这个页面观察下有哪些报错信息或者资源错误。另外这是什么浏览器？

**Comment by 1212wuhu** [comment]
> 在打开控制台的情况下，再次刷新这个页面观察下有哪些报错信息或者资源错误。另外这是什么浏览器？也可以试着换个浏览器看看是否也一样问题。

好吧，这是浏览器的问题。我尝试了使用谷歌浏览器。页面恢复正常。出现问题的浏览器是Microsoft Edge
版本 118.0.2088.76 (正式版本) (64 位)

**Comment by 1212wuhu** [comment]
> 在打开控制台的情况下，再次刷新这个页面观察下有哪些报错信息或者资源错误。另外这是什么浏览器？也可以试着换个浏览器看看是否也一样问题。

这是最新的微软浏览器版本

**Comment by plainheart** [comment]
好的，可能兼容性问题，后面我抽空测试一下。
