### ISSUE TITLE
How to show custom image inside bar chart tooltip?

### ISSUE THREAD

**Issue by KaustubhDTawate** [apache/echarts#19273]
### What problem does this feature solve?

-

### What does the proposed API look like?

-

**Comment by helgasoft** [comment]
_tooltip.formatter_ accepts HTML - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsBGBDAxgawHMAnYAV2gBMBhYAG2CIC5lYIBbLAgU2YHIALMGBABnRgHpxXHPyxEwIgHRYQufl0UMCU6OPacuI8fQLBFIaAV4AaWES4guWMH2jAAtPcfObsULggwAE9GAAZFACZYAF9rNFgADwBBBIgxZHj0CmcsZgBtXgBZGF9eABVSLlKAdS4KUrL-UlKAMSIIUoBlH1teTvJeAF142PiglLTmJFH0ES52w3zMjPRV2GywXNg8gA4I0NsATgBmCKPQgEYj44AWWwuIw4PYC-Pj59f9wbi19GDHPgiHDOMDzGzLWZBNgYOh8VRgfgScSFC4AVkUNwiZwuO0UD0OtHc6IiADYbu4IooAOwknaE4kk1HWSk0ukXRShUIkomKHYk44AGXZZOsuIuFxutHROx2VPc4R2qNRsFolP5ER5b0lare1nRWqlvMV1gVSsJN0iqJ21gtaIiQvRmOxYseAC9wb9YCIoTDaJ0IK6eLBUaFltF4t94mBgHRICApssAGYMDhCebMAAUIAAlAgAHwsCF2LhgUhEOAAIgAPOwCF6iDh4AIhKIkdJZPIlCo1BotDo9BxuEYTGYLFZYAB3CAUBHwcUXWDiAsV2AAalgIEU0CwbC4AG4ZqsAPrJoip0FMWDV2v1xvN4RiSTtuQKZSqGS9ojaLi6fRD4zAKY5iWLwk7TrO86LnmFYjCg0R7kAA)

**Comment by KaustubhDTawate** [comment]
Thanks for the previous response. Actually i have to render image inside tooltip for react native application so what is the approach?

**Comment by helgasoft** [comment]
Maybe others may answer better for react native, I'm not familiar.
But if the issue is about **remote vs local** (or embedded) images then one could use SVG :
```tooltip: { formatter: `<svg width="100px" height="100px"><path d="M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z" /></svg>` }```

**Comment by KaustubhDTawate** [comment]
I am currently using ECharts for a React Native app.  I need to render a custom tooltip that includes both images and text with various colors and styles. Is it possible to create a custom tooltip in ECharts for React Native?

Additionally, I have attached a demo image for reference.


![TooltipImage](https://github.com/apache/echarts/assets/85387357/b7a71e07-1e16-4b45-a659-dc6ad1825e3c)

**Comment by AleeFarook** [comment]
How the hell I can add image in tooltip in react native ehart in line chat ?

I am fucked here

**Comment by AleeFarook** [comment]
> Thanks for the previous response. Actually i have to render image inside tooltip for react native application so what is the approach?

I am facing this same issue ?
