### ISSUE TITLE
Dynamic "borderRadius" Application for Top Series in Stacked Bar Charts

### ISSUE THREAD

**Issue by BenJackGill** [apache/echarts#19275]
### What problem does this feature solve?

The current `borderRadius` setting for a stacked bar charts does not allow us to put a border radius on the top stacked series, whatever series that may be.

It only allows us to put a `borderRadius` on one particular series. But sometimes that series will have no value and will not be displayed. During these times the top stacked series will not be rounded.

Therefore we need a method of using `borderRadius` on the top stacked series, whatever series that may be at the time.

**Example:**

In the image below the stacked bars on the left have a green `2012` which is currently the top stack and correctly rounded using `borderRadius`.

But the right stacked bars do not have a value for `2012` because it is `undefined` for that country. So the top series in that case is actually `2011` which does not get the `borderRadius` applied.

<img width="771" alt="Screenshot 2023-11-07 at 2 21 21 pm" src="https://github.com/apache/echarts/assets/2043257/43f332f8-4860-447e-beac-ed786b4008a4">

**Here is [live demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQQIZhsDOWYTV6AhAC2-LlGhcSAbQDkAY2ABXaGABOAT1nlYsgEwAGAIx7tuw0aOyAupXTouytfKwyB9pLEUr1GkrIAhNTYALwgMMwsjEgB2Ax0LPRIAZgNYFnsPL2VVTX8ASUIYLHE2SONo2CMDeNhEkhUCLAAzCGgsAnT3ayoM2AAPAEF-iClkag0QV115DlxgTVl0u1gNYdGmPp41CBK3TNRM9Gg2UX8o7Xd0MEnp2QAjNjVLo9guTnkAa38NLCeuF5HfCKJr8V7ofr-by5LQrV5-cwVWRXLqZProQ5HE5nREmQGZG5TfyPZ5w-zvNhfH5_NQAsnoYHAUHIFEQqE5Xz4o4I_TGUwo9H2CBgLDCADKN2wTFg9wWTTUACU2EIlGNpKkdBrYLUDNZUfZSFQeqQANxAA).**

**Here is the above illustrated with code:**

```JavaScript
option = {
  legend: {},
  tooltip: {},
  dataset: {
    dimensions: ['country', '2012', '2011'],
    source: [
      { country: 'Brazil', 2011: 70, 2012: 30 },
      { country: 'Indonesia', 2011: 100, 2012: undefined }
    ]
  },
  xAxis: { type: 'category' },
  yAxis: {},
  series: [
    {
      name: '2011',
      type: 'bar',
      stack: 'years',
      encode: {
        x: 'country',
        y: '2011'
      }
    },
    {
      name: '2012',
      type: 'bar',
      stack: 'years',
      encode: {
        x: 'country',
        y: '2012'
      },
      itemStyle: {
        borderRadius: [30, 30, 0, 0],
      },
    }
  ]
};
```

  [1]: https://echarts.apache.org/en/index.html
  [2]: https://echarts.apache.org/en/option.html#series-bar
  [3]: https://i.stack.imgur.com/KAgRh.png

### What does the proposed API look like?

I'm not sure how the API should work to fix this problem.

I think the easiest way is to allow `borderRadius` to take a call back function. Params of the call back function should contain details about the current series so we can rely on that to code our own solution.

**Comment by helgasoft** [comment]
If data is "stacked"(added) in advance, we could use ```barGap:'-100%'``` to get the desired effect -  [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAB4CC1EAziUuugQIZgckDaA5ACEAThwBeEDP3Kx-ASUIwsjCB2myAqgGVa_ALqwKVAJ70mLI-kZZhEZXyrpUbNtA4BbLCX4AmAAwAjAHqAEYcwgDiHCDeALQBfn4ApNKObGDGIF6yYcLqaexcPLC8AQAc_gDMMj6VACxlAJw1jX71epQu6BBgWO5aGdgssCHAwgQ2AEocBBAArswlCTLLsH4yfgaWXdtOBbBunt7-AT6pXbAZWd65-egA9PeF3HzlVbAA1AGNlT4ArDV6k1PrU6pUyi02nVPpUEokOvtOC8lhU2p9vr8ARcLutYD5WvUYXDNp0uj0-gNjENkCMxhNhNNZgtXrjVrjNoZSehSFQ9ChSABuIA)
![image](https://github.com/apache/echarts/assets/13038071/c0b0ab7d-f6e7-4a65-b5a2-67ad1bd4f013)

**Comment by BenJackGill** [comment]
Thanks for the suggestion, but there are some problems with this solution:

1. This is rounding all series, not just the top series.
2. These bars are not stacked, they are layered. So in this case we have to add the values of all other series that are layered on top to get the correct effect. This extra data manipulation could be avoided if we had a new feature that directly addressed the issue.

I'll probably use this workaround because it's the only workable solution I've seen but I still think the problem needs to be fixed.

P.S. In your example I could not see the stacked bars unless I hover over the "2011" legend. I fixed that [here](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAB4CC1EAziUrAQIZjskDaA5ACEATuwBeEDH3Kw-ASUIwsjCOykyAqgGVafALqwKVAJ70mLQ-kZYhEJbyrpU6Z7GjsAtlhJ8ATAAYARh8pB2cwIxAvGQAjdiEQl3QOLl4AgA5_AGZpAIBOTJ8AVmkfXL9MgBZdSkTYCDAsd01w7BZYaOAhAmsAJXYCCABXZlgeAL8cidgpv31SUItnJ0S3T29_AICExPDI71j4msSDgHF2EG8AWnG_AFJtl2TuUYA2LJzMguLYPPKqo5c9UazSMrWQ7U63SEfQGw1SU3G0hmcwWAOQoXQqyivkCfgeYQi2IO-PQp3OVxu9zRSU4zx4FXesDSXxyWX-GLqDSaLSirA6XV6_SGIzGCJmSJRLnm6F0KFIAG4gA) by layering in the correct order.

**Comment by helgasoft** [comment]
see also #18080 for another workaround option

**Comment by BenJackGill** [comment]
I'm not sure what is the new solution there? I think the proposed solution uses your `barGap:'-100%'` idea.

**Comment by BenJackGill** [comment]
Another drawback I discovered for the `barGap:'-100%` workaround is that you must know which series will be lowest / highest before you arrange the order of the series. This is because the lowest must at the front. Unfortunately, this makes it unworkable for me because I cannot know that ahead of time.

In [this example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQQIZhsDOWYTV6AhAC2-LlGhcSAbQDkAY2ABXaGABOAT1nlYsgEwAGAIx7tuw0aNn9xg7IC6ldOi7K18rDIHOksRSvUNElkAITU2AC8IDDMLIxIAVgMdCz0SAGYDWBZnHz9lVU1ggElCGCxxNljjeNgADmTYVJIVAiwAMwhoLAJs73sqHNgADwBBYYgpZGoNEE9deQ5cYE1ZbKdYDXHJpiGeNQgKr1zUXPRoNlFguO1vdDBZ-dkAIzY1W7PYfEU2_k_0YbBfyFLQbT5Bcw1WR3dYwiBgLDCADKD2wf3-zxWbTUACU2EIlFNpJkdCTYI0DANPqRvEN0KczhcrpCTB8zg85sFXu8wc5uQBxNiMXQAWiMBgMAFI2blvsBfsgYQCgQVAjKzhCbKyYXTnPDESiNGjFf9YJi1Ni8QSiWSyRSqWcabkhgNSABuIA) it works because `2012` is the lowest value.

But in [this example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQQIZhsDOWYTV6AhAC2-LlGhcSAbQDkAY2ABXaGABOAT1nlYsgEwAGAIx7tuw0aOyAupXTouytfKwyB9pLEUr1GkrIAhNTYALwgMMwsjEgBmAx0LPRIAVgNYFnsPL2VVTX8ASUIYLHE2SONo2AAOeNhEkhUCLAAzCGgsAnT3ayoM2AAPAEF-iClkag0QV115DlxgTVl0u1gNYdGmPp41CBK3TNRM9Gg2UX8o7Xd0MEnp2QAjNjVLo9h8RSb-V_R-_29crQrV5-cwVWRXZYQiBgLDCADKN2wX2-9wWTTUACU2EIlGNpHEdATYLUDD1XqR3H10IcjiczqCTC8jjcpv5Hs8gfZ2QBxNiMXQAWiMBgMAFImZl3sBPsgIT8_jlfBKjiD9MZTBCqfZobCERokbLvrBUWp0VicXiiUSSWSjhTMn0eqQANxAA) it does not work because I made `2012` the highest value and now the `2011` series is hidden behind `2012`.

**Comment by Ovilia** [comment]
I'm going to support a new feature `stackBorderRadius` so that you don't need to hack on this.

**Comment by BenJackGill** [comment]
Amazing! I think there are other people who want all series rounded as [seen here](https://github.com/apache/echarts/issues/18080). So maybe supporting both types would be good. Only top series rounded, and also all series around without any white gaps.

**Comment by Ovilia** [comment]
I tried to make this a new feature but it seems unnatural to support this in the current pipeline. So I made [this demo](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=G4QwTgBAzgpmCWMoQLwQNoCgI4gb21yIBMQAXEALgwEYAmABgBoJHmIaBWdgDnYHZ2NGkIDMDALpNCRHGQCeABxjUA5ACNwq6bNxQKAYwDWakKpkQAvjtwFdpCtXQiWAFgBsLd65aqAtNoQ7P6BkjZECspqmmDaFjj6IMam5kTWFnayDlQY4r4BLOyMLC4QIYVS8RCRKmUxcbqJyWVmFulEmfbkOeh5ZQVBLMUcwQNhVXJKtRpa4bJNJnWpuO22ExDZTqXDXOyjgdwl47qTUXWz6wvRyzjpEgDcmJgGAPYAdvrQhkYAkm8AZi9UPhLI9AZAABQAGxgZAg8GBDHu8IgAB5oHBEFB0JIAHTZXEwt4AczIAAtkQBqSnwACU-EI4Ig0NhEAAVojkRz0bAEEhCTASeSqZS2fTOhBXh84QsAHIgAC2MGBvKx6DZElxC0eRHg_2ZAEI5YqYOKqlKyPA3gBXGA6lYWPWGhZ_QHoY1KiRmxrfV0vd3feWe4ESogLADKFDAZCclROXySRgAom9iLGqqC2hYpZ8rYCVb6Af6PTAHtn3p9sirMUh1Zrsuh4GXdfqIVWAGTtjbdCAGlBoELe2ROiF5l5a76R8BkRsSVBoG1QqFD3RjieJqfR2fAtn2tJVNcLFPEbdoXdZ26YSyYJksuEItBIlE8mtQAVCikQal0hk4HNwqs0FVWsm3xbp7X_eEiwLRM_XdV9Z3XYxmwgW8YThDlHy5NEMT5bFQIJIlSU_akxV_XBIPgKBNzhNBD0nKMZw1ec6L3SUK3vKBj2BejE2POsWPhNjILIF5FAAIReMBiDgHiuNTCAAH4RggagkQsAB6DSIB-fV5Bea0NneVQ4QAdxAN44XUKSZLAAAlEBiHga1kHICBrLIUSFRYNkXJlVl4DhUT3OVBhy2ldyXk8l4FUk6TZLo6jGKU1hVKCNiG2YtBQwgUAoVtahMrjYcyBgBVI3kGFqBynBrPi-zHOcqAnFEiSbLgFhWri2yWA8rzuo6yLoti9qwAkDMLysK8njEy13hDQgAA8AEFFqo6qLBqNQDHIGBiSk-QGlwTYMFUABZYzfAAFVtQJVAAdRgYg7quslrTugAxBA7vDcgfutN5VHG24bHkVb1vI05pjy27CFWYCoCve4gA) for you, which can dynamically deal with all situations with stack.

**Comment by BenJackGill** [comment]
@Ovilia thank you so much for this.

I have been playing around with it for the last few days trying to get it working on my project. But I am having a lot of trouble with the chart legend. If a chart legend is added and some of the stacks are removed by clicking on the legend icons then sometimes the top stack is not rounded.

I tried to fix it by using various events (`legendselectchanged`, `finished`, `rendered`, etc) but I am not as skilled as you with eCharts.

Could you help me figure this out?

Here is your example with an [added chart legend](https://echarts.apache.org/examples/en/editor.html?c=bar-stack-borderRadius&code=G4QwTgBAzgpmCWMoQLwQNoCgIQN7ZwgBMQAXEALgwEYAmABgBoIGmJqBWNgDjYHY21aoIDM9ALqMCOUgE8ADjCoByAEbhlUwtHIBjANYqQm6RAB2IALZKIy4wQC-WvKZLkq6YcwAsANma-3szKALSaEGyh4RLOMgo2ahqxOiAGRibaFtYqqsqOzvjabpQYYsFhzGwMzF62FRGSpnKKOUmmUHqGtsbJWQm6eThOBIWExR5lddHM1eyR9TFN8a1gGYQdqV1qazh9KkSDEMM4ozjjNFWCXJXl4ddzjdrNCeqryRtptrm9Vgkwhw5MOIANyYXQAezMHRSBgAkmYAGbg1B4BygpGQAAUABsYKQIPAUfRgQSIAAeaBwRBQdASAB0xTpuLMAHNSAALEkAai58AAlC4cBiIDi8RAAFZEkmSimwBBIJkwVkc7lc8UC04QCFQ_EffQAOV-KLl1PQ4vEdL1oO08ARIoAhHrDdYNaYcNrSPAzABXGDWwiAm12zGOzrwpHoJ2_cSu7Q4PXh8GRzrOmDiFGa7R6gDK5DApA8jzj8c6AFEzERC26jv6hqZtdCvUjjWHEUmo9YQfXIdDisaqUgzRbiuh4F2gyK-wAyKfEMggCD2lBoKKxuO2kVN8GWzq58CkUfp5fmb3Y7Fr4tbnebPf5w8o8W1gPVq968tEe9oR-mQNHTCA4VRXxQk0GJUlZQHKBFWVTkIB5flBS1Ht8T7NATUHMcGXnf0G2AtsW02RNI0gw9rwMccIEA3F8UlUDpXJSl5RpTDGWZNlYJ5dVEJwAB6HikJ1AkoFvfE0FfXc8wPc1UGPeAn1woT3xRcTNnfIcZLE-TkIgUhwXkAAhcEwCIOBlKgJSAH4WHoCAqGJbtBNUcFSF0yxDOM0y6Nced1LQTMIFAbFfSoEdzWSHB4FIGBLFzWRcSofycCcjywAAJRAIh4G9KAPF0gyjJMsBmDy9zCuYJyXPBNyCrgcrnNc0q4HEatfyGf1AUBPTPUhDMCFxFklUrbjoHZcEAHcqFIMBfXyAgAA8AEE5vgHLhueFRdDIGAWSM2QdjndwMGUABZSFwmUAAVX1zoAdRgA5ggu9lvXOgAxBBzuzMhPu9MxlGaoZnFkJaVoSpYWlsQLrtm-NIKodCoH_YEgA&lang=ts). When you click the legend "b" icon you will see some of the stacks are not rounded.

**Comment by daidr** [comment]
I think it is really not elegant to implement rounded corners by traversing the dataset every time the legend changes, and there are edge cases:

Imagine if I set the border radius to 10px, but the height of the topmost bar in the stacked chart is not enough 10px, then this solution's rendering result is problematic: [demo](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=G4QwTgBAzgpmCWMoQLwQNoCgIQN7ZwgBMQAXEALgwEYAmABgBoIGmJqBWNgDjYHY21aoIDM9ALqMCOUgE8ADjCoByAEbhlUwtHIBjANYqQyggF8teacTKUabWs2rNlAWk0Q2r9xIsyFSiDUNXx0QAyMTHHMCfG0Scip0MWc3ZntBT1SPSSs5RRV1ME0rKD1DQOMzC1jCeNt0J0Cs9MdM7xztPICgopDSsPK1SIhonBqcOsThZgZHLjSU93n2H1z_AuCSsoLh00xxAG5MTF0AewA7UtCDAElzgDNT1DxTI8fIAAoAGxhSCHhnvQDv8IAAeaBwRBQdASAB0dVhP3OAHNSAALYEAakx8AAlJYcO8IN9fhAAFaA4EU8GwBBIREwFHorGYsn48YQM6XP79AwAORAAFsYM9aVD0GTxLDefojtp4PdiQBCGUC4Xsqw4LmkeDnACuMDlhD28sVHxVZTuj3QqqFMHEGu0OBlVtONrKavtzw52hlAGVyGBSIkOk7nWUAKLnIghzUjI1RKxcq66x6iy0PN224WHJMXK51UWQpASqV1dDwXOm4mFgBktes5AgSpQaC8jqdCuJqdO0rKAfApAr4lQaH1Xy-HbDPb7AwHQeHzzJCeNcZnMqjREXaGXVhNI0weyJJL-ALQQJBNOLUAZTIxEGxeIJnPzf0LaDFJcr8JsRuTp8zdMBldG1r2HWcDCrCBjx-P4KXPKkwQhOloW_BEkVRe9sTZZ8tVff4oHnP40HXftAyHSVRxIld_wIzdnlIgZN1LKj_ho_DSFOeQACFTjAIg4AYqB6IAfhYegICoIErAAehkiAbkVWRTj1YgLmUP4AHcQHOP5VD4gSwAAJRAIh4D1ZAyAgfTSE4wVmDJCyeVJeA_k46yRXoPNuWs05bNOQVeP4wSSMI8iIDEhhJI8Fdy0otAfQgUAvgNKg4tDeVSBgQUA1kH4qESnB9OC4zTPMqBEk4niDLgZgqqCwzmBsuyGtq3z_MCmqwHEON9yiI09j2TAuJ1C5vQIAAPABBCb4Aq3CIC6FRdDIGBkT42RijiGxEmUABZdTnAAFQNdxlAAdRgIgzqOtE9TOgAxBAzr9MgXr1c5lB6qILFkGa5oKtZ8kCZLTqqAhPygQ8DiAA).

<img width="1401" height="1019" alt="Image" src="https://github.com/user-attachments/assets/28d7ecba-39ac-4b61-a53d-f2d2732da1bf" />

I wonder if it's possible to crop out the correct border radius in a way similar to a mask?

However, considering that the labels are attached to the bars, this might affect the rendering of the labels.

**Comment by joaoviana** [comment]
+1 to having a `stackBorderRadius` 🙏 
The demo solution follows the `data` array approach, but what if I just want to use `series` + `encode`? It would be great to have a _native_ solution
