### ISSUE TITLE
[Bug] Visual map for line chart does not work on dimensions higher than 1

### ISSUE THREAD

**Issue by jpfeuffer** [apache/echarts#19270]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AG4CGANgK5W0A0JAvt-uRz4iqUmUo1YDFu1q9-sPFQBOEKoVgBtEulFjYAE0ZhGRTZoCMAVgAMnC_YC6nLdav2nLy1YAcnAEwBzq4AbHaB_o7OOqQU1HTMENAcMTwk0ej0-KwsALKMIGYxevqKKmp4AJLQBlQYRHYxYgYQALZU0HhQ0ESBTaQgagDG6kWlpUiwrUkNLq2M9bAWAHQOsEPAzMDKdABGbBywfP0TUzNLq3MLvS4bWztSylQGtEcK46ST0z2w_pdT11gAGZbpttnQAOZPDqvY4fDKkOGwaI8ADcQA

### Steps to Reproduce

see example. super simple.

switch dimension to 1 to see how it should look like, since dimension 1 and 2 are actually the same.

### Current Behavior

Does not color the lines

### Expected Behavior

switch dimension to 1 to see how it should look like, since dimension 1 and 2 are actually the same.

### Environment

```markdown
All
```

### Any additional comments?

```
option = {
  xAxis: {
    type: 'value',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [[150,1,1], [155,1,1], [158,2,2], [160,2,2]],
      type: 'line'
    }
  ],
  visualMap: [
    {
        seriesIndex: 0,
        dimension: 2,
        pieces: [
            { min: 0, max: 1.1, color: 'blue' },
            { min: 1.1, max: 2, color: 'red' },
            { min: 2.1, max: 3, color: 'green' },
        ],
    },
  ],
};
```

**Comment by jpfeuffer** [comment]
Similar issues with no answers:
https://github.com/apache/echarts/issues/18629
https://github.com/apache/echarts/issues/11667

**Comment by frab90** [comment]
any idea why this happens? have you already done any investigation?

**Comment by Ovilia** [comment]
After cheching [the source code](https://github.com/apache/echarts/blob/75dd430d77e8949d56f2129f05018fe8629e5b2d/src/chart/line/LineView.ts#L280-L295), I think this is by-design instead of being a bug.

For line series, the data dimensions are not arbitory, but instead, the first dimension means X and the second Y. So if visualMap takes a dimension other than X and Y, it makes to sense whether to map the color of line vertically or horizontally. Thus, only the first and seconds dimension should be allowed for visualMap.

**Comment by jpfeuffer** [comment]
Could we convert this into a feature request instead? Or is there a workaround on how to color different line segments of a series differently? Independently of their x/y dimensions.

**Comment by helgasoft** [comment]
> is there a workaround on how to color different line segments of a series differently? Independently of their x/y dimensions.

yes, custom lines - [Demo](https://echarts.apache.org/examples/en/editor.html?code=PTAEGMHsDsBcCcCWAjArrRNTIJ6gBYCmANgOYCGAzpAGawB0UAtgFAAm5s5oAvKANotQAgOQ4RAGhEAPSSIBu5YqkIiAuhKECAjBNAiATAAYDBgLRGA7BYCsk0EfoGNW_gGY9hk-aMAOM9oAbPaOAJwuwvwGnsamFqEBwXqONhEC0fqx5tpGiSH0gWn8RjHeAdoW2vaWaqAgoMRUsKAADpCIcHpQxJDwoIik0L2EbCxqANwsNKjQ4BhYxB2EAEqE0GyE8AAULeTw5EyUeuQtiACUoADeWltQvWzavKAniIyQ91uCwsIv9IrKhC2ulaewOlHoHC4AEl1oRpDDKIgNmdNN9nqc_koVFsSiD9ocIZxyDCNvDoIjkVo1GcUVphLd3vA2AYnr87kzPnTvr9_tjgbt8eDIcTYWSKYRQABqUDaWlon4Y3mA3ECsGE6GihFIiXS2Vc6lnSbCeCEWCoeDQK5c2A4FqEABc-kW0FUqO-lHwJwdVvloGk2kd7IexTSaJwAYgjOD2lD32kBkDUYMIbdYYTkfuyZjXIAvqnQJQbcRvddfc7CAB1JGwfCO7TRLnCQvwSAAa29v0LOGLWzO9BoiGIxDqYBoLaYoHkiEoqCUAFkTrn87A4bAAMIwFdwR2XUCNgtFkt733CFfSWCOnlYwEGFHHk8Ad2rtdAxnzaIHQ_tImQjXArckfdhBoTdHRERAuEWcBsEgYgNj6IIWmkCBzUReRVH3HMl2tVcN2gAdSB3VpIEReZoDAjpxREUA8y0HNJiwyAWjIp5S1ADBYGLIiZ2QM8L30bpemwPApxnecTlANhECYNZERgAA-KoaLdHAAEFpGnIibTtMClWo2jhGkdTNKudjbW9EQMBk-xKHAJRvQQFRlK0WB3mIDAWh3AzJKJShTUdfhLmoc1wAdYUczSPykEISgAq5Ni0W0izwFQQtICYQDfTWKANiI6Q6z0HBHSMZzfRNWF4ChFcmEdctVgq_MsOENJRNnYgF08n13XwSAH0dRzCHzOziBSxpfwc-AVHzKSZPJTByNffMmA6Yq9CYch8plfMOmWchoFIEt90E-AApEUgTTWewxBIHoHyuk02HUXM6JYeigA)
![image](https://github.com/apache/echarts/assets/13038071/606eb707-638b-42e7-8440-5cab3903ee6e)
