### ISSUE TITLE
[Bug] : Bar Chart: legend.selectMode = false is not working

### ISSUE THREAD

**Issue by SonaliPI** [apache/echarts#19271]
### Version

5.2

### Link to Minimal Reproduction

https://echarts.apache.org/

### Steps to Reproduce

legend.selectMode = false is not applying.

### Current Behavior

legend.selectMode = false is not applying.

### Expected Behavior

legend.selectMode = false Should apply

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
You should specify in more detail what you expect to happen or add an example.

I think it is working as expected. See [this example](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkA9FNgBVNtVh82GYGUo1SanHh4kwATxDUGbABaMAJsADu9WDNj0L1uw8aqr1AGaMArrgA3LAAxoxwjNhs6gBGSvTYwtQOwNouljb2-gC-xDnc6NjUNNBW4orFoaJWALLA3oR-0dQFxBTk5USSxT5gDADMAKRc-uQU5v3OACwjhSSxwGCYALaDc_qhMGCMwgAyjPHYhGCk_tT588wAgqxs4vpGJgwAblHn9JfEhrfsD5JPUzOcKiChpQyjSRWRg7QgAbXo9WgXGcABUPpxnAB1ahWFH0VHmfz4gBi5HxAGUYZT_MiALpfdCKcjUe6wOH6CSSWDQRgrIH0AAiEFI1GqkO5gIYsUYpAlkjYO1CAGsGJgdth5SRsIdqMdutymeY7CczhdDW1DdQViBLGw_gbDT5gKF_GyXLQIKzPhb5lCYYx4QMAEwABkxA1DwYjoYAjBGBtMIwBOcOwAaRiNhhmSS0kLmSXn8hi1XbYWDXPF-gzGAUyuXVplK1XOdVRLVFXX6gvciwmsjnfToPOSa22zwOnuSZ2u93Mr0cIewEckaGw9mxsOY2Mh7dx7eJzGpzHBzOwYOx0M5kgrqc8vkC64-HwQJIwpSVjsYWvS2VfxWMCqapLO2jawDqRz_IasB9rYpqDr6S5jnak5LugM5umYnrekuK7oGugbssGW6wLGAAc0akcm8bnoe57HumZ4DJe17DtWd5FgKABqEDeOon5gVKzj1v-zbARqX4QXqUGGrB8HmtyeGwMhE5sne6EuphzjzjhiGGgR8KxgArGmF6UWGNHGUmVFphmabTCxuTsUunEMBS1CyqE5iwAAotAFDJF-Qn0CJYEAUBrYgZqYFSd2aEwcacEDgpuZgSp9pqfFGFzthi56dyBnshRaZkbusCpjRyZ0ZuDE7meO7ZrkxAMjkQRAA).

**Comment by helgasoft** [comment]
Please make an effort to create **Minimal Reproduction code**.
```legend.selectMode: false``` works - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEksByTxUjVQrFF-ZFhoRgBbGlpGXiDBYTEARgAmAAYeWFS02ASAViyADiyAdiyEhNKAZhTrR1J0Cmo6ACNGDloguxIakgAbNipoATcg7z76FgEpARpYADNGHu97PjsAbiA)

**Comment by plainheart** [comment]
Please notice the option is `selectedMode` instead of `selectMode`.
