### ISSUE TITLE
[Bug] 自定义symbol时引入透明空心圆的svg，如何设置线的端点不出现在icon中心位置

### ISSUE THREAD

**Issue by YingML** [apache/echarts#19277]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/YingML/pen/MWLJyoe

### Steps to Reproduce

option = {
    "yAxis": {
        "type": "category",
        "show": false
    },
    "xAxis": {
        "type": "value",
        "min": 1699093341108,
        "max": 1699266141108,
        "show": false
    },
    "grid": {
        "left": "3%",
        "top": 0,
        "bottom": 0,
        "right": "3%"
    },
    "tooltip": {
        "className": "tooltip-container",
        "trigger": "item",
        "appendToBody": false,
        "enterable": true
    },
    "series": [
        {
            "data": [
                [
                    1699169199280,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Ok",
                    "",
                    ""
                ],
                [
                    1699186331024,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Ok",
                    "",
                    ""
                ],
                [
                    1699216311576,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Critical",
                    "",
                    ""
                ],
                [
                    1699220594512,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Ok",
                    "",
                    ""
                ],
                [
                    1699229160384,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Critical",
                    "",
                    ""
                ],
                [
                    1699233443320,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Ok",
                    "",
                    ""
                ],
                [
                    1699237726256,
                    "PaaS告警,hedan-prod-rke/DaemonSet/nfs-csi/csi-nfs-node,",
                    "Critical",
                    "",
                    ""
                ]
            ],
            "type": "line",
            "symbol": "path://m16,8a8,8 0 1 1 -16,0a8,8 0 0 1 16,0zm-3.97,-3.03a0.75,0.75 0 0 0 -1.08,0.022l-3.473,4.425l-2.093,-2.094a0.75,0.75 0 0 0 -1.06,1.06l2.646,2.647a0.75,0.75 0 0 0 1.079,-0.02l3.992,-4.99a0.75,0.75 0 0 0 -0.01,-1.05l-0.001,0z",
            "symbolSize": 15,
            "lineStyle": {
                "width": 5,
                "join": "miter",
                "miterLimit": 1,
            },
            "emphasis": {
                "focus": "series",
                "lineStyle": {
                    "width": 3,
                    "shadowBlur": 5,
                    "shadowColor": "rgba(238,238,238,1)"
                }
            }
        }
    ],
    "visualMap": [
        {
            "seriesIndex": 0,
            "type": "piecewise",
            "show": false,
            "dimension": 0,
            "pieces": [
                {
                    "min": 0,
                    "max": 1699186331024,
                    "color": "hsl(84,53%,46%)"
                },
                {
                    "min": 1699216311575,
                    "max": 1699220594511,
                    "color": "hsl(0,100%,60%)"
                },
                {
                    "min": 1699220594511,
                    "max": 1699220594512,
                    "color": "hsl(84,53%,46%)"
                },
                {
                    "min": 1699229160383,
                    "max": 1699233443319,
                    "color": "hsl(0,100%,60%)"
                },
                {
                    "min": 1699233443319,
                    "max": 1699233443320,
                    "color": "hsl(84,53%,46%)"
                },
                {
                    "min": 1699237726255,
                    "max": 1699237726256,
                    "color": "hsl(0,100%,60%)"
                }
            ]
        }
    ]
};

### Current Behavior

自定义symbol时引入透明svg文件，如何设置线的端点不出现在icon中心位置？

正常引用'emptycircle'不会出现线段展示在icon中心位置的问题。自定义的话不行，能否支持symbol设置多个path，并设置某一个path的颜色固定为白色？ 或 能否支持设置线的端点不出现在icon中心位置？

### Expected Behavior

 1、可以设置线的端点不出现在icon中心位置
 或
 2、symbol设置多个path，设置某一个path的颜色固定为白色

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
consider using a **non-transparent** SVG symbol/path to avoid seeing line-ends through it.
Example:
```symbol: 'path://M15.422,18.129l-5.264-2.768l-5.265,2.768l1.006-5.863L1.64,8.114l5.887-0.855 l2.632-5.334l2.633,5.334l5.885,0.855l-4.258,4.152L15.422,18.129z'```
