### ISSUE TITLE
[Bug] 移动端 在点击饼图扇区的外围部分也会触发扇区的高亮

### ISSUE THREAD

**Issue by emotionl** [apache/echarts#19286]
### Version

5.3.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWzQCGAtlsQOQCCAxuwRrAGI7B6zADRUKYAJ4gmsZiHwix6HLQAmEAK5FSzACwAGAKQjZAdiPMAuqOrpaAN2ARVAGVoAjLABsA8vdxetCDEAGa0Xtg2toGeXsSothQYABbAAO6h4ZFKsAC-UdRY9CDJtBgQ2gmJmOzhTGERWDn5OTHeLhDQMlWJKemZjc0FFKq0YLTEZNXIsPbhGjIAjPq6ABzCNAwyzADKWLQ47MmwAKLQAOadWMx5w9RIs_MypgDMAKwbdIwsACIQOFh2GAbi1pg85l4FsQ3qt9J8tiwTvRaBAvCC7hRwU9iGtdPDvrIAKrQKBwViqDDonLoLGQmQvfRwzYE5gANWcWGAsHJlLyOUsYly5AFuQA3EA

### Steps to Reproduce

点击扇区的外围部分触发扇区高亮
<img width="373" alt="image" src="https://github.com/apache/echarts/assets/17172758/7992cf06-6dc7-4bc6-ba43-541fdfcd409d">

### Current Behavior

在点击饼图扇区的外围部分也会触发扇区的高亮

### Expected Behavior

- 在点击饼图扇区的外围部分不会触发扇区的高亮
- 只在点击扇区本身在触发扇区的高亮

### Environment

```markdown
- OS: macOS Monterey
- Browser: 119.0.6045.105（正式版本） (x86_64)
- Framework: N/A
```

**Comment by plainheart** [comment]
可能是因为 ECharts 默认在移动端开启了[智能指针吸附](https://echarts.apache.org/handbook/zh/how-to/interaction/coarse-pointer/)，指针相应区域会稍有变大，以便于使用者点击。如果不希望这样，可以在 [`init`](https://echarts.apache.org/api.html#echarts.init)初始化图表时显式设置 `useCoarsePointer` 为 `false`。

**Comment by emotionl** [comment]
Thank you @plainheart ～
