### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eric8180** [apache/echarts#19285]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/eric8180/pen/RwvVgYm

### Steps to Reproduce

点开上面的网址就可以看到问题了

### Current Behavior

如图所示 旭日图六点钟方向 显示的数据 与其他的数据不一致，position都是outside，但是这一个显示异常。目测数据为11条和17条时这个问题是必现的

### Expected Behavior

数据显示一致 都为outside

### Environment

```markdown
- OS:macOS
- Browser:chrome
- Framework: vue3
```

### Any additional comments?

官网上 我粘贴了我的option 问题同样出现 应该和我的本地环境无关

**Comment by plainheart** [comment]
已在 #19176 修复，待 v5.5.0 版本发布。
