### ISSUE TITLE
[Bug] Candlesticks display incorrectly when zooming out versus zooming in with a certain amount of data

### ISSUE THREAD

**Issue by michaelmoopenn** [apache/echarts#19290]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=MYewdgzgLgBMCGsC8MDaBdAUAMxAJxgAoAbAU1gEsYUBGAbhioB4UBWABnYYoGoeBKGAG9MMMXEQA6AA4BXCAAtCAcnjL-mAL6ZQkWABNE8amiy4CJcoxP1rLGDU7c-gkeJiGo8GfKWoARDQA7ABskgDMABz-ADSBQQCckgBM4bHxYck06cFJACxp6DEBuZI00XHlNJKRyTlBkZIJQTm1knl5_kUlbeGsrck1Ca3VrMOVkeHt_d2BbQkhA-3ZE9WRK3N5ZXWz5VPNrWF57K1TrGkTYawt6BraINJQFOAmbjAAHgCC7xQQAFzCUTiTzwAEIKBAzQxIEAT2-vwBQihQLEIIAWiAQABbREomBQGHSUgA5QUSAUfSkZTQ9zQeB4KAA9g08SkMD6AGOdiQlkQUh4Cikf5oPFvdwEokkhDssjQCjAADW1LxqKMAJBeO0YiwmjomEwfKgAEkwFB-QA3eDEQjYWRgYBPF6EVxAkE-RSEHr7FqVBbtE4TM7hDblK5BbK3IHg91KfwAI38GjEWJhAGEFPSoJJDQB5R7PMCEMUfeHC4sgsGIHl4vkCoUA1AqwHudwVjxGJvI9xYMSafh6qEwZKcdj9oA

### Steps to Reproduce

Open the minimal reproduction link and wait for few candlesticks to show up.
Then zoom in and out, you will see that the new candles display correctly or incorrectly depending on the zoom level.
The issue occurs also when changing the right panel width with the mouse

(From my experience, the issue occurs only when updating the chart with setOption)

### Current Behavior

New candles added with setOption display incorrectly when zooming out with a certain amount of data.
Correct display:
![Screenshot 2023-11-11 at 12 41 19 PM](https://github.com/apache/echarts/assets/64182544/a6da62da-c627-4df9-9cad-bbb823f8a799)
Incorrect display after zoom out:
![Screenshot 2023-11-11 at 12 41 04 PM](https://github.com/apache/echarts/assets/64182544/07da8fb3-a814-4b77-bc91-f1ca4700aecc)

### Expected Behavior

The new candles should display with the right yAxis values for any zoom level as long as the candles are in the display area.

### Environment

```markdown
- OS: MacOS Ventura 13.0
- Browser: Chrome, Safari
- Framework: react@18.2.0
```

**Comment by helgasoft** [comment]
duplicate of #18983, #18503.  On large zoom-out candlesticks become **1 pixel wide**, which is the minimum by design.

**Comment by michaelmoopenn** [comment]
If you examine the zoom-out screenshot closely, you'll notice that the new candles are cut in half, with the upper portion not being displayed. The upper part has the same width as the visible section. If the lower part is visible, the upper part should also be visible and not cut off.

**Comment by helgasoft** [comment]
ok, so the issue is about the **height**, not the width.
Notice that [candlestick.data](https://echarts.apache.org/en/option.html#series-candlestick.data) should be in format **[open, close, lowest, highest]**, which is not the case in your data:
present = data.push(["183.97","196.40","183.531","186.571"])
correct = data.push([183.97,186.571,183.531,196.40])

**Comment by michaelmoopenn** [comment]
You are totally right! Thanks for your responses!
