### ISSUE TITLE
[Feature] can you upgrade tsconfig target >= "ES6"

### ISSUE THREAD

**Issue by triajidhan** [apache/echarts#19304]
### What problem does this feature solve?

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error

### What does the proposed API look like?

-

**Comment by sparr** [comment]
Per https://github.com/microsoft/TypeScript/issues/51909:

> ### What should I use instead?
> #### `target: ES3`
> ES3 runtimes are nearly 100% extinct, so we're removing support for this as an emit target.
> 
> Fix: Use `target: ES5` as the next-closest thing along with a linter to detect any potentially-problematic ES3 constructs, or use `target: ESNext` and use a different downleveling emitter.

**Comment by septatrix** [comment]
We are currently already at TS 5.3...

**Comment by dohuuhuy** [comment]
how to fix : 
Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error. 
 
 tôi đang cần gấp

**Comment by plainheart** [comment]
duplicate of #19560. Please follow #19560.
