### ISSUE TITLE
[Bug] 关系图 legendHoverLink:true 时候，图例悬浮事件不准确。

### ISSUE THREAD

**Issue by zhanghang2017** [apache/echarts#19301]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=graph

### Steps to Reproduce

链接地址：https://echarts.apache.org/examples/zh/editor.html?c=graph

### Current Behavior

不同图例hover显示的类目是一样的

### Expected Behavior

不同图例hover显示对应的类目

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
duplicate of #13869
