### ISSUE TITLE
[Bug] line serier clip error

### ISSUE THREAD

**Issue by Cat1007** [apache/echarts#19308]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=area-simple&renderer=svg&code=DYUwLgBARghgziCBeCAKAdiA7hAIjMEVARgE4A2ADgBoJTaBmASiYDoBzcAFQEsBbIkwDcAKFCQA9pnwBPZBABMAFggAqCA3IAGLWojEdW0eIgATAohQBtALrHwZgjHlWrmHPkKo2nMLwHetFo2dmIO5mAwCi5u2HgW3hzc_IJBIaIAZhIATmgmPPLEQhAFADyKhkYlANTVTBAA3iIQECboEjgo7vFeqLAIENUoUiCyLKItETCsAA4ArnAAFqhWzS0Q7VhJfimBay0AsgSLrNkSc-imqKhHYCfZMJcSfN4QALQQWqwArPXqCrpqo5IlYCh9iDYrBCmGsbMIRABfET9SxobqeIhkKi0egaFjbfyCTI5PIOAooIolCDlAGGYo8Wr1JotNodeTohJ9eCIIYQEZjeGTJwKWYLZardYbDoE3ZMaj7CC3e7nS7XJWnR6mZ6vD5fX56AGDYFRUHvfSQ6Gw-FIiQzMA8KTyZkQMASCTAe0zABcjQVYGyPHYnGyPoA5DAAB48OCh-WSmYSOA8e1SH0ZC4AYxT6DQdqZCpa2XAc2yOasdqswVooYMAFJQ6FJUiWgi4y7k6Afc6WSAMmAwxmQOhCNlY36QBH-xBQwAZGDZTgQACCRecAGFFvOwKG1q21q73VAJBGuwqMiACCWQKfJULIgAtN18G-3loyJdRuAASUuE7D7UwHdXz3V8izgV0iy7EDbzgGAADcQCXb8-BgTgoIVZsIGgiMP2jF8WjAGQZmvad7QEMdJSPC5zGyGQAHEYG9CBK2rAwtHrGxdzbd9P3wl0iJI0M4JgYA5hACj1hQk99B0NsWj4Hh0B9LQ5OgFUaPoxifRY6c2I4ri1gQAMQDgbSFQAenM31JUs9Z0BgAQwwAMRgABrRBPBgYgJJaWyCIEsNgEU8TVL8iA4BkPgj2Af8Rh8iAwuTEA-AAZUIztrPWMKWgzd0cjDABiABRBglFwb5SCArKrJbUKauNH0pgsqzoJabs7IcwSXPcnooni_ziMC4L-vCyLotiwDVJaJLUvSkj2slXLgHy6cCp0JdKAAdi0KqmymhrjQUDDYURIQgA

### Steps to Reproduce

set yAxis min and max

### Current Behavior

<img width="747" alt="image" src="https://github.com/apache/echarts/assets/54425790/94da3f29-c219-4326-805e-5eeacb7df24b">
show unexpected line

### Expected Behavior

just cut the data

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
This is just your data. The first entry is the current time.
