### ISSUE TITLE
After I updated the label effect also disappeared with the pie chart

### ISSUE THREAD

**Issue by linhuanxia** [apache/echarts#19305]
### What problem does this feature solve?

Why will my label label be opacity set to 0 below 5.0.0 to be visible? Above 5.0.0 the opacity will be hidden along with the table. I want the pie chart to be hidden, but the labels in the corresponding position will be displayed. How do I do that?
![image](https://github.com/apache/echarts/assets/38238997/10b206f2-5b03-406a-9174-5844c774c7ff)
I need the effect

![image](https://github.com/apache/echarts/assets/38238997/b1ad21be-afaf-459f-bf13-eabf536021d1)
But after I updated the label effect disappeared with the pie chart

### What does the proposed API look like?

![image](https://github.com/apache/echarts/assets/38238997/10b206f2-5b03-406a-9174-5844c774c7ff)
I need the effect

**Comment by MatthiasMert** [comment]
I think the attributes (like opacity) get passed down to the label from the pie chart itself if you dont manually override them. [Here](https://echarts.apache.org/examples/en/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWzQCGAtlsQOQCCAxuwRrAGI7B6zADRUKYAJ4gmsZiHwix6HLQAmEAK5FZAVgAMAUkXV0q2mFrEyJiklgA3WgBsNMgIx6ALAA5hNBjLMAMpYtDjsABawAKLQAOYQ0FjMsAC-ojbodo4uMgDsAMw6fnSMLAAiEDhY7GAp6Uq2Ds6uxDreeiUBLNH0tBBO9RmZ2S0yPp5dZbIAqtBQcKyqGEONWc25xAV6nf7TzABqEKpYwLBLK2mNALrD1BBgWPRBkk4yqJmw7MBOwDgsYBU0AwIDCWGgdUaDRsTloACMsE4ADKJd5rTARYAAd2IgNcdxMTlRLwkb2IH0-Xx-fxYcNh7AA1sx0akoWJWehrihUgBuIA) is an esample that should work.

**Comment by linhuanxia** [comment]
Thanks ! I solved it, close it .
