### ISSUE TITLE
[Bug] [Urgent] Chart always visually lower than setting in mobile devices

### ISSUE THREAD

**Issue by LikeDreamwalker** [apache/echarts#19310]
### Version

5.4.3

### Link to Minimal Reproduction

Business repo and reproduction is below

### Steps to Reproduce

1. Create a chart and set itself a specific height and width.
2. Change the dev tool's current viewport to check the render results.
This issue is weird, but after I tried all the solutions I know it still won't work. 
This screenshot is for mobile devices, and you can see the canvas also the container has a right size, but still the chart is rendered only part of the available space:
![image](https://github.com/apache/echarts/assets/45194556/f288cf14-bff0-4f0f-af4b-f10b6bafd8a1)
And this screenshot is for normal desktop in Browser, the chart is rendered as expected:
![image](https://github.com/apache/echarts/assets/45194556/535d0267-9f21-4aec-9b68-94784c1c3a83)
And I am wondering what caused this issue. I tried follow ways to solve it, but none of them can work:

- Use `resize()` to force its size
- Use `100%` width and height for the chart, set the real size of the chart container
- Render or resize it async
- Edit or lock the DPR and resize

I have no idea if I touched some rules of rendering, but this issue can be very annoying for mobile devices. Please show me more info even if this is not a bug. I can only code a container and set offset for now to solve it.

### Current Behavior

Mobile devices is rendering a Chart visually lower than Desktop.
This screenshot is for mobile devices, and you can see the canvas also the container has a right size, but still the chart is rendered only part of the available space:
![image](https://github.com/apache/echarts/assets/45194556/f288cf14-bff0-4f0f-af4b-f10b6bafd8a1)
And this screenshot is for normal desktop in Browser, the chart is rendered as expected:
![image](https://github.com/apache/echarts/assets/45194556/535d0267-9f21-4aec-9b68-94784c1c3a83)

### Expected Behavior

Mobile devices should be rendered as the same effects as Desktop.

### Environment

```markdown
- OS: macOS
- Browser: Microsoft Edge 版本 119.0.2151.72 (正式版本) (x86_64)
- Framework: MPX but it is used as Vue@2.6.14
```

**Comment by LikeDreamwalker** [comment]
After using a larger height it will visually look better:
![image](https://github.com/apache/echarts/assets/45194556/c5588376-2578-4c2e-8802-1cef337ecfc2)
![image](https://github.com/apache/echarts/assets/45194556/95afbf63-eba0-49e3-b525-daa0efaf3f0f)

So is this a preset rule for improving Mobile' devices render effect?

**Comment by plainheart** [comment]
The chart has default gaps on the [`left/right/top/bottom`](https://echarts.apache.org/option.html#grid.left). You can adjust them as you like.

**Comment by LikeDreamwalker** [comment]
> The chart has default gaps on the [`left/right/top/bottom`](https://echarts.apache.org/option.html#grid.left). You can adjust them as you like.

Thank you so so much for your reply, I have confirmed the default gap space causes this issue, and because these gaps are set as pixels rather than responsive units, they look much more obvious on mobile than the desktop.

I don't have any more questions.
