### ISSUE TITLE
树图鼠标高亮展示问题

### ISSUE THREAD

**Issue by KaiWenPaul** [apache/echarts#19318]
### What problem does this feature solve?

树图鼠标高亮的时候能够高亮节点的所有父节点和所有子节点

### What does the proposed API look like?

树图鼠标高亮的时候能够高亮节点的所有父节点和所有子节点

**Comment by plainheart** [comment]
设置 [`emphasis.focus`](https://echarts.apache.org/option.html#series-tree.emphasis.focus) 为 `'relative'` 即可。[Demo](https://echarts.apache.org/examples/editor.html?c=tree-legend&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAxqoUnAAS5RxTMC8zA3tc2aEowAKYAuZgHIAZgBtYoqQBoBzWhHxzcMUYUkBtNYP6CzQkROlsOK42Y1adew_fOnzn4WMlT6hADdReGCkO09PR21dfWYjCIjeCx9pMAYgkJgw5WYAqDkAVysAdgAmAEZmAF9VBM8k7yspABFROXxgfDhRXAAVUQAPODTA4O6YFVz8oskAFlKATlnqt08AXVXBGs2-HcFG32b2KABVOC1wuqnCqwBmW9LSnarVjfNt91WD63wkAAcFCBLuYos5YvEEg1LId8PAQABlP4wLpKHJ5G6SAAcmPu1VqkOSTUwRFEiOR3Um6JmzHKxQeeJ2UJSUgASqJaHAySjKdM7gA2Uq3FYRN5mD5mDzmb6yOSDYEOTTRFxxJlNABiCl0ADVfjyMcxZuVynzqqKtviTF9odIAI5FGBAi0KpwxVx1VW-ACCxGIumI7FEAFEBkjREgkPgGHrqcbjQz3YSvYRcNGrOUAAylYrxgnSz3kiBic60VOSW6YhaVcWJRPST0ZKDEVHXakVqtO9y1qQAISIsBAwdD4cjhFLzFKFaF1fqXbSwD-sF-UbRvMkAFYM1OOxLZ6h56gI91B7ph8uW_zitnp53pWkCoQ4GPipj24yu0dumcLiv9YbDTma2lZpfnOQgOTHBZcWvHdpWPMMIzPKkrA3W50wAmdYJDE8EMIABJcZ2FQCYf2pW4-VpdCb2tKQ1VHEi7lKWY0Ogkwu1wmQxyzekWL4NikE9Tj01uBZKJg6jiQIuQx3KCplh4j1pAAWXYDQx1uYpZkxUTWOlZSBg6ApgDHTFZi3Rk9i7Is0FwbILNBV04gsnTqLwFN6PXSDtIwlzkzU1CvKo5koAbJtOMxK9t0A6j6HvR93PHS8ArE5kCCYIhwPixZSiS5yUvwAIxzXBY1xy3jpVEG1CqWUqFNkOjzzmPlmMi7zmWIOKGuYJqzKuZKmna5skMkAUSp4wKmnwGQOPijStLGvrfF-KAx1mciaq7OQOqG5gioipyyuozbBtXLryhE-bcqaYAoAGMKet6g7mU6ertone7etq4BUDczqitfB7HqugopPi7r1ulQgKqq86WvG3xCFQLaTvLE0LsB3wiLUwVweoojcGCAAjR1OtQvaAdqmAoBIY79UvbK0dqpA2nZJH9UWVHYYW6QmFwfGCvisj3quRmCgJscmua_aRaMzLMUl8muwKP4bBp0j0zJh7aryZEqdoVW7luUbOcu3x0AgYJ9ckRYYalrsBkxgW1zk430ekAB9Ti-TkiyzU8eSu0UogDJlzqTKFuHpAAOUR6S1ydrzaoAeWIzqFmKeXc2ogBFe1ie28pywWDm32lFkqdC-LyiK52S-o-E4GREgvxBzrDX8_3pXhQyn0rBOuy1RcoAJ2VpJkmuE2lAedbAy2aXC4uJ-ogANB3OqNdMq1eexp0lMxpSQWh8lRVZ7OVCEouZXD4UP2VlL-TiMyN2vmWJSHYGvo_pNuOMO_E1BiA_iPAWVd_qZ2ZMnAgwg5CANnupdOfdpQ5ypucWUMDOKmSfovZkSCHxdHYPlUkN9Z6aWEgg6iLJUCIzQZXYoa4F5gKaNQ1upQ-RzRarVGBvQQB_FnuUTEFQyHMl6B0Qhn94prhxFOLe7w1AbCqDQbWrBjjZR4B4aU8hFCXFPuCewu99jUXkHKbc2jDC1Q1IoHU2RW5GlRr7HeVpmQHzESfRUYI3QMN8FfIhd8H7pkwR46Qr9RDvyIV_H-7CuzYAAaE4BG5BFNAgX2aBMSSaXgzhfJoOCUGiKAZ1Riht4m-CyXg84QQmHbRITbLBTQKFUJSfnWh9CMm-HKSdeYrDCnSE4dw3h_DQHNOkMIsQrT9QSKgtIsUTo9FdlSgCKAjoXEujPrVYCcIuQUnitiKCdjZHUHkdQUAkBYCIE0PjbAeAiBkCoAc8A0B4DIFEHAROfxzgMFIGoUgqAXkjm4LscwcBKGbXwH8SQ0yG74B9MERa3QjLbydEzZEYZ3GfDqHAHpvgG6iGPnUGwUBDC4rWC1BQBM2igosn8A8XQRy-FlDIOKFkMjFnyJ6doxBYhSE6LzIBFl8gQvZciYgEBHzPCJcEoISAyW9WJaSv5D0KWHmpdIAVQr5R1EZfgG-LK-W-E5bgblANeVsppaIOlUgLIvDqDxUQ85oARglbKuoAB6R1zBABaAYAMkdAACRoASHNAAK2oATW1AAxKoANU9AASioAIKDACdDrkNcCBbhxuYIAAH1ADTmoAelNACAxhZGQqBaAFHtVIXQChSlKBFTsQYC5kyemTGkOQCg_hM0kA3IoLUqYdHwQwZoBRKavNiHHdMLbCBtp7Z27tI4TjKwDJIWh6ZVgWrMKKKo5BqBUCAA)
