### ISSUE TITLE
[Bug] 声明的自定义图形不能控制拖拽方向

### ISSUE THREAD

**Issue by somnusnrlq** [apache/echarts#19314]
### Version

5.4.3

### Link to Minimal Reproduction

https://jsfiddle.net/TokyYX/smjdkzvL/1/

### Steps to Reproduce

1. 示例中添加了一个自定义红色圆点 实现只能在纵向拖动 现在是可以随便拖动
2. 代码中在拖拽事件中控制了cx为固定值无效

### Current Behavior

想要实现控制一个方向的拖动

### Expected Behavior

想要实现控制一个方向的拖动

### Environment

```markdown
- OS:windows11
- Browser: chrome
- Framework: 119.0.6045.160
```

**Comment by helgasoft** [comment]
not-a-bug,  see [Official Example](https://echarts.apache.org/examples/en/editor.html?c=line-draggable)
please close issue if problem solved

**Comment by plainheart** [comment]
You can set `draggable` as `'horizontal'` or `'vertical'` to restrict the dragging direction. Refer to this [demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=LYTwwgFghgTgLgOgM4FM4HkAOcCWB7AOwAoBvAKAAIKAPAQWpyQC4Lyqq4RMUWByAYyhwUAczwwQvADSV2AEyFQWAbV4BZQtIq8AKgFcUW3gHUUcozoh6jAMRg4jAZSFO9BXgF1ZAXxlUQ9IwsbOyc3HwAblAANga8Pn4UqPYozBTKslQh7BQKcErpAIwATAAMUhRl5RSFAKzVABzVAOzVhYVtAMylHok5YTzaAEaw0pnsSBB4AO4AQlD8ANYiMHhucixwMAZ97CNLK2sEco6c0YPZORT8eNHifDAiI0SFTRWvbW8UpQjFAJTxK4UbzjEFULzeP4AbjIZBuBCQcFyMCgIgACngcAQ4KdYEiALwUAgoaYUFD8aDwJAIFZQTAQHD8BBgHAwfjnUiySZ0i7XagsDrVfggAWlaowFi1YGJREgc7BCgAMxw0WiDzMvGlsgA9NrtFN7AAvQj5aKavW8CIoeCMmLmihDPC3FBQAiyOQokQiKBDeX68Q4Y3Yu2JQ0sACckbIkJhoEgeJpaAAWjAiH8EFA5HIiB7URisTj8vBoUA).

**Comment by somnusnrlq** [comment]
谢谢
