### ISSUE TITLE
[Bug] 动态的series，会导致数据错乱。

### ISSUE THREAD

**Issue by vernonin** [apache/echarts#19332]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/s/nervous-mendeleev-xmk33z?file=/src/index.js

### Steps to Reproduce

1.第一次显示正常。
2.当选择其他项，异步获取series。
3.将新的series数据放在option。

### Current Behavior

1.第一次显示正常。
2.当选择其他项，异步获取series时，数据不对应了。

### Expected Behavior

当我异步获取series时，希望数据跟series保持一致。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
默认策略是会合并前后配置项，你的这种场景可以设置 [`notMerge`](https://echarts.apache.org/api.html#echartsInstance.setOption) 为 `true` 避免合并，直接以新配置项替换旧配置项。

**Comment by vernonin** [comment]
好的，O(∩_∩)O谢谢啦！
