### ISSUE TITLE
[Bug] the name of Axias cannot  be placed in the lower right corner of the line-chart

### ISSUE THREAD

**Issue by zcg1991** [apache/echarts#19338]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-function&version=5.3.2

### Steps to Reproduce

function func(x) {
  x /= 10;
  return Math.sin(x) * Math.cos(x * 2 + 1) * Math.sin(x * 3 + 2) * 50;
}
function generateData() {
  let data = [];
  for (let i = -200; i <= 200; i += 0.1) {
    data.push([i, func(i)]);
  }
  return data;
}
option = {
  animation: false,
  grid: {
    top: 40,
    left: 50,
    right: 40,
    bottom: 50
  },
  xAxis: {
    name: 'x',
    minorTick: {
      show: true
    },
    minorSplitLine: {
      show: true
    },
    nameTextStyle:{
      verticalAlign:'bottom'
    }
  },
  yAxis: {
    name: 'y',
    min: -100,
    max: 100,
    minorTick: {
      show: true
    },
    minorSplitLine: {
      show: true
    }
  },
  dataZoom: [
    {
      show: true,
      type: 'inside',
      filterMode: 'none',
      xAxisIndex: [0],
      startValue: -20,
      endValue: 20
    },
    {
      show: true,
      type: 'inside',
      filterMode: 'none',
      yAxisIndex: [0],
      startValue: -20,
      endValue: 20
    }
  ],
  series: [
    {
      type: 'line',
      showSymbol: false,
      clip: true,
      data: generateData()
    }
  ]
};

### Current Behavior

![捕获](https://github.com/apache/echarts/assets/44219901/9eb0c03b-5c65-4e79-be60-d2dd03130fd8)

### Expected Behavior

![捕获2](https://github.com/apache/echarts/assets/44219901/30982d52-592b-4317-bdd5-dbea83a4ae6a)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

  nameTextStyle:{
      verticalAlign:'bottom'
    }

is not  effective

the name of xAxis is always at position 0 of the Y axis, not the lower right corner

**Comment by helgasoft** [comment]
experiment with [xAxis.nameTextStyle.lineHeight](https://echarts.apache.org/en/option.html#xAxis.nameTextStyle.lineHeight), negative values will move _name_ down, but to a fixed (unresponsive) distance. Eventually _rich_ could also help if you find a good example.

**Comment by zcg1991** [comment]
> experiment with [xAxis.nameTextStyle.lineHeight](https://echarts.apache.org/en/option.html#xAxis.nameTextStyle.lineHeight), negative values will move _name_ down, but to a fixed (unresponsive) distance. Eventually _rich_ could also help if you find a good example.

thanks for help
but I try two methods but nothing happen ....
![111](https://github.com/apache/echarts/assets/44219901/92c8b1f1-997c-46b5-9b33-9c736b171ad0)


![222](https://github.com/apache/echarts/assets/44219901/9f54d399-34fe-4cb8-b04b-bbc2ca0d9c0d)

**Comment by helgasoft** [comment]
```
    nameTextStyle: {
      lineHeight: -222,
      verticalAlign: 'bottom'
    }
```

**Comment by zcg1991** [comment]
> ```
>     nameTextStyle: {
>       lineHeight: -222,
>       verticalAlign: 'bottom'
>     }
> ```

thanks ,  it works
