### ISSUE TITLE
echarts地图散点图配合使用高德地图或者百度地图，保存图片功能的问题

### ISSUE THREAD

**Issue by yuchuang0208** [apache/echarts#19340]
### Version

5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap

### Steps to Reproduce

echarts官网中的示例
地图散点图

### Current Behavior

地图散点图+百度地图，toolbox.feature.saveAsImage，下载的图片没有地图背景，只有散点图，我在官网的例子中使用也不行。
![全国主要城市空气质量 - 百度地图 (1)](https://github.com/apache/echarts/assets/31911855/7aa82f42-718a-4a01-a1cb-a8eb4a856888)
是不支持背景还是需要其他的配置项？？

### Expected Behavior

下载的图片中有百度地图背景

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
高德/百度地图图层和 ECharts 图层互相独立，因此调用 ECharts 的导出 API 并不会包括地图底图，你可以结合使用 dom 转 image 之类的库来导出包括地图的图片。
