### ISSUE TITLE
[Bug] showtip event bug.

### ISSUE THREAD

**Issue by luojiandan** [apache/echarts#19346]
### ECharts Version:5.4.3

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  tooltip:{
    trigger:'axis'
  },
  series: [
    {
      data: [820, 932, 901, 934, 1290, 1330, 1320],
      type: 'line',
      smooth: true,
      showSymbol:false    //show while tooltip hover.
    }
  ]
};
```

### Current Behavior
```
//showtip event bug.
myChart.on('showtip',function(params){
  myChart.setOption(option)
})
```
### Expected Behavior
![image](https://github.com/apache/echarts/assets/5663556/29fc0d05-e71c-4ade-83ab-de138bc1ee62)

**Comment by MatthiasMert** [comment]
the problem is the `setOption` on the event callback. If you remove it everything works fine. [Here](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG5gRqysVBx0jLh4tA4keIkQVISwovzEHoLCYgCMAKwADDywAEwAzDX1dQAstXVlABy1ZQ0Vva0A7B0AbFXWoR4U1HT-ENDKU6R42sAA7ibkALYARhFEAGYBWct2JLZ2ANwoKNvkAMLajBxgAHQwABS0qxtRMp8QC9GNs8ABKBAAPlg9BgeAiVDe_mArEBwNBYLBVyAA) is an example.

**Comment by luojiandan** [comment]
> The problem is the `setOption` on the event callback. If you remove it everything works fine. [Here](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG5gRqysVBx0jLh4tA4keIkQVISwovzEHoLCYgCMAKwADDywAEwAzDX1dQAstXVlABy1ZQ0Vva0A7B0AbFXWoR4U1HT-ENDKU6R42sAA7ibkALYARhFEAGYBWct2JLZ2ANwoKNvkAMLajBxgAHQwABS0qxtRMp8QC9GNs8ABKBAAPlg9BgeAiVDe_mArEBwNBYLBVyAA) is an example.

yes，remove is ok.
but my business code want to change option's value.then use setOption again.
so,can't remove it.

**Comment by luojiandan** [comment]
> As a workaround you can adjust the symbol yourself: [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jmTAwP6QIG5gRqysVBx0jLh4tA4keIkQVISwovzEHoLCYgCMAKwADDywAEwAzDX1dQAstXVlABy1ZQ0Vva0A7B0AbFXWoR4U1HT-ENDKU6R45AC2AEYRdNAwyoV2JLZ2ANwoKGvkAMLajBxgAHQwABS0eNrAAO5RMs8gd4w1ngAJQIAB8sEuNzujyyYAA8uAoNBnkgskZcmI0estv46FQ1uBrhAOPR_Mo7NY7MDgWcLtdbvcnijaNoIAIqD9an8AUDQfAIVDGbDOYjIC80dlMflsZttrJdot0lSaScgA)

hi @MatthiasMert thanks for you replay.
![image](https://github.com/apache/echarts/assets/5663556/d474e682-37ce-4711-8dd6-0f0bb27b856c)
my code is:
```
var arrDates=['23-11-16','23-11-17','23-11-18','23-11-19','23-11-20','23-11-21','23-11-22']
var arrPrices=[8.6,5.3,6.2,7.1,4.2,7.8,3.5]
var arrDatas=[]; 
var arrData2=[];  //最后一个标记点
var intLength=arrDates.length;
for(var i=0;i<arrDates.length;i++){
  var isLast=i==arrDates.length-1?true:false;
  arrDatas.push({
    name:arrDates[i],
    value:arrPrices[i],
    last:isLast
  });
  
  if(i==arrDates.length-1){
    arrData2.push(i);
    arrData2.push(arrPrices[i]);
  }
}

var dataDesc='数据更新时间：10-08 14:25'

option = {
  grid:{
    left:'5%'
  },
  title:{
    text:'价格波动图',
    left:'4%',
    top:'1%',
    subtext:dataDesc,
    subtextStyle:{
      color:'#CFCFCF',
      fontSize:13,
      position:'right',
    }
  },
  graphic:{
    elements:[
      {
        type:'text',
        textContent:'XXXX',
        right:'10%',
        top:'10%'
      }
    ]
  },
  xAxis: {
    type: 'category',
    data: arrDatas.map(item=>item.name),
    boundaryGap:false,
    axisLine:{
      show:false,
    },
    axisTick:{
      show:false
    },
    axisLabel:{
      show:true,
      color:'rgba(200,200,200,1)',
      fontFamily:'黑体',
      fontSize:13,
      formatter:function(params,index){
        if (index==intLength-1||index==0) {
          return params  //只显示首、尾标注
        }
      }
    }
  },
  yAxis: {
    type: 'value',
    interval:4,
    axisLine:{
      show:true,
      lineStyle:{
        color:'rgba(242,242,242,0.9)'
      }
    },
    axisLabel:{
      color:'rgba(200,200,200,1)'
    },
    splitLine:{
      show:true,
      lineStyle:{
        color:'rgba(242,242,242,0.9)'
      }
    }
  },
  tooltip:{
    trigger:'axis',
    backgroundColor:'#777777',
    borderWidth:0,
    padding:[6,10,6,10],
    formatter:function(params,ticket,callback){
      var data=params[0].data;
      return data.last?'':`${data.name} ¥${data.value}`
    },
    textStyle:{
      color:'white',
      fontSize:13,
    }
  },
  series: [
    {
      data:arrDatas,
      type: 'line',
      symbol:'circle',
      symbolSize:6,
      showSymbol:false,
      smooth:false,
      markPoint:{
        data:[
          {
            name:'最大值',
            coord:arrData2,
            symbol:'circle',
            symbolSize:8,
            animation:false,
            label:{
              show:true,
              position:'top',
              backgroundColor:'#EB432E',
              color:'white',
              fontFamily:'sans-serif',
              fontSize:13,
              align:'right',
              padding:[6,10,6,10],
              borderRadius:8,
              formatter:function(params){
                var index=params.data.coord[0];
                return `${arrDates[index]} 当前 ¥${params.data.coord[1]}`
              }
            }
          }
        ]
      },
      itemStyle:{
        color:'#EB432E',
      },
      lineStyle:{
        width:1.5,
      },
      areaStyle: { //区域填充样式
        normal: {
            //线性渐变，前4个参数分别是x0,y0,x2,y2(范围0~1);相当于图形包围盒中的百分比。如果最后一个参数是‘true’，则该四个值是绝对像素位置。
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: "rgba(244,156,144,0.5)"
                },
                {
                    offset: 1,
                    color: "rgba(255,255,255,0.01)"
                }
            ], false)
        }
      },
    }
  ]
};

/* event bug
myChart.on('showtip1',function(params){
  var index=params.dataIndex;
  if(index==intLength-1){
    option.series[0].markPoint.data[0].label.show=true;  
  }else{
    option.series[0].markPoint.data[0].label.show=false;
  }
  myChart.setOption(option);
})

myChart.on('hidetip1',function(params){
  option.series[0].markPoint.data[0].label.show=true;  
  myChart.setOption(option);
})
*/
```

**Comment by MatthiasMert** [comment]
[Example1](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAVgAwA0MATAMyEnEAsRxWAHEVqTk1QOy0BseAugNwAoQSAAOUAJbg0MAN6CYMBGAkBbJFLAAuGADMEAGwgBTAgpgAPAIIWJEHfMWKoAT1HGdAcmBJjAcxAAJxdPMyd4JAQdDE8AWXBQmE8AFQBXY0TPAHVjOEzkgAtUzIAxQIlMgGUkKtSwT14wmABfJpcbOwdzZzcPJIA3Q3TPc1bzKBAQA0lRByhyvz9jQK8EWwhPMcUTcuN7TG65Q8VEZB1ThCbw13cvAwkwDKunCBdVACMprzBwJ8Pm8y8QTNISCVQuADCBQQgSgADpwAAKTwQAogADuM0SiNEMIQqggAEo0AA-I6KUCQWAPODGCwyXGBfEQOEXACSYFpFiEinBUJh8JMUAA8uJNIjZDsJHtorJ1IEANYABRADygDleHy-SWAEkCwAMTxgms-BkqEgAXn1GBEzphZKAgnBojS6UQLhhXRZeLxmr6_c1CcDCaC-dDYQiwMiChJaViiDi8QTiagyWGBXChaLJEjJctpfsMHKYcrVWB1XITdrPD9HpsA4SQ0A)

[Example2](https://echarts.apache.org/examples/zh/editor.html?c=line-smooth&code=G4QwTgBOYCIgLgUwM4F4DaByATAZgLQCMhRAbJgDQ4HFEDsl1RJhAHI3s0QJwc0nYADHy7ZCI2tmyYAugFgAUKEjQACmACWAYxQZWAOlIUArPtwVS-7BTr7CFACxWb-1hVz7j8peChhYCCBo6DIA3BCKyn4B8CDYGGEQEAD0yYAA5oBwKoAAcoBUcoDgFoAN0YCdDpG-GgB28AAyiOUA5vAAFqjQcEjI-gA2tQ2NoYoAZgD2YAAUURqogqEaADytCChdPU0zANRrAJQA3opJE8hVQfCoky3-bUvd9U1EAPzwYACuiABcAyCdyIj9CkkLsQ6AAcnshGqNdn8khByiAALZvAEodAaGQUPbQ0CdF6vNSaHTIFFojFJTrHV4aQ7HDEAX02vySGI0A1GZyRHWuvSIOxJ0TacX0ILBrPpvIBAqF4Lx2mRqNFUJpikVClKkAAJoEYCgtKhMIAHU0AdsaAF7NAA2mgDfTQAvqYAsf8IgnwglYEEIDle2GMmEUiiGQPgGiG5QgqAgkP-5Q0cIQfvKrwgHy-iHRULqmjVrxD0O6A3gr0wxgApB6FYmkr74N007ykAAPbOYQDvcoAeC0ARzaACqVAH9qlF5mdrDgLxeh8G9OcIfd5yCeACNq9mNbEtcgtP2kuOp4gawBleAAT3L6ehEC0Q06IxzAGIAMIAMSvV87UP3w0q640AC83oRzLykkChsgNL7_RzTQ6kaeA733ZUkhpftkxAIFGm0Ct7wgRBugRSpkFedAv2DHCSy3IE3kwadwP3Ac13gc9_SQSocwADQYujSLIiBgNA4dBFHZD90HIEOILHDIOhbwoP7KsAEEq0pGM9wgbdCJjTAtEWOoRi3ZiIFnEAY3FDoIyBVkkDhVAAD5_0QOF9FhBFNiXCAJyGJ5yg1MAtwAcTg95Pm-OyQCkw4KjeWTl0aIYAHcvPjOzoLFfyABVtAAayQliwXCyLvl5GLkL8ykjgnVCUrItKIseF47KSQ9jzAIC6gnEBRiEQQKCalrBGawhNg0pJH3gS94Q0TotxzQBFvMAZXlutjajnzfV4PwqqawAjeAkBqgYnK0ADylGIFwHhZAKAqNU1x5bjoWZCBWWctdUFOSoahuRoiAAH2eo6bqmTZcLO_cwEQeAnjAANdrAfaklSQAr5UAPjNAC5PQA0zMAQAZAD4dPJAAubPCICEiCstpfst0k6Tvp4gi3ggTAsReDSKlWrFXgcXz_KqQKiv3ErXjKhMcM6QLNx3IKMaqk9MDAOqGuwBxrHFyWJYoQR9G4LrBKyhm8pAArOhZ6FBZq4XRca9q2ua1rOsLCC7OQIFueqZngogNmOYW7nykQXndwFo8hZF-rGplqWWpluWFdNsiscx3GMUHI9fT42THg0Oo6kQHXcuQDT6q0RLk0c5yqOqs86ALwu05GY6wAAdQ0NUmleZreV2tU1QqOosKMW0LAoW1iWQ4YloQVb3g2radr2uEDt9DP_ooZTOk6dPEtOlioi01AQf29BBBkfQtIZMi_oBoHNMCLpjjuTBMFeAADAASbYtKs-FEBpCAAFKb7vinH4v5XKwo13-bO7WOYwoISQJNXqM13yfmQkJbKy4k4aBQDGbCyFbZaVxBcQIB0cLyVJpgJ2iBJrIC3HCByGtMDlH9AQhaRCSFHgga8IwOFkBwiGEMaucYfI4QjGARKqghjU01vuNByCWL7ltixayRE0iAHJNQAPAqTRYoeEu6CYhxAWqlYhpCcxaA0GALQ3QFHFU0XQ18bw3AY33CAMMy0owZU5j9MiZJ1aCNESFdKDsLFkR_H-LaOZeKGJYnPLOTk1S5yFqeAAogAIQcLgbAESAlkUAZgYB5lEkPmov1OEg1hqYGQFY5A-BviaAGOk6E4DTFzSga4linx47RmFvHUCZTvwgAbk3FuHdmqtw3uo0RDkwClwAEptI0KCV45iHEsR7stfu61yibSjMPUGo8F41MXmUa6VYV4jw6HfJRgz15hE8SxPegMAzX22OyFEWyZBP0AMr6gBZJRfjfVeo8t5HwOWqdAhA7lfymSHE5YcAWh33CJEOC1zJwj_i4yqHsdaRJiXEhJC1YGOJ5tuN2DiwqV2roQTwqKFrgEQCAGFwYUjJEAFzKgB99UANYagBRRUAOwWgB4fQxhQ3uGsibrIpYAfr9ADkBoABDtAAbyoAGH_HkOByIAIeU9SADAlQA1EqAHozKszUtzNSrNYLc2BRiAGBgwAL2qCAAH6dVCIAD7d7mADi5NsgAjfUAKDKurABLboAWjlAAhboAPzcZWABXrQAQAyACDNQAOeaZFyNKhVgAMAg5oATAIRWAEwlQAp9GAG21HIsiFWAF2_QAn9qAHmFQABL6AFl5QAdv5eqBYAmEiAwooS0I0cA8AOiwXgtofQTNnbgDcqDRutR4CjGahATtnb7AQHQOI7lSQhgDAGN8bMXa-mDqLQAIi9mLBw9NCDGFbgu2WnhNjTqBWbLd0IB2DuHaO_6MZ7A7sUfCmMs69ZumMC1YwN7r1rsEJ1TdAKWKgtEWiWM3lECbAxu-tFUEMTeBpL8T0KoFBwi3OeCtYB4D6H9KMPJoUwrR0oJdN5yAvqmS5YecoyB4AQHelWQMEAMMfNiAASS2TvSD0HK36DHQAeR9Es7YxSEGYT7dsbhvD-G0WDDQrRZMdF6IMRQO2xjOj0IgG4Q-sQkHbC-Ugoj4npQEhucdKsMg7l3JpHc39Cg6SgYg1BmDcGEOYAQsdVD4nln7SwyZCAtGzMMf-sxoebH4GIK4zxvhAiBOScUhQ52mAaR6bpPSIAA)

**Comment by luojiandan** [comment]
> [Example1](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAVgAwA0MATAMyEnEAsRxWAHEVqTk1QOy0BseAugNwAoQSAAOUAJbg0MAN6CYMBGAkBbJFLAAuGADMEAGwgBTAgpgAPAIIWJEHfMWKoAT1HGdAcmBJjAcxAAJxdPMyd4JAQdDE8AWXBQmE8AFQBXY0TPAHVjOEzkgAtUzIAxQIlMgGUkKtSwT14wmABfJpcbOwdzZzcPJIA3Q3TPc1bzKBAQA0lRByhyvz9jQK8EWwhPMcUTcuN7TG65Q8VEZB1ThCbw13cvAwkwDKunCBdVACMprzBwJ8Pm8y8QTNISCVQuADCBQQgSgADpwAAKTwQAogADuM0SiNEMIQqggAEo0AA-I6KUCQWAPODGCwyXGBfEQOEXACSYFpFiEinBUJh8JMUAA8uJNIjZDsJHtorJ1IEANYABRADygDleHy-SWAEkCwAMTxgms-BkqEgAXn1GBEzphZKAgnBojS6UQLhhXRZeLxmr6_c1CcDCaC-dDYQiwMiChJaViiDi8QTiagyWGBXChaLJEjJctpfsMHKYcrVWB1XITdrPD9HpsA4SQ0A)
> 
> [Example2](https://echarts.apache.org/examples/zh/editor.html?c=line-smooth&code=G4QwTgBOYCIgLgUwM4F4DaByATAZgLQCMhRAbJgDQ4HFEDsl1RJhAHI3s0QJwc0nYADHy7ZCI2tmyYAugFgAUKEjQACmACWAYxQZWAOlIUArPtwVS-7BTr7CFACxWb-1hVz7j8peChhYCCBo6DIA3BCKyn4B8CDYGGEQEAD0yYAA5oBwKoAAcoBUcoDgFoAN0YCdDpG-GgB28AAyiOUA5vAAFqjQcEjI-gA2tQ2NoYoAZgD2YAAUURqogqEaADytCChdPU0zANRrAJQA3opJE8hVQfCoky3-bUvd9U1EAPzwYACuiABcAyCdyIj9CkkLsQ6AAcnshGqNdn8khByiAALZvAEodAaGQUPbQ0CdF6vNSaHTIFFojFJTrHV4aQ7HDEAX02vySGI0A1GZyRHWuvSIOxJ0TacX0ILBrPpvIBAqF4Lx2mRqNFUJpikVClKkAAJoEYCgtKhMIAHU0AdsaAF7NAA2mgDfTQAvqYAsf8IgnwglYEEIDle2GMmEUiiGQPgGiG5QgqAgkP-5Q0cIQfvKrwgHy-iHRULqmjVrxD0O6A3gr0wxgApB6FYmkr74N007ykAAPbOYQDvcoAeC0ARzaACqVAH9qlF5mdrDgLxeh8G9OcIfd5yCeACNq9mNbEtcgtP2kuOp4gawBleAAT3L6ehEC0Q06IxzAGIAMIAMSvV87UP3w0q640AC83oRzLykkChsgNL7_RzTQ6kaeA733ZUkhpftkxAIFGm0Ct7wgRBugRSpkFedAv2DHCSy3IE3kwadwP3Ac13gc9_SQSocwADQYujSLIiBgNA4dBFHZD90HIEOILHDIOhbwoP7KsAEEq0pGM9wgbdCJjTAtEWOoRi3ZiIFnEAY3FDoIyBVkkDhVAAD5_0QOF9FhBFNiXCAJyGJ5yg1MAtwAcTg95Pm-OyQCkw4KjeWTl0aIYAHcvPjOzoLFfyABVtAAayQliwXCyLvl5GLkL8ykjgnVCUrItKIseF47KSQ9jzAIC6gnEBRiEQQKCalrBGawhNg0pJH3gS94Q0TotxzQBFvMAZXlutjajnzfV4PwqqawAjeAkBqgYnK0ADylGIFwHhZAKAqNU1x5bjoWZCBWWctdUFOSoahuRoiAAH2eo6bqmTZcLO_cwEQeAnjAANdrAfaklSQAr5UAPjNAC5PQA0zMAQAZAD4dPJAAubPCICEiCstpfst0k6Tvp4gi3ggTAsReDSKlWrFXgcXz_KqQKiv3ErXjKhMcM6QLNx3IKMaqk9MDAOqGuwBxrHFyWJYoQR9G4LrBKyhm8pAArOhZ6FBZq4XRca9q2ua1rOsLCC7OQIFueqZngogNmOYW7nykQXndwFo8hZF-rGplqWWpluWFdNsiscx3GMUHI9fT42THg0Oo6kQHXcuQDT6q0RLk0c5yqOqs86ALwu05GY6wAAdQ0NUmleZreV2tU1QqOosKMW0LAoW1iWQ4YloQVb3g2radr2uEDt9DP_ooZTOk6dPEtOlioi01AQf29BBBkfQtIZMi_oBoHNMCLpjjuTBMFeAADAASbYtKs-FEBpCAAFKb7vinH4v5XKwo13-bO7WOYwoISQJNXqM13yfmQkJbKy4k4aBQDGbCyFbZaVxBcQIB0cLyVJpgJ2iBJrIC3HCByGtMDlH9AQhaRCSFHgga8IwOFkBwiGEMaucYfI4QjGARKqghjU01vuNByCWL7ltixayRE0iAHJNQAPAqTRYoeEu6CYhxAWqlYhpCcxaA0GALQ3QFHFU0XQ18bw3AY33CAMMy0owZU5j9MiZJ1aCNESFdKDsLFkR_H-LaOZeKGJYnPLOTk1S5yFqeAAogAIQcLgbAESAlkUAZgYB5lEkPmov1OEg1hqYGQFY5A-BviaAGOk6E4DTFzSga4linx47RmFvHUCZTvwgAbk3FuHdmqtw3uo0RDkwClwAEptI0KCV45iHEsR7stfu61yibSjMPUGo8F41MXmUa6VYV4jw6HfJRgz15hE8SxPegMAzX22OyFEWyZBP0AMr6gBZJRfjfVeo8t5HwOWqdAhA7lfymSHE5YcAWh33CJEOC1zJwj_i4yqHsdaRJiXEhJC1YGOJ5tuN2DiwqV2roQTwqKFrgEQCAGFwYUjJEAFzKgB99UANYagBRRUAOwWgB4fQxhQ3uGsibrIpYAfr9ADkBoABDtAAbyoAGH_HkOByIAIeU9SADAlQA1EqAHozKszUtzNSrNYLc2BRiAGBgwAL2qCAAH6dVCIAD7d7mADi5NsgAjfUAKDKurABLboAWjlAAhboAPzcZWABXrQAQAyACDNQAOeaZFyNKhVgAMAg5oATAIRWAEwlQAp9GAG21HIsiFWAF2_QAn9qAHmFQABL6AFl5QAdv5eqBYAmEiAwooS0I0cA8AOiwXgtofQTNnbgDcqDRutR4CjGahATtnb7AQHQOI7lSQhgDAGN8bMXa-mDqLQAIi9mLBw9NCDGFbgu2WnhNjTqBWbLd0IB2DuHaO_6MZ7A7sUfCmMs69ZumMC1YwN7r1rsEJ1TdAKWKgtEWiWM3lECbAxu-tFUEMTeBpL8T0KoFBwi3OeCtYB4D6H9KMPJoUwrR0oJdN5yAvqmS5YecoyB4AQHelWQMEAMMfNiAASS2TvSD0HK36DHQAeR9Es7YxSEGYT7dsbhvD-G0WDDQrRZMdF6IMRQO2xjOj0IgG4Q-sQkHbC-Ugoj4npQEhucdKsMg7l3JpHc39Cg6SgYg1BmDcGEOYAQsdVD4nln7SwyZCAtGzMMf-sxoebH4GIK4zxvhAiBOScUhQ52mAaR6bpPSIAA)

Hi @MatthiasMert ,I get it.
thanks very much.
best wish for you.
