### ISSUE TITLE
[Feature] 绘制两条折线间的面积

### ISSUE THREAD

**Issue by kanoakliu** [apache/echarts#19343]
### What problem does this feature solve?

我有一个场景需要绘制两条曲线间的面积，但当我查看文档后发现`line`类型折线的`areeaStyle`可以绘制面积区域，通过`origin`配置图形区域的起始位置，但是`origin`仅能控制`start`,`end`这些，新增的`number`也只能控制面积区域在number所在的直线上而不是可以到下面另一条折线停止？（原谅我并不是专业的Web开发人员，如果可以请给我一些提示，非常感谢）

### What does the proposed API look like?

我现在的解决方案是两条折线都通过`areaStyle`绘制面积，通过下方曲线的面积颜色调整为echarts背景色同样的颜色来覆盖上面曲线多余的面积以此实现虚假的两条曲线间的面积，但是这会在鼠标悬停到上方曲线时暴露，有什么更好的解决方案吗
![image](https://github.com/apache/echarts/assets/73887119/5831c426-ab9f-4b7d-a29b-f3f51b875bd1)
![image](https://github.com/apache/echarts/assets/73887119/defbb291-a5db-4ffb-94c1-5e686ae8d016)

**Comment by MatthiasMert** [comment]
You can use the [stack property](https://echarts.apache.org/en/option.html#series-line.stack) of the line line series together with [areaStyle](https://echarts.apache.org/en/option.html#series-line.areaStyle).

[Here](https://echarts.apache.org/examples/en/editor.html?c=doc-example%2Fline-stack-tiled&edit=1&reset=1&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AI2ABXaABNGXAOKMQRAGaMANnip9SsCWEZEA2rUAWKoAA5XrEOAYuVOHAkHJWDgbbU7gFLk7gW0U7gU9NaAXRIBfdVhyHHwiVA0KajoAN2VhKlp_QNUOCCpCWF1-Yg10aEYAWxozQAQjQBK5Xmz0SOLaJQhoBMCNPALgYDAACyIwDnjm0jxtegBrOiHGUcrczWYdTIBGAAYeWAWAJlX1hdWAVgAWLYA2FdgADgBmU4B2Ze8B9EkqRgBlCiVi8JnYemAlTjorA4VCo0ESMz82QC2S-GnyRTogBCMwC0sdNcjU6PVGmiWm0Ot0yH01FVYBNRuNhiMcaQtPNdFdVgszptYPsLodYNcAJw7WAXLmnBlrJb3ElPV7vT4k9C_f4cOgCJTxcG5SEaaEaWGkeG1QDwhoBEFWp1UotSxTRJrXaXR6RIepMpFMmVLttL0Cwu61OC3dLJOvPW7MZntWAq2Irt4re5A-YWlPz-ALMwLEKvVUJIvj8AG4gA) is a small example.

**Comment by kanoakliu** [comment]
> You can use the [stack property](https://echarts.apache.org/en/option.html#series-line.stack) of the line line series together with [areaStyle](https://echarts.apache.org/en/option.html#series-line.areaStyle).
> 
> [Here](https://echarts.apache.org/examples/en/editor.html?c=doc-example%2Fline-stack-tiled&edit=1&reset=1&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AI2ABXaABNGXAOKMQRAGaMANnip9SsCWEZEA2rUAWKoAA5XrEOAYuVOHAkHJWDgbbU7gFLk7gW0U7gU9NaAXRIBfdVhyHHwiVA0KajoAN2VhKlp_QNUOCCpCWF1-Yg10aEYAWxozQAQjQBK5Xmz0SOLaJQhoBMCNPALgYDAACyIwDnjm0jxtegBrOiHGUcrczWYdTIBGAAYeWAWAJlX1hdWAVgAWLYA2FdgADgBmU4B2Ze8B9EkqRgBlCiVi8JnYemAlTjorA4VCo0ESMz82QC2S-GnyRTogBCMwC0sdNcjU6PVGmiWm0Ot0yH01FVYBNRuNhiMcaQtPNdFdVgszptYPsLodYNcAJw7WAXLmnBlrJb3ElPV7vT4k9C_f4cOgCJTxcG5SEaaEaWGkeG1QDwhoBEFWp1UotSxTRJrXaXR6RIepMpFMmVLttL0Cwu61OC3dLJOvPW7MZntWAq2Irt4re5A-YWlPz-ALMwLEKvVUJIvj8AG4gA) is a small example.

Thanks for your answer, it really helps me a lot. I just thought of a stupid way to prevent discovery by banning all interactions with line through 'silent' attribute. Hahaha, how stupid I am.thank you again.
