### ISSUE TITLE
Data Zoom min and Max Values are not correct when yAxis scale option true.

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#19358]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/GRzwzGp

### Steps to Reproduce

Check the minimal reproduction. Data zoom min value is 150 but the y-axis starts from 140. Max value also doesn't match with y-axis max value.

### Current Behavior

Max and min values of datazoom doesn't match with axis. 

### Expected Behavior

Max and min values should be same

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
In the linked example you are not applying any min / max restriction to dataZoom.

In case you are referring to the yAxis labels not starting and ending exactly with the min and max values of your data, this has nothing to do with dataZoom but is automatically done by the `scale` option. If you want your axisLabel set to your minimum and maximum data values you can use the axis property [min and max](https://echarts.apache.org/en/option.html#yAxis.min):

`yAxis: {
  min: 'dataMin',
  max: 'dataMax'
}`

**Comment by abdurrahmanyildirim** [comment]
Yes, it doesn't work correctly when scale is true. Is there a way to apply scale values from dataZoom?

**Comment by abdurrahmanyildirim** [comment]
Any solution?

**Comment by MatthiasMert** [comment]
best i can come up with is setting yAxis min and max to the minimum an dmaximum data values: [example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2Srz8sAC2ENBEABR-gVQAlAgAfLCxSgB04dCOpKGMGNFpCcmpARl5GPY5QmCMAFrAwKFiIe4entR0eP4QAlQcwe2wzrh4AJLQfQWwAAw5Hv5UAGZgdIsrg-142sAA7gAiwibajAJ7REsBeFTzsHYk1jnXRlSEsKKtIYLCYgCMAKxzWAAJgAzEDgcCACw8EG_AAcsN-oP-SKhAHZYcCAGwzR5fDreWg9aDKEL3dC2OwAbiAA)

**Comment by abdurrahmanyildirim** [comment]
Okay, thanks for your time.

**Comment by MatthiasMert** [comment]
Actually [this](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAjAVgAwA0MATAMyEnEAsRxWAHEVqTk1QOy0BseAugNwAoQSAAOUAJbg0MAN6CYMAB4BBJRIgAuOQsUwoAT1EBTbQHJgSYwHMQAJwNmCuxYmTaMZgLLgnMMwAqAK7GfmYA6sZwYQEAFkFhAGJ2EmEAykjpQWBmvLoAvs6KBmoa2vJ6-kam_gBuCAA2IU4uMBCWDTVQdiFFMIW6bggAWiAgALYerRWVVSbmEA0ScMZ2LbNtsSAA7gAiSAhpsQhwO9oAZo0Qxn2VJeoQAJJgK0rahK2KnedQ5t9Q61mDQQACNjA1EvZxkgoKttLDoLd-rpeH1riljFpMNNPvADtohkjFIZ5v4lmBQq18ijBPkhIJztlgJJpAioAAKepNYwASh0ilAkFgoHGonAxjAUAgMgA8iCAFbGZkAOgl3QkmPZ4wMAGFjnYoMqAPoisUUyUQLwIUQ8oQC8DQGD3DQyU3ii3K84SF7s9kYMAIcY3GBG3h81AAPhgAaDyu9wCaKwg7LMzogZh5POwAl0gsdGHG3qI0KUvBkaeNRvGIBWDWVCAeyvajWMxuMSlhkrtMFzDpAnWVDRA1i13p5ugk5xgnMaITQqHQVqgsWVhbA7OVm6Gmf5ejsxigQTsYBga-71MUk-nXLnC8XSBXJY3W4OO5min3h-Pp4b590vcgftWyHEdtT1BADXHD8DyPE8b2MIR8iAA) might work.
