### ISSUE TITLE
[Bug] graphic组件使用type: 'group'时报错 Uncaught Error: Changing parent is not supported.

### ISSUE THREAD

**Issue by wyzhang0401** [apache/echarts#19360]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=mix-line-bar&code=PTAEGMHsDsGdIDYFMB0DIHMAUBZGBKAKEMgAcAXASxlAF5QBvQ0UcyRK0gLkeZdYBOlDBiQCeAcgCGAD0qwJAGj4tZ8gAqRK0cmJ5N-_cgE9SSSeAGRYC5YZaXrsAMonk-lfajpxoCQGIATmCJTxYAX09IiLtWdgQAI0gZD0MAMyQpcgBXAXNee1AAEyypADVKJAB3fVBYAAtIGsFspEVQPKkigHloBGMeNKkEWCRQcNjDAFspDEpwABVTfIY6xubyAVb2kzMeAG0JBG0kJT8EqQEJAF1xyf482DY82oamnk3Wu7C6qQA3JAAQVgAEkZqJXusPlsxtF-HCJnxkKJoEVUvwSuQpAcJABRP5SUiQARZajQM4SdR5cCUUiULFUGAUhZIKZmEk5PI3PiIlgyQFyWAHTwGey7fIScBZJAYYnGJQ_THY0CHPDk9oSBatCkAdSQRWZ9WyFIAYkIKc4shbsuTrvdVILNNpdL5RYVxZIGl0mqFCrz7GpYAt5gBrdGFYbCaA6-n1AAyUgSSAQ0O2PxYzrEBJToAADPb-MdoEhXMZ3AVCvxvMTJP4AEIADjrgLruN9lbhhk74z4dr4xgF8mFhjdRmWkmz2oL0CkUwlVKQNLpDLJCsKU20PHzPxmKVAACYAKzbwqZgTZnjHguBhNJnOj9LEmbkF2SBiTpDhUBTBDtrtRe4H1Ycc_A_Nd7BnOdJBZNkxCyXJTgLDdoC3JDZB4I8CzPC9QEPa9BVvZNw3sNInyyV8_HfYZWi_AAGgBhP94SiXtYlGIQkCFFURR-SCJXxQliVJJkCw9c5LnAww2A4WliMMD8TTIl89FANIbXARloFALAP3wCtKw6JBOS0j9QAAaj8b9fwAbnTHs_QLJVh0rfcUHzUAABYUECdoAHY3PafcAGYUH3QLDxQAA2PzIpQXz2gARiCiLotABLItcsLQCC1zUv3XMAtAWKPPaEKgp-a4AJ4wo-MkBcl3pYT1R-MSJAuK5RPiTg5P4BSlIotToA0sltN0_TKzyYzQFMiyJCsiRbIM7sYkVUpnMKXL2ginzQECQr92KwKGzivyCvitLfJSxKG0y9oPOO86EuOht2li9zXPKwpKq7QDeNnCUYPZeCuVEkCjhOST-AHQUQVRJA9wSzqZO4cb5OopBFIEZ8BvUzTRvRvSgMMSbchM9HzMshiFrs5bvkKJyVVc97QtKlAgrulA8KKtnEoKrL8p5g8QpKoXCvSznEqZ17Qu-5iWEq8JbMIZByFAeopFgAAlJA4byIo6FU4ZRlsqZjHo9WBHIFAYCwCQ8l1_UziwPTaAAPgrSg0m0gBCdWtZ1ooxH1QnPFGchgznSBsnILBBuGmhndRtWNe1h39foT4kEWrwYCeUA1QN03zcuK2oGgAFLYWSB1EoGRkywVZ-RhuG91zO4_DVCR8Gzwwy7zrUxnoIuLdLmAK_D6va_rxvB1BFut3bzVtW74hCj71X6iQYR6lVoezZHlBRHIAAJLeMB352e_4YeS5QMPugoMkG7sjASVIep5nWysibFMHX6j0gkMDIABIpDxxQn4PIpAEBgMQnZXuH8EBFHtl_AyLAf4GVakWOBaDKyUDRH4XMCUgG4LWISFY8C0EyASjwNUBZSGgGMDQ7K0VKEGRkPuWhMB6GkOMJw0AvlcyfQYfCHhBknhlgoSI-wTwrAhglAIDAFwsAJXOphbK50CoJVzPgEhDDsEABENb1AOFzQ8stpG0yWmIwoGDKxYIhjY08BCJC5n3HotBXo9hJwYdQngA8nGViYTwIKrDpGGA4f4tM4Sob8MEcIyxgTDASPLHY8RmxIDyMkIo5RqjwqlU0SgbRuikn2EMcY0xW0LEiKsR2NhoBql-jso08YK8fp5jaT2cI3cgA

### Steps to Reproduce

1. 通过graphic-group-children定义了两个竖线
2. 设置$action="replace"
3. 只渲染了一条竖线

### Current Behavior

通过graphic - group类型定义了两个竖线，且设置了$action="replace", 只渲染了一条竖线。
且在本地实现的时候，echarts内容报错：Uncaught Error: Changing parent is not supported

### Expected Behavior

期望是展示两条竖线

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
not-a-bug, graphic update works - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGAY1LA2HbpPRKVbAMozs8ohpIKcwOrHoBiAJx36PEgF9HL9E_WwDNaABNxHsTMAIKsbIQA2o4SGjJyioyiFObSXI7ovomMkfQAsjBclgAqAK7UhfQA6tS-FUUAFiUVAGLkFTqJ7SXQ9AC6npJ8bILCohYxxnGG9Gz1jL7AAO4OxoHGQ0UQCgDW4ukkjNiU0JUQYPUAMowARtTYhGCkZQMao7QAboeEAAwvkkfQah6aQGPbGSSmbDmBhWABCAA5YcFYQBRFbgtwaTHuYj9YjSULsSLRfZTBifbBlNLGaCMAC2034pGoCggIDOiSgPT-sDpwh-PLpLEIACYAKy_fZvUgUwgSnlDK63e5GcEAM3MQrAYwYSApZScvOw6Mk2NgaxIEyksmm-vKPNpDIYRWodLkpESJWZ1I0fOgAv2QuYorFPOlstgof2ipudzB6s1iR1lj1hwNsAADQBhE3OVy4zxsWgQajhWBRSRW9CO6Yoz4gcycgo8smWa6MUg-ySYHB4ePGO3NRPasSwNXdBSQGCwAAUdoAlKrwbBmWAvXA7bAANSWI30ADc-xxqx5mTA2XLR9gIoAdL9YAAWG82TiwADsd9fIoAzDeRV-xRvAA2V83yAm831fABGb9AJA2AoKA29_1gb9b3gkVvk_WBwIfV9f2_fZelcF4q1gGsGCZFk2Q5KduVJG0GHbTsWywXA2X7DRB2HZNx2gScuVnBcl3BVd11gTcd3oPdD2XM13FPLJiWXdDX0Al9YBsbCRVwr94Qg0CsMghC3zg6D4WQ18H304yoP0-FX3A-9b0I4xiNNUj9go4pXXdT1vRbRjLABe19gJMIAEk_GoYMENY3sOJEyRuNILVeInOihLTahFzIyQxNIDdsu3XdswPK95PNRTz0iW9nL_fCb2_Kyb1DHCmugrCUMwjrr1_PC-uwxDWugurHL_dy83QYinEPFAizATYGWAEowBnPiBOnGdcuIUxoDYMBYHyOBEDpaQszmUgwBvPb3loRbgH4CBmDuGckFgEJIui2LviqyxjvoedZNgPaDtgUpqAQXlzsu67bvuopHue173s-9got8GKfj--gIcB4HQcO-pqEoepDtOmGO2umgwAACRJigye24GzouqmbwWgB5cAuTexwKA9EB6i2ZSNDyjAgvoAWVpALsNAAEkYTb_UsZkQGwJXQuXO5XWoEQywrZckvBVt6BCuXlwgfxLG-KCLfBWZGHiY3l2YKDCGOnll2kd3UJAq9jGYEUPZgL3wWkYPYGJ0nDoAemvAPnDDyQDpBQxxeMA7lG2aZmVqZONBCgARRhZkiNqxUmo3zUTi1lwz61nbN4Qter2ArYYb4RXtzO5mdhvJDdwgIYLyQfcIb9_bbkgg-H55E7HyPo8Zw6ACpYCMsUF6q7fU9BF2HceYAc6YylW-n4vS_qcu1Kro3KtNK87-PEhJqcIGUA8BCoKBoA)

![image](https://github.com/apache/echarts/assets/13038071/14c08e61-9a5a-49dc-8536-f3fe9a3d1286)

**Comment by wyzhang0401** [comment]
> not-a-bug, graphic update works - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGAY1LA2HbpPRKVbAMozs8ohpIKcwOrHoBiAJx36PEgF9HL9E_WwDNaABNxHsTMAIKsbIQA2o4SGjJyioyiFObSXI7ovomMkfQAsjBclgAqAK7UhfQA6tS-FUUAFiUVAGLkFTqJ7SXQ9AC6npJ8bILCohYxxnGG9Gz1jL7AAO4OxoHGQ0UQCgDW4ukkjNiU0JUQYPUAMowARtTYhGCkZQMao7QAboeEAAwvkkfQah6aQGPbGSSmbDmBhWABCAA5YcFYQBRFbgtwaTHuYj9YjSULsSLRfZTBifbBlNLGaCMAC2034pGoCggIDOiSgPT-sDpwh-PLpLEIACYAKy_fZvUgUwgSnlDK63e5GcEAM3MQrAYwYSApZScvOw6Mk2NgaxIEyksmm-vKPNpDIYRWodLkpESJWZ1I0fOgAv2QuYorFPOlstgof2ipudzB6s1iR1lj1hwNsAADQBhE3OVy4zxsWgQajhWBRSRW9CO6Yoz4gcycgo8smWa6MUg-ySYHB4ePGO3NRPasSwNXdBSQGCwAAUdoAlKrwbBmWAvXA7bAANSWI30ADc-xxqx5mTA2XLR9gIoAdL9YAAWG82TiwADsd9fIoAzDeRV-xRvAA2V83yAm831fABGb9AJA2AoKA29_1gb9b3gkVvk_WBwIfV9f2_fZelcF4q1gGsGCZFk2Q5KduVJG0GHbTsWywXA2X7DRB2HZNx2gScuVnBcl3BVd11gTcd3oPdD2XM13FPLJiWXdDX0Al9YBsbCRVwr94Qg0CsMghC3zg6D4WQ18H304yoP0-FX3A-9b0I4xiNNUj9go4pXXdT1vRbRjLABe19gJMIAEk_GoYMENY3sOJEyRuNILVeInOihLTahFzIyQxNIDdsu3XdswPK95PNRTz0iW9nL_fCb2_Kyb1DHCmugrCUMwjrr1_PC-uwxDWugurHL_dy83QYinEPFAizATYGWAEowBnPiBOnGdcuIUxoDYMBYHyOBEDpaQszmUgwBvPb3loRbgH4CBmDuGckFgEJIui2LviqyxjvoedZNgPaDtgUpqAQXlzsu67bvuopHue173s-9got8GKfj--gIcB4HQcO-pqEoepDtOmGO2umgwAACRJigye24GzouqmbwWgB5cAuTexwKA9EB6i2ZSNDyjAgvoAWVpALsNAAEkYTb_UsZkQGwJXQuXO5XWoEQywrZckvBVt6BCuXlwgfxLG-KCLfBWZGHiY3l2YKDCGOnll2kd3UJAq9jGYEUPZgL3wWkYPYGJ0nDoAemvAPnDDyQDpBQxxeMA7lG2aZmVqZONBCgARRhZkiNqxUmo3zUTi1lwz61nbN4Qter2ArYYb4RXtzO5mdhvJDdwgIYLyQfcIb9_bbkgg-H55E7HyPo8Zw6ACpYCMsUF6q7fU9BF2HceYAc6YylW-n4vS_qcu1Kro3KtNK87-PEhJqcIGUA8BCoKBoA)
> 
> ![image](https://private-user-images.githubusercontent.com/13038071/288164823-14c08e61-9a5a-49dc-8536-f3fe9a3d1286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTk3MjAsIm5iZiI6MTcwMTkxOTQyMCwicGF0aCI6Ii8xMzAzODA3MS8yODgxNjQ4MjMtMTRjMDhlNjEtOWE1YS00OWRjLTg1MzYtZjNmZTlhM2QxMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTkzYTQ4MTUxOWQzNmVhYjE2NzE1OTRhNjdmZDY5ZTdmYWE1MGJkODI3MmVmMzFkNjdmM2Q5ZGRmMjIxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-JHDbvRuF0tz2wfnGVFoMY2G9wepSANiBCZ4RJ9Gw2w) 📌 please close issue if problem solved.

非常感谢
