### ISSUE TITLE
[Bug] line breaks when zoomed in/out (bug since 5.4.2 version)

### ISSUE THREAD

**Issue by snukhulov** [apache/echarts#19376]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/echarts-data-zoom-test-xdzyxj

### Steps to Reproduce

1. Zoom in chart
2. Zoom out chart
3. Repeat until there is a line break

### Current Behavior

When zooming chart out
<img width="1192" alt="Снимок экрана 2023-12-09 в 18 27 04" src="https://github.com/apache/echarts/assets/36777577/2d2667aa-4136-48e6-8677-0723366a328d">
suddenly line breaks
<img width="1194" alt="Снимок экрана 2023-12-09 в 18 26 53" src="https://github.com/apache/echarts/assets/36777577/62f31e05-359e-4bbc-affd-ebf125462bd0">

### Expected Behavior

Line doesn't break (like in version 5.4.1 and below)

### Environment

```markdown
- macOS Monterey
- Browser: Chrome 120.0.6099.71
```

### Any additional comments?

There is no such a bug in version 5.4.1 and below

**Comment by plainheart** [comment]
Fixed in #18960
