### ISSUE TITLE
[Bug] 仪表盘的progress值在定时器位100毫秒的时候会出现值和进度条对应不上的情况

### ISSUE THREAD

**Issue by lightman0215** [apache/echarts#19378]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=gauge-progress

### Steps to Reproduce

1、创建一个仪表盘的图表
2、通过定时器修改仪表盘的值；

### Current Behavior

使用定时器setInterval每0.1秒修改仪表盘的数据的时候，仪表盘的progress的进度会和值无法匹配

### Expected Behavior

我希望能够在每0.1秒的时候的值和进度能匹配上

### Environment

```markdown
- OS:Mac OS 14
- Browser:Chrome 120
- Framework:React 18
```

**Comment by helgasoft** [comment]
disable animation - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=gauge-progress&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAEYAHAAZ-1dFmgATCdNkqB6ALYRoxfWtiG2AD2IAmACzm1GEFIhgAch0MAjXMRydqpqIDjALDgERJQW6BgAFsAA7sRgOBxYIRbhHFoAwmwgaRlZBhTJEJpgCYEK5QC-2RQgwCZgAbFxEADGMMwgbDWEAPQjALJ2SgCcSgB0AMwAbAsK07xLcgCsizPT07AAMlOziytrG9u7-wf5J3JzDgoLAOzBmzsLewcndo9KqwWlyWczk0ycdgUsF-jyeW3WmxeiyC0y2SyOJxBsyW0wUvDeCjmLy28LstxOSKUW22W3xCz-y1RLxe0JmDjmdgW0yBLwWOwcciWdiCrNOQrRSzpOzRSheULuM3mW1WDlpvOlSwcdhxovmqrkcheUrmEqUcgcurOq3W6pNSyWZotx0VVouttN5tgCoUIJeDl5kvd9sdrOecwUNKNvL-Ky1C1DC3DkfxZLmZpeOLsXqmYYjJKjkLm3KUAqzOcTEejKcJCgcC095fDObk1aJJOmZIxSgUhLsLw7lyR9bJaOz3cJ9K5ks2ILBEKhOemHIcTiNH2u-0ty2tl0-31gAC0-OV0DJJMNYExiQBSY9xWCVaq1eSSk-wYAAMw_2DA-Q0HRwYgSBUS8tlvABdRpmnQGwIAwQ4TFkVB71yAoihKTJoIodxoCwABlOgZGIZD7wfKoL0UN8Gig8pYIwAAVXoAGtiLfVx3C8Hx_EA6EsNPRCCNoIiunvR8L2CN90D6KRgB4pgAGIbiYKiaIsdiPAQ3DWPvM8WAoiSdIEwikMksin2IIFTOk2TmEU_ZlPvaiLCaWjrDgw42H8KRtLiTQ4OEaAelkL4-Ngay5Ls6Y7ziD8YDAPCIAAL1kKZVLUSAwGEki1KSVJYA_NgpGwNLqE0LBhAgbyRLUXw2B6JjImAPJNHyYAZIir8P2iixfFksqcFa9rbKU0LepwfqAHVyOfAy4jE58mAdW9QpwrAAAksAgFgEjAYgnFChJNu23bYH2t8xv6gAlNg_I4GI8TfT9v3Kv9oAAoCQKYPkINCgA3QrMgkCArEgfoaFKULYpwEH3vyvIelBuAAAp_qkTIAEpqpycqOBwOAmCQVHMgAHyYWAAGpYCJrA5jAYAADEIGsLBNCRpRMcppgGiQPIPGJpjDBGBIGiYABuKjQrwHpn2yuJqZ80j8rihLkuILZnEV2K3omo6duYXqpH67rSPC2zmReBzSJcxXeZO2X7y1-KkpSjWTbamzL0i4370GTQ_MkD7eFgECAFopiDuQlEgxWnLiWPqGttRNCGNggLfe21Hl-QlCUFSLHArC2GgYGhigUwCqKrABFjyCGnFj94cR2BNAZ8rpaRzGSMMWh8gSEQwDmH8AHlwDLpGkEwXB8BiCeBGT4QgMJgHZEjpRyfGIYEjmHAi5bwwO4AKicBpwNgBoz_R8XqJ_ABJN7cFRpGW_ptuEgjnP0aAA)
📌 please close issue if problem solved.

**Comment by plainheart** [comment]
If the animation is required, you can set the option `animationDurationUpdate`  as the same as the timer interval `100`.

**Comment by lightman0215** [comment]
thx,it's worked
