### ISSUE TITLE
[Bug] `layoutIterations` not working as expected on sankey charts

### ISSUE THREAD

**Issue by Arch-Storm** [apache/echarts#19375]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoAzgUwE4Q2gXLANoqxnKnllgCeIGhARGgIbQDWGNjANJVRgC2IABYs0EAhSpUAZsADGAVymMWAEwBWLBRmgLufGbAC-RmdGDqMAcRYhCAFgAc5qpesB1COrAjCAMwATG7kADYsNMBKYACSYNgskDBSwaFk6kkshCTGZKh55NAsggywjACyAMoASgAKsAAkAIzOAAy8_HkQCYJVtGFlBYXkCsBhwFhMAEZhShidI6bp5GZdVMOFxaVMAEJKYeywdTi6Tc2OHStUPUL9NIOEmyNjE1Pls_OLI2uFv3nPYzbMqMAAqwDALDCsAAwsA0GA0OdmgFvoVbn0BkN1nlXpMmFgMOo0Xl_sYyTJARYSiCAGosHAsWYYWHwxFNABsAFYScYMfdHtIlrA8e9GITiddVlKKRsce4aUwAGIQAAeRNZCKRjRcvJk_KxT3lMlFBKJeqosulxqpCp25ROwFkPVgFQZAHMIHBGkEAOwW8gGh7Y4Ui8b48ruwl6ANkK1xqW2oqK8o1DCQiDQt1YT3ey6x2BBwVJqim8oGNgF-PLHEAXRWYS97CkuQBsDQ0SwuiY1Xq53avFgkJz6b2ByOJwgZxa-Z4sAAblD5oQLm0a4UkO3O93yr2Gi0B3Ph-7R6n0yxM66PV6mrOF0uypd122O0ouyD9odjqcWTOrkOPVPMEIShTV2RaFFB0XOYymaFFn2MTdX3fMcv0nadV0HY8gMdZ0wCvHMbx9f052g5dYD9BDKS3N8d2AyFoThLVkVRI9ALAJh6UZZkwO1bkoIfQhuSojYaJQ8pwQY3iWKw9jlTVDUmPA3VSME2AXBE2B6xxRtoAwAUQ1xcMxSjDRcGgMAA2ULB5z0PApDaAA6LkVitItDOMMtGCjLg9StCJpgwMIjUKLyc2mFgAAo2h4GK4sc30AEoA3kCylRKTMaCYABBRkwhSmAwCqCAAC9YJinEKX-bSTCAA

### Steps to Reproduce

1. Use `layoutIterations` > 0, where a node with a higher value should be below a lower value.

### Current Behavior

![image](https://github.com/apache/echarts/assets/42775469/9eef5971-f4a9-4121-9fe6-4c2da9fb3827)

### Expected Behavior

![image](https://github.com/apache/echarts/assets/42775469/ef83a129-03c0-4c69-961c-3cd091d59558)

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome 119.0.6045.200
- Framework: /
```

### Any additional comments?

Another example of a similar problem, where layoutIterations fixes the ordering but aligns everything to `y=0`.

This is using `layoutIterations: 32` :
![image](https://github.com/apache/echarts/assets/42775469/e2706153-7f98-438d-8b12-b23b9901e701)

Using `layoutIterations: 0`:
![image](https://github.com/apache/echarts/assets/42775469/fc0657e2-cbf7-483d-97e1-7151adfba209)

Optimal, but currently impossible (to my knowledge) behaviour:
![image](https://github.com/apache/echarts/assets/42775469/e872cf48-1ba0-4a2a-8577-9e78877d813a)

**Comment by MatthiasMert** [comment]
>  where a node with a higher value should be below a lower value

where did you get that information?

**Comment by Arch-Storm** [comment]
> where did you get that information?

I'm not implying that that should be the default behaviour. If you look at the current behaviour, it should be visible that "retail margin" should be below "net profit". But because "retail margin" has a higher value it gets placed above it, also causing a lot of unwanted overlap in the process. This might be good in a lot of cases, but in this one there could be a way to preserve that order, without having everything aligned straight at the top.

**Comment by MatthiasMert** [comment]
I agree that the algorithm produces some suboptimal results but I dont think this is a bug.

[Here](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoAzgUwE4Q2gXLANoqxnKnllgCeIGhARGgIbQDWGNjANJVRgC2IABYs0EAhSpUAZsADGAVymMWAEwBWLBRmgLufGbAC-RmdGDqMAcRYhCAFgAc5qpesB1COrAjCAMwATG7kADYsNMBKYACSYNgskDBSwaFk6kkshCTGZKh55NAsggywAOTqSoKCNACM5ekyEAmCAMq0YWVICsBhwFiE5WBYbGggLFh6YOVm_HkRAEYYYYRIaCLAAO6EsixhmCbzVHOFBYWwxaVDVTU0QY3Hza0dNF1rvf2DFSNjE1PQGanC5LFZrDbbXb7Q5PMjA4znQpXMqMACybQASgAFWAAEjqzgADLxYeQWkJXu9pBcyJ8BkxFmElBgSTT4TJ2VREXlkUwAEJKMLsWBYnC6PF1RzEppUcntTrdUlUOnfRiM5msi6c8ja_JKy4lFEAFWAYH2sAAwsA0GA0BK6gFNYU5ZTFTTaX16bBGFN1E68rrTDLqUjDUwAGqTCAsRkYS3W214gBsAFZ_cYXQq1vqPV8mL70xzg4HucZed6AGIQAAeGHU8ZtdtxLkLspeWZDFxV-brrZ1xeDpYsYe9ouAshasFRkwA5hA4LiggB2PtkTNvN3u7vemdTPSroOkkv68uMDEYM0QMJT2fzvFSg_rqlD4zbxgGNgHwPagC6TTC87sFIuR5EgsBoNEWC6Dc1S1A0PCwGaWAzheTC3LUQS8LAABu-zMoQhKHmc4GQdB3rotiEpElhSEoWA_KCsKooQOK-IPghuFMmUkqESWJFKFBKIUTi-LUQhtGod656Xte07IXezbSjheFlFKRGgfxgkMUKIpinGbFKRJ9HeiaZrXlajb2o6HEqYQdQOupCKaWRjACjpzGsTxNGzpJjBjhOYA3vJC7LlhnH4bAy6OTIYEQQJLmmeaFmJviDrechvmRjgMZdA2KWpmFtmwKm0Vcs5xqmklCZNvZ1mIT5xmMFWtb1slTYtjZXFOM4pWwH-TwAdAGCutmhRvruGi4ICfbKFg2F6HgUiEgAdCmTTak-m6vp6qq7lwhbaqCqydsqO35jOiwsAAFISPC3fdy1LgAlH28iAhWJRXjQTAAILZWEr0wGAbQQAAXtxt1POywL9SYQA) is a hack which may lead to preferable results for you.

**Comment by Arch-Storm** [comment]
> Here is a hack which may lead to preferable results for you.

Thank you, this works for the time being. Using the nodegap to space them is quite clever.
