### ISSUE TITLE
[Bug] In line chart, using encode.y with Array only write one line

### ISSUE THREAD

**Issue by LiDopamine** [apache/echarts#19379]
### Version

main

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/basic-line-chart-forked-kvwz55?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq0byf7s00063b6lzram9ogm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq0byf7r00023b6lmbquofog%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq0byf7r00033b6ly1ufl9bu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq0byf7r00053b6lhg4qsmua%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq0byf7r00023b6lmbquofog%2522%253A%257B%2522id%2522%253A%2522clq0byf7r00023b6lmbquofog%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq0byf7r00053b6lhg4qsmua%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0byf7r00043b6lyes9dsrp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq0byf7r00053b6lhg4qsmua%2522%252C%2522activeTabId%2522%253A%2522clq0byf7r00043b6lyes9dsrp%2522%257D%252C%2522clq0byf7r00033b6ly1ufl9bu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq0byf7r00033b6ly1ufl9bu%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

nothing

### Current Behavior

I'm not sure how the line chart should be shown for encod. y fill in multiple dimensions, the examples in the documentation are supported for this. However, the actual rendering result only renders the first polyline.

### Expected Behavior

Multiple lines

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULTsAeBBbEAzgFzIC-ANOlrAJ75GlKXVYAmAhmB4QKZhNWNTIWABXAE4BjXqQDaQ4TTkBGCrABM6gMzqALOoCs6gGzqA7OoAc6gJzqVABgC6VDEuFytsA7DOwbWCcHbxVfFX8VQI0XNw9Pb397INDjIOi1TV8NS1htWMV4uTTAlVD_GPUNbMDtb21_PQL3eMxih0cHNMrNNPydNKb9NMNm1qx2lIdo3368xu89QMNfEzHx2DlksKrMjVrBxeTDfxNdWHN18a2HCtnFzp9l099zbysr1pv0qtyG4aMq3Ob2smVsnyKyR6cyGsFGpkel2sj3BHQhWFcihYLVgYGAwAANpAQExsTQCbwAOa8aBsUluMgAbnQhEI8DkzmZaFAkBgADpONw-GA-aJJDI5C4-QBbDggAAU8uwFAgAEoEAA-ZCsVl8kBiQgAC3lSFgijAtBAslgACICRBoLwbepoBxpdaIHEsDSpMA2NakNhSJlaPIIK5cfiiRASZs9jp9M5YGRWGRVeg01yeVBoKLeBIILxCAhYKzGUA)
![image](https://github.com/apache/echarts/assets/13038071/02fc5acf-875c-46e5-8cdc-4ffedb219648)
📌 please close issue if problem solved.

**Comment by LiDopamine** [comment]
So we can't draw multiple sets of lines through a single source？

**Comment by helgasoft** [comment]
Since I do not understand what exactly you are trying to accomplish, here is my second and [final guess](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmAJ4gCmRA5AMYCGY5A5sAE4lUC-ANGrCTnxEkPPgBMGdPOTDC-6PMACurGpVgBteek0BGbrABMBgMwGALAYCsBgGwGA7AYAcBgJweDugAwBdA7AA9IGwYAAW-LCRABqwdLh4sAA2dABG5El42ugaxrCWsPawrrA-Xnm6BbpFuiWGfrw6Orl27uVeNqV1-kYFhk6wJg3Zmp0luhVF9QaGfSUmeSZF5sNNOZ1lpZ3TRp1Dpp0rFp1Wq2saGxV1BfuDy3nmJVYFtmdNGm5efT2G84cPn1gViKtjMsAcb2agOqMxuD28FieIIKDjyzkhOWhdQGS2O1heYNRLh6bgxmkBO1uRyBCMKtIhLlppK83khvj4onQYGAwCSkBAwk5yWY5GgYkFKE4AG4UHhEogNL4ZaBIDAAHQSMBSGRqxQqNRqgBmbAAonQaGEABSWjAASgQAD5kNo5WqQEo8FakKEyOoqEkINByFQDNJWBByHgADJ0EjKMAAIRI1FYwAA7lRYJxbTLs8rwFBoLryOHIwhYHKpUA).
Also see [official example](https://echarts.apache.org/examples/en/editor.html?c=dataset-series-layout-by).
![image](https://github.com/apache/echarts/assets/13038071/97c91265-2bad-4fa2-b7b4-cc7537372ec8)

**Comment by LiDopamine** [comment]
Thanks for your help, I'm trying to see if I can set multiple dimension values through encode.y to draw multiple polylines under one legend group. Because ecode.x is to set multiple dimension values in the official website [example](https://echarts.apache.org/zh/option.html#series-line.encode), I have tried many schemes locally, but there is no way to make encode.x or encode.y fill in multiple dimension values to be effective. I would like to confirm whether the echarts supports drawing a group of polylines through multiple encode.

**Comment by helgasoft** [comment]
> multiple dimension values through encode.y

This is for chart types like _candlestick_ which need multiple values to represent one single element - [Demo](https://echarts.apache.org/examples/en/editor.html?c=custom-ohlc&code=GYVwdgxgLglg9mABAZwA4BsZQCIEMq4AUATrgO54ECUiA3gFCKIQLJTP4CmA5nMQJ6VciALyIA2gF0A3I2at2AN1zoQnZKIky5wPokLLiiGJoAM044gA8iUhXy4AdOk5huUABYWYAah80GJiYILl4BIUdUEGQPEnIhcRhJcVNJKlkg23iHROTUzRgMoOVVdUjo2LsEpPS5AF85Yk4oEGIkQKCQqB4-QQcALg5usL6CABo5JhK1ZEHp9XrZBoASR25mwgAlAHltgBUAfQAFAEE9gAlEH0QAcgB6ABMHO9xkZGbH57Y4CABrAFpsAApACSjgAVsgEDcxohQJBYAh9FUHAE5IZEE8CJo0JgcA44vZqEUALb8ADCHlwxCgjneUG2qERYEIk30cCZ8CQYg6mVwYBgJPwXMGwBU7wmmSYLnWYAeg15UoARnAoFA4CTBgBGUySqXSzjAKCDG4QVzdYgwtmZLG4QbiG7YOBkf5AhDqYxyzgADxukmtiDqesy6rg6FgqAVAaYUGIMG462IJtw3pgyCt-qYKbTRzgMDAFqjmaCUH4qE4JogxDgbxu0cDwalqBrWBFcPA0C5-mbyFhqGpuBJvcQnHQsNHm040FhyBgAC9OGji1NqYg4ErwZpaIh1ZHEDrA0Vi-vweIHS4jTDbnHuB4oH7xD5CD2UpJrCh55xHIoYJwyABlT9X0QO5EAAJioSQ3zEABmcx6yYJoWjaNcNyPKUGn1IMA2zZBc3zQs6HrTAwF-e1t29E5U2QEEvW9ZN0HQG5A39LDGxjOAwxVeiiOLYBOHwVoK145dbQALU4zUROXRB-CotNaIeH1RXFTgEIbdSlWICoixkncy2E89804AANK9TRcak_XUzDM1szJsP1bg43lCR60VfUL2NW4dQAUgzZcbzvE0AA5_PY5VVXVKStQAVlMet7KCSQIso6j7Xc9TS3LStQl6ALi1tQZbUcLoenCBwIsyFVwCeAQAHFcD3MV0AldTcIAGWMhU1zAMTOGrFTWs4DSZNxLAurAYTtxiZ0hveUblxJfMTVtABZfMCszIUeJudaUy2_VcPwgsBt0mS521UwEpkpKHIDFKAzk9K3OLDypWQEIXEGWM1CqoJxqgE4mjtaTl1msgfu0tTbsSh6IvEySMrerKDJNfNZyUw6PoIGlBgAThC_6mFcVydV1dTlrAAA1FQ1H_fswCuxL_vezIIahv7UZy25kEwJTLWJxAVTVDVBgANgpsbce8wmhdJq6paW_NadKBn-WZ4s7sQR79XeON1GRzM2aCMBB2Ex1nVdd0NHzJTfSF7KLZCOUXDYGA_mxm1BVcWdWHtG5_nMjlXHMiB0BrThzIjsh1HvWEbg8eMPDjv15cgOAlPO5ceKVmT-HtLVYTA2EYNhAAWXW9NDcMYD3cQi_A0uK9Y5dHNEgZMQcb86YWLWHrZOoqEbX6YcQWoh-kIA)
