### ISSUE TITLE
[Feature] [Question] Prevent scaling when zooming in Sunburst Chart

### ISSUE THREAD

**Issue by comfycush** [apache/echarts#19370]
### What problem does this feature solve?

I'm trying to create a sunburst chart which needs to be zoomed in or out. When zoomed in, it scaled the size of the chart which makes the text overlapped. Is there a way to prevent scaling when page zooming?

Zoom 175%:
![image](https://github.com/apache/echarts/assets/72155210/bd670356-c2a9-43b5-9687-e2f9d22983f0)

Zoom 80%:
![image](https://github.com/apache/echarts/assets/72155210/b5d6d745-679c-4a7c-bb63-07778d9dd131)

**Comment by dberardo-com** [comment]
can this be prevented on line series as well ? so basically scaling the y axis only at first render and then leave it as is when zooming in ?
