### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by cxf1112** [apache/echarts#19380]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/p/devbox/echart-test-zdml23?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A12%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq0cltr40007356khp6ts53t%2522%252C%2522sizes%2522%253A%255B65.42790151921454%252C34.572098480785456%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq0cltr40002356k63s0n6u3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq0cltr40004356kud90kuhf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq0cltr40006356kqq34ove1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B45.37501913066445%252C54.62498086933555%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq0cltr40002356k63s0n6u3%2522%253A%257B%2522id%2522%253A%2522clq0cltr40002356k63s0n6u3%2522%252C%2522activeTabId%2522%253A%2522clq0d4zr6011g356kssin268e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0cpmz20002356klspwjy6y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FHelloWorld.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clq0d4zr6011g356kssin268e%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clq0cltr40006356kqq34ove1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0cltr40005356kksh4j4sr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq0cltr40006356kqq34ove1%2522%252C%2522activeTabId%2522%253A%2522clq0cltr40005356kksh4j4sr%2522%257D%252C%2522clq0cltr40004356kud90kuhf%2522%253A%257B%2522id%2522%253A%2522clq0cltr40004356kud90kuhf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0cltr40003356khmtrlduw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq0cltr40003356khmtrlduw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

echarts 使用 echart.resize()，响应式展示报错。报错信息：Uncaught TypeError: Cannot read properties of undefined (reading 'get')
具体查看控制台报错信息。

### Current Behavior

![image](https://github.com/apache/echarts/assets/17537862/f89f413e-cd8b-40a9-87f1-ee7d82a8d388)

### Expected Behavior

请帮忙看看是什么问题，目前找不到解决方案？

### Environment

```markdown
window11
chrome 版本 120.0.6099.71
vue3
```

**Comment by plainheart** [comment]
看代码对整个 _myChart_ 实例对象使用了 `ref` 导致被 Vue 代理，影响了 echarts 内部属性访问，考虑改用普通变量或 shallow API。参见 [FAQ](https://echarts.apache.org/faq.html#others)

**Comment by cxf1112** [comment]
感谢大佬指点
