### ISSUE TITLE
[Bug] Shadow config doesn't work in graphic.elements-text.style

### ISSUE THREAD

**Issue by AngryFrog777** [apache/echarts#19389]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.4.3

### Steps to Reproduce

option = {
  graphic: {
    type: 'text',
    left: 'center',
    top: `50%`,
    z: 100,
    style: {
      text: 'some text',
      font: 'bolder 36px MontserratAce',
      shadowColor: 'red',
      shadowBlur: 20,
      shadowOffsetY: 20,
      shadowOffsetX: 20,
    }
  }
};

### Current Behavior

Shadow doesn't work when I use the above option.

### Expected Behavior

The shadow works as the option describes.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
it's a documentation bug, _shadowColor_ should be _textShadowColor_ - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnAhiAFhAMYBcya6sYAniAKZkDkYdAHmIwDQXoA2dAMzBMidaCyxceVUEwCsABgCkUyrABeZAIwKF3NQGca_MqjXoW7eQDYQrKmw77zAmMNiMARsF4ATOliwcrb2ALJuBgG4YACCoqrmvBDQdADqEL5g-GQALJywRljAANYMHlh0vlywAhC8vEyevACudAlqlmAAyvg4vsAA7gDCPsBYTNR09YPtlJ09fYMAQi3jsABMzh2OC_0DAPICApFgAJpkAMzSAL4Ut9cA3EA)
![image](https://github.com/apache/echarts/assets/13038071/fdb7a306-3746-4899-9299-9f41eb471ece)
