### ISSUE TITLE
Boxplot doesn't render layered with other chart types

### ISSUE THREAD

**Issue by dominikj111** [apache/echarts#19391]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/boxplot-layering-issue-h4zx3c

### Steps to Reproduce

Just follow the Minimal Reproduction link.

### Current Behavior

<img width="694" alt="Screenshot 2023-12-13 at 06 03 52" src="https://github.com/apache/echarts/assets/7355912/f6ba3e38-299e-4ac6-8fa5-c8edc8aa7e12">

### Expected Behavior

<img width="692" alt="Screenshot 2023-12-13 at 06 04 35" src="https://github.com/apache/echarts/assets/7355912/6bf77e1c-2dae-4258-a54c-e67140b939ef">

### Environment

```markdown
- OS: macOs Sonoma
- Browser: All
- Framework: Any and vanilla js
```

### Any additional comments?

It works well on Apache Echarts version 5.4.0.

**Comment by MatthiasMert** [comment]
You can put them on different axes or use axis type 'value'. 

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFywDaa6ylVsewArgE4DGBpFttZAbAOwAaWHwCsQvj3EAGIQA4xw2eMmKAugJpdeg4QonS5epcJV9Z6zd37i9pmbHnjj-tZdirNAXw21UXWABmTMAAtgAiOPhEAJLQGAQAHqQybmBMWNB4AcBMIaR-_rBgAJ4g7LAA5ABGwAkgADbAYBVunl4-VAW0QaERuIRgsfFJsACMHd3BIQAq6ZnZuQBKBHgM9SRj7ZpdVPTMbBxu6GT2sgBMFoXk9gCcUpeFZOPCACwP_k9yAMzvWmdy9wmfyENz4Hn84KobXQDwSAEEEhA8BwkCUyqQKiwcAQAOY5YoVbzINHlTHYvFMAlCPAAC2AAHdSAEsPVCJ4HsUEUj8t5KIQmBAVodfG54Yi8ENEqRxm5oFgQqSanVGs0gegSRilQ0mhU1ZhIgNJSNRlsRf45QqMdhcKNdalSqS8FiwGACEw7f5rVFBnEpbAvnqxUijclTZ1ZfLSV6zh6uEGJb6Ril_BrKvUINACLHaF7DYnSF8vJQPJ4ANxAA)

**Comment by dominikj111** [comment]
That works for me.
But still, is it not a bug?

**Comment by helgasoft** [comment]
not-a-bug
For a single **category xAxis** to work in such mixed environment, it needs **data** - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=EYBwNg9gLgBAvDA3gKBjAzhArgJwMYCmAXDANqppkBsA7ADQw0CsDNVrADAwBwuPet2_ALp0KaUrVZ82nHjIGMhNbqPHV6jGcq4xerRbJEVhyAL4BuZKDAEAdvDIA6FwEEcOAIYBPABQ3oJ0xcQidbOwBzKAALAEonAGsCb3RfWOErZAgQKABLCAcEFDQAD1cS3PQSRBgAE08oTxIbexgzBgB6DvhSLgBGOgAmUzRvcsrq9op6xvQCKBJyShgAqDFl4uWYADMcCABbABEGzzmoAEk7WoISki51NCgvO3RtiBx96ofKKG8QYhgAHJgBASuBoIDvmZ1FMNt9dgdjrN5pdrrcYAN4Xt9gAVZ6vd77ABKBHQWDACwxMPWlE2y2C-ABSy2El03GGNJZvQYAE4OGoWRIBowACwCwWkYXcADM4q5gx4_M5W1ICpgPJoIy2WrQ0LQ4rmOFypMW6jplDsnn2AOBoPBUEBysefxtILBkAdTrqJzOqJuJD61LN30t1pIgJmnj6ju-v3-4fQeAaUAIOBjLMjvqu_pg0qDcJZoZtkcG6a2cZtYFydgIZeWmZR2fReeWepgpksQA)
