### ISSUE TITLE
[Bug] label is not works on custom series chart

### ISSUE THREAD

**Issue by umutcantopal** [apache/echarts#19405]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=pie-parliament-transition&code=MYewdgzgLgBAJgQygmBeGBtAUDGBvGANwQBsBXAUwC4YAOABnoBoYwEBbamAcgEFuYAXyY58RUpRoA2AMwBWFm041uAIQHDRBYuS5yGijl24BhDSNzaJXACy0bh5TwAi5reN00ZjR8YCibpYekjAATD6sRioAYhpYALoA3FigkLBwFABmCGQkUAAKpBRQUBRomKIA9JU8AMRyAIxStACcAEbcLNy1wBRywP2ddZltwPIA7EPdtCOZM1O1UnItcPYLI7QUUggLwOPjobS0C-O0UvQt9AstDcA2AwvNl207ot1yNuP0wFKdb7U3YB7OR_XDdbLAWj6UF1ChbKQImHdcYyYD0DJI2oyF6hA6YzKQmxyUKYloIc5tGyYigIcZA4DcBLJVLQGAAJwQcAAlmQIOUMNxvABSKYMEVJFLgVkABy5FAA8tKoFzwOU8KIIBQ2XKIDRsLhLKIDTAoABPaXGWUUGHGrlwFTc6DatpkZXgG0Gjnc3k0L08iAWY0wEgINoUEg0dVBg0QAAWIAA7jQoGzKEaDZpo2QwFzCFqIKQACocyBct1gZOpiiB40IHPsJAqsDOMgc8sAVWliFKNAajGY6dw3YQNGH6cEoniWEEzKlsGlCDZJC5RjAUEV5fKAApMtngJutwBKfCiEjFGAQMjscrDgB0bIocDIvR3e4Pl_YLGArePUc9xVbMALyvGAAGoYG_Nlbx0ShklwYQYHoQ84ODc86wAczPPl0AwCVcDPWBoEXKBeDATCynQABaABZJBY1vfIAEkYBqUIUIIiDW1I8jyiItkSLIs8ULvTIQDZPwEGAWNXzAfcmxgLcywodhf3TDCsNvaVeWkyDuLPZD010wSylA9BFNKdhoOsFjgJUmAACoYFoqB6KYhywhQwQDNwdSKAgTTtK3PiBJ48DnNc5jHNCbyYF3WTNwXJcV04NcABkEFNEBXSC5B-L06sYAoMA4HylgoBAZASFK9lmHZBoWAgLkAC8KFU40OLZRMIBMLK13KcLb16LkSC3Lc2QaGBKJq48akalqYvw89pRALk12wzA8INDryjZegUNwUS2QUjiuXKPaYFOgAedkup67MoESC7QNAtqg2qGAACUKGAUhvxDUoL2aihB1Q2Bysqj7VvQgBlGkoAgAA5K8wyO9ABs67M4FG8HSHy9y2RmwH5v2rbzzACgE2hoHtxxqrjPxwnachsjYaQRHka1EmDrEhSQcW2AAGt-ro29MhIEAxNG4K8ccgmbPJymgePRyFaplquYNIXroGsWJbZUaipK-nZcJ1Wlfcs2WsmmAGgoSipA13AhdM1gKbV4Ho1e6MON88ohZqNlHdBmAAA9hZcwaQAgLdfOV9kg4401w_oxqwBj4y48DvmYGW1b4YCuMtwwEOWFNeIFozEGjpduaKBJidjQfKBAJzla1s80Qm5bv9cE1bU_MjEGzQtFRv2gEB2A9XA7QdLknS5F1yyn-AkBHFfkBrLbQ3DQfo17-MkxNKsQczINQDE7k2FKaHTWgZSaExrJVsfTfcGzXN8yLEtGvLStKFfmAdYuQNnLC2NsTZOzdi4H2HwVdDZakYhZGgcU5Kqi3IlDgAZAGyi9kGYgR07Rh3QBg9g_lhyMWKhQEOQd8FEDlIrK2aMRbsFWjHWUt50LFAAOp2hckeFgCB2GcKgAACQoFydCsYoBHgrsaWhu1tzoMXJqaI4skBjU5P6DA9By42RgXHQg9D3aEzYtneRE0zJKLZCotR0i_S8gwA0XRNR9HuUMW7c2rEaGLggkQ7BXIOHcN4dJOO9BbxyG8UdYASd0CCICcIsREipFHncmEiJZifG13KO4hhZQahyD2hko6uc1rlESsuVcUB0qZWytnHyxkIAYEIfEABtYGlNLgGHcCTjWkGgGm5KKvTcC7SGXVUZWTwIyGzrI_8zc2RAR7nvYexh0IY2lMvY0UlhpwAfBWVued_INmlDJVBQF0FQFwXvdkAF5kniudGZZo8uRsmAGeDZe8cjlVUEgKSf9qx1KDHGQRXBFn3INMAEONAIVgRzlAbRLSAXRmiVCpO4ElSOIRWC6MbIaBZNYoijMozjTQFNGeXeWLjSZGGhGeAWQch5EKARUoHSw5ClpdkXIBQiglAoLeM8ZEXJTgpfBAlM4AVeWzmK6MDdK7wWSF5I8yQOKQV2euJU8kzIgHVaqYhcoNxNgMpqKAFDShsh0Ccg8r0VVFTVZudA1q1z6p1agXVCptVAQAPw50XBUlKtr5I0CtE6sAKF2CmhMLGYit4jXBq3A6_14ADIIXCIwZCQA

### Steps to Reproduce

set series.label.show to the `true` and series.type must be `custom`. 

### Current Behavior

data label is shows up with pie type series but not shows up with custom type. 
![Screenshot from 2023-12-15 08-55-36](https://github.com/apache/echarts/assets/92383753/48ab6564-7aa9-48c3-b926-e3272d0f3c76)
![Screenshot from 2023-12-15 08-55-49](https://github.com/apache/echarts/assets/92383753/9aa72222-ee16-4e03-a8a7-5207497182ea)

### Expected Behavior

labels should be visible as pie chart

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Browser: Google Chrome 119.0.6045.159
- Framework: Vue.JS 2.6.14
```

**Comment by helgasoft** [comment]
Nice morphing, but a **single label** for a set of custom scatter points (type: 'circle') ?  
That's not-a-bug, but unrealistic expectation.

**Comment by Ovilia** [comment]
@helgasoft is right. This is not a bug. You need to add a `text` element in the returned group of `renderItem`.
