### ISSUE TITLE
how can we set the height and width manually ? 

### ISSUE THREAD

**Issue by neonarc4** [apache/echarts#19409]
### What problem does this feature solve?

it solve me my complex resizing issue i need height control but it lack

### What does the proposed API look like?

need props of height and width

**Comment by MatthiasMert** [comment]
On [initializing](https://echarts.apache.org/en/api.html#echarts.init) it takes the height and width of the parent container:
> Instance container, usually is a DIV element with height and width defined

If already initialized you can use [resize funtion](https://echarts.apache.org/en/api.html#echartsInstance.resize).

**Comment by neonarc4** [comment]
@MatthiasMert  but how can we do it ? i didnt understand is height and width go in parameter of function ? resize(100,200) ?

**Comment by MatthiasMert** [comment]
If you have multiple [grids](https://echarts.apache.org/en/option.html#grid) in one chart instance you can change the width and height of each grid, or specify the size in % to begin with such that the grids will be adjusted on resize.

**Comment by neonarc4** [comment]
how can i change the color of pie chart only the first element not the rest other uneffected  also i have multiple chart instance then how do we resize do i need to group them before doing resize?

**Comment by neonarc4** [comment]
@MatthiasMert  i able to understood it but why the range is not showing me ? 
![image](https://github.com/apache/echarts/assets/140290288/9295f005-d1fa-479b-8fd1-2d11327a1d28)
suppose i want light color on lowest value and high color on max value at present sheet

**Comment by MatthiasMert** [comment]
Pls take a look at the [documentation](https://echarts.apache.org/en/option.html#visualMap-continuous.inRange) and the [examples](https://echarts.apache.org/examples/en/index.html#chart-type-heatmap) ([1](https://echarts.apache.org/examples/en/editor.html?c=scatter-stream-visual), [2](https://echarts.apache.org/examples/en/editor.html?c=heatmap-large), [3](https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian)).

[Here ](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAFiArgJwjAvDA2gcgEwAMeAzAPQCMpALDgDQz5FmUCsdDhJFpAbO410oB2fp2akAHDgC6AbgBQ8kAAcoAS3AYYAb3kwYUECAA265QC4de_TGUgIa9eEs5DynNYC-tawHNkagAmlro2Biou5AQApB763tYAHgCCiWoQIdb6UACeygCmLsAAhlD5viDIOXRZMIGlxZYIKBA-8W0wOanpllja3tq5BUWl5ZXV9PVQjdjktHi0xPRU0p7SHQBu6YjFxgCyxRZWYQC2amCWBB36J8WJluQAnNcwJcbAiMbFAEbGhQbIRD5F4QfIBfIQACSYEC-XuMCWtXOACVimBfP9QmEYCpisBHDlLgA6KgvfSgYyVXo4HL5YyUgDu_EqaIx_GQ-UCMlqni8HVB4Iy2FqWLCYGKJ3-OCmxRq2IMeSlxnO-Tl2OgeIA1i4ACogabGNVhGW9J5LGDkCQseiWuYWiQSG1CCTSHkvUU2E3YFiOmA8c08O0--gsPDrWr6cWSlwy8hGmxDJUquI2BJhD36L1YchCc2WhYWx4Fy1CG0Scjh-VRqUyvDx7KKlzKsCqt0iiMK4YMOD5Uq3dxkzrdKEwuEPQdZrBXafrWa0K4V-hYBZXMNLpZXYizrCkq4rJcL2gsbdzOY8bcLOZCbdLOYupekuaPber2hRSvy7HZ-ZvxfYBaXmu2BLJeW4Pj-5D7tgm5vseS5zLe55Lgst7Xuuixvve2Ckrez6umEaYwK6niyEAA)is a guess what you wanted for your example code provided.

**Comment by neonarc4** [comment]
awesome 2 last question bro
 how can i make tooltip background color transparent 
 how can i do tick||nextick / on datetime what ur way of doing it ?   sometime it needed for realtime chart kinda when data goes low and vast

**Comment by MatthiasMert** [comment]
Pla read the [documentation](https://echarts.apache.org/en/option.html#tooltip.backgroundColor): `tooltip: {backgroundColor: 'transparent'}`

I dont understand the second question. You can add [dataZoom ](https://echarts.apache.org/en/option.html#dataZoom-inside)if that helps.
[Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAFiArgJwjAvDA2gcgEwAMeAzAPQCMpALDgDQz5FmUCsdDhJFpAbO410oB2fp2akAHDgC6AbgBQ8kAAcoAS3AYYAb3kwYUECAA265QC4de_TGUgIa9eEs5Dyutf0AjAIbAA1gDmyEhgACYAwiYgyC5QyD6Qyj7IAKZgUDjWAL601oYmXiAAHpa6NjAAZqk-UCipZZ42YbU-AFpGALZluU3ZOXn6wWphjRVuLuQEAKRZ-r36xQCCxWoQYzZQAJ7KDQzAtamBMVseFS1QPpYIKBCDMAswWytrlljaEMrGjgAyamB7D4IADulkqPmMEFS2Vy2m2uxcBygRxO7AuV2w5FoeFoxHoVGk2Wk9wAbmtEBCALI-CxWCqdf6WAj3fSdHylGDkACcLJgB2MwEQxh8XmMe3iiFSvKhyDUqQgAElwqkOXimv8AEqJQKApr6FR-RxbJkAOiovP0oGMMTeOGCqXS_C2qWM1uB_Bi2tS_DSYRkfQG1hlcvW2Ca5QqMDAPk6exw6LOkfhce-AMTFWgfn8LgAKiBLsZ081Wm9uXjORIWPRyBIsRWJNWhBJpH1eRHziXsCwGzAeOWeHXu_QWHhiXqozG4-jyEX9MmXKnva3w-P0aWhOWazjOVztzWhNXa2PIxPYy50XhZwYdin_kuKo99O3NjeXHAalA2e4LU8XorlRyWKrp2WBYMy4HEpitDMuQkFYDizKjvQWB4syxBweazIEshMG0CwcFYliPBwTiWJCHBeJYs2yHmliXJwYhtBTMeJ6RlgWKkbByE4qRSHYHipHoTR2JMdh2BoUx-HIVilHEdxuJMeRyF4pR1HYOalH0S2D73C22SyEAA)

**Comment by neonarc4** [comment]
![image](https://github.com/apache/echarts/assets/140290288/cfb8bd5d-ec24-4917-b86e-69065bb59796)
in darkmode it get rip

**Comment by neonarc4** [comment]
i read the data zoom although it not look like tick value like the nivo doing https://nivo.rocks/guides/axes/ @MatthiasMert

**Comment by MatthiasMert** [comment]
Whats wrong with dark mode?

You can use axis type 'time' instead of 'category': [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygUwjAvDA2mZB3GAESWQAoByAJgAZKBmAWmoBYmBGcgSgBoZcDiKCjXpMArOy69-REsNqNqANkk8--WUKoKmAdlXSNgsttHUAHKoC6AbgBQdkAAcoAS3AYYAbzswYUEBAAGzcnAC5vXz8YJxAIVzdwCPIAp3JuKL8AIwRgAGsAcwAnEABXMDgAYWCQIuSoIoRIJwQi5DAociiAXwy_AOCskAAPCJ9omAAzZCRStrHM6MQoBAAtQIBbMd7F7p6-mGLXOAWJ1OS2agBSLr8dv2GAQWHXCAisceioAE8nZHrXBtkOlFssEBFlqgDvdvD8_slgCQCrVvukYBAABYgPARSYIIIQZC8MHvNjcSjcOjcZjcMRWPZ-KwHb7PV7vLwQJxBBIAGVcuDGmOxuPxhO6vS8cP-MHIiJQyKKqOJSHB2DJFKpMGYTPRWJxU1FyG6TKiADdXqV8QBZBDhSITDb8iLUA5-DYIUYwNgATldMERQWApSCCCyQWlDVKRMWhKKrlQAEkKshPVTFvyAEpNArSz4TZy5BLfZ0AOhpiz8oCCtXe5GKyHaaPI32QQWreCbtWzwN45DacHIVl2-yisfjb2wizz0TACCByTBIIm_V-0vI3NwS-X0FyeWSABUQCsgluJiTsFhIRAsNQdT66DrLyRr2wmWxzHTeE-UNfKG_zK-X5XlgD7cO-5iPsB2pgboEFDhMMJ-NOfjnlg36oDeTJiBBQHPlggFKKB2DAX-3BKIBxF4aB2GQXh0FiH-JrLnwc5rmCHB-iu8IyhuwK7H6yHwCq7zodet4wURon4f-pGUT-WCkT6slSaB766LR8nQe-r5Mcus7zjKYKUKeXyrskvG3NEiH2suUrJBiMxQO6aScTALIvBASZwCmERkhWMBPB5Xk-V6rmoTe3AuuJaqRWBj4Ui6ylUi6kk0i60HYC6ZKfjFZJKPFYHcOpX5UmSOHYDSZLeo-iVgeJ_nMfh5JgRRCnNWwSXtal7UZRFpU5U1pX5V-GowY-VKleVWA0qV1XwVZBxDt0NhAA&theme=dark)

**Comment by neonarc4** [comment]
awesome >.< kinda dark mode giving the problem on reactivity doesnt work on deep nested thing

**Comment by neonarc4** [comment]
@MatthiasMert i been stuck to think how do we update properly heatmap ? it keep getting flash whole thing and update harder to see value on heatmap reading

**Comment by neonarc4** [comment]
sorry for late message @MatthiasMert  what dateformat should i need to support axis type i tried strftime("%Y-%m-%d %H:%M:%S") also other time format not worked

**Comment by neonarc4** [comment]
also i got weird result with time
![image](https://github.com/apache/echarts/assets/140290288/32f2b697-ee34-4ff5-afd3-dd8b2363a3c1)

**Comment by neonarc4** [comment]
![image](https://github.com/apache/echarts/assets/140290288/c8b63645-c01b-4ab6-9278-e3a33946eadf)

**Comment by neonarc4** [comment]
```

const zx = {
  backgroundColor:'',
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: []
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
  xAxis: {
    type: 'time',
    boundaryGap: false,
                axisLabel: {
                formatter: (function(value){
                    return dayjs(value).format('h:mm:ss a');
                })
            },
    data: []
  },
  yAxis: {
    type: 'value'
  },
  series: []
}
 even i remove the format value i still have issue with   let axrc = date.x.map((ix)=>new Date(ix)) no idea what the issue

**Comment by neonarc4** [comment]
@MatthiasMert  sorry for the late i bit stuck on nuxt production issue but this is how i update thing  

i set this to solve it for now animation: false

https://github.com/apache/echarts/assets/140290288/1a84c092-9654-4ae1-8f46-eab46fae1c87

**Comment by neonarc4** [comment]
@MatthiasMert 
![image](https://github.com/apache/echarts/assets/140290288/304efc5a-4291-4269-9b15-2caf5bb9cc2d)
i keep getting this issue even i set the time sometime it spam
