### ISSUE TITLE
[Bug] when I use treemap . if text is too long ,and label set is overflow: 'breakAll', the text will overflow

### ISSUE THREAD

**Issue by freeliujian** [apache/echarts#19403]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/freeliujian/pen/ZEwNwxE

### Steps to Reproduce

this is option : 
var option = {
  tooltip: {
    formatter(info) {
      const { name } = info;
      return [`<div>${name}</div>`].join('');
    },
  },
  color: ['#419CE6', '#44A2EF', '#5FB4F9', '#5FB4F9', '#5FB4F9'],
  series: [
    {
      type: 'treemap',
      width:262,
      height:208,
      breadcrumb: { show: false },
      roam: false,
      zoomToNodeRatio: 0,
      nodeClick: 'none',
      label: {
        // width: 15,
        // position: ['0', '10%'],
        overflow: 'breakAll',
        // formatter(info) {
        //   console.log(info, 'treemapInfo');
        //   const hasStylabelArrary = [`{name|${info.name}}`];
        //   return hasStylabelArrary.join(' ');
        // },
        // rich: {
        //   name: {
        //     verticalAlign: 'center',
        //     align: 'center',
        //     fontSize: 14,
        //     lineHeight: 16,
        //     fontFamily: 'Metric',
        //   },
        // },
      },
      itemStyle: {
        borderColor: '#fff',
        borderWidth: 1,
      },
      data: [
        {
          name: 'askjdhkjqwe',
          value: 50,
        },
         {
          name: 'asiudkjy',
          value: 40,
        },
        {
          name: 'askjdkajshdkj',
          value: 30,
        },
        {
            name:'asd',
          value: 15,
        },{
          name: 'Aqweisj Viwushbwkqi of thefood Exshutweq Owuwbashr',
          value: 9,
        },
      ],
    },
  ],
};

### Current Behavior

the text is overflow
![image](https://github.com/apache/echarts/assets/31119150/2f8a60c0-4b26-4072-9054-627554bd3751)

### Expected Behavior

hope don't overflow

### Environment

```markdown
- OS:Window 11
- Browser:Chrome@119.0.6045.160
- Framework:
```

**Comment by dhruvchandak30** [comment]
@freeliujian This can be corrected by changing the value in the object.

![image](https://github.com/apache/echarts/assets/116879117/0ed1aafe-1912-4211-89ef-2f6e3c7a15cb)

**Comment by helgasoft** [comment]
Treemap will look much better when truly responsive, **without width and height**.
Also lets be realistic - treemap is all about proportions and long labels will not fit small rectangles (values). Either shorten or abbreviate long labels or change font size.
If proportions are less important than labels, then use another hierarchical chart type, like tree or sunburst or sankey.

**Comment by freeliujian** [comment]
> Treemap will look much better when truly responsive, **without width and height**. Also lets be realistic - treemap is all about proportions and long labels will not fit small rectangles (values). Either shorten or abbreviate long labels or change font size. If proportions are less important than labels, then use another hierarchical chart type, like tree or sunburst or sankey.
> 
> 📌 please close issue if problem solved

I have solved that.will close this issues
