### ISSUE TITLE
[Bug] Visual map into polar chart works incorrect.

### ISSUE THREAD

**Issue by AndreyPatseiko** [apache/echarts#19407]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-polar-label-radial&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyAvgDRobDBaQgFIlm4DmO0AJrfegG4QDOArgEMsAWUE1kZdGACeIfLADkICDgDGOAO58ci0unQr1OXgQDaUg0lhrKwAE4FFjezhZ7YAW0EAPAgGZYTgN0a1ssBycZHCwIzQ9vP1gAdiD9EOQbO0clFWgAawTfAgBGAAY0y1CsiJzFV1ZFIMsAXTJgkEpBHNQQgHo-2DMIaF4IVhxYe0FWCH5eYlhgfjAxiamZud42kOnZ-fN_MsXFAA4ygFJFFtgBm0E4XhwwfhAbFjBprFgAC0ocdrpPZbACCPj4tEssnkTi4wn4unS6F8fAAKhA1PlIRlYLw_poCAAzYRPSzBdAAL1wXBipVugxAK1gLnGSzgYFAGB-kzUP26q0BZAejFwYIhkhC0IUijUgjAOEYDhkeksACNlmxujIAOLiIkknBI3EgLAQMAAGRGCl6GTxwAJGHsCKN6FN0BwAGVZLhsTiapElABifwhlV-jByaVu3RVZohcmwFG8S3u30hO0O4lYUnxo1UnA0rClRZ3RlgZn2VkwchvMDcmx8-wCyx3WzQQkQRj8BqwVUyWAAIQAorAABRPNSQGC8WAgeygXgASksrDlgnMscUADkwxltwBJLdD3chbfHl1KIdHk8GRTnzdDj33nF3j039Cvt8XxRfzcej0AOrvkogHAYoAGgd-QFQVu0GbrBYFbghrTtCghAANwoCgoBTtAAB0TyViYCBDGQNrSJGTiqt0N7UfYAHjHWTjlJcN62A4szQHKnoyLw8qeE4nRYDRRp8YImJOIIHh3Ha_BYKwsDzJMdaTLwgieKpYDifksCEg4s4rJA0CMLAq5aWyNa6fp7o-OWhGqLwlhcRpTgejgRG8AAtGUN5meuQwAKyLOUwWLAATIsAAsOyVKEUKUUodG0d0DGsExsAsUa7H2Jx3Eerx_GCV09g3mJElKFJRrOdKbkeZ5JS-Wu5gRbAYV4S1bWReF7WLP4MWECgLToUAA

### Steps to Reproduce

Check link for minimal reproduce.

### Current Behavior

If I set visual map, it's use not value for bar chart but series index for changing color.
![image](https://github.com/apache/echarts/assets/18285745/4f8d6f16-2aa1-475b-89e5-84515a6501d6)

### Expected Behavior

Visual map should be applied for each bar by their value, not by chart order.
![image](https://github.com/apache/echarts/assets/18285745/58d5595d-a58a-4eea-864a-6182f1be6836)

### Environment

```markdown
- OS: Window 10
- Browser: Chrome Version 120.0.6099.72 (Official Build) (64-bit)
- Framework: lit-web components
```

**Comment by MatthiasMert** [comment]
You need to specify the [dimension](https://echarts.apache.org/en/option.html#visualMap-piecewise.dimension). For example `'radius'` works.

[Example](https://echarts.apache.org/examples/en/editor.html?c=bar-polar-label-radial&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyAvgDRobDBaQgFIlm4DmO0AJrfegG4QDOArgEMsAWUE1kZdGACeIfLADkICDgDGOAO58ci0unQr1OXgQDaUg0lhrKwAE4FFjezhZ7YAW0EAPAgGZYTgN0a1ssBycZHCwIzQ9vP1gAdiD9EOQbO0clFWgAawTfAgBGAAY0y1CsiJzFV1ZFIMsAXXT0VghPFl4oaAIy9OCQSkEc1BCAeknYMwhoXtYcWHtBTv5eYlhgfjBF5dX13hbLQ4gN839BpQAOMoBSRRbYaZtBOF4cMH4QGxYwVZYWAAC0oODIwTOGwAgj4-LRLLJ5E4uMJ-Lp2rBfHwACoQNT5BEZWC8UGaAgAM2En0swXQAC9cFwYqUXjMQLtYC4IKxtnAwKAMMDlmpgWM9hD0u9GLhYfDJCEkQpFGpBGAcIwHDI9JYAEY7NhjGQAcXElOpOExvBAWAgYAAMvMFBMMqTgOSMPZ0Zj0LboDgAMqyXBE4k1SJKADE_hjOrDGDkyr9uiqzRCdKxcN4jv9oZCbo9VKwNPTmMZOGZWFKW1eHLAXPsPL55F-YGFNjF9gllletmgFIgjH4DVgupksAAQgBRWAACk-akgMF4sBA9lAvAAlJZWGrBOZU4oAHJxjLHgCSR6np5Cx-vPqUU6vN4Minvh6nAffxLfAZf6F_P8H0UIDDwDAMAHV_yUSDoMUCDYOAqCkKPZDD1QuCjww1oIRQQgAG4UBQUAl2gAA6T5GxMBBZjIF1pETJxdTGF9mPsCCeTbJxygeF9bAcTpoDVQMZF4dVPCcEYsBYq0wEEAknEEDxXjdfgsF5DZljbZZeEEboSTkglYApBxV12SBoEYWBdzk5sBV-Ez7Fgf0fHrSjVF4SwhO6JwAxwKjeAAWjKF8bP3WYAFYtnKaKtgAJi2AAWE50GCeiE2RJQ2L4ih7EE4SA1E8TJNGewXzE-TCSUJTMW85U_ICwKSlCvdzAS2A4rI9rOsS-Kuq2fwUuaFp8KAA)

**Comment by AndreyPatseiko** [comment]
Thanks! It's work perfectly.  🙇‍♂️
