### ISSUE TITLE
[Bug] Legend组件inactive状态下lineWidth没有跟随配置

### ISSUE THREAD

**Issue by zhiyuc123** [apache/echarts#19412]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?renderer=svg&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0kC-ANCXI58RVKTKUasWgDdGAGwCuVWoImNceADKMARlQViSEgGacAtsxYc6Secqq9YAdR4TefdbAVsq0ABNjCTBQIgBGAAZI73QIaEZ6SFkqAGFgBU46AGIAUQBWXIA2XIAhNRNYCBYLFwgAsAALCKLYqpqACSoIVkawIgAONoV4qgBlCl9giVgAd3qmiMqBSoDmRiIAbUr0cRn0BItpWhHoKnD3GZX9vf3D49OqACZLjzbdndJ7ukeAZgr9uhHhNyFNiIDSBRqFtfvxYFEALqfdCefao0hIlHePBUDgQKiEWDbCS3L6MI4_UYXd6SaEyR4AmZ4cgWPQZOj0CAcei-RkSZmsjJjCAAL2kRWWbVJB3JD1GLxpULlZz5pAFbKMMk53N5NPVQtF4sllWlsG-9NG_0VUkpKr1LI1HK5PNU9sFCmFYqIEo8JCRvAA3EA

### Steps to Reproduce

进入复现链接，关闭一个图例，可以看到线宽变化

### Current Behavior

![image](https://github.com/apache/echarts/assets/46096473/e681a6c4-696b-4f39-841e-e18d86721dbb)
inactive状态下的line Width始终是2，没有跟随legend.lineStyle配置

### Expected Behavior

inactive状态下的lineWidth和active状态保持一致

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

![image](https://github.com/apache/echarts/assets/46096473/dbf30b43-9075-499d-bb56-5584bd8dfa9c)

这里线的颜色不是inactiveColor，是设计如此吗

**Comment by helgasoft** [comment]
looks like a bug. 
There is an **undocumented** attribute 'inactiveWidth', but it does not take effect.
Good question for the developers
https://github.com/apache/echarts/blob/5b0c09637a00e033bc63e93fb41391b56e3a9ffd/src/component/legend/LegendView.ts#L642

**Comment by Ovilia** [comment]
@helgasoft It seems it was implemented as `legend.lineStyle.inactiveWidth` by mistake. I will fix this. Thanks!

**Comment by Ovilia** [comment]
Please refer to [legend.lineStyle.inactiveColor](https://echarts.apache.org/en/option.html#legend.lineStyle.inactiveColor) and [legend.lineStyle.inactiveWidth](https://echarts.apache.org/en/option.html#legend.lineStyle.inactiveWidth).

**Comment by plainheart** [comment]
@Ovilia FYI, besides the legend line width, the following code shows a numeric value of `legend.inactiveBorderWidth` won't take effect as well. Except for the literal `auto`, any other value will fall back to use `legend.itemStyle.borderWidth`. Please have a look.

https://github.com/apache/echarts/blob/master/src/component/legend/LegendView.ts#L629-L638

![image](https://github.com/apache/echarts/assets/26999792/2adbb726-7099-48d0-b6b4-2334631eb132)

👉 [**Reproduction Demo**](https://echarts.apache.org/examples/editor.html?c=line-stack&renderer=svg&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqwD0FsYAFhAM6wHBYPQDkYNAhgNZZYWAGbCsAYzAAaWAHcIGDLGE9FsAEY9xfGsFgADCGCwBbAMpgAntgB064ACcCWBwHUIBOvrLoqsCNBakABuWABCjs5uHnQkHAG0LkYcUj6U1HSMzKzsXLwCQqIS0nIKSipqmtq6BkamFtZYdpEu7p603uT-gZIQoRFOrTG0JABMAAypXX4cPACuYMAc_kx0gjAYlnKOfAE4sMGqc1hpfgFBfeEt0e1x84spaee9_dcAwsAYjnHiljycU3IdXMVmwJFQXXQ9kGN1isAArGkAL5kJGAgAeAEF0YxwWkrCAsD8eMYcI5LI8ugQSTwSABtDgAWRgKVgHAAKsdWRxXFgCNz2bQ5tyAGIOCDcswkyVzTgAXVRgMs2NxpC6BKJbMOGC5irIDCSbHpaQhkMCJk1HAAoiYeApKZCNXEMAEsA6qTT6QBGCYyL0AZlGfvGXr9_oALDIAJyTWCjf2x0Ze8ZywFdBiWEz2DBmCAAL01vrS6AzWc-cQcxXdQOMIMaeMh5GhUTacIAHGnIc2XB8vg4K3yOMXYCiuqPYAqkQBuIA)
