### ISSUE TITLE
[Bug] legend不对齐的问题

### ISSUE THREAD

**Issue by lllianreg** [apache/echarts#19417]
### Version

5.4.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

none

### Current Behavior

![image](https://github.com/apache/echarts/assets/21689406/6636a877-2ef0-4de8-bad9-4f56206ca016)
发现通过api怎么设置都无法实现legend属性的 文字和图案的居中对齐

### Expected Behavior

可以居中对齐

类似下面css的效果
` display: flex; justify-content: center;`

### Environment

```markdown
- OS:windows11
- Browser:Chrome 
- Framework:
```

**Comment by Ovilia** [comment]
Probably due to special font or platform. Please provide an online demo.

**Comment by lllianreg** [comment]
> 可能是由于特殊的字体或平台。请提供在线演示。

https://codesandbox.io/p/sandbox/beautiful-jepsen-qgyfjy?file=%2Fsrc%2Findex.js%3A75%2C1

**Comment by lllianreg** [comment]
`display: flex; align-items: center; flex-direction: row`

**Comment by LiDopamine** [comment]
@lllianreg 看起来是字体的问题导致的，可以尝试更换字体来修正问题，或者使用 legend.textStyle.padding 来进行位置的修正
