### ISSUE TITLE
Sunburst: Improve label positioning

### ISSUE THREAD

**Issue by Aleksashka11** [apache/echarts#19416]
### What problem does this feature solve?

Hi!
Dealing with a typical issue in the sunburst chart—too many categories causing text overflow. I've come up with a workaround by placing all labels on the right, but it's not very intuitive. I'd like to keep the same functionality but have labels positioned close to each category for better clarity. Below are the pictures of what I have and what I want to have (you've already have a great label positioning for other charts).
<img width="554" alt="pie_chart" src="https://github.com/apache/echarts/assets/59337516/8d6b97e6-1ee0-4035-abc2-72cb5a0f8be6">
<img width="675" alt="sunburst_1" src="https://github.com/apache/echarts/assets/59337516/493fe68a-3d3d-436b-952f-8cefa447e097">

### What does the proposed API look like?

label: {
  "position": "outside"
}
If you do have something similar, I would appreciate your help!

**Comment by Ovilia** [comment]
It's not recommended to use sunburst labels like pie because it would be messy. You should redesign your expected chart and see what is the most important information you would like your visitors to see.
