### ISSUE TITLE
[Bug] selectedOffset选中时偏移距离和间距不一致

### ISSUE THREAD

**Issue by MC-YCY** [apache/echarts#19433]
### Version

5.4.3

### Link to Minimal Reproduction

https://www.isqqw.com/viewer?id=43032

### Steps to Reproduce

```js
option = {
   title: {
      text: 'Referer of a Website',
      subtext: 'Fake Data',
      left: 'center'
   },
   tooltip: {
      trigger: 'item',
      show: false,
   },
   legend: {
      orient: 'vertical',
      left: 'left'
   },
   series: [
      {
         name: 'Access From',
         type: 'pie',
         radius: '50%',
         data: [
            { value: 1048, name: 'Search Engine', select: { itemStyle: { shadowColor: '#5470c6' } } },
            { value: 735, name: 'Direct', select: { itemStyle: { shadowColor: '#91cc75' } } },
            { value: 580, name: 'Email', select: { itemStyle: { shadowColor: '#fac858' } } },
            { value: 484, name: 'Union Ads', select: { itemStyle: { shadowColor: '#ee6666' } } },
            { value: 300, name: 'Video Ads', select: { itemStyle: { shadowColor: '#73c0de' } } }
         ],
         selectedMode: true,
         selectedOffset: 15,
         select: {
            itemStyle: {
               shadowBlur: 10
            }
         },
         labelLine: {
            show: false
         },
         emphasis: {
            disabled: true,
         }
      }
   ]
};

myChart.on('mouseover', (event) => {
   console.log(event)
   myChart.dispatchAction({
      type: 'select',//默认显示江苏的提示框
      seriesIndex: 0,//这行不能省
      dataIndex: event.dataIndex
   });
})
```

### Current Behavior

各个选中的元素，设置的偏移量selectedOffset和间距不一致
![Snipaste_2023-12-23_21-10-55](https://github.com/apache/echarts/assets/87837356/4a0feba6-68da-427c-9a35-539f9df82c73)
![Snipaste_2023-12-23_21-11-04](https://github.com/apache/echarts/assets/87837356/134ab4ec-e875-42e0-b1e5-b16da98baf7a)
选中第一个饼图同其它选中饼图的距离不一致 

### Expected Behavior

期望所有选中的间距都一致

### Environment

```markdown
- OS:window11
- Browser:Microsoft Edge
版本 120.0.2210.77 (正式版本) (64 位)
- Framework:html5
```

**Comment by helgasoft** [comment]
> Expect all selected spacing to be consistent

Looks like "consistent" for ECharts means smaller gaps for smaller pie sectors. Do you expect **equal** spacing gaps for all sectors?

BTW _selectedOffset_ works - set ```selectedMode:'single', selectedOffset:55,``` to see effect.

**Comment by MC-YCY** [comment]
> > Expect all selected spacing to be consistent
> 
> Looks like "consistent" for ECharts means smaller gaps for smaller pie sectors. Do you expect **equal** spacing gaps for all sectors? That would **not** be good design given that a selected small sector will have to pop out too far from the pie.
> 
> BTW _selectedOffset_ works - set `selectedMode:'single', selectedOffset:55,` to see effect.

Thank you for your answer. I understand that this is a bad design;
