### ISSUE TITLE
geo can't zoom in phone

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#19443]
### Version

^5.4.3

### Steps to Reproduce

this is option
```js
        const option = {
          backgroundColor: 'white',
          title: {
            text: 'test',
            textStyle: {
              fontSize: 14,
            },
          },
          visualMap: {
            show: false,
            min: 0,
            max: 500,
            splitNumber: 0.1,
            inRange: {
              color: ['#d94e5d', '#eac736', '#50a3ba'].reverse(),
            },
            textStyle: {
              color: '#fff',
            },
          },
          geo: {
            type: 'map',
            map: 'world',
            // zoom: 2, // 当前视角的缩放比例
            zoom: 1,
            roam: true, // 是否开启平游或缩放
            silent: true,
            aspectScale: 1,
            //layoutCenter: ['90%', '50%'], // 地图位置
            layoutCenter: ['50%', '50%'], // 地图位置
            layoutSize: '150%',
            label: {
              emphasis: {
                show: true,
                color: '#fff',
              },
            },
            itemStyle: {
              color: 'rgba(48,97,186,0.3)', // 地图背景色
              borderColor: 'rgba(0, 0, 0, 0)', // 省市边界线
              emphasis: {
                color: 'rgba(32,42,58,0.3)', // 悬浮背景
              },
            },
          },
          series: [
            {
              name: 'AQI',
              type: 'heatmap',
              coordinateSystem: 'geo',
              /* itemStyle: {
                normal: {
                  color: 'skyblue',
                },
              },*/
              data: convertData(data),
            },
          ],
        }

```

### Current Behavior

can't zoom in phone

### Expected Behavior

zoom in phone

### Environment

```markdown
- OS: android
- Browser: edge
- Framework: vue3
```

**Comment by helgasoft** [comment]
please do not submit **incomplete** code
Cannot reproduce, geo zooms on phone as expected - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsBGBDAxgawHMAnYAV2gBMBhYAG2CIC5YByAdwAsIwBTFgGjSxIYWj2ap06XgA8wzFrwDOYAUOk85AZTABPMRPVSAZjDBaIAL3GwAjABYjAXyFPB6AG4QlpLLQCyWCCGUrBKHMBszMZ-SjzuUgC2ENDMAAwJ6IlYMswArGkZRkogtNwAcqSJGDxMsGkAdLaZsCkASljQBDaSobAA9P04dAzMANosAMQUAJz2PHkUAqyTPLgA7ADMAGzLUwVYm9gsALoNRDwetXEAFACULejD9HUTF0v8rBi0pHwnzi1ZOY9AZkEYniM6lNjDCWM5XAlusAQlI9CAbCxsiA1KEsQo2AxaB8jJZgMBEsxmkYSFgKcIiL9PoNYIB6M0AZCqAAH1APQqgGc9QAcdoA0I0AlP6APlNihAxNB5PTGUYsCUeDhzDg_DYqaFaFhdGQwFQeFLauMWJs0gBSPYFc0nJn9WCABnVAH9qgFl5QB2_kZNdrSOYrBjbJacVJNTVaCjQjxEiAOPLvKG-uFIswwAz4uCpM9RisYcY4X1YC5Qm4jNxwzp9D1U-moUQCNgbvYABz8Gbrfi2evbfiNTZ3ZbMx2AGYDAPZmgCcg1MYBgUWo0F4Kau1jL1T4LtI9m2wQCA7oAgPUAnfGAGVdAP1-qfDkejSljoUrs5rWBumwATPx7A-8o2uz2BrbADUGgDtbIep_NSABhboHERAQDwZ6wGMRi9KE0C0hiACCACKACSAahGiGIcGsYBYhhaZkkQFApFgvBaLoKjhgoSIEeg3ykEQFjWJS6p9BQZFYOMYy2HetgNAUMxpNsD6wHe9gNGk9j2Js96fNJ9gnP8BZCP8TgANxAA)

**Comment by zhoufanglu** [comment]
> please do not submit **incomplete** code Cannot reproduce, geo zooms on phone as expected - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsBGBDAxgawHMAnYAV2gBMBhYAG2CIC5YByAdwAsIwBTFgGjSxIYWj2ap06XgA8wzFrwDOYAUOk85AZTABPMRPVSAZjDBaIAL3GwAjABYjAXyFPB6AG4QlpLLQCyWCCGUrBKHMBszMZ-SjzuUgC2ENDMAAwJ6IlYMswArGkZRkogtNwAcqSJGDxMsGkAdLaZsCkASljQBDaSobAA9P04dAzMANosAMQUAJz2PHkUAqyTPLgA7ADMAGzLUwVYm9gsALoNRDwetXEAFACULejD9HUTF0v8rBi0pHwnzi1ZOY9AZkEYniM6lNjDCWM5XAlusAQlI9CAbCxsiA1KEsQo2AxaB8jJZgMBEsxmkYSFgKcIiL9PoNYIB6M0AZCqAAH1APQqgGc9QAcdoA0I0AlP6APlNihAxNB5PTGUYsCUeDhzDg_DYqaFaFhdGQwFQeFLauMWJs0gBSPYFc0nJn9WCABnVAH9qgFl5QB2_kZNdrSOYrBjbJacVJNTVaCjQjxEiAOPLvKG-uFIswwAz4uCpM9RisYcY4X1YC5Qm4jNxwzp9D1U-moUQCNgbvYABz8Gbrfi2evbfiNTZ3ZbMx2AGYDAPZmgCcg1MYBgUWo0F4Kau1jL1T4LtI9m2wQCA7oAgPUAnfGAGVdAP1-qfDkejSljoUrs5rWBumwATPx7A-8o2uz2BrbADUGgDtbIep_NSABhboHERAQDwZ6wGMRi9KE0C0hiACCACKACSAahGiGIcGsYBYhhaZkkQFApFgvBaLoKjhgoSIEeg3ykEQFjWJS6p9BQZFYOMYy2HetgNAUMxpNsD6wHe9gNGk9j2Js96fNJ9gnP8BZCP8TgANxAA)

thank you for answer! 
i find question, this is not echarts question. 
this is uni-app question 
i add `window.wx = {} // 解决echarts不能拖动问题` in `main.js` fixed this problem
