### ISSUE TITLE
[Bug] Histogram Bars Not Aligned with Coordinates 直方图柱子与坐标未对齐

### ISSUE THREAD

**Issue by TonyYanOnFire** [apache/echarts#19445]
### Version

5.4.3

### Link to Minimal Reproduction

[link](https://echarts.apache.org/examples/zh/editor.html?c=bar-histogram&code=PTAEGUFNNALAXeAHAzgLhAcwJb1gVwCMA6AYwHsBbYSCygM0htNgEMAneFAWhXlfgAoWm04pi7SDj6R2AFXasAdinrl2lABS1w_eMXiKVajcVjY-5TIsoBKANyDBAN1YAbfJBQBGUAF5QAG1BUFAAJgB2AE5iABYAGnCIgGZiMMSwgDZvOIyAVlSIjNii8O8ADmJSsIAGHMzEiprc0G9MyoTWiJy8xuy0-JDWvLzib0a8mPHWzLDiZImY9OHU6e9Y5t7W2OXvZJjyxuS53eT6o9iBob2cqMawubvW71vEqMqn8srS8suf1IarRqzUB3lq83uzTWbWIvWuL1hjRqqQWQPOQJqggAuo4XO5PCgwv4gkNCltUX9yWkqREtp1OqkqWE6YlUszWdSOeTWYlOnDQmytkzhRkqlTuaB6TzJYjJbzpWSObT5XK5aTOarFaqGbLUXrRcrQIKFQa6WLeRrGYMBRq5jSJZd2UalUKVVqtVs5oaKS6eervRrHWanXyLRKJcbwuajbrZQyVQl1fbEq7nZrLdHYtjca4PF5ksTggLlg9WctjhlliUyxlSjteSXShWjVXSnlyx3K6yiqTqnXy02qyXO-ER94IrLIt3aynhzOktOhtWF0bBzXV_Pkk3-7y22uWw3DwfRzPSXPj-PdY3N32j1ON8f68fm_fm1vrSvS8f7-2j-_JcseT7q-gE7ie4FvteQw_teEF1vuL5gcu94oQOs5Hr-B69tOz67BOnrAYR85Piht4rsuJE9gKZFvkhaHPtU9Ffl-tHzqRi7UbuXbgahbFgexAF3mRmG8VhxbrqJAksWRX6XgROFAdxX6URxPFkcumH_opj6waJL7nixQ4plRgnkQZI7MfB64iYx3HLvpSkmc22l6fRiHGeuyEWbZpnNshJmSTJba6fxBnbnx67_q-AXqQhbkjv-7nfj5X4iYBnZLkxVlqZFcWNPhSkJbBiW3tBxXnlFblBY5xFFTh97VthyWbmF9VgaxoBpdxHWWR-2kkeZLUeZK4WdUZPHeZ5GWcceXWfrBT4dYtNEVeeFHpE1lWFUJ85zct9VZTVJ5nhJ6XdT5JURRBk2fhdTkjvtzUrkli3ntp_VvStH72dVT1aeN0mnW1w02apMFDbdN7dTdDUhRJtlNb1pkqfNuXA758XQx50F3cNgPPaNWn8XuOGJUxG2hCB22malpRyXjunlVx10RWVzP_q9bH0fZxW4zlz1zpltVc_D3GaYN4EDVNItC5DNN80lzGM-d6PKTFB3WRdn2i6u2ZOLmBLEgbXhhI4lCQHg5AACYoIWADkKAAI74BwkAAErkOQ8B24kDsUIgPugHb9CSJAVuUMoAAi2CsBQSgWIHDvwPg7CYF4dtYk45BIPA2DkEoxIAN5DFbAisCgFtoCSoShMXNc1yg5Ap6QkBV8b4gR0gmiaMbtj-AAfEExtYrYQyhAAvh-tdjzXhjKKo6iUFXdf17PACeSCt0HOh6Gg5iWNYrCUD7M_13H9DYJgy-n6v5uW1bVd37A1soIE3iZ6vNfjzf3_17_oBYg_PAT2bhc5IGvvXEwEdECyCrpoJAHAj4oD7n4QeK966SGTuwAuAADAAJIXBBNhxCl34MQFAbhsAt00Nwbwthx5VwIUQpBxBSGsDfliceODHB_yGJPIYAAPAAggIiwECG6kHcFvQwngp6gHgBvLedtjYn3rigJAlD4AABlsBKC3ughuz8ADuVd6DuArjPfh9dCBNyUKXdga8ADirBwFBDtnkAApInTxGc-EfjXiIsRoADEKM3lXZR-JICqMMeQExoAzFuAsRPD8Fd2DYC8FXIsNcDGhCUEfJR-9gGH2PnI0IoSlGEA4NE6xHAADq2ArZ4HCVEGIyQvGlNAG4VghBIBuHEZ_FAxiq4yMgB00ISByAoFwHnJQ4TgFIDtj_DpkAlAUCtvo0AAiq41ESGvKuvgrGrzYRXeAABJOxkAtmtEsUMTO497BAA&version=5.4.3)

### Current Behavior

When using ecStat to draw histograms, in some cases, the bars do not align with the coordinates as shown in the following image. Setting values to values1 works fine, but setting it to values2 and values3 results in anomalies.

在使用ecStat绘制直方图时, 某些情况下会出现柱子和坐标未对齐. 如下图所示
将values设为 values1 是正常的, 设为values2 和 values3 都会出现异常. 

![bar-histogram](https://github.com/apache/echarts/assets/55646026/27751f9d-117e-4c23-93e6-3553d291240b)

I have examined the histogram data returned by ecStat, and it appears to be normal. I believe this issue originates from echarts.

我检查了ecStat返回的直方图数据 , 看起来是正常的, 我相信这个问题来自于echarts

### Expected Behavior

![bar-histogram (1)](https://github.com/apache/echarts/assets/55646026/3879ec28-9e90-4503-b46d-3524542e956a)
The edges of the bars align with the corresponding coordinates.

**Comment by helgasoft** [comment]
> Setting values to values1 works fine, but setting it to values2 and values3 results in anomalies.

...then it obviously comes from the data. Data **_values2_** are the only decimals, _values1_ and _values3_ are integers and display fine.
Replace _xAxis.type_ to 'category' and it will show exact X-values - they are not in the middle of the interval (i.e. 3.8 is not the middle of 3.5 to 4.0). I suppose this comes from internal rounding 3.75 to 3.8. 
Also maybe a smaller value for _barWidth_ will look better.
![image](https://github.com/apache/echarts/assets/13038071/d1e27aca-565d-40b7-894a-db896ae5410d)

**Comment by TonyYanOnFire** [comment]
@helgasoft Thank you for your insight. You're almost correct, except for the part about `values3` being okay. If you take a closer look, you'll notice that `values3` actually encounters the same issue. 
I'm not sure if this is a bug in esStat or if it's intentional, but it's definitely has nothing to do with echarts. I will close this issue.
As a workaround to the problem, rather than using the transform option, we can recompute `x` based on the output from `histogram` function, [like this.](https://echarts.apache.org/examples/zh/editor.html?c=bar-histogram&code=PTAEGUFNNALAXeAHAzgLhAcwJb1gVwCMA6AYwHsBbYSCygM0htNgEMAneFAWhXlfgAoWm04pi7SDj6R2AFXasAdinrl2lABS1w_eMXiKVajcVjY-5TIsoBKANyDBAN1YAbfJBQBGUAF5QAG1BUFAAJgB2AE5iABYAGnCIgGZiMMSwgDZvOIyAVlSIjNii8O8ADmJSsIAGHMzEiprc0G9MyoTWiJy8xuy0-JDWvLzib0a8mPHWzLDiZImY9OHU6e9Y5t7W2OXvZJjyxuS53eT6o9iBob2cqMawubvW71vEqMqn8srS8suf1IarRqzUB3lq83uzTWbWIvWuL1hjRqqQWQPOQJqggAuo4XO5PCgwv4gkNCltUX9yWkqREtp1OqkqWE6YlUszWdSOeTWYlOnDQmytkzhRkqlTuaB6TzJYjJbzpWSObT5XK5aTOarFaqGbLUXrRcrQIKFQa6WLeRrGYMBRq5jSJZd2UalUKVVqtVs5oaKS6eervRrHWanXyLRKJcbwuajbrZQyVQl1fbEq7nZrLdHYtjca4PF5ksTggLlg9WctjhlliUyxlSjteSXShWjVXSnlyx3K6yiqTqnXy02qyXO-ER94IrLIt3aynhzOktOhtWF0bBzXV_Pkk3-7y22uWw3DwfRzPSXPj-PdY3N32j1ON8f68fm_fm1vrSvS8f7-2j-_JcseT7q-gE7ie4FvteQw_teEF1vuL5gcu94oQOs5Hr-B69tOz67BOnrAYR85Piht4rsuJE9gKZFvkhaHPtU9Ffl-tHzqRi7UbuXbgahbFgexAF3mRmG8VhxbrqJAksWRX6XgROFAdxX6URxPFkcumH_opj6waJL7nixQ4plRgnkQZI7MfB64iYx3HLvpSkmc22l6fRiHGeuyEWbZpnNshJmSTJba6fxBnbnx67_q-AXqQhbkjv-7nfj5X4iYBnZLkxVlqZFcWNPhSkJbBiW3tBxXnlFblBY5xFFTh97VthyWbmF9VgaxoBpdxHWWR-2kkeZLUeZK4WdUZPHeZ5GWcceXWfrBT4dYtNEVeeFHpE1lWFUJ85zct9VZTVJ5nhJ6XdT5JURRBk2fhdTkjvtzUrkli3ntp_VvStH72dVT1aeN0mnW1w02apMFDbdN7dTdDUhRJtlNb1pkqfNuXA758XQx50F3cNgPPaNWn8XuOGJUxG2hCB22malpRyXjunlVx10RWVzP_q9bH0fZxW4zlz1zpltVc_D3GaYN4EDVNItC5DNN80lzGM-d6PKTFB3WRdn2i6u2ZOLmBLEgbXhhI4lCQHg5AACYoIWADkKAAI74BwkAAErkOQ8B24kDsUIgPugHb9CSJAVuUMoAAi2CsBQSgWIHDvwPg7CYF4dtYk45BIPA2DkEoxIAN5DCAoBWwIrAoBbaAkqEpehMXddgKEoQoOQKekJANfG-IEdIJomjG7Y_gAHxBMbWK2CXzegAAvh-9egI3oCL6EhjKKo6iUDXy-ry38AAJ5IF3Qc6HoaDmJY1isJQPvTy3D9x_Q2CYDv98Pw_5uW1bNdf7A1soECN4TOTcP6hFnu_FuEDQHgPvliD88BPZuFzkgN-D8TAR0QLIGumgkAcBvigYefgx7LwfpIZO7AC4AAMAAkhc8E2HEOXfgxAUBuGwJ3TQ3BvC2FnjXOhDCCHEGYawIBWJZ5UMcA_aBc8PwAA8ACCciLBoJbigUg7gT6GE8B-NeR8T522NnfB-KAkDsPgAAGWwEoE-pC1H_wAO413oO4KuQxwG6NAIQduShy7sAPgAcVYKgoIds8gAFJE4RIzkMeeQwD5KJUUvdxoBD7HxroY_EkBjH2PIE40ALi3BuI8UMKu7BsBeBrkWFudjQgiJrmfAQZgLCIOvloHuiQ_4ALEbYYRFdiB900IQaxo9QCaECEM6xgQwhYlAAAai8VM5Ik8V7hESMQDZwylCsPYZwnhk9bCeNCEoG-BjL6tJsDkh-aSDGEA4Fcludz2AAHVsBWzwBkqIMRkiRKOaANwrBCCQDcKosBKBHE120ZAP5oQkDkBQLgPOSgMmIKQHbFJJSwGQCUBQK2tjQByJrjURIB8a6-DiWAkRVd4AAElfGQEJa0FJMjM6z3sEAA&version=5.4.3)
