### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tw19920521** [apache/echarts#19462]
### Version

^5.1.1

### Link to Minimal Reproduction

1

### Steps to Reproduce

无数据时候，即data=[],不知道为啥显示灰色饼图？

### Current Behavior

<img width="175" alt="1703233192412" src="https://github.com/apache/echarts/assets/52408708/3bd19fda-c426-40c2-b977-d3da6f5e2a04">

### Expected Behavior

期望空白

### Environment

```markdown
- OS:windows
- Browser:Chrome
- Framework:vue2.6
```

**Comment by plainheart** [comment]
设置 [`showEmptyCircle`](https://echarts.apache.org/option.html#series-pie.showEmptyCircle) 为 `false` 即可隐藏。
