### ISSUE TITLE
[Bug] Timeline with bar categories does not fully replace option series

### ISSUE THREAD

**Issue by helgasoft** [apache/echarts#19472]
### Version

5.4.3

### Link to Minimal Reproduction

[Example](https://echarts.apache.org/examples/en/editor.html?c=dataset-simple0&code=PYBwLglsB2CMAEBeeBvAUPeBnApgJwhywC54BtDTVSq-MATxB1IHIAjAQzxYBoaqAJhzAdSFWrTIsAssIDGACw7wAMsLA5e8ACwBmAHS6AunwlUp0iABsA1vAAqODloAcB2Ef6ZPtAL6VPXwBuNFBIGAAmJGpMXAIiMX50MwYmVk5uUwkhEUSzTAt5JVV1TR54AE4DAHYTL3MZaztHZ3KAVjb9DyyzKQBhBRwiHHg-4DlgVvgXCP02uvzyFgB1DitoAFcweAAhPGAAd2hCLV0Krp8JS8xfHpiJVOZ4di5eepzRcnqCmSLlNTAGlcnRcC3yFiaDicWmqBm0YN6LAGQ1wo3Gky0ADZOhEERIpKt1ltdvsjid2gYKtcqNT_N40MFQuAoNBosk6MBgFY2MAAB7EFDwABmTjAGzwzBQEqwYGAEtIKF8Sqysq5kBACtulF5AEFeRASKg6Iwniw5MIcABzOX0FjwLWYeh6g2alUQAC2OCsEGgT3ZmA4-qw9hNrHNGmteFtdw-YgiAAZYG1ygnYJjLg74GEWYayNmYLByvnoLiGUEgA)

### Steps to Reproduce

Timeline has only two steps. Move from first to second and back to first. Use Restore button to restart.

### Current Behavior

On return to first timeline step, bars from second step remain instead of being removed.

### Expected Behavior

Bar chart series to be replaced on each timeline step.

### Environment

```markdown
- OS: win 10
- Browser: Chrome
- Framework:
```

### Any additional comments?

Did not dive in the source code, but feels like timeline is using _setOption_ with update instead of **replace**.

**Comment by plainheart** [comment]
Maybe you can set a [`replaceMerge`](https://echarts.apache.org/option.html#timeline.replaceMerge) strategy (e.g. _replaceMerge: 'series'_) for the timeline component.

**Comment by helgasoft** [comment]
that was it, thank you @plainheart !
[revised example](https://echarts.apache.org/examples/en/editor.html?c=dataset-simple0&code=PYBwLglsB2CMAEBeeBvAUPeBnApgJwhywC54BtDTVSq-MATxB1IHIAjAQzxYBoaqAJhzAdSFWrTIsAssIDGACw7wAMsLA5e8ACwBmAHS6AunwlUp0iABsA1vAAqODloAcB2Ef6ZPtAL6UTSgAPAEEgiBJUeCERMRl5JVV1TR4ZaztHZyN4Xz5fAG40UEgYACYkakxcAiIxfnQzBiZWTm5TCRjRci9zeLBFZTUwDS0ATgMAdkCzTAt0hyctAFYl_Q92sykAYQUcIhx4LeA5YGceeBdS_SXpmakAdQ4raABXMHgAITxgAHdoQi0ulGax8ElBmFy9R6TWY8HYXF4PU6dRm5D6AySwxSF1WLlumzStgWZ3gEwM2nxEm2u32h2Opy0ADZVqVKZIWI9nm9Pt8_gDzksDKNwVQRf5vO1QuFIihosIuhYEoNkrxCRlFqkdntcHSTmcOU9Xu8vr9_ppspCCkVwFBoBUGnRgMArGxgEFiLKAGZOMAvPDMFD-rBgYD-0goXyR9oh52QEDhyGYKURcN0RiwlhyYQ4ADmofoLBy7XoYRTqETdAgAFscFYINBYQ7MBxpfZ06wsxo83gCxs5bFyKUAAywJbnYewRkmeD8f0gKwcOQ4aT4HPMFjVQhYFiUCvFW2RMj7mCwc7H6CstAFIA)
