### ISSUE TITLE
[Bug] 在折现图中，tooltip.renderMode='html',无法绘图

### ISSUE THREAD

**Issue by qc5926** [apache/echarts#19490]
### Version

5.4.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

tooltip: {
          show: true,
          trigger: 'axis',
          alwaysShowContent: true,
          className: 'echarts-tooltip echarts-tooltip-dark',
          renderMode: 'html',
          appendToBody: true,
        }

### Current Behavior

![image](https://github.com/apache/echarts/assets/66767805/28aaaf20-1108-47c4-a53f-e999dc28cab8)

### Expected Behavior

tooltip可以添加到body中，对其样式进行自定义

### Environment

```markdown
- OS: Win 11
- Browser: Chrome 120.0.6099.200
- Framework: Vue@3
```

**Comment by qc5926** [comment]
Framework: vue@3, uniapp

**Comment by qc5926** [comment]
在 uniapp中会报错，app中不支持document获取节点信息

**Comment by plainheart** [comment]
In those environments that don't support HTML, you will need to use the [`richText`](https://echarts.apache.org/option.html#tooltip.renderMode) mode of the tooltip, instead of the `html` mode.
