### ISSUE TITLE
No available Thousand and Decimal separators (g.e. Commas and dots)

### ISSUE THREAD

**Issue by josepalomino123** [apache/echarts#19495]
### What problem does this feature solve?

There are missing **Thousand separators** and **Decimal separators** (g.e. **Commas** and **Periods**) in the **Pie charts**, when we use the **tooltip** with a **formatter**, as we can check on the two examples below:

### 1) link: https://echarts.apache.org/examples/en/editor.html?c=pie-rich-text
![image](https://github.com/apache/echarts/assets/156306198/52aaa96e-e46b-4d20-8d98-2bf6ea780c70)
![image](https://github.com/apache/echarts/assets/156306198/bc82da4e-1e6b-4d55-9f53-ca84fc442bd1)

### 2) link: https://echarts.apache.org/examples/en/editor.html?c=pie-nest
![image](https://github.com/apache/echarts/assets/156306198/050c266b-97a0-4159-8ee3-dd3a032f5a63)
![image](https://github.com/apache/echarts/assets/156306198/05ae16ff-63ea-4980-a499-a478fc93d753)

### What does the proposed API look like?

I will add them there.

**Comment by josepalomino123** [comment]
Many thanks in advance for your help.

**Comment by helgasoft** [comment]
template formatter is not enough. Replace with ``` formatter: (p) => {return p.value.toLocaleString(); }```

📌 please close issue if problem solved.

**Comment by josepalomino123** [comment]
Hello [helgasoft](https://github.com/helgasoft),
Many thanks. Nevertheless; the **formatter** is very useful, because I can display many necessary info in the **tooltip**.
If I use `formatter: (p) => {return p.value.toLocaleString(); }`, then I can _only_ show the **Value**, but not the rest of info (like the **Text**, for example).
Then, If I replace `formatter: '{a} <br/>{b} : {c} ({d}%)'` by `formatter: (p) => {return p.value.toLocaleString(); }` the formatter lose all its meaning (it is like showing only `formatter: '{c}'`, then I lose the rest of info).

**Comment by helgasoft** [comment]
Variable **_p_** has all the info available, take a look and choose what you need.

**Comment by josepalomino123** [comment]
Many thanks
