### ISSUE TITLE
how do we set tick interval in type time on xAxis

### ISSUE THREAD

**Issue by neonarc4** [apache/echarts#19506]
also  i tried set interval on type time in xAxis to 2  but didnt work
![image](https://github.com/apache/echarts/assets/140290288/1db83fd7-03ba-461e-92d0-aed730b4f41a)

```

  xAxis: {
    type: 'time',
    minorTick: {
      show: true,
      splitNumber: 3
    },
    offset: 4,
    axisTick: {
      interval: 3,
      length: 4,
      inside: true
    },
        axisLabel:{
          shadowOffsetX: 10,
          hideOverlap: true,
             rich: {
            year: {
                // Make yearly text more standing out
                color: 'crimson',
                fontWeight: 'bold'
            },
            month: {
                color: 'firebrick'
            },
            day: {
                color: 'gold'
            },
            hour: {
                color: 'teal'
            }
        },
          minorTick: {
      show: true,
      splitNumber: 4,
      length: 4,
      interval: 4
    },
  },

``` 
this type time didnt work sometime it create very odd value if i can control the interval 2x rather 1x would be alot better

**Comment by helgasoft** [comment]
Minimal Reproduction is incomplete

**Comment by neonarc4** [comment]
@helgasoft what u want on minimal reproduction ? this library doesnt have any realtime chart example using datazoom

```

        dataZoom: [
        { 
            xAxisIndex: [0],
            realtime : true,
          showDetail : true,
            start: 40,
            end: 100                      
        },
],

```
this keep reset if new datapush  making impossible to see data

**Comment by neonarc4** [comment]
@helgasoft 
bro i fixed the datazoom i should not push data on xaxis that solve the issue but how can i fix this tick interval issue ? i have xAxis:{type:time}

**Comment by neonarc4** [comment]
>.< sorry i have fixed the datazoom  bit of my mistake but how can i fix this tick interval issue ? i have xAxis:{type:time}

**Comment by helgasoft** [comment]
interval is not supported for axis type 'time', see #19502, #19381, #18952, etc.  Try [minInterval](https://echarts.apache.org/en/option.html#xAxis.minInterval) instead of _interval_.
📌 Please search existing issues before submitting a new one.

**Comment by neonarc4** [comment]
i tired but it didnt work as i excepting i dont know what am i missing 

```
    minInterval: 2,
    maxInterval: 3600 * 1000 * 24*60*10,
```
so i am sending the data something in this format  [2024-01-13 00:12:00+00:00,zz]  ,[2024-01-13 00:12:03+00:00,zz1]

**Comment by helgasoft** [comment]
for **less** labels increase minInterval, for **more** labels decrease maxInterval. No need to use both. However they are just recommendations, the chart will set labels automatically depending on readability.
Value 3600*1000 *24 is one day (in msec).  
The rest is experiments...

**Comment by neonarc4** [comment]
thnx bro >.< one last issue i have facing bit of when i try to color month or day or year it doesnt work in rich 

```

 axisLabel:{
          shadowOffsetX: 10,
          hideOverlap: true,
             rich: {
            year: {
                color: 'crimson',
                fontWeight: 'bold'
            },
            month: {
                color: 'firebrick'
            },
            day: {
                color: 'gold'
            },
            hour: {
                color: 'teal'
            }
        },
