### ISSUE TITLE
[Bug] : xaxis timeseries chart axis values overlapping to each other for small width

### ISSUE THREAD

**Issue by ktx-abhay** [apache/echarts#19504]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXKuugM4AWwA7vmAE4CuApgDRrF0QDmnjt-ARAEMAHhBL82AX1bphAQVEl8yNujABPEI2UBySAFtGOmbGlt1CscqLtN22DoBug7Ex1STJXhEZLYAbVUVYmIAE0EwQWV_fwBGAHYABgBWFIBOZNjYgGZYgBZmWFjEgF1mOKTU5IyAJhz8wprSwoqU9OTc3ILYbOaAhLbq5Lz67rzSsqC1O11sCGgjIMk2EpRJAG4gA

### Steps to Reproduce

create any timeseries chart with 200px width

### Current Behavior

![image](https://github.com/apache/echarts/assets/141122205/bcbf3c07-5c7d-4261-88ee-970d0223d54b)

### Expected Behavior

improve auto interval calculation or support custom interval option for timeseries

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
try ```minInterval: 6666``` or higher

**Comment by ktx-abhay** [comment]
working 
Thank You.
