### ISSUE TITLE
[Bug] 'barMinHeight' is invalid in this case.

### ISSUE THREAD

**Issue by Coffeeinwater** [apache/echarts#19500]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-data-color&version=5.4.3

### Steps to Reproduce

Here is the code and the screenshot.

```
option = {
  grid:{
    top: 0,
    right: 10
  },
  yAxis: {
    type: 'category',
    data: ['Monasdadsa', 'Tue', 'Wed', 'Thu'],
  },
  xAxis: {
    type: 'value',
    show: false,
    inverse: true,
  },
  series: [
    {
      data: [
        120,
        10,
        150,
        0,
      ],
      type: 'bar',
      barMinHeight: 4,
    }
  ]
};
```

![微信图片_20240112114756](https://github.com/apache/echarts/assets/48342254/6a541ed1-c189-4b01-a61c-b0d559b92170)

### Current Behavior

bar of 'Thu' is gone.

### Expected Behavior

bar of 'Thu' shows up.:  
in this case: 'inverse' is false.

### Environment

```markdown
- OS:windows
- Browser:chrome
- Framework:
```

**Comment by helgasoft** [comment]
agree - [barMinHeight](https://echarts.apache.org/en/option.html#series-bar.barMinHeight) does not play well with [inverse](https://echarts.apache.org/en/option.html#xAxis.inverse)

**Comment by helgasoft** [comment]
_barMinHeight_ is actually displayed, but in the wrong direction - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurGKIQAwA0x6OGAFmIQIwXEC-N6AngIIAPCAGdCqEqR4gApoQDkAYwCGYaRmBYec7iVwqlhANpyAsjCXC9uYUu2w5AFQCu0u3IDq03G4cMncgF1OHQFBETFaSRl5ADclABsXbUiAehThBmAAd0IAMwThaR10CGgY6SxCwjAsF2DiMmB4yBAxLmJCnGlRWENI8QlYPTADXpYAJmpYNippgFYpqYBaAGYVgOKSMClZewAjJSxkwdgDrBNSgAlpCEZmWAAWSI5iII4AbiA)
![image](https://github.com/apache/echarts/assets/13038071/d3405fe9-2a25-4412-bfb3-2e6f444680d7)

**Comment by Nishant-Nagururu** [comment]
Can I work on this issue?

**Comment by VijayMakkad** [comment]
Where can I upload the code for you to check whether its correct or not?
