### ISSUE TITLE
Independent 'splitNumber' for Multiple Y-Axes in E-charts

### ISSUE THREAD

**Issue by balasahebbagal** [apache/echarts#19522]
### What problem does this feature solve?

I have observed a limitation in E-charts when it comes to plotting graphs with multiple Y-axes. particularly concerning the 'splitNumber' parameter.

As of the current implementation, E-charts allows users to plot graphs with multiple Y-axes using the 'yAxis' configuration, where each object within the array represents a distinct Y-axis. The 'splitNumber' key within these objects defines the number of divisions on the Y-axis and their corresponding labels based on the maximum data value.

The observed problem arises when configuring 'splitNumber' for multiple Y-axes. While users have the flexibility to specify 'splitNumber' for each Y-axis individually, E-charts currently applies the 'splitNumber' only to the first Y-axis. Subsequent Y-axes inherit the 'splitNumber' from the first one, leading to incorrect axis point calculations.

For example, if the 'splitNumber' for the first Y-axis is set to 5, and the second Y-axis has a 'splitNumber' of 3, the expectation is to have three points with intervals based on the maximum value of the data. However, the current behavior results in five points on the second Y-axis, inherited from the first one.

This limitation affects the accurate representation of data, especially when different Y-axes require distinct 'splitNumber' configurations. To address this issue, I kindly request the implementation of independent 'splitNumber' support for each Y-axis, ensuring that the specified values are applied correctly to their respective axes.

By addressing this concern, E-charts can enhance its flexibility and provide users with more accurate and customizable visualizations, particularly in scenarios involving multiple Y-axes with varied 'splitNumber' requirements.

### What does the proposed API look like?

If the splitNumber issue is fixed in E-charts, it would result in more accurate and customizable visualizations, especially in scenarios involving multiple Y-axes with varied splitNumber requirements. Here are the potential positive outcomes of fixing this issue:

1. Independent Configuration: Users would be able to independently configure the splitNumber for each Y-axis. This means that different Y-axes can have their own distinct splitNumber values, allowing for more precise control over the number of divisions and their intervals.  
2. Accurate Axis Points: Each Y-axis would accurately represent the specified splitNumber, ensuring that the axis points are correctly calculated based on the maximum data value for that specific axis. This would eliminate the current behavior where subsequent Y-axes inherit splitNumber values from the first one..
3. Customizable Visualizations: Users would have greater flexibility in creating visualizations that meet their specific requirements. Whether dealing with multiple datasets or diverse scales of data, the ability to set independent splitNumber values for each Y-axis enhances the customization options available to users.
4. Improved Data Representation: The fixed splitNumber issue would result in more meaningful and contextually relevant representations of data on each Y-axis. This is particularly important when dealing with datasets that have distinct characteristics or scales across different Y-axes.

**Comment by Ovilia** [comment]
Is this the same problem as described in #19523?

**Comment by MatthiasMert** [comment]
You can adjust `splitNumber` individually for each `yAxis`. See [this example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxj-xUqQrU6AN0YANkq87uh4IAEQYAByCgC2AEZUHEQAzI6kDu6onujeNLL-QcoZnuGRMfFJKbAATKWwdiTWGXjJEFSEsKLZoWSUBbSR0CV9QmAi3QCMAKwADDx1qQt1tQAsi7VTAByLU6kze2sA7JsAbHMt7lmeObn5dMOjubDOuHgAktACVBhEUw1BMIxLVlosDmdNjtFts5iszqlTrAZidFscZmcrp4muhbHYANxAA).

But `splitNumber` doesnt always do exactly what you specified. From the [documentation](https://echarts.apache.org/en/option.html#yAxis.splitNumber):

> Note that this number serves only as a recommendation, and the true segments may be adjusted based on readability.

If you want your label intervals exactly you can make use of [`min` / `max`](https://echarts.apache.org/en/option.html#yAxis.min) and [`minInterval `/ `maxInterval`](https://echarts.apache.org/en/option.html#yAxis.minInterval).
