### ISSUE TITLE
[Bug] echarts-gl: error when displaying a simple surface

### ISSUE THREAD

**Issue by Hirnochse** [apache/echarts#19527]
### Version

5.4.3

### Link to Minimal Reproduction

-

### Steps to Reproduce

**This is the code I use to display a rectangular plain surface :** 

  option = {
  tooltip: {},
  backgroundColor: '#fff',
  xAxis3D: {
    type: 'value'
  },
  yAxis3D: {
    type: 'value',
    min: 0,
    max: 6
  },
  zAxis3D: {
    type: 'value'
  },
  grid3D: {
    viewControl: {
      projection: 'orthographic'
    }
  },
  series: [
    {
      type: 'surface',
      wireframe: {
        // show: false
      },
      data:
      [
      [0, 3, -8],[0, 3, -7], [0, 3, -6], [0, 3, -5], [0, 3, -4], [0, 3, -3], [0, 3, -2], [0, 3, -1],
      [15, 3, -8],[15, 3, -7],[15, 3, -6], [15, 3, -5], [15, 3, -4], [15, 3, -3], [15, 3, -2], [15, 3, -1],
      ]
    }
  ]
};

### Current Behavior

**This is the result I get:**
![image](https://github.com/apache/echarts/assets/157098535/1662151b-3e6a-46f4-921c-29f13303b17b)

### Expected Behavior

**When I edit the data-series to:**

      [0, 3, -7], [0, 3, -6], [0, 3, -5], [0, 3, -4], [0, 3, -3], [0, 3, -2], [0, 3, -1],
      [15, 3, -7],[15, 3, -6], [15, 3, -5], [15, 3, -4], [15, 3, -3], [15, 3, -2], [15, 3, -1],

**I get a correct rectangular surface:**

![image](https://github.com/apache/echarts/assets/157098535/1c33d4c1-9495-4aab-856e-65444361af8b)

**All I did was deleting the first data in each row:**
      [0, 3, -8],
      [15, 3, -8],

### Environment

```markdown
You can reproduce the issue by pasting the code into the "examples" page on
https://echarts.apache.org/
```

### Any additional comments?

Is there any further documentation I overlooked?

**Comment by helgasoft** [comment]
not-a-bug 
This is about coordinate ordering: X values need to change first, then Y values. As shown in [surface.data](https://echarts.apache.org/en/option-gl.html#series-surface.data) example.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?gl=1&code=F4YwdgLgBAvFAcBuAUAEwIYXbKBtAuirgAwA0UAjAKz4B0AtugA4AULAbgJSwB8UA3sihQAZgHsATlBYBLHAFpQkRFDkAeOPIoqZAal3dBw4Riy0mAVwDOACxa525AMzkZ-TimNQA9N9PpzaztcGWdydncVXygQSQkAUxBoAHd0AE9yZMkAaysoZJkIGzELaCtJCCEoAF9kao9kaJEZAA9RSShJGQBzGTB0ABtZMFiJBKTufzRMAPKJCDZ0cgAjbhg-dFwAJnwoeShl7cjkWLBygfjaAbFuln8G5DEmCBkxMBwjKAgxMQGXpgAXAJqqQqst0CBst0JCUwKgAMK_SRAgDkAGIRJiUaDhC0AIItGRWJwAESB_BBVTSBKJpPJUHofSBZAZ6BaQIAbDUcVBgDTiWTgTzoTJUHSBFVhOwZPFkojIDCBuTJcYmDCAFaJF5vVEVYrQ5g2GQgFEq2rCSnCKzxCQyqxA3Aqz5eCBpJjxVFWCwSEQQ-LYlXCAoJEQSdD0D1CwNQfxAqZec1QfB1RBAA)
![image](https://github.com/apache/echarts/assets/13038071/2024f511-0973-49d9-a3e7-5a05b876a58c)
📌 please close issue if problem solved.

**Comment by Hirnochse** [comment]
Many thanks for the quick reply and the detailed demo code! I was able to solve the problem in my code with your help. 

I had read the series-suface.data example before. However, since I am not dealing with a surface parallel to the X/Y axis - as in the example - but with a surface parallel to the Y/Z axis, I could not use the series-suface.data example exactly. I must have mixed up the required order of the X and Y values.

It would be nice if the documentation for this could be a bit more detailed. The required sequence is not described there in text form, but has to be guessed from the sample data.
