### ISSUE TITLE
优化这种日期和年份重叠怎么优化 各位大佬

### ISSUE THREAD

**Issue by zhaohuaT** [apache/echarts#19529]
### Version

    "echarts": "^5.3.3"

### Link to Minimal Reproduction

。。

### Steps to Reproduce

<img width="883" alt="image" src="https://github.com/apache/echarts/assets/20346995/8158afda-a68c-4dcb-9f3a-15c65b391a26">

### Current Behavior

<img width="883" alt="image" src="https://github.com/apache/echarts/assets/20346995/8158afda-a68c-4dcb-9f3a-15c65b391a26">

### Expected Behavior

<img width="883" alt="image" src="https://github.com/apache/echarts/assets/20346995/8158afda-a68c-4dcb-9f3a-15c65b391a26">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by zhaohuaT** [comment]
目前只有这个办法吧。 hideOverlap  用这个隐藏重叠的标签

**Comment by plainheart** [comment]
考虑试试给使用 [`rich`](https://echarts.apache.org/option.html#xAxis.axisLabel.rich) 给年份和月份的 `axisLabel` 添加一个垂直偏移，也可避免跟较近日期 label 重叠，实现年月份 label 和日期 label 交错放置。

<img src="https://github.com/apache/echarts/assets/26999792/5b087ced-a1ea-47bc-b3e7-5b9e1273f1f8" width="600">

参考：
- https://echarts.apache.org/zh/option.html#xAxis.axisLabel.formatter
- https://echarts.apache.org/zh/option.html#xAxis.axisLabel.rich
