### ISSUE TITLE
[Feature] 如何获取map中label的坐标

### ISSUE THREAD

**Issue by GoldWood2000** [apache/echarts#19525]
### What problem does this feature solve?

例如在map渲染完成后，我如何获取此label的坐标
![image](https://github.com/apache/echarts/assets/52521162/caf22019-914c-4959-99c4-00dae017a5cd)

### What does the proposed API look like?

获取map的label的坐标

**Comment by helgasoft** [comment]
It is hard to get the label positions from ECharts, and much easier to calculate them from the geoJson map file.
The [official example](https://echarts.apache.org/examples/en/editor.html?c=map-HK) reads from [this geoJson](https://echarts.apache.org/examples/data/asset/geo/HK.json). The file has all provinces and their contour line coordinates. For each province you need to sum all latitude and longitude values separately and calculate their mean.  These two numbers will be the geographical center of the province, i.e. the province label position.
