### ISSUE TITLE
[Feature] 添加迷你图（小图）功能

### ISSUE THREAD

**Issue by freedomdebug** [apache/echarts#19531]
### What problem does this feature solve?

迷你图，小图在众多图表中是常见的，
如下：
highcharts：https://www.hcharts.cn/demo/highcharts/sparkline
Ant Design Charts：https://v0-charts.ant.design/demos/tiny
antv：https://antv-g2plot-v1.gitee.io/zh/examples/sparkline/multiple
![image](https://github.com/apache/echarts/assets/7620476/f21a2a29-803a-436f-942b-533999def7df)

### What does the proposed API look like?

可参考antv
https://antv-g2plot-v1.gitee.io/zh/examples/sparkline/multiple/API

**Comment by Ovilia** [comment]
用多系列，把坐标轴之类的隐藏了，是不是可以满足需求？

**Comment by helgasoft** [comment]
duplicate of #17693

**Comment by freedomdebug** [comment]
duplicate of https://github.com/apache/echarts/issues/17693
