### ISSUE TITLE
[Bug] Y axis labels do not match with the y axis value

### ISSUE THREAD

**Issue by amreekminocha** [apache/echarts#19530]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-stack

### Steps to Reproduce

This is an example in apache echarts
Will be easily visible in the example link shared

### Current Behavior

Y axis Label values are not at all matching with the actual value
Tooltip matches tho

### Expected Behavior

Y axis Label values should match with the actual y value

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
Did you realize that the example is using stacked lines? [Here](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtSgFEAtnQhZKg2JQCq0KHACCrDrulABqEKw4wLABQR4AIhByOAxgbh7UOHRyDAAWsHbQity8ALoCwuiKCiaEsrgAZhQeAMwApG5msAqKOU2UACztFcQARsBgog5UbR2yDDD03Bx0IzhYBGByAK445SJiWGOkprL1mWBbSSeysFp0AG44floAkk4q0vydX3rDpH6aLTXdBgACeIHwHgYlhwimAclBs1GwC2xiyoIA4nQpLB6nQsFocMNzJY6DZKABZGBpSgAFR2NIA6mwabSclsaQAxBQ06iWXmoyhlX5EUEA7TAjDgyGUe74hl7dCEhQ4IGwaydGQ3aB0BwyxzOVzE4hgiFULDFJGyCxWdUARgATAAGdx25oO11Ou2u5r9dwAThdsAdzSDDrtTuFxH0si1sh1eqo3l80UCVpN0vNluNJNt1gdztdAA4PbA7f7vcHfe4HYH3M1Q_WI1GRbHOugEzKwhEojF0yDMx4LTx-7AbWT7QBWMPumte12Tv1luuwBtB_rN77GuPETtUBJJFKj00y4e8HNj0k2d1Bhul0OVhtL5ortf150t2Ax4g7ju6mUZFkuT5IU2btlKZpDmBNyXnmJZBv6s6wIGlaIUujorm6jZljen4_LAZT8AA3EAA) is it without.

If this is not the issue, pls specify more in detail what you are expecting to be shown on the yAxis.

**Comment by amreekminocha** [comment]
Thanks for helping
Didn't see stacked earlier

**Comment by TopTrainers** [comment]
> Did you realize that the example is using [stacked](https://echarts.apache.org/en/option.html#series-line.stack) lines? [Here](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAFUxDACcIAc0U45VOqQgBnPuiFFcK6K2lF0rOvQIBtSgFEAtnQhZKg2JQCq0KHACCrDrulABqEKw4wLABQR4AIhByOAxgbh7UOHRyDAAWsHbQity8ALoCwuiKCiaEsrgAZhQeAMwApG5msAqKOU2UACztFcQARsBgog5UbR2yDDD03Bx0IzhYBGByAK445SJiWGOkprL1mWBbSSeysFp0AG44floAkk4q0vydX3rDpH6aLTXdBgACeIHwHgYlhwimAclBs1GwC2xiyoIA4nQpLB6nQsFocMNzJY6DZKABZGBpSgAFR2NIA6mwabSclsaQAxBQ06iWXmoyhlX5EUEA7TAjDgyGUe74hl7dCEhQ4IGwaydGQ3aB0BwyxzOVzE4hgiFULDFJGyCxWdUARgATAAGdx25oO11Ou2u5r9dwAThdsAdzSDDrtTuFxH0si1sh1eqo3l80UCVpN0vNluNJNt1gdztdAA4PbA7f7vcHfe4HYH3M1Q_WI1GRbHOugEzKwhEojF0yDMx4LTx-7AbWT7QBWMPumte12Tv1luuwBtB_rN77GuPETtUBJJFKj00y4e8HNj0k2d1Bhul0OVhtL5ortf150t2Ax4g7ju6mUZFkuT5IU2btlKZpDmBNyXnmJZBv6s6wIGlaIUujorm6jZljen4_LAZT8AA3EAA) is it without.
> 
> If this is not the issue, pls specify more in detail what you are expecting to be shown on the yAxis.

so can you explain what the use and what it means of stacked line when you specified stack: 'total'? because i got into this trap too.
