### ISSUE TITLE
[Feature] 颜色渐变使用conic-gradient

### ISSUE THREAD

**Issue by horizonzzzz** [apache/echarts#19537]
### What problem does this feature solve?

是否有方法将颜色设置为conic-gradient形式？
我在使用中并没有找到设置的方法，只能用canvas画一个然后放到color里。

### What does the proposed API look like?

设置color：
```javascript
{
  type: 'conic',
  a: 0,
  x: 0.5,
  y: 0.5,
  colorStops: [{
      offset: 0, color: 'red'
  }, {
      offset: 1, color: 'blue'
  }],
  global: false
}
```

或者使用渐变色构造函数：
```javascript
echarts.graphic.ConicGradient
```

**Comment by Ovilia** [comment]
`conic-gradient` is not supported because lack of scenerio. Could you please provide the situation where this should be provided? If it's common, you are welcomed to make a pull request to support this. If not, you may find some hack ways or try another design.

**Comment by horizonzzzz** [comment]
Well, this is also the first time I have encountered this kind of chart requirement in my work, which is a round bar chart with gradual color change. canvas insertion is used to solve this problem.

**Comment by adithyaappu** [comment]
@horizonzzzz can you provide a bit more explanation on the 'canvas insertion', that you mentioned? I'm also facing the same issue, and my use case is a 360 degree gauge chart. 

![image](https://github.com/apache/echarts/assets/37062841/900bb933-f995-4fa3-808c-069c1ab414b3)

**Comment by jiayp** [comment]
> 然后

请问怎么使用canvas画扇形渐变并放到echarts里面使用？能指教一下吗？

**Comment by jiayp** [comment]
> because

![image](https://github.com/apache/echarts/assets/731265/f059610c-ca94-42b2-89b0-3c8c4a346c1b)
Like this AQI

**Comment by horizonzzzz** [comment]
@adithyaappu @jiayp 

`
import Color from 'color'

      const color = new Color(this.color)
      const canvas = document.createElement('canvas')
      canvas.setAttribute('width', this.size)
      canvas.setAttribute('height', this.size)
      const ctx = canvas.getContext('2d')
      const gradient = ctx.createConicGradient(
        Math.PI * 1.5,
        this.size / 2,
        this.size / 2
      )
      gradient.addColorStop(0, color.mix(Color('white'), 0.5))
      gradient.addColorStop(1, this.color)
      ctx.fillStyle = gradient
      ctx.fillRect(0, 0, this.size, this.size)
`

and then set `color: { image: canvas }`

**Comment by jiayp** [comment]
> @adithyaappu @jiayp
> 
> ```js
>       import Color from 'color'
> 
>       const color = new Color(this.color)
>       const canvas = document.createElement('canvas')
>       canvas.setAttribute('width', this.size)
>       canvas.setAttribute('height', this.size)
>       const ctx = canvas.getContext('2d')
>       const gradient = ctx.createConicGradient(
>         Math.PI * 1.5,
>         this.size / 2,
>         this.size / 2
>       )
>       gradient.addColorStop(0, color.mix(Color('white'), 0.5))
>       gradient.addColorStop(1, this.color)
>       ctx.fillStyle = gradient
>       ctx.fillRect(0, 0, this.size, this.size)
> ```
> 
> and then set `color: { image: canvas }`
> 
> Modify the code as appropriate

Thanks, you saved me.

**Comment by mstijak** [comment]
Is it possible to do the same with the SVG renderer?

**Comment by horizonzzzz** [comment]
> Is it possible to do the same with the SVG renderer?

i don't know, you can try it
