### ISSUE TITLE
[Bug] Cannot set minimum/fix margin between each label/item on y-axis in gantt chart

### ISSUE THREAD

**Issue by soniagtm** [apache/echarts#19542]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight

### Steps to Reproduce

1. Create gantt chart with the options just like the available [example](https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight)
2. Try creating with larger data (more parking apron index) or expand the y-axis slider or remove the y-axis slider

### Current Behavior

When creating gantt chart with larger data, it appears that the axis label as well as gantt item overlaps over each other or if the data is too small, then the space between each item would be too large and as I checked, I couldn't find any specific option that I could set to prevent this or to fix the space between each item vertically.

<img width="939" alt="Screenshot 2567-01-24 at 16 31 26" src="https://github.com/apache/echarts/assets/96282005/278ebd6a-46c0-42ff-a736-73cca2eaea3f">

![image](https://github.com/apache/echarts/assets/96282005/30756888-f05c-4d63-af7f-763816a5db5e)

### Expected Behavior

There should be some options to set the minimum margin between each item on y-axis so that no items are overlap over each other.

**Comment by helgasoft** [comment]
Actually the official Gantt example has very flexible dataZoom options set up.
I've enhanced the **two** yAxis dataZooms in [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=G4QwTgBAEgogkgcSgFQPoCUCCy4HkIC8EADAHQBsA3AFCiQAicAsqgMLYwK7oCaqcAOXowAGoRI06ERixxMYqTOnRwAapgAy4gIyTw05qjkLhABSXIAquhjiATHobZMqAFq5cLTJeS5UTXFUFZCh0XGRkDVsiAGZiR2lnNw8WEX4BAGU4YXThMSJdWn16JPdPVD5BLJzBPPEYhJLkFzKvHz8AoNQM0xgYenEyByKnZuTy719_QJMYZBhWNCUYFwB1bJD6-JGIVAATMBAAcyOQACMAGwBTBP3Dk4BLADsjmAvbg4B7AAcMgAsQHtPgB3D73I7PI6sACuYAAzp8wLgAGbIuFXAAu4gA2sQADQkAC6YOOEJeyAeAFsrhori8MX8SY8XugrgBjRF7ME_VkcsBcnaoNngDFXOEPEBPEQAIU-0KeezhOOJguFYFF4slPFl8sVytuh2B9BAGJAtxA0Ixn2Nptcn0-lMwTypJsRNAAJKQjpiABRhcKocybADUEAA5AB6PYmkARkBw9EYqMxuMPMDfREYgC0cLZfyue2h11IACsEU8wwTkfK2RiHp8nhAfYabSAAJQQADe1AguxbMfE_dNNF7lIAnqwAerSIncN86w2fT6fgvG0RKSAANZXOern1tg80AC-bZo1aetfrjY3293V_3XZ7EDAmNhje7vd7Vs-Fzr3wAXF2R54k-vaSi6q6AciIAXOiIGfhAdYYtcgEfghiFXAAHhigFhggkoYlinzIhAmBphm6oQAAYhcDxHH8GKVqBn7XMiOHhmydKimAYbMcBzHRra9qUoB2LMb2aHoYhY7fFcuFwrRexXDxBLiZ-mGYJhDxwnACpYYB-Jqb2yIPL-ylMJ8Sm4cCVxblRpncUxUm9vmdEMYBdiGc5EBnJ8hEOgZ8HOXCprqoFRkQHSeweeQQVSQCCrXHAHJPP-EW9mG3wmn8_4RhGTDaGQADseLaNopAAJxQBVpAxGyWYACyVXiZAxFmAAcpDtXiTUNR1XV4jVDVsviACseIxM1NXaHinXdUNfzlXVTUVVmrWzV1jWkA1G3tVmQ2sNoNXjdo5C1aVo0UKVdikHYpXFaV5UVQAXhABWTTEeJ2L1UBnUVqh2DEfxneQAO9a973nUdFC_aQRXAFm5UNcDFCqND5DPU5zkJXs1wZA8z1yeG7XEAApFjUl5XCfwgvQmIgKZUEweian8VJknoRiMlE2GzzikpFPoQ80XhnzwtXCIgsIRpWk6XpmHhd5JlmWAFlWeGNl2Q5ylS5-IUiorzlRTFcXoc9wm4E8FnQuiqz5lcFxM7BVymwhlKfMAO5W3K6IWZ7gEYmA0JXKzruPt5XOyfJik6wSZwgGym5HGAcoKqwP6Irh3zPJuuu9mOmnabpSkKyQqneVTDvsqKeyttKCdJynur_p24C2RkXMoZ2HIXJnYYvnsYZHmzzlnEH1Md2OXc-ZyymrMLDL_ndM_8sp6e92A_79wWQ9h6OHtXFAkq41ck9dz3fcD5WEA_AnDxc_-2gj1J5sOhonyJwHQcuxFwILzlEBCp72fG5diQCIpWgAhAIqXlR5-StCJCAnlgH6zChACq40IrG0AcQWB8Vj54wJkTPB6Fqa03pozCA0FnahzUhzBCkceZiwFuXZywtcLMKuDwPOEAC6y2LvpMuEAIqoPYhg4B2DCokIQq_Skltra23to7KhzMf7eXdp7eRPsrh-yJoHYOwCNFewUVcO2VwHZf2DqzZihJTbJ3YeHUhNNgSWLUZzH4gEYFh18v5RByC1KsTAbgsOYBQEeWkT5BuydU57HXpncMABiVEyJda-VXmAeeexF4kD4qbGW2lUJqUYbhOs1JdYZnFJBcMkDdZwm-LRDEGhnhE3oSxZpZ8WnpQgBfTeEBsRhgSTACq_QqJUTDISCKR5aFSRALLJpTxOneTIS4lRNCpLP0_LM7SFJP6OKkrRBZHTCneV7D03CCSKp2AqpgaUmBeLeSmessOWy4QaHOBYvZ6EzmJMudc25PDOFOzghFGCdFUocS4jraxCENl8IKZ8sCssdmblQhAZZQKrgQA2b2OpDT5ktLRc4jFWLnlzOaai9Fqz0QkrUi8t5ZwPmdkJSCYl2KICUmeIbN2szAKoCHCAUgWUwCbkhJgb4KcnikEEgK649I_i5OYuiUJYpRJ0Iig4sMyJaL0QxK2HhxSOI2wQTwl8ekwBwFFIg01SkwD4SeIRC1VxKTAL2FSOk4oGxwl5fy0gWrQFSrdU8D1QaJEXksosk5pdsQyCMMwBQSgVDqA0ASGNxhUBmAsNYGAtiuljkAjG9g8wuC8FyKIYBX57S_geFA6NhhC2cG4JUIQZaDCyDjYoZQahNApsMGmjN6ArA2AmQ8l1MZvUgCNDGX12qGJSpjNM9CrSvzc1wmyI1DoTVRWUo6q1W6wCF1ee8i4O6XWBuDV6vsE7WyCvACKl4YqJUBupEGq8cJQ0cnVku9SgFEblt4QZSZo7TTjsnaaG9wrRXiobHOsDG5vg-nPJeBsTZ75OoJM8EuHYv29hfBiN8fSMNYUJKQFKwoMQ-lQ5SU8ky2zQs_MOrFx5qCIdXM-PddqHWWp9EKkAlI30QBANnLDT4pBkauEcREY4BGYXEIJh4pBQAXGDj6AtHBi1NryNR3sUhSlXEwGAUJinZPZxI_afkPpsRyYUzBZTqb20Jq7RoNsBIxMSbAFJ-WhItMQB026umQq8MvmM_JjknILNWcU7Z3t7b-2DpgM57pJpxOSek15kcPn9Chf5BkMcSoiA8b46ZzkOW4TpaFCKMUEopQ6gVHCXEhJxBZb2CV0gmEytqg1FVmUMS6vaAa0QJrLWZOhkG7l0gf8smMifOV9UlWtQ1cVPVxrZnmtjbHO1irmonjah69iPry3itrYgCNlbLXXI6vS1IeOYBaRyvELp_zIpYRXCW1mRCbr9OGZgvV9LeUIAIExIhfMEBzsMm6YiF8dSGx6itBAWVRwwfaBvo2McAnZakBE_oa7UArigOCzOIhFn8SAK83thrAAqaA8AkBoCwDgXAl39AyaILpz7DxFM_cx5AVHLOPsGfZ99_bb3se44u1zqhM6MQCGhJSBlkAiARZs1cH0MQOyhjDGGRnkA_U6ul7Lue_9xDsinBiOEvrEQbgxF6TEyAsIYl5ORnXDE9dy7bON_-WuMLYUIMxa7t2Ed_AgAAPgl6Al3BvJvHYgA1YgEAABkceIDDciTdukAfg8FBJmpAA_KH3XMu5dqVwpr8XL5awCAtzBRrtFvgO-lGOB33HwC8f4xzUumFTZ5t4abCb2S_dp4ZKbc77kU849AU-E8nuy8YlUHAUw1fq114b9XJvhw-MEjb4BDvzEu9jh7__QC_e7sRiQUP0XI-Rfj97JP0v1dbfe4GzXpfjeCut-Yu3zvgE9_MV7wAo_Aez8wlR9z8MQJ9vNcN8MOYDUwxoloRvhBY8xTIDg6RVV2YIEV1wxp8AUjgnhEQiYABCafCvMADcC4FBAEKONjcvSvMgkRTuImKzEKKeZXWjJ5NVCODA7eWsbA3Al8QCQg6uWfefBPCAfAxXJTZXBqZzERCgomafIQlBegwCRg-gn0JlZWZRAZPYPYM4OIM4MMLFVg9CNlL9aArA4BMFPA_g6fe_DEcgwTOQu_O3RQ5g5QkzJg64NQrpDQkpQ4INIVLiHhHFQOT4bcXwyUOpNue1IIr3diUUbCP9eIjEeyC4TQpJVEe5ZyE8OjXsBjI8JjFjK8NjM1A9elB2HdVfFvAkOTYTbTfQHnATEzJrInaokzSLZXYgNsUnPrdLB4EiH0VHAAHggFfyK2yyO1DFGlqM_AgLACeHS0eTY0C3fGYmgNgPgNNgqXvivFEiAV4RzQQkQIuGQPBTEjQI4MoMymyh4WpgcOORORFjDCYHxFjw0HxCzE8ggA0DiDxA-Nj1YAajuj-IgBiG6kRggFGneKRw0C8XBJhJeIgFcBiNLgiQQi7z-L_V_0AgqlRM_GH3Yn8ROThxADHDlHYjDA5E9h4kAzoNcIRXQh8MSRiHIHajZHIDZEyPWQXQQlMM4KSJuKUPpOlg8h2lzR_U-i6SSLcPk3aJ9G0GkKJKSNUGUjrGFAuEwG1XBTDB8WNUSLtw1LBVXUhRUklLtxSLSOSU5OMO5M_F5MuP5JcJQiFO_WgUwSJPRLulNOwmVPVAeDVINJwNwh1I3T1OwgDK1M4ntVji9PYnEOUzsAVJOSSPNPOVwWICtJhRyIgDyIKJrFYzZCf2rnrxf2b3XyoIxGmNmMbGNxFDN2TkEz-D9JI0LNrGLJX2nw33f0AlGNGzN23zRO7NLLN17NIG_wQixJGKHLGNWzN1_0AJ1UHLX2HNOzG3xLAOPCAA). The red slider only moves up & down. The pink dataZoom is the aperture(width) of the red slider. Using both can customize the vertical resolution to your liking.

https://github.com/apache/echarts/assets/13038071/190e51f9-443d-48a1-a13e-8c261a95d77a

📌 please close issue if problem solved.

**Comment by soniagtm** [comment]
Hello @helgasoft 

Thank you very much for your help! The issue is that every time the chart is rendered, the vertical resolution will be set back to default, and it won't work with different heights of the component and a different amount of data _- assuming that the data for each day is unpredictable, meaning that there might be many more parking aprons or just some_. This might pose a slight inconvenience if the user has to adjust the length of the slider every time the chart or the page is reloaded.

Are there any other ways to solve this problem?

Much appreciated for the help, and thank you in advance.

**Comment by helgasoft** [comment]
> _assuming that the data for each day is unpredictable, meaning that there might be many more parking aprons or just some_.

If a chart parameter is data-dependent, then the developer's task is to set it up accordingly. 
For example add a function to set dataZoom [start/end](https://echarts.apache.org/en/option.html#dataZoom-slider.start) based on the number of data items.

**Comment by soniagtm** [comment]
I was thinking of the same solution, but it would have been much easier if there was a configuration option for this case. 

Thank you very much for your help; I'll close the issue.
