### ISSUE TITLE
freeze 3x on svg even we are not interact with the svg nightmare

### ISSUE THREAD

**Issue by neonarc4** [apache/echarts#19544]
svg performance is odd on scrolling then any other library compare to apex chart ,chartjs and many other  

look ur example https://echarts.apache.org/examples/en/editor.html?c=scatter-stream-visual

try set it svg and scroll up and down at left corner u will notice urself how lol

**Comment by neonarc4** [comment]
![image](https://github.com/apache/echarts/assets/140290288/a6dfdce9-29e0-4d6a-99a2-75a4ca70d48f)
canvas performance is ok  
![image](https://github.com/apache/echarts/assets/140290288/13b7ef83-4bfc-41b1-b556-eb4a10d93f90)
look at ur svg 
![image](https://github.com/apache/echarts/assets/140290288/dc3453f9-82e8-4b5b-8b17-899128e8105a)

**Comment by neonarc4** [comment]
what going on ur library we not interact with svg why it freezing scrollbar ?

**Comment by MatthiasMert** [comment]
cant reproduce.

also note, that large amounts of data in svg will always lead to performance issues.

**Comment by neonarc4** [comment]
@MatthiasMert >.<   their is no large data it freeze the smooth scroll many time also the normal scroll i almost have like that something is very odd when u animation happen the scroll started to freeze even on 20 data point i have not saw this on any other library

**Comment by neonarc4** [comment]
@MatthiasMert  https://ahoak.github.io/renderer-benchmark/ try it i not sure what happen to ur library core svg issue other svg library animation are very smooth while performing scrolling when ur chart update it freeze the mousewheel twice

**Comment by MatthiasMert** [comment]
I dont notice any performance issues witch the echarts svg on my side.

**Comment by neonarc4** [comment]
> I dont notice any performance issues witch the echarts svg on my side.

![image](https://github.com/apache/echarts/assets/140290288/29d845f6-03a0-428f-a2cc-06e3279de9bb)
https://motion.dev/guides/feature-comparison

**Comment by neonarc4** [comment]
> I dont notice any performance issues witch the echarts svg on my side.

its quite freezing let me host my website i will share u my website link wait 2min i will enlarge bit svg so u can see the issue of freeze on mobile and pc

**Comment by neonarc4** [comment]
@MatthiasMert  https://turbobeta.vercel.app/demo/prototype try scrolling up and down

**Comment by MatthiasMert** [comment]
> @MatthiasMert echart svg https://turbobeta.vercel.app/demo/prototype try scrolling up and down try scroll this plotjs svg https://turbobeta.vercel.app/demo/photon

smooth  scrolling for both

**Comment by neonarc4** [comment]
https://ahoak.github.io/renderer-benchmark/

**Comment by neonarc4** [comment]
> > @MatthiasMert echart svg https://turbobeta.vercel.app/demo/prototype try scrolling up and down try scroll this plotjs svg https://turbobeta.vercel.app/demo/photon
> 
> smooth scrolling for both

yah it has smooth scroll enable both global app.vue

**Comment by helgasoft** [comment]
@neonarc4, try the official example with SVG and the following additions:
```
      animation: false,
      series: [{
          large: true, largeThreshold: 99999999, ...
```
Best demos do not include frameworks or plugins, just JS + ECharts.

**Comment by neonarc4** [comment]
do we need this attribute why not by default they enable ?

**Comment by neonarc4** [comment]
> animation: false,

didnt work 
![image](https://github.com/apache/echarts/assets/140290288/0413ad18-4b3d-44b2-b484-30faa5c6c170)

**Comment by neonarc4** [comment]
though i am using this https://github.com/idiotWu/smooth-scrollbar cause of dampling

**Comment by plainheart** [comment]
@neonarc4 Thank you for your feedback on the performance issue of the SVG renderer. Is it possible to provide a simple demo without any framework for reproduction?

**Comment by neonarc4** [comment]
sure i will do it tomorrow

**Comment by neonarc4** [comment]
sorry for troubling plainheart and bro mathias also helgas seems like the performance was ok overall i think this vue echarts or nuxt has some problem i will try to investigate further later right now i switch to canvas cause of insane performance on realtime

also if possible try using web animation api for svg animation to reduce to avoid that 1st post of mine >.< 


https://codesandbox.io/p/sandbox/dynamic-data-time-axis-vmvkjt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrv6s0kq00063569wyrx0fqu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrv6s0kq00023569hxzlikxs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrv6s0kq00033569de18lkgl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrv6s0kq0005356957t231dp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrv6s0kq00023569hxzlikxs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrv6s0kp00013569d6t2ttor%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clrv6s0kq00023569hxzlikxs%2522%252C%2522activeTabId%2522%253A%2522clrv6s0kp00013569d6t2ttor%2522%257D%252C%2522clrv6s0kq0005356957t231dp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrv6s0kq00043569683t78qz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrv6s0kq0005356957t231dp%2522%252C%2522activeTabId%2522%253A%2522clrv6s0kq00043569683t78qz%2522%257D%252C%2522clrv6s0kq00033569de18lkgl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrv6s0kq00033569de18lkgl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by helgasoft** [comment]
> switch to canvas cause of insane performance on realtime

well, if you can switch away from SVG, try _scatterGL_ and forget about performance issues - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=scatterGL-gps&gl=1&code=CQOg5gpgLgUgygeQHIAoBQACDAlBCAqA-gAoCC-AEhgNQYDkA9ACYCGULDLAzl9M2xwAWAewCuvALQAHAE4BLAMYQJLGRBYAmEACsuwgHZ0ANJgwAzUfoVQ5BjClbsAlBgDeprADdVGYVJt2ALxuHlgYNlAANhAAXCFhCeEQAB5QcXQAInJcUhAyXLb6vmYYIuIQGLKKFQBG3BBMvkVQghWq6sahCdFmafRK-lB5nYlhUH5xAAxdGAC-JqOe2aIskQCyLFJxrhgzWAC2cvpxAIwArBqTGkYY-yzJp2cAnE8AHJMLoxhMcvsQ-gUDKdPqNhPJ_n06J48jYFKsRl95GBBH0Th89uEJv0IcMQYkhqk4gBtOgUACSAHEKMZ6AAZBAAdToAF08Qk4ZEFKJIiwatE4lAZKIIGywkdsCx9JBthisAphJEwcS6ABiMwaBQAZhOLBpqo0ABYagB2dUsjGzGbzGbjBU2LbxL6CuRgSAydL3bI0hgMehyIb7GmBfTCDGerjEYRHIbux1fcIAT1y6QUMmEPDoFqtouSpGS2W21tGCbzBbcRcSvHBXGJ7njWH0LD-6SqShUal1ooSUCTsXoXDhUBjFNpCPjXAT-xqCrgcgAXn2zl2wo4WHFV8vLaNmaFZgBuUL7BMAYUEqigIF4UAQ_kKKD8AX0TgPWEtz6AA) 🚀

**Comment by neonarc4** [comment]
@helgasoft awesome performance is their 2d line and bar one as well for gl cause i saw only 3d for gl yet so far? >.<
