### ISSUE TITLE
[Feature] 如何实现x轴刻度线自定义样式

### ISSUE THREAD

**Issue by dadaguai-git** [apache/echarts#19573]
### What problem does this feature solve?

目前有一个需求需要更改x轴刻度线的样式，但是看了官网API 似乎没有更改这个的方案(有可能我漏看了),请问有解决方案么
![demo_20240131101103](https://github.com/apache/echarts/assets/35138018/4a83480f-b80d-402f-9262-799eb0383122)
类似于蓝色横线标注的样式

### What does the proposed API look like?

无

**Comment by helgasoft** [comment]
>  need to change the style of the x-axis tick mark

[xAxis.axisTick.lineStyle](https://echarts.apache.org/en/option.html#xAxis.axisTick.lineStyle)
📌 please close issue if problem solved.

**Comment by dadaguai-git** [comment]
> > need to change the style of the x-axis tick mark
> 
> [xAxis.axisTick.lineStyle](https://echarts.apache.org/en/option.html#xAxis.axisTick.lineStyle) 📌 please close issue if problem solved.

感谢
