### ISSUE TITLE
[Feature] markLine

### ISSUE THREAD

**Issue by postfaxcn** [apache/echarts#19584]
### What problem does this feature solve?

同时画x,y轴标线， x 轴要求：起始无，终止有箭头，y 轴要求: 起始有箭头，终止无，在一个serie中画不出来。希望 markLine 结构中的 data 里的每一条的 symbol 也可以是个数组，可以同时控制起终标志。

### What does the proposed API look like?

同时画x,y轴标线， x 轴要求：起始无，终止有箭头，y 轴要求: 起始有箭头，终止无，在一个serie中画不出来。希望 markLine 结构中的 data 里的每一条的 symbol 也可以是个数组，可以同时控制起终标志。

**Comment by MatthiasMert** [comment]
[Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMgL4A0asAnjvkUmRXgKYBOEThsA2hequgNhhKIJkQDkeAMYBDMGFbjyg9ABM5MolyQA3GQBsArmNgAWMsj1GTAJlKwICgLYBlYfpNIpwfcBYSAcxYmJmhxYmIAXWUVJxkWAGsAGQhoT14VdTBNbgyVXPz8r2A_VS07AAZo2DxKJwAjHwloGCZw0mLS8tIARgA6AE4ADkjiPJVo8cEeQpVOljLuCtIbatqGpthxeJZgAHclGrrG_QAlYGyFIhsAdmWjjf0AeQAzF-YwLXuAWh7Vsnmiy4dlgq3s6xOzVa4SmAkisPh-TGgmRsHhxAA3EA)
