### ISSUE TITLE
[Bug] Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### ISSUE THREAD

**Issue by dohuuhuy** [apache/echarts#19585]
### Version

"echarts": "^5.4.3",

### Link to Minimal Reproduction

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Steps to Reproduce

"echarts": "^5.4.3",

### Current Behavior

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Expected Behavior

Option 'target=ES3' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by dohuuhuy** [comment]
source nextjs  "next": "14.1.0",    "typescript": "^5"

**Comment by plainheart** [comment]
duplicate of #19560
