### ISSUE TITLE
[Bug] loading layout was overlapped by graphGL

### ISSUE THREAD

**Issue by AndreyPatseiko** [apache/echarts#19597]
![image](https://github.com/apache/echarts/assets/18285745/f8ebba43-ffc9-41ae-a4f7-44ecbca85e84)

### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=graphgl-large-internet&gl=1&theme=dark&code=CQOg5gpgLgUgygeQHIAoBQACDAlBCAqA-gAoCC-AEhgNQYDkA9ACYCGULAtGADYMsDO_aMzYsGASwB2UCACdJ0cLJYAHABYgAVvwD2kugBpMGAGYBXSQGMo4vRhRhl6gJQYA3sawA3FrIwQmSH4MAF4MR1UNAKCQAFtVFHMrGzsUaIhXDyxsjFloM3l3TxyMXQLLCAAuf0CIAG0ABgBdIxLs9llIKGr0uoBGFuKcn24zKowAJiGMAF8AbmKZ5wXh3wxLNggwHVlxCGCwuqaV7J8_DZlt3f2AWVVQ93nis4xJHSZ9h4j1EDeP_jiCSS1lsknsfwyRTa4hM9gAhBctjs9vw7io6hC6gBmJpNTLTLCIq4okAqMz8NQoLJtbKSFixcaYnEE2bLFlE5G3VQY971HFNB5QWRjE45GbTPJQApg6ltAAe1TuUA0ykkTB0sRQrgAVBgAO5SdV6kBSBSyADq4iYytaNIAnoq2CqWGqNVqMLqDa7jaa5BQIOIwGooLa2gwGBgFa9eY1BjSMOGMA7ox9-nGafw7bEAEY6bhwcQAL0ZMYm6baHNkyaZ5ZKIzG1T60yeYrZOVidoAwmpfFAQEIoAgVClJFTppY8ztqnUWXROtmUBMGliDBMsQBOAx9ACszkMs_nKAA7Cud6uN3vQyU52AF2vN2u-lvd_v4zeF2eJn0j-f15eD7eKBYg0z6_v-b6Hme34ACxga-NLvigfR9AAbL-z7gQhh73qB24AByYW0iGfhuW5HtBhHXthpF9A0EwYfBRHUZuUEvleOTEduBjQbB96URxzFbtBXE7vx2SIcB6GiYxVGAThfR4XhDHseJkHbg-NFsQBH7qaBfEyQJgEkZuPFiVgnHoXhR5mfQanoV-1kGapcnLnpF5OeZglQYpNmIfJIl0b5gn4cp2mLppQlaRBRmoW5f4ebZRkiViT76SpnmASeUlRVhSVSSlQV5VZcHpYld4RY-e7TLWWBCNc_DTiyso0lAdoqOMdDfGoADiAAyCVYBCDUpvspVYOkw0TWN6ybMS-zVJWJK6LIUCJBYIKpCwBgYNm-LxjkkrShgLC_PSEAYBwO2nQyoo0ks03cFIEBwK13DjM18YTtwU5lSwi7blxEwA6uwMNCAExVftszTeIMixC9dpvdUH00joKgsJYsPJk2UMzNNJg7BUpBQNwAgTMjLI5PwMgqMNT6U9k1No_gah5BSeZMI201YJosMyLI-B5nIEBWOMtHczUkDmgGQbdBgjTg9tAwSxEXhY9UIEM-NtTS4GwYAJKSCYowixUXNa6UGyPZIYAa-DDPivGjslE0ixtrMaBsh23a9v2ag6HqvU6CwTBSGAWpAA

### Steps to Reproduce

1) open chartGL example
2) activate loading screen (add `myChart.showLoading();`)

### Current Behavior

The GL layout is positioned on top the loading layout and interact like normal chart (tooltips are active)

### Expected Behavior

The same behavior like other echarts (not GL)  

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Did you forget [hideLoading](https://echarts.apache.org/en/api.html#echartsInstance.hideLoading) ? [Demo](https://echarts.apache.org/examples/en/editor.html?c=graphgl-large-internet&gl=1&theme=dark&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZwBSAygPIByp1ABHwBKHDgBUA-gAUAgqIASfANR8A5AHpcUOFAC0xADZqoSJMw1aoaonEYxCzBjCgAHCAgBWSVIRUAafnwAZgCuhADGcPjefKTETq7kfADeAQIAbrB8jLhMSHwAvHxxLm7ZuQjALqQh4ZHRpGWMiSkCrXwwzMF2yaltfF5dYYwAXFk5jADaAAwAuv59rdowTHCjjRMAjHO9bRn6wSN8AEw7fAC-NG1nVL0ZMHxhWozEqDD4jHmFEzOXrXcPTxebw-AFkXAVkhdbplCKhcB8IcVXAhYfCkBUqjUIlFCDFUU0egt8IEYgBCR42IHvJBg5wTfETADMMxmzVOAgpz1e1IQzmCKFILQWrUIUGAhwZzPZ5xuwoBlO5oJc9Lhk2ZMwhcBgB1-V1OHTgXVxQoWAA9RmC4G4nIRcKhgBQ-AAqPjoIh29AIIj2GAAdXwuCt82FIAtWmtUFt9sdLrdUc93tsckY-GIEDgwYWajUfHNfAZs0zfWzfFD-dVm22cqQIGAACNUPo2PgAF4SitHKvCzlAsuSrsLPYHUYbU5Qq6y1qgSCwRCmOAcZx1QiC05hRuvUYTaUqZZ10hHKaM3xHRkATl8GwArOQ_Du96QAOzH68n8-3ottXfEfeni-njZLxvO85W_fdXyODZHzfM8P3vH9SEZKYgJguDQIfV8oIAFlQkDhTA0gNg2AA2GCgLQ_CHz_FCrwADgohYCIg89L0fLCGL6AjqI2KYjnIvDGKoljMOAz9WiYq9fCwnC_w4r8hIvDYsMk685PEh8kLI1SBM4hTL1o2j-LEgQJP_YTRPg8Cr0UyTZJ0-SEOYi9pLUkyMNsljaMfVzVHcsjIO8-z1IQw8Xw82CgrckLzP0-jIt86KbMvXifK4li6KMyyDxipSLPQxySJQuzjISqzL0ZQDiqy58tLyyjHPC8qNlSvyvNwkq0qSgDb1OAdWlMYEkC3aUTWFOAQGcQ4VCRCAAHFMHigR8SG8s0RKgRGhWzb1vlLlBtGHtFXRLx4GqUJsXqKBfD4Os2TlNoDSNPgoBRMVGD4HQbte8VdWFa4dv0IhGDYcb9EOUa5XXfRN1KqADyvWyEZPJGpgQI4evu84dvwGxgBBkAwdGCHhVQZwoDCHGy1HTGzh2gAtQJXiGaQ4H0YwjiJ6U2iQGxnBWwCuf6uBSdECAOhQRtcBHHaBHcHGbBgURG1sRhwkOHiZbGJhfRTNNVj4aY0eurZNeKNJKdGZDBY28YddTdMAElCECfZVaGaXrf6R5AZIS20cFs5pUDhYZl6a5funaB4AQCAA0YbA8CIMhJ0DqggA)
📌 please close issue if problem solved.

**Comment by AndreyPatseiko** [comment]
No. I've activated preloader for showing the problem.
The problem is that when you activate the loading, the preloader doesn't overlap GL diagram, and you can interact with GL chart (get tooltips or zoom in). It looks like the GL chart has a larger z-Index and is displayed in the foreground.
If you compare [default behavior](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXEgL4A0asAHgIIUQDO-y56YAniAKaMDkAxgIZgOAc2AAnVtzLp0AE0H9GAbW4BZGFNjcAKgFcOm7gHUOsw9oAWuwwDExEQwGVBT3dG4BdcqXKsa9RlQZDHYuLQA3fmx9bm9pWDoOew4GWCVmJmC5BWUARgBWAAYSWAAmAGZistKAFhLS3IAOEtzy_JaagHZ6gDZCj3jgtk4ebAhoAwyici8iAG4UAFtWAGELfjEwADo6C2AAdwAZYH5ZceEACgBKOaA) with [minimal reproduce](https://echarts.apache.org/examples/en/editor.html?c=graphgl-large-internet&gl=1&theme=dark&code=CQOg5gpgLgUgygeQHIAoBQACDAlBCAqA-gAoCC-AEhgNQYDkA9ACYCGULAtGADYMsDO_aMzYsGASwB2UCACdJ0cLJYAHABYgAVvwD2kugBpMGAGYBXSQGMo4vRhRhl6gJQYA3sawA3FrIwQmSH4MAF4MR1UNAKCQAFtVFHMrGzsUaIhXDyxsjFloM3l3TxyMXQLLCAAuf0CIAG0ABgBdIxLs9llIKGr0uoBGFuKcn24zKowAJiGMAF8AbmKZ5wXh3wxLNggwHVlxCGCwuqaV7J8_DZlt3f2AWVVQ93nis4xJHSZ9h4j1EDeP_jiCSS1lsknsfwyRTa4hM9gAhBctjs9vw7io6hC6gBmJpNTLTLCIq4okAqMz8NQoLJtbKSFixcaYnEE2bLFlE5G3VQY971HFNB5QWRjE45GbTPJQApg6ltAAe1TuUA0ykkTB0sRQrgAVBgAO5SdV6kBSBSyADq4iYytaNIAnoq2CqWGqNVqMLqDa7jaa5BQIOIwGooLa2gwGBgFa9eY1BjSMOGMA7ox9-nGafw7bEAEY6bhwcQAL0ZMYm6baHNkyaZ5ZKIzG1T60yeYrZOVidoAwmpfFAQEIoAgVClJFTppY8ztqnUWXROtmUBMGliDBMsQBOAx9ACszkMs_nKAA7Cud6uN3vQyU52AF2vN2u-lvd_v4zeF2eJn0j-f15eD7eKBYg0z6_v-b6Hme34ACxga-NLvigfR9AAbL-z7gQhh73qB24AByYW0iGfhuW5HtBhHXthpF9A0EwYfBRHUZuUEvleOTEduBjQbB96URxzFbtBXE7vx2SIcB6GiYxVGAThfR4XhDHseJkHbg-NFsQBH7qaBfEyQJgEkZuPFiVgnHoXhR5mfQanoV-1kGapcnLnpF5OeZglQYpNmIfJIl0b5gn4cp2mLppQlaRBRmoW5f4ebZRkiViT76SpnmASeUlRVhSVSSlQV5VZcHpYld4RY-e7TLWWBCNc_DTiyso0lAdoqOMdDfGoADiAAyCVYBCDUpvspVYOkw0TWN6ybMS-zVJWJK6LIUCJBYIKpCwBgYNm-LxjkkrShgLC_PSEAYBwO2nQyoo0ks03cFIEBwK13DjM18YTtwU5lSwi7blxEwA6uwMNCAExVftszTeIMixC9dpvdUH00joKgsJYsPJk2UMzNNJg7BUpBQNwAgTMjLI5PwMgqMNT6U9k1No_gah5BSeZMI201YJosMyLI-B5nIEBWOMtHczUkDmgGQbdBgjTg9tAwSxEXhY9UIEM-NtTS4GwYAJKSCYowixUXNa6UGyPZIYAa-DDPivGjslE0ixtrMaBsh23a9v2ag6HqvU6CwTBSGAWpAA) you will see differences.
On the line chart you can't interact with chart - tooltips and zooming don't work. But in the reproducing example all this works, even when preloader was active. 
Also in GL, it seems that GL chart is placed above the prelaoder.

**Comment by helgasoft** [comment]
But the preloader is not supposed to stay together with the chart. It is temporary in nature and meant to be disposed thru _hideLoading_ - see  [showLoading API](https://echarts.apache.org/en/api.html#echartsInstance.showLoading).
Why would anyone keep it there?

**Comment by AndreyPatseiko** [comment]
I want to change data for the same chart without clearing data when fetching in progress. Because I think it's not necessary step.
Thanks for you advise about API. 
I found simplest way to get what I want. 
`myChart.showLoading({ zlevel : 11 })`
