### ISSUE TITLE
[Feature] Sort bar chart by series weight

### ISSUE THREAD

**Issue by AntidotUser** [apache/echarts#19596]
### What problem does this feature solve?

Version
5.4.3

Link to minimal reproduction
No response

Steps To Reproduce
When drawing stacked bar graph in echarts the series in each stacked bar are sorted randomly.

Current Behavior
 
<img width="571" alt="weird order" src="https://github.com/apache/echarts/assets/159126129/92a1f4ab-d08d-4b0a-88ac-1974ffb9e364">

Stacked bars are sorted incorrectly.

Expected Behavior
The series in each bar should be sorted with the highest (at the left / bottom) to the lowest (at the right / top) based on the value of the series.
Please take into account vertical and horizontal bar charts.
On the example above, on the right bar the blue series should be between the yellow and the red ones

Here is a dos and don'ts image:

![dosdonts](https://github.com/apache/echarts/assets/159126129/a0d2ce66-4a20-4665-9989-52775fefacf2)

Environment

``` 
- OS:
- Browser:
- Framework:
```

Any additional comments?
Any configurations/options in echarts that can be done to achieve this would be helpful.

### What does the proposed API look like?

Ideally, a "sort" boolean parameter on the "xAxis" and "yAxis" options should be enough, which default value would be "false" in order not to break anything already existing.

**Comment by helgasoft** [comment]
Sorting is data preparation, done by developer.
ECharts is just a display machine, no AI yet.  [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYZwBAvGDaBQYwMwCYAMAaMjXM9gjHogCx4CcGW2eaAuuvDMmpvgBy5j5mFjImZkFIpUTZ6jaB0psUmCrzICuQyvjFqUqWrFoBuWKAB0AMwD2AJwCiAQwDGACwAUTgB4BKSAD4wAb0YWAKYALgCuFgB2YK5GIJbBTiahEXbBAJZmUU42mABGnv4ICEFhkWA2YAC0YLkGCAC-7gaNBqDQ2kbJIA5pJgkA5AAiaUGp_U2GIND4tJ0R3b0DALI2aQA2YACCwOOtU8izXT19Tv0AamnAgWZbOxPGR4tO0P0AtjbBFmmu_Zj9S5lfmB-gAVUKBIH9ADqgR2fxBDlCkIAYl9IQBlD4Y5L9WgTXI2CyQPyMYIATwADoEAFzAgkWX6MEDBewAa1p_WCZhZa0ZCBAgS-gRAABkbGSzKFggAhMkcixmADufLAaxsuUCa1pvjA3SVtM-4LA9QYCECrwpDhsIDSIG1YHMdlCduBAqFIH6xtg9QMsDMFPSmWJhTAXLMa3SFO1jAQnzSAHN44KOTZXLaVQhU7aAApmNIRYLJvyhyk011W4BKz31RgmxhrQJJiLAbV1hCuTZpl2-NtgMmd2328lUjl2D6Nyxk6umsDAD7WkL2uLhOxl0DGmdutLC2nQel5QkHiw6H1AA).
![image](https://github.com/apache/echarts/assets/13038071/fa867abe-7180-41af-9a50-8fb8a5b185ee)

**Comment by AntidotUser** [comment]
Thanks a lot, I'll do like this.
