### ISSUE TITLE
[Bug] Broken diagram when zooming out with the mouse wheel

### ISSUE THREAD

**Issue by wrfz** [apache/echarts#19614]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-time-axis

### Steps to Reproduce

Zoom with the wheel so that you only see the years in the lower timeline.
The error occurs if you zoom in briefly with the mouse wheel and then zoom out again abruptly.

### Current Behavior

Part of the diagram is painted over with another part.

![broken_chart](https://github.com/apache/echarts/assets/77174685/182c60ad-f144-4aee-be48-710a7ca8503c)

### Expected Behavior

Such render artifacts should not occur.

### Environment

```markdown
- OS: Windows
- Browser: Chrome, Firefox
```

**Comment by MatthiasMert** [comment]
set `animation: false`

**Comment by wrfz** [comment]
Thanks for the hint. The workaround helps to avoid display issues.
However, I would like to leave the animation on, as it makes working with the charts more interesting and pleasant.
It would be nice if the bug could be fixed.
It also doesn't come across well that the issue occurs with the standard example without changing any settings.

**Comment by plainheart** [comment]
#18960 should fix it. Feel free to try the v5.5.0-rc.2.

**Comment by wrfz** [comment]
Thank you very much! I cannot reproduce the error with this PR.

**Comment by wrfz** [comment]
Closed as the error has been fixed
