### ISSUE TITLE
Tooltip on axis labels which are truncated

### ISSUE THREAD

**Issue by kelp-harshal** [apache/echarts#19616]
### What problem does this feature solve?

get full view of labels which are now truncated

### What does the proposed API look like?

{
      gridIndex: index,
      show: index === 0,
      position: 'top',
      type: 'category',
      data: this.graphData.map((item: ISourcingGraphView, i: number) => {
        return {
          value: i,
          textStyle: {
            overflow: 'truncate',
            width: item['show_group_by'] ? item['group_width'] : 0,
            tooltip: item['tooltip']
          },
        };
      }),
      alignTracks: false,
      axisLabel: {
        show: true,
        position: 'top',
        interval: 0,
        formatter: (value: number) => {
          const showGeo = Boolean(this.activeGraphType?.showGeo);
          return showGeo
            ? this.graphData[value as number]['geography_code']
            : this.graphData[value as number]['show_group_by']
            ? this.graphData[value as number]['group_by']
            : '';
        },
      },
      axisLine: {
        onZero: true,
      },
      axisTick: {
        show: false,
      },
    }

**Comment by plainheart** [comment]
#16315 is for thos feature but it still needs discussion. You can refer to https://codepen.io/plainheart/pen/jOGBrmJ as a workaround.
