### ISSUE TITLE
设置k线图xAxis.axisLabel.showMaxLabel:true,强制显示最后一个x轴标签时，标签显示不全，被截断

### ISSUE THREAD

**Issue by soeasyjx** [apache/echarts#19615]
### Version

5.4.3

### Link to Minimal Reproduction

[demo](https://echarts.apache.org/examples/zh/editor.html?code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WgPT2YAURXAAFjACWUIgFsALhgQBCIwQBh_4HQIInD0KSJocPcvAHN3RKhtBgkVKBVSBQgEVB8AETyVAAoAbRoYGBq8a1IARjV7VvtrABY8ABoYazUWgDprADZB4bHJ6dsAdlG1abUJ61GATh6AXX76xua2jq7rAFYBobVyec3W5fm-PnGpq4tlvj2Dppb2zu67LczsszqsehNRqChtZNsC1FDhuCttYvg0fsd_jDLoiltZrKszs9NnxVmolvDVhM1KNPvs0Uc_l1rti1qRRgsEWo-BseiSrj0lnxNqs-NSFhNUYdfid7GpWizRaMeisrnxgT18VcFvdhqs7jSUXSpRjrJ0WQslj1WtMrZtRqRNcMJnazgsbdZ7q0zpL0X9TX13cDNo6Nc8vTbWktCTaemyuT6GR1TRcI9ahsrqe0baRqSremSlYbvonuvYJtjlRsJnz8z0lTWNUs3emrey1AnpaWFhXrqNnRHnmc82ptuMQ2pqUKOyb7ID060IesbSMlRG6z0Y9Sc9O_Z0571W3d3fczq9el6lXmeteaTuk51NhXZmeuRsj1rqUP3UtSAs76WWgVakemFK5NiWVoazJNkJjTYZwK2XYjV9e8PXNZ5uVWc4tk5Ug7UjVYFgwot6U7U08RZPFENWVo6wXVZ3nFUk2Sef9yJTK4xiXTjgUwq4LzaUlniItjunLGixQ3aFNlzKS8SFGlQMRNltVE6xu1uJtm2Gdox1uDYcywusqTU_cRg2EZKWBM4lOuIlHTWCEF3_E4WQmOszjk-EXTgicWJfZ0-29ZCSw6AMrhXCx5gWYD5hs8ZOQnSEkOLTsOg4vEFjrPhfMmZY4PUtlcrDFLSIxDpxIi6lYLBCCoI9PsCXua8XPsDT-TZa8jPGWzSDrdSCQMkjjT-DozLyjUaOeGr-I82ykomP8QrSzp5Ro4yoNaNkbNuCFo04tlNglZbys6awWTw0Z6OhPhF3mdyaWHJKYVa9psVsDYCOhKktm085qXOR4IQnV7wrxM5gQtaK2VsOLcwK8Ux1ejLJjtOVoueOTzlIGiDNpVLTsg97Fp6-ZY3tR14PGBGIVIYKCdGh93pvOZoVdS95kiynYPy1rALipsvMjZY_vZyb-MFY6GY6JM1v454PW63oaPuF9exyvnzqw5qsIVza63A0lhpQ2Vugyic6yyrCIQWBzWjtd9EWyzY-cqnTBxrGElkWx5PTth2XZOxn1PezY0agtoXkeWzhnrPn93Uz8ESdB5oRXR3E8hemyuDx9OcxpSU-4vFbBpAqkT4JbpfsHozXmGElTPRFV2hdT8rJ6lYX_WutbTg368F-vOqxodC272V3pXftW-BGF5mFwHoVbNRSpGsLZ2xe2IWV6FWhPJTIJgv7Wg2Gzx7z3f1T-7CocvpU_pXttx6297ei2PM8Scj-T8hJukr65-cs8RrC2J7e2Wd564ibhqOOQd14n3epBe0hdSA209n1JUWM8qTGfhle2Ds4KQXuNsaYkZyQoINoHautcFyb0ClSUho41SkImJDGsW9LzP3ah6WE9o8z20nKQoi99GFRlaM_fcRCDSiMakMSM6osaoL4c_C-eJI4nzJsZRR21PZnCKuIuBNdui92ARCLGMCvrAI2KzPEPRgQn3HsMZmVZHSQQ8nJSCGwcpkxcY4sGkFyTJyQZZORfA6IFTyg4wxPcUa6XtowtGhD9TMNbsZds0SxLvRzIpIRSxHaRknE3LakJ8Y53St0TeCwVLsKyldVxPNaJCLtKw_8ZwJ5NPtMnOmkIOl03rl4gx1c2luw9KfTmnpj5jLTrTKuZT7BtO4ZlGkf9rLHztF1JeMMpZzLaQnGBI4ybA05uqSmENqatPsKo3oEIjqczfNfe4XIyaSwuS_euxFDmPXrrxcu3tZlr3mZ0NQzNvae0PJTOUywm56JpNnAFbTaKTyJJA-0BVumV05g7dJQzOixJ_IXN-YDPye2wvbV5IyGorzivcbxu8VKiy8f8k2CLFkgTLo8RlZNMYFSeMgi5_MbrAw_mHLYhccpbAYmjKhOzuhAK9ldXy3S963CKg5bp2KZUUQYmKXCPJ9Ic1mldUp8LujAtuJOBGwIfbQlqYqg2cLmXdDBrYZqydeVfhtTDZOwZITSpNSHIGfYm4yXtJ7RUJC3j3CZSWNpthQ6xU4o8ym4qBRYU-vy1RIxPxeTfg6bWV1tIW2WBqk1zIaLb05MLDkNFOox0hsbGNsogEjBUl5cgvrbho0LdhIc_4JjtLeDDAqIrF54lHMq_iwES0m37c6hCCMeTc0tsGiCfb5nvSqeyBGh0P4TBYn9RGt010jIesqHxCqyZsl_PdRcfqZ1tWcVHOlEroTdOvWzGC06Sz9reowoqpDeQglIdg1xmwio7BoDsAAlLQAAZnAMAwAoBeHADAYopQoAVHyFUDAKgpBYZUFBmAABvA4YhYDADyEQVImAACeBGFA1B2LQBo5GYAADcVCoDgIkRjzGDiwfkFUTjWAvAKFIFQbwMAAA8MBcP4cqKMVAYRUhQHcJJrwABqTTRHSMNFY1RmjGB6OKYQHACA7gcN4YIzULwOxRjoa8MAIgVQcYwFaFBmopBoMsf05x7jiRRhmYs1ZhT-RbM-YOAAXwOBgIgUA4AYDACRg4BnfBGZM_kIIlH0t0YI0aBo_meMQCCEVxI0XaAxfg4h5DqHKOoGAHAVAVGACyAgqiqFoygBDUBdMHBE3JxITXYC4CY75wTWBhMqFE-JwYynku4FUPkNkZWIBKZU2pjTMmYDzY09pvr-nvCwZgFUMTsnOvdbAL1lLh2GhxYgMNoL5nLN4AALR4Bg6l_T9BkNgB475hoMXDsDYe34cTAOYATZOwNgAVuDmAcPzsqC6yAHrkmYf7Zu7d0HMBNO4E00tgooxVu2ZgK9hHOwajiIh0D_T93HvBcszjpwF3UdXc-4D2L8XEvJfp6gKAlWaAhFqwtrHyGoDKaCHp_TvgAAeUAgh4EAFBygBB6MAODGgAHUwGF95TsGFcwFINFo0UAQBoGQwgKXX2oAYDSKkDgiuVCy68BAbXh3HfO4AAogC8Fd-3WPDtQFo6ERXwAMAgAgC7r7tOotGmU3bsArBLeHcJ0EJogBT0wANKXDwG1jiOeBBvPwG1gV-fmQQcB0aVINvE_-520QPXQQtoFbk2kdw-uWjN4AEYgCgCbwI-AvQAFJXfffAPkH3AAZFQneiCoCCNbnjRuDiy4EE7krtfA_B_wDl6jdGR8NBT7kZbowd8Zfy197vCHVDGYAOIqAt5DrjMRm_u4gBPn3RApfBDAAALQ4CAIIWDJ_IgGAGPL7RzKAd_MAT_EjNDdwaQQA4A0Al_NfKfGfOfWvBoCzaQFrR3NA2fefDAHjZvLA-AqQFrSfafAgmABfIgEgyHTAPwPIXwDAKbALQYH3dgWXA7W7BoLwY7U7BPIgWXHAbAXAQoAAHwkO8CEJELENwDsTJ3cx4N4Lu25ySw4y43-y-0O1p10KjyXwaFo1X2dyT30wgHqxgNoObwgIEDixUDMMO2wKkEIMX30IrwOEJx_1N37zqEO2lwDyDxgLwB9wgC8HYH33MPyAwCgAADUtCYDCc2RT88tKgagkiT9DNUj8h1swBVNPBydBleCwhWB4iAsggMiUjjMbNKisjqjFN5t8ilC7FJRDsAAvHwifEAYAAAa1cKIAMIaElBiBt0SFTy-wCP0zABUD8GCMz0iIaE32CMowT2U2gCcx6IWKPwcO2JWwSIgHoJ8H8AAGVA9JdMDR9uAghEA5AMB6DWMTAMBSAKjpBZBHj7iYBu9DAOBbjriEADAjBbiPivjATHjniJBXiASfjHidDkDYSmCMAeivcfd9dJjDtmt0DHDVCJsmDe8_dqskMUNksqgEBpsZiVDVC1CEsNDSTcMwcABCXAP7VAVAGAAAfhgFwLU1GDDyvxJLJL8GJwSKI003wDwBgEVy0EpM50pLAMpMPz8OlLRNUOmNmMV1wMRK2N4NADYFT0bTlAum8w-OBwSKCGGBuFhN4KOL8FONo3OOVMpNACuPwAwFSE7yqCtH6D3X6DVCgzwEtNuz0NULlKVIDMO1VOCJSHSEyE0ICy1NuyWMVyYNl3jJNICzKC8H7zwCjIyGgH9OlLhILIdNuwjMV3iBjLK1TJlyCKTJ9yrMKwSIzKzPLLzLDMLNDILIaFLPwBUHYw4BUDt1jJ42_xgCiHDyIHrJoJrJ7L7Nwzt0nLKybJD2iAnLbKDMO1aITNN35y8Af2LIaBxOYPxIQ0JNQ35LpIpMpLi2pOS1pJmNGAjNx3wGk07wwAAD5xTRTzz7zCcT9TdDAYApCxSOdpT1z9MwKgzacIMosqAgA)

### Steps to Reproduce

1. 通过cnpm 安装5.4.3版本的echarts
2. 脚本顶部引入echarts ；`import * as echarts from "echarts"; `
3. 初始化图表 `echarts.init(chartDom, null, { renderer: "canvas" })`

#### 关键option
```javascript
{
grid: {
    left: 20,
    right: 20,
    bottom: '15%',
    containLabel: true
  },
  xAxis: {
    type: 'category',
    data: data0.categoryData,
    boundaryGap: false,
    axisLine: { onZero: false },
    splitLine: { show: false },
     axisLabel: {
      showMaxLabel: true,
      showMinLabel: true,
      formatter(value, index) {
        if (index === 0 || index === 45 - 1) {
          return value;
        }
      }
    }
  }
}
```

#### 效果图
<img width="1010" alt="image" src="https://github.com/apache/echarts/assets/17918538/950aa762-5bf9-4428-bf3c-5d25a0c127e2">

2013/6/13没有显示完全

### Current Behavior

一页最多显示45天的k线数据，且只需显示当前可视数据中开始和结束的两个时间标签，当通过 showMaxLabel=true,showMinLabel=true来达到所需要目的时，最后一个标签显示不完全，查看文档，也没有找到相关可以设置最后一个标签偏移量的属性
#### 提示
根据公司UI标注我设置了grid的left，right都为20

### Expected Behavior

能够完整的显示最后一个标签

### Environment

```markdown
System:
    OS: macOS 14.1.2
    CPU: (14) arm64 Apple M3 Max
    Memory: 73.36 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 19.1.1 - /usr/local/bin/prlctl
  IDEs:
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 121.0.6167.160
    Edge: 121.0.2277.112
    Safari: 17.1.2
```

**Comment by helgasoft** [comment]
yep, frustrating bug 🐛 - not to be able to see last date.
Note to developers - does _grid.containLabel_ work only for left-side labels?
Workaround - add an invisible **second yAxis**: ```{ position: 'right', data:[' '], show:false }```

**Comment by soeasyjx** [comment]
> yep, frustrating bug 🐛 - being unable to see last date. Note to developers - does _grid.containLabel_ work only for left-side labels? Workaround - add an invisible **second yAxis**: `{ position: 'right', data:[' '], show:false }`

希望能从根本上解决这个问题
