### ISSUE TITLE
自定义k线图最大值和最小值标记的图形时，平移k线图，当最大值和最小值正好处于y轴边缘时，此时自定义标记图形有可能会覆盖y轴label

### ISSUE THREAD

**Issue by soeasyjx** [apache/echarts#19617]
### Version

5.4.3

### Link to Minimal Reproduction

[demo](https://echarts.apache.org/examples/zh/editor.html?code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WgPT2YAURXAAFjACWUIgFsALhgQBCIwQBh_4HQIInD0KSJocPcvAHN3RKhtBgkVKBVSBQgEVB8AETyVAAoAbRoYGBq8a1IARjV7ABZ7azwAGhhrazVOgDoATgGh6wB2UZnOqaHSUc7FwbVW0gBdPvrG5raO7rV-weHrUYA2SfPrAFZR61uh1rmHpc7W0ZHd_aaWu0uvY7FNWuMrk91q9vvcXq0-CsrjMlq1LnC_g0AUdgeMzq9Hp0UXdHjNiQTVuThmMZmpMQdAcd7Ft8UMxuM1EtrJD2qj0Vclmo1KNSJ16digd1Wq1WWpIeM-KjxqN7vdUe8BedOpdOnxxYdJczeqi-CKXi1ITNFedRatoUNIdz9Yzga17vjwcrxq0wXxvuNoW85mpzbbxuNnTipVcPTdrpzBuCxnw1YmrqTrdZwZDOnS9liDUy3h7xo9SAmsxzRpm3qaiWDxnN7q1I4aER6_dXrA25pqszNCfbSJDy62i3ilm1RmjPmMrkOVvdMw8VtKx8ChrKc59Lm9BZduZ9Hmj191hqztddu4m-GN7oG-Jc_Tur6eep0O8HU69TWpr1nb2nH07h5aw3weVl2mneFwx-YDK2-FMuTnPN_kLDcY0nYU-HhMkJngt5sL7LNFz1fMGRxe4eg9GYVitMEFmnf9Wiub5WkDGZlXTdcqNOBjlVIb8Wkeb83gEoShmrFtyIlDoqMw840RVQU2KpJShLlEUZh4-wZlZWZq2ItQRLU5U1k-FYnRk9CqNBLVLhDT5IQrYZCX_B5HizHSJy1eUjMuRsuW-NRlyJQydJZLlTUfJzqxch4pM-XttOsl0qPaC9e1C_13M2H5iPuFYUwij9BVNc03hFeDhOrKkQwmVCCzS5l3XVM1kOrVFhSXLljwjVLKOZBTpmC-1m0SxS6Kpe4nxStDmuLT5lWfc5H1qz462qvhTVIfr5sGlpWT4ZyXNg8Mlk7F41F2n49qag6ZSWRsgKma7j2q8ZV3_N6fh0zdXvLeZv2unUnp1U7lQRP6-POKsVqGAdripRj4Ou9l7j-0rVu-TohO2lUXNop4hPGdE7oooEqNmI7ISuYiqwsC7hQDAHvjm-7KZ6OyhiraE_2C9zO3rG1Vz-nyLm6vnrDGUhvqzac6rGIUdOu_FNkdYHKoHV6tlWK7yHmMCBs5zY1ZaeY-YNuEnuVNRyWuxdGopjornsGHhgNrMbeJp6xmlC66yd2T7FdrGebmaqZh1dz53memI_XV3WvOImZkjlYOSWK4iuRyFjsTkPWVj3MX39rUVlIKk6eucng9dvSX0PSaJknMtpqRIP0NdjKG1XMFdR-UTuSeZjPunbYaG2ABKWgADM4DAYAoC8cAYGKUooAqfIqgwFQpC3lQp5gABvfYxFgYA8iIVJMAATwPhQam2WgGnPmAADcVFQOBEkf5_9lnvIKon8sBeAUKQKg3gYAAB4YC733pUUYqAwipCgO4SBXgADUmCj6nwaK_K-N8MD30QQgOAEB3A7z3gfGoXhtijHXl4YARAqikAGK0KeNQdgz32A0T-39EijDIRQqhCD8i0Oni_GAABffYGAiBQDgBgMAJ9eEwEvr4IhJD8hBA0dfO-B9yJ8K_j_CAQR-GmP2NI2gsj56L2XqvS-qBgBwFQFfAAsgIKoqhb4oAXlAXB-wQFwMSK42AuAn5SMAVgYBKhQHgIGMglRuBVD5BWBYwRSTUHoKgbApJGDsGBPwd4WeMAqhgNgT4vxYAAmqOKQ0eREAwlCPIZQvAABaPAPD6nqPAMvMAP8pENFkcU4JTS_DgKGTAaJZTgkACtJkwAWZUlQviQD-MgXMwpdT6njJgJg3AmDUkFFGBkiAtCYDtKWdsGoLYpkjPwY05pwjKF7KcFU9ZNTukyLkQopRKinmoCgDYmgIQHHJJ2QAIzcAAa1SBgT5rA5AYCCIQSwSB0Xov6PsZeUBkFBDwfg3wAAPKAqLABQcoAQejADgxoAB1NsXFOQbPMlMBSBWPIlAEAaBl4IAJWoqAGA0ipA4KilQxKvAQAZfgsVEqAAKIAvA1JFTs4pUBb6hFRcABFEBJVqIedI8iyDhVgFYHy4pxyghNEAKemABpM4eBPHJwdQISK-BPGHQGM61WE9hnkXhV4U1Kq17uGkEEAVP8jEwCZSylokbBXpBjWwtRkKQBQE5YEfApAACkUrX59JUIqgAMioSFRBUBhowD_dl-xiUCHFWYoNaqNX4D0Vo3NuQdEdpOa2gxlRI0poXqoYhABxFQvLplfxiJGmVEBC2KqIAS4IYAABaHAQBBFnpOogMjI2MKgHOsAC6T7BtDRO1AMQd1qJncW0t5ag0NAodIdxYqb1lorRGtRD6Q1SHcUWktb6YDhqIJGhoIB34cFnvEVF4bF5X3bQ0PwcTUiKqCJ0JNPTomIbTRwWJAiBiKvYMSopPSSllII0QYlOBsC4EKAAH1o94E1FGqO4FxpcmAHD731PkYo5RH8TFECmcUh5wm9XVoaLfOtErLVqMJcUiATij1AZA2vEoPgBDyJUGakjj6pDvqIJ-y9PS90ADk4B-FLSimA9w9WRrk_ghAIAIA-BXmAVF8b3BQHg12y1eB8D0nk9-jdW6VMzvlYq3wVn7OBdPZu89BmekiZ-Q0ekxzl1cozXUYp0XAPqqPXgRVzn2DeegHEqAAA1ATQRjkrB7cQmhNXRh1e0SoJBKC0HsekoZsIrBKsCOq5UWrhDe3iMa81g-bWwDZPY7jAL-CABeGXC0gGADC_TYmUvkRiIKxIMnsuGbACoPw-XbXeabfly-JrkHQCYTC7zFqu3pIExAFTUQvDjri1OwzPh_AAGU1X4q43m7gQREDIpU8DzApBqvSFkCYDAEOYApsMBwZFoOEAGCMODwzDRkdY_h9DiQsPMeo_h4Zg1hnEMYBheFmp2meluNvfTkjmG8iRY3QvJermykIDiUd4jJHHl_L47z3eEyACEuABmoFQDAAA_DAZ9aDRgIsHVUUXR3TkCaPpg_AfnUVaEF8MnHRmSMPay0bnLPTDvHdRSkdImR-MCO8z087qLEPEpd7s2-Fm0A2qIEQBAAhigkBZcpk38mfcprvXgXnaCAiOHcYUUgqBWistQMnkUFBWjza96MgTZQvAZrwPbjI0A8_4IgFHtAv2vDzaPddRHkffeoAAPKz1njEFlTR2mFRzQMHYTf8E_b8P92-gOrckbx6TkHigyTz70hH_BFOjf4MZwByfPTQCz8IAvskFfimOec-C1F0a8BL-N6vlfluL8wBt_l-IjuMkH9y82vAfhFUv6ry3_3gfg-hCXn0yHwfWrxjzj3cAT3sCT3TzTxT0z2EBzy_1ANr3ryCEb1v2_2j3b07wUV8172zTOEH1vxHzHwn1v1xzYBn0wFRQID30X1X19Vv3XzvU33qW32oLnz3xfwaCPxc3AFPyIGZXPwYNN1XwyUL2L0f3LyXyS2KR9XqSSweQnmsSAA)

### Steps to Reproduce

1. 通过cnpm 安装5.4.3版本的echarts
2. 脚本顶部引入echarts ；`import * as echarts from "echarts"; `
3. 初始化图表 `echarts.init(chartDom, null, { renderer: "canvas" })`

#### 关键option
```javascript
series: [
    {
      name: '日K',
      type: 'candlestick',
      data: data0.values,
      clip: false,
      itemStyle: {
        color: upColor,
        color0: downColor,
        borderColor: upBorderColor,
        borderColor0: downBorderColor
      },
      markPoint: {
        label: {
          formatter: function (param) {
            return param != null ? Math.round(param.value) + '' : '';
          }
        },
        data: [
          {
            name: 'highest value',
            type: 'max',
            symbolKeepAspect: true,
            symbol: 'path://M0 0l1 0l0 0.00001z',
            valueDim: 'highest',
            symbolSize: 30,
            symbolOffset: ['-50%', 0],
            itemStyle: {
              borderColor: '#777777'
            },
            label: {
              color: '#777777',
              position: 'left'
            }
          },
          {
            name: 'lowest value',
            type: 'min',
            symbolKeepAspect: true,
            symbol: 'path://M0 0l1 0l0 0.00001z',
            symbolSize: 30,
            symbolOffset: ['-50%', 0],
            itemStyle: {
              borderColor: '#777777'
            },
            label: {
              color: '#777777',
              position: 'left'
            },
            valueDim: 'lowest'
          }
        ]
      }
    }
  ]
```

#### 效果图
<img width="1004" alt="image" src="https://github.com/apache/echarts/assets/17918538/ed656bac-d1ae-4afc-ac6b-3c56c3ec3b12">

`2013/4/2日为最大值，处于边缘位置，正好覆盖了y轴label`

### Current Behavior

自定义k线图最大值和最小值标记图形时，平移k线图，当k线的最大值和最小值正好处于当前数据视图中的边缘位置时，这时自定义的最大值或最小值标记图形有可能会覆盖在y轴label上，会导致文字重叠在一起，影响阅读

### Expected Behavior

希望能当监测到，如果标记图片覆盖y轴label时，能自动调整其位置，使之不覆盖y轴label

####效果图
<img width="1008" alt="image" src="https://github.com/apache/echarts/assets/17918538/43ca9031-9b25-4b92-990f-0c0d0209b154">

### Environment

```markdown
System:
    OS: macOS 14.1.2
    CPU: (14) arm64 Apple M3 Max
    Memory: 68.73 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 19.1.1 - /usr/local/bin/prlctl
  IDEs:
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 121.0.6167.160
    Edge: 121.0.2277.112
    Safari: 17.1.2
```

**Comment by MatthiasMert** [comment]
You can manually set xAxis [min](https://echarts.apache.org/en/option.html#xAxis.min) and [max](https://echarts.apache.org/en/option.html#xAxis.max) such that your markPoints fit inside.

**Comment by soeasyjx** [comment]
> You can manually set xAxis [min](https://echarts.apache.org/en/option.html#xAxis.min) and [max](https://echarts.apache.org/en/option.html#xAxis.max) such that your markPoints fit inside.

？

**Comment by soeasyjx** [comment]
> ```
>  markPoint: { 
>     data: [{
> 	name: 'highest value', type: 'max', 
> 	symbolOffset: ['50%', 0], 
> 	label: {color: '#777777', position: 'right'}, ...
>     },
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/13038071/305202804-ea093dc6-db66-46d3-af48-b76f8040ab8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTQ1NjgsIm5iZiI6MTcwODA1NDI2OCwicGF0aCI6Ii8xMzAzODA3MS8zMDUyMDI4MDQtZWEwOTNkYzYtZGI2Ni00NmQzLWFmNDgtYjc2ZjgwNDBhYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDAzMzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDQ4YjIxN2MwZGU5MGM0MDVlYjFiNmM5YTVlZjkwZjJkOWI1ZDllYWU1ODkyOTQxODMxMDJjYWViZWI4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uk6ejj1uGdCiYmp699OjwSOuPPpHrahu3OvleBYPfrw) 📌 please close issue if problem solved. NB: debug and "how to" questions are better posted on [stackoverflow](https://stackoverflow.com/search?q=echarts), where there are more volunteers to help.

按照上面的写法标识图形的位置就固定了。为了还原公司UI设计  ，标记图形的默认原始位置需要为：`symbolOffset: ['-50%', 0]`

只有当最大值/最小值刚好处于y轴边缘时才临时调整其位置为 `symbolOffset: ['50%', 0]`，否则标记位置为默认原始位置。。。。。

**Comment by soeasyjx** [comment]
我最终通过监听datazoom 事件，判断最大值，最小值，是否处于边缘来解决此问题，处于边缘则动态调整极值点symbolOffset 值
