### ISSUE TITLE
possibility of having image instead of text in Line Race graph - feature

### ISSUE THREAD

**Issue by chaitanya415** [apache/echarts#19612]
### Version

Latest

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-race

### Steps to Reproduce

https://echarts.apache.org/examples/en/editor.html?c=line-race

### Current Behavior

We can have custom text using formatter at endLabel in Line Race Graph. It would be useful if we can also have provision for having image instead of text. 

### Expected Behavior

Possibility of having image instead of text at endLabel on Line Race graph

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
> Possibility of having image instead of text at endLabel on Line Race graph

It's possible. You could also create different _rich_ image formats for different countries. But I doubt image + text can be displayed both side by side.
```
      endLabel: {
        show: true,
        formatter: '{img|}',  // or '{img|{a}}'
        rich:{
          img: {backgroundColor: {image: 'https://echarts.apache.org/en/images/logo.png'}}
        }
      },
```
![image](https://github.com/apache/echarts/assets/13038071/d2dd3209-8611-483f-bb1a-9a7aa472adf0)

📌 please close issue if problem solved.

**Comment by chaitanya415** [comment]
Awesome. Thank you for the quick reply.
