### ISSUE TITLE
当设置了yAxis.z 值时 yAxis.splitLine 分割线，覆盖在了series.item上，没法单独设置yAxis.splitLine的层级

### ISSUE THREAD

**Issue by soeasyjx** [apache/echarts#19629]
### Version

5.5.0

### Link to Minimal Reproduction

[demo](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-sh&code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WgPT2YAURXAAFjACWUIgFsALhgQBCIwQBh_4HQIInD0KSJocPcvAHN3RKhtBgkVKBVSBQgEVB8AETyVAAoAbRoYGBq8a1IARjV7VvtrABY8ABoYazUWgDprADZB4bHJ6dsAdlG1abUJ61GATh6AXX76xua2jq7rAFYBobVyec3W5fm-PnGpq4tlvj2Dppb2zu67LczsszqsehNRqChtZNsC1FDhuCttYvg0fsd_jDLoiltZrKszs9NnxVmolvDVhM1KNPvs0Uc_l1rti1qRRgsEWo-BseiSrj0lnxNqs-NSFhNUYdfid7GpWizRaMeisrnxgT18VcFvdhqs7jSUXSpRjrJ0WQslj1WtMrZtRqRNcMJnazgsbdZ7q0zpL0X9TX13cDNo6Nc8vTbWktCTaemyuT6GR1TRcI9ahsrqe0baRqSremSlYbvonuvYJtjlRsJnz8z0lTWNUs3emrey1AnpaWFhXrqNnRHnmc82ptuMQ2pqUKOyb7ID060IesbSMlRG6z0Y9Sc9O_Z0571W3d3fczq9el6lXmeteaTuk51NhXZmeuRsj1rqUP3UtSAs76WWgVakemFK5NiWVoazJNkJjTYZwK2XYjV9e8PXNZ5uVWc4tk5Ug7UjVYFgwot6U7U08RZPFENWVo6wXVZ3nFUk2Sef9yJTK4xiXTjgUwq4LzaUlniItjunLGixQ3aFNlzKS8SFGlQMRNltVE6xu1uJtm2Gdox1uDYcywusqTU_cRg2EZKWBM4lOuIlHTWCEF3_E4WQmOszjk-EXTgicWJfZ0-29ZCSw6AMrhXCx5gWYD5hs8ZOQnSEkOLTsOg4vEFjrPhfMmZY4PUtlcrDFLSIxDpxIi6lYLBCCoI9PsCXua8XPsDT-TZa8jPGWzSDrdSCQMkjjT-DozLyjUaOeGr-I82ykomP8QrSzp5Ro4yoNaNkbNuCFo04tlNglZbys6awWTw0Z6OhPhF3mdyaWHJKYVa9psVsDYCOhKktm085qXOR4IQnV7wrxM5gQtaK2VsOLcwK8Ux1ejLJjtOVoueOTzlIGiDNpVLTsg97Fp6-ZY3tR14PGBGIVIYKCdGh93pvOZoVdS95kiynYPy1rALipsvMjZY_vZyb-MFY6GY6JM1v454PW63oaPuF9exyvnzqw5qsIVza63A0lhpQ2Vugyic6yyrCIQWBzWjtd9EWyzY-cqnTBxrGElkWx5PTth2XZOxn1PezY0agtoXkeWzhnrPn93Uz8ESdB5oRXR3E8hemyuDx9OcxpSU-4vFbBpAqkT4JbpfsHozXmGElTPRFV2hdT8rJ6lYX_WutbTg368F-vOqxodC272V3pXftW-BGF5mFwHoVbNRSpGsLZ2xe2IWV6FWhPJTIJgv7Wg2Gzx7z3f1T-7CocvpU_pXttx6297ei2PM8Scj-T8hJukr65-cs8RrC2J7e2Wd564ibhqOOQd14n3epBe0hdSA209n1JUWM8qTGfhle2Ds4KQXuNsaYkZyQoINoHautcFyb0ClSUho41SkImJDGsW9LzP3ah6WE9o8z20nKQoi99GFRlaM_fcRCDSiMakMSM6osaoL4c_C-eJI4nzJsZRR21PZnCKuIuBNdui92ARCLGMCvrAI2KzPEPRgQn3HsMZmVZHSQQ8nJSCGwcpkxcY4sGkFyTJyQZZORfA6IFTyg4wxPcUa6XtowtGhD9TMNbsZds0SxLvRzIpIRSxHaRknE3LakJ8Y53St0TeCwVLsKyldVxPNaJCLtKw_8ZwJ5NPtMnOmkIOl03rl4gx1c2luw9KfTmnpj5jLTrTKuZT7BtO4ZlGkf9rLHztF1JeMMpZzLaQnGBI4ybA05uqSmENqatPsKo3oEIjqczfNfe4XIyaSwuS_euxFDmPXrrxcu3tZlr3mZ0NQzNvae0PJTOUywm56JpNnAFbTaKTyJJA-0BVumV05g7dJQzOixJ_IXN-YDPye2wvbV5IyGorzivcbxu8VKiy8f8k2CLFkgTLo8RlZNMYFSeMgi5_MbrAw_mHLYhccpbAYmjKhOzuhAK9ldXy3S963CKg5bp2KZUUQYmKXCPJ9Ic1mldUp8LujAtuJOBGwIfbQlqYqg2cLmXdDBrYZqydeVfhtTDZOwZITSpNSHIGfYm4yXtJ7RUJC3j3CZSWNpthQ6xU4o8ym4qBRYU-vy1RIxPxeTfg6bWV1tIW2WBqk1zIaLb05MLDkNFOox0hsbGNsogEjBUl5cgvrbho0LdhIc_4JjtLeDDAqIrF54lHMq_iwES0m37c6hCCMeTc0tsGiCfb5nvSqeyBGh0P4TBYn9RGt010jIesqHxCqyZsl_PdRcfqZ1tWcVHOlEroTdOvWzGC06Sz9reowoqpDeQglIdg1xmwio7BoDsAAlLQAAZnAMAwAoBeHADAYopQoAVHyFUDAKgpBYZUFBmAABvA4YhYDADyEQVImAACeBGFA1B2LQBo5GYAADcVCoDgIkRjzGDiwfkFUTjWAvAKFIFQbwMAAA8MBcP4cqKMVAYRUhQHcJJrwABqTTRHSMNFY1RmjGB6OKYQHACA7gcN4YIzULwOxRjoa8MAIgVQcYwFaFBmopBoMsf05x7jiRRhmYs1ZhT-RbM-YOAAXwOBgIgUA4AYDACRg4BnfBGZM_kIIlH0t0YI0aBo_meMQCCEVxI0XaAxfg4h5DqHKOoGAHAVAVGACyAgqiqFoygBDUBdMHBE3JxITXYC4CY75wTWBhMqFE-JwYynku4FUPkNkZWIBKZU2pjTMmYDzY09pvr-nvCwZgFUMTsnOvdbAL1lLh2GhxYgMNoL5nLN4AALR4Bg6l_T9BkNgB475hoMXDsDYe34cTAOYATZOwNgAVuDmAcPzsqC6yAHrkmYf7Zu7d0HMBNO4E00tgooxVu2ZgK9hHOwajiIh0D_T93HvBcszjpwF3UdXc-4D2L8XEvJfp6gKAlWaAhFqwtrHAAjNwABrVIGA2esDkBgIIhBYMq9VwMA4MuvCsCCHp_TynYNQCV6QAApOrw7GA0juEN_gE3Zv9Ni5AFAKAIBAg29NwVmAP2VBeDAAAGRUGLogqAghQAwDx6LRoAAeAhI9eBK1jhoUBaOhCVzl6jdG7cNEJ0EQnbI08Zfy19h3CHVDGYAOIqAQEEWDXGYj7C-45qAvufdEB12h9w0hq-16IDAKLHuVCx4gAAFSc5LnXX2GgWc75D7vX3ad94OLRmPcfx-HYgPV1vMBQ88Y943gQcWVCr-xx3qQXfUAxDn7vkoPhm9gE37rtfJ-Q9h6IB7hopQ78AGUk_KaP7dz3Jgiu-AtGQe8Qmet2SeKejQfIxqh2tOgOV-GGAAcnAH4IHkAaCF9gPnHv7oHsHgnvpj7hAFrpvtvq_hPjAH4NNqkD7kEDjBQexhwMhvVgIKUKkGAErg7k7i7ngJfkXnLtNrRhXlXjPufuQV9gAF5BBqAR4HCE4ABaIALuQQdQh2D--mkBm-eARBJB4Bk--QGA1ueib-MAYQ2u7m5Ac-BwkoMQFuiQKhX26hDQYAKgfgWhgAp6YADSehW-yeWhlGYArAym0Ao-Ph2euQy2xOXGxWJhPg_g3-tGv-BBh2oA3AQQiACuJhrGgBpAOe0gsggBWRMADuhgHACu6RCABgRgmRFBDQJR1ROReR-gbAZRgBFBC-_-VBGAkuAACiAD7tbk4XrgHkHn_v_pDpgFQU7hwNXghkhihsllUAgNNq4QduMebtzkljAMsbhmDgAIS4B_aoCoAwAAD8MALWeQ7gowsuJeSxKxfgURAWRGmm-AeAMASuWg6xnO6xHR4x4Rqh3xQx_-LhbhSulx3RPh_-oAbAKhjacoF03mRRwO0Rm-wwNwtRt2cRfgCRSRwJ4xqRmASuGAqQYuVQVo_Qe6_QaoUGvB3x-m8B4xfx6x-Jh2oJWhKQ6QmQHGqJUJEBfhSuVBkefJKJAWZQXgrueAnJGQ0AdJ3xzJ4xrJ-m7JSu8Q3JZWIpGhAp-AfgPumphWqJ4pkpapspmJPx4xEG_-jJtOEGUWVAQAA)

### Steps to Reproduce

1. 通过cnpm 安装5.5.0版本的echarts
2. 脚本顶部引入echarts ；import * as echarts from "echarts"; 
3. 初始化图表 echarts.init(chartDom, null, { renderer: "canvas" })

#### 关键配置
```
 {
 grid: {
    left: '0%',
    right: '0%',
    bottom: '0%',
    containLabel: true
  },
yAxis: {
    scale: true,
    splitArea: {
      show: false
    },
    splitLine: {
      show: true,
      lineStyle: {
        color: 'yellow',
        type: [8, 8],
      }
    },
    splitNumber: 5,
    axisLabel: {
      inside: true,
      margin: 0,
      verticalAlign: 'bottom'
    },
    boundaryGap: false,

    z: 3
  },
}
```

#### 场景重现
当通过`grid.containLabel: true` 将坐轴包含在gird中，同时设置`yAxis.axisLabel.inside=true`将y轴刻度标签朝向，添加选项`yAxis.z=3` 使y轴层级高于series(需求所致)，显示y轴分割线(splitLine)，这时分割线会覆盖在series.item上，目前没有办法单独去设置splitLine的层级

#### 效果
<img width="1007" alt="image" src="https://github.com/apache/echarts/assets/17918538/8f195904-c8ce-4029-b7f9-1bd890c867a8">

### Expected Behavior

`需求是需要y轴层级高于series，所以设置了y轴的z值`，但此时y轴分割线覆盖在了series上，有办法单独让分割线处于series下面么

希望能提供单独设置splitLine层级的属性

### Environment

```markdown
System:
    OS: macOS 14.1.2
    CPU: (14) arm64 Apple M3 Max
    Memory: 153.39 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Parallels: 19.1.1 - /usr/local/bin/prlctl
  IDEs:
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 121.0.6167.184
    Edge: 121.0.2277.128
    Safari: 17.1.2
```

**Comment by helgasoft** [comment]
One could squeeze a chart a little, but mixing axis labels with candlesticks looks cluttered. 
Could be better - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh&code=MYewdgzgLgBArgBwMIgDYgE4wLwwOQDEApsAAzml4DcAUKJLIgEKYAmRGK6WuhAHAEEKlWvWgxWIAO5gumHPgLlWAQwDMwanXDjJMlhnac083ktJ8AYgCY-WgPT2YAURXAAFjACWUIgFsALhgQBCIwQBh_4HQIInD0KSJocPcvAHN3RKhtBgkVKBVSBQgEVB8AETyVAAoAbRoYGBq8a1IARjV7VvtbPAAaGGtrAE4AVgA6NRH-6zUAFgA2MamB4fHJ6bnFoesAXV76xua2jq7hvoG5gHYxwY2RvjGhvg21a_WL-bUxvj2Dppb2p17GpKBt5qQxpdljM-NYxrNnhdZtc-EMNnwvpd5r8Gv9jkC1K1zjCvrM1OjxrNrBtLq0buSLkM6bCcYcAR1rJ1ia9rrNWtM-UMxqRqR8hSNLgLrHTWiNWXjAZzZsSqeNtlKHrKBa1rvcBbMIWofvtcUdFfYRirWvyBmSvu0BaQvgzrGTebsTWz8Zz5iq1HD5ojXXN4UGqddJba-ZC1PKzRz7Jc_RD5mjba0HiMXWohrMbqLg19UXH2d17HZtYt5gWyXDZtq8_Wo18nSXvZ0K1G6UypXSRvNtZSXbMR982-bWkMVS0bgOLrDHjaZpcvlmpddSJdxwmWtyMfC0zMhtcMzSU0uc9dc6yYDsAJS0ABmcDAwCgXnAMGKpSgFXyVQwFQpD_FQ7xgABvA4xFgYA8iIVJMAATxAhQah2WgGmgmAADcVFQOBElQ9CDkfeQqlwrAvAUUgqG8GAAB4YEA4DKjGVAwlSKB3ForwAGpeLAyCGkwuCEIwZDWIQOAIHcACgJAmovB2MZvy8YAiCqUh-laO8alIe8MOE3D8MSMYpJkuSWPyRSDIOABfA4MCIKA4AwMAIIOETfDEiT8iCWDvKQkDPQaYyCIgIIwsSezaAckJ30_XAhJgd8oHYoJkoaXwAA8oCCPBVKgAAZLwwCIPpPJgdjHzymBSHsz0oBANB3wQDLKqgDA0lSDh8pUbKvAgCrhJgfrBoABRAUrfAwdqRqyxDQny4AMBACAhsqhyGjsz12J6sBWAy7bPVSLrDo8kbqtqvBSAAUmG4SuvSa67oehoACMQCgJrAnwV6Qpgeh8lKoqVHeohUCCTqCIag5EIEAaIou4SIFg9KUowAiAcKgQnJUOb5pk6QocxogAYaFQ8YAZSgRD0vA0BuACJoEFKgBrPo8CkFJfDwHYtuEnbKsKkqyoJkaiakEmscqhpSjKmm6aIcX5sZzB8qkjASnK8nhNppbGkRH5ZZgAXjuFkofAAOTgPxwdmmApkqsaIFB8HIeRkbHFKiAvHYaWyZNvxKdSUqgi0k3sI4d80YEUpUjAfLPu-kA_DwTaAc-l9VHEgBxFQ2pgR88JiAHHAALyCNRYYabKEcGlX9eV_AAvgpC3tyPzO4KMZW584LKqzg7KcQ_PC-hwORpd0Xm_A4IwAALQ4EAgmL1AYlN7HLeK0rZ6_dxiaLkuiE3yq_DD_BVHyABZUqO-D7L8qvlRr_69PzYaGIusSII6hGzLhJgBUH4ZueBYIHVQB3BaBswEqAgZkNSHNdbPyCM_CEUUIC6x8P4RW6MAEjTVg7RAcgMC60wiYDApBUHSFkBQshMBPqGA4CQoIzA2DMLoSbD67DjDcCoRIGhBgjAkJNkLEaYjbw0DslQIAA)
![image](https://github.com/apache/echarts/assets/13038071/a738f5e0-8faa-45fa-aca2-e80e2358f1b7)

**Comment by soeasyjx** [comment]
还有其他的解决方案么，我们需要把y轴覆盖在k线图上

**Comment by helgasoft** [comment]
try with **two overlapping Y-axes** - one for splitlines without labels, the second with labels. Different z values.

**Comment by soeasyjx** [comment]
> try with **two overlapping Y-axes** - one for splitlines without labels, the second with labels. Different z values.

在k线图中需要，监听datazoom事件来，计算min，max值，以此达到两个y轴重叠

**Comment by guava3s** [comment]
> try with **two overlapping Y-axes** - one for splitlines without labels, the second with labels. Different z values.尝试使用**两个重叠的 Y 轴**- 一个用于没有标签的分割线，第二个用于带有标签的分割线。不同的 z 值。

Exquisite attention
