### ISSUE TITLE
当使用散点图加路径图时，存在部分数据结构下路径未渲染问题

### ISSUE THREAD

**Issue by YanaDH** [apache/echarts#19631]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULTsBEAPAgrhAM7YBcy6W1OxAFsAO7mwBmAhgDbECmANFRqZsYAJ4geLbADcuAV0mDMAXwEYs2UYRItU6odnpMWHbvyU0R4yRRnzF-2KosjgwTpBC7njwzwBOEDykFADaFtR6QgZiElLEAMbsYGAB2GrRlgBenDzSPJwsAIwZmRoAJsnsLOGOZVhR9WWGogC2AEbuAMoQWTawACwADKVN0XacCjURY9EjM7M0QwuzALormT6LmI3bGsRtnZw9fSzDo3s4spP9tZfRALQATEPzdfewy--L699lW9tdpcWh1ur1-ucNk0JlMwlDFi83h8lvCyr89gDFkC9iCjicIUiPjDbqixg8iq8Lsivsj0dtMbNsdtcWDThRIX8xsTppztg8AMyU0lNGkfOmLBljJmLFnHcFnQn3blw3mLB7DRXIz7CoTi2aSprS2ay_EKqnM66w2B3LWYclC1Wze2i-56sYG-pGrkHUFytmDTU4y0kx1kwWBj7OnU0N1ND1lL3Qn14-XsiMy4M8212jXm-5R0PRWP1eOZRP1E2pgN542ZlXZ2DOmt7Ckuy7F_7N6Ll5rJ1kErsVuvW6OZAUOhut0dYDubQc0HuZSv-jnI5Ujwv1dUT7NTzcx6Ol7vT4R9v0Dk9XexZ3c721tvaz6JHoSL8Zn01p-dL4c223h78RUvJ8hBfBdL2XC992odc_y1XNL2oB9thAmhlFRVZ52wCBUlaLoxFyXRo2wBJ3GAfwpAAYleIZ0mI0B2ASHDRGKVF0L-eMeysOJbE4CBoGCOjHRItx_HKfjkh4LpRGIXCpCSfxUmICB2GgJ5yiErkcjyAoWHTSweFYVgeASMAiP3QwGGYCgwH8BRAOEWz2AgTgABkeGgABzMA6D0hzaEOdwpHYfx_GMfzIJYAA2NisL4gT8NEQiKDfYQEjkfx8gE4gQk-AA6IYAFZYtRbBKjAap60BCDSPI8pcrg5FGuzJtELmNrMEwjqNwbJD_LGZDXWA_qNHiqSCP6VLmlIzhyKkfweA0y92Ixfyppg2qxIa7rmttVroKAg7dRGoRdq1Z4716wb22GiCxsS5LKCOywZrm2wFqW56VvpNaatE-qb1tM7qROsprsfUHqGByNW0h9rnuoVDMi657sHuibzIbETZoo2xPIWjzsGWw9ftRzaAaqoHuuoC79OpbqUYbaH81h6msHBlDbtR9Gksm7rsbenB8Z4Qnif3MDIj-urtoRrBmcucc6Y-DmfjhzB5b2Wm1ZRWXOq5tcece9bxle3GcA-omvpJ6NjbS_6ZaZtm7URbWkIZ7WNb5ACne1XXYCRotQbR_jxt5zHswFs3sGF0WrfF0m13Jh3s09tUEL9t2_cZlOfcV132YZ_WiUNvm_cj-bFst5FvolBOiSTwGtVTp1vYzgus493P0969uGwD467pDh7S6x02pBj6Aq4-Gv9TrpUG8ppvc9Ztu7T3PvO9Xz588wFW1iLpUS_D21y_eyuxdWm2pa2xumuXy6GwLDedtzl2fb3sZ-5jIOj5S_mx7Pp9au1t9y2xwAvHqOct5K3uB_Jo2cqZb32j3NerxC7PQQcCX-T1R5kSjhPKe9wZ7ujnsCCBzdMgUKaFrd-7sX5IJXigxs69sxf0Rj_IeGM_5lwAULAmk8L4_SvmTe2t8PhUK3K3JhT9WGb2kW_aB6DaQcISlwnBEdeHYAtoI2uwjE6iMXnfJBCimFwPqJgox0ipEoJkbaNhM4VGhyNv_PB49-GEMuMQuMpCcTkPodI7uNiWF2LkTY6xPdbFansZ1Rxw9j5alPubc-cdL6gOvhTSBiCrEPxasEqJoSImBIiXk2kB8sGcLDtw3BOM3EiwESkoRaSRHSzEfcCRZRkEoJKWKApV0d6-z7mUnE2CwEbVcYAjxGIQF7DASJFphjxH3xgZcbprpemPxMSgsxaIhnMhGS4mpEydGzz0fXAxmSl7QP6ds5G6zck5NtKsm6GDYlqNGRoTRBDjkkNOfPc57SoavweVqG5gd_FBOBciJ5j5dkyn2Tw8ZfC6mTPpNM6qzSb4LLabncJvVoUoTuXtTZPdQW6lhcaeF1TBZaOScA-OvyyH_PBRE4lV06F-wBY8XFk40FZ3JVySlGjEXR3cd87xDLfFMo5V3SFHx8Wq2Zb1POPt5X7xeYPVRlT1En00dohpuimn6PmRcyxYTZX3FVZ_Ql50il4t5YM9V3MKnOIRYcpFsc6WpJmek5OWSunmsuKS7-iqGzLL2EGxG_LoSCp1cKvVnrGneoxRkzl6sVUBvDeyx2W9WWhqUT0jVTiR5CrdTSoB080VYh9a0y4qaljXKzVAphjCtn5rWYWuJVSS3Uq-fqk5hqznGrrXW6gubswRocSG28YbtgTr1o6g2zri2xtLb2hNBqk1GsxSaxZW9uXjsbX6nuY77xtvbK8rV7y7alvjRW-lA6_lDqnbaE9ILD2XKYfu09fKF3FyXfE_Rq7RV9p-Q-xlT7pVb1tXmjuz6tRfrfT-5RHa3kHOpbeohlbGTVqxbWn2CH6awcg0w6DB6kMFqdZql1VL8HAfXfqDCKwZ6_GUAAbiAA

### Steps to Reproduce

直接可见

### Current Behavior

左上角和左下角路径未渲染，箭头未显示完全

### Expected Behavior

所有路径正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
好像是默认开启的 [`clip`](https://echarts.apache.org/option.html#series-lines.clip) 策略裁切了，可以先显式设置为 `false`。
