### ISSUE TITLE
[Bug] 在饼图中修改单个扇区距离圆心的距离应该使用哪个属性？

### ISSUE THREAD

**Issue by 001221211** [apache/echarts#19635]
### Version

e.g.5.2.2

### Link to Minimal Reproduction

无

### Steps to Reproduce

无

### Current Behavior

修改前：
![image](https://github.com/apache/echarts/assets/116131743/f3596173-2342-4210-89ae-3e9e6b5bb1d6)
修改后：
![image](https://github.com/apache/echarts/assets/116131743/d9dc1ef2-0a22-491a-94e0-f2685b7c75a2)

### Expected Behavior

修改哪个属性？谢谢

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
```selectedMode:'single', selectedOffset:55,``` ?

![image](https://github.com/apache/echarts/assets/13038071/3064af20-2b0a-46a2-9761-1be95ba6c504)

**Comment by 001221211** [comment]
谢谢你的回复，但是为什么我这样没有效果？
![Uploading image.png…]()
