### ISSUE TITLE
Some issues about boxplots

### ISSUE THREAD

**Issue by DimeSnow** [apache/echarts#19646]
### What problem does this feature solve?

I hope that my multiple series of box plots will present different numbers of box plots as the horizontal axis expands.
My coordinates are time, there may be 3 boxes on time 1, but only 2 on time 2.
The information I can access is that the number of boxes is fixed. Do I have any methods to meet my needs?

### What does the proposed API look like?

I hope to have higher scalability

**Comment by Ovilia** [comment]
Not sure what you want. Can you provide an image of expected result?

**Comment by DimeSnow** [comment]
![fac734a9f9f0acab627692a2a3eafb8](https://github.com/apache/echarts/assets/76728380/3d712fd0-2193-4eb7-bed6-a5606aa41a0c)
Like this.I need to dynamically determine the number of boxes to be presented during a certain time period based on data.

**Comment by helgasoft** [comment]
see [official example](https://echarts.apache.org/examples/en/editor.html?c=boxplot-multi)

**Comment by DimeSnow** [comment]
I have carefully read this example. But in this example, the fixed number of boxes is 3, which does not match my expectations

**Comment by helgasoft** [comment]
Maybe #19250 could help. Solution is for bars, but could be eventually adapted to boxplots.

**Comment by DimeSnow** [comment]
Thank you very much for answering my questions.
