### ISSUE TITLE
[Bug] timeline how to set Radio type？

### ISSUE THREAD

**Issue by zhoufanglu** [apache/echarts#19656]
### Version

5.4.3

### Steps to Reproduce
* timeline config 
```js
          timeline: {
            data: this.recentYears,
            axisType: 'category',
            bottom: 170,
            left: 10,
            playInterval: 1000,
            width: '380rpx', //宽度
            // height: 50, //高度
            show: this.mapType === '税惠',
            autoPlay: false,
            lineStyle: {
              color: '#a3a4a9',
            },
            label: {
              color: '#a3a4a9',
            },
            controlStyle: {
              color: '#5386ed',
              emphasis: {
                color: '#5386ed', // 设置选中时的颜色
              },
            },
          },
```

### Current Behavior
![image](https://github.com/apache/echarts/assets/24451091/4b9c5f0b-7955-4150-95c2-9ef6bfb19a79)

### Expected Behavior
When I select 2024, the first three dots don't need to be highlighted

Excuse me, how should I configure it? No online demo will work

**Comment by MatthiasMert** [comment]
`timeline` has the property [progress](https://echarts.apache.org/en/option.html#timeline.progress) which allows for configuration of the progressed items.

To lower the opacity you can use:

```javascript
progress: {
    itemStyle: {opacity: 0.1},
    lineStyle: {opacity: 0.1}
}
```

**Comment by zhoufanglu** [comment]
> `timeline` has the property [progress](https://echarts.apache.org/en/option.html#timeline.progress) which allows for configuration of the progressed items.
> 
> To lower the opacity you can use:
> 
> ```js
> progress: {
>     itemStyle: {opacity: 0.1},
>     lineStyle: {opacity: 0.1}
> }
> ```

Thank you for your answer and adopting your plan， i slove this
