### ISSUE TITLE
[Feature] bind graphic to grid

### ISSUE THREAD

**Issue by SanLeen** [apache/echarts#19669]
### What problem does this feature solve?

some way to limit graphic's render scope to grid

<img width="769" alt="demo" src="https://github.com/apache/echarts/assets/22147095/f2ea81de-bbb1-4acd-b36e-3a1f3bd722a9">

#### expectations

https://github.com/apache/echarts/assets/22147095/2588e018-e940-4a99-a1bc-7d4a4e7a1eca

### demo code
```javascript
option = {
  graphic: [
    {
      type: 'circle',
      x: 100,
      y: 350,
      shape: {
        r: 100,
      },
      style: { fill: '#0000aa' },
    }
  ],
  grid: [
    {
      bottom:300,
    },
    {
      height: 220,
      bottom: 30,
    }
  ],
  xAxis: [
    {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    {
      gridIndex: 1,
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
  ],
  yAxis: [
    {
      type: 'value',
    },
    {
      gridIndex: 1,
      type: 'value',
    }
  ],
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    },
    {
      xAxisIndex: 1,
      yAxisIndex: 1,
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};
```

### What does the proposed API look like?

```javascript
setOption({
  ...,
  graphic: [
    {
      type: 'circle',
      x: 100,
      y: 350,
      gridIndex: 0,  // 👈 sincerely hope to add this api 
      shape: {
        r: 100,
      },
      style: { fill: '#0000aa' },
    }
  ],
});
```

**Comment by SanLeen** [comment]
@helgasoft 🙏Thanks for your reply, but you may not understand my idea correctly, I have added the expectations video to my post, please check it out

**Comment by helgasoft** [comment]
I see the circle attached to the line and moving with it, maybe you need [markPoint](https://echarts.apache.org/en/option.html#series-line.markPoint) - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=DYewQiAukgtgBAXngcgBwFIUG4BQALASwmjiVQFZMdcQAHSQkAO3IG9d54BzAJwEM6RAMYAueAG0uAegBUnLvA6LFkAJ50ApuJTDCvYcE0oANApUAjKDFjiiJGyfhGAZpB0AmAMxYzKrgDO-ILaSvC84mgADPAAvn7-AepG4mzwLoTAwDrAhNz4kBbAAK7GceZxJrLSFcr-6lo6vJrCkKYVXFakts7g1nBOru6o3r4d8EEhqfAA7oQAJpD44gCMUVFO-Jp5BaJeXpXjSWopYRlZOnyamswo5SqxCgC6CXwL4hK14102dsT9sAq8S-_ngWx2wxQABYfO1QT84OJQA44EDngkAB4AQQxhACHxB9Q0oV0_Egmm4IF4ajh_nmZP4HxQAFkWKZUAAVUrslAAdU08x5HPwxR5ADFeIQeQBlMky4q3J5AhJcOoqN7zACSzHmmgxqxVqmJOmEZIpVJphq49MgjMkLLZThQXOMTv5gqdwtFTolUqdsra_oVKCVD3RCjUOLxBJUaqNjVQADd-CVjMrCerJVqdXqDeMGiTk6mUGiuC8FAFNJLNPjJBnFDa7RIVhQNvBvG2PB4oU4PCs0E4Vl4KIOoQB2XsANii5dBBZyhGYrvg41g_F4AGsAAogRfuOMqAJqWBWbK6fSGV1Hk8gYDSwgAL20KxfTnGXEI5Ng0uS2jYwlvKlRBQZoPXgeh-D0dRRCiAA6ChgVBa0GVECQ2GxXF8RQX12UjTDRBfFZYlDfxHgeQ0D3gDC8W1XV9XgFYrXgPCaJzejGPGRsPhbTsvE7bte37Qdh1HCd22nWciQTFBciXEswzLBJGwALRARE2HnFBFwCBZlySdd3FbJwbnmUQxzbc5yV4VldWA5gWGMYFcFibAgA).

**Comment by SanLeen** [comment]
@helgasoft 🤔But mark-point cannot be listened to for mouse events

**Comment by helgasoft** [comment]
> But mark-point cannot be listened to for mouse events

??!  of course _markPoint_ can generate mousemove events. Just seeing the emphasis effect is proof that _markPoint_ is mouse sensitive.

**Comment by SanLeen** [comment]
@helgasoft 🤔However, Echarts does not expose the API

**Comment by SanLeen** [comment]
Finally, I found a solution. Use `registerShape` api to register a `custom shape` and `setClipPath` in `beforeUpdate` hook.

- [demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts&code=MYGwhgzhAEDiBOBLAJgYUfUBTaWAeALlgHbIxbAAWY8BEAdAObxgAOliw96mIOA3gCho0AEZYAZgHt4WAKqtkYIgAoCHCAC5oYYgE8AlNoBuUlNCEiRiCdDUb6EaqyxMkyAJLJoAMh92AQnVEBkYsAlQQRFYABWVKFQNoAB9k6GCGJzZXWQAlLAgpEGMsBBQDJMsrEWApYggCXCoaOg96gl1gHABeJupaUPC2hs6sACE9ABEpAFt7EPoAfUWAL3h6ZFmDAG5hauha9ugIPRhein7W9tGAbQByRbZEO4BdJnDUKRlkRGJlLAAyqciDMIIldvsDnUGukaGECGVvL0TgwJL9kCozgA-Y70GZSZBYEAAfno5m6FPSDiyLjcKC8Oz21RsgQ68HhiMqTP2h0KfHoWHg8BkKgABjdETxsC8xJIZPJFP9tGz4dBmOYACT8DKOZyudWeZAAX2gxCkjWkAFdSNBpPBoFqdSgjaLGZCRLICJb4MQIfsjdyatDGqBonF1NBesQsAB3PotUIsdicej5YAEFT8Y565Vw8KI94ENMEAKJaBGt37AD0VegAPCB2FrFYv0YYik1qUSAK6Sk0FYshKxEazDYHGAMAkwpmuDwXSwP2IbfUOAN0BYS6wgapCwgHyisXiKlDh_UleqOppOSw-T5JURkdtYBAe79IgD78EAYuCbcY5TsiMCERDwACeoqHcBpSnwdwADRwO40FYIyghSKwBCIHUj5VKOybANoNzclUzLINokFJuOACMcHbgQeguGRUEYNgNGQle2jEfsBpeGRRANAAsmAvyIqx7rAHg2iUQADFJ8HAHo2gAEwyfB8CSSp25GrB24NHofAcbaiAgCAZEAMQAGIAGyoOZACstl3OW2nVFpRHbigjEUZwimiRe9FYJ5KBIb5VjsRY24iNxpHQHcfEEAClqiCJzliRJ0DSbJBwKdAAAsKnrupsmaSl1S6fpFiGcZZkAIKoIpimUQA7I5rkuSlLwpQaBFuZCHkxXFgnCe4IUiKI5oELM2gAMwaW1PX7H1sUFPFiXJdulBYIgjCUAQSnKSVVhjQQE0zNNRUuXsHV7Hg1V4CE3XVJxIh0QxMXAP8jAyHoI3QEoHQEXc_F1HBMUACqWlgIN3AA6guUOg5QlpQ-ZSBQwCyho9arzcq1VhPWq7htISaWUQdz3-WR71EJ98DfWTv3KGAANA8Q8MQ1DsPIPDiPI6j8F3OjBCY6zLw4-1KV6Ld93QIRj3pBTMXGM-7PwbjIhZtxpD4JJ8EvQFivK5DquXSle7dloMvzdUf1MzLlG2ZlikzfB9U5S7lEABzwZRU22d7OWNS7llSVdkJ62RUTRncYtW1YN13RARPa-l9OSwnSck_TNsEfbjvO9Arvu176W-_7gcF8Hof7OHMWR0bOOXV-uyCBI1rpphxDQJaipEJEYZHlyIgzHoqCXI44QAPLoR3mbcrh44PfsWaLfPnDUfBYVZnkBRFPe7jKvAEPlk527L9F5H_sAPkbzmFXb3epT7-kh84CaavQFXFa7AGggxuiUgxnoGAZAyAACiQ4CAABlgIkEFBBWQEBEArCNl3HuWA-6nkoIyYeo8Wj0DqBBG2AAtL4MwQbdz-ugg84YsHbCAA)

- source
```typescript
class GridCircle extends echarts.graphic.Circle {
  beforeUpdate(this: any): void {
    if (this.shape.gridId && (!this.getClipPath() || this.shape.reResolveGrid)) {
      const echartsInstance = echarts.getInstanceByDom(this.__zr.dom);
      const sys = echartsInstance['_api'].getCoordinateSystems();
      const targetGrid = sys.find(s => s.model?.id === this.shape.gridId);
      if (!targetGrid) {
        console.error(`[GridCircle] beforeUpdate: target grid ${this.shape.gridId} not found for ${this.id}`);
        return;
      }
      const clipPath = new echarts.graphic.Rect({ shape: targetGrid.getRect!() });
      // Set cropping boundaries to prevent graphics from exceeding the grid range
      this.setClipPath(clipPath);
      this.shape.reResolveGrid = false;
    }
  }
}
echarts.graphic.registerShape('gridCircle', GridCircle);

option = {
  graphic: [
    {
      id: 'graphic1',
      type: 'gridCircle',
      shape: {
        gridId: 'testMainGrid',
        cx: 100, cy: 200, r: 100,
      },
      style: { fill: '#F6CF55' },
    },
    {
      id: 'graphic2',
      type: 'gridCircle',
      shape: {
        gridId: 'testSubGrid',
        cx: 100, cy: 400, r: 100,
      },
      style: { fill: '#AC2217' },
    },
  ],
  grid: [
    {
      id: 'testMainGrid',
      bottom: 300,
    },
    {
      id: 'testSubGrid',
      height: 220,
      bottom: 30,
    }
  ],
  xAxis: [
    {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    {
      gridIndex: 1,
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
  ],
  yAxis: [
    { type: 'value', },
    { gridIndex: 1, type: 'value', }
  ],
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    },
    {
      xAxisIndex: 1,
      yAxisIndex: 1,
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
    }
  ]
};

function updateClipPath() {
  myChart.setOption({
    graphic: [
      { id: 'graphic1', shape: { reResolveGrid: true } },
      { id: 'graphic2', shape: { reResolveGrid: true } },
    ],
  });
}

window.addEventListener('resize', updateClipPath);
myChart.on('dataZoom', updateClipPath);
```

**Comment by SanLeen** [comment]
Thank you very much for your enthusiastic reply. 🙏 @helgasoft
