### ISSUE TITLE
[Bug] series-map, 使用dataset，当dimensions中数值字段超过1个时，visualMap.type为piecewise时，地图颜色会取最小值颜色

### ISSUE THREAD

**Issue by whitexie** [apache/echarts#19664]
### Version

5.5.5

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKgkLCIEPi4jNh4RGRUQaKM9tDwSAgwjMT4SHCMMACyUAAOpFJ6Ahai7l4-loHBwQIANioA1lAAXAFJTaItjFZwPQC0AIwAzOPmfU1wqCU9AEwArLP9wehRcBA946tzAL4bTcJQ6FD4-D2Nm4PDY-PjAAyn_QtLossAHO9N21wux6h36JzmUj4NgKC1ErHw9lQUluc2CDxGolGAHYAGz_YKfFZ41GiQHA77HJJHRLBRZOFwAXl6_QAbrkbFAWsUvncPiASowelISvgUoxtmoLCT0UKYPhiBA4FLNiEiD03iTgFAAB49SYATheRuN-NE9k59hsbQARoMenAYNDTSgMJgoNbGC17Y7GKb8tqMQBtKTCeUQapSbDoKQAXWO_wWqBaTh54P68kUaiDJN5myissYSCtStNwQIwEYhCQzirPWDhCgFYjLM50NjpdEJhsMHsgtEgZJ_X8ogbFaFrXdjag1RbLWhPQALD9lssXstJpZZ9Dlovl8tRGmVU1h6O-1IJ0hOjPW32sdMFwv9ZubzvRHfxgeO8ET42zwI5QAXqY07PnOfY4qsqyTGs6yiFujCvhBUGfoOx4jr-44wJ0VYqNeYErPqj5TDMcEvgRj4oUeaGnkKYCcvgVioDAhD4CBpH4aIkw_C8C7jAukxvOx256txvGUVRAToWO0hgEmTF4EioHzqIqzjD8WKrMuSkISCalYuJVE_tJUiyYQhApE4lolkJfaTKshqTAuWLaa-dmGgZR5GWeAAinoXLAjB4cp-rjFiLz6ssLk9CF-mHoZUk-bkDoInAoioFYoiyXOwDWqxQXgdBhVRaIOLQR5KpeUKABiLRMVEbHwfs-rTBpOJ_DZr7jM1oXlZslXSAA4owTE5A1N7RSF-qEbB8GvlNXW9UOCVCuclzXPl-wGuuUzFVMEWLdRGHSAAkvIaAbaIBz6qsWK_Lt9mrAd37LSdLQtEQqC5Bd4y_BpMG7b9j1xZ5L1SMdhAEFADYXRBkx3o5xWw7FX6STRJ0YGNHECVivE_HiHV6i8ONPajR1SAA0lDHhIBdvw_PZLwzWR3w_PTJP9RTlZwDY9jtCAF38aJBzFYLLzs6D2A2LkrHQ9pi44i8anNSLCsfsDFWg8URCBXLl3QZNkUE3ryz6uLaNSMUMAgG0EMXZpPwLqspXFfbC5m2TxSqFAqTuMwcA07rOI4guOJ8QuiPBzi7vGYUCKRMQUMXfqrOTJMCvFcnPyTNHZ6x2ZhaoIodtwyFBouyXOdCrHqi5NWJQirTyePss-OzQRDuV9I1ddnKMNrl1rOI_3ncW6YiiyzZ-xGqpvG7dPI8AHKMNaMAdJjylqZBqxrLt9NAyjHNLy28i0xpPzdcVyxn4v4qiOcwAlCg-BZN90FE2pu1vzf6CiJ4BRqPzXWrNg4M2KsAt26s-qgyXj_QojBtQIkUpPb4Lw95cUvqg_eqFnrmxgaIAAmkxdo31rphRbiRNul1SFi0gUtXBTFdiZVgEmIg68-z6j-kTDcRsOHb0XgwiAohvJQHaIXNhPQcRTRxHdI2kjTa0MOsZdgkQkGNUugcB8K4mZgU6hoiBB9QbsHaG0NAWoLpcT4suQSlCLH6OwaTJRWRiCmHMefZqUFipcSmiPPglYqzWxbCxcRl0r6lSgq3ZmP1cTZwUTgsmrA0DRFEMdJANtcDfUZmuCKc9Vg0IMebXQqAbCMLojAFhE81FOXXLdbhlCqkxPyWTQpxTBHCNEUXIBqc7LhyNlnBp9iOZcD8YWNQOtkEgOkfxRGjso6xIcWeIZ2pcK6xbozCKLxanM1WfZEe2hFDhhWXvX6l894jwAGoFGAGPGGqzniIxbuc5-OQgkXR-JvPGzlembxHgAdRUJEEgCwzCB3PmFH6iNQW_MLKlM5TyiB5V1pvVYvFNk6P2KcuZHMfm5ERFWIgdtbqlWTi7QlvyQCoGAPEAlwdwVGxurMxpxkoQwlQHCRB5ig5hQdp4zlB5UJxhVEcOYMZ_hqDlIWOsOZULm0qKIPgiwACieR8BanyAHVCcB-Rni1CUZUR4ymNm9E6VCOqhSVD1SqDMKhmCnQLEWZMFrNiVkRNEFEElRD4HyMABeZNTyOpVGoqQ8EpCoQUYwB-0BqxIDdRJG0noY3updOgI1jB7FCqoumzYmbggCoPDQYIoQ0iICzOwEo9JCCkDpDWRI1JKBAA

### Steps to Reproduce

在`dataset.dimensions`中添加`value2`

### Current Behavior

<img width="400" alt="image" src="https://github.com/apache/echarts/assets/30469146/df2f42eb-947f-410d-a3d5-d36a40cdb468">

### Expected Behavior

<img width="400" alt="image" src="https://github.com/apache/echarts/assets/30469146/b5745170-6a12-4792-97ec-d9eb522a6c93">

**Comment by MatthiasMert** [comment]
Specify the visualMap [dimension](https://echarts.apache.org/en/option.html#visualMap-piecewise.dimension).

[Example](https://echarts.apache.org/examples/zh/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKgkLCIEPi4jNh4RGRUQaKM9tDwSAgwjMT4SHCMMACyUAAOpFJ6Ahai7l4-loHBwQIANioA1lAAXAFJTaItjFZwPQC0AIwAzOPmfU1wqCU9AEwArLP9wehRcBA946tzAL4bTcJQ6FD4-D2Nm4PDY-PjAAyn_QtLossAHO9N21wux6h36JzmUj4NgKC1ErHw9lQUluc2CDxGolGAHYAGz_YKfFZ41GiQHA77HJJHRLBRZOFwAXl6_QAbrkbFAWsUvncPiASowelISvgUoxtmoLCT0UKYPhiBA4FLNiEiD03iTgFAAB49SYATheRuN-NE9k59hsbQARoMenAYNDTSgMJgoNbGC17Y7GKb8tqMQBtKTCeUQapSbDoKQAXVNBGAjEISGchCFLM50Kkx3-C1QLScPPB_XkijUQZJvM2UVljCQVqVpuCCaTKdMSB6wcIUETEYzLSzlik_ehy1jTdEJhsMHsgtEgZJ_X8om7iaFrXdPag1RHc4ALD9lssXstJpZd8segej6JiyqmsvV3OpBukJ0d5m51jpnu9_rz5-l6iN-4y3hOwSPj2z4CHKABepjbgBA5zjiqyrJMazrKIF49Kh6FgYuD4rlB64wJ0yYqB-yErPqf5TDM2GATRf4EfeRFPkKYCcvgVioDAhD4IhjHUaIkw_C8e7jHukxvMJo56uJkmsWxATEWu0hgPmfF4EiSHQiC4w_FiqyHnpjBAashlYspbGQepUiaYQhApE4lqNnJc6TKshqTHuWJmUBXmGjZ952c-AAinoXLAjBUfpoj6uMWIvPqywBT0iXWXetlqRFuQOgicCiKgViiJpA7ANaglxShGF1elog4hhIUqmFQoAGItHxURCbu-z6tMxk4n8HlAeMA1JS1mxtdIADijB8TkvWfhliX6rRWE4Qla1TUuuVCuclzXDV-wGqeUwNVMqW7exJHSAAkvIaAnaIBz6qsWK_Jd3mrDdEH7Q9LQtEQqC5C94y_MZmGXZDv3ZaFANSPdhAEFA3Yvahkzfr5DWY1l4GqRxD0YMtIkyVikk_Hio16i8FN_YTd1SAA0mjHhIC9vw_N5LybUx3w_NzDMzSzSZwDY9jtCAL3SYpBwNbLLzC4j2A2Lkgno2ZV44i8hkDQrOugfDrWI8URCxVrr0YWtaU01byz6srRNSMUMAgG0KMvSZPx7qsTUNd7e5O0zxSqFAqTuMwcAc5bOI4nuOJSXuuPxziwf2YUCKRMQaMvfqguTJMOsNfnPyTOnz6Z05daoIoXtY4lBoBw3FdCpnqi5CmJQipz-d_ss1NbQ7Put9I7dTnKGMnuNgu49Po8u6Yiiax5-xGpZkmXevC8AHKMNaMAdKT8WGWhqxrJd3NwwTIt7xm8ic8ZPwTQ1yxP7v4qiOcwAlCg-BZODDCdNDKXSAR_dAohPAFDUNLS2gt448wavAoOxtpqIz3hAwojBtQIl0qvb4Lwr5iVfoQ6-hF_rOwwaIAAmnxdo4N3rJQHgxLa40PpK1QXtShfFdhlVgPmIgx85z6ihnTM8dsRHn13jwiAohwpQHaLXIRuF1o4i-nbHE60F7sEiHgvqr0Di_iPHzZCY1DEoJvojdg7Q2hoC1C9MSUlDyyS2o4ix5DGb2XYFkYgpgHHPwGuhBqYktGcNuvZPgSZkzuwzAJZRr035NXQoPfmENcTlzCRQpmrA0DRFEPdJAHtcDg15ieVKW9VgcMsc7XQqAbC8K4jAARK99F-VPJ9cRW02kZOqUzWp9TZHyMUXXOBhcvLJztmXHpHiRZcCiXWNQFt8EILUdJXGvs06ZM8c-OZ2pKKWwHrzVKLxOn80Od5Be2hFDhgOVfSGr8r4LwAGoFGAEvDGhzni4wHs8_-OQ4kvR-KfKm_lJmnwXgAdRUJEEgCwzCx2fslCGuNEWQrrEVJ5fyiDVUtqfVYklTmmP2I8rZIsIW5ERMmIgXtPpNXzgHWlkKQCoGAPEGl8dkV2w-ps3pEToTwFQHCXBDi47JR9sE0Vt5CIxhJEcOYcY5hqDlHWTslZCLO0qKIPgiwACieR8BanyDHQicB-TPi1CUZU94mk9m9E6QiFqhSVCtSqUsKhmCPVrPWAsLrNhJkRNEFEKlRD4HyMAHeTMny-pVPo4cn5sxsTCYwH-0AUwdmZCpG0nog3BsnGgdAdrGAeLlYm2V8qqQ0GCKENIiByzsBKPSQgpA6SpkSNSSgQA)
