### ISSUE TITLE
Some issues about boxplots and datasets

### ISSUE THREAD

**Issue by DimeSnow** [apache/echarts#19677]
### What problem does this feature solve?

https://echarts.apache.org/examples/zh/editor.html?c=boxplot-light-velocity
In this example, dataset is used to implement boxplot. But when I was reviewing the documents, I found out about
The configuration item for {transform: {type: 'boxplot'}} is briefly omitted. I want to know how to customize the value of the horizontal axis in this example. I tried to ask AI tools, and the answer given was to configure the data column of xAxis. But when I configured it, the chart only had the correct X-axis but no data. I guess this is because my xAxis is directly configured instead of referencing the dataset.

### What does the proposed API look like?

thanks

**Comment by helgasoft** [comment]
yes, API is missing, but there is _itemNameFormatter_ in the code example.
For instance try ```itemNameFormatter: (x) => {return ['A','B','C','D','E'][x.value]; }```
📌 please close issue if problem solved.
