### ISSUE TITLE
[Bug] Must dataZoom data be consistent with xAxis data? If not, how do I set it

### ISSUE THREAD

**Issue by zhaoyangguang2017** [apache/echarts#19674]
### Version

5.2.2

### Link to Minimal Reproduction

Must dataZoom data be consistent with xAxis data? If not, how do I set it

### Steps to Reproduce

Must dataZoom data be consistent with xAxis data? If not, how do I set it

### Current Behavior

Must dataZoom data be consistent with xAxis data? If not, how do I set it

### Expected Behavior

Must dataZoom data be consistent with xAxis data? If not, how do I set it

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
_dataZoom_ needs to be attached to an axis in order to zoom; otherwise, what values are we zooming?
