### ISSUE TITLE
[Feature] Multiple stack names

### ISSUE THREAD

**Issue by mKainzbauer** [apache/echarts#19682]
### What problem does this feature solve?

Currently, stacking is possible with 
`series-line.stack`
`series-bar.stack`
where stack is a string and series with the same `stack` are stacked. 

Consider you have three series: A, B and C

The problem: one cannot stack series B on top of series A, and series C on top of series A at the same time, without stacking series B on top of series C. It may be desired to stack C on A, and B on A, but not B on C.

### What does the proposed API look like?

Classic: stack is a string, A, B and A are stack on top of each other.
```
seriesA.stack = "a"
seriesB.stack = "a"
seriesC.stack = "a"
```
New: stack may also be an array of strings: B is on top of A, C is on top of A, but C is neither on top of B, nor is B on top of C.
```
seriesA.stack = ["ab", "ac"]
seriesB.stack = "ab"
seriesC.stack = "ac"
```

**Comment by helgasoft** [comment]
I think the easy (and proper) solution is to preprocess the data and calculate desired stacked values for certain lines, then just display all lines with _areaStyle_ without stacking anything.

**Comment by mKainzbauer** [comment]
Easy? Proper? Wrong! Manipulating the values is definitely NOT the solution. Just a simple use case your proposal wil fail: if you show a tooltip on the value, it's wrong. Furthermore: imagine you hide one series, now what will you do? Recalculate the values again (and even more wrong)?
Your proposal is simply wrong in every way.

When you stack series, you stack them, you don't manipulate them.

**Comment by helgasoft** [comment]
ok, bad judgement this morning, sorry. All your arguments are valid and my idea/statement is false.
Now lets look at some code. Lines B and C are stacked over A **independently** [Demo](https://echarts.apache.org/examples/en/editor.html?c=area-stack&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrAIIBOOdsAwgAs6XMJSIBfADREwwYFkggCqYhi4QA5ppxcqdUhADOlGWoPGACsAjQwulUTVgAniHyxKDLsCMmzarBYdABGOFiOgcQhjEyaPgCu0Kz8CsB6ngDEAGx0AOwAnAAcAKziURJOsJXo0kS4Oskq1QGkHIZGBADaVaqBIcBJrCIuAOJ0yrAAZnRYRjgBasP03ZQAsjCmngAqCThblADqbAfbggkHAGIaB9R0YlKe1EmUALpVNbCvAS7txip1dDzDQ4TqwHpqPpqaB0AC2HkoHFMVXQrncVCwtn2i2IRnozCoIWRUREvFoLlwAJx6BwsJAwiM_0IUXQU2ADASYMowIgoPKgUBgWWdG6AEYAEwABkeooAzOKZZLRTLZQAWR4FaWwcWyrXi0WS95qQXoKHEGHwqhI6kYNwIzHQbEo2B42JUBjEwKkujkynIE3EWn0uiMsFmtRsjlcnl850B9DCsVSlUK2AG5VptUavW6x76w0fHHh2AWhEAIU9zjtGKxldx-KYhLr6G9vo8SHjsCDDKZxdZ7M5VBjJjjNsT4PFybTRVTooKGZ16u1msestzsFlBqNxADxdLVH4zdt6M8DqdUVdBM8Hptrdcfo7Nu7Id7zv7UaHul5I4qY_uIvBUUShzVMpQzIClznLU1y1VUt0LIh3gkABuIA). Of course A is duplicated, but the chart should look like you want it, no?

![image](https://github.com/apache/echarts/assets/13038071/bab9adbe-59ba-4b0a-b1d5-10ff8c553099)

**Comment by mKainzbauer** [comment]
Thanks for the input, this is a partial workaround. One side effect is the duplicated entry in the tooltip:

![image](https://github.com/apache/echarts/assets/58649043/00debeb1-3d45-418a-a737-5517d592ba89)

I use custom tooltips anyway, but: is there an easy way to remove/exclude the duplicated series from being displayed in the tooltip?

Various other side effects from duplicating the series "A" may also occur. So it seems quite a bit hacky. Anyway, your input is very much appreciated, I hope I didn't sound rude in my reply. I totally understand bad judgement in the early hours (although it's late in the evening at my place :) )

**Comment by helgasoft** [comment]
>  it seems quite a bit hacky.

Yes, it is. 
> I use custom tooltips anyway, but: is there an easy way to remove/exclude the duplicated series from being displayed in the tooltip?

No, custom tooltip is the way to go.

> Various other side effects from duplicating the series "A" may also occur. 

Yes, we need to mitigate them - [Demo2](https://echarts.apache.org/examples/en/editor.html?c=area-stack&code=CYQwLiCCAEC80G0CMAmADAGmkgzCrSaSBOALFgJybQo7UqEC6A3AFAD2ADmAJbsB2caAG9W0aLzAAbAKYAuEWPESZADzAKA5AGUIAYwDWM4NEgAnGSGgBhABYgzYTUoC-GJWHbspvTgtHKEmY8AOYhMmZaIKo8AM6a7oHRcQAK7Dz8YBH-SoFgAJ6c8tCaembssfGJgdBSIABGMlI5Ncr1IIYh5QCu_MDW3uyRJQDEAGwgAOwUABwArM6tLrnQy-JuSrLhff6r1aqQMbEKCCsBNfXsvaBm-QDiIH7QAGYgUrEy1YGgECeaALICBIlAAq3RkwM0AHVjJCQbZupCAGLBSHacBo3qaRgrNbQRjVfKHOL-DbiD7BGTHRBnFbifggAC2xU0kASdIkhRZUgyEK-yli-gMWnq7NaDksunyslJ_PEMkZnHssRJIhe7D03WpmgpPCpmj2HJ-IAUxsguP550CDOZWjZcs5RS0PP4fI5go6wpKejFNVi-UZl2aJX4Ajd4osIClMpEekGkU0YDMIH4sU4EsymjJNRdMmjxWEcakQzkieTqfTFkz2cCCqVIBV1OE0GAcQasmAciT4MNrQ-sj0GjVrdi7eMXbMPZrymNpvAUAttNaNpZACFfXkuc7eRuBUKRbvxBKowUY8I3NAAF5yHAOuvK1XN54arVaXX63s1WeIFDoAgzfBsAoYgaDILAUCoLAcDoKCmEXQIrWUFctGsQ9HW5HcHQ9QwtB9B1j3zWUrzkcgOXvBtH3VTVtXfeJP2-ecTiQOZ6DwcCiAIOZyCA6hoOoUg4MCbMcRcZggA)

**Comment by mKainzbauer** [comment]
Now for some real world example, I implemented the workaround with the custom tooltip and it seems to work out for my particular use case: [example](https://echarts.apache.org/examples/en/editor.html?c=area-stack&code=MYewdgzgLgBA0gUQJoH0AKBVASgYQBICCAyggCIwC8MA5AA4CuATsABYCGEApgCbUDcAKFCRYiVEQxo0AGQCSZSjQj1atADYBLHvyHho8ZChwB5AHISAsgqrVhygLbbBd0YbRZjpDDms1ajEG56YCddEQNUfAIsAHFfW3ZGAHNQlwiUUlkiKNj47g0IVjZk1L1XVEysBBwAFWlIs0s8jUZOYCg1AE8cPXpHXkEBNU5YNRBgNmGiKEYNMCTFak4wAFoMIh0BEFooDXBFAG8BGBhdjs4ALhgjk5OoTgAPKCvqNBAAd05GADMx95gcIkoNRjjAAL4AGlBUBAIDUu1oVxutxmGiSKUYLzYDwK1Chtxg2IKbzm90x11BBKgnVolxomjAnBBBMhlJgEBYHyuM3onHxt1oIAgGl24Bec2F3CZ_JO3xAjHsbCgZKu33oYHaezAMAAFLRimx7BAIacNMAANYjE0TNRqABGbAtAEoKQSTsNYDC4Qi8DULNJKGyCdQADxQNh24YAPjDjBjUG4MFAagg-rAFAARAAmDPs6nDTNysBQFbCgBedIepcVtr4Gaj1BgAGog7c5QqlTUQNJxpNODUNI5prN5nqDUaANoABgAugA6IkQABqk15LpbbtuoYA9AmY7u4zpNx72Zz_lRvpMuIJN_rGIaIHP2whHSwdTqRZx7C6KFHXZuYG3bc7DhTg5zGJIdW2UUwCdG8AI0b5dWgrU5y4WZOAgCdP3sNCvi0CBZDAKUHnnMBDU4GAAEIKCoMQMlkKpanqIxGgwKxyAAH04mAUPAPCMKwnCBIIoiSPnaBHXNShaKUcMLWoF1kQAmBEN1KiClMNhTA_e5cO4JU2AnABGGcnSU1tNw5D5FB5Th4JUu5YXhDRaF9f1mwoSyANDGY806AsMyLEtyzpCAazUOt424Btm28zdhMVRhLUYOLHLdYT0IIrTHDS9KtxDXcYrDRNoACzhM3uJ4VkmNEwCuWYkhYKA-BgfVuHyeYVmGb5nhgYyp1oB5WuClZPjRZqrjtOFuCixsN3y2V5UVKBdK_OcDPDEyZxNKd13it1GwAdXmg7g0KvcLsPByALBby7s3ME4NbVooCYbVrP-AB-U5nJ9P0AybGgLojaNGxeI9bge8F-WGFJiKRVkTgeAgcQgJE2U-7lGF5GUYHsOYiLJAA3SYrgAZgANinGmabxxdpDmOllNuLGYEvFNODZJHbkXAcLQxqyz1VK8uZZPHqVpF5dkcPFMfUEVGcZQW3TZuzufptHpAjTg1BVglgqIDQKyuAbudBHnOlRgpEf5LLMKuCc2RZk5yMcK56PcTxvDIPG7hpOlqAZaVWwgTp7GmvWaDAcAQ83IDJIFmg7Tlzdk3lF5kjtHUswAVlzk0synAuYAADkp3a51Lp1U7dTa2Ed7yTIAdinABOSnyYAFmp2mpxNYzyebru5yLynx4nrMsy7wedqb4zW477u277_v-q7rvm7nSm2_Jve9678m29zrM55Ulv287k_V4H4y2635vc4n8eN8p3PTL924L6X_Ob7Lt-5zk1LvvA-U8pylw_vPReV9S5_3vlmOcC9V5TiPjPUuZ8ALf07pTAafcB65xQYg3OIDu5ZmMgNcmGDNxYKpl3P-C875zi7lmZ-b826l1LrnKhboaGU1bng_qEDyZzmIcgp-xlc5t24QSGh_CBHGT4Qg5uJCD4d2btIr-SCl7KPodTSmVce7Py7rnUubcpGfxOLI3utMB5UynNvKmz9H5t0HpA8-WjO7NxXvImebdt5dzMYElxWY25kI0ZYjxQCi4CKLqXB-BDV7kynFmdRFiYA0M4X_Ke5MEFTkHiA4x5Mn7hPSZEjh9D2G5M7iAu-K9H4lJoS4-hudW6IOQUg8mCiGmRLbnQnx085xNOQTgze3ToFHzkXTfqJ9cmGIni0lhbjMEeL6fQzeuc5zN3Ls_X-R9zFQMvnQpJ8jm5F0GU_VhXjjGpIOR3Oh1iplkIUaPBRz9S7MOIWMw57cslkJHs3Vhb884Aq4WkrBM9ok2JgGQ95LzAVPxYTc9x0CZ4JKhWPEeLDWGcIXpQsFKzjKwJiRIvxzDAXJNCaC25lNmG4KhYSkxo8pyArzjkruXy7nT3ocojZpzLmdx7qffFKKUncqzMIzerCZl3yWdQlZxz5E0vsSfIJZj-HkI5TSveujiGbIBU4zplNxWasPg8teEiclV0cRPPlQKTVHzWRAq1gLS4hI7ia5hzTCFJJZUfFJHq0VTIkZTUugyVFD2HkUj1RL6Un1DXfEhhLh7oOFYc9-ay8lV0mXkkNj9KYmtzqsoNOT7FDxISkuJ98C3ZoHlPBB79LnT2Afm1NdyzXmoUaGlVQSIHvxTdSnuCqg3F3scfVeC8CF4oHePOBHCRFYvmaAqlyLDk7zgQA5l5KXHNyRcslFpy_7AOEdgt5WzXkmsfn_ENobW6sI3tsqdK67lbL_vnPxgKQ1GsPv2p9NKIGvs3tvYhJD27d3Za2GcGtnatjdnST22AogkFIJ_SWgdg61wJGHCOcIXgx0ZBh1m8lzQvETuaAjJxiicDYNMcqttWzp3JNQLOOcj4mmAWxte9jq7kZgPXRuv7u5msrrOVtArvFQvsSJ6lRTIVBtyZqopgbONzikwJkxf9JMKZwRplTWmi3KdU3uy-VMa0wE06JoeyDhMKZ0QIruobDNyvGQCnTjmeGRK8a5hTrqvMWcyQI8z0nynyPkxZoZEndNhf09ZsLpnAu_v01M-LRm7koN8wO5l6WEs_JC5FgdxlZMGZNRIrLKWaWEtK05w5ZCskjzczIlZXKAt5YS6K3L9XNEoqHUllrZXD7dZiwOux7X7XiZ6x1iJKLPXNYm6UqbSnBsJfs5V9zKL00zYLdFszvWqt3JaSthrKL221p26t1dA3oV1ZNTOjbome5jaK3dg9dmHMXoW9t2b4KX23YHf-jbEGoMEhdjAWDHtDASCkHIX2rZUMvHQ5_LDkdcOxx46RkjRGeOUeo_mZmPMCQMczkkB0OoF5d0LoPWtbdK7cc_nx9J0me4Hc68ZgJTPJvGevj9tT73ku7ZgWzubxntNc7K7QgXvC4uncO8Z7Nj3pO2fRVdizLmRd86Hg9xboufOq7O0vfzEXPtlJjeNhT4WTdRfFz0yXhuUXILl9li7vPddKqEx9k1OWDfFcK5rvnqLLcooqzr6XnK6Xm4HU1z3d22uR6G1Zt3d3tVB-Z3c4bMeEsOqT-zu502099eMfQ0LA7luZ8F3t0P9u-uFv92m631249O-DzSzu1e22u4b8npvGv48Due4rqXHf1m1f71nml33c--7-57gH4toOblB-kEw5h2LQ83LD-kTNUfhyR9HFHn8E5EZeCnT-BOaDMfFVTsu5MOOV0pjXWnhl-Oi8ZwI_OW9N7ltMUax9T-u_5w2QEy5U5DuIVaTTnKFExDZSRRNQeLxBTX-ARI1fRfOEhT1R-b_NXdTBAshbeI9EBHRXdNXYXKFbTKuFBApIuNAvTV9FebeapfeFhFpCBLTUzExfRRPPuC5aeGzOPFpfROJFRAJKeH9UXBXINYeYyQBDuIxXuIeGzV3VuLeJBVeUJIBAg53dXP-AFBBV-HZLxaeNQxvKJTQ9hJhZREhcrEJbzd7GlPxKcMw_eQpYhFtILY3NeamUNHJKVTpJ-dA9Qs3NwlJERa1ceYBThf1C3LA4RDPVeSRZwgTe-agvxPOVVFeQdXwxvRLNeExPxAFVVDhCNWVZ3I5V9OJKuBdCeWBFpdlO7TLF_d-BxcdR-YBaojLX_ZhRBbZeZPOamEAhLArV9EJTZfrEBKee5Yrd7YhBBbucdd5HdFovo1wk0fOUNbo1hNLDhE1GreRTJTZHeVVExFJAwgfCPR5fOCQrZflOhXovraPR5HdBBd5RNDhEJZdPrbrNeEJYyEeQtFI1uO-YQ33dgqZY5CQqvVeN-J-V4wE13TpL4oDMRDuYuUbP-HJQlQBewhwlQj1b3GAHJFpQZKQ5-c_KEoo_PARLZetJTKcDeVudIgfYvdFXVZlPI4hDucuAtcvQuVpOZCoxTHuEkjIsE9FV1UePZIJQdYpO7fbARbuDw4DEBFeY-QojI47GAMxNgzol-WBUxfZBLZvGJCBEePRN5P3I4kfQxFEhRYRArctGmMhOIvrNdGU0hSQrdJEp7HEiNEeTeVeJ5WIt7LJPhPxQeVVCkjeOk80sfINXeDZQTN5L_HeE1SfINI1LeFxQFNBTpSDTcbMqGPGYHefeiSoaoOoBoJfDiFDAOOHDfBHLfHDHffDBHA_OSKSTHVobHWja4PHW4E_JjInHOfOQuYuNjCubbGnVsOnJ2ATZ_cA_E9_EYz_Y1CzVnOo__Qk8ee44AuAnElpYRKAmpGA3U0XeA4glhEReU0BOwz5CzTA08iQkNFRfArTTkmAEg2BFAig686TJVF_Gg8ectN-M9Zgkotg94zg-YkQnggFLNAQ0JLMAE9Q0QteXeUNZtIxSRTeBCwwlXKFBQxBWXFQuJGzLvLQphHkwC0JUZPzHErxUNeckBCwo8tXfXKZGwlTDE7uYhJw7zRYmAWIwBcot-bwzuU3F81MoI7FIBE-M00vTuXpK9cVSQu3f02LRI0eSRVVak6pd3Hg0xXYvI4BHdZUgfNLF_Uo11F1YuYed3V3M4hovuCdZo93X_JJDoqVbo5JL3AYnI4Y-grlB033ErF_S1aYhy2Y6yu7QPWclYi5Z-dYrC44l84NLeOS_YjhArTYrbXFXlQSgFQTa433W481U5CVfVLoshFxe1OPBROhedX4mmDVBPC7BRXVHdS5Q1JcobV3C1B44IxRceE-ZEnxJ1NCt5N1AK0knEkrKIzdIkv1GS8FMk3CheQBdtcM0xaNLJJkvYwJThI-T9DkrJbkl1Pkt-TbLJEU8_VVCUiawU0zWUlTXeEhFeThBK801Uh8xBdcv9cBAFa7Zqkdc5Royda7V3dhLtQS4DD5a7LvDuDZWauK7dBalZXvKZWBd9PquJCBceAMhAmlTZBGmlezf8i9Xit9Wg7FL9IBJMl8wtFKi87VXeDeXMgkFmmGWfN0QswwYs5iMspoZDGHKs9fRs0OOsqOagPDOOVWZs6gUjQEYoFIXgT-LHGjYYOjNOOEDOU_fsvOEuIuEucuanO_Cch_enac2yucji-C4AiM2S5eV9fOJhb6zco1bc19ZRERJ6_echdXOA6ws85A8gq822mhW81i7Ah8khJ8izIg1igaUgj84Oqg38-xf8kYwCpgmOlg8uQBMC8eLg5XKCvgji5eIQmzC7FC51dC3pLZOQzQuw_C5BQi5G5zEio1MiqVPQqioLGikw-i_eRiqwq9AJdilAriqmHi6gtgyG4SkOnpMSwIpwt5KS8I6TeSyIpShE26jvCZNS5IzStInSkonInasxfIoy93C7ExLeCy7FKyiC33Wo2c-87rRy7uZy19Vywldyp-TyyKncwYyNctfy8Yz-qY_TQlTeCK_LMmxlVYuKpJDYqPJKp-FKsUwJExCBAqook44qopTZXKgVV2qPUzBeRSyVHZKeGVKq3RWq7tIJdVYy80oE81ISvVdqhRTq9PbqyYqum1LFQahPLvL4kavqkNca7Er1Ga31UJFuw5JaqZZuFa1PWmdapi0k3i1lFTU-9hVkg6qUl80VJhE6_Ofk86g0hBK68Uq-be806UqFB60DZ68BExOvK9YBL6u9bUv6u7fU-lQGsdByy9Oeo7MGudE-Lw0hAUgfJ0qFOG7RrdBeOR59HE9GhxbFM9HGp7aw_G29IxYmkSp7WB99F1Kmt62S-zWmwDISkDJm8DHMwHW4AsiiMHSIQgXIAW1fIWoOGs0W7DcWyW1HGWuWxIRWtsqjVW3HY_TWxjLONgEnYecnK_fqEJG_Y2zcSchnV3bGzZcNHJWA5crvUxBBO-D9CE8p0OnEr9RBOgkY05P2rJIBK1O3QeVetTXiopexApwFWU6JkfKmF845wBKkmmZeZO-lArG9W5kBOw4CkLQI2pFI4-d-wu-hduDZcuO3ak5hcu4eurduJF9-Jhu2nC1i3VcipxZm5XLvQCplPZvhP5u27Xela20eMq1hL4oe-RA4wZTIu0kJ4zYLelKS3Zj9R-WeMLF83petaFveBeDaiIqFWBUEwrWmb-03UzOCzZTUm1e-C5lZO3NjHOnNM5-Cy--hfJRBN1Ay11Gy5pfG1gs59hD-xVWFMOhywp_LKat-b0kuvedkyK97C1CQ0JJ1wtYrXihRTNBRJF9hWQ5BrJGg2K-FchB-nBrbdvc0oqn3Io94nNjIlh_NgfFRivQErvTNipnPMPJbd7YBPxXc8NLSzakLR-K1vZ9-bBwUpK1xJhMglRMJKUrKlBeNPZ6eNNu6w9YeJhcVcNe-ZJpvOPezWMvZw-FBRl8FPx6tx0tvYfCp2Jrd33VG0tooy9EvL7Xiit8FZMorafPMjmgkLmioLIHIOITpt0NfHpkWqyMW5HL96WqSdHVs5W9syZ9Wt0XsuZljC_djMuZTLudZuuU2qcp_Hdm3Fnct3dy5lvK-HnTDyJd1ot_52O49wwn88fdQvhbDyzKjpCk0R-b49tGmN9Ous9jzDDtDvXHEy9spXDjjzuIVg9vwl87j8Zde8jwwhI1j23evPD23R3WT75VDl18TgffoqTw5IKlT80qKwTjIrYxk4M6166mlddxrLbHZp-mIyRTY0hlBLeMRieAacd4t6qlJOrVVhqgNobZq7uB-WVveXpAVlPHhneKufJctZFoa-lZRJAhzr_Tt-kqa-j7eB7PuLhvPawjZO-LFzpQ-ZtrTip9bAr8FIU3TgfexnrFhLF0DV5txmU6N1L2mdL33TdvB99ZNoxHdUGrJUnT2s5g56dLvcVHdAS2Noij0xN55XAgQoL0fd7IuOE3yqO_V_dSNoeDZIM2N2byptF2BUefzptdRW9k4aGSDMEQQNUDUGCdmZaTsbsXsYYAcIcVEUcTaTgCyE4V6d6EHTgf4ImNQOcUgJUfsQcTgAAMVu9WjGBtE4GHDmCSBNBZje9A5oH6A0D6AIxllh5xxI05EYGBAtidCfEh51De-ejulJlShjiwCo06iSDh_mEWBWBWB0Eu81H2HbBWh1DAD6DtC-BNHyCSBFAgA-9UiQm5956-BkioGp9p_h4Z6SFF8-5GG-554ji-HgmhjV759SioFMEl8YAl_V8YGendBGBBz6AV8UDvC4DB7GCVCN517nBhDB40AeB4FJ7RGF_Mmd_u5h4V51DZGh77AV9BFN5gBPClGAEHEmCIE4DvCVHlEUBSCgFIDaBj7UDj4T5hEN-D6mBe8V_gjUk96F6gAgBgD_CnBgAADJq_qI1eFe5w5hgA1B6ApQIBSf0-aws-DQc_zJ_xXZLeC_PJeMu_Y_4_e_5Qbp2xdQTwNBFApxWp5-QxeMvey-l-mwmwlfbgG_h-mwbApxIYTuLZQQvvGBtRd-RwkhBA7oBA2fruU-0_o_u-J_7wc-dQ8_3v_wTxtQqAJDjJ4Iv_EHL7x7D-8C-H_B7u9zQj0A7Q0AK_iTkLjh8z-F_G_gIDv7qh2e2oR_mP0z6v9E-ufSAaLx_6KB_-gAxQGABAGQCA-n_InsoFgHgDjIiA-CMgJBw38gAA)

The example shows the powerflow of a grid-backed photovoltaic power generation system, on-site consumers and a battery for storing energy. Stacking "charged" and "directlyConsumed" makes perfect sense in combination with the "produced" line. Also, stacking "discharged" and "directlyConsumed" makes perfect sense in combination with the "consumed" line. But showing all this data together would resolve in a confusing stacking von "charged" and "discharged", when charging and discharging occurs within the same interval, and not having the possibility of keeping the stacks apart, although they share a common base.

Thanks for showing me the workaround.

Nonetheless I think adding the possibility to define more than one stack for a series would solve this problem in a cleaner and more comprehensive way. Looking forward to have this one in an upcoming version.

**Comment by helgasoft** [comment]
If I had the choice, I would put (produced, charged, directlyConsumed) and (consumed, discharged, directlyConsumed) in two separate [connected](https://echarts.apache.org/en/api.html#echarts.connect) charts. But of course it all depends on the customer's vision.

Thank you for sharing! Real-life examples are the best 🎖️
