### ISSUE TITLE
[Bug] TS 约束问题

### ISSUE THREAD

**Issue by dadaguai-git** [apache/echarts#19689]
### Version

5.4.3

### Link to Minimal Reproduction

无

### Steps to Reproduce

1. 初始化echarts 数据
2. 使用`setOption `api 更新新的参数
3. 使用`setOption`api 中 `replaceMerge` 配置

### Current Behavior

TS 进行报错 并且查看index.d.ts 发现并没有抛出`replaceMerge` 

### Expected Behavior

提供`replaceMerge`  API

### Environment

```markdown
- OS:windows 11
- Browser:Chrome 122.0.6261.96
- Framework:Vue@3
```

### Any additional comments?

![demo1](https://github.com/apache/echarts/assets/35138018/05244399-79b5-4beb-9ea6-61985acfad1d)
![demo2](https://github.com/apache/echarts/assets/35138018/c1091d83-b612-405d-b788-0918e414c71f)

**Comment by plainheart** [comment]
从截图内容看着像是你仍在使用由 DefinitelyTyped 社区维护的  echarts 类型定义，可能存在较多不同步的地方，从 ECharts 5.0.0 开始已经内置了 TS 类型定义，请卸载 `@types/echarts` 依赖后再试。

**Comment by dadaguai-git** [comment]
> 从截图内容看着像是你仍在使用由 DefinitelyTyped 社区维护的 echarts 类型定义，可能存在较多不同步的地方，从 ECharts 5.0.0 开始已经内置了 TS 类型定义，请卸载 `@types/echarts` 依赖后再试。

Thanks
