### ISSUE TITLE
[Bug] Heatmap in some Size show a blank space at left top

### ISSUE THREAD

**Issue by huiyu4** [apache/echarts#19702]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian&version=5.4.3

### Steps to Reproduce

1.Given the example at https://echarts.apache.org/examples/zh/editor.html?c=heatmap-cartesian&version=5.4.3, set the div (id=chart-container)style background:black;

![1](https://github.com/apache/echarts/assets/162938671/f5cba2ba-5bcf-43b3-be2a-5578af68b073)

2.resize the Browser ,the blank space show up at left top 

![2](https://github.com/apache/echarts/assets/162938671/ebad1dea-a549-4ca1-b59c-b43712ecfaff)

Or  add dataZoom config ,zoom the chart ,it also show up
```
      dataZoom: [
        {
            type: 'inside',
            xAxisIndex: [0],
            start: 0,
            end: 100,
        },
        {
            type: 'inside',
            yAxisIndex: [0],
            start: 0,
            end: 100,
        },
     ],
```

![3](https://github.com/apache/echarts/assets/162938671/35f4ae87-ece7-41a7-b0d4-2b4d7ef96d3f)

### Current Behavior

Heatmap in some Size show a blank space at left top 

### Expected Behavior

There is not blank space in any size

### Environment

```markdown
- OS:windows 11
- Browser:Chrome 122.0.6261.112
- Framework: React
```

**Comment by helgasoft** [comment]
cannot replicate in dark mode [Demo](https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian&theme=dark&code=PTAEAcCcFMBdYJbUgWgQcwHYHsYCgBjbTAZ1lAAtsBXSE0AXlAG09R3QByARgCYBDTgBou3QSM4DhXAMziuAFnmcArMoBs4th04B2ZQA5lATmXcADGbHDt7Hr3DSejiQ6cyXiz6pe2u6711vA29jbwtw7kc8AF0AbjwQCBh4JFQMHHwiUnIAE34AT3omVg4uAGV-WFp8gqcAMUgEWqcAFQpaEhahP04AdWhczGguwrbqEe6uAFliKc5y6kwW2ISkqDhEZDQsXGhCYjJQfNh-RhZmcxEr0BUYkUuRbif7lhvea9fH0BlPh5uFH83iIVEDvuowTddJCRAYYaBjPCLEjnqBeF8bnwRAoMU9fqBuLiCYCCUTuKCfmSIaAcf8ntDQOoyXCaWTEay6WibjIibxUTzObwPmjefi7g9UVCvqjJdKRMLzHKfmDUSTFRKQSqRNT1SxUQzdcxUSzDaj2aanjdxXqnqj0RqCcL7TaCfimQ7uCTjErybafdT3S7uAzdD6WQYfey-EreFaY6jrUb5cLQw7ePjncwFS8HsKZV8nWDhfjDcK1QXNaBS9qiyIDRXQCaG-aG8jKbnbfLW3nW_jvR3ibDWxSLK2A62GYm8yyp092bOuXWG3zscuncv8bSWCWlw98fyvhmwfiS4fscfK4a3RfQPW97Cc9uRC37wS46_uKqz47d0_XU8t2YfcSW4AU_19R1v24al-3AycoJnKCoyveUbkDID5S_V8hVXbD9y-NVH2YECRDA4j5TBElTweElyxoytCXoxlKLrFjGzY9lMxAgECM7DkWBA9cmNA3CBIA0TyIJEdAJA6lo2EhlGLEglw14gl5zU2NSM0_VNOLTTqJYCl3i-EciIpBVTNI7SHgpOijMvKzmKrJy7wc9iRVs58wRHHivIJfN_KxW4nJEt9QpJRMRwpVN3Ogv0goZdCRybIKNP8rT23cld-OYCyhOywzmB1Ii5LBalLIeakiupeziscqqaxcxrb3Kh9mpYGC2rfUq-MNOSCvq_9SRaz0bM6p47K-OSdWm-luu4VKJvU7rMqUoacszCrBoqt0YhiPwADoAFt-HAAAKAAzJYCEQYhQHOhBYGgY6AEpQAAbz8FJaEwFgnpeo1XgB47LmB57QfRUAAB9oa4FBOHiPAAF9XoSbBwDuv6mC-9hYGwbAABtEHAAAuT6_HAbASCehBiHJzh8eidhkZ6dh0CaXJydxjgKGgDAKFgBmVHMABSGwyiZhmLHF7RWe0AAPABBBWEBIbm_FgApwGgBmCCqaB0FwOo2Y4E5-HJqhOlN9gSHAQmnqVmALc-0ASCoAB3cnYEgCYRH4Z3yi1wndY-0AiEJ3BSc4IhIFIBBCYAa04ZHQGRuXTYKFW1Y1yXtd1rh9eeo3IBNvxzfJ2oSBt0AQDth3YCd6AXbD93sC90Afb90AA-boOChD0mPojqPOAKaBCcjj2U7TjPtAANzV6h-EJ6YztzjhjoQTByauPxToV8nkT8fXCYIahCf4AAjQfO996Aa9wJBMCFrgqCaAAvYhTkJiWOBDy6r8Y7QBfsgP-7Ar7YHgNgY60sVCyxZqbEgyAkDqxYH4HmZRMD8GOgXTgAAFG6FBQAAGEA65HARwLWOsGZ8yqKdXwZR2AV2OFUfgNd2CXyvhPDeTC3ae29vfPwiDhGgBeuACg_AaZoMwUwkG_db6yL4e7fguR24ACFCa0CPnvPhZQVFqI9iQomUcuCQHQFffg50bg2OuIdFQr1OCiJZqI9OZQ3GgHuNoc2AAtAmsDPrp2RnEIAA), but see a problem with _splitArea.areaStyle_ - maybe the two issues are related?
Only _splitArea.areaStyle_ from the **first axis** is used, the second _areaStyle_ is ignored.
Does your issue persist without _splitArea_ ?

**Comment by huiyu4** [comment]
> cannot replicate in dark mode [Demo](https://echarts.apache.org/examples/en/editor.html?c=heatmap-cartesian&theme=dark&code=PTAEAcCcFMBdYJbUgWgQcwHYHsYCgBjbTAZ1lAAtsBXSE0AXlAG09R3QByARgCYBDTgBou3QSM4DhXAMziuAFnmcArMoBs4th04B2ZQA5lATmXcADGbHDt7Hr3DSejiQ6cyXiz6pe2u6711vA29jbwtw7kc8AF0AbjwQCBh4JFQMHHwiUnIAE34AT3omVg4uAGV-WFp8gqcAMUgEWqcAFQpaEhahP04AdWhczGguwrbqEe6uAFliKc5y6kwW2ISkqDhEZDQsXGhCYjJQfNh-RhZmcxEr0BUYkUuRbif7lhvea9fH0BlPh5uFH83iIVEDvuowTddJCRAYYaBjPCLEjnqBeF8bnwRAoMU9fqBuLiCYCCUTuKCfmSIaAcf8ntDQOoyXCaWTEay6WibjIibxUTzObwPmjefi7g9UVCvqjJdKRMLzHKfmDUSTFRKQSqRNT1SxUQzdcxUSzDaj2aanjdxXqnqj0RqCcL7TaCfimQ7uCTjErybafdT3S7uAzdD6WQYfey-EreFaY6jrUb5cLQw7ePjncwFS8HsKZV8nWDhfjDcK1QXNaBS9qiyIDRXQCaG-aG8jKbnbfLW3nW_jvR3ibDWxSLK2A62GYm8yyp092bOuXWG3zscuncv8bSWCWlw98fyvhmwfiS4fscfK4a3RfQPW97Cc9uRC37wS46_uKqz47d0_XU8t2YfcSW4AU_19R1v24al-3AycoJnKCoyveUbkDID5S_V8hVXbD9y-NVH2YECRDA4j5TBElTweElyxoytCXoxlKLrFjGzY9lMxAgECM7DkWBA9cmNA3CBIA0TyIJEdAJA6lo2EhlGLEglw14gl5zU2NSM0_VNOLTTqJYCl3i-EciIpBVTNI7SHgpOijMvKzmKrJy7wc9iRVs58wRHHivIJfN_KxW4nJEt9QpJRMRwpVN3Ogv0goZdCRybIKNP8rT23cld-OYCyhOywzmB1Ii5LBalLIeakiupeziscqqaxcxrb3Kh9mpYGC2rfUq-MNOSCvq_9SRaz0bM6p47K-OSdWm-luu4VKJvU7rMqUoacszCrBoqt0YhiPwADoAFt-HAAAKAAzJYCEQYhQHOhBYGgY6AEpQAAbz8FJaEwFgnpeo1XgB47LmB57QfRUAAB9oa4FBOHiPAAF9XoSbBwDuv6mC-9hYGwbAABtEHAAAuT6_HAbASCehBiHJzh8eidhkZ6dh0CaXJydxjgKGgDAKFgBmVHMABSGwyiZhmLHF7RWe0AAPABBBWEBIbm_FgApwGgBmCCqaB0FwOo2Y4E5-HJqhOlN9gSHAQmnqVmALc-0ASCoAB3cnYEgCYRH4Z3yi1wndY-0AiEJ3BSc4IhIFIBBCYAa04ZHQGRuXTYKFW1Y1yXtd1rh9eeo3IBNvxzfJ2oSBt0AQDth3YCd6AXbD93sC90Afb90AA-boOChD0mPojqPOAKaBCcjj2U7TjPtAANzV6h-EJ6YztzjhjoQTByauPxToV8nkT8fXCYIahCf4AAjQfO996Aa9wJBMCFrgqCaAAvYhTkJiWOBDy6r8Y7QBfsgP-7Ar7YHgNgY60sVCyxZqbEgyAkDqxYH4HmZRMD8GOgXTgAAFG6FBQAAGEA65HARwLWOsGZ8yqKdXwZR2AV2OFUfgNd2CXyvhPDeTC3ae29vfPwiDhGgBeuACg_AaZoMwUwkG_db6yL4e7fguR24ACFCa0CPnvPhZQVFqI9iQomUcuCQHQFffg50bg2OuIdFQr1OCiJZqI9OZQ3GgHuNoc2AAtAmsDPrp2RnEIAA), but see a problem with _splitArea.areaStyle_ - maybe the two issues are related? Only _splitArea.areaStyle_ from the **first axis** is used, the second _areaStyle_ is ignored. Does your issue persist without _splitArea_ ?

No.There is not blank space now.It is useful.Thank you
