### ISSUE TITLE
removeData

### ISSUE THREAD

**Issue by Anchel123** [apache/echarts#19708]
### What problem does this feature solve?

to be able to remove data without re render like with the append data

### What does the proposed API look like?

no idea

**Comment by helgasoft** [comment]
[Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcSYOAHmHgOQDGWElA1hsLAE44C2wAbjrDDuQF8ANGljEAgsQgBnPMmGiAnpJlykC9NJzMIOWbADao9KnRnY0xWwBGwLAGUIAL3ywATAAYR59ABMAhmD-ckY-ZgYAjB4AdF6wAByxACwAut5hhokeAOxCsABs0QCcAKxpxj6RAMyxednRJfHlGYZFsSV5ifERzRmREbUJ0VVVvWGRSYP1-fljlRE1SXmF3XPmkTFxhSNr4RGTcYlFs-njEW4Ny9HxbrvoBm0RHbD1t6fzA8-vd4Y1HlV5SZuUbvdbnaJuOrXEEVdYXDyQ2CTJLZH6Rdp5Go7UHhA7PSbHNGFf5QtypHH3cFbCEnWF7eGda7kun3eoeeJ5ErXN4swxchGc6L5Jp03ZgRQgVzkaSUQJEZjkCoCUQpFACADcKDYigAwgALfzMMDRGAACioNHo5DyADMAK7QSiQM0gQ3-NjSACUpl44Cg0GiWh0egMHhS0QCQWiIFAps9mvQoGdAcwuGiRFICETfpgge0umkofDkf80Vw0AA5mA9QnYNr9YbjVowAB5HPQU1J_3x9AAel7dpAkZ4Mlg0GAYBYOBAWH8lBwavjQA)
📌 please close issue if problem solved.

**Comment by Edo2610** [comment]
[Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyGOAHmAQOQDGWElA1hsLAE44C2wAbjrDDubAC-AGjSxiAQWIQAzgSQixATymz5i9DJzMIOObADaY9KnRnYEACYEAjKPOalbAEbAsAZQgAvfLABMAAz2DpYAhmChBEYOZgY2AQB0QbAAHEkALAC6wTEGaQEA7MKwAGwJAJwArNnGDnEAzEnFBQmVKTUx6AblSZXFaSk2HZ1xNk2pCfX1w7k26eMtJSUzdTaN6cVlgyvmcYnJZVM7sXPjaeXLOat-rZsJKX7HXT02fbAtj1e7NmNvH0-GRoBerFeZ-aZfE43PzNe4Q2q7G4BGGwebpAoAuK9YqNI6QrrzAJveYXTFlYGwvxZfGGGxIu5-S4IqFne7U5ldFoBFLFSr3T4cwx85G8hIldrM45gJQgXzkGSUcJgbTkWqCMSZFCCADcKDYSgAwgALULMMAJGAACioNHo5GKADMAK7QSiQGCwS0gU2hNgyACUyDEuDAsCdIDCyoA-hBoJYSAheOAoNAElodHoEg7Y5YAJJxkiWmQIAB8sBkCSsCEQNn9uvQYlA7tT6d0MgM4cjOBjBeImQSkdCCRAoEtdcbyZgCUwuGnJFDiCbKbT2jbHYj4W7OZI_cHCVw0AA5mAjfXYPrjabzVowAB5SfQS21UwOVt6KKCl-dCzWWB2QXoIOBBLlOb7tp2m49vGfYDuEoSCuqMRShA2C-EgRCkMBD4rhm4EbtG24wXuB7HkaQhqlcX5mNAwBgAAstoh6-A6oRYFokJYKEXhKAAqvhvhgMwTo4GqYjjoIdZAA)

In this way you can update only necessary options and, with big data, setOption is more speedy.
