### ISSUE TITLE
[Bug] [Bug] 使用scatter3D 点位无法点击

### ISSUE THREAD

**Issue by swanghao** [apache/echarts#19704]
### Version

5.1.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?version=5.1.1&code=G4QwTgBAJg9gLgERHEEC8EDaAoCEDeueEAdiALYCmAXBAOSC25oHu6gQHp0A0ReoANgK40sARgBMABgB0IoewgBmSSICsskQF1OxCAGM-AZzgxySFLUJa8ZKrUasOXYrwG1MoxTPmKVEdZou6DIxMQMwBfB3C8cLUAbmxsUEgALwArAFkQAAd0egALODhMvWoAehKAd0qJAEs9AEc68oltIxKQPT1KOBKAcy6SvRKoZBAAWiEANjkAFjExAA5p6YB2ZYBOIVHcgCUASQAzABk5HgBPJQkUvRgSOjjsABIJPrgAKQBlAHkAOQAKVIymVk-z4JG0cGqNwgvz6MFe1xIAEoCERKNpcuA4HoJGBKD1anBKGBAb86HIoIC9BwILD4TdEXFQgz4jBMhCoRhzDTKDA5AgzA5yFkbOTKfYtHBTplBHQhZk-eLHNVKOUAMI3OBgGA8AUWaAEkBgwRCBR-LSZQ1pGD6SgAIT4BRuNh4lH2cEVWi1KEJVpt9sdJBsYGqPXydAiRFCfk6wcoxSwDi5EqlMrlCrNxDlIopWSpGbw1UJ5Hekpdur1EFZIG0hdOtDEDii-YgwGVao1Wp1KIrEDKEEA3hmAODlYXzALRygA-3QAwKoAYf8bxCgBqNtBNYmbeAtJF9nX9hkD9Bdbo9Fi9yEoW7tDt3QZDYbnUbnSRdwEoXbWEQzSeIkulNj02mQhJgOmc4tDAYALmQhLvKcBiUOQNgjggR54HopzkAARtq1BzngdAWnAuSlCUaTrBMEiTBAQhKMsEjzBM9ETMs2iTEIUjzJR1ESGIJpyLxlETKxIjsbMNFiNMEBiBASgTNMXFKLxvE8KMIgbLR4lCSIEjTPJCnKapizKfMmnaQpciqkoglSTJEhrGIDHLFJllyFREjLKZcg-KIWnsVRNF0fZ2jLGR8yjMsFxiGspmUfMrFBeMkw2XZ9EOSprEGUICW2fZlFCJICwSZ54XidMmkMclPj6eJGVkVlyVJGkShiRIcgiFJnEiCIAUTGs5GtZJogXEsozya5EyUcoWnTOM4jNSIejDWRLXTZIS0DZNy2zdNg3iSNcVrUs40ra1SiDWVDluLN43bYds1JBA5CSWIyGVhaNaSsuzaPpQz5drlzbDKY0DwMEEZ4Go2ChPc5CnKqGJgHAEg3KS2g8NU2gANbUr8lDImgAB83Y6Dc1wuhIRJamA2PMkyMRAA

### Steps to Reproduce

```
const option = {
        geo3D: {
          map: '3dMaps',
          type: 'map3D',
          instancing: true,
          label: {
            show: true,
            distance: 1,
            formatter: (res) => {
              return `{a|${res.name}}`
            },
            rich: {
              a: {
                borderWidth: 1,
                borderColor: 'transparent',
                padding:5,
              }
            }
          },
          viewControl: {
            distance: 130 ,
            panMouseButton: 'left',
            rotateMouseButton: 'right',
          },
          itemStyle: {
            color: "#275ec4", // 地图板块的颜色
            opacity: 1, // 图形的不透明度 [ default: 1 ]
            borderWidth: 2, // (地图板块间的分隔线)图形描边的宽度。加上描边后可以更清晰的区分每个区域   [ default: 0 ]
            borderColor: "#a1eaff", // 图形描边的颜色。[ default: #333 ]
          },
          emphasis: { // 当鼠标放上去  地区区域是否显示名称
            itemStyle: {
              color: '#ff7f00'
            },
            label: {
              show: true,
            }
          },
          light: { // 光照阴影
            main: {
              color: "#FFFFFF", // 光照颜色
              intensity: 2, // 光照强度
              shadowQuality: "light", // 阴影亮度
              shadow: true, // 是否显示阴影
              alpha: 50,
              beta: 10,
            },
          },
          zlevel: 6,
        },
        series: [{
            type: 'map3D',
            map: '3dMaps',
            itemStyle: {
              opacity: 0
            },
            viewControl: {// 须与geo3D中相同，
              distance: 130,
              panMouseButton: 'left',
              rotateMouseButton: 'right',
            },
            zlevel: 9,
        },{
          type: 'scatter3D',
          coordinateSystem: 'geo3D',
          symbol: 'path://M796.16 157.866667c161.28 157.013333 161.28 407.04 0 564.053333l-291.84 282.453333-291.84-282.453333C51.2 564.906667 51.2 315.733333 212.48 157.866667c76.8-75.093333 181.76-116.906667 291.84-116.906667 110.08 0 215.04 42.666667 291.84 116.906667zM504.32 557.226667c69.12 0 125.44-53.76 125.44-120.32s-56.32-120.32-125.44-120.32-125.44 53.76-125.44 120.32 55.466667 120.32 125.44 120.32z m0 0',
          symbolSize: [33, 37],
          opacity: 1,
          zlevel: 10,
          emphasis: {
            label: {
              show: true,
              position: 'center',
              textStyle: {
                color: '#fff',
                fontSize: 14,
                backgroundColor: '#02172d',
                padding: [10, 20]
              },
              formatter: function (res) {
                return res.data.customData.name 
              }
            }
          },
          data: dotData
        }],
      }
      self.$nextTick(() => {
        self.myChart.setOption(option);
        self.myChart.on('click', e => {
          console.error(22222222222)
          console.error(e)
        })
      });
```

### Current Behavior

1、使用 geo3D 无法监听到点击事件 只有在series中添加了一个map3D对象才能监听到点击事件，但是这样做会有点小问题就时屏幕尺寸发生变化或者鼠标拖动的时候底部可能会出先一个没有颜色的地图
2、无法监听到scatter3D中点击图标的点击事件

### Expected Behavior

希望能够监听地图区域点击和3D地图上点位的点击事件

### Environment

```markdown
- OS: windows 11
- Browser: Chrome 96.0.4664.55
- Framework: Vue@2

"echarts": "^5.1.1",
"echarts-gl": "^2.0.8",
```

**Comment by helgasoft** [comment]
scatter3D points **can** be clicked on 3D maps - [Demo](https://echarts.apache.org/examples/en/editor.html?gl=1&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QzhAaQQArJKkJSANKIBmAV0IBjOPmOjSmgFJHC5UQG9qo0aCQsIgQ-LiM2HhEZFR-ooy20PBICDCMxPhIcIwwALJQAA6kUrpmom4esf6BSYhqcOwFDsakcf6kqE2OhKIAvD5t_qIOcAA2jABcA0Mzw4wAHnBTUnydCAAijIRI-HAgorqiAEwADACMZ1KD_gC-pteiAG6ZVlCj-QVTvrNDwERTAA4Tid7j9qlB5lMAKzA4GgsHZRZTADaJXwxAgZSk2HQUgAuvCfmk3g5gJNhjArIxCbNbG9bFZRlAAEbjKZwSnUh7-NQwfCMJAASUI4UhohB3NERFYUBI5O-YP8tlQo1QMBRUlG6IgcCQAGsQKyqViQIxRqrceYpGrZUw0rh8ZKbg87tQHnBUCqHJ9pgi-cQ7ctdoxgGZJRY1cAFNl1dJvLYbqISVcfq6fuMmCKvq6HpoAMzrL6SmQyeLAArQHZIUToNV66tEcqMVAF8xqcb2Uy2LW2PWiXCoUSEVBwYsyFAYKYWN5qcz-EuiZXAMmEOCiVBWNce0QT9DmZmb0ShcIBQoFyVRn0lHRhxUwHDAdmcmkzABe40eZqmZzzL6GTOZL8fB3NB0CnGdGFENMwRDCsVEyItFX8YNgAAZT2NlfSQxcVTVZZTXNDAUyQ51FWgn4UPQkBMIVRUS2ZNVwhgAB1MI4AgKYTgQKE_xmTooFsXYQE4hBzlEBd8HLNVFFXABCJ1ePE8czQSbJcFyVBwifKklNEfQrCyJM5iyMcUCiEhliZYBAPgW9ZhzH5eX5JAUUlbx51LD0vXwApzG7fBeyTEUpWyNCMMYBBYMrTJ-0HYc11rGA9UlfxCCgMllkvOzFT2ApySkS8C2ysFL2WUpzAXJcVzXDct0HY9GBS0R30YT9RmhRT_Ci-CXKwpDKPCxDsKGZVVVjKQCItYrsP4wS9m_Jrbia8iwXkRRXOG4C0oy6RAFo5QB_SMALmUykeN4qSmU4TihAB2BA8wAFigzqhnc7b8sAPztABW5E6zvJM4oXu67bvugEnsWrb0vywAcOWO8xTtGc7RDzM4ADYARRhAzjBzbXsh5ZAHVlWGnl-qYUYATjJo4EBR7HhtxnapEATptADQdQAv0x-hHyXu-6TnuqEEHusnaew-n8sAR9tABYbQB19Q5xGebRsnqcelbFVF5ZAF05QBM_MAOfVZfJPNrpRqFFeu0GVbBNXpEAEbzAHJNQBNuT1qY-bOIEEDJ67haQy2pEAIcjAA0NR3RChKFTnuhAjhp82fm9wBXEMAJXTA6OM4yeBN3PdVoc8ekQBhYPewPBZd8PI-e_xvcAex1AAvUwOoQBAEzgQAFlZLiGGcAYUVAHRzfOzlN0Ssaj2ZvcAdGUifhxGjnH27KfTi3M4Zm3ABX1ROXa4smzeb73AEybQAGV0Dsnu6psmm_B739sAQljA7zPM0en6PZ_ywBuz0AbJ1A6BDHV6gpqCSat6PiG7CpDAFsDkbwgq4FEMxAUMYTDLAOrDcGABRFQUDlgw2mmCQUSAmQil6lIJ-aCfhSB0BgVUTgwBCSkBrHW-DZiEPQFAfAoguA7BIBQ6Q8dqEzFoTYRhxhiCsN9gHZuAA5aSHFpDDw4UMKQqF6GiB0DYPhywz6SP8NI6AjCiD8O3io6QqFoDAFEHoqwDDVj8MljLZuqFaoQByIQAmcDNpSC4LI0xywF46KcUgKkPRmKyn4bnDxXBvGiFyDYfhlcPG-J6EEfA_CvqRN4Yw2RqFNHLFtg7ZuUgACaUArCMJ2AYjSLDlgs3ZpkrJwTsDFOkB3YiZFnrtlUowdSmlyQcipM9IgWRZSCQshSDpTUAJAVokhXc2kuSbURHAKiNFwZKlwuNVkAk9RlBLAAYgsJsnR_gIyrggdqJY0gGKjAdM3HZxhpn4FfH9I4ZzRDMmWcQe8NhcBgAWcsGAxAHmkBBEcX8FxTAnHIHUkiy1OmhRmfKcGs0hLfmbgxGATFWK4HYiJHi4NupVj_sNUaeFpBPMYFsEFZEwVNTMgQPpmp0o2TgJIrUGJDkjMVFGf4fVsK4vGhsrZdyiDZG2LC8UDc7nksnP0iZm0QJ4AwAARVeFqea0gbEHO2UmUYcEnYSglfc5gUBvwnHBv3GY1L-SrmxdhXlWwdgKq4lCA1y0FJulVk1XK-UkB0jgDGIqz03rLAKKgXlSBJHKkYkQBQjBUIgCyCGZY-Z1iSKQCAayKpfUKA4iWXIogzggjzCcUQAhji_NzSCEEWMYSmBzXmgtphTjikBaYLGKdy25ulaIRtKNc1lpTqIFtWbTDtszdm3Nr542JuOSk65KJubmG5l_c1ELBrAQ5csI0jAygwoVX3Z6LU2rfgBU1TFCE2VggGtRKFWql3SHtMSsEpESLPTWrq0QyJwbIguGHM4od_rmHHuHAEEc8xk3MFm2dw1X1nDDuPXmX7jhUyOH-lGAHv3jzxJ_J0DwUMzBuOQOIsQsM0BqMEBALQpD-V7GUUgBQvC9AAHy-hLPgCwzgCjIByM5LgIA8q9F6AAIjddGHIBZuPYfmdsFUEVVRkCkAUVc0hxDMYfcKUUuHYgEfgERwgxRNCNPsIkW0zTyOUb6LRhU9HGMUZY3yAU7HOM8b4x6gT6whNxGVKJ8YCAJMUeU5QIAA).   Also please use latest echarts-gl v.2.0.9

![image](https://github.com/apache/echarts/assets/13038071/a5253e32-8cf8-456d-83f8-eb5bd70dd569)
