### ISSUE TITLE
[Bug] symbol无法全部显示问题

### ISSUE THREAD

**Issue by daidaic** [apache/echarts#19712]
### Version

5.5.0

### Link to Minimal Reproduction

暂无

### Steps to Reproduce

echarts中我设置symbol 显示不全,有部分显示部分不显示,鼠标放上去则可以正常显示出来,我需要它默认全部展示,
![image](https://github.com/apache/echarts/assets/47729929/8766b523-de68-4dfc-8c86-10f0753090f4)

### Current Behavior

我是创建了两条折线图,第二条折线用于展示symbol 

### Expected Behavior

symbol可以全部展示出来,

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
Pls share a minimal example.
