### ISSUE TITLE
[Feature] 添加自定义组件中，基于富文本格式的文字超长截断和换行功能

### ISSUE THREAD

**Issue by Fnxxxxo** [apache/echarts#19714]
### What problem does this feature solve?

目前一直没找到这块的示例，label与graphic组件的配置在此也不适用，希望能添加该功能支持

### What does the proposed API look like?

如下示例：[Demo](https://echarts.apache.org/examples/zh/editor.html?c=custom-cartesian-polygon&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM73EC-ANMdtRrQAJoVQlYwxmEaEA2vQBGjUvR6x6tUsFUBdbn3TMAgqzZji6ALYRohAAyGSVloQCM9g8QCep9hYkbO1hHS1gXZndPdF5iNloIanNYOTDxCQxvEGoGAGMAVzZMKzUw9AB6cthAcGNALO1AP7VACwjAbx9AaPVALjlAK8DawEk5MthSahFaAEkwaitCADN86FzIGFgAChAVRis2dUYQCABKIgySADcVWGYANUZsfOoEWG2IADoT6-ol-12Abn70E9JYbyXV53B7PK43JZuL4_WB_WBsCAAL1uiFBLwhACZoYdfqdclhSMI2CCdo98TphEs5BdwdR1IDabpoTDKrBABt-gDYlQCX7oAjfRhgzA-VIcHSOMy2QYFG0-RApTFRkI5MJbDk9l0TjF3kVBKJcjc6ph6FyAAsINhhINgql5SRRTbxTkNIN5nL7eg2Mbto67W6AO4QYRgY2EBHIjVu2DG6iUY1gENI6iGjKxCPwsDeAQBVOwKZm7AMUgUZTvHiOMuPADsu3osFZvMAORmAJyCkxIuC3YCn7T75emJRpxswwK6_QGg4QMfZQqmB2AAMIwXMUMSwEDABELYL0WwI4TUAAqoAAMtQpkOO-GbcAjrQpthgL6GIpBowANbD-1FDPe9sSXPYfMaAAxAAHPYoGge-brYLY1AABLRhQsbjgALBe9pTDAYAAMoJu4wFoTaM7yD-GT0EgT7UK-AA-FGvrRL70Yxz4McxTGUS-XCQRGZETCAnoImwVG8fx7DCYwAliRJVh8eJonSSJ8TybJbCcQR8q6I8ABWwC2Es9AADrQPQuxqWK5Amlm2awPRllWbAV43neD4aPRnB2eeJESJJ_gHO5ZCzLk0jfn5JDAPk4ykAA6qOwYaG4ACs9hcambbual2bpW6mXytlhz6GKXDfIcnYSKy3Q9IADqaAHbG_RSDIxFiqy1WAJ4ZgBY_9SgAK6oA4Bb0t16iAOSagDwOvlOJ6uoABs6gTmq_QjTExD6IVQA)

**Comment by helgasoft** [comment]
API does not support _style.rich_. But [style.overflow](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_text.style.overflow) works - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMhgE4QDmZApsYQOQCGAHhAM62wC-ANGrNpVWgATQkm69GAQWYtRsALZNCAJk490AT2ms5ixoQCca3i2oRKs2AG1e6VOgcYNISnQDGAVxaZ5tdY9hiSmFqAEkwSnlCADMPaDdIGFgAChB6Ynp5Fi5YehAIAEpkWwCAN3TYRgA1emwPSgRc_IA6crrKZIAGAoBuEsdy4lgNGvbGvIhW2vrkgEZe_odB2BYIAC8GxAmp9uTlBYClircsYiEWcZaT4DPkq2rpyhyRx4BdBcX0ILAPYjh7Q4OMDOVywWhkYjADwgPyfBz6WDXM4sKydV7-QHDQhI85WWbouHoNwACwg2CEQWghBsmMcANpQJBdCCCVhDMcLGJeVB9PZ6AA7hAhGBiYRVhsMXzYMTKORiWAxetKISAuIpStgfxRCrDtEydhmWQAEb0LpcTrm83NADsBVoOocHAdavZvIZwJcdAijDAbKl3rAAGEYHqyHIQMBVokqWCINBVkJKAAVUAAGUo0V9xnV3g0WuK6oFQpFKk6FodjmApWo0WwwH5dCNQXoAGs_eq9dgDWCNJQu_X21LsHHKAAJWVkeUqAAskr50RgYAAykrCLMABxz9kB6kVgK0JuUVuH4_Nlsn89ni_Xs-D9W0SIgLmrUzyJ_0F-P5-sL8fn9v79X3fF97ULWBXmaAArYA42SWgAB1oEQ2gCj3J0-XQ2lXjhDg-kOF1HCEegwHoak8RyAA2HJlDLV5sMcTDsNwoA)
![image](https://github.com/apache/echarts/assets/13038071/f92b87fe-a033-4c89-82f8-cb32c7877c9a)

**Comment by Fnxxxxo** [comment]
@helgasoft So emphasis is not supported？

**Comment by helgasoft** [comment]
oops - _style.rich_ is supported, but is missing from the [API](https://echarts.apache.org/en/option.html#series-custom.renderItem.return_text.style) - a documentation bug.
emphasis is also supported - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMhgE4QDmZApsYQOQRiUC2tsAvgDRqzaVXQATQkk7cAHgEExEAM7DYTAIZjCARnZd0ATymz5SlbACcG7jOoRKc2AG1u6VOicYtISnQDGAVxmYWm51hiSkFqAElGJkIAMy9oD0gYWAAKEEViRSYZDlhFEAgASmR7QIA3dNgxADVFbC9KBFz8gDpyuspkgAYCgG4S53LiWC0a9sa8iFba-uTVXv6nQdgZCAAvBsQJqfbkgCZ5wMWKjyxiARlxlpPgM-SbaunKHJHHgF15hfRgsC9iOEdDk4wK53LBaGRiMAvCBaAFAZVCNczjIbJ1XnDAVpEadzjZVOjPk4PAALCDYATBaCEGwA-HOYFuOjBBKwwmHGTEvKgpCwADuEAEYGJhBW6xyxMo5GJYBFawaojpgV8Wl48miZOwdAhlBCrAViqBlDEYAAwjBGNAZUQ2YDlarrQbAfzBcLlnKALSqToYx3oYClajRbDAXl0ABGwUUAGtWb7AqQScJojJdp0k-aAMpywiptj6uPoRjG6k2xW0JDJ1MAHwjlGjtfrkajDebTZb7abbFjBectH5QtgzBAnJWFyHI9kzXHilH09nTGHM9kc9ktFLgNezQAVsAINBkrQADrQY-0Arr5xsC-mONF00wdVkeQgYArRJUsF7lYCSgAFVAAAylDRGAeo-nSK7WDydrcrA6rYJqYLBAIersDabCvISbB9Ic-ZOAIihgIo1Kos0ADMOQAGw5KmaKYZe3CYdhQA)
📌 please close issue if problem solved.

**Comment by Ovilia** [comment]
If there's some document missing, it would be very helpful to others if you make a pull request to [echarts-doc](https://github.com/apache/echarts-doc) to fix this.
