### ISSUE TITLE
It does not position the label correctly on waterfall chart when it crosses the X axis

### ISSUE THREAD

**Issue by lmarquinez** [apache/echarts#19724]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-waterfall

### Steps to Reproduce

Value that across the X axis.

### Current Behavior

I am using a bar chart, specifically the waterfall chart. I have added the option to display the labels and apparently it works fine.

The problem arises when I give it a position, such as top, and this bar crosses the X axis. In this case it does not position it correctly, since it seems that it understands that the value of this bar ends in the axis when really it is higher.

### Expected Behavior

To position it correctly, taking into account the whole bar and not up to the axis.

### Environment

```markdown
- OS:
- Browser: Chrome
- Framework: Angular 15
```

**Comment by MatthiasMert** [comment]
In the provided link i cannot see any issues.

**Comment by lmarquinez** [comment]
I had not added stackStrategy: 'all'

**Comment by lmarquinez** [comment]
I had not added stackStrategy: 'all'
