### ISSUE TITLE
[Bug] How to implement an interval chart

### ISSUE THREAD

**Issue by Lazydd** [apache/echarts#19722]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-waterfall&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDqAhmDgE4BmtWWsAwgBa2NiUANEXQBnAK4AjBuSoAZCADcI0AOawAoqRA5oonKNgrYAZW66AXueiUiAX2HowwYFkggCqYhkYRVqpipaUghRIRFYYNCABWAVBkZPCKcATx0qUV4AE2AAd1tvBwjmYEYAW3oEgmZxaABjSBhYAAoQPloy0QBKQm90RT4MQcQ2xg7RAG0ARgBdAG5k2EYcMHFGODA-ADpoDpxYAGpYSgAeSUYAegA-SkOhxi39XwMAOT2726o7zYeBrHEcAtCvZHLBVL4sklvLhmBRjgBmACk4W8vlU3DhlAALMjQehJMAwM4ylQkSjiHUYJsVHJaJIcFgCGBGACQURSABBEKiKHEMBpfDHOr0HCqUopcliEBYCBgBTQQVIWCZPLVNj6WBFbxZei0AgTSgAFUJbCExwASroBIJjgBVSAyyAGM1GsZ6EClTaNGw2ygAWRw6pdAHkwOZGJQZmz0CkuaFeal0sc_gCCprQU8IAZ9REvH1dmVBZRolhaHUcNxXFkmJK-QKqJI-LWxJs6gBrKjGzZYZtGBhlEz83AJvoExjVxicVylKjM2juvhW3voSlYGfHOcL5bQASLLV9HBlEC8UTx3p9dCyw-DlLD88X_GlCdTteJDdu0SjJd4h-r9eUTdP0XHc0wvOw9x_dAdU2fUpgABkEAAmBCAFp4KjQofzzbwCyLBRmH2KdRGtRZ-STShGwjSDlVbDtji7U1qNLelGXvPoVVyJkWRwaj0A9U9vSoFRT2rUDiH3bVdX1eEENgLEEPQiJwPQKM7DmIA

### Steps to Reproduce

open

### Current Behavior

If there are negative numbers, it still starts from 0

### Expected Behavior

Start from specified position
![image](https://github.com/apache/echarts/assets/71319962/57f15a1b-9f2c-4405-aef8-3885a37b593f)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
set [stackStrategy](https://echarts.apache.org/en/option.html#series-bar.stackStrategy) to `'all'`

**Comment by Lazydd** [comment]
> set [stackStrategy](https://echarts.apache.org/en/option.html#series-bar.stackStrategy) to `'all'`

This works
