### ISSUE TITLE
[Bug] map中国地图 右下角南海诸岛与中国最新地图展示有不同的地方

### ISSUE THREAD

**Issue by Ryemail** [apache/echarts#19725]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/zh/option.html#series-map

### Steps to Reproduce

map 地图南海诸岛与最新地图展示不一致

### Current Behavior

![WechatIMG489](https://github.com/apache/echarts/assets/33651645/71d8041c-22e7-4ae5-ab2b-534f6f52eb20)

### Expected Behavior

<img width="131" alt="image" src="https://github.com/apache/echarts/assets/33651645/1fa9092c-8a25-40c5-87d7-0d81d77399a5">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
ECharts 不提供地图数据，但在默认情况下，当用户 register 并使用了 `map: 'china'` 但 map 数据不包括 `'南海诸岛'` 时，ECharts 会自动注入内置的简版[南海诸岛](https://github.com/apache/echarts/blob/master/src/coord/geo/fix/nanhai.ts)（[钓鱼岛](https://github.com/apache/echarts/blob/master/src/coord/geo/fix/diaoyuIsland.ts)也是如此），以防止地图出现整体缺少的问题。如需精确展示，建议购买合规的详细地图数据后自行注册并使用。

**Comment by helgasoft** [comment]
duplicate of #17295, #16935 and others. Next time please [search issues](https://github.com/apache/echarts/issues?q=is%3Aissue+%22South+China+Sea%22) first.
📌 please close issue if problem solved.

**Comment by huhongliang** [comment]
我这边的数据是完整，全尺寸的地图可以显示岛屿，但是缩略图仍然不行，下面上图片，我们的客户是国企，搞不了缩略图只能上全尺寸
![1712732080827](https://github.com/apache/echarts/assets/28997491/70264cde-1c4c-4792-bc72-5c3cd8e8a99f)

**Comment by plainheart** [comment]
缩略图是内置的，如果已经是全图，可以将其移除。

**Comment by qZhiKing** [comment]
@plainheart 请问下怎么去隐藏这个南海诸岛

**Comment by forestwanglin** [comment]
> [@plainheart](https://github.com/plainheart) 请问下怎么去隐藏这个南海诸岛

register的时候不要取名china就不会自动显示了
