### ISSUE TITLE
[Bug] render is slow when yAxis.type=time and yAxis.max is less then the min of data

### ISSUE THREAD

**Issue by aHappySand** [apache/echarts#19739]
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple

### Steps to Reproduce

optoin = 
{
                    "title": [],
                    "tooltip": {
                        "show": "{A}:{V}"
                    },
                    "toolbox": {},
                    "xAxis": [
                        {
                            "type": "category",
                            "showRange": false,
                            "scale": true,
                            "inverse": false,
                            "axisLabel": {
                                "fontStyle": "normal",
                                "fontSize": 12,
                                "fontFamily": "Microsoft Yahei UI",
                                "fontWeight": "normal",
                                "fontColor": "#61646b",
                                "show": true,
                                "interval": "auto",
                                "rotate": 0,
                                "color": "#61646b",
                                "fontType": 1,
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": null,
                                "margin": 5,
                                "hideOverlap": true
                            },
                            "axisLine": {
                                "show": true,
                                "onZero": false,
                                "lineStyle": {
                                    "color": "#d1d4de"
                                }
                            },
                            "axisTick": {
                                "show": true,
                                "lineStyle": {
                                    "color": "#d1d4de"
                                }
                            },
                            "splitLine": {
                                "show": false,
                                "lineStyle": {
                                    "color": "#e8edf8"
                                }
                            },
                            "data": [
                                "SC3+SC1清洗",
                                "台阶测试",
                                "干法去胶",
                                "显影",
                                "显微镜检查",
                                "标记干法刻蚀",
                                "涂胶",
                                "湿法去胶",
                                "激光打标",
                                "甩干",
                                "目检",
                                "零层曝光"
                            ],
                            "labelHeight": 77.39999389648438,
                            "axisMultiLabel": {
                                "show": false,
                                "data": [
                                    {
                                        "rotate": 0,
                                        "rotation": 0,
                                        "sinValue": 0,
                                        "height": 16,
                                        "offset": 16
                                    }
                                ],
                                "height": 16,
                                "font": {
                                    "fontType": 1,
                                    "fontFamily": "Microsoft Yahei UI",
                                    "fontSize": 12,
                                    "fontWeight": "normal",
                                    "fontStyle": "normal",
                                    "horizontalAlignment": 0,
                                    "verticalAlignment": 1,
                                    "textWrapping": 1,
                                    "name": null
                                },
                                "categoryWidths": [
                                    77
                                ]
                            }
                        }
                    ],
                    "yAxis": [
                        {
                            splitNumber: 5,
                            "scale": true,
                            "show": true,
                            "showRange": false,
                            "type": "time",
                            "position": "left",
                            "name": null,
                            "nameLocation": "end",
                            "nameGap": 17,
                            "nameTextStyle": {
                                "verticalAlign": "top",
                                "color": "#333"
                            },
                            "axisLabel": {
                                "fontStyle": "normal",
                                "fontSize": 12,
                                "fontFamily": "Microsoft Yahei UI",
                                "fontWeight": "normal",
                                "fontColor": "#61646b",
                                "show": true,
                                "margin": 5,
                                "fontType": 2,
                                "textPattern": "{V:yyyy-MM-dd}",
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": null,
                                "hideOverlap": true,
                                "showMinLabel": false,
                                "showMaxLabel": true,
                                "width": 42,
                                "overflow": "truncate",
                                "color": "#61646b"
                            },
                            "axisLine": {
                                "show": true,
                                "onZero": false,
                                "lineStyle": {
                                    "color": "#d1d4de"
                                }
                            },
                            "axisTick": {
                                "show": true,
                                "lineStyle": {
                                    "color": "#d1d4de"
                                }
                            },
                            "splitLine": {
                                "show": true,
                                "lineStyle": {
                                    "color": "#e8edf8"
                                }
                            },
                            "max": "2023-03-20 00:00:00",
                            "min": null,
                            "title": "Move Out 时间",
                            "labelWidth": 50
                        }
                    ],
                    "series": [
                        {
                            "yAxisIndex": 0,
                            "name": "A0001#01",
                            "main": "Move Out 时间",
                            "type": "scatter",
                            "label": {
                                "fontType": 4,
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": "Move Out 时间",
                                "fontFamily": "Microsoft Yahei UI",
                                "fontSize": 12,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "show": false,
                                "color": "#333",
                                "rotate": 0,
                                "position": "top",
                                "distance": 2
                            },
                            "data": [
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "激光打标",
                                        "2023-11-26 13:15:18",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "目检",
                                        "2023-11-26 13:18:16",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "SC3+SC1清洗",
                                        "2023-11-26 14:58:39",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-26 15:11:59",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "涂胶",
                                        "2023-11-26 16:55:25",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "零层曝光",
                                        "2023-11-26 17:17:15",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显影",
                                        "2023-11-26 17:59:57",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-26 19:03:18",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "标记干法刻蚀",
                                        "2023-11-26 23:17:44",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-26 23:52:11",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "干法去胶",
                                        "2023-11-27 01:16:11",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "台阶测试",
                                        "2023-11-27 01:31:18",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "湿法去胶",
                                        "2023-11-27 02:50:55",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 03:00:32",
                                        null,
                                        null
                                    ],
                                }
                            ],
                            "zlevel": 1,
                            "itemStyle": {
                                "color": "#69a1ff",
                                "opacity": 1,
                                "hideColor": "rgb(225, 236, 255)"
                            },
                            "symbolSize": 10,
                            "progressive": 20000,
                            "progressiveThreshold": 40000,
                            "symbol": "circle",
                            "markLine": {
                                "silent": true,
                                "symbol": "none",
                                "data": [],
                                "animation": false
                            }
                        },
                        {
                            "yAxisIndex": 0,
                            "name": "A0001#02",
                            "main": "Move Out 时间",
                            "type": "scatter",
                            "label": {
                                "fontType": 4,
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": "Move Out 时间",
                                "fontFamily": "Microsoft Yahei UI",
                                "fontSize": 12,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "show": false,
                                "color": "#333",
                                "rotate": 0,
                                "position": "top",
                                "distance": 2
                            },
                            "data": [
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "激光打标",
                                        "2023-11-27 03:10:08",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "目检",
                                        "2023-11-27 03:19:45",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "SC3+SC1清洗",
                                        "2023-11-27 03:29:22",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 03:38:59",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "涂胶",
                                        "2023-11-27 03:48:36",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "零层曝光",
                                        "2023-11-27 03:58:13",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显影",
                                        "2023-11-27 04:07:50",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 04:17:27",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "标记干法刻蚀",
                                        "2023-11-27 04:27:04",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 04:36:41",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "干法去胶",
                                        "2023-11-27 04:46:18",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "台阶测试",
                                        "2023-11-27 04:55:55",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "湿法去胶",
                                        "2023-11-27 05:05:32",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 05:15:09",
                                        null,
                                        null
                                    ],

                                }
                            ],
                            "zlevel": 1,
                            "itemStyle": {
                                "color": "#f7b15a",
                                "opacity": 1,
                                "hideColor": "rgb(253, 239, 222)"
                            },
                            "symbolSize": 10,
                            "progressive": 20000,
                            "progressiveThreshold": 40000,
                            "symbol": "circle",
                            "markLine": {
                                "silent": true,
                                "symbol": "none",
                                "data": [],
                                "animation": false
                            }
                        },
                        {
                            "yAxisIndex": 0,
                            "name": "A0001#03",
                            "main": "Move Out 时间",
                            "type": "scatter",
                            "label": {
                                "fontType": 4,
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": "Move Out 时间",
                                "fontFamily": "Microsoft Yahei UI",
                                "fontSize": 12,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "show": false,
                                "color": "#333",
                                "rotate": 0,
                                "position": "top",
                                "distance": 2
                            },
                            "data": [
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "激光打标",
                                        "2023-11-27 05:24:46",
                                        null,
                                        null
                                    ],
                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "目检",
                                        "2023-11-27 05:34:23",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "SC3+SC1清洗",
                                        "2023-11-27 05:44:00",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 05:53:37",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "涂胶",
                                        "2023-11-27 06:03:14",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "零层曝光",
                                        "2023-11-27 06:12:51",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显影",
                                        "2023-11-27 06:22:28",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 06:32:05",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "标记干法刻蚀",
                                        "2023-11-27 06:41:42",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 06:51:19",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "干法去胶",
                                        "2023-11-27 07:00:56",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "台阶测试",
                                        "2023-11-27 07:10:33",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "湿法去胶",
                                        "2023-11-27 07:20:10",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 07:29:47",
                                        null,
                                        null
                                    ],

                                }
                            ],
                            "zlevel": 1,
                            "itemStyle": {
                                "color": "#4dd263",
                                "opacity": 1,
                                "hideColor": "rgb(219, 246, 224)"
                            },
                            "symbolSize": 10,
                            "progressive": 20000,
                            "progressiveThreshold": 40000,
                            "symbol": "circle",
                            "markLine": {
                                "silent": true,
                                "symbol": "none",
                                "data": [],
                                "animation": false
                            }
                        },
                        {
                            "yAxisIndex": 0,
                            "name": "A0001#04",
                            "main": "Move Out 时间",
                            "type": "scatter",
                            "label": {
                                "fontType": 4,
                                "horizontalAlignment": 0,
                                "verticalAlignment": 1,
                                "textWrapping": 1,
                                "name": "Move Out 时间",
                                "fontFamily": "Microsoft Yahei UI",
                                "fontSize": 12,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "show": false,
                                "color": "#333",
                                "rotate": 0,
                                "position": "top",
                                "distance": 2
                            },
                            "data": [
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "激光打标",
                                        "2023-11-27 07:39:24",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "目检",
                                        "2023-11-27 07:49:01",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "SC3+SC1清洗",
                                        "2023-11-27 07:58:38",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 08:08:15",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "涂胶",
                                        "2023-11-27 08:17:52",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "零层曝光",
                                        "2023-11-27 08:27:29",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显影",
                                        "2023-11-27 08:37:06",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 08:46:43",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "标记干法刻蚀",
                                        "2023-11-27 08:56:20",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "显微镜检查",
                                        "2023-11-27 09:05:57",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "干法去胶",
                                        "2023-11-27 09:15:34",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "台阶测试",
                                        "2023-11-27 09:25:11",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "湿法去胶",
                                        "2023-11-27 09:34:48",
                                        null,
                                        null
                                    ],

                                },
                                {
                                    "name": "Move Out 时间",
                                    "value": [
                                        "甩干",
                                        "2023-11-27 09:44:25",
                                        null,
                                        null
                                    ],
                                }
                            ],
                            "zlevel": 1,
                            "itemStyle": {
                                "color": "#fcf26b",
                                "opacity": 1,
                                "hideColor": "rgb(254, 252, 225)"
                            },
                            "symbolSize": 10,
                            "progressive": 20000,
                            "progressiveThreshold": 40000,
                            "symbol": "circle",
                            "markLine": {
                                "silent": true,
                                "symbol": "none",
                                "data": [],
                                "animation": false
                            }
                        },

                    ],
                    "textStyle": {
                        "fontStyle": "normal",
                        "fontSize": 12,
                        "fontFamily": "Microsoft Yahei UI,\"Helvetica Neue\",Helvetica,\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",\"微软雅黑\",Arial,sans-serif",
                        "fontWeight": "normal",
                        "fontColor": "#61646b"
                    },
                    "grid": {
                        "top": 7.199999999999999,
                        "bottom": 77.39999389648438,
                        "left": 50,
                        "right": 100
                    },
                    "dataZoom": [],
                    "animation": false
                }

### Current Behavior

render is slow
![scatter](https://github.com/apache/echarts/assets/12469251/6139ea4d-5ffa-42fa-9d67-83bffe73d743)

### Expected Behavior

render fast

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
maybe you just need _encode_ - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMrGAJ4gCmRA5JALYXWwC-ANGrKTvkUieVVjUAxgEMwFAObAATqSZtYAGykVoAEwJI2HPBRkQKhWAG0O6VOiuxoohjSwAGZwEYAxI5fV219HVEQ0DQAssAAbhSwAPIArmCwgG-mgC-p3uZWZJQ0eGJgEjKpvrBqwsDqgnwYRC6snESOLD6-6uKiRGaFFmmFtvZCoRHRcYkpjR2wYaJKMYIm1IAD9oCSioDKRoDgFt5CAEyOGwDMALQuLnsbAGywLjsELgCsVwAc69AxSko1Ty8Aul1WOmOWYzY7IJqP1IrF4skCgCJlMZtRAHdugAGLdbULa7A5HU7nS4uO5XE6PZ6vGxEr5jX4df5jHrA0GDCEjb7WGHTNrUADKAGEdgBqLkuQCgdoB0WxRaP2h2OZxcABYCNc8TsAJyEl5vUlMhoaqkdGkhcJgoaQ0YdFlwwCUroAnPVF23FmKlt0OcuVatVJM-GophW13SBeoG4OGULGprZgCDbQBvAdb0RKsS4TnLbhtririe8lGSOp7fN7fLq-vr6YHjYUQ6ZqIA3tMAQjqAXbMFlHbZLzgB2K4tm4pl3pj3Fqw56x5kEFgNGjXoUuzQB8ZoBHfXrGMbLhb10VcqbHbdXfJPc6AMBvUH_sNjJ34-oE8AdfqAHVTEYBT81nMaly8cOIenc7GcKWesfasA7pw6P0KTKyZYrIADdEWoAqzaANxKgABYXedqwLsrYENK0prmm76-J-vajrutJDoeQYmkBcLnlet41KiNpzliSHXBsVxeK-66YdY2HbgCv4EQyREliRbKQYA3cqRpRYo0U2sCePijHoeqm5arhXEHjxW5WCegAPyoAbGmANK2gCr0fBxwSVJOwuPcsnuvJfyKb6-bKUWuEnoA_nYQcJBkbEZDHXI4CbmRumaqd-6BKQaKkOfxZaWm5RmXM4BA7BsvmsT83wfD2ABeKgREoVQ9hAEh0OyZAqLwGolEosg0AARrC6wAPS1UIbgnIqoguAAZm1vFWKAojCHlpA5RqAAWEBlJywDlTINAyJIlUABQbEmNS7Ccy3XNcACU1DfNheCkHQlUTeyEBpYILiOD2e0HRNNB9TIwgqF1_gyAA1gAMoE5QangEAqNAYBEGAMjTKpV2HdlQjQDAjCqc0YCtKYqUaqI0AQP4kAwEQbWTHoO1pFmOZcLgeAAJIaBQlSST2A5OK4HgJT2_iBH6IX2YUGTAtk4h5F1xSlOUmA5bUkmaoUcMI-0lLWXuf6EapY7hbMiyrFFkk4t5jgvuub7dgpO7BYWI7HorCLIqJ1ExtFVzLtKybMRhutWfrNn7qzRuAbCbJcry_LCqrT4EBsy6LYljtS87MvcWzHvAbMkXm9GmJWzseJLqHlnh5xLuy6Fxue2WEb-5c0oKgS9tyf5etZ5Hdnu8GJtVrWRdyniFzp5XTvV_htcAfX-eTjOCcNu5kmyo4i6OO3H4BdL3du73xH96el43v7soLoHq7lxZHeZ9S2dR3Xi-x9QYGQbBa-bwQjhodvfnT1X-81_PXXMibZGr0P4mj3F8bSkx2sWJhy9LPFmhsF58SXkJESmwLZJx_tKeMuIp5YRnhHOe4DX5qRNlpPSl91o-TvkldA7FkCgNsi_eW4wTbOVcl_S2klbiOFuPFFBbE0FdzAf-LBCsl7x1gYnQyjCrhMOdIAh25IUrpUyhQCG1Rvh5QoAVIqX0xhlQqo1NqTZKo3FEFgnqfUyCDTGCNMaE0NHUBmvNJMOxlpKmWotLaO1Lr7XBsdU6VQLrfDBjdIQd0How2-M9d6n0SpjB-n9AGJBgYUFBq43x1AobQECWMcWbQkZjBRmjcQUAgiwGxkoXGH58bGkJtwUm5NKZeJ9HuWmngPA7CegEPJrtME9g5lkHIPMex8zKLwQW5wagDRFthNJphH46gPj3Hh1Cl7KzWPQ-BzDA6ykQWwn4HCn4YO4VQk8SJ_YsNlLsdZJDNmTOfm0sKS9vZ8k5IKEUiyhHLNQtfSeRDgHZnIa0nZVyT78KooIkeyzriXB2FvcRFcH6dy2VwuWvy4SF0eUC-MAcZQnNFnvc52y4V5xPo3OsSKjJIM8gAtMOsM4gPQbC3OMdSKDwEcPIlgcGIbC1mSoBFLPlUooZc3FpEV4UQZd_Rw8Z4rXzthCneULMU1OxTSvuJ8z7QTgoSySf9TLSgZpK--qCJmyupdHBV_LyL-3jNcUyLgxHsokbvSlnCeU_L5QJFyMCAWMski2WK1wy7auIRiu1MKHU4tpWyXB-lVXjyuN5HYjT3mcq_F8nOhrj5wloa6sSDDI1bCjei0hgU8IGqPpAv5VoI0tiDihcF1rIVYSkd8DKFAsrGN8Io5RpBipkLUeYqajVpTqHUKcWNGoDH9WbYUUxFBxqTWmrNBalrlqIIcdKJx0rrA-KUO4s61TfDrtuhAe6j1GaiFeh9ZJYSOgRLUFEoGINvrxIhok6GWCxkmAyR0LJ6NclYxxhQPG7C0hlOJmTMoVTqYuzqe4G-TTmZBvlekAQnTub6F5tAEofTiCU2qMLeooyWhtD1bmKZlD4Vsnmf7FsSoVm5rOfq2Dybi1wn2WWlCj5SVEnJbarl9rvnBqNV7bktz7nkZbnFNl7GOWcYTdynjcGGNsn-RmpZeJNYiOowR_sRHeUhoLumuBTzW6Li1dWqVuroVYsLRA3wJ58X-zxO5QOVrxM2tXVxwNMn6NWffvSt1wqFSep9cZnV_6zO0fc0WzzS8P6Cp85mvEiCUKxt9R8qT3Gk3hbfkvJVF8I2p3jFsNTIXCMXMddpycAr_aPluNcKtTma3BZlUVuVHmMsn2gRVkRcVb5JfjThaTaXLMtbhGG9rSYZJxsk711Lh8BvYKXmm9rOxVliddM50zDWNPFd4ym-TpahWZptkciVgW_XMDrYUBtTbBkKPyoVdtqiOjqJ7dQNwbVhBtVOJVfRIBeqjquyY0ak7u0zusdcaUa0NgOM2ttFz6B12bs8S466D7_GHqCcekJZ7O0Xt-lewGMS4lI5oEklJHQX1vsKB-nJmN8k_r_cldAXxmAAG4gA).
📌 please close issue if problem solved.

![line-simple](https://github.com/apache/echarts/assets/13038071/18bf491f-ce04-43de-96f5-ac6c545718f4)

**Comment by aHappySand** [comment]
we have to set min or max for filter the time， and the [DEMO](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMrGAJ4gCmRA5JALYXWwC-ANGrKTvkUieVVjUAxgEMwFAObAATqSZtYAGykVoAEwJI2HPBRkQKhWAG0O6VOiuxoohjSwAGZwEYAxI5fV219HVEQ0DQAssAAbhSwAPIArmCwgG-mgC-p3uZWZJQ0eGJgEjKpvrBqwsDqgnwYRC6snESOLD6-6uKiRGaFFmmFtvZCoRHRcYkpjR2wYaJKMYIm1IAD9oCSioDKRoDgFt5CAEyOGwDMALQuLnsbAGywLjsELgCsVwAc69AxSko1Ty8Aul1WOmOWYzY7IJqP1IrF4skCgCJlMZtRAHdugAGLdbULa7A5HU7nS4uO5XE6PZ6vGxEr5jX4df5jHrA0GDCEjb7WGHTNrUADKAGEdgBqLkuQCgdoB0WxRaP2h2OZxcABYCNc8TsAJyEl5vUlMhoaqkdGkhcJgoaQ0YdFlwwCUroAnPVF23FmKlt0OcuVatVJM-GophW13SBeoG4OGULGprZgCDbQBvAdb0RKsS4TnLbhtririe8lGSOp7fN7fLq-vr6YHjYUQ6ZqIA3tMAQjqAXbMFlHbZLzgB2K4tm4pl3pj3Fqw56x5kEFgNGjXoUuzQB8ZoBHfXrGMbLhb10VcqbHbdXfJPc6AMBvUH_sNjJ34-oE8AdfqAHVTEYBT81nMaly8cOIenc7GcKWesfasA7pw6P0KTKyZYrIADdEWoAqzaANxKgABYXedqwLsrYENK0prmm76-J-vajrutJDoeQYmkBcLnlet41KiNpzliSHXBsVxeK-66YdY2HbgCv4EQyREliRbKQYA3cqRpRYo0U2sCePijHoeqm5arhXEHjxW5WCegAPyoAbGmANK2gCr0fBxwSVJOwuPcsnuvJfyKb6-bKUWuEnoA_nYQcJBkbEZDHXI4CbmRumaqd-6BKQaKkOfxZaWm5RmXM4BA7BsvmsT83wfD2ABeKgREoVQ9hAEh0OyZAqLwGolEosg0AARrC6wAPS1UIbgnIqoguAAZm1vFWKAojCHlpA5RqAAWEBlJywDlTINAyJIlUABQbEmNS7Ccy3XNcACU1DfNheCkHQlUTeyEBpYILiOD2e0HRNNB9TIwgqF1_gyAA1gAMoE5QangEAqNAYBEGAMjTKpV2HdlQjQDAjCqc0YCtKYqUaqI0AQP4kAwEQbWTHoO1pFmOZcLgeAAJIaBQlSST2A5OK4HgJT2_iBH6IX2YUGTAtk4h5F1xSlOUmA5bUkmaoUcMI-0lLWXuf6EapY7hbMiyrFFkk4t5jgvuub7dgpO7BYWI7HorCLIqJ1ExtFVzLtKybMRhutWfrNn7qzRuAbCbJcry_LCqrT4EBsy6LYljtS87MvcWzHvAbMkXm9GmJWzseJLqHlnh5xLuy6Fxue2WEb-5c0oKgS9tyf5etZ5Hdnu8GJtVrWRdyniFzp5XTvV_htcAfX-eTjOCcNu5kmyo4i6OO3H4BdL3du73xH96el43v7soLoHq7lxZHeZ9S2dR3Xi-x9QYGQbBa-bwQjhodvfnT1X-81_PXXMibZGr0P4mj3F8bSkx2sWJhy9LPFmhsF58SXkJESmwLZJx_tKeMuIp5YRnhHOe4DX5qRNlpPSl91o-TvkldA7FkCgNsi_eW4wTbOVcl_S2klbiOFuPFFBbE0FdzAf-LBCsl7x1gYnQyjCrhMOdIAh25IUrpUyhQCG1Rvh5QoAVIqX0xhlQqo1NqTZKo3FEFgnqfUyCDTGCNMaE0NHUBmvNJMOxlpKmWotLaO1Lr7XBsdU6VQLrfDBjdIQd0How2-M9d6n0SpjB-n9AGJBgYUFBq43x1AobQECWMcWbQkZjBRmjcQUAgiwGxkoXGH58bGkJtwUm5NKZeJ9HuWmngPA7CegEPJrtME9g5lkHIPMex8zKLwQW5wagDRFthNJphH46gPj3Hh1Cl7KzWPQ-BzDA6ykQWwn4HCn4YO4VQk8SJ_YsNlLsdZJDNmTOfm0sKS9vZ8k5IKEUiyhHLNQtfSeRDgHZnIa0nZVyT78KooIkeyzriXB2FvcRFcH6dy2VwuWvy4SF0eUC-MAcZQnNFnvc52y4V5xPo3OsSKjJIM8gAtMOsM4gPQbC3OMdSKDwEcPIlgcGIbC1mSoBFLPlUooZc3FpEV4UQZd_Rw8Z4rXzthCneULMU1OxTSvuJ8z7QTgoSySf9TLSgZpK--qCJmyupdHBV_LyL-3jNcUyLgxHsokbvSlnCeU_L5QJFyMCAWMski2WK1wy7auIRiu1MKHU4tpWyXB-lVXjyuN5HYjT3mcq_F8nOhrj5wloa6sSDDI1bCjei0hgU8IGqPpAv5VoI0tiDihcF1rIVYSkd8DKFAsrGN8Io5RpBipkLUeYqajVpTqHUKcWNGoDH9WbYUUxFBxqTWmrNBalrlqIIcdKJx0rrA-KUO4s61TfDrtuhAe6j1GaiFeh9ZJYSOgRLUFEoGINvrxIhok6GWCxkmAyR0LJ6NclYxxhQPG7C0hlOJmTMoVTqYuzqe4G-TTmZBvlekAQnTub6F5tAEofTiCU2qMLeooyWhtD1bmKZlD4Vsnmf7FsSoVm5rOfq2Dybi1wn2WWlCj5SVEnJbarl9rvnBqNV7bktz7nkZbnFNl7GOWcYTdynjcGGNsn-RmpZeJNYiOowR_sRHeUhoLumuBTzW6Li1dWqVuroVYsLRA3wJ58X-zxO5QOVrxM2tXVxwNMn6NWffvSt1wqFSep9cZnV_6zO0fc0WzzS8P6Cp85mvEiCUKxt9R8qT3Gk3hbfkvJVF8I2p3jFsNTIXCMXMddpycAr_aPluNcKtTma3BZlUVuVHmMsn2gRVkRcVb5JfjThaTaXLMtbhGG9rSYZJxsk711Lh8BvYKXmm9rOxVliddM50zDWNPFd4ym-TpahWZptkciVgW_XMDrYUBtTbBkKPyoVdtqiOjqJ7dQNwbVhBtVOJVfRIBeqjquyY0ak7u0zusdcaUa0NgOM2ttFz6B12bs8S466D7_GHqCcekJZ7O0Xt-lewGMS4lI5oEklJHQX1vsKB-nJmN8k_r_cldAXxmAAG4gA) dose't set min or max，and the axis is inverse。if you insist no problem，I close the issue.

**Comment by aHappySand** [comment]
I've put a limit on min and max not to exceed the value range， thank you!
