### ISSUE TITLE
[Bug] 散点图覆盖地图时，使用dataset指定更新散点图数据失效

### ISSUE THREAD

**Issue by Fnxxxxo** [apache/echarts#19733]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykDkEccADkgFwD0_JqgBWSVIQQBjQvyhd8_XFDhR-UiESgIxE1gBoABADMAroSlx8Ew6VNIoAKXGFyhgN7VDh0JFiJNXEZsPCIyKi9DRg1_JAQYRmJ8JDhGGABZeTYALwgDQ3snFwjvVC4rGwBeD0jvYV4a7yafeQbWXINappgcYAbjKAAbJEYugF99LoA3ZNMhzK4Gz2bvbMHGKcZBhoAmSZXDBWjGPkMAbS7m9x8iBoBGI2AoAA9dgAZDCcum6-Bbwx2Dxar0MABYPmNvgBdfYrEYwfAnACShCCILe41h3mUqhGcAaFwOhFMg0GWJ-3284lMMCkjAJlJ-hkIUGA9MMrEADaaAMNd8lMhqZ2QBmCHkg7XFlstqAf0jAPOhfIF7LuosZ3glrPZrEASumAd1sFYNBQ0RZ8xSt1VKOYAMV0AwQH6w2GACsn0ZUO-kOaMK68MRp0JZsZaw2W3upu8ks1HVDhjgIC4mqeXE6B28PVZ_SGIyjCbakcZjGAXGgSGS6eGjCjOKgeJRaPubtNy2Tgc220MQqj2QaoKjwhrjHRUZjcbajGMxmicAAylIVKkYEnk1JUKgYAQWalJyAUvm2sIFwckCBgAAjVCDSf4bLsnZvCsqKvMPsDxn4VLAScx9ZLVWGJeDFdtAAxMebw7FAoGsIyXzJlEFioEE34wd4gwkG0KHEPuyaDCoaEqJhBz8gamqEYKkEwe6KwUd4rreGMNDeL40DwMgzAAPLlNYhCkGUFSuPRhh4gAKvgbKoKYLBmBYvEUI0TSMf4LFwOx0mNs0lZ4gyMGqcm1K0uy2kwQQbKEMWEi-qw6H5BZeFGKwJGMKwnpIU0ul0ppzlNGcdyAggoIAOxGEKdwIDs7aGMqbxOR53heXcABsvlAkKACcCDJUYN6RT-1E_lRlHQuMJQmgCbylREYxUEAA

### Steps to Reproduce

1. 设置地图和geo配置
2. 基于该地图，添加散点图覆盖物
3. 配置dataset和映射encode
4. 延迟更新dataset的散点图数据

### Current Behavior

仅地图数据保留，散点图数据未渲染

### Expected Behavior

地图数据和散点图数据均得到渲染

### Environment

```markdown
- OS: win11
- Browser: Chrome 120.0.6099.130
- Framework: TS 4.9.0
```

**Comment by helgasoft** [comment]
incorrect definition of dataset in setTimeout. Try [this code](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbA5BHHAA5IAXAHphAY1yEEAKyS5GAG3wA3GAkLNhxCMIWoS6VEnz6tjVLP0BaYFD5WxEIlAACtpHEYxxTwlBlI-pwANOxsAGYAroRicCaEbKSRSFAAUoGE5GwA3mEcoJCwiE7y2HhEZFR5bIyORUgIMIzE-B5eALJ2pJwAXhAhbMlpGVUcHKh8cfpsALw51RxMqILzY2tstnwrvf2h62MwOMAr4VAKSIwLbAC-e-vKrZFnnVur-2w9CozKiisATHd9nx8LVGEI2ABtK5rbIbIgrACMwQ2UAAHv8AAw3QHvWHAeFsP5IlHotgAFix12hbAAuji1hcYCCkABJQjyUkYq63K64KBwKAXOArKHvNiESIKBT0sa5MUcQKRGBiRgi6kw8VQYCqriABtNAGGuA2UZ0iOoAzJSZftYX5tdtAP6RgHnQo0mnUIy3q2Wau1cQBK6YB3WxdClNKwt2M9HBtWp1nEAGK6AYICgyG2ABWG6emnUqn7OlXRnMtViuXyz7fX5sJGe20xvohT1wEB8GObOvytiHLUnM4XK1jTbbWu9jiMYB8aDGcGnc6MIdsPkCoVsjmIrO94ti0s_BSh2c9FZk2dLJeMTmzhtN7aMcLhWpwADKYn5nhgrflYlQqBgBD8njvIDaxxcEsr5ikgIDAAARqgCh3vgPQ6n8GKzvOgrMMep6evgnjAHeDZfCs65vtBn7bAAxBBGJ_FAlGcJ6PJtowMSoPIBERmwCgkNsHHECB8oKPyXH8rxYrGsGMaiaatFttm7wyWsmZrNcNBrAU0DwMgzAAPKTPEpATFMmQ0NUQoACr4NqqCRCwUQxAZiRZIR-TgGpiBCtpBmkI5YwoUKhbyl5-wENqhDGPo4IQpw3EDJFQnIpwEmMJwuZtgqlnKjqoopRwEIIkSCBkgA7MiZoIggfxmsi7oYslWWQgiCIAGz5cSZoAJwIK1yKIdVbEKfKcnrH1imjGMtyEhiE0jVSVBAA).

**Comment by Fnxxxxo** [comment]
@helgasoft Thanks for your reply. This is not my case. The bug is about the data merge. When I set `datasetIndex: 0` for the effectScatter graph and `datasetIndex: 1` for the geo map, provide only one of them in setTimeout cannot append new data in the previous graph.

**Comment by helgasoft** [comment]
_This is not my case_ !? ... well, it is not my case either. I fixed **your** code to correctly merge the scatter dataset. 
Is there another problem ?

**Comment by Fnxxxxo** [comment]
@helgasoft Sorry for not make it clear. I means the use case. In the issue. I want to init the map with visual map data. Then merge the data with new scatter data. It seems both my code and yours are not work. So I think it is a bug.

**Comment by helgasoft** [comment]
sorry, but I still do not understand what "does not work"...
Here is a map and scatter, both with visualMaps and datasets. Updating both successfully - [Demo](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbA5BHHAA5IAXAHphAY1yEEAKyS5GAG3wA3GAkLNhxCMIWoS6VEnz6tjVLP0BaYFD5WxEIlAACtpHEYxxTwlBlI-pwANOxsAGYAroRicCaEbKRgAHLA5GwA3mEcoJCwiE7y2HhEZFTZbIyO-UgIMIzE-B5eALJ2pJwAXhAhbClpNBwcqHxx-mwAvJkVHEyogtNDS2y2fAtdPaHLQzA4wAvhUApIjDNsAL5by8pNkUdta2wA2mccWdtLBMCMhMb6CwBGK4fNgnGD4RhIACShHkAA8FgAGYEfPgQsSQhYvEFLDIrIiA4IrKAItgAJmRbDEqD0MHWfEiMD4CkYnAuKJBeOABPJQOJpIALJTqbT1iBFHp0Gzzq8hgBdImyjgs8JwQSccHaOC9TxwtVPTirEKcTgK0FoLBQABGikEcBgkVOIMusveOK-Pz-hAWZI5yzBEOhsMYpKBSrYaKqmOe4be-O9bD5tlJFKJItQdK4xHqP2lfu2XJ5ZKTJIWQrTNIz63quGl4YVsd1-s4fFQRDgSGNpqJKAwmGttvtjtlMu2De2uCgcCgJzVMZBhEiCgU-cWOMCjIxWNjmTYfm-60A_pGAedDAFeBgG6bQBcyr1lEdHYDEeyd3j94x1oAldMA7raAQHcb3e34mj4ujiQwvlAB5cIAjjqADhyv5EreCj3mwADMQGrhwcojmc47-l4gbbpy4avus3QhOGcAgHwAGGnYZEgbs4EHEcJzocSjwbHROKMMAfDQMYQgRMxjCsZO06zjC8KAiOq5uiCcwSSGSKsRRVHrIw4ThFUcAAMpiFOngwJxILUhmBB-J42kgM0-xZuYRkfEgIDAFaNLafgnQAam4Y_NS8gLLJOIKCQ6xBcQ9kggoU4hVO4UfAhSGcPFrLhqOHypUsmFLOcgxDLk0DwMgzAAPKjPEpAjGMhDlBUs4ACr4N8qCRCwUQxJViTpAFOTgPliCziVlWkF1QyiTOzAETiw0Tg1nrxAJBqhb0nCRdqRKJf-3Y7huMBbvOIFDE8ALFggAoAOxEshAIIGSyFEgCiI4ftzwAgCABsJ18shACcCBfRdD07plOLAZNW1NTtAHYk9u7EVwJ4Xte8H_gsqFPtDMPgdRX5wWwSUPmj0NgRBnAwTjeMoWhO5xrDnCAJHagC9-mTyNsAArBcgMpbKQNZeUWV3S9AK8-zVBAA).
![image](https://github.com/apache/echarts/assets/13038071/f01f5e93-66d9-407b-8677-ff55c88f1cc4)

**Comment by Fnxxxxo** [comment]
I close this issue. The dataset cannot be partially updated. I find it should be updated with full dataset.
