### ISSUE TITLE
[Bug] Support on CSS Variables for color property on charts

### ISSUE THREAD

**Issue by mariafurtadobravo** [apache/echarts#19743]
### Version

5.5.0

### Link to Minimal Reproduction

https://codepen.io/mariahquery/pen/mdgWjgv

### Steps to Reproduce

1. Simple Bar Chart with color defined with css variable 
2. The color prop is defined with a css variable because we want to use with design tokens. Eg.: color: ['var(--kds-sys-color-chart-brand)']. 
3. When you hover over each bar on the chart, each bar disappears instead of remain the same color and increase its brightness to perform the expected hover Apache Echarts behaviour.

### Current Behavior

When you hover over each bar on the chart, each bar disappears.

### Expected Behavior

When you hover over each bar on the chart, each bar should remain the same color and increase its brightness to perform the expected hover Apache Echarts behaviour.

### Environment

```markdown
- OS: macOS Sonoma 14.3.1
- Browser: Chrome Version 122.0.6261.129 (Official Build) (arm64)
- Framework: No framework, just plain Vanilla JS
```

**Comment by plainheart** [comment]
This feature won't be added since Canvas doesn't recognize the CSS variables currently. It's suggested to use `window.getComputedStyle(DOM).getPropertyValue('--the-css-var')` to get real color values before calling `setOption`.

**Comment by mariafurtadobravo** [comment]
> This feature won't be added since Canvas doesn't recognize the CSS variables currently. It's suggested to use `window.getComputedStyle(DOM).getPropertyValue('--the-css-var')` to get real color values before calling `setOption`.

I'm using SVG rendering instead of Canvas, so it should work, right? 
The CSS Variable used on the color property by default is rendering correctly but **when you hover, it glitches**.
So I would say that **the bug is when we hover the chart, the color prop doesn't work correctly**

**Comment by plainheart** [comment]
> I'm using SVG rendering instead of Canvas, so it should work, right?

Usually a new added feature should work with both SVG renderer and Canvas renderer.

> The CSS Variable used on the color property by default is rendering correctly but when you hover, it glitches

This is because the highlighted color is calculated from the color in normal state, if the color is a css varaible, ECharts will not be able to parse it and get the highlighted color. To circumvent this, you may try to set the emphasis color explicitly.

Anyway, I think it's easy enough to get the real values of the CSS variables without the built-in support from ECharts.

**Comment by mariafurtadobravo** [comment]
> > I'm using SVG rendering instead of Canvas, so it should work, right?
> 
> Usually a new added feature should work with both SVG renderer and Canvas renderer.
> 
> > The CSS Variable used on the color property by default is rendering correctly but when you hover, it glitches
> 
> This is because the highlighted color is calculated from the color in normal state, if the color is a css varaible, ECharts will not be able to parse it and get the highlighted color. To circumvent this, you may try to set the emphasis color explicitly.
> 
> Anyway, I think it's easy enough to get the real values of the CSS variables without the built-in support from ECharts.

I already tried setting the
