### ISSUE TITLE
[Bug] Icon base 64 background image in label no work

### ISSUE THREAD

**Issue by electroheadfx** [apache/echarts#19746]
### Version

5.5.0

### Link to Minimal Reproduction

[sandbox exemple](https://codesandbox.io/p/sandbox/line-chart-in-cartesian-coordinate-system-33pnfn?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2lyeym00063b6f65dr3pjj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2lyeyl00023b6fh438jkm5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2lyeym00033b6fj8u0rfjr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2lyeym00053b6fx298cwrl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2lyeyl00023b6fh438jkm5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2lyeyl00013b6frg3x0bqr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clu2lyeyl00023b6fh438jkm5%2522%252C%2522activeTabId%2522%253A%2522clu2lyeyl00013b6frg3x0bqr%2522%257D%252C%2522clu2lyeym00053b6fx298cwrl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2lyeym00043b6fu0n5lxv6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2lyeym00053b6fx298cwrl%2522%252C%2522activeTabId%2522%253A%2522clu2lyeym00043b6fu0n5lxv6%2522%257D%252C%2522clu2lyeym00033b6fj8u0rfjr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2lyeym00033b6fj8u0rfjr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

Just try to add base64 image to markLine's label background, it doesn't work. only the text label show ('ADV 2')
It works  only with color and direct image URL

Here a direct link to echarts player:
[echarts background label test](https://echarts.apache.org/examples/en/editor.html?c=line-in-cartesian-coordinate-system&code=G4QwTgBGCuB2DOEC8EBMAoUkC2BTE80YuiKGWEAlgMYD2sAQmJQCYDmuyEA5JdiBwBcAemEsQAFxCC-A3MIAOsNgG4ARgVwA2ACwAaSgDUGAeQBKAdwAMAaQDibWgEEXTgHIBlAKoALAKJebK4AwgCark7YwU7hLsG0AAq42NARwQAaDACSAOrpALKu8AAqrgAyfhZ-kQoWsa7pnmZWWU5g8DrUWgCKEWaw3V4AjAxxAB4AVhbAAByhg64ePt5mDIYAEmwMAF6GPizFAGJjh4cAIjrbwXYAzN1uDPC0DACOflYSOtgA1IcMbt1QkMAFIvKwAGysxSsPWAUg8EhsAE9DB4ssCyjpQrQzsMAJxgJFqNj5b60KxsABmwQA1oYyjMnKhDMDKDoEkMFN8XndKQo2ABWMBWUIvdIsABaWXS1D8CWgNx86wkWm2ElQLCReO2ZWEYDKZQk4JmSNQxWg23y22AlNgE1g2xu6RMJjYwSGbDxAoA7MCaWVUCYwN0_dVDmpuuwGN0GIdpj4zOS1G5gTcBTSsnjYEjDtTQh50jd6ME2IZggKzsAzPk7KFgi8vuthKEzt0zuE7IcnBLih4GEixcDcGYcjZtmdtnYWAx0vAzC87JQ1AknOwzmBwTlUGcfCY_J3vgKrJOvCBUMCcqFgOkhjSrBLgjonBY8RIiBMFRLDBYFOszhMWDOHJDCpNxvgsEwLBYGZvm2bYfB8AD0i8NxhGAWAbnWShtmoCQTDOEBikwnQBQkeBwQlGYxgSeA2kObA8WwciBUOUI1FwBI_BALxumoKwQBuLwzCcYpcG9G4rDMG4JlQAVtiRHIPDOLQQGgbB1gYHxvmCNRqGBeAshAMprjYCVhFgEwXhAGYfHSVAshMGwzGAOxDAlPFgUpM5ihbdZUDxMorD8MY7AYG5vWCbYdAldJgAYUIvFCw48RuLJ4EpWMkS4iQJGwM5KDsYIzks7YhhAEBlDAMwJW2HIvEiJEhh0X4BQmYR0g8GlKXyXibjGGxUAmSkvBmNQhnyYQJnyVBvhpNRgQ8ExYBpXBgGgaALDMYQaR8JFwVCAV1hMYAtAuWA8W6dIaS0NwZjALxsCRBRvQ8d0ZhYeB1lgagZnql5wTKBgFGgdFvAYM51gFbBsw3GY6soNxtisQwhmCPEzBAKwbjOBRutwUJsz8Ng3EoCQGAkWAzBYQwsm9F5KAUANKaRYBgWoMpDgSKx4AFYItDGCRulob0GGCcEwBmYclyGGydDKCSsiGIY3BuBg8QsSgQD8CRtn-4BtjYbZ4HC4odC8HIyjcEAckpBJKQtBRqEDGYhjxYDqAsLQEi0CSWDALIrGgLxgTGVAEeGdJsGBQw3G9CYzgFMYrG-bjyx0Mw3HgUIbkpPEJT8CYvGAM4ziBnxgGwLqnGBJwRWgYAygFBRaFwHR0gUeqtBeYQbe-bocm-BubFoaBaBMAs2DJoYcngb16pYBIS0pNRYFgXBKQCMwsloHw1GCNwzmodI7G2MZPo8bYojYGwLB8CUc_q2O3FkvyWHWGkbmKeBPVwSgfAzP-QwEhnAkOsCUZwLDgj8FkLQ-R0i0BsCAboMCwpIjKBuUQ4YFBZDAMIMYbAzgSmgGoaA3wFAvEMGcb0SN4C3AkBYLwNJDjelwLQLIahKSUnoHYHahhYBqFoEpcE6w-pjBeGUHIHxox4mKN6dIlJrbCEOJ6WgbhwRsGNmwIY-14DRHSI4Fg1AWChDsBMMweIZjQFwAoLQwRlE2DGOkYI_USxgFgEMagwQEiHBsBNGwuAfDehpEMMYfgFB-GKD4HI2BtioGgFoHI-RKRgDUCwbANgcg0jMNQOw2B0iHGKL8b4IMnA2GpjSdYpQrJ4mgN0Fe_ZQgKGwH4NwJhKDgxpAoOMZQWC4GVFYb0dgZiqO2JQXEPgnD0GBNsYouQYrAlPF4NQ6wnAzASMAMAAp3FOGgDMQ4AoQChHSakKwvE2DYDAH4YIM8QoSlwGMMW3wF5qCRBIWgxQchnB0krCUdg46hTsOsQw6SWByRuH4GktT0ktJsBKdU4JigSGAJ1SkNhwTUFwGoGwNxDAJG9IYJJ2wPBgGBBIfiOgFE5GEF5YQZhDrehAGcHxLAG6UFgJjFSHg2CyPWN0E0lBgB-G9KEag4IzjT0pItXa-RwTAhANQeAChujQBeO4Q4ExvisNCLmLQ5xhBaEpBMfaYhUBOQlD4SawBKD5H2MCIY4UFAQNQC8aAQx6rbFCFCYQOgZh2FwFkMYYwak0j8GUeAOQ1DenYiwGkwgVZuDMD4Lw8BlGHG9ZQAc1AwAMA8B4NNTh7bHhAN8BgsA_T-NoN0eA1B-GaWoPaHIJgFBDGgOkQWFhDC0HWGMYoNbVIMAlPkfI9CxhDCyIcHIdgQDABsJ2nIOhsxDDODMJisALBuFoNgDwsjDBqByHtZSIAGbAiRFk4o4IFDgjbJsSgqB0g4ysII-A11Ob5HWDkLInR8i0C8MEG44IuxOCyAKceTVgCoG2KPMwpptgJHWNQLIPEaRjE2OsYEGNQjwBjIYMmwQFDwHyAoIkYAbDdAFGUSgwgLBEomDBJGhw-buNlAwHQZx-hIgSD4WA6QshuFwIyCI3hDDmBsLzUIWQshIG4JgcAVA6CwFXMALgvB-BCFEOIKQMhVPyCUKoDQ8BtD6CMKYSwtgHDOFcJ4XwAQghxHqJEaI9R4hJBSGkTIuQChFFKC4CoVQah1AiE4RoHhmitHaJ0HofQBjDFGE4ZxUxZjzHqi4PsKw1ibAYGMPYbgjhZfOOJboKQcZNKcHYM4iH8jBKsF4AUtAdAgGQzYaA25qBuDKC8M4xgfyUAsE5MYwI2DiZMDcDwChbiUBpGwNQoRoB-D8GYQ4tBG1lC1moLwToJjwDKGcF49MPA5GBMAHQNIEj0ysDSJEZwdo5B8FIMoEx4PfC0DMPEcdgAsDqfIBIEoyhtq0N6PEeIsZeh1nBG4Oc_AsCcH4dIEwxg5ged6HIDBqBsBMGMZ8Zw2Dju6AEPwlIhgeFoH4G43iwAQZaWYSgEwQBjDcGALQ3xXwWG6IcIWkY7BpQkGYFbqB1gWBmNGHwjIxHPhyKGygApuj5G9IRm4wI8SHAQgkNgPhDhgAuFoFgJwnBnDbaOMwOgchFTsHiFOZxYAzFgKxvESIPlLsuqgMYIAdDILxGfUQFhXcJGo9AcE_BTfAB8GUCUEw_A5E9HdSDoQncSASKEIFwB9X7NnKgUnTd1iRoFDG8H0YVpmDg3kCQagygeC0EiHw68RXby0GoYFO8nDC_yMAJw1ptfCCGJQLIqwtC0G1YYUaG10hWCXIUHIThgC0EwkRvE1y7ByppjYBQZLUA0m9GwawbBGVOC0HiUpEoaDfB8EMOwYwBTuSV2YT1LCzAeGoN6AtWGQC0DACYFglBtuTyNDYGYWgQ03FwGgDYHWEKjcUYVIReCRHSElw42wHj3IUMyRAAOoGECnBeBmARQlA8GBGWgYFMmAAsHtSRG6AsCdieTGDAHww8hmHXS1BMDxBYAeielGwImEFwDNGKR0DYC-AsCRH9QUFCBJmEgmGBGEAlAUBmBeAFFtlgCyG2HlVVHeC8DAB0DxFWlwG6DhxpAMkoHWBbWmRVAWWwAlEOjYGgDOCRAKhMGBAYG9H6znlVW6B0BbUBgUG0D7ngB2GwC8HiQkAJ1oFQGCBMDsA8HBCTjTAsFtim2MHgBYDKyRAmBMF-isCsDUW-FjgrzGB8DGF2RuFwW-ApFgBiNwGVisEB29GoHWw8BAFwGCGBEOHRBYAsALXyBmBmB0mBD_WhFwFfB8CyFCAZ0MAmD73yHrDmm9BoHlXWHkKGHWFoE1BwTcF3y0B-BpAKIIMMGoBxWAG6ANh2l4x8VCAkDACwJpApR62oHgx8BjBmG53lRuGoB8CnxYCsAXmgGKC0AtWwGVWt0iR5mEFoAkOAAe1PTAG2AYFoBmB-hjQjVQC8ALh4ScGEGBCCS0BmwSCX0pB8B0BYAKLGEpFCDMDCBMCRBsAmUoEoByAU2wEdjuCOjMBsC7nCTKEnBuG2C8FgEuUMHA2BHyXSBsIlGBCyA8CGBsB9QYGKFaP9jcAFC8AlBFRpFCAcRMEOEoDMBpnyByDuG9EpBeF4irAGyzSRG2G-GoB5A8BmFklnVPWBFCEMGEFiWxWAHBHgDACkJmBAhdJpByHBAsHJHESRG9CsGojsHBCiUjFCAYC8DxEpGEB8DsA6zGEaX8HyHgGwFMnXTjBsBjOVCRC0DYDJDUR8AYGgGEloDwjWzp2KFsPSBJ2XDODUgSFGSWLYByFqNajMCGGFlKzgOwFuHGj_wV2-CLGCJb07KBlGL9SRAsASGpxMBaDCTxBsBeFoGEBMBpH9GXOgAFCREDIlGoAUCA2NIkAkI4mf1QGEFXG8BeAxFgBTAYAsDMheCyCNXSASFgErhAGA0OH20hh8CpHyGKBAELnWAqDUDfO6BMAFDcBlQFByGoBAFPW2GcErXagECNQiWEEXmpRTnSC0HBAFBxJ0EMDsH5jGDUGyIImQtwFwFjTOFIsIO6GCAkDMQSAdOiiGB8E4TsOMjADTR0D5zhFwHbGEACHpCTQLX_ngBeGzXzHSGWSyEih0AmCGEGlQBVwFGWHWEpFwC8AmDKBDg8HyDUDsDMC0AUBuDcFfFQGoAlBsBpGBC0C8G9BgRlOBGBB8HBFwDsBMGgDsC8FoE7WCAlGAu9DNEQ2mJlOKAUBlUkMhW3LYD2iyFgC0GBABiyCrRVXnyYv_WvmBAmFCGtAlEpD5yFh8CglCAmB8CsCRDYG6BsG-C8GSwmEoBmGKDAHjg7mfgFHApAB_OwAPgiXmyyEoCsBeA8ElQ8GgDaVu0oDUnAB_zlluGNKgOey8GEzCTgmgCKhmCoQSB0FMVg0oJYEPIiD8AA2KBpCmsK2CGCGk3QEBIkEoHoC4AAG90AIAIAMcxhKB4BBAIBXqABfPQD6iAJEJwH6v6gG4G0GjTTQCQf6gAbVBs-ves-vRqoBYH-qsBBoxs-vfzwAQGeoQCRu4AUBpG4D0B4FAHBCsUpp4FYHpu4AM2AFwGYAkCRG4AAF1ca8angiAMUkaUa8bEacaIAxaxbuBhNubea8aIBEb9A0AqbFapasgZbhbPqubhaYaMa0a8bWB_qhhZb0bklN0CIpADMJBkrekxhsbjbPrjiKp0oX9sB_q9a5aOa3D_rmaX8JBKaNb0b5NKRKA2A3aIACbcAib6BvbGaqaX9ekwBvaCBqBuAIBAaA706MbM6IAebQaDNmASAhaMbRAIBiQIBwQ2VOBhb3b0bPbcBvaK615_a5bG7cAEQ9p66AaA7PqNYWAJAfA7aM77aIB4AniLAPAkRsABFwR_qFEXTcBh7-AwB_RK63bu6IAKpZAnro6IA56DNh7PrW726vK165aMa6BwQX9vazh5iOBs1abcBm6z6e7WB-7DaD7a6npO7uBxBR7cAWBpNn6daz74BJ7p7vbqBKAwBRVH6P7QGp7aBwQPBsJO6hgcb17kgFAfACBfrT7n7w7fqQA1AvKsaIBjirF17gG5a4akb5bXqIA6B46kaxahgubgaAaGHaAmH5bFbWG06uac7h7s7PqqGIAS6CBLaIBddDA0Bq6A666G7K6n6Maj6OaT6u7n7e637xahHh7R7aBx6wHEHZ6QB57F7wAV6148G5bN7-Bt7YATGzH17VGO7rGz6FGeAngK6AGP7RGMb4Hp7kHthO6JI4GjHwREwpAJBO70Hn7wQiHcAZ6NH8H9GLB_ryGF7178bfqpBvpO6ABaIYAUD-z65ueAUmYm727AVgFgLy5Rs-rhMAOx6JxOngV6p6o0XAAAH2kbQEBvqblpLo0GoEmzABHlgBYHiEvtae4GIB8aydLvlVGfGcmcQavuSfwaoG03-poHoCYFYA4BKbTqOa0YHogFCYWcrxDtu3-ouc2eYEeLcefo6fUZrs2YUBABYHf2UCRsKeKZ0YBasC1s2ZEYWeEbxr8fRswewfKahreb5oQvUYyaOa4WoGgChuZrZsoBIAGbxvifYiSfhbltSfSZgEyc2chZUcruPs7qJbxtOf-uKYWc-ovvWe4GIbpqOfBazo_pofloWeRpBY2aFZHvCZ2fk0UyOZbupbUdpeZbPtZZmYImXoYAftxaFYZfOalYhe1YxuhZwbhflelbXhpaeZFZfr7rOaZfNblsVevosdVc5aNYhedZEd1cDq4bAFIcRtQCptYflcpbxrpefoCeMbk3oElddc4e4cRpuD9eBZBe5bxtzs2fXpTZdZ5dBq1sBpUHQHQEemCGwbAAkAADpLam17GAAKR64mgAShUCAA)

### Current Behavior

It show transparent instead to render the base64 image

### Expected Behavior

It should show the same image there is in symbols from Label

### Environment

```markdown
- OS: mac
- Browser: arc, safari
- Framework: echarts player
```

**Comment by helgasoft** [comment]
remove _image://_ from iconBridge 
![image](https://github.com/apache/echarts/assets/13038071/24ffba6e-bb18-4d6f-9bd3-a70b4142f8f4)
📌 please close issue if problem solved.

**Comment by electroheadfx** [comment]
Merci Helgasoft, it works ! thanks
