### ISSUE TITLE
[Feature] add borderRadius option to sankey

### ISSUE THREAD

**Issue by jaipaljadeja** [apache/echarts#19750]
### What problem does this feature solve?

Considering this Basic Sankey [Example](https://echarts.apache.org/examples/en/editor.html?c=sankey-simple)
I was thinking if somehow we can add border-radius to the nodes of sankey chart.

### What does the proposed API look like?

i think we can do `series-sankey.itemStyle.borderRadius`

**Comment by deftliang** [comment]
I also need this feature
