### ISSUE TITLE
[Bug] 如何获取图例正确的高度，使用itemheight和gap 算 会有偏差，有没有一种内置api方法

### ISSUE THREAD

**Issue by LBJDJW** [apache/echarts#19755]
### Version

5.0

### Link to Minimal Reproduction

如何获取图例正确的高度，使用itemheight和gap 算 会有偏差，有没有一种内置api方法

### Steps to Reproduce

如何获取图例正确的高度，使用itemheight和gap 算 会有偏差，有没有一种内置api方法[Bug] 

### Current Behavior

如何获取图例正确的高度，使用itemheight和gap 算 会有偏差，有没有一种内置api方法

### Expected Behavior

如何获取图例正确的高度，使用itemheight和gap 算 会有偏差，有没有一种内置api方法

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
暂无公开 API 获取，可参考如下使用私有 API 从 BoundingRect 中得到高度。[Demo](https://echarts.apache.org/examples/zh/editor.html?renderer=svg&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrAB4CC1EAziauumAJ4hYkDkAxgEMwuYACcOvSm1gFhgkgG1eAWRhTYvACoBXLBt4B1LAQNaAFjoMAxMRAMBlYY53ReAXSoUqHekxZU7Fw8mgBughh6vF7SsIxYdljMsIqByGno0IIAtiG8AKLZghAYUhmwnNx8GBDQ-rEycmAKKQCMAEwADOSwrQDM7T2tna1DfQAsPQCc3bDtfbPtw54ypFSepADcKCjZHADC5oJiYAB0MAAUvGL4BAkmGhcAlAgAfOno_DCMYJi4twAJLAQHDmX6IPBgAAy_0I-2A2RAMHwYCBILBz22n2-wGwpwwwBwF2weEIaNBYCe21IVJ2ADNXPxIDBYJCYaSCPDEcjoKjgRTnh9YF9oD9hQikXVeWo7hgELA9odjmdITKsBhnqdIVzJSiriTbrxadjRb8vtypWAAGoQLAAd3liqOJy1WGttrtAHk6TqeWA1RrzbrpcBZcbxabYDcmfKg36bfatWJgDoQK6wAAhFOEWo4ABKWCZmKoNzAOjEcGjZ3M_LB1KAA)

```js
function getLegendComponentHeight() {
  const componentModel = myChart.getModel().getComponent('legend');
  const componentView = myChart.getViewOfComponentModel(componentModel);
  const rect = componentView.group.getBoundingRect();
  return rect.height;
}
```

**Comment by LBJDJW** [comment]
不过第一次渲染是undefined 不知道会不会有什么影响

**Comment by plainheart** [comment]
应该不会有 undefined 吧？我测了下并未出现。
