### ISSUE TITLE
[Bug] echarts v5在Chrome87版本下不起作用

### ISSUE THREAD

**Issue by q869939686** [apache/echarts#19756]
### Version

5.4

### Link to Minimal Reproduction

[Bug] echarts v5在Chrome87版本下不起作用

### Steps to Reproduce

[Bug] echarts v5在Chrome87版本下不起作用

### Current Behavior

[Bug] echarts v5在Chrome87版本下不起作用

### Expected Behavior

[Bug] echarts v5支持的Chrome最低版本是多少？

### Environment

```markdown
- OS:
- Browser:
- Framework:
[Bug] echarts v5在Chrome87版本下不起作用
```

**Comment by plainheart** [comment]
能贴一下报错信息吗？
