### ISSUE TITLE
在线定制后怎么引入啊？

### ISSUE THREAD

**Issue by chergn** [apache/echarts#19758]
[在线定制](https://echarts.apache.org/zh/builder.html)的，下载完在vue项目中怎么引入呢？我这样引入都不对
![image](https://github.com/apache/echarts/assets/43592730/954cbf18-0af6-4e64-a101-e1974b506ea9)
![image](https://github.com/apache/echarts/assets/43592730/babc3a6e-bc45-44e6-9739-b2edd32e3db0)

**Comment by plainheart** [comment]
在线定制的为 UMD 模块，可以直接使用 script 引入。
