### ISSUE TITLE
[Bug] candlestick 成交量顏色顯示錯誤

### ISSUE THREAD

**Issue by s34631327** [apache/echarts#19753]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush

### Current Behavior

成交量顏色是根據漲跌來呈現,
但目前好像是根據陰陽線來呈現,
這是錯誤的,
我目前是還沒找到你們官網錯誤的範例,
但我自己試起來是這樣
![89](https://github.com/apache/echarts/assets/61456373/74263783-20be-4742-b014-db87c73c6e01)

如上圖
如以紅漲綠跌來說   (台灣股市紅黑K顏色恰好相反)
該圖成交量顏色應該為紅色
因為是上漲

### Expected Behavior

*****此範例為台灣股市   (台灣股市紅黑K顏色恰好相反)
![789](https://github.com/apache/echarts/assets/61456373/e9fb6888-4a8f-4727-9b6d-4df4c52f7c53)

由此可見2024/02/15 為黑K
但是是上漲的
所以成交量顏色為紅色
如是不漲不跌
則為灰色

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
> The chart’s volume color should be red. Because it is rising

Please search existing issues before submitting a new one.  This is a duplicate of #18467.
default candle colors are according to the western standard - rising is green, falling is red.
One can change them with [itemStyle](https://echarts.apache.org/en/option.html#series-candlestick.itemStyle.color0).
📌 please close issue if problem solved.

**Comment by s34631327** [comment]
我知道顏色可以更改,
也知道西方標準,
但我要反應的不是這個問題。

目前情況:
  成交量顏色等同K線顏色

應修改為:
  成交量顏色取決於漲或跌
  也就是說
  ***以紅漲黑跌為例***
  今日 close < 昨日close
  成交量顏色則為黑色
  
  今日 close > 昨日close
  成交量顏色則為紅色
  
  今日 close = 昨日close
  成交量顏色則為灰色

下圖
2024/02/15
是最好例子
![789](https://github.com/apache/echarts/assets/61456373/358de2d3-336a-4e97-b1f1-e41e8f3f2783)

**Comment by helgasoft** [comment]
ok, so you need customization of the volume bars colors. This is done by preprocessing the candlestick OHLC data and set whatever volume bar colors you like with [data.itemStyle.color](https://echarts.apache.org/en/option.html#series-bar.data.itemStyle.color).

**Comment by s34631327** [comment]
我知道顏色可以自訂,
但我不是要自定成交量顏色,

我要表達的是:
你們k線和成交量顏色會相同,
但實際上兩者可能不同,
這是否有地方可以更改兩者定義?

**Comment by s34631327** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=candlestick-brush

你們範例中
splitData()
有誤
錯誤:
    volumes.push([i, rawData[i][4], rawData[i][0] > rawData[i][1] ? 1 : -1]);

應改為:
  
if(i == 0)
	volumes.push([i, rawData[i][4], 0]);
else if( rawData[i-1][1] < rawData[i][1] )
	volumes.push([i, rawData[i][4], 1]);
else if( rawData[i-1][1] == rawData[i][1] )
	volumes.push([i, rawData[i][4], 0]);
else
	volumes.push([i, rawData[i][4], -1]);

visualMap中加入:

{
  value: 0,
  color: flatColor
},

並定義
const flatColor = '#5B5B5B';

以上
