### ISSUE TITLE
[Bug] make pie chart labels different in color

### ISSUE THREAD

**Issue by tokyohost** [apache/echarts#19762]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/QWQ-QAQ/pen/OJGjXQQ

### Steps to Reproduce

[Make pie chart labels different in color](https://codepen.io/QWQ-QAQ/pen/OJGjXQQ)

### Current Behavior

![image](https://github.com/apache/echarts/assets/36682592/eec4cb96-d41a-44ce-a864-dc97b06830b3)

### Expected Behavior

<img width="307" alt="1711507763420" src="https://github.com/apache/echarts/assets/36682592/cd958dec-0a25-488f-8189-1beaf3fc2c44">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

我通过rich 里的a，b 参数尝试控制不同的颜色，但是只会生效a 的，b部分的颜色一直跟着a走
```
textStyle: { // 字符串模板
          rich: {
            b: {
              align: 'left',
              // color: '#8D97A4',
              color: '1',
              width: 55,
              padding: [0, 8, 0, 0]
            },
            a: {
              align: 'left',
              color: 'rgb(128, 134, 149)',
              width: 130,
              padding: [0, 8, 0, 0]
            },

          }
        }
```

**Comment by MatthiasMert** [comment]
You can set the color in [legend data](https://echarts.apache.org/en/option.html#legend.data.textStyle.color) for each item individually.

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=G4QwTgBAJiAuIGcIF4IG0BQEIG8vYgDsQBbAUwC4IByQLS1BvzUDbtQWr1ACv0Ha_agGn21ABsArpQgBGAAw8CEMGQAOAezCwAKgE85ZAMIKoI6qO68ImsAGMyheAHMRAVgDMAOnH4AvlNzHi5KtUDdCYAziRxG0gLCVAAsntiyisrqmjp6fgBMoQSmFlYgtlSpqS7unnjSPvqAjjqA6eaA-OqADOohMRDhIqlNcUqqGtq6-gDsGdhZljYioqJF2B74pQTlfvWA_kaAoMqA836ApCGNxi357fKdiT0pNAAcgyZk5iO5YxOuUyXepPqAboqAa3JbYSBCY3vxXUlen4AJznYY5PIQABskwgbgwAF0ANwYDCgSBmBT8JQodD4agAYnE4mBABEAGLkjKEvqiABCJ3JAFFqQS-kymVCAIIOVmiYF0zl01mUrRQ8QDTyE8niE5M4msrSk4niFlSglMxzi8Qi8lc_ksxEotHgCD8Mi2QhQUlwEC4gDyACMAFZkMywJwAazIagQAAoYPAEABKJwkEByP0AM0EhHdAEsFIQIH741ayAAPYNeWJkWCCMDJ2bYebQW0INBpvQZhFOcpNWCZ2AAZVganNVBwEEx2LAVB7Skr6ZrcPcKLcweNCjksETydQswHfe7WKUnnNlqgneMSnjIz8wEus7M33OsGnfmyjbA53jmMIl_j5nNt8bJAA4hH8pJjPG3wB1eMoFgAALKgoSaQMQCoDdLGtW0mijJRw1ga8qBjONZyTFNymzYsCHNWAIAQWBIFQahqBRaRsEI5pvmEKjqKQyA_Vo-NcXEJEIHYgAeMsgycc1CGsUCuPjABqcS8OMaR4yjFMoIreNa3KFBkFQXCc2or4flxRTK1rFpGO07AAHpTOI0jcQAAxwEAAB8ABIcHKNw3FwR0nJwP0_RaCALO-fgADlBBIbMACoxGJUNz3JeMMzIKA_VSYM3AAUnc6yZOokiyIgWyHOc1y3BwTznP05SnHBUZ0sy4yTNkfNC0ssB6ukeFtI6ghpmkBAyHNd1EoAWSBCAo2-PqGzAeNrFsMAmUPKwqFI4QGybVt2xEfDYjvMCtO06D9pMpc_DAaxHT9URUhOLgxAcaIxEiYFg3ObSAHcgNAqhRAcH8TMyEAoCgNNrCoNBJAgG6IAh8QEWyqZsq6hGHlRGiQEdfrt16kCFDe9CJrIJpFAQP850vEZLmoYp8HPLFZzkLGCGYlC0JoUr3M7Mw3EAN7kqZR_A-umsgEDB4xtqIZ4_C5MwLAQJByTABQSFeiA200Pw5D3FWwEB-NBBF9BqHutLuBoKE7BNhEmjRjH-EZ7SEBxvGxoJ62meQuBWeoHAoHSlWhgUEmsIfGg0xJvQ-eonrqLIEg5BAxB4wN8Wbcxo6Had5awFW-H3asZt4wAL30UQoX9vPYH_MgZpA2A_EdLEoEjzrEbd_h0f6gAZNMttzx3caz4RW-yqCqEU4xo7htwkSAA)

**Comment by tokyohost** [comment]
> You can set the color in [legend data](https://echarts.apache.org/en/option.html#legend.data.textStyle.color) for each item individually.
> 
> [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=G4QwTgBAJiAuIGcIF4IG0BQEIG8vYgDsQBbAUwC4IByQLS1BvzUDbtQWr1ACv0Ha_agGn21ABsArpQgBGAAw8CEMGQAOAezCwAKgE85ZAMIKoI6qO68ImsAGMyheAHMRAVgDMAOnH4AvlNzHi5KtUDdCYAziRxG0gLCVAAsntiyisrqmjp6fgBMoQSmFlYgtlSpqS7unnjSPvqAjjqA6eaA-OqADOohMRDhIqlNcUqqGtq6-gDsGdhZljYioqJF2B74pQTlfvWA_kaAoMqA836ApCGNxi357fKdiT0pNAAcgyZk5iO5YxOuUyXepPqAboqAa3JbYSBCY3vxXUlen4AJznYY5PIQABskwgbgwAF0ANwYDCgSBmBT8JQodD4agAYnE4mBABEAGLkjKEvqiABCJ3JAFFqQS-kymVCAIIOVmiYF0zl01mUrRQ8QDTyE8niE5M4msrSk4niFlSglMxzi8Qi8lc_ksxEotHgCD8Mi2QhQUlwEC4gDyACMAFZkMywJwAazIagQAAoYPAEABKJwkEByP0AM0EhHdAEsFIQIH741ayAAPYNeWJkWCCMDJ2bYebQW0INBpvQZhFOcpNWCZ2AAZVganNVBwEEx2LAVB7Skr6ZrcPcKLcweNCjksETydQswHfe7WKUnnNlqgneMSnjIz8wEus7M33OsGnfmyjbA53jmMIl_j5nNt8bJAA4hH8pJjPG3wB1eMoFgAALKgoSaQMQCoDdLGtW0mijJRw1ga8qBjONZyTFNymzYsCHNWAIAQWBIFQahqBRaRsEI5pvmEKjqKQyA_Vo-NcXEJEIHYgAeMsgycc1CGsUCuPjABqcS8OMaR4yjFMoIreNa3KFBkFQXCc2or4flxRTK1rFpGO07AAHpTOI0jcQAAxwEAAB8ABIcHKNw3FwR0nJwP0_RaCALO-fgADlBBIbMACoxGJUNz3JeMMzIKA_VSYM3AAUnc6yZOokiyIgWyHOc1y3BwTznP05SnHBUZ0sy4yTNkfNC0ssB6ukeFtI6ghpmkBAyHNd1EoAWSBCAo2-PqGzAeNrFsMAmUPKwqFI4QGybVt2xEfDYjvMCtO06D9pMpc_DAaxHT9URUhOLgxAcaIxEiYFg3ObSAHcgNAqhRAcH8TMyEAoCgNNrCoNBJAgG6IAh8QEWyqZsq6hGHlRGiQEdfrt16kCFDe9CJrIJpFAQP850vEZLmoYp8HPLFZzkLGCGYlC0JoUr3M7Mw3EAN7kqZR_A-umsgEDB4xtqIZ4_C5MwLAQJByTABQSFeiA200Pw5D3FWwEB-NBBF9BqHutLuBoKE7BNhEmjRjH-EZ7SEBxvGxoJ62meQuBWeoHAoHSlWhgUEmsIfGg0xJvQ-eonrqLIEg5BAxB4wN8Wbcxo6Had5awFW-H3asZt4wAL30UQoX9vPYH_MgZpA2A_EdLEoEjzrEbd_h0f6gAZNMttzx3caz4RW-yqCqEU4xo7htwkSAA)

thanks !, it's worked.  really solve my urgent need :)
