### ISSUE TITLE
[Bug] labelLayout is not work

### ISSUE THREAD

**Issue by Gamehu** [apache/echarts#19761]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/label-line-adjust-forked-kz46z8

### Steps to Reproduce

CodeSandbox can not happen this issue,have to copy it to own computer

### Current Behavior

Get the same code to the local area, labellayout does not execute at all

### Expected Behavior

labellayout is work

### Environment

```markdown
- OS:macos sonoma
- Browser: chrome 123.0.6312.59（
- Framework: react 16.14.0
```

**Comment by plainheart** [comment]
Have you imported and used the LabelLayout feature like this?

```js
import * as echarts from 'echarts/core'
import { LabelLayout } from 'echarts/features'

echarts.use(LabelLayout)
```
