### ISSUE TITLE
[Bug] series中type为line的数据，设置showSymbol为false，点legend隐藏数据后，鼠标悬浮过的数据无法隐藏

### ISSUE THREAD

**Issue by helloword1989** [apache/echarts#19766]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack&version=5.5.0&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOSQC2OsAzjgE4Q4OwAmAhmN5UQC-AGiJhgwLJBAFUxDKwDmillW6kIDAehFFcK6J1lF0PPgQDa1TpWGxrAJkoBdIaPSLWRwvNIEAjA4ADO7EpA4BwW5EZtwAWhI0libyPqnyYACeIPj2DFgQnCy2KenMONxSEHQEYMwArjih6egMABbAAO61DU2lqaQAghoMAJKGZJZBzs0tDHzMFLAh_RlkYADKWbjGLakAZjCbEABeuf7-q8SCV7p7cnsY2bmU-YXFs2UVVTUKjZ-pdpdHr_K7oTLDTTjIp-WAWaYA-S4fZLSgOACkJUejAWSxW2Kw3AARjgsAAFcoAY00UGgBActyIMyIQxGu2IWRyVFoOCxxCJwHqhm4zEyAHFuDJYPtKkxZgxKZV8HVGtFwZCGOz0DQIHTYABaByzGjqelqpisdjJeQPeTQbi_ax8jLPKgK3hgD79BiZGgCrAbU65ABsANi1paFn8AHZ_EEACzB-PxoKp1N2fzMvZR2MJpMpuPp2CZxFwmNxxPJoLBIslq45iv5oIAZjTGdc6Q711mtuI9sdYE4TgBnJeBWgvIBQM6G19_oIMqwcv64bh9fLearaZCywAdM2HAAOIKHo8n6Opw8AVivh6zkY3lYLbb3B9PDnjx8PB-DAE4HA4zbBve6QNpuKY1juQT7keQHBse0b_s2h7XkEwGlmBT4ti-0FvleJ4IVe8a_r-V7-MB_RdjoTIoIIADcQA

### Steps to Reproduce

1，series[0],type为scatter，data为类似这样的时序数据[[1710464400000, 1],[1710464401000, 1],[1710464402000, 1],...]
2，series[1],type为line，data为series[0]中的数据线性拟合后的数据，showSymbol设置为false
3，图表生成后，直接点击legend中的任意一个，对应图表中数据可正常隐藏
4，鼠标悬浮任意一段数据后，再点击legend中的任意一个，刚才悬浮过的地方残留有数据在图表上
下面的完整代码可直接在https://echarts.apache.org/examples/zh/editor.html?c=line-stack&version=5.5.0上试验
[echarts完整代码.txt](https://github.com/apache/echarts/files/14771111/echarts.txt)

### Current Behavior

1）数据量在3000多，图表生成后，鼠标悬浮任意一段数据后，再点击legend中的任意一个，刚才悬浮过的地方残留有数据在图表上
2）数据量较少时没问题

### Expected Behavior

点击legend中的任意一个，对应图表数据正常隐藏，不受其它操作的影响

### Environment

```markdown
- OS:win10
- Browser: Chrome 123.0.6312.59（正式版本）
```

**Comment by helgasoft** [comment]
Minimal Reproduction is with 4 points only - cannot reproduce.
cannot reproduce with 3100 points either - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-stack&version=5.5.0&code=CYQwLgvA2gug3AAgGYHsBOCAUBLCAGRbAHgGYBGPAhbAahoEoEBvBUMAOgAcBXAZwAtMUMgHYKAFgBs48XgqUa8vACpsAGgQBZcP3ZoQAO2AoAtpnox6iAL4AoFJzDYUBhBGa2ECJ2AA2AUwAuDy8vMH8ADzBggHInE38EXn80bH9eVnAQGM8EazVcsBQUXydOYKZcsNSAcxqU2JAI7F4cr3zcgPqjCqrMsBBgqDjgGI0RgCYYmFyOrxrU4F7QhAjgsgm8ApWIifXN2e3-kAAtYpMhvpXKldvvAE9OIIQY3l9sYBSxq9u0fxBStgEsEwGhuP4jncvAIUAB3EFgiE_HYAQWavAAkkZIkM8DBIVDeAM0NEEFtkaFwlEAMpge4BZZQlaoAxganYABezzIZAp7QpcyhNyZDyesTeHy-BLufwB8WeoPB0tuMPh3kRypW9zRLSxnzWCCgeM1oQCSFJMQmAFJviKksTSeS7b4QAAjfy-AAKfwAxi1nAZghMBbl8bkIjreIywo9nnEgf5baFXShuEYQGh7gBxEDlZAA5IE3g-gFBRX-Q65bXo6MIEzYQMIAC0EwJJiaQcrSRSaSjhr6wpWBhAwJeYFGyrpYpexfA4TQSZWvHuJhTvnZXP2yrYg37TOEYjwUhklFPGjIYf3ogk0lkSnPl6hB5vAFZZJtKA-Tc-j5IRLISDPBALx-GYVkFLxB1CYdR0mRdKVjWJ3gMRNlVVakVzXYIkALJE7h3YI2D6OwvBmaw4CAA)

**Comment by helloword1989** [comment]
with the code in the file i upload,reproduce it with 3600 points



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月28日 02:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [apache/echarts] [Bug] series中type为line的数据，设置showSymbol为false，点legend隐藏数据后，鼠标悬浮过的数据无法隐藏 (Issue #19766) |

Minimal Reproduction is with 4 points only - cannot reproduce.
cannot reproduce with 3100 points either - Demo

**Comment by helgasoft** [comment]
sorry, did not see the text file after the other link.
tested and **bug confirmed** for large datasets
workaround is to add ```emphasis:{disabled:true},``` under **_option_**. This property is undocumented.

**Comment by helloword1989** [comment]
thanks, set emphasis disabled worked
