### ISSUE TITLE
[Feature] Could legend item support the text and icon display vertically?

### ISSUE THREAD

**Issue by Sheepeer** [apache/echarts#19776]
### What problem does this feature solve?

I wanna create a legend like this:
![image](https://github.com/apache/echarts/assets/78125933/8b488d59-99f0-4360-a539-344a56df6a02)

### What does the proposed API look like?

```
legend: {
  align: 'top' | 'bottom'
}
```

**Comment by Sheepeer** [comment]
I tried using padding and textPadding to achive this, but in v5, it seems not effective.

**Comment by Sheepeer** [comment]
Solved by add ```rich``` to textStyle.

**Comment by B-o0O** [comment]
> Solved by add `rich` to textStyle.

i have the same problem , how did u solve it ,could u show me the code please
