### ISSUE TITLE
[Bug] Treemap doesnot work!

### ISSUE THREAD

**Issue by wusonw** [apache/echarts#19774]
### Version

5.5.0

### Link to Minimal Reproduction

https://codepen.io/wangwuzhen626/pen/dyLVbvw

### Steps to Reproduce

it work on [example site](https://echarts.apache.org/examples/zh/editor.html?c=treemap-show-parent&lang=ts) , but doesnot work on my computer

### Current Behavior

tree map cannot display as i wanted

### Expected Behavior

treemap shows well

### Environment

```markdown
- OS: macos and windosw
- Browser: chrome 
- Framework:null
```

### Any additional comments?

Please help me with this problem, thanks!

**Comment by plainheart** [comment]
去掉 JSON.parse 前后包裹的 []。

**Comment by wusonw** [comment]
我的问题，粗心了，检查了几遍没发现这个data后面多套了一层，**万分感谢**！
