### ISSUE TITLE
堆叠图线条错乱

### ISSUE THREAD

**Issue by smilingClown** [apache/echarts#19771]
### What problem does this feature solve?

堆叠图,多条折线图~ 当x轴不同时候,画的图会乱掉,画一条线的时候,页面显示是正确的
![image](https://github.com/apache/echarts/assets/29882458/ef67d474-5ad8-4d43-83e9-159a076da270)
![image](https://github.com/apache/echarts/assets/29882458/016daffb-ded6-451e-a5dc-ba050caa0765)

### What does the proposed API look like?

期望,多条折线图,显示内容正确

**Comment by smilingClown** [comment]
option = {
  yAxis: {
   
  },
  xAxis: {
    type: 'category',
    axisLabel: {},
    axisPointer: {
      show: true,
      type: 'line',
      lineStyle: {
        type: 'solid'
      }
    }
  },
  dataZoom: [
    {
      type: 'slider',
      bottom: 50,
      height: 22,
      brushSelect: false
    }
  ],
  series: [
  
    {
      name: '财信宽投宝象500指数增强33号',
      type: 'line',
      showSymbol: false,
      data: [
        ['20230120', 0],
        ['20230203', -0.04],
        ['20230210', -0.06],
        
        
       
      ]
    },
    {
      name: '华商领先企业',
      type: 'line',
      showSymbol: false,
      data: [
        ['20230120', 0],
        ['20230130', -0.4887],
        ['20230131', -1.3847],
        ['20230201', -0.2715],
        ['20230202', -0.4209],
        ['20230203', -0.1901],
        ['20230206', -1.1811],
        ['20230207', -1.2218],
        ['20230208', -1.9142],
        ['20230209', -0.5973],
        ['20230210', -1.0861],
        ['20230213', 0],
        ['20230214', -0.4043],
        ['20230215', -0.8489],
        ['20230216', -2.5064],
        ['20230217', -3.4901],
       
     
      ]
    },
  
  ],
  backgroundColor: '#FFFFFF'
};附上代码

**Comment by MatthiasMert** [comment]
If you dont specify [data](https://echarts.apache.org/en/option.html#xAxis.data) for xAxis type `'category'` echarts populates the xAxis data by order of occurrence. (which in your example would be `'20230120'` > ``'20230203'` > `'20230210'` > `'20230130'`).

To solve this provide xAxis data in the desired order: [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsCeBBAHhAzgFzIC-ANGrDrgcauumBiAKbEDkAxgIZgsDmwAE4Z2FBrAAmvbsQDalCewBMABmUBmVQEY1YxQxXqt2rfonojmnRu3mLVrWrviHa6-_tL3T1Rq-GPuqqAGwBlkFqAOzhsI7BAByx8WoAnMmR2qoZxuqmOR7aACwFTtoArKV5Ya7eucraMQYAurWw3Hj4ADLcAEYsADZ05AYdBAAKwBDQfEJ0Buj4ABbAAO7EYEIArixtjMxscQPTLLHH0CwAykwDh_QW-6wc-MDHkuwLsCQG3-gj6NIwNwAFrAYAAW3kBnuEiYTzi-DeLCEsV6wDAYAhxHKqj2sCWLAg_CWYGIymUeN622Wl0GLE4pNgADNuAN8CwfpRWpR2UIICwiLAFBIYQxoNxwYd2IAiWMAh_KAXu1AKlGgFztQCGMTjVIBwY0ADqaAPI1AFz6Gg0gHflWJwqXnU545ZrS4YcFoobM1nsvGA2RCz7oOTxXTZMiwVTch7elJ-MSwAC0qgAdKoisGQz7Mv6o7HQs1PpmJP8GKL0OLJRxAHLKgDFVQBhGYAJRUAgPKALDkzQcOJbYjbVnaHa9iCy2btPu6oSGhb69AGg3jQ0FTKnozGigkElFEw9k7lTC4o9oYxoEkVF-Oh5EdBGZ8oohUlxYVx51MfY0U0heJFffP4AzPtKkdI-GM_gjUNzG2gJNo2jfhO9SqDEb6buSQFgQeEFJNBMapMUyjwb-aS3jG5SpFEGgYSkWTHpuqgJCEoH7ph-SjoRmQlG-d7xgRVFEZUjExjuCSpHR9TaP-kbKDhoQJqxmRQVGGizp-oFZpy6CJr03CcAA1vwQjAFs0CSAAwq8wgcAAxAAYqZZkfCQADcQA)
