### ISSUE TITLE
[Feature] 添加Canvas元素的style设置

### ISSUE THREAD

**Issue by Fnxxxxo** [apache/echarts#19778]
### What problem does this feature solve?

可以在canvas元素上添加诸如z-index属性，控制canvas与外部元素的展示层级

### What does the proposed API look like?

设置series时，可以添加新属性，如给地图系列所在画布添加一个层级
```
{
  type: 'map',
  zlevel: 1,
  canvasStyle: {
    zIndex: 10
  }
}
```

**Comment by plainheart** [comment]
外部元素指的是除 echarts 容器之外的 HTML 元素？

**Comment by Fnxxxxo** [comment]
@plainheart 对的。我有一个外部的通栏跑马灯，穿过地图。如果有办法能给canvas上z-index，遮挡问题会好解决。对应的如果添加了这个配置，任何涉及外部元素和画布的遮挡问题，就可以在H5体系下解决，在canvas里规划zlevel，然后把需要突出的层单独与H5做布局处理

**Comment by plainheart** [comment]
可以尝试如下两种方式：

1、CSS 选择器

```css
canvas[data-zr-dom-id="zr_你的canvas序号"]
```

2、通过 API 获取到 Canvas Layer 对应的 DOM 元素

```js
myChart.getZr().painter.getLayer(Canvas序号).dom.style.zIndex = xxx
```
