### ISSUE TITLE
如何使用Echarts完成心电图

### ISSUE THREAD

**Issue by changmen1** [apache/echarts#19777]
### What problem does this feature solve?

我需要从websocket获取数据然后进行绘制，每一组有32条数据，X轴定义的最大值是320，我需要两条波形线，形成的动画效果，这是效果图
![666](https://github.com/apache/echarts/assets/164463472/2a0e0295-a52c-4934-b847-847f9eeda6e2)

### What does the proposed API look like?

希望有人可以有好的想法

**Comment by Fnxxxxo** [comment]
实时的估计不大行。没找的echarts有增量绘制的功能，你添加新数据，原来的动画就中断了。
你要是能缓存320个单位的数据，你批一批喂给折线图，那可以画。不过要是实时场景，估计会死人

**Comment by helgasoft** [comment]
> But if it were a real-time scene, people would probably die.

wow  @Fnxxxxo, ECharts could be a "[killer](https://www.google.com/search?q=killer+app+meaning)", but is not a murderer 🎃

@changmen1, take a look at [dynamic-data](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data), and some [animation examples](https://echarts.apache.org/examples/en/editor.html?c=dynamic-data2&theme=dark&code=GYVwdgxgLglg9mABAJwIZgCZwLYBFVSoAUAlIgN4BQiiYcA7ogLy0Cmj-UrRA1HYz0QJW-AJ4kA3NUQA3VABsQrZrIVLEggLIEAFgDo0mHKUQAqRACYADIgC0iAIxWpNZKyghkSKjRphU2KwAXLQMelBwAMpQyDBgAOakADTSNHKKwYgA2qm-Wfx68e4AYiDy8gCarKjIyaH0he6aCFA6JoIOSfWNUJzcJAC6egBWcHFEAOQA9BMkKb6-2q0GcOAYROlKJLkD0gC-UnuU8u6IGASoKlkDUidQ9Spg7Ih9RA4AnO8A7F3vXQDMkmOp2EYhUFgALGZEP8AGxWGzmJwI26nTbKFhLfSGLDYEzmACsKMowDgyEQGxqiBgKmc1MQAB5HAi6TAeDwyD4zhc9AAHEAAZzaOJwnGIJCBRzgvNgCBUXNgUBOIS5NC4AA8oCEJrhRP5sDAIC8LogAGSIAAqMECiAAguqYAKJvt5ogInB5LBeSrcjEYPEishtTAuNgJl1UA6BdrROHcqTkNgCFwg4hQJBZUgiLyagEBZzcjQc2hsAKVMW81krDdC6pyecuI9nq8K6W9PrWECFq53J4s7WaA3WD1XmQeAPENMJhoJ0Qhz1mmBWu1HGOJ1OZ93fPOilBSuUqjV2uvENrN1vEK2BXp0VkHLst13fHtXTQAFqRx0ABTGS9YqdVXx0GtAh4DAEJgAUAVWFyI4aBfaR1XtR0fQWKBRF5TIJlgQI4wWAVeXkEMABk4kyQCaCFBgIKgmCFjgxAEJoURkOjChfQwrD0Tw3wACNVkwGpRAAcVQb1sisLoJmRABSCYBlfRACKIqBSKeVDuyo-gaPkaDYNdJilP_GBWDYnIFgo2gAiw4pUAAa2UMVw2pDAgk6RBa3QzDtSIp4ePwnQGEiURsH4-QdOgxTBwuEIG1QfTcnIN1OO1AUIGTf9nKmKZWGAYBWGgSJ0qgFNawgIjxMg3TWCi7lCFii4qwU2sBRCsLIhgAAvTIHHc2sQ1YbBolEZUKH45AMH_AB1GAMFaIJ_i6cbJuQABhD0ySCCY3AwCZDIWJNkDstTyInVrQo9EIsgmOg_KSG7hHkrp5FQXjWHCigtIi1h9u7XzWGG0byHoWb5vciANqDCZ4jcVgwGcrysIFD1Zr2hj4OkZrosIN84BwIJyAFQhkC1b4ujh1zkQQg5KGgqAAEk_2QdIiHTaAwIpAtsdQPQhRgYAoFIFw2HoDAVBFPALiF6Q4r5QU2ieUWn2wURVp0GooF59wAHkZTAohAOg2JTKu2skrihrCC6Wa3K6RjavNmLskVjAFI8i9EEO46yI0j2LaycgWKjEIXZvNRWDvAY9jdic9nd7t0cQB9GMlLpet6yQgA).
