### ISSUE TITLE
[Bug] upgrade local 4.4.0version to 5.5.0 version，the front-end reported error

### ISSUE THREAD

**Issue by waterworld-warehouse** [apache/echarts#19783]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=area-stack

### Steps to Reproduce

1.write a component in my project.  （This component worked in version 4.4.0, but not in version 5.5.0）
<template>
  <div :id="id" ref="plot" v-loading="loading" :class="className" :style="{height:height,width:width}" />
</template>

<script>
import echarts from 'echarts'
import resize from '@/components/Charts/mixins/resize'
import _ from 'lodash'
import '../figures/macarons'

export default {
  mixins: [resize],
  props: {
    className: {
      type: String,
      default: 'chart'
    },
    id: {
      type: String,
      default: () => 'chart' + _.now().toString().slice(10, 13) + _.random(100, 999).toString()
    },
    width: {
      type: String,
      default: '100%'
    },
    height: {
      type: String,
      default: '100%'
    },
    plotData: {
      type: Object,
      default: () => {
        return {}
      }
    },
    columnsWithArea: {
      type: Array,
      default: () => [] // 需要显示面积的列名称
    }
  },
  data() {
    return {
      loading: false,
      chart: null,
      // 组件的series参数
      seriesItemDefaultSettings: {
        type: 'line',
        stack: 'Total',
        emphasis: {
          focus: 'series'
        }
      }
    }
  },
  watch: {
    plotData: {
      handler(newVal) {
        this.initChart()
      },
      deep: true
    }
  },
  mounted() {
    this.initChart()
  },
  beforeDestroy() {
    if (!this.chart) {
      return
    }
    this.chart.dispose()
    this.chart = null
  },
  methods: {
    initChart() {
      this.$emit('start-loading')
      // 创建一个 ECharts 实例，并设置成 macarons 主题
      this.chart = echarts.init(document.getElementById(this.id), 'macarons')
      const myChart = this.chart
      // 绘制图表
      var date = this.plotData['index'] // 横坐标
      var title_name = this.plotData['title']
      var columns = this.plotData['columns'] // 序列名称汇总
      var series_data = this.plotData['data'] // 所有序列数据

      var series_item_tmp // 在循环设置series的items时用于存放单个序列的设置字典
      var series = [] // series全设置
      var col_name // 暂存单个序列的名称
      var col_data // 暂存单个序列的数据
      for (var i = 0; i <= columns.length; i++) { // 对每个序列进行循环
        col_name = columns[i]
        col_data = series_data[col_name]

        // 对单个序列的设置进行初始化
        series_item_tmp = {}
        for (var key in this.seriesItemDefaultSettings) {
          series_item_tmp[key] = this.seriesItemDefaultSettings[key]
        }
        // 设置序列名称和序列数据
        series_item_tmp['name'] = col_name
        series_item_tmp['data'] = col_data

        // 设置面积显示
        if (this.columnsWithArea.includes(col_name)) {
          series_item_tmp['areaStyle'] = {}
        }
        series.push(series_item_tmp)
      }
      var option = {
        title: {
          text: title_name
        },
        tooltip: {
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            label: {
              backgroundColor: '#6a7985'
            }
          }
        },
        legend: {
          data: columns
        },
        toolbox: {
          feature: {
            saveAsImage: {}
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [
          {
            type: 'category',
            boundaryGap: false,
            data: date
          }
        ],
        yAxis: [
          {
            type: 'value'
          }
        ],
        series: series
      }
      myChart.setOption(option)

      setTimeout(_ => {
        this.chart.resize()
        // 初始化后进行resize, 如果是在被其他组件调用, 则只对当前display不为None的LinePlot生效
        // 对于其他display由none切换回显示的LinePlot组件需要手动调用resize
      }, 100)
      this.$emit('init-finished')
    }
  }
}
</script>

2.use my component.

          <StackedAreaChart
            v-if="Object.keys(linePlotData).length > 0"
            :ref="linePlotData.tab_name"
            :height="height"
            :width="itemWidth"
            :plot-data="linePlotData"
            :sort-tooltip="linePlotData.sort_tooltip"
            :sort-legend="linePlotData.sort_legend"
            :columns-with-area="linePlotData.columns"
          />
          
          
                linePlotData:
      {
        'plot_type': 'LinePlot',
        'tab_name': '底层配置走势图',
        'title': '底层配置走势图',
        'index': [
          '2023-12-01',
          '2023-12-04',
          '2023-12-05',
          '2023-12-06',
          '2023-12-07',
          '2023-12-08',
          '2023-12-11',
          '2023-12-12',
          '2023-12-13',
          '2023-12-14'
        ],
        'columns': ['苹果1号', '香蕉2号', '西瓜3号', '葡萄4号'],
        'data': {
          '苹果1号': [120, 132, 101, 134, 90, 230, 210, 134, 90, 230],
          '香蕉2号': [320, 332, 301, 334, 390, 330, 320, 301, 334, 390],
          '西瓜3号': [520, 532, 501, 0, 590, 530, 520, 501, 634, 590],
          '葡萄4号': [20, 32, 0, 34, 90, 30, 20, 21, 34, 90]
        }
      },
      
      
      
      here is my package.json
      
      {
  "name": "vue-element-admin",
  "version": "4.4.0",
  "description": "A magical vue admin. An out-of-box UI solution for enterprise applications. Newest development stack of vue. Lots of awesome features",
  "author": "Pan <panfree23@gmail.com>",
  "scripts": {
    "dev": "vue-cli-service serve",
    "lint": "eslint --ext .js,.vue src",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "new": "plop",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit"
  },
  "dependencies": {
    "@form-create/element-ui": "^2.5.31",
    "@gjmh/element-ui": "^2.15.14-beta.1",
    "@toast-ui/editor": "^2.3.1",
    "@vueuse/core": "^10.3.0",
    "axios": "0.18.1",
    "clipboard": "2.0.4",
    "codemirror": "5.45.0",
    "core-js": "3.31.1",
    "driver.js": "0.9.5",
    "dropzone": "5.5.1",
    "echarts": "5.5.0",
    "file-saver": "2.0.1",
    "fuse.js": "3.4.4",
    "js-cookie": "2.2.0",
    "jsonlint": "1.6.3",
    "jszip": "3.2.1",
    "lodash": "^4.17.21",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "print-js": "^1.6.0",
    "screenfull": "4.2.0",
    "script-loader": "0.7.2",
    "sortablejs": "1.8.4",
    "uuid": "^9.0.0",
    "vue": "^2.7.14",
    "vue-count-to": "1.0.13",
    "vue-easy-lightbox": "^0.23.0",
    "vue-pdf-app": "^2.1.0",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vue2-waterfall": "^3.0.1",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",
    "xlsx": "0.14.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.5.19",
    "@vue/cli-plugin-eslint": "4.5.19",
    "@vue/cli-plugin-unit-jest": "4.5.19",
    "@vue/cli-service": "4.5.19",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "9.5.1",
    "babel-eslint": "10.1.0",
    "babel-jest": "23.6.0",
    "babel-plugin-dynamic-import-node": "2.3.3",
    "chalk": "2.4.2",
    "chokidar": "2.1.5",
    "connect": "3.6.6",
    "eslint": "7.1.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-vue": "^9.15.1",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.3.1",
    "lint-staged": "8.1.5",
    "mockjs": "1.0.1-beta3",
    "plop": "2.3.0",
    "runjs": "4.3.2",
    "sass": "1.26.2",
    "sass-loader": "8.0.2",
    "script-ext-html-webpack-plugin": "2.1.3",
    "serve-static": "1.13.2",
    "svg-sprite-loader": "5.0.0",
    "svgo": "1.2.0",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "bugs": {
    "url": "https://github.com/PanJiaChen/vue-element-admin/issues"
  },
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "keywords": [
    "vue",
    "admin",
    "dashboard",
    "element-ui",
    "boilerplate",
    "admin-template",
    "management-system"
  ],
  "license": "MIT",
  "lint-staged": {
    "src/**/*.{js,vue}": [
      "eslint --fix",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/PanJiaChen/vue-element-admin.git"
  }
}

### Current Behavior

error,could no create chart
[
![前端报错的图片](https://github.com/apache/echarts/assets/65522098/e3577a8b-fdf9-49bd-b973-cd47d2f5055e)
](url)

### Expected Behavior

create chart as official website case

### Environment

```markdown
- OS: win 10 
- Browser: Chrome 123.0.6312.86（正式版本） （64 位）
- Framework: vue@2.6.10
```

**Comment by waterworld-warehouse** [comment]
`<template>
  <div :id="id" ref="plot" v-loading="loading" :class="className" :style="{height:height,width:width}" />
</template>

<script>
import echarts from 'echarts'
import resize from '@/components/Charts/mixins/resize'
import _ from 'lodash'
import '../figures/macarons'

export default {
  mixins: [resize],
  props: {
    className: {
      type: String,
      default: 'chart'
    },
    id: {
      type: String,
      default: () => 'chart' + _.now().toString().slice(10, 13) + _.random(100, 999).toString()
    },
    width: {
      type: String,
      default: '100%'
    },
    height: {
      type: String,
      default: '100%'
    },
    plotData: {
      type: Object,
      default: () => {
        return {}
      }
    },
    columnsWithArea: {
      type: Array,
      default: () => [] // 需要显示面积的列名称
    }
  },
  data() {
    return {
      loading: false,
      chart: null,
      // 组件的series参数
      seriesItemDefaultSettings: {
        type: 'line',
        stack: 'Total',
        emphasis: {
          focus: 'series'
        }
      }
    }
  },
  watch: {
    plotData: {
      handler(newVal) {
        this.initChart()
      },
      deep: true
    }
  },
  mounted() {
    this.initChart()
  },
  beforeDestroy() {
    if (!this.chart) {
      return
    }
    this.chart.dispose()
    this.chart = null
  },
  methods: {
    initChart() {
      this.$emit('start-loading')
      // 创建一个 ECharts 实例，并设置成 macarons 主题
      this.chart = echarts.init(document.getElementById(this.id), 'macarons')
      const myChart = this.chart
      // 绘制图表
      var date = this.plotData['index'] // 横坐标
      var title_name = this.plotData['title']
      var columns = this.plotData['columns'] // 序列名称汇总
      var series_data = this.plotData['data'] // 所有序列数据

      var series_item_tmp // 在循环设置series的items时用于存放单个序列的设置字典
      var series = [] // series全设置
      var col_name // 暂存单个序列的名称
      var col_data // 暂存单个序列的数据
      for (var i = 0; i <= columns.length; i++) { // 对每个序列进行循环
        col_name = columns[i]
        col_data = series_data[col_name]

        // 对单个序列的设置进行初始化
        series_item_tmp = {}
        for (var key in this.seriesItemDefaultSettings) {
          series_item_tmp[key] = this.seriesItemDefaultSettings[key]
        }
        // 设置序列名称和序列数据
        series_item_tmp['name'] = col_name
        series_item_tmp['data'] = col_data

        // 设置面积显示
        if (this.columnsWithArea.includes(col_name)) {
          series_item_tmp['areaStyle'] = {}
        }
        series.push(series_item_tmp)
      }
      var option = {
        title: {
          text: title_name
        },
        tooltip: {
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            label: {
              backgroundColor: '#6a7985'
            }
          }
        },
        legend: {
          data: columns
        },
        toolbox: {
          feature: {
            saveAsImage: {}
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [
          {
            type: 'category',
            boundaryGap: false,
            data: date
          }
        ],
        yAxis: [
          {
            type: 'value'
          }
        ],
        series: series
      }
      myChart.setOption(option)

      setTimeout(_ => {
        this.chart.resize()
        // 初始化后进行resize, 如果是在被其他组件调用, 则只对当前display不为None的LinePlot生效
        // 对于其他display由none切换回显示的LinePlot组件需要手动调用resize
      }, 100)
      this.$emit('init-finished')
    }
  }
}
</script>
`

sorry, here is my component code, I don't know why my answer code is not Standard.

**Comment by plainheart** [comment]
参阅 https://echarts.apache.org/handbook/zh/basics/release-note/v5-upgrade-guide/

**Comment by waterworld-warehouse** [comment]
here is my code
![图片1](https://github.com/apache/echarts/assets/65522098/070df5dd-faa3-4e4c-81b4-73efad1dab07)
![图片2](https://github.com/apache/echarts/assets/65522098/0dc55fa6-9a59-4b64-96da-8270b63b05e2)
![图片3](https://github.com/apache/echarts/assets/65522098/e89235d7-2209-4fdf-b18a-197611a6da70)
![图片4](https://github.com/apache/echarts/assets/65522098/b4b24694-ae72-4f7b-8df7-73467c5afd69)
![图片5](https://github.com/apache/echarts/assets/65522098/aa17a6a6-25cc-4632-b5ff-ecc419b1afae)

**Comment by waterworld-warehouse** [comment]
> 参阅 https://echarts.apache.org/handbook/zh/basics/release-note/v5-upgrade-guide/

Thank you for your answer. I know what's wrong.

import echarts from 'echarts';
// 或者按需引入
import echarts from 'echarts/lib/echarts';
这两种方式，v5 中不再支持了。
使用者需要如下更改代码解决这个问题：
import * as echarts from 'echarts';
