### ISSUE TITLE
[Feature] Disable emphasis state on legend hovering

### ISSUE THREAD

**Issue by ViniciusCestarii** [apache/echarts#19782]
### What problem does this feature solve?

I'm creating a chart using echart graph and i found that i can't disable the emphasis trigered by legend hovering, resulting in some unpleasent results.

this issue can be seem in your own example: https://echarts.apache.org/examples/en/editor.html?c=graph
where hovering the legend show only some conexions when the series.emphasis.focus = 'adjacency'

    legend: [
      {
        data: graph.categories.map(function (a) {
          return a.name;
        })
      }
    ],

    series: [
      {
        name: 'Les Miserables',
        type: 'graph',
        layout: 'none',
        data: graph.nodes,
        links: graph.links,
        categories: graph.categories,
        roam: true,
        label: {
          position: 'right',
          formatter: '{b}'
        },
        lineStyle: {
          color: 'source',
          curveness: 0.3
        },
        emphasis: {
          focus: 'adjacency', 
          lineStyle: {
            width: 10
          }
        }
      }
    ]

### What does the proposed API look like?

    legend.triggerEmphasis = false (default true)

**Comment by plainheart** [comment]
Just set [`legendHoverLink`](https://echarts.apache.org/option.html#series-graph.legendHoverLink) as `false`.

**Comment by ViniciusCestarii** [comment]
Thanks, I didnt notice this option property! I think it would be good to update this [example](https://echarts.apache.org/examples/en/editor.html?c=graph) to prevent this unexpected behavior when hovering over the legend.
