### ISSUE TITLE
[Bug] convertFromPixel  pie get is undefined?

### ISSUE THREAD

**Issue by piaopiaoran** [apache/echarts#19797]
### Version

5.3.0

### Link to Minimal Reproduction

no

### Steps to Reproduce

`<pre><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.3.0/dist/echarts.min.js"></script>
</head>
<body>
    <div id="main" style="width: 600px;height:400px;border:1px solid red;"></div>
    <script type="text/javascript">
        var chart = echarts.init(document.getElementById('main'));
        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            // xAxis: {},
            // yAxis: {},
            series: [{
                name: '销量',
                type: 'pie',
                data: [
                    { value: 1048, name: 'Search Engine' },
                    { value: 735, name: 'Direct' },
                    { value: 580, name: 'Email' },
                    { value: 484, name: 'Union Ads' },
                    { value: 300, name: 'Video Ads' }
                ]
            }]
        };
        chart.setOption(option);

        var zRender = chart.getZr();
        function handleIndexChange(params) {
            console.log('params', params);
            xIndexTem = chart.convertFromPixel({seriesIndex:0}, [params.offsetX, params.offsetY])
            // error 找不到原因为啥这里是undefined
            console.log('xIndexTem', xIndexTem); 
        }
        zRender.on('click', handleIndexChange);
    </script>
</body>
</html></pre>`

### Current Behavior

convertFromPixel return undefined

### Expected Behavior

convertFromPixel return data

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Pie charts do not have a  coordinate system for _convertFromPixel_ to convert to.
If axes are added and _convertFromPixel_'s parameter is changed from _seriesIndex_ to _gridIndex_, then one will get some coordinates. 
But I doubt they'll be more valuable than the pixel coordinates already available. [Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyGOAHmAQOQCiAwgBYCGATmAM7noC-ANGhsMFkggCSbr1wBzHNAAmI2GPTEAgsQgsRLWsADueAGb0sLHN1gBPVes3a9h46Z7oTjCDg2wA2r3Sp0_2Gh6AFt8WHJAAFTAecTyJwCMcxAw8hA3WJ9_GXowegJveP8kWAA3IwBXMIBGAAYAFgAOLkCQ5IBlHCYAY1pYSmgJCGgcdkUCwlKsCoIAdgBmAFYmoNCKABEIRhxOsBG4gqKJqdh5-uqllopKYPoILF2MgIPysIba85XwgFVoKDhlGTYCj28SekzCs2qZ2aH3IADUIDIcMBYP9ARwHrAALoZdHobEcADcKBQpUYsAAXgAlaSIsmIYLmOhMMAAOikYAAWowABQASiJ-jK0G2v1gDFkuAAkrISEz-jhuSAmCEWLzkLxOjAWAIcCysMAJNyUsrgmwmkrGCr-bxiNLEcQACo4YIIWAMpnMFma6DFHDMABijGAwQAChBiDgsNyihJXDI7SQCNUgV4MhaVSzgPp9CYwAANYHp02Z7O5gCavEx1vQ3u1uD1BqNtpljudsVgzftTuC1vRVJpfsz0CNnSwEE6AGt2-KZFKW3KpPygA)

**Comment by piaopiaoran** [comment]
@helgasoft i want to get Pie charts click dataIndex，but the above method doesn't seem to work。Is there a good way to recommend。must use zrender click

**Comment by piaopiaoran** [comment]
@helgasoft I'm very worried at the moment，Please, do something

**Comment by piaopiaoran** [comment]
@pissang Can you help me，Please

**Comment by helgasoft** [comment]
it seems zRender click has correct _dataIndex_ in ```params.target.__ec_inner_3.dataIndex```
📌 please close issue if problem solved.
