### ISSUE TITLE
[Bug] 雷达图如何添加纵向滚动条

### ISSUE THREAD

**Issue by guoliuqing123** [apache/echarts#19802]
### Version

无

### Link to Minimal Reproduction

无

### Steps to Reproduce

无

### Current Behavior

实现雷达图添加纵向滚动条

### Expected Behavior

 雷达图如何添加纵向滚动条

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
不太明白，雷达图怎么滚动？
