### ISSUE TITLE
[Issue]  geoJson MAP 如何在嵌套图形里面只在鼠标悬停子图形时高亮显示

### ISSUE THREAD

**Issue by zhengshubin** [apache/echarts#19803]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=map-HK

### Steps to Reproduce

code:
const geoJson={
  "type": "FeatureCollection",
  "features": [
     
        {"type":"Feature",
        "properties":{"name":"a"},
       "geometry":{ 
        "type": "Polygon",
        "coordinates": [
                        [ 
                            [100.0, 0], 
                            [101.0, 0.0], 
                            [101.0, 1.0], 
                            [100.0, 1.0], 
                            [100.0, 0.0] 
                        ] // 这层括号可能就是为了突出此为面，首尾点相同
                ] // 注意里面多了一层括号，区别于线
}

        },
		   {"type":"Feature",
        "properties":{"name":"b"},
       "geometry":{ 
        "type": "Polygon",
        "coordinates": [
                        [ 
                            [100.5, 0.5], 
                            [100.8, 0.5], 
                            [100.8, 0.8], 
                            [100.5, 0.8], 
                            [100.5, 0.5]
                        ] // 这层括号可能就是为了突出此为面，首尾点相同
                ] // 注意里面多了一层括号，区别于线
      }

        },
       
    ]
}
  echarts.registerMap('HK', geoJson);
  myChart.setOption(
    (option = {
     
    
      series: [
        {
          name: '香港18区人口密度',
          type: 'map',
          map: 'HK',
          label: {
            show: true
          },
         
        }
      ]
    })
  );

### Current Behavior

a图形高亮而b不触发

### Expected Behavior

b图形高亮，a不触发任何事件

### Environment

```markdown
- OS: win11
- Browser:  chrome
- Framework:
```

**Comment by helgasoft** [comment]
Apparently maps do not support nested areas. But they could be built as custom polygons - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChLwIwAYA0kCsaC6GSqmkA7KQUXAEwnmXI0m4PFYsJ4DcCoE1MeFRTYsANnyFGKauLGs4KABxy8nHggD2ABzABLTQDtBAbyJhNmgDb7tALkgmAvlMgAPAIJu9AZwfPXAE8vX38XIisAUwBzSMNgMNcfSIAnPUi_IWRkM2zssEDtSIcAcgBjAFcfCwBbEtc8wxAa4sgSj3qiPJS44FSASTBImocAMwrDMv0jSAAKbRAU5p8sEG09AEpHLrzIKLBIbU09QzAfQThuHbzRzRS5_cg9QTQuJ8gAHkg-EAA6KMM0TAAAs3noANTgra5XZ5I4nM6_bRVYGzNZ6X5lSwpYCzH5wPR4DYbHiw5BOa7ZHpgCopYwwsmQApFUpHKyBKwnSKdRnIHzAtatBm8-GnTKis4NXk-GqWEEONC_AAsUsZMrlwIAwkZqksEQ5ELzdnASJJKYy4BJxPhzbs1EbwkbqhzWujfs6orNhYzRnorFYHIZIgB3SCRMoClKI6JLbTAvRlX4AGS5iwA4ktgOlTrNTVgSCgsIajdlvSXNKNRskwArVSWsVY7qUesASrbYY6Szl22SK1XIjXIIWe7CG022utDABrNtd8kjyBEuuw3WaKetEoAIysFW5PacG2X2WGcZAPlC2y7Htd63dBU9Jkgvv9pRjkTiJUgB_3tqcpN2nZ5D8Dg_DsgGXrszIbpU1SaHUdZNC0pQAEI8rsABeUQAG6RAGkCyJSPTxAMQwjE-ExTAYxjzIsyyrOs0K2o8ErnLAlz_rCtz3LMjzPLArzvF8PzUP8cRAqCTyQoxRosUiKJoreWJ3LiwkEkSJK_ra1K0vSPZQay1gclyaFqgKLKOIcxxig4LFfkefL3jeGLXl6T5-nhJSBLhjbBvUkCruurK0toUSfge9lhjUp7npkZYro5Dhui5j7Ph5yIpCF3JfhsP6Mn-lLgcgwHfOAIDUGBRBqH-QA)
