### ISSUE TITLE
[Feature] 能否增加一个legend全选和反选的功能。目前只有自己添加一个全选的legend

### ISSUE THREAD

**Issue by huihui925** [apache/echarts#19817]
### What problem does this feature solve?

能否增加一个legend全选和反选的功能。目前只有自己添加一个全选的legend ，写起来代码过多。这个功能挺常用的，希望能支持。

### What does the proposed API look like?

无

**Comment by plainheart** [comment]
https://echarts.apache.org/option.html#legend.selector

**Comment by huihui925** [comment]
> https://echarts.apache.org/option.html#legend.selector

非常感谢，很赞！
