### ISSUE TITLE
[Bug] lines series doesn't work with dataMin or dataMax

### ISSUE THREAD

**Issue by Reecer9714** [apache/echarts#19818]
### Version

5.4.1

### Link to Minimal Reproduction

https://codepen.io/cyric/pen/OJNpLxJ

### Steps to Reproduce

1. Create a lines series using 'dataMin', 'dataMax' or the default values
2. Observe the axes not respecting the data on load or after zoom

### Current Behavior

A specific min or max must be defined otherwise the axis doesn't auto scale

### Expected Behavior

The data to be visible, especially after scroll zoom. Similar to scatter

### Environment

```markdown
- OS: Debian
- Browser: Firefox 115.4.0esr
- Framework: Vue@3
```

### Any additional comments?

[Reopening of issue 13177](https://github.com/apache/echarts/issues/13177)

**Comment by helgasoft** [comment]
yes, _lines_ do not work with axis dataMin or dataMax, but it's easy to extract those values from the data - [Demo](https://echarts.apache.org/examples/en/editor.html?code=G4QwTgBANglgdgUwM4QLwQNoCgIQN464QDGA9qWACZIBcmhRmAjADQRMAMAuiw0RgGY2A7ny6EAvr1wFGZCtTrZGuQW048-qgKzDRjcbimFZReVVr0VmXe27SVGAOx7DRNxKxcA3FgBmaBAAFAAeLH4ArnAAlGgAfPhgCAAuEWBwEJFwQQB0eSE55tQ5ALYgAA5BQQCesagJ5eBICACScMk1GExc0b0QEr5lIYEAsiDJABalICG5ebCISNOVoXUJfqFsY5PTIb3Rg_Cj41Ml8HM5C8jLVXvxmZsQ26fw-75YpOXJMKQZ6KYhACCIRgljwEDOcDoHDYQzonH6DmqwNBdHBkLokNhM0xMwgAGptIjCM0wDBkEo-KZGMlquUEHQAORXJCMhxychUeDjBAAZWqSGSCBKTOI4CFSBgIDgACZKGytBBKOMQHQWeyiEhqiUAEakKCimBgYhQBAK6xa3X63kwABeDIgukV5X11SudD8ICgzT4nlwmlwyuSIAAWuQRXhafSaIz4JLKGa2BRye0Y8AEGBvmKoGyIMiQUg2gmQjQOJ4BkA).

**Comment by Reecer9714** [comment]
I ended up doing something similar. Calculating the minimum for the `lines` series, then using a function for the yAxis min to compare that to the rest of the data.
