### ISSUE TITLE
[Bug] NPE with tooltip

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#19827]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html

### Steps to Reproduce

My use case involves calling setOption on a chart that is already rendering.

I apologize that I don't have reproducible code as I don't know what is causing the following NPE. I am hoping the stack trace can help. From the little I tried to debug, during the setOption, a tooltip element is getting created, but some how it is also getting disposed before the manuallyShowTip is being called to show the tooltip.

### Current Behavior

it results in NPE with the following stack trace.

```js
TooltipHTMLContent.js:312 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at TooltipHTMLContent.setContent (TooltipHTMLContent.js:312:19)
    at TooltipView._showTooltipContent (TooltipView.js:562:20)
    at TooltipView.<anonymous> (TooltipView.js:465:12)
    at TooltipView._showOrMove (TooltipView.js:343:60)
    at TooltipView._showSeriesItemTooltip (TooltipView.js:464:10)
    at TooltipView._tryShow (TooltipView.js:324:14)
    at TooltipView.manuallyShowTip (TooltipView.js:244:12)
    at TooltipView.js:149:37
```

### Expected Behavior

It should not throw NPE. I confirmed that version 5.4.0 doesn't have this issue.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
cannot replicate _showTip_ error - [Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyGOAHmAQOQDGWElA1rAGbABOsAzgBbADuAKhBDlYAXwA0aDMGBZIIAqnTowLCAHM1OFhQCGxCO3ISlsHVh46AnuwDK3HgGEYYHNDIYWAVxyTxk3JrQACYKfuhqqiHIksqgFABMAAwApEYxsLiM7uQArKnGSgBGwGBgwAC2FHlpJqpqnNkAjCk1SpTOOhDQADI6hThYBCrevgXEAIL67ArpYJYg-LBUOi5qrJat6MWewToslgDiOvJMZuw4BejsIDRg3V2LiiYc9kNeF-noNNA4NnO4M2ebRkrAoAGJGgBOeI6AAssPIn1E6TCSj0BgE9AUL14BEYZxwokusCCKx0BAA2uR4gBaADMRiWtIRYiZNJyjOpNIAbJzaQB2Pk0gAc5AAuqNJJZJgZsdAdOVFuQNkTJOdVDhprAKekniZ5YqKONNko5gsKN8cCavg8_pYAdEgeh2lhQUsWGpCjoABSNHJiRrc-JieJ0_2NACUiKBqJMexwOjtDqQsbaNBO-Kw52J6FJYHJ2py_tgRdZkMSrP5_NZzQrsEhkLFOY86k0LHuPwAogA3VzuYY-EypvVKA1KgBC1ow8yVlqnlqTjyRzpB2ndnp9FfisO5AeFdIDUaRqfQEBc5UXgKdLrd5A9Xu9W53e4PkejzxPphYCcvyE_1EEPECWbPMCwpMMa0SOthTrbli3LVkYKbJEVFbLQOxwHs-zeEYh0kCURAAbhQFByksBxOD2MAADoYG9KgaHoRlvQjBAAD5HVgMiKKo6iggMEAVkoThxkoSA6JHM0lS4XgBCEYl1QgTUAElghIAgK3SUDVKCdSS18CNiJEQygA)

**Comment by dirslashls** [comment]
I managed to work around this. My charts are highly interactive and so the setOption API is getting called multiple times. I think there is some timing issue that can cause the above NPE. As I managed to work around it, I am closing it as I am not sure how to provide a reproducible test case.

**Comment by IM-001** [comment]
The lazyUpdate: true can help mitigate that I think.

`yourEchartInstance.setOption({
  // whatever setOption you're setting
}, {
  lazyUpdate: true,
});`

**Comment by piersrr** [comment]
I worked around this. Had the error when using setOption with a drag function and misusing setOption(options, true) when I should have been setting a narrower set of options e.g. setOption(options,{replaceMerge:['series']}), instead of "true"

**Comment by Jasperhino** [comment]
> I managed to work around this. My charts are highly interactive and so the setOption API is getting called multiple times. I think there is some timing issue that can cause the above NPE. As I managed to work around it, I am closing it as I am not sure how to provide a reproducible test case.

How did you work around this?

**Comment by ktx-abhay** [comment]
Facing same issue. any solution?

**Comment by adrianimboden** [comment]
I had/have the exact same issue. In my case, it happens when multiple `setOption()` calls are being done.

I had multiple `setOption()` calls directly beside each other, which triggered the NPE instantly on small changes.

After refactoring, I had only one setOption which updated everything at once. I have never seen the NPE since then.

But I am quite certain that this is an unsolved bug still. Calling setOption often may not be good for performance, but it should certainly not crash because of this.
