### ISSUE TITLE
[Bug] Bar chart column width with a single data point is extremely wide.

### ISSUE THREAD

**Issue by PJUllrich** [apache/echarts#19833]
### Version

5.5.0

### Link to Minimal Reproduction

https://jsfiddle.net/emL5csh3/1/

### Steps to Reproduce

1. Create a Bar chart with a single data point.

### Current Behavior

<img width="751" alt="CleanShot 2024-04-15 at 10 19 41@2x" src="https://github.com/apache/echarts/assets/10426523/4167e440-3a09-4c07-bce3-c7ce64ebee97">

The column of the single data point is extremely wide and it exceeds the width of its "space" on the xAxis.

### Expected Behavior

The width of the column should not exceed the width of its width in the xAxis. So, if I have 10 data ticks on the xAxis and all of them are e.g. 20px, the max width of the column of a single data point should not exceed 20px.

### Environment

```markdown
- OS: macOS Sonoma 14.4
- Browser: Arc
- Framework:
```

**Comment by MatthiasMert** [comment]
Just specify the [barWidth](https://echarts.apache.org/en/option.html#series-bar.barWidth) if you want a specific one. By default (and because bars are most often used with category axis) echarts will make the bar use all space available.
