### ISSUE TITLE
[Feature] 折线图series上的label支持和x轴一样的根据密度分布显示

### ISSUE THREAD

**Issue by SONASIDANTE** [apache/echarts#19832]
### What problem does this feature solve?

大数据量的时候想显示label，就会出现所有label都显示的请客。如果自己进行密度分布可能和x轴的数据显示不同步
![image](https://github.com/apache/echarts/assets/18680319/9b5d0649-d23c-4bff-93fc-91dc98698315)

### What does the proposed API look like?

增加一个类似xAxis均匀显示的api`   xAxis: {
        data: xData,
        axisLabel: {
          interval: 'auto'
        }
      },`

**Comment by MatthiasMert** [comment]
labelLayout { [hideOverlap](https://echarts.apache.org/en/option.html#series-line.labelLayout.hideOverlap): true} ?
