### ISSUE TITLE
[Bug] axisLabel width无效

### ISSUE THREAD

**Issue by GetemJay** [apache/echarts#19841]
### Version

5.5.0

### Link to Minimal Reproduction

https://jsfiddle.net/qch70t5z/1/

### Steps to Reproduce

设置的width不生效
![image](https://github.com/apache/echarts/assets/26429903/8c3e53a8-3ed8-4833-8c17-46f8d4c8b963)

### Current Behavior

当width设置成大于y轴文字实际占用的宽度后，并不生效。（往小了设置是生效的）

### Expected Behavior

axisLabel.width可以生效

### Environment

```markdown
- OS:macOS Sonoma
- Browser:123.0.6312.122
- Framework:Vue@3
```

**Comment by Ovilia** [comment]
If you set `grid.left` to be larger, you will see that `axisLabel.width` is actually working. If you want to move the chart to the right, the correct way is to set `grid.left` to be larger instead of changing `axisLabel.width`. `axisLabel.width` is to control the text wrapping.

**Comment by GetemJay** [comment]
> If you set `grid.left` to be larger, you will see that `axisLabel.width` is actually working. If you want to move the chart to the right, the correct way is to set `grid.left` to be larger instead of changing `axisLabel.width`. `axisLabel.width` is to control the text wrapping.

实际的需求是有一列很多个图表 希望y轴可以对齐 但是由于y轴的数字大小不一样 有的是10 有的是3000000。我试了下 就算设置了grid.left为一个大的值 然后设置axisLabel.width 也没办法对齐。请问这种情况应该怎么处理呢？而且按照文档上的描述axisLabel.width是控制“文本显示宽度”，但是实际上单独设置又不生效，是不是有歧义呢

**Comment by GetemJay** [comment]
啊我知道了。grid.containLabel设成false。
