### ISSUE TITLE
[Feature] 在Echarts图标的表格/标题中添加上标/下标

### ISSUE THREAD

**Issue by XiaoKonglong99** [apache/echarts#19848]
### What problem does this feature solve?

我在用Apache ECharts 5.5 中绘制图表的时候，希望在图标的标签中插入下标文字。
例如分子的Apparent permeability: P<sub>app</sub>
我在查找了相关资料后发现该功能无法实现，希望能在后续的版本中支持。感谢！

### What does the proposed API look like?

NA

**Comment by plainheart** [comment]
如果是数字或英文的话，可以考虑使用[工具](https://www.tinytextgenerator.com/superscript-text.html)将常规字符转换上标或下标字符。
