### ISSUE TITLE
[Bug] dataset decals

### ISSUE THREAD

**Issue by brandonstubbs** [apache/echarts#19853]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqx7ACuATgMYGkDa5Fys0WAtk7AOQwC_ADSwAblgA21PgEZYAXxFsKSTjz78wAd2CiJ02aTliIYAtwDKYAJ5S-6jAXrTS6vLe4AjYFNLatBBY0ADmDvxKUYqqALrkyuSEQQR4LKqo7Oh2IFogEMKqMejxigDcQA

### Steps to Reproduce

`itemStyle` is ignored from a `dataset`

#### dataset example:
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqx7ACuATgMYGkDa5Fys0WAtk7AOQwC_ADSwAblgA21PgEZYAXxFsKSTjz78wAd2CiJ02aTliIYAtwDKYAJ5S-6jAXrTS6vLe4AjYFNLatBBY0ADmDvxKUYqqALrkyuSEQQR4LKqo7Oh2IFogEMKqMejxigDcQA

#### series data example:
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5CPkwDRUUAmAhmL2Jlq1JLGi8Ato1hMYWDrABuvADYBXGQEZYAX04iKYidOZgA7sEUqN29rAhgskgMp1VMpNywBjNcSQMWkkAI2BVMzxeaABzDyZdXT0udABdLl1ydN0AbiA

#### workaround
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsCGAnCGBcya6sAptBgEYA2JAJgWFgK4kA0R6tJAxhlQUlgBnABbAA7g2ZtYXXlSEEA2oKEBPALYVg_WAHJoMEntgBfVsmGbtuvY1zQA5jROmAumaLmitDGAxCJGACHMLATFjcJMqh6ILkGtH6RnoWAG58LAQAjGbsxMTxGIkEduLAqbAZVFmwuaahbl75wiQ4JIqwSqGoBehgaiBJeiAQxqEN6E2mANxAA
This workaround was taken from https://stackoverflow.com/questions/77321155/customising-item-style-of-a-specific-item-of-the-series-using-dataset-property-i

### Current Behavior

Currently the `itemStyle` is ignored if you are using a `dataset`.

### Expected Behavior

Ideally `itemStyle` would not be ignored and I could use this same `itemStyle` across multiple series that use this datasource. There is a workaround, I want to confirm if that is the recommended approach or if this is indeed an issue?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
This is not a problem with decal. Add `  aria: {
    decal: {
      show: true
    }
  }` to your option

**Comment by brandonstubbs** [comment]
@Ovilia that does not solve the issue, as now there is a decal on each value. See example:
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsCGAnCGBcysAJgKYDGGANgUrAM4AWwA7gWFgK4mwC-vANGmIYwGOiTA0h6OsA5YyJAgG1p6QtAwBbJbADkMEnv6wAblS4EAjALXpamnQT1hmwY2Yu6rJiGBJaAMpgAJ6UurSkFNSEdCFaAEbAMS44GNAA5uF6vLk8agC6QjyCMiQ4JHQqaqjq6qEgunogEEZq-ehFPADcQA

**Comment by Ovilia** [comment]
Dataset is used to seperate data from style, so it's natural that there is no `dataset.source.itemStyle` option. The correct way to set decal is like: 
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsCGAnCGBcya6sAJgKYDGGANgUrAM4AWwA7gWFgK5kA0plGgwIBtegwCeAWwBGwWrADkWSmEWwAvv3HS5CxRQhYK1Muo0BdTUS1ESGMBgZkwdIugbAuxsqPfF6aAwpXyUYM34ANxoeAgBGTV5_dEDg0MUwVmBFKJjQhI1_CxskjzIcMmFYEX9UYmIwCRB0kAgzf0L0Yo0AbiA

**Comment by brandonstubbs** [comment]
Ok thanks for confirming that is the correct approach to take

**Comment by brandonstubbs** [comment]
This does not work for the bar chart:
https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack&code=PYBwLglsB2AEC8sDeAoWsCGAnCGBcya6sAJgKYDGGANgUrAM4AWwA7gWFgK5kA0plGgwIBtegwCeAWwBGwWrADknXNADm1MotgBffuOlyFiihCwVN2nQF1dRPUQAeAQUcRhyWGAkgyBExhgZGrAWBJWvEQSru50DugkgRgMZGB0ROgMwFzmfrAiGcT00BhSeYowWvwAbjQ8BACMupHERbAlZf5grMCKNXV5TTqF1vYtjGQ4ZB4Frait6N6-_jLYioXD6KM6ANxAA

One bar should be `triangle` the other `circle`, they are both `triangle`
