### ISSUE TITLE
[Question] 在title中应用rich富文本标签失败

### ISSUE THREAD

**Issue by sichenyong** [apache/echarts#19855]
### What problem does this feature solve?

Version: 5.5.0
在官网中rich自定义富文本样式的示例是这样的：
An example of  custom `rich` text style on the offical website  is as follows: 
![image](https://github.com/apache/echarts/assets/91589693/62923a15-ccf2-4308-9930-7af684eadafa)

我仿照这么写：
i wrote it like this: 
```javascript
  option = {
      title: {
          text: [`highLight|关键词${search_text}`, '气泡统计图'].join(''),
          textStyle: {
              rich: {
                  highLight: {
                      color: 'red'
                  }
              }
          }
      },
// something others
}
```

在应用的时候富文本样式没有效果......
it does't work correctly......

![image](https://github.com/apache/echarts/assets/91589693/8d714d7a-5eac-480c-847c-6d3145a99254)

### What does the proposed API look like?

how to work correctly?

**Comment by plainheart** [comment]
得用 {} 包起来呀
