### ISSUE TITLE
[Feature] Is there any copyright restriction on the China map in your source code?

### ISSUE THREAD

**Issue by Fred-wizard** [apache/echarts#19858]
### What problem does this feature solve?

Hi, I noticed that there is no China map chart in your official website examples. Is it due to copyright restrictions or some other reason? I want to use this map, but I'm concerned about copyright issues, so I wanted to ask.

### What does the proposed API look like?

looking forward to your reply.

**Comment by plainheart** [comment]
ECharts is just a charting library. We don't provide the map data. If you hope to display charts on the map, you must ensure the map data and source are legal. To be serious, you need to get a map approval number for your map if you plan to make it accessible to the public.
