### ISSUE TITLE
minMargin 的用法在文档里面为什么搜不到？

### ISSUE THREAD

**Issue by huohuo521** [apache/echarts#19861]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-labelLine-adjust&version=5.4.3

### Steps to Reproduce

https://echarts.apache.org/examples/zh/editor.html?c=pie-labelLine-adjust&version=5.4.3

### Current Behavior

minMargin 的用法在文档里面为什么搜不到？

### Expected Behavior

minMargin 的用法在文档里面为什么搜不到？

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
_minMargin _ is undocumented
https://github.com/apache/echarts/blob/697e7984e40d3136ce6c22ca581a245b6b1bf877/src/util/types.ts#L1056
