### ISSUE TITLE
[Bug] x轴和y轴都是数值的情况下，怎么配置才能保证坐标是1:1的刻度比例？

### ISSUE THREAD

**Issue by myhub5120** [apache/echarts#19868]
### Version

5.3.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple

### Steps to Reproduce

[叶型坐标轴等比缩放.txt](https://github.com/apache/echarts/files/15129321/default.txt)
![2024-04-26_182432](https://github.com/apache/echarts/assets/5894073/68e45dff-854c-4b12-acea-b5da7a0623af)
使用附件中的文件，在echars的line图上进行测试，也无法达到1:1的准确比例。

### Current Behavior

[叶型坐标轴等比缩放.txt](https://github.com/apache/echarts/files/15129299/default.txt)
请下载附件查阅，看到的效果总不是1:1，比如：x的坐标轴是1cm的间隔，那么y轴也要同时保持1cm的间隔
请问这个怎么配置呢？

### Expected Behavior

我期望数据导入之后，x和y坐标的大小要1:1的比例保持，设置了各种效果，感觉比例还是不对。特别是缩放后。
当坐标轴设置interval和min/max后，感觉数据的横坐标刻度不是个正方形效果。

### Environment

```markdown
- OS:windows
- Browser: chrome 124.0.6367.79
- Framework:Vue@3
```

**Comment by helgasoft** [comment]
> feels like the abscissa scale of the data is not a square effect.

First, your data isn't exactly "square",  [-10,10] vs [-11,12].
Second, setting up a square chart is easy. Just _init_ with width & height, or add [resize](https://echarts.apache.org/en/api.html#echartsInstance.resize) later - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-function&code=GYVwdgxgLglg9mABKSAKAHgSkQbwFCKLqID0AvIgIwAMA3AYgE4CmUIjSAsgIZQAWAOgDOMMBmwAqRD34CIcIRkRSATIgDUVSdN6CRY4lIDMGxCu0BWOngC-eFNHhIA5szDNGvZgBFe3VNj4hAA2rIgAJn6IFADaALr0hMBwjIiooVCIMNGIALQq1HRZiAA8FAVF2eoU1AKUgQyEkVDcAgAOIEJ8qDEwADTI4BCoMJhxmImIdoQsbBwRfvR2cG2wCDlBiNxgMAC2vE4AXMjcwULMfQzOjDDhx5uEUCvHACzUl4QhzMBQx1Yfnxuzj4v0QbwBhAARnAoE9dn9qAwbAD0ABBdAwIT3RqIMDcXbMY4AcnQRIhiF2ohSABUYBAANbYz6fLpwADuxygjBAzBxyJxlLAKQAym1gjAoAAZUSE3A4wisjmILk8vlIgEAT3RmKZnzxBOJGrJAtEx1yNHeAu46GOFvJgppdMZcuZCr47M53N5zP5zIdjFF4qlMt1zMVntVPvVDGa3AAWnA4PDEDEcQ8We6lSqLvLlRq2rKiaIROFmMbXcgYMEoB5OHBS8She5y660RihABJMClm0p6hxckKlqMKAANVOPLNBUHiDc4XHwUnZkRPvJ6bdHuVXpnUHzheLtzLM-AVZrjDrDcQRKbR9zWvbXZ7xxi_ZnQmHY4nsvylorc4XS4FGqhADgw5w3MwWIpmmua7gWxLis2b6ZsKGq7NCwTHMApznDOEDim0EY5hWsbHK47ieDWvgtAEwGIHEtj0OcUC0gScAgFAqABNEAB8uAUhqADCfDcCOAgsCIABezCoDgbK3PwhxWO8iB8MwMDAr8yk2JgyJUNQExAA)
📌 please close issue if problem solved.

**Comment by myhub5120** [comment]
@helgasoft thank you
