### ISSUE TITLE
[question] 折线图的起始位置如何做偏移

### ISSUE THREAD

**Issue by wangchao0724** [apache/echarts#19877]
### Version

5.5

### Link to Minimal Reproduction

none

### Steps to Reproduce

https://codesandbox.io/p/sandbox/basic-area-chart-qstf3z?file=%2Findex.js

### Current Behavior

X轴的起点和终点不能设置偏移，[boundaryGap](https://echarts.apache.org/zh/option.html#xAxis.boundaryGap) 选项不能满足我的需求

### Expected Behavior

X轴的起始坐标可以设置偏移，从偏移位置开始显示坐标轴, 并且不影响坐标轴间隔 ![image](https://github.com/apache/echarts/assets/155077270/82198393-9631-4947-b5f7-ff6f610cf3e2)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
> The starting point and end point of the X-axis cannot be offset.

That is due to xAxis being type 'category'.  Try xAxis with _type:'time'_ and _min_ and _max_ values.

**Comment by wangchao0724** [comment]
> > X轴的起点和终点不能偏移。
> 
> 这是因为 xAxis 是“类别”类型。尝试使用 xAxis _type:'time'_以及_最小值_和_最大值_。

如果X轴不是 "time" 类型, 要如何做偏移呢？
