### ISSUE TITLE
[Bug] geo.select.disabled 设置为true，不生效

### ISSUE THREAD

**Issue by FlyoverBlind** [apache/echarts#19903]
### Version

5.5.0

### Link to Minimal Reproduction

geo.select.disabled 设置为true，不生效 

### Steps to Reproduce

geo.select.disabled 设置为true，不生效 

### Current Behavior

geo.select.disabled 设置为true，不生效 

### Expected Behavior

geo.select.disabled 设置为true，不生效 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Did you forget to set also [selectedMode](https://echarts.apache.org/en/option.html#geo.selectedMode) ?

**Comment by FlyoverBlind** [comment]
> Did you forget to set also [selectedMode](https://echarts.apache.org/en/option.html#geo.selectedMode) ?

this is my code `myChart.showLoading();
$.get(ROOT_PATH + '/data/asset/geo/HK.json', function (geoJson) {
  myChart.hideLoading();
  echarts.registerMap('HK', geoJson);
  myChart.setOption(
    (option = {
      title: {
        text: 'Population Density of Hong Kong （2011）',
        subtext: 'Data from Wikipedia',
        sublink:
          'http://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83#cite_note-12'
      },
      tooltip: {
        trigger: 'item',
        formatter: '{b}<br/>{c} (p / km2)'
      },
      toolbox: {
        show: true,
        orient: 'vertical',
        left: 'right',
        top: 'center',
        feature: {
          dataView: { readOnly: false },
          restore: {},
          saveAsImage: {}
        }
      },
      visualMap: {
        min: 800,
        max: 50000,
        text: ['High', 'Low'],
        realtime: false,
        calculable: true,
        inRange: {
          color: ['lightskyblue', 'yellow', 'orangered']
        }
      },
      geo: {
        map: 'HK',
        selectedMode: 'multiple',
        label: {
          show: true
        },
        emphasis: {
          disabled: true
        },
        select: {
          disabled: true
        },
        
      },

    })
  );
});
`

**Comment by plainheart** [comment]
根据原始 PR #15534，`select: { disabled: true }` 是为了设置某个数据项禁止选中，如果全部都不希望选中，可以直接设置 `selectedMode` 为 `false`。

**Comment by helgasoft** [comment]
And here is the opposite - to select from data and from _dispatch_ action - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiCMC8AEDaAoWsDesB2IC2BTAXLAOQCCANiAEY4hEA0sAbiGQK4GwAsAHAEy-wAvnWRpMODkQDyACwCWAe3pMW7QpADsAZkhCRKdFjyFSAJzkAvBVmXM2HAGwBWJ1oYBnXGVwBjMLmBCVGA5dypvQgAzFk9BPVFDCRMSUwBrEAww91tVDl4ATk58-INxY2IAYRY5SIVTDDlaBjs1WG4ABk5dYQSyyQqFMjqQYCVm3MInSG4NDy9ff0C0ELDKCNhoslj4gF0AbkREbABPCpkQUzAAOncZBQB3ABkFEbkMAHMACgBKA4ASK7vXBgT4AJSkUgAKgB9AAKJEhAAlYABqYgAelAEHRIHcnjA6KBCnRAFUAMokK4AK3c1mUkVYGD8igwsE-rDCAClaRhvmhRCczhdrvJgLhnq8Pj8DihfOdLu4rqZcO9Qv5TABZEAAB0-RHJJGUHJA3OsDFQohQ5Fx6SCKG8kTAhAAtJAdAwwAptYReE4GPc5MAwDJ1E4SkJfqJPe8yHAwKZ2DLYF6wCzYHALSgUIxQqwWFrvfys1mHU7iOZ3jIwMpsG9CO0GLBsCAAB6EDrtBuWrNvUEZIF2nyDOqEeDlgLKIjHLxDe5EWA7ITd4Swbuecy4dyj7ulMDHbWSZvams6kwG5RWBTYH0MUwva-wePsfTFrOebx-AIahRikzYVhkKm2rePQO5vvMfh2mBxZyP42Bknu6yoEOQymPgRDNkCGAQMolB1GKpgDKh6HKsAuH4bgpgAOqBsG-BaII0Hhq-sBYiAhBsZAYGMcWOyiIISaCvK1z4lI2qptYnwpiykYoEJwpXCs2rgD4MgkMykmoHuB4mO-CzKGxACSGBim2CANloi6CJG1l7EAA).

**Comment by FlyoverBlind** [comment]
this is ok
