### ISSUE TITLE
[Bug] 配置多个legend 展示未实现

### ISSUE THREAD

**Issue by guoliuqing123** [apache/echarts#19908]
### Version

无

### Link to Minimal Reproduction

无

### Steps to Reproduce

data = [
    [
        {
            "type": "education",
            "name": "硕士",
            "value": 138,
        },
        {
            "type": "education",
            "name": "本科",
            "value": 549,
        },
        {
            "type": "education",
            "name": "专科",
            "value": 131,
        },
        {
            "type": "education",
            "name": "其他",
            "value": 73,
        }
    ],
    [
        {
            "type": "compile",
            "name": "空管在编",
            "value": 365,
        },
        {
           
            "type": "compile",
            "name": "合同",
            "value": 50,
        },
        {
            
            "type": "compile",
            "name": "劳务派遣",
            "value": 9,
           
        }
    ],
    [
        {
            "number": null,
            "avgAge": null,
            "license": null,
            "proportion": 0.81,
            "type": "sex",
            "name": "男",
            "value": 858,
            "countValue": null,
            "eduCountList": null,
            "omDeptId": null,
            "omOfficeId": null,
            "omManageUnitId": null,
            "itemStyle": {
                "borderWidth": 2,
                "color": "#7291c8"
            }
        },
        {
            "number": null,
            "avgAge": null,
            "license": null,
            "proportion": 0.19,
            "type": "sex",
            "name": "女",
            "value": 202,
            "countValue": null,
            "eduCountList": null,
            "omDeptId": null,
            "omOfficeId": null,
            "omManageUnitId": null,
            "itemStyle": {
                "borderWidth": 2,
                "color": "#7ed6ba"
            }
        }
    ]
],
result = [
    {
        "type": "education",
        "value": 891
    },
    {
        "type": "compile",
        "value": 424
    },
    {
        "type": "sex",
        "value": 1060
    }
],

option = {
  tooltip: {},
  legend:[
    {
      left: '10%',
      selectedMode: false,  //图例选择的模式
      bottom: '5%',
      data:[
        {
          name: '男',
          icon: 'circle',
        },
        {
            name: '女',
            icon: 'circle',
         },
      ],
    },
    {
      right: '30%',
      selectedMode: false,  //图例选择的模式
      top: '1%',
      data:data[1]
    },
    {
      right: '30%',
      selectedMode: false,  //图例选择的模式
      top: '45%',
      data:data[0]
    },
  ],
  grid: [
    {  //柱状图1
      top: 10,
      width: '50%',
      bottom: '60%',
      right: 10,
      // containLabel: true
    },
    {  //柱状图2
      top: '55%',
      width: '50%',
      bottom: 0,
      right: 10,
      // containLabel: true
    }
  ],
  xAxis: [
    {
      type: 'value',
      max: result.filter(item=>item.type === 'compile')[0].value,
      splitLine: {
        show: false
      },
      axisTick: false,// 隐藏刻度代码
      axisLabel: { //隐藏刻度字
        show:false
      },
      axisLine:{ //隐藏坐标轴
        show:false
      },
    },
    {
      type: 'value',
      max: result.filter(item=>item.type === 'education')[0].value,
      gridIndex: 1,
      splitLine: {
        show: false
      },
      axisTick: false,// 隐藏刻度代码
      axisLabel: {
        show:false
      },
      axisLine:{
        show:false
      },
    }
  ],
  yAxis: [
    {
      type: 'category',
      data: Object.keys(data[1]).reverse().map(function (key) {
        return data[1][key]['name'];
      }),
      splitLine: {
        show: false
      },
      axisTick: false,// 隐藏刻度代码
      axisLabel: {
        show:false
      },
      axisLine:{
        show:false
      },
    },
    {
      gridIndex: 1,
      type: 'category',
      data: Object.keys(data[0]).reverse().map(function (key) {
        return data[0][key]['name'];
      }),
      splitLine: {
        show: false
      },
      axisTick: false,// 隐藏刻度代码
      axisLabel: {
        show:false
      },
      axisLine:{
        show:false
      },
    }
  ],

  series: [
    {
      type: 'pie',
      radius: ['35%', '50%'], //饼图大小
      center: ['20%', '50%'], //饼图位置
      label: {
        show: false,
      }, //引导线不显示
      hoverOffset: 0,
      data: data[2],
    },
    {
      type: 'bar',
      stack: 'compile',
      barWidth: 15,
      z: 3,
      label: {
        show: false
      },
      itemStyle:{
        color: function (params) {
          if (params.name === '劳务派遣') {
            return '#64A7EB';
          } else if (params.name === '合同') {
            return '#60D8AC';
          } else if (params.name === '空管在编') {
            return '#7591C8';
          }
        }
      },
      data: Object.keys(data[1]).reverse().map(function (key) {
        return data[1][key]['value'];
      }),
      name: Object.keys(data[1]).reverse().map(function (key) {
        return data[1][key]['name'];
      }),
    },
    {
      type: 'bar',
      stack: 'compile',
      barWidth: 15,
      silent: true,
      itemStyle: {
        color: '#ebebeb'
      },
      data: Object.keys(data[1]).reverse().map(function (key) {
        return (result.filter(item=>item.type === 'compile')[0].value - data[1][key]['value']);
      })
    },
    {      
      type: 'bar',
      stack: 'education',
      barWidth: 15,
      xAxisIndex: 1,
      yAxisIndex: 1,
      z: 3,
      label: {
        show: false
      },
      itemStyle:{
        color: function (params) {
          if (params.name === '硕士') {
            return '#64A7EB';
          } else if (params.name === '本科') {
            return '#60D8AC';
          } else if (params.name === '专科') {
            return '#7591C8';
          } else if (params.name === '其他') {
            return '#aaaaaa';
          }
        }
      },
      data: Object.keys(data[0]).reverse().map(function (key) {
        return data[0][key]['value'];
      }),
        name: Object.keys(data[0]).reverse().map(item=>item.name),
    },
    {
      type: 'bar',
      stack: 'education',
      barWidth: 15,
      silent: true,
      xAxisIndex: 1,
      yAxisIndex: 1,
      itemStyle: {
        color: '#ebebeb'
      },
      data: Object.keys(data[0]).reverse().map(function (key) {
        return (result.filter(item=>item.type === 'education')[0].value - data[0][key]['value']);
      })
    },
  ]
};

### Current Behavior

![图一](https://github.com/apache/echarts/assets/105954867/0b82fb98-7ca8-4ba8-87de-8fe106c62997)
已将legend 配置为 数组 但是柱状图的legend 未展示出来 （不知道是否是我的配置问题）

还有个问题 环形图是否可以将文字数据展示在类似图二的样式中 是否有配置项之类的

### Expected Behavior

![图二](https://github.com/apache/echarts/assets/105954867/71ae4953-941f-4406-b39d-99ad864c9cb0)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
As the [documentation ](https://echarts.apache.org/en/option.html#legend.data) states, `legend.data` is associated with series **names**. In echarts the approach to what you want to do would be to use one series for each bar. Also, you can use [showBackground](https://echarts.apache.org/en/option.html#series-bar.showBackground) instead of using a stacked bar.

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AG4CGANgK5W0A0J6eAFsADuRAGYs8VEgF9u6cjnxFUpMpRqxaAY0ZgqAc2AAnclx6x-Q0eMnoZJZvqrQAJkrPOdjIgG0k0RgC26rSAXl6Ahd6AFOqAaP60Msj-QXSAECqAMCqxnPGBwYDNSoCFSoB8toDGCbEAutKy5lSGEFSEsN5myiqq1HQARoyGps2wCcHh0d3NHYYA6hDOYHxEAIwArBUqIwDijCBEAByLpBaCAEKMmgDWeobArC5EYIbs2-gQugEAyhQObj3omsDMRnQAxAB2OYAThmAGENrQzLY7rAPGAvPUAMwANjmZRUdhUTRUFFaGhGQxUfWSaVhI3Gk2msHmsN2B2Op3OlzINyosIeVGer3UOOaXx-hn-KIADAARDZYMFQnpY5rwxHeOYijGkOXoPnoPHBQmwkkaPJFImkCkTKazBbQ8wCfaHE5nC6uVm3K2c7nkN7ED6wAW_DR_FEAFiwAIAonsZc11aQFT5garbCQylIANxAA)

**Comment by guoliuqing123** [comment]
谢谢啦   还有个问题 环形图是否可以将文字数据展示在类似图二的样式中 是否有配置项之类的呢
