### ISSUE TITLE
how to change the scale size of the pie and doughnut chart when hover

### ISSUE THREAD

**Issue by karthik-noveau** [apache/echarts#19910]
### Version

5.5.0

### Link to Minimal Reproduction

https://github.com/karthik-noveau/e-charts

### Steps to Reproduce

npm install
npm start
hover on pie chart

### Current Behavior

not able to control the scaling size of the hovered pie chart

### Expected Behavior

need to reduce the scaling size of hovered piechart item

### Environment

```markdown
- OS:macOS
- Browser:chrome
- Framework:react js
```

**Comment by Ovilia** [comment]
https://echarts.apache.org/en/option.html#series-pie.emphasis.scaleSize

**Comment by karthik-noveau** [comment]
> https://echarts.apache.org/en/option.html#series-pie.emphasis.scaleSize

Thank you
