### ISSUE TITLE
[Bug] X-Axis does not follow the configuration of each dataset and grid

### ISSUE THREAD

**Issue by hmidibe** [apache/echarts#19916]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFywDaa6ylVsewArgE4DGBpFttnXtA5AGEcBAObAmEAnwA0NXrD5gAniCmz5VPgFkA8gEkAcgGVYAEQCisAKwAGG7AEAxAIKwAFLABq-gBoBaIy0TAEoFdQ0FWwBGWD9YKLt7J1cPbz1_QJCwuV4-BJsYuIBmRIcXdy9fAKDYUJkcrj4SgtjrUuSKtIyauvCNPgAFABkAVRMARRHLWzsylMr06qz6iIVdQxMLNqTyjy10gBVLXob-aNb8nfn9nyPa7NW8u0LYZquKm7uTx-aXmfe9odjg8IoNRhMptsAbBPsCVqD1sYzNNZh0PKZnAdXN9Qec4pc5hUMVj7vD-vkXm9CejMdiQf1fq1_tSzLTSX15GCxrBJijUbtWSS6qdYABdDncEXoPjOFgACxweDJnKw8pwyt4AHYAJwAOiiADYJVwbMbaKapbALatrRFbRp7fJHbxnSazVRXeb3egorqAExFb3xPUGqJBmwi8Uinj9TzACAAD1gACUAJcEAA2GsaADd4wns7RtZrdZq_eGK5bPR7Kzba3b6w7G079Zqg379WGq5H3THOXHEw5gABbcBYABGEAzEDwqcLmjzifn6GLuoNVmbLs3bqr269u4PdcPdv1AA5263wz3o3xMin01npAo8MOlU_8k_TVbPz_v3-vwBv6Af-UYaH2uR3gII5jpO06zsuz6vghH7Hk2qFOnuNboVu2E7ke-ENt2GigfIZB8KYOBYPemYyAo2C4LRwFMUBLH_r-H4gb2lrkZRQ6jrgsEznOQZ8PRWAIdW6CSd-uH7gRaHyRhslYYpvAoapJqRg0opyAAvhyqC8GATBYNAeAAGbiMOpCGfIyiqKQfDmVOYAEEw84sDAzkiDZloYBAw4EGZUDQI59lqJaOZYBmDDsAoi4FiK-kiiAEjQCQsDGbFDS6XpBkNMZpkWVZvkaOFjnORmrnue6nnQN5pURP5gXBTAYUqBFqxRTFcV8C-SpJe6qUQOlpBZQQOV5XItm0IVZmWUw1nUGVHUVS5bkeV5EA-ctTUBUFeAhe1qgId1sWOWJfCDSlaUZeNk20MltAzVQc3FYtjVGatCiVdVm31dtn3yM1B1HQo4WndF50KKqCpgFdGhPfIw2jZlTDZbwuWPZQJEZqIQUYEDeBysAADuY3oxN6BIyIEiE-Q00NHj5kZU8ACk2YSCIcoZepXBgKAjkJBzxrjsAYAC0tfCajYIsNHVuAjUME6ZqQ5nRYQU3PUzBAs0Lsuc9tPOkHzs2CwoRRWHLvBixLI6OQALFb2YK1gSsqxmasa1TVBI-gL3oMzrPC4b3O83YxoCyAjkGgbovi5Ljl-nH8swIr0DK-OquwOrGaa49-W8EH-vW1wXPG_EEcFebfCns78d21L9ep-lbsZx7Xt5z71M4-EAvAFVEDR7t6DE2TFOxRyxnbSIbmOVgCYzgjsBI0oziL3gHCM7wtMQBgejQBgBAJqQrrlQoLDCGITBKNmI05m5hATwQxoLzOmfZwHVCWelADqBBG1ZmLDMGB5w_zAEYCAAAvOKUQHYPV9oXLgu996H2PibSO30-CX1ctfW-xp76PziuNV-G8P6exHlwcB_9AGOWAaA904DIEwJNvAzGWsqBfxQQfI-J9YDlgKlgnBohxD4IaIQpgT80aTwaG_PA5Cga0GoQAsOdCB4MJFEw6BsC2FcCxog7eyC6Y8PQa8TBDkL5X1EXfaAD9JHEMpqQ9-HdKFKLTjQ1RCh6FgLTswnRCCe7oBIgmdeM4t7ax3sYtBfDXTAHMuZQgGUz5YLOp1LgY9ybSJfrIshI04pf3QDAAAWm5YAz93TFNKaEvAJiYkBJXkg2g3DokYIaHEhJRBT7mN6qk7MGTyk5PfnkxRVBKlMDKVkip0ASnjOqbUk29S_auNgM03hpABG8HaYkrpgiLF8F6cafpkzBnyOGcswp0zSkDI0GM4AcyWn8MWY0qgqzTGBjafE7ZMkvp7IOQ0I5JCTlDDOQU2AtzrnyFufctZrxFm90oIQCQBBN4MwifzLB44sA1QaNALAgVHKIk2HyFkXQljsn-bgFgABrRyeBKVUuzBmFxoKAWOM0e4lRFc-DeJysaJlWcMzKyUIwDKoK5R7wIDoOxTLh73UxockmpMABCqoqW00YIfCFtBMXUvVQwQ-RhlB4xGYUkAqoIDKFPrqXRBcGhiUSfM-Ixo14b0da6EJrqHmuiCp5I-JrYB8I2fIJQp8nmGNmhirF2ZcX4siC0fE7QBSkrvDiWgdLVW0vpYy5lIpWUyI0Mo2hXj1HL1tUXD2QqRX-vFUfKVbkZXP15f8xVKrdXjP1fTQFNtVV6oNUa_JIpQDmstVaa1TbeD2qII6rsvAXUzjdcaD186vXGh9cAP15yA2kHeRoENVow1oojXszF2LeAxt6hSVoVI0QLG6MsQ59LM2quzQK_1ebskFo5UW7lJbx1cH5ZmStDBRUihrZK6VWBZWUz_WmltPb22auOd2ttGqMCGqUMazdQ6WAWr3TYMd8q7WUQdQ8mdXA501JXQ0JdlGYXeugL6gdGg-EO3dHhg9nDdm9RPdGvFvVGRxGZDe5NPR6RUHTdSp91KX2f1zYqrVVCv2eJ_SA0tBjy0CqAyBjQYG61MAbVkmD4m4MoY7Qp9AOq1UIbQ_2_12HcNWpteprgk6wDTuddC0x7rPMxNXQx9dTH5B8I3CKdj7Cy2cZ-dxqNxpz2OWGNyXkUISVVBTWJ0ej7nxZr5TmjQ77GFKa5TywjGnANYGFcB6tEq9MGblXohVZNW1WdQ-Z2Alne02Yw4FzZZqcMjvw056mxpXPuYaBRhd1GfM7N4GujdoK-FGlC6G8Lzn_ZcboTFnFfGCX6CRFsGYLJYTkt4BJmlWXn05dfZu_L7K_6cqAb-kr_6K3larZu3TEGoMY3q82xr8GWtIa4O16z6HMOgvs_1gjP2J3EanaRjznq6OLqm98rgs3utcD4W2Jb-6VtDfDa9SNp6uBxbjS8AkN6jupvE5lvq2Wma5fkDdz9d3v3Feh89zTr3Kvveq59xtT3YN_dM4hrtQP_sdtBxj2gEO8NQ4i7QEb8Oxso-84jrzfnGP-r4eeHHEY8cNIJ-gc-3LNtnu2woS9xRE3XCBMd9JtPTsyYoSy-TgPeCFuU-zhXVAAOCu59p-QH362QYFxzoXyqJei7Zch5rkvbNYd6w50dg3Dcw9wCRmFZHaDjao7wGjE2Zv-bmyKPh2o2PLb0RwtbUWNvE9oKTpozwmQ24-Hb6nGWM3nek5d2TeW3di494Vh7qmjOBxexVwPvBg_6dD4ZwXxnhdx-j_m8XIvOtg8HUnyHqelnoCV1nhHy6keTfV75ho6Ptcm2rGFqvPuv4m547Fi3XIIR8mhFT9LdBHf09Ky7uT487uimrOXuj24evuE-b2YqfOIeX23cq2i-ke6-rWwOqGUudm2-cuu-w2sObmyus6quyOZ-02aOxe0uVAfCUQ2e5Gle2M9-62XiZuJOL-hKyI2wLIxIdIfSP-F2DOV2rugBg-wBYAHiRWYBPu4-XOk-VWta_O8-4Bo8Jmy-naMea-yh6Biew6WBY-mAuBo2BBxBqOtABeeepBWum6lBQas6tBvs1eyyj-TBDeL-eIlc_I8wnB9uaaPBPefBfeTOA-qhQ-IBYho-C-khZW0hvOshsBYeEhdAShHWKBUeG-5BpqWhjmOhB-pi1B6AueJ--ehBF-ZBV-8QO6waNhgSCBD-ROvGsaTw8arwreNIQoX-p2UmDKve_-_eghgRwhohI-oCOhfuWmMh4GMR8hcRGSTWiRQBFmyRGh4OmBGRYRuhGecOh-Kuhhaux-GuRR5h82rCFeuOd-VRDBpu9eVAjeAmyWN6HhHe3-XedOvBf-b6ARq-QRIh92aioRChsAwxAeoxNWc-dWkxCR1mSR6-CxW-6RKemReh-B5GhRBRWxmuAWJRUQIWu6FRK8dh1Rx6jhlxL-CWb-NxAodxrR3hHRvhXR_hPR7xfRXxxaPxcR_xkR0B0Rs-cBOhUxyREJ6hCeixMJA2cJaxeBGxBhOx5-yJkpJBtAl-FhJsi2WJxxdBpxtejBFx6AjerB-2bhnQqWom3BjxTunRrxdJH68gnuIRgxKxrJUBoGMBnJsRCBihS-MxQhcxkJAp0JfW2hKxWRgaR-tG2RRBMpTqexaJCp_CRx-uJx-Oh6hO-JmpsAjeLhFOSaBp96FKxpv-nOfhJ2bxFpHx_R3xNpvxdpPO7JYxTpExLp8Rbp4JsxbW8x3pNySxsJ_p8JMKVhVAeRIZp-YZORsA8pBxZieuHGNe6KSZtRF6ze1uepqQmZnhNOOZzxeZNJBZ5pBWwRAxam8Z65IxUR1ZtW0GKxPJyBTZqB8eXWGBQp8udZAZ6yQZ-hmOKOQ5I5pepArG45BuSyeJ0WyZVxc5pJ8wImWZJ2lJzuZpmSHp38w-pZe5aeB5AJR5QJXJZ5YJAOsFV5faN5mhvpyxvxj50Zmxg5oZwZlBqJJezGpAmJ5RKpth9B6p5xM58W4IPIkIQmGZiwaWRpkm3eVJLx12hZ25nxbO4hdZFZU-XAM-J532oJDZWFvRnp_JeFgpBFHZRFXZpiPZuRb55FL5cpxRUZSp9FsZqp-5k5R6AFrFawu2RK7BlO7eFJq5PhQlAhMFylcFO5CFQxkBlZDpHJcl8BlliB0xjZ2FLZalPpyewpnZopjqulsAfZlFA5FFrSRe-xn5sA2Oyp5ljFapU5Nlz-dRaZTRMIzlfFZ2Txbl650FrW6AVpu5flUh9pOmjpwV3JmFZml5UVm-bZd52BRGCVDySVKVGVr5hh75xlo5uueVE59hNRJVs5DR16Aon-VV7RUFwlW5t2YloBzJkl_l0ltAslwJp5vx55yhfJHWUJA1GlcVWlI13Zz5CJxh-lEZ1FQWpA5eP5cZSFVliZxVW2dR1xXFtutwcID6rlgldVO1nl9JbiPlTJZZLJx1gJchIJdZV17pXlOFKRt5D195oV--2lgZpF6V4Z0plN01WVNFlcMZC1_5detlr-HF7-h2lV0N_FNVsNtAfu9VTZjV8FKNiFe-fx6NqFmNF1ClSB11vVXp0V91sVxNANVAxFY1H11NhlVAH59NVBjNv5zyxuS1INvUOpxKtxbI9xbRAl21HlDVOcItKmqNR1rVAV7VQV518l2N3VK-RZVA-Nd1kK7Zj1cRGtr14pk1ZFn1qRW68QSVuR2J-ioVzNGprNZVC5goXB3N1VJp1JgtsFwtyNLtYtnRh5VZaFzpJN9ZctuNiNzZit_VIdg1Ip-A6xOlkd_Z2tb1utM12VUQZR1hDFlRqdZxT-Zt-sq15V5Jm1dtpp8NjtTVvltpktld0tPtNdONEVeNfVcdsuhF4dZNT5FNOt6AJhUdRldN318Q3581RtRumUpt5uoNwF4NRI1tLlPN-d7lABCNAdSN-11pZd1JFdgVx53tIVatrpddO9DdQdrZLdRNQ16e7dYpndp9vd59WtZhkZo5GJht_1f549BJWpRJ7FSW79zROd2Z39uZ_NjOm5_9olJZotLVERbVQeHVkDXVilPVkVTd-9odqt4tEdmDl9FBODV9eDA9plw9-Vo9atadLFy1O2GwbBB2wmS5NtkFC9DtQtTtJd3ubtHDHtXDXt6Fl1ftKh8De9hNKtKDLmx9Y5EplNSVF9GDmVMj9NidyVyduJJDgFzhDR6ZoF2jX9ed9DEB_Bf9S9ztxjNdUlGN4xWNW91jN1IOiDPWrd8VaDjqQ9vZKO7jRTVFcdfCBTOe_jTFRVLNqjluwFa1YTPFhpudW1ejsTBjy9bDq97tJ1VAZ1ljst4VSltjgj9jO-bdmebyXd5NPdL1sdJRd9ZlTNgTrNYN5VYFy5nedDa5DDMT3RzDe1rDpd7D_ubJ4DVdtZaTfD_tosdj-FDjkzHd5TMzJ9cznjuDX1-etFhDFlSjqzdTbNlDGz4Tc9vN9tHTRdhjQDzVPTpjfT6AAz1d0Dtdwz_Du9YzDzEzuTUzLz4jHz71hhSVetN9cjNBI9OJ1T1ltTk9dl6jupH-XNtDkTuz0T-Z6SIlRzjJJzcLZznD0-3DgzvtNzNjADjdqlzd2TyDTz6DeLrjiVBlo1pTJRuVyzD9CZJt05gLmdjLkNWzDxOztVez7LEecTRjEliTa9FzG9UD4t29IzYrCDStSDjzOLzz26rzJF7zsznzZTpAc1arRDxtT9WrtL9RlI5VG1rT89Bdi9nT8TFrKLSTUtKTMtwrsDDrdzmL6lrrT1eTDyFTyVJTaVCrCzUZv199Qbj9DhQTr9DRVDFVerOjMNELBzZrMLK95ZVrntEDQr1zGb6LozErQjOTebuLHr-LPrhLYZxL_d-tN-VThV1L6dgLxJ7NIFbeTbETbTsb-jULXTPLXbvTyTNZqTKL9rg7jr9zOb2LY77rLjiJRLir8zXjXzmOJsQ5SdFLKd_zzFE9L95t9lGjWds90b4L7Tbb8b5rh1lrx7Kbp7ab_baLtzDQTrkrXAB9mlR9z10zk7bz0dbjyrUZUQvjt-fzxDf7pDKZwT5OM9n9YLP9cNe7XlxdHb3TR78LJ7nVGFIrGTaBWTGHwjjjiuzjhb41XrBHpbr7frpRvzBVY9lHtbK1EbIH9HYHjHxrG5HLu1LObHh7aNcH69qbm9576TCtw74zfpd7srE78rSrJb9n0n6JSz8jKzinazb9dHLRDHUT4RWnprUHenCTSb3b5jvbyLdrZnAjFnWLVn2H-bMKYnxb3r-H0jb7xhJsdFrn6rkWNTK7Yba7wLqn3n6nvnEt-ztJhzunxzwX4tybRnCHJnkXvH5nt1AnMuQnMr-TnrxTT7Zb-DZLlT37AT7ngLFtjl3Fd6-rtt4Hu7kLLH0LNXibdXoXArFjEXDWA7KHsebXzrUrub8X47sALnhThhhbHjcrvrJRpHi7CneXKjYbOrKWzT4FDuLbEHlX7bS3MHIXhn1rxntrm3yHorWbMXN7cXD5zjJ3elZ3z7uHTnUZhbX7CjlLS7QNNLAHU9Kn0ImzzbhrfNbL_niBX33LtX5dKFDX3HVjLX0Xu36HHXo7h3970PRbsPDniXRHo5LPyPbn93_7zBdbfwILL303ujc3kH-7CbP3K3f3PblzZ7zXW3IPqH17MVt7TPNnx3nr53KOhbJL3z1gcnijFHfPVHjehXnFwvU3ePLLRrhPhdC3B7ZPoDFP_3jXgPv2SvfH159PoynXbrmvLP4nOvbPCPo5g3vZt3v7pvSnaje2lt61TLEF734vn3gX33rtsHnH8HVPQzvJrXmTe3gnjPkPOHLG2vcPl3aXMnqr2XVbGrIbwNmPZOFwkbSfb3-Prbafkv0Hmfv32flPPDPHXvBf_HRfDP0rAfjqQfuvlftnV3UZAbdf5HwbNbrNVujRWdUbzLO7v9EvjvUvffMvA_bvuf6bwP3vuFvvaRk_1n0_Ff7P8PC_o5FbgbK_1bz9Av_GnnW_7fXhKfe_bvgf174gM_8YDOXja14Yj9aehfa_mCn9538HkM_UPpJwLac8B6C7YblS3R75dm-QLS3r_y3Y-dWWfnB3g3VY4Z9QByFc5hAIB5QCL-o_H3iO1v4a97-eHB9tO0pp6852N9A2n9Xf4N81-Y3IDgyw4Jqcd-MbQAUwxJ7iVpe5PGgWF3l6IdTONPDFmDzV4Q8a6xFZAWGRD66D0B-tG7lgLR6asm-X_RyE9ytolcJBs3KQdpyq6WlD-VAzTuAMUGQDh-DAmAWPzgGYcw6pfBLqYh0FcC5-HAvutfQN6D0jeqPO7suwe54CN-jTD-tYOT6d8Pu0g9PqT2W7yD-WMlQVht096eC1BdPZgQd38FHcgh3XR_lXzCHeNeB3PPxsYJiE4C4h5gi2D_2hCgcbBGne3nGx75BcshLvBQWt3C5XMVB0AoobAJKHq8yhzPB_il1CHoB9e77eIFl3JYo8f2JvWIfzycJ1ELeHNKwTQxSG28CepA3ocAP6FyDBhOQ06nkNGGK9ChQ7YoZZ0PozDA-cw1ARz366yMohGwnGCgF0gABuIAA

### Steps to Reproduce

You can check the code in the minimal reproduction

### Current Behavior

Actually, each chart does not follow the configuration of its XAxis. Somehow, the x-axis was shifted 

### Expected Behavior

Each chart on the same dataset using the transform filter and multiple Grid/Axis configuration can be displayed correctly and each group of data has it's own configuration.

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Framework: Angular
```

**Comment by helgasoft** [comment]
The series come from 4 different datasets, they can't have the same stack id. Add the following code after _option_:
```
option.series = option.series.map((ss) => {
  ss.stack= 'stak' + ss.datasetIndex;
  return ss;
});
```
You could also use [scroll](https://echarts.apache.org/en/option.html#legend.type) for the long legend. 📌 please close issue if problem solved.

![image](https://github.com/apache/echarts/assets/13038071/1bc51b35-d217-4443-8d07-1aade3889f92)

**Comment by hmidibe** [comment]
It works for me. Thank you
