### ISSUE TITLE
[Bug] 盒须图dataset计算有误，最大值不对

### ISSUE THREAD

**Issue by GetemJay** [apache/echarts#19918]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcsA2musiaRjgB5gEDkAshAMYAWOWAzjALQPAAnXAE9YAUSogcAiAFsc0MHQA05UrgBmtWHWYKw0umoC-qiqgroDNegFcQUgQQCKAZlgBqWAEYAdAFZYACpYAElnACVYAB1oLGAAd2kXb1geHwDgsMiVNXQAI0EAE2kAYWB4px0AYgBOetzLWEKBEoEAdQgisFYCbzNLazAAZTBhXAILJtgNGDB2nAgAc1ZtOmhBWQBDLEbp2cVhiAAvfB8AFgGmrAhoHAAJRZXtACYABjzYU0_NNe83gCkewoYFA9FqgKMFGMJAAugMilswFtODhtMRzJ8APRY2AgARoyDSHjLDYEz7cWwCPQEDHTel09BvK6wZlqNkUDmkLlMlk81l8wVqADsLNFIpZLxeYpQsM-TTl0JZUxBAi20E4swEskm8owwik9EKkniShZFGYMA0y0msAgBlkADktvIAGKbJEGKp0aj45AANx2thwxjoX0-MKVahVpA0AmAsgAIkiUWjQtASlQ-uaZvHZAAVNUarWyCI4Ti2LDabwmOEDUEVSAgXWq5ZLZI6e04WTA2BbKgQTgABWAty9LcGBrOdE4rC2RUSUNI3woJc90gAFCAtmrZJwAJRkJqWjUVHC-eJLLc7l0H2voFewJYyIoT9C_ej_IEsmTPT-QllCjAUEdR0bx_CBEhHyoABBAdODffVDR0ZgkRwJZBGEXtClsDMd2EABxLZmwwARgxZaAXRwIiSNcflOBAG4wBggktkQ9BZ0SAgNB2VETBZBimIAGVuM4Yw41guJmXicHvL4BmEODB0QsZkLoQMsGDXtKPkegAGtZCxThYFkW5bGMl56mUN4bN7QT7RYnA2KPSxOISAgwDI2ToSggZURkctaWjT4dOnY1GOAM1PlUsLgBNSLe3QRFkVRMB00zPo5LlYwAG4gA

### Steps to Reproduce

观察图中的数据

### Current Behavior
[
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    7,
    7,
    7,
    22,
    7
]
这样的一组数据 最大值明显是22 但是返回的结果却是['expr 0', 0, 0, 0, 7, 17.5]
![image](https://github.com/apache/echarts/assets/26429903/f7bfae7c-ec4d-41bb-86e2-7554a8cc257a)

### Expected Behavior

结果返回正确

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
Missing the outliers series from the second dataset ? Add ```{ name: 'outlier', type: 'scatter', datasetIndex: 2}```
📌 please close issue if problem solved.
