### ISSUE TITLE
[Bug] Dt[_t] is not a constructor

### ISSUE THREAD

**Issue by bhavyakelp** [apache/echarts#19921]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoW7YCIDmAnCAJpgFzJoYWYDOAFsAO4mxi4CuApgDTkXqYA27AGZgmADm68MmfNhqjSEnr0xhQ4yVKwAjYGDUBbJgGYADJqmYAxjDABDCNAAyd7e35MWHCyt24C7LgA6oRgNEwAjD6UfgG4AMLA_MC4TJgAxPEA7PEAYgAiuZjKAL4-AuzY7NBEpKhaWHb8ENjQaYIimNHSKRDVClh0-ABetk1dyjF6hkzmk9IEdvZMANrzUvUNWpjQdgbsaQCCE1vbEGDsBgDKYACegkybpw3WSSlp6QBMEca5YqbFZ68ErrYHdDagl67fZpABCJyB0nOlxu9wOdUhz1eyVSpAyAFZPvkACz5fKAxHoEFAsqY9BPRE7PborDxLDgraYZHXO4PDGUyw2HEfXKHABsxIlFMp1OesqkAF0OVyLgYABLsFrySJzF4XAAeYFRfLIQOx7zxXyyn1hxgAogjTpghLYrhBhiyIqZQfLYLTKGokpAQI9QdQ6IxSF4uGG7CAQNUCAAVYCw4AEW6eNgxl4gOwEAiObCzZWxQKJYWWz7W20O0spOIhAhhSLKg1G3kshkvIUWrDpISDoeOzku6BgXJ7CD8TN4w4AN0C9lgNzsNTs_hHLzHRvdnuJPtLdisAGs8MBWDUK32MtWbfbpX7yvrDvqIFRQ3rbgm0lYlpUUkzZVFmWUg1jNT5TAiMQt22SCIgATlgyxIMg5CVFQiJ0MoVDPkfCglVjN8qBcNwPH5LFaAYLNvDpLBHAuXB53GUhdSxHc3Q9HUOUoPMCyLVY6IoYkeK0NjKXExFvSBQizR3ScDGnWcsAXJc7BXex103US-B3IJNTkAZiVMSSezeXF-wQ4kELFBC6zo51XU7NJziaCArHwjB_W2OxiKcRwuwcqjI1gIQmiodhDyI98k3ck9P0oiMmDC_gIp0xpmlaEIwlI9waMihpvMsKgQGaMB_OgQKzWC5LwoKrRfSKrBblfd9BIabttjuH88WY_gOGw6RdEvRZcFuABxON2oFTAvQAUkGyx5s8xV0swXz31y8jTRmmqo2zdLKA4vduKE6R5KnGcjkXXBl1XLSiEO87bH0rUjJMp6-F7CyCU-fEsjFLC6Kal4NpIgKEspcNqNIFKIuBtawdi09IcZPbQrqz6MpaaBspoLb8oRoLSvOCqqt2pLYbq4Goo6hzupZTA-oGtbhq0iaprAs6-GWrHZtMBa6NkrEwYJiiofR6M-eOrjSC9aXbAUpTrrUjS11Gx7uawPSDO1UhjNMrFvo-Ql_sBlawQc0WIfFtHKYx1L6tOEGfOI5H4tt6r7bhnMZrcrLznx1w8v2jgieqknyptnaJe96maR9ZRhb4CL8HYD8ubps0GbSbQN0WnQNybFtSE-MU1uhRnjjWkC7GmylOqh5mWVs_EADoIklWysYoLWMD72AB74bljXJgVtjLYJQnCVie-2Y2qx-P4ATnyxJ-vH6WDXEqN36AuzUngAlfMIFYDPYHA8fnk-VethvoetkNq_eGk5_eAVB_fRpLHG8ZZumFsmIDuxhjJRAfkPAeD8VQomcp7N-mBJ7FxnrAJ-V9zQ_S-Evf4-8sTr3MmkLe0Ad64D3rfKY_hAjH0LGfeub8pD3zoQ0BhjCpCoLoa_FhH86FfzlD_KB_9SBijEFkYB-JAa3wgc_KBI9YEx0YQghsgQkElgfpQBe_Zvi_GwWQoaiiEj4LxIQ4hpDVG6IobgKhp9z6XxYRQZhtiMD2IcSgnRrDTHoC4W_Hhzs-F0KZk0Aa-tPjGDbsYMQxIRLgLfpAvxMi0Soz8Yg6eKiHHoI-Jo5eOCnR4MrFgIxeYSHjiyZyI-J8aGZ2cegJxDjqm2LYW_DhjDPHP28VsF2pxf5mgEbAYkf025ik-GITuEjolSNiaqUeCT4FJObMg-pUN1G3iwSvdxOg9EbwIbgbeBSTGpNKdQ6xqy7GuN4LUlh8yr6NLoc0q-rTCpCzWi1YiABJGo7B9QpKxJcEANA7BUDanAp0hYqCuEELUZg2Zw4i2gBAAwSwoBtFDr7J0a5YXwpgEmGgJCqL8HBV6D6VsYVwsgDAfIrAtkksRbAH4BKzSouJQiu0fyBJ4gAI6sHzBS9yryLbtLkV-HqhdUisyLsk0u5cHKVzhAXTAtdaFAk6Vibp3w26DNspBEymqTJnKBJIq-0iJmyMVVDGZJcXGrLSZaQkJIyTFJeDkm8-Td5FJOQo8xljykXyOY4k5xzvXoAuePK5b8bnjzuQ1Xx8DlXt07lZUwCEE2JoTWIHVzw9XjwNTA-JgK0Gmrma6xZ6RrWknJK6h1m8tlEJ2S6i1-yrHytsamt-Tbn6BoFMG5-oaBThqkHyrOUaAksmCW3BCxgEJZHxVqkyWRjCr3TQKTNPJs38umXo5Rs8LWFuLbast6yDF5MrcYmtey9EesOZUqpvqfX-vNRelBqyu0yi1n2rQxrOTdIiGKNuM7CRiinZqltDR52UkXZMnN483WNjFbe2xlr-zbtLbWvduTVCHuraIXd7qynnovYB8eeH21XoDQ-z-z7I3P38f1T0Iihn4nCUmhjc7Rn6vGVmk0b6D5rug22p0W6iQlrtRPZDjq0POow0hrDByG0sII5SWTUkiP3ocY-xEPbgQPIck898ryAgfI3Wab5vz_nnw4wsd8oL2DgujFClFRL0VUqloStFlLMXYroLinUtLoXOYRWSrlMBIhmAuetOzlKmX_OgMWNlHKCBcqsDy2mr76bfkZs0SqMq5UVIbvwwdTBiQjqGREDV_7EIjLGcxmU5G0HdPywDIRnwGOJrELOqJ5W2uqaqxB7p7dqzWXxP-6dLW6HAYXWGzrM0P1tygviYk_wBvfCyGVljFWOta1M5YSbER_rxsa8m4RS2M3DbDRps0Uq8TxBlVpqgOn3mtgcml9gYGV1OnoNBobM1C2iglFKPm5aRTiklMSC2FAX3D0Ncu9bWBPsA5-1rSD5Z90ZCHMOX7XHZmRBs5yQzzKTNw-BRZqzkLv5BVuAYXQ21rAQFwFYB4a0qCk_J5xFkSgvYMCuAzpI-VEahYRVzpzDKMVYvTu5vFmruc-dJeS-zkR-vBfpfZ8LLKsDss5fC-LbRE4ERQCUIAA

### Steps to Reproduce

The graph component that I intent to create is similar to the one shown in the link above.

### Current Behavior

Currently, I've developed a component named C1, which accepts data as input and renders it as illustrated in the provided code snippet. Subsequently, this C1 component is utilized in two distinct modules, M1 and M2, each within its respective components. The folder structure is organized as follows:

- Components
   |----- C1 ( my echarts graph)

- M1
   |------ MC1 -> C1

- M2
   |------ MC2 -> C1

The issue I'm encountering is that while the graph functions correctly in M1, it fails to do so in M2, despite both modules receiving identical data for graph generation.

The error encountered in M2 is:
``` Dt[_t] is not a constructor ```

In the C1 component I initialise the graph using the following code snippet
```
this.chart = echarts.init(
      this.elementRef.nativeElement.querySelector(`#my-chart`),
      null,
      { renderer: 'canvas' },
    );
```

This image gives a detailed explanation for the issue faced.

<img width="1211" alt="Screenshot 2024-05-10 at 4 03 30 PM" src="https://github.com/apache/echarts/assets/147727230/48a558e2-1241-4cc8-80e9-0c2898f4152a">

### Expected Behavior

Ideal behaviour is that it should work in both the modules.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
See if the [FAQ](https://echarts.apache.org/faq.html#others) helps.

**Comment by bhavyakelp** [comment]
@plainheart Already checked the existing docs and support, but could not find anything constructive

**Comment by plainheart** [comment]
Did you import and use the renderers, component and series?
https://echarts.apache.org/handbook/en/basics/import/#shrinking-bundle-size

**Comment by bhavyakelp** [comment]
Yes, it was some import issue. Imported CanvasRenderers and now it works fine. Thankyou!
