### ISSUE TITLE
[Bug] The tooltip arrow is not showing when the property "confine" is set to true

### ISSUE THREAD

**Issue by jgoncab-arte** [apache/echarts#19927]
### Version

5.4.3

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-simple&version=5.4.3&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6MMGAAbSCCKpSsPNuAA7kRgHEqOpCDAeBCQMHTOILz8sPQwAGYQ0DRkoVT24eQ4-F7JFNR0AG6Mrkq0-SR4VEZUhLCiyd4-sEJgIm0AjABMAAw8sCOjsP0ArJMAHJMA7JP9_SsAzMPW4T5l2bQARowcdT52JLZ2ANxAA

### Steps to Reproduce

1. Set tooltip.show to true.
2. Set tooltip.position to 'top', 'left', 'right' or 'bottom'.
3. Set tooltip.confine to true.

### Current Behavior

When tooltip.confine is set to true the arrow of tooltip is no longer shown.
![image](https://github.com/apache/echarts/assets/169657500/897904c8-6297-414f-a6c7-a8d36ecaecdf)

### Expected Behavior

I was expecting the arrow to still display as it does when confine is set to false.
![image](https://github.com/apache/echarts/assets/169657500/c1f96270-0d92-4061-a410-b4b3c9da6641)

### Environment

```markdown
Modifying the examples provided in https://echarts.apache.org/ . For example: https://echarts.apache.org/examples/en/editor.html?c=bar-simple&version=5.4.3&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6MMGAAbSCCKpSsPNuAA7kRgHEqOpCDAeBCQMHTOILz8sPQwAGYQ0DRkoVT24eQ4-F7JFNR0AG6Mrkq0-SR4VEZUhLCiyd4-sEJgIm0AjABMAAw8sCOjsP0ArJMAHJMA7JP9_SsAzMPW4T5l2bQARowcdT52JLZ2ANxAA
```

### Any additional comments?

It also happens when I create a function for the property tooltip.position even when it returns 'top' and it would be nice that at least in this case the arrow would still show. I have a case when I use a function to decide if I want it on top or on the right so I can not use simply a string to set that property.

**Comment by Ovilia** [comment]
This is intentional. Because with `confine`, the tooltip position may probably be changed so the arrow won't pointing to the data any more.
