### ISSUE TITLE
[Bug] echarts 5.3版本开始  柱状图 BarminHeight属性设置无效

### ISSUE THREAD

**Issue by chenxingshuang** [apache/echarts#19920]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack&version=5.5.0

### Steps to Reproduce

柱状图 直接设置minBarHeight 没有生效

### Current Behavior

没有生效

### Expected Behavior

最小高度生效

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
See #18327
