### ISSUE TITLE
[Bug] xAxis "1" not found

### ISSUE THREAD

**Issue by rr210** [apache/echarts#19928]
### Version

5.5.0

### Link to Minimal Reproduction

无

### Steps to Reproduce

const xAxis = [
  '星期一',
  '星期二',
  '星期三',
  '星期五',
  '星期六',
  '星期天'
];
const bar1 = [10, 2, 0, 4, 5, 6, 7];
const bar2 = [8, 9, 10, 11, 12, 13, 14];
const bar3 = [0, 0, 17, 18, 19, 20, 21];

function dealBar(arr, name) {
  const bar = [];
  arr.forEach((item, index) => {
    const data = [];
    for (let i = 0; i < index; i++) {
      data.push('');
    }
    if (item) {
      data.push(item);
      bar.push({
        name,
        type: 'bar',
        xAxisIndex: index,
        barWidth: 20,
        data
      });
    }
  });
  return bar;
}
option = {
  legend:{},
  xAxis: xAxis.map((item, index) => {
    const data = Array(xAxis.length).fill('');
    data[index] = item;
    return {
      type: 'category',
      position: 'bottom',
      data: data
    };
  }),
  yAxis: {
    type: 'value'
  },
  series: [
    ...dealBar(bar1, 'bar1'),
    ...dealBar(bar2, 'bar2'),
    ...dealBar(bar3, 'bar3')
  ]
};

### Current Behavior

[Bug] xAxis "1" not found

### Expected Behavior

分组过滤为0的 不占位

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
maybe [this code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAHgQTgSwjAvDA2gckPhmg-OaAAcjgDQz4GAxcmRYYJBytlgKXJOGC2imwYJSaOAugG4AUKEiwARgEMATgEYM2WQAZyAJnIqYAFnIBWcgDZyAdkEjw0GFOmqFWABzkAnOWWvZr9TFkBmV1rNRS2sfO01NWWNXR28XGFVNVVkzEAAHKGRwBQBvIRgYABsAUwBzIrAAEwAuGGyAX1I8-CRUGtz8_KgAT1SimpxgSShSkGkusib81JAIZAzwfvEQKCgQAFsJjpgKockaxBQIJoamrpaINpP8iCLpZCKL7EnamG7exZlaHag9qxl5K4dbKvHp9CjWL67GrWWyA_LAt5gnAQ8jfX4hGB1Jp8IR1ARAA) will help
📌 please close issue if problem solved.
