### ISSUE TITLE
tab快速切换导致加载重叠，怎么解决啊

### ISSUE THREAD

**Issue by zhaohuaT** [apache/echarts#19922]
### Version

echarts": "^5.3.3

### Link to Minimal Reproduction

https://fanyi.baidu.com/?aldtype=16047#en/zh/issues

### Steps to Reproduce

快速切换快速切换快速切换快速切换快速切换快速切换快速切换快速切换快速切换快速切换

### Current Behavior

快速切换导致加载问题
![哈哈哈哈](https://github.com/apache/echarts/assets/20346995/e3c3c77a-a517-4300-9c6a-c11392f819fb)

### Expected Behavior

不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠不要重叠

### Environment

```markdown
- OS:
- Browser:
- Framework:
vue3 ，    "echarts": "^5.3.3"
```

### Any additional comments?

无

**Comment by deftliang** [comment]
The link to minimal reproduction seems to be incorrect
