### ISSUE TITLE
[Bug] 折线图纵坐标值不对

### ISSUE THREAD

**Issue by woxiangbo** [apache/echarts#19945]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack

### Steps to Reproduce

1.打开链接 https://echarts.apache.org/examples/zh/editor.html?c=line-stack
2.鼠标移动到倒数第二列，可以发现 最大值是Search Engine的1330，但是左边的纵坐标的值 已经是  2500了

### Current Behavior

y轴上的值不准确

### Expected Behavior

折线图上的点的值，应该在Y轴 值的范围之内

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by GetemJay** [comment]
这是堆叠图 先看文档吧
