### ISSUE TITLE
[Bug] The "backgroundColor" covers the entire map when any scatter data is on it

### ISSUE THREAD

**Issue by daxiaraoming** [apache/echarts#19949]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap&theme=dark&code=MYewdgzgLgBAJgQygmBeGBtAUDGBvGMBAWwFMAuGAckHdbQC9SqAaGANwQBsBXCmATgEYYAX0Y58hEjyqAgRMAoOoCxNQPWmTVh26V-AJkEisAXQDcWUJFgBzUiADCIEACc4AWQQAHNPjH1KGLfwB0_ACszADM_gAcvHqiuHJK3vwADLx-AOzh_CGaqaEpAGyJ4Zp5edFYQkYm0DAmLKR2UAAiSCjoAGacYMBQAJbgMAAUiMgAlB64bHYwdqQQ7hiGYm32g5MwPe6JBuswADzwLX7spGBmUAAW2z0A1NdjeGITCFMW1rYO7q829k6uGMMIDA9PR-IhkRa4XA9NqDL7vOD3R6QmYQPwuTgQc4DB6Q3ESMiUAFAkFg0gxPFPLg8OE_PwmYBIIYtYl-NhUkZI3BCEZGXFCMT83AzKCcOxgaazIwVLAgFy9froHEwAD0ypggFg5QAFSoBN-MAp8qARh1APRmgAtFQCLeYAQtzEqpgACMEMAANZmOwgTpwGzseyUKhQOwISAuZ4nKBMMRh3C9KDHShKiOkAAeUG9xsAv2qAbjlAIGRgDn1QBAeoAvL0AKDaACljAPOJMAAtDBAH5ugDK9QAM6oA_tVDuIgnBtUATSeoAJgbRdxBgAAVHJpAn4emBm5DWzb2BOHd7zlAoC5yKqAO6btHEUfjyfk3DHNpdqjAYP1KgC8lQWzsXqr8aQ309MwWOzenod4iXrnkm3EVwYyRM8wA7d9MCSAAWAJ-EgrReFCVI_ECQJEhCEIogPGAAC9bGIShgiRF0SEoX1uCvMQIHqHpZm8JFYyfABPFwpAgBllwvLDcFAH4JyQUgAGVGOgUh8Oof9XCnXEAUoWp6iaFomVGLiYAgRjiBtEB2AEnpsJ4DounlcUBjZREKSFUgRTFVR2AwTQ9BVGAkl5PFdApE5QDgHgGNxNl1BgTROWEFT2AQG1SHYIDzN7ewAI48CqDwG0hCkvEXBACBPz6MBvTsF8l1SltzhAddKDaDgqKCty8VElxzgQTKICi8zQvCyLH2izEStIuxyOiwVXKRaq9HKAwgA

### Steps to Reproduce

Just open the Official Example like [this](https://echarts.apache.org/examples/zh/editor.html?c=effectScatter-bmap), then choose the dark mode

### Current Behavior

The "backgroundColor" covers the entire map when any scatter data is present, using a custom theme that defines the backgroundColor.

### Expected Behavior

`backgroundColor: 'transparent'` by default in any theme

### Environment

```markdown
- OS: macOS 
- Browser: Chrome
- Framework: Vue@3
```

**Comment by plainheart** [comment]
如你所述，覆盖设置 backgroundColor 为 `'transparent'` 即可。ECharts 是覆盖在百度地图之上渲染的，必须将其背景设置为透明，否则将遮挡地图。

**Comment by daxiaraoming** [comment]
> 如你所述，覆盖设置 backgroundColor 为 `'transparent'` 即可。ECharts 是覆盖在百度地图之上渲染的，必须将其背景设置为透明，否则将遮挡地图。

官方给的dark主题中backgroundColor没有透明度,也没有相关说明。使用自定义主题表现为没标点时地图正常,有标点时全白,我被这个奇怪的问题困扰了很久,我建议在文档里添加说明。
