### ISSUE TITLE
Can the yAxis labels sit on top of the splitline?

### ISSUE THREAD

**Issue by 27pchrisl** [apache/echarts#19952]
### What problem does this feature solve?

Hi, our designer has come up with the following design that I am unable to replicate in echarts where the yAxis label is sitting on top of the splitline

![Screenshot 2024-05-18 at 13 45 46](https://github.com/apache/echarts/assets/6286310/9ec7e614-f26f-44f1-a987-6b585ffa700a)

Using this configuration I can move the text to the correct position:

```
'yAxis' => [
  'axisLabel' => [
    'padding' => [0, 0, 3, 0],
    'inside' => true,
    'verticalAlign' => 'bottom',
  ],
],
```

![Screenshot 2024-05-18 at 13 47 31](https://github.com/apache/echarts/assets/6286310/3b1417d3-dbb1-4dca-82ae-44c659246db3)

But I cannot figure out how to move the line series so there is some margin on the left to prevent overlap.

Is such a design possible with echarts? Thanks for the great library!

### What does the proposed API look like?

Ideally there would be some way of padding the splitline to overflow its container, or adding internal margin to cause the chart to start in a different position, or adding some sort of margin to the xAxis to do this?

**Comment by helgasoft** [comment]
> adding some sort of margin to the xAxis to do this?

yes - [boundaryGap](https://echarts.apache.org/en/option.html#xAxis.boundaryGap), see [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=M4EwBAvGDkBMAMsAsBaeBGFsCcAVeAHAFzzwnwBa0A3AFAgCGALg5GANoC6dAZgPYAnMAApaYMIyYBTNgDspAdzAARZlOGgAlHXGSZAHijylq6cLiJUiNAFZo2sRLUA6YFKan1e5wHN3n4U0wAGowdE1aIIBvR0kGZwAHAFdgAAthdmMVNWE9TQAaMABZZlTnAQZZED4AW0CwACow0k4HAF9aWj4EpgBLPlk2GPEADwBBEd7gIjBh8TAmAE8EqRnoPpqpaHzHcQAjPiSqhgFFgHEGBJn2aHR4AFJtmDvHzh35sAZJ4AAFPl7ZNIBDMomA0nwFDMmAIklJCsBZJcoTCZB1xG13mBFhMpiDdmCEgAbXpMAAyANWszAxPkAGUloTKaCAMZ8QmCNYCKQgaBgNp8zHiL5TUkMPZSQl4j7iBIMEAgAE-a7wQoqsAAZlVb3x4gBwF6IEp0NhgvmADcpAI-syGISxsSfLI1gcmExatB8WiBY43AJelJphxQUsVmsaVtCnEZnE-ZxaG1qEA)
![image](https://github.com/apache/echarts/assets/13038071/a0255a8e-e38a-4c46-9d08-d2f803ac10f6)

**Comment by 27pchrisl** [comment]
Perfect thanks @helgasoft ! The additional thing I missed that was in your demo was to use time series, I was using categories before.
