### ISSUE TITLE
[Bug] Some example charts are not able to load in Codepen and Codesandbox

### ISSUE THREAD

**Issue by cavalia88** [apache/echarts#19950]
### Version

5.5

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/les-miserables-h6ss7x?file=%2Findex.js

### Steps to Reproduce

1. Go to example charts:  https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout
2. Click on  icone "Open with Codepen" or "Open with Codesandbox"
3. You will directed to Codepen or Codesandbox page
4. You will see a spinning blue circle with "loading" message. Stuck at loading page

### Current Behavior

1. Go to example charts:  https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout
2. Click on  icone "Open with Codepen" or "Open with Codesandbox"
3. You will directed to Codepen or Codesandbox page
4. You will see a spinning blue circle with "loading" message. Stuck at loading page

### Expected Behavior

Expect to see the graph load properly on Codepen or Codesandbox page. Should be able to see the same graph as what's shown on the https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout page

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework:
```

### Any additional comments?

Was trying to edit the graph on Codepen when i came across this issue. A few other "graph" type charts also face similar loading issues

**Comment by plainheart** [comment]
It's because our website limits access to resources from third-party origins. You can download the file required in the example and replace the URL like `ROOT_PATH + '/data/asset/data/les-miserables.json'`.
