### ISSUE TITLE
[Bug] 谷歌浏览器升级后，canvas内容白屏问题

### ISSUE THREAD

**Issue by heyang1014** [apache/echarts#19955]
### Version

chrome:115

### Link to Minimal Reproduction

nope

### Steps to Reproduce

1.浏览器为115版本
2.打开使用echart的页面
3.切换其他的站点，多切换一些再切回带有echat的站点
4.发现canvas画的内容是白屏的
5.关闭浏览器的硬件加速就不会有这个问题

### Current Behavior

关闭浏览器的硬件加速就不会有这个问题

### Expected Behavior

关闭浏览器的硬件加速就不会有这个问题

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
Duplicate of #19946
