### ISSUE TITLE
[Feature] Can I customize the color blending effect？

### ISSUE THREAD

**Issue by PUYIXIU** [apache/echarts#19961]
### What problem does this feature solve?

Can I set the superposition effect of translucent colors on the same chart?
 For example, I want to achieve a deepened effect when two translucent colors are mixed,
 rather than one color covering the other color

#### Effect I Want
![design](https://github.com/apache/echarts/assets/56141200/26d77ff2-f6b3-48fe-8de5-9ec5f5f2f5a8)

#### Effect I Achieve
![real](https://github.com/apache/echarts/assets/56141200/64f605fa-9b10-4428-b505-936fff27e52b)

### What does the proposed API look like?

I wish color blending to achieve a similar effect to **canvas's globalCompositeOperation api** , or **svg's feBlend filter** effect：

**Comment by nielskrijger** [comment]
Did you manage to figure out a workaround?
