### ISSUE TITLE
enable tooltip only for lint point of area chart

### ISSUE THREAD

**Issue by karthik-noveau** [apache/echarts#19960]
### Version

5.5.0

### Link to Minimal Reproduction

https://github.com/karthik-noveau/e-charts

### Steps to Reproduce

1. npm install
2. npm start
3. hover on the area chart 

### Current Behavior

tooltip is enabled for both area and line point

<img width="942" alt="image" src="https://github.com/apache/echarts/assets/82690268/ac31945c-b237-4223-981e-063f98a044e5">

### Expected Behavior

when mousehover on the line point, that time only, tooltip should be enable

<img width="751" alt="image" src="https://github.com/apache/echarts/assets/82690268/4ef79553-91ed-441e-b3ea-3add94895c84">

### Environment

```markdown
- OS: macos
- Browser: chrome
- Framework: reactJs
```

**Comment by Ovilia** [comment]
Can you provide more information on what you expect?

**Comment by karthik-noveau** [comment]
> Can you provide more information on what you expect?

I requirement is , when i hover on area, tooltip should not show
but I hover on the Line Point ( circle ), that time only tooltip should be display

**Comment by plainheart** [comment]
Setting tooltip trigger as `'item'` may meet your requirement.
