### ISSUE TITLE
[Bug] OKLCH css color blocks blink when mouse hover

### ISSUE THREAD

**Issue by Reverier-Xu** [apache/echarts#19976]
### Version

5.5.0

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/monochrome-sunburst-v3f8ys?file=%2Findex.js%3A11%2C30

### Steps to Reproduce

1. fork the example at official sunburst.
2. change the item color to [`oklch()`](https://bottosson.github.io/posts/oklab/) colors.
3. move mouse to select one block on the charts.

### Current Behavior

the block starts blinking and can not selected by mouse.

### Expected Behavior

act normally as RGB blocks.

### Environment

```markdown
- OS: Arch Linux rolling
- Browser: Microsoft Edge 125.0.2535.51 on native wayland
- Framework: any
```

### Any additional comments?

[spectacle_20240525_181133.webm](https://github.com/apache/echarts/assets/41937333/d794f9c7-3a2a-4a2d-8a54-cfbfec4681c8)

**Comment by plainheart** [comment]
ECharts doesn't support oklch colors. See https://echarts.apache.org/option.html#color

**Comment by helgasoft** [comment]
@frenicohansen, blinking solution is to put ```itemStyle:{ color: 'inherit' }``` in _emphasis_.
@plainheart, _oklch()_ color format is definitely supported, but **how** is still a mystery, see discussion in #20757.
