### ISSUE TITLE
[Bug] Echarts地图加载自定义地图展示时，在V4.8以V5.1表现不同，V5.1出现名称位移到左上角

### ISSUE THREAD

**Issue by zenta777** [apache/echarts#19974]
### Version

>=5.1

### Link to Minimal Reproduction

https://codepen.io/zenta777/pen/rNgLbZz

### Steps to Reproduce

这里有一个demo示例。

[EchartsDemo.zip](https://github.com/apache/echarts/files/15426204/EchartsDemo.zip)

### Current Behavior

地图上的点没有标签文字，看左上角出现了这些标签文字。

![image](https://github.com/apache/echarts/assets/15935108/3f7315fc-31fd-4a56-98b0-88c98f21cbed)

### Expected Behavior

![image](https://github.com/apache/echarts/assets/15935108/0b5055bc-50aa-49a8-a058-af7aaab76554)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
代码过于臃肿，难以查看问题，需要简化下 Demo。
