### ISSUE TITLE
[Bug] legend.tooltip xss问题

### ISSUE THREAD

**Issue by lixm9881** [apache/echarts#19988]
### Version

5.3.2

### Link to Minimal Reproduction

https://codepen.io/lixm9881/pen/vYwgREo

### Steps to Reproduce

<img width="486" alt="image" src="https://github.com/apache/echarts/assets/66252087/3ae8c347-a498-40dd-9946-a3b1365d861d">

### Current Behavior

<img width="1024" alt="image" src="https://github.com/apache/echarts/assets/66252087/b6db9ed3-e869-4a63-bf09-9d20b88dcae5">

### Expected Behavior

正常显示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
请详细描述下问题

**Comment by lixm9881** [comment]
> 请详细描述下问题

图例的数据中包含html标签时，鼠标滑过图例显示的内容被解析成html了。如截图中所示：
<img width="329" alt="image" src="https://github.com/apache/echarts/assets/66252087/e9793e9d-994e-422c-a371-2556d120556a">
<img width="893" alt="image" src="https://github.com/apache/echarts/assets/66252087/8840fa1b-15d3-427d-9f0a-a4f61d74df96">
