### ISSUE TITLE
[Bug] Print Functionality for an Chart Missing

### ISSUE THREAD

**Issue by sour1804** [apache/echarts#19986]
### Version

5.5

### Link to Minimal Reproduction

https://echarts.apache.org/en/option.html#toolbox

### Steps to Reproduce

Create Chart in angular application and add toolbox support for that Chart. 
Try to find the print support in toolbox or in chart it self.

### Current Behavior

No Print Functionality.

### Expected Behavior

Need to print individual chart.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
You can export the chart as image and print it. I don't think it is a core function that ECharts should provide.
