### ISSUE TITLE
[Feature] show minimum value in bar chart

### ISSUE THREAD

**Issue by alihamidy32** [apache/echarts#20008]
### What problem does this feature solve?

when we have bar chart whit outlier data for example green : 1000 , and blue : 1 ,we have serious issue in stacked bar chart ,and bar chart just show green because is too long and doesn't show blue just show label 
i don't need markPoint because i need to show integrated chart 
![image](https://github.com/apache/echarts/assets/45121837/a01a434c-2def-4dc2-99cb-982c916bad01)
![image](https://github.com/apache/echarts/assets/45121837/5d058fce-e9e7-474a-bba3-94d50fa0d5c5)
![image](https://github.com/apache/echarts/assets/45121837/d0c1f5cf-a0c8-4768-a963-e46cc35230ad)
![image](https://github.com/apache/echarts/assets/45121837/e8fd8f7f-15cf-4211-82ab-41b8130112f7)

### What does the proposed API look like?

i think just like minBarWidth and minBarHeight we can have something like that to set default width or height and just set to minimum or very low values.
Thank you

**Comment by Ovilia** [comment]
Stacked bar with minHeight may cause logical misleading problems so it's not considered.
