### ISSUE TITLE
[Feature] 希望Tooltip的valueformatter能够判断是哪个值

### ISSUE THREAD

**Issue by nyssance** [apache/echarts#20000]
### What problem does this feature solve?

假定我在tooltip上显示一些信息，那么价格是不要百分号的，幅度是需要百分号的，现在提供的很鸡肋。如果我条目少，我自己的写formatter就好了，我现在条目很多，但是又不能针对某一条去定制。现有的只考虑了不同系列的情况，某认一个系列就一个value.事实上，某个系列里面有十几项数据，xy轴之外，tooltip显示剩余的信息，才是tooltip的作用。
另外现有的valueformatter，数字格式化会加逗号，但是我自己value一下，这个逗号又没了，等于完全自己重做。还不如自己去写formatter，其实主要就是个对齐的功能。
或者就是加一个全局的百分号类型的解决方案，标注了这项是百分号形式，不管是y轴还是tooltip自动显示百分号。

### What does the proposed API look like?

(value: number | string, dataIndex: number, params) => string

**Comment by helgasoft** [comment]
_dataIndex_ has been added already, but is not documented yet. See duplicate #18997 with fix.
So this is working: ```valueFormatter: function (value, dataIndex)```
📌 please close issue if problem solved.

**Comment by plainheart** [comment]
The `dataIndex` callback parameter has been provided since v5.5.0 and can be found at: https://echarts.apache.org/option.html#tooltip.valueFormatter.
