### ISSUE TITLE
[Bug] Can't see brush button in toolbox

### ISSUE THREAD

**Issue by miyanyan** [apache/echarts#20006]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2&version=5.5.0&code=GYVwdgxgLglg9mABAJwIZgCZwLYBFVSoAUAlIgN4BQiiYcA7ogLy0Cmj-UrRA1HYz0QJW-AJ4kA3NUQA3VABsQrZrIVLEggLIEAFgDo0mHKUQAqRACYAjIgC0iKwAYpNZKyghkSKjRphU2KwAXLQMelBwAMpQyDBgAOakADTSNHKKwYgA2qm-Wfx68e4AYiDy8gCarKjIyaH0he6aCFA6JoJWSfWNUJzcJAC6egBWcHFEAOQA9BMkKb6-2q0GcOAYROlKJLkD0gC-UnuU8u6IGASoKlkDUidQ9Spg7Ih9RFYAnO8A7F3vXQDMkmOp2EYhUFgALGZEP8AGyORzQpwI26nTbKFhLfSGLDYEzmZHOSjAODIRAbGqIGAqZxUxAAHgcCNpMB4PDIPjOFz0AAcQABnNo4nCcYgkIFHOA82AIFSc2BQE4hTk0LgADygIQmuFE_mwMAgLwuiAAZIgACowQKIACCapg_Im-3miAicHksB5ytyMRg8SKyC1qHtjpdNBJyGwBC4gcQoEgMqQRB5NQC_I5uRoKbQ2H5KmzaayjhumdUZPOXEez1eBdzej1rCBC1c7k8SdLNArrB6rzIPA7iGmEw0A6IXZ6zTArXaDj7A6HI-bvnHRSgpXKVRq7XniC1i6XiFr_L06KyVl2S6bvj2YcQwYdAAUxlPWLGVb50FaCPAwCFgAp-VYXIjhoG9pDVO0HW9BYoFEHlMgmWBAgmW9-R5eQYCgAAZOJMnfGhBQYP8AKAhYQMQMCaFESD-Wg3xYPgrV0RQ3IACNVkwGpRAAcVQL1skcLoJmRABSCYBlQ9DMJwp46IWQj6GI-RAOA51pDdeR2LVOTEAUkIYiUW9gGqDw3B0zsLgALTgHBzN8aiQwASUwVhtLjEjb1AzzEFY5ABR0OzVTgzIsgmDCngADRQwcIBOGpxO8yjmwrVAADUYHYZUUGqDAAHkwHkUR9L85Qkvk1AZFYG1-UcqMimVMqKJdJLfP8nSIKcly3ImBR5BYhZWsFGSAGsg3KfrfFWKBcuAAAhPzBTsiB3VJG15B5HRUBCRw9CsVSvOkQDYlYWjslyfDaACBDilQYblFFCaYOCrVwtYR7fAUyJRGwdj5CUwDvJSkIUv2xBdgOShAKgZyY3SIh42gH9yQzcNSXJOQyWpFgWQZRAAFYJCpNkUeXblBRgYAoFIFxScIXl_KIYU8AuUgr3I7BRAAYU25AoD0KHculH8iHfI6MtOnIlwuizCGBi5S3ImgLwoiUukJSQgA

### Steps to Reproduce

1. First of all, the brush button is shown in the link above
2. But when I download the ```echarts.common.min.js`` from github release https://github.com/apache/echarts/tree/5.5.0/dist
3. then write a html and copy the code to html and run it in edge, the brush button is not shown

### Current Behavior

This is the code in my pc, it's a copy of the ```Dynamic Data + Time Axis```, and I add brush to ```setOption```
```
<!DOCTYPE html>
<html style="height: 100%">
<head>
    <meta charset="UTF-8">
    <script src="echarts.common.min.js"></script>
</head>
<body style="height: 100%; margin: 0">
    <div id="main" style="width: 100%; height: 100%;"></div>
    <script type="text/javascript">
        var chartDom = document.getElementById('main');
        var myChart = echarts.init(chartDom);
        var option;

        function randomData() {
            now = new Date(+now + oneDay);
            value = value + Math.random() * 21 - 10;
            return {
              name: now.toString(),
              value: [
                [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
                Math.round(value)
              ]
            };
          }
          let data = [];
          let now = new Date(1997, 9, 3);
          let oneDay = 24 * 3600 * 1000;
          let value = Math.random() * 1000;
          for (var i = 0; i < 1000; i++) {
            data.push(randomData());
          }
          option = {
            title: {
              text: 'Dynamic Data & Time Axis'
            },
            tooltip: {
              trigger: 'axis',
              formatter: function (params) {
                params = params[0];
                var date = new Date(params.name);
                return (
                  date.getDate() +
                  '/' +
                  (date.getMonth() + 1) +
                  '/' +
                  date.getFullYear() +
                  ' : ' +
                  params.value[1]
                );
              },
              axisPointer: {
                animation: false
              }
            },
            xAxis: {
              type: 'time',
              splitLine: {
                show: false
              }
            },
            yAxis: {
              type: 'value',
              boundaryGap: [0, '100%'],
              splitLine: {
                show: false
              }
            },
            toolbox: {
                show: true,
                feature: {
                    dataZoom: {
                    yAxisIndex: false,
                    },
                    // add brush here
                    brush: {
                    type: ['lineX', 'clear'],
                    },
                    dataView: { readOnly: true },
                    saveAsImage: {},
                },
            },
            // add brush here
            brush: {
              xAxisIndex: 'all',
              brushLink: 'all',
              outOfBrush: {
                colorAlpha: 0.1
              }
            },
            series: [
              {
                name: 'Fake Data',
                type: 'line',
                showSymbol: false,
                data: data
              }
            ]
          };
          setInterval(function () {
            for (var i = 0; i < 5; i++) {
              data.shift();
              data.push(randomData());
            }
            myChart.setOption({
              series: [
                {
                  data: data
                }
              ]
            });
          }, 1000);
          
          option && myChart.setOption(option);
    </script>
</body>
</html>
```
And when I run this html in edge, the brush button is not shown but all other toolbox buttons are shown
![image](https://github.com/apache/echarts/assets/40262194/6a3c6d94-5d36-4577-9100-584493e3f953)

### Expected Behavior

![Uploading image.png…]()

### Environment

```markdown
- OS:win11
- Browser:edge
- Framework:
```

**Comment by helgasoft** [comment]
Try using a public _content delivery network_ (CDN) like https://cdn.jsdelivr.net/npm/echarts@latest/dist/echarts.min.js, instead of downloading from Github source.

**Comment by miyanyan** [comment]
> Try using a public _content delivery network_ (CDN) like https://cdn.jsdelivr.net/npm/echarts@latest/dist/echarts.min.js, instead of downloading from Github source.

This works well, but I wonder about the difference, maybe this's no icon in the github release?

**Comment by miyanyan** [comment]
I found that I'm using ```echarts.common.min.js```, After I changed to ```echarts.min.js``` the brush button is back, so the brush function is not include in ```echarts.common.min.js``` right?

Is it needed to log some waring messages when someone uses the brush function in ```echarts.common.min.js```, this may help.

**Comment by plainheart** [comment]
`echarts.common` only contains common components and series and `echarts.simple` is like this but contains less components and series. Use `echarts.js` or `echarts.min.js` if you hope all features are enabled. The `brush` feature depends on the `BrushComponent` which does not exist in those two entries.
