### ISSUE TITLE
[Bug] 点击拿到地图中markpoint具体的参数

### ISSUE THREAD

**Issue by wangrui333** [apache/echarts#20018]
### Version

5.1.2

### Link to Minimal Reproduction

https://github.com/wangrui333/123/blob/master/index.vue

### Steps to Reproduce

   var option = {//市级数据

        //地图配置
        series: [{
          type: 'map',
          map: name,
          zoom: 1.2,
          top: '10%',
          x: 'center',
          label: {
            show: true,
            color: '#770928'
          },
          itemStyle: {
            normal: { // 静态的时候显示的默认样式
              borderWidth: 1, // 边框宽度
              areaColor: '#C0C4CC', // 地图颜色
              borderColor: '#ffffff' // 边框颜色
            },
            emphasis: { // 鼠标移入动态的时候显示的默认样式
              borderWidth: 2, // 边框宽度
              areaColor: '#909399' // 地图颜色
            }
          },

          markPoint: {
            symbol: 'circle',
            symbolSize: 15,
            //文字标签
            label: {
              show: false, //是否显示标签
              position: 'top',//标签的位置
              color: '#ffffff', //文字的颜色
              fontSize: 12 //文字的字体大小
            },
            //标注的样式
            itemStyle: {
              opacity: 0.8,//图形透明度。支持从 0 到 1 的数字，为 0 时不绘制该图形。
              color: '#ffffff'
            },
            silent: true,//图形是否不响应和触发鼠标事件，默认为 false，即响应和触发鼠标事件。
            /**
             * 标注的数据数组。每个数组项是一个对象：{ name: '舒兰市', coord: [126.97170, 44.41223], value: '78', symbolSize: 10, },
             * name 标注名称
             * coord 数据在相应坐标系上的坐标位置 经纬度值
             * value 标注值，可以不设。
             * symbolSize 标记的大小，可以单独设置每个标记的大小
             */
            data: markData
          },
          data: seriesData
        },
        ],
      }
markData: [
            { name: '南京雨花茶', coord: [118.701323, 31.870489],},
          ]

### Current Behavior

![image](https://github.com/apache/echarts/assets/112047230/599c4d1f-5270-4bd0-9b3e-c6de45383917)
![image](https://github.com/apache/echarts/assets/112047230/a8612838-11f1-4af9-ac08-84db7befce6e)
没有拿到具体的数据

### Expected Behavior

拿到markData中具体的数据

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
想拿到什么数据？

**Comment by plainheart** [comment]
看了下提供的代码，`markData` 是二维数组形式，而不是对象数组形式，可以参照上述例子改一下。

**Comment by wangrui333** [comment]
> 刚试了下，可以正常获取呀？🤔 [示例](https://echarts.apache.org/examples/editor.html?c=map-HK&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QzhAaQQArJKkJSANKIBmAV0IBjOPmOjSmgFJHC5UQG9qo0aCQsIgQ-LiM2HhEZFR-ooy20PBICDCMxPhIcIwwALJQAA6kUrpmom4esf6BSYhqcOwFDsakcf6kqE2OhKIAvD5t_qIOcAA2jABcA0Mzw4wAHnBTUnydVqMK3aIAIoyESPhwIKKoFqLCxsSiOpeigBD_AEwADACML4CQ_2aDM0hWAEbZRbLbYKKCWGCoYCiADq-AA1vgCowCFAvrMhr8_qMiHCJt9ZlIIHA4AUJjIZAAvCAIdDwxHI_BQBCoGDEGS0hEyACkAFEAJxcgQANi5fIFPJFACEAByCgBivNlAheXOlYF5Ir5ABYuZKFTyAKyq7aqp68o3SgSqgDMAGJbIdGDxCKhsgBaF4PKT4gC-pnxcFQqFGDlJ03Rwxg-GITBgy0dwDREYsLOACmycek3j-PoAPH8YDIAHzeWw-5wFUQyURw4APcje9F-gNB0Z_VDzKa-COiFAYKZwGBWRj-nss_B7JbSABuOQctigoyT6PGFinUijxCJy9mgbDUlsk5yO5mFkYCisaS7-Jm8kUADUJ-gu6I0nh2IRRiAphZF2pRM2Pb-GkWQspMPiAUBSBQLOAhIAAkmmTBdj6N4Ab6o6zNOmRWIu-Rht2EbAEQUzSk8TyYeiaadqIBrkeRlG7gsU4ANolNGEBlFI2DoFIAC6jEzG-Ib4MA4G_qMaiCUMC6jLY6xQFi4GDsO0n-EQrBQCQ4GET2tjBiyUxsdiW5wEgcIgFiw5cSAjCjKMGBcSyWmxsi_FoahTbSWoUaMEgRlobpRGwHCqxEFOQU9neUABUBsyRXFoiEFAYnLIAUqoZSeiX6SyuBGW8WoIPRWoPOYDwPAgDzWtKLzagJaE9qAcoTqMeXSJ61qNol_iQd1CVxclqXSIA6sqADVygAXaYAjUGAGzBWVxTlMBtSxBVFeRJVlRV1rVbVWp8Q1syeYle1xb1EaDeBUiAJmZgD0di80qAFzKgBdcoAx8qAGPagBlenNQxHEiyxpgUX3VIUyylGpQwbH8dnXt1fbPpGw77ad6LRbFiXeElKUXYAtHKAP6R91lNOi7DlMzxPAaADsCDWlqAFgzM6PncsgB-doAK3IE0T4EvAaWrk5TWrSrT-3-AzmPLIAOHL4-YhOjMTojWi8QrSkKCAvILfUY0NUjDZLojS7LQpihVQpq2jGsXYAnTaAGg6gBfpuzMvgVqWpPFqBoIFqfIm3FIua4Aj7aACw2gDr6nbstO4rfIIEKNNIxG3sXYAunKAJn5gBz6sH4HWuTQoGuH5MC9H6Kx8sgAjeYA5JqAJtyqdTC7d1PAgfLk57QEF9IgBDkYAGhoV7RBrPIVDzG3n8Vm8sgCuIYASukdw8tXkbXDc9k3UiAMLBTMd-7d2VX3dNDHPgD2OoAF6kdwa0o1Qg0pRxvwuD9IgDCioA6ObLy8OdFar_f0xfUiAOjKOt6-B5UPJTfIPDPGOr9i6ABX1ce1da65zPj4V-gBMm0AAyuHc-T3wqtqQB-dX440AISxHctqK3QQPRm0hADdnoAbJ0O5kWVnyXO-16pxXJKIQAV4GACztQAknKAFgVQAD56AAIzQAIDr7XOvhaGiUpBgEnDARcogtK4BhH5DMJhli40lkLUQPIVDyPFso7q8EkAbEILgfyJDyHQKkDcdADknBgEOCAKQyxE4pxMTodAUB8CiC4AcEgtjpCj0BkMUx6AbBuMuF4qQbdfH-AAHIsjgBAZYH9wnSAAMouOuDYYgITsEJKkIk6AbiiAhIQVknJKVRA5KsK41YIT_ZB2gYk1AVgYk5EIMsbWWSuApMqcsUBbTfh7BhFpEJi82nDh6LkGwITd5ZOhFpUQQR8AhNZlM247TXGJPyUXMuWSACaUArBuIOFCXIwTlhW1tiYrZIzRDYE8csG-XUeyHSbPiY6QwfTkDiLEN5NBqA1GCMyQgxRbDYlsHCMo-l9jBkYAgByxAqBAA)
> 
> ![image](https://private-user-images.githubusercontent.com/26999792/338524439-7f922521-4c53-4fae-a408-772b934d748f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTY1MjcsIm5iZiI6MTcxODE1NjIyNywicGF0aCI6Ii8yNjk5OTc5Mi8zMzg1MjQ0MzktN2Y5MjI1MjEtNGM1My00ZmFlLWE0MDgtNzcyYjkzNGQ3NDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxMzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNzk4Njc5Njc2NDMyMzc5NzQ5MDg3ZjE2ZDI2NjNiZjRhZjE1ZjlhNjdhNjFmNDk2ZjlmN2I2MzEzYmUwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rI4ylH4OmNTmIFf4nkF6vMTfFakv3c56jLUEE9cXGzg)

多谢大佬，已解决
