### ISSUE TITLE
[Bug] Empty "params.seriesData" in axisPointer.label.formatter when using Vue3 ref() to store echarts instance.

### ISSUE THREAD

**Issue by meatjam** [apache/echarts#20012]
### Version

5.5.0

### Link to Minimal Reproduction

https://codepen.io/meatjam/pen/RwmZKOO?editors=0010

### Steps to Reproduce

1. Open Console in your browser.
2. Move your mouse into any area of the chart.
3. The console will display "seriesData: []" indicating that params in axisPointer.label.formatter got a seriesData with empty array.
![image](https://github.com/apache/echarts/assets/43535074/72bfd7f7-805e-44ea-941e-662843d72b66)

### Current Behavior

In this reproduction, I wanna get seriesData in axisPointer.label.formatter like these:
![image](https://github.com/apache/echarts/assets/43535074/22678692-2c06-4e65-8ce9-f9c0e0d078d9)

But I got empty array instead which is abnormal.
I'm using vue3 ref() to store echart instance.It may be the main reason.
If you store echarts instance in normal usage, seriesData will display as expected.

You may  switch to "normal usage" from here:
![image](https://github.com/apache/echarts/assets/43535074/dc6363d9-5bf2-4860-a99e-1e2f72f7f3d1)

### Expected Behavior

Get series in params.seriesData.

### Environment

```markdown
- OS: windows 10 x64
- Browser: 125.0.6422.142
- Framework: vue 3 + echarts 5.5.0
```

**Comment by plainheart** [comment]
Please don't use ref for echarts or any third-party instance, it might affect inner property access and cause poor performance. If you have to use ref, just use `shallowRef` instead.
