### ISSUE TITLE
[Bug] Candlestick border mode issue

### ISSUE THREAD

**Issue by matttttttty** [apache/echarts#20025]
### Version

5.5.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

              type: "candlestick",
              data: data.values,
              itemStyle: {
                color: undefined,
                color0: undefined,
                borderColor: this.upColor,
                borderColor0: this.downColor,
              },

### Current Behavior

<img width="289" alt="22" src="https://github.com/apache/echarts/assets/48928947/2e27f979-819b-41b9-8744-0187e3368465">

### Expected Behavior

<img width="492" alt="333" src="https://github.com/apache/echarts/assets/48928947/20b951ab-a593-443e-b68a-5df799946617">

### Environment

```markdown
- OS:
- Browser:
- Framework:
mac 13.1 (22C65)
chrome
vue2
```

### Any additional comments?

Hi ,can I remove the middle line in the candlestick when I just want show borders?

**Comment by helgasoft** [comment]
data order should be OCLH - [Demo](https://echarts.apache.org/examples/en/editor.html?c=candlestick-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurACYCGYFRA2gOQBMADAIwDsAtK854wCz0ANLCZsuPPgFZholh269GANlliFkxu3oBdEgF8hJAJ458RJIZJ4ApgCcINwrFol0qUqTDGQNovQBjCmgyABsnSACAa2E3UkpqOnQAemTYAHkAYQAZAAlYYDsyezjPWhYRAGZ-ER4qgA4dI08y_mYqqSr22ClmJtLSWkrWBq6Rfn5-lsHK-trOnvHGPWmplogwGwBbAGVvcIsB9ADgUMLmfwB3AAsNm1jp49PC_wBzOxsbaAfHgCNC4p2TLPOxvD5fH7Tf5FezAs52C6iD5kSGkKyefQkPT6ADcQA)
![image](https://github.com/apache/echarts/assets/13038071/6e8eb6aa-bfad-4b1b-9d04-a08f1e552935)

**Comment by matttttttty** [comment]
thx
