### ISSUE TITLE
[Feature] 能否增加一个X轴分组分层级的功能

### ISSUE THREAD

**Issue by gdfetemplate** [apache/echarts#20023]
### What problem does this feature solve?

增加X轴分组分层级的功能
例如：
![image](https://github.com/apache/echarts/assets/152265759/30b3826c-8e8c-49cb-8e93-f787be0c7f50)

### What does the proposed API look like?

希望效果能如上图一样

**Comment by helgasoft** [comment]
duplicate of #18923
