### ISSUE TITLE
[Bug] Line/area series step on data with nulls produces unexpected results

### ISSUE THREAD

**Issue by alxnddr** [apache/echarts#20021]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJi0Ar-_jywAKwADBkAbLmwKWkZAOyFAByFxf7WoR4U1HT-ENDK9aSMHFSMJhT-3kiwoIz0EBRE2QB0AEywDnHoeCwgdFTQmh3o9DBt9GAAcqn-0WAcSnF2JLZ2ANxAA

### Steps to Reproduce

1. Have a line/area cartesian chart where first and last data points are null ([example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJi0Ar-_jywAKwADBkAbLmwKWkZAOyFAByFxf7WoR4U1HT-ENDK9aSMHFSMJhT-3kiwoIz0EBRE2QB0AEywDnHoeCwgdFTQmh3o9DBt9GAAcqn-0WAcSnF2JLZ2ANxAA))
2. Set `areaStyle: {}`
3. Set `step: end` and `connectNulls: true` props
4. The chart does not appear correctly

### Current Behavior

Area polygon is incorrect, the bottom of it is shifted:

<img width="1274" alt="Screenshot 2024-06-11 at 3 48 40 PM" src="https://github.com/apache/echarts/assets/14301985/b50a2690-0c6f-4310-b607-38d6a088fbf2">

### Expected Behavior

The area polygon should be correct

### Environment

```markdown
- OS: macos
- Browser: chrome
- Framework: n/a
```

### Any additional comments?

There is a related problem when `connectNulls` is false:
<img width="1268" alt="Screenshot 2024-06-11 at 3 48 19 PM copy" src="https://github.com/apache/echarts/assets/14301985/3a0bdfef-5141-4d08-8f37-6711869eee3e">

**Comment by Ovilia** [comment]
[This](https://echarts.apache.org/examples/zh/editor.html?c=line-step&edit=1&reset=1&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYOIsAMhNDpUQL4A0RYwwWSCAKpiGAE4QA5lJziqAQ1IQAzu3TciuWdAAmIoul0KwCggG0adBrQXiwlLrCv1YAWQi7duR89quAUT1KAF1OHnQpSX1CMVwAMwpnAGYAUkdDWEkpAAskygAWdIjiACNgMD4AWyo0jLEAYxhTFkYFUpwsAjBxAFcccN5-LHLSAzF4nBNe8XxYsVgVBQA3HABBFQBJKoVZEQ5Mg40S0jXlFXHiMABPEDnKBpMcKWBxa_riY1MLSjcYX0oABV-gCAOo4XQAwE5XoAgBikgB1BMSN60FCg3Q1zOqku6BudyoywUWBBmMWcggOAusHMmVEC2gCiq938NlM9g-YgJ9ywLDYJTEKmsVGFdgcguIdimtGuuH2kqMJjMtIAjAAmAAMTlVyXVTkoAFoAcanABObWwdXJS3q1WasJiTRiBliJksqhs9yebwCzL4268_lc4jC-hUKo-nyK2DShSy-XIZ0LL4q8zqrVOdUADn1zlN-d86otTgKNtL9sdxGT6FdxHdrOssCCkJjPKofNYIfQYeEzhwwRjcYTcyQNc-yosBQArJay3mjSbfNOS7Bp-W15XDkQwhwANxAA) looks as expected to me. [Step](https://echarts.apache.org/en/option.html#series-line.step) can be one of `'start', 'middle', 'end'`.
