### ISSUE TITLE
Faceting visualizations

### ISSUE THREAD

**Issue by joshuaclausen** [apache/echarts#20048]
### What problem does this feature solve?

I can't seem to find any eChart that provides a "chart repeat" visualization, also known as a faceted visualization.  I'm sure there are other terms for this.

By "repeat options" I mean specifying a dimension that results in the chart being repeated for each of the values found in that dimension. Each of those repeated charts is simply filtered by a single value of the dimension. This would allow you to quickly see, e.g. count over time by product and then how that looks for each region. If you had 5 regions, then you would have 5 charts, each showing the count over time by product in each of those regions. Then you could easily swap out region for "customer age group" to see a different view of things.

This kind of visualization is really valuable, and I expect it will see a lot of use.

### What does the proposed API look like?

Tableau does faceting really well.

The Observable Plot library has this feature:
https://observablehq.com/plot/features/facets

eCharts4R has something:
https://echarts4r.john-coene.com/reference/e_facet

The Seaborn Python visualization library has this:
https://seaborn.pydata.org/generated/seaborn.FacetGrid.html

**Comment by Ovilia** [comment]
You can use multiple `grid` and `xAxis` and `yAxis` to do this in ECharts. See the [example](https://echarts.apache.org/examples/zh/editor.html?c=scatter-anscombe-quartet).
