### ISSUE TITLE
[Feature] bar图，想鼠标悬浮上去时候，shadow可以横坐标同时正负偏移，且y轴相对偏移一点，类似遮罩效果，应该怎么实现

### ISSUE THREAD

**Issue by lyz1991** [apache/echarts#20049]
### What problem does this feature solve?

when mouseover bar chart，achieve the effect shown in the below image, the emphasis height is small larger than data bar don't equal to the axisPointer Line's default height 

### What does the proposed API look like?

<img width="392" alt="WechatIMG53" src="https://github.com/apache/echarts/assets/15042461/eba46943-ac18-4c45-9305-bc9362322a87">

**Comment by lyz1991** [comment]
<img width="392" alt="WechatIMG53" src="https://github.com/apache/echarts/assets/15042461/8ddd1434-1a76-4790-8d31-97454da1801d">
预期效果，如图所示

**Comment by Ovilia** [comment]
This seems to be like axisPointer. Can you be more specific how's it different and why it's a necessary design?

**Comment by lyz1991** [comment]
> This seems to be like axisPointer. Can you be more specific how's it different and why it's a necessary design?

if set axisPointer, the axisPointer's height seems to be all the same, but I want the emphasis's height is only a little larger than the data bar's height，just if the data is small then it's emphasis height is relative short and if the data is large then it's emphasis height is relative high

**Comment by Ovilia** [comment]
What does the emphasized rect mean then, if it's not just background? What's the meaning of its height when its slightly taller the the bar's and how you are going to convary this information without making users being confused?

**Comment by lyz1991** [comment]
> What does the emphasized rect mean then, if it's not just background? What's the meaning of its height when its slightly taller the the bar's and how you are going to convary this information without making users being confused?


just a highlighted  effects to make page looks better， no extra meaning.

**Comment by Ovilia** [comment]
If this is the case, I don't think this is a common feature. That being said, you may consider creating a rectangle at the bar's back using `graphic.elements` to hack this effect, which should be a little challenging and you need to figure out the position with careful calculation.
