### ISSUE TITLE
[Feature] echarts5的x轴type:time，能同时支持echarts 4.9.0的x轴type:time效果么？

### ISSUE THREAD

**Issue by huihui925** [apache/echarts#20047]
### What problem does this feature solve?

**期望结果：** 希望echarts5版本，能支持旧版的效果。

**能解决的问题：**
一：echarts 4.9.0版本，设置x轴type：time且设置min和max后。得到的结果：
1. x坐标轴 时间会自动设置且不会拥挤，文字不会重叠。
2. echarts内部会根据不同情况，自动设置是精确到年月日或者时分秒等。
如图：
![image](https://github.com/apache/echarts/assets/58799528/8514cde1-5037-459c-9225-ec9b6ee9d7f6)
![image](https://github.com/apache/echarts/assets/58799528/0f00b749-308d-42e1-8a88-f69b7277a549)

目前echarts5不知道该如何达到旧版的效果，新功能分级模板的展示格式（无法满足自动根据min-max范围设置格式 且x轴每个刻度保持一致），另外x轴刻度还会重叠 拥挤，设置interval分割来达到不重叠效果，需要计算，感觉也有点问题。

### What does the proposed API look like?

希望echarts5版本，能支持旧版的效果

**Comment by Ovilia** [comment]
#19919 provides a callback that you can decide where to show the ticks for the time axis. This feature is supported since 5.5.1, which is under the process of releasing now. You can use the nightly version or wait for another few weeks for the new release.

**Comment by huihui925** [comment]
> #19919 provides a callback that you can decide where to show the ticks for the time axis. This feature is supported since 5.5.1, which is under the process of releasing now. You can use the nightly version or wait for another few weeks for the new release.

@Ovilia 感觉不太满足个人要求，如果想要指定min和max  中间刻度自适应  不拥挤重叠，该怎么做呢？

**Comment by Ovilia** [comment]
You can use the [formatter](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter) in the form of "Cascading Templates" to set different templates according to different time granularity. The interval is calculated automatically by ECharts to make sure more important labels are displayed.
