### ISSUE TITLE
[Bug] itemStyle.color配置成回调函数时，lineStyle.color无效

### ISSUE THREAD

**Issue by never51463** [apache/echarts#20042]
### Version

e.g. 5.5.0

### Link to Minimal Reproduction

https://github.com/apache/echarts/issues/10910

### Steps to Reproduce

配置series-line.itemStyle.color作为回调函数时，只有拐点变色，lineStyle没有按文档所说的会根据itemStyle.color取值
![企业微信截图_17186920882953](https://github.com/apache/echarts/assets/28085937/64540bd3-decd-48ff-91e1-d5eadac0b674)
![企业微信截图_17186921122638](https://github.com/apache/echarts/assets/28085937/950d7b98-98d3-41de-a732-22042f5ec9d5)

该问题与19年被提出并且被修复过，现在在新版本重新出现该问题并且没有解决

### Current Behavior

当itemStyle的color使用回调函数时，线条颜色不能产生相应变化

### Expected Behavior

当itemStyle的color使用回调函数时，线条颜色也能产生相应变化

### Environment

```markdown
- OS:windows 10
- Browser: 
- Framework:
```

**Comment by Ovilia** [comment]
This does not appear to be a bug, in my opinion. When `itemStyle.color` is defined as a callback function, it has the capability to return different colors based on varying data indices. However, `lineStyle.color` does not support using different colors for different data indices. As a result, when it is specified as a callback, it defaults to the series color as a graceful fallback.

**Comment by never51463** [comment]
This behavior does not match the document description, and the returned value belongs to a reasonable color range. It is unreasonable to assume that it is not a bug simply because it is returned using a callback function. Especially when the document explicitly states that lineStyle can inherit from itemStyle, this detail is illogical and independent of whether itemStyle uses callback function methods.
![企业微信截图_17186941434179](https://github.com/apache/echarts/assets/28085937/0748b053-2d33-45b7-a5c7-237507e700d2)

**Comment by never51463** [comment]
if it's no a bug, how to choose when I need to modify the color of a segment of a line based on different numerical values, but it is not a gradient scene？ @Ovilia

**Comment by Ovilia** [comment]
Currently, ECharts doesn't have the ability to set line styles of different segments, if visualMap doesn't count.

**Comment by never51463** [comment]
Perhaps adding support for callback function types to lineStyle would be more in line with the documentation's explanatory logic. 
@Ovilia When there are multiple series, visualMap cannot support the simultaneous use of multiple configurations, and conflicts will be automatically merged.

**Comment by Ovilia** [comment]
#17138 Maybe you can follow this feature. This is an epic feature so it's still in pending state and I don't know if when I have time to do this.

**Comment by never51463** [comment]
ok, i know that
