### ISSUE TITLE
split line from xAxis overlapped axisLine from yAxis

### ISSUE THREAD

**Issue by ninja-liu** [apache/echarts#20053]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqVh4QAGwhgAMhGg1i99Hm3AAO5EYBxKdr4uXiYUTjSovqT0wE6cBLQARk5KtPykAL55hej5EeQ4-EQJpBTUdABujNnKEeiMuHgeXlV5fgHBoeG9sFFUMeRxPYnoyakcdBysGYwAFABMAKwbPACMAAx7PId7AHQAHACUvMPogRACYNoEO2vDxQUkpSR4VEZUhLBRHlqvYhGARICdhtDrA1gBmGFrNYAFh4sJ2ZzROzh21gO2RAHY0WsAGx7WzDWreWijXL2d7WFD5ADcQA

### Steps to Reproduce

here is the configuration to reproduce the issue:

option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    splitLine: {
      show: true,
      lineStyle:{
        color:'blue'
      }
    }
  },
  yAxis: {
    type: 'value',
    axisLine: {
      show:true,
      lineStyle: {
        color: 'rgba(255,100,0,0.8)',
        width:12
      }
    }
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};

### Current Behavior

while splitline  attr in xAxis options and axisLine atrr in yAxis options set concurrently, two lines from each other overlapper in the position where yAxis axisline lies. 

### Expected Behavior

provide a way to hidden the line of splitLine in the position where yAxais lies

### Environment

```markdown
- Browser:
```

**Comment by semla** [comment]
Isn't it just that the axisLine is transparent? When set to 1 instead of 0.8 the splitLine is not visible

**Comment by ninja-liu** [comment]
> Isn't it just that the axisLine is transparent? When set to 1 instead of 0.8 the splitLine is not visible

transparent is prefered by the UI what happens now and then.

**Comment by Ovilia** [comment]
The current behavior is by-design. If you want the feature of removing the min/max tick, we need a new option like `splitLine.showMinLine`.
