### ISSUE TITLE
tree 开启roam鼠标缩放和平移漫游，点击节点时，如何将点击的节点移到居中位置。好像并不能获取到节点相对树图的距离吧

### ISSUE THREAD

**Issue by BWA-579** [apache/echarts#20059]
### What problem does this feature solve?

聚焦点击的节点展开

### What does the proposed API look like?

支持动态居中

**Comment by helgasoft** [comment]
see #20098  #18961

**Comment by BWA-579** [comment]
> 参见[#20098 ](https://github.com/apache/echarts/issues/20098) #18961

是tree，不是treemap哦

**Comment by BWA-579** [comment]
> 参见[#20098 ](https://github.com/apache/echarts/issues/20098) #18961

是tree，不是treemap哦

**Comment by helgasoft** [comment]
clicked tree node to center - [Demo](https://echarts.apache.org/examples/en/editor.html?c=tree-basic&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzOQqUAzADaxGCAFZJUhKQBpRWgK6EAxnHynRpeYvKiA3tVGjQkWEQIfFxGbDwiMiofUTcoBDtgnVwYRkIELVQYAFEoRNIbe0dnVwVrYEsiUIAPD29fXyrGatEAUlEAJlEAXl7RAAZRADIhlzdyhNQdPQAHNVwe0TgYa0Zo3wBfdb9waHhkZnYZ4sJSGN9SVGOnQkX6ht84VCnHGYAuL3OHpZh8YiYYB8pPg4IxgBYvg9ln8AexCEDgKhrGpEQA3RhSSGiDbmLFqX6MJAfADaWN892-DTgIBmjCBy0YGMsMBwwDey1WuMpDziJLiAF0udzHlcgQBGVoQ4W-HSMLRwIEAdklQuFACNUHAnmzpBKpdLfsQIArpB1-iqyQ0kCBgBqdABlfAALzpokVqu5ejVjB0Hwp0pmqCQIJuQNl8v10tE6Pg-DsUB0Ah0f3h0mAIVwssj0oTKaBhuN2eFmUIcEdLo-AE5LZsPZTZVB0UTPlGZVBvb6W63fIHgyd839C3XpTHHPHE8niKmpOncJmmTXvrmp2G5XBMd2NoucYuwTNoMHm_7i6g7MigaEkHY0vJSxvpTuo80ZlBCLgBG-wFNZmoPhzGMODyvvgwAKDcAAi1gwGBpgfAArHB_SAQ0wGgSckHQScACqMxuK6iqIZaW6UvyXxbDE2z-HsiCmKQUh2MmdgANYWC4MwzB43QAHxdr4VGBAgBBIC-cCJAIDg3KQx5LDSrpSAyjCsKyrF2KgwCBoQaRwFwslvFI-L4ISRaxNUHz8fsTBwAA6iEcAQBQMhdAAtKI7EIIw6KlggqBaFoahwAAGsOuAgGZuwCZZwiMIOLDkI5oguW5Hlad5vn-QAmmR2x8eF-z-UcJyXNcpjbFsNBlUAA).
📌 please close issue if problem solved.

**Comment by BWA-579** [comment]
> clicked tree node to center - [Demo](https://echarts.apache.org/examples/en/editor.html?c=tree-basic&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzOQqUAzADaxGCAFZJUhKQBpRWgK6EAxnHynRpeYvKiA3tVGjQkWEQIfFxGbDwiMiofUTcoBDtgnVwYRkIELVQYAFEoRNIbe0dnVwVrYEsiUIAPD29fXyrGatEAUlEAJlEAXl7RAAZRADIhlzdyhNQdPQAHNVwe0TgYa0Zo3wBfdb9waHhkZnYZ4sJSGN9SVGOnQkX6ht84VCnHGYAuL3OHpZh8YiYYB8pPg4IxgBYvg9ln8AexCEDgKhrGpEQA3RhSSGiDbmLFqX6MJAfADaWN892-DTgIBmjCBy0YGMsMBwwDey1WuMpDziJLiAF0udzHlcgQBGVoQ4W-HSMLRwIEAdklQuFACNUHAnmzpBKpdLfsQIArpB1-iqyQ0kCBgBqdABlfAALzpokVqu5ejVjB0Hwp0pmqCQIJuQNl8v10tE6Pg-DsUB0Ah0f3h0mAIVwssj0oTKaBhuN2eFmUIcEdLo-AE5LZsPZTZVB0UTPlGZVBvb6W63fIHgyd839C3XpTHHPHE8niKmpOncJmmTXvrmp2G5XBMd2NoucYuwTNoMHm_7i6g7MigaEkHY0vJSxvpTuo80ZlBCLgBG-wFNZmoPhzGMODyvvgwAKDcAAi1gwGBpgfAArHB_SAQ0wGgSckHQScACqMxuK6iqIZaW6UvyXxbDE2z-HsiCmKQUh2MmdgANYWC4MwzB43QAHxdr4VGBAgBBIC-cCJAIDg3KQx5LDSrpSAyjCsKyrF2KgwCBoQaRwFwslvFI-L4ISRaxNUHz8fsTBwAA6iEcAQBQMhdAAtKI7EIIw6KlggqBaFoahwAAGsOuAgGZuwCZZwiMIOLDkI5oguW5Hlad5vn-QAmmR2x8eF-z-UcJyXNcpjbFsNBlUAA). 📌 please close issue if problem solved.



> clicked tree node to center - [Demo](https://echarts.apache.org/examples/en/editor.html?c=tree-basic&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzOQqUAzADaxGCAFZJUhKQBpRWgK6EAxnHynRpeYvKiA3tVGjQkWEQIfFxGbDwiMiofUTcoBDtgnVwYRkIELVQYAFEoRNIbe0dnVwVrYEsiUIAPD29fXyrGatEAUlEAJlEAXl7RAAZRADIhlzdyhNQdPQAHNVwe0TgYa0Zo3wBfdb9waHhkZnYZ4sJSGN9SVGOnQkX6ht84VCnHGYAuL3OHpZh8YiYYB8pPg4IxgBYvg9ln8AexCEDgKhrGpEQA3RhSSGiDbmLFqX6MJAfADaWN892-DTgIBmjCBy0YGMsMBwwDey1WuMpDziJLiAF0udzHlcgQBGVoQ4W-HSMLRwIEAdklQuFACNUHAnmzpBKpdLfsQIArpB1-iqyQ0kCBgBqdABlfAALzpokVqu5ejVjB0Hwp0pmqCQIJuQNl8v10tE6Pg-DsUB0Ah0f3h0mAIVwssj0oTKaBhuN2eFmUIcEdLo-AE5LZsPZTZVB0UTPlGZVBvb6W63fIHgyd839C3XpTHHPHE8niKmpOncJmmTXvrmp2G5XBMd2NoucYuwTNoMHm_7i6g7MigaEkHY0vJSxvpTuo80ZlBCLgBG-wFNZmoPhzGMODyvvgwAKDcAAi1gwGBpgfAArHB_SAQ0wGgSckHQScACqMxuK6iqIZaW6UvyXxbDE2z-HsiCmKQUh2MmdgANYWC4MwzB43QAHxdr4VGBAgBBIC-cCJAIDg3KQx5LDSrpSAyjCsKyrF2KgwCBoQaRwFwslvFI-L4ISRaxNUHz8fsTBwAA6iEcAQBQMhdAAtKI7EIIw6KlggqBaFoahwAAGsOuAgGZuwCZZwiMIOLDkI5oguW5Hlad5vn-QAmmR2x8eF-z-UcJyXNcpjbFsNBlUAA). 📌 please close issue if problem solved.

nb,解决了十分感谢
