### ISSUE TITLE
[Bug] Cannot call specified dataset by 'datasetIndex' from a switchableOption's 'series'

### ISSUE THREAD

**Issue by philip-gc** [apache/echarts#20065]
### Version

5.5.0

### Link to Minimal Reproduction

https://github.com/philip-gc/echarts_issue_switchableOption

### Steps to Reproduce

In directory ./demo/index.js,

From line 65 to 76 to create each `switchableOption`, when I coded this to refer to the dataset with specific transformation:

```javascript
series: [
   {encode: {x: 'B01', y: 'A'}, datasetIndex: 1},
   {encode: {x: 'B02', y: 'A'}, datasetIndex: 1}
]
``` 

The `datasetIndex` property did not work. 

But it works fine when I use this property in `baseOption`'s `series`.

### Current Behavior

The `datasetIndex` property doesn't work within `switchableOption`'s `series`, contrast to `baseOption` scenario.

### Expected Behavior

Just behave consistently, `datasetIndex`!

### Environment

```markdown
- OS: Windows 10 22H2 Enterprise
- Browser: Chrome 125.0.6422.176
```

**Comment by helgasoft** [comment]
see if [this Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=CYZwpgLgvABA2gWAFA1TA3staQHsCuATgMZgBc8W2acA5AIK0A0MtAQgAwCMz7HATL04BmIVx5N2XQZLZdRAXSZVq8WgENmMLhxap-u7BwB0AVj0BOPdv7WTAdlNKV1OgCMtXc2i4AOazAmvsIs_Lb6hqhcxlzOKKpqxJ4hPgBsAUFcLJGBAQB2-AA2hXEJasBaObnUBcUsfnoGdsYWCi6obfGoAL7KXRjtMABmhLgAtgAi6hDq4BAAknnAYAAeFLqDEITqeSBDuIRjFIj92OgQAJ4ADuSsQwCWhRBghFrEuHkPAOYU6MD3YzAu3uHwofBkrAAhFBaOtur1BqhztdbrQ8IQIG8Pt9fv9AcDQaxOBIYAdloQwcsQEl4YNOtgEf1MKdhqNJtNZpBFss1rlNttdvtDsdERhLjcwQ8ni8sZ97j8MHigSAQXkwXIIbRobDAvC-mVkRLWOjMSx3nKFX8AcrVerxFoyS9KWBqbRaSz6WhGR0-shcFcIKqYLBmahA4DCvc8rdQ2h1Ct7iAACoosHEaZgL4HC5aYAc458LRSWie70wL6Ee7AEVMwpgIYQMH8ACkWgA7lWIAALMEAFg4rbLSMrXy7jdYLfbnZ7rH7g5YAHoFzAk13E-XK8AYOuhTAdrhuy8YPg8oQwIUM1uK-orl2WAArfAgCAwYAfPIHmDps9UUowFb0AmIA1mcFZVtyqzrCw4qogAbuohT4GAbr6mg6BgcAEG8lkMAwWC8GIch3S_qhFyAYmIFoRhWFQbhqasOmzxZoQOZDhg1FLJB2jQfRtCMZm2ZuiRVD-oGHzAZQTKDHmMxzBQoCQKh2DgJWLqUaohqom46ivAEMBAu8yy_LyfAkhcYKML0r4cnMNHaGxZx4cajHPLp-l5IZMYmZwELmawlksDJnILJx2EOWhxEei4bGxtgQVya-cxKTgLz3GpkkGk5tDaW52AGbgRkYN59osH5DAodZslcqFFD8OFSJZdS0yuVo-WFegxW-RZFXxdVPK1fVGCRaono9L-yDdAA3EAA) works for you. It includes the same dataset in both timeline options.
📌 please close issue if problem solved.

**Comment by philip-gc** [comment]
> see if [this Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=CYZwpgLgvABA2gWAFA1TA3staQHsCuATgMZgBc8W2acA5AIK0A0MtAQgAwCMz7HATL04BmIVx5N2XQZLZdRAXSZVq8WgENmMLhxap-u7BwB0AVj0BOPdv7WTAdlNKV1OgCMtXc2i4AOazAmvsIs_Lb6hqhcxlzOKKpqxJ4hPgBsAUFcLJGBAQB2-AA2hXEJasBaObnUBcUsfnoGdsYWCi6obfGoAL7KXRjtMABmhLgAtgAi6hDq4BAAknnAYAAeFLqDEITqeSBDuIRjFIj92OgQAJ4ADuSsQwCWhRBghFrEuHkPAOYU6MD3YzAu3uHwofBkrAAhFBaOtur1BqhztdbrQ8IQIG8Pt9fv9AcDQaxOBIYAdloQwcsQEl4YNOtgEf1MKdhqNJtNZpBFss1rlNttdvtDsdERhLjcwQ8ni8sZ97j8MHigSAQXkwXIIbRobDAvC-mVkRLWOjMSx3nKFX8AcrVerxFoyS9KWBqbRaSz6WhGR0-shcFcIKqYLBmahA4DCvc8rdQ2h1Ct7iAACoosHEaZgL4HC5aYAc458LRSWie70wL6Ee7AEVMwpgIYQMH8ACkWgA7lWIAALMEAFg4rbLSMrXy7jdYLfbnZ7rH7g5YAHoFzAk13E-XK8AYOuhTAdrhuy8YPg8oQwIUM1uK-orl2WAArfAgCAwYAfPIHmDps9UUowFb0AmIA1mcFZVtyqzrCw4qogAbuohT4GAbr6mg6BgcAEG8lkMAwWC8GIch3S_qhFyAYmIFoRhWFQbhqasOmzxZoQOZDhg1FLJB2jQfRtCMZm2ZuiRVD-oGHzAZQTKDHmMxzBQoCQKh2DgJWLqUaohqom46ivAEMBAu8yy_LyfAkhcYKML0r4cnMNHaGxZx4cajHPLp-l5IZMYmZwELmawlksDJnILJx2EOWhxEei4bGxtgQVya-cxKTgLz3GpkkGk5tDaW52AGbgRkYN59osH5DAodZslcqFFD8OFSJZdS0yuVo-WFegxW-RZFXxdVPK1fVGCRaono9L-yDdAA3EAA) works for you. It includes the same dataset in both timeline options. 📌 please close issue if problem solved.

Thanks! It's brilliant!

But still, what state in the [Option Doc](https://echarts.apache.org/en/option.html#timeline) and [API Doc](https://echarts.apache.org/en/api.html#echartsInstance.setOption) that explain `baseOption` and `switchOption`'s "merging" mechanism do not cover the situation your solution meets.

Hope echarts documentation can be much more detailed and coherent, more accurate and less misleading!

**Comment by philip-gc** [comment]
> > see if [this Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=CYZwpgLgvABA2gWAFA1TA3staQHsCuATgMZgBc8W2acA5AIK0A0MtAQgAwCMz7HATL04BmIVx5N2XQZLZdRAXSZVq8WgENmMLhxap-u7BwB0AVj0BOPdv7WTAdlNKV1OgCMtXc2i4AOazAmvsIs_Lb6hqhcxlzOKKpqxJ4hPgBsAUFcLJGBAQB2-AA2hXEJasBaObnUBcUsfnoGdsYWCi6obfGoAL7KXRjtMABmhLgAtgAi6hDq4BAAknnAYAAeFLqDEITqeSBDuIRjFIj92OgQAJ4ADuSsQwCWhRBghFrEuHkPAOYU6MD3YzAu3uHwofBkrAAhFBaOtur1BqhztdbrQ8IQIG8Pt9fv9AcDQaxOBIYAdloQwcsQEl4YNOtgEf1MKdhqNJtNZpBFss1rlNttdvtDsdERhLjcwQ8ni8sZ97j8MHigSAQXkwXIIbRobDAvC-mVkRLWOjMSx3nKFX8AcrVerxFoyS9KWBqbRaSz6WhGR0-shcFcIKqYLBmahA4DCvc8rdQ2h1Ct7iAACoosHEaZgL4HC5aYAc458LRSWie70wL6Ee7AEVMwpgIYQMH8ACkWgA7lWIAALMEAFg4rbLSMrXy7jdYLfbnZ7rH7g5YAHoFzAk13E-XK8AYOuhTAdrhuy8YPg8oQwIUM1uK-orl2WAArfAgCAwYAfPIHmDps9UUowFb0AmIA1mcFZVtyqzrCw4qogAbuohT4GAbr6mg6BgcAEG8lkMAwWC8GIch3S_qhFyAYmIFoRhWFQbhqasOmzxZoQOZDhg1FLJB2jQfRtCMZm2ZuiRVD-oGHzAZQTKDHmMxzBQoCQKh2DgJWLqUaohqom46ivAEMBAu8yy_LyfAkhcYKML0r4cnMNHaGxZx4cajHPLp-l5IZMYmZwELmawlksDJnILJx2EOWhxEei4bGxtgQVya-cxKTgLz3GpkkGk5tDaW52AGbgRkYN59osH5DAodZslcqFFD8OFSJZdS0yuVo-WFegxW-RZFXxdVPK1fVGCRaono9L-yDdAA3EAA) works for you. It includes the same dataset in both timeline options. 📌 please close issue if problem solved.
> 
> Thanks! It's brilliant!
> 
> But still, what state in the [Option Doc](https://echarts.apache.org/en/option.html#timeline) and [API Doc](https://echarts.apache.org/en/api.html#echartsInstance.setOption) that explain `baseOption` and `switchOption`'s "merging" mechanism do not cover the situation your solution meets.
> 
> Hope echarts documentation can be much more detailed and coherent, more accurate and less misleading!

That is to say. Within `switchableOption` part, `series`' `dataIndex` can only call the dataset inside, unable to call dataset at `baseOption`. The doc should explain this.
