### ISSUE TITLE
[Feature] 仪表盘(gauge)的"progress"功能希望能设置背景

### ISSUE THREAD

**Issue by comvir** [apache/echarts#20060]
### What problem does this feature solve?

5.5.0版的gauge新增了progress功能，当配置只显示progress时，希望有个轨道背景，看起来像个完整的进度条。
虽然可以叠加一个serie实现，如果progress能直接设置背景最好不过。

### What does the proposed API look like?

```
{
   type:"gauge",
   progress:{
      show:true,
      background:{
         //someprops
      }
   }
}
```

**Comment by plainheart** [comment]
试试 [`itemStyle.color`](https://echarts.apache.org/option.html#series-gauge.progress.itemStyle.color) 设置为一个 [image](https://echarts.apache.org/option.html#color)？

**Comment by comvir** [comment]
> 试试 [`itemStyle.color`](https://echarts.apache.org/option.html#series-gauge.progress.itemStyle.color) 设置为一个 [image](https://echarts.apache.org/option.html#color)？

itemcolor本来是要跟随区间色的，progress看起来像个进度条，如果有个背景就是完整的进度条了

**Comment by plainheart** [comment]
不太明白想要什么样的效果。能画个示意图么？我指的是 progress 选型下的 itemStyle.color

**Comment by comvir** [comment]
> 不太明白想要什么样的效果。能画个示意图么？我指的是 progress 选项下的 itemStyle.color

**Comment by comvir** [comment]
> 不太明白想要什么样的效果。能画个示意图么？我指的是 progress 选项下的 itemStyle.color
例如这样
![image](https://github.com/apache/echarts/assets/7907986/d0ac077d-e4b0-4adb-b081-b0fa7810339a)
如图所示，进度条的颜色"progress.itemStyle.color"设的"auto"，进度到不同位置时颜色不同。
图中的灰色背景我用饼图替代的。

**Comment by comvir** [comment]
> `axisLine.lineStyle.color`: [ [1, 'blue']]
> 
> See [demo](https://echarts.apache.org/examples/zh/editor.html?c=gauge-temperature&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUAxlmhhcxEkwCsABgCkfWEwBs8pgF1-1dBjBscYAILQWAG0awATDJlbtIgCbGzFgLTW71ALYRoxWwLoXmwAHsSqnhQYIKYQYAByHF4ARuKwAIyWkehxWF4AynTmxKjaQsCmwDjMAMQAYnWGAEIAnOlMgbAAvtmwIDjALDgERJRlOgAWwADuxGA4HFi96NMQDmATxADMMp09nSDAvmLVY-MYU7OwAGZspth7vaEQGAAyvhal47HQWIW0xTO41gq3Wm1gO2W5UqpzIwOoJHSvCUyVMiw0nWo6kx3UenWeGAAKhBBABrEo4hwvPTQYTEVwAFikUOisQSSVSp2ZOJ-fyKnxxKzWG2IWUFsEEFSqtRaso6wK6eLKrLi71-FOBVN0bFpbikYuB5hMIoyDKhvP-gK-wNBJq2UPQkphMrlOMVZX2ZQJrzYqVMGvGWppdNg7gCwKd0qUNVlLT4OOuMDA-QgAC8LNYldodYIpqdrdoLjNiLd7lgs9RIGArTii1dSw8Pb0HFg9BB_UDtAA3O6LYwQYKQGBzBZLHG28EqNTmj4ACSwEBYEzAxAZ4fGySqLZwACU2FSOKMABxQ4DXa7YMAAYREJwktiUrnSUgUmgTSZT6fC67KidEAHUFyXFcUQqbd42BRMcEHO8lCQHs0SwLpYAABqvCDxkjU4mF8CZcDieVtE9bQHDYPQJBxAsygQxZRV2BVOmxahiPQKiaHoCxWE4bgMOoYRRDSSRZAUZEp1fXptQMZxAWsH8KEcaS3A8TofD8WA5KCUJv16XICn5AMyiw2o6gAEQAdi2BkzMI5jen6QZhgwUY2MmYsaFHKEJ2II8KwoQ5jjSFzMEuEs7kbIinhCF41QFYE61CstfPQAliTJAzCxCm4wvLJtOhVMAYvS6h4qyxLcq9KK3l9LAOyCkqGxyiLOhbNtatrTKGqS2BSPI0hKPFGiM3o8Z3W0JiKFG7EugAbhQS8AEkBJwBCAAprg4WkhzgFaAEozklaBdFgHAdQcYAvAQWAAGoVoAWTIiYADoTugM6vF22AACpYFUHbHrAYA6ggEIsAcFbLB22agloK8Jn0MBHsvAB5cAoGgFaC2wPACAosogp6thcfhILqEG4gXre8VRrKcbbM6fGyMJvr4U7YEyeO07zqpnFaYmgRxq6SGUB6KwbBkSGgA)

意思理解有误，进度条本体色是可以变色的，变色依据是"axisLine.lineStyle.color"可以设多段颜色

**Comment by Ovilia** [comment]
没明白你要什么
