### ISSUE TITLE
[Bug] zh website CDN issue  

### ISSUE THREAD

**Issue by 18876247070** [apache/echarts#20064]
### Version

5.5

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=bar-y-category-stack

### Steps to Reproduce

打开链接即可发现，内容空吧，页面报错。
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6:37
common.js?_v_=85b684f192:1 Uncaught ReferenceError: $ is not defined
    at common.js?_v_=85b684f192:1:582
vue.min.js:6 ReferenceError: $ is not defined
    at a.fetchVersionList (example-bundle.js?_v_=2561fdd485:1:152239)
    at a.mounted (example-bundle.js?_v_=2561fdd485:1:143840)
    at Be (vue.min.js:6:11407)
    at Qt (vue.min.js:6:25438)
    at Object.insert (vue.min.js:6:20517)
    at k (vue.min.js:6:60576)
    at Cn.__patch__ (vue.min.js:6:61934)
    at e._update (vue.min.js:6:34609)
    at Cn.r (vue.min.js:6:68555)
    at pn.get (vue.min.js:6:26867)
Ve @ vue.min.js:6
example-bundle.js?_v_=2561fdd485:1 Uncaught (in promise) ReferenceError: $ is not defined
    at example-bundle.js?_v_=2561fdd485:1:124252
    at new Promise (<anonymous>)
    at Le (example-bundle.js?_v_=2561fdd485:1:123788)
    at a.mounted (example-bundle.js?_v_=2561fdd485:1:212380)
    at Be (vue.min.js:6:11407)
    at Qt (vue.min.js:6:25438)
    at Object.insert (vue.min.js:6:20517)
    at k (vue.min.js:6:60576)
    at Cn.__patch__ (vue.min.js:6:61934)
    at e._update (vue.min.js:6:34609)

### Current Behavior

只想查看一下案例，但是查看案例详细报错

### Expected Behavior

希望能看到到案例详细，现在页面内容导致报错，无法更直观查看

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
看看 Console，是不是那个 jQuery 的 CDN 报错了？

**Comment by 18876247070** [comment]
是的

https://cdn.staticfile.net/jquery/3.7.1/jquery.min.js


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] [Bug]  (Issue #20064)





 
看看 Console，是不是那个 jQuery 的 CDN 报错了？

**Comment by plainheart** [comment]
这是咱国内的 CDN https://staticfile.net/，不应该无法访问呀

**Comment by 18876247070** [comment]
七牛 CDN 提供的前端加速服务，staticfile.net 当前已经不再维护了
不过奇怪的是他们官网给出的公告消息很矛盾，没有时间日期的公告。有可能这个公告不新鲜而且显示与公告内容相反。
Staticfile 加速服务，最初这是 2016 年上线的，七牛 CDN 联合掘金推出的，七牛提供分发服务，掘金提供赞助。现在赞助商已经变成了 51la，但这都停止维护了。可能是没钱了吧



旧的还能用地址在这边：https://cdn.staticfile.org/jquery/3.7.1/jquery.min.js；
或者不用staticfile，可以选择用一下别的国内cdn；
官网：http://cdn.bytedance.com/；

由国内字节跳动公司所出品的公共库，同步 cdnjs.com，但有时候可能针对部分库未及时更新到最新版本，需要注意这一点，否则在使用时可能会导致一些莫名的错误。；



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] [Bug]  (Issue #20064)





 
这是咱国内的 CDN https://staticfile.net/ ，不应该无法访问呀

**Comment by plainheart** [comment]
staticfile 不维护的是旧域名 org，不是 net。bytedance 的不太合适，很多库缺失，之前考虑过，最后没采用。可以用手机移动流量试试，如果没问题，那应该是你那边特定环境问题。

**Comment by plainheart** [comment]
staticfile#702 看了下该仓库 issue，似乎也有其他人反馈类似问题，考虑到一直觉得这个 CDN 速度较慢，后续我会综合考虑换掉 它。

**Comment by 18876247070** [comment]
试了一下我的另外一台不同环境和移动设备确实可以访问的，抱歉抱歉，没有更严谨换个环境验证一下。给你耽误时间了
，，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/echarts] [Bug] zh website CDN issue   (Issue #20064)





 
staticfile 不维护的是旧域名 org，不是 net。bytedance 的不太合适，很多库缺失，之前考虑过，最后没采用。可以用手机移动流量试试，如果没问题，那应该是你那边特定环境问题。

**Comment by biluochun** [comment]
一样无法访问了..https://cdn.staticfile.net/jquery/3.7.1/jquery.min.js..昨天还好好的.

**Comment by plainheart** [comment]
已经移除 staticfile CDN，再试试看。

**Comment by biluochun** [comment]
> 已经移除 staticfile CDN，再试试看。

试了,可以 https://registry.npmmirror.com/jquery/3.7.1/files/dist/jquery.min.js
