### ISSUE TITLE
[Bug] echarts容器图表全屏显示时,主题为什么自动变成了黑色

### ISSUE THREAD

**Issue by zxy-github136** [apache/echarts#20088]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis

### Steps to Reproduce

1.打开链接，
2.F12打开谷歌浏览器控制台，
3.输入document.querySelector('#chart-container').requestFullscreen()
4.会发现echarts主题变为了黑色

### Current Behavior

想做全屏展示，但是全屏之后，图表主题变成黑色了

### Expected Behavior

全屏之后，图表主题不变

### Environment

```markdown
- OS: Win10
- Browser: Chrome 126.0.6478.127
- Framework: Vue@3 或 echarts官网
```

### Any additional comments?

在一个加班的夜晚的前夕

**Comment by zxy-github136** [comment]
yes ok

**Comment by helgasoft** [comment]
_document.querySelector('#chart-container')_ returns null in my browser...
Try setting fullscreen background in CSS:
```
#chart-container:fullscreen { background-color: 'yellow';}
#chart-container:-webkit-full-screen {  background-color: 'yellow'; /*  width: 100vw;  height: 100vh;*/}
#chart-container:-moz-full-screen { background-color: 'yellow'; }
#chart-container:-ms-fullscreen { background-color: 'yellow'; }
```

**Comment by zxy-github136** [comment]
Operation process [step.zip](https://github.com/user-attachments/files/16022725/step.zip)

**Comment by plainheart** [comment]
得给 container 元素设置个背景颜色，示例页面没有设置默认背景颜色，会继承浏览器默认的背景色。当只有 container 元素全屏时，没有可以继承的背景色，于是就出现了所谓的“黑色”背景。

```css
#chart-container {
  background-color: #fff;
}
```

**Comment by zxy-github136** [comment]
是的，you are right
