### ISSUE TITLE
[Bug] Gauge chart: Progress axis color disappears on negative min max limit

### ISSUE THREAD

**Issue by akashsonune** [apache/echarts#20097]
### Version

5.1.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAEYAHAAZ-1dFmgATCdNkqB6ALYRoxfWtiG2AD2IBaAEwAWc2owgpEMADkOhgEa4xHIOqmpeWIYAynQyxKgW6ADGwFLAOMwAxACsCgAiAJwAYgV8BoIAFmyawADuAMKp6cw4LP5sABQqcgDMCrwO2dm8SgB0TtkAlGWJmFU1tQBCUhwZ8q4WGPN1APIAZnvYYAAaxKHl6FvVuwdHAJpn5QC-YdQgOMAsOARElLNbdWIYBwHCwrzUHw4WnqbBAQJBYIusFqEE0YAqwQUz3B6BAwBMYCCf0SEBSplgTBAbHRhAA9LSALIOJQFMY9ABsfQKvHZcmyox6LIKBVgABlmayBZyFNzefzBcKRfUJXJxgoegB2UJygVCkUShzjJR9Ho8uTs0ZyAouBwKWAG8ZOBTZWVyDUCkIFbLssUSi2s9kFfpahSjDVDAoOJUS91KbJ84YanqGjlejUa-0spyjBw9AqmpP8pzmhwhTOS9mDdns3iF0bepQau3KlljbJ9Ca1nr871OByB8tjCZyN1dnvVpRyJyDqVcsf1idT32t2cy-fe9mT6cthQWjVOJM1usbreZ9WjBQJjVdw2cvs9M89C9X2tR0aTjWBhywHdPy9Da8Q1GfMlGLb9mXPS8k1CICFCcHolwgv8ILkV9Q3DF0o2XBRQwcDVIzNd0EKjb0fwg0NkzzGteQtK0bTtCCChzJwXGvHUFWFGcOTndi9VgAAtGZEhkSQaQpcMAFIhIsFE0QxeQayRYBbiwMB6g0Qk1hIFQKWyKSAF1sXKGwIAwUUTFkBJEkhaFYXhUEcQoTxoCwGJaDiYlZlksTFCRJ4jIsEyMAAFVJABreIkXcTwfD8QI1nOWZnNc2JLKRdBvPkxLZlgFI0jWJhMkVJg_ICtwPC8cyXMipKNBYHzsosZK3I8qyvNRMTTXS3KmgKorhRK2Z_IsF5jOsUzRTYQIpBqxJNFM4RoCSWRBUc5JeqyYq1tgPYYDAKIIAAL1kZkyuoSAwFaqKKkBHa2CkbAzooTRVLYCAZs8tR2iSMKvmAKFNEafKsgOPZpK-9IXpwIHmgpfrSm2_xIdwAB1Dqsu2zLmE3KTtuSgAJLAIBYCowGIFxtoqImSbJ2AKaRJGcChgAlaoIA4X5-iUlS1I0oltN4CluwM7aADd7tBCQICsSAYHsxFZl2nAZc04g9ihJJZbgDpxZWLBJk-ixvjAVY4CYJBddBAAfJhYAAalgS2sFGMBgCKCBrCwTQugNh2mCeJAoS8K2wsMWkKieJgAG4_O2vAknktrEid2acp2vaDuO4hsg2HLdugMAUep0nmCRqQofB2Y8thwr0w1QactGtOg9ppPFYzo6TtzquNrhrbutxap5skYgBdgHTHB0uQlEMtPhsSefqCbtRNGpNhR6RNu1BT2A7GnpRSosWeKHnwynijoA

### Steps to Reproduce

1. Open gauge chart
2. set min to 0 and max to -100
3. see that the progress color is disappeared

### Current Behavior

When the min and max for the gauge chart is set to negative values (we have a requirement to show the gauge with negative values), the progress color fades away

### Expected Behavior

The progress color should be retained irrespective of whether min max is negative/positive

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: Angular 17
```

**Comment by helgasoft** [comment]
try ```axisLine: { lineStyle: { color: [[1, 'transparent']] } },```

**Comment by akashsonune** [comment]
We are actually doing something like this [example](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAEYAHAAZ-1dFmgATCdNkqB6ALYRoxfWtiG2AD2IBaAEwAWc2owgpEMADkOhgEa4xHIOqmpeWIYAynQyxKgW6ADGwFLAOMwAxACsCgAiAJwAYgV8BoIAFmyawADuAMKp6cw4LP5sABQqcgDMCrwO2dm8SgB0TtkAlGWJmFU1tQBCUhwZ8q4WGPN1APIAZnvYYAAaxKHl6FvVuwdHAJpn5QC-YdQgOMAsOARElLNbdWIYBwHCwr3CYEiMVocWQsBSaTWTE4YGATFgLwusFqEE0YAqwQUz3B6BAwBMkLWCUSEBSplgTBAbHxhAA9KyALIOJQFMY9ABsfQKvH5cmyox6PIKBVgABlubyJYKFMLReLJdKZfUFXJxgoegB2UJqiVSmUKhzjJR9HoiuT80ZyAouBwKWAW8ZOBTZVVyA0SkIFbL8uUKh28_kFfpGhSjA1DAoOLUK_1KbJi4YGnqWgVBg0G908pyjBw9Aq2rPipz2hwhQuK_mDfn83iV0bBpQGt3anljbJ9Catnri4NOByR-tjCZyP1DkfNpRyJyTpVCufthdL0O91cq9fB_mL5c9hQOg1OLMttsHo-F_WjBQZg1Dy2Csc9O89B9P1tJ0aLg1IwcWATy_R8hmfGNRnLJRq2A7l70fLNQighQnB6LcELAhC5F_WN4x9JNtwUWMHANRM7X9DCk2DECENjbMyxbUUHSdF03QQgoSycFxnxNDVpRXAU134s1YAALRmRIZEkFkGXjABSPhYAiaJYlkJB4SaJEUTRDESQoHE8QJeQWyxYBbiwMB6g0SliBIFQGWyJSAF1iXKGwIAwWUTA0rEAVqQg9jYKRsAM9APg4LR6jYEAgRBMEsU8aAsGhWFqVmIy5MUcKKARZpSAcx1eAZb5NCYFzeCKpxeFYb4NAqqqxn6Jh_BWHhKpIXCmFoLApDSWoKpc2AsSedyLE8jAABVaQAa3ifyPC8XwAiCd1cuS1L1IW2Z0Cykzzl2rTESyTUmFG8a3CWsAfJSnbpI0FhssO6TfLSvyjv24hbSxZJtNO6VztmMaLExCbrC82U2ECKR7osTQvOEaAklkSVcvypFMjO3K9hgMAoggAAvWRuUu6hIDAdL_IqQFYGC0KsDJihNCstgIFhv5EnaJJZq-YAos0RoToZTIDj2KSLH8dIWZwIWCqYLHAdyqWcBlgB1XE5JeiwvoZQ8lI23yAAksAgFgKjAYgXFyipTfNy3YGtrEVZlgAlaoIA4X5-nMyzrNstaHJKphh1c3KADcQtBCQICsSAYHi0EcfSOO7LpqKknjuAOkj9rJk52ZvjAVY4CYJBc9BAAfdEAGpYArrBRlRIoIGsLBNC6fO66YJ4kCirxK9mwxWQqJ4mAAblG3K8CSEyMsSBu4d23HoHxonZGyDZl7xtW7Yt5gpakGWJd2jGsnzA0gd2sHdv7h359mFe1-Js4t9mM-Rex36KCZTQEckeyjlHKOEcnIJQbkjog0SFA6gN9qCaGZGweyWIH5qEXrAEBSgLoWAgRQKBbknjjyAA) where we set the color of progress to 'auto' meaning it should be taken from the axiline color. and we are hiding the axis line.

In this case when the max limit is negative, the progress color is black/disappearing

**Comment by kingyue737** [comment]
I think it is a bug. The reproduction of OP is a little strange. Here is my reproduction, `max` is bigger than `min`:

https://echarts.apache.org/examples/en/editor.html?c=gauge-multi-title&code=MYewdgzgLgBA5gQwK5wKYBEFQTAvDAbQCgYYBvE0mANwQBslUAuGAWgCYAGAGktLAQBbZjADkAcRAgAJqN5UYUAJZQ6IigtIgAZtoiooAYVRgoqAE4sCo1gBZOAUjliAHI9EBdPjAC-8qtIGCEp0LBqaOnoGxqYWVjb2TtxiAJwArE5eCj6UfpThpLQMInY83gLCLKIAQgZm5nLeyqrq3lq6-kYm9fHuyaJumd55CoHYIWFtMJGdMT2Eon2pGZ7Duf4FNPSMLKwAbGUKFSKiAAoW2qjAUI0KzWqTmtMd0d1xC4nOA-5ZVCMBQQm5CmM1esUsHyWonSQ2yuSIHgA3EQQAAHZTgPDA0j6cxKVAQKzeTakKAAT1RJ0QKFQt00giUYCYrAAjJxDvSEAAPZks_wKBBgYAACxAEJJVAgooA7iwoOZGPzNFKQNKAIIAIxA1BE8sVUxxSgAXiIWS4lQoVKhBABlckPbFPKigOhiqoAYgAYmrDC40i5RAbfFN_gpUSBGfMJaQlKAmWJUVhhUwAPQpgCy7AAdCluJwswB2AAy2dz-YLwBZWdsee42b23Cr7DrWYb9eoLJZaWAPCrtlZWeb9Y4rZbezoPE4wAHNc4I72A_Y8_nADUAMxZteGfNrxs5vezwstsuFo10p7SpTSKDJmDmoNqMBwG9VQbniIvLrgqw8VywzShlQqLmCAcDmAShKOk8KqyooCqoBaVDahYdAIKicrwYhpAgUgYDSIYaEYYwIaIdySgQEWjKtE6MA4XhBHoXBxFPIBpDSFgCAsNSaCYNgiH3NRTraOAUA2sapq2CRUxjMEoRQZol7Xre9hYTAwqoEocDClALAsjWQbCaYYkmrp-k0S6bpiO6ujaO-CgaggwAANZgSAuH4SAroQqIjLqXiNyqVq5iBOYABKCDSEoSCQbuBlioIWDzKIZBFIwPhOCGaykF4PiIkAA

**Comment by Ovilia** [comment]
Thanks. The above demo is a bug.
