### ISSUE TITLE
[Feature] Bar marker line

### ISSUE THREAD

**Issue by DavidMarquezF** [apache/echarts#20103]
### What problem does this feature solve?

There is no way to create marker lines for each bar with an appropriate width. There is a workaround with marker pointers, but the width has to be hardcoded, which means that it doesn't respond to changes in number of bars, redimension, etc.

The workaround:

```
option = {
  title: {
    text: 'Rainfall vs Evaporation',
    subtext: 'Fake Data'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['Rainfall', 'Evaporation']
  },
  toolbox: {
    show: true,
    feature: {
      dataView: { show: true, readOnly: false },
      magicType: { show: true, type: ['line', 'bar'] },
      restore: { show: true },
      saveAsImage: { show: true }
    }
  },
  calculable: true,
  xAxis: [
    {
      type: 'category',
      // prettier-ignore
      data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    }
  ],
  yAxis: [
    {
      type: 'value'
    }
  ],
  series: [
    {
      name: 'Rainfall',
      type: 'bar',
      data: [
        2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3
      ],
      markPoint: {
        data: [
          { type: 'max', name: 'Max' },
          { type: 'min', name: 'Min', coord: [10,10]  }
        ],
        symbol: "rect", 
        silent: true,
        symbolSize: [40,3], 
        itemStyle: {color: "black"}, 
        label: {show: false },
      },
    },
    {
      name: 'Evaporation',
      type: 'bar',
      data: [
        2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3
      ],
   
    }
  ]
};
```

Result: 
![image](https://user-images.githubusercontent.com/32216320/173351664-2496b303-e18b-4401-9333-db332cb3bcc9.png)

This issue was already created: https://github.com/apache/echarts/issues/17210

### What does the proposed API look like?

Add a new option for the bar series `barMarker`, which would have a data property with the ordered value of the markers. It could also just have a reference to a dataset with `datasetIndex`.  Another option would be to have a list of objects with the dimension name and the value to assign (this way you would be able to omit columns).

It should have styling options similar to the ones offered by markPoint:

* Specify symbol (it could be a circle, line, dotted line, etc.)
* Label
* Color
* Etc.

This would allow us to create things like this (photo from apexcharts):
![image](https://user-images.githubusercontent.com/32216320/173351265-79944601-5eb2-4c9d-9a1c-44991e37105f.png)

Another way of doing this would be with the `markPointer` like the workaround but allow to set a custom string for the size (something like `['barWidth', 3]`)

**Comment by Ovilia** [comment]
This can be done with a scatter series apart from a bar series. See [the demo](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=MYewdgzgLgBARgQwE4HUCWATKALGBeGAVgAYBuAKHJAAco1x8YBvcmGADwEF20IAuZqzYwoAT2oBTAQHJgCKBIDmIJKOkAaIWwzyEAgNrSAsuA0xpAFQCuEs9JQSMdi9it2AYkjR2AyvN9WYNIAukIAvppsoty8AizCIuJS5gBuCAA2NtLhkTAQEl4S_DD6WoIJ2roGAIwATMTqMPUNMNUkjQAcLQDsLdXVfQDMxMG5CWKSMohIGmVs0-hY2GUR8RU6UHoldS3NjW0tXY29-wP7w6NziZPmEHJQCjNjwhCiALZwIOkCABRpmRJGtRkAg3hAAJT4AB85QqbCQEigViQYBgwKQoIgADoNggAJJgDASdj4PAEWowAD85mAaCQwHSthgMgRwCg0gocIiV1eHy-PjQAC9kn8MjYgSCwZC8DC1nCEUiUWjJdjcQSiSSyeSqU1iMySgtMDhGoRgpyKty4bzPukAPIAM3t-Sgv3-4uVGKl0Nh8sRyNR6MxON06uJpO1VwS1P0LRIwRgkeEBhaRnk2CxGMJIDeP0hACoYMMYABaVqmq5hFZCUJhUhAA).

**Comment by DavidMarquezF** [comment]
Perfect, thank you!
