### ISSUE TITLE
[Feature] echarts实现点击图标全屏 有没有全屏的属性

### ISSUE THREAD

**Issue by Zaodianshui0928** [apache/echarts#20112]
### What problem does this feature solve?

echarts实现全屏浏览

### What does the proposed API look like?

1

**Comment by plainheart** [comment]
借助浏览器全屏 API 即可。 [Demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsBGBDAxgawHMAnYAV2gBMBhYAG2CIC5YByAYgDMuWAaNWMMDoZgAD2ap06DgFMsYUkRkT-U2AFsAngDFStWgGccSmdBVq1BgBbAA7szBFSMvhamQwtZa0AWioHkdXlULCBwYZhYQeStGAHoYgFkAZgBWAA4AOgAWWAB2ADZUgAlMgCY89LzKypyAN1Tk9MSm5sKSgEZExuammoBads7upqt6rubMmoL0sqqc2jaS1N6F1NhkgE50nKG1ze3u5cXYFYAvDUTMhrzYAAZaQ6WV3a2h3o2X7uPEkumqvJyvj8ZlUAGp5TI3EYNIaJGoDMbNKz9DoInq9UYwqzgk5JNJZWAldYZP7_eZHFZvPY7d77ZoPB4g0rlEk5VoomEg-GYrndCYY3mFFIZTJndQXK63Qrgm6c9lDKw87pwuXjJH87oglKZdIdbr3DpAv4Ag2_WaUj50mk7CmnQJudAwHC0EJ4Zgccg4SAwWAACgAlMggm4KMAcKR1KYwOl3fojCZoABRLwR6BgIP2gD8sBDYZTUZkoggYF0seMMlM_vTbmYWioViwRCjBBkYAAIsB1P70koAI7OAzFvSGMsVv0AbirsAAvumZ2o59PXLBRABBQsGczuTQgbwsHDyGQEBiaO1SCjyLDMADaLHiMF4rAAKs4HywAOoyCivx9WUiv7REBAr4AMryCB5AsAAuvwU5Lpoa4QBugZqGA267jUWC0C-MFLgYMiATISFXkEkgWOeYCXrAV5tMkNw8ASiR0QSJSZPR7SpPRHTJJxmQ5GxeQ3JBS4oWh4TOtAMgsEEC7QVOE4oLW9aNukzZth2XZYBQFAJjUkYADKIWApj4T6LAxsO8Y4PW0DNg-pAgORMglhZ5bQI-RZeOOKAoO60CelAcD2Y5zlxq57meDI_rIRomh1g2UZ4WAADy4ABT6pHoIIwhiJuaiyPIijeBlFhaCFI5mNF9oCB53g5uGkbRkOoWmEmMh5rAWYsIAAAmAF-K_gsLA4T9ZOC7ztJMFeVOQA)
