### ISSUE TITLE
[Feature] legend.formatter希望可以像tooltip.formatter一样支持返回 HTML 字符串或者创建的 DOM 实例

### ISSUE THREAD

**Issue by superYe7** [apache/echarts#20118]
### What problem does this feature solve?

使用legend时只能通过配置项或rich修改样式，但是可配置的内容非常有限，比如我无法实现图例换行后居中对齐（如图）。希望formatter可以支持返回一个HTML，同时通过入参将图例的icon、名称、是否选中等信息返回，这样可以在使用时自由配置图例样式。
![image](https://github.com/apache/echarts/assets/38695007/08f8badd-2239-4761-99f6-e0329311f400)

### What does the proposed API look like?

// 使用字符串模板，模板变量为图例名称 {name}
formatter: 'Legend {name}'
// 使用回调函数
formatter: function (name) {
    return 'Legend ' + name;
}

**Comment by plainheart** [comment]
legend 就不是用 HTML 渲染的，怎么会支持返回 HTML 呢？这种需求通常可以自行使用 HTML 创建 legend 元素，然后借助 ECharts [API[](https://echarts.apache.org/api.html#echarts) 实现事件处理。
