### ISSUE TITLE
[Bug] 当使用svg渲染，折线图使用渐变色时，series中data数据都相同时折现无法显示

### ISSUE THREAD

**Issue by renqiankun** [apache/echarts#20127]
### Version

5.5.1

### Link to Minimal Reproduction

https://codepen.io/renqiankun/pen/zYVYzXN

### Steps to Reproduce

1当使用svg渲染，2折线图使用渐变色时，3 series中data数据都相同

### Current Behavior

折现图无法显示

### Expected Behavior

同canvas渲染可以展示折现

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by renqiankun** [comment]
Expect SVG to also display

**Comment by plainheart** [comment]
Duplicate of #15467

**Comment by plainheart** [comment]
之前已经研究过这个问题，后面我会再跟进下。
