### ISSUE TITLE
[Bug] Bar Height Differences in Normalised Stacked Charts

### ISSUE THREAD

**Issue by badger-github** [apache/echarts#20126]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=bar-stack-normalization-and-variation&code=PTAEBUAsFMCdtAZ0gewK4BsAmoB2KAXUAIwV2gHMBDAgSwDcF6qM1pFRbdRYqB3ACI0qAKFDiJk8QGMUuREV6DhoALygA2mKk6NARgBsBgHQAOACwAacwCZjB05YAMlvXvvmAupe07JGgFYzG0sg0xD3AE4rKK8fPykNA3NjJxDTAHZjAGZQkxsDSxssw29fBM0Ap2NzKwzs4wyI7IbTQozI4wC48oSNFxdOjKL3bJ6KiU8AbhFZeSICQhYhAio1TWmRADMUWFAACgxoIlp1pynOUAAeHn4Vqn7PYyPcCgJIC4BqT9oASlAAN7aI5ERBoAC2Zxm4h2e0Ox1AACsoUjrrdlKtntBXu8vp9Ef8gZIwZDPuolPcNIjPBpaJtxABfbSLVYYe7GAAOaGQ-xJvxmTLmClAFFgtBw6iJoCOWwIAC5QHonC5tGKKJB5YrlfFQIsOQqqjriIRFuCDU4RAyZkKiKLxQB1cXvdbggCeAGFIFRYARjBRjo6sO99v8ALQisVYLGy0Dhu1RtUa61yYXxgAS0Fo6qI6jdnu9vv9BAzWY1IdjEfFxj1FfjxmNBFNyfmoGkNEou1dged6nj3cgoDAFOEjyxOI-sxTRGI3v76zbBA7sC7ToHACpQNUDM3hTPYAAFKhYLBcCjrfYLpcroMD8N7_v_MA2HeguC0djrLTiADkAlo8GkAhvx1b8AFkqFoDBQAAQSwYDtG_aCti2SDaHbGC4JAgA1cVoBQDD4J_ABlaBvWkAcAFFXi4aBvxEJ5wSoDl9n2XAqHBaBLCQcV_lUAA-QFVWONBYG4KVxDYjidXEAhXQ5aAFW_PdCIkBQqGkABrRSWRYFTxHvVdFIMJwAFI9OlKhSAwBVxNU1A-AVAhYDYaSJFhRjGzgBV9g5b12MQXiBPA95jFgdBcCwHy_PBRBjGYVgEA3JVlUfLVQE-UBvzM8oGVcrBhAVYdVg0RBxQYpiWKwLiTywQLel1JY2RHGrPGudQnFAAB-TdQAVHAwB0pripa8pfm0K1LX5ScW1kDBdk_b8AGJugyJxpAMYDMsWyI9GkaQMgCTalq2dTTACUwjsW6BoCMIxLvqaQnCwWjNhtUBoCODjcAIDh1A0TZYQOEFUXUPQuMRF51iKh4nCeF43g-VEbgh7E8QJQSZCnaVoFlAANdY6xlIgMsvChOznDdkTvb1D2PU9oVbLHEwIfH1CJ_GMr3WmT1eUAN2fYEESJgBNAnI2rFAOXSyssBLbMGeB5nRbZnGCGFhnAfhE4zi4yH1EQN92DHBGLlOG4XjxP4MYkN6ORQLgfs_ekbaxomACFvTljVz2h2kaSpxVWoGxrKQDvRPH-Dd00zeXyjth3Yq5HkNHZ3XVeFiOGfEePvsT7lIH2FPVdxtPZVF8N3c9mONUz8o3uZj3YC9nMDl9ukqSDhrWVDiO-Zl5us9AHOfs5fPC-ZkueFLNWKwbqvp9ryRh7z5OJ64pXF4kZfR-T1PsbLzfxBF2MVdlRuB_KJWT6n7Nz-rghB4-6AvpHpOC9smS5IUzK7YwV0ydwOZcQyAmLfw_lve2ud6q5XqgoV0RwbL1RhJBayjM5qwD9q5SQkt1K0FkgqaoNgAjQJylNRkloRCSzoHIdYUojj-giog4kT9ALQCwKBFAz0FQnQwAbcaOp4w6ldNBAAHrQRATCJCyXkopeKbA6KMh1CI0R4jJGfxkZlUmnZzL5VWAqDQYE5BHXAPIri357RsOMZANA35PD8O0AbMU7ABG8A5JAWg0g1HvU-tiH641LRTCAA

### Steps to Reproduce

Simply view chart with rawData - it is obvious visually when using Normalisation and Variation because the variation bars are the correct height and so graph looks very strange

### Current Behavior

Bars are smaller when using 0 in first array, if use 0.1 bars are correct height

### Expected Behavior

Bars should be correct height for graph

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox
- Framework: Vanilla
```

### Any additional comments?

Not Working (Bars Lower than they should be using a 0 in the rawData first line)

https://echarts.apache.org/examples/en/editor.html?c=bar-stack-normalization-and-variation&code=PTAEBUAsFMCdtAZ0gewK4BsAmoB2KAXUAIwV2gHMBDAgSwDcF6qM1pFRbdRYqB3ACI0qAKFDiJk8QGMUuREV6DhoALygA2mKk6NARgBsBgHQAOACwAacwCZjB05YAMlvXvvmAupe07JGgFYzG0sg0xD3AE4rKK8fPykNA3NjJxDTAHZjAGZQkxsDSxssw29fBM0Ap2NzKwzs4wyI7IbTQozI4wC48oSNFxdOjKL3bJ6KiU8AbhFZeSICQhYhAio1TWmRADMUWFAACgxoIlp1pynOUAAeHn4Vqn7PYyPcCgJIC4BqT9oASlAAN7aI5ERBoAC2Zxm4h2e0Ox1AACsoUjrrdlKtntBXu8vp9Ef8gZIwZDPuolPcNIjPBpaJtxABfbSLVYYe7GAAOaGQ-xJvxmTLmClAFFgtBw6iJoCOWwIAC5QHonC5tGKKJB5YrlfFQIsOQqqjriIRFuCDU4RAyZkKiKLxQB1cXvdbggCeAGFIFRYARjBRjo6sO99v8ALQisVYLGy0Dhu1RtUa61yYXxgAS0Fo6qI6jdnu9vv9BAzWY1IdjEfFxj1FfjxmNBFNyfmoGkNEou1dged6nj3cgoDAFOEjyxOI-sxTRGI3v76zbBA7sC7ToHACpQNUDM3hTPYAAFKhYLBcCjrfYLpcroMD8N7_v_MA2HeguC0djrLTiADkAlo8GkAhvx1b8AFkqFoDBQAAQSwYDtG_aCti2SDaHbGC4JAgA1cVoBQDD4J_ABlaBvWkAcAFFXi4aBvxEJ5wSoDl9n2XAqHBaBLCQcV_lUAA-QFVWONBYG4KVxDYjidXEAhXQ5aAFW_PdCIkBQqGkABrRSWRYFTxHvVdFIMJwAFI9OlKhSAwBVxNU1A-AVAhYDYaSJFhRjGzgBV9g5b12MQXiBPA95jFgdBcCwHy_PBRBjGYVgEA3JVlUfLVQE-UBvzM8oGVcrBhAVYdVg0RBxQYpiWKwLiTywQLel1JY2RHGrPGudQnFAAB-TdQAVHAwB0pripa8pfm0K1LX5ScW1kDBdk_b8AGJugyJxpAMYDMsWyI9GkaQMgCTalq2dTTACUwjsW6BoCMIxLvqaQnCwWjNhtUBoCODjcAIDh1A0TZYQOEFUXUPQuMRF51iKh4nCeF43g-VEbgh7E8QJQSZCnaVoFlAANdY6xlIgMsvChOznDdkTvb1D2PU9oVbLHEwIfH1CJ_GMr3WmT1eUAN2fYEESJgBNAnI2rFAOXSyssBLbMGeB5nRbZnGCGFhnAfhE4zi4yH1EQN92DHBGLlOG4XjxP4MYkN6ORQLgfs_ekbaxomACFvTljVz2h2kaSpxVWoGxrKQDvRPH-Dd00zeXyjth3Yq5HkNHZ3XVeFiOGfEePvsT7lIH2FPVdxtPZVF8N3c9mONUz8o3uZj3YC9nMDl9ukqSDhrWVDiO-Zl5us9AHOfs5fPC-ZkueFLNWKwbqvp9ryRh7z5OJ64pXF4kZfR-T1PsbLzfxBF2MVdlRuB_KJWT6n7Nz-rghB4-6AvpHpOC9smS5IUzK7YwV0ydwOZcQyAmLfw_lve2ud6q5XqgoV0RwbL1RhJBayjM5qwD9q5SQkt1K0FkgqaoNgAjQJylNRkloRCSzoHIdYUojj-giog4kT9ALQCwKBFAz0FQnQwAbcaOp4w6ldNBAAHrQRATCJCyXkopeKbA6KMh1CI0R4jJGfxkZlUmnZzL5VWAqDQYE5BHXAPIri357RsOMZANA35PD8O0AbMU7ABG8A5JAWg0g1HvU-tiH641LRTCAA

Working (Bars correct height using a 0.1 instead of 0 in rawData first line)

https://echarts.apache.org/examples/en/editor.html?c=bar-stack-normalization-and-variation&code=PTAEBUAsFMCdtAZ0gewK4BsAmoB2KAXUAIwV2gHMBDAgSwDcF6qM1pFRbdRYqB3ACI0qAKFDiJk8QGMUuREV6DhoALygA2mKk6NARgBsBgHQAOACwAacwCZjB05YAMxvZb1775gLqXtOyQ0AVjMbSxDTMM8ATisYnz8AqQ0Dc2MnMNMAdmMAZnCTGwNLGxzDX38kzSCXcyss3OMsqNzG02Ks6OMghMqkjSdnSy6sks9c3qqJbwBuEVl5IgJCFiECKjVNWZEAMxRYUAAKDGgiWk2nGc5QAB4efjWqAe9jE9wKAkgrgGpv2gBKUAAb20JyIiDQAFsLnNxHsDsdTqAAFYwlG3e7KdavaDvT4_b7IwEgyQQ6HfdRKR4aZHeDS0bbiAC-2mW6wwj2MAAc0MhDmT_nMWQsFKAKLBaDh1CTQCcdgQAFygPROQbaCUUSCK5WqxKgZZcpU1PXEQjLSFGpwiJlzEVEcWSgDqks-m0hAE8AMKQKiwAjGCinZ1YT6HQEAWjFEqwOPloEjDpjGq1trkosTAAloLRNUR1B7vb7_YGCFmc1qw_Go5LjAaq4njKaCObU4tQNIaJR9u7g671Ine5BQGAqcJnji8V95mmiMRfYPNh2CF3YD2XUOAFSgFwGVuiuewAAKVCwWC4FE2hyXK7XIaHkYPg8BYBse_BcFo7E2WnEAHIBLQ8DSAQv56r-ACyVC0BgoAAIJYKB2i_rBOw7NBtCdnBCFgQAapK0AoFhiF_gAytAvrSEOACi7xcNAv4iC8kJUFyhyHLgVCQtAlhIJKgKqAAfMC6qnGgsDcDK4gcVxeriAQ7pctASq_gexESAoVDSAA1spbIsGp4iPuuykGE4ACkBmylQpAYEqknqagfBKgQsBsLJEjwsxzZwEqhxcr6nGIPxQmQZ8xiwOguBYH5AWQogxjMKwCBbiqqrPjqoDfKAv4WZUTLuVgwhKqO6waIgkpMSxbFYDxZ5YMFfT6isHJjnV3i3OoTigAA_NuoBKjgYB6S1pVtZU_zaDa1qCtObayBg-zfr-ADEPRZE40gGKB2XLdEejSNIWRBNtK07JpphBKYJ3LdA0BGEY10NNIThYPR2x2qA0AnFxuAEBw6gaNs8JHGC6LqG4KJvJsJVPE4LxvB8XzoncyJvASRLCTIM6ytA8oABqbA2cpEFl14UN2C5bqiD6-sep7nrC7bY8mBAE-oxME1lB502e7ygFur6gkixMAJqE9GtYoFymXVlgZa5ozoMs2L7O4wQIuM8DiJnBcPFQ-oiAfuwE6I1c5x3GjmV_MSlQfVyKBcH936MhIH3EwAQr68tapeMP0nS1PKu1Q3NdSgd6N4gJbpm2YK5U9uO_FPJ8hoHN62rIuR4z4gJ79Se8pAhyp2rePp_KYuRh7Xux1qWe28z5YEJ7sDe3mRx-wyNLB017Jh5H_Oy632egLnf3cgXRcs6XPCNxXM-5s3rd15Io_5ynU88cry8SKv48p2nOPl9v4ii_GqvyovNcEMPytn_PWqX43w9fdAP1j8nhf2XJClKdl9sYO6cmuBLLiGQCxX-X8d4Ozzo1fKjUFDuhOHZRqcJoK2SZgtWA_t3KSClppWg8klQuBsEEWBeUZrMmtCIKWdA5CbBlCcQMUVkGkhfsBaAWBwIoFekqM6GBDaTT1ImPU7pYIAA9aCIBYRIeSillKJTYAxZkeoxHiMkdI7-cjspk27JZQq6wlQaAgnIE64BFE8V_I6DhpjIBoF_N4QR2hDYSnYEI3gXJIC0GkBoz631cR_UmtaGYQA

**Comment by helgasoft** [comment]
It seems the problem is with _graphic_, the stacked bars look correct and identical in both examples. Also be aware that the _graphic_ elements are not responsive and will change on chart resize.

**Comment by badger-github** [comment]
Thank you very much for your comment, it made me look at it again from a different perspective, the issue is simple that I need to set a max: 1 on the Yaxis - this prevents the charts going to 1.2 when the bar is at 1.  Seems to fix my issue anyway.

  yAxis: {
    type: 'value',
    max: 1
  },
