### ISSUE TITLE
[Bug] 5.5.0版本无法进行手动高亮饼图，其他图没有问题

### ISSUE THREAD

**Issue by Jackwew** [apache/echarts#20134]
### Version

5.5.0

### Link to Minimal Reproduction

5.5.0

### Steps to Reproduce

```js
export const option = () => {
	return {
		title: {
			text: '饼图程序调用高亮示例',
			left: 'center'
		},
		tooltip: {
			trigger: 'item',
			formatter: '{a} <br/>{b} : {c} ({d}%)'
		},
		legend: {
			orient: 'vertical',
			left: 'left',
			data: ['直接访问', '邮件营销', '联盟广告', '视频广告', '搜索引擎']
		},
		series: [
			{
				name: '访问来源',
				type: 'pie',
				radius: '55%',
				center: ['50%', '60%'],
				data: [
					{ value: 335, name: '直接访问' },
					{ value: 310, name: '邮件营销' },
					{ value: 234, name: '联盟广告' },
					{ value: 135, name: '视频广告' },
					{ value: 1548, name: '搜索引擎' }
				],
				emphasis: {
					itemStyle: {
						shadowBlur: 10,
						shadowOffsetX: 0,
						shadowColor: 'rgba(0, 0, 0, 0.5)'
					}
				}
			}
		]
	}
}

let currentIndex = -1;

setInterval(function() {
  var dataLen = option.series[0].data.length;
  // 取消之前高亮的图形
  myChart.dispatchAction({
    type: 'downplay',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
  currentIndex = (currentIndex + 1) % dataLen;
  // 高亮当前图形
  myChart.dispatchAction({
    type: 'highlight',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
  // 显示 tooltip
  myChart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
}, 1000);
```

### Current Behavior

5.5.0版本无法进行手动高亮饼图，其他图没有问题

```javascript
instance.dispatchAction({
					type: 'highlight',
					seriesIndex: 0,
					dataIndex: 1
				})
```

当seriesIndex 设置为0时会报错
信息如下： 
![image](https://github.com/apache/echarts/assets/50656464/c7bbf005-ab87-408e-b172-e9c1a6d0cd13)

### Expected Behavior

期待正常高亮饼图

### Environment

```markdown
- OS: macos sonoma 14.5
- Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Framework: react 18
```

**Comment by Jackwew** [comment]
Found the problem
```javascript
// good
let currentIndex = -1;

setInterval(function() {
  var dataLen = option.series[0].data.length;
  // 取消之前高亮的图形
  myChart.dispatchAction({
    type: 'downplay',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
  currentIndex = (currentIndex + 1) % dataLen;
  // 高亮当前图形
  myChart.dispatchAction({
    type: 'highlight',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
  // 显示 tooltip
  myChart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: currentIndex
  });
}, 1000);

// bad
  var dataLen = option.series[0].data.length;
  // 取消之前高亮的图形
  myChart.dispatchAction({
    type: 'downplay',
    seriesIndex: 0,
    dataIndex: 1
  });
  // 高亮当前图形
  myChart.dispatchAction({
    type: 'highlight',
    seriesIndex: 0,
    dataIndex: 1
  });
  // 显示 tooltip
  myChart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: 1
  });
```
Why do errors occur when setting the first or other dataindexes separately？
Can someone help me solve this problem?

**Comment by plainheart** [comment]
你是 setOption 之后，立即调用 dispatchAction 吗？需要等一下，比如加上一个 setTimeout(() => { // ... }, 0)

**Comment by Jackwew** [comment]
> 你是 setOption 之后，立即调用 dispatchAction 吗？需要等一下，比如加上一个 setTimeout(() => { // ... }, 0)。
> 
> 
> 
> [Demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOSA-mYH9qg0F6DxeoMAxgFK6AbWYHVygXJ6DR8pQBoi6XADMKsSgGMc0MDgBOlIgF8h6MMGBZIIAqmIYFEAOYnFVCPIC2y9GqK5z0ACb7hsYMdkTKAN0VIKQBDLEEPMV9I8MMXYLBgggBtSkAXt0BS40B-6MA71MFJQDqEwDe5QFIQwABUvMpAFQDAfbdAfz1AKRUKwDHIwESMhorAHBNAIl9AVH1AOZNKAF1VdVgAZ0UIHDHkjwNDWGhg63xJHMBTc0AEuxiFsABPEFXKECmdwwVglwgAVxnJAFZ7gFIz4hk5C1gU-4AGF4FJAA2P5DUaxeKJL4eQxIWB-ULXVYAZiR9wBSxWVAyOUosAcC2IsPhWERBCRAEYfujlkcimVcfiCcg4QjVgAmJEAFmpmMkNXaeLBCyJrII5NRPKOrQFjIJIpJq3J905AA5JVRuv0GdDYIMhegcNYQAALYJjCB3eYEqyGgDK-1w7iZxDGppcwAA7gAhEkKMVUnWGV2XT0AeVEogmYAAGgQA870MH3R6AMLaLxUBQmABGwQAFFTYIXiwA6e4ASjsTJUOprhjrupQKgA3CgULgwLApNcFAofABJVxkBCwAC05NbKCjABUICtgNcwHnRNdoFJIDBYHny4R0PCFLA4gkADKyEegDfQEsTbxjJI_QYlo_BEu4aAmMDG1voAD0P9ggBryoAEbaANJygCySlwgAhbrQgBG-kQ1h7CmpoKGAT4WiA8RSMaACC65QNAeZWhgBxHMm0AgFgwR7K8N5TGMg4uGQcZCs-DFMV2PZ9nIbGkKo5bfhxvYDkOpAjnm3ZCdxImwAA1LA5I7k8h4Qqe0ACX-sBcIAyvpgbB8GIchqFXGMGFgFhuGXoRHj7IcVDGqYxpYA5YA0ZM0w8cxHisSJBASVxYA8Xx6n_oAfGbcBgWg6BAID6UhwQoWhJmYTheEwFZhg2UcrqerOICubeHlFixEKFX5wmMbx9j8U2AI_PxQA)

不是的，我是在echarts渲染完成后调用高亮函数的

**Comment by plainheart** [comment]
贴下代码片段，看看怎么写的。
