### ISSUE TITLE
Is there any option to generate pdf for chart

### ISSUE THREAD

**Issue by Abhishek-Jetani** [apache/echarts#20142]
### What problem does this feature solve?

easy to  generate pdf

### What does the proposed API look like?

getDataURL({ type: 'pdf' });

**Comment by helgasoft** [comment]
duplicate of #5181
Try [this solution](https://codepen.io/helgasoft/pen/jOQjzBy). It uses 3rd party library _pdfmake_.
📌 please close issue if problem solved.

**Comment by Abhishek-Jetani** [comment]
thank you

**Comment by Abhishek-Jetani** [comment]
@helgasoft thank you
