### ISSUE TITLE
[Feature] the radar Labels display on the periphery of the series line

### ISSUE THREAD

**Issue by comvir** [apache/echarts#20140]
### What problem does this feature solve?

look like sketch
![image](https://github.com/apache/echarts/assets/7907986/6da5a889-cc82-410a-ba94-f22d4b076a8a)

### What does the proposed API look like?

```
type:"radar",
label:{
    //optional words: periphery、edge、ring
    position:'periphery'
}
```

**Comment by helgasoft** [comment]
see [data.label](https://echarts.apache.org/en/option.html#series-radar.data.label.show)
![image](https://github.com/apache/echarts/assets/13038071/08b6b8ca-99c0-47d1-9eea-8c56431064b0)

📌 please close issue if problem solved.

**Comment by comvir** [comment]
> see [data.label](https://echarts.apache.org/en/option.html#series-radar.data.label.show) ![image](https://private-user-images.githubusercontent.com/13038071/347610472-08b6b8ca-99c0-47d1-9eea-8c56431064b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTc2NTEsIm5iZiI6MTcyMDY1NzM1MSwicGF0aCI6Ii8xMzAzODA3MS8zNDc2MTA0NzItMDhiNmI4Y2EtOTljMC00N2QxLTllZWEtOGM1NjQzMTA2NGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAwMjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MWEwMzZkOWM4Y2JlMzg1NTFkZTFiNDY2ZjI5ZmIyYmRlNGVhMmVmY2FhZjAwMTYzY2ZjNTQxNjBjN2JkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmWItYlBK2lUJ_PH-6jVt8bVFqNl25ie63OmEU7pS0I)
> 
> 📌 please close issue if problem solved.

It doesn't seem to meet expectations. Labels need to be displayed on the periphery of the outline of the series line.

**Comment by Ovilia** [comment]
Labels should be shared with different series in the same radar chart. So it's theoretically wrong to should labels at the position of one series. That being said, you could use `label.formatter` to decide what text to be displayed.

**Comment by comvir** [comment]
> Labels should be shared with different series in the same radar chart. So it's theoretically wrong to should labels at the position of one series. That being said, you could use `label.formatter` to decide what text to be displayed.

You're right, I'll educate our designers
