### ISSUE TITLE
[Bug] Echarts 内存泄漏

### ISSUE THREAD

**Issue by promise6512** [apache/echarts#20141]
### Version

5.5.0

### Link to Minimal Reproduction

no

### Steps to Reproduce

使用react + echarts 开发的数据大屏，会实时更新数据，重新渲染，大屏放久了会崩溃，排查发现很多 detached HTMLDivElement 被 echarts 中的 EcEventProcessor 引用，有人碰到过类似的问题吗？ 崩溃是必现的
![image](https://github.com/apache/echarts/assets/86681329/0edd88f2-12b1-4b1f-9037-aebaa66b0437)

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS: MacBook Pro M1
- Browser: chrome
- Framework: react16
```

**Comment by plainheart** [comment]
感谢反馈，不过内存泄漏问题一定得有一个简易能够复现的例子，才好方便我们排查，节省大家时间。

**Comment by idealy233** [comment]
> 感谢反馈，不过内存泄漏问题一定得有一个简易能够复现的例子，才好方便我们排查，节省大家时间。

文档中的例子就可以复现，只需要高频次（1s）或者大数据（1000+）或者多图表（3+）然后调用setoption就可以明显复现。

**Comment by plainheart** [comment]
浏览器无痕模式也测测看，有的可能是某些扩展插件影响的。

**Comment by plainheart** [comment]
@promise6512 如果你也是用的 line 系列，看看是不是跟 #20151 类似？
