### ISSUE TITLE
[Bug] Default value of barCategoryGap and  barGap not as described in the document

### ISSUE THREAD

**Issue by innerWang** [apache/echarts#20148]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMgL4A0as2ApgOaXQAmhSp5AHgIKsQDOT569AIZhBhANoAiALIwJJWBIAqAV0pyFAdUr11SgBbLdAMQBOEXQGVhl5dAkBdci3QBPTjybPY3Smcq9YMVR0dGhBAFtKQgkrKjl-DBcQKIUAI0ETeJDYIRFxAFZ5ACYABnkAZgA2eQBGMtg64vqAFkd0IkciIA&_source=echarts-doc-preview

### Steps to Reproduce

1. Use the example of https://echarts.apache.org/zh/option.html#series-bar.barCategoryGap
2. Edit the example, set barCategoryGap as  '20%' , will found the bar width and gap changed,  set barCategoryGap as '31%', bar width and gap not changed
3. Add another series, set barGap as '30%', will found bar width and gap changed, set barGap as '20%', not changed

### Current Behavior

Description is inconsistent with behavior。

In the document,  default value of barCategoryGap is '20%'， default value of barGap is '30%'.

### Expected Behavior

I expect the description to be consistent with the behavior。 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
API for both barGap and barCategoryGap  says _"this attribute is shared by multiple 'bar' series"_. This means they should be defined once in a single bar series.
