### ISSUE TITLE
[Feature] Get coordinates of series area

### ISSUE THREAD

**Issue by FrontendTerminator** [apache/echarts#20154]
### What problem does this feature solve?

I created chart based on your library. I want to add some custom feature and I need to know coordinates (x1, x2, y1, y2) of series area. The screenshot shows the area I'm talking about:
<img width="1155" alt="2" src="https://github.com/user-attachments/assets/b2e233fc-5075-4c9b-8015-3ab43032b7c4">

It would be great if you add some api to get coordinates 

### What does the proposed API look like?

I don't have any code examples, just asking to add it. Thanks

**Comment by helgasoft** [comment]
for (x1, x2, y1, y2) try (0, [getWidth](https://echarts.apache.org/en/api.html#echartsInstance.getWidth), 0, [getHeight](https://echarts.apache.org/en/api.html#echartsInstance.getHeight))
📌 please close issue if problem solved.

**Comment by FrontendTerminator** [comment]
> Have you tried the [`convertToPixel`](https://echarts.apache.org/api.html#echartsInstance.convertToPixel) API?

It solved my issue. Thank you

**Comment by FrontendTerminator** [comment]
Ticket can be closed
