### ISSUE TITLE
[Bug] Echart setoption内存会随时间增长且无法回收（必现）

### ISSUE THREAD

**Issue by idealy233** [apache/echarts#20151]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Ftutorial-dynamic-data

### Steps to Reproduce

这是贵官网文档的示例，复现步骤如下
1、将该网址使用chrome浏览器访问
2、打开开发者工具，打开内存tab页面
3、在几分钟的时间周期内点击录制按钮
4、观察每个快照的内存情况
此时可以发现内存会一直在增大，且无法清除。
![1720769661275](https://github.com/user-attachments/assets/483222c3-2efa-4d5a-8971-e7511034ace3)

### Current Behavior

该内存在三分钟的时间内涨了1MB，而且这是数据量小且只有一个图表的情况，如果是多个图表或者增加数据量（data），那么内存增加的会更加明显。

如上所述，如果链接不可用，这边还可以提供代码。

### Expected Behavior

在业务使用过程中，多次调用setoption不应存在内存上涨且无法降低的情况。

### Environment

```markdown
- OS:Windows 11
- Browser:Chrome
- Framework:Vue@3
```

### Any additional comments?

业务中不可以clear图表（会造成数据显示错误），此时在多次动态更新数据图表后（时间较长时）页面必定崩溃

**Comment by plainheart** [comment]
用浏览器无痕模式（即不加在任何扩展插件等）测试一下看看，对比下结果。

**Comment by idealy233** [comment]
> 用浏览器无痕模式（即不加载任何扩展插件等）测试一下看看，对比下结果。
chrome的无痕模式运行5分钟四次快照结果 中间每次都点击回收垃圾
结果还是内存会有增长，问题依然可以复现
![image](https://github.com/user-attachments/assets/e9994130-a04e-4de9-8719-3b96981856cd)

**Comment by plainheart** [comment]
我使用无痕模式在未加载任何扩展的情况下，内存占用几乎不变。

**Comment by idealy233** [comment]
> Measuring _usedJSHeapSize_ usually gives a good idea about memory leaks, see #19984.测量 usedJSHeapSize 通常可以很好地了解内存泄漏，请参见 #19984 。 Adding the same code here:在此处添加相同的代码：
> 
> ```
> cnt=0;
> setInterval(function () {
>     if (cnt++ % 20 ==0) console.log(performance.memory.usedJSHeapSize);
>    ...}, 500)
> ```
> 
> produces the following numbers:生成以下数字：
> 
> > 34088105, 26805145, 32471229, 28301814 31722715, 34552112, 29943652, 32546547, 32307095, 29559186, 29551095, 29960710, 30817662, 27309092, 25565771, 31258954, 28833919, ...
> 
> which **do not** show evidence of a memory leak.没有显示内存泄漏的证据。

1、usedJSHeapSize获取内存方式有效的情况下：
需要注意的是这个内存溢出的问题在数据量小时并不明显，在您的回复的例子中是每10秒进行一次的内存检查，这样获取的数据您是否试过长时间获取呢？比如1个小时，或者可以在例子中增加数据量的显示来减少测试的时间（比如增加x轴显示的数据量）
2、（重要）为什么chrome浏览器的无痕模式，运行该示例内存会随时间增长且无法消除？（usedJSHeapSize有效性存疑？）
这个问题是如何导致的？是chrome浏览器的问题，还是代码的问题？是否可以就此问题给予一定解释
（同时我稍后将在edge和firefox的浏览器验证是否可以复现该问题）

**Comment by idealy233** [comment]
经过测试 edge上和chrome问题一样，firefox内存不太明显。

发现一个情况，看看对分析是否有意义：
1、开发环境是vue3
2、对比官方例子中内存溢出的比较，自己的代码明显溢出速度更快，而且分布在array内存的溢出更多（而官方例子比较均匀且complied code溢出占用多）
3、确认了，只注释掉setoption这一行代码后 内存一点都不会溢出（可以排除本身代码问题）
![image](https://github.com/user-attachments/assets/a2e0b537-74f2-410b-b546-a5205146cc6b)

**Comment by plainheart** [comment]
> 开发环境是vue3

是不是把整个 data 深度监听了？用了 ref 或者 reactive？

**Comment by idealy233** [comment]
> 是不是把整个 data 深度监听了？
data之前确实是深度监听，所以怀疑是这个问题已经调整和官方案例相同了，换为了setInterval，结果还是比较快的涨内存
>用了 ref 或者 reactive？
因为是vue子页面的缘故 prop的data确实用了reactive，这边尝试改一下再看
>chart 实例对象用 ref 声明了？
chart实例用的let声明的没有用ref
> 运行一段时间后，内存有所小的增长是正常的，因为内部会缓存一些东西。
嗯嗯 小的内存增长业务也是接收的 这边调整之后再观察看下

感谢回复！

**Comment by idealy233** [comment]
已经移除了所有reactive，页面无 ref 和 data 深度监听 
![image](https://github.com/user-attachments/assets/9d5cb956-dab9-489f-964b-4d37b742e4df)
依然有很明显的内存增长，且array在其中依然占比很明显
![image](https://github.com/user-attachments/assets/c5536eab-ff51-4a19-8e19-cc004588782d)

**Comment by idealy233** [comment]
纯js开发在如今是否不太现实，如果确实是vue3框架导致的，是否可以跟踪下vue3等常用框架下的导致内存溢出的兼容问题？
例如在上述例子中，已经尽可能避免使用watch deep或ref等可能造成内存问题的代码，仍无法有效的避免内存快速增长的问题

**Comment by plainheart** [comment]
> 感觉业务系统的纯js开发在如今不这么现实。

使用第三方框架导致的内存泄漏通常不是库本身应该考虑的事。因此建议使用纯 JS 复现问题，以便确认是否为库本身问题。

中午使用 issue 提供的例子（下载为 HTML） 测试跑了几个小时仅有 1MB 左右的少量增长，未发现明显的内存泄漏问题。

**Comment by idealy233** [comment]
找到原因了，并不是vue watch deep或者ref之类的问题导致的。
而是当series的symbol项未设置或者设置为非none（因为默认值是circle）导致的，
当设置如上时，在反复setoption时，array占用的的内存会随时间一直增长，且无法释放。

**Comment by plainheart** [comment]
@idealy233 看起来好像还真和你说的有一定关系，LineView render 函数里动态创建 `changePolyState` 箭头函数以改变 this 指向这里占用了过多内存，稍后我来改一下。

| Before | After |
| :----: | :----: |
| ![image](https://github.com/user-attachments/assets/7c4003dd-e775-482e-9808-0c1451b59477) | ![image](https://github.com/user-attachments/assets/16818680-7dfa-410f-a71c-158c0a992da5) |

**Comment by gpcwhitecap** [comment]
Line的series的symbol项设置为none，内存也涨

**Comment by ZedCoding** [comment]
watch(
  () => props.option,
  (newOption) => {
    if (!chart) return;
    const optionValue = toValue(newOption);
    chart.setOption(optionValue, !chart.getOption());
    if (props.autoAction) {
      nextTick(() => {
        startAction();
      });
    }
  },
  { deep: true }
);

问题：定时轮询执行setOption  页面长时间放置  内存占用会越来越高   echarts版本5.6.0  怀疑setOption有内存泄露问题

**Comment by limingqian** [comment]
> 找到原因了，并不是vue框架，或它的watch deep或者ref之类的问题导致的。 而是当series的symbol项未设置或者设置为非none（因为默认值是circle）时，此时再多次调用setoption，占用的内存会随时间一直增长，且无法释放。

如果想使用 symbol 怎么办呢

**Comment by idealy233** [comment]
> > 找到原因了，并不是vue框架，或它的watch deep或者ref之类的问题导致的。 而是当series的symbol项未设置或者设置为非none（因为默认值是circle）时，此时再多次调用setoption，占用的内存会随时间一直增长，且无法释放。
> 
> 如果想使用 symbol 怎么办呢

bug新版已经修复了吧，我没再关注这个问题。
