### ISSUE TITLE
[Bug] Can't change the color between two nodes

### ISSUE THREAD

**Issue by songwillow** [apache/echarts#20159]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0kC-ANCXI58RVKTKUasBszadufQegBu-AK6MANgFlGIMSXQBbCNCIBGZaWOMMRAEzX0eABbAA7kQBm2vFWdYMwAlRmhWaXEJWHpgLU4iAG1aDlYAI0YACgcAVhz-WAsATgBmAocANgKABgA6HOqASloClPSs3PzC0vKqwtrqptoAXSNYXiUSABNmRn8wJLGoiSmIYypoPChNpNoMFpluVpVtdSoRwJdgdQ56aUSxiUTqmoKLYcvSRKtYF8KPx5fJy_VoAWgugPQiTKIJk4IB0S-ABZXrAHAjEbBEl0_ujPlC-n93oDRhIJugMf4OBAqIQsUtARRqHRXFRmLYQDwySRRrwANxAA

### Steps to Reproduce

Using the heatmap sample, change the visualmap colors to have one with 50% opacity and the other with 100% opacity. 

### Current Behavior

The color between the 50% opacity nodes doesn't blend together and has a border color of a full opacity.

![image](https://github.com/user-attachments/assets/64f8cea1-ff25-4b8a-b583-351d3f60b43a)

### Expected Behavior

It should honor the opacity and color the whole node the same color and not have the borders be the full opacity

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Framework: React
```

**Comment by helgasoft** [comment]
I do not see a border in your example... Does [this](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMrGAJ4gCmRA5AMYCGYFA5sAE6nWwC-ANGrFI58RVOnQBbCNCIAGAHQBWfuNgT6GIgEYlK8RvwAZegCMKAG1Gw8AC2AB3IgDN65vBR570eEOYhhDaSpiWwdnV3ceAXQAehiyShoGJlYOagE-AQA3fABXVwBZehBRaLVpbS81DSIAJirQx1gXNwoq6QAlemhmYLFVWFpgc3YiAG1qNmYTegAKWsVlWC0ATgBmXlhagDZNhUVZAEpqTcnpuYWl1Y2t3eX5WSPqAF0y7gy9ABNGencwcbK_VUnwgEgo0DwUAh42oGBOsGonFOWVcuQoLyq3mAuTYtGCYzKqjGsk2WlJz0x4jGZOW5Mp6DG9VpCIAtBjCVSbjTqGyKRyGQAWUmbWp8gZUq4isXi2BjO40rSvcVK8TvdDS9xsCAUQiypAkcjBag2CiMdQgLjcV7cADcQA) look better ?

**Comment by songwillow** [comment]
@helgasoft  there's this darker border between the two lighter nodes
![image](https://github.com/user-attachments/assets/4e2fe4e1-fb03-46e5-8c08-74ed20614a3b)

**Comment by songwillow** [comment]
@helgasoft to show the gradient of a single color but if that's not possible I guess I can use the full opacity of that shade
