### ISSUE TITLE
[Feature] Add an option to remove brush toolbox

### ISSUE THREAD

**Issue by zkycaesar** [apache/echarts#20163]
### What problem does this feature solve?

Currently, if I add brush to the chart, the toolbox will always show:
![image](https://github.com/user-attachments/assets/d7e80bb9-6c34-4641-a2f3-46ad9efc94c6)
Even if I set `brush.toolbox: []`, the toolbox still shows. I want to have an option to clear the brush toolbox.

### What does the proposed API look like?

I want to have an option to clear the brush toolbox.

**Comment by plainheart** [comment]
Setting [`toolbox.show`](https://echarts.apache.org/option.html#toolbox.show) as `false` to hide the toolbox.

**Comment by zkycaesar** [comment]
> Setting [`toolbox.show`](https://echarts.apache.org/option.html#toolbox.show) as `false` to hide the toolbox.

@plainheart But that would hide all the toolbox, I just want to hide brush and keep others.

**Comment by plainheart** [comment]
```js
toolbox: {
    feature: {
        brush: {
            show: false
        }
    }
},
```

**Comment by zkycaesar** [comment]
> ```js
> toolbox: {
>     feature: {
>         brush: {
>             show: false
>         }
>     }
> },
> ```

Ok. Didn't see that in the doc.
