### ISSUE TITLE
[Feature] echarts支持多个tooltip吗？

### ISSUE THREAD

**Issue by shenxiang216** [apache/echarts#20168]
### What problem does this feature solve?

1. hover条形图的柱子可以展示一种tooltip
2. hover横轴文本展示另一种tooltip（横轴文本可能超长被裁剪，期望hover显示全部的文本）

### What does the proposed API look like?

1

**Comment by plainheart** [comment]
目前不能同时显示多个 tooltip。

**Comment by plainheart** [comment]
Duplicate of #11382

**Comment by shenxiang216** [comment]
对于横轴文本超长，hover展示完整文字浮窗，要怎么实现呢？
![image](https://github.com/user-attachments/assets/459964a5-69ee-4af1-a1c0-78d4eaef26f0)

**Comment by shenxiang216** [comment]
@plainheart 劳烦大佬解答

**Comment by shenxiang216** [comment]
> 目前不能同时显示多个 tooltip。

不是说同时展示两个，是hover不同的位置，展示不同的tooltip

**Comment by plainheart** [comment]
@shenxiang216 轴标签显示 tooltip 目前也不支持，这是 #16315 要做的事。不过有变通方法可以自行实现，参见 https://codepen.io/plainheart/pen/jOGBrmJ

**Comment by shenxiang216** [comment]
收到，大佬，你是echarts开发者吗
