### ISSUE TITLE
[Bug] 当设置grid.right: 0时，axis label会超出右边界

### ISSUE THREAD

**Issue by zkycaesar** [apache/echarts#20162]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurDhgBZiEAMANMegMYxgCGE0AMqwEYCmAG0JgsAVz710AX0mxiADwCC8iAGdCqErDABPEH0IByAG6sB4w7JnEdytRoba9B2CbMXi19Kr44-62ABtR00tWFxWNkJAgEYAVjpYACYAZkSkpIAWWmSYgA4cmJS4wsyAdhykgDZqWrqAXVktXX0jAQ4-Q0cpYnqUKQBuIA

### Steps to Reproduce

使用如下配置即可复现：
```
option = {
  grid: {
    right: 0,
    containLabel: true,
  },
  
  xAxis: {
    type: 'value',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 26000000],
      type: 'line'
    }
  ]
};
```

### Current Behavior

当设置grid.right: 0, 且最后一个x坐标比较大时，最右边的坐标lebel会超出界面，即使设置了grid.containLabel: true也没有生效。
![1721093466903](https://github.com/user-attachments/assets/bfb9afa7-fdc2-4d98-b45c-d3efad0943dc)

### Expected Behavior

当设置grid.right: 0时，最右边的坐标lebel不会超出界面。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
如果用的是 v5.5.0 及以上版本，可以设置 [`axisLabel.alignMaxLabel`](https://echarts.apache.org/option.html#xAxis.axisLabel.alignMaxLabel) 为 `'right'` 使之右对齐。[Demo](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurDhgBZiEAMANMegMYxgCGE0AMqwEYCmAG0JgsAVz7EAvvXQAPAIKyIAZ0KoSsMAE8QfQgHIAbqwHj9MkqyXLu_IUQ3oTEDNACyV24INlK-hrCSUhZaiipqAdq6BsamfP7o0sTKfDh8qrAA2gHqjrisbISZAIwArHSwAEwAzBWVlQAstFXFABzNxdWlHQ0A7M2VAGzUI6MAuhYaUXqw-gIc8QFB6GMokgDcQA)

**Comment by zkycaesar** [comment]
> 如果用的是 v5.5.0 及以上版本，可以设置 [`axisLabel.alignMaxLabel`](https://echarts.apache.org/option.html#xAxis.axisLabel.alignMaxLabel) 为 `'right'` 使之右对齐。[Demo](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurDhgBZiEAMANMegMYxgCGE0AMqwEYCmAG0JgsAVz7EAvvXQAPAIKyIAZ0KoSsMAE8QfQgHIAbqwHj9MkqyXLu_IUQ3oTEDNACyV24INlK-hrCSUhZaiipqAdq6BsamfP7o0sTKfDh8qrAA2gHqjrisbISZAIwArHSwAEwAzBWVlQAstFXFABzNxdWlHQ0A7M2VAGzUI6MAuhYaUXqw-gIc8QFB6GMokgDcQA)

嗯，这倒是个办法。
