### ISSUE TITLE
[Bug] Dynamic Data Issue

### ISSUE THREAD

**Issue by ChinaID** [apache/echarts#20164]
### Version

5.5.1

### Link to Minimal Reproduction

Sorry, but there is no available link on public internet.
I just wrote a similar script, but it's not the same one because the situation will happen when the data is loaded by Ajax dynamically.

https://echarts.apache.org/examples/en/editor.html?code=G4QwTgBAJiAuIQLwQNoEYCsAGANBATAMy4H4Ase-aAHHmoRnWQOyUBsWAugNwBQvAewAOsAJYCAdkggBvXhAgAPAIKLRAZwBcs-QoiwAnkICm2gOQBjOMYDmAsAbM5dCmPG0ozAWUlOIZgBUAV2M_MwB1YygwgIALILCAMTBRMIBlOHSgiTNOXQBfZwUDVQ1tOT19I1N_UAAbELMCooh1YxTjLVQXHUrXOBBtNxAWysMTcwAjcCbK_N08_O4gA

### Steps to Reproduce

The data is displayed correctly on the chart if it is fixed:
![3](https://github.com/user-attachments/assets/b4417972-60ae-4894-bba3-58db22519c1e)

But the data is displayed incorrectly on the chart if it is loaded dynamically:
a), sure the data is same as the fixed one.
![1](https://github.com/user-attachments/assets/42a6f3f7-201e-4327-88e5-372e60b38420)

b), but it looks like it did not start from 1 but 2.
![2](https://github.com/user-attachments/assets/4eec04f9-2d2c-4383-9ad1-86015d2102a7)

### Current Behavior

The data is displayed incorrectly on the chart if it is loaded dynamically:
a), sure the data is same as the fixed one.
![1](https://github.com/user-attachments/assets/42a6f3f7-201e-4327-88e5-372e60b38420)

b), but it looks like it did not start from the position 1 but 2.
![2](https://github.com/user-attachments/assets/4eec04f9-2d2c-4383-9ad1-86015d2102a7)

### Expected Behavior

Correct display data on the chart whatever it is fixed or loaded dynamically:
![3](https://github.com/user-attachments/assets/b4417972-60ae-4894-bba3-58db22519c1e)

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome
- Framework:
```

**Comment by plainheart** [comment]
直接把 response 赋给 data 就行，为什么要用 JSON.stringify 序列化为 JSON 字符串呢？data 入参应是一个数组。

**Comment by ChinaID** [comment]
验证有效,非常感谢!
