### ISSUE TITLE
[Question] Custom series type - Render svg pattern into a rect 

### ISSUE THREAD

**Issue by songwillow** [apache/echarts#20179]
### What problem does this feature solve?

I'm using the custom series chart to display a modified bar chart. Based on the profile example.

I've been trying to render an svg on the rect object but rect doesn't seem to support this functionality

<img width="856" alt="image" src="https://github.com/user-attachments/assets/0a59b450-8b92-4d66-a2e9-2e92e85554c5">

### What does the proposed API look like?

This is what I'm trying to achieve
![sample](https://github.com/user-attachments/assets/616afe18-e92c-4cf0-8f2d-9b54c76fe453)

**Comment by helgasoft** [comment]
try [horizontal stacked bars](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack) with [decal](https://echarts.apache.org/en/option.html#series-bar.data.itemStyle.decal), or custom line segments #18634 (but probably without decal).

**Comment by songwillow** [comment]
Thanks a lot, this works perfectly
