### ISSUE TITLE
[Question] x and y values ​​in data

### ISSUE THREAD

**Issue by akbasferhat** [apache/echarts#20177]
### What problem does this feature solve?

Hello,
How can I use eCharts this way? I couldn't find an example in the documentation.

{"x": "2024-07-18T00:00:00.000000Z","y": 137.5}

![image](https://github.com/user-attachments/assets/5bf2a19e-84b4-4799-8781-860973d11e8c)

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeBYAULWZjADaRAC5l1NMwAnCAc2oFMLiByAQwA8IBnJgGlLPZcACsAjQwDYqgxlyATxB1mAYwrBO3PjNmr1nAMpg5uJSW2zYyvMEawmAYgCcz3v1kBfLR6-xP_E_TQACZSbrBBLGAsxADaALo-fjJsAIIcnLFh0haw0CwAtqZMERKu5vKKzJCFZd78CfxyaVyZ5tkWRpV2AG4suACudLUWeYXMABJ0kcOygpwAMiwARnS4oeVkAGY2-ZEStkxIvQN07rD5uDNkSXVtYRVFx4NXmKNFAMJ4QS-wc4srazMOUw2wouzA-2YRz6g3cPxu1x8DRknAYEDoGVgMSy9zIACI3njiHjJpE8T4cnjOnQibA8UsWBRybjMHiSixadiNjl2sDgXi2LS8QAmAAMwoALABaUUAdilAEYABwAFVFosI6s1ooAdOr9aKAFrM7l8ulyWkKgDMsp1AFYWRYEWagS6LAKhWLJTL5cq1Qrtdq9QajSa3e6LcQFRKFY7buHeeG6YLiV7pXLFarxYH1cGDcaKUm8ZHYNbbcKHab427E-GPanxenfVmrTndSHQ4W6yWy3HEX3MLW3fW6WmfZm1RK23n9QWBxHLTadbLK-HnWahy6RyLG-O_aK7dOO3Oq_ye1bdSv5-u-Zuzduxxn9wA2I8hk9J_E9iXC69d4F3nyD67k-Waym--Zhp-5qLkqOoVn-86AfyKajiBzZqkqEGzlBn7FpaMaIaeg7zrIwHeqBaqONh6oftB-FRoRxG-P-PKkfiqE7hRGEKhqWq5seuFFiWYp2vaREJuxrKcY-PEBvx7bvkJ3a0sKakSTWUnJp66ETgqwo0Z2WkMbk_S4LgGkushlIybpfrWoZdF4SW0BmRZzE3gBxm2dxelTgpM60cpw4uW5lkbt5Om-fZh4BYJrH3qF5nhbekUNtFqoKq-cVKQlQFJe5a55WQ1nuj5TZ6eBOWQcVlIFSlXnMWR5V7plWHVThtULsQrnJR5XWlc1UUVfZ1EdUFXVkfV_VIWlaEZSqYqOcFW7TUVs1NRxw2tYt8l8YpNXGWtbqeWxm3SdtlFqctk1frSvWFSdA1zVxI2qsKrbjUZ50wT1YUeY6cRhOud4EgUNLEp8uBBCtdLUkKuBiDSCVspEHKtJJP3kW9ar7UG8VHapjgSmJsrPg1Z3Qdp6U46Ke347lhPEMKsoCbGM3MYNW00zt2ZfU5wmqZKtrOBTFhcxdPOUaKn37YF31UyZH3Play6ymLsgS9T820_5csE1jIlWs-ooayVL2yROB43UzsDK6rspKmbJFYy10vZfrjOG5adps87rp4W7GFyjb3tRs4jg6o4Tsc5jitB1b7We4dYd244fux5pruXcHY3J51tvCsTtqO_7WvYztvGh4rInp-27PrZzFt2Zl9MCV7NdE-qZfNwt-nV_RIkk2JCrq5nVm9zjDn87D-WqUqGeN3H9EJ_ZesMynnfM8XUeOD32dSzxsX5xNhfE5Hz4x0vWfxznekexvBep0Xvv77fh-VQPzm0he3fjxFB8daVyTo_U-z9HCv3_qlQBr1K551AQrQeP99RvxXnfP0S0Z63VZCWX-psoGNXfkAq6bcDpPy3rAPBqDA7oPegZLBZ9fZ6gbk9DaRDYFXVlgggWKlt5_zXIDYG9QtDuAANxAA)

### What does the proposed API look like?

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeBYAULWZjADaRAC5l1NMwAnCAc2oFMLiByAQwA8IBnJgGlLPZcACsAjQwDYqgxlyATxB1mAYwrBO3PjNmr1nAMpg5uJSW2zYyvMEawmAYgCcz3v1kBfLR6-xP_E_TQACZSbrBBLGAsxADaALo-fjJsAIIcnLFh0haw0CwAtqZMERKu5vKKzJCFZd78CfxyaVyZ5tkWRpV2AG4suACudLUWeYXMABJ0kcOygpwAMiwARnS4oeVkAGY2-ZEStkxIvQN07rD5uDNkSXVtYRVFx4NXmKNFAMJ4QS-wc4srazMOUw2wouzA-2YRz6g3cPxu1x8DRknAYEDoGVgMSy9zIACI3njiHjJpE8T4cnjOnQibA8UsWBRybjMHiSixadiNjl2sDgXi2LS8QAmAAMwoALABaUUAdilAEYABwAFVFosI6s1ooAdOr9aKAFrM7l8ulyWkKgDMsp1AFYWRYEWagS6LAKhWLJTL5cq1Qrtdq9QajSa3e6LcQFRKFY7buHeeG6YLiV7pXLFarxYH1cGDcaKUm8ZHYNbbcKHab427E-GPanxenfVmrTndSHQ4W6yWy3HEX3MLW3fW6WmfZm1RK23n9QWBxHLTadbLK-HnWahy6RyLG-O_aK7dOO3Oq_ye1bdSv5-u-Zuzduxxn9wA2I8hk9J_E9iXC69d4F3nyD67k-Waym--Zhp-5qLkqOoVn-86AfyKajiBzZqkqEGzlBn7FpaMaIaeg7zrIwHeqBaqONh6oftB-FRoRxG-P-PKkfiqE7hRGEKhqWq5seuFFiWYp2vaREJuxrKcY-PEBvx7bvkJ3a0sKakSTWUnJp66ETgqwo0Z2WkMbk_S4LgGkushlIybpfrWoZdF4SW0BmRZzE3gBxm2dxelTgpM60cpw4uW5lkbt5Om-fZh4BYJrH3qF5nhbekUNtFqoKq-cVKQlQFJe5a55WQ1nuj5TZ6eBOWQcVlIFSlXnMWR5V7plWHVThtULsQrnJR5XWlc1UUVfZ1EdUFXVkfV_VIWlaEZSqYqOcFW7TUVs1NRxw2tYt8l8YpNXGWtbqeWxm3SdtlFqctk1frSvWFSdA1zVxI2qsKrbjUZ50wT1YUeY6cRhOud4EgUNLEp8uBBCtdLUkKuBiDSCVspEHKtJJP3kW9ar7UG8VHapjgSmJsrPg1Z3Qdp6U46Ke347lhPEMKsoCbGM3MYNW00zt2ZfU5wmqZKtrOBTFhcxdPOUaKn37YF31UyZH3Play6ymLsgS9T820_5csE1jIlWs-ooayVL2yROB43UzsDK6rspKmbJFYy10vZfrjOG5adps87rp4W7GFyjb3tRs4jg6o4Tsc5jitB1b7We4dYd244fux5pruXcHY3J51tvCsTtqO_7WvYztvGh4rInp-27PrZzFt2Zl9MCV7NdE-qZfNwt-nV_RIkk2JCrq5nVm9zjDn87D-WqUqGeN3H9EJ_ZesMynnfM8XUeOD32dSzxsX5xNhfE5Hz4x0vWfxznekexvBep0Xvv77fh-VQPzm0he3fjxFB8daVyTo_U-z9HCv3_qlQBr1K551AQrQeP99RvxXnfP0S0Z63VZCWX-psoGNXfkAq6bcDpPy3rAPBqDA7oPegZLBZ9fZ6gbk9DaRDYFXVlgggWKlt5_zXIDYG9QtDuAANxAA)

**Comment by plainheart** [comment]
Two ways:

1. Use [dataset](https://echarts.apache.org/option.html#dataset). ([Demo](https://echarts.apache.org/examples/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGAY1LA2HbpPRKVbAMozs8ohpIKcwOrHoBiAJx36PEgF9HL9E_WwDNaABNxjr6MYIyEANoAusQexMwAgqxs4Y4SGtCMALaG9EGiXI7oMnIMkFkOkm6wEZ7SCezJkqmSRdkAbozYAK7U-cbpWQwAEtTBvRp8bAAyjABG1NgBxugAZuYZwaIW9EjtXdROsBnY5RqV7p7oTVKybR3dY5L92QDCOL4PJBPTcwtGS6ukdZgTYMHZ3fYnCquYjVYi5RhsahgBokK7oNjATqkBSGMIFVH4yTMBgAJgADCSACwAWjJAHZqQBGAAcABUyWT8ByuWSAHQcgVkgBaH2M0kIjIAzHTeQBWQmwGJLP7K4mWclU2kMlnsxk8nn8wXC0UacWwRmUxkKpVLNEaNX0DU0-lMtkU_Ucw2CkUXJZmqUykny5U24x2omkinO7VuyUevlG42-sUS6XW5ME5XoB1OrWu9mU-NegU-hXof3S3l04NLUMacMkHNRvM6smyouJ0tZ2AVvnV9MKhvZyOal2tgBsHaNXaz_spJIHyqHsCbo5j7LpU-9JskFeZvKDi9tZZXI-j-bJzK3JZ3JDnVpDGcuJ9X59bNmvHJnyvvR7DL7PFs2UZTluU9Ttb3LQhyVlOU_3rAD1WbMdgL1MCE2nSCe2gkkF0fQdEMdZD10ZElPyTE8zWgTpsGweDGkI3MUNZKVyO_P1CGo2j6MzLNXyAljC3Q4svywqiaLo_Cl0Y4j80ZdthIgp8704iSeOfbt-OYxlJ0UzDlKg2AuMk2tlOXLSSM3PTtwM7CjLUqTj00wDtKvayb1s8TuMc_9nKQtc5I_dzRM81TvNMgi_KIgKdXJNixLCkzjDrBioqY9cSTQ0CMJsyjEvUlUlgs_NcPi0L7PC5KzJkmK2RJONgoo7svKS058SiKF0FhdFaAgagklgPFUrSTJsmGUYMxaBgZkYUgTQAenm2BEWoWAAAtgRAJJFuoBQ1tmsA2F5RgQEYPbqF5cwKHm0BIBgXkNqOKxEXIfrqWwYQLuoaBTF8ah8UWjA1tW1ZaOAAB3YQKFgAADb7fuoGHYFMaBlkoLFgigOAFEYOA5lgYAMggYFqF8WAESB1aQGUORSGkdaKbAYHltGozRvxeHgD-xYioYZhbzNehpEhZxfUqKInAAbiAA))

Just put your object array to the `dataset` option.

```js
dataset: [
  {
    source: YOUR_OBJ_ARRAY
  }
]
```

3. Transform your object array to a 2D array. ([Demo](https://echarts.apache.org/examples/editor.html?c=line-stack&code=PYBwLglsB2AEC8sDeBYAULWZjADaRAC5l1NMwAnCAc2oFMLiByAQwA8IBnJgGlLPZcACsAjQwDYqgxlyATxB1mAYwrBO3PjNmr1nAMpg5uJSW2zYyvMEawmAYgCcz3v1kBfLR6-xP_E_TQACZSbrBBLGAsxADaALo-fjJsAIIcnLFh0haw0CwAtqZMERKu5vKKzJCFZd78CfxyaVyZ5tkWRpV2AG4suACudLUWeYXMABJ0kcOygpwAMiwARnS4oeVkAGY2-ZEStkxIvQN07rD5uDNkSXVtYRVFx4NXmKNFAMJ4QS-wc4srazMOUw2wouzA-2YRz6g3cPxu1x8DRknAYEDoGVgMSy91gACI3njiHjJpE8T5ZHjOnQifiliwKOTcXiSixadiNrJ2sCLHi2LS8QAmAAMgoALABaYUAdglAEYABwAFWFwsIqvVwoAdKrdcKAFpMznAvFyWlygDM0q1AFZcbceZhuY7MHyBSLxVLZYqVXLNZqdXqDUaXZSzcQ5WK5fbETGnXHefziR7JTL5crRf7VYG9YaKaHTearVrBXbjZgETznS63cnRanvRmLVntUHg_ma-HYJbpQnK8Dq47a_iU170yqxS2c7q8wmw0XrdKyy7-zlBzzh0L62OfcKbVO27Py7yu5btUu-x2LOuTUmR9u07uAGwHoNH0NkQsRsWCy8Jm85Juo6Phm0qvrmIYfvip4WgqJbLo6q7XnOn53lunogSqCrgTOkEfl-3ZRn-x4AYm7oPo2KqODhqrvlBBGRtGx5IVyKGumhwGUXKaoatmh54QWXYijatrES6pGUhxFHjnKfq8a2b4CZ2tKCqpYmOhJqHkRhXGCjR7ZsdBtLQP0uC4OpVaGUB0k-pa-l0fhXYmWZFkDlZUk6TJk7ydOtFKUOTmmeZzFXqxx6SdpDYyfuPn8aFJqBS5IX_u5kU7sqcovrFinxYBiXBSuuVAvRHlRbZYHZRBRXzsQzkFYhRWaexaWYYq9n-Ru-WuWuqV1p5tnUZVuHVZ-XXJSRvX3v1yoiu1I2umNhUpeFWl9WVM1yTxClVVZi0NctUH4qV6VKqpc27cZQXdchK3NWtJ2Cs2Q1-fNRm1VdzG4nEWq7CAAAUwBLAAVggAB8WKA0DWpsDwsCQ1qchxAAlGE7j1Fo7gANxAA))

```js
[
  ['2024-07-18T01:00:00.000000Z', 141],
  ['2024-07-18T02:00:00.000000Z', 137.25],
  // ...
]
```

```js
data: yourObjectArray.map(obj => [obj.x, obj.y])
```
