### ISSUE TITLE
[Bug] toolbox.feature.yAxisIndex is not working when series.type is line

### ISSUE THREAD

**Issue by suedar** [apache/echarts#20208]
### Version

5.5.1

### Link to Minimal Reproduction

[echarts example](https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Fbar-dataZoom-filterMode&edit=1&reset=1&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbASgPLcAqAfQAKAQT4AJNgGo2AcgD0uKHCjyoSJM0XLVqAEZRgUAXoCuuJnAEAHGKmuokUADYCATAAYAjG4TP8SIgAVkiohLIANOxsAGamhADGcPhhbKT6hsZmFszu3m7kbADe0RygkLCIEPi4jNh4RGRUpWz2yakAvMUtHHCoqM7J1gBc3Rzj43Aw-MRMMKOy-HCMwLI9bAC-URMczoxMhLijJTvjSiqjANqyAOJ26HAQkXIAQuaWbJ5eXs-ybzlwT75WQAXW2pzYSxWNygIzYAFZ1lt1n0BnpUAAPY7rDgxRjKUwwRjYiFnHQALX6wBJpPGKAwoympkY4NJyNpbAxIgxAQAkodGFi2B4Imx5PJAODGgCztQBXKoBsuQAGoAXeMA98qAU7lANURgHLjQBsSjjxiBuXyBUKYi5NPqNkjWeNiNMjmMIX04bIfABSSL6vYxOALLwem0TabECC-uReDwB_UJMIqIiYKB6RjORkwZnW9ZcnlIGmnABE5ygeau-o4XgA7G43F4ABxuAAsHibTcDOwrVdrbnLzZbpbY7erNYAzD3exyB7WhyOe62JhPhwA2Uez8bzocATmXffn9c8M-3lcH9fhW_Hh9r9Zrp9p8_hEf3Z47NfhjYfN_Pz-7b9J86X15_H4LtOzYrmWgF_iBB5Pgum7fhC86Vv-8EfuWJ5wacCFXuhbYfjW96QY-g41q-BHvk-NZfqRAFPrB2Fzh-67AWOZGDuuEHMdRrG0RxyEdpue5Ubx1abmhgkYeem5YWJOF8d8SHibJJE8QpwkVvJMnCQJ0n0XxbhMSKUGaexBmEV465uNxJksWZQ5aVZnE2aJykaTZUnOTpwn1vh7mrhJ9ZKfZQlmfWlE-WBfFOWF_YSfC-mgdFEXGfFE7rvClnJRJC52RlfELpFOXCQubmBSpZnlt5JUueu5YBQVZWhZVHlmcVjW-Xxw7qU1641klhnNelfXruZnVtcJqUjeFY3FQVe4VTNTa1YZe4NfNFWtZNXxxUt3i9YRXwDXtHhVhNCXHW4-XbW403bUOc03Yth1Dit20Betp2ePWW2HfWu0sR9B1_R48LZdt8IXYd8LXYdC53dDD2Awuz2HQ1b0Dp45ZfYD5a_Zx6MA7jHh1idaOE-DgM1lDgPrrDVPwwT1XE4e1ajlFaMRpjuMRjjQnM_jPPfCDe3fGTnO1ozVbVszdGjZLdP8124sdvpqNM14U6K9WQ7cypmt8zrXi7hrBsi_zl5G3e5ty_r8JI39XjGSrEv2xz_MLtrGnVjBRuIdLG0Vib-vlpTnN4UbxFh7bnOWY7fEu_rbFG0NGueILf2eAHHueMHPPVjTuPVlbmdqb773Hcnenl-7HkS3rme2cnQ4Z9XenZzrDZ5zn_nJyFyeRTHVaxb3Vcy-dtfN1lyd5ZPreZ-Vyc1fPkc5y1M1XXHmc9cnNZjyPw0l2jFlN7vM_VyOHc6yOhenx4S8X2tM23evp_2xrt07xttmp7jtlHx_V2v7dABV8ZZTlvh7Icr0H6fVfj9GB793qNy_jzRuv8EGQ1fjDDBwCP6I1fijB-GM8HDw_uWeBaMhxE33kzChqDyEU1ftTBh2CEEMyoRLV6_dGxPxlo2Yh71GxkKZl5JBOsvK0KEWLNhVZdznw9ruZhaNdxgOrtAjWn1uEbU-nwxRG41GGykQ2Y8eiT48ItgY48CihE2zUQ7GaP0NH8LdjYwR7CfbaR4ahNRQc1Gh3MeHPxyieHRzsYxNRCdzFJwMSeERHsTziIlieExG07yyOrneSxCTi7uOSXZfuwMHFo2BtopmwMXED3rlExuGtYpJPei-VJMsXwZIHj3KJfcZpgwKSU-ExSElpWqRPKJU8hm1MKXPKJC8JmBOSSvJakMukJM3lE7e1S97ZLqeNKJ3UNZLgaRtJczS3BLmme9TBOy1bnN6VWGGZSjll3WWjLK8Trn_wMUBPZpyIE7KejsyBS0FyqIeUzAFVyjn1luXlGJ1c8rPKOegt5ZygUSzdoct2JzHn4P-YQt52MdmkJ2ZQpF1znyjn1GCfUeYoDZj4PgBIABrYsjpSR5npOgRlZpnAWjZCuSl2ZMBEEYIyk4tI8z-EIIwAAynAEAewhV9g4HmGMzhUAwEZXmAAxAkeEWqtV5j7FablFKqUBATEmZwcqOSioFeIRgMxQyMq8PCeKiqBgqrVTAYgBhSAimFKKH1HgEALnIHqw1zL0TxCUDAEAMJrDsvNIwDMpxDTZlzDsPM0rrCCtGHmAAbi4ZkeYeVIASC4LNbAmQsiNXyxMyYhUGp2OyHYmhpiMBzGwS4-phXMsIIYMteYU71gALQ30HRZYUHhhhNknR4UdR0h0jrHXpYYaVl3rjYIWvs6aQCZrVWKwVzqkAgGAOic12bCBhH3ZuwsjKO0cg4G9e98VH3yt9S-h9r670frve-n9T6v0cl_W-v9gHP0ge_cBiDQGoOgcgzB6D4H4MAdgwhuDqGUPoaQ4h2kYHMNodwxh7DyH8PEcI1h0kOHSN4cowR8jRHqMkdo2RiEFHGNUdYzR5jdH2MMc40x04LHeNscExx_jXHhM8dE3xnYAnJNCdkyJ6TYn5MScU1JiYMnVNyc0wp9TSntMqd02p8YGnDNadMzp4zenzMGcs0Z59ZnbMOfsxZ5zNnXP0Y89xzz4nvPKd8_p_z1nAuOZc_-4L7mvORZ81FvzMWAtxaCwlkLbmwtJYi9FjLsXMvxey4liEbgrPJfC6l3L4xGx_pPBV99lWX01c_XVu9DWORNdpOVuzJWsudZy11vLPWitpY691obvXhv9dK-lvrE3RtTZG7Nsbk3BtzZm_N6bi2VtLbW8trbm2dsmfW_t7be3DuFeO-1o7u2TsXbO5d87t2bv3eu49pzV3nt3ae6Ft7r2Htffeylz7H3gN9hBJadYwOJgbBoBMco0B4DIGYNwaw7RCDpERykQgzQJgtGh5UBABAkDWGUAkCAIgkho9IF28Y4o2CAA28wAJdGAEgEwAtHKAC5lQA--qAEp_QAfKYom3cSOQKg6WMBuMqgwzgwCElCDAT0pxBcgAWIWSkqBgASuTIwJI0udgK6pCrvYSQSfJBzXzitLQNgY82NQKgQA)

### Steps to Reproduce

Please check the link for chart options

### Current Behavior

I was using [dataZoomSelect](https://echarts.apache.org/zh/option.html#dataZoom). When I scale the chart, I only want the y-axis to scale and the x-axis to remain unchanged. But the current situation is that the x-axis and y-axis have changed, which means toolbox.feature.yAxisIndex does not take effect. For example, when I select the following content
<img width="629" alt="截屏2024-07-29 17 15 05" src="https://github.com/user-attachments/assets/1086b574-a71e-4265-94ca-26eea61c9cfa">

it display like this 
<img width="821" alt="image" src="https://github.com/user-attachments/assets/32798fc6-b524-4ad3-9ae8-e924a7b7b0f6">

which is only scale the area I select instead of ignore the y-axis. 

### Expected Behavior

what I want is this effect
<img width="817" alt="image" src="https://github.com/user-attachments/assets/475cb400-b9b0-40fe-9c14-eec6d941b98d">

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
In your example you are defining `xAxisIndex` and `yAxisIndex` on the wrong level. [Here ](https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Fbar-dataZoom-filterMode&edit=1&reset=1&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbASgPLcAqAfQAKAQT4AJNgGo2AcgD0uKHCjyoSJM0XLVqAEZRgUAXoCuuJnAEAHGKmuokUADYCATAAYAjG4TP8SIgAVkiohLIANOxsAGamhADGcPhhbKT6hsZmFszu3m7kbADe0RygkLCIEPi4jNh4RGRUpWz2yakAvMUtHHCoqM7J1gBc3Rzj43Aw-MRMMKOy-HCMwLI9bAC-URMczoxMhLijJTvjSiqjANqyAOJ26HAQkXIAQuaWbJ5eXs-ybzlwT75WQAXW2pzYSxWNygIzYAFZ1lt1n0BnpUAAPY7rDgxRjKUwwRjYiFnHQALX6wBJpPGKAwoympkY4NpbAxIgxAQAkodGFi2B4Imx5PJAODGgCztQBXKoBsuQAGoAXeMA98qAU7lANURgHLjQBsSjidiBOTy-QKYi5NLqOMjSRskazxsRpkcxhC-nDZD4AKSRXV7GJwBZeT22ibTYgQP1yLweQO6hJhFRETBQPSMZyMmDMm3rDlcpA004AInOUHzV3NbC8AHY3G4vAAONwAFg8zebQZ2lerdbcFZbrbLHZrtYAzL2-2yB3WhyPe22JhPhwA2Uez8bzocATmX_arg4bnhn287tYb8K3453dYbtbPtPn8MjB_PR_hTcft4vtfhPbfpPnS5vv4fgu04tiuHB_v-oGHoOC6bj-ELzlWAEIR-FanvBpyIdeGHth-tYPlBT6DseyGYXh36Ee-R5wThc4fuuIFjlRg7rpBTGAdRNHsShnabvulEcTWm7oQJPFCR42GiWRvHfKRuEya-UnyUJlZyXRvH8Up6lCW4jFCtBXjrm4bH6URhluFxpnMYZQ6aVZgk2SJ3HSUJQ6Sc5ymGQ2BEedpXmKb5q4XuuDYUYF4HBU54XlpFelgTFvHwiZ8UTuu8KWSlwULnZmW8QuUW5UJC7ufZYmGRWPmlS55UBVVnnrhWYV1X564lc1QW8cOakdUJtbJQZrUZQNRndRFvFpaNCVCa1k0DvulWFfutWLc2TUrZV7VjdW3hxdBXz9URXxDYdHjbbRPWeG4BV7adJUrUOC03UOy1PWtN21ZtU2eA2u0nQ2B3Md9x2Ax48I5Td8LXSd8J3TdC6PSdC4vYjb0nU1n1zR4Fa_SDFYA4JngVsDBMSeDJ2frNO6eLWsMneuCMgyFlPVp4DXM52o7RXNkY4wTkb42JNYeMTgvfGTgPfFDEt1uzNZC-dW1y8jEvdrLXh6RjVPq7zotDgLLk1huat7sbUt81eav3pbyt81-asmZrLNeMB9v68pNawWrSEK19lZm6LFa0xL-FqyRPvc7WqMS5Zju8TrBuGW72nTbLl2p6D6dBwTNYM9nXg24LNZR9ndmxyz8fu9WScXdWIsG7p4vZ0O_v125qfee3Bf16FqdRWXV0V8nV3V4rV115X2Wp_lU9Z4XFWpxWXeV41qdtYtbhdeHVMbyPX0b-PQ8jVvLMWS3lczcf1YjrngsjkvycjsXt8bYtD2DxdD273ND0Hx_Z1aX_M-D8N6yynDfA2U574fyHE_CBH1X4_VAf9JBv9FbN0brfSGoCYagPhrgqBaCFywPdjAzmr9sagLxpQ1BX03IYIgRTS-ukaagPpqwghtC2ZMI-mXJs79FZNi_lTJsNC5reXoe7byQCLreVngbPc4DJGNllnuYhydEEqKnJooRLMfqiOESbbhJ4VEW24VbMxHCxF224Q7Ra_1-FfX-jo6s_19G6O9gAgRaEVGBxUSHbhYdPGOMjiomOdiGKhOcY2dcbjqyngkcnU80jFanjke7e8ijEn51lveNRF0wZkL2mDBxc0wZRLBrEgeCT8nNxyW3JhL5Mn5IbJYqmL48kpL7otSGJS2lJRyelHJk8GnTxGWkxJ88GmLxySvBpa8imbyCaUvqOTayVPStUlJE0GkXyWVTJcTTFZLlaSzJcHSvp4NlvDXppznZXMMlc_-XN9lXUeeMi6wFDkXOelc0hTCkaFMOkjG5VdkH_IbJU_KmyLlYP-Tg_5ly9mnIBQi85c0iGAsBkQkFxkqH_KJlc-shKoq6jBLqfMUAcx8HwAkAA1iWJ0pJ8z0nQAyk0zgzRWhXBSnMmAiCMAZScWk-Z_CEEYAAZTgCAPYgqywcHzLGZwqAYAMvzAAYgSPCTVmr8xlmtFy8llKAiJmTM4WVbIRX8vEIwGYYYGVeHhPFBVAxlWqpgMQAwpAhSCmFN6jwCAFzkF1Qapl6J4hKBgCAGE1g2WmkYJmU4-ocx5h2PmKV1gBWjHzAANxcMyfM3KkAJBcJmtgTIWSGt5UmFMgr9U7EtDsTQ0xGC5jYJcXUQqmWEEMKW_Ml0GwAFosYDosoKDwwxmwTo8CO06g7h2jt0sMdKS71xsALWWNNIAM2qtFQKp1SAQDAHRGarNhAwh7o3UWBl7a2QcE-ne-KD65U-uffel9t7323rfd-x9n62Q_tfb-gDH7gNfqA-BwDkGQMQeg1BsDcH_0wfg7BlDyG0OIYQ7SUDGHUM4fQ1hpDeGiMEcw6SbDJHcMUfw2RwjVHiM0dIxCcjDHKMseo0x2jbH6MccY6cZjPHWMCfY3xzjQnuMid4zsfjEnBMyeE1J0TcnxMKckxMaTKnZMafk2pxTWnlM6dU-MdTBnNMme00Z3TZn9MWcM0-0zNn7N2fM056zLm6Pua4x5sTXmlM-b035qzAWHPOb_UFtznmIveci756L_nYuBfi8F1zoXEvhai-lmLGW4tZYSxCNwlmkthZSzl8YTZf2nnK2-irz7qsftq7e-rbJGu0jK7Z4rmWOvZc67l7rhXUvta64NnrQ2-slbS718bI3JvDZm6NibA3ZvTbm1Nhby3FuraW5tjb23jNrb21t3bB2CtHba4dnbx3zunYu2dm7127tXYe45y7T3buPZC69l793PtveSx997QGywgl1HWiYQOJgbBoBMco0B4DIGYNwaw7RCDpERykQgzQJgtGh5UBABAkDWGUAkCAIgkho9IJ28Yoo2CAA28wAJdGAEgEwAtHKAC5lQA--qAEp_QAfKYoi3cSOQKhaWMBuEqgwzgwCElCDAL0pxBcgAWEWSkqBgDipTIwJI0udgK6pCrvYSQSfJGzXz8tLQNgY82NQKgQA)is the corrected example.

**Comment by suedar** [comment]
> In your example you are defining `xAxisIndex` and `yAxisIndex` on the wrong level. [Here ](https://echarts.apache.org/examples/zh/editor.html?c=doc-example%2Fbar-dataZoom-filterMode&edit=1&reset=1&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbASgPLcAqAfQAKAQT4AJNgGo2AcgD0uKHCjyoSJM0XLVqAEZRgUAXoCuuJnAEAHGKmuokUADYCATAAYAjG4TP8SIgAVkiohLIANOxsAGamhADGcPhhbKT6hsZmFszu3m7kbADe0RygkLCIEPi4jNh4RGRUpWz2yakAvMUtHHCoqM7J1gBc3Rzj43Aw-MRMMKOy-HCMwLI9bAC-URMczoxMhLijJTvjSiqjANqyAOJ26HAQkXIAQuaWbJ5eXs-ybzlwT75WQAXW2pzYSxWNygIzYAFZ1lt1n0BnpUAAPY7rDgxRjKUwwRjYiFnHQALX6wBJpPGKAwoympkY4NpbAxIgxAQAkodGFi2B4Imx5PJAODGgCztQBXKoBsuQAGoAXeMA98qAU7lANURgHLjQBsSjidiBOTy-QKYi5NLqOMjSRskazxsRpkcxhC-nDZD4AKSRXV7GJwBZeT22ibTYgQP1yLweQO6hJhFRETBQPSMZyMmDMm3rDlcpA004AInOUHzV3NbC8AHY3G4vAAONwAFg8zebQZ2lerdbcFZbrbLHZrtYAzL2-2yB3WhyPe22JhPhwA2Uez8bzocATmX_arg4bnhn287tYb8K3453dYbtbPtPn8MjB_PR_hTcft4vtfhPbfpPnS5vv4fgu04tiuHB_v-oGHoOC6bj-ELzlWAEIR-FanvBpyIdeGHth-tYPlBT6DseyGYXh36Ee-R5wThc4fuuIFjlRg7rpBTGAdRNHsShnabvulEcTWm7oQJPFCR42GiWRvHfKRuEya-UnyUJlZyXRvH8Up6lCW4jFCtBXjrm4bH6URhluFxpnMYZQ6aVZgk2SJ3HSUJQ6Sc5ymGQ2BEedpXmKb5q4XuuDYUYF4HBU54XlpFelgTFvHwiZ8UTuu8KWSlwULnZmW8QuUW5UJC7ufZYmGRWPmlS55UBVVnnrhWYV1X564lc1QW8cOakdUJtbJQZrUZQNRndRFvFpaNCVCa1k0DvulWFfutWLc2TUrZV7VjdW3hxdBXz9URXxDYdHjbbRPWeG4BV7adJUrUOC03UOy1PWtN21ZtU2eA2u0nQ2B3Md9x2Ax48I5Td8LXSd8J3TdC6PSdC4vYjb0nU1n1zR4Fa_SDFYA4JngVsDBMSeDJ2frNO6eLWsMneuCMgyFlPVp4DXM52o7RXNkY4wTkb42JNYeMTgvfGTgPfFDEt1uzNZC-dW1y8jEvdrLXh6RjVPq7zotDgLLk1huat7sbUt81eav3pbyt81-asmZrLNeMB9v68pNawWrSEK19lZm6LFa0xL-FqyRPvc7WqMS5Zju8TrBuGW72nTbLl2p6D6dBwTNYM9nXg24LNZR9ndmxyz8fu9WScXdWIsG7p4vZ0O_v125qfee3Bf16FqdRWXV0V8nV3V4rV115X2Wp_lU9Z4XFWpxWXeV41qdtYtbhdeHVMbyPX0b-PQ8jVvLMWS3lczcf1YjrngsjkvycjsXt8bYtD2DxdD273ND0Hx_Z1aX_M-D8N6yynDfA2U574fyHE_CBH1X4_VAf9JBv9FbN0brfSGoCYagPhrgqBaCFywPdjAzmr9sagLxpQ1BX03IYIgRTS-ukaagPpqwghtC2ZMI-mXJs79FZNi_lTJsNC5reXoe7byQCLreVngbPc4DJGNllnuYhydEEqKnJooRLMfqiOESbbhJ4VEW24VbMxHCxF224Q7Ra_1-FfX-jo6s_19G6O9gAgRaEVGBxUSHbhYdPGOMjiomOdiGKhOcY2dcbjqyngkcnU80jFanjke7e8ijEn51lveNRF0wZkL2mDBxc0wZRLBrEgeCT8nNxyW3JhL5Mn5IbJYqmL48kpL7otSGJS2lJRyelHJk8GnTxGWkxJ88GmLxySvBpa8imbyCaUvqOTayVPStUlJE0GkXyWVTJcTTFZLlaSzJcHSvp4NlvDXppznZXMMlc_-XN9lXUeeMi6wFDkXOelc0hTCkaFMOkjG5VdkH_IbJU_KmyLlYP-Tg_5ly9mnIBQi85c0iGAsBkQkFxkqH_KJlc-shKoq6jBLqfMUAcx8HwAkAA1iWJ0pJ8z0nQAyk0zgzRWhXBSnMmAiCMAZScWk-Z_CEEYAAZTgCAPYgqywcHzLGZwqAYAMvzAAYgSPCTVmr8xlmtFy8llKAiJmTM4WVbIRX8vEIwGYYYGVeHhPFBVAxlWqpgMQAwpAhSCmFN6jwCAFzkF1Qapl6J4hKBgCAGE1g2WmkYJmU4-ocx5h2PmKV1gBWjHzAANxcMyfM3KkAJBcJmtgTIWSGt5UmFMgr9U7EtDsTQ0xGC5jYJcXUQqmWEEMKW_Ml0GwAFosYDosoKDwwxmwTo8CO06g7h2jt0sMdKS71xsALWWNNIAM2qtFQKp1SAQDAHRGarNhAwh7o3UWBl7a2QcE-ne-KD65U-uffel9t7323rfd-x9n62Q_tfb-gDH7gNfqA-BwDkGQMQeg1BsDcH_0wfg7BlDyG0OIYQ7SUDGHUM4fQ1hpDeGiMEcw6SbDJHcMUfw2RwjVHiM0dIxCcjDHKMseo0x2jbH6MccY6cZjPHWMCfY3xzjQnuMid4zsfjEnBMyeE1J0TcnxMKckxMaTKnZMafk2pxTWnlM6dU-MdTBnNMme00Z3TZn9MWcM0-0zNn7N2fM056zLm6Pua4x5sTXmlM-b035qzAWHPOb_UFtznmIveci756L_nYuBfi8F1zoXEvhai-lmLGW4tZYSxCNwlmkthZSzl8YTZf2nnK2-irz7qsftq7e-rbJGu0jK7Z4rmWOvZc67l7rhXUvta64NnrQ2-slbS718bI3JvDZm6NibA3ZvTbm1Nhby3FuraW5tjb23jNrb21t3bB2CtHba4dnbx3zunYu2dm7127tXYe45y7T3buPZC69l793PtveSx997QGywgl1HWiYQOJgbBoBMco0B4DIGYNwaw7RCDpERykQgzQJgtGh5UBABAkDWGUAkCAIgkho9IJ28Yoo2CAA28wAJdGAEgEwAtHKAC5lQA--qAEp_QAfKYoi3cSOQKhaWMBuEqgwzgwCElCDAL0pxBcgAWEWSkqBgDipTIwJI0udgK6pCrvYSQSfJGzXz8tLQNgY82NQKgQA)is the corrected example.

@MatthiasMert you are right. Thanks for your help
