### ISSUE TITLE
[Bug] When customizing the gradient color palette (option. color), the label setting color: "inherit" does not take effect

### ISSUE THREAD

**Issue by Child-qjj** [apache/echarts#20217]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/wizardly-parm-zkjm8j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzb1016f00073b6l2m16uf30%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzb1016e00033b6l4ffgrr6d%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzb1016e00043b6lby998cix%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzb1016e00063b6lz2x5k8sf%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzb1016e00033b6l4ffgrr6d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzb1016e00023b6l2n7xdwe0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clzb1016e00033b6l4ffgrr6d%2522%252C%2522activeTabId%2522%253A%2522clzb1016e00023b6l2n7xdwe0%2522%257D%252C%2522clzb1016e00063b6lz2x5k8sf%2522%253A%257B%2522id%2522%253A%2522clzb1016e00063b6lz2x5k8sf%2522%252C%2522activeTabId%2522%253A%2522clzb106vr00183b6l35c9af3r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzb1016e00053b6lya2j3tlm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzb106vr00183b6l35c9af3r%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzb1016e00043b6lby998cix%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzb1016e00043b6lby998cix%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

设置option.color 并且在饼图中formatter自定义文本格式
color:'inherit'

### Current Behavior

the color of data and label is different

### Expected Behavior

the same color of data and label

### Environment

```markdown
- OS:macOS Monterey
- Browser:Chrome 126.0.6478.183
- Framework:Vue@2
```

**Comment by helgasoft** [comment]
Pie label **text** to have (inherit) gradient color ? I don't think this is possible and even if it is, users probably won't like it.

**Comment by Child-qjj** [comment]
You're right, but I actually only want to get one of the values, or be able to functionally set the color. and now I can't do like this `{
color: function(params){
 return params.color.stopColors[1].color // or other ways to get the same color
}
}`

**Comment by helgasoft** [comment]
you can set the label text color to match the gradient - [Demo](https://echarts.apache.org/examples/en/editor.html?code=MYewNiBODOC8AEBtAsAKHh-BvNnMBcBPABwFMAueAIjAEsA7UgQ0ioBpc94APSgBg7ouhfoK48ATKM55CU-AEYxXUBEgBlfCGLRKKIeJwHx8EADMz0UvmnHxqqJSqQA5gCMmACgkBWH2wBOABY2BQkANlCASioZLgBfZUM48XNLa0olFJVwR2pXD28_QJCwyL4AOiCY7Ix47IBdJMwXCA8wSjMmMCs4xLijcSIyJzpGFnZs3ngBbJEZ5oxueVm7eDlMxfgHDS0dPVrsQ4w0qxsF4-3cyCcCrwUAZkjwiTZffwUatbqtjEGTE4WM6bS47W7ue5PNgvN7FSrVWLfeD1NZNbKtEDtTrdXrGfrGf54YYUahjZisLbTVbiebUrjLWw0-RZNY7TTaXRIQ6EkynDIXJEYMH5CFFfwBSISCQPaKIgH4gE81JA_ksgFC67gwrvQKS6VseFfeWNLYYrHwLo9Uh9ZpK-DE0YMcmTNZUra0ykrd3MrZsvac_SKy58850gHC5yinUBAJsIKxz5ykwKkx2vAhkGCq5qLVeaOx-MGqpG5Mm9FtbrYq02gbZB2kp0TSmM4QtvAMgVMzP2a7s_ZcpFpzAZzvqiN3MWhAAcBYTJfEKeSWZHarHmpF2uKChncdjhqTC7LazNlYtOOteNtdZIJJojYpUzbmA9Uy9cx92T9HIOg-DKtDvyYOOoo7lKpQBEoiaHIuXBDoC6TnKu4brpGhSgRI4FKPu0FHuIJ4dGe1aXrWaz1ne4wPq6T4YC-rpvmsGyKL6vb-j-QbLv-1E5DmG5eOEAgKAoAgYQJ84JIBcGmJxTGgihE78aEQlvEEAjYUiKLiGix4VgRlq4ngMF2mRZJNo-o6yFxHZhs-H6six34Dux6pSQhXF4MBhSPAA7KEDw-d5srQRJf6uTJWYeXmQQhBh0VRUWCI4aipo6VW-mYIZ14jA2FEuuIbpzJZ9FdmFPZqH2AbciFwLmSYEWeAE_nhD5OpQepwUcaFSG1XJooKF5MoSI8sIfGJBm4Vw-GpReBlXqRN6OjlzY1TRhVcYxXUamVrGOamVX8tZpV5Kh9wKLFHzhDKrXyu1zkroBm1HROfUDcUEh8Jdo3peNeCTYRaU_CRQzzdlzpLQd6yrct6y2YduwOYGu0ddV4PuT1nmDaEASvL4kGfQDv5I6q93Zo9oo-JEglTsNgXqd9LQpX901fUIDQANxoNo-C0CA9AIP8WjgFzxCUDy-CQLQLguKQNzULQ-CkAAtrlmBmFACtMPg8sy1QWBuPE8Ai8A-ueFgAAm8QAKQlimYCkFL9CmyLcR7E4bggJrIBK800AABYgAA7lNnApsKOzQMoVji6QFUEtk9BMArt4AHISz7XP0C43SkPAADCPssPgytEsDVDELQpBF5gkBMKbtAAK4BhEbDUFOfAW1QWn2KQ9Ba3oVA-G37DUAP7ed1wkAgFYAAqJfV7XDeVxgLvwA84Nux7CuUKvgjZGATBuKQBFDgA9MfEYMD70ty4vKtqxrvcWnX9DAFzPPwJ4xAsAn0BREc4U89AfA2B4Dx0Ts3AAbt0OupBm5kEgMAbuQD9YIE_tXBW0B2ZZkgNYOukB6A7WcgAAywEwAAPgAEiwHAhBPdLbxEIcTDAxC3AUKwKA0g8R4hYB9pAUhXDgCsMgWAaBnDCGXAwKfagutSGAE34wArdaAHDTQANOaAHHEwAFK6AHYLQA8Pp63kWowAG3mABLo7RWBuCyLkZorR3B4g3zwA0CoAArEADBPBUAADr0CoFETB11Dji2AD7J2WYmBBOchgboEt6CjFIGYQujCLQ83wOoWgAAvW8q9iDcFsVwVWPcABiCdaBgHmFQKepAADWIBsl4FyfgAA6qQVO5wB58HEfASR596CX3FnEy4MFxBuFCWEiJLgomkhib0rMGBanJLSU4U6mTqm33yYU4pTgAAKDAXAFIzvAdQOclnTMSQ0pplAWnxI6ShC-V9JlhPgJ_U2tcM56AEPAKmCwZgND6cTYAQznIjLGTQCZhyEk91mbeBZWT4m1IKQrIpJTNkZx2S4PZBzoXHMaS4NOZy-Aoy4A8p5LgXnN1ea8qcXypntOPiTbW1yelLP6VwHhfz1QeGAOUlwE8n6mxzlcrpNyQX-1oKbfAgSSphMvqcxQrSswaVLGsRlpsNYhIIbBS4QjoGZFxcTdhtxJ7ZwUEsveB8j40soGHRAfB7Ffh0Ja611xkSAUZX8eAGqSSr1ebq_I-r4ASCHsaw-IszUWoUParaHI7UVB2MiR13JXVQJJCpT1CdbwTysCvf1-9A3ALBBaiQYaoDlUjdG_WzrgFupxcmxOer01BCoLGwc8bhEkn4lW1NPqfD1rLVgJtmr4BeW1SAlNNbs7hC7RJXtJJW5tpHf28dcaK3wD8DO716apzzsbYuqKK7nA-oCBuxUk6t7byHdW1dBq-AHtTEe31g6vW7vTYJLtdMMBy0VpoQgtsWV4DdpAU20s6nCtFVvQCv7_2QF5TxKgABiPJcGDzMzGizNA8QgA)
![image](https://github.com/user-attachments/assets/327cfe37-45c7-43f6-8395-bf6b466f7dd9)
📌 please close issue if problem solved.

**Comment by Child-qjj** [comment]
> you can set the label text color to match the gradient - [Demo](https://echarts.apache.org/examples/en/editor.html?code=MYewNiBODOC8AEBtAsAKHh-BvNnMBcBPABwFMAueAIjAEsA7UgQ0ioBpc94APSgBg7ouhfoK48ATKM55CU-AEYxXUBEgBlfCGLRKKIeJwHx8EADMz0UvmnHxqqJSqQA5gCMmACgkBWH2wBOABY2BQkANlCASioZLgBfZUM48XNLa0olFJVwR2pXD28_QJCwyL4AOiCY7Ix47IBdJMwXCA8wSjMmMCs4xLijcSIyJzpGFnZs3ngBbJEZ5oxueVm7eDlMxfgHDS0dPVrsQ4w0qxsF4-3cyCcCrwUAZkjwiTZffwUatbqtjEGTE4WM6bS47W7ue5PNgvN7FSrVWLfeD1NZNbKtEDtTrdXrGfrGf54YYUahjZisLbTVbiebUrjLWw0-RZNY7TTaXRIQ6EkynDIXJEYMH5CFFfwBSISCQPaKIgH4gE81JA_ksgFC67gwrvQKS6VseFfeWNLYYrHwLo9Uh9ZpK-DE0YMcmTNZUra0ykrd3MrZsvac_SKy58850gHC5yinUBAJsIKxz5ykwKkx2vAhkGCq5qLVeaOx-MGqpG5Mm9FtbrYq02gbZB2kp0TSmM4QtvAMgVMzP2a7s_ZcpFpzAZzvqiN3MWhAAcBYTJfEKeSWZHarHmpF2uKChncdjhqTC7LazNlYtOOteNtdZIJJojYpUzbmA9Uy9cx92T9HIOg-DKtDvyYOOoo7lKpQBEoiaHIuXBDoC6TnKu4brpGhSgRI4FKPu0FHuIJ4dGe1aXrWaz1ne4wPq6T4YC-rpvmsGyKL6vb-j-QbLv-1E5DmG5eOEAgKAoAgYQJ84JIBcGmJxTGgihE78aEQlvEEAjYUiKLiGix4VgRlq4ngMF2mRZJNo-o6yFxHZhs-H6six34Dux6pSQhXF4MBhSPAA7KEDw-d5srQRJf6uTJWYeXmQQhBh0VRUWCI4aipo6VW-mYIZ14jA2FEuuIbpzJZ9FdmFPZqH2AbciFwLmSYEWeAE_nhD5OpQepwUcaFSG1XJooKF5MoSI8sIfGJBm4Vw-GpReBlXqRN6OjlzY1TRhVcYxXUamVrGOamVX8tZpV5Kh9wKLFHzhDKrXyu1zkroBm1HROfUDcUEh8Jdo3peNeCTYRaU_CRQzzdlzpLQd6yrct6y2YduwOYGu0ddV4PuT1nmDaEASvL4kGfQDv5I6q93Zo9oo-JEglTsNgXqd9LQpX901fUIDQANxoNo-C0CA9AIP8WjgFzxCUDy-CQLQLguKQNzULQ-CkAAtrlmBmFACtMPg8sy1QWBuPE8Ai8A-ueFgAAm8QAKQlimYCkFL9CmyLcR7E4bggJrIBK800AABYgAA7lNnApsKOzQMoVji6QFUEtk9BMArt4AHISz7XP0C43SkPAADCPssPgytEsDVDELQpBF5gkBMKbtAAK4BhEbDUFOfAW1QWn2KQ9Ba3oVA-G37DUAP7ed1wkAgFYAAqJfV7XDeVxgLvwA84Nux7CuUKvgjZGATBuKQBFDgA9MfEYMD70ty4vKtqxrvcWnX9DAFzPPwJ4xAsAn0BREc4U89AfA2B4Dx0Ts3AAbt0OupBm5kEgMAbuQD9YIE_tXBW0B2ZZkgNYOukB6A7WcgAAywEwAAPgAEiwHAhBPdLbxEIcTDAxC3AUKwKA0g8R4hYB9pAUhXDgCsMgWAaBnDCGXAwKfagutSGAE34wArdaAHDTQANOaAHHEwAFK6AHYLQA8Pp63kWowAG3mABLo7RWBuCyLkZorR3B4g3zwA0CoAArEADBPBUAADr0CoFETB11Dji2AD7J2WYmBBOchgboEt6CjFIGYQujCLQ83wOoWgAAvW8q9iDcFsVwVWPcABiCdaBgHmFQKepAADWIBsl4FyfgAA6qQVO5wB58HEfASR596CX3FnEy4MFxBuFCWEiJLgomkhib0rMGBanJLSU4U6mTqm33yYU4pTgAAKDAXAFIzvAdQOclnTMSQ0pplAWnxI6ShC-V9JlhPgJ_U2tcM56AEPAKmCwZgND6cTYAQznIjLGTQCZhyEk91mbeBZWT4m1IKQrIpJTNkZx2S4PZBzoXHMaS4NOZy-Aoy4A8p5LgXnN1ea8qcXypntOPiTbW1yelLP6VwHhfz1QeGAOUlwE8n6mxzlcrpNyQX-1oKbfAgSSphMvqcxQrSswaVLGsRlpsNYhIIbBS4QjoGZFxcTdhtxJ7ZwUEsveB8j40soGHRAfB7Ffh0Ja611xkSAUZX8eAGqSSr1ebq_I-r4ASCHsaw-IszUWoUParaHI7UVB2MiR13JXVQJJCpT1CdbwTysCvf1-9A3ALBBaiQYaoDlUjdG_WzrgFupxcmxOer01BCoLGwc8bhEkn4lW1NPqfD1rLVgJtmr4BeW1SAlNNbs7hC7RJXtJJW5tpHf28dcaK3wD8DO716apzzsbYuqKK7nA-oCBuxUk6t7byHdW1dBq-AHtTEe31g6vW7vTYJLtdMMBy0VpoQgtsWV4DdpAU20s6nCtFVvQCv7_2QF5TxKgABiPJcGDzMzGizNA8QgA) ![image](https://private-user-images.githubusercontent.com/13038071/354436007-327cfe37-45c7-43f6-8395-bf6b466f7dd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjUxNTUsIm5iZiI6MTcyMjU2NDg1NSwicGF0aCI6Ii8xMzAzODA3MS8zNTQ0MzYwMDctMzI3Y2ZlMzctNDVjNy00M2Y2LTgzOTUtYmY2YjQ2NmY3ZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAyMTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMTg2ODJiN2U0ZjhkZTJkMzMyM2NhOTUxNDMwM2U1OWQxZWVlNWQzNDZiYzFkMmNlYmY0NzUwNzQxNDBhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lijqlpQKwZRYTZqHwV0T_qzIw6ANVwndKBon3H_DvfM) 📌 please close issue if problem solved.

That's what I'm doing now. I might prefer automation config
