### ISSUE TITLE
[Bug] Linechart with multiple series using dataset only renders the total amount of points of the first series

### ISSUE THREAD

**Issue by hazren-sulaiman** [apache/echarts#20223]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&version=5.5.1&code=PYBwLglsB2AEC8sDeAoWsAmBDMWDOApmAFzJrqx7ACuATgMYGmoUUYCMpA2uwDQBMAXV7lWGftwAsA4aIoB6eR259-vAMyzW6ReKkDeANi3aM67gFYjvAOwmxk_QE4ZcgL7k3I9AA8Agj4QeMxyYACeIEywAOQAblgANtQE0d4UeAAWwADupGC0yZ5pYQFBIazhkaRxicmpcpk5eQUEReSEtBAEwbBccizaBND0wBhRA9qwPtUc9ZPoYTP80XLoXquwlVHRCRDQKe5p6BMUQyNj5fPTMWZz84s3kiuT65Nb1bv7zxQe6CZgwGACUgIEu6EauU2LTa6CwnSwYNgQywACMEgQMM1CmsUG4ANxAA

### Steps to Reproduce

The issue can be seen in the Minimal Reproduction Link.

### Current Behavior

1. I have a linechart with two series. 
2. Series 1 has 2 data and series 2 has 3 data. 
3. The data are declared in datasets like the following:

dataset: {
    source: {
      d1: [1,2],
      d2: [4,2],
      d3: [5,6,7],
      d4: [4,9,2]
    }
  }

4. Series 1 will take in d1 and d2 using encode:

encode: {
        x: 'd1',
        y: 'd2'
      }

5. Series 2 will task in d3 and d4 using encode:

encode: {
        x: 'd3',
        y: 'd4'
      }

6. When rendered, it only display a total of 2 data for both series. Series 2 is missing the last data which is (7,2).

### Expected Behavior

Expected result:

Series 1 to display 2 data: (1,4) and (2,2)
Series 2 to display 3 data: (5,4), (6,9), and (7,2)

### Environment

```markdown
- OS:MacOS
- Browser:Google Chrome
- Framework:
```

**Comment by helgasoft** [comment]
[dataset](https://echarts.apache.org/handbook/en/concepts/dataset/) defines rows and columns which implies that it is a **rectangular matrix**. Your matrix is not rectangular hence the problem. Solution is to fill missing values with _null_:
```
      d1: [1,2,null],
      d2: [4,2,null],
```
📌 please close issue if problem solved.

**Comment by hazren-sulaiman** [comment]
Thank you!
