### ISSUE TITLE
Different grid.left between ms edge window and ubuntu

### ISSUE THREAD

**Issue by dino-claw** [apache/echarts#20257]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/winter-leaf-3zcv6n

### Steps to Reproduce

You can open [codesandbox demo](https://codesandbox.io/p/sandbox/winter-leaf-3zcv6n) on window to see the issue
1. enter https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts on MS EDGE `WINDOW` and `UBUNTU`
2. enter option ={
  title: {
    text: null,
    left: 'center',
    top: '2%',
    textStyle: {
      fontWeight: 'normal',
      fontSize: '18px',
      fontFamily:
        '"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif'
    }
  },
  subtext: null,
  legend: {
    orient: 'horizontal',
    top: 'bottom',
    textStyle: {
      fontWeight: 'bold',
      fontSize: '12px',
      fontFamily:
        '"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',
      color: '#333333',
      padding: [0, 10, 0, -7],
      lineHeight: 12
    },
    itemHeight: 12,
    icon: 'circle',
    itemGap: 3
  },
  tooltip: {
    textStyle: {
      fontSize: '12'
    },
    padding: 7
  },
  grid: {
    containLabel: true,
    left: '0',
    top: '8%',
    bottom: '9%'
  },
  series: [
    {
      data: [9],
      type: 'bar',
      itemStyle: {}
    }
  ],
  xAxis: {
    minInterval: 1
  },
  yAxis: {
    z: 1000,
    data: ['test1@eeeeeeeeeee.cccccccccc.com'],
    axisLabel: {
      fontSize: 10
    }
  },
  graphic: [
    {
      type: 'text',
      left: 'center',
      bottom: 5,
      silent: true,
      style: {
        text: 'Messages',
        fill: '#666666',
        fontFamily:
          '"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',
        fontSize: 12
      }
    }
  ],
  id: 'top-recipients'
}

### Current Behavior
when using grid.left: '0'
on Window, the y labels overflowed but it works fine on Ubuntu  

![image](https://github.com/user-attachments/assets/5cfc01b6-1025-4bec-8890-61fa97ac9ce8)

### Expected Behavior

It should be the same at both window and Ubuntu with ms edge

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
_grid.left_ set to 5+ pixels helps.
_containLabel_ helps as well, but cannot do the impossible. A horizontal label 222px wide will never fit in a 200px wide chart.
There are many options to deal with long axis labels. See [axisLabel](https://echarts.apache.org/en/option.html#yAxis.axisLabel) and try rotate, inside and width + overflow. [Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurAMYxgCGE0AMpQEYCmANoWFgK5MA0x6LJgDMwhAKzEAvn3S5KVAM5NRyWAuCcspJoQDaugORgmCsAEYAAk2s3bTAHSknzl4-ABbAz1gBOALp-sNLESjgmekiwYACeIDqwBgyUWAZBft5gwMAskCD4SMHoAB4AgkUQCoSR7jQAktDGWABulGywZkEysNFlFVVRsfEGpPJMGMBY0V6wAF74Zgtd6JTlCvTMbZH8JAD0O1jAVMaEPgAM3tvoNAp4Ohzc3uQsE_gG0azPAO5el7B7n3gwAALeaLWDAJpMLBCL6ve7QEbGH4kEhCCgAZQgM3iZlOsG2kiCKEkAG4gA)

**Comment by dino-claw** [comment]
I tried with grid.left 2% so it can work on width 960px and width 200px chart simultaneously. I wonder why it's only happens on window

**Comment by dino-claw** [comment]
Thanks for the investigate
