### ISSUE TITLE
[Bug] when effectScatter and legend are used on the map, effectScatter cannot be hidden when legend is switched multiple times

### ISSUE THREAD

**Issue by huyu456** [apache/echarts#20286]
### Version

5.5.0

### Link to Minimal Reproduction

no

### Steps to Reproduce

option configuration
```
  option = {
    geo: [
      {
        map: "china",
        roam: false,
        silent: true,
        layoutSize: "100%",
        zoom: 1.2,
        itemStyle: {
          borderColor: "#c9c9c9",
          borderWidth: 1,
          areaColor: "#ffffff",
        },
        emphasis: {
          label: {
            show: false,
            color: "#ffffff",
          },
        },
      },
    ],
    legend: {
      itemWidth: 9,
      itemHeight: 9,
      orient: "vertical",
      icon: "circle",
      // data: ["用户地域分布", "服务商地域分布"],
    },
    tooltip: {
      trigger: "item",
    },
    series: [
      // 用户
      {
        type: "effectScatter",
        coordinateSystem: "geo",
        name: "用户地域分布",
        data: [
          { name: "上海", value: [121.472644, 31.231706, 123] },
          { name: "北京", value: [116.405285, 39.904989, 100] },
          { name: "山东", value: [117.000923, 36.675807, 23] },
          { name: "宁夏", value: [106.278179, 38.46637, 43] },
        ],
        symbolSize: 15,
        symbolOffset: [-10, -10],
        encode: {
          value: 2,
        },
        zlevel: 2,
        label: false,
        itemStyle: {
          color: "#95FF58", //散点颜色
        },
      },
    ],
  }
```

### Current Behavior

after continuously switching legend, effectScatter cannot be hidden
![1724400440090](https://github.com/user-attachments/assets/375af65b-e65d-4cd2-b842-a5ec6d198105)

### Expected Behavior

effectScatter can be hidden and displayed normally，I tested scatter to hide and display properly, but effectScatter did not

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
set ```legendHoverLink:false``` in effectScatter series
📌 please close issue if problem solved.

**Comment by huyu456** [comment]
> set `legendHoverLink:false` in effectScatter series 📌 please close issue if problem solved.

I've tried. It doesn't work

**Comment by helgasoft** [comment]
how did you try? no code provided ... works for me - [Demo](https://echarts.apache.org/examples/en/editor.html?c=geo-svg-scatter-simple&code=CQOg5gpgLgFASgeQQFQPoAUCCyASACAajwHIB6AEwEMpLTKBne6UyAe1IFlKAHVVgM1QBJAMYQANpQB25EPQBuYYgBo8_AK5SRUAJaspeGArABKPAG8AUHjwQRAC0oAnKPRBOIYHfSgQnXbhhiHTFJGVRjFQs8YwAuGMU8AF8TAG5rPFZuXX08AF4LDJsoVlZxXW548yTVcU8IGVjq5SK8NirW4tLynUrCmwGB-ntWAHd4qCd1CE7klsGbAFseeODQ6XIIxRVZp1ZKRYmpmcGa1qYnHQh6DoW8KABPbghViH5-OygAZRFqXycorMpAcXiQ3h9tFE6pAZDhWPI_AAZHRSADWsX4lHETHmCxEpSc5BR1AgXwePgghxIbB2dzYQhkEAAHvEAAy4wb0B6LABGZS-OgAXqCNFocgYYNxnAd6GYrHcbB4oOonBKpU4ZQBtABMAF08KQ8ABGVmsswAKmNAFZCHgrek7mc7jpfIsvo86rcFfjxKwnKsAMQ81naygh4izJ0LBr48ig-UKkplCrxbWRjkDKg0eKa2Y2TUAFgAHEWQNqAMxWosF7UmgDsRdZVvLqgLVoAnCA66z20by0Xy-XWXWrXXywA2VQm1m6jODTV17sgcsFo1W8cFgvlo3t9vl9uqEd1kDt8d12vtgvtosbkeqIezvN4TVGo2NkCs8va9va6s78ffkah5biA45GqujYDgWAHgaojaPgqz5FpeH7lnW7asuOX7am2U5vqWO5Flaa79pWppFqoYEIQqL5odqJ7Idq65DtuLZ4AWi7LgOu4lhu7bNnWh4znOAy0Q2oHakxRpMaOp6qHuVqgd21Y3r-v5bnBRq6rM2mnBkSQOngiwPAAwo4LhyNACDZHoUgwFk4ppJYKSpEAA)

**Comment by huyu456** [comment]
> how did you try? no code provided ... works for me - [Demo](https://echarts.apache.org/examples/en/editor.html?c=geo-svg-scatter-simple&code=CQOg5gpgLgFASgeQQFQPoAUCCyASACAajwHIB6AEwEMpLTKBne6UyAe1IFlKAHVVgM1QBJAMYQANpQB25EPQBuYYgBo8_AK5SRUAJaspeGArABKPAG8AUHjwQRAC0oAnKPRBOIYHfSgQnXbhhiHTFJGVRjFQs8YwAuGMU8AF8TAG5rPFZuXX08AF4LDJsoVlZxXW548yTVcU8IGVjq5SK8NirW4tLynUrCmwGB-ntWAHd4qCd1CE7klsGbAFseeODQ6XIIxRVZp1ZKRYmpmcGa1qYnHQh6DoW8KABPbghViH5-OygAZRFqXycorMpAcXiQ3h9tFE6pAZDhWPI_AAZHRSADWsX4lHETHmCxEpSc5BR1AgXwePgghxIbB2dzYQhkEAAHvEAAy4wb0B6LABGZS-OgAXqCNFocgYYNxnAd6GYrHcbB4oOonBKpU4ZQBtABMAF08KQ8ABGVmsswAKmNAFZCHgrek7mc7jpfIsvo86rcFfjxKwnKsAMQ81naygh4izJ0LBr48ig-UKkplCrxbWRjkDKg0eKa2Y2TUAFgAHEWQNqAMxWosF7UmgDsRdZVvLqgLVoAnCA66z20by0Xy-XWXWrXXywA2VQm1m6jODTV17sgcsFo1W8cFgvlo3t9vl9uqEd1kDt8d12vtgvtosbkeqIezvN4TVGo2NkCs8va9va6s78ffkah5biA45GqujYDgWAHgaojaPgqz5FpeH7lnW7asuOX7am2U5vqWO5Flaa79pWppFqoYEIQqL5odqJ7Idq65DtuLZ4AWi7LgOu4lhu7bNnWh4znOAy0Q2oHakxRpMaOp6qHuVqgd21Y3r-v5bnBRq6rM2mnBkSQOngiwPAAwo4LhyNACDZHoUgwFk4ppJYKSpEAA)

Thank you for your answer, I use it in vue, the problem still exists, but I use it alone in HTML, it works normally, I think it may be my configuration error or echarts.use has a component that is not introduced
