### ISSUE TITLE
[Bug] TreeMap Label rich backgroundColor image DataURI not working ( showing broken image )

### ISSUE THREAD

**Issue by hassanedelbi** [apache/echarts#20280]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&lang=ts&code=MYewdgzgLgBMBOBTAhlRB1eyAO3EBMBlANQHEBJAW2QHNEYBeGACgEpGA-GAbwCgY44aDACW1OoREAvekwCMABgUBufoMixsyfPhFgajGItUDQGmACNkwANY14IAK5h8AYRAAbEPEMAiJPi-JurCABaIIjShsExitIiSMjAA1DAATDAAVDBaOno0wWbCAO4i-FChhnES0vSpGdm5uvqqakWwemCI8OhlFVXiCbWFQh1gXfAAEhFRMaKDiYitpqMwEABuNO5gaDuGAAZqAgA8Gwal5aEMvgAk3BcVAL6-MOGR0dd3b7PPMAAelA8kGu0Sg2AAXAB6SHFWEAOmKAGY4d4aJC0koFJCzr4OEcBDBjkhgLAHldbvc-qFft8PhTaVBfgAzEQeDyfbhWWz2JwudxeeC_SF4gkE47VRD40WhJBMkFQMEQKGQxDAULIeBQCBwnDWcIo-BoxBgSESiCQrw0EBw7D6AD8AH11g6GBi0gAWBRpNIANl8UoJfw5TXyzwDAgAnsHtM0aGHRaKyRzOt1epd4wmBAzk-NutN3oz_ZnhfjjtjNiKYPtljAkFBHPAwFX8KhkOCJeWaMkAR5lFYIIgfe6ADR3CxQEDIZhnba7KCsR7V3iPVq8XggbBQETgQx8AQD-AiRBKmAAbXxe4TUAjeHBMAA5FAkIhqNh78OAy2oG2z-GeH-BDAZBKEQO97zAEB8EQABBd8AJgdZkA8RxQKMBQP0zUU1VZfAkDAO9z0whNLyI0UgJAsCIKg6DkDg0iE0Q5DUPdeCBEeDD6P_TiCXI1DwMgmCLDo7iEKQlC7x9ViYEeeCAF0_3Yv8SMw3jKIEgAhYSiMY8T0nQ-DsI8XDjQIqTlPo1SHyoxB1NojjuJ01CMXszjDOM_DfxEglzJEyz-Kg2y5C0rzRKYu8MSk0UZK8-TuOi0jYsw-LRVklyBA8ZALEQDw7x8gQmW8agFW6O8mWcEltybNguNIusGybe9uDEGgAB9HnvYJM0UojDzVXL4Oa_ruK5OwHGcNxPG8IaRIlO8EBQNBMBwPAiDIKh4jYNLSOhQRKBAvYKnoTKQHWRBhxgcqQD241YEOyxspAYpIpgHaJRgcFfFBbAlWhVV1U1bVdTVRADSNE0zQtEArRte0nRdN1PW9P1WO6ziGTvABWfTuLJcKlHg5KE0Jtj8Xi-SVyAA

### Steps to Reproduce

1. Go to the [Link to Minimal Reproduction](https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&lang=ts&code=MYewdgzgLgBMBOBTAhlRB1eyAO3EBMBlANQHEBJAW2QHNEYBeGACgEpGA-GAbwCgY44aDACW1OoREAvekwCMABgUBufoMixsyfPhFgajGItUDQGmACNkwANY14IAK5h8AYRAAbEPEMAiJPi-JurCABaIIjShsExitIiSMjAA1DAATDAAVDBaOno0wWbCAO4i-FChhnES0vSpGdm5uvqqakWwemCI8OhlFVXiCbWFQh1gXfAAEhFRMaKDiYitpqMwEABuNO5gaDuGAAZqAgA8Gwal5aEMvgAk3BcVAL6-MOGR0dd3b7PPMAAelA8kGu0Sg2AAXAB6SHFWEAOmKAGY4d4aJC0koFJCzr4OEcBDBjkhgLAHldbvc-qFft8PhTaVBfgAzEQeDyfbhWWz2JwudxeeC_SF4gkE47VRD40WhJBMkFQMEQKGQxDAULIeBQCBwnDWcIo-BoxBgSESiCQrw0EBw7D6AD8AH11g6GBi0gAWBRpNIANl8UoJfw5TXyzwDAgAnsHtM0aGHRaKyRzOt1epd4wmBAzk-NutN3oz_ZnhfjjtjNiKYPtljAkFBHPAwFX8KhkOCJeWaMkAR5lFYIIgfe6ADR3CxQEDIZhnba7KCsR7V3iPVq8XggbBQETgQx8AQD-AiRBKmAAbXxe4TUAjeHBMAA5FAkIhqNh78OAy2oG2z-GeH-BDAZBKEQO97zAEB8EQABBd8AJgdZkA8RxQKMBQP0zUU1VZfAkDAO9z0whNLyI0UgJAsCIKg6DkDg0iE0Q5DUPdeCBEeDD6P_TiCXI1DwMgmCLDo7iEKQlC7x9ViYEeeCAF0_3Yv8SMw3jKIEgAhYSiMY8T0nQ-DsI8XDjQIqTlPo1SHyoxB1NojjuJ01CMXszjDOM_DfxEglzJEyz-Kg2y5C0rzRKYu8MSk0UZK8-TuOi0jYsw-LRVklyBA8ZALEQDw7x8gQmW8agFW6O8mWcEltybNguNIusGybe9uDEGgAB9HnvYJM0UojDzVXL4Oa_ruK5OwHGcNxPG8IaRIlO8EBQNBMBwPAiDIKh4jYNLSOhQRKBAvYKnoTKQHWRBhxgcqQD241YEOyxspAYpIpgHaJRgcFfFBbAlWhVV1U1bVdTVRADSNE0zQtEArRte0nRdN1PW9P1WO6ziGTvABWfTuLJcKlHg5KE0Jtj8Xi-SVyAA)
2. The image will show as broken, Comment Line 72 and uncomment Line 74, The image will render correctly.

### Current Behavior

Showing a Red Rectangle with broken image

### Expected Behavior

Showing a Red Rectangle with the actual Image

### Environment

```markdown
- OS:
- Browser: Tried on Edge, Chrome
- Framework:
```

### Any additional comments?

I need to be able to put the logos of the companies in a background circle like in [TradingView HeatMap](https://www.tradingview.com/heatmap/stock/#%7B%22dataSource%22%3A%22SPX500%22%2C%22blockColor%22%3A%22Perf.YTD%22%2C%22blockSize%22%3A%22market_cap_basic%22%2C%22grouping%22%3A%22sector%22%7D)

**Comment by plainheart** [comment]
In this case, you must also convert the nested `<image>` href to data URI.
