### ISSUE TITLE
[Bug] when specified calendar.monthLabel.nameMap option, echarts halts with error

### ISSUE THREAD

**Issue by sksthrs** [apache/echarts#20299]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=area-pieces&version=5.5.1&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5JALZW0A0J6ARsAK7QAmAQwBO5AOICQRAGYCANniokAvm3Tkc-IqlJlKNWLQBuc7s1WkuvQSPGTYAbQAMLAwGZHAUloBdZeYDGclT8wlrssAwwYAAWADICHFSyYTro0AJMALISRPYARACMeSx5AEzFea4VACwVAKwVAGwVAOwVABwVAJwVBY69RSUF5d7m6Ep-JIb43HLZdtqkFNR0IBBU_lQA7vhm4XjRwFvScgpjsHwQTNB4UNBEzvtUQut4AJL8VBgP52sbVIQHOF0ItUrAAOZgIgFc46WRQ2CuWGkfzAWTAIR0ITgjgCAAUzlghIK7UJjgAdNUAJS0YGwFR00GpSFEOrI9DwogtdmwVHozEGbG4gkuYmk0WUml0iY6XzjcwKF4A3LhJnoZb6WiyCDQPZgvCRYAxB7kxrIvDkBhcZIGaAwPWpbW6gDKFFk-jVKLRGLoAGI6tUWo4AMKNVh09A7PjG2B1aXIhjCADWsR1HojsAtVrRuVodt1rFt9p8PNkCSSWkzh2OsBk8io9J5gjAAlySEwGkBBUbyA7uEBrh77ew_dZQ77mlgLXpctSDLBwioAld5HdWnnqWbraBYPQ9jxuq2sAAIgIwFQ8bRSo4Cl0ALR9B-OWhUqnk8FUMAAFSuF6pLmvRxRgzfdDxPM8LyvG97wKAoHwKF83w_b9fzxf9Y0aICeVA7ZwPPS9r1vB9SmIxD30_H8mDQlwWjqLCQIPXDT3wqDrzvG8H1cMjkMov8XDqUlgN3BxGKPZjIOvNjHBIgpqm4ijUPQ0o6KE3ccLEiCCOkxx2PaB86nklCqPQ9x6OE9S8Ik7T2JgsNX3Ioy-NgaoVOw0TLK0tjYIfFpDN46jEUcMy1Pc8TPLg6SH3aPzFJcPogLpWdxhIXwlAAbiAA

### Steps to Reproduce

1. make table with x-axis as timestamp (milliseconds from 1970-01-01T00:00:00Z)
2. include option calendar.monthLabel.nameMap as array of string (example: ["1", "2", ..., "12"])
3. draw chart

### Current Behavior

no chart appears.
in console, an error (accessing undefined.toString()) is reported.

### Expected Behavior

chart appears, its x-axis label is based on nameMap option.

### Environment

```markdown
- OS: Windows 11 23H2
- Browser: Mozilla Firefox 129.0.2
- Framework: of official editor's
```

### Any additional comments?

When you remove `calendar` object from the option, it works and a chart appears.

**Comment by helgasoft** [comment]
[calendar.range](https://echarts.apache.org/en/option.html#calendar.range) is required, but missing in your code.
📌 please close issue if problem solved.

**Comment by sksthrs** [comment]
Thank you, I confirmed adding calendar.range enables Echarts work again.
I close this issue, but I'd be happy if remark like 'make sure setting calendar.range' to the nameMap option document.
