### ISSUE TITLE
[Feature] [Question] Bars inside bar on Chart

### ISSUE THREAD

**Issue by ImSpectrum** [apache/echarts#20296]
### What problem does this feature solve?

Hello, can you tell me how to get an effect like in the picture? Maybe it is possible to add something like this to eCharts?

I tried to reproduce it, but I have big problems with responsiveness. 

![image](https://github.com/user-attachments/assets/129091ce-8c5d-4b6b-b6aa-c0e491086d81)

### What does the proposed API look like?

![image](https://github.com/user-attachments/assets/3115f1d9-060b-40c0-833b-c7167d4bd193)

**Comment by helgasoft** [comment]
yes, possible - [Demo](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=CYQwLiAEC8DaDkBZA9gO3gGkvAKgVwFNNsB1A4Y3ACz0oDEAnAS0oGVw290BdAbgChkABzBM0MSAG9-kSAA8AgnKYBnAFyRYM2VNmgIsgL4ZtsyXvAgsKqsgDuagGYgANioJHt3E7ICeS1Q1zAC81AAZIY0gXAgBzAlRgNUkosGRkF1EhZONtd2YCdU1TXVQQAFsCDXgAIxdCTBKLCA1YAEYAJjCsLu7INoBWPoAOPoB2Pra2yYBmMO8myDBfISrsGpAGYlCOktydUoq1-FiGAgTGg-aQVunJ0aw7x-msCawH_vmfK-XV6o2tlgdntvmZFvobppOn1eo8hu9xpMXv05gsrksVscAcQVBAAMYAazU8GAFCwAJITGAYCo1WGwwApJcrniMsgGNUAMQzHkzYiKZQqACSiQIcjUbSBEpBJWk6IhtzC90mSueiIRjy-i1-WM2OPxRJJZMgi1ZLnZXN5fKwAtUIuAYolUraey8_EMvCAA)
![image](https://github.com/user-attachments/assets/14344592-435c-4c26-b736-adc8ae613da8)

**Comment by ImSpectrum** [comment]
> yes, possible - [Demo](https://echarts.apache.org/examples/en/editor.html?c=bar-simple&code=CYQwLiAEC8DaDkBZA9gO3gGkvAKgVwFNNsB1A4Y3ACz0oDEAnAS0oGVw290BdAbgChkABzBM0MSAG9-kSAA8AgnKYBnAFyRYM2VNmgIsgL4ZtsyXvAgsKqsgDuagGYgANioJHt3E7ICeS1Q1zAC81AAZIY0gXAgBzAlRgNUkosGRkF1EhZONtd2YCdU1TXVQQAFsCDXgAIxdCTBKLCA1YAEYAJjCsLu7INoBWPoAOPoB2Pra2yYBmMO8myDBfISrsGpAGYlCOktydUoq1-FiGAgTGg-aQVunJ0aw7x-msCawH_vmfK-XV6o2tlgdntvmZFvobppOn1eo8hu9xpMXv05gsrksVscAcQVBAAMYAazU8GAFCwAJITGAYCo1WGwwApJcrniMsgGNUAMQzHkzYiKZQqACSiQIcjUbSBEpBJWk6IhtzC90mSueiIRjy-i1-WM2OPxRJJZMgi1ZLnZXN5fKwAtUIuAYolUraey8_EMvCAA) ![image](https://private-user-images.githubusercontent.com/13038071/361645938-14344592-435c-4c26-b736-adc8ae613da8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTI1MDksIm5iZiI6MTcyNDgxMjIwOSwicGF0aCI6Ii8xMzAzODA3MS8zNjE2NDU5MzgtMTQzNDQ1OTItNDM1Yy00YzI2LWI3MzYtYWRjOGFlNjEzZGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAyMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNTU2NzllNWU2YTQ2NzRmYzk0ZDQyZTIxOThkMmQ2YmU1MGQ5NGFiZGFhNjUwNmJlNGI3ODliYjRkNjBhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSpI4Gp0z_TUunSvBwMlNkKc207buuHjKutU2Fpxuoc)

Thank you very much! I reworked it, adapting it to my chart. Now everything works correctly.
