### ISSUE TITLE
[Bug] Cannot apply Axis type as value in heatmap

### ISSUE THREAD

**Issue by ycli0536** [apache/echarts#20291]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/echarts-heatmap-axis-value-issue-h5wnx6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm08i5avv00063b6iwgc9a4z5%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm08i5avv00023b6ik12n2q6f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm08i5avv00033b6ijsvywkgj%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm08i5avv00053b6ieijnb73v%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm08i5avv00023b6ik12n2q6f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08i5avv00013b6imt3sm7at%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm08ibwnm00023b6i39cspe45%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2159302%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A2159302%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fpublic%252Fdata.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm08ics1c00023b6i4buzh9gv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm08jjai400023b6ivh8lnq1b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5553%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A5553%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdata.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm08li83f00023b6io8a05kjx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A42%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A42%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fheatmap.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm08i5avv00023b6ik12n2q6f%2522%252C%2522activeTabId%2522%253A%2522cm08li83f00023b6io8a05kjx%2522%257D%252C%2522cm08i5avv00053b6ieijnb73v%2522%253A%257B%2522id%2522%253A%2522cm08i5avv00053b6ieijnb73v%2522%252C%2522activeTabId%2522%253A%2522cm08i92wm002j3b6if6htabfa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08i5avv00043b6i3yyhe1fx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm08i92wm002j3b6if6htabfa%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm08i5avv00033b6ijsvywkgj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm08i5avv00033b6ijsvywkgj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce

Change type in option.xAxis and option.yAxis from 'category' to 'value'.

### Current Behavior

Error: Heatmap on cartesian must have two category axes at HeatmapView._renderOnCartesianAndCalendar

### Expected Behavior

It can shows the 2d matrix data with correct coordinate as in data. So far, it looks like the `data` (in `option`) coordinate is not the real coordinate in my data, e.g., I have to start [i, j] from [0, 0]. In `'category'` type, I have to specify x and y ticks label individually. I wish I can use the coordinate (e.g., dimension) directly from my dataset.
Currently I'm basically following this [example](https://echarts.apache.org/examples/en/editor.html?c=heatmap-large). But I tried to apply dataset in heatmap? I might applied it wrongly. It also shows me a blank graph. You can use `testData` to test dataset mode as well.

### Environment

```markdown
- OS:macOS Ventura 13.2
- Browser: Chrome 127.0.6533.120 (Official Build) (arm64)
- Framework: Vite React TS
```

### Any additional comments?

I thinks this is the same issue as #17164

**Comment by helgasoft** [comment]
Setting **data** for xAxis and yAxis and making them **value** type is not a good idea.
Heatmap works with _dataset_ and axes type 'value' in TS - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts&code=MYewdgzgLgBAJgQygmBeGBtAUDTAGAGhkJgFY8BdAnfIgRiPKpoxICZHLrdWiBmTsx4kALIO60y4liQBs04UQDsCyQA5VvGAE5NJOiSYStdBmS4z6Hc0Ml0BN4_rGPLMOqT315rxe5W-dhqBJroh7IYWPGaGIgB02toibHjafErkeFl4IrYYZmak8dpqaqSkbGoZfKQesnlm1kUJanyysto5ShnZ9cZmDs0leGxsSrJqsuV43X0sZi5DSlWyqXQi2Vlz0YyMxUrassl8JyUifGoNRD5DrTMbeHx0bKRXMAG3nWrPdNps62pcv0iMEhtoMh5nko3mFynEsmo8LIniJ7DkOm8DIxSPCUmxZEo6FVMlkgfN6IUcY8aiJwaQ0nQjpimlSREo2GyDmSdu5BlTVlNzkdvi9MYsqUo-Ejvl8MpjPGQqa0yqkjjUittMAUblS_rSOdpXsD_Nj4SUJm12VllnRMaCcQY2HxwRy-KLjb9TQZneNUUS3Y9NfkiCkvTknc8SdkjSxrIZtAl1tzMNZCgmqi9Uct2TGeNYmum2lC2nlrIN06ltETqu7Y0RFgmDt10my2KXdmQK07rSLcynrox0y9TKRZpscu33oO4pM1c8ni9ssmMNZQQm_hVWwHNsvrLD14kLi9WovSZOsTBVvCyqtx9lbcZU2Yr3Qm2pOt1a3mrNc8HExlaSgTo-9AOFe6QAeykpfv27guFeIiyEmpDIm2IHuAqV6kBc9IiNhkbnj4V63rUIjfLeWQPnWJqXn-Ry0jSpgwSu9DBMRhJITMFSbFR37uGExFqGwhz0mkp68bBoa0XEExkXkDhyPEt5CdWUYSRgDjPvEbJ4NhsiVO-hzqQ41hHHENTIucnSvn2Gn8Nc8RjBy-lpFWeB1PJ9YOf-UrJISRSeVIl6OThiFpKsNSMoFRHxFKHiZLUBHGA4ARmckOQjO59j0ukgVsfE9LdqscrJUQAnxN8eClJU4zIgSfCBReUzwu0FSHMSjXPjifBhTlul_Ic2iNaZOLIgcRKjpcpW8tcOJ6lVgp3DMU0sJp8GyHEvzuRUHJVSVq30JhG3JCkgGPElB3uERG2rCqExCYkj2NalG1KMk5yTJUFSSsumlsRtQnCe07TPLSiSNQJAOjpUlopMtxkhnIAP6a0F08C4chqDOqJBi4z5Y-U3TuRM6kuKZWNSkB_woYi955C4YFY6YfzCUSBh08YLjwVj7mTOyTKcx2Ey4iiSLMfB1xM-c21A_TyiS-ZiLka-DWCzAbFY5Kpg9eCuNldcCZEqq6zi_QciNgYy542YQH_mk3S1ezlFy-41i29ZJsVLTztq_Yyh0HEmQeDU_ybGhLB4y47LwqQrSrIcLseMobCB3hVS9onPjR2kgLnLMicBJK_4pMSqGPeDvvBEXzprGRHjl0NvthEXiE9UhHJg09atSS3GThzwCokNHqKh_btkKjbAedCPvz8yh-J5AqbsB3hoyEqk6Tj_Z7wBwYkqZThb2jIvXnvH-Vb2BnxgKgqtvvqOBL_L86xIifl7-_C420zaBqNywt8f0QhMIC51JRCRWgPEEycY6PEBJvN-zcU5K2pDreOuVr5m2UHwOIQFVgag6hg9wNt4ggLZBMP4VUShb1dsoHEkp2po0wBPFKr0CTtBeNBZIvw37rGUEoHBYwSh81Uu5Hht8CayVjoTZ474eFZwTM5PCY8eGF0bDUEYp1zocggUw1iII_wjENBkH-nceFhERJtcoDxDjnCsdQqSFibI_1sj4IeDouINwbnkHwxDzJIjaOQfEBCWA-Ddtg2OgJuhEmXD4FK2DHgjFKGRUo-0eA-CjinDonEepOi8cYG40DLJuiQoSYJaSBzvCQW9ICkwYny3eNg5I7REhjFjqkzAPgq6OWWO-fE7JvH63eN1RIo5Ei3XaRgHxQ9XoXDqUQ5QWNRidCrG3MpHSfzvEbGkHqgTnTlwGTNdWAcdkZERGAiZPiXBCRwYkFJnQ9ldxCYdEE8QuIbCPqpA5jIQTuLqqqL5AQygznINxRIe1aQ6MmXo9WG1hJnBQm6L55jjoULaEkcF4IDkOI2hURFxgAjTJwR0GYnz8X0FoTJZ4lQhH80NMuAIbsCoWhpmNWyAQ4k4K4YaVIPL9JstPkXUYPUqbJDyB8LB14ZhATSCCyY6lUoSpqJKDIslGEYELsoV5ExiqumWJ0IMgKKVw26OcMK-yyU6GUK9UwIC46MmJmKzB7wCZukBP8YkHMWABFMPowO7IShJBqj1dBXqNnXPZBZHI_LDmAhnIKbMVV7jHwtbwmFM5ZjOjdBcCZ3qFSlBkmFPlnD3WOqumVAxtNhWElLa-Mqu9GQnEWlKLiNbghVk5VKKRTpf5_x4N6sIfx4QjhyG0OuHJoQWqkoO3S5ARSd0eTwYIQ9-FSlyZ4hdmBgg2zoTXQ4Bk8jBEZeZIkocciQuCBy18edyj903QKlO70yK3IeRXFgoJoH11smxaBH0TiBm9qI4wVcJUw0NLHKqB6oHvCUsrPSkHLXvBxeNDo5BlxbqHljUoCcgMUhBCvQ0UwO7nrDY5FC-k6jEZjfw9yUE_jwdTe-Sl748IjDQ88nQU8oT0Z8GkHB1Tkhe3owEQ0m0nQpLdAcR6E633QpE0kZ4MxgIyf4mVWFVZyJFBfUGQ9JBDjmWSXkMIhLiXSvgcYMIvjZJIUsvpH6qsWBhDdkgsibQnRPAmWEFKxy8JFEiSkSKQYwhRz_AGICEFPGGaFumaqh5GQbH0oFipttQbkG5VWZizcP5IlfESSYuEWaRfVoUso3RY5PEK83YoNQWk_TntJngFnl04OWn8ERPsHO4fVn-MokxbntG_r2zAFnVyOXinHcEeSOtUcDrOZ0yQqjBsGxgCzLhOh8cQqMekwDbIWYVLxnKTTemULKIV75OgcTicoaYMOp3hP8JvWUNI_UgbLgs22iREFHhOTBpCizA6sa3JyHSBkdVCtToTNKLWzELxuIaPoaB-FARwImReN2f4XgTDvJ66IJBGbmWFI9ls5r5iiGuNRpycOhYbQuP6HKKO5DXBxd2ynU5Lz8NpGFZHtkLxsQUUjlnzcA5CSOHZ-nTqxfzOdTJZ09qx7Y61PoVcKcigQf6PoBwkw4icnGBvHo7Wcf0FW-jjwt78j6D2-E1dovuf6B47CkOLPa06EWYGM4RORmO7bQmB4kn12QovJ6HQ657XVfd0kFnUl2YNBiNA9IiJ3Uo4KAbLXiFJRunwrpRC0eQyM4EaJHMpXs8wDAtpSoOXATYTOMuH1MB4IpzekjuBL7DRF8wkLzkhjUTMYqNz581whfZtQycNVNfUr15NdSDodRodmHyjJFC2zU9F4EuzpEDsG1vXjkXi8d9DQpEQlUTu_uCi-JlTV4V-JRzb7dgoxI7MMjV4KBr7BOZ1F2tWK-bfVz-FJESj8DFx-7G7aICJQJwtIaC9WWo2oZUJCb0-oBIve9Ad2Q6BI4CtUbQBI2-72isw-FwJwPa2-_2CQOYyI6waIWe_QjQumEOwCC43OcYye6Izek20QqYs0MkU-VoqIDQ-Y1wyuzwMqBIEW_QZY04Zy50UqPBp8o4RKEaw4puzwHYKEfq5A0-86S2ih78ZA1OSE5wvw1W5c9B9SMhvw5Q-qIg6hQYmha4n8JqUSChe4_eCQ6QWQown-IhTqzUyIJYHhkuHQCQUwucsc6kmhmhb0MksGPh8wqYKU3uSQDEqQICrhUhcELym0OQ8BhILBWoqYeaiyToGwdBKRZ27aqwbIOsOu2QDhSBMBn8QkDePa4evhRIZUOIsceoEavwj0_uqYA6sK6Uyo4w5cIR-Yum1OBm_QCk7BlQt49s6hDQmkThtI7IVQiSYWBgVhJkjAP-WaHgpQV6fWCx28zQqMowSSSQJwscRxtejAD6x4qITwL6KOgwnAiY5Q7Rok8cChYErxFhucKk7cYM1xHwu89wHQvkwqAs8wGutxCQvMpSSQ5cJ2kxgycI4wm8jaVY88PU1xF49Iqc4IBwwCR-3OmkWk8IZE0oeWiJ3xGywsYKToQEoyxO0QmkKUWqkwMwuq74r8KJqRUuhoPWukx4b0JQuJea2Cbcr4WQ7mR4_umknSG0hwSI4IxwPEuJgKCY7chGWUoeuJbaAcToBIoMc6iQkB-QmkA6U8eyC4vw_wbI1eJkumKcM6VUoMwh8wGMSxdQWO0YDQeM2x_4Rw80rMp43OZMjAkpboRkGwAGIRDM9Y6YRwGUYUkYgGnpp8bI6RqQ_mcM941eiw9YOIHCZEqEvYWQ4ZFSFhWu4IqQdcFE20_p9S1ZVYUwzSIMi48ZUGiEgcNQqM4UPElZCGtIdsboz8pxgSTZ7ghg8SiEDwWOXZkuMhk04IQk9IaZUU_QeMpkmSxY_6g5U5fsbOM4mY8RPUaZChkc0Ch-NSyZ6pW57G3QWul-QiZenZh5nSu8bkJuypVRh5gK2CRk6miITEHOh5wQQK7QkUo4GQSJh5yKWumUfk-EBol5iMIITO24WObYWAFAAA3FgFgCAAAA5QAACW4AaAMAAA3jQFACACAAADbkXEUABcNFAAvhIAAB4ACC3FZFEA7FtFuAuAUAAAnsRQAKbsUADkAAbggIxQAK5SWyU0BcU0DiX8WCXCU0BiWSUyUwAKVKWqXqW4CaW4DyWCXKVKUACyCAbFNF-lMAAAtmRWAOxYQC5a5QgNxexezBILgMAEpcAMpYxQgAAEaMVGVQAABOqlQVMAcVUlSl5FrlRlAAZkpRAFJUlR5QAEoIBgAADmRlIlolwVTFIAcV7F2AlVlVslAAxI8ShrJUlY1U1XhBkJFSIO1S5Z1W9AgHAHAHQP1Q1aJc1VFXANoFJdoONRNcZU1VJXgJlXwJlWoAtRNc1ZlbtZlZFZlVtQ1TtVJStZ0EdZ1ZlYgFJUhBdZNU1ZlYhHAOcHdbgM1XAPvGMK9UtQgJkPiOZQ1RQC5ZZaJWRVAFJa5QAOpkVwBQAAAW7FLw-V4NrlAAElJWRSVXDVAOxeoklUpZjZ5cZQgMpfRUdR5fJVJXFblexdlYxblUlTVWRVJWADjcZXDUzQAF7gDICMVHUxWZVs2yXAAs3g1xVHXEXDVwAeUlV1X6BZBEDy2UAaUSCIDIC5Vs3UUwAQAgDKVxUi3sVq0oAg25VxXM1CWYAuUVWVVgAIAZVyUADiJNEAEAZFxVd1El0lclcNqVUAvlxFd1ENxFcNCArtFt1tDVYNENAAyhJTFXpYtaJZFTVXAFTQAMLVW1VLUnB8DfW4DJ1xWp1xXQ2w0I3uADWiUcUV0g2VXEVxUgAlUpUu1kWU0BXZAdUwDFVkW-XkXgC005VSXA00BA0cV4VAA)

**Comment by ycli0536** [comment]
> Setting **data** for xAxis and yAxis and making them **value** type is not a good idea. Heatmap works with _dataset_ and axes type 'value' in TS - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&lang=ts&code=MYewdgzgLgBAJgQygmBeGBtAUDTAGAGhkJgFY8BdAnfIgRiPKpoxICZHLrdWiBmTsx4kALIO60y4liQBs04UQDsCyQA5VvGAE5NJOiSYStdBmS4z6Hc0Ml0BN4_rGPLMOqT315rxe5W-dhqBJroh7IYWPGaGIgB02toibHjafErkeFl4IrYYZmak8dpqaqSkbGoZfKQesnlm1kUJanyysto5ShnZ9cZmDs0leGxsSrJqsuV43X0sZi5DSlWyqXQi2Vlz0YyMxUrassl8JyUifGoNRD5DrTMbeHx0bKRXMAG3nWrPdNps62pcv0iMEhtoMh5nko3mFynEsmo8LIniJ7DkOm8DIxSPCUmxZEo6FVMlkgfN6IUcY8aiJwaQ0nQjpimlSREo2GyDmSdu5BlTVlNzkdvi9MYsqUo-Ejvl8MpjPGQqa0yqkjjUittMAUblS_rSOdpXsD_Nj4SUJm12VllnRMaCcQY2HxwRy-KLjb9TQZneNUUS3Y9NfkiCkvTknc8SdkjSxrIZtAl1tzMNZCgmqi9Uct2TGeNYmum2lC2nlrIN06ltETqu7Y0RFgmDt10my2KXdmQK07rSLcynrox0y9TKRZpscu33oO4pM1c8ni9ssmMNZQQm_hVWwHNsvrLD14kLi9WovSZOsTBVvCyqtx9lbcZU2Yr3Qm2pOt1a3mrNc8HExlaSgTo-9AOFe6QAeykpfv27guFeIiyEmpDIm2IHuAqV6kBc9IiNhkbnj4V63rUIjfLeWQPnWJqXn-Ry0jSpgwSu9DBMRhJITMFSbFR37uGExFqGwhz0mkp68bBoa0XEExkXkDhyPEt5CdWUYSRgDjPvEbJ4NhsiVO-hzqQ41hHHENTIucnSvn2Gn8Nc8RjBy-lpFWeB1PJ9YOf-UrJISRSeVIl6OThiFpKsNSMoFRHxFKHiZLUBHGA4ARmckOQjO59j0ukgVsfE9LdqscrJUQAnxN8eClJU4zIgSfCBReUzwu0FSHMSjXPjifBhTlul_Ic2iNaZOLIgcRKjpcpW8tcOJ6lVgp3DMU0sJp8GyHEvzuRUHJVSVq30JhG3JCkgGPElB3uERG2rCqExCYkj2NalG1KMk5yTJUFSSsumlsRtQnCe07TPLSiSNQJAOjpUlopMtxkhnIAP6a0F08C4chqDOqJBi4z5Y-U3TuRM6kuKZWNSkB_woYi955C4YFY6YfzCUSBh08YLjwVj7mTOyTKcx2Ey4iiSLMfB1xM-c21A_TyiS-ZiLka-DWCzAbFY5Kpg9eCuNldcCZEqq6zi_QciNgYy542YQH_mk3S1ezlFy-41i29ZJsVLTztq_Yyh0HEmQeDU_ybGhLB4y47LwqQrSrIcLseMobCB3hVS9onPjR2kgLnLMicBJK_4pMSqGPeDvvBEXzprGRHjl0NvthEXiE9UhHJg09atSS3GThzwCokNHqKh_btkKjbAedCPvz8yh-J5AqbsB3hoyEqk6Tj_Z7wBwYkqZThb2jIvXnvH-Vb2BnxgKgqtvvqOBL_L86xIifl7-_C420zaBqNywt8f0QhMIC51JRCRWgPEEycY6PEBJvN-zcU5K2pDreOuVr5m2UHwOIQFVgag6hg9wNt4ggLZBMP4VUShb1dsoHEkp2po0wBPFKr0CTtBeNBZIvw37rGUEoHBYwSh81Uu5Hht8CayVjoTZ474eFZwTM5PCY8eGF0bDUEYp1zocggUw1iII_wjENBkH-nceFhERJtcoDxDjnCsdQqSFibI_1sj4IeDouINwbnkHwxDzJIjaOQfEBCWA-Ddtg2OgJuhEmXD4FK2DHgjFKGRUo-0eA-CjinDonEepOi8cYG40DLJuiQoSYJaSBzvCQW9ICkwYny3eNg5I7REhjFjqkzAPgq6OWWO-fE7JvH63eN1RIo5Ei3XaRgHxQ9XoXDqUQ5QWNRidCrG3MpHSfzvEbGkHqgTnTlwGTNdWAcdkZERGAiZPiXBCRwYkFJnQ9ldxCYdEE8QuIbCPqpA5jIQTuLqqqL5AQygznINxRIe1aQ6MmXo9WG1hJnBQm6L55jjoULaEkcF4IDkOI2hURFxgAjTJwR0GYnz8X0FoTJZ4lQhH80NMuAIbsCoWhpmNWyAQ4k4K4YaVIPL9JstPkXUYPUqbJDyB8LB14ZhATSCCyY6lUoSpqJKDIslGEYELsoV5ExiqumWJ0IMgKKVw26OcMK-yyU6GUK9UwIC46MmJmKzB7wCZukBP8YkHMWABFMPowO7IShJBqj1dBXqNnXPZBZHI_LDmAhnIKbMVV7jHwtbwmFM5ZjOjdBcCZ3qFSlBkmFPlnD3WOqumVAxtNhWElLa-Mqu9GQnEWlKLiNbghVk5VKKRTpf5_x4N6sIfx4QjhyG0OuHJoQWqkoO3S5ARSd0eTwYIQ9-FSlyZ4hdmBgg2zoTXQ4Bk8jBEZeZIkocciQuCBy18edyj903QKlO70yK3IeRXFgoJoH11smxaBH0TiBm9qI4wVcJUw0NLHKqB6oHvCUsrPSkHLXvBxeNDo5BlxbqHljUoCcgMUhBCvQ0UwO7nrDY5FC-k6jEZjfw9yUE_jwdTe-Sl748IjDQ88nQU8oT0Z8GkHB1Tkhe3owEQ0m0nQpLdAcR6E633QpE0kZ4MxgIyf4mVWFVZyJFBfUGQ9JBDjmWSXkMIhLiXSvgcYMIvjZJIUsvpH6qsWBhDdkgsibQnRPAmWEFKxy8JFEiSkSKQYwhRz_AGICEFPGGaFumaqh5GQbH0oFipttQbkG5VWZizcP5IlfESSYuEWaRfVoUso3RY5PEK83YoNQWk_TntJngFnl04OWn8ERPsHO4fVn-MokxbntG_r2zAFnVyOXinHcEeSOtUcDrOZ0yQqjBsGxgCzLhOh8cQqMekwDbIWYVLxnKTTemULKIV75OgcTicoaYMOp3hP8JvWUNI_UgbLgs22iREFHhOTBpCizA6sa3JyHSBkdVCtToTNKLWzELxuIaPoaB-FARwImReN2f4XgTDvJ66IJBGbmWFI9ls5r5iiGuNRpycOhYbQuP6HKKO5DXBxd2ynU5Lz8NpGFZHtkLxsQUUjlnzcA5CSOHZ-nTqxfzOdTJZ09qx7Y61PoVcKcigQf6PoBwkw4icnGBvHo7Wcf0FW-jjwt78j6D2-E1dovuf6B47CkOLPa06EWYGM4RORmO7bQmB4kn12QovJ6HQ657XVfd0kFnUl2YNBiNA9IiJ3Uo4KAbLXiFJRunwrpRC0eQyM4EaJHMpXs8wDAtpSoOXATYTOMuH1MB4IpzekjuBL7DRF8wkLzkhjUTMYqNz581whfZtQycNVNfUr15NdSDodRodmHyjJFC2zU9F4EuzpEDsG1vXjkXi8d9DQpEQlUTu_uCi-JlTV4V-JRzb7dgoxI7MMjV4KBr7BOZ1F2tWK-bfVz-FJESj8DFx-7G7aICJQJwtIaC9WWo2oZUJCb0-oBIve9Ad2Q6BI4CtUbQBI2-72isw-FwJwPa2-_2CQOYyI6waIWe_QjQumEOwCC43OcYye6Izek20QqYs0MkU-VoqIDQ-Y1wyuzwMqBIEW_QZY04Zy50UqPBp8o4RKEaw4puzwHYKEfq5A0-86S2ih78ZA1OSE5wvw1W5c9B9SMhvw5Q-qIg6hQYmha4n8JqUSChe4_eCQ6QWQown-IhTqzUyIJYHhkuHQCQUwucsc6kmhmhb0MksGPh8wqYKU3uSQDEqQICrhUhcELym0OQ8BhILBWoqYeaiyToGwdBKRZ27aqwbIOsOu2QDhSBMBn8QkDePa4evhRIZUOIsceoEavwj0_uqYA6sK6Uyo4w5cIR-Yum1OBm_QCk7BlQt49s6hDQmkThtI7IVQiSYWBgVhJkjAP-WaHgpQV6fWCx28zQqMowSSSQJwscRxtejAD6x4qITwL6KOgwnAiY5Q7Rok8cChYErxFhucKk7cYM1xHwu89wHQvkwqAs8wGutxCQvMpSSQ5cJ2kxgycI4wm8jaVY88PU1xF49Iqc4IBwwCR-3OmkWk8IZE0oeWiJ3xGywsYKToQEoyxO0QmkKUWqkwMwuq74r8KJqRUuhoPWukx4b0JQuJea2Cbcr4WQ7mR4_umknSG0hwSI4IxwPEuJgKCY7chGWUoeuJbaAcToBIoMc6iQkB-QmkA6U8eyC4vw_wbI1eJkumKcM6VUoMwh8wGMSxdQWO0YDQeM2x_4Rw80rMp43OZMjAkpboRkGwAGIRDM9Y6YRwGUYUkYgGnpp8bI6RqQ_mcM941eiw9YOIHCZEqEvYWQ4ZFSFhWu4IqQdcFE20_p9S1ZVYUwzSIMi48ZUGiEgcNQqM4UPElZCGtIdsboz8pxgSTZ7ghg8SiEDwWOXZkuMhk04IQk9IaZUU_QeMpkmSxY_6g5U5fsbOM4mY8RPUaZChkc0Ch-NSyZ6pW57G3QWul-QiZenZh5nSu8bkJuypVRh5gK2CRk6miITEHOh5wQQK7QkUo4GQSJh5yKWumUfk-EBol5iMIITO24WObYWAFAAA3FgFgCAAAA5QAACW4AaAMAAA3jQFACACAAADbkXEUABcNFAAvhIAAB4ACC3FZFEA7FtFuAuAUAAAnsRQAKbsUADkAAbggIxQAK5SWyU0BcU0DiX8WCXCU0BiWSUyUwAKVKWqXqW4CaW4DyWCXKVKUACyCAbFNF-lMAAAtmRWAOxYQC5a5QgNxexezBILgMAEpcAMpYxQgAAEaMVGVQAABOqlQVMAcVUlSl5FrlRlAAZkpRAFJUlR5QAEoIBgAADmRlIlolwVTFIAcV7F2AlVlVslAAxI8ShrJUlY1U1XhBkJFSIO1S5Z1W9AgHAHAHQP1Q1aJc1VFXANoFJdoONRNcZU1VJXgJlXwJlWoAtRNc1ZlbtZlZFZlVtQ1TtVJStZ0EdZ1ZlYgFJUhBdZNU1ZlYhHAOcHdbgM1XAPvGMK9UtQgJkPiOZQ1RQC5ZZaJWRVAFJa5QAOpkVwBQAAAW7FLw-V4NrlAAElJWRSVXDVAOxeoklUpZjZ5cZQgMpfRUdR5fJVJXFblexdlYxblUlTVWRVJWADjcZXDUzQAF7gDICMVHUxWZVs2yXAAs3g1xVHXEXDVwAeUlV1X6BZBEDy2UAaUSCIDIC5Vs3UUwAQAgDKVxUi3sVq0oAg25VxXM1CWYAuUVWVVgAIAZVyUADiJNEAEAZFxVd1El0lclcNqVUAvlxFd1ENxFcNCArtFt1tDVYNENAAyhJTFXpYtaJZFTVXAFTQAMLVW1VLUnB8DfW4DJ1xWp1xXQ2w0I3uADWiUcUV0g2VXEVxUgAlUpUu1kWU0BXZAdUwDFVkW-XkXgC005VSXA00BA0cV4VAA) 📌 please close issue if problem solved.

Thanks for your quick reply and demo! I From your demo I realized that I used minimal bundle in my code and didn't include Dataset related modules. Thank you so much! Now it works as my expectation with axis type as category. So using category is correct in my case.
