### ISSUE TITLE
[Bug] 没人发现官网所有示例的ts代码看不了了吗？一直转圈

### ISSUE THREAD

**Issue by gedaaxiba** [apache/echarts#20305]
### Version

最新

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=area-stack-gradient&lang=ts

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/0febb029-618d-4280-81a7-11d6546e8375)

### Current Behavior

打开官网示例ts代码一直转圈 无法查看

### Expected Behavior

![image](https://github.com/user-attachments/assets/9f0bb1f1-6027-4848-94c5-5f15fd605702)

### Environment

```markdown
Chrome 
版本 128.0.6613.84（正式版本） （64 位）
```

**Comment by plainheart** [comment]
已修复 apache/echarts-examples@9dfa5e7abe7d25f1a97cae88a6a2da189e59849f，刷新重试即可。

**Comment by gedaaxiba** [comment]
**已经一周多了了 我以为会有人注意到这个问题**

**Comment by gedaaxiba** [comment]
> 已修复 [apache/echarts-examples@9dfa5e7](https://github.com/apache/echarts-examples/commit/9dfa5e7abe7d25f1a97cae88a6a2da189e59849f)，刷新重试即可。

已经一周多了了 我以为会有人注意到这个问题

**Comment by gedaaxiba** [comment]
> 已修复 [apache/echarts-examples@9dfa5e7](https://github.com/apache/echarts-examples/commit/9dfa5e7abe7d25f1a97cae88a6a2da189e59849f)，刷新重试即可。

谢谢 已经一周多了了 我以为会有人注意到这个问题
