### ISSUE TITLE
[Bug] VisualMap Feature alternates the Line Marker color even when it is turned off

### ISSUE THREAD

**Issue by hzmacso** [apache/echarts#20327]
### Version

echarts-for-react": "^3.0.2"

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/visualmap-yl4h4r

### Steps to Reproduce

To replicate the issue, here is a boilerplate code for a chart with a visual map, with a toggle button to enable or disable the visual map.  https://codesandbox.io/p/sandbox/visualmap-yl4h4r

### Current Behavior

when I click the "Hide Visual Map" button, the marker colors remain as per the visual map's threshold colors. What I want is for the markers to revert to the default line color when the visual map is turned off. Currently, the only way to achieve this is setting  `enableVisualMap: false ` in the config, i.e. completely removing the visual map-related code.
Or could there be something I missed regarding the toggle state?  
![image](https://github.com/user-attachments/assets/e3b6bdf6-af6f-4b15-be9f-4cad4a1f6b86)

### Expected Behavior

What I want is for the markers to revert to the default line color when the visual map is turned off. 
![image](https://github.com/user-attachments/assets/b3d3d769-3552-4255-a889-c872ffe6a7d2)
### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: React
```

**Comment by MatthiasMert** [comment]
Looks to me like your Button is only disabling the `areaStyle`. If you want to remove the visualMap you should use [setOption](https://echarts.apache.org/en/api.html#echartsInstance.setOption) with `{replaceMerge: ['visualMap]}` as option. At least in vanilla echarts. cant speak for your framework

**Comment by hzmacso** [comment]
> Looks to me like your Button is only disabling the `areaStyle`. If you want to remove the visualMap you should use [setOption](https://echarts.apache.org/en/api.html#echartsInstance.setOption) with `{replaceMerge: ['visualMap]}` as option. At least in vanilla echarts. cant speak for your framework.
> 
> As a workaround solution you could also set [seriesIndex](https://echarts.apache.org/en/option.html#visualMap-continuous.seriesIndex) to an invalid value: [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6AG74FjADYTGIIkgclyHHxffjJKGlknDyVae0dYPCojKkJYUVDUUlIhMBE0gEYAVgAGHlgAJgBmUorygBYy8vyADjL8ysK2uoB2RoA2Yut4rIpqOncIaGVQuxJbOwBuFGXEsDkIAFsqYAUwAAoAM0t6SBg9gEpidA3yAGFtRg4wADpVgHlwKGg9pBc8N083jESESyTwAEloAIqBgiABafJ2ax2c4oBywarFYrnBZAA)

Hey Matthias, I played around with `setOption` and it works! Thank you very much

**Comment by hzmacso** [comment]
> Looks to me like your Button is only disabling the `areaStyle`. If you want to remove the visualMap you should use [setOption](https://echarts.apache.org/en/api.html#echartsInstance.setOption) with `{replaceMerge: ['visualMap]}` as option. At least in vanilla echarts. cant speak for your framework.
> 
> As a workaround solution you could also set [seriesIndex](https://echarts.apache.org/en/option.html#visualMap-continuous.seriesIndex) to an invalid value: [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6AG74FjADYTGIIkgclyHHxffjJKGlknDyVae0dYPCojKkJYUVDUUlIhMBE0gEYAVgAGHlgAJgBmUorygBYy8vyADjL8ysK2uoB2RoA2Yut4rIpqOncIaGVQuxJbOwBuFGXEsDkIAFsqYAUwAAoAM0t6SBg9gEpidA3yAGFtRg4wADpVgHlwKGg9pBc8N083jESESyTwAEloAIqBgiABafJ2ax2c4oBywarFYrnBZAA)

Hey Matthias, I played around with `setOption` and it works! Thank you very much
