### ISSUE TITLE
[Bug] I want to change the distance of the axis from, say, 0,0. Change it to (0,80)

### ISSUE THREAD

**Issue by IsXueYi** [apache/echarts#20328]
### Version

5.2.2

### Link to Minimal Reproduction

no

### Steps to Reproduce

This is a question

### Current Behavior

 I want to change the distance of the axis from, say, 0,0. Change it to (0,80)；
 But I looked through the documentation and did not find this feature

### Expected Behavior

I wish I could implement this feature so that I could complete such a design draft
In addition, areaStyle for line supports one color above 80 and another color below 80
![image](https://github.com/user-attachments/assets/2bd607fc-de1a-4cac-b1cb-7cc179b17a76)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I'd like to hear back from the team to determine if I didn't find the configuration or if it's not currently supported

**Comment by acse-hz6215** [comment]
Hi, I'm not sure what you mean by changing the axis, if you mean changing the size of the rectangle formed by the x-axis and y-axis, you can edit it using `grid.width` and `grid.height` https://echarts.apache.org/en/option.html#grid

To set one color above 80 and another color below 80, I suggest using visualMap instead of editing the area style. You can refer to this example: https://echarts.apache.org/examples/en/editor.html?c=area-pieces

**Comment by IsXueYi** [comment]
First of all, thank you very much for your reply
Let me elaborate on my problem：

![image](https://github.com/user-attachments/assets/67ad0b5d-cbd2-4a4c-a994-3c40da28f517)


    1.My goal is to make a graph that shows the temperature,
    And set a critical value: 80°
    2.The effect is shown in the figure.
    3.I want areaStyle to be displayed based on this critical value,
    For example, if my value is 100, 'areaStyle' shows the area 100-80

Do you see what I mean?
My problem is that I can implement the above image with echarts。

**Comment by acse-hz6215** [comment]
Based on my experience, `areaStyle` doesn't allow you to set colors based on defined boundaries (I could be wrong though). If you want to achieve what you described, I suggest using `visualMap`. I have made similar graph like this before 
![image](https://github.com/user-attachments/assets/17a8be71-fc11-4084-b883-dd4ad0cc25d7)

**Comment by MatthiasMert** [comment]
You can use the [stack](https://echarts.apache.org/en/option.html#series-line.stack) property to achieve a similar effect: [Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAugbgFAA2AprAQtGjAIwAMN-AZiAE4wAUAlqvRwDwBMdHBwDUIgJQwA3nhgxQkWBA4BzMJQCySABYA6ZgjBwQAWzaTeMGroCsMAPwwAtFRgAuavjlkKI9MrUYACoYLSg9AyNTc2Dqell4JARdAAcAVwhtNgwOABoYHygscXwAXzwFCgAjciICDjAiSgBBZgMAT10GZmipYjAVcI9BGlL8tgAPXI5JVAA-TDyYAHYaYvxKpWRgAGsiOAARJMpEZF0TBBTJtAWMCYw1_PuqLGcVtZK8L5AUqA5wSgyOQTZoTDgQDxSKDtFJEDwAcmASCIKhY7XhYwS7VB4MhECRxA8UGYaSImLkADdwWkEAQtCkPBggXIYNDYQiFH8wGkQBl4bkEnITA0PABmGgClkwC4TDxUQSSlkNABKhhUcOkgpZoAILEZ8PqKm0UCqBFJ_PhpvN-XhLDVRH5MHhzH28KwWvKclKWEVECIzA4RAhmC1zKlbI1BoaDsVUugCF2CPju35Wrkyn6UCJJKIsZZEHaJiqIAICLA4BjaYK0YAytDCdIdXqncTDBAUggXWAoBi83JTggPDU_fVGh682GWRGEaPK1L09sdknF6n5zBkzs6wYoCj2gjaQRV_OICYQCAhqyc3314Xi6WneXGkepQOPBv9kdkNfO0QEHX2g2Uieiy5IwO6pQ4EAA)

**Comment by helgasoft** [comment]
stack with 2 colors - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygmBeGBtAugbgFAA2AprAQtGjAIwAMN-AZiAE4wAUAlpfTFwDwwATHRy8A1GICUMAN54YMUJFgQOAczCUAskgAWAOmYIwcEAFs20gTX0BWGAH4YAWiowAXNXwKyFMelUNGAAqGB0oAyMTc0sQ6np5eCQEfQAHAFcIXTYMDgAaGF8oLEl8AF88JQoAI3IiAg4wIkoAQWYjAE99BmYYmUKiMDUIz2EaGDKCtgAPAo5pVAA-THyYAHYaEvwqlWRgAGsiOAARZMpEZH0zBFS2GYXljGmMTYLnqiwXdc3SvDwQVJQDjgShyBTTFrTDgQTz9KAdVJETwAcmASCIahYHWREzyiQ6kOhsJgEDRxE8UGY6Wak0SADdoekEAQdKlPBhEgowQoefDESjUhwiMAiAB3aFEZF4nk8wXCogwzCcmWyQpQTwANgAnPotXqCqACCwUcw1LU2DQCpbqAAOa02AAskhxtJVPP6wyR3wNICNzBNRxdyoUWGVFRD0pJRGYQsVHJl3JlfK9yIaTSlwZJe32KOgCAOGbdqmIYHVMEp1MjMogHTM1V9KLA4ElVZ5aaIAGV4eTVYbjTBkZTjBBUghmIMoC7WwoLghPLUIPVGkQw63E7yESn24WVXmDrnszvq9mu0YoBiOijmQQjzyIGYQCARuWqURpyTa_WCI3m7eZ8lPD3Q4TmSd8xyIBAuw6HsZHDHk4NDMocCAA)
![image](https://github.com/user-attachments/assets/d3ad6249-a05f-4b37-9e00-1fa316adbdff)

**Comment by IsXueYi** [comment]
Thank you all for your selfless help in solving my problem.
I will pass on your great spirit
