### ISSUE TITLE
[Bug] echarts.init opt set height 100%, result show 100px not full height

### ISSUE THREAD

**Issue by fewbadboy** [apache/echarts#20323]
### Version

5.5.1

### Link to Minimal Reproduction

https://codepen.io/Ovilia/pen/dyYWXWM

### Steps to Reproduce

```
const props = withDefaults(defineProps<LineChartProps>(), {
  height: () => '100%',
... 
lineChart.value = ECharts.init(lineRef.value, null, {
  height: '100%'
})
...
<template>
  <div ref="lineRef" :style="{ height: props.height }" ></div>
</template>
```

![image](https://github.com/user-attachments/assets/49bb64ac-c467-449a-8a32-dc45b64b939c)

comment `height`, 
![image](https://github.com/user-attachments/assets/e43ff2bf-d5de-4fcd-867b-3305cad877e3)

### Current Behavior

![image](https://github.com/user-attachments/assets/94f8050d-7cac-4505-bd51-80d7b850cac8)

### Expected Behavior

![image](https://github.com/user-attachments/assets/cf3d5a84-0a80-45e9-b8bd-23fb6fcc2c19)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
The [grid](https://echarts.apache.org/option.html#grid) component has default values for [`top`](https://echarts.apache.org/option.html#grid.top), [`bottom`](https://echarts.apache.org/option.html#grid.bottom), [`left`](https://echarts.apache.org/option.html#grid.left) and [`right`](https://echarts.apache.org/option.html#grid.right).

**Comment by SeanErvinson** [comment]
Encountered the same issue when I was using react I had to delay the render or re-render the graph to actually take on the parent size.

**Comment by fewbadboy** [comment]
> The [grid](https://echarts.apache.org/option.html#grid) component has default values for [`top`](https://echarts.apache.org/option.html#grid.top), [`bottom`](https://echarts.apache.org/option.html#grid.bottom), [`left`](https://echarts.apache.org/option.html#grid.left) and [`right`](https://echarts.apache.org/option.html#grid.right).

![image](https://github.com/user-attachments/assets/2cd5e99f-b241-4a12-bb24-baf296d9635d)

**Comment by plainheart** [comment]
You can adjust the grid top/left/bottom/right as needed. For example,

```js
grid: {
  top: 6,
  bottom: 0,
  right: 0,
  left: 0,
  containLabel: true
}
```

**Comment by plainheart** [comment]
> Encountered the same issue when I was using react I had to delay the render or re-render the graph to actually take on the parent size.

@SeanErvinson You must ensure the container has real width and height before rendering the chart. If you try to render the chart when the container is not visible, the chart may fail to get the size. There should be a warning like _Can't get DOM width or height_ in the development environment.
