### ISSUE TITLE
[Bug] pie chart 百分比很小时，无法显示扇区

### ISSUE THREAD

**Issue by hongdeyuan** [apache/echarts#20333]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQRjUC29ANMegGbCksBDMMzqwAFABMhAgJQIAfFxLoABgB4ARvIAkSKWAEA6aAJbUAvoV36jIWgGNq0MOYCkagPRaVndOd-w2NQ00BKEqMqYBLD0AKyuHEpB3GAMjs609MT-xADOtBDUuYQA2koRyrAmZgwAgvaOubmwAGKkwGwBkQCedgwghYmVsKQCEhAArsWwJfQALAAMCewxAOxL9AC6XSR2pOlgAAqk1PYQuVDQhABsO-gCAG7AEBIAMgIa1NgA8g-02AJotwBNh8ndAh8vuElMpcgALYAAd0IwNB1HB6BAwAukBgaScIiywxyw1YIDhAgu0wqwwBn2w0OGsIRyLIE3RMMqvGcAGUIAAvaiERYYkjcsAAdWolDhqRiGhwEiJTPMnJJlTpX1eEGgQqITNg8KRKJB-TV4JspU56CQsAeIPZhAAjAs5qt3QAOFbVPX0HnUAT7OGwACi0AoOuo9Fg6uGtvt2EdsCdTu9pl9ABEICd7GBo7HKvGHXrU1V0wwQ4IINh86Ki4mS2majEAKrQS6wWoSXK163IO3F51N30ANRe1GAne7-c5myUqvQc_MAG4gA

### Steps to Reproduce

一个很大的数据：1047778， 4个很小的数据：1；查看是否扇区都能显示

### Current Behavior

存在多项数据时，有一个数据特别大时；其他很小数据的扇区看不到占比情况；例如： 

```
       { value: 1047778, name: 'Search Engine' },
        { value: 1, name: 'Direct' },
        { value: 1, name: 'Email' },
        { value: 1, name: 'Union Ads' },
        { value: 1, name: 'Video Ads' }
```

### Expected Behavior

期望在数据占比相差很大时，也能有一个最小扇区占比显示；

### Environment

```markdown
- OS:macos 14
- Browser: chrome 128.0.6613.120
- Framework:
```

### Any additional comments?

预期如下：
![image](https://github.com/user-attachments/assets/e550178b-2dfe-4113-965e-b57236431722)

**Comment by plainheart** [comment]
考虑设置一下 [`minAngle`](https://echarts.apache.org/option.html#series-pie.minAngle)

**Comment by hongdeyuan** [comment]
> 考虑设置一下 [`minAngle`](https://echarts.apache.org/option.html#series-pie.minAngle)

非常感谢；这个 API 可以解决我的问题；
