### ISSUE TITLE
[Bug] Custom Series renderItem's api.value() always returns type number

### ISSUE THREAD

**Issue by DerekNMartin** [apache/echarts#20338]
### Version

5.5.1

### Link to Minimal Reproduction

https://codepen.io/derekmartian/pen/vYqPbJN

### Steps to Reproduce

Chart Option:
```
{
  tooltip: {},
  xAxis: {},
  yAxis: {},
  series: [
    {
      type: 'scatter',
      name: 'ECR',
      data: data,
      dimensions: dimensions,
      encode: {
        x: 2,
        y: 1
      }
    },
    {
      type: 'custom',
      name: 'error',
      data: data,
      renderItem: renderItem,
      dimensions: dimensions,
      encode: {
        x: [1, 2, 3],
      },
    }
  ]
}
```

### Current Behavior

Since labels and `api.style()` are deprecated for custom series types, the only way I can see to add a label is to include a text type within the `renderItem` group.
However, when trying to access `api.value(0)`, it returns a number, which is `NaN`, because it's supposed to be a string.

Dimensions includes a defined ordinal type

```
const dimensions = [{name: 'name', type: 'ordinal'}, 'expert rank', 'rank avg', 'rank std'];
```

The data is of the format: `['Josh Allen', 1, '1.30', '0.64', 4]`

When using `api.value(0)` within a custom series type, it returns `NaN`

![image](https://github.com/user-attachments/assets/80e2397b-2a0a-41aa-bfc2-5aa83b46a79b)

### Expected Behavior

`api.value(0)` should return the correct value if the dimension's type is specified

### Environment

```markdown
- OS: macOS Monterey
- Browser: Version 127.0.6533.120
- Framework: Vue@3
```

### Any additional comments?

I tried this on version `5.1.2`, which is the version prior to `5.2` and `api.value(0)` returns the correct value

**Comment by Ovilia** [comment]
Can you provide a full demo?

**Comment by DerekNMartin** [comment]
> Can you provide a full demo?

I provided a codepen link under Link to Minimal Reproduction - is that not enough?

**Comment by helgasoft** [comment]
yes, looks like a bug - [dimensions](https://echarts.apache.org/en/option.html#series-custom.dimensions) cannot define data type _string_ with 'ordinal'.
[Workaround](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgSwLYFNIPBGBeGBtAWACgYYBvKATwAcUAuGAchACdEwBDAG0YF8AaJigAetFrBYcwAa0aDGkmTA4A3AOZymi6TGhxNYAK5cuxALoBuYqEiw4HKBxz5ipPIwBSICAAsYAQRM0TQBGQRCAOgBmAAZBGIiANgAWQSizfld8T240GAAJQ3EITQAmQVKkuJgEgE5ymGSMrPcAGQ4kDhYYDw5gaQhwTSjwiNqAdlGYgA5BJsyiS2JiADNDMGAoDDAYFjQ4FBYASSgUJAAKai6OiEEOagQASnIsm2gYNRYQQ2pnMizSFRaAxGJ9vtQ5ACYMAfAguHA9mAGHgzFleFYSDAuChYAAjDgQFAAEWQRzgwmcIQxpGxsBAUB8hxJSDJFNwIRgAFoYPjCczWdSsTiYGhQAdnFdJEgIBFRSADoK3iBsREuCA1Od7ggIipuIYUOcYo9-FqdXqDSFjabdVx9ecoo9HoKAPTOzioZz2Rx4a3m86WzkhMx4GJLTFvWAoYDdXC-20GuUHCLCENmJ2vTCwVRqZxxu2JlDJvBB9PhzO6KBwXMPM3x84FoulNOK8tIBBgABq5tz6i5FarzpgpRbthgnWEXfjPZzAGp-zBB8OsrSeQSUJP9c4oyxBSvJR1nCjBfukHhecTSeSzM5zxuUMfrqf6YyWPyr85x3fd8LYWofAAFEB21gWMa1AVg4EuR9S1IE88GfJlL2Ea9cDbTtzW_WA1QAd0A4Dq21cC2CgqUYKFWAfG4FYAHUEDgBlKSXTFdW6aBKGxP4oWgL5pHoZQaxUBAIEMbhzkYUA1RYRhjTRQUwR-CIYThBE0AiahDF8c4oX-TFSEBGg-MYLh2xQSFdL0qBFAgBAtnAZFGF8e5TOaczSEc4Exw4XiAGVKNoLTXL038AKAsAoDPNc32QvtKK4Gi6IZBY9OSmBgrwsL4IZRCWSvJKUtINLQvC88ouvOdYvi-ifDy_LCuAzKX1KqFSBkwK2OxBh2pQKEBG05qYCBQzjLAUyaosqybO2ez3Ocsa3L8vjOh8haAvygqED_dLisipCXLW1KNpC-qENfXa5r0nCtoivkzv6mkQFwoqGuy1lUUC1r8q6zqqGxHqxp0_LBpBYbRv6yypGs2ykWyGbGD2lKZoYJaUF8pzVrWy6npK3aYqo2iqvO-7HuOrLTpy5DCaxB6rux8mytSvGEuqu6qeJjKTqa97zq-it2O68zeChV0YDvGAhOULhsI4SgsEGmAjCQXFDkEFAVDyBlvj_AbGXgZA0Gs8ABoMsWsGYNh224RgYHObj2zUR5iGFvSyCNjzGFOYQoE0YQGDqjLQxgOdEkEShfcOq6gz7YPHcHBGfr4l2PagBh3RQGBeqIJ3SEFzEyLWDYoc85a0fPMIYBtfUy_PBoK5QUpngBvSWN0Ba_nRLiFoiSgOVwUvBXmpzkx78vzSpDvB8oUobzXJjkpm5Mp9wWvZ70vYoCKHYZsFHPSDXjePi-H4MRzkBqEL3BG6gEBlS2agGDIDPSGEfxhCE-_H5gSgX7f8gP8JFgEAoAgMiPqgUgZMAgMABwpwpLnVTiCAAogAYQAEpmXyl6DgDBMHnQLPfGAPshyCE_gwMuNkzgADkOj0BiOnc6XAOBKy4HQMgvgHp0EsvqQQKxWCdCgDAkEZBcS8E0NQbwk07LuBCDEGIABSTQjBpFyLhjvPSH9SCN2SuA8SGkr5IHQSleBQgWBfFgf1TB2CHAcHOoiA4xxThIAYLYw4JwzjnUQKgdAmBsF6y8ZAXBGx5QJ32oQ4sFQ0jXhSuovS5CkDeXjvfCSrA6AKBQPoVR2cshvXREAA) with labels.
![image](https://github.com/user-attachments/assets/155bf70a-ae92-45e5-b6c5-659063b01fc7)

**Comment by DerekNMartin** [comment]
Thanks, I'll go with that 🙏
