### ISSUE TITLE
[Bug] Cannot read properties of null (reading 'offsetWidth') when using notMerge

### ISSUE THREAD

**Issue by Curtis-Lockley** [apache/echarts#20335]
### Version

5.5.1

### Link to Minimal Reproduction

https://jsfiddle.net/az4p58gs/

### Steps to Reproduce

All you need to do once opening to reproduce the bug is to scroll around and zoom in/out until the crash occurs.

### Current Behavior

Currently, there is a chance that when scrolling for a crash to occur as shown below.
![echarts-null-value](https://github.com/user-attachments/assets/e544cb53-dbb7-4bd9-868b-9aeb0f762cc1)

Below is the error message
```
echarts.min.js:45 Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
    at t.getSize (echarts.min.js:45:781248)
    at e._updatePosition (echarts.min.js:45:792803)
    at e.<anonymous> (echarts.min.js:45:790188)
    at e._showOrMove (echarts.min.js:45:788953)
    at e._showAxisTooltip (echarts.min.js:45:790116)
    at e._tryShow (echarts.min.js:45:788458)
    at e.manuallyShowTip (echarts.min.js:45:787122)
    at echarts.min.js:45:786112
```

### Expected Behavior

The intended behaviour is:

1. rebuild options from scratch using new data
2. remember the previous scroll position
3. not crash when scrolling/zooming

In my real app, I achieve the first 2 points by taking the values from **chart.getOption** and manually merging them into the new object.

### Any additional comments?

In my real app, I've seen the issue even if the chart is rebuilt every 5 seconds instead of 100ms. As it seems to happen whenever **chart.setOption**, the interval was lowered to make it quicker to reproduce.

Although options does not change. In the real app, options could be built from the same data, but filtered to exclude certain data points.

**Comment by ktx-abhay** [comment]
Facing same issue. Any update on this?

**Comment by jesse-garrison-panther** [comment]
Hello all, I just ran into this issue, and I can see the fix in the src directory here in Github, but it's not in the built version of the code as far as I can tell.

**Comment by plainheart** [comment]
@jesse-garrison-panther Hi, we are preparing the release of v5.5.2 and it will be finished within two weeks at most.

**Comment by Mangor1no** [comment]
Hi @plainheart, I saw that the new version v5.6.0 has been released, but the fix had not been included in it. Is there any plan to release it? Thanks
