### ISSUE TITLE
[Bug] The data points on the line chart become misaligned after the resize() function is called.

### ISSUE THREAD

**Issue by blukio** [apache/echarts#20349]
### Version

5.5.1

### Link to Minimal Reproduction

See the code below

### Steps to Reproduce

The following is the Vue 3 code where the error occurs.
```js
<template>
  <div ref="charts" style="width: 50%; height: 50%" />
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import * as echarts from 'echarts'

const charts = ref()
const map = ref()

onMounted(() => {
  map.value = echarts.init(charts.value)
  setInterval(() => {
    const arr = []
    for (let i = 0; i < 100; i++) {
      arr.push(parseInt(Math.random() * 100))
    }
    map.value.setOption({
      xAxis: {
        type: 'category'
      },
      yAxis: {
        type: 'value'
      },
      series: [
        {
          data: arr,
          type: 'line'
        }
      ]
    })
  }, 500)

  window.addEventListener('resize', () => {
    map.value.resize()
  })
})
</script>
```

### Current Behavior

After the browser renders the page, resizing the browser window will trigger the resize() event. After the resize() event is triggered, the data points are not correctly destroyed.
![before](https://github.com/user-attachments/assets/0d458917-edc7-4c80-be48-df8c1c769a50)
![after](https://github.com/user-attachments/assets/a90969f1-acda-4a9a-b583-64c4b06e1c13)

### Expected Behavior

The data points should be correctly destroyed and refreshed.

### Environment

```markdown
- OS:windows10
- Browser:chrome(128.0.6613.138)
- Framework:vue@3
```

### Any additional comments?

I encountered this issue while writing code to render charts based on dynamic data: when I set the resize() property, changing the viewport size causes data points to become misaligned.

**Comment by helgasoft** [comment]
cannot reproduce in straight Javascript - [Demo](https://echarts.apache.org/examples/en/editor.html?code=G4QwTgBOkLwQ2gXQNwCgD2AHALgS3QHYRwDeqEEAHgIKW4DOAXBGRRdgJ6YCmzA5AGMQ2bgHN0YDn3IQAvgBoZHWg2as2nHv1AAbAK7dpFBTPrcwubkwQyK6thAAmwkM2iKH7Lrwh8duAkNbORlEVFk0AHdcR2IIAGZEtDNsAEkCETBdAApsgEpiAD4WGWg4pDQKADMJCGydbmwIXDiABmRmiAAeCABGVvbmgGohgvsoMDAAOkw9egALbMxwM3TsbIBZYXmpsBACR3QAW3yIACo-gby8ypCKI44AYXnwbCmUgHkcfAJskggzBYrGonC43JM5HIbjJorE4LCYDBEvEIAB-CAAFixEGYyNuD2er12VlwAC9uH9Ydh5sxYbJoQoIABWK7IIA)

**Comment by plainheart** [comment]
Is there any error in the console? Try to use `shallowRef` and see if it helps.

**Comment by blukio** [comment]
> Is there any error in the console? Try to use `shallowRef` and see if it helps.
Thank you, your method is feasible.

**Comment by blukio** [comment]
> cannot reproduce in straight Javascript - [Demo](https://echarts.apache.org/examples/en/editor.html?code=G4QwTgBOkLwQ2gXQNwCgD2AHALgS3QHYRwDeqEEAHgIKW4DOAXBGRRdgJ6YCmzA5AGMQ2bgHN0YDn3IQAvgBoZHWg2as2nHv1AAbAK7dpFBTPrcwubkwQyK6thAAmwkM2iKH7Lrwh8duAkNbORlEVFk0AHdcR2IIAGZEtDNsAEkCETBdAApsgEpiAD4WGWg4pDQKADMJCGydbmwIXDiABmRmiAAeCABGVvbmgGohgvsoMDAAOkw9egALbMxwM3TsbIBZYXmpsBACR3QAW3yIACo-gby8ypCKI44AYXnwbCmUgHkcfAJskggzBYrGonC43JM5HIbjJorE4LCYDBEvEIAB-CAAFixEGYyNuD2er12VlwAC9uH9Ydh5sxYbJoQoIABWK7IIA)

Thank you, you are correct. It seems I had a misunderstanding while using Vue.
