### ISSUE TITLE
[Bug] series.encode maps to incorrect values when key is missing in first datapoint

### ISSUE THREAD

**Issue by jamesp-v** [apache/echarts#20340]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWzQCGAtlsQEQCCGEtzANFRVtADGwACZNK1agE8WtDlz7oAvr0mwwUkOOYAjWjmZ8VfVGrqMWrAGZ5BXVZIHCxxU2tgzYzWjYh3DasZqGlosegZGDuhu1ObaAKIArjigWDyKsE6i4jGSnsxYyakBkkGSIdrhJcrkALoOAB6sDRBEEhQVLHZgWADmwDhSJWVSza2ufJ1eAG60ADaJaeRlYMDAc5AgE9RgeL29uLItGMMOIrRgclhgxGTUuegYwMmC4nfuD3lY-iwAjACcAFYAAzpdwUOScYgANgATFF3D5bLRiABmAAsCLUAHpsZkiqFYAAOLGSXH4lKExLQMRWCDQLAiUnKZntcFSb44P7_aGg1noSEo2DQkkZahIvxC1H_fkU1LEX7A1llNSfaSc7kAdj5Yoh8mIRKVuoFvjsxEB8ONcsJv1huqUGVqRjqKCUQA

### Steps to Reproduce

Use chart option:
```javascript
option = {
  series: [
    {
      name: "Asia",
      encode: {
        y: "asia"
      },
      type: "bar"
    },
    {
      name: "Africa",
      encode: {
        y: "africa"
      },
      type: "bar"
    },
    {
      name: "Europe",
      encode: {
        y: "europe"
      },
      type: "bar"
    }
  ],
  xAxis: {
    type: "category"
  },
  yAxis: {
    type: "value"
  },
  tooltip: {
    trigger: "axis"
  },
  dataset: [
    {
      source: [
        {
          year: "1950",
          asia: 62,
          africa: 34,
          // europe: 8,
          // europe: undefined,
        },
        {
          year: "1960",
          asia: 68,
          africa: 39,
          europe: 10,
        },
        {
          year: "1970",
          asia: 80,
          africa: 52,
          europe: 12
        }
      ]
    }
  ]
}
```

### Current Behavior

Given this source dataset where one of the keys is missing on the first datapoint:
```javascript
[
  {
    year: "1950",
    asia: 62,
    africa: 34,
    // europe: 8,
    // europe: undefined,
  },
  {
    year: "1960",
    asia: 68,
    africa: 39,
    europe: 10,
  },
  {
    year: "1970",
    asia: 80,
    africa: 52,
    europe: 12
  }
]
```
The "Europe" series will incorrectly use the values of the "Asia" series.

### Expected Behavior

The "Europe" series should display as if it were undefined ("-") for year 1950, and should display its correct values (10 and 12) for 1960 and 1970 respectively.

### Environment

```markdown
- OS: macOS Sonoma
- Browser: Chrome 128.0.6613.121
- Framework: N/A
```

**Comment by helgasoft** [comment]
encode needs _dimensions_ to work correctly. Please see [official example](https://echarts.apache.org/examples/en/editor.html?c=dataset-simple1) for a simpler way of using dataset.
📌 please close issue if problem solved.
