### ISSUE TITLE
[Feature] valueFormatter 回调函数的参数增加 seriesIndex

### ISSUE THREAD

**Issue by kkkisme** [apache/echarts#20358]
### What problem does this feature solve?

之前有类似的feature
#18997
但是dataIndex似乎太鸡肋了，同一series的数据展示的格式大概率是相同的，用不到dataIndex。

而用到seriesIndex的场景会比较多，例如：
![image](https://github.com/user-attachments/assets/3594cbf7-fb5d-43f9-8d7e-83dc586bd67f)
这里的需求是区分不同series：**金额**、**占比**需要展示成**数字**或**百分比**

![image](https://github.com/user-attachments/assets/ad102e48-8261-44c4-a503-f15fcff722fe)

### What does the proposed API look like?

``` ts
valueFormatter: (value: string | number, dataIndex: number, params: SeriesModel) => string
```

**Comment by plainheart** [comment]
直接设置在单个 series ？感觉也不麻烦。
