### ISSUE TITLE
[Bug] Funnel chart with custom labelLayout leads to incorrect label position after resize

### ISSUE THREAD

**Issue by KaguraDun** [apache/echarts#20366]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=funnel&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBiArtNDlpUQL4A0RYwwWkIBVMQwAnCAHNxOEVQhgcAW0qdhAM2AiFAQzDyZsSki2tYAHgBGIgPQA-JOZOCAxqwCkLdBy48s54KUEidFUcHVoRfEJhdAATHS0ANQgcAHdBWAitGIB5aCwATwJVLSwAZxxYL2iMnFLuCMEq6NKtADccAEFSgEltKUagyrYVWFwpaBjA4TiwLQIAbUoAZQALYBTlAwBhLAgnAGtNyiTSuUoAXWGicrFahcGhaOgtBUiaekZmEeEwfJA31QfJjKQboXCqCgGACMAAZ3N9iNwBLAAGwwhHoPy6YAKAhojGwFIQGJgFZUAAccJB1QUEGgBHRoNg2gCsFhjJpdKWEAAXm8qQSWdy-VR2fCmaUNJDKFpSk4cBM6eJqdFxFpkQAmAlYLTmJhTaqwUprNKiWg4AnoEDAU6QGBUYC0MCnGI4DzRJrCHV6rAAGTpkUe1Vw0HEpIIsMtowDS1-uANhsJxPDbKj6F-_yokt2MXd1VYTM9xDkilj-XjUUNfhErpEW14GioAGJVK2VdVq7WAOrJslswsExQgFayiClBPRb36yuJ9TQMDCyIamFMzwDplTv1afKOyEAChAWhEL1KAEoEDYZ4anDA6rAxwBRdpwRCH48KUoAOhmWm6EzIsCuLAGoIPAiAwgA3KuxaqLAe6Ps-55BomNRgOEcBvieUEoUMOERGhIhwMhiasphH6fpuABKOBOGAn6kLAAC0sBkV-ES0Z-RIkisabECUEj0gYYjiCsYDtoarDYR6BI_vciZILArQlOaBAAKzsLAzyvFQJxnJUUYKUpWAqWy6KaS8bx_gAjrQEAiPklD6dBhnKZE7IaVpbzZDW0iOUW6CXMIBYBSgklAA

### Steps to Reproduce

1. Open chart by link
2. Resize editor window

### Current Behavior

Central label goes off screen

### Expected Behavior

Central label keep position

### Environment

```markdown
- OS: Windows 11
- Browser: chrome 128.0.6613.138
- Framework:
```

### Any additional comments?

I try to distribute labels with even pattern. If the x, y properties are set in the return of the labelLayout function, the position after resizing will be incorrect.

**Comment by sz-p** [comment]
It doesn't look like a bug

```js
labelLayout: (params) => {
    const isEven = params.dataIndex % 2 === 0;
    if (isEven) {
      return params;
    }
    return {
      // params.labelRect.x will changed in every callback
      x: params.labelRect.x - params.rect.width,
      align: 'right',
    };
 }
```

try

```js
labelLayout: (params) => {
    const isEven = params.dataIndex % 2 === 0;
    if (isEven) {
      return params;
    }
    return {
      x: params.rect.x - params.rect.width,
      align: 'right',
    };
 }
```

**Comment by KaguraDun** [comment]
Oh my bad. Thanks for help!
