### ISSUE TITLE
[Bug] geo.projection setting are not taking effect

### ISSUE THREAD

**Issue by aaa930811** [apache/echarts#20360]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/yyksql?file=%2Findex.js

### Steps to Reproduce

```
<template>
    <div class="geoMap"></div>
</template>

<script>
    import * as echarts from 'echarts'
    import {
        fetchChinaMapData
    } from '@/api/getLocalChinaMap'
    import {
        getOrganizationConfig
    } from '@/api/data'

    export default {
        name: 'GeoMap',
        data() {
            return {
                geoData: []
            }
        },
        methods: {
            setData() {
                getOrganizationConfig().then(res => {
                    console.log(res)
                    const geoData = this.convertGeoData(res.result)
                    // console.log('geoData', geoData)
                    this.geoData = geoData
                    this.setChart()
                })
            },
            setChart() {
                let myChart = this.$echarts(this.$el);
                myChart.clear();
                myChart.resize()
                // 再得到数据的基础上，进行地图绘制
                fetchChinaMapData().then(res => {
                    // 注册地图(数据放在axios返回对象的data中哦)
                    echarts.registerMap('China', res);
                    let option = {
                        tooltip: {}, // 配置提示框，有这个配置项即可
                        geo: {
                            map: 'China', // 选择你需要的地图类型
                            roam: true,
                            zoom: 1,
                            center: [103.97, 32.71],
                            projection: {
                                project: (point) => [point[0] / 180 * Math.PI, -Math.log(Math.tan((Math
                                    .PI / 2 + point[1] / 180 * Math.PI) / 2))],
                                unproject: (point) => [point[0] * 180 / Math.PI, 2 * 180 / Math.PI *
                                    Math.atan(Math.exp(point[1])) - 90
                                ]
                            },
                            label: {
                                show: true,
                                color: 'white',
                                fontSize: 10
                            },
                            itemStyle: {
                                areaColor: '#1E90FF',
                                borderColor: '#fff'
                            }
                        },
                        series: [
                            // {
                            //     type: 'map',
                            //     map: 'China',
                            //     projection: {
                            //         project: (point) => [point[0] / 180 * Math.PI, -Math.log(Math.tan((
                            //             Math.PI / 2 + point[1] / 180 * Math.PI) / 2))],
                            //         unproject: (point) => [point[0] * 180 / Math.PI, 2 * 180 / Math.PI *
                            //             Math.atan(Math.exp(point[1])) - 90
                            //         ]
                            //     },
                            //     roam: true,
                            //     zoom: 1,
                            //     // center: [103.97, 32.71],
                            //     // zlevel: 2,
                            //     label: {
                            //         show: true,
                            //         color: 'white',
                            //         fontSize: 10
                            //     },
                            //     itemStyle: {
                            //         areaColor: '#1E90FF',
                            //         borderColor: '#fff'
                            //     }
                            // },
                            {
                                name: '合作机构',
                                type: 'effectScatter',
                                coordinateSystem: 'geo',
                                // zlevel: 3,
                                data: this.geoData,
                                encode: {
                                    value: 2
                                },
                                symbolSize: function (val) {
                                    return val[2];
                                },
                                showEffectOn: 'render', // 闪动效果的触发时机
                                rippleEffect: {
                                    // color: '#28CCB6',
                                    brushType: 'stroke', // 光圈的样式，'stroke'表示仅描边
                                    scale: 4, // 光圈放大倍数
                                    // period: 5, // 光圈动画的周期，值越小，速度越快
                                },
                                itemStyle: {
                                    color: {
                                        type: 'radial',
                                        x: 0.5,
                                        y: 0.5,
                                        r: 0.5,
                                        colorStops: [{
                                            offset: 0,
                                            color: '#9cfda3' // 0% 处的颜色
                                        }, {
                                            offset: 1,
                                            color: '#2cedf460', // 100% 处的颜色

                                        }],
                                        global: false // 缺省为 false
                                    },
                                },
                                tooltip: {
                                    formatter: function (params) {
                                        return params.seriesName + '<br/>' + params.marker + params
                                            .name;
                                    }
                                }
                            }
                        ]
                    };
                    // console.log(option)
                    myChart.setOption(option);
                    window.addEventListener("resize", function () {
                        myChart.resize();
                    });
                })
            },
            convertGeoData(data) {
                const output = data.map(item => ({
                    name: item.organization_name,
                    value: [item.longitude, item.latitude, 10]
                }));
                return output;
            }
        },
        mounted() {
            this.setData()
        }
    }
</script>
<style lang="less" scoped>
    .geoMap {
        position: relative;
        width: 100%;
        height: 100%;
    }
</style>
```

### Current Behavior

我需要在geo地图上设置墨卡托投影，但是当我设置geo.projection时地图就直接不显示了

### Expected Behavior

我能够正确的在地图上设置墨卡托投影，并且展示带有涟漪特效动画的散点（气泡）图

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
[geo.projection](https://echarts.apache.org/en/option.html#geo.projection) works fine - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChKQN5OZAdiAtgUwC5IByAWQFccAjEAS2IBp1kA3EAG3MPgHYAmAHQAOHjwDMQhpACMATgEAGHgFZZKqdIC66AL5NkaDFlzdiAETzsAFvX0Y2nbnFEC-0gGzuhfKXyEDPd1FlX21kPXRDDGx8ImIAZTpMMEgABTwwPAAnAGcqciyAc0ZmSAcuIjgxBVd3ABYfSFVhWTq2qTEwyAiDUpjTAAkAe0xCyABpEeK7Vg4K-GlpOoFpZR53WUa-QT9lZTcpOq6e1D6TOIBBHBzMrNAcEqNyp2WhNRCmwTEVWSllY7sUWQ_TiiUwkAAYlkQJgAMa0HKwoaPexzJwAWmk2wEDTqH2-Ah4QgUv0g7mOCE0AG4EAAHLJDABWeFhYFoIxgp2Q9KZLLARAAFLShrRkgBKGAAPngpSFIuScAUmkgAHoZMSJQAqSCkcBWASpACSM0g6N1YH17CGhQF5v1EEwAtteoNhtVkD4kAA1JA5aKwHAtO7pBrINq7a6JWq-GKxehNHZyJgeczWYLhf6JdBpYgjH6FUqw-qFFGdS6jSanZ7tSGS-6I0atWWLQJwDDnS28AAPWn5gNaWOmyCyBTxhA6GkIIa0tkc2BRQp4IZEIGQHAgWlxADuQyy7GAKOQDNwRDAWS4JoAXkMhjgiD5Sim-ezMLo7GAb-w2ZvUCcaLCAGtCgZJNgAAYSGK0sjiABiaQqHg-CUTZMB2G4VccnIKhMi7fkSCfVkX0PSAuziWE8GSbJiJwsB4jAABPNCV1KZAkSg2CADMuOIUodDfdA0MXTBgGYoxd1oCi8OIFhsjZWEOGItCOLwxZpBNGi6MY9CWMgNjdzidchIgHijD48I7BybIJJySpSlXZAGNpUx11pYjkEXIZDWE7siFHUyTXs4xYhIPAuL5NzIEc0xQo4vl4nksBbgipFd2AUVwDweJ6JuPA7xIDzksg_SSCyPADxNZBQAgCrIs_b9RKMDAON3ddEuydMs2lQKjFKsACnBWkBH6b0SGgYgRsG544D4akdPCHSTiMHJ6OoSD4loS9uA4pNCI5AUHAlbrIF6_qyg4ablW1ZQaUa7oaqyWhaVpNCAFEwrTLlbsgKhzxyKwABV6KcuIbgZAC8Ai5BEQ4bg6gW3ixwnIA).
📌 please close issue if problem solved.

**Comment by aaa930811** [comment]
> [geo.projection](https://echarts.apache.org/en/option.html#geo.projection) works fine - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChKQN5OZAdiAtgUwC5IByAWQFccAjEAS2IBp1kA3EAG3MPgHYAmAHQAOHjwDMQhpACMATgEAGHgFZZKqdIC66AL5NkaDFlzdiAETzsAFvX0Y2nbnFEC-0gGzuhfKXyEDPd1FlX21kPXRDDGx8ImIAZTpMMEgABTwwPAAnAGcqciyAc0ZmSAcuIjgxBVd3ABYfSFVhWTq2qTEwyAiDUpjTAAkAe0xCyABpEeK7Vg4K-GlpOoFpZR53WUa-QT9lZTcpOq6e1D6TOIBBHBzMrNAcEqNyp2WhNRCmwTEVWSllY7sUWQ_TiiUwkAAYlkQJgAMa0HKwoaPexzJwAWmk2wEDTqH2-Ah4QgUv0g7mOCE0AG4EAAHLJDABWeFhYFoIxgp2Q9KZLLARAAFLShrRkgBKGAAPngpSFIuScAUmkgAHoZMSJQAqSCkcBWASpACSM0g6N1YH17CGhQF5v1EEwAtteoNhtVkD4kAA1JA5aKwHAtO7pBrINq7a6JWq-GKxehNHZyJgeczWYLhf6JdBpYgjH6FUqw-qFFGdS6jSanZ7tSGS-6I0atWWLQJwDDnS28AAPWn5gNaWOmyCyBTxhA6GkIIa0tkc2BRQp4IZEIGQHAgWlxADuQyy7GAKOQDNwRDAWS4JoAXkMhjgiD5Sim-ezMLo7GAb-w2ZvUCcaLCAGtCgZJNgAAYSGK0sjiABiaQqHg-CUTZMB2G4VccnIKhMi7fkSCfVkX0PSAuziWE8GSbJiJwsB4jAABPNCV1KZAkSg2CADMuOIUodDfdA0MXTBgGYoxd1oCi8OIFhsjZWEOGItCOLwxZpBNGi6MY9CWMgNjdzidchIgHijD48I7BybIJJySpSlXZAGNpUx11pYjkEXIZDWE7siFHUyTXs4xYhIPAuL5NzIEc0xQo4vl4nksBbgipFd2AUVwDweJ6JuPA7xIDzksg_SSCyPADxNZBQAgCrIs_b9RKMDAON3ddEuydMs2lQKjFKsACnBWkBH6b0SGgYgRsG544D4akdPCHSTiMHJ6OoSD4loS9uA4pNCI5AUHAlbrIF6_qyg4ablW1ZQaUa7oaqyWhaVpNCAFEwrTLlbsgKhzxyKwABV6KcuIbgZAC8Ai5BEQ4bg6gW3ixwnIA). 📌 please close issue if problem solved.

It turns out that I set the "geo.center" property, and I wonder what the default value is.

**Comment by helgasoft** [comment]
it seems _geo.center_ has to be projected - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChKQN5OZAdiAtgUwC5IByAWQFccAjEAS2IBp1kA3EAG3MPgHYAmAHQAOHjwDMQhpACMATgEAGHgFZZKqdIC66AL5NkaDFlzdiAETzsAFvX0Y2nbnFEC-0gGzuhfKXyEDPd1FlX21kPXRDDGx8ImIAZTpMMEgABTwwPAAnAGcqciyAc0ZmSAcuIjgxBVd3ABYfSFVhWTq2qTEwyAiDUpjTAAkAe0xCyABpEeK7Vg4K-GlpOoFpZR53WUa-QT9lZTcpOq6e1D6TOIBBHBzMrNAcEqNyp2WhNRCmwTEVWSllY7sUWQ_TiiUwkAAYlkQJgAMa0HKwoaPexzJwAWmk2wEDTqH2-Ah4QgUv0g7mOCE0AG4EAAHLJDABWeFhYFoIxgp2Q9KZLLARAAFLShrRkgBKGAAPngpSFIuScAUmkgAHoZMSJQAqSCkcBWASpACSM0g6N1YH17CGhQF5v1EEwAtteoNhtVkD4kAA1JA5aKwHAtO7pBrINq7a6JWq-GKxehNHZyJgeczWYLhf6JdBpYgjH6FUqw-qFFGdS6jSanZ7tSGS-6I0atWWLQJwDDnS28AAPWn5gNaWOmyCyBTxhA6GkIIa0tkc2BRQp4IZEIGQHAgWlxADuQyy7GAjEgsLwyWyRBTfPZmAEF9ZAsDSwY200YpNDNwRDAWS4JoAXkMhhwIgfFKW9Z0wXQ7DAAD2DZTdUBOGhYQAa0KBkk2AABhIYrSyOIAGJpCoIiiJRNkwHYbhVxycgqEyLt-RIMCrxRZAuziY9TyyVjIHosB4jAABPSiV1KZAkVwgiADMZOIUodEg9BKMXTBgFEoxd1oE9GOIFhsjZWEOB4yipMYxZpBNPiBOEqixKPHDdzidcVIgOSjAU8I7BybItJySpSlXYFzhIPAZL5HjkCE2lTFCqS-XiQywFuCL7N3YBRXAPB4kEm48CAkhF2RE1xIcvCSCyPAD2KyBQAgaroJwuD1KMDApN3dckrPX1aSzaVApaiqwAKcFaQEfpvRIaBiAm0bnjgPhqTs8I7JOIwckE6gcPiWhf24KSk1ZK9fQcCV-uQQbhrKDh5uVbVlBpFrumqrJaFpWlKIAUTCtMuUeyAqG_HIrAAFUE6K4huBlkLwFLkERDhuDqFb5LHCcgA).

**Comment by aaa930811** [comment]
> 似乎必须投影 _geo.center_ - [演示](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChKQN5OZAdiAtgUwC5IByAWQFccAjEAS2IBp1kA3EAG3MPgHYAmAHQAOHjwDMQhpACMATgEAGHgFZZKqdIC66AL5NkaDFlzdiAETzsAFvX0Y2nbnFEC-0gGzuhfKXyEDPd1FlX21kPXRDDGx8ImIAZTpMMEgABTwwPAAnAGcqciyAc0ZmSAcuIjgxBVd3ABYfSFVhWTq2qTEwyAiDUpjTAAkAe0xCyABpEeK7Vg4K-GlpOoFpZR53WUa-QT9lZTcpOq6e1D6TOIBBHBzMrNAcEqNyp2WhNRCmwTEVWSllY7sUWQ_TiiUwkAAYlkQJgAMa0HKwoaPexzJwAWmk2wEDTqH2-Ah4QgUv0g7mOCE0AG4EAAHLJDABWeFhYFoIxgp2Q9KZLLARAAFLShrRkgBKGAAPngpSFIuScAUmkgAHoZMSJQAqSCkcBWASpACSM0g6N1YH17CGhQF5v1EEwAtteoNhtVkD4kAA1JA5aKwHAtO7pBrINq7a6JWq-GKxehNHZyJgeczWYLhf6JdBpYgjH6FUqw-qFFGdS6jSanZ7tSGS-6I0atWWLQJwDDnS28AAPWn5gNaWOmyCyBTxhA6GkIIa0tkc2BRQp4IZEIGQHAgWlxADuQyy7GAjEgsLwyWyRBTfPZmAEF9ZAsDSwY200YpNDNwRDAWS4JoAXkMhhwIgfFKW9Z0wXQ7DAAD2DZTdUBOGhYQAa0KBkk2AABhIYrSyOIAGJpCoIiiJRNkwHYbhVxycgqEyLt-RIMCrxRZAuziY9TyyVjIHosB4jAABPSiV1KZAkVwgiADMZOIUodEg9BKMXTBgFEoxd1oE9GOIFhsjZWEOB4yipMYxZpBNPiBOEqixKPHDdzidcVIgOSjAU8I7BybItJySpSlXYFzhIPAZL5HjkCE2lTFCqS-XiQywFuCL7N3YBRXAPB4kEm48CAkhF2RE1xIcvCSCyPAD2KyBQAgaroJwuD1KMDApN3dckrPX1aSzaVApaiqwAKcFaQEfpvRIaBiAm0bnjgPhqTs8I7JOIwckE6gcPiWhf24KSk1ZK9fQcCV-uQQbhrKDh5uVbVlBpFrumqrJaFpWlKIAUTCtMuUeyAqG_HIrAAFUE6K4huBlkLwFLkERDhuDqFb5LHCcgA)。

这正是困扰我的地方，是否应该在文档上注释一下，如果使用墨卡托投影，center应该使用projection.project([114,22])而不是[114,22]
