### ISSUE TITLE
[Feature] Zebra Striping For Charts

### ISSUE THREAD

**Issue by vishaalagartha** [apache/echarts#20364]
### What problem does this feature solve?

Zebra striping is a styling feature that can create clarity between horizontal or vertical columns in tables and graphs. It is a common feature in tables, but less common in graphs. The design I'm aiming to achieve is something like the ones below:
<img width="492" alt="Screenshot 2024-09-23 at 9 40 36 AM" src="https://github.com/user-attachments/assets/02abe557-bd42-4dc7-b0be-6461b0bbd3c2">
<img width="489" alt="Screenshot 2024-09-23 at 9 40 56 AM" src="https://github.com/user-attachments/assets/04e6975c-708b-4598-9675-2746f02d18fb">

Note the vertical stripes on each x column.

### What does the proposed API look like?

I'm not sure if there is an existing API for this or workaround, but I think the API should allow us to add the following parameters:

* `zebraStripeDirection` (horizontal or vertical)
* `zebraStripeColorEven` (even numbered column/horizontal color)
* `zebraStripeColorOdd` (odd numbered column/horizontal color)

**Comment by helgasoft** [comment]
see [markArea](https://echarts.apache.org/en/option.html#series-line.markArea)

**Comment by vishaalagartha** [comment]
@helgasoft - I actually did a little more research - wouldn't [splitArea](https://echarts.apache.org/en/option.html#xAxis.splitArea) be the appropriate use case for this?

**Comment by Ovilia** [comment]
@vishaalagartha Yes, `splitArea` is suitable for this case and it supports an array of color which can be used as zebra striping.

**Comment by vishaalagartha** [comment]
@Ovilia , I'm trying to add `splitArea`, but the chart is showing up funny. See screenshot below:
<img width="566" alt="Screenshot 2024-09-23 at 8 02 22 PM" src="https://github.com/user-attachments/assets/72130f3d-1183-4b2f-890e-0672253c327b">

These are my options shown below:

<img width="780" alt="Screenshot 2024-09-23 at 8 04 58 PM" src="https://github.com/user-attachments/assets/a7d15864-04ce-47dc-850f-2665a108c8dd">

I'm trying to get even areas for each x-axis point.

**Comment by Ovilia** [comment]
@vishaalagartha This may be a bug with time axis. Can you provide an online demo?

**Comment by vishaalagartha** [comment]
I'm actually opting for the `markArea` option instead! It seems more configurable to me.
Thanks for all the help either way though!
