### ISSUE TITLE
[Bug] 从5.5.0版本开始，极坐标的角度轴设置boundaryGap: false后axisLine未正常闭合

### ISSUE THREAD

**Issue by 0x1f57** [apache/echarts#20367]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=scatter-polar-punchCard&edit=1&reset=1&version=5.5.0

### Steps to Reproduce

打开[此链接](https://echarts.apache.org/examples/zh/editor.html?c=scatter-polar-punchCard&edit=1&reset=1&version=5.5.0)

按照下面截图，修改axisLine的show为true

![image](https://github.com/user-attachments/assets/3aa31145-a19c-477d-ba3c-fa9637a05570)

此问题仅在5.5.0及以上版本出现，5.5.0以下的版本则正常

![image](https://github.com/user-attachments/assets/d82df7c1-1de1-4fbe-ba34-8c78c799912d)

### Current Behavior

极坐标的角度轴设置boundaryGap: false后axisLine未正常闭合

### Expected Behavior

极坐标的角度轴设置boundaryGap: false后axisLine能够正常闭合

### Environment

```markdown
- OS: win10
- Browser: Chrome 129.0.6668.59
- Framework: Vue@3
```

**Comment by Ovilia** [comment]
This is not a bug. See #20184 for more information.
