### ISSUE TITLE
[Bug] 绘图数据出错

### ISSUE THREAD

**Issue by xieguigang** [apache/echarts#20375]
### Version

5.5.1

### Link to Minimal Reproduction

https://jsfiddle.net/75bpny3s/1/#

### Steps to Reproduce

你好，

我这边想通过echarts绘制多系列的``盒须图``，但是我发现目前盒须图绘制上在不同的数据上还存在有问题，具体问题如下：

当我使用下面的配置信息进行绘图的时候，会正常显示出多系列的盒须图

![image](https://github.com/user-attachments/assets/d3650cc9-7851-4f0d-95fd-294624264ceb)

这个是正常的配置信息以方便进行比较：[https://jsfiddle.net/so4Lgbve/2/](https://jsfiddle.net/so4Lgbve/2/)

但是，当通过上面相同的配置信息，但是更换了一个新的数据源之后，echarts绘制出错了，显示错误信息：Uncaught TypeError: Cannot read properties of undefined (reading 'ends')，这个可能是一个数据计算上的错误没有被echarts正确处理导致的。

![image](https://github.com/user-attachments/assets/14d80444-bfe4-418b-b050-81432599f0f0)

这个是出错的配置信息以方便进行测试：[https://jsfiddle.net/75bpny3s/1/#](https://jsfiddle.net/75bpny3s/1/#)

上面的两个配置信息差别仅在数据源上

### Current Behavior

绘制出错，仅显示出了第一个盒子

```
echarts.min.js:45 
 Uncaught TypeError: Cannot read properties of undefined (reading 'ends')
    at gP (echarts.min.js:45:605242)
    at t._add (echarts.min.js:45:604321)
    at t._performRestAdd (echarts.min.js:45:225165)
    at t._executeOneToOne (echarts.min.js:45:224302)
    at t.execute (echarts.min.js:45:223868)
    at e.render (echarts.min.js:45:604638)
    at t.progress (echarts.min.js:45:167158)
    at t._doProgress (echarts.min.js:45:135641)
    at t.perform (echarts.min.js:45:135213)
    at echarts.min.js:45:216158
```

### Expected Behavior

正常情况下应该可以正常的显示出两个盒子

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
several things to fix:
- remove yAxis.data
- add _fromDatasetIndex_ and _config_
- add _series.datasetIndex_

[Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgZglg5gvAAgN4KgFwKYFsByBDLDAMRACcs81NSAuBAcgFEAPAB1IwGdOpx6EAvgCgQrNLzAJESIQgTi0AGwx0A2rLnJ5GZmjr0ACgAsMYEGgCerDAgAiUCBAwcwaBC3ZcefADQJlEHoMwKbU_AI-GnIympqYuvoArqzWtAgAigDMCADUCACMAHQArAgAVAgAkukASggAOmCKIADuznTp-QgAtAUl5VW19JGxcgBGZAAmzgDCIM1p9ADEAJxrw1GaE6TTpADqUJNoRnT5I6PxaADKlsp0KBDg11AAXioFACyC57EBQfT5AAMAFINqN5KJ9CsQfRNsI5ABdc6TSh4TgYILqWIxUacECJUghNQIVT5D6ZADsfjJKwATNTMisqQVMgA2Zn5TKZAAc1Np3My1Ip3LOLIprOpH1ZxQRCARcJ-WjxBKJJNUrPymr8H1prNpCNlEU2KDQpDwYE4j3I93kVne9AmbGaaGGCFAkFgEQQEFIICwtlR6LQlTA02YNEB32N8jNFqtWBtlms-kdrGdrvd0BgXp9foDaDRGJDYZoXQECA0SI0eFIUDwNtMeDGykmdFNiQwfmmwDwihtnCMrTbpA7gijcjQIHm4lYidrMBg7QY6GwrrwzCgnAMICgriXJrt-gHeEmrXC4_8GEXocTkIYQNBF5gtdbWj--gfrvnRn-n78EyoP0P2KR8jTkCwAEEN04e5NiTe0e0wGAyAsMEtnxUMawsABxPBZxjDtFTAAgMFw_DMkBRUAHoqJRAs1CYNgOG4CR6CrWJODTdAII4eslUHFo6AgXt0QvOROMUdAABld3eFAByHb0RJseEL2YKDN1g2J4P0AA3XsOzQuRiMIfQDAwPAAGsEB4iyjIQCTuN4_sBOHUcwM0GisF3U5AWhEpij8ChwwQDVNQ0Dz0VrLg1GjEz7XSRJe3QCwEDmVxfUUThXR0hhU3TLtAyLUMdBoWkxK0eL9AAVTASyzBaMAcsPPKQCdcxXTowtgxK8NslU-UBAAbiAA)

**Comment by xieguigang** [comment]
That’s great, my problem is solved, thank you very much.😋
