### ISSUE TITLE
[Bug] Donut chart's center number is not showing the correct tooltip and there is no way to disable it as well

### ISSUE THREAD

**Issue by ndrohankar** [apache/echarts#20381]
### Version

5.2.2

### Link to Minimal Reproduction

https://github.com/apache/echarts/issues/14051

### Steps to Reproduce

Go for any donut chart and select the position inside the label property as the center.
Now, say when we are returning the sum of all the numbers, the tooltip on the center label should show the correct data instead it is showing the first series value.

### Current Behavior

Tooltip for the center label in the donut chart should show the correct value or there should be some provision to disable the tooltip for the label in the donut chart.

### Expected Behavior

Tooltip for the center label in the donut chart should show the correct value or there should be some provision to disable the tooltip for the label in the donut chart.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
use ```label:{ silent:true }``` to disable tooltip  (undocumented)
📌 please close issue if problem solved.

**Comment by plainheart** [comment]
Besides the approach by @helgasoft, you can leverage a centered [`title`](https://echarts.apache.org/option.html#title) horizontally and vertically to show the sum. The [`title`](https://echarts.apache.org/option.html#title) component doesn't show the tooltip as it doesn't support currently. [Demo](https://echarts.apache.org/examples/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcsA2musiaRjgB5gEDkASjgGY4BO7swzsAhrAHUcAIwDOEMDjoAacqVEBXYZJr0AYrwDWOWABFeYXjLnpczWrDoBjHNEls6cgL6yKqCugD0n2IoC2JpSqsACMAAwALAAcsADUsADsAMwArHGwKVFh6dER6UlhYa4eZhbWtvbGHhig9DZ27I4UTiQAusVgwMBYkCAE7qRgbBAA5iPs9BI4fk2wLiS449AAJv1ywMMV9ABu7JBWvFhVpKX0pbPz6KLsEDiiBMRugdC8fviWAIJWNqKisGpsYAzYoUMAATxA7zoIFuxwobF4ywgCnuRDoBQApDJLCkwlj2oFlgZeA9AugkLBtocFO9wtFpLAXm96ABlHC8NhWAAWsAAotARhBoFI5iCPBSqVgaQRkikGUyoboIBwrGA6KKychKdT3pkiozXlDeX5eBAjhrquTtVL3rl5Yb6ABVaBQOAfZaidWXS0SnUEAr6hX0ABqEGWOGAsHdnrmgVazjaKCcAG4gA)
