### ISSUE TITLE
[Bug] echarts Qn[o] is not a constructor

### ISSUE THREAD

**Issue by bbhxwl** [apache/echarts#20383]
### Version

5.5.1

### Link to Minimal Reproduction

http://

### Steps to Reproduce

I debug locally and run it locally without any problems, but when I publish it to the server, I encounter this error. I don't know why?

<img width="711" alt="image" src="https://github.com/user-attachments/assets/a211a427-7dc6-440d-b676-b98f81642638">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/42627ac1-9bb7-4f99-a359-971c86ee13da">
```
const chart = useTemplateRef("chart");

```

```
    <div ref="chart" class="w-full h-full" v-bind="$attrs"></div>

```

### Current Behavior

I debug locally and run it locally without any problems, but when I publish it to the server, I encounter this error. I don't know why?

<img width="711" alt="image" src="https://github.com/user-attachments/assets/a211a427-7dc6-440d-b676-b98f81642638">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/42627ac1-9bb7-4f99-a359-971c86ee13da">
```
const chart = useTemplateRef("chart");

```

```
    <div ref="chart" class="w-full h-full" v-bind="$attrs"></div>

```

### Expected Behavior

I debug locally and run it locally without any problems, but when I publish it to the server, I encounter this error. I don't know why?

<img width="711" alt="image" src="https://github.com/user-attachments/assets/a211a427-7dc6-440d-b676-b98f81642638">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/42627ac1-9bb7-4f99-a359-971c86ee13da">
```
const chart = useTemplateRef("chart");

```

```
    <div ref="chart" class="w-full h-full" v-bind="$attrs"></div>

```

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
See if #19921 helps.
