### ISSUE TITLE
[Feature] How to highlight both ancestor and descendant nodes of hover simultaneously

### ISSUE THREAD

**Issue by sentimental114** [apache/echarts#20397]
### What problem does this feature solve?

Now I have a requirement to highlight both the ancestor and descendant nodes of the current hover, but the configuration item can only be selected as a single option. How can I implement it? Thanks

### What does the proposed API look like?

Can a new configuration be added to the configuration item to enable this feature

**Comment by plainheart** [comment]
If it's the tree series, you can set [`emphasis.focus`](https://echarts.apache.org/option.html#series-tree.emphasis.focus) as `'relative'` to highlight ancestor and descendant nodes.

**Comment by sentimental114** [comment]
![微信图片_20241008140647](https://github.com/user-attachments/assets/042b6b09-c06d-4b02-857e-65d9700a0af2)
I have tried this before, and it seems to have a bug. When using this configuration, it turns into highlighting itself. The same effect as using 'self' configuration

**Comment by plainheart** [comment]
The sunburst series doesn't support `'relative'` yet. You can open a PR to add support for this feature, just like #17009.

**Comment by MatthiasMert** [comment]
You can also implement it on top using [mouse events](https://echarts.apache.org/en/api.html#events.Mouse%20events) and modifying the itemStyle accordingly.

[Example](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=G4QwTgBAJiAuIQLwQNoCgIQN4cxAdiALYCmAXBAOQDiYI-UADiJQDS6YDGAFgJYA2UMCXwV0ePDgkTCpCpQCq-TvxIQAMiQD2bDtND8AruQgBGAKztpeHgKEixe61OvTZJygGEthgM698CAApEE4Aa11XfRAjEwAmJ2kAXyso7ETrd3lvPwCIAFlwAE9ItMwDYwpLDOlbQWFRVBrnZtcsqhDw3y18UrKJCvjWiSThiABdVpTWlzL2rx9_QIAhET60wYoAFimayetplqj5gEFDfFhg-hJ1iTr7RvE02bT5nKWIAGk4G9SyzYgOzKoyi-2Sf0kNXmADE4NwSGBbngAaYAAwQu58eoOJplF7HYgefK_MYA6r9CC8WAkIgAZVgRVUFHxaU4Wn4WjA8mEUEoYxBaUOzzG82WYC0sHhkAACiRqYiMa4UbtQYkBZgwUKXvN8rwwiTMXYGo4jm1CfIlCo1AARehIrhYh4m4UUt6LPLqQycEqK6wAgDMU19kNd5qo7w9XoiwYGMUqgJjNkdxtxFPSabw8wAciRGPCAO72jZxoYZ9VpMFRcsSSt4cua1LasOULP0b3re4pp4SFmYeaW1QQLN6g2uTs47uuXtuZsRlZyhlF2OxCimIMzEWz92BIIifA-0kligJYF7NV6TVocYAbjQWkYsF4PSQ6YgvgRvBIvmZegZjA8vjnAARoYYC-LA6wwPAFBQSAEJ0FAvB-GI6JUAAnKiACklDjBC_AgEBJD8D-1jivA1LciAiExHyIwQjSeYgP436vhIABmWicMhVD4D0Nx6AKoxJLeaBoEQRSeNw4CwAAdD0AAUlBEIs2jAAibAQGx5ycI-z7ycwdBEL4ACUr6qJcfAAObcPwvDWdSUAvgZxC-DJsDCCQ0pwgAkvgHEyUQICMPJVI0kgAB8lLUkQMnuMZt6YLwbEQPp4AuTJsEyeOgQAISIMg5xQCQbEBCQUCmS8Vk2XZ3AOS-VW2fZZVZT0nBwPJbL8KoOnWl-nAiDAFy-KlhmubBxnGbgAq4BxkAdT04FRWFWjJeNrEQCBdgABI1Y1tVlba8AhdFrAQA1NUOadWD3qEVJFBQqIyXESTxVNomYOJknSTJ76wAA8g-T74PJWDvmAn4sSgWCwTBcAgEk4wvbeSOiWJElSWAskKUpKk-BBp1acoumBCNLkVTNnIpWy-CLaFRAQCt0Bw-TEibYIO3WXtDmHSAx00qdKC4dgN2cHdq4o5gAqfRjsm_QDxMg2DENiNDcOw_ACMoyjomEzpQMQJ13WwL1vj9Qw9CwMNa0uElKWZdlSD5RAhXFaV5UQMIsCgYEKCZe4N64Lg5nQH1A0W74L6-3DsWEgHmCzVTC2XPcDOrdH2Us3gRWm2HQ0vtnZuDZbLXKO1hskD1ofm0NHWOhNCUQAKnveyHOfV5byOo7rxMbYY227RdB1w_JsGnedTVQKddP0oyJCZ7b8nj_tUAyQEKiGNnI_R3FpmZdPDKDsg13MKLDLiw3RHvkz8Cr9FM-H0tdIHyQDe4Av9vJiIjsFQwrv4GVplm5gHwA3BO80abJ0dKna-IAsqf3wJnTAbMoAc2qhPHmtc7BjwHhPKed9n6vUlmgJIQA)

**Comment by MatthiasMert** [comment]
Code can be copied from tree (https://github.com/apache/echarts/blob/master/src/chart/tree/TreeView.ts#L488-L492) to sunburst (https://github.com/apache/echarts/blob/master/src/chart/sunburst/SunburstPiece.ts#L154-L157).
