### ISSUE TITLE
[Bug] scatter and line with area - scatter is covered with line chart

### ISSUE THREAD

**Issue by supportdesk-si** [apache/echarts#20393]
### Version

5.2.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=scatter-polynomial-regression

### Steps to Reproduce

This is from the eCharts [site](https://echarts.apache.org/examples/en/editor.html?c=scatter-polynomial-regression). Code is altered to demonstrate the issue.

```
// See https://github.com/ecomfe/echarts-stat
echarts.registerTransform(ecStat.transform.regression);
const data = [
  [96.24, 11.35],
  [33.09, 85.11],
  [57.6, 36.61],
  [36.77, 27.26],
  [20.1, 6.72],
  [45.53, 36.37],
  [110.07, 80.13],
  [72.05, 20.88],
  [39.82, 37.15],
  [48.05, 70.5],
  [0.85, 2.57],
  [51.66, 63.7],
  [61.07, 127.13],
  [64.54, 33.59],
  [35.5, 25.01],
  [226.55, 664.02],
  [188.6, 175.31],
  [81.31, 108.68]
];
option = {
  dataset: [
    {
      source: data
    },
    {
      transform: {
        type: 'ecStat:regression',
        config: { method: 'polynomial', order: 3 }
      }
    }
  ],
  xAxis: {
    splitNumber: 20
  },
  yAxis: {
    min: -40,
  },
  series: [
    {
      name: 'scatter',
      type: 'scatter',
      symbolSize: 20,
    },
    {
      name: 'line',
      type: 'line',
      smooth: true,
      datasetIndex: 1,
      symbolSize: 1,
      symbol: 'circle',
      label: { show: true, fontSize: 16 },
      labelLayout: { dx: -20 },
      encode: { label: 2, tooltip: 1 },
          areaStyle: {
      opacity: 1
    },
    }
  ]
};
```

### Current Behavior

The line chart overlaps and hides scatter. Changing the order of the series has no effect, it seems scatter will always be under the line chart.

![image](https://github.com/user-attachments/assets/107a970b-c9b1-4d49-8b1f-d3dc7f1f2638)

### Expected Behavior

Controlling the order of the series to draw line chart first and then scatter (z-index as a CSS comparison).

### Environment

```markdown
Browser, vanilla JS
```

**Comment by MatthiasMert** [comment]
There is a [z-property](https://echarts.apache.org/en/option.html#series-scatter.z) for series.

[Example](https://echarts.apache.org/examples/en/editor.html?c=area-time-axis&code=KYYwFghgTgLgzgOisA5gSzjYUAqUIB2cAZgPZQC2AFKAMowQwIz5FmVKrJxxqkEBKANwBYAFAh-mAAQATRhGkBeaQG1x0tQE4AbAgBMAFgA00gIxmEAZgCsAXWMa1VqwgAMW0wA4bCCw6dVGwB2BB1TKz0dMwCxTVVIhGDg031Q_R1Y-P03P1M9YP0stUNfGysIvStg4tULXLcU6S9csytawvcbVNyvL1qrLQQvfQjQs3tHOJKvLtNg3MnA3u7pfQQQ2ptLHXDpHVcaqfjo9yazNL9247UdQw2TaRcNrQGy1N83GJvVfQyN1a7e5uIo_Mx9MKmMzBXxWb6BLyWOFQtyzHT9cR2URiUgABxgfAIymkAG8nPIGHBgDAAFxqJyaMnTTSaOCkACuUBAwDpFIgDOkAF8boyBZoWIQSOQKHSmSz5dIYABPXE86QAcjoDFpyBQ3F4_HVIoVkgIxDQKFl0go1LApFkdPVuNIABslQRSBQ0BAXUbpORZNg6VYhWLQ8zw5pigAPACC0YwsoFcFxLrQMAAcuyKAAjINrNxOYVOJXxxOkgVegh0gC0hjcN2L0ypUDQwDgdPUEblCoIEBtjrgIEYWCgRrDytVg-HMFH44jrKVuddtDQAC81TljZo18GBU35T35X2Bxq0wRgPOFYqVWr1efL9vpHAKKRSDAwHSWOzgE--VSYAASQIQNozpMwnzgJccxXdc1QgsMoOXF1HRANAuRdR8wxdCA8xQ0lnztAB3L8oB_UwyAIGBVw3cCdCFJ8cLwgAZCAlQ5WkCNkMDpBrHIGLDYACEkQMrSY4B8NGRU3xdAlcXAgSFwVaBgAgeglUwpMlLxCA0OVcD92NQUnDscRBSEIA)

**Comment by supportdesk-si** [comment]
Thanks @MatthiasMert never occurred to search by only 1 letter
