### ISSUE TITLE
[Bug] Heatmap not updating when number or series changes to 1

### ISSUE THREAD

**Issue by gtsirkalova** [apache/echarts#20404]
### Version

5.5.0, .5.5.1

### Link to Minimal Reproduction

https://codepen.io/Galya-Tsirkalova/pen/OJKbQYK

### Steps to Reproduce

1. Create a heatmap chart with one item in the `option.series` array
2. Change the `option.series` to contain 2 items 
3. Change the `option.series` to contain 1 item

### Current Behavior

The data in the chart is not changes and the visualization is stuck to the way it looks like when the `option.series` array contains 2 items

### Expected Behavior

The chart gets updated

### Environment

```markdown
- OS: Windows, Linux
- Browser: Chrome, Firefox
- Framework: React
```

### Any additional comments?

I don't want to use `setOption` with `notMerge=true` because I need to keep the tooltip open if the it's been already open during data update.

When the newly coming data contains more than 1 items in the series array the chart gets updated. Example here: 
https://codepen.io/Galya-Tsirkalova/pen/wvVomoK

Please advise how can I proceed!

**Comment by helgasoft** [comment]
duplicate of #6202, see answer by @pissang.
@gtsirkalova, unlike your code in previous #20269, this time you made an effort to simplify it 👍 
A Minimal Reproduction could be even shorter - [Demo](https://echarts.apache.org/examples/en/editor.html?code=PTAEAsFMEMBcFtoAcBQBjA9gOwM6whgK4BOOoAvKANoDkAjAEzQ0A0o9zbNTr7AzMwC6AbnTY8oACbQAnmUq0AynBLSZvGgDFiASzUaAKuBI59IsbnzTY0CtRShqABjYvQAVkEsH1Oq7Z0Xj5UDP6gDEGOVHwBbAAskdSh4WwAnIIo5tbQDHZUVC5-AByCGTiQupA4dHk-AN6gWNDwkABc7Jo6pLC8sDJIbexQcIhIvNnt2WwANtAARpDT7Q044BgA7u2wxISQoAC-bJjTGMTtNADETpoAQnQ3AGw0B5mi5ZU4uQr1jc2DWl08L1-v9hghkOM4NBJlCZvNFstQKsNlsdntDqBjqdzldbvcnmwAF6tBiHH5NFrnRSQTBYSTAgbnMGjSE2GE2ZKzBZLUArNabUDbXYHI4YE5ndjESD0omtPgvcwYJCwHTYOx1HywDBilVIRFIDA4HQq7DnLVjEWgADmukky1pNh0WAAMvClkLIBjppArZA6a06mTHAAPACCwZ0OGWPkcfUZ7DQcB9p3U3kcjgmBBMafTOCQ02Noal0N5Mdz_NRuzL-x8QdAMnDkej6cFIPOidgyeIqbLmbUOBzjjzBdgRZgzZbSIrgrR1drOfeOiq7UXVToKH2b0gsAMOhaRFgAAoAGaELBoE1YQ8ASlLjngMgAwuBoMRYAA6SSRpBwNDgUMXqqV4ai2cb_Mi6y7mMg5IhUS44AAknSkDBu0Li9lCSGSCh7R8LW16iBidDEQRKCwFa0x2Me0DTOUW6wEhnbEAAbjRJ5noBao3negoUXYACE5HTKI95Pi-b7vuUsAAPLKkBh5lkJoAAPy8quUbqaSoDLOprTqXQGJlg0Ur5tAaCQAAshUvrtLQ6k0IILyOKRGIMG5DAEUAA) (with solution).

**Comment by gtsirkalova** [comment]
The problems seems to be solved by using ` { replaceMerge: ['series'] }` as proposed in the demo. Thank you!
