### ISSUE TITLE
[Feature] Animatable dashOffset for LineStyles

### ISSUE THREAD

**Issue by Syndlex** [apache/echarts#20414]
### What problem does this feature solve?

I would really like to animate the LineStyle of a Graph Chart.

Example:
![Unbenanntes Diagramm-Seite-6](https://github.com/user-attachments/assets/55f8f850-905a-407c-b5e3-552fb7b0196d)
 
The Mozilla docs already talk about how to animate this:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineDashOffset#marching_ants

Tested it in the Editor: [Link](https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQ1AbrAAT6MC8jAjDQzM4XAFMYDADZtGSAXACS_IaNJ8AxjAHAB_ADScADHqq0AZgFdCSuPlSFlq9fwoBvaoxfNxLAKS69jANScaV0YlKyRUEQEEEVQyfHJqAF9aABIEYikAKQBlAHkAOVIAJRycgBUAfQAFAEFSgAk_RgByAHpcKDgoFqgkSTg2jq6IpABaYHxJGCgAI2GEACswwibtEzMLK0ZSYimABwhyRicXUEhYRAh8XAFsPCIyAxdUXY3rdmPXOFRwi12ALiOCU0zlcEXShFwAIA2iCgh8gi52p0ATsoPsEEoOgJiKgYPgBEgEMA0aQ1uZLNZSFBDvCES5VHBjDBrFAEIQoOpAnTGAl4nSkkEALrAoKTfFIaGw1y0oLs9QApqYAmMACyEyEM2GKylQTgIF2AgVqP22u5jBEUBAqGMcAVhCsAlN3KRUBRewgbNQ1yQIu5IiIAGsJYxjR7_YQg766ZjBDi8QS3WiPTHsbjxVGETAcMAAXAYMYBBmghbpgIRACZQiUBhc_nCzqEbtUEh8K8FXjiBA4E6zYZccS4IIYAqHNMEk0Gy4gZPzTMy5hLdbbUcZy5LtccnQhBb_ow8wWZ9OzUhMRFMPhxsvK0FxoQAToEAAWIsI4kADwBACZDy-XOGBFkeoRBWq7BOEuIKmETJKI6v6fPqhrNLgqCDgIuA9tyShMluhAEsGD4AMxwS46BXHAEAAgArMRjDtCgOSGIYfQAvgh4NgKriCiCCRcqc0DwMgUg5C8FKkM8rwGLylBAA)

I think it would need some CSS injection or so.
Any idea where i can find examples for this?

I also Tried Keyframes but I can't get them to work and I can not find a Example with working Keyframe Lines.

### What does the proposed API look like?

Not Really have a suggestion. Animations can be very complicated.

For me it would be enought to have:
`series-graph.lineStyle.type = 'animated'`

or maybe it already work with keyframes and i am just not capable.

**Comment by helgasoft** [comment]
Good idea! Your research got very close to the solution. Just have to reset [dashOffset](https://echarts.apache.org/en/option.html#series-graph.lineStyle.dashOffset) in a loop.  [Keyframes](https://echarts.apache.org/en/option.html#graphic.elements-line.keyframeAnimation.keyframes) are for graphic elements only.
[Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDesBQtaTAGwKYC5l0NNcAPMQgcgCEBDAZwgGNYBxAJzpAAsriAvgBpiYYMGyQQhJMOJ1oEALZ1IMfADM62BrhEZdHCLgaEA2sQxJLJMAE8QBWFQDmXXlX0kM2OneAArpTO0DC4njYGdkoARhIAyhAAXk4ArAAMXt4cwHRKhGAcAXqRsL4xuNgypQY8wADuBUW4pXLeGLgAJi648dFxVbBmVMwQHMx4ns50HDn1VAC6WSRdPX2xCclOZgAsQrAAjOlLpau4ADJ0FYPW7SQaMGCJKYQATOmtyxidqnTmNUQ7t5oHknFQAHLATq4Q4RIEkMiEADM6UyAIwdmRqIBbSBt3hsBBSjBkOhsFecIJiNgAA5UV92pjYCiPvDcXd8fCiSSoTCkZT4dTUhkGd4mUdWUD2e1OUDudRSTCdgKgUKRejYEyMpK7gJSic7tgINAANamIYA2V3BiBcZONEEzAzHrBA6ikgMfqbF5DVL7d4GgnlSrVR21BpNYoa6WG429ex4UNh-oQTpgHiEP0ajDMAIcABuuGgJnN6QAdK9ozj3Vb2ja88weWSKe6MGBnbhghDebDW2UriHAWGGHVGphmtG-0bi_EE05a3dcwWiyXCOXK469Wyaxr63aFT2Diq7u2OC6D2T-dXLbvbY2LzCWxrT-fnIrmfxtzfHXv72-e0-jovp2D6wMq17wguHp3k2MJHn2wFdu-4FsvqDLTvGdiJkOdygHQoz2GuZYAJz7PYjjmH6qSBncKZphm5LukuhbFgwpatDYW6wAsqACAA3KgqDABoGi6GAiBHHxsCGAwiCgGo0BloYxgMGYxwCWJACS0BgLgBbaAAFAZACUCAAHxDsJomdgAtDZUkQBosAGVZYmwAAPLA6Sma5nYIIc6QCQYekMGWGGzlhuBlj8I4APIiW5ckJZ2QWwEodgAMI8DMYBKZ2sXgFA0AGUgykmIQMkCMZqViQAKsouCBGABkqOMPD7MKqTVbx-wHMK1VAA) should work with any type of line, not only graph links.
📌 please close issue if problem solved.
![ezgif com-optimize (2)](https://github.com/user-attachments/assets/b57086e8-00f8-485c-871a-80f6e73797cf)

**Comment by Syndlex** [comment]
@helgasoft Nice that was a quick answer:
It worked sort of... Now the Graph is not stopping to turn. :D
https://github.com/user-attachments/assets/25ad98de-e472-4f67-8ba8-29347d4e9289

Added this to the Chart: 
```js
let offset = 10;
setInterval(() =>{
  offset--; if (offset < 0) offset = 10;
  mychart.setOption({series: {lineStyle: {dashOffset: offset}}});
}, 150);
```

It also is flickering like it would render new everytime the 

Slowed the interval to 5000 the effect is show the rendering even more.
https://github.com/user-attachments/assets/32ce821a-35b5-4139-8949-224fc1b78849

**Comment by helgasoft** [comment]
The solution is very CPU/GPU intensive. Would work fine for a **limited** number of lines on a **static** chart.
But I wouldn't use it on a highly dynamic chart with lot of animation like your graph with ```layout: 'force'```.
BTW with so many lines(links) the "marching ants" effect loses its appeal.

**Comment by Syndlex** [comment]
`layout: 'force'` doen't work for me but thats okay its not a show stopper.
Thank you for your help! Maybe someone else can use this.
