### ISSUE TITLE
[Bug] Wrong order of bars on stack chart when both series have a negative value

### ISSUE THREAD

**Issue by AykutBurak** [apache/echarts#20428]
### Version

5.5.1

### Link to Minimal Reproduction

https://codepen.io/jsprocsslearner/pen/BaXRLxL

### Steps to Reproduce

- Create a chart with two bar series
- Make them stacked bar
- Assign negative values to both series

### Current Behavior

- Order of the bars are wrong

### Expected Behavior

- Order of the bars should be the same as the order of the series given

### Environment

```markdown
- OS: MacOS
- Browser: Chrome Latest
- Framework: JS
```

**Comment by helgasoft** [comment]
The "wrong" order comes from the **series' order of appearance**. 
When series' places are [switched](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=M4OQBAvGDeBQZgHYEMC2BTAXGA5CdA5sgC4CWAbujgDTxgDGA9gDaMBO2OAxAGI8Cc_ABwAmGnWIBPAA5ZcAI2RtxCYMWT0A1p2KN1zFWEVsAwiULtJAcWTTsIgAy0ExgOqkAJsQAW2AIwALM5gpMToqADKUsxycAgu7B7obO5evmB-wQlsSaYs7Jy8_ADsQgCsDjh0AL7BIADyAPrMyPLozNhx8cDejADu2MRsAK7oWWAAZuyoJGEcuNDy1YYIfZ4-2BVOdAiMlGwTrAO4Q8OI9OYrYNKMwKGkjIicpIh3SQAy6BPEVx6kashznIRON9mQLswAILMUgEJ64VCeDwxK6MCYTYDoYjYADaTjAAFo_EIALrjKaIYgRUgALzkfhBO0mj2IrnQsO82LAADYHNt4gx8vNuABmSEigIiAAiVQQtToHhIyFxTK6AvIyGYo2wBJFADpisURWVufwRX4zWUygF-A5ikz5QK1fENVq5LqDUaTWaLcbrbb7QLqnQSbBqgBuWCwYAABUgMDoKAwnBjt3ulEMTFYwq4xRMAFEhCZuYYpLJOMZDACtDo9JrDMYzGECJYbHYwI5gm51ulAsFQuEopIYp0mfJEslUhsMuNxzlkiYhYUyiYpSIAEIBWVgR1gRXqFVOpkIV3awkOPVCBz8ALlAIWhxCYncvwO8bOk-as8Xq83u8Pp8hBfB0QzDSNYEYaQyEeeMuhiAh0EQDxOl3AAPSFUP-UcBTLOQcFPKhxiTdAABV0FQqloliY9BWzQpDWKK4EBhRB0AACXZAhOXsblxhPZJwU1aFYXhHBEI8bc5XGYBpBhYh3heaiBVUXpjlOMYaJY9AhxHBNlPiLMClwLghHQIRhH4PxkCY-JcM4RUenQCSaODINxi0nSlOUwyc1M8zzKsmy7NwBzvCcySd3GZBMOAd5WnaFCamCXQWDIdtoF3SQMKwvTbJkPCLmbSwrhefZMUGEYNIFAB6ar92VMAcRwVw2EeAgwAnZRqFwRc2DYdB6GIDr52UMkx0YM5FTYaxbAq0YopihTWOw5Sen6bAJk1TE3yZaL_jitoOlygU1uOTbmG2tymRkuSlq8k7VLmqrlM1ET3B8A6ErAdS-LADyqJW_SfMKPyLMC36EGCnBQvClyQKkuhMTYUh0GAXFY260AxoQWqkZRtHGtATGYxJeJatwFq2pwYbcjAoA) you get the "correct" order:
![image](https://github.com/user-attachments/assets/a91452ba-af87-4287-b944-b20f574bb547)
📌 please close issue if problem solved.

**Comment by AykutBurak** [comment]
> The "wrong" order comes from the **series' order of appearance**. When series' places are [switched](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=M4OQBAvGDeBQZgHYEMC2BTAXGA5CdA5sgC4CWAbujgDTxgDGA9gDaMBO2OAxAGI8Cc_ABwAmGnWIBPAA5ZcAI2RtxCYMWT0A1p2KN1zFWEVsAwiULtJAcWTTsIgAy0ExgOqkAJsQAW2AIwALM5gpMToqADKUsxycAgu7B7obO5evmB-wQlsSaYs7Jy8_ADsQgCsDjh0AL7BIADyAPrMyPLozNhx8cDejADu2MRsAK7oWWAAZuyoJGEcuNDy1YYIfZ4-2BVOdAiMlGwTrAO4Q8OI9OYrYNKMwKGkjIicpIh3SQAy6BPEVx6kashznIRON9mQLswAILMUgEJ64VCeDwxK6MCYTYDoYjYADaTjAAFo_EIALrjKaIYgRUgALzkfhBO0mj2IrnQsO82LAADYHNt4gx8vNuABmSEigIiAAiVQQtToHhIyFxTK6AvIyGYo2wBJFADpisURWVufwRX4zWUygF-A5ikz5QK1fENVq5LqDUaTWaLcbrbb7QLqnQSbBqgBuWCwYAABUgMDoKAwnBjt3ulEMTFYwq4xRMAFEhCZuYYpLJOMZDACtDo9JrDMYzGECJYbHYwI5gm51ulAsFQuEopIYp0mfJEslUhsMuNxzlkiYhYUyiYpSIAEIBWVgR1gRXqFVOpkIV3awkOPVCBz8ALlAIWhxCYncvwO8bOk-as8Xq83u8Pp8hBfB0QzDSNYEYaQyEeeMuhiAh0EQDxOl3AAPSFUP-UcBTLOQcFPKhxiTdAABV0FQqloliY9BWzQpDWKK4EBhRB0AACXZAhOXsblxhPZJwU1aFYXhHBEI8bc5XGYBpBhYh3heaiBVUXpjlOMYaJY9AhxHBNlPiLMClwLghHQIRhH4PxkCY-JcM4RUenQCSaODINxi0nSlOUwyc1M8zzKsmy7NwBzvCcySd3GZBMOAd5WnaFCamCXQWDIdtoF3SQMKwvTbJkPCLmbSwrhefZMUGEYNIFAB6ar92VMAcRwVw2EeAgwAnZRqFwRc2DYdB6GIDr52UMkx0YM5FTYaxbAq0YopihTWOw5Sen6bAJk1TE3yZaL_jitoOlygU1uOTbmG2tymRkuSlq8k7VLmqrlM1ET3B8A6ErAdS-LADyqJW_SfMKPyLMC36EGCnBQvClyQKkuhMTYUh0GAXFY260AxoQWqkZRtHGtATGYxJeJatwFq2pwYbcjAoA) you get the "correct" order: ![image](https://private-user-images.githubusercontent.com/13038071/377190898-a91452ba-af87-4287-b944-b20f574bb547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDc0ODgsIm5iZiI6MTcyOTE0NzE4OCwicGF0aCI6Ii8xMzAzODA3MS8zNzcxOTA4OTgtYTkxNDUyYmEtYWY4Ny00Mjg3LWI5NDQtYjIwZjU3NGJiNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA2Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjEyMTJiYjBiY2Y5ZjY4NTY3NDY1ZGZhYzc1ZGFjNGE0NGJmYjZlMmQ1MGViY2YwZTBjY2Q3ZWU3ZGFiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dYD7x23JJ9jTUMZpdbjAO_wSQndWzNOn984DrsW3hY0) 📌 please close issue if problem solved.

unfortunately the order is still incorrect; even tough the legends are "positive" - "negative" the order of the bars are "negative" - "positive".

the correct order would respect the order of series given, which is;
it should first render "positive" if we give "positive" as the first serie item,
it should first render the "negative" if we give "negative" as the first serie item.

**Comment by helgasoft** [comment]
> unfortunately the order is still incorrect; even tough the legends are "positive" - "negative" the order of the bars are "negative" - "positive".

How do you define _the order of the bars are "negative"-"positive"_? Is it left-to-right ?
Maybe the best way to explain is to show an image or drawing of **what you expect** to see as "correct". 
I already did. The **order starts from x=0** and bars go left or right depending on the value sign.

**Comment by AykutBurak** [comment]
> How do you define _the order of the bars are "negative"-"positive"_? Is it left-to-right ? Maybe the best way to explain is to show an image or drawing of **what you expect** to see as "correct". I already did. The **order starts from x=0** and bars go left or right depending on the value sign.

I understand what you mean, yes it makes sense in that regard. I expect the order of the bars to be always left to right, which seems like an edge case.
