### ISSUE TITLE
[Feature] when symbol is svg，make the whole area of svg can trigger mouse event，not just the svg path

### ISSUE THREAD

**Issue by Xiaobaishushu25** [apache/echarts#20434]
### What problem does this feature solve?

When Symbol is SVG, only the SVG paths will generate a click event. so the User need to be precise in order to click on a node.
The area between the paths is not clickable. 
![A](https://github.com/user-attachments/assets/f44b5836-257f-4b86-99dd-058ecbc30c82)
For example，Like the SVG above, only the middle T and black border can correspond to mouse events, and the transparent area in the middle cannot be triggered.

### What does the proposed API look like?

Suggested is to augment the Symbol attributes with SymbolMask: `match` | `square`| `none`, where:

`match `will make the whole SVG clickable, tracking the outline shape perimeter
`square` will create a square clickable area around the shape perimeter
`none` (or undefined or not-set) - events will fire only when clicking the paths

**Comment by helgasoft** [comment]
> The area between the paths is not clickable.

Could you please present **SVG code** for such symbol ? I'm trying with single path and cannot reproduce - [Demo](https://echarts.apache.org/examples/en/editor.html?code=BYUwhgTgLgvABAIgLIEYAMAaAzGuBBOAJk2Lk0xTgFZMd8iTdyNKBOW3ARTnYwDZcNDOzjd0_XOLoAvBACgAzgDcA5nHhwA5AB5lagB4BbADYA7BTATAoUAA4AuAPSOA7m4B0LrO4D2EFY7EaGiOeghwSgCWIC4AQj76lkxw6JLBCAB8mnAA1HJwWtq2YFDAcABmkcbGlqY-piDhClAQPgDWIJYQIAAmTS3tIAC0LpE9pZZYtvrhPZbZOXCgkFC5WuGOGdqhqlkA3HJyPrZQkfXqcADe-XD6ePqRCvZXNwVQAJ62IM-aAMYlIBUfnemgwrzgPRKYGeAG1NEh6qCtAAVACuICRmgA6r1McjgKjMQAxCCRTEAZRKFNRpk0AF0bgBfMEFd73R7PS5wZlwKA-HzGU4OS7Mm4KECkkBPOAw8HXAoKiFQ2EoIREHAYIiEAAsmsIKAAHJqUFgqMbtQB2PUCOksxW8z7fLTGSINJHggoKd6GABGAp-kUMYBU32ckKg0MDwZAOxUOSMxj2v2AkHFsFRUHKRs0iz0mo9cGcXt9_q0xVKTkcOaW4Gg-ftcGLfuM5Mi0m-VCo4MZNwZjL2QA)

**Comment by Xiaobaishushu25** [comment]
> > The area between the paths is not clickable.
> 
> Could you please present **SVG code** for such symbol ? I'm trying with single path and cannot reproduce - [Demo](https://echarts.apache.org/examples/en/editor.html?code=BYUwhgTgLgvABAIgLIEYAMAaAzGuBBOAJk2Lk0xTgFZMd8iTdyNKBOW3ARTnYwDZcNDOzjd0_XOLoAvBACgAzgDcA5nHhwA5AB5lagB4BbADYA7BTATAoUAA4AuAPSOA7m4B0LrO4D2EFY7EaGiOeghwSgCWIC4AQj76lkxw6JLBCAB8mnAA1HJwWtq2YFDAcABmkcbGlqY-piDhClAQPgDWIJYQIAAmTS3tIAC0LpE9pZZYtvrhPZbZOXCgkFC5WuGOGdqhqlkA3HJyPrZQkfXqcADe-XD6ePqRCvZXNwVQAJ62IM-aAMYlIBUfnemgwrzgPRKYGeAG1NEh6qCtAAVACuICRmgA6r1McjgKjMQAxCCRTEAZRKFNRpk0AF0bgBfMEFd73R7PS5wZlwKA-HzGU4OS7Mm4KECkkBPOAw8HXAoKiFQ2EoIREHAYIiEAAsmsIKAAHJqUFgqMbtQB2PUCOksxW8z7fLTGSINJHggoKd6GABGAp-kUMYBU32ckKg0MDwZAOxUOSMxj2v2AkHFsFRUHKRs0iz0mo9cGcXt9_q0xVKTkcOaW4Gg-ftcGLfuM5Mi0m-VCo4MZNwZjL2QA)

Thank you very much for your demo. I learned how to use `'image://data:image/svg+xml;charset=utf8,'+ svg, ` to set up symbol.
At first, I consulted the official documentation https://echarts.apache.org/zh/option.html#series-scatter.symbol and only provided such examples `symbol:'path://xx'`  when setting up SVG. I wrote the demo according to the document [demo](https://echarts.apache.org/examples/zh/editor.html?c=scatter-simple&code=PYBwLglsB2AEC8sDeAoW6zGAG0iAXEgL4A0asAHgIIUQDO-yp5AnjfY8WenQKYBOEXg1gBtculTppsOiwC2AIxwBlCAC9ejAKwAGbjNgATAIZgTjcYemiAjLoB0-2AA4nAFgC6B66Le6AdhJYADYHAE5tbwlDOwBmJ2CAh20XaOt0UXCnbWC3F1t0jLtbRNcHOLii31t3MuSQkOrY2wT3YLCC5pk7R2cwyu6bWrK3cKafFoAmFI6HFymhzOzbXNhkxcme21K1jaWxBN044Lqpqq3hmamk-YuYnpndG9g69wCDuxzghMHLzLqujWdXGnzCx1uUy8_zEtiecymEweV1G82hyMyyV0LmC2nmmwxYjxz1xDhCaWRQzALBAWlgAHI6ABjMxgAT0y5yJQ4RgAIhAZgAFvgAPQigCy9hm7lgukFBWyUxMUocMpVMt0stgtm1z1VuulADcFQ4leqDfrNZrbABac3qgAS6uVerVrq11rtrq90oAas77e6rdqLe4far1LB5FNdHUXLAY3HDakQdiXIKptpsuSQu4mVn5rpbCEtfZknFVlM7dcXPHaqUAlNiza4nippmS-5HLVsTapskXNopvGQo4QjGXDaAo53No4aExxPq8kApEprKW9k4k2QnbSu5yZPp6q51Xtw4AuSbZEnP2q03TeFwve6tpLza9BfwrGbV2IruXEVZ9J3eFJWhLKZsnccI4WvO5Y1gbQEihSdMwqNd1lKfsfwPMlwncNUNmOe8EgCbRyQTMImwIj9pWHeNEVNWow0HBxbHGeNdF_PEXDIqtVhSXNJwKCIq1wkJ8LDew3FaAiAGFGnBXRxgTWxkm_RtQnbFJnwTWN5kQ8kUhQvS4wdOJAlNSN5BCZI1IIwzjPcFwHW0Id_yZP8VM1RsnEAkty0beNwl-WsGNI8iGKwp912LCoXBlCsImc-MvJLJL8NrdZSOHLVKhSXj-P3Q9ELGBYw3PS940vNjB13B9IN0uK4gS2jVXohM8TiNdr1CrK0O6odzICOo4hG9xfURUpt2c6zNUzOoAgCOFXJCUpK084lyK1VdVXHGUZKa44mN0xjqJlKEUkvbV_HbRKGhcbdXh4vjYDGslHvXR6UhTPKHu3O1FtnEtGgqNyxLaNSSwSiolvq19rpGEbyI_MIh2chMZhC99wmSZyMe07GQmG0bxt9OdwXGdReUuTAcDwQhCTAQQAHMWYEfB6QgNl5A5Qk6EFYAAHd8GZgBXXhLiIGJpfQTwUCIABuIA), and you can see that the tooltip cannot be triggered when the mouse is placed in a transparent area. But now with your method, it works very well.
