### ISSUE TITLE
[Feature] Disable calendar heatmap {day,month,year}Label clickable cursor

### ISSUE THREAD

**Issue by calvincramer** [apache/echarts#20437]
### What problem does this feature solve?

Duplicate of closed issue https://github.com/apache/echarts/issues/9858 

### What does the proposed API look like?

Optional similar to `xAxis.silent` but for `calendar.{day,month,year}Label.silent`

**Comment by plainheart** [comment]
As a workaround, you can refer to this [demo](https://echarts.apache.org/examples/editor.html?c=calendar-simple&code=GYVwdgxgLglg9mABAcwKZQGowE5RAQwBsARfKfACgE9V9sBKRAbwChFEIEBnKRAEzKpEAXkQBqVBAAWdKFwB0sALap5ABzpdU1WtnGIA5AFoADAEZTZg_QDcbDt16owfEeMkzcC5ao3YtOnT6xmYATEYAzFa29pxgPPz4VAAqMCpuEQBsJiaIAFSIoQAs-YhmOSZ27HEJAuRuANoAulWIwHB6FIToiD5udag2vWlCADyiznxDfWKiAikjjKzs7HX46iBcUhQN9iuIHrLeI_Lt2EpkFD4ANIZMVA9UAL5GTACyby9MfHxPBrfAIhaejXPYrN5kKSnQhwDoUCFQKHYfAuOBKCiMArlCr0MFNGLsJ72bDoEDYJBrOxEuBqWAINzLRAANxgXAIhAhagAXMwwVs4AB3HmAwhaUH7JQwMA8kzilYXAAePOxOXsTzlECIkzoPMZ7GRYDQPIMoXMAHYDGq5VpsDBUFxdWCoFQ1KhjVJaFALmp_mDOB0-FLBABlKg8VBKY2a7ouOi-_ZrHloTA4PBEUjkCgm83WNUsJ52FhKKgAYU8UHkCCzJJcqBJfH-iAxIgAfLz2MWy7IwfJk284HxUIQMT3aNIS2i1AhnFAKExEBcpckXW7DNHtdgDIh1U3OEop2AZ_3B4RGMI23qVjVeHuDzOsKgBW5O-Xe-gHwKAPLACf76dgKBjyHChb3_QCByHAl9gcP9DwAj95DHKQACVJjrVA-AoChINbdtoPYGBgCbIdFBXERhFEAwoFQBUoGsPD8PYEiuBgGNeFEKBsBAQYwX2Il8KeKDCRiQSbCAA).

**Comment by sz-p** [comment]
Add setting `calendar.{day,month,year}Label.silent` or `calendar.{day,month,year}Label. cursor ` ?

**Comment by plainheart** [comment]
@sz-p Adding a `silent` option for the label would be enough. :)
