### ISSUE TITLE
[Bug] echarts 设置主题不生效

### ISSUE THREAD

**Issue by Julycc41** [apache/echarts#20463]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/ji-ben-bu-ju-antd-5-21-5-forked-3d596c?file=%2Fdemo.js%3A7%2C52

### Steps to Reproduce

下载引入了 怎么没生效呢

### Current Behavior

初始化引入显示主题

### Expected Behavior

https://codesandbox.io/p/sandbox/ji-ben-bu-ju-antd-5-21-5-forked-3d596c?file=%2Fdemo.js%3A7%2C52

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
```diff
- const myChart = echarts.init(document.getElementById("dahs", "vintage"));
+ const myChart = echarts.init(document.getElementById("dahs"), "vintage");
```

**Comment by Julycc41** [comment]
找到了 写迷糊了我 非常感谢您的回复
