### ISSUE TITLE
添加图表库中多环形进度的椭圆支持

### ISSUE THREAD

**Issue by jinHua-96** [apache/echarts#20466]
### What problem does this feature solve?

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/a2425bdb-c3a2-4b2e-99f1-d9021d0ae9f4">

### What does the proposed API look like?

基于现阶段的多环图支持椭圆的功能

**Comment by Ovilia** [comment]
Use [custom series](https://echarts.apache.org/examples/zh/index.html#chart-type-custom) to implement your own.
