### ISSUE TITLE
[Feature] 关于饼图中负值被默认删除的问题，希望添加自定义选项

### ISSUE THREAD

**Issue by lascyb** [apache/echarts#20479]
### What problem does this feature solve?

> [Bug] 饼图，不能在没有任何提示的情况下直接筛选去除我数据中存在的负值，这会导致我想要的结果不完整 #20473

饼图默认删除了数据中的负值，且没有任何提示，删除数据的工作应该由用户自行操作，echarts只需要给出提示

### What does the proposed API look like?

提供参数，选择是否筛选掉负值，至少在默认情况下，负值不应该被默认删除

**Comment by Ovilia** [comment]
Don't open duplicated issues.
