### ISSUE TITLE
[Feature] 请问一下这种叫做什么图，可以用 echarts 实现吗？

### ISSUE THREAD

**Issue by L9m** [apache/echarts#20472]
### What problem does this feature solve?

![mastery-credit-graph](https://github.com/user-attachments/assets/00862d65-c97f-4d42-b37e-fdded3576df6)

### What does the proposed API look like?

附件中的图形可以用 echarts 实现吗？要怎么实现

**Comment by jiajiaxing1** [comment]
多个饼图嵌套+饼图扇区间隙可以试下，可以参考这个试下https://www.makeapie.cn/echarts_content/xHyh3Q7Zuf.html
