### ISSUE TITLE
[Bug] StackedLine Display Error

### ISSUE THREAD

**Issue by jiao006** [apache/echarts#20477]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-stack

### Steps to Reproduce

`option = {
  title: {
    text: 'Stacked Line'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['2023', '2024']
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      name: '2023',
      type: 'line',
      stack: 'Total',
      data: [120, 132, 101, 134, 90, 230, 210]
    },
    {
      name: '2024',
      type: 'line',
      stack: 'Total',
      data: [0,0,0,0,0,0,0]
    }
  ]
};`

using this option (the second group data is all 0) on examples page, we will see two lines overlapping.  

### Current Behavior

when unchecked the 2023 series, the line for 2024 will be correct.
![image](https://github.com/user-attachments/assets/501835e6-2965-4b5e-b66f-d5daad1dcf37)
![image](https://github.com/user-attachments/assets/ff7e7524-7eef-4b7e-9d12-e2ccd6a6fe93)

### Expected Behavior

if change the sequence of the data,the chart will be correct.
I hope the chart can display normally no matter how the order changes.

attach the correct chart
![image](https://github.com/user-attachments/assets/3d783ac6-6893-4edd-958d-9e5fd7dfa944)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
🐛 bug confirmed
Workaround - switch places of the two series - [Demo](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcyGOAHmAQOQDKYAhgMYDWOAJrADITQ7mwC-ANGgzBgWSCAJIMAJwgBzOTmkUaxCAGceAobkXRmk7emIBBNeslD0YAJ4h8scnRpgcc4NJvlB6dACNgAFd9Gk8AcRoJWAAzGix1HB9fZhcaAgBtcgBZGG9HABVA7n5HAHUWPPJ8gAtAyoAxWUrKF2bg8gBdISNYGzMNSQw7B3IANziirSSE2RwLWHSrQmgaAFsRgCYABg2AFjzbewosTmLYdVpGCnzgWiw8pfQU2gytkrfYD6_3946-JPQqF8vhW6wo2w2AGZvI8hkdHCcuDDgegLvQGNdbnFkSjnmkFgBGbYlAmQjYkrYEkmQ3YlACcHyhjIJWy6wJ6XV4AG4gA)
