### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by ZBeanDan** [apache/echarts#20474]
### Version

"echarts": "^5.5.0",

### Link to Minimal Reproduction

const option = {       title: {         text: props.title,         left: 'center',         bottom: 20       },       tooltip: {         trigger: 'item'       },              xAxis: {         type: 'category',         data: props.data?.xaxis       },       yAxis: {         type: 'value'       },       legend: {         left: 'center',         textStyle: {           color: '#000'         },         data: props.data?.legend?.slice(0, 4)       },       grid: {         left: '4%', // 调整左侧距离         containLabel: true // grid 区域是否包含坐标轴的刻度标签       },       series: props.data?.lineData?.slice(0, 4)     };

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/ac62d170-12ca-418c-be6d-e26a8b134ca1)
![image](https://github.com/user-attachments/assets/6e97a8a5-2a17-48af-97c9-fe7b9263f0a6)

点击legend配置的标题时，浏览器控制台提示如上错误

### Current Behavior

Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at LineView2.render (echarts.js?v=1c336748:33743:38)
    at Task2.progress (echarts.js?v=1c336748:20328:20)
    at Task2._doProgress (echarts.js?v=1c336748:17963:12)
    at Task2.perform (echarts.js?v=1c336748:17942:18)
    at echarts.js?v=1c336748:24024:26
    at GlobalModel2.<anonymous> (echarts.js?v=1c336748:16359:12)
    at Array.forEach (<anonymous>)
    at each (echarts.js?v=1c336748:425:9)
    at GlobalModel2.eachSeries (echarts.js?v=1c336748:16357:7)
    at renderSeries (echarts.js?v=1c336748:24015:17)
    

### Expected Behavior

正常展示，点击时不报错

### Environment

```markdown
- OS:Mac Pro
- Browser:Chrome 130.0.6723.92
- Framework:vue3
```

**Comment by ZBeanDan** [comment]
已解决

**Comment by rocketsbigfan** [comment]
铁子怎么解决的？
