### ISSUE TITLE
[Bug] 饼图，不能在没有任何提示的情况下直接筛选去除我数据中存在的负值，这会导致我想要的结果不完整

### ISSUE THREAD

**Issue by lascyb** [apache/echarts#20473]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/devbox/kz4yvk

### Steps to Reproduce

所有的值只要是负数就会存在

### Current Behavior

我司财务报表中中存在部分负利润，但是在饼图展示时直接被隐藏，这是无法接受的结果

### Expected Behavior

它可以报错，也可以令图表直接不显示，我可以人工处理含负值的数据，但是不能在没有任何提示的情况下直接筛选去除我数据中存在的负值

### Environment

```markdown
- OS: Windows 10
- Browser: Microsoft Edge 130.0.2849.68
- Framework: Vue@3.4.15
```

**Comment by lascyb** [comment]
我在 #15095 中，看到了一些这方面的更改，但是标题写的是 - 令饼图支持负值，结果却是直接筛选去除了负值

**Comment by helgasoft** [comment]
workaround - add absolute values as another data column - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNpwOSGNrQDqaIDQEYAMPt4C6Gk8ig-LHoEYC0uhhAUAPYAOYAlswHYyQDejUqAgBnAKZgAXPEGlhHALbjuorqplJuIZZkiIAbiAA2AV3GZEAJwOJiQ-aOamrAY3EyRIBwF97pMGZmY05WGTlHAAtmAHcZMCtzDAdSADNmK0VwMHErGXEYAD4BFPlIK0kXXnEAOm1lAGpEKQAeACMrSAB6QsQG2qMzcTgAJkIAbm6u_QAKfmAfAFIASkRSn2SygA10zOzcmUR-Np9Wju7C_lcfOYWVtdINh2NxAHMVYHDIJ4COMBfwqUcgAPaT6bhvcAcAwFCSuQJWUSYIHiUEAZTAAE8ASUyqRXMEMocAMQgVxksnIvGQdLcMBojgALw8-iwABZWMCHvIfL5NpAJFYOOJRJpShEyljWCzEKxhVS8fUZQBJAAKCrKVhAwA4plF-jZOEWGvkxhAbXExkB1NIrGYak4PEOzhyVhNZV2WTArsO_AAAjYfO75DsMl6fTTTNx4epIHNINK3CowCQld9lribfieE4XjVjMxXjME7l3HTUzpxMtxqVqRUwFVIGmGvpWy3E2WwJAW4hjTWs7zqYOeQ4mD5xkA).
![image](https://github.com/user-attachments/assets/be4c059a-33a8-44d6-92e0-0f17128bc18c)
📌 please close issue if problem solved.

**Comment by lascyb** [comment]
你好 @helgasoft ，感谢回复 

- 实际上我当前系统中的数据处理就和您提供的Demo中类似，也是对数据进行了预处理，使所有传入值大于等于0，并提供了额外的维度进行数据展示。
- 但是也正是因为官方api中没有提到负值，所以我才会提出这个问题
- 作为用户系统中的第三方依赖，当我的数据源是 
`data = [10,-10]` 
的时候，在用户没有明确设置删除负值的情况下，echarts不应该粗暴的删除数据中的-10
- 饼图应该基于用户给出的数据生成，而不是基于程序自行删改后的数据生成
- 所以我上面提出：饼图含负值的区域直接被隐藏，这是无法接受的结果，这和预期的结果不符，我宁愿他直接报错令饼图显示失败。
- 在会议展示的时候，如果它报错，我可以在会议前处理，但是它直接删除了我的数据，如果我检查不出来，但是领导看出来了，那就完蛋了。

不知道我描述的您是否可以理解
（ps.其实就是，不支持负值就直接报错吧，不要动用户的数据T_T）

**Comment by Ovilia** [comment]
@lascyb Negative values are not expected in Pie charts because it's meaningless to have negative pie pieces so it's natural be be filtered. If not, the total value could be not as expected. ECharts filters invalid data so that the rest can be displayed. There is no reason to print an error log and renders nothing when there is a negative value. You should be responsible for your input to make sure it's valid all the time. Otherwise, there is possibility that you get expected result with valid input before your presentation and then when in presentation, the data dynamically changed and have negative ones.

**Comment by lascyb** [comment]
@Ovilia 文档中没有任何地方提示过负值会被过滤，这种没有任何提示且不经过用户设置就直接过滤用户数据进行渲染的行为我觉得很无语

**Comment by lascyb** [comment]
> @Ovilia 文档中没有任何地方提示过负值会被过滤，这种没有任何提示且不经过用户设置就直接过滤用户数据进行渲染的行为我觉得很无语

或许含有负数的饼图毫无意义，但是总有些数据会含有负数，这个控制权应该交给用户，而不是让觉得负数无意义就把它自行删除

**Comment by lascyb** [comment]
或许含有负数的饼图毫无意义，但是总有些数据会含有负数，这个控制权应该交给用户，而不是让觉得负数无意义就把它自行删除

**Comment by lascyb** [comment]
有没有个什么东西可以发起个投票

**Comment by Ovilia** [comment]
As I explained, this is the universal behavior of ECharts. If you feel otherwise, you may make a pull request and let's discuss about it later.
