### ISSUE TITLE
[Bug] Emphasis label cannot be hidden on a funnel chart

### ISSUE THREAD

**Issue by abelykh0** [apache/echarts#20490]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=pie-simple&lang=ts&version=5.5.1&code=PYBwLglsB2AEC8sDeAoWsCmBbEALAhgM4SEBcya6sA9NQCYn4BGANhneWAE4CuGANJXQtmGFuVRUqhXMADu5AGb4WhAUKq1FwLlnxgwGLuQAUIfF3xYysfNACeASgQA-WACJ3gqem3QwAMoQAF4Y5ADMAAwaAL6UMd6walwQGDYA2hqSPiJMYhIaUjLySipqhbAJFbliADIQ0GEUPtKyCrDKqhgVVS1g9iBNAOSKPNCNLEOJUnT6-OSZLehIsABuKnzkAIyRACwAHPyw0FbDARgWAMa4sACi0ADmDRhDldM-K-ssm7AA7OEAViOJywwwAIhAuBhLmBXr0lp8Nk0AftIsDTuQhrc9BBJpUKgBdWKUIkxADcQA

### Steps to Reproduce

Create a funnel chart with hidden labels and label lines, hide the emphasis label. It still shows up.

### Current Behavior

Hover over any point, you will see the emphasis label.

### Expected Behavior

Hover over any point, you SHOULD NOT see the emphasis label.

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: N/A
```

### Any additional comments?

Workaround exists, use 
```
formatter: (params: any) => ""
```

**Comment by plainheart** [comment]
```js
emphasis: {
    label: {
       show: false
    }
}
```

**Comment by abelykh0** [comment]
In which version it is fixed?

**Comment by abelykh0** [comment]
My example has this code and it the label is showing

**Comment by plainheart** [comment]
You need to add this option under the _series_ option. [Demo](https://echarts.apache.org/examples/editor.html?c=pie-simple&lang=ts&version=5.5.1&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWwA2AhgEZY3GrXUYAWwA7sQGZ0a2KhQC-AGlHp6TGgBkI0LK2kUuvAUJHtYktVgC2ITnQwQilXTMbNV19dz6xBwrGvRi1-3WACeICqwAOT8AK7QyjTBUroAJnRgdMRkDkiwAG5CYUEAjAAMACwAHBKw0HSGQcEAylh0OADGnLAAotAA5kpYwXqx1ulZNDnEAOwAzACsZRVVxMEAIhA4WI1gvT4DmdlBk8X5M5XVrYZ0ENF6agC6ol7oN2IA3EA)
