### ISSUE TITLE
[Bug] yAxis.nameTruncate not working

### ISSUE THREAD

**Issue by FirstVertex** [apache/echarts#20501]
### Version

5.5.1

### Link to Minimal Reproduction

[Echarts playground link](https://echarts.apache.org/examples/en/editor.html?c=bar-background&code=PYBwLglsB2AEC8sDeAoWsCeBBAHhAzgFzJrqxgYgCmxA5AMYCGYVA5sAE4a0A0p6AegGxojALZUAKhwCu0Ji1j4qVMfnLARwMLABGVWADM59SDAjRWsABZUOVfiPFTZ85jRJkyYxjgDqEAAmYNbEAKx8XoLCVAA2sRAg-AR0AHTptI4AvpFkgcyMxADajui0ALIQ9NaMcbylsLQAyiwgNdAQBozQgeS2sE1y-NYWBgBC3YH1UY2SwIFTuV4VjFzTUbQASlU1HIsNtJLWwD7qIQbSjBbrywAyGNDQN2RbwKx2z2UAIhDdVJ-NcqrADWmS8AF1SDlSDhcClPGRfARJFVgcRUDNhsAAO7EQyMWLKbJLWBI_C3UbohpY3FGAlErzQrwUah0ABuBJk_yhuWUHE6RFgJS8GKiEBYYhaGFiHlFM10nECdk2jECEBkgqKAAYeLAAMy6g2wLWQmZMqL5MCFIUNdBymawDmxLnEACcACYSTNxaopTKqQ6ovRgLFOAHA1EWR5aAloFRVgDAzhiDrbQ6MCmvRGcO7iABGLOBjC542Fh3B0McFqgTVpwP2iNRYCGQzKMCZusRithxocVi6RgACgAbDw8wB2HgADknWtSroAlGDG1FzSuyA317Bm62qO3YAXO4Huxw6H2B4O8wAWHh60d592jueL5db2BZI9kcFlmasUMD2I8XpBx1w_RswIdNcok3LwnRdA88wNTsfUlCh_QRRsT3DdcozoWN4w4RMHWTUtP3QDNSLfHN8x_KJiw7N8T2rJJijIjc2K8Hc2wYt8yCw3t-yHe9JxnHhnyXDj31omYYJXLi9xoyT0H42hzyHa9b3vR8xPnCTePfNjvzYv9gAAoDCRAlcIMDazVzLWT0DgjwwldWiUL9WVP34hzI0oaN8ITaSyBI1M3wo0Kt2og8gvIksIvXJiwBrVj9J8wN5P3eLeJUtSRzHETZ1018tyg9c0odDLFP05SQx7VTBMvG87zHbTxOK0DDJi2ATLMukLM_WyzTTUr2MbJz8zCQ9G3ctDPIS2rTwwldcMaALCK6kKuvCjaSymrd6MordEuSm1UqU7cW24w79JyhrhOnQqX0kkbG3KmZKui87bovDTmofJ8iuezrjP_AlzIZKzO0GsgXqWmZxtgcc9sDGbpTmldvLYlaY1GQK2M2tjtvx3atrirrjpY07eLeptLoU67soWs87vyh6dKe_TYfrc6PuRxnK2Zn6mq0gGOd46HAyMt8erBvqIfAqHhvszsEbzLUkOmiUPOwrsmbhiNsbWoiZgJsKePXKK-cbA6sswhbmNrM7qou3dMq6rxvqE1nRLa573f19def9mqBYEoXNJa0W9PF4HpdBwC5cshXk8g5Wxs5DwHxvZCtdmnXjz1mnDdx9b8fNlciaoknCbJtiKcd6mebpt2vr1-qL3un3Ac5_2ac45uquqz3Goj_72ejt8JYdKWtxlhP8X6jqU7NNOI1VvUNYjVH0PKzG32LuM8ao8vrZP7Nq7C2vGPtpLKeFRvnY-22jrb3LO8eieSt7pvXcHm7X4ar9EW492qQzfDPdcc9wZJwjFPdAU9YY-QRsOKcblc5o3zuWQuWM_J4RLsbKIpt9pnyTBffaV8X6VgdilB-1Un7B1gMPd-IC_aST7mQIOrdQ7t3UsLSOLDOax1nvHaBA1FY2VXoGBGrps6a19HnAOQZsH71watfBG0SHpk0SbMh64bbkxvide-b52HoHoVwuqb9vYf1AeBb-j8B6fWdsPIB_DfaCPAV1KBicxHL1XA0CBZBsYDkItkUgM8kohkgCAHWYB-SsHeItWgZJnhkgAArAAsCwRam5sbDFVDiYqUFgzQEMJScgshLLmhlO8HoOsaTQJJChAAElQCArBrD7gfE0kpZ5gByECJsKgphngsBwGAbW-sFR7GVKqdUgp3TEkcLfOgCowBJTEM8EAqo1SWBTFCFAWQADcQA)

### Steps to Reproduce

1. Visit above playground link with small-ish viewport so the y axis labels will be truncated.  (or use horizontal slider in playground to make chart viewport narrow)
2. on yAxis with type: 'category', see the usage of `nameTruncate` option.
3. notice it is not functioning as described in the documentation

### Current Behavior

The label was not truncated according to the maxWidth input.  When the label is long, only the last few characters are visible, which is an awkward way to identify the data.

### Expected Behavior

Expect `nameTruncate` option to work [as described in the docs](https://echarts.apache.org/en/option.html#yAxis.nameTruncate).
Expect that it should show `nameTruncate.maxWidth` characters, and if the string is longer, it should show the ellipsis.  This way, the user will be able to read the *first* part of the name, which they will more easily recognize than the *last* part of the name.

### Environment

```markdown
This is reproducible in the live echarts playground.  See attached link.
```

### Any additional comments?

Thank you.  Much love for echarts ❤️

**Comment by helgasoft** [comment]
not-a-bug, _nameTruncate_ is for the axis name, which you don't even have.
What you want is [yAxis.axisLabel.overflow](https://echarts.apache.org/en/option.html#yAxis.axisLabel.overflow) - [Demo](https://echarts.apache.org/examples/en/editor.html?c=bar-background&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXEgMYxgCGE0AMmQEYCmANvmFgK70C-ANGrAJ4BBAB4QAzvmR90YfiHqSA5ETJh6GYFn6Le6dGVFiaDZsmAA3elgBmjYAHd8i1m2gq1O2PbxgAFvgB2AJ5pWFxVMkkAbVD0RQBZCCJfMiYdWNhFAGU1EBToCHpYMmhcWD8irNcxX0oigCES3HS9PUUAFWBcZt1WzPiyLRa-xQAlJJSsHoyO32AAWzIxct8i9qwKaGHWxSp-aC3endHgDCtttoARCBL6C7iBrABrRVCAXT4Q9GERcUlUVoGcTtJJPf4ZGoOSTWMiMMT0UJfPRAox1cF9WCQxywGFwhGtJEyOQKTLmWEcV7oJHwnD0CSwGKtAF9CBqeY5fiMEnMjG0TS4KyjMi4CBselRAAM3FgAGZpXLYBKPhjCXpwuRohl0DyMbAyYwOJIAJwAJiOutZ9HZsi56N1rRIdiwdvtrVk8iUjDqg3uruEkilWt1_AD5tdsGEJskAEYw67-FHFXH7Y7NDlQOKg_adeHWsBrNZ4WBQ1nXannZksBhaGQABQANm40YC3AAHC2JQA6I0ASkpuYJyddOYHsHzhfoxdgsdLKeATqUVZrtejABZuDLG9GTY2u73-6PYJxZ3o3kOMRg7DXTLj4Sfj-GH7rVUzS_rDdPo3LS5brZzuSe5Yurm7okooXrQPQPrnn0_pJie6AhvBh6RjGMGtAmJaHuW6YgJmh7aghfTjkWWEEegQGVtWdZbi27bcHufZEVS6F9COA4kZOaHMXolGKEudZrhuW47gx3ZMeRT4DmeRGXsA17QrCd4DlJz5Bi-ejsXo74kgArEaMG_hytpSAOlFaRioGet6WC-vacGBoeSGOaOqHTqxiGJi5ZnzmmYAZpq5EWa6nFTt5BF8QJDZNnRHbiQeo4aeGwX2qF3HkRRvkVvx1Eruum5NqJjEJSpREyYeckKTiSn4rmqkqupQ7BTpMa6TO4ZGTaAE-QupmjlZmQQVBtkeRGZEDs5o1ue1o6Ycho44f5eGBQRKW6ml83kZFuW0W2cX7jxSXDjx6AbTNW1ZYuuVCQV267vFh1laNlWwopeL3qW9V6EdzXkiSATnRabLGd1ubmURA3gTZdm6g5o2TUR03w15o2LQFDI8WtGIbeF2GXVRy67fRxWHaNhEZWOBake5J2wNty43SJ90HZJT2yVer3Ve9pWPo1Qa_QaJLRhK34dcDXXAXOvVY-UxLWZB0GI-NuYIyhiaA-Gc242WWW4fhq20zjZO8fjOWEzFe1iSzBFHdmhtU1xNMU_Tgn5UzVsSTbbMVRzN41R9vP2j9b5_TGJrrj-4v_pLurg4ekNDYrKHK5rKd-uryNp1Lfno4yBsU0btMu9FzaWyTknGzLeYO1OGsLabUWM4VzOe4eX32uVo4vX73N1Z9fN2-GLXTjKouup10d9eGcf9XLg3Q1NWfBkvGJI0RWuo7rS364eVd6IXzsNztFvEw9FeY_bE618bmW9WbrvCc3HslX3h6dwO3dvcpr-uu3R5NSHQWkh6ytkMlHEya0Z4DgTgvJWm0VYr1ghndeKMiJo2WhjIKl9qbax6poK65tS6n2tm3Su2DHZ1zwdlRubsn7ly9m_Z6vsv61UDr_AeuoBYfiNBHMWVoQYxwxFAkCc8oYKxGnA3By94HhjXk5VBeMnR6xWrvchYUb50yPoQ2Kz9SYXwLjXdKGVi5Nzuro1mjD2byU5reVh7C2ENQxO_PQkMay2URHwTu_l5yQBAMBVgEAMBnGyiiC4KIAAKwBKBqArCOSGNRhQOASqqEg0BrBonKOwWqx5OAAG4gA)
📌 please close issue if problem solved.

**Comment by FirstVertex** [comment]
Sorry I didn't know about that option!  Thank you for the explanation.  Have a niiiiiice day 😃
