### ISSUE TITLE
[Feature] Scatter with Marginal Histogram

### ISSUE THREAD

**Issue by humphreylee** [apache/echarts#20519]
### What problem does this feature solve?

It presents an integrated presentation of data - scatter plot with marginal histogram. Examples from other application are below.
- [Matplotlib](https://matplotlib.org/stable/gallery/lines_bars_and_markers/scatter_hist.html)
- [Matlab](https://www.mathworks.com/help/stats/[scatterhist](https://www.mathworks.com/help/stats/scatterhist.html).html)
- [R ggplot2](https://stackoverflow.com/questions/8545035/scatterplot-with-marginal-histograms-in-ggplot2)

### What does the proposed API look like?

Both scatter and histogram as already in place.  The question is how to integrate them in single display.

**Comment by MatthiasMert** [comment]
https://github.com/ecomfe/echarts-stat?tab=readme-ov-file#histogram

**Comment by humphreylee** [comment]
Thanks! The example looks almost perfect. I'm just wondering if the histogram can be made smaller—essentially more "marginal" in comparison to the scatter plot.

**Comment by humphreylee** [comment]
Thank you for the quick response. I’ll give it a try.
