### ISSUE TITLE
[Bug] 官网模拟迁徙示例5.1.0版本以上报错，无法正常查看

### ISSUE THREAD

**Issue by tseking** [apache/echarts#20510]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=geo-lines&version=5.1.0

### Steps to Reproduce

![Snipaste_2024-11-13_17-49-00](https://github.com/user-attachments/assets/006e20ff-6ce4-4aba-8787-380dd2df84d1)

### Current Behavior

官网模拟迁徙示例在5.1.0及以上版本查看报错，在5.1.0及以下版本查看显示异常。

5.0.2版本：
![Snipaste_2024-11-13_17-53-22](https://github.com/user-attachments/assets/b9b610b3-7d07-4add-8dc5-a57962302182)

最新版本：
![image](https://github.com/user-attachments/assets/daf6e065-d4a0-4d83-92d0-74cda859c91d)

### Expected Behavior

期望正常显示

### Environment

```markdown
- Browser: Chrome 版本 130.0.6723.117（正式版本） （64 位）
```

**Comment by helgasoft** [comment]
not-a-bug, this ought to be a legacy example, it isn't in the [official list](https://echarts.apache.org/examples/en/index.html#chart-type-map).
Even for Version 5.0.2 the map isn't there. Map [china](https://github.com/apache/echarts/blob/18f8ea3aba11bb533885d2ed3b817d8da455602a/test/data/map/js/china.js) has been moved out of the official distribution long ago (says 4 years).
AFAIK the only map currently included is 'world'. See for yourself by replacing 'china' with 'world' in _geo.map_.
GeoJson map of China exists in the repo though and could be loaded  - [Demo](https://echarts.apache.org/examples/en/editor.html?c=geo-lines&version=5.1.0&code=CQOg5gpgLgUgygeQHIAoBQACDByAFlKABwGcAuAenIGMATAOxACtiaIAbASwDcAnEO6OTC5yAQ0KiquCOQhTRPKMQACAW1HEoEHuS2byNUVFHl1hcswD2darg51RTYtewAaTBgBmAVzpUoHNYYKFL2ogDiEJbwyACUGADeHlhyuApKIDwQYBya2gCy4ijYoQ5uGKURUTFIsQDcyRhcChiQlgDClpY8NIWEGAC8iY1YgFBygO62pBgA2gCMAEyzIAAsAGzLAByuGADMS_MbAJyzALruWBcYgDhygHnBU3OzOyBHAKw72_PzIIcADKfnl2ugFIQ-6zWYbEAAdh-kPeu0hIBeL0eZxGGEAtHKARx1QY8Vp9Dh8vstIRtUYCMIAWOUAfjY4pbEjZwnarECzVazF5kwEUwBBNjiIXtwdsdi8QPNDkzOZdAJxyV1B82WiOWs22yx-eOW80lF0AvHKAFhscYdEet5h8IeCXsstVhADJygECcwAU5oAFfPuGwRh3mTJVTxeGwZVowgG15bEzMFfV4vD5PWY_Q6Q_2AXflAFnaOJFP02W12hpjm39gAdFQB7uqCft7fsrdsydmmdv7AKDKgBZNHFqnZrSEqulHQ7-wDoyoAauRxzOWSLLqtFb07AMuXcmIZjID2yw-S1Wi3-aMA6sp9kPg54_ZdCpbun6kicXNeAQO0ixDiQSMB6WezNSesGvADBm_ZAPzTq1NIFWqx21ZPhga6AFgJcpLNGHpCl8rLzByQGAGXKgAXqXyLKrEcHwKusJL-oAD8qFiGiwssKcIHL-6HHmigAQKoApQE4giYrQR-PqruSgA-KoAMSqAJa2gCeTrSKwLAuGAjsspb-oAHSqAMxpl4CXsQoKq6u7-oAEyqACg6gAXdnKboUSqIpMpR5KAAiqwYPFekJ_kKhrofMqz-oAkGqAC6KcpqscSJCmq_4Wv6gDkmoAMCo4k8JIWpZO7Cj5gB78XKXyfIxmYrKq45ooAlJqAKS29F4rMN47IaSpHP6gBUmoA-co4l8AEvCa8LfEqgFooAgFrTnMRGHJsFU7Aijziv6Z6AEc24GIocqytreVlrLZQGALnagCEeUW7UbDZ8lzssAH-oA_dqAIPxqFIsKQqBZCkLwWigAcegRDw5RajJLEic3-oA_nonWC3rRkNd6LAN_qAFN6gBS6u-5VltlzExv6gBveoAkdpFoa0blUKA5wY-aKAAT6gBt2oAx8opiyxJDSOGzlXGQGAAn692zAi5VHgtOw2QZgKAO36hPMuhPpCgxT3-oABwaE1h8xppGaHEv6gAIRoAvwlFk8hzld-uxquZRP-oANkaEzlqxvExGywf6gD-RlT6UvPtmN0jCB3koAk0aABQh9zHCyGyK-56OK_6gAHpoAhKnOYtGr7oiOP-oAp6aAOaOBqiiS4vCoiPwev6gBgZoAcGZFl8xyHDecErH-NXkoAtuby4ieykYarqwv6gDF5oAIXrpeTjIKe6Y1ooAz-b3bObVx5h3x7ZaQGAFQWgBMtgFGfzM9CLFpl_qAGbWgCSNjiCo7EcgceculOXIAqjYNlu7WrO63PNj8BuAoA-jYoVuXz_oKt4wZszdooAETbSYRUYehmGososFfkoA5Ta088ByBxCixpv6gDNNoACXaj98Im3NYyfH9IASZtCb8k-BmBOYJeZAUAA82YNF4fhskJJkzFWT-gQfdTmzFLZMSRHBf0gA5WzXOldkc1obPGhKxQEJCLxbmZHNAhuw9JtQ3pccYqMtxNiOHCTKzxkQP0BIAEdtABayqhYskI_p013CfckgA722QaZb43cdorGLIlckgBH20AMzqADzoRkPoqbK_pACgdoAHfiSqAP2g3cm7p_SAEo7XBapRIwIRCrfuQFAC0duQmchoA7oNTGKbRgJABqdunS2pMJZQhJHDckgANO0ALb2NjzrxwRNCfa_p1KE08UTdBCJRL_n9IAWXtvpbizMcDMGDyoKMBIAfYdcLO1hLGRmiIFgzwuIASOdABVdkWA8ewKp3l9IcLpWBAAHzg1B6UJKzGM-PeJE_pAALboAOfVnafGbBopEe1_SAA23QAZKl9WalQ4SSw0yiX9IAZ_dEZFy3AqUSoshRmk_CIy4gB4z3ToOJaHwRTulAUBQAZ56AHC3QA2Tp-0WPNYSaoQ7k39IAWb8nKETVC8dYHxAmos4RcQAUgHrK3H81kQ0MGqjhUBQA4QGADC9GxCwra3m9HNBJgJAD4QSZBY0UkRZTVJs-plxADzQa438yIspLGynlICgBG4MADlB6VFZQowd3WYPKLiAHngwAvzZo2XH8IUIpOba39ECHhjUiR7HFiJMUuM0SAGsQwAZUHguRSybWxiRza3GRgQAhhH6nxc8BkNTMmsjoZcQARhGQN_NjUiEJLZ_n9IAf0jGFzD-Jo8e1C5owhjSo6MENYILU5l_ICgBWWIvvGumcdhnMnMtdIC4VACJcoAejs_aCRqQqIh_pABFCc0-5O4ZHtIOIsf0gB6hMAB8JACMbGNqWFICgBFhMJk8UajbfweiVVgQAQImqUAFiagB60xkrGLZcV5Sun9IAWcSqUzkyWOa2mVc1okAIuJgA5ZWdp-Nq6KWQh1dYAHZTAC7uuDD82VGQikyvAtEgA3lM_TOCsPp34sj2lirAgBxVM3n7Yk_43axhDv6QA_qmAFIzOUIoVbBWEgqOCGxF0YDQ4ATJtO5HigreD-qLXVocAN02NjLZwWocSNY_pJJgM7hjGpEIYzIn9IAJXS7WNTcYrWRc42rJ0BIAN_TADOip3SEA0hLyihC-k4jQAC-DRLjNB4BgAAQjAAAIkYUQgwZhommAkDADhVAQCmNgXs2AMCae2DZuzDmcATHKM0Ng3gvOi1c_6aztnRD2cc851z7mwsRZwHdXzoh_OBZ-MFoCoXPORZ7C5tziRYteewN5cKiXktTA2KlzTIWPPhYK1F3L1W4vYHPCVgLUxoRpasw12r2Xot5cyzgV8LWvOrAq1V_LWWcsxf69gE2Q2pgvFG-lrrE3evLZwJhub0KOvkgyzVlb9Xxs4HrJtys23AS7ca3Vqbe2cBHs25zM7lwLvdcm31m72BjqbejMFxoJwdMXD0xgOAAAJUzxgLPTE64d7APnVvQ-O9sPzrWMBBcq0t6HsODvTcjpt34j2LjPcc5j67jWEuI6S8j8r-OsCE-8-MV7a3sBTs2-1tHUPpvE7e41jb5PSsYBG9TmYjPOeM7u7z5HC3Be05h_TuH02yObdVFL4Xsusfvec-Lrzp22c7ZVwz6HMp7uLfZ-9kX0OitfdG79_7WBAfhAAFpg_M0MSHuvocJbl-9z5uOXjK_d_mfX02iq4-N276bHu1fc4w5tqnOvzuM4jyTgrYumgU686zsb4eA-e8a9GkGm2Bdx6ewn7PkeCuC025LovBOS-B_e59zXUwlfV5p7XnPL3G8Sz91nuvl36ed4ey3oX_ve8Fe4Zbn7lw_uNEB4QNgogBAAAUjC4EGGibAEgoC4AoOQfIRN14fm_I8bcmcuAAFojijmWGwM_exDSHDP58JYSnDhsBhbCR_R5D87CoCixYF-sJlxH86YxQz8Fhn8Boz9_xvg2QwCiJRJZgqBb8EQAJ5gz8mx14oCHkqEME5oH9oCBplRwCVhjg38PxYRXBOY-N_wb879vhKCiIX8uBL84Jr8AImwlowDtZRRfQ2AFhRQk15QRUjwb9HgHlRJXB3Rvg9gyC3hlRb5ixr8iY_04Iz9b5jhIQ-D9o74Ix1CiZZC9g1CvhFDRDmx4oH8pDxRZg-Dopx5H8lQ5wjwAAZffVMI_PYfkR4AAL2wBt1T30yoGsC4G0CgCdwsx8D8ACCCBQEMGMHiCSHJEByyGIAh2n3JE8G6GCEBw4Asx-DqAwByIAB4MBYjHA2AIA6AwAt98iOAABqWo-ItEW3FoUogASS0FUAs1KOmA4DSPJH8K8B4EsFUE6G6BoAszaFGJ6D6GmDaI6OmB-BOH4Bqz6MSJaCgA6C6B6AmKiCmN6HEFmLM3aIgFUDmCWM81WMBA4E8GCE8CGJGK2PGIADIniMANi9jGj-iLhkiQBCBvBiBcAUAEiviLg7jhikAbs5iTiFjziasgJyQNiIS4soTTjThlj7N4TARAixiyAZgwSHixjth3jHiNMQTXN6gmjXM0RNM0QsgoBvAeA6AMBki_DtMZ8WhAi2BMiXdsAABiUQVYKgIjKgcoPkzwTwUQEOeYUU3ktYAAIwgAgEOGwEuMB2IG0A4AgBSJd0uNd3Oyc2y22CMydxCxl3KBBxNPS2wDJwwAdxNN-xAAyJ4AAFFJBASIj_BAgmSUAOAOjtgOBPjAR1SeBNTiBfj_jATKTgSvj-tfToTFiMBaicAMAAAVSwQgaMNwSkrAKAAAT0IAK04AEGICzLJK8PKOCLYCmGVGzIwAgHFLkCgCmGjJBIBMsAAHcpgoAeAAtMTLgCyQzLAaAphvxaycyeBRAOA2AnCKiqjt8MBJY-yLhOTuhHNeTxTPBSyySMBiBczVA5TLA2A4AOAvCtday3NayiyIA4A8zyjmyxzbNuh1AqzhhtzlzDzVyKgPyeAej_Qvj2yOAaAt8pgfglzLgqAGTgjizcSuUHyaSySLyyTSiphAi6BgjFAncfT5jThYhKTEL-iWzyRYz5iEykyXM0yMyfgtyvi8yCzHMrySylzyyIBKypgTRazdz9zDz7hsA6BrAIBRSFAhj2yVSlzOKDyjyTyvNowlz6zPBGz7y3y2zOy3ieyIAwKMABzAhhz-cNLuzJzpzZzgKFyNLxLuLNL58l8V9TK9yJLjzTzqyXhzylyrybzcy7zXztyVyeAULvzfyNKAKgL5yay3z0zJBfTcyQLfwNKIKeAoKtSYLRRnLazkKvy0KQjMK4zUSThcKvj8LyRCLARiL4yThEzkyKLMylzaKCs5LGy4AqAjAtAeBqL-jsSegwgtA4Bcy8hVBHM2gWryRmLWLbwlyQzCA58IBnSGz_BFLty5SeyASUz8yCtNAhiABrAS5Ksk-fBUl8wq8kZSrstSjSwgSwYgX0r0xzEM4QKAAa_op09QAgbQRzBIOUzTbALa1s2yw8-yrzD0qI70vzQMskukhkpkvzaYTUDAcgDADYPw8kfK_orKtyjy_arE783yrkn83oz6r41KrKs4kAMwFAf6r04IFE4GkE0Gxkzyt8_rFEwmzzDS5ovnSYx4mYhmtEi4kAVChqqAFAQ44wY47KkAJHCAHKuC-GwETTXK_o-CwECky4GWvw9MgGizQquUyQNasAIY3wGgToLGtc1UZYUQF4ZUoCAIKAVGykrQAADybJwEAEIrQAfaM1pABM_TuqwGIG8DlLtoduwEAAdTQAO2NAB6v0AD0dQALTDAAQ809owHKM8H9qoAqKatjr9pRq8zRqwG8rXI3I-ryupItq6DYACEIFmoROusgB8pwCyrzulqAnKMgDoB0rRu6E1LoH9vQoCAarYFTvTMcwPIIGGNjvjv9uuvwFjtSumANNTPTMqrpxnsotFLugXszL_LeIgHtvTrLtaoxpwHXPFNroRsxPVPKP8AgF6CHJWvsDAHKMPouERqwDaG3suDMEc0qGHtEF2ufqDNwA7KmAlLYHVLwsxKGPCyOt7MpORtvIztrIUAgFEANs_L5JLioE2FjqwAPJ6G0EQarr5ONtNuVOAcpJOMIDSHOtxMzrjs_vYG_oOt_pUu7IC1xqRo6K3tppBLgYQd3r5PmFEAAh2BoDvoRrwoLrRGDNDKmHEa1K0z8NUFzPaDSEUBAHVKgAQEIABpQFVq9MVqpPqCAA).
📌 please close issue if problem solved.

**Comment by tseking** [comment]
好的，感谢！我是从series-lines.effect配置中进入此示例的，建议替换地址或移除。
![image](https://github.com/user-attachments/assets/0b061f1f-2c2d-4712-91f3-5f5640523015)
