### ISSUE TITLE
[Bug] 中国地图 右下角缩略图中 南海诸岛 边界九段线的问题

### ISSUE THREAD

**Issue by caiyan1121** [apache/echarts#20539]
### Version

5.4.3

### Link to Minimal Reproduction

/

### Steps to Reproduce

使用echarts 绘制中国地图的时候，右下角缩略图中南海诸岛只有9段，现在应为10段，是否可以加入第十段线，或者有什么可以修改缩略图的方案吗？

### Current Behavior

![image](https://github.com/user-attachments/assets/f6b287d6-83c2-460c-ba56-a3212b5fe678)

### Expected Behavior

南海诸岛 缩略图显示边界十段线

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
你的地图数据自带南海诸岛数据，可修改 map name 'china' 为其他名称如 `China` 去除自带的右下角简版南海诸岛。

**Comment by XingKai04** [comment]
+1保留右下角南海诸岛10线 有什么办法
