### ISSUE TITLE
[Feature] Add support to directly render react components in tooltip

### ISSUE THREAD

**Issue by Abdullahiqbal2021** [apache/echarts#20544]
### What problem does this feature solve?

```
import { Link } from "react-router-dom";

const options = {
    tooltip: {
            trigger: "item",
            enterable: true,
            formatter: (params) => {
                const { value, name } = params as { value: number; name: string };
                return <Link to={'/'}> Navigate </Link>
            },
        },
}
```

I want to directly use the react component in tooltip but it don't work
I also tried this
`return renderToString(<Link to={"/"}> Navigate </Link>);`

### What does the proposed API look like?

I want that tooltip can render any custom component that we pass

**Comment by plainheart** [comment]
I don't think this should be a feature that ECharts needs to support. You can consider getting the DOM element rendered by the react component and returning it to the tooltip formatter of ECharts.

**Comment by iamcrisb** [comment]
@plainheart solution should be the standard way of doing this for everyone doing framerwork wrappers.
