### ISSUE TITLE
[Feature] 有没有这种根据海拔高度显示温度的图

### ISSUE THREAD

**Issue by liyaxin58** [apache/echarts#20555]
### What problem does this feature solve?

![a0a95da133fc29ec454b767ebfa784b](https://github.com/user-attachments/assets/186caa3a-5df0-4077-b0fa-349192b287eb)

### What does the proposed API look like?

![a0a95da133fc29ec454b767ebfa784b](https://github.com/user-attachments/assets/01de9ef7-cbbf-4248-88e1-ced3bb5b249c)
想要根据海拔高度显示温度的图

**Comment by cmingxu** [comment]
I am looking for this too, or does echarts support customize into any chart into this ?

**Comment by MatthiasMert** [comment]
[This](https://echarts.apache.org/examples/en/editor.html?c=heatmap-large&code=DYUwLgBAdg9glgZxBAvBA5uAcvJAJEYABxACcAKASgG4AoUSADwBEBDMV1CAbQF06GEAJ5sOXPnViIQAOiQgAJuQCy7ABYzSrKApgBbKjXrgIYOHuRpRs2AHcqdAGYBXKAGMzMKBhBQy7EFFWcjA1cFYAGgg9OCgovVZGSggAb1oICEEFdk40CXSIRxhSCHJBOC4ABmoICoAeNAAWSuragGo25LSMjKKSspMAKyqa4YaIACYW0Y6ugp6IAHpFzJNGLnIE9YBaaNjkgCpapcmWiDa9qDoFjOXVyCENrYhdmKhDiGGVgEYzi7frjdshwZERnAg1ORuHAosMouRyFIkKCyMBYhNyBUVs1YScpskLpUZABWD6NUnnb7E3hGG5LFbA1ig8GQ6GwqKwUgJYDMRBgEJhDhRJIQI6c7m8hD80LhKJCSg0wEZAC-8wgLByzIhiJAtgg1hC5hAlBkYBgAEkAMoAeUtYFIsXQhiVpiN5zQvzORwAbJVRRBfYDVb1iqVBMM0K0xhBPTNOqk1SJNWDtapQpoYK4lIMDgBmSoHInfSiLX60iDBiCkcDOUjeRl0VVZHJcTB-LRgQI5cgTKLbYlRUl0NxeBAwUAyYAwJ1JjiUWgwIiebxobqmGDjsxEABcqWVEQKjAAgoxELu1xkwEISLuAORuALoYpCW8HhaM3cajgFfcFIQns8EwWK8bwge9H2fV81Q_YQgh_N8IAAN0QZxWGAVQdyAno3l3KkEIyLZd19fCIAfYA3GcYBWAAI1AXd7WcEASOrNCzAsXdHDQpASNiAAlbRMHPNUMhHKdSF3bhhJ6W8AGJc2-XNvQATmJKC6QyWTyQAdmJajGjU9TZK0xpWAUBRvgMulZJohQlJAJTLJuWSQEqRxc0cAAORyFlkxw_McajHG86SZMcEAXKUypgo00LshAb0LJInzQsab0FEaXNorAmSFC0_MJi0rLrOJFoJm9W8pN4NVfwWB10DUMBdxKkjqJgMAzT0IjKh4zs9AAdTgBRQl3fMepAPQCDgerGogErKnggokAdEAEAktULx6KBWHYsCAHFWHBBA4G0YKQJAO8wnYBIiGCmDGSSiBxqINRWCO1asLpOBertIQ6I-9TWtIBQyAAYXHYo7zk3NMoehZAeB0gBqGtRcKklUpJqm4iFIadqwQI7EPOmMWm6qTtHMdg4C8DiuJAaqCiq5U6GWFnWbZ9mOc5rnuZ57naDuEhSDRbwkWQMJiDIQocb0CAGrAIhVuWdAvrUZxqJkEc9EWQYYCQZ70EWUXBgQfnebN82Lct1naBcdxlx8MAcGkAgJYoOYRKo_GIF2rQFH-kcoClUhnA8YpyEYOUogAL3dm5QkQGR1jQRgXUvNQE8eNAhFT0x04QGQo64KOXUrDJdDADEI-EWPaprOtc4T9YjnWC54_zx4jmz-n3za3Nw8jiAY_-jJqzAWtvDbxP_Rbhv2_9R5W7zgv_WL7uKwKAOpQwX3c3ENU_D1H3TPIb4olPiBKkoEiD-933yG2c_z8v6_dVv4_z4fqJn_31-j6UT-XhPyvj_Q-d8n5n2AQsG-f977gJjJAzav8wFfz7MWF-oDj4AO6oAhBGRoF32wY_XB0AkHH2wQAtBIC35KEIag4h-CyGoLoQzQEm9IBED3gsKkj9iIxlzFpKISlz6RTPgOPhj9cxRCmMIsRSlvSDkkTGJSjQpHQyiAIyYEwxHfBxGqRSZ9KiKNGgGJSZ9Gi9ggB5QRpiID8KkTiSYj9sETEUd8ERAYzFWMmI0DR3wpgkRcSoiAOkUGTHkUojR3oLHKKkcSCxEw3FSMMWfb4GjczaPPrmCxxJfFaTSZItUHkvEuN8Y0GxxJwkeVyUE_xMYtFn30TGLSPCvHei8aksRxkz7ek6afNUCkgkKRsY0YpvjvThLyWY8JVJinySiB5Vx3xz4TAmDYvxFjeEJIkQUhYLjnG1N-LIixjRz7EjEalex5znGNEGZUCxOjFHEiCT02JURvSuISiRZZ3xKnYLykkmxWlplZLPlUpJXiPJrPacpJJhC5ENO0aNfpPzQXtOJDYjy0zvS3MIZUNZSl2n_JjJiqIijsWDniakqRZVYmky4RMQZLjBxJIsbmdpPiUntJpZMM58yLEeTEQk-JlQNFTHCei6lAi1QcpjOKwloL7mQqkV48x1LXELLPlpZxCkUk2IZWi-JUQblfKed0xRWrqWP2JK4yoVrtHeg0RlTV0Sz6rOpaSvV1qz42IJV8yo7TfjqLWTqzRNSQVNPaQKlJ9zKg1O-MUi5EAlKiomMU4kmSVFqgZfcpSiiXHFMDTGY1dTvWPy0msqJ9jz4eVOY_ckqjBVlLMQE3MayRVGvxZSoJcziWPyUm26ZOTQVBI8jU2Nmrpl4TqX0hYzUID1rqY60RzjTV8NmeEqYsi80rJSc80VeqglaXiU6_pJzXXtJUuo1pG6p2fJjBU0F80Mj8AKHcAAKjAKs40YCE1zsgPwihCihliMDdYtgtBECII6KIug1agD_RAQWehnAcHthwWiyBQBQHQKEAoggkNcBvkeUgWghDkHTRMcsgh0C-wAAqEdfsR0j5G_HlnfXnWoCAoC3kgJwQmpBHhPhgH7eQChHSFFcB4KmcQIDURQ7USAthigAGsEAQBgMpmQEBzSQAQM4SDxQwBqYmAAPR-a-hkcA_JkF8Lp8KftEJoUYvnCAfUHSdggGOCw8dsOyfAJ2EoVnhCZhIYBvQxRkCifzgUW2UmvCefs-QUTNdaiOFKKJiAAA-C-EAABkuWEuAbqPA4e9IICWjIsgGUhW_aZjAFJDLBw0A9Otd6EuaoMtoDTBoRwU4w7JZdEFpL9mIDFa0d6FLGQMsAB80AZbqMVjy7WFh9DDCYCokYaj1B5W19o8YNoZEEIhHOQ2KgFeLKVjIiEuBEGhLwCAJn0sjYK1oocGNHrACQJdpCN27sPdKMNwDmXsseWSC9s55YFilx6Ehv7aBYcVAuON-7aBjtSRo6ZWjcPt6Y-hOcHbKOccKFzNwa7ABSOpL6oc_kWoly-gI7gySZ0ziAtHUSxGgLgSLY8_Ixck_bTiwMQgpdHuPUw_pIBHEl6UaXIR_TehePegkxNyyVli_bUApAiDkEiLJqIYARd128CfRXBv_ScFbv6aiQYLOTGYKz9n3gnZID53baTiHHeVzlClu4AAxEDEBXBfW3oNUihBgCkS8BwWI4miDwCgPVhYggAAaXBusyF6xuCgSQHoAE00_qAz31ig8oXR3F2iYasVEzC_sYI8EcxQxNbU7GpmAaW4-xEUyrDnoR2Bh-AMANUSd1SK-Ty6TOwhFe57LysNzrAOHVc7yATAJQ3Dh7U33176XuSa9qAn5fktBZUz9g-bw1FkCd5xgoEOgGwjVnnAsVPaBU_g-JC6fPaB8-v5nxAEGaEKLV7_pc6R4J4OhybLhqaODSyPSsBuBqDqZpbVZFC1iR51hkAmxJ4mBQBnBoAY4KBY6p4XCw6568C8AyDlxe7VwuiCDYHfCth0bcCEEe5cjcD54XDfCkHkFtSUGPC7DFjUFYG_D0G45MF0FEFkB6CsGcEUHhyK7nyl5qg0FLLCH4GMH45iHMGSFsExjSHcGyF8FyhyGQ5lZgx6BggeZIGmTIAUSkC_qObACMRAYlCMCKEmDOBcCC4gDhzGF3Dmj75a7jgBAIbIElB4yURGZqii71ya7a4xGIgtAciFrOBXyrBa7xHnxQBLJRDJFRCeHkDyiq4FBRHeAbSiYkSCzCwTA_iNhAA) is the closest to your example I can think of right now.
