### ISSUE TITLE
[Bug] yAxis split line overlay with the xAxisLine

### ISSUE THREAD

**Issue by jacksonyin** [apache/echarts#20568]
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=line-simple&theme=dark&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6IYHgiQYdMKF79YAE2aMiAbVqNesWgCM1DbTNoBdPqViNceADIRoNYsfR4AFsADuRMBwCuVI3ZgAtKg5gN09vaXQAGysqAGUKCJtUO1IKajo8YCi9H2TnCBkwByIAJhy7ekzOOg4qPXDYAF9pBrK8ECiwS2siJLtHFyIAM0YIvDDkqOs48gSe-vQ8gqLYAFYy4wqIqvVWGqpoWnqW-qsWDgA3EaGPaHpROAAKKxkqDB5YS4ivAEpbZNgamAPBw4M9XrAAITwRAABgA3EdmiRjuhyDh8HNjKkbLRPl4pMZTPguol6v1XLBhqNxr5oAEgiEvOtYJNYvFSf8yJQcRksgT_otCiVmehNttaDU6skmsYUaQ2h0SZi-k4Ke4mfVWdNZn9cvkhasRbAxRw6OQqBEts5DtLmadAp9rrd7rAntAXm8PiMfrq7IDgaD3eCobCEdLmj45WMOBAqIRYIppL1jHIwAoEwBGFYw97FADMOdgxWKABZ3hmSwB2XMANhhhnq2LorJtpBlsH0KAacKAA

### Steps to Reproduce

1. create a simple chart
2. add yAxis.splitLine

### Current Behavior

the bottom yAxisLine overlay with the xAxisLine
![image](https://github.com/user-attachments/assets/8f086cc4-2638-483c-b71c-5ba5aa84da09)

### Expected Behavior

I try yAxisLine.interval, but it only support the category type, 
How to hide the bottom yAxisLine?

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by MatthiasMert** [comment]
`showMinLine` and `showMaxLine` are features coming with a future version. If you select one of the nightly versions in the echarts editor its already supported.

[Example](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&theme=dark&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6IYHgiQYdMKF79YAE2aMiAbVqNesWgCM1DbTNoBdPqViNceADIRoNYsfR4AFsADuRMBwCuVI3ZgAtKg5gN09vaXQAGysqAGUKCJtUO1IKajo8YCi9H2TnCBkwByIAJhy7ekzOOg4qPXDYAF9pBrK8ECiwS2siJLtHFyIAM0YIvDDkqOs48gSe-vQ8gqLYAFYy4wqIqvVWGqpoWnqW-qsWDgA3EaGPaHpROAAKKxkqDB5YS4ivAEpbZNgamAPBw4M9XrAAITwRAABgA3EdmiRjuhyDh8HNjKkbLRPl4pMZTPguol6v1XLBhqNxr5oAEgiEvOtYJNYvFSf8yJQcRksgT_otCiVmehNttaDU6skmsYUaQ2h0SZi-k5nABZKxKykjMbM8mMmnGVnTWZ_XL5IWrEWwMUcOjkKgRLbOQ7S5mnQKfa63e6wJ7QF5vD4jH5muyA4GggPgqGwhHS5o-OVjDgQKiEWCKaS9YxyMAKTMARhWMPexQAzKXYMVigAWd6F2sAdjLADYYYZ6ti6KzXaQZbB9CgGnCgA&version=5.5.2-dev.20241130)

**Comment by jacksonyin** [comment]
great!!!
