### ISSUE TITLE
[Bug] WEB ONLINE SIMULATOR. I don't know what, but there's something wrong 🤓

### ISSUE THREAD

**Issue by GitHubWebStudioMakerPerfect** [apache/echarts#20578]
### Version

**JavaScript Simulator**

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoF0DcAoFAzArgOwMZgEsB7bSAJxG2CIFsBJbMAMTNobAFMyA3EAGwAUNAtgA0kGiAAeASkgBvSCkjkOYTGVIBZcAAsAdOj5EiZATrAGKVWgLkAqSEOmQAtBJGQA1JACMcn2FsGVQAXzQsPEISSBBgYAB9AAciETA7eWVIbl8YckpqekYWNkYuXkFfAAZxACYqkKzuWrzrQvYSos4efgFquobUFW4AZlaC0uZWLvLe_sh6xuGAFnGbLs72WcqahcGmgFY19uLprZ6dgaXsgDZjyc2yi4FXX3F_IeyAdnuNs6eKi83n5rqAIPokpgAM66ARwHLiZqIkaI5aIg6Im6Ir4IRrhDCmJx8NSQAh5KpIUmQAA8sGqlIIXi8ckUcUSKTSdkp-NwJChRGJ-mMAHMBGCQCEgA

### Steps to Reproduce

Click as you want on the button "Run".

### Current Behavior

Look at your browser console.

You will always read the same values!!!

### Expected Behavior

For a random function the expected behavior it's a random value 😝😜🤪😎

### Environment

```markdown
- OS: EACH
- Browser: Firefox, Chrome, Each one
- Framework: Random
```

### Any additional comments?

WTF?!?!?!?  Never seen anything like it.

**Comment by helgasoft** [comment]
> WTF?!?!?!? Never seen anything like it.

You could run the same JS code directly in the Console. How is it related to anything ECharts ?

**Comment by GitHubWebStudioMakerPerfect** [comment]
Not agree with this. On the ECharts simulator you can see always the same result.

So
> WTF?!?!?!? Never seen anything like it.

That's this:
```
[
  [
    14,
    15,
    17,
    12,
    12,
    -1,
    -1
  ],
  [
    14,
    10,
    17,
    14,
    15,
    1,
    -1
  ],
  [
    15,
    18,
    16,
    10,
    18,
    -1,
    -1
  ],
  [
    17,
    17,
    11,
    11,
    19,
    -1,
    -1
  ],
  [
    20,
    10,
    15,
    11,
    17,
    0,
    0
  ],
  [
    12,
    14,
    17,
    13,
    15,
    1,
    0
  ],
  [
    15,
    19,
    17,
    20,
    15,
    0,
    1
  ],
  [
    15,
    18,
    16,
    15,
    19,
    1,
    -1
  ],
  [
    19,
    11,
    13,
    12,
    20,
    1,
    -1
  ],
  [
    20,
    19,
    13,
    18,
    18,
    1,
    1
  ],
  [
    13,
    14,
    15,
    15,
    20,
    1,
    1
  ]
]
```

If you check this in any other tool that offers JavaScript processing you will have a different result for each execution.

Want a direct test?

Try Echarts online simulator at the link posted in the bug report.

Then test it here:

https://jsfiddle.net/hb95186n/

**In the second one it will be random every time, in the first one it will always be the same result** (ASURD!!!)

**Comment by helgasoft** [comment]
You may use the Random button instead of Run if you really need to test such JS code in the Editor.

**Comment by plainheart** [comment]
The ECharts editor uses the [`seedrandom`](https://github.com/davidbau/seedrandom) library to ensure all developers get the same result. If you hope to get a different result in each run, just click the `Random` button.
