### ISSUE TITLE
Gauge Chart: Labels Not Working with Color Regions in Gauge Chart

### ISSUE THREAD

**Issue by ARULSARAVANAN1** [apache/echarts#20591]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=gauge-grade&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAEYAHAAZ-1dFmgATCdNkqB6AMYawuYiSYBWJQFI-sJgHZLdgLqq1ONpogciDgE5bPgNYAFsIaGJ9NXC2AA9iABYYtQwQKQgwADkOMIAjM1gFD2oEiAwAGUjZVFj0TOgsAGU6GWI6-vQAdwhNMAALYmtS-sNgKWAcc1DYkiUAOgAmS14HAGIlRyS2byZ3WbV5hec1pk3LBSXFfdGukjkz9c18pQClhX3D9FdDgF9Qn87rAQMBIqZppQuhBxlEHCA2INCAB6ZEAWTkSwWJUWjikmN4KQWcgAErjKpjsbxcQAvEJdGSSJEOOQANjswJ6fWZS1SsWAADMBdgwABhExFeZnAC0rOCB2hpjCrVo7ShXVg40mkKYnDAwCY_0BwPKGAAKjCANYdQ6MljMkq2moqtWdLpaqbMPUGzkUXr9IbyI2xIGhdKZMDVJo2hkae2Bx0M51tWrfTUTT0Ob30jX-5lyYNqUOxU2VNiFKQx-oYAbAbrEMA4DhYX0enXrJKszudnOxAUwMDNCA02RyJK-nxCNjQYzEaUAZlWhxwwGEpmYwkkJggbCkvbU_ZwYUREOIAo4M8gMFgAAoAG675sASnV0IFt4fUmbsAAPIg5EoL5uhqOBYGAHA4HATCigA8jBlRMAA3GmfywFgUjYLAEDvvej5YLAAB88hKOgABkpGwJ-35_rA86Aa-IFgRBUGwWiABiMEAEpmkhKFoRh-HYR-eGEYgdGwORlEiTRKRAWm6CgeBkEOCSACiYg8chGqwAC2mKcxUlflgWn1LpRbApAYCuocgrCmB4rQKepAqA48q-v2jlDiOxBssaoSaGBbAQJWDHUB5g7DrI85LL6tkig5TlSg40pyC4tyHFRWASBAx5XnCjbNu5Uy5U556XlAcC4UZcl6UxylooiAwLCuF6aFVz6wAA1A4AANoq8V0xZjBmOqRAMuBZIaIbApoiJsDMXTAbEmXEEsMVptAbBhLI0EQaBjmwGaWBhAwXhKTwhbUL81Bmb8fyIUAA

### Steps to Reproduce

I have created a Gauge chart and added a custom label using the axisLabel and formatter options. However, the labels are only working based on the split numbers, not the color regions. I would like to know if there's a way to set labels according to the color regions instead of relying on split numbers.

Output:
![image](https://github.com/user-attachments/assets/2e8cd486-db90-459e-af6a-68fec4391750)

Expected:
![image](https://github.com/user-attachments/assets/7f872a67-1297-413c-84d5-dea5029faec4)

### Current Behavior

The labels are only working based on the split numbers, resulting in the same labels appearing multiple times. Changing the split number to set the labels also affects the tick values.

### Expected Behavior

The labels should be associated with specific color regions in the gauge chart, not based on the split numbers. The labels should be displayed once for each color section, regardless of the split number.

### Environment

```markdown
- OS: windows
- Browser: Chrome
- Framework: Angular
```

**Comment by helgasoft** [comment]
[Easy](https://echarts.apache.org/examples/en/editor.html?c=gauge-grade&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5AOYCGAri1kwDRUUMYNjjABBaCwA2jWAEYAHAAZ-1dFmgATCdNkqB6AMYawuYiSYBWJQFI-sJgHZLdgLqq1ONpogciDgE5bPgNYAFsIaGJ9NXC2AA9iABYYtQwQKQgwADkOMIAjM1gFD2oEiAwAGUjZVFj0TOgsAGU6GWI6-vQAdwhNMAALYmtS-sNgKWAcc1DYkiUAOgAmS14HAGIlRyS2byZ3WbV5hec1pk3LBSXFfdGukjkz9c18pQClhX3D9FdDgF9Qn87rAQMBIqZppQuhBxlEHCA2INCAB6ZEAWTkSwWJUWjikmN4KQWcgAErjKpjsbxcQAvEJdGSSJEOOQANjswJ6fWZS1SsWAADMBdgwABhExFeZnAC0rOCB2hpjCrVo7ShXVg40mkKYnDAwCY_0BwPKGAAKjCANYdQ6MljMkq2moqtWdLpaqbMPUGzkUXr9IbyI2xIGhdKZMDVJo2hkae2Bx0M51tWrfTUTT0Ob30jX-5lyYNqUOxU2VNiFKQx-oYAbAbrEMA4DhYX0enXrJKszudnOxAUwMDNCA02RyJK-nxCNjQYzEaUAZlWhxwwGEpmYwkkJggbCkvbU_ZwYUREOIAo4M8gMFgAAoAG53gCU6q6OCwYA4ODgD_g8EssAAfgcUVgAmXAmFgYgf3gXlAOA4AwkPMAIKgu9f0XOCmBJVcUKYJgAG5C2oYs1EgMBXUOQVhXfcVoFPUgVAceVfX7OihxHYg2WNUJNHfNgIErF8DwHdjZHnJZfSokVaPoqUHGlOQXFuQ4713ZsJAgY8rzhRtmxYqYtPo89LygOB7zUrBnzdeo3w_L9YDRREBgWFcL00cypGbZ8AGoHAABtFAj_lbDMdUiAZcCyQ0Q2BTRETYGYums2JVM82QlgktNoDYMJZCYUVPzfOjYDNLAwgYLw7J4IiKF-YjyF-P58KAA)
![image](https://github.com/user-attachments/assets/90623343-eac6-42f7-b0de-0881c3cd75b3)

📌 please close issue if problem solved.
