### ISSUE TITLE
[Bug] gradient color doesn't work for visualMap-piecewise + splitnumber

### ISSUE THREAD

**Issue by Justin-ZS** [apache/echarts#20592]
### Version

5.5.0

### Link to Minimal Reproduction
[Minimal Reproduction](https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoW7YCIDGwA2wATpgFywDaaG1q1dGO-RAymKAM6kVX2_I99BmYADMR7AKZguABgA0Awb0YFiZTIQDmAIwCGACgBsAdjmwAjACZzZyzMNmZAOgDMASkyKlsAL4LvdLQByqLiUlw2XsFYuKpcGjoGJmZWNrB2DhYeUYI-OdQAuv7emAAessVKmACeFfkMpZYRlULVTWTy9eiYYNUgEvF4ENASusQtfJiaBHp4XCK6eJI5fjlBVbEsbCCcZJTR6OsH3aGS0h0TBypE8Vp6-uYArC4pABwALLbvac7unserY5HY7CMRnZpdISbNRYO4GJ4vCwfL5pczZAGQoqQsp1AI1XElRoQvFtAlVXr9QbDUbjbHTYCzeaLZZ8QG8YHKaGsDhcfYHDnRUFhc6wTrHajXGEJe6WR7ydLmACcZkej0crnRBzZ0QFwSF4LIkXFDGht0S-ll8usytgqpSmuieQCWLx5Qu2Nq7td7Qsl3oNR9YpKFIG6iGIzGmD9dCmM0WTKWEhW0d1Eq52123CBkMmp3CXuNMSYUrhFselhSLk-6XVfxzGG1wVTJTzIqNhclZpl5cr1YrWX-Wsx0YlbtFI4YnvH2KJhon3VJBfJfVDWHDNKjdLjczIC0TybW2PTPL29cOZ5jrbJ4s76lLsrVFmSsGM_d-DuCjYCzaqV7nF7TYsuwMB8UmfV97UHR1hxna9JinIMqlnX0PUDecsBDKkI1pPF6UZXdmSTVkUyPYtuR2XkLx_IQ_2nQsiziO9zXMcxq3MV40ksFxH3fKDP3QmgAIYWj22NW9YWY1i3k47jIIvJ1vBdQk4OUBD0LKH1RNaNDsUwsNqUjdS8PjAj92Iw88WPCjT2zej9XzOiO1NJj7isK0ZEfLjTFFDU-ICL9vGo3MwQcrSQWciTXLsWwPNsFxvLRPzvAUpQlKQlT_TUmdNPUxdHOXSl9OwzdcO3BMWV4ALz0ssiM0o2yO1oxCbwi6V4QgixHj7SxMl4-SBIwIKQhCtsBv9VrS3MDqnm6zJEvkmDXQymMsu9YkSjy5rJj0tcDJwkpjJ3WA9wq-gqv4GrVHIzM-R1ISThG5bLpuFyQLlFJFUfFifl8_qqPurARLGmMJvNS0Pq-li5IxZ11LHLbVKehoctQpHuh2zB10MrcGRM47CIPPhqMla76v5AH7JFBHBVB7tESsBLLG8vqAWBob_SBinabe-mmZSPmBwW2HYKXVo0awZCwtUnS8QxrH9qqQ7yqIyqBDSiWAEFSggTNdR6Fd4gAN0WABXAZo0wEBgHYCBIBgeJtGAMA2AAWxK5RdG19gABldG0CQjuJgALCAABMJAAeUNiRCDwXQQC4MBCDN9TFggTRoAAWWGX3_aOzGJBEaRU6GDPM893OA9udOg-kFYBEbGotZ1rg9Yx7BdDACRNCIWoLatm27egQZC7r6hG8kQgIAkG6LODA31D0BWhEkPAJGwLvQ8z4Bw_iF2TbwSAQDX92qgkF2QCD3Qbd1i9MFt8_WGqE-yHZy8QF0bBbYQpxFSF5L1Kr3XiKN-98u4uyfi_C6jUP5f16OtMSjtCDh0IAAFQXlgdg-Aw6nxvEglBAB1MOYAg5cEsH9EEcc86twpqAT-38Ij_yUOdCUEhoC4F3q_O-Y5brinMBedWJIybGhkAIyEKU6ASPVlMKeocaHbVAFwV4Fs15FyURbKemha7qJyJgR2ztgBuzIC4amRZoBgF0DnP2VcyBJzNg3Foejk7sFIVwhR-BHY8OxIQYBSV0AFAcQIHowAPHADHHrFxwAADuytAkSk0IQeOIdsC8mkaHTu18HK8MEniLBJtCDYAkAACVGCg5W6lQ4QBdmwm2MBZ4NTEtAXQ1T4iAEB3QAv3K4JBBjIglSmlzGBhKAAXjACQ6DCqwmiX43IbMKZNJaeoQAAKmAFyMgA-l3dgYBsADIpiIIgLtO6txYfPCZmARAEEOYMhgIyRjjNXJgapScIApIoeTOy8z7mLMAPOJ6yZ5bJ2XZPZhADkgOOQVe55zgCXIpjcsZGDJQACFahMMEII5QeSCmrmyd4bFgpADNNoAdWVWldIOD1QwLhFTvGUQDcwMgPJVgEcDXFepABK6YAd1tiVXPQIYSwPVHhS2iJYd4VLXiMovMyvEgBFvMAJn5gB9G05QDYw3FuLKgBj1V4QqxXHAlSUQA_nqABw5BV9EniyipaYgIhhDCvEeKK44aKlA6qqIAf0jADzoYAK8DADdNoALmUSXRGtTIYwrxqX0SZq8OlWqDiOqEIAQO1ADwmoAPbVADzpp6n1XLYAUopVxNN5h4p2AjdEKNkxABqdkS31wRWJhseIYT4ANHiKg8uQu1TKKaysAPNBRrCxWHJUq4NhYXCvBcFa_NwRC3KEAL3x0aO3GkMDm2UDg1WGBkB8YdARR3-kAI46Tqp18JcJm_tab3hKuMKIpt4qKaAAxXQAwQHbuOLS94lLHimABu8IVg6V04opoASk1ACktoAID0y0BG4vYd6ANrWatPdqimgBQxUAJkhgAT5RTQB7wVrXhKprfRXdvKT0HHtYINdMZACR2oAXv0b2kqtYqV8FYAaUt3YYd9DqKaACg5Nl_7s3kp5S8RVlhKX0bwxTQArLGAD3dUj0RaUsXsKqjDHF-28b4PhiUsqt1IaUKxT67wXACuCHKGQb6IORopoAWcTABheqxgG3F3gyHePO41lnjDvFk7weTDBACqaUptNGrVQcQPRZqlDn6BOe6IARLlS3Zpza8RUPUD2muw9EXDcmKZFsAOjKInggRYbb240tGw1-boAFrAeLkvKcED1awGa02KmtTxvTBaKbrsNUVvgspd2zvc-xKzOXqB5cwIAeM9ABfeilgItLPqsXNd4YVFnbU4ebXZXVTrAB3Gsm71DXeDsQHYG6zhZDB1p5R1jAXXEuABq5UzxrD38oy3wnNJjdvoC64ASBVADp5gN7wg6lVCuzcYJVdHqsjopoAbbVAC7uk9pQ3GzUauzTIbjGrrtZg7GykLz6KW0qfSGulQboddcAJq28rlv0AHZDqjIbjA8sm7F6bHZAANpoAMNdAAvfoAPhVAAoOoh97EPFQ8rTaqD7jacOLWDMMaoABhK-hAwAABEMnyKuLEE2Lth5uI7CIaeeBQ71PooNAG21bZQMwIAMr0vk471I83Qdz4iZwAKKoIAEoAEl-f67xEHUpMcABi-zDlkGgAfPAabJg60zgABSKYnZOKtVe-ABnFko6SLHCNV3lom6vedgC1ys35mztl26uBjR5U8Une5bJo4YqDNefLWRs_5GfBRp2vlwD3eAvcJ6qCIF2YBVlh3hnnxvodjfqBFxHAAqgi72puK96hEKHK3cj3ee470IB3ugUEu-BW72Atf6-h6qAAawkFOTA_OJDABF4bAAWiPvELthgQEF2MEUq-Z-TF0NAaATtO5QFlyv6fDeV5EDAE7xXk-YjmCn4lDnzgAC74CxLr6SKf4R41aQE5JwH-iQBJ6fI_Jl7p537KBZ5SA55AG_gF7QBF7IHxDfKp7l4YH-hV6Zi36f6TBN4t5t4IIIEMBj7d5YC94D5D64FCBj4T414f5MExhz4L6u4378ECEMBb477aAuylB4CGwABqXBkw5-0Al-Quohde5BMYD-T-FiQ8fBmhNB6K3-v-Ac_-OATQWhrCF8vQ_O4Bpkp0cBEi9EASLhaaZyf-i-IKEuoemAlSLsqCQcPikSSuqSM-mMwwG-Xhy-5ArhhYYKQg2ezyphSu0RICn-mAHuLs_shAaRMekB1BAhq-0B4RuA0AlSQ8eRNkTBhRNRnuJRGR4YURIh-R6-xRkBcRxoCRkwUuMuKRocVR0CvhWRORgxcevA7R6-nR4ozhACd8hAUycuYkCuZhKuoeb8eIPB5hhsIg2gocLgocH22giougxglKlmeghg68io2A2gShDASBWuHS9xJw-BhBTxnSWhmAlBBha-TBZyXe8KzAluVuAAcgAOIvFYCG6sGYAi5W6ZxQmWxjBsI_6hygnNKri1EIEyIP4HxjAMJT6GECGYBCHO4tFEl_E4mSHxDexRISCglFIABWSJOhz--hlJXxWCwu_R8Q2AMg0yMMhYMBQgUeugqSrygoYpEp_k9chQjihsOsJsiw5cCc1R9AxMGMIA08hSUSOs5s2I_hNSr-jBkw7Ax8tsoJ0uOROiZ-wwEQp27E6kByY4IOYaYO2IwwFuD-mgq4oCEUeWGxnItUJ4MOCBQZgoTUVhJoQEr0DwM6bwyi6QGmtYH4kB3Rby4hD0wopp_x3M8ZqIQacUqIaZ6-sxxoIpS0osdkq06-GkuZYkm04Rcse0XBsYuMR0J0IeMxaaEZIMIZ1kYZcBfZeIUZRh40sZkU8I96bwVolgSZLMTBGZd0WZ2ZBoKEq5DEL0U5DwM5SIc5SZ80Ah5Z4olZyk1ZHYtZvhks4RTZGRLZxU4RSsDh3ZrMAMI5MZV0dU6pw545l4j0F5OJ-ZYWKQxgnEsoqZgp8RWhH5v4AFG5q54kbUDw-6FgYFtgEFgsx5DRkBOIgFN4V5qu9Z_4uFd5uFD5G4T5ZUL5AMy5gQGRVkaxv5m5lM4sdkwFkWT4iIvKb4v0x5MFf5EonMLFHFc05KGF_YR5S5OFdZ7eGRhFdkN58lMsdZFF2MuFz5-MZk0F75DFA5TFkBsFNE8Fo2vhwFEOKQVmtgTwkFf5dF34glwk8FmmuF5lklVlCoX0pZoeJ532ilbFG0AVSEKMpFKlvhaly8dkmlXZtFvZelX5oZ4xGpjla5DkplRF-ZioqIqF1gvFdY_Ff5RlwUOZJFiFmV2VSZuV0M0lHR4RclpFQVQgSloVjV208K8sbZ0VBM9E9laurl-lrR6xKVgMJl0Z3Q-ZZx_MNodgNoi5CBvVSgRVw0JVCFWZSFpYk1Fg3GMUNoUl81Ml15rViM-FIIzVdZZFql7VrZVFHZEBOl9ERlJM35Q5hlw1rFJ1dZ-Zz4qQMUvUfFS5AlLFwlZVk5yF311gv11V-1tVGR9V51R1_oZ1vhF14VV1j5GRXV2lXRYi_k6kwAJsYAEcIg3p0AvpPheorUAAxIqDTVBegAkZgJEjErYsHnjVPKifEEHEQBADchYgCiUA_BAtUNkfYbCL4upILeCfHOLD0BIKUCKPhpgOgG6UupYXfKxMYGdt0DzuSHLWAJAn6XfHsuYgQhIDXCKHovgHIuIupB_KHH0poFwGqJ6eAkQqHCQhEATgLeAiUubZ7epKohbYUuYjHEVqSWbVoiKLyupPoq7EonKRgNImwPgEfOTRKEzUHvYuPCgD4EAA)

### Steps to Reproduce

see reproduction link

### Current Behavior

echarts loged as `[ECharts] '[object Object]' is an illegal color, fallback to '#000000'`

### Expected Behavior

Render gradient color normally

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?
`visualMap-piecewise + pieces` can render gradient color correctly

**Comment by helgasoft** [comment]
Isn't _piecewise_ the opposite of gradient ? Here is one way of doing _piecewise_ colors - [Demo](https://echarts.apache.org/examples/en/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AG4CGANgK5W0A0J6IweESDDoAjYGDDAAtlx6xGuPABlGIqsyKpSpABYQAJlQDy9KgCdmjEETBn23behYQA5tACyEaCrUbYtZioAMzBZR3lmVw8FH3U6M1cdULkAXxIUh1hyHHxNOQpqOgBjRjAqF2AzcjDSPgEhaDpAkNp0zLxzCCpCWABtOS1HApp_EUYzGu0OwKKy_XdgQzopVmZIEEDJ0iopEB1GAR7B8MEdgGUKQLzw7VBGIsFyIgAGADoATjltNPCMr9hplRZtcbqcpBdyFdiDdSHcHhQiABGTIwsRmQxmAAqlBGtDwwEi-i24TRGIA6gYwDoiAAmf7oP4wyy-EEwuGPJH02A_RyMxxUaBFRYjY6ODBIlGOJ6wZ7_HkMkgAXUyLgS-lZZFARAAHJLmmAdZKEi4koa5GIJNIiABmZ6SoXQMCMLyxPy2dhtEgiOx4anQ0iSAlicV9WhmIGhRWe9CB5jBjW-4AAdyIQRYHWjsFVVj0RSIvWVJH0pQOVANfQG_3xrDMRSoAAkqIwMan01RJehq7WRv0Yb1aIBmm0A6sqAQHcuLAaQA2SfW94AFl1sERz2eAFZrXPC33aIAldMA7rZjziwSc0qer5ETucL7Vbm79wCLeYBM_MA-jaH2AAdmt69X7yPU-1NKbh2pD9oA_nqADhyb6IquNKrgudrHpO2qrjewHoP2gD-kYA86GAFeBgDdNoAXMrjshzzvtqi40mRK63uE_aAIHagDwmoAe2qAPOm-FEUes6zjS1pHoi1rvjSzw0Y4_aAGp2o7joi8GrpOc5Hj-a40iJ2j9s-gDzQVBU4Cdai66daSEqSBtCAL3xdFvpO_GwZOf6Ts82pAVy_aAI46GFQda3G6Uec6fu-wloaGgAYroAwQFQc8c7zqu77eYBBlGehtCAJSagCktoAQHrjl-zyTquCHIYB8WhoAoYqAJkhgAnyux45Idqn7ybAHmnv5Tm0IAkdqAL36b7_u8gk0ke84eZOBX9oAUHJ7ulfEzievEfjS86DbQgCssYAe7phYiy6Tr-dXavxqFNc-blSRFcHWheOXPHFAX9oAs4mAGF6Y11XB4U2Uu4Xvo526AKpp-1HgBq4oReV7hTt26AIlykl8dt7xTjFD1zWJgDoym-kNKXpBnao124Dgj45TjS_HvFN7zIbNF20M5kHY-ux3Wj1sBbQ5A0k4A8Z6AF96YXvOec4IVenNA3etCgRhgB3GmxhFSeRAnak92XvCec1w4ANXJ3dJ77nouq0eejfOAJAqgDp5m-BmfoBfHvp-DNNYA22qALu6HXzmjAF8c8M0AXNe5g7Ac6zsu0UTiu5FzYAmravsR1OEzTlEnrztG0IADaaAGGugAvfoAfCqACg6FXG47Ms079JvKf8Ik8re9D4KwLDuFY-aVuEwx0CAXR1km-AcMB-gQFIAoCMIS7AXgGyCAAcqwUhqGYZrhFIXhIj5qvAVICi0rb9k9f8XgAEqMNALgirAXJCswlT5rQADEiK4yfNLjmGLhjAAFLx8mrpwbxzgAlBf4ZEkZfK3KwYBGEEa8bxFDvAk-9_CqioAKVovxu46GTDYOw7Z_iVC6I6OgsCEgAC8YBOmYMSWAYIzjkCHgSeIEY8FggAOLlxlMBMoGByz9nQDNeCAEL7K1VugWgRk6FgAhFCUU2ggjYLJFQRI5ZaBiGYESOUwEQDNhbhvIgD9l5lCkBSfQVIkRLxOKoxsYitHAX1MUAUZQJjAR0KIk05ZTzAQtJIKQOpUhKkyLGdYCZYEpjIAg9IKAUgAG4gA).
![image](https://github.com/user-attachments/assets/ea888264-573e-4236-a5d1-2f7101661623)

**Comment by Justin-ZS** [comment]
> Isn't _piecewise_ the opposite of gradient ? Here is one way of doing _piecewise_ colors - [Demo](https://echarts.apache.org/examples/en/editor.html?c=pie-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AG4CGANgK5W0A0J6IweESDDoAjYGDDAAtlx6xGuPABlGIqsyKpSpABYQAJlQDy9KgCdmjEETBn23behYQA5tACyEaCrUbYtZioAMzBZR3lmVw8FH3U6M1cdULkAXxIUh1hyHHxNOQpqOgBjRjAqF2AzcjDSPgEhaDpAkNp0zLxzCCpCWABtOS1HApp_EUYzGu0OwKKy_XdgQzopVmZIEEDJ0iopEB1GAR7B8MEdgGUKQLzw7VBGIsFyIgAGADoATjltNPCMr9hplRZtcbqcpBdyFdiDdSHcHhQiABGTIwsRmQxmAAqlBGtDwwEi-i24TRGIA6gYwDoiAAmf7oP4wyy-EEwuGPJH02A_RyMxxUaBFRYjY6ODBIlGOJ6wZ7_HkMkgAXUyLgS-lZZFARAAHJLmmAdZKEi4koa5GIJNIiABmZ6SoXQMCMLyxPy2dhtEgiOx4anQ0iSAlicV9WhmIGhRWe9CB5jBjW-4AAdyIQRYHWjsFVVj0RSIvWVJH0pQOVANfQG_3xrDMRSoAAkqIwMan01RJehq7WRv0Yb1aIBmm0A6sqAQHcuLAaQA2SfW94AFl1sERz2eAFZrXPC33aIAldMA7rZjziwSc0qer5ETucL7Vbm79wCLeYBM_MA-jaH2AAdmt69X7yPU-1NKbh2pD9oA_nqADhyb6IquNKrgudrHpO2qrjewHoP2gD-kYA86GAFeBgDdNoAXMrjshzzvtqi40mRK63uE_aAIHagDwmoAe2qAPOm-FEUes6zjS1pHoi1rvjSzw0Y4_aAGp2o7joi8GrpOc5Hj-a40iJ2j9s-gDzQVBU4Cdai66daSEqSBtCAL3xdFvpO_GwZOf6Ts82pAVy_aAI46GFQda3G6Uec6fu-wloaGgAYroAwQFQc8c7zqu77eYBBlGehtCAJSagCktoAQHrjl-zyTquCHIYB8WhoAoYqAJkhgAnyux45Idqn7ybAHmnv5Tm0IAkdqAL36b7_u8gk0ke84eZOBX9oAUHJ7ulfEzievEfjS86DbQgCssYAe7phYiy6Tr-dXavxqFNc-blSRFcHWheOXPHFAX9oAs4mAGF6Y11XB4U2Uu4Xvo526AKpp-1HgBq4oReV7hTt26AIlykl8dt7xTjFD1zWJgDoym-kNKXpBnao124Dgj45TjS_HvFN7zIbNF20M5kHY-ux3Wj1sBbQ5A0k4A8Z6AF96YXvOec4IVenNA3etCgRhgB3GmxhFSeRAnak92XvCec1w4ANXJ3dJ77nouq0eejfOAJAqgDp5m-BmfoBfHvp-DNNYA22qALu6HXzmjAF8c8M0AXNe5g7Ac6zsu0UTiu5FzYAmravsR1OEzTlEnrztG0IADaaAGGugAvfoAfCqACg6FXG47Ms079JvKf8Ik8re9D4KwLDuFY-aVuEwx0CAXR1km-AcMB-gQFIAoCMIS7AXgGyCAAcqwUhqGYZrhFIXhIj5qvAVICi0rb9k9f8XgAEqMNALgirAXJCswlT5rQADEiK4yfNLjmGLhjAAFLx8mrpwbxzgAlBf4ZEkZfK3KwYBGEEa8bxFDvAk-9_CqioAKVovxu46GTDYOw7Z_iVC6I6OgsCEgAC8YBOmYMSWAYIzjkCHgSeIEY8FggAOLlxlMBMoGByz9nQDNeCAEL7K1VugWgRk6FgAhFCUU2ggjYLJFQRI5ZaBiGYESOUwEQDNhbhvIgD9l5lCkBSfQVIkRLxOKoxsYitHAX1MUAUZQJjAR0KIk05ZTzAQtJIKQOpUhKkyLGdYCZYEpjIAg9IKAUgAG4gA). ![image](https://private-user-images.githubusercontent.com/13038071/396278238-ea888264-573e-4236-a5d1-2f7101661623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcwMjUsIm5iZiI6MTczNDQwNjcyNSwicGF0aCI6Ii8xMzAzODA3MS8zOTYyNzgyMzgtZWE4ODgyNjQtNTczZS00MjM2LWE1ZDEtMmY3MTAxNjYxNjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YjE5NWJlNDEzMzEzNGYwZGM0N2JhNWExZTYyZDMxOWNmMjU5NGViNjg4YTkwYzBlMGNiNDUyNGE1ZjQ4MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.32zYH1FJjsJYM0j-MftG2MCMJiMrdiLxRYQMmVYaiAA)

No. piecewise just splits values into pieces.
For each splited piece, I want to paint it in gradient color.

**Comment by helgasoft** [comment]
> For each piece, I want to paint it in gradient color.

not-a-bug, [documentation](https://echarts.apache.org/en/option.html#visualMap-piecewise.inRange:~:text=About%20the%20possible%20value%20range%20of%20visual%20value) says inRange _color_ format is RGB or hex only, gradient is not mentioned/supported.
📌 please close issue if problem solved.

**Comment by Justin-ZS** [comment]
closed as a bug. Turn to post a new feature requirements
