### ISSUE TITLE
[Bug] series-pie.label.formatter {@xxx} is not taking effect

### ISSUE THREAD

**Issue by paopjian** [apache/echarts#20616]
### Version

5.2.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&version=5.5.1&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBKOAZjgE5OzB2wCGsA6jgEYBnCGByUANEXQCArnxHkqAMQ4BrHLAAiHMB3GTYuOhViUAxjmgjGlIgF8J6MMGBZIIAqmIZGEAOa-mKmEcAFsbdHsiXADoABMPfWAfC2NKADcmSFMOLD0vQ1SC8NhIqSYIHAECAG19Ty8DDj4cLDx6htg6JJDtKzxKJFNbZAABUnHbPI7YAHoZzu7ewLppaFNIGAAKEA5GDhCBAEp2hrniZjBpRjgAAwASJB29g4A6WO0OF_HSWxv9LzOtn-JQcDWg-3wJgAgqZzAIBLBFIxgGFQV4wABPECQyggCpTLx7WIQaRVEwAVgADABSAnEd46GrA9BIWBpHLSSEARkpABYABxiWDgkI4gDKOF2pgAFrAAKLQXwQaCiIXffpcyilaas9lYTkEADsAGZyUKRTiNBBmOtxLB1ZQAEyUEHM5BsjmQ8n8ynmiFUOU9CC5NXjfrGl3ajq6z0EAW8v2iqgAVWgUDgUNiAjtDt5kbRDRj-shxspvuF_pMADUILEcMBYJns6HSP1yZHgQBdAvoUIgaUcIRkk5eYIhMWY3AJabEAQD2LAADuACF9YwCDyew05xwF4uAPJ0OgCHBgAAaBF9bqk86XAGEXEkqIxfHwOJty5-hZSXuTDsUOiBQD9CA2BOxQWwAG4gA

### Steps to Reproduce

1. set series data with 'xxx' key in object
2. set series label:{ formatter:'{@xxx}',}

### Current Behavior

{@xxx} is not taking effort , {c} shows. 

### Expected Behavior

expect 'xxx':1 show in the label, not value

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?
``` javascript
option = {
  title: {
    text: 'Referer of a Website',
    subtext: 'Fake Data',
    left: 'center'
  },
  tooltip: {
    trigger: 'item'
  },
  legend: {
    orient: 'vertical',
    left: 'left'
  },
  series: [
    {
      label:{
        formatter:'{c} {@xxx}',
        // formatter:function(params){
        //   return `${params.data.xxx}`
        // }
      },
      name: 'Access From',
      type: 'pie',
      radius: '50%',
      data: [
        { value: 1048, name: 'Search Engine', xxx:'1'},
        { value: 735, name: 'Direct', xxx:'2' },
        { value: 580, name: 'Email', xxx:'3' },
        { value: 484, name: 'Union Ads', xxx:'4' },
        { value: 300, name: 'Video Ads', xxx:'5' }
      ],
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }
      }
    }
  ]
};
```

**Comment by helgasoft** [comment]
apparently label format _[@xxx]_ works under one of two conditions:
* series **dataset** as array-of-arrays or  array-of-objects
* series **data** as array-of-arrays

Series data as array-of-objects, as your example, does **not** work unfortunately. This is not explained in the documentation.
[Demo](https://echarts.apache.org/examples/en/editor.html?c=pie-simple&version=5.5.1&code=M4ewrgTgxgpgvAAgNoCgEIN4IG4EMA2YMAXAgIwAMALABwA0CAdrgLYkIDkAyjLtABYIAoowDmAS0YwODAB7ziHMhwC-dNJhwEipAOwBmAKwNmbUhwAi4iDCgAXGQnmzFAJg4I1GrHkLtDNBQmrOwcQiy44viOzor6Hl7oPtrstFTBZpwAqoziIIwIAIIAJsAxChxUCepJWn6k-hRBTCHmAGrixTAgRaXlLhyGCSgAugDcKMW4driIqOhIlLQM3LwCwmKS0ivKIzXIBsacVjb2jhzuCHsaSAHNYRFR5_FX-0hpKzl5BSVlK1WvG6Ne4dLo9X7nIZXUYTEAABzs3wQiAwGkRdnw7FR6HQdhgsjs5gASjAAGYwGwQBAgUkIXAIADqMAARsBxHiZBp0MAwMy8QTzAAxXAAaxgCAs01wnJxCExpMJnFgjDxEA4GkSCDsIBA-ERcNIWE1mNEMEYxUN1Ig4jNio42ApiKgBEc8rtbtU-wA9F6pjNgDBCRhQJBYGocT6EAB3EAQEXALU6jR-3ABoMh6DsFPh9AaAPWmDAUhIbE4_C4ZkwfDELDAfggKPEOwQIj7WWk2MROyqxQYAACixGKkwfecKhlsoQPo7EC7PYQpLAjHs3wAFHC-KxgABKLA2OyQAoAAwAJBgNxAtwA6FNXsdHlRczxtlqZDiFKCwYAJwUQEAsCdcQATzhUI4RtQCEEvYpxDAItOEMCgAFJIJgthGDZfJ4KQe0UhkDhTG2DhnA4a5ZR9FN0EjGM4wTbUQA1EYUBUMYgA).

**Comment by sz-p** [comment]
The problem occurred in  https://github.com/apache/echarts/blob/master/src/data/helper/dataProvider.ts#L489-L494
