### ISSUE TITLE
如何完全隐藏Y轴坐标？

### ISSUE THREAD

**Issue by hacker5257** [apache/echarts#214]
如下图红框和箭头所示的Y轴坐标线，如何才能完全隐藏，隐藏之后，左右两边都是空白，谢谢！
![111](https://f.cloud.github.com/assets/6768274/2243123/6121e33a-9d1e-11e3-8a7f-2449a6511d28.png)

**Comment by luwenchun** [comment]
怎么做的

**Comment by Aariffe** [comment]
yAxis:{axisLable:{show:false, inside: true}}
