### ISSUE TITLE
如何将柱形图中的Label纵向排列？

### ISSUE THREAD

**Issue by hacker5257** [apache/echarts#215]
![999](https://f.cloud.github.com/assets/6768274/2243258/9b33722c-9d24-11e3-950c-96b95fe4a9df.png)
如上图红色箭头所指的数字，在柱形比较窄的时候，需要纵向排列，如何实现？

**Comment by zsk526** [comment]
希望能支持旋转label

**Comment by fingnet** [comment]
同希望
