### ISSUE TITLE
关于在类目型坐标轴下的字体样式问题

### ISSUE THREAD

**Issue by lang1pal** [apache/echarts#226]
类似与这样的效果
坐标轴在不同的区间可以指定不同的颜色
![axis](https://f.cloud.github.com/assets/3123645/2307642/c87b0378-a2ae-11e3-9472-8d37799dba6c.png)
- axisLabel里面的textStyle中的color属性 `{color} color`只能接收color对象无法接收方法
- 坐标轴的type为value时无法个性化每个坐标的样式

在K线图是否能增加这样的效果

**Comment by xusheng-china** [comment]
建议柱状图类似的Y轴文本标签区域的宽度支持自定义，虽然可以设置文字大小，但是难免有文字多些的需求，目前是使用旋转，但是还是文字超出宽度部分就都看不到了。

**Comment by fuligold** [comment]
能否给一个valueAxis axisLabel textStyle.color可接受方法 的实例？
