### ISSUE TITLE
echart 是否能兼容ExtJs?

### ISSUE THREAD

**Issue by kuugua** [apache/echarts#242]
觉得ExtJs自带的图标功能太弱，请问能否直接在ExtJs中使用echart？thks！

**Comment by DamonChan** [comment]
请问你这个问题解决了吗？我现在也想在extjs环境中集成echarts，但是还不知道该从哪里入手。有什么建议吗？

**Comment by MayBeWrong** [comment]
//define like this
Ext.define('me.ux.EchartsPanel', {
    extend: 'Ext.Component',
    alias: 'widget.echartspanel',
    liquidLayout: false,
    initComponent: function () {
        var me = this;
        if (!me.height) {
            //must have a init height 
        }
        if (!me.option) {
          //no options
        }
        me.on("afterrender", function () {//or boxready
            if (me.theme) {
                me.echarts = echarts.init(me.getEl().dom, me.theme);
            } else {
                me.echarts = echarts.init(me.getEl().dom);
            }
            if (me.option) {
                me.echarts.setOption(me.option);
            }
        });
        me.callParent();
        me.on("resize", function (ta, width, height, ow, oh, e) {
            me.echarts.resize(ow - 10, oh - 5);
        });
    }
});
//add use like this
Ext.create('me.ux.EchartsPanel', {
                height: 300,
                option: option,
                paddingLeft: 10,
                theme: 'dark',
                columnWidth: .5,
            })
