### ISSUE TITLE
Grid直角坐标系内绘图网格中的x能实现自适应吗？

### ISSUE THREAD

**Issue by SportGuy** [apache/echarts#245]
Hi,kener 
     我们在使用中会出现Y轴的label长度不确定，有时候很长有时候很短，这种情况下如果都固定一个宽度，会影响chart的显示效果，能否实现Grid直角坐标系内绘图网格中的x能实现自适应吗？

best regard!

**Comment by shoppon** [comment]
还是希望能够提供此功能。

**Comment by yelingfeng** [comment]
不自适应 产品很难动态设置一些比例
