### ISSUE TITLE
dataRange对于line或者bar，在recalculate 为true时，会自动上色吗？

### ISSUE THREAD

**Issue by randyliu77** [apache/echarts#275]
dataRange对于line或者bar，在recalculate 为true时，会自动上色吗？有没有可能给个例子？在当前的example中只有map的，但对于line或者bar来讲，有x,y，如果支持，不知道这个格式怎么写。
谢谢。

**Comment by Chorola** [comment]
刚好最近也用到渐变的，dataRange设置的颜色组为['maroon','purple','red','orange','yellow','lightgreen']，柱状图通过getGradientColors获取渐变颜色数组来填充。
"normal": {
    color : function (seriesIndex,dataIndex,value){
        var gradientColorList = require('zrender/tool/color').getGradientColors(['maroon','purple','red','orange','yellow','lightgreen']);	
        return gradientColorList[Math.abs(seriesIndex.data.value)];
		                            },
