### ISSUE TITLE
多地图能否支持到市一级的地图

### ISSUE THREAD

**Issue by chouqin** [apache/echarts#288]
现在的多地图是点开一个省，能够展开省的地图，看到省内各个市的数据。

是不是能够把这个地图再降一级，在点击具体的市之后，点开这个市的地图，然后显示这个市下面各个区县的数据？这样在展示统计数据时能够更加精确，我们在实际项目中有这个需求。

**Comment by fantaishao** [comment]
没有用require格式应该使用这个方法
require('echarts/util/mapData/params').params[city] = {
    getGeoJson: function(callback) {
         $.getJSON('./getgeojson/' + city, callback);
    }
}
