### ISSUE TITLE
echarts和弦图label过多时会重叠起来。

### ISSUE THREAD

**Issue by OctPanda** [apache/echarts#322]
echarts和弦图label过多时会重叠起来。如图：

![image](https://cloud.githubusercontent.com/assets/7566164/2954021/ec1b2306-da69-11e3-94d8-29169b2dac62.png)

有没有什么办法让label 显示成向心。如图
![image](https://cloud.githubusercontent.com/assets/7566164/2954028/0d1ce27e-da6a-11e3-8e3f-f31d6bed00e5.png)

**Comment by 12wzy** [comment]
2.0的什么参数可以这样显示啊？没找到啊。。。
