### ISSUE TITLE
myChart.refresh()刷新图表，怎么没有重新加载option。

### ISSUE THREAD

**Issue by wangqiang0323** [apache/echarts#324]
需要的效果是ajax类型的刷新，不会重新load页面

**Comment by huansoo** [comment]
ajax请求后，刷新图表，图表的横轴和纵轴的值都变化了，该怎么做呢，目前测试结果时，横轴只会在原来的基础上，继续增加新的值。而且希望的结果是，将以前的invalid，然后将ajxa返回的横轴结果，重新绘制，这个需求能满足吗？
