### ISSUE TITLE
用地图显示较多的点的时候，部分地理位置坐标显示错误。

### ISSUE THREAD

**Issue by asfeixue** [apache/echarts#369]
1.用百度地图api找西安，坐标明显不对后，换别的在线API，定位到真实坐标之后，输入给echarts。显示西安的点已经超出地图区域。使用map的markpoint。
这是用到的地址坐标：
延安, 109.50051, 36.60332
榆林, 109.74593, 38.27944
汉中, 107.04548, 33.08157
渭南, 109.48393, 34.50236
西安, 108.94017, 44.49171
铜川, 108.96807, 34.90837

option = {
                backgroundColor: '#fff',
                color: ['rgba(30,144,255,1)','lime'],
                title : {
                    text: 'xxxxx',
                    x:'center',
                    textStyle : {
                        color: '#fff'
                    }
                },
                theme : 'monokai',
                tooltip : {
                    trigger: 'item'
                },
                legend: {
                    orient: 'vertical',
                    x:'left',
                    data:['电信','移动','联通']
                },
                dataRange: {
                    min: 0,
                    max: 10,
                    text:['高','低'],           // 文本，默认为数值文本
                    calculable : true
                },
                toolbox: {
                    show : true,
                    orient : 'vertical',
                    x: 'right',
                    y: 'center'
                },
                series : [
                    {
                        name: '电信',
                        type: 'map',
                        hoverable: false,
                        mapType: 'china',
                        itemStyle:{
                            normal:{
                                borderColor:'rgba(100,149,237,1)',
                                borderWidth:0.5,
                                areaStyle:{
                                    color: '#ccc'
                                }
                            }
                        },
                        data:[],
                        markPoint: {
                            symbolSize: 2,       // 标注大小，半宽（半径）参数，当图形为方向或菱形则总宽度为symbolSize \* 2
                            itemStyle: {
                                normal: {
                                    borderColor: '#87cefa',
                                    borderWidth: 1,            // 标注边线线宽，单位px，默认为1
                                    label: {
                                        show: false
                                    }
                                },

```
                            emphasis: {                 // 也是选中样式
                                // color: 各异,
                                borderColor: 'rgba(0,0,0,0)',
                                borderWidth: 5,
                                areaStyle: {
                                    color: 'rgba(255,215,0,0.8)'
                                },
                                label: {
                                    show: false,
                                    textStyle: {
                                        color: 'rgba(139,69,19,1)'
                                    }
                                }
                            }
                        },
                        data : []
                    },
                    geoCoord: {}
                },
                {
                    name: '移动',
                    type: 'map',
                    hoverable: false,
                    mapType: 'china',
                    itemStyle:{
                        normal:{
                            borderColor:'rgba(100,149,237,1)',
                            borderWidth:0.5,
                            areaStyle:{
                                color: '#ccc'
                            }
                        }
                    },
                    data:[],
                    markPoint: {
                        symbolSize: 2,       // 标注大小，半宽（半径）参数，当图形为方向或菱形则总宽度为symbolSize * 2
                        itemStyle: {
                            normal: {
                                borderColor: '#87cefa',
                                borderWidth: 1,            // 标注边线线宽，单位px，默认为1
                                label: {
                                    show: false
                                }
                            },

                            emphasis: {                 // 也是选中样式
                                // color: 各异,
                                borderColor: 'rgba(0,0,0,0)',
                                borderWidth: 5,
                                areaStyle: {
                                    color: 'rgba(255,215,0,0.8)'
                                },
                                label: {
                                    show: false,
                                    textStyle: {
                                        color: 'rgba(139,69,19,1)'
                                    }
                                }
                            }
                        },
                        data : []
                    }
                },
                {
                    name: '联通',
                    type: 'map',
                    hoverable: false,
                    mapType: 'china',
                    itemStyle:{
                        normal:{
                            borderColor:'rgba(100,149,237,1)',
                            borderWidth:0.5,
                            areaStyle:{
                                color: '#ccc'
                            }
                        }
                    },
                    data:[],
                    markPoint: {
                        symbolSize: 2,       // 标注大小，半宽（半径）参数，当图形为方向或菱形则总宽度为symbolSize * 2
                        itemStyle: {
                            normal: {
                                borderColor: '#87cefa',
                                borderWidth: 1,            // 标注边线线宽，单位px，默认为1
                                label: {
                                    show: false
                                }
                            },

                            emphasis: {                 // 也是选中样式
                                // color: 各异,
                                borderColor: 'rgba(0,0,0,0)',
                                borderWidth: 5,
                                areaStyle: {
                                    color: 'rgba(255,215,0,0.8)'
                                },
                                label: {
                                    show: false,
                                    textStyle: {
                                        color: 'rgba(139,69,19,1)'
                                    }
                                }
                            }
                        },
                        data : []
                    }
                }
            ]
        };

        $.each(resultData, function(key, value) {
            if(key == 'net0') {
                $.each(value, function(childKey, childValue) {
                    option.series[0].markPoint.data.push({name:childValue.cityName, value:childValue.net});
                });
            } else if(key == 'net1') {
                $.each(value, function(childKey, childValue) {
                    option.series[1].markPoint.data.push({name:childValue.cityName, value:childValue.net});
                });
            } else if(key == 'net2') {
                $.each(value, function(childKey, childValue) {
                    option.series[2].markPoint.data.push({name:childValue.cityName, value:childValue.net});
                });
            }
        });

        var cityPoint = resultData['cityPoint'];
        for(var i = 0; i < cityPoint.length; i++) {
            var cityName = cityPoint[i]['name'];
            var lng = cityPoint[i]['lng'];
            var lat = cityPoint[i]['lat'];
            option.series[0].geoCoord[cityName] = [lng, lat];
        }

        myChart.setOption(option, true);
```

![error](https://cloud.githubusercontent.com/assets/4454266/3288059/4a1f5624-f55f-11e3-8c6e-7dfa8c7f2192.png)

**Comment by ronaldhan** [comment]
这里遇到的问题可能与地图坐标系统有关。

通过GPS设备获取的坐标，可以称为原始坐标（如果误差较小，可以认为是真实地理坐标），是没有人工偏移的。通过[百度地图Geocoding API](http://developer.baidu.com/map/index.php?title=webapi/guide/webservice-geocoding)进行地址解析获取的经纬度坐标是`百度地图坐标`，此类坐标是经过人工偏移的，即加入了人为的误差，与此地点的真实地理坐标是有偏移的。由此，可能导致真实坐标在行政区划范围内，但是`百度地图坐标`由于人为误差并不在行政区划内的情况。

问题在于：echart使用的地图底图数据是否与百度地图一样，加入了人为误差？简言之，echart是否使用百度地图的底图。
* 如果使用的是百度地图的底图，则用户添加地点数据时，需要将自己的坐标转换为百度地图坐标再使用，转换方法参考[百度地图坐标转换API](http://developer.baidu.com/map/index.php?title=webapi/guide/changeposition)。
* 如果使用的不是百度地图的底图，则需要在文档中对地图数据的坐标系统进行说明。如果底图使用的是真实地理坐标数据（一般而言，此类公开地图服务不可能使用真实地理坐标，具体参见国家测绘局关于网络地图服务的规定，获取地图服务牌照的地图强制性经过人工偏移），则需要将自己的数据进行纠偏，转化为真实坐标再使用。
