### ISSUE TITLE
dataZoom 拖动巨卡！

### ISSUE THREAD

**Issue by MrsWang** [apache/echarts#386]
做了个scatter，使用dataZoom时，想得到拖动对应区域的数据，可是拖动时巨卡！

数据大概有4万个点，有解决方法没？

dataZoom : {
            show : true,
            realtime: false//这个也去掉了
}

large: true,
largeThreshold:40000,

求助~有何解决方法。

**Comment by 799677446** [comment]
请问下问题是怎么解决的
