### ISSUE TITLE
图例项过多时，legend和其他部分重叠在一块儿

### ISSUE THREAD

**Issue by zhaohng** [apache/echarts#398]
刚做了一个图，图例有43项，展现的时候legend和toolbox、坐标轴部分重叠在一块了

ps：感谢你们做出这么棒的图表库

**Comment by sameenzm** [comment]
设置grid的y。
可参考：http://echarts.baidu.com/echarts2/doc/doc.html#Grid

**Comment by tina-root** [comment]
如何解决？？？
