### ISSUE TITLE
dataZoom和markLine同时使用

### ISSUE THREAD

**Issue by tonychi** [apache/echarts#417]
dataZoom和markLine同时使用时，自定义的线在改变dataZoom的大小时会自动消失。而组件本身提供的平均值、最大、最小值则不会消失。
如何做到能否提供个建议？

我尝试过，使用delMarkLine, addMarkLine在dataZoom事件时重新画线。但是遇到两个问题：
1. 线的名称怎么得到？怎么指定？
2. 按照文档addMarkLine传入markData总是报错。

**Comment by xd199153** [comment]
你好，我也遇到了这样的问题， 请问你怎么解决的？

**Comment by LimitSY** [comment]
`markLine: {
    data: [{
        yAxis: 100      
    }]
}`

[https://github.com/ecomfe/echarts/issues/2204](https://github.com/ecomfe/echarts/issues/2204)
