### ISSUE TITLE
能否提供3D展示功能？

### ISSUE THREAD

**Issue by fye** [apache/echarts#433]
Highcharts 和 FushionCharts提供了3D展示功能，效果也非常不错，ECharts后续也能否提供3D展示功能出来？

**Comment by fuqi7758521** [comment]
刚好解决了我想问的

**Comment by xueyanjun2011** [comment]
说了那么多都是废话，两个字没有。

**Comment by xxxspy** [comment]
3D图得有啊，比如三维的散点图，如果不是3D，这类数据就没法展示了

**Comment by cajan** [comment]
你不能老是从设计人员角度去看，实际中客户经常喜欢立体的，开发人员的需求和审美不是主要的，市场才是主导，做开发的难道不知道这些道理么。。

**Comment by phping1** [comment]
3d map必须得有啊
