### ISSUE TITLE
图例内容一多就会覆盖图表

### ISSUE THREAD

**Issue by hkb1990** [apache/echarts#437]
有时候图例内容一多就会覆盖图标，极端的情况如下:
![default](https://cloud.githubusercontent.com/assets/2637138/3579973/34cefc92-0bcc-11e4-96cb-587d2f32d5ec.png)

有没办法实现类似HighCharts里的这种图例？
![qq20140715104828](https://cloud.githubusercontent.com/assets/2637138/3579970/20bb04f8-0bcc-11e4-9751-6506472f0867.jpg)

**Comment by wpp5354** [comment]
@kener 部分图例名称太长，专业名词，无法精简，有没有更好的解决方案，谢谢
