### ISSUE TITLE
What's the typical way to reload data, and keep other options such as 'selected label', 'data zoom'.

### ISSUE THREAD

**Issue by xiujunma** [apache/echarts#45]
I'm using a websocket connection to push tick to browser.
When new tick arrived, I run these code:

```
echart.clear();
echart.setOption({xAxis: new_option.xAxis, series: new_option.series});
    echart.refresh();
```

The new tick is plotted in chart, but failed to keep  'selected label' and 'data zoom' status.
Is there any way to plot new tick in existing chart and keep 'selected label' and 'data zoom'.

Thanks.

**Comment by JeanVanDenderFlume** [comment]
Hello when i have initial data in the chart the Echart looks fine.
When i getData from the server and calculate my own new dataseries and reset the options with = nuill and with clear() i see the chart going away in the debugger, but when it is drawn i see   a line from initial data set to the end of the inital dataset. And second the new datapoints have double series in the tooltip

https://ibb.co/L9pmcbN

How do i add a new dataseries to a excisting instance?
This component is good, but a bit complex i think? I hope you could help me quick.
I use Angular6
