### ISSUE TITLE
timeLine是否可以动态加载数据

### ISSUE THREAD

**Issue by chinareny2k** [apache/echarts#455]
我想在timeLine上每经过一个点都动态的加载一组数据进行显示有什么实现的方法吗

**Comment by sanpi0205** [comment]
##如果只是要动态加载数据，可以分三步：
* 定义一个option,参见官网的[例子](http://echarts.baidu.com/doc/example/map14.html)
* option中的options元素是数组，按照javascript数组添加元素的方式添加数据，如option.options.push();
* 生成地图或其他图表，chart.setOption(option);

**Comment by Percuse** [comment]
为什么每次setoption都会触发timeline—changed时间啊
