### ISSUE TITLE
[优化] type: 'line' & smooth: true 的展示待优化

### ISSUE THREAD

**Issue by lin-credible** [apache/echarts#4556]
#### 问题简述 (One-line summary)

type: 'line' & smooth: true: 一切如图

![echarts_line](https://cloud.githubusercontent.com/assets/3191641/20613036/bcf29b92-b2fa-11e6-9a95-953a282d158e.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echarts 3
+ 浏览器类型和版本 (Browser version): newest version of firefox & chrome 
+ 操作系统类型和版本 (OS Version): windows 10 & OS X EI Captian

#### 重现步骤 (Steps to reproduce)
1. 准备好对应数据即可

y值:  0, 0, 6000, 6000, 6000, 0, 0   ......    0, 0, 2000, 2000, 2000, 0, 0  (制造这样的波峰波谷即可看到效果)

#### 可能哪里有问题 (What went wrong)

smooth的算法待优化，从当前效果的展示来看，value越大，平滑度越小，但是有时候视图数据量很小，这种误差效果太明显，严重影响体验。

#### ECharts配置项 (ECharts option)

> 主要看 series
```javascript
option = {
    ...
    series: [
                    {
                        type: 'line',
                        smooth: true,
                        symbol: 'emptyCircle',
                        symbolSize: 8,
                        lineStyle: {
                            normal: {
                                width: 2.5,
                                color: '#4a90e2'
                            }
                        },
                      ...
                  }
               ]
}

```

#### 其他信息 (Other comments)

`smooth: true`:
![smooth_true](https://cloud.githubusercontent.com/assets/3191641/20613351/25c0bd5e-b2fe-11e6-82a2-e9481e5a6e32.png)

`smooth: false`:
![smooth_false](https://cloud.githubusercontent.com/assets/3191641/20613358/2e968ada-b2fe-11e6-8135-a167804575e6.png)

**Comment by pissang** [comment]
因为平滑后还能保证整个曲线的最大值最小值跟之前是一样的，不能出现类似小于 0 大于 100 的情况

**Comment by lin-credible** [comment]
@pissang 我接受这种解释，另外，这样的视图生产环境重现的几率也不是很高！不过关于这种平滑效果的优化，是否有更优的处理？比如highcharts的平滑效果：[链接](http://jsfiddle.net/vkn4Lb9q/)
<img width="1051" alt="screen shot 2016-11-25 at 11 30 22" src="https://cloud.githubusercontent.com/assets/3191641/20613824/a1d2f764-b302-11e6-9b2a-eec09f933956.png">

**Comment by pissang** [comment]
@lin-credible 谢谢建议，我们会尝试优化下
