### ISSUE TITLE
echarts与其他js库（比如dojo）相冲突

### ISSUE THREAD

**Issue by zhousheng193** [apache/echarts#47]
由于网站是使用dojo构建，在导入echarts后，发现两者冲突，特别是define，和require两个关键字，通过硬方法直接把define，require直接替换成其他单词，画图是可以成功了，但是有些未知BUG经常出现,对此很是担心，直接替换似乎不可取，不知道是否有其他解决的方法，还是你们在下个版本会解决这个问题，希望尽快得到答复，谢谢！

**Comment by liujin834** [comment]
我同时引入Arcgis JS API和Echart，jquery UI冲突，解决方案是确保jquery ui和echart 在 Arcgis JS API的dojo加载之前就已经加载完毕，我把Jquery UI和echart放在<head>中，然后arcgis放在<body>结尾
