### ISSUE TITLE
建议：series.data中增加showSymbol选项，优先级高过series.showSymbol

### ISSUE THREAD

**Issue by k8w** [apache/echarts#4748]
### One-line summary [问题简述]

有这样一种使用场景：
1. 有一张实时折线图，因为数据量大，所以不显示symbol（`seres.showSymbol: false`）
2. 为方便查看，鼠标移动到相应位置时，出现tooltip同时显示Symbol
3. 最新的一个数据点，无论鼠标是否移动，都显示Symbol（更清晰的显示实时数据）

**问题**
按现在的EChart配置似乎无法实现以上目的。
如果series设置了showSymbol为false，则没有任何办法对具体的点做特殊处理。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.x
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Win7

**Comment by WanderHuang** [comment]
我也有类似场景。描述如下：
* 【场景】
1.  非实时，几十条线，每条线上有几百上千个点
2. 需要根据外部条件决定某些线不展示(开关)。这个我用setOption可以做
3. 开启showSymbol耗时1500ms左右，关闭showSymbol耗时370ms左右（关闭showSymbol对切换的效果要好一点）
4. 需要鼠标放到线上展示对应的数据值
* 【尝试】
1. 关闭showSymbol后，tooltip没法触发。感觉tooltip还是通过点的鼠标事件触发的，如果没有这些点，事件就没法触发。
2. 关闭showSymbol。通过监听mousemove事件。但是这个没法知道当前鼠标离哪个线的哪个点更近。
3. 关闭showSymbol。tooltip用axis触发，但是这个一下就触发一条线上的多个数据，在formatter内也没法知道当前鼠标离哪条线更近，因此要么每个有点的数据都显示，要么就都不显示。也不符合想要的效果。
* 【求助】
想问一下有没有哪个事件能够模仿tooltip的trigger="item"的情景, 能够在showSymbol关闭时，获取到鼠标位置和当前线上的数据？
* 【环境】
  * echarts 4.2.1
  * chrome 75.0.3770.142
