### ISSUE TITLE
IE8 example\line1.html 版本echarts-2.0.1 无法正常显示

### ISSUE THREAD

**Issue by zhhxgh** [apache/echarts#475]
IE8 浏览器：example\line1.html 在1.4.1版本显示正常，版本echarts-2.0.1 无法正常显示

**Comment by iulo** [comment]
echart 2.x 同样问题，补一个我的场景下的解决方案。
场景：鼠标hover后显示浮窗，浮窗中有loading态，绘制完图表才show图表的div。结果ie8下空白，浏览器zoom才显示图表。
解决方案： ie8下在绘制图表时，chart init的元素，不能是display: none; 状态
