### ISSUE TITLE
力导向图里节点和连线错位

### ISSUE THREAD

**Issue by cheechow** [apache/echarts#5082]
### One-line summary [问题简述]
力导向图，当force配置项为layoutAnimation: false时，切换时间轴、点击图例、重新setOption时，图里的节点和连线错位。

当force配置项为layoutAnimation: true时，布局迭代晃动强烈，体验不好。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:v3.4.0
+ Browser version [浏览器类型和版本]:chrome/firefox/IE 11
+ OS Version [操作系统类型和版本]:win8.1

### Expected behaviour [期望结果]
force配置项为layoutAnimation: false时，切换时间轴、点击图例、重新setOption时，图里的节点和连线不会错位。【或者force配置项为layoutAnimation: true时，晃动减轻】

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/20678798/22967352/17110942-f3a1-11e6-9d6d-ba504b4d8e30.PNG)

**Comment by jerdbo** [comment]
any update

**Comment by jerdbo** [comment]
meet same problems

**Comment by jerdbo** [comment]
@Ovilia please help assign it to some one

**Comment by wangzhengbo** [comment]
Same problems.

**Comment by Genster111** [comment]
同样的问题也遇到了，鼠标拖动还不会发生，一旦缩放就会立马错位
