### ISSUE TITLE
echarts 在chrome 上会内存泄露

### ISSUE THREAD

**Issue by xzlmoon** [apache/echarts#510]
echarts 在chrome 上会内存泄露
echarts实例化后 在chrome上内存会不停的长。

**Comment by cjhcms** [comment]
echarts这么多年了，这个mac chrome内存泄露的问题还没解决？

**Comment by pissang** [comment]
？

**Comment by cjhcms** [comment]
请问：echart动画渲染在mac的chrome上会出现内存泄露，这个问题echarts现在解决了吗

**Comment by pissang** [comment]
这个跟之前版本 chrome 有关，你现在试下还是否存在内存泄露问题

**Comment by cjhcms** [comment]
现在还是存在的，我们这边的只要是mac的chrome,都会出现内存泄露，并且很严重？如果跟版本有关，chrome版本多少以后不会出现这个问题？

**Comment by pissang** [comment]
echarts 和 chrome 都是什么版本？

**Comment by cjhcms** [comment]
echart: 2.2.7 ; chrome 50.0.2661.102 (64-bit)

**Comment by cjhcms** [comment]
多少版本以后不会有这个问题?

**Comment by pissang** [comment]
你试试 3 以后的版本

**Comment by cjhcms** [comment]
好，我先试试

**Comment by mofengfs** [comment]
你们4年前讨论的问题，现在Echarts依然存在内存泄漏问题

**Comment by MartinGaoC** [comment]
2019年了，这个问题还是存在。别甩锅给谷歌了，真的有问题，clear方法和dispose方法根本无效，内存稳步上升

**Comment by tz310200** [comment]
动态图表内存会一直涨,长时间开着就会导致页面崩溃了

**Comment by linzhe141** [comment]
现在还有这个问题

**Comment by fungmo** [comment]
我对百度没意见，但是共产党领导下的韭菜码农应该很伟光正啊，怎么会出现这种常年未解决的bug，哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈，强大啊墙国

**Comment by pissang** [comment]
引起内存问题的可能性很多，希望大家在反馈问题的时候能够附上自己可以复现的 demo 帮助我们排查问题

**Comment by wangdaodao** [comment]
> 
> 
> 引起内存问题的可能性很多，希望大家在反馈问题的时候能够附上自己可以复现的 demo 帮助我们排查问题

https://github.com/apache/echarts/issues/7540，这个有demo，2018年就开始跟进了，到现在是啥样？

**Comment by haolang** [comment]
> > 引起内存问题的可能性很多，希望大家在反馈问题的时候能够附上自己可以复现的 demo 帮助我们排查问题
> 
> #7540 这个有demo，2018年就开始跟进了，到现在是啥样？

https://github.com/apache/echarts/issues/18686

官方示例也有这个问题

应该还没解决

**Comment by silentzone** [comment]
应该还是有，使用chrome mac 版本，页面打开echart的页面闲置几个小时后，内存占用超10g
