### ISSUE TITLE
delMarkPoint在原图位置会生成很暗的阴影效果

### ISSUE THREAD

**Issue by zillionlee** [apache/echarts#519]
一、 delMarkPoint生效，但是在原图位置会生成很暗的阴影效果（图中白框所示，图上不太明显，实际效果比较明显）； 
二、delMarkLine只是删除了线上的动态的点，但是线还在； 
![a](https://cloud.githubusercontent.com/assets/3169882/3805861/0aaba5ae-1c3f-11e4-8d3f-694dc61f25a4.png)

![b](https://cloud.githubusercontent.com/assets/3169882/3805875/595fbe6a-1c3f-11e4-86d2-9aacb12e4d97.png)

**Comment by retanoj** [comment]
现在还没解决方法吗？
我也遇到了同样的问题。。
