### ISSUE TITLE
请问关于bar图的拖动问题

### ISSUE THREAD

**Issue by dongshimou** [apache/echarts#5260]
### 希望bar图能够每1px都能拖动。
比如每一个柱子height完全显示，但是由于拖动，可能width只有几px。

目前bar是：假如每个刻度之间是100px，拖到50px，出现动画，这一个bar消失。
我的期望是：所有的bar不出现这种动画，不管拖动到多少px，都会显示（即使宽度很小），除非完全的消失在显示图层中。

如图：

![default](https://cloud.githubusercontent.com/assets/9100799/23849647/52526700-0817-11e7-870a-d469bc8e4eea.jpg)

草图，见谅。

**Comment by FengHuangDong** [comment]
@Ovilia has any solution?

**Comment by Ovilia** [comment]
滚动条是什么？dataZoom 吗？提供一个例子吧
