### ISSUE TITLE
多级地图的鼠标滚轮缩放问题

### ISSUE THREAD

**Issue by huoshan12345** [apache/echarts#543]
从全国地图，点击某个省进入省级地图后，这个时候如果滑动滚轮，发现地图不会放大或者缩小，但是再次点击省内某区域后返回全国地图，却发现，全国地图被放大（或缩小了），也就是刚才的滑动滚轮操作对象其实是全国地图。
请问怎么能改成是对当前地图放缩呢？

**Comment by IdenPin** [comment]
同样的问题
