### ISSUE TITLE
About pie-Doughnut question!

### ISSUE THREAD

**Issue by ghost** [apache/echarts#5489]
It is possible to put in center of pie-Doughnut sum of all the elements values? If yes, please, tell me how!?!?

**Comment by sudheer9047** [comment]
Is it possible to have a semi circle type of doughnut chart instead of full circle (as specified below).
![Capture](https://user-images.githubusercontent.com/34652606/72896032-d8a53e80-3d44-11ea-88d4-330d3c0c21b2.PNG)
