### ISSUE TITLE
candles and bars appear blurred on borders for small scale .. 

### ISSUE THREAD

**Issue by anoosurf** [apache/echarts#5494]
### One-line summary [问题简述]

the candles and bars look blurred at borders despite shadow & border being set as zero. i think it is possibly because of the x/y pixels being decimals & not rounded . can there be an option to make it crisper so that the charts are more sharp & crisper ( by possibly rounding of x/y pixels to near integer or 0.5)

### Version & Environment [版本及环境]
+ ECharts version latest
+ Browser version Chrome
+ OS Version windows10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/4696146/24986711/83182e1e-2019-11e7-826f-063c6231122f.png)

**Comment by anoosurf** [comment]
any idea on how this could be made crisper ? some option for rounding of pixels maybe ?

**Comment by vishnug1995** [comment]
any response ???

**Comment by anoosurf** [comment]
someone got a solution for this ?

**Comment by 100pah** [comment]
The candlestick has been applied the "subPixelOptimize" but need to test in windows10 to reproduce this issue.

**Comment by anoosurf** [comment]
even a normal bar chart has hazy borders... ( ideally a bar chart could use the .rect() method for bars with an addition of 0.5 to remove the haziness in borders)
or is there some setting where we can remove the "subPixelOptimize" option ? or where do can we modify the source code to get this effect
