### ISSUE TITLE
移动端 在图表上滑动 页面顶部闪烁抖动

### ISSUE THREAD

**Issue by Sapphire2k** [apache/echarts#5497]
### 移动端 在图表上滑动 页面闪烁
在使用了 ``-webkit-overflow-scrolling: touch;``
在图表上滑动，回弹的时候 会产生页面抖动的情况
去除后 消失，
希望能解决，在体验上能迈出一大步！谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts@3.4.0
+ Browser version [浏览器类型和版本]: WkWebview
+ OS Version [操作系统类型和版本]: iOS 10.3

### Expected behaviour [期望结果]
在使用原生回弹的情况下 页面正常显示，不抖动

### ECharts option [ECharts配置项]

用的是 折线图 柱状图， 并且显示了 tips

**Comment by juanha** [comment]
+1

**Comment by yangzhenyin** [comment]
+1

**Comment by wufeng87** [comment]
遇到了类似的ios 点击图表滚动的抖动问题，现在有啥办法处理吗？谢谢

**Comment by yangzhenyin** [comment]
tooltip: {
  enterable: true,        // 去抖动
  showDelay: 200,         // 延迟显示
  trigger: 'item',        // 设置提示框
  confine: true,          // 限制图标内部
},
您可以试一下在 tooltip 配置项内设置 tooltip 延迟显示,图表内部滑动在移动端导致页面抖动是因为 tooltip 弹框一直刷新显示导致的,希望对您有帮助.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wufeng87"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午3:04
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"牛顿"<yangzhenyin0223@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] 移动端 在图表上滑动 页面顶部闪烁抖动 (#5497)





 
遇到了类似的ios 点击图表滚动的抖动问题，现在有啥办法处理吗？谢谢

**Comment by shenjianbo** [comment]
在用于实例化图表的dom元素外层再包一层div元素，加overflow: hidden;即可！
