### ISSUE TITLE
把echarts图表 用 transform 翻转90度后，手机端的dataZoom失效

### ISSUE THREAD

**Issue by suhuixiao** [apache/echarts#5538]
![op jie0 b_8 m9 d 67o 3](https://cloud.githubusercontent.com/assets/25878428/25173193/ca386bd6-2525-11e7-896d-a37dff3ace96.png)

**Comment by godfrey-yin** [comment]
怎么搞啊，我的也是移动端滑动，还有toolbox都失效！！！

**Comment by SamZSL** [comment]
请问你解决了么

**Comment by suhuixiao** [comment]
当时没有解决，不要用transform翻转了

**Comment by SamZSL** [comment]
可我不想通过翻转手机来实现横屏查看，而是直接固定横屏，这该如何实现呢？

**Comment by Dowgen** [comment]
@SamZSL @suhuixiao @godfrey-yin 各位大佬，你们后来怎么解决的阿

**Comment by cjzhang1230** [comment]
@SamZSL 问题解决了吗？

**Comment by suhuixiao** [comment]
我觉得最好就是监听页面窗口大小自适应echart图表的宽高，这样横屏也没问题的，前提是这个页面所在的应用支持横竖屏切换

**Comment by SamZSL** [comment]
@cjzhang1230 @Dowgen 我变通了一下，用echart的inverse属性来进行y轴反转，在将x轴的position设置为top，最后将原先x轴的值付给y轴，y轴的值赋给x轴，变相的实现横向显示，这样不会影响缩放，希望对你们有所帮助：，代码如下：` xAxis: {
                        type: 'value',
                        splitLine: {
                            show: false
                        },
                        boundaryGap: true,
                        position:'top',
                        axisLabel:{
                            rotate:90
                        }
                    },
                    yAxis: {
                        type: 'category',
                        axisLine : {onZero: false},
                        data: xData,
                        boundaryGap: true,
                        splitLine: {
                            show: false
                        },
                        axisLabel:{
                            rotate:-90,
                            interval:200
                        },
                        inverse: true
                    },`

**Comment by kf53916** [comment]
@SamZSL 坐标轴的axisPointer.label无法旋转，你是怎么处理的？
