### ISSUE TITLE
可否让ECharts在Node.js服务器上跑？

### ISSUE THREAD

**Issue by mawenjian** [apache/echarts#554]
有个疯狂的想法，可否让ECharts在Node.js服务器上跑？ECharts是用JavaScript写的，理论上经过修改有可能在服务器端运行。所以我想请教下官方人员，这么做是否具有可行性？如果可行（不可行）的话，难点或者瓶颈会在哪里？谢谢。

**Comment by XiaodiKong** [comment]
我在使用http://blog.csdn.net/zor_chen/article/details/31371501这个尝试，但是在换成echarts3的代码的时候报错“ReferenceError: Can't find variable: echarts” 请问是什么原因？

**Comment by suxiaoxin** [comment]
完全可以，因为公司需要，最近写了个。
https://github.com/suxiaoxin/node-echarts

**Comment by 100pah** [comment]
👍
也可参见<https://tonicdev.com/56cb0fbc3a0cd70c0074022b/56cb0fbc3a0cd70c0074022c>

**Comment by xiaomaiyun** [comment]
问题解决 https://github.com/xiaomaigou/echarts-export-server
