### ISSUE TITLE
axisPointer:{type:"cross"}横线如何吸附在线图上

### ISSUE THREAD

**Issue by wanglianjie91** [apache/echarts#5546]
如题，折线图上，axisPointer:{type:"cross"}，如何让横的那条线，一直吸附在折线上，而不会跟随我的鼠标上下移动。

**Comment by pissang** [comment]
用 markLine ？

**Comment by 100pah** [comment]
axisPointer 做不到，
然而，感觉你的需求，可以使用 markLine 实现？

**Comment by mumuy** [comment]
同问！

**Comment by yjzzcao** [comment]
有例子吗

**Comment by hiwanz** [comment]
我猜是这个效果

```javascript
option = {
    tooltip:{
        show: true,
        trigger: 'axis',
        axisPointer:{
            type: 'cross',
            axis: 'y',
            crossStyle:{
                type: 'solid'
            }
        }
    },
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};

```

**Comment by autukill** [comment]
他的意思是:  X 轴和 Y 轴  axisPointer 的 snap 是独立的, echarts 不能从多个点中选出(吸附)一个点.
想要实现: 先以 X 轴吸附到的点为目标, 然后 Y 轴指示线的坐标 y 值等于目标点的 y 值

只能用markline

**Comment by blacider** [comment]
> 他的意思是: X 轴和 Y 轴 axisPointer 的 snap 是独立的, echarts 不能从多个点中选出(吸附)一个点.
> 想要实现: 先以 X 轴吸附到的点为目标, 然后 Y 轴指示线的坐标 y 值等于目标点的 y 值
> 
> 只能用markline

@autukill  markline只能标记几个固定的线，没有办法满足跟随鼠标吧？

**Comment by autukill** [comment]
> > 他的意思是: X 轴和 Y 轴 axisPointer 的 snap 是独立的, echarts 不能从多个点中选出(吸附)一个点.
> > 想要实现: 先以 X 轴吸附到的点为目标, 然后 Y 轴指示线的坐标 y 值等于目标点的 y 值
> > 只能用markline
> 
> @autukill markline只能标记几个固定的线，没有办法满足跟随鼠标吧？

监听鼠标事件, 修改 echarts option

plotly 例子: https://plotly.com/javascript/pointcloud/

**Comment by renqWork** [comment]
yAxis: {
        axisPointer: {
            show: true,
            snap: true
        }
    },

**Comment by renqWork** [comment]
`   yAxis: {
        axisPointer: {
            show: true,
            snap: true
        }
    },`
