### ISSUE TITLE
关系图graph新加需求。

### ISSUE THREAD

**Issue by dun-cat** [apache/echarts#5571]
最近公司要在图类型为graph的关系图上加需求。
需求是节点单击后加个圆环菜单围绕node节点。请问有什么解决方案吗？
想自己去修改echarts源码，但是看不懂echarts的源码的抽象和代码的组织意图，能给点学习资料吗？

**Comment by pissang** [comment]
没什么现成的解决方案，只能自己实现

**Comment by dun-cat** [comment]
有没有学习的共享资料？实在是能力有限，一时半会看不懂源码。不知道从哪着手二次开发。

**Comment by pissang** [comment]
不用改源代码，只需要监听鼠标事件然后自己处理就行了

**Comment by dun-cat** [comment]
比较麻烦，环形菜单实现的话会考虑一些问题。

**Comment by dun-cat** [comment]
单单只监听事件恐怕还不够，环形菜单实现的话会考虑一些问题。比如环形内环的大小得和节点相关联、当节点在移动的时候，环形菜单的位置也要随节点一起移动。还有一些其它问题的。
后来我找其它库了。现在基于d3库，自己实现了一个力导图，以此来适应业务需求。
<img width="745" alt="test" src="https://cloud.githubusercontent.com/assets/4863887/25849136/d1858e8a-34ef-11e7-8fc2-1f0f79d50abc.png">

**Comment by dun-cat** [comment]
单单只监听事件恐怕还不够，环形菜单实现的话会考虑一些问题。比如环形内环的大小得和节点相关联、当节点在移动的时候，环形菜单的位置也要随节点一起移动。还有一些其它问题的。
后来我找其它库了。现在基于d3库，自己实现了一个力导图，以此来适应业务需求。

**Comment by 1cy** [comment]
@pissang   请教一下node节点如何绘制环形菜单？ 监听鼠标事件之后遇到上面提到的位置、大小问题。能不能给一个思路？  谢谢

**Comment by remkl** [comment]
hi, i have a similar question following https://github.com/apache/echarts/issues/4119

I was thinking it may be possible to achieve this using https://echarts.apache.org/en/option.html#graphic.elements-ring.%24action, however i'm not sure how we could associate the graphic element with the graph node - so it moves when the node moves.

wondering if you have any insight here @pissang ? or if we would need to make the change inside the echarts library itself

thanks in advance for your time (sorry for asking here in english 😅)
