### ISSUE TITLE
动态加载数据， tooltip 自动消失

### ISSUE THREAD

**Issue by lixing-youxing** [apache/echarts#5631]
### One-line summary [问题简述]
动态加载数据的情况下，鼠标移入到图表中触发了 `tooltip` 显示，但是下一个 interval 数据动态加载进来，`tooltip` 就会自动消失（这个时候鼠标仍然是在图表中的），这样就没办法通过 `tooltip` 查看一个点的提示说明，不太方便。使用 `tooltip` 的配置项 `alwaysShowContent` 倒是可以让提示一直在，但是移出图表之后提示仍旧在，难道需要自己监听移出图表事件，然后 `dispatchAction ` 来移除 `tooltip` 吗？尝试过 `setOption` 的第二个参数设置为 `false` 或者 `true` ，结果是一样的。请教一下这个问题有没有办法解决？谢谢。
_PS. 我印象中以前的版本（也许是 3.3.x）好像不会自动消失。_

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]: Chrome 版本 58.0.3029.81 (64-bit)
+ OS Version [操作系统类型和版本]: macOS latest

### Expected behaviour [期望结果]
动态加载数据， `tooltip` 不会自动消失

### Other comments [其他信息]

例如 Echarts 的官方示例：http://gallery.echartsjs.com/editor.html?c=dynamic-data2

**Comment by AntiMoron** [comment]
可能这个issue对你也有用。

https://github.com/ecomfe/echarts/issues/5630

重设数据后再重设回tooltip位置

**Comment by qugemingziburongyia** [comment]
解决了吗?

**Comment by ssjtbcf** [comment]
解决了吗？
