### ISSUE TITLE
Echarts3中series为graph，layout为‘none’时,data中的x,y怎么设置？

### ISSUE THREAD

**Issue by yishangtanhuan** [apache/echarts#5659]
### One-line summary [问题简述]
Echarts3中series为graph，layout为‘none’时，data中的x，y怎么设置？每个点 x，y随机值 [ 随机值限定一个范围 ] ？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:chrome 56
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
不清楚x，y怎么设置

**Comment by pissang** [comment]
layout 为 none 的话，x，y 就是你自己对关系图布局的结果。所以如果你没有其它算法对关系图进行布局的话不要设置为 none

**Comment by Naslang** [comment]
@pissang 请问x、y是相对于那个点，我设置一个点的x和y都为0，节点为什么没有渲染到画布的左下角？谢谢~~~

**Comment by githubrab** [comment]
我也有相同的问题，设置layout 为 none，设置x,y关系图的位置总是没有按预期显示，不知道x,y的定位是相对于什么的

**Comment by JasinYip** [comment]
有同样的疑惑，不明白这两个值到底如何设置，什么叫「你自己对关系图布局的结果」？

**Comment by candy4290** [comment]
我也有相同的问题！
