### ISSUE TITLE
想问两个问题 1 怎么画虚线 2 两条虚线起始时间点不一样怎么画

### ISSUE THREAD

**Issue by KongnuanZhao** [apache/echarts#566]
比如我想用折线图来展现预测的数据，前面一条实线描述的是实际的数据，比如到8月1号，8月2号往后用另一条虚线 描述 自己预测的数据  请问应该怎么做呢？

**Comment by loveitmac** [comment]
建议把这个提醒加上去，找了很久，才发现需要设置smooth为true.

**Comment by loveitmac** [comment]
建议把这个提醒加上去，找了很久，才发现需要设置smooth为true.
