### ISSUE TITLE
动态更新数据的时候datazoom如何保持固定区间

### ISSUE THREAD

**Issue by huchhong** [apache/echarts#5680]
### One-line summary [问题简述]

动态更新数据的时候，缩放和滑动datazoom的效果是datazoom的百分比不变，导致datazoom选中的数据区间也一直在更新。

### Expected behaviour [期望结果]

datazoom选中区域的startValue和endValue在数据更新的时候保持不变，除非end或endValue已经在坐标轴的最末端。这样方便数据更新的时候固定查看某一段区间。

### ECharts option [ECharts配置项]

```javascript

var fakeData = genData();
var series = genSeries(fakeData);

var option = {
    title: {
        text: '仿真数据'
    },
    xAxis: {
        splitLine: {
            show: false
        },
        type: 'time'
    },
    tooltip: {
        trigger: 'axis',
    },
    yAxis: {
        type: 'value'
    },
    showDetail: false,
    dataZoom: [{
        throttle: 100
    }, {
        type: 'inside'
    }],
    series: series
}



function genData() {
    var now = new Date();
    var length = 1440;
    var value = Math.random() * 100;
    var oneMinute = 60 * 1000;

    var data = [];
    for (var i = 0; i < length; i++) {
        var t = new Date(+now + i * oneMinute);
        value = value + Math.random() * 20 - 10;
        data.push({
            name: t.toString(),
            value: [
                t,
                +value.toFixed(2)
            ]
        })
    }

    return data;
}

function updateData(data) {
    var last = data[data.length - 1];
    console.log(last);
    var lastTIme = new Date(last.name);
    var lastValue = last.value[1];
    // console.log(lastValue);
    var oneMinute = 60 * 1000;

    var t = new Date(+lastTIme + oneMinute);
    var value = lastValue + Math.random() * 20 - 10;
    // console.log(value);

    data.push({
        name: t.toString(),
        value: [
            t,
            +value.toFixed(2)
        ]
    })

    return data;
}

function genSeries(data) {
    var series = {
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data,
        markPoint: {
            data: [{
                type: 'max',
                name: 'max value'
            }, {
                type: 'min',
                name: 'min value'
            }]
        }
    }

    return series;
}

setInterval(function() {
    fakeData = updateData(fakeData);
    myChart.setOption({
        series: genSeries(fakeData)
    })
}, 100);
```

**Comment by 100pah** [comment]
> datazoom选中区域的startValue和endValue在数据更新的时候保持不变
这样的话，动态更新的时候，数据窗口完全不变，那么视图上也看不出在动态更新，而是『静止』的，是需要这种效果么？

**Comment by ZiQiangWang** [comment]
我也在找这种效果的实现方式，你目前实现了吗

**Comment by colbertchai** [comment]
也在寻找这种，能让滑动区间时候。新数据进来刷新时候会自动回到最开始默认区间。题主解决了吗？

**Comment by WangAngIOT** [comment]
同需要这种效果，想根据不同区间和等级动态请求后台获取数据

**Comment by colbertchai** [comment]
> 同需要这种效果，想根据不同区间和等级动态请求后台获取数据

最后用了没用滑块效果 用了 inside的模式 通过滚动鼠标轮放大缩小  不会数据失真~

**Comment by WangAngIOT** [comment]
@colbertchai 有个问题想请教下，我也是临时使用inside模式，但是如果显示的全部内容，datazoom事件就没法缩小了，鼠标事件上好像没有wheel。然后还有个问题，如果放大到一定程度，比如原来是月份等级，一共显示了10个月，每个月一个值，现在放大到一个月，然后从后台请求一个月的每天的数据，然后更新series，在更新series之后，datazoom就变了，这个地方处理不是很方便。请问您有思路吗

**Comment by colbertchai** [comment]
你好 我通过改变inside之后  datazoom可以灵活改变 且不失真  你的可能是echart调用版本问题 你试试调用其他的版本试试
------------------
世上有味之事，包括诗，酒，哲学，爱情，往往无用，吟无用之诗，醉无用之酒，读无用之书，钟无用之情，终于成一无用之人，却因此活得有滋有味。

 




------------------ 原始邮件 ------------------
发件人: "WangAngIOT"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 上午10:36
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "柴健"<274431720@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 动态更新数据的时候datazoom如何保持固定区间 (#5680)




@colbertchai 有个问题想请教下，我也是临时使用inside模式，但是如果显示的全部内容，datazoom事件就没法缩小了，鼠标事件上好像没有wheel。然后还有个问题，如果放大到一定程度，比如原来是月份等级，一共显示了10个月，每个月一个值，现在放大到一个月，然后从后台请求一个月的每天的数据，然后更新series，在更新series之后，datazoom就变了，这个地方处理不是很方便。请问您有思路吗

**Comment by WangAngIOT** [comment]
@colbertchai 谢谢你的回复，我已经采用其他的方式解决了

**Comment by lvybriage** [comment]
> > 同需要这种效果，想根据不同区间和等级动态请求后台获取数据
> 
> 最后用了没用滑块效果 用了 inside的模式 通过滚动鼠标轮放大缩小 不会数据失真~

@chaijian2019 你好，请问inside模式通过滚轮来实现缩放，那么在来了新数据之后，滚轮放大的效果不会被刷新吗

**Comment by lvybriage** [comment]
> @colbertchai 谢谢你的回复，我已经采用其他的方式解决了

请问是怎么解决的呀，我也遇到了这个问题

**Comment by angwangiot** [comment]
> 
> 
> > @colbertchai 谢谢你的回复，我已经采用其他的方式解决了
> 
> 请问是怎么解决的呀，我也遇到了这个问题

我分等级查询了，并没有按照原来的思路。每次查询时只有一个等级，滚轮滑动也只是显示当前查询的数据。
![图片](https://user-images.githubusercontent.com/16277126/68721651-0441d500-05ee-11ea-8c94-3bb9424863c9.png)
