### ISSUE TITLE
Map中的tooltip显示问题

### ISSUE THREAD

**Issue by GloriaCHL** [apache/echarts#5695]
### One-line summary [问题简述]
使用js方式导入map的地图数据时，tooltip.formatter可以通过{b}拿到地图区域的名称（如官网例子 http://echarts.baidu.com/demo.html#map-china） 使用json导入map数据时formatter却拿不到，formatter函数形式中的参数一 params也没有对应的数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts@3.5.4
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Mac

### Expected behaviour [期望结果]
希望通过json引用map数据时也能拿到map本身的区域名称

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{b}'
    },
    series: [
        {
            name: '中国',
            type: 'map',
            mapType: 'china',
            selectedMode : 'multiple',
            label: {
                normal: {
                    show: true
                },
                emphasis: {
                    show: true
                }
            },
            data:[
                {name:'广东', selected:true}
            ]
        }
    ]
};

```

**Comment by pissang** [comment]
这两种方式没什么区别

**Comment by GloriaCHL** [comment]
别的其他是没什么区别。不过我现在碰到的情况是我需要在tooltip里显示地图的相应省份的名称。使用我上面的配置，如果通过js方式引用地图数据的话，就可以用{b}拿到身份名称，也可以用function拿到；但如果是通过json方式的话就怎么也拿不到了。

**Comment by dreamerhammer** [comment]
> 别的其他是没什么区别。不过我现在碰到的情况是我需要在tooltip里显示地图的相应省份的名称。使用我上面的配置，如果通过js方式引用地图数据的话，就可以用{b}拿到身份名称，也可以用function拿到；但如果是通过json方式的话就怎么也拿不到了。

@GloriaCHL 我也遇到这个问题，请问你说的用js方式是什么方式？

**Comment by qtttttttttting** [comment]
你好，我也遇到了map tooltip拿不到数据的情况，请问要怎么解决
