### ISSUE TITLE
itemSymbol in the visualMap (piecewise) can't be set

### ISSUE THREAD

**Issue by jarben** [apache/echarts#5719]
Version: 3.5.4

Seems like itemSymbol can't be changed to "circle" or other values in visualMap: 

![image](https://cloud.githubusercontent.com/assets/561365/25891744/744f61f4-3572-11e7-9d05-b6d2d8499a4b.png)

**Comment by yueshuiniao** [comment]
同样碰到这个问题

**Comment by hoganjobs** [comment]
目前使用中也遇到这个问题，不知道这个问题是否修复了？

**Comment by laurapizza** [comment]
@Ovilia `itemSymbol` issue

**Comment by sophia1024** [comment]
2021年了，itemSymbol依旧不生效

**Comment by sophia1024** [comment]
![image](https://user-images.githubusercontent.com/54983463/104982037-c091f900-5a44-11eb-954f-ae77a21a04ef.png)
$.get(ROOT_PATH + '/data/asset/data/aqi-beijing.json', function (data) {
    myChart.setOption(option = {
        title: {
            text: 'Beijing AQI'
        },
        tooltip: {
            trigger: 'axis'
        },
        xAxis: {
            data: data.map(function (item) {
                return item[0];
            })
        },
        yAxis: {
            splitLine: {
                show: false
            }
        },
        toolbox: {
            left: 'center',
            feature: {
                dataZoom: {
                    yAxisIndex: 'none'
                },
                restore: {},
                saveAsImage: {}
            }
        },
        dataZoom: [{
            startValue: '2014-06-01'
        }, {
            type: 'inside'
        }],
        visualMap: {
            top: 10,
            itemWidth: 10,
            itemHeight: 10,
            itemSymbol:'diamond',
            inRange: {
                color: ['#121122', 'rgba(3,4,5,0.4)', 'red'],
            },
            outOfRange:{
             color: '#999',
              symbol: 'pin',
        },
            right: 10,
            pieces: [{
                gt: 0,
                lte: 50,
                color: '#096',
                symbol: 'pin',
            }, {
                gt: 50,
                lte: 100,
                color: '#ffde33',
                symbolSize: 12,
                symbol: 'diamond',
            }, {
                gt: 100,
                lte: 150,
                color: '#ff9933',
                symbol: 'circle',
            }, {
                gt: 150,
                lte: 200,
                color: '#cc0033'
            }, {
                gt: 200,
                lte: 300,
                color: '#660099',
                   symbol: 'diamond',
            }, {
                gt: 300,
                color: '#7e0023'
            }],
        },
        series: {
            name: 'Beijing AQI',
            type: 'line',
            symbol:"arrow",
            data: data.map(function (item) {
                return item[1];
            }),
            markLine: {
                silent: true,
                data: [{
                    yAxis: 50
                }, {
                    yAxis: 100
                }, {
                    yAxis: 150
                }, {
                    yAxis: 200
                }, {
                    yAxis: 300
                }]
            }
        }
    });
});
