### ISSUE TITLE
饼图标签可否在左右两侧上下对齐

### ISSUE THREAD

**Issue by zhouboluo** [apache/echarts#5733]
### One-line summary [问题简述]
如题，有时候标签太多，会显得有点乱，能不能上下对齐

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
如下这种效果：
![11](https://cloud.githubusercontent.com/assets/7812751/25978784/11691068-36f7-11e7-814c-91fc5e271fa7.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by dyl169** [comment]
![image](https://user-images.githubusercontent.com/19199353/62934731-d9ca5b00-bdf7-11e9-8522-2eccb497b1af.png)
是的 这种效果需要如何配置或者计算
