### ISSUE TITLE
利用toolbox里面切换成line时，boundaryGap为true也不留白

### ISSUE THREAD

**Issue by yangxiaoqiao2016** [apache/echarts#5775]
### One-line summary [问题简述]
刚生成的折线图boundaryGap是有作用的，但是通过toolbox切换成折线的时候是没有作用的。
测了一下echart2的版本没有这个问题。echarts3的都有这个问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.4.0
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

通过toolbox切换成折线的时候boundaryGap需要有作用

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
                		restore: { show: true },
                        magicType: {
                            type: ['line', 'bar']
                        },
                        saveAsImage: {},
                    },
    },
    xAxis: {
        type: 'category',
        boundaryGap: true,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[220, 182, 191, 234, 290, 330, 310]
        }
    ]
}

```

**Comment by publisherfk** [comment]
`我也遇到了这个问题，切换之后，boundaryGap自动置为了false，我本来准备试着` toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {
                type: ['line', 'bar'],
                option:{
                    xAxis:{
                		boundaryGap: true,
                	}
                }
            },
            restore: {},
            saveAsImage: {}
        }
    },`
也没起作用

**Comment by YGYOOO** [comment]
这个问题还没有人来解决么。。。。

**Comment by egoipse** [comment]
Same issue here... No solution yet, at 2026
