### ISSUE TITLE
希望能够增加【流程图】功能

### ISSUE THREAD

**Issue by guofei9987** [apache/echarts#5787]
对flowchart等一众丑陋的流程图工具感到绝望了

**Comment by guhuajun** [comment]
嗯，也不需要做成下面收费组件那么的复杂
1. http://draw2d.org/draw2d/
2. https://www.jointjs.com/

**Comment by billychou** [comment]
现在新版本有流程图吗？ @guofei9987

**Comment by WaldenBing** [comment]
同上，强烈建议推出流程图，虽然用借助关系图也能简单实现流程图功能，但是复杂点的实现就太费劲了

**Comment by guofei9987** [comment]
仍然没有
