### ISSUE TITLE
请问一下ubuntu下firefox散点图无法显示是什么问题？

### ISSUE THREAD

**Issue by mazechi** [apache/echarts#579]
使用遨游浏览器是可以显示的，不清楚是哪里配置有问题么，有些图又可以显示……
![snapshot1](https://cloud.githubusercontent.com/assets/3959927/3961038/c43026f0-274b-11e4-845b-741353ee51de.png)
移动到点上面是会显示出来那个点，说明数据载入应该没有问题
![snapshot2](https://cloud.githubusercontent.com/assets/3959927/3961039/c4344f3c-274b-11e4-9dc1-742eda6588ec.png)
下面这个又可以显示，真的很疑惑……

**Comment by liminjun** [comment]
Mark.
