### ISSUE TITLE
visualMap[i]-piecewise.pieces以0分段问题

### ISSUE THREAD

**Issue by arrinhzh** [apache/echarts#5801]
### One-line summary [问题简述]
我想实现以0为分界线，实现大于0的部分做处理，小于0的部分做处理
![2017-05-22_163825](https://cloud.githubusercontent.com/assets/19544024/26299385/3541c46c-3f0d-11e7-8685-323a2b8ee6c4.jpg)
，但是
 pieces: [{
	            
	                lte: 0,
	                color: 'rgba(0,0,255,0.6)'
	            }, {
	                gt: 0,
	             
	                color: 'rgba(255,0,0,0.6)'
	            }]
报错。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win

### ECharts option [ECharts配置项]

```javascript
option = {

	    title: {
	        text: '到期损益'
	    },
	    tooltip : {
	        trigger: 'axis',
	        axisPointer: {
	            type: 'cross',
	            label: {
	                backgroundColor: '#6a7985'
	            }
	        }
	    },
	    legend: {
	        data:['到期损益']
	    },
	    visualMap: {
	        top: 10,
	        right: 10,
	        pieces: [{
	               // gt: -500,
	                lte: 0,
	                color: 'rgba(0,0,255,1)'
	            }, {
	                gt: 0,
	               // lte: 500,
	                color: 'rgba(255,0,0,1)'
	            }]
	            ,
	            outOfRange: {
	                color: '#999'
	            }
	        },
	    grid: {
	        left: '3%',
	        right: '4%',
	        bottom: '3%',
	        containLabel: true
	    },
	    xAxis : [
	        {
	            type : 'category',
	            boundaryGap : false,
	            splitLine:{
	                show:true
	            },
	            data:[7,8,9,10,11,12,13]
	        }
	    ],
	    yAxis : [
	        {
	            type : 'value'
	        }
	    ],
	    series : [
	        {
	            name:'到期损益',
	            type:'line',
	            stack: '总量',
	            areaStyle: {normal: {
	               
	            }},
	            data:[90,80,-10,90,10,-50,-40]
	        }
	    ]
	
}

```

### Other comments [其他信息]

如果把 pieces: [{
	               // gt: -500,
	                lte: 0,
	                color: 'rgba(0,0,255,1)'
	            }, {
	                gt: 0,
	               // lte: 500,
	                color: 'rgba(255,0,0,1)'
	            }]
注释掉的两行打开任意一行就可以显示，但是不能实现我就想以0分隔两段吗？

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/blob/master/src/component/visualMap/PiecewiseModel.js#L372

**Comment by mmfjx** [comment]
遇到同样的问题，只能讨巧，中间加一个范围很小的分段
pieces = [ { min: top, color: '#FF0000' },
 { min: top - 0.001, max: .top, color: '#00BB58' },
  { max: top - 0.001, color: '#00BB58' }]

**Comment by helgasoft** [comment]
@mmfjx's workaround is valid - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsCeBBAHhAzgFzIC-ANGrDrgcUrGBiAKbEDkAxgIZjMDmwAE4Y2scpXzNBEZkVgBtSulTpVDJq1hsANhGjM2ZWLv0BlRts30A7hAAmYABbEArGIpr0XQcy7mMlnQkSmKUALoesHY8XJJgxIpqKp52EAC2zND4UFkJbBi-goZaIILAAGYQYGwRIej4wACughyaiZ7KdZ4F3uwATAAMAIwDhl1qpRVVxCMD4-7zyR3oPYL9w0Njy6qTlfGwg3Pb4ttLy6vrQ31b27C707AAtEMuR8sny2cdF1qDQwDMN22932_wGbw6wQ6YRCUNgtXQADcCI0uNoALJcEAJEJfBigVwDSJqaR8Rz7IldEAyVpydodejaXjER4DAB04OGRg4wG0QnYPjsog-HQA9KLYGi0sB8GBYPhGhxWsw7PjYI57MwGI4tQAvKTAYxcABGzG0i1gfH2rI54KGRiZxHZnPtsB5fLWWjAgi4WRA3ky1QdJrN7C0Is89Ctmmddu5vP5WmN2kaBlC0OJqiaYAA8uUAEq-vhWebuxNsADEADZmDWa2wunD0HCYSQANxAA)
![image](https://user-images.githubusercontent.com/13038071/231564547-098f66e4-5e13-4166-849e-77d585cf0d8a.png)
