### ISSUE TITLE
Tooltip disappears when data updated

### ISSUE THREAD

**Issue by snowl** [apache/echarts#5812]
### One-line summary [问题简述]
When a new option is pushed to the chart with new data (and the user is hovering over data), the tooltip stops showing for the user.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.4
+ Browser version [浏览器类型和版本]: Google Chrome 57
+ OS Version [操作系统类型和版本]: Fedora 24

### Expected behaviour [期望结果]
The tooltip continues showing (if the cursor is over new data, the new data is updated into the tooltip).

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            params = params[0];
            var date = new Date(params.name);
            return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + params.value[1];
        },
        axisPointer: {
            animation: false
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: 'a',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }]
}

```

### Other comments [其他信息]

You can see this happening in this demo: https://ecomfe.github.io/echarts-examples/public/editor.html?c=dynamic-data2

**Comment by ilovedesert001** [comment]
any progress ?

**Comment by snowl** [comment]
no

**Comment by iamtheddrman** [comment]
This is one that I'd like to see fixed as well. I was considering using this for a project with dynamic data, but with non-functional hover text, it won't work for my users unfortunately. I'd be happy to lend a hand if someone could point me in the right direction.
