### ISSUE TITLE
关于雷达图 symbol 标记图形样式的设置

### ISSUE THREAD

**Issue by ghost** [apache/echarts#5845]
### One-line summary [问题简述]
新版 3.0 中 雷达图在 series -> data -> itemStyle -> norma l-> color  中 color 没有回调方法所以不能对单个 symbol 标记设置不同的颜色，目前只能统一设置同一种颜色**（但是 2.0 中 color: function(params) 是可以单独设置不同颜色的）**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: 所有
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
鉴于 2.0 中存在过这个功能，是否在新版 3.0 中是故意去掉此功能的还是 BUG 或者 API 进行了调整？望告知？以及如何实现我阐述的功能. ThankYou.

### ECharts option [ECharts配置项]
chartOptions: {
				    	radar: {
				    		shape: 'circle',
					        indicator: [
					           { name: '可用', max: 100},
					           { name: '健康', max: 100},
					           { name: '繁忙', max: 100},
					           { name: '故障', max: 100},
					           { name: '危险', max: 100}
					        ],
					        name: {
						    	textStyle: {
						    		color: 'black'
						    	},
				                formatter: function(v, e) {
				                    v == '可用' && (e.nameTextStyle.color = '#70CE46');
	                                v == '健康' && (e.nameTextStyle.color = '#81A8C9');
	                                v == '繁忙' && (e.nameTextStyle.color = '#D268D4');
	                                v == '故障' && (e.nameTextStyle.color = '#EF5A44');
	                                v == '危险' && (e.nameTextStyle.color = '#FFB132');
				                    return v;
				                }
				            }
					    },
					    series: [{
					        name: '预算',
					        type: 'radar',
					        symbolSize: 14,
					        itemStyle: {
					            normal: {
					                lineStyle: {
					                    width: 1,
					                    color: '#4D9CC3'
					                }
					            }
					        },
					        data : [
							    { 
							    	value : [100, 100, 100, 100, 100],
							    	name : '数据项一',
							    	itemStyle: {
					                    normal: {
					                        color: function(params){
					                        	// 3.0 中无此回调？
					                        }
					                    }
				                    }
							    }
							]
					    }]
					}

### Other comments [其他信息]
如何设置不同颜色
![11111](https://cloud.githubusercontent.com/assets/28969879/26479572/f89193ba-4206-11e7-93cc-9e238ceb65e9.jpg)

**Comment by bigggge** [comment]
有方法了吗？

**Comment by pandashuai** [comment]
同问，怎么设置该点的颜色
