### ISSUE TITLE
希望能尽快升级一下仪表盘

### ISSUE THREAD

**Issue by mike-han** [apache/echarts#5849]
项目要用一个chart库，我试用了一下echarts，感觉各方面都不错：
移动端可以放大拖动

- 色彩也好看
- 配置也灵活
- 而且可以通过formatter实现国际化

就选了echrts,然后。。

没想到会这么多用到仪表盘
但是echarts的仪表盘太单一了

- 没有横竖类型的  
- 也没有内部上升的动画效果（可以看一下amcharts的仪表盘https://www.amcharts.com/demos/animated-gauge/），
- 指针不可以自己定义样式，

希望能尽快升级一下，不胜感激

**Comment by 100pah** [comment]
> 没有横竖类型的
横竖类型指的是？（有没有例子？）

**Comment by Mignon-han** [comment]
@100pah 类似这个：http://gallery.echartsjs.com/editor.html?c=xB1Hg1l11Z
是我用bar chart 模拟的，也是我们暂时代用的解决方案
如果要做的话，希望加上设置 indicator 来做一些临界值的标记，现在是用echarts的graphic模拟的

可以看一下wijmo 的guage:http://demos.wijmo.com/5/Angular/GaugeIntro/GaugeIntro/

**Comment by Mignon-han** [comment]
希望能尽快升级一下仪表盘，加一些新的类型和功能，在实际使用中，仪表盘还是使用的比较多的

**Comment by zhanghongyublog** [comment]
@Mignon-han  请问怎么利用formatter进行国际化呀

**Comment by Mignon-han** [comment]
@zhanghongyublog 
举个例子, 让y轴的刻度值遵循某种语言的显示规则。
```
function localization(){
      ...
}

yAxis.axisLabel.formatter = function(value){
    return localization(value);
}
```

**Comment by AndyShaoxianfeng** [comment]
指针不可以自己定义样式现在好像还没做到吧？@pissang

**Comment by confirmTing** [comment]
我也想要自定义指针，希望大佬们能够支持

**Comment by yangdongMC** [comment]
@pissang 大佬请问一下，这个自定义指针这块有列入支持计划吗？配置文档翻阅了好几遍没有找到一个便捷可解决的办法。

**Comment by plainheart** [comment]
自定义指针从 5.0 已经开始支持
