### ISSUE TITLE
X轴如果是时间数据怎么实现

### ISSUE THREAD

**Issue by skynice** [apache/echarts#586]
目前X轴有枚举值类型和数值类型，如果X轴是时间类型的话，如何使用数值类型的轴实现？

**Comment by houyewei** [comment]
太不靠谱了把，都不解释清楚

**Comment by pissang** [comment]
time 类型和数值类型一样，不过提供了额外的时间格式化

**Comment by houyewei** [comment]
谢谢，不过还是建议在文档里完善下，文档貌似没有解释这块

Sent from Outlook




On Tue, May 19, 2015 at 8:27 PM -0700, "Yi Shen" <notifications@github.com> wrote:












time 类型和数值类型一样，不过提供了额外的时间格式化

**Comment by pissang** [comment]
嗯，谢谢建议

**Comment by baibaimoonish** [comment]
您好，请问一下x轴time类型 具体支持哪些时间数据的格式？“yyyy-mm-dd”？“yy／mm／dd”？
