### ISSUE TITLE
scale缩放后tooltip被遮挡

### ISSUE THREAD

**Issue by leiyongliang** [apache/echarts#5883]
当把整个canvas通过scale缩放后，大概scale的值大于1.2时，tooltip会显示在图表的下层，不能显示在最顶层，以至于被遮挡

![image](https://cloud.githubusercontent.com/assets/25165099/26662341/ccde0402-46b5-11e7-9b18-0620b147354a.png)
![image](https://cloud.githubusercontent.com/assets/25165099/26662362/ed3456c0-46b5-11e7-954d-1fddab7fa353.png)
![image](https://cloud.githubusercontent.com/assets/25165099/26662658/18cde9a2-46b8-11e7-9a6c-6c4806157a71.png)

**Comment by leiyongliang** [comment]
@leeight @cnberg @firede @chriswong @firedfox

**Comment by luxinru** [comment]
+ 1

**Comment by luxinru** [comment]
我也碰到这个问题

**Comment by leipeng** [comment]
try tooltip.extraCssText: 'translateZ(999px);'

**Comment by Yangerle** [comment]
@leipeng 用你的方法解决啦，谢谢
