### ISSUE TITLE
在vue中使用echarts，在tooltip中的formatter使用自定义html无法绑定组件内函数作为事件

### ISSUE THREAD

**Issue by feng-fu** [apache/echarts#5888]
### One-line summary [问题简述]

在vue中使用echarts，在tooltip中的formatter使用自定义html无法绑定组件内函数作为事件， 是否其事件必须为全局事件，如果要使用vue中的事件该怎么操作，望解决。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]: chrome 58
+ OS Version [操作系统类型和版本]:windows 10

### ECharts option [ECharts配置项]

```javascript

formatter: function(params, ticket, callback){
  return `<div style="width:20px;height: 20px;" onclick="${this.todoSth(params.data[0])}"></div>`
}
...

methods: {
  todoSth:function(){
      // todo sth...
  }
}

```

### Other comments [其他信息]

![qq 20170601160002](https://cloud.githubusercontent.com/assets/20320122/26670203/5d82f170-46e3-11e7-98de-24b9f1d7970b.png)

**Comment by 531431988** [comment]
同求

**Comment by 531431988** [comment]
https://codepen.io/anon/pen/KEPeqa
在线示例，求解，如何绑定

**Comment by wangxuesong29** [comment]
@531431988 @feng-fu 
你们好！你们最后的绑定是如何实现的呢？

**Comment by z953218350** [comment]
> @ 531431988 @ feng-fu
> 你们好！你们最后的绑定是如何实现的呢？

例如：把formatter: function(params) {
} 
改为
formatter: (params) =>  {
}
就可以了

**Comment by zier95** [comment]
同上问题，求解决

**Comment by pissang** [comment]
5.0 开始支持返回 dom 节点，可以在这个节点上绑定事件
