### ISSUE TITLE
series map结合百度地图 求解

### ISSUE THREAD

**Issue by wuruihua** [apache/echarts#5935]
### One-line summary [问题简述]
series map现在可以使用geo坐标系，但是不支持coordinateSystem:bmap

# Expected behaviour [期望结果]

coordinateSystem:bmap  series-map可以叠加在百度地图

### ECharts option [ECharts配置项]

```javascript
option = {
bmap:{

}
,series:[{
type:'map',
coordinateSystem:bmap
}]
}

```

### Other comments [其他信息]
![_2017-06-07t08-43-13 617z](https://user-images.githubusercontent.com/12755809/26869842-728ba014-4ba0-11e7-8404-ef09a353901b.png)

**Comment by heyingjie** [comment]
有同样的需求，将echarts的map作为行政区域边界叠加在百度地图上。但是不知道怎样将百度地图的坐标与ECharts map的坐标对应起来。还有就是缩放的时候让两个地图同步缩放

**Comment by wuruihua** [comment]
已解决 修改echarts底层代码 在drawGeo时将 坐标转换后再进行绘制

**Comment by pissang** [comment]
@wuruihua 赞，后续会支持这个特性

**Comment by alicelh** [comment]
@wuruihua 求问解决方案，看源代码不是很懂，希望能给些提示，谢谢！

**Comment by egisxp** [comment]
也遇到该问题，什么时候能支持？

**Comment by zss1004504439** [comment]
> 已解决 修改echarts底层代码 在drawGeo时将 坐标转换后再进行绘制

大神 怎么实现的？
