### ISSUE TITLE
直角坐标系热力图如何去除网格线

### ISSUE THREAD

**Issue by kliffhuang** [apache/echarts#6011]
### One-line summary [问题简述]

希望在3.0版本中直角坐标系热力图。已设置去除x轴y轴的坐标及splitLine，但似乎图上的网格还在。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome/webkit
+ OS Version [操作系统类型和版本]:win10/android6.0

### Expected behaviour [期望结果]

期望如同2.0的百度页面热力图一样纯净

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {},
    xAxis: {
        type: 'value',
        show: false,
        splitLine: {
            show: false
        },
        data: xData
    },
    yAxis: {
        type: 'value',
        show: false,
        splitLine: {
            show: false
        },
        data: yData
    },
    visualMap: {
        min: 0,
        max: 1,
        show: false,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    series: [{
        name: 'Gaussian',
        type: 'heatmap',
        data: data,
    }]
};

```

### Other comments [其他信息]

![qq 20170616210240](https://user-images.githubusercontent.com/7894597/27227712-2819ccac-52d7-11e7-989f-3fa480df2b70.png)

**Comment by pissang** [comment]
这个不是网格

**Comment by kliffhuang** [comment]
这是热力点/散点绘制的边框吗？热力图系列中，是否有办法去除？已试了散点图，效果稍好，但花了双倍的生成时间。

**Comment by tomcake** [comment]
题主找到方法了嘛？感觉这个是辅助线，是否无法去除？

**Comment by tomcake** [comment]
> 这个不是网格

这个可以去除嘛？如果可以去除，热力图更清爽！

**Comment by MikeNo007** [comment]
1

**Comment by feiniao33** [comment]
> 这个不是网格

这个背景线不能去除，真心不好看，像是加了马赛克，很影响使用。希望有解决办法下，谢谢！

**Comment by pissang** [comment]
@feiniao33 你用的是什么版本？这个已经有优化过了

**Comment by feiniao33** [comment]
> @feiniao33 你用的是什么版本？这个已经有优化过了
感谢回复，    
"echarts": "^5.3.0", 在数据量大的时候很明显，下面的官方示例中也能看到有很多“背景线”，不知道如何去除？
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

**Comment by feiniao33** [comment]
> @feiniao33 你用的是什么版本？这个已经有优化过了

感谢回复，    
"echarts": "^5.3.0", 在数据量大的时候很明显，下面的官方示例中也能看到有很多“背景线”，不知道如何去除？
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

**Comment by feiniao33** [comment]
> @feiniao33 你用的是什么版本？这个已经有优化过了
要是有解决方法告知一下哈，谢谢~

**Comment by feiniao33** [comment]
> @feiniao33 你用的是什么版本？这个已经有优化过了

感谢回复，
"echarts": "^5.3.0", 在数据量大的时候很明显，下面的官方示例中也能看到有很多“背景线”，不知道如何去除？
https://echarts.apache.org/examples/en/editor.html?c=heatmap-large

**Comment by plainheart** [comment]
@feiniao33 这不是“网格线”或者“背景线”，而是因为计算精度问题导致的“缝隙”，一般只有在 dpr 不是整数时会出现。[fix-heatmap-gap](https://github.com/apache/echarts/tree/fix-heatmap-gap) 是针对此问题的修复分支。

**Comment by feiniao33** [comment]
> @feiniao33 这不是“网格线”或者“背景线”，而是因为计算精度问题导致的“缝隙”，一般只有在 dpr 不是整数时会出现。[fix-heatmap-gap](https://github.com/apache/echarts/tree/fix-heatmap-gap) 是针对此问题的修复分支。

谢谢，这个问题原来有解决方案了。我看到是通过add 0.5px to avoid the gaps可以修复。但是我不明白的是，我应该怎么做才能解决这个问题，我是用Angular，在安装的echarts下没有找到您修改的这个代码的区域，没办法直接按照这个方式修改，我应该怎么做才能修复这个问题呢？谢谢！

**Comment by feiniao33** [comment]
> @feiniao33 这不是“网格线”或者“背景线”，而是因为计算精度问题导致的“缝隙”，一般只有在 dpr 不是整数时会出现。[fix-heatmap-gap](https://github.com/apache/echarts/tree/fix-heatmap-gap) 是针对此问题的修复分支。

找到修改的地方了了，在node_modules/echarts/lib/chart/heatmap/HeatmapView.js下进行fix-heatmap-gap的 add 0.5px to avoid the gaps一样的代码修改，就可以消除“缝隙”，非常感谢！完美解决！

**Comment by plainheart** [comment]
@feiniao33 好的 抱歉没注意到你的上个评论 稍后我会提个PR 看看能不能合入 5.3.2

**Comment by feiniao33** [comment]
@plainheart 没事儿~能合进去就更好了！感谢感谢！

**Comment by feiniao33** [comment]
@plainheart  我发现ng build之后，没能把修改后的代码打包进去，不知道啥问题了。坐等5.3.2修复这个问题！！请问什么时候会出5.3.2呀？
