### ISSUE TITLE
Cannot select overlapping bubbles in a scatter chart

### ISSUE THREAD

**Issue by subhc** [apache/echarts#6034]
### One-line summary [问题简述]

Cannot select overlapping bubbles in a scatter chart because z2 index of one bubble brings it on top and hides the other bubbles. Please check the example.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.4
+ Browser version [浏览器类型和版本]: Safari 10.1.1 (12603.2.4)
+ OS Version [操作系统类型和版本]: macOS Sierra v10.12.5

### Expected behaviour [期望结果]

It should be configurable that in a scatter chart bigger bubbles should not come on top.

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'value',
        max: 50
    },
    yAxis: {
        type: 'value',
        max: 50
    },
    series: [{
        type: 'scatter',
        symbolSize: d => d[2],
        label: {
            emphasis: {
                show: true,
                formatter: param => param.data[3],
                position: 'top'
            }
        },
        itemStyle: {
            normal: {
                color: param => param.data[3]
            }
        },
        data: [
            [25, 25, 100, 'red'],
            [25, 25, 25, 'green']
        ]
    }]
}

```

### Other comments [其他信息]

This is happening at [/src/util/graphic.js#L253](http://github.com/ecomfe/echarts/blob/7e84c33318c5bf07085f2953507323ad95432192/src/util/graphic.js#L253)
can z2 elevation be made optional?

**Comment by rajukiran** [comment]
Can someone provide the alternate to avoid overlapping items which are in the same time frame...!

**Comment by natalidedik** [comment]
I can still sort bubbles by size by descending, but still it is unreal to select the smallest ones, no matter what z index is set. Actual fix on that is required here

**Comment by jsahkjfhasjhfas** [comment]
现在还是没有解决
