### ISSUE TITLE
K线图之间每根柱线的间距（图）

### ISSUE THREAD

**Issue by benweizhu** [apache/echarts#6064]
### One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/5471228/27540038-456712a6-5ab1-11e7-9097-2ed164236287.png)

比如它和下面的柱状图就对不上

![image](https://user-images.githubusercontent.com/5471228/27540294-45bfc01c-5ab2-11e7-9c7b-90651a11cbb8.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望能够调整他们之间的间距

barWidth已经是自适应了，但是由于柱子间距的还是太大了，所以对不上

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以设置 barCategoryGap

**Comment by benweizhu** [comment]
candlestick没有barCategoryGap，只有bar才有~

**Comment by MrLiZ** [comment]
有解决吗？

**Comment by benweizhu** [comment]
我也想问，这个有解决吗？

**Comment by MrLiZ** [comment]
是不是还没解决？没解决的话晚点我再问问

**Comment by benweizhu** [comment]
一年了兄弟，有解决吗？

**Comment by 13560280319** [comment]
我也想问，echart设置不了吗，没有这个属性
