### ISSUE TITLE
Any english version via NPM or something ?

### ISSUE THREAD

**Issue by l2aelba** [apache/echarts#6090]
**Good job** so far guys, thanks for a **flexible chart library**. 👍 

But I just was wondering one thing about any **official english version** 

via `npm install echarts` and `import echarts from 'echarts'` or something ?

_PS: I see its chinese texts and axis-id `��-�0` and more._

**Comment by pissang** [comment]
Thanks! We will think about publishing a english version

**Comment by LogIN-** [comment]
Is there any progress on this? 
At least if no English version is explicitly published on NPM or somewhere, we should make this couple of strings to be translatable by Translation files, this actually also makes more sense.

**Comment by JoshSchoen** [comment]
I can see that there is a langEN.js but no way to really use in when using npm that I can see. Any help or  update is very much appreciated!

**Comment by gajus** [comment]
```js
import echarts from 'echarts/dist/echarts-en';

```
