### ISSUE TITLE
图例颜色显示问题

### ISSUE THREAD

**Issue by ironmp** [apache/echarts#615]
图例颜色显示是使用根据该值索引series中同名系列所用的图表类型和itemStyle的，但有一个需求是图例就是显示series值的内容，每个项颜色不一样，但如果值的内容有相同时颜色显示就混乱了，没有按预期的每个项一个颜色去显示，请问这个问题有什么好的解决办法吗？
还有一个小问题是如果div没有指定宽高怎么控制图的大小？

**Comment by changbb** [comment]
请问楼主是怎么解决的？谢谢！

**Comment by RephoneYin** [comment]
> 非常感谢，已经完美解决！谢谢了，我还得多多学习。
@ironmp 
咋解决的呀? 遇到了同样的问题, 颜色不能设置, 文档说, 可以通过svg来是设置颜色, 但是又没有例子, 哎! 脑瓜疼, 脑瓜疼!!
