### ISSUE TITLE
echarts3 使用type=‘graph’ 属性中的draggable 拖拽 ，如何解决鼠标松开就定位当前显示效果？

### ISSUE THREAD

**Issue by hello-jin** [apache/echarts#6219]
### One-line summary [问题简述]

echarts3 使用type=‘graph’ 属性中的draggable 拖拽 ，如何解决鼠标松开就定位当前显示效果？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3
+ Browser version [浏览器类型和版本]: 谷歌
+ OS Version [操作系统类型和版本]: windows 7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
> 如何解决鼠标松开就定位当前显示效果

抱歉没有理解这句话。

**Comment by zhengsusu2014** [comment]
同问啊，楼主的意思就是，关系图上的节点被拖拽后不要回弹，拖到了哪个坐标就显示在哪个坐标上。

**Comment by stillsilly** [comment]
这个问题后来解决了吗……

**Comment by stillsilly** [comment]
有没有每个节点的dragend事件可以设置啊？或者设置引力斥力为0之类的，文档翻了好久没找着解决方案……

**Comment by zdRan** [comment]
其实我也找了好久，type: 'graph'，我期望的是，当拖动A节点的时候，其他节点不动。配置上draggable: false,好像没有什么效果。

**Comment by ArrayZheng** [comment]
现在能实现了吗
