### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null at js/echarts-original.js:23051

### ISSUE THREAD

**Issue by ahunigel** [apache/echarts#628]
Uncaught TypeError: Cannot read property 'getAttribute' of null
 at js/echarts-original.js:23051

不停刷新页面，然后某次就出现以上错误，所有chart都一片空白了

**Comment by likunlovecode** [comment]
Error in nextTick: "TypeError: Cannot read property 'getAttribute' of null"；我的报错是这样的this.$nextTick(function() {
            this.drawPie('main');
            this.drawLie('main2');
            // this.drawKie('main3');
        })
