### ISSUE TITLE
Issue with connectNulls and overflow hidden

### ISSUE THREAD

**Issue by gpoussel** [apache/echarts#6284]
### One-line summary [问题简述]
Nulls are connected only if the point before and after are currently displayed.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.x
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
I am looking for a way to use ``connectNulls`` even when the last point before null value is not currently displayed.
Today, the line is not connected to the left-side of the chart. Is it a bug of ``connectNulls`` or am I missing another option? I thought that ``clipOverflow`` would do the job, but it seems not.

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    dataZoom: [
        {
            type: 'slider',
            xAxisIndex: 0,
            filterMode: 'empty'
        }
    ],
    series: [
        {
            name:'联盟广告',
            type:'line',
            data:[220, 182, null, 234, 290, 330, 310],
            connectNulls: true,
            clipOverflow: false,
            symbolSize: 10
        }
    ]
}

```

### Other comments [其他信息]

![github-issue1](https://user-images.githubusercontent.com/217122/28610588-184d88aa-71e9-11e7-81db-313bdda39ac5.png)
![github-issue2](https://user-images.githubusercontent.com/217122/28610620-37a7f1b8-71e9-11e7-943a-7f79b3700be6.png)

**Comment by paulzi** [comment]
+1! zoom break line chart...

**Comment by bragma** [comment]
The problem also shows in the demos, ex:

https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-draggable

If you zoom on the left, the leftmost point is filtered and the chart is cut. I've found a workaroud using filterMode: "none", but there is another bug: the symbol is not removed:

![image](https://user-images.githubusercontent.com/1101058/31602609-eef53f42-b25d-11e7-9009-04d4baeef819.png)

**Comment by tmtron** [comment]
+1 to avoid auto-close

**Comment by tmtron** [comment]
+1 to avoid auto-close
