### ISSUE TITLE
Echarts内存不释放问题

### ISSUE THREAD

**Issue by rjgaoyuan** [apache/echarts#631]
Echarts 在地图初始化后，对MarkPoint赋值，然后地图冒泡，发现如果定时切换MarkPoint的值，使得地图上的点切换会导致浏览器占用的内存不断增加而不会释放。然后我去看了一下Echarts 关于百度迁徙那个例子，在我来回切换图例，地图变幻数据的时候，内存也是如此。不断切换图例，内存会不断增长。

http://t.cn/8sasfnN

想问一下，这种通过对地图上的点切换后导致内存不断上涨的问题有什么好的解决办法吗？

**Comment by 823844596** [comment]
请问该问题怎么解决的？谢谢~

**Comment by yangbai1991** [comment]
我也出现了同样的问题，绘制的地图，30s更新一下，一段时间后页面就卡死了。。。

**Comment by yangbai1991** [comment]
这个我最后试了一下，还是可以解决的，就是如果已经初始化过了，再次使用的时候是否一下就可以了！
核心代码如下：
`
var map = {
    chart: echarts.init(document.getElementById('chart')),
    scatter: function() {
        map.chart && map.chart.dispose();
        map.chart = echarts.init(document.getElementById('chart'));
    }
}
`
