### ISSUE TITLE
echart3绘制城市地图（深圳），地图数据老旧，没有光明新区和大鹏新区

### ISSUE THREAD

**Issue by 417673259** [apache/echarts#6310]
根据下载后得到的json数据，绘制城市地图，但是数据应该很近没更新了。
深圳没有光明新区，而且大鹏新区已经不属于龙岗新区，独立出来了。

希望能更新下这些数据。

**Comment by 100pah** [comment]
官网上的『地图下载』中的地图数据是实时取自第三方地图提供方。

**Comment by 417673259** [comment]
那请问有什么策略去处理这种问题吗，即绘出来的地图不准确，落后了

**Comment by xcchcaptain** [comment]
遇到同样的问题，即使找到了市级的矢量地图网站，很难找到资源
