### ISSUE TITLE
简单地提供ES Module下的静态分析和按需构建的能力

### ISSUE THREAD

**Issue by otakustay** [apache/echarts#6346]
在使用echarts的时候，如果用最简单的办法：

```js
import echarts from 'echarts'
```

会将整个包都引入进来，并且无法按照使用的功能进行按需的构建，总大小约有250KB，对于很多应用来说，这个体积太过庞大

如果需要按需构建，则要自己手动选择使用的组件，通常是这样的：

```js
import echarts from 'echarts/lib/echarts';

import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/line';
import 'echarts/lib/component/tooltip';
```

这里的一个关键问题是，`chart/*`和`component/*`的引用并没有对应的变量以及使用之处，这引申出2个问题：

1. 容易忘记`import`
2. 容易在移除相关代码后忘了删除`import`

其中前者还算比较容易在测试过程中发现，而后者更容易造成bundle体积的无端浪费

基于此，我希望echarts可以提供这样的功能：

```js
import echarts from 'echarts';
import {bar, line} from 'echarts/chart/types';
import {tooltip, markArea} from 'echarts/component/types';

// bar === 'bar'
// line === 'line
// tooltip === 'tooltip'
// markArea === 'markArea'

const options = {
    ...,
    series: [
        {
            type: line,
            [markArea]: {...}
        }
    ]
};
```

简单来说，通过导出部分字符串常量在代码中留下静态的信息，这保证了对echarts完全向后兼容并且只包含极少的改动（提供一些常量）

之后可以通过开发一个`babel-plugin-echarts`来对这些`import`进行编译，以上代码的import部分就能编译成：

```js
import echarts from 'echarts/lib/echarts';
import 'echarts/chart/bar';
import 'echarts/chart/line';
import 'echarts/comopnent/tooltip';
import 'echarts/comopnent/markArea';

const bar = 'bar';
const line = 'line';
const tooltip = 'tooltip';
const markArea = 'markArea';
```

同时如果有没有用到的部分，也可以简单地进行Tree Shaking

**Comment by 100pah** [comment]
有个我还没想清楚的地方：

对于 
```js
var option = {
    legend: {
    },
    xAxis: {
    },
    grid: {
    },
    ...
}
```
这些并没有 `type` 属性的组件，怎么办呢？

**Comment by 100pah** [comment]
有两问题不知怎么解决：

（1）有些组件，在 `option` 中的名字和模块名是不一样的。
例如：
`xAxis` `yAxis` 需引用的是 `'echarts/lib/component/axis'`

（2）组件中也有 `type`，例如

```js
dataZoom: [
    {
        type: 'slider',
        ... 
    },
    {
        type: 'inside',
        ...
    }
]
```

那么组件的 type，放在哪里比较好呢？

**Comment by otakustay** [comment]
第1个问题其实不是很重要，可以让babel-plugin-echarts来做个配置表

第二个问题，就代码中的这个场景，我觉得可以有一个`import {slider, inside} from 'echarts/component/dataZoom/types';`来搞？其实我也不知道总共有多少这一类的东西……

**Comment by SidKwok** [comment]
@otakustay 根目录下的`index.js`有这些东西的详细目录，另外我觉得`babel-plugin-echarts`的确是一个很赞的想法。

**Comment by Cryrivers** [comment]
另外建议 npm 的包里提供支持 ES Module 的构建版本。（即保留 import, export，但编译成 ES5)，以方便 webpack 按需构建

**Comment by pissang** [comment]
@Cryrivers src 下的就是 es 模块的版本，除了 import 和 export，语法都是 es5 （其实是 es3）的。

但是不建议引用 src 模块，因为其它扩展引用的都是 lib 下的模块，如果同时引用了这些扩展的话可能会打包得到两个 echarts 命名空间

**Comment by Brooooooklyn** [comment]
有什么进展吗
