### ISSUE TITLE
treemap 可以设置缩放的最大最小比例嘛？

### ISSUE THREAD

**Issue by qilerongrong** [apache/echarts#6384]
treemap中是否可以设置缩放的最大最小比率？有时候并不希望用户无限的缩小或者放大，同时有时候想动态通过代码设置缩放比率。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ali-mohammadi** [comment]
did you find any solution on this?
