### ISSUE TITLE
散点图 在grid 设置背景图片纹理 ，如何在datazoom 缩放的时候纹理图片也跟着放大改变？

### ISSUE THREAD

**Issue by Watermelon-S** [apache/echarts#6442]
One-line summary [问题简述]

Version & Environment [版本及环境]

ECharts version [ECharts 版本]:
官方最新版

Browser version [浏览器类型和版本]:
谷歌浏览器最新版

OS Version [操作系统类型和版本]:
win7

Expected behaviour [期望结果]

就是想要设置背景图片可以和缩放功能一起有放大缩小 移动，寻求帮助~~~

ECharts option [ECharts配置项]
var bgPatternImg= new Image();
option = {
       grid:{
		show : true,
		width: 500,
		height: 300,
		backgroundColor: {
			image: bgPatternImg,
			repeat: 'repeat'
		}
	},
       dataZoom:[
		{
			type: 'inside',
			xAxisIndex: [0]  
		 },
		{
			type: 'inside',
			yAxisIndex:[0],
                 }
	]
}

**Comment by hcgit9527** [comment]
请问这个问题解决了吗   同问啊
