### ISSUE TITLE
桑基图如何实现点击一个node，高亮显示与之相连的link

### ISSUE THREAD

**Issue by DormyMo** [apache/echarts#6480]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by shangxinbo** [comment]
同问

**Comment by banzhuanl** [comment]
关注

**Comment by yy7054wyq5** [comment]
获得路径node和link，重新加样式，重新生成图表。。。

**Comment by jeeseDear** [comment]
> 获得路径node和link，重新加样式，重新生成图表。。。

具体怎么弄，您知道吗

**Comment by yy7054wyq5** [comment]
@jeeseDear 修改配置中的itemStyle和lineStyle.自己建立一个Map即可，通过node找到相邻的线。

**Comment by Andreyanghehe** [comment]
绑定点击事件, 获取点击的节点name, 筛选option中的data和links中name一致的节点,改变其style,重新加载图表. 我猜的 手动狗头
