### ISSUE TITLE
heatmap和graph结合问题

### ISSUE THREAD

**Issue by ZoeHuang13** [apache/echarts#6486]
### One-line summary [问题简述]
heatmap的坐标系只有cartesian2d和geo，但是我的graph的坐标系是none，layout是none，想在graph的基础上增加热力图。
尝试过将graph的坐标系设为cartesian2d，但是这样就不能缩放了，即使加入了datazoom，缩放的效果也和坐标系为none、layout为none不同。同时，heatmap的坐标系为cartesian2d时，好像也不能是geo上的那种热力图，只能是方块那种的...
那就只能用geo组件了，但是并不需要地图啊...这时的geo组件应该怎么写？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
graph的坐标系为none，layout为none，如何将heatmap与之对应？
heatmap数据的x、y值和graph数据的x、y值是对应的。

### ECharts option [ECharts配置项]

```javascript
option = {
var option = {
            series: [
                {
                    type: 'graph',
                    layout: 'none',
                    data: graph.nodes,
                    links: graph.links,
                    roam: true,
                    focusNodeAdjacency: true,
                    label: {
                        normal: {
                            show: 'true',
                            position: 'inside',
                            formatter: '{b}'
                        }
                    },
                    lineStyle: {
                        normal: {
                            color: 'source'
                        }
                    }
                }
            ]
        };
}

```

**Comment by 15036900300** [comment]
我也遇到了同意的问题，当graph设置coordinateSystem: 'cartesian2d'时，缩放效果就失效了，不知道该如何解决了

**Comment by 100pah** [comment]
@15036900300 graph设置coordinateSystem: 'cartesian2d'时，并且使用了 dataZoom 后，是可以缩放的。这种缩放效果不是您的期望么？

**Comment by 15036900300** [comment]
@100pah 这个缩放效果给人呈现的感觉有点卡顿，并且没有roam那种交互方式友好
