### ISSUE TITLE
可否提供一个专门供 require.js 加载的例子

### ISSUE THREAD

**Issue by kycool** [apache/echarts#657]
感觉官方提供的模块化加载文件有些凌乱，同时源码下载后发现文件摆放也是不知所谓

官方说：
如果你使用模块化开发但并没有自己的打包合并环境，或者说你不希望在你的项目里引入第三方库的源文件，我们建议你使用单文件引入，同模块化包引入一样，你需要熟悉模块化开发，这种方式只是我们预先帮你把常用图表组合连接合并在一起，你只需一个符合AMD规范的加载器，同时引入一个echarts相关js即可

我在 require.js 的配置文件中配置
         , 'echarts':    '../libs/echarts'
然后在调用文件中调用
        define([
          'jquery'
        , 'echarts/echarts-original'
        ], function(
          $
        , Echarts
        ) {
        ....
然后调用

```
initEcharts: function() {
  var obj = this;
  var myChart = Echarts.init($('#chartf'));
  .........
```

这里报错了  init 方法 未定义 同时在开发者工具中 输入 Echarts 也是 undefined
不得其解

**Comment by shangyue1110** [comment]
遇到同样的问题~~~在issues里找了很久~~在#918、#1153里面逐渐明白为什么会出这个问题~
echarts自带了一个esl的加载器~~上下文环境被require覆盖了~然后造成echarts自己的依赖没有正确加载，因此自身实例化不成功，最终导致echarts为未定义~不知道在require里面配一个shim是否能够解决~~正在尝试中~~
