### ISSUE TITLE
Echarts图表曲线在堆叠状态下，如果数据包含负数，实际绘图效果和预期不符

### ISSUE THREAD

**Issue by LiGaoLiang7** [apache/echarts#6602]
### Version & Environment [版本及环境]  
+ ECharts version [ECharts 版本]:2.0
+ Browser version [浏览器类型和版本]:Chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]:
某条曲线中有负数点，整个高度堆叠应该被拉下去，实际上echarts处理方式为正数和正数堆叠，负数和负数堆叠。

![360 16410119195312](https://user-images.githubusercontent.com/16475699/30065826-b0aab662-9288-11e7-83be-4bd7c7e5e094.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by fluxlinkage** [comment]
echart.js中找到并注释掉
if ((value >= 0 && stackedValue > 0)  // Positive stack
|| (value <= 0 && stackedValue < 0) // Negative stack)
{
和
}
这几行。
使得代码成为
// Considering positive stack, negative stack and empty data
//if ((value >= 0 && stackedValue > 0)  // Positive stack
//    || (value <= 0 && stackedValue < 0) // Negative stack
//) {
	value += stackedValue;
//}
就解决问题了。
感觉这个if画蛇添足，应该删掉。
附修改后效果图：
![echarts](https://user-images.githubusercontent.com/31914934/30362905-b1128b94-9890-11e7-8c12-a1c90184aed6.png)
echarts.min.js暂时不知道怎么改……

**Comment by shrektan** [comment]
I'm bite by this issue. Hope there's an option to control this "default" behavior.

**Comment by LiGaoLiang7** [comment]
> I'm bite by this issue. Hope there's an option to control this "default" behavior.

Highcharts is another option, It performs in line with expectations

**Comment by shrektan** [comment]
> > I'm bite by this issue. Hope there's an option to control this "default" behavior.
> 
> Highcharts is another option, It performs in line with expectations

Yep, but the license... This is the only thing that I'm not satisfied with Echarts.
