### ISSUE TITLE
Unable to show tooltip on Parallel chart lines

### ISSUE THREAD

**Issue by lisachristina1234** [apache/echarts#6609]
Summary : Parallel Chart Tooltip

Version & Environment
+ ECharts version 3
+ Browser version: Version 59.0.3071.115 (Official Build) (64-bit)
+ OS Version: Ubuntu 16.04

Expected behavior :
On mouse hover tooltip should be displayed on lines which are rendered between the axes.

Other comments
I have tried on ECharts demo editor to show the tooltip but it's not triggering the event on lines which are drawn across parallel axes. Please refer demo chart link :
https://ecomfe.github.io/echarts-examples/public/editor.html?c=parallel-aqi
I am able to show tooltip only on the title of Parallel Axes. 
Is there any specific way to show tooltip on Parallel chart rendered lines?
Any help will be appreciated.
Thanks in advance !!!

**Comment by lvybriage** [comment]
I also have the problem.

**Comment by seriousAA** [comment]
Echarts simply doesn't have this feature on parallel axis....
You can try highcharts by the way.
