### ISSUE TITLE
关系图鼠标移到节点上时，能否改变被突出边的透明度？

### ISSUE THREAD

**Issue by Lily-Jian** [apache/echarts#6670]
### One-line summary [问题简述]
在鼠标移到节点上的时候能突出显示节点以及节点的边和邻接节点，并且可以改变被突出边的颜色，但是不能改变被突出边的透明度。
地址：
http://gallery.echartsjs.com/editor.html?c=xHk28KqP5-&v=2

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
在鼠标移到节点上的时候突出显示节点以及节点的边和邻接节点，的同时，能改变被突出的边的透明度。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by SchnWalter** [comment]
This seems to be a feature request and not a bug. I would recommend relabeling it.
