### ISSUE TITLE
地图页面整体添加scale时触屏操作点击位置偏移，鼠标操作正常

### ISSUE THREAD

**Issue by troy351** [apache/echarts#6674]
### One-line summary [问题简述]

地图页面整体添加scale时触屏操作点击位置偏移，鼠标操作正常

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome 61
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]

触屏点击位置不发生偏移

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

使用样例[http://echarts.baidu.com/demo.html#map-china](http://echarts.baidu.com/demo.html#map-china)
重现步骤：
1. 在devtool中选中上述样例右侧渲染结果的iframe
2. 给iframe的`body`加上css `transform: scale(0.7)`，尝试点击地图上的省份
3. 鼠标点击正常，未发生错位
4. 触屏点击不正常，发生错位

**Comment by tylerdd** [comment]
关注ing 希望得到尽快解决

**Comment by tylerrrkd** [comment]
。

**Comment by cn-xufei** [comment]
关注中，不只是地图，其他图表都有偏移问题，现在卡在这里了
![image](https://user-images.githubusercontent.com/14144811/48237745-01246f80-e403-11e8-9b76-6b0be3f6eea6.png)
