### ISSUE TITLE
legend如何设置超长自动截断，并且自动对齐等能力

### ISSUE THREAD

**Issue by WebsonLeo** [apache/echarts#6702]
### One-line summary [问题简述]
legend如何设置超长自动截断，并且自动对齐等能力

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:Chrom 61.0.3163.79
+ OS Version [操作系统类型和版本]:window7 专业版

### Expected behaviour [期望结果]
希望图例能提供一个用户自定义样式的接口，以实现图例的自动截断、自动对齐等等能力。比如，一个图例非常长，而canvas就那么大点，这个时候，就希望图例能自动截断并显示省略号，而不是由用户通过format来写，那样写不标准，也不好计算。最主要的是不同的字符，占的像素不一致，如果没有CSS样式来指定像素，根本无法保证上下两行图例所占像素一样，进而展示对齐效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17735331/30532813-ca83e842-9c88-11e7-9936-e1c5b4dd5ff2.png)

**Comment by YH-Chen** [comment]
+1
