### ISSUE TITLE
Tooltip trigger item

### ISSUE THREAD

**Issue by dscis** [apache/echarts#6708]
Hello,

Great library, one bug though on the line charts. When SymbolSize is zero or showSymbol false on series tooltip is not working.

Thanks,
dscis

**Comment by Ovilia** [comment]
@100pah will follow up and find if this is a feature or bug.

**Comment by amittonge** [comment]
Trend line is ultimately line chart and where I prefer to keep SymbolSize is zero or showSymbol false and want to show trend line expression as tooltip on line.

**Comment by locknono** [comment]
Any progress?
