### ISSUE TITLE
饼状图在移动端的使用问题

### ISSUE THREAD

**Issue by Elvira-Ho** [apache/echarts#6716]
在移动端使用时，当文字超出屏幕会直接截断，可否有让文字换行的参数
写了个例子如下
[demo](https://codepen.io/i-summer/pen/QqjXXO)

**Comment by Ovilia** [comment]
`'\n'` 换行

**Comment by Summer-Shirley** [comment]
具体怎么使用？

**Comment by Summer-Shirley** [comment]
怎么使用？

**Comment by DukeGJ** [comment]
你可以监听屏幕大小的改变吗？大小改变的时候刷新一次

**Comment by Ovilia** [comment]
series 和 legend 中的 `'直接访问'` 改为 `'直接\n访问'`

**Comment by Summer-Shirley** [comment]
@DukeGJ 怎么监听

**Comment by DukeGJ** [comment]
移动端应该提供了窗体大小改变的事件监听，你只要在窗体大小改变之后刷新页面就好了，具体你可你查查API

**Comment by zhupengxiang** [comment]
@Summer-Shirley  兄弟这个问题弄好了么
