### ISSUE TITLE
treemap 如果zoom放大后，更新数据（setOption）会恢复到默认大小，请问是否可以保持ZOOM大小呢

### ISSUE THREAD

**Issue by qilerongrong** [apache/echarts#6719]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
目前应该是不支持这样的功能的

**Comment by z-hao** [comment]
我是这么处理的

```
var zoomStart = 50; //给个默认值

var option = {
   dataZoom: [{
      type: 'inside',
      start: zoomStart
    }, {
      show: false
    }],
};

myChart.setOption(option);

myChart.on('datazoom', function(params) {

    zoomStart = params.batch[0].start;

  });

```

**Comment by qilerongrong** [comment]
@z-hao 我这里没有试成功，是在treemap中加入dataZoom的配置嘛？能看下是怎么结合treemap来实践的嘛，多谢~

**Comment by z-hao** [comment]
不好意思，之前没有发现treemap设置了dataZoom会报错，这个好像确实实现不了 @qilerongrong

**Comment by ZeeMenng** [comment]
treemap好像不支持dataZoom的配置？

**Comment by wangminli** [comment]
> 
> 
> 目前应该是不支持这样的功能的

请问后期会支持这个更新数据（setOption）后， 不重绘全图形的功能么？
