### ISSUE TITLE
图例legend.pageButtonPosition的建议

### ISSUE THREAD

**Issue by zhangjiaqing** [apache/echarts#6745]
### One-line summary [问题简述]
legend.pageButtonPosition属性只能选择‘start’和‘end’，既然legend本身有高宽，说明也是盒子，希望能实现指定放在任意位置的功能

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这可能会比较复杂，请问你是想放在什么位置？

**Comment by zhangjiaqing** [comment]
![20170922174507822](https://user-images.githubusercontent.com/13639247/30749212-4c8b794a-9fe5-11e7-9b0b-757de998266a.png)

比如图中的位置

**Comment by aloehh** [comment]
比如这种：
<img width="472" alt="屏幕快照 2019-09-03 上午11 03 11" src="https://user-images.githubusercontent.com/31988199/64142468-9f743c80-ce3e-11e9-94e9-fbe55930f10a.png">

**Comment by choukin** [comment]
@[zhangjiaqing](https://github.com/zhangjiaqing) 请问你想要的效果怎么实现的

**Comment by zhangjiaqing** [comment]
> @[zhangjiaqing](https://github.com/zhangjiaqing) 请问你想要的效果怎么实现的

并没有实现😔
