### ISSUE TITLE
Sankey charts : How to avoid Sankey nodes overlapping without making chart to to drawn in bottom-up direction.

### ISSUE THREAD

**Issue by lisachristina1234** [apache/echarts#6792]
One-line summary : 
    Nodes in sankey chart are getting overlapped on another nodes.
    I have used "nodeGap" property to remove the overlapping but it is drawing sankey chart in bottom-up 
    direction and not positions the node vertically center.
    Even I have tried setting "layoutIterations" to 32 and above but still overlapping ocurrs.

Version & Environment : 
    ECharts version : 3
    Browser version: Version 59.0.3071.115 (Official Build) (64-bit)
    OS Version: Ubuntu 16.04

### Expected behaviour
1. When "nodeGap = 3" property is used in sankey series then chart should be drawn as is default direction and nodes should be verically center.
2. When "layoutIterations" used to remove/reduce the overlapping, it should do the same as per specification in echarts documentation.

### ECharts option :
option = {
  "backgroundColor": "#FFFFFF",
  "series": [
    {
      "type": "sankey",
      "left": 50.0,
      "top": 50.0,
      "right": 125.0,
      "bottom": 50.0,
      "layout": "none",
      "data": [
        {
          "name": "Werne",
          
          "itemStyle": {
            "normal": {
              "color": "#f18bbf",
              "borderColor": "#f18bbf"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Duesseldorf",
          "itemStyle": {
            "normal": {
              "color": "#0078D7",
              "borderColor": "#0078D7"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Cambridge",
          "itemStyle": {
            "normal": {
              "color": "#3891A7",
              "borderColor": "#3891A7"
            }
          },
          "value": 500.36999743431807
        },
        {
          "name": "Colma",
          "itemStyle": {
            "normal": {
              "color": "#0037DA",
              "borderColor": "#0037DA"
            }
          },
          "value": 0.2199999988079071
        },
        {
          "name": "W. York",
          "itemStyle": {
            "normal": {
              "color": "#C0BEAF",
              "borderColor": "#C0BEAF"
            }
          },
          "value": 612.1199932694435
        },
        {
          "name": "Frankfurt am Main",
          "itemStyle": {
            "normal": {
              "color": "#EA005E",
              "borderColor": "#EA005E"
            }
          },
          "value": 536.7599945068359
        },
        {
          "name": "Metz",
          "itemStyle": {
            "normal": {
              "color": "#D13438",
              "borderColor": "#D13438"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Orleans",
          "itemStyle": {
            "normal": {
              "color": "#567C73",
              "borderColor": "#567C73"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Saint-Denis",
          "itemStyle": {
            "normal": {
              "color": "#9ed566",
              "borderColor": "#9ed566"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Hof",
          "itemStyle": {
            "normal": {
              "color": "#2BCC7F",
              "borderColor": "#2BCC7F"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Cliffside",
          "itemStyle": {
            "normal": {
              "color": "#809B48",
              "borderColor": "#809B48"
            }
          },
          "value": 2906.2699892893434
        },
        {
          "name": "Leeds",
          "itemStyle": {
            "normal": {
              "color": "#9B2D1F",
              "borderColor": "#9B2D1F"
            }
          },
          "value": 1356.6899970173836
        },
        {
          "name": "Victoria",
          "itemStyle": {
            "normal": {
              "color": "#604878",
              "borderColor": "#604878"
            }
          },
          "value": 827.3899968340993
        },
        {
          "name": "Erlangen",
          "itemStyle": {
            "normal": {
              "color": "#A5644E",
              "borderColor": "#A5644E"
            }
          },
          "value": 536.7599945068359
        },
        {
          "name": "Saint Germain en Laye",
          "itemStyle": {
            "normal": {
              "color": "#2D3F3A",
              "borderColor": "#2D3F3A"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Roissy en Brie",
          "itemStyle": {
            "normal": {
              "color": "#761721",
              "borderColor": "#761721"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Wokingham",
          "itemStyle": {
            "normal": {
              "color": "#B1BADD",
              "borderColor": "#B1BADD"
            }
          },
          "value": 812.6600027084351
        },
        {
          "name": "Runcorn",
          "itemStyle": {
            "normal": {
              "color": "#B0CCB0",
              "borderColor": "#B0CCB0"
            }
          },
          "value": 1120.4800013303757
        },
        {
          "name": "Newton",
          "itemStyle": {
            "normal": {
              "color": "#8164A3",
              "borderColor": "#8164A3"
            }
          },
          "value": 1781.909985654056
        },
        {
          "name": "Morangis",
          "itemStyle": {
            "normal": {
              "color": "#8E562E",
              "borderColor": "#8E562E"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Metchosin",
          "itemStyle": {
            "normal": {
              "color": "#C1504D",
              "borderColor": "#C1504D"
            }
          },
          "value": 1750.7899813987315
        },
        {
          "name": "Kirkby",
          "itemStyle": {
            "normal": {
              "color": "#CCAF0A",
              "borderColor": "#CCAF0A"
            }
          },
          "value": 753.4000000059605
        },
        {
          "name": "London",
          "itemStyle": {
            "normal": {
              "color": "#956251",
              "borderColor": "#956251"
            }
          },
          "value": 8619.309983983636
        },
        {
          "name": "Offenbach",
          "itemStyle": {
            "normal": {
              "color": "#C17529",
              "borderColor": "#C17529"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Warrington",
          "itemStyle": {
            "normal": {
              "color": "#CEC597",
              "borderColor": "#CEC597"
            }
          },
          "value": 2162.8300000429153
        },
        {
          "name": "Vancouver",
          "itemStyle": {
            "normal": {
              "color": "#9F2936",
              "borderColor": "#9F2936"
            }
          },
          "value": 1528.580000281334
        },
        {
          "name": "SuperiorCard",
          "itemStyle": {
            "normal": {
              "color": "rgba(128,155,72,255)",
              "borderColor": "rgba(128,155,72,255)"
            }
          },
          "value": 17942.459927342832
        },
        {
          "name": "Lille",
          "itemStyle": {
            "normal": {
              "color": "#ac7430",
              "borderColor": "#ac7430"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Hamburg",
          "itemStyle": {
            "normal": {
              "color": "#00BCF2",
              "borderColor": "#00BCF2"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Langley",
          "itemStyle": {
            "normal": {
              "color": "#CD7B38",
              "borderColor": "#CD7B38"
            }
          },
          "value": 1274.8199949413538
        },
        {
          "name": "Les Ulis",
          "itemStyle": {
            "normal": {
              "color": "#424242",
              "borderColor": "#424242"
            }
          },
          "value": 715.6799926757812
        },
        {
          "name": "Saarbrücken",
          "itemStyle": {
            "normal": {
              "color": "#f63185",
              "borderColor": "#f63185"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "N. Vancouver",
          "itemStyle": {
            "normal": {
              "color": "#9CBC59",
              "borderColor": "#9CBC59"
            }
          },
          "value": 1862.4599857926369
        },
        {
          "name": "Chalk Riber",
          "itemStyle": {
            "normal": {
              "color": "#4F4BD9",
              "borderColor": "#4F4BD9"
            }
          },
          "value": 0.9200000166893005
        },
        {
          "name": "Esher-Molesey",
          "itemStyle": {
            "normal": {
              "color": "#3EC562",
              "borderColor": "#3EC562"
            }
          },
          "value": 911.4700058028102
        },
        {
          "name": "Chatou",
          "itemStyle": {
            "normal": {
              "color": "#F06F2E",
              "borderColor": "#F06F2E"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Hannover",
          "itemStyle": {
            "normal": {
              "color": "#C3986D",
              "borderColor": "#C3986D"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Roncq",
          "itemStyle": {
            "normal": {
              "color": "#4D291C",
              "borderColor": "#4D291C"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Ingolstadt",
          "itemStyle": {
            "normal": {
              "color": "#009c7a",
              "borderColor": "#009c7a"
            }
          },
          "value": 536.7599945068359
        },
        {
          "name": "Drancy",
          "itemStyle": {
            "normal": {
              "color": "#986F0B",
              "borderColor": "#986F0B"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Langford",
          "itemStyle": {
            "normal": {
              "color": "#3C8EA4",
              "borderColor": "#3C8EA4"
            }
          },
          "value": 2343.4599857851863
        },
        {
          "name": "Lebanon",
          "itemStyle": {
            "normal": {
              "color": "#4F82BE",
              "borderColor": "#4F82BE"
            }
          },
          "value": 0.8700000047683716
        },
        {
          "name": "Maidenhead",
          "itemStyle": {
            "normal": {
              "color": "#D38017",
              "borderColor": "#D38017"
            }
          },
          "value": 549.8400026857853
        },
        {
          "name": "Stoke-on-Trent",
          "itemStyle": {
            "normal": {
              "color": "#A8CDD7",
              "borderColor": "#A8CDD7"
            }
          },
          "value": 1131.7099939212203
        },
        {
          "name": "Peterborough",
          "itemStyle": {
            "normal": {
              "color": "#7A072D",
              "borderColor": "#7A072D"
            }
          },
          "value": 999.159998036921
        },
        {
          "name": "Suresnes",
          "itemStyle": {
            "normal": {
              "color": "#859599",
              "borderColor": "#859599"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Versailles",
          "itemStyle": {
            "normal": {
              "color": "#84AA33",
              "borderColor": "#84AA33"
            }
          },
          "value": 894.5999908447266
        },
        {
          "name": "Neunkirchen",
          "itemStyle": {
            "normal": {
              "color": "#ff8b67",
              "borderColor": "#ff8b67"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Vista",
          "itemStyle": {
            "normal": {
              "color": "rgba(106,82,134,255)",
              "borderColor": "rgba(106,82,134,255)"
            }
          },
          "value": 18624.78990776837
        },
        {
          "name": "Westminster",
          "itemStyle": {
            "normal": {
              "color": "#1B587C",
              "borderColor": "#1B587C"
            }
          },
          "value": 1149.7999994903803
        },
        {
          "name": "Kiel",
          "itemStyle": {
            "normal": {
              "color": "#A19574",
              "borderColor": "#A19574"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Newcastle upon Tyne",
          "itemStyle": {
            "normal": {
              "color": "#918485",
              "borderColor": "#918485"
            }
          },
          "value": 1448.2899911925197
        },
        {
          "name": "Oxon",
          "itemStyle": {
            "normal": {
              "color": "#FFA98C",
              "borderColor": "#FFA98C"
            }
          },
          "value": 493.6499986946583
        },
        {
          "name": "West Sussex",
          "itemStyle": {
            "normal": {
              "color": "#B0E3C0",
              "borderColor": "#B0E3C0"
            }
          },
          "value": 592.1700052022934
        },
        {
          "name": "Oak Bay",
          "itemStyle": {
            "normal": {
              "color": "#4BADC7",
              "borderColor": "#4BADC7"
            }
          },
          "value": 1565.109990529716
        },
        {
          "name": "Milton Keynes",
          "itemStyle": {
            "normal": {
              "color": "#BA144C",
              "borderColor": "#BA144C"
            }
          },
          "value": 1648.2200061008334
        },
        {
          "name": "Eilenburg",
          "itemStyle": {
            "normal": {
              "color": "#F0A22E",
              "borderColor": "#F0A22E"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "ColonialVoice",
          "itemStyle": {
            "normal": {
              "color": "rgba(64,105,157,255)",
              "borderColor": "rgba(64,105,157,255)"
            }
          },
          "value": 19347.629926368594
        },
        {
          "name": "Liverpool",
          "itemStyle": {
            "normal": {
              "color": "#A28E6A",
              "borderColor": "#A28E6A"
            }
          },
          "value": 857.1999968588352
        },
        {
          "name": "Calgary",
          "itemStyle": {
            "normal": {
              "color": "#9F413E",
              "borderColor": "#9F413E"
            }
          },
          "value": 361.3899962902069
        },
        {
          "name": "CAD",
          "itemStyle": {
            "normal": {
              "color": "#40699D",
              "borderColor": "#40699D"
            }
          },
          "value": 27615.459851033986
        },
        {
          "name": "Paris La Defense",
          "itemStyle": {
            "normal": {
              "color": "#989391",
              "borderColor": "#989391"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Villeneuve-d'Ascq",
          "itemStyle": {
            "normal": {
              "color": "#886CE4",
              "borderColor": "#886CE4"
            }
          },
          "value": 178.9199981689453
        },  
        {
          "name": "Gloucestershire",
          "itemStyle": {
            "normal": {
              "color": "#964305",
              "borderColor": "#964305"
            }
          },
          "value": 422.28999888151884
        },
        {
          "name": "Gateshead",
          "itemStyle": {
            "normal": {
              "color": "#485FB5",
              "borderColor": "#485FB5"
            }
          },
          "value": 1425.7099913656712
        },
        {
          "name": "Salzgitter",
          "itemStyle": {
            "normal": {
              "color": "#87a0c7",
              "borderColor": "#87a0c7"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Woolston",
          "itemStyle": {
            "normal": {
              "color": "#FFE2C5",
              "borderColor": "#FFE2C5"
            }
          },
          "value": 833.3199937939644
        },
        {
          "name": "Frankfurt",
          "itemStyle": {
            "normal": {
              "color": "#40699D",
              "borderColor": "#40699D"
            }
          },
          "value": 715.6799926757812
        },
        {
          "name": "Münster",
          "itemStyle": {
            "normal": {
              "color": "#7e7eb2",
              "borderColor": "#7e7eb2"
            }
          },
          "value": 715.6799926757812
        },
        {
          "name": "York",
          "itemStyle": {
            "normal": {
              "color": "#587C7D",
              "borderColor": "#587C7D"
            }
          },
          "value": 3172.9999914616346
        },
        {
          "name": "High Wycombe",
          "itemStyle": {
            "normal": {
              "color": "#F07F09",
              "borderColor": "#F07F09"
            }
          },
          "value": 216.83999809622765
        },
        {
          "name": "Stuttgart",
          "itemStyle": {
            "normal": {
              "color": "#E3008C",
              "borderColor": "#E3008C"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Sooke",
          "itemStyle": {
            "normal": {
              "color": "#4E8542",
              "borderColor": "#4E8542"
            }
          },
          "value": 1764.499989286065
        },
        {
          "name": "Essen",
          "itemStyle": {
            "normal": {
              "color": "#B58B80",
              "borderColor": "#B58B80"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "München",
          "itemStyle": {
            "normal": {
              "color": "#4dc0a6",
              "borderColor": "#4dc0a6"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Haney",
          "itemStyle": {
            "normal": {
              "color": "#6A5286",
              "borderColor": "#6A5286"
            }
          },
          "value": 2310.4499812424183
        },
        {
          "name": "Port Hammond",
          "itemStyle": {
            "normal": {
              "color": "#F89746",
              "borderColor": "#F89746"
            }
          },
          "value": 1711.1399984136224
        },
        {
          "name": "Saint Ouen",
          "itemStyle": {
            "normal": {
              "color": "#744DA9",
              "borderColor": "#744DA9"
            }
          },
          "value": 179.50999814271927
        },
        {
          "name": "Watford",
          "itemStyle": {
            "normal": {
              "color": "#E8B7B7",
              "borderColor": "#E8B7B7"
            }
          },
          "value": 1326.5300009772182
        },
        {
          "name": "GBP",
          "itemStyle": {
            "normal": {
              "color": "#C32D2E",
              "borderColor": "#C32D2E"
            }
          },
          "value": 36151.6699392423
        },
        {
          "name": "Paderborn",
          "itemStyle": {
            "normal": {
              "color": "#F0C42E",
              "borderColor": "#F0C42E"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Dunkerque",
          "itemStyle": {
            "normal": {
              "color": "#881798",
              "borderColor": "#881798"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Colomiers",
          "itemStyle": {
            "normal": {
              "color": "#efa835",
              "borderColor": "#efa835"
            }
          },
          "value": 357.8399963378906
        },
        {
          "name": "Oxford",
          "itemStyle": {
            "normal": {
              "color": "#D8B25C",
              "borderColor": "#D8B25C"
            }
          },
          "value": 1831.3799968883395
        },
        {
          "name": "Bury",
          "itemStyle": {
            "normal": {
              "color": "#FEB80A",
              "borderColor": "#FEB80A"
            }
          },
          "value": 903.9400005489588
        },
        {
          "name": "Royal Oak",
          "itemStyle": {
            "normal": {
              "color": "#009DD9",
              "borderColor": "#009DD9"
            }
          },
          "value": 2128.459992274642
        },
        {
          "name": "Shawnee",
          "itemStyle": {
            "normal": {
              "color": "#F07F09",
              "borderColor": "#F07F09"
            }
          },
          "value": 2346.919983509928
        },
        {
          "name": "Lancaster",
          "itemStyle": {
            "normal": {
              "color": "#D34817",
              "borderColor": "#D34817"
            }
          },
          "value": 685.6899967193604
        },
        {
          "name": "DEM",
          "itemStyle": {
            "normal": {
              "color": "#4E342E",
              "borderColor": "#4E342E"
            }
          },
          "value": 7693.559921264648
        },
        {
          "name": "Grevenbroich",
          "itemStyle": {
            "normal": {
              "color": "#FFA836",
              "borderColor": "#FFA836"
            }
          },
          "value": 536.7599945068359
        },
        {
          "name": "Distinguish",
          "itemStyle": {
            "normal": {
              "color": "rgba(159,65,62,255)",
              "borderColor": "rgba(159,65,62,255)"
            }
          },
          "value": 22523.68987865001
        },
        {
          "name": "Cheltenham",
          "itemStyle": {
            "normal": {
              "color": "#FF6551",
              "borderColor": "#FF6551"
            }
          },
          "value": 573.0499979257584
        },
        {
          "name": "Reading",
          "itemStyle": {
            "normal": {
              "color": "#72A376",
              "borderColor": "#72A376"
            }
          },
          "value": 188.52999836206436
        },
        {
          "name": "Pantin",
          "itemStyle": {
            "normal": {
              "color": "#69797E",
              "borderColor": "#69797E"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Kassel",
          "itemStyle": {
            "normal": {
              "color": "#e65e20",
              "borderColor": "#e65e20"
            }
          },
          "value": 536.7599945068359
        },
        {
          "name": "Orly",
          "itemStyle": {
            "normal": {
              "color": "#6E6A68",
              "borderColor": "#6E6A68"
            }
          },
          "value": 0.5899999737739563
        },
        {
          "name": "FRF",
          "itemStyle": {
            "normal": {
              "color": "#5ba33b",
              "borderColor": "#5ba33b"
            }
          },
          "value": 6977.879928588867
        },
        {
          "name": "Cergy",
          "itemStyle": {
            "normal": {
              "color": "#B4009E",
              "borderColor": "#B4009E"
            }
          },
          "value": 178.9199981689453
        },
        {
          "name": "Paris",
          "itemStyle": {
            "normal": {
              "color": "#666666",
              "borderColor": "#666666"
            }
          },
          "value": 1074.1599889993668
        }
      ],
      "links": [
        {
          "source": "FRF",
          "target": "Colomiers",
          "value": 357.8399963378906
        },
        {
          "source": "SuperiorCard",
          "target": "FRF",
          "value": 894.5999908447266
        },
        {
          "source": "DEM",
          "target": "München",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Reading",
          "value": 188.52999836206436
        },
        {
          "source": "CAD",
          "target": "Shawnee",
          "value": 2346.919983509928
        },
        {
          "source": "GBP",
          "target": "Kirkby",
          "value": 753.4000000059605
        },
        {
          "source": "FRF",
          "target": "Roncq",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Peterborough",
          "value": 999.159998036921
        },
        {
          "source": "DEM",
          "target": "Frankfurt am Main",
          "value": 536.7599945068359
        },
        {
          "source": "GBP",
          "target": "Oxford",
          "value": 1831.3799968883395
        },
        {
          "source": "Vista",
          "target": "FRF",
          "value": 1789.1999816894531
        },
        {
          "source": "CAD",
          "target": "Langley",
          "value": 1274.8199949413538
        },
        {
          "source": "DEM",
          "target": "Offenbach",
          "value": 357.8399963378906
        },
        {
          "source": "FRF",
          "target": "Villeneuve-d'Ascq",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Dunkerque",
          "value": 357.8399963378906
        },
        {
          "source": "DEM",
          "target": "Eilenburg",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Paris",
          "value": 1073.5199890136719
        },
        {
          "source": "GBP",
          "target": "Maidenhead",
          "value": 549.8400026857853
        },
        {
          "source": "CAD",
          "target": "Sooke",
          "value": 1764.499989286065
        },
        {
          "source": "CAD",
          "target": "Vancouver",
          "value": 1528.580000281334
        },
        {
          "source": "DEM",
          "target": "Hamburg",
          "value": 357.8399963378906
        },
        {
          "source": "GBP",
          "target": "London",
          "value": 8619.309983983636
        },
        {
          "source": "CAD",
          "target": "Oak Bay",
          "value": 1565.109990529716
        },
        {
          "source": "Distinguish",
          "target": "FRF",
          "value": 2683.7999725341797
        },
        {
          "source": "DEM",
          "target": "Neunkirchen",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Cergy",
          "value": 178.9199981689453
        },
        {
          "source": "DEM",
          "target": "Hof",
          "value": 357.8399963378906
        },
        {
          "source": "FRF",
          "target": "Paris La Defense",
          "value": 178.9199981689453
        },
        {
          "source": "CAD",
          "target": "Westminster",
          "value": 1149.7999994903803
        },
        {
          "source": "DEM",
          "target": "Ingolstadt",
          "value": 536.7599945068359
        },
        {
          "source": "GBP",
          "target": "Saint Ouen",
          "value": 0.5899999737739563
        },
        {
          "source": "FRF",
          "target": "Lille",
          "value": 357.8399963378906
        },
        {
          "source": "GBP",
          "target": "Leeds",
          "value": 1356.6899970173836
        },
        {
          "source": "FRF",
          "target": "Morangis",
          "value": 357.8399963378906
        },
        {
          "source": "GBP",
          "target": "Orly",
          "value": 0.5899999737739563
        },
        {
          "source": "SuperiorCard",
          "target": "DEM",
          "value": 1431.3599853515625
        },
        {
          "source": "Vista",
          "target": "CAD",
          "value": 5369.929964579642
        },
        {
          "source": "GBP",
          "target": "Paris",
          "value": 0.6399999856948853
        },
        {
          "source": "GBP",
          "target": "Liverpool",
          "value": 857.1999968588352
        },
        {
          "source": "GBP",
          "target": "Stoke-on-Trent",
          "value": 1131.7099939212203
        },
        {
          "source": "Distinguish",
          "target": "DEM",
          "value": 2504.8799743652344
        },
        {
          "source": "CAD",
          "target": "Langford",
          "value": 2343.4599857851863
        },
        {
          "source": "DEM",
          "target": "Kassel",
          "value": 536.7599945068359
        },
        {
          "source": "GBP",
          "target": "High Wycombe",
          "value": 216.83999809622765
        },
        {
          "source": "CAD",
          "target": "Port Hammond",
          "value": 1711.1399984136224
        },
        {
          "source": "DEM",
          "target": "Duesseldorf",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Gloucestershire",
          "value": 422.28999888151884
        },
        {
          "source": "Distinguish",
          "target": "GBP",
          "value": 10384.949975416064
        },
        {
          "source": "FRF",
          "target": "Roissy en Brie",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "West Sussex",
          "value": 592.1700052022934
        },
        {
          "source": "CAD",
          "target": "Cliffside",
          "value": 2906.2699892893434
        },
        {
          "source": "GBP",
          "target": "Newcastle upon Tyne",
          "value": 1448.2899911925197
        },
        {
          "source": "GBP",
          "target": "Runcorn",
          "value": 1120.4800013303757
        },
        {
          "source": "GBP",
          "target": "W. York",
          "value": 612.1199932694435
        },
        {
          "source": "DEM",
          "target": "Kiel",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Woolston",
          "value": 833.3199937939644
        },
        {
          "source": "Distinguish",
          "target": "CAD",
          "value": 6950.059956334531
        },
        {
          "source": "DEM",
          "target": "Frankfurt",
          "value": 715.6799926757812
        },
        {
          "source": "CAD",
          "target": "Colma",
          "value": 0.2199999988079071
        },
        {
          "source": "DEM",
          "target": "Essen",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Chatou",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Cheltenham",
          "value": 573.0499979257584
        },
        {
          "source": "SuperiorCard",
          "target": "GBP",
          "value": 8228.39999615401
        },
        {
          "source": "CAD",
          "target": "Haney",
          "value": 2310.4499812424183
        },
        {
          "source": "FRF",
          "target": "Saint Ouen",
          "value": 178.9199981689453
        },
        {
          "source": "CAD",
          "target": "Chalk Riber",
          "value": 0.9200000166893005
        },
        {
          "source": "DEM",
          "target": "Salzgitter",
          "value": 178.9199981689453
        },
        {
          "source": "ColonialVoice",
          "target": "FRF",
          "value": 1610.2799835205078
        },
        {
          "source": "DEM",
          "target": "Stuttgart",
          "value": 357.8399963378906
        },
        {
          "source": "FRF",
          "target": "Saint-Denis",
          "value": 178.9199981689453
        },
        {
          "source": "CAD",
          "target": "Royal Oak",
          "value": 2128.459992274642
        },
        {
          "source": "FRF",
          "target": "Les Ulis",
          "value": 715.6799926757812
        },
        {
          "source": "FRF",
          "target": "Drancy",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Esher-Molesey",
          "value": 911.4700058028102
        },
        {
          "source": "SuperiorCard",
          "target": "CAD",
          "value": 7388.099954992533
        },
        {
          "source": "GBP",
          "target": "Bury",
          "value": 903.9400005489588
        },
        {
          "source": "GBP",
          "target": "Watford",
          "value": 1326.5300009772182
        },
        {
          "source": "CAD",
          "target": "Victoria",
          "value": 827.3899968340993
        },
        {
          "source": "DEM",
          "target": "Saarbrücken",
          "value": 178.9199981689453
        },
        {
          "source": "GBP",
          "target": "Lancaster",
          "value": 685.6899967193604
        },
        {
          "source": "FRF",
          "target": "Pantin",
          "value": 178.9199981689453
        },
        {
          "source": "CAD",
          "target": "Newton",
          "value": 1781.909985654056
        },
        {
          "source": "GBP",
          "target": "Oxon",
          "value": 493.6499986946583
        },
        {
          "source": "CAD",
          "target": "Calgary",
          "value": 361.3899962902069
        },
        {
          "source": "DEM",
          "target": "Münster",
          "value": 715.6799926757812
        },
        {
          "source": "DEM",
          "target": "Grevenbroich",
          "value": 536.7599945068359
        },
        {
          "source": "DEM",
          "target": "Paderborn",
          "value": 357.8399963378906
        },
        {
          "source": "GBP",
          "target": "York",
          "value": 3172.9999914616346
        },
        {
          "source": "CAD",
          "target": "Metchosin",
          "value": 1750.7899813987315
        },
        {
          "source": "FRF",
          "target": "Suresnes",
          "value": 357.8399963378906
        },
        {
          "source": "FRF",
          "target": "Versailles",
          "value": 894.5999908447266
        },
        {
          "source": "DEM",
          "target": "Erlangen",
          "value": 536.7599945068359
        },
        {
          "source": "CAD",
          "target": "Lebanon",
          "value": 0.8700000047683716
        },
        {
          "source": "GBP",
          "target": "Wokingham",
          "value": 812.6600027084351
        },
        {
          "source": "GBP",
          "target": "Cambridge",
          "value": 500.36999743431807
        },
        {
          "source": "ColonialVoice",
          "target": "GBP",
          "value": 8040.7799860313535
        },
        {
          "source": "FRF",
          "target": "Saint Germain en Laye",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Metz",
          "value": 178.9199981689453
        },
        {
          "source": "FRF",
          "target": "Orleans",
          "value": 357.8399963378906
        },
        {
          "source": "GBP",
          "target": "Milton Keynes",
          "value": 1648.2200061008334
        },
        {
          "source": "GBP",
          "target": "Warrington",
          "value": 2162.8300000429153
        },
        {
          "source": "CAD",
          "target": "N. Vancouver",
          "value": 1862.4599857926369
        },
        {
          "source": "DEM",
          "target": "Hannover",
          "value": 178.9199981689453
        },
        {
          "source": "Vista",
          "target": "GBP",
          "value": 9497.539981640875
        },
        {
          "source": "DEM",
          "target": "Werne",
          "value": 178.9199981689453
        },
        {
          "source": "ColonialVoice",
          "target": "DEM",
          "value": 1789.1999816894531        },
        {
          "source": "ColonialVoice",
          "target": "CAD",
          "value": 7907.36997512728
        },
        {
          "source": "GBP",
          "target": "Gateshead",
          "value": 1425.7099913656712
        },
        {
          "source": "Vista",
          "target": "DEM",
          "value": 1968.1199798583984
        }
      ],
      "lineStyle": {
        "normal": {
          "color": "source",
          "curveness": 0.5
        }
      },
      "itemStyle": {
        "normal": {
          "color": "#1f77b4",
          "borderColor": "#1f77b4"
        }
      },
      "label": {
        "normal": {
          "textStyle": {
            "color": "rgba(0,0,0,0.7)",
            "fontFamily": "Arial",
            "fontSize": "12"
          }
        }
      }
    }
  ],
  "tooltip": {
    "trigger": "item"
  }
};

### Other comments 
I hope echarts team would soon povide the solution.
Thanks in advance.

**Comment by lisachristina1234** [comment]
Please refer the example https://jsfiddle.net/lisachristina1234/3j0b3r7x/12/
Hover on Vista and Distinguish nodes, it will be observed that they are overlapped.

**Comment by deqingli** [comment]
Hi @katherinebai,  I have tested the demo and it was ok, as the following picture. please try it again with new echarts version. In addition, your demo is amazing, and I will add it to our official website with a reference to your GitHub, if you have any opinion, email me and I will remove it.

![image](https://user-images.githubusercontent.com/13548221/54517169-e3ac7700-499b-11e9-922d-7c769627b5f0.png)

**Comment by katherinebai** [comment]
I'm sorry, I did not report this bug, so please @lisachristina1234 to check the issue. Thanks.

**Comment by deqingli** [comment]
@katherinebai  sorry, it's my mistake.

**Comment by deqingli** [comment]
@lisachristina1234  sorry, I misunderstand your issue, I will test it in the bottom-up direction.
