### ISSUE TITLE
关系图graph支持两个data节点之间多条link，每个link代表一种关系，并可以筛选？

### ISSUE THREAD

**Issue by bojiangwin** [apache/echarts#6811]
关系图graph支持两个data节点之间多条link，每个link代表一种关系，并可以筛选？
如两个人A、B：
A是B的同学
A是B的男朋友
A是B的老乡
A是B的。。。。

每一种关系用一条线相连，这样A和B之间应该有多条线。

并且可以通过同学、老乡这些条件筛选。

这个不知道怎么实现？

**Comment by javaMumu** [comment]
我有同样的需求。

**Comment by itDjango** [comment]
同样需求，求解答

**Comment by YzPaul3** [comment]
是目前还不支持吧？

**Comment by BerQin** [comment]
我也是这个需求，我想实在找不到解决的只能修改源码了 专门为这个做一部分

**Comment by Ovilia** [comment]
@BerQin B 欢迎提 PR 啊！

**Comment by wangcongyi** [comment]
@Ovilia  是不是可以这么做：
  官方目前不支持 相同节点多条线， 但支持不同节点放在同一位置上~~
  所以一条线就在相同位置上增加一个节点？

**Comment by BerQin** [comment]
@wangcongyi @Ovilia 其实相同的 source 和 target点被过滤掉了，他在判断线ID生成上有些问题，只判断了线的目标点和出发点，其实还有一个因素决定了线的唯一性，就是value所以可以把生成线的那部分代码修改一下就行，如果在深入的修改需要判断线的偏移量那部分如果多先线的偏移量自动给加上，不过也可以让用户自己去设置curveness线的这个属性！我项目用就修改了这部分 没有在深入的研究

**Comment by BerQin** [comment]
好像是 276 和 280部分

**Comment by sannai** [comment]
请问 你们这个问题解决了吗？

**Comment by HowToMeetYou** [comment]
修改源码且将关系连线改成曲线，修改代码稍后贴上

**Comment by HowToMeetYou** [comment]
> 请问 你们这个问题解决了吗？
1.修改源码
nodemodules-echarts-lib-data-Graph.js中graphProto.addEdge：
if (edgesMap[key]) {
  return;
}
return注释掉
2.代码中曲度改用随机
curveness: Math.random()

**Comment by small752** [comment]
1.修改源码
nodemodules-echarts-lib-data-Graph.js中graphProto.addEdge：
if (edgesMap[key]) {
return;
}
return注释掉
2.代码中曲度改用随机
curveness: Math.random()

用上述方法好像还是没有效果， 另外改node-modules里的方法还是不太方便，以后版本迭代了针对源码的这个改动肯定就忘记了。有没有在业务代码中实现这个效果的方法

**Comment by small752** [comment]
上述方法有效了，是我第二步没做对

**Comment by ZinLiao** [comment]
有同样需求
19 年了，这需求貌似还没办法解决~

**Comment by topvis** [comment]
顶一下，有同样需求。希望能够有这个功能。

**Comment by liuttcc** [comment]
> 上述方法有效了，是我第二步没做对

请问下注释后，第二步改成随机曲度没有用是怎么回事？

**Comment by gaoruimin** [comment]
> > 上述方法有效了，是我第二步没做对
> 
> 请问下注释后，第二步改成随机曲度没有用是怎么回事？

我是注释加了，没效果，随机曲度没问题，echart是不是最多两条，还是只能显示一样的数据
![image](https://user-images.githubusercontent.com/26756964/58853394-b8991000-86cc-11e9-9bf8-7e9535d9c6ef.png)

**Comment by zuiidea** [comment]
- 使用 @HowToMeetYou 的方法可以解决问题，但是每次安装或者更新依赖后都需要手动更改源码，在持续集成环境中也不太好操作，这里附上一个重写 addEdge 的方法，具体操作参加下面代码：

```
import Graph from 'echarts/lib/data/Graph'
import echarts from 'echarts'

const Edge = Graph.Edge
const Node = Graph.Node

function generateNodeKey(id) {
  return '_EC_' + id;
}

Graph.prototype.addEdge = function (n1, n2, dataIndex) {
  var nodesMap = this._nodesMap;
  var edgesMap = this._edgesMap; // PNEDING

  if (typeof n1 === 'number') {
    n1 = this.nodes[n1];
  }

  if (typeof n2 === 'number') {
    n2 = this.nodes[n2];
  }

  if (!Node.isInstance(n1)) {
    n1 = nodesMap[generateNodeKey(n1)];
  }

  if (!Node.isInstance(n2)) {
    n2 = nodesMap[generateNodeKey(n2)];
  }

  if (!n1 || !n2) {
    return;
  }

  var key = n1.id + '-' + n2.id; // PENDING

  // if (edgesMap[key]) {
  //   return;
  // }

  var edge = new Edge(n1, n2, dataIndex);
  edge.hostGraph = this;

  if (this._directed) {
    n1.outEdges.push(edge);
    n2.inEdges.push(edge);
  }

  n1.edges.push(edge);

  if (n1 !== n2) {
    n2.edges.push(edge);
  }

  this.edges.push(edge);
  edgesMap[key] = edge;
  return edge;
}

```

- 此外，代码中曲度使用随机可能导致图形不是很好看，这里附上一个曲度优先生成的列表，使用方法如下：

```
/**
 * 生成边曲度优先使用列表
 * @return  [0.2, -0.2, 0.4, -0.4, 0.6, -0.6, 0.8, -0.8, 1, -1, 0.1, -0.1, 0.3, -0.3, 0.5, -0.5, 0.7, -0.7, 0.9, -0.9]
 */
const CURVENESS_LIST = Array.from({ length: 20 })
.map((_, i) => (((i < 10 ? i + 2 : i - 9) - (i % 2)) / 10) * (i % 2 ? -1 : 1))

// 1. 已存在的边的列表
const data = []
// 2. 预期生成的优化曲度后的列表
const echartLinks = []

data.forEach(link => {
    // 3. 查询已优化的列表中，已存在的两个顶点相同的边
    const sameLink = echartLinks.filter(
        item =>
        item.source === link.source &&
        item.target === link.target
    )

    // 4. 优化曲度
    link.lineStyle.normal.curveness = CURVENESS_LIST[sameLink.length] || Math.random()

    echartLinks.push(link)
})
```



优化前：`curveness: Math.random()`
![image](https://user-images.githubusercontent.com/16070518/59480003-87210100-8e91-11e9-9eb5-4e9221cf41e3.png)




优化后：`curveness: CURVENESS_LIST[sameLink.length] || Math.random()`
![image](https://user-images.githubusercontent.com/16070518/59479972-6ce72300-8e91-11e9-9b80-800cef6606b4.png)

**Comment by Ovilia** [comment]
请问这个 issue 现在遗留的具体需求是什么？如果有的话可以优先支持

**Comment by topvis** [comment]
@Ovilia 我觉得主要的一点是： 两个节点间同方向的连线应该允许多于一条的连线。现在的版本只允许一条连线。打个比方，从北京（节点1）到上海（节点2）有两条路线可以走，现在的版本只能显示其中的一条路线。
如果新版本允许一条以上相同方向的连线的话，还需有一定的算法保证这多条连线不重合（有不同的curveness）。

**Comment by singlelonghair** [comment]
注释掉return后，我的实验结果和topvis一致，多条显示线是重合的，但是category值是叠加在一起的。是否内部可以实现算法根据category值自适应不一样的curveness；注;将curveness改成随机，其也是重叠的，并没有因为category值不同而产生两个不同曲度的线。

**Comment by Ovilia** [comment]
@singlelonghair 非常欢迎 pull request，愿意尝试一下吗？

**Comment by singlelonghair** [comment]
我在使用中发现一个新问题，发现同一个节点不能被多次target，请问这个现在有解决办法没？

**Comment by singlelonghair** [comment]
pull request可以的。

**Comment by deqingli** [comment]
#11260

**Comment by lolysc** [comment]
> 我在使用中发现一个新问题，发现同一个节点不能被多次target，请问这个现在有解决办法没？

我这可以指向多个target。版本：echarts 4.6.0  上面解答的注释return的方案也行的通，random修改曲率也行得通。
感觉是echarts的bug啊

**Comment by iaminvictus1993** [comment]
mark 两点之间 支持多条links

**Comment by yzg111** [comment]
这个组件实现了同一个指向多个连接线的效果，https://www.npmjs.com/package/react_compoent_dyzg_version/v/0.1.8

**Comment by yangmin4052** [comment]
graphProto.addEdge = function (n1, n2, dataIndex) {
...
    // var key = n1.id + '-' + n2.id; 
    var key = n1.id + '-' + n2.id + dataIndex;
...
}
先把这里改了，在配合curveness实现不就好了
比如
link={
  ...
  lineStyle：{
    curveness: 0.2 * i/(length - 1) - 0.1
  }
  ...
}

**Comment by Ovilia** [comment]
Supported

**Comment by zl2fxy** [comment]
> graphProto.addEdge = function （n1， n2， dataIndex） { ... var 键 = n1.id + '-' + n2.id; var 键 = n1.id + '-' + n2.id + '-' + dataIndex; ... } 先把源码的这里改了，再在自己实现的时候将curveness实现不就好了 比如 link={ ... lineStyle：{ curveness： 0.2 * i/（length - 1） - 0.1 } ... } 不过对source和target有点要求，不能既有source->target，也有target->source，否则curveness需要用另外的计算方式

随机连线不好看，我写了个算法

**Comment by zl2fxy** [comment]
function handlerEdges(uniqueArray) {
    var groupBy = {};
    let groupByList = Array.from(new Set(uniqueArray.map(x => x.qweGroupBy)));

    groupByList.forEach(item => {
        let key = item;
        if (!groupBy[key]) {
            groupBy[key] = [];
        };
        //找自身和对向数据
        let filters = uniqueArray.filter(x => (x.qweGroupBy == key || x.qweGroupByFaXiang == key) && x.WC == false);
        groupBy[key] = groupBy[key].concat(filters);
        //找完了标记，下次不能被使用
        filters.forEach(filterItem => { 
            uniqueArray.find(x => x.qweUuid == filterItem.qweUuid).WC = true;
        });
    });
    
    let shuju = [];

    //开始算曲率
    for (const [key, value] of Object.entries(groupBy)) {
        let length = value.length;
        //判断是否有对向数据
        let hasDuiXiang = Array.from(new Set(value.map(x => x.qweGroupBy))).length > 1;
        
        if (hasDuiXiang) {
            var zhengXiangs = value.filter(x => x.qweGroupBy == key);
            var fanXiangs = value.filter(x => x.qweGroupByFaXiang == key);
            //加成系数，如果两边数量相等, 就对称，不相等就从最中间线开始
            var jiachengXiShu = zhengXiangs.length == fanXiangs.length ? 1 : 0;
            zhengXiangs.forEach((item, index) => {
                item.curveness = (index + jiachengXiShu) * 0.1;
                item.lineStyle = {
                    width: 1,
                    color: 'source',
                    curveness: item.curveness
                };
                shuju.push(item);
            });
            fanXiangs.forEach((item, index) => {
                item.curveness = (index + 1) * 0.1;
                item.lineStyle = {
                    width: 1,
                    color: 'source',
                    curveness: item.curveness
                };
                shuju.push(item);
            });

        }
        else {
            // 求商
            let quotient = Math.floor(length / 2);
            let remainder = length % 2;
            if (remainder == 0) {
                value.forEach((item, index) => {
                    if (index < quotient) {
                        item.curveness = (index + 1) * 0.1;
                    }
                    else {
                        item.curveness = -(((index - quotient) + 1) * 0.1);
                    }
                    item.lineStyle = {
                        width: 1,
                        color: 'source',
                        curveness: item.curveness
                    };
                    if (item.to == item.form) {
                        item.lineStyle.curveness = 0.8
                    }
                    shuju.push(item);
                })
            }
            else {
                value.forEach((item, index) => {
                    if (index < quotient) {
                        item.curveness = (index + 1) * 0.1;
                    }
                    else if (index == quotient) {
                        item.curveness = 0;
                    }
                    else {
                        item.curveness = -(((index - quotient) + 1) * 0.1);
                    }
                    item.lineStyle = {
                        width: 1,
                        color: 'source',
                        curveness: item.curveness
                    };
                    if (item.to == item.form) {
                        item.lineStyle.curveness = 0.8
                    }
                    shuju.push(item);
                })
            }
        }
        
    }
    return shuju;
}
