### ISSUE TITLE
will bar/treemap etc support selection status and select/unselect event like pie chart

### ISSUE THREAD

**Issue by OliviaSong** [apache/echarts#6813]
I've implemented the bar selection function, but I'm distressed about how to manage the code, so I ask if the Officialare considering implementing it，t's best to merge my code into the master

        var select=seriesModel.isSelected(data.getName(dataIndex));
        if(false===select)
        {
            color="#CDC5BF";
        }else{
            color = data.getItemVisual(dataIndex, 'color'); 
        }

this can keep unselectbar gray

**Comment by davidhg1710** [comment]
Hi! Could you share how did you implement the bar chart selection? I need that to call a query to update charts only with selected bars, but I have no idea of how. Thanks a Lot
