### ISSUE TITLE
brush 支持 bmap吗

### ISSUE THREAD

**Issue by Sbbq** [apache/echarts#6825]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by dfEric** [comment]
brush会跟着bmap的拖动平移事件导致选点不准确，从文档没找到支持的方式，正好也遇到同样问题，希望我们大神指教。。。

**Comment by Sbbq** [comment]
geo支持是因为有geoIndex,感觉geo支持的话，bmap也应该支持呀。

**Comment by dfEric** [comment]
geo的坐标系是经纬度，bmap也是，所以有些奇怪为什么只和bmap的roam冲突，geo正常

**Comment by ObservedObserver** [comment]
遇到同样的问题，希望官方能给出解决方案。

**Comment by dfEric** [comment]
有人有解决方法或者替代方法不，分享一下。

**Comment by a6318539** [comment]
这个问题无解么？

**Comment by nanmucoffin** [comment]
![image](https://user-images.githubusercontent.com/43234002/58065100-1f8bd480-7bb7-11e9-8220-8f84961f6a2e.png)

**Comment by nanmucoffin** [comment]
this.map.chart.on('brush', (p: any) => {
      if (p.command === 'clear') {
        this.map.chart.dispatchAction({
          type: 'takeGlobalCursor',
          key: 'brush',
          brushOption: {
            brushType: false,
            brushMode: 'single'
          }
        })
        this.brushComplete()
      } else {
        const mapChart = this.map.chart
        const amapInstense = mapChart.getModel().getComponent('amap')
        amapInstense.getAMap().setStatus({
          dragEnable: false,
          rotateEnable: false,
        })
        if (!p.areas.length) {
          amapInstense.getAMap().setStatus({
            dragEnable: true,
            rotateEnable: true,
          })
        }
      }
    })
