### ISSUE TITLE
Truncated data when resizing small

### ISSUE THREAD

**Issue by josevi86** [apache/echarts#6855]
### One-line summary [问题简述]
When I resize a chart, the data (shown next to the axes) that points to the graphic is being truncated. This happens with small width.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome Versión 61.0.3163.100 (Build oficial) (64 bits)
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
The chart should resize correctly, showing to the user the entire data. Screenshot attached

![7cef4103](https://user-images.githubusercontent.com/9534310/31663128-40dfb024-b341-11e7-95fb-1fff2750d666.PNG)

### ECharts option [ECharts配置项]
```javascript
option ={
	"title": {
		"text": "dqwdqqdwqdwqdwq",
		"left": "left",
		"top": "top",
		"textStyle": {
			"fontFamily": "roboto",
			"fontSize": 16,
			"color": "#FFA901"
		}
	},
	"grid": {
		"show": true
	},
	"tooltip": {
		"showContent": true,
		"trigger": "item"
	},
	"axisPointer": {
		"show": true,
		"type": "line",
		"snap": true
	},
	"toolbox": {
		"itemSize": 10,
		"itemGap": 10,
		"showTitle": true,
		"left": "right",
		"top": "bottom",
		"show": true,
		"feature": {
			"mark": {
				"show": true
			},
			"dataZoom": {
				"yAxisIndex": "none"
			},
			"magicType": {
				"show": true,
				"type": ["line",
				"bar"]
			},
			"restore": {
				"show": true
			},
			"saveAsImage": {
				"show": true
			}
		}
	},
	"calculable": true,
	"xAxis": [{
		"type": "category",
		"data": ["Pedro",
		"MarÃ­a",
		"Lucas",
		"JosÃ©",
		"Elvira",
		"Antonio H",
		"Antonio",
		"Ana"]
	}],
	"yAxis": [{
		"type": "value",
		"nameTextStyle": {
			"fontSize": 8
		}
	}],
	"series": [{
		"type": "bar",
		"data": [39889180,
		9030902,
		9276974,
		9458339,
		10458510,
		11546903,
		9358735,
		9698892]
	}]
}

```

### Other comments [其他信息]
Screenshot: 
![7cef4103](https://user-images.githubusercontent.com/9534310/31663128-40dfb024-b341-11e7-95fb-1fff2750d666.PNG)

**Comment by DukeGJ** [comment]
You can insert \n in the yAxis label,that's can solve your problem temporarily.

**Comment by shalmalijain** [comment]
I am facing the same problem. Is there any solution to this??
