### ISSUE TITLE
散点图重叠如何解决

### ISSUE THREAD

**Issue by tianfenggithub** [apache/echarts#6868]
### One-line summary [问题简述]
由于业务关系,部分散点图数据会完全一样,导致在页面上发生重叠,但是对于每个散点我都有点击事件,以及鼠标移动到点击可以跳转至对应的页面,但是重叠的话导致有一部分散点没有办法点击到

### Expected behaviour [期望结果]
期望结果:如果点重叠的时候,能有办法点击到每个重叠的点.跳转至对应的页面.
比如鼠标移动到上面的时候,出现一个列表,将每个点的相关信息以列表形式展现,点击相应的行跳转至对应的页面
或者能让重叠的点散开也行.能点到就好

**Comment by Ovilia** [comment]
你可以自己给重叠的点增加一点误差距离

**Comment by NsNe** [comment]
> 你可以自己给重叠的点增加一点误差距离
Hi,您好，有没有一个默认的坐标算法，可以绘制各个散点。自己用random生成的坐标有时候会显示不完全
