### ISSUE TITLE
请问柱状图的markline，可以自己设置一个固定的数值吗？

### ISSUE THREAD

**Issue by whytzb** [apache/echarts#688]
请问柱状图的markline，可以自己设置一个固定的数值吗？

**Comment by web5** [comment]
@whytzb  请问该怎么配置

**Comment by whytzb** [comment]
@web5 

markLine : {
					symbol : [ 'circle', 'circle' ],
					symbolSize : [ 0, 0 ],
					itemStyle : {
						normal : {
							color : 'red',
							label : {
								position : 'top'
							}
						}
					},
					data : [ [ {
						value : '99% markLine',
						xAxis : -1,
						yAxis : 99
					}, {
						xAxis : 99,
						yAxis : 99
					} ] ]

				}

**Comment by web5** [comment]
@whytzb   thanks
   markLine : {
symbol : [ 'circle', 'circle' ],
symbolSize : [ 0, 0 ],
itemStyle : {
normal : {
color : 'red',
label : {
position : 'top'
}
}
},
data : [ [ {
value : '99% markLine',
xAxis : -1,
yAxis : 99
}, {
xAxis : 99,
yAxis : 99
} ] ]

            }

中两个 xAxis yAxis 设置是关键

**Comment by waynezzz** [comment]
@web5 @whytzb 
设置xAxis yAxis对echarts 2.x有效，有没试过3.x.x?
