### ISSUE TITLE
关系图 dblclick事件触屏无效

### ISSUE THREAD

**Issue by luomohuafengyu** [apache/echarts#6898]
### One-line summary [问题简述]
关系图组件，因为需要同时使用拖动和点击事件跳转页面，所以我使用鼠标click事件，然后直接跳转页面了，然后我改为dblclick事件进行跳转，但是在windows系统具有触屏功能显示器上，dblclick事件双击无反应，但是用鼠标进行双击又是正常的。请问有什么方法可以处理嘛

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:'3.7.1'
+ Browser versio
version [EChecharts3
+ Browser version和版本]: chrome 59.0.3071.115（正式版本） （32 位）
+ OS Version [操作系统类型和版本]:window7

### Expected behaviour [期望结果]
希望能够提供给予帮助的解决方案

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
直接监听 dom 的 dblclick 事件呢？

**Comment by ZhelinCheng** [comment]
@pissang 折线图也有相同的问题，在移动端无法触发dblclick 事件，但可以触发click事件。

**Comment by GodsDusk** [comment]
同样的问题，关系图中dblclick无法触发，click可以触发

**Comment by 2577873863** [comment]
有人解决么？我也遇到同样的问题啦  QAQ

**Comment by kchjxxgh** [comment]
怎么解决呢？监听单击延时么？
