### ISSUE TITLE
请问在力导向图中如何判断点击的是空白区域？

### ISSUE THREAD

**Issue by huoshan12345** [apache/echarts#692]
点击的是点或者边我会判断，但是如何判断点击既不是点也不是边，而是图中的空白区域。

**Comment by web5** [comment]
木有解决方案？

**Comment by kener** [comment]
@pissang

**Comment by pissang** [comment]
那好像也没什么办法，现在点击等事件的抛出会 setTimeout，也不能通过一个标志变量或者 cancelBubble    来组织父容器事件的触发 @kener
