### ISSUE TITLE
Graph设置默认zoom以及center

### ISSUE THREAD

**Issue by houx15** [apache/echarts#6921]
### Expected behaviour [期望结果]
期望graph能够实现以下功能：
1.设置默认的zoom值（以及zoom的最大值与最小值）
（现在在option中设定zoom值，会导致图无法缩放）
2.设置某一个node为center

**Comment by DukeGJ** [comment]
参考：http://echarts.baidu.com/option.html#dataZoom-inside.start

**Comment by houx15** [comment]
@DukeGJ 您那个是dataZoom组件，但是我此处提出的是关于关系图的缩放比例的问题，好像那个不能应用过来？

**Comment by pissang** [comment]
试一下 center 属性

**Comment by houx15** [comment]
@pissang 感谢回复！zoom值设定之后会导致不能缩放（zoom比例被固定），但是本意是希望设定一个zoom的范围。

**Comment by houx15** [comment]
【update】还是打算尝试设置“默认zoom与center”，参考了源代码之后发现：
                   1.在src/charts/graph/createView中，如果setOption中设置了zoom值，其会调用setZoom函数设置zoom值
                   2.在graphAction中，roam事件触发之后会调用setZoom函数设置zoom值
                   3.【原因】在roamHelper中，对于roam事件设置了检测，当zoom值不为null的时候，不会重新设置zoom值

如果理解没有错的话，这个地方应该是有两种需求：1.需要固定在一个zoom值； 2.需要设置一个初始zoom值

**Comment by swan-zhou** [comment]
不可以设置默认缩放比，最后是怎么解决的？

**Comment by zephyo** [comment]
i have same issue, don't know how to set default zoom ratio and range for graph
