### ISSUE TITLE
yAxis轴设置min显示问题

### ISSUE THREAD

**Issue by shiyunn** [apache/echarts#6938]
### One-line summary [问题简述]
当yAxis设置最小值时，小于最小值的会显示到xAxis下面
![image](https://user-images.githubusercontent.com/1575562/32306057-30985bc4-bfb4-11e7-8e3f-c8cd7800e329.png)

### Version & Environment [版本及环境]
+ ECharts version [3.7.2]:
+ Browser version [chrome  62.0.3202.75]:
+ OS Version [MaxOS 10.13]:

### Expected behaviour [期望结果]

不显示小于最小值的图形

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value',
            min:300
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'邮件营销',
            type:'bar',
            stack: '广告',
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            type:'bar',
            stack: '广告',
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'bar',
            stack: '广告',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'搜索引擎',
            type:'bar',
            data:[862, 1018, 964, 1026, 1679, 1600, 1570],
            markLine : {
                lineStyle: {
                    normal: {
                        type: 'dashed'
                    }
                },
                data : [
                    [{type : 'min'}, {type : 'max'}]
                ]
            }
        },
        {
            name:'百度',
            type:'bar',
            barWidth : 5,
            stack: '搜索引擎',
            data:[620, 732, 701, 734, 1090, 1130, 1120]
        },
        {
            name:'谷歌',
            type:'bar',
            stack: '搜索引擎',
            data:[120, 132, 101, 134, 290, 230, 220]
        },
        {
            name:'必应',
            type:'bar',
            stack: '搜索引擎',
            data:[60, 72, 71, 74, 190, 130, 110]
        },
        {
            name:'其他',
            type:'bar',
            stack: '搜索引擎',
            data:[62, 82, 91, 84, 109, 110, 120]
        }
    ]
};

```

**Comment by DukeGJ** [comment]
这很正常啊，你设置了y轴最小值，相当于最小值作为y轴的0刻度，那么低于这个最小值肯定要在y轴下方

**Comment by SamShiyun** [comment]
这种设置最小值以后能不能隐藏xAxis轴下方的呢？ 我看highcharts是隐藏的，现在这种交互很奇怪啊

**Comment by DukeGJ** [comment]
@pissang  如果低于这个设置的y轴最小值应该是要隐藏的，有什么办法解决吗？

**Comment by Foolyou** [comment]
请问这个有解决方案了吗？看了下 bar 的属性里以及 grid 的属性里似乎都没有控制 @DukeGJ 所说的可以隐藏的属性。

**Comment by zhans1099** [comment]
现在还有这个问题 请问有解决了的么

**Comment by zhans1099** [comment]
想了零时解决办法
添加辅助条  
1、辅助条的数字和 yMin 值一样
2、对应的data 的 value值也要相应的减去 ymin 的值

app.title = '堆叠柱状图';
option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data: ["汽温", "壁温", "氧化", "超温"],
        bottom: 1
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ["1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7"]
        }
    ],
    yAxis : [
        {
            min: function(){return 450},
            max: function(){return 500},
            type : 'value'
        }
    ],
    series : [
        {
            name: '辅助',
            type: 'bar',
            stack: '广告',
            itemStyle: {
                normal: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                },
                emphasis: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                }
            },
            data: [450, 450, 450, 450, 450, 450, 450]
        },
        {
            name:'应收',
            type:'bar',
            data:[450, 450, 453, 450, 450, 450, 450]
        },
        {
            name:'电视',
            type:'bar',
            stack: '广告',
            data:[10, 20, 30, "-", "-", 40, "-"]
        },
        {
            name:'手机',
            type:'bar',
            stack: '广告',
            data:["-", "-", "-", "-", 50, "-", "-"]
        },
        {
            name:'网页',
            type:'bar',
            stack: '广告',
            data:["-", "-", "-", 0, "-", "-", 0]
        }
    ]
};

**Comment by Ray1993** [comment]
现在这个bug解决了吗 需要怎么配置
