### ISSUE TITLE
Echarts折线或者柱状堆叠（多线多柱）一维数组问题

### ISSUE THREAD

**Issue by EarlYan** [apache/echarts#6942]
### One-line summary [问题简述]
我如果有2条折线数据，对应的X轴不同，放入Echarts折线堆叠图中就会引起数据偏差的问题。
比如周一至周日。第一组数据只有周一，周三，周五，周日。第二组数据只有周二，周四，周六。
我把X轴取并集成为周一至周日。但是数据层面第一组数据的数组长度为4，而第二组数据长度为3。我的X轴长度为7。就会引起数据错位。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.2
+ Browser version [浏览器类型和版本]:Chrome 61.0.3163.100
+ OS Version [操作系统类型和版本]:macOS 10.12.6

### Expected behaviour [期望结果]
希望增加数据和X轴的对应关系。

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[120, 132, 101, 134]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[220, 182, 191]
        }
    ]
};

```

**Comment by pissang** [comment]
预处理下填入空数据让数组对其

**Comment by EarlYan** [comment]
如果设置为null的情况下。
option = {
    title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[120,null,132,null, 101,null,134]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[null,220,null, 182, null,191,null]
        }
    ]
};
就全部都是点而并非线

**Comment by EarlYan** [comment]
希望能够自动补齐线。
如今用户需要预处理自己计算两点的差值塞入中间为null的点

**Comment by yfzhangCode** [comment]
@pissang  你好，我获取的数据是动态的，所以如何根据 不同的X轴 去 替换掉那些 null 数据为后台获取的真实数据
