### ISSUE TITLE
Binning on Map坐标映射不正确

### ISSUE THREAD

**Issue by futureio** [apache/echarts#6965]
http://echarts.baidu.com/demo.html#map-bin
 官方实例中的
```
var lngExtent = [39.5, 40.6];
var latExtent = [115.9, 116.8];
```
是什么意思？
按照左下角和右上角坐标理解的化，左下角坐标是正确的，右上角坐标有较大偏差，有人遇到相同的问题吗？

**Comment by futureio** [comment]
我是使用百度Map提供的坐标拾取系统查看的
附地址： http://api.map.baidu.com/lbsapi/getpoint/index.html

**Comment by eniac27427** [comment]
精度运算问题。

**Comment by futureio** [comment]
@eniac27427 然而并不是，这个差距远远比所谓的精度差很多

**Comment by eniac27427** [comment]
朋友你好，我之前debug过，那个代码是有精度问题。而且经纬度变量在有个地方写反了，不知你发现了没。在网格太多的情况下，性能也是个问题。
    另外，如果你想实现这种效果，我倒是找到一个更好的方法，很乐意与你分享。



logindeny@163.com
 
发件人： Future.hui
发送时间： 2017-11-20 20:29
收件人： ecomfe/echarts
抄送： hello; Mention
主题： Re: [ecomfe/echarts] Binning on Map坐标映射不正确 (#6965)
@eniac27427 然而并不是，这个差距远远比所谓的精度差很多

**Comment by qqzeng** [comment]
> 朋友你好，我之前debug过，那个代码是有精度问题。而且经纬度变量在有个地方写反了，不知你发现了没。在网格太多的情况下，性能也是个问题。 另外，如果你想实现这种效果，我倒是找到一个更好的方法，很乐意与你分享。 logindeny@163.com 发件人： Future.hui 发送时间： 2017-11-20 20:29 收件人： ecomfe/echarts 抄送： hello; Mention 主题： Re: [ecomfe/echarts] Binning on Map坐标映射不正确 (#6965) @eniac27427 然而并不是，这个差距远远比所谓的精度差很多 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

你好，我也遇到了这个问题。而且，我发现，在这个 demo 中，我打上自己数据集中的坐标，发现整个区域有较大的偏移，请问你是有对应的解决办法吗？或者有其它更好的解决方案来做 binning map 吗？谢谢

**Comment by wokeT** [comment]
请问有解决方法了吗？
