### ISSUE TITLE
Click Evnets in EChart stacked Bar Chart

### ISSUE THREAD

**Issue by AngariDinesh** [apache/echarts#6980]
HI 

I am using Echart library for my chart generation in that i am using mouse click events.

I am facing issue in Stacked bar chart.
Issue:When i am clicking on stacked bar chart i am getting values like below.
productA
Dinesh

But i need this values with there respective column names like below.
Product Name:productA
Sales Rep:Dinesh

This is the link i am musing to generate stacked bar chart....
https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-y-category-stack

Please help me to get click events like above what code i need to use.

Thanks in Advance............

**Comment by AngariDinesh** [comment]
No one facing this issue......
or this is the bug in echart????

**Comment by jaykhatriwebdesigner** [comment]
Hello @AngariDinesh 

This link may help you  : http://echarts.baidu.com/echarts2/doc/example/event.html

Cheers

**Comment by zachsa** [comment]
If the title of an issue isn't spelled correctly... is it really an issue?
