### ISSUE TITLE
timsort.js:443 Uncaught Error: at mergeLow

### ISSUE THREAD

**Issue by roblav96** [apache/echarts#7003]
![bug](https://i.imgur.com/dPKwwkf.gif)
I get this error that breaks the tooltip and axis pointers:
```
timsort.js:443 Uncaught Error
    at mergeLow (timsort.js:443)
    at mergeAt (timsort.js:302)
    at TimSort.forceMergeRuns (timsort.js:268)
    at sort (timsort.js:671)
    at Storage.updateDisplayList (Storage.js:95)
    at Storage.getDisplayList (Storage.js:70)
    at Painter.refresh (Painter.js:263)
    at ZRender.refreshImmediately (zrender.js:220)
    at ZRender.flush (zrender.js:245)
    at Object.update (util.js:390)
mergeLow @ timsort.js:443
mergeAt @ timsort.js:302
forceMergeRuns @ timsort.js:268
sort @ timsort.js:671
updateDisplayList @ Storage.js:95
getDisplayList @ Storage.js:70
refresh @ Painter.js:263
refreshImmediately @ zrender.js:220
flush @ zrender.js:245
(anonymous) @ util.js:390
_update @ Animation.js:156
step @ Animation.js:170
requestAnimationFrame (async)
step @ Animation.js:168
requestAnimationFrame (async)
step @ Animation.js:168
requestAnimationFrame (async)
step @ Animation.js:168
requestAnimationFrame (async)
...
```
I'm using `time` as axis type. It seems to only happen when I zoom in very close.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: `latest`
+ Browser version [浏览器类型和版本]: Chrome `latest`
+ OS Version [操作系统类型和版本]: Mac `latest`

**Comment by roblav96** [comment]
Bump? :D

**Comment by pissang** [comment]
Can't reproduce the bug in my examples. Can you bump your option when the error occurs? Thanks

**Comment by roblav96** [comment]
@pissang Apologies for not originally including the `getOption()` :X
### [chart.getOption.json](https://gist.github.com/roblav96/3e543b1e9e29c23d40add13cb77abbfc)
Let me try and put together a fiddle for you. Thanks for taking the time to look into this =]

**Comment by roblav96** [comment]
Couldn't get a fiddle up and running without it freezing my browser 😞 

I notice that it does **not** throw these errors after I call `chart.clear()`. When I dynamically add series by calling `setOption` is when it starts to throw errors **also** while zoomed in pretty close ~10 xaxis points in view.

**Comment by roblav96** [comment]
When I comment out line `timsort.js:436` `throw new Error(); // throw new Error('mergeLow preconditions were not respected');` the axis pointer works properly. I'm not too sure why this should even throw in the first place. I need to spend more time wrapping my head around the zrender library :D
