### ISSUE TITLE
设置legend.selectedMode=false，但是保留饼图的hover效果

### ISSUE THREAD

**Issue by NangeGao** [apache/echarts#7042]
### One-line summary [问题简述]

http://echarts.baidu.com/demo.html#pie-doughnut 在这个官方示例中，我添加了legend.selectedMode= false，期待结果是，不能点击隐藏某个legend了，但是保留hover到某个legend相应饼图高亮的效果。
我记得之前是可以的，这是当前版本升级后出bug了吗？还是我哪里设置的有问题？
感谢！

### ECharts option [ECharts配置项]

```javascript
option = {
    legend: {
        orient: 'vertical',
        x: 'left',
        selectedMode: false,
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
}

```

**Comment by kathy-wazowski** [comment]
这个 bug 一年多了，管理员大大什么时候修一下啊?

**Comment by cuijian-dexter** [comment]
@kathy-wazowski Actions can be triggered manually
http://echarts.baidu.com/api.html#action
