### ISSUE TITLE
ECharts的Title支持Html的sub sup上下标标签吗？或者其他方式实现上下标？

### ISSUE THREAD

**Issue by FFHHVV** [apache/echarts#7062]
### One-line summary [问题简述]
ECharts的Title、xy轴的单位显示等支持Html的sub sup上下标标签吗？或者其他方式实现上下标？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by zztj** [comment]
同问，图表需要显示离子，一些单位比如平方，立方。

**Comment by victoryfb** [comment]
同问，在legend中如何实现上标和下标

**Comment by dataonfirecn** [comment]
同问，在legend中如何实现上标和下标

**Comment by zdbfba739** [comment]
同问，在legend中如何实现上标和下标，想要显示PM10,PM2.5,O3,SO2

**Comment by peach5460** [comment]
同问

**Comment by nxhsgit** [comment]
这个有解决方案吗？

**Comment by xusJs** [comment]
有没有大佬有啥解决方案吗？

**Comment by nwb5233** [comment]
同文，有没有大佬有解决方案？需处理气体显示

**Comment by rouxiaoxiao** [comment]
同问！！要表示气体SO2等

**Comment by rouxiaoxiao** [comment]
> 同文，有没有大佬有解决方案？需处理气体显示

请问有解决办法了么？

**Comment by susiwen8** [comment]
https://github.com/apache/incubator-echarts/issues/13363
@rouxiaoxiao

**Comment by rouxiaoxiao** [comment]
> [#13363 (comment)](https://github.com/apache/incubator-echarts/issues/13363#issuecomment-700437480)
> @rouxiaoxiao

非常感谢您的回答，也通过您的方法实现了上角标，那我如果需要表达SO2这种下角标有没有什么好的方法么？
