### ISSUE TITLE
calculable拖拽重计算拖出来后不是变成一个圆点

### ISSUE THREAD

**Issue by dengzibiao** [apache/echarts#709]
calculable拖拽重计算拖出来后不是变成一个圆点，还是原来的三角结构，并且那个三角结构跟随着鼠标移动,并且type为pie的时候tooltips出不来

**Comment by Honwhy** [comment]
我有三个series用于绘制饼图的，我也想用一个坐标轴和这三个关联起来的。
也出现了
`Uncaught TypeError: Cannot read property '_axisList' of undefined`的错误，
这种算不算不该写的属性？
```
xAxis: [
	{
	type : 'category',
	data: ['CPU','内存','存储']
					    
	splitLine : {
		show: false
	} ,
	axis: {
		axisLine: {
			show: false
	       }
         }
	}
]
```
