### ISSUE TITLE
地图区域hover时不高亮显示

### ISSUE THREAD

**Issue by closertb** [apache/echarts#7109]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望版本3能恢复版本2的hoverable设置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
如果不需要交互的话可以设置 `silent: false

**Comment by closertb** [comment]
那还是有区别，需要交互，交互用提示框做显示，只是不想颜色跟着改变。

**Comment by pissang** [comment]
@closertb 了解了，后面会优化这点

**Comment by gzr736278296** [comment]
优化之后怎么用？

**Comment by liuhao153** [comment]
优化好了吗，怎样用呢？

**Comment by pissang** [comment]
5.2.0 开始支持 `emphasis.itemStyle.color` 设置为 `'inherit'` 关闭 hover 高亮。

**Comment by liuhao153** [comment]
怎样去掉click之后的高亮呢？

**Comment by huangbh1024** [comment]
> 怎样去掉click之后的高亮呢？

找到解决办法了嘛
