### ISSUE TITLE
echarts的legend如何设置文字在图标后面呢？

### ISSUE THREAD

**Issue by wuranhw** [apache/echarts#7114]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
默认不就这样么？

**Comment by wuranhw** [comment]
@pissang 收到，我的配置是这样的   legend: {
                orient: 'vertical',
                x: 'right',
                y: 'middle',
                left: 'right',
                // selectedMode: 'false',
                // bottom: 20,
                data: result
            },
效果是文字在图标左侧。

**Comment by Jarsey** [comment]
我也有这个问题……
