### ISSUE TITLE
地图显示标签文字大小的控制

### ISSUE THREAD

**Issue by zhangJiangKai** [apache/echarts#7122]
### One-line summary [问题简述]
1:开启鼠标缩放和平移漫游以及地图显示标签后 ,随着地图放大和缩小,如何控制字体的放大缩小,或者隐藏
2:在初始化地图并显示标签后,如何根据当前容器的宽高或者其他可以算出一个合适的标签文字大小
上述两个问题因为实例容器宽高过小,显示的标签堆叠在了一起

![image](https://user-images.githubusercontent.com/33944793/33238204-5f630914-d2c3-11e7-88b3-6e91d664b3c6.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:Windows

### Expected behaviour [期望结果]

得到控制标签文字大小的思路或提示,或者其他的解决思路或提示

### ECharts option [ECharts配置项]
```js
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{b}'
    },
    series: [
        {
            roam:true,
            name: '中国',
            type: 'map',
            mapType: 'china',
            selectedMode : 'multiple',
            label: {
                normal: {
                    show: true
                },
                emphasis: {
                    show: true
                }
            },
            data:[
                {name:'广东', selected:true}
            ]
        }
    ]
};
```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xrJ8QPx_xG&v=1

**Comment by LvBay** [comment]
我使用树图的时候也遇到类似问题，请问有解决方案吗？我目前是通过隐藏叶子节点的labe临时缓解一下，但也不是长久之计。 @pissang @zhangJiangKai

**Comment by LvBay** [comment]
我发现echart2貌似不会存在这个问题 [(https://echarts.baidu.com/echarts2/doc/example/tree2.html)]
