### ISSUE TITLE
Bar Chart数据列顺序问题？

### ISSUE THREAD

**Issue by TangHuanan** [apache/echarts#7146]
### One-line summary [问题简述]

Bar Chart能不能按照数据的大小，按顺序显示, 包括数轴上的Label？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.x
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: mac os

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by eidonjoe** [comment]
可以在传入data之前自己进行一步排序

**Comment by TangHuanan** [comment]
这样和坐标轴上的Label就对应不上了， y轴是category类型

**Comment by pissang** [comment]
现在需要在排序的时候把 xAxis.data 的顺序也换过来，后续会在这上面做优化简化这个工作量

**Comment by TangHuanan** [comment]
我现在的使用和这个图是差不多的， http://gallery.echartsjs.com/editor.html?c=xSkFFABj0e，y轴是category类型， x轴是value, 数据排序后， 明显值和y轴的Label就对应不上了

**Comment by meifu2027** [comment]
> 现在需要在排序的时候把 xAxis.data 的顺序也换过来，后续会在这上面做优化简化这个步骤

老哥，现在这个特性加了吗？

**Comment by 100pah** [comment]
（1）可使用 `xAxis.inverse`。
（2）先排序 `series.data` 再向 echarts 设置。

**Comment by meifu2027** [comment]
> （1）可使用 `xAxis.inverse`。
> （2）先排序 `series.data` 再向 echarts 设置。

有考虑在未来的版本里支持根据series.data的值进行排序吗？
