### ISSUE TITLE
echart3+bmap，初始化图标之后，异步更新数据在第一次更新时会更新整个地图而不是只更新数据

### ISSUE THREAD

**Issue by 865077695** [apache/echarts#7153]
echart3+bmap，初始化图标之后，异步更新数据在第一次更新时会更新整个地图而不是只更新数据

### Version & Environment [版本及环境]
+ echart3
+ chrome、360、edge、Firefox

### Expected behaviour [期望结果]
如何才能只更新数据而不是整体全部刷新

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ruipeng-wang** [comment]
I had the same problem!
