### ISSUE TITLE
echarts官网文档 ‘配置项’ 下的‘Series’里对'type:gauge'类型缺少'data'和'center'的描述？

### ISSUE THREAD

**Issue by zhang122622623** [apache/echarts#7159]
### One-line summary [问题简述]
   查看官方例子中仪表盘的绘制时，series里有'data'和‘center’这两个参数；链接：
 http://echarts.baidu.com/demo.html#gauge-car-dark
   对照 echarts官网文档，发现 ‘配置项’ 下的‘Series’里，关于仪表盘图'type:gauge'类型的描述里并没有关于'data'和'center'这两个参数的描述；链接：http://echarts.baidu.com/option.html#series-gauge.type

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
   虽然可以自己琢磨这两个参数的意义和用法，但还是希望文档中能加上对这两个参数的描述；

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢建议，后面会补上

**Comment by shyangs** [comment]
gauge, 底下 data 显示出来的 name 的位置和大小可以改吗?

**Comment by zhang122622623** [comment]
@shyangs 可以改，data里的name和value分别对应series[i]的title和detail属性，在这两个属性里可以设置相应的文字样式和位置；具体可看教程：[http://echarts.baidu.com/option.html#series-gauge.title](url)

**Comment by alexsunday** [comment]
center现在仍未补上

**Comment by Lstoryc** [comment]
都2020了 还没补上
