### ISSUE TITLE
force图如何拖拽一个节点时，其他节点不受影响

### ISSUE THREAD

**Issue by shangxinbo** [apache/echarts#7204]
### One-line summary [问题简述]

拖拽一个节点时，其他节点的位置会动，如果节点多了的话，会不停的旋转，请问这个问题怎么解决？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: latest
+ Browser version [浏览器类型和版本]: chrome latest
+ OS Version [操作系统类型和版本]:  windows

### Expected behaviour [期望结果]

拖拽一个节点时，其他节点不动

**Comment by SmallBlackZhang** [comment]
同样的问题，还没找到好的解决方案。
