### ISSUE TITLE
想要获取原点位置

### ISSUE THREAD

**Issue by vkiller178** [apache/echarts#7235]
### 想要获取原点位置

想在横轴下面加一个类似于播放进度条的东西，但是现在不能确定原点位置？请问有什么办法吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.7.2+ 
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/19320239/33817312-dd42f01c-de79-11e7-81d2-d504f1cd987b.png)

**Comment by pipione** [comment]
这个问题你解决了吗，我也有个类似的功能需要实现。 如果能得到帮助十分感谢。
