### ISSUE TITLE
X Axis Data is not Showing 

### ISSUE THREAD

**Issue by prince082583** [apache/echarts#7240]
### One-line summary [问题简述]
First X axis data is not showing when there is no data in first series

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
xAxis: [{
                            type: 'category',
                            data: ['Above 70', 'Above 50','Below 50'],
                          
                        }],

}

```

**Comment by chrisparma** [comment]
I have the same issue? Did you find any solution?
