### ISSUE TITLE
tree如何通过convertToPixel获取像素坐标值？

### ISSUE THREAD

**Issue by wg5945** [apache/echarts#7265]
### One-line summary [问题简述]

想模仿“拖拽的小例子”实现，tree中每个节点生成一个graphic

`position: myChart.convertToPixel('grid', dataItem),`
这个方法貌似不能再tree中使用，有没有比较好的实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome63
+ OS Version [操作系统类型和版本]:Mac

**Comment by deqingli** [comment]
Sorry, I don't quite understand what your problem is? please provide a demo.
