### ISSUE TITLE
使用SVG渲染的bug

### ISSUE THREAD

**Issue by fzudust** [apache/echarts#7312]
### One-line summary [问题简述]

使用SVG渲染的时候,resize无效
在ie和火狐浏览器中,x轴label显示错位

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome 63,ie11,firefox 57
+ OS Version [操作系统类型和版本]:windows 7

### Expected behaviour [期望结果]
可以正常使用resize

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
                trigger: 'axis',
                formatter(params) {
                    return params[0].data[0].replace('.', '月') + '日<br/>' + params[0].data[1] + '次'
                },
                backgroundColor: '#61a0a8',
                textStyle: {
                    color: 'white'
                }
            },
            xAxis: {
                name: '时间',
                type: 'category',
            },
            yAxis: {
                name: '数量(次)',
                type: 'value',
            },
            series: [{
                name: 'line',
                type: 'line',
                data: []
            }]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/7448572/34143869-e10f118e-e4c9-11e7-8541-9c25e3f93a27.png)

**Comment by rcjiang** [comment]
使用svg渲染时关于实例的resize问题我再补充下我遇到的问题, 创建图表实例后(创建实例时, 配置中没有声明图表宽度):
1. 当图表的容器宽度变小时, resize方法有效;
2. 当图标的容器宽度变大时, resize方法无效, 仍认为是创建实例时容器的宽度. 
3. 使用resize({width: dom.clientWidth}), 或者给出一个大于创建时容器宽度的值, 还是无效的;
4. 以上的"无效"是指:图表本身被放大了, 但是超过初始宽度的部分被截断了没显示.
5. 如果修改为用canvas渲染, 则正常.

**Comment by pissang** [comment]
@rcjiang 这个问题在最新的代码中已经修复了

**Comment by wangxingwu0** [comment]
这个问题依然存在，麻烦您确认

**Comment by wangxingwu0** [comment]
@pissang 这个问题依然存在

**Comment by adrielsantiago** [comment]
@pissang - Any update on this? I'd love to help get this resolved. I'm seeing this issue persist in the latest Firefox (currently 63.0.3). Seems fine in Chrome and Safari.
