### ISSUE TITLE
既实现个省份颜色不同，又能使用scatter3D  lines3D  bar3D

### ISSUE THREAD

**Issue by jiangshichao** [apache/echarts#7333]
[问题简述]
        需要使用echarts-gl画地图，每个省的颜色不一样，并且需要在上面画点  线  柱体
现在的问题是使用map3D  和visualMap 组件可以实现各省颜色不同，但是再使用scatter3D的时候没法选择坐标系了，而使用geo3d组件和scatter3D   lines3D    bar3D  可以做出地图效果，但是不能实现各省不同颜色，有上面办法二者兼容吗

       另我现在画曲线是用贝塞尔曲线方程计算坐标画的，目前飞线有没有曲线类型？

 [版本及环境]
 [ECharts 版本]:
3.8.4
 [浏览器类型和版本]:
 [操作系统类型和版本]:

[期望结果]

     既实现个省份颜色不同，又能使用scatter3D  lines3D  bar3D

 [其他信息]

**Comment by pissang** [comment]
目前是 visualMap 只能给 series 中的 map3D 使用，map3D 上无法显示其它类型的系列，所以只能使用 geo3D 然后设置 regions 里面的颜色了

```js
geo3D: {
regions: [{
  name: '浙江省',
  itemStyle: {areaColor: 'red' }
}]
}
```

**Comment by Jfs007** [comment]
我也遇到这个，那请问下有没有js的暴露出来的visualMap的接口，，因为regions的话我没法知道怎么根据数据映射对应的颜色，，如果有个接口，我就可以和line3D或者bar3D的颜色统一起来

**Comment by REGGEN8** [comment]
题主找你好    这个你有demo吗  可以参考下不

**Comment by zhaoxiaoran** [comment]
> 目前是 visualMap 只能给 series 中的 map3D 使用，map3D 上无法显示其它类型的系列，所以只能使用 geo3D 然后设置 regions 里面的颜色了
> 
> ```js
> geo3D: {
>   regions: [{
>     name: '浙江省',
>     itemStyle: {areaColor: 'red' }
>   }]
> }
> ```
4.0的版本现在支持了吗

**Comment by changfu2015** [comment]
标记的图形想换成effectScatter 类型的闪动圆点如何实现，配置好像没有生效

**Comment by linxiaowang** [comment]
> 标记的图形想换成effectScatter 类型的闪动圆点如何实现，配置好像没有生效
有好的解决方法了吗

**Comment by yswang0927** [comment]
这个3D Map问题最新的5.4.3版本也没有能实现，很纠结，用echarts渲染3D Map 很方便，但是一些常见的诉求又满足不了。
