### ISSUE TITLE
yAxis splitLine interval: function(index, val) {} doesn't work

### ISSUE THREAD

**Issue by sunnyShining** [apache/echarts#7336]
### One-line summary [问题简述]
在使用折线图时，想发现纵轴横线过于密集，想通过yAxis.splitLine.interval使线条变少，发现使用函数不能执行

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.4
+ Browser version [浏览器类型和版本]: all
+ OS Version [操作系统类型和版本]: all

### Expected behaviour [期望结果]

纵轴横线过于密集，希望通过配置使横线变少

### ECharts option [ECharts配置项]

```javascript
// 部分配置信息如下，console不打印index
option = {
	yAxis: {
                    axisTick: {
                        show: false,
                    },
                    axisLine: {
                        show: false,
                    },
                    splitLine: {
                        show: true,
                        lineStyle: {
                            color: '#ddd',
                            width: 1,
                            type: 'solid'
                        },
                        interval: function(index, val) {
                            console.log(index);
                            return val;
                        }
                    },
	}

```
### Other comments [其他信息]

￼

**Comment by pissang** [comment]
请具体描述你的问题

**Comment by sunnyShining** [comment]
已详细描述

**Comment by amittonge** [comment]
The function specified for interval property is not get invoked in case of value axis.

**Comment by Xalio08** [comment]
Why ? It would be really useful for time intervals, which are not the same depending on the month.
