### ISSUE TITLE
请问，有显示出一列的堆积值之和的label吗？

### ISSUE THREAD

**Issue by royleexh** [apache/echarts#740]
类似温度计例子中的那种（[http://echarts.baidu.com/doc/example/bar10.html](http://echarts.baidu.com/doc/example/bar10.html)），但它是把最后最后一组数据的label给用了，如果我把最后一组数据对应的legend点掉，就没法显示一个置顶的和值，有没有专门的标签？

**Comment by mosakashaka** [comment]
@royleexh  请问空data + formatter这个是怎么做的呢，我是像下面这样，增加了一个空的series，但是鼠标移动到每个bar上面，都会显示这个series名称，然后值是0.。。，

`           
         
{
                        name: '小计',
                        type: 'bar',
                        stack: '总量',
                        label: {
                            normal: {
                                show: true,
                                position: 'right',
                                formatter: function (param) {
                                    var o = myChart.getOption().legend[0].selected;
                                    for (var i = 0, l = option.yAxis.data.length; i < l; i++) {
                                        if (option.yAxis.data[i] == param.name) {
                                            var sum = 0;
                                            for (var j = 0, m = option.series.length; j < m; j++) {
                                                if (o[option.series[j].name] != false) {
                                                    sum += option.series[j].data[i];
                                                }
                                                //alert(option.series[j].name + ":" + o[option.series[j].name] + ":" + sum);
                                            }
                                            return sum;
                                        }
                                    }
                                }
                            }
                        },
                        data: [0, 0, 0, 0, 0, 0]
                    }

`
