### ISSUE TITLE
地图拖拽出div后，鼠标移回来可继续拖拽

### ISSUE THREAD

**Issue by LinXiudong** [apache/echarts#7428]
### One-line summary [问题简述]

地图配置可拖拽后，在地图上按下左键可进行拖拽，放开左键取消拖拽。但如果按下左键后把鼠标移出div，后松开左键，再把鼠标移入div，这时不需要再次按下左键，地图也会随着鼠标拖拽移动

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 466035017** [comment]
mouseUP没接收到呗正常

**Comment by TonySheva** [comment]
emmm....在用气泡图的时候，拖拽放大了一定比例，鼠标移出div

**Comment by TonySheva** [comment]
这个问题怎么解决呢？尝试在移入div时，给地图做了一次 .click(),但这样不算是一次mouseup...

**Comment by autukill** [comment]
能主动取消这个事件吗? 
我的场景是: 用户左右滑动 inside datezoom 时, canvas 外出现 loading 层. 这时候能主动释放 echarts 的按下状态就好.

**Comment by zwb910615** [comment]
myChart.on('globalout', function (params) {
    
      var mouseEvent= document.createEvent('MouseEvents');
        mouseEvent.initEvent('mouseup', true, true);
        myChart._dom.getElementsByTagName('canvas')[0].dispatchEvent(mouseEvent)
        
  
    });

**Comment by autukill** [comment]
> myChart.on('globalout', function (params) {
> 
> ```
>   var mouseEvent= document.createEvent('MouseEvents');
>     mouseEvent.initEvent('mouseup', true, true);
>     myChart._dom.getElementsByTagName('canvas')[0].dispatchEvent(mouseEvent)
>     
> 
> });
> ```

解决了, 我在 vuejs 中使用.相关代码

```
<template>
  <div ref="dom" class="charts"></div>
</template>

<script>
...
    this.chart = echarts.init(this.$refs.dom)
    this.chart.on('globalout', (params) => {
        let mouseEvent = document.createEvent('MouseEvents');
        mouseEvent.initEvent('mouseup', true, true);
        this.$refs.dom.getElementsByTagName('canvas')[0].dispatchEvent(mouseEvent)
      });
...
</script>
```
