### ISSUE TITLE
echarts-gl,surface曲面图里的data数据有什么规律吗

### ISSUE THREAD

**Issue by tomhaitao** [apache/echarts#7429]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hanwenbo** [comment]
无解啊

**Comment by Eli-yu-first** [comment]
不知道
