### ISSUE TITLE
地图上的点渐变不兼容ie8

### ISSUE THREAD

**Issue by xyxuyao** [apache/echarts#7445]
### One-line summary [问题简述]

ie8下地图上的点不显示渐变，如图：
谷歌浏览器效果图：
![m69gz7c7bg 00d2rd s k](https://user-images.githubusercontent.com/13941855/34665889-e336313a-f49c-11e7-97b0-7e075b4e5c68.png)
ie8效果图：
![5v n4uzyu o7u9 qjvl g](https://user-images.githubusercontent.com/13941855/34665901-eaede44a-f49c-11e7-9c9f-119f50bfa0cf.png)

此版本控制颜色的拖动条渐变问题修改代码后解决了，但是点还是不兼容ie8：
![image](https://user-images.githubusercontent.com/13941855/34665967-22869d20-f49d-11e7-97fe-9fc6ab011dfd.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:ie8
+ OS Version [操作系统类型和版本]:window

### Expected behaviour [期望结果]
期望地图上的点的渐变能兼容到ie8

### ECharts option [ECharts配置项]

itemStyle: {
                    normal: {
                        color: {
                            type: 'linear',
                            x: 0,
                            y: 0,
                            x2: 1,
                            y2: 1,
                            colorStops: [{
                                offset: 0, color: '#FACD87'
                            }, {
                                offset: 0.4, color: '#FACD87' 
                            }, {
                                offset: 0.4, color: '#F08D69' 
                            }, {
                                offset: 1, color: '#F08D69' 
                            }]
                        }
                    }
                }

```




### Other comments [其他信息]
<!-- For example: Screenshot or Online demo -->
<!-- [例如，截图或线上实例 (JSFiddle/JSBin/Codepen)] -->

**Comment by liqingzheng** [comment]
IE8本来就不支持渐变的。IE8采用vml渲染。所以你这个无法实现。

**Comment by xyxuyao** [comment]
@liqingzheng 我已经找到原因了 zrender目录下的lib/vml/graphic.js代码红框部分判断为false, 修改一下让设置渐变的时候也进入这个if语句就可以显示渐变了 
![image](https://user-images.githubusercontent.com/13941855/34751911-25cbf036-f5ea-11e7-8ffe-119e468d122c.png)

**Comment by xyxuyao** [comment]
@pissang   @liqingzheng 设置地图上的点为渐变的时候，zrender目录下的lib/vml/graphic.js代码红框部分判断为false, 修改一下让设置渐变的时候也进入这个if语句就可以显示渐变了
如图：

![image](https://user-images.githubusercontent.com/13941855/34752331-8d0e1722-f5ec-11e7-88d7-61c654da51f1.png)

**Comment by anlena** [comment]
这个在echarts.js怎么改啊？我找不到改的地方
