### ISSUE TITLE
建议饼图加一个gap参数来绘制扇形之间的间隙

### ISSUE THREAD

**Issue by csyasin** [apache/echarts#7450]
### One-line summary [问题简述]
如题, 开发中遇到需要在饼图的各扇形之间加上分隔的间隙, 目前只能自己添加假数据来模拟间隙的存在, 而且间隙的比重需要手动计算, 并且这个用来当作间隙的假数据的个数还不一定, 当数据量比较多或者是存在值为0的数据的时候处理起来就比较麻烦

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
饼图加一个参数来控制各扇形之间的间隙大小

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
是否可以通过设置 [borderWidth](http://echarts.baidu.com/option.html#series-pie.itemStyle.normal.borderWidth) ，然后将边框设为透明或背景色，实现需求？

**Comment by paradox010** [comment]
borderwidth在饼图只有一个数据(100%)的时候也会显示边框

**Comment by xialvjun** [comment]
@Ovilia 设为透明的时候, borderWidth 就失效了

**Comment by CocaColf** [comment]
> 是否可以通过设置 [borderWidth](http://echarts.baidu.com/option.html#series-pie.itemStyle.normal.borderWidth) ，然后将边框设为透明或背景色，实现需求？

这个不行，当只有一个数据时，按理来说要显示一个完整的圆，但实际上是缺了设置的border这一块

**Comment by TLovers** [comment]
> @Ovilia 设为透明的时候, borderWidth 就失效了

透明borderWidth 确实是没有效果了

**Comment by shenxiang216** [comment]
现在有解决吗？

**Comment by shenxiang216** [comment]
> > @Ovilia 设为透明的时候, borderWidth 就失效了
> 
> 透明borderWidth 确实是没有效果了

大佬现在怎么解决的这个问题呢，我用的padAngle，涉及觉得间距不均匀
