### ISSUE TITLE
Switching Language?

### ISSUE THREAD

**Issue by ghost** [apache/echarts#7451]
Hey guys,

just wanted to say great job on this amazing library! 👍 

I'm wondering about one thing: is there a way to switch language more gracefully than renaming the language files? I found the different langEN.js etc. files in the lib folder and renaming the chinese lang.js to langCN.js and the english one to lang.js does switch the language, but wouldn't it be much better to have some generic language option?

I.e. in the echarts API you can specify 
```js
lang: 'EN',
```
and it will load the langEN.js file? Is this already in place and have I missed it?

If not, I would be happy to contribute with something like this.

Thanks!

**Comment by dburucu** [comment]
switch language and switch output formats for values would be great

**Comment by dirk-ecker** [comment]
yes great idea, does anybody know if this is intended

**Comment by 100pah** [comment]
Current, switch language on runtime has not been supported. 
Language can only be switched on build stage, as [this doc introduced](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Create%20Custom%20Build%20of%20ECharts):

```shell
node node_modules/echarts/build/build.js --lang en
```

**Comment by Karamuto** [comment]
In highcharts this is possible simply calling a function: https://api.highcharts.com/highcharts/lang

Maybe this would be also an option for here? I really need this feature without the need to rebuild the library every time there is an update.

**Comment by BrianGilbert** [comment]
it would be great if there was a config item for lang switching, you could even leave the default as chinese.. an example of this proposal that would define to use EN translations:

```
option = {
    lang: 'EN',
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: 'bar',
        showBackground: true,
        backgroundStyle: {
            color: 'rgba(220, 220, 220, 0.8)'
        }
    }]
};
```

**Comment by lixianshengdezhanghao** [comment]
I think this is a more urgent thing！！！！！！

**Comment by JSchmidt63** [comment]
I think is a urgent feature. Switches given langFI or langDE without building echarts. There is a var lang sadly without a interface.

**Comment by BrianGilbert** [comment]
@JSchmidt63 I agree this needs to be resolved, but for you own benefit we managed by using https://www.npmjs.com/package/patch-package

**Comment by stereokai** [comment]
Any news about this? Thanks

**Comment by JSchmidt63** [comment]
Look here in this issue
Progress of Next Major Version: 5.0 #12926
to be build at a extension, planed at september

**Comment by wf123537200** [comment]
can see the [PR13083](https://github.com/apache/incubator-echarts/pull/13038) and welcome to join the PR.  :p
