### ISSUE TITLE
请问如何设置面积图里面积的透明度？

### ISSUE THREAD

**Issue by JasonZhou903** [apache/echarts#746]
例如http://echarts.baidu.com/doc/example/line3.html
这样设置的itemStyle: {normal: {areaStyle: {type: 'default'}}}面积颜色会自动分配，
但是又怎么设置它的透明度呢？

**Comment by lcoder** [comment]
areaStyle.opacity 不行吗http://echarts.baidu.com/option.html#series-line.areaStyle.normal.opacity
