### ISSUE TITLE
iframe中echart无法获取问题

### ISSUE THREAD

**Issue by zhoujun900113** [apache/echarts#7480]
您好，我在使用echarts图表的过程中遇到一个问题，希望能够得到解答，谢谢！
我有个主页面叫work.jsp，内部有个div，id叫chart0，然后还有个iframe，我会在iframe中调用echarts.init(parent.document.getElementById("chart0"));此时chart0内部可以被绘制出echarts图表，但之后我在work.jsp内部的js调用echarts.getInstanceByDom(document.getElementById("chart0"));并不能获取到该echart图表实例，请问这个怎么解决？

**Comment by pissang** [comment]
因为两个不在同一个命名空间里，所以没法互相获取

**Comment by zhoujun900113** [comment]
@pissang 那这个问题没有其他方式解决吗？

**Comment by a24576946** [comment]
同样的问题，难道没有解决方案吗

**Comment by zpf96126** [comment]
同问，不过我是在绘制出echarts图表后，重新打开iframe ,然后使用var demo=echarts.getInstanceByDom(parent.document.getElementById("chart0"))去获取图表实例，然后提示demo 为Undefined

**Comment by zpf96126** [comment]
@zhoujun900113 我想到一个办法，就是你把echarts.init放在work.jsp中的一个函数里，假设叫a
function a(参数..){echarts.init(document.getElementById("chart0"))... },然后在iframe中使用parent.document.a()来进行echart的初始化,这样就能在work.jsp中调用echarts.getInstanceByDom(document.getElementById("chart0"));获取图表实例
