### ISSUE TITLE
Can I customize the tree chart's node  

### ISSUE THREAD

**Issue by gyanendrakumar** [apache/echarts#7486]
### One-line summary [问题简述]
Hi Team ,Can I customize the tree chart's node in ECharts Tree
Can I use add button along with node symbol (one for expand n collapse and other for add child node) .
so that I can add child node from add button .
Can I add some Template so that we can add TextBox  on mouseover .

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by orenaksakal** [comment]
+1
