### ISSUE TITLE
echarts 4.0如何在ppt中使用

### ISSUE THREAD

**Issue by screetBloom** [apache/echarts#7503]
### One-line summary [问题简述]
希望可以像描述的一样可以在ppt中使用Echarts，但是目前好像没有相关介绍

### Expected behaviour [期望结果]
希望可以像描述的一样可以在ppt中使用Echarts，但是目前好像没有相关介绍

**Comment by Ovilia** [comment]
目前还在等待在 PPT 应用商店上线，到时候会有文档的，谢谢~

**Comment by bryan-lai** [comment]
期待这个功能

**Comment by screetBloom** [comment]
好的 ，谢谢回复

**Comment by kaka2008** [comment]
8天过去了，还没有审核通过吗？

**Comment by kaka2008** [comment]
这个功能放弃了吗？

**Comment by huandzh** [comment]
hi, @pissang . 不知道现在进展如何了？THX

**Comment by hanfengcan** [comment]
过了好久了,什么时候过审核呢

**Comment by cainnn** [comment]
现在情况怎么样了？还没审核通过吗？

**Comment by huaji1992** [comment]
好期待呀~~~

**Comment by ssp97** [comment]
好期待啊。还没有审核通过吗？
