### ISSUE TITLE
axisLabel中的width和height无法使用百分比

### ISSUE THREAD

**Issue by KumaCool** [apache/echarts#7525]
### One-line summary [问题简述]
xAxis, yAxis > axisLabel > width, height
xAxis, yAxis > axisLabel > rich > width, height
设置百分比无效,会导致标签消失.以及不是特别理解文档里关于这两参数的解释.
我无法控制及获取轴标签的宽度.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8 + ~ 4.0
+ Browser version [浏览器类型和版本]: chrome 63.0.3239.132
+ OS Version [操作系统类型和版本]: os sierra 10.12.6

### Expected behaviour [期望结果]
![](http://chuantu.biz/t6/208/1516242738x-1404781246.jpg)
上面是我初期想实现的结果...我想要控制标签的宽或获得宽以实现下面的效果图.
最终我是想完成下面X轴的效果.如有其它变通的方法谢谢指点下.
![](http://chuantu.biz/t6/208/1516242936x-1404793585.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        axisLabel: {
            backgroundColor: 'red',
            width: '100%',
            formatter(v, i) {
                return i % 2 > 0 ? '{blue|}' : v
            },
            rich: {
                blue: {
                    width: '100%',
                    backgroundColor: 'blue'
                }
            }
        }
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        areaStyle: {}
    }]
}

```

**Comment by lvybriage** [comment]
I met the same problem.

**Comment by tz310200** [comment]
不紧紧是%没用,数值也不行 我不想用文字自动高度,想自己手动设置也不行

**Comment by zouysay** [comment]
> 不紧紧是%没用,数值也不行 我不想用文字自动高度,想自己手动设置也不行

我也是width 设置不了，有找到解决方案么
