### ISSUE TITLE
lines3D tooltip无效

### ISSUE THREAD

**Issue by Mying666** [apache/echarts#7528]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 466035017** [comment]
同#6317

**Comment by pissang** [comment]
lines3D 暂时不支持 tooltip

**Comment by 466035017** [comment]
@pissang 后续会考虑开发吗？

**Comment by htengweb** [comment]
lines3D不可以加事件吗？

**Comment by LbyKevin** [comment]
现在lines3D可以加事件吗？@pissang
