### ISSUE TITLE
datazoom事件产生的params，不止一种形式

### ISSUE THREAD

**Issue by shmilyoo** [apache/echarts#7602]
### One-line summary [问题简述]
在datazoom事件发生，在回调里面打印params字符串：
当使用inside缩放的时候，产生的params为：

    {"type":"datazoom","batch":[{"dataZoomId":"\u0000\u0000-\u00001","start":0,"end":1.774238498512835,"type":"datazoom","batch":null}]}

当使用slider缩放或者拖动的时候，产生的params字符串为

    {"type":"datazoom","from":"viewComponent_19_0.4897147372797057","dataZoomId":"\u0000\u0000-\u00000","start":1.3888888888888888,"end":6.496460720735057}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by NANAYWY** [comment]
> ### One-line summary [问题简述]
> 在datazoom事件发生，在回调里面打印params字符串：
> 当使用inside缩放的时候，产生的params为：
> 
> ```
> {"type":"datazoom","batch":[{"dataZoomId":"\u0000\u0000-\u00001","start":0,"end":1.774238498512835,"type":"datazoom","batch":null}]}
> ```
> 当使用slider缩放或者拖动的时候，产生的params字符串为
> 
> ```
> {"type":"datazoom","from":"viewComponent_19_0.4897147372797057","dataZoomId":"\u0000\u0000-\u00000","start":1.3888888888888888,"end":6.496460720735057}
> ```
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]:
> * Browser version [浏览器类型和版本]:
> * OS Version [操作系统类型和版本]:
> 
> ### Expected behaviour [期望结果]
> ### ECharts option [ECharts配置项]
> ```js
> option = {
> 
> }
> ```
> 
> ### Other comments [其他信息]

请问你的回调是怎么做的
