### ISSUE TITLE
“北京公交路线 - 百度地图”的Demo中的lines-bus.json坐标偏移，公交数据未加密？

### ISSUE THREAD

**Issue by BranZhang** [apache/echarts#7606]
### One-line summary [问题简述]
“北京公交路线 - 百度地图”的Demo中的lines-bus.json的数据与百度地图底图不匹配，是因为坐标系没有统一，公交数据没有加密？

![image](https://user-images.githubusercontent.com/10242480/35366652-7ba1e160-01b5-11e8-8b57-51527e568913.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:Chrome 62.0
+ OS Version [操作系统类型和版本]:Windows 10

官网示例：
http://echarts.baidu.com/examples/editor.html?c=lines-bmap-bus

### Expected behaviour [期望结果]

公交数据与百度地图的道路数据匹配，避免出现公交横穿建筑轮廓的情况。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by LeoLiu8023AmyLu** [comment]
gps坐标直接放入会有偏移情况，是否需要转化坐标？

**Comment by plainheart** [comment]
公交数据未做处理，仅作示例，实际使用需转为百度坐标系。
