### ISSUE TITLE
X轴向左移动折线图被切断，怎样让线能跟Y轴连接起来

### ISSUE THREAD

**Issue by x3852** [apache/echarts#7620]
![image](https://user-images.githubusercontent.com/26081477/35390822-a8aa51da-0217-11e8-87b4-544bcedafcf9.png)
![image](https://user-images.githubusercontent.com/26081477/35390967-2ae0eb0a-0218-11e8-9d4f-8666fc778ca0.png)

**Comment by chuihinwai** [comment]
```dataZoom: [
        {
            filterMode: 'none'
        }
    ]```

http://echarts.baidu.com/option.html#dataZoom-slider.filterMode
