### ISSUE TITLE
echart3关系图力导向布局如何为设为图片的symbol加边框和变圆？

### ISSUE THREAD

**Issue by WQQWQQ** [apache/echarts#7643]
### One-line summary [问题简述]
echarts3的力导向关系图的节点symbol设为'image://url'的图片后如何为其添加边框和修改为圆形？设置symbol为circle以及itemStyle的color选项设为image用dom元素纹理填充不重复也只能见到很模糊的图片左上角。请问关系图的节点需要对后端返回的图片添加边框和变圆应该如何实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts v3.8.5
+ Browser version [浏览器类型和版本]:所有浏览器
+ OS Version [操作系统类型和版本]:所有操作系统

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

需要实现的效果如下图：
![image](https://user-images.githubusercontent.com/12482800/35496864-bfcff9d0-0502-11e8-9963-a25377768af3.png)

**Comment by pissang** [comment]
暂时没有办法

**Comment by WQQWQQ** [comment]
感谢您的回复~希望echarts团队继续完善~

**Comment by WQQWQQ** [comment]
感谢您的回复~

**Comment by lengfo** [comment]
遇到同样的问题，期望支持

**Comment by tonyzheng1990** [comment]
期望支持变圆

**Comment by pylee** [comment]
2019年特来请求官方支持

**Comment by zhaoyingli** [comment]
2020年特来请求官方支持

**Comment by ruinuola** [comment]
期望支持加边框

**Comment by xulongzhe** [comment]
2024年特来寻求支持

**Comment by cjlhll** [comment]
2025年特来寻求支持
