### ISSUE TITLE
经纬度转换为平面坐标

### ISSUE THREAD

**Issue by xyxuyao** [apache/echarts#7654]
### One-line summary [问题简述]
我想通过经纬度转换为对应的平面坐标，然后在地图上画饼图，请问echarts能提供一个对应的转换方法吗，或者有没有其它解决办法

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
期望官方能提供一个对应的转换方法，谢谢！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by luguokong** [comment]
http://echarts.baidu.com/api.html#echartsInstance.convertToPixel

**Comment by luguokong** [comment]
参考：http://echarts.baidu.com/api.html#echartsInstance.convertToPixel

**Comment by xyxuyao** [comment]
感谢您的回答@luguokong，我用了api提供的方法还是不能转换，返回的是undefined ，
echartObj.convertToPixel('geo', [104.065735, 30.659462], 我用的是echarts4.0.2的版本

**Comment by luguokong** [comment]
@xyxuyao 这个要看你是使用了geo组件，还是直接使用了series.map
如果没有使用geo组件应该是echartObj.convertToPixel({seriesIndex: 地图的index}, [104.065735, 30.659462])

**Comment by xyxuyao** [comment]
@luguokong 谢谢!， echartObj.convertToPixel({seriesIndex: 0}, [104.065735, 30.659462])  2D地图是可以获取到的 用的3D地图就获取不到了

**Comment by pissang** [comment]
@xyxuyao 3D 的暂时还不支持坐标转换

**Comment by xyxuyao** [comment]
@pissang 好的，谢谢，期待将来能添加这个功能， 我用了其它js库中的转换方法，但是缩放比例和距离需要做调整，请问有其它好的解决办法吗？

**Comment by zmm2tysu** [comment]
@xyxuyao 你好，我现在也碰到这个问题。echartObj.convertToPixel({seriesIndex: 0}, [104.065735, 30.659462])用这个转换出来的像素值就是坐标，好像没转换对，能沟通下你的方法么？
