### ISSUE TITLE
反馈4.0版本和 4.0.2版本中配置项中的geo的label的位置（position/offset的配置）失效

### ISSUE THREAD

**Issue by webLame** [apache/echarts#7676]
One-line summary [问题简述]

使用geo地理坐标系组件，配置项label中的position、offset、distance按照文档配置没有效果，位置没有发生改变。

Version & Environment [版本及环境]

ECharts version [ECharts 版本]:
Browser version [浏览器类型和版本]:
OS Version [操作系统类型和版本]:
echarts版本4.0，浏览器是chrome63，win10操作系统
Expected behaviour [期望结果]
修改的label的属性起作用，位置改变；

ECharts option [ECharts配置项]
```js
option = {
backgroundColor: '#021023',
		geo: {
			map: opt.map,
			roam: false,
			layoutCenter: ['50%', '50%'],
			layoutSize: "100%",
			itemStyle: {
				normal: {
					areaColor: '#16345B',
					borderColor: '#3B9C7B',
					borderWidth: 1
				},
				emphasis: {
					color: 'rgba(37, 43, 61, .5)'
				}
			},
            label: {
                normal: {
                    show:true,
                    color:"#c5f7da",
                    fontWeight:"bold",
                    fontSize:"11",
                    position:"insideTopRight"
                },
                emphasis: {
                    color: "#c5f7da"
                }
            }
		},
		series: opt.series


}
```
Other comments [其他信息]

![35383001-fb96e154-01fb-11e8-9ea8-ed1ade9fc438](https://user-images.githubusercontent.com/29446513/35604230-3e6bf54e-067c-11e8-807b-e3e7fb07141d.png)

**Comment by LtHelo** [comment]
加1
