### ISSUE TITLE
能否支持自定义绘图引擎

### ISSUE THREAD

**Issue by ShaneLi** [apache/echarts#7694]
我希望能够在React Native上使用Echarts， 请问最佳解决方法如何？（主页链接的https://github.com/somonus/react-native-echarts  每个图都要建立一个新的Webview，我们希望能够避免这个）

目前想法是希望能在Echarts 或 zrender 里加入自定义绘图引擎 （例如https://github.com/react-native-community/react-native-svg ），不知是否现实？如果可以的话应该从哪里入手接入？

**Comment by fingera** [comment]
大佬，搞好了没
