### ISSUE TITLE
变换容器尺寸后图表实例的resize可不可以不手动调用，像highcharts一样

### ISSUE THREAD

**Issue by ghost** [apache/echarts#7730]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
改进方法：默认监听容器尺寸变化，改变时调用 resize。除此之外，需提供一个额外的配置项取消自动 resize。
```js
chart = echarts.init(dom, null, {
    autoResize: false
});
```

**Comment by 100pah** [comment]
是否可以参考 <https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js>

**Comment by Justineo** [comment]
F.Y.I. 我在 [vue-echarts](https://github.com/ecomfe/vue-echarts/blob/d784d8399551411f11ce5ce4f9dbce633a728687/src/components/ECharts.vue#L163-L177) 里是用自己封装的一个 [resize-detector](https://github.com/Justineo/resize-detector/) 实现的。
