### ISSUE TITLE
dataset  当X轴数据有重复时，重复的X轴会合并

### ISSUE THREAD

**Issue by sunyui** [apache/echarts#7745]
dataset 数据如下：
```js
dataset: {
            dimensions: ['product', 'Matcha Latte', 'Milk Tea', 'Cheese Cocoa'],
            source: [
                ['2013', 41.1, 30.4, 65.1],
                ['2013', 86.5, 92.1, 85.7],
                ['2016',24.1, 67.2, 79.5],
                ['2017',55.2, 67.1, 69.2]
            ]
  }
```
当我
 encode: {x: 'product', y:null} 时，
**两个 2013 会合并到一起。**

+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: macos

### Expected behaviour [期望结果]

X轴 应显示为 2013，2013，2016，2017

**Comment by cuibei** [comment]
xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]

**Comment by enzocq** [comment]
没人回答了吗

**Comment by Aoble** [comment]
来个人救救孩子吧

**Comment by zemelLeong** [comment]
可以试试这样子：

**Comment by 775146061** [comment]
> ```js
> tmp
> ```

兄弟，你这个tmp变量从哪儿来的
