### ISSUE TITLE
NodePadding & LayerPadding Option Removed in Echart version 4.0

### ISSUE THREAD

**Issue by vij1ay** [apache/echarts#7767]
In tree graph layout, nodePadding(used for giving padding between each end elements - padding of brothers), layerPadding (used for giving duisatnce between two connections - padding of layers) options are removed in latest version (4.0.2)

Is any option availbale other than this to acheive the same ?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 58
+ OS Version [操作系统类型和版本]: CentOS

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
`tree` series in 4 has been totally rewritten and options are all changed. Perhaps @deqingli can look at this problem?

**Comment by pedroviniv** [comment]
Hi. Any advance on that? I think it would be a nice feature to echarts.
