### ISSUE TITLE
echarts在设置geo且为世界地图的情况下，使用nameMap后无法针对特殊区域(regions属性无效)产生样式变更

### ISSUE THREAD

**Issue by AsceticBoy** [apache/echarts#7802]
### One-line summary [问题简述]
`echarts` 使用过程中发现在 `geo` 且 `map` 为 `world` 的情况下，使用 `nameMap` 更换英文名为中文后，无法使用 `regions ` 属性，针对特殊地区使用 `label`、`itemStyle` 等属性的设置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: Chrome63
+ OS Version [操作系统类型和版本]: macOS 15.3

### Expected behaviour [期望结果]
使用 `geo -> nameMap` 后，仍旧能对特殊区域进行样式处理，比如高亮中国区域

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{b}'
    },
    geo: [
        {
            name: '世界地图',
            type: 'map',
            map: 'world',
            roam: true,
            selectedMode : 'single',
            label:{
                normal: {
                    show:false,
                    formatter: function (params) {
                        return nameMap[params.name];
                    }
                },
                emphasis: {
                    label:{
                        show:true
                    }
                }
            },
            itemStyle:{
                areaColor: 'blue'
            },
            nameMap: {
                'China' : '中国'
            },
            regions:[{
                name: 'China',
                itemStyle:{
                    areaColor: 'red'
                },
                label:{
                    show: true
                }

            }]
        }
    ],
    series: []
}
```

### Other comments [其他信息]

使用上述 `options` 配置即可复现

**Comment by AsceticBoy** [comment]
@pissang

**Comment by hl-stone** [comment]
@AsceticBoy 参考此链接 https://github.com/apache/incubator-echarts/issues/5732

**Comment by hl-stone** [comment]
4.04版本此问题 也存在！ @AsceticBoy  你这个问题解决了吗？

**Comment by hl-stone** [comment]
这个问题这么没有人关注啊，设计使用中，很需要！

**Comment by AsceticBoy** [comment]
我后面没处理掉！！@hi-stone

**Comment by zerolzg** [comment]
我也遇到了,还有使用nameMap映射时,俄罗斯的中文名称会出现偏移,不过偏移的问题我是看https://github.com/apache/incubator-echarts/issues/5745 这个通过改源码解决了,这两个问题貌似一直没修复

**Comment by hl-stone** [comment]
@zerolzg  通过修改那个源码好使吗?我在4.04的版本基础上修改过，发现问题还是存在啊，你有修改好的源码能共享测试下吗？

**Comment by xieyezi** [comment]
解决了吗？？？？

**Comment by sjfkai** [comment]
遇到同样的问题，还有什么办法为国家标颜色吗？

**Comment by zhanglukay** [comment]
请问解决了吗

**Comment by sjfkai** [comment]
我最终用 visualMap 实现了相似的效果
