### ISSUE TITLE
Parallel Coordinates: Brushing problem

### ISSUE THREAD

**Issue by PatMartin** [apache/echarts#7805]
### One-line summary [问题简述]

Brushable selections only work on the first axis.

```
option = {
  "parallelAxis": [
    {
      dim: 0,
      name: "Name",
      type: "category",
      data: [
        "Bob",
        "Alice"
      ]
    },
    {
      dim: 1,
      name: "Pet",
      type: "category",
      data: [
        "Fido",
        "Spot",
        "Rover"
      ]
    },
    {
      dim: 2,
      name: "Species",
      type: "category",
      data: [
        "Dog",
        "Cat"
      ]
    }
  ],
  "series": {
    "type": "parallel",
    lineStyle: {
      width: 4
    },
    "data": [
      [
        "Alice",
        "Rover",
        "Dog"
      ],
      [
        "Bob",
        "Spot",
        "Cat"
      ],
            [
        "Bob",
        "Fido",
        "Dog"
      ]
    ]
  }
}
```

**Comment by seriousAA** [comment]
I just met same problem

**Comment by AndreHermanto** [comment]
I have the same problem, is there any solution to this? 

`option = {
    parallelAxis: [
        {
            dim: 0,
            name: 'Test',
            type: 'category',
            data: ['Excellent', 'Good', 'OK', 'Bad']
        },
        {
            dim: 1,
            name: 'Test',
            type: 'category',
            data: ['Excellent', 'Good', 'OK', 'Bad']
        },
        {
            dim: 2,
            name: 'Score',
            type: 'category',
            data: ['Excellent', 'Good', 'OK', 'Bad']
        },
        {
            dim: 3,
            name: 'Score',
            type: 'category',
            data: ['Excellent', 'Good', 'OK', 'Bad']
        }
    ],
    series: {
        type: 'parallel',
        lineStyle: {
            width: 4
        },
        data: [
            ['OK', 'OK', 'Excellent', 'Good'],
            ['Bad', 'Bad', 'OK', 'OK'],
            ['Bad', 'Excellent', 'OK', 'Excellent']
        ]
    }
};
`

**Comment by Akkarine** [comment]
In new versions this issue fixed.

For those, who came from [pyecharts](https://github.com/pyecharts/pyecharts) like me:

To solve this issue, you need update echats.min.js script. You can do it by redefining `CurrentConfig.ONLINE_HOST` to something fresh, like `'https://cdn.jsdelivr.net/npm/echarts@5.1.1/dist/'`
