### ISSUE TITLE
环形图 设置cursor:default, 图形上鼠标样式改成箭头，但是label上鼠标样式还是手状

### ISSUE THREAD

**Issue by stoneshu123** [apache/echarts#7811]
### One-line summary [问题简述]
环形图 设置cursor:default, 图形上鼠标样式改成箭头，但是label上鼠标样式还是手状

雷达图 cursor: default设置无效，是不支持还是bug?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by iVapor** [comment]
我参考 [Echarts 使用问题小结](https://github.com/shuangmianxiaoQ/myblog/issues/12)  里的 **修改鼠标悬浮在图形元素上时的鼠标样式** 部分 解决问题。
``` 
myChart.on('mousemove', function (params) {
        if (params.seriesIndex === 0) {
            myChart.getZr().setCursorStyle('default');
        }
    });
```
