### ISSUE TITLE
Display map from GeoJson

### ISSUE THREAD

**Issue by ghost** [apache/echarts#7856]
I' am trying to create a map (I am working with Django) which which show the border of Hungary. I have download the border of Hungary and the format is [GeoJson](https://github.com/integralvision/geo-data-hungary/blob/master/GeoJSON/l10-country/1-magyarorszag.geojson).  I created the script based on the Echart [docs](https://ecomfe.github.io/echarts-doc/public/en/option.html#geo) but the the map didn't appear. I attach my script and html. 

**My html:**
 ```
 <div class="canvas-wrapper">
         <div id="station_map" style="min-width:  100px; min-height: 500px;"></div>
 </div> 
```

**My script:**

```
$.get('{% static "js/map/hungary.geojson" %}', function (hungaryJson) {
    echarts.registerMap('hungary', hungaryJson);
    var chart = echarts.init(document.getElmentById('station_map'));
    chart.setOption({
        series: [{
            type: 'map',
            map: 'hungary'
        }]
    });
});
```
The GeoJson data loaded correctly (see below) so I do not understand why do not working:
![image](https://user-images.githubusercontent.com/32642115/36905420-9d5bca92-1e33-11e8-802b-f7ecd274dbe6.png)

**Comment by cuibei** [comment]
你的HTML里的id是station_map，而你js里面使用的id却是station_chart，难道执行init时控制台没有报错误么？
The ID in your HTML is station_map, but the ID in your JS is station_chart. Does the console fail to report the error when performing the init method?

**Comment by bummm26** [comment]
Sorry it was a typo, In my script the correct ID is station_map, I just type it wrong here, the problem is still actual.

**Comment by cuibei** [comment]
Let me have a look at your geojson file.

**Comment by cuibei** [comment]
You can add my WeChat, the micro signal is abcmaopao

**Comment by bummm26** [comment]
@cuibei In my question there is a link (GeoJson) where you can find it

**Comment by cuibei** [comment]
Right enough, waiting for me to download to look at the operation. Which country are you from, please?

**Comment by bummm26** [comment]
@cuibei Hungary

**Comment by chfw** [comment]
I have downloaded the geojson file and it can be displayed:

![screen shot 2018-03-03 at 12 59 55](https://user-images.githubusercontent.com/4280312/36934513-d813239c-1ee2-11e8-97d3-13cd0a36bd3d.png)

![screen shot 2018-03-03 at 13 01 31](https://user-images.githubusercontent.com/4280312/36934518-0899ba3a-1ee3-11e8-92ca-c9151d41313b.png)

**Comment by bummm26** [comment]
You do that with my code? Thank you in advance!

**Comment by bummm26** [comment]
@chfw I attached my code, if you have time please look at my code. Thank you in advance.
[map.zip](https://github.com/ecomfe/echarts/files/1793540/map.zip)

**Comment by 100pah** [comment]
In your code
```html
<script src="jquery-1.8.3.min"></script>
```
should be 
```html
<script src="jquery-1.8.3.min.js"></script>
```

and
```js
document.getElmentById('main')
```
should be
```js
document.getElementById('main')
```

**Comment by bummm26** [comment]
@100pah The map still not drawing. What I missed? Thank you in advance!

**Comment by chfw** [comment]
I am not sure where the problem is.

![screen shot 2018-03-08 at 17 35 40](https://user-images.githubusercontent.com/4280312/37166540-3465d096-22f7-11e8-8b15-e19c013f84f7.png)
