### ISSUE TITLE
dataZoom[i]-slider.handleStyle.color is not working

### ISSUE THREAD

**Issue by akvaliya** [apache/echarts#7876]
I am using echarts version "4.0.4".

When i tried to change color of data-zoom slider handle, it's not working.

My data-zoom array is like below.

```
DataZoomArray = [
    { type: 'inside', start: 50, end: 100, yAxisIndex: 0 },
    {
        show: true, filterMode: 'empty',
        yAxisIndex: 0,
        handleStyle: {
            color: '#fff'
        }
    }
];
```
I think it's bug. every other properties of handleStyle is working fine.

**Comment by ILovePing** [comment]
echarts version 4.4.0 
same problem

**Comment by pissang** [comment]
Hi @ILovePing @akvaliya , can you provide a full option for us to reproduce.

I tested it on https://echarts.apache.org/examples/en/editor.html?c=area-simple and it works fine

**Comment by jaycethanks** [comment]
and the property : dataZoom[i]-slider.borderColor dosen't work the same . 
it works fine online, but doesn't work in local codes.

**Comment by zhanghuanchong** [comment]
I tried with `handleColor` which works with v4.6.0.

```
    dataZoom: [
          {
            type: 'inside',
            realtime: true,
            rangeMode: 'value',
            startValue: 1,
            endValue: 10
          },
          {
            show: true,
            realtime: true,
            rangeMode: 'value',
            startValue: 1,
            endValue: 10,
            fillerColor: '#ff0000',
            handleColor: '#990000'
          }
        ]
```

**Comment by yy-richard** [comment]
echarts version 5.3.3
same problem

**Comment by yy-richard** [comment]
like this
