### ISSUE TITLE
渲染树形图时,如果设置了charts.on('dblclick',[function])后,双击操作在特定场景下难以触发

### ISSUE THREAD

**Issue by doopcl** [apache/echarts#7941]
### One-line summary [问题简述]
复现条件
1,渲染数据为多级的tree图
2,给echarts对象绑定dblclick 触发事件

之后当双击某个带有子节点的节点时,节点因为展开动画而偏移,难以触发双击的事件响应,除非双击速度很快

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  4.0.2
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]:  Mac OS

### Expected behaviour [期望结果]

双击时不要触发叶子节点的展开和收起操作

### ECharts option [ECharts配置项]

```javascript
option = {
series: [
                        {
                            type: 'tree',
                            data: [],
                            symbol: 'rect',
                            symbolSize: [50, 14],
                            top: 0,
                            bottom: 0,
                            itemStyle: {
                                color: '#c4d9f5',
                                borderColor: '#cccccc',
                                borderWidth: 1
                            },
                            label: {
                                fontSize: 10
                            },
                            expandAndCollapse: true,
                            initialTreeDepth: 1
                        }
                    ]
}

```

### Other comments [其他信息]

http://jsrun.net/FkZKp

请双击该重现案例中的sub-1 节点,会发现其子节点会展开和收起,点击其子节点(sub-1-1 没有子节点)可正常触发dblclick

**Comment by doopcl** [comment]
@100pah  
我个人的想法是:
1,双击节点应该可以命中dblclick的自定义事件上,目前在我的demo中基本难以操作到
2,单击的话因为存在组件自有事件和自定义事件两种,那么流程上可以理解为,当用户自定义了click事件时,可以在自定义事件中自行控制是否继续走到节点 展开/收起 操作,如果用户未定义,则可以默认走到节点展开/收起 操作.
不知道能否可以实现?

**Comment by 100pah** [comment]
1, 这点看起来是有点问题，应考虑。
2, 默认的展开/收起 操作，是可以全局关闭的，如果全局关闭后，再监听 onclick 事件，则可以自己定义：做展开收起，还是做什么别的事情。

**Comment by gitXiaoQing** [comment]
@100pah ，您好，“默认的展开/收起 操作，是可以全局关闭的”，在‘配置项’里没有找到关于`type: 'tree'`的关闭click事件，请问是哪个属性或方法？

**Comment by pimkle** [comment]
> @100pah ，您好，“默认的展开/收起 操作，是可以全局关闭的”，在‘配置项’里没有找到关于`type: 'tree'`的关闭click事件，请问是哪个属性或方法？

[文档](http://echarts.baidu.com/option.html#series-tree.expandAndCollapse)

**Comment by pimkle** [comment]
可以把点击事件从 `dblclick` 转为 鼠标右键的 `contextmenu`, contextmenu 的回调里面 ``` params.event.event.preventDefault() ``` 会屏蔽默认右键操作。  
一定要用 dblclick 的话，`series` 儿子里面 加个 `animationDelayUpdate` 的属性，延迟 300，这样用户就更容易点击得到。
