### ISSUE TITLE
Line charts with dataZoom draw vertical line after a value of 0 on refresh when zooming

### ISSUE THREAD

**Issue by BigPino67** [apache/echarts#7961]
### One-line summary [问题简述]

Line charts with dataZoom draw vertical line on refresh when zooming with a value of 0 before the next value. If i replace the zoom, the chart is drawn perfectly. It's only on refresh.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: IE 11
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]
No vertical line

### Other comments [其他信息]
Before refresh :
![chart_ok2](https://user-images.githubusercontent.com/15323780/37529209-70345538-292e-11e8-9baf-a609aceb66cb.png)

After refresh :
![chart_vert](https://user-images.githubusercontent.com/15323780/37529036-fc96217e-292d-11e8-85f5-600d2654d5d3.png)

After replacing the zoom :
![chart_ok2](https://user-images.githubusercontent.com/15323780/37529226-7d9635b6-292e-11e8-8616-bc8fab15b8a9.png)

**Comment by 100pah** [comment]
May I have the `echarts option` to reproduce the issue?

**Comment by txs1992** [comment]
@100pah
