### ISSUE TITLE
bar3D设置坐标轴轴线不显示，报错‘Cannot read property '0' of null’

### ISSUE THREAD

**Issue by Lacorda** [apache/echarts#7986]
### One-line summary [问题简述]

bar3D设置坐标轴轴线不显示，报错‘Cannot read property '0' of null’

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  4.0.4
+ ECharts-gl version [ECharts 版本]:  1.1.0
+ Browser version [浏览器类型和版本]: chrome 65.0.3325.162（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: OS 10.12.5

设置xAxis.axisLine.show = false。报错
直接在官方示例里预演，同一个位置报同样的错误：

echarts-gl.js:37490 Uncaught TypeError: Cannot read property '0' of null
    at i.<anonymous> (echarts-gl.js:37490)
    at Array.forEach (<anonymous>)
    at i._updateAxisLabelAlign (echarts-gl.js:37486)
    at i._updateAxisLinePosition (echarts-gl.js:37468)
    at i._onCameraChange (echarts-gl.js:37370)
    at sub.trigger (echarts-gl.js:19628)
    at sub._update (echarts-gl.js:17181)
    at sw.trigger (echarts.min.js?_v_=1519819816100:1)
    at sw._update (echarts.min.js?_v_=1519819816100:1)
    at t (echarts.min.js?_v_=1519819816100:1)

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {},
    visualMap: {
        max: 20,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    xAxis3D: {
        type: 'category',
        data: hours,
        axisLine: {
          show: false
        }
    },
    yAxis3D: {
        type: 'category',
        data: days
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        boxWidth: 200,
        boxDepth: 80,
        viewControl: {
            // projection: 'orthographic'
        },
        light: {
            main: {
                intensity: 1.2,
                shadow: true
            },
            ambient: {
                intensity: 0.3
            }
        }
    },
    series: [{
        type: 'bar3D',
        data: data.map(function (item) {
            return {
                value: [item[1], item[0], item[2]],
            }
        }),
        shading: 'lambert',

        label: {
            textStyle: {
                fontSize: 16,
                borderWidth: 1
            }
        },

        emphasis: {
            label: {
                textStyle: {
                    fontSize: 20,
                    color: '#900'
                }
            },
            itemStyle: {
                color: '#900'
            }
        }
    }]
}

```

**Comment by Zegendary** [comment]
@Lacorda 解决了吗? 我也碰到同样问题

**Comment by fndbs1314** [comment]
@Lacorda  请问这个问题解决了吗?我碰到了同样问题

**Comment by fndbs1314** [comment]
@Lacorda @Zegendary 可以将轴线设置为透明
