### ISSUE TITLE
graph 中 如何给 label 添加点击事件？

### ISSUE THREAD

**Issue by Yangjia23** [apache/echarts#7994]
### One-line summary [问题简述]
在关系图graph 中，item 已经实现了点击事件，能否给label也添加点击事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
}

```

### Other comments [其他信息]

线上实例地址：  http://gallery.echartsjs.com/editor.html?c=xSJMz-slcz&comment=0

**Comment by 100pah** [comment]
这个例子，可以使用 series.type: 'tree'。

**Comment by howieliu** [comment]
我们公司也有这个需求，能否label支持html标签，或者，支持点击事件？

**Comment by deqingli** [comment]
#11497

**Comment by snowmoon2** [comment]
把echarts升级到5.0以上就行了，记得用import * as 你原来的变量名 from 'echarts'来导入
