### ISSUE TITLE
Using 'time' type with time_stamp format

### ISSUE THREAD

**Issue by ghost** [apache/echarts#7997]
I have xAxis data which contain the following format:

`data: ['2018-03-21 00:00', '2018-03-21 00:10', '2018-03-21 00:20', '2018-03-21 00:30', '2018-03-21 00:40', ..]`

When I am trying to use 'time' type to use the possibility this type (e.g: add 1 hour interval), I got an empty chart. I know that when I use 'category' type the chart appear but when is use this type I can't add correct interval. 

**EDITED:**

I tried to convert date format like this:
```
date=[];
for (var i in data){

         date.push(new Date(data[i]));
        }
```
I got a format like this:

`Thu Mar 22 2018 03:50:00 GMT+0100 (CET)`

Unfortunately the chart still do not working.

Thank you for you answers in advance!

**Comment by 100pah** [comment]
If `xAxis.type` is set as `'time'`, the time data should be put in `series.data` or `dataset.source`.

For example: 
```js
option: {
    xAxis: {type: 'time'},
    yAxis: {},
    series: {
        ...,
        data: [
            ['2018-03-21 00:00', 1213232],
            ['2018-03-21 00:10', 3232323],
            ...
        ]
    }
}
```
