### ISSUE TITLE
Tree图重写鼠标点击事件

### ISSUE THREAD

**Issue by leftluoyi** [apache/echarts#8004]
用的是echarts 4，具体来是reacts-for-echarts。

目前有一个Tree图（不是treemap），点不多。想要在单击的时候，显示选中的节点。但是tree图本身的单击事件是展开或者收回子树。想问一下如何屏蔽原来的鼠标点击事件而采用自己的事件呢？

现在暂时的方法是在点击了之后使用setOption让图刷新一次，但是这样图会抖一下。

多谢～

**Comment by ColinCLL** [comment]
tree.setOption({...})
tree.on(click(), function(){})

**Comment by 100pah** [comment]
可关闭：<https://ecomfe.github.io/echarts-doc/public/en/option.html#series-tree.expandAndCollapse>

**Comment by wwenj** [comment]
是需要点击折叠这一功能的，但单击也想显示选中节点，所以能不能双击时展开折叠树？
