### ISSUE TITLE
怎样使类型为line图表渲染从从右向左展开（x轴坐标倒置，看到的问题）？

### ISSUE THREAD

**Issue by JsonShare** [apache/echarts#8007]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.5.2
+ Browser version [浏览器类型和版本]:  chrome 60.0
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

目前的问题：
bar型的图表 是可以 从右向左 渲染展开的
但是： line型图表从右向左渲染 是不能的？

### ECharts option [ECharts配置项]

```javascript
var xAxisData = [];
var data1 = [];
var data2 = [];
for (var i = 0; i < 100; i++) {
    xAxisData.push('类目' + i);
    data1.push((Math.sin(i / 5) * (i / 5 -10) + i / 6) * 5);
    data2.push((Math.cos(i / 5) * (i / 5 -10) + i / 6) * 5);
}

option = {
    title: {
        text: '柱状图动画延迟'
    },
    legend: {
        data: ['bar', 'bar2'],
        align: 'left'
    },
    toolbox: {
        // y: 'bottom',
        feature: {
            magicType: {
                type: ['stack', 'tiled']
            },
            dataView: {},
            saveAsImage: {
                pixelRatio: 2
            }
        }
    },
    tooltip: {},
    xAxis: {
        data: xAxisData,
                inverse : true,
        silent: false,
        splitLine: {
            show: false
        }
    },
    yAxis: {
    },
    series: [{
        name: 'line',
        type: 'line',
        data: data1,
        animationDelay: function (idx) {
            return idx * 10;
        }
    }, {
        name: 'line',
        type: 'line',
        data: data2,
        animationDelay: function (idx) {
            return idx * 10 + 100;
        }
    }],
    animationEasing: 'elasticOut',
    animationDelayUpdate: function (idx) {
        return idx * 5;
    }
};

```

**Comment by JsonShare** [comment]
@leeight @cnberg @xvaara @firede @chriswong 
你好，可以实现吗？  先谢谢了

**Comment by KoalaHui** [comment]
xAxis: [
                {
                    type: 'category',
                    axisTick: { show: false },
                    data: data.time,
                    scale: true,
                    boundaryGap: true,
                    //inverse: true,从右往左画线
                    axisLabel: {
                        show: true,
                        margin: 8,
                        color: '#000'
                    },
                    axisLine: {
                        show: false,
                        onZero: true,
                        lineStyle: {
                            color: borderColor,
                            width: 1
                        }
                    },
