### ISSUE TITLE
Type log axis cant control axisTick interval

### ISSUE THREAD

**Issue by mecha9** [apache/echarts#8014]
### One-line summary [问题简述]
Log axis sets ticks equal distance apart instead of equal numeric change and this cannot be over-ridden.

### Explanation
For Candlestick chart, log axis is better, but none of these properties:
- splitNumber
- interval
- logBase
- axisTick.interval

Can make the y-axis have set intervals, e.g. 5 - 10 - 15- 20 or control number of intervals. Echarts makes the axisTicks force to be equal distance apart so they go 1 - 10 - 100 axisTicks.
http://echarts.baidu.com/examples/editor.html?c=line-log

Can log chart have y-axis like log chart on right in this picture?
https://i.investopedia.com/inv/articles/site/logvslinear.gif

The axis tick distance is lowered instead of changing the numeric interval.

I see the interval property maybe can do this, but I cant get it to work.
https://ecomfe.github.io/echarts-doc/public/en/option.html#yAxis.interval

### Version & Environment [版本及环境]
Latest version

**Comment by BugZappr** [comment]
+1 on this.  I'd like to use a log Y axis on your candlestick example.  However, if I add to the YAxis section, so that I have:

>               yAxis: [
>            {
>                scale: true,
>                splitArea: {
>                    show: true
>                 },
>                 type: "log",
>                 min: 15000,
>                 max: 25000,
>                 interval: 2000
>            },

to the first YAxis section, I get just two axis labels: 15000 and 25000.  In this case, I believe it should be five.

**Comment by nsarka** [comment]
Has anyone solved this yet? I need something similar--my log axis won't update with new values no matter what setting I use for the interval. I'm using a custom chart if that makes any difference. Thanks

**Comment by kristian2x** [comment]
+1 We need this too (but for regular line charts)

**Comment by Proxi01** [comment]
Up :arrow_up: 
Faced with the same issue

**Comment by mmastand** [comment]
Same issue, any updates?

**Comment by aleixtusetbadia** [comment]
+1

**Comment by anke1460** [comment]
interval在对数轴下设置不起作用啊
