### ISSUE TITLE
echart yAxis and xAxis label cutout

### ISSUE THREAD

**Issue by t0n1zz** [apache/echarts#8018]
hi, so i am using echart in my bootstrap project and i use this styling to control the size of the chart
```
<style scoped>
	.echarts{
		width: 100vw;
		min-width: 50vw;
		height: 50vh;
	}
</style>
```

and i find there is some anoying problem that happen if only i have long yAxis or xAxis label like this
![screen shot 2018-03-25 at 22 54 47](https://user-images.githubusercontent.com/6964548/37877067-97a4c05a-307f-11e8-88f8-cb046f091f95.png)

so how to fixed it? to make sure there is no cutout in yAxis and xAxis label?

**Comment by 100pah** [comment]
Try <http://echarts.baidu.com/option.html#grid.right> please ~

**Comment by t0n1zz** [comment]
well i tried it but it just have a weirds issue, i make grid left and right 10% and it just feels not right comparing with chartjs it have a responsive parameters that can automatically create grid size according to the container.

**Comment by knadt** [comment]
Any update?

**Comment by lakshmiSachidanandam** [comment]
Am alternate option is to adjust with grid margins and set a fixed width for labels while they can be represented with ellipsis for longer ones.

**Comment by k1ngbanana** [comment]
> Am alternate option is to adjust with grid margins and set a fixed width for labels while they can be represented with ellipsis for longer ones.

https://stackoverflow.com/questions/38693662/label-cant-display-when-echarts-labels-length-is-too-long/60787785#60787785

i have try this links method, and it helps me.
the solution in the link is set property below
**grid: { containLabel: true }**

hopes this also helps u
