### ISSUE TITLE
数据动态更新动画不连续的问题

### ISSUE THREAD

**Issue by chillyond** [apache/echarts#8032]
### One-line summary [问题简述]
http://www.echartsjs.com/gallery/editor.html?c=doc-example/tutorial-dynamic-data
这个官方例子在数据更新时，左边的动画不是连续的

### Expected behaviour [期望结果]
希望可以像右边一样保持连续的动画

**Comment by PeachT** [comment]
我也需要解决这个问题，你有找到方法吗？

**Comment by PeachT** [comment]
https://stackblitz.com/edit/angular-echarts0-line
这样子的效果还可以
