### ISSUE TITLE
关于legend的formatter的问题

### ISSUE THREAD

**Issue by qmy777** [apache/echarts#806]
我想请教下，在pie中，使用legend的formatter属性如何获取pie中的数据呢？{name}是系列名，那不知道可否使用{value}获取到系列中的数据呢？？如果不行，那如何才可以获取到相关的值呢？？

谢谢各位啦

**Comment by chaserstrong** [comment]
@kener   
请问，也可以通过pie的label formatter时记下来后更新legend。 这句话具体用代码怎么实现呢？

**Comment by ZiSeFeng** [comment]
`label: { //标签的位置
                normal: {
                    show: false,
                    position: 'inside', //标签的位置
                    textStyle: {
                        color: '#fff',
                    },
                    formatter:function(params){
                        return params.value + '人'
                    }
                },
                emphasis: {
                    show: true,
                    textStyle: {
                        fontWeight: 'bold'
                    }
                }
            },`
