### ISSUE TITLE
漏洞图填充不规则的数据两边不是一条斜的直线

### ISSUE THREAD

**Issue by liminjun** [apache/echarts#807]
通过 http://echarts.baidu.com/doc/example/funnel.html 修改数据，修改如下：
data:[
                {value:60, name:'访问'},
                {value:40, name:'咨询'},
                {value:20, name:'订单'},
                {value:100, name:'点击'},
                {value:150, name:'展现'}
            ]
![image](https://cloud.githubusercontent.com/assets/966009/4730707/01f2b24e-599e-11e4-938b-c7f53381aeef.png)

得到的如上图的漏斗图。开发者期望漏斗图，数据是不限定的，可以增加漏斗层的高度，但是宽度调整之后，需要保持左右还是一条斜的直线。现在的数据显示出来的漏斗图，可能不符合用户的要求。或者有其他的地方需要配置。

**Comment by hecomzhangzhiguo** [comment]
这个到现在也不支持吗？我们的阶段是固定的流程的，只能通过高度来显示多少。

**Comment by tiannanyexian** [comment]
2023还不支持吗
