### ISSUE TITLE
tooltip的fomatter模板字符串

### ISSUE THREAD

**Issue by zhangjiaqing** [apache/echarts#8073]
### One-line summary [问题简述]

当使用dataset设置数据时，tooltip的formatter用的时候{c}不能正常显示
显示成 数据拼接了，
应该单独显示数据值的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: chrrome
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]

正常显示数据值

### ECharts option [ECharts配置项]

```javascript
option = {
    legend: {},
    tooltip: {
         formatter: '{b} <br/> {a}: {c}'
    },
    dataset: {
        source: [
            ['product', '2012', '2013', '2014', '2015'],
            ['Matcha Latte', 41.1, 30.4, 65.1, 53.3],
            ['Milk Tea', 86.5, 92.1, 85.7, 83.1],
            ['Cheese Cocoa', 24.1, 67.2, 79.5, 86.4]
        ]
    },
    xAxis: [
        {type: 'category', gridIndex: 0},
        {type: 'category', gridIndex: 1}
    ],
    yAxis: [
        {gridIndex: 0},
        {gridIndex: 1}
    ],
    grid: [
        {bottom: '55%'},
        {top: '55%'}
    ],
    series: [
        // These series are in the first grid.
        {type: 'bar', seriesLayoutBy: 'row'},
        {type: 'bar', seriesLayoutBy: 'row'},
        {type: 'bar', seriesLayoutBy: 'row'},
        // These series are in the second grid.
        {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
        {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
        {type: 'bar', xAxisIndex: 1, yAxisIndex: 1},
        {type: 'bar', xAxisIndex: 1, yAxisIndex: 1}
    ]
};

```

**Comment by ZXand618** [comment]
option = {
    legend: {},
    tooltip: {
    },
    dataset: {
        source: [
            ['product', '2012', '2013', '2014', '2015'],
            ['Matcha Latte', 41.1, 30.4, 65.1, 53.3],
            ['Milk Tea', 86.5, 92.1, 85.7, 83.1],
            ['Cheese Cocoa', 24.1, 67.2, 79.5, 86.4]
        ]
    },
    xAxis: [{
            type: 'category',
            gridIndex: 0,
            tooltip: {
                formatter: '{b} <br/> {a}: {c}'
            }
        },
        {
            type: 'category',
            gridIndex: 1,
            tooltip: {
                formatter: '{b} <br/> {a}: {c}'
            }
        }
    ],
    yAxis: [{
            gridIndex: 0
        },
        {
            gridIndex: 1
        }
    ],
    grid: [{
            bottom: '55%'
        },
        {
            top: '55%'
        }
    ],
    series: [
        // These series are in the first grid.
        {
            type: 'bar',
            seriesLayoutBy: 'row'
        },
        {
            type: 'bar',
            seriesLayoutBy: 'row'
        },
        {
            type: 'bar',
            seriesLayoutBy: 'row'
        },
        // These series are in the second grid.
        {
            type: 'bar',
            xAxisIndex: 1,
            yAxisIndex: 1
        },
        {
            type: 'bar',
            xAxisIndex: 1,
            yAxisIndex: 1
        },
        {
            type: 'bar',
            xAxisIndex: 1,
            yAxisIndex: 1
        },
        {
            type: 'bar',
            xAxisIndex: 1,
            yAxisIndex: 1
        }
    ]
};

**Comment by NeoLSN** [comment]
我也遇到了一樣的情況，目前只能自掛function來解決這問題。

**Comment by CoderPoet** [comment]
是的，dataset模式确实有这个问题。并且其中的dataIndex也不是正确的数组下标，只能自己维护一个数组下标来提取到正确的数据了。

**Comment by CoderPoet** [comment]
![image](https://user-images.githubusercontent.com/19374680/48252112-c9d3b400-e43e-11e8-962e-d63fe9019373.png)
