### ISSUE TITLE
axisLabel 较长时，旋转后显示不完整

### ISSUE THREAD

**Issue by buwoyouwo** [apache/echarts#808]
如图，折线图中，axisLabel较长，旋转90°后由于图表高度有限，label显示不完整
![31a17201-c14d-4384-8d05-77c40d7f4691](https://cloud.githubusercontent.com/assets/8155966/4730871/a89228a2-59a1-11e4-9dae-b05ee6c7b2cb.png)

**Comment by IEfucker** [comment]
我遇到了相同的问题，查到这个issue，14年的，给的建议实在是临时性。@kener 
![echarts](https://cloud.githubusercontent.com/assets/3446876/18782432/11058104-81b9-11e6-9bf9-5c278d134f53.png)
总会有label很长的情况。

如果截取label字符长度，tip中显示的label也是截取过的，能单独配置axisLabel和tip中的标题吗

**Comment by 100pah** [comment]
1. 旋转仍然是一种比较通用的长label解决方案。

2. axisLabel 和 tooltip 做不同显示，也是可以的。formatter 中可以指定 axisLabel 和 tooltip 中显示什么。

**Comment by IEfucker** [comment]
@100pah 感谢回复，
1.这个方案确实是我想尝试解决的，我发的图片很明显，旋转后label间的空间是够的，但label的区域已经超出canvas的范围，被裁切了，通过设定axisLabel的margin值也没有效果；
2.tooltip的formatter我尝试过，但似乎只能改title下面的内容，tip的title默认还是x label的值，这个怎么改

**Comment by IEfucker** [comment]
第二点我看到文档了，但似乎是拼tip内容的字符串，tip的title默认还是和label相同，现在没办法开电脑，之后我再确认下。

第一点没错，这样设计是为了放下更多内容，但我的问题是什么呢，图片很清楚，当我旋转后，文字区域超过画布canvas了，查了关于padding，margin的文档美没找到解决方案。这个显示效果和highcharts比确实不好。谢谢

发自我的 iPhone

**Comment by 100pah** [comment]
关于第一点：tooltip 通过 formatter 能把里面内容做任意修改的。

关于第二点：把 <http://echarts.baidu.com/option.html#grid.bottom> 留出更多 label 空间，是否能解决您的问题？

**Comment by IEfucker** [comment]
@100pah 
formatter我再研究下，grid.bottom生效了，还是要说这api难用
