### ISSUE TITLE
折线图 label(比如数字) 如何自动避免被折现遮挡

### ISSUE THREAD

**Issue by komagic** [apache/echarts#8081]
### One-line summary [问题简述]

折线图 label(比如数字) 如何自动避免被折现遮挡

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

当 用echarts 出折线图的时候，折点上的label位置是由我们事先选定的，但是如果需要大量自动出图时候（例如出全国多个省份温度变化图），label的位置就很有必要自动规避折线，否则label会被折线覆盖（或者label覆盖折线）。

**Comment by deqingli** [comment]
please provide more detailed msg, such as a demo, for us to debug.
