### ISSUE TITLE
直角系，x轴的刻度长度能否强制限制？问题描述：需要在x轴上显示30个刻度，1.2.3.4.... ....30这样。但是现在只有1，2，那么怎么才能让1，2只占用一定的刻度，后面的没有的留空，就是3到30的位置留空，不需要均匀分布。

### ISSUE THREAD

**Issue by ranzeng** [apache/echarts#8092]
直角系，x轴的刻度长度能否强制限制？问题描述：需要在x轴上显示30个刻度，1.2.3.4.... ....30这样。但是现在只有1，2，那么怎么才能让1，2只占用一定的刻度，后面的没有的留空，就是3到30的位置留空，不需要均匀分布。

**Comment by wu0792** [comment]
@ranzeng 问题解决了吗，我也遇到这个问题
