### ISSUE TITLE
markpoint在做offset之后无法自适应边界

### ISSUE THREAD

**Issue by mymickey** [apache/echarts#8108]
### One-line summary [问题简述]
原有的markpoint在蜡烛图中很容易和蜡烛图相互叠加
![image](https://user-images.githubusercontent.com/572102/38453139-80ed0b70-3a83-11e8-93dc-13d1c5267427.png)

我做了偏移之后，无法自适应边界（如：指针可以左右自适应指向目标），求解决方案

![image](https://user-images.githubusercontent.com/572102/38453158-bc980dd2-3a83-11e8-8c42-e897d1166ac5.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mymickey** [comment]
@pissang  @100pah

**Comment by dvago** [comment]
I've got the same problem:

![Screenshot 2020-04-14 at 10 12 28](https://user-images.githubusercontent.com/5074033/79207632-d7157f00-7e38-11ea-88ac-65f973f45c1b.png)

Any solution on this issue after 2 years?
