### ISSUE TITLE
markpoint的symbol支持回调函数吗

### ISSUE THREAD

**Issue by ymli1981** [apache/echarts#8140]
一个图表的标注能否设置多个图片？
比如有的是图片A，有的是图片B、
说明文档里没写支持回调函数，不知如何实现？

**Comment by pissang** [comment]
可以设置 data 每个项的 symbol

**Comment by ymli1981** [comment]
怎么设置？能否给个例子

**Comment by pissang** [comment]
data: [ { xxxx, symbol: 'circle' }, { xxxx, symbol: 'rect' } ]

**Comment by ymli1981** [comment]
多谢！

**Comment by wowzhu** [comment]
> ```js
> 数据： [{xxxx，符号： ' circle ' }，{xxxx，符号： ' rect ' }]
> ```

循环出的数据怎样单独设置呢 
![image](https://user-images.githubusercontent.com/22386833/55316587-52f88f80-54a1-11e9-9995-ce00cc56cefb.png)
option.series[8].symbol = 'circle';  我这样试了下  不是单独改变一个  而是改变了几个
