### ISSUE TITLE
输入“2018-04-13 08:52:12.197587”，echarts画出的时间是08：55

### ISSUE THREAD

**Issue by MI-Class** [apache/echarts#8148]
### One-line summary [问题简述]
这种时间格式  “2018-04-13 08:52:12.197587”  在Y轴type为time 中显示的时间为2018-04-13 08：55

### Version & Environment [版本及环境]      echarts 源代码
+ ECharts version [ECharts 版本]:                   4.04
+ Browser version [浏览器类型和版本]:          火狐，谷歌
+ OS Version [操作系统类型和版本]:
window10 1607

### Expected behaviour [期望结果]
我在文档中看到  2018-04-13 08:52:12.197587   这种的时间格式并不被支持，文档中支持的时间格式为“2018-04-13 08:52:12.197”，希望能够支持毫秒有6未的，毕竟.net中使用DateTime.Now获取的就是这种时间格式，如果不能支持这种时间格式就直接报错不能绘图

### ECharts option [ECharts配置项]

```javascript
var data=[["2018-04-13 08:12:08.435691","21.88"]
,["2018-04-13 08:52:12.197587","22.19"]];
option = {
 title: {
                    text: '室内温度'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        animation: false
                    }
                },
                xAxis: {
                    type: 'time',
                    splitLine: {
                        show: false
                    }
                },
                yAxis: {
                    type: 'value',
                    min:20,
                    boundaryGap: [0, '100%'],
                    splitLine: {
                        show: false
                    }
                },
                series: [{
                    name: '温度',
                    type: 'line',
                    showSymbol: false,
                    hoverAnimation: false,
                    data: data
                }]
}

```

**Comment by Ovilia** [comment]
如果有这个需求的话，建议将坐标轴类型设为 category。因为即使输入六位时间，在内部处理的过程中（Date 对象）会丢失这个信息，还是会变成三位，所以没法支持六位。

**Comment by MI-Class** [comment]
其实这个重要的不是能不能显示出六位的，从输出图表的数值上来看，echarts是将小数点后六位除1000，得到的几百秒，然后又转换成了分钟，加到了分钟上，所以才会相差个几分钟，这个应该是属于echarts内部逻辑有问题，其实我对于是否支持六位并不关心，因为那种精度没什么用，只是，echarts应当采取报错，不支持六位，或者改下内部逻辑，为什么微秒的六位会影响到秒，分，最重要的是还给画出来了

**Comment by TeemoRZ** [comment]
我也遇到同样问题，时间轴上不能显示毫秒；把xAxis 的Type 设置为 category，无法分辨数据的分布；求官方支持毫秒的 Type ：time
