### ISSUE TITLE
dataset 可以为每个数据指定样式

### ISSUE THREAD

**Issue by sep8** [apache/echarts#8151]
### One-line summary [问题简述]
dataset 的单个数据不支持支持指定样式， 尤其是饼图中指定dataset作为数据的时候，我有一个需求是为每一个扇面指定固定的颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:v4.0.4
+ Browser version [浏览器类型和版本]:chrome 65
+ OS Version [操作系统类型和版本]:win 10

### Expected behaviour [期望结果]
dataset 的每个数据可以支持指定样式

### ECharts option [ECharts配置项]
```javascript
option = {
    legend: {},
    tooltip: {},
    dataset: {
        source: [
            ['score', 'amount', 'product'],
            [{
                value: 89.3,
                itemStyle: {
                    color: 'red'
                }
            }, 58212, 'Matcha Latte'],
            [57.1, 78254, 'Milk Tea'],
            [74.4, 41032, 'Cheese Cocoa'],
            [50.1, 12755, 'Cheese Brownie'],
            [89.7, 20145, 'Matcha Cocoa'],
            [68.1, 79146, 'Tea'],
            [19.6, 91852, 'Orange Juice'],
            [10.6, 101852, 'Lemon Juice'],
            [32.7, 20112, 'Walnut Brownie']

        ]
    },
    series: [{
        type: 'pie',
        encode: {
            value: 'score',
            // seriesName:0,
            // itemId: 0,
            itemName: 2
        }
    }]
}
```
### Other comments [其他信息]
http://gallery.echartsjs.com/editor.html?c=xrkcSXiasG&v=1

**Comment by Mignon-han** [comment]
我还有一个想法，如果想数据和样式分离的话，可不可以在dataset里面加一种新的 `dimension`类型, 比如说名为`style`,可以用来把样式映射到series的每个数据中。
```
option = {
  dataset: {
    dimensions: ['score', 'amount', 'product', {name: 'scoreStyle',type: 'style'}],
    source: [
      [89.3, 58212, 'Matcha Latte', {color: 'red' }],
      [57.1, 78254, 'Milk Tea', {color: 'blue' }],
      [74.4, 41032, 'Cheese Cocoa', {color: 'green' }]
      ...
    ]
  },
  series: [{
    type: 'bar',
    encode: {
      x: 'product',
      y: 'score',
      style: 'scoreStyle'
    }
  }]
}
```
因为`series.data[i]` 是可以是对象，并且可以为每个`data[i]`指定样式。
我们很想把产品的eCharts版本升级到4.x, 但是为每一个data[i] ，指定样式的功能实现不了的话，就没办法使用dataset这个强大的功能,也就没必要着急升级了。

**Comment by pissang** [comment]
dataset 原先的设计就是为了数据和样式分离，所以不会考虑在 dataset 里去做一些样式的设置。

不过确实有不少需求会要设置某个数据的样式用来突出这个数据，如果是使用颜色透明度等方式编码的话，建议使用 visualMap 组件。

**Comment by Mignon-han** [comment]
@pissang 你好，按照您说的方法，我去试了一下。我想要为柱状图的每个柱子按照不同的category指定样式。但是配置的都有问题，麻烦帮忙看一下，怎么配置能达到我的目的。
下面是我的例子：http://gallery.echartsjs.com/editor.html?c=xSkA-8JX3z&v=1
```
var option = {
    dataset: {
        source: [
            ['score', 'amount', 'product'],
            [89.3, 58212, 'Matcha'],
            [57.1, 78254, 'Milk'],
            [74.4, 41032, 'Cocoa'],
            [50.1, 12755, 'Brownie'],
            [89.7, 20145, 'HCocoa']
        ]
    },
    xAxis: {},
    yAxis: {
        type: 'category'
    },
    visualMap: [{
        type: 'piecewise',
        dimension: 2,
        categories: ['Matcha', 'Milk', 'Cocoa', 'Brownie', 'HCocoa'],
        color: ['red', '#bf444c', '#d88273', '#f6efa6', 'blue']
    }],
    series: [{
        type: 'bar',
        encode: {
            x: 'score',
            y: 'product'
        }
    }]
};
```

**Comment by WeiRu1016** [comment]
想问一下，dataset如何根据没有encode的字段为每个数据指定样式

**Comment by drumslave-git** [comment]
Hi.
If anyone needs it, I found a workaround.

My dataset looks like this:

```
{source: [
  {value: 15, name: 'test', color: '#FF00FF'},
  ...
]}
```

Before chart init you need to add such code

```
import echarts from 'echarts';

const VISUAL_PRIORITY = echarts.PRIORITY.VISUAL.COMPONENT;

echarts.registerVisual(VISUAL_PRIORITY, {
    createOnAllSeries: true,
    reset: function (seriesModel) {
        const data = seriesModel.getData();

        data.each(function (idx) {
            const itemModel = data.getItemModel(idx);
            let color = itemModel.get('itemStyle.color');
            if(!color){ // if there is no color set in normal way
                color = itemModel.get('color');

                if(color && typeof color === 'string'){ // if there is no such field in dataset, it can return array (default color palette)
                    data.setItemVisual(idx, 'color', color);
                }
            }
        });
    }
});
```

After this you can init charts as always. Using such approach you can do any calculations based on your dataset item data to determine color.

Don't know if it is good, but works for me and I got no other choice.

**Comment by greedy747** [comment]
> 我还有一个想法，如果想数据和样式分离的话，可不可以在dataset里面加一种新的 `dimension`类型, 比如说名为`style`,可以用来把样式映射到series的每个数据中。
> 
> ```
> option = {
>   dataset: {
>     dimensions: ['score', 'amount', 'product', {name: 'scoreStyle',type: 'style'}],
>     source: [
>       [89.3, 58212, 'Matcha Latte', {color: 'red' }],
>       [57.1, 78254, 'Milk Tea', {color: 'blue' }],
>       [74.4, 41032, 'Cheese Cocoa', {color: 'green' }]
>       ...
>     ]
>   },
>   series: [{
>     type: 'bar',
>     encode: {
>       x: 'product',
>       y: 'score',
>       style: 'scoreStyle'
>     }
>   }]
> }
> ```
> 
> 因为`series.data[i]` 是可以是对象，并且可以为每个`data[i]`指定样式。
> 我们很想把产品的eCharts版本升级到4.x, 但是为每一个data[i] ，指定样式的功能实现不了的话，就没办法使用dataset这个强大的功能,也就没必要着急升级了。

series里的itemStyle,label如果支持array，是不是可以解决问题？

**Comment by hanjingnuo** [comment]
echart 4.0才开始支持dataset，dataset是为了数据和样式分离，而图表个性化样式很多，而且样式一般都是根据数据项驱动的，因此目前的dataset设计没有考虑兼容data的itemStyle等，就不能做到兼容性，希望能综合考虑下，并不一定要在dataset中实现，建议兼容data之前的设计，新建一个dataStyle属性也可以，希望能考虑。
