### ISSUE TITLE
echarts 3和4，svg 方式渲染，在 IE9 - IE11 上面饼图、柱状图数据显示重复

### ISSUE THREAD

**Issue by huigeek** [apache/echarts#8152]
### echarts 版本3和版本4，svg 方式渲染，在 IE9 - IE11 上饼图、柱状图

的数据显示重复

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts 3 完整版，echarts 4 完整版
+ Browser version [浏览器类型和版本]: IE9  IE10 IE11
+ OS Version [操作系统类型和版本]: windows7

### Expected behaviour [期望结果]

修复 SVG 模式渲染在 IE11 上饼图、柱状图数据不重复

### ECharts option [ECharts配置项]

**option 配置省略，应该不是option的配置问题，拿的官方事例的饼图、柱状图都有同样问题**

```javascript
option = {

}

```

### Other comments [其他信息]

![wechatimg49](https://user-images.githubusercontent.com/13644163/38715669-18e56c8a-3f0f-11e8-9ff6-db8ba58da3e9.jpeg)
http://echarts.baidu.com/examples/editor.html?c=pie-legend
![wechatimg50](https://user-images.githubusercontent.com/13644163/38716781-327eb8a8-3f15-11e8-8f7f-24316d626c65.jpeg)
http://echarts.baidu.com/examples/editor.html?c=bar-negative

**Comment by xuchao008** [comment]
@huigeek 请问，演示demo上怎么做到svg渲染，谢谢。

**Comment by huigeek** [comment]
@xuchao008 http://www.echartsjs.com/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93

// 使用 Canvas 渲染器（默认）
var chart = echarts.init(containerDom, null, {renderer: 'canvas'});
// 等价于：
var chart = echarts.init(containerDom);

// 使用 SVG 渲染器
var chart = echarts.init(containerDom, null, {renderer: 'svg'});
