### ISSUE TITLE
Highlighting the clicked month

### ISSUE THREAD

**Issue by vikramkalta** [apache/echarts#8160]
![test](https://user-images.githubusercontent.com/23207610/38778731-84d90884-40db-11e8-822d-4bcdd9cf1e6e.png)

I want to get the selected month by user highlighted!! as you can see in the image i have attached. I have come close by using brush, but still could not acheive it completely. 
When I dispatch an action, lets say I pass ['Mar', 'Apr'] to coordRange property, and it makes a brush between Mar and April, I want it to be highlighted exactly April if user selected April.
Thanks

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
Try using the `markArea` component to highlight the area

**Comment by thomaspessato** [comment]
@vikramkalta did you solve your problem?

**Comment by vikramkalta** [comment]
@pissang Hi, thanks for the reply, sorry about the late reply. I will definitely try using markArea and update. (Im heavily using echarts for a project, little bit help from the inside people would be great).

@thomaspessato i solved my problem using graphic and positioning graphic using offsetX which i get with every click, although if u resize the browser, it does not stay at that selected month anymore.

**Comment by thomaspessato** [comment]
@vikramkalta I managed to change label style after click, for example:

```javascript
this.chart.on('click', (params) => {
    params.event.target.style.fontWeight = "bold";
    params.event.target.style.textFill = "#000";
})
```

This related to the point clicked... but would be nice if we on click, since this doesnt change data, just label / point / area style.

I saw that people were using setOption() for this... but don't know how to do this, exactly :/

**Comment by vikramkalta** [comment]
@thomaspessato I guess u are trying to just emphasize the circle when it is clicked!! 
I reworked on it today and and found exactly what i was looking for, so i made a custom series with same rectangular figure, and position it inside renderItem property.

renderItem: (params: any, api: any) => {
                const categoryIndex = api.value(0);
                console.log('category', api.coord([api.value(0), maxVal]));
                const start = api.coord([api.value(0), maxVal]);

                if (params.dataIndex === this.monthIndex) {
                  return {
                    type: 'group',
                    children: [
                      {
                        type: 'rect',
                        shape: {
                          width: '30',
                          height: 110
                        },
                        position: newStart,
                        top: this.options.grid.top,
                        style: { fill: 'rgba(255,255,0,0.3)' }
                      }
                    ]
                  };
                }

              },

Phewwww... even if screen sizez changes the graphic does not move a inch.....

**Comment by vikramkalta** [comment]
set emphasize to false in the options or refer the docs, and set emphasize for each click. or you can dispatch an action on a click and that would do the same!!
dispatchAction({
    type: 'highlight',
    // optional; series index; could be an array of multiple series
    seriesIndex?: number|Array,
    // optional; series name; could be an array of multiple series
    seriesName?: string|Array,
    // options are index of data
    dataIndex?: number,
    // options are data name
    name?: string
})

refer the api section in echarts website

**Comment by vikramkalta** [comment]
but in order to keep the previous clicked circle also in the same state, i had not tried that yet!!

**Comment by thomaspessato** [comment]
@vikramkalta  Damn!! That was so obvious... thanks for pointing that out!

**Comment by thomaspessato** [comment]
I could not find emphasize on click, but will search for that

**Comment by vikramkalta** [comment]
@thomaspessato I have tried dispatching action, it works for a click, on every click just pass the ev.dataIndex to dataIndex property
https://ecomfe.github.io/echarts-doc/public/en/api.html#action

**Comment by thomaspessato** [comment]
gonna try this!

**Comment by Ppsj** [comment]
but  automatically triggered highlight event cannot be triggered event.
For example, when I switch automatically, the mouse moves up. Trigger the default highlight. But did not trigger the highlight event.
So, I think there are other ways to handle the mouseover event.
(sorry， my english is poor)
https://codepen.io/Carl_su/pen/zyzWQQ
