### ISSUE TITLE
Wrong dataShadow for axis type time

### ISSUE THREAD

**Issue by pm789** [apache/echarts#8186]
### One-line summary [问题简述]
The dataShadow of the dataZoom is plotted with incorrect x-axis position when axis type is 'time'.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.2
+ Browser version [浏览器类型和版本]: Firefox 59.0.2 (64bit)
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]
When the axis type is 'time', the dataShadow in the dataZoom should be plotted depending on the time.
However, the data points are plotted with a constant offset in the dataShadow, even when there are huge jumps in time.
The example below should be pretty self-explanatory.

### ECharts option [ECharts配置项]

```javascript
option = {
    title : {
        text: 'DEBUG',
        x: 'center',
    },
    grid: {
        bottom: 80
    },
   
    dataZoom: {
        type: 'slider',
        //showDataShadow: false,
        show: true,
        realtime: true,
        xAxisIndex: 0,
    } ,
    xAxis : {
        type: 'time',
        boundaryGap : false,
        axisLine: {onZero: false},
    } ,
    yAxis: {
        type: 'value',
    },
    series: {
        name:'seriesName',
        type:'line',
        yAxisIndex:0,
        animation: false,
        data: [ ['2009/6/12 2:00', 0], 
                ['2009/7/1 0:00', 0], 
                ['2009/7/1 1:00', 100], 
                ['2009/7/1 2:00', 0], 
                ['2009/7/1 3:00', 0], 
                ['2009/7/1 4:00', 0], 
                ['2009/7/1 5:00', 0], 
                ['2009/7/1 6:00', 0], 
                ['2009/7/1 7:00', 0], 
                ['2009/7/1 8:00', 0], 
                ['2009/7/1 9:00', 0], 
        ]
    }
};
```

### Other comments [其他信息]
Use online editor for fast testing: https://ecomfe.github.io/echarts-examples/public/editor.html

![e-charts bug](https://user-images.githubusercontent.com/38489453/38918986-9a51521e-42ef-11e8-9094-28b503fa1704.png)

**Comment by mmadden** [comment]
I can confirm this is still an issue in ECharts version 4.1.0.

**Comment by SachioKuro** [comment]
Still an issue on 4.2.1. Any plans to fix it?

**Comment by sirkalmi** [comment]
This problem also occurs with me, it is very annoying.
