### ISSUE TITLE
想获取北京市石景山区的geoJson

### ISSUE THREAD

**Issue by AndrewXiGua** [apache/echarts#8190]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
https://github.com/echarts-maps/echarts-china-counties-js#直辖市

**Comment by lishaoh** [comment]
@chfw 能提供街道信息吗

**Comment by chfw** [comment]
我可以尝试一下。请发具体要求到我的联系信箱 wangc_2011@hotmail.com 。时间周期会长一点啊，我得找空做。

**Comment by hl-stone** [comment]
@chfw  你好，做这样类型的地图数据，采用什么方法或工具呢，有出教程吗？
