### ISSUE TITLE
lines使用effect后 无法clear()

### ISSUE THREAD

**Issue by insecthole** [apache/echarts#8225]
### One-line summary [问题简述]
lines使用effect后，clear(),方法无法清除干净

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.04
+ Browser version [浏览器类型和版本]:所有浏览器
+ OS Version [操作系统类型和版本]:win10 64

### ECharts option [ECharts配置项]

```javascript
option = {
 xAxis: {
            min: 0,
            max: 200
        },
        yAxis: {
            min: 0,
            max: 200
        },
        color:"black",
        series: [{
            coordinateSystem: 'cartesian2d',
            type: 'lines',
            data: [{
                coords: [[0, 66], [122, 150]],
            }],
            effect: {
                show: true,
                color: "white"

            },
        }]
}

```

**Comment by Adelaide1014** [comment]
需要注意加载顺序,若是图标没有加载完成就执行了chart.clear();就不会起作用；
可以
<pre>
setTimeout(function() {
    chart.clear();
    //chart.dispose();
}, 10000);
</pre>

**Comment by chj-damon** [comment]
同样遇到了这个问题，clear之后，线还在，但是像是残影一样
