### ISSUE TITLE
Webpack tree shaking not working too well on echarts

### ISSUE THREAD

**Issue by Amine-H** [apache/echarts#8239]
### One-line summary [问题简述]

Webpack tree shaking not working too well on echarts

![dependencies](https://user-images.githubusercontent.com/6276978/39365808-1f7674b0-4a2a-11e8-90d3-5100c202484b.PNG)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Chrome 65.0.3325.181 (Official Build) (64 bits)
+ OS Version [操作系统类型和版本]: macOS 10.13.4

### Expected behaviour [期望结果]
would be great if I could only bundle Piechart into my solution.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by shinnyx** [comment]
Any update on this?

**Comment by aesyondu** [comment]
Hi, did you follow the instruction on the docs?
https://echarts.apache.org/en/tutorial.html#Use%20ECharts%20with%20webpack

Went down from 2.5mb -> 1mb

<details>
<summary>
Before:
</summary>

```javascript
import echarts from "echarts"
```

<img width="935" alt="image" src="https://user-images.githubusercontent.com/57334943/78223412-677ac800-74f9-11ea-9044-4cd0434d7b06.png">
</details>


<details>
<summary>
After:
</summary>

```javascript
import echarts from 'echarts/lib/echarts'
import 'echarts/lib/chart/bar'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/title'
```
<img width="779" alt="image" src="https://user-images.githubusercontent.com/57334943/78223504-909b5880-74f9-11ea-879a-926a24d41382.png">
</details>
