### ISSUE TITLE
setOption.geo.regions的label.offset不起作用

### ISSUE THREAD

**Issue by zmrzwj** [apache/echarts#8247]
### One-line summary [问题简述]
setOption.geo.regions下的label.offset不起作用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

v4.1.0
chrome 66.0.3359.139
macos highsierra 10.13.4

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lolysc** [comment]
我也遇到这个问题。position和label都没用，我下载了最新源码环境里的demo，用geo-map.html测试，也还是不行。bug，能尽快解决么？地图上省份名称调整位置是刚需啊

**Comment by funlee** [comment]
我也遇到这个问题了，只有color fontSize 这些属性能生效
