### ISSUE TITLE
关于option更新方面的问题

### ISSUE THREAD

**Issue by xuhuan** [apache/echarts#828]
问题已解决，配置少个[]。

echarts修改参数基本就只能靠一个setOption。
highcharts基本上各个参数都可以动态进行局部更新，感觉这种方式比较合理。
![image](https://cloud.githubusercontent.com/assets/1960194/4821772/ac204d76-5f34-11e4-9882-de7602868e8f.png)

还有感觉文档有点混乱，demo太少，一页一堆的参数，大部分参数配置都没有实例。
条理性有点欠缺，建议能否出一份highcharts的api文档类似结构的文档？
highcharts的英文文档感觉看起来比echarts的中文文档轻松很多，哪怕我不怎么熟悉，
它的文档结构已经说明了很多。
![image](https://cloud.githubusercontent.com/assets/1960194/4821765/85081dea-5f34-11e4-87a2-ca69dcd74ae9.png)

**Comment by wych1987** [comment]
`
option = {
    legend: {
        orient: 'horizontal', // 'vertical'
        x: 'right', // 'center' | 'left' | {number},
        y: 'top', // 'center' | 'bottom' | {number}
        backgroundColor: '#eee',
        borderColor: 'rgba(178,34,34,0.8)',
        borderWidth: 4,
        padding: 10,    // [5, 10, 15, 20]
        itemGap: 20,
        textStyle: {color: 'red'},
        selected: {
            '降水量' : true
        },
        data: [
            {
                name:'蒸发量',
                icon : 'image://../asset/ico/favicon.png',
                textStyle:{fontWeight:'bold', color:'green'}
            },
            '降水量','最高气温', '最低气温'
        ]
    },
    xAxis :{
        data : ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} ml'
            }
        },
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} °C'
            },
            splitLine : {show : false}
        }
    ],
    series : [
        {
            name:'蒸发量',
            type:'bar',
            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6]
        },
        {
            name:'最高气温',
            type:'line',
            yAxisIndex: 1,
            data:[11, 11, 15, 13, 12, 13, 10]
        },
        {
            name:'降水量',
            type:'bar',
            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6]
        }
    ]
};
setTimeout(function(){
	var p  = {
    legend: {
       selected:{"降水量":false}
}
    }
 myChart.setOption(p);
                    
},5000)
             
                    `
为啥图表不刷新啊，，，求教

**Comment by wych1987** [comment]
option = {
	legend : {
		orient : 'horizontal', // 'vertical'
		x : 'right', // 'center' | 'left' | {number},
		y : 'top', // 'center' | 'bottom' | {number}
		backgroundColor : '#eee',
		borderColor : 'rgba(178,34,34,0.8)',
		borderWidth : 4,
		padding : 10, // [5, 10, 15, 20]
		itemGap : 20,
		textStyle : {
			color : 'red'
		},
		selected : {
			'降水量' : true
		},
		data : ['蒸发量','降水量', '最高气温'	]
	},
	xAxis : {
		data : ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
	},
	yAxis : [{
			type : 'value',
			axisLabel : {
				formatter : '{value} ml'
			}
		}, {
			type : 'value',
			axisLabel : {
				formatter : '{value} °C'
			},
			splitLine : {
				show : false
			}
		}
	],
	series : [{
			name : '蒸发量',
			type : 'bar',
			data : [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6]
		}, {
			name : '最高气温',
			type : 'line',
			yAxisIndex : 1,
			data : [11, 11, 15, 13, 12, 13, 10]
		}, {
			name : '降水量',
			type : 'bar',
			data : [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6]
		}
	]
};
setTimeout(function () {
	var p = {
		legend : {
			selected : {
				"降水量" : false
			}
		}
	}
	myChart.setOption(p);

}, 5000)    
    
这样并没有刷新图表信息啊。。。求教。。。

**Comment by xfworld** [comment]
@kener  要是在API里面有这些介绍就好了，前期自己走了很多弯路 ：） 在没看到这个解释之前，都还不明白为什么要这么用；

**Comment by ileler** [comment]
@kener 问个问题，，，我现在有个需求，导出图片时给图片加上水印，，，，现在在导出操作里setOption时页面也会更新，正确的使用方式是怎样的呢？？？

**Comment by kener** [comment]
没懂后半段，前半段最新发布的版本不就支持水印吗？

**Comment by ileler** [comment]
恩恩。。。我上午折腾了半天算是完成这个需求（：页面上展示正常的图表，导出报表时加上自定义的水印。）了，，，我自己的想法是调用`getDataURL`时传的option能带`graphic`水印，可是貌似不能，于是就只有`setOption`附加`graphic`上去，但是一旦调用`setOption`页面就会更新，所以没法满足需求。今天上午想了个解决方案，就是在body后面加一个全屏`div`然后set其`z-index=-1`，然后导出时把加水印的option在这个底层的div上渲染，然后借助这个底层div的echarts对象调用其`getDataURL`，这样算是完美的满足了需求。

**Comment by ileler** [comment]
there is my code. (＾▽＾)

**Comment by tinybright** [comment]
如何修改 一个series的属性呢？
