### ISSUE TITLE
能否让力导图节点之间有多条连线

### ISSUE THREAD

**Issue by yanggaojun101** [apache/echarts#8317]
目前两个节点无法有两条同向的线条
希望能像如图所示那样，两个节点之间可以有多条连线

![1](https://user-images.githubusercontent.com/3292215/39857234-2d2da6c4-5465-11e8-9f77-02e4bd841648.png)

**Comment by YzPaul3** [comment]
同样建议，可以展示出两个节点之间的不同关系。目前只能转投向d3来实现

**Comment by sannai** [comment]
请问 你们这个问题用什么办法解决了

**Comment by deqingli** [comment]
#11260

**Comment by hankdandan** [comment]
还没有解决吗，我现在版本是5.0没有// if (edgesMap[key]) { // return; // }这行说要注释的代码
使用的是id作为source和target的
求解决
