### ISSUE TITLE
3D绘制surface曲面中的问题

### ISSUE THREAD

**Issue by waitkafuka** [apache/echarts#8319]
3D surface图表中的数据坐标，有什么要求吗？按理说不是应该空间中任意三个不重合的点都可以绘制出一个面吗？为什么在实际中绘制不了呢？
代码：

```
    var myChart = echarts.init(document.getElementsByClassName('chart-container')[0]);
    var data = [
        [-1, -1, 0],
        [0, -1, 0],
        [0.5, -1, 0]
    ];
    var option = {
        grid3D: {
        },
        xAxis3D: {
        },
        yAxis3D: {
        },
        zAxis3D: {
        },
        series: [{
            type: 'surface',
            data:data
        }]
    }
    myChart.setOption(option);
```

实际上是想做一个类似这样的图：
![image](https://user-images.githubusercontent.com/8555018/39874041-36f73f3c-549f-11e8-9d87-63d7a8946e40.png)
但是用上面三个数据点的代码，把数据放进去，渲染不出来，是一片空白：
![image](https://user-images.githubusercontent.com/8555018/39874078-54324df8-549f-11e8-9023-d57cd323ade1.png)
求解！
是对data有什么要求？

**Comment by waitkafuka** [comment]
把里面的data换一下，换成这种：
```
var data = [
        [-1, -1, 0],
        [-0.5, -1, 0],
        [0, -1, 0],
        [0.5, -1, 0],
        [1, -1, 0],
        [-1, -0.5, 0],
        [-0.5, -0.5, 1],
        [0, -0.5, 0],
        [0.5, -0.5, -1],
        [0, 0, 0],
        [0.5, 0, 0],
        [1, 0, 0],
        [1, 0.5, 0]
    ];
```
就能出来图形：
![image](https://user-images.githubusercontent.com/8555018/39874403-3785e330-54a0-11e8-888f-3b97a2c93f55.png)
这是为什么？难道是点不够？

**Comment by weenhall** [comment]
这个问题解决了吗，兄台

**Comment by harsima** [comment]
和顺序有关，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴

**Comment by EmptyHead35** [comment]
> 和顺序有关，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴

那怎么做垂直x轴平行y轴的平面，我输入了这个  data:[[0,0,0],[0,1,0],[0,0,1],[0,1,1]]，然后出不来图

**Comment by harsima** [comment]
> > 和顺序有关，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴
> 
> 那怎么做垂直x轴平行y轴的平面，我输入了这个 data:[[0,0,0],[0,1,0],[0,0,1],[0,1,1]]，然后出不来图

请认真看我说的，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴，正确的顺序是这样的：[0,0,0],[1,0,0],[0,0,1],[1,0,1]

**Comment by EmptyHead35** [comment]
我要一个过x=0的平面，就是x一直为0，y和z任意的，不过已经解决了，用的u和v画出来的。------------------ 原始邮件 ------------------
发件人: "harsima"<notifications@github.com>
发送时间: 2019年7月12日(星期五) 上午9:12
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "EmptyHead35"<873245573@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [apache/incubator-echarts] 3D绘制surface曲面中的问题 (#8319)


  
和顺序有关，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴
  
那怎么做垂直x轴平行y轴的平面，我输入了这个 data:[[0,0,0],[0,1,0],[0,0,1],[0,1,1]]，然后出不来图
  
请认真看我说的，先做X轴一排数据（Y轴不变），然后再逐次向上加Y轴，正确的顺序是这样的：[0,0,0],[1,0,0],[0,0,1],[1,0,1]
 
&mdash;

**Comment by hanwenbo** [comment]
@EmptyHead35 怎么排序  分享下

**Comment by EmptyHead35** [comment]
> @EmptyHead35 怎么排序 分享下


[](https://www.echartsjs.com/zh/option-gl.html#series-surface.data)
这个上面写了排序的规则。我自己做了几个平面，

option = {
    tooltip: {},
    backgroundColor: '#fff',
    visualMap: {
        show: false,
        dimension: 2,
        min: -1,
        max: 1,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    xAxis3D: {
        type: 'value'
    },
    yAxis3D: {
        type: 'value'
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        viewControl: {
            // projection: 'orthographic'
        }
    },
    series: [{
        type: 'surface',
        wireframe: {
            // show: false
        },
        //这个垂直z轴是x，y面
         data:[[0,0,0],[1,0,0],[0,1,0],[1,1,0]]
    },{
        type: 'surface',
        wireframe: {
            // show: false
        },
        //这垂直y个是x，z面
         data:[[0,0,0],[1,0,0],[0,0,1],[1,0,1]]
    },{
        type: 'surface',
        wireframe: {
            // show: false
        },
        //这垂直x个是y，z面,但是这个面画不出来
         data:[[0,0,0],[0,1,0],[0,0,1],[0,1,1]]
    }
    ,{
        type: 'surface',
        wireframe: {
            // show: false
        },
        parametric:true,
        //这垂直x个是y，z面,用参数方程画出来
          parametricEquation: {
    u: {
        min:0,
        max: 1,
        step: 1
    },
    v: {
         min:0,
        max: 1,
        step: 1
    },
    x: function (u, v) {
        return 0;
    },
    y: function (u, v) {
        return u;
    },
    z: function (u, v) {
        return  v
    }
         }
    }
    
    
  
]
}

**Comment by EmptyHead35** [comment]
> @EmptyHead35 怎么排序 分享下

https://www.echartsjs.com/zh/option-gl.html#series-surface.data

**Comment by hanwenbo** [comment]
@EmptyHead35 我想根据三维的散点坐标画出来曲面图  您有思路么

**Comment by EmptyHead35** [comment]
> @EmptyHead35 我想根据三维的散点坐标画出来曲面图 您有思路么

你可以私聊我，或者用QQ交流。。。你要所有散点都有了，就是用data，而不是用方程了。

**Comment by hanwenbo** [comment]
@EmptyHead35 您qq多少 我的是9476400
我所有的散点都有

**Comment by nba20416** [comment]
> 所有散点都有了，就是用data，而不是用方程

您好，我也有这个问题，我有三维的点，但是出不来曲面图是空白。不知道怎么处理Z轴的数据。
