### ISSUE TITLE
服务器端导出echarts的图片有合适方案吗

### ISSUE THREAD

**Issue by wdp284551135** [apache/echarts#837]
请问一下，最近在做一个定时器导出报表的功能，需要导出web页面生成的同样效果的echarts图片，请问有合适的解决方案吗？

**Comment by XiaodiKong** [comment]
类似的问题转了好久个， @kener 请问有没有直接的方法或者解决方案？看了几个issue，也没找到那个是真的解决办法

**Comment by wdp284551135** [comment]
我用别的方式实现了，你可以参考下，phantomjs+nodejs来做，phantomjs来调用echart.js渲染图表，然后用nodejs调用phantomjs得到渲染后图表的base64图片编码

**Comment by XiaodiKong** [comment]
@wdp284551135 我现在也是打算这么做，但是过程中遇到点问题，请问是否可以把你的代码给我看下？

**Comment by XiaodiKong** [comment]
@wdp284551135 能否给我个联系方式？我想和你请教下

**Comment by wdp284551135** [comment]
用户名这个数字就是qq

**Comment by debug2012** [comment]
我做了一个服务端导出echarts图片的服务

https://debug2012.github.io/2017/04/14/export-echarts-image/

**Comment by YH-Chen** [comment]
除了node-canvas（下载不了）、phantomjs、puppeteer（不让使用），还有其他方法吗

**Comment by YH-Chen** [comment]
您的来信已经收到，我会尽快查阅！
