### ISSUE TITLE
Tree 4.0，tree点击节点后追加数据

### ISSUE THREAD

**Issue by burgod** [apache/echarts#8393]
### One-line summary [问题简述]

echarts 4.0，tree点击节点，写了 onclick事件，然后里面当节点追加数据params.data.children.push，怎样才能展示数据呢，debugger看到数据已经追加到params了，但是option里面没有，看到有说调用实例的refresh方法，但是提示refresh not a function.

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]:火狐，谷歌
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]

点击树节点，追加数据后，是追加追加，不能清除树前面的数据。能在新展开的节点展示这些数据。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lurenj** [comment]
问一下，怎么解决的？我现在也是在这里卡住了,用appendData()但是数据显示不出来！而且也有点搞不懂怎么添加到指定的节点下！
