### ISSUE TITLE
Piecewise visualmap 需要和legend一样支持分页

### ISSUE THREAD

**Issue by ToughRover** [apache/echarts#8401]
Piecewise的visualmap，在散点图中分类变量的分类增多时，visuamap组件的布局会超出画布，很难做处理，希望这块和legend一样支持分页显示

**Comment by ToughRover** [comment]
这个问题有人处理吗？

**Comment by IEfucker** [comment]
同问，visualMap很长怎么处理，换行？or分页？

**Comment by Marsellen** [comment]
你好，可以看看这个回答，会不会帮你解决问题，https://github.com/apache/echarts/issues/8413#issuecomment-772348246

**Comment by lcyh** [comment]
这个问题几件了还没人解决呢
