### ISSUE TITLE
vue中怎么监听echarts事件

### ISSUE THREAD

**Issue by child110** [apache/echarts#8402]
### One-line summary [问题简述]
正常可以通过下面代码监听echarts事件
    chart.on('click', function (params) {
                console.log(params)
            });

   <div id="biEchart"  @click="onClick($event)" style="width:100%;height: 250%">
在vue中通过@click只能监听到dom事件，怎么监听ecahrts事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 52linyuepeng** [comment]
这个是不是 vue 中没有区别吧。
拿到实例 chart
```
chart.on('click', function (params) {
console.log(params)
// 如果你需要抛给外层组件
// this.$emit('click', params)
});
```

如果你希望用更接近于 vue 的方式，可以封装一层，或者直接用  vue-echarts 库。

**Comment by child110** [comment]
正常不是在vue中，直接  
chart.on('click', function (params) {
                console.log(params)
            });
就可以获取echarts事件参数
但是在vue中 mounted(){
this.chart.on('click', function (params) {
                console.log(params)
            });
}获取不到事件参数，不想用vue-echarts时怎么办？请问怎么封装

**Comment by child110** [comment]
在watch写监听函数就可以了 多谢

**Comment by luckyguygx** [comment]
我写了watch还是没用 可以贴下代码吗？谢谢 @child110
