### ISSUE TITLE
ReferenceError: zrUtil is not defined

### ISSUE THREAD

**Issue by wukuy** [apache/echarts#8452]
### One-line summary [问题简述]

js 报错
某些android版本手机报错
```
[Vue warn]: Error in callback for watcher "options": "ReferenceError: zrUtil is not defined"
```
折线图无法正常显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
4.10
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
vivo X6Plus L android 5.1
还有另一款手机忘记了叫什么型号，也是版本比较低的
公司也就几台测试机，两台报的相同的错误

### Expected behaviour [期望结果]
4.10没这个问题的报错

### 我这里已经解决，
package.json
```json
"echarts": "^4.0.4",
```
改为
package.json
```json
"echarts": "4.0.4",
```

`^`去掉。把版本号锁死在4.0.4，`^`会升级小版本
重现装包
特意提issues，遇到相同问题有参考

**Comment by luxueyan** [comment]
use echarts 4.1 ！ I have the same problem in chrome 44！

**Comment by xiongyuqiong** [comment]
我的是vue+echarts4.1.0 也遇到了这个问题  请问楼主有遇到过么

**Comment by donotlb** [comment]
android 5.1.1, 换成固定版本 4.0.4 暂时解决了问题，希望官方能解决该问题，兼容性调试是真的消耗时间啊

**Comment by chenchensdo** [comment]
降至4.0.4版本确实可以，最新版本反而不行，是什么原因，希望官方关注一下

**Comment by Circleee** [comment]
我也遇到过了这个问题

**Comment by Amorites** [comment]
移动端 chrome40 echarts 4.2.1 可以复现

**Comment by HY0606** [comment]
如果在不能降级的情况下，有别的解决方案吗？ @wukuy

**Comment by SHERRYWANNA** [comment]
android 4.4 
echarts 4.7.0
env 打正式包情况下就会消失，development下还会出现
