### ISSUE TITLE
parallel图中选择数据时无法正常显示

### ISSUE THREAD

**Issue by PinkD** [apache/echarts#8473]
### One-line summary [问题简述]

`parallel` 图中：

当 `parallelAxis` 中的数据有多个 `type` 为 `category` 时，在图中只有选择第一组数据时才能正常显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 64Bit 64.0.3282.186 
+ OS Version [操作系统类型和版本]: Win10 64Bit 10.0.16299

### Expected behaviour [期望结果]

选择每一组数据均能正常显示

### ECharts option [ECharts配置项]

```javascript
option = {
 color: [
        '#c23531', '#91c7ae', '#dd8668'
    ],
    legend: {
        top: 10,
        data: ['北京', '上海', '广州'],
        itemGap: 20
    },
    parallelAxis: [
        {dim: 0, name: schema[0].text, inverse: true, max: 31, nameLocation: 'start', type:'category'},
        {dim: 1, name: schema[1].text},
        {dim: 2, name: schema[2].text},
        {dim: 3, name: schema[3].text},
        {dim: 4, name: schema[4].text},
        {dim: 5, name: schema[5].text},
        {dim: 6, name: schema[6].text},
        {dim: 7, name: schema[7].text,
        type: 'category', data: ['优', '良', '轻度污染', '中度污染', '重度污染', '严重污染']}
    ],
    parallel: {
        left: '5%',
        right: '13%',
        bottom: '10%',
        top: '20%',
        parallelAxisDefault: {
            type: 'value',
            name: 'AQI指数',
            nameLocation: 'end',
            nameGap: 20,
            nameTextStyle: {
                fontSize: 12
            }
        }
    },
    series: [
        {
            name: '北京',
            type: 'parallel',
            lineStyle: lineStyle,
            data: dataBJ
        },
        {
            name: '上海',
            type: 'parallel',
            lineStyle: lineStyle,
            data: dataSH
        },
        {
            name: '广州',
            type: 'parallel',
            lineStyle: lineStyle,
            data: dataGZ
        }
    ]
}

```

注：以上代码来源例子 [parallel-all](http://www.echartsjs.com/gallery/editor.html?c=doc-example/parallel-all) ，并将其中的 `parallelAxis` 中的第一组数据改为 `category` 类型

### Other comments [其他信息]

此issue与 #7805 应该为同一问题，但提供了更完整问题描述

截图：

选中第一组数据：

![1](https://user-images.githubusercontent.com/14852537/41013416-93d5846e-6978-11e8-882b-d00fe9b9ba1c.JPG)

选中最后一组数据（另一组 `type` 为 `category` 的数据）：

![2](https://user-images.githubusercontent.com/14852537/41013458-b9f18422-6978-11e8-84e5-84f275db84b2.JPG)

**Comment by seriousAA** [comment]
我今天遇到了相同的问题，调了半天意识到是echarts的问题，好难受

**Comment by lvybriage** [comment]
@Ovilia 小姐姐，你能顺便帮忙回复一下这个问题吗？我也遇到了相同的问题，在搜issue的时候发现也有人遇到了相同的问题。非常感谢
