### ISSUE TITLE
获取地图缩放比例

### ISSUE THREAD

**Issue by Quintalq** [apache/echarts#8510]
echarts 4.0 geomap 有没有方法可以获取到当前地图缩放的比例呀，调用georoam 获取的zoom一直都是1.1

**Comment by pissang** [comment]
getOption().geo[0].zoom

**Comment by Quintalq** [comment]
嗯，我也是想到了这个

**Comment by jichenchen91** [comment]
我也遇到这个问题，但是用了你的方法提示“无法获取未定义或 null 引用的属性’0‘”，请问这是怎么回事呢？

**Comment by Quintalq** [comment]
你要看你的getOption获取回来的数据有没有geo这个属性额

**Comment by jichenchen91** [comment]
果然没有，谢谢你啊，我找到原因了，是我初始化的时候并没有加上geo这个属性

**Comment by jichenchen91** [comment]
不好意思，我还有个问题没能解决，就是我检测到的缩放级别，是初始化就配置好的，有可以获得当前缩放级别的方法吗？因为我需要根据放大级别显示地图名称，比如地图放大到3倍，就显示所有国家名称；地图缩小到1倍的时候就隐藏国家名称

**Comment by Quintalq** [comment]
getOption().geo[0].zoom

**Comment by jichenchen91** [comment]
baseOption  = {
                         width: 800,
                         height: 440,
                         visualMap: visualMap,
                         geo: {
                        	 zoom: 1,
                         },
                         series: [
                             {
                                 name:'title',
                                 type: 'map',
                                 mapType: 'world',
                                 roam: true,
                                 scaleLimit: {
                                     min: 1,
                                     max: 5
                                  },
                                 itemStyle: {  
                                     normal: {  
                                         borderColor: '#f5f5f5',  
                                         color: 'white',  
                                         label:{
                                        	 show: false,
                                         }
                                     }  
                                 },
                                 data: omapData
                             }
                         ]
                     };
                    worldMap.setOption(baseOption, true);
                    worldMap.on("click", function(params){
                        window.location = "${basePath!''}/riskBip/countryRisk?countryPkno="+params.data.countryPkno;
                    });
                    worldMap.on("georoam", function(params){
                    	console.log(worldMap.getOption().geo[0].zoom)
                    })

你好这是我的option配置，能看到geo的zoom初始值为1；但是当我执行georoam（最后一段）方法时，console出来的zoom值一直都是初始值1，我想获取的是地图放大的级别，这个怎么获得啊？

**Comment by Darcrandex** [comment]
我也遇到同样的问题。。。

**Comment by jichenchen91** [comment]
@Darcrandex  我的问题解决了，描述一下你的问题

**Comment by fuxinruming** [comment]
@jichenchen91 你好，我的问题也是这样，怎么能动态获取地图的当前缩放级别，而不是设置的级别

**Comment by 10229428** [comment]
> @Darcrandex 我的问题解决了，描述一下你的问题

请问你是如何解决了啊？geo.zoom的值好像是固定的，并非当前缩放级别的值

**Comment by jichenchen91** [comment]
optino.geo.zoom = worldMap.getOption().geo[0].zoom

**Comment by jichenchen91** [comment]
> > @Darcrandex 我的问题解决了，描述一下你的问题
> 
> 请问你是如何解决了啊？geo.zoom的值好像是固定的，并非当前缩放级别的值

不知道能不能帮到你，我做了一些固定的数据数组，地图缩放变化时直接切换数据源了
