### ISSUE TITLE
如何设置数据视图显示的div区域大小，在toolbox中没有找到,默认的div样式太大,偏移位置，尤其关闭和刷新按钮错位

### ISSUE THREAD

**Issue by shanewds** [apache/echarts#8515]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="js/echarts.js"></script>
    <style>
    
	element.style {
	    position: absolute;
	    left: 11px;
	    top: 5px;
	    bottom: 333px;
	    right: 5px;
	    background-color: rgb(255, 255, 255);
	}
    </style>
</head>
<body>
    <div id="outer">
    
    <div id="main" style="width:550px;height:400px;"></div></div>
    <script type="text/javascript">
  

        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
         var option = {
        		 legend: {                       //图例
                     show:false,                   //是否显示图例
                     orient: 'vertical',           //布局方向
                     x: 'left',                    //图例相对位置
                    // data:['一班','二班','三班'] //图例内容
                   },
                   toolbox: {
        		        show : true,
        		        feature : {
        		            mark : {show: true},
   
        		                dataView : {show: true, readOnly: false,
        		            	
        		            },
        		            magicType: {show: true, type: [ 'pie']},
        		            restore : {show: true},
        		            saveAsImage : {show: true}
        		        }
        		       
        		   },
                   series: [                       //内容
                     {
                       name:'驻留时间占比',      //内容标题
                       type:'pie',                 //图标样式
                       selectedMode: 'single',     //选中模式：单选
                       radius: ['42%', '22%'],         //饼图大小，[x,y]:x表示内半径，y表示外半径  
                       itemStyle : {
   		                normal : {
   		                    label : {
   		                    	  show: true, 
   		                    	  //position: 'inner',
   		                    	  position: 'outer',     
   		                         // formatter: '{d}%' 
   		                            textStyle:{
      		                    		color: '#818181',
      		                    		fontSize: 14,
      		                    		fontWeight: 'bold'
      		                    	}
   		                    },
   		                    labelLine :{
   		                    	show:true,
  		                        length: 100,
  		                        lineStyle:{
  		                        	color: '#818181'
  		                        	
  		                        }
   		                    	
   		                    } 
   		                }
   		                },
                       
                     
                       
                       color:['#2D4E7C','#3D67A2','#4A7BC1','#7286AA','#95A0B5'],    //颜色
                      // name:['一班','二班','三班'],                      //内容名称
                       data:[                                              //数据
                           {value:16.5,name:'<5min'},     //selected:是否被选中
                           {value:22.5,name:'5-10min'},
                           {value:16.7,name:'10-15min'},
                           {value:11.9,name:'15-20min'},
                           {value:32.4,name:'>20min'}
                       ],               
                     },
                     /////////////////
                      {
                       name:'驻留时间占比',      //内容标题
                       type:'pie',                 //图标样式
                       selectedMode: 'single',     //选中模式：单选
                       radius: ['42%', '22%'],         //饼图大小，[x,y]:x表示内半径，y表示外半径  
                       itemStyle : {
   		                normal : {
   		                    label : {
   		                    	  show: true, 
   		                    	  position: 'inner',
   		                    	 // position: 'outer',     
   		                         // formatter: '{d}%' 
   		                          textStyle:{
      		                    		//color: '#818181',
      		                    		fontSize: 12,
      		                    		fontWeight: 'bold'
      		                    }
   		                    },
   		                    labelLine :{
   		                    	show:true,
  		                        length: 100,
  		                        lineStyle:{
  		                        	color: '#818181'
  		                        }
   		                    	
   		                    } 
   		                }
   		                },
                       
                     
                       
                       color:['#2D4E7C','#3D67A2','#4A7BC1','#7286AA','#95A0B5'],    //颜色
                      // name:['一班','二班','三班'],                      //内容名称
                       data:[                                              //数据
                           {value:16.5,name:'16.5%'},     //selected:是否被选中
                           {value:22.5,name:'22.5%'},
                           {value:16.7,name:'16.7%'},
                           {value:11.9,name:'11.9%'},
                           {value:32.4,name:'32.4%'}
                       ],               
                     },
                     {
                       name:'大于5分钟观众占比',
                       type:'pie',
                       radius: ['42%', '56%'],
                       itemStyle : {
      		                normal : {
      		                    label : {
      		                    	
      		                    	  show: true, 
      		                    	  position: 'outer'    		                    	
      		                         // formatter: '{d}%'
      		                    	
      		                    },
      		                    labelLine :{
      		                    	show:false,
      		                        length: 40,
      		                        lineStyle:{
      		                        	color: '#818181'
      		                        }
      		                        
      		                    	
      		                    } 
      		                }
      		          },
                      
                       color:['#F2F2F2','#AE2318'],  
                       data:[
                           {value:16.5,name:''},  
                           {value:83.5,name:''}
                         
                       ]
                      
               }],
                   //backgroundColor: "#190c12",     //背景颜色
        		
          };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>
<img width="752" alt="wx20180613-132039 2x" src="https://user-images.githubusercontent.com/19984920/41331683-d63cd048-6f0c-11e8-847d-f772c9c81cb6.png">

<img width="1424" alt="wx20180613-132113 2x" src="https://user-images.githubusercontent.com/19984920/41331703-e8906e80-6f0c-11e8-91d1-f4c0a30eae1e.png">

**Comment by pissang** [comment]
toolbox 可以自定义显示的内容

**Comment by hcgit9527** [comment]
同问  数据视图右下角的关闭刷新按钮  如何设置样式以及偏移位置？  没有相关配置

**Comment by weiwei-zhang** [comment]
父元素上加个相对定位 position: relative；应该是width:100%继承出了问题
