### ISSUE TITLE
添加一个可以查看各类图表的各部分对应是什么配置选项的图文文档

### ISSUE THREAD

**Issue by kuige** [apache/echarts#8522]
### One-line summary [问题简述]
虽然现在有教程，有 API，有配置项手册，等等，但是还是无法直观地看到各类图表的各部分到底对应的是什么配置选项，而且有时候在配置项手册搜索的时候都不清楚要搜索什么关键字，只能逐个展开查看各个选项是什么意思，是怎么用的，比较麻烦，特别是新手对 echarts 不太熟悉的。

所以希望可以提供这样的图文文档，里面对每一类图表的每一部分都进行标注，标注各部分对应的配置选项是什么，这样只要开发者一查看这个文档，马上就知道自己要找的选项是什么，然后直接在配置项手册查看具体的使用说明，这样大大节省了查找配置项花费的时间。

![image](https://user-images.githubusercontent.com/8212800/41388521-db18b142-6fbe-11e8-807e-82fe5526de23.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
谢谢建议，我们正在做这部分的文档~
