### ISSUE TITLE
Scale fontSize of the whole chart

### ISSUE THREAD

**Issue by Paul-Kijtapart** [apache/echarts#8529]
### One-line summary [问题简述]
is there a suggested way to scale up/down the font size of a chart?
Or change the default fontSize used in various textStyle (i.e. update the minimum font size)?

### Expected behaviour [期望结果]
I am hoping to set font size for a chart with children having responsive font size.

This is similar to how I can work with CSS: https://jsfiddle.net/coolbean/yu5cej3n/3/

From the above link,
fontsize 'em' is employed to enable responsive font size of each child.
(i.e. for instance, if the font-size of the document is 12pt, 1em is equal to 12pt. )

You can change the font size used for class parent and see that each child responds accordingly.

### Question
I am wondering if Echart has some options to scale up the size of all font.

**Comment by mrarmyant** [comment]
I too would love this functionality.

**Comment by raaaaay-c** [comment]
Please find it here and see if it's helpful. 
https://stackoverflow.com/questions/59559511/how-to-auto-scale-font-size-in-echarts/
