### ISSUE TITLE
Request: Cumulative Line Chart

### ISSUE THREAD

**Issue by Meldanen** [apache/echarts#8536]
### One-line summary
The cumulative line chart doesn't seem to be included in ECharts.

### Request
We're thinking of changing our charting library, but it will hard to do so if the new one does not support cumulative line charts.

### Example (NVD3)
http://nvd3.org/examples/cumulativeLine.html

### Other comments 
If there is no time for this to be done by your team, could we develop it for you and have it added to the source code?

**Comment by pissang** [comment]
Not sure if it meets your request, cumulative line chart can be created by processing the data and use `tooltip.formatter` and `label.formatter` to display the original value. Please tell me if I missed anything.

**Comment by Meldanen** [comment]
Hi Pissang,

Thank you for your quick reply and sorry for the delay.

That's not exactly what we're looking for as we need a line (similar to the one in the example I've linked), that rebases the chart as you move it.

Kind Regards,
Meldanen

**Comment by klukiyan** [comment]
@pissang can you please explan what do you mean?
