### ISSUE TITLE
Request: Add a Brush End Event

### ISSUE THREAD

**Issue by neelneelneel** [apache/echarts#8537]
### One-line summary [问题简述]
Dispatch a 'BrushEnd'  event at the end of brushing. 

### Expected behaviour [期望结果]
I want to dispatch a Brushend event, so that I can trigger another function on the brush end.

#### Possible Change:

Modify dispatch in BrushView to emit 'brushend'

https://github.com/apache/incubator-echarts/blob/0d5e6d9f32bef1f1face878f9ccf9987a80ab339/src/component/brush/BrushView.js#L104-L109

**Comment by davyxzhang** [comment]
This would be helpful in a project I'm working on

**Comment by mlarosa2** [comment]
this would help me overcome cross browser compatibility issues with IE. Currently I am using a complicated workaround

**Comment by tmtron** [comment]
+1

**Comment by tmtron** [comment]
+1
