### ISSUE TITLE
折线图的data label太多，如何只显示相应坐标轴节点的

### ISSUE THREAD

**Issue by SparksFyz** [apache/echarts#8554]
### One-line summary [问题简述]

折线图的data label太多，如何只显示相应坐标轴节点的， 剩余的节点数值靠tooltp来显示

### Other comments [其他信息]

<img width="876" alt="2018-06-20 5 46 44" src="https://user-images.githubusercontent.com/8748814/41652053-aab9df8a-74b4-11e8-831e-5c883f5e8fab.png">

**Comment by deqingli** [comment]
label overlapping #11497
