### ISSUE TITLE
visualMap.itemSymbol not working as expected

### ISSUE THREAD

**Issue by SevenOutman** [apache/echarts#8560]
### One-line summary [问题简述]
`visualMap.itemSymbol` 以及 `visualMap.inRange.symbolSize` 无法按照文档介绍的方式工作。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0 via npm
+ Browser version [浏览器类型和版本]: Chrome 67
+ OS Version [操作系统类型和版本]: Ubuntu 16.04

### Expected behaviour [期望结果]
1. 使用分段式 `visualMap` 时希望使用圆形 icon，参考文档 http://echarts.baidu.com/option.html#visualMap-piecewise.itemSymbol，将 `visualMap.itemSymbol` 设为 `'circle'`，并没有起作用。
2. 阅读源码发现这里的 `itemSymbol` 配置可能会被 `inRange.symbol` 覆盖（即便并未设置 `inRange.symbol`，它的默认值 `'roundRect'` 也会覆盖 `itemSymbol`，这不符合预期），因此设置 `inRange.symbol` 为 `'circle'`，此时可以正常显示圆形图标，但 `inRange.symbolSize` 不起作用。

### ECharts option [ECharts配置项]

```javascript
option = {
  visualMap: {
    type: 'piecewise',
    itemSymbol: 'circle'
  }
}

```

### Other comments [其他信息]

可以在此官方实例中重现。
http://www.echartsjs.com/gallery/editor.html?c=doc-example/scatter-visualMap-piecewise

**Comment by laurapizza** [comment]
@Ovilia - this is a duplicate issue for [5719](https://github.com/apache/incubator-echarts/issues/5719)
