### ISSUE TITLE
折线图内存泄露和cpu占用率高

### ISSUE THREAD

**Issue by pengye1207** [apache/echarts#8572]
### One-line summary [问题简述]
持续的动态更新折线图的数据，会造成内存不断的上涨以及cpu持续的高占用，直到页面卡死崩溃

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:IE11
+ OS Version [操作系统类型和版本]:WIN 7

### Expected behaviour [期望结果]
内存占用能够稳定，cpu占用降低

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

直接使用官方实例，稍微增加点数据量即可，现象会更加明显

var base = +new Date(2014, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];

var data = [Math.random() * 150];
var data1 = [Math.random() * 150];
var data2 = [Math.random() * 150];
var data3 = [Math.random() * 150];
var data4 = [Math.random() * 150];
var data5 = [Math.random() * 150];

var now = new Date(base);

function addData(shift) {
    now = [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/');
    date.push(now);
    data.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
    data1.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
	data2.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
	data3.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
	data4.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
	data5.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
    now = new Date(+new Date(now) + oneDay);
}

for (var i = 1; i < 100; i++) {
    addData();
}

option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        boundaryGap: [0, '50%'],
        type: 'value'
    },
    series: [
        {
            name:'data',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data
        },
         {
            name:'data1',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data1
        },
		{
            name:'data2',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data2
        },
		{
            name:'data3',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data3
        },
		{
            name:'data4',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data4
        },
		{
            name:'data5',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            data: data5
        },
    ]
};

setInterval(function () {
    addData(true);
    myChart.setOption({
        xAxis: {
            data: date
        },
        series: [{
            name:'data',
            data: data
        },
        {
            name:'data1',
            data: data1
        },
		{
            name:'data2',
            data: data2
        },
		{
            name:'data3',
            data: data3
        },
		{
            name:'data4',
            data: data4
        },
		{
            name:'data5',
            data: data5
        }
		]
    });
}, 500);

**Comment by pengye1207** [comment]
ie下用工具查看，单页面cpu资源比例27%，占用线程为IEShims.dll!IEShims_SetRedirectRegistryForThread

**Comment by Colisy** [comment]
问题解决了吗

**Comment by pengye1207** [comment]
> 问题解决了吗

减少渲染时间间隔，减小数据更新频率，相对会好些
