### ISSUE TITLE
[enhancement]请echarts的series.data中支持null ， 同时支持x，y的属性字段定义

### ISSUE THREAD

**Issue by appleskiller** [apache/echarts#859]
基于以下两点：
1.在echarts的series.data中不支持null的，并要求在数据层面中处理成‘-’
2.在echarts的series.data中要求对应xAxis.data补齐data数据

问题为：
如上述，我们需要在数据层面处理两遍数据，只是为了补齐series.data与xAxis.data对应，这给数据处理增加了一定的压力。

建议是：
增加值对象的x和y字段，这样echarts能够很容易找到值对应的那个x或y，而不必完全基于索引，同时使得
系列的数据项可以不完整（多系列时它们通常不是完整的）。

**Comment by ynioba** [comment]
实际上我个人觉得，series.data中应该允许null，因为在MES系统中，或者别的一些系统中，null表示没有采集到数据，而0是采集到的数据为0。实际上可以显示为，断开的几个线段，这样，就真的非常直观了。对客户的界面也非常的友好。

**Comment by vipjeffreylee** [comment]
支持

在 2015年5月25日 下午2:07，ynioba <notifications@github.com>写道：

**Comment by NiuGui8** [comment]
但是设置为null之后曲线就断开了 ， 想要的效果是即使设置为null ，也能将前后两个有数据的点连接起来，而不是曲线变成一小段一小段。

**Comment by Assur** [comment]
> 但是设置为null之后曲线就断开了 ， 想要的效果是即使设置为null ，也能将前后两个有数据的点连接起来，而不是曲线变成一小段一小段。

工业互联网趋势图，缺失数据空着更加合理，连起来就不能表示异常了
