### ISSUE TITLE
使用DataZoom组件拖动图表时，鼠标指针离开图表再次进入即使没有按下左键仍会跟着指针移动

### ISSUE THREAD

**Issue by marcong95** [apache/echarts#8604]
### One-line summary [问题简述]
使用DataZoom组件拖动图表时，鼠标指针在**按住左键状态下**离开图表再次进入即使没有按下左键仍会跟着指针移动

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: Chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
鼠标指针离开图表再次进入，在重新按下鼠标左键之前，图标不跟随鼠标指针移动

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

使用DataZoom的实例均可复现，如：
http://echarts.baidu.com/examples/editor.html?c=area-rainfall

**Comment by liushumei** [comment]
遇到同样的问题，求解决

**Comment by zwb910615** [comment]
有人知道怎么解决吗

**Comment by WangAngIOT** [comment]
同遇到，有什么解决办法吗

**Comment by FengHuangDong** [comment]
同遇到，有什么解决办法吗

**Comment by malinlin809** [comment]
同遇到，请问有什么解决办法么

**Comment by pissang** [comment]
最新版本应该不存在这个问题了
