### ISSUE TITLE
[Question] dynamic data - wiggling animation - series and/or axis update?

### ISSUE THREAD

**Issue by MarcMagnin** [apache/echarts#8636]
Hi,

Looking at the tutorial on dynamic data, I noticed an issue after about 5-6s:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=doc-example/tutorial-dynamic-data
We can see that the animation is getting a weird behavior probably related to this: 
https://bost.ocks.org/mike/path/
Any idea on how we can prevent this to happen? Not using `setOptions()` but directly manipulating the axis data?

As well I'm not sure to understand what's the best approach to deal with a timeserie. Our serie data is in the form of [[epoch_time,value]...] and I can set this fine to the option.series and just update the series object without touching the axis (with x axis type set to time). 
In the following example I can see that both series and axis data are updated: https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Dynamic.jsx
Is there is any advantage of one way or another? Only serie update is ok? Splitting the timestamp and the value onto the axis and manually updating them is faster?

Many thanks for your help!

**Comment by klausb** [comment]
I'm facing the same behavior. What is the trick to update the series data to get to the true sliding graph?
