### ISSUE TITLE
map3D dispatchAction mapSelect无效

### ISSUE THREAD

**Issue by elelvenliu** [apache/echarts#8639]
[问题简述]
chart series type是map3D时，选中地图版块无效，请问要怎么才能生效
chart.dispatchAction({
            type: 'mapSelect',
            name: '和田地区'
        })

**Comment by shunzizhan** [comment]
遇到同样的问题，不知道楼主解决没有

**Comment by fdandan** [comment]
遇到同样的问题+1，不知道楼主解决没有

**Comment by zhuoshengjie** [comment]
+1,是不是 map3d不支持dispatchAction
