### ISSUE TITLE
Listen to Mouse Events on the Grid Area

### ISSUE THREAD

**Issue by gkemp94** [apache/echarts#8644]
### One-line summary [问题简述]
Would it be possible to request a feature that allows the user to listen to all mouse events on a grid area, and retrieve the x/y value at that point, even if you're not hovering over an point/bar on the chart. 

We're trying to implement a feature where as you move the mouse across the chart, a text span underneath the chart is updated with statistics.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by LeonAlvarez** [comment]
+1 forthis feature

**Comment by pchaganti** [comment]
👍

**Comment by tmtron** [comment]
+1 - would be nice to have

**Comment by FengHuangDong** [comment]
+1
