### ISSUE TITLE
[enhancement]关于分组数据

### ISSUE THREAD

**Issue by appleskiller** [apache/echarts#865]
这是一点小期望：
我们知道，对于图表库来说，单系列渲染的是明细数据，多系列渲染的是分组数据，咱姑且叫它一级分组数据，依此，echarts可否有能力呈现二级分组数据呢？

当然，不能要求单个图表去实现如tableau一样有能力渲染无限级分组数据，但二级分组的需求还是常常碰到的，这方面，highcharts似乎有实现。因此希望echarts有所考量，简单实现。

（ps：比如增加series.categoryName字段用以区别相同series.name所在的不同组）

**Comment by ytzhangFTD** [comment]
麻烦问一下，这个问题有解决方案么，想学习下。
