### ISSUE TITLE
graph关系图，希望能够有多个label显示

### ISSUE THREAD

**Issue by houx15** [apache/echarts#8660]
graph中可以为每一个node设置其label，可以通过formatter来设置其内容以及样式，但是在有的情况下，我可能希望能够同时显示两个label，比如一个node的value以及其name，并且二者的位置、样式完全不同。
请问这种情况下，我可以通过rich的配置来实现功能吗，或者说，建议label可以接受数组？

**Comment by Yangjia23** [comment]
请问实现了嘛？ @houx15

**Comment by deqingli** [comment]
#11497
