### ISSUE TITLE
y轴刻度和折线的数值对不上

### ISSUE THREAD

**Issue by alvin198761** [apache/echarts#8662]
以官网链接为例：http://echarts.baidu.com/examples/editor.html?c=line-stack
这个是官网的链接， 明显可以看出，周日的数据：
搜索引擎是： 1320，但是显示的刻度是 2500 以上
联盟广告是： 300 ，却显示在 500的刻度上

我现在的问题跟官网例子一样，希望能给个方案

**Comment by qinyuling** [comment]
请问你解决了吗 我也遇到了同样的问题
