### ISSUE TITLE
漏斗图用dataset时，tooltip.formatter失效

### ISSUE THREAD

**Issue by tyyzqmf** [apache/echarts#8668]
### One-line summary [问题简述]
漏斗图用dataset时，tooltip.formatter失效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: firefox 6.1.0
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]
提示数据值{c}

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c}%"
    },
    legend: {},
    dataset: {
        source: [
            {value: 60, name: '访问'},
            {value: 40, name: '咨询'},
            {value: 20, name: '订单'},
            {value: 80, name: '点击'},
            {value: 100, name: '展现'}
        ]
      },
    series: [
        {
            type:'funnel',
        }
    ]
};

```

### Other comments [其他信息]

![echarts-bug](https://user-images.githubusercontent.com/18416040/42434829-1818ea68-8387-11e8-9540-cfc561b51646.png)

**Comment by tyyzqmf** [comment]
有人吗？帮帮忙呗~

**Comment by cuijian-dexter** [comment]
@tyyzqmf  You can see my pr.I hope it works for you.
https://github.com/apache/incubator-echarts/pull/9385
