### ISSUE TITLE
网站上gl实例加载不出来

### ISSUE THREAD

**Issue by WeiXOu** [apache/echarts#8669]
网站上gl实例加载不出来

**Comment by ayufish** [comment]
我也有同样的问题，7.10上午还可以，下午突然就刷不出来了

**Comment by liyongsennn** [comment]
一样。。。为什么啊，刷不出来

**Comment by pissang** [comment]
哪个实例？

**Comment by hsilence** [comment]
@pissang echarts.baidu.com 网站上有个‘实例’ 导航，‘实例’下有个‘gl实例’，
所有的gl实例，一直在加载中，就是加载不出数据，时好时坏

**Comment by liyongsennn** [comment]
通过这三天经验发现每天上午到下午四点左右之前是没问题的，但到傍晚就不行了

**Comment by Jet12138** [comment]
gl功能的，geo配置，不显示图形出来。
environment: './data3.jpg',  //地球的外部太空环境
            baseTexture: './data1.jpg',     //地球的纹理，这里用的山川河流
            heightTexture: './data2.jpg',   //地球的高度纹理，这里弃置

**Comment by Jet12138** [comment]
It had been resolved. I changed a GPU-better computer.
