### ISSUE TITLE
树状图在resize后，再次展开节点，节点的label以及symbol都无法显示

### ISSUE THREAD

**Issue by MUYUSY** [apache/echarts#8672]
### One-line summary [问题简述]
树状图在resize后，再次展开节点，节点的label以及symbol都无法显示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4
+ Browser version [浏览器类型和版本]:chrome 67.0.3396.99（FF同样有此问题）
+ OS Version [操作系统类型和版本]:Windows 10

### Expected behaviour [期望结果]
树状图在resize后能够正常使用。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

做了 个根据节点数目动态调整container的高度和宽度的功能，调整完后使用resize()，图像大小是动态调整了，但是收缩后再展开，子节点的symbol和label均不显示了，但是仍旧可以点击。
截图：
![image](https://user-images.githubusercontent.com/16941350/42488699-5ba1f9b6-8439-11e8-9d49-345a9627fd20.png)

**Comment by deqingli** [comment]
Please provide a demo for us to debug, since the `resize()` work normally on my computer.
