### ISSUE TITLE
使用document.createElement或使用Jquery$('div')这种方式创建的dom上初始化echart，双y轴的情况下，两个y轴会重叠

### ISSUE THREAD

**Issue by yangyifanNeu** [apache/echarts#8700]
### One-line summary [问题简述]
在一个悬空的dom（即调用document.createElement或使用Jquery$('div')这种方式创建的dom）上初始化echart，在调用完setoption之后，将节点append到页面上时，如果是双y轴的情况下，两个个y轴会重叠在一起。如下图：
![default](https://user-images.githubusercontent.com/28598717/42747051-472124ac-890d-11e8-9c80-ce3acb121a31.PNG)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4
+ Browser version [浏览器类型和版本]:chrome 66.0.3359.181（正式版本） （32 位）
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
option = {
      {"series":[],"animation":true,"title":{"text":"一周内温度降雨量统计"},"grid":{},"tooltip":{"trigger":"axis"},"legend":{"orient":"horizontal","show":true,"data":[]},"xAxis":[{"name":"日期","show":true,"type":"category","nameGap":30,"axisLabel":{"interval":0,"rotate":0}},{"show":false,"axisLine":{"onZero":false},"nameGap":30,"axisLabel":{"interval":0,"rotate":0}}],"yAxis":[{"name":"温度","show":true,"interval":10,"max":40,"min":0,"axisLabel":{},"axisLine":{},"axisTick":{},"type":"value"},{"interval":20,"max":80,"min":0,"name":"降雨量","show":true,"type":"value","axisLabel":{}}],"dataZoom":[{"show":false,"type":"slider"}]}
}

```

**Comment by jimoweicheng** [comment]
你怎解决这个问题的？
