### ISSUE TITLE
4.1 版本 splitLine 显示异常

### ISSUE THREAD

**Issue by panshuangqing** [apache/echarts#8709]
4.1 版本的 splitLine 有bug 不能够正常显示 

同样的配置 我用 3.x.x版本能正常显示
给下 配置 
option = {
    "legend": {
        "data": [
            "ActiveBug数",
            "总Bug数",
            "新增Bug数",
            "修复Bug数"
        ],
        "top": 25
    },
    "xAxis": {
        "type": "category",
        "data": [
            "2018-06-27",
            "2018-06-28",
            "2018-06-29",
            "2018-06-30",
            "2018-07-01",
            "2018-07-02",
            "2018-07-03",
            "2018-07-04",
            "2018-07-05",
            "2018-07-06",
            "2018-07-07",
            "2018-07-08",
            "2018-07-09",
            "2018-07-10",
            "2018-07-11\n上车日",
            "2018-07-12",
            "2018-07-13",
            "2018-07-14",
            "2018-07-15",
            "2018-07-16",
            "2018-07-17"
        ],
        "grid": {
            "y2": "100"
        },
        "axisTick": {
            "alignWithLabel": true
        },
        "axisLabel": {
            "rotate": "45"
        },
        "splitLine": {
            "show": true,
            "lineStyle": {
                "type": "dashed",
                "width": 2,
                "color": [
                    "black"
                ]
            },
            interval: function(index, value) {
                console.log(option.markLine);
                if (option.markLine !== null && option.markLine.indexOf(index) >= 0) {
                    return true;
                } 
                return false;
            }
        }
    },
    "": {
        "left": "center"
    },
    "title": {
        "left": "center",
        "text": "详细Topic版本质量",
        "fontSize": "12"
    },
    "toolbox": {
        "feature": {
            "saveAsImage": {}
        },
        "right": 30
    },
    "yAxis": [
        {
            "type": "value",
            "name": "数量",
            "axisLabel": {
                "formatter": "{value}"
            },
            "symbol": "none",
            "splitLine": {
                "show": false
            }
        }
    ],
    "series": [
        {
            "name": "ActiveBug数",
            "type": "line",
            "data": [
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                3,
                4,
                2,
                2,
                4,
                6,
                5,
                3,
                6,
                3,
                3,
                4,
                0,
                1
            ],
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "position": "top"
                    }
                }
            },
            "markLine": {
                "data": [],
                "symbol": [],
                "itemStyle": {
                    "normal": {
                        "lineStyle": {
                            "type": "dotted",
                            "color": "#000"
                        }
                    }
                }
            }
        },
        {
            "name": "总Bug数",
            "type": "line",
            "data": [
                "0",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "4",
                "5",
                "5",
                "5",
                "7",
                "13",
                "21",
                "20",
                "26",
                "32",
                "32",
                "33",
                "32",
                "33"
            ],
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "position": "top"
                    }
                }
            }
        },
        {
            "name": "新增Bug数",
            "type": "line",
            "data": [
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                2,
                1,
                0,
                0,
                2,
                9,
                4,
                1,
                5,
                4,
                0,
                0,
                2,
                1
            ],
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "position": "top"
                    }
                }
            }
        },
        {
            "name": "修复Bug数",
            "type": "bar",
            "data": [
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                4,
                9,
                1,
                3,
                8,
                0,
                0,
                4,
                0
            ],
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "position": "top"
                    }
                }
            }
        }
    ],
    "markLine": [
        14
    ]
}

**Comment by Ovilia** [comment]
建议整理一下代码格式，方便看清楚。我试了一下，去掉 interval 函数是能显示 splitLine 的，所以检查下 interval 函数是不是有问题吧~
