### ISSUE TITLE
Emphasis-label does not work for lines

### ISSUE THREAD

**Issue by juntan86** [apache/echarts#8721]
### One-line summary [问题简述]
Emphasis-label does not work for lines, for e.g. the label position cannot be set to 'top' or 'middle'. Also rich text cannot be properly applied in this situation.
This function has been tested and passed for other series types, like scatter, however it has been discovered that at least for lines it does not work.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.10
+ Browser version [浏览器类型和版本]: Chrome 67.0.3396.99
+ OS Version [操作系统类型和版本]: Win10

### Expected behaviour [期望结果]
Emphasis-label works for lines.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mzy2240** [comment]
Do find the same issue. It should be a easy fix.

**Comment by r-tanner-f** [comment]
Have the same issue on sunburst I believe

**Comment by thorsteinssonh** [comment]
same issue - latest minified version I downloaded.
Bascially itemStyle: {emphasis ...}   works but lineStyle: {emphasis: ...} has no effect
For lines lineStyle emphasis looks 100x prettier, so would be nice to have this.

Can revert to an older version to get this to work?
