### ISSUE TITLE
希望平行坐标系能增加维度拖拽功能

### ISSUE THREAD

**Issue by JohnnyZhangQiao** [apache/echarts#8728]
### 希望平行坐标系能增加维度拖拽功能
动态图：[plotly框架展示](https://s3-us-west-1.amazonaws.com/plotly-tutorials/plotly-documentation/images/python_parcoords_ex1.gif)

可以参考：[plotly](https://plot.ly/python/parallel-coordinates-plot/)

**Comment by Lijiaoa** [comment]
这个功能很强啊！团队有意向要支持吗？ @plainheart 
And @JohnnyZhangQiao , 请问这个issue有进展吗？
