### ISSUE TITLE
如何设置地图整体呈现渐变色而不是区域一块接着一块呈现渐变，官网好像没有讲到，所用版本为echarts 3.85

### ISSUE THREAD

**Issue by zhilizhui** [apache/echarts#8734]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hsilence** [comment]
要怎么设置才能让整个地图从上往下颜色渐变，怎么没人回答呢
