### ISSUE TITLE
MarkPoint里面设置coord之后，就没有label内容显示了。设置type: min/max, 可以显示数据 

### ISSUE THREAD

**Issue by everglow1** [apache/echarts#8740]
### One-line summary [问题简述]

在series中设置标注MarkPoint， 使用coord确定标注的坐标，标注里面没有文本。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:windows 7

### Expected behaviour [期望结果]

这好像是个bug啊。我用几个例子都测了。series中MarkPoint设置coord之后就没有文本内容了

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by rong4620** [comment]
最近試著從ECharts 版本 3.6.2 升到 4.0、4.1.0rc2 也有發生此問題
建立一個bar圖  axis.type 設為 'category' 
 x軸資料設定為日期字串如 '2018/07/23' ,  '2018/07/24' , '2018/07/25'
 markPoint: { 
            data: [{"coord":["2018/07/23",84.61]},
                      {"coord":["2018/07/24",84.61]},
                      {"coord":"2018/07/25",38.98]}],
            label: {
                position: 'top',
                fontSize: 14,
                color: '#000'
            },
        }
結果無法顯示markPoint label內容

**Comment by 2014guai** [comment]
```
data: [
            {coord: [0, 22], value: 22},
            {coord: [1, 33], value: 33},
            {coord: [2, 44], value: 44},
            {coord: [3, 44], value: 44},
        ],
```
前面位置，后面值。

**Comment by tomastong** [comment]
@2014guai  是这样的，解决了，点个赞
