### ISSUE TITLE
Does echart4 support chord with ribbon?

### ISSUE THREAD

**Issue by linxingyun** [apache/echarts#8743]
### One-line summary [问题简述]
As checked the demo/echarts-examples for echart3/echart4, there is no any demo of ribbon chord. 
I found echart2 has demo on supporting ribbon chord.  But the demo code from echart2 cannot work in echart3/echart4.
So I got question on whether echart4 can support the ribbon chord diagram? If yes, could you please help to provide a demo to demonstrate it? Thank you so much!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DmitryMaksakov** [comment]
I've got the same question. Chords are very commonly used chart, so having it in ECharts will be very helpful!

**Comment by sjcobb** [comment]
This may be what you're looking for: https://echarts.apache.org/examples/en/editor.html?c=graph-circular-layout

**Comment by iamflowerdog** [comment]
I've got the same question, I had a solution to support ribbon chord.

you could import chord after import echarts:
`import * as echarts from 'echarts';
import 'echarts/lib/chart/chord'`
 but there is anther question I met, the tooltips was gone.

**Comment by ataft** [comment]
Any updates on chords for version 5?

I see that issue https://github.com/apache/echarts/issues/10098 is requesting the same...
