### ISSUE TITLE
legend  can not  rotate

### ISSUE THREAD

**Issue by swwinone** [apache/echarts#8777]
### One-line summary [问题简述]

legend text can not rotate

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: all
+ Browser version [浏览器类型和版本]:all
+ OS Version [操作系统类型和版本]:all 

### ECharts option [ECharts配置项]

```javascript
option = {
 legend: {
        type: 'scroll',
        orient: 'vertical',
        right: 10,
        top: 20,
        bottom: 20,
        data: data.legendData,

        selected: data.selected,
        textStyle:{
                rich:{
                    a:{
                        fontSize:20,
                        verticalAlign:'top',
                        align:'center',
                        padding:[0,0,28,0],
                        rotate: 90,
                    },
                }
    },
    },
    formatter: function (name) {
    return '{a|' + name +"}";
    },
}

```
![1532937736192-image](https://user-images.githubusercontent.com/24319059/43384980-272d6e48-9412-11e8-8025-f5006e4c1407.png)

**Comment by Ovilia** [comment]
Hi swwinone, I would like to make sure, in which case is this necessary? Because I don't think it a good idea to rotate the text in that the readability is decreased.

**Comment by swwinone** [comment]
First, I use echatrs on the phone page. To achieve the full-screen feel of the line chart, I rotated the entire echarts diagram, and other options could be rotated, but only legend could not rotate.
![1533562028329-image](https://user-images.githubusercontent.com/24319059/43719201-a8760318-99bf-11e8-9bcc-491bc385ab59.png)

**Comment by Ovilia** [comment]
That makes sense. Let's see if we can provide an option for it.

**Comment by seawenzhu** [comment]
is there any fix for this?

**Comment by wei-xiaomeng** [comment]
Hello, has this problem been solved? I also met. Can you tell me how to solve it?

**Comment by susiwen8** [comment]
Sorry for this delay, a solution has been proposed, but It needs future development, something needs to enhance

**Comment by szu-bee** [comment]
I just do like this:
```js
      legend: {
        icon: 'none',
        formatter: (name) => {
          const verticalName = name.split('').join('\n')
          const arr = [`{a|${verticalName}}`]
          return arr.join('\n')
        },
        textStyle: {
          rich : {
            a: {
              lineHeight: 20,
            }
          }
        },
      },
```

**Comment by wozien** [comment]
is there any fix for this?

**Comment by susiwen8** [comment]
I think html is the best way to do this,

**Comment by wozien** [comment]
> I think html is the best way to do this,

i use css transform to rotate parent dom, but it not work in minapp, like weapp

**Comment by wozien** [comment]
so i think it may be can set rotate property with per compoent, link axis, tooltip, lengend

**Comment by susiwen8** [comment]
What I propose is that use somting like `<div>`  to create custom legend, in miniprogram is `<view>`

**Comment by wozien** [comment]
> What I propose is that use somting like `<div>` to create custom legend, in miniprogram is `<view>`

I will try. thanks guy. 👍🏻
