### ISSUE TITLE
Tree tooltip 存在的问题。

### ISSUE THREAD

**Issue by simonguo** [apache/echarts#8800]
![image](https://user-images.githubusercontent.com/1203827/43562354-a284f74e-964e-11e8-8fab-9905d0b700e3.png)

Tree 节点 hover 时候默认显示 整个 path 路径， 但是， tooltip 定制 formatter 的回调函数中没有对应的 path ， 只有当前节点信息。

**Comment by Ovilia** [comment]
代码链接？http://gallery.echartsjs.com/editor.html

**Comment by wuyuw** [comment]
同样的问题，解决了吗
