### ISSUE TITLE
Emphasis on ItemStyle not working properly

### ISSUE THREAD

**Issue by nick-voisin** [apache/echarts#8810]
### One-line summary [问题简述]
If in emphasis, you set a border color, you have to hover over the border to see the color.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 67.0.3396.99
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
I think the intended use, was to hover over the node, just like the color or shadow property, in order to change borderColor. Just like in:  https://finviz.com/map.ashx

### ECharts option [ECharts配置项]

```javascript
			option = {
				series: [{
						name: "TreeMap",
						type:'treemap',
						data: oData[0].children,
						visibleMin: 300,
						levels: this.configureLevels(),                                    
						label: this.configureLabel(),
						upperLabel :this.configureUpperLabel(),
						breadcrumb : {top: 10},
						itemStyle: {
							normal: {
								borderColor : "lightsteelgrey",
								borderWidth : 2
							},
							emphasis: {
								borderColor : "yellow",
								borderWidth : 2
							}
						}
				}]
			
``
### Other comments [其他信息]
<!-- For example: Screenshot or Online demo -->
<!-- [例如，截图或线上实例 (JSFiddle/JSBin/Codepen)] -->

**Comment by Ovilia** [comment]
Thanks for your advice. I think this totally makes sense.
We will fix it later.

**Comment by Skullnick** [comment]
Any update ?

**Comment by sherifsarhanf9g** [comment]
Will this be fixed any time soon? this seems like a big oversight. @Ovilia
