### ISSUE TITLE
Add dispatchAction of type: 'treemapZoomToNode' to treemap

### ISSUE THREAD

**Issue by nick-voisin** [apache/echarts#8815]
### One-line summary [问题简述]

Would it be possible to add a dispatchAction 'treemapZoomToNode' to treemap ? Just like highlight :

dispatchAction({
    type: 'treemapZoomToNode',
    // optional; series index; could be an array of multiple series
    seriesIndex?: number|Array,
    // optional; series name; could be an array of multiple series
    seriesName?: string|Array,
    // options are index of data
    dataIndex?: number,
    // options are data name
    name?: string
})

If not, where can I code it ? Right now it's a private function in TreemapView.js under : 

    /**
     * @private
     */
    _zoomToNode: function (targetInfo) {
        this.api.dispatchAction({
            type: 'treemapZoomToNode',
            from: this.uid,
            seriesId: this.seriesModel.id,
            targetNode: targetInfo.node
        });
    }

Thanks for your help !

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 68.0.3440.84
+ OS Version [操作系统类型和版本]: Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Skullnick** [comment]
I'm not sure this is the intended use by I added the following function in echarts.js in the treemap section, under the render function : 
`    /**
     * @override
     */
    highlight: function (seriesModel, ecModel, api, payload) {
        var targetInfo;        var targetInfo;
        var viewRoot = seriesModel.getViewRoot();

        viewRoot.eachNode({attr: 'viewChildren', order: 'preorder'}, function (node) {
            var bgEl = this._storage.background[node.getRawIndex()];
            if (bgEl) 
            {
                if(payload.name === node.name)          
                    targetInfo = {node: node};
                
            }
        }, this);

        if(payload.name !== "")      
            this._zoomToNode(targetInfo);
    }`

I then called a dispatchAction of type 'highlight' like the following : 
curChart.dispatchAction({type: 'highlight', name: sName});

It does the job but I'm sure you could implement something cleaner :)

**Comment by Skullnick** [comment]
Could this be added please ? On each new update I have to insert this function.

**Comment by w0lv3r1nix** [comment]
> I'm not sure this is the intended use by I added the following function in echarts.js in the treemap section, under the render function :
> 
> ```
> /**
> * @override
> */
>     highlight: function (seriesModel, ecModel, api, payload) {
>         var targetInfo;        var targetInfo;
>         var viewRoot = seriesModel.getViewRoot();
> 
>         viewRoot.eachNode({attr: 'viewChildren', order: 'preorder'}, function (node) {
>             var bgEl = this._storage.background[node.getRawIndex()];
>             if (bgEl) 
>             {
>                 if(payload.name === node.name)          
>                     targetInfo = {node: node};
>                 
>             }
>         }, this);
> 
>         if(payload.name !== "")      
>             this._zoomToNode(targetInfo);
>     }
> ```
> I then called a dispatchAction of type 'highlight' like the following :
> `myChart.dispatchAction({type: 'highlight', name: sName});`
> 
> It does the job but I'm sure you could implement something cleaner :)

I'm sorry, where did you add the highlight code? Couldn't find highlight option in treemap.
