### ISSUE TITLE
x轴和y轴处不应该画分隔线splitLine

### ISSUE THREAD

**Issue by yangdan8** [apache/echarts#8843]
### One-line summary [问题简述]

设置yAxis.splitLine.lineStyle.type=dotted明显见到底部有条虚线,
靠近x轴和y轴这里不应该画分隔线splitLine才正确

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
不太理解底部有虚线是什么意思，可以截图说明吗？

**Comment by yangdan8** [comment]
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        splitLine: {
            show: true,
            lineStyle: {
                width: 5,
                color: ['green']
            }
        }
    },
    yAxis: {
        type: 'value',
        splitLine: {
            show: true,
            lineStyle: {
                width: 5,
                color: ['green']
            }
        }
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true
    }]
};

**Comment by yangdan8** [comment]
![qq 20180817132704](https://user-images.githubusercontent.com/16515026/44249161-46c90600-a221-11e8-8d04-aa88aea2a8f0.png)
x 轴和y轴都看不到了,这里是否不应该画分隔线?

**Comment by 100pah** [comment]
@yangdan8 在上面图片的这里例子中，如果 x 轴 y 轴处的 splitLine 不绘制，只有轴的细黑线，看起来并不是很协调。
如果 splitLine 是个”很强“ 的样式的话，是不是要设置成，xAxis yAxis 不显示呢？

**Comment by yangdirun** [comment]
设计图：![image](https://github.com/apache/echarts/assets/105510326/ea6ebfe7-556c-493e-a671-d99ba7608172)
我写的页面
![image](https://github.com/apache/echarts/assets/105510326/cab64da4-1878-4194-8f36-f696dad05e35)
x轴看起来是是虚线 没法还原设计图

**Comment by yangdirun** [comment]
> 设计图：![image](https://private-user-images.githubusercontent.com/105510326/331753333-ea6ebfe7-556c-493e-a671-d99ba7608172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTI4MzksIm5iZiI6MTcxNTk5MjUzOSwicGF0aCI6Ii8xMDU1MTAzMjYvMzMxNzUzMzMzLWVhNmViZmU3LTU1NmMtNDkzZS1hNjcxLWQ5OWJhNzYwODE3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwMDM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTVjN2I4OTM1OGRkYzY5ZjU0MDA0MWM5ZmRjNGIyYjk5YjlhZmI0NjhhNzg2MThmZmVmNGQwZTNkZDdhN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mAZUmjgspYGjFdHZX3rFvgXiQfqxptTerxVZrt2cY58) 我写的页面 ![image](https://private-user-images.githubusercontent.com/105510326/331753382-cab64da4-1878-4194-8f36-f696dad05e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTI4MzksIm5iZiI6MTcxNTk5MjUzOSwicGF0aCI6Ii8xMDU1MTAzMjYvMzMxNzUzMzgyLWNhYjY0ZGE0LTE4NzgtNDE5NC04ZjM2LWY2OTZkYWQwNWUzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwMDM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTQzM2UwYTI2ODU2ZDg1YzlkMjFlNGNiODQ2OGQ4NzVmOTFiMzQ3ZGY5ZTY5NWFlYTMzNDQyMGY2NWZmNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FVLEdUCj24dSRcu9CZpEgoMFoac1sw8nzjUu4FjlQeQ) x轴看起来是是虚线 没法还原设计图

@Ovilia

**Comment by shenxiang216** [comment]
七年了，这个问题依旧存在吗？
