### ISSUE TITLE
geo.regions[i].label.formatter， geo.regions[i].label.position 设置无效

### ISSUE THREAD

**Issue by aweffr** [apache/echarts#8852]
### One-line summary [问题简述]
geo.regions[i].label.formatter
geo.regions[i].label.position
geo.regions[i].label.fontWeight
以上三个配置项赋值没有效果。

geo.regions[i].label.show的设置有效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.3 , 4.1.0 均有此问题
+ Browser version [浏览器类型和版本]:  Chrome V67
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
期望输出:

世界地图上中国图形标注为加粗的"**SHOULD BE HELLO WORLD**"而不是默认的"China"。

![pic](https://github.com/aweffr/echart-sandbox/raw/master/snapshot.png)

### ECharts option [ECharts配置项]

```javascript
const option = {
  title: {show: false},
  geo: {
    show: true,
    type: 'map',
    map: 'world',
    regions: [
      {
        name: 'China',
        label: {
          show: true,
          position: 'top',
          formatter: function () {
            return 'SHOULD BE HELLO WORLD'
          },
          fontWeight: 'bolder',
        },
        value: +0.14,
      },
    ]
  },
};

```

### Other comments [其他信息]

我做了一个小实例在 https://github.com/aweffr/echart-sandbox

**Comment by aweffr** [comment]
geo.regions[i].label.position 我按文档尝试了多个值，也没有用。

我还试过formatter函数里加console.log,发现这个函数始终没有被调用过。

**Comment by Pancho2wang** [comment]
我也碰到没有效果
position可以用padding去调整位置
formatter还没找到方法
