### ISSUE TITLE
v4.1.0 datazoom 'toFixed of null' error

### ISSUE THREAD

**Issue by wangyx233** [apache/echarts#8862]
### One-line summary [问题简述]

3.8.5版本切换到4.1.0时有报错‘TypeError: Cannot read property 'toFixed' of null’。排查后发现，xAxis的data为[],而datazoom的startValue，endValue为string类型的值时会触发。3.8.5版本则无报错。
现在是给xAxis的data赋值后，再设置datazoom的startValue和endValue可以避免这个问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Chrome 版本 68.0.3440.84（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: macOS High Sierra 10.13.3

### Expected behaviour [期望结果]

良好的向下兼容性~

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: []
    },
    yAxis: {
        type: 'value',
        data: []
    },
    dataZoom: [
        {
            type: 'slider',
            show: true,
            xAxisIndex: [0],
            startValue: '1日',
            endValue: '5日'
        },
    ],
    series: [
        {
            name: 'test',
            type: 'line',
            data: []
        },
    ]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/16773666/44020092-58104d44-9f13-11e8-93a3-0ed75b520133.png)
对照3.8.5版本的代码，valueWindow->[-1,-1]
![image](https://user-images.githubusercontent.com/16773666/44020194-b969208e-9f13-11e8-8e4e-525a004d2a0b.png)
4.1.0：valueWindow->[null,null] 所以有上述报错。
![image](https://user-images.githubusercontent.com/16773666/44020382-4d0207fc-9f14-11e8-8773-35968b683464.png)

**Comment by keqingrong** [comment]
#8490

**Comment by superllmin** [comment]
+1
