### ISSUE TITLE
请问如何让visual map和地图配合的时候，动态的让visual map的hover颜色也根据数据映射到某个数据区间

### ISSUE THREAD

**Issue by zhanzekun** [apache/echarts#8866]
### One-line summary [问题简述]
如何让配合map类型的visualMap组件的hover色 也根据数据映射到某个颜色区间？
现在的hover色是由series - emphasis -itemStyles - areaColor 决定的，可是文档中这个地方只支持字符串写死…这个有办法吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.3
+ Browser version [浏览器类型和版本]: Chrome最新版本
+ OS Version [操作系统类型和版本]: win10 pro

### Expected behaviour [期望结果]
希望鼠标hover到地图上时，hover高亮色也是根据数据映射到某个颜色区间

### ECharts option [ECharts配置项]

```javascript
option = {
   visualMap: [{
		show: false,
		max: 100
		min: 1
		left: 'left',
		top: 'bottom',
		text: ['高', '低']
		textStyle: {
		    color: "#8F909E"
		},
		seriesIndex: 0,
		calculable: true,
		inRange: {
		    color: [ '#EDF0FF','#849EFF']
		},
      series: [
		{
		        top:'5%',
		        left:'15%',
			right:'18%',
			bottom:'5%',
			name: 'temp',
			type: 'map',
			mapType: 'china',
			roam: false,
			label: {
				normal: {
					show: false
				 },
			       emphasis: {
				        show: false
			         }
			},
			emphasis: {
				itemStyle: {
					areaColor: '#cdcdcd'
				}
			},
			data:data
				}
			]
};

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17589129/44069086-d24264fc-9faf-11e8-9022-68639edd5ee6.png)

**Comment by zhanzekun** [comment]
内蒙古hover态这个灰色就是我自己设置的，如果我不设置默认是黄色…我希望它也能是一个用数据映射到颜色区间的样子，有办法吗

**Comment by seminelee** [comment]
``` js
itemStyle: {
  emphasis: {
     areaColor: null
  }  
}
```
According to  #[3173](https://github.com/apache/incubator-echarts/issues/3173)

**Comment by KrzysztofMadejski** [comment]
1. `areaColor: null` behavior should be documented. 
  It works if placed under `series.emphasis`

            series: [
            {
                name: '香港18区人口密度',
                mapType: 'HK', // 自定义扩展图表类型
                emphasis: {
                    itemStyle: {
                      shadowColor: 'black',
                      shadowBlur: 5,
                      areaColor: null
                    }
                },
2. Does not work if placed under https://echarts.apache.org/en/option.html#geo.emphasis.itemStyle.areaColor
    Shadow can be seen, but areaColor is `yellow` still

        geo: {
            emphasis: {
                itemStyle: {
                  shadowColor: 'black',
                  shadowBlur: 5,
                  areaColor: null
                }
            }, 
            map: 'HK'
         },
         series: [
            {
                name: '香港18区人口密度',

3. I'd expect full transparency to work using below code. Also with non-zero opacity to get a shading of the color below.

            series: [
            {
                name: '香港18区人口密度',
                emphasis: {
                    itemStyle: {
                      shadowColor: 'black',
                      shadowBlur: 5,
                      areaColor: '#ffffff00'
                    }
                },

**Comment by JoenZhu** [comment]
any update?
