### ISSUE TITLE
异步加载的数据无预期的动画效果

### ISSUE THREAD

**Issue by WhiteMinds** [apache/echarts#8891]
### One-line summary [问题简述]
一个线性图表, 初始数据[1, 2, 3]会正常的出现动画效果, 2秒后异步追加数据[4, 5, 6], 会是直接出现的, 而不是动画

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.1.0.rc2
+ Browser version [浏览器类型和版本]:chrome 68.0.3440.84  64bit
+ OS Version [操作系统类型和版本]:macos 64bit

### Expected behaviour [期望结果]
和初始数据一样使用动画效果过度加载

### ECharts option [ECharts配置项]

```javascript
data = [4, 5, 6]
option = {
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {
      type: 'value'
    },
    series: [{
      data: data,
      type: 'line',
      smooth: true
    }]
}

// 这里是追加数据时的代码 (也使用appendData尝试过, 效果一样)
setTimeout(function () {
   data.push.apply(data, [1, 2, 3])
   chart.setOption(option)
}, 2000)
```

### Other comments [其他信息]

http://gallery.echartsjs.com/editor.html?c=xHyaYJ-r8Q

**Comment by Ovilia** [comment]
有动画啊：http://gallery.echartsjs.com/editor.html?c=xS1ED_ZEI7&v=1 你 ECharts 版本是？

**Comment by WhiteMinds** [comment]
@Ovilia 啊实在不好意思, 例子给反了, 是初始为456, 追加123, 这样才能看出效果..

**Comment by biggerthan** [comment]
远古问题啊, 请问解决了吗, 我把issue都翻到这里了

**Comment by Ovilia** [comment]
@biggerthan 欢迎提 PR，或者等我们在 4.6.0 版本看看这个问题。

**Comment by pissang** [comment]
折线图对于新加的数据点目前是没有过渡动画的

**Comment by jigaoquan** [comment]
2021年了，这个问题解决了吗？

**Comment by ChiaSang** [comment]
同问是否解决了
