### ISSUE TITLE
options.title.textStyle properties don't work

### ISSUE THREAD

**Issue by eliashdezr** [apache/echarts#8897]
### One-line summary [问题简述]
I'm trying to center the title text and doesn't work.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.1.0
+ Browser version [浏览器类型和版本]: Chrome v68
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
Title should be centered

### ECharts option [ECharts配置项]

```javascript
option = {
    title:{
        text: 'Title should be centered',
        textStyle: {
            align: 'center'
        }
    },
    series: [
        {
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 60, name: ''}]
        }
    ]
};
```

http://echarts.baidu.com/examples/editor.html?c=gauge-car

**Comment by DiegooChen** [comment]
Use `left:'center'` instead, although its very strange, I believe it was the old version code that work but echart help documents updated.



`title: {
          text:'Title should be centered',
          left:'center',
        },
`
