### ISSUE TITLE
Sunburst with defined levels has weird behavior when drill down

### ISSUE THREAD

**Issue by yingxu9871** [apache/echarts#8907]
### One-line summary [问题简述]

可以用 sunburst demo 重现问题： http://echarts.baidu.com/examples/editor.html?c=sunburst-book,
1. 点击"心理" 节点下钻,  
2.再点击中心节点到达上一层级“非虚构”，
3. 无中心节点返回上一层，且出现怪异黄色色块， (应该是中心节点被遮挡，露出部分黄色色块)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

no weird behavior when drilled down and go back to the upper level. 

### Other comments [其他信息]

1. 点击"心理" 节点下钻后.再点击中心节点
![image](https://user-images.githubusercontent.com/28331441/44378249-0d4f0e00-a533-11e8-8933-129ff0eace22.png)
2. 到达上一层级“非虚构”，现怪异黄色色块，且无中心节点返回上一层
![image](https://user-images.githubusercontent.com/28331441/44378286-44bdba80-a533-11e8-8cdf-d771ce8627fb.png)

**Comment by yingxu9871** [comment]
这个问题可以稳定复现， 它的严重行在于，在最后一张图的状态，由于“无中心节点”， 客户无法返回上层节点“虚构”/"非虚构"， 给人的感觉是卡死了。 其实是“”非虚构“”遮挡住了“中心节点”。

**Comment by yingxu9871** [comment]
sorry, close by mistake.

**Comment by sBhaskar20** [comment]
Any progress on this? This is a blocker for us in terms of sunburst adoption in our product.
