### ISSUE TITLE
在饼图个数不确定的时候如何设置center和radius确保大小和间距自适应

### ISSUE THREAD

**Issue by cyh41** [apache/echarts#8930]
### One-line summary [问题简述]
饼图的数据是循环出来的，不确定饼图的具体个数。
如何设置 center 和radius，保证不同个数的饼图在当前面板（面板可设置全屏）都能够正确大小显示
类似 justify-content:space-around

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
        const seriesArr = this.queryMeasHeader.map((name, i) => {
          return {
            name: name,
            type: "pie",
            selectedMode: "single",
            radius:[]//TODO
            center:[]//TODO
            label: {
              normal: {
                position: "inner"
              }
            },
            labelLine: {
              normal: {
                show: false
              }
            },
            data: seriesData[i]
          }
        })
}

```

**Comment by Ovilia** [comment]
setOption 的时候你已经知道图表个数了吧，这时候可以对不同个数设置不同的 radius 和位置

**Comment by cyh41** [comment]
那这样不能设置公共的方法。只能写几种情况。数量为1设置一种，数量为2设置一种，以此类推...

**Comment by cyh41** [comment]
@Ovilia 那这样不能设置公共的方法。只能写几种情况。如果数量为1设置一种，数量为2设置一种，以此类推...

**Comment by zzjzz9266a** [comment]
> @Ovilia 那这样不能设置公共的方法。只能写几种情况。如果数量为1设置一种，数量为2设置一种，以此类推...

如果数量很多的时候，不确定哪一部分的密度最高，出现大量的label堆叠的情况怎么办。。
![image](https://user-images.githubusercontent.com/17211710/60379772-4b7a5f80-9a6b-11e9-8bc4-8725042fd10e.png)
