### ISSUE TITLE
Add Datazoom cursor options / locations

### ISSUE THREAD

**Issue by tstearncascade** [apache/echarts#8936]
###One-line summary:

It would be helpful to have cursor options for Datazoom. Different cursor behaviour depending on where the user mouseovers or if the user is grabbing/dragging the datazoom. 

### Version & Environment
ECharts version [ECharts 版本]: 4.1.0

### Expected behaviour [期望结果]

For example, echarts could have the option to use the grab/grabbing css cursors when hovering over the middle of the zoom bar, to show the user that they can grab and drag.

Currently the only cursor appears to be the 'resize' cursor, whether mouseover is on the datazoom handle or on the main bar.

### Other comments [其他信息]

Mouseover centre zoom bar:

![image](https://user-images.githubusercontent.com/35701170/44538657-edb61200-a6f9-11e8-942f-95faad364320.png)

Grabbing and dragging centre zoom bar:

![image](https://user-images.githubusercontent.com/35701170/44539185-67023480-a6fb-11e8-87b8-1bd4c791493e.png)

**Comment by james-mint** [comment]
is there any update on this?

**Comment by wind-liang** [comment]
is there any update on this?

**Comment by luccabimachine** [comment]
+1

**Comment by Krknv** [comment]
+1

**Comment by razibutt01** [comment]
any update on this?
