### ISSUE TITLE
dataset source 为对象数组时候是不是不支持 series.seriesLayoutBy？

### ISSUE THREAD

**Issue by aiingstan** [apache/echarts#8969]
### One-line summary [问题简述]
我参照 [官方示例](http://www.echartsjs.com/gallery/editor.html?c=dataset-series-layout-by) 中的代码，把 `source` 变成 `JSON` (试过对象数组和 `JSON`，都是可以渲染的) 以后，无法实现原先的改变行、列的效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]: Firefox 61.0.2
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]

`source` 使用对象数组能够达到和示例二维数据表一样的可以置换行、列显示的效果

### ECharts option [ECharts配置项]

```javascript
option = {
  // 除了 dataset，其余部分和官网示例一样
  dataset: {
        dimensions: ['product', '2012', '2013', '2014', '2015'],
        source: [{"2012":"41.1","2013":"30.4","2014":"65.1","2015":"53.3","product":"Matcha Latte"},{"2012":"86.5","2013":"92.1","2014":"85.7","2015":"83.1","product":"Milk Tea"},{"2012":"24.1","2013":"67.2","2014":"79.5","2015":"86.4","product":"Cheese Cocoa"}]
    }
}

```

**Comment by junh2017** [comment]
我也遇到了这个问题！

**Comment by aperyx** [comment]
我也遇到了这个问题！
