### ISSUE TITLE
echarts有没有考虑出服务器端的sdk

### ISSUE THREAD

**Issue by marinesky** [apache/echarts#898]
echarts有没有考虑出个服务器端的sdk,因为前端的有些功能在某些浏览器上使用不了,比如那个保存图片在IE8下用不了,只有在服务端弄,但服务端没有echarts,如果用jfreechart生成的风格又不太一样了,不知道怎么解决这个问题

**Comment by xiaomaiyun** [comment]
参考这个 https://github.com/xiaomaigou/echarts-export-server
