### ISSUE TITLE
Inversing font color  of gouge scale 

### ISSUE THREAD

**Issue by vcardeal** [apache/echarts#9011]
### One-line summary [问题简述]

Hi everyone, I'm facing a issue with font number scale. when i put clockwise false the interval of colors is right but the font get inverses color. any ideia how to solve?

(https://user-images.githubusercontent.com/30213232/45057890-504dcd00-b06d-11e8-8332-06498542370e.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Please provide code to reproduce this.

**Comment by aminzabardast** [comment]
Here is the options that creates the issue:
Setting `clockwise` to false does not effect `axisLine`
```
option = {
    series: [
        {
            clockwise:false,
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50}]
        }
    ]
};
```

**Comment by Ovilia** [comment]
@aminzabardast OK. I'll look into it.

**Comment by Ovilia** [comment]
It seems to be fixed.
