### ISSUE TITLE
focusNodeAdjacency可否支持整条链路的高亮，高亮至dataIndex为0的root node

### ISSUE THREAD

**Issue by laoxubuer** [apache/echarts#9013]
### One-line summary [问题简述]
focusNodeAdjacency可否支持整条链路的高亮，高亮至dataIndex为0的root node，如下图，选中蓝色节点后，高亮整个链路上的node和edge

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 
+ Browser version [浏览器类型和版本]: 
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
直接支持这类特性或者是否有什么委婉的方式可以实现？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![xxm98 pg _b7m2ct2yv1r7](https://user-images.githubusercontent.com/7135991/45071901-1501db80-b10b-11e8-83ff-d0a0891c5cbe.png)

**Comment by 100pah** [comment]
目前还不支持。如果链路全高亮，会不会很容易就，整个图表全都高亮了？

**Comment by laoxubuer** [comment]
如果关系是多链路的而不是单线的，的确很容易都亮了。之前考虑dipatchAction 执行多个focusNodeAdjacency，但是似乎这个事件的特性就是高亮当前节点和相邻节点，然后其他节点变暗，那么实际上完全同步的情况下，用户只会看到执行的最后那一下。

如果支持传入数组，是否就能精确得指定哪些节点需要高亮，然后同时高亮其相邻节点。

**Comment by 100pah** [comment]
> 如果支持传入数组，是否就能精确得指定哪些节点需要高亮，然后同时高亮其相邻节点。

感觉有道理。考虑支持下这种场景。

**Comment by ilovepumpkin** [comment]
同意！如果focusNodeAdjacency action能够支持传node的dataIndex的数组或者edge的dataIndex数组，那用户就可以自己指定highlight那些，这样比较灵活
