### ISSUE TITLE
力学导向图无法在nodes中设置节点颜色

### ISSUE THREAD

**Issue by bigjoy** [apache/echarts#902]
看文档中的力学导向图示例的缩略图应该是可以给node设置不同的颜色的，但是示例中却只有一个一种颜色。试着在nodes中设置不同的itemStyle，但是很明显nodeStyle里的color并没有生效，依然没办法修改node颜色，请问是不是新版本把该设置关闭了？如果要定制node的颜色应该如何设置呢?

**Comment by pissang** [comment]
试了一下也可以，单个节点上是 itemStyle.emphasis.borderWidth, 没有 nodeStyle 了
