### ISSUE TITLE
旭日图能设置初始显示几层数据吗？

### ISSUE THREAD

**Issue by Dogtiti** [apache/echarts#9021]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0
+ Browser version [浏览器类型和版本]:Chrome 68
+ OS Version [操作系统类型和版本]:macOS 10.13.6

### Expected behaviour [期望结果]

能不能只是我点击之后进入到下一级，而在初始化的时候不显示其他子集内容，只显示父级内容

![image](https://user-images.githubusercontent.com/38354472/45142753-e14ab280-b1eb-11e8-8eed-dc28593b3609.png)
===========》》》

![image](https://user-images.githubusercontent.com/38354472/45142800-050df880-b1ec-11e8-94e0-f4eb53e35dc2.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://www.echartsjs.com/gallery/editor.html?c=sunburst-drink

**Comment by DidoFitch** [comment]
你好，请问进度如何？项目中有此需求，全部显示的话最外层数据太多，需求提出默认显示父级，点击再加载
