### ISSUE TITLE
Y轴刻度自定义和X轴文字显示不全

### ISSUE THREAD

**Issue by sandyfog** [apache/echarts#906]
![image](https://cloud.githubusercontent.com/assets/3823038/5083742/3c5c799e-6f36-11e4-9b82-a09b649bb6c6.png)

Y轴刻度自定义是否可以自定义，如上图所示：其中一项特别多，导致其他项显示不了
X轴文字显示不全的问题，当X轴文字太长是会出现这个问题，请问如何解决。

**Comment by huzemin** [comment]
可以使用option中的grid进行设置。
```javascript
option = {
 grid:{
     x: 150
 }
}
```

**Comment by Baby123xi** [comment]
I think it has some wrong here...
