### ISSUE TITLE
singleAxis series unable to use function for SymbolOffset

### ISSUE THREAD

**Issue by ghost** [apache/echarts#9083]
### One-line summary [问题简述]

We are able to set a function for the symbolSize under a singleAxis series, but we cannot
set a function for the symbolOffset. Please fix this, it would be very handy to use the symbolOffset.

Thank you.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
What series do you use?

**Comment by civilwarrock** [comment]
I was using the Scatter series. Love it by the way. Another feature I would love to have if possible is a background color behind the series. We can set height and width, so it would be awesome to place a background color behind the series without having to use a grid. Thanks!

**Comment by pissang** [comment]
You can try the `markArea` component to highlight the zone with a background color
