### ISSUE TITLE
Dynamically show/hide labels on zoom in/out

### ISSUE THREAD

**Issue by sethwilsonUS** [apache/echarts#9086]
Hello,

I'm using eCharts for network graphs. As part of each node, I have the following code:

`node.label = {
  normal: {
    show: node.symbolSize > 30
  }
};`

I would like to have this change dynamically as the user zooms in/out to show/hide more labels. I've looked at the event documentation, but can't seem to figure out how to do this. Thanks for your help.

**Comment by dsamoylov** [comment]
Hello, any news on that one? That feature is really needed.

**Comment by deqingli** [comment]
#11497
