### ISSUE TITLE
moveOnMouseWheel 不起作用啊

### ISSUE THREAD

**Issue by southwhale** [apache/echarts#9095]
### One-line summary [问题简述]

moveOnMouseWheel设置为false 没有起到应有的效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.1以下版本构建出的源码里直接没有moveOnMouseWheel的配置项，4.2.0-rc.1版本中有此配置项，但配置为false后并不起效果
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win 8

### Expected behaviour [期望结果]

期望moveOnMouseWheel为false时鼠标滚轮缩放到最大限度后不会平移对应的图形

### ECharts option [ECharts配置项]

```javascript
option = {
  ...,
  dataZoom: [
    {
        id: 'dataZoomX',
        xAxisIndex: [0, 1, 2],
        type: 'inside',
        minValueSpan: 10,
        moveOnMouseWheel: false,
        rangeMode: ['value'],
        startValue: 0,
        endValue: data.times.length - 100
    }
  ],
  ...
}

```

**Comment by matulkum** [comment]
I observed exactly the same problem. Using latest Chrome on OSX: setting `moveOnMouseWheel` on `dataZoom` has no effect:
```
        dataZoom: [
          {
            type: 'inside',
            moveOnMouseWheel: false,
            filterMode: 'none',
            xAxisIndex: [0],
            minValueSpan: 3600 * 24 * 1000 * 7, // 1 week min
          },
        ],
```

**Comment by xiaonaiquan** [comment]
> I have the same issue. moveOnMouseWheel is false but the chart still scrolls.

Hi,Did you solve this problem?
