### ISSUE TITLE
建议itemStyle的borderColor也可以与color一样引入函数动态计算

### ISSUE THREAD

**Issue by southwhale** [apache/echarts#9100]
### One-line summary [问题简述]

建议itemStyle的borderColor也可以与color一样引入函数动态计算

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.1
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win8, mac

### Expected behaviour [期望结果]

itemStyle的borderColor可以与color一样引入函数动态计算每一项的borderColor值，甚至borderWidth也一起实现可以动态的根据每一项value的值来动态设置可变值，其实感觉itemStyle的每一项配置都可以引入函数配置的方式，更加的灵活自由

### ECharts option [ECharts配置项]

```javascript
option = {
    ...,
    seriers:[
        {
            ...,
            itemStyle: {
                color: function(...args) { },
                borderColor: function(...args) { },
                borderWidth: function(...args) { }
            },
            ...
        }
    ]
}

```

**Comment by shuxinjin** [comment]
same suggestion . n

**Comment by limit81995** [comment]
有解决么

**Comment by limit81995** [comment]
有解决办法吗
