### ISSUE TITLE
轴线映射控制

### ISSUE THREAD

**Issue by menciusKael** [apache/echarts#9110]
![image](https://user-images.githubusercontent.com/29659731/45858643-f9483780-bd90-11e8-8dc4-dc9d200bfe8c.png)

如何让 图中折线图，相对左边y轴映射，而不是右边

**Comment by Ovilia** [comment]
http://www.echartsjs.com/option.html#series-line.yAxisIndex

**Comment by menciusKael** [comment]
感谢。已解决
