### ISSUE TITLE
Tooltips with the "axis" trigger are closed when calling chartInstance.setOption().

### ISSUE THREAD

**Issue by BenoitZugmeyer** [apache/echarts#9116]
### One-line summary [问题简述]

When the chart shows a tooltips with `trigger: "axis"`, calling `chartInstance.setOption()` is closing the tooltip.

### Version & Environment [版本及环境]

+ ECharts version [ECharts 版本]: 4.1 or 4.2.0-rc.1
+ Browser version [浏览器类型和版本]: Firefox 62.0 and Chrome 69.0.3497.92
+ OS Version [操作系统类型和版本]: Arch Linux, up to date

### Expected behaviour [期望结果]

When hovering an empty part of the chart (= not a serie), the tooltip configured with the `"axis"` trigger is showing. When calling `setOption()` when the tooltip is shown, it should still be displayed.

### ECharts option [ECharts配置项]

(this is a modified version of https://ecomfe.github.io/echarts-examples/public/editor.html?c=dynamic-data2 )
```javascript
myChart = echarts.init(document.querySelector('main'))

function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join("/"),
      Math.round(value)
    ]
  };
}

var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
  data.push(randomData());
}

option = {
  tooltip: {
    trigger: "axis",
    formatter: function(params) {
      params = params[0];
      var date = new Date(params.name);
      return date.getDate() +
        "/" +
        (date.getMonth() + 1) +
        "/" +
        date.getFullYear() +
        ":" +
        params.value[1];
    },
  },
  xAxis: {
    type: "time"
  },
  yAxis: {
    type: "value",
    boundaryGap: [0, "100%"]
  },
  series: [{
    type: "line",
    data: data
  }]
};


setInterval(function() {
	myChart.setOption({})
}, 1000);

myChart.setOption(option);
```

### Other comments [其他信息]

Online demo: https://jsfiddle.net/z0ok3m2f/18/ (to reproduce: hover a blank part of the chart, the tooltip should show up, but it will be closed after a bit, because `setOption` is called)

**Comment by ValueLan** [comment]
`
    let index = -1;
    chartInstance.on("hideTip", function() {
      index = -1;
    });

    chartInstance.on("showTip", function() {
      index = 1;
    });

    function setOption() {
      chartInstance.setOption({});
      if (index != -1) {
        dispatchAction({
          type: "showTip"
        });
      }
    }


`
