### ISSUE TITLE
pie图只有加了 calculable : true时候才会显示白圈

### ISSUE THREAD

**Issue by dengzibiao** [apache/echarts#913]
pie图只有加了 calculable : true时候才会显示白圈，但是我不想添加拖拽事件，但是在数据为0的时候如果没有白圈就不好看了，所以能不能加个属性，显示白圈的属性，谢谢百忙中抽出时间

**Comment by smalltwo** [comment]
有属性可以控制calculable为true时出现那根线的粗细吗
