### ISSUE TITLE
Negative line calculate stack 

### ISSUE THREAD

**Issue by mexvod** [apache/echarts#9141]
option = {

    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : [1,2,3,4,5]
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            type:'line',
            stack: '1',
            data:[110,120, 120, 101,115]
        },
        {
            type:'line',
            stack: '1',
            label: {
                normal: {
                    show: true,
                    position: 'top'
                }
            },
            areaStyle: {normal: {}},
            data:[134,200, -20, 181,143]
        }
    ]
};

![default](https://user-images.githubusercontent.com/10468397/46138836-a5889300-c255-11e8-9809-d40d3c8c196c.png)
Negative areaStyle badly !!
Next:
option = {

    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : [1,2,3,4,5]
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            type:'line',
           
            data:[110,120, 120, 101,115]
        },
        {
            type:'line',
           
            label: {
                normal: {
                    show: true,
                    position: 'top'
                }
            },
            data:[134,200, 80, 181,143]
        }
    ]
};
![default](https://user-images.githubusercontent.com/10468397/46139045-35c6d800-c256-11e8-8755-7cc86c82cddf.png)
How to make:
![default](https://user-images.githubusercontent.com/10468397/46139171-7de5fa80-c256-11e8-8924-17c3f449be9b.png)
how to paint over these areas?

**Comment by gcem** [comment]
An option to disable negative stacks would result in the image with black painting. Example:
![image](https://user-images.githubusercontent.com/34423323/96114250-0becb680-0eee-11eb-83d7-2256a0f002cd.png)

Notice that negative stack is also causing distorted areas such as that in #9317, and areas are drawn correctly with it disabled. Ideally, in a stacked chart with negative stack, the line would break where the function's interpolated value becomes 0, and jump immediately between positive and negative parts of the chart:
![image](https://user-images.githubusercontent.com/34423323/96116228-cbdb0300-0ef0-11eb-817b-e435e16fc4dd.png)
