### ISSUE TITLE
series.graph节点数量大于1010时focusNodeAdjacency不能显示label

### ISSUE THREAD

**Issue by liujiusheng** [apache/echarts#9143]
### One-line summary [问题简述]
在使用graph图时，节点数量大于1010个时使用focusNodeAdjacency，节点和连线能正常高亮，但是节点的label不能正常显示出来。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:^4.1.0
+ Browser version [浏览器类型和版本]:chrome 69.0.3497.100
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
确认是否确实有此问题。若是特意这样控制，请官方文档上标注限制值，若确实为bug,修复此bug.

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
            text: 'NPM Dependencies'
        },
        // animationDurationUpdate: 1500,
        // animationEasingUpdate: 'quinticInOut',
        series : [
            {
                type: 'graph',
                layout: 'force',
                // progressiveThreshold: 700,
                data: data.node,
                edges: data.link,
                label: {
                    emphasis: {
                        position: 'right',
                        show: true,
                    }
                },
                roam: true,
                focusNodeAdjacency: true,
                lineStyle: {
                    normal: {
                        width: 0.5,
                        curveness: 0.3,
                        opacity: 0.7
                    }
                }
            }
        ]
}

```

**Comment by pissang** [comment]
没有这种限制，希望能给出更详细的复现信息

**Comment by liujiusheng** [comment]
@pissang https://github.com/liujiusheng/echart-graph-test我把数据上传到里面了，麻烦看一下。数据的node部分目前共了1014个结点，任意删除4个就能复现这个问题了。

**Comment by chenyeye** [comment]
我用的时候也发现了这个问题，我测的节点数量超过967时会出现这种情况，我的同事测的是超过1075个节点时出现了这种情况，题主最后有什么优化方案吗？

**Comment by liujiusheng** [comment]
> 我用的时候也发现了这个问题，我测的节点数量超过967时会出现这种情况，我的同事测的是超过1075个节点时出现了这种情况，题主最后有什么优化方案吗？

暂时也没找到办法，只有把节点数减少呗。

**Comment by zhaoYan1006** [comment]
您好，打扰了，能说下是什么原因导致会出现这样的问题么？可以通过修改源码解决么？




------------------ 原始邮件 ------------------
发件人: "liujiusheng"<notifications@github.com>;
发送时间: 2019年2月17日(星期天) 下午3:30
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "289472157"<289472157@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] series.graph节点数量大于1010时focusNodeAdjacency不能显示label (#9143)



 
我用的时候也发现了这个问题，我测的节点数量超过967时会出现这种情况，我的同事测的是超过1075个节点时出现了这种情况，题主最后有什么优化方案吗？
  
暂时也没找到办法，只有把节点数减少呗。

**Comment by liujiusheng** [comment]
> 您好，打扰了，能说下是什么原因导致会出现这样的问题么？可以通过修改源码解决么？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "liujiusheng"<notifications@github.com>; 发送时间: 2019年2月17日(星期天) 下午3:30 收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>; 抄送: "289472157"<289472157@qq.com>; "Manual"<manual@noreply.github.com>; 主题: Re: [apache/incubator-echarts] series.graph节点数量大于1010时focusNodeAdjacency不能显示label (#9143) 我用的时候也发现了这个问题，我测的节点数量超过967时会出现这种情况，我的同事测的是超过1075个节点时出现了这种情况，题主最后有什么优化方案吗？ 暂时也没找到办法，只有把节点数减少呗。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

没仔细去查到底什么问题导致的。能不能修改源码解决那得看你自己改不改得动啦。
