### ISSUE TITLE
3D绘制surface曲面的颜色映射问题

### ISSUE THREAD

**Issue by KimChen2016** [apache/echarts#9144]
### One-line summary [问题简述]
不知道是不是我理解有误，在3D绘制中选择surface类型时
1.不能绘制垂直于X轴的平面（也就是所有点如果x值是一样的，这些点就没法画出一个面）
2.在series中设定了data属性时，visualmap中设定的数据只能对应到坐标值上
  也就是说颜色只能随着坐标值（x或者y或者z）的变化而变化

我的需求是:
我在3D上绘制了一组连续的正方体，绘制时数据类型用的是surface，并设定了visualMap
另外每个正方体都有一个属性值，我想要根据这个属性值和设定的visualMap来让每个正方体显示不同的颜色
但是不知道该如果设定，或者说选择surface方式绘制时无法实现这个功能

另外如果这样做不行的，时候有什么方式可以满足我的要求？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
可以同自定义的值来控制每个正方体颜色

### ECharts option [ECharts配置项]

```javascript
let gridRange = [3, 6, 4, 7, 5, 6];
let pointData = [];

// buttom
let z = gridRange[4];
for(let y = gridRange[2]; y <= gridRange[3]; y++) {
    for(let x = gridRange[0]; x <= gridRange[1]; x++) {
        pointData.push([x, y, z]);
    }
}

// back
let y = gridRange[3];
for(let z = gridRange[4]; z <= gridRange[5]; z++) {
    for(let x = gridRange[0]; x <= gridRange[1]; x++) {
        pointData.push([x, y, z]);
    }
}

// top
z = gridRange[5];
for(let y = gridRange[3]; y >= gridRange[2]; y--) {
    for(let x = gridRange[0]; x <= gridRange[1]; x++) {
        pointData.push([x, y, z]);
    }
}

// front
y = gridRange[2];
for(let z = gridRange[5]; z >= gridRange[4]; z--) {
    for(let x = gridRange[0]; x <= gridRange[1]; x++) {
        pointData.push([x, y, z]);
    }
}

option = {
    tooltip: {},
    backgroundColor: '#fff',
    visualMap: {
        show: true,
        text:['High','Low'],
        calculable : true,
        dimension: 2,
        min: 0,
        max: 10,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    xAxis3D: {
        type: 'value',
        min: 0,
        max: 10,
        interval: 1
    },
    yAxis3D: {
        type: 'value',
        min: 0,
        max: 10,
        interval: 1
    },
    zAxis3D: {
        type: 'value',
        min: 0,
        max: 10,
        interval: 1
    },
    grid3D: {
        viewControl: {
            projection: 'perspective'
        }
    },
    series: [
    // bottom, back, top, front
    {
        type: "surface",
        data: pointData
    },
    // left
    {
        type: "surface",
        parametric: true,
        parametricEquation: {
            u: { min: gridRange[2], max: gridRange[3], step: 1 },
            v: { min: gridRange[4], max: gridRange[5], step: 1 },
            x: function(u, v) { return gridRange[0] },
            y: function(u, v) { return u; },
            z: function(u, v) { return v; },
        }
    },
    // right
    {
        type: "surface",
        parametric: true,
        parametricEquation: {
            u: { min: gridRange[2], max: gridRange[3], step: 1 },
            v: { min: gridRange[4], max: gridRange[5], step: 1 },
            x: function(u, v) { return gridRange[1] },
            y: function(u, v) { return u; },
            z: function(u, v) { return v; },
        }
    }
    ],
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/22983796/46240505-389f0580-c3db-11e8-9bbe-3d2a5513f28d.png)

**Comment by EmptyHead35** [comment]
> ### One-line summary [问题简述]
> 不知道是不是我理解有误，在3D绘制中选择surface类型时
> 1.不能绘制垂直于X轴的平面（也就是所有点如果x值是一样的，这些点就没法画出一个面）
> 2.在series中设定了data属性时，visualmap中设定的数据只能对应到坐标值上
> 也就是说颜色只能随着坐标值（x或者y或者z）的变化而变化
> 
> 我的需求是:
> 我在3D上绘制了一组连续的正方体，绘制时数据类型用的是surface，并设定了visualMap
> 另外每个正方体都有一个属性值，我想要根据这个属性值和设定的visualMap来让每个正方体显示不同的颜色
> 但是不知道该如果设定，或者说选择surface方式绘制时无法实现这个功能
> 
> 另外如果这样做不行的，时候有什么方式可以满足我的要求？
> 
> ### Version & Environment [版本及环境]
> * ECharts version [ECharts 版本]:
> * Browser version [浏览器类型和版本]:
> * OS Version [操作系统类型和版本]:
> 
> ### Expected behaviour [期望结果]
> 可以同自定义的值来控制每个正方体颜色
> 
> ### ECharts option [ECharts配置项]
> ```js
> let gridRange = [3, 6, 4, 7, 5, 6];
> let pointData = [];
> 
> // buttom
> let z = gridRange[4];
> for(let y = gridRange[2]; y <= gridRange[3]; y++) {
>     for(let x = gridRange[0]; x <= gridRange[1]; x++) {
>         pointData.push([x, y, z]);
>     }
> }
> 
> // back
> let y = gridRange[3];
> for(let z = gridRange[4]; z <= gridRange[5]; z++) {
>     for(let x = gridRange[0]; x <= gridRange[1]; x++) {
>         pointData.push([x, y, z]);
>     }
> }
> 
> // top
> z = gridRange[5];
> for(let y = gridRange[3]; y >= gridRange[2]; y--) {
>     for(let x = gridRange[0]; x <= gridRange[1]; x++) {
>         pointData.push([x, y, z]);
>     }
> }
> 
> // front
> y = gridRange[2];
> for(let z = gridRange[5]; z >= gridRange[4]; z--) {
>     for(let x = gridRange[0]; x <= gridRange[1]; x++) {
>         pointData.push([x, y, z]);
>     }
> }
> 
> option = {
>     tooltip: {},
>     backgroundColor: '#fff',
>     visualMap: {
>         show: true,
>         text:['High','Low'],
>         calculable : true,
>         dimension: 2,
>         min: 0,
>         max: 10,
>         inRange: {
>             color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
>         }
>     },
>     xAxis3D: {
>         type: 'value',
>         min: 0,
>         max: 10,
>         interval: 1
>     },
>     yAxis3D: {
>         type: 'value',
>         min: 0,
>         max: 10,
>         interval: 1
>     },
>     zAxis3D: {
>         type: 'value',
>         min: 0,
>         max: 10,
>         interval: 1
>     },
>     grid3D: {
>         viewControl: {
>             projection: 'perspective'
>         }
>     },
>     series: [
>     // bottom, back, top, front
>     {
>         type: "surface",
>         data: pointData
>     },
>     // left
>     {
>         type: "surface",
>         parametric: true,
>         parametricEquation: {
>             u: { min: gridRange[2], max: gridRange[3], step: 1 },
>             v: { min: gridRange[4], max: gridRange[5], step: 1 },
>             x: function(u, v) { return gridRange[0] },
>             y: function(u, v) { return u; },
>             z: function(u, v) { return v; },
>         }
>     },
>     // right
>     {
>         type: "surface",
>         parametric: true,
>         parametricEquation: {
>             u: { min: gridRange[2], max: gridRange[3], step: 1 },
>             v: { min: gridRange[4], max: gridRange[5], step: 1 },
>             x: function(u, v) { return gridRange[1] },
>             y: function(u, v) { return u; },
>             z: function(u, v) { return v; },
>         }
>     }
>     ],
> }
> ```
> 
> ### Other comments [其他信息]
> ![image](https://user-images.githubusercontent.com/22983796/46240505-389f0580-c3db-11e8-9bbe-3d2a5513f28d.png)
不能绘制垂直于X轴的平面（也就是所有点如果x值是一样的，这些点就没法画出一个面），这个问题解决了么
