### ISSUE TITLE
AMD requirejs？

### ISSUE THREAD

**Issue by huyinghuan** [apache/echarts#918]
我使用模块化单文件引入echarts， 如何使用requirejs 来加载echarts？，根据文档的中说明 build/dist/echars.js里面已经包含了 els， 我在引入requirejs后， requirejs 无法正常工作（表现在data-main引入的js文件无法工作）
为什么使用requirejs？ els在文档说了不支持shim之类配置。

**Comment by terminatorheart** [comment]
我使用的2.1.10版本，社区版和百度版都下载下来测试过，使用通常requirejs加载amd模块的方式加载echarts都会引入很多其他画图类文件

**Comment by huyinghuan** [comment]
@terminatorheart  那不是其他画图类， 那是echart依赖的画图核心包。
最新的解释在这里 https://github.com/ecomfe/echarts/issues/1153#issuecomment-69878760

**Comment by terminatorheart** [comment]
嗯，谢谢您的解答，原来不少人都遇到了这个问题呀，不过不知道esl什么时候能支持shim，毕竟老的库和插件还非常多，都修改为模块化的标准方式是很有难度的

**Comment by huyinghuan** [comment]
@terminatorheart  我也只是是遇到过这个坑而已。。

**Comment by terminatorheart** [comment]
还是没有好办法，准备切回highcharts画图了，折腾半周了，再不搞完没法交代了

**Comment by pissang** [comment]
https://github.com/ecomfe/esl esl 2.0 支持 shim 了

**Comment by terminatorheart** [comment]
哦，nice，如此甚好

**Comment by errorrik** [comment]
最新版本echarts中，带的是esl1.8.8。我们已经升级了构建工具，在echarts发布新版的时候，带的esl就会升级到2.0.2.

在此之前，如果想要使用esl2.0.2版本，请将其置于echarts的script标签前。

```html
<script src="http://s1.bdstatic.com/r/www/cache/ecom/esl/2-0-2/esl.js"></script>
<script src="echarts.js"></script>
```

esl发现页面上存在amd环境，策略是自动退出。requirejs也是如此。

**Comment by terminatorheart** [comment]
@erik168 谢谢您的解答，我又有一个新的问题，图形切换能够支持的类型全部都在doc中列出来了吗，比如折柱动态类型切换，饼漏斗图动态类型切换，力导和弦动态类型切换。好像没有饼图和柱状图的切换（或者是我使用的方式不对？），方便添加上吗？

**Comment by kener** [comment]
这个应用场景在多系列下比较复杂，多个饼图如何布局和大小控制并没有很好的方案，依然需要用户定义很多pie图的布局参数所以一直没做。
如果仅是单系列的动态类型切换实在太简单了也不值得做，自己扩展一个工具栏重新setOption就行：
柱形变饼：把option拿到，series.type改成pie，xAxis、yAxis、grid都存到_xAxis,_y..然后删掉，setOption更新；
饼变柱形：把option拿到，series.type改成bar，xAxis、yAxis、grid都从_xAxis,_y..里还原删掉，setOption更新；
并不复杂可以自己实现。

**Comment by RuralHunter** [comment]
建议文档里说明模块化单文件方式不支持requirejs，免得别人浪费时间

**Comment by huyinghuan** [comment]
@RuralHunter  有个不优雅的解决办法 提供参考

在引入echarts的script标签上加上一个onload事件， 加载完成后， 启用require如：

```
<script src="require.js"></script>
<script>
 var allReady = function(){
   require('app'); 执行默认文件
}
</script>
<script src="echarts.js" onload="allReady()"></script>
```

**Comment by guanghemm** [comment]
@huyinghuan 我也和你一样使用了requirejs和echarts，通过模块化单文件引入方式来使用echarts，也copy官网的example，执行到echarts.init的时候报错，调试发现require进来的echarts是个undefined；
然后我调整了requirejs和echarts的载入顺序，就发现其他的更疑惑的错误；
求问，你最后是怎么解决的？

**Comment by RuralHunter** [comment]
我放弃了单文件方式，直接用完整的源文件
