### ISSUE TITLE
Performance is poor if series has a lot of data

### ISSUE THREAD

**Issue by DongJoon-Ko** [apache/echarts#9187]
### One-line summary [问题简述]

Performance is very poor if there is a lot of legend data(
Approximately 2000 or more).
No matter what the behavior is(mouseover tooltip, click magictype, click legend, ... all of chart division), performance is poor.
If the data is small, the performance is normal.

### Version & Environment [版本及环境]
ECharts version [ECharts 版本]: 4.2.0-rc.1
Browser version [浏览器类型和版本]: Google Chrome Versión 69.0.3497.100 (Build oficial) (64 bits)
OS Version [操作系统类型和版本]: Windows 10 Pro 

### ECharts option [ECharts配置项]
{
  "grid": {
    "x": 30,
    "x2": 25,
    "y": 45,
    "y2": 71
  },
  "animationDuration": 20,
  "tooltip": {
    "show": true,
    "trigger": "axis",
    "backgroundColor": "rgba(0,0,0,0.6)"
  },
  "legend": {
    "show": true,
    "data": [
      "Item ID - 1",
      "Item ID - 2",
      "Item ID - 3",
      "Item ID - 4",
      "Item ID - 5",
      "Item ID - 6",
      "Item ID - 7"
      ///....2000 or more data
////////
"series": [
    {
      "name": "Item ID - 1",
      "type": "line",
      "yAxisIndex": 0,
      "barGap": 0,
      "symbolSize": 5,
      "data": [
        141,
        289,
        197,
        182,
        162,
        129,
        127,
        118,
        140,
        226,
        184,
        128,
        125,
        114,
        102,
        109
      ],
      "markPoint": {
        "clickable": false,
        "itemStyle": {
          "normal": {
            "borderWidth": 0,
            "label": {
              "show": false
            }
          }
        },
        "tooltip": {
          "show": false
        },
        "effect": {
          "show": false,
          "shadowBlur": 0.4
        },
        "data": [
          {
            "type": "max",
            "symbolSize": 7,
            "symbol": "circle"
          }
        ]
      }
    },
//............2000 or more series data

**Comment by Ovilia** [comment]
You have 2000 series? Basically, 2000 data each for small amount of series have a better performance.

**Comment by BEGEMOT9I** [comment]
@Ovilia Hi. I have a specific case when there is a set of about 9000 series with 3 values or 3 series with 9000 values. In the first case, the performance drops dramatically (drawing the graph takes more than a minute) with respect to the second case, when it takes only a few seconds. Is there a way to increase productivity? I tried to use dataset (it got worse), set the property `large` to true and disable animation. ECharts v4.1.0
