### ISSUE TITLE
FlowGL 矢量场图在 iPhone 主流浏览器上无法显示

### ISSUE THREAD

**Issue by iboying** [apache/echarts#9189]
### One-line summary [问题简述]
【GL 矢量场图】在 iPhone 主流浏览器上无法显示，Android 手机浏览器和PC端浏览器可正常访问。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts 2.0
+ Browser version [浏览器类型和版本]: iPhone safari、iPhone chrome、iPhone 微信浏览器
+ OS Version [操作系统类型和版本]: iPhone、iOS 12.0

### Expected behaviour [期望结果]
iPhone 访问官网 GL 矢量场图 能看到效果。

### ECharts option [ECharts配置项]

```javascript
option = {

}
```
此处使用官网示例的代码即可；

### Other comments [其他信息]

官网示例即可查看：
http://www.echartsjs.com/examples/editor.html?c=flowGL-noise&gl=1&theme=dark

iPhone Safari查看效果：
![image](https://user-images.githubusercontent.com/10523771/46725020-d2a16080-ccad-11e8-8d0d-d9edac986df8.png)

Android 微信查看效果：
![image](https://user-images.githubusercontent.com/10523771/46725142-1eeca080-ccae-11e8-841d-17cf2d7cc886.png)

Mac chrome 查看效果：
![image](https://user-images.githubusercontent.com/10523771/46725000-c7e6cb80-ccad-11e8-8b61-18713e6a422f.png)

**Comment by iboying** [comment]
@Ovilia 这个兼容性问题有什么方法能解决吗？谢谢

**Comment by sicaboy** [comment]
两年了，有人有解决方案了吗？
