### ISSUE TITLE
ajax如何根据新的option刷新图形

### ISSUE THREAD

**Issue by Asutos** [apache/echarts#92]
首次加载通过get请求到option，之后根据查询条件通过ajax的方式刷新图形信息，图形显示位置为一片空白。
省略require.config
require(
   [
    'echarts',
    'echarts/chart/line',
    'echarts/chart/bar'
  ],
  function(ec){
    echarts = ec.init(document.getElementById('graphic')
    echarts.setOptioin(eval($!option))  
 }
)
图形正常显示
之后通过ajax的callback刷新图形
$.get(url,function(option){
   echarts.setOption(option)
})
无法加载图形，原来显示的图形的div变为空白
(option数据格式正常)

**Comment by zmwxiaoming** [comment]
解决了么,与jdk没啥关系吧
