### ISSUE TITLE
使用 echarts 提供的构建脚本自定义构建报错

### ISSUE THREAD

**Issue by myy012** [apache/echarts#9203]
报错信息：
```
min && plugins.push(uglifyPlugin({
TypeError: uglifyPlugin is not a function
```

解决方案：

找到**/node_modules/echarts/build/config.js**文件
 
```
const uglifyPlugin = require('rollup-plugin-uglify')
// 修改为
const uglifyPlugin = require('rollup-plugin-uglify').uglify
```

**Comment by Ovilia** [comment]
看起来是 `rollup-plugin-uglify` 没更新导致的，@100pah 麻烦跟进下。

**Comment by svengong** [comment]
> 看起来是 `rollup-plugin-uglify` 没更新导致的，@100pah 麻烦跟进下。
这都多久了还有这个问题，最新版本。。

**Comment by JonathanChaochen** [comment]
According to tutorial https://www.echartsjs.com/en/tutorial.html#Create%20Custom%20Build%20of%20ECharts
I still have this issue
