### ISSUE TITLE
当鼠标松开时能捕捉到brush end事件

### ISSUE THREAD

**Issue by Gamehu** [apache/echarts#9215]
One-line summary [问题简述]
目前echarts的brushSelected能捕捉到框选的结果，但是没有brush end的事件，无法预测框选结束。

Version & Environment [版本及环境]
ECharts version [ECharts 版本]:3.8.5
Browser version [浏览器类型和版本]:69.0.3497.81
OS Version [操作系统类型和版本]:windows10
Expected behaviour [期望结果]
框选图表，当鼠标松开时能捕捉到brush end事件

ECharts option [ECharts配置项]
 

var xAxisData = [];
var data1 = [];
var data2 = [];
var data3 = [];
var data4 = [];

for (var i = 0; i < 10; i++) {
    xAxisData.push('Class' + i);
    data1.push((Math.random() * 2).toFixed(2));
    data2.push(-Math.random().toFixed(2));
    data3.push((Math.random() * 5).toFixed(2));
    data4.push((Math.random() + 0.3).toFixed(2));
}

var itemStyle = {
    normal: {
    },
    emphasis: {
        barBorderWidth: 1,
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowColor: 'rgba(0,0,0,0.5)'
    }
};
option = {

    backgroundColor: '#eee',
    legend: {
        data: ['bar', 'bar2', 'bar3', 'bar4'],
        align: 'left',
        left: 10
    },
    brush: {
        toolbox: ['lineX', 'clear'],
        xAxisIndex: 0
    },
    tooltip: {},
    xAxis: {
        data: xAxisData,
        name: 'X Axis',
        silent: false,
        axisLine: {onZero: true},
        splitLine: {show: false},
        splitArea: {show: false}
    },
    yAxis: {
 
    },
    grid: {
        left: 100
    },
    series: [
        {
            name: 'bar',
            type: 'line',
            stack: 'one',
            itemStyle: itemStyle,
            data: data1
        }
    ]
};

myChart.on('brushSelected', renderBrushed);

function renderBrushed(params) {
    var brushed = [];
    var brushComponent = params.batch[0];

    for (var sIdx = 0; sIdx < brushComponent.selected.length; sIdx++) {
        var rawIndices = brushComponent.selected[sIdx].dataIndex;
        brushed.push('[Series ' + sIdx + '] ' + rawIndices.join(', '));
    }

    myChart.setOption({
        title: {
            backgroundColor: '#333',
            text: 'SELECTED DATA INDICES: \n' + brushed.join('\n'),
            bottom: 0,
            right: 0,
            width: 100,
            textStyle: {
                fontSize: 12,
                color: '#fff'
            }
        }
    });
}
}

**Comment by Ovilia** [comment]
`brushSelected` 包括了“用户在界面中创建、删除、修改选框时会发出”，有什么需要不能满足？

**Comment by Gamehu** [comment]
你好，现在的brushSelected 是在不断触发，就是我无法知道什么时候是框选完了，比如当我鼠标放开的时候其实就意味着我框选完了，但是现在没有这个单独对框选结束的事件

**Comment by cuijian-dexter** [comment]
@Gamehu You can achieve this by setting parameters `brush.throttleType` and parameter `brush.throttleDelay.`

**Comment by cuijian-dexter** [comment]
@Gamehu Before officially supporting methods, I recommend that you filter out brushEnd through the different execution orders of mousedown, brushSelected and mouseup methods.
