### ISSUE TITLE
漏斗图每层的标签在position: 'left' | 'right'时如何水平对齐?

### ISSUE THREAD

**Issue by shawtung** [apache/echarts#9217]
### One-line summary [问题简述]
如图, 希望标签视觉上能在一列上, labelLine的长度可以自动变化.
现在我只能手动设置data[i].labelLine.length来实现这个效果.
按我的理解, label.align应该就是对应这个功能, 但各种实验均未发现这个align到底有啥用...

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/11240622/46864504-301fe380-ce4d-11e8-9ef9-0333f5bc2034.png)
![image](https://user-images.githubusercontent.com/11240622/46864851-1763fd80-ce4e-11e8-83cb-6e7bed6c9f9b.png)

**Comment by Ovilia** [comment]
align left 表示的就是如图一所示的对齐方式，目前好像没有别人反馈有图二的需求，先标个 enhancement。

**Comment by zhuxinping** [comment]
您好,我也遇到这个问题请问如何让漏斗图的引导线动态设置长度让文本靠左或靠右对齐

**Comment by cuijian-dexter** [comment]
@zhuxinping I realized it by modifying the source code. I'll mention it sometime these days.
