### ISSUE TITLE
柱状图设置背景

### ISSUE THREAD

**Issue by cn-xufei** [apache/echarts#9227]
### One-line summary [问题简述]
很多业务场景需要给柱状图设置个背景，比如👇
![image](https://user-images.githubusercontent.com/14144811/46927437-f971e500-d067-11e8-89db-d42c51fe85fc.png)
当然echars目前可以通过barGap=‘-100%'来将一组bar的serie重叠，并且还得用一组最大值数据填充data，然后才看起来是个背景
但是当柱状图是多个系列的，比如👇
![image](https://user-images.githubusercontent.com/14144811/46927566-9df42700-d068-11e8-8851-0d7a839e4d2d.png)
就不能barGap=‘-100%'这么玩了，但也可以曲线救国，比如可以设置双xAxis，原数据在第一个x轴展示，将原数据拷贝一份在第二个x轴展示，取最大值数据作为data，并设置第二个x轴不可见，两个x轴的刻度数据保持一致，最终效果👇
![image](https://user-images.githubusercontent.com/14144811/46927746-9c772e80-d069-11e8-8085-e5018473aeaf.png)

给柱状图设置背景，这是一个痛点，相信很多人也有类似的需求，希望官方可以扩展下配置支持这种模式

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.x

### Expected behaviour [期望结果]
希望柱状图开放一个柱子背景的配置项

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        data: ['a', 'b', 'c', 'd'],
        axisTick: {show: false},
        axisLabel: {
            formatter: 'barGap: \'-100%\''
        }
    },
    yAxis: {
        splitLine: {show: false}
    },
    animationDurationUpdate: 1200,
    series: [{
        type: 'bar',
        itemStyle: {
            normal: {
                color: '#ddd'
            }
        },
        silent: true,
        barWidth: 40,
        barGap: '-100%', // Make series be overlap
        data: [60, 60, 60, 60]
    }, {
        type: 'bar',
        barWidth: 40,
        z: 10,
        data: [45, 60, 13, 25]
    }, {
        name: 'hehe',
        type: 'bar',
        barWidth: 40,
        z: 10,
        data: [45, 60, 13, 25]
    }]
};


```

**Comment by cn-xufei** [comment]
更正下，在设置柱状图背景的时候，背景的数据是数据轴的最大刻度值而不是原数据的最大值
本人的获取方式是：chart.getModel().getComponent('yAxis', 0).axis.scale.getExtent()[1]
希望官方可以考虑下，支持背景的配置

**Comment by deqingli** [comment]
您好，谢谢您的反馈和建议
