### ISSUE TITLE
地图：移动端拖动，拖出边界后，无法再拉回

### ISSUE THREAD

**Issue by Dushusir** [apache/echarts#9239]
### One-line summary [问题简述]
地图：移动端拖动，拖出边界后，无法再拉回。
发现地图组件的范围并不是占满整个canvas，导致拖动距离地图较远的区域无法触发地图跟随手指滑动。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:微信内置浏览器， 微信版本6.7.3
+ OS Version [操作系统类型和版本]:iOS 11

### Expected behaviour [期望结果]
可视化结果：地图可以随意拖动，且不会全部溢出边界，或者溢出边界后可以拖回。
代码结果：地图的可触摸拖动范围扩大到整个canvas。

### ECharts option [ECharts配置项]
均为地图默认项即可

### Other comments [其他信息]

截图如下链接：红色圆圈处已无法触摸
http://p5vpw73bu.bkt.clouddn.com/%E5%9C%B0%E5%9B%BE.png

**Comment by 895457129** [comment]
@deqingli 有没有解决办法

**Comment by hiblacker** [comment]
tree模式 遇到同样的问题

**Comment by serfend** [comment]
似乎当`graph`的节点和连接较多的时候，会出现可视区域也不可拖拽、缩放的情况
https://serfend.top:12443/#/home/dashboard

**Comment by serfend** [comment]
发现似乎是当有value=0的值出现时，无法拖拽、缩放

**Comment by chardlau** [comment]
我使用下面方法暂时掩盖了问题：
在理论上无限远的地方加两个节点，让graph事件有效区域变大，例如{x:-10000,y:-10000},{x:10000,y:10000}. 
这个方法需要配套地修改graph的width、height、left、top、right、bottom，不然可能会出现节点压缩成一堆的情况

**Comment by LQ0611** [comment]
我在做世界地图，也遇到了 地图在拖拽的时候，可以将地图完全拖拽出可视区域，并且无法移回

**Comment by KappaFish0914** [comment]
遇到同样的问题，这个最近有优化吗

**Comment by wenlittleoil** [comment]
> 我在做世界地图，也遇到了 地图在拖拽的时候，可以将地图完全拖拽出可视区域，并且无法移回

I also encountered the same problem.

**Comment by wenlittleoil** [comment]
我是从产品交互层面解决的，可以手动在地图左下角添加一个重置按钮，当地图被拖出边界后无法拖回时，点击重置按钮可恢复地图原样`const onClickResetButton = () => yourChart.setOption(yourChartOption, true)`

**Comment by TaR1z** [comment]
如果在微信小程序，可以劫持touchMove事件，设置四周边界，但是不完美，强行移动也会导致无法拖回
`javascript
    touchMove(e) {
      const chart = this.chart;
      const needGesture = this.data.needGesture;
      const len = e.touches.length;
      const width = this.chart.getWidth();
      const height = this.chart.getHeight();
      const boundary = {
        top: 0,
        left: 0,
        right: width,
        bottom: height,
      };
      if (chart && len > 0) {
        const touch = e.touches[0];
        const handler = chart.getZr().handler;
        const { x, y } = touch;
        if (boundary.top > x || boundary.bottom < x || boundary.right < y || boundary.left > y) {
          return;
        }
        if (needGesture && len === TOUCH_POINT_NUM) {
          handler.processGesture(wrapTouch(e), 'change');
          return;
        }
        handler.dispatch('mousemove', {
          zrX: touch.x,
          zrY: touch.y,
          preventDefault: () => {},
          stopImmediatePropagation: () => {},
          stopPropagation: () => {},
        });
      }
    },
`
