### ISSUE TITLE
能否提供一个方式，设置item的selected的样式类似hover的放大效果

### ISSUE THREAD

**Issue by zhaoquanfeng064** [apache/echarts#9245]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by deqingli** [comment]
您好，麻烦提供详细的信息，操作效果图以及 echarts option 的配置

**Comment by zhaoquanfeng064** [comment]
![snipaste_2018-10-24_09-48-38](https://user-images.githubusercontent.com/16482775/47401113-915f8500-d772-11e8-8476-659e7f15a991.png)

您好，类似上诉图片的效果；
option={
   series:[
     {
        type:'pie',
        data:[{name:'zz',value:10,selected:true}]
     }
  ]
}
当数据select的时候能够支持方法效果，跟鼠标移动上去的那个放大一样，请问怎么实现

**Comment by zhaoquanfeng064** [comment]
谢谢羡辙，请教个问题，echarts饼图在实现的时候使用了什么坐标系么

**Comment by zhaoquanfeng064** [comment]
羡辙,如果使用series:{type:''custom},自定义绘制我图片里面这个样式的饼图，不设置坐标系的话，api.coord()这个方法未定义，请问有方法可以计算出角度和半径么
