### ISSUE TITLE
Continue Showing Same Tooltip On Dynamic Graph (Until Mouse Moves)

### ISSUE THREAD

**Issue by adamtLICOR** [apache/echarts#9246]
### One-line summary [问题简述]
Is there a simple way to continue showing the same tooltip on a dynamic graph (until the mouse moves)?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0 (via vue-echarts 3.1.3)
+ Browser version [浏览器类型和版本]: Chrome 69.0.3497.100
+ OS Version [操作系统类型和版本]: OSX High Sierra (10.13.6)

### Expected behaviour [期望结果]
I have a graph that adds one new data point to a series every second. I can highlight any of those points, and the tooltip shows up just fine:

![screen shot 2018-10-17 at 5 14 29 pm](https://user-images.githubusercontent.com/16004285/47119522-bd3db080-d230-11e8-832e-a24c7197b6a4.png)

However, when the graph updates the data after the next second, the tooltip moves on to the next point (because that point is now highlighted).

This makes it difficult to read any tooltip data.

Is there an easy way to keep showing the first tooltip, preferably until the mouse moves (to signal that another tooltip should be shown)?

**NOTE**: I have tried using the `alwaysShowContent` option, and that works somewhat. However, the tooltip shows for the currently selected point, and then changes to show for the next point in the series. After that happens, the tooltip *does* stay on the screen.

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip: {
        trigger: 'axis'
    }
    ...
    xAxis: {
       type: 'category'  
   }
}

```

### Other comments [其他信息]

A similar issues appears on the Dynamic Graph example on the official docs page: https://ecomfe.github.io/echarts-examples/public/editor.html?c=dynamic-data2

However, here, the tooltip usually disappears entirely (because no point is highlighted at all).

**Comment by deqingli** [comment]
sorry，I don't fully understand what you mean. Maybe you can add markPoint in your series, like this http://echarts.baidu.com/examples/editor.html?c=line-marker

**Comment by adamtLICOR** [comment]
My graph updates every second, and when it does, the cursor is no longer hovering over the same data point, so the shown tooltip changes (or disappears, depending on how the graph moves).

I want the tooltip to stay visible, until I move the mouse.

**Comment by Ovilia** [comment]
Can you try with `tooltip.alwaysShowContent`?

**Comment by i0x915** [comment]
Is there a fix or workaround planned for this ?

**Comment by AmitBisht14** [comment]
Is there any fix or workaround? I am also stuck with tooltip.alwaysShowContent solution suggested by @Ovilia but as @adamtLICOR said it blocks the hideTip action from getting dispatched. Thus looking for a discrete solution

**Comment by AmitBisht14** [comment]
In detail workaround as suggested by @adamtLICOR set tooltip.alwaysShowContent to false. After this you have to set the chart options which will reset tooltip property of alwaysShowContent thus it won't suppress hideTip dispatchAction
