### ISSUE TITLE
how would I set a click event on bar's label?

### ISSUE THREAD

**Issue by ybroch** [apache/echarts#9274]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Currently this is not supported. We are considering to add this feature.
See discussion at https://lists.apache.org/thread.html/bd553b1ada9e0cad979ee1411a332c6577dbe2c436c655a68eb7d1d1@%3Cdev.echarts.apache.org%3E
