### ISSUE TITLE
时间time类型怎么控制x轴的距离呢，貌似设置interval这个没有办法控制。

### ISSUE THREAD

**Issue by linwj603** [apache/echarts#928]
![image](https://cloud.githubusercontent.com/assets/9821623/5139344/ca478b14-7197-11e4-9c16-1b5d45e87844.png)

**Comment by xfworld** [comment]
@kener 这个问题最后有解决办法不？

**Comment by NeilJee** [comment]
这个问题有后续么

**Comment by marvinren** [comment]
这个问题看来没有后续了，我也遇到这种问题

**Comment by cryingbat** [comment]
> interval只适用于category，time axis自动根据区间适配划分，time axis目前是beta版，欢迎提建议

希望time轴能支持像类目轴一样，缩放时能自动隐藏显示不下x轴的时间
