### ISSUE TITLE
y轴名字(yAxis的name属性)超长问题显示不全

### ISSUE THREAD

**Issue by kin1492** [apache/echarts#9286]
### One-line summary [问题简述]
y轴名字(yAxis的name属性)超长问题,
y轴名字太长时会以y轴轴线为中心,分布在y轴轴线左右两侧,左侧部分文字会被遮盖

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0-rc.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:linux,windows

### Expected behaviour [期望结果]
y轴名字可以自定义起始点,可以设置名字的起始位置,y轴轴线的左侧或右侧,起始点在y轴轴线的左侧时候,名字均分在y轴轴线左右两侧显示,名字起始位置在轴线右侧的时候,名字的第一个字符和轴线对齐,或者是根据名字的长度自适应,只要不会遮住名字就好

### ECharts option [ECharts配置项]

```javascript
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        name:'y轴名字超长名字显示不全12345677890000000000',
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true
    }]
};


```

**Comment by 100pah** [comment]
如果名字太长，一般可以 `yAxis.nameLocation` 设为 `'middle'`，或者用 `yAxis.nameTextStyle` 里的 `align`、`verticalAlign` 来详细控制。
关于自动控制不超出可视区域，确实是个可以考虑的功能，因为应用场景或许有一些。

**Comment by bq-hentai** [comment]
请问一下 能做到文本从y轴轴线开始的位置进行输出吗，我查了文档，包括尝试了 nameLocation 和 nameTextStyle 里面的属性，但是并不能成功

**Comment by bq-hentai** [comment]
Duplicate of #9901 

see https://github.com/apache/incubator-echarts/issues/9901#issuecomment-463549820

**Comment by wjhcc2018** [comment]
我也遇到这个问题了，大家解决了吗

**Comment by 100pah** [comment]
Fixed in #21059
