### ISSUE TITLE
关系图中怎样显示部分nodes? (根据属性筛选）

### ISSUE THREAD

**Issue by chairy11** [apache/echarts#9292]
### One-line summary [问题简述]
比如关系图中有1000个节点nodes，nodes自带很多属性，我可能想通过某种条件筛选，符合的为其中的500个nodes，原地保留，隐藏不符合条件的另外500个nodes。
有没有办法去控制这些节点的显示或隐藏？有没有show: boolean之类的选项？

### Expected behaviour [期望结果]

类似通过点击legend显示或隐藏部分nodes。只是希望通过另一些事件，显示或隐藏部分符合某些条件的nodes。

谢谢：）

**Comment by 100pah** [comment]
如果筛选条件不需要动态逻辑（即，每个节点属于哪个类能预先确定）的话，那么 graph 的 [categories](http://www.echartsjs.com/option.html#series-graph.categories) 能支持筛选，例如 <http://echarts.baidu.com/examples/editor.html?c=graph>。

**Comment by chairy11** [comment]
> 如果筛选条件不需要动态逻辑（即，每个节点属于哪个类能预先确定）的话，那么 graph 的 [categories](http://www.echartsjs.com/option.html#series-graph.categories) 能支持筛选，例如 http://echarts.baidu.com/examples/editor.html?c=graph。

不够呢，比如除了category，我还有好几种不同维度的属性，需要根本不同的维度属性筛选。
比如：
1000个nodes，id为0~999，分类为"类别一"、"类别二"。
加上搜索框，搜索的是名字中含有"汽车"的node。这时候后台搜索，返回了ids。这个ids是[0,2,3,4]。我就想在原数据基础上，只显示这四个点，其它的全部隐藏。

现在我的做法是更新nodes数据本身，可以实现。
但我想，既然可以在legend上点击category就实现部分节点的显示和隐藏，那我能不能用同类事件触发部分数据的显示和隐藏？

**Comment by 100pah** [comment]
legend 的事件确实可以触发显示和隐藏，但是对于多维度的情况就不太足够。
我想，在现有的架构下，或许可以增加这样的实现：
```js
chart.dispatchAction({
    type: 'focus',
    seriesIndex: 0,
    dataIndex: [5, 6],
    edgeDataIndex: [1, 4]
});
```
不同于已有的 `highlight` `downplay`, `'focus'` 会高亮指定的，清除其余的，这个“清除”的范围，默认是“所指定的系列”。

**Comment by ryancui-** [comment]
要实现类似 Category 的带动画的显示与隐藏，但要保持原有的 Legend, 有什么进展吗？
