### ISSUE TITLE
markLine on line serie doesn't respect zoom

### ISSUE THREAD

**Issue by ramarro123** [apache/echarts#9304]
during zoom phase, markLine with type=average doesn't respect the correct zoom window, but show the avg of all the dataset.

it's possible to force it to calculate the avg of the "visible" zoom window of data?

for instance if i zoom from 1 to 10 i want to see the avg calculated from 1 to 10 not from 0 to end_data

**Comment by sxmpasch** [comment]
I think that is exactly what markLine of type average is doing...:
Go to example https://ecomfe.github.io/echarts-examples/public/editor.html?c=area-simple
Add a markLine:
```
            markLine: {
                data: [
                    {type: 'average', name: 'test'},
                ],
            },

```
This markLine shows the average of  the current view...

**Comment by ramarro123** [comment]
it doesn't work for me

here a demo

http://jsfiddle.net/qsbLt2a9/

avg of temp = 27,5 (correctly displayed if no zoom)

if i zoom on a interval of 29/30 the avg stay 27.5

that's the full view ( correct)
<img width="658" alt="schermata 2018-10-31 alle 08 35 03" src="https://user-images.githubusercontent.com/5493729/47772744-fd4c6b00-dce7-11e8-8f13-397fe1bd4d28.png">

that's the zoomed view ( not correct)
<img width="659" alt="schermata 2018-10-31 alle 08 35 19" src="https://user-images.githubusercontent.com/5493729/47772765-076e6980-dce8-11e8-85d3-c156e9df85eb.png">

**Comment by sxmpasch** [comment]
OK, it looks like "filtermode":"none" in "dataZoom" prevents the line from being adjusted, since nothing is being filtered out... unfortunately with so few series data items, the line draw is then not completed either...

**Comment by ramarro123** [comment]
so, we can consider that a bug?
filtermode and markLine shouldn't "interfere" imho.

**Comment by sxmpasch** [comment]
I think it is just as it was designed. By filtering out all data points being not in visible range, the average value is re-calculated. This is at least the explanation. Whether it is considered as a bug or a new feature request, it depends on the contributors. 
If I had to implement this, I would filter out all non-visible points, but I would complete the line drawings towards the left/right edge of the viewport by looking at the unfiltered series...

**Comment by 100pah** [comment]
Probably we need to support another `filerMode` option, with filter out all values outside the view, except the ones next to the points inside the view.
This option makes sense only in line chart, but after all line chart is a commonly used chart.

**Comment by ramarro123** [comment]
well it make sense also for people that use custom item renderer actually, and want to track back previous record.

**Comment by StefanoSega** [comment]
I would say a nice feature would be also to be able to apply `filterMode` only to certain datasets you want.
I've the common issue of lines/markAreas disappearing when zooming, it can be solved by setting `filterMode: none` but if I do that performance-wise the graph becomes very bad.
