### ISSUE TITLE
zoom 属性设置缩放 图表悬浮不正常

### ISSUE THREAD

**Issue by 582324763** [apache/echarts#9310]
### One-line summary [问题简述]

css中使用zoom 属性设置缩放，echart图表的鼠标悬浮事件错位，不能正确的找到元素的位置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 582324763** [comment]
![image](https://user-images.githubusercontent.com/32918610/47827403-acf10e00-ddb8-11e8-9032-9354e7d0cbfb.png)

**Comment by 100pah** [comment]
echarts 的版本是？

**Comment by xiaobinwu** [comment]
也是同样遇到这种问题，有什么解决办法吗

**Comment by 582324763** [comment]
应该是3.4.0

**Comment by 582324763** [comment]
> 也是同样遇到这种问题，有什么解决办法吗

暂时还没解决呢

**Comment by 582324763** [comment]
> echarts 的版本是？

应该是3.4.0

**Comment by Forget7** [comment]
遇到了同样的问题，求解决方案。

**Comment by wangbinyq** [comment]
4.2.1 还是有问题

**Comment by ChenLiaoyuan** [comment]
遇到同样的问题，css使用zoom属性缩放页面后，echarts图表的鼠标事件触发位置错位，影响交互，echarts版本是4.2，望修复。

**Comment by wangbinyq** [comment]
在 echart 的 div 上加上 zoom: 1 / zoom 可以解决

**Comment by ChenLiaoyuan** [comment]
> 在 echart 的 div 上加上 zoom: 1 / zoom 可以解决

这是什么原理？第二个zoom是指之前页面缩放的值吗？如之前缩放35%，echart的div就加上zoom: 1/0.35？把echart的div放大吗？

**Comment by wangbinyq** [comment]
我是用的 vue-echarts 的封装, 模板里面是 `<ECharts :options="chartOptions" :style="{zoom : 1/ zoom, height: '100%', width: '100%'}">`

**Comment by xiaobaixin** [comment]
> 我是用的 vue-echarts 的封装, 模板里面是 `<ECharts auto-resize :options="chartOptions" :style="{zoom : 1/ zoom, height: '100%', width: '100%'}">`
> 
> 这样做图图的大小不会变, 但是能够正常铺满父 div, 而且交互也没有问题.
但是这样整体效果看着会变小
