### ISSUE TITLE
关系图

### ISSUE THREAD

**Issue by hanruiying** [apache/echarts#9320]
echarts关系图可以自定义添加搜索的功能吗？实现搜索查询高亮

**Comment by 100pah** [comment]
如果仅仅是“让某些点高亮，其他点保持原样”，可以尝试使用：
`chart.dispatchAction({type: 'highlight', ...})` 

如果是“让某些点高亮其他点暗下来”，这目前只能通过 setOption 实现。

类似问题也参见 #9292

**Comment by liuttcc** [comment]
那如果是想让一些边（edge）也通过dispatchAction高亮呢？dispatchAction highlight对边的dataindex无效
