### ISSUE TITLE
line线图的动画效果只有从左到右的Easing吗？能不能提供从上到下或者从下到上的展开效果？

### ISSUE THREAD

**Issue by stlst** [apache/echarts#9322]
### One-line summary [问题简述]
line线图初始化或者数据更新的时候的动画效果，都是沿着x轴从左往右发生的缓动效果。如这个例子：
http://www.echartsjs.com/gallery/editor.html?c=line-easing 。 这样子，数据发生更新的时候带来的动画效果很突兀。

我希望，线图初始化或者数据更新的时候，是沿着y轴发生缓动效果的。如这个例子：https://www.dbface.com/assets/echarts/doc/example/line3.html

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.1
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

line chart的初始和数据更新动画效果如这个demo所示：
https://www.dbface.com/assets/echarts/doc/example/line3.html

### ECharts option [ECharts配置项]

```javascript
option = {
    grid: {
      left: '14%',
      right: '10%',
      top: '3%',
      bottom: '33%',
    },
    color: ['#ed312f'],
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      boundaryGap: false,
      axisLabel: {
        rotate: 45,
        },
      axisTick: {
        alignWithLabel: true,
        length: 0,
      },
    },
    yAxis: {
      type: 'value',
      axisTick: {
        length: 0,
      },
      nameTextStyle: {
        align: 'left',
      },
      axisLabel: {
        margin: 5,
      },
    },
    series: {
      data: [820, 932, 901, 934, 1290, 1336, 1310],
      type: 'line',
      smooth: true,
      itemStyle: { normal: { areaStyle: { type: 'default' } } },
    },
    // animation:false,
    animationEasingUpdate: 'backIn',
  }

```

**Comment by Ovilia** [comment]
Currently this is not supported and we have no easy way to implement this. Marked as new-feature.

**Comment by masami10** [comment]
Hi this feature will be available soon??? @Ovilia
