### ISSUE TITLE
symbolOffset not working in markLine data

### ISSUE THREAD

**Issue by ryanpei94** [apache/echarts#9325]
### One-line summary [问题简述]
Trying to change symbol by using 'image://' and change symbolOffset but it's not working in markLine data

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.2
+ Browser version [浏览器类型和版本]: Google Chrome 70.0.3538.77
+ OS Version [操作系统类型和版本]: 

### Expected behaviour [期望结果]
- Able to customise the symbol image position

### ECharts option [ECharts配置项]

```javascript
 markLine: {
               lineStyle: {
                        width: 1,
                        color: '#626c91',
                        type: 'solid'
                    },
                    data: [
                        [
     
                            {
                                xAxis: 50,
                                yAxis: 0,
                                symbol: 'none',
                            },
                   
                            {
                                xAxis: 50,
                                yAxis: 1800,
                                symbol: 'image://../../../assets/images/greyboxTest.png',
                                symbolSize: [160, 60],
                                symbolOffset: [0, '50%']
                            }
                        ]
                    ]
                }

```

### Other comments [其他信息]

<img width="147" alt="screen shot 2018-11-01 at 7 37 48 pm" src="https://user-images.githubusercontent.com/44670480/47849717-a80a7980-de0d-11e8-9996-0a87d99518e8.png">

**Comment by ryanpei94** [comment]
If the image "box" not transparent, it will cover the text "50, current 8000"

**Comment by stribulsergey** [comment]
the same problems. any news?

**Comment by WorldWideWebb** [comment]
Bump - symbolOffset doesn't work for me either.
