### ISSUE TITLE
当主图tooltip的trigger设为axis时，如何使得markPoint在mouseover到它上面时显示跟随的tooltip

### ISSUE THREAD

**Issue by southwhale** [apache/echarts#9331]
### One-line summary [问题简述]
当主图tooltip的trigger设为axis时，如何使得markPoint在mouseover到它上面时显示跟随的tooltip（即markPoint的tooltip的trigger设为item）。
（意图是想有两个独立的tooltip，主图的tooltip始终被固定在某个位置，markPoint上的tooltip可以跟随鼠标位置）
查了文档配置项，好像当前版本的markPoint已经没有了tooltip的配置项，那么想实现这样的功能该如何做？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0-rc.2
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: Win8、MacOs

### Expected behaviour [期望结果]

有两个独立的tooltip，主图的tooltip始终被固定在某个位置，markPoint上的tooltip可以跟随鼠标位置并且markPoint的tooltip

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]
[在线例子](http://gallery.echartsjs.com/editor.html?c=xJSw2eQjzT&v=2)

**Comment by 100pah** [comment]
MarkPoint 目前版本确实做不到这件事。
如果不使用 MarkPoint，而是使用第一个单独的系列，例如 scatter，那么可以单独在此系列上定制 
trigger 为 'item' 的 tooltip。

**Comment by huainanhai** [comment]
> > MarkPoint 目前版本确实做不到这件事。
> > 如果不使用 MarkPoint，而是使用第一个单独的系列，例如 scatter，那么可以单独在此系列上定制
> > trigger 为 'item' 的 tooltip。
> 
> 那么这个单独scatter系列里设置的tooltip和在option最外层设置的tooltip两者是否是独立的呢？我希望candlestick的tooltip始终固定位置，而scatter的tooltip可以被item的mouseover事件触发并跟随鼠标位置显示
> 补充：经过亲自试验，这两个tooltip是同一个tooltip，但是当是axis触发的时候位置是固定的，当是item触发的时候tooltip位置根据scatter的position配置项而定（这个配置项可以设置为top、bottom、left、right等等）

恐怕 scatter 里面 series.tooltip不会起作用吧

**Comment by iamweilee** [comment]
> 起作用

我的代码里的确是做到了

**Comment by iamweilee** [comment]
> > > MarkPoint 目前版本确实做不到这件事。
> > > 如果不使用 MarkPoint，而是使用第一个单独的系列，例如 scatter，那么可以单独在此系列上定制
> > > trigger 为 'item' 的 tooltip。
> > 
> > 
> > 那么这个单独scatter系列里设置的tooltip和在option最外层设置的tooltip两者是否是独立的呢？我希望candlestick的tooltip始终固定位置，而scatter的tooltip可以被item的mouseover事件触发并跟随鼠标位置显示
> > 补充：经过亲自试验，这两个tooltip是同一个tooltip，但是当是axis触发的时候位置是固定的，当是item触发的时候tooltip位置根据scatter的position配置项而定（这个配置项可以设置为top、bottom、left、right等等）
> 
> 恐怕 scatter 里面 series.tooltip不会起作用吧

我的代码里的确是做到了
