### ISSUE TITLE
双grid时添加多yAxis时报错：xAxis and yAxis must use the same grid

### ISSUE THREAD

**Issue by lsy9202** [apache/echarts#9332]
### One-line summary [问题简述]
双grid，双yAxis时报错：
echarts_v4.2.0rc2.js:39142 Uncaught Error: xAxis and yAxis must use the same grid
    at echarts_v4.2.0rc2.js:39142
    at ExtendedClass.<anonymous> (echarts_v4.2.0rc2.js:21073)
    at Array.forEach (<anonymous>)
    at each$1 (echarts_v4.2.0rc2.js:528)
    at ExtendedClass.eachSeries (echarts_v4.2.0rc2.js:21071)
    at Function.Grid.create (echarts_v4.2.0rc2.js:39120)
    at echarts_v4.2.0rc2.js:21377
    at each$1 (echarts_v4.2.0rc2.js:538)
    at CoordinateSystemManager.create (echarts_v4.2.0rc2.js:21376)
    at ECharts.update (echarts_v4.2.0rc2.js:27205)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.2.0rc2
+ Browser version [浏览器类型和版本]:chrome v70
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {
    grid:[{
        height:"40%"
    },{
        height:"40%",
        bottom:"20px"
    }],
    xAxis: [{
        type: 'category',
        gridIndex:0,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },{
        type: 'category',
        gridIndex:1,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    }],
    yAxis: [{
        type: 'value',
        gridIndex:0
    },{
        type:'value',
        gridIndex:0,
        position:'right'
    },{
        type: 'value',
        gridIndex:1
    },{
        type:'value',
        gridIndex:1,
        position:'right'
    }],
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        xAxisIndex:0,
        yAxisIndex:0
    },{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        xAxisIndex:1,
        yAxisIndex:1
    }]
};


```

**Comment by lsy9202** [comment]
我给不显示刻度和文字的yAxis加上min和max手动指定了范围，现在都显示刻度和文字的了，但是这个是必须的吗？yAxis.type=value时不是应该自动获取范围的吗？

var option = {
    grid:[{
        height:"40%"
    },{
        height:"40%",
        bottom:"40px"
    }],
    xAxis: [{
        type: 'category',
        gridIndex:0,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },{
        gridIndex:0
    },{
        gridIndex:1
    },{
        type: 'category',
        gridIndex:1,
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    }],
    yAxis: [{
        type: 'value',
        gridIndex:0
    },{
        type:'value',
        gridIndex:0,
        min:0,
        max:1500,
        scale:true,
        position:'right'
    },{
        type: 'value',
        min:0,
        max:1400,
        gridIndex:1
    },{
        type:'value',
        gridIndex:1,
        scale:true,
        position:'right'
    }],
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        xAxisIndex:0,
        yAxisIndex:0
    },{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        xAxisIndex:3,
        yAxisIndex:3
    }]
};

**Comment by Ovilia** [comment]
Seems to be a bug.
