### ISSUE TITLE
Heatmap tile emphasize on hover

### ISSUE THREAD

**Issue by cheezyXx** [apache/echarts#9339]
### One-line summary
Emphasize heamap tile on hover and its particular label on axis x and y.

### Version & Environment
+ ECharts version: 4.1
+ Browser version:  Chrome 70
+ OS Version: Windows 10 Pro

### Expected behaviour
I would like to change emphasize of heatmap tile on hover and its labels. How to do it? Is it possible?

![image](https://user-images.githubusercontent.com/35870262/47992905-7257e000-e0ee-11e8-9df8-abee960d164d.png)

**Comment by pissang** [comment]
I m afraid you cannot change the size of tile.
