### ISSUE TITLE
对于直角坐标系，能否在横坐标下面增加表格，类似附件中《大数据》一书的图

### ISSUE THREAD

**Issue by chenzugang** [apache/echarts#934]
这样的图能很好平衡图形与数据的关系，在一些场景下很实用。
![img_20141120_213403](https://cloud.githubusercontent.com/assets/496043/5152765/3d3a618c-723d-11e4-8d02-409cfad27cd9.jpg)

**Comment by R-River** [comment]
这种将图的图例和x轴标签与表格结合的形式貌似在经济、行业类研究中比较常见 我知道ec一直强调数据驱动 那么表格也应该可以看做一种特殊的数据展示方式吧 如果可以的话 还请考虑一下这种需求 谢谢
