### ISSUE TITLE
移动端强制横屏之后  X轴滚动条失效

### ISSUE THREAD

**Issue by ThinkerK** [apache/echarts#9342]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/39954388/47997189-f84b4980-e135-11e8-9311-a1cf9fc9498c.png)

X轴的滑动是左右滑动   但是移动端强制横屏后（就是将div旋转90度）  

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

强制横屏后  依然可以实现滑动

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/39954388/47997189-f84b4980-e135-11e8-9311-a1cf9fc9498c.png)

**Comment by ThinkerK** [comment]
强制横屏后  X轴方向的滑动失效了

**Comment by Ovilia** [comment]
How was the transform implemented? By CSS transform rotate?

**Comment by ThinkerK** [comment]
对的

**Comment by ThinkerK** [comment]
想问下   这个问题  有消息了吗 ？
