### ISSUE TITLE
当k线图的数据实时接收websocket推送来的数据并同步渲染k线时，鼠标在k线上不断移动时，十字线出现卡顿现象

### ISSUE THREAD

**Issue by southwhale** [apache/echarts#9351]
### One-line summary [问题简述]

当k线图的数据实时接收websocket推送来的数据并同步渲染k线时，鼠标在k线上不断移动时，十字线出现卡顿现象（图表的所有动画已被关闭）
打开浏览器的性能监控工具截了点图供参考。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts-4.2.0.rc2
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: win7、mac

### Expected behaviour [期望结果]

实时绘制k线时鼠标在k线上移动时，十字线能平滑跟随

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![11](https://user-images.githubusercontent.com/1096160/48069524-acb99e00-e210-11e8-84b7-e4de1a4b7d6a.png)
![22](https://user-images.githubusercontent.com/1096160/48069537-b3481580-e210-11e8-8d10-10ba88590ce1.png)
![33](https://user-images.githubusercontent.com/1096160/48069553-b9d68d00-e210-11e8-983a-a88d3d83d45b.png)
![44](https://user-images.githubusercontent.com/1096160/48070158-2dc56500-e212-11e8-9774-c51753064a8b.png)

**Comment by iamweilee** [comment]
目前做了一个缓解之计：监听页面的mousemove事件，每次记录事件触发时间戳，当实时数据到达时计算当前时刻与之前记录的时间戳二者时间差，若小于100ms则不更新图表，否则才更新。但这也只是缓解之计。期望更好的方法解决之。

**Comment by 13560280319** [comment]
我现在也遇到了这个问题，请问最后你是怎么解决的呢

**Comment by iamweilee** [comment]
> 我现在也遇到了这个问题，请问最后你是怎么解决的呢

echarts一直没修复 建议换个k线图表库
