### ISSUE TITLE
echarts  X轴分区填充不同颜色

### ISSUE THREAD

**Issue by kimmyXu** [apache/echarts#9355]
echarts  X轴分区填充不同颜色
浏览器引入echarts.js  版本echart4  
希望实现X轴不同区域填充不同颜色，效果如图，求大神帮忙

https://github.com/kimmyXu/incubator-echarts/blob/master/11.png

**Comment by pissang** [comment]
参考 http://www.echartsjs.com/examples/editor.html?c=line-sections
