### ISSUE TITLE
datazoom选中范围默认光标

### ISSUE THREAD

**Issue by 799677446** [apache/echarts#9358]
### One-line summary [问题简述]

鼠标移动到datazoom选中范围默认是move光标

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Google Chrome 版本 70.0.3538.77
+ OS Version [操作系统类型和版本]: 

### Expected behaviour [期望结果]

想要鼠标移动到datazoom选中范围能自定义光标

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/13121299/48114031-5ee87880-e298-11e8-864c-988101ca086d.png)

**Comment by leixu2txtek** [comment]
Any  update for this  issue, or some else workaround?
