### ISSUE TITLE
chart.on 点击事件无法抓到 toolbox.feature.dataZoom 是否被点击

### ISSUE THREAD

**Issue by jason19659** [apache/echarts#9365]
### One-line summary [问题简述]

chart.on 点击事件无法抓到 toolbox.feature.dataZoom 是否被点击

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.2.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

chart.on('click',function(params) {
		console.log(params)
	})
正常打印按钮的点击事件

**Comment by pissang** [comment]
chart.on 目前不支持 toolbox.feature.dataZoom 点击事件
