### ISSUE TITLE
数据缩放工具同时锁定X/Y比例

### ISSUE THREAD

**Issue by Supertramplee** [apache/echarts#9369]
### One-line summary [问题简述]
如果做如下设置：
```js
dataZoom: [
        {
            type: 'inside',
            xAxisIndex: 0,
            filterMode:'none',
            minValueSpan: size_x
        },
        {
            type: 'inside',
            yAxisIndex: 0,
            filterMode:'none',
            minValueSpan: size_y
        }],
```
数据缩放工具设置两个轴时，其中一轴会在边界状态时不响应滚轮缩放，导致X/Y比例失控。

### Expected behaviour [期望结果]

框选缩放组件 / 数据缩放组件 是否可以锁定X,Y的缩放比例？ 或锁定同时控制X/Y必须同时缩放？
另， 框选缩放工具是否可以增加最小缩放值 minValueSpan ?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]:Win10

**Comment by cradiy** [comment]
我有同样的需求，请问你解决了吗？
