### ISSUE TITLE
官网demo缺少依赖

### ISSUE THREAD

**Issue by kongminhao** [apache/echarts#9376]
### One-line summary [问题简述]

http://echarts.baidu.com/examples/editor.html?c=graph-webkit-dep 

从上述页面中下载的Demo缺少jQuery依赖

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![](http://caiji.scuseek.com/d3aae52373493882e5584cd39b5400b6.png)

**Comment by IanSmith123** [comment]
👍  同样遇到该问题， 手动引入jquery之后解决，对新手稍微有点不友好 :) 。

**Comment by SchnWalter** [comment]
Guys, could you please write in English?

I've recently started watching in project, and I believe that it has no chance of graduating from the Apache Incubator if people need use a translation service for everything.

Thank you!

**Comment by kongminhao** [comment]
@SchnWalter 

Yeah, you know this project was developed by chinese company named baidu, so I use chinese, but i was glad to translate for you.

This issue is about echarts' official website.

In the demo on url http://echarts.baidu.com/examples/editor.html?c=graph-webkit-dep

click the DOWNLOAD button will download a sample file with bug which lack the import of jquery.

**Comment by SchnWalter** [comment]
Yes, I know and I'm thankful for that. But now that the library is part of the Apache Incubator, which is great, it would be nice to gradually transition to English where it may be relevant or helpful for other people. It's nice to be able to search the web for an issue and find a discussion around it. Most people will search in English.

P.S. Thanks for all your work!
