### ISSUE TITLE
散点图当piecewise visualMap和y轴使用同一列数据时内容无法显示

### ISSUE THREAD

**Issue by ToughRover** [apache/echarts#9381]
### One-line summary [问题简述]
散点图，当y轴选择一个离散型数据列，并且设置了离散的visualMap和y轴共享一列数据时，图上的点显示为空白
![image](https://user-images.githubusercontent.com/30818686/48328271-46a0a100-e67e-11e8-87d9-cbfe48b85f38.png)

当去掉option中的visualMap部分时，图可以显示内容

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.1.0
+ Browser version [浏览器类型和版本]:  Chrome 70.0.3538.77 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: macOS 10.14

### Expected behaviour [期望结果]

当离散visualMap和y轴使用同一列数据时，图可以正确显示

### ECharts option [ECharts配置项]

option = {
  "xAxis": {
    "show": true,
    "nameLocation": "middle",
    "name": "AQI",
    "nameGap": 50,
    "type": "value",
    "nameTextStyle": {
      "fontSize": 13
    },
    "scale": true,
    "splitLine": {
      "show": true,
      "lineStyle": {
        "type": "dashed"
      }
    },
    "splitArea": {
      "show": false
    },
    "axisLine": {
      "symbol": [
        "none",
        "arrow"
      ],
      "symbolSize": [
        6,
        9
      ]
    }
  },
  "yAxis": {
    "show": true,
    "name": "LEVEL",
    "nameLocation": "end",
    "nameGap": 10,
    "nameTextStyle": {
      "fontSize": 13
    },
    "type": "category",
    "scale": true,
    "splitLine": {
      "show": true,
      "lineStyle": {
        "type": "dashed"
      }
    },
    "splitArea": {
      "show": false
    },
    "data": [
      "Good",
      "Slightly polluted",
      "Excellent",
      "Medially polluted"
    ],
  },
  "series": [
    {
      "type": "scatter",
      "name": "LEVEL",
      "data": [
        [
          73,
          "Good",
          "Good"
        ],
        [
          133,
          "Slightly polluted",
          "Slightly polluted"
        ],
        [
          91,
          "Good",
          "Good"
        ],
        [
          81,
          "Good",
          "Good"
        ],
        [
          110,
          "Slightly polluted",
          "Slightly polluted"
        ],
        [
          60,
          "Good",
          "Good"
        ],
        [
          61,
          "Good",
          "Good"
        ],
        [
          77,
          "Good",
          "Good"
        ],
        [
          78,
          "Good",
          "Good"
        ],
        [
          74,
          "Good",
          "Good"
        ],
        [
          46,
          "Excellent",
          "Excellent"
        ],
        [
          22,
          "Excellent",
          "Excellent"
        ],
        [
          36,
          "Excellent",
          "Excellent"
        ],
        [
          60,
          "Good",
          "Good"
        ],
        [
          83,
          "Good",
          "Good"
        ],
        [
          67,
          "Good",
          "Good"
        ],
        [
          100,
          "Good",
          "Good"
        ],
        [
          88,
          "Good",
          "Good"
        ],
        [
          176,
          "Medially polluted",
          "Medially polluted"
        ],
        [
          163,
          "Medially polluted",
          "Medially polluted"
        ],
        [
          79,
          "Good",
          "Good"
        ],
        [
          87,
          "Good",
          "Good"
        ]
      ],
      "symbolSize": 12,
      "dimensions": [
        {
          "name": "AQI",
          "type": "number"
        },
        {
          "name": "LEVEL",
          "type": "ordinal"
        },
        {
          "name": "LEVEL",
          "type": "ordinal"
        }
      ],
      "encode": {
        "x": 0,
        "y": 1
      }
    }
  ],
  "visualMap": [
    {
      "seriesIndex": 0,
      "dimension": 1,
      "type": "piecewise",
      "mapType": "color",
      "splitNumber": 8,
      "inRange": {
        "color": [
          "#fa8072",
          "#5ab1ef",
          "#7d9ec0",
          "#d87a80"
        ]
      },
      "categories": [
        "Good",
        "Slightly polluted",
        "Excellent",
        "Medially polluted"
      ]
    }
  ]
}

**Comment by Ovilia** [comment]
`dimension` should be 2 instead of 1. The data `[73, "Good", "Good"]` is in the form of `[xAxis value, yAxis value, data value]`, so we should use data value with visualMap.

**Comment by ToughRover** [comment]
I do not know how echarts handle the series data inside, actually the data I passed to series is a 2 columns, n rows data array, So I use dimension 1 as Y axis value as well as visualMap. It appears to me echarts copied the column for visualMap in this special case, this is not reasonable since users do not know the behavior of copying of a column after the original data is passed to echarts option. So I cannot define the correct dimension for visualMap in this special case. The behavior should be consistent with common case. (visualMap and y axis uses different column).

**Comment by Ovilia** [comment]
That's reasonable. We will have @100pah to have a further look at this. It may take some time.
Thanks for letting us know.
