### ISSUE TITLE
echarts-gl中的 grid3D.splitArea 能否设置贴图

### ISSUE THREAD

**Issue by 4074** [apache/echarts#9389]
### Version & Environment [版本及环境]
+ ECharts version [4.2.0]:
+ Browser version [Chrome 70.0.3538.67]:
+ OS Version [Windows7]:

![popo 20181113112523](https://user-images.githubusercontent.com/4033831/48389116-0e10ce00-e737-11e8-961c-51b598496507.png)

**Comment by Ovilia** [comment]
It doesn't seem so from the doc. Have @pissang for a double check.
