### ISSUE TITLE
Increase clickable area for scatter items

### ISSUE THREAD

**Issue by ngfx23** [apache/echarts#9395]
### One-line summary [问题简述]

离散图的点太小的话，在触屏一体机上很难点到，最小的半径设置成5，在电脑上可以比较容易显示提示语，触屏一体机上，要点出提示语的时候，一直点不到那个点

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by ngfx23** [comment]
想知道有没有办法可以增加点击的范围，但是不改变点的大小
![image](https://user-images.githubusercontent.com/17866124/48457800-e127ee00-e7fe-11e8-959f-25ec35855f22.png)

**Comment by Ovilia** [comment]
Currently, no. But this is a good idea and can be served as an improvement.
