### ISSUE TITLE
1000多条line看起来已经有点卡卡的了

### ISSUE THREAD

**Issue by huyansheng3** [apache/echarts#9400]
### One-line summary [问题简述]
数据量级比较大，渲染的时候一卡一卡的出来，感觉体验稍微差了一点。 看performance，渲染花了900多ms，有相关的办法优化吗？

附上测试文件的地址：
https://raw.githubusercontent.com/huyansheng3/echart-demo/master/scatter-linear-regression.html

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

期望的结果是不要卡卡卡卡

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Please try disable animation.

**Comment by huyansheng3** [comment]
is there any other way to enhance use experience?
almost total 4W points,  the amount maybe is not large.

**Comment by jason19659** [comment]
试试 增加 series.sampling
