### ISSUE TITLE
Consider adding LTTB sampling algorithm

### ISSUE THREAD

**Issue by lvdsimpson** [apache/echarts#9403]
### One-line summary [问题简述]

Please consider adding the LTTB (Largest-Triangle-Three-Buckets) down sampling algorithm as described here: https://github.com/sveinn-steinarsson/flot-downsample

### Expected behaviour [期望结果]
Charts with a large number of points can be down-sampled and displayed without losing their overall shape.  

### Other comments [其他信息]
Demo of LTTB with flot plugin and flot:
http://flot.base.is

**Comment by Ovilia** [comment]
Thanks. That seems to be a nice new feature.

**Comment by tkappenman** [comment]
Are there plans to add a threshold parameter for sampling strategies like in the flot demo?

**Comment by pissang** [comment]
@tkappenman This issue will be closed. You can open another issue to describe the feature request in more detail.
