### ISSUE TITLE
tree图label添加点击事件

### ISSUE THREAD

**Issue by lising1984** [apache/echarts#9409]
### One-line summary [问题简述]
我想实现点击label的时候，也可有click事件，以便于在节点的收起和展开状态不改变的状态下，点击的时候再做一些页面的功能处理。比如点击节点A，那么子节点收起或者展开，点击节点A 的label，实现页面的跳转功能。目前点击click的处理都在节点上，功能冲突了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts4.0.4
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
点击label的时候，也可有click事件

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MarRoar** [comment]
遇到了同样的需求，不知道怎么解决。
