### ISSUE TITLE
请问echart.util是什么呢?我查找api的时候没发现相关的介绍啊

### ISSUE THREAD

**Issue by 805399949** [apache/echarts#9413]
- [ ] I am using English in this issue.

## General Questions

- [ ] I have read the document and examples and tried to solve it by myself.
- [ ] I have searched for similar issues and that didn't help.
- [ ] I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with:
- [ ] issue type
- [ ] one sentence description in issue details
- [ ] demo if this is bug report

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*
- [ ] I have a bug to report
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*
- [ ] There's something wrong with the documents
- [ ] Others, or I'm not sure which issue types to choose here

## Issue Details

{DESCRIBE_HERE}

### Expected Behavior

{DESCRIBE_HERE}

### Current Behavior

{DESCRIBE_HERE}

### Online Example

{ADD_LINK_OF_DEMO_HERE}

{PASTE_RELATED_CODE_HERE}

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

{DESCRIBE_HERE}

## Environment

- ECharts version: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. {BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Please see https://github.com/apache/incubator-echarts/tree/master/src/util . The document should be improved.
