### ISSUE TITLE
graph 加载数据，产生off未定义错误

### ISSUE THREAD

**Issue by asdfhalkehflkajdhf** [apache/echarts#9422]
1、数据和错误信息可以查看以下两个链接。
这两个数据是使用程序跑出来，并不存在格式不对的问题。因为有的是可以显示

**错误显示**
https://www.xn--vusv75dba7g.cn/NLP/b/topicGraph.html

`echarts.js:54307 Uncaught TypeError: Cannot read property 'off' of undefined
    at echarts.js:54307
    at Graph.graphProto.eachEdge (echarts.js:52679)
    at ExtendedClass.render (echarts.js:54304)
    at Task.progress (echarts.js:24193)
    at doProgress (echarts.js:23115)
    at Task.taskProto.perform (echarts.js:23038)
    at echarts.js:27882
    at ExtendedClass.<anonymous> (echarts.js:21073)
    at Array.forEach (<anonymous>)
    at each$1 (echarts.js:528)`

**正常显示**
https://www.xn--vusv75dba7g.cn/NLP/a/topicGraph.html

２、在graph中我使用这个双击是不管用
chartObj.on('dblclick', function (params) {
console.log(params);
});

我试过4.1的多个版本，目前使用的echars版本是echarts-4.2.0-rc.2，
尝试去解决问题，但太深入了。

==================================================================

1, data and error messages can view the following two links.
These two data are running out of the program, and there is no problem of incorrect format. Because some can be displayed.
* * error shows * *
Https://www.xn--vusv75dba7g.cn/NLP/b/topicGraph.html
`echarts.js:54307 Uncaught TypeError: Cannot read property'off'of undefined
At echarts.js:54307
At Graph.graphProto.eachEdge (echarts.js:52679)
At ExtendedClass.render (echarts.js:54304)
At Task.progress (echarts.js:24193)
At doProgress (echarts.js:23115)
At Task.taskProto.perform (echarts.js:23038)
At echarts.js:27882
At ExtendedClass.<anonymous> (echarts.js:21073)
At Array.forEach (<anonymous>)
At each$1 (echarts.js:528) '
* * normal display * *
Https://www.xn--vusv75dba7g.cn/NLP/a/topicGraph.html
2, in graph, I use this double click is useless.
ChartObj.on ('dblclick', function (params) {
Console.log (params);
});
I tried more than 4.1 versions, and the echars version I use now is echarts-4.2.0-rc.2.
Trying to solve the problem, but too deep.

**Comment by asdfhalkehflkajdhf** [comment]
２、在graph中
		 我是用这个双击是不管用 
		 chartObj.on('dblclick', function (params) { 
			 console.log(params); 
	}); 

我试过4.1的多个版本，这个是echarts-4.2.0-rc.2

**Comment by Ovilia** [comment]
Can you provide the difference option between the normal and error chart?

**Comment by asdfhalkehflkajdhf** [comment]
> 你能提供正常和错误图表之间的差异选项吗？
>Can you provide the difference option between the normal and error chart?

谢谢，我已经找到问题，是在计算坐标时，y的值为NaN。从一开始我就找错了方向，因为坐标是随机计算的。并没有想到会是y值坐标出错。他们提示off没有定义。就直接进到错误代码行查找，最终没有结果。现在已经好了。
Thank you. I have found the problem. When calculating coordinates, the value of Y is NaN.　
[a.zip](https://github.com/apache/incubator-echarts/files/2591715/a.zip)

From the beginning, I found the wrong direction because the coordinates were random. I didn't expect it to be an error in the y value coordinate. They suggested that off was not defined. It goes straight to the wrong code line and finds no result. It's all right now.

但是，双击事件仍然无响应，代码见附件
[a.zip](https://github.com/apache/incubator-echarts/files/2591719/a.zip)
。
However, the double click event is still unresponsive, and the code is attached.

事件代码写法如下：
The event code is written as follows:
```
		g_myChart.on('dblclick', function (params) {
			console.log('dblclick');
		});
```
