### ISSUE TITLE
I can't get right-rendered GL-options ,in globe/environment-and-baseTexture-and-heightTexture  

### ISSUE THREAD

**Issue by Jet12138** [apache/echarts#9427]
- [ ] I am using English in this issue.

## General Questions

- [ ] I have read the document and examples and tried to solve it by myself.
- [x ] I have searched for similar issues and that didn't help.
- [x ] I have tried with the latest version of ECharts and still have this problem.

In this issue, I have provided information with:
- [ ] issue type
- [ ] one sentence description in issue details
- [ ] demo if this is bug report

## Issue Type

- [ x ] I have a question to ask about *how to use ECharts to ...*
- [ x ] I have a bug to report
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*
- [ ] There's something wrong with the documents
- [ ] Others, or I'm not sure which issue types to choose here

## Issue Details

when I used codes as follow:
   globe: {
            show: true,
            environment: '/public/space.jpg',   //外部太空环境
            baseTexture: '/public/earth.jpg',    //地球的纹理(这里用的山川河流)
            heightTexture: '/public/height.jpg',   //地球的高度纹理

            displacementScale: 0.04,
            shading: 'realistic',
            realisticMaterial: {
              roughness: 0.8
            },
            light: {
              ambient: {
                intensity: 0.4
              }
            },
            viewControl: {
              autoRotate: true,
              autoRotateDirection: 'ccw',
              distance: 160,
              minDistance: 60,
              miaxDistance: 300,
              autoRotateSpeed: 5,
              autoRotateAfterStill: 8,
              targetCoord: [113.762137,34.711329]
            },
          },
I can't get the rendered  'environment' , 'baseTexture' and 'heightTexture',but the default black envir and white earth.Sometimes when I change ' import echarts-gl ' to 'import 'echarts/dist/echarts-gl' ' and run the 'vue-cli-service serve' ,I got the right result. I found a fancy img in my browser console/network 

### Current Behavior

![image](https://user-images.githubusercontent.com/23096219/48689672-87f8f980-ec06-11e8-9309-1c1e1c313b4a.png)

### Online Example

{ADD_LINK_OF_DEMO_HERE}

 globe: {
            show: true,
            environment: '/public/space.jpg',   //外部太空环境
            baseTexture: '/public/earth.jpg',    //地球的纹理(这里用的山川河流)
            heightTexture: '/public/height.jpg',   //地球的高度纹理

            displacementScale: 0.04,
            shading: 'realistic',
            realisticMaterial: {
              roughness: 0.8
            },
            light: {
              ambient: {
                intensity: 0.4
              }
            },
            viewControl: {
              autoRotate: true,
              autoRotateDirection: 'ccw',
              distance: 160,
              minDistance: 60,
              miaxDistance: 300,
              autoRotateSpeed: 5,
              autoRotateAfterStill: 8,
              targetCoord: [113.762137,34.711329]
            },
          },

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [x ] ECharts GL
- [x ] Third-party libraries,Vue.js's  .vue

## Anything Else We Need to Know

{DESCRIBE_HERE}

## Environment

- ECharts version:   "echarts": "^4.2.0-rc.2",
    "echarts-gl": "^1.1.1",

- [ ] It happens only on certain browsers or operating systems. 

版本 70.0.3538.102（正式版本） （64 位）

**Comment by Jet12138** [comment]
![image](https://user-images.githubusercontent.com/23096219/48690912-71a16c80-ec0b-11e8-8037-92d5b84e2457.png)

**Comment by Jet12138** [comment]
It had been resolved. I changed a GPU-better computer.

**Comment by Jet12138** [comment]
2018-11-30 ， today, i redo 'vue-cli-service serve'  ,I found the white is back. I used the Vue CLI 3 ,so I found a rule when I wanted to fix it .  In the same folder,I make the component's config to use the echart-gl  effect and  put the earth.jpg ,height.jpg and space.jpg. But when I put the three jpgs in the public , I redo the  'vue-cli-service serve',I found it fixed. I do nothing but copy the same-three-jpgs in the public folder........ What is joking is that , then I DELETE the three jpgs in the 'public folder'. It is alse run as well. So, the problem is when can the echarts-gl run as 2+2=4?

**Comment by Jet12138** [comment]
我是中国的民工啦，欢迎用中文交流，解决这个bug.

**Comment by Jet12138** [comment]
I suggested put the three jpgs in the Vue CLI3 in the public folder. And the config for the 'globe' as following:
environment: './space.jpg', //外部太空环境
baseTexture: './earth.jpg', //地球的纹理(这里用的山川河流)
heightTexture: './height.jpg', //地球的高度纹理

**Comment by MONTYYYYY** [comment]
Any solution for this yet ?

**Comment by MONTYYYYY** [comment]
> I suggested put the three jpgs in the Vue CLI3 in the public folder. And the config for the 'globe' as following: environment: './space.jpg', //外部太空环境 baseTexture: './earth.jpg', //地球的纹理(这里用的山川河流) heightTexture: './height.jpg', //地球的高度纹理



> I suggested put the three jpgs in the Vue CLI3 in the public folder. And the config for the 'globe' as following: environment: './space.jpg', //外部太空环境 baseTexture: './earth.jpg', //地球的纹理(这里用的山川河流) heightTexture: './height.jpg', //地球的高度纹理

awesome stuff
