### ISSUE TITLE
lines3d 不支持动态加入数据

### ISSUE THREAD

**Issue by hxmwr** [apache/echarts#9453]
如果加入新的数据，然后 setOption， 所有动画会重新开始

**Comment by deqingli** [comment]
Hi, Please provide a detailed demo address for us to debug, and please describe the problem and the results you want, which I can't see from the picture. Thank you

**Comment by hxmwr** [comment]
http://gallery.echartsjs.com/editor.html?c=xYcH2bHnFW&v=2
I want to every received data point animated once only, cause my backend will push these different data points by random time interval and there are no way for supplying a whole bunch of data to echarts to render. Apparently echarts cannot understand my opinion and just cancel the ongoing animation and restart, that's not a smart way I think and it's not a bug yet, but I hope you consider this situation and provide an official solution, many thanks.

**Comment by hxmwr** [comment]
@Ovilia Can you help?

**Comment by GreenLv** [comment]
请问问题解决了吗？我最近也想使用动态加载的lines3D，但是数据一更新原来画的线就没有了。

**Comment by Tnon** [comment]
解决了吗？
