### ISSUE TITLE
legend 始终为一行显示

### ISSUE THREAD

**Issue by QinZonger** [apache/echarts#9465]
由于外部盒子宽度限制，柱状图的legend 显示为2行，怎么设置为一行。
`
legend: {
            data: ['直接访问', '邮件营销','联盟广告','视频广告','搜索引擎']
        },
`

**Comment by yizhengfeng-jj** [comment]
设置为一行的话，从理论上来讲第一个想法是让图例尽量小，想法如下
1：改变字体大小
2：减少图例之间的间距
option = {
 legend: {
  itemGap: '', 图例之间的间距，
  normal: {
      textStyle: {
       fontSize:'' // 改变字体大小

 }
  }
}

}
最后不行 跟设计商量，legend一行放不下的话，可以设置type: ‘scroll’,超出部分会滚动，也是在一行
option = {
 legend: {

 type:'scroll',
  itemGap: '', 图例之间的间距，
  normal: {
      textStyle: {
    

 }
  }
}

}
