### ISSUE TITLE
正负图提示出现错乱

### ISSUE THREAD

**Issue by thelongmarch** [apache/echarts#9467]
![image](https://user-images.githubusercontent.com/8542608/48999560-fb17e800-f191-11e8-9e86-16d21af7eb7c.png)

如图所示，这个怎么解决

**Comment by cuijian-dexter** [comment]
What is the expected effect?Please provide the corresponding option

**Comment by thelongmarch** [comment]
正负图，如果负数都是0就会出现这种情况

**Comment by thelongmarch** [comment]
在这里提供一种方案给可能遇到这个问题的人，label中formatter设置，如果负轴为0不显示
![image](https://user-images.githubusercontent.com/8542608/49065732-d6874300-f259-11e8-85bc-bfbaab563cf9.png)
