### ISSUE TITLE
使用lines绘制路径，如何用一张图片作为地图并和路径同步缩放？

### ISSUE THREAD

**Issue by fuguohong** [apache/echarts#9470]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [ x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ x] Required: issue type；（必填）issue 类型
- [ x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ x] Required: ECharts version；ECharts 版本

## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

我使用lines绘制了路径，如何用一张图片作为地图，当我放大、缩小、移动lines时，地图也同时变化保持其相对位置不变？

### Expected Behavior

当我缩放、拖动绘制的路径，地图图片和路径能同步移动不错位

### Current Behavior

当我缩放、拖动绘制的路径，地图图片能够同时缩放、移动，但是出现了比较严重的错位

### Online Example

THIS IS REQUIRED FOR ALL BUG REPORTS AND QUESTIONS!!! 如果是提问或报 bug 一定要提供这一项！

{ADD_LINK_OF_DEMO_HERE}

```
// div w=1200 h=800
// imgW 和 imgH 实际上保持了其宽高比，并非写死
var imgW = 1200
var imgH = 800
var data = [{
    coords: [
        [50, 50],
        [100, 100]
    ],
}, {
    coords: [
        [20, 30],
        [50, 50]
    ],
}, {
    coords: [
        [50, 50],
        [86, 12]
    ],
}]

var mapimg = {
    type: 'image',
    position: [0, 0],
    scale: [1, 1],
    style: {
        image: '1.jpg',
        width: imgW,
        height: imgH,
    }
}

var option = {
    graphic: [mapimg, ],
    xAxis: {
        min: 0,
        max: 100,
        type: 'value',
    },
    yAxis: {
        min: 0,
        max: 100,
        type: 'value',
    },
    series: [{
        type: 'lines',
        coordinateSystem: 'cartesian2d',
        symbol: 'circle',
        symbolSize: 8,
        data: data,
        lineStyle: {
            width: 2,
            opacity: 0.8
        },
    }],
    dataZoom: [{
            id: 'xZoom',
            type: 'inside',
            xAxisIndex: 0,
            filterMode: 'none'
        },
        {
            id: 'yZoom',
            type: 'inside',
            yAxisIndex: 0,
            filterMode: 'none'
        }
    ],
};
myChart.on('dataZoom', arg => {
    console.log(arg)
    const data = arg.batch[0]
    const start = data.start
    const end = data.end
    const scale = 100 / (end - start)
    let xoffset = mapimg.position[0]
    let yoffset = mapimg.position[1]
    for (let d of arg.batch) {
        if (d.dataZoomId === 'xZoom') {
            xoffset = 0 - (d.start / 100) * imgW * scale
        } else {
            yoffset = 0 - ((100 - d.end) / 100) * imgH * scale
        }
    }
    mapimg.scale = [scale, scale]
    mapimg.position = [xoffset, yoffset]
    myChart.setOption(option)
})

```

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

我在graphic中用image来显示图片， 在datazoom事件中对图片进行缩放平移。但是出现了较严重错位。不知道哪里有问题，或者是否有其他更好的方式来实现？

## Environment

- ECharts version；ECharts 版本: 4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
The feature is under development: support image and SVG on geo coords.
