### ISSUE TITLE
Need example for category based coloring of lines

### ISSUE THREAD

**Issue by klausb** [apache/echarts#9491]
I'm switching from vega-lite to echarts, but I'm stuck with the replication of a simple vega-lite example showing a multi-line chart with unknown categories. See the example here: https://vega.github.io/vega-lite/examples/line_color.html.

For each new category a new line is drawn in a separate color and the legend is extended. The key here is, that the categories (symbol names) are not known upfront and do not need to be specified.

Thanks,
klaus

**Comment by jason19659** [comment]
https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-stack

**Comment by klausb** [comment]
Hi,

this is not the same. I saw this one. The difference is, that all y values refer to a common set of x values, which is not the case for the vega-lite example. I wonder if you can specify x and y together in the series arrays, not just the y values.

**Comment by klausb** [comment]
Meanwhile I managed to render a chart, by creating multiple series on the fly. However the problem I see is that I'm forced to transform a column base data set into multiple 2-dimensional arrays.

Ideally, it would be possible to purely specify a config, w/o data transformation. 

Can this be achieved with dimensions, where the third dimension is driving the color and creating a new line for each new entry in the 3rd dimension?

**Comment by 100pah** [comment]
> this is not the same. I saw this one. The difference is, that all y values refer to a common set of x values, which is not the case for the vega-lite example. I wonder if you can specify x and y together in the series arrays, not just the y values.

```js
option = {
    legend: {},
    xAxis: {type: 'category'},
    yAxis: {},
    series: [
        {
            name:'A',
            type:'line',
            data: [
                ['x', 120], 
                ['z', 132], 
                ['a', 101]
            ]
        },
        {
            name:'B',
            type:'line',
            data: [
                ['y', 130], 
                ['a', 32], 
                ['z', 61]
            ]
        }
    ]
};
```


> Can this be achieved with dimensions, where the third dimension is driving the color and creating a new line for each new entry in the 3rd dimension?

Using

**Comment by klausb** [comment]
Thanks for the update.
