### ISSUE TITLE
How to set axisPointer snap to both X-axis and Y-axis?  如何让axisPointer同时吸附X轴和Y轴？

### ISSUE THREAD

**Issue by fakedestinyck** [apache/echarts#9504]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

PLEASE MAKE SURE OF ALL THE FOLLOWING OPTIONS IN REQUIRED FIELDS ARE TICKED (with x)!
Otherwise, the issue will not be answered.
And think before you tick. :)
请确保以下每项都打上勾了！并且确保都做了这些事哦~ 这将大量简化我们的工作流程，使你的问题更快速得到解答。

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

How to set axisPointer snap to both X-axis and Y-axis?

Currently, I set `yAxis.minInterval = 1`. When I attempt to move my mouse inside the graph, can I force the Y-axis line (horizontal line) of the axisPointer to move discretely from 1 to 2, 2 to 3, etc., rather than continuously from 1 to 2 (i.e. `1.00 1.01 1.02 ... 1.99 2`)?

如何让axisPointer同时吸附X轴和Y轴？
比如我设了y轴的最小刻度为1，我能不能让axisPointer的那根y轴的线不要连续移动，而是只会比如 1 2 3的这样移动?

### Expected Behavior

axisPointer snap to both X-axis and Y-axis.

axisPointer同时吸附X轴和Y轴。

### Current Behavior

axisPointer only snaps to X-Axis.

axisPointer只吸附在X轴上。

### Online Example

```
tooltip: {
	trigger: 'axis',
	axisPointer: {
		type: 'cross',
		label: {
			backgroundColor: '#6a7985'
		},
		snap: true
	}
},
```

## Topics

- [ ] Legend
- [x] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

N/A

## Environment

- ECharts version；ECharts 版本: 4.2.0 rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：N/A

**Comment by cuijian-dexter** [comment]
http://www.echartsjs.com/gallery/editor.html?c=doc-example/candlestick-axisPointer

**Comment by 100pah** [comment]
Currently, in an axis whose `type` is `'value'`, the `axisPointer` can only snap to data point, rather than axis tick.

Could I know why do you intend to make `axisPointer` snap to axis tick (e.g., 1, 2, 3)?
If the scenario is reasonable, it can be added as a new feature ~

**Comment by fakedestinyck** [comment]
> Currently, in an axis whose `type` is `'value'`, the `axisPointer` can only snap to data point, rather than axis tick.
> 
> Could I know why do you intend to make `axisPointer` snap to axis tick (e.g., 1, 2, 3)?
> If the scenario is reasonable, it can be added as a new feature ~

I'm making a ranking chart. And since the ranking could only be an integer, there's no reason that the y-axis label of the axisPointer would be a floating number rather than an integer. That is what I am thinking. @100pah
