### ISSUE TITLE
图表隐藏之后，窗体resize，此时再显示图表，图表变成一个变形的图片了。

### ISSUE THREAD

**Issue by Shu-Ji** [apache/echarts#952]
项目需要根据用户的不同需要显示不同的图表。

比如做成tab标签样式(类似bootstrap的tab控件，而非浏览器的标签)，希望选择不同的tab显示不同的图表，但是切换tab之后，如果用户缩放窗口，再切换回去，之前那个图表就乱掉了。因为数据量比较大，不希望每次点击标签重新请求数据。

比如图表位于div#main中：

``` javascript
$('#main').hide();
// 这个时候缩放窗口大小
$('#main').show();
```

**Comment by zhangbobell** [comment]
@Shu-Ji 我也碰到这个问题了，感谢你的提问让我解决了问题。但是仍然会出现 #1885 所说的问题，需要初始化前需要移除之前的事件处理函数。你可以看看。
