### ISSUE TITLE
关系图的节点symbol不支持gif图吗，请问有什么推荐的解决方案

### ISSUE THREAD

**Issue by Raj6666** [apache/echarts#9530]
调试了一下官网关系图的例子，关系图的节点symbol仅支持自定义的图片，但如果输入的是gif图片的话则gif无动效，请问有什么解决方案

**Comment by pissang** [comment]
echarts doesn't support animated gif image yet.

**Comment by Raj6666** [comment]
嗯嗯 我了解到因为echarts也是用canvas实现的，但因为在canvas上渲染gif的话永远只会渲染第一帧
所以我现在打算把gif解析成n张图片，然后setInterval每隔几毫秒就换一次图片，模拟生成一个gif试试
不过不知道会不会对浏览器性能有什么影响 @pissang

**Comment by Ovilia** [comment]
你可以试试看~

**Comment by PlayerYao** [comment]
svg格式的动图是可以支持的

**Comment by pissang** [comment]
@PlayerYao 赞想法，试了下用 svg 的渲染器确实可以支持 gif

**Comment by zhoupeihuang** [comment]
this.myChart = echarts.init(document.getElementById("main"),'dark',{renderer:'svg'});
就可以支持gif 完美

**Comment by noGarne** [comment]
使用svg渲染的时候label设置backgroundColor使用image的时候导入的png图片不显示
