### ISSUE TITLE
词云初始化显示可以从现在的渐进式配置成一瞬间显示所有的词吗？

### ISSUE THREAD

**Issue by yinuocode** [apache/echarts#9537]
现在的词云显示数据多的时候总是需要几秒钟才能显示完成，从中间向周围扩散的显示过程。
能否通过配置属性来达到一次性显示所有词，不要看到渲染过程。

**Comment by yinuocode** [comment]
另外词云可以缩放和拖拽吗，没找到相关配置呢
用的是 echarts4+echarts-wordcloud
望能回复

**Comment by Ovilia** [comment]
渲染过程的存在是因为渲染需要好几秒完成，如果白屏很久的话体验不是很好，所以现在不支持没有渲染过程的效果。
不支持缩放拖拽，欢迎 PR。
