### ISSUE TITLE
Only scrolling without scaling when using dataZoom

### ISSUE THREAD

**Issue by awxxxxxx** [apache/echarts#9546]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

How to disable scale chart elements when dynamically adding data?

In candlestick, when user move the chart and left boundary is reached, I will fetch data from remote server and put to chart. After that, the elements on chart was shrunk, even though set the fixed size like `barWidth`. 

Before(100 items):
![before](https://user-images.githubusercontent.com/7347183/49584908-cc6eee00-f997-11e8-86ac-996855fe57f0.png)

After(200 items):
![after](https://user-images.githubusercontent.com/7347183/49584888-b8c38780-f997-11e8-86a4-6e3ac6ca2f00.png)

Here is the chart option:

``` javascript
  dataset: {
    dimensions: ['date', 'open', 'close', 'high', 'low'],
    source: [],
  },
  dataZoom: [
    {
      type: 'inside',
      xAxisIndex: [0, 1],
      start: 50,
      end: 100,
      zoomLock: true,
    },
  ],
  xAxis: [
    {
      type: 'category',
      boundaryGap: false,
      axisLine: { lineStyle: { color: '#777' } },
      axisLabel: {
        formatter: function (value) {
          return echarts.format.formatTime('yyyy/MM', value);
        }
      },
      axisPointer: {
        label: {
          show: false,
        }
      },
      min: 'dataMin',
      max: 'dataMax',
    }, 
    {
      type: 'category',
      gridIndex: 1,
      scale: true,
      boundaryGap: false,
      splitLine: { show: false },
      axisLabel: { show: false },
      axisTick: { show: false },
      axisLine: { lineStyle: { color: '#777' } },
      splitNumber: 20,
      min: 'dataMin',
      max: 'dataMax',
      axisPointer: {
        label: {
          show: false,
        }
      },
    }
  ],
  yAxis: [
    {
      scale: true,
      splitNumber: 2,
      axisLine: { lineStyle: { color: '#777' } },
      splitLine: { show: true },
      axisTick: { show: false },
      min: 'dataMin',
      max: 'dataMax',
      axisLabel: {
        inside: true,
        formatter: '{value}\n'
      }
    },
    {
      scale: true,
      gridIndex: 1,
      splitNumber: 2,
      axisLabel: { show: false },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: { show: false }
    }
  ],
  grid: [{
    left: 20,
    right: 20,
    top: 20,
    height: 180
  }, {
    left: 20,
    right: 20,
    height: 40,
    top: 200
  }],
  series: [
    {
      type: 'candlestick',
      encode: {
        x: 'date',
        tooltip: ['open', 'close', 'high', 'low', 'volume'],
      },
      itemStyle: {
        normal: {
          color: '#ef232a',
          color0: '#14b143',
          borderColor: '#ef232a',
          borderColor0: '#14b143'
        },
        emphasis: {
          color: 'black',
          color0: '#444',
          borderColor: 'black',
          borderColor0: '#444'
        }
      },
    },
    {
      type: 'bar',
      name: 'volume',
      tooltip: {
        show: false,
      },
      encode: {
        x: 0,
        y: 5,
      },
      xAxisIndex: 1,
      barWidth: 2,
      yAxisIndex: 1,
    }]
```

### Expected Behavior

Only scrolling,  when dynamically adding data. It is a similar to [2789](https://github.com/apache/incubator-echarts/issues/2789).

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [x] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4.2.0-rc-2}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
What do you want to show when appending new data?

**Comment by awbear** [comment]
Thanks for reply. As I mentioned before, disable scale the graphic elements when appending new data and keep scrolling along the X axis available.

### Here are demos:

#### Expected Behavior:
![1544512820271](https://user-images.githubusercontent.com/7347183/49784711-2cc7ac00-fd59-11e8-8903-ce2e3e43fa0a.gif)

#### Current Behavior:
![1544513049032](https://user-images.githubusercontent.com/7347183/49784748-4bc63e00-fd59-11e8-85bf-5b0cc80a26b1.gif)

In the second demo, graphic elements was shrunk after pending data. The first shows that graphic elements will keep the fixed size, it's a common scene in candlestick. 

How to implement the feature as the first demo shows when using candlestick and dataset?

Thx.

**Comment by Ovilia** [comment]
Try this one: http://echarts.baidu.com/option.html#dataZoom-slider.zoomLock

**Comment by awbear** [comment]
Yes, I found this option in https://github.com/apache/incubator-echarts/issues/2789 and tried. It works without appending new data, but when adding more data all elements in chart was still scaled down. 

Here is my option:
```javascript
const options = {
 dataset: {
    dimensions: ['date', 'open', 'close', 'high', 'low'],
    source: [],
  },
  dataZoom: [
    {
      type: 'inside',
      xAxisIndex: [0, 1],
      start: 50,
      end: 100,
      zoomLock: true,
    },
  ],
  xAxis: [
    {
      type: 'category',
      boundaryGap: false,
      axisLine: { lineStyle: { color: '#777' } },
      axisLabel: {
        formatter: function (value) {
          return echarts.format.formatTime('yyyy/MM', value);
        }
      },
      axisPointer: {
        label: {
          show: false,
        }
      },
      min: 'dataMin',
      max: 'dataMax',
    }, 
    {
      type: 'category',
      gridIndex: 1,
      scale: true,
      boundaryGap: false,
      splitLine: { show: false },
      axisLabel: { show: false },
      axisTick: { show: false },
      axisLine: { lineStyle: { color: '#777' } },
      splitNumber: 20,
      min: 'dataMin',
      max: 'dataMax',
      axisPointer: {
        label: {
          show: false,
        }
      },
    }
  ],
  yAxis: [
    {
      scale: true,
      splitNumber: 2,
      axisLine: { lineStyle: { color: '#777' } },
      splitLine: { show: true },
      axisTick: { show: false },
      min: 'dataMin',
      max: 'dataMax',
      axisLabel: {
        inside: true,
        formatter: '{value}\n'
      }
    },
    {
      scale: true,
      gridIndex: 1,
      splitNumber: 2,
      axisLabel: { show: false },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: { show: false }
    }
  ],
  grid: [{
    left: 20,
    right: 20,
    top: 20,
    height: 180
  }, {
    left: 20,
    right: 20,
    height: 40,
    top: 200
  }],
  series: [
    {
      type: 'candlestick',
      encode: {
        x: 'date',
        tooltip: ['open', 'close', 'high', 'low', 'volume'],
      },
      itemStyle: {
        normal: {
          color: '#ef232a',
          color0: '#14b143',
          borderColor: '#ef232a',
          borderColor0: '#14b143'
        },
        emphasis: {
          color: 'black',
          color0: '#444',
          borderColor: 'black',
          borderColor0: '#444'
        }
      },
    },
    {
      type: 'bar',
      name: 'volume',
      tooltip: {
        show: false,
      },
      encode: {
        x: 0,
        y: 5,
      },
      xAxisIndex: 1,
      barWidth: 2,
      yAxisIndex: 1,
    }]
}
```

Here is my update logic(simplified):
```javascript
fetchData().then(resp => {
  let option = {
    dataset: {
      dimensions: ['date', 'open', 'close', 'high', 'low'],
      source: [....],
    },
  }
  option.dataset.source = prevSource.concat(resp.data)
  echarts.setOption(option, true)
})
```

**Comment by Ovilia** [comment]
Please provide a working demo at http://gallery.echartsjs.com/editor.html or http://jsfiddle.net . You may use setTimeout for the `fetchData` part.

**Comment by Ovilia** [comment]
Thanks. I can reproduce it now.
I think it should either be a bug (if `zoomLock` should constrict window size when data enters), or an enhancement (if `zoomLock` only constrict window size when dragging).
