### ISSUE TITLE
你好，我的代码使用了themeriver,但是它是本身就不支持鼠标事件的相应吗？

### ISSUE THREAD

**Issue by slience2014** [apache/echarts#9554]
- [ x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [ x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x ] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x ] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ x] Required: issue type；（必填）issue 类型
- [ x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ x] There's something wrong with the documents；文档有些问题
- [x ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

你好，我的代码使用了themeriver,但是它是本身就不支持鼠标事件的相应吗？

### Expected Behavior

点击某条河流，有鼠标事件响应

### Current Behavior

N

### Online Example

var dom = document.getElementById("container");
var myChart = echarts.init(dom,'macarons',{renderer: 'svg'});
var app = {};
var option = {

    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'line',
            lineStyle: {
                color: 'rgba(0,0,0,0.2)',
                width: 1,
                type: 'solid'
            }
        },
    },

    legend: {
        data: ['topic0', 'topic1', 'topic2', 'topic3', 'topic4']
    },
    dataZoom: [
        {
            show: true,
            realtime: true,
            start: 
            45,
            end: 85
        },
        {
            type: 'inside',
            realtime: true,
            start: 45,
            end: 85
        }
    ],

    singleAxis: {
        top: 50,
        bottom: 50,
        axisTick: {},
        axisLabel: {},
        type: 'time',
        axisPointer: {
            animation: true,
            label: {
                show: true
            }
        },
        splitLine: {
            show: true,
            lineStyle: {
                type: 'dashed',
                opacity: 0.2
            }
        }
    },

    series: [
        {
            type: 'themeRiver',
            clickable:true,
            data: dataset
           // itemStyle: itemStyle,
            
        }
    ]
};

    myChart.setOption(option);
    myChart.on('mouseover','series', function (params) {
    console.log("yes");
    console.log(params);
});

## Topics

- [ ] Legend
- [x] Tooltip
- [x ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4}

- [x] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Seems not supported yet.

**Comment by slience2014** [comment]
Thank you



    
    
        
            
                
                    
                        
                    
                    
                        
                            793919316
                            
                            
                                
                                    邮箱：793919316@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年12月11日 13:01，羡辙 写道： Seems not supported yet.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-echarts","title":"apache/incubator-echarts","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-echarts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ovilia in #9554: Seems not supported yet."}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-echarts/issues/9554#issuecomment-446073104"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/apache/incubator-echarts/issues/9554#issuecomment-446073104",

"url": "https://github.com/apache/incubator-echarts/issues/9554#issuecomment-446073104",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

},

{

"@type": "MessageCard",

"@context": "http://schema.org/extensions",

"hideOriginalBody": "false",

"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",

"title": "Re: [apache/incubator-echarts] 你好，我的代码使用了themeriver,但是它是本身就不支持鼠标事件的相应吗？ (#9554)",

"sections": [

{

"text": "",

"activityTitle": "**羡辙**",

"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",

"activitySubtitle": "@Ovilia",

"facts": [



]

}

],

"potentialAction": [

{

"name": "Add a comment",

"@type": "ActionCard",

"inputs": [

{

"isMultiLine": true,

"@type": "TextInput",

"id": "IssueComment",

"isRequired": false

}

],

"actions": [

{

"name": "Comment",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-echarts\",\n\"issueId\": 9554,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"

}

]

},

{

"name": "Close issue",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apache/incubator-echarts\",\n\"issueId\": 9554\n}"

},

{

"targets": [

{

"os": "default",

"uri": "https://github.com/apache/incubator-echarts/issues/9554#issuecomment-446073104"

}

],

"@type": "OpenUri",

"name": "View on GitHub"

},

{

"name": "Unsubscribe",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 421716378\n}"

}

],

"themeColor": "26292E"

}

]
