### ISSUE TITLE
The links.label of graph.force set show to true, graph will be lucency.

### ISSUE THREAD

**Issue by zhangchengshan** [apache/echarts#9557]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

When i set the show field to true in links.label of graph.force, the whole graph is lucency.
![image](https://user-images.githubusercontent.com/6310213/49715263-c5432b00-fc8a-11e8-9ef2-8441416e21b2.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/6310213/49715306-ddb34580-fc8a-11e8-922f-a879200f7fb2.png)

### Online Example
            option = {
                series: [{
                    type: 'graph',
                    layout: 'force',
                    animation: false,
                    label: {
                        normal: {
                            show:true,
                            position: 'right'
                        }
                    },
                    edgeLabel: {
                        show: true,
                        formatter: function(params) {
                            return params.data.in
                        }
                    },

                    focusNodeAdjacency: true,
                    draggable: true,
                    roam: true,
                    force: {
                        layoutAnimation:true,
                        gravity:0.01, 
                        edgeLength: 150, 
                        repulsion: 55
                    },
                    data: data.nodes,
                    links: data.edges
                }]
            };

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: 4.2.0-rc2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Cannot reproduce. Checkout this example: http://gallery.echartsjs.com/editor.html?c=xX_NLZRp5P and add `symbol: 'image://https://s1.ax1x.com/2018/03/10/9RqK0J.jpg'` after line 50th to see.

**Comment by zhangchengshan** [comment]
@Ovilia http://gallery.echartsjs.com/editor.html?c=x3Mizu7x8l&v=4

**Comment by zhangchengshan** [comment]
i found when i set label.show to true and not set linestyle, the graph is lucency.

**Comment by Ovilia** [comment]
OK. That seems to be a bug.

**Comment by zhangchengshan** [comment]
@Ovilia okey,  i think you can close this issue if this case is a bug.

**Comment by Ovilia** [comment]
@zhangchengshan It should be closed after the bug is fixed.
