### ISSUE TITLE
containLabel:true, 右边的文字还是被遮挡了

### ISSUE THREAD

**Issue by yizhengfeng-jj** [apache/echarts#9560]
## Issue Details
设置了containLabel: true ,然后设置了right:0，但是x轴的坐标还是被部分遮挡了
![image](https://user-images.githubusercontent.com/20452750/49777207-8076cd00-fd3a-11e8-9350-f356f9a4c3d7.png)

## Expected Behavior
我想要的效果是文字正好和右边距离为0，但是这样设置好像是图表距离右边为0了，但是containLabel：true,难道不包括右边的文字么，为什么左边设置left:0,文字被包含了，难道值对left,bottom有效果么

## Current Behavior

![image](https://user-images.githubusercontent.com/20452750/49777406-51ad2680-fd3b-11e8-947d-2bc3960653d7.png)

这里面的最后一个周日的 ‘日’字被遮住了，我想让周日显示出来，并且按照我设置的right:0,紧挨着最右边显示，我该如何去做了

**Comment by Ovilia** [comment]
I'm afraid it can only be achieved by setting the last label to be something like `'周日        '` so that it will appear to be left than the current position.

**Comment by 520zzj** [comment]
left的优先级比containlabel要高

**Comment by georgezouq** [comment]
@Ovilia 这块有计划优化吗

**Comment by susiwen8** [comment]
Let's track in #15562

**Comment by jhxxs** [comment]
> I'm afraid it can only be achieved by setting the last label to be something like `'周日 '` so that it will appear to be left than the current position.

这个方法挺有效。目前给 `x`轴的第一项前面填充它对应长度空格，最后一项后面填充对应长度的空格，`axisLabel`不会被遮挡了。
```js
{ 
  grid:{
    containLabel: true,
    left: "auto",
    right: "auto",
    bottom: 0
  }
}
```

**Comment by Rico00121** [comment]
{
  grid: {
          left: '26px',
          right: '3%',
          bottom: '3%',
        },
} 
可以给right加上 %的留白

**Comment by humorHan** [comment]
最后解决了吗？ 困扰很久...不能指定固定的left right  因为y轴标签宽度不定

**Comment by soeasyjx** [comment]
我也遇到了这个问题，有可靠的解决方案么

**Comment by Rico00121** [comment]
> 我也遇到了这个问题，有可靠的解决方案么

看起来只能调整grid属性在右边加上合适的百分比%留白

**Comment by soeasyjx** [comment]
> > 我也遇到了这个问题，有可靠的解决方案么
> 
> 看起来只能调整grid属性在右边加上合适的百分比%留白

官方就不能出来给一个偏移量设置的属性么

**Comment by gentlecoder** [comment]
好像目前只能通过设置right来解决，又更好的办法踢我一脚
