### ISSUE TITLE
点击toolbox的保存图片后，menu消失，需要移动鼠标才能再次显示

### ISSUE THREAD

**Issue by HaroldliGC** [apache/echarts#9561]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

点击toolbox的保存图片后，menu消失，需要移动鼠标才能再次显示

### Online Example

http://gallery.echartsjs.com/editor.html?c=x5sBbcJHtj&v=1

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by HaroldliGC** [comment]
![gif](https://user-images.githubusercontent.com/36347241/49777995-46132d00-fd46-11e8-87c6-16ec9c09e5c4.gif)
示例图

**Comment by Ovilia** [comment]
无法复现，请提供操作的浏览器及操作系统环境

**Comment by HaroldliGC** [comment]
> 无法复现，请提供操作的浏览器及操作系统环境

Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Windows 10 Enterprise 64-bit(10.0, Build 17134)

**Comment by Ovilia** [comment]
SVG 版本正常吗？

**Comment by HaroldliGC** [comment]
> SVG 版本正常吗？

但是我使用的时默认的canvas渲染

**Comment by HaroldliGC** [comment]
> 你试下 SVG 吧，我手边没有 window 电脑，暂时没法跟进

非常感谢，但是使用svg渲染也存在同样的问题。

**Comment by Ovilia** [comment]
暂时不需要其他信息了，谢谢。等下周我找个 windows 机器测试下，抱歉排期比较紧。
