### ISSUE TITLE
堆叠图markPoint坐标轴显示叠加

### ISSUE THREAD

**Issue by shenghou** [apache/echarts#9564]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ ] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

在堆叠图中添加markPoint，markPoint的坐标是根据data大小计算得来的，由于图是堆叠来的，所以越往上面图的markPoint坐标越偏。

例如两条时间序列的折线图在某个点分别有值100、200  ，那么上面条线的坐标值为300，这样markPoint的坐标就会偏下；

如图
![image](https://user-images.githubusercontent.com/24260845/49789823-df067000-fd67-11e8-810e-f27f804e8b2e.png)

### Expected Behavior

希望markPoint的坐标也能堆叠

## Topics

- [x] MarkPoint

## Environment

- Any

**Comment by shenghou** [comment]
在堆叠图中markPoin type 设置为max min 位置也是错误的，
http://gallery.echartsjs.com/editor.html?c=xB1p_RMTdG

**Comment by xiaoYown** [comment]
这个问题留了好久
