### ISSUE TITLE
title under series[i]-gauge not working

### ISSUE THREAD

**Issue by Renhj90520** [apache/echarts#9569]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [x] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

There is a 'title' under series[i]-gauge, I set its properties, but it is not working.

I have two series in my chart, I noticed there is a 'title' under series[i]-gauge, I think it should give a title for each series, but it isn't shown, I wonder what is this 'title' for?
{
      series: [
        {
          title: {
            show: true,
            text: "CPU使用率",
            color: "#fff",
            fontSize: 12,
            offsetCenter: ["50%", "50%"]
          },
          name: "CPU使用率",
          type: "gauge",
          min: 0,
          max: 100,
          radius: "70%",
          center: ["50%", "50%"],
          startAngle: 180,
          endAngle: 0,
          splitNumber: 4,
          axisLine: {
            lineStyle: {
              color: [
                [0, "rgba(16, 86, 187, 0.57)"],
                [1, "rgba(16, 86, 187, 0.57)"]
              ],
              width: 3,
              shadowColor: "#fff",
              shadowBlur: 10
            }
          },
          axisTick: {
            length: 6,
            lineStyle: {
              color: "auto",
              shadowColor: "#fff",
              shadowBlur: 10
            }
          },
          splitLine: {
            length: 10,
            lineStyle: {
              width: 3,
              color: "auto",
              shadowColor: "#fff",
              shadowBlur: 10
            }
          },
          pointer: {
            length: "50%",
            width: 3
          },
          itemStyle: {
            color: "#fff"
          },
          axisLabel: {
            color: "#fff"
          },
          detail: {
            color: "#fff",
            formatter: function(val) {
              return val + "%";
            },
            fontSize: 13
          },
          data: [{ value: "52" }]
        }
      ]
    }
## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4.1.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Hi. Please refer to the doc. There's no `title` under series, but it's under `option`, and can be an array.

**Comment by Renhj90520** [comment]
@Ovilia  Hi, Thanks for your reply. I'm referring the doc v4.x, and the url is http://echarts.baidu.com/option.html#series-gauge.title
