### ISSUE TITLE
globe中使用scatter3D没办法触发dispatchAction

### ISSUE THREAD

**Issue by undefinedTL** [apache/echarts#9573]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [√] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [√] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [√] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ ] Required: issue type；（必填）issue 类型
- [ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [√] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [√] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

在globe中使用dispatchAction触发scatter3D的tooltip无效

### Expected Behavior

我想要在图形渲染完毕后，初始化一个tooltip

### Current Behavior

但是现在使用文档中指出的dispatchAction并没有用，我在option中使用的tooltip可以正常使用

### Online Example

```
var globel = echarts.init(document.getElementById('globe'));
		
		const option = {
			// backgroundColor: '#000',
			visualMap: {
				show: false,
				min: 0,
				max: 60,
				inRange: {
					symbolSize: [1.0, 10.0],
					opacity:[1,0.5]
				}
			},
			tooltip: {
				trigger: 'item',
				alwaysShowContent:true,
				formatter: function(prams,d,callback){
					return prams.value
				},
			},
			globe: {
				baseTexture: require('../assets/world.png'),
				globeOuterRadius: 100,
				displacementScale: 0.1,
				viewControl:{
					autoRotate:false
				},
				postEffect:{
					bloom:true,
					screenSpaceAmbientOcclusion:true
				},
				shading: 'color',
				z: 9
			},
			series: {
				type: 'scatter3D',
				coordinateSystem: 'globe',
				blendMode: 'source-over',
				symbolSize: 2,
				itemStyle: {
					// color: 'rgb(148, 148, 148)',
					color:'#b4b4b4',
					opacity: 1
				},
				data: data
			}
		}
*******************************
		globel.dispatchAction({
			type:'showTip',
			seriesIndex:0,
			dataIndex:1
		})
```

## Topics

- [ ] Legend
- [√] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by chenjun1996** [comment]
同样的问题，什么原因？？
