### ISSUE TITLE
Using dataZoom config, there is a problem when update data

### ISSUE THREAD

**Issue by justb** [apache/echarts#9586]
In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [ ] Required: issue type
       Maybe is a bug
- [ ] Required: one sentence description in issue details
       Using dataZoom config, there is a problem when update data, the chart is going to be weird
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
![image](https://user-images.githubusercontent.com/22002343/49981777-88ca4480-ff94-11e8-8345-05df87174e1c.png)

I click button at right-top, just update series data

![image](https://user-images.githubusercontent.com/22002343/49981794-a3042280-ff94-11e8-93f5-08b45e0526db.png)

- [ ] Required: ECharts version；ECharts 版本
3.8.5

**Comment by Ovilia** [comment]
What's the problem here?
