### ISSUE TITLE
How can I fix the position of elements when datazoom ?

### ISSUE THREAD

**Issue by drorhilman** [apache/echarts#9593]
I have some elements on the scatter plot which I would like to be fixed in the same visual position when the data zoom active. 
How can I translate a fixed position on the x==0 when data-zooming ?
or in other words: how can I know where is the new relative position of the data-point when zooming ?

currently, I try to do it like that, but it doesn't work...

```
INIT_PIXELS = chart.convertToPixel({'seriesIndex': 0}, (0,0))

function zoomEvent(params){
    new_pox_x = chart.convertFromPixel({'seriesIndex': 0}, INIT_PIXELS)[0]
   // then I update the series ... to contain this new_pos_x
   // but it does not work right.
}
```

**Comment by Ovilia** [comment]
Hi. This should be improved later.
