### ISSUE TITLE
4.2.0rc2 brush 只能选择前400个点

### ISSUE THREAD

**Issue by sola1121** [apache/echarts#9605]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [x] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

使用4.2.0rc2 时, brush只能选择到前400个点, 而使用3.8.5版本则可以正常工作.
when I use version 4.2.0rc2, the brush function just can selected first 400 points in dataIndex, but with version 3.8.5, it work right.

![2018-12-17 15-09-24](https://user-images.githubusercontent.com/33486730/50127168-ef0fd980-02aa-11e9-99da-0207494092cf.png)
以上是使用4.2.0rc2版本, 但是只能选择到前400个点.
above is version 4.2.0rc2, it just can select first 400 points
![2018-12-17 15-10-14](https://user-images.githubusercontent.com/33486730/50127206-21b9d200-02ab-11e9-81c5-21bddab0fcda.png)
以上是使用3.8.5, 这个可以正常的工作.
above is version 3.8.5, it work right

### Expected Behavior

希望能像3.8.5一样工作

能够正确的选出范围中的点.

### Online Example

var option = {
        animation: true,
        title: {
            backgroundColor: '#333',
            text: default_title_text,
        },
        tooltip:{
            show: true, trigger: 'item',
            enterable: true, hideDelay: 150,
        },
        brush: {
            toolbox: ["lineX", "lineY", "clear"],
            throttleType: 'debounce',
            throttleDelay: 300,
            seriesIndex: 1,   // "all",
            inBrush: {color: "#FFAB91"},
            outOfBrush: {colorAlpha: 0.1}
        },
        dataZoom: [
            {type: "slider", orient: "horizontal"}, {type: "inside", orient: "horizontal"}
        ],
        xAxis: {
            name: "频率", scale: true, max: max_X, min: min_X,
        },
        yAxis: {
            name: "电平", max: max_Y, min: min_Y,
        },
        series: [
            // 第一组数据
            {
                name: "监测电平连线",
                data: original_data["level"],   //  [[a1, a2], [a3, a4], ...]
                type: 'line',
            },
            // 第二组数据
            {
                name: "监测电平点",
                data: original_data["level"],   // 希望brush出来的, want to be brush out, like [[a1, a2], [a3, a4], ...]
                type: "scatter",
            },
            // 第三组数据
            {
                name: "告警频率点",
                data: alert_signal_data_handler(alert_data, max_Y),
                type: "scatter",
            },
            // 第四组数据
            {
                name: "信号频率点",
                data: alert_signal_data_handler(signal_data, min_Y),
                type: "scatter",
            }
        ]
    }

 function renderBrushed(params) {
        // brush事件, 这里将会进行一些简单的统计与计算
        var brushComponent = params.batch[0]
        var level_index = brushComponent.selected[1].dataIndex  // 获取series[1]
...do something
}

以上是我部分相关option配置
## Topics

- [ ] Legend
- [ ] Tooltip
- [x] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {4.2.0rc2}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by lishihong** [comment]
为什么关了啊，3.8.5可以，4.2版本不行啊
