### ISSUE TITLE
双Y轴距离图标的距离如何设置？

### ISSUE THREAD

**Issue by dtboy1995** [apache/echarts#9606]
<img width="518" alt="default" src="https://user-images.githubusercontent.com/19227547/51509845-a1e8cf80-1e35-11e9-848c-9ca49f73cbf2.PNG">

粉色区域的距离如何设置 thanks a lot

**Comment by dtboy1995** [comment]
@deqingli 谢谢回复
文档中http://echarts.baidu.com/option.html#xAxis.boundaryGap说的很清楚，类目轴没有别的设置了，我是想设置类似`boundaryGap: ['20%', '20%']`,类目轴中无效

**Comment by Ovilia** [comment]
Do you want to set the position of chart area? That should be http://echarts.baidu.com/option.html#grid

**Comment by iamweilee** [comment]
我猜楼主的意思是网格正常画  但是网格里的内容希望能做到距离左右两边指定的空间，比如50px或者20%这样

**Comment by iamweilee** [comment]
我猜楼主的意思是网格正常画 但是网格里的内容希望能做到距离**网格**左右两边指定的空间，比如50px或者20%这样

**Comment by dtboy1995** [comment]
@iamweilee 您说的对

**Comment by Ovilia** [comment]
@100pah Why is `boundaryGap` not available for category axis?
