### ISSUE TITLE
Themeriver: some properties of label don't take effect in themeriver

### ISSUE THREAD

**Issue by yingxu9871** [apache/echarts#9614]
- [ x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x ] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [ x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x ] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x ] Required: issue type；（必填）issue 类型
- [x ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

label position , label rotate, label offset properties don't take effect in themeriver.

1. Use online demo http://echarts.baidu.com/examples/editor.html?c=themeRiver-basic to reproduce the issue: 
2. add below in series of themeriver, there is no change according to label position, rotate and offset. 
            label: {
                show: true,
                position: 'top',
                rotate: 90,
                offset: [50,80]
            },  

### Expected Behavior

Those properties should work.  And as my themeriver begin with small value, the label are overlapped, do you have better solution to avoid this issue?

![image](https://user-images.githubusercontent.com/28331441/50203413-683b2980-039c-11e9-8d4c-79343eda1be7.png)

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
@pissang @100pah  we should discuss the position of the label about `polygon`. I think we should some special work to compute the position of the label.

**Comment by deqingli** [comment]
Follow is my idea:
1. We can show the label of each stream in the blank area of the diagram just like D3, though I am confused about how to determine the position of the blank area.

![image](https://user-images.githubusercontent.com/13548221/67540853-935b7b80-f719-11e9-942a-a91af88b46f8.png)

2. We can place the label in the largest height of each stream.

<img width="567" alt="themeRiver_label" src="https://user-images.githubusercontent.com/13548221/67541038-1b418580-f71a-11e9-9485-a54b4401de3c.png">

For the above two scenarios, we can design our setting like this:
```js
label: {
    // inside represent place the label in the largest height of each stream
    // outside represent place the label in the blank area
    position: 'inside' or 'outside'
}
```

**Comment by pissang** [comment]
I'm not sure about the first one.

About the `inside`. I think it's a good idea to find the largest height range.

**Comment by 100pah** [comment]
I agree. Find the largest height is a practical way. 
And about "place in some blank area", I am not sure how the labels are able to connect to the polygon if all of the label need to be displayed.

**Comment by deqingli** [comment]
#11497

**Comment by deqingli** [comment]
Since the discussion above, we can define `series.themeRiver.label` as below:
 ```js
label: {
    position: 'left' or 'right' or 'inside'
}
```
While with the position `left' or 'right', the label may overlapping as the picture referenced in the issue show, so we should discuss a proposal to solve this problem.
