### ISSUE TITLE
 xAxis 的类型为 time 时  zoomData 的数据阴影跟图表不一致

### ISSUE THREAD

**Issue by Eunknight** [apache/echarts#9616]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；4.1.0

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

xAxis的`type`为`time`，数据不连贯时  `zoomData` 的 `type: 'slider'`, 数据阴影(DataShadow) 跟图表对不上。

### Expected Behavior

数据阴影跟图表一一对应

### Current Behavior

数据阴影跟图表对不上，数据阴影的间隔为数据量的平均间隔。
比如总时间为12小时. 1小时,11小时,12小时,有三条数据，数据阴影的分布为三大段.会分布在中间，而不是两边。

### Online Example
https://jsfiddle.net/Eunknight/uam3hx7n/41/

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: 4.1.0
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by tmtron** [comment]
maybe this is related to #10082
