### ISSUE TITLE
brush doesn't clear if I mouseout of the chart

### ISSUE THREAD

**Issue by kojilab** [apache/echarts#9627]
The brush doesn't clear if I mouseout of the chart. The event triggers but doesn't clear with single and removeOnClick.

Let me know if there's a workaround. Thanks

**Comment by cuijian-dexter** [comment]
can you provide a demo？

**Comment by kojilab** [comment]
Here you go. Video attached. It's a single page app and I refresh results after the brush thing happens. You can clearly see that the mouse out doesn't clear the brush compared to when I stay within the canvas.
https://drive.google.com/file/d/1GoH4N1Hlvo-eO3nLLDC5LiTqCEoB95WH/view?usp=sharing

**Comment by pissang** [comment]
@100pah  It seems to be a bug of `dataZoom` in toolbox component.

**Comment by kojilab** [comment]
Thanks @pissang If there's a workaround for now, let me know. Thanks a lot!!

**Comment by 100pah** [comment]
Probably "globalmouseup" event should be added in zrender for `brush` and `toolbox dataZoom`.

**Comment by kojilab** [comment]
@100pah In this demo i use the brushSelected event

**Comment by vvkee** [comment]
@kojilab Hi, did you solve it?
