### ISSUE TITLE
力导向图的问题

### ISSUE THREAD

**Issue by liuyang1** [apache/echarts#963]
我主要需要力导向图这种模式,作为无向图的展现方式.发现下面的一些问题:
1, 节点没有label选项支持.
一般而言节点的key和显示的label不一定是一样的.但是这里我没有找到label的支持.只能直接使用name这个属性,这里兼了以上两者的功能,但是key不同,label相同的情况就没有办法了.
2, 没有缩放功能支持
虽然实例中有中等规模的力导向图的示意,但是对于力导向图不支持缩放功能.
地图的缩放功能,我没有去尝试.一般的dataZoom属性,完全没有效果.
roam选项支持的滚轮缩放,也没有.
没有缩放,那么实际应用只能支持小规模的图,局限太大了.

如果是我错漏了哪个地方,多谢指出.

**Comment by aha-09** [comment]
> 不过将roam设置为scale或者move,那么两个功能分别都是可以的.
> 将roam设置为true的时候,缩放和移动都不可以的.

树图也出现了这种情况  （版本：5.0.1）
