### ISSUE TITLE
关系图Graph，symbolSize为数组时，节点实际会占据一个宽高中较大值的正方形区域，导致箭头位置不准

### ISSUE THREAD

**Issue by wonderjar** [apache/echarts#9653]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

关系图Graph，symbolSize为数组时，节点实际会占据一个宽高中较大值的正方形区域(而不是指定了宽高的长方形区域)，导致箭头位置不准

### Expected Behavior

箭头是 
节点1 -> 节点2
节点2 -> 节点3

### Current Behavior

![image](https://user-images.githubusercontent.com/8806004/50505991-82b68680-0ab1-11e9-993d-0ef71cd5d97f.png)

所有节点其实有个隐含的高度，才导致箭头的起点，终点不对，看起来甚至反转了

### Online Example

http://jsfiddle.net/wonderjar/4sLb1ufc/

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

放缩可以看出箭头的翻转，放大后可以了解到节点的真实的上边缘，下边缘

## Environment

- ECharts version；ECharts 版本: 4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
Similar to #5038. 
Needed to be enhanced.

**Comment by Irislm** [comment]
有什么hack的解决方案吗

**Comment by caoyukun0430** [comment]
请问这个箭头起始点问题，以及箭头被覆盖的情况有解决方法了吗？谢谢

**Comment by panghu-alt** [comment]
我也遇到了这个问题，迷茫。
