### ISSUE TITLE
Treemap / Sunburst

### ISSUE THREAD

**Issue by rajpatelukyahoo** [apache/echarts#9663]
- [ x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions
Is there any way to provide data from CSV file or an array to Treemap or Sunburst type charts?

## Issue Type

- [ x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Topics

- [ ] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by 100pah** [comment]
Current the input data of tree/treemap/sunburst should be organized into a tree.
But could I have more details about your expectation: 
why needs input as an array what the array like?

**Comment by rajpatelukyahoo** [comment]
Here is the text file containing my data in CSV format.


Thank you for your response.

[SENTIMENT.txt](https://github.com/apache/incubator-echarts/files/2723874/SENTIMENT.txt)

**Comment by pmenga52** [comment]
Hi,
May I push up this post, I also try to get data from csv files (OK for a lot of chart types), and for sunburst graph, I don't know how to create the data tree. 
Here is an example of csv file and the resulting sunburst graph (sorry, it has been graphed with highcharts javascript library.
[sunburst.txt](https://github.com/apache/incubator-echarts/files/3720766/sunburst.txt)

<img width="599" alt="sunburst" src="https://user-images.githubusercontent.com/45292014/66702692-9f534080-ed0a-11e9-944d-04183412a9f2.png">
