### ISSUE TITLE
legend does not respect itemStyle.opacity

### ISSUE THREAD

**Issue by tmalaher** [apache/echarts#9670]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [x] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request
- [ ] I have a feature to enhance
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

When overriding the itemStyle in a data series, the legend does not respect the opacity setting.

### Expected Behavior

Setting the data[n].itemStyle.opacity should affect both the plot area and the legend.

### Current Behavior

![legend opacity bug](https://user-images.githubusercontent.com/41802/50603562-25875000-0e78-11e9-97b1-4fcbcfcac59f.png)

Setting the itemStyle.color and opacity results in the legend showing a fully opaque item of the correct color. The opacity is ignored.

### Online Example

Using 4.1.0 (only one I could get a link to from jsfiddle):
<http://jsfiddle.net/yL64mkn0/>

Full code:

```javascript
var option = {
            title: {
                textStyle: {fontSize:12},
                text:'Legend Opacity Bug'
            },
            toolbox: {
             	 show: true,
             	 feature: {
             	 	 saveAsImage: {show: true}
             	 }
            },
            legend: {
                data:['Value2','Border'],
                right: '10%'
            },
            xAxis: {type: 'time'},
            yAxis: {type: 'value'},
            series: [
				{
                name: 'Value2',
                type: 'line',
                data: [
					[1546377489000, 1.26],
					[1546377589000, 3.68],
					[1546377689000, 5.24],
					[1546377789000, 7.82],
					[1546377889000, 9.95],
					[1546377989000, 11.81],
                	[1546378089000, 13.04],
					[1546378189000, 5.33],
					[1546378289000, 7.84],
					[1546378389000, 3.58],
					[1546378489000, 1.96],
				]
				},
            {
            	name: 'Border',
                type: 'bar',
				itemStyle: {  color: 'green', opacity: 0.3 },
                markArea: {
                            itemStyle: 
                            	{ normal: { color: 'green', opacity: 0.3 }},
                            label: {
                                normal: {
                                	show: false,
                                    position: ['0%','50%'],
                                    color: '#000'
                                }
                            },
                            data: [
								[{
                                    name: 'Lower Critical',
                                    yAxis: -99999999999
                                }, {
                                    yAxis: 1.5
                                }],
								[{
                                    name: 'Upper Critical',
                                    yAxis: 9.5
                                }, {
                                    yAxis: 99999999999
                                }]
                            ]
                }
            }
            ]
        };
```

## Topics

- [x] Legend
- [ ] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Anything Else We Need to Know

N/A

## Environment

- ECharts version 4.2.0-rc2；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
Currently only color and symbol will be reflected in the legend.
