### ISSUE TITLE
希望多条折线时，浮动到某条折线，tooltip展示该条折线信息

### ISSUE THREAD

**Issue by Cyycl** [apache/echarts#9677]
- [ ] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

- [X] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [X] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [X] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [X] Required: issue type；（必填）issue 类型
- [X] Required: one sentence description in issue details；（必填）一句话的问题描述
- [X] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [X] Required: ECharts version；ECharts 版本

## Issue Type

- [X] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

多条折线时，浮动到某条折线，tooltip展示该条折线信息，而不是全部折线信息

### Expected Behavior

多条折线时，浮动到某条折线，tooltip展示该条折线信息，而不是全部折线信息，方便查看某条折线的数值，类似antv功能，https://bizcharts.net/products/bizCharts/demo/detail?id=line-series&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE

### Current Behavior

多条折线时，tooltip始终展示的是全部折线信息

### Online Example
https://bizcharts.net/products/bizCharts/demo/detail?id=line-series&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE

## Topics

- [ ] Legend
- [X] Tooltip
- [ ] Event
- [ ] Performance
- [ ] SVG
- [ ] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；ECharts 版本:  v4.1.0

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
You can set [trigger](http://echarts.baidu.com/option.html#tooltip.trigger) to `'item'`. But it's not possible to support both axis trigger and item trigger now.
