### ISSUE TITLE
饼图/圆环图如何将份额值 显示在图例后面？

### ISSUE THREAD

**Issue by yilan99** [apache/echarts#968]
如图所示

![0b7c53adce03479a5060a391039d5393](https://cloud.githubusercontent.com/assets/9817065/5215016/fe196fc8-765d-11e4-93b2-d2bbf9c5ab49.JPG)

**Comment by lightforme** [comment]
这个问题还没有解决吗

**Comment by LinBoLen** [comment]
+1

**Comment by puppetDev** [comment]
+1
