### ISSUE TITLE
旭日图label 颜色在交互中变化bug

### ISSUE THREAD

**Issue by Hppyyung** [apache/echarts#9681]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details
旭日图设置label minAngle属性，点击不含label item， zoom in, 再点击中心 zoom out，再点击不含label item，则整个旭日图 label 颜色发生变化

### Expected Behavior

旭日图label颜色不发生变化

### Current Behavior

旭日图label 颜色 发生变化

### Online Example

http://gallery.echartsjs.com/editor.html?c=xnaTN9oHIF&v=1

## Environment

- ECharts version；ECharts 版本: {4.2.0}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by pissang** [comment]
Can't reproduce the bug
