### ISSUE TITLE
echarts结合百度地图绘制500+个点（effectScatter），当拖动地图时非常卡顿，请问有什么方法可以解决，或者提供一个思路，不胜感激

### ISSUE THREAD

**Issue by justJokee** [apache/echarts#9685]
echarts结合百度地图绘制500+个点（effectScatter），当拖动地图时非常卡顿，请问有什么方法可以解决，或者提供一个思路，不胜感激

**Comment by xujunpro2** [comment]
effectScatter因为动画效果的缘故，是很耗费性能的，建议不要全部加载，可以使用图层类似的设计，通过缩放地图加载/隐藏某些scatter，或者采用聚合标记的思路，先使用普通scatter，然后放大地图到合适的zoom的时候，再切换为effectScatter。话说你500+个scatter如果全在屏幕上，估计也密密麻麻了。

**Comment by justJokee** [comment]
> effectScatter因为动画效果的缘故，是很耗费性能的，建议不要全部加载，可以使用图层类似的设计，通过缩放地图加载/隐藏某些scatter，或者采用聚合标记的思路，先使用普通scatter，然后放大地图到合适的zoom的时候，再切换为effectScatter。话说你500+个scatter如果全在屏幕上，估计也密密麻麻了。

thanks，不过这和动效没关系，最近考虑离太近的点只显示一个，先这样优化下吧

**Comment by Nyya** [comment]
可以试试 zlevel 设置 为 1，具体见 http://echarts.baidu.com/option.html#title.zlevel
{    type: 'effectScatter', zlevel: 1    }

**Comment by mizi-lin** [comment]
估计 只能从源头改期，先禁掉动画吧··
