### ISSUE TITLE
When left is set on legend, right stops working

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#9686]
Hello,

I am trying to adjust this example https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-stack and I want to set the following properties for the legend:

```
    legend: {
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他'],
        left: 0,
        right: 50,
    },
```

But it looks like as soon as I set left to something, then changing the value of right does nothing.

What I would like is the legend to start from the beginning, and not go past a specific point, because it overlaps the toolbox.

**Comment by pissang** [comment]
You can try width instead of right

**Comment by xvaara** [comment]
This is a bug. There should be a way to set this, and the documentation gives the idea that it should work both ways.
let's say I have tow Y-axis and I want to aling legends inside them, so I would give something like:
{ left: 50, right: 50 }
with width I really can't do that, without doing dom trickery to get the width of the chart and so on.
