### ISSUE TITLE
Missing symbol border in legend for scatter series

### ISSUE THREAD

**Issue by kanchev** [apache/echarts#9689]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Symbol's border is not rendered at all in the legend for scatter series with itemStyle set with color, borderColor and borderWidth properties.

### Expected Behavior

The borderColor and borderWidth properties are picked up from series itemStyle and rendered correctly in the legend.

### Current Behavior

The border is rendered property in the grid but it's missing in the legend. Only the color property is used to fill the symbol.

### Online Example

option = {
    xAxis: {},
    yAxis: {},
        legend: {
        show: true,
        orient: 'vertical'
    },
    series: [{
        symbolSize: 20,
        data: [
            [1, 1]
        ],
        type: 'scatter',
        name: 'missing border',
        itemStyle: {
            color: 'green',
            borderColor: 'red',
            borderWidth: 5,
        }
    }]
};

Paste this here: https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-simple

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}
I'm using Google Chrome, not sure if this happens with other browsers.

**Comment by pissang** [comment]
Currently only display `color` and `symbol` of series

**Comment by kanchev** [comment]
Are you planning to support also borderColor for the legend?

Btw from technical point of view I assumed that the same logic is used to render symbols for the series and for the legend.

**Comment by pissang** [comment]
Yes it's a very common request. We will think about adding more visual properties in the legend. Thanks @kanchev

**Comment by huanggm** [comment]
Series symbol is none, but legend symbol still rendered.

**Comment by Ovilia** [comment]
Fixed in #14497, released in 5.1.0.
