### ISSUE TITLE
Echarts-gl 矢量场图怎么更换地图（底图）比如更换成openlayers

### ISSUE THREAD

**Issue by lsai2270** [apache/echarts#9714]
echarts-gl矢量场图事例下载之后发现用的是百度地图的api接口，然后自己不想用百度地图的api,想换成openlayers的地图，尝试了好几个办法都没有成功，官方文档上也没有说明怎么更换echarts-gl的地图，请各位大牛看看有没有什么解决办法

**Comment by pissang** [comment]
You can try echarts openlayer extension. For example https://github.com/sakitam-fdd/ol3Echarts

**Comment by lsai2270** [comment]
> You can try echarts openlayer extension. For example https://github.com/sakitam-fdd/ol3Echarts

thanks  for you help ,i will try

**Comment by lsai2270** [comment]
现在已经可以渲染出来了，可是ol3Echarts.js里面的remove()方法不可以执行，有没有什么解决办法，是需要从openlayer map中来删除吗？？

**Comment by lsai2270** [comment]
> > You can try echarts openlayer extension. For example https://github.com/sakitam-fdd/ol3Echarts
> 
> thanks for you help ,i will try

现在已经可以渲染出来了，可是ol3Echarts.js里面的remove()方法不可以执行，有没有什么解决办法，是需要从openlayer map中来删除吗？？

**Comment by pissang** [comment]
@lsai2270 You can open an issue about the `remove()` in https://github.com/sakitam-fdd/ol3Echarts
