### ISSUE TITLE
data zoom (in toolbox) stops working after changing axis type

### ISSUE THREAD

**Issue by gnijuohz** [apache/echarts#9736]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

Zooming stops working after changing axis type from linear to log scale (although it doesn't seem to matter from which type to which type)

### Expected Behavior

The zooming feature still works

### Current Behavior

The zooming feature doesn't work. Here is the error:

> Cannot read property 'getMinMaxSpan' of undefined

### Online Example

See a demo here: https://codesandbox.io/s/4x0xx62no9

The zoom feature works at first, but after changing it to log scale, it no longer works. If you change it back to linear scale, the zoom feature doesn't work there as well.

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
4.2.0-rc.2

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by asionius** [comment]
@gnijuohz 请问这个问题有进展了吗

**Comment by asionius** [comment]
您好，我已收到您的邮件~上线后我会尽快阅读~。
