### ISSUE TITLE
是否可以在legend中添加图表data

### ISSUE THREAD

**Issue by Dzxwind** [apache/echarts#9747]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [x] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

在legend对象下的formatter方法中建议将参数params中加入图表的data。使得legend能够调用到图表数据。

### Expected Behavior

在legend对象下的formatter方法中建议将参数params中加入图表的data。使得legend能够调用到图表数据。

### Current Behavior

params中只有name

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}  最新版

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by cuijian-dexter** [comment]
https://echarts.baidu.com/option.html#legend.data

**Comment by deqingli** [comment]
@Dzxwind  what kind of data do you want? the raw series.data or the data of the current chart,  these two are different within ECharts. While inside ECharts the raw series.data will be transformed into the date of the current chart after some processing.

**Comment by Dzxwind** [comment]
@deqingli 在实际使用Echarts过程中，往往需要在图例中加入series.data下的数据。当前echarts版本中legend.formatter作为回调函数使用时，里面的params只有name。因此我需要的是能够在这个params中获取到series.data中的数据。
举一个简单的例子，也是我最近碰到的需求，需要显示这样的图例

- 北京 10个(20%)
- 上海 15个(30%)
- 广州 15个 (30%)

我目前的做法只能是获取到params参数中的name，然后与原数组做匹配循环以实现需求。

**Comment by Ovilia** [comment]
I don't think showing detailed data like value and percentage is the best practice for using legend.
So I guess for your specific requirement, you have to use some hack ways.
@100pah What do you think?
