### ISSUE TITLE
force graph 多边支持了吗，现在只支持单边

### ISSUE THREAD

**Issue by yu-cover** [apache/echarts#9753]
求方案

**Comment by deqingli** [comment]
@yu-cover  sorry, I'm confused about what you want. Is [this](https://www.echartsjs.com/examples/editor.html?c=graph-simple) what you want?

**Comment by thWinterSun** [comment]
由A节点指向B节点的多条边？如何实现？

**Comment by yu-cover** [comment]
> 由A节点指向B节点的多条边？如何实现？

A节点指向B节点，B节点指向A节点，这种情况只有一条边的两个箭头，想用双向边来实现

**Comment by Git-David** [comment]
同问， 支持A节点发出两条不同的边指向B节点吗？

**Comment by topvis** [comment]
这里有一个临时解决方案，参见https://github.com/apache/incubator-echarts/issues/6811

**Comment by deqingli** [comment]
#11260
