### ISSUE TITLE
ECharts browser resize

### ISSUE THREAD

**Issue by MINDoSOFT** [apache/echarts#9770]
When you press Ctrl+'+' to zoom-in or zoom-out the browser window, echarts does not redraw causing aliasing issues (blurry text and shapes). After refresh the echart redraws OK. I am running the demo from [here](https://ecomfe.github.io/echarts-examples/public/editor.html?c=mix-line-bar)

Before refresh:
![screenshot from 2019-01-16 15-35-06](https://user-images.githubusercontent.com/890368/51252652-125e9f00-19a5-11e9-8180-cdc18bdcdc04.png)

After refresh:
![screenshot from 2019-01-16 15-35-14](https://user-images.githubusercontent.com/890368/51252658-168abc80-19a5-11e9-8296-bc2b68ba07ea.png)

**Comment by MINDoSOFT** [comment]
Hi there @100pah @pissang  ,

this issue still occurs with the [latest echart examples](https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar) and version 4.7.0.
Can you take a look at this.

Thank you for your time and effort.

Best regards,
Sergios.

**Comment by parumsancto** [comment]
Use svg render
