### ISSUE TITLE
设置`dimensions`之后，`dataZoom`中原来总动生成的缩略图消失

### ISSUE THREAD

**Issue by FireBushtree** [apache/echarts#9773]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ x ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

设置`dimensions`之后，`dataZoom`中原来总动生成的缩略图消失。

### Expected Behavior

`dataZoom`中的缩略图不消失，K线图中`dataZoom`缩略图原为`open`的值，期望该缩略图的展示可配置为`close`的值。

### Current Behavior

K线图中`dataZoom`的缩略图展示不可配置

### Online Example

```
option = {
    dataset: {
        source: [
            ['2013/1/24', 2320.26,2320.26,2287.3,2362.94],
            ['2013/1/25', 2300,2291.3,2288.26,2308.38],
            ['2013/1/28', 2295.35,2346.5,2295.35,2346.92],
            ['2013/1/29', 2347.22,2358.98,2337.35,2363.8],
            ['2013/1/30', 2360.75,2382.48,2347.89,2383.76],
            ['2013/1/31', 2383.43,2385.42,2371.23,2391.82],
            ['2013/2/1', 2377.41,2419.02,2369.57,2421.15],
            ['2013/2/4', 2425.92,2428.15,2417.58,2440.38],
            ['2013/2/5', 2411,2433.13,2403.3,2437.42],
            ['2013/2/6', 2432.68,2434.48,2427.7,2441.73],
            ['2013/2/7', 2430.69,2418.53,2394.22,2433.89],
            ['2013/2/8', 2416.62,2432.4,2414.4,2443.03],
        ]
    },
    tooltip: {},
    xAxis: {type: 'category'},
    yAxis: {
        scale: true
    },
    dataZoom: [{type: 'slider'}],
    series: [{
        type: 'candlestick',
        encode: {
            x: [0],
            y: [1, 2, 3, 4],
            tooltip: [1, 2, 3, 4],
        },
        dimensions: [null, '开', '收', '低', '高']
    }]
};
```

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
4.2.0-rc.2
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
@FireBushtree  What does the thumbnail mean? please provide an image/demo to explain this.

**Comment by FireBushtree** [comment]
if do not set the `dimensions`, the thumbnail will show like this:
![image](https://user-images.githubusercontent.com/32190667/51297877-439aa600-1a5d-11e9-9c41-5c8975e84045.png)
after setting the `dimensions`, the thumbnail:
![image](https://user-images.githubusercontent.com/32190667/51297929-70e75400-1a5d-11e9-987d-2828ceca9016.png)
