### ISSUE TITLE
How can lineStyle.type support below types?

### ISSUE THREAD

**Issue by wmjcom** [apache/echarts#9781]
From documentation, it describes that “ lineStyle.type only choose from below three types".
'solid'
'dashed'
'dotted'

If I need more types like below image, how can they be supported?

![20190117175223](https://user-images.githubusercontent.com/45786005/51310044-b8cba280-1a80-11e9-85f5-d68981977602.png)

**Comment by 100pah** [comment]
It is probably beyond the meaning of `lineStyle`.
But, what scenario do you use lineStyle in?

[custom series](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Custom%20Series) might help.

**Comment by plainheart** [comment]
The dashed line has been supported since 5.0.0
