### ISSUE TITLE
Remove-Refresh data without setOption()

### ISSUE THREAD

**Issue by iSanchezDev** [apache/echarts#9782]
## General Questions

- [x] ECharts version；4.1.0
- [x] ECharts-GL version；1.1.1

## Issue Details

I'm working on a **cyber threat world map**. 

What I want to do looks imposible with the API or eCharts properties. 

I have to remove each line after a few seconds of doing its respective **appendData()** method.

I am representing a line with effect from region source to its destination with a scattered point.

![threatmap_isanchez](https://user-images.githubusercontent.com/25980900/51314441-fbc15200-1a4f-11e9-84dd-515d658767c6.gif)

Each line-point attack being added like:

```javascript
// Config lines and scatters

newSeriesEvent() {
   const serieLine = {
      name: event.event_type,
      type: 'lines',
      zlevel: 1,
      coordinateSystem: 'geo',
      large: true,
      effect: {
        show: true,
        period: 0.5,
        symbol: 'pin',
        symbolSize:  11,
        trailLength: 0,
        loop: false
      },
      lineStyle: {
        normal: {
          width: 1.1,
          opacity: 0.8
        }
      },
      showSymbol: false,
      animationEasing: 'quadraticIn',
      animationDuration: 600,
      data: []
    }

    const serieScattered = {
      name: event.event_type,
      type: 'effectScatter',
      coordinateSystem: 'geo',
      showEffectOn: 'render',
      zlevel: 2,
      label: {
        normal: {
          formatter: '{b}',
          position: 'right',
          show: false
        },
        emphasis: {
          show: false
        }
      },
      hoverAnimation: true,
      rippleEffect: {
        brushType: 'stroke'
      },
      symbolSize: 8,
      data: []
    }

    this._series.push(serieLine, serieScattered);
}

// New event

appendData() {
      const line = {
        seriesIndex: position,
        data: [{
          coords: [srcPosition, dstPosition],
          lineStyle: {
            curveness: Math.random() * (0.4 + 0.4) - 0.4
          },
        }],
      };

      const scatter = {
        seriesIndex: position++,
        data: [{
          name: event.event_type,
          value: dstPosition,
        }]
      }

      this._chart.appendData(line);
      this._chart.appendData(scatter);
}
```
This release I made, refresh the whole map with **this.chart.setOption({series: this.series})** after 100 events as max arrived.

Are there other ways to remove each line without refreshing the whole content??  

Any suggestions?

### Expected Behavior

For instance, this map shows how the attack should be working on my case: 

![fortinet_threatmap](https://user-images.githubusercontent.com/25980900/51316849-2910fe80-1a56-11e9-805e-0b4bc535450a.gif)

### New feature 

It'll be nice to have a **removeData()** method like **appendData()** or a **{duration: 2s}** property for each data added with  **appendData()**. 

That can be VERY useful for realtime applications in general. 

This map is receiving in realtime more than hundreds events for second!!

I'll do appreciate your help, thank you so much :beers:

**Comment by kmmertes** [comment]
I too desperately need this feature.  Another way to do this (at least for me) is to have a feature that limits the number of data points in a series.  But chartInstance.removeData({series_index, element_index_start, element_index_end}) would be nice.

**Comment by eapatel** [comment]
I really need removeData feature as well. Any update?

**Comment by eapatel** [comment]
@kmmertes how did you limit number of data points in a series? Is it from API or UI?
