### ISSUE TITLE
echart tree label support click event

### ISSUE THREAD

**Issue by pespidog** [apache/echarts#9815]
-遇到一个需求就是希望在点击树的节点的时候，会弹出该节点的信息，但是这个时候那个节点的子节点又会被伸缩，所以希望能够在label上添加点击事件，这样可以分离这两个操作，但是一直找不到地方实现

![mi6re0 ctn4 4 s 6316y5](https://user-images.githubusercontent.com/27176451/51515698-a9b56d80-1e4f-11e9-9bdb-f0ccce0fef55.png)

**Comment by 100pah** [comment]
@deqingli Probably we should find a way to support collapse/expand and plain click both.

**Comment by infjer** [comment]
同样的需求+1
追问一下，目前有没有阻止折叠的方法？

**Comment by ringgoyao** [comment]
![1](https://user-images.githubusercontent.com/5906943/56945421-bf76b500-6b59-11e9-932e-33965381b340.png)
同求label事件或者相关属性，做到这一步后，发现没法点击字的时候心冰凉啊

**Comment by nanhao1986** [comment]
持续关注这个问题，目前采用了替代方案：
`document.oncontextmenu = function () { return false; };`
先屏蔽系统的右键操作，然后通过右键点击实现弹窗：
`myChart.on('contextmenu',  function (params) {
      //do something
    });`

**Comment by deqingli** [comment]
#9409

**Comment by deqingli** [comment]
#11416

**Comment by deqingli** [comment]
#8004

**Comment by deqingli** [comment]
> ![1](https://user-images.githubusercontent.com/5906943/56945421-bf76b500-6b59-11e9-932e-33965381b340.png)
> 同求label事件或者相关属性，做到这一步后，发现没法点击字的时候心冰凉啊

您好，请问你也是想点击字的时候显示节点的详细信息么

**Comment by deqingli** [comment]
After research, I think this kind of diagram is the most suitable.
![image](https://user-images.githubusercontent.com/13548221/71509638-ff4b9300-28c6-11ea-8b80-bd3262335bb7.png)
If using this, we should compute label length and add it to the layout computation.

**Comment by huanledeniuduzi** [comment]
> ![1](https://user-images.githubusercontent.com/5906943/56945421-bf76b500-6b59-11e9-932e-33965381b340.png)
> 同求label事件或者相关属性，做到这一步后，发现没法点击字的时候心冰凉啊

请问您实现点击文字的功能了吗？

**Comment by ycshill** [comment]
同问啊，急求

**Comment by ycshill** [comment]
> on('contextmenu', function (params) { //do something });

不能实现啊

**Comment by noru** [comment]
+1. It is so far the most wanted feature of tree series. Wonder why it wasn't included in the first place.

**Comment by noru** [comment]
> 持续关注这个问题，目前采用了替代方案：
> `document.oncontextmenu = function () { return false; };`
> 先屏蔽系统的右键操作，然后通过右键点击实现弹窗：
> `myChart.on('contextmenu', function (params) { //do something });`

Not working on 4.8.0

**Comment by RedZhu1900** [comment]
同问，什么时候可以支持label点击事件？

**Comment by Tanelmer** [comment]
同问+1

**Comment by rokon0614** [comment]
我这边是这么解决的，在外层套一个div，然后加上点击时间，然后根据echart里面有一个this.chart._chartsViews[0]._data._itemLayouts属性有每一个图标(就是展开收缩的那个图标)的位置，然后根据偏移量计算一下是在哪个图标的范围内即可。
希望能帮到大家，也希望官方尽快出lable的点击事件。

**Comment by lillian56** [comment]
5.0的图标和标签都能触发点击事件，但是，怎样让其中一个事件屏蔽掉原本的展开折叠子节点的功能呢？

**Comment by caijingwen-vincent** [comment]
现在点击树标签一定会收缩子树。似乎没有办法选择是否展开折叠子节点

**Comment by whateveryoudo** [comment]
支持 html 插入 就好了， 目前定制只能 rich,  加事件 也不好加， echart  onclick 回来的参数一点用都没有，根本没法判断哪里触发的
