### ISSUE TITLE
echart不能设置多个Y轴吗？

### ISSUE THREAD

**Issue by ghost** [apache/echarts#983]
我要做个图，然后图里包含5种数据，3条线，2个柱状图，然后我在yAxis里设置了5个对象属性，只能显示两个， 如何显示多个呢？

**Comment by jeeseDear** [comment]
> 我的做法也许你可以借鉴一下，竖着画多个图，隐藏前几个图的x轴，最后让这几个图联动起来。可以达到一个x轴多个y轴的效果
大佬这个怎么做到几个一起联动

**Comment by jeeseDear** [comment]
> 我的做法也许你可以借鉴一下，竖着画多个图，隐藏前几个图的x轴，最后让这几个图联动起来。可以达到一个x轴多个y轴的效果。

怎么做到一起联动啊 大佬
