### ISSUE TITLE
echarts  后期会不会发布 立体柱形图 3D Column Chart

### ISSUE THREAD

**Issue by changingshow** [apache/echarts#9832]
![test](https://user-images.githubusercontent.com/7709440/51599528-bfec2800-1f3a-11e9-8b49-f778434442bd.png)
类似于上图这种，立方体柱形图，或者圆柱体柱形图的展示样式？

**Comment by pissang** [comment]
https://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20ECharts%20GL%20%E5%AE%9E%E7%8E%B0%E5%9F%BA%E7%A1%80%E7%9A%84%E4%B8%89%E7%BB%B4%E5%8F%AF%E8%A7%86%E5%8C%96

**Comment by changingshow** [comment]
> https://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20ECharts%20GL%20%E5%AE%9E%E7%8E%B0%E5%9F%BA%E7%A1%80%E7%9A%84%E4%B8%89%E7%BB%B4%E5%8F%AF%E8%A7%86%E5%8C%96

这个是基于xyz三个坐标轴的立体图标，我的意思是在xy轴这种平面图标上，使用立体的柱形图，只是柱形图看起来是立方体或者圆柱体。

**Comment by pissang** [comment]
看文章最后
