### ISSUE TITLE
effectScatter的涟漪效果在火狐下消失了

### ISSUE THREAD

**Issue by yaowei9363** [apache/echarts#9846]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

effectScatter涟漪效果在火狐下没有 ,在谷歌是好的

我自查了下原因,是因为itemStyle的渐变问题主要代码如下:
```javascript
color:{
                          type: "radial",
                          x: 0.5,
                          y: 0.5,
                          r: 1,
                          colorStops: [
                            {
                              offset: 0,
                              color: "rgba(0,0,0,0)" 
                            },
                            {
                              offset: 0.6,
                              color: "rgba(0,0,0,0)" 
                            },
                            {
                              offset: 1,
                              color: "#f1fbff"
                            }
                          ],
                          globalCoord: false
                        }
```
**如果是写两个渐变色l两个色是正常的,三个色的话在火狐就没有涟漪效果了**

### Expected Behavior

火狐下两个以上渐变色涟漪效果正常显示

### Current Behavior

火狐效果如下:
![image](https://user-images.githubusercontent.com/23254093/51811813-c509f800-22e9-11e9-807b-445aad9f58d0.png)
谷歌效果如下:
![image](https://user-images.githubusercontent.com/23254093/51811842-ec60c500-22e9-11e9-98d5-011b64c71222.png)

### Online Example

任何一个effectScatter demo 把颜色改为如下渐变即可复现

```javascript
color:{
                          type: "radial",
                          x: 0.5,
                          y: 0.5,
                          r: 1,
                          colorStops: [
                            {
                              offset: 0,
                              color: "rgba(0,0,0,0)" 
                            },
                            {
                              offset: 0.6,
                              color: "rgba(0,0,0,0)" 
                            },
                            {
                              offset: 1,
                              color: "#f1fbff"
                            }
                          ],
                          globalCoord: false
                        }
```

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}
 "echarts": "4.1.0"
- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}
"firefox":"64.0.2"

**Comment by pissang** [comment]
Please post your example code on the gallery https://gallery.echartsjs.com/explore.html
