### ISSUE TITLE
Can I create custom formatter for the chart

### ISSUE THREAD

**Issue by LaxdeepBomble** [apache/echarts#9853]
**Echarts version**: 4.2.1-rc1
**Browser version** : Chrome Version 71.0.3578.98
**OS version**: Ubuntu 18.04

I have created a series chart and I have some use cases in which I want to do some task while rendering every data. Currently, I am referring the `labelFormatter` which gets called for every datapoint for formatting of the labels.
From this reference, can I create my own "custom formatter" which will gets called on every datapoint rendering.

**Comment by Ovilia** [comment]
It seems an event like `'data-rendered'` should be provided, and I think this is reasonable. But I doubt if there would be a performance problem for large data.
@100pah What do you think of?

**Comment by tmtron** [comment]
Can you please explain the use-case for this request?
I am asking, because I have performance issues with custom series (see [Stackoverflow](https://stackoverflow.com/questions/55771899/performance-hints-for-custom-series)) and I am looking for alternatives.
