### ISSUE TITLE
Geo map displays only one itemStyle areaColor when multiple series data have different itemStyle areaColor

### ISSUE THREAD

**Issue by stephan227** [apache/echarts#9857]
Geo map will only display 1 series.data itemStyle.areaColor at a time.   I have the visualMap set to false. 

I am currently using echarts@4.2.1-rc.1

The expected map result:
![usa population estimates 2012](https://user-images.githubusercontent.com/13683178/51876627-9b7bbb80-233f-11e9-9f34-18371aacd112.png)

The actual map  result:
![usa population estimates 2012 1](https://user-images.githubusercontent.com/13683178/51876609-8dc63600-233f-11e9-9180-a1d07617b697.png)

Code:
```
myChart.showLoading();

$.get('data/asset/geo/USA.json', function (usaJson) {
    myChart.hideLoading();

    echarts.registerMap('USA', usaJson, {
        Alaska: {              // 把阿拉斯加移到美国主大陆左下方
            left: -131,
            top: 25,
            width: 15
        },
        Hawaii: {
            left: -110,        // 夏威夷
            top: 28,
            width: 5
        },
        'Puerto Rico': {       // 波多黎各
            left: -76,
            top: 26,
            width: 2
        }
    });
    option = {
        title: {
            text: 'USA Population Estimates (2012)',
            subtext: 'Data from www.census.gov',
            sublink: 'http://www.census.gov/popest/data/datasets.html',
            left: 'right'
        },
        tooltip: {
            trigger: 'item',
            showDelay: 0,
            transitionDuration: 0.2,
            formatter: function (params) {
                var value = (params.value + '').split('.');
                value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,');
                return params.seriesName + '<br/>' + params.name + ': ' + value;
            }
        },
        legend: {
            
        },
        visualMap: false,
        toolbox: {
            show: true,
            //orient: 'vertical',
            left: 'left',
            top: 'top',
            feature: {
                dataView: {readOnly: false},
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                name: 'red',
                type: 'map',
                roam: true,
                map: 'USA',
                visualMap: false,
                itemStyle:{
                    emphasis:{label:{show:true}}
                },
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },
                data:[
                    {name: 'Alabama', itemStyle: { color: 'red'}},
                ]
            },
              {
                name: 'blue',
                type: 'map',
                roam: true,
                map: 'USA',
                visualMap: false,
                itemStyle:{
                    emphasis:{label:{show:true}}
                },
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },
                data:[
                    {name: 'Alaska', itemStyle: { color: 'blue'}},
                ]
            },
                          {
                name: 'green',
                visualMap: false,
                type: 'map',
                roam: true,
                map: 'USA',
                itemStyle:{
                    emphasis:{label:{show:true}}
                },
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },
                data:[
                    {name: 'Florida', itemStyle: { color: 'green'}}
                ]
            }
        ]
    };

    myChart.setOption(option);
});
```

**Comment by stephanbochet** [comment]
I was able to perform the expected chart using the visualMap piecewise type. 

`myChart.showLoading();

$.get('data/asset/geo/USA.json', function (usaJson) {
    myChart.hideLoading();

    echarts.registerMap('USA', usaJson, {
        Alaska: {              // 把阿拉斯加移到美国主大陆左下方
            left: -131,
            top: 25,
            width: 15
        },
        Hawaii: {
            left: -110,        // 夏威夷
            top: 28,
            width: 5
        },
        'Puerto Rico': {       // 波多黎各
            left: -76,
            top: 26,
            width: 2
        }
    });
    option = {
        title: {
            text: 'USA Population Estimates (2012)',
            subtext: 'Data from www.census.gov',
            sublink: 'http://www.census.gov/popest/data/datasets.html',
            left: 'right'
        },
        tooltip: {
            trigger: 'item',
            showDelay: 0,
            transitionDuration: 0.2,
            formatter: function (params) {
                var value = (params.value + '').split('.');
                value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,');
                return params.seriesName + '<br/>' + params.name + ': ' + value;
            }
        },
            visualMap: {
                type: 'piecewise',
                pieces: [
                    {
                        min: 1,
                        max: 1,
                        color: 'red',
                        label: 'red'
                    },
                                        {
                        min: 2,
                        max: 2,
                        color: 'blue',
                        label: 'blue'
                    },
                    {
                        min: 3,
                        max: 3,
                        color: 'green',
                        label: 'green'
                    }
                ]
            
            
            
        },
        toolbox: {
            show: true,
            //orient: 'vertical',
            left: 'left',
            top: 'top',
            feature: {
                dataView: {readOnly: false},
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                
                name: 'USA 333',
                type: 'map',
                roam: true,
                map: 'USA',
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },
                data:[ {name: 'Alaska', value: 1},
                {name: 'Texas', value: 1},
                {name: 'Washington', value: 2},
                {name: 'California', value: 2},

                {name: 'Florida', value: 3},
                {name: 'Puerto Rico', value: 3}
                ]
            }
        ]
    };

    myChart.setOption(option);
});`
