### ISSUE TITLE
Disable calendar heatmap dayLabel's clickable cursor

### ISSUE THREAD

**Issue by ClemMakesApps** [apache/echarts#9858]
![2019-01-28 20 46 46](https://user-images.githubusercontent.com/3363898/51880714-e8f72900-233d-11e9-8588-44cefffc3223.gif)

Is there a way to disable the clickable cursor for the `dayLabel` and `monthLabel`? They don't seem to do anything when clicked. This behavior is found in https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-heatmap

**Comment by pissang** [comment]
It seems heatmap series doesn't support setting `itemStyle.cursor` yet.

**Comment by MahalakshmiSankaran** [comment]
is there any update on this enhancement?

**Comment by calvincramer** [comment]
This would be a nice addition. Something like `xAxis.silent` but `calendar.{day,month,year}Label.silent`
