### ISSUE TITLE
使用百度地图出现白块或者白线

### ISSUE THREAD

**Issue by xinglipeng** [apache/echarts#9865]
人在上海，打开echart官方案例 https://echarts.baidu.com/examples/editor.html?c=map-polygon，出现白块或者白线，晃动地图后会变好。
![image](https://user-images.githubusercontent.com/37685122/51890165-5a82b600-23d6-11e9-9806-62c061763f62.png)
白块多出现在缩放的情况
![image](https://user-images.githubusercontent.com/37685122/51890307-acc3d700-23d6-11e9-8fbe-e9bd9c3e685e.png)
- chrom浏览器提示如下
`
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.baidu.com/error.html with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
`

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by xq5356** [comment]
I have met the same question, is there any solution ?

**Comment by plainheart** [comment]
This issue is related to Baidu Map self, so I'm going to close it. It should occur only when using API 2.0 and the custom style. You could try to use API 3.0, whose map servers are better than the 2.0's.

```js
bmap: {
    center: [116.46, 39.92],
    zoom: 10,
    roam: true,
    // for API 3.0, you will need to use `mapStyleV2` instead of `mapStyle`
    mapStyleV2: {
        // Refer to http://lbsyun.baidu.com/index.php?title=open/custom
        styleJson: []
    }
}
```
