### ISSUE TITLE
No data info on one day period chart.

### ISSUE THREAD

**Issue by Janicek2** [apache/echarts#9873]
## Issue Type

- [x ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

No data info on one day period chart.

### Expected Behavior

![chart](https://user-images.githubusercontent.com/35063987/51982880-7d28d380-2497-11e9-9c84-1529879ce9ba.png)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Could you please provide the option of this?

**Comment by Janicek2** [comment]
{"grid":{"top":80,"right":40,"left":30,"bottom":20,"containLabel":true},"toolbox":{"show":true,"itemGap":10,"itemSize":20,"feature":{"restore":{"title":"Restore"},"dataZoom":{"title":{"zoom":"Zoom tool","back":"Restore zoom"}},"saveAsImage":{"title":"Save as image"},"mySaveAsCSV":{"show":true,"title":"Save as CSV","icon":"path://M0,0h10l4,4v16h-14v-20M10,0v4h4M4,8l6,8m0,-8l-6,8","onclick":{"_custom":{"type":"function","display":"<span>ƒ</span> bound toCSV()"}}},"magicType":{"type":["line","bar"],"title":{"line":"Line chart","bar":"Bar chart"},"option":{"bar":{"animationEasing":"elasticOut","animationDelay":{"_custom":{"type":"function","display":"<span>ƒ</span> animationDelay(?)"}}},"line":{"animationEasing":"linear"}}}}},"legend":{"data":["11 Lincoln Speedtec 505 SP (Rywal Gdańsk)"],"top":40,"type":"scroll"},"tooltip":{"confine":true,"formatter":{"_custom":{"type":"function","display":"<span>ƒ</span> (Array.isArray(params)"}}},"xAxis":{"type":"category","axisLabel":{"showMinLabel":true,"showMaxLabel":true,"formatter":{"_custom":{"type":"function","display":"<span>ƒ</span> ()"}}},"axisLine":{"show":false},"axisTick":{"alignWithLabel":true,"show":true},"splitLine":{"show":false},"data":["2019-02-14 00:00:00"]},"yAxis":{"type":"value","axisLabel":{"formatter":{"_custom":{"type":"function","display":"<span>ƒ</span> (?)"}}},"axisLine":{"show":false},"splitNumber":5,"min":null,"max":180,"interval":60,"minInterval":60},"dataZoom":[{"type":"inside","start":0,"end":100}],"series":[{"name":"11 Lincoln Speedtec 505 SP (Rywal Gdańsk)","type":"bar","connectNulls":true,"data":["171"],"itemStyle":{"color":"#2196f3"}}],"animationDuration":300,"color":[{"50":"#e3f2fd","100":"#bbdefb","200":"#90caf9","300":"#64b5f6","400":"#42a5f5","500":"#2196f3","600":"#1e88e5","700":"#1976d2","800":"#1565c0","900":"#0d47a1","a100":"#82b1ff","a200":"#448aff","a400":"#2979ff","a700":"#2962ff"},{"50":"#e8f5e9","100":"#c8e6c9","200":"#a5d6a7","300":"#81c784","400":"#66bb6a","500":"#4caf50","600":"#43a047","700":"#388e3c","800":"#2e7d32","900":"#1b5e20","a100":"#b9f6ca","a200":"#69f0ae","a400":"#00e676","a700":"#00c853"},{"50":"#fff3e0","100":"#ffe0b2","200":"#ffcc80","300":"#ffb74d","400":"#ffa726","500":"#ff9800","600":"#fb8c00","700":"#f57c00","800":"#ef6c00","900":"#e65100","a100":"#ffd180","a200":"#ffab40","a400":"#ff9100","a700":"#ff6d00"},{"50":"#efebe9","100":"#d7ccc8","200":"#bcaaa4","300":"#a1887f","400":"#8d6e63","500":"#795548","600":"#6d4c41","700":"#5d4037","800":"#4e342e","900":"#3e2723"},{"50":"#e8eaf6","100":"#c5cae9","200":"#9fa8da","300":"#7986cb","400":"#5c6bc0","500":"#3f51b5","600":"#3949ab","700":"#303f9f","800":"#283593","900":"#1a237e","a100":"#8c9eff","a200":"#536dfe","a400":"#3d5afe","a700":"#304ffe"},{"50":"#ffebee","100":"#ffcdd2","200":"#ef9a9a","300":"#e57373","400":"#ef5350","500":"#f44336","600":"#e53935","700":"#d32f2f","800":"#c62828","900":"#b71c1c","a100":"#ff8a80","a200":"#ff5252","a400":"#ff1744","a700":"#d50000"},{"50":"#fffde7","100":"#fff9c4","200":"#fff59d","300":"#fff176","400":"#ffee58","500":"#ffeb3b","600":"#fdd835","700":"#fbc02d","800":"#f9a825","900":"#f57f17","a100":"#ffff8d","a200":"#ffff00","a400":"#ffea00","a700":"#ffd600"}]}
