### ISSUE TITLE
建议series[i]-line.sampling可以同时返回两个值，最大值和最小值

### ISSUE THREAD

**Issue by Ericazhang1990** [apache/echarts#9874]
- [√] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [√ ] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [ √] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [√ ] Required: issue type；（必填）issue 类型
- [√ ] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [ ] Required: ECharts version；ECharts 版本

## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [√] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

sampling属性支持两个像素点内返回最大值和最小值

### Expected Behavior

1 添加类似"max"，“min”的属性，来返回两个像素点内的最大值和最小值；
2 sample自定义可以返回数组，返回多个值，返回1个值则是对一个像素点内的值稀释，返回两个点则是对2个像素点内的值进行稀释。
两种方案希望有一种被使用

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ovilia** [comment]
Could you please provide the usage of these two plans?

**Comment by Ericazhang1990** [comment]
收到回复很高兴
首先，第一种方案希望直接能添加sample的属性值，代表获取单位采集点内的最大值和最小值，当前echarts提供的方案是，像素点内的最大值，最小值和平均值，但都是一个像素点内的数据为单位，是否可以以两个像素点内的数据为单位返回最大值和最小值。
其次，当前sample属性支持自定义函数，但是自定义函数返回值当前只支持返回单个值，用以表示一个像素点内数据显示一个值，是否可以修正为支持返回n个值，同时设置参数n个像素点稀释，例如，设置两个像素点内的数据显示两个点，sample自定义函数返回两个值，同时设置以2个像素点内的数据为单位

**Comment by sywwww** [comment]
你好，请问这个问题解决了吗？

**Comment by DuskMount** [comment]
It is useful to show both max and min value in a frame when ploting audio signal.
If just using "max" or "min" method, the signal will be distorted.

_original signal without sampling_
![Screen Capture_select-area_20201008221422](https://user-images.githubusercontent.com/47274401/95474796-22f44b80-09b8-11eb-97c2-f03efc622dc0.png)

_signal with sampling "max"_
![Screen Capture_select-area_20201008222220](https://user-images.githubusercontent.com/47274401/95474858-31dafe00-09b8-11eb-9a52-ba593c0ef97c.png)

_signal with sampling "min"_
![Screen Capture_select-area_20201008223631](https://user-images.githubusercontent.com/47274401/95474642-ee808f80-09b7-11eb-9871-2188d59b7efb.png)
