### ISSUE TITLE
echart 4.1.0在设置 series[i]-line.label.show 时候 label不会自适应的 部分不展示

### ISSUE THREAD

**Issue by mayunhai** [apache/echarts#9888]
在设置 series[i]-line.label.show 时候 label不会自适应的 部分不展示而会变成全部展示 很拥挤，和4.0.0及之前对比 体验较差
itemStyle: { normal: { color: color, barBorderRadius: 0, label: { show: true, position: 'top', offset: [0, -10], formatter(p) { return p.value > 0 ? p.value : '' } } } },

**Comment by wind108369** [comment]
希望能加上label的重叠检测机制，或者在formatter里面暴露label的位置，使用者可以自行去判断

**Comment by deqingli** [comment]
#11497
