### ISSUE TITLE
Is there an option to increase spacing between leaves in a tree?

### ISSUE THREAD

**Issue by ctcuff** [apache/echarts#9891]
## General Questions
Is it possible to add spacing between the leaves of a tree? I've looked through the docs but is seems like the only spacing options are applied to the labels themselves.

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### Expected Behavior

#

## Current Behavior
The leaves here overlap, is there anyway to change this?
![leaves](https://user-images.githubusercontent.com/7400747/52189800-e5194a00-2808-11e9-9af4-d0982d41fe29.PNG)
Another example:
![leaaves-2](https://user-images.githubusercontent.com/7400747/52189947-c071a200-2809-11e9-8c30-5d1ea436b9ec.PNG)

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by EvilKraft** [comment]
+1

**Comment by leetia316** [comment]
+1

**Comment by marnunez** [comment]
Looking for the same.

**Comment by citrusjunoss** [comment]
Looking for the same.
