### ISSUE TITLE
散点图区域选择部分点不能被选中(只能选中400个点)

### ISSUE THREAD

**Issue by leoliu1984** [apache/echarts#9893]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### 简单描述问题：
散点图区域选择部分点不能被选中, 包括矩形选择，Polygon选择，X轴选择，Y轴选择

### 预期效果：
![image](https://user-images.githubusercontent.com/47359584/52289245-4ccbb400-2933-11e9-9749-a0362af04953.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/47359584/52289256-5228fe80-2933-11e9-8a7c-fc3a55fb9694.png)

无论怎么选择，只能选中361个点。这个数字是通过brushselected回调函数中的params中的dataIndex数组中得到。
Total : 3143
Selected : 361

当把数据从3143降到3000时，还是同样的效果，只能选中361。
当把数据从3000降到2999时，选中的数量变为2591。

数量3143的时候的debug截图：ItemLayout数组为 400
![image](https://user-images.githubusercontent.com/47359584/52300991-ebb1d980-294e-11e9-99b9-a9b9448e8da4.png)

数量2999的时候的debug截图：ItemLayout数组为 2999
![image](https://user-images.githubusercontent.com/47359584/52301028-06844e00-294f-11e9-96df-252d21751407.png)

请问有什么建议吗？

在该例子3143组数据中，横坐标的数值没有空值，纵坐标的数值有425个为null.

## Environment

- ECharts version；ECharts 版本: 4.2.1

**Comment by leoliu1984** [comment]
应该是和 [https://github.com/apache/incubator-echarts/issues/9605](url) 同样的问题。

**Comment by Ende93** [comment]
In [the exampe of 4.2.1](https://gallery.echartsjs.com/editor.html?c=xO7v7zJU8P&v=1), all 600 points can be selected

**Comment by leomeger** [comment]
Please increase your data to 3000, and test it once again.

**Comment by leoliu1984** [comment]
Hi, @100pah 请问这个bug有修复计划吗？

**Comment by leoliu1984** [comment]
Hi , @100pah @Ovilia  通过看源码找到问题所在了，在4.2.1的echarts.js中的第19915，19916行，应该是为了效率考量，所以当数据量超过3000的时候分批成400一批去处理，但是程序有bug只处理了第一次。
我暂时将3000改为5000，我这边的问题可以暂时解决，请尽快修正这个bug。

**Comment by sshallow** [comment]
快 2024 年了，居然还存在这个问题，把我坑坏了，起码给个开关啊，

**Comment by sshallow** [comment]
> Hi , @100pah @Ovilia 通过看源码找到问题所在了，在4.2.1的echarts.js中的第19915，19916行，应该是为了效率考量，所以当数据量超过3000的时候分批成400一批去处理，但是程序有bug只处理了第一次。 我暂时将3000改为5000，我这边的问题可以暂时解决，请尽快修正这个bug。

老哥，这个代码在哪里该呀，有关键字吗（我使用的  "name": "echarts",  "version": "5.4.3",）

**Comment by leomeger** [comment]
> > Hi , @100pah @Ovilia 通过看源码找到问题所在了，在4.2.1的echarts.js中的第19915，19916行，应该是为了效率考量，所以当数据量超过3000的时候分批成400一批去处理，但是程序有bug只处理了第一次。 我暂时将3000改为5000，我这边的问题可以暂时解决，请尽快修正这个bug。
> 
> 老哥，这个代码在哪里该呀，有关键字吗（我使用的 "name": "echarts", "version": "5.4.3",）

你可以在echart的js搜下面的关键字，这里的3000需要改成你需要的更大的数字，另外我用的是4.2.1版本，不知道你用的版本是否可以适用.
progressiveThreshold: 3000,
progressive: 400,

**Comment by sshallow** [comment]
> > > Hi , @100pah @Ovilia 通过看源码找到问题所在了，在4.2.1的echarts.js中的第19915，19916行，应该是为了效率考量，所以当数据量超过3000的时候分批成400一批去处理，但是程序有bug只处理了第一次。 我暂时将3000改为5000，我这边的问题可以暂时解决，请尽快修正这个bug。
> > 
> > 
> > 老哥，这个代码在哪里该呀，有关键字吗（我使用的 "name": "echarts", "version": "5.4.3",）
> 
> 你可以在echart的js搜下面的关键字，这里的3000需要改成你需要的更大的数字，另外我用的是4.2.1版本，不知道你用的版本是否可以适用. progressiveThreshold: 3000, progressive: 400,

已找到相关配置，option.series中设置
```
 // progressiveThreshold: 6000,//设置渲染进度阈值，渲染的图形数量超过这个阈值，会放弃一些细节的绘制，以优化性能。
 progressive: 5000, //设置渲染每一帧的图形数量，如果数据量巨大，这个值可以小一点，否则会卡顿
```
