### ISSUE TITLE
请问是否支持一条折线图分几段不同颜色显示

### ISSUE THREAD

**Issue by xiaohulu** [apache/echarts#990]
本想通过多个serias实现，但是画出来的线是断开的，还需要补充点。
请问是否支持只画一条曲线，但是分几段按不同颜色显示？

**Comment by flyingxu** [comment]
同一维度上的的数据,可能对应一个范围，有些合理的范围，比如pm2.5 = 15 优，是绿色；而有些范围不合理，比如pm2.5 = 280 污染，是黄色。我觉得这种需求还是挺多的。

**Comment by 100pah** [comment]
现在支持了。参见：<http://echarts.baidu.com/demo.html#line-aqi>
