### ISSUE TITLE
地图渲染在chrome和firefox上填充颜色表现不一致

### ISSUE THREAD

**Issue by One-boy** [apache/echarts#9904]
## Issue Type

- [x] I have a bug to report；我想要报 bug

## Issue Details

地图渲染在chrome和firefox上表现不一致。
默认地图是填充了颜色，但是在chrome上没有正确填充，在firefox上正确填充。

Map rendering is inconsistent in chrome and firefox.
The default map is filled with color, but not correctly in chrome and not correctly in firefox.
### Expected Behavior

期望表现一致。
在chrome上也能正确填充颜色。

Consistent expected performance.
You can also fill in colors correctly on chrome.
### Online Example

[在线demo](http://129.204.80.72/ec-test/)
[表现不一致截图示例](http://129.204.80.72/ec-test/img.png)
![表现不一致截图示例](http://129.204.80.72/ec-test/img.png)

```

```

## Environment

- ECharts version；ECharts 版本:4.0.1

- Chrome:71,firefox:64

## Code（echarts配置代码）
```js
 {
    title: {
      text: '地图标题',
      textStyle: {},
      x: 'left', // 放在x轴中部
    },
    //
    tooltip: {
      show: false,
    },
    // 地理坐标系组件配置
    geo: {
      show: true,
      map: 'test',
      roam: true, // 开启鼠标平移漫游
      layoutCenter: ['50%', '50%'], // 地图的中心
      layoutSize: '80%', // 地图占容器的百分比
      itemStyle: {
        normal: {
          borderColor: 'rgba(67,115,255,1)',
          areaColor: 'red', // 地图区域颜色
        },
        emphasis: {
          borderColor: 'blue',
          areaColor: 'green', // 高亮时地图区域颜色
        },
      },
    },
    visualMap: [],
    series: [
      {
        name: '',
        type: 'map',
        geoIndex: 0, // 使用第一个geo
        data: [],
      },
    ],
  }
```

**Comment by Ovilia** [comment]
Using SVG rendering, the polygon is rendered as:
```js
<path d="M 120.1178 30.3195 L 120.116 30.3187 L 120.1163 30.3205 L 120.1173 30.3205 L 120.1178 30.3195 Z" 
fill="red" fill-opacity="1" stroke="rgba(67,115,255,1)" stroke-width="0.00000321353119024121" paint-order="fill" stroke-opacity="1" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" 
transform="matrix(134746.6875,0,0,-179662.265625,-16184987,5447482)" clip-path="none"></path>
```

Not sure if transform is related here. But it seems odd that Chrome renders fill to be transparent when there is `fill="red"`.
Further inspectation required.

**Comment by aiyuwanhua** [comment]
i met the same bug yestoday. any news about it?

**Comment by aiyuwanhua** [comment]
[自定义geojson的多边形，部分简单多边形渲染不出来 #4017](https://github.com/apache/incubator-echarts/issues/4017)

this may help
