### ISSUE TITLE
连线地图 设置emphasis.label.position='middle'不起作用，还是用到默认的end

### ISSUE THREAD

**Issue by 767994269** [apache/echarts#9907]
"emphasis":{
	 "label":{
	       "show":true,
	       'position':'middle',
	       "color":'#fff'
	 }
}

**Comment by deqingli** [comment]
please provide the whole `option` or the demo in [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), thanks

**Comment by 767994269** [comment]
> please provide the whole `option` or the demo in [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all), thanks

https://gallery.echartsjs.com/editor.html?c=x3e2vqklYr&v=1

**Comment by 767994269** [comment]
@deqingli 这是链接，https://gallery.echartsjs.com/editor.html?c=x3e2vqklYr&v=1，麻烦帮忙看一下，困扰了好长时间了。
