### ISSUE TITLE
this force.edgeLength: [10, 100] attribute  does not work when  node count beyond 27 

### ISSUE THREAD

**Issue by zhaoYan1006** [apache/echarts#9915]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by deqingli** [comment]
please provide a more detailed message, such as the ECharts `option` and the demo in [gallery](https://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all)

**Comment by zhaoYan1006** [comment]
https://gallery.echartsjs.com/editor.html?c=xYbNl-MPMl&v=1，this is the demo!  I find the limit number is not definite, it is always variable.  whatever thanks a lot.




------------------ 原始邮件 ------------------
发件人: "abigale Li"<notifications@github.com>;
发送时间: 2019年2月14日(星期四) 晚上9:12
收件人: "apache/incubator-echarts"<incubator-echarts@noreply.github.com>;
抄送: "289472157"<289472157@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/incubator-echarts] this force.edgeLength: [10, 100]attribute  does not work when  node count beyond 27  (#9915)




please provide a more detailed message, such as the ECharts option and the demo in gallery
