### ISSUE TITLE
官方示例中的柱状图，如果改变最后一个柱子的颜色，默认会触发图例颜色改变，求解决

### ISSUE THREAD

**Issue by wqzwh** [apache/echarts#9916]
## Issue Type

- [ ] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [x] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

### 简单描述问题：

官方示例中的柱状图，如果改变最后一个柱子的颜色，默认会触发图例颜色改变

### Expected Behavior

期望的效果是，如果强制给最后dataIndex为0的柱状附着颜色，图例颜色不变

### Current Behavior

图例的颜色默认变色了

![image](https://user-images.githubusercontent.com/16662470/52772106-ab4f0b80-3072-11e9-9259-40ba53cff971.png)

### Online Example

[示例运行](https://echarts.baidu.com/examples/editor.html?c=bar-y-category)

使用以下代码测试，默认我设置了curDataIndex为0，当curDataIndex设为别的值不会出现图例变色问题

```js
app.title = '世界人口总量 - 条形图';
var curDataIndex = 0
option = {
    title: {
        text: '世界人口总量',
        subtext: '数据来自网络'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    legend: {
        data: ['2011年', '2012年']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'value',
        boundaryGap: [0, 0.01]
    },
    yAxis: {
        type: 'category',
        data: ['巴西','印尼','美国','印度','中国','世界人口(万)']
    },
    series: [
        {
            name: '2011年',
            type: 'bar',
            data: [18203, 23489, 29034, 104970, 131744, 630230],
            itemStyle: {
                color: p => {
                  const dataIndex = p.dataIndex
                  if (curDataIndex === dataIndex) {
                    return '#999'
                  } else {
                    return 'yellow'
                  }
                }
            }
        },
        {
            name: '2012年',
            type: 'bar',
            data: [19325, 23438, 31000, 121594, 134141, 681807],
            itemStyle: {
                color: p => {
                  const dataIndex = p.dataIndex
                  if (curDataIndex === dataIndex) {
                    return '#999'
                  } else {
                    return 'red'
                  }
                }
            }
        }
    ]
};
```

## Environment

- ECharts version；ECharts 版本: {DESCRIBE_HERE}

- [ ] It happens only on certain browsers or operating systems. 对于特定浏览器或操作系统才会出现的问题，请提供相应环境信息：{BROWSER_VERSION_OR_OS_INFORMATION_HERE}

**Comment by Ende93** [comment]
这种出现多种颜色的情况建议用 `legend` 来设置吧，感觉不算 bug

**Comment by wqzwh** [comment]
@Ende93  怎么给单个图例设置颜色呢，只能给图例的文本设置吧

**Comment by Ende93** [comment]
哦，我记错了...

**Comment by Ende93** [comment]
也可以拆成多个 series 来解决

**Comment by wqzwh** [comment]
@Ende93  能按照官网写个实际测试的例子么
