### ISSUE TITLE
How can I remove style change on out of range map serie

### ISSUE THREAD

**Issue by 19mariusz95** [apache/echarts#9920]
## General Questions

- [x] Required: I have read the document and examples and tried to solve it by myself. （必填）我读过了文档和教程，并且曾试图自己解决问题。
- [x] Required: I have searched for similar issues and that didn't help. （必填）我搜索过 issue 但是没有帮助。
- [x] Required: I have tried with the latest version of ECharts and still have this problem. （必填）我试过最新版本的 ECharts，还是存在这个问题。

In this issue, I have provided information with: 在这个 issue 中我提供了以下信息：
- [x] Required: issue type；（必填）issue 类型
- [x] Required: one sentence description in issue details；（必填）一句话的问题描述
- [ ] Required: demo；（必填）能反映问题的例子（如果你想提问或报 bug）
- [x] Required: ECharts version；ECharts 版本

## Issue Type

- [x] I have a question to ask about *how to use ECharts to ...*；我想提问如何使用 ECharts 实现某功能
- [ ] I have a bug to report；我想要报 bug
- [ ] I have a feature to request, e.g.: *I'd like a new feature that ...*；我需要一个新功能
- [ ] I have a feature to enhance, e.g.: *The current feature should be improved in the way that ...*；我希望改进某个功能
- [ ] There's something wrong with the documents；文档有些问题
- [ ] Others, or I'm not sure which issue types to choose here；其他，或我不知道应该选什么类型

## Issue Details

When my map series data are in range I would like to keep original behavior so item lightness is increased but for out of range data I would like to remove the animation and set specific color for out of range data

I tried:
`
visualMap: {
        calculable: true,
        inRange: {
            color: ['#DAE2EE', '#0288D1'],
        },
        outOfRange: {
            color: '#00AA00',
        }
    },
`
but color changes.

Also I found out that if outOfRange.color is red, green or blue animation is disabled.

### Expected Behavior

There is no animation on out of range data

### Current Behavior

Brightness changes when mouse over out of range data

## Topics

- [ ] Legend
- [ ] Tooltip
- [x] Event
- [ ] Performance
- [ ] SVG
- [x] Map
- [ ] ECharts GL
- [ ] Third-party libraries, e.g.: Vue.js, React

## Environment

- ECharts version；4.2.0-rc.2

**Comment by Ovilia** [comment]
@19mariusz95 Have you defined `min` and `max` in `visualMap`?

**Comment by 19mariusz95** [comment]
@Ovilia Yes, I have. My full visualMapConfig is as follows:
{
        seriesIndex: 0,
        min: 0,
        orient: 'horizontal',
        itemHeight: 260,
        itemWidth: 10,
        left: 'center',
        padding: [5, 10, 5, 10],
        calculable: true,
        inRange: {
          color: ['#DAE2EE', '#0288D1']
        },
        outOfRange: {
          color: '#00AA00'
        }
      }

**Comment by Ovilia** [comment]
@19mariusz95 Please provide the full option. Thanks!

**Comment by 19mariusz95** [comment]
@Ovilia 
My option is
https://gist.github.com/19mariusz95/31271bd4b01393e73f9b55ca3d7ce170
Just put it in here:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=map-world-dataRange

**Comment by Ovilia** [comment]
I see. So you requested a feature that emphasis style should be configured (not changing opacity is one of the styles that can be configured). Is that right?

**Comment by 19mariusz95** [comment]
I would like to set out of range data to be in same color even if mouse cursor is over the area. At the same time I would like to be in range data to have the animation enabled - area changes its opacity when cursor over it.
