### ISSUE TITLE
VisualMap can not support multiple dimensions.

### ISSUE THREAD

**Issue by zteric** [apache/echarts#9925]
- [x] I am using English in this issue. 在这个 Issue 中我使用了英文（强烈建议）。

## General Questions

Issue Type: new feature
Description: VisualMap can not support multiple dimensions.
Version: 4.1.0
Chart Type: scatter

I am trying to highlight those points which is inside of a configured range(both 2 dimensions will be included) in scatter chart.
For example, if the x-axis value of this point is greater than 10 and y-axis value of this point is less than 5, mark this point with a different color.

I have already tried visualMap, but seems like it does not support multiple dimensions.

Any suggestions or advises would be appreciated.

**Comment by deqingli** [comment]
sorry, VisualMap don't support multiple dimensions yet.

**Comment by zteric** [comment]
> sorry, VisualMap doesn't support multiple dimensions yet.

Is there any plan to achieve this?

**Comment by 100pah** [comment]
Reasonable. 
The visualMap needed to support mapping customization.

**Comment by zteric** [comment]
> Reasonable. Thanks.
> The visualMap needed to support mapping customization.
> 
> And a temporary solution:
> Make an extra dimension to mark that whether use different color, and visualMap uses the dimension.

Thanks for your reply, I have tried your temporary solution to solve my problem already, and it is working properly for now.

**Comment by BigPackie** [comment]
> Reasonable. Thanks. The visualMap needed to support mapping customization.
> 
> And a temporary solution: Make an extra dimension to mark that whether use different color, and visualMap uses the dimension.

The temporary solution can only change the `itemStyle` and not the `lineStyle` between the items which does not looks nice especially if there are more items after each other that should be highlighted with different color. It would be really nice if one could access all dimensions at visual mapping, or at least make it as a parameter when definig `data` the same way as `itemStyle`.
