### ISSUE TITLE
Resize issue with force graph : nodes are out of the canvas

### ISSUE THREAD

**Issue by samfrach** [apache/echarts#9954]
### Version
4.2.0-rc.2

### Reproduction link
[https://echarts.baidu.com/examples/editor.html?c=graph-force](https://echarts.baidu.com/examples/editor.html?c=graph-force)

### Steps to reproduce
on the demo site : 
1) select only the first nodes in the legend (only the red box must be enabled)
2) then you have a central node with 7 satellites
3) zoom so that the "star" fills 100% of your canvas
4) resize your browser window to be for example 30% smaller
the nodes are out of the canvas.. and can't be seen anymore

### What is expected?
a way to get them black (even if the user has to click on a kind of "center the nodes" icon)

### What is actually happening?
it is out of the box

---
I am using it with ngx-echarts

**Comment by 100pah** [comment]
A "center the nodes" icon is not supported by default but can be made by echarts API.

**Comment by samfrach** [comment]
what is the name of the function to do that please ?

**Comment by samfrach** [comment]
please help needed !

I am looking for 2 solutions, either : 

1) would be to explain how to "center the nodes"
OR
2) how to zoom/focus on a specific node ... (expected result would be that the target node would be in the center and zoomed in ...)

thank you a lot
