### ISSUE TITLE
TreeMap刷新后回到当前展示路径

### ISSUE THREAD

**Issue by JohnnyRuiGe** [apache/echarts#9960]
### What problem does this feature solve?
目前使用dispatchAction方法的方式进行记忆路径跳转，但是有几次跳转动画。是否API有其他用法能直接展示记忆路径。

### What does the proposed API look like?
直接展示记忆路径，没有跳转动画

**Comment by 100pah** [comment]
虽然不太清楚 “记忆路径” 具体指什么。
但是，设置 `series.animation: false` 能阻止转换动画。

**Comment by JohnnyRuiGe** [comment]
可能是我的表述有问题，我的图形是类似官方Echarts Option Query的demo。需求是刷新后展示刷新前的层级页面。

**Comment by paradox010** [comment]
请教一下treemap有相关的dispatchAction吗？

**Comment by wangminli** [comment]
> 
> 
> 可能是我的表述有问题，我的图形是类似官方Echarts Option Query的demo。需求是刷新后展示刷新前的层级页面。

我也遇到同样的问题，请问你解决了么？求告知！
