### ISSUE TITLE
“保存为图”的右边被截断

### ISSUE THREAD

**Issue by wanghaoxing** [apache/echarts#9963]
### Version
4.2.1-rc1

### Steps to reproduce
所有图都是这样的

### What is expected?
“保存为图”的右边不被截断

### What is actually happening?
“保存为图”的右边被截断

**Comment by Ovilia** [comment]
@wanghaoxing Thanks for reporting. This should be an enhancement.

Reproducible example: https://gallery.echartsjs.com/editor.html?c=xrJZ60TVIg
![image](https://user-images.githubusercontent.com/779050/53149579-1061ae80-35e9-11e9-9ae6-3947089f415d.png)
