### ISSUE TITLE
title.textStyle.align not working

### ISSUE THREAD

**Issue by jeffersonswartz** [apache/echarts#9968]
### Version
4.2.1-rc1

### Reproduction link
[http://jsfiddle.net/jeffersonswartz/y8zs5coq/5/](http://jsfiddle.net/jeffersonswartz/y8zs5coq/5/)

### Steps to reproduce
Add title text and set textStyle.align as 'center'

### What is expected?
The title should be centered

### What is actually happening?
The text is left aligned which is default

**Comment by 100pah** [comment]
For the `title` component`, the `title.textAlign` can be used. But the `title.textStyle.align` does not work, which I should remove it from the doc.

And if intent to put the text in center, it can be achieved by setting `title.left: 'center'`.

**Comment by jeffersonswartz** [comment]
@100pah Thanks, The `title.left: center` worked but it centers both the title and subtext. 
How can I center the title alone without moving the subtext?

**Comment by 100pah** [comment]
@jeffersonswartz That is not supported

**Comment by jeffersonswartz** [comment]
> > How can I center the title alone without moving the subtext?
> > @jeffersonswartz swartz That is not supported.
> > But we can use two titles to get it.
> 
> ```
> option: {
>     title: [{
>          text: 'xxx'
>     }, {
>          text: 'xxx (original subtext)'
>     }]
> }
> ```

I tried that too but the second title object overlaps the first one. Is there a way to place the second title below the first one without overlapping?

**Comment by jeffersonswartz** [comment]
@100pah Any help on the overlapping issue
