### ISSUE TITLE
Echarts graph plots: specifying symbol per category

### ISSUE THREAD

**Issue by kovla** [apache/echarts#9979]
### Version
4.1.0-release

### Reproduction link
[https://stackoverflow.com/questions/54754423/echarts-4-graph-plot-specify-symbol-per-category](https://stackoverflow.com/questions/54754423/echarts-4-graph-plot-specify-symbol-per-category)

### Steps to reproduce
1. Specify a graph plot, with e.g. 2 categories. 
2. Specify symbol type (e.g. rect or diamond) for each category (not per data point)
3. See that these per-category settings have no effect. 
See the provided link to stackoverflow for a reproducible example (https://codepen.io/autarkie/pen/LqqZjM) 

### What is expected?
Expected is that symbol size and type can be specified per category, not per data point. 

### What is actually happening?
Both size and type of symbol parameters have no effect on the plot.

**Comment by 100pah** [comment]
This problem has been fixed and will be released in 4.3.0.
