### ISSUE TITLE
series tree left most label are cutting off

### ISSUE THREAD

**Issue by mohitsati14** [apache/echarts#9985]
### Version
4.1.0-release

### Steps to reproduce
Draw a tree chart. Give the root node a long name

### What is expected?
Chart should automatically move aside or should be display like this ...

### What is actually happening?
Label is cutting off

**Comment by mohitsati14** [comment]
Label cutting off:
<img width="782" alt="screenshot 2019-02-25 at 8 10 37 pm" src="https://user-images.githubusercontent.com/40822315/53344785-8a6f9b80-3939-11e9-87f3-e8206ccd7371.png">
Actual label:
<img width="370" alt="screenshot 2019-02-25 at 8 10 43 pm" src="https://user-images.githubusercontent.com/40822315/53344800-93f90380-3939-11e9-8446-77708227d49f.png">

**Comment by deqingli** [comment]
#11497
