### ISSUE TITLE
radar图设置富文本rich后triggerEvent失效

### ISSUE THREAD

**Issue by segmafrontend** [apache/echarts#9997]
### Version
4.2.1-rc1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xI5OU7NUef&v=1](https://gallery.echartsjs.com/editor.html?c=xI5OU7NUef&v=1)

### Steps to reproduce
1、在4.2.0-rc2中使用正常，升级到4.2.1-rc1后出现该bug
2、正常配置radar.triggerEvent=true，可以触发标签的点击事件
3、配置name的formatter和rich之后，再点击标签，无法触发事件

### What is expected?
配置formatter和rich后，标签仍然可以按triggerEvent的设置触发事件

### What is actually happening?
配置name的formatter和rich之后，再点击标签，无法触发事件

**Comment by pissang** [comment]
@100pah Please have a look at this problem.
